### ISSUE TITLE
Spurious "Could not find system (in)dependent libraries" messages

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#1009]
**Original date**: 2012/02/17

If an executable is built on one version of Linux - e.g. Ubuntu Jaunty with python2.6 - and then run on another version of Linux - e.g. Ubuntu Hardy with python2.5 - you get spurious messages:

```
Could not find platform independent libraries <prefix>
Could not find platform dependent libraries <exec_prefix>
Consider setting $PYTHONHOME to <prefix>[:<exec_prefix>]
```

(The same problem arises if e.g. an executable is built on Hardy/python2.5 and run on Jaunty/python2.6 - it's not dependent on which direction you go in.)

These messages can be suppressed by setting Py_FrozenFlag in Python to 1 (in much the same way as Py_NoSiteFlag is set).

I have a patch to attach to this ticket which suppresses the spurious messages.

Regards,

Vinay Sajip

**Comment by aquavitae** [comment]
It looks like this is a regression with Python 3. I'm getting exactly the same behaviour as described above with Python 3.5

**Comment by htgoebel** [comment]
@aquavitae This ticket is 8 years old and for PyInstaller 1.4. If you have a current problem, please open a new ticket giving all the information the ticket-template will ask you.
