### ISSUE TITLE
Error in function pyi_path_executable when calling a .exe as an Azure Webjob

### ISSUE THREAD

**Issue by ping13** [pyinstaller/pyinstaller#1066]
I want to deploy a `.exe` as an Azure WebJob (see this [blog entry by Scott Hanselman](http://www.hanselman.com/blog/IntroducingWindowsAzureWebJobs.aspx)
for some background). In theory, you just copy a `.exe` (or any other script) to
the Azure Website and it should run (again, see [Scott Hanselman's blog for details](http://www.hanselman.com/blog/IntroducingWindowsAzureWebJobs.aspx)).

My problem: The `.exe` works fine on my local machine and on some directory of the website's underlying Azure VM. However for the WebJob, the `.exe` is internally copied to another directory (in this case `C:\DWASFiles\Sites\~1walkalytics\Temp\jobs\continuous\servicecoverage\ymcoal51.2zm`). Here, my `.exe` gives an error "Cannot open self [...]", see log below with the debug flag turned on. It seems that the executable path in the bootloader is incorrectly calculated. 

My C knowledge is rusty and I'm not really a Win32 expert. Does anybody know how to resove this issue?

Thanks
Stephan

Here is the log when calling `calc_service_coverage.exe` in directory `C:\DWAS Files\Sites\~1walkalytics\Temp\jobs\continuous\servicecoverage\ymcoal51.2zm`

```
C:\DWASFiles\Sites\~1walkalytics\Temp\jobs\continuous\servicecoverage\ymcoal51.2zm> calc_service_coverage.exe
LOADER: executable is C:\DWASFiles\Sites\calc_service_coverage.exe
LOADER: homepath is C:\DWASFiles\Sites
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\DWASFiles\Sites\calc_service_coverage.exe
LOADER: Cannot open archive: C:\DWASFiles\Sites\calc_service_coverage.exe
LOADER: archivename is C:\DWASFiles\Sites\calc_service_coverage.pkg
LOADER: Cannot open archive: C:\DWASFiles\Sites\calc_service_coverage.pkg
Cannot open self C:\DWASFiles\Sites\calc_service_coverage.exe or archive C:\DWASFiles\Sites\calc_service_coverage.pkg
```

**Comment by codewarrior0** [comment]
`pyi_path_executable` was recently made more robust, and tries to use platform-specific functions to get the *real, absolute* path to the executable instead of relying on `argv[0]`. This issue is probably fixed. 

@ping13, if you could test this using the latest `python3` branch, your results would be helpful. (The branch also works with Python 2.7.)

**Comment by ThomasWaldmann** [comment]
Maybe related: #1634

**Comment by htgoebel** [comment]
@ping13 Any update? Otherwise I'm going to close this issue.

**Comment by ping13** [comment]
Thanks for the followup. I currently have no way (and time) to reproduce this issue - sorry.
I do appreciate your help here and I hope the issue is fixed. Thanks!
