### ISSUE TITLE
hook for flask and its extensions

### ISSUE THREAD

**Issue by fyears** [pyinstaller/pyinstaller#1071]
Hi.

In short:

I am using Windows 8. I haven't tested on other platforms. I found pyinstaller cannot detect `flask.ext.sqlalchemy` while generating exe files.

In details:

Here is what I've installed:

``` bash
> pip freeze
Flask==0.10.1
Flask-SQLAlchemy==2.0
PyInstaller==2.1.1dev-953f6e3
...
```

Here is the simplest example:

hello.py:

``` python
# hello.py
import flask.ext.sqlalchemy as s
t = s
print t.__str__
```

Of course, I can run `python hello.py` without any problems.

Run the following command in `cmd.exe` in Windows:

``` cmd
pyinstaller --noupx hello.py
```

Run the generated `dist\hello\hello.exe` in `cmd.exe` in Windows to see the debug information:

```
> dist\hello\hello.exe
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File ".\build\hello\out00-PYZ.pyz\flask.ext
hook", line 87, in load_module
ImportError: No module named flask.ext.sqlalchemy
```

**Comment by matiasbonet** [comment]
Did you manage to find the solution? I am trying to compile a flask_restful API and I have the same problem. I import like flask.ext.restful and add a hidden import "flask_restful"

Now I get an import error with another module called views but I adding it as a hidden import and does not work. 

a = Analysis(['test.py'],
             pathex=[basepath],
             hiddenimports=['flask_restful','flask_restful.views'],
             hookspath=None,
             runtime_hooks=None)

**Comment by thethomaseffect** [comment]
I'll get a chance to potentiallyimplement this starting this week, but it it ends up taking too long I'll have to give it a miss so any help from those experience with flask and it's many dependencies is most appreciated. I hope it's okay to use this issue to log progress, mainly because:

 - I can't do this publicly on Github, it's for work and the project is super sensitive info
 - If this does end up being scrapped and I don't have the time to package up everything into a pull request I can stick the files on a repo and let someone else fork and submit the pull request.

The good thing is while Flask is huge and it'll take time this will add support for a lot of widely used stuff!

**Comment by fyears** [comment]
@matiasbonet My ugly solution is just try to find all the hidden import and import them **explicitly** in the code file, not the special `spec` file for pyinstaller.

**Comment by matiasbonet** [comment]
Thanks! keep me posted with the updates. If I find a solution I will post it too.
@fyears, sorry for my ignorance, not sure what do you mean with import explicitly in the code file. You mean add each of the libraries manually to the main script?

This is how my imports look like:

from flask import Flask,request,render_template,url_for, redirect, Response
from flask.ext.restful import reqparse, abort, Api, Resource
from flask_restful_swagger import swagger

**Comment by fyears** [comment]
@matiasbonet 

Please look at my original post at the first floor. For example, I need `import flask.ext.sqlalchemy` in the main file, but pyinstaller said `No module named flask.ext.sqlalchemy`. So I have to write the code to import the hidden models explicitly in the main file, like,  `import flask_sqlalchemy._compat`.

In your example, maybe you could write these lines in your main file:
```python
from flask import Flask,request,render_template,url_for, redirect, Response
from flask.ext.restful import reqparse, abort, Api, Resource
from flask_restful_swagger import swagger

# additional lines for pyinstaller
import flask_restful as _
import flask_restful.views as _
```
So pyinstaller could detect ("know") `flask_restful` automatically.

**Comment by matiasbonet** [comment]
@fyears Thanks! I haven't seen your reply until now. I was developing and leaving this as an unsolve part!

I make it work with your solution. Compiling and adding any package he was asking me heheh definetly not the nicer solution but it worked!

#pyinstaller fixes
import flask_restful as _
import flask_restful.utils as _
import flask_restful.representations as _
import flask_restful.representations.json as _
import flask_restful.reqparse as _
import flask_restful.fields as _

Thanks again!

**Comment by htgoebel** [comment]
@matiasbonet We'd appreciate if you could write a hook then. Doing this is easy, just take PyInstaller/hooks/hook-rawpy.py as an example.

**Comment by matiasbonet** [comment]
@htgoebel I tried using the hidden imports but it wasn't working. Not sure how to migrate my solution to this format. 

I tried before generating the spec file and adding 
hiddenimports = ['flask_restful']

But then I got no error when generating exe but the exe wasn't working or doing anything.

If I have time next week I will do more testing on this solution and add I will try to generate the hook.

**Comment by micmica** [comment]
Have you find the solution for this one? I have the same problem with flask.ext and with flask_bootstrap, I would like to write I hook but I'm really new with this. Do you know come example of hook where I can see how to add directory from module with html documents.
In flask_bootstrap I have directory template that pyinstaller doesn't recognize even if I add to the hiddenimports flask_bootstrap....?

**Comment by chriddyp** [comment]
Any progress on this issue?

**Comment by bluebad** [comment]
I met the same problem. When I run target exe, it raise an error "Import Error: Module SocketServer not found.Then I follow hook example, write a simple hook: 
`from PyInstaller.utils.hooks import collect_submodules
hiddenimports = ['SocketServer']
`
Then re run pyinstaller. This time, it worked. Post out, hope this help some one.

**Comment by Legorooj** [comment]
Stale
