### ISSUE TITLE
Onefile option does not work with matplotlib

### ISSUE THREAD

**Issue by alex-piccione** [pyinstaller/pyinstaller#1074]
Hi,

Problem: generated .exe file does not work, it open and close immediately. the "folder" version of generated .exe works (not --onefile option).

Ambient: Windows 7, Python v2.7.x, PyInstaller 2.1 (last downloadable windows installer)

I use in the "main" python file import to make matplotlib working:
from PyInstaller.hooks.hookutils import matplotlib_backends

I thought matplotlib was "fully" supported, also for --onefile option, it is not?

Alessandro

**Comment by nithinp** [comment]
I just tried it now.. Mathplotlib is not working with pyinstaller.. :(

**Comment by nithinp** [comment]
it shows a runtime error

         RuntimeError: The WebAgg backend requires Tornado.

**Comment by htgoebel** [comment]
So please provide more information as described in <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>.
