### ISSUE TITLE
64-bit executable does not run on 64-bit Windows

### ISSUE THREAD

**Issue by dsoprea** [pyinstaller/pyinstaller#1076]
I don't quite understand this error, and I couldn't seem to find even a compatible reference to it on the Internet, much less a discussion/solution:

```
This version of C:\Users\Administrator\Desktop\xyz.exe is not compatible with the version of Windows you're running. Check your computer's system information to see whether you need a x86 (32-bit) or x64 (64-bit) version of the program, and then contact the software publisher.
```

I tried it with and without "--onefile" (the only special parameter that I'm passing into *pyinstaller", aside from the *spec* file).

Any suggestions?

**Comment by codewarrior0** [comment]
No system information, no python version or pyinstaller version, no response to request for environment info. Open a new issue if you still have this problem.

https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
