### ISSUE TITLE
pyinstaller is unable to load external module

### ISSUE THREAD

**Issue by afterhill** [pyinstaller/pyinstaller#1080]
Hi, I use pyinstall to EXE my PyQt4 application. After my application is launched, it will dynamically load the external .PY modules through the builtin `__import__(mod_name)`. The loaded modules also refer to some other shared libs. I put these shared libs in the sys.path after the EXE is launched and I also can see the sys.path includes the shared libs path throught the console output by pyinstaller. 

However the question is: the shared lib CANNOT be loaded and always get complained that the shared lib module is not available.

I copied the sys.path into the normal Python environment, it is working without any issue. I don't know where is the root cause? why the `__import__()` is not working under pyinstaller environment even the sys.path is set up properly.

**Comment by keymandll** [comment]
I've got the same or at least a very similar issue. I would like to be able to import modules external to the pyinstaller packaged code dynamically. (e.g. modules installed using pip) Even though I set sys.path to include the site-packages folder where the installed modules reside, the pyinstaller packed app is not able to find them. Not sure how relevant it is but I'm trying to load the modules using `importlib.import_module`, e.g.:

`
m_mod = importlib.import_module("package.module")
`

The pyinstaller spec file is very simple as I'm just experimenting at the moment. I've included it below.

`# -*- mode: python -*-

from distutils.sysconfig import get_python_lib

block_cipher = None

def get_package_paths():
    paths = ['.', './packages']
    paths.append(get_python_lib(standard_lib=True))
    paths.append(get_python_lib(standard_lib=False))
    return paths

a = Analysis(['packages/fl-engine-service/flengine/engine.py'],
             pathex=get_package_paths(),
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='engine',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               name='engine')
`
