### ISSUE TITLE
Matplotlib compatibility

### ISSUE THREAD

**Issue by moonshoes87** [pyinstaller/pyinstaller#1088]
Pyinstaller on Mac 10.9.5 doesn't work with this minimal matplotlib script.  The version of matplotlib is: 1.1.0.  The Python distribution is EPD 7.3-2 (32 bit).  Pyinstaller: 2.1.  Here is the script:

import matplotlib
import matplotlib.pylab as pylab

x = pylab.linspace(0,20,1000)
y = pylab.sin(x)
pylab.plot(x,y)
pylab.show()

Pyinstaller.py runs through, and the executable will start, but it crashes as soon as you mouse-over the plot with this error:  MKL FATAL ERROR: Cannot load <mkl-thread-layer>

This error does not happen when the script is run without being, or when pyinstaller is run on Windows.  I found other reports of people having this problem, so I don't think it's specific to my setup.  Any thoughts?

**Comment by matysek** [comment]
Closing. Author did not respond for a long time.
