### ISSUE TITLE
Add python-firebase support

### ISSUE THREAD

**Issue by TTimo** [pyinstaller/pyinstaller#1098]
https://github.com/mikexstudios/python-firebase for https://www.firebase.com/

Pure python module but uses multiprocessing a lot. I tried a simple script, a obtained an exe, but it turned into a fork bomb when I tried to execute it.

**Comment by htgoebel** [comment]
If somebody wants to implement this, feel free to provide a pull-request

**Comment by Legorooj** [comment]
Closing - stale
