### ISSUE TITLE
Merge redundant constants

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1103]
bjones1 wrote https://github.com/pyinstaller/pyinstaller/commit/b083d4db3b5f7394bae4f379fb336f15a3735830#commitcomment-8640028

> I believe having three constants here (PY_EXECUTABLE_SUFFIXES, PY_EXTENSION_SUFFIXES, PY_IGNORE_EXTENSIONS, ) is redundant -- why not combine these into one (keep only PY_EXTENSION_SUFFIXES, which comes from Python's standard lib, instead of PyInstaller)?

**Comment by jack17529** [comment]
ok i can help

**Comment by xoviat** [comment]
Submit a PR.

**Comment by jack17529** [comment]
Can someone help me in understanding the lines-

is_pkg_statement = 'import %s as p; print hasattr(p, "__path__")'
     is_package = eval_statement(is_pkg_statement % package)
     assert is_package
 
     file_attr = get_module_file_attribute(package)

**Comment by xoviat** [comment]
```
is_pkg_statement = 'import %s as p; print hasattr(p, "path")'
is_package = eval_statement(is_pkg_statement % package)
assert is_package
file_attr = get_module_file_attribute(package)
```

I'm not sure how much more clear this can be: `assert is_package` means the code checks whether `p` is a package and raises an `AssertionError` if it isn't. Look:

```
Python 3.6.0 (v3.6.0:41df79263a11, Dec 23 2016, 08:06:12) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.path
<module 'ntpath' from 'C:\\Program Files\\Python36\\lib\\ntpath.py'>
>>>
```

`pkg_base = remove_suffix(pkg_dir, package.replace('.', os.sep))`

Think:

1. `.replace` is a string method, so you know that `package` must be a string.
2. Intuitively, `package` would be a package name in the format of `a.b.c`, so calling `replace` would return `a\b\c`. 
3. `pkg_dir` is probably the full path to the package.
4. `remove_suffix` probably removes a suffix, so it's not a leap to infer that this returns the directory in `sys.path` that contains the package.

**Comment by htgoebel** [comment]
Gents, may I ask you to continue with the Python tutorial somewhere else. This is not a support forum, but an issue discussion system. Thanks.

**Comment by jack17529** [comment]
Syntactically I too understood whole of the code @xoviat . I just wanted to know what does it meant from the context importantly this line - 'import %s as p; print hasattr(p, "__path__")'
which was not explained.

Please send that to my mail 15ucs130@lnmiit.ac.in .

Sorry @htgoebel.
