### ISSUE TITLE
IOError: [Errno 9] Bad file descriptor when using PyInstaller with DaemonContext

### ISSUE THREAD

**Issue by marcinbarczynski** [pyinstaller/pyinstaller#1108]
PyInstaller: version 2.1
Platform: Linux icore-05 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

I generated an executable (--onefile) from the following python code:

```python
import daemon
import sys

ctx = daemon.DaemonContext(stdout=sys.stdout, stderr=sys.stderr)
with ctx:
    pass
```

daemon module is an implementation of https://www.python.org/dev/peps/pep-3143/ from python-daemon package.

When the program finishes, it prints out an error:
```
close failed in file object destructor:
IOError: [Errno 9] Bad file descriptor
```
The same happens with --onedir option.

This is because bootloader leaves 3 extra open descriptors when starting to execute python code. All of them point to the executable file itself. By default, DaemonContext closes all open descriptors right after fork. So, when program finishes, bootloader tries to close one of the open descriptors which causes the error message.

Are the open descriptors really necessary when running python code? Why is only one of them explicitly closed at the end of the program?

If they are required, I think that the behaviour is worth documenting and creating a recipe for DaemonContext. The recipe is simple:
```python
fds_to_myself = []
if getattr(sys, 'frozen', False):
    fds_to_myself.extend([of.fd for of in  psutil.Process(os.getpid()).open_files() 
            if of.path == sys.executable])

ctx = DaemonContext(
    ...
    files_preserve=fds_to_myself
)
```

What do you think?

**Comment by chuanliu77** [comment]
This is great! In my case, I need to find all the open files to reserve, which works great!

**Comment by htgoebel** [comment]
@marcinbarczynski You are welcome submitting this to the wiki.

**Comment by tallforasmurf** [comment]
Added wiki page Recipe python-daemon package
