### ISSUE TITLE
Inhibit meaningless combinations of command-line arguments

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1110]
As issue #794 showed, people may use e.g. `--onefile` together with a specfile, which is useless because the specfile is already generated an will be used unchanged.

So if a specfile is given, we should inhibit most (if not all) options from `makespec`.

@matysek IMHO this can wait until the switch to argparse #686, which already implements support for conflicting arguments. What do you thing?

**Comment by htgoebel** [comment]
This should be easy to implement when changing from optparse to argparse.

**Comment by htgoebel** [comment]
Implementing this is not *that* easy, since the make-spec options are added in `building/makespec.py`, but the `scriptname` argument is added in `__main__.py`. Also when doing a quick internet search, I did not find a simple solution for specifying conflicts. `argparse` seams to only support mutal-exclusive groups. And argparse does not support nested groups, so calling `PyInstaller.building.makespec.__add_options()` which a mutex-groups does not work.

Seams we need to collect all makespec-options and then interate over them checking if any of the options has been given. If we can not check if they are give, we could check if they differ from their default.

**Comment by htgoebel** [comment]
If a spec-file is given, we should also inhibit use of options which are ignored in this case.

**Comment by Legorooj** [comment]
This has been implemented( Pretty sure anyway; the docs say so.)
