### ISSUE TITLE
fix "--onefile" for Python3

### ISSUE THREAD

**Issue by jhyland** [pyinstaller/pyinstaller#1119]
Hi,

While the "--onefile" option works in the Python2 version of pyinstaller, this does not seem to be working intuitivley for Python3 at least for me anyways. When compling a simple py file via "pyinstaller --onefile myfile.py" for the Python3 version of pyinstaller, the message "libexpat.so.1 could not be extracted!" when the compiled file is executed. Using the same technique for the Python2 version of pyinstaller runs the compiled file correctly.

**Comment by matysek** [comment]
Related pull request #1137

**Comment by jarondl** [comment]
Thank you very much @matysek
