### ISSUE TITLE
Remove usage of `_mktemp`

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1121]
1. We *must not* use `_mktemp`, because it is limited to 26 files. (See http://msdn.microsoft.com/en-us/library/34wc6k1f.aspx: the template will be replaces by one letter and 5-digits process number and "mktemp can create a maximum of 26 unique file names for any given combination of base and template values")
2.  `_mktemp` is deprecated, we should consider using `_mktemp_s` instead (see code example in above mentioned page)

**Caveat:** `_mktemp_s` is still restricted to 26 filenames per process. Isn't there a different implementation?

How we currently use the `mktemp`-family:
- In stb.h `stb_fopen` (which seams to be unused)
 - #ifdef _MSC_VER: [`_mktemp`](https://github.com/pyinstaller/pyinstaller/blob/python3/bootloader/src/stb.h#L5424, actually this is `stb_mktemp`, which is just an alias)
 - #ifndef _MSC_VER: [`mkstemp`](https://github.com/pyinstaller/pyinstaller/blob/python3/bootloader/src/stb.h#L5434)
- In pyi_path.c `pyi_path_fopen`:
 - #ifdef _WIN32: [`_mktemp`](https://github.com/pyinstaller/pyinstaller/blob/python3/bootloader/src/pyi_path.c#L305)
 - #ifndef _WIN32: [`mkstemp`](https://github.com/pyinstaller/pyinstaller/blob/python3/bootloader/src/pyi_path.c#L315)

**Comment by matysek** [comment]
Related pull request #1137

**Comment by matysek** [comment]
I removed the code that was using it. The code was no longer needed.
