### ISSUE TITLE
Please remove `bootloader/src/stb.h` - it is unused

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1122]
Hi @matysek 

the file `bootloader/src/stb.h` is no longer used. Please remove it. It's existence took me time when investigating issue 11119.  (I'm not doing it because you are the master of the bootloader ;-)

```
$ cd bootloader
$ grep -lr stb_ 
src/stb.h
src/pyi_global.c
$ grep -r stb_ src/pyi_global.c
 * All functions starting with 'stb_' prefix are from this toolbox.
$ 
```

**Comment by matysek** [comment]
Related pull request #1137
