### ISSUE TITLE
Add "command" for collecting data-files to `build.py`

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1125]
We could help users collecting their own data-files if we'd add a "command" named e.g. "Datafiles".

There is already such a thing in [`tests/basic/test_onefile_pkg_resources.spec`](https://github.com/pyinstaller/pyinstaller/blob/v2.1/tests/basic/test_onefile_pkg_resources.spec).

After implementation we should describe it [in the manual](http://pythonhosted.org/PyInstaller/#adding-files-to-the-bundle) end eliminate such code from the tests.

**Comment by codewarrior0** [comment]
:+1: 

To collect my data files, for some reason I am using a hookfile for my project modules and calling `hookutils.collect_data_files` on them.

**Comment by htgoebel** [comment]
Closed by #1460.
