### ISSUE TITLE
PyInstaller3: error running one-file executable

### ISSUE THREAD

**Issue by thorstenkampe** [pyinstaller/pyinstaller#1141]
Running a one-file Linux executable created with PyInstaller from the 
Python3 branch results in
```
libexpat.so.1 could not be extracted!
```

**Comment by matysek** [comment]
It could be that because of #1119 the linux bootloader should be also recompiled.

**Comment by matysek** [comment]
After recompiling linux bootloaders onefile mode should work.

**Comment by thorstenkampe** [comment]
Recompiling the bootloader solved this issue
