### ISSUE TITLE
File create from pyinstaller lock it self on windows even cant rename

### ISSUE THREAD

**Issue by YueLunGames** [pyinstaller/pyinstaller#1144]
Hello, looks like file create from pyinstaller will lock it self when running, even cant rename.
I want to known is there a way to allow it.

**Comment by htgoebel** [comment]
Please provide more information, this is much to less for even thinking about an answer. See
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by YueLunGames** [comment]
I think I already explain very clear.
maybe you need a example?
1. create 1.py and use pyinstaller generate 1.exe on windows
2. run 1.exe
3. now we can't remove or rename 1.exe until it exit

so it's the problem about file locking
http://en.wikipedia.org/wiki/File_locking
http://msdn.microsoft.com/en-us/library/windows/desktop/aa363858%28v=vs.85%29.aspx

I think you may need close file handle after extra python files.

**Comment by htgoebel** [comment]
YueLunGames submitted a patch in  #1145
