### ISSUE TITLE
hookutils test for QML should use try/except

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1148]
In hookutils.qt5_qml_dir() (line 328) there is the following test,

     qmldir = subprocess.check_output(["qmake", "-query",
                                      "QT_INSTALL_QML"]).strip()
    if len(qmldir) == 0:

However, the command qmake -query QT_INSTALL_QML returns a nonzero return code when QML is not installed. This causes program termination with a subprocess.CalledProcessError exception. The code should use a try/except, e.g.

    try:
         qmldir = subprocess.check_output(["qmake", "-query",
                                      "QT_INSTALL_QML"]).strip()
    except subprocess.CalledProcessError:
        qmldir = ''
    if len(qmldir) == 0:

etc.

**Comment by tallforasmurf** [comment]
n.b. this is in the python3 branch

**Comment by htgoebel** [comment]
Thanks for reporting

**Comment by jarondl** [comment]
Using the updated python3 branch, I get a syntax error:

    from PyInstaller.utils.hooks.hookutils import collect_submodules
    File "test_venv\lib\site-packages\PyInstaller\utils\hooks\hookutils.py", line 329
    except IOError,:
                  ^
    SyntaxError: invalid syntax

I'll submit a PR in a moment
