### ISSUE TITLE
invalid "rstrip" call in hook_utils qt5_qml_plugins_binaries()

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1149]
hook_utils line 352, 

    def qt5_qml_plugins_binaries(dir):
        """Return list of dynamic libraries formatted for mod.binaries."""
        import string
        binaries = []
        qmldir = qt5_qml_dir()
        dir = string.rstrip(dir, os.sep)

Program terminates with "AttributeError: 'module' object has no attribute 'rstrip'". It is not clear to me what this is trying to do but "rstrip" is a method of the bytes module, not of the string module. Suggest perhaps this could use os.path.dirname() to get everything to the left of the last separator?

**Comment by tallforasmurf** [comment]
n.b. this is in the python3 branch. Don't see how to put that label on it.

**Comment by htgoebel** [comment]
Thanks for reporting.
