### ISSUE TITLE
Pyinstaller and path issue with noconsole

### ISSUE THREAD

**Issue by Elite** [pyinstaller/pyinstaller#1150]
I created an GUI for https://github.com/rg3/youtube-dl and it works fine when executed from python file, however if I pack it using pyinstaller with one file option it downloads the video but fails to convert it using ffmpeg (one copy of which is in the application folder and another on OS path).

I noticed if I allow pyinstaller to open a console window http://pythonhosted.org/PyInstaller/#id23 it works fine and executes ffmpeg. Any ideas how to fix this?

**Comment by htgoebel** [comment]
I assume, this is a `ffmpeg` issue: Maybe it requires stdin or std out to be a tty.
