### ISSUE TITLE
wscript: `lsbcc` should be searched in $PATH

### ISSUE THREAD

**Issue by fake-name** [pyinstaller/pyinstaller#1151]
I'm trying to build the bootloader on linux (Ubuntu 12.04) using python 3.

The issue is that the search path for the `lsbcc` binary is apparently only `['/opt/lsb/bin']`. This is a problem since `lsbcc` on ubuntu gets installed to `/usr/bin`. 

This means that even if you have `lsbcc` installed, and it's on your `$PATH`, it's still not found by `waf` because it's not searching in the proper place.

I created `lsb`/`bin`, and symlinked `/usr/bin/lsbcc`, and it found it correctly.

It then has other compilation issues, but that's a separate issue.

**Comment by htgoebel** [comment]
Yo can specify the path using the option `--lsbcc-path`, see `./waf --help`.

**Comment by fake-name** [comment]
Sure, that's fine, but the point is all the *other* dependencies are searched for much more broadly, and apparently the system *could* just use `$PATH`, so why not do that?

**Comment by htgoebel** [comment]
You are right on this :-)

**Comment by matysek** [comment]
PyInstaller is already doing that.
