### ISSUE TITLE
Execute error when path contains wide character.

### ISSUE THREAD

**Issue by YueLunGames** [pyinstaller/pyinstaller#1162]
Version of python: 2.7 32bit
Version of pyinstaller: download from git
System: windows 7 64bit

How to reproduce:
1: pack script to executable, run
pyinstaller.py 1.py

2: put 1.exe to c:\一二三 and run
Then an exception will throw:
ImportError: Can't load frozen modules

I found the encoding of string pyz_filepath in pyi_importers.__init__ is utf-8.
But windows require file path encoding must be ansi.
I didn't known how to fix it yet.

**Comment by matysek** [comment]
This is the limitation of Python 2 on windows. There is implemented workaround that converts path to 'Short pathname': http://msdn.microsoft.com/en-us/library/windows/desktop/aa364989(v=vs.85).aspx

However, this is not perfect. Some paths cannot be converted to short name e.g. chinese characters. There is nothing more we could do in this regard for python 2.

We should concentrate the effort on python3 that uses wchar everywhere.

**Comment by YueLunGames** [comment]
I still hope it can get fix.
Because old version of pyinstaller (1.5.1) didn't have this problem.
I try to fix my self by add
```pyz_filepath = pyz_filepath.decode("utf-8").encode(sys.getfilesystemencoding())```
But no luck because pyi_importers can't import codec module.

**Comment by htgoebel** [comment]
@matysek I assume you wanted to close this issue, as you marked it as "won't fix"?!

**Comment by matysek** [comment]
@YueLunGames if you are able to fix this please create a pull request.
