### ISSUE TITLE
Problem with bootloader building executable using cygwin

### ISSUE THREAD

**Issue by jjtapia** [pyinstaller/pyinstaller#1165]
I'm trying to build a Python executable using cygwin. The same code has already been built with pyinstaller and verified to work using both MacOSX  10.10 and the latest Linux Ubuntu version. I suspect the problem has something to do with the bootloader, but I'll elaborate on what I have tried so far:

Current specs:
-python 2.7.8
-repository pyInstaller (commit 707e2e62a80aef2f8f1c0628250ae8e59c779cf0)
-spec file: http://pastebin.com/7cztdNt5

The first thing I encountered was pyinstaller being unable to find the libpython library. I had to modify bindepend.py line 726 from
names = ('libpython%d%d.dll' %pyver,)
to
names = ('libpython%d.%d.dll' %pyver,)

Doing this enabled pyinstaller to find the library in question. Additionally I also compiled a bootloader for cygwin as instructed in the bootloader folder. After this pyinstaller created a file, however when running it I get the message:

'Cannot open self   or archive  .pkg'

If there is any additional information I can provide to help solving this issue I'll be more than glad to help.

**Comment by jjtapia** [comment]
Activating the debug flag throws the following information:

LOADER: executable is
LOADER: homepath is
LOADER: _MEIPASS2 is NULL
LOADER: archivename is 
LOADER: Cannot open archive
LOADER: archive name is .pkg
LOADER: Cannot open archive .pkg
Cannot open self or archive .pkg

So it'd seem to be failing to set any of the path variables? Does this sound familiar to anyone?

**Comment by matysek** [comment]
> LOADER: Cannot open archive

This probably means that pyinstaller was not able to append python modules to the exe file.

Please look at these wiki pages:
https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by jjtapia** [comment]
I see. Do you think there could be any other reason as to why this would happen other than having missing modules? I've been comparing the list of modules I get both using archive_viewer and COLLECT in spec so I get a directory instead of an executable and compared that to the ones I get in the Linux and MacOSX executables that were correctly assembled, however I cannot pinpoint that is critically missing from the cygwin implementation.

**Comment by jjtapia** [comment]
Ok, I think I found the problem. When defining a name for the executable inside EXE in the spec file

name='sbmlTranslator.exe',

The name has to explicitly have the extension '.exe' when using cygwin. Failing to do this will result in the problem described above.
