### ISSUE TITLE
qt5_plugins directory is not created

### ISSUE THREAD

**Issue by AcidWeb** [pyinstaller/pyinstaller#1166]
**Python3 branch** - Python 3.4.1 32bit

Tested both on Windows and Linux. Using single file and single directory output.
In all cases qt5_plugins directory is not part of output bundle - and that obviously cause application to crash.

When qt5_plugins is created manually everything start to work correctly.

**Comment by matysek** [comment]
I found similar issue with other hooks too.

**Comment by AcidWeb** [comment]
PyInstaller 3.0 fixed it this issue.

Additionally on Windows some QT plugins are broken by UPX compression. That cause error like they are missing. Remember that if you ever have similar problem reported.
