### ISSUE TITLE
"SIP developer tools" break PyInstaller on Windows

### ISSUE THREAD

**Issue by AcidWeb** [pyinstaller/pyinstaller#1167]
**Python3 branch** - Python 3.4.1 - Windows only.

If during PyQT5 installation user select "SIP developer tools" PyInstaller can't bundle SIP properly anymore.

No errors during bundle creation. Output apps fail due lack of SIP.

**Comment by AcidWeb** [comment]
After additional research I discovered that problem is not caused by 64 bit Python.

Updated bug description.

**Comment by AcidWeb** [comment]
Problem was not caused by 64bit Python - Changed bug description.

**Comment by codewarrior0** [comment]
This is almost certainly related to #1267

**Comment by AcidWeb** [comment]
Problem no longer occurs when using Python 3.4 + PyInstaller 3.0 + PyQt5 5.5.1.
