### ISSUE TITLE
Gtk3 python app

### ISSUE THREAD

**Issue by lamazavr** [pyinstaller/pyinstaller#1169]
Hi, I am trying to build simple Gtk3 app on Fedora Linux with 2.1.1dev-707e2e6 pyinstaller.
It builds fine (as I can see), but when I start it:
ImportError: PyCapsule_Import could not import module "datetime"

Here is an archive with logs and my files: http://blablacode.ru/files/installer.tar.gz
Thanks, sorry for my English.

**Comment by htgoebel** [comment]
Please follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
