### ISSUE TITLE
Can not capture incoming packet with raw_socket at Windows (python 2.7.9, pyinstaller 2.1)

### ISSUE THREAD

**Issue by anch0vy** [pyinstaller/pyinstaller#1178]
my code:

```python
import socket

HOST = socket.gethostbyname(socket.gethostname())
s1 = socket.socket(socket.AF_INET, socket.SOCK_RAW)
s1.bind((HOST, 0))
s1.ioctl(socket.SIO_RCVALL, socket.RCVALL_ON)
print HOST

while True:
	packet,(IP,_)=s1.recvfrom(65535)
	print IP
```
command
`pyinstaller --clean -y sockettest.py`

And run at administrator console, but i can only capture outgoing packet.

What should i do?

![default](https://cloud.githubusercontent.com/assets/6133895/5992149/d7cf0852-aa5e-11e4-9129-dc66b8794bb6.PNG)

**Comment by htgoebel** [comment]
I can not see why this problem is related to PyInstaller.
Please have a look at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
