### ISSUE TITLE
Onefile ".exe" made with Pyinstaller returns "requests.exceptions.SSLError: [Errno 2] No such file or directory"

### ISSUE THREAD

**Issue by ALEERQUESON2DIAS** [pyinstaller/pyinstaller#1179]
Hello,

I'm using PYinstaller  v2.1 with Python 2.7.9 to made and onefile exe qith an application (python-onedrive 15.02.2 - https://pypi.python.org/pypi/python-onedrive). All is under Windows 7 PRO 64 bits but Python 2.7 and accesoriies are in 32 bit.

I have read all instructions and I have checked the recommendations on bugs and read open bugs. 

I reach this platform as suggested by developper of application as you can see in
https://github.com/mk-fg/python-onedrive/issues/48

The aplication works O.K. as a ".py" module as you can see following
C:\>onedrive-cli -c b:/OD.lcrc ls
- ALQS2D
- Documentos
- Documents
- Fotos
C:\>

After building an --onefile .exe with the aplication, when executing the resultant .exe  in the same or different machine, I have given errors in <<requests>> module as show following
 
C:\Python27\Lib\site-packages\onedrive\dist>cli_tool -c B:/OD.lcrc ls
Traceback (most recent call last):
File "", line 397, in 
File "", line 322, in main
File "C:\Python27\Lib\site-packages\onedrive\build\cli_tool\out00-PYZ.pyz\onedrive.api_v5", line 6
15, in listdir
File "C:\Python27\Lib\site-packages\onedrive\build\cli_tool\out00-PYZ.pyz\onedrive.api_v5", line 3
58, in listdir
File "C:\Python27\Lib\site-packages\onedrive\build\cli_tool\out00-PYZ.pyz\onedrive.api_v5", line 3
33, in call
File "C:\Python27\Lib\site-packages\onedrive\build\cli_tool\out00-PYZ.pyz\onedrive.api_v5", line 1
64, in request
onedrive.api_v5.ProtocolError: (None, '[Errno 2] No such file or directory')

C:\Python27\Lib\site-packages\onedrive\dist>

I have verified the building process and used pyi-archive_viewer and it seems to be all O.K. No missing modules and error messages.

Thanks a lot for your atenttion.

Next the result of binding proccess

C:\Python27\Lib\site-packages\onedrive>pyinstaller --onefile cli_tool.spec
46 INFO: Testing for ability to set icons, version resources...
77 INFO: ... resource update available
77 INFO: UPX is not available.
108 INFO: Processing hook hook-os
233 INFO: Processing hook hook-time
248 INFO: Processing hook hook-cPickle
326 INFO: Processing hook hook-_sre
451 INFO: Processing hook hook-cStringIO
560 INFO: Processing hook hook-encodings
576 INFO: Processing hook hook-codecs
1060 INFO: Extending PYTHONPATH with C:\Python27\Lib\site-packages
1060 INFO: checking Analysis
1075 INFO: building because C:\Python27\lib\site-packages\onedrive\api_v5.py changed
1075 INFO: running Analysis out00-Analysis.toc
1075 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
3572 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none ...
3572 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21
022.8_none_bcb86ed6ac711f91.manifest
3588 INFO: Searching for file msvcr90.dll
3588 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb
86ed6ac711f91\msvcr90.dll
3588 INFO: Searching for file msvcp90.dll
3588 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb
86ed6ac711f91\msvcp90.dll
3588 INFO: Searching for file msvcm90.dll
3588 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_bcb
86ed6ac711f91\msvcm90.dll
3697 INFO: Analyzing C:\Python27\lib\site-packages\PyInstaller\loader\_pyi_bootstrap.py
3697 INFO: Processing hook hook-os
3713 INFO: Processing hook hook-site
3743 INFO: Processing hook hook-encodings
3852 INFO: Processing hook hook-time
3868 INFO: Processing hook hook-cPickle
3947 INFO: Processing hook hook-_sre
4086 INFO: Processing hook hook-cStringIO
4195 INFO: Processing hook hook-codecs
4664 INFO: Processing hook hook-pydoc
4835 INFO: Processing hook hook-email
4902 INFO: Processing hook hook-httplib
4948 INFO: Processing hook hook-email.message
5026 INFO: Analyzing C:\Python27\lib\site-packages\PyInstaller\loader\pyi_importers.py
5089 INFO: Analyzing C:\Python27\lib\site-packages\PyInstaller\loader\pyi_archive.py
5151 INFO: Analyzing C:\Python27\lib\site-packages\PyInstaller\loader\pyi_carchive.py
5198 INFO: Analyzing C:\Python27\lib\site-packages\PyInstaller\loader\pyi_os_path.py
5214 INFO: Analyzing cli_tool.py
5526 INFO: Processing hook hook-pywintypes
6290 INFO: Processing hook hook-xml
6368 INFO: Processing hook hook-xml.sax
6399 INFO: Processing hook hook-pyexpat
6447 INFO: Hidden import 'requests' has been found otherwise
6447 INFO: Hidden import 'codecs' has been found otherwise
6447 INFO: Hidden import 'encodings' has been found otherwise
6463 INFO: Looking for run-time hooks
7101 INFO: Using Python library C:\Windows\system32\python27.dll
7257 INFO: C:\Python27\Lib\site-packages\onedrive\build\cli_tool\out00-Analysis.toc no change!
7273 INFO: checking PYZ
7273 INFO: building because C:\Python27\lib\site-packages\onedrive\api_v5.pyc changed
7273 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
9628 INFO: checking PKG
9628 INFO: building because C:\Python27\Lib\site-packages\onedrive\build\cli_tool\out00-PYZ.pyz chan
ged
9628 INFO: building PKG (CArchive) out00-PKG.pkg
12111 INFO: checking EXE
12111 INFO: rebuilding out00-EXE.toc because cli_tool.exe missing
12111 INFO: building EXE from out00-EXE.toc
12174 INFO: Appending archive to EXE C:\Python27\Lib\site-packages\onedrive\dist\cli_tool.exe

**Comment by mk-fg** [comment]
It's all my fault that I haven't been clear on this in the linked python-onedrive issue, but I meant opening an issue with another module (requests), which raises that error in the first place, when ran from PyInstaller bundle, my apologies.

It's not my call, of course, but maybe this issue should be just closed as misdirected.

**Comment by ALEERQUESON2DIAS** [comment]
As the previous entry said, my excuses for opening this issue for PYinstaller.

Please close it and excuses.
