### ISSUE TITLE
fix hook-cryptography to put *.pyd files next to the exe file

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1185]
Cryptography hook does not put *.pyd files next to the exe file but to the path like

```
./dist/sample/sample.exe
./dist/sample/cryptography/module.pyd
```

PyInstaller convention is to put them to filename like: /dist/sample/cryptography.module.pyd and not into  cryptography subdirectory.

**Comment by matysek** [comment]
this is related to #1187

**Comment by Legorooj** [comment]
This had been fixed
