### ISSUE TITLE
HP-UX 11.31 ia64 support

### ISSUE THREAD

**Issue by poyntesm** [pyinstaller/pyinstaller#1186]
Hello,

I can see from readme that HP-UX is not supported, however I note that Solaris and AIX have experimental support. Would it be possible to add HP-UX experimental support?

Python 2.7.x is available for the platform.

http://hpux.connect.org.uk/hppd/hpux/Languages/python-2.7.9

In addition I had no issues to add setuptools or indeed install pyinstaller to the system. However its clear at the moment the support will not work.

#pyinstaller -F /usr/local/bin/jsonpatch
19 INFO: wrote /root/home/hpiespoy/jsonpatch.spec
162 INFO: UPX is not available.
283 INFO: Processing hook hook-os
844 INFO: Processing hook hook-time
862 INFO: Processing hook hook-cPickle
1248 INFO: Processing hook hook-_sre
1888 INFO: Processing hook hook-cStringIO
2389 INFO: Processing hook hook-encodings
2471 INFO: Processing hook hook-codecs
4355 INFO: Extending PYTHONPATH with /usr/local/bin
4356 INFO: checking Analysis
4356 INFO: building Analysis because out00-Analysis.toc non existent
4356 INFO: running Analysis out00-Analysis.toc
4532 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/loader/_pyi_bootstrap.py
4606 INFO: Processing hook hook-os
4683 INFO: Processing hook hook-site
4763 INFO: Processing hook hook-encodings
5298 INFO: Processing hook hook-time
5313 INFO: Processing hook hook-cPickle
5687 INFO: Processing hook hook-_sre
6309 INFO: Processing hook hook-cStringIO
8977 INFO: Processing hook hook-codecs
12069 INFO: Processing hook hook-pydoc
12741 INFO: Processing hook hook-email
13033 INFO: Processing hook hook-httplib
13209 INFO: Processing hook hook-email.message
13501 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/loader/pyi_importers.py
13732 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/loader/pyi_archive.py
13946 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/loader/pyi_carchive.py
14158 INFO: Analyzing /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/loader/pyi_os_path.py
14181 INFO: Analyzing /usr/local/bin/jsonpatch
14945 INFO: Hidden import 'codecs' has been found otherwise
14946 INFO: Hidden import 'encodings' has been found otherwise
14946 INFO: Looking for run-time hooks
Your platform is not yet supported.

This appears to come from get_python_library_path() which has no HP-UX support as 1st error point.

#find /usr/local/lib/python2.7 -name libpython*
/usr/local/lib/python2.7/config/libpython2.7.a

#file /usr/local/lib/python2.7/config/libpython2.7.a
/usr/local/lib/python2.7/config/libpython2.7.a: archive file

It seems that on HP-UX it might be similar in setup to AIX.

Please let me know if I can assist you at all in any tests..

Regards
Esmond

**Comment by matysek** [comment]
Hi @poyntesm , we do not have the necessary knowledge and resources to do that.

But have you tried to compile the bootloader?

It might not be hard to add hpux support. It might be just a matter of editing a few files.

We would welcome patches.

**Comment by poyntesm** [comment]
Hi @matysek ,

Thanks for quick response. I have not compiled the bootloader before. it might be a bit past me but I will give it a try. Is http://pythonhosted.org/PyInstaller/#building-the-bootloader the best resource. I am more than willing to give it and go and will look to the AIX/Solaris support as guides for maybe where edits/logic is needed. Is it OK to comment/ask for support in this issue if I get very stuck?

**Comment by matysek** [comment]
@poyntesm yes, it's the place where to look for instructions. As you described, hpux support might be similar, in that case I would try to find in pyinstaller code places where aix is mentioned. Good place to understand the code is probably file ./PyInstaller/compat.py.

It's ok to ask in this issue.

**Comment by poyntesm** [comment]
So using the HP standard C compiler which is the below...

  B9007AA.C-ANSI-C      C.06.26        HP C/aC++ Compiler

We get an error

/tmp/PyInstaller-2.1/bootloader>/usr/local/bin/python ./waf configure build install
HP-UX-32bit detected
Checking for program gcc or cc           : /usr/bin/cc

So since it says AIX was built using GCC I placed GCC 4.2.3 onto the system.

/tmp/PyInstaller-2.1/bootloader>/usr/local/bin/python ./waf configure build install
HP-UX-32bit detected
Checking for program gcc or cc           : /usr/local/bin/gcc
Checking for program cpp                 : /usr/local/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for gcc                         : ok
Checking for library dl                  : not found

I persume and forgive me I am not a massive compling guru.. I think its looking for libdld right?

/tmp/PyInstaller-2.1/bootloader>find /usr -name libdl*
/usr/lib/libdld.1
/usr/lib/libdld.2
/usr/lib/libdld.sl
/usr/lib/hpux32/libdl.so.1
/usr/lib/hpux32/libdl.so
/usr/lib/hpux32/libdld.so
/usr/lib/hpux32/libp/libdlv_vxfs.so
/usr/lib/hpux32/libp/libdlv_vxfs.so.1
/usr/lib/hpux32/libdlv_vxfs.so
/usr/lib/hpux32/libdlv_vxfs.so.1
/usr/lib/hpux64/libdl.so
/usr/lib/hpux64/libdl.so.1
/usr/lib/hpux64/libdld.so
/usr/lib/hpux64/libp/libdlv_vxfs.so
/usr/lib/hpux64/libp/libdlv_vxfs.so.1
/usr/lib/hpux64/libdlv_vxfs.so
/usr/lib/hpux64/libdlv_vxfs.so.1
/usr/lib/pa20_64/libdl.1
/usr/lib/pa20_64/libdl.sl
/usr/lib/pa20_64/libdld.1
/usr/lib/pa20_64/libdld.sl
/usr/lib/pa20_64/libdlv_vxfs.1
/usr/lib/pa20_64/libdlv_vxfs.sl
/usr/lib/pa20_32/libdlv_vxfs.1
/usr/lib/pa20_32/libdlv_vxfs.sl
/usr/lib/libdld.0
/usr/lib/libdlv_vxfs.1
/usr/lib/libdlv_vxfs.sl

i guess the /usr/lib/hpux32/ one is the correct one,but seems not to be found, any ideas... thanks for any help.

**Comment by matysek** [comment]
* libdl is a library that contains function dlopen().
* your python looks like 32bit: HP-UX-32bit detected
* I assume the right one is probably /usr/lib/hpux32/libdl.so
* you might try to set LD_LIBRARY_PATH or hpux equivalent to point to /usr/lib/hpux32

**Comment by poyntesm** [comment]
@matysek .. So I tried LD_LIBRARY_PATH and also LD_PRELOAD but still fail. However the config.log shows that 

[1/2] ^[[32mcc: build/.conf_check_0/test.c -> build/.conf_check_0/testbuild/default/test_1.o
^[[0m['/usr/local/bin/gcc', '-I../common', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=500', '-D_REENTRANT', '-D_BSD_SOURCE', '../test.c', '-c', '-o', 'default/test_1.o']
[2/2] ^[[33mcc_link: build/.conf_check_0/testbuild/default/test_1.o -> build/.conf_check_0/testbuild/default/testprog
^[[0mld: Bad keyword argument: dynamic
Fatal error.
collect2: ld returned 1 exit status
['/usr/local/bin/gcc', 'default/test_1.o', '-o', '/tmp/PyInstaller-2.1/bootloader/build/.conf_check_0/testbuild/default/testprog', '-Wl,-Bdynamic', '-ldl']
command returned 'Build failed:  -> task failed (err #1): \n\t{task: cc_link test_1.o -> testprog}'not found

Below is a "ld -V " output

/tmp/PyInstaller-2.1/bootloader>ld -V
ld: 92453-07 linker ld HP Itanium(R) B.12.55  IPF/IPF

**Comment by matysek** [comment]
Try to look at file ./bootloader/wscript where the whole build process is defined.
Another option is to start looking at the develop version.

**Comment by poyntesm** [comment]
So I can "try" to look at the wscript, but I fear I will get little lost. I have tried also on the develop version and same result.

**Comment by matysek** [comment]
you need to tell gcc where to look for libraries. I think for gcc it is option -L.  like:  -L /usr/lib/hpux32/

You might try append somewhere into wscript line like
```python
conf.env.append_value('CCFLAGS', '-L/usr/lib/hpux32/')
```
or
```python
conf.env.append_value('LINKFLAGS',  '-L/usr/lib/hpux32/')
```

**Comment by poyntesm** [comment]
So I can see the option is now passed to GCC but still no joy. The error on bad keyword argument I am also researching.

[1/2] ^[[32mcc: build/.conf_check_0/test.c -> build/.conf_check_0/testbuild/default/test_1.o
^[[0m['/usr/local/bin/gcc', '-L/usr/lib/hpux32/', '-I../common', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=500', '-D_REENTRANT', '-D_BSD_SOURCE', '../test.c', '-c', '-o', 'default/test_1.o']
[2/2] ^[[33mcc_link: build/.conf_check_0/testbuild/default/test_1.o -> build/.conf_check_0/testbuild/default/testprog
^[[0mld: Bad keyword argument: dynamic
Fatal error.
collect2: ld returned 1 exit status
['/usr/local/bin/gcc', 'default/test_1.o', '-o', '/tmp/PyInstaller-2.1/bootloader/build/.conf_check_0/testbuild/default/testprog', '-L/usr/lib/hpux32/', '-Wl,-Bdynamic', '-ldl']
command returned 'Build failed:  -> task failed (err #1): \n\t{task: cc_link test_1.o -> testprog}'not found[code]

**Comment by poyntesm** [comment]
From http://ftp.gnu.org/pub/old-gnu/Manuals/ld-2.9.1/html_node/ld_3.html

-akeyword
    This option is supported for HP/UX compatibility. The keyword argument must be one of the strings `archive', `shared', or `default'. `-aarchive' is functionally equivalent to `-Bstatic', and the other two keywords are functionally equivalent to `-Bdynamic'. This option may be used any number of times. 

Looking now to where this is set from

**Comment by poyntesm** [comment]
@matysek Do you have any idea where '-Wl,-Bdynamic' gets set from, I have grep'd for it but no luck..

**Comment by matysek** [comment]
@poyntesm that probably is the default settings from waf that is used for compilation of bootloader. The ./waf file is a kind of self-extracting executable. It extracts python files into directory like
```
.waf-1.5.18-402a8e0721eb718ff717906f130db0f4
```

**Comment by poyntesm** [comment]
@matysek Thanks. So file /bootloader/.waf-1.5.18-402a8e0721eb718ff717906f130db0f4/wafadmin/Tools/gcc.py had the reference .

Changed to below
#       v['SHLIB_MARKER']='-Wl,-Bdynamic'
        v['SHLIB_MARKER']='-Wl,-adefault'

And now thankfully libdl is found, however libz is not :(

/tmp/PyInstaller-2.1/bootloader>/usr/local/bin/python ./waf configure build install
HP-UX-32bit detected
Checking for program gcc or cc           : /usr/local/bin/gcc
Checking for program cpp                 : /usr/local/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for gcc                         : ok
Checking for library dl                  : yes
Checking for library z                   : not found

libz.so is in a seperate directory of "/usr/local/lib/hpux32/" so I amended to add a second "-L" option to gcc but it did not work :(.

['/usr/local/bin/gcc', '-L/usr/lib/hpux32/ -L/usr/local/lib/hpux32/', '-I../common', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=500', '-D_REENTRANT', '-D_BSD_SOURCE', '../test.c', '-c', '-o', 'default/test_1.o']
[2/2] cc_link: build/.conf_check_0/testbuild/default/test_1.o -> build/.conf_check_0/testbuild/default/testprog
ld: Can't find library for -lz
Fatal error.
collect2: ld returned 1 exit status
['/usr/local/bin/gcc', 'default/test_1.o', '-o', '/tmp/PyInstaller-2.1/bootloader/build/.conf_check_0/testbuild/default/testprog', '-L/usr/lib/hpux32/ -L/usr/local/lib/hpux32/', '-Wl,-adefault', '-lz']

**Comment by poyntesm** [comment]
Also I was looking foward, so as a note also GCC on HPUX does not support -m32 or -m64

    if conf.env.CC_NAME == 'gcc':
        if myarch == '32bit' and conf.check_cc(ccflags='-m32', msg='Checking for flags -m32'):
            conf.env.append_value('CCFLAGS', '-m32')
        elif myarch == '32bit' and conf.check_cc(ccflags='-milp32', msg='Checking for flags -milp32'):
            conf.env.append_value('CCFLAGS', '-milp32')
        elif myarch == '64bit':
            conf.env.append_value('CCFLAGS', '-m64')
        elif myarch == '64bit' and conf.check_cc(ccflags='-mlp64', msg='Checking for flags -mlp64'):
            conf.env.append_value('CCFLAGS', '-mlp64')

and that appears to work... 

Checking for function readlink           : yes
Checking for flags -m32                  : not found
Checking for flags -milp32               : yes

Still got to solve my libz issue though. Any pointers on that will be great.

**Comment by poyntesm** [comment]
@matysek  Progress :) .. there is now two new errors.

root@xxxxx.hp.com:/tmp/PyInstaller-2.1/bootloader>/usr/local/bin/python ./waf configure build install
HP-UX-32bit detected
Checking for program gcc or cc           : /usr/local/bin/gcc
Checking for program cpp                 : /usr/local/bin/cpp
Checking for program ar                  : /usr/bin/ar
Checking for program ranlib              : /usr/bin/ranlib
Checking for gcc                         : ok
Checking for library dl                  : yes
Checking for library z                   : yes
Checking for function readlink           : yes
Checking for flags -m32                  : not found
Checking for flags -milp32               : yes
'configure' finished successfully (1.370s)
Waf: Entering directory `/tmp/PyInstaller-2.1/bootloader/build'
[ 2/40] cc: common/pyi_utils.c -> build/debug/common/pyi_utils_1.o
In file included from ../common/pyi_utils.c:53:
../common/stb.h:369: error: size of array 'stb__testsize2_uinta' is negative
In file included from ../common/pyi_utils.c:55:
../common/pyi_archive.h:61: error: 'PATH_MAX' undeclared here (not in a function)
Waf: Leaving directory `/tmp/PyInstaller-2.1/bootloader/build'
Build failed:  -> task failed (err #1):
        {task: cc pyi_utils.c -> pyi_utils_1.o}

**Comment by poyntesm** [comment]
Some details on PATH_MAX on HP-UX i found.
https://lists.gnu.org/archive/html/bug-gnulib/2011-06/msg00242.html

As temporary workaround I set in ./common/pyi_archive.h
>#define PATH_MAX 1024

Leaving just one issue now..

>'configure' finished successfully (4.538s)
Waf: Entering directory `/tmp/PyInstaller-2.1/bootloader/build'
[ 2/40] cc: common/pyi_utils.c -> build/debug/common/pyi_utils_1.o
In file included from ../common/pyi_utils.c:53:
../common/stb.h:369: error: size of array 'stb__testsize2_uinta' is negative
Waf: Leaving directory `/tmp/PyInstaller-2.1/bootloader/build'
Build failed:  -> task failed (err #1):
        {task: cc pyi_utils.c -> pyi_utils_1.o}

**Comment by poyntesm** [comment]
Ok, so bear with me as I am really not a compiler expert :)

I set the line to as below
>typedef char stb__testsize2_uinta[sizeof(stb_uinta)==sizeof(char*) ? 1 : 0];

I needed to .set the PATH_MAX also in /common/pyi_path.c and then in common/pyi_utils.c I needed to ensure mkdtemp.h was included.

Then I seem to get much futher but I still see one warning

>In file included from ../common/main.c:48:
>../common/stb.h: In function 'stb__try_chunk':
>../common/stb.h:2609: warning: cast from pointer to integer of different size

But then the bootoader seems to have built

[36/40] cc: common/pyi_path.c -> build/debugw/common/pyi_path_4.o
[37/40] cc_link: build/debug/linux/getpath_1.o build/debug/common/pyi_utils_1.o build/debug/common/pyi_launch_1.o build/debug/common/pyi_pythonlib_1.o build/debug/common/pyi_archive_1.o build/debug/common/pyi_python_1.o build/debug/common/pyi_global_1.o build/debug/common/main_1.o build/debug/common/pyi_path_1.o -> build/debug/run_d
[38/40] cc_link: build/release/linux/getpath_2.o build/release/common/pyi_utils_2.o build/release/common/pyi_launch_2.o build/release/common/pyi_pythonlib_2.o build/release/common/pyi_archive_2.o build/release/common/pyi_python_2.o build/release/common/pyi_global_2.o build/release/common/main_2.o build/release/common/pyi_path_2.o -> build/release/run
[39/40] cc_link: build/releasew/linux/getpath_3.o build/releasew/common/pyi_utils_3.o build/releasew/common/pyi_launch_3.o build/releasew/common/pyi_pythonlib_3.o build/releasew/common/pyi_archive_3.o build/releasew/common/pyi_python_3.o build/releasew/common/pyi_global_3.o build/releasew/common/main_3.o build/releasew/common/pyi_path_3.o -> build/releasew/runw
[40/40] cc_link: build/debugw/linux/getpath_4.o build/debugw/common/pyi_utils_4.o build/debugw/common/pyi_launch_4.o build/debugw/common/pyi_pythonlib_4.o build/debugw/common/pyi_archive_4.o build/debugw/common/pyi_python_4.o build/debugw/common/pyi_global_4.o build/debugw/common/main_4.o build/debugw/common/pyi_path_4.o -> build/debugw/runw_d
Waf: Leaving directory `/tmp/PyInstaller-2.1/bootloader/build'
'build' finished successfully (35.920s)
Waf: Entering directory `/tmp/PyInstaller-2.1/bootloader/build'
* installing build/debug/run_d as ../../PyInstaller/bootloader/HP-UX-32bit/run_d
* installing build/release/run as ../../PyInstaller/bootloader/HP-UX-32bit/run
* installing build/releasew/runw as ../../PyInstaller/bootloader/HP-UX-32bit/runw
* installing build/debugw/runw_d as ../../PyInstaller/bootloader/HP-UX-32bit/runw_d
Waf: Leaving directory `/tmp/PyInstaller-2.1/bootloader/build'
'install' finished successfully (0.234s)

Question now is has my approach been stupid and what do I do with the built bootloader??

**Comment by matysek** [comment]
> Question now is has my approach been stupid and what do I do with the built bootloader??

You approach has not been stupid.  Now you have the basic for other work:
* get back to running pyinstaller.py
* and edit pyinstaller python code, until you get pyinstaller to create the executable
* when pyinstaller is able to create the executable you will see if there are necessary other modifications in the bootloader.

**Comment by poyntesm** [comment]
Thanks for sticking with me on this. I was detailing steps for others in the future as it might help. I re-ran the installer now for Pyinstaller so that the newly compiled bootloader gets added and that seemed to have happened with no issue.

>ls -l /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/bootloader/HP-UX-32bit/*
-rw-r--r--   1 root       sys         296080 Feb 12 17:14 /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/bootloader/HP-UX-32bit/run
-rw-r--r--   1 root       sys         560324 Feb 12 17:14 /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/bootloader/HP-UX-32bit/run_d
-rw-r--r--   1 root       sys         296080 Feb 12 17:14 /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/bootloader/HP-UX-32bit/runw
-rw-r--r--   1 root       sys         560324 Feb 12 17:14 /usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/bootloader/HP-UX-32bit/runw_d

I will now start to try amend the pyinstaller code itself. Thanks again.

**Comment by poyntesm** [comment]
@matysek 

Can you tell me what the expected filename structure should be in the block below from bindepend.py.

I had added the is_hpux logic and basics in compat.py and _ _init_ _.py
```python
is_hpux = sys.platform.startswith('hp-ux') 
is_unix = is_linux or is_solar or is_aix or is_hpux
```

However the function below is then erroring

```python
def getSoname(filename):
    """
    Return the soname of a library.
    """
    cmd = ["objdump", "-p", "-j", ".dynamic", filename]
    m = re.search(r'\s+SONAME\s+([^\s]+)', compat.exec_command(*cmd))
    if m:
        return m.group(1)
```

At the moment with some logic to add the HPUX path

```python
        elif is_hpux:
            paths.append('/usr/local/lib/hpux32')
```

So we pass to getSoname the filename of /usr/local/lib/hpux32/libpython2.7.so ... which seems right..but gives error

```
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-2.1-py2.7.egg/PyInstaller/bindepend.py", line 660, in findLibrary
    return os.path.join(dir, getSoname(lib))
  File "/usr/local/lib/python2.7/posixpath.py", line 75, in join
    if b.startswith('/'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Thanks.

**Comment by poyntesm** [comment]
Sorry was not reading function right. The SONAME is not in output from that command

```
objdump -p -j .dynamic /usr/local/lib/hpux32/libpython2.7.so

/usr/local/lib/hpux32/libpython2.7.so:     file format elf32-ia64-hpux-big
private flags = BE, ABI32

Program Header:
    PHDR off    0x00000034 vaddr 0x04000034 paddr 0x00000000 align 2**2
         filesz 0x00000120 memsz 0x00000120 flags r--
 DYNAMIC off    0x00000190 vaddr 0x04000190 paddr 0x00000000 align 2**3
         filesz 0x000000e0 memsz 0x000000e0 flags r--
    NOTE off    0x00000154 vaddr 0x04000154 paddr 0x00000000 align 2**2
         filesz 0x0000003c memsz 0x0000003c flags r--
0x70000001 off    0x00027d60 vaddr 0x04027d60 paddr 0x00000000 align 2**3
         filesz 0x0002f918 memsz 0x0002f918 flags r--
0x60000000 off    0x00000000 vaddr 0x00000000 paddr 0x00000000 align 2**0
         filesz 0x00000000 memsz 0x00000000 flags r--
0x60000016 off    0x00481cb8 vaddr 0x00000000 paddr 0x00000000 align 2**2
         filesz 0x00000098 memsz 0x00000098 flags r--
    LOAD off    0x00000000 vaddr 0x04000000 paddr 0x00000000 align 2**5
         filesz 0x00427210 memsz 0x00427210 flags r-x 860000
    LOAD off    0x00430000 vaddr 0x40010000 paddr 0x00000000 align 2**4
         filesz 0x0003e338 memsz 0x00044a48 flags rw- 80000
    NOTE off    0x0046e338 vaddr 0x00000000 paddr 0x00000000 align 2**2
         filesz 0x00013a18 memsz 0x00000000 flags r--

Dynamic Section:
  NEEDED      libnsl.so.1
  NEEDED      librt.so.1
  NEEDED      libdl.so.1
  NEEDED      libm.so.1
  RUNPATH     /usr/local/lib/hpux32:.
  FLAGS       0x0
  0x60000001  0x0
  PLTGOT      0x4004b860
  HASH        0x400bf88
  STRTAB      0x4005cd0
  SYMTAB      0x4000270
  0x70000000  0x4004e830
  0x6000000c  0x40dcd68
  0x6000000b  0x1
  0x60000008  0x5283a137
  0x60000009  0xe0871470
  0x60000018  0xd4881e60
  RELA        0x400e764
  RELASZ      0x195fc
  PLTREL      0x7
  JMPREL      0x4024fb8
  PLTRELSZ    0x2da8
  0x6000000d  0x402026c
  0x6000000e  0x4674
  RELAENT     0xc
  STRSZ       0x62b7
  SYMENT      0x10

**Comment by poyntesm** [comment]
So I checked into what the output of objdump should provide and the simple filename of the library seems to be the SONAME in 99% of the case. So I amended to just provide that.

```
xxxxxx.gre.omc.hp.com:(/root/home/hpiespoy)(hpiespoy)#file /root/home/hpiespoy/dist/jsonpatch
/root/home/hpiespoy/dist/jsonpatch:     ELF-32 executable object file - IA64
xxxxxx.gre.omc.hp.com:(/root/home/hpiespoy)(hpiespoy)#/root/home/hpiespoy/dist/jsonpatch
usage: jsonpatch [-h] [--indent INDENT] [-b] [-i] [-v] ORIGINAL [PATCH]
jsonpatch: error: too few arguments
xxxxxx.gre.omc.hp.com:(/root/home/hpiespoy)(hpiespoy)#

i am very happy now. I will prepare a pull request for you :)

**Comment by poyntesm** [comment]
@matysek 

Spoke to soon, I move the binary to another server now...
So one issue I am seeing . I see errors about unsupported hash type. I see it repeated for md5,sha1,sha224,sha256,sha384 and sha512

```
xxxx:/home/./jsonpatch_hpux a.json patch.json --indent=3
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/root/home/hpiespoy/build/jsonpatch/out00-PYZ.pyz/hashlib", line 139, in <module>
  File "/root/home/hpiespoy/build/jsonpatch/out00-PYZ.pyz/hashlib", line 91, in __get_builtin_constructor
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
...
```

However the actual script worked (is applying a json patch), but we do get alot of errors to stdout.

**Comment by matysek** [comment]
@poyntesm If you are able to implement HP-UX support this could be then merged.
