### ISSUE TITLE
look for .dlls in the same directory as where .pyd are located

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1187]
- On windows some Python C extensions (.pyd) files depend on some dlls.
- Those dlls are in the same directory as .pyd file:

```
./package/subpackage/modname.pyd
./package/subpackage/dependency.dll
```
- pyinstaller should look for dependent dlls also in directories /package/subpackage.

For matplotlib there is a hack that does this but it is not a general solution.

**Comment by htgoebel** [comment]
Removing this from the project's schedule until somebody wants to pick it up an provide a pull-request.

**Comment by Legorooj** [comment]
This is implemented
