### ISSUE TITLE
use pkg_resources on each located package to find its entry points

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1188]
[As described here](https://github.com/pyinstaller/pyinstaller/pull/140#issuecomment-73174437)

Use pkg_resources on each located package in the Analysis step to find its entry points and make sure those modules are collected. This approach would work for any module that uses entry_points for anything, and will include any modules specified in entry_points.

cryptography benefits from calling pkg_resources.iter_entry_points("cryptography.backend") since it will list all entry points that match the group name cryptography.backend from all installed packages, meaning a package that adds a new backend for cryptography doesn't have to explicitly register itself with the cryptography module - it just needs to present that entry point and pkg_resources will take care of finding it for cryptography.

A cryptography-specific solution is to edit hook-cryptography.py and either list cryptography.hazmat.backends.openssl as a hidden import, or inspect cryptography's entry_points there. In fact, you could have the hook use iter_entry_points to find all of the packages that present cryptography backends and collect them.

**Comment by codewarrior0** [comment]
Add `[Originally posted by codewarrior0 here](https://github.com/pyinstaller/pyinstaller/pull/140#issuecomment-73174437)`, please.

**Comment by ubmarco** [comment]
I'd love that new feature.
I'm working with [groundwork](https://github.com/useblocks/groundwork), a plugin manager that finds its plugins using `pkg_resources.iter_entry_points`. It uses the `entry_points` group `groundwork.plugin`. Unfortunately groundwork does not see any plugins when being bundled through PyInstaller.

I've found a workaround that could serve as an implementation blueprint.
I adapted the recipe given in the [wiki](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Setuptools-Entry-Point) and wrote an own spec file:

```
# -*- mode: python -*-

block_cipher = None

def Entrypoint(dist, group, name, **kwargs):
    import pkg_resources

    # get toplevel packages of distribution from metadata
    def get_toplevel(dist):
        distribution = pkg_resources.get_distribution(dist)
        if distribution.has_metadata('top_level.txt'):
            return list(distribution.get_metadata('top_level.txt').split())
        else:
            return []

    kwargs.setdefault('hiddenimports', [])
    packages = []
    for distribution in kwargs['hiddenimports']:
        print(distribution)
        packages += get_toplevel(distribution)

    kwargs.setdefault('pathex', [])
    # get the entry point

    ep = pkg_resources.get_entry_info(dist, group, name)
    print('ep: {}'.format(ep))
    # insert path of the egg at the verify front of the search path
    kwargs['pathex'] = [ep.dist.location] + kwargs['pathex']
    # script name must not be a valid module name to avoid name clashes on import
    script_path = os.path.join(workpath, name + '-script.py')
    print("creating script for entry point", dist, group, name)
    with open(script_path, 'w') as fh:
        print("import pkg_resources", file=fh)
        print("d = pkg_resources.Distribution(version='1.0.0')", file=fh)
        print("ep1_gw = pkg_resources.EntryPoint.parse('erc_e2e_manager = erc_e2e.plugins.erc_e2e_manager:ErcE2eManager', dist=d)", file=fh)
        print("ep2_gw = pkg_resources.EntryPoint.parse('erc_e2e_svn = erc_e2e.plugins.erc_e2e_svn:ErcE2eSvn', dist=d)", file=fh)
        print("d._ep_map = {'groundwork.plugin': {'erc_e2e_manager': ep1_gw, 'erc_e2e_svn': ep2_gw}}", file=fh)
        print("pkg_resources.working_set.add(d, 'erc_e2e')\n", file=fh)
        print("import", ep.module_name, file=fh)
        print("%s.%s()" % (ep.module_name, '.'.join(ep.attrs)), file=fh)
        for package in packages:
            print("import", package, file=fh)
    kwargs['hiddenimports'].append('erc_e2e.plugins.erc_e2e_manager')
    kwargs['hiddenimports'].append('erc_e2e.plugins.erc_e2e_svn')
    print(kwargs)

    return Analysis(
        [script_path] + kwargs.get('scripts', []),
        datas=[('erc_e2e/applications/erc_e2e_app/configuration.py', 'erc_e2e/applications/erc_e2e_app')],
        **kwargs,
    )

a = Entrypoint('erc_e2e', 'console_scripts', 'erc_e2e')

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='erc_e2e_app',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='erc_e2e_app')
```

The idea is to append some code to the file `build/erc_e2e/erc_e2e-script.py` to make the `groundwork.plugin` entry points visible to the application. It's done manually here but the proposal could be expanded so that setuptools is used directly to extract all that information programmatically.

**Comment by danyeaw** [comment]
Could we expand the scope of this Feature request to not just support pkg_resources? Python 3.8 includes importlib-metadata in the standard library and is it intends to replace most uses of pkg_resources entry point API and metadata API. It also available on PyPI now for use outside of the standard library, and the project that I maintain has already replaced pkg_resources with it.

@ubmarco I have a use case very similar to yours with [Gaphor](https://github.com/gaphor/gaphor), but I am using the entry points to load services and plugins (21 of them). Do you have an example of this being used in a project? I looked at groundwork and I didn't see a spec file.

**Comment by bjones1** [comment]
I implemented this fully at one point, and found the results was a huge and bloated binary, since this pulls in a lot of packages not essential to the code.

A better solution IMHO is to use hooks to include the entry points of specific packages. This is implemented already with code like this in a hook:


``` Python
from PyInstaller.utils.hooks import requirements_for_package
hiddenimports += requirements_for_package('package_name')
```

However, the `requirements_for_package` function could certainly use some rewriting. This seems like a good place to start, executing the `importlib-metadata` code only if it can be imported.

**Comment by danyeaw** [comment]
Instead of importing all entry points for every package, what if we only import the entry points of the app that is being packaged?

**Comment by earonesty** [comment]
This is something that needs to be decided on a per-package basis.  for `keyring`, entry points should probably all be included.   `hidden_imports += [ep.module_name for ep in pkg_resources.iter_entry_points('keyring.backends')]`   For other systems, this might be inappropriate.

**Comment by jaraco** [comment]
> Instead of importing all entry points for every package, what if we only import the entry points of the app that is being packaged?

As earonesty indicates, this approach isn't generally viable. What you're really alluding to is - what entry points is the application going to call, but my guess is you can't predict that reliably.

How huge and bloated is the binary? Addressing this issue would go a long way to supporting a lot of missing use-cases; perhaps the larger binary is actually what most users would want.

I find this approach interesting, but while it's addressing the missing imports issue, it doesn't seem to be addressing the other issue - that packages supplied in a pyinstaller environment don't have any metadata. It would be nice if this work also [extended the search algorithm](https://docs.python.org/3/library/importlib.metadata.html#extending-the-search-algorithm) for packages supplied by pyinstaller such that calls for metadata (version, files, etc) would also succeed.

**Comment by bwoodsend** [comment]
[PyInstaller.utils.hooks.collect_entry_point()](https://pyinstaller.readthedocs.io/en/v4.7/hooks.html#PyInstaller.utils.hooks.collect_entry_point) (#5737) is probably the closest we're ever going to willingly go to implementing this.
