### ISSUE TITLE
Symbol error when running on previous OS X releases (build on 10.10, fails to run on 10.9)

### ISSUE THREAD

**Issue by barn** [pyinstaller/pyinstaller#1191]
Similar to #694 I believe (so mark as a dupe if need be)

Using the test python at https://gist.github.com/barn/1dcb75f0b476294e59f2 I'm unable to take that bundled app and run it on 10.8 or even 10.9.

I've gone through the joy of MACOSX_DEPLOYMENT_TARGET and the likes. SDKROOT. Different python libraries.

On 10.8, from a 10.10 build, I get:

```
[vagrant@vagrants-Mac:-vagrant]% ./demo_pyinstaller
Error loading Python lib '/var/folders/ld/4bn_z1q53r96dp44fddhj2yr0000gn/T/_MEIRW0Ds3/Python': dlopen(/var/folders/ld/4bn_z1q53r96dp44fddhj2yr0000gn/T/_MEIRW0Ds3/Python, 10): Symbol not found: ___sincos_stret
  Referenced from: /var/folders/ld/4bn_z1q53r96dp44fddhj2yr0000gn/T/_MEIRW0Ds3/Python
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/ld/4bn_z1q53r96dp44fddhj2yr0000gn/T/_MEIRW0Ds3/Python
```

https://gist.github.com/barn/51aeb936371e74c7424c is the build process as I've last ran it.

I haven't found a combination of MACOSX_DEPLOYMENT_TARGET that seems to help. So far only building it on a 10.8 VM does. Then it runs on 10.8-10.10.

**Comment by matysek** [comment]
@barn As you wrote the 'safe' way is to build on 10.8. The failure might be related to your environment - homebrew, macports, stock OSX python. Usually the best way to use python on OS X is macports or homebrew.

There is not much we could do about it. Closing.

**Comment by JPLeBreton** [comment]
If it's definitely the case that apps built with newer versions of OSX don't work with older versions, it would be nice to add a section like the one for Linux forward-compatibility http://pythonhosted.org/PyInstaller/#making-linux-apps-forward-compatible to the documentation.

**Comment by tallforasmurf** [comment]
I will double check that this is covered, I think I already did it but have not checked it in.

**Comment by tallforasmurf** [comment]
Yes, I put that in the latest rev, see http://pythonhosted.org/PyInstaller/#making-mac-os-x-apps-forward-compatible

**Comment by abulka** [comment]
Mac forward compatible doco link has changed to http://pythonhosted.org/PyInstaller/usage.html#making-mac-os-x-apps-forward-compatible

**Comment by htgoebel** [comment]
The correct link for Mac forward compatible docs is https://pyinstaller.readthedocs.io/en/stable/usage.html#making-mac-os-x-apps-forward-compatible since PyInstaller Docs are hosted at readthedocs since quite some while.
