### ISSUE TITLE
PyQt5.4 QtWebEngine with Mac OS app bundle "Couldn't mmap icudtl.dat"

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1193]
I have been trying to build a PyQt5.4 app that uses the new QtWebEngine browser module. PyInstaller does its usual thing and copies the relevant modules into .app/Contents/MacOS. However the app will fail to start with the message "Couldn't mmap icudtl.dat". This message is the sign of a major complication with bundling QtWebEngine for Mac OSX.

The problem is that unlike the other QtXxxx modules, which can operate correctly from inside the MacOS folder, QtWebEngine has to be installed as a "framework" in the Frameworks folder. Based on email with a Qt developer, the commit that initiates that change is here (https://codereview.qt-project.org/#/c/99052/) and the code that implements it is here (https://github.com/qtproject/qttools/blob/dev/src/macdeployqt/shared/shared.cpp).

Bottom line, in order for QtWebEngine to work in a MacOS app, the folder structure must be:
```
myscript.app/
    Frameworks/
        QtWebEngineCore.framework/
            Helpers@ -> Verssion/Current/Helpers
            Libraries@ -> Versions/Current/Libraries
            QtWebEngineCore@ -> Versions/Current/QtWebEngineCore
            Resources@ -> Versions/Current/Resources
            Versions/
                Current/
                    QtWebEngineCore (executable)
                    Resources/
                        Info.plist with the following two keys:
                        CFBundleExecutable: QtWebEngineCore
                        CFBundleIdentifier: org.qt-project.QtWebEngineCore
                        icudtl.dat
                        qtwebengine_locales/*.pak
                        qtwebengine_resources.pak
                Helpers/QtWebEngineProcess.app
                Libraries/ffmpegsumo.so
    MacOS/
        myscript
        other binaries needed by PyQt
```
This is the structure of files and folders that is built by the Qt tool "macdeployqt" (source linked above). I created this structure manually in an app built by PyInstaller. I deleted QtWebEngineCore from inside MacOS, and built the structure above by ``cp -R `` from an example app built by macdeployqt.

Also there remain two modules in MacOS that link to QtWebEngineCore (QtWebEngine and QtWebEngineWidgets) and I had to use install_name_tool to change their links from ``@executable_path/QtWebEngineCore`` to ``@executable_path/../Frameworks/QtWebEngineCore.framework/QtWebEngineCore``.

Also, the QtWebEngineCore module has links to other modules such as QtWebEngine and QtGui, and these have to be changed to ``@executable_path/../MacOS/whatever``.

It is not clear to me how such changes could be performed in a hook.

**Comment by matysek** [comment]
This was recently fixed in this #1495 pull request. If it does not work for you please reopen. Thanks.

**Comment by glennra** [comment]
The change in [#1495] (https://github.com/pyinstaller/pyinstaller/pull/1495) isn't quite right. It allows a browser window to be opened but it also creates an extra icon on the dock. Please reopen this.

**Comment by matysek** [comment]
@glennra Are you going to work  on it?

**Comment by glennra** [comment]
Yes
