### ISSUE TITLE
Error with wxPython in a thread with --onefile only

### ISSUE THREAD

**Issue by KenV99** [pyinstaller/pyinstaller#1195]
Using current develop branch and 32bt python2.7 with wxPython 3.0 on Windows 7 x64, I am running wx.App in it's own thread as instructed here: http://wiki.wxpython.org/MainLoopAsThread. It runs fine with no errors with pythonw.exe. It also runs fine after using PyInstaller building to one folder. However with the --onefile option, the program fails with a wxWidgets error:

assert "module->m_state == State_Initialized" failed in wxModule::DoCleanUpModules(): not initialized module being cleaned up.

If the only differences is that the file is decompressed and then run using onefile, it's not clear to me why it would fail with onefile and not fail when there is a folder of files.

**Comment by KenV99** [comment]
I am also getting an:

assert "wxIsMainThread()" failed in wxSocketBase::IsInitialized(): unsafe to call from other threads

error now. Is the execution from a --onefile build using a different threading model than if using --onedir?

**Comment by matysek** [comment]
Please try `python3` branch. If the issue remains, please reopen.
