### ISSUE TITLE
Diagnostic Information Still Printed from Executable

### ISSUE THREAD

**Issue by leycec** [pyinstaller/pyinstaller#1196]
In response to #1140, [matysek](https://github.com/matysek) kindly squelched [a few stray `print()` statements](https://github.com/matysek/pyinstaller/commit/8d416fb13e1b9e1a0d67e15db12ffdb7929be0ee) leaking from the bootloader. However, a recent [stackoverflow question](https://stackoverflow.com/questions/28611297/suppress-output-when-running-pyinstaller-generated-executable/28644186#28644186) suggests that he may not have got 'em all.

**I can now confirm this.** Despite passing *no* custom options to the embedded Python interpreter, I'm seeing the following debug output at executable startup:

    _heapq
    /home/leycec/py/betse/dist/betse/_heapq.cpython-33.so
    atexit
    /home/leycec/py/betse/dist/betse/atexit.cpython-33.so
    time
    /home/leycec/py/betse/dist/betse/time.cpython-33.so
    grp
    /home/leycec/py/betse/dist/betse/grp.cpython-33.so
    _bz2
    /home/leycec/py/betse/dist/betse/_bz2.cpython-33.so
    math
    /home/leycec/py/betse/dist/betse/math.cpython-33.so
    _hashlib
    /home/leycec/py/betse/dist/betse/_hashlib.cpython-33.so
    _random
    /home/leycec/py/betse/dist/betse/_random.cpython-33.so
    fcntl
    /home/leycec/py/betse/dist/betse/fcntl.cpython-33.so
    PIL._imaging
    /home/leycec/py/betse/dist/betse/PIL._imaging.cpython-33.so
    array
    /home/leycec/py/betse/dist/betse/array.cpython-33.so
    PyQt4.QtCore
    /home/leycec/py/betse/dist/betse/PyQt4.QtCore.cpython-33.so
    sip
    /home/leycec/py/betse/dist/betse/sip.cpython-33.so
    binascii
    /home/leycec/py/betse/dist/betse/binascii.cpython-33.so
    _lzma
    /home/leycec/py/betse/dist/betse/_lzma.cpython-33.so
    select
    /home/leycec/py/betse/dist/betse/select.cpython-33.so
    _posixsubprocess
    /home/leycec/py/betse/dist/betse/_posixsubprocess.cpython-33.so
    _datetime
    /home/leycec/py/betse/dist/betse/_datetime.cpython-33.so
    _socket
    /home/leycec/py/betse/dist/betse/_socket.cpython-33.so
    parser
    /home/leycec/py/betse/dist/betse/parser.cpython-33.so
    _pickle
    /home/leycec/py/betse/dist/betse/_pickle.cpython-33.so

Happily, I've hunted down and fixed this locally. Expect a pull request shortly. *Huzzah.*

**Comment by thorstenkampe** [comment]
Definitely not merged: line 472 and 473 in `loader/pyi_importers.py`
```
                        print(fullname)
                        print(filename)
```

**Comment by htgoebel** [comment]
> Definitely not merged

Of course not. The pull request is still waiting for an update from the author, see https://github.com/pyinstaller/pyinstaller/pull/1197#issuecomment-76921402

**Comment by leycec** [comment]
I am slow. Deadlines make me so. Such terrible rhyming: "Oh, no!"

In all seriousness, I'm swamped like a bloated corpse body in the bayou. Sorry for the delays on this and your other perspicacious commentary, [htgoebel](https://github.com/htgoebel). I should have a bit more time over the next few days to attend to everything. (*Should.*)

**Comment by htgoebel** [comment]
@leycec I have no hurry :-) I was just answering @thorstenkampe – for the case he wanted to submit an updated pull-request :-)
