### ISSUE TITLE
Warning while using --onefile and matplotlib

### ISSUE THREAD

**Issue by majkadaw** [pyinstaller/pyinstaller#1200]
I am building a standalone exe with the --onefile parameter.
While running the exe I always get the following warning:
WARNING: file already exists but should not: C:\Users\majkdawi\AppData\Local\Temp\_MEI37002\Include\fig.h
I figured out, that importing the matplotlib module causes the problem.

Using:
Python 2.7.2
pyinstaller 2.1
matplotlib 1.1.0 (even if there is a newer version, currently i have to use this one)

**Comment by matysek** [comment]
The warning should be fixed in `python3` branch.
