### ISSUE TITLE
__init__() got an unexpected keyword argument 'cipher'

### ISSUE THREAD

**Issue by nhubbard** [pyinstaller/pyinstaller#1201]
Hi!
I been using PyInstaller for a while now... it is awesome!
I recently started getting an error when compiling a target in my project's Makefile that ends with the title of this issue.
When I run ```pyinstaller --onedir paperpad.spec```, it gives me the following error:
```
pyinstaller --onedir paperpad.spec
37 INFO: UPX is not available.
62 INFO: Processing hook hook-os
167 INFO: Processing hook hook-time
170 INFO: Processing hook hook-cPickle
237 INFO: Processing hook hook-_sre
348 INFO: Processing hook hook-cStringIO
441 INFO: Processing hook hook-encodings
454 INFO: Processing hook hook-codecs
775 INFO: checking Tree
776 INFO: checking Tree
776 INFO: building out01-Tree.toc because directory ext changed
776 INFO: building Tree out01-Tree.toc
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==2.1', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/main.py", line 88, in run
    run_build(opts, spec_file, pyi_config)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/main.py", line 46, in run_build
    PyInstaller.build.main(pyi_config, spec_file, **opts.__dict__)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/build.py", line 1924, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/build.py", line 1873, in build
    execfile(spec)
  File "paperpad.spec", line 11, in <module>
    cipher=block_cipher)
TypeError: __init__() got an unexpected keyword argument 'cipher'
Makefile:71: recipe for target 'nodeps' failed
```

Any possible reason? My project uses PyQt4.

I didn't make any changes, but I recall that I recently updated PyInstaller to the latest stable version.

Thank you!

**Comment by htgoebel** [comment]
Am 05.03.2015 um 20:21 schrieb Nicholas Hubbard:
> |  File "paperpad.spec", line 11, in <module>
>     cipher=block_cipher)
> TypeError: __init__() got an unexpected keyword argument 'cipher'|

Well, the error message is sound and IMHO clear: remove the argument
`cipher` in the .spec file.

We may have had this as an argument in some versions, but I can not
really remember. Simple remove ist if you do not need it.

-- 
Schönen Gruß
Hartmut Goebel
Dipl.-Informatiker (univ), CISSP, CSSLP
Information Security Management, Security Governance, Secure Software
Development

Goebel Consult, Landshut
http://www.goebel-consult.de

Blog:
http://www.goebel-consult.de/blog/openstreetmap-karten-in-typo3-einbinden
Kolumne:
http://www.cissp-gefluester.de/2012-09-steht-ein-manta-fahrer-vor-der-uni

**Comment by nhubbard** [comment]
Okay, thank you @htgoebel!
