### ISSUE TITLE
ImportError: No module named sqlparse on Mac 10.10

### ISSUE THREAD

**Issue by vinodsharma** [pyinstaller/pyinstaller#1204]
Hi,
I'm facing an error while trying to build a binary for python program which uses sqlparse. can you please help me resolve this issue?

This is the error that I observed when tries to run the binary generated by the pyinstaller.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named sqlparse

However running the python program throws no such errors:

    python bundlesqlparse.py

    select *
    from foo

SourceCode:

    import sqlparse
    import sys 

    def main():
        print(sqlparse.format('select * from foo', reindent=True))

    if __name__ == "__main__":
        main()

Pyinstaller command & logs:

    pyinstaller bundlesqlparse.py

    7 INFO: wrote /private/tmp/xml/sqlparsebinary/bundlesqlparse.spec
    18 WARNING: You are running 64-bit Python: created binaries will only work on Mac OS X 10.6+.
    If you need 10.4-10.5 compatibility, run Python as a 32-bit binary with this command:

        VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 /usr/bin/python

    4027 INFO: UPX is not available.
    4040 INFO: Processing hook hook-os
    4109 INFO: Processing hook hook-time
    4110 INFO: Processing hook hook-cPickle
    4151 INFO: Processing hook hook-_sre
    4219 INFO: Processing hook hook-cStringIO
    4278 INFO: Processing hook hook-encodings 
    4287 INFO: Processing hook hook-codecs
    4499 INFO: Extending PYTHONPATH with /private/tmp/xml/sqlparsebinary
    4499 INFO: checking Analysis
    4499 INFO: building Analysis because out00-Analysis.toc non existent
    4499 INFO: running Analysis out00-Analysis.toc
    4506 INFO: Analyzing /Library/Python/2.7/site-packages/PyInstaller/loader/_pyi_bootstrap.py
    4513 INFO: Processing hook hook-os
    4522 INFO: Processing hook hook-site
    4531 INFO: Processing hook hook-encodings
    4594 INFO: Processing hook hook-time
    4597 INFO: Processing hook hook-cPickle
    4647 INFO: Processing hook hook-_sre
    4722 INFO: Processing hook hook-cStringIO
    4787 INFO: Processing hook hook-codecs
    5028 INFO: Processing hook hook-pydoc
    5096 INFO: Processing hook hook-email
    5128 INFO: Processing hook hook-httplib
    5148 INFO: Processing hook hook-email.message
    5317 INFO: Analyzing /Library/Python/2.7/site-packages/PyInstaller/loader/pyi_importers.py
    5346 INFO: Analyzing /Library/Python/2.7/site-packages/PyInstaller/loader/pyi_archive.py
    5372 INFO: Analyzing /Library/Python/2.7/site-packages/PyInstaller/loader/pyi_carchive.py
    5395 INFO: Analyzing /Library/Python/2.7/site-packages/PyInstaller/loader/pyi_os_path.py
    5397 INFO: Analyzing bundlesqlparse.py
    5398 INFO: Hidden import 'codecs' has been found otherwise
    5398 INFO: Hidden import 'encodings' has been found otherwise
    5399 INFO: Looking for run-time hooks
    5496 INFO: Using Python library /System/Library/Frameworks/Python.framework/Versions/2.7/Python
    5496 INFO: Adding Python library to binary dependencies
    5511 INFO: Warnings written to    
       /private/tmp/xml/sqlparsebinary/build/bundlesqlparse/warnbundlesqlparse.txt
    5517 INFO: checking PYZ
    5517 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
    5517 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
    6340 INFO: checking PKG
    6340 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
    6340 INFO: building PKG (CArchive) out00-PKG.pkg
    6349 INFO: checking EXE
    6349 INFO: rebuilding out00-EXE.toc because bundlesqlparse missing
    6349 INFO: building EXE from out00-EXE.toc
    6350 INFO: Appending archive to EXE  
                      /private/tmp/xml/sqlparsebinary/build/bundlesqlparse/bundlesqlparse
    6353 INFO: checking COLLECT
    6353 INFO: building COLLECT out00-COLLECT.toc

My sys.path values are:

    ['/private/tmp/xml/sqlparsebinary', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pyparsing-2.0.3-py2.7.egg', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pydicom-0.9.9-py2.7.egg', '/Library/Python/2.7/site-packages/pip-1.5.6-py2.7.egg', '/Library/Python/2.7/site-packages/lxml-3.4.2-py2.7-macosx-10.10-intel.egg', '/private/tmp/xml/sqlparsebinary', '/Library/Python/2.7/site-packages', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python27.zip', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-darwin', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/plat-mac/lib-scriptpackages', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-tk', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-old', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/lib-dynload', '/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages']

Please let me know if more information needed.
Thanks,
Vinod

**Comment by htgoebel** [comment]
Am 06.03.2015 um 21:08 schrieb vinodsharma:
>
> This is the error that I observed when tries to run the binary
> generated by the pyinstaller.
> Traceback (most recent call last):
> File "", line 1, in
> ImportError: No module named sqlparse
>

Thanks for your short example. Unfortunately I can not reproduce this
here using current PyInstaller developer-version and  |sqlparse| just
installed from pip.

Please folow the guide at
<https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong>.

-- 
Schönen Gruß
Hartmut Goebel
Dipl.-Informatiker (univ), CISSP, CSSLP
Information Security Management, Security Governance, Secure Software
Development

Goebel Consult, Landshut
http://www.goebel-consult.de

Blog:
http://www.goebel-consult.de/blog/openstreetmap-karten-in-typo3-einbinden
Kolumne:
http://www.cissp-gefluester.de/2011-10-aus-der-schublade-in-die-koepfe

**Comment by vinodsharma** [comment]
Thanks for replying & providing a useful link. I just removed the pyinstaller and installed it again from the pip. Now issue is gone. Seems like something was broken with my pyinstaller installation.

**Comment by ctismer** [comment]
Fuck you -- correct???

Sent from my Ei4Steve

**Comment by vinodsharma** [comment]
What????????
