### ISSUE TITLE
Python 3 tkinter hook(s)

### ISSUE THREAD

**Issue by AlexanderRavenheart** [pyinstaller/pyinstaller#1221]
On Windows 7 x64 with Python 3.4 , no virtual env, I had to modify the hook-_tkinter.py and pyi_rth__tkinter.py files to be able to package and execute a tkinter application.

Here are the modified files:
https://drive.google.com/open?id=0B8hvWNm-l9jFWDVmTVBSUUg1VTg&authuser=0
https://drive.google.com/open?id=0B8hvWNm-l9jFNndvLXB1Q1VucDQ&authuser=0

**Comment by htgoebel** [comment]
Hi, thanks. Can you please submit a pull-request?! This makes integrating your changes *much* more easier.

**Comment by AlexanderRavenheart** [comment]
Hi @htgoebel ,

1. I don't know how to do a pull-request.
2. The changes I made are hacky and will surely not work on other platforms or when using virtualenv.

**Comment by htgoebel** [comment]
> I don't know how to do a pull-request.

See <https://help.github.com/search/?utf8=%E2%9C%93&q=pull-request>

> The changes I made are hacky and will surely not work on other platforms or when using virtualenv.

:-( So I'm closing this issue, as we can nit use your work then.

**Comment by AlexanderRavenheart** [comment]
I understand you cannot use my work but can it or I help you in any way to make it work by default for others users that may end up in my situation?

**Comment by htgoebel** [comment]
Of course you can. This is why I asked for a pull-request. A pull-requests makes it as easy as possible for us to understand your changes and eventually discuss further improvements.

You can find more information at <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Contribute>. If you need more assistance, the mailing-list https://github.com/pyinstaller/pyinstaller/wiki/Community#mailing-list it the best way to ask.

**Comment by AlexanderRavenheart** [comment]
Also, why did you close this issue?
The issue is valid because it exists with the default hook files so why close it?

**Comment by htgoebel** [comment]
> Also, why did you close this issue?

Because he are not going to work on it. The original message basically says: "Hey, there are some files fixing some issues." This is nothing we can handle. Please submit a pull-request!
