### ISSUE TITLE
Menu bar not visible when building wx app

### ISSUE THREAD

**Issue by nsbasic** [pyinstaller/pyinstaller#1223]
When the app starts, the menu bar shows "Finder", instead of the app name as expects. The user needs to click on another app, then on the app again to see the app's menu bar. The app then works normally.

Here's a description of the identical problem (with a fix!)  with PyQt:
http://dvitonis.net/blog/2015/01/07/menu-bar-not-visible-when-building-pyqt-app-bundle-pyinstaller-mac-osx-mavericks-yosemite/

**Comment by htgoebel** [comment]
Duplicate, see #1215
