### ISSUE TITLE
added celery to hidden imports still presents importError

### ISSUE THREAD

**Issue by mattshirtliffe** [pyinstaller/pyinstaller#1228]
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: cannot import name Celery

**Comment by htgoebel** [comment]
This is *much* too less information for doing anything. Please provide more information as described in https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by mattshirtliffe** [comment]
Sorry I have created a simple application to to demo what I'm doing with pyinstaller. I get the import error after I have run pyinstaller main.spec

ImportError: cannot import name Celery
Python 2.7.6
Ubuntu 14.04.2 LTS
Flask 0.10.1
celery 3.1.17



from flask import Flask
from celery import Celery

app = Flask(__name__)

capp = Celery('tasks',broker='amqp://guest@localhost//')

@capp.task
def add(x,y):
    return x+y

@app.route("/")
def hello_you():
    return "Hello You"

if __name__ == "__main__":
    app.run()


Here is my spec file
# -*- mode: python -*-                                                                                                                                                                                       

block_cipher = None

a = Analysis(['simpleflaskapp/main.py'],
             pathex=['/home/vagrant'],
             hiddenimports=['celery'],
             hookspath=None,
             runtime_hooks=None,
             excludes=None,
             cipher=block_cipher)
pyz = PYZ(a.pure,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='main',
          debug=False,
          strip=None,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=True,
               name='main')

**Comment by htgoebel** [comment]
Okay, but did you follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged ?

**Comment by mattshirtliffe** [comment]
Yes

**Comment by htgoebel** [comment]
@mattshirtliffe I'm closing this for now. Please test with PyInstaller 3.0 or the current development head. If this still is an issue, please reopen and provide more details.
