### ISSUE TITLE
trying to include a config file with exe

### ISSUE THREAD

**Issue by mythreal** [pyinstaller/pyinstaller#1229]
I have been reading the PDF and am unsure about how to include a .json file with the exe. My exe requires this as a config file. Single file exe or multi-file. It is unclear to me if I can use the -r flag. if so how do you know the type? would it be JSON? then name.json? Then JSON? 

I have built a spec file as well to try that out.  I have tried 
collect = COLLECT(a.binaries + [('JSON', 'C:\\Desktop\\DT\\file.json', 'DATA')])
but the documentation is unclear there as well, at least to me. 
I thought I should ask if I should be using this as a hook file (datas)?
I have tryed moving the .json to the same path as the exe as that is where my code looks for it but that doesnt work either.
I have been searching for days and have found very little information on the subject.
Maybe im trying to do something unsupported?
Thanks for your time.

**Comment by htgoebel** [comment]
The `-r` option is for including a reasource from another file.

For including a data file like your json-file, please refer to http://pythonhosted.org/PyInstaller/#adapting-to-being-frozen and http://pythonhosted.org/PyInstaller/#accessing-data-files. If this is still unclear I suggest playing around – it works, other already did it :-)

**Comment by mythreal** [comment]
Thanks for the point in the right direction. I appreciate that. It's not that I havent been playing around with this for a week straight. Just looks like I was playing around with the wrong things.

Thanks again. 


     On Thursday, April 2, 2015 2:18 AM, Hartmut Goebel <notifications@github.com> wrote:
   

 Closed #1229.—
