### ISSUE TITLE
"six" Python Compatibility Library Unsupported

### ISSUE THREAD

**Issue by leycec** [pyinstaller/pyinstaller#1230]
PyInstaller's Python 2 and 3 branches both fail to support [six](https://pythonhosted.org/six), a popular Python 2 and 3 compatibility library. This is trivially shown by the following minimal length example, attempting to import `tkinter` in a version-agnostic manner:

    from six.moves import tkinter as Tk
    Tk._test()

Assuming the active Python interpreter to have been built with `tkinter` support, PyInstaller successfully freezes this example. However, the resulting executable fails:

    Traceback (most recent call last):
      File "<string>", line 3, in <module>
      File "/usr/lib64/python3.3/site-packages/six.py", line 89, in __get__
        result = self._resolve()
      File "/usr/lib64/python3.3/site-packages/six.py", line 108, in _resolve
        return _import_module(self.mod)
      File "/usr/lib64/python3.3/site-packages/six.py", line 79, in _import_module
        __import__(name)
    ImportError: No module named 'tkinter'
    
Running `pyi-archive_viewer out00-PYZ.pyz | grep tkinter` confirms that `tkinter.py` was *not* frozen into the executable, implying that PyInstaller failed to properly detect the `six`-specific import statement `from six.moves import tkinter as Tk`.

As a casual examination of `six.py` would reveal, properly detecting such statements will be non-trivial. Like, *really* non-trivial. `six` internally molests Python's runtime import system, including:

* Dynamically transforming itself from a module into a package.
* Dynamically defining a fake `six.moves` module.
* Dynamically defining a PEP 302-compliant importer for this module, converting imports of non-existent attributes from this module into conventional imports specific to the current Python version (e.g., converting `from six.moves import tkinter as Tk` into `import tkinter` under Python 3).

I probably shouldn't have, **but I did it anyway.** Against my (...clearly lacking) better judgement, I've added Python 3 support for `six` locally and will be submitting a pull request shortly.

**Comment by htgoebel** [comment]
I'm closing this issue, as there is #1231. Thanks!
