### ISSUE TITLE
Install instruction not clear

### ISSUE THREAD

**Issue by Peter0** [pyinstaller/pyinstaller#1232]
On https://github.com/pyinstaller/pyinstaller/wiki it reads

"Install latest stable version by issuing the command
pip install pyinstaller"

This leaves the question where to do that. At command line or at a python prompt?
As a occasional python user I'm unfamiliar with pip. Commandline simple doesn't know this command, python prompt gives "SyntaxError: invalid syntax", whereby the arrow ("^" character) points to the second "l" (last letter) of "install".

Python 2.7.9 (64-bit), Win 7/64
Please add a link or hint to become smarter.

**Comment by Peter0** [comment]
It seems to be a path problem, as the Scripts directory isn't included there. Giving "C:\Python27\Scripts\pip" (or similar) do the trick.

Read http://stackoverflow.com/questions/4750806/how-to-install-pip-on-windows and the answer http://stackoverflow.com/questions/4750806/how-to-install-pip-on-windows/21182892#21182892

– Peter

**Comment by htgoebel** [comment]
PyInstaller is a tool for python developers. And I'd expect Python developers to know who to use essential tools like `pip`. Because if you do not known them, how would you want to develop and debug your program then?
