### ISSUE TITLE
pyinstaller cannot include setuptools eggs

### ISSUE THREAD

**Issue by gao2733** [pyinstaller/pyinstaller#1238]
Hi,
I am using pyinstaller to build Openstack keystone CLI into a single executable.
Here is my spec file:
```
# -*- mode: python -*-
import glob
import os
import platform

PYVER = 'python2.6'
if os.path.exists('.venv/lib/python2.7'):
   PYVER = 'python2.7'

SETUP_EGG = glob.glob('./target/setuptools*.egg')[0]
BASE_PATH = '.venv/lib/' + PYVER + '/site-packages/'
EXE_NAME = "keystone"

a = Analysis([BASE_PATH + "keystone.py"],
             pathex=[SETUP_EGG],
             hiddenimports=[],
             hookspath=None)

pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name=os.path.join('dist', EXE_NAME),
          debug=False,
          strip=None,
          upx=True,
          console=True )
```
The 'keystone' was created, but when I executed it, I have:
  File "/home/dev/git/remote-client/build/keystone/out00-PYZ.pyz/pkg_resources", line 626, in resolve
pkg_resources.DistributionNotFound: setuptools

Once I put setuptools*.egg into dist, then it can run.
I just cannot have keystone executable to include the egg file.

**Comment by htgoebel** [comment]
`pkg_resources` is not supported, see https://github.com/pyinstaller/pyinstaller/wiki/FAQ#misc and https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Setuptools-Entry-Point.

Further look at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
