### ISSUE TITLE
Command line does not recognize pyinstaller Windows 7

### ISSUE THREAD

**Issue by gigapouch** [pyinstaller/pyinstaller#1239]
I typed the command that the PyInstaller Manual told me to into the command line, but I get an error message that says "'pyinstaller' is not recognized as an internal or external command, operable program or batch file."

What can I do to fix this?

**Comment by htgoebel** [comment]
PyInstaller is a tool for python developers. And I'd expect Python developers to know who to execute installed Python scripts/programs. Because if you do not known them, how would you want to develop and debug your program then?

**Comment by gigapouch** [comment]
I came to PyInstaller because I wanted to convert my Python programs to an executable file.

**Comment by tallforasmurf** [comment]
How did you install PyInstaller? If as documented (http://pythonhosted.org/PyInstaller/#installing-in-windows) and in particular, using pip-Win (https://sites.google.com/site/pydatalog/python/pip-for-windows) then after "pip install PyInstaller" there should be an executable script named pyinstaller that can be called from the command line.

However, now that I look at it, I agree that the Windows install section could use improvement. As it happens, I need to do a windows install myself in the next few days and I will make some notes and maybe improve the docs.

**Comment by gigapouch** [comment]
I downloaded the 64-bit setup .exe and ran it, at first. Just now I installed it using pip-Win.  Now how do I use it?

**Comment by htgoebel** [comment]
<https://docs.python.org/2/faq/windows.html#how-do-i-run-a-python-program-under-windows>, found by simple searching the internet for `python script execute windows`.

**Comment by gigapouch** [comment]
I know how to execute a python program, but I would like to know how to use *PyInstaller*. Even in the Python command line it is not recognized.

**Comment by gigapouch** [comment]
Is there an alternative you can recommend? I've already tried py2exe, which didn't work either.

**Comment by codewarrior0** [comment]
On Windows, you have to modify your PATH environ to include `c:\python27\scripts`. The Python installer doesn't add that to your path on its own.

**Comment by gigapouch** [comment]
I hope this isn't a dumb question, but how do you do that?

**Comment by JohnyMoSwag** [comment]
@gigapouch You'll find people more willing to help if you'd a least put forth a little effort. 

[How to add to windows path](https://www.google.com/search?q=how+to+add+to+windows+path&ie=UTF-8&oe=UTF-8&hl=en&client=safari)

**Comment by gigapouch** [comment]
Thanks everyone, it works now! Just had to locate it on my hard drive after it was finished compiling.

**Comment by oya163** [comment]
`easy_install pyinstaller` is also easy thing to do

**Comment by namzop** [comment]
> @gigapouch You'll find people more willing to help if you'd a least put forth a little effort.
> 
> [How to add to windows path](https://www.google.com/search?q=how+to+add+to+windows+path&ie=UTF-8&oe=UTF-8&hl=en&client=safari)

Bruh. Where is the file located?

**Comment by johnjroby** [comment]
> PyInstaller is a tool for python developers. And I'd expect Python developers to know who to execute installed Python scripts/programs. Because if you do not known them, how would you want to develop and debug your program then?

Youre those elitist types. If you dont have a supportive answer, what worth is you responding?

**Comment by rokm** [comment]
> Youre those elitist types. If you dont have a supportive answer, what worth is you responding?

It lets you know that you shouldn't waste your time waiting around for others to solve a problem that is yours to solve. Whether that's worth anything is up to you to decide, but this is an issue/bug tracker, not a Python Environment Management 101.
