### ISSUE TITLE
ctrl-z stopped problem

### ISSUE THREAD

**Issue by qetra** [pyinstaller/pyinstaller#1244]
Hi all.

I can't stop ctrl-z key with pyinstaller. Normally, I catch signal for ctrl-z. But, signal_handler isn't work in pyinstaller ?

What is problem ?

**Comment by htgoebel** [comment]
Hi,

what signal_handler are you talking about? Please provide more information, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#information-we-need

**Comment by htgoebel** [comment]
may be related: #208

**Comment by htgoebel** [comment]
I'm now closing this as duplicate. There has been no info since 10 months now, so I assume it is the same as 208.
