### ISSUE TITLE
test_requests fails with SSL-error

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1250]
@rbranche: When running test_requests stand-alone, i get this exception:
```requests.exceptions.SSLError: EOF occurred in violation of protocol (_ssl.c:581)```

Can you please submit a working version so we'll get tests passing at travis-ci. Thanks.

**Comment by rbranche** [comment]
Looking at this now.

It's working for me with requests=2.6.2

    test_requests (__main__.LibrariesTestCase) ... ok

(pyinstaller)local-3:tests{develop} ryan$ pip freeze
...
requests==2.6.2

**Comment by rbranche** [comment]
Yeah, I'm not able to reproduce with requests 2.6.2. 

@htgoebel: Does 2.6.2 work on travis-ci?

**Comment by htgoebel** [comment]
stackoverflow.com/questions/14102416/ had the answer: Need to use TLSv1.

@rbranche: This test fails in tracie-ci, but this may have different reasons. The output there is not helpful currently.
