### ISSUE TITLE
hookutils.get_homebrew_path returns bytes, needs to be str

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1253]
hookutils.get_homebrew_path() returns the string it gets from subprocess.check_output() which alas is a bytes type. The several functions that call it pass that value into os.path.join() resulting in an error, "builtins.TypeError: Can't mix strings and bytes in path components". The fix is a one-line change on line 389, replace

    return path

with

    return str(path,'UTF-8')

I have made this in my Python3 branch.

**Comment by htgoebel** [comment]
> I have made this in my Python3 branch.

Pull-request please :-)

**Comment by matysek** [comment]
This was already fixed probably in 2a853f6eeadcc8ffbe95468bfc9b7223d3e32cd0.
