### ISSUE TITLE
Pyinstaller-python3 winutils error.

### ISSUE THREAD

**Issue by nospam2k** [pyinstaller/pyinstaller#1257]
PyInstaller/hooks/hook-PyQt4.py line 21 says:

    from PyInstaller.utils.winutils import extend_system_path

It should be:

    from PyInstaller.utils.win32.winutils import extend_system_path

I imagine this problem is also in every other reference to winutils but I havn't confirmed.

**Comment by htgoebel** [comment]
Closed by 740d441.
