### ISSUE TITLE
PyQt5 QML libraries are bundled wrong

### ISSUE THREAD

**Issue by MartinBriza** [pyinstaller/pyinstaller#1260]
While bundling a QtQuick application using PyQt5 under Windows (and WINE), I've encountered a bunch of issues with QML support:
The QtQuick hook does create a folder "qml" containing some of the required libraries, namely "Models.2", "QtQml", "QtQuick.2", "StateMachine" and "uick.2" (sic). "uick.2" contains the same dlls as "QtQuick.2" but not the qmltypes and qmldir files.
Another problem is, "QtQuick" is not included at all, despite the fact the application won't start without it.
And finally, the application is searching for them in the root folder of the created package, not in the "qml" folder PyInstaller creates.

**Comment by htgoebel** [comment]
@MartinBriza I'm closing this for now. If this still is an issue, please reopen and provide current details.
