### ISSUE TITLE
Debug PyQt5 DLLs are included when not needed

### ISSUE THREAD

**Issue by MartinBriza** [pyinstaller/pyinstaller#1261]
Adding qt5[LIB]d.dll files along with qt5[LIB].dll ones is redundant and makes the created executables unnecessarily huge.

**Comment by htgoebel** [comment]
I'd appreciate a pull request, esp. since I do not have a windows system.

**Comment by MartinBriza** [comment]
I have no idea how to do fix that up unfortunately...
I'll stop by on your IRC channel some time to request help if that's okay.

**Comment by matysek** [comment]
@MartinBriza How this could be reproduced?
* What tools did you install and with that options? Just standard installation?
* Did you use `python3` branch?

**Comment by htgoebel** [comment]
@MartinBriza I'm clsing this for now. If this still is an issue, please reopen and provide more details.
