### ISSUE TITLE
python xml.sax being imported but still get parser error

### ISSUE THREAD

**Issue by brownzilla** [pyinstaller/pyinstaller#1268]
Hey there,

I'm trying to build my exe for my game that requires xml.sax.drivers and xml.sax.drivers2 and when I import them I just get another random ImportError no module named handler

**Comment by htgoebel** [comment]
To gelp you, wee need more information, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by matysek** [comment]
Closing, not enough info was provided.
