### ISSUE TITLE
lensfunpy not working, usage of __file__

### ISSUE THREAD

**Issue by neothemachine** [pyinstaller/pyinstaller#1271]
A user of my library [lensfunpy](https://pypi.python.org/pypi/lensfunpy) reported that it wasn't working with pyinstaller. Apparently packaged xml files to be loaded weren't found. I haven't tested this myself yet. Note that lensfunpy is a Cython wrapper around a native library (dll), and I guess what fails is the [following code](https://github.com/neothemachine/lensfunpy/blob/master/lensfunpy/__init__.py):

```python
    _ROOT = os.path.abspath(os.path.dirname(__file__))
    _xml_glob = os.path.join(_ROOT, 'db_files', '*.xml')
...
    paths = glob.glob(_xml_glob)
```

So what is pyinstaller doing in such a case where `__file__` is used? Is that supported? Do I have to change anything?

**Comment by tallforasmurf** [comment]
Have you read this? http://pythonhosted.org/PyInstaller/#adapting-to-being-frozen
Note that presence of the "frozen" attribute of sys applies also to apps bundled by cxfreeze, py2exe, and pyqtdeploy.

**Comment by htgoebel** [comment]
You may also want to provide a hook for inclusion into PyInstaller to collect these files when freezing. See https://pythonhosted.org/PyInstaller/#using-hook-files

**Comment by neothemachine** [comment]
The hook file is the solution, plus a bugfix in my library (I accidently overwrite `__file__` which then messes up path resolution of data files in pyinstaller's case).

The hook file hook-lensfunpy.py is:

```python
from hookutils import collect_data_files
datas = list(filter(lambda p: p[0].endswith('.xml'), collect_data_files('lensfunpy')))
hiddenimports = ['numpy', 'enum']
```

I let you know once I released a bugfix for my library, then you can include this hook file. Note that I filter the collected data files as it otherwise bundles .dll files twice.

**Comment by htgoebel** [comment]
Closing the issue, as there is a related pull request now.
