### ISSUE TITLE
Support for pkgutil.extend_path() missing

### ISSUE THREAD

**Issue by thorsant** [pyinstaller/pyinstaller#1283]
Hi

I have a package which spans multiple folders. In the documentation it is indicated that this can be solved by using hooks. Lets say my main package is called acme, and I have 3 different sub packages, which are located at different root paths as mentioned above, and these three pacakges are named utils, db and io. So I implement a hooks file for acme, hook-acme.py which looks something like this

    hiddenimports = ['io', 'utils', 'db']

The in my spec file I add the hooks path, and to the pathex I add the rootpath of the different packages . 

    Analysis(['main.py'], pathex = ['C:\\python\\io', 'C:\\Data\\python\\db', 'C:\\Data\\utils'], hookspath=[.\\hooks])

In C:\python\io there is a folder acme with a \__init__.py file and a subdir io, also with a \__init__.py file. Same goes for C:\python\db and C:\python\utils as well, i.e

* C:\
    * python
        * io
            * acme
                * \__init__.py
                *  io
                    * \__init__.py
        * db
            * acme
                * \__init__.py
                * db
                    * \__init__.py
        * utils
            * acme
                * \__init__.py
                * utils
                    * \__init__.py

The \__init__.py file in the acme folders contains the following lines
```
from pkgutil import extend_path
__path__ = extend_path(__path__, __name__)
```
The hook gets processed correctly and the build works fine. But when I run my program, it can only find the acme.io package. But if I set C:\\python\\\db first in the pathex, it can only find the acme.db package. How can I make this works sp all packages are detected properly?

**Comment by htgoebel** [comment]
As I already wrote on the mailinglist: Namespace packages are not yet  supported.

And since your ate not even talking about namespace packages, even further: I strongly doubt, your setup works in plain python. Does this work on your system?
``` python
import acme.db
import acme.utils
```

**Comment by thorsant** [comment]
It works when running from python using pkgutils and extend_path in the
__init__.py files of each of the acme folders.

Sorry for the name confusion, I am not into the python lingo yet as I have
mainly been programming in other languages.

**Comment by htgoebel** [comment]
Okay, so you *are* using namespace packages using the `pkgutils.extend_path` mechanism. You should know, that this is a lot of magic, even if it looks so simple.

So first of all, please try the current development head. But I'm afraid, this is not yet supported.

**Comment by thorsant** [comment]
Yes, I am, I'm just not in on the lingo, sorry about the confusion. Yes, it
looks simple...

Looked at the source of the develop branch and the hookutils.py, but at
least there it does not seem to be implemented, but I'll give it a try.

Could it be possible to compile each of the repos to binary archives and
include them using the PYZ object in the spec file of the project using
these io, db and utils libraries? Do you think that would work? Currently I
copy all the libs to a temporary folder in my build script, such that there
is no namespace package anymore, and then compile with pyinstaller. This
works, but not really preferable.

**Comment by htgoebel** [comment]
The easiest solution is to symlink (resp. copy) `utils/acme/utils` to `acme/utils`, `db/acme/db` to `acme/de` and so on. So you have a single directory containing the whole `acme` package`.

**Comment by thorsant** [comment]
Ok, thats what I have done so far as a part of the build process. I want to
keep them as separate repos though, since they are quite independent.

Thanks for the help sorting this out.

**Comment by htgoebel** [comment]
I think this is related to the issue with Namespaces not handled correctly.

**Comment by htgoebel** [comment]
@thorsant Please try (and use :-) the current `python3`-branch, support for `pkgutil.extend_path()` is implemented there already. The python3-branch works with python 2.7, too.

These test-cases basically work, so support for `pkgutil.extend_path()` is implemented and done already. **So consider this done**.

These test-cases work only "basically", because `pkgutil.extend_path()` behaves different from the other namespace-techniques if zipped eggs are involved. And this is the case in the current test-case. I'll rework and comment the test-case.
