### ISSUE TITLE
[Windows] QML File name case mismatch

### ISSUE THREAD

**Issue by seanegoodwin** [pyinstaller/pyinstaller#1284]
According to [this](https://bugreports.qt.io/browse/QTBUG-15706) Qt bug report, QML enforces filename case matching and fails out with an error ("File name case mismatch") if it finds a mismatch. Pyinstaller runs included files through os.path.normcase, which is what causes this problem to appear. 

As a test, I swapped out the instances of normcase with normpath, which fixed the issue. I don't know if lower case paths on Windows is desired, but if it's not this should work.

**Comment by htgoebel** [comment]
Can you please point to the *exact* place you changed? Please mind giving the branch you are using (I assume you are using some development version from github).

**Comment by htgoebel** [comment]
Closing since no more details have been given since five months now.
Anyway this could be related to #1676
