### ISSUE TITLE
pyinstaller

### ISSUE THREAD

**Issue by Shamasfs** [pyinstaller/pyinstaller#1292]
when i entered the command pyinstaller --name touchtracer ..\kivy27\examples\demo\touchtracer\main.py the command prompt through an error
 "'pyinstaller' is not recognized as an internal or external command, operable program or batch file."
how can i fix this prob.i have added path also but still its giving me same error.please help me out how can i do this.

**Comment by JMSwag** [comment]
Which OS are you using? How did you install Python? What's the current value of PATH?

**Comment by carlosperate** [comment]
I assume from the backslashes that you are trying this on Windows, how did you install pyinstaller?

**Comment by Shamasfs** [comment]
am using windows7 32bit os,and this is what the PATH C:\Python27

On Wed, Jun 10, 2015 at 8:38 AM, Carlos <notifications@github.com> wrote:

> I assume from the backslashes that you are trying this on Windows, how did
> you install pyinstaller?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyinstaller/pyinstaller/issues/1292#issuecomment-110801743>
> .
>



-- 
Warm Regard's
Shamshad Shirageri
nanoPix ISS (P) Ltd
Hubli

**Comment by carlosperate** [comment]
Follow the steps from the documentation and try again:
http://pythonhosted.org/PyInstaller/#verifying-the-installation

**Comment by Shamasfs** [comment]
ok thank you :-)

On Wed, Jun 10, 2015 at 9:58 PM, Carlos <notifications@github.com> wrote:

> Follow the steps from the documentation and try again:
> http://pythonhosted.org/PyInstaller/#verifying-the-installation
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pyinstaller/pyinstaller/issues/1292#issuecomment-110823179>
> .
>



-- 
Warm Regard's
Shamshad Shirageri
nanoPix ISS (P) Ltd
Hubli
