### ISSUE TITLE
Error loading Python DLL when there're Unicode chars in absolute path

### ISSUE THREAD

**Issue by CarlLee** [pyinstaller/pyinstaller#1295]
Program crashes and unable to load Python DLL when there're Unicode characters in absolute path.
The error is gone when after renaming all folder names containing Unicode characters to ASCII names.
Below is the error message.
```
D:\Projects\python\EMSStatistics\dist\中文路径>EMSStatistics.exe
Error loading Python DLL: D:\Projects\python\EMSSTA~1\dist\涓枃璺緞\python27
.dll (error code 126)
```

**Comment by codewarrior0** [comment]
That's when running in `onedir` mode (the default), right? Does the same thing happen if you run pyinstaller with `--onefile`?

**Comment by CarlLee** [comment]
Error occurred, too, but a different one. Here's the trace:
```
D:\Temp\pyinstaller_test\中文>hello
Traceback (most recent call last):
  File "<string>", line 21, in <module>
  File "D:\Programs\Python27\Lib\site-packages\PyInstaller\loader\pyi_importers.
py", line 507, in install
    sys.meta_path.append(FrozenImporter())
  File "D:\Programs\Python27\Lib\site-packages\PyInstaller\loader\pyi_importers.
py", line 156, in __init__
    raise ImportError("Can't load frozen modules.")
ImportError: Can't load frozen modules.
```

**Comment by codewarrior0** [comment]
There are a handful of issues about this with a few variations. The gist of it is the part of PyInstaller written in C isn't fully unicode-aware. It's supposed to use MS-DOS filenames as a kind of workaround, but it looks like it isn't even doing that correctly - your first error has a mix of MS-DOS filenames and unicode characters.

**Comment by CarlLee** [comment]
So it seems there should be some refactoring of C code.

**Comment by codewarrior0** [comment]
This is fixed in `python3` branch. The Python DLL is now loaded using the wide-string Windows API, so any unicode path is allowed.
