### ISSUE TITLE
Improve structure of test suite

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1299]
In pyinstaller code repository there are tests in directory 'tests'. These tests should be better organized and improved for running in a continuous integration system.

**Comment by htgoebel** [comment]
@matysek backporting this to the develop-branch become hard, esp. since you are intermixing these changes with other merges (would be better to us a branch by it's on for this issue) Where can I find the description on what you are doing here?

**Comment by htgoebel** [comment]
Martin, this came to my mind: We have a lot of tests (esp. old import-tests) which basically test the `Analysis` step. But currently we test the complete building, running and at last compare with a `.toc`.

What do you think about implementing some `test_Analysis` method with accepts the same parameters like `Analysis` does plus a list of expected entries. The later would replace the `.toc` filles.

**Comment by matysek** [comment]
@htgoebel Sounds like a good idea. This looks more like a candiate for unit tests: ./tests/unit/test_analysis.py

Do you have an implementation ready or should I look at it?

**Comment by htgoebel** [comment]
You are right, unit-tests are the right place for this. Go ahead, I don not have any code for this yet.

**Comment by matysek** [comment]
I'm closing this ticket. We've got a new decent test suite with continuous integration for Linux (Travis) and Windows (Appveyor). And it works with Python 2.7, 3.3, 3.4.

There are still a lot of tests that should be migrated to py.test but that will be solved later.
