### ISSUE TITLE
bootloader fails to build, user32 library not found

### ISSUE THREAD

**Issue by hansonap** [pyinstaller/pyinstaller#1304]
When trying to install pyinstaller for python3 (following instructions at bottom of page under experimental ports at https://github.com/pyinstaller/pyinstaller/tree/python3) it fails at 'checking for library user32: not found'

I have python 3.4 and MS VS 2013 express installed

**Comment by matysek** [comment]
Does the precompiled bootloader work for you?

**Comment by Csega** [comment]
I have the same problem. Where can I find the precompiled bootloader for Pyinstaller for Python 3?

**Comment by codewarrior0** [comment]
I can trivially reproduce this error:

```
Setting top to                           : [...]\bootloader
Setting out to                           : [...]\bootloader\build
Platform                                 : Windows-32bit detected
Checking for 'msvc' (C compiler)         : C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\BIN\amd64\CL.exe
Checking for library user32              : not found
```

I ran `waf` using a 32-bit python, and the config.log says it failed when trying to pass the `/MACHINE:x86` flag to the 64-bit version of LINK.exe. I'm not sure why waf is using the amd64 version of MSVC.

**Comment by codewarrior0** [comment]
Found out why, and now it's fixed. It might have been possible to use `--target-cpu` to override its cpu type choice, but it looks like that option was broken too.

**Comment by Csega** [comment]
Thanks, it works now! :)
