### ISSUE TITLE
import sqlite3 with --onefile gives warning since python 2.7.9

### ISSUE THREAD

**Issue by KevinArturia** [pyinstaller/pyinstaller#1305]
Running the generated .exe gives the following Warning message.

    WARNING: file already exists but should not: 
    C:\Users\kevin\AppData\Local\Temp_MEI40122\Include\pyconfig.h

Note that this does not happens with python 2.7.8.

This looks like the same as [issue 783](https://github.com/pyinstaller/pyinstaller/issues/783) but the proposed fix does not solve the issue.
I tried with the develop branch but this gives another error:

    Error loading Python DLL:
    C:\Users\kevin\AppData\Local\Temp_MEI38202\python27.dll

The python3 branch seems to work fine.

**Comment by htgoebel** [comment]
> The python3 branch seems to work fine.

You are using the python3-branch with Python 2.7.9?

**Comment by KevinArturia** [comment]
No, I am using it with python3.
I tried with python2 but I got an error message saying that pyinstaller requires python 2.7+ (although I am using python 2.7.9)

**Comment by htgoebel** [comment]
So the error occurring with Python 2.7.9 on the develop-branch is:
```
Error loading Python DLL:
C:\Users\kevin\AppData\Local\Temp_MEI38202\python27.dll
```
But there is no warning about file already exists.

Right?

When Using Python3 and the python3 branch, no error occurs. Right?

**Comment by KevinArturia** [comment]
The answer to both questions is yes.

**Comment by matysek** [comment]
Closing. User reported that `python3` branch works.
