### ISSUE TITLE
Different error every time ish

### ISSUE THREAD

**Issue by ysrd** [pyinstaller/pyinstaller#1308]
I know this isn't really a bug, but, I made a package that works on the machine I made it on. And I suspect it will work on every other machine with the same version of that distro but I tried to run it on others, like CentOS7 and ubuntu 14.04 but they all give me the import error for glibc, except every one of them reports it needs a different version of glibc. One has glibc 2.12 and wants glibc 2.14, one has glibc 2.17 and wants glibc2.18 The original is 2.21 so this error asking for different versions was giving me some  hope it might work on something other than the very latest version of fedora (22).
Unfortunately we used some very new features from wxpython and matplotlib and only fedora 22 has the latest versions of all of the hundreds of packages we needed. And my deadline is 2 days from this posting so I am not expecting much help with this, but more or less just wondering why the error is different every time. (Could it be that libc.so, who seems to be generating the error can't see the future that is now or it would cause issues with space and time... ;-)
Thanks, your program works very well 
Ysrd.

**Comment by htgoebel** [comment]
Thanks for your report. Sadly it is lacking too many information to help you. Please have a look at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#when-submitting-a-bug and provide more information for *both* your platform. I'm closing this issue. Please reopen it when providing the information. Thanks.

**Comment by ysrd** [comment]
Hi,
error occurs when you try to run my application, I don't think the application matters as it is the pyinstaller bootcode calling glibc.
pyinstaller 2.2.1dev. 
Built on Fedora 22 Linux,
attempted to run on (almost everything Linux) (try ubuntu 14.04 and Centos 7 as examples.)
Works fine on any Fedora 22 system, but fails on almost everything else. (IT does run on ArchBang)
The problem is probably in glibc but I want to know if anyone else has seen the same thing where the glibc version reported as required is different on different OSes. 
Like I said, I doubt this is a pyinstaller thing, I just want to know if anyone else sees the same error pattern I do. (And I don't see anyplace else I can post this discussion so if there is a chat forum thing please point me to it.)

**Comment by htgoebel** [comment]
> And I don't see anyplace else I can post this discussion so if there is a chat forum thing please point me to it.

The mailinglist is a better place if you just want to discuss. https://github.com/pyinstaller/pyinstaller/wiki/Community
