### ISSUE TITLE
argv emulation for drag and drop not working on OS X 64bit (opendocument events)

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1309]
The bootloader implements argv emulation when the user drag and drops file on the created .app file.

Notes:
- The implementation uses Carbon framework for this.
- The implementation works only with 32bit bootloaders.
- Carbon framework is missing some functions in 64bit environment. Especially the WaitNextEvent.
- We could either:
  - use other functions from Carbon that are available in Carbon
  - manage events with Cocoa but it would require use objC and probably rewrite some bootloader parts in objC

Resources:
- pull request #50 - previous implementation
- https://developer.apple.com/legacy/library/documentation/Carbon/Conceptual/Carbon_Event_Manager/Tasks/CarbonEventsTasks.html
- https://developer.apple.com/legacy/library/documentation/Carbon/Reference/Carbon_Event_Manager_Ref/
- https://developer.apple.com/legacy/library/documentation/Carbon/Reference/Carbon_Event_Manager_Ref/index.html#//apple_ref/doc/uid/TP30000135-CH1g-97760
- https://developer.apple.com/legacy/library/documentation/Carbon/Conceptual/Carbon_Event_Manager/Tasks/CarbonEventsTasks.html#//apple_ref/doc/uid/TP30000989-CH203-CIHFIHIF

**Comment by matysek** [comment]
@dhyams I checked that you dit the original implementation. Do you thing you could look at it or do you have any suggestions how to make argv emulation working for 64bit OS X?

**Comment by matysek** [comment]
This requires a lot of work, removing from `PyInstaller 3.0` milestone.

**Comment by AcidWeb** [comment]
Lack of this feature also break file association mechanism.

**Comment by matysek** [comment]
@AcidWeb Do you have any suggestion how this could be fixed?

**Comment by AcidWeb** [comment]
I don't know OS X well enough to comment this issue.

But I know that py2app approach work on all current OS X releases:
https://bitbucket.org/ronaldoussoren/py2app/src/79e351a5f029f80a2505ed2e2ff7a57a896a1a8f/py2app/bootstrap/argv_emulation.py?at=default&fileviewer=file-view-default

**Comment by AcidWeb** [comment]
I want small clarification. Documentation states:
> OpenDocument is the only AppleEvent the bootloader handles. If you want to handle other events, or events that are delivered after the program has launched, you must set up the appropriate handlers.
Handlers in application code or handlers in bootloader code?

**Comment by AcidWeb** [comment]
When I have .app created by py2app and already one instance of it is running and I try to open file associated to this application that first instance receive event ``QtCore.QEvent.FileOpen``.

In PyInstaller I got nothing. It is like application don't start at all second time.

And I'm not sure if PyInstaller simply require other approach to parse these events or just support for any event parsing is simply broken.

**Comment by AcidWeb** [comment]
> PyInstaller spawns a child process as it is bootstrapping the executable, and your Python code runs in this child process. By experimentation, it was found that the AppleEvents never make it to the child process.

OK. This explain much.

**Comment by giumas** [comment]
@AcidWeb Has there been any progress on the issue? I am hitting the same problem with wxPython

**Comment by AcidWeb** [comment]
I'm not working on this issue.
If you really need it - use py2app.

**Comment by giumas** [comment]
@matysek Do you have plan to work on this ticket? I would like to help on solve this issue... but Mac world is quite obscure to me!

**Comment by matysek** [comment]
@giumas not any particular plan yet. The only plan I could think of is doing it similar as py2 app does. It could be helpful if you could find out what from the py2 app principles could be applied to pyinstaller.

**Comment by LevN0** [comment]
I too, as apparently are a lot of projects, am waiting on this feature/bug-fix. I hope the maintainers will make it a bigger priority.

**Comment by dhyams** [comment]
I did the original implementation of argv emulation on OSX for 32-bit.  I am not sure what is broken now, but I am getting a Mac very soon, so I do plan to look into it.  No guarantees on success or the timetable.

I also don't have any special knowledge on the Mac platform at all; the original implementation was just done just by force of will.

**Comment by dhyams** [comment]
I believe I have a solution for this in a branch.  I'm wondering if I can get some volunteers for testing this functionality.  It's branch argvemu_osx64 from my fork of the pyinstaller repo.

https://github.com/dhyams/pyinstaller.git

**Comment by dhyams** [comment]
Pull request here: https://github.com/pyinstaller/pyinstaller/pull/2219

**Comment by cculianu** [comment]
URI event handling is still broken for me on pyinstaller based apps.  Basically my apps on OSX never receive the URI events when a user opens one of my custom schemes that my app defines in its info.plist.

Is there any plan to work on this?

Or.. is there a known workaround?

Or should I switch back to py2app?

**Comment by cculianu** [comment]
FYI, I fixed this. See my PR here: #3832 .

**Comment by Legorooj** [comment]
Closing - stale
