### ISSUE TITLE
PyGame - ImportError: No module named base

### ISSUE THREAD

**Issue by koutoftimer** [pyinstaller/pyinstaller#1312]
Building simple clicker, but I'm not satisfied with FPS of javascript, so I decided to use something faster. As one of options: PyGame. I'm working without virtual enviroment under `Ubuntu 14.4.2` with pygame installed via `# apt-get install python-pygame`.

I already have some primitive ui system with single external dependency - pygame. I'm  running `pyinstall`, than trying to start executable from `dist` folder.

    $ ./dist/miner/miner 
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in load_module
        exec(bytecode, module.__dict__)
      File "/home/ruslan/Documents/Programing/miner-pygame-build/build/miner/out00-PYZ.pyz/pygame", line 99, in <module>
    ImportError: No module named base
    
Extended logs:

    $ pip freeze
    PyInstaller==2.1
    pygame==1.9.1release

    $ pip -V
    pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

    $ python -V
    Python 2.7.6

    $ pyinstaller miner.py 
    6 INFO: wrote /home/ruslan/Documents/Programing/miner-pygame/miner.spec
    28 INFO: UPX is not available.
    45 INFO: Processing hook hook-os
    129 INFO: Processing hook hook-time
    130 INFO: Processing hook hook-cPickle
    185 INFO: Processing hook hook-_sre
    272 INFO: Processing hook hook-cStringIO
    349 INFO: Processing hook hook-encodings
    360 INFO: Processing hook hook-codecs
    626 INFO: Extending PYTHONPATH with /home/ruslan/Documents/Programing/miner-pygame
    626 INFO: checking Analysis
    627 INFO: building Analysis because out00-Analysis.toc non existent
    627 INFO: running Analysis out00-Analysis.toc
    663 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/_pyi_bootstrap.py
    677 INFO: Processing hook hook-os
    688 INFO: Processing hook hook-site
    700 INFO: Processing hook hook-encodings
    779 INFO: Processing hook hook-time
    781 INFO: Processing hook hook-cPickle
    837 INFO: Processing hook hook-_sre
    928 INFO: Processing hook hook-cStringIO
    1017 INFO: Processing hook hook-codecs
    1318 INFO: Processing hook hook-pydoc
    1413 INFO: Processing hook hook-email
    1456 INFO: Processing hook hook-httplib
    1483 INFO: Processing hook hook-email.message
    1523 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py
    1552 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_archive.py
    1581 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_carchive.py
    1609 INFO: Analyzing /usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_os_path.py
    1613 INFO: Analyzing miner.py
    1627 INFO: Processing hook hook-pygame
    2176 INFO: Processing hook hook-parser
    2251 INFO: Processing hook hook-distutils
    2359 INFO: Processing hook hook-sysconfig
    2543 INFO: Processing hook hook-setuptools
    2712 INFO: Processing hook hook-xml
    2792 INFO: Processing hook hook-xml.sax
    2812 INFO: Processing hook hook-pyexpat
    2862 INFO: Processing hook hook-xml.dom
    2868 INFO: Processing hook hook-xml.dom.domreg
    3339 INFO: Hidden import 'codecs' has been found otherwise
    3340 INFO: Hidden import 'encodings' has been found otherwise
    3340 INFO: Looking for run-time hooks
    3341 INFO: Analyzing rthook /usr/local/lib/python2.7/dist-    packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py
    objdump: section '.dynamic' mentioned in a -j option, but not found in any input file
    5238 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
    5239 INFO: Adding Python library to binary dependencies
    5272 INFO: Warnings written to /home/ruslan/Documents/Programing/miner-    pygame/build/miner/warnminer.txt
    5294 INFO: checking PYZ
    5294 INFO: rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
    5294 INFO: building PYZ (ZlibArchive) out00-PYZ.toc
    7475 INFO: checking PKG
    7475 INFO: rebuilding out00-PKG.toc because out00-PKG.pkg is missing
    7475 INFO: building PKG (CArchive) out00-PKG.pkg
    objdump: section '.dynamic' mentioned in a -j option, but not found in any input file
    7543 INFO: checking EXE
    7543 INFO: rebuilding out00-EXE.toc because miner missing
    7543 INFO: building EXE from out00-EXE.toc
    7545 INFO: Appending archive to EXE /home/ruslan/Documents/Programing/miner-    pygame/build/miner/miner
    7572 INFO: checking COLLECT
    7573 INFO: building COLLECT out00-COLLECT.toc
    
    $ ./dist/miner/miner 
    Traceback (most recent call last):
      File "<string>", line 2, in <module>
      File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyi_importers.py", line 270, in     load_module
        exec(bytecode, module.__dict__)
      File "/home/ruslan/Documents/Programing/miner-pygame/build/miner/out00-PYZ.pyz/pygame",     line 99, in <module>
    ImportError: No module named base

**Comment by htgoebel** [comment]
Please follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong, esp. use the most recent development version. If this does not help, please see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs and reopen this ticket.

Also see #819 (which is missing any example, too)
