### ISSUE TITLE
Several (pointless) VisualC warnings and pyconfig errors. And apparent Fix for them

### ISSUE THREAD

**Issue by Viissataa** [pyinstaller/pyinstaller#1320]
At least with --onefile, the compiler prints multiple warnings of  MS Visual C 9 libraries that it namely "was unable to find". However the .exe is created and works fine, even with modules the warnings concern. When starting, it finally warns that "pyconfig.h already exists" in Temp folder, but afterwards works again fine. There is an apparent fix: in build.py of PyINstaller in method append, when you change "if tpl[2] == "BINARY" into "if tpl[2] in ["BINARY", "DATA", "binary","data"]" all these errors disappear.

**Comment by matysek** [comment]
Hi @Viissataa,

thanks for reporting the issue but your description does not tell enough information like - pyinstaller version, detailed pyinstaller output or code example for reproducing it.

**Comment by matysek** [comment]
I think this should be fixed in `python3` branch.
