### ISSUE TITLE
Split archive classes into readers and writers

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1321]
This allows for differentiating between reading/importing (where we need to imp_lock, open/close and seek often) and writing (where we do not need to so this)

Beside this saves some (neglectable) space in the frozen exe

**Comment by matysek** [comment]
* Do you mean the modules in ./PyInstaller/loader?
* Is this meant only for python3 branch?
* I think a good idea is to keep readers in ./PyInstaller/loader/ and move writers to ./PyInstaller/

**Comment by htgoebel** [comment]
Yes to all three questions.
