### ISSUE TITLE
_pyi_bootstrap.NullWriter: is missing attribute `encoding`

### ISSUE THREAD

**Issue by CarstenGrohmann** [pyinstaller/pyinstaller#1324]
Hi,

I use PyInstaller to create a non-console executable on Windows for my wxPython based GUI application. 

The application runs fine if I enable the console output with `EXE(..., console=True)`. But it failed silently without console `EXE(..., console=False)`. The application returns always with errorlevel 0.

Using an own NullWriter class extended by the `encoding` attribute solves my issue.

I assume the error is triggered by logging.StreamHandler during writing unicode to stdout/stderr in combination with redirected stdout/stderr using instances of `NullWriter`.

My environment:
* Python: 2.7.8
* PyInstaller: 2.1
* wxPython: 2.8.12.1 (msw unicode)
* OS: Windows XP

Suggested implementation:
```python
class NullWriter:
    softspace = 0
    encoding = 'UTF-8'

    def write(*args):
        pass

    def flush(*args):
        pass
```

Please consider to add the `softspace` attribute to your `NullWriter` class additionally to the `encoding` attribute.

Regards,
Carsten

**Comment by CarstenGrohmann** [comment]
Would it be possible to fix this issue with a hook instead of changing the source code?

**Comment by htgoebel** [comment]
If I understand this correctly, your application uses `logging`. And it fails when run in windowed mode. Correct?

PyInstaller does not add *any* logging to the applications. So if your application fails, I'd strongly assume some error in your application. Does your application run if you start it (unfrozen) via `pythonw`? Have you search the internet about using `logging` in a windowed mode?

**Comment by CarstenGrohmann** [comment]
Yes, my application uses `logging`. Yes, it fails if running in windows mode. The application runs fine without PyInstaller on Linux and Windows (via `python.exe` and `pythonw.exe`).

Yes, I've searched the internet and found some interesting entries e.g. usage of 
```python
sys.stdout = tempfile.TemporaryFile()
sys.stderr = tempfile.TemporaryFile()
```
I've tested the `tempfile` example successfully. It's a good workaround.

I'm not familiar with the PyInstaller code, but I think the root cause is the missing `encoding` attribute in the PyInstaller `NullWriter` implementation used as a drop-in replacement for `sys.stdout` and `sys.stderr`.

The Python documentation (https://docs.python.org/2.7/library/stdtypes.html#file-objects) strengthens my assumption:
> file.encoding
> The encoding that this file uses. When Unicode strings are written to a file, they will be converted to byte strings using this encoding. In addition, when the file is connected to a terminal, the attribute gives the encoding that the terminal is likely to use (that information might be incorrect if the user has misconfigured the terminal). The attribute is read-only and may not be present on all file-like objects. It may also be None, in which case the file uses the system default encoding for converting Unicode strings.

Regards,
Carsten

**Comment by htgoebel** [comment]
> I think the root cause is the missing encoding attribute in the PyInstaller NullWriter implementation used as a drop-in replacement for sys.stdout and sys.stderr

Ah, now I got it.
