### ISSUE TITLE
Python3 branch will not start on Python 2.7.8

### ISSUE THREAD

**Issue by astamp** [pyinstaller/pyinstaller#1327]
In the tip of the python3 branch: (efd24aaba321738bc2ee0af031f31f24801ecd0f) PyInstaller will not start on Python 2.7.8 on Windows.

The following error is reported:
PyInstaller requires at least Python 2.7 or 3.3+.

It appears that the version check in PyInstaller/__init__.py on line 18 will fail on the Python 3.3 case for Python 2.7 as well.

    # Fail hard if Python does not have minimum required version
    if sys.version_info < (2, 7) or sys.version_info < (3, 3):
        raise SystemExit('PyInstaller requires at least Python 2.7 or 3.3+.')

Changing this to the code below will allow PyInstaller to properly start on Python 2.7.

    # Fail hard if Python does not have minimum required version
    if ((sys.version_info.major == 2 and sys.version_info < (2, 7)) or
            (sys.version_info.major == 3 and sys.version_info < (3, 3))):
        raise SystemExit('PyInstaller requires at least Python 2.7 or 3.3+.')

**Comment by htgoebel** [comment]
Thanks for pointing this out.

But to be honest: AS of now PyInstaller will not run on Python 2.7, even if we fix this, simply because there are some places where the python3-branch is not compatible with Python 2.7

**Comment by astamp** [comment]
Thanks for the quick response.  Is the plan for the python3-branch to eventually work with Python 2.7?

**Comment by codewarrior0** [comment]
I was JUST about to ask that! There are a few features on the python3 branch I'd like to try on 2.7.

**Comment by matysek** [comment]
> a few features on the python3 branch I'd like to try on 2.7.

@codewarrior0 @astamp The main obstacle for Python 2.7 in python3 branch is the bootloader. We would like to have one bootloader that would work with python 3 and python 2.7. But that is not as straightforward as I though.

**Comment by htgoebel** [comment]
@matysek 
> We would like to have one bootloader that would work with python 3 and python 2.7. But that is not as straightforward as I though.

I was already wondering what has to been doe to make the bootloader work for Python 2.7, too. Could you please document the issues somewhere, maybe directly in the code? Or did you already and I've overlooked?

**Comment by htgoebel** [comment]
(Why was this issue not closed automatically when I pushed 0ecf0ac?)

**Comment by matysek** [comment]
@htgoebel I put down these notes about that: https://github.com/pyinstaller/pyinstaller/wiki/Python-3-Port#python-2-compatibility

I hope it is understandable.

**Comment by htgoebel** [comment]
@matysek Thanks for the notes. They look okay for me at a first glance.
