### ISSUE TITLE
Mac OS X: qt_menu.nib not necessary with Qt 5.4 / PyQt5 hooks

### ISSUE THREAD

**Issue by pandel** [pyinstaller/pyinstaller#1332]
Hi!

I tried to build a mac app bundle from my pyqt5 based python3 script via pyinstaller, but somehow, it is not working.

    Python3.4.3 - installed via pkg installer from python.org to /Library/Frameworks/Python.framework
    Qt 5.4.2 - installed via offline installer from qt.io to /Users/<username>/Qt5.4.2 as proposed by the installer
    PyQt5/sip - build from source, installed via setup.py

First, I had to add "from PyInstaller.build import Tree" to the spec file, because python complained about missing "Tree". Then, when pyinstaller went through the pyqt hooks, it started complaining about missing 'qt_menu.nib'. After hours of googling I can only say, that this directory simply doesn't exist and I absolutely have no clue where to find it, or if I have to create it or whatever. Also, this directory seems to be not necessary when running the script via command line, the script works as expected...

What can I do to fix this?

Regards,
Holger

**Comment by matysek** [comment]
Recently I refactored PyInstaller to have a clear namespace of API for .spec file.  I added 'Tree' to the namespace. I think it should fix the import in spec file. Feel free to add more symbols to namespace if you think it should be there.

**Comment by matysek** [comment]
Regarding qt_menu.nib PyInstaller should probably include more paths where it is looking for it.

**Comment by pandel** [comment]
Ah I see, many thanks for that! ...and regarding the paths... this qt_menu.nib is missing completely in Qt 5.4.2. At the moment I'm trying to build qt from source to see, if the missing dir is created. Alternatively, I'll try to install the whole python3 environment via homebrew. Let's hope for the best...

**Comment by matysek** [comment]
@pandel I installed Qt5.5 from qt.io and really there is no qt_menu.nib. It is necessary to run the .app bundle of a PyQt app.

Does your .app bundle work without qt_menu.nib? 

If so then maybe recent Qt5 dropped the necessity to have qt_menu.nib or it could be a changed in any recent OS X version?

**Comment by pandel** [comment]
I think I don't understand... I go to my source folder, open a terminal and run "python3 script.py" -> UI comes up, everything works including loading resources from qt resource file, ui files. etc. But when I try to build a .app bundle with pyinstaller, then it asks me for qt_menu.nib. Perhaps I'm doing something wrong...

**Comment by matysek** [comment]
@pandel Could you hack the PyInstaller code that it skips the inclusion of qt_menu.nib?
I'd like to make sure that your app created by pyinstaller will work without it.

**Comment by pandel** [comment]
Yep!  I'll give it a try and report!

**Comment by pandel** [comment]
YES! That did the trick!

Basically, I commented out the nib thing line

     "datas = [
    #          (qt5_menu_nib_dir(), ''),
    ]" 

at the end of hook-PyQt5.py and it works!

Thanks for your help!

**Comment by matysek** [comment]
Thanks for reporting this and testing. I will reopen it since we need to find out what has been changed and in what cases pyinstaller should handle that in PyQt5 hooks.

**Comment by pandel** [comment]
Ok, thanks ;-)!

**Comment by rdrey** [comment]
Hey @pandel 

Congrats on getting it to work, I'm jealous. :stuck_out_tongue_winking_eye:

I'm running the same versions of python & Qt5 as you, installed PyQt5, SIP & pyinstaller all in the same virtualenv via setup.py's. My pyinstaller is the python3 branch (d7e2fae).

Did you have to copy your `Qt*.framework` files somewhere else first? Did you run `pyinstaller` with `QT5DIR=` env variable?

I'm stuck getting a ton of errors while running `pyinstaller`:

    5294 INFO: Processing hook   hook-PyQt5.QtWidgets.py
    5295 INFO: Processing hook   hook-xml.py
    5636 INFO: Processing hook   hook-xml.sax.py
    5638 INFO: Analyzing run-time hooks ...
    5641 INFO: Including run-time hook 'pyi_rth_qt5.py'
    5643 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
    5649 INFO: Looking for dynamic libraries
    5654 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /Users/rainer/work/Qt/5.5/clang_64/plugins/iconengines/libqsvgicon.dylib)
    5654 ERROR: Can not find path ./QtSvg.framework/Versions/5/QtSvg (needed by /Users/rainer/work/Qt/5.5/clang_64/plugins/iconengines/libqsvgicon.dylib)
    5654 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /Users/rainer/work/Qt/5.5/clang_64/plugins/iconengines/libqsvgicon.dylib)
    5654 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /Users/rainer/work/Qt/5.5/clang_64/plugins/iconengines/libqsvgicon.dylib)
    ...

Do you have any ideas?

**Comment by pandel** [comment]
Hi!

At first, we are not using the same versions! I use 5.**4.2** for PyQt and Qt, you are using 5.5 obviously. Might be a problem...

Second, I did not have to copy anything, as installed everything (python3, pyqt5, qt5 libs) via homebrew (http://brew.sh/), what made everything verrryyyy easy ;-) But from what I conclude, it should have worked with a normal python3 installation and a qt5 setup via qt online installer within the user directory like yours. But beware, you have to setup a ``.profile`` file, settings PATH and such to reflect your setup and make python3 and pyinstaller find your libs...

I don't have the chance to check out your setup, as I don't have time to revert to the manually installed python/pyqt/qt solution, sorry.

If you want to save time, go get rid of all the manually installed things and install via homebrew, it saves a lot of time and set's it all up for you very nicely ;-)

**Comment by Tamriel** [comment]
I installed `python3`, `qt5` and `pyqt5` via brew on a fresh VM.
I cloned this repo, checked out the python3 branch and ran `python3 setup.py install`.
But when I run `pyinstaller my_program.py` I get issue #1301.
What have you done different so it works for you?

**Comment by pandel** [comment]
????? It's all here in the thread! Did you read it? Please read your error log thoroughly... You got:

    15400 ERROR: Cannot find qt_menu.nib directory
    Traceback (most recent call last):

Find **hook-PyQt5.py**, comment line as follows, reinstall pyinstaller and you're good to go...

    if is_darwin:
        datas = [
    #        (qt5_menu_nib_dir(), ''),
        ]

**Comment by rdrey** [comment]
Wow, thanks! I ignored all my reservations and went ahead without a virtualenv (using global python3) and everything installed via homebrew and it worked perfectly.

(I decided to first try out bundling my side-project idea before coding anything "real" and I'm glad I can get started now.) :D

**Comment by htgoebel** [comment]
@pandel This sounds like `hook-PyQt5` requires a fix?! Why is the qt_menu.nib not required in your setup?

**Comment by pandel** [comment]
That's a really good question and I absolutely don't know! I even don't know what qt5_menu.nib is, or better, was good for... perhaps it has something to do with wether you precompile the Qt5 .ui files to Python code, or if you bind them at runtime via the PyQT uic module as I do...

**Comment by rdrey** [comment]
@htgoebel I can confirm that it's no longer necessary in Qt 5.5.0 on OS X... Haven't tried out any other platforms, though.

**Comment by htgoebel** [comment]
@rdey: Okay, so how to detect it's 5.5.0 and not 5.4?

**Comment by rdrey** [comment]
@htgoebel 

    >>> from PyQt5.QtCore import QT_VERSION_STR
    >>> print(QT_VERSION_STR)
    5.5.0

But it looked like @pandel's `Qt5.4.2` also needed it commented out.

It's probably safe to say that `Qt>5.4` doesn't have a `qt_menu.nib`

I'll try to send a pull request once I've googled how to parse semantic version numbers cleverly in python.

**Comment by htgoebel** [comment]
@rdrey  You may want to have a look at and follow #1373

**Comment by rdrey** [comment]
@htgoebel Sorry, took me a while to get back to my little side project. Let me know if that looks ok, please.
