### ISSUE TITLE
OS X - in manual recommend using homebrew or macports.

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1333]
The manual should recommend OS X users to use either homebrew or macports for Python usage on OS X.

**Comment by tallforasmurf** [comment]
Why, particularly? I have installed Python 3.3 and later 3.4 from the python.org distribution, into /Library/Frameworks/Python.framework/Versions. Then you set the Versions/Current link and always set PYTHONHOME to /Library/Frameworks/Python.framework/Versions/Current.

**Comment by matysek** [comment]
@tallforasmurf These are the reasons I think of:
* with Python you usually need some 3rd party modules like PyQt, ...
* for not all modules osx binaries are provided (PyQt, ...)
* some modules require additional libraries
* users end up with compiling libraries and modules themselves
* users then report issues that are related to environment setup and not directly to PyInstaller
* homebrew/macports offer many libraries and python modules ready to compile and use

**Comment by leycec** [comment]
Gotta concur with @matysek on this one. Homebrew and/or MacPorts are *invaluable* for installing non-trivial application dependencies – particularly, non-pure-Python requiring configuration, compilation, and installation of low-level shared libraries (e.g., Matplotlib, Numpy, Scipy, PySide, PyQt).

All the _usual_ offenders, really. I'd personally give the nod to Homebrew, which I found to be substantially more helpful than MacPorts. (MacPorts makes it basically infeasible to install older versions of dependencies, whereas this is trivial in Homebrew.)

**Comment by matysek** [comment]
@tallforasmurf could you please do this too while working on manual?

**Comment by tallforasmurf** [comment]
Done in pull request
