### ISSUE TITLE
Windowed exe will not run when running external application with subprocess and redirected stdout

### ISSUE THREAD

**Issue by durden** [pyinstaller/pyinstaller#1339]
I've been using Pyinstaller for a while for a PyQt4 application.  It has worked great but recently I decided to change my build to be windowed with no console, the -w option.  This new build **almost** works. I'm able to double-click the exe and run fine.  However, I cannot run this exe from a Windows command window.  I've narrowed the problem down to calling another executable that writes to stdout.

I've read all over that windowed applications cannot write to stdout.  Thus, my application uses logging and never writes to stdout.  However, this external executable (not written by me) does write to stdout. I typically ran the external executable in my Pyinstaller-built application with the following code:

```python
    try:
        output = subprocess.check_output(exe)
    except Exception as err:
        print 'Unable to verify license %s' % (err)
        sys.exit(-1)
```

So, when switching to a windowed application I changed the code to something like the following that redirects this command's output to a file.

```python
tmp_file = '.license_output'

    try:
        with open(tmp_file, 'w+') as file_obj:
            proc = subprocess.Popen(exe, stdout=file_obj)
            ret = proc.wait()

        if ret != 0:
            print 'Unable to verify license %s' % (err)
            sys.exit(-1)

        with open(tmp_file, 'r') as file_obj:
            output = file_obj.read()
    except Exception as err:
        print 'Unable to verify license %s' % (err)
        sys.exit(-1)
```

Unfortunately, the windowed executable still does not run from the Windows command prompt.  Is this a problem with PyInstaller?  My redirection code seems to be working but when running the PyInstaller-built application it seems to exit after the `POpen` line.

**Comment by durden** [comment]
I forgot to mention I'm using the 2.1 release version of PyInstaller on Windows 7.

**Comment by matysek** [comment]
* Have you tried the 'develop' version?
* Does your redirection work when using pyisntaller without the -w option?

**Comment by durden** [comment]
I just tried the HEAD of the 'develop' branch [a71bbff4](https://github.com/pyinstaller/pyinstaller/commit/a71bbff4610178bc60a5afda04bef4c4248a5a91), and the same problem exists.

I also double checked my redirection and it works when not using the -w argument and running from the command prompt.  The redirection also works when using the -w argument and double-clicking the exe in Windows Explorer. So, the only combination that doesn't work is using the -w argument and trying to run the executable from the command prompt.

**Comment by htgoebel** [comment]
> However, I cannot run this exe from a Windows command window
> [...]
> still does not run from the Windows command prompt

What exactly do you mean with this? What is the traceback? Does your test-program run when not frozen?

**Comment by durden** [comment]
Sorry, I wasn't very specific.  My test program runs when it is not frozen without any problems.  Also the test program runs without any problems when **not** using the -w option.

I see no output or traceback when running my test program built with the -w option. I run the .exe from the command prompt, and I immediately get the command prompt back without anything else.

**Comment by htgoebel** [comment]
The script you showed in https://github.com/pyinstaller/pyinstaller/issues/1339#issue-96034177 is the one failing and is (almost) complete? I'm asking because you you wrote something abut PyQT4.

Please try redirecting your stderr at the very beginning of you program `sys.stderr = open('stderr.txt', 'w')` and add print-statements behind every other statement like this: `print  >> sys.stderr, "11"`

**Comment by durden** [comment]
No, my application is a PyQt4 application. The code in the comment is just the code to run an external exe to verify a 'license', which runs a C executable that logs something to an internal database. My PyQt4 application must run this C executable, which sadly only outputs information to stdout. So, I'm trying to redirect that stdout to a file then read the file contents with my PyQt4 application.

My PyQt4 application correctly gets and reads the redirected output in a file if I run my PyQt4 application by double-clicking the exe in Windows Explorer. It also runs correctly with no changes from the command prompt if I remove the -w argument.

**Comment by durden** [comment]
Thanks for the debug tip.  I ran with the following debug and the stderr.txt file only gets '1', '2', and '3' in it.  So the app seems to crash for some reason during the call to `POpen`. However, that's assuming the exe correctly flushed stderr I guess.

```python
    print >> sys.stderr, '1'
    # See verify_license.py for more information on why this is done with
    # subprocess
    tmp_file = '.license_output'

    print >> sys.stderr, '2'
    try:
        with open(tmp_file, 'w+') as file_obj:
            print >> sys.stderr, '3'
            proc = subprocess.Popen(exe, stdout=file_obj)
            print >> sys.stderr, '4'
            ret = proc.wait()

            print >> sys.stderr, '5'

        if ret != 0:
            print >> sys.stderr, '6'

            print 'Unable to verify license %s' % (err)
            sys.exit(-1)

            print >> sys.stderr, '7'

        with open(tmp_file, 'r') as file_obj:
            print >> sys.stderr, '8'
            output = file_obj.read()

        print >> sys.stderr, '9'
    except Exception as err:
        print 'Unable to verify license %s' % (err)
        sys.exit(-1)

    print >> sys.stderr, '10'
```

**Comment by durden** [comment]
I've re-created the issue with a small demo application.  Try creating the following with the -w flag. I can double-click the exe and run.  However, running test_demo.exe from the command prompt just returns the command prompt and no GUI.  Also note that the redirection goes to a file called `.license_output`. This file has no data in it when running with a -w build from the command prompt. I assume this is because something is crashing behind the `POpen` call.

```python
import sys
import subprocess
from PyQt4 import QtGui

def verify_license():
    tmp_file = '.license_output'

    try:
        with open(tmp_file, 'w+') as file_obj:
            proc = subprocess.Popen(['echo', 'hi'], shell=True, stdout=file_obj)
            ret = proc.wait()

        if ret != 0:
            sys.exit(-1)

        with open(tmp_file, 'r') as file_obj:
            output = file_obj.read()

    except Exception as err:
        sys.exit(-1)

    if 'hi' not in output:
        raise Exception('bad news: output was %s' % (output))


def main():
    sys.stderr = open('stderr.txt', 'w')

    app = QtGui.QApplication(sys.argv)

    w = QtGui.QWidget()
    w.resize(250, 150)
    w.move(300, 300)
    w.setWindowTitle('Simple')
    w.show()
    
    sys.exit(app.exec_())


if __name__ == '__main__':
    verify_license()
    main()
```

**Comment by codewarrior0** [comment]
Since the default for Popen is to inherit the filehandles from the calling process, and that process has closed filehandles for stderr and stdin, have you tried passing `stderr=subprocess.STDOUT` and `stdin=subprocess.PIPE` to the Popen call to make sure the child's filehandles are at least valid?

**Comment by pandel** [comment]
@durden
May I ask a question? Why do you insist on using -windowed parameter? One of my applications has to run with a GUI and also on the command line. As I hate the black console window while in GUI mode, I simply hide it, and that should avoid any problems with your file handles as well...

Try something like this:

    # as part of your imports
    if sys.platform.lower().startswith('win'):
        import ctypes
    
        def hideConsole():
            """
            Hides the console window in GUI mode. Necessary for frozen application, because
            this application support both, command line processing AND GUI mode and theirfor
            cannot be run via pythonw.exe.
            """
    
            whnd = ctypes.windll.kernel32.GetConsoleWindow()
            if whnd != 0:
                ctypes.windll.user32.ShowWindow(whnd, 0)
                # if you wanted to close the handles...
                #ctypes.windll.kernel32.CloseHandle(whnd)
    
        def showConsole():
            """Unhides console window"""
            whnd = ctypes.windll.kernel32.GetConsoleWindow()
            if whnd != 0:
                ctypes.windll.user32.ShowWindow(whnd, 1)
    
    ...
    # later, in main()
    # hide console window, but only under Windows and only if app is frozen
                if sys.platform.lower().startswith('win'):
                    if getattr(sys, 'frozen', False):
                        hideConsole()

**Comment by durden** [comment]
@pandel Thanks for that.  I think it will work.  I was only using the -w parameter because I thought it was the recommended way to get rid of the console window.  I don't mind hiding it as you suggested. I'm just trying to figure out why it doesn't seem to work in my scenario.

**Comment by durden** [comment]
@codewarrior0 Your suggestion seems to fix my issue! I changed the call to subprocess to explicitly set `stderr` and `stdin`.  Here's the full working example:

```python
import sys
import subprocess
from PyQt4 import QtGui

def verify_license():
    tmp_file = '.license_output'

    try:
        with open(tmp_file, 'w+') as file_obj:
            proc = subprocess.Popen(['echo', 'hi'], shell=True,
                                    stdout=file_obj, stderr=subprocess.STDOUT,
                                    stdin=subprocess.PIPE)
            ret = proc.wait()

        if ret != 0:
            sys.exit(-1)

        with open(tmp_file, 'r') as file_obj:
            output = file_obj.read()

    except Exception as err:
        sys.exit(-1)

    if 'hi' not in output:
        raise Exception('bad news: output was %s' % (output))


def main():
    app = QtGui.QApplication(sys.argv)

    w = QtGui.QWidget()
    w.resize(250, 150)
    w.move(300, 300)
    w.setWindowTitle('Simple')
    w.show()
    
    sys.exit(app.exec_())


if __name__ == '__main__':
    verify_license()
    main()
```

**Comment by durden** [comment]
I guess this isn't a PyInstaller bug after all.  Would it be worth mentioning this situation in the documentation though?  Also, maybe the console hiding snippet could be included in the docs somewhere too.

I'm glad to help out with that, but I haven't the slightest clue if and where that should go in.

Thanks so much for helping out folks! I'm glad it's not a bug. Hopefully this thread will still prove useful for other people though in the future.  Speaking of the future, is there a better place to bring something like this up instead of an issue?  I didn't assume it was a bug to start with; I just didn't know where the best place to post something like this was.  Thanks again.

**Comment by pandel** [comment]
My problem was, that my program had to work windowed AND from console, and nothing really worked, even before introducing pyinstaller to package my app. That was the reason for me to simply hide the window ;-)

... I would love to see pyinstaller to have a bootloader variant, that could open (or attach to) a console window and only show it, if one specifies a command line option, else simply hide it... that would make the suggested show/hide funcs obsolete.

**Comment by htgoebel** [comment]
@pandel We'd appreciate a pull-request :-)

**Comment by bjones1** [comment]
All, I've put together a page on this topic -- please take a look and provide feedback.

https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess

**Comment by durden** [comment]
@bjones1 Thanks for putting that together.  It looks good to me except it might not be obvious to people that the `subprocess.Popen` call results in an `OSError` exception if stdin,stdout,stderr aren't redirected correctly.  It wasn't obvious to me because I didn't see an actual exception, things just didn't work. Maybe just a link to this thread on the recipe?  Not sure if that's too detailed or not.

**Comment by bjones1** [comment]
Thanks for taking a look. I added the link per your suggestion.

**Comment by htgoebel** [comment]
IMHO, changing the path i not a good Idea, as it may have security impacts. Instead the executable should be called with an (absolute or relative) path, e.g. `./myapp`.

**Comment by bjones1** [comment]
@htgoebel, thanks for taking a look. I removed the Linux path modifications.

**Comment by cpbotha** [comment]
@pandel Starting our windows exe with the console hidden sounds like the ideal solution for also being able to run end-to-end tests via the exe (where normally it's just a GUI app).

However, trying the example code you've posted, one sees the console window appearing and then disappearing. Do you know of any way to work around this?

**Comment by bjones1** [comment]
Per the earlier comments, see https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess.

**Comment by cpbotha** [comment]
My question was specifically about having an optional console available for my packaged app (configurable at runtime), and not about spawning subprocesses.

**Comment by bjones1** [comment]
My apologies -- I misunderstood what you wanted. I haven't tried @pandel's code, so I can't provide any help there.

**Comment by cpbotha** [comment]
Thank you in any case. :)

I managed to solve our specific problem by adding an additional `EXE()` instance to our spec file. Now we have two small(ish) exes alongside hundreds of megabytes of DLLs, one without console and one with console for running e2e tests.

**Comment by pandel** [comment]
@cpbotha 
Hey, sorry for the late reply. Your obseration is correct. I never got around this console-appearing-disappearing problem, but I simply ignore it :)
