### ISSUE TITLE
Make python3 branch support Python 2.7 again

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1341]
When #1328 (bootloader) is done, we need to head forward and restore support for Python 2.7 is the remaining (Python) parts.

**Comment by htgoebel** [comment]
It looks like I made this work with remarkable few changes. But I have to re-enable the old test-suite first to check if all these test still pass.

**Comment by matysek** [comment]
@htgoebel  I will have to test the bootloader  on Win/OS X. Appveyor does not compile the bootloader yet.

**Comment by matysek** [comment]
* Windows: I recompiled the bootloader on windows witn mingw and run the py.test tests before and after compilation:In bot cases theare are the same failing tests. 32bit Python 3.4. It looks like your changes do not break much for Windows.
* OS X: Trying to compile the bootloader but I get the following error. Not sure yet what exactly that means:
```
bash-3.2$ python3 waf distclean all
'distclean' finished successfully (0.008s)
'all' finished successfully (0.000s)
'distclean' finished successfully (0.000s)
Setting top to                           : /Users/martin/Projects/pyinstaller/python3/bootloader
Setting out to                           : /Users/martin/Projects/pyinstaller/python3/bootloader/build
Platform                                 : Darwin-64bit detected
CYAN                                     : WARNING: Building bootloader for Python 64-bit on Mac OSX
CYAN                                     : For 32b-bit bootloader prepend the python command with:
CYAN                                     : VERSIONER_PYTHON_PREFER_32_BIT=yes arch -i386 python
Checking for 'clang' (C compiler)        : /usr/bin/clang
Checking for program 'strip'             : ['/usr/bin/strip']
Checking for library m                   : yes
Checking for library z                   : yes
'configure' finished successfully (0.502s)
Waf: Entering directory `/Users/martin/Projects/pyinstaller/python3/bootloader/build/debug'
[ 1/12] c: src/main.c -> build/debug/src/main.c.1.o
[ 2/12] c: src/pyi_archive.c -> build/debug/src/pyi_archive.c.1.o
[ 3/12] c: src/pyi_global.c -> build/debug/src/pyi_global.c.1.o
[ 4/12] c: src/pyi_launch.c -> build/debug/src/pyi_launch.c.1.o
[ 5/12] c: src/pyi_path.c -> build/debug/src/pyi_path.c.1.o
[ 6/12] c: src/pyi_python.c -> build/debug/src/pyi_python.c.1.o
[ 7/12] c: src/pyi_python27_compat.c -> build/debug/src/pyi_python27_compat.c.1.o
[ 8/12] c: src/pyi_pythonlib.c -> build/debug/src/pyi_pythonlib.c.1.o
[ 9/12] c: src/pyi_utils.c -> build/debug/src/pyi_utils.c.1.o
In file included from ../../src/pyi_pythonlib.c:39:
In file included from /Users/martin/Projects/pyinstaller/python3/bootloader/src/pyi_python.h:25:
/Users/martin/Projects/pyinstaller/python3/bootloader/src/pyi_python27_compat.h:22:13: warning: inline function 'PI_Py2Sys_AddWarnOption' is not defined [-Wundefined-inl
ine]
inline void PI_Py2Sys_AddWarnOption(char * str);
            ^
../../src/pyi_pythonlib.c:174:8: note: used here
                            PI_Py2Sys_AddWarnOption(&ptoc->name[2]);
                            ^
In file included from ../../src/pyi_pythonlib.c:39:
In file included from /Users/martin/Projects/pyinstaller/python3/bootloader/src/pyi_python.h:25:
/Users/martin/Projects/pyinstaller/python3/bootloader/src/pyi_python27_compat.h:21:13: warning: inline function 'PI_Py2Sys_SetArgvEx' is not defined [-Wundefined-inline]
inline int  PI_Py2Sys_SetArgvEx(int argc, char ** argv, int updatepath);
            ^
../../src/pyi_pythonlib.c:216:7: note: used here
      PI_Py2Sys_SetArgvEx(status->argc, status->argv_char, 0);
      ^
In file included from ../../src/pyi_pythonlib.c:39:
In file included from /Users/martin/Projects/pyinstaller/python3/bootloader/src/pyi_python.h:25:
/Users/martin/Projects/pyinstaller/python3/bootloader/src/pyi_python27_compat.h:19:13: warning: inline function 'PI_Py2_SetProgramName' is not defined [-Wundefined-inline]
inline void PI_Py2_SetProgramName(char * str);
            ^
../../src/pyi_pythonlib.c:248:7: note: used here
      PI_Py2_SetProgramName(status->archivename);
      ^
In file included from ../../src/pyi_pythonlib.c:39:
In file included from /Users/martin/Projects/pyinstaller/python3/bootloader/src/pyi_python.h:25:
/Users/martin/Projects/pyinstaller/python3/bootloader/src/pyi_python27_compat.h:18:13: warning: inline function 'PI_Py2_SetPythonHome' is not defined [-Wundefined-inline]
inline void PI_Py2_SetPythonHome(char * str);
            ^
../../src/pyi_pythonlib.c:288:7: note: used here
      PI_Py2_SetPythonHome(pypath);
      ^
4 warnings generated.

[10/12] c: src/pyi_win32_utils.c -> build/debug/src/pyi_win32_utils.c.1.o
[11/12] cprogram: build/debug/src/main.c.1.o build/debug/src/pyi_archive.c.1.o build/debug/src/pyi_global.c.1.o build/debug/src/pyi_launch.c.1.o build/debug/src/pyi_path.c.1.o build/debug/src/pyi_python.c.1.o build/debug/src/pyi_python27_compat.c.1.o build/debug/src/pyi_pythonlib.c.1.o build/debug/src/pyi_utils.c.1.o build/debug/src/pyi_win32_utils.c.1.o -> build/debug/run_d
Undefined symbols for architecture x86_64:
  "_PI_Py2Sys_AddWarnOption", referenced from:
      _pyi_pylib_start_python in pyi_pythonlib.c.1.o
  "_PI_Py2Sys_SetArgvEx", referenced from:
      _pyi_pylib_start_python in pyi_pythonlib.c.1.o
  "_PI_Py2_SetProgramName", referenced from:
      _pyi_pylib_start_python in pyi_pythonlib.c.1.o
  "_PI_Py2_SetPythonHome", referenced from:
      _pyi_pylib_start_python in pyi_pythonlib.c.1.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/Users/martin/Projects/pyinstaller/python3/bootloader/build/debug'
Build failed
 -> task in 'run_d' failed (exit status 1): 
        {task 4571285824: cprogram main.c.1.o,pyi_archive.c.1.o,pyi_global.c.1.o,pyi_launch.c.1.o,pyi_path.c.1.o,pyi_python.c.1.o,pyi_python27_compat.c.1.o,pyi_pythonlib.c.1.o,pyi_utils.c.1.o,pyi_win32_utils.c.1.o -> run_d}
['/usr/bin/clang', '-arch', 'x86_64', 'src/main.c.1.o', 'src/pyi_archive.c.1.o', 'src/pyi_global.c.1.o', 'src/pyi_launch.c.1.o', 'src/pyi_path.c.1.o', 'src/pyi_python.c.1.o', 'src/pyi_python27_compat.c.1.o', 'src/pyi_pythonlib.c.1.o', 'src/pyi_utils.c.1.o', 'src/pyi_win32_utils.c.1.o', '-o', '/Users/martin/Projects/pyinstaller/python3/bootloader/build/debug/run_d', '-lz', '-lm']
```

**Comment by matysek** [comment]
@htgoebel Why is the inline keyword used for PI_Py2_* functions?

It causes compilation failures with clang on osx and gcc 5.1 on linux.

**Comment by htgoebel** [comment]
@matysek Just for code-optimization. I did not manage to make this a macro, so I used `inline`. If this is a problem, you can safely remove it FMPOV.

**Comment by codewarrior0** [comment]
Correct me if I'm wrong, but it doesn't work to put an 'inline' function into a C file. It has to go into the H file so that it can be included into and properly inlined into the other C files. When you put the inline function in the C file, some compilers will do a "remove unreferenced functions" optimization, which removes any unused functions marked "static" or "inline". Later, you'll get a "symbol not defined" linker error on the other C files that use them.

**Comment by matysek** [comment]
@htgoebel PyInstaller should be able now again create .exe with python 2.7. Helloworld seems working.

**Comment by htgoebel** [comment]
@matysek Argl, I've already been working on this for some days. This is why the ticket is assigned to me. Now we've done duplicate work :-(((

**Comment by codewarrior0** [comment]
Do you mind if I work on getting this to run on Windows? There are still some py3-isms in winmanifest.py and pefile.py related to the change in string types (isinstance not working with py2's 'unicode', bytes[0] returning an int on py3 and a str on py2, etc...)

**Comment by htgoebel** [comment]
@codewarrior0 I'D would be great if you could work on the Windows specific part. I don not have windows. @matysek Okay? Or are you working on this already?

**Comment by matysek** [comment]
> @matysek Okay? Or are you working on this already?

@htgoebel Sorry about that. I was not sure if your work on Python 2 ended with the bootloader or not. Just continue. I will just continue with appveyor.

**Comment by htgoebel** [comment]
@matysek FYI: I'm currently working on getting the the old test-sute pass (almost) for python3. Then I'll make it pass (almost) for Python 2.7 (on the python3 branch).

**Comment by htgoebel** [comment]
For the records:

Testname | PyI 2.1 | develop (90304142)
---------|---------|------------------
test_c_extension | fail | fail
test_onefile_c_extension | fail | fail
test_twisted_qt4reactor | Xfail | skip
test_twisted_reactor | fail | pass
test_eggs1 | skip | skip
test_eggs2 | pass | pass
test_onefile_tkinter | pass | fail
test_pycrypto | pass | fail
test_sphinx | skip | fail
test_stderr_encoding | - | fail
test_stdout_encoding | - | fail
test_crypto | - | fail
test_onefile_crypto | - | fail
test_onefile_pkgutil-get_data__main__ | - | skip |

**Comment by htgoebel** [comment]
For the records: As of 44460835 the status for the old test-suite is, for both Python 2.7 and Pyhton 3.3:
- nearly all of basic and import tests pass
- for Python 3, all import test pass - while I do  not have many packages installed
  for Python 3
- for Python 2, some import tests fail
- multipackage tests have not been tested yet

Here is a list of the failing tests and the reason:

Failing | Reason
---------|------------
test_pkg_structures | This is a quite hacky test at all and needs to be reworked
test_eggs1 | While modulegraph supports including modules from eggs, we don't support adding the data. This as unsupported in PyInstaller 2.1, too.
test_eggs2 | While modulegraph supports including modules from eggs, we don't support adding the data. This worked in Python 2.1
test_nspkg1-bbb-zzz | I assume this fails due to some bugs in namespace-support.
test_nspkg1-empty | I assume this fails due to some bugs in namespace-support.
test_nspkg1 | I assume this fails due to some bugs in namespace-support.
test_nspkg2 | I assume this fails due to some bugs in namespace-support.
test_nspkg-pep420 | I assume this fails due to some bugs in namespace-support.
test_onefile_pkgutil-get_data__main__ | Our import mechanism returns the wrong loader-class for `__main__`.

**Comment by htgoebel** [comment]
I've been using the python-branch for Python 2 now for running quite some tests. I'd say, it's done.

There are still deficits the current python3-branch has compared with PyInstaller release 2.1: Namespaces have a problem, __path__ extensions have aproblem, egg-data is not included. But these are not related to Python 2, so I close this issue.

**Comment by matysek** [comment]
@htgoebel Do you think we are ready to make 'develop' from python3 branch?

**Comment by htgoebel** [comment]
> Do you think we are ready to make 'develop' from python3 branch?

I would not do this, because of the remaining issues I mentioned. But I may get convinced :-)

BTW: I have to recherché and test what is the "correct" way for doing this in git: merge python3 into develop or just forward develop to python3-head. Maybe a merge without `--no-ff` has the same effect as the later.

**Comment by matysek** [comment]
@htgoebel, @codewarrior0  Then let's agree at least that we do not accept pull request  for 'develop' anymore.

**Comment by htgoebel** [comment]
> let's agree at least that we do not accept pull request for 'develop' anymore.

ACK.

**Comment by codewarrior0** [comment]
> Then let's agree at least that we do not accept pull request for 'develop' anymore.

Agreed.

> BTW: I have to recherché and test what is the "correct" way for doing this in git: merge python3 into develop or just forward develop to python3-head. Maybe a merge without --no-ff has the same effect as the later.

I think develop can be safely fast-forwarded to python3. I just tried it with `checkout develop; merge python3` and it worked without a merge commit, with develop and python3 now on the same commit. 

Then if you want, deprecate the python 3 branch: Add a commit to delete all the files except for a README that says "Check out develop branch please ;)"

**Comment by htgoebel** [comment]
Since we are revering to the python-branch a lot, I'd prefer having a merge commit.

**Comment by matysek** [comment]
@htgoebel Do you have any estimate when python3 could be merged into develop?
