### ISSUE TITLE
Rename FakeModule.name to __name__

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1343]
This is how the name is stored in normal modules and how hooks may access the name. Indeed, `hooks1/hook-pkg1.py` for `test_pkg_structures` does this.

This seams to be done wrong when FakeModule was introduced in 25c1ec2b946. So maybe `name` is used at other places or modulegraph uses `name`. We'll have to look into this.

**Comment by htgoebel** [comment]
We should do this prior to release 3.0 to get a clean interface for the users.

**Comment by matysek** [comment]
@htgoebel What is the status of this issue? Is it still valid with the new replacement for FakeModule?

**Comment by htgoebel** [comment]
I'll implement this as a property, just for the case the change to PostGraphAPI (see https://github.com/pyinstaller/pyinstaller/issues/1553#issuecomment-144012794) will not be done.
