### ISSUE TITLE
building with append_pkg=False results in crash

### ISSUE THREAD

**Issue by synapse211** [pyinstaller/pyinstaller#1345]
The error message is:

"Cannot open self test or archive test.pkg"

Is append_pkg deprecated or am I missing something? After removing it builds correctly but harder to debug for deps.

**Comment by htgoebel** [comment]
Need more info, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by synapse211** [comment]
My bad, reproducing is quite easy

test.py and test.spec attached

$ pyi-build test.spec
58 INFO: UPX is available.
60 INFO: Extending PYTHONPATH with /home/synapse/tmp
60 INFO: checking Analysis
60 INFO: Building Analysis because out00-Analysis.toc non existent
61 INFO: Creating base_library.zip for Python 3
8019 INFO: running Analysis out00-Analysis.toc
8065 INFO: Looking for graph hooks ...
8069 INFO: Analyzing test.py
8071 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller/loader/_pyi_bootstrap.py
15208 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyi_importers.py
15235 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyi_archive.py
15271 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyi_carchive.py
15305 INFO: Analyzing /usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyi_os_path.py
15313 INFO: Hidden import 'codecs' has been found otherwise
15314 INFO: Hidden import 'encodings' has been found otherwise
15314 INFO: Looking for import hooks ...
15322 INFO: Processing hook   hook-encodings.py
16286 INFO: Processing hook   hook-pydoc.py
16290 INFO: Processing hook   hook-sysconfig.py
16292 INFO: Processing hook   hook-distutils.py
16300 INFO: Processing hook   hook-xml.py
16952 INFO: Processing hook   hook-xml.sax.py
16955 INFO: Processing hook   hook-site.py
16959 INFO: Analyzing run-time hooks ...
16981 INFO: Looking for dynamic libraries
17278 INFO: Looking for eggs - TODO
17279 INFO: Python library not in binary depedencies. Doing additional searching...
17351 INFO: Using Python library /usr/lib/i386-linux-gnu/libpython3.4m.so.1.0
17417 INFO: Warnings written to /home/synapse/tmp/build/test/warntest.txt
17444 INFO: checking PYZ
17444 INFO: Rebuilding out00-PYZ.toc because out00-PYZ.pyz is missing
17444 INFO: Building PYZ (ZlibArchive) out00-PYZ.toc
18197 INFO: checking PKG
18198 INFO: Rebuilding out00-PKG.toc because out00-PKG.pkg is missing
18198 INFO: Building PKG (CArchive) out00-PKG.pkg
18281 INFO: checking EXE
18281 INFO: Rebuilding out00-EXE.toc because test missing
18281 INFO: Building EXE from out00-EXE.toc
18282 INFO: Bootloader /usr/local/lib/python3.4/dist-packages/PyInstaller/bootloader/Linux-32bit/run
18289 INFO: Copying archive to test.pkg
18294 INFO: checking COLLECT
18295 INFO: Building COLLECT out00-COLLECT.toc

$ ./dist/test/test 
Cannot open self /home/synapse/tmp/dist/test/test or archive /home/synapse/tmp/dist/test/test.pkg

without append_pkg=False this works perfectly

**Comment by synapse211** [comment]
test.py:
```
print ("HI")
```

test.spec:
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['test.py'],
             pathex=['/home/synapse/tmp'],
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None,
             excludes=None,
             cipher=block_cipher)
pyz = PYZ(a.pure,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='test',
          debug=False,
          strip=None,
          upx=True,
          append_pkg=False,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=True,
               name='test')
```

**Comment by htgoebel** [comment]
I still don't know which *exact* version you are using.

**Comment by synapse211** [comment]
3.0.dev0

**Comment by htgoebel** [comment]
You didn't read the link I gave you, did you? There it says
> when using a git-checkout, please state the revision number

I'm angry because you are simply loading of this problem to us and note giving enough information for use to solve it. We are volunteers and running behind information is wasting our time.

**Comment by synapse211** [comment]
I used pip3.4 install https://github.com/pyinstaller/pyinstaller/archive/python3.zip and not git. 

By the way you guys have a unit test for this in the old suite which fails: test_pyz_as_external_file

I tried the latest python3 branch, same error happens:
revision is ca570f8d47b56009d50ce21851dc1ba15929f9c7
full version string of built package is PyInstaller===3.0dev-ca570f8

**Comment by htgoebel** [comment]
Thanks for the info.

**Comment by htgoebel** [comment]
Solved on my working branch. Please use https://github.com/htgoebel/pyinstaller/tree/make-old-test-suite-work for now. I'll have to finish this work before merging into the python3-branch

**Comment by synapse211** [comment]
FYI just tested this, the make-old-test-suite-work branch did not solve it for me.

Using this rev:
7a5f1510c8271c76993c38cfadcc96067174f443

**Comment by htgoebel** [comment]
Sorry, I forgot to write that you need to recompiler the bootloader.
