### ISSUE TITLE
Add a hook for `distribute`?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1349]
If `distribute` is installed, the frozen exe fails with `ImportError: Couldn't find the real 'site' module`. I think, the cause is that we removed support for the `faked-site`-module in python3-branch 12de5e2fdc.

@matysek You worked on fake-site in #510. Do we need to restore this? Or should there be a hook for `distribute.site`, replacing it with a do-nothing module?

**Comment by htgoebel** [comment]
Addendum:
* 
```
PYTHONPATH= PYINSTALLER_RUNTESTS_WORKDIR= \
python2 ./runtests.py Import/test_pep302_import_protokol.py
```
* https://bitbucket.org/tarek/distribute/src

**Comment by matysek** [comment]
@htgoebel I was considering reintroduce fake-site but it is possible to tell python.dll to not use 'site' for module searching. Do you think there is a more general usecase for 'fake' hooks?

**Comment by matysek** [comment]
'distribute' was deprecated so I think we do not care module 'distribute'.

**Comment by htgoebel** [comment]
> 'distribute' was deprecated so I think we do not care module 'distribute'.

This was my firs thought, too. But some test-case crashed with the import error, just because I had `distribute` installed.

**Comment by htgoebel** [comment]
We should at least issue a warning or even stop building if `distribute.site` shows up.

**Comment by matysek** [comment]
@htgoebel How could I reproduce the import error? Just install 'distribute' package?

**Comment by htgoebel** [comment]
@matysek The setup seams to be more complicated. I'll try to reproduce and create a receipt for reproduction. This may take some days, though.

**Comment by htgoebel** [comment]
As reproducing this is more complicated, I'm post-boning to milestone 3.1

**Comment by htgoebel** [comment]
I'm closing this, since I've been the only one reporting such an issue and `distribute` is deprecated anyway.
