### ISSUE TITLE
use new pefile release with built-in Python 3 support

### ISSUE THREAD

**Issue by pandel** [pyinstaller/pyinstaller#1357]
Hi!

Trying to install pyinstaller vi a ``python setup.py install``, results in a working copy of pyinstaller, BUT I get the following message under Windows:

    Processing PyInstaller-3.0dev_4f757b8-py3.4.egg
    creating c:\python34\lib\site-packages\PyInstaller-3.0dev_4f757b8-py3.4.egg
    Extracting PyInstaller-3.0dev_4f757b8-py3.4.egg to c:\python34\lib\site-packages
      File "c:\python34\lib\site-packages\PyInstaller-3.0dev_4f757b8-py3.4.egg\PyInstaller    \lib\pefile_py2.py", line 82
        IMAGE_ORDINAL_FLAG              = 0x80000000L
                                                    ^
    SyntaxError: invalid syntax
    
    Removing pyinstaller 3.0dev-1d241e8 from easy-install.pth file

Perhaps it means nothing, perhaps it is important, I don't know. Just wanted to report it...

Regards,
Holger

**Comment by matysek** [comment]
the pefile_py2.py is there for Python 2 compatibility.

I think we should somehow exclude it when installing PyInstaller and using Python 3.

**Comment by pandel** [comment]
Ok, thanks. I'll simply ignore it for now...

**Comment by codewarrior0** [comment]
That's right, it needs to be excluded because setuptools will try to precompile all .py files to .pyc on install.

**Comment by codewarrior0** [comment]
Actually, it's not that important. The install succeeds regardless of the syntax error, and the file never gets imported anyway.

**Comment by tartley** [comment]
You could add a line to the python3 branch README install instructions saying that this error is harmless. I just wasted a bunch of time trying to fix it and googling it before ending up here. Presumably every new user does the same?

**Comment by htgoebel** [comment]
For the records: Neither of these approaches work:
```
    packages=find_packages(exclude=['PyInstaller.lib.pefile_py2']),
    packages=find_packages(exclude=['PyInstaller.lib.*']),
    packages=find_packages(exclude=['PyInstaller.lib']),
```
Removing `recursive-include PyInstaller *` from `MANIFEST.in` does not work either.

**Comment by htgoebel** [comment]
Okay, when thinking on this, the reason is obvious: `pefile_py2` is not a package :-) So the solution would be to make it a package by renaming to `pefile_py2/__init__.py`. But this does not solve the issue either :-( The file is still included and compiled.

**Comment by matysek** [comment]
Recently was released a new version of pefile that supports both py2/py3. This issue is solved when we use the new pefile version.

I will change the title and description of the issue.

**Comment by matysek** [comment]
New version of pefie is available at: https://github.com/erocarrera/pefile/releases/tag/v2016.3.4

**Comment by matysek** [comment]
I think we should remove the bundled `pefile` module and make it as a pyinstaller dependency in `setup.py`:
- the reason why we keep bundled copy of pefile is having support for Python 3 in pefile
- new pefile version depends on module `future`
- pefile dependencies might change and I do not want to be exposed to that

There are two pefile issues that block this move:
- https://github.com/erocarrera/pefile/issues/92
- https://github.com/erocarrera/pefile/issues/93

**Comment by matysek** [comment]
This could be implemented since the pefile issues were fixed.

**Comment by matysek** [comment]
pefile is now:
* installed from PYPI (latest version works with both py2 and py3)
* is only windows dependency
* is installed automatically as dependency by `python setup.py install` or `pip install pyinstaller`

**Comment by tallforasmurf** [comment]
@matysek writes, "pefile... is only windows dependency" however,

* [the doc](https://github.com/pyinstaller/pyinstaller/blob/develop/doc/requirements.rst) still says "requires the PyWin32_ or pypiwin32_"

* [setup](requires the PyWin32_ or pypiwin32_ ) still attempts to import one or the other of those, in addition to now adding the pefile requirement

Should requirements.rst be changed?

**Comment by matysek** [comment]
@tallforasmurf you are right it should be mentioned there. Could you please do that? Thanks.

**Comment by tallforasmurf** [comment]
Ah! "is only windows dependency" means, "is only a dependency in windows" -- not, "is the only windows dependency".

Commit fbfcd2 and 2e15a9d

**Comment by matysek** [comment]
> Ah! "is only windows dependency" means, "is only a dependency in windows" -- not, "is the only windows dependency".

Yes, you got it :-) sorry for not being clearer.
