### ISSUE TITLE
MERGE, COLLECT ? - I don't understand how to accomplish my goal

### ISSUE THREAD

**Issue by pandel** [pyinstaller/pyinstaller#1358]
Hi!

At first, I'm sorry for the long post, but I need to describe my problem in detail, I think...

I'm trying to accomplish the following via a .spec file definition, but I'm unable to do so. I think it's me not really understanding MERGE, COLLECT, etc., so I'd like to describe my situation.

Let's assume that I have a development folder like this:
```sh   
Base folder
    -> images
        -> ...
    -> oPB (python source package)
        -> help
            file1.qch
            file2.qhc
        -> ui
            ui_file1.ui
            ui_file2.ui
        -> core
            -> x86
                dll files
            -> x64
                dll files
            ....
        -> <more subfolders with python code>
    -> some more folders....
    mainprogram.py
    helpviewer.py
```

Let's assume further, both python scripts in the base folder depend on the package 'oPB' and different data files in different subdirectories. "mainprogram" should be obvious, "helpviewer" opens only the help pages in a standalone viewing application. Both applications use/import classes from the 'oPB' package.

Now, I want pyinstaller do the following:
- create a **single** output directory
- put all dependencies, necessary dlls, data files of **both** scripts into it
- put mainprogram.exe **AND** helpviewer.exe in the base of this distribution directory

I tried many different versions of my spec file, but I simply cannot get this to work. At the moment, I create two different collection directories and copy one exe over by hand. But that can't be the right way!

My working spec file with the copy thing:
```sh
# -*- mode: python -*-
ui_tree = Tree('oPB/ui', prefix='oPB/ui', excludes=['*.qss', '*.py'])
lang_tree = Tree('c:/Python34/Lib/site-packages/PyQt5/translations', 'PyQt5/translations', excludes=['assistant*.*', 'designer*.*', 'linguist*.*', 'qscintilla*.*'])
help_tree = Tree('oPB/help', prefix='help')
dll64_tree = Tree('oPB/core/x64', prefix='x64')
dll86_tree = Tree('oPB/core/x86', prefix='x86')

mainprogram_a = Analysis(['mainprogram.py'],
             pathex=['.'],
             hookspath=None,
             runtime_hooks=None)

helpviewer_a = Analysis(['helpviewer.py'],
             pathex=['.'],
             hookspath=None,
             runtime_hooks=None)

mainprogram_pyz = PYZ(mainprogram_a.pure)
mainprogram_exe = EXE( mainprogram_pyz,
          mainprogram_a.scripts,
          mainprogram_a.dependencies,
          exclude_binaries=True,
          name='mainprogram.exe',
          debug=False,
          strip=False,
          upx=False,
          console=True,
          icon='images/prog_icons/opb/package_256x256.ico')

helpviewer_pyz = PYZ(helpviewer_a.pure)
helpviewer_exe = EXE(helpviewer_pyz,
          helpviewer_a.scripts,
          helpviewer_a.dependencies,
          exclude_binaries=True,
          name='helpviewer.exe',
          debug=False,
          strip=False,
          upx=False,
          console=False,
          icon='images/prog_icons/help/help.ico')

mainprogram_coll = COLLECT(mainprogram_exe,
                mainprogram_a.binaries,
                mainprogram_a.zipfiles,
                mainprogram_a.datas,
                ui_tree,
                lang_tree,
                help_tree,
                dll64_tree,
                dll86_tree,
                [('ui/mainprogram_rc.py', 'oPB/ui/mainprogram_rc.py', 'DATA')],
                [('ui/stylesheet.qss', 'oPB/ui/stylesheet.qss', 'DATA')],
                strip=None,
                upx=False,
                name='mainprogram')

helpviewer_coll = COLLECT(helpviewer_exe,
                helpviewer_a.binaries,
                helpviewer_a.zipfiles,
                helpviewer_a.datas,
                lang_tree,
                help_tree,
                strip=None,
                upx=False,
                name='helpviewer')
```

and here an example that did NOT work:
```sh
# -*- mode: python -*-
ui_tree = Tree('oPB/ui', prefix='oPB/ui', excludes=['*.qss', '*.py'])
lang_tree = Tree('c:/Python34/Lib/site-packages/PyQt5/translations', 'PyQt5/translations', excludes=['assistant*.*', 'designer*.*', 'linguist*.*', 'qscintilla*.*'])
help_tree = Tree('oPB/help', prefix='help')
dll64_tree = Tree('oPB/core/x64', prefix='x64')
dll86_tree = Tree('oPB/core/x86', prefix='x86')

mainprogram_a = Analysis(['mainprogram.py'],
             pathex=['.'],
             hookspath=None,
             runtime_hooks=None)

helpviewer_a = Analysis(['helpviewer.py'],
             pathex=['.'],
             hookspath=None,
             runtime_hooks=None)

MERGE( (mainprogram_a, 'mainprogram', 'mainprogram.exe'), (helpviewer_a, 'helpviewer', 'helpviewer.exe') )

mainprogram_pyz = PYZ(mainprogram_a.pure)
mainprogram_exe = EXE( mainprogram_pyz,
          mainprogram_a.scripts,
          mainprogram_a.dependencies,
          exclude_binaries=True,
          name=os.path.join('dist', 'mainprogram.exe'),
          debug=False,
          strip=False,
          upx=False,
          console=True,
          icon='images/prog_icons/opb/package_256x256.ico')

helpviewer_pyz = PYZ(helpviewer_a.pure)
helpviewer_exe = EXE(helpviewer_pyz,
          helpviewer_a.scripts,
          helpviewer_a.dependencies,
          exclude_binaries=True,
          name=os.path.join('dist', 'helpviewer.exe'),
          debug=False,
          strip=False,
          upx=False,
          console=False,
          icon='images/prog_icons/help/help.ico')

mainprogram_coll = COLLECT(mainprogram_exe,
                mainprogram_a.binaries,
                mainprogram_a.zipfiles,
                mainprogram_a.datas,
                ui_tree,
                lang_tree,
                help_tree,
                dll64_tree,
                dll86_tree,
                [('ui/mainprogram_rc.py', 'oPB/ui/mainprogram_rc.py', 'DATA')],
                [('ui/stylesheet.qss', 'oPB/ui/stylesheet.qss', 'DATA')],
                strip=None,
                upx=False,
                name='app_bundle')

helpviewer_coll = COLLECT(helpviewer_exe,
                helpviewer_a.binaries,
                helpviewer_a.zipfiles,
                helpviewer_a.datas,
                lang_tree,
                help_tree,
                strip=None,
                upx=False,
                name='app_bundle')
```
I thought, that MERGE would combine both dependencies, datas, etc. and put both via the two COLLECTs into a folder called 'app_bundle' below the 'dist' folder. But pyinstaller even tries to delete the first created collection when reaching the second.

I also tried different variations based on the pyinstaller test suite, but sometimes i. e. , helpviewer.exe was put into a subfolder of the mainprogram dist, and, when started, wasn't able to find its dependencies or data files. etc. I have absolutely no clue what I have to do to make it work...

Would someone please be so nice to tell me what am I doing (AND understanding) wrong here? I think, besides my wrong understanding of MERGE, COLLECT and such, I really did not get the point where to put the <name>.binaries, <name>.zipfiles, <name>.dependencies, ... lines and especially, what it means if I put them into EXE or COLLECT...

I hope, someone understands what I'm trying to ask for...

Regards,
Holger

**Comment by bjones1** [comment]
MERGE seems to work for me when creating a multipackage bundle. However, I do have to manually copy over files from the the other packages in the  bundle to the main package (the first in the list, for you it is `mainprogram`). Probably a bug, I haven't put together a good clean test case.

**Comment by pandel** [comment]
As far as I can tell, MERGE seems to be working, at least regarding the dependencies. So, my main problem might be in the COLLECT section... as you, I have to manually copy over the exe file from my second script (helpviewer) to the main package....

**Comment by htgoebel** [comment]
Please checkout `tests/multipackage/test_multipackage4.spec` for a complete example.

**Comment by pandel** [comment]
From what I see, test_multipackage4.spec does build two different dist folders with two different programs, but merges their dependencies, right? (Actually, the test fails with a ``NameError: name 'sys' is not defined`` when I try to run ``pyinstaller test_multipackage4.py``, so I have to guess what the spec file does...)

But, if so, that is NOT what I tried to accomplish...

And, additionally, I find no explanation for the following line anywhere:

    name=os.path.join('build', 'pyi.'+sys.platform, __testname__,
                                __testname__ + '.exe'),

Why do you do this and where do you get the path component ``'pyi.'+sys.platform`` from? I can't find a directory like this anywhere during the build...

**Comment by htgoebel** [comment]
> NameError: name 'sys' is not defined

Just add an import :-)

> `name=os.path.join('build', 'pyi.'+sys.platform, __testname__,
                            __testname__ + '.exe'),`

You can ignore this, this is just because on how the test suite works.

**Comment by pandel** [comment]
Pffff :-)))) Tested it...

And as I assumed, this is absolutely NOT what I wanted. It creates two different folders, one with the first exe and all deps and another one with the second exe and a manifest only. But, what I wanted is the opposite: **one single** folder with **both EXEs** and **every** necessary **dependency** for them both **inside** ;-)

**Comment by htgoebel** [comment]
I'm confident that you are able to adopt this to your needs :-)

But you should know, that MERGE puts *all* python modules into one of the exes, not into a separate file.

**Comment by htgoebel** [comment]
@pandel Did you succeed?

**Comment by pandel** [comment]
@htgoebel No i didn't, sorry. As I said in my first posting, I have a working version, but it creates two separate distributions (one for each exe), and after that, I have to copy over one exe and delete its (now unnecessary) dist folder. Every other configuration I tried resulted in different kinds of dist folder variations (two besides each other, one inside the other, etc.), but none of them worked as expected, because then the second exe file has different problems to find data files, modules, etc. As I said, perhaps it is me not REALLY understanding the MERGE and COLLECT parameters, so I'm too stupid to get it going... but that's ok for now ;-)....

I think I should close this issue myself...

**Comment by Siecje** [comment]
In order to have all executables in the same directory you need to have one `COLLECT` and pass the four arguments for each executable

```
COLLECT(mainprogram_exe,
                mainprogram_a.binaries,
                mainprogram_a.zipfiles,
                mainprogram_a.datas,

                helpviewer_exe,
                helpviewer_a.binaries,
                helpviewer_a.zipfiles,
                helpviewer_a.datas,

```
