### ISSUE TITLE
"Example MERGE spec file" is incomplete

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1361]
The manual is lacking a *complete* .specfile example. The snippets are missing the COLLECT stage or one-dir.
http://pythonhosted.org/PyInstaller/#example-merge-spec-file

See `tests/multipackage/test_multipackage4.spec` and the other example in the old test-suite

**Comment by tallforasmurf** [comment]
I have added COLLECT lines to the skeleton example, and updated the path to the tests (in old_suite now). I don't think including a really complete example in the manual would help, but re-open if you want more.
