### ISSUE TITLE
Bootloader: set sys._MEIPASS in the bootloader already

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1366]
Make i available as early as possible, so it can be used in `pyi_importers.py` instead of relying on `sys.path` being set up in a certain way.

See d627237ce551c2 for a discussion.

**Comment by codewarrior0** [comment]
I'll take care of it. I've got to make sure sys._MEIPASS is encoded correctly, and I can reuse some of the code I used to add pyz paths with the correct encoding.

**Comment by htgoebel** [comment]
Fine. I was already hoping you'll take this task :-)

**Comment by codewarrior0** [comment]
Done in 30de5bb81eafa114d94aa7c609c772f11c67ab4a

**Comment by htgoebel** [comment]
Great. Thanks.
