### ISSUE TITLE
rename top-level PyInstaller module to lowercase

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1370]
PyInstaller uses CamelCase for top-level module name. We should rename it to lowercase:

```
PyInstaller.module  ->  pyinstaller.module
```

**Comment by codewarrior0** [comment]
I'm not sure I see the benefit. Packages on pypi are already case insensitive; `pip install PyInstaller` and `pip install pyinstaller` produce the same result. The command line script that gets installed is already named `pyinstaller` in all lower-case which is how most users interact with it. And on Mac and Windows, the filesystem is case insensitive by default so `import PyInstaller` and `import pyinstaller` also produce the same result.

The case insensitive filesystem on Mac and Windows also offers difficulties: In the source checkout, if I rename the folder "PyInstaller" to "pyinstaller", git will still see it as the same filename and won't allow me to commit a change that just changes the case of the filename. What's worse, if you commit such a change from Linux (where case matters), when I pull that change, my git won't rename my folder to lower case so any files I add later will have the original CamelCase.  

There's one workaround for this, which goes something like `git mv PyInstaller pyinstaller2; git mv pyinstaller2 pyinstaller` - that will force git rename the folder to lower case on Mac and Windows.

Actually renaming the PyInstaller module to pyinstaller in the code is trivial - I can do it in a couple of clicks with Pycharm's "Rename" refactoring command.

**Comment by htgoebel** [comment]
I don't mind about the spelling of the package. I see no real reason for changing, but could live with - except if the double-`git mv` leads to dozens of files changes in the commit-log.

**Comment by htgoebel** [comment]
@matysek Do you still want to rename the top-level, then please push to Milestone 3.1. Or can we close this ticket?

**Comment by matysek** [comment]
@htgoebel I would like still to do that but there is no rush with it and it could wait.

**Comment by htgoebel** [comment]
@matysek I'm still wondering why.

**Comment by matysek** [comment]
Closing. It is really not necessary to rename it.

**Comment by htgoebel** [comment]
Additional reason for *not* renaming: It would somewhat break the change history, since most git commands would stop at the commit renaming the files.
