### ISSUE TITLE
reenable scanning code for ctypes dlls

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1374]
Recently I noticed that method scan_code_for_ctypes() is not used in python3 branch. We should use it again.

**Comment by matysek** [comment]
I found out that this is outside of my knowledge: It requires understanding of Python bytecode.

**Comment by htgoebel** [comment]
So it looks like this to be my job :-)

**Comment by matysek** [comment]
* @htgoebel  Rather 3.0 if possible, because it might ease some hooks that are bundling additional dlls.
* I'm just implementing some preparation for this - collect all modules that needs scanning.

**Comment by htgoebel** [comment]
> I'm just implementing some preparation for this - collect all modules that needs scanning.

Fine. It'll take some days until I can start working on this.

**Comment by htgoebel** [comment]
@matysek Do we have a test-case for this? `import/test_ctypes_cdll_c.py` passes with both Python 2.7 and 3.3

**Comment by matysek** [comment]
@htgoebel Do you mean in py.test suite? In py.test there is nothing like that.

Could you make a new bug report with a list of tests that are important and you'd like me to move them to py.test?

**Comment by htgoebel** [comment]
@matysek  I meant test-cases at all. There is only one: `test_ctypes_cdll_c`. And this is a no-brainer since the resp. dll/so is collected anyway.

I'll implement some more :-) And I'll implement them for the new test-suite. This is a good training for me.

**Comment by matysek** [comment]
@htgoebel Just to let you know that yesterday I implemented support for .toc files:
* Just create a new test script in ./functional/scripts/pyi_scriptname.py and
* then just create .toc like ./functional/logs/pyi_scriptname.toc and 
* it should be picked  up automatically

**Comment by htgoebel** [comment]
@matysek I've seen this. Thanks. I just pushed support for having the source within the test-function, see 7c0bcf1c.

Regarding the ctypes-tests: We have to thing about how to test this at all. The `test_ctypes_CDLL_find_library__nss_files` I just added passes, but `libnss_files.so` is not included in the frozen app. Am I missing something here?

**Comment by matysek** [comment]
libnss_files* is in the _unix_excludes list in ./PyInstaller/depend/dylib.py.

**Comment by htgoebel** [comment]
IC. Thanks. Any idea what to use instead? ghostscript should be available on may systems, too.

**Comment by matysek** [comment]
What about libusb?  I think that the `hook-usb.py` could be dropped when resolving ctypes imports is working.

**Comment by htgoebel** [comment]
libusb sounds good. I'll add this, too.

**Comment by htgoebel** [comment]
I just re-enabled basic support for Python 2.7, 3.3 and 3.5 and some test-cases on my personal repository at https://github.com/htgoebel/pyinstaller/tree/1374-reenable-scanning-code-for-ctypes-dlls.
libusb-1.0 is not installed on travis, but ghostscript is and all test pass.
I still need to add tests for other code-patterns as handled in https://github.com/htgoebel/pyinstaller/blob/1374-reenable-scanning-code-for-ctypes-dlls/PyInstaller/depend/utils.py#L194

**Comment by matysek** [comment]
@htgoebel Could this be closed?

**Comment by htgoebel** [comment]
This can be closed. Reworking the tests is still open, but there is pull-request #1452 for this:
