### ISSUE TITLE
refactoring build.py - split into more modules

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1375]
Make a submodule `PyInstaller.spec` that will continue code related to spec files:
* move `PyInstaller.makespec -> PyInstaller.spec.makespec`
* move some classes from build.py into `PyInstaller.spec.api`

**Comment by htgoebel** [comment]
I' currently busy cleaning up and fixing some issues in build.py. So I strongs suggest not touching this until PyI 3.0 is released.

**Comment by matysek** [comment]
Well, I'm just working on fixing tests and almost ready for merging.  I could do merging of your fixes then.

**Comment by matysek** [comment]
It's only about splitting classes / functions into several modules.

**Comment by htgoebel** [comment]
To be frank, I do not see major reason for this split. But now it is done.

Regarding the `cliutils` -> `utils.cliutils` rename: I think this is totally pointless. The `cliuitls` are not utility-functions for PyInstaller, as `utils` would imply.

I just wonder why you marked this "low", but stated working on it immediately?

**Comment by matysek** [comment]
> I just wonder why you marked this "low", but stated working on it immediately?

Yes, it's low priority but it was still getting on my mind.

I see this refactoring as a base for further polishing.

**Comment by htgoebel** [comment]
Sorry for being so harsh. No offense meant. I still appreciate your work :-)

**Comment by matysek** [comment]
Feel free to do more refactoring ;-)
