### ISSUE TITLE
"pip install PyInstaller" cmd should build bootloader if precompiled not available

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1377]

**Comment by htgoebel** [comment]
How should this be implemented? Just check if the bootloader for the current platform exists and then run `cd bootloader && ,/waf all --no-lsb`?
Or should we check for lsbtools, too?

**Comment by matysek** [comment]
I suggest this:
- if not exist compile bootloader
- if platform linux and `lsbcc` not in PATH or /opt/lsb/bin/lsbcc not exits - use option `--no-lsb`
- just use this command: `cd bootloader && python waf all $OPTIONS`
- run the setup.py phase

**Comment by htgoebel** [comment]
lsbcc is not available for my platform, so I can nor test it in detail. Does running `lsbcc` without any arguments return an error code? Or does it accept `version`? Thus I could simply run `lsbcc --version` to check if it is installed.

**Comment by htgoebel** [comment]
Forget my last entry. I'll simply use `which`.

**Comment by matysek** [comment]
@htgoebel thanks it works well with lsbcc. Just tested it :-)
