### ISSUE TITLE
`pip install pyinstaller` for Python 3 fails in Windows

### ISSUE THREAD

**Issue by msarfati** [pyinstaller/pyinstaller#1380]
```
> pip install pyinstaller
Collecting pyinstaller
  Using cached PyInstaller-2.1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "C:\Users\Michael\AppData\Local\Temp\pip-build-ew_yf7o2\pyinstaller\setup.py", line 18, in <module>
        from PyInstaller import get_version
      File "C:\Users\Michael\AppData\Local\Temp\pip-build-ew_yf7o2\pyinstaller\PyInstaller\__init__.py", line 32, i n <module>
        from PyInstaller import compat
      File "C:\Users\Michael\AppData\Local\Temp\pip-build-ew_yf7o2\pyinstaller\PyInstaller\compat.py", line 129
        if sys.maxint > 2L ** 32:
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Michael\AppData\Local\Temp\pip-build-ew_yf7 o2\pyinstaller
```

My system:
* Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
* PyWin installed from `pywin32-219.win32-py3.4.exe`

**Comment by matysek** [comment]
Hi @msarfati,

PyInstaller 2.1 does not support python 3. We are working hard on getting Python 3 working. You might try our python3 branch. Mostly works:
https://github.com/pyinstaller/pyinstaller/tree/python3

**Comment by matysek** [comment]
I think it might be a good idea to publish a prerelease of python3 branch on PYPI.

**Comment by msarfati** [comment]
I agree. Or at least update the documentation, which says to just run ```pip install pyinstaller```:
https://htmlpreview.github.io/?https://github.com/pyinstaller/pyinstaller/blob/python3/doc/Manual.html#installing-in-windows
