### ISSUE TITLE
PYPI prerelease of python3 branch

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1381]
I think a good idea would be to publish a development version `3.0.dev0` on PYPI.
* `pip` by default installs stable versions. But command `pip install --pre PyInstaller`  should also install development or prerelease versions.
* This attempt will test and improve our release process.

More info for packaging: https://packaging.python.org/en/latest/index.html

**Comment by htgoebel** [comment]
IMHO this is a bug in pip. PyInstaller is clearly marked as "Python 2 only"

**Comment by matysek** [comment]
TODO:
* make sure `setup.py sdist` works and bundles all required files
* signing the `tar.gz` file
* test uploading to pypi `twine upload dist/*`

**Comment by matysek** [comment]
* I created a `3.0.dev0` prerelease: https://pypi.python.org/pypi/PyInstaller/3.0.dev0
* It can be installed by:
```
pip install --pre PyInstaller
```

**Comment by matysek** [comment]
* I will try to do next prerelease `3.0.dev1` signed.

**Comment by matysek** [comment]
I created another prerelease so I'm closing this.

https://pypi.python.org/pypi/PyInstaller/3.0.dev2
