### ISSUE TITLE
propagate modulegraph changes upstream

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1401]
Recent upgrade of modulegraph ( https://github.com/pyinstaller/pyinstaller/commit/bba025f6861f27f7107b3e4105e9bb9abf49e35f )
 version broke python3 branch and reverted some custom module graph changes that were not yet submitted to upstream.

Tasks:
* Fix module graph in python3 branch.
* Propagate graph hook related changes to upstream of modulegraph.

**Comment by htgoebel** [comment]
@matysek I'm sorry for causing this trouble.  I really did a bad job in bba025f. Mea culpa!

**Comment by matysek** [comment]
Upstream pull request: https://bitbucket.org/ronaldoussoren/modulegraph/pull-requests/12/
