### ISSUE TITLE
Make all tests passing in PyInstaller 2.1 pass in python3-branch

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1402]
Here is an overview of the current test-status. Please update this list whenever an issue is solved. We should not merge `python3` into `develop` as long as there are test worse then in release 2.1 or fall behind `develop` head.

* **bold** means: this is worse then in release 2.1 resp. when using the other Python version
* Referenced issues point to the issue this is tracked in (only for failing tests)
* Referenced commits  point to where this has changed (normally: solved)
* `?` means: Not tested at the moment (e.g. because the library is not installed on my system)
* This list contains only test-cases which failed in release 2.1, failed on develop-head or fail on python3-branch.

Testname | Release 2.1 | `python3`-branch with Python 3.3 | `python3`-branch with Python 2.7
---------|---------|-----------------|----
**basic/** |
test_pkg_structures       | pass | **fail** [3]  | **fail** [3]
test_pyz_as_external_file | -    | pass | pass
test_stderr_encoding | -    | - [6] | - [6] 
test_stdout_encoding | -    | - [6] | - [6] 
**import/** |
test_c_extension         | fail | pass | pass
test_eggs1          | skip |   pass ce50cb9fc497 [1] | pass ce50cb9fc497 [1]
test_eggs2          | pass | pass ce50cb9fc497 [2] | pass ce50cb9fc497 [2]
test_nspkg-pep420   | pass | pass 82e6b3ad6 | n/a
test_nspkg1         | pass | pass 82e6b3ad6 | pass 82e6b3ad6
test_nspkg1-bbb-zzz | pass | pass 82e6b3ad6 | pass 82e6b3ad6´
test_nspkg1-empty   | pass | pass 82e6b3ad6 | pass 82e6b3ad6
test_nspkg2         | pass | pass 82e6b3ad6 | pass 82e6b3ad6
test_onefile_c_extension              | fail | pass | pass
~~test_onefile_pkgutil-get_data__main__~~ | - | skip [4] #1456 | skip [4] #1456
test_onefile_relative_import          | pass | pass [7] #1382 | pass
test_onefile_relative_import2         | pass | pass [7] #1382 | pass
test_onefile_relative_import3         | pass | pass [7] #1382 | pass
**libraries/** |
test_gst | pass | ? | pass 50e145a1
test_pycrypto        | pass | pass | pass
test_onefile_tkinter | pass | - [6] | - [6]
test_PyQt4-uic | - | fail | fail
test_python_makefile | pass | pass | **fails** on multiplatform
test_requests | - (develop: pass) | pass | pass
test_sphinx          | skip (develop:fail) | pass | pass
test_twisted_qt4reactor | fail | ? | pass
test_twisted_reactor    | fail | pass | pass
test_wx_pubsub_arg1  | pass | pass https://github.com/pyinstaller/pyinstaller/issues/1367#issuecomment-143542610 | pass https://github.com/pyinstaller/pyinstaller/issues/1367#issuecomment-143542610
test_wx_pubsub_kwargs  | pass | pass https://github.com/pyinstaller/pyinstaller/issues/1367#issuecomment-143542610 | pass https://github.com/pyinstaller/pyinstaller/issues/1367#issuecomment-143542610
test_wx_pubsub  | pass | pass | pass https://github.com/pyinstaller/pyinstaller/issues/1367#issuecomment-143542610 | pass https://github.com/pyinstaller/pyinstaller/issues/1367#issuecomment-143542610
**crypto** |
test_crypto          | - | - [6] | - [6]
test_onefile_crypto  | - | - [6] | - [6]

<h5>Notes</h5>
* [1] While modulegraph supports including modules from eggs, we don't support adding the data. This was unsupported in PyInstaller 2.1, too. Also see #1362.
* [2] While modulegraph supports including modules from eggs, we don't support adding the data. This worked in Python 2.1. Also see #1362.
* [3] This is a quite hacky test at all and needs to be reworked
* [4] Our import mechanism returns the wrong loader-class for `__main__`.
* [5] This passed in develop 90304142
* [6]  Moved to the new test-suite. They are listed here, because they are in the list in https://github.com/pyinstaller/pyinstaller/issues/1341#issuecomment-124833911
* [7]  Moved to the new test-suite. They are listed here, because they failed earlier.

**Comment by htgoebel** [comment]
Made test_gst pass (only tested for Python 2.7) 50e145a1.

**Comment by matysek** [comment]
I agree that relative imports and data-file from eggs should be fixed prior merging python3 branch.

**Comment by htgoebel** [comment]
Test-cases for relative imports for Python 3.3 and 3.4 work again, see https://github.com/pyinstaller/pyinstaller/issues/1382#issuecomment-131452540

**Comment by htgoebel** [comment]
test_eggs1 and test_eggs2 now pass, see ce50cb9fc and now closed #1362.

**Comment by htgoebel** [comment]
I've just seen that `test_onefile_pkgutil-get_data__main__`  did  nod exist in v2.1: v2.1 was released 2013-09-27, while `test_onefile_pkgutil-get_data__main__` 2014-12-24. So I'm removing this one from the blocking list and will postpone the related issues to milestone 3.1

**Comment by htgoebel** [comment]
est_wx_pubsub_arg1, test_wx_pubsub_kwargs and test_wx_pubsub now pass, see https://github.com/pyinstaller/pyinstaller/issues/1367#issuecomment-143542610

**Comment by htgoebel** [comment]
All tests beside the weird hack `test_pkg_structures` pass now. I'. closing this issue.
