### ISSUE TITLE
About "WARNING: library python%s%s required via ctypes not found" issue

### ISSUE THREAD

**Issue by MengJueM** [pyinstaller/pyinstaller#1403]
This warning is always genereted by `"PyInstaller.depend.util.py"` in `"def scan_code_for_ctypes(co, instrs, i)`". The root cause is from below like source code:

```
        self.pythondll = \
            CDLL('python%s%s' % (sys.version[0], sys.version[2]))
```

The OPCODE is:

```
            369 LOAD_GLOBAL             29 (CDLL)
            372 LOAD_CONST               6 (u'python%s%s')              
            375 LOAD_GLOBAL             30 (sys)
            378 LOAD_ATTR               31 (version)
            381 LOAD_CONST               1 (0)
            384 BINARY_SUBSCR       
            385 LOAD_GLOBAL             30 (sys)
            388 LOAD_ATTR               31 (version)
            391 LOAD_CONST               7 (2)
            394 BINARY_SUBSCR       
            395 BUILD_TUPLE              2
            398 BINARY_MODULO       
            399 CALL_FUNCTION            1
            402 LOAD_FAST                0 (self)
            405 STORE_ATTR              32 (pythondll)
```

Based on the below code in `def scan_code_for_ctypes(co, instrs, i)`:

```
        if name in ("CDLL", "WinDLL"):
            # Guesses ctypes imports of this type: CDLL("library.so")

            # LOAD_GLOBAL 0 (CDLL) <--- we "are" here right now
            # LOAD_CONST 1 ('library.so')

            _libFromConst(i + 1)
```

We can catch the bug right here:
>             # Guesses ctypes imports of this type: CDLL("library.so")
>            # LOAD_GLOBAL 0 (CDLL) <--- we "are" here right now
>            # LOAD_CONST 1 ('library.so')

`'python%s%s' % (sys.version[0], sys.version[2])` has to be calculated in multiple OPCODE steps until BINARY_MODULO, but PyInstaller only tracks the first OPCODE `LOAD_CONST`. 

I'm trying to raise a PR to fix this bug, but yet not finding a elegant way to execute the partly OPCODE. Do you guys have any comment?

**Comment by codewarrior0** [comment]
The warning is harmless. The python DLL is explicitly included by the Analysis step, so we don't care if scan_code_for_ctypes doesn't find it.

**Comment by htgoebel** [comment]
We are not going to implement a byte-code interpreter. This will be an endless story.
