### ISSUE TITLE
Change interface of `add_binary` and Co.

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1405]
I just stepped over `FakeModule.add_binary()` (I've seen it earlier, but did not review it) and I find it irritating and complicated.

1. It's called "add binary" (singular), but expects a list of binaries.
2. It requires to pass 3-tuples, while the last element is fixed for all cases: it has to be `"BINARY"`.
3. It does not even test if the third element of each tuple actually is `BINARY`. This is done later in `FakeModule._process_hook_function`.
4. `FakeModule._process_hook_function` strips this 3rd element and add the elements to `self.binaries`.
5. In none of the cases (as far as I've seen), it has any benefit over setting the module-global variable `binaries` in the hook:
  * 21 times out of 26 it is used to add binaries collected by `qt5_plugins_binaries` (and related functions).
  * 2 times it is used to add binaries collected by `_resolveCtypesImports()`
  * 3 times it is used to add single files.

* The same is true for `add_data` - which is used a single time
* Both `add_import` and `del_import` are used exactly once: in `hook-PIL.Image.py` - which is for a outdated package.

##### Questions
* What are the reasons for having `FakeModule` these methods (`add_import`, `del_import`, `add_data` and `add_binary`)?

##### Proposal
1. Remove `add_binary` and `add_data`.
2. If not: rename `add_binary` to ``add_binaries`

What do you think?

**Comment by tallforasmurf** [comment]
I confess that FakeModule class and its methods were my invention. (It may have been changed some since then.)  I wanted some way to make existing hooks work with my modulegraph code. A hook expected to receive a Module and the new assembly logic did not have a Module to give. So it passed something that offered the facilities that hooks expected to find in a Module.
The point is that -- as far as I know, perhaps it has changed since -- the only purpose of FakeModule is to interface to hooks. If there is a way to do it better, do not hesitate to change it.

**Comment by matysek** [comment]
* As @tallforasmurf mentioned, the `FakeModule()` was created to migrate import hooks to modulegraph.
* Now some of its methods are just duplicated and useless.
* I agree that FakeModule should be reviewed. @htgoebel go ahead with what you think is good.
* We should also review the api we need to provide for `hook(mod)`.

@tallforasmurf thanks for your invention

**Comment by htgoebel** [comment]
I eliminated `add_binary` and `add_datas`, see https://github.com/htgoebel/pyinstaller/tree/1405-eliminate-add_binaries-add_datas. I'll pull-request and merge as soon as the CI tests pass.

**Comment by htgoebel** [comment]
@matysek: I wonder what is the difference between `excludedimports` and those removed using `del_import`. The later ones are simply passed to [`mod_graph.removeReference()`](https://github.com/pyinstaller/pyinstaller/blob/python3/PyInstaller/building/imphook.py#L300), while for the former once we have [a lot of code](https://github.com/pyinstaller/pyinstaller/blob/python3/PyInstaller/building/imphook.py#L361).

Contrary, `add_import` works exactly like `hiddenimports`.

**Comment by matysek** [comment]
@htgoebel I think 'del_import' was supposed to work the way `excludedimports` works.

**Comment by matysek** [comment]
@htgoebel What is the status of this issue? Is it still valid with the new replacement for FakeModule?

**Comment by htgoebel** [comment]
Well, `del_import` works differently: It just calls `mod_graph.removeReference` for each listed node (see [line 338](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/imphook.py#L338)). Whereas `excludedimports` result in more magic, see [line 404](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/imphook.py#L404).

So I'm totally unsure what to to.

The best would we if https://github.com/pyinstaller/pyinstaller/issues/1553#issuecomment-144012794) would be done :-)

**Comment by htgoebel** [comment]
This can be closed if #1557 will be merged.
