### ISSUE TITLE
PyInstaller fails when ZODB3 is an imported Module 

### ISSUE THREAD

**Issue by robert-boulanger** [pyinstaller/pyinstaller#1413]
When packing an application which uses ZODB pyinstaller fails. The module pickle_3.py used by zodbpickle has in sum 4 classes with constructors like this:

    def __init__(self, file, protocol=None, *, fix_imports=True):

PyImporter fails with the following output (it doesn't like the asterisk) :

    13981 ERROR: invalid syntax (pickle_3.py, line 178)
    Traceback (most recent call last):
      File "/usr/local/lib/python2.7/site-packages/PyInstaller/depend/owner.py", line 110, in getmod
        co = compile(stuff.replace("\r\n", "\n"), py[0], 'exec')
      File "pickle_3.py", line 178
        def __init__(self, file, protocol=None, *, fix_imports=True):
                                                ^
    SyntaxError: invalid syntax

this occurs when using python 2.7.10 on OSX (brew install) as well with python 2.7.10 on Windows 7

**Comment by htgoebel** [comment]
This module uses Python3 syntax, while you are using Python 2.7. You need to use the current `python3`-branch head and exclude this module using the `--exclude-module=` option.

Alternatively you may implement a hook excluding this module depending on the Python version used. Please see https://htmlpreview.github.io/?https://github.com/pyinstaller/pyinstaller/blob/python3/doc/Manual.html#using-hook-files.

We'd appreciate if you'd implement a hook and issue a pull-request, as this would others help :-)

**Comment by matysek** [comment]
@htgoebel I just realized that the --exclude-module option is broken in python3 branch.
@robert-boulanger How did you installl zodb? Just `pip install zodb`?

**Comment by robert-boulanger** [comment]
I installed it via pip

**Comment by matysek** [comment]
@robert-boulanger Do you have any simple code example that reproduces the issue?

**Comment by robert-boulanger** [comment]
lnstalled it via pip ZODB3

    pip install ZODB3

but I figured out, that adding excludes=['zodbpickle.pickle_3'],  like here

    a = Analysis(['myscript.py'],
             excludes=['zodbpickle.pickle_3'],
             pathex=['/Users/robert/Development/python/requirements'],
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None)

and using the current dev branch (2.1.1) will work and zodb gets packed correctly and works.

**Comment by robert-boulanger** [comment]
@matysek: here a short example to reproduce:

    import ZODB, ZODB.FileStorage
    from  BTrees.OOBTree import OOBTree
    from persistent import Persistent
    import transaction
    from random import randrange

    class Test():
        def __init__(self,i):
            self.i=i*i

    if __name__ == "__main__":
        storage = ZODB.FileStorage.FileStorage('test.fs')
        db = ZODB.DB(storage)
        connection = db.open()
        root = connection.root()
        if not root.has_key('testentry'):
            root['testentry'] = OOBTree()
        transaction.commit()
        testTree = root['testentry']
        for i in range(randrange(1,50),randrange(50,100)):
            if not i in testTree:
                test=Test(i)
                testTree[i] = test
        transaction.commit()

**Comment by matysek** [comment]
I'm closing this. The --exclud-module option is fixed in python3 branch and your example worked for me with Python 3.4 on OSX.
