### ISSUE TITLE
use mingw-w64 to compile bootloader in appveyor

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1414]
Recent changes in PR #1409 require the option `-municode` to be passed to gcc:
* But default mingw on appveyor does not have this option.
* mingw-w64 should be installed on appveyor and used to compile bootloader

Resources:
* http://mingw-w64.org/
* http://www.appveyor.com/docs/installed-software

**Comment by codewarrior0** [comment]
Theoretically, we should be able to have AppVeyor send a pull request whenever the bootloader is changed.

**Comment by matysek** [comment]
@codewarrior0 I would not automate this yet at least until PyInstaller 3.0 is out.
