### ISSUE TITLE
Close python3-branch and merge it back into develop

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1417]
This is a flow up to #1341 

matysek wrote:
> Do you have any estimate when python3 could be merged into develop?

This depends on which test-cases of #1402 we decode on to be working prior to merging. I thing, at least the test related to relative import #1382 and data-file from eggs #1362 should be fixed. If you disagree, please comment at #1402.

Regarding the estimate: I have this on my list with top priority of all PyInstaller-related stuff. Unfortunately may paid projects demand some more time at the moment. So if you could support n these issues, feel free. (Just mind to assign the ticket to yourself then :-)

##### List of blocking issues

- ~~test related to relative import #1382~~ done, see https://github.com/pyinstaller/pyinstaller/issues/1382#issuecomment-131452540
- ~~test related to data-file from eggs #1362~~ done, see https://github.com/pyinstaller/pyinstaller/issues/1402#issuecomment-137687141
- ~~modulepath not honoring `__path__` extensions, see #1322 and https://github.com/pyinstaller/pyinstaller/issues/1420#issuecomment-135657824~~ closed, see https://github.com/pyinstaller/pyinstaller/issues/1322#issuecomment-143546397
-  ~~Distutils package not bundled when run from virtualenv. #1420~~ solved, see 62642f3bb

Should this block too?
-  ~~Module Import Ordering Preserved #1393~~ merged  0f0c14f

**Comment by codewarrior0** [comment]
For the record, I can now build my main project MCEdit (Python 2.7, numpy, PySide, and others) using the python3 branch, so this has my approval :+1:

**Comment by leycec** [comment]
Thanks for the [exhaustive test-case comparison](https://github.com/pyinstaller/pyinstaller/issues/1402)! So ultimate. So useful. We're almost at the starting gates, folks. :horse: 

I'm currently catapulting through a number of [breaking issues](https://github.com/pyinstaller/pyinstaller/pull/1393) in my valiant (..._but probably ultimately futile_) attempts to resolve #1367 and its  corresponding three failing functional tests. It'd be great if we could hold off on the branch transition until I nail this sucker to the cross.

**Comment by leycec** [comment]
**Please God(s) don't do this yet.**

See the section "Backward Compatibility" at [this comment](https://github.com/pyinstaller/pyinstaller/issues/1420#issuecomment-135657824). The `python3` branch appears to have broken backward compatibility with respect to user-defined hooks in fairly severe ways _that totally aren't my fault_.

**Comment by matysek** [comment]
I was hoping that `hook(mod)` function could be dropped dropped one day and be fine with just global variables. But that is probably not going to happen.

I think breaking barckward compatibility is ok when:
* we do a lot of changes - e.g. Python 3
* we provide stable and consistent alternative
* we document the changes.

**Comment by leycec** [comment]
> I was hoping that hook(mod) function could be dropped dropped one day and be fine with just global variables. But that is probably not going to happen.

Man, I _wish_. My insane life would become sane and happy. Unfortunately, I can say with 103.4% certainty that "...it ain't gonna happen."

For traditional post-import hooks, global variables are sufficient. Which is great! For anything more complex, however – like hooks manipulating the underlying module graph, method parameters, or return values (e.g., the recently created post-create package and pre-import module hooks) – it _really_ helps to have an intermediate data structure sanitizing communication between the external hook and the PyInstaller codebase.

**Enter `FakeModule`,** the bane of my short-lived existence.

**Comment by matysek** [comment]
@htgoebel Are we going to merge `python3` before `3.0` release or are we fine with having python3 as the default branch?

**Comment by htgoebel** [comment]
IMHO the blockers for merging into develop are release-blockers, too.

**Comment by htgoebel** [comment]
#1393 was merged today.
I closed #1322, as this has basically been solved by implementing post-create package hooks.

**Comment by htgoebel** [comment]
Now all blocking issues are solved, I'm going to merge. But I'll have to do some minor cleanup-work first. Although It should happen today.

**Comment by htgoebel** [comment]
Done!

**Comment by htgoebel** [comment]
Branch python3 is gone! Please continue. contribution on the `develop` branch

**Comment by htgoebel** [comment]
Wiki main-page is updated.
