### ISSUE TITLE
Unit-tests should send test fail reason to stdout rather than stderr

### ISSUE THREAD

**Issue by codewarrior0** [pyinstaller/pyinstaller#1418]
The tests currently raise SystemExit on failure, which sends its message to stderr. The message is mixed in with the build debug output and the loader debug output. Almost nothing goes to stdout, so this would make it easier to find the failure reason.

**Comment by htgoebel** [comment]
Is this still an issue?

**Comment by codewarrior0** [comment]
Negative. Since installing pytest-catchlog, the output is cleanly separated.
