### ISSUE TITLE
Filename encoding in archive files

### ISSUE THREAD

**Issue by codewarrior0** [pyinstaller/pyinstaller#1422]
Filenames are encoded as UTF-8 when stored in the archive. This is correct, as we can't know the encoding the system will have when the app is run. There are two edge-cases remaining for properly encoding filenames, and hopefully the last two I'll have to think about:

**Archive extraction:** On Linux systems where the locale encoding is not UTF-8, during archive extraction the filename needs to be decoded from UTF-8 and re-encoded using the locale encoding. This is the edgiest of edge cases, and only worth mentioning because some folks on the python-dev mailing list keep bringing up Latin-1 encoding (ISO-8859-1) whenever encodings are discussed. (This is already handled on Windows, where our internal filenames are always UTF-8, and on OS X, where the system's filenames are always UTF-8)

**Archive building:** When using Python 2.7 to build the archive, the syntax `fn.encode('utf-8')` will raise a UnicodeDecodeError if `fn` is a filename containing non-ASCII characters, since calling `encode` on a `str` will implicitly decode it to `unicode` using the default encoding, which is ASCII. PyInstaller on Python 2.7 generally uses `str` as filenames, which means their encoding is ANSI. So, on Python 2.7, we should decode `fn` using `sys.getfilesystemencoding()` before encoding to utf-8. (Relevant to #1222)

**Comment by htgoebel** [comment]
Good that you spotted this. Is there any need to adopt archive-viewer and maybe even the test-cases, too? If so, I'll put this into you experienced hands.

**Comment by codewarrior0** [comment]
I haven't looked, but I'd expect that if anything is needed for the archive-viewer or test-cases, it would be to decode with utf8 and encode with fsencoding, or vice versa, and even then only on python 2.

**Comment by Legorooj** [comment]
Stale
