### ISSUE TITLE
travis tests seam to fail randomly

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1423]
travis tests seam to fail randomly:

* 734.2 (Py 3.3): test_zmq[onefile]
* 734.3 (Py 3.4): test_tkinter[onedir]

And then, without any related changes:

* 735.1 (Py 2.7): test_zmq[onedir]: No executable file was found
* 738.1 (Py 2.7): test_zmq[onedir]: No executable file was found

But then, without any meaningful changes at all (only to README files):
* 739.1 (Py 2.7): test_tkinter[onedir]: No executable file was found

NB: 736, 377 are for pull-request

**Comment by codewarrior0** [comment]
In the test_zmq failure in 738.1:

`INFO: wrote /tmp/pytest-0/popen-gw2/test_zmq_onefile_0/django_site.spec`

Why is it building django_site.py?

Oh, I see. Default arguments to test_script are `[]` when they should be `None`. Fix coming right up.

**Comment by codewarrior0** [comment]
Fixed!

**Comment by matysek** [comment]
It usually happened only after running django tests. I haven't found out yet why. Thanks if that really fixes it.

**Comment by codewarrior0** [comment]
It's the [Mutable Default Arguments](http://docs.python-guide.org/en/latest/writing/gotchas/) gotcha. The django test uses `app_name` which would get stored in `app_args` and reused for later tests.

**Comment by htgoebel** [comment]
I had a bad feeling when I saw these lists as default arguments. We should get rid of them ASAP, bei either replacing by `None` or an empty tuple `()` (the later is a tick I've seen in modulegraph).
