### ISSUE TITLE
Errors out with "libz.so.1 file too short" (or something similar) when creating file in /tmp fails

### ISSUE THREAD

**Issue by shrikrishnaholla** [pyinstaller/pyinstaller#1428]
Problem detected downstream with docker/compose#1761

Basically, if creating files in `/tmp` fails for whatever reason, the executable panics and becomes useless. Maybe there should be some kind of fallback if file creation at `/tmp` fails?

In my case, somehow `/tmp` had gotten mounted to a block device with a `1M` size limit. So when the [docker-compose](https://github.com/docker/compose) binary tried to create files, it couldn't and the next stage (or whatever) expected those files to be present and panicked when they weren't found.

**Comment by julienvincent** [comment]
+1 would like a fix

**Comment by codewarrior0** [comment]
I have a feeling PyInstaller apps aren't the only thing that break if your `/tmp` is suddenly non-writable. Besides, where would you even fall back to?

**Comment by shrikrishnaholla** [comment]
> I have a feeling PyInstaller apps aren't the only thing that break if your /tmp is suddenly non-writable.

That wouldn't matter as I was running this on a server and not on a desktop. Hence I needed only a couple of programs running.
I was just wondering whether adding a try catch block to `mktemp()` and trying alternative locations (`$HOME/.tmp` maybe?) would be more helpful.
Although solving this problem manually seems simple, adding simple fallbacks like these helps automate away stuff without having to worry about sudden changes in the environment

**Comment by codewarrior0** [comment]
> That wouldn't matter as I was running this on a server and not on a desktop.

That makes no difference. Having a non-writable `/tmp` is a sensible failure condition for a program that needs to write temporary files. We're not going to clutter your home directory with files that won't ever be deleted after the app crashes. The best "fix" you can hope for is for us to fail sooner, when the `write()` fails, rather than later, when the incomplete temp folder is accessed.

**Comment by codewarrior0** [comment]
#1429 describes the fix.

**Comment by codewarrior0** [comment]
If you need to direct a pyinstaller app to a different temp folder, you may use the `TMPDIR` environment variable.

**Comment by shrikrishnaholla** [comment]
Makes sense. Thanks

**Comment by htgoebel** [comment]
@shrikrishnaholla Like any other good Unix application does :-) So no need for any fall-back.
