### ISSUE TITLE
Bootloader: Add FATAL_PERROR macro

### ISSUE THREAD

**Issue by codewarrior0** [pyinstaller/pyinstaller#1431]
Add a variant of the FATALERROR macro, similar to `perror`, which uses `strerror` to also print a description of the error code in `errno`. It can be used to print error messages from stdlib failures like so:

```
result = fwrite(data, ntohl(ptoc->ulen), 1, out);
if(1 != result) {
    FATAL_PERROR("fwrite", "Failed to write all bytes for %s", ptoc->name);
    return -1;
}
```

With output that should look like this:

```
Failed to write all bytes for python27.dll (fwrite: Permission denied)
```

Similarly, for Windows OS errors, add a macro FATAL_WINERROR which will use `GetLastError()` and `FormatMessage()` to print the error message. See also the function `GetWinErrorString()` in `pyi_win32_utils.c`

**Comment by htgoebel** [comment]
Sounds like a good idea.

**Comment by htgoebel** [comment]
@codewarrior0 What is the status of this issue? Are you going to submit a pull-request anytime soon?

**Comment by codewarrior0** [comment]
I.... could have sworn I merged this in a long time ago. Let me take a look.

**Comment by htgoebel** [comment]
Should I wait with rebuilding the bootloaders?

**Comment by codewarrior0** [comment]
All done! Rebuild them whenever you're ready.
