### ISSUE TITLE
onefile output is different size every time (unreliable order of dict iteration)

### ISSUE THREAD

**Issue by tartley** [pyinstaller/pyinstaller#1434]
Running pyinstaller several times in succession creates an executable with a different size every time. The size itself isn't a problem, it's the lack of reproducibility that worries me.

    for n in 1 2 3 4 ; do rm -rf build dist; python $(which pyinstaller) --onefile main.py 2>out; ls -l dist/main; done
    -rwxr-xr-x 1 jhartley jhartley 4878415 Aug 24 21:18 dist/main
    -rwxr-xr-x 1 jhartley jhartley 4881686 Aug 24 21:18 dist/main
    -rwxr-xr-x 1 jhartley jhartley 4878549 Aug 24 21:19 dist/main
    -rwxr-xr-x 1 jhartley jhartley 4882598 Aug 24 21:19 dist/main

Adding '--clean' to the pyinstaller cmd line args make no difference.

Where the content of main.py is:

    #!/usr/bin/env python
    
    import sys
    print(sys.version_info)

This is on version 3.0dev-0b01b1b, on the python3 branch, commit 0b01b1bfe0f32d2a26fbaa3a7952e96ab61ecdef.

I'm on Ubuntu 15.04, Python 3.4.3.

**Comment by codewarrior0** [comment]
This *is* worrying.

I suspect it is because things like modules are kept in a `dict` at some point and then read out in an undefined (`dict`-determined) order, and if hash seed randomization is enabled, each run will give a different order.

It would be even more worrying if the contents of the TOC files are changing, and not just with respect to the ordering.

**Comment by htgoebel** [comment]
@tartley Could you please check which of the files in `build` changed? This would help narrowing where to search.

**Comment by codewarrior0** [comment]
Hash seed randomization seems to be the default for Python 3.3+, so the unreliable order of `dict` iteration might be one explanation.

This is probably the explanation, since using `python3` branch with Python 2.7 produces identical output every time, but Python 3.4 does not.

**Comment by htgoebel** [comment]
Closed by #1582. Please look there and in the manual for more information.
