### ISSUE TITLE
python guidebook: update pyinstaller

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1435]
Create pull request for https://github.com/kennethreitz/python-guide that will update the notes about pyinstaller at this page: http://docs.python-guide.org/en/latest/shipping/freezing/

Thinks to update:
- PyInstaller supports Python 3
- remove the prerequisite pywin32 - it will get installed automatically
- pyinstaller bundles MS Visual C++ dlls
- import from zip files
  ...

**Comment by tartley** [comment]
FWIW just yesterday I submitted a modest PR to python-guide:
https://github.com/kennethreitz/python-guide/pull/548
amending the opening paras of both the 'freezing' and 'packaging' pages, aiming to discuss the pros and cons of packaging versus freezing, and when you would choose each. I did this as a way to get feeback on the PR before embarking on the planned next task of adding pyinstaller notes there.

**Comment by htgoebel** [comment]
The pull-request has been merged. Can we close this issue?

**Comment by matysek** [comment]
* No, see the description for more details.
* The guidebook cannot be updated unless 3.0 is released.

**Comment by tartley** [comment]
Agree with matysek: My PR on python-guide was only a modest few intro paras. It did not dive into describing PyInstaller at all yet.

**Comment by htgoebel** [comment]
I'm closing this, as this is nothing to be done by use. That guide is a project independent of PyInstaller and we can not take care about all of these guides.
