### ISSUE TITLE
Running executable via the PATH gives "Cannot find self..."

### ISSUE THREAD

**Issue by tartley** [pyinstaller/pyinstaller#1436]
Running my generated executable using

    $ dist/hello
    hello world

works fine, but if I then move it to anywhere on the $PATH:

    $ mv dist/hello ~/bin
    $ hello
    Cannot open self /home/jhartley/scratch/pyexe/hello or archive /home/jhartley/scratch/pyexe/hello.pkg
    $ echo $?
    255

It works whenever I type in the full absolute or relative path to the executable, but doesn't work if the executable has been found by virtue of being on my PATH.

Where:

    $ cat hello.py
    print('hello world')

Executable built using:

    rm -rf hello.spec dist build ; pyinstaller --onefile --clean hello.py

Ubuntu 15.4,  Python 3.4.3, pyinstaller 3.0dev-0b01b1b.

Apologies if I'm making some elementary error.

**Comment by codewarrior0** [comment]
I think this was broken in 0d599eec02894dd383785a21b0f7689b08a905a3.

[StackOverflow](http://stackoverflow.com/questions/933850/how-to-find-the-location-of-the-executable-in-c) describes ways to find the executable on different platforms, and notes that `argv[0]` isn't 100% trustworthy and that the problem of finding the exe is hard on platforms without `/proc` or platform-specific functions.

**Comment by codewarrior0** [comment]
Should be fixed in d2e749f0d1fede80828c29837940a9269f596ebb

**Comment by tartley** [comment]
Confirmed this now works fine for me on the tip of python3 branch. Thanks everyone, you rock!
