### ISSUE TITLE
scan_code_for_ctypes - only for pure python ( no attribute 'co_code' )

### ISSUE THREAD

**Issue by akbhat** [pyinstaller/pyinstaller#1437]
This is related to ticket #1346. The solution worked for Windows but the following error is encountered when executed on Ubuntu. How do I resolve this?
```
abhat@ubuntu:~/Desktop$ pyinstaller --onefile --hidden-import=ncclient.devices.junos jdatap.py
12 INFO: PyInstaller version 3.0dev
12 INFO: wrote /home/abhat/Desktop/jdatap.spec
15 INFO: UPX is not available.
16 INFO: Extending PYTHONPATH with /home/abhat/Desktop
16 INFO: checking Analysis
17 INFO: Building Analysis because out00-Analysis.toc is non existent
17 INFO: Initializing module dependency graph...
18 INFO: Looking for graph hooks ...
19 INFO: Analyzing hidden import 'ncclient.devices.junos'
2295 INFO: running Analysis out00-Analysis.toc
2313 INFO: Analyzing jdatap.py
3858 INFO: Looking for import hooks ...
3860 INFO: Processing hook hook-distutils.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:15: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
import distutils
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:16: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
import os
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:17: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
import sys
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:18: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
import sysconfig
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:20: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
from PyInstaller.compat import base_prefix
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-distutils.py:21: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
from PyInstaller.utils.hooks.hookutils import relpath_to_config_or_make
3862 INFO: Processing hook hook-sysconfig.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:15: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
import sysconfig
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:16: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
import os
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:17: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
import sys
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:19: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
from PyInstaller import compat
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-sysconfig.py:20: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
from PyInstaller.utils.hooks.hookutils import relpath_to_config_or_make
3863 INFO: Processing hook hook-xml.py
3930 INFO: Processing hook hook-jinja2.py
3964 INFO: Processing hook hook-lxml.etree.py
3978 INFO: Processing hook hook-httplib.py
3978 INFO: Processing hook hook-xml.sax.py
3979 INFO: Processing hook hook-encodings.py
/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/hooks/hook-encodings.py:11: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
from PyInstaller.utils.hooks.hookutils import collect_submodules
4325 INFO: Looking for ctypes DLLs
4367 WARNING: library rpcrt4.dll required via ctypes not found
Traceback (most recent call last):
File "/usr/local/bin/pyinstaller", line 9, in 
load_entry_point('PyInstaller==3.0.dev0', 'console_scripts', 'pyinstaller')()
File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/main.py", line 97, in run
run_build(opts, spec_file, pyi_config)
File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/main.py", line 50, in run_build
PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.dict)
File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/build_main.py", line 682, in main
build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/build_main.py", line 625, in build
exec(text, spec_namespace)
File "", line 12, in 
File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/build_main.py", line 181, in init
self.postinit()
File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/datastruct.py", line 151, in postinit
self.assemble()
File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/building/build_main.py", line 420, in assemble
ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.0.dev0-py2.7.egg/PyInstaller/depend/utils.py", line 147, in scan_code_for_ctypes
instrs = pass1(co.co_code)
AttributeError: 'NoneType' object has no attribute 'co_code'
```

**Comment by matysek** [comment]
@htgoebel Do you think that modulegraph could pass some wrong module types to `scan_code_for_ctypes`?

**Comment by htgoebel** [comment]
@akbhat We need to know which module is tested here but does not have a code-object. Please rerun with --log=DEBUG and grep the output for `for shared libraries or dlls`.

@matysek: Could be. We are not checking any type at [`get_co_using_ctypes`](https://github.com/pyinstaller/pyinstaller/blob/python3/PyInstaller/depend/analysis.py#L401), and simply use the referer's code-object without checking.

**Comment by akbhat** [comment]
@htgoebel Below is the dll grep with --debug.

abhat@ubuntu:~$ cat build.log | grep dll
4799 DEBUG: Scanning uuid for shared libraries or dlls
4839 WARNING: library rpcrt4.dll required via ctypes not found
4850 DEBUG: Scanning ctypes.util for shared libraries or dlls
4854 DEBUG: Scanning jinja2.debug for shared libraries or dlls
4857 DEBUG: Scanning /home/abhat/Desktop/jdatap.py for shared libraries or dlls
4859 DEBUG: Scanning ctypes.macholib.dyld for shared libraries or dlls

**Comment by htgoebel** [comment]
So `ctypes.macholib.dyld` seams to be to module causing the error. I tried reproducing this without success:

1. A simple program (just `import ctypes.macholib.dyld`) does *not* raise this error
2. In Python 2.7.9 `ctypes.macholib.dyld` does *not* even import `ctypes`, so it should not occur in this list at all.

Could you please try to find a minimal program (not using this junos stuff) which raises the error?

**Comment by akbhat** [comment]
@htgoebel The issue happens if you include the ncclient hidden import. Refer to the minimal code example at https://gist.github.com/akbhat/ff7e0a30c7521902b56b (junos stuff commented out).

pyinstaller --onefile d.py --log=DEBUG --hidden-import=ncclient.devices.junos

8008 INFO: Analyzing d.py
8100 INFO: Looking for import hooks ...
8109 INFO: Processing hook   hook-xml.py
8693 INFO: Processing hook   hook-lxml.etree.py
8776 INFO: Processing hook   hook-httplib.py
8805 INFO: Processing hook   hook-xml.sax.py
8835 INFO: Processing hook   hook-encodings.py
/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/hooks/hook-encodings.py:11: RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import
  from PyInstaller.utils.hooks.hookutils import collect_submodules
8871 DEBUG: Collecting submodules for encodings
9281 INFO: Looking for ctypes DLLs
9281 DEBUG: Scanning uuid for shared libraries or dlls
9316 WARNING: library rpcrt4.dll required via ctypes not found
9325 DEBUG: Scanning ctypes.util for shared libraries or dlls
9327 DEBUG: Scanning ctypes.macholib.dyld for shared libraries or dlls
Traceback (most recent call last):
  File "/homes/akbhat/twc/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.0dev', 'console_scripts', 'pyinstaller')()
  File "/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/main.py", line 97, in run
    run_build(opts, spec_file, pyi_config)
  File "/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/main.py", line 50, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/building/build_main.py", line 682, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/building/build_main.py", line 625, in build
    exec(text, spec_namespace)
  File "<string>", line 12, in <module>
  File "/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/building/build_main.py", line 181, in __init__
    self.__postinit__()
  File "/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/building/datastruct.py", line 151, in __postinit__
    self.assemble()
  File "/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/building/build_main.py", line 420, in assemble
    ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
  File "/homes/akbhat/twc/local/lib/python2.7/site-packages/PyInstaller-3.0dev-py2.7.egg/PyInstaller/depend/utils.py", line 147, in scan_code_for_ctypes
    instrs = pass1(co.co_code)
AttributeError: 'NoneType' object has no attribute 'co_code'

**Comment by matysek** [comment]
@akbhat Please try this version of `python3` branch. I think it fixes the issue: https://github.com/pyinstaller/pyinstaller/commit/ebe53b1c1dd3e467fb1420713e6b4be871139ed2

**Comment by matysek** [comment]
@akbhat Try again. I tested your  example on Windows with Python 2.7 and it is working.

**Comment by akbhat** [comment]
@matysek This is a Linux specific error so can you verify the fix on Linux? Windows worked before this fix.

**Comment by matysek** [comment]
@akbhat I tested also on linux it worked for me. I was not able to reproduce any error.

**Comment by akbhat** [comment]
@matysek Are these changes checked in? Can I just use the latest pyinstaller3_dev download?

**Comment by matysek** [comment]
@akbhat The changes are checked in. This link should download always latest version of `python3` branch. https://github.com/pyinstaller/pyinstaller/archive/python3.zip
