### ISSUE TITLE
zipimport: can not open file /tmp/_MEIruZRcw/base_library.zip

### ISSUE THREAD

**Issue by mo0feng** [pyinstaller/pyinstaller#1444]
I met a compiled program under Linux error:
**OS:** Linux 2.6.32-431.el6.x86_64 
**Issue:**CentOS
**Python Version:**3.3.6
**Pyinstall Versioner:** python3
**Pyinstaller exec:**
```
pyinstaller daemon_linux_cmdb_client.spec 
80 INFO: PyInstaller: 3.0dev
80 INFO: Python: 3.3.6
81 INFO: Platform: Linux-2.6.32-431.el6.x86_64-x86_64-with-centos-6.5-Final
84 INFO: An exception occured when testing for UPX:
84 INFO:   PermissionError(13, 'Permission denied')
85 INFO: UPX is not available.
86 INFO: Extending PYTHONPATH with /home/pyinstall/tools/linux_client
87 INFO: checking Analysis
97 INFO: Building because hiddenimports changed
97 INFO: Initializing module dependency graph...
100 INFO: Looking for graph hooks ...
103 INFO: Analyzing base_library.zip ...
4877 INFO: running Analysis out00-Analysis.toc
4902 INFO: Analyzing daemon_linux_cmdb_client.py
8640 INFO: Looking for import hooks ...
8643 INFO: Processing hook   hook-encodings.py
8662 INFO: Processing hook   hook-xml.py
8742 INFO: Processing hook   hook-site.py
8746 INFO: Processing hook   hook-xml.sax.py
8746 INFO: Processing hook   hook-pycparser.py
9082 INFO: Processing hook   hook-pydoc.py
9083 INFO: Processing hook   hook-cryptography.py
[('/usr/local/lib/python3.3/site-packages/cryptography/_Cryptography_cffi_53e352ffx62b488b1.cpython-33m.so', 'cryptography'), ('/usr/local/lib/python3.3/site-packages/cryptography/_Cryptography_cffi_773090caxffc7b1ce.cpython-33m.so', 'cryptography'), ('/usr/local/lib/python3.3/site-packages/cryptography/_Cryptography_cffi_4a89b544xd5c405b7.cpython-33m.so', 'cryptography'), ('/usr/local/lib/python3.3/site-packages/cryptography/_Cryptography_cffi_53e352ffx62b488b1.cpython-33m.so', 'cryptography'), ('/usr/local/lib/python3.3/site-packages/cryptography/_Cryptography_cffi_773090caxffc7b1ce.cpython-33m.so', 'cryptography'), ('/usr/local/lib/python3.3/site-packages/cryptography/_Cryptography_cffi_4a89b544xd5c405b7.cpython-33m.so', 'cryptography')]
9134 INFO: Processing hook   hook-distutils.py
9140 INFO: Processing hook   hook-sysconfig.py
9141 INFO: Processing hook   hook-setuptools.py
9215 INFO: Looking for ctypes DLLs
9233 INFO: Analyzing run-time hooks ...
9242 INFO: Including run-time hook 'pyi_rth_pkgres.py'
9263 INFO: Looking for dynamic libraries
10033 INFO: Looking for eggs - TODO
10034 INFO: Using Python library /usr/lib64/libpython3.3m.so.1.0
10072 INFO: Warnings written to /home/pyinstall/tools/linux_client/build/daemon_linux_cmdb_client/warndaemon_linux_cmdb_client.txt
10093 INFO: checking PYZ
10100 INFO: Building because toc changed
10100 INFO: Building PYZ (ZlibArchive) /home/pyinstall/tools/linux_client/build/daemon_linux_cmdb_client/out00-PYZ.pyz
10921 INFO: checking PKG
10923 INFO: Building because toc changed
10923 INFO: Building PKG (CArchive) out00-PKG.pkg
19745 INFO: Bootloader /usr/local/lib/python3.3/site-packages/PyInstaller/bootloader/Linux-64bit/run
19745 INFO: checking EXE
19747 INFO: Building because toc changed
19748 INFO: Building EXE from out00-EXE.toc
19751 INFO: Appending archive to EXE /home/pyinstall/tools/linux_client/dist/daemon_linux_cmdb_client
```
**Debug:**
```
./daemon_linux_cmdb_client start  
PyInstaller Bootloader 3.x
LOADER: executable is /home/pyinstall/tools/linux_client/dist/daemon_linux_cmdb_client
LOADER: homepath is /home/pyinstall/tools/linux_client/dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /home/pyinstall/tools/linux_client/dist/daemon_linux_cmdb_client
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /tmp/_MEIruZRcw
LOADER: LD_LIBRARY_PATH=/tmp/_MEIruZRcw
PyInstaller Bootloader 3.x
LOADER: executable is /home/pyinstall/tools/linux_client/dist/daemon_linux_cmdb_client
LOADER: homepath is /home/pyinstall/tools/linux_client/dist
LOADER: _MEIPASS2 is /tmp/_MEIruZRcw
LOADER: archivename is /home/pyinstall/tools/linux_client/dist/daemon_linux_cmdb_client
LOADER: Already in the child - running user's code.
LOADER: Python library: /tmp/_MEIruZRcw/libpython3.3m.so.1.0
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is /tmp/_MEIruZRcw/base_library.zip:/tmp/_MEIruZRcw
LOADER: sys.prefix is /tmp/_MEIruZRcw
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /tmp/_MEIruZRcw/base_library.zip:/tmp/_MEIruZRcw
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyiboot02_egg_install.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running daemon_linux_cmdb_client.py
LOADER: Back to parent (RC: 0)
LOADER: Doing cleanup
LOADER: Freeing archive status for /home/pyinstall/tools/linux_client/dist/daemon_linux_cmdb_client
```

**Comment by codewarrior0** [comment]
Those look to me like the logs from a successful build and execution. Did you forget to include the error and traceback?

**Comment by mo0feng** [comment]
@codewarrior0 
Try:
2015-08-27 16:35:23,885-Client-INFO-Activate:Debug--Enabled
2015-08-27 16:35:23,888-Client-ERROR-Connect Server Err:zipimport: can not open file /tmp/_MEIruZRcw/base_library.zip
2015-08-27 16:35:23,889-Client-INFO-Connect Service Success!
2015-08-27 16:35:23,892-Client-INFO-Data len:29
2015-08-27 16:35:23,893-Client-ERROR-Read JsonData Or Send Err:(32, 'EPIPE')
2015-08-27 16:35:23,893-Client-INFO-Connection died unexpectedly!
![pyinsaller_err_3](https://cloud.githubusercontent.com/assets/9604557/9516261/15809544-4cda-11e5-8dde-d9e48dbcc6ce.gif)

**Comment by codewarrior0** [comment]
Instead of `logger.error`, can you write `logger.exception` so you get the full traceback?

**Comment by mo0feng** [comment]
Thanks
I try again.

**Comment by codewarrior0** [comment]
I'm not sure what to make of this just yet.

It looks like you're writing a daemon. Do you use `os.setuid` or similar to make the daemon run as a different user? If so, that user probably doesn't have permission to read `base_library.zip` (or really, any file in the extraction dir.).

I don't know the best way to make PyInstaller support apps that use `os.setuid`. Maybe you'll have to use `chmod +s` instead to do the `setuid` at the OS level.

**Comment by mo0feng** [comment]
Yes, I am writing a daemon.
Thank you very much for your reply and help, I am using the root user is running this program.
I just put the python upgrade to 3.4, after upgrading found django has a similar mistake, the system may have multiple python environment and the relationship between python2.6 yum I use?Can I have a try to solve this problem.This is not a pyinstaller bug, is my wrong judgment.Thank you very much ~

**Comment by codewarrior0** [comment]
No problem, glad to help.

@htgoebel, any thoughts on onefile apps that try to use `os.setuid`?

**Comment by htgoebel** [comment]
@codewarrior0 I seen no point where we could solve this issue, there are too many places raise problems. To list just a few:

- No way to detect if we are running with `chmod +s` (AFAIK)
- No general way to set permissions for some group (umask may be set)
- the user and group to give the files to would need to be put into options somehow

To be frank: IMHO it's not a good idea to use setuid with `--onefile`. If one wants, he should implement the work-around fitting his requirements.

**Comment by codewarrior0** [comment]
I had the same feeling. It's up to the user's judgement on how to deal with `setuid` apps. All we can really do is make a note in the docs about the permissions issue with `os.setuid` with `--onefile`.

Closing as this is not something we can fix.

**Comment by mo0feng** [comment]
@codewarrior0  @htgoebel  
Thank your very much!

**Comment by tallforasmurf** [comment]
We already have that warning, see http://pythonhosted.org/PyInstaller/#how-the-one-file-program-works for the sentence, "Do not give administrator privileges to a one-file executable (setuid root in Unix/Linux, "Run this program as an administrator" property in Windows 7). There is an unlikely but not impossible way in which a malicious attacker could corrupt one of the shared libraries in the temp folder while the bootloader is preparing it. Distribute a privileged program in one-folder mode instead."
Does this need to be clarified or made more specific?

**Comment by codewarrior0** [comment]
It mentions the security issue, but it doesn't mention that `os.setuid()` won't work if you decide to setuid root anyway. Maybe the bootloader should output some alarming messages if it finds out it's running as root?

[I already added a note](https://github.com/pyinstaller/pyinstaller/commit/e4d9fcd03bdf1748636fa8c1cc8c2ef44a68cf00), but further edits [are welcome](https://github.com/pyinstaller/pyinstaller/edit/python3/doc/source/Manual.rst)
