### ISSUE TITLE
[Enhancement] pywin32 -> pypiwin32

### ISSUE THREAD

**Issue by Calrama** [pyinstaller/pyinstaller#1447]
Could you please use pypiwin32[1] instead of pywin32[2] as a dependency (for at least the python3 version of pyinstaller)?
The former is a pypi-compatible distribution of the latter, allowing for use in virtual environments, and proper automatic dependency installation through pip.

[1] https://pypi.python.org/pypi/pypiwin32
[2] https://pypi.python.org/pypi/pywin32

**Comment by matysek** [comment]
Do you mean to use 'pypiwin32' in `tests/requirements.txt` or pyinstaller in general should recommend `pypiwin32`?

**Comment by codewarrior0** [comment]
> Or even install pypiwin32 automatically when doing setup.py install for PyInstaller?

I like this idea. I didn't know there was a version available on pypi.

**Comment by matysek** [comment]
> I like this idea. I didn't know there was a version available on pypi.

When looking at pypi it looks like it was not until tomorrow.

**Comment by matysek** [comment]
done.

**Comment by codewarrior0** [comment]
:+1:

**Comment by Calrama** [comment]
Sorry for the late reply and thank you, this is exactly what I meant.

> When looking at pypi it looks like it was not until tomorrow.

One remark: pypiwin32 has been available since January, but it has not been publicised much.
