### ISSUE TITLE
Travis - run tests on OS X

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1448]
Travis supports running tests on OS X and OS X was recently enabled for our account. However the Python support in Travis is not complete and there are available some workarounds:
* bug report: https://github.com/travis-ci/travis-ci/issues/2312
* utilities for Travis and OS X: https://github.com/MacPython/terryfy
* example script: https://github.com/pyca/cryptography/blob/master/.travis/install.sh
* osx travis config example: https://github.com/MacPython/numpy-wheels/blob/master/.travis.yml

**Comment by htgoebel** [comment]
Thanks for taking care of this :-)

**Comment by matysek** [comment]
I'm thinking of creating a new respository 'pyinstaller-travis-osx' with own .travis.yml and this repository would reference other files from 'pyinstaller' main repository.

**Comment by matysek** [comment]
* I created a repo for running OS X tests on: https://travis-ci.org/pyinstaller/pyinstaller-osx-tests/
* However, I still haven't found out how to automate running OS X tests - notify Travis to run tests when another repository changes. @htgoebel and @codewarrior0 do you have any suggestion?

**Comment by matysek** [comment]
> Hmm... can't you use $TRAVIS_OS_NAME to conditionally run the OS X-specific install stuff only on OS X?

@codewarrior0 I can't use this variable because travis config file allows to specify only one programming language in it:
* Linux uses `language: python` - this does not work on OS X yet.
* OS X workaround is `language: objective-c` - workaround used by other projects to run tests on OS X with Travis.

> Instead of using a separate repo you chould use a separate branch. Or you need to add this repo as another project to travis.

@htgoebel could you tell more about this how it would work?

**Comment by matysek** [comment]
I tried set up this service: https://nightli.es/
* it should run the tests once a day.
* Let's see if it works.

**Comment by matysek** [comment]
Closing:
* https://nightli.es/ runs the osx tests once per day.
* I think for now running OS X tests once per day is sufficient.
