### ISSUE TITLE
Pyinstaller, no usb backend 

### ISSUE THREAD

**Issue by jksfiftyfive** [pyinstaller/pyinstaller#1449]
I have a GUI that Id like to turn into Windows 7 EXE with Pyinstaller.

This GUI communicates to a device via an FTDI SPI controller. Ive used pyftdi to implement communication. GUI works great.

However, Im getting the "no backend available" when I try to run my EXE.

It boils down to this part of the code, which ive just shortened to include my candidate (\pyftdi\pyftdi\usbtools.py):
```
c = 'libusb0'
print 'usb candidate: ',c
m = getattr(um, c)
print 'm attr: ',m
backend = m.get_backend()
```
Running this in python works great. Running it in EXE, backend returns None.

I noticed that Pyinstaller does have hooks for matplotlib backend and usb hook, so i was hoping that my solution would be a combination of these two.

hooks/usb hook.py just finds the library, but does none of this backend stuff:

```
# NOTE: Mind updating run-time hook when adding further libs.
libusb_candidates = (
    # libusb10
    'usb-1.0', 'usb', 'libusb-1.0',
    # libusb01
    'usb-0.1', 'libusb0',
    # openusb
    'openusb',
)


def hook(mod):
    for candidate in libusb_candidates:
        libname = ctypes.util.find_library(candidate)
        if libname is not None:
            break

    if libname is not None:
        # Use basename here because Python returns full library path
        # on Mac OSX when using ctypes.util.find_library.
        bins = [os.path.basename(libname)]
        mod.binaries.extend(_resolveCtypesImports(bins))
```

I do notice that the libusb0.dll is copied to my EXE directory.

So my questions are: 

1)How can i get Pyinstaller to either copy the usb-backend files that contain what its searching for, but cant seem to find? or just use the in-place structure that regular python seems to have no problem using

2)Does this have anything to do with the dll being local to my EXE dir, and do i need to copy some other files? (I did try just moving usb/backend dir to my EXE dir... no luck)

3)Can this be solved by adding more to usb hook to try to mimic the matlab-backend hook?
```
    def matplotlib_backends():
    """
    Return matplotlib backends availabe in current Python installation.

    All matplotlib backends are hardcoded. We have to try import them
    and return the list of successfully imported backends.
    """
    all_bk = eval_statement('import matplotlib; print matplotlib.rcsetup.all_backends')
    avail_bk = []
    import_statement = """
try:
    __import__('matplotlib.backends.backend_%s')
except ImportError, e:
    print str(e)
"""

    # CocoaAgg backend causes subprocess to exit and thus detection
    # is not reliable. This backend is meaningful only on Mac OS X.
    if not is_darwin and 'CocoaAgg' in all_bk:
        all_bk.remove('CocoaAgg')

    # Try to import every backend in a subprocess.
    for bk in all_bk:
        stdout = exec_statement(import_statement % bk.lower())
        # Backend import is successfull if there is no text in stdout.
        if not stdout:
            avail_bk.append(bk)

    # Convert backend name to module name.
    # e.g. GTKAgg -> backend_gtkagg
    return ['backend_' + x.lower() for x in avail_bk]
```
thanks

**Comment by matysek** [comment]
Please provide more information, especially you Python and PyInstaller version. See for more details:
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by codewarrior0** [comment]
It looks like it isn't including the python modules under `usb.backend`. Try putting this line in the usb hook and tell us if it makes a difference:

`hiddenimports=['usb.backend.libusb10', 'usb.backend.libusb01', 'usb.backend.openusb']`

**Comment by jksfiftyfive** [comment]
python version 2.7.9 32bit, pyinstaller 2.1

i did try adding that line underneath the existing hidden imports line in hook-usb.py, cleaned, recompiled and it didnt work.  So i added combined the lines  to just have one hidden import statement:

hiddenimports=['glob','usb.backend.libusb10', 'usb.backend.libusb01', 'usb.backend.openusb']

and repeated the build.  still no luck.  

Do i need to rebuild any eggs or anything to make pyinstaller see my changes to the hook file? 

Is this not finding dlls?  I do see that libusb0.dll gets copied to the dist dir.  Are there others that are needed but not copied?

thanks

**Comment by matysek** [comment]
@jksfiftyfive Could you try the `python3` branch?

PyInstaller does some magic for the `usb` module when your frozen app gets started. You could find it in file `PyInstaller/loader/rthooks/pyi_rth_usb.py`

**Comment by jksfiftyfive** [comment]
Hi Matysek,,

Im sorry, I dont understand what you want me to do with this file?  Is the pyi_rth_usb not usually imported with my build?

thanks

**Comment by matysek** [comment]
> Im sorry, I dont understand what you want me to do with this file? Is the pyi_rth_usb not usually imported with my build?

This file is imported in your build before `import usb` is done. This is file where you might start looking why the libusb0.ddl is not found even when available next to the .exe file.

**Comment by jksfiftyfive** [comment]
I wanted to post this file from pyftdi.  its usbtools.py.  this ends up calling usb/libloader.py.  is the ftdi usbtools "over writing" what the rth_usb hook does to find the dll and backend?

usbtools.py:

    def _find_devices(cls, vps, nocache=False):
        """Find an USB device and return it.
           This code re-implements the usb.core.find() method using a local
           cache to avoid calling several times the underlying LibUSB and the
           system USB calls to enumerate the available USB devices. As these
           calls are time-hungry (about 1 second/call), the enumerated devices
           are cached. It consumes a bit more memory but dramatically improves
           start-up time.
           Hopefully, this kludge is temporary and replaced with a better
           implementation from PyUSB at some point.
        """
        cls.LOCK.acquire()
        try:
            backend = None
            candidates = ('libusb1', 'libusb10', 'libusb0', 'libusb01',
                          'openusb')
            um = __import__('usb.backend', globals(), locals(),
                            candidates, -1)
            for c in candidates:
                try:
                    m = getattr(um, c)
                except AttributeError:
                    continue
                backend = m.get_backend()
                if backend is not None:
                    break
            else:
                raise ValueError('No backend available')
            if not cls.USBDEVICES or nocache:
                # not freed until Python runtime completion
                # enumerate_devices returns a generator, so back up the
                # generated device into a list. To save memory, we only
                # back up the supported devices
                cls.USBDEVICES = []
                devlist = []
                vpdict = {}
                for v, p in vps:
                    vpdict.setdefault(v, [])
                    vpdict[v].append(p)
                for dev in backend.enumerate_devices():
                    device = usb.core.Device(dev, backend)
                    vendor = device.idVendor
                    product = device.idProduct
                    if vendor in vpdict:
                        products = vpdict[vendor]
                        if products and (product not in products):
                            continue
                        devlist.append(device)
                cls.USBDEVICES = devlist
            return cls.USBDEVICES
        finally:
            cls.LOCK.release()

**Comment by matysek** [comment]
> I wanted to post this file from pyftdi. its usbtools.py. this ends up calling usb/libloader.py. is the ftdi usbtools "over writing" what the rth_usb hook does to find the dll and backend?

There might be an issue related to that fact that pyftdi has its own "magic" and does not rely on pysub. Could you try create an app that uses just pyusb? This could confirm it.

**Comment by jksfiftyfive** [comment]
I can try that at some point, but this is part of a production test set and we've got parts coming in within the week, so i cant modify anything at this time, but will attempt the change once we are finished testing

ill report back.  

if you do any testing in the meantime, please let me know

thanks

**Comment by htgoebel** [comment]
@jksfiftyfive Any news on this?

**Comment by htgoebel** [comment]
Got no further info since two months now. Closing.

**Comment by eslavko** [comment]
....Just for info. I got hit to same trouble. Code works as py, and doesn't find usb backend when compiled to exe. No solution yet.

**Comment by tatarize** [comment]
Chrisv's solution in #1891 seems like it got the .dll and properly included it.
