### ISSUE TITLE
libc runtime dynamic linker errors

### ISSUE THREAD

**Issue by akbhat** [pyinstaller/pyinstaller#1450]
https://github.com/pyinstaller/pyinstaller/wiki/FAQ#misc

Will this ever be fixed or the the solution to compile with older version of glibc is final?

Compiled on 
3.2.0-70-generic #105-Ubuntu SMP Wed Sep 24 19:49:16 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Ran into glibc error on
2.6.32-504.1.3.el6.x86_64 #1 SMP Tue Nov 11 17:57:25 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

Error loading Python lib '/tmp/_MEIhUvRwR/libpython2.7.so.1.0': /lib64/libc.so.6: version `GLIBC_2.14' not found (required by /tmp/_MEIhUvRwR/libpython2.7.so.1.0)

**Comment by matysek** [comment]
This will always be an issue and not really related to PyInstaller. I don't know how this could be fixed. If you find a solution, let us know. I haven't found any.

**Comment by akbhat** [comment]
@htgoebel @matysek - Have you guys looked at any of these possible options to pack glibc with the pyisntaller binary atleast for Linux distributions?
http://magicermine.com/
http://statifier.sourceforge.net/

**Comment by lilingyu** [comment]
statifier not working
