### ISSUE TITLE
Remove own BuiltinImporter even for Python 2.x

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1455]
We currently have an implementation of [`BuiltinImporter`](https://github.com/pyinstaller/pyinstaller/blob/python3/PyInstaller/loader/pyimod03_importers.py#L63), which is only used for Python 2.7. Some comment there already asks if we really need it.

According to [PEP 302](https://www.python.org/dev/peps/pep-0302/):

> Currently, this list is empty by default, and frozen and built-in module imports are done after traversing sys.meta_path , but still before sys.path

We are adding the BuiltinImporter to `sys.meta_path` as first element, so the module-search order results in:

| **Python 2.x** | **Python 3.x** |
| --- | --- |
|  | 1. frozen imports by Python |
| 1. BuiltinImporter | 2. built-in import by Python |
| 2. FrozenImporter | 3. FrozenImporter |
| 3. CExtensionImporter | 4. CExtensionImporter |
| 4. frozen imports by Python |  |
| 5. built-in import by Python |  |
| 6. elements on sys.path | 5. elements on sys.path |

Since we are (obviously) not including any built-in modules, removing BuiltinImporter would change the order, modules are searched, but the result should be the same.

**But there is one exception:** Within PyInstaller, the module named `__main__` will not be handled by our BuiltinImporter, but by the Python built-in-loader. And this makes a small difference: Python3 `_frozen_importlib.BuiltinImporter` does not have a `get_data()` method.

**But then again:** When running from python, `__main__` module is loaded by zipimporter (if applicable) or pkgutil.ImpLoader resp. _frozen_importlib.SourceFileLoader. See https://gist.github.com/htgoebel/e06f8b4dc50be3bb0418 for test-scripts.
##### Concluding proposal

I propose to remove our BuiltinImporter and fix PyInstaller to get the correct loader (our FrozenImporter) for `__main__`.

Any objections?

**Comment by htgoebel** [comment]
This blocks #1456.

**Comment by htgoebel** [comment]
As this test did not exist in release 2.1, it's not a blocker for release 3.0. Pushing forward to release 3.1.

**Comment by htgoebel** [comment]
@pyinstaller/core-developers @pyinstaller/issue-contributors Just want to ask if there are any objections on removing our BuiltinImporter.

**Comment by bjones1** [comment]
Not from me. But, I'm not as familiar with this portion of the code.

**Comment by matysek** [comment]
* I'm fine too with removing it if pyinstaller works without it.
* I implemented BuiltinImporter for Python2 and my thinking at that time was that we first need to check if a module is 'built-in' before trying other importers. I did not do any complex analysis. It worked so I kept it that way.

**Comment by bwoodsend** [comment]
This was fixed in 0ab2b4e754c06d21d7cda68e546a7c1c4143cbf5.
