### ISSUE TITLE
PyQt 5.5 bundling don't work correctly

### ISSUE THREAD

**Issue by AcidWeb** [pyinstaller/pyinstaller#1458]
Apparently something changed in PyQt 5.5 as both pyinstaller and py2app can't bundle needed files anymore.

https://gist.githubusercontent.com/AcidWeb/4eabc71ac2114da779de/raw/b0e052a3936905b106c1f241c3851b508f5dc288/gistfile1.txt

Additionally entire process crash with error:
`Security-Alert: try to store file outside of dist-directory. Aborting. '/usr/lib/libc.dylib'`

Tested on OS X 10.10 and 10.8 using Python 3.4 and latest revision of python3 branch.

**Comment by htgoebel** [comment]
Please provide more information, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by AcidWeb** [comment]
I don't really have anything to add. I'm mentioning this issue mostly because py2app also fail similar way with QT 5.5. So it look more like generic error caused by some change in QT/PyQT itself.

When using QT 5.4.* bundle frameworks correctly but pyinstaller crash with Security-Alert. 

I don't use pyinstaller for this project yet so I don't have any tweaked spec file. It is output of bare pyinstaller. I'm quite sure it can be replicated with any code that use QT 5.5.

Complete build log:
https://gist.githubusercontent.com/AcidWeb/ea661c45b4dc7463634d/raw/84997187e12cde6162ba26e21e97a2d734c0a22d/gistfile1.txt

**Comment by AcidWeb** [comment]
Problem occurs only when official binary QT installation is used to compile PyQt.
When QT is compiled thru brew all files are bundled correctly.

So IMHO this is upstream bug and it can be closed.
