### ISSUE TITLE
14 ERROR: You are running PyInstaller as user root. This is not supported

### ISSUE THREAD

**Issue by FinlayDaG33k** [pyinstaller/pyinstaller#1459]
this error showsup when using PyInstaller, yet the only user I have on my system is root (Kali Linux)... how do I solve this without making another user?

**Comment by codewarrior0** [comment]
In `utils/misc.py`, edit the function `check_not_running_as_root()` to return `True`.

**Comment by FinlayDaG33k** [comment]
Did it thanks!
