### ISSUE TITLE
allow attributes 'binaries' and 'datas' in spec file

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1460]
Allowing attributes 'binaries' and 'datas' in spec file will simplify the datafiles recipe and make it much easier for users to supply own data files or binaries.

Syntax of `datas` and 'binaries' would be the same as in import hook files and even glob statements would be allowed.

Snippet of a customized .spec file with datas:
```python
# -*- mode: python -*-
block_cipher = None
my_datas = [('/tmp/KKLLKKKK.txt', 'ddts')]

a = Analysis(['test.py'],
             pathex=[],
             binaries=None,
             datas=my_datas,
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None,
             excludes=None,
             cipher=block_cipher)
...
```

**Comment by htgoebel** [comment]
Good idea!

**Comment by matysek** [comment]
@tallforasmurf This is something you could document in the manual :-)

**Comment by tallforasmurf** [comment]
Question is, will this be exposed also as a command line argument, --datas=path etc? Or only by editing spec?

**Comment by matysek** [comment]
> Question is, will this be exposed also as a command line argument, --datas=path etc? Or only by editing spec?

It could be exposed. I'm not sure about the format for command line arguments because `path` usually conists of two items:
```python
('source/dir/glob/file/*.data', 'target_dir_in_dist')
```
Do you have any suggestion how this could be expressed as cli arguments?

**Comment by matysek** [comment]
@tallforasmurf Related issue for cli arguments is probably #703 .

**Comment by tallforasmurf** [comment]
I knew there was SOME reason this seemed like such a good idea...
