### ISSUE TITLE
manual - document new hook types (Post-create package hooks, In-safe import hook hooks)

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1463]
Pull request #1393 will introduce new hook types (Post-create package hooks, In-safe import hook hooks)

This new hook types should be well documented and as well how to migrate from old-fashionated hooks to any of these types.

**Comment by matysek** [comment]
@htgoebel Not sure if this should go to 3.1 or 3.0.1 milestone?

**Comment by htgoebel** [comment]
IMHO the documentation should be written after the dust has saddled. We'll see when this is done
