### ISSUE TITLE
update changelog / readme / credits.txt for PyInstaller 3.0

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1464]
This is the current changelog in `doc/CHANGES.txt` in `python3` branch:
```
(+ user visible changes, * internal stuff)

Changes since PyInstaller 2.1
-------------------------------
 + Support for Python 3
 + Support only Python 2.7 and 3.3+
 + (Windows) Bootloader is now built with full Unicode support.
 + (OS X) Executables built with PyInstaller under OS X can now be digitally
   signed.
 + (Windows) for 32bit bootloader enable flag LARGEADDRESSAWARE that allows
   to use 4GB of RAM.
 + (OS X) 32bit precompiled bootloader no longer distributed, only 64bit.
 + Allow override PyInstaller default config directory by environment variable
   PYINSTALLER_CONFIG_DIR.
 + Bootloader debug messages 'LOADER: ...' printed to stderr.
 + Option --key to obfuscate the Python bytecode.
 * Use library modulegraph for module dependency analysis.
 * PyInstaller no longer extends sys.path and bundled 3rd-party libraries do not
   interfere with their other versions.
 * Option to exclude Python modules in import hooks. Variable 'excludedimports'
   can be used in import hook files.
 * Option to bundle dynamic libraries in import hooks. Variable 'binaries'
   can be used to do so. PyInstaller then also includes these binaries in to the
   dependency checking for dynamic libraries.
 * Tests migrated to py.test framework.
 * Improved testing infrastructure with continuous integration (Travis - Linux,
   Appveyor - Windows)
```
TODO list:
* ~~reformat the changelog to RestructuredText, use `rst2html` for testing~~
* ~~include `doc/CHANGES.txt into `long_description` for pypi~~
* ~~include `README.rst` into `long_description` for pypi~~
* update `doc/CREDITS.rst` based on merged pull requests for release 3.0.
* *update `doc/CHANGES.txt` from commits/tickets/pull requests*

**Comment by htgoebel** [comment]
What do you think about sorting the changes by importance? For me, the most important user-visible changes are:
- Added support for Python 3.3 and 3.4
- Removed support for Python 2.6 and lower
- Full unicode-support in the bootloader ... list some of the issues solved by this

**Comment by codewarrior0** [comment]
The two big issues solved by the unicode support are only present on Windows:

- Python 2.7 apps can now run from paths with non-ASCII characters
- Python 2.7 `onefile` apps can now run for users whose usernames contain non-ASCII characters

Aside from that, full unicode support was *required* to properly support Python 3, since the Python 3 API is unicode-only in a lot of places.

**Comment by matysek** [comment]
@htgoebel @codewarrior0 could you look at the following pypi page and provide some feedback regarding appearence, formatting and information there?

https://testpypi.python.org/pypi/PyInstaller/3.0.dev5

Final pypi page for 3.0 will look like that. (Still need to update changelog for 3.0) Thanks

**Comment by htgoebel** [comment]
Am 21.09.2015 um 18:51 schrieb Martin Zibricky:
>
> @htgoebel <https://github.com/htgoebel> @codewarrior0
> <https://github.com/codewarrior0> could you look at the following pypi
> page and provide some feedback regarding appearence, formatting and
> information there?
>
> https://testpypi.python.org/pypi/PyInstaller/3.0.dev5
>

Look good for me. Just some remarks:

  * Python version 2.7 / 3.3+. should be *2.7 / 3.3—3.4* as*we are not
    yet supporting Python 3.5*
  * Near the top: In the source "documentation", "website", "code"
    should have a colon on front, too. This will give a definition list
  * Nitpicking: Near the top: "documentation", "website", "code" should
    be upper-case.
  * Maybe rename "Requirements" into "Requirements and Supported Platforms"?
  * Maybe rename "experimental Ports" into "Contributed"?
  * For the "experimental Ports" state that these are contributed and we
    are happy for feed-back and enhancements on these.


-- 
Schönen Gruß
Hartmut Goebel
Dipl.-Informatiker (univ), CISSP, CSSLP
Information Security Management, Security Governance, Secure Software
Development

Goebel Consult, Landshut
http://www.goebel-consult.de

Blog:
http://www.goebel-consult.de/blog/kleiner-erfahrungsbericht-mit-online-ocr-diensten

Kolumne:
http://www.cissp-gefluester.de/2012-04-compliance-bringt-keine-sicherheit

**Comment by matysek** [comment]
@htgoebel I incorporated your suggestions. Thanks for the feedback: https://testpypi.python.org/pypi/PyInstaller/3.0.dev6

**Comment by ThomasWaldmann** [comment]
Note: 3.5 support is there now and also the readme has already been updated accordingly.

**Comment by matysek** [comment]
@htgoebel and @codewarrior0 I finished updating `CHANGES.rst` and `CREDITS.rst`. Please look at it if you would like to append something. Tomorrow I will use these files for the release.

**Comment by htgoebel** [comment]
@matysek: Neither you not me is listed for PyI 3.0. There is no need to hide you light under a bushel. I suggest adding this at the *very* top:

* Martin Zibricky - Core developer and release manager
* Hartmut Goebel - Core developer

**Comment by htgoebel** [comment]
In the changelog I changes some entries into sentences, so it's clear what happened)

**Comment by matysek** [comment]
> Neither you not me is listed for PyI 3.0.

fixed ;-)
