### ISSUE TITLE
scipy linalg import does not work

### ISSUE THREAD

**Issue by Csega** [pyinstaller/pyinstaller#1465]
Hi Guys!

I just found, that when import the following statement:

``` python
from scipy import linalg

print("Done.")
```

It works with Python, PyInstaller generate the exe file for it, but when I try to run the exe, it gives the following error message:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name linalg
test returned -1
```

I'm using Python 3.3.5 (32 bit) on Windows 8.1 (64 bit) with scipy 0.16.0 (official release through pip).

How can I solve this? Please help!

**Comment by matysek** [comment]
Could you try installing scipy from http://www.lfd.uci.edu/~gohlke/pythonlibs/?

**Comment by Csega** [comment]
I tried, but it gives the same... :(

**Comment by htgoebel** [comment]
Please step-by-step follow the instructions in https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly, esp. the `pyi-archiveviewer?-part to see the archive content. There should be a `scipy.linalg` module in the embedded PYZ.

**Comment by Csega** [comment]
I read and followed the steps and I succeeded. The module was missing.

I had success with the following command:
pyinstaller test.py --onedir --log-level=DEBUG --hidden-import=scipy.linalg --hidden-import=scipy.linalg.cython_blas --hidden-import=scipy.linalg.cython_lapack

I tried to formulate this experience in a hook-file, but what I tried to make wasn't successful. I made two hook files,
one with the name hook-scipy.py with the command:

hiddenimports = ['scipy.linalg']

and one hook-scipy.linalg, which contains:

hiddenimports = ['scipy.linalg.cython_blas', 'scipy.linalg.cython_lapack']

But it did not work for me automatically. What do I do wrong?

**Comment by matysek** [comment]
It's weird that `scipy.linalg` is not found even when explicitly imported in your code. It looks like this issue is similar to #1430 . @Csega could you look at it to confirm it is similar?

**Comment by Csega** [comment]
I just read through the thread you mentioned, and yes, it seems similar to me. Additionally, I found an explicit relative import error with h5py. I get the following error message:

```
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "c:\Python33\lib\site-packages\pyinstaller-3.0.dev0-py3.3.egg\PyInstaller\loader\pyimod03_im
porters.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Projektek\Python\pyinstaller\targets\edvis\customfiles\VideoWidget.py", line 25, in <mod
ule>
    from .InternalData import MovieConfig
  File "c:\Python33\lib\site-packages\pyinstaller-3.0.dev0-py3.3.egg\PyInstaller\loader\pyimod03_im
porters.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Projektek\Python\pyinstaller\targets\edvis\customfiles\InternalData.py", line 15, in <mo
dule>
    from .mmf_mgr import *  # For file operations
  File "c:\Python33\lib\site-packages\pyinstaller-3.0.dev0-py3.3.egg\PyInstaller\loader\pyimod03_im
porters.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Projektek\Python\pyinstaller\targets\edvis\customfiles\mmf_mgr.py", line 16, in <module>
    from h5py import *
  File "c:\Python33\lib\site-packages\pyinstaller-3.0.dev0-py3.3.egg\PyInstaller\loader\pyimod03_im
porters.py", line 311, in load_module
    exec(bytecode, module.__dict__)
  File "c:\Python33\lib\site-packages\h5py\__init__.py", line 13, in <module>
    from . import _errors
ImportError: cannot import name _errors
EDVIS returned -1
```

However, I hidden-imported the h5py._errors module, and it is in the list (in --onedir mode):

```
h5py._conv.pyd
h5py._errors.pyd
h5py._objects.pyd
h5py.h5.pyd
h5py.h5a.pyd
h5py.h5d.pyd
h5py.h5ds.pyd
h5py.h5f.pyd
h5py.h5fd.pyd
h5py.h5g.pyd
h5py.h5i.pyd
h5py.h5l.pyd
h5py.h5o.pyd
h5py.h5p.pyd
h5py.h5r.pyd
h5py.h5s.pyd
h5py.h5t.pyd
h5py.h5z.pyd
hdf5.dll
```

**Comment by Csega** [comment]
I can get rid of the error by using the following hidden imports:

--hidden-import=h5py._errors --hidden-import=h5py.defs --hidden-import=h5py.utils --hidden-import=h5py.h5ac --hidden-import=h5py._proxy

**Comment by VeroL** [comment]
i encountered the same runtime error with scipy:
`ImportError: cannot import name linalg`

but adding the hook the `hook-scipy.py` (`hiddenimports = ['scipy.linalg']`) suggested by @Csega was able to solve it.
my PyInstaller\hooks folder already contained the `hook-scipy.linalg.py`, but not `hook-scipy.py`

Using pyinstaller 3.2 , Python 3.5.1 :: Anaconda 4.0.0 (64-bit), win10

I see it's related to this post: https://github.com/pyinstaller/pyinstaller/issues/1919
so i guess it will be fixed in a next version.

**Comment by htgoebel** [comment]
New news in this for more then a year. closing. If you feel this is still an issue with the current release, please open a brand new issue.

**Comment by sariya** [comment]
Python 2.7.15  unix debian flavor  scipy version '0.19.1'.

I get error importing linalg

```
>>> from scipy import linalg
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name linalg

```

sci-py was installed using conda.

**Comment by firnand4** [comment]
try to update your scipy with
`conda update scipy`
