### ISSUE TITLE
Fix security alert when using ctype with an absolute path for the lib

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1466]
This is the ticket for what is described in https://github.com/pyinstaller/pyinstaller/pull/1452#issue-104772547

> But, if I pass a hard-coded path, I get a `SystemExit: Security-Alert: try to store file outside of dist-directory. Aborting. 'c:\\users\\bjones\\appdata\\local\\temp\\pytest-33\\test_ctypes_gen_onedir_cdll_0\\data\\ctypes_dylib\\ctypes_dylib.dll'`.

and https://github.com/pyinstaller/pyinstaller/pull/1452#issuecomment-138097402:

> I assume, the cause is in `depend.utils.resolveCtypesImports()`, where the full path is put into the second element while only the basename should. I assume, this happens in [line 344](https://github.com/pyinstaller/pyinstaller/blob/python3/PyInstaller/depend/utils.py#L344), where a `os.path.basename()` is missing, and the `os.path.join()` a few lines below simply returns the original path.
>
> But when adding the `basename`, you may run into the next problem: The shared lib may not be found below, as only `LD_LIBRARY_PATH` and the ls-cache are searched. So you may need to redesign this whole function to behave differently if an absolute path (`os.path.isabs`) is given. Presumably in this case, the whole search can be skipped and simply return `('/path/to/fixture/ctypes_dylib.so', 'ctypes_dylib.so', 'BINARY')`

**Comment by springermac** [comment]
I've come up with something that may fix this. See #1526

**Comment by adammenges** [comment]
Sweet! I'll give it a go where I'm experiencing this ASAP.

**Comment by htgoebel** [comment]
@adammenges We are *short* before releasing PyInstaller 3.0. Please report your feedback until 2015-10-01 20:00 CET. If it still does not work, I need a minimal example, including *all* required setup, which I can just cut and paste. Otherwise this will not make it into PyInstaller 3.0.

If I don't get feedback, I'll assume it*s fixed.

**Comment by adammenges** [comment]
This looks great, `develop` no longer has a security-alert for me :grinning:
