### ISSUE TITLE
Remove unittests from scipy

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1469]
When looking at [`scipy/__init__.py`](https://github.com/scipy/scipy/blob/master/scipy/__init__.py#L59), I have the impression, that scipy's whole unittest-suite is included. We should exclude it.

**Comment by matysek** [comment]
Does this mean modify `collect_submodules()` to something like this?  
```python
collect_submodules('scipy', exclude=['scipy.tests'])
```

**Comment by htgoebel** [comment]
I did not look into this yet. But I assume, yes.

**Comment by htgoebel** [comment]
It is more complicated: `scipy.test` is `numpy.testing.Tester().test`.

We'd better leave it as it is until somebody reports an issue.
