### ISSUE TITLE
Appveyor tests are waiting on something (times out)

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1480]
The appveyor jobs run out of time:

* The log says that tests finished in 20 minutes but
* the job times out after 40 min.

Pytest is probably waiting on some subprocesses. My gues is that it might be related to `test_interactive.py`.

**Comment by matysek** [comment]
Running all tests on Windows 7 confirms that 'test_interactive.py::test_pyside' keeps pyside window opened even after running the tests. Appveyor probably waits even for the pyside window to exit.

**Comment by matysek** [comment]
https://docs.python.org/3/library/subprocess.html#module-subprocess This tells that subprocess should be killed when timed out but probably it is not the case everywhere.

**Comment by htgoebel** [comment]
Adding a (qt-) timer to the script could be a solution.

**Comment by htgoebel** [comment]
I just pushed https://github.com/pyinstaller/pyinstaller/tree/issue-1480-Appveyor-timeout-out implementing the timer. Let's see if this solves the issue
