### ISSUE TITLE
COPYING.TXT needs attention before 3.0 release

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1481]
"About the PyInstaller Development Team" is perhaps out of date, or at least the embedded date "as of 2013" needs to be changed. Related: the file doc/credits.txt omits at least a couple of names that have been contributing a lot in recent months.

IANAL but the runtime-exception language seems rather loose to me. Perhaps you can find someone who is a lawyer to look at https://www.gnu.org/licenses/gcc-exception.html and redo the exception text.

COPYING.TXT incorporates the full text of the GPL 2.0 -- is it best to incorporate the whole text? or instead to have only a link to the official page, e.g. http://www.gnu.org/licenses/gpl-2.0.html ?

**Comment by htgoebel** [comment]
See also #1499: "Update maintainers on website"

**Comment by matysek** [comment]
@tallforasmurf I updated COPYING.txt and put there  link to gpl license. If you have any idea for new wording of the bootloader exception please go ahead.
