### ISSUE TITLE
Forcing the use of packaged python interpreter

### ISSUE THREAD

**Issue by topiwala** [pyinstaller/pyinstaller#1482]
I've packaged my code in Ubuntu 14.04 LTS, and when the binary is run on a fresh Ubuntu 14.04 LTS, it works fine (It has the same Python interpreter 2.7.6).
However, when run on Fedora 18, which has a different interpreter (2.7.9), it doesn't work (fails on a Popen call that invoked subprocess._execute_child with the message "no such file or directory"

I think this is because it's trying to use the target system's Python interpreter rather than the one that's packaged. Is there any way around this?

**Comment by matysek** [comment]
@topiwala could you try the python3 branch?

**Comment by topiwala** [comment]
My code extensively uses Python 2.x features, and as such will not work with the Python3 interpreter. Moving my codebase to Python3 is a much larger exercise that I'd like to avoid. Is there any relation between the Python3 branch, and the interpreter?

**Comment by codewarrior0** [comment]
The `python3` branch has been compatible with Python 2.7 since sometime this summer. Give it a try!

**Comment by htgoebel** [comment]
@topiwala Does thy python3-branch work for you? If so, please close this ticket.

**Comment by htgoebel** [comment]
Closing since no more details have been given since two months now.
