### ISSUE TITLE
pefile.py using lots of CPU time (appveyor optimization)

### ISSUE THREAD

**Issue by codewarrior0** [pyinstaller/pyinstaller#1484]
I built the `pyi_interact_pyside.py` test script under profiling and got this result:

[Profiler graph](http://i.imgur.com/jiKQByZ.png)

75% of the CPU time is spent in `bindepend.Dependencies` searching for binary dependencies by parsing the export and import tables of PE files using `pefile.py`. A quick look at `pefile.py` revealed a lot of low-hanging fruit - things like RVA ranges for sections are being computed every call when they could be cached. The exports table is only parsed so we can find "forwarded exports", but the entire table is scanned and ExportData objects created for exports we aren't interested in.

Someday it might be worth the time to optimize `pefile.py` a bit.

**Comment by htgoebel** [comment]
Should we aim for solving this in 3.1 already? Feel free to set it as milestone.

**Comment by codewarrior0** [comment]
Nah, it's not that important. It would have a bigger impact on AppVeyor times than it would for any users. If we ever get impatient waiting for AppVeyor to finish, this is where to start.
