### ISSUE TITLE
Remove pyi-build 

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1490]
Per Martin, "Yes, pyi-build should be dropped since it only duplicates the behavior of 'pyinstaller'
command."

**Comment by matysek** [comment]
I already removed it when working on #1489 :-)

**Comment by mpekalski** [comment]
https://pyinstaller.readthedocs.io/en/stable/spec-files.html

is that docs still relevant or not?

**Comment by bwoodsend** [comment]
I take it you mean the line:

https://github.com/pyinstaller/pyinstaller/blob/9e59228aba00ddadc0b7edeace5c07ef2db7b431/doc/spec-files.rst#L621

In which case, you're right, it should have been changed to `pyinstaller foobarzap.spec`.
