### ISSUE TITLE
doc/source/Makefile use of _pyinstaller-options-options 

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1491]
Manual.rst displays all options with one line of code, `.. include:: _pyinstaller-options.tmp` which is certainly a good idea.

However in build_main.py.\_\_add_options() the default values for --distpath and --workpath are set to \_\_init\_\_.py.DEFAULT_DISTPATH and \_\_init\_\_.py.DEFAULT_WORKPATH. Also a good idea.

But  `make html` in the doc/source directory builds _pyinstaller-options.tmp by capturing the output of `pyinstaller --help` with the result that the manual shows, for example, 

     --distpath=DIR Where to put the bundled app (default: /Developer/PYIN STALLERWORK/pyinstaller/doc/source/dist)

Which is probably not correct for most readers... ;-)

It is not clear to me how to preserve both of these good ideas and still get the manual to show something like,

     --distpath=DIR Where to put the bundled app (default: CURRENT DIRECTORY/dist)"

**Comment by matysek** [comment]
What about introducing a "hidden option" like `--doc-formatting' that would be like `--help` but `pyinstaller.py` will print the default values like CURRENT DIRECTORY/dist etc.?

**Comment by htgoebel** [comment]
Indeed "hidden option" seams to be possible:
- with argparse: `help=argparse.SUPPRESS`
- with optparse: `help=optparse.SUPPRESS_HELP`

But help is generated at the same time `--doc-formatting` is evaluated. So changing the help-message to a fixed value as suggested above seams to be the best solution.

**Comment by tallforasmurf** [comment]
I am not sure I understand the plan. Is it:

1. In \_\_main\_\_.\_\_add\_options(), add an option --doc-formatting that would be used only by the doc Make file,

2. with that option use help=optparse.SUPPRESS_HELP so that it will not show up in the normal help display,

3. Around line 85 of \_\_main\_\_.py we have parsed the args, so we may now test `if opts.doc-formatting :` and...

Here I am not clear about how to generate a help display in which the --distpath and --workpath values are static, not the dynamically-set default values created in \_\_main.\_\_add\_options().

I see the OptParse.remove\_option() method, one could remove the --distpath and --workpath options; add new ones with static default values; call parser.print\_help() and exit. That would work, except I wonder if it would change the order of the help display so those options would now come at the end? I could test this -- unless you had a different approach?

Also -- should we make another Issue with the topic, "replace deprecated OptParse with ArgParse" and a target of 3.1?

**Comment by codewarrior0** [comment]
PyInstaller doesn't call `os.chdir` anywhere, so isn't it safe to just change DEFAULT_DISTPATH to a relative path?

**Comment by htgoebel** [comment]
I've implemented my proposed solution in ebefab6e514

**Comment by tallforasmurf** [comment]
that fixes the issue. I put a comment on the commit, but you can close this, with that.
