### ISSUE TITLE
Failed to run packaged GTK3 application on Mac OS

### ISSUE THREAD

**Issue by yniesp** [pyinstaller/pyinstaller#1492]
(process:61069): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed
(process:61069): GLib-GObject-CRITICAL **: g_param_spec_pool_insert: assertion 'pool != NULL' failed
(process:61069): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed
Segmentation fault: 11

This is the output after I run the .app file directly, but I can directly run the python file without any problem. Any help? Thanks!

**Comment by codewarrior0** [comment]
Not enough info. Read this: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

Since you're on OS X, also attach the CrashReporter log for the segmentation fault.

**Comment by yniesp** [comment]
Sorry, please see this crash report:
https://www.dropbox.com/s/o4pgg2m52dfkl69/main_2015-09-15-182538_Stevens-MacBook-Pro-212.crash?dl=0

Platform details:
sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11
BuildVersion:	15A279b
python --version
Python 2.7.10
pyinstaller --version
2.1

**Comment by codewarrior0** [comment]
Version 2.1 is outdated. Could you try the 3.0 prerelease version? `pip install -U --pre pyinstaller`

**Comment by yniesp** [comment]
Thank you for your reply. I still get the similar error from the output:
(process:72905): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed
(process:72905): GLib-GObject-CRITICAL **: g_param_spec_pool_insert: assertion 'pool != NULL' failed
(process:72905): GLib-GObject-CRITICAL **: g_param_spec_pool_lookup: assertion 'pool != NULL' failed
(process:72905): Gtk-CRITICAL **: gtk_settings_get_for_screen: assertion 'GDK_IS_SCREEN (screen)' failed
Segmentation fault: 11

pyi-archive_viewer dist/main.app/Contents/MacOS/main 
output(http://pastebin.com/YbH4tRD9)

warnmain.text
output(http://pastebin.com/cckgqG10)

**Comment by virtuald** [comment]
@yniesp Did you figure this out? I'm hitting the same issue, even with my custom GTK hooks installed (see #1662). I feel like I'm missing a data directory or something...

**Comment by matysek** [comment]
@yniesp or @virtuald any description how to set up the necesary environment and what code snippet?

**Comment by virtuald** [comment]
@matysek I figured this out but forgot to post it, the problem was that `Gtk.init()` wasn't being called. PyGObject calls `Gtk.init` when `gi.overrides.Gtk` is loaded. However, the overrides weren't getting loaded because of the bug mentioned in #1689. 

This bug is fixed with #1689 and #1662.

**Comment by virtuald** [comment]
@matysek if you want to set up an OSX environment to test this sort of thing out, I've created the [Python GTK3 + GStreamer SDK](https://github.com/exaile/python-gtk3-gst-sdk) which allows one to compile the right environment + dependencies on OSX. I haven't put it together in a downloadable binary environment yet.

If you have an appropriate GTK3 environment set up, the [hello world example](http://python-gtk-3-tutorial.readthedocs.org/en/latest/introduction.html) is sufficient to trigger this bug.
