### ISSUE TITLE
Update website for 3.0 release

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1500]
Website pyinstaller.org is outdated and does not contain information about PyInstaller 3.0.

**Comment by matysek** [comment]
@htgoebel Are you going to work on this or should I do that?

**Comment by htgoebel** [comment]
I'll prepare it this morning. So you'll just need to add the sha-2 checksum, `make` and push.

**Comment by htgoebel** [comment]
I prepared this as far as I could. @matysek Please review
- the *maintainers* section
- the *features* section*

and adopt to whatever you think is correct.

**Comment by matysek** [comment]
@htgoebel Thanks! I update the download links and checksums.
