### ISSUE TITLE
wrong python dynlib name on freebsd 10.2?

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#1504]
see PR #1506

**Comment by matysek** [comment]
@ThomasWaldmann Please create a pull  request.

**Comment by ThomasWaldmann** [comment]
first issue #1503 needs to get fixed, otherwise this can't be tested.

**Comment by htgoebel** [comment]
Perhaps we should simply trade `is_freebsd` like `is_unix` here, as the later also searches for `m` and `mu`.

**Comment by ThomasWaldmann** [comment]
@htgoebel i tried just commenting the "elif freebsd" block, but it still did not find the libpython.

freebsd (10.2): libpython3.4m.so.1  <- this is the correct name, but the code does not search for it.

linux: libpython3.4m.so.1.0

I am unsure whether the freebsd version could be just added to the generic "unix" list.

**Comment by ThomasWaldmann** [comment]
note: #1503 is fixed, so this is the last thing to make it work for freebsd (when starting from a pyinstaller git checkout and compiling the bootloader manually).

**Comment by htgoebel** [comment]
@ThomasWaldmann IC, I overlook that. Please submit a pull-request.

**Comment by matysek** [comment]
Closing, it is fixed in #1506
