### ISSUE TITLE
be more helpful when the python dynlib is not found

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#1505]
it currently points out that this is a common issue when the python-dev package is missing on debian/ubuntu.

while that's helpful there, it doesn't help on other platforms at all. more helpful would be:

- to say in which pathes it looked
- to say for which filenames it looked
- to say which code file one must hack to fix this

**Comment by matysek** [comment]
Pull request are welcome.

**Comment by ThomasWaldmann** [comment]
Well, the main point of this issue is still todo, see first post.

**Comment by yyuu** [comment]
Umm. Showing all candidate library paths would be somewhat complicated since the library path is pretty diverse per platform. Showing only candidate _filename_ would be easy, though.

**Comment by yyuu** [comment]
@ThomasWaldmann Pushed another fix as b53eb24975ae35a3a73c573e46ce0dcf84360043. This might be still insufficient to find what is missing on the system, but I believe it'd be clear somehow than before. I'll open another PR later.

**Comment by ThomasWaldmann** [comment]
ah, better. now one at least knows what filename it could not find.
and use it as starting point for own search.
