### ISSUE TITLE
Document using `spec_namespace` in .spec-files.

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1511]
matysek had the great idea of implementing `spec_namespace`. Now this need to be documenting for how to use it on `.spec`-files (if doc is required for this). See `build/buildmain:build()`.

**Comment by matysek** [comment]
* `CONF` is meant for runtime configuration and not for .spec files.
* I would hold on for 3.1 with documenting it. I think it needs some time to settle down.

**Comment by htgoebel** [comment]
@tallforasmurf Oh, yet another one for you :-)

**Comment by tallforasmurf** [comment]
OK... I see https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/config.py and see the nice docstring in it. I am trying to grasp where the user could employ this facility.

I think I see some potential for use by the writer of a new hook, maybe. But no actual use in existing hooks, only in hooks/utils, so no examples to steal from.

"...meant for runtime configuration..."? Does this mean that CONF is bundled and made available by the bootloader? That would be strange but useful -- I could put some key:value in via the .spec file, and read it out in a runtime hook or even in my main script. Is that the idea?

Incidentally -- in a multifile search for `CONF[` I see several keys being used that are not mentioned in the config.py docstring:

* distpath
* binding_redirects
* configdir
* main_script
* spec, specnm, specpath
* warnfile

I would offer to update the docstring myself but I think possibly someone might want to change some of those keys for consistency, e.g. spec_name not specnm ...?

**Comment by matysek** [comment]
* @tallforasmurf By 'runtime configuration' I mean PyInstaller runtime not the frozen exe.
* Go ahead with renaming keys in `CONF` and making them consistent.

**Comment by tallforasmurf** [comment]
OK, one more question: do I document use of CONF in the manual? Is it open for use by hook-writers?
If not for hook-writers -- if only for developers of PyInstaller -- then it probably should not be in the manual, yes?

**Comment by matysek** [comment]
I would not consider CONF being a public stable API. I'd rather not document it at all. @htgoebel Do you need to have CONF documented in manual?

**Comment by htgoebel** [comment]
Hubs, sorry, I was wrong. I did not mean `CONF`, but `spec_namespace`, which defines the namespace available in `.spec`-files. See `build/buildmain:build()`

**Comment by tallforasmurf** [comment]
fixed #d266276f
