### ISSUE TITLE
Hook datas copies directory contents rather than the directory (and contents)

### ISSUE THREAD

**Issue by matham** [pyinstaller/pyinstaller#1513]
Hi,

There seems to have been a lot of recent changes to build_main.py in the pyhton3 branch which broke packaging in kivy. After fixing our abuse of pyinstaller internals (specifically the global `rthooks` seems to have been removed) we are left with one issue which doesn't seem to be due to our misuse.

In our hook we have 
```py
datas = [
    (kivy.kivy_data_dir, 'kivy_install'),
    (kivy.kivy_modules_dir, 'kivy_install'),
]
```

Before, the `kivy.kivy_data_dir` directory itself (and of course its contents) was copied into `kivy_install`. Now, it seems that the contents of `kivy.kivy_data_dir` themselves are directly copied there . Is this intentional?

For reference, here's the whole spec file, although it's referring to kivy code I have not pushed yet:
```py
# -*- mode: python -*-
from kivy.tools.packaging.pyinstaller_hooks import get_hooks
import os
block_cipher = None


a = Analysis(['..\\kivy34\\examples\\demo\\touchtracer\\main.py'],
             pathex=['g:\\Python\\dev3\\TouchApp'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             excludes=None,
             win_no_prefer_redirects=None,
             win_private_assemblies=None,
             cipher=block_cipher, **get_hooks())
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='touchtracer.exe',
          debug=False,
          strip=None,
          upx=True,
          console=True )
coll = COLLECT(exe,  Tree('../kivy34/examples/demo/touchtracer/'), Tree([f for f in os.environ.get('KIVY_SDL2_PATH', '').split(';') if 'bin' in f][0]),
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=True,
               name='touchtracer')
```

Danke!

**Comment by matysek** [comment]
> Before, the kivy.kivy_data_dir directory itself (and of course its contents) was copied into kivy_install. Now, it seems that the contents of kivy.kivy_data_dir themselves are directly copied there . Is this intentional?

Yes, that is intentional. It was changed to allow renaming of the directory you are copying. New manual should cover this. So your fix would be:
```python
datas = [
    (kivy.kivy_data_dir, 'kivy_install'+os.path.basename(kivy.kivy_data_dir)),
    (kivy.kivy_modules_dir, 'kivy_install'+os.path.basename(kivy.kivy_modules_dir)),
]
```

@tallforasmurf Could you confirm that documentation will cover this?

**Comment by htgoebel** [comment]
You want to use `os.path.join`  of course. :-)

**Comment by matham** [comment]
Ok, great. I guess I'll leave it open so the docs could be updated/fixed.

**Comment by matysek** [comment]
@tallforasmurf Could you please add to the manual section `Adding Data Files` append an example that bundles recursively whole content of a directory? e.g.
```python
added_files = [
         ( '/mygame/data', 'data' ),
         ]
```
Then please close this issue. Thanks.

**Comment by tallforasmurf** [comment]
#bcdfe51
