### ISSUE TITLE
FileExistsError is not available in Python 2 (python 2 compatibility)

### ISSUE THREAD

**Issue by glennra** [pyinstaller/pyinstaller#1517]
https://github.com/pyinstaller/pyinstaller/blob/python3/PyInstaller/building/osx.py#L209

**Comment by matysek** [comment]
@glennra you are right. It breaks python 2 compatibility on osx.

**Comment by matysek** [comment]
@glennra I just pushed a fix. Could you try latest dev version?

**Comment by glennra** [comment]
Thanks, that fixes it for me.
