### ISSUE TITLE
Protect branches against force-push or merges not passing CI tests

### ISSUE THREAD

**Issue by codewarrior0** [pyinstaller/pyinstaller#1518]
[Github recently added a new feature](https://help.github.com/articles/about-protected-branches/) that allows a branch to optionally be protected against forced pushes, and/or be protected against merges that don't pass the CI tests. Do you think we should enable this feature?

Settings link (admins only): https://github.com/pyinstaller/pyinstaller/settings/branches/python3

**Comment by matysek** [comment]
I enabled protection for branches `master` and `develop`. `python3` will be merged into develop one day.

I don't think enable protecting against  merges that don't pass CI tests is necessary (At least not yet). But it should be discussed.

**Comment by matysek** [comment]
Closing. Such protection is already enabled.
