### ISSUE TITLE
Using osgeo.osr in single-file mode shows "Failed to get UTF-8 buffer size" message

### ISSUE THREAD

**Issue by giumas** [pyinstaller/pyinstaller#1521]
On Win7 64bit, python 2.7.10 32bit and last `python3` commit (abe435cce27878b7c1738a236722e8f14819aea2), I get the following error message: `Failed to get UTF-8 buffer size (WideCharToMultiByte: The parameter is incorrect.)`

This is a minimal example code that provides that message:

    import osr
    
    osr_inputs = osr.SpatialReference()
    osr_inputs.ImportFromEPSG(4326)
    osr_calc = osr.SpatialReference()
    osr_calc.ImportFromEPSG(54014)
    coordTransform = osr.CoordinateTransformation(osr_inputs, osr_calc)

The `hook-osgeo.ogr.py` that I am using is pretty simple (to collect some auxiliary data):

    from PyInstaller.utils.hooks import collect_data_files
    datas = collect_data_files('osgeo', subdir='data/gdal')

The error message is not present when I create a single-folder application.

I am getting the same error both on classic `cpython` and on `conda` environments.

The message is not there if I run the script or if I use `PyInstaller 2.1` to freeze it.

**Comment by codewarrior0** [comment]
Build your app with `pyinstaller --debug` and post the full output from running the built exe.

**Comment by giumas** [comment]
After having updated at the last f47b910207743bc2fcd7a70d80dd5f48d86cb5e7 commit, the message is disappeared. Cool!

Incidentally, I would have a more general, but related question about the `osgeo` hook, but I believe that is better to open another ticket.

**Comment by codewarrior0** [comment]
> After having updated at the last f47b910 commit, the message is disappeared. Cool!

I had a feeling that's what it was. The debug output isn't needed, then.

Go ahead and open another issue for the `osgeo` hook.
