### ISSUE TITLE
website redirections for manual / downloads

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1529]
Manual contains some old links pointing to old Trac installation. We should fix these urls and set website redirections to github wiki:
* FAQ: http://www.pyinstaller.org/wiki/FAQ -> https://github.com/pyinstaller/pyinstaller/wiki/FAQ
* https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages
* http://www.pyinstaller.org/wiki/Recipe -> https://github.com/pyinstaller/pyinstaller/wiki/Recipes
* All downloads are put to https://github.com/pyinstaller/pyinstaller/releases, website should redirect here for downloads.

**Comment by htgoebel** [comment]
I've just set up redirects for faq, recipes and supported packages.

The old Downloads are linked to sourceforge, so I don't know what to change here.

**Comment by matysek** [comment]
@htgoebel I copied all tarballs from sourceforge to github releases (https://github.com/pyinstaller/pyinstaller/releases) so downloads should go now only to github releases and sourceforge can be dropped.

**Comment by htgoebel** [comment]
@matysek Yes, but we can not put redirects on sourceforge. What do you mean?
(Currently index.html contains a link to the PDF-manual at sourcforge, but this is the only occurrence.)

**Comment by matysek** [comment]
@htgoebel I do not want any redirects to sf.net. What I mean is replace the `Downloads` section by link to https://github.com/pyinstaller/pyinstaller/releases if anyone ever wants to try older releases.

**Comment by htgoebel** [comment]
IMHO the Download section should stay there – even if this is another place we need to update on releases. Whenever I'm searching for some tool-download, I prefer to have it on the main-page. Put feel free to change it yourself. You – of course – have commit-permission there, too.

**Comment by tallforasmurf** [comment]
I've updated these links, commit ea6821a to be pushed shortly.
