### ISSUE TITLE
Rework hooks manipulating __path__ into post-create package hooks.

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1532]
As of today, all these hooks seam to work. But we should check them:
`grep __path__ PyInstaller/hooks/*.py`.
- `hook-win32com` used `__path__` manupulation in PyInstaller 2.1 – now we include all 
- `hook-PyQt4.uic.port_v2` inhibits the import of this very package if Python3 is used. Related are hooks for port_v3 and PyQT5. -> Create a test-case for this kind of stuff
- `wx.lib.pubsub`, see #1530

**Comment by matysek** [comment]
@htgoebel 
* Does the new function `add_package_path` fulfills your requirements for __path__ manipulation?
* Could this issue be closed or anything else to do?

**Comment by htgoebel** [comment]
matysek: This method helps, but the other topics are still open.

**Comment by htgoebel** [comment]
I checke the hooks and there is no hook manipulating `__path__` directly.
