### ISSUE TITLE
Pyinstaller 3.0.6dev produces no executable

### ISSUE THREAD

**Issue by Pixdigit** [pyinstaller/pyinstaller#1540]
While using Pyinstaller 3.0.6dev on Ubuntu studio 14.10 and using the --onedir or --onefile tag in combiniation with --noupx no contents are produced in ./dist/ . Also no errors get returned. Last output is:
`20040 INFO: Appending archive to EXE <insert source path here>/dist/test` (with the <> replaced by the actual path).

**Comment by htgoebel** [comment]
Please run `pyinstaller --clean` to clean PyInstaller cache and remove temporary files before building.

**Comment by Pixdigit** [comment]
Thank you. Now works completely fine. And I am sorry for forgetting to do this even after reading through the before reporting bug page.
