### ISSUE TITLE
RuntimeWarning: Parent module 'pyi_hook' not found while handling absolute import

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1541]
Whenever a hook is executed, I get this error message from within the hook::
```
INFO: Processing hook   hook-encodings.py
.../pyinstaller/PyInstaller/hooks/hook-encodings.py:11: RuntimeWarning: Parent module
'pyi_hook' not found while handling absolute import
  from PyInstaller.utils.hooks import collect_submodules
DEBUG: Collecting submodules for encodings
```

I also get this for other import types, e.g. `Parent module 'pyi_pre_find_module_path' not found while handling absolute import`.

This occurs when the hook is loaded and executed via `importlib_load_source`. I assume, it is related to #1537 and #1538 and caused by changing the working directory.

**Comment by codewarrior0** [comment]
This is because the call to `importlib_load_source` uses a dotted module name for the new module's name:

```
self._module = importlib_load_source('pyi_hook.'+self._name, self._filename)
```

The dotted module name makes the import machinery think there is a package module called `pyi_hook`. It should be enough to change the module name to e.g. `'pyi_hook_`+self._name.

**Comment by matysek** [comment]
Yesterday I implemented a fix for this. I need to do some testing first before pushing.

**Comment by htgoebel** [comment]
Thanks.
