### ISSUE TITLE
appveyor: python 3.5 tests

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1547]
Appveyor recently added python 3.5 to their environment. We should run tests with this Python version too.

**Comment by matysek** [comment]
Python 3.5 test fail at the moment because there are missing some precompiled dependencies, e.g. matplotlib .whl package: https://github.com/matplotlib/matplotlib/issues/5155

Appveyor run: https://ci.appveyor.com/project/matysek/pyinstaller-ewwmo/build/114/job/xapf86wdwjb16c50

**Comment by stephenrauch** [comment]
Thanks to @bjones1 [appveyor tests](https://ci.appveyor.com/project/matysek/pyinstaller) are now passing.  Can this issue be closed?  Or is there still work to do?

**Comment by htgoebel** [comment]
Python 3.5 is active in appveyor for quite some time now. Closing.
