### ISSUE TITLE
Unify hooks into a single file

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1554]
When implementing 250acf24e8 (Restore `fake-site` module) I got terribly hit by a "old" `hook-site.py` which as overwriting my new pre-find_module-hook.

We should think about merging all types of hooks into a single file, containing functions `pre_find_module_path()`, `pre_safe_import_module()` and `hook()`/`post_graph()` (or however this should be called).

There is one problem, though: The "body" of the module is executed already when then hook-file is loaded the first time - in `find_module`. So we need to find a way to re-execute the file as `post_graph`-hook. Otherwise we would need to change the interface of hook-files.

**Comment by matysek** [comment]
I love this idea. It also came to my mind one day.

**Comment by Legorooj** [comment]
Hooks in one file is a very good idea - replace hook files with functions in `hook.py`?

**Comment by bjones1** [comment]
I agree that it's a good idea, but also note that pre-find/pre-safe hooks are very rare. So, changing the interface IMHO would be fine. However, from another perspective, this would have little impact since it's rarely used.
