### ISSUE TITLE
3.0.dev6 is on pypi, but not tagged in the repo

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#1556]

**Comment by matysek** [comment]
I forgot to push tags ( git push --follow-tags ). Thanks for reminder.

**Comment by giumas** [comment]
There is at least 1 missing file ('doc/CHANGES.rst') in the archive loaded in PyPi: https://pypi.python.org/packages/source/P/PyInstaller/PyInstaller-3.0.dev6.tar.gz

This is the stack trace:

    C:\zzz_dev>pip install --pre pyinstaller
    Collecting pyinstaller
      Downloading PyInstaller-3.0.dev6.tar.gz (2.7MB)
        100% |################################| 2.7MB 204kB/s
        Complete output from command python setup.py egg_info:
        Traceback (most recent call last):
          File "<string>", line 20, in <module>
          File "c:\users\xxxxx\appdata\local\temp\pip-build-fkiawx\pyinstaller\setup.py", line 38, in <module>
            read('doc/CHANGES.rst')])
          File "c:\users\xxxxx\appdata\local\temp\pip-build-fkiawx\pyinstaller\setup.py", line 34, in read
            return unicode(codecs.open(filename, encoding='utf-8').read())
          File "C:\Users\xxxxx\AppData\Local\yyy_x86\py2\lib\codecs.py", line 884, in open
            file = __builtin__.open(filename, mode, buffering)
        IOError: [Errno 2] No such file or directory: 'doc/CHANGES.rst'

        ----------------------------------------
    Command "python setup.py egg_info" failed with error code 1 in c:\users\xxxxx\appdata\local\temp\pip-build-fkiawx\pyinstaller

**Comment by matysek** [comment]
Thanks, will do a new prerelease.

**Comment by matysek** [comment]
It is fixed: https://pypi.python.org/pypi/PyInstaller/3.0.dev7

Thanks man.
