### ISSUE TITLE
OSX - recipe when codesign fails with QtWebEngineProcess

### ISSUE THREAD

**Issue by glennra** [pyinstaller/pyinstaller#1559]
codesign fails on a packaged app because <app dir>/QtWebEngineProcess.app/Contents/Info.plist is a symlink to ../../../Resources/QtWebEngineProcess.app/Contents/Info.plist

**Comment by matysek** [comment]
@glennra Do you have any guess why it is happening?
Does it happen for every app or just thoose using QtWebEngine?

**Comment by glennra** [comment]
@matysek This issue is specific to QtWebEngine. QtWebEngineProcess runs in a separate process and in order for it to not create an extra dock icon it is required to be located inside an app bundle with an Info.plist file that has the LSUIElement key set to true. PyInstaller puts the QtWebEngineProcess binary in the correct location `<app_dir>/Contents/MacOS/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess` but the Info.plist file which is supposed to be located at `<app_dir>/Contents/MacOS/QtWebEngineProcess.app/Contents/info.plist` gets put in `<app_dir>/Contents/Resources` and PyInstaller creates a symlink to its correct location. `codesign` fails because of this symlink because it requires the Info.plist to be an actual file.

**Comment by springermac** [comment]
@glennra I can't reproduce this using `codesign -s Test --deep Test.app`. The symlinks are intentional to allow codesigning to work since it fails if there are any non binary files in the `MacOS` folder.

**Comment by glennra** [comment]
@springermac With a minimal test app I can't reproduce it either. This is the error message that I get from attempting to sign a more complex app:

    /path/toMyApp.app: signed bundle with Mach-O thin (i386) [org.qt-project.Qt.QtWebEngineCore]    
    /path/toMyApp.app: the main executable or Info.plist must be a regular file (no symlinks, etc.)
    In subcomponent: /path/to/MyApp.app/Contents/MacOS/QtWebEngineProcess.app

I have worked around it by replacing the symlinked Info.plist with the actual file after PyInstaller has run.

**Comment by matysek** [comment]
> I have worked around it by replacing the symlinked Info.plist with the actual file after PyInstaller has run.

@glennra Is it possible to generalize this workaround and integrate into pyinstaller or is it more like a candidate for a recipe in the wiki?

**Comment by glennra** [comment]
Given that it works for a minimal test app then, for now, it's probably better as a wiki recipe. The way that QtWebEngineProcess is packaged into the app is currently not ideal because it requires a specific bundle identifier (org.qt-project.Qt.QtWebEngineCore) to make it work. I couldn't figure out any other way to do it.

**Comment by springermac** [comment]
@glennra Is the source code for the more complex app available somewhere?

**Comment by glennra** [comment]
@springermac No sorry, it's a proprietry app.

**Comment by Legorooj** [comment]
Can this be closed?
