### ISSUE TITLE
Can not find path ./libwx_osx_cocoau-3.0.0.0.0.dylib

### ISSUE THREAD

**Issue by giumas** [pyinstaller/pyinstaller#1560]
With the last `develop` on Yosemite 10.10.5 and Anaconda python 2.7.10, when freezing a `wxpython`-based application, I get (both single-file and single-folder):

    30980 ERROR: Can not find path ./libwx_osx_cocoau-3.0.0.0.0.dylib (needed by /Users/test/zzz_x86/py2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_misc_.so)
    30985 ERROR: Can not find path ./libwx_osx_cocoau-3.0.0.0.0.dylib (needed by /Users/test/zzz_x86/py2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_controls_.so)
    30990 ERROR: Can not find path ./libwx_osx_cocoau-3.0.0.0.0.dylib (needed by /Users/test/zzz_x86/py2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_windows_.so)
    30995 ERROR: Can not find path ./libwx_osx_cocoau-3.0.0.0.0.dylib (needed by /Users/test/zzz_x86/py2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_gdi_.so)
    31000 ERROR: Can not find path ./libwx_osx_cocoau-3.0.0.0.0.dylib (needed by /Users/test/zzz_x86/py2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_core_.so)
    31003 ERROR: Can not find path ./libwx_osx_cocoau-3.0.0.0.0.dylib (needed by /Users/test/zzz_x86/py2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_grid.so)

The dylib is actually here: `/Users/test/zzz_x86/py2/lib/libwx_osx_cocoau-3.0.0.0.0.dylib`

If I manually copy the dylib in the single-folder, the application works.

**Comment by matysek** [comment]
@giumas Could you verify that this issue is similar to #1514 ?
* It is also related to using directly a 3rd party Python distribution.

**Comment by giumas** [comment]
I believe that is the same issue:

    tests-Mac:_bag test$ otool -L /Users/test/zzz_x86/py2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_misc_.so
    /Users/test/zzz_x86/py2/lib/python2.7/site-packages/wx-3.0-osx_cocoa/wx/_misc_.so:
        /usr/lib/libstdc++.6.dylib (compatibility version 7.0.0, current version 7.4.0)
        @rpath/libwx_osx_cocoau-3.0.0.0.0.dylib (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
        /System/Library/Frameworks/Carbon.framework/Versions/A/Carbon (compatibility version 2.0.0, current version 136.0.0)
        /System/Library/Frameworks/Cocoa.framework/Versions/A/Cocoa (compatibility version 1.0.0, current version 12.0.0)
        /System/Library/Frameworks/AudioToolbox.framework/Versions/A/AudioToolbox (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 111.1.4)
        /System/Library/Frameworks/OpenGL.framework/Versions/A/OpenGL (compatibility version 1.0.0, current version 1.0.0)
        /usr/lib/libgcc_s.1.dylib (compatibility version 1.0.0, current version 1.0.0)
        /System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 476.18.0)   

I have been able to freeze the same application by using vanilla Python (always 2.7.10) and `wxPython` from here: http://downloads.sourceforge.net/wxpython/wxPython3.0-osx-3.0.2.0-cocoa-py2.7.dmg

**Comment by matysek** [comment]
@giumas I'm closing this and follow #1514 for updates.
