### ISSUE TITLE
UPX breaking vcruntime140.dll (64bit)

### ISSUE THREAD

**Issue by AcidWeb** [pyinstaller/pyinstaller#1565]
PyInstaller: 3.0.dev8
Python: 3.5.0 64bit
Platform: Windows-10.0.10240

UPX compression is corrupting vcruntime140.dll.
Both in `onedir` and `onefile` output is affected.
Replacing vcruntime140.dll with not compressed copy fix the issue.

Considering that vcruntime140.dll is one of **core** DLLs in 3.5 release forcing UPX to skip this file would be good idea.

Issue can be replicated using **any** code.
Not tested 32bit version.

**Comment by matysek** [comment]
@AcidWeb What is your upx version?
Could you try to apply different combination of upx options on vcruntime140.dll if you are able to find out the right one?

**Comment by AcidWeb** [comment]
upx 3.91
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43

Not found any option combination that work.

**Comment by youtux** [comment]
Same issue here. I found a workaround: compile it using an x86 Windows (with an x86 version of Python, but I don't know if that matters).

**Comment by hobbsd** [comment]
I get this same problem with Python 3.5.1 32bit on Windows 10 64bit with Pyinstaller 3.0 and upx 3.91w. Using the --noupx switch works.

**Comment by jftuga** [comment]
I would like to confirm hobbsd's results with PyInstaller 3.1.  The --noupx makes the executable work OK.  On my binary, the upx version is only 16% smaller so it is not really that big a deal not to use the --noupx option.

**Comment by SinHouse** [comment]
I have the same issue with anaconda 64 bit: python 3.5.1, Windows 10 64 bit, upx 3.91 and pyinstaller 3.1.1. 

I have also used the --noupx option to solve it.

**Comment by AndCycle** [comment]
got similar issue, but worse,

build env
python 3.5.1 (32bits) 
win10 (x64)

run env
win 7 (32bits)

hit by
C:\tmp>helloworld.exe
```
Error loading Python DLL: C:\Users\user\AppData\Local\Temp\_MEI21802\python35.dl
l (error code 126)

missing vcruntime140.dll
```

**Comment by DevDesignGirl** [comment]
Same behaviour for Windows 10, 64 bit ( Platform: Windows-10-10.0.10586-SP0) 
PyInstaller: 3.2
Python: 3.5.1
UPX 3.91w
NRV data compression library 0.84
UCL data compression library 1.03
zlib data compression library 1.2.3
LZMA SDK version 4.43

without upx everything works fine, with upx getting messagebox on application start, like this:
---------------------------
sind_generator.exe - Bad Image
---------------------------
Программа "C:\Users\myusername\AppData\Local\Temp\_MEI115362\VCRUNTIME140.dll" не предназначена для выполнения в Windows или содержит ошибку. Попробуйте установить программу еще раз с исходного установочного носителя либо обратитесь к системному администратору или поставщику программного обеспечения за поддержкой. Состояние ошибки 0xc000007b.

**Comment by linglung** [comment]
I had the same problem. 
- python 3.5
- pyinstaller 3.2
- build with Windows 10 x64
- with/out upx

Built an exe based on command line, distributed it to run in Windows Server 2012, got trouble.
*Executed with cmd windows

>  \AppData\Local\Temp_MEI**\VCRUNTIME140.dll

* executed with Git bash 

> \AppData\Local\Temp\9\_MEI56282\python35.dll (error code 127)

**Comment by alanyang3** [comment]
I have this same problem. I can't disable UPX in my case because it reduces my binary from 89MB to 27MB.

The executable works as long as vcruntime140.dll is not UPX packed. Is there a workaround to skip UPX packing for vcruntime140.dll?

**Comment by htgoebel** [comment]
I'm closing this ticket, see the followup #2659.

**Comment by zhujunling-nj** [comment]
Modify the building/utils.py, skip execution of upx when file name is vcruntime140.dll

![default](https://user-images.githubusercontent.com/26447863/53395791-b3e20300-39dd-11e9-8e5a-efe40baba7db.PNG)

**Comment by meanpossum** [comment]
UPX compression strips the SHA Digital Signature form vcruntime140.dll so it is no longer seen as valid (AV software?).

**Comment by erickcastrillo** [comment]
> 
> 
> I have the same issue with anaconda 64 bit: python 3.5.1, Windows 10 64 bit, upx 3.91 and pyinstaller 3.1.1.
> 
> I have also used the --noupx option to solve it.

I had the same issue in the past and I found an option to exclude vcruntime140.dll from UPX process by adding --upx-exclude FILE to prevent a binary from being compressed when using upx. This is typically used if upx corrupts certain binaries during compression. FILE is the filename of the binary without path. This option can be used multiple times.

`pyinstaller --upx-exclude=vcruntime140.dll --onefile --windowed get.py`

Soucer: https://pyinstaller.readthedocs.io/en/stable/usage.html#platform-specific-notes

**Comment by trodick** [comment]
Is there a similar option for use in a .spec file? I am working on an open-source project where most of our users aren't going to want to have to mess with adding more command-line options to the build command.

**Comment by hobbsd** [comment]
> 
> 
> Is there a similar option for use in a .spec file? I am working on an open-source project where most of our users aren't going to want to have to mess with adding more command-line options to the build command.

@trodick: add `upx=False` to the `exe = EXE(...)` section.

**Comment by weyou** [comment]
> Is there a similar option for use in a .spec file? I am working on an open-source project where most of our users aren't going to want to have to mess with adding more command-line options to the build command.

@trodick add the following to spec file:
`exe = EXE(... upx=True, upx_exclude="vcruntime140.dll", ...)`

**Comment by a12591771** [comment]
> > I have the same issue with anaconda 64 bit: python 3.5.1, Windows 10 64 bit, upx 3.91 and pyinstaller 3.1.1.
> > I have also used the --noupx option to solve it.
> 
> I had the same issue in the past and I found an option to exclude vcruntime140.dll from UPX process by adding --upx-exclude FILE to prevent a binary from being compressed when using upx. This is typically used if upx corrupts certain binaries during compression. FILE is the filename of the binary without path. This option can be used multiple times.
> 
> `pyinstaller --upx-exclude=vcruntime140.dll --onefile --windowed get.py`
> 
> Soucer: https://pyinstaller.readthedocs.io/en/stable/usage.html#platform-specific-notes

Thank you very much. It's very useful
