### ISSUE TITLE
test_celementtree fails if _xmlplus (PyXML) is installed

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1568]
It fails with `ImportError: No module named xml.etree.cElementTree` on my system. CI passes, but this *could* be a sign for some deeper problem.
Using 896a85e0590 and Python 2.7.

For Python 3 it passes.

**Comment by htgoebel** [comment]
This is caused by `_xmlplus` being installed.

**Comment by htgoebel** [comment]
@matysek I implemented a fix for this - which was interesting regarding what I learned. **But** this package is *dead*. It is not in Debian, it has been removed in my distributions current version and most comments I found say it is dead, not even working with Python 2.6 and was [removed in Python 3.1](https://bugs.python.org/issue11164).

What do you suggest? Some of my ideas:

1. Keep my fix, even if we ave no chance to test it in CI
2. Implement a `pre_safe_import_module/hook-_xmlplus.py` which `raises SystemExit('PyXML and _xmlplus are outdated. Please get rid of it.')`
3. Do nothing, let those having _xmlplus installed solve the problem on their own. (This is a bad idea IMHO)

**Comment by matysek** [comment]
> Implement a pre_safe_import_module/hook-_xmlplus.py which raises SystemExit('PyXML and _xmlplus are outdated. Please get rid of it.')

@htgoebel I vote for this. To inform user. Please add to that hook a TODO with current date and note that it should be removed in a few years.

**Comment by htgoebel** [comment]
Argl, this breaks Ci tests for 2.7 since Travis seams to have xmlplus installed.

**Comment by ryoonc** [comment]
Just to spell it out for others' benefit, since it wasn't immediately obvious to me (and this is the top search result on google), on my machine I found _xmlplus in C:\Python27\Lib\site-packages. From within that directory, I deleted the _xmlplus folder, a PyXML egg, reinstalled pyinstaller, and the runtime messages about cElementTree finally disappeared.
