### ISSUE TITLE
windows - .spec file should not contain 'appname.exe' but just 'appname' - be platform neutral

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1575]
On Windows PyInstaller generates .spec file that contains code with suffix `.exe` in appname. PyInstaller should generate .spec without containing `.exe` suffix.

Spec snippet now
```
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='helloworld.exe',
```
requested
```
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='helloworld',
```

**Comment by matysek** [comment]
@codewarrior0 This should fix the issue with .exe suffix in .spec files in PIL test.

**Comment by htgoebel** [comment]
Huh? I though, windows requires this extension for taking a program as being executable?!

**Comment by matysek** [comment]
Windows requires it but our .spec might not require it and you could build then app from the same .spec  for several OS without any OS specific code.

**Comment by htgoebel** [comment]
Ups, I've only seen the second commit. So I did not recognize you moved the logic somewhere else. Sorry.

But this solution is a good idea IMHO :-)

**Comment by codewarrior0** [comment]
Nice. :+1:
