### ISSUE TITLE
Problem with hiddenimports and hooks

### ISSUE THREAD

**Issue by micmica** [pyinstaller/pyinstaller#1577]
First, sorry for my English I hope you can understand me.
My application works fine from PyCharm, after creating exe with PyInstaller I get "No module name geventwebsocket" so I've added to the hiddenimports- geventwebsocket, and  then I get "No module name server" so I added geventwebsocket.server and so on.. Now I get "Can not import name WebSocketError" which is a class in geventwebsocket.exceptions.. So I tried adding to the hiddenimports geventwebsocket.exceptions,WebSocketError, but It is not working... Please help.Thank you!
P.S. I also tried with hooks but it's not working, do I need to put my hooks to dir where my source code is or?

**Comment by htgoebel** [comment]
Did you read the manual? Is so, please read both https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs carefully and follow the instruction there. Otherwise we are not able to help.

**Comment by micmica** [comment]
I have read it, and I wrote my hook files, and I called pyinstaller --additional-hook-dir=myhook script.spec (I also tried pyinstaller --additional-hook-dir=.myhook script.spec) and I don't know why is not working. 

I want to add all moduls from sqlalchemy like:

from PyInstaller.utils.hooks import collect_submodules, collect_data_files

hiddenimports = (collect_submodules('sqlalchemy.engine') +
                 collect_submodules('sqlalchemy.ext') +
                 collect_submodules('sqlalchemy.sql') +
                 collect_submodules('sqlalchemy.util'))
datas = collect_data_files('sqlalchemy')

I have saved it like hoook-sqlalchemy.py in myhook file 
I am new with this so I belive It is my fault, I will keep looking, but thank you for answering!

**Comment by htgoebel** [comment]
So the next step is to read [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by htgoebel** [comment]
@micmica We need more details, otherwise we can not help you. Please repoen when posting the required info.
