### ISSUE TITLE
Pyinstaller, hook for flask_bootstrap

### ISSUE THREAD

**Issue by micmica** [pyinstaller/pyinstaller#1579]
Hello. I'm new with pyinstaller but I have read manual and really tried to make it work but I guess It's too complicate for me at this moment so I would need a help from people with more experience.
However I have a problem with flask_bootstrap, after adding flask_bootstrap to hiddenimports my error No modul name flask_bootstrap was gone, but now I see that hiddenimports did not helped pyinstaller to get directory from that module, in this case it is template directory with html documents in it.
So, do you have some written hook to recommend that is including directories from module?

Sorry for my English I don't use it a lot.
Thank you in advance, when I get my hook-flask_bootstrap.py work I will post it!

P.S. Can you please tell me do you have under PyInstaller\utils folder named hooks?
I read on manual that if I want to add folder I can use 
from PyInstaller.utils.hooks import collect_data_files, but I was wandering if I should have folder hooks in folder utils? Because that is not the case :/

**Comment by matysek** [comment]
@micmica 
* Hooks are placed in `./PyInstaller/hooks/`
* `PyInstaller/utils/hooks` is only for helper functions
* As an example you could use any file from `PyInstaller/hooks` that contains `collect_data_files`.
* It looks like you need hook like `hook-flask_bootstrap.py`:
```python
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('flask_bootstrap')
```

**Comment by micmica** [comment]
Thank you! :+1:

**Comment by matysek** [comment]
@micmica Could this be closed?
