### ISSUE TITLE
pandas: C extension pandas.lib not included

### ISSUE THREAD

**Issue by jksfiftyfive** [pyinstaller/pyinstaller#1580]
Hi,

Im using python 2.7.9 32 bit python on windows 7.

I tried this with the development version of pyinstaller 

Im getting this error when trying to run my exe.  it seems to build ok, but doesnt execute.  The following message appears:   

ImportError: C extension: lib not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
DataCombinerApp returned -1

I tried running, 'python setup.py build_ext --inplace' without luck.

I have found several suggestions on the web, including

1) downloading VCC compiler for python 2.7 and re-installing pandas with zip/source
2) uninstalling/installing panda using condas
3)installing pandas using pip

still get the error

Any ideas?

thanks

**Comment by jksfiftyfive** [comment]
i should also add that the code works fine.  i dont get the error when running within python 

im only having issues with the executable

**Comment by htgoebel** [comment]
You probably need to create a hook for pandas. See http://pythonhosted.org/PyInstaller/#understanding-pyinstaller-hooks. The description there should still be okay for your case.

**Comment by jksfiftyfive** [comment]
But what file(s) should the hook point to?  looks like its not complaining that it cant find the file, it looks like its complaining that a C extension file isnt built.  

Any ideas?
thanks

**Comment by notgonnacodethat** [comment]
hi i'm experiencing the same problem, got the following error during build (both --onedir and --onefile) and running the .exe

ImportError: C extension: lib not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.


i tried to build with "python setup.py build_ext --inplace --force" as well as using pyinstaller 3.1.dev0, still no luck

**Comment by matysek** [comment]
> But what file(s) should the hook point to? looks like its not complaining that it cant find the file, it looks like its complaining that a C extension file isnt built.
> 
> Any ideas?
> thanks

@jksfiftyfive It looks like pyinstaller does not bundle C extension and pandas thus complains that it was not compiled.
* Question is why do you need to compile anything with pandas yourself when there are prebuilt pandas wheel packages on pypi: https://pypi.python.org/pypi/pandas/
* You still haven't provided enough info for reproducing this issue: https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong, https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by dloman** [comment]
I'm also having this issue trying to use pyinstaller on centos. I don't understand which files I need to add to hook. 

I tried running with the ```--onedir```,  ```--onefile``` and  ```--noupx``` flags

**Comment by dloman** [comment]
fixed this issue on my end.  Pyinstaller wasn't including ``$PYTHONDIR/site-packages/pandas/lib.so``` just copied this into the dist directory and named it pandas.lib.so and it appears to be working. Pyinstaller is awesome keep up the good work!

**Comment by matysek** [comment]
@dloman thanks for debugging

**Comment by rth** [comment]
@matysek  Regarding your earlier comment,
> Question is why do you need to compile anything with pandas yourself when there are prebuilt pandas wheel packages on pypi

I can confirm that the same issue occurs with prebuild pandas package for anaconda on Windows 8.1 (python 2.7). 

Here is a minimal working example:

**test.py**
   
    import pandas as pd

    assert pd.lib.is_float(1) == 0

**Makefile.bat**

    conda create --yes -n test_env pip future nose cython setuptools=18 pywin32 libpython numpy=1.9 scipy=0.15 pandas=0.14 python=2
    call activate test_env
    pip install pyinstaller
    pyinstaller test.py
    call deactivate

The full build output can be found [here](http://pastebin.com/1P4ayNeP) with in particular this error:

    IOError: [Errno 22] invalid mode ('rb') or filename: 'c:\\miniconda\\envs\test_env\\lib\\site-packages\\pandas\\lib.pyd'
which is strange since that file does exist on the system (although in `C:\Miniconda\envs\test_env\Lib\site-packages\pandas` I'm not sure why the path would be in lower case in the logs). 

Great work for the 3.0 release btw!

**Comment by notgonnacodethat** [comment]
@dloman thanks for your answer, works like a charm
for windows, just copy lib.pyd from pandas folder to dist folder and rename it to pandas.lib.pyd

**Comment by tallforasmurf** [comment]
could this be managed with an added binaries item? As described here:
https://pythonhosted.org/PyInstaller/#adding-binary-files

**Comment by notgonnacodethat** [comment]
@tallforasmurf tried modifying the spec file by adding binary / data file, but the "pandas.lib.pyd" file will be automatically placed in "dist/pandas.lib.pyd" folder instead of the root "dist" folder and that doesn't work

anyone know how can I modify in the spec file so that a binary can placed in the same folder as the .exe?

**Comment by dloman** [comment]
I also tried modifying the binaries section of the spec file and that didn't work. I got --onefile version working by first running ```pyinstaller --onefile pandasScript.py``` then going into the build directory and editing ```*Analysis.toc```, ```*COLLECT.toc```, ```*EXE.toc```, and the ```*PKG.toc``` files. In all of those files I searched for the word hashtable and found this line ```('pandas.hashtable', '/usr/local/lib/python2.7/site-packages/pandas/hashtable.so', 'EXTENSION'),```.  I added ```('pandas.lib', '/usr/local/lib/python2.7/site-packages/pandas/lib.so', 'EXTENSION'),``` immeditaly following the hashtable line and then reran ```pyinstaller --onefile pandasScript.py``` and it works. Not sure why adding pandas.lib into the spec file didn’t work but this is an inelegant work around. Hope this helps

**Comment by tallforasmurf** [comment]
@dloman if what you say is true, I think that if the following change to your spec file does not work,

    a = Analysis([' ... script name ... '],
     ...
     binaries= [   (  '/usr/local/lib/python2.7/site-packages/pandas/lib.so', 'pandas.lib' ) ] ,
    ...

...then there must be a bug somewhere. Because that is exactly what the binaries arg is supposed to accomplish.

**Comment by matysek** [comment]
@jksfiftyfive @dloman or @rth could anyone of you confirm that these commits fix this issue?

**Comment by rth** [comment]
@matysek  I can confirm that the above commits fixed the issue for me on Windows 8.1 with Anaconda, (Python 2.7 and 3.4), as well as on Linux (Python 2.7 and 3.4). Thanks!

**Comment by soupault** [comment]
Fixed for me also (Win7, Anaconda, Python 3.4).

**Comment by dloman** [comment]
Fixed for me as well :+1:

**Comment by ProfPh** [comment]
The commits didn't work for me but the latest dev version did fix it!

**Comment by Fuzzwah** [comment]
Latest dev version isn't working for me (Anaconda2-2.4.0-Windows-x86, Pandas 0.17.0, PyInstaller-3.1.dev0-py2.7)

Here's my (very) minimal test.py:

```
import pandas as pd

print(pd.__version__)
```

Super simple spec file (made by c:\Anaconda2\Scripts\pyi-makespec.exe --onefile test.py)
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['test.py'],
             pathex=['C:\\Users\\myuser\\Documents\\Projects\\pandas-test'],
             binaries=None,
             datas=None,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='test',
          debug=False,
          strip=False,
          upx=True,
          console=True )
```

Last bit of the output from the pyinstaller.exe test.spec command:

```
60986 ERROR: C:\Users\myuser\AppData\Roaming\pyinstaller\bincache00_py27_32bit\pandas.lib.pyd
Traceback (most recent call last):
  File "c:\Anaconda2\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.1.dev0', 'console_scripts', 'pyinstaller')()
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\building\build_main.py", line 755, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\building\build_main.py", line 701, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\building\api.py", line 444, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\building\api.py", line 235, in __init__
    self.__postinit__()
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\building\datastruct.py", line 163, in __postinit__
    self.assemble()
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\building\api.py", line 298, in assemble
    dist_nm=inm)
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\building\utils.py", line 254, in checkCache
    res = winmanifest.GetManifestResources(os.path.abspath(cachedfile))
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\utils\win32\winmanifest.py", line 999, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "c:\Anaconda2\lib\site-packages\pyinstaller-3.1.dev0-py2.7.egg\PyInstaller\utils\win32\winresource.py", line 171, in GetResources
    hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
pywintypes.error: (5, 'LoadLibraryEx', 'Access is denied.')
``` 

I'm running the command in a cmd window which has admin rights.

**Comment by joedborg** [comment]
Confirmed the dev version (3.1dev0) is the winner.

**Comment by MajjigaDeepak** [comment]
After including pandas.lib in dist folder & adding in binary in spec file.i executed the app but still same error.Should I do any build after this change?

**Comment by matysek** [comment]
@MajjigaDeepak if you have any issues please create a new report with exact description technical details.
