### ISSUE TITLE
migrate import tests to pytest

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1583]
All tests from `./tests/old_suite/import` should be migrated to `./tests/functional/test_import.py`

**Comment by matysek** [comment]
* I created a repo for running OS X tests on: https://travis-ci.org/pyinstaller/pyinstaller-osx-tests/
* However, I still haven't found out how to automate running OS X tests - notify Travis to run tests when another repository changes. @htgoebel and @codewarrior0 do you have any suggestion?

**Comment by htgoebel** [comment]
Instead of using a separate repo you chould use a separate branch. Or you need to add this repo as another project to travis.

**Comment by codewarrior0** [comment]
Hmm... can't you use `$TRAVIS_OS_NAME` to conditionally run the OS X-specific install stuff only on OS X?

From the [Travis environment variables reference](http://docs.travis-ci.com/user/environment-variables/)

**Comment by matysek** [comment]
I commented about OS X in a wrong ticket. Let's continue in #1448 .
