### ISSUE TITLE
excludedimports in hooks - modules not bundled at all (e.g. FixTk)

### ISSUE THREAD

**Issue by georgemunteanu** [pyinstaller/pyinstaller#1584]
[INPUT]
```python
import Tkinter
import os
from Tkinter import *

# Create Tk instance
root = Tkinter.Tk(className="test")

# Open Notepad
def openNotepad():   
    import pywinauto
    app = pywinauto.Application.start("notepad.exe")
   

# Add menu 
menu = Menu(root)
root.config(menu=menu)
filemenu = Menu(menu)
menu.add_cascade(label="01 File", menu=filemenu)
filemenu.add_command(label="New", command=openNotepad)

# Pack all
root.mainloop()
```

[OUTPUT]
```
when running exe file I will see:
Traceback (most recent call last):
  File "<string>", line 17, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 363, in load_m
odule
    exec(bytecode, module.__dict__)
  File "C:\Python27\lib\lib-tk\Tkinter.py", line 38, in <module>
    import FixTk
ImportError: No module named FixTk
test returned -1
```

NOTE: I am using: python 2.7.10. I am using pyinstaller: 3.0
NOTE: When running the .py everything works as expected.
NOTE: If I remove the openNotepad function than the exe file will not return any error, therefore the app. created with Tkinter works.
NOTE: If I remove the the Tkinter part (thus leaving only the openNotepad) then the exe file open the Notepad.
NOTE: According to docs: https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages, the pywinauto library is supported

That's why please share what I am missing out.
Take care

It is caused by complex implementation of `excludedimports` attribute in hooks. There is proposed a better and simpler implementation for `excludedimports`: https://github.com/pyinstaller/pyinstaller/issues/1553#issuecomment-144934669

**Comment by matysek** [comment]
@georgemunteanu Does any of these workarounds work?
1. use pyinstaller option `--hiddenimport=FixTk`
1. explicitly import only the items you need and not importing all like `from Tkinter import *`

**Comment by georgemunteanu** [comment]
thanks for reply.
1. I've tried: pyinstaller.exe --onefile --windowed --hiddenimport=FixTk C:\automat\test.py. 
The system returns: 
Usage: pyinstaller-script.py [opts] <scriptname> [ <scriptname> ...] | <specfile>
pyinstaller-script.py: error: no such option: --hiddenimport


2. I;ve alter the code so that "from import ...." statement is no longer needed. I got the same result.ImportError: No module named FixTk.


NOTE: In the meantime, I have also added: C:\Python27\lib\lib-tk\ to PATH env. variable. But to no avail.   I will keep investigatiing ...

**Comment by matysek** [comment]
> pyinstaller-script.py: error: no such option: --hiddenimport

Ups. Typo. The option is `--hidden-import` sorry about that.

**Comment by georgemunteanu** [comment]
no biggie. I did pyinstaller.exe --help and I found the correct syntax.

**Comment by georgemunteanu** [comment]
yes yes yes yes. I found the fix:
"
import sys
sys.path.append(r'C:\Python27\lib\lib-tk')
"

I hope this will help others.

**Comment by matysek** [comment]
@georgemunteanu yes, it won't work on other PCs. This just confirms that for some reason, FixTk is not bundled with the executable.
* Does the defualt `--onedir` mode work?
* What other Python packages besides `pywinauto` do you have installed?

**Comment by georgemunteanu** [comment]
Hi,
a) i have tried: --onedir option. Result: works om localhost but not on other env.
b) Apart from default libraries, I have installed: twilio, pyautogui.
NOTE: in the mean time  I added: "import sys; sys.path.append(r'C:\Python27\lib\lib-tk')" in Tkinter.py + FixTk.py. Result:  works om localhost but not on other env.
I will keep digging....

take care

**Comment by matysek** [comment]
@georgemunteanu Could you post here the full debug pyinstaller output you get for your app? Options `--debug --log-level=DEBUG`. For more details see 
* https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong
* https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by georgemunteanu** [comment]
Full build stack is:
========================================
47 INFO: PyInstaller: 3.0
47 INFO: Python: 2.7.10
47 INFO: Platform: Windows-2008ServerR2-6.1.7601-SP1
47 INFO: wrote C:\Users\gmunteanu\test.spec
47 INFO: UPX is not available.
47 INFO: Extending PYTHONPATH with C:\automat
47 INFO: checking Analysis
108 INFO: checking PYZ
140 INFO: checking PKG
171 INFO: Building because C:\Users\gmunteanu\build\test\test.exe.manifest changed
171 INFO: Building PKG (CArchive) out00-PKG.pkg
296 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
5975 INFO: Bootloader C:\Python27\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
5975 INFO: checking EXE
5975 INFO: Building because out00-EXE.toc is bad
5975 INFO: Building EXE from out00-EXE.toc
5975 INFO: Appending archive to EXE C:\Users\gmunteanu\dist\test.exe

C:\Users\gmunteanu>pyinstaller.exe --onefile --windowed C:\automat\test.py
62 INFO: PyInstaller: 3.0
62 INFO: Python: 2.7.10
62 INFO: Platform: Windows-2008ServerR2-6.1.7601-SP1
62 INFO: wrote C:\Users\gmunteanu\test.spec
62 INFO: UPX is not available.
62 INFO: Extending PYTHONPATH with C:\automat
62 INFO: checking Analysis
92 INFO: Building because C:\Python27\lib\lib-tk\Tkinter.py changed
92 INFO: Initializing module dependency graph...
92 INFO: Initializing module graph hooks...
155 INFO: running Analysis out00-Analysis.toc
155 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by C:\Python27\python.exe
249 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0
.30729.1_none_3da38fdebd0e6822.manifest
249 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0
.30729.4940_none_acd19a1fe1da248a.manifest
249 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0
.30729.6161_none_acd388d7e1d8689f.manifest
342 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
342 INFO: Found manifest C:\Windows\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.3
0729.6161_none_08e61857a83bc251.manifest
342 INFO: Searching for file msvcr90.dll
342 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none
_08e61857a83bc251\msvcr90.dll
342 INFO: Searching for file msvcp90.dll
342 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none
_08e61857a83bc251\msvcp90.dll
342 INFO: Searching for file msvcm90.dll
342 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none
_08e61857a83bc251\msvcm90.dll
437 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0
.30729.1_none_3da38fdebd0e6822.manifest
437 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0
.30729.4940_none_acd19a1fe1da248a.manifest
437 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0
.30729.6161_none_acd388d7e1d8689f.manifest
437 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
686 INFO: Analyzing C:\automat\test.py
5319 INFO: Processing pre-find module path hook   distutils
6990 INFO: Looking for import hooks ...
7005 INFO: Processing hook   hook-distutils.py
7005 INFO: Processing hook   hook-xml.py
7082 INFO: Processing hook   hook-PIL.py
7082 INFO: Excluding import 'FixTk'
7082 WARNING:   Removing import 'FixTk'
7082 INFO: Excluding import 'Tkinter'
7082 INFO: Excluding import 'PyQt5'
7082 INFO: Excluding import 'PySide'
7082 INFO: Excluding import 'PyQt4'
7082 INFO: Processing hook   hook-win32com.client.py
7082 INFO: Processing hook   hook-httplib.py
7098 INFO: Processing hook   hook-encodings.py
7582 INFO: Processing hook   hook-_tkinter.py
7801 INFO: checking Tree
7832 INFO: checking Tree
7848 INFO: Processing hook   hook-PIL.Image.py
8207 INFO: Processing hook   hook-pywintypes.py
8378 INFO: Processing hook   hook-xml.sax.py
8378 INFO: Processing hook   hook-PIL.SpiderImagePlugin.py
8378 INFO: Excluded import 'FixTk' not found
8378 INFO: Excluding import 'Tkinter'
8378 INFO: Processing hook   hook-xml.etree.cElementTree.py
8378 INFO: Processing hook   hook-win32com.py
8471 INFO: Processing hook   hook-pythoncom.py
8674 INFO: Looking for ctypes DLLs
8783 WARNING: library Shcore.dll required via ctypes not found
8845 INFO: Analyzing run-time hooks ...
8861 INFO: Including run-time hook 'pyi_rth__tkinter.py'
8861 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
8878 INFO: Looking for dynamic libraries
9282 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.
0.30729.6161_none_a554a30de6a6e582.manifest
9391 INFO: Searching for assembly amd64_Microsoft.VC90.MFC_1fc8b3b9a1e18e3b_9.0.30729.6161_none ...
9391 INFO: Found manifest C:\Windows\WinSxS\Manifests\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.
30729.6161_none_044aad0bab1eb146.manifest
9407 INFO: Searching for file mfc90.dll
9407 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_non
e_044aad0bab1eb146\mfc90.dll
9407 INFO: Searching for file mfc90u.dll
9407 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_non
e_044aad0bab1eb146\mfc90u.dll
9407 INFO: Searching for file mfcm90.dll
9407 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_non
e_044aad0bab1eb146\mfcm90.dll
9407 INFO: Searching for file mfcm90u.dll
9407 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.0.30729.6161_non
e_044aad0bab1eb146\mfcm90u.dll
9486 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.mfc_1fc8b3b9a1e18e3b_9.
0.30729.6161_none_a554a30de6a6e582.manifest
9486 INFO: Adding redirect Microsoft.VC90.MFC version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
11326 INFO: Looking for eggs
11326 INFO: Using Python library C:\Windows\system32\python27.dll
11326 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.MFC', language=None, arch=u'amd64', oldVersion=(9, 0, 21022,
8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9a1e18e3b'), BindingRedirect(name=u'Micr
osoft.VC90.CRT', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729,
 6161), publicKeyToken=u'1fc8b3b9a1e18e3b')]
11342 INFO: Warnings written to C:\Users\gmunteanu\build\test\warntest.txt
11342 INFO: checking PYZ
11358 INFO: Building because C:\Python27\lib\lib-tk\Tkinter.py changed
11358 INFO: Building PYZ (ZlibArchive) C:\Users\gmunteanu\build\test\out00-PYZ.pyz
11701 INFO: checking PKG
11717 INFO: Building because C:\Users\gmunteanu\build\test\out00-PYZ.pyz changed
11717 INFO: Building PKG (CArchive) out00-PKG.pkg
11842 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)
17520 INFO: Bootloader C:\Python27\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
17520 INFO: checking EXE
17520 INFO: Building because out00-EXE.toc is bad
17520 INFO: Building EXE from out00-EXE.toc
17536 INFO: Appending archive to EXE C:\Users\gmunteanu\dist\test.exe
==============================================


I've noticed: 
7082 INFO: Excluding import 'FixTk'
7082 WARNING:   Removing import 'FixTk'
7082 INFO: Excluding import 'Tkinter'

**Comment by matysek** [comment]
> 7082 INFO: Excluding import 'FixTk'
> 7082 WARNING:   Removing import 'FixTk'
> 7082 INFO: Excluding import 'Tkinter

@georgemunteanu This is what I though.

Does it work when you comment out line starting with `excludedimports` in files `\PyInstaller\hooks\hook-PIL.py` and `hook-PIL.SpiderImagePlugin.py`?

**Comment by georgemunteanu** [comment]
yes. it does. 
status: problem solved
thanks a bunch for helping me out.

**Comment by htgoebel** [comment]
As already stated in the first comment above, this is to be solved by https://github.com/pyinstaller/pyinstaller/issues/1553#issuecomment-144934669 which says:
> Rather than attempting to undo previous `ModuleGraph` operations, it's usually better to _not_ do those operations in the first place. Fortunately, preventing imports from happening is pretty simple: just override the existing `ModuleGraph._safe_import_hook()` method with a new `PyiModuleGraph._safe_import_hook()` method implemented as follows:

**Comment by matysek** [comment]
@htgoebel Don't you mind if I work on this?

**Comment by htgoebel** [comment]
I plan working an these hook-issues this weekend. Is this okay for you?

**Comment by matysek** [comment]
@htgoebel give it a try then. I will focus on #1581.

I was thinking about this a little bit:
* It's not that straightforward as it seems.
* The best solution would be to first do #1554:
  * it would allow to keep 
  * it's more work
* One possibility to implement it is to take advantage of `lazyimports`:
  * I was playing with it a little bit: https://github.com/matysek/pyinstaller/commit/b8309f1807cdb37db16101a251084f485f189c7b
  * If you add key to lazyimports `lazyimports['tkinter'] = None` then tkinter is excluded.
  * if you do not add there then it is not.
  * Questions are:
    * How to exclude `tkinter` when it is referenced from any `PIL` module?
    * How to include `tkinter` when it is referenced from another module than `PIL`?
  * My suggestion for implementation is like this:
    * Create additional mapping to modulegraph where you would keep excludedimports like this:
       `{'tkinter': ['PIL', 'pydoc']}`
    * in func `_import_module` you would need access to module name, that is going to import `tkinter`
    * in `_import_module` function `tkinter` is going to be imported then: 
      * if tkinter is going to be imported from any `PIL.*` or `pydoc.*` - keep tkinter in `lazyimports` and do not import it.
      * if tkinter is imported from any other module, remove `tkinter` from self.lazyimports.

**Comment by htgoebel** [comment]
Buh, I had to change the implementation if TOC and Tree first to get the `.toc`-files really pretty printed. This took quite some time.

@matysek My approach would be this: In a hook, "excludedimports" would *not* remove all references to that module, but just the edge from this hook's module to the "excluded" import.

When looking at `_ImportHook.process_excludedimports`, I have the impression this does too much. It is not only removing the connection between the modules, but also completly removes the node (at least in some cases). I'll try to rework this. Stay tuned.

**Comment by htgoebel** [comment]
Buh, this is very tricky:
```
#import PIL, Tkinter, FixTk # fails
#import PIL, FixTk, Tkinter # passes
#import FixTk, Tkinter, PIL # passes
import Tkinter, FixTk, PIL # fails
#import FixTk, PIL # passes
#import Tkinter, PIL # passes
#import PIL, Tkinter # passes
```

**Comment by htgoebel** [comment]
Argl, the error in the original app only shows up on win32, since only there, TKinter import FixTk.
PIL is an optional component of `pywinauto`, thus in the original app imported via that.
