### ISSUE TITLE
PyInstaller GUI  - try library Gooey

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1587]
- PyInstaller does not have a working gui.
- We could try the python library https://pypi.python.org/pypi/Gooey/
- this library should turn CLI app into GUI dialog with all available options
- this liibrary could replace the old Tkinter script `pyinstaller-gui.py`

**Comment by Legorooj** [comment]
I've got a project I did plenty of design for, but never implemented. Would a spec file IDE be helpful? An interactive wizard, syntax highlighting, etc. You could then click the `run` button and it'd run the compilation.

Whatdya think?

**Comment by bjones1** [comment]
I think that would be helpful. However, it should live in a separate package.

**Comment by Legorooj** [comment]
@bjones1 of course another repo. It'll be "seperate" from PyInstaller.

**Comment by Legorooj** [comment]
I'm closing this. I've got a pyinstaller gui, `PyCompile`, which currently supports spec file generation for *most* of the options under final development. I'll let you all know when it's ready to go live. (@bjones1 would you be willing to have a look at it?)

**Comment by bjones1** [comment]
@Legorooj sure.
