### ISSUE TITLE
Old PyQtX._qt hidden import

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#1595]
When building my PyQt4-based application, I get a lot of `13325 WARNING: Hidden import 'PyQT4._qt' not found (probably old hook)` messages. Checking on Python, `import PyQt4._qt` fails. Is this old code that could be removed from the many `hook-PyQt4.*.py` files it appears in?

**Comment by matysek** [comment]
It looks like it is old code. I tried `import PyQt4._qt` on Debian 7 and it is not there. It should be safe to remove it from hooks.

**Comment by bjones1** [comment]
OK. Done per #1602.
