### ISSUE TITLE
PyQt5 is missing from includes unless specified in hidden-import

### ISSUE THREAD

**Issue by soupault** [pyinstaller/pyinstaller#1600]
Here is a simple Qt-based app from the internet - http://pastebin.com/9Ef06GQi .

Using both stable 3.0 and latest 3.1dev I tried to create `--onedir` build. 

The issue is that application fails to start, writing `No module named 'PyQt5'` in the console.

Tried to add direct import like `import PyQt5` in the source file.

Built with `-hidden-import=PyQt5` application starts to work.

**Comment by AcidWeb** [comment]
Windows?

Because PyQT5 hook work correctly on OS X and Linux.

**Comment by soupault** [comment]
Yes, sorry, forgot to mention SW specs:

Windows 7 x64, Python 3.4 (anaconda), Qt5.5, PyQt5.

**Comment by AcidWeb** [comment]
Due to lack of installers (Python 3.5) I not tested QT5 with pyinstaller yet - so can't help.
But I'm 100% sure that hook is working correctly on other OS.

**Comment by htgoebel** [comment]
Sounds like a duplicate to #1584. Please run pyinstaller with `--debug` and post the complete log. Tahnsk.

**Comment by htgoebel** [comment]
@soupault Prior to posting the complete log please try the current development head. I just fixed #1584, so I expect this one to be fixed, too.

**Comment by htgoebel** [comment]
@soupault Any news on this topic?

**Comment by soupault** [comment]
First of all, I updated my workspace to: 

Python 3.4.3, Qt5.5.1, PyQt5, latest git-version of PyInstaller (3.1.dev0+2a2c1a2).

Then I cleaned up some modules (including PyQt4) and tried several build-options.

	pyinstaller --onedir --windowed test_app.py
	pyinstaller --onedir --windowed --hidden-import=PyQt5 test_app.py
	pyinstaller --onedir test_app.py
	pyinstaller --onedir --hidden-import=PyQt5 test_app.py

Result is always the same:
http://dpaste.com/0K9H8R9

I tried also to add 'PyQt4' to 'excludes' and rebuild executable. Here is the output:
http://dpaste.com/1DB7EXW

It seems like something is f*cked up. I cannot reproduce the successful build with my new environment.
In any case, I expect this simple application not to require PyQt4.

**Comment by htgoebel** [comment]
You assume, this is an Qt-problem. So I suggest you stripping down the example app to the bare minimum - esp. throw out this padas-stuff.
Further freeeze using the `--debug` option. Check the output of both PyInstaller and your running application and post it.

**Comment by AcidWeb** [comment]
Can't replicate.

I got same environment and everything is working here.

**Comment by matysek** [comment]
This is similar to #1584.
@soupault try these things:
* comment out lines with `excludedimports` in all hook files or
* try my branch: https://github.com/matysek/pyinstaller/tree/hooks_for_parent_pkgs

**Comment by soupault** [comment]
As suggested by @htgoebel , I had removed `pandas` import (I have no idea how did I miss it).

Executable is created much faster now and finally works. 

Nevertheless, should investigate better into `pandas` hooks as long as `import pandas as pd` is quite typical and recommended codeline. I suppose the issue is related to `pandas` shortcuts to visualize `DataFrame`'s (`df.plot()` instead of traditional `matplotlib` workflow: `plt.subplots` -> `axes.plot(df.a, df.b)` -> `...`). Blacklisting those imports for pandas should do the job.

As mentioned in https://github.com/pydata/pandas/issues/11143 , `pandas` developers aren't planning further development of plotting shortcuts, so the support of `pandas` hook wouldn't be a great deal.
