### ISSUE TITLE
UPX on Windows leads to python27.dll loading error

### ISSUE THREAD

**Issue by olemoign** [pyinstaller/pyinstaller#1603]
Windows 7
Python 2.7.10
Pyinstaller 3 and `develop`
UPX 3.91

Packaging works fine without UPX but using UPX, I get (in onefile and onedir):
`Error loading Python DLL: C:\Users\Olivier\AppData\Local\Temp\_MEI60122\python27.dll (error code 14001)`

**Comment by matysek** [comment]
@olemoign could you play a little bit with different upx options on the python27.dll?
* Currently PyInstaller uses these upx options on windows: `--lzma -q`
* Probably create onedir exe from your app without upx and then just copy there upxed python27.dll there with different upx options?
* Are you able to find out options that works for python27.dll?

**Comment by htgoebel** [comment]
Closing since no more details have been given since a month now.

**Comment by olemoign** [comment]
Really sorry for the silence. I finally found the time to test further. Like described, if I create a onedir exe from my app with upx, I get the error.
If I `upx --lzma -q` the original `python27.dll` and I copy the result file in the app folder, it works. This result file is slightly smaller (few bytes) than the python27.dll obtained when bundling. Are you sure that the python27.dll file is treated like the others when bundling the app ?

When looking at the bundling logs, I'm surprised to see that:
- in onefile, upx execution is mentioned on a number of files, but not trace of python27.dll
- in onedir, no mention of upx execution.
