### ISSUE TITLE
UnicodeDecodeError - collect_data_files does not return filenames as unicode

### ISSUE THREAD

**Issue by HeartUnchange** [pyinstaller/pyinstaller#1604]
all information is here:

    E:\python27\Scripts>pyinstaller.exe --onefile --windowed D:\fuck\dla.py
    65 INFO: PyInstaller: 3.0
    65 INFO: Python: 2.7.10
    65 INFO: Platform: Windows-7-6.1.7601-SP1
    66 INFO: wrote E:\python27\Scripts\dla.spec
    69 INFO: UPX is not available.
    72 INFO: Extending PYTHONPATH with D:\fuck
    72 INFO: checking Analysis
    237 INFO: checking PYZ
    308 INFO: checking PKG
    309 INFO: Building PKG because out00-PKG.toc is non existent
    309 INFO: Building PKG (CArchive) out00-PKG.pkg
    531 WARNING: One binary added with two internal names.
    531 WARNING: ('libsodium.pyd',
     'e:\\python27\\lib\\site-packages\\zmq\\libsodium.pyd',
     'BINARY')
    531 WARNING: was placed previously at
    532 WARNING: ('zmq\\libsodium.pyd',
     'e:\\python27\\lib\\site-packages\\zmq\\libsodium.pyd',
     'BINARY')
    621 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 3072
    9, 6161)
    Traceback (most recent call last):
      File "E:\python27\Scripts\pyinstaller-script.py", line 9, in <module>
        load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
      File "e:\python27\lib\site-packages\PyInstaller\__main__.py", line 99, in run
        run_build(opts, spec_file, pyi_config)
       File "e:\python27\lib\site-packages\PyInstaller\__main__.py", line 47, in run_
     build
         PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
      File "e:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
    737, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
    ))
      File "e:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
    680, in build
        exec(text, spec_namespace)
      File "<string>", line 28, in <module>
      File "e:\python27\lib\site-packages\PyInstaller\building\api.py", line 431, in
     __init__
        strip_binaries=self.strip, upx_binaries=self.upx,
      File "e:\python27\lib\site-packages\PyInstaller\building\api.py", line 233, in
     __init__
        self.__postinit__()
      File "e:\python27\lib\site-packages\PyInstaller\building\datastruct.py", line
    156, in __postinit__
        self.assemble()
      File "e:\python27\lib\site-packages\PyInstaller\building\api.py", line 308, in
     assemble
         archive.build(self.name, mytoc)
       File "e:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 248,
     in build
        self._finalize()
       File "e:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 548,
     in _finalize
        self.save_toc(toc_pos)
      File "e:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 646,
      in save_toc
        tocstr = self.toc.tobinary()
      File "e:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 435,
      in tobinary
         nm = nm.encode('utf-8')
      UnicodeDecodeError: 'ascii' codec can't decode byte 0xbf in position 38: ordinal
     not in range(128)

the source file is 

    import matplotlib.pyplot as plt
    import numpy as np
    data = np.loadtxt(r"D:\fuck\fuck_c++\ConsoleApplication2\ConsoleApplication2\dla_circle.txt")
    for x in xrange(data.shape[0]):
        for y in xrange(data.shape[1]):
            if data[x][y] == 1:
                plt.plot([x,],[y,],"ro",markersize=0.5)
    plt.show()

**Comment by htgoebel** [comment]
There seams to be some filename containing "wrong" (non-ascii) characters. Somewhere PyInstaller is reading a filename which is *not* converted to unicode. So wee need to find out how this happens.

Please post the generated `.spec`-file and search the generated `out00-PKG.toc` file (it it exists, else the other `.toc` files).

**Comment by HeartUnchange** [comment]
i have upload these files here:

https://github.com/HeartUnchange/my-tools/tree/master/pyinstaller_issue

**Comment by htgoebel** [comment]
I can't spot any unusual stuff there. Please warp
```
  File "e:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 435,
  in tobinary
     nm = nm.encode('utf-8')
```

by
```
try:
   nm = nm.encode('utf-8')
except UnicodeDecodeError:
  assert False, repr(nm)
```
This shoud print the offending `nm`.

**Comment by HeartUnchange** [comment]
the result is 

    AssertionError: 'ipython\\qt\\console\\qtconsoleapp.pyw - \xbf\xec\xbd\xdd\xb7\x
    bd\xca\xbd.lnk'

**Comment by HeartUnchange** [comment]
I delete this .lnk and build again.
building is successful.but.the executable is not right.The error infomation is like to [issue#1605](https://github.com/pyinstaller/pyinstaller/issues/1605)

**Comment by HeartUnchange** [comment]
the solution is here:

http://stackoverflow.com/questions/25733467/pyinstaller-no-module-named

**Comment by htgoebel** [comment]
No, this is not the solution for *this* issue, since you removed the link.

**Comment by htgoebel** [comment]
I assume, the reason for *this* issue is that `collect_data_files()` does not return filenames as unicode, but as string. I'll try to write a test-case for this.

**Comment by htgoebel** [comment]
@HeartUnchange  Please try if my test-case fails on your machine:
- Download and unpack https://github.com/htgoebel/pyinstaller/archive/issue-1604-collect_data_files-unicode.zip
```
pip install pytest
python2 -m py.test -k unit
```
should
```
FAIL tests/unit/test_hookutils.py::test_collect_data_all_included[package]
```.

**Comment by HeartUnchange** [comment]
yes the result is 

    tests\unit\test_hookutils.py:220: AssertionError
    =========================== short test summary info ===========================
    FAIL tests/unit/test_hookutils.py::test_collect_data_all_included[package]

**Comment by matysek** [comment]
@HeartUnchange I'm just guessing but does this patch fixes the unicode error?
```diff
diff --git a/PyInstaller/utils/hooks/__init__.py b/PyInstaller/utils/hooks/__init__.py
index 1b9b16b..a38b3c6 100755
--- a/PyInstaller/utils/hooks/__init__.py
+++ b/PyInstaller/utils/hooks/__init__.py
@@ -636,7 +636,7 @@ print(p.__file__)
         attr = exec_statement(__file__statement % package)
         if not attr.strip():
             raise ImportError
-    return attr
+    return unicode(attr)
```

**Comment by codewarrior0** [comment]
The problem here is caused by Python 2's implicit `decode` operation. `str` types are already encoded. When you call `str.encode('UTF-8')`, Python 2 automatically does `str.decode('ASCII').encode('UTF-8')`. The fix is to do something like:

```
if is_py2 and isinstance(nm, str):
   nm = nm.decode(sys.getfilesystemencoding());
nm = nm.encode('utf-8')
```

**Comment by codewarrior0** [comment]
> Somewhere PyInstaller is reading a filename which is not converted to unicode.

On Python 2, all filenames PyInstaller receives are `str` types. Converting all filenames to `unicode` is kind of a big project. I'd have to find every point in the code where PyInstaller gets a filename, and either change it to get the filename using a unicode API (for example, passing a unicode string to `os.listdir` calls the unicode API), or explicitly decode the filename using the filesystem encoding. See also #1222.

**Comment by htgoebel** [comment]
@codewarrior0 Can I give this into your experienced hands?

**Comment by htgoebel** [comment]
This issue is *not* solved.

**Comment by Tryph** [comment]
I have a data directory named "TEST_°caractere". It caused the error described by HeartUnchange. So I tried the patch proposed by codewarrior0, and it worked just fine.
However even if the exe is correclty generated, the application does not run properly. It stop with the following message:
**data\TEST_┬░caractere\Fingerprint-constrate\GC-temperature-1304-245-350021.tif could not be extracted!**
A quick search shows that this message is printed by the bootloader
