### ISSUE TITLE
the executable created by pyinstall return -1

### ISSUE THREAD

**Issue by HeartUnchange** [pyinstaller/pyinstaller#1605]
![1](https://cloud.githubusercontent.com/assets/8402502/10512464/1d81a5ac-7373-11e5-8e8a-327c2ab5f5c8.PNG)

build information is here

    C:\Users\zhx>pyinstaller --windowed --onefile  D:\fuck\pyqt\what.py
    55 INFO: PyInstaller: 3.0
    56 INFO: Python: 2.7.10
    58 INFO: Platform: Windows-7-6.1.7601-SP1
    59 INFO: wrote C:\Users\zhx\what.spec
    62 INFO: UPX is not available.
    65 INFO: Extending PYTHONPATH with D:\fuck\pyqt
    65 INFO: checking Analysis
    65 INFO: Building Analysis because out00-Analysis.toc is non existent
    65 INFO: Initializing module dependency graph...
    72 INFO: Initializing module graph hooks...
    147 INFO: running Analysis out00-Analysis.toc
    151 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
      required by e:\python27\python.exe
    253 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
    c8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
    254 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
    c8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
    256 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
    c8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
    259 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
    c8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
    362 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30
    29.6161_none ...
    362 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc
    b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57.manifest
    365 INFO: Searching for file msvcr90.dll
    365 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
    .0.30729.6161_none_50934f2ebcb7eb57\msvcr90.dll
    366 INFO: Searching for file msvcp90.dll
    368 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
    .0.30729.6161_none_50934f2ebcb7eb57\msvcp90.dll
    368 INFO: Searching for file msvcm90.dll
    369 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_
    .0.30729.6161_none_50934f2ebcb7eb57\msvcm90.dll
    474 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
    c8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
    476 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
    c8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
    479 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
    c8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
    480 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1
    c8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
    481 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0,
    30729, 6161)
    687 INFO: Analyzing D:\fuck\pyqt\what.py
    707 INFO: Looking for import hooks ...
    713 INFO: Processing hook   hook-PyQt4.py
    717 WARNING: Hidden import 'PyQt4._qt' not found (probably old hook)
    717 INFO: Processing hook   hook-encodings.py
    4578 INFO: Processing hook   hook-PyQt4.QtGui.py
    5019 WARNING: Hidden import 'PyQt4._qt' not found (probably old hook)
    5022 INFO: Processing hook   hook-PyQt4.QtCore.py
    5111 WARNING: Hidden import 'PyQT4._qt' not found (probably old hook)
    5111 INFO: Processing hook   hook-httplib.py
    5125 INFO: Looking for ctypes DLLs
    5134 WARNING: library python%s%s required via ctypes not found
    5154 INFO: Analyzing run-time hooks ...
    5160 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
    5172 INFO: Looking for dynamic libraries
    15256 INFO: Looking for eggs
    15256 INFO: Using Python library C:\Windows\system32\python27.dll
    15257 INFO: Found binding redirects:
    [BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVer
    ion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 6161), publicKeyToken=u'1fc8b3b9
    1e18e3b')]
    15267 INFO: Warnings written to C:\Users\zhx\build\what\warnwhat.txt
    15276 INFO: checking PYZ
    15276 INFO: Building PYZ because out00-PYZ.toc is non existent
    15276 INFO: Building PYZ (ZlibArchive) C:\Users\zhx\build\what\out00-PYZ.pyz
    15493 INFO: checking PKG
    15493 INFO: Building PKG because out00-PKG.toc is non existent
    15493 INFO: Building PKG (CArchive) out00-PKG.pkg
    15616 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 3
    729, 6161)
    19174 INFO: Bootloader e:\python27\lib\site-packages\PyInstaller\bootloader\Win
    ows-32bit\runw.exe
    19175 INFO: checking EXE
    19177 INFO: Building EXE because out00-EXE.toc is non existent
    19177 INFO: Building EXE from out00-EXE.toc
    19181 INFO: Appending archive to EXE C:\Users\zhx\dist\what.exe

spec file and toc file have been uploaded to here

https://github.com/HeartUnchange/for_issue/tree/master/pyinstaller/the%20executable%20created%20by%20pyinstall%20return%20-1

**Comment by HeartUnchange** [comment]
I delete the option --windowed ,and I get the error information:

C:\Users\zhx>C:\Users\zhx\dist\dla.exe
Traceback (most recent call last):
  File "<string>", line 6, in <module>
  File "e:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 363, in load_module
    exec(bytecode, module.__dict__)
  File "e:\python27\lib\site-packages\matplotlib\pyplot.py", line 114, in <modul
e>
    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "e:\python27\lib\site-packages\matplotlib\backends\__init__.py", line 32,
 in pylab_setup
    globals(),locals(),[backend_name],0)
  File "e:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 363, in load_module
    exec(bytecode, module.__dict__)
  File "e:\python27\lib\site-packages\matplotlib\backends\backend_tkagg.py", lin
e 7, in <module>
    from matplotlib.externals.six.moves import tkinter_filedialog as FileDialog
  File "e:\python27\lib\site-packages\matplotlib\externals\six.py", line 199, in
 load_module
    mod = mod._resolve()
  File "e:\python27\lib\site-packages\matplotlib\externals\six.py", line 113, in
 _resolve
    return _import_module(self.mod)
  File "e:\python27\lib\site-packages\matplotlib\externals\six.py", line 80, in
_import_module
    __import__(name)
ImportError: No module named FileDialog
dla returned -1

**Comment by HeartUnchange** [comment]
the solution is here:
http://stackoverflow.com/questions/25733467/pyinstaller-no-module-named

**Comment by HeartUnchange** [comment]
in py-file i write these:
    import sip
    sip.setapi('QVariant', 2)
    sip.setapi('QString', 2)

and then the executable show the error information:

    Traceback (most recent call last):
      File "<string>", line 8, in <module>
    ValueError: API 'QVariant' has already been set to version 1

I have found :
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-PyQt4-API-Version

**Comment by JokerQyou** [comment]
Did you find any solution to this? I'm having the same problem here. Nothing but that message box pop up and says 'main returned -1'. I've tried build with the `--debug` flag but the executable still does not log anything.

I'm on Windows 10 with Python 2.7.10 and PyInstaller 3.0.

**Comment by JokerQyou** [comment]
The `sip` related workaround does not work. I'm not doing anything with the API version of PyQt4.

**Comment by HeartUnchange** [comment]
@JokerQyou you can build without the option --windowed so that you can see error information when you run the executable.

**Comment by JokerQyou** [comment]
Thank you for the tip! I have already done that after I replied here, and have found the reason. I've created another issue about this problem, #1607 .
