### ISSUE TITLE
the executable return -1

### ISSUE THREAD

**Issue by HeartUnchange** [pyinstaller/pyinstaller#1610]
i write a application which using PyQt4 ,ctypes and numpysmodules.
the source is [here](https://github.com/HeartUnchange/for_issue/blob/master/pyinstaller/new_bp/bp.py)
and the source file of loaded dll is [here](https://github.com/HeartUnchange/for_issue/blob/master/pyinstaller/new_bp/Source.cpp)

i build the py file to executable successfully.
all buiding information is [here](https://github.com/HeartUnchange/for_issue/tree/master/pyinstaller/new_bp)

but when i run this executable,it throw an error,
   
    Traceback (most recent call last):
    File "<string>", line 78, in <module>
    File "<string>", line 64, in __init__
    File "<string>", line 16, in __init__
    File "<string>", line 24, in load_dll
    File "<string>", line 142, in __init__
    File "e:\python27\lib\ntpath.py", line 208, in basename
      return split(p)[1]
    File "e:\python27\lib\ntpath.py", line 180, in split
      d, p = splitdrive(p)
    File "e:\python27\lib\ntpath.py", line 115, in splitdrive
      if len(p) > 1:
      TypeError: object of type 'NoneType' has no len()
      bp returned -1

but i run the py file directly,it works.

**Comment by matysek** [comment]
@HeartUnchange Please debug your linked app into just a few lines of code that cause this error.

**Comment by HeartUnchange** [comment]
code:
    #!/usr/bin/env python
    #-*- coding:utf-8 -*-

    __author__ = 'Heartunchage'

    import ctypes
    from numpy.ctypeslib import ndpointer

    libHandle = ctypes.windll.kernel32.LoadLibraryA('library.dll')
    lib = ctypes.WinDLL(None, handle=libHandle)
    lib.haha.restype = ndpointer(dtype=ctypes.c_int, shape=(401,401))
    data = lib.haha()
    print data[200,200]
    del lib
    ctypes.windll.kernel32.FreeLibrary(libHandle)

debug information:
D:\fuck\bp>D:\fuck\bp\dist\stu_bp_timer.exe
PyInstaller Bootloader 3.x
LOADER: executable is D:\fuck\bp\dist\stu_bp_timer.exe
LOADER: homepath is D:\fuck\bp\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is D:\fuck\bp\dist\stu_bp_timer.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\zhx\AppData\Local\Temp\_MEI80522
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is D:\fuck\bp\dist\stu_bp_timer.exe
LOADER: homepath is D:\fuck\bp\dist
LOADER: _MEIPASS2 is C:\Users\zhx\AppData\Local\Temp\_MEI80522
LOADER: archivename is D:\fuck\bp\dist\stu_bp_timer.exe
LOADER: SetDllDirectory(C:\Users\zhx\AppData\Local\Temp\_MEI80522)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\zhx\AppData\Local\Temp\_MEI80522\stu_bp_timer.ex
.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\zhx\AppData\Local\Temp\_MEI80522\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\zhx\AppData\Local\Temp\_MEI80522
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename stu_bp_timer.exe.manif
st
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\zhx\AppData\Local\Temp\_MEI80522
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running pyi_rth_win32comgenpy.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running stu_bp_timer.py
Traceback (most recent call last):
  File "<string>", line 10, in <module>
  File "<string>", line 142, in __init__
  File "e:\python27\lib\ntpath.py", line 208, in basename
    return split(p)[1]
  File "e:\python27\lib\ntpath.py", line 180, in split
    d, p = splitdrive(p)
  File "e:\python27\lib\ntpath.py", line 115, in splitdrive
    if len(p) > 1:
TypeError: object of type 'NoneType' has no len()
stu_bp_timer returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for D:\fuck\bp\dist\stu_bp_timer.exe

**Comment by HeartUnchange** [comment]
I have known what is the problem.
in my script, i try to use these codes to unload dll:

    libHandle = ctypes.windll.kernel32.LoadLibraryA('library.dll')
    lib = ctypes.WinDLL(None, handle=libHandle)
    ....
    del lib
    ctypes.windll.kernel32.FreeLibrary(libHandle)

but the variable  lib is initialed with argument <em>None</em>,when pyinstaller build ,it didn't provide a path ,so that it throw an error.

i have found solution for this ,although it is not perfect.
    
    import _ctypes
    lib = ctypes.cdll.LoadLibrary('library.dll')
    libHandle = lib._handle
    ...
   del lib
   _ctypes.FreeLibrary(libHandle)

and it works.
refer to :
http://stackoverflow.com/questions/359498/how-can-i-unload-a-dll-using-ctypes-in-python

**Comment by matysek** [comment]
@HeartUnchange Should be anything fixed in pyinstaller that you reopened the issue?
