### ISSUE TITLE
Empty datas attribute causes PyInstaller to add contents of PyInstaller root directory to data TOC

### ISSUE THREAD

**Issue by springermac** [pyinstaller/pyinstaller#1615]
If the datas attribute of a hook is an empty list PyInstaller will include files from the PyInstaller root directory in the hooks datas object.

Found this when the qt4_menu_nib_dir function didn't find a nib.

**Comment by htgoebel** [comment]
Are you sure about that `datas == []`? Or does `datas` contain an element witch is the empty string (`datas == ['']`).

Looking at `utils.hooks.qt4_menu_nib_dir()`: This returns an empty string in case the qt_menu.nib directory is not found. Thus resulting in an empty string in `datas`.

**Comment by springermac** [comment]
Ah right its when `datas == ['']`.

**Comment by matysek** [comment]
So how should be this fixed?

**Comment by htgoebel** [comment]
1. I suggest to test the result at the place where qt4_menu_nib_dir is used.
2. Maybe it's good idea qt4_menu_nib_dir to return `None` in this case, as this will show up errors more easily (one can not `listdir(None)`

Same for qt5.

Are you going to provide a pull-request?

**Comment by springermac** [comment]
I'm working on some cleanups and fix for the qt functions but this does raise the question again of what should happen if a hook cannot find its needed datas or binaries. Should it print a warning and let PyInstaller continue or print a warning and cause PyInstaller to exit?

**Comment by htgoebel** [comment]
Behavior depends on the hook, I'd say. If the files are known to be required, PyInstaller should raise an error and exit. Otherwise just issue a warning.
