### ISSUE TITLE
Code Style

### ISSUE THREAD

**Issue by springermac** [pyinstaller/pyinstaller#1616]
Does the PyInstaller project have a stated code style?

**Comment by matysek** [comment]
@springermac It does not but it should be formalized. Do you have any suggestion?
Landscape.io reports a lot of style issues: https://landscape.io/github/pyinstaller/pyinstaller

**Comment by springermac** [comment]
I think PEP8 and PEP257 would be good places to start.

**Comment by stephenrauch** [comment]
IMHO, PEP8 ought to be a given.  PEP257, is also great idea, but if docstrings are desired, then the preferred method for specifying parameters and returns codes should also be specified.  PyCharm (my tool of choice) recognizes 5 different formats for inserting docstrings...

@matysek, @htgoebel,

What is the general feeling about PR's that are just formatting changes?  I would be interested in looking at doing some changes that do nothing more than improving landscape.io scores, but these sorts of changes can make merging code from before the changes somewhat painful.  So I would not want to do that if it was too disruptive.

**Comment by htgoebel** [comment]
Short answer while traveling: i don't like this, it makes hunting in the history much more compliated.

**Comment by Legorooj** [comment]
A coding style has now been added to the Dev guide: https://pyinstaller.readthedocs.io/en/stable/development/coding-conventions.html
