### ISSUE TITLE
ctypes dll scan - absolute paths not working

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1620]
This is a followup from #1609. PyInstaller can not handle absolute paths. The absolute path will be there in the frozen app, too, but the dll will not. We are thinking about checking this in scan_code_for_ctypes and fail is an absolute path occurs as the first. element.

How to reproduce this issue: Use `vlc.py` from https://wiki.videolan.org/PythonBinding/ and freeze it. Example output on linux:
```
$ python3 pyinstaller.py --clean vlctest/vlc.py 
102 INFO: PyInstaller: 3.1.dev0+8ae75f0
102 INFO: Python: 3.5.0
103 INFO: Platform: Linux-4.2.3-1-ARCH-x86_64-with-arch
103 INFO: wrote /home/tgc/projects/OpenLP/pyinstaller/vlc/vlc.spec
104 INFO: UPX is not available.
105 INFO: Removing temporary files and cleaning cache in /home/tgc/.local/share/pyinstaller
106 INFO: Extending PYTHONPATH with /home/tgc/projects/OpenLP/pyinstaller/vlctest
106 INFO: checking Analysis
106 INFO: Building Analysis because out00-Analysis.toc is non existent
106 INFO: Initializing module dependency graph...
107 INFO: Initializing module graph hooks...
108 INFO: Analyzing base_library.zip ...
2809 INFO: running Analysis out00-Analysis.toc
2834 INFO: Analyzing /home/tgc/projects/OpenLP/pyinstaller/vlctest/vlc.py
3041 INFO: Looking for import hooks ...
3043 INFO: Processing hook   hook-pydoc.py
3044 INFO: Processing hook   hook-encodings.py
3054 INFO: Processing hook   hook-xml.py
3275 INFO: Processing hook   hook-xml.sax.py
3285 INFO: Looking for ctypes DLLs
3357 WARNING: library libvlc.dll required via ctypes not found
3388 WARNING: library libvlc.dll required via ctypes not found
3420 WARNING: library libvlc.dylib required via ctypes not found
Traceback (most recent call last):
  File "pyinstaller.py", line 15, in <module>
    run()
  File "/home/tgc/projects/OpenLP/pyinstaller/PyInstaller/__main__.py", line 97, in run
    run_build(opts, spec_file, pyi_config)
  File "/home/tgc/projects/OpenLP/pyinstaller/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
  File "/home/tgc/projects/OpenLP/pyinstaller/PyInstaller/building/build_main.py", line 738, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/tgc/projects/OpenLP/pyinstaller/PyInstaller/building/build_main.py", line 681, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/home/tgc/projects/OpenLP/pyinstaller/PyInstaller/building/build_main.py", line 208, in __init__
    self.__postinit__()
  File "/home/tgc/projects/OpenLP/pyinstaller/PyInstaller/building/datastruct.py", line 156, in __postinit__
    self.assemble()
  File "/home/tgc/projects/OpenLP/pyinstaller/PyInstaller/building/build_main.py", line 469, in assemble
    ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
  File "/home/tgc/projects/OpenLP/pyinstaller/PyInstaller/depend/utils.py", line 181, in scan_code_for_ctypes
    elif binary != os.path.basename(binary):
  File "/usr/lib/python3.5/posixpath.py", line 139, in basename
    i = p.rfind(sep) + 1
AttributeError: 'tuple' object has no attribute 'rfind'
```

**Comment by HeartUnchange** [comment]
there is a example on windows,

    #!/usr/bin/env python
    #-*- coding:utf-8 -*-

    import ctypes

    class test_class:
        def __init__(self):
            self.lib = ctypes.CDLL("library.dll")
        def life(self):
            self.lib.love()

    if __name__ == '__main__':
        test = test_class()
        test.life()

the source of library.dll is : 
  
    extern "C"{
        #include <stdio.h>
        int love(){
           printf("I still love the life" );
          return 0;
       }
    }

compile command :

    g++ -c -fPIC test.c -o test.o
    g++ -shared -Wl,-soname,library.dll -o library.dll test.o

the error information is :

    pyinstaller --onefile mini_bp.py
    1500 INFO: PyInstaller: 3.0
    1506 INFO: Python: 2.7.10
    1506 INFO: Platform: Windows-7-6.1.7601-SP1
    1509 INFO: wrote D:\fuck\bp\mini_bp.spec
    1513 INFO: UPX is not available.
    1539 INFO: Extending PYTHONPATH with D:\fuck\bp
    1539 INFO: checking Analysis
    1539 INFO: Building Analysis because out00-Analysis.toc is non existent
    1539 INFO: Initializing module dependency graph...
    1600 INFO: Initializing module graph hooks...
    1888 INFO: running Analysis out00-Analysis.toc
    2029 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
    
      required by e:\python27\python.exe
    35225 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_
    1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
    35242 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_
    1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
    35263 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_
    1fc8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
    35279 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_
    1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
    35398 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.3
    0729.6161_none ...
    35398 INFO: Found manifest C:\Windows\WinSxS\Manifests\x86_microsoft.vc90.crt_1f
    c8b3b9a1e18e3b_9.0.30729.6161_none_50934f2ebcb7eb57.manifest
    35406 INFO: Searching for file msvcr90.dll
    35407 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b
    _9.0.30729.6161_none_50934f2ebcb7eb57\msvcr90.dll
    35409 INFO: Searching for file msvcp90.dll
    35410 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b
    _9.0.30729.6161_none_50934f2ebcb7eb57\msvcp90.dll
    35411 INFO: Searching for file msvcm90.dll
    35414 INFO: Found file C:\Windows\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b
    _9.0.30729.6161_none_50934f2ebcb7eb57\msvcm90.dll
    35539 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_
    1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
    35541 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_
    1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
    35544 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_
    1fc8b3b9a1e18e3b_9.0.30729.4940_none_f47ed0f6f6564d90.manifest
    35545 INFO: Found C:\Windows\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_
    1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
    35546 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0
    , 30729, 6161)
    36271 INFO: Analyzing D:\fuck\bp\mini_bp.py
    41858 INFO: Looking for import hooks ...
    41898 INFO: Processing hook   hook-httplib.py
    41909 INFO: Processing hook   hook-encodings.py
    43457 INFO: Looking for ctypes DLLs
    43488 WARNING: library python%s%s required via ctypes not found
    Traceback (most recent call last):
      File "E:\python27\Scripts\pyinstaller-script.py", line 9, in <module>
        load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
      File "e:\python27\lib\site-packages\PyInstaller\__main__.py", line 99, in run
        run_build(opts, spec_file, pyi_config)
      File "e:\python27\lib\site-packages\PyInstaller\__main__.py", line 47, in run_
    build
        PyInstaller.building.build_main.main(pyi_config, spec_file, **opts.__dict__)
    
      File "e:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
    737, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
    ))
      File "e:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
    680, in build
        exec(text, spec_namespace)
      File "<string>", line 16, in <module>
      File "e:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
    207, in __init__
        self.__postinit__()
      File "e:\python27\lib\site-packages\PyInstaller\building\datastruct.py", line
    156, in __postinit__
        self.assemble()
      File "e:\python27\lib\site-packages\PyInstaller\building\build_main.py", line
    468, in assemble
        ctypes_binaries, ctypes_warnings = scan_code_for_ctypes(co)
      File "e:\python27\lib\site-packages\PyInstaller\depend\utils.py", line 164, in
     scan_code_for_ctypes
        nested_binaries, nested_warnings = scan_code_for_ctypes(c)
      File "e:\python27\lib\site-packages\PyInstaller\depend\utils.py", line 182, in
     scan_code_for_ctypes
        elif binary != os.path.basename(binary):
      File "e:\python27\lib\ntpath.py", line 208, in basename
        return split(p)[1]
      File "e:\python27\lib\ntpath.py", line 180, in split
        d, p = splitdrive(p)
      File "e:\python27\lib\ntpath.py", line 116, in splitdrive
        normp = p.replace(altsep, sep)
    AttributeError: 'tuple' object has no attribute 'replace'

**Comment by HeartUnchange** [comment]
i use the bare filenames but it still failed.so i think the problem is not caused by absolute paths.
this is an example without class:

    #!/usr/bin/env python
    #-*- coding:utf-8 -*-

    __author__ = 'Heartunchange'

    import ctypes

    if __name__ == '__main__':
        lib = ctypes.CDLL("library.dll")
        lib.love()

i use pyinstaller build it successfully.

**Comment by htgoebel** [comment]
This in case by using ctypes in a function or method. In this case, `scan_code_for_ctypes` is calling itself recursively, but the recursed call already returns a tuple.
