### ISSUE TITLE
Appveyor - use pip-accel to speed up environment setup

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1621]
`pip-accel` package might speed up setting up environment for testing on Appveyor.
* now it takes on appveyor about 15 min. to pip-install all dependencies for tests
* most of the time (around 10 min) is taken by compiling `numpy` and `pycrypto`
I tested the speed up on my Win7 VM and I got this times to install all dependencies:
* 1st run: 14 min 19 sec
* 2nd run: 1 min 23 sec

This is the related pull request that adds Windows support to `pip-accel`: https://github.com/paylogic/pip-accel/pull/60

**Comment by htgoebel** [comment]
Mind setting COLOREDLOGS_LOG_FORMAT to get more terse logging of pip-accel.

**Comment by matysek** [comment]
Tests are enabled again and pip-accel caching is doing a good job in setting up the virtualenv in a few minutes.
