### ISSUE TITLE
No handlers could be found for logger "PyInstaller.utils.misc"

### ISSUE THREAD

**Issue by lyuhongley** [pyinstaller/pyinstaller#1622]
1) Enviroment:
OS: redhat linux 7.0
Python: 2.7
when using, No handlers could be found for logger "PyInstaller.utils.misc".

2) Analysing:
I searched the web, and some same errors:
Error message “no handlers could be found for logger ZODB.FileStorage” on copied ZODB database
http://stackoverflow.com/questions/11191398/error-message-no-handlers-could-be-found-for-logger-zodb-filestorage-on-copied
SO, I guess they are the same questions.

3) Solution:
SO, I modified the codes:
PyInstaller-3.0\PyInstaller\utils\misc.py
...
Remark: # from PyInstaller import log as logging
Remark: # Bugfix(No handlers could be found for logger "PyInstaller.utils.misc")
Add: import logging
Add: logging.basicConfig()
...
And, anyway it's OK, ^:)

**Comment by matysek** [comment]
@lyuhongley Could you try latest dev version? It should be fixed there. For details see #1564. Closing as duplicate.
