### ISSUE TITLE
Document adding a new test-case for libraries

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1629]
From https://github.com/pyinstaller/pyinstaller/pull/1614#issuecomment-150847908 and follow-ups:
1. add the package (e.g., `lxml`) to https://github.com/pyinstaller/pyinstaller/blob/develop/tests/requirements.txt#L21 (if yes, why `wxPython` is not present in the list?)
2. Additionally you should add the related apt-package to `.travis.xml`.
3. There are 2 possible approaches:
   - using `pyi_builder.test_script`, add a minimal script that uses the package here: https://github.com/pyinstaller/pyinstaller/tree/develop/tests/functional/scripts and the actual test here: https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/test_libraries.py
   
   or
   - using `pyi_builder.test_source`, directly put the script content in a string
   
   I personally prefer using the later since it keeps the script in the test-code. But if the script is too long, it should be put into a separate file.

Pleas also see: "Use `textwrap.dedent()` in hooks, utils.hook and test-suite" #1531

**Comment by tallforasmurf** [comment]
Sorry, what is needed from me? I am working on the user manual which has nothing about the test environment?

**Comment by htgoebel** [comment]
Oh, I thought I could off-load documenting this, too :-) If you do not consider this as your job, please assign back and I'll create a simple wiki-page.

**Comment by giumas** [comment]
I was wondering if some kind of order could be defined in `test_libraries.py`.. I mean to shuffle the functions to follow (for instance) the alphabetical order of the libraries.

**Comment by htgoebel** [comment]
@giumas This is a good idea.

**Comment by tallforasmurf** [comment]
I could look at it next week but I know zip about the test environment, or testing in general, or how it is documented now (if at all) so it would take a while to get up to speed.

**Comment by Legorooj** [comment]
What's the status of this issue? Safe to close?
