### ISSUE TITLE
openpyxl: data-files missing

### ISSUE THREAD

**Issue by ProfPh** [pyinstaller/pyinstaller#1631]
Working on Windows 10 x64 with Python 3.5

During build I get the api-ms-win-cert dependency errors (I have all the redistributable packages + the SDK) but the build does complete and give me an .exe

The .exe only runs (blinks) to briefly display some error and then closes. Examining the warning logs show:
```
    missing module named resource - imported by posix, C:\Users\User\Documents\Python\123.py
    missing module named posix - imported by os, C:\Users\User\Documents\Python\123.py
    missing module named time.gmtime - imported by time, http.cookies
    missing module named time.time - imported by time, http.cookies
    missing module named _datetime.__doc__ - imported by _datetime, datetime, C:\Users   \User\Documents\Python\123.py
   missing module named _posixsubprocess - imported by subprocess, C:\Users\User\Documents\Python\123.py
```
Even the standard built in modules are not being imported.

**Comment by htgoebel** [comment]
Please follow the instructions in https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs. Otherwise we will not be able to help you.

Whar is this `123.py` module? Why are you importing `posix` there whil running on windows?

**Comment by ProfPh** [comment]
123.py is a test script with only
    print("hello world")

So the modules being imported appear to be independant of the imports in the script being turned to an .exe 

I have tried it with --onefile, --onedir and with --noupx seperately to no avail.

**Comment by htgoebel** [comment]
Need more info: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by ProfPh** [comment]
I did start with a clean installation. I did clear cache.The program is getting packaged fine (except the dependency errors). Some module is definitely missing, yes. There is no logdict.log file. The warning logs show the missing modules as posted above. The error occurs when running the application. PyInstaller 3.0. Python 3.5. Windows. Can't use pyi-archive_viewer, it gives the error "failed to create process" in cmd

**Comment by codewarrior0** [comment]
> The .exe only runs (blinks) to briefly display some error and then closes. 

Instead of double-clicking on it, run the .exe from a command window so you can see its output. If you build the exe with `--debug` you will get even more output. Post the output here when you get it.

**Comment by ProfPh** [comment]
Running debug:


C:\Users\User\Documents\Python>python -m PyInstaller --debug test.py
62 INFO: PyInstaller: 3.0
62 INFO: Python: 3.5.0
62 INFO: Platform: Windows-10.0.10240
62 INFO: wrote C:\Users\User\Documents\Python\test.spec
62 INFO: UPX is not available.
62 INFO: Extending PYTHONPATH with C:\Users\User\Documents\Python
62 INFO: checking Analysis
78 INFO: checking PYZ
78 INFO: checking PKG
78 INFO: Building because toc changed
78 INFO: Building PKG (CArchive) out00-PKG.pkg
109 INFO: Bootloader C:\Python35\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run_d.exe
109 INFO: checking EXE
109 INFO: Building because out00-EXE.toc is bad
109 INFO: Building EXE from out00-EXE.toc
156 INFO: Appending archive to EXE C:\Users\User\Documents\Python\build\test\test.exe
171 INFO: checking COLLECT
171 INFO: Building COLLECT because out00-COLLECT.toc is non existent
171 INFO: Building COLLECT out00-COLLECT.toc

C:\Users\User\Documents\Python>cd dist

C:\Users\User\Documents\Python\dist>cd test

C:\Users\User\Documents\Python\dist\test>test.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\User\Documents\Python\dist\test\test.exe
LOADER: homepath is C:\Users\User\Documents\Python\dist\test
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\User\Documents\Python\dist\test\test.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\Users\User\Documents\Python\dist\test)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\Users\User\Documents\Python\dist\test\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Users\User\Documents\Python\dist\test\base_library.zip;C:\Users\User\Documents\Python\dist\test
LOADER: sys.prefix is C:\Users\User\Documents\Python\dist\test
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\User\Documents\Python\dist\test\base_library.zip;C:\Users\User\Documents\Python\dist\test
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running test.py
hello
LOADER: OK.
LOADER: Cleaning up Python interpreter.


For a one line script with just print("hello world") the warning log is:

missing module named resource - imported by posix, C:\Users\User\Documents\Python\test.py
missing module named posix - imported by os, C:\Users\User\Documents\Python\test.py
missing module named _posixsubprocess - imported by subprocess, C:\Users\User\Documents\Python\test.py
missing module named _datetime.__doc__ - imported by _datetime, datetime, C:\Users\User\Documents\Python\test.py
missing module named unicodedata.ucd_3_2_0 - imported by unicodedata, stringprep, encodings.idna, C:\Users\User\Documents\Python\test.py
missing module named re.compile - imported by re, _strptime, C:\Users\User\Documents\Python\test.py
missing module named re.IGNORECASE - imported by re, _strptime, C:\Users\User\Documents\Python\test.py
missing module named re.escape - imported by re, _strptime, C:\Users\User\Documents\Python\test.py
missing module named _sre.MAXGROUPS - imported by _sre, sre_constants, C:\Users\User\Documents\Python\test.py
missing module named _sre.MAXREPEAT - imported by _sre, sre_constants, C:\Users\User\Documents\Python\test.py
missing module named sre_constants.SUBPATTERN - imported by sre_constants, re, C:\Users\User\Documents\Python\test.py
missing module named sre_constants.BRANCH - imported by sre_constants, re, C:\Users\User\Documents\Python\test.py
missing module named _operator.__doc__ - imported by _operator, operator, C:\Users\User\Documents\Python\test.py
missing module named collections.ChainMap - imported by collections, string, C:\Users\User\Documents\Python\test.py
missing module named _heapq._heapreplace_max - imported by _heapq, heapq, C:\Users\User\Documents\Python\test.py
missing module named _heapq._heapify_max - imported by _heapq, heapq, C:\Users\User\Documents\Python\test.py
missing module named _heapq._heappop_max - imported by _heapq, heapq, C:\Users\User\Documents\Python\test.py
missing module named heapq.nlargest - imported by heapq, difflib, C:\Users\User\Documents\Python\test.py
missing module named inspect.CO_GENERATOR - imported by inspect, bdb, C:\Users\User\Documents\Python\test.py
missing module named _opcode.stack_effect - imported by _opcode, opcode, C:\Users\User\Documents\Python\test.py
missing module named readline - imported by cmd, code, pdb, C:\Users\User\Documents\Python\test.py
missing module named _imp.acquire_lock - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp.init_frozen - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp.is_frozen - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp.get_frozen_object - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp._fix_co_filename - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp.lock_held - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp.is_frozen_package - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp.is_builtin - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp.release_lock - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
missing module named _imp.create_dynamic - imported by _imp, imp, C:\Users\User\Documents\Python\test.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\Users\User\Documents\Python\test.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\Users\User\Documents\Python\test.py
missing module named zipimport.zipimporter - imported by zipimport, pkgutil, C:\Users\User\Documents\Python\test.py
missing module named win32api.RegQueryValueEx - imported by win32api, platform, C:\Users\User\Documents\Python\test.py
missing module named win32api.RegCloseKey - imported by win32api, platform, C:\Users\User\Documents\Python\test.py
missing module named win32api.RegOpenKeyEx - imported by win32api, platform, C:\Users\User\Documents\Python\test.py
missing module named win32api.GetVersionEx - imported by win32api, platform, C:\Users\User\Documents\Python\test.py
missing module named win32con.VER_NT_WORKSTATION - imported by win32con, platform, C:\Users\User\Documents\Python\test.py
missing module named _scproxy._get_proxy_settings - imported by _scproxy, urllib.request
missing module named _scproxy._get_proxies - imported by _scproxy, urllib.request
missing module named _scproxy - imported by urllib.request
missing module named 'org.python'.imp - imported by 'org.python', xml.sax
missing module named 'org.python' - imported by xml.sax
missing module named 'java.lang'.Exception - imported by 'java.lang', xml.sax._exceptions
missing module named xml.parsers.expat.ParserCreate - imported by xml.parsers.expat, plistlib, C:\Users\User\Documents\Python\test.py
missing module named java - imported by platform, C:\Users\User\Documents\Python\test.py
missing module named java.System - imported by java, platform, C:\Users\User\Documents\Python\test.py
missing module named 'java.lang' - imported by platform, C:\Users\User\Documents\Python\test.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, C:\Users\User\Documents\Python\test.py
missing module named termios - imported by tty, C:\Users\User\Documents\Python\test.py, getpass
missing module named _ssl.OPENSSL_VERSION - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.OPENSSL_VERSION_NUMBER - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.OPENSSL_VERSION_INFO - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.MemoryBIO - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl._SSLContext - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.SSLWantWriteError - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.SSLWantReadError - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.SSLError - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.SSLEOFError - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.SSLSyscallError - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.SSLZeroReturnError - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.CERT_NONE - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.CERT_REQUIRED - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.CERT_OPTIONAL - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.nid2obj - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.txt2obj - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.RAND_pseudo_bytes - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.RAND_bytes - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.RAND_add - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.RAND_status - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.RAND_egd - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.HAS_ALPN - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.HAS_NPN - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.HAS_ECDH - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.HAS_SNI - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl._OPENSSL_API_VERSION - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.enum_crls - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named _ssl.enum_certificates - imported by _ssl, ssl, C:\Users\User\Documents\Python\test.py
missing module named time.strptime - imported by time, ssl, C:\Users\User\Documents\Python\test.py
missing module named _hashlib.pbkdf2_hmac - imported by _hashlib, hashlib, C:\Users\User\Documents\Python\test.py
missing module named hashlib.sha512 - imported by hashlib, random, C:\Users\User\Documents\Python\test.py
missing module named _bz2.BZ2Compressor - imported by _bz2, bz2, C:\Users\User\Documents\Python\test.py
missing module named _bz2.BZ2Decompressor - imported by _bz2, bz2, C:\Users\User\Documents\Python\test.py
missing module named _lzma._encode_filter_properties - imported by _lzma, lzma, C:\Users\User\Documents\Python\test.py
missing module named _lzma._decode_filter_properties - imported by _lzma, lzma, C:\Users\User\Documents\Python\test.py
missing module named grp - imported by tarfile, shutil, C:\Users\User\Documents\Python\test.py
missing module named grp.getgrnam - imported by grp, shutil, C:\Users\User\Documents\Python\test.py
missing module named binascii.a2b_qp - imported by binascii, quopri, C:\Users\User\Documents\Python\test.py
missing module named binascii.b2a_qp - imported by binascii, quopri, C:\Users\User\Documents\Python\test.py
missing module named binascii.a2b_base64 - imported by binascii, email.base64mime, C:\Users\User\Documents\Python\test.py
missing module named binascii.b2a_base64 - imported by binascii, email.base64mime, C:\Users\User\Documents\Python\test.py
missing module named socket.SOCK_STREAM - imported by socket, ssl, C:\Users\User\Documents\Python\test.py
missing module named socket.AF_INET - imported by socket, ssl, C:\Users\User\Documents\Python\test.py
missing module named socket.SOL_SOCKET - imported by socket, ssl, C:\Users\User\Documents\Python\test.py
missing module named socket.SO_TYPE - imported by socket, ssl, C:\Users\User\Documents\Python\test.py
missing module named builtins.abs - imported by builtins, operator, C:\Users\User\Documents\Python\test.py
missing module named builtins.str - imported by builtins, locale, C:\Users\User\Documents\Python\test.py
missing module named _functools.reduce - imported by _functools, functools, C:\Users\User\Documents\Python\test.py
missing module named functools.partial - imported by functools, operator, email.charset, C:\Users\User\Documents\Python\test.py
missing module named functools.singledispatch - imported by functools, pkgutil, C:\Users\User\Documents\Python\test.py
missing module named _functools.cmp_to_key - imported by _functools, functools, C:\Users\User\Documents\Python\test.py
missing module named _functools.partial - imported by _functools, functools, C:\Users\User\Documents\Python\test.py
missing module named _functools._lru_cache_wrapper - imported by _functools, functools, C:\Users\User\Documents\Python\test.py
missing module named posix._exit - imported by posix, os, C:\Users\User\Documents\Python\test.py
missing module named pwd.getpwnam - imported by pwd, shutil, C:\Users\User\Documents\Python\test.py
missing module named pwd - imported by posixpath, tarfile, shutil, http.server, webbrowser, C:\Users\User\Documents\Python\test.py, netrc, getpass
missing module named posix._have_functions - imported by posix, os, C:\Users\User\Documents\Python\test.py
missing module named nt._getvolumepathname - imported by nt, ntpath, C:\Users\User\Documents\Python\test.py
missing module named nt._getfullpathname - imported by nt, ntpath, C:\Users\User\Documents\Python\test.py
missing module named nt._getfinalpathname - imported by nt, ntpath, C:\Users\User\Documents\Python\test.py
missing module named nt._isdir - imported by nt, ntpath, C:\Users\User\Documents\Python\test.py
missing module named nt._exit - imported by nt, os, C:\Users\User\Documents\Python\test.py
missing module named nt._have_functions - imported by nt, os, C:\Users\User\Documents\Python\test.py
missing module named ce - imported by os, C:\Users\User\Documents\Python\test.py
missing module named ce._exit - imported by ce, os, C:\Users\User\Documents\Python\test.py
missing module named ce._have_functions - imported by ce, os, C:\Users\User\Documents\Python\test.py
missing module named ntpath.commonprefix - imported by ntpath, unittest.util, C:\Users\User\Documents\Python\test.py
missing module named warnings.warn - imported by warnings, plistlib, random, C:\Users\User\Documents\Python\test.py
missing module named _warnings._defaultaction - imported by _warnings, warnings, C:\Users\User\Documents\Python\test.py
missing module named _warnings.warn_explicit - imported by _warnings, warnings, C:\Users\User\Documents\Python\test.py
missing module named _warnings._filters_mutated - imported by _warnings, warnings, C:\Users\User\Documents\Python\test.py
missing module named _warnings.filters - imported by _warnings, warnings, C:\Users\User\Documents\Python\test.py
missing module named _warnings.warn - imported by _warnings, warnings, C:\Users\User\Documents\Python\test.py
missing module named _warnings._onceregistry - imported by _warnings, warnings, C:\Users\User\Documents\Python\test.py
missing module named collections.OrderedDict - imported by collections, enum, inspect, email._header_value_parser, unittest.util, C:\Users\User\Documents\Python\test.py
missing module named time.monotonic - imported by time, subprocess, threading, socketserver, C:\Users\User\Documents\Python\test.py
missing module named _thread.allocate_lock - imported by _thread, _strptime, C:\Users\User\Documents\Python\test.py
missing module named _thread.get_ident - imported by _thread, reprlib, C:\Users\User\Documents\Python\test.py
missing module named _thread.RLock - imported by _thread, functools, C:\Users\User\Documents\Python\test.py
missing module named _collections.defaultdict - imported by _collections, collections, C:\Users\User\Documents\Python\test.py
missing module named _collections.OrderedDict - imported by _collections, collections, C:\Users\User\Documents\Python\test.py
missing module named _collections._count_elements - imported by _collections, collections, C:\Users\User\Documents\Python\test.py
missing module named _collections.deque - imported by _collections, threading, collections, C:\Users\User\Documents\Python\test.py
missing module named collections.deque - imported by collections, threading, contextlib, ast, shlex, pydoc, email.feedparser, C:\Users\User\Documents\Python\test.py
missing module named _thread.stack_size - imported by _thread, threading, C:\Users\User\Documents\Python\test.py
missing module named _thread._local - imported by _thread, threading, C:\Users\User\Documents\Python\test.py
missing module named threading.current_thread - imported by threading, _threading_local, C:\Users\User\Documents\Python\test.py
missing module named threading.RLock - imported by threading, _threading_local, bz2, C:\Users\User\Documents\Python\test.py
missing module named functools.wraps - imported by functools, signal, contextlib, unittest.result, unittest.signals, C:\Users\User\Documents\Python\test.py
missing module named collections.namedtuple - imported by collections, selectors, difflib, inspect, urllib.parse, ssl, unittest.util, doctest, functools, C:\Users\User\Documents\Python\test.py
missing module named math.log - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named math.ceil - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named math.exp - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named math.e - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named math.pi - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named math.sqrt - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named math.sin - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named math.acos - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named math.cos - imported by math, random, C:\Users\User\Documents\Python\test.py
missing module named sys.modules - imported by sys, dummy_threading, C:\Users\User\Documents\Python\test.py
missing module named itertools.count - imported by itertools, threading, C:\Users\User\Documents\Python\test.py
missing module named itertools.islice - imported by itertools, threading, reprlib, C:\Users\User\Documents\Python\test.py
missing module named itertools.starmap - imported by itertools, collections, C:\Users\User\Documents\Python\test.py
missing module named builtins.open - imported by builtins, bz2, tokenize, tarfile, C:\Users\User\Documents\Python\test.py
missing module named itertools.chain - imported by itertools, tokenize, collections, C:\Users\User\Documents\Python\test.py
missing module named itertools.repeat - imported by itertools, tokenize, collections, C:\Users\User\Documents\Python\test.py
missing module named copy.deepcopy - imported by copy, weakref, email.generator, C:\Users\User\Documents\Python\test.py
missing module named _weakref.getweakrefs - imported by _weakref, weakref, C:\Users\User\Documents\Python\test.py
missing module named _weakref.CallableProxyType - imported by _weakref, weakref, C:\Users\User\Documents\Python\test.py
missing module named _weakref.ref - imported by _weakref, _weakrefset, weakref, C:\Users\User\Documents\Python\test.py
missing module named _weakref.ReferenceType - imported by _weakref, weakref, C:\Users\User\Documents\Python\test.py
missing module named _weakref.ProxyType - imported by _weakref, weakref, C:\Users\User\Documents\Python\test.py
missing module named _weakref.getweakrefcount - imported by _weakref, weakref, C:\Users\User\Documents\Python\test.py
missing module named _weakref.proxy - imported by _weakref, weakref, collections, C:\Users\User\Documents\Python\test.py
missing module named weakref.ref - imported by weakref, _threading_local, C:\Users\User\Documents\Python\test.py
missing module named org - imported by copy, C:\Users\User\Documents\Python\test.py
missing module named org.PyStringMap - imported by org, copy, C:\Users\User\Documents\Python\test.py
missing module named _struct._clearcache - imported by _struct, struct, C:\Users\User\Documents\Python\test.py
missing module named _struct.__doc__ - imported by _struct, struct, C:\Users\User\Documents\Python\test.py
missing module named errno.ENOENT - imported by errno, gettext, C:\Users\User\Documents\Python\test.py
missing module named gettext.ngettext - imported by gettext, argparse, optparse, C:\Users\User\Documents\Python\test.py
missing module named gettext.gettext - imported by gettext, argparse, optparse, getopt, C:\Users\User\Documents\Python\test.py
missing module named _dummy_threading - imported by dummy_threading, C:\Users\User\Documents\Python\test.py
missing module named _dummy_threading.__all__ - imported by _dummy_threading, dummy_threading, C:\Users\User\Documents\Python\test.py
missing module named dummy_threading.RLock - imported by dummy_threading, bz2, C:\Users\User\Documents\Python\test.py
missing module named _winapi.CREATE_NEW_CONSOLE - imported by _winapi, subprocess, C:\Users\User\Documents\Python\test.py
missing module named _winapi.STARTF_USESTDHANDLES - imported by _winapi, subprocess, C:\Users\User\Documents\Python\test.py
missing module named _winapi.SW_HIDE - imported by _winapi, subprocess, C:\Users\User\Documents\Python\test.py
missing module named _winapi.STD_OUTPUT_HANDLE - imported by _winapi, subprocess, C:\Users\User\Documents\Python\test.py
missing module named _winapi.STD_ERROR_HANDLE - imported by _winapi, subprocess, C:\Users\User\Documents\Python\test.py
missing module named _winapi.CREATE_NEW_PROCESS_GROUP - imported by _winapi, subprocess, C:\Users\User\Documents\Python\test.py
missing module named _winapi.STARTF_USESHOWWINDOW - imported by _winapi, subprocess, C:\Users\User\Documents\Python\test.py
missing module named _winapi.STD_INPUT_HANDLE - imported by _winapi, subprocess, C:\Users\User\Documents\Python\test.py
missing module named os.urandom - imported by os, random, C:\Users\User\Documents\Python\test.py
missing module named _io.StringIO - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.BufferedWriter - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.BlockingIOError - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.FileIO - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.UnsupportedOperation - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.TextIOWrapper - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.BufferedRandom - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.open - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.BufferedRWPair - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.DEFAULT_BUFFER_SIZE - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.IncrementalNewlineDecoder - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.BufferedReader - imported by _io, io, C:\Users\User\Documents\Python\test.py
missing module named _io.BytesIO - imported by _io, io, C:\Users\User\Documents\Python\test.py

**Comment by codewarrior0** [comment]
```
LOADER: Running test.py
hello
LOADER: OK.
LOADER: Cleaning up Python interpreter.
```

This output indicates success. It seems your problem was double-clicking the EXE instead of running it from a command window. 

Feel free to open another issue when something actually goes wrong. ;)

**Comment by ProfPh** [comment]
What... as I said originally this was always working for a hello world script. I was just showing the warnings and errors thrown for such a simple script.

For a script that actually has imports the .exe does not run no matter how you open it..

**Comment by ProfPh** [comment]
I didn't actually say that in the first post, my mistake. Running it on an actual script now.

**Comment by ProfPh** [comment]
```
C:\Users\User\Documents\Python>python -m PyInstaller --debug login.py
62 INFO: PyInstaller: 3.0
62 INFO: Python: 3.5.0
62 INFO: Platform: Windows-10.0.10240
62 INFO: wrote C:\Users\User\Documents\Python\login.spec
78 INFO: UPX is not available.
78 INFO: Extending PYTHONPATH with C:\Users\User\Documents\Python
78 INFO: checking Analysis
109 INFO: checking PYZ
125 INFO: checking PKG
125 INFO: Building because toc changed
125 INFO: Building PKG (CArchive) out00-PKG.pkg
156 INFO: Bootloader C:\Python35\lib\site-packages\PyInstaller\bootloader\Window
s-64bit\run_d.exe
156 INFO: checking EXE
156 INFO: Building because out00-EXE.toc is bad
156 INFO: Building EXE from out00-EXE.toc
156 INFO: Appending archive to EXE C:\Users\User\Documents\Python\build\login\l
ogin.exe
156 INFO: checking COLLECT
156 INFO: Building COLLECT because out00-COLLECT.toc is non existent
156 INFO: Building COLLECT out00-COLLECT.toc

C:\Users\User\Documents\Python>cd dist

C:\Users\User\Documents\Python\dist>cd login

C:\Users\User\Documents\Python\dist\login>login.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\User\Documents\Python\dist\login\login.exe
LOADER: homepath is C:\Users\User\Documents\Python\dist\login
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\User\Documents\Python\dist\login\login.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\Users\User\Documents\Python\dist\login)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\Users\User\Documents\Python\dist\login\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Users\User\Documents\Python\dist\login\base_lib
rary.zip;C:\Users\User\Documents\Python\dist\login
LOADER: sys.prefix is C:\Users\User\Documents\Python\dist\login
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\User\Documents\Python\dist\login\base_li
brary.zip;C:\Users\User\Documents\Python\dist\login
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running login.py
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\User\appdata\local\programs\python\python35\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 363, in load_module
  File "C:\Python35\lib\site-packages\openpyxl\__init__.py", line 12, in <module
>
    with open(src_file) as src:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Docum
ents\\Python\\dist\\login\\openpyxl\\.constants.json'
login returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.
```

**Comment by codewarrior0** [comment]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\User\appdata\local\programs\python\python35\lib\site-packages\
PyInstaller\loader\pyimod03_importers.py", line 363, in load_module
  File "C:\Python35\lib\site-packages\openpyxl\__init__.py", line 12, in <module
>
    with open(src_file) as src:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\User\\Docum
ents\\Python\\dist\\login\\openpyxl\\.constants.json'
```

You must explicitly include any non-Python data files into your exe's folder. Read https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Collect-Data-Files for more info.

**Comment by codewarrior0** [comment]
Actually, since openpyxl is a third party package, you may want to define a hook file `hook-openpyxl.py` that collects the data files using the `datas` variable.

Manual entry for hooks: https://pythonhosted.org/PyInstaller/#hook-global-variables

Example hook that only collects data files: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-appy.pod.py

**Comment by ProfPh** [comment]
Hey, thanks for reopening it. I'm still a little confused on what to do. I added the snippet of code to the .spec file and then built it using pyinstaller login.spec, where are the datafiles collected after I run it?

**Comment by ProfPh** [comment]
If we can say that it's no longer a bug, where should I seek help in using PyInstaller?

**Comment by ProfPh** [comment]
nvm

**Comment by ProfPh** [comment]
Correct in thinking this is a bug with openpyxl:

https://bitbucket.org/openpyxl/openpyxl/issues/498/moving-constants-to-a-configuration-file
https://bitbucket.org/openpyxl/openpyxl/pull-requests/67/include-constantsjson-as-part-of-the/diff
https://bitbucket.org/openpyxl/openpyxl/pull-requests/83/use-__about__py-instead-of-constantsjson/diff

Using the changes made in the last url and then installing openpyxl from that makes pyinstaller work

**Comment by htgoebel** [comment]
Sound as this is solved?!

**Comment by eskawl** [comment]
can these warnings be ignored? I got some 750 missing module warnings in the warning file. Although executing a function from one of these module works as intended. I am on win 10, python 3.4, pyinstaller 3.2
