### ISSUE TITLE
Import Error With Message module.

### ISSUE THREAD

**Issue by thebongy** [pyinstaller/pyinstaller#1632]
I am trying to convert a python flask application into an exe. It is rasing an import error with the message module, even though this file appears to be present in the `.pyz` file. Why is the Import error raised, even though the module appears to exist? I am using python 2.7 with Pyinstaller 3.0 . 
The Error:
[error1](https://cloud.githubusercontent.com/assets/7080652/10726997/82247912-7bfc-11e5-86af-c6d3dfb0506d.jpg)
`.pyz file appears to have the module`:
[error2](https://cloud.githubusercontent.com/assets/7080652/10727007/963e513e-7bfc-11e5-9133-d6f44f7362ab.jpg)

**Comment by htgoebel** [comment]
Please follow the instructions in https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs. Otherwise we will not be able to help you.

**Comment by thebongy** [comment]
I have tried everything @htgoebel , but still the error persists.....

**Comment by htgoebel** [comment]
Please follow https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by thebongy** [comment]
OS:Windows Vista,
Python-Version:2.7
PyInstaller Version:3.0 (Also Tested with latest dev version from github)

**Comment by htgoebel** [comment]
Read *all* of the Wiki-page and provide *all* of the information. If you want us to help you, you need to provide enough information. And this s what we described in the wiki.

**Comment by thebongy** [comment]
Here is a simple reproduction of the error:
1.Download this gist: https://gist.github.com/thebongy/7ac17b98a63a218223ce
a) Ensure Flask is installed on machine:
`pip install Flask`

2.Use `pyInstaller main.py` to create the exe/

3.Run the exe,
`/dist/main.exe`
The following import error is produced:
![error1](https://cloud.githubusercontent.com/assets/7080652/10728716/415f96e2-7c0a-11e5-9512-a11a09ce31c1.jpg)

4. Error is reproduced even with `--onedir` , `--noupx`, `--onefile` options included in the pyinstaller command individually.

[Please Inform me if any extra info required]

**Comment by htgoebel** [comment]
Thanks. The error message is misleading. It's the module `email.message` which is missing. Python 2.7 gives inprecise error messages when importing a submodule fails.

Please check if `email.message` is in the PYZ. It should, since we support it and have a test-case for it. So it may be a problem of `werkzeug`.

And please post test, not pictures. Images can not be quoted.

**Comment by thebongy** [comment]
Yes email.message is in the PYZ. Is there any present workaround for the problem?

**Comment by htgoebel** [comment]
Nothing I'm aware of. Sorry.

**Comment by thebongy** [comment]
@htgoebel No Worries :) . I plan to transfer my work to the `bottle` library instead of `flask` because it seems to work fine as an exe with a simple program. 

Anyway, thank you for your support :+1:

**Comment by qingweiqm** [comment]
hi, I have the same issue, any ideas now ?

I checked the PYZ file, it shows:
 'email.message': (0, 1122171, 10009),

which means the email.message is in or not ?

@htgoebel
