### ISSUE TITLE
How can I package multiple .py files into single .exe file ? 

### ISSUE THREAD

**Issue by georgemunteanu** [pyinstaller/pyinstaller#1633]
1. [PROBLEM]
input: multiple .py files
output: a single .exe file 

2. [CODE]
Test example:
I have a main.py + component.py. 
[ main.py code ]
```
# Import packages
import Tkinter
from Tkinter import *
import tkFileDialog
import tkMessageBox

# Create dummy function
def showMessage():
    import subprocess
    execfile("component.py")

       
# Add button
root = Tkinter.Tk(className="test")
button= Button(root, text="Click", command=showMessage)
button.grid(row=10, column=3, sticky = W + E)
    
# Pack it
root.mainloop() 

[ component.py. code ]
# Import packages
import Tkinter
from Tkinter import *
import tkFileDialog
import tkMessageBox

# Create dummy function
def showMessage():
    tkMessageBox.showinfo('test', 'test.')
showMessage()
```

[CURRENT RESULT]
The exe file will check for component.py and because it will not find it, it will fail to open the msgBox.
Note: I have build only the main.py file
Note: I am using python 2.7.10 + pyinstaller 3.0.

**Comment by htgoebel** [comment]
This is not supported by PyInstaller.

I suggest using "import component" as the easiest way to get your expected result.

**Comment by georgemunteanu** [comment]
thanks. I will consider every .py as a separate module.

**Comment by villuis91** [comment]
You can use multiple imported files. I tested it with simple scripts and works well.
What is giving problems is the import of the distinct libraries.

I don't import with subprocess. I'm doing it with "import folder.script" or with "from folder.script import func"
