### ISSUE TITLE
bootloader & freebsd: exe location extraction from /proc broken

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#1635]
For binaries made with single-file mode and if /proc is mounted on FreeBSD (seems not all users have it mounted), it tries to get the full path from there, but there are some funny characters at the end:
```
root@muenchen:/ # borg
Cannot open self /usr/local/bin/borg▒▒ or archive /usr/local/bin/borg▒▒.pkg
```
Maybe some \0 missing?

See there, line 253:
https://github.com/pyinstaller/pyinstaller/commit/d2e749f0d1fede80828c29837940a9269f596ebb

**Comment by ThomasWaldmann** [comment]
Working on this...

**Comment by breyer** [comment]
On a different terminal, does funny characters are question marks:

```
Cannot open self /usr/local/bin/borg?? or archive /usr/local/bin/borg??.pkg
```

**Comment by ThomasWaldmann** [comment]
@breyer yes, in fact it could be arbitrary crap of indefinite length.

**Comment by ThomasWaldmann** [comment]
Needs a windows developer now to fix it on windows also.

**Comment by ThomasWaldmann** [comment]
Is there any issue with (the now quite trivial) PR #1637 ?

**Comment by ThomasWaldmann** [comment]
I can confirm this fix works on freebsd:
```
$ sudo umount /proc
$ borg.exe
Cannot open self /vagrant/borg/borg/borg.exe or archive /vagrant/borg/borg/borg.exe.pkg
$ sudo mount -t procfs none /proc
$ borg.exe
usage: borg.exe [-h] [-V]
...
```                
You see, without /proc mounted, it does not work, with /proc mounted it does. So /proc-based discovery of the exe locations works.
