### ISSUE TITLE
No pyinstaller.py created with pip install or configure.py

### ISSUE THREAD

**Issue by essandess** [pyinstaller/pyinstaller#1646]
I'm trying to install pyinstaller and have not been able to create the `pyinstaller.py` script:

* `sudo -H pip install pyinstaller`
* ``cd `python -c "from distutils.sysconfig import get_python_lib; print(get_python_lib())"`/PyInstaller``
* `ls`

    `__init__.py	building	configure.pc	log.py`
    `__init__.pyc	compat.py	depend		log.pc`
    `__main__.py	compat.pyc	fake-modules	utils`
    `__main__.pyc	config.py	hooks`
    `archive		config.pc	lib`
    `bootloader	configure.py	loader`

* `python configure.py`

    `Traceback (most recent call last):`
     ` File "configure.py", line 20, in <module>`
     `    from . import  combat`
    `ValueError: Attempted relative import in non-package`

* `python -m PyInstaller.configure configure.py`
* `ls ~/.local/share/`
* `ls ~/Library/Application\ Support/`

Am I doing something wrong? Where is `pyinstaller.py`?

**Comment by essandess** [comment]
Never mind. Here's the install command:

* `sudo -H python -m PyInstaller configure.py`

Should this be documented somewhere?

**Comment by matysek** [comment]
@essandess `configure.py` no longer exists and `pip install` creates  command just `pyinstaller`.
