### ISSUE TITLE
pyinstaller --help output causes RST errors

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#1648]
The doc makefile calls `pyinstaller --help` to generate the options list for the manual.

Some recent change in this output is causing the following errors,

    _pyinstaller-options.tmp:15: (WARNING/2) Option list ends without a blank line; unexpected unindent.
    _pyinstaller-options.tmp:88: (WARNING/2) Option list ends without a blank line; unexpected unindent.
    _pyinstaller-options.tmp:99: (WARNING/2) Definition list ends without a blank line; unexpected unindent.

Frankly I do not see what the problem is, those three lines look just like other lines for content and for use of blank lines. But that is restructured text for you. Unfortunately these error message then appear in the generated HTML and there is no way to exclude them.

For reference the offending lines are:

line 13-17

    --clean               Clean PyInstaller cache and remove temporary files
                      before building.
    --log-level {DEBUG,INFO,WARN,ERROR,CRITICAL}
                      Amount of detail in build-time console messages

 line 86-9

    -m <FILE or XML>, --manifest <FILE or XML>
                      add manifest FILE or XML to the exe
    -r FILE[,TYPE[,NAME[,LANGUAGE]]], --resource FILE[,TYPE[,NAME[,LANGUAGE]]]
                      Add or update a resource of the given type, name and

line 98-100

                      used multiple times.
     --uac-admin           Using this option creates a Manifest which will
                      request elevation upon application restart.

**Comment by tallforasmurf** [comment]
When I pull the latest source (4 Nov 15) this problem has gone away.

**Comment by tallforasmurf** [comment]
Sorry, I had a bungled installation and _pyinstaller-options.tmp was not being built. Yes the problem still occurs. Investigating.

**Comment by htgoebel** [comment]
I'll take care of this.

**Comment by tallforasmurf** [comment]
The problem is the restrictive rules of Rst "option lists", see http://docutils.sourceforge.net/docs/ref/rst/restructuredtext.html#option-lists. In an option list there is no provision for displaying detailed syntax of an argument. The option list only supports an *option* followed by "an argument placeholder". A placeholder may be a word, or it may be `< any characters >`. 

In the output of pyinstaller --help, there are two lines that do not match this pattern, 

    --log-level {DEBUG,INFO,WARN,ERROR,CRITICAL}

    -r FILE[,TYPE[,NAME[,LANGUAGE]]], --resource FILE[,TYPE[,NAME[,LANGUAGE]]]

As a result, Rst fails to recognize these two lines as "options". This gives an error because the option list (preceding the line) has unexpectedly ended. It thinks you have an option list and a definition list butted together.

I have experimented with changing those lines to the allowed syntax,

    --log-level < DEBUG | INFO | WARN | ERROR | CRITICAL >

    -r < FILE[,TYPE[,NAME[,LANGUAGE]]] >, --resource <FILE[,TYPE[,NAME[,LANGUAGE]]] >

and this eliminates the errors. However, Rst always shows the "argument placeholder" in italics. That's appropriate for the -r option, where those words are meta-variables, but not appropriate for the --log-level where they are literal values to be copied.

I would recommend changing both entries to use only a place-holder in the command and expand the place-holder in the text, for example:

    --log-level LEVEL
                      Amount of detail in build-time console messages.
                      LEVEL may DEBUG, INFO, WARN, ERROR, or CRITICAL
                      (default: INFO).

    -r RESOURCE, --resource RESOURCE
                      Add or update a resource to a Windows executable.
                      The RESOURCE is one to four items,
                      FILE[,TYPE[,NAME[,LANGUAGE]]].  FILE can be a
                      data file or an exe/dll. For data files, at least
                      TYPE and NAME must be specified. LANGUAGE defaults
                      to 0 or may be specified as wildcard \* to update all
                      resources of the given TYPE and NAME. For exe/dll
                      files, all resources from FILE will be added/updated
                      to the final executable if TYPE, NAME and LANGUAGE are
                      omitted or specified as wildcard \*.This option can be
                      used multiple times.
