### ISSUE TITLE
pyside signal not fired when communicating between threads

### ISSUE THREAD

**Issue by balddude** [pyinstaller/pyinstaller#1657]
Hello, when I freeze this code under Mac, signal in "MyThread.run()" is not emitted. Under Windows everything is fine. Other than the signal not being emitted, the code run fines.
For more information see [http://stackoverflow.com/questions/33444132/pyside-signal-not-fired-with-pyinstaller-when-communicating-between-threads]

##### To reproduce
- run filename.app
- Click on "OK" button.
- Click on "Cancel" button.

###### Expected behavior
After pressing the "Cancel" button, *DLL got the value.* is displayed in widget.
Running the code below produces the expected behavior.

###### Wrong behavior
After pressing the "Cancel" button, nothing is displayed in widget.

##### Run through:
sudo pyinstaller  filename.py --windowed --noconsole

##### Platform details:
Using python 2.7.10
Pyinstaller 3.0
Yosemite 10.10.5 (Mac Pro...the wine cooler)
PySide 1.2.1

    import sys
    from PySide import QtGui
    from PySide.QtCore import QThread, Signal, QObject
    
    def functionInDLL(callback):
        return_value = 0
        while (return_value == 0):
            return_value = callback(2)
    
    
    class MyThread(QThread):
        str_signal = Signal(str)
        def __init__(self):
            QThread.__init__(self)
            self.return_value = 0
    
        def returnValueToDll(self, data=0):
            return self.return_value 
    
        def run(self):
            if functionInDLL(self.returnValueToDll) == 42:
                print"DLL got the value."
                self.str_signal.emit("DLL got the value.") # not emitted when frozen
            else:
                print"DLL did not get the value."
                self.str_signal.emit("DLL did not get the value.")
            self.exec_()         
    
        def setValueSentToDll(self, data):
            self.return_value = data
    
    
    
    class MainThreadClass(QObject):
        int_signal = Signal(int)
        def __init__(self):
            super(MainThreadClass, self).__init__()
            self.test_thread = MyThread()
            self.int_signal.connect(self.test_thread.setValueSentToDll)
    
        def startMyThread(self):
            self.test_thread.start()
    
        def sendStopValueToDLL(self):
            self.int_signal.emit(42)          
    
    
    
    class MyGUI(QtGui.QWidget):
        def __init__(self):
            super(MyGUI, self).__init__()
            self.text_information = QtGui.QLabel(text="No started yet...")
            self.dll_information = QtGui.QLabel(text="")
            self.ok_button = QtGui.QPushButton("OK")
            self.cancel_button = QtGui.QPushButton("Cancel")
            self.close_button = QtGui.QPushButton("Close")
            label_hbox = QtGui.QHBoxLayout()
            hbox = QtGui.QHBoxLayout()
            hbox.addWidget(self.ok_button)
            hbox.addWidget(self.cancel_button)
            hbox.addWidget(self.close_button)
            vbox = QtGui.QVBoxLayout()
            label_hbox.addWidget(self.text_information)
            label_hbox.addWidget(self.dll_information)
            vbox.addLayout(label_hbox)
            vbox.addLayout(hbox)
    
            self.setLayout(vbox)
            self.ok_button.clicked.connect(self.onOk)
            self.cancel_button.clicked.connect(self.onCancel)
            self.close_button.clicked.connect(self.onClose)
            self.show()
            self.main_thread = MainThreadClass()
            self.main_thread.test_thread.str_signal.connect(lambda data: self.setDllStatusOnWidget(data))
    
    
        def onOk(self):
            self.main_thread.startMyThread()    
            self.text_information.setText("Started")
            self.dll_information.setText("")
    
        def onCancel(self):
            self.main_thread.sendStopValueToDLL()
            self.text_information.setText("Canceled")
    
        def onClose(self):
            self.main_thread.test_thread.exit()   
            self.close()
    
        def setDllStatusOnWidget(self, text=""):
            self.dll_information.setText(text)
    
    
    if __name__ == '__main__':
        app = QtGui.QApplication(sys.argv)
        ex = MyGUI()
        sys.exit(app.exec_())

**Comment by codewarrior0** [comment]
A couple things to note:

- All of your signals run on the main thread. There are no calls to `moveToThread`, which would move an object and its signals to another thread; and because your worker thread is just spinning in a loop in `functionInDLL`, it would never get a chance to handle those signals anyway. The call to `self.exec_()` in `MyThread.run()` is probably pointless. 

- I have frequently had random crashes when connecting a signal to a lambda. I believe this is because the PySide wrapper for signal calls does not retain the lambda object. 

Does anything change if you replace the lambda with `self.main_thread.test_thread.str_signal.connect(self.setDllStatusOnWidget)?

**Comment by balddude** [comment]
# oooohhh YEAH!!!
Man, you made my day! heck no, you made my weekend!

On a more serious note. Running a few tests, the lambda seems to solve the problem.
I need to run more tests to see if everything is fine, but it's looking good.

**Comment by htgoebel** [comment]
Sounds like this is solved.
