### ISSUE TITLE
problem with hardcoded ldconfig path

### ISSUE THREAD

**Issue by spinus** [pyinstaller/pyinstaller#1659]
Hi,

I'm using the system when there is no /sbin/ldconfig and pyinstaller is crashing. I did a symlink and work correctly but wonder if woulndn't be good if pyinstaller will search for ldconfig the same way as it searches for upx? or mayby distutils find_executable would be handly?

**Comment by matysek** [comment]
@spinus What function `find_executable` exactly do you mean? Could you try to fix it and submit a pull request?

**Comment by spinus** [comment]
http://epydoc.sourceforge.net/stdlib/distutils.spawn-module.html#find_executable

I could but I'm very busy now and cannot provide any timeline :( probably new year?

**Comment by matysek** [comment]
If that's not fixed by that time feel free to do that.

**Comment by spinus** [comment]
OK.

**Comment by htgoebel** [comment]
@spinus Where is `lsconfig` located on your system?

**Comment by htgoebel** [comment]
If we work on this, we should reuse the `LDCONFIG_CACHE` in `depend.utils`.
@ThomasWaldmann Could you please post a view lines of FreeBSD `lsconfig -r`-ouput here. Can the first line be skipped like on Linux? Thanks.

**Comment by ThomasWaldmann** [comment]
```
[vagrant@freebsd-10 ~]$ ldconfig -r    
/var/run/ld-elf.so.hints:
	search directories: /lib:/usr/lib:/usr/lib/compat:/usr/local/lib:/usr/local/llvm35/lib
	0:-lgeom.5 => /lib/libgeom.so.5
	1:-lnvpair.2 => /lib/libnvpair.so.2
	2:-lthr.3 => /lib/libthr.so.3
	3:-ldtrace.2 => /lib/libdtrace.so.2
...
```

**Comment by htgoebel** [comment]
Uff, this looks quite different than on linux. I'll work on this tomorrow.

**Comment by spinus** [comment]
@htgoebel thank you for the effort and a PR, but I'm affraid it won't help too much.

Currently ldconfig in my system can be grabbed from ``/home/spinus/.nix-profile/bin/ldconfig`` (this is in my PATH) which is symlink to ``/nix/store/hd6km3hscbgl2yw8nx7lr5z9s8h89p04-glibc-2.21/bin/ldconfig``.

Any particular reason why hardcoding available search paths is preferred over environment PATH variable which should contain all executables available for user?

**Comment by htgoebel** [comment]
FreeBSD seams to be even more complicated than i thought.. I'll have to set up a vagrant machine myself.

**Comment by ThomasWaldmann** [comment]
https://github.com/borgbackup/borg/blob/master/Vagrantfile Feedback welcome. :)

**Comment by htgoebel** [comment]
@spinus Well, on most Linux-systems, `/sbin` is not on the users path. What kind of system are you using?

**Comment by spinus** [comment]
@htgoebel it's http://nixos.org/ (but I'm using debian/ubuntu few others as well), I see, you're right, I totally forgot about this :[

so, maybe PATH + sbin pathes, or this would be too crazy?

**Comment by spinus** [comment]
Thank you!

**Comment by htgoebel** [comment]
@ThomasWaldmann Thanks a lot for the Vagrantfile. It made testing this *much* easier!
