### ISSUE TITLE
Configurable policy for importing external Python files

### ISSUE THREAD

**Issue by rasky** [pyinstaller/pyinstaller#166]
**Original date**: 2010/03/15

Currently, PyInstaller adds the executable's directory to the sys.path, making it possible to import external Python files. This is very useful in some scenarios (eg: external plugins) but other people find that it is even a security problem (since attackers can inject code by adding files on the filesystem and relying on modules that are correctly missing; eg: posix.py on a Windows system).

After [770], users that are aware of this can remove the executable's directory from sys.path at runtime to avoid imports of external files. This is of course sub-optimal (especially since most Python programmers are unfamiliar with import internals).

I think that PyInstaller should simply let the user decide about which behaviour he wants, through the spec file.

**Comment by htgoebel** [comment]
I'm in favor of *not* implementing this, IMHO it's not worth the effort and there is a simple workaround.
Instead add a recipe to the wiki.

**Comment by htgoebel** [comment]
No more comments, closing
