### ISSUE TITLE
builds not reproducible

### ISSUE THREAD

**Issue by anarcat** [pyinstaller/pyinstaller#1668]
i tried to see if i could generate the same binary with the same source tree by running pyinstaller multiple times. the idea here is that reproducible builds are a useful feature to have to verify the integrity of a binary (compared to the source code). some rationale is well detailed in [Debian's reproducible build project](https://wiki.debian.org/ReproducibleBuilds/About).

turns out that repeated calls to pyinstaller do *not* generate the same binary, as i was led to believe by #1590. here's an example:

```
(borg-test)[1167]anarcat@angela:borg$ pyinstaller -D -n borg-linux-64 \
      --hidden-import=logging.config borg/__main__.py
129 INFO: PyInstaller: 3.1.dev0
130 INFO: Python: 3.4.2
132 INFO: Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
135 INFO: wrote /home/anarcat/src/borg/borg-linux-64.spec
143 INFO: UPX is not available.
148 INFO: Extending PYTHOHPATH with paths
['/home/anarcat/src/borg', '/home/anarcat/src/borg']
149 INFO: checking Analysis
157 INFO: Building because hookspath changed
158 INFO: Initializing module dependency graph...
165 INFO: Initializing module graph hooks...
173 INFO: Analyzing base_library.zip ...
4764 INFO: Processing pre-find module path hook   distutils
4785 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.4/distutils'
8598 INFO: Analyzing hidden import 'logging.config'
9233 INFO: running Analysis out00-Analysis.toc
9321 INFO: Analyzing /home/anarcat/src/borg/borg/__main__.py
10731 INFO: Looking for import hooks ...
10739 INFO: Processing hook   hook-sysconfig.py
10748 INFO: Processing hook   hook-pydoc.py
10749 INFO: Processing hook   hook-distutils.py
10752 INFO: Processing hook   hook-encodings.py
10790 INFO: Processing hook   hook-xml.py
11484 INFO: Looking for ctypes DLLs
11493 INFO: Analyzing run-time hooks ...
11544 INFO: Looking for dynamic libraries
12583 INFO: Looking for eggs
12584 INFO: Python library not in binary depedencies. Doing additional searching...
12773 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.4m.so.1.0
12816 INFO: Warnings written to /home/anarcat/src/borg/build/borg-linux-64/warnborg-linux-64.txt
12891 INFO: checking PYZ
12897 INFO: Building because toc changed
12897 INFO: Building PYZ (ZlibArchive) /home/anarcat/src/borg/build/borg-linux-64/out00-PYZ.pyz
13588 INFO: checking PKG
13590 INFO: Building because /home/anarcat/src/borg/build/borg-linux-64/out00-PYZ.pyz changed
13590 INFO: Building PKG (CArchive) out00-PKG.pkg
13814 INFO: Bootloader /home/anarcat/.virtualenvs/borg-test/lib/python3.4/site-packages/PyInstaller/bootloader/Linux-64bit/run
13814 INFO: checking EXE
13816 INFO: Building because strip changed
13816 INFO: Building EXE from out00-EXE.toc
13818 INFO: Appending archive to EXE /home/anarcat/src/borg/build/borg-linux-64/borg-linux-64
13849 INFO: checking COLLECT
13856 INFO: Building COLLECT out00-COLLECT.toc

(borg-test)[1166]anarcat@angela:borg$ pyinstaller -D -n borg-linux-64-new \
     --hidden-import=logging.config borg/__main__.py
127 INFO: PyInstaller: 3.1.dev0
127 INFO: Python: 3.4.2
129 INFO: Platform: Linux-3.16.0-4-amd64-x86_64-with-debian-8.2
131 INFO: wrote /home/anarcat/src/borg/borg-linux-64-new.spec
138 INFO: UPX is not available.
144 INFO: Extending PYTHOHPATH with paths
['/home/anarcat/src/borg', '/home/anarcat/src/borg']
145 INFO: checking Analysis
154 INFO: Building because hookspath changed
155 INFO: Initializing module dependency graph...
158 INFO: Initializing module graph hooks...
162 INFO: Analyzing base_library.zip ...
4762 INFO: Processing pre-find module path hook   distutils
4783 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.4/distutils'
8635 INFO: Analyzing hidden import 'logging.config'
9298 INFO: running Analysis out00-Analysis.toc
9395 INFO: Analyzing /home/anarcat/src/borg/borg/__main__.py
10822 INFO: Looking for import hooks ...
10832 INFO: Processing hook   hook-pydoc.py
10833 INFO: Processing hook   hook-encodings.py
10871 INFO: Processing hook   hook-distutils.py
10880 INFO: Processing hook   hook-sysconfig.py
10883 INFO: Processing hook   hook-xml.py
11582 INFO: Looking for ctypes DLLs
11590 INFO: Analyzing run-time hooks ...
11639 INFO: Looking for dynamic libraries
12733 INFO: Looking for eggs
12734 INFO: Python library not in binary depedencies. Doing additional searching...
12950 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.4m.so.1.0
12989 INFO: Warnings written to /home/anarcat/src/borg/build/borg-linux-64-new/warnborg-linux-64-new.txt
13087 INFO: checking PYZ
13096 INFO: checking PKG
13098 INFO: Building because /home/anarcat/.virtualenvs/borg-test/lib/python3.4/site-packages/PyInstaller/loader/pyimod01_os_path.pyc changed
13099 INFO: Building PKG (CArchive) out00-PKG.pkg
13325 INFO: Bootloader /home/anarcat/.virtualenvs/borg-test/lib/python3.4/site-packages/PyInstaller/bootloader/Linux-64bit/run
13326 INFO: checking EXE
13331 INFO: Building because strip changed
13332 INFO: Building EXE from out00-EXE.toc
13334 INFO: Appending archive to EXE /home/anarcat/src/borg/build/borg-linux-64-new/borg-linux-64-new
13370 INFO: checking COLLECT
13385 INFO: Building COLLECT out00-COLLECT.toc
(borg-test)[1169]anarcat@angela:borg2$ diff -rq dist/borg-linux-64*
Files dist/borg-linux-64/base_library.zip and dist/borg-linux-64-new/base_library.zip differ
Only in dist/borg-linux-64: borg-linux-64
Only in dist/borg-linux-64-new: borg-linux-64-new
(borg-test)[1178]anarcat@angela:dist$ diff -rq *
Files borg-linux-64/base_library.zip and borg-linux-64-new/base_library.zip differ
Only in borg-linux-64: borg-linux-64
Only in borg-linux-64-new: borg-linux-64-new
(borg-test)[1179]anarcat@angela:dist130$ pyi-archive_viewer borg-linux-64/borg-linux-64
 pos, length, uncompressed, iscompressed, type, name
[(0, 278, 364, 1, 'm', 'struct'),
 (278, 1171, 2018, 1, 'm', 'pyimod01_os_path'),
 (1449, 4006, 8888, 1, 'm', 'pyimod02_archive'),
 (5455, 5741, 14995, 1, 'm', 'pyimod03_importers'),
 (11196, 2445, 6603, 1, 's', 'pyiboot01_bootstrap'),
 (13641, 46, 41, 1, 's', '__main__'),
 (13687, 1506872, 1506872, 0, 'z', 'out00-PYZ.pyz')]
?
(borg-test)[1180]anarcat@angela:dist$ pyi-archive_viewer borg-linux-64-new/borg-linux-64-new
 pos, length, uncompressed, iscompressed, type, name
[(0, 278, 364, 1, 'm', 'struct'),
 (278, 1171, 2018, 1, 'm', 'pyimod01_os_path'),
 (1449, 4006, 8888, 1, 'm', 'pyimod02_archive'),
 (5455, 5741, 14995, 1, 'm', 'pyimod03_importers'),
 (11196, 2445, 6603, 1, 's', 'pyiboot01_bootstrap'),
 (13641, 46, 41, 1, 's', '__main__'),
 (13687, 1506461, 1506461, 0, 'z', 'out00-PYZ.pyz')]
?
```

The variation is in the `pyz` file:

```
(borg-test)[1185]anarcat@angela:dist1$ diff <(pyi-archive_viewer borg-linux-64/borg-linux-64 2>/dev/null) <(pyi-archive_viewer borg-linux-64-new/borg-linux-64-new 2>/dev/null)
8c8
<  (13687, 1506872, 1506872, 0, 'z', 'out00-PYZ.pyz')]
---
>  (13687, 1506461, 1506461, 0, 'z', 'out00-PYZ.pyz')]
```

Turns out the modules in there are not ordered consistently:

```
(borg-test)[1191]anarcat@angela:dist1$ diff -u <(head a) <(head b)
--- /dev/fd/63  2015-11-11 20:19:39.214182156 -0500
+++ /dev/fd/62  2015-11-11 20:19:39.214182156 -0500
@@ -1,10 +1,10 @@
  Name: (ispkg, pos, len)
-{'__future__': (0, 17, 1872),
- '_collections_abc': (0, 1889, 7959),
- '_compat_pickle': (0, 9848, 1954),
- '_dummy_thread': (0, 11802, 2225),
- '_osx_support': (0, 14027, 5304),
- '_strptime': (0, 19331, 7305),
- '_sysconfigdata': (0, 26636, 186),
- '_sysconfigdata_m': (0, 26822, 8047),
- '_threading_local': (0, 34869, 2948),
+{'__future__': (0, 172975, 1872),
+ '_collections_abc': (0, 1180606, 7959),
+ '_compat_pickle': (0, 58957, 1954),
+ '_dummy_thread': (0, 1194415, 2225),
+ '_osx_support': (0, 871793, 5304),
+ '_strptime': (0, 4791, 7305),
+ '_sysconfigdata': (0, 889072, 186),
+ '_sysconfigdata_m': (0, 881025, 8047),
+ '_threading_local': (0, 142008, 2948),
```

which obviously messes up the result. I am not sure i understand why this happens.

Another test, with `-F`, shows that the .zip file does change size there as well...

anything i missed here?

**Comment by phelixbtc** [comment]
relevant: https://github.com/pyinstaller/pyinstaller/issues/1582  
There is a link to a dev branch that at least improves things.

**Comment by htgoebel** [comment]
@anarcat You are using some development version, but which exactly? There has been a change at 2015-10-23 (e04dc31146169e34475f150a44dc933275643d6c) which addresses at least part of the problem.

**Comment by htgoebel** [comment]
@anarcat Please mind: Even when using the current development head, you'll see differences between build. This is due to the fact that PyInstaller is compiling many modules even if there already is byte-code module -- and here "hash  randomization" steps in. So you well need to build with `PYTHONHASHSEED` set -- and of course document the value you used for building, like this:

```
python -c 'import random as R ; R.seed() ; print(R.randint(0,2))' > hashseed.txt
PYTHONHASHSEED=$(cat hashseed.txt)
```

@tallforasmurf Do you think, this is worth documenting in the manual?

**Comment by tallforasmurf** [comment]
It is certainly non-obvious!
I will review this on monday. 
Can anyone comment in general on the need for completely reproducible builds?

Is it not the case, that any change in the source code between builds (even in assertions or comments, depending on the Python optimize option) however small, would cause a difference? Or any update to a dependency module?

 So reproducibility is only between two builds of the identical source with unchanged dependencies?

**Comment by anarcat** [comment]
On 2015-11-14 16:09:31, Nat Picker wrote:
> So reproducibility is only between two builds of the identical source with unchanged dependencies?

That is correct. It is my expectation, basically.

On 2015-11-14 13:49:41, Hartmut Goebel wrote:
> @anarcat Please mind: Even when using the current development head,
> you'll see differences between build. This is due to the fact that
> PyInstaller is compiling many modules even if there already is
> byte-code module -- and here "hash randomization" steps in. So you
> well need to build with `PYTHONHASHSEED` set -- and of course document
> the value you used for building, like this: [...]

What is the hashseed for? What is the impact of publishing that seed?

A.

-- 
Music gives a soul to the universe, wings to the mind, flight to the
imagination and life to everything
                         - Plato

**Comment by anarcat** [comment]
> So reproducibility is only between two builds of the identical source with unchanged dependencies?

@tallforasmurf That is correct. It is my expectation, basically.

> @anarcat Please mind: Even when using the current development head,
> you'll see differences between build. This is due to the fact that
> PyInstaller is compiling many modules even if there already is
> byte-code module -- and here "hash randomization" steps in. So you
> well need to build with `PYTHONHASHSEED` set -- and of course document
> the value you used for building, like this: [...]

@htgoebel What is the hashseed for? What is the impact of publishing that seed?

As for the version number, i tried both with the latest 3.x release and the latest `devel.zip` from the time i reported the bug.

**Comment by htgoebel** [comment]
> What is the hashseed for?

"Its purpose is to allow repeatable hashing, such as for selftests for the interpreter itself", see https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED. This will *disable* hash-randomization, Hash-randomization is a feature to address certain denial-of-service-attacks, see [this presentation from 23C3](http://events.ccc.de/congress/2011/Fahrplan/attachments/2007_28C3_Effective_DoS_on_web_application_platforms.pdf) (you may want to skip the math-part), [Python issue 13703](http://bugs.python.org/issue13703) and [PEP 456](https://www.python.org/dev/peps/pep-0456/). The aim is to make the order of elements within a hash/dict unpredictable - so it's the opposite of what we need for reproducible builds.

Hash-randomization is not important for PyInstaller, since if somebody would prepare such data to trigger the denial-of-service-attack, he/she would target him/herself. PyInstaller does not take random input from anybody.

> What is the impact of publishing that seed?

None. Again: PyInstaller does not take random input from anybody. So we safely can use a fixed seed (resp. disable seeding) here.

P.S.: It came to my mind that it should be save to just set `PYTHONHASHSEED=0`.

**Comment by htgoebel** [comment]
I take this as solve. If you find further issues, please open a new ticket.
