### ISSUE TITLE
explicitly stated hidden imports get excluded by hooks

### ISSUE THREAD

**Issue by phelixbtc** [pyinstaller/pyinstaller#1669]
```
import PIL.Image
import Tkinter
```
built with option `--hidden-import=FixTk`  
results in build info: `INFO: Excluding import 'FixTk'`  
and executable error: `ImportError: No module named FixTk`  

It would be nice if the PIL hook would not remove the FixTk module. Particularly it should respect my `hidden-import` argument no matter what the hook says. Same results with imports the other way round. Version 3.0

**Comment by matysek** [comment]
* This looks like similar to #1584.
* @phelixbtc Does this happen with the `develop`?
* If it is not yet fixed in `develop`, does it work with branch from pull request #1651?

**Comment by phelixbtc** [comment]
@matysek The dev version works. :)  

From testing it seems to me that also `--hidden-import` has precedence now as expected. Thank you guys for the great work.
