### ISSUE TITLE
Multi-executable support

### ISSUE THREAD

**Issue by rasky** [pyinstaller/pyinstaller#167]
**Original date**: 2010/03/15

PyInstaller should grow support for packing programs made of multiple executables.

Currently, there is no way to leverage common parts between multiple executables. Each executable must be build isolated from the others:
- In one-dir mode, dynamic libraries will be reused because they sit on the filesystem, but all Python modules will be duplicated within the two executables.
- In one-file mode, all dynamic libraries and modules are duplicated within each executable.

It is possible to do much better than this, and let each executable reuse parts extracted from other executables.

**Comment by MatthewScholefield** [comment]
How does this multiprocess branch work? Does it still exists as of today? I can't find anything on it.

**Comment by pwuertz** [comment]
I'm also looking for a way of building bundles containing multiple binaries with shared dependencies. This is not the same thing as `multiprocess` right? If so, I can't find anything in the docs about this..

**Comment by bjones1** [comment]
See https://pyinstaller.readthedocs.io/en/v3.3.1/spec-files.html#multipackage-bundles. Contributions welcome.
