### ISSUE TITLE
Cython + PyInstaller once again

### ISSUE THREAD

**Issue by uentity** [pyinstaller/pyinstaller#1671]
Hi all!

Although this topic was already discussed in issue #1353 it is still very actual for me, because no final solution was provided there.

I have exactly the same problem, as described in #1353 - very similar project layout, everything works just fine when I run PyInstaller on project's Python source tree, but if I cythonize everything and build *.so (*.pyd) extensions from sources Analysis module is unable to find *any* dependencies and fails to work correctly.

So, the statements are:
1. PyInstaller discover all the dependencies between Python sources (including external ones from third-party libs) and put 'em all in resulting executable. If I start this executable, application is loading and working fine.
2. However once I inplace compile Python sources to binary extensions, PyInstaller no longer able to find imports (dependencies), and cannot find compiled extensions (they are not present in dist directory at all).

Please somebody experienced **provide a reproducible steps to successfully package Cython-compiled modules with PyInstaller** in described (or similar) cases.
Some questions.
1. What should I expect when PyInstaller correctly recognize all Cython-compiled project modules? Should they go into BINARIES (and copied as a tree of files into resulting *dist* folder) or into PURE (and compressed to executable file)?
2. I've read many times that PyInstaller is able to analyze binary Python extensions and their imports. How can it do that with Cython-compiled extensions? They're not linked to each other and export almost the same set of generic functions. And in my case I really don't need such kind of inspection.
3. Why PyInstaller doesn't find *.so modules? How can I force it to detect and use them?
4. Why can't we just make Analysis use Python source tree and then lookup for corresponding compiled modules. If file x.so (x.pyd) is found for corresponding source x.py -- we take x.so (x.pyd), otherwise compile x.py -> x.pyc and take x.pyc (just like Python itself does).
This behavior is exactly what I desire. How can I manually do that (if there is no other solution)?

**Comment by codewarrior0** [comment]
PyInstaller is able to analyze binary Python extensions *only for C shared libraries*. It cannot analyze them for Python imports. If you have compiled your entire source tree using Cython, then PyInstaller will not be able to analyze your Cython compiled files for Python imports and you will have to specify all of them explicitly using `hiddenimports`.

If you have also Cython-compiled your main script that you use to start your program, I would not expect PyInstaller to work at all, since the startup code is only equipped to run a pure-python main script.

**Comment by uentity** [comment]
Thanks for the answer!

@codewarrior0, I'm not sure that I fully understand the following:
> PyInstaller is able to analyze binary Python extensions only for C shared libraries. It cannot analyze them for Python imports.

Is that mean that PyInstaller only detects:
1. if any of discovered Python source files imports binary shared module X, then X should be included into BINARIES;
2. if shared library X links to another shared library Y, then also include Y into BINARIES (and follow linkage chain further)?

My main start script is pure Python, that's why PyInstaller is able to detect it's dependencies.

If the above statements are correct, then most preferable solution for me would be the following:
1. Start Analysis on Python source tree and let it discover all external (out-of-project) dependencies.
2. Modify ```python pure``` TOC and remove all project files from it.
3. Manually append all Cython-compiled modules to BINARIES.
Is there a way to implement 2-nd stage?

Adding all external dependencies to hidden imports seems to me a very time-consuming and error-prone manual procedure.

**Comment by htgoebel** [comment]
> 2. Modify pure TOC and remove all project files from it.
Is there a way to implement 2-nd stage?

Yes, just modify the `.spec` file. It is a normal python script.

**Comment by tallforasmurf** [comment]
On Fri, Nov 13, 2015 at 3:02 AM, Alexander Gagarin <notifications@github.com
> wrote:

3. Manually append all Cython-compiled modules to BINARIES.
> Is there a way to implement 2-nd stage?
>
> Adding all external dependencies to hidden imports seems to me a very
> time-consuming and error-prone manual procedure
>
You probably do not need to work with TOC structures unless you want to.

See the new manual,

    http://pythonhosted.org/PyInstaller/#adding-binary-files

As you say in step 1, let pyinstaller (or pyi-makespec) build a spec file.

Then add a line to the spec file something like this:

    my_cython_mods = [ ( 'src/*.so', '.' ) ]

and modify Analysis to have  binaries=my_cython_mods, ....

Possibly your cython modules are in more than one folder, then you need
more than one tuple in the list, see the preceding section of the manual
for examples.

**Comment by uentity** [comment]
Thanks @codewarrior0, @htgoebel, @tallforasmurf!
I actually successfully implemented steps 1 - 3 and now my application actually starts!
Step 2 takes only a few lines of code filtering auto-built TOC.
Now I'm facing another issue: local imports not working. I.e. the following code:
```
from A import AA
```
in module B.py located in directory A throws exception.
I feel that it somehow connected to __init__.py handling, but I can't figure out how exactly.
Just to note: if I package non-Cython-compiled Python sources with PyInstaller all local imports work fine.

**Comment by uentity** [comment]
I discovered that import errors were caused by missing modules that failed to compile with Cython. So this issue isn't related to PyInstaller.
By replacing missing modules with *.pyc files I fix errors and my packaged application is fully functional.
Once again, thanks for your answers.
