### ISSUE TITLE
A problem regarding IPython of "ImportError" in scipy

### ISSUE THREAD

**Issue by senkrain** [pyinstaller/pyinstaller#1675]
My Python and IPython are 2.7.10 and 4.0.0 respectfully.

When I run scipy.sparse.linalg on IPython:
![50b8394a-abb8-4518-a83f-15f7e091db2d](https://cloud.githubusercontent.com/assets/15844146/11162730/86794d6a-8aea-11e5-89dd-0d83c00525ac.png)
But actually linalg exists!

When I run the same code on Python, it works well:
<img width="455" alt="c19eb582-f5aa-4089-8d4d-d110e2ce6d10" src="https://cloud.githubusercontent.com/assets/15844146/11162739/b72909a0-8aea-11e5-9b1f-c57408f703de.png">

My spyder information is as follows:
<img width="517" alt="8cacdc23-5d7a-4f4b-9c5b-d9144a93e9e7" src="https://cloud.githubusercontent.com/assets/15844146/11162743/d5b4e2a4-8aea-11e5-9d38-9dc41b39f5db.png">

**Comment by codewarrior0** [comment]
It doesn't look like you're using PyInstaller. Maybe you're looking for [IPython's issue tracker?](https://github.com/ipython/ipython/)

**Comment by htgoebel** [comment]
I can not see why this issue should be related to PyInstaller.
