### ISSUE TITLE
Tcl import error when importing pandas and Tkinter

### ISSUE THREAD

**Issue by cricketgriff** [pyinstaller/pyinstaller#1677]
I received the following error message when trying to run the resulting .exe file created using pyinstaller (option: -w) on the code below.  When I switch the import statements so that I import pandas before Tkinter, pyinstaller works.  This is an issue because I had multiple script files that I wanted to package with pyinstaller and it kept failing due to the order of import statements.  Specifically, I had a gui script (that imported Tkinter) that called a separate computational script (that imported pandas).  I could not make it run correctly by putting the pandas import before the Tkinter import in the first and/or second script.

Error message:
Version conflict for package "Tcl": have 8.5.7, need exactly 8.5.2 
![tclerror](https://cloud.githubusercontent.com/assets/7172629/11196512/b024a9da-8c74-11e5-8d76-f84ab3258aeb.png)

Minimal code:

    import Tkinter as tk
    import pandas as pd
    root = tk.Tk()
    root.mainloop()

System:
Python 2.7.9, Enthought Canopy 1.5.5
pandas 16.2
Tkinter 8.5
pyinstaller 3.1.dev0
Windows 7-6.1 SP1

**Comment by cricketgriff** [comment]
I did edit a couple of package files before I ran the aforementioned code.
\PyInstaller\hooks\hook-PIL.py and commented out:  `excludedimports = [modname_tkinter, 'FixTk', 'PySide', 'PyQt4', 'PyQt5']`
\PyInstaller\hooks\ hook-PIL.SpiderImagePlugin.py and commented out:  `excludedimports = [modname_tkinter, 'FixTk']`

**Comment by matysek** [comment]
@cricketgriff Do you have any idea why `Canopy` python distribution is complaining about Tcl version mismatch?

**Comment by cricketgriff** [comment]
@matysek, I do not have any idea.  I spent some time searching the interwebs but didn't find anything that helped me get to the bottom of it.

**Comment by matysek** [comment]
@cricketgriff Does it work when you freeze your app just with the CPython distribution?

**Comment by htgoebel** [comment]
Got no further info since two months now. Closing.
