### ISSUE TITLE
exe file generated by PyInstaller not running on another pc with the same windows version

### ISSUE THREAD

**Issue by MartinCharlis** [pyinstaller/pyinstaller#1679]
When i convert my python script to exe on windows platform by pyinstaller i get the output file ran successfully in the same pc ,
but it doesn't run in another pc and i got this error ..

python 2.7.10

in pyinstaller 2.1:
print this message:
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\Martin\appdata\local\temp\pip-build-25jk7z\pyinstaller\PyInstaller\loader\pyi_importers.py", line 409, in load_module
ImportError: DLL load failed: The specified module could not be found.`

in pyinstaller 3:
I used cmd to execute exe file but i didn't get any error but it doesn't work too i don't know whats happened it's just suspended or something !!

and sometimes i get this error , ( when i move it to another path )
`Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 521, in load_module
ImportError: DLL load failed: The specified module could not be found.`

**Comment by Csega** [comment]
Sorry, I opened another issue, then I realized, I have the same (or at least similar) problem, so I closed it and just copy my original message here:

"Hi guys!

I successfully packaged an application with Pyinstaller (latest development snapshot: ac57f93). When I try to run it on my own machine (where all the necessary Python stuff is installed), everything works fine. But when I try to run it on a different machine without the necessary packages, I get the following error message:

Traceback (most recent call last):
File "", line 56, in 
File "c:\Python33\lib\site-packages\pyinstaller-3.1.dev0-py3.3.egg\PyInstaller
\loader\pyimod03_importers.py", line 548, in load_module
ImportError: DLL load failed: The specified module could not be found.
pyi_rth_qt5 returned -1

The funny thing is, that there is no C:\Python33 folder on that machine. Could you help me figure out, what can be the problem?

I use Python 3.3 (win32) on Windows 8.1 x64 for packaging and try to run the exe on a Windows 7 x64 machine for running. And I use the following command for producing the exe file:

pyinstaller test.py --onedir --log-level=DEBUG --hidden-import=scipy.linalg --hidden-import=scipy.linalg.cython_blas --hidden-import=scipy.linalg.cython_lapack --hidden-import=scipy.integrate --hidden-import=h5py._errors --hidden-import=h5py.defs --hidden-import=h5py.utils --hidden-import=h5py.h5ac --hidden-import=h5py._proxy --hidden-import=tkinter.filedialog

Thanks for your help in advance!
Cheers!
Csega"

**Comment by tallforasmurf** [comment]
No quick fix from me, just the observation that these both relate to the boot-loader process, for example pyi_rth_qt5 is a "run-time hook" setting up for PyQt5. Suggest you add the --debug option, it causes the bootloader to emit a lot of info during startup. Then compare the output running on the dev. system and on the test system.

**Comment by Csega** [comment]
Thanks for the fast reply. Here is what my dev system prints out with the --debug option:

> .\test.exe --debug
PyInstaller Bootloader 3.x
LOADER: executable is [...]\test\dist\test\test.exe
LOADER: homepath is[...]\test\dist\test
LOADER: _MEIPASS2 is NULL
LOADER: archivename is [...]\test\dist\test\test.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory([...]\test\dist\test)
LOADER: Already in the child - running user's code.
LOADER: Python library: [...]\test\dist\test\python33.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is [...]\test\dist\test\base_library.zip;[...]\test\dist\test
LOADER: sys.prefix is [...]\test\dist\test
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is [...]\test\base_library.zip;[...]\test\dist\test
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_mplconfig.py
LOADER: Running pyi_rth_mpldata.py
LOADER: Running pyi_rth_win32comgenpy.py
LOADER: Running pyi_rth_qt5.py
LOADER: Running pyi_rth_qt5plugins.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running test.py

And at the exit:

LOADER: OK.
LOADER: Cleaning up Python interpreter.

The test machine prints the following message (the same as without the --debug option):

Traceback (most recent call last):
File "<string>", line 56, in <module>
File "c:\Python33\lib\site-packages\pyinstaller-3.1.dev0-py3.3.egg\PyInstaller
\loader\pyimod03_importers.py", line 548, in load_module
ImportError: DLL load failed: The specified module could not be found.
pyi_rth_qt5 returned -1

**Comment by htgoebel** [comment]
@MartinCharlis @Csega Could you please use one of the `straces` (see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) and try to figure out which DLL is been searched.

**Comment by MartinCharlis** [comment]
Thanks for the fast reply. But I found exactly my problem here:
https://github.com/pyinstaller/pyinstaller/issues/1671

thanks again....

**Comment by Csega** [comment]
@htgoebel I managed to figure out which dlls are missing on the test machine (I used DependencyWalker):

API-MS-WIN-APPMODEL-RUNTIME-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ERROR-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-ROBUFFER-L1-1-0.DLL
API-MS-WIN-CORE-WINRT-STRING-L1-1-0.DLL
API-MS-WIN-SHCORE-SCALING-L1-1-1.DLL
DCOMP.DLL
GPSVC.DLL
IESHIMS.DLL

Then, I ran the DependencyWalker on the dev machine, and there there were three dlls, which were missing (the program runs there perfectly):
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL

Do you know, which dlls are these and how can I get them?

**Comment by Csega** [comment]
It seems, I've found the root of the error. I found the dlls, which weren't copied to the folder next to the exe. I copied them and now everything works fine.

**Comment by htgoebel** [comment]
Do you want to share your knowledge?

**Comment by Csega** [comment]
I just figured out, which dlls could be missing. They belonged to the cv2 python module, which I compiled myself. I copied the dlls to the directory, where the .exe file was, and it worked. :)

**Comment by crazyxprogrammer** [comment]
I am also facing exact same problem but I am not able to find the solution using the discussion above
@Csega Please describe your approach (In my case also there is an error for cv2). How u find the required dll for solving this error

**Comment by TensorTom** [comment]
I'm having this problem with paths and cv2 but there is no DLL. I'm using the pyinstaller onefile option.
