### ISSUE TITLE
Document typespec `EXTENSION` for TOC?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1686]
Follow-up to https://github.com/pyinstaller/pyinstaller/issues/1676#issuecomment-158534054:

DATA and BINARY entries get their destination-names normalized. So if on needs to keep the case, he/she needs to change the typecode into EXTENSION -- which is what cyton compiled modules actually are.

For this reason we should include `EXTENSION` in the short list in https://pythonhosted.org/PyInstaller/#id77

**Comment by tallforasmurf** [comment]
#e3dcf94 removes obsolete info about name normalization
