### ISSUE TITLE
with UPX - Could not find or load QT platform plugin "windows"

### ISSUE THREAD

**Issue by JMSwag** [pyinstaller/pyinstaller#1688]
This application failed to start because it could not find or load the Qt platform plugin "windows".

No warnings in debug output.

Python: 3.4.3
PyInstaller: Latest development branch
PyQt: 5.5.1
Platfrom: Win 7 SP1 - Runs fine on Mac 10.9 - 10.11
Example app & pyinstaller output: https://gist.github.com/JMSwag/54f15d33ac4a8516cb71

I get the same result in onedir & onefile modes

Using --noupx it runs fine. I can live with the 5mb difference but thought the team should be aware.
I'm ok with this being closed if deemed a non issue.

**Comment by AcidWeb** [comment]
UPX is corrupting some of QT DLLs.

**Comment by matysek** [comment]
@JMSwag and @AcidWeb do you have any suggestion if there any better upx options that would not corrupt qt plugins?

**Comment by JMSwag** [comment]
@matysek I'll test out [CExe](http://www.scottlu.com/Content/CExe.html) and report back.

**Comment by AcidWeb** [comment]
@matysek I not found any combination of upx options that don't damage qwindows.dll.

**Comment by ChadSki** [comment]
This issue still repros for me.

While using folder output, I can simply `upx -d qt5_plugins\platforms\qwindows.dll` to uncompress the faulty library.

How can I workaround this problem when using single-exe output? Is there a way to specify that upx should compress every dynamic library _except_ qwindows.dll?

**Comment by weyou** [comment]
I also come across this issue.  May Pyinstaller provide an option to ignore the compress for some dll/exe.  For example: 
     upx_excludes=[...]

**Comment by htgoebel** [comment]
I'm closing this ticket, see the followup #2659.

**Comment by dickreuter** [comment]
Looks like this issue is still not resolved
