### ISSUE TITLE
pyinstaller 32 bit output detect as virus

### ISSUE THREAD

**Issue by goldalworming** [pyinstaller/pyinstaller#1692]
Hi, I compiled my python code to two version. 32bit and 64bit. in 64, output run well and no virus alert (avast) but the output of the same code of 32 bit result malware-gen in avast.

please give solution for 32 bit.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is nothing(!) we con do here.

See [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
