### ISSUE TITLE
Support module replacement trick

### ISSUE THREAD

**Issue by dimaqq** [pyinstaller/pyinstaller#1697]
I wish pyinstaller supported the module-replacement-with-object-at-loading-time, per http://stackoverflow.com/a/7668273

Here's a simplest possible example, library `lib`

```py
# lib.py
import sys

class Lib(object):
    @property
    def foo(self):
        return 42

sys.modules[__name__] = Lib()
```

 and its user `main`:

```py
# main.py
import lib

print lib.foo
```

**Comment by dimaqq** [comment]
P.S.
I saw that fail in PyInstaller==2.1
I was unable to test in PyInstaller==3.0 because that fails for me with `rfind` something
I can see that there's a test now for this specific usage: pyinstaller/tests/functional/modules/pyi_testmod_dynamic.py

**Comment by htgoebel** [comment]
PyInstaller 2.1 is out-dated and we no longer support it.
As you write, for PyInstaller 3.0 we have a test-case, which passes fine here.

I'm closing this ticket. I you still have some problem, please provide more information, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
