### ISSUE TITLE
Wrapping pip 7.1.2 fails - USER_SITE == None

### ISSUE THREAD

**Issue by virtuald** [pyinstaller/pyinstaller#1699]
Can be demonstrated very easily on linux via:

    pyinstaller --clean -F `which pip`

And that generates the following stack trace:

```
root@87ba95481f9c:~# dist/pip 
Traceback (most recent call last):
  File "<string>", line 7, in <module>
  File "/tmp/pip-build-2K5lpH/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 364, in load_module
  File "/usr/local/lib/python2.7/dist-packages/pip/__init__.py", line 13, in <module>
    from pip.utils import get_installed_distributions, get_prog
  File "/tmp/pip-build-2K5lpH/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 364, in load_module
  File "/usr/local/lib/python2.7/dist-packages/pip/utils/__init__.py", line 19, in <module>
    from pip.locations import (
  File "/tmp/pip-build-2K5lpH/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 364, in load_module
  File "/usr/local/lib/python2.7/dist-packages/pip/locations.py", line 144, in <module>
    bin_user = os.path.join(user_site, 'bin')
  File "/usr/lib/python2.7/posixpath.py", line 77, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
pip returned -1
```

It looks like what's happening is the site.USER_SITE value is None, and pip expects it to be a string.

Of course, one might ask why would you want to wrap pip? Well, we're using the pip api from our application, and it fails in the same way because of this bug.

I suspect this is really a bug in pip, and I'll file the bug over there also. But, hard to say.

Packages: Ubuntu 14.04: Python 2.7.6; pip 7.1.2; pyinstaller latest develop as of this writing

**Comment by matysek** [comment]
* @virtuald The goal of pyinstaller is to have `site-packages` disabled. Is there any value that `USER_SITE` could be set to and also indicate to all python code that `site-packages` is disabled?
* If not then this issue should be closed as `won't fix`.

**Comment by virtuald** [comment]
I don't really know what the right answer here is. I know for us, we set the value of site.USER_SITE to an empty string and it seems to work just fine for me.

Perhaps one solution could be a runtime hook checking for an import of `pip`, at which point you could set the USER_SITE to an empty string, or perhaps set it to an empty temporary directory?

**Comment by matysek** [comment]
@virtuald I don't wan't to change globally `site.USER_SITE` just because of one package.

Better solution would be to create rthook for pip and override the value USER_SITE in pip directly. Override the `user_site = site.USER_SITE` value in `pip/locations.py` file.

**Comment by virtuald** [comment]
That would be fine, but the code is executed at the toplevel module of pip, so you can't actually import `locations.py`.

**Comment by matysek** [comment]
* Well, this is more political than technical issue.
* @htgoebel and @codewarrior0 what do you think about setting `USER_SITE` to empty string in our `fake-site.py`?
* It looks like it should not hurt in general. I tried to run python with options `-s -S` and this is what I got:
```
$ python -S -s 
Python 2.7.10 (default, Sep  8 2015, 17:20:17) 
[GCC 5.1.1 20150618 (Red Hat 5.1.1-4)] on linux2
>>> import site
>>> site.ENABLE_USER_SITE
False
>>> site.USER_SITE
'/home/user/.local/lib/python2.7/site-packages'
>>> 
```

**Comment by virtuald** [comment]
I would advocate for adding a runtime hook that whenever pip is imported, it sets the USER_SITE to an empty string.

**Comment by htgoebel** [comment]
@matysek Would be fine for me. We'll see, if this breaks other thing, tough :-)

**Comment by matysek** [comment]
I did that change and these are my CI jobs before pushing to main tree:
* https://ci.appveyor.com/project/matysek/pyinstaller-ewwmo/build/199
* https://travis-ci.org/matysek/pyinstaller/builds/97518693

**Comment by matysek** [comment]
Tests passed then it seems ok.

**Comment by matysek** [comment]
@virtuald please test if that works for you.

**Comment by codewarrior0** [comment]
> @codewarrior0 what do you think about setting USER_SITE to empty string in our fake-site.py?

I think it should be fine.
