### ISSUE TITLE
`__path__` not respected during imports?

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#1704]
In working on #1601 and #1703, I've run into another potential bug I don't know how to fix. It appears that PyInstaller doesn't respect a module's `__path__` attribute when doing imports. In particular, I noticed the following:

wxPython's pubsub module provides three APIs (v1, v2, and v3; only v1 and v3 are documented at http://wiki.wxpython.org/WxLibPubSub). The filesystem looks like:

```
wx/lib/pubsub:
   pub.py - The v3 API.
   pubsub1/pub.py - the v1 API.
   pubsub2/pub.py - the v2 API.
```

When importing `wx.lib.pubsub`, its `__init__.py` imports `pubsubconf.py`, which calls `setVersion(1)`, which adds `pubsub1/` to the `__path__`. Then, `__setupForV1()` does an `import pub`, which *should* import `pubsub1/pub.py`; CPython does this. However, the frozen binary produced by PyInstaller imports `pub.py`, the v3 API, causing later failures.

To demonstrate this, I added these lines to `wx.lib.pubsub.pubsubconf` beginning at line 83; I'm using wxPython 2.8.12.1:

``` Python
        print(self.__searchPaths)
        print(pub.__file__)
```

Output from CPython:
```
['C:\\Python27\\lib\\site-packages\\wx-2.8-msw-unicode\\wx\\lib\\pubsub\\pubsub1', 'C:\\Python27\\li
b\\site-packages\\wx-2.8-msw-unicode\\wx\\lib\\pubsub']
C:\Python27\lib\site-packages\wx-2.8-msw-unicode\wx\lib\pubsub\pubsub1\pub.pyc
```
The first list gives `__path__`, which lists the `pubsub1/` subdirectory first, and shows that `pub.pyc` was imported from that subdirectory.

Output from PyInstaller:
```
['c:\\users\\bjones\\appdata\\local\\temp\\pytest-of-bjones\\pytest-299\\test_wx_lib_pubsub_protocol
_de0\\dist\\wx_lib_pubsub\\wx\\lib\\pubsub\\pubsub1', 'c:\\users\\bjones\\appdata\\local\\temp\\pyte
st-of-bjones\\pytest-299\\test_wx_lib_pubsub_protocol_de0\\dist\\wx_lib_pubsub\\wx\\lib\\pubsub']
c:\users\bjones\appdata\local\temp\pytest-of-bjones\pytest-299\test_wx_lib_pubsub_protocol_de0\dist\
wx_lib_pubsub\wx\lib\pubsub\pub.pyc
```

While the first entry, which returns `__path__`, puts the `pubsub1/` subdirectory first, the actual `pub.pyc` comes not from this subdirectory, but from the root directory.

**Comment by codewarrior0** [comment]
I was working on this a while back. `__path__` is in fact respected, but what's happening is that the .py files included as data-files are only searched after the FrozenImporter is unable to find them. Yet, FrozenImporter finds the v3 `pub.py` without allowing the filesystem importer to find the v1 `pub.py`. So the search order goes:

```
PYZ/wx/lib/pubsub/pubsub1
PYZ/wx/lib/pubsub   # v3 pubsub is found here
_MEIPASS/wx/lib/pubsub/pubsub1  # v1 pubsub should be found here
_MEIPASS/wx/lib/pubsub
```

I made an attempt at changing FrozenImporter to fall back to the filesystem importer for each element in `__path__`. It was kind of ugly and I can now see why @htgoebel called it a hack to change FrozenImporter to respect `__path__`. Ideally we would just freeze `pubsub/pubsub1/pub.py` as `pubsub/pub.py`, "baking" the path override into the frozen python files.

**Comment by bjones1** [comment]
@codewarrior0, thanks -- that's a very helpful explanation. Since this sounds like a hard bug to fix, I would suggest:

1. Marking the failing wxPython tests as xFail (only for 2.8.10 <= wxPython version < 2.9).
2. Creating some unit tests to expose the bug clearly, and marking them as xfail.

If you think this is a reasonable approach, I can work on these items, unless you'd like to take the lead.

**Comment by codewarrior0** [comment]
>Since this sounds like a hard bug to fix

I think this bug spawned a 100-comment discussion on a pull request a few months ago. We were trying all kinds of approaches to predict the way `__path__` would be modified and freeze the v1 files in the places where the v3 files normally go, and each approach seemed to require more intensive changes than the last one. In the middle of that, I added the `__path__` handling to FrozenImporter to solve one of the problems, but the other problem is that some of the folders in pubsub aren't actually python packages. This means modulegraph won't import them so we can't use hiddenimports *or* collect_submodules to find them, so I ended up adding the pyfiles as data files.

Another possible solution, given where we are at now, would be a way to add the files in these non-package folders to the PYZ as regular python modules, so the current FrozenImporter can find them via path overrides.

You can go ahead and work on the unit tests if you want. I was under the impression that the current wxPython tests already exposed the bug when running with wxPython 2.8.x.

**Comment by bjones1** [comment]
Are you referring to #1393? That's a long, confusing one...looking at older issues, #1367 seems relevant. 

> Ideally we would just freeze pubsub/pubsub1/pub.py as pubsub/pub.py, "baking" the path override into the frozen python files.

Is this possible to do in a hook? Or does this require editing the wxPython source?

> Another possible solution, given where we are at now, would be a way to add the files in these non-package folders to the PYZ as regular python modules, so the current FrozenImporter can find them via path overrides.

Finally, it seems like the tests should be marked as xfail -- what haven't they been? Am I missing something?

> You can go ahead and work on the unit tests if you want. I was under the impression that the current wxPython tests already exposed the bug when running with wxPython 2.8.x.

I think having a simple, clear test case might be helpful for future work on this, or at least to clearly show the bug. I'll put it together.

**Comment by codewarrior0** [comment]
> Is this possible to do in a hook? Or does this require editing the wxPython source?

Hooks were the first attempt. We were having problems predicting which folders are added as path overrides, if any were at all, because they depended on the order in which certain pubsub modules are imported, and this ordering isn't visible to us from modulegraph's static analysis. 

I don't think editing the wxPython source would help us, but looking at the source, it may be intended for the user to remove `autosetuppubsubv1` (and probably a couple of others) from the installed library, so that's another edge case to consider.

> Finally, it seems like the tests should be marked as xfail -- what haven't they been? Am I missing something?

Pretty sure that's because the CI systems only install wx versions 2.9 or newer, and the tests only fail with 2.8.x.

**Comment by bjones1** [comment]
Closing this -- the presence of an xfail test should be a good place for future work to start from.
