### ISSUE TITLE
Python 3.5 code compiled with PyInstaller 3.0 crashes running under code page 65001 on Windows

### ISSUE THREAD

**Issue by ShaiWavesAudio** [pyinstaller/pyinstaller#1705]
I'm compiling a command line application using PyInstaller 3.0 with python 3.5 on Windows.

When I run the application under CMD.EXE configured for **code page 65001**, the compiled executable will not run, with the message:

Fatal Python error: Py_Initialize: can't initialize sys standard streams
LookupError: unknown encoding: cp65001

If CMD.EXE is configured for it's default code page (437) the compiled executable will run without problem.

The program can be as small as 
``` python
print("")
```

without any import statements.

What I already tried:

* inserted the following code as the very first thing my application calls:
``` python
 import codecs
 codecs.register(lambda name: codecs.lookup('utf-8') if name == 'cp65001' else None)
```
* Called 'chcp 65001' before compiling with PyInstaller, so the whole compilation is done under code page 65001

* Ran cmd.exe in admin mode

These did not solve the problem.

System information:

* Windows 7 Enterprise, Service Pack 1
* Python 3.5
* PyInstaller 3.0
* The command I use to change the code page: chcp 65001

**Comment by codewarrior0** [comment]
Running python itself in a `chcp 65001` command window works as expected.

The module `encodings.cp65001` is correctly bundled into `base_library.zip`. Modifying the encodings module with debug info reveals the root of this problem: an error while importing `encodings.cp65001`.

```
Fatal Python error: Py_Initialize: can't initialize sys standard streams
Traceback (most recent call last):
  File "[...]\lib\encodings\__init__.py", line 100, in search_function
    level=0)
  File "[...]\lib\encodings\cp65001.py", line 6, in <module>
    import functools
ImportError: No module named 'functools'
```

Either the `functools` module should be explicitly included in `base_library.zip`, or any modules added to the base library need to be recursively scanned for imports, and these imports also added to the base library. 

In fact, the modules *are* recursively scanned in `initialize_modgraph`, but any new modules found are excluded in `create_py3_base_library` using a regular expression.

**Comment by ShaiWavesAudio** [comment]
codewarrior0 thanks. As I'm new to PyInstaller, is there a workaround on my side? Should I include some code in my spec file?

**Comment by codewarrior0** [comment]
I don't think there's a simple workaround. We'll have to update `compat.PY3_BASE_MODULES` to include the needed modules. This bug appears to affect Python 3.4 too.

**Comment by htgoebel** [comment]
You could try adding `functools` to `--hiddenimports`. Well, this does not get it into `base_library.zip`, so it may not succeed.

**Comment by ShaiWavesAudio** [comment]
Since I cannot release my product without support for code page 65001 on Windows, I tried solving the problem by adding functools to compat.PY3_BASE_MODULES.
functools required adding collections. So I also added collections to compat.PY3_BASE_MODULES. But I'm still getting the same error since collections  needs distutils, which I also added.
However now the *compilation* fails saying:
ImportError: No module named 'distutils.command' 

I would like to investigate more but can anyone give me directions on how to solve this?

**Comment by matysek** [comment]
@ShaiWavesAudio could you try first your app with command `python -v` to see what all `distutils` dependencies your app needs and then add them to PY3_BASE_MODULES?

**Comment by ShaiWavesAudio** [comment]
My own app does not use distutils at all. It looks like pyinstaller is using it and fails to import it correctly. Attached is my revised compat.py and the output from calling PyInstaller:


[pyinstaller.out.txt](https://github.com/pyinstaller/pyinstaller/files/61028/pyinstaller.out.txt)

[compat.py.txt](https://github.com/pyinstaller/pyinstaller/files/61031/compat.py.txt)

**Comment by ShaiWavesAudio** [comment]
Any news on this issue? Until it's fixed I'm forced to downgrade to python 2.7 and PyInstaller 2.1. I'm willing to help solve this, but need direction as what to do, having tried all the above suggestions. Thanks.

**Comment by codewarrior0** [comment]
Taking a look at this now.

**Comment by codewarrior0** [comment]
This should be fixed in e7fc427c635eba563d0e6fcdc6208f846f8f84c4.

You're welcome to check out the `develop` branch and confirm the fix.

**Comment by ShaiWavesAudio** [comment]
Yes it's fixed! Great work everyone, and many thanks. When is 3.1 being released?

**Comment by htgoebel** [comment]
> When is 3.1 being released?

This is planned to happen within the next few days.
