### ISSUE TITLE
copy_metadata() - document usage of this function

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1706]
* In pull request #1700 was introduced function `copy_metadata()` that allows fixing pkg_resources for some packages.
* Usage of this function should be documented in manual.
* For example of this function see hook `hook-logilab.py`.

**Comment by matysek** [comment]
@tallforasmurf could you please take care of this?

**Comment by tallforasmurf** [comment]
The comments in copy_metadata() indicate that (1) some packages have metadata that is not part of an egg, and (2) some do not have metadata folders at all. However the code does not appear to allow for either of these cases?

Here is what I propose to add, however I would also like to say what is returned if 'package-name' does not have a metadata folder. (Or should the call be in a try/except?)

> copy_metadata( 'package-name' ):

>    Given the name of a package, return the name of its distribution metadata folder as
> a list of tuples ready to be assigned (or appended) to the datas global variable.
> Not all packages have distribution metadata.
> When it exists it is normally a folder with a name ending in `-info` somewhere
> in the site-packages folder.
> The tuple returned has two strings.
> The first is the full pathname to the folder in this system.
> The second is the folder name only.
> When this tuple is added to datas, the folder will be bundled at the top level.

**Comment by bjones1** [comment]
@tallforasmurf, thanks for working on this! This function shouldn't be invoked if there's no metadata to copy. It supports all metadata formats except zipped eggs.

My suggestions:

# `copy_metadata(package-name)`

Given the name of a distribution as a string, this function returns the name of its distribution metadata folder as a list of tuples ready to be assigned (or appended) to the `datas` global variable. The tuple returned has two strings: 

  The first is the full pathname to the folder in this system.
  The second is the folder name only.

When this tuple is added to `datas`, the folder will be bundled at the top level. An `AssertionError` will be raised if the given distribution does not exist; in the most common case, a package may not be accompanied by the metadata in a distribution.

## Background

The (pkg_resources)[https://pythonhosted.org/setuptools/pkg_resources.html] package provides a commonly-used means of accessing metadata, such as the package's version, of a distribution. By default, PyInstaller does not include this metadata when freezing an application. Packages which depend on this metadata will therefore fail with errors such as **oops, I can't find this old errors message -- re-create it by deleting the call to copy_metadata in hook-logilab**. To fix this, create a hook file which invokes `copy_metadata`. For example, the `logilab` package's distribution is named [logilab-common](https://pypi.python.org/pypi/logilab-common/); `hook-logilab.py` includes `datas = copy_metadata('logilab-common'`, which copies the appropriate folder containing logilab-common's metadata to the frozen executable.

**Comment by tallforasmurf** [comment]
Thanks, I'll put this in when I get back from a business trip on wednesday

**Comment by tallforasmurf** [comment]
n.b. if anyone wonders why I never push the Manual.pdf as well, it's because I can't get rst2pdf to work. It dies somewhere in the "reportlab" package with a "broken pipe".
