### ISSUE TITLE
Recent PyGObject changes break GStreamer on OS X with Homebrew

### ISSUE THREAD

**Issue by cbenhagen** [pyinstaller/pyinstaller#1709]
@virtuald:

I finally managed to track down the issues that lead to my errors with the recent PyGObject changes. 

Before i try to fix them myself I think it makes sense for you to have a quick look at this. I guess you might be able to fix it in a cleaner way as you are already familiar with the matter.

- `hook-gi.repository.Gst` is missing the hidden import of `gi.repository.Gio`.
  - I would simply add `hiddenimports += ['gi.repository.Gio']` but I guess you will find a nicer solution.

- `hook-gi.repository.Gio` fails to collect `gio_modules` which leads to GStreamer being unable to do neworking stuff.
  - This is because libdir is returned as `/usr/local/opt/glib/lib` instead of `/usr/local/opt/glib-networking/lib` or even better just `/usr/local/lib/`.

**Comment by cbenhagen** [comment]
In case you need a simple testcase:

```Python
#!/usr/bin/env python
import sys
import time

import gi
gi.require_version('Gst', '1.0')

from gi.repository import Gst

Gst.init(sys.argv)

player = Gst.ElementFactory.make("playbin", "player")
audiosink = Gst.ElementFactory.make("autoaudiosink", "audiosink")
player.set_property("audio-sink", audiosink)

player.set_property("uri", 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg')
player.set_state(Gst.State.PLAYING)

time.sleep(10)
```

**Comment by virtuald** [comment]
Have you tried [this branch](https://github.com/virtuald/pyinstaller/tree/exaile)? That has all of my fixes merged into it, and I was able to build a fairly complex application with it without any problems.

**Comment by cbenhagen** [comment]
I just tried it now and got the same error:

```
souphttpsrc gstsouphttpsrc.c:1556:gst_soup_http_src_parse_status:<source> error: TLS/SSL support not available; install glib-networking (6), URL: https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg, Redirect to: (NULL)
```

**Comment by virtuald** [comment]
Thinking about it, I haven't tried it with homebrew, I might be able to look at it tonight, but I have to go for a few hours now. What are the absolute locations of:

* libgio.*.dylib
* gio_modules

**Comment by virtuald** [comment]
My guess is that since the plugin is bringing in `Gio`, that it is indeed a hidden import that won't be declared by the `Gst` typelib (though I haven't checked) and we'll need to add Gio to the hidden import list. However, I wonder if there's a way to discover the requirements of the various plugins -- otherwise this could happen for other things too (though, Gio is such a basic requirement that it's probably ok to add to the hidden imports here).

**Comment by cbenhagen** [comment]
They get linked to `/usr/local/lib/libgio-2.0.0.dylib` and `/usr/local/lib/gio/modules/`.

**Comment by virtuald** [comment]
I'm having issues running your script in a non-frozen state. Oddly enough, on linux your script works fine. However, running on OSX, I get the TLS error that you get (once again, without pyinstaller involved).

**Comment by virtuald** [comment]
Ah, [--with-libogg and --with-vorbis needs to be specified when installing.. weird](https://github.com/Homebrew/homebrew/issues/32400). Now it works, but I'm getting some odd pyinstaller related bugs.

**Comment by virtuald** [comment]
@cbenhagen I ran into some other issues and added fixes for those. I also restored the previous GIR search behavior if the modules aren't found relative to the gio library. 

The exaile branch in my repo has been updated as well, try it out and let me know if it works for you.

**Comment by cbenhagen** [comment]
Awesome! You are my hero! :)
