### ISSUE TITLE
Code-signed executables with Tk do not work

### ISSUE THREAD

**Issue by rasky** [pyinstaller/pyinstaller#171]
**Original date**: 2010/04/01

PyInstaller projects using Tk support (Makespec --tk) are broken when using code-signing.

There are two possible fixes here, and both should be eventually done:

 - Remove the explicit support for Tk and rely on the new infrastructure of data files from hooks to package Tk data files.
 - Make CArchive compatible with code-signed executables, for users attempting runtime extraction of data.

**Comment by matysek** [comment]
Duplicate of pull request #1075
