### ISSUE TITLE
GLib MainLoop is broken

### ISSUE THREAD

**Issue by cbenhagen** [pyinstaller/pyinstaller#1710]
While this simple testcase runs as expected when run from the commandline it does break with the following output:

```Python
Traceback (most recent call last):
  File "<string>", line 34, in <module>
  File "/usr/local/Cellar/pygobject3/3.18.2/lib/python2.7/site-packages/gi/module.py", line 137, in __getattr__
    self.__name__, name))
AttributeError: 'gi.repository.GObject' object has no attribute 'MainLoop'
```

Changing the depreciated `GObject.MainLoop()` to `GLib.MainLoop()` does again work on the commandline but gives the following error:

```Python
Traceback (most recent call last):
  File "<string>", line 34, in <module>
TypeError: GLib.MainLoop.new() takes exactly 2 arguments (0 given)
```

I tested this with the master and develop branch of PyInstaller. This is why I think this is not related to this issue: https://github.com/pyinstaller/pyinstaller/issues/1709

Testcase:

```Python
#!/usr/bin/env python
import sys

import gi

gi.require_version('Gst', '1.0')
from gi.repository import Gst, GObject

Gst.init(sys.argv)


def on_message(bus, message):
    t = message.type
    if t == Gst.MessageType.EOS:
        player.set_state(Gst.State.NULL)
        sys.exit()
    elif t == Gst.MessageType.ERROR:
        player.set_state(Gst.State.NULL)
        err, debug = message.parse_error()
        print "Error: %s" % err, debug


player = Gst.ElementFactory.make("playbin", "player")
audiosink = Gst.ElementFactory.make("autoaudiosink", "audiosink")
player.set_property("audio-sink", audiosink)

bus = player.get_bus()
bus.add_signal_watch()
bus.connect("message", on_message)

player.set_property("uri", 'https://upload.wikimedia.org/wikipedia/commons/c/c8/Example.ogg')
player.set_state(Gst.State.PLAYING)

mainloop = GObject.MainLoop()
mainloop.run()
```

**Comment by virtuald** [comment]
Mainloop is probably broken because the overrides aren't being brought in properly (see definition of mainloop in [gi.overrides.GLib](https://github.com/GNOME/pygobject/blob/master/gi/overrides/GLib.py). You must have #1689 merged for overrides to work properly.

**Comment by cbenhagen** [comment]
I just tried it with your exaile branch and it worked. Or at least it works as much as the simpler example in https://github.com/pyinstaller/pyinstaller/issues/1709.

I am leaving this open until https://github.com/pyinstaller/pyinstaller/pull/1689 gets merged so that it is easier to find for people who run into the same issue.

**Comment by cbenhagen** [comment]
Thank you for fixing this @virtuald !
