### ISSUE TITLE
Pyinstaller Assistant Packaging -- not an issue

### ISSUE THREAD

**Issue by douglasmccormickjr** [pyinstaller/pyinstaller#1715]
Hi there Pyinstaller people,

I've built a couple of tools to help streamline the building and application packaging process behind PyInstaller.  I'd like to release them into the wild (under MIT license -- it would link all the tools.parts together) but I don't want it to just linger out there with no one finding it or using it for that matter.  These tools make it considerably easier for users to generate apps with python (primarily, I've been working more in the windows world, it could be ported to OSX too though).

Besides me further "prepping it up" (I'm nearly done with that part) would there be a good place to add this "assisting tool" into the PyInstaller project?  I'd like to know what you guys think

Thanks so much,
-Doug Jr.

**Comment by matysek** [comment]
@douglasmccormickjr you have several options:
* Use this wiki page: https://github.com/pyinstaller/pyinstaller/wiki/Projects-Using-PyInstaller
* write to pyinstaller mailing list or python announce list
* If your tool proves to be useful then it could be mentioned in the PyInstaller manual.

Question is if your long-term goal is to integrate your tools into pyinstaller or keep it as separate tool. I you'd like to integrate it then the required license would be probably GPL.
