### ISSUE TITLE
Django 1.9 compatibility

### ISSUE THREAD

**Issue by jordanorc** [pyinstaller/pyinstaller#1717]
When trying to use Pyinstaller with Django 1.9 it seems not find templatetags and the following exception is raised:
- 'i18n' is not a registered tag library. Must be one of: 

Note that it doesn't list any of default templatetags. 

I tried on Pyinstaller 3.0 and 3.1.dev0.

**Comment by matysek** [comment]
Latest tested Django version is 1.8. We will have to find out what changes are in Django 1.9. Pull requests are welcome.

**Comment by linville** [comment]
I had a similar issues with static files and a custom tag library that were not being registered. I have worked around the issue by just modifying the app's `settings.py` to load the required template tag libraries-

    'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries': {
                'staticfiles' : 'django.templatetags.static',
                'i18n' : 'django.templatetags.i18n',
            },
        },

Further information-
* There was a pull request in Django that describes the new API in detail: django/django#4657
* The Django source for `Template::get_installed_libraries()` itself alludes to the new [Template Library API](https://docs.djangoproject.com/en/1.9/_modules/django/template/backends/django/).

**Comment by jordanorc** [comment]
The problem is in function `get_package_libraries` in module `django.template.backends.django.py`. It uses `walk_packages` from `pkgutil`. The problem here is `pkg.__path__` points to a folder that doesn't contains python source. I don`t know yet how to solve the problem. 

Any ideas?

**Comment by roboslone** [comment]
Bump. Also, Django 1.10 was released [couple of months ago](https://docs.djangoproject.com/en/1.10/releases/1.10/).

**Comment by franciscod** [comment]
After adding a lot of `*.templatetags.*` modules, I hacked this: #2441. Apparently it works. Check it out!

**Comment by bwoodsend** [comment]
Closing as we no longer support django1.x. If this issue persists in django2.x then raise a new issue.
