### ISSUE TITLE
making pyinstaller work with boto3

### ISSUE THREAD

**Issue by amitm02** [pyinstaller/pyinstaller#1723]
How can i get pyinstaller to work with boto3?
I'be seen a thread about boto3 hook, but i'm not clear about what i actually need to do to make it work..
Currently I get:
File "/usr/local/lib/python2.7/site-packages/botocore/loaders.py", line 313, in list_api_versions
    raise DataNotFoundError(data_path=service_name)
botocore.exceptions.DataNotFoundError: Unable to load data for: s3

Thanks all

**Comment by matysek** [comment]
Use the `develop` version of pyinstaller. And if that does not work then report new issue or try to fix the boto3 hooks.

**Comment by amitm02** [comment]
works!
thanks

**Comment by 636express** [comment]
I had the same problem. Problem solved by using PyInstaller==3.1.dev0. 

Thank you PyInstaller Team!!!
