### ISSUE TITLE
Document new Analysis() argument 'strip_paths'

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1725]
Recently the issue #1724 was fixed and new .spec argument `strip_paths` was introduced in commit.
https://github.com/codewarrior0/pyinstaller/commit/93d25e563e49f88f5977afd9b6e26cb34bfb5efa

This should be documented in the manual.

**Comment by tallforasmurf** [comment]
assign it to me, I'll get to it this week.

**Comment by htgoebel** [comment]
I vote against using this option at all, see https://github.com/codewarrior0/pyinstaller/commit/93d25e563e49f88f5977afd9b6e26cb34bfb5efa#commitcomment-15009644

**Comment by matysek** [comment]
@codewarrior0 Could you please decide whether you want to keep `strip_paths` or not?

If not, please close it as won't fix. If yes then reassign it to tallorasmurf. Thanks.

**Comment by codewarrior0** [comment]
`strip_paths` is gone. We can bring it back if there is actual demand.
