### ISSUE TITLE
Local files relative to PyInstaller bundle (onefile mode)

### ISSUE THREAD

**Issue by diannall** [pyinstaller/pyinstaller#1726]
I am building a small app that will be loaded on to a user's machine and it will need to look in the same directory as the bundle for specific mp3 files. These mp3 files will not be bundled with the py file, so I don't need the sys._MEIPASS path, but just the system path to the bundle itself. We need a small app to modify specific mp3 id3 tags for users. The mp3s will be on their local machine or a usb drive. My idea is to just drop the script where the mp3s are and run it.

This is what I have tried...

        if getattr(sys, 'frozen', False):
            basedir = sys._MEIPASS
        else:
            basedir = os.path.dirname(os.path.abspath(__file__))

        mp3path = basedir + "/test.mp3"

When I test before building, it gives me the correct path:

        /Users/name/path/to/file/test.mp3

When I run the bundle, the mp3 path is:

        /var/folders/d8/67z60y2x7c73kk_m0w50w2pr0000gp/T/_MEI9qySOb/test.mp3

When I just use the dirname from `__file__`, the path is my user folder

        /Users/name/test.mp3

Essentially, if the mp3s are in

        /Users/name/Desktop/mp3s

The app should be dropped in that location and it will fine the mp3 files it needs.

**Comment by tallforasmurf** [comment]
The code you show for setting basedir is for setting the location of the executing app, and by implication anything bundled with it. (In a one-file bundle, the place you "drop the app" is not from whence it executes; as described in the doc, the one-file app expands into a temp folder before executing.

However you want to find files based on the user's preferred directory, which is not necessarily the same as the app location anyway (the user might well ignore your suggestion to drop the app with the files). Don't you want to use something like os.getcwd() ?

**Comment by diannall** [comment]
Thanks, but getcwd() also just returns the home dir, not where the app is located.

**Comment by htgoebel** [comment]
Well, then a quick work-around would be to use a wrapper-batch-file witch sets an ENV var.

Or maybe `sys.argv[0]` is usable?

Otherwise you maybe could use windows- functions like `GetModuleFileNameW`. See `pyi_path_executable` in `bootloader/src/py_path.c`.

**Comment by matysek** [comment]
The trick with `sys.argv[0]` should work.
```python
basedir = os.path.dirname(sys.argv[0])
```
I think this trick should be mentioned in the manual for `onefile` mode.

@tallforasmurf could you please look at it?

**Comment by tallforasmurf** [comment]
I will, but I believe I will retain the name `basedir` for the location of the app and bundled files, and add the use of another name, maybe `launchdir` ? for the location from which the app was launched. These would be the same for a one-folder app, and different for a one-file app.

**Comment by codewarrior0** [comment]
Ah, you should actually use `sys.executable` for the location of the exe. It is more reliable because `sys.argv[0]` is set by the process that calls the exe. 

If the calling process is a shell, it can set argv[0] to just a plain filename if the exe was put in $PATH and called with just its filename.  argv[0] only contains a full path when the exe is launched via Windows Explorer or possibly other file managers (Finder, Nautilus, etc...).

**Comment by tallforasmurf** [comment]
Added lots of info on this as commit #030cf50 - comments welcome

**Comment by codewarrior0** [comment]
Nicely done! If there is anything to add, it's the two main use-cases that require `sys.executable` and `sys.argv[0]`:

**Symlinks.** The one in #1208 has a program that is symlinked with a bunch of different names, and the program behaves differently depending on which symlink was used to start the program. `sys.argv[0]` contains the name of the program as it was invoked, and is needed for this use-case. If you're familiar with [BusyBox](https://busybox.net/) then you know what this is for. This is mainly for shell users.

**Implicit working dir.** That's the one in this issue (and a couple of others):

> My idea is to just drop the script where the mp3s are and run it.

That is, put the program in a folder where it is going to work. To find the folder, you need `sys.executable` to get the actual, non-symlinked full path to the executable. This is mainly for GUI users. 

`sys.executable` is also useful when the program is meant to be in the same folder as its configuration files, data files, documents, etc. This is sometimes called a "portable install" and is useful for installing the app on a thumb drive, so the app's folder contains everything it needs.

**Comment by tallforasmurf** [comment]
Excellent point. I've added s'more wordz at https://github.com/pyinstaller/pyinstaller/commit/d4def20c7723fa1ff8a7e1f52c4ba4dadcb564c1

I'm tempted to close this but maybe somebody will see a typo or something...

**Comment by diannall** [comment]
Thanks so much for your help! `sys:executable` has worked great. 

For me, it was including the name of the app, so I had to strip that to get the directory name instead.
Here is the code I'm using:

    basedir = sys.executable
    last_dir = basedir.rfind("/")
    basedir = basedir[:last_dir]

**Comment by matysek** [comment]
> I'm tempted to close this but maybe somebody will see a typo or something...

@tallforasmurf don't hesitate, close it. There is always room for new issues ;-)

**Comment by htgoebel** [comment]
@diannall You want to use `os.path.dirname` instead of `rfind`.

**Comment by htgoebel** [comment]
@tallforasmurf Well done :-)

**Comment by diannall** [comment]
@htgoebel Oh yes, OF COURSE! My brain was off :)

**Comment by JithinPavithran** [comment]
I'm not able to add data files to `onefile` mode. Tried everything above. Tried in each folder specified in the [doc](https://pythonhosted.org/PyInstaller/runtime-information.html#using-sys-executable-and-sys-argv-0). The file is not found during execution.
This is very frustrating.

**Comment by tallforasmurf** [comment]
Did you actually try the small program `directories.py` shown in that section of the doc? Run it as a normal script (`python directories.py`). Then make a onefile bundle of it (`pyinstaller -F directories.py`) and run that.

If you have done that, please show,
1. some code how your app tries to locate the data file. Where does it look for the data?
2. how you tell pyinstaller about the data files

**Comment by htgoebel** [comment]
@JithinPavithran If you have problems, pelase open a *new* ticket. This one is about changes to the documentation.
