### ISSUE TITLE
Crypto.Cipher import error on OS X

### ISSUE THREAD

**Issue by wellu** [pyinstaller/pyinstaller#1728]
I'm running OS X El Capitan and using preinstalled Python 2.7.10. I've run

```
sudo easy_install pycrypto
```

to install crypto package. Then I have a trivial Python app that imports AES from Crypto.Cipher. Running it with

```
python Hello.py
```

works fine and prints the Hello World! line just fine so I believe crypto imports work. However if I run

```
pyinstaller -F Hello.py
```

and then

```
./dist/Hello
```

I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named Crypto.Cipher
Hello returned -1
````

pyinstaller itself works as I'm able to compile the same example code if I leave the crypto parts out.

The same steps work fine in Debian and Ubuntu using 2.7 Python. Any help appreciated. Example app attached but here is the source code also inlined:

```
from Crypto.Cipher import AES

obj = AES.new('This is a key123', AES.MODE_CBC, 'This is an IV456')
print "Hello World!"
```

I've tested the same code both on El Capitan and on Mountain Lion with the same exact result. For El Capitan I had to do some patching for the pyinstaller to make it work but that is another issue.

[Hello.zip](https://github.com/pyinstaller/pyinstaller/files/63998/Hello.zip)

**Comment by matysek** [comment]
Please try latest `develop` version. Both issues should be fixed there.

**Comment by wellu** [comment]
Ok, removed both pycrypto and pyinstaller packages under /Library/Python/2.7. Then I built and installed the latest develop with

```
sudo python setup.py install
```

after that I reinstalled pycrypto with the easy_install:

````
sudo easy_install pycrypto
```

Again, I can compile the Hello.py to binary but when I try to run it I get

````
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller-3.1.dev0_93d25e5-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 382, in load_module
    exec(bytecode, module.__dict__)
  File "build/bdist.macosx-10.11-intel/egg/Crypto/Cipher/AES.py", line 50, in <module>
  File "/Library/Python/2.7/site-packages/PyInstaller-3.1.dev0_93d25e5-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 382, in load_module
    exec(bytecode, module.__dict__)
  File "build/bdist.macosx-10.11-intel/egg/Crypto/Cipher/_AES.py", line 7, in <module>
  File "build/bdist.macosx-10.11-intel/egg/Crypto/Cipher/_AES.py", line 6, in __bootstrap__
ImportError: dlopen(/var/folders/b6/4ml3n4cd3k99k9w6r9qqcztm0000gn/T/_MEIMXRq7v/Crypto/Cipher/_AES.so, 2): image not found
Hello returned -1
```

**Comment by matysek** [comment]
@wellu Are you sure that the file `Crypto/Cipher/_AES.so` was really compiled when you did `sudo easy_install pycrypto`?  Do you have XCode installed?

**Comment by wellu** [comment]
I have XCode installed with command line tools. Also I can run the attached Hello.py with

```
python Hello.py
```

which means that pycrypto itself is working just fine. Once I compile Hello.py to binary then the import starts to fail. It seems to me that pyinstaller bundles the Python parts of the pycrypto library (e.g build/bdist.macosx-10.11-intel/egg/Crypto/Cipher/AES.py) but fails to include or locate the actual shared library.

Clearly this

```
ImportError: dlopen(/var/folders/b6/4ml3n4cd3k99k9w6r9qqcztm0000gn/T/_MEIMXRq7v/Crypto/Cipher/_AES.so, 2))
```

means that at runtime the _AES.so shared library is not found.

Also, unzipping /Library/Python/2.7/site-packages/pycrypto-2.6.1-py2.7-macosx-10.11-intel.egg reveals that it indeed has ./Crypto/Cipher/_AES.so in it. Somehow pyinstaller misses that library when creating the binary.

**Comment by matysek** [comment]
> Also, unzipping /Library/Python/2.7/site-packages/pycrypto-2.6.1-py2.7-macosx-10.11-intel.egg reveals that it indeed has ./Crypto/Cipher/_AES.so in it. Somehow pyinstaller misses that library when creating the binary.

* @wellu this is probably the reason. PyInstaller is not looking for C extensions inside zipped .egg files.
* @htgoebel Do you know more about this topic?
* I just remember that in the past zipsafe eggs were those that did not contain any C extensions. Has it changed since then?

**Comment by wellu** [comment]
Just a side note: this works out-of-the box on Ubuntu 14.04 with distribution provided pyinstaller 3.0.

**Comment by wellu** [comment]
This issue is happening only on OS X. Tested on Windows and Linux and the AES import works without issues.

@matysek @htgoebel any pointers where to look for more information? Is pyinstaller completely broken in case of .egg files containing native extensions?

**Comment by matysek** [comment]
@wellu Could you rather try virtualenv and pip to install PyCrypto? Not sure if it's worth the effort to fix this corner case.

Thanks for confirmation.

**Comment by wellu** [comment]
Tested with virtualenv + pip and everything works as expected. This confirms that the bug is related to easy_install and .egg only. As both easy_install and .egg are more or less deprecated there is really no point in fixing this bug. Better just to point out people to use pip instead.

Suggesting closing this as known issue and won't fix resolution.

**Comment by matysek** [comment]
@wellu Thanks for testing with virtualenv.
