### ISSUE TITLE
Executable fails when using 'from site import getsitepackages'

### ISSUE THREAD

**Issue by MrSimonC** [pyinstaller/pyinstaller#1731]
Using pyinstaller on windows 7, python 3.4.3 (and python 3.5.1) on a file with a single line of:
```python
from site import getsitepackages
```
compiles fine, but then fails on execute with
```dos
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: cannot import name 'getsitepackages'
test returned -1
```
I've analysed outPYZ*.pyz - as it says to do on [when things go wrong](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged) and `sites` *is* included.

However, I've noticed that changing the python file code to:
`import site` or `from site import *` works. Also, a quick test of:
```python
from time import sleep
```
works fine with no complaints. I can't work out if this problem is specific to this module? How do I get `from site import getsitepackages` to work?

**Comment by htgoebel** [comment]
Within PyInstaller there is no such thing like "site packages", so this function would return an empty list anyway. The site-module we are putting into the frozen app is only a fake,implementing only the absolute minimum,

Please change your program to handle this by testing for sys,frozen.See the manual for more information.

IMHO we should not implement a fake `getsitepackages` in our fake `site`-module. This would only delay the errors and make debuggin more complicated. With an import-error you directly, this function is not available.
