### ISSUE TITLE
Shelve Hook

### ISSUE THREAD

**Issue by Penaz91** [pyinstaller/pyinstaller#1733]
First of all, thank you for making this awesome project.
I had quite some issues using Shelve with PyInstaller, until i noticed that its hook file was missing.
I made a small basic hook that made it work for me, hope it's useful.

[hook-shelve.zip](https://github.com/pyinstaller/pyinstaller/files/67450/hook-shelve.zip)

Thanks again.

**Comment by matysek** [comment]
@Penaz91 Please create a pull request. Thanks.

**Comment by Penaz91** [comment]
Will do, sorry but i'm pretty new on the Issue/Pull request stuff.

**Comment by Penaz91** [comment]
Closing, I created said Pull Request, Id is #1734
