### ISSUE TITLE
Unable to Run exe file.

### ISSUE THREAD

**Issue by MajjigaDeepak** [pyinstaller/pyinstaller#1736]
I developed a windows  application using pyqt4 using anacondas which has pythn 3.5. I tried pyinstaller to convert into exe file in order to distribute but exe file is generating but when I try to open its throwing error as "Fatal Error:  main.py returned -1" 
While running the pyinstaller  command itself  I can see many warnings regarding cp.pywin64 but I installed all these stuff couldn't able to figure what is causing the issue.

os I am using is Windows10

Please suggest any way to get out this hurdle.Your help is most appreciated.

**Comment by htgoebel** [comment]
You can fond more help at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong
