### ISSUE TITLE
pyinstaller putting added files into own directory

### ISSUE THREAD

**Issue by rbalik** [pyinstaller/pyinstaller#1744]
I have this line in my Analysis definition:

`datas=[('version.txt', 'version.txt')]`

Instead of adding the version.txt file to the root of the directory, it makes a new directory called version.txt and sticks version.txt inside of that. I've tried hardcoding directory names and nothing seems to work.
Seems like a bug, but please let me know if I'm missing something here.

**Comment by tallforasmurf** [comment]
I suspect the manual (http://pythonhosted.org/PyInstaller/#adding-data-files) must be wrong. @htgoebel please clarify: the 2nd item int the tuple, the target, is a relative path including filename, or is a folder path?
The examples in the manual seem to go both ways. I'm thinking in this case, `datas=[('version.txt','.')]` giving a target folder (dot for top level), would work...?

**Comment by rbalik** [comment]
Oh duh, that fixed it. Just a documentation bug. Thanks

**Comment by htgoebel** [comment]
@tallforasmurf You are right, the manual needs to be corrected here. It behave exaclty like datas in hooks. The same is true for `Anaylsis(... binaries=...)`.

The possibility to pass `datas` and `binaries` to `Analysis` was introduced in the later beta-phase of release 3.0 (see a3555a1eab6c147fb74ffc9e022bbdb4a3f014dd).

**Comment by tallforasmurf** [comment]
Actually it turns out, the actual manual says the correct thing (https://github.com/pyinstaller/pyinstaller/blob/develop/doc/source/Manual.rst). It is the manual at pythonhosted that is out of date.

**Comment by matysek** [comment]
I updated the pythonhosted manual from `develop`.
