### ISSUE TITLE
ModuleGraph can get confused by symlinks

### ISSUE THREAD

**Issue by inglesp** [pyinstaller/pyinstaller#1750]
I'm trying to package an application that uses PyQt5 and QScintilla2 on OSX.  Building the package works fine, but when it comes to run, it fails with an `ImportError` on:

```
import PyQt5.Qsci
```

This is because although `ModuleGraph` is able to find and import the `PyQt5` package, it's not able to find `PyQt5.Qsci`, because it's looking in the wrong place.

I've installed PyQt5 with homebrew, which puts the relevant `.so` files in `/usr/local/Cellar/pyqt5/5.5.1/lib/python3.5/site-packages/PyQt5/`, and then creates a symlink to each `.so` file in `/usr/local/lib/python3.5/site-packages/PyQt5/`.

I've also installed QScintilla2 with homebrew, which puts `Qsci.so` in `/usr/local/Cellar/qscintilla2/2.8.4/lib/python3.5/site-packages/PyQt5/`, and symlinks this to `/usr/local/lib/python3.5/site-packages/PyQt5/Qsci.so`.

The problem comes when `ModuleGraph` tries to work out where it should be importing `PyQt5.Qsci` from.  I think it assumes that `PyQt5.Qsci`'s "head" package is the `PyQt5` package.  It has previously found the `PyQt5` package in `/usr/local/lib/python3.5/site-packages/PyQt5/`, but via `ModuleGraph._find_module`'s call to `os.path.realpath`, it records the `PyQt5` package as being in `/usr/local/Cellar/pyqt5/5.5.1/lib/python3.5/site-packages/PyQt5/`.

As such, it tries to look here for `PyQt5.Qsci`, and this fails.

Commenting out [these two lines](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/modulegraph/modulegraph.py#L1680-L1681) causes the build to produce something usable.  Beyond that though, I'm not sure what to recommend as a fix -- I assume those lines are there for a reason, but it looks like they've been there since the modulegraph project was imported into bitbucket [almost ten years ago](https://bitbucket.org/ronaldoussoren/modulegraph/commits/d3e37458866c340178f200640a768a3e3a5c333b)!

**Comment by htgoebel** [comment]
Said two lines resolve the sym-link (using `realpath`). This was *not* done in `modulefinder` on which `modulegraph` is based on, see [the original commit of `modulefinder`](
https://hg.python.org/releasing/3.5/annotate/a5c879726b3a/Lib/modulefinder.py#l354).

I can see no reason, why `realpath` should be required at all here: Either it is a module, then the real path does not matter at all. Or it is a package, in which case the real path is of no interest and even hurts as this issue shows.

I assume, it should be save to replace this by `abspath` or `absnormpath`, or even remove it.

Any opinions? Should this go into release 3.1?

**Comment by bjones1** [comment]
I see no reason for these two lines -- if tests pass with them removed, I'd suggest including this in v3.1.

**Comment by inglesp** [comment]
I did try to run the tests with those lines removed, the tests seem to leak temporary files and I ran out of disk space...  Is this a known problem?
