### ISSUE TITLE
PyGame hook dont bundle all DDL files

### ISSUE THREAD

**Issue by AcidWeb** [pyinstaller/pyinstaller#1751]
Windows 10
Python 3.5 
PyInstaller 9c4a08f

There are 5 DLL files (zlib1.dll, libogg.dll, libvorbis.dll, libvorbisfile.dll, mikmod.dll) that are part of PyGame egg but are not bundled to PyInstaller output.

Lack of them break loading of many (all?) audio formats supported by PyGame.

**Comment by tallforasmurf** [comment]
I observe there exists a hook-pygame (https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-pygame.py) but it lists only one thing, pygame._view.

**Comment by htgoebel** [comment]
Is this fixed? Can we close the ticket?
