### ISSUE TITLE
Pyinstaller Question 

### ISSUE THREAD

**Issue by artguy10** [pyinstaller/pyinstaller#1757]
I am creating a Python program that requires the Tesseract OCR engine. How do I include it with my executable?

**Comment by nchammas** [comment]
Do the docs not answer your question?

For example: http://pythonhosted.org/PyInstaller/#adding-files-to-the-bundle

**Comment by tallforasmurf** [comment]
OK, for reference Tesseract OCR is here: https://github.com/tesseract-ocr
When I search pypi on "tesseract" I see there are *at least eight* different Python wrappers for it!
Which one are you using?
What happens when you try to bundle your main script with PyInstaller? Does it report any errors?

**Comment by matysek** [comment]
Closing since no reaction for long time.
