### ISSUE TITLE
Take advantage of setuptools to offer a more consistent Python packaging experience

### ISSUE THREAD

**Issue by nchammas** [pyinstaller/pyinstaller#1758]
PyInstaller is extremely user-friendly. Being able to just run `pyinstaller script.py` and get a working package is fantastic.

However, when things get a bit more complicated -- for example, if I have additional files to include -- I feel like I am duplicating work I already did when I got `setuptools` to package my project properly. I have a `MANIFEST.in`, I've specified my `packages` and `entry_points`, and I know that `python setup.py sdist` does what I want.

Wouldn't it be great if I could reuse all that work with PyInstaller?

What are the PyInstaller team's thoughts on somehow reusing existing Python packaging tools to minimize or eliminate duplicate work that users have to do to use PyInstaller? If a user has done the work to get `python setup.py sdist` and `python setup.py bdist_wheel` working, is there a future in which they can run something like `python setup.py pyinstaller_dist` and know they'll get what they want without having to do anything else?

In my opinion, that would create the ideal user story for PyInstaller: "If it works with `setuptools`, it will work with PyInstaller--no extra work required."

Or to put it in code: "If `python setup.py sdist` does what you want, then `python setup.py pyinstaller_dist` will give you what you are looking for."

Previous discussion: #987

**Comment by nchammas** [comment]
Additional note: Better integration with setuptools should, among other things, also resolve issues like #305.

**Comment by htgoebel** [comment]
As you can see in #987, we discussed this since long, but nobody stepped forward implementing it. This is why #987 has been closed as "won't fix".

*If somebody (you?) provides a pull-request implementing this integration, we'd happily review and accept it.*

But we (the core team) will not work on this in the foreseeable future - this is why I'm closing this issue as "won't fix", too.

**Comment by YakDriver** [comment]
@nchammas I love this suggestion. I'm just starting to use pyinstaller with code that already works with setuptools and I find it strange that you can't leverage all that setup to just make pyinstaller work. Did you ever find a solution? Tips?

**Comment by nchammas** [comment]
@YakDriver - Unfortunately, I did not come up with a solution that lets you reuse all the setuptools scaffolding with PyInstaller. You can take a look at [how my project, Flintrock, uses PyInstaller](https://github.com/nchammas/flintrock/blob/master/generate-standalone-package.py).

I still believe that it would be elegant and user friendly to have something like `python setup.py pyinstaller_dist` exist, but as @htgoebel pointed out, it seems like this will have to come from a motivated contributor. Since the status quo works well enough, I doubt it will happen.

**Comment by YakDriver** [comment]
@nchammas seeing your approach with Flintrock helped get my builds working! Thank you. With all the complexity of setuptools, I can see why folks are reluctant to pick it up.
