### ISSUE TITLE
compiling with --noconsole giving fatal error return -1 under windows 32 bit while execution

### ISSUE THREAD

**Issue by dannyrock** [pyinstaller/pyinstaller#1761]
Compiling with out --noconsole works fine while execution i.e (Pyinstaller file.py --onefile)
but it gives this error if i compile with --noconsole argument while execution i.e ( Pyinstaller file.py --onefile --noconsole)
code :
from selenium import webdriver
import time
from selenium.webdriver.common.keys import Keys
import os
driver = webdriver.Firefox()
driver.get("http://google.com/")

screenshoot : http://i.imgsafe.org/f3c6308.png

**Comment by htgoebel** [comment]
Please provide more information, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by htgoebel** [comment]
Closing since there have been no relevant information since one month.
