### ISSUE TITLE
super cool tool - looking at better compression

### ISSUE THREAD

**Issue by denfromufa** [pyinstaller/pyinstaller#1766]
Hi PyInstaller developers and hackers!

I would like to thank you for this useful tool. It worked out of box without any hassle for my simple script using `shutil` and `sys` modules!

I looked at "onefile" and "expanded" (see list of files below) versions and the compression seems suboptimal when compared to 7z archive of "expanded" version by about 30% against "onefile" version. Is there any way to improve this, i.e. to get smaller "onefile" executable?

```
msvcp90.dll
msvcr90.dll
python27.dll
pywintypes27.dll
select.pyd
unicodedata.pyd
win32api.pyd
win32evtlog.pyd
_ctypes.pyd
_hashlib.pyd
_socket.pyd
_ssl.pyd
bz2.pyd
clr.pyd
merge_.exe
merge_.exe.manifest
Microsoft.VC90.CRT.manifest
msvcm90.dll
```

**Comment by AcidWeb** [comment]
http://pythonhosted.org/PyInstaller/#using-upx

**Comment by denfromufa** [comment]
i hit this problem:

https://github.com/pyinstaller/pyinstaller/issues/1184
