### ISSUE TITLE
packagin e.g. `six` fails if setuptools 19.4 is installed

### ISSUE THREAD

**Issue by dbskccc** [pyinstaller/pyinstaller#1772]
when i packaging a small file(see attach) with pyinstaller 3.1, it show the error below:
```
R:\dist\draw>draw.exe
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__diact__)
  File "site-packages\pkg_resources\__init__.py", line 74, in <module>
  File "site-packages\pkg_resources\extern\__init__.py", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
pyi_rth_pkgres returned -1
```
any suggestion about it?

[draw.zip](https://github.com/pyinstaller/pyinstaller/files/93246/draw.zip)

**Comment by htgoebel** [comment]
Please provide a *minimal* example. If this is in the zip-archive you attached, please provide it as plain text, since for security reasons we will not open zip-archives.

**Comment by isaaczafuta** [comment]
I ran into the same issue-- Only difference between builds was an upgrade of setuptools from 19.2 to 19.3. Downgrading to 19.2 solved the issue.

**Comment by dbskccc** [comment]
well, in my case, the simple code as below show the same error.

from pylab import *
plot([10,20],[50,60])
show()

the setuptools is 19.4
R:\dist\tt>easy_install --version
setuptools 19.4 from c:\python27\lib\site-packages (Python 2.7)

**Comment by cdujeu** [comment]
I can confirm, same for us, fixing setuptools to 19.2 fixed the same issue.

**Comment by dbskccc** [comment]
uninstall setuptools 19.4, reinstall 19.2 fixed the problem. thanks @isaaczafuta

**Comment by htgoebel** [comment]
Thanks. For te report. Scheduling for 3.2 since there is an easy work-around. If we fix it until 3.1.1 is releases (if it is), we can push it there, too.

**Comment by Bluehorn** [comment]
Since you asked for a minimal example:

```
$ cat use_pkg_resources.py 
import pkg_resources
$ python -m PyInstaller -y --onedir use_pkg_resources.py
23 INFO: PyInstaller: 3.1
[...]
$ $ ./dist/use_pkg_resources/use_pkg_resources 
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/tmp/pip-build-xQxi6D/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "/usr/opt/dynasdk/loco2-precise/lib/python2.7/site-packages/pkg_resources/__init__.py", line 48, in <module>
    from pkg_resources.extern import six
  File "/usr/opt/dynasdk/loco2-precise/lib/python2.7/site-packages/pkg_resources/extern/__init__.py", line 60, in load_module
    "distribution.".format(**locals())
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
pyi_rth_pkgres returned -1
```

**Comment by htgoebel** [comment]
https://github.com/pyinstaller/pyinstaller/issues/1773#issuecomment-173009510 has a solution.

**Comment by YDD9** [comment]
I have conda setuptools 23.0.0, run into the same problem, downgrading setuptools 19.2 works for me.
Although during downgrade the setuptools via pip install setuptools == 19.2 has a bug to overcome, maybe I should firstly try with conda install setuptools==19.2 ? anyone did this let me know.
