### ISSUE TITLE
'six' is required; worked fine with previous version of pyinstaller

### ISSUE THREAD

**Issue by txtsd** [pyinstaller/pyinstaller#1773]
I get this when I run the built executable. It worked fine when built with the previous version of `pyinstaller`.
```
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "/usr/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 363, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib/python3.5/site-packages/pkg_resources/__init__.py", line 48, in <module>
    from pkg_resources.extern import six
  File "/usr/lib/python3.5/site-packages/pkg_resources/extern/__init__.py", line 60, in load_module
    "distribution.".format(**locals())
ImportError: The 'six' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
pyi_rth_pkgres returned -1
```

**Comment by opqopq** [comment]
To solve, in spec file, I hadd to add the followings in hidden imports:

hiddenimports=['six','packaging', 'packaging.version', 'packaging.specifiers'],

**Comment by htgoebel** [comment]
This seams to be an issue with setuptools 19.3, see https://github.com/pyinstaller/pyinstaller/issues/1772#issuecomment-172467268. Please try downgrading setuptools to 19.2 and report back if this solved the issue in your case, too.

**Comment by pythonic64** [comment]
Downgrading to setuptools==19.2 fixed this issue for me.

**Comment by Bluehorn** [comment]
Same problem here, I fixed this with a new hook script for the vendor hack inside pkg_resources:

```diff
(loco2-precise)torsten.landschoff@horatio:~/opensrc/pyinstaller$ git diff --cached
diff --git a/PyInstaller/hooks/hook-pkg_resources.py b/PyInstaller/hooks/hook-pkg_resources.py
new file mode 100644
index 0000000..cff9036
--- /dev/null
+++ b/PyInstaller/hooks/hook-pkg_resources.py
@@ -0,0 +1,6 @@
+def list_vendored_modules():
+    from pkgutil import walk_packages
+    import pkg_resources._vendor
+    return ["pkg_resources._vendor.{1}".format(*x) for x in walk_packages(pkg_resources._vendor.__path__)]
+
+hiddenimports = list_vendored_modules()
```

**Comment by htgoebel** [comment]
@Bluehorn Would you pleas be so kind submitting a pull-request, so you'll get the credits for this fix. (I'm going to prepare release 3.1.1 in the meanwhile).

**Comment by htgoebel** [comment]
@Bluehorn Just a quick question: This code basically collects `pkg_resources._vendor` and all sub-modules? Correct? So if you are going to issue a pull-request, please use 
```
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('pkg_resources._vendor')
```

**Comment by Bluehorn** [comment]
@htgoebel Thanks, I did not know of `collect_submodules`.

**Comment by smartswdeveloper** [comment]
The fix doesn't solve the issue to me.

I get the same issue using pyinstaller 3.1.1 and  python 3.5.1 using Anaconda.
It works only after downgrading to setuptools==19.2 as  suggested by pythonic64

**Comment by nealkruis** [comment]
I am seeing the same issue as @smartswdeveloper using pyinstaller 3.1.1 and python 2.7.11 with Anaconda. Needed to downgrade setuptools in order to get it to run correctly. 

I suggest re-opening this issue, or I can create a new one.

**Comment by Insoleet** [comment]
Same problem, python 3.5.1 with Anaconda on Windows. I think we should re-open this issue.

**Comment by bpteague** [comment]
+1 for re-opening.  Anaconda distribution of Python 2.7.11 on Windows; downgrading setuptools to 19.2 fixed the problem for me.

**Comment by bjones1** [comment]
Doing a bit of looking, on my Windows PC and current PyInstaller (see below), `hook-pkg_resource.py` invokes `collect_submodules`, which incorrectly returns an empty list. This is because `pkg_resources` is installed in an egg:



``


``` Python
>>> import pkg_resources
>>> pkg_resources.__file__
'C:\\Users\\bjones\\Downloads\\WinPython-32bit-3.4.4.1Qt5\\python-3.4.4\\lib\\site-packages\\pkg_resources\\__init__.py'
>>>
```

Deleting the .egg file shown above causes Python to find the non-.egg version:

```
78 INFO: PyInstaller: 3.2.dev0+g8e0a51f.mod
78 INFO: Python: 3.4.4
78 INFO: Platform: Windows-10-10.0.10240
```

**Comment by salvoip** [comment]
Dear devs,

I have faced the same issue with python 3.5.1 using miniconda 3. My fix is just to extract setuptools-20.3-py3.5.egg as setuptools in site-packages, and change the setuptools.pth file to ".\setuptools". Building successful with pyinstaller 3.1.1 (why does pyinstaller 3.2 fail to look for binary dependencies of several api-ms dlls with the same code?).

Can this considered a valid solution or extracting the setuptools-20.3-py3.5.egg can trigger additional side-effects?

All the best and thank you!

**Comment by bjones1** [comment]
@salvoip, I think 08020fd185d23a9a316583adef82c5b94d10bd0e fixes this. Would you test?

**Comment by ronanpaixao** [comment]
@bjones1 This may be a workaround for a simple package, but I'm getting errors for a program which doesn't use NumPy: https://github.com/ronanpaixao/PyPDFTK/

When generating it also goes from 13MB (with setuptools 19.2) to 30MB (with setuptools 26.1.1). Maybe it's importing some troublesome package?

PyPDFTK is pretty much PyQt and PyPDF2. I'm also trying my spec file in a simpler project and it works fine. Maybe PyPDF2 is another culprit?

**Comment by bjones1** [comment]
First follow the steps at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs. It's hard to tell if this is related or not.

**Comment by ebadali** [comment]
@smartswdeveloper Your fix, resolved my issue. 
But i can only run exe from Cmd, Clicking it doesn't do anything.

Any idea ?
