### ISSUE TITLE
No module named 'requests_ntlm'

### ISSUE THREAD

**Issue by njhpq** [pyinstaller/pyinstaller#1774]
when i use pyinstaller bundles my python script in One-File Program(a exe file), i get some error message.(pyinstaller 3.1   python3.3 under windows 7 64it)

here is my python script
======================
1 #!/usr/bin/env python
2 # -*- coding: utf-8 -*-
3 import os
4 from datetime import date
5 import requests
6 from requests_ntlm import HttpNtlmAuth
7 from bs4 import BeautifulSoup
......
=======================

here is error message by "dist exe Program"
====================
 Traceback (most recent call last):
    File "<string>", line 6 in <module>
 ImportError: No module named 'requests_ntlm'
====================

**Comment by htgoebel** [comment]
Please try [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged) and find out, why this module is missing. Since it is a top-level import, some of your paths may be missing.

**Comment by htgoebel** [comment]
Please check which version of setuptools you have installed. There have been problems reporte for setuptools 19.4, while downgrading to 19.2 solves the issue.

**Comment by dessant** [comment]
This must be the same as https://github.com/pyinstaller/pyinstaller/issues/1780.
@njhpq, it is fixed in the develop branch.

**Comment by htgoebel** [comment]
@dessant You are right. Thanks for pointing this out :-)
