### ISSUE TITLE
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.

### ISSUE THREAD

**Issue by minimatronik** [pyinstaller/pyinstaller#1781]
Hello. I have some problem after success build exe with PyInstaller.
Onput of build proccess: [error.txt](https://github.com/pyinstaller/pyinstaller/files/96501/error.txt)
When i try run program i getting error:
> dist\MyProgram.exe
Traceback (most recent call last):
  File "<string>", line 11, in <module>
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 74, in <module>
  File "site-packages\pkg_resources\extern\__init__.py", line 60, in load_module
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
pyi_rth_pkgres returned -1

I get this error when build several different programs.
I used --onedir and clear %APPDATA%\pyinstaller.
PyInstaller: 3.2.dev0+5427395
Python: 3.4.3

**Comment by minimatronik** [comment]
Output after build with --debug: [error1.txt](https://github.com/pyinstaller/pyinstaller/files/96510/error1.txt)

**Comment by htgoebel** [comment]
This seams to be an issue with setuptools 19.3, see https://github.com/pyinstaller/pyinstaller/issues/1772#issuecomment-172467268. Please try downgrading setuptools to 19.2. If this does not solve you issue, please reopen the ticket.

**Comment by nchammas** [comment]
Just hit this myself. Can confirm that downgrading to setuptools 19.2 fixes the issue for me.

Has this been reported on the [setuptools issue tracker](https://bitbucket.org/pypa/setuptools/issues)?

**Comment by nchammas** [comment]
To clarify, I looked through the issues on there and couldn't tell if our issue here had been tracked down to something else reported there.

**Comment by YangChuan80** [comment]
Yeah, I encountered the same problem, and I downgraded to 19.2, it worked. Thank you so much!
