### ISSUE TITLE
AttributeError: 'module' object has no attribute '_MEIPASS' (redux)

### ISSUE THREAD

**Issue by bharadwaj-raju** [pyinstaller/pyinstaller#1785]
Using the latest git version of PyInstaller and vlc.py, PyInstaller cannot find the libVLC ctype.

The code runs fine in the interpreter.

Command: `pyinstaller --onefile --windowed --noupx file.py`

(Same with `--onedir`)

(Windows)

**Comment by bharadwaj-raju** [comment]
Closed: found [this recipe](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Win-Load-External-DLL).

**Comment by bharadwaj-raju** [comment]
Recipe failed: Libraries found but app crashes.

`sys has no attribute _MEIPASS`

**Comment by codewarrior0** [comment]
Post the full traceback for that error.

Make sure none of your code is reloading the `sys` module.

**Comment by bharadwaj-raju** [comment]
Traceback (most recent call last):
        File "C:\Users\Bharadwaj\Documents\python\app.py", line 26, in <module>
         ctypes.windll.kernel32.SetDllDirectoryW(sys._MEIPASS)
         AttributeError: 'module' object has no attribute '_MEIPASS'
As for reloading, (though I don't fully understand 'reload'), none of my code (except Qt.QApplication which takes `sys.argv`) uses any `sys` modules.

**Comment by codewarrior0** [comment]
`sys._MEIPASS` is set by the exe produced by pyinstaller before it runs any python code. I can think of a few reasons why it would not be set:

- The code `reload(sys)` is executed
- You are using a version of PyInstaller prior to 3.0
- PyInstaller was improperly installed and is using the old 2.1 bootloader files

Could you reinstall PyInstaller and run `pyinstaller -v` to double-check the version number?

**Comment by bharadwaj-raju** [comment]
`pyinstaller -v`

3.2.dev0+5427395 
I got the latest git version.

**Comment by htgoebel** [comment]
There already have been old bug-reports for this, see #801. In contrast to #801 here it happens on the developers machine, so we have a chance to find the root-cause. I would be very happy if we could find the reason for this.
@bharadwaj-raju: *Please* try to find a *minimal* example, where this occurs.

**Comment by codewarrior0** [comment]
@bharadwaj-raju Looking at your traceback, it looks like you get that error when running your app in the Python interpreter? Not using PyInstaller? `sys._MEIPASS` is only available when your app is frozen using PyInstaller.

To check if your app is frozen, use `getattr(sys, 'frozen', False)`; see [the manual](https://pythonhosted.org/PyInstaller/#run-time-information) for details.

**Comment by bharadwaj-raju** [comment]
@codewarrior0 Yes, that was the Python interpreter. However, the app also crashes when on frozen state. (`App returned -1`). Also could it be because I have two python files, in one there is the `sys._MEIPASS`, in the other, I import `sys` and call `sys.argv`.

**Comment by bharadwaj-raju** [comment]
Is there any way to tell PyInstaller to include it through the `spec` file?

**Comment by htgoebel** [comment]
I strongly suggest you cleaning up your setup first, see http://pythonhosted.org/PyInstaller/#id47.

Then come back and open a new ticket providing *all* the information required, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
