### ISSUE TITLE
Symantec flags runw_d.exe as a trojan

### ISSUE THREAD

**Issue by dougn** [pyinstaller/pyinstaller#1787]
When performing a pip install pyinstaller, Symantec virus protection flags and quarantines runw_d.exe believing it to be a trojan, and causing the install to fail. This just started happening with the 3.1 release. The 3.0 release does not have this happen.

![pip-pyinstaller](https://cloud.githubusercontent.com/assets/68801/12463707/3246471a-bf93-11e5-89a5-7c08ab78f433.PNG)

**Comment by dougn** [comment]
I disabled virus protection, installed PyIntaller 3.1, built my .exe with it, and then re-enabled virus protection. Now when I run my built .exe, Symantec fires again, and my built .exe is also considered a virus.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is nothing(!) we can do here.

See [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
