### ISSUE TITLE
Display custom bootloader message

### ISSUE THREAD

**Issue by sbrcher** [pyinstaller/pyinstaller#1797]
I have a program (about 100 MB executable size) that uses one-file mode and it takes about 15 seconds for the file to self-extract and start running the python code.  Users are sometimes confused by this long delay (and blank console window) and think the program is frozen.  I enabled debug mode as a temporary workaround to let the users know that something is happening.  

It would be helpful if the bootloader could be programmed to display a custom message while extracting the files.  In my case, the message would read "Program loading, please wait" or something similar.

**Comment by htgoebel** [comment]
Feel free to submit a pull-request :-)

**Comment by Legorooj** [comment]
Maybe a splash screen option? User adds an image with `--splash=image.formst`. The screen shows until app is ready to run.

**Comment by Legorooj** [comment]
Closing this - there's an open PR to add a splash screen.
