### ISSUE TITLE
Mailing list not accepting posts from new members

### ISSUE THREAD

**Issue by nchammas** [pyinstaller/pyinstaller#1798]
Posting this here since I can't seem to get a response from the [mailing list](https://groups.google.com/forum/#!forum/pyinstaller) owners.

Around 2 weeks ago I joined the group and submitted a post. I believe it was held for moderation since it was my first post. I followed up recently with an email to the owners asking about my post when I saw it had still not gone through.

Did my post get gobbled up by some kind of spam filter?

**Comment by rasky** [comment]
Well, yes, the notification was caught by my own spam filter and didn't know the mails were pending. Now flushed.

**Comment by nchammas** [comment]
:+1: Thank you.
