### ISSUE TITLE
SyntaxError: Non-UTF-8 code ... but no encoding declared

### ISSUE THREAD

**Issue by dessant** [pyinstaller/pyinstaller#1800]
After packaging the example from https://github.com/pyinstaller/pyinstaller/issues/1780#issue-127366372  with the develop branch, i get this error while running the executable:

```python
$ python ./dist/a/a.exe
  File "./dist/a/a.exe", line 1
SyntaxError: Non-UTF-8 code starting with '\x90' in file ./dist/a/a.exe on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

The error is not present with 3.0 or 3.1, and encoding headers should not be needed for python 3 anyway, because utf-8 is the default.

**Comment by codewarrior0** [comment]
`a.exe` is a Windows executable, not a Python script. Instead of passing it to Python, just run it as is:

`./dist/a/a.exe`

**Comment by dessant** [comment]
@codewarrior0, oh dang, that was a silly mistake, thanks! :stuck_out_tongue_winking_eye:

**Comment by SalvishGoomanee** [comment]
Hello, 

I have the same issue at the moment. I of course executed the `.exe` by simply typing in `app.exe` but it is not working at all for me. 

Double clicking on the app to open does not show anything. 

Are there modifications to the `app.spec` file that needs to be appended? 

Thanks for any possible inputs!

**Comment by bwoodsend** [comment]
Whatever your issue is, it won't be this. Create a new issue.
