### ISSUE TITLE
[Documentation] Misplaced figure in PDF documentation

### ISSUE THREAD

**Issue by JokerQyou** [pyinstaller/pyinstaller#1802]
By following the download link in `http://pyinstaller.org` , which is `https://github.com/pyinstaller/pyinstaller/blob/v3.1/doc/Manual.pdf?raw=true` I downloaded a PDF copy of the documentation. In page 36 there is a misplaced figure which covers most of the page, and I cannot read the text behind it. Screenshot attached below.

![image](https://cloud.githubusercontent.com/assets/1465267/12601464/2e114264-c4dc-11e5-93a8-815cb78e269c.png)

**Comment by tallforasmurf** [comment]
Verified using the 3.1 PDF linked from pyinstaller.org (which is the link above). The figures of the ZlibArchive and CArchive have been "floated" instead of being inline between paragraphs. The html version at http://pythonhosted.org/PyInstaller/ is fine. So, some problem with rst2pdf.

**Comment by htgoebel** [comment]
I also filed a bug report at rst2pdf.
