### ISSUE TITLE
Mac --windowed .app Not Clickable, Runs From Console

### ISSUE THREAD

**Issue by riggsd** [pyinstaller/pyinstaller#1804]
I've built the Tkinter "hello world" from the Python docs: https://docs.python.org/2/library/tkinter.html#a-simple-hello-world-program

I'm building it with `pyinstaller --noupx --windowed hello.py`.

**Success:** launching the "onedir" version of the executable, `./dist/hello/hello`
**Success:** launching the contents of the .app itself, `./dist/hello.app/Contents/MacOS/hello`
**Fail:** double-clicking on the .app from within Finder, or launching it with `open ./dist/hello.app`

When the .app fails to launch, I see the following message in the OS X Console (not the commandline, but the OS X error message center):

`com.apple.launchd.peruser.501[275]: (hello.77648[49190]) Exited with code: 255`

Environment:

OS X 10.9.5
Python 2.7.11, TCL/Tk 8.6.4 both built with `homebrew`
PyInstaller 3.1

Build log follows:

```
(pyitest)[driggs@host /Users/driggs/tmp/pyi_test]$ pyinstaller --noupx --windowed hello.py
22 INFO: PyInstaller: 3.1
23 INFO: Python: 2.7.11
27 INFO: Platform: Darwin-13.4.0-x86_64-i386-64bit
27 INFO: wrote /Users/driggs/tmp/pyi_test/hello.spec
32 INFO: UPX is available.
33 INFO: Extending PYTHONPATH with paths
['/Users/driggs/tmp/pyi_test', '/Users/driggs/tmp/pyi_test']
33 INFO: checking Analysis
34 INFO: Building Analysis because out00-Analysis.toc is non existent
34 INFO: Initializing module dependency graph...
36 INFO: Initializing module graph hooks...
112 INFO: running Analysis out00-Analysis.toc
120 INFO: Analyzing /Users/driggs/tmp/pyi_test/hello.py
1321 INFO: Looking for import hooks ...
1323 INFO: Processing hook   hook-encodings.py
1722 INFO: Processing hook   hook-_tkinter.py
1804 INFO: checking Tree
1805 INFO: Building Tree because out00-Tree.toc is non existent
1805 INFO: Building Tree out00-Tree.toc
1858 INFO: checking Tree
1858 INFO: Building Tree because out01-Tree.toc is non existent
1858 INFO: Building Tree out01-Tree.toc
1899 INFO: Looking for ctypes DLLs
1901 INFO: Analyzing run-time hooks ...
1905 INFO: Including run-time hook 'pyi_rth__tkinter.py'
1913 INFO: Looking for dynamic libraries
1977 INFO: Looking for eggs
1977 INFO: Using Python library /usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/Python
1981 INFO: Warnings written to /Users/driggs/tmp/pyi_test/build/hello/warnhello.txt
2119 INFO: checking PYZ
2119 INFO: Building PYZ because out00-PYZ.toc is non existent
2119 INFO: Building PYZ (ZlibArchive) /Users/driggs/tmp/pyi_test/build/hello/out00-PYZ.pyz
2317 INFO: checking PKG
2317 INFO: Building PKG because out00-PKG.toc is non existent
2317 INFO: Building PKG (CArchive) out00-PKG.pkg
2325 INFO: Bootloader /usr/local/lib/python2.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
2326 INFO: checking EXE
2326 INFO: Building EXE because out00-EXE.toc is non existent
2326 INFO: Building EXE from out00-EXE.toc
2332 INFO: Appending archive to EXE /Users/driggs/tmp/pyi_test/build/hello/hello
2333 INFO: Fixing EXE for code signing /Users/driggs/tmp/pyi_test/build/hello/hello
2342 INFO: checking COLLECT
2342 INFO: Building COLLECT because out00-COLLECT.toc is non existent
2342 INFO: Building COLLECT out00-COLLECT.toc
3218 INFO: checking BUNDLE
3218 INFO: Building BUNDLE because out00-BUNDLE.toc is non existent
3218 INFO: Building BUNDLE out00-BUNDLE.toc
3816 INFO: moving BUNDLE data files to Resource directory
```

**Comment by riggsd** [comment]
Same result observed when building outside of a virtualenv.

**Comment by riggsd** [comment]
Output in Console after compiling with `--debug` and launching the .app:

```
PyInstaller Bootloader 3.x
LOADER: executable is /Users/driggs/tmp/pyi_test/dist/hello.app/Contents/MacOS/hello
LOADER: homepath is /Users/driggs/tmp/pyi_test/dist/hello.app/Contents/MacOS
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /Users/driggs/tmp/pyi_test/dist/hello.app/Contents/MacOS/hello
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to /var/folders/v5/j9cckf390nq5xj6k1z0yybrr0000gn/T/_MEI42a6co
LOADER: AppleEvent - processing...
LOADER: AppleEvent - installed handler.
PyInstaller Bootloader 3.x
LOADER: executable is /Users/driggs/tmp/pyi_test/dist/hello.app/Contents/MacOS/hello
LOADER: homepath is /Users/driggs/tmp/pyi_test/dist/hello.app/Contents/MacOS
LOADER: _MEIPASS2 is /var/folders/v5/j9cckf390nq5xj6k1z0yybrr0000gn/T/_MEI42a6co
LOADER: archivename is /Users/driggs/tmp/pyi_test/dist/hello.app/Contents/MacOS/hello
LOADER: Already in the child - running user's code.
LOADER: Python library: /var/folders/v5/j9cckf390nq5xj6k1z0yybrr0000gn/T/_MEI42a6co/Python
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is /var/folders/v5/j9cckf390nq5xj6k1z0yybrr0000gn/T/_MEI42a6co
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is /var/folders/v5/j9cckf390nq5xj6k1z0yybrr0000gn/T/_MEI42a6co
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running hello.py
hello returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: 255)
LOADER: Doing cleanup
LOADER: Freeing archive status for /Users/driggs/tmp/pyi_test/dist/hello.app/Contents/MacOS/hello
1/30/16 9:35:47.051 PM com.apple.launchd.peruser.501[275]: (com.myotisoft.hello.77648[50446]) Exited with code: 255
```

I launched the binary from within the .app as `./dist/hello.app/Contents/MacOS/hello` and its debug output is identical (except the tmpfile paths) until the `hello returned -1` line.

I tried commenting most of the "hello world" code out; importing `Tkinter` succeeds, but `root = Tk(); root.destroy()` fails with -1 when launched with `open`, succeeds when launched from commandline.

**Comment by riggsd** [comment]
Attempted compiling homebrew's tcl-tk `--with-threads` and without, same result. Double-click of the .app fails with -1, launching the binary inside the .app works correctly.

I'm all out of debugging ideas. 

Here's the contents of the generated `Info.plist`

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>

<key>CFBundleIdentifier</key>
<string>com.myotisoft.hello</string>

<key>CFBundleShortVersionString</key>
<string>0.0.0</string>

<key>CFBundleExecutable</key>
<string>MacOS/hello</string>

<key>CFBundleName</key>
<string>hello</string>

<key>CFBundleInfoDictionaryVersion</key>
<string>6.0</string>

<key>CFBundleDisplayName</key>
<string>hello</string>

<key>CFBundleIconFile</key>
<string>icon-windowed.icns</string>

<key>CFBundlePackageType</key>
<string>APPL</string>

<key>LSBackgroundOnly</key>
<string>0</string>

</dict>
</plist>
```

And the contents of the .app itself:

```
$ find hello.app/
hello.app/
hello.app//Contents
hello.app//Contents/Frameworks
hello.app//Contents/Info.plist
hello.app//Contents/MacOS
hello.app//Contents/MacOS/hello
hello.app//Contents/Resources
hello.app//Contents/Resources/icon-windowed.icns
```

**Comment by JokerQyou** [comment]
Actually I'm having the same problem. I have an application that uses PyQt4, but none of the PyQt related files get bundled into the `.app` folder, I think that might be on of the possible causes.

**Comment by amouma** [comment]
Same problem here. I've tried everything I can think of, including changing working directory from script at start. App runs ok if started from terminal with "open myapp.app/", but launches and quits immediately upon double-clicking.

Environment:
OS X 10.11.14
Python 3.5.1
PyQt5 (correctly bundled using custom hook)
Pyinstaller 3.2

**Comment by danauerbach** [comment]
Might get additional info by looking at the system.log in the console app.

**Comment by tallforasmurf** [comment]
Yeah, all you'll get is `Exited with code: 255` as shown in the first post. See the debug run in the second post:

    LOADER: Running hello.py
    hello returned -1
    LOADER: OK.
    LOADER: Cleaning up Python interpreter.
    LOADER: Back to parent (RC: 255)```

**Comment by amouma** [comment]
My script reads a text file on startup and that was the problem. I've changed to so it loads this text from a variable and it starts fine. 

So now it works, but there is another part in the app when files must be read from disk and I'm having the same problem. The file object is correctly instantiated, but the app crashes when I try to read the text into a variable. This is the code:
```
if os.path.exists(full_file_path):
  fobj = open(full_file_path, 'r')
  self.show_info_box("File found: " + full_file_path)    # Added for debugging. Shows fine
  text = fobj.read().replace('\n', '')      # App crashes here. Works fine unfrozen
  fobj.close()
```
The file is plain text, and is user-selected using QFileDialog. As you can see, I'm even using `os.path.exists` to make sure file I/O is not the problem. Needless to say, everything works flawlessly when running in unfrozen mode.

**Comment by tallforasmurf** [comment]
what is the full_file_path?

I am stuck trying to imagine any difference between using the `open` command for an app object, versus double-clicking the icon for the same object. They should amount to the same thing. What happens if you control-click/right-click on the app icon and select Open from the context menu?

**Comment by amouma** [comment]
`full_file_path` is something like `/Users/username/user_dir/text_file.txt`
I've been struggling with the same thing for a whole day. Googled everything and read Apple's man page on the `open` command (which states that it's the same as double-clicking on an .app). Tried changing things in `Info.plist`, creating an alias... can't think of anything else.

Right-clicking on the .app and selecting "Open" crashes just like double-clicking. I'm getting kind of desperate.

**Comment by riggsd** [comment]
@tallforasmurf, are you able to reproduce this bug with the simple example Tkinter program here, as I described in my first comment? https://docs.python.org/2/library/tkinter.html#a-simple-hello-world-program

**Comment by JokerQyou** [comment]
My suggestion here would be to use logging module to log as much log as
possible to a file, and when you have found which single line the problem
happens, add extra try/except to log the exact traceback info.

**Comment by riggsd** [comment]
When double-clicking the .app or executing with the `open` command, it dies on the following line:

    from Tkinter import *

It must be segfaulting (or something?), because the logging in my catch-all `except` clause doesn't get executed. All I can see at that point is that the OS gets a 255 return code.

Launching the same executables the following ways work as expected (Tk "hello world" gui comes up successfully):

    ./dist/hello
    ./dist/hello.app/Contents/MacOS/hello

**Comment by amouma** [comment]
I decided to rewrite the GUI using PyQt4. All is well now. I wish someone had told me this before, though!

**Comment by riggsd** [comment]
Completely uninstalled homebrew `python` and all related portions of development toolchain. Installed python.org Python 2.7.12 and ActiveTCL 8.6.4 (still on OS X 10.9.5).

I still get the exact same failure when double-clicking the .app or using `open` command. I can launch the non-app version in the `dist` directory from the commandline, and it works fine.

Uninstalled PyInstaller, installed `py2app`. It packages everything up just fine, the .app is runnable from my machine and launches perfectly from another (OS X 10.11) machine.

**Comment by cjrh** [comment]
Seems like #604 might have been related.

**Comment by camdenb** [comment]
I'm having this issue too trying to package a python file using libtcod.

**Comment by LoveBootCaptain** [comment]
i'm running in that issue to as well.
i run a little pygame program.
can't load it with double click, but form terminal no problem. binary runs good as well.
is there any progress on that issue. seems that there is no solution at all, when i google for that problem, nobody has a good solution :(

**Comment by xoviat** [comment]
Can you run this [this script here][1] and create a gist with the output?

```
dtruss -a -f pyinstaller_executable.app
```

[1]: https://github.com/joyent/dtruss-osx/blob/master/dtruss

**Comment by jmason86** [comment]
Same issue here with a pyside / Qt app. Works fine launching the unix executable (direct from terminal or double click from Mac Finder) but crashes on launch of the .app with console messages: 
Feb 14 22:38:48 Federation JPM_serial_reader_app[9880]: Failed to execute script serial_reader
Feb 14 22:38:48 Federation JPM_serial_reader_app[9880]: LOADER: OK.
Feb 14 22:38:48 Federation JPM_serial_reader_app[9880]: LOADER: Cleaning up Python interpreter.
Feb 14 22:38:48 Federation JPM_serial_reader_app[9878]: LOADER: Back to parent (RC: 255)
Feb 14 22:38:48 Federation JPM_serial_reader_app[9878]: LOADER: Doing cleanup
Feb 14 22:38:48 Federation JPM_serial_reader_app[9878]: LOADER: Freeing archive status for /Users/jmason86/Dropbox/Development/Python/Serial_Reader_Pyside_Qt/dist/JPM_serial_reader_app.app/Contents/MacOS/JPM_serial_reader_app
Feb 14 22:38:48 Federation com.apple.xpc.launchd[1] (JPM_serial_reader_app.13092[9878]): Service exited with abnormal code: 255

**Comment by jmason86** [comment]
@amouma When you got it to work under PyQt4, was the rest of your listed environment still the same? 
It's not working for me with: 
OS X 10.12.3
Python 2.7.11
pyside (though I see a qt4_plugins folder inside /dist/appname/Contents/MacOS)
Pyinstaller 3.2.1

**Comment by amouma** [comment]
Yes, everything was the same. I'm running Mac OS 10.11 though.

**Comment by LoveBootCaptain** [comment]
I think i have found a solution. For raspberry and Mac OS at least. Couldn't test Windows yet.
But it is working. I made a basic project template for a pygame-Game which imports a image file from a subfolder inside the project.

the key for me was that os.path.dirname(os.path.realpath(__file__)) as the "working directory" was not working for the mac.app when i double click the app. But launch from console was fine, launch the binary was fine, compile it on a raspberry and run the executable was fine.

now i used sys.path[1] and "rebuild" the last rest of the path "by hand". the reason why sys.path[0] sometimes is empty when running the double clicked as mac.app. when you launch from console with `open /Applications/Mac.app` it works cause sys.path[0] is not empty.

i hope you understand what i have done to get this working. my python and linux skills are not expert but i think it is easy to understand, when you have a look in the project files and the .spec file i use to create this.

i called it jenkins_test cause i wanted to have this woking in my CI-CD-Pipeline:
https://github.com/LoveBootCaptain/jenkins_test

hope you can use it and contribute.

kind regards from berlin

**Comment by htgoebel** [comment]
@LoveBootCaptain What are you talking about? This issue is about some tkinter program, not about pygame. And this tkinter program is not using `__file__` anywhere. Looks like you have a different isssue and want to read https://pyinstaller.rtfd.org/en/latest/runtime-information.html, which describe the correct way to access data-files at run-time. Alternatively you can use `pkg_resources.resource_filename()` (and related).

**Comment by LoveBootCaptain** [comment]
you are right... i commented the wrong ticket. sorry for that and thank you for your information.

**Comment by cajomferro** [comment]
Did someone find a solution for this? I am experiencing the same symptoms. Using pyinstaller 3.2.1 with PyQt5, I can generate the bundle both with --onedir and --onefile. Everything runs ok If I run the script on command line or double click. However running the .app it just open and closes immediately. The console log is completely useless. There is no error. Getting desperate here..any hints?!

**Comment by txdm** [comment]
Similar issue with a basic tkinter app. My .py runs as expected, but building with pyinstaller results in a .app that doesnt execute. The terminal version opens terminal and attempts to start but fails with this ouput:
`ImportError: dlopen(/var/folders/4c/7f_0hzss2413wmq3538w9jz00000gn/T/_MEIIpslzr/_tkinter.so, 2): Library not loaded: @loader_path/Tcl
  Referenced from: /var/folders/4c/7f_0hzss2413wmq3538w9jz00000gn/T/_MEIIpslzr/_tkinter.so
  Reason: no suitable image found.  Did find:
	/var/folders/4c/7f_0hzss2413wmq3538w9jz00000gn/T/_MEIIpslzr/Tcl: not a file
	/private/var/folders/4c/7f_0hzss2413wmq3538w9jz00000gn/T/_MEIIpslzr/Tcl: not a file
Failed to execute script`

**Comment by arvindsree** [comment]
Same issue with PyQt4 on mac

**Comment by htgoebel** [comment]
Hmm, looks like nobody is interested in solving this. Should I close the ticket or is somebody raising his/her hand?

**Comment by arvindsree** [comment]
Please don't close the ticket. This is a huge blocker. QT GUI is rendered useless now as we cannot create GUI mac apps using pyinstaller.

**Comment by htgoebel** [comment]
@arvindsree So you going to work on this?

**Comment by arvindsree** [comment]
I wish I could. But, I am fairly new to the mac app environment.

I tried the build environment on the new mac. (Looks like PyQT4 installation itself is broken -Qt website, brew install, port install fail). So I decided to upgrade my whole code to python3 and qt5. 
Seems like the issue is present with PyQt5 and python3 as well.

I suspect its got something to do with how the newer OSX interprets the Info.plist

**Comment by ErikBjare** [comment]
I thought I was having the same issue but fixed most of it.

 - macOS 10.12.6
 - Python 3.6
 - PyInstaller 3.3
 - PyQt 5.9

The app runs fine with `open ./ActivityWatch.app` but when it's doubleclicked it just closes immediately. Does anyone have an idea how to find out what is going wrong? It's a bit difficult since it runs just fine on the terminal (both `open ./ActivityWatch.app` and `./ActivityWatch.app/Contents/MacOS/aw-qt`).

**Comment by StefGre** [comment]
Hi there, 
i had the same problem, and i'd like to share how i fixed it in hope it can help somehow. 
the problem: bundled "myprogram" works fine when called from console within the MacOs directory, but double clicking the myprogram.App would fail and leave an obscure message "28/09/2017 09:43:05,778 com.apple.xpc.launchd[1]: (myprogram.491232[66301]) Service exited with abnormal code: 255"

I knew where the problem was in the code because it had worked just before the change. 

The line causing the problem was a numpy.loadtext("Directory/%s.txt" % (filename), unpack=True)
"Directory" being declared in the myprogram.spec as "datas=[ ('./Directory', './Directory') ]," 
   
I changed that line into:
np.loadtxt("%s/cf/%s.cf" % (Directory_path, self.name), unpack=True)

and declared earlier in the code:
Directory_path = resource_path("Directory")

where resource_path is declared earlier:
def resource_path(relative_path): # needed for bundling                                                                                                                            
    """ Get absolute path to resource, works for dev and for PyInstaller """
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

this later little piece of code helped me to fix some other problems... 

no being an expert i can't explane how and why. Hope it does fix your problem.

**Comment by ryanbaer** [comment]
@ErikBjare I've been checking out this project and I'm a big fan. Great work so far. I came here looking to find out if there was work in progress to make it so aw-qt doesn't show in the dock anymore, which it looks like there is?

Anyway, I noticed you had trouble finding more info about that macOS error code. That particular error code is: `errSecCSUnsigned: Code object is not signed.`

Here's a good resource for looking up macOS API errors:
https://osstatus.com/

**Comment by ErikBjare** [comment]
@ryanbaer Thanks a lot! That's actually really helpful. Perhaps some code signing is all that's needed, now I just have to figure that out...

**Comment by cesgarma** [comment]
Ok. Not pyinstaller, but using py2app I have the same problem stated here. I am using "moviepy" and using only the VideoFileClip import so I imported this way:

from moviepy.video.io.VideoFileClip import VideoFileClip

Reading the thread here I realized that is the line causing the problem. If I change to:

import moviepy

I can double click and open the bundle, but moviepy is really not working. I still need to import properly the object I need somehow. Bottom line I think I need to add the modules through py2app in the setup.py. I'll try that.

**Comment by lzkelley** [comment]
I'm not sure if this will be at all relevant for this discussion, but I was having a similar problem when packing an application using Electron (and a python backend).  After packaging using `electron-builder`, my app worked from the command line, but the python process failed when double-clicking the icon.  It turns out the problem is that when double-clicking, environment variables aren't carried over.  So in my case, it had no idea how to run `python` in the first place.  This package fixed it: https://www.npmjs.com/package/fix-path.

Perhaps in this (pyinstaller) case, one of the dependencies isn't actually being properly incorporated --- and this is only being seen when the environment variables aren't loaded?

**Comment by mishaturnbull** [comment]
Hoping this helps someone who finds this thread -- I was indeed able to solve my problem using StefGre's solution which I tweaked a bit to only return anything different on MacOS, since the program was working fine on Windows/Linux.  Here's what I came to:

```python
import sys
import os
import platform

_IS_MAC = platform.system() == 'Darwin'

def resource_path(relative_path):  # needed for bundling
    """Get absolute path to resource, works for dev and for PyInstaller"""
    if not _IS_MAC:
        return relative_path
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(
            os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)
```

However, I'm now stuck with what seems to be an inability to store user settings, which is one of the things that my application relies on (storing data offline until it can be uploaded later with Internet... seems like I can't do that).  If anyone's got a workaround for this, give me a mention!

**Comment by arvindsree** [comment]
StefGre's solution did not work for me btw. However p2app with python3 qt5 worked for me. So I went ahead with that

**Comment by bw4sz** [comment]
Throwing my hat in here as well. I had a perfectly functioning app before add moviepy module. There is a separate thread over here

https://github.com/Zulko/moviepy/issues/263

App opens in every conceivable way even

```
open -a "myApp"
```
except for double click.

Only broke after adding moviepy. Will report back if solved.

**Comment by ecc86** [comment]
I have had the same problem and found a possible solution here: 
[Stackoverflow Link](https://stackoverflow.com/questions/26176169/pyinstaller-os-x-app-runs-from-command-line-but-not-finder-window)

> This is most likely due to a bad assumption about the working directory. When you launch from the Finder, the working directory may well be / (depends on OS X version), which is not writeable. If your app writes to the current working directory then you should probably set the working directory to somewhere sensible at startup.
(by [Paul R](https://stackoverflow.com/users/253056/paul-r))

It seems my app when launched via click on the .app somehow uses root / as working directory. 

To check I inserted a logging feature to check if my program runs on root. 
After all my import statements I added:

```python
import os
import syslog

APP_NAME = 'My App'
# Define identifier for Mac Console Logging
syslog.openlog(APP_NAME)
# Record a message
working_dir = 'Working dir: %s' % (os.getcwd())
syslog.syslog(syslog.LOG_ALERT, working_dir)`
```

(see [Stackoverflow Link](https://stackoverflow.com/questions/2244153/how-to-log-python-program-activity-in-mac-os-x))

The problem in my case seemed to be caused by a config file that resided within my main script's folder. To read and write to it I originally did not point to it with a path. I Now wrote the file to the Users Application Support Folder and pointed to it with an absolute path. I luckily use Pyglet anyway in my script so I could use [This](https://pythonhosted.org/pyglet/programming_guide/saving_user_preferences.html).

My Code now includes this:

```python
from pathlib import Path
import configparser
import os
import pyglet

dir = pyglet.resource.get_settings_path(APP_NAME)
if not os.path.exists(dir):
    os.makedirs(dir)
os.chdir(dir) # just for safety
CONFIGFILE = Path(os.path.join(dir, 'config.ini'))

# (...)

class Config(configparser.ConfigParser):
    def set_defaults(self):
        self['WINDOW'] = {
            'win_width': '400',
            'win_height': '400',

# (...)

if __name__ == "__main__":
    config = Config()
    if CONFIGFILE.is_file():
        config.read(CONFIGFILE)
    else:
        config.set_defaults()
        with open('config.ini', 'w') as CONFIGFILE:
            config.write(CONFIGFILE)
```

**Comment by jongiambi** [comment]
Same issue on Mac OS 10.12.6 (16G1212).

Pyinstaller Version: 3.3.1
Python: 3.5.3

Only running from terminal with `./app_name` works. Double clicking results in import errors (relating to Tensorflow - even though imports are confirmed packaged in one_dir mode). 

To get around this I've created an AppleScript that looks like a .app and launches the app via `./`

Possibly related to Python path? 

Heres the exact error dump:

```
[7603] LOADER: _MEIPASS2 is /var/folders/nd/g6cky20d52q30yx9fh3fbn840000gn/T/_MEIxuyumh
[7603] LOADER: archivename is /Users/jongiambattista/Documents/Builds/TestApp
[7603] LOADER: Already in the child - running user's code.
[7603] LOADER: Python library: /var/folders/nd/g6cky20d52q30yx9fh3fbn840000gn/T/_MEIxuyumh/Python
[7603] LOADER: Loaded functions from Python library.
[7603] LOADER: Manipulating environment (sys.path, sys.prefix)
[7603] LOADER: Pre-init sys.path is /var/folders/nd/g6cky20d52q30yx9fh3fbn840000gn/T/_MEIxuyumh/base_library.zip:/var/folders/nd/g6cky20d52q30yx9fh3fbn840000gn/T/_MEIxuyumh
[7603] LOADER: sys.prefix is /var/folders/nd/g6cky20d52q30yx9fh3fbn840000gn/T/_MEIxuyumh
[7603] LOADER: Setting runtime options
[7603] LOADER: Initializing python
[7603] LOADER: Overriding Python's sys.path
[7603] LOADER: Post-init sys.path is /var/folders/nd/g6cky20d52q30yx9fh3fbn840000gn/T/_MEIxuyumh/base_library.zip:/var/folders/nd/g6cky20d52q30yx9fh3fbn840000gn/T/_MEIxuyumh
[7603] LOADER: Setting sys.argv
[7603] LOADER: setting sys._MEIPASS
[7603] LOADER: importing modules from CArchive
[7603] LOADER: extracted struct
[7603] LOADER: callfunction returned...
[7603] LOADER: extracted pyimod01_os_path
[7603] LOADER: callfunction returned...
[7603] LOADER: extracted pyimod02_archive
[7603] LOADER: callfunction returned...
[7603] LOADER: extracted pyimod03_importers
[7603] LOADER: callfunction returned...
[7603] LOADER: Installing PYZ archive with Python modules.
[7603] LOADER: PYZ archive: out00-PYZ.pyz
[7603] LOADER: Running pyiboot01_bootstrap.py
[7603] LOADER: Running pyi_rth__tkinter.py
[7603] LOADER: Running pyi_rth_mplconfig.py
[7603] LOADER: Running pyi_rth_mpldata.py
[7603] LOADER: Running pyi_rth_multiprocessing.py
[7603] LOADER: Running pyi_rth_pkgres.py
[7603] LOADER: Running pyi_rth_traitlets.py
[7603] LOADER: Running pyi_rth_qt5.py
[7603] LOADER: Running init.py
Using TensorFlow backend.
ERROR: <class 'tensorflow.python.framework.errors_impl.NotFoundError'>
Traceback (most recent call last):
  File "init.py", line 195, in <module>
  File "init.py", line 161, in run_from_GUI
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/keras/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/keras/activations.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/keras/engine/__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/keras/engine/training.py", line 25, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/keras/callbacks.py", line 26, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/tensorflow/contrib/__init__.py", line 27, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/tensorflow/contrib/cudnn_rnn/__init__.py", line 28, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/tensorflow/contrib/cudnn_rnn/python/ops/cudnn_rnn_ops.py", line 34, in <module>
  File "site-packages/tensorflow/contrib/util/loader.py", line 55, in load_op_library
  File "site-packages/tensorflow/python/framework/load_library.py", line 64, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: dlopen(site-packages/tensorflow/contrib/util/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/_cudnn_rnn_ops.so, 6): image not found
[7603] Failed to execute script init
[7603] LOADER: OK.
[7603] LOADER: Cleaning up Python interpreter.
[7601] LOADER: Back to parent (RC: 255)
[7601] LOADER: Doing cleanup
```

**Comment by Legorooj** [comment]
@jongiambi please see #4704 
Closing - stale.

**Comment by Merkwurdichliebe** [comment]
This issue is identical when using py2app on Catalina. This is apparently not specific to pyinstaller. Any obvious fix found since the thread was closed?

**Comment by Legorooj** [comment]
@Merkwurdichliebe I suggest that you open a new issue; the newer developers can help track this down.

**Comment by htgoebel** [comment]
As the traceback clearly shows, this is an issue with tensorflow.

**Comment by utsavDave97** [comment]
> Hoping this helps someone who finds this thread -- I was indeed able to solve my problem using StefGre's solution which I tweaked a bit to only return anything different on MacOS, since the program was working fine on Windows/Linux. Here's what I came to:
> 
> ```python
> import sys
> import os
> import platform
> 
> _IS_MAC = platform.system() == 'Darwin'
> 
> def resource_path(relative_path):  # needed for bundling
>     """Get absolute path to resource, works for dev and for PyInstaller"""
>     if not _IS_MAC:
>         return relative_path
>     base_path = getattr(sys, '_MEIPASS', os.path.dirname(
>             os.path.abspath(__file__)))
>     return os.path.join(base_path, relative_path)
> ```
> 
> However, I'm now stuck with what seems to be an inability to store user settings, which is one of the things that my application relies on (storing data offline until it can be uploaded later with Internet... seems like I can't do that). If anyone's got a workaround for this, give me a mention!

@mishaturnbull Would you please tell me where to put this code and how to activate this method?

**Comment by Legorooj** [comment]
Please open a new issue if you're still having this problem.
