### ISSUE TITLE
PyInstaller + PyGame gives (pygame parachute) Segmentation Fault

### ISSUE THREAD

**Issue by orsenthil** [pyinstaller/pyinstaller#1805]
The way PyInstaller bundles the python files, it does not work properly with pygame and throws Segmentation Fault.

```
18:53 $ /Users/senthilkumaran/custompython/memorypuzzle/dist/memorypuzzle ; exit;
Fatal Python error: (pygame parachute) Segmentation Fault
Abort trap: 6
logout
```

* I used py2app to bundle the pygame code and was able to [bundle it properly](https://www.dropbox.com/sh/5mjmdm4s5bxx381/AABPOIpaqZiRZ0K7B1d2fG5Ka?dl=0).

* I am on Python 2.7.11 from www.python.org. Installed in a custom directory, with --enabled-shared
* I installed pip in this custom directory directly using get-pip.py
* I Installed both stable version of PyInstaller and development verison of PyInstaller and I can reproduce this bug in both.

```
✔ ~/custompython
18:52 $ ./bin/pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Downloading https://github.com/pyinstaller/pyinstaller/archive/develop.zip
     | 3.2MB 8.6MB/s
Requirement already satisfied (use --upgrade to upgrade): setuptools in ./lib/python2.7/site-packages (from PyInstaller==3.2.dev0+d8c1f45)
Installing collected packages: PyInstaller
  Found existing installation: PyInstaller 3.1.1
    Uninstalling PyInstaller-3.1.1:
      Successfully uninstalled PyInstaller-3.1.1
  Running setup.py install for PyInstaller ... done
Successfully installed PyInstaller-3.2.dev0+d8c1f45
```

Please do not dismiss this as Pygame bug, since I am able to bundle this using py2app, it's worth investigating what could be the problem with PyInstaller. The bug is reproducible in both directory (default) mode as well as in Single file binary mode.

**Comment by htgoebel** [comment]
@orsenthil There is no chance for us tracking this down with the given information. Please provide *much* more details, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs. Or even better: try tracking this down yourself, since you have the environment triggering this error.
