### ISSUE TITLE
"No module named archive.writers"

### ISSUE THREAD

**Issue by ShawnHL** [pyinstaller/pyinstaller#1806]
I tried to turn a .py file to a .exe file by using pyinstaller,but then it shows:
"ImportError: No module named archive.writers".
(It occurs when python tried to import "ZlibArchiveWriter & CArchiveWriter" from PyInstaller.archive.writers)
I really don't know what should I do now...

**Comment by htgoebel** [comment]
Please provide more information, other wiese we are not able to help you. See https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by htgoebel** [comment]
Closing. Not enough info to even think about investigating this.
