### ISSUE TITLE
Make PyInstaller version available at runtime

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1807]
We could e.g. on the fly generate a mini-script which sets some value in `sys` (maybe even `sys.frozen`)

**Comment by virtuald** [comment]
+1

**Comment by htgoebel** [comment]
**How to implement this?**
Several options for implementing this:

1. generate a mini-script on the fly
2. put the information into an OPTION entry and either

   1. evaluate the option in the bootloader
   1. evaluate the option in an additional boot-script

IMHO, option 1 is the best, since it is most flexible and easy to implement

Opinions?
**What information to store?**

I propose using a named tuple-like datastruct like `sys.version_info` with an additional first element 'product', which is st to `PyInstaller`. This would allow differentiating between different freezers (py2app, py2exe, etc.) One never know what this may be useful for :-)

**Where to store this?**

I propose storing this into `sys.frozen`, which up-to-now is only tested for existence in all cases I know.

**Comment by Legorooj** [comment]
We gonna do anything about this then?

**Comment by bwoodsend** [comment]
I'm going to park this given how little interest there has been since 2016. Feel free to post below if you believe that you have a compelling use case for it.
