### ISSUE TITLE
Exe made with pyinstaller does not run. 

### ISSUE THREAD

**Issue by OscarEReyes** [pyinstaller/pyinstaller#1808]
I decided to try again with something simpler that just prints "Hello World." But, it still does not run. Now someone told me to drag the exe to the command line and see what it says. But it says nothing. I drag, run, and it just goes to the next line and displays a blinking underscore indefinitely.  Is there anything that I am doing wrong?

**Comment by tallforasmurf** [comment]
I don't see another issue by you, closed or open. Nor any message from you in the google group message list. So some detail would help. What OS? What version of Python? What does PyInstaller print out while it makes the app? Try running with the `--debug` option, this makes the bootloader print messages while it initializes when you run the app.

**Comment by OscarEReyes** [comment]
My bad, Windows 8.1 64 bit, python 3.4. It prints nothing which lead me to ask. And do i add --debug when I try to run the exe?

**Comment by KeyWeeUsr** [comment]
Similar to my issue? #1767

**Comment by htgoebel** [comment]
@OscarEReyes: Please follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs. Oterhwise we will not be able to help you.
