### ISSUE TITLE
Linux PyQt5+QML QXcbIntegration error

### ISSUE THREAD

**Issue by yzinets** [pyinstaller/pyinstaller#1809]
Sorry for my bad English.
I have minimal working app and build it without .spec file using only command. But when I run result program, it gives an error. 
System: Antergos(Archlinux+Openbox)
Python 3.5.1
PyInstaller 3.1

glxgears works well. 
![2016-02-03-214550_1366x768_scrot](https://cloud.githubusercontent.com/assets/17050536/12791242/dd880a16-caae-11e5-87ca-9f6134bc7b62.png)

Logs:
[build_log.txt](https://github.com/pyinstaller/pyinstaller/files/116102/build_log.txt)
[run_log.txt](https://github.com/pyinstaller/pyinstaller/files/116103/run_log.txt)

Program:

```
import sys
from PyQt5 import QtCore, QtWidgets, QtQuick

if __name__ == "__main__":
    myApp = QtWidgets.QApplication(sys.argv)
    appLabel = QtQuick.QQuickView()
    appLabel.setSource(QtCore.QUrl('basic.qml'))
    appLabel.show()
    myApp.exec_()
    sys.exit()
```

QML:

```
import QtQuick 2.0

Rectangle {
    width: 250; height: 175

    Text {
        id: helloText
        anchors.verticalCenter: parent.verticalCenter
        anchors.horizontalCenter: parent.horizontalCenter
        text: "Hello World!!!\n Traditional first app using PyQt5"
        horizontalAlignment: Text.AlignHCenter
    }
}
```

**Comment by uetoyo** [comment]
Do you use VirtualBox or is it a normal installation?

**Comment by htgoebel** [comment]
Please build you program using `--debug`, see https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong

**Comment by cornellitchi** [comment]
This is not VM.
Here is debug log.
[run_debug.txt](https://github.com/pyinstaller/pyinstaller/files/119265/run_debug.txt)

**Comment by uetoyo** [comment]
I thing this problem with some OpenGL settings; use `glxinfo` and send a log.

**Comment by cornellitchi** [comment]
[glxinfo_log.txt](https://github.com/pyinstaller/pyinstaller/files/119435/glxinfo_log.txt)

**Comment by uetoyo** [comment]
Try load glx module in `/etc/X11/xorg.conf`.

**Comment by uetoyo** [comment]
Ok, try this `qmlscene /path/to/your.qml`

**Comment by cornellitchi** [comment]
qmlscene is working

![2016-02-05-231210_1366x768_scrot](https://cloud.githubusercontent.com/assets/17050536/12854868/c41a6ef6-cc44-11e5-9aae-9a658f39d2b2.png)

**Comment by cornellitchi** [comment]
Haven't /etc/X11/xorg.conf

**Comment by cornellitchi** [comment]
Haven't /etc/X11/xorg.conf

**Comment by uetoyo** [comment]
:)

**Comment by cornellitchi** [comment]
Sorry, I'm not so good in Linux :)
![2016-02-05-204350_1366x768_scrot](https://cloud.githubusercontent.com/assets/17050536/12855730/be583624-cc49-11e5-9bda-7f913b7dcad6.png)

**Comment by uetoyo** [comment]
> Sorry, I'm not so good in Linux :) 

Me neither, I am on Windows OS now, but glx module shoul be enabled ... read a documentation for your Linux dist.

```
Section "Module"
    Load           "glx"
EndSection
```

**Comment by CLitchi** [comment]
Okay. Which linux OS can build this from-a-box?

**Comment by CLitchi** [comment]
Okay x2. Installed Linux Mint, libs and other stuff. Now have:
FileNotFoundError: Path or glob "QtQml" not found or matches no files

**Comment by uetoyo** [comment]
@CLitchi Please post your code
.

**Comment by cornellitchi** [comment]
Code is the same as in the first message. I always put basic.qml in the same folder with executable.
Problem with glx appears only when I'm using QML. It's sad...

**Comment by Insoleet** [comment]
I have the same problem with the following situation : 
- I build my application with a fresh ubuntu 14.04 install
- I distribute my application to an upgraded ubuntu 14.04 install, the app crashes with the following errors : 

```
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled

(sakia:11731): Gtk-CRITICAL **: IA__gtk_widget_style_get: assertion 'GTK_IS_WIDGET (widget)'
```

It looks like PyInstaller is packaging too much libraries, with some libraries not being backward compatible ?

**Comment by Insoleet** [comment]
Some updated information : 

- If I run my source code with python, QtWebEngine runs without any problem
- If I package it using pyinstaller and run it, QtWebEngine crashes : 

```
$ ./sakia 
static QPlatformTheme* QKdeTheme::createKdeTheme(): Unable to determine KDE dirs
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
QOpenGLWidget: Failed to create context
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
composeAndFlush: makeCurrent() failed
[1]    25096 segmentation fault (core dumped)  ./sakia
```

**Comment by estebes** [comment]
Anyone found any solution for this?

**Comment by uetoyo** [comment]
@estebes I will try it on my linux machine.

**Comment by yggdr** [comment]
I'm running into the same problem here in Ubuntu 16.04 (VBox) and 16.10 (native). Has anyone accomplished anything regarding this issue?

**Comment by smearumi** [comment]
I'm using Fedora 24 and I've solved the 'QXcbIntegration error' problem as follows:

After finishing the execution of pyinstaller:

1. Remove everything inside the directory <package_directory>/qt5_plugins/
2. Copy everything from /usr/lib64/python3.5/site-packages/PyQt5/Qt/plugins/ and Paste to <package_directory>/qt5_plugins/

These steps should solve this issue.

**Comment by htgoebel** [comment]
Seem to be solved.
