### ISSUE TITLE
pyinstaller fails for pandas on mac os x

### ISSUE THREAD

**Issue by behollis** [pyinstaller/pyinstaller#1815]
trying simple following script. already tested simple numpy, matplotlib scripts with pyinstaller.
```
import pandas
import matplotlib.pyplot as plt
from pandas.tools.plotting import parallel_coordinates
sampdata = pandas.read_csv('/usr/local/lib/python2.7/site-packages/pandas/tests/data/iris.csv')
parallel_coordinates(sampdata, 'Name')
plt.show()
```
```
$ ./pandastest 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller-3.1.1-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "pandas/__init__.py", line 13, in <module>
ImportError: C extension: dlopen(/var/folders/_m/74p6ddhs70z4v8z7pcrsgwbh0000gn/T/_MEILskpr5/numpy.core.multiarray.so, 2): Symbol not found: ___addtf3
  Referenced from: /var/folders/_m/74p6ddhs70z4v8z7pcrsgwbh0000gn/T/_MEILskpr5/libquadmath.0.dylib
  Expected in: /var/folders/_m/74p6ddhs70z4v8z7pcrsgwbh0000gn/T/_MEILskpr5/libgcc_s.1.dylib
 in /var/folders/_m/74p6ddhs70z4v8z7pcrsgwbh0000gn/T/_MEILskpr5/libquadmath.0.dylib not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace' to build the C extensions first.
pandastest returned -1
```

**Comment by behollis** [comment]
i believe this is an issue with pyinstaller packing the default mac ox python versus the one that was installed via brew. i get the same issue above when running the pandas python script via the original apple python. i don't when i use the brew installed  python.

since i have the env var PYTHONEXECUTABLE set to the brew python and have that in my PATH var, i'm not sure how to force pyinstaller to use the proper python executable / interpreter in the produced exe. by default , the brew python is invoked on my command line.

**Comment by tallforasmurf** [comment]
I believe PyInstaller bundles the same Python that is executing PyInstaller. See https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/build_main.py#L343 and following. That's why http://pythonhosted.org/PyInstaller/#supporting-multiple-python-environments recommends using VENV for each Python version.

**Comment by htgoebel** [comment]
@behollis Could you solve this issue using venv?

**Comment by behollis** [comment]
Hi Hartmut,

Thanks for checking in on this. I'm currently preparing a conference 
talk and haven't had a chance to revisit the problem yet.

I'll let you know if the suggestions work or not soon.

Regards,
Brad

**Comment by htgoebel** [comment]
So I'm closing this for now. When you had a chance to revisit the problem, please report here. And, of course, reopen the issue if necessary.

**Comment by behollis** [comment]
Okay, so when trying to use virtualenv, the matplotlib backends apparently won't work:  

http://matplotlib.org/faq/virtualenv_faq.html

However, their workaround is to use the system python which will likely cause PyInstaller to not work.
