### ISSUE TITLE
Docs: hints

### ISSUE THREAD

**Issue by pepperminze** [pyinstaller/pyinstaller#1816]
Today I had my first session with pyinstaller, and finally it worked! Thanks for the pyinstaller and the possibility to build a single file exe!

Background: Casual programmer, WinXP, Python34
I'm referring to the Docs on http://pythonhosted.org/PyInstaller/

1. Shortening the Command
The hint to BATCHfile is valuable. But it took me quite a while, before I remembered, that I can make the console stay open. For debugging purposes. Suggestion: Add a line "pause>nul"

2. Using a console window
Yes, I would have liked to. But I cound't see it. May be it popped up somewhere in the background, but I never noticed. And when I closed my programm, no console to be seen to check for errors.
Suggestion: Add an option that makes the console stay open for debbuging purposes.

3. Adding files to a bundle
I had an issue with 2 images that wound't show. To speed up error detection a hint that the datafiles are stored in the programfolder directly and not hidden somewhere in subfolders could be nice.

4. When things go wrong
Suggestion: Give the now "how to report bugs" page a name like "how to find out if it's bug". Then it's more obvious that there are some hints on debugging
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

5. data: how to link?!
My data links in the program failed to work after bundling (import images to display). No hint that this would occur and how to solve it. With google I luckiliy found someone who solved it that way (or via try/except):

        if getattr( sys, 'frozen', False ) :
            self.image_dir = sys._MEIPASS       
        else:
            self.image_dir = os.path.dirname(__file__)

Is that a good idea? I don't know. For now it works.

**Comment by tallforasmurf** [comment]
> (1)  Suggestion: Add a line "pause>nul"

I supposed that  you would run a batch command from the command line in a command window. Why does it close? You should see all the 100+ lines of PyInstaller output, and then be able to do `dir dist` and so on.

> (3) ...  a hint that the datafiles are stored in the programfolder directly and not hidden somewhere in subfolders..

http://pythonhosted.org/PyInstaller/#adding-data-files shows that the destination `"."` sends the copied file "into the top level of the bundled app". But please suggest some better wording or another example.

> (5) ...My data links in the program failed to work after bundling (import images to display)...

The code you show is also here: http://pythonhosted.org/PyInstaller/#run-time-information. That section has other suggestions on how to find data files in different situations.

**Comment by pepperminze** [comment]
Am 07.02.2016 20:51, schrieb Nat Picker:
>
>     (1) Suggestion: Add a line "pause>nul"
>
> I supposed that you would run a batch command from the command line in 
> a command window. Why does it close? You should see all the 100+ lines 
> of PyInstaller output, and then be able to do |dir dist| and so on.
>
Ah, that's the way. What I did: I wondered how to run a batch file. 
Thought a little of the way you suggest, but then decided to double 
click on the bat file.

>     (3) ... a hint that the datafiles are stored in the programfolder
>     directly and not hidden somewhere in subfolders..
>
> http://pythonhosted.org/PyInstaller/#adding-data-files shows that the 
> destination |"."| sends the copied file "into the top level of the 
> bundled app". But please suggest some better wording or another example.
>
Ah, right. May be that's an issue, because I'm not english native, only 
casual programming, and I was already struggling some hours to set up 
things before I came to that point. For me "top level folder" would habe 
been easier to grasp.
>
>     (5) ...My data links in the program failed to work after bundling
>     (import images to display)...
>
> The code you show is also here: 
> http://pythonhosted.org/PyInstaller/#run-time-information. That 
> section has other suggestions on how to find data files in different 
> situations.
>
Ah, for me "runtime xy" sounds for being something for professionals. I 
didn't have a clear understanding of what it means. For folks like me 
add a line in the section "Adding data files" like: "Don't forget to 
adjust the paths in your program as described in the section 
"runtime-information"."

**Comment by htgoebel** [comment]
Thanks for your comments.pepperminze already answered most of you questions.

> (4) When things go wrong
> Suggestion: Give the now "how to report bugs" page a name like "how to find out if it's bug". Then it's more obvious that there are some hints on debugging

This is what https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong is for.

**Comment by tallforasmurf** [comment]
> add a line in the section "Adding data files" like: "Don't forget to adjust the paths in your program as described in the section "runtime-information"."

Well I was about to do that when I noticed that at the top of the "adding data files" section (http://pythonhosted.org/PyInstaller/#adding-files-to-the-bundle) it already says,

> To find the data files at run-time, see Run-time Information.

So not much to add to that.

**Comment by pepperminze** [comment]
Ah!
Well, yes, it could be stated more clearly.  One problem for me was the 
term run-time. The next is, the beginning of the sentence doesn't alert 
me. When I come to that point I've been reading docs for some hours and 
may there is still a way to go. Far not every paragraph contains 
information, that I need now. How decide what to read more carfully. So 
for me a clear hint, that I have to change the code, would have been 
useful. Something like:
"To find data files at run-time, adjust your code as described in 
Run-time Information."


Am 12.02.2016 22:44, schrieb Nat Picker:
