### ISSUE TITLE
linux - more secure bootloader: use  -D_FORTIFY_SOURCE=2

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1820]
I recently found out that fedora uses the gcc option `-D_FORTIFY_SOURCE=2` to produce more secure binaries.

We should consider using this option for linux bootloaders:
https://stackoverflow.com/questions/13517526/difference-between-gcc-d-fortify-source-1-and-d-fortify-source-2

@htgoebel What do you think?

**Comment by htgoebel** [comment]
I like this idea. Perhaps there are other options we can use? (I'm not a C-user, I can not tell)
