### ISSUE TITLE
Trojan found during installation

### ISSUE THREAD

**Issue by Madsvj** [pyinstaller/pyinstaller#1821]
I just started working at this new company. Obviously I wanted to install pyinstaller, and during the unpacking (using pip install) "symantec Endpoint Protection" (the anti malways system at the company) went all crazy and deleted the unpacking exe file and even blocked me from using python (fixed that though). 

Have you ever experienced anything like that? 

Tl;dr Company anti malwares stops and deletes installing files during unpacking because of Trojan detected.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is nothing(!) we can do here.

See [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
