### ISSUE TITLE
linux pyqt5 python3

### ISSUE THREAD

**Issue by pohmelie** [pyinstaller/pyinstaller#1826]
Trying to build app, which use `.ui` file for creating gui. I add `datas=[("gui.ui", "."), ("favicon.png", ".")]` to my spec file. If I build it with `-D` everything is fine, I see my files in directory and app running as expected. But in case of `-F` I got message, that there is no `gui.ui` file:
```
FileNotFoundError: [Errno 2] No such file or directory: 'gui.ui'
```
It looks like there was such issues already, but they were solved via converting `.ui` to `.py`. I will provide more info if necessary.

**Comment by tallforasmurf** [comment]
How does your code use a .ui file? Does it call `PyQt5.uic.compileUi()` or similar method from this page[1]? If so, the code has to pass the open .ui file as the first argument. How does it locate that file?

[1] http://pyqt.sourceforge.net/Docs/PyQt5/designer.html?highlight=.ui#the-uic-module

**Comment by pohmelie** [comment]
I use http://pyqt.sourceforge.net/Docs/PyQt5/designer.html?highlight=.ui#PyQt5.uic.loadUi
``` python
from PyQt5 import QtGui, QtCore, QtWidgets, uic
...
    def __init__(self, ...):
        ...
        uic.loadUi("gui.ui", self)
```

**Comment by tallforasmurf** [comment]
Yes. Unfortunately Phil has not documented how this (or any of the other functions on that page) treat the "uifile" parameter when it is a relative filename. Obviously it is not looking in the temp directory used by the one-file app. I would speculate that it looks where `__file__` points. As documented (http://pythonhosted.org/PyInstaller/#run-time-information), `__file__` is unreliable in a bundled app.

Your code should form a complete, absolute path string and pass that to `uic.loadUi`. Use code like what is shown in the above-linked topic, for example

     if getattr(sys, 'frozen', False):
          # we are running in a bundle
          bundle_dir = sys._MEIPASS
     else:
          # we are running in a normal Python environment
          bundle_dir = os.path.dirname(os.path.abspath(__file__))
    guicpath = os.path.join( bundle_dir, 'gui.ui' )

**Comment by pohmelie** [comment]
@tallforasmurf, works fine. Thank you.
