### ISSUE TITLE
Python3 Kivy (with SDL2) fails to build properly on OSX, dlopen error

### ISSUE THREAD

**Issue by synapse211** [pyinstaller/pyinstaller#1828]
I'm trying to compile an application with pyinstaller on OSX using Py3 and Kivy. The build goes through fine, and it works on the machine that built it, but not on a machine that doesn't have sdl2, sdl2_image, etc... installed from brew.

I narrowed the problem down to _img_sdl2 in Kivy, attached the source of test.py and test.spec in the zip: [pyinstallerbug.zip](https://github.com/pyinstaller/pyinstaller/files/134445/pyinstallerbug.zip)

I get the following error message when running it on the test machine:

> [ERROR  ] [ImageSDL2   ] Failed to init required 1 support
> [ERROR  ] [ImageSDL2   ] b'Failed loading libjpeg.dylib: dlopen(libjpeg.dylib, 6): image not found'
> [ERROR  ] [ImageSDL2   ] Failed to init required 2 support
> [ERROR  ] [ImageSDL2   ] b'Failed loading libpng.dylib: dlopen(libpng.dylib, 6): image not found'
> [ERROR  ] [ImageSDL2   ] Failed to init required 4 support
> [ERROR  ] [ImageSDL2   ] b'Failed loading libtiff.dylib: dlopen(libtiff.dylib, 6): image not found'
> [ERROR  ] [ImageSDL2   ] Failed to init required 8 support
> [ERROR  ] [ImageSDL2   ] b'Failed loading libwebp.dylib: dlopen(libwebp.dylib, 6): image not found'

The latest stable pyinstaller and also the current dev pyinstaller fails to produce a working end result.
Also, in dist there's libpng16.16.dylib, I tried symlinking it to libpng16.dylib, libpng.dylib, but none of that worked. Also tried DYLD_LIBRARY_PATH / DYLD_FALLBACK_LIBRARY_PATH set to the proper locations, that failed as well.

```
versions:
pyinstaller: 3.2.dev0+ge99e483
Kivy: Kivy==1.9.1
Python 3.5.1
```

I also uploaded a built.zip with the actual output here: [http://www.filedropper.com/built](url)
Sorry for the 3rd party site, github did not let me upload it as it's too large.

**Comment by htgoebel** [comment]
This messages all say "image not found", so I assume you did not include all your data or trying to access it using wrong paths. Please refer to https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

**Comment by synapse211** [comment]
If by image you mean the actual png file I try to open, it's there. Even if it wasn't it should be a FileNotFound exception, not this. Also I did everything according to the linked document before posting the initial report.

Furthermore, the compiled binary works on the machine that built it, but not on a machine that is a fresh install. This suggests that the libpng library is being found through other means.

I have tried the same file with an ubuntu machine. It works fine, although I had to add "gi" to excludes (had no gtk installed), and I modified the image path to one that exists on both machines. All is well here.

With the OSX version this is the place where the error comes from (line 21):
https://github.com/kivy/kivy/blob/master/kivy/core/image/_img_sdl2.pyx

Here IMG_Init() fails. I kept digging.

For the ubuntu version these are the files that are linked to libpng according to ldd:
```
kivy.core.image._img_sdl2.cpython-34m-x86_64-linux-gnu.so
kivy.core.text._text_sdl2.cpython-34m-x86_64-linux-gnu.so
kivy.core.window._window_sdl2.cpython-34m-x86_64-linux-gnu.so
libfreetype.so.6
libSDL2_image-2.0.so.0
libSDL2_ttf-2.0.so.0
```

On OSX, only this file links to libpng according to otool -L:
`libfreetype.6.dylib`

I don't know how relevant this is as clearly the osx dynamic loader works very differently from linux's and I'm not familiar with it at all.

Here are the full lists:
ubuntu: ldd *.so
osx: otool -L *.so; otool -L *.dylib (I concatenated the two outputs)
[linked_files_ubuntu.txt](https://github.com/pyinstaller/pyinstaller/files/136210/linked_files_ubuntu.txt)
[linked_files_osx.txt](https://github.com/pyinstaller/pyinstaller/files/136216/linked_files_osx.txt)

I hope this helps.

**Comment by htgoebel** [comment]
According to https://www.libsdl.org/projects/SDL_image/docs/SDL_image.html `IMG_Init()` does not read an image file. So I assume you are right about some library missing.

Have you tried `strace` (or whatever it is called on OS X)?

**Comment by synapse211** [comment]
I tried dtruss, which did not show much, no open() is visible. However, you can do some nifty things with DYLD. DYLD_PRINT_LIBRARIES prints out what is happening in the linker.

build machine:
```
$ DYLD_PRINT_LIBRARIES=1 ./dist/test/test 2>&1| grep libpng
dyld: loaded: /Users/vagrant/pyinstallerbug/dist/test/libpng16.16.dylib
dyld: loaded: /usr/local/lib/libpng.dylib
```

vanilla machine:
```
$ DYLD_PRINT_LIBRARIES=1 ./dist/test/test 2>&1| grep libpng
dyld: loaded: /Users/synapse/pyinstallerbug/dist/test/libpng16.16.dylib
[ERROR  ] [ImageSDL2   ] b'Failed loading libpng.dylib: dlopen(libpng.dylib, 6): image not found'
```

Here are the full logs (with kivy debug output interspersed, sorry, grep for "dyld:"):
[linker_buildserver.txt](https://github.com/pyinstaller/pyinstaller/files/136765/linker_buildserver.txt)
[linker_vanilla.txt](https://github.com/pyinstaller/pyinstaller/files/136766/linker_vanilla.txt)

From the output of the vanilla machine the last 4 lines are notably missing, the earliest libpng load is due to libfreetype I think. The 4 lines are:
```
dyld: loaded: /usr/local/lib/libjpeg.dylib
dyld: loaded: /usr/local/lib/libpng.dylib
dyld: loaded: /usr/local/lib/libtiff.dylib
dyld: loaded: /usr/local/lib/libwebp.dylib
```

Exactly what it complains about. I think there is some special machinery here that loads these dynamically at runtime, as they don't show up in otool. If I copy libpng.dylib into the built directory, it does not work. If I copy over the library and use DYLD_FALLBACK_LIBRARY_PATH, it does load the libpng library.

**Comment by htgoebel** [comment]
If you just copy the dylibs to the build-directory, this will not make them appear in the application bundle.

I suggest trying a hook `hook-kivy.core.image._img_sdl2` (if this does not get pulled, use just `...core.image`) adding these libs as `binaries` (see https://pythonhosted.org/PyInstaller/#hook-global-variables and refer to other hooks).

Pinging @cbenhagen @matham @dessant since this i mivy related and you may have another idea

**Comment by htgoebel** [comment]
No news here, so I assume the issue is solved.
