### ISSUE TITLE
TLS Callbacks

### ISSUE THREAD

**Issue by mattervr** [pyinstaller/pyinstaller#1829]
Not sure what happened but pyinstaller started throwing errors when compiling and I am having trouble tracking down a fix.  Seems to affect a https connection within the script.  Script runs fine when run via python but compile fails with the below error.  Any ideas?

```
744 INFO: Executing - upx --lzma -q C:\Users\moliver\AppData\Roaming\pyinstaller\bincache01_py27_32bit\tmptjk93y
upx: C:\Users\moliver\AppData\Roaming\pyinstaller\bincache01_py27_32bit\tmptjk93y: CantPackException: TLS callbacks are not supported

Running the executable results in the following:
Traceback (most recent call last):
  File "<string>", line 72, in <module>
  File "site-packages\shotgun_api3\shotgun.py", line 471, in __init__
  File "site-packages\shotgun_api3\shotgun.py", line 499, in server_caps
  File "site-packages\shotgun_api3\shotgun.py", line 526, in info
  File "site-packages\shotgun_api3\shotgun.py", line 2061, in _call_rpc
  File "site-packages\shotgun_api3\shotgun.py", line 2194, in _make_call
  File "site-packages\shotgun_api3\shotgun.py", line 2244, in _http_request
  File "site-packages\shotgun_api3\lib\httplib2\__init__.py", line 1608, in request
  File "site-packages\shotgun_api3\lib\httplib2\__init__.py", line 1350, in _request
  File "site-packages\shotgun_api3\lib\httplib2\__init__.py", line 1272, in _conn_request
  File "site-packages\shotgun_api3\lib\httplib2\__init__.py", line 1036, in connect
  File "site-packages\shotgun_api3\lib\httplib2\__init__.py", line 80, in _ssl_wrap_socket
  File "ssl.py", line 911, in wrap_socket
  File "ssl.py", line 520, in __init__
IOError: [Errno 2] No such file or directory
hMover_v1.9 returned -1
```
I am setting the cacerts location in my program using the below line and the cacerts file is in the same directory as the executable.
os.environ['REQUESTS_CA_BUNDLE'] = os.path.join(application_path, 'cacerts.txt')

**Comment by codewarrior0** [comment]
What is `application_path`? You need to use `os.path.dirname(sys.executable)` to get the folder the exe is in, or `sys._MEIPASS` to get the folder containing files that are bundled with the exe.

Did you try `assert os.path.exists(os.path.join(application_path, 'cacerts.txt'))`?

**Comment by mattervr** [comment]
Yeah I set the application path with the following.  will try the assert command.

if getattr(sys, 'frozen', False):
    application_path = os.path.dirname(sys.executable)
elif __file__:
    application_path = os.path.dirname(__file__)

**Comment by codewarrior0** [comment]
Actually, I don't think `REQUESTS_CA_BUNDLE` will help you, because I don't see `requests` in your traceback at all. The `shotgun_api3` library you are using seems to include its own `cacerts.txt` in its [embedded copy of httplib2](https://github.com/shotgunsoftware/python-api/tree/master/shotgun_api3/lib/httplib2), and I'll bet that file is not being automatically bundled by PyInstaller.

The usual solution is to create a hook file `hook-shotgun_api3.py` to tell PyInstaller to bundle that file, similar to [other hook files](https://github.com/pyinstaller/pyinstaller/tree/develop/PyInstaller/hooks). It should list the certs file under `datas` as [described in the manual](https://pythonhosted.org/PyInstaller/#hook-global-variables).

<sub>...frankly, this business of creating hook files for each and every Python library is starting to get stale, but that's a topic for another thread.</sub>

**Comment by mattervr** [comment]
Figured it out!!  Sooooo the problem was I had installed Universal Extractor which was added to my system path and had an old upx.exe file (v3.5).  I replaced it with the latest 3.9.1 and my exe's are back to compiling again.  Thanks for looking into it codewarrior0.  Hope this helps someone else in the future.

**Comment by mattervr** [comment]
jumped the gun...so that removed the compile about TLS callbacks...but the program is still throwing the same ssl errors when run.

This code compiled just fine before so it is definitely something with my dev environment.

**Comment by htgoebel** [comment]
I suggest you follow the instructions at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly, which says: "Try without UPX packaging".

**Comment by htgoebel** [comment]
The solution is to be found here:https://github.com/shotgunsoftware/python-api/blob/master/shotgun_api3/lib/httplib2/__init__.py#L188-L195

Just implement your version of `ca_certs_locater`and everything is fine.

It would be great, if you'd create a hook for this, which we could include into PyInstaller. Please have a look at PyInstaller/hooks/pre_find_module_path/hook-site.py on how to include a fake module. In your case you should make sure, the faked module is used as fall-back only, So append the `fake-modules` directory to the end of `search_dirs`.

**Comment by mattervr** [comment]
Hartmut you are my hero.  Dropped in a new ca_certs_locater.py file in the httplib2 folder with the following code and my compiles are running beautifully.  Will look into generating the hook

`import sys
import os
def get():
	if getattr(sys, 'frozen', False):
	    application_path = os.path.dirname(sys.executable)
	elif __file__:
	    application_path = os.path.dirname(__file__)

	return os.path.join(application_path, 'cacerts.txt')`
