### ISSUE TITLE
Not bundled/bundled PyQt5 app view differs

### ISSUE THREAD

**Issue by pohmelie** [pyinstaller/pyinstaller#1830]
## When running pure python app:
![screenshot - 18 02 2016 - 10 38 28](https://cloud.githubusercontent.com/assets/2385765/13136654/7bb548ce-d62c-11e5-8aa2-02948bd34953.png)

## When running bundled app:
![screenshot - 18 02 2016 - 10 39 40](https://cloud.githubusercontent.com/assets/2385765/13136662/8f40d886-d62c-11e5-8c69-dc4b716b694d.png)

As you can see this differs a bit (colors, focus, gradients and looks not native). **Probably this is not pyinstaller issue**.

xubuntu 14.04 / python 3.4.3 / pyqt 5.2.1

**Comment by htgoebel** [comment]
Please have a look at related issues: https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+theme+is%3Aclosed

**Comment by pohmelie** [comment]
Ok, so I'll try pyinstaller from repo.

**Comment by pohmelie** [comment]
Yep, that works fine!

**Comment by pohmelie** [comment]
Actually I did not find #1769 cause did not include «theme» word in search :laughing:
My bad.
