### ISSUE TITLE
failed to create process

### ISSUE THREAD

**Issue by gbarnabic** [pyinstaller/pyinstaller#1832]
I get this error "failed to create process." every time I try to run pyinstaller.exe from the command line.  Even when I just execute it with no parameters.  Other exe's in the same directory (i.e. pip.exe or pip3.exe) run fine, so it can't be a path issue.  I tried changing it's properties to "compatibility" mode, trying Win8, Win7, WinXP.  When researching this issue I have seen numerous other posts with the same issue and no real solutions except PATH issues in some cases.  But as I said other .exe's in the same location are working fine, so it's location is surely in scope and it is being found.  I'm on a Win8 computer.  I did install the development version and got the same results.  I realize it may be some kind of environment issue and not something with pyinstaller but at this point I'm dead in the water.

**Comment by htgoebel** [comment]
I'm quite sure, this is related to your environment, so I'm closing this ticket.

PyInstaller itself is a pure Python program. So it if does not even start up, you need to fix your environment. Please refer to <https://pythonhosted.org/PyInstaller/#installing-in-windows>.

**Comment by chonghai** [comment]
Here is a solution:
http://stackoverflow.com/questions/31808180/installing-pyinstaller-via-pip-leads-to-failed-to-create-process

It's work to me.
Wish help.

**Comment by hsumerf** [comment]
I had the same issue so I checked the  file
**C:\Python27\Scripts\pyinstaller-script.py**
and there was an old python path which when I installed python installer
**C:\Python27\python.exe**
But later I renamed python.exe --> python2.exe, so I just changed the path 
**C:\Python27\python.exe --> C:\Python27\python2.exe**
in file
**C:\Python27\Scripts\pyinstaller-script.py**
and it worked perfectly.

**Comment by abdulhakimdesuki** [comment]
I have the same problem but I solve it by using pip3 not pip to install pyinstaller 
first you should uninstall old pyinstaller by issuing .... c:\pip uninstall pyinstaller  then after uninstall do finish .... issue .... c:\pip3.7 install pyinstaller .....
