### ISSUE TITLE
PyCrypto: AttributeError: 'module' object has no attribute 'RSA'

### ISSUE THREAD

**Issue by tingfengainiaini** [pyinstaller/pyinstaller#1834]
I have raised the question in stackoverflow.
http://stackoverflow.com/questions/35477674/pyinstaller-attributeerror-module-object-has-no-attribute-rsa

My python file runs all right with python directly:

`python detectIPConflict.py`
However, when the script packaged by PyInstaller:

`pyinstaller --onefile detectIPConflict.py`
`./dist/detectIPConflict`
Here goes the error:

```
WARNING: No route found for IPv6 destination :: (no default route?)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.1.1-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "scapy/all.py", line 46, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.1.1-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "scapy/crypto/__init__.py", line 17, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller-3.1.1-py2.7.egg/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "scapy/crypto/cert.py", line 19, in <module>
AttributeError: 'module' object has no attribute 'RSA'
detectIPConflict returned -1
```

I also have seek into the scapy/crypto/cert.py, in line 19:
`from Crypto.PublicKey import *`
I can not find why this error happened. I'm get confused.

Anyone can help?

Version info:

Python: 2.7.6
pyinstaller: 3.1.1
scapy: 2.3.2 (installed by pip command)
pycrypto: 2.6.1

Here is the detectIPConflict.py:

```
#!/usr/bin/env python
# -*- coding:utf-8 -*-
from scapy.all import *

def ip_conflict():
    ipscan='10.2.86.190/23'
    ip_dict = dict()
    ip_me = get_if_addr('eth0')
    mac_me = get_if_hwaddr('eth0')
    print "--------IP ME---------"
    print ip_me, "--", mac_me
    print "----------------------"
    ip_dict[ip_me] = mac_me
    try:
        ans,unans=srp(Ether(dst="FF:FF:FF:FF:FF:FF")/ARP(pdst=ipscan),iface="br0", timeout=2,verbose=False)
    except Exception,e:
        print str(e)
    else:
        print ("   MAC            --   IP   ")
        for snd,rcv in ans:
            list_mac=rcv.sprintf("%Ether.src% -- %ARP.psrc%")
            mac = rcv.sprintf("%Ether.src%")
            ip = rcv.sprintf("%ARP.psrc%")
            # print mac,'-->',ip
            if ip not in ip_dict:
                ip_dict[ip] = mac
    for has_ip in ip_dict.keys():
        print has_ip, "------ " + ip_dict[has_ip]
if __name__ == "__main__":
    ip_conflict()
```

**Comment by tingfengainiaini** [comment]
I have fixed this error by modification of the python2.7/dist-packages/scapy/crypto/cert.py code: Modify line 19,20,21:

from Crypto.PublicKey import RSA
from Crypto.Cipher import ARC2
from Crypto.Hash import MD2
This works for me.

However, I don't know why 'import *' can not be recognized by pyinstaller. Grateful fort any explanations.

**Comment by matysek** [comment]
@tingfengainiaini I am probably not the best person but pyinstaller for a long time does not support recognizing `import *`. And even the library `modulegraph` that we now use does not support that.

My guess is because it's harder to detect those dependencies and and it would mean slow down the module dependency resolution noticeably.

Anyway, question is where it should be fixed permanently:
- the scapy module - reporting an issue with pyinstaller packaging or
- fix the pyinstaller hook for scapy?

**Comment by tingfengainiaini** [comment]
@matysek ,Thanks for your answer. 
I found in pyinstaller:3.0, there is a specialized hook for scapy. Probably, this new hook do not get around  with this 'import *' issue.

**Comment by htgoebel** [comment]
The reason is quite easy: [Crypto/PublicKey/__init__.py](https://github.com/dlitz/pycrypto/blob/master/lib/Crypto/PublicKey/__init__.py) does not contain an `import` statement. So PyInstaller can not detect the submodules.

So this is not  scapy-issue, but a PyCrypto one.

A simple solution would be to create hooks for the relevant Crypto modules.

**Comment by htgoebel** [comment]
pycrypto is [officially dead](https://github.com/dlitz/pycrypto/issues/173) and [seriously buggy](http://lists.gnu.org/archive/html/guix-devel/2016-12/msg01007.html). Please move forward to an alternative. We ought not spend time fixing support for dead software.
