### ISSUE TITLE
A way to completely override a default hook

### ISSUE THREAD

**Issue by dessant** [pyinstaller/pyinstaller#1835]
I'm trying to override hook_matplotlib.py and hook_kivy.py (stop it from being executed) and use my own hook instead.

My use case for matplotlib is to not collect `mpl-data`.  I was trying to override `datas` in the custom hook, but it seems the values are being added to the global list, rather than being able to manipulate the list directly.

Having direct access to the globals would be nice (from a hook), but the best way would be to not execute the default hook at all, when needed. Otherwise we would have to write boilerplate just to undo what has been done in the default hook.

The comment below mentions overriding the globals completely, but i couldn't find a way in the docs or forums, sorry if this has been addressed already.
https://github.com/pyinstaller/pyinstaller/pull/1678#issuecomment-158761602

**Comment by leycec** [comment]
Thanks for the detailed feature request, dessant. :construction_worker: 

I'm currently refactoring our hook infrastructure to support [lazy hook loading](https://github.com/pyinstaller/pyinstaller/pull/1651). While my refactoring doesn't relate _directly_ to your feature request, I'm hip-deep in the PyInstaller codebase. This seems like an appropriate time to brainstorm possible solutions for hook overriding before I inevitably suffer a concussion and forget everything... _again._

In order of decreasing preference, we could:

1. Add support for a new hook attribute, function, or callback permitting custom hooks to inform PyInstaller of their desire to override the corresponding official hook. This effectively requires lazy hook loading, which should be good to go... _any minute now._. Given that, we could add support for a new optional:
  * `is_override` hook boolean, defaulting to `False` when undefined. If explicitly set to `True` by a custom hook, the corresponding official hook would be removed from the cache of hooks to be run.
  * `modify_hooks()` hook function, passed the list of all hooks to be run for this module – including both the corresponding official hook (if any) and the current custom hook. This hook function could then be defined by the current custom hook so as to:
    * Reorder the order of hooks in this list. Currently, official hooks are _always_ run before custom hooks.
    * Remove one or more hooks from this list – in this case, the first element of this list (i.e., the corresponding official hook).
    * Modify any attributes or callables defined by one or more hooks in this list – in this case, removing the `datas` attribute from the first element of this list.
1. Add a new CLI option `--exclude-hook={hook_name}`. PyInstaller would accept multiple such options and, for each, remove the corresponding official hook from the cache of hooks to be run. For the following reasons, I'm not terribly fond of this approach:
  * Any custom hook intended to override an official hook should be required to explicitly inform PyInstaller of that fact at runtime via some hook attribute, function, or callback embedded directly in that custom hook. Externalizing this relationship into a CLI option makes it all-too easy to accidentally forget to pass that option.
  * Adding yet more CLI options is feasible, but _not_ necessarily desirable.

## What Should We Do, leycec?

**I have a strong preference for the `modify_hooks()` approach.** It's the maximally general-purpose solution, ensuring that we don't have to continually add new hook attributes or CLI options whenever a user requests low-level support for manipulating yet another hook interaction (e.g., reordering hooks, removing hooks, modifying hooks).

A few examples in a hypothetical hook:

1. Prevent the corresponding official hook from being run:

        def modify_hooks(hooks):
            del hooks[0]   # It's really that simple, folks.

1. Remove the `datas` attribute from the corresponding official hook – but still run that hook:

        def modify_hooks(hooks):
            del hooks[0].code.datas   # I'm not kidding here, people.

1. Force the current custom hook to be run before the corresponding official hook – but still run that hook:

        def modify_hooks(hooks):
            official_hook = hooks[0]
            hooks = [hooks[1], official_hook]

What say you, glorious code compatriots?

**Comment by matysek** [comment]
I suggest that pyinstaller could just overriide default hooks when a hook with the same name would be present in the directory specified with option `--additional-hooks-dir `

**Comment by tallforasmurf** [comment]
What @matysek said also popped into my mind. Find any local hooks first (they are uncommon I believe); then do not load an official hook having the same name. Is there any presumption in current code that user-supplied hooks are loaded last?

**Comment by matysek** [comment]
@tallforasmurf I checked the source code and the implementation works this way:
- first process hooks bundled in pyinstaller
- second use user hooks if they have the same module name

**Comment by leycec** [comment]
In principal, I agree with the "just make local hooks _always_ override default hooks." [KISS](https://en.wikipedia.org/wiki/KISS_principle), amirite?

In practice, I've actually leveraged the fact that PyInstaller currently runs both default and local hooks for the same module in a shipped application. Since I didn't have time to submit my changes upstream (..._I still don't!_), I simply defined a local hook "monkey patching" the default hook of a problematic module with additional functionality.

If we refactor PyInstaller to unconditionally override default hooks with local hooks, that hackery breaks. I'd either need to **(A)** actually submit my changes upstream (..._which I really should do anyway_) or **(B)** copy-and-paste the contents of the default hook into the local hook. The issue with **(B)**, of course, is synchronization; upstream changes to the default hook would be ignored by my local hook. The issue with **(A)** is laziness. (It's a problem.)

Admittedly, this is probably an edge case. As [tallforasmurf](https://github.com/tallforasmurf) suggests, the number of applications actually using the `--additional-hooks-dir` option (excluding those authored by PyInstaller developers) might be negligibly small. But `--additional-hooks-dir` _does_ publicly exist and _is_ well-documented – so it would be kind-of nice to preserve backward compatibility here.

**Comment by htgoebel** [comment]
@leycec To be frank, the "hook patching" mechanisms is over-engineered IMHO. Much too much code for rare cases.

As The Zen of Python says:
> Simple is better than complex.
> Special cases aren't special enough to break the rules.

**Comment by thierryBottaro** [comment]
I'm not a so prolific Python programmer, but I use the "--additional-hooks-dir" and I don't understand how you may use pyInstaller without this option. 
To me, Numpy needed it absolutely (the optimization DLLs were not loaded by the standard hook) and my icons/splashscreen are also loaded through an hook.

The "user hook always overrides other hooks" is dead simple, but may not be as evolutive as the leycec solution. If the default hook is upgraded, the modification could be taken into account if the custom hook just modifies it, not if it completely overrides it.

**Comment by Quuxplusone** [comment]
> In principal, I agree with the "just make local hooks always override default hooks." KISS, amirite?

Yes.

> In practice, I've actually leveraged the fact that PyInstaller currently runs both default and local hooks for the same module in a shipped application. Since I didn't have time to submit my changes upstream, I simply defined a local hook "monkey patching" the default hook for a problematic module with additional functionality specific to that application. It is a thing of beauty. 🗻

> If we refactor PyInstaller to unconditionally override default hooks with local hooks, that sweet hackery breaks. I'd either need to (A) actually submit my changes upstream (...which I really should do anyway) or (B) copy-and-paste the contents of the default hook into the local hook.

Or (C) programmatically get the path to the default hook, and then import and run that hook as part of the local hook. Right?  Surely that's only a couple of lines of code today. I imagine it could be made into a one-liner if pyinstaller exposed some additional API function such as `myhookmodule = get_default_hook('mypackage.submodule')`.

I've run into this problem with pyinstaller and an application that imports `django` but is not itself a Django application: the default `hook-django.py` is inappropriate, but I can't quite figure out how to tell pyinstaller "This program needs you to package up `django`, but please don't run the default `hook-django.py`; I've got my own hook for that."

**Comment by om26er** [comment]
What are my options today, if I want to override twisted hook instead of monkey patching it myself.

**Comment by htgoebel** [comment]
Try this:
- mkdir my-hooks
- create an empty file my-hooks/hook_XXXX.py
- pass `--additional-hooks-dir=my-hooks` when running pyinstaller (or add it n the spec-file).

Please report back it this works.

**Comment by om26er** [comment]
> Try this:
> 
>     mkdir my-hooks
>     create an empty file my-hooks/hook_XXXX.py
>     pass --additional-hooks-dir=my-hooks when running pyinstaller (or add it n the spec-file).
> 
> Please report back it this works.

Thanks, I just tried and it did not help. I actually named the hook `py_rth_twisted.py` and added below code to it
```
from twisted.internet.iocpreactor import reactor

reactor.install()
```
but the environment actually had the default reactor, the one that PyInstaller installs. Though if I monkey patch the default twisted hook, it fixes my issue.

**Comment by htgoebel** [comment]
This issue is about hooks, not about run-time hooks. If your problem is about a run-time hook, please add open a new ticket. If you have problems with the existing twisted hook, please provide a pull-request.

**Comment by pebbywebby** [comment]
I'm also interested in solving this (or maybe learning more about pyinstaller by explaining my issue). In my case, I do not need additional modules, but want to _exclude_ some. I have a script that imports QApplication from PyQt5.Qt, but the hook for PyQt5.Qt then includes everything under the sun in Qt as seen [here](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-PyQt5.Qt.py):
```python
hiddenimports = []
for f in os.listdir(os.path.dirname(get_module_file_attribute('PyQt5'))):
    root, ext = os.path.splitext(os.path.basename(f))
    if root.startswith('Qt') and root != 'Qt':
        print ("Adding this root" + str(root))
        hiddenimports.append('PyQt5.' + root)
```

Though I may be bumping into a Qt limitation that might bite me, I wanted to see if I could trim some of the unneeded libs (e.g. the huge QtWebEngineCore). Even if my specfile lists certain modules to exclude, the hook will still override my request. I see the xref html file produced indicates those modules were excluded, even though they are ultimately included. _Interesting aside: even if I modify the hook file to not include the QtWeb* files, they are still coming in somehow even though they are not listed in the xrefs html_

It makes sense to me that either a local, total replacement for the hook file behavior or my own explicit exclusions should be available to me. Per the discussion above, it allows me to take total responsibility for what's going on even if I may be reproducing boilerplate. If my explicit exclusions aren't working as intended, I can file/search a new issue for that.

**Comment by bjones1** [comment]
You contributions would be welcome. I'd be in favor of having local hooks replace system hooks.

**Comment by ulukyn** [comment]
I found a way to replace system hooks (hook-gi.repository.Gtk.py) by my own version since the hook includes themes/ and icons/ folders who take Gigabytes...

So i have created a virtualenv, pip installed pyinstaller and all i need, after that i have replace the hook in my virtualenv by my own version and start pyinstaller with <ENV>/bin/pyinstaller <MYFILE.py>

**Comment by logan-pugh** [comment]
How can I use a custom hook to override which DLLs are included by an imported library? Similar to  @pebbywebby's comment https://github.com/pyinstaller/pyinstaller/issues/1835#issuecomment-428015480, I want to prevent certain DLLs from being included my the built executable, e.g. `opengl32sw.dll` which needlessly bloat the file size of the executable.

**Comment by logan-pugh** [comment]
Well to answer my own [question](https://github.com/pyinstaller/pyinstaller/issues/1835#issuecomment-590483347), here's an example of using a "pre-find-module-path" hook to override a default hook (`hook-PyQt5` in my case): https://gist.github.com/logan-pugh/c37b359bc65a365480310c157b1d284e

It's not pretty, but at least it is better than editing the PyInstaller source.
