### ISSUE TITLE
Wrong Python3.5 path

### ISSUE THREAD

**Issue by Tamriel** [pyinstaller/pyinstaller#1836]
I installed Python3.5 with HomeBrew on OS X and no other Python installations.

Now I get `File "/usr/local/lib/python3.5/site-packages/PyInstaller/archive/writers.py", line 371, in add
    fh = open(pathnm, 'rb')
FileNotFoundError: [Errno 2] No such file or directory: '/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyInstaller/loader/rthooks/pyi_rth_qt5.py'` ([full exception](https://gist.github.com/Tamriel/eaf343c3ae339d4ce122))

That missing file is at `/usr/local/lib/python3.5/`... but PyInstaller looks at `/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/`...

**Comment by htgoebel** [comment]
Please run `pyinstaller --clean` and try again.
