### ISSUE TITLE
Pyinstaller won't run. "ImportError: DLL load failed"

### ISSUE THREAD

**Issue by jstil003** [pyinstaller/pyinstaller#1840]
I installed pyinstaller 3.1.1 and even tried the 3.2.dev build but neither seem to work. I am on Windows and I have python 3.5 installed. Any time I try to run pyinstaller I receive the following:

```
C:\Windows\system32>pyinstaller
Traceback (most recent call last):
  File "c:\python35\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python35\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Python35\Scripts\pyinstaller.exe\__main__.py", line 5, in <module>
  File "c:\python35\lib\site-packages\PyInstaller\__main__.py", line 21, in <mod
ule>
    import PyInstaller.building.build_main
  File "c:\python35\lib\site-packages\PyInstaller\building\build_main.py", line
32, in <module>
    from ..depend import bindepend
  File "c:\python35\lib\site-packages\PyInstaller\depend\bindepend.py", line 42,
 in <module>
    from ..utils.win32.winmanifest import RT_MANIFEST
  File "c:\python35\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", l
ine 97, in <module>
    from PyInstaller.utils.win32 import winresource
  File "c:\python35\lib\site-packages\PyInstaller\utils\win32\winresource.py", l
ine 20, in <module>
    import pywintypes
  File "c:\python35\lib\site-packages\win32\lib\pywintypes.py", line 124, in <mo
dule>
    __import_pywin32_system_module__("pywintypes", globals())
  File "c:\python35\lib\site-packages\win32\lib\pywintypes.py", line 64, in __im
port_pywin32_system_module__
    import _win32sysloader
ImportError: DLL load failed: The specified module could not be found.
```

Is the problem with the _win32sysloader.pyd? If so, I know I have the file located under the following directory: `C:\Python35\Lib\site-packages\win32`.

**Comment by tallforasmurf** [comment]
Forgive me for saying the obvious, but have you installed pywin32? It is a [requirement](http://pythonhosted.org/PyInstaller/#windows) for windows.

**Comment by jstil003** [comment]
@tallforasmurf So I _need_ both pypiwin32 and pywin32 installed? I installed pywin32 now and it doesn't seem to be throwing this error anymore. However, pip installed the pypiwin32 along with pyinstaller, so I assumed this would work since it says to use pypiwin32 or pywin32. Strange that I had already tried installing pywin32 anyway and it didn't appear to work.

**Comment by tallforasmurf** [comment]
You are correct, pip should have installed pypiwin32.

In the above, the PyInstaller module [winresource.py](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/win32/winresource.py#L21)  imports pywintypes, and that fails.

pywintypes.py appears to be part of the pywin32 package. You say when you installed pywin32, the error stopped happening.

This suggests maybe winresource.py is dependent on pywin32? I don't know if there is supposed to be a compatible pywintypes in the other package.

**Comment by htgoebel** [comment]
Obviously this is not related to PyInstaller, but to your environment: `pywintypes` fails to import `_win32sysloader`.
```
  File "c:\python35\lib\site-packages\win32\lib\pywintypes.py", line 124, in <module>
    __import_pywin32_system_module__("pywintypes", globals())
  File "c:\python35\lib\site-packages\win32\lib\pywintypes.py", line 64, in __import_pywin32_system_module__
    import _win32sysloader
ImportError: DLL load failed: The specified module could not be found.
```
Please check your environment. There is nothing we can do here.

**Comment by yunchih** [comment]
The solution [here](https://github.com/ContinuumIO/anaconda-issues/issues/37#issuecomment-67492289) might work.  I manage to make it work only by manually installing pywin32 from [here](https://sourceforge.net/projects/pywin32/files/pywin32/).

**Comment by ondj** [comment]
@jstil003 Hi. After installing Python 3.5 on clean Windows 7 x86 machine and then run `pip install pyinstaller`, I got the same error. So I analyze `_win32sysloader.pyd` dependencies in Dependency Walker and there is a dependency to MSVCR100.DLL file, which is a part of the Microsoft Visual C++ 2010 Redistributable Package. After installing this package, PyInstaller works correctly.

**Comment by matyvico** [comment]
I can confirm that installing Microsoft Visual C++ 2010 Redistributable Package fixed the error. Thank you!

**Comment by t-animal** [comment]
I can confirm this. On a clean Win7 VM installation I, after installing pyinstaller via pip to a virtualenv, i still n eeded to install pywin32 and Microsoft Visual C++ 2010 Redistributable Package.

**Comment by algorys** [comment]
Same problem happens to me. 

Until I install **Microsoft Visual C++ 2010 Redistributable**, pywin32 produce an error (`DLL not found`) at the end of installation. Once the twice install,  `pyinstaller` works.

Note: test on Win Server 2012, Python 3.5.3 x64, pywin32-220.win-amd64-py3.5.exe

**Comment by chinue** [comment]
copy msvcr100.dll to C:\Windows, then it works

**Comment by ericfrederich** [comment]
I'm having this issue as well with a version of Python I compiled myself with Visual Studio 2012 (required to be able to link against other 3rd party C libraries).

Should MSVC 2010 C++ Redistributable really be a dependency, or just if you're using a version of Python you downloaded from python.org?
