### ISSUE TITLE
"FileNotFoundError: [Errno 2]" when creating exe with langdetect

### ISSUE THREAD

**Issue by eahirst** [pyinstaller/pyinstaller#1842]
I'm putting together an executable that uses the langdetect module, but every time I try to run the exe, it displays:

`FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\me\\AppData\\Local\\Temp\\_MEI53962\\langdetect\\utils\\messages.properties`

Use of modules with pyinstaller seems to be sort of buggy, so here's another module that it doesn't work with.

Running this on a Windows 7, by the way.

**Comment by htgoebel** [comment]
Did you read this manual section https://pythonhosted.org/PyInstaller/#adding-files-to-the-bundle ?

**Comment by eahirst** [comment]
Well, I tried it (without that section) and now it's working, so I guess I did completely miss something. Sorry!
