### ISSUE TITLE
FileNotFoundError: Path or glob "/usr/include/python3.4m/pyconfig.h" not found or matches no files.

### ISSUE THREAD

**Issue by ragnarok22** [pyinstaller/pyinstaller#1846]
When I put in console `pyinstaller main.py` this is the error `FileNotFoundError: Path or glob "/usr/include/python3.4m/pyconfig.h" not found or matches no files.` I search pyconfig.h in py commputer and I found in `/usr/include/python3.4dm/pyconfig.h`. I use python3.4, how i cant fix this?

**Comment by sasuke22** [comment]
Even I try a hello world in python and the problem persist

**Comment by htgoebel** [comment]
> Even I try a hello world in python and the problem persist#

This already is an important information, but please provide more details, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by Legorooj** [comment]
Closing due to no response from author.
