### ISSUE TITLE
python-dateutil 2.5.0 isn't packaged correctly

### ISSUE THREAD

**Issue by tjstum** [pyinstaller/pyinstaller#1848]
Hi,

The [python-dateutil package](https://github.com/dateutil/dateutil) [changed](https://github.com/dateutil/dateutil/commit/aac0a119fbd247316157a0362c1d4eff21431bc3) how they do their imports in a subpackage in version 2.5.0. PyInstaller now seems to be choking on it at runtime.

A script that reproduces the issue:
```
import dateutil.parser

def main():
    print "success!"

if __name__ == "__main__":
    main()
```

With dateutil 2.4.0 installed, this works both packaged and unpackaged. With dateutil 2.5.0 installed, this works unpackaged but breaks when packaged:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\dateutil\tz\__init__.py", line 1, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\dateutil\tz\tz.py", line 17, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\dateutil\tz\__init__.py", line 1, in <module>
ImportError: No module named tz
test returned -1
```

I tried adding `--hidden-import dateutil.tz.tz`, but that did not help.

The [way they import names](https://github.com/dateutil/dateutil/blob/master/dateutil/tz/__init__.py) during tz's `__init__` is a little strange, but it should be something that PyInstaller supports. I am happy to submit a hook change, but it's not clear to me what needs hooking (since it's not just a case of a missing module).

**Comment by htgoebel** [comment]
I found a line in that change which at least looks curious, but I assume it is plain wrong. Please see 
https://github.com/dateutil/dateutil/commit/aac0a119fbd247316157a0362c1d4eff21431bc3#commitcomment-16397845

But I'm sorry, I can not reproduce this in a fresh virtualenv. (using python_dateutil-2.5.0-py2.py3-none-any.whl)

**Comment by pganssle** [comment]
Hey guys, feel free to make an issue or PR over at dateutil and I'll take a look. Not sure why I went with `.__init__` instead of `.`. Seems like that would not be my intuition about how it's done.

I'm not particularly familiar with pyinstaller, though, so any steps to help me reproduce would be helpful.

**Comment by tjstum** [comment]
Hmm... I'm unable to reproduce this on Mac OS X (my original case was on Windows).

@htgoebel, do you by chance have a Windows machine you could try testing this on? I will take a look again tomorrow to make sure I wasn't doing something dumb.

**Comment by htgoebel** [comment]
@tjstum Sorry, no Windows around here.

**Comment by LevN0** [comment]
I can reproduce this on Linux (CentOS 6.7).

**Comment by codewarrior0** [comment]
I can reproduce this locally with Python 2.7 and python-dateutil-2.5.0. 

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "c:\users\rio\documents\src\pyinst1328\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\dateutil\parser.py", line 43, in <module>
  File "c:\users\rio\documents\src\pyinst1328\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\dateutil\tz\__init__.py", line 1, in <module>
  File "c:\users\rio\documents\src\pyinst1328\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\dateutil\tz\tz.py", line 17, in <module>
  File "c:\users\rio\documents\src\pyinst1328\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\dateutil\tz\__init__.py", line 1, in <module>
ImportError: No module named tz
```

I also noticed this is causing one of our tests to fail when run from my personal repo; see https://github.com/pyinstaller/pyinstaller/issues/1847#issuecomment-192044679. The test doesn't seem to fail on the main repo because pip-accel is still installing dateutil-2.4.2 - I'm not sure if there's a way to clear the pip cache on Travis and make it install the newer version.

**Comment by htgoebel** [comment]
I just cleaned the cache and started a new test.

**Comment by htgoebel** [comment]
This is a bug in dateutil. See my fix in https://github.com/dateutil/dateutil/pull/202

**Comment by pganssle** [comment]
I'm not 100% convinced that this is actually a bug in *dateutil*, considering that it works perfectly on standard python interpreters. I'll try and retool, but it seems like this may be an actual problem with pyinstaller not supporting a normally valid import scheme.

**Comment by htgoebel** [comment]
It is a bug in datutil, which is doing recursive import and is doing it wrong. See my lengthy explanation in https://github.com/dateutil/dateutil/pull/202#issuecomment-192352290

**Comment by pganssle** [comment]
My "not 100% convinced" has now been bumped from something like 85% to something like 99.99% :P

**Comment by nchammas** [comment]
I ran into this issue here with botocore and dateutil 2.5.0. Downgrading to dateutil 2.4.2 fixed the PyInstaller packaging for me.
