### ISSUE TITLE
dnspython hook needs to be updated

### ISSUE THREAD

**Issue by MarkInLA** [pyinstaller/pyinstaller#1853]
It appears that  DNS data is being corrupted when running a python file as an executable created by pyinstaller if the code imports and uses the dns.resolver module from the dnspython library.

If I execute the following code in a file from the command line (the data has been replaced with dummy data to illustrate the point and simplified to show the issue)
>python dnsfoo.py
```
import time
import math
import json
import os
import sys
import glob
import dns.resolver
import pickle
import subprocess
ipList = resolver.query(url,'APL') # url is a regular url
for ipAddress in ipList:
    print(repr(ipAddress))
```
Here is a single line of the output (there can be hundreds)
```
<DNS IN APL rdata: 1:1.1.1.1/32>
```
Which is exactly correct.
If I do the following:
>pyinstaller dnsfoo.py 
>dist\dnsfoo\dnsfoo.exe
and run the exe I get the following output:
```    
<DNS IN APL rdata: \# 8 0001200476c1d40c>
```
I am running the latest version of Python 3.5, dnspython and pyinstaller. Originally, I received a warning for dns.rdata having an out-of-date hook file.  I fixed that.  
The dns.resolver module seems to heavily use winreg functions when being used under windows. That is not being found by pyinstaller.  

Here is the build output

63 INFO: PyInstaller: 3.1.1
63 INFO: Python: 3.5.1
63 INFO: Platform: Windows-10-10.0.10586-SP0
63 INFO: wrote C:\dnsfoo\dnsfoo.spec
78 INFO: UPX is not available.
78 INFO: Extending PYTHONPATH with paths
['C:\\dnsfoo',
 'C:\\dnsfoo']
78 INFO: checking Analysis
78 INFO: Building Analysis because out00-Analysis.toc is non existent
78 INFO: Initializing module dependency graph...
94 INFO: Initializing module graph hooks...
94 INFO: Analyzing base_library.zip ...
1923 INFO: running Analysis out00-Analysis.toc
2252 INFO: Analyzing C:\dnsfoo\dnsfoo.py
2408 INFO: Looking for import hooks ...
2408 INFO: Processing hook   hook-xml.py
2564 INFO: Processing hook   hook-encodings.py
2580 INFO: Processing hook   hook-dns.rdata.py
2595 INFO: Processing hook   hook-pydoc.py
2611 INFO: Looking for ctypes DLLs
2611 INFO: Analyzing run-time hooks ...
2627 INFO: Looking for dynamic libraries
2704 INFO: Looking for eggs
2704 INFO: Using Python library c:\python35\python35.dll
2704 INFO: Found binding redirects:
[]
2704 INFO: Warnings written to C:\dnsfoo\build\dnsfoo\warndnsfoo.txt
2720 INFO: checking PYZ
2720 INFO: Building PYZ because out00-PYZ.toc is non existent
2720 INFO: Building PYZ (ZlibArchive) C:\dnsfoo\build\dnsfoo\out00-PYZ.pyz
2939 INFO: checking PKG
2939 INFO: Building PKG because out00-PKG.toc is non existent
2939 INFO: Building PKG (CArchive) out00-PKG.pkg
2954 INFO: Bootloader c:\python35\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
2954 INFO: checking EXE
2954 INFO: Building EXE because out00-EXE.toc is non existent
2954 INFO: Building EXE from out00-EXE.toc
2954 INFO: Appending archive to EXE C:\dnsfoo\build\dnsfoo\dnsfoo.exe
3017 INFO: checking COLLECT
3017 INFO: Building COLLECT because out00-COLLECT.toc is non existent
WARNING: The output directory "C:\dnsfoo\dist\dnsfoo" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
7347 INFO: Removing dir C:\dnsfoo\dist\dnsfoo
7378 INFO: Building COLLECT out00-COLLECT.toc

Here is the warning file:

missing module named resource - imported by posix, C:\dnsfoo\dnsfoo.py
missing module named posix - imported by os, C:\dnsfoo\dnsfoo.py
missing module named _datetime.__doc__ - imported by _datetime, datetime, C:\dnsfoo\dnsfoo.py
missing module named _posixsubprocess - imported by subprocess, C:\dnsfoo\dnsfoo.py
missing module named _heapq._heapreplace_max - imported by _heapq, heapq, C:\dnsfoo\dnsfoo.py
missing module named _heapq._heapify_max - imported by _heapq, heapq, C:\dnsfoo\dnsfoo.py
missing module named _heapq._heappop_max - imported by _heapq, heapq, C:\dnsfoo\dnsfoo.py
missing module named unicodedata.ucd_3_2_0 - imported by unicodedata, stringprep, encodings.idna, C:\dnsfoo\dnsfoo.py
missing module named _operator._compare_digest - imported by _operator, hmac
missing module named _operator.__doc__ - imported by _operator, operator, C:\dnsfoo\dnsfoo.py
missing module named _sre.MAXREPEAT - imported by _sre, sre_constants, C:\dnsfoo\dnsfoo.py
missing module named _sre.MAXGROUPS - imported by _sre, sre_constants, C:\dnsfoo\dnsfoo.py
missing module named _functools.reduce - imported by _functools, functools, C:\dnsfoo\dnsfoo.py
missing module named _functools.cmp_to_key - imported by _functools, functools, C:\dnsfoo\dnsfoo.py
missing module named _functools.partial - imported by _functools, functools, C:\dnsfoo\dnsfoo.py
missing module named _functools._lru_cache_wrapper - imported by _functools, functools, C:\dnsfoo\dnsfoo.py
missing module named 'org.python' - imported by pickle, C:\dnsfoo\dnsfoo.py, xml.sax
missing module named 'org.python'.imp - imported by 'org.python', xml.sax
missing module named 'org.python'.PyStringMap - imported by 'org.python', pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.load - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.Unpickler - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.dump - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.loads - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.PicklingError - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.PickleError - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.Pickler - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.dumps - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named _pickle.UnpicklingError - imported by _pickle, pickle, C:\dnsfoo\dnsfoo.py
missing module named posix._exit - imported by posix, os, C:\dnsfoo\dnsfoo.py
missing module named posix._have_functions - imported by posix, os, C:\dnsfoo\dnsfoo.py
missing module named ce - imported by os, C:\dnsfoo\dnsfoo.py
missing module named ce._exit - imported by ce, os, C:\dnsfoo\dnsfoo.py
missing module named ce._have_functions - imported by ce, os, C:\dnsfoo\dnsfoo.py
missing module named inspect.CO_GENERATOR - imported by inspect, bdb, C:\dnsfoo\dnsfoo.py
missing module named _opcode.stack_effect - imported by _opcode, opcode, C:\dnsfoo\dnsfoo.py
missing module named readline - imported by cmd, code, pdb, C:\dnsfoo\dnsfoo.py
missing module named _imp.release_lock - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp.is_frozen - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp.init_frozen - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp.get_frozen_object - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp._fix_co_filename - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp.acquire_lock - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp.is_builtin - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp.lock_held - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp.is_frozen_package - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
missing module named _imp.create_dynamic - imported by _imp, imp, C:\dnsfoo\dnsfoo.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\dnsfoo\dnsfoo.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\dnsfoo\dnsfoo.py
missing module named zipimport.zipimporter - imported by zipimport, pkgutil, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.Array - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.Structure - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.Union - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._Pointer - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.CFuncPtr - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.__version__ - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.RTLD_LOCAL - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.RTLD_GLOBAL - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.ArgumentError - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.FormatError - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.FUNCFLAG_USE_ERRNO - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.FUNCFLAG_CDECL - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.FUNCFLAG_USE_LASTERROR - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.FUNCFLAG_PYTHONAPI - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.LoadLibrary - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.FUNCFLAG_STDCALL - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.dlopen - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.resize - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.sizeof - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.byref - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.alignment - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.addressof - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.get_errno - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.set_errno - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._SimpleCData - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.pointer - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._pointer_type_cache - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._check_HRESULT - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.get_last_error - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes.set_last_error - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._memmove_addr - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._string_at_addr - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._cast_addr - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._memset_addr - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _ctypes._wstring_at_addr - imported by _ctypes, ctypes, C:\dnsfoo\dnsfoo.py
missing module named _winreg - imported by platform, dns.resolver, C:\dnsfoo\dnsfoo.py
missing module named _winreg.CloseKey - imported by _winreg, platform, C:\dnsfoo\dnsfoo.py
missing module named _winreg.HKEY_LOCAL_MACHINE - imported by _winreg, platform, C:\dnsfoo\dnsfoo.py
missing module named _winreg.QueryValueEx - imported by _winreg, platform, C:\dnsfoo\dnsfoo.py
missing module named _winreg.OpenKeyEx - imported by _winreg, platform, C:\dnsfoo\dnsfoo.py
missing module named _scproxy._get_proxies - imported by _scproxy, urllib.request
missing module named _scproxy._get_proxy_settings - imported by _scproxy, urllib.request
missing module named _scproxy - imported by urllib.request
missing module named 'java.lang'.Exception - imported by 'java.lang', xml.sax._exceptions
missing module named xml.parsers.expat.ParserCreate - imported by xml.parsers.expat, plistlib, C:\dnsfoo\dnsfoo.py
missing module named java - imported by platform, C:\dnsfoo\dnsfoo.py
missing module named java.System - imported by java, platform, C:\dnsfoo\dnsfoo.py
missing module named 'java.lang' - imported by platform, C:\dnsfoo\dnsfoo.py, xml.sax._exceptions
missing module named vms_lib - imported by platform, C:\dnsfoo\dnsfoo.py
missing module named _winapi.STARTF_USESHOWWINDOW - imported by _winapi, subprocess, C:\dnsfoo\dnsfoo.py
missing module named _winapi.SW_HIDE - imported by _winapi, subprocess, C:\dnsfoo\dnsfoo.py
missing module named _winapi.STD_INPUT_HANDLE - imported by _winapi, subprocess, C:\dnsfoo\dnsfoo.py
missing module named _winapi.STARTF_USESTDHANDLES - imported by _winapi, subprocess, C:\dnsfoo\dnsfoo.py
missing module named _winapi.CREATE_NEW_PROCESS_GROUP - imported by _winapi, subprocess, C:\dnsfoo\dnsfoo.py
missing module named _winapi.STD_OUTPUT_HANDLE - imported by _winapi, subprocess, C:\dnsfoo\dnsfoo.py
missing module named _winapi.CREATE_NEW_CONSOLE - imported by _winapi, subprocess, C:\dnsfoo\dnsfoo.py
missing module named _winapi.STD_ERROR_HANDLE - imported by _winapi, subprocess, C:\dnsfoo\dnsfoo.py
missing module named termios - imported by tty, C:\dnsfoo\dnsfoo.py, getpass
missing module named _ssl.OPENSSL_VERSION - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.OPENSSL_VERSION_NUMBER - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.OPENSSL_VERSION_INFO - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl._SSLContext - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.MemoryBIO - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.SSLWantWriteError - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.SSLEOFError - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.SSLError - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.SSLZeroReturnError - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.SSLWantReadError - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.SSLSyscallError - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.CERT_OPTIONAL - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.CERT_REQUIRED - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.CERT_NONE - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.nid2obj - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.txt2obj - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.RAND_bytes - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.RAND_pseudo_bytes - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.RAND_add - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.RAND_status - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.RAND_egd - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.HAS_SNI - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.HAS_ECDH - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.HAS_ALPN - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.HAS_NPN - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl._OPENSSL_API_VERSION - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.enum_certificates - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named _ssl.enum_crls - imported by _ssl, ssl, C:\dnsfoo\dnsfoo.py
missing module named time.strptime - imported by time, ssl, C:\dnsfoo\dnsfoo.py
missing module named winreg.CloseKey - imported by winreg, platform, C:\dnsfoo\dnsfoo.py
missing module named winreg.HKEY_LOCAL_MACHINE - imported by winreg, platform, C:\dnsfoo\dnsfoo.py
missing module named winreg.QueryValueEx - imported by winreg, platform, C:\dnsfoo\dnsfoo.py
missing module named winreg.OpenKeyEx - imported by winreg, platform, C:\dnsfoo\dnsfoo.py
missing module named os.urandom - imported by os, random, C:\dnsfoo\dnsfoo.py
missing module named _hashlib.pbkdf2_hmac - imported by _hashlib, hashlib, C:\dnsfoo\dnsfoo.py
missing module named hashlib.sha512 - imported by hashlib, random, C:\dnsfoo\dnsfoo.py
missing module named _bz2.BZ2Compressor - imported by _bz2, bz2, C:\dnsfoo\dnsfoo.py
missing module named _bz2.BZ2Decompressor - imported by _bz2, bz2, C:\dnsfoo\dnsfoo.py
missing module named _lzma._decode_filter_properties - imported by _lzma, lzma, C:\dnsfoo\dnsfoo.py
missing module named _lzma._encode_filter_properties - imported by _lzma, lzma, C:\dnsfoo\dnsfoo.py
missing module named grp - imported by tarfile, shutil, C:\dnsfoo\dnsfoo.py
missing module named grp.getgrnam - imported by grp, shutil, C:\dnsfoo\dnsfoo.py
missing module named binascii.a2b_qp - imported by binascii, quopri, C:\dnsfoo\dnsfoo.py
missing module named binascii.b2a_qp - imported by binascii, quopri, C:\dnsfoo\dnsfoo.py
missing module named binascii.a2b_base64 - imported by binascii, email.base64mime, C:\dnsfoo\dnsfoo.py
missing module named binascii.b2a_base64 - imported by binascii, email.base64mime, C:\dnsfoo\dnsfoo.py
missing module named _dummy_threading - imported by dummy_threading, C:\dnsfoo\dnsfoo.py
missing module named _dummy_threading.__all__ - imported by _dummy_threading, dummy_threading, C:\dnsfoo\dnsfoo.py
missing module named dummy_threading.RLock - imported by dummy_threading, bz2, C:\dnsfoo\dnsfoo.py
missing module named nt._exit - imported by nt, os, C:\dnsfoo\dnsfoo.py
missing module named nt._getvolumepathname - imported by nt, ntpath, C:\dnsfoo\dnsfoo.py
missing module named nt._getfullpathname - imported by nt, ntpath, C:\dnsfoo\dnsfoo.py
missing module named nt._getfinalpathname - imported by nt, ntpath, C:\dnsfoo\dnsfoo.py
missing module named nt._isdir - imported by nt, ntpath, C:\dnsfoo\dnsfoo.py
missing module named nt._have_functions - imported by nt, os, C:\dnsfoo\dnsfoo.py
missing module named math.log - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named math.ceil - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named math.exp - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named math.e - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named math.pi - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named math.sqrt - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named math.sin - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named math.acos - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named math.cos - imported by math, random, C:\dnsfoo\dnsfoo.py
missing module named socket.SOCK_STREAM - imported by socket, ssl, C:\dnsfoo\dnsfoo.py
missing module named socket.AF_INET - imported by socket, ssl, C:\dnsfoo\dnsfoo.py
missing module named socket.SOL_SOCKET - imported by socket, ssl, C:\dnsfoo\dnsfoo.py
missing module named socket.SO_TYPE - imported by socket, ssl, C:\dnsfoo\dnsfoo.py
missing module named _struct._clearcache - imported by _struct, struct, C:\dnsfoo\dnsfoo.py
missing module named _struct.__doc__ - imported by _struct, struct, C:\dnsfoo\dnsfoo.py
missing module named struct.calcsize - imported by struct, ctypes, C:\dnsfoo\dnsfoo.py
missing module named struct.unpack - imported by struct, pickle, C:\dnsfoo\dnsfoo.py
missing module named struct.pack - imported by struct, pickle, C:\dnsfoo\dnsfoo.py
missing module named errno.ENOENT - imported by errno, gettext, C:\dnsfoo\dnsfoo.py
missing module named _thread.allocate_lock - imported by _thread, _strptime, C:\dnsfoo\dnsfoo.py
missing module named _thread.get_ident - imported by _thread, reprlib, C:\dnsfoo\dnsfoo.py
missing module named _thread.RLock - imported by _thread, functools, C:\dnsfoo\dnsfoo.py
missing module named time.monotonic - imported by time, subprocess, threading, socketserver, C:\dnsfoo\dnsfoo.py
missing module named _thread.stack_size - imported by _thread, threading, C:\dnsfoo\dnsfoo.py
missing module named _thread._local - imported by _thread, threading, C:\dnsfoo\dnsfoo.py
missing module named threading.current_thread - imported by threading, _threading_local, C:\dnsfoo\dnsfoo.py
missing module named threading.RLock - imported by threading, _threading_local, bz2, C:\dnsfoo\dnsfoo.py
missing module named pwd.getpwnam - imported by pwd, shutil, C:\dnsfoo\dnsfoo.py
missing module named pwd - imported by posixpath, tarfile, shutil, http.server, webbrowser, C:\dnsfoo\dnsfoo.py, netrc, getpass
missing module named ntpath.commonprefix - imported by ntpath, unittest.util, C:\dnsfoo\dnsfoo.py
missing module named _collections.deque - imported by _collections, threading, collections, C:\dnsfoo\dnsfoo.py
missing module named _collections.defaultdict - imported by _collections, collections, C:\dnsfoo\dnsfoo.py
missing module named _collections.OrderedDict - imported by _collections, collections, C:\dnsfoo\dnsfoo.py
missing module named _collections._count_elements - imported by _collections, collections, C:\dnsfoo\dnsfoo.py
missing module named _warnings.filters - imported by _warnings, warnings, C:\dnsfoo\dnsfoo.py
missing module named _warnings._onceregistry - imported by _warnings, warnings, C:\dnsfoo\dnsfoo.py
missing module named _warnings._filters_mutated - imported by _warnings, warnings, C:\dnsfoo\dnsfoo.py
missing module named _warnings.warn_explicit - imported by _warnings, warnings, C:\dnsfoo\dnsfoo.py
missing module named _warnings._defaultaction - imported by _warnings, warnings, C:\dnsfoo\dnsfoo.py
missing module named _warnings.warn - imported by _warnings, warnings, C:\dnsfoo\dnsfoo.py
missing module named _weakref.ProxyType - imported by _weakref, weakref, C:\dnsfoo\dnsfoo.py
missing module named _weakref.ref - imported by _weakref, _weakrefset, weakref, C:\dnsfoo\dnsfoo.py
missing module named _weakref.proxy - imported by _weakref, weakref, collections, C:\dnsfoo\dnsfoo.py
missing module named _weakref.ReferenceType - imported by _weakref, weakref, C:\dnsfoo\dnsfoo.py
missing module named _weakref.getweakrefs - imported by _weakref, weakref, C:\dnsfoo\dnsfoo.py
missing module named _weakref.getweakrefcount - imported by _weakref, weakref, C:\dnsfoo\dnsfoo.py
missing module named _weakref.CallableProxyType - imported by _weakref, weakref, C:\dnsfoo\dnsfoo.py
missing module named builtins.abs - imported by builtins, operator, C:\dnsfoo\dnsfoo.py
missing module named builtins.open - imported by builtins, tokenize, tarfile, bz2, C:\dnsfoo\dnsfoo.py
missing module named builtins.str - imported by builtins, locale, C:\dnsfoo\dnsfoo.py
missing module named org - imported by copy, C:\dnsfoo\dnsfoo.py
missing module named org.PyStringMap - imported by org, copy, C:\dnsfoo\dnsfoo.py
missing module named copy.deepcopy - imported by copy, weakref, email.generator, C:\dnsfoo\dnsfoo.py
missing module named _io.TextIOWrapper - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.FileIO - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.BufferedReader - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.UnsupportedOperation - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.BufferedRWPair - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.BufferedWriter - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.StringIO - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.open - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.BufferedRandom - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.BlockingIOError - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.IncrementalNewlineDecoder - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.DEFAULT_BUFFER_SIZE - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named _io.BytesIO - imported by _io, io, C:\dnsfoo\dnsfoo.py
missing module named itertools.chain - imported by itertools, tokenize, collections, C:\dnsfoo\dnsfoo.py
missing module named itertools.repeat - imported by itertools, tokenize, collections, C:\dnsfoo\dnsfoo.py
missing module named itertools.count - imported by itertools, threading, C:\dnsfoo\dnsfoo.py
missing module named itertools.islice - imported by itertools, threading, reprlib, pickle, C:\dnsfoo\dnsfoo.py
missing module named itertools.starmap - imported by itertools, collections, C:\dnsfoo\dnsfoo.py
missing module named sys.modules - imported by sys, dummy_threading, C:\dnsfoo\dnsfoo.py
missing module named sys.getwindowsversion - imported by sys, platform, C:\dnsfoo\dnsfoo.py
missing module named sys.maxsize - imported by sys, pickle, C:\dnsfoo\dnsfoo.py
missing module named md5 - imported by dns.entropy
missing module named sha - imported by dns.entropy
missing module named _json.make_encoder - imported by _json, json.encoder
missing module named _json.encode_basestring - imported by _json, json.encoder
missing module named _json.encode_basestring_ascii - imported by _json, json.encoder
missing module named _json.scanstring - imported by _json, json.decoder
missing module named _json.make_scanner - imported by _json, json.scanner

**Comment by codewarrior0** [comment]
Confirmed for Python 3.4 on Windows 7 also. Haven't found out the cause yet.

**Comment by MarkInLA** [comment]
BTW, I changed the hook-dns-rdata.py on my system to

hiddenimports = [
    "dns.rdtypes",
    "dns.rdtypes.ANY",
    "dns.rdtypes.IN"
	]
and it seemed to kill the warning on build.

**Comment by codewarrior0** [comment]
I have a feeling the cause is that one (or all) of the modules under `dns.rdtypes` needs to be added to hiddenimports, since the `\# 8 0001200476c1d40c` format output is the one used when an appropriate Rdata subclass can't be found. I think the answer is as simple as adding `collect_submodules('dns.rdtypes')`.

**Comment by MarkInLA** [comment]
Can you spell out what that would look like, as other people are going to have the same issue and having a nice recipe to solve this problem would be nice treat to discover from a search engine.

**Comment by MarkInLA** [comment]
Thanks codewarrior0 for the info, it seems to work.  I changed my hook-dns.rdata.py file to: 

from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('dns.rdtypes')

(I comment out everything else in the file)
And it seems to work!  

You may want to update your sources on this (after you test it and agree that it works)

**Comment by codewarrior0** [comment]
Thanks. Will give it a try shortly.

**Comment by MarkInLA** [comment]
I will close out this issue as it has been resolved.  Thanks again for the very quick response on this.
