### ISSUE TITLE
error with japanese non-unicode module [+WORKAROUND]

### ISSUE THREAD

**Issue by berrytsakala** [pyinstaller/pyinstaller#1854]
1) i'm trying to freeze kaa-editor:  https://github.com/kaaedit/kaa

2) i simply ran pyinstaller and the Kaa's entry point but got this error.  error:

41 INFO: PyInstaller: 3.1.1
41 INFO: Python: 3.5.1
41 INFO: Platform: Linux-3.13.0-37-generic-x86_64-with-LinuxMint-17.2-rebecca
[...]
  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1834, in _find_module_path
    file_handle = StringIO(loader.get_source(module_name))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x81 in position 39078: invalid start byte

3) the problematic module is [pyjf3](https://pypi.python.org/pypi/pyjf3) which is encoded in an old japanese shitty encoding shiftJIS.
I converted it to utf8, and edited the -_-coding-_\- accordingly to utf-8

4) now I get this error:

  File "/usr/local/lib/python3.5/dist-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1788, in _find_module_path
    pathname = loader.get_filename(module_name)
  File "/usr/local/lib/python3.5/dist-packages/pyjf3-0.3-py3.5.egg/pyjf3.py", line 13
SyntaxError: bytes can only contain ASCII literal characters.

5) i'm lost.
attached: my converted egg file.  The only module converted is pyjf3.py

[pyjf3-0.3-py3.5.egg.zip](https://github.com/pyinstaller/pyinstaller/files/156806/pyjf3-0.3-py3.5.egg.zip)

**Comment by berrytsakala** [comment]
2nd bug solved: 
(i.e. paragraph 4) in my original post)

i hard-coded this particular module's path in the filesystem, when this module is encountered, since it only wants the module's name, not contents:

                    try:
                        pathname = loader.get_filename(module_name)
                    except SyntaxError:
                        print(' >>>>>>>>>>>>>> error! <<<<<<<<<<<<<')
                        pathname = '/usr/local/lib/python3.5/dist-packages/pyjf3-0.3-py3.5.egg/pyjf3.py'

this bug might be easily fixed, i assume.

thanks !
i now have kaa frozen as elf. 
it's a wonderful console-based text editor !!!

**Comment by htgoebel** [comment]
This seams to be a problem with the zipimporter. Simply install pyjf3 *without* `--egg` option and it works.
