### ISSUE TITLE
module import failed on windows

### ISSUE THREAD

**Issue by majj** [pyinstaller/pyinstaller#1859]
code example:

`
import arrow

x = "2016/3/4 9:01:02"

timestamp =arrow.get(x, "YYYY/M/D H:mm:ss").timestamp

print(timestamp)
`

Z:\maboio\grab>pyinstaller --onefile --icon=grab.ico ts1.py
155 INFO: PyInstaller: 3.1.1
155 INFO: Python: 2.7.11
171 INFO: Platform: Windows-XP-5.1.2600-SP2
171 INFO: wrote Z:\maboio\grab\ts1.spec
187 INFO: UPX is not available.
219 INFO: Extending PYTHONPATH with paths
['Z:\\maboio\\grab', 'Z:\\maboio\\grab']
219 INFO: checking Analysis
219 INFO: Building Analysis because out00-Analysis.toc is non existent
219 INFO: Initializing module dependency graph...
234 INFO: Initializing module graph hooks...
328 INFO: running Analysis out00-Analysis.toc
344 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
344 INFO: Found C:\WINDOWS\WinSxS\Policies\x86_policy.9.0.Microsoft.VC90.CRT_1fc
8b3b9a1e18e3b_x-ww_b7353f75\9.0.21022.8.policy
359 INFO: Found C:\WINDOWS\WinSxS\Policies\x86_policy.9.0.Microsoft.VC90.CRT_1fc
8b3b9a1e18e3b_x-ww_b7353f75\9.0.30729.1.policy
375 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.307
29.1_x-ww ...
375 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_Microsoft.VC90.CRT_1fc8
b3b9a1e18e3b_9.0.30729.1_x-ww_6f74963e.manifest
375 INFO: Searching for file msvcr90.dll
375 INFO: Found file C:\WINDOWS\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9
.0.30729.1_x-ww_6f74963e\msvcr90.dll
375 INFO: Searching for file msvcp90.dll
375 INFO: Found file C:\WINDOWS\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9
.0.30729.1_x-ww_6f74963e\msvcp90.dll
375 INFO: Searching for file msvcm90.dll
375 INFO: Found file C:\WINDOWS\WinSxS\x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9
.0.30729.1_x-ww_6f74963e\msvcm90.dll
375 INFO: Found C:\WINDOWS\WinSxS\Policies\x86_policy.9.0.Microsoft.VC90.CRT_1fc
8b3b9a1e18e3b_x-ww_b7353f75\9.0.21022.8.policy
375 INFO: Found C:\WINDOWS\WinSxS\Policies\x86_policy.9.0.Microsoft.VC90.CRT_1fc
8b3b9a1e18e3b_x-ww_b7353f75\9.0.30729.1.policy
391 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0,
30729, 1)
548 INFO: Analyzing Z:\maboio\grab\ts1.py
2803 INFO: Processing pre-safe import module hook   six.moves
3822 INFO: Processing pre-find module path hook   distutils
4355 INFO: Looking for import hooks ...
4371 INFO: Processing hook   hook-distutils.py
4371 INFO: Processing hook   hook-encodings.py
5075 INFO: Looking for ctypes DLLs
5075 INFO: Analyzing run-time hooks ...
5092 INFO: Looking for dynamic libraries
5217 INFO: Looking for eggs
5233 INFO: Using Python library C:\WINDOWS\system32\python27.dll
5233 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVers
ion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 1), publicKeyToken=u'1fc8b3b9a1e1
8e3b')]
5247 INFO: Warnings written to Z:\maboio\grab\build\ts1\warnts1.txt
5342 INFO: checking PYZ
5342 INFO: Building PYZ because out00-PYZ.toc is non existent
5342 INFO: Building PYZ (ZlibArchive) Z:\maboio\grab\build\ts1\out00-PYZ.pyz
5796 INFO: checking PKG
5796 INFO: Building PKG because out00-PKG.toc is non existent
5796 INFO: Building PKG (CArchive) out00-PKG.pkg
5921 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 307
29, 1)
7411 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Windo
ws-32bit\run.exe
7425 INFO: checking EXE
7425 INFO: Building EXE because out00-EXE.toc is non existent
7425 INFO: Building EXE from out00-EXE.toc
7457 INFO: SRCPATH [('grab.ico', None)]
7457 INFO: Updating icons from ['grab.ico'] to c:\windows\temp\tmpx7vmje
7473 INFO: Writing RT_GROUP_ICON 0 resource with 90 bytes
7473 INFO: Writing RT_ICON 1 resource with 1128 bytes
7473 INFO: Writing RT_ICON 2 resource with 5909 bytes
7473 INFO: Writing RT_ICON 3 resource with 9640 bytes
7473 INFO: Writing RT_ICON 4 resource with 4264 bytes
7473 INFO: Writing RT_ICON 5 resource with 67624 bytes
7473 INFO: Writing RT_ICON 6 resource with 16936 bytes
7519 INFO: Appending archive to EXE Z:\maboio\grab\dist\ts1.exe

`
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\arrow\__init__.py", line 3, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "**site-packages\arrow\arrow.py**", line 11, in <module>  
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\dateutil\tz\__init__.py", line 1, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "**site-packages\dateutil\tz\tz.py**", line 17, in <module>
  File "c:\python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py",
 line 389, in load_module
    exec(bytecode, module.__dict__)
  File "**site-packages\dateutil\tz\__init__.py**", line 1, in <module>
ImportError: No module named tz
ts1 returned -1
`

site-packages\arrow\arrow.py", line 11:
`
from dateutil import tz as dateutil_tz
`

but  **C:\Python27\Lib\site-packages\dateutil\tz.py ** is there

**Comment by htgoebel** [comment]
This is a bug in dateutil, see  #1848. Please downgrade to dateutil < 2.5 or wait for a updated version of dateutil.
