### ISSUE TITLE
Trouble with Pytz

### ISSUE THREAD

**Issue by TTT3** [pyinstaller/pyinstaller#1864]
python 2.7.11

The script uses pytz, and as an .exe works fine from my computer; however when opened by someone else they encountered this error:

```
Traceback <most recent call last>:
File "<string>", line 258, in module
File "<string>", line 20, in init
File "site-packages\pytz_init_.py, line 180, in timezone pytz.exceptions.UnknownTimeZoneError:'US/Pacific'    
```

The code that's causing the error is:

```
self.pacific = pytz.timezone('US/Pacific')
```

The line directly before this is `self.UTC = pytz.timezone('UTC')` and does not produce an error.

I know Pyinstaller is equipped to handle Pytz, and when it compiled it created a Pytz folder which contains the zoneinfo folder with what should be all the necessary files.  The person it was sent to checked and said the zoneinfo folder and all of its contents did make it onto his machine.  Any ideas?

**Comment by htgoebel** [comment]
If I understand you correctly, your program and all the required data have been frozen as expected?!

I tried reproducing this, and it worked fine. Try this simple script `test_tz.py`:
```
import pytz
print(pytz.__file__)
print(pytz.timezone('US/Pacific'))
```

Zoneinfo should then be in `dist/test_tz/pytz/zoneinfo`

**Comment by TTT3** [comment]
Sorry let me try and rephrase.  When I compiled my script it created the zoneinfo folder and works just fine on my computer.  However, when I send it to someone and they try and open it on a different computer (they confirm the zoneinfo folder is still present) it gives the error I listed.

**Comment by htgoebel** [comment]
I assume that the `zoneinfo` folder not only has been created but also been populated with all required files. Right? So I assume that for some reason you missed distributing the folder contents.

Otherwise I need more exact information: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by TTT3** [comment]
Yep, I had them check to make sure all of the files are there.  I sent them the entire `dist` folder just to make sure something wasn't accidentally being left out.  I'll go through the reporting link and update later, thanks.

**Comment by htgoebel** [comment]
Nothing new since 1 1/2 year. I assume this is solved.
