### ISSUE TITLE
pyinstaller error with matplotlib

### ISSUE THREAD

**Issue by TimingSpace** [pyinstaller/pyinstaller#1865]
I use pyinstaller in generate  pythion program with matplotlib a exe file
The exe is generated well but when use the exe, there is a error said no module named 'tz'
what does it mean?

I have test the pythinstaller with program with numby and pyqt4 without matplotlib, it works well! )

**Comment by leycec** [comment]
This is a [known issue](https://github.com/dateutil/dateutil/pull/202#issuecomment-192352290). `python-dateutil` 2.5.0 is [currently broken with respect to PyInstaller](https://github.com/pyinstaller/pyinstaller/issues/1848), unfortunately.

Until `python-dateutil` issues a new stable release correcting this, consider temporarily downgrading to `python-dateutil` [2.4.2](https://github.com/dateutil/dateutil/releases/tag/2.4.2). Apologies for the mild inconvenience – and thanks for taking the time to report this, nonetheless.

**Comment by TimingSpace** [comment]
Thank you very much, this problem is solved in that way and my program run normal in the begin.
But when I make it show a figure(draw by matplotlib) by a button , another error occurs
"This probably means that Tcl wasn't installed properly."

This computer is without a python, so cannot a program run without python?
Or should install a Tcl?
Or what happens and what should I do?

**Comment by LevN0** [comment]
Make a folder build, and check if it contains Tcl and Tk directories. (The packaged binary should run without Python, but the computer you are running PyInstaller on to make the binary must have Tcl/TK installed if that is the backend MPL is set to use.)

**Comment by htgoebel** [comment]
Is this still an issue? If so, have you tried the current development version and is it solved there? Ifnot: does any other ticket relating to tkinter describe your problem, so we can close this one?

**Comment by htgoebel** [comment]
No reaction for several month, assume this is solves.
