### ISSUE TITLE
Executable produces "agent returned -1"

### ISSUE THREAD

**Issue by jstil003** [pyinstaller/pyinstaller#1870]
I am using a Windows computer with Python 3.4 and pyinstaller 3.0 (also happening with Python 3.5 and pyinstaller dev). So I had this previously working, but I wanted to get rid of the command prompt from showing up when the application is running. So I changed "--nowindowed" to "--windowed" and now every time the executable will runs I receive a message box with: 
`Fatal Error! 
agent returned -1`

What would cause this error when I only change one flag? Also, all imports have remained the same as the functioning executables, according to the pyi-archive_viewer.

Edit: I have tried making the executable with the "onedir" flag and that executable seems to run perfectly normal. When I add the "onefile" flag back, the executable gives me the error immediately.

**Comment by matysek** [comment]
Please provide more info. See
* http://www.pyinstaller.org/if-things-go-wrong.html
* http://www.pyinstaller.org/how-to-report-bugs.html

**Comment by jstil003** [comment]
This is the environment I'm currently trying to make it work in, which produces the same error I previously encountered: 

- Windows Server 2012
- Python 3.5
- Pyinstaller 3.2 .dev0+69ca81d
- Error occurs: Running executable
- Error: `Fatal Error! agent returned -1` (agent is my python file)
- Flags: --onefile, --windowed, --name, --distpath, --workpath, --log-level, --icon

I was creating executables previously with all of the above flags, except the `--windowed` one. However, when I added the '--windowed' flag I was encountering this error as soon as the executable tries to run my code. 

I have been able to reproduce this using the same flags and using a test python file. It will error out when trying to use a module that I imported. In particular, I tested with the subprocesss module.

 I do not have an `ImportError` and I do not see any difference between the `.pyz` files when using the archive viewer or anything when I use Process Monitor. I have used the debug flag as well and I know the process errors out immediately after the executable attempts to run the python file.

**Comment by htgoebel** [comment]
Please provide more from the traceback. A single line makes it hard to presage what's going on.

**Comment by jstil003** [comment]
Sorry, I hope this will help more.
[trace.txt](https://github.com/pyinstaller/pyinstaller/files/177879/trace.txt)

**Comment by htgoebel** [comment]
I can not spot any error in this file. Maybe you uploaded the wrong one?

**Comment by jstil003** [comment]
Sorry yet again, I included one I made with --onedir. This should be of more use: 
[trace.txt](https://github.com/pyinstaller/pyinstaller/files/178036/trace.txt)

I assume this is the problem: `INFO: Manifest Definition Identity is (null).`

**Comment by htgoebel** [comment]
Still I can not find the error you reported:
> Error: Fatal Error! agent returned -1 (agent is my python file)

**Comment by jstil003** [comment]
I receive that error when I try to run the program. I assumed you meant use sxstrace when you asked for traceback. This is what I received with --debug:

Note: basedir is the location where I'm trying to send all the files and is a normal path

`basedir>MyExe.exe
PyInstaller Bootloader 3.x
LOADER: executable is basedir\MyExe.exe
LOADER: homepath is basedir
LOADER: _MEIPASS2 is NULL
LOADER: archivename is basedir\MyExe.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is basedir\MyExe.exe
LOADER: homepath is basedir
LOADER: _MEIPASS2 is C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602
LOADER: archivename is basedir\MyExe.exe
LOADER: SetDllDirectory(C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602\MyExe.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602\base_library.zip;C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602
LOADER: sys.prefix is C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename MyExe.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602\base_library.zip;C:\Users\ADMINI~1\AppData\Local\Temp\2\_MEI34602
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running agent.py
agent returned -1
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for basedir\MyExe.exe`

**Comment by htgoebel** [comment]
Again, there is no "Fatal Error! agent returned -1" error message, only "agent returned -1" - which is a difference. AFAIK PyInstaller does not issue such a message.

But given that this is only e cut-and-paste-problem: It means that your script is catching any error and terminating with `sys,exit(-1)` or `raise SystemExit(-1)`, (If your script would not catch the error, there would be a traceback.) You need to track down where and why it does this. And so we most probably are back to https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

**Comment by jstil003** [comment]
I guess I should clarify the "Fatal Error!" is the title of the message box when I create the executable using --debug and the body of the box is the "agent returned -1". 

I think I may have found what is causing the problem, but I'm not sure how to fix it. I am using subprocess in my executables and I think this may result in output to STDERR, which causes my executable to fail. In my code, I assume this was never a problem because previously it would output this to the console window, but now that I'm trying to use --nowindowed it throws an error?

**Comment by tallforasmurf** [comment]
The docs for subprocess say of [check_output](https://docs.python.org/3.4/library/subprocess.html#subprocess.check_output) that "stdout is not permitted as an argument, as it is used internally to collect the output from the subprocess." By directing stderr to STDOUT you are probably feeding it stuff it doesn't recognize, maybe even a loop generating error messages?

**Comment by jstil003** [comment]
@tallforasmurf I think it means you can't direct stdout elsewhere. Below it also states "To also capture standard error in the result, use stderr=subprocess.STDOUT".

**Comment by tallforasmurf** [comment]
You are correct. Sorry for the noise.

**Comment by codewarrior0** [comment]
In --windowed mode, your app may not have a valid stdin, stdout, and stderr. You need to redirect all of stdin, stdout, and stderr when calling a subprocess via the subprocess module.

See #1339 and https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess

**Comment by htgoebel** [comment]
@jstil003 I'm afraid, I'll bore you, but I assume you did not follow <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#information-we-need>, ans I *strongly* suggest you'll no *now*. You did only provide vague information, you did not provide a minimal example which would have allowed us to spot the problematic points early. Instead we have to tear each bit of information out of you.

I'm closing this now. You may reopen it *after you did your homework*.

(If anybody is curious: Yes, I'm angry.)
