### ISSUE TITLE
Cannot open path/../project_name or path/../project_name.pkg

### ISSUE THREAD

**Issue by FabrizioA** [pyinstaller/pyinstaller#1872]
Hi, 
I'm using PyInstaller (3.2.dev0-e78c279) installed from the git's sources with the command "python setup.py install".
I'm compiling a Django 1.8.11 app with command: "pyinstaller --name=project_name --debug --onefile  manage.py" from inside of my django project folder.

Compile go ok, but when I try to execute the app from ./dist/project_name/project_name I get:
"fabrizio@ubuntu:~/Desktop/path/ ./dist/manage PyInstaller Bootloader 3.x
LOADER: executable is /home/fabrizio/Desktop/path/dist/manage
LOADER: homepath is /home/fabrizio/Desktop/path/dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /home/fabrizio/Desktop/path/dist/manage
LOADER: **pyi_arch_check_cookie failed**
LOADER: archivename is /home/fabrizio/Desktop/path/dist/manage.pkg
LOADER: Cannot open archive: /home/fabrizio/Desktop/path/dist/manage.pkg
Cannot open self /home/fabrizio/Desktop/path/dist/manage or archive /home/fabrizio/Desktop/path/dist/manage.pkg

Are anyone had this issue?
I'm on Ubuntu 14.04

**Comment by htgoebel** [comment]
Please provide more details, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs. Otherwise we can not help you.

**Comment by FabrizioA** [comment]
hi @htgoebel , just I've added debug info.

**Comment by htgoebel** [comment]
IC. You need to compiler the bootloader. We changed it but did not yet include new pre-compiled files.

**Comment by FabrizioA** [comment]
Thanks @htgoebel , I'm using pyinstaller for the first time... how can I compile the bootloader?

**Comment by htgoebel** [comment]
Read the manual :-)
