### ISSUE TITLE
BOTO3 1.2.6 Borken.

### ISSUE THREAD

**Issue by junxianshen** [pyinstaller/pyinstaller#1873]
the latest pyinstaller both stable and development, doesnt work with boto3 1.2.6.

it says, fatal error, return -1

would anyone pls suggest the working version of boto3?
# Problem

import boto3 
in the source file, results runtime error

Fatal Error!
pyiboot01_bootstrap returned -1
# Version

win 10

python --version
Python 3.4.3

pyinstaller --version
3.2.dev0+b3674f2

boto3
1.2.6

cheers!

**Comment by htgoebel** [comment]
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
