### ISSUE TITLE
doc update - bootloader compiled with pip install

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1875]
Recently #1377 was implemented.

It should be documented that for experimental and other not supported platforms, command
`pip install pyinstaller` or `python setup.py install` will try to compile the bootloader if it is not already precompiled for supported OS.

@tallforasmurf could you please look at this? Thanks.

**Comment by tallforasmurf** [comment]
soon.

**Comment by tallforasmurf** [comment]
close via d2d8c1d
