### ISSUE TITLE
OSX, when bundling app, all local files are copied into dist dir -> infinite space used.

### ISSUE THREAD

**Issue by nekopep** [pyinstaller/pyinstaller#1879]
Hi,

I got an application that correctly bundles under windows.

I just switched to osx and rerun the procedure to generate an application but I fall into a really boring issue I didn't had before :/

Basicaly the resulting ./dist/ directory contains all the needed files + all the ./ files!
Meaning all sources,build/(old)dist dir are copied into the dist dir resulting in infinite space used on the disk!

Here is my code structure:
```
/Monitor/Monitor.py
/Monitor/__init__.py
/Monitor/libs/*.py
/Monitor/Monitor.spec
/Monitor/dist
/Monitor/build
```
I run this command:
```
#/bin/sh
rm -rf dist/Monitor
pyinstaller -D --strip  --log-level DEBUG -i ../../ressources/logo.icns Monitor.py

Pyinstaller version: 3.1.1 (also tried with 3.2-devel)

29 INFO: PyInstaller: 3.1.1
29 INFO: Python: 2.7.11
34 INFO: Platform: Darwin-15.3.0-x86_64-i386-64bit
35 INFO: wrote /Users/xxxx/Documents/win_sync/utils/src/Monitor/Monitor.spec
35 DEBUG: Testing for UPX ...
41 INFO: UPX is available.
41 INFO: Removing temporary files and cleaning cache in /Users/xxxx/Library/Application Support/pyinstaller
59 DEBUG: script: /Users/xxxx/Documents/win_sync/utils/src/Monitor/Monitor.py
60 INFO: Extending PYTHONPATH with paths
['/Users/xxxx/Documents/win_sync/utils/src',
 '/Users/xxxx/Documents/win_sync/utils/src/Monitor/']
60 INFO: checking Analysis
60 INFO: Building Analysis because out00-Analysis.toc is non existent
60 INFO: Initializing module dependency graph...
62 INFO: Initializing module graph hooks...
```

Everything run smoothly until the end.
Then If I go into the dist build with all expected files + a  copy of /Monitor/* (included /Monitor/build) and you see where it goes...

Any idea why I got this behaviour under OSX?
Should I change something on my side?

Thanks for any support!
Nekopep

**Comment by matysek** [comment]
* Is it with the python that is provided directly with OSX or how did you install it?
* Does it happen even with the simple helloworld app?

**Comment by nekopep** [comment]
This is with python installed via mac-ports.

This is the python installed as default on my system:
Python 2.7.11 (default, Mar  1 2016, 18:40:10) 
[GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
Type "help", "copyright", "credits" or "license" for more information.

It does not happen with a simple app :/

I've just done a test with test.py:
print "OK"

and test.py is not copied into dist dir.

**Comment by nekopep** [comment]
Please note, I also get another issue when trying to generate .app file even on simplest .py file.
#1880 
Perhaps it is related... or not!

**Comment by nekopep** [comment]
@matysek : I can run a debug session on pycharm to help debugging this.
Can you point me out where I should put some breakpoints?

I've seen an interesting thing:
The local file (that should not be copied) are copied AFTER all mandatory (normal) file are put (.so, script exe file) so there must be some path taken by the code
 that make it thing after having copied every files from hook it start copying local dir.

Hope it will help you to give me some hints on where to place breakpoints!

**Comment by nekopep** [comment]
I've setup a pycharm debug session and I'm on IRC tonight (freenode #pyinstaller) if you are willing to help me navigate the pyinstaller code base.

**Comment by nekopep** [comment]
I've done some progress.
I've run the code to a point where the dictionnary additional_files_cache contains 'PyQt4' that is a set listing all the file of my base directory (that will be later copied)!
Looks like the PyQt4 under osx is doing strange things...

Any comments appreciated :)

**Comment by codewarrior0** [comment]
The entries are added to the additional files dict in `build_main.py:437` in a line that looks like `additional_files_cache.add(imported_name, imphook_object.binaries, imphook_object.datas)`. From there you can find out which hookfile is adding all of your files to the dict. Maybe a conditional breakpoint if `imphook_object.datas` is longer than 100 or so?

**Comment by nekopep** [comment]
So this is the PyQt4 hook that is importing all my files :/
When the hook is executed? at line build_main:433? 
I can't manage to trigger the breakpoint in hook-PyQt4.py: line 32...
Will add a breakpoint into qt4_menu_nib_dir()

**Comment by nekopep** [comment]
Here a stackcall of PyQt4 hook:
update_dependencies, imphook.py:304
_process_datas, imphook.py:280
format_binaries_and_datas, utils.py:392

format_binaries_and_datas, utils.py is called with (binaries_or_datas=[('','')] , workingdir=None)
then at format_binaries_and_datas, utils.py:447, the for loop is called with:
src_dir: '.'
src_subdir_basenames: [all my base dire directories!]
src_file_basenames: [all my sources files that should not be copied!!]

Hope it can helps.

**Comment by nekopep** [comment]
line 423 of utils.py:
src_root_path_or_glob = os.path.normpath(src_root_path_or_glob) ...

and for src_root_path_or_glob, trg_root_dir in binaries_or_datas:
where binaries_or_datas = [('','')]
so src_root_path = ''
then src_root_path_or_glob = os.path.normpath(src_root_path_or_glob) 
makes src_root_path_or_glob = '.' so it start scanning the base directory :/

Bug spotted!

What should I do now?

**Comment by nekopep** [comment]
So the bugs arise because self._module.data of PyQt4 hook = [('','')].
I've added a dirty patch line 417 of utils.py:
    if binaries_or_datas == [('','')]:
        return toc_datas
To workaround the issue.
But defiitively we must understand why PyQt4 hook is setting data to [('','')]

**Comment by codewarrior0** [comment]
It looks like the last line of `qt4_menu_nib_dir` needs to raise an exception if it can't find the nib dir, instead of just returning `''`. I'm not really sure, since I don't know why this nib dir is needed... does the built exe work for you even though this dir isn't being found?

**Comment by nekopep** [comment]
Well I've got a strange, but don't know if it is related to the issue:
Traceback (most recent call last):
  File "<string>", line 1, in <module>
NameError: name 'c' is not defined
pyiboot01_bootstrap returned -1

...
The only thing I'm sure is that, exe works on windows and source python file works on mac.
I'm in directory mode.

**Comment by codewarrior0** [comment]
Are you running PyInstaller from source? Try rebuilding the bootloader: `(cd bootloader; waf all)`

**Comment by nekopep** [comment]
Yes running from source.
I tried waf all but got compilation error :)

Anyway I think the issue is line 241 of utils.py
line menu_dir = ''
Should be line_menu_dir = None
Because if it does not find the dirs at the end it compares to None and not to '' ...

Checking the compile error...

**Comment by nekopep** [comment]
Looks like clang is a bit rigid:
[10/13] Compiling src/pyi_utils.c
../../src/pyi_launch.c:368:54: error: passing 'unsigned char *' to parameter of type 'const char *' converts between pointers to integer types with different sign [-Werror,-Wpointer-sign]
            code = PI_PyMarshal_ReadObjectFromString(data, ntohl(ptoc->ulen));
                                                                                      ^~~~
1 error generated.

Waf: Leaving directory `/Users/ldufrechou/Documents/win_sync/sda14_utils/pyinstaller-develop/bootloader/build/debug'
Build failed
 -> task in 'run_d' failed (exit status 1): 
	{task 4403223184: c pyi_launch.c -> pyi_launch.c.1.o}
['/usr/bin/clang', '-arch', 'x86_64', '-O2', '-Wdeclaration-after-statement', '-Wimplicit-function-declaration', '-Werror', '-mmacosx-version-min=10.7', '-I/pyinstaller-develop/bootloader/build/debug/src', '-I/pyinstaller-develop/bootloader/src', '-D_POSIX_C_SOURCE=200112L', '-D_XOPEN_SOURCE=600', '-D_REENTRANT', '-D_BSD_SOURCE', '-D_DARWIN_C_SOURCE', '-DHAVE_UNSETENV=1', '-DLAUNCH_DEBUG', '-DNDEBUG', '../../src/pyi_launch.c', '-c', '-o', '/pyinstaller-develop/bootloader/build/debug/src/pyi_launch.c.1.o']

**Comment by nekopep** [comment]
Hey good news!
It's running! After bootloader compilation.
By the way I needed to change pyi_launch.c:368 by:
code = PI_PyMarshal_ReadObjectFromString((const char*)data, ntohl(ptoc->ulen));

**Comment by nekopep** [comment]
Setting line_menu_dir = None was a bad idea.
Because then the format_binaries_and_datas, utils.py:447 is call with  (binaries_or_datas=[(None,'')] , workingdir=None)
And the application crash because of the line:
src_root_path_or_glob = os.path.normpath(src_root_path_or_glob)
Because it tries to normalize 'None'...

I kept the patch:
    if binaries_or_datas == [('','')]:
        return toc_datas
that perhaps is ugly, but works :)

**Comment by nekopep** [comment]
@htgoebel : I've seen that a workaround of #1615 was to correct pyqt hook, I think we should add a protection into format_binaries_and_datas. If a hook send an empty list we should avoid at all cost to include all file of root dir, because it could expose source code in the bundled dir. In my case I was lucky enougth that my root dir was 1GB+ so I saw something was wrong! But the same error could arise easily without the user noticing it ...
The little patch I add works but not sure it covers all the use case.

**Comment by nekopep** [comment]
@htgoebel : Ha sorry did not saw #1885 !

**Comment by htgoebel** [comment]
@nekopep I take this as "ticket can be closed" :-)
