### ISSUE TITLE
issues with copy_metadata

### ISSUE THREAD

**Issue by benoit-pierre** [pyinstaller/pyinstaller#1888]
While using `copy_metadata` to package an application that requires `pkg_resources` I have encountered the following issues:

* the `Distribution.egg_info` field is not always set (but that does not necessarily mean no egg_info file exists)

* the egg_info file basename does not always encode the project name, e.g. with `pyhook` and `pywin32` on Windows, the files are: `c:\python27\lib\site-packages\pyhook-1.5.1-py2.7-win32.egg\EGG-INFO` and `c:\python27\lib\site-packages\pywin32-219-py2.7-win32.egg\EGG-INFO`, so using `datas.extend(copy_metadata(package))` will only effectively include one of them

Here is what I've been using instead of `copy_medata` in my hooks:
```python
def get_metadata(package_name):
    dist = pkg_resources.get_distribution(package_name)
    egg_info = '%s.egg-info' % dist.egg_name()
    metadata = dist.egg_info
    if metadata is None:
        metadata = '%s/%s' % (dist.location, egg_info)
        if not os.path.exists(metadata):
            return None
    log.info('%s metadata: %s / %s', package_name, metadata, egg_info)
    return (metadata, egg_info)
```

**Comment by bjones1** [comment]
@benoit-pierre, thanks for filing the issue. A couple of questions:

* I'm not surprised that `pkg_resources.get_distribution(package_name).egg_info` isn't always correct, since it isn't documented. For my testing, can you provide an example of a distribution in which `egg_info` isn't defined?

* I don't think I understand what's wrong in your second point. For pywin32, `copy_metadata` seems to work for me; it reports:

  ```
Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyInstaller.utils.hooks import copy_metadata
>>> copy_metadata('pywin32')
[('c:\\users\\bjones\\downloads\\winpython-32bit-3.4.4.1qt5\\python-3.4.4\\lib\\site-packages\\pywin32-220.dist-info', 'pywin32-220.dist-info')]
```

  ...which is correct for my system. Does this not work on yours? If not, does updating to the latest version (220) help?

* I'm running Python 3.4, so I can't easily test `pyhook`, which seems to be Python 2 only. What output do you get for `copy_metadata('pyhook')`?

**Comment by benoit-pierre** [comment]
* I'm not sure when `egg_info` is not correct, I think it might depend on how a package is installed (with a distribution package manager, using pip, from source, with a dedicated installer...). On my system (Arch Linux), I have quite a few packages without `egg_info` defined:

```python
> python2 <<\EOF
import site
from pkg_resources import find_distributions

print [d.project_name for s in site.getsitepackages() for d in find_distributions(s) if not d.egg_info]
EOF
['adns-python', 'reportlab', 'pycrypto', 'BeautifulSoup', 'Editra', 'ipaddress', 'CDDB', 'subprocess32', 'meliae', 'pytz', 'getmail', 'pygpgme', 'gmpy2', 'PySDL2', 'ufw', 'pexpect', 'pyserial', 'team', 'dnspython', 'Pyrex', 'kaa-metadata', 'cssselect', 'louis', 'virtualenv', 'python-libtorrent', 'wrapt', 'marisa', 'python-musicbrainz2', 'mutagen', 'epydoc', 'zenmap', 'greenlet', 'wxPython-common', 'pygobject', 'Magic-file-extensions', 'numpy', 'scipy', 'arandr', 'PyBluez', 'docutils', 'dogtail', 'UNKNOWN', 'pwquality', 'html5lib', 'bzr', 'bottle', 'hachoir-metadata', 'ptyprocess', 'mpmath', 'notmuch', 'configobj', 'pychecker', 'xpybutil', 'enum34', 'hachoir-core', 'lxml', 'pyxdg', 'python-sane', 'hachoir-parser', 'picard', 'include-server', 'PyPDF2', 'python-musicbrainz', 'namebench', 'hidapi', 'kaa-base', 'mercurial', 'PyYAML', 'apsw', 'pygame']
```

But using my code:

```python
> python2 <<\EOF
import os
import site

import pkg_resources


def get_metadata(package_name):
    dist = pkg_resources.get_distribution(package_name)
    egg_info = '%s.egg-info' % dist.egg_name()
    metadata = dist.egg_info
    if metadata is None:
        metadata = '%s/%s' % (dist.location, egg_info)
        if not os.path.exists(metadata):
            return None
    return (metadata, egg_info)

packages = set(d.project_name for s in site.getsitepackages()
               for d in pkg_resources.find_distributions(s))
print [name for name in packages if not get_metadata(name)]
EOF
['zenmap', 'apsw']
```
* Again, I think this depend on a number of factor, but the egg_info file basename is not always unique.

On my Windows 10 VM install of Python 2.7:

```python
> ./windows/helper.py run python.exe <<\EOF
import os
import site
from collections import defaultdict

from pkg_resources import find_distributions

dups = defaultdict(list)
for s in site.getsitepackages():
  for d in find_distributions(s):
    if not d.egg_info:
        continue
    dups[os.path.basename(d.egg_info)].append((d.project_name, d.egg_info))
print [dl for dl in dups.values() if len(dl) > 1]
EOF
[[('pyhook', 'c:\\python27\\lib\\site-packages\\pyhook-1.5.1-py2.7-win32.egg\\EGG-INFO'), ('pywin32', 'c:\\python27\\lib\\site-packages\\pywin32-219-py2.7-win32.egg\\EGG-INFO')]]
```

But always using `Distribution.egg_name()` guarantees a unique filename, since it encodes both the project name and the version.

With my code, I can successfully package my application on Linux / Windows / OSX, with Python2 and a number of dependencies.

Note that both those issues are actually mentioned in the [current implementation of `copy_metadata`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/hooks/__init__.py#L1415).

**Comment by bjones1** [comment]
@benoit-pierre, thanks -- your test code on Arch Linux showing `egg_info` failures is very helpful. Let me clean up your code when I have a minute. Would you mind testing it for me when it's ready?

On the second point, why does `basename(dist.egg_info)` need to be unique? Or how would having a unique name change the code? I seem to be missing something here.

**Comment by benoit-pierre** [comment]
Let's say I need metadata for both `pyhook` and `pywin32`, with my Windows install and the current version of `copy_metadata`, this is what gets added to `datas` in my hook:

```
('c:\\python27\\lib\\site-packages\\pyhook-1.5.1-py2.7-win32.egg\\EGG-INFO', 'EGG-INFO'),
('c:\\python27\\lib\\site-packages\\pywin32-219-py2.7-win32.egg\\EGG-INFO', 'EGG-INFO'),
```

So PyInstaller will package `c:\\python27\\lib\\site-packages\\pyhook-1.5.1-py2.7-win32.egg\\EGG-INFO` as `EGG-INFO`, and then overwrite it with `c:\\python27\\lib\\site-packages\\pywin32-219-py2.7-win32.egg\\EGG-INFO`: so in the resulting executable, only the metadata for `pywin32` are available.

**Comment by bjones1** [comment]
Strange. The code in `copy_metadata` is:

``` Python
    # We want to copy from the ``metadata_dir`` to PyInstaller, leaving off its
    # prefix in ``sys.path``. The ``location`` attribute provides this prefix,
    # per https://pythonhosted.org/setuptools/pkg_resources.html#distribution-attributes.
    # For example, if ``package_name`` is ``regex``, then ``location = c:\python27\lib\site-packages``
    # and ``metadata_dir = c:\python27\lib\site-packages\regex-2015.11.09.dist-info``.
    # We should therefore return ``[ ('c:\python27\lib\site-packages\regex-2015.11.09.dist-info',
    # 'regex-2015.11.09.dist-info') ]``.
    return [ (metadata_dir, metadata_dir[len(dist.location) + len(os.sep):]) ]
```

Give your output above, I would expect that `metadata_dir` (which is `dist.egg_info`) would contain `'c:\\python27\\lib\\site-packages\\pyhook-1.5.1-py2.7-win32.egg\\EGG-INFO'` and `dist.location` would be `'c:\\python27\\lib\\site-packages`, so I would expect `copy_metadata` to return `(('c:\\python27\\lib\\site-packages\\pyhook-1.5.1-py2.7-win32.egg\\EGG-INFO', 'pyhook-1.5.1-py2.7-win32.egg\\EGG-INFO'),)`. Which of these assumptions is incorrect in your installation?

To help debug this, I've updated `copy_metadata` based on your suggestions; I've attached the [`__init__.zip`](https://github.com/pyinstaller/pyinstaller/files/179864/__init__.zip) file in which it resides. Would you run this and provide the output on your system?

**Comment by benoit-pierre** [comment]
`location` is set to the directory containing `EGG-INFO`, hence the problem. That's why I think using `dist.egg_name()` to get a unique filename is a better idea.

**Comment by bjones1** [comment]
OK, thanks. I've updated my code, since yours doesn't work on my system (it seems to only support eggs, but not other formats). Would you try it?

[`__init__.zip`](https://github.com/pyinstaller/pyinstaller/files/179906/__init__.zip)

**Comment by benoit-pierre** [comment]
> OK, thanks. I've updated my code, since yours doesn't work on my system (it seems to only support eggs, but not other formats)

Can you elaborate on that?

The fact that `egg_info` is not always defined, and the basename being `EGG_INFO` are 2 separate problems.

In my case, for `pyHook`, `egg_info` is set to `c:\python27\lib\site-packages\pyhook-1.5.1-py2.7-win32.egg\EGG-INFO` and `dist.location` to `c:\python27\lib\site-packages\pyhook-1.5.1-py2.7-win32.egg`, so your code does not work.

**Comment by bjones1** [comment]
```
>>> get_metadata('sphinx')
('c:\\users\\bjones\\downloads\\winpython-32bit-3.4.4.1qt5\\python-3.4.4\\lib\\site-packages\\Sphinx-1.3.5.dist-info', 'Sphinx-1.3.5-py3.4.egg-info')
```

The file should be kept in `Sphinx-1.3.5.dist-info` instead.

**Comment by bjones1** [comment]
Hmmm. How can we tell these two cases apart? `if dist.egg_name() in dist.location:` then use `egg_name()`?

**Comment by benoit-pierre** [comment]
> The file should be kept in Sphinx-1.3.5.dist-info instead.

```shell
> mkdir tmp
> cp -a ~/.local/lib/python2.7/site-packages/macholib-1.7.dist-info tmp/macholib-1.7.egg-info
> python2 -c 'from pkg_resources import find_distributions; print list(find_distributions("tmp"))'
[macholib 1.7 (/home/bpierre/progs/src/plover/tmp)]
```

Are you sure the extension is a hard requirement?

**Comment by bjones1** [comment]
The question is more for you: can you demonstrate, in all cases, that renaming a distribution will not break pkg_resources' ability to find it? Since I'm not certain of the answer, I'd like to avoid doing so.

**Comment by benoit-pierre** [comment]
Since we're getting the original file name from `egg_info`, by the way of `pkg_resources`, I think it's pretty safe to assume that the version of `pkg_resources` that will be packaged in does in fact support it, no?

**Comment by bjones1** [comment]
That's a good point. Let me do some testing here to make sure this works for me.

**Comment by bjones1** [comment]
Here's my updated version -- how's this? [`__init__.zip`](https://github.com/pyinstaller/pyinstaller/files/180040/__init__.zip)

**Comment by benoit-pierre** [comment]
This version works fine. :+1:

**Comment by bjones1** [comment]
OK, I've pushed an update. Thanks for your help!

**Comment by htgoebel** [comment]
@benoit-pierre Coming back to this old issue: We urgently need a test-case for this, as the solution turned out to cause other problems. Please provide a list of directories and file-names for both of these packages as they are on your system and as they are to be in the frozen application. How did you install them?  Thanks.

**Comment by benoit-pierre** [comment]
I'm sorry, but I don't use pyinstaller anymore. Knowing now more about packages metadata, I can see that the current implementation can cause issues when a package was installed as an egg (egg-info metadata), and not from a wheel (dist-info metadata). With dist-info, the requirements and supported extras are listed in PKG-INFO, but with an egg, that information is in a dedicated `requires.txt` file.

**Comment by benoit-pierre** [comment]
I think this is better:
```diff
 PyInstaller/utils/hooks/__init__.py | 6 +++++-
 1 file changed, 5 insertions(+), 1 deletion(-)

diff --git i/PyInstaller/utils/hooks/__init__.py w/PyInstaller/utils/hooks/__init__.py
index 0f3230f2..df000eab 100755
--- i/PyInstaller/utils/hooks/__init__.py
+++ w/PyInstaller/utils/hooks/__init__.py
@@ -854,7 +854,11 @@ def copy_metadata(package_name):
     # Determine a destination directory based on the standardized egg name for
     # this distribution. This avoids some problems discussed in
     # https://github.com/pyinstaller/pyinstaller/issues/1888.
-    dest_dir = '{}.egg-info'.format(dist.egg_name())
+    if isinstance(dist, pkg_resources.DistInfoDistribution):
+        metadata_format = 'dist-info'
+    else:
+        metadata_format = 'egg-info'
+    dest_dir = '{}.{}'.format(dist.egg_name(), metadata_format)
     # Per https://github.com/pyinstaller/pyinstaller/issues/1888, ``egg_info``
     # isn't always defined. Try a workaround based on a suggestion by
     # @benoit-pierre in that issue.
```

Test:
```shell
> python -m venv venv
> ./venv/bin/pip freeze --all
pip==9.0.1
setuptools==28.8.0
> ./venv/bin/easy_install -q six
> ./venv/bin/pip install -q python-xlib
> ./venv/bin/python -c 'import sys; from PyInstaller.utils.hooks import copy_metadata; print(list
[
[('/home/bpierre/progs/src/pyinstaller/venv/lib/python3.6/site-packages/six-1.11.0-py3.6.egg/EGG-INFO',
 'six-1.11.0-py3.6.egg-info')],
[('/home/bpierre/progs/src/pyinstaller/venv/lib/python3.6/site-packages/python_xlib-0.20.dist-info',
 'python_xlib-0.20-py3.6.dist-info')]
]
```

**Comment by htgoebel** [comment]
Reading this issue form the top, the first comment describes two problems:

1. `dist.egg_info`might be None, but the egg-info exists.

   Inspecting the [code of pkg_resources 0.6.8](https://github.com/pypa/setuptools/blob/0.6.8/pkg_resources.py), released 1 Nov 2009,
   I could not find any relevant case where this might happen:
   - NullProvider is unusabel abyway, EmptyProvider returns nothing for all requests,
   - FileMetadata only knows "PKG-INFO"
   - PathMetadata is expected to be passed a non-None egg_info value.
   - EggProvider might have egg_info == None, if is is not egg at all. egg_info is set regardless if
      EGG-INFO actually exists.
   - EggMetadata is based on ZipProvider, which is based on EggProvider.

   Also the original poster did not show an example where this happens (apologies if I missed them, please point me to the example.).
   So I'm going to remove this part of the change in a later commit.

2. All Eggs' egg-info directory is called EGG-INFO, thus they are overwriting each other. This is the part which's solution is wrong and now brings the problems.

   pkg_resources.DistInfoDistribution was added in 0.6.28, released 22 Jul 2012, thus I assume it would okay to use it. Anyway, I'm not sure if we should hard-code these "metadata_format". This could make the code less future-proof. What about handling exactly the case which caused this error:
   ```
   dest_dir = metadata_dir[len(dist.location) + len(os.sep):] # taken from the old code
   if os.path.basename(dest_dir) == "EGG-INFO:
     # this e.g. is an zipped or unzipped egg
     dest_dir = '{}.egg-info'.format(dist.egg_name())
   ```

   Or maybe we could even use `dest_dir = os.path.basename(metadata_dir)`.
