### ISSUE TITLE
ImportError for wxPython on some systems.

### ISSUE THREAD

**Issue by 10se1ucgo** [pyinstaller/pyinstaller#1894]
Version info:
- Python 3.5.1 (v3.5.1:37a07cee5969, Dec 6 2015, 01:54:25) [MSC v.1900 64 bit (AMD64)] on win32
- pyinstaller 3.2.dev0+gc78733e.mod
- Windows 10 64bit

A couple of users of my program report that they receive an error when running an exe built with pyinstaller + Python 3. I sent a debug build to one of them and asked them to run it in a console window. The result:

```
C:\Users\...\Music\Pyjam-debug>pyjam.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\...\Music\Pyjam-debug\pyjam.exe
LOADER: homepath is C:\Users\...\Music\Pyjam-debug
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\...\Music\Pyjam-debug\pyjam.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\...\AppData\Local\Temp\_MEI37162
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\...\Music\Pyjam-debug\pyjam.exe
LOADER: homepath is C:\Users\...\Music\Pyjam-debug
LOADER: _MEIPASS2 is C:\Users\...\AppData\Local\Temp\_MEI37162
LOADER: archivename is C:\Users\...\Music\Pyjam-debug\pyjam.exe
LOADER: SetDllDirectory(C:\Users\...\AppData\Local\Temp\_MEI37162)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\...\AppData\Local\Temp\_MEI37162\pyjam.exe.manifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\...\AppData\Local\Temp\_MEI37162\python35.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: Pre-init sys.path is C:\Users\...\AppData\Local\Temp\_MEI37162\base_library.zip;C:\Users\...\AppData\Local\Temp\_MEI37162
LOADER: sys.prefix is C:\Users\...\AppData\Local\Temp\_MEI37162
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename pyjam.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\...\AppData\Local\Temp\_MEI37162\base_library.zip;C:\Users\...\AppData\Local\Temp\_MEI37162
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running jam.py
Traceback (most recent call last):
File "jam.py", line 25, in <module>
File "C:\Python35\lib\site-packages\pyinstaller-3.2.dev0+gc78733e.mod-py3.5.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
File "site-packages\wx\__init__.py", line 17, in <module>
File "C:\Python35\lib\site-packages\pyinstaller-3.2.dev0+gc78733e.mod-py3.5.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
File "site-packages\wx\core.py", line 6, in <module>
File "C:\Python35\lib\site-packages\pyinstaller-3.2.dev0+gc78733e.mod-py3.5.egg\PyInstaller\loader\pyimod03_importers.py", line 573, in load_module
ImportError: DLL load failed: The specified module could not be found.
Failed to execute script jam
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for C:\Users\...\Music\Pyjam-debug\pyjam.exe
```

I then asked him to run DependencyWalker, and he said he got these errors:

```
LoadLibraryExW("\python3.dll", 0x0000000000000000, LOAD_WITH_ALTERED_SEARCH_PATH) returned NULL. Error: The specified module could not be found (126).
LoadLibraryExW("\DLLs\python3.dll", 0x0000000000000000, LOAD_WITH_ALTERED_SEARCH_PATH) returned NULL. Error: The specified module could not be found (126).
LoadLibraryExW("C:\Users\...\AppData\Local\Temp\_MEI47762\wx._core.cp35-win_amd64.pyd", 0x0000000000000000, LOAD_WITH_ALTERED_SEARCH_PATH) returned NULL. Error: The specified module could not be found (126).
```

I then sent him a version built with Python 2.7 and it seems to have worked just fine. I cannot seem to reproduce this issue myself and only a small portion of people have this issue.

I've also looked into the archive with pyi-archive_viewer and it seems to be there...

I apologize for the lack of info, please do ask if you need anything more.

**Comment by htgoebel** [comment]
Thanks for the report. We had similar reports earlier, but the developer was not able to interact with the customer to be able to debug this.

A few questions, so:

- Are you using UPX?
- Did you try in onedir-mode?

What makes me curious on the output of DepedencyWalker is:

1. The bootloader seams to try to load python3.dll from `\' and from `\DLLs\', which IMHO is somewhat wrong (but I'm not a windows guy)
2. The output says it does not find python3.dll, nevertheless continues executing. So maybe it finds wx._core...pyd somewhere else, too (which would make me even more curious, though), and fails loading something else. Could you make your customer run this using stracent? (On linux I would use `strace -e trace=file`)

**Comment by 10se1ucgo** [comment]
- UPX is disabled. UPX causes problems for me, giving me these errors:
```
Window caption: pyjam.exe - Bad image

C:\Users\10se1ucgo\AppData\Local\Temp\_MEI192562\VCRUNTIME140.dll is either not designed to run on Windows or it contains an error. Try installing the program again using the original installation media or contact your system administrator or the software vendor for support.
Error status 0xc000007b.
```
and

```
Window caption: Fatal Error!

Error loading Python DLL:
C:\Users\10se1ucgo\AppData\Local\Temp\_MEI192562\python35.dll (error code 193)
```

- I haven't tried one-dir mode yet, I will try now.

**Comment by 10se1ucgo** [comment]
Okay, I sent him a one-dir mode build and he gets the same error

```
Traceback (most recent call last):
  File "jam.py", line 25, in <module>
  File "C:\Python35\lib\site-packages\pyinstaller-3.2.dev0+gb306e8d.mod-py3.5.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\wx\__init__.py", line 17, in <module>
  File "C:\Python35\lib\site-packages\pyinstaller-3.2.dev0+gb306e8d.mod-py3.5.egg\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\wx\core.py", line 6, in <module>
  File "C:\Python35\lib\site-packages\pyinstaller-3.2.dev0+gb306e8d.mod-py3.5.egg\PyInstaller\loader\pyimod03_importers.py", line 573, in load_module
ImportError: DLL load failed: The specified module could not be found.
```

**Comment by htgoebel** [comment]
[pyimod03_importers.py, line 573](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/pyimod03_importers.py#L573) is only reached if the file exists in the filesystem, which is tested just before.

**Comment by 10se1ucgo** [comment]
So what does that mean for me?

**Comment by 10se1ucgo** [comment]
Does anyone know if any recent changes would have an affect on this?

**Comment by linglung** [comment]
same here. got problem like this

**Comment by linglung** [comment]
Same here. I've got problem like this with upx include. After remove it, everything goes fine.

**Comment by 10se1ucgo** [comment]
It's been 9 months and no help ;-;

**Comment by htgoebel** [comment]
New news in this for more then half a year. closing. If you feel this is still an issue with the current release, please open a brand new issue.

**Comment by Schmetzler** [comment]
I had the same issue, but I found the solution,
you must add "msvcp140.dll" to upx-excludes (as well as "vcruntime140.dll"). Then everything works as expected (at least for me)

**Comment by engineervix** [comment]
> 
> 
> I had the same issue, but I found the solution,
> you must add "msvcp140.dll" to upx-excludes (as well as "vcruntime140.dll"). Then everything works as expected (at least for me)

Thanks @Schmetzler for this, I was going crazy! I'm building a [Gooey](https://github.com/chriskiehl/Gooey) application and I had already excluded `vcruntime140.dll`,  and ``python38.dll` but kept encountering an error whenever I ran the application. After excluding `vcruntime140.dll`, everything worked perfectly 😄

**Comment by christopherjude** [comment]
Hi, any updates on this ? (Not using upx) The exe runs fine on win 10 and 11 but this issue persists on win 8.1.
