### ISSUE TITLE
fix OSX tests for Travis

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1895]
The OS X tests do not pass:

Mark the failing tests as xfail and over time fix the following tests to pass:
- tests/functional/test_libraries.py::test_tkinter[onedir]
- tests/functional/test_libraries.py::test_tkinter[onefile]
- tests/functional/test_libraries.py::test_tkinter_FixTk[onedir]
- tests/functional/test_libraries.py::test_tkinter_FixTk[onefile]
- tests/functional/test_libraries.py::test_pil_FixTk[onedir]
- tests/functional/test_libraries.py::test_pil_FixTk[onefile]
- tests/functional/test_libraries.py::test_idlelib[onedir]
- tests/functional/test_libraries.py::test_idlelib[onefile]
- tests/functional/test_libraries.py::test_enchant[onedir]
- tests/functional/test_libraries.py::test_enchant[onefile]
- tests/functional/test_import.py::test_app_with_plugin[onedir]
- tests/functional/test_import.py::test_app_with_plugin[onefile]
- tests/functional/test_hooks/test_pil.py::test_pil_tkinter[onedir] - macpython
- tests/functional/test_hooks/test_pil.py::test_pil_tkinter[onefile] - macpython

**Comment by springermac** [comment]
@matysek Not all of these fail in the develop branch see https://travis-ci.org/springermac/pyinstaller-osx-tests/builds/117598116.

**Comment by matysek** [comment]
@springermac thanks for pointing this out - I realized that travis was stuck running the same git commit all the time.

**Comment by xoviat** [comment]
@htgoebel Can this be closed?

**Comment by springermac** [comment]
@xoviat @htgoebel No some of these tests are still marked as xfail though it may be better to open sperate issues for each test that is still marked as xfail though.

Some of these have been fixed and others already have separate issues so there should only be a couple that need to be done.

**Comment by htgoebel** [comment]
@springermac Seems like you have an overview about what still has to be done :-) Are you going to create the remaining issues, please? And please make sure the issue comment refers to xfail, thus the xfail hopefully will be removed when finished. Thanks.

**Comment by Legorooj** [comment]
Please address each test in its own PR.
