### ISSUE TITLE
Crash when trying to run a packaged blender as python module

### ISSUE THREAD

**Issue by 10-p** [pyinstaller/pyinstaller#1904]
Hi,

I've been trying to bundle blender when compiled as a python module. With that you just write "import bpy" within a script and the power of blender becomes available to you.

However, once I bundle the application successfully, and after copying an additional folder into the built folder, the second the script executes "import bpy", the program crashes. 
The program runs perfectly if I omit the "import bpy" statement.

This crash is consistent with blender not finding the scripts folder (in my case, 2.76) somewhere that python can find (in my case with the normal python on windows: "C:\Python34\2.76"), though there's more to it as you will see.
## Current Configuration:

My system configuration is:
- Windows 7 32 bits
- Python 3.4.4
- Blender 2.76b (built from source)
- PyInstaller 3.1.1

Spec file [here](http://pastebin.com/zvTVwtx3)
Logfile of the bundle creation [here](http://pastebin.com/fM9bceKs)
Logfile of the executable [here](http://pastebin.com/5QZJFHGH)
Warn file [here](http://pastebin.com/YgWmGyHB)
Mega testing script [here](http://pastebin.com/bi6BsHBT). The result of this script is a nice gray cube placed at C:\tmp\.png

I can provide my built files (they are the 2.76 folder, bpy.pyd and a few other dlls) of blender for testing, though building them is fairly easy, considering the complexity of the project. If on windows, just use "make.bat bpy" (once the dependencies are installed).
## Things I tried:
- Used to had Windows 10 64 bits, python 3.5 and blender 2.77 (blender is dependant on specific mayor python revisions), but I had the exact same crashes.
- Use the development version of pyinstaller. Building goes fine, but executing results in the following:

> LOADER: PYZ archive: out00-PYZ.pyz
> LOADER: Running pyiboot01_bootstrap.py
>   File "<string>", line 1
>     \ufffd
>     ^
> SyntaxError: invalid character in identifier
> pyiboot01_bootstrap returned -1
> LOADER: OK.
- Running the normal python interpreter while I monitor with "Process Monitor" and writing "import bpy", I can see that "2.76/scripts/modules/bpy_types.py" gets loaded first, then "2.76/scripts/modules/bpy/__init__.py", so on and so forth.
  However, when run the packaged version I can see that only" bpy_types.py" gets loaded, nothing else.
- This is the output of the script I use to build using the same libraries that pyinstaller uses when run through the normal python interpreter:

> C:>python
> Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600 32 bit (Intel)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> import bpy
> >>> bpy.ops.render.render(write_still=True)
> Fra:1 Mem:3.87M (9.89M, Peak 13.76M) | Time:00:00.00 | Preparing Scene data
> # ... FRAME RENDERING PROGRESS HERE, IT IS QUITE VERBOSE
> 
> Fra:1 Mem:3.79M (9.89M, Peak 19.90M) | Time:00:00.73 | Sce: Scene Ve:8 Fa:6 La:1
> Saved: C:\tmp\.png
>  Time: 00:00.87 (Saving: 00:00.13)
> 
> {'FINISHED'}
> >>> quit()
> Error: Not freed memory blocks: 8, total unfreed memory 0.004288 MB
> 
> C:>

I honestly don't know how can I tackle this, so any help will be greatly appreciated.

Thanks a lot

**Comment by krame505** [comment]
This bug affects me as well.

**Comment by hanbeibei** [comment]
oh.. I stuck on this bug, too...package it on windows 32bits system, but run on 64 bit system, the exe file seems not work at all.

**Comment by htgoebel** [comment]
Have you been able to solve this in the meantime?

>- Use the development version of pyinstaller. Building goes fine, but executing results in the following:
>
>> LOADER: PYZ archive: out00-PYZ.pyz
>> LOADER: Running pyiboot01_bootstrap.py
>>   File "<string>", line 1
>>     \ufffd
>>     ^
>> SyntaxError: invalid character in identifier
>> pyiboot01_bootstrap returned -1
>> LOADER: OK.

Please delete the `build/` folder to ensure there are no incompatible artifacts left.

> - Running the normal python interpreter while I monitor with "Process Monitor" and writing "import bpy", I can see that "2.76/scripts/modules/bpy_types.py" gets loaded first, then "2.76/scripts/modules/bpy/__init__.py", so on and so forth.
  However, when run the packaged version I can see that only" bpy_types.py" gets loaded, nothing else.

What do you mean with `I can see that only" bpy_types.py" gets loaded`? In the frozen application you should not see any file-access to such a file. All modules will be loaded from an archive.

Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by htgoebel** [comment]
No reaction for several month, assume this is solves.
