### ISSUE TITLE
Support pkgutil.iter_modules

### ISSUE THREAD

**Issue by TobiX** [pyinstaller/pyinstaller#1905]
I have a plugin system in Dosage which uses pkgutil.iter_modules (https://github.com/webcomics/dosage/blob/master/dosagelib/loader.py) to find all modules with plugins. It seems iter_modules is only supported for Python's built in loaders at the moment (see https://hg.python.org/cpython/file/tip/Lib/pkgutil.py#l128, https://hg.python.org/cpython/file/tip/Lib/pkgutil.py#l176 and https://hg.python.org/cpython/file/tip/Lib/pkgutil.py#l391). It would be nice if PyInstaller's FrozenImporter had a iter_modules implementing the pkgutil protocol¹, so one could discover modules in PyInstaller-packaged libraries.

(As you can see, I'm currently special-casing PyInstaller by accessing the "toc" set of FrozenImporter directly. This works, but feels a bit hacky to me...)

¹ This "contract" seems to be rather under-documented. It's implemented in pkgutil, which references PEP-302 a lot, but that does not mention iter_modules anywhere - I can only find a reference to this method in some [bug report](http://bugs.python.org/issue14982), [commit message](https://hg.python.org/cpython/rev/b92fa1c5a96b) and [withdrawn PEP-402](https://www.python.org/dev/peps/pep-0402/).

**Comment by mohanraj-r** [comment]
Thanks a lot @TobiX !

I have been struggling to get a frozen django app work with the `run_gunicorn` command which is discovered by django using `pkgutil.iter_modules()` which fails to work as expected inside the frozen app. 

I tried your[ `toc` hack ](https://github.com/webcomics/dosage/blob/master/dosagelib/loader.py)and it seems to work. 

Right now I am stuck at a `pkg_resources.load_entry_point()` exception for `gunicorn`

```
Error: class uri 'simple' invalid or not found:

[Traceback (most recent call last):
  File "site-packages/gunicorn/util.py", line 125, in load_class
  File "site-packages/pkg_resources/__init__.py", line 568, in load_entry_point
  File "site-packages/pkg_resources/__init__.py", line 561, in get_distribution
  File "site-packages/pkg_resources/__init__.py", line 441, in get_provider
  File "site-packages/pkg_resources/__init__.py", line 962, in require
  File "site-packages/pkg_resources/__init__.py", line 849, in resolve
DistributionNotFound: The 'gunicorn' distribution was not found and is required by the application
]
```

Anyway, back to more digging. Thanks again for the `toc` hack @TobiX

**Comment by mohanraj-r** [comment]
I was able to solve the `pkg_resources.load_entry_point()` issue by adding a `hooks.copy_metadata('gunicorn')`. Thanks to @bjones1 (https://github.com/pyinstaller/pyinstaller/issues/1713) 

```
from PyInstaller.utils import hooks
datas.extend(hooks.copy_metadata('gunicorn'))
```

**Comment by gendrion** [comment]
hi,

having the same issue, I've spun up a test repo that shows that the above workarounds aren't working for me 

https://github.com/gendrion/pyinstaller_test

as you can see it prints the following when run through an interpreter

```
Start Imports
module names from iter_modules:  ['mymodule.file1', 'mymodule.file2']
module names after get_importer toc:  ['mymodule.file1', 'mymodule.file2']
File 1 Imported
File 2 Imported
End Imports
```

but when running the exe:

```
Start Imports
module names from iter_modules:  []
module names after get_importer toc:  []
End Imports
```

I would expect get_importer to get the files even though iter_modules can't when using it via pyinstaller

Please advise :)

**Comment by gsemet** [comment]
works fine !

**Comment by gsemet** [comment]
Hi. update to pyinstaller 3.4 seem to have broken something:
- collect_submodule still works (as we can see in the log)
- but the [trick described here](https://github.com/gendrion/pyinstaller_test/blob/master/mymodule/__init.__py) using `pkgutil.get_importer` does not work anymore.

How can I list all submodule from a given point (a-la `pkgutil.iter_modules` which is known to not work with pyinstaller) ?

**Comment by The-Compiler** [comment]
With the current PyInstaller (`developer` branch, but I guess it's the same for v3.4), indeed, `pkgutil.get_importer()` returns `None`. However, using `pkgutil.iter_importers(package.__name__)` with `package` being your main package seems to work. Here's what I ended up doing:

```python
toc = set()
for importer in pkgutil.iter_importers('qutebrowser'):
    if hasattr(importer, 'toc'):
        toc |= importer.toc
for name in toc:
    if name.startswith(components.__name__ + '.'):
        yield name
```

Full file: [loader.py](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/extensions/loader.py)

**Comment by TobiX** [comment]
Just for the record: This was "broken" by b5c9f21fe6959d63dde77ee07ba60122e515f254 and can be restored by this diff:

```diff
--- a/PyInstaller/loader/pyimod03_importers.py
+++ b/PyInstaller/loader/pyimod03_importers.py
@@ -802,12 +802,12 @@ def install():
     fimp = FrozenImporter()
     sys.meta_path.append(fimp)
 
-    if sys.version_info[0] == 2:
-        # _`path_hook installation`: Add the FrozenImporter to `sys.path_hook`,
-        # too, since `pkgutil.get_loader()` does not use `sys.meta_path`. See
-        # issue #1689.
-        sys.path_hooks.append(fimp)
+    # _`path_hook installation`: Add the FrozenImporter to `sys.path_hook`,
+    # too, since `pkgutil.get_loader()` does not use `sys.meta_path`. See
+    # issue #1689.
+    sys.path_hooks.append(fimp)
 
+    if sys.version_info[0] == 2:
         # Import hook for renamed C extension modules. The path hook above means
         # that the standard Python import system for C extensions will only work
         # if those extensions are not in a submodule. In particular: A C
```

I'm a bit hesitant to suggest this as a fix, because I don't know the ins and outs of the python import system and how this might influence other behaviour.

**Comment by gsemet** [comment]
Hi. It would be cool to keep this feature running, somehow, since I have a pyinstaller executable that relies on this "discovery" mecanism (basically it is able to find its sub command automatically, each subcommand being on single .py file)

**Comment by arossert** [comment]
Any updates regarding this issue?
I want to use the faker module and having the issue with dynamic loading (#3839).
Is there a way around this?

**Comment by adamgreg** [comment]
This is a problem for me too. It would be great if it could be fixed. In the meantime is there a suggested workaround / alternative?

**Comment by The-Compiler** [comment]
I posted a workaround in my comment above.

**Comment by adamgreg** [comment]
Thanks @The-Compiler, I missed that before. I'll give it a try!

**Comment by gsemet** [comment]
Here is my updated function after recommendation from @The-Compiler 👍 
```python

def iter_namespace(ns_pkg):
    """Pyinstaller-compatible namespace iteration.

    Yields the name of all modules found at a given Fully-qualified path.

    To have it running with pyinstaller, it requires to ensure a hook inject the
    "hidden" modules from your plugins folder inside the executable:

    - if your plugins are under the ``myappname/pluginfolder`` module
    - create a file ``specs/hook-<myappname.pluginfolder>.py``
    - content of this file should be:

        .. code-block:: python

            from PyInstaller.utils.hooks import collect_submodules
            hiddenimports = collect_submodules('<myappname.pluginfolder>')
    """
    prefix = ns_pkg.__name__ + "."
    for p in pkgutil.iter_modules(ns_pkg.__path__, prefix):
        yield p[1]

    # special handling when the package is bundled with PyInstaller 3.5
    # See https://github.com/pyinstaller/pyinstaller/issues/1905#issuecomment-445787510
    toc = set()
    for importer in pkgutil.iter_importers(ns_pkg.__name__.partition(".")[0]):
        if hasattr(importer, 'toc'):
            toc |= importer.toc
    for name in toc:
        if name.startswith(prefix):
            yield name
```

works with Python 3.6 and Pyinstaller 3.5
