### ISSUE TITLE
Pyinstaller does not include movieypy properly and executable throws an error

### ISSUE THREAD

**Issue by pratikone** [pyinstaller/pyinstaller#1910]
My project is a video editor which makes use of PyQt4 and Moviepy modules. 
On running pyinstaller default spec with the project, the build goes without a problem but all attempts to run the executable throw error stating certain moviepy folder cannot be found. 

The issue has already been reported in moviepy community but since the domain of the problem is shared between moviepy and pyinstaller, hence, sharing it here too.
Here is the link : [url](https://github.com/Zulko/moviepy/issues/263)

Copying the error code from that issue here (my error message is similar) :    
`
C:\Users\domcib01\Documents\Lab Videos\Python\LAB_NAME\OS\LabTemplates\Python\LAB1>dist\lab1script\lab1script.exe Traceback (most recent call last): File "<string>", line 7, in <module> File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module exec(bytecode, module.__dict__) File "moviepy\editor.py", line 34, in <module> File "C:\Python27\Lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module exec(bytecode, module.__dict__) File "moviepy\video\fx\all\__init__.py", line 16, in <module> WindowsError: [Error 3] The system cannot find the path specified: 'C:\\Users\\domcib01\\DOCUME~1\\LABVID~1\\Python\\LAB_NAME\\OS\\LABTEM~1\\Python\\LAB1\\dist\\LAB1SC~1\\moviepy\\video\\fx/*.*' lab1script returned -1
`

OS : Windows 7
Python version : 2.7
Latest PyQt4 and moviepy installed via pip

**Comment by matysek** [comment]
Please follow:
* https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong
* https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

**Comment by pratikone** [comment]
Hi @matysek , it was the first thing I did.
However, I went into the source code of moviepy to find what was the problem. Turns out a rogue exec statement was the issue. I have developed a workaround it and have posted [here](https://github.com/Zulko/moviepy/issues/263#issuecomment-203831141). Please have a look at it as it explains the problem and the solution.

**Comment by htgoebel** [comment]
moviepy/video/fx/all/__init__.py needs to be adopted to run when frozen. See my comment on you moviepy issue.

**Comment by serkandaglioglu** [comment]
@htgoebel I read  your comment on moviepy issue but the link is broken. I have same problem. How can I solve?

**Comment by htgoebel** [comment]
@serkandaglioglu: see https://github.com/pyinstaller/pyinstaller/issues/1910#issuecomment-203838488

**Comment by aminanderian** [comment]
> @serkandaglioglu: see [#1910 (comment)](https://github.com/pyinstaller/pyinstaller/issues/1910#issuecomment-203838488)

Hi htgoebel,
I read your comment but can't find out what you ant to say that's not clear for me,
can you explain about moviepy/video/fx/all/__init__.py ?
thanks
