### ISSUE TITLE
Random ImportError: DLL load failed: Invalid access to memory location

### ISSUE THREAD

**Issue by shanewangs** [pyinstaller/pyinstaller#1914]
This is an anonnying bug which won't happen every time but is worth noting. 

**Basics**: python 2.7.3(32bit), wxPython 3.0.2(32bit), cython 0.23.4, windows 7 64bit , pyinstaller 3.1.1

My app is generated with `pyinstaller myapp.py --onefile -w`, so it occasionally gives `myapp returned -1` window when loading. In order to find out what went wrong, I bundled a new version with `pyinstaller myapp.py --onefile`, and got the trackback:

```
Trackback (most recent call last):
File "<string>", line 43, in <module>
File "d:\program files (x86)\python2.7.3\lib\site-packages\pyinstaller-3.1.1-py2.7.egg\PyInstaller\loader\pyimod03_importers.py", line 546, in load_module
ImportError: DLL load failed: Invalid access to memory location.
```

I also tried to make it work with `pyisntaller 2.1`, but got similar trackback as well:

```
File "<string>", line 43, in <module>
File "\program files (x86)\python2.7.3\lib\site-packages\pyinstaller-2.1-py2.7.egg\\PyInstaller\loader\pyi_importers.py", line 409, in load_module
    module = imp.load_module(fullname, fp, filename, self._c_ext_tuple)
ImportError: DLL load failed: Invalid access to memory location.
```

**Comment by matysek** [comment]
Please provide minimal example how to reproduce that.

**Comment by shanewangs** [comment]
Found the solution! It works all right for the past hours or so, and will keep tracking to make sure my software won't occasionally crash when it starts. 

According to http://stackoverflow.com/a/19222790/5090290

> The issue was that python linked to different msvcrt than MinGW when compiling the module -- it is reported at http://bugs.python.org/issue16472.

And then  according to http://bugs.python.org/issue16472#msg193968:

> I can confirm that when a module is linked against msvcr90, it crashes with "invalid access to memory". When removed that library from the linker options (that is - no explicit msvcr, in any version) - module worked perfectly.
> 
> Note that comment on http://hg.python.org/cpython/file/6e1dd1ce95b8/Lib/distutils/cygwinccompiler.py#l333 (Minge32CComiler class) already says "no additional libraries needed", but 3 lines later it sets dll_libraries to msvcr90 (via get_msvcr). So just removing lines 336:338 works great.
