### ISSUE TITLE
Use `docs.pyinstaller.org` for hosting the docs?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#1915]
Read the Docs [supports CNAME](http://docs.readthedocs.org/en/latest/alternate_domains.html#cname-support). So we could point docs.pyinstaller.org there and use our own domain when referring to the docs.

What do you think?

**Comment by matysek** [comment]
@htgoebel this sounds good.  +1

**Comment by bjones1** [comment]
+1

**Comment by htgoebel** [comment]
@rasky So can you please add a CNAME to the DNS:

docs.pyinstaller.org.   7200    IN  CNAME   readthedocs.org.

Thanks.

**Comment by htgoebel** [comment]
@rasky Pinging: Can you please add a CNAME to the DNS:

docs.pyinstaller.org. 7200 IN CNAME readthedocs.org.

**Comment by Legorooj** [comment]
@bjones1 @htgoebel @matysek is there any point now? `pyinstaller.readthedocs.io` is so well known that people will get confused if we switch.

**Comment by bjones1** [comment]
I agree. Let's leave this as is.
