### ISSUE TITLE
Application enters infinite loop after PyInstaller build 

### ISSUE THREAD

**Issue by BillBridge** [pyinstaller/pyinstaller#1921]
I have written an application that runs without any problems on my windows desktop both from a PyCharm instance as well as from the Python commandline.
The build with PyInstaller (latest version - fresh new build) completes without erros. But when starting the application, it enters a kind of infinite loop.

The application characteristics:
- Windows 7
- Python 2.7.11
- Kivy 1.9.1
- numpy 1.10.4
- Matplotlib 1.3.0
- OpenCV 2.4.12
- imutils
- tinydb 3.1.3
- psutil 4.1
- pyHook 1.5.1
- Pillow 3.1.1

It makes use of multiprocessing so I have implemented the relating recipe: freeze_support(). 

I have followed all the hints and tips I could find but nothing provided me the solution (as far as I could understand these - I am newbee type.....).

Attached you will find a file containing the .spec file, the output of the PyInstaller build and the logging (Debug mode) when executing the application:
[PyInt-Logging03042016.txt](https://github.com/pyinstaller/pyinstaller/files/201513/PyInt-Logging03042016.txt)

I noticed the following in the warn~.txt file: I created a test version of the application containing only the multiprocessing flow and primary GUI (Kivy) interaction. This application builds and runs without any problems. But the warn~.txt file of both versions contain about exactly the same list of warnings. So I have attached this file as well.

[warnpapack.txt](https://github.com/pyinstaller/pyinstaller/files/201519/warnpapack.txt)

Please could you help me solving my problems?
Thanks very much in advance.

**Comment by matysek** [comment]
* Could you debug your app to the few lines that cause that? Any minimal example to reproduce?
* Does anything from #1899 applies to your case?

**Comment by BillBridge** [comment]
Thanks for your very very quick reply.
I am not sure if #1899 applies here but there might be some clues.

Please find some debug info.

It starts with the file arcanamain.py:
`def showArcana():
        print "IN: showArcana..."
        import arcana
        arcana.startArcana()
    
    
    if __name__ == "__main__":
        from multiprocessing import freeze_support
        import arc_activate
        freeze_support()
        arc_activate.showGate()
`

Then in arc_activate.py > showGate():
`def showGate():

    from kivy.app import App
    from kivy.uix.widget import Widget
    from kivy.core.window import Window

    from multiprocessing import Process, freeze_support

    class arc_Gate(Widget):

        def init_arcana(self):
            pass

        def open_arcana(self):
            print "IN: open_arcana..."
            editProcess = Process(target=arcanamain.showArcana)
            print "PASSED: Process..."
            editProcess.daemon = False
            editProcess.start()
            print "PASSED: start...."
            editProcess.join()
            print "PASSED: join..."
            os._exit(0)

            if editProcess.exitcode != 0:
                os._exit(0)

    class arc_activateApp(App):
        def build(self):
            global appsize
            Window.size = appsize
            Window.clearcolor = (1,1,1,0)
            Window.clear()
            arcWin = arc_Gate()
            arcWin.init_arcana()
            return arcWin

    arc_activateApp().run()
`

As you can see in the debug, it never reaches arcanamain.showArcana:
C:\Projects\UP52\UP52-PAPACK\dist\papack>.\papack.exe
PyInstaller Bootloader 3.x
LOADER: executable is C:\Projects\UP52\UP52-PAPACK\dist\papack\papack.exe
LOADER: homepath is C:\Projects\UP52\UP52-PAPACK\dist\papack
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Projects\UP52\UP52-PAPACK\dist\papack\papack.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\Projects\UP52\UP52-PAPACK\dist\papack)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\Projects\UP52\UP52-PAPACK\dist\papack\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Projects\UP52\UP52-P~1\dist\papack
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Projects\UP52\UP52-PAPACK\dist\papack
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running pyi_rth_kivy.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth_win32comgenpy.py
LOADER: Running pyi_rth_gstreamer.py
LOADER: Running arcanamain.py
[INFO              ] [Logger      ] Record log in C:\Users\VanDeBrugWi\.kivy\log
s\kivy_16-04-03_11.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015,
20:32:19) [MSC v.1500 32 bit (Intel)]
screensize (40, 40)
desktopsize (1366, 768)
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sd
l2, img_pil (img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.0.0 - Build 10.18.10.4176>

[INFO              ] [GL          ] OpenGL vendor <Intel>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 4000>
[INFO              ] [GL          ] OpenGL parsed version: 4, 0
[INFO              ] [GL          ] Shading version <4.00 - Build 10.18.10.4176>

[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, n
ot docked
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] NPOT texture support is available
IN: open_arcana...
_**PASSED: Process...
PASSED: start....**_
PyInstaller Bootloader 3.x
LOADER: executable is C:\Projects\UP52\UP52-PAPACK\dist\papack\papack.exe
LOADER: homepath is C:\Projects\UP52\UP52-PAPACK\dist\papack
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Projects\UP52\UP52-PAPACK\dist\papack\papack.exe

**Comment by BillBridge** [comment]
Still haven't found any clues or whatsoever. Here is some comparison of logging in the .kivy logs directory when running the application from 3 different starting angels.

1) This is the logging when running the application in the PyCharm environment. In this case it runs without any problems.

[INFO              ] [Logger      ] Record log in ~\.kivy\logs\kivy_16-04-05_27.txt
[INFO              ] [Kivy        ] v1.9.1
[INFO              ] [Python      ] v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
[INFO              ] [Factory     ] 179 symbols loaded
[INFO              ] [Image       ] Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] [OSC         ] using <thread> for socket
[INFO              ] [Window      ] Provider: sdl2
[INFO              ] [GL          ] GLEW initialization succeeded
[INFO              ] [GL          ] OpenGL version <4.0.0 - Build 10.18.10.4176>
[INFO              ] [GL          ] OpenGL vendor <Intel>
[INFO              ] [GL          ] OpenGL renderer <Intel(R) HD Graphics 4000>
[INFO              ] [GL          ] OpenGL parsed version: 4, 0
[INFO              ] [GL          ] Shading version <4.00 - Build 10.18.10.4176>
[INFO              ] [GL          ] Texture max size <16384>
[INFO              ] [GL          ] Texture max units <16>
[INFO              ] [Window      ] auto add sdl2 input provider
[INFO              ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO              ] [Text        ] Provider: sdl2
[INFO              ] [GL          ] NPOT texture support is available
[INFO              ] [Base        ] Start application main loop
[INFO              ] [GL          ] Unpack subimage support is available


2) This is the logging when running the application from the Python commandline. In this case it runs without any problems.

[INFO              ] Logger: Record log in ~\.kivy\logs\kivy_16-04-05_25.txt
[INFO              ] Kivy: v1.9.1
[INFO              ] Python: v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
[INFO              ] Factory: 179 symbols loaded
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] OSC: using <thread> for socket
[INFO              ] Window: Provider: sdl2
[INFO              ] GL: GLEW initialization succeeded
[INFO              ] GL: OpenGL version <4.0.0 - Build 10.18.10.4176>
[INFO              ] GL: OpenGL vendor <Intel>
[INFO              ] GL: OpenGL renderer <Intel(R) HD Graphics 4000>
[INFO              ] GL: OpenGL parsed version: 4, 0
[INFO              ] GL: Shading version <4.00 - Build 10.18.10.4176>
[INFO              ] GL: Texture max size <16384>
[INFO              ] GL: Texture max units <16>
[INFO              ] Window: auto add sdl2 input provider
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] Text: Provider: sdl2
[INFO              ] GL: NPOT texture support is available
[INFO              ] Base: Start application main loop
[INFO              ] GL: Unpack subimage support is available

3) This is the logging when running the application from the PyInstaller build package.
[INFO              ] Logger: Record log in ~\.kivy\logs\kivy_16-04-05_22.txt
[INFO              ] Kivy: v1.9.1
[INFO              ] Python: v2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:32:19) [MSC v.1500 32 bit (Intel)]
[INFO              ] Factory: 179 symbols loaded
[INFO              ] Image: Providers: img_tex, img_dds, img_gif, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO              ] OSC: using <thread> for socket
[INFO              ] Window: Provider: sdl2
[INFO              ] GL: GLEW initialization succeeded
[INFO              ] GL: OpenGL version <4.0.0 - Build 10.18.10.4176>
[INFO              ] GL: OpenGL vendor <Intel>
[INFO              ] GL: OpenGL renderer <Intel(R) HD Graphics 4000>
[INFO              ] GL: OpenGL parsed version: 4, 0
[INFO              ] GL: Shading version <4.00 - Build 10.18.10.4176>
[INFO              ] GL: Texture max size <16384>
[INFO              ] GL: Texture max units <16>
[INFO              ] Window: auto add sdl2 input provider
[INFO              ] Window: virtual keyboard not allowed, single mode, not docked
[INFO              ] Text: Provider: sdl2
[INFO              ] Base: Start application main loop
[INFO              ] GL: NPOT texture support is available
[INFO              ] Base: Leaving application in progress...
[WARNING           ] stderr: Traceback (most recent call last):
[WARNING           ] stderr:   File "<string>", line 23, in <module>
[WARNING           ] stderr:   File "C:\Projects\UP52\arc_activate.py", line 57, in showGate
[WARNING           ] stderr:     arc_activateApp().run()
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\app.py", line 828, in run
[WARNING           ] stderr:     runTouchApp()
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\base.py", line 487, in runTouchApp
[WARNING           ] stderr:     EventLoop.window.mainloop()
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 619, in mainloop
[WARNING           ] stderr:     self._mainloop()
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\core\window\window_sdl2.py", line 362, in _mainloop
[WARNING           ] stderr:     EventLoop.idle()
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\base.py", line 330, in idle
[WARNING           ] stderr:     self.dispatch_input()
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\base.py", line 315, in dispatch_input
[WARNING           ] stderr:     post_dispatch_input(*pop(0))
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\base.py", line 221, in post_dispatch_input
[WARNING           ] stderr:     listener.dispatch('on_motion', etype, me)
[WARNING           ] stderr:   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\core\window\__init__.py", line 1030, in on_motion
[WARNING           ] stderr:     self.dispatch('on_touch_down', me)
[WARNING           ] stderr:   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\core\window\__init__.py", line 1046, in on_touch_down
[WARNING           ] stderr:     if w.dispatch('on_touch_down', touch):
[WARNING           ] stderr:   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\uix\widget.py", line 432, in on_touch_down
[WARNING           ] stderr:     if child.dispatch('on_touch_down', touch):
[WARNING           ] stderr:   File "kivy\_event.pyx", line 718, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7699)
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\uix\behaviors\button.py", line 110, in on_touch_down
[WARNING           ] stderr:     self.dispatch('on_press')
[WARNING           ] stderr:   File "kivy\_event.pyx", line 714, in kivy._event.EventDispatcher.dispatch (kivy\_event.c:7654)
[WARNING           ] stderr:   File "kivy\_event.pyx", line 1224, in kivy._event.EventObservers.dispatch (kivy\_event.c:13497)
[WARNING           ] stderr:   File "kivy\_event.pyx", line 1108, in kivy._event.EventObservers._dispatch (kivy\_event.c:12329)
[WARNING           ] stderr:   File "c:\python27\lib\site-packages\kivy\lang.py", line 1557, in custom_callback
[WARNING           ] stderr:     exec(__kvlang__.co_value, idmap)
[WARNING           ] stderr:   File "C:\Projects\UP52\UP52-P~1\dist\papack\arc_activate.kv", line 5, in <module>
[WARNING           ] stderr:     on_press: root.open_arcana()
[WARNING           ] stderr:   File "C:\Projects\UP52\arc_activate.py", line 32, in open_arcana
[WARNING           ] stderr:     editProcess.join()
[WARNING           ] stderr:   File "C:\Python27\lib\multiprocessing\process.py", line 145, in join
[WARNING           ] stderr:     res = self._popen.wait(timeout)
[WARNING           ] stderr:   File "C:\Python27\lib\multiprocessing\forking.py", line 297, in wait
[WARNING           ] stderr:     res = _subprocess.WaitForSingleObject(int(self._handle), msecs)
[WARNING           ] stderr: KeyboardInterrupt


Any help in finding the problem is highly appreciated. Thanks in advance.

**Comment by BillBridge** [comment]
The PyInstaller build also fails over multiprocessing.Manager()

I have removed the initial part of the application (see above. now directly calling arcanamain.showArcana() ).
Now it starts correctly the next kivy window (process) but it fails over creating a global namespace using multiprocessing.Manager():

# Create a global nameSpace carrying the actual instruction dictionary
freeze_support()
playMgr = Manager()

The recipe re. putting freeze_support() does not help unfortunately.
The console output shows:

PyInstaller Bootloader 3.x
LOADER: executable is C:\Projects\UP52\UP52-PAPACK\dist\papack\papack.exe
LOADER: homepath is C:\Projects\UP52\UP52-PAPACK\dist\papack
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Projects\UP52\UP52-PAPACK\dist\papack\papack.exe
LOADER: No need to extract files to run; setting extractionpath to homepath
LOADER: SetDllDirectory(C:\Projects\UP52\UP52-PAPACK\dist\papack)
LOADER: Already in the child - running user's code.
LOADER: Python library: C:\Projects\UP52\UP52-PAPACK\dist\papack\python27.dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Projects\UP52\UP52-P~1\dist\papack
LOADER: Setting runtime options
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Projects\UP52\UP52-PAPACK\dist\papack
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py

**Comment by htgoebel** [comment]
Is this still an issue? If so, have you tried the current development version and is it solved there?

**Comment by BillBridge** [comment]
This issue is resolved. I do not know exactly anymore how we've resolved this (unfortunately).

**Comment by lfernandes** [comment]
Just in case someone else comes here looking for a solution, here is what worked for me:


```python
import multiprocessing
...

if __name__ == '__main__':

    # Pyinstaller fix
    multiprocessing.freeze_support()

    main()
```

I found it [here](https://stackoverflow.com/a/32677108/1541042), and you can see more details on [this wiki](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing).
