### ISSUE TITLE
PyQt5/QtQuick: qmldir and qmltypes files are not copied

### ISSUE THREAD

**Issue by alinmear** [pyinstaller/pyinstaller#1922]
I encountered an error while building a PyQt5 Qml Application. 

The PyQt5.QtQuick hook pulls in the folders QtQml, QtQuick, QtQuick.2 as expected but doesn´t pull in the "qmldir" and "*.qmltypes" files in any of the sub/folders.

After Copying them per hand the application works as expected (Without copying these files, the application quits with the following msg: QtQuick/QtQuick.Layouts/QtQuick.Controls is not installed; list index out of range).

Plattform:
Windows 7 x64 Ultimate
Python 3.4 32bit
VM within VMWare Workstation 12 Pro
PyInstaller Version 3.1.1

**Comment by metachris** [comment]
Same on OSX with PyInstaller v3.1.1

This is the hook in question: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-PyQt5.QtQuick.py

**Comment by emohedano** [comment]
I'm currently experiencing a similar issue. When I execute `pyinstaller sample.py` I get a folder with the following structure
- dist
  - sample
    - qml
      - Controls.2
      - QtQuick
        - Controls.2

But when I try to run my program I get the following error:
```
qml/QtQuick/Controls.2/ApplicationWinwow.qml: -1 No such file or directory
```
When I copy the *.qml and *.js files from qml/Controls.2 to qml/QtQuick/Controls.2 everything works as expected, so I was wondering if anyone else was having the same problem or if I am doing something wrong? 

Help appreciated

**Comment by cbenhagen** [comment]
@emohedano this can be fixed like this:
https://github.com/pyinstaller/pyinstaller/pull/2743

**Comment by htgoebel** [comment]
duplicate of #2743
