### ISSUE TITLE
Unable to acquire oracle environment handle

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#1924]
Pyinstaller has problems handling scripts tha import ex_oracle. While the compilation works fine, the problem will execute with a runtime error: Ex_oracle.interfaceError: unable to acquire oracle environment handle

This has been reported by various users. Proposed solutions of correctly setting the environment variables or excluding oci.dll from the complication do not always work.

**Comment by dickreuter** [comment]
I have found the solution and how it could be fixed, but somebody needs to implement it:

Whnever a script imports cx_Oracle the following file needs to added to the exe part of the spec file:
   a.binaries+[('oraociei12.dll','oraociei12.dll','BINARY')],

Currently oraociei12.dll (which is part of cx_Oracle, is missing and that's why pyinstaller is not compiling this package correctly. For older versions it can also be oraociei11.dll instad of 12.

**Comment by htgoebel** [comment]
We would appreciate if you'd submit a hook for this. See https://pyinstaller.readthedocs.org/en/latest/hooks.html for more information about who to implement hooks.

**Comment by robo3945** [comment]
The proposed solution works well but it's better to know that the second element of the tuple is the DLL filename **with its path**. So in my spec file I used this one:  a.binaries+[('oraociei12.dll','C:\\oracle\\product\\instantclient_12_1\\oraociei12.dll','BINARY')],

I hope this help

**Comment by zeruitle** [comment]
I have 2 question:
1. is oraociei11 or oraociei12 matters? if so, how?
2. even if we package oraociei inside, is target computer need install oracle? or at least instant client?

Thank You
