### ISSUE TITLE
appveyor: install mingw-w64 using msys2

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#1932]
For appveyor we now use VisualStudio to compile bootloader. However, our precompiled bootloader is compiled with mingw-w64. We should try again to get mingw-w64 to appveyor environment.

Implementation:
- appveyor bundles msys2
- msys2 contains package manager `pacman`
- use `pacman` to install mingw-w64 package

Links:
- http://help.appveyor.com/discussions/suggestions/615-support-for-msys2
- https://github.com/appveyor/ci/issues/352#issuecomment-138149606
- https://github.com/msys2/MINGW-packages
- https://github.com/appveyor/ci/issues/597
- https://github.com/appveyor/ci/issues/466

**Comment by htgoebel** [comment]
Pre-compiiled bootloaders are build with VisualStudio now, see #2415
