### ISSUE TITLE
scan_code_for_ctypes relusts in absolute path for binary name and buid fails with security warning.

### ISSUE THREAD

**Issue by concussiongfx** [pyinstaller/pyinstaller#1934]
Hi,
I am trying to upgrade my build system from pyInstaller2.1 to 3.1.1 and I am seeing a failure on windows during the build process. I see this warning and exit:

> Security-Alert: try to store file outside of dist-directory. Aborting.

I have tracked this down to how **scan_code_for_ctypes** is finding the dll. In **__scan_code_instruction_for_ctypes** we find the library name and return **ctypes.util.find_library(libname**). The problem is what **find_library** returns is an absolute path to the dll and we wind up with a binary entry like:

`('C:\\Program Files\\ImageMagick-6.9.2-Q16\\CORE_RL_wand_.dll', 'C:\\Program Files\\ImageMagick-6.9.2-Q16\\CORE_RL_wand_.dll', 'BINARY')`

There is this cehck and warning, but nothing is done to remove or fix the bad path
```
        elif binary != os.path.basename(binary):
            # TODO make these warnings show up somewhere.
            logger.warn("ignoring %s - ctypes imports only supported using bare filenames", binary)
```

**Comment by htgoebel** [comment]
Are you using an absolute path in your program when calling `ctypes.util.find_library(CORE_RL_wand_.dll)`?

**Comment by concussiongfx** [comment]
I am not. Here is the line from my code.

`libpath = ctypes.util.find_library('CORE_RL_wand_')`

doing a quick test from python, I see this:

```
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (
AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import ctypes.util
>>> ctypes.util.find_library("CORE_RL_Wand_")
'C:\\Program Files\\ImageMagick-6.9.2-Q16\\CORE_RL_Wand_.dll'
>>> ctypes.util.find_library("ACCTRES")
'C:\\Windows\\system32\\ACCTRES.dll'
>>>
```

changing the append to only add the basename gets around the issue in my case, but I am not sure if it is the right change for PyInstaller as a whole.

```
def __recursivly_scan_code_objects_for_ctypes(co, binaries):
    # Note: `binaries` is a list, which gets extended here.
    instructions = iter(pass1(co.co_code))
    while 1:
        # ctypes scanning requires a scope wider than one bytecode
        # instruction, so the code resides in a separate function
        # for clarity.
        try:
            bin = __scan_code_instruction_for_ctypes(co, instructions)
            if bin:
                binaries.append(os.path.basename(bin))
        except StopIteration:
            break

    for c in co.co_consts:
        if isinstance(c, type(co)):
            __recursivly_scan_code_objects_for_ctypes(c, binaries)
```

**Comment by htgoebel** [comment]
Thanks for the info.

The correct place would after the `ctypes.util.find_library(libname)` at the end of `__scan_code_instruction_for_ctypes`. Otherwise we would remove the path even if someone used an absolute path in e.g. `cdll.Library()` - which would not work in a frozen app. I'll push a fix in a few minutes.
