### ISSUE TITLE
Problem jinja2 render

### ISSUE THREAD

**Issue by junajo10** [pyinstaller/pyinstaller#1938]
Hello,
I have created my file .exe 
pyinstaller -F myfile.py

When I execute the generated file myfile.exe, I obtained this message:
NotImplementedError: Can't perform this operation for unregistered loader type

I have replaced:
```
CONTENT_FILENAME = "./content.html"
PAGE_FILENAME = "./page.html"
#template_content = jinja2_env.get_template(CONTENT_FILENAME)
#template_page = jinja2_env.get_template(PAGE_FILENAME)
```
by:
```
template_content =jinja2_env.from_string(open(os.path.join(os.path.dirname(__file__), 'templates', CONTENT_FILENAME)).read())
template_page =jinja2_env.from_string(open(os.path.join(os.path.dirname(__file__), 'templates', PAGE_FILENAME)).read())
```
but i have problems with this line: JINJA2 RENDER
```
self.template_page_highcharts = template_page
self._htmlcontent = self.template_page_highcharts.RENDER(chart=self)
```
Could someone help me to solve this problem?

Rgds,
JJ

**Comment by htgoebel** [comment]
You need to change the way to get the filename, see https://pyinstaller.readthedocs.org/en/latest/runtime-information.html
