### ISSUE TITLE
Executable extremely large or not built

### ISSUE THREAD

**Issue by mountDoom2** [pyinstaller/pyinstaller#1940]
Hello,

I'm creating a cross-platform application and I'm trying to bundle a zip file, which has about 700MB into the executable. When I run pyinstaller, the build creates extremely big executable or crashes, depending on system. On 32-bit Debian 8.2 I'm getting the following error during build:

```
242977 INFO: Appending archive to ELF section in EXE /home/user/dist/executable
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.2.dev0-g2f86ac6', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 39, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/api.py", line 407, in __init__
    self.__postinit__()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/api.py", line 564, in assemble
    raise SystemError("objcopy Failure: %s" % stderr)
SystemError: objcopy Failure: 
objcopy: out of memory allocating 2147483648 bytes after a total of 0 bytes
```
On other systems (Centos 6.6-64bit and Windows 7-64bit) the binary is created, but it has 1.6GB with same archive included.
Before I added the zipfile (to be exact - when I used 10MB archive for testing), the resulting application had 30MB (which is all right as it uses wxPython), but with the real archive the executable size had increased by more than double of 'pure' datasize.

On all platforms I use Python 2.7
On Linux platforms I use Pyinstaller 3.2.dev0-g2f86ac6
On Windows platforms I use Pyinstaller 3.1.1

Here's my spec file:
```
# -*- mode: python -*-
import os
from os import path

block_cipher = None
import os

datas = []
dirs = ['files', 'images']
for dir in dirs:
   for fname in os.listdir(src_path):
       datas.append((path.join(src_path, fname), dir))
       
a = Analysis([path.join(src_path, 'main.py')],
             pathex=[src_path, ''],
             binaries=None,
             datas=datas,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='main',
          debug=False,
          strip=False,
          upx=True,
          console=True )
```
and I run pyinstaller with:

`os.system(r"pyinstaller --windowed --clean --log-level=DEBUG %s"%(spec_path))`

**Comment by htgoebel** [comment]
PyInstaller puts your zipfile into another zip-container, together with the python code and all your other files and images. This huge file is then appended to the PyInstaller bootloader using objcopy.

Your development machine fails to package since it is 32-bit. 2147483648 (2GB) is the maximum size a 32-bit system can handle. Given that the file is approx. 1,6GB, it' clear that the build fails. (Well, objcopy could do a better job here.)

Regarding the size: Please check the size of build/*/*PYZ* and use the archive-viewer and inspect that file. Maybe you have some additional data in your `files` or `images` directory.

Oh, I just spotted a possible error: I assume all files and images are added several times: if `datas` contains a directory, the whole content is included automatically. But you are adding all files an directories recursively. See the bottom of this manual section: https://pythonhosted.org/PyInstaller/#id53.

**Comment by tallforasmurf** [comment]
For some reason linking to `/#id53` doesn't work for me. Try https://pythonhosted.org/PyInstaller/#adding-data-files .

**Comment by mountDoom2** [comment]
Thank you helping me out, the archive was really appended mutiple times. I do apologize for bothering you with such issues.
