### ISSUE TITLE
win32 specific version-file option broken under python3

### ISSUE THREAD

**Issue by AndCycle** [pyinstaller/pyinstaller#1955]
`pyinstaller --version-file ver.txt --onefile test.py`

this is actually an upstream bug in pywin32, 
I just left the issue here to ease the tracking

http://stackoverflow.com/questions/31290641/how-do-i-use-pywintypes-unicode/31314297#31314297

pywintypes.Unicode() fails in Python 3
https://sourceforge.net/p/pywin32/bugs/697/

>   File "D:\test\build\virtualenv_runtime\env\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 161, in toRaw
>     nm = pywintypes.Unicode(u'VS_VERSION_INFO')
> TypeError: must be impossible<bad format char>, not str
>

**Comment by htgoebel** [comment]
Thanks for reporting this here. I assume it is okay closing this issue, since you write "I just left the issue here to ease the tracking".
