### ISSUE TITLE
Generating an uninstaller

### ISSUE THREAD

**Issue by jacksonofalltrades** [pyinstaller/pyinstaller#1960]
I'm wondering if pyinstaller has any support for generating platform-specific uninstallers. I'm not really sure what the best way is to write a program that will remove itself and all of the rest of the stuff generated by pyinstaller.

Thoughts? Suggestions? Thanks!

**Comment by tallforasmurf** [comment]
What am I missing? All the stuff that PyInstaller collects goes into either a single folder or a single executable file. To uninstall, just delete it.

**Comment by jacksonofalltrades** [comment]
Can I write a script that deletes itself and it's own folder? Windows, OSX, and Linux won't complain about that? If so, you're right, it's pie.

**Comment by tallforasmurf** [comment]
Me, I would just tell my users, "to uninstall the whizbang app, just move it to the trash." But as for how automated uninstall is supposed to work on the major platforms, I'm clueless.

Anybody else with an idea?

**Comment by jacksonofalltrades** [comment]
Yeah, I get where you're coming from, but unfortunately I have to make this idiot-proof for my clients users.

**Comment by htgoebel** [comment]
I'm afraid you need to use a separate installer then. E.G. [nsis](http://nsis.sourceforge.net/)
