### ISSUE TITLE
Freezing a PyGI app

### ISSUE THREAD

**Issue by cinchent** [pyinstaller/pyinstaller#1966]
I was having no success freezing my PyGI (a.k.a. PyGObject) application into an executable.  (Per the "Supported Packages", I was using the 3.2 preliminary version of PyInstaller, PyGi 3.18.2, Windows 7, Python 2.7.10)

To simplify the problem from my (somewhat large) PyGI app and try a more basic test, I picked a random PyGI example program (`spinner.py`) verbatim from the Gnome site.  It executed fine as a script, but after freezing it as a single executable via `pyinstaller -F spinner.py`, this was the result when I launched the executable:

```
Traceback (most recent call last):
  File "spinner.py", line 2, in <module>
  File "site-packages\gi\__init__.py", line 102, in require_version
ValueError: Namespace Gtk not available
Failed to execute script spinner
```

I won't bore you with the details of what all I had to try to get past this problem, but the solution may be of interest to others.

It turns out that the PyGI installation may not include .gir files, which are necessary in the freezing process, in order for the PyGI introspection layer to have the correct API definitions for the Gnome libraries.  (GIR files are XML representations of the type library files representing the APIs in binary form.)

On my system, the `.typelib` files were in `C:\Python27\Lib\site-packages\gnome\lib\girepository-1.0`.  The PyInstaller hooks expect to find them the corresponding `.gir` files in the `C:\Python27\share\gir-1.0` directory, which I had to create. Using the `g-ir-generate` utility, which may be included in the PyGI installation bundle, it was a simple matter of executing:
  `g-i-generate Gtk-3.0.typelib >C:\Python27\share\gir-1.0\Gtk-3.0.gir`
and so on, for each `.typelib` file.

Voila.

**Comment by matysek** [comment]
@htgoebel and @codewarrior0  do you think that this is something that could be automated with the pygi hook or is this a candidate for a recipe?

**Comment by htgoebel** [comment]
In `PyInstaller.utils.hooks.gi.gir_library_path_fix` we aleady call `g-ir-compiler`. So maybe this can be automated, too.

@springermac, @virtuald: Want to help here?

**Comment by virtuald** [comment]
Interesting, @cinchent

* How did you install PyGI? Via the all-in-one installer?
* Are there any gir files anywhere? Perhaps we're just looking in the wrong place... I don't think PyGI can function without the compiled files.

**Comment by cinchent** [comment]
Yes, I used the all-in-one installer.

No, there were no .gir files anywhere.  After contacting the maintainer of the all-in-one installer (tumagonx), he acknowledged the lack of them, but (inexplicably enough) in the latest version (pygi-aio3.18.2-rev7) actually removed the g-ir-generate precompiled executable from the all-in-one bundle, even when the "Install Gir" option is checked!  When I questioned the rationale for that, he said anyone could always download that project and build the executables from source, and omitted them because "who would need to build .gir files"?

**Comment by cinchent** [comment]
Incidentally, there was a follow-up issue (#1968) related to this.  In the end, there was a happy outcome to that, but there is an ongoing issue with the PyGObject hooks when a particular PyGObject module is imported, with certain dependent certain type libraries remaining absent.  See that issue for details.

**Comment by ic3man5** [comment]
I get this same issue with Python3.4 but I don't have a share directory.

looks like all my *.typelib files are in:
C:\Python34\Lib\site-packages\gnome\lib\girepository-1.0\


```
D:\development\python_stuff>PyInstaller gtk_test.py
70 INFO: PyInstaller: 3.2
70 INFO: Python: 3.4.4
71 INFO: Platform: Windows-10-10.0.14393
73 INFO: wrote D:\development\python_stuff\gtk_test.spec
74 INFO: UPX is not available.
75 INFO: Extending PYTHONPATH with paths
['D:\\development\\python_stuff', 'D:\\development\\python_stuff']
75 INFO: checking Analysis
76 INFO: Building Analysis because out00-Analysis.toc is non existent
76 INFO: Initializing module dependency graph...
78 INFO: Initializing module graph hooks...
80 INFO: Analyzing base_library.zip ...
1215 INFO: Processing pre-find module path hook   distutils
2021 INFO: running Analysis out00-Analysis.toc
2839 INFO: Caching module hooks...
2843 INFO: Analyzing D:\development\python_stuff\gtk_test.py
2911 INFO: Processing pre-safe import module hook   gi.repository.Gtk
2914 INFO: Loading module hooks...
2915 INFO: Loading module hook "hook-pydoc.py"...
2915 INFO: Loading module hook "hook-gi.repository.Gtk.py"...
3004 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
4292 INFO: Processing pre-safe import module hook   gi.repository.GObject
4294 INFO: Processing pre-safe import module hook   gi.repository.Gdk
4295 INFO: Processing pre-safe import module hook   gi.repository.Atk
4296 INFO: Loading module hook "hook-distutils.py"...
4297 INFO: Loading module hook "hook-gi.py"...
4305 INFO: Loading module hook "hook-gi.repository.Gdk.py"...
4392 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
4403 INFO: Processing pre-safe import module hook   gi.repository.cairo
4404 INFO: Processing pre-safe import module hook   gi.repository.Pango
4404 INFO: Processing pre-safe import module hook   gi.repository.Gio
4405 INFO: Processing pre-safe import module hook   gi.repository.GdkPixbuf
4405 INFO: Loading module hook "hook-xml.py"...
4562 INFO: Loading module hook "hook-encodings.py"...
4572 INFO: Loading module hook "hook-gi.repository.GObject.py"...
4660 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
4686 INFO: Processing pre-safe import module hook   gi.repository.GLib
4692 WARNING: Hidden import "gi._gobject.option" not found!
4693 INFO: Loading module hook "hook-gi.repository.Atk.py"...
4777 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
4790 INFO: Loading module hook "hook-gi.repository.cairo.py"...
4873 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
4877 INFO: Loading module hook "hook-gi.repository.Pango.py"...
4969 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
4973 INFO: Loading module hook "hook-gi.repository.Gio.py"...
5059 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
5150 INFO: Loading module hook "hook-gi.repository.GdkPixbuf.py"...
5242 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
5353 INFO: Processing pre-safe import module hook   gi.repository.GModule
5354 INFO: Loading module hook "hook-gi.repository.GModule.py"...
5440 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
5443 INFO: Loading module hook "hook-gi.repository.GLib.py"...
5529 ERROR: Unable to find gir directory: c:\python34\share\gir-1.0.
Try installing your platforms gobject-introspection package.
5706 INFO: Looking for ctypes DLLs
5711 INFO: Analyzing run-time hooks ...
5715 INFO: Including run-time hook 'pyi_rth_gtk.py'
5717 INFO: Including run-time hook 'pyi_rth_glib.py'
5718 INFO: Including run-time hook 'pyi_rth_gdkpixbuf.py'
5719 INFO: Including run-time hook 'pyi_rth_gio.py'
5719 INFO: Including run-time hook 'pyi_rth_gi.py'
5727 INFO: Looking for dynamic libraries
13268 INFO: Looking for eggs
13268 INFO: Using Python library C:\WINDOWS\system32\python34.dll
13269 INFO: Found binding redirects:
[]
13297 INFO: Warnings written to D:\development\python_stuff\build\gtk_test\warngtk_test.txt
14044 INFO: checking PYZ
14045 INFO: Building PYZ because out00-PYZ.toc is non existent
14045 INFO: Building PYZ (ZlibArchive) D:\development\python_stuff\build\gtk_test\out00-PYZ.pyz
14727 INFO: checking PKG
14727 INFO: Building PKG because out00-PKG.toc is non existent
14728 INFO: Building PKG (CArchive) out00-PKG.pkg
14783 INFO: Bootloader c:\python34\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
14783 INFO: checking EXE
14785 INFO: Building EXE because out00-EXE.toc is non existent
14785 INFO: Building EXE from out00-EXE.toc
14786 INFO: Appending archive to EXE D:\development\python_stuff\build\gtk_test\gtk_test.exe
14833 INFO: checking COLLECT
14833 INFO: Building COLLECT because out00-COLLECT.toc is non existent
14834 INFO: Building COLLECT out00-COLLECT.toc
15176 INFO: Updating manifest in C:\Users\drebbe\AppData\Roaming\pyinstaller\bincache00_py34_32bit\libgtk-3-0.dll
15177 INFO: Updating resource type 24 name 2 language 1033

D:\development\python_stuff\dist\gtk_test>gtk_test.exe
Traceback (most recent call last):
  File "gtk_test.py", line 2, in <module>
  File "site-packages\gi\__init__.py", line 100, in require_version
ValueError: Namespace Gtk not available
Failed to execute script gtk_test
```

**Comment by virtuald** [comment]
I'll probably be playing with packaging my app once again later this month, so I can look at this then. I use the all-in-one installer, so I'm sure I'll run into the same issues.

**Comment by fritjofbuettner** [comment]
I am currently using this to manually add the required typelibs in my .spec file:
```python
import os
import site

typelib_path = os.path.join(site.getsitepackages()[1], 'gnome', 'lib', 'girepository-1.0')
binaries=[(os.path.join(typelib_path, tl), 'gi_typelibs') for tl in os.listdir(typelib_path)]
```
hope this helps
---
Python 2.7.12 (anaconda)
PyGI 3.18
PyInstaller 3.3 (installed from Github)

**Comment by ic3man5** [comment]
Thank you, I'll try this out and report back.

**Comment by ic3man5** [comment]
Can confirm this works:

here is the .spec file:

```
# -*- mode: python -*-
import os
import site

typelib_path = os.path.join(site.getsitepackages()[1], 'gnome', 'lib', 'girepository-1.0')


block_cipher = None


a = Analysis(['gtk_test.py'],
             pathex=['D:\\development\\python_stuff'],
             binaries=[(os.path.join(typelib_path, tl), 'gi_typelibs') for tl in os.listdir(typelib_path)],
             datas=None,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='gtk_test',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='gtk_test')

```

And for completeness here is the python file:

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

win = Gtk.Window()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```

**Comment by Averell7** [comment]
Python 3.4
Pygi aio 3.18
Windows 7

The spec file of ic3man5 solved a part of the problems. 
I still get three Warnings : 

```
14107 INFO: Loading module hook "hook-gi.repository.GdkPixbuf.py"...
14123 WARNING: "hook-gi.repository.GdkPixbuf" ignored, since GDK not found (i.e., "gdk-pixbuf-query-loaders" not in $PATH).

39170 INFO: Loading module hook "hook-gi.repository.GObject.py"...
41158 WARNING: Hidden import "gi._gobject.option" not found!

43201 INFO: Looking for dynamic libraries
57704 WARNING: lib not found: gdiplus.dll dependency of c:\prog2\python34\Lib\site-packages\gnome\libgdk_pixbuf-2.0-0.dll

```
I am not sure they are are a problem. 

- gdk-pixbuf-query-loaders does not exist in the source
- gdiplus.dll does not exist in the source

But when I run the program (the small test program of ic3man5, I get this error : 
`gi.RepositoryError: Typelib file for namespace 'GdkPixbuf', version '2.0' not found`
Copying manually GdkPixbuf-2.0.typelib in gi_typelibs solves the problem
Then another error : `gi.RepositoryError: Typelib file for namespace 'GModule', version '2.0' not found`
Copying manually solves the problem and the program runs. 
Note that GdkPixbuf.gir and Gmodule.gir were already present in the gi-typelibs directory. 

### Poppler
But I need Poppler. So I added the following lines to gtk_test.py : 

```
gi.require_version('Poppler', '0.18')  
from gi.repository import Poppler
document = Poppler.Document.new_from_file("file:///" + "test.pdf", None)
```
The first line raises the error : **Namespace Poppler not available**

If I comment it, the third line raises the error : 
```
WARNING **: Failed to load shared library 'libpoppler-glib-8.dll' referenced by the typelib: 'libpoppler-glib-8.dll'
cifiÚ est introuvable.
Traceback (most recent call last):
  File "test111.py", line 10, in <module>
GLib.Error: g-invoke-error-quark: Could not locate poppler_document_new_from_file: 'libpoppler-glib-8.dll': Le module spécifié est introuva
Failed to execute script gtk_test
```
I have not yet found how to make pyinstaller handle the import of Poppler.

**Comment by Breakthrough** [comment]
Thanks for the fix @fritjofbuettner / @ic3man5, everything is working perfectly after modifying my .spec file.

**Comment by steelcowboy** [comment]
When I ran ic3man5's test, I got kind of confused about what the result should be. I ran `pyinstaller -F gtk-test.spec` and under the dist directory I got the gtk_test.exe and it works within that directory; however, I can't move the exe anywhere and have it work. How can I take that output and make it an installable (or at the very least standalone) application?

**Comment by Averell7** [comment]
If you want to see what I have done, the application is downloadable on SourceForge :
https://sourceforge.net/projects/pdfbooklet/files
Take the version 3 (Python 3, Gtk 3+, Pyinstaller)

I have not built a single executable, because it is slower to run and implies some modifications in the code to access local data (this is explained in Pyinstaller documentation).
I package the installation file with InnoSetup.
See the iss file attached.

[PdfBookletSetup-iss.txt](https://github.com/pyinstaller/pyinstaller/files/754348/PdfBookletSetup-iss.txt)
[pdfbooklet300.spec.txt](https://github.com/pyinstaller/pyinstaller/files/754351/pdfbooklet300.spec.txt)

**Comment by fritjofbuettner** [comment]
As a follow-up, since this issue is still open: Has anyone successfully frozen a PyGI app that uses Gstreamer-1.0?

Consider this simple script that runs a dummy pipeline and prints the steps:

```python
# gst_test.py
import time
import gi
gi.require_version('Gst', '1.0')
from gi.repository import GObject, Gst

if __name__ == '__main__':
    GObject.threads_init()
    Gst.init(None)
    Gst.debug_set_active(True)
    Gst.debug_set_default_threshold(4)
    pipeline = Gst.parse_launch("videotestsrc num-buffers=50 ! fakesink")
    print("pipeline initialized")
    pipeline.set_state(Gst.State.PLAYING)
    time.sleep(1)
    pipeline.set_state(Gst.State.PAUSED)
    time.sleep(1)
    print("DONE")
```

When freezing with PyInstaller by `pyinstaller gst_test.py`, all the Gstreamer DLL files are included and Gstreamer itself can be run. However during the `Gst.parse_launch` call, the .exe runs into segmentation fault:

```
$ dist/gst_test/gst_test.exe
WARNING: no real random source present!
0:00:00.414009511  6208 000001CA27051F30 INFO            GST_PIPELINE gstparse.c:326:gst_parse_launch_full: parsing pipeline description 'videotestsrc num-buffers=50 ! fakesink'
0:00:00.415179600  6208 000001CA27051F30 INFO     GST_ELEMENT_FACTORY gstelementfactory.c:361:gst_element_factory_create: creating element "videotestsrc"
0:00:00.416196490  6208 000001CA27051F30 INFO        GST_ELEMENT_PADS gstelement.c:670:gst_element_add_pad:<GstBaseSrc@000001CA270784E0> adding pad 'src'
0:00:00.417152176  6208 000001CA27051F30 INFO     GST_ELEMENT_FACTORY gstelementfactory.c:361:gst_element_factory_create: creating element "fakesink"
0:00:00.418061105  6208 000001CA27051F30 INFO        GST_ELEMENT_PADS gstelement.c:670:gst_element_add_pad:<GstBaseSink@000001CA2643C750> adding pad 'sink'
0:00:00.418982958  6208 000001CA27051F30 INFO     GST_ELEMENT_FACTORY gstelementfactory.c:361:gst_element_factory_create: creating element "pipeline"
0:00:00.419928381  6208 000001CA27051F30 INFO            GST_PIPELINE grammar.y:652:gst_parse_perform_link: linking some pad of GstVideoTestSrc named videotestsrc0 to some pad of GstFakeSink named fakesink0 (0/0) with caps "(NULL)"
0:00:00.420827045  6208 000001CA27051F30 INFO        GST_ELEMENT_PADS gstutils.c:1709:gst_element_link_pads_full: trying to link element videotestsrc0:(any) to element fakesink0:(any)
0:00:00.421786913  6208 000001CA27051F30 INFO                GST_PADS gstutils.c:1009:gst_pad_check_link: trying to link videotestsrc0:src and fakesink0:sink
0:00:00.422789738  6208 000001CA27051F30 INFO                GST_PADS gstutils.c:1523:prepare_link_maybe_ghosting: videotestsrc0 and fakesink0 in same bin, no need for ghost pads
0:00:00.423843121  6208 000001CA27051F30 INFO                GST_PADS gstpad.c:2316:gst_pad_link_prepare: trying to link videotestsrc0:src and fakesink0:sink
0:00:00.424735704  6208 000001CA27051F30 INFO                GST_PADS gstpad.c:2524:gst_pad_link_full: linked videotestsrc0:src and fakesink0:sink, successful
0:00:00.425610799  6208 000001CA27051F30 INFO               GST_EVENT gstevent.c:1512:gst_event_new_reconfigure: creating reconfigure event
0:00:00.426566486  6208 000001CA27051F30 INFO               GST_EVENT gstpad.c:5655:gst_pad_send_event_unchecked:<videotestsrc0:src> Received event on flushing pad. Discarding
Segmentation fault
```

I have tried `multiprocessing.freeze_support()` before importing Gst because that has solved issues with freezing a multi-process Gtk app before. But here it did not help. 
Any ideas?

---

- Windows 10 x64
- Python 3.4.5 (anaconda)
- PyGI AiO 3.24 (via [sourceforge](https://sourceforge.net/projects/pygobjectwin32/files/))
  - Gstreamer 1.12.0 with plugins

**Comment by htgoebel** [comment]
Is this still an issue? If this still is an issue please try the latest release and the latest development version.

**Comment by virtuald** [comment]
I am able to freeze and deploy a fairly complex app using Pyinstaller + Windows + msys2.

**Comment by Averell7** [comment]
Sorry, but for PdfBooklet (Gtk3 and Poppler) the last version of PyScripter is still missing necessary libraries and dlls, as indicated above : 

GdkPixbuf-2.0.typelib, 
GModule-2.0.typelib
Poppler-0.18.typelib
libpoppler-glib-8.dll
libstdc++.dll
libopenjp2.dll
liblcms2-2.dll

I didn't test each miss individually, I can do it if it is useful. But omitting the first group creates an error about missing GdkPixbuf, and omitting the second creates an error about missing Poppler.

**Comment by gpraceman** [comment]
I ran into the "Could not locate poppler_document_new_from_file: 'libpoppler-glib-8.dll'" error with Gtk3, Poppler on Windows 10, with MSYS2 and Pyinstaller 3.5.  I had to add all of the following entries to my spec file to correct it.  That is quite a lot of missed files.

Poppler-0.18.typelib
libbrotlicommon.dll
libbrotlidec.dll
liblcms2-2.dll
libcurl-4.dll
libidn2-0.dll
libnghttp2-14.dll
libnspr4.dll
libopenjp2-7.dll
libpangoft2-1.0-0.dll
libplc4.dll
libplds4.dll
libpoppler-87.dll
libpoppler-glib-8.dll
libpsl-5.dll
libunistring-2.dll            
nss3.dll
nssutil3.dll
smime3.dll

**Comment by alexdelorenzo** [comment]
> Is this still an issue? If this still is an issue please try the latest release and the latest development version.

@htgoebel This is still an issue with MinGW on Windows 10. `hello.py` from the [PyInstaller docs](https://pygobject.readthedocs.io/en/latest/getting_started.html) can successfully be built into an executable, however upon running it you get this error:

```bash
$ ./hello.exe
gi/_gi-cpython-38.dll could not be extracted!
fopen: No such file or directory
```
