### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by AFAgarap** [pyinstaller/pyinstaller#1967]
First, I'm running Windows 7 x86 on a Virtual Box environment. The specifications of the machine are as follows:
* CPU: Intel Core i5-3317U @ 1.70 GHz
* RAM: 2.00 GB
* System type: 32-bit OS

--

Now, I installed Python 3.5.1 in this OS, and also installed PyInstaller 3.1.1 through `pip install`. The problem is I could not get PyInstaller to run. I've attached some screenshots below. I tried to solve the problem by installing `pywin32`, `pypiwin32`, and `pywintypes`, but it did not help. Thank you for your kind response!

--
![deepinscreenshot20160502100037](https://cloud.githubusercontent.com/assets/11130276/14945918/f0a8b340-0fdf-11e6-998c-72c9f833e81f.png)
![deepinscreenshot20160502100120](https://cloud.githubusercontent.com/assets/11130276/14945944/3530eea6-0fe0-11e6-8e8f-0804bbeb368b.png)

**Comment by codewarrior0** [comment]
pywin32 for Python 3.5 seems to require the Visual Studio 2010 Runtime, even though Python 3.5 does not use that version of the runtime.

Try installing the [Microsoft Visual C++ 2010 Redistributable Package](https://www.microsoft.com/en-us/download/details.aspx?id=5555) and let us know if that fixes it.

**Comment by AFAgarap** [comment]
Okay, got it. Thank you. Will keep you posted!

**Comment by AFAgarap** [comment]
I did what you advised me to do, and it worked! Thank you very much! Been having this problem for more than two weeks now.

--
![deepinscreenshot20160502161644](https://cloud.githubusercontent.com/assets/11130276/14950053/5f94abae-1014-11e6-96f1-95437fdfb863.png)
