### ISSUE TITLE
Freezing a PyGi app, part 2

### ISSUE THREAD

**Issue by cinchent** [pyinstaller/pyinstaller#1968]
PyInstaller freezes simple PyGI (a.k.a. PyGObject) apps fine.  That was part 1.

A more complex PyGI app, specifically one that uses Pango, freezes ok, but fails during startup with:

  File "myapp.py", line 1682, in <module>
    pygtkcompat.enable_gtk(version='3.0')
  File "site-packages\pygtkcompat\pygtkcompat.py", line 125, in enable_gtk
  File "site-packages\gi\importer.py", line 114, in load_module
  File "site-packages\gi\module.py", line 271, in get_introspection_module
  File "site-packages\gi\module.py", line 120, in __init__
  **gi.RepositoryError: Typelib file for namespace 'PangoFT2', version '1.0' not found**

All the other imports from gi.repository load successfully, but not Pango.  The PangoFt2 version 1.0 typelib file is present in the same location as all the others, and so is its corresponding library file.

Perhaps it has to do with use of the PyGI GTK compatibility layer?  I tried eliminating all references to/usages of Pango in the source code entirely, just to see if that made any difference, and the same error occurred.  Weird.

A more-than-casual investigation into the rather Byzantine PyGI introspection mechanism, repository, and compatibility layer revealed nothing that stood out as being exceptional.  I also tried an uninstall/reinstall with the latest all-in-one installer for PyGI version 3.18.2, to no avail -- same exact error results.  Windows 7, Python 2.7.10, PyInstaller 3.2.

I understand this is almost certainly a failing of the PyGI hooks, not PyInstaller itself, but the hooking mechanism for PyGi gets very opaque very quickly.

Does someone having familiarity with these hooks -- if not the hook developer him/herself -- see this problem with Pango?  Pango with pygtkcompat?

**Comment by cinchent** [comment]
The problem is indeed linked to use of PyGI with the pygtkcompat module.

It is not just that the PangoFT2 module is a hidden dependency of Pango and that (when using the pygtkcompat layer) Pango is a hidden dependency of Gtk.  Even when PangoFT2 is declared in the 'hiddenimports' list, the problem persists.  And even explicitly importing this library in the source code causes a different problem: an ImportError on startup of the executable.

The solution is that the typelib binary file must explicitly be listed in the 'binaries' list, and indicated to be unpacked into the 'gi_typelibs' deployment subdirectory.

Providing this missing typelib reveals other missing typelibs as well.  In all, the following typelibs must be manually bundled this way:
  PangoFT2-1.0
  freetype2-2.0
  fontconfig-2.0

**Comment by Averell7** [comment]
> The solution is that the typelib binary file must explicitly be listed in the 'binaries' list, and indicated to be unpacked into the 'gi_typelibs' deployment subdirectory.

Using the solution provided in #1966, all typelibs files are listed in binaries. But only a part of them are copied in 'gi_typelibs' :  
Atk-1.0.typelib
cairo-1.0.typelib
Gdk-3.0.typelib
Gio-2.0.typelib
GLib-2.0.typelib
GObject-2.0.typelib
Gtk-3.0.typelib
Pango-1.0.typelib
