### ISSUE TITLE
PyQt5 images not loaded in Mac OS X

### ISSUE THREAD

**Issue by muammar** [pyinstaller/pyinstaller#1979]
##### What is the exact problem?

I have created a standalone application with pyinstaller to be used as systray in Mac OS X. The application works as excepted, except for the fact that the systray image is not shown. When I launch my python script from console everything works as expected. 

I have tried several options I found when searching for this problem such as: 
1. Adding data in the `Analysis` part of the spec file. 
2. Collect all files using the page of the wiki.
3. Modifying my code to look for the icons.
4. Copy the icon manually in every possible place within the `app` to see if it is loaded. 

I found that if I launch the application from `Contents > MacOS > nameofapp` the things work as expected. 

I am building using:

```
pyinstaller -i images/google.icns --windowed --onefile start_tray.py
```
##### Software versions you are using.

```
42 INFO: PyInstaller: 3.2
42 INFO: Python: 3.5.1
46 INFO: Platform: Darwin-15.4.0-x86_64-i386-64bit
```
##### A minimal example program which shows the error. Ideally this is a one-liner :-)

Sorry, I don't have a one-liner, but to reproduce this, maybe you can clone this: https://github.com/muammar/mkchromecast/tree/pyinstaller and run the command shown above. I am sure this is a very trivial problem, but I am new to pyinstaller. 

You can see the [spec file here](https://raw.githubusercontent.com/muammar/mkchromecast/pyinstaller/start_tray.spec).

Thanks in advance, and please feel free to close this report if actually the bug is me :).

**Comment by davidjamesbeck** [comment]
This conversation seems not be going anywhere, but I am having a similar problem (OS 10.13 and 10.14, Qt 5.11, PyQt5, Python 3.7). I build a -onebundle app and it runs properly except the .png splash screen and all the .png button icons are not visible; they are in the places they should be in the list directory, and the .txt files that I also include in the app are avaialbe (so it is not that things are in the wrong place).

Was there ever any resolution to this?

**Comment by davidjamesbeck** [comment]
sorry, I meant "-onefolder" not "-onebundle"

**Comment by YohannLeee** [comment]
same problem with me, if any update please @me, thanks ~

**Comment by NachoCheeseDog** [comment]
David - your problem is different from the original post.  I use the pyrcc utility provided by pyqt to turn my image files into a resource file (actually another .py python file).  All the icons work fine in my app and you avoid all the trouble you're having.

**Comment by davidjamesbeck** [comment]
Thanks, I'll give that a try. I've been using an IDE that budnles things correclty, but it is always good to be able to do things for yourself.

**Comment by BoboTiG** [comment]
Unless someone gives a minimal reproduction script, I think this issue should be closed @Legorooj.

**Comment by Legorooj** [comment]
Closing. Please open a new issue if you still encounter this problem.
