### ISSUE TITLE
Resulting exe terminates with R6034 after upgrade to pyinstaller 3.2

### ISSUE THREAD

**Issue by EberhardL** [pyinstaller/pyinstaller#1985]
# Environment
- Windows 7 / Windows Server 201R2
- pyzmq installed via pip
# Test program

 # test script to demonstrate the load error

 import os, sys

 from zmq import Context
 from zmq import Poller

 # does not get here in frozen bits when run as exe
 print 'success'
# Result for version 3.1
## D:\test>c:\Python27\Scripts\pip.exe show Pyinstaller

Metadata-Version: 2.0
Name: PyInstaller
Version: 3.1
...

D:\test>c:\python27\Scripts\pyinstaller test.py
155 INFO: PyInstaller: 3.1
155 INFO: Python: 2.7.10
155 INFO: Platform: Windows-7-6.1.7601-SP1
171 INFO: wrote D:\test\test.spec
171 INFO: UPX is not available.
187 INFO: Extending PYTHONPATH with paths
['D:\test', 'D:\test']
187 INFO: checking Analysis
187 INFO: Building Analysis because out00-Analysis.toc is non existent
187 INFO: Initializing module dependency graph...
...
4750 INFO: Appending archive to EXE D:\test\build\test\test.exe
4780 INFO: checking COLLECT
4780 INFO: Building COLLECT because out00-COLLECT.toc is non existent
4780 INFO: Building COLLECT out00-COLLECT.toc
4844 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)

D:\test>cd dist\test

D:\test\dist\test>test.exe
success
# Result for version 3.2

D:\test>c:\Python27\Scripts\pip.exe install --upgrade Pyinstaller
Collecting Pyinstaller
Requirement already up-to-date: setuptools in c:\python27\lib\site-packages (from Pyinstaller)
Requirement already up-to-date: pefile in c:\python27\lib\site-packages (from Pyinstaller)
Requirement already up-to-date: future in c:\python27\lib\site-packages (from pefile->Pyinstaller)
Installing collected packages: Pyinstaller
  Found existing installation: PyInstaller 3.1
    Uninstalling PyInstaller-3.1:
      Successfully uninstalled PyInstaller-3.1
Successfully installed Pyinstaller-3.2

D:\test>rm -rf build

D:\test>rm -rf dist

D:\test>c:\python27\Scripts\pyinstaller test.py
1157 INFO: PyInstaller: 3.2
1157 INFO: Python: 2.7.10
1157 INFO: Platform: Windows-7-6.1.7601-SP1
1157 INFO: wrote D:\test\test.spec
1157 INFO: UPX is not available.
1171 INFO: Extending PYTHONPATH with paths
...
23657 INFO: Appending archive to EXE D:\test\build\test\test.exe
23687 INFO: checking COLLECT
23687 INFO: Building COLLECT because out00-COLLECT.toc is non existent
23687 INFO: Building COLLECT out00-COLLECT.toc
23734 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 6161)

D:\test>cd dist\test
D:\test\dist\test>test

Message Box "Runtime Error!  Program: D:\test\dist\test\test.exe  R6034 An application has made an attempt to load the C Runtime library incorrectly."

After pressing OK:

Traceback (most recent call last):
  File "test.py", line 5, in <module>
  File "c:\users\leba\appdata\local\temp\pip-build-2suog9\Pyinstaller\PyInstaller\loader\pyimod03_importers.py", line 38
9, in load_module
  File "site-packages\zmq__init__.py", line 42, in <module>
  File "ctypes__init__.py", line 443, in LoadLibrary
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 131, in **init**
  File "ctypes__init__.py", line 365, in **init**
WindowsError: [Error 1114] Eine DLL-Initialisierungsroutine ist fehlgeschlagen
Failed to execute script test
# Additional Hints

I ran the code in the pdb and it tries to load libsodium.pyd. 
os.path.exists() for the variable that is used to load the lib returns True.

The directory:

D:\test\dist\test>dir
 Datenträger in Laufwerk D: ist work
 Volumeseriennummer: 1400-7000

 Verzeichnis von D:\test\dist\test

11.05.2016  16:17    <DIR>          .
11.05.2016  16:17    <DIR>          ..
11.05.2016  15:43            68.608 bz2.pyd
11.05.2016  15:43           485.888 libsodium.pyd
11.05.2016  16:17             1.050 Microsoft.VC90.CRT.manifest
11.05.2016  15:43           225.280 msvcm90.dll
11.05.2016  15:43           569.680 msvcp90.dll
11.05.2016  15:43           653.136 msvcr90.dll
11.05.2016  15:43           127.488 pyexpat.pyd
11.05.2016  15:43         2.460.160 python27.dll
11.05.2016  15:43           110.080 pywintypes27.dll
11.05.2016  15:43            10.240 select.pyd
11.05.2016  16:17         1.108.617 test.exe
11.05.2016  16:17             1.008 test.exe.manifest
11.05.2016  15:43           686.080 unicodedata.pyd
11.05.2016  15:43           100.352 win32api.pyd
11.05.2016  15:43            24.064 win32pipe.pyd
11.05.2016  16:17    <DIR>          zmq
11.05.2016  15:43            39.424 zmq.backend.cython.constants.pyd
11.05.2016  15:43            32.768 zmq.backend.cython.context.pyd
11.05.2016  15:43            13.312 zmq.backend.cython.error.pyd
11.05.2016  15:43            45.568 zmq.backend.cython.message.pyd
11.05.2016  15:43            77.824 zmq.backend.cython.socket.pyd
11.05.2016  15:43            22.016 zmq.backend.cython.utils.pyd
11.05.2016  15:43            26.112 zmq.backend.cython._device.pyd
11.05.2016  15:43            30.208 zmq.backend.cython._poll.pyd
11.05.2016  15:43            11.264 zmq.backend.cython._version.pyd
11.05.2016  15:43            88.064 _ctypes.pyd
11.05.2016  15:43           910.336 _hashlib.pyd
11.05.2016  15:43            46.080 _socket.pyd
11.05.2016  15:43         1.315.328 _ssl.pyd
              28 Datei(en),      9.290.035 Bytes
               3 Verzeichnis(se), 42.258.952.192 Bytes frei

D:\test\dist\test>dir zmq
 Datenträger in Laufwerk D: ist work
 Volumeseriennummer: 1400-7000

 Verzeichnis von D:\test\dist\test\zmq

11.05.2016  16:17    <DIR>          .
11.05.2016  16:17    <DIR>          ..
11.05.2016  15:43           485.888 libsodium.pyd
11.05.2016  15:43           310.784 libzmq.pyd
               2 Datei(en),        796.672 Bytes
               2 Verzeichnis(se), 42.258.952.192 Bytes frei

**Comment by aldefalco** [comment]
I have the same problem when I try to build a twisted application. On 3.1.1 it works very well but on 3.2 it shows same winerror message box.

**Comment by stephenrauch** [comment]
I was able to duplicate this with 3.2 and with master branch, but it appears to be fixed on the tip of develop branch.

**Comment by xiaocaiyidie** [comment]
thanks
