### ISSUE TITLE
How to pull in libraries from custom QT build?

### ISSUE THREAD

**Issue by aalexei** [pyinstaller/pyinstaller#1988]
Hi, I'm trying to bundle a PyQt app on OSX that should use a customised QT build but I cannot get pyinstaller to find the QT libs, so after building and running I get:

```
Failed to execute script pyi_rth_qt5plugins
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py", line 46, in <module>
  File "/Users/alexei/projects/nexus/py3qt5/env/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
ImportError: dlopen(/Users/alexei/projects/nexus/py3qt5/pyinstaller/dist/Nexus.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so, 2): Library not loaded: @loader_path/QtCore
  Referenced from: /Users/alexei/projects/nexus/py3qt5/pyinstaller/dist/Nexus.app/Contents/MacOS/PyQt5.QtCore.cpython-35m-darwin.so
  Reason: image not found
```

I'm running a clean install of PyInstaller-3.2. Python 3.5 in a pyenv, OsX 10.11.4, and QT 5.6.0. 

Oddly out00-Analysis.toc lists about half the python modules from the env and half from the homebrew python3.5 on the system (which was used to generate the virtual env). Is this normal?

While pyinstaller is finding the PyQt libs in the env it seems to be failing to find the QT libs in  /usr/local/Qt-5.6.0/ , so I get stuff like 

`3170 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/Qt-5.6.0/plugins/imageformats/libqico.dylib)`

How do I feed in the location of all these libraries?

**Comment by danauerbach** [comment]
Try the current Dev version of PyInstaller. There was a patch merged in just after 3.2 that fixed some qt lib problems. I am successfully packaging a PyQt5 app that uses a custom (from source) build of Qt v 5.6.

**Comment by danauerbach** [comment]
I believe the patch that (hooefully) fixes your problem was #1965.

**Comment by aalexei** [comment]
Yes! That fixes finding the QT libs and I can see them appearing in my dist folders, many thanks for that.

The app still doesn't run though and dies without any useful debug info. In the `build/nexus/warnnexus.txt` file there are a ton of missing modules:

```
missing module named PyQt5.QtCore.QCoreApplication - imported by PyQt5.QtCore, /Users/alexei/projects/nexus/py3qt5/env/lib/python3.5/site-packages/PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py
missing module named 'PyQt5.sip' - imported by /Users/alexei/projects/nexus/py3qt5/env/lib/python3.5/site-packages/PyInstaller/loader/rthooks/pyi_rth_qt5plugins.py
missing module named _datetime.__doc__ - imported by _datetime, datetime, /Users/alexei/projects/nexus/py3qt5/nexus.py
missing module named _operator.__doc__ - imported by _operator, operator, /Users/alexei/projects/nexus/py3qt5/nexus.py
missing module named _heapq._heapreplace_max - imported by _heapq, heapq, /Users/alexei/projects/nexus/py3qt5/nexus.py
```

Could this be an issue with using a virtual env?

(App runs fine when source executed with python from virtual env from command line)

**Comment by aalexei** [comment]
The above warnings are probably fine as previous successful builds have similar warnings about missing modules but the apps run fine.

So, have no clue as to why the built app dies.

**Comment by danauerbach** [comment]
Not sure about those specifically. But, if it's sip related, and if you haven't installed sip from here: https://riverbankcomputing.com/software/sip/intro, I suggest you download, build locally and install. Process similar the PyQt builds/install. Uninstall any other sip installed by pip first. Then build/install this new sip. This should be done **before** building/installing PyQt, so you may have to rebuild/install PyQt.

Not sure this is the **only** way to make it work, but it works for me. FYI: I am using conda/miniconda virtual environments.


Good luck!

**Comment by bjones1** [comment]
I'm closing this, since #3233 should fix it -- see the [instructions](https://github.com/pyinstaller/pyinstaller/pull/3233#issuecomment-362094587) there.
