### ISSUE TITLE
Built application crashes on launch in Windows 10

### ISSUE THREAD

**Issue by JPLeBreton** [pyinstaller/pyinstaller#1998]
I have an application that builds and runs in Windows 7 and XP with Python 3.4.4 (32 and 64 bit in Win7). The same application builds, but does not run, in Windows 10. Here's the error I get when I run in Win10:

`Traceback (most recent call last):`
`File "playscii.py", line 12, in <module>`
`File "platform.py", line 1083, in system`
`File "platform.py", line 978, in uname`
`File "platform.py", line 559, in win32_ver`
`File "platform.py", line 515, in _get_real_winver`
`File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 152, in __init__`
`File "ctypes\__init__.py", line 351, in __init__`
`OSError: [WinError 126] The specified module could not be found`
`Failed to execute script playscii`

I tried all the suggestions on the "if things go wrong" wiki page, including disabling UPX and packaging with --onedir and running the latest dev version of PyInstaller, none of which changed the problem.

Given that the program runs perfectly in other versions of Windows (and, more incidentally, the Mac .app bundle I create with PyInstaller as well) it appears that everything it requires is getting packaged properly.

I tried creating a minimal program that imports the same modules and then simply prints something, and it _did_ run in Win10, so I'm not really sure what to investigate next.

Here's more info that might be relevant:

PyInstaller build log: https://gist.github.com/JPLeBreton/1ccf79d95337e4d2041b27c2cf34a644

Packages installed on the build system:
`
appdirs (1.4.0)
future (0.15.2)
numpy (1.11.0)
pefile (2016.3.28)
Pillow (3.2.0)
pip (8.1.2)
PyInstaller (3.2)
PyOpenGL (3.1.0)
pypiwin32 (219)
PySDL2 (0.9.3)
setuptools (18.2)
`

Here's the program's main script:
https://bitbucket.org/JPLeBreton/playscii/src/default/playscii.py?fileviewer=file-view-default

and here's its PyInstaller spec:
https://bitbucket.org/JPLeBreton/playscii/src/default/playscii_win.spec?fileviewer=file-view-default

**Comment by htgoebel** [comment]
> File "platform.py", line 515, in _get_real_winver
> File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 152, in __init__
> File "ctypes\__init__.py", line 351, in __init__
> OSError: [WinError 126] The specified module could not be found

This message it quite clear, isn't it? cytpes fails to find the DLL which ["platform.py", line 515](https://hg.python.org/cpython/file/v3.4.4/Lib/platform.py#l515) tries to import.And iy you lokk at ["platform.py", line 515](https://hg.python.org/cpython/file/v3.4.4/Lib/platform.py#l515), you'll see that the DLL in question is "version.dll".

**Comment by JPLeBreton** [comment]
How did you determine that filename, and where could I find it? I see `version = WinDLL('version')` on line 515 there; I ran across that in my initial troubleshooting for this and didn't know what to make of it. I can't find a file named `platform.dll` anywhere on my system.

Is there any explanation for why a minimal program that has the same line as line 12 from my program would build and work?

**Comment by JPLeBreton** [comment]
Ahh, I see now; I don't think I understood the implications of ctypes.WinDLL('version') there.

I was able to fix this by adding this to my spec's include_bins list:
  `(winreg.ExpandEnvironmentStrings('%WINDIR%') + '\\system32\\version.dll', '.')`
but that seems inelegant in the extreme... is there a better way?

Interestingly, builds of this application I made last October didn't exhibit this problem (not working in Win10), but I've no idea what could have changed since then.

**Comment by codewarrior0** [comment]
That's not just inelegant, it's a bit dangerous. We don't include the Windows system DLLs specifically to avoid problems related to version mismatches between those DLLs and the surrounding system. I believe the `version.dll` will be present on any version of Windows.

One thing I know that changed since October is the Fall Update to Windows 10 (aka Threshold 2) but I doubt that would have removed `version.dll` - it exports functions related to getting info from a file's version resources.

> I tried creating a minimal program that imports the same modules and then simply prints something, and it did run in Win10, so I'm not really sure what to investigate next.

Did the minimal program call `platform.system()`?

**Comment by JPLeBreton** [comment]
Yes, I made a minimal program that was simply `import platform; print(platform.system())` and a slightly more involved one that did all the same imports as my application. Both built and ran in Windows 10.

**Comment by htgoebel** [comment]
So this ticket can be closed?

**Comment by JPLeBreton** [comment]
No, my application still doesn't run in Win10 and I'd like to understand how to fix that. Is there any reason one built application wouldn't be able to find / access version.dll functionality in Windows\system32\ and another would?

**Comment by codewarrior0** [comment]
I'm not sure, but here's a guess. If you have `c:\windows\syswow64` in your PATH environment variable, this will cause `ctypes` to use an incorrect search order when looking for DLLs - it may load the 32-bit version of the DLL when the Python process is 64-bit. It isn't needed to have that particular folder in your PATH, since any LoadLibrary calls done to a DLL under `c:\windows\system32` by a 32-bit process will automatically be redirected by Windows to `syswow64` (which is where it keeps the 32-bit DLLs... long story).

**Comment by JPLeBreton** [comment]
Hm, interesting. Is this on the machine building the application, or on the machine running the built application? I actually have been building with 32-bit Python (3.4) in an old Windows XP VM, which of course doesn't have any 64 bit stuff. The Win10 install I'm testing the build on is 64-bit though.

**Comment by JPLeBreton** [comment]
Just checked back on this, I do not have `c:\windows\syswow64` in my PATH environment variable.

**Comment by JPLeBreton** [comment]
This issue is still happening for me, with latest (3.2.1), as described in the first post. Any reports since then of applications built on a 32-bit Windows system crashing on a 64-bit one?

**Comment by haiyangdeperci** [comment]
I am having the exact same problem and I don't a see a solution here.

**Comment by htgoebel** [comment]
Please try v3.4 and the most current development version.
Several month old, so I'm closing this for now.
