### ISSUE TITLE
pyinstaller works on powerpc linux, big endian arch

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#2000]
Not a bug, just some feedback:

I was curious whether pyinstaller would work on this nowadays rather exotic (and big endian) arch.

So I built pyinstaller (3.2+ develop branch checkout) and made a single-file binary for borgbackup with it - under qemu-ppc and debian linux powerpc. It works!

When building the bootloader, one needs to use `python ./waf --no-lsb all`.

**Comment by codewarrior0** [comment]
That's awesome. Though I can't say I'm surprised, as I remember seeing the occasional `ntohl()` call and endian markers in `struct.pack` format strings. Then again, that may have nothing to do with it.

I'd hate to close this with no action, so I'll just add "PowerPC Linux" to the unsupported-yet-somehow-working platforms list in the readme.

**Comment by htgoebel** [comment]
@TW: Really awesome. And awesome to see which platforms you are bringing borgbackup on :-) Thanks for reporting this.
