### ISSUE TITLE
Bug Issues with Local Install on Linux

### ISSUE THREAD

**Issue by Alexhuszagh** [pyinstaller/pyinstaller#2001]
So I've tried both standard installs (both local and global via pip), as well as straight from the download directory.

I keep on getting the following traceback:

```
Traceback (most recent call last):
  File "pyinstaller.py", line 15, in <module>
    run()
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/building/api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/building/api.py", line 189, in __init__
    self.__postinit__()
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/building/datastruct.py", line 178, in __postinit__
    self.assemble()
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/building/api.py", line 274, in assemble
    pylib_name=pylib_name)
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/archive/writers.py", line 329, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/archive/writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/archive/writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "/home/alex/Downloads/PyInstaller-3.2/PyInstaller/archive/writers.py", line 376, in add
    fh = open(pathnm, 'rb')
IOError: [Errno 13] Permission denied: '/usr/local/share/icons/hicolor/22x22/apps/caffeine.png'
```

My current install is Ubuntu 16.04. This is using the stable 3.2 branch of PyInstaller, on Python2.7 (standard Ubuntu install).

This "technically" fixes the issue:
`for f in /usr/local/share/icons/*/*/*/*.png; do sudo chmod 777 $f; done`
`for f in /usr/local/share/icons/*/*/*/*.svg; do sudo chmod 777 $f; done`

However, changing user permissions (especially so globally) seems to be questionable. Furthermore, by default root has rw and user has r permissions.

**Comment by codewarrior0** [comment]
This doesn't sound like a problem with PyInstaller. The first thing you should find out is, if your app runs fine in the Python interpreter, why can your app access those files normally but PyInstaller cannot access them to copy them? Are you running your app and PyInstaller as different users?

**Comment by Alexhuszagh** [comment]
My app makes no attempt to use any of those icons. I supply my own icon set which is provided as a.datas and has no correlation with that icon set. 

I am also running my app and PyInstaller as the same user. (The errors, and the inclusion of those icons made no sense to me whatsoever). The only thing I can mention is I likely do not have a clean PyInstaller directory: I've sampled PyInstaller 3, used PyInstaller 2, done local installs, pip installs, setup.py installs from source.

My install script looks something like this:

`
BINARIES = [('llvmlite/binding/libllvmlite.so', '/usr/lib/python2.7/site-packages/llvmlite/binding/libllvmlite.so', 'BINARY')]
DATAS = [('pkg/resources/png/icon.png', '/home/alex/git/pkg/resources/png/icon.png', 'DATA')]

a = Analysis(['myscript.py'],
             pathex=['.'],
             binaries=None,
             datas=None,
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)


pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)


exe = EXE(pyz,
          a.scripts,
          a.binaries+BINARIES,
          a.zipfiles,
          a.datas+DATAS,
          name='myscript',
          debug=False,
          strip=False,
          upx=True,
          console=True )
`

a.datas contains nothing of importance here, just the default:

`
[('lib/python2.7/config-x86_64-linux-gnu/Makefile', '/usr/lib/python2.7/config-x86_64-linux-gnu/Makefile', 'DATA'), ('local/include/python2.7/pyconfig.h', '/home/alex/git/virtualenvs/all/local/include/python2.7/pyconfig.h', 'DATA')]
`

**Comment by htgoebel** [comment]
I support codewarrior: This seams not to be a PyInstaller problem. The `caffeine.png` file is *read*, and normally  all files in `/usr/local/share/` should be world-readable. For me this looks more like whatever did install these icons into `/usr/local/` is buggy.

Anyway, If you want to find out, why this image-file is included, you need to debug the `toc`s in `PYZ.assemble()`, as this is which "heading" the call-stack of the failures (PyInstaller/building/api.py", line 274, in assemble).

**Comment by Alexhuszagh** [comment]
Weird, explicitly setting the permissions to 640 rather than their defaults does fix the issue, despite the fact that the icons with issues were originally showing the following using ls -l

```
ls -l /usr/local/share/icons/hicolor/22x22/apps/caffeine.png
-rw-r----- 1 root root 1411 Apr 14  2013 /usr/local/share/icons/hicolor/22x22/apps/caffeine.png
```

This makes me feel it has nothing to do with PyInstaller as well, I'll look into debugging PYZ.assemble() but that seems to confirm it's nothing on your end. Thanks for the excellent program as well, PyInstaller is wonderful.
