### ISSUE TITLE
In the sandbox of os x,My application will call the XPC service that contain one executable file generated by Pyinstaller .But i was told I need code-sign my "Python" file. 

### ISSUE THREAD

**Issue by houlin** [pyinstaller/pyinstaller#2008]
**In the sandbox of os x,My application will call the XPC service that contain one executable file generated by Pyinstaller .But i was told I need code-sign my "Python" file. But how can i get the Python file . It 's in the single executable file .Can I specify one signed "Python file" when I generate the single executable file? Below is the error :**

_`kernel[0]: CODE SIGNING: process 32173
 [obfsproxy-xpc-se]: rejecting invalid page at address 0x107be7000 from offset 0x1000 in file     "/private/var/folders/nt/j_7h77js7bsfvhw4s44k7cf40000gn/T/com.houlin.obfsproxy-xpc-   server/_MEINzOiO6/Python"
 (cs_mtime:1464339917.0 == mtime:1464339917.0) (signed:1 validated:1 tainted:1 wpmapped:0   slid:0)
`_

**Comment by houlin** [comment]
**Now I have code-sign the file** ("/private/var/folders/nt/j_7h77js7bsfvhw4s44k7cf40000gn/T/com.houlin.obfsproxy-xpc- server/_MEINzOiO6/Python") using below code:
`codesign -f -s  "3rd Party Mac Developer Application: lin hou (KF34Q87E4G)"  --entitlements  /Users/houlin/workspace1/vpn_master/obfsproxy-xpc-service/obfsproxy-xpc-service.entitlements   
***/***/Python`
**but,I still get the error below :**
`16/5/28 下午6:47:42.000 kernel[0]: CODE SIGNING: process 29381[obfsproxy-xpc-se]: rejecting invalid page at address 0x108249000 from offset 0x1000 in file "/private/var/folders/nt/j_7h77js7bsfvhw4s44k7cf40000gn/T/com.houlin.obfsproxy-xpc-server/_MEI4o6uYx/Python" (cs_mtime:1464432462.0 == mtime:1464432462.0) (signed:1 validated:1 tainted:1 wpmapped:0 slid:0)
16/5/28 下午9:26:45.060 com.apple.xpc.launchd[1]: (com.houlin.obfsproxy-xpc-server[29702]) Binary is improperly signed.
`

**Comment by houlin** [comment]
[here](http://stackoverflow.com/questions/37481464/code-signing-of-a-pyinstaller-generated-executable-on-macos-x-not-honored) a link from stackoverflow

**Comment by springermac** [comment]
Please see https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing for information on signing a Mac OS X app built with PyInstaller.

**Comment by htgoebel** [comment]
Now news since 1 1/4 years. Assume this is solved.
