### ISSUE TITLE
Receive error that msvcr100.dll cannot be found

### ISSUE THREAD

**Issue by diggity801** [pyinstaller/pyinstaller#2012]
Python version: 3.4.4
PyInstaller: 3.2
Os Version: Windows 10 and Windows 8 and Windows 7 and Windows XP and Windows Vista.

Unable to run program on Windows XP even though it worked moments earlier tonight when packaged  as one file. It states that it failed to execute script.

I just updated to the latest build of PyInstaller

**Comment by AndCycle** [comment]
when building with directory, the msvcr100.dll do exist,

for some reason as one file it failed to read msvcr100.dll.

**Comment by AndCycle** [comment]
https://github.com/pyinstaller/pyinstaller/issues/1974
oops, related? gonna look into it later.

**Comment by diggity801** [comment]
I updated to the latest build using the dev zip posted in the help yourself links and it works now. It not only works now but AVG doesn't detect the builds as trojans any more. Hooray!

**Comment by AndCycle** [comment]
@diggity801 I think you can safely close this one as it been fixed in develop branch
