### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by quieromicubita** [pyinstaller/pyinstaller#2015]
After I get the .exe with Pyinstaller I try to run the application and it pops this message 'Failed to execute script'.

The application runs 'correctly' if I comment the following line of code:

`# i_path = ipath[count]`

The line above is within a for loop to store paths for 10 images which are button icons added dynamically:
```
for i in range(len(pos)):
            if i == 0:
                grid.addWidget(self.edit, 0, 3)
            elif i >= 4 and i <= 15:
                count = i-4
                button = QtGui.QPushButton()
                button.setObjectName(self.key_names[count])
                # i_path = ipath[count]
                # icon = QtGui.QIcon(i_path)
                # icon.setThemeName(i_path)
                # button.setIcon(icon)
                # button.setIconSize(QtCore.QSize(70,70))
                grid.addWidget(button, pos[i][0], pos[i][1])
                button.clicked.connect(self.buttonClick)
            (code continues with other elif)
```
The error occurs when running the application. There isn´t any error message when running Pyinstaller.

The application runs correctly without building the exe, by just running the .py file it shows the app exactly as desired.

Pyinstaller: 3.3.dev0+8756735
Python 2.7.10
Platform: Windows -7-6.1.7601-SP1

Building with the following commands: --onefile --noupx --windowed --icon=entercodescreen.ico entercodescreen.py

The warning file in the 'build' directory has a long list of missing modules but I don´t know how to interpret warnings yet.

**Comment by codewarrior0** [comment]
Build the app without --windowed and run it from a command prompt to get the full error output.

**Comment by quieromicubita** [comment]
Thanks for a quick answer. I got this message:

C:\Python27\My Projects\Pos\dist>entercodescreen.exe
Traceback (most recent call last):
  File "entercodescreen.py", line 115, in <module>
  File "entercodescreen.py", line 109, in main
  File "entercodescreen.py", line 14, in __init__
  File "entercodescreen.py", line 56, in initUI
IndexError: list index out of range
Failed to execute script entercodescreen

Now, why does the .py file run correctly then?

**Comment by codewarrior0** [comment]
I don't know. You'll have to do some debugging on your own and find out why `ipath` isn't getting set correctly when frozen. Maybe it's being set using a list of data files that are in your source folder but aren't in the frozen app. 

To add data files to the frozen app, see http://pyinstaller.readthedocs.io/en/latest/spec-files.html#adding-files-to-the-bundle

**Comment by quieromicubita** [comment]
You're right. I built without --onefile and I can´t see the dir where I have the images. I´ll check the link you suggested to see how to include the images directory.

Thanks.

**Comment by htgoebel** [comment]
I take this as "solved".

**Comment by quieromicubita** [comment]
Solved indeed. Thanks a lot. I looked at the link you suggested and ended up learning about how to change the .spec script and how to add files and directories. Now the bundled app runs 100% !! In fact, I´ll call my 'own' .spec scripts from now on.

**Comment by ebadali** [comment]
@quieromicubita can you share your .spec file ?

**Comment by LipillaiDave** [comment]
+1 share

**Comment by Sashkiv** [comment]
@LipillaiDave @ebadali Problem solved with run .spec script (pyinstaller main.spec)
My spec script is:

```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['e:\\myapp'],
             binaries=[],
             datas=[('e:\\myapp\\templates\\main.glade', 'templates')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz, a.scripts, exclude_binaries=True,
          name='Title of app', debug=False, strip=False,
          upx=True, console=False)

coll = COLLECT(exe, a.binaries, a.zipfiles, a.datas,
               strip=False, upx=True, name='myapp')

```

**Comment by aksbju** [comment]
get all libraries used in the script from Lib\site-packages to your application directory
will work
