### ISSUE TITLE
Ambiguous Phrase on the Homepage

### ISSUE THREAD

**Issue by matumaros** [pyinstaller/pyinstaller#2016]
On http://www.pyinstaller.org/ under Features - Flexible packaging mode, the 3 points seem like they say "You can package it into one folder, one executable or you can completely customize how it's packaging it". I spent hours trying to find how to customize it, until somebody in the IRC told me that is not what it means.

**Comment by codewarrior0** [comment]
I suppose it's trying to say that you can run `pyinstaller myapp.py --onefile`, or `pyinstaller myapp.py --onedir`, or `pyinstaller myapp.spec`. The first two use default packaging settings, but the third one uses the settings in the spec file which have a much greater degree of freedom.

**Comment by Legorooj** [comment]
Closing because it isn't a bug
