### ISSUE TITLE
Remove auto-generated usage in manual

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2020]
In #1990 @tallforasmurf wrote:

> However, this calls into question the use of --help to automatically generate that piece of the documentation. […]
> Well, I have been doubtful about this technique for some time. Yes, it automatically ensures that the doc will match the code, and that the option summary only needs to be edited in one place. However it makes it impossible to reformat the option summary, or edit it in any way, or use a cross-reference from the option summary to a discussion, or from a discussion back to a particular option.

So: Should be remove the automatically generated pieces of documentation??

**Comment by tallforasmurf** [comment]
I'm the only one to express a worry. In the particular case of the add-files option, I had imagined that the help text would be different on different platforms. However, @linusg-github put both options in the text, so that is not an issue.
So, on balance, I say let it stand.

**Comment by bjones1** [comment]
And, on a side note, I'm very excited about the ability to specify the text in one place and then having it appear both in the manual and in the help text. @htgoebel, that was very nicely done. DRY is the way to go with this as with anything.

**Comment by htgoebel** [comment]
So we'll keep the automatically generated pieces.
