### ISSUE TITLE
_tkinter.TclError: couldn't open "image.png": no such file or directory

### ISSUE THREAD

**Issue by laykatz** [pyinstaller/pyinstaller#2038]
Hi everyone, pyinstaller is not allowing me to convert my python app into an executable with an  image which is in  png format, is there a way to allow this I did some research I couldn't find anything about how to accomplish this.   
The code holding the image looks like so, and the image is in the folder with the .py file
```
# Variable holding the image
photo = PhotoImage(file="image.png")
# Invoke the image and displays it on the main window
label = Label(window, image=photo)
label.pack()
```
but when it program builds I get this error, I don't get this error if I comment out everything about the image, and the program works beautifully. But I would like to add this image as the background of my application. Is there anyway this can be done? Thanks in advance.
```
  File "test.py", line 49, in <module>
  File "tkinter\__init__.py", line 3384, in __init__
  File "tkinter\__init__.py", line 3340, in __init__
_tkinter.TclError: couldn't open "image.png": no such file or directory
```

**Comment by htgoebel** [comment]
You have to tell PyInstaller to bundle the image. See http://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle and https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged

**Comment by InanisV** [comment]
So is there any solution? I have the same problem.
I place the .png file in the output directory, however, the program says no such file or directory.
