### ISSUE TITLE
Error in icon.py loading icon

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#2039]
Using the latest (3.3.dev0+91b5311) and also the latest build of pywin (pywin32-220) I attempt to bundle an app under Windows 7 32bit. If I do not include an `icon=Marvin.icns` in the spec file, it completes successfully. When I do specify an icon file, it terminates with the following traceback (edited)

```
11715 INFO: Updating icons from Marvin.icns to C:\Users\dcortesi\AppData\Local\Temp\tmptmb08932
Traceback (most recent call last):
...
File "C:\Python34\lib\site-packages\pyinstaller-3.3.dev0+91b5311-py3.4.egg\PyInstaller\utils\win32\icon.py", line 172, in CopyIcons
hsrc = win32api.LoadLibraryEx(srcpath, 0, LOAD_LIBRARY_AS_DATAFILE)
pywintypes.error: (193, 'LoadLibraryEx', '%1 is not a valid Win32 application.')
```

I believe I bundled the same app successfully using an earlier version, perhaps 3.0?

Possibly related to issue #1347?

**Comment by codewarrior0** [comment]
Isn't ".icns" the file extension for Mac OS X icons? Windows icons use ".ico" AFAIK.

**Comment by tallforasmurf** [comment]
You are correct, it should refer to Marvin.ico, and when it does, the build completes.
So I am going to leave this open but flag it "Low" because all that should change is to put that call to win32api.LoadLibraryEx() in a try/except block and issue a decent warning instead of crashing.

**Comment by yagman** [comment]
I have used ".ico" in windows 7 64bit and it crashed! How did you fix that?

more info this in issue #2445

**Comment by htgoebel** [comment]
@tallforasmurf Can you please submit a pull-request?! I don't have a window machine at hand to develop it, esp. fetching the correct base-exception and printing the message. Thanks.

**Comment by tallforasmurf** [comment]
Oh my, so long ago. I will see if I can recreate this.

**Comment by htgoebel** [comment]
Should be easy, Simply pass `--icon` with some PDF file :-)

**Comment by htgoebel** [comment]
Already fixed sinde 2 years :-)
