### ISSUE TITLE
pyinstaller windows executables can't run from System32 folder in 64 bit windows

### ISSUE THREAD

**Issue by ohadcn** [pyinstaller/pyinstaller#2046]
compile an executable using pyinstaller on windows (use `onefile` directive, don't pollute system folders), copy the executable file to c:\windows\system32\ on a 64 bit windows machine and run the executable.
the run ends with error `Cannot open self C:\Windows\system32\hello.exe or archive C:\Windows\system32\hello.pkg`

after coping the file to c:\windows\SysWow64\ folder, it can run from System32 folder too, I guess that Wow64FsRedrection made the OS look for the archive in SysWow64 folder instead of in System32 folder.

**Comment by codewarrior0** [comment]
> I guess that Wow64FsRedrection made the OS look for the archive in SysWow64 folder instead of in System32 folder.

You seem to have a complete understanding of the issue.

Just don't put a 32-bit executable in the c:\windows\system32\ folder.
