### ISSUE TITLE
struct.error while building with icon on Windows

### ISSUE THREAD

**Issue by sabian2008** [pyinstaller/pyinstaller#2051]
Today I tried to build an EXE with pyinstaller (no news here) but when I tried to add an icon (which is the first time I've done so), I'm getting an error which complete output I paste below:

```
E:\Element Tester>pyinstaller -F tester.py --icon tester.ico
110 INFO: PyInstaller: 3.3.dev0+d25657e
140 INFO: Python: 3.4.3
140 INFO: Platform: Windows-7-6.1.7601-SP1
190 INFO: wrote E:\Element Tester\tester.spec
220 INFO: UPX is not available.
310 INFO: Extending PYTHONPATH with paths
['E:\\Element Tester', 'E:\\Element Tester']
310 INFO: checking Analysis
410 INFO: checking PYZ
781 INFO: checking PKG
871 INFO: Building because c:\python34\lib\site-packages\PyInstaller\loader\pyim
od01_os_path.pyc changed
871 INFO: Building PKG (CArchive) out00-PKG.pkg
20579 INFO: Bootloader c:\python34\lib\site-packages\PyInstaller\bootloader\Wind
ows-32bit\run.exe
20579 INFO: checking EXE
20579 INFO: Building EXE because out00-EXE.toc is non existent
20579 INFO: Building EXE from out00-EXE.toc
20579 INFO: SRCPATH [('tester.ico', None)]
20579 INFO: Updating icons from ['tester.ico'] to C:\Users\IEUser\AppData\Local\
Temp\tmpx7vtwjgu
Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.3.dev0+d25657e', 'console_scripts', 'pyinst
aller')()
  File "c:\python34\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_
build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python34\lib\site-packages\PyInstaller\building\build_main.py", line
788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "c:\python34\lib\site-packages\PyInstaller\building\build_main.py", line
734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "c:\python34\lib\site-packages\PyInstaller\building\api.py", line 407, in
 __init__
    self.__postinit__()
  File "c:\python34\lib\site-packages\PyInstaller\building\datastruct.py", line
161, in __postinit__
    self.assemble()
  File "c:\python34\lib\site-packages\PyInstaller\building\api.py", line 494, in
 assemble
    icon.CopyIcons(tmpnm, self.icon)
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 165
, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 122
, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 93,
 in __init__
    entry.fromfile(file)
  File "c:\python34\lib\site-packages\PyInstaller\utils\win32\icon.py", line 63,
 in fromfile
    self._fields_ = list(struct.unpack(self._format_, data))
struct.error: unpack requires a bytes object of length 16
```

First I tried adding the icon in the spec file directly but then, thinking I might have missed the syntax, I used the command in the above text. The result in both cases was the same. As searching the internet didn't provide anything useful, and after several tests and a few hours, I decided to bring it here. I think I must be doing something wrong, but I've been unable to find any documentation pointing me in the right direction.

I don't know which useful details might be missing. The error appears both in the stable version and in the development version. I'm using a virtualized Windows, from the ["official development images"](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/linux/) and never had a problem before.

Excuse me if I did wrong reporting this and thank you for your time.

Cheers

P.S: The error doesn't appear while building (with same spec file or command) in both linux32 and linux64. However this is expected behaviour, as in linux the icon flag is ignored.

P.S2: I found one reference [here](http://www.lawebdelprogramador.com/foros/Python/1543566-struct.error-al-crear-exe-con-pyinstaller.html) but it wasn't useful

**Comment by sabian2008** [comment]
Sorry for bumping, but just in case this has gone unnoticed.

**Comment by yagman** [comment]
why was this closed without an answer?! I am having the same issue with pyinstaller 3.2.1

**Comment by sabian2008** [comment]
I've just realized I never updated this issue.

Several months later (I could do without icons) I realized I had grabbed an image and manually added .ico as extension. This was really silly of me, as five minutes of Internet searching revealed that .ico files had special metadata. I downloaded an "ico converter" and problem solved.

I apologize for the inconvenience.

Cheers,
