### ISSUE TITLE
Having trouble running pyi-grab_version

### ISSUE THREAD

**Issue by jakirkham** [pyinstaller/pyinstaller#2052]
Built and am trying to run PyInstaller on Mac, but it does not seems to be working. It appears to be looking to import `pywintypes`, which really doesn't make sense. Here is the traceback I'm seeing.

Using Python 3.5 from Anaconda.

```
$ pyi-grab_version --help
Traceback (most recent call last):
  File "/zopt/conda3/envs/_test/bin/pyi-grab_version", line 4, in <module>
    import PyInstaller.utils.cliutils.grab_version
  File "/zopt/conda3/envs/_test/lib/python3.5/site-packages/PyInstaller/utils/cliutils/grab_version.py", line 15, in <module>
    import PyInstaller.utils.win32.versioninfo
  File "/zopt/conda3/envs/_test/lib/python3.5/site-packages/PyInstaller/utils/win32/versioninfo.py", line 15, in <module>
    import pywintypes
ImportError: No module named 'pywintypes'
```

**Comment by jakirkham** [comment]
Same story when running `pyi-set_version --help` as well.

**Comment by stephenrauch** [comment]
What is the use case here? From the docs:

_pyi-grab_version is used to extract a version resource from a Windows executable. See [Capturing Windows Version Data](http://pyinstaller.readthedocs.io/en/stable/usage.html#capturing-windows-version-data)._

Were you just trying to understand what the script did, thus the ```--help```?

**Comment by jakirkham** [comment]
> Were you just trying to understand what the script did, thus the `--help`?

Pretty much. It wasn't obvious to me that it was Windows only initially. Normally I would figure I could run `--help` to determine what it does. Though I suppose there is an argument for simply not installing these commands on Mac. That being said, I guess you are right that I could look at the docs.

Not really a big deal how it get resolved (if at all). Just figured I should share the new user perspective.
