### ISSUE TITLE
is it  support pymssql  ??

### ISSUE THREAD

**Issue by zsz00** [pyinstaller/pyinstaller#2055]
is it  support pymssql  ??
can you  support pymssql in next update??
thanks!

**Comment by stephenrauch** [comment]
To get the devs attention, you will need to be more specific.  You will need to try and use pyinstaller with a program that uses pymssql, and then if it does not work, you will need to follow the instructions for [submitting a bug](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by htgoebel** [comment]
@zsz00 If somebody is contributing a hook, we will happily integrate it.

But we will not implement one ourself for two reasons:

1. mssql is a proprietary, commercial product which we do not have installed.

2. mssql is mostly used in companies which are earning money, If they need a hook, they should dedicate resources to implement it or should go out and fund the development. I see no reason why volunteers should work for free to make companies save money.

**Comment by zsz00** [comment]
https://pypi.python.org/pypi/pymssql

pymssql
A simple database interface for Python <http://www.python.org/> that builds
on top of FreeTDS <http://www.freetds.org/> to provide a Python DB-API (
PEP-249 <http://www.python.org/dev/peps/pep-0249/>) interface to Microsoft
SQL Server <http://www.microsoft.com/sqlserver/>.



2016-06-17 15:48 GMT+08:00 Hartmut Goebel <notifications@github.com>:

**Comment by zsz00** [comment]
help me ..
thanks

2016-06-19 16:21 GMT+08:00 Sz Z <zsz6174@gmail.com>:

**Comment by zsz00** [comment]
pyinstaller support pyodbc , but the pyodbc is very bad to chinese.
so , i must use the pymssql  to link sql server .
please help and support the pymssql in next pyinstaller version.
thank you very much!

2016-06-20 9:54 GMT+08:00 Sz Z <zsz6174@gmail.com>:
