### ISSUE TITLE
Files built with --noconsole fail to run

### ISSUE THREAD

**Issue by ChrisTruncer** [pyinstaller/pyinstaller#2056]
Just a FYI, the first thing I did was go through each of the guides linked when creating an issue.  Since I did not see anything after running those tests that could point me to something to debug, I wanted to post here.

I'm kind of an odd situation.  I run pyinstaller on Linux, within Wine, to make windows executables on Linux.  This has worked without a problem for a while now.  However, since moving to 3.1 and now 3.2, I am running into an issue.  When I build an executable from a python script and I use the --noconsole flag, the executable will not run and gives a "Fatal Error - Cannot open self or archive" error.

However, if I don't provide the --noconsole flag, it works perfectly.  I've tested this using --onefile and --onedir, and the results are the same.  If --noconsole is present, the executable won't run.  If it isn't there, then it runs perfectly.

I'm running PyInstaller 3.2 now and am just kind of confused.  Any ideas?

**Comment by tallforasmurf** [comment]
Just to be clear, the fatal error result happens on "real" Windows (v7? 10?) as well as WINE?
Have you built with the `--debug` flag to see what the bootloader knows?

**Comment by ChrisTruncer** [comment]
Yes, when I run this on a real Windows 7 machine, it gives the fatal error.  I will state this process used to work, so I'm not trying something experimental here, it's been the way I've aways "compiled" scripts.

Another note, when using --debug, the script crashes where windows says it crashes.

But if I run the same script without --noconsole it all works perfectly.

**Comment by ChrisTruncer** [comment]
Actually, I stand corrected.  When I use --debug with --noconsole, the script works.  Everything runs, and nothing crashes.

So I've narrowed it down, if I use --noconsole, it fails.  If I use --debug AND --noconsole then the debug info shows up, and the script runs successfully.  So it ONLY fails if I use --noconsole without --debug.

**Comment by tallforasmurf** [comment]
I am clueless about both windows and the bootloader, however just perusing the loader.py source searching for "debug" I find these comments: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/pyiboot01_bootstrap.py#L67 *et. seq.* through line 97.

Looking at the C source, I see lots of calls to a macro VS('informative progress string') which I assume is printing conditional debug output. However I don't see where VS() is defined. Presumably when --debug was given, VS will do something different. Hopefully somebody who knows the bootloader will comment now.

**Comment by ChrisTruncer** [comment]
Yeah, I'm not sure what exactly would be different, but it does seem to be different somehow since --noconsole works only when coupled with --debug.

If there's any extra info I can give, please ask.  I'd really love to keep using --noconsole :)

**Comment by tallforasmurf** [comment]
I'm out of my depth here. @htgoebel, @matysek, have you seen this thread?

**Comment by jouker1** [comment]
same problem in windows 10 x64 gives a "Fatal Error - Cannot open self or archive" error .

**Comment by matysek** [comment]
@ChrisTruncer to slim down the debugging does latest develop version with helloworld example produce the same error?

**Comment by codewarrior0** [comment]
Can't reproduce when building on Windows 7 with either the v3.2 release or the develop head. Might be something specific to WINE.

**Comment by ChrisTruncer** [comment]
I just confirmed that a simple hello world produces the same error.

![helloworld](https://cloud.githubusercontent.com/assets/1674822/16305696/2adb7a50-3918-11e6-82c0-7a4c2e67e7fb.png)

**Comment by ChrisTruncer** [comment]
I just wanted to follow up and see if the developers had any suggestions for this issue.

Thanks for your help

**Comment by ChrisTruncer** [comment]
@Codewarrior0 - I know someone else reported a Veil issue here, sorry about that.  But it is partially related to this.  They are getting a popup because we can't use --noconsole due to the issue I've referenced in here.  If there's any additional information I can give you to help look into this, please let me know.

**Comment by codewarrior0** [comment]
When running with both `--noconsole` and `--debug`, you should get additional popups leading up to the "Cannot open self" popup. Would you mind transcribing at least the last few leading up to the program's termination?

"Cannot open self" is displayed if `pyi_arch_setup` returns a failure status, `pyi_arch_setup` can only return a failure status if `pyi_arch_open` also does so, and `pyi_arch_open` does not return a failure status without also writing/popping-up an error message about the reason it failed. It will be either "Cannot open archive", "Cannot find cookie", "Could not allocate buffer", "Could not read from file", or "Error on file".

**Comment by ChrisTruncer** [comment]
@codewarrior0 - I wish I could give you that information with --debug.  However, if I run both --noconsole AND --debug, the executable works perfectly.  It does not break, and there is no error.  I only encounter this error if I run --noconsole without --debug.  The only error message I get at any time is essentially the screenshot earlier in this thread.

I tried to determine if it was something related to my specific system, so I built out a couple of VMs to test the environment, and it also happens on other systems (Linux, Debian with wine) so this is repeatable too and not something just isolated to my system.

**Comment by codewarrior0** [comment]
It's just bizarre that what causes the failure is the lack of --debug. 

This flag makes PyInstaller choose a different bootloader to build the exe from. The only difference  with the debug bootloader is that the `VS()` macro is defined to something other than a no-op.

But maybe it's not directly related to the `VS()` macro. The debug bootloader will among other things have a different file size.

From looking through the source code and knowing that only the "Cannot open self" popup is displayed, I can narrow it down to two failure reasons. Either `fopen()` fails when opening the executable (not likely), or `pyi_arch_find_cookie()` (`pyi_arch_check_cookie()` in 3.2 release) fails to find the cookie that is written to the very end of the file. 

It looks like you aren't using code signing. My wild guess is that, when building under WINE, the build process writes some incorrect data to the end of the executable which the bootloader code is then unable to read, but this only happens with the non-debug bootloader because of a difference in file sizes.

Do you think you could upload a faulty exe so I can do some quick analysis on it?

**Comment by ChrisTruncer** [comment]
Yeah, I'll look into writing one now.  So full disclosure, Veil-Evasion writes AV evading files which can be used for various purposes, that's what we've been using this for.  I'm thinking I **should** be able to do a hello world again that re-creates this issue.  If for some reason I need to use a full file output from Veil, I'll sinkhole it to 127.0.0.1 and it won't connect outbound.  I'll also give you the full information on the file so you know what you are opening.

Would you want me to upload it here (not even sure if GitHub allows executables to be uploaded), or is there a way I can contact you and send it through another channel?

**Comment by codewarrior0** [comment]
I understand. I wasn't planning on running the file anyway, just doing a hex dump and making sure the cookie data isn't completely messed up.

A simple helloworld exe would be best, to eliminate the possibility that Veil is doing something to cause this. If you can't upload it here, a file sharing site like Dropbox or Google Drive is fine.

**Comment by codewarrior0** [comment]
(Have you checked all four combinations with/without --debug and --noconsole to see if any others fail in the same way?)

**Comment by ChrisTruncer** [comment]
OK, I just validated it again, and everything is still as described above.  The "hellowithdebug" is a hello world with debug mode enabled (using --noconsole).  So it won't show any output since there is --noconsole, but the program works.  The hellonodebug doesn't have --debug and it produces the error described above.

Hope that this uploads fine :)


[helloworldfiles.zip](https://github.com/pyinstaller/pyinstaller/files/369685/helloworldfiles.zip)

**Comment by ChrisTruncer** [comment]
And you're correct, I'm not code signing the executables that are created by this @codewarrior0

**Comment by codewarrior0** [comment]
Both exes have a correct cookie and will display properly in the pyi archive viewer. I ran both exes in a virtual machine. Here's the first thing I found that is going wrong: `hellonodebug` is reading from the wrong position in the file (24 bytes from the end, rather than 88 bytes, where 88 == sizeof(COOKIE)).

![image](https://cloud.githubusercontent.com/assets/307683/16929356/207c3b16-4cd3-11e6-9519-a4bd76b57153.png)

While doing this, I noticed that `hellonodebug` has no dependency on `MSVCR100.dll`, while `hellowithdebug` does depend on it. I examined the 32-bit bootloaders for release 3.2 (which have a known issue where the 32-bit ones were incorrectly compiled with MSVC 10.0) and found they all depend on `MSVCR100.dll`. I then checked the ones on the develop head (since I had personally rebuilt them to address this issue) and confirmed that none of them depend on this DLL - they were built with MinGW instead of MSVC. 

The situation where the `runw.exe` and `runw_d.exe` bootloaders are different with respect to `MSVCR100.dll` is not represented by any version of PyInstaller. So my conclusion is that your PyInstaller installation is damaged and contains incorrect bootloader files.

**Comment by ChrisTruncer** [comment]
@codewarrior0 - So I'm not certain how this can be fixed.  I've completely nuked the pyinstaller directory that I've been using and reinstalled from the latest develop branch.  Nothing else is modifying the file and I continue to get this error.  The only way I can fix this is by not using --noconsole but I'd really prefer not to do that.

I can confirm I am using the latest version that is present on this Github repo as of 15 minutes ago when I re-cloned the repo down, deleted everything currently on my system, and used the new clone.

**Comment by ChrisTruncer** [comment]
Also @codewarrior0, I'd like to say I really appreciate you taking the time to look into this as well.

**Comment by codewarrior0** [comment]
Download Process Monitor and Dependency Walker and see if you can reproduce my investigations into the seek position and the MSVCRT100.dll linkage. I am 100% certain that you are using an outdated and mismatched version of the `Windows-32bit/runw.exe` bootloader.

**Comment by ChrisTruncer** [comment]
I did a lot of digging into my codebase, and I think you are right.  I am going to try to continue to play with this and see if I can figure out exactly where the issue is.  I did just get one payload to work with --noconsole after dragging a known good runw.exe from one system over to my current dev system.  So, it must be, as you said, something with how I am building out pyinstaller.

If you wouldn't mind, I'd like to leave this open just in case I have any questions, but I HOPE that I can take it from here and figure it out.

I'd like to again state I really appreciate you taking the time to look into this and help debug the issue.  I'll close this once I have it completely fixed, but I do believe it is on my end.

Thanks again.

**Comment by ChrisTruncer** [comment]
@codewarrior0 - As I'm sure you knew, you were correct.  It was indeed an old version of runw that was being replaced at runtime, and therefore wasn't using the old one.  Once I found that, a 5 second fix made it all work again.

Thanks again for taking the time to look into this.

**Comment by willyamyep** [comment]
Please @ChrisTruncer can you tell me how you fix your problem. I think i have the same.
Thank you.

**Comment by skysoft999** [comment]
@ChrisTruncer  Even i too facing the same issue somebody help me please.

**Comment by Zakariyya** [comment]
I have also encountered this problem. And don't know how to solve it

**Comment by hsumerf** [comment]
In Python 2.7 use subprocess like this: 
```
DEVNULL = open(os.devnull,"wb") 
output = subprocess.check_output(command, shell=True,stderr=DEVNULL,stdin=DEVNULL)

```
In Python 3 use subprocess like this:
```
DEVNULL = subprocess.DEVNULL
output = subprocess.check_output(command,shell=True, stderr = DEVNULL , stdin = DEVNULL )

```

**Comment by CODAIR2** [comment]
> 
> 
> In Python 2.7 use subprocess like this:
> 
> ```
> DEVNULL = open(os.devnull,"wb") 
> output = subprocess.check_output(command, shell=True,stderr=DEVNULL,stdin=DEVNULL)
> ```
> 
> In Python 3 use subprocess like this:
> 
> ```
> DEVNULL = subprocess.DEVNULL
> output = subprocess.check_output(command,shell=True, stderr = DEVNULL , stdin = DEVNULL )
> ```

How does this work again? Anyone?
