### ISSUE TITLE
Failed to Generate Process

### ISSUE THREAD

**Issue by cyrilcourtoy** [pyinstaller/pyinstaller#2057]
On fresh install of pyinstaller on windows where the path to python contains spaces, I get the **failed to generate process** error

To fix this issue the first line of **pyinstaller-script.py** must be changed from :

`#!c:\program files (x86)\python35-32\python.exe`
to
`#"!c:\program files (x86)\python35-32\python.exe`"

This is a known issue from the community, however, every time I upgrade pyinstaller this error comes back. The location for **python.exe** on the first line of the **pyinstaller-script.py** must be surrounded by double quotes if the installation path contains spaces. Since the default in windows is **C:\Program Files (x86)\Python35-32** there is a good chance of that happening to many users.

ref: https://stackoverflow.com/questions/17373265/pip-easy-install-failure-failed-to-create-process

**Comment by htgoebel** [comment]
This issue is related to pip. If you have any idea what PyInstaller could do about this, please re-open the issue - or even better: submit a pull-request.
