### ISSUE TITLE
please  support the pymssql 

### ISSUE THREAD

**Issue by zsz00** [pyinstaller/pyinstaller#2058]
pyinstaller support pyodbc , but the pyodbc is very bad to chinese. 
so , i must use the pymssql  to link sql server .

pymssql
https://pypi.python.org/pypi/pymssql 
A simple database interface for Python that builds on top of FreeTDS to provide a Python DB-API (PEP-249) interface to Microsoft SQL Server.

please help and support the pymssql in next pyinstaller version.
thank you very much!

**Comment by matysek** [comment]
hi @zsz00, please add any code example how you use pymssql or any traceback you get while trying latest pyinstaller version.

**Comment by htgoebel** [comment]
Duplicate, won't fix, see #2055

**Comment by zsz00** [comment]
import pymssql
conn = pymssql.connect(host="127.0.0.1",user="sa",password="passwd.",
database="master")
cur=conn.cursor()
cur.execute("select * from tab")
data=cur.fetchall()
print(data[1])


2016-06-22 16:12 GMT+08:00 Martin Zibricky <notifications@github.com>:

**Comment by zsz00** [comment]
https://pypi.python.org/pypi/pymssql/2.1.3 

pymssql is very good,,

**Comment by zsz00** [comment]
@matysek , help me please ,, https://pypi.python.org/pypi/pymssql/2.1.3
can you  add the pymssql to pyinstaller ?
  i must use the pymssql to link sql server .
thank you very much!

**Comment by htgoebel** [comment]
@zsz00 Please stop posting requests for pymssql. See my answer in https://github.com/pyinstaller/pyinstaller/issues/2055#issuecomment-226703522
