### ISSUE TITLE
Import error when running an executable from a python script which imports requests

### ISSUE THREAD

**Issue by LarryMartell** [pyinstaller/pyinstaller#2060]
Here is my test script:

> import requests

Here is the output of pyinstaller:

> $ pyinstaller --clean --debug pyi_test.py 
> 60 INFO: PyInstaller: 3.2
> 60 INFO: Python: 2.7.5
> 61 INFO: Platform: Linux-3.10.0-327.13.1.el7.x86_64-x86_64-with-redhat-7.2-Maipo
> 65 INFO: wrote /home/lmartell/pyi_test.spec
> 70 INFO: UPX is not available.
> 71 INFO: Removing temporary files and cleaning cache in /home/lmartell/.cache/pyinstaller
> 82 INFO: Extending PYTHONPATH with paths
> ['/home/lmartell', '/home/lmartell']
> 83 INFO: checking Analysis
> 83 INFO: Building Analysis because out00-Analysis.toc is non existent
> 83 INFO: Initializing module dependency graph...
> 87 INFO: Initializing module graph hooks...
> 169 INFO: running Analysis out00-Analysis.toc
> 190 INFO: Caching module hooks...
> 195 INFO: Analyzing /home/lmartell/pyi_test.py
> 2011 INFO: Processing pre-safe import module hook   _xmlplus
> 2660 INFO: Loading module hooks...
> 2660 INFO: Loading module hook "hook-xml.py"...
> 2724 INFO: Loading module hook "hook-httplib.py"...
> 2724 INFO: Loading module hook "hook-requests.py"...
> 2726 INFO: Loading module hook "hook-encodings.py"...
> 3242 INFO: Looking for ctypes DLLs
> 3242 INFO: Analyzing run-time hooks ...
> 3265 INFO: Looking for dynamic libraries
> 3812 INFO: Looking for eggs
> 3813 INFO: Using Python library /lib64/libpython2.7.so.1.0
> 3833 INFO: Warnings written to /home/lmartell/build/pyi_test/warnpyi_test.txt
> 3964 INFO: checking PYZ
> 3964 INFO: Building PYZ because out00-PYZ.toc is non existent
> 3964 INFO: Building PYZ (ZlibArchive) /home/lmartell/build/pyi_test/out00-PYZ.pyz
> 4561 INFO: checking PKG
> 4561 INFO: Building PKG because out00-PKG.toc is non existent
> 4561 INFO: Building PKG (CArchive) out00-PKG.pkg
> 4596 INFO: Bootloader /usr/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
> 4596 INFO: checking EXE
> 4596 INFO: Building EXE because out00-EXE.toc is non existent
> 4597 INFO: Building EXE from out00-EXE.toc
> 4599 INFO: Appending archive to ELF section in EXE /home/lmartell/build/pyi_test/pyi_test
> 4631 INFO: checking COLLECT
> 4631 INFO: Building COLLECT because out00-COLLECT.toc is non existent
> WARNING: The output directory "/home/lmartell/dist/pyi_test" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
> 7136 INFO: Removing dir /home/lmartell/dist/pyi_test
> 7181 INFO: Building COLLECT out00-COLLECT.toc

And when I run the executable:

> $ dist/pyi_test/pyi_test 
> Traceback (most recent call last):
>   File "pyi_test.py", line 1, in <module>
>     import requests
>   File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.**dict**)
>   File "requests/**init**.py", line 58, in <module>
>   File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.**dict**)
>   File "requests/utils.py", line 26, in <module>
>   File "/usr/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.**dict**)
>   File "requests/compat.py", line 7, in <module>
>   File "requests/packages/**init**.py", line 95, in load_module
> ImportError: No module named 'requests.packages.chardet'

**Comment by matysek** [comment]
@LarryMartell could you try the latest 'develop' version of pyinstaller?

**Comment by matysek** [comment]
@LarryMartell one more thing...try this option `--hidden-import=requests.packages.chardet`

**Comment by LarryMartell** [comment]
If I clone the repo, can I just run pyinstaller.py or do I have to run
setup.py install from the cloned repo? I tried with pyinstaller.py from the
cloned repo and I got the same error. I tried running setup.py install from
the cloned repo and I got error: could not create 'PyInstaller.egg-info':
Permission denied even thought I was running as root.

**Comment by LarryMartell** [comment]
Same error with this option.

**Comment by stephenrauch** [comment]
Just an FYI, I was unable to duplicate on windows with python 2.7.11

**Comment by LarryMartell** [comment]
I am on RHEL 7.2 with Python 2.7.5

**Comment by LarryMartell** [comment]
I figured out the permission denied problem with the install, but it made no difference. Still get the same error.

**Comment by htgoebel** [comment]
Is this still a problem?

**Comment by LarryMartell** [comment]
Yes.

**Comment by htgoebel** [comment]
Please try the latest development version of PyInstaller. Also please use the latest version of requests.

**Comment by htgoebel** [comment]
No more feedback, I assume this is solved.

**Comment by LarryMartell** [comment]
Sorry I have not tried it. My client has moved on to other issues. If and
when they want to revisit this I will let you know either way if it works
or not.
