### ISSUE TITLE
(PyQt4) Wierd case of app not showing, but showing in CMD

### ISSUE THREAD

**Issue by techbliss** [pyinstaller/pyinstaller#2061]
First thanks for making this great builder.
I have encountered a wierd case and cant find any way to solve this.

I made a splash screen app in PyQt4  that fetch the newest github release build.
https://github.com/techbliss/x64dbg_updater

I have tried 
the commands

```
pyinstaller.exe --windowed --singlefile --icon=app.ico File.py
```

```
pyinstaller.exe --singlefile --icon=app.ico File.py
```

and some more 

all build fine, but app GUI aint showing when runned.

i can see in the bacground that app is runing if not chosed --windowed 

and is downloading latest release(runing the app).

But then if i drag the compiled app into command prompt window, the splash shows correct.

any ideas

using  latest developer build, but any branch it is like this.

**Comment by htgoebel** [comment]
PyInstaller does not have an option `--singlefile`. Are you sure you are using the official version?

Anyway, please try the current development version. If this does not help, please search the open and closed issues about these kind of problems. There should be some about applications running with `--console`, but not with `--windowed`.

**Comment by techbliss** [comment]
Actuelly today, i found the problem.

it is correct the --singlefile do not exitst, I meant --onefile.None the less was the problem.That the splash screenpicture was not copied to ditribution folder.
I fixed this by converting the .png to python hex , and adding this to the pyinstaller conversing command.

issue can be closed.
