### ISSUE TITLE
[ImportError] DLL Load failed (PyCrypto-2.6.1)

### ISSUE THREAD

**Issue by CyberDonky** [pyinstaller/pyinstaller#2062]
Hello Developers / Users of PyInstaller,

For my schoolproject I'm using PyInstaller to convert the python file with the included modules to one Executable file with the following command:
`pyinstaller --onedir --onefile --name=IFSCP "C:\Python27\main.py"`
_I'm not using prefix --windowed, because the Python Program is in console mode._

Everything went fine with compiling, but there is one issue while opening the executable. The following error comes up by loading the executable:

```
Traceback (most recent call last):
 File "main.py", line 13 in <module>
 File "C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a5d\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
     exec(bytecode, module, __dict__)
 File "c:\users\yourik~1\appdata\local\temp\easy_install-gzievh\pycrypto-2.6.1-py2.7-win32.egg.tmp\Crypto\Cipher\AES.py", line 50, in <module>
 File "C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a5d\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
     exec(bytecode, module, __dict__)
 File "c:\users\yourik~1\appdata\local\temp\easy_install-gzievh\\pycrypto-2.6.1-py2.7-win32.egg.tmp\Crypto\Cipher\_AES.py", line 7 in <module>
 File "c:\users\yourik~1\appdata\local\temp\easy_install-gzievh\\pycrypto-2.6.1-py2.7-win32.egg.tmp\Crypto\Cipher\_AES.py", line 6 in __bootstrap__
ImportError: DLL load failed: Kan opgegeven module niet vinden. 
```

_Kan opgegeven module niet vinden. -> Can't find module_

The ImportError don't show up without the
`from Crypto.Cipher import AES`
in the script. 

Debug info:

```
C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a5d\IFSCP\dist>IFSCP.exe

PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a5
d\IFSCP\dist\IFSCP.exe
LOADER: homepath is C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a5d\
IFSCP\dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a
5d\IFSCP\dist\IFSCP.exe
LOADER: Extracting binaries
LOADER: Executing self as child
LOADER: set _MEIPASS2 to C:\Users\YOURIK~1\AppData\Local\Temp\_MEI60522
LOADER: Setting up to run child
LOADER: Creating child process
LOADER: Waiting for child process to finish...
PyInstaller Bootloader 3.x
LOADER: executable is C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a5
d\IFSCP\dist\IFSCP.exe
LOADER: homepath is C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a5d\
IFSCP\dist
LOADER: _MEIPASS2 is C:\Users\YOURIK~1\AppData\Local\Temp\_MEI60522
LOADER: archivename is C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a
5d\IFSCP\dist\IFSCP.exe
LOADER: SetDllDirectory(C:\Users\YOURIK~1\AppData\Local\Temp\_MEI60522)
LOADER: Already in the child - running user's code.
LOADER: manifestpath: C:\Users\YOURIK~1\AppData\Local\Temp\_MEI60522\IFSCP.exe.m
anifest
LOADER: Activation context created
LOADER: Activation context activated
LOADER: Python library: C:\Users\YOURIK~1\AppData\Local\Temp\_MEI60522\python27.
dll
LOADER: Loaded functions from Python library.
LOADER: Manipulating environment (sys.path, sys.prefix)
LOADER: sys.prefix is C:\Users\YOURIK~1\AppData\Local\Temp\_MEI60~1
LOADER: Setting runtime options
LOADER: Bootloader option: pyi-windows-manifest-filename IFSCP.exe.manifest
LOADER: Initializing python
LOADER: Overriding Python's sys.path
LOADER: Post-init sys.path is C:\Users\YOURIK~1\AppData\Local\Temp\_MEI60522
LOADER: Setting sys.argv
LOADER: setting sys._MEIPASS
LOADER: importing modules from CArchive
LOADER: extracted struct
LOADER: callfunction returned...
LOADER: extracted pyimod01_os_path
LOADER: callfunction returned...
LOADER: extracted pyimod02_archive
LOADER: callfunction returned...
LOADER: extracted pyimod03_importers
LOADER: callfunction returned...
LOADER: Installing PYZ archive with Python modules.
LOADER: PYZ archive: out00-PYZ.pyz
LOADER: Running pyiboot01_bootstrap.py
LOADER: Running pyi_rth_pkgres.py
LOADER: Running pyi_rth__tkinter.py
LOADER: Running main.py
Traceback (most recent call last):
  File "main.py", line 13, in <module>
  File "C:\Users\Youri Kool\Desktop\pyinstaller-pyinstaller-8689a5d\PyInstaller\
loader\pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "c:\users\yourik~1\appdata\local\temp\easy_install-gzievh\pycrypto-2.6.1-
py2.7-win32.egg.tmp\Crypto\Cipher\_AES.py", line 7, in <module>
  File "c:\users\yourik~1\appdata\local\temp\easy_install-gzievh\pycrypto-2.6.1-
py2.7-win32.egg.tmp\Crypto\Cipher\_AES.py", line 6, in __bootstrap__
ImportError: DLL load failed: Kan opgegeven module niet vinden.
Failed to execute script main
LOADER: OK.
LOADER: Cleaning up Python interpreter.
LOADER: Back to parent (RC: -1)
LOADER: Doing cleanup
LOADER: Freeing archive status for C:\Users\Youri Kool\Desktop\pyinstaller-pyins
taller-8689a5d\IFSCP\dist\IFSCP.exe
```

I installed the following applications:
**Pywin32 version 220**
**cx-Freeze version 4.3.4**
**PyCrypto version 2.6.1**
Pyinstaller pyinstaller-pyinstaller-8689a5d (Developer) and PyInstaller-3.2 giving the same error.

I hope someone can help me :) 

Thank you in advance.

Regards,

Youri

**Comment by tallforasmurf** [comment]
I am confused by `pyinstaller --onedir --onefile` because these options should be mutually contradictory. It appears that the `--onefile` option was effective, as the trace is shows unpacking into a temp folder. So you can leave out the `--onedir`.

So this module `Crypto.Cipher` is trying to access some DLL that didn't get into the bundle. This is common. You need to find out what it is trying to load and get that into the bundle, either by editing the spec file or by creating a "hook" for this module. The hooks being distributed do not include one for anything called "Crypto" that I see. Only module cryptography.

Something I would investigate first is, looking at this line:

File "c:\users\yourik~1\appdata\local\temp\easy_install-gzievh\pycrypto-2.6.1-
py2.7-win32.egg.tmp\Crypto\Cipher\_AES.py", line 6,

I am curious about the location `yourik~1\appdata\local\temp\` etc, which (I think) is not where a normal Python module would be installed. If the location of module Crypto was not in sys.path at the time pyinstaller was building the bundle, that might explain why it didn't find all the dependencies. So is module Crypto correctly installed? And if you just start up Python and type `import Crypto.Cipher`, does that work?

**Comment by htgoebel** [comment]
Please try with only *one* of `--onedir` or `--oneifle` (also I do not assume this is the course of the error.

Then:
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by htgoebel** [comment]
pycrypto is [officially dead](https://github.com/dlitz/pycrypto/issues/173) and [seriously buggy](http://lists.gnu.org/archive/html/guix-devel/2016-12/msg01007.html). Please move forward to an alternative. We ought not spend time fixing support for dead software.
