### ISSUE TITLE
pyinstaller3.2  build onefile exe , can not run with loading msvcr100.dll

### ISSUE THREAD

**Issue by jimying** [pyinstaller/pyinstaller#2074]
environment：
windows7  pyqt4   python2.7.11   pyinstaller3.2

Problem：
build onfile exe, when run it,  stop with loading msvcr100.dll

**Comment by alxchk** [comment]
Same problem. Looks like loader now depends on latest runtime. Maybe there is a way to distribute different loaders? Or at least distribute msvcr90 for python2.7?

**Comment by codewarrior0** [comment]
This is already fixed in the latest develop head. The loader had been compiled incorrectly.
