### ISSUE TITLE
Virus Gen:Variant.Razy.41062 report in pyinstaller / docutils / rst parser on windows 7 and windows 10

### ISSUE THREAD

**Issue by BillBridge** [pyinstaller/pyinstaller#2076]
I am building an exe called sg-assist.exe using pyinstaller.
Unfortunately at build time this triggers my virusscanner (both alerted by Norman and F-secure) with the following virus: Gen:Variant.Razy.41062 - though my PC is clean.
When setting the build environment to the list of accepted (do not include in scanning) folders the build produces a distribution package. But when installing this package on another PC with another virusscanner, same virus is triggered..

When adding docutils to the list of excluded modules in my PyInstaller script, the application is build without any virus triggers but then of course the lack of docutils results in an error message:

![docutils-error](https://cloud.githubusercontent.com/assets/18249253/16465701/5b04d42e-3e40-11e6-8510-685bb3c38228.png)

Here is the PyInstaller spec file:

[test-spec.txt](https://github.com/pyinstaller/pyinstaller/files/340025/test-spec.txt)

 It occurs only when building sg-assist.exe with option console=False ; see attached test-spec.txt file above.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is nothing(!) we can do here.

See [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by BillBridge** [comment]
I find this a very strange reply. It is very obvious that PyInstaller is "doing" something here. It is even reproducable! When I set console = False it will trigger not only my Virus scanner but also the scanners of my customers. It is unacceptable to ask customers to contact their anti-virus vendor when they want to use my product! 
It looks like you just don't want to look into this matter......

**Comment by htgoebel** [comment]
PyInstaller uses different bootloaders for window- and cosole-mode. If your anti-virus vendor considers one of these file as a virus, there is *nothing* we can do about this Even if we'd change our code, they'd change their pattern and we race starts again.
