### ISSUE TITLE
Broken links on pyinstaller.org

### ISSUE THREAD

**Issue by pjvandehaar** [pyinstaller/pyinstaller#2077]
**Edit: I see that [this commit](https://github.com/pyinstaller/pyinstaller.github.io/commit/1e46907c3226476a624846dcea5720aca4e89ea4) should have fixed this issue but apparently Sphinx hasn't been re-run.**

(Sorry if this is the wrong place to report this.)

www.pyinstaller.org/ contains several links to https://pyinstaller.rtfd.io/ .  But it looks like the wildcard  certificate for that site is broken, so those links lead to scary pages in all web browsers.

Here are the links that need to be updated:
- _Downloads_ > _Change Log_ should point to http://pyinstaller.readthedocs.io/en/latest/CHANGES.html
- The first 4 links in the section _Documentation_ should point to:
    - http://pyinstaller.readthedocs.io/en/stable/
    - https://media.readthedocs.org/pdf/pyinstaller/stable/pyinstaller.pdf
    - http://pyinstaller.readthedocs.io/en/latest/
    - https://media.readthedocs.org/pdf/pyinstaller/latest/pyinstaller.pdf

Here's are some more pages with broken links: https://www.google.com/#q=site:www.pyinstaller.org+info:https:%2F%2Fpyinstaller.rtfd.io

**Comment by htgoebel** [comment]
The correct place to report this issue would have been https://github.com/rtfd/readthedocs.org/issues/328 of course :-)

I don't have any clue, why this change is not shown on the website. I just force-pushed the repo, but this does not change the content on the website. Seams to be an github issue.

**Comment by pjvandehaar** [comment]
The links are correct on https://github.com/pyinstaller/pyinstaller.github.io/blob/master/index.rst but not on <https://github.com/pyinstaller/pyinstaller.github.io/blob/master/index.html>.

I don't know much about Sphinx, but I think you have to `make` [that `Makefile`](https://github.com/pyinstaller/pyinstaller.github.io/blob/master/Makefile).

I agree it's a readthedocs issue, but it doesn't look like they'll ever fix it.

**Comment by htgoebel** [comment]
Thanks, indeed the HTML pages have not been rebuild. Thanks for pointing this out - I did not see it when looking at the diff.

**Comment by pjvandehaar** [comment]
Thanks @htgoebel !
