### ISSUE TITLE
wxpython app freezing and with strange look

### ISSUE THREAD

**Issue by mprosperi** [pyinstaller/pyinstaller#2082]
I have a large wxpython application that I used to package with py2exe. I recently passed to pyinstaller to solve problems with some libraries but I'm facing a new issue with pyinstaller (python 2.7 for win64,wxpython classic 3.0.2): 
- the program packaged with pyinstaller on win7 works fine on win7 and win8 but on win10 freezes when I choose a menu entry from the menu bar without messages on console and has a different look with respect to when it runs directly from source
- the problem is present on win10 also if I create the package on win10
- trace.txt from sxstrace is emtpy
- I've tried both pyinstaller 3.2 and the development version with the same result
  I've attached a sample wxpython script that I haven't succeeded to freeze when clicked but which shows the different look when packaged with pyinstaller (see the different arrow of the central button)

thank you in advance for hints or solution

[wxsimple.txt](https://github.com/pyinstaller/pyinstaller/files/344229/wxsimple.txt)

**Comment by mprosperi** [comment]
The solution I've found is removing the compatibility section from the exe manifest generated by pyinstaller

**Comment by Legorooj** [comment]
Closing because fix discovered.
