### ISSUE TITLE
when i try to execute the created exe file i get error "Failed to execute script pyi_rth_pkgres" I am using python 2.7 32bit and my system is in 64bit

### ISSUE THREAD

**Issue by bhuwantm** [pyinstaller/pyinstaller#2084]
If you have problems to get your application running, please first

* follow the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If you problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.

**Otherwise we will not be able to help you.**

**Comment by bhuwantm** [comment]
downgrading setuptools solved the problem

**Comment by nchammas** [comment]
@bhuwantm Downgrading from what version to what version fixed the problem for you?

**Comment by remdragon** [comment]
I just ran into this same problem with pyinstaller 3.3.1. Tried downgrading to 3.3 and that didn't fix the problem.

I stumbled across this and I had recently updated my setuptools, so decided to try downgrading setuptools to the default for my version of Python and it fixed this issue.

Problematic setuptools: 38.4.0
working setuptools: 28.8.0
python version: Python 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)] on win32
pyinstaller and setuptools versions acquired via pip
python installed from python.org

**Comment by NHades** [comment]
Adding "pkg_resources.py2_warn" to hiddenimports solves this issue

**Comment by Kulbear** [comment]
@NHades what do you mean by adding "pkg_resources.py2_warn" to hidden import? How to do that? Thanks!

**Comment by Odatas** [comment]
You can put that in the console line as an argument

pyinstaller --hidden-import pkg_resources.py2_warn

I advice to use the auto py to exe which is a gui for pyinstaller. 

pip intall auto-py-to-exe

**Comment by BhuvneshSain** [comment]
> You can put that in the console line as an argument
> 
> pyinstaller --hidden-import pkg_resources.py2_warn
> 
> I advice to use the auto py to exe which is a gui for pyinstaller.
> 
> pip intall auto-py-to-exe

I did use auto-py-to-exe but still the same issue.
