### ISSUE TITLE
PyQt5 Fatal Error: Failed to execute script

### ISSUE THREAD

**Issue by Veys26** [pyinstaller/pyinstaller#2087]
This is the most non-sense issue about PyQt5-Pyinstaller. There is no common point of the systems that has this problem. For example, %50 of the systems (Windows 7) could run the program, %50 of them couldn't. This also same for other systems such as Windows-10. Some of the systems can't run the app and this error occurs:

[Fatal Error](http://1.1m.yt/rGb3s1o.png) **cek** is the name of the .py file.

I tried **every** solution in **https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong**. Nothing worked.

**Comment by redstoneleo** [comment]
https://github.com/pyinstaller/pyinstaller/issues/2015#issuecomment-222408252

**Comment by bjones1** [comment]
Please provide more information. Closing for now. See also #3233.
