### ISSUE TITLE
Payload Veil show prompt windows when run “Bug Pyinstaller”

### ISSUE THREAD

**Issue by cacaocaca** [pyinstaller/pyinstaller#2091]
Hi guys i have kali linux rolling 
`Linux kali 4.5.0-kali1-686-pae #1 SMP Debian 4.5.5-1kali1 (2016-06-06) i686 GNU/Linux`

Becouse if generate any payload with veil afther use easy binder for binder with winrar or other but it is same and run on windows he show me so the prompt of windows .. How can i solve it ?
https://postimg.org/image/um7j3vdlz/
This Problem is about pyinstaller how i can solve it

**Comment by htgoebel** [comment]
What is "veil"? What are "easy binder" and "binder"?

Beside this: Please node that you can not build executable for Windows on an Linux system (except if using wine).

**Comment by codewarrior0** [comment]
"Veil" is [Veil-Evasion](https://github.com/Veil-Framework/Veil-Evasion/), a security tool for testing and bypassing antivirus products.

This issue should probably be reported with them first.

**Comment by cacaocaca** [comment]
I have already reported but dont hav solve solution https://github.com/Veil-Framework/Veil-Evasion/issues/369#issuecomment-231428092 update me if i can solve it please

**Comment by cacaocaca** [comment]
You can solve it in these days ?

**Comment by cacaocaca** [comment]
Some answers to solve this problem exists ?

**Comment by codewarrior0** [comment]
Not our problem. See #2056

**Comment by cacaocaca** [comment]
You wouldn't believe how i m so happy .. Thanks for your time and thanks for update me really.

**Comment by cacaocaca** [comment]
Something don't work still i have tested just now https://github.com/Veil-Framework/Veil-Evasion/issues/375 but thanks i hope Chris solve it .

**Comment by cacaocaca** [comment]
I have solve https://github.com/Veil-Framework/Veil-Evasion/issues/375#issuecomment-234713611
