### ISSUE TITLE
"Looking for dynamic libraries" for a long time with pyinstaller 3.2

### ISSUE THREAD

**Issue by xiangxw** [pyinstaller/pyinstaller#2092]
Recently, I updated pyinstaller from 2.1 to 3.2.
Then.
![1](https://cloud.githubusercontent.com/assets/1129415/16718282/2ccdfe04-4751-11e6-9448-b7bc05e08579.png)

No problem with pyintaller 2.1.
win7
python 2.7.10
pyqt5

**Comment by stephenrauch** [comment]
Dup of #2022

**Comment by xiangxw** [comment]
oh. thanks
