### ISSUE TITLE
New Appveyor failures: Access is denied

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2100]
[Current builds](https://ci.appveyor.com/project/matysek/pyinstaller/build/1189) fail on Appveyor again:

> WindowsError: [Error 5] Access is denied: 'c:\\users\\appveyor\\appdata\\local\\temp\\1\\pip-zxu3jg-uninstall\\python27\\scripts\\pip.exe

**Comment by bjones1** [comment]
I assume this is because of the [Appveyor update](https://www.appveyor.com/blog/2016/07/16/migration-to-rackspace). Or because Appveyor just can't run for long without failing for some bizarre reason...

I have a commit that seems to fix this, Now AppVeyor dies trying to compile numpy...

**Comment by bjones1** [comment]
I'm struggling to fix some Appveyor weirdness. My attempts are at https://github.com/bjones1/pyinstaller/tree/appveyor-fix, with results at https://ci.appveyor.com/project/bjones1/pyinstaller/history. Any help is welcome!

Progress:
- The access denied error is fixed.
- I've updated some of the Appveyor scripts.
- I'm using @stephenrauch's Pillow fix to work around those problems.
- I'm using the `-U` flag with `pip install` to make sure we're using the latest version of all packages.

Problems:
- I don't understand why some wheels I can see on PyPI don't get installed. For example, [Pillow 3.3.0](https://pypi.python.org/pypi/Pillow/3.3.0) lists `Pillow-3.3.0-cp35-cp35m-win32.whl`, but Python 3.5 doesn't seems to use this. Why?
- Pandas complains `non-existing path in 'numpy\\distutils': 'site.cfg'` on Python 3.5, then tries and fails to build numpy from source. It's happy for all other Python versions. Why?
- CherryPy is failing on Travis and Appveyor, making it a separate issue, and needs fixing.
- lxml 3.3.4 installs fine, but 3.6.0 (the latest) doesn't, and tries building from source. For now, we can just specify the lxml version.

**Comment by bjones1** [comment]
Fixes in #2105.
