### ISSUE TITLE
sys.argv and wildcards

### ISSUE THREAD

**Issue by kotlet-schabowy** [pyinstaller/pyinstaller#2102]
Hi,

I wonder how people solve this issue:

following files are in current directory:
n_1.txt
n_2.txt
b_1.txt

the script is as follows:
```
import sys
print(sys.argv)
```

unfrozen:
```
J:\>python test.py -o n_?.txt
sys.argv: ['test.py', '-o', 'n_?.txt']

J:\>python test.py -o b_?.txt
sys.argv: ['test.py', '-o', 'b_?.txt']
```

frozen:
```
J:\>test.exe -o n_?.txt
sys.argv: ['test', '-o', 'n_1.txt', 'n_2.txt']

J:\>test.exe -o b_?.txt
sys.argv: ['test.py', '-o', 'b_?.txt']
```

How to prevent this file name extraction in the frozen case? My usecase expects the unfrozen behaviour. When script is frozen it does not work.

#######################
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec 5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32

pip show pyinstaller
Metadata-Version: 1.1
Name: PyInstaller
Version: 3.1.1

**Comment by codewarrior0** [comment]
Unlike UNIX shells, the Windows command shell `cmd.exe` does not expand wildcards. A windows console application must explicitly request wildcard expansion. We do not request wildcard expansion, so I wonder why we are getting it...?

Aha! MinGW will automatically expand wildcards (presumably to be more like UNIX) - this can be disabled by defining a global variable: http://mingw-users.1079350.n2.nabble.com/Windows-where-is-the-function-setargv-defined-td7582536.html

**Comment by codewarrior0** [comment]
I'm not sure we should disable wildcard expansion globally. Other users may expect it, wanting their cross-platform app to behave similarly on both UNIX and Windows despite the differences in the command shells on the two platforms. The flexible thing to do might be to add another Windows-specific option to the bootloader and the EXE build step to select whether wildcards in argv are expanded, and explicitly call [`__wgetmainargs`](https://msdn.microsoft.com/en-us/library/ff770599.aspx) to get the args without wildcard expansion after loading the bootloader options from the archive.

(Another difference on Windows is that argv is provided by the OS as a single string, and the program is responsible for splitting it into a string array, parsing quotes, etc. In our case, and the case of most Windows console programs, this CRT function is called to bridge the gap between what the Windows OS gives you and what the C standard says the program should get.)

**Comment by kotlet-schabowy** [comment]
Hi, I do not want you to break any UNIX or other compability. But in my case: whatever.exe -o n*  asks whatever.exe, which is a frozen python script, to boil water (for stupid example). Why there is code which does not pass n* as value to option -o but instead it searches in the current directory for file names matching n*?
Yes I know my example is stupid but I hope you get the point.
So your proposal to have some option to turn off this file name extraction is most welcome.

**Comment by htgoebel** [comment]
IMO we should follow the [Principle of Least Surprise](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

* On Unix, the wildcard expansion is done by the shell, so the program always sees the list of filenames. This is what the user and the programmer expect.
* On Windows this seams to be different (given what is written above): Nobody expects the wildcards to be expanded. So a Python program on Windows needs to expand the arguments itself.

This behaviour should not differ whether the the program is frozen or not.

So I suggest staying with the platform-specific behaviour here, which means: Do *not* expand wildcards on  Windows, even when building with mingw.

(Side-note: IMHO the windows way of doing this is crap. But this is how Windows works.)

**Comment by stephenrauch** [comment]
@htgoebel 

Unfortunately the Window's way is actually the PC-DOS way.  And in the beginning, PC-DOS did not even have hierarchical directories. Ouch.

Let me second the notion that having the frozen app expand the command line, when this is not the behavior of the unfrozen app, is unwelcome behavior.

**Comment by codewarrior0** [comment]
> This behaviour should not differ whether the the program is frozen or not.
> having the frozen app expand the command line, when this is not the behavior of the unfrozen app, is unwelcome behavior.

I agree, this is the most important bit.

Turning off wildcard expansion on Windows should be a simple one-line change, then. Let me just make sure it works....

**Comment by codewarrior0** [comment]
Done!
