### ISSUE TITLE
pyinstaller fails to start in Windows 10

### ISSUE THREAD

**Issue by mikhaelsk** [pyinstaller/pyinstaller#2103]
My Environment:
- Windows 10 
- Visual Studio 2015
- Python 35-32
after making "pip install pyinstaller " install finishes successfully, but the program does not start with reason "failed to create process".
I have read the manual "how to install", and i even checked that my steps are correct (because the same steps successfully start pyinstaller in Windows 7).

**Comment by htgoebel** [comment]
This looks like a problem in your Python setup.

**Comment by mikhaelsk** [comment]
hmm/ Ok, I'll try to setup it in a clean Win10

**Comment by mikhaelsk** [comment]
I installed everything in a clean OS, and pyinstaller began to work!
Thank you for advice!

**Comment by outofthink** [comment]
I resolved it!
change 
`#!c:\python 3.5\python.exe`
to
`#!"c:\python 3.5\python.exe"`
in yourpythonhome/scripts/pyinstaller-script.py

**Comment by dee1337** [comment]
fresh win10 install, clean python 3.5 - outofthink posted the solution that worked for me
