### ISSUE TITLE
cherrypy >= 6.1.0 fails tests

### ISSUE THREAD

**Issue by jstewmon** [pyinstaller/pyinstaller#2109]
From the cherrypy [changelog]:

```
6.1.0
-----

* Combined wsgiserver2 and wsgiserver3 modules into a
  single module, ``cherrypy.wsgiserver``.
```

[changelog]: https://github.com/cherrypy/cherrypy/blob/master/CHANGES.txt

**Comment by bjones1** [comment]
@jstewmon, wonderful! Thanks so much. That should make fixing the hook trivial. Thanks so much! Feel free to fix this, or I can when I have a minute...(out of the office right now)...
