### ISSUE TITLE
Pyinstaller does not include the zeep module

### ISSUE THREAD

**Issue by js1972** [pyinstaller/pyinstaller#2120]
I have a python 3.5 script that includes zeep as follows:

```
from zeep import Client
from zeep.transports import Transport
from datetime import datetime, date, timedelta
import argparse
from payline_types import RecordType01, RecordType02, RecordType03
import requests
```
When I build an exe it always fails with this error:
```
Traceback (most recent call last):
  File "timesheet_reader.py", line 54, in <module>
  File "site-packages\zeep\transports.py", line 23, in __init__
  File "site-packages\zeep\utils.py", line 42, in get_version
  File "site-packages\pkg_resources\__init__.py", line 943, in require
  File "site-packages\pkg_resources\__init__.py", line 829, in resolve
pkg_resources.DistributionNotFound: The 'zeep' distribution was not found and is required by the application
Failed to execute script timesheet_reader
```

I've used the following command:
```
pyinstaller --clean -F timesheet_reader.py
```
I've also tried without the -F to get the directory version - no difference.

Any ideas? I have tried adding --hidden-import=zeep and also --hidden-import=zeep.Client and --hidden-import=zeep.transports. Makes no difference....

I've also tried calling pyinstaller and specify a hook:
--additional-hooks-dir .
With a hook file referencing zeep.
Still no difference.

Zeep's dependency (lxml) does seem to be picked up and included though... But the pure python files that make up zeep do not.

I'm testing this on Windows with a fresh install of Python 3.5.

**Comment by js1972** [comment]
I should add I installed the latest version of pyinstaller from the master branch...

**Comment by stephenrauch** [comment]
Can you post the entirety of a minimum app that will duplicate this?

**Comment by js1972** [comment]
Here's a small sample:

First install zeep with:
```
pip install zeep
```

Then save this into a simple python script. When you run it, it makes a SOAP call to a web service and should display the number 62.137 to the console:
```
from zeep import Client

client = Client("http://www.webservicex.net/ConvertSpeed.asmx?WSDL")
print(client.service.ConvertSpeed(100, "kilometersPerhour", "milesPerhour"))
```

**Comment by stephenrauch** [comment]
Just did a [Pull request](https://github.com/stephenrauch/pyinstaller/commit/86eed37ccbbdeaed29b7364654db89fb4062dec0) with a hook that resolves this.  The CI is not cooperating, but the hook should be fine.

**Comment by js1972** [comment]
Thankyou for that Stephen. I've cloned you PR and installed it. Doesn't complain about the zeep module now but instead I get the following error:
```
PS C:\Users\Administrator\dyflex-timesheets-master\dist> .\test_zeep.exe
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-packages\PyInstaller\loader\pyimod03_impo
rters.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 2958, in <module>
  File "site-packages\pkg_resources\__init__.py", line 2944, in _call_aside
  File "site-packages\pkg_resources\__init__.py", line 2986, in _initialize_master_working_set
UnboundLocalError: local variable 'dist' referenced before assignment
Failed to execute script pyi_rth_pkgres
```

Where test_zeep.exe above was built with:
```
pyinstaller --clean -F test_zeep.py
```
test_zeep.py is just that basic sample python file I copied in above... No errors are raised from the execution of pyinstaller.

Is there something specific that needs to be done with your PR before it can be used? Anything need to be built, etc?

**Comment by stephenrauch** [comment]
So I tested on Python 2.7 and windows 7.  Works fine.  Unfortunately I failed to get everything installed for either python 3.4 or 3.5.  Somethings are stupid difficult on windows.  Mostly because of the compiler situation.  Pure python modules are much less of a problem.  And since I use python 2.7 for basically everything, there is not currently much impetus to fix these things in my environment.  So, I am unlikely to be much help...

**Comment by js1972** [comment]
No worries Stephen - thanks for your efforts anyway... Looks like this is full of holes on both Windows and Mac. My program is so simple I'll just port to another language.   ;-)

**Comment by stephenrauch** [comment]
So I got this going in python 3.4 on windows 7 and that also work fine:

```
C:>zeep-test\dist\zeep-test.exe
62.137
```

Which version of windows and which distribution of python 3.5 are you using?

**Comment by js1972** [comment]
Testing on a Windows server 2012 R2 64 bit in an AWS instance.
The official python dist from https://www.python.org/downloads/windows/ -> 3.5.2

Is there something necessary as a build step prior to using your PR? I just cloned it and installed with `pip install --upgrade -e .`

**Comment by stephenrauch** [comment]
how did install lxml?  when I do pip install zeep it dies trying to build lxml...  I assume this is due to a missing library.  one down rev of lxml on pypi has a python 3.4 binary, but I could find nothing for 3.5.  so more magic than I want to chase, but if you the recipe...

**Comment by js1972** [comment]
Ok no worries. Really appreciate your time looking into this Stephen.
1. Installed Python 3.5.2 from here https://www.python.org/downloads/release/python-352/
2. Choose Windows x86-64 executable installer Windows for AMD64/EM64T/x64, not Itanium processors - ensure you tick the box to add python to the PATH
3.  The above installs an old pip so I updated it with `pip install --upgrade pip`
4. Install wheel so as to get a matching version of lxml: `python -m pip install wheel`
5. Download lxml from here https://dl.dropboxusercontent.com/u/7546923/lxml-3.6.1-cp35-cp35m-win_amd64.whl (I just saved it on dropbox - originall from http://www.lfd.uci.edu/~gohlke/pythonlibs/)
6. python -m pip install lxml-3.6.1-cp35-cp35m-win_amd64.whl (install the file just downloaded)
7. Then install zeep as per normal `pip install zeep`
8. Then run the test program...

**Comment by stephenrauch** [comment]
Thanks, the missing magic was: ```python -m pip install wheel```

But sadly, it still works for me...  One diff is that I have a 32 bit python 3.5

```
"C:\Program Files (x86)\Python35-32\python.exe" C:/Users/stephen/Documents/github/pyinstaller/pyinstaller.py --clean -F C:\Users\stephen\Documents\src\test_scripts\zeep-test.py
838 INFO: PyInstaller: 3.3.dev0+g527776d
838 INFO: Python: 3.5.1
838 INFO: Platform: Windows-7-6.1.7601-SP1
844 INFO: wrote C:\Users\stephen\Documents\github\pyinstaller\zeep-test\zeep-test.spec
```

But that exe worked fine:

```
>zeep-test\dist\zeep-test.exe
62.137
```

So I have still failed to duplicate.

**Comment by js1972** [comment]
Wow. That's even more painful when it can't be duplicated. The only other thing I did was install visual studio community edition 2015 before I started to install Python and the other steps I mentioned before. 
I might soon up another fresh Windows instance and this time install 32bit Python and see....
This sort of stuff epitomises everything that is wrong with computers.  ;-)

**Comment by js1972** [comment]
Well tried again with a fresh windows instance and used 32bit python. pyinstaller then gives a whole raft of different issues. I'm done with it. It is just not stable. 
Thankyou very much for assisting though. ;-)
