### ISSUE TITLE
if your scripts involve importing of vtk, modify the pyinstaller/hooks/hook-vtkpython.py to pyintaller/hooks/hook-vtk.py

### ISSUE THREAD

**Issue by HawkRong** [pyinstaller/pyinstaller#2129]
I use vtk carried along with pythonxy environment. Simply changing the 'hook-vtkpython.py' to 'hook-vtk.py' solved all my issues concerning vtk importing.

**Comment by ghuijs** [comment]
For VTK release 8.2, I have updated the hook-vtk.py file with the hiddenimports below.
This seems to work well for my project including VTK and QT.
    hiddenimports = ['vtkmodules','vtkmodules.all','vtkmodules.qt.QVTKRenderWindowInteractor','vtkmodules.util','vtkmodules.util.numpy_support']

For completeness, to also get OSPRAY within VTK, I have used:
--add-binary 'libospray_module_ispc.so' --add-binary 'libembree3.so.3'

(and used [staticx](https://github.com/JonathonReinhart/staticx) to port to an older system)

**Comment by CesMak** [comment]
Thank you so much this works:

hiddenimports = ['vtkmodules','vtkmodules.all','vtkmodules.qt.QVTKRenderWindowInteractor','vtkmodules.util','vtkmodules.util.numpy_support']

**Comment by smerkousdavid** [comment]
For anyone else that encounters similar issues with vtk + wxPython don't forget to add 'vtkmodules.wx' and not just 'vtk.wx'. Took a bit of debugging to find that out

**Comment by bwoodsend** [comment]
I'm going to close this as this issue is superseeded by https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/327.
