### ISSUE TITLE
Esky support for pyinstaller

### ISSUE THREAD

**Issue by timeyyy** [pyinstaller/pyinstaller#2133]
Esky is an autoupdate framework for various python freezers. However pyinstaller seems to be king but it isn't supported.

> There's no PyInstaller support at the moment, but I would be very interested in getting it added - it is a frequently requested feature.

> The reason it was not added previously is that PyInstaller uses a custom archive format, and has not traditionally provided an API for reading/writing that format. 

Has this changed?

**Comment by JMSwag** [comment]
[PyUpdater](http://www.pyupdater.org) is a viable option if nothing has changed.
