### ISSUE TITLE
Weird focus behavior when opening pyinstaller app bundle on OS X

### ISSUE THREAD

**Issue by johncsnyder** [pyinstaller/pyinstaller#2134]
When I open a pyinstaller app bundle on OS X, the focus goes away from finder (or whatever app has current focus when you open the app), then back, and then finally to the pyinstaller app. Here's a gif:

![temp](https://cloud.githubusercontent.com/assets/9882099/17431006/dd860cd2-5af7-11e6-8e58-82d1eefd8426.gif)

Not a huge issue, but a bit bothersome. I'm not sure where this behavior is originating, whether its pyinstaller, pyqt, or qt itself. However, it doesn't happen if i start the app from the terminal. Is there an easy fix, or this behavior is unavoidable?

_system info:_
python 3.4.4 (anaconda), OS X 10.11.5, qt 5.4.1, pyqt 5.4.1, pyinstaller 3.3.dev0+ga909f1a

_minimal example:_
`temp.py`

```
if __name__ == '__main__':
    import sys
    from PyQt5.QtWidgets import QApplication, QMainWindow
    app = QApplication(sys.argv)
    window = QMainWindow()
    window.show()
    sys.exit(app.exec_())
```

Run `pyinstaller --windowed temp.py`, and open `dist/temp.app`

**Comment by tallforasmurf** [comment]
Can not duplicate. `open dist/test.app` causes little window to come to the front right away.

Yosemite 10.10.5, PyInstaller 3.2, Python 3.4.3
