### ISSUE TITLE
Error running the exe file in Windows "Failed to execute script pyi_rth_pkgres"

### ISSUE THREAD

**Issue by ebonat** [pyinstaller/pyinstaller#2137]
Hi,

I have created a simple Python program including the following packages:
```
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

if __name__ == '__main__':
    print("Hi!")
```

I have created the installation package using the following command line:

`pyinstaller --onedir --name=appname --windowed "C:\appname.py"`

The required folders (build and dist) and the spec file are created properly with no errors. When I run the appname.exe file I got the error "Failed to execute script pyi_rth_pkgres".

I'm using the following now:

- Anaconda3 4.1.1.64-bit
- Python 3.5.2
- PyInstaller 3.2
- Windows 10 64-bit

Any help is very appreciated. Feel free to contact me at any time you need.

Thank you,

[Edit by htgoebel: Removed useless boilerplate stuff.]

**Comment by cpett** [comment]
I am seeing the same issue. With Anaconda3 4.0 and Windows 8.1.

I have tried various fixes like [this](http://stackoverflow.com/questions/29109324/pyinstaller-and-pandas), but to no avail.

I am now trying to package using the developer version. It's a terribly frustrating error.

**Comment by cpett** [comment]
Update: The developer branch seems to have worked for the very basic script I wrote for testing. I will try again on my real application tomorrow

**Comment by ebonat** [comment]
Hi cpett,

Thank you for your response. I feel very bad too! Is anyone testing the
PyInstaller releases before putting in production for download? This is
very bad for sure. I hope to get a simple response from the PyInstaller
Team VERY SOON!

Thanks again,

Ernest Bonat, Ph.D.
Senior Software Engineer | Senior Data Scientist
Visual WWW, Inc. | President and CEO
115 NE 39th Avenue | Hillsboro, OR 97124
Cell: 503.730.4556 | Email: ernest.bonat@gmail.com

*The content of this email is confidential. It is intended only for the use
of the persons named above. If you are not the intended recipient, you are
hereby notified that any review, dissemination, distribution or duplication
of this communication is strictly prohibited. If you are not the intended
recipient, please contact the sender by reply email and destroy all copies
of the original message.*

**Comment by ebonat** [comment]
Hey cpett,

Try it and let me know. I did test it with PyQT 4 and it works very well.
I'll try it this week with PyQT 5. Let you know!

Thank you,

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Scientist

**Comment by cpett** [comment]
Ebonat,

The developer branch worked just fine for my error. I would recommend giving that a try if you're okay/able to use developer branches.

Good luck!

**Comment by ebonat** [comment]
Hi cpett,

Would you explain me how to use the developer branches? I need to know how
do run the PyInstaller for it!

Thanks

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Scientist

**Comment by htgoebel** [comment]
Please revere to the wiki: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-its-a-bug

**Comment by cpett** [comment]
@ebonat Ebonat, here's what I did to get the developer branch running (I'm sure there are better ways):

1. Remove PyInstaller `pip uninstall pyinstaller`
2. Clone (download the zip if you don't have git) the 'develop' branch from [github](https://github.com/pyinstaller/pyinstaller)
     a. There should be a green button on the right that says 'clone or download'
3. Navigate to the cloned file (or unzip it if not using git)
4. Make sure you are in the directory with `setup.py`
5. Run `python setup.py install`

Hopefully that helps!

**Comment by htgoebel** [comment]
@cpett I suggest reading all of [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) which shows a much easier way.

**Comment by ebonat** [comment]
Thanks cpett!

Hi,

I have fixed this problem by following the steps:

1. Uninstall the PyInstaller downloaded from http://www.pyinstaller.org/
pip install pyinstaller

2. Install the PyInstaller from the GitHub developer repository
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip

Still not clear to me why the main site http://www.pyinstaller.org/ does not have the latest release? 

Thanks

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Scientist

**Comment by dzimbeck** [comment]
Dev version does not fix the problem, please reopen

**Comment by m1lhaus** [comment]
Same problem here. Trying to build script using pandas and openpyxml. Using latest dev version of Pyinstaller.

**Comment by betterenvi** [comment]
Same. Dev version does not fix the problem.

**Comment by ebonat** [comment]
OK! This is very clear now.

Who is to going to fix this bug! We need to have this fix as soon as
possible!

Thanks

Ernest Bonat, Ph.D.
Senior Software Engineer | Senior Data Scientist
Cell:503.730.4556 | Email:ernest.bonat@gmail.com

*The content of this email is confidential. It is intended only for the use
of the persons named above. If you are not the intended recipient, you are
hereby notified that any review, dissemination, distribution or duplication
of this communication is strictly prohibited. If you are not the intended
recipient, please contact the sender by reply email and destroy all copies
of the original message.*

**Comment by pbsds** [comment]
I'm getting this error when trying to include either numpy or pygame

**Comment by arjunsharma321** [comment]
Problem solved he guys

Locate PyInstaller folder..\hooks, e.g. C:\Program Files\Python\Lib\site-packages\PyInstaller\hooks.

Create file hook-pandas.py with contents (or anything similar based on your error):

hiddenimports = ['pandas._libs.tslibs.timedeltas']

Run pyinstaller -F my_app.py.

**Comment by htgoebel** [comment]
@arjunsharma321 We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by arjunsharma321** [comment]
Create file hook-pandas.py in your C:\Program Files\Python\Lib\site-packages\PyInstaller\hooks
add these lines 
hiddenimports = ['pandas._libs.tslibs.timedeltas']
or else library that is compile source error
showing while run exe such as numpy, pip or else update error

run your installer Eg: Run pyinstaller -F  my_app.py

**Comment by htgoebel** [comment]
@arjunsharma321 This is not a pull-request, it it?!

**Comment by crifan** [comment]
thanks to @ebonat and @cpett , same problem and fixed by:
```shell
pip uninstall pyinstaller
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

**Comment by ebonat** [comment]
hi crifan, thank you very much!
