### ISSUE TITLE
Tkinter reproducible ImportError even with --hidden-import

### ISSUE THREAD

**Issue by UgoT** [pyinstaller/pyinstaller#2139]
_Python version:_ 2.7.10 (Installed with current Python(x,y), 32bit)
_PyInstaller Version_: 3.2
_Platforms_: Windows 7 32bit and Windows 10 64bit
_Matplotlib version_: 1.5.1  (only used in the second example)

**First example:**
```
### File test1.py starts below ###
#!python
import sys
if sys.version_info.major==2:
    # Python2
    from Tkinter import *
else:
    # Python3
    from tkinter import *
### END of test1.py ###
```

The code runs without any issue.
Pyinstaller creates the executable without problems:
`pyinstaller -D --hidden-import=Tkinter test1.py`
...
During the execution of PyInstaller these WARNINGs appear:
_11045 WARNING: Attempted to add Python module twice with different upper/lowercases: Tkinter
11045 INFO: Including run-time hook 'pyi_rth__tkinter.py'
11061 WARNING: Attempted to add Python module twice with different upper/lowercases: Tkinter_

When I run the executable I get the error
```
dist\test1\test1.exe
Traceback (most recent call last):
  File "test1.py", line 5, in <module>
    from Tkinter import *
ImportError: No module named Tkinter
Failed to execute script test1
```

The same issue happens without the argument `--hidden-import=Tkinter` while running PyInstaller.

In principle the code for Python 3 should never run, and I was not expecting an interaction with PyInstaller. But everything goes smoothly if I comment line 7:
```
### File test1_ok.py starts below ###
#!python
import sys
if sys.version_info.major==2:
    # Python2
    from Tkinter import *
else:
    # Python3
    pass # from tkinter import *
### END of test1_ok.py ###
```

`pyinstaller -D --hidden-import=Tkinter test1_ok.py`
... 
Here I do not see the WARNINGs on the lowercase/uppercase Tkinter.
`dist\test1\test1.exe`
No error here!

I inspected the two executables, to see which module is there.
The bad one:
```
pyi-archive_viewer dist\test1\test1.exe
 pos, length, uncompressed, iscompressed, type, name
[(0, 170, 234, 1, 'm', u'struct'),
 (170, 1157, 2732, 1, 'm', u'pyimod01_os_path'),
 (1327, 3946, 11188, 1, 'm', u'pyimod02_archive'),
 (5273, 6043, 19096, 1, 'm', u'pyimod03_importers'),
 (11316, 1557, 4529, 1, 's', u'pyiboot01_bootstrap'),
 (12873, 401, 636, 1, 's', u'pyi_rth__tkinter'),
 (13274, 163, 226, 1, 's', u'test1'),
 (13437, 1090632, 1090632, 0, 'z', u'out00-PYZ.pyz')]
? Q
```
And the good one:
```
pyi-archive_viewer dist\test1_ok\test1_ok.exe
 pos, length, uncompressed, iscompressed, type, name
[(0, 170, 234, 1, 'm', u'struct'),
 (170, 1157, 2732, 1, 'm', u'pyimod01_os_path'),
 (1327, 3946, 11188, 1, 'm', u'pyimod02_archive'),
 (5273, 6043, 19096, 1, 'm', u'pyimod03_importers'),
 (11316, 1557, 4529, 1, 's', u'pyiboot01_bootstrap'),
 (12873, 401, 636, 1, 's', u'pyi_rth__tkinter'),
 (13274, 159, 207, 1, 's', u'test1_ok'),
 (13433, 1141544, 1141544, 0, 'z', u'out00-PYZ.pyz')]
? Q
```
But I could not figure out any difference at a first glance.

**Second example:**
This one is trickier, involving also matplotlib.
**The code of test2.py compiles with pyinstaller, but the executable gives the same ImportError as above at runtime.**
In order to fix it, it is enough to remove the line with `import matplotlib`. But it is also possible to fix the issue by switching the two lines, see list test2_ok.py below.

```
### File test2.py starts below ###
#!python2
from Tkinter import *
import matplotlib
### END of test2.py ###
```
Here is the error message:
```
dist\test2\test2.exe
Traceback (most recent call last):
  File "test2.py", line 2, in <module>
    from Tkinter import *
ImportError: No module named Tkinter
Failed to execute script test2
```

By switching the two lines you get this working program:
```
### File test2_ok.py starts below ###
#!python2
import matplotlib
from Tkinter import *
### END of test2_ok.py ###
```
Note that now I got the WARNING about the double attempt to import Tkinter even with test2_ok.py, but the final executable runs smoothly.

**Comment by stephenrauch** [comment]
Have you tried this with dev tip?  This looks a  lot like a bug that has been resolved.

From the wiki under ['How to Report Bugs'](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs):

*Please try latest development version. Simply use pip install:*

```
https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

*to install the latest git version.*

**Comment by UgoT** [comment]
Trying now with the development version of pyinstaller (Version 3.3.dev0+d3e0cb4).
Both test1.py and test2.py now work!

I was a bit conservative on the update on the development version and I did not try it before.
I hope I can distribute my 4000-line python code among my colleagues!
