### ISSUE TITLE
again: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by neneok** [pyinstaller/pyinstaller#2142]
I have a python application using `matplotlib` and `QT` and I ran into a problem similar to #1289.
Because #1289 is supposed to have been solved, I installed the development version of `pyinstaller` and copied the sample program `plottest.py` of #1289 :

```
import matplotlib.pyplot as plt

x = [0, 1, 2, 3, 4]
y = [0, 1, 4, 9, 16]

plt.plot(x, y)
plt.show()
```

The sample program runs succesfully from the command line
`> python plottest.py`
However, the `pyinstaller` build fails with the same error (full --debug output in the attached file):

`RuntimeError: maximum recursion depth exceeded while calling a Python object`

To capture the output, I ran the command from the powershell_ise. Powershell adds some extra output (lines 2-4), compared to a regular command shell. The rest of the output is the same in both shells.
[output.txt](https://github.com/pyinstaller/pyinstaller/files/413883/output.txt)

I followed the guidelines in:

   https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

i.e. remove the config and cache files, install the latest release (3.2) and the problem persisted. Next, I installed the development release (3.3.dev0+d3e0cb4), but no improvement.

My latest environment is as follows:
- Windows 7
- WinPython-64bit-3.4.4.3Qt5 installation from http://winpython.github.io/
- a few pip updates resulting in the following installation

```
> python --version
Python 3.4.4
> pip list
adodbapi (2.6.0.7)
alabaster (0.7.8)
args (0.1.0)
astroid (1.4.7)
astroML (0.3)
Babel (2.3.2)
backports-abc (0.4)
baresql (0.7.3)
bcolz (1.1.0)
beautifulsoup4 (4.4.1)
blaze (0.10.1)
blosc (1.3.3)
bloscpack (0.9.0)
bokeh (0.11.1)
boto3 (1.3.1)
botocore (1.4.36)
Bottleneck (1.1.0)
bqplot (0.7.1)
brewer2mpl (1.4.1)
certifi (2016.2.28)
cffi (1.7.0)
click (6.6)
clint (0.5.1)
cloudpickle (0.2.1)
colorama (0.3.7)
CommonMark (0.5.4)
cvxopt (1.1.7)
cx-Freeze (4.3.4)
cycler (0.10.0)
cyordereddict (1.0.0)
Cython (0.24.1)
cytoolz (0.8.0)
dask (0.10.1)
datashape (0.5.2)
db.py (0.4.4)
decorator (4.0.10)
distributed (1.11.2)
docopt (0.6.2)
docrepr (0.1.0)
docutils (0.12)
emcee (2.1.0)
entrypoints (0.2.2)
fasteners (0.14.1)
Flask (0.11.1)
Flask-Cors (2.1.2)
formlayout (1.1.0)
future (0.15.2)
geopy (1.11.0)
greenlet (0.4.10)
guidata (1.7.5)
guiqwt (3.0.2)
h5py (2.6.0)
holoviews (1.6.0)
html5lib (0.9999999)
husl (4.0.3)
idlex (1.13)
imagesize (0.7.1)
ipykernel (4.3.1)
ipyleaflet (0.2.1)
ipyparallel (5.1.1)
ipython (5.0.0)
ipython-genutils (0.1.0)
ipython-sql (0.3.7.1)
ipywidgets (5.2.2)
isort (4.2.5)
itsdangerous (0.24)
jedi (0.9.0)
Jinja2 (2.8)
jmespath (0.9.0)
joblib (0.10.0)
jsonschema (2.5.1)
julia (0.1.1)
jupyter (1.0.0)
jupyter-client (4.3.0)
jupyter-console (5.0.0)
jupyter-core (4.1.0)
Keras (1.0.6)
Lasagne (0.2.dev1)
lazy-object-proxy (1.2.2)
llvmlite (0.12.1)
lmfit (0.9.3)
locket (0.2.0)
lxml (3.6.0)
Markdown (2.6.6)
MarkupSafe (0.23)
matplotlib (1.5.2)
mccabe (0.4.0)
mingwpy (0.1.0b3)
mistune (0.7.3)
mkl-service (1.1.2)
monotonic (1.1)
mpld3 (0.2)
mpmath (0.19)
msgpack-python (0.4.7)
multipledispatch (0.4.8)
mysql-connector-python (2.0.4)
nbconvert (4.2.0)
nbformat (4.0.1)
nbsphinx (0.2.8)
netCDF4 (1.2.4)
networkx (1.11)
nltk (3.2.1)
nose (1.3.7)
notebook (4.2.1)
numba (0.27.0)
numexpr (2.6.1)
numpy (1.11.1+mkl)
numpydoc (0.6.0)
oct2py (3.5.9)
odo (0.5.0)
pandas (0.18.1)
pandas-datareader (0.2.0)
param (1.4.1)
partd (0.3.4)
patsy (0.4.1)
pefile (2016.3.28)
pep8 (1.7.0)
pg8000 (1.10.5)
pickleshare (0.7.2)
Pillow (3.3.0)
pip (8.1.2)
pkginfo (1.3.2)
prettytable (0.7.2)
prompt-toolkit (1.0.3)
psutil (4.3.0)
ptpython (0.35)
PuLP (1.6.1)
py (1.4.31)
PyAudio (0.2.9)
pybars3 (0.9.1)
pycodestyle (2.0.0)
pycparser (2.14)
pyflakes (1.2.3)
Pygments (2.1.3)
PyInstaller (3.3.dev0+d3e0cb4)
pylint (1.6.1)
pymc (2.3.6)
pymc3 (3.0)
PyMeta3 (0.5.1)
pymongo (3.2.2)
pyodbc (3.0.10)
PyOpenGL (3.1.1)
pyparsing (2.1.5)
pyqtgraph (0.9.10)
pyserial (3.1.1)
pystache (0.5.4)
pytest (2.9.1)
python-dateutil (2.5.3)
python-hdf4 (0.9)
pythonnet (2.1.0)
PythonQwt (0.5.5)
pytz (2016.4)
pywin32 (220.1)
PyYAML (3.11)
pyzmq (15.3.0)
QtAwesome (0.3.3)
qtconsole (4.2.1)
QtPy (1.1.1)
recommonmark (0.4.0)
redis (2.10.5)
reportlab (3.3.0)
requests (2.10.0)
requests-toolbelt (0.6.2)
rope-py3k (0.9.4.post1)
rpy2 (2.7.8)
Rx (1.5.2)
s3fs (0.0.6)
scikit-image (0.12.3)
scikit-learn (0.17.1)
scikit-neuralnetwork (0.7)
scilab2py (0.6)
scipy (0.18.0rc2)
seaborn (0.7.1)
setuptools (25.1.6)
simplegeneric (0.8.1)
simplejson (3.8.2)
six (1.10.0)
snowballstemmer (1.2.1)
Sphinx (1.4.5)
sphinx-rtd-theme (0.1.9)
spyder (3.0.0.dev0)
SQLAlchemy (1.0.14)
sqlite-bro (0.8.11)
sqlparse (0.1.19)
statsmodels (0.8.0rc1)
sympy (1.0)
tables (3.2.3)
tblib (1.3.0)
Theano (0.8.2)
toolz (0.8.0)
tornado (4.4)
traitlets (4.2.2)
twine (1.7.4)
twitter (1.17.1)
wcwidth (0.1.7)
Werkzeug (0.11.10)
wheel (0.29.0)
widgetsnbextension (1.2.6)
win-unicode-console (0.5)
winpython (1.6.20160625)
wordcloud (1.2.1)
wrapt (1.10.8)
xarray (0.7.2)
xlrd (1.0.0)
XlsxWriter (0.9.3)
zarr (1.0.0)

```

**Comment by neneok** [comment]
After quite some experimentation, I found the following _workaround_. Create the `plottest.spec` file and the `plottest.exe` executable in separate steps. Before creating the executable, edit the .spec to increase the maximum recursion depth just before the analysis phase:
```
import sys  % this line added
sys.setrecursionlimit(10000)  % this line added

a = Analysis(['plottest.py'],
         ...
```
This produces a 200 Mb executable (which apparently is still missing some hidden imports, but this can be fixed).

It would be nice to either have this workaround documented or to fix/restructure the pyinstaller code, such that the `RuntimeError: maximum recursion depth exceeded while calling a Python object` will no longer occur.

**Comment by Evertvdw** [comment]
The solution above also prevented the recursion limit reached option, only the created Main.exe is not working for me. The generated `'warnMain'` contains 3000 lines of `'missing module ....'` lines, so something is certainly going wrong there. 

I use WinPython-64bit-3.4.4.3Qt5 and have a project using PyQt5, pyqtgraph, and multiple UI_design files created with the QtDesigner. The project at this point is to big to break down what import or statement causes the generated .exe file to malfunction, but I guess it has something to do with this issue. 

When running the generated .exe I get the following error code:
`Error loading Python DLL: <PATH>\python34.dll (error code 126)`

Does anyone have any new solutions for this problem?

**Comment by Chaos99** [comment]
I probably suffer from the same error.

Windows 7
WinPython-64bit-3.5.2.2Qt5
pyinstaller 3.3.dev0+483c819 (installed today)

Stacktrace ends with \lib\ast calls in a seemingly endless loop of modulegraph calls. 

I have not broken this down to a specific import, as it seems to be a known problem after all.
It's not mathplotlib. pandas or QT fro me, at least not directly.
Full list of imports on request.

**Comment by kdre** [comment]
I am having the same issue with the latest git version (3.3.dev0) and also with version 3.2.1. 

The workaround by neneok worked for me, but I would prefer that I do not need a spec file...

**Comment by xoviat** [comment]
Guido has said not to use recursive algorithms in python. Also I don't think this involves the bootloader.

**Comment by htgoebel** [comment]
Of course this is a modulgraph issue, not a bootloader one.

**Comment by xoviat** [comment]
Duplicate #2426.

**Comment by htgoebel** [comment]
Closing as duplicate, since the is no use in having several tickets for the same issue.

**Comment by MariaLiljeroth** [comment]
> After quite some experimentation, I found the following _workaround_. Create the `plottest.spec` file and the `plottest.exe` executable in separate steps. Before creating the executable, edit the .spec to increase the maximum recursion depth just before the analysis phase:
> 
> ```
> import sys  % this line added
> sys.setrecursionlimit(10000)  % this line added
> 
> a = Analysis(['plottest.py'],
>          ...
> ```
> This produces a 200 Mb executable (which apparently is still missing some hidden imports, but this can be fixed).
> 
> It would be nice to either have this workaround documented or to fix/restructure the pyinstaller code, such that the `RuntimeError: maximum recursion depth exceeded while calling a Python object` will no longer occur.

THANK YOU! spent ages on this issue
