### ISSUE TITLE
IOError when executing compiled 

### ISSUE THREAD

**Issue by akbhat** [pyinstaller/pyinstaller#2144]
Issue with same Python module referred in #1346

Pyinstaller version = 3.1.1

from jnpr.junos.op.fpc import FpcHwTable
from jnpr.junos.op.fpc import FpcInfoTable

Just build the above two lines (--onefile) and run the executable. Traceback provided below

$ ./dist/a 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/jnpr/junos/op/fpc.py", line 7, in <module>
  File "site-packages/jnpr/junos/factory/__init__.py", line 33, in loadyaml
IOError: [Errno 2] No such file or directory: '/tmp/_MEI65S8TC/jnpr/junos/op/fpc.yml'
a returned -1

Do I need explicit instructions to include the .yml file in the frozen binary?

**Comment by akbhat** [comment]
Any updates on this?

**Comment by akbhat** [comment]
Can somebody help with this? Minimal example included to replicate issue.

**Comment by JMSwag** [comment]
https://pythonhosted.org/PyInstaller/spec-files.html#adding-files-to-the-bundle

**Comment by akbhat** [comment]
import pkgutil
help_bin = pkgutil.get_data('jnpr.junos.op', 'fpc.yml')
I have verified that print help_bin outputs the contents of the missing data file.

Is adding the above to the spec file sufficient or does help_bin then need to be passed to Analysis via datas? What is correct syntax to achieve this? I am suing the --onefile option.

**Comment by JMSwag** [comment]
You may need a [pyinstaller hook](https://pyinstaller.readthedocs.io/en/stable/hooks.html#understanding-pyinstaller-hooks). Check out the collect_data_files function.

[lib2to3 hook](https://github.com/pyinstaller/pyinstaller/blob/9dc28c0661f341a0a2fe90ca1c07ea2795939103/PyInstaller/hooks/hook-lib2to3.py)

**Comment by akbhat** [comment]
The collect_data_files solution worked. Thanks @JMSwag

**Comment by JMSwag** [comment]
@akbhat NP!
