### ISSUE TITLE
spec file always recreated

### ISSUE THREAD

**Issue by pbienst** [pyinstaller/pyinstaller#2145]
135 INFO: PyInstaller: 3.3.dev0+d3e0cb4
137 INFO: Python: 3.5.2
138 INFO: Platform: Windows-10-10.0.14393-SP0

If I edit a spec file manually, the next time I run pyinstaller it is recreated and I lose my changes...

**Comment by stephenrauch** [comment]
To use a spec file you need to change the command line to specify the ```.spec``` file instead of the ```.py``` file:

https://pyinstaller.readthedocs.io/en/stable/spec-files.html
