### ISSUE TITLE
hook-zmq no longer works for PyZMQ 15.4.0+

### ISSUE THREAD

**Issue by codewarrior0** [pyinstaller/pyinstaller#2147]
Previously, `zmq.__init__` would search its package path for the library `libzmq.pyd` using a glob-pattern and then load it using a call to `ctypes.CDLL.LoadLibrary`. This allowed us to freeze the file as `zmq/libzmq.pyd` and also exclude the file `zmq.libzmq.pyd` (for reasons I will get into).

As of a recent update, `zmq.__init__` now simply imports the library as a Python module using `from . import libzmq`. When frozen, this import now silently fails, but leads to a different error. When PyZMQ later imports the extension modules under `zmq.backends`, it yields an error "ImportError: DLL load failed: The specified module could not be find". Since the backend modules are actually present, this indicates they failed to load because one of their DLL dependencies was not found - this dependency being `libzmq.pyd`.

`libzmq.pyd` is not on the DLL search path. In the previous PyZMQ version, loading the DLL via `LoadLibrary` implicitly puts it on the search path as an already-loaded-DLL, so when the backends are imported, they can always find it. In the current version, it will only attempt to load this DLL through a Python import statement, which will cause our CExtensionImporter to try to load `zmq.libzmq.pyd`, and fail because it was excluded during the build process.

If `zmq.libzmq.pyd` is not excluded, we still get the same "ImportError: DLL load failed" while importing the backend modules: they link to the library by name, which is `libzmq.pyd`. Our CExtensionImporter will not import the module from `zmq/libzmq.pyd`. 

As mentioned in another issue (https://github.com/pyinstaller/pyinstaller/issues/2005#issuecomment-222660537), I discovered that adding our importer to `sys.path_hooks` prevents the Python import system from falling back to the filesystem for imports: After the `sys.meta_path` importers fail to import `zmq.libzmq`, Python finds a cached `path_hooks` importer for the module `zmq` and stops there.

The resolution to this might be to change the importer added to `sys.path_hooks` to also search the filesystem if it fails to find the module in the archive.
## 

This issue may be specific to Windows and/or to PyZMQ installations that bundle libzmq (as opposed to allowing the system's package manager to install it).

**Comment by bjones1** [comment]
A more radical proposal: What if we did away with the CExtensionImporter, placing all extensions in a directory rather than a dotted filename (i.e. `zmq/libzmq.dll` instead of `zmq.libzmq.dll`? This should make PyInstaller behave a bit more like Python, and hopefully avoid some of these corner cases in the future. The downside I see: this will produce a lot of subdirectories, cluttering the filesystem a bit. A fair trade, IMHO.

**Comment by bjones1** [comment]
I'm seeing [Appveyor failures](https://ci.appveyor.com/project/bjones1/pyinstaller/build/1.0.144) of the zmq tests only on Python 2.7. Is this the same issue, or is something else going on?

**Comment by codewarrior0** [comment]
> Is this the same issue?

Yep. The test failure looks exactly like the error I got locally.

**Comment by codewarrior0** [comment]
> What if we did away with the CExtensionImporter, placing all extensions in a directory rather than a dotted filename (i.e. zmq/libzmq.dll instead of zmq.libzmq.dll?

Hmm. We might run afoul of the `sys.path_hooks` behavior that prevents the filesystem from being searched if a `path_hooks`-returned importer claims that pathname. Other than that, I get the feeling that CExtensionImporter (and the dotted filename pattern) is a legacy of the `iu.py` import hooking mechanism from the earliest versions of PyInstaller. I'd have to double check to be sure.

**Comment by TTimo** [comment]
What is a good workaround for this? I think I'm running into the same issue.

**Comment by TTimo** [comment]
I decided to get latest from git and see if I could make some progress on this. It seems latest has a new problem in collect_submodules which wasn't happening in 3.2:

```
5463 DEBUG: Collecting submodules for zmq.backend
6103 DEBUG: collect_submodules - Found submodules: set(['zmq.backend.cffi', 'No', 'file:', 'zmq.backend.cython.socket', 'file', 'zmq.backend', 'zmq.backend.cython.message', 'open', 'zmq.backend.cython.constants', 'zmq.backend.cython.error', ':', 'zmq.backend.cython', 'zmq.backend.cython._poll', 'Cannot', 'zmq.backend.cython._device', 'fatal', 'C:\\Python27\\lib\\site-packages\\zmq\\backend\\cffi\\__pycache__\\_cffi_ext.c(209)', 'C1083:', 'such', 'zmq.backend.cython.utils', 'zmq.backend.cython._version', 'include', "'sys/un.h':", 'zmq.backend.cython.context', 'zmq.backend.select', 'error', 'directory', '_cffi_ext.c', 'or'])
```

The full log for 3.3-dev is at: https://gist.github.com/TTimo/1614752c59579e099e4f4106d85c14fd

For reference the log for 3.2 is here: https://gist.github.com/TTimo/d91d43c4c73d6269021f52db376d3c40

**Comment by aj-ptw** [comment]
I'm running into the same issue

**Comment by TTimo** [comment]
I tried backing to older revisions but could never get it working. I will try again.

Unfortunately I have not been able to get any feedback from core developers on this. My posts to pyinstaller google group are not going through, and the irc channel is utterly dead.

I'm posting a bounty through BountySource to encourage a fix though, it's not much but maybe that will encourage some activity. I would really like to see zmq as an officially supported package in pyinstaller.

https://www.bountysource.com/issues/37007741-hook-zmq-no-longer-works-for-pyzmq-15-4-0

**Comment by xoviat** [comment]
@TTimo If you're willing to live with a bit larger executable, [subzero][1] can package this correctly if you disable optimize_imports.

[1]: https://github.com/xoviat/subzero

**Comment by albertogomcas** [comment]
I saw a similar issue mentioned in https://github.com/zeromq/pyzmq/issues/999 but the suggested "fix" did not work for me. (Python3.6, pyzmq 16.0.2)

I would love any hints about how to workaround this issue!

**Comment by carlosperate** [comment]
I had the same problem with pyzmq 16.0.2 on Windows, I had to revert back to version 15.3.0 as suggested by @aj-ptw .

**Comment by TTimo** [comment]
tested successfully - thanks @bjones1 !
please feel free to claim the bounty

**Comment by bjones1** [comment]
Thanks! Will do. I've also submitted #3544, which makes the hooks easier to maintain in the future.
