### ISSUE TITLE
Executable file compiled by PyInstaller does not work on Windows 7

### ISSUE THREAD

**Issue by Michael-Zheng** [pyinstaller/pyinstaller#2149]
I am creating a document using Pyinstaller.

Everything is working perfectly, and everything is in place.

Once I distributed my file to my colleagues however, the file seemed to give a Fatal Error, and nothing else. I tested this more and discovered this issue was only on those with windows 7; 8 and 10 worked fine.

I am on Windows 10 with Python 2.7

I feel like this has something to do with python or python-docx

Any help would be greatly appreciated, Thanks!

**Comment by htgoebel** [comment]
Huh? Creating a *document*? This is not what PyInstaller is made for.

Anyway: Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by dagheyman** [comment]
Similar issue here, executable works on Windows 10 but not 7, 8 or Server 2012. Using latest PyInstaller from pip. Will see if I can provide example code.

Error message is "Fatal Error! Error loading Python DLL [...] /python27.dll (error code 14001)

**Comment by voltagex** [comment]
@dagheyman Can you build a barebones hello world exe and see if the same issue happens?

**Comment by voltagex** [comment]
Python 3.5.1:
Building a hello world script with the develop branch above runs on Windows 10 fine, but results in 
![image](https://cloud.githubusercontent.com/assets/159567/18026587/77d8215a-6c8f-11e6-952f-078b517de76d.png) on Windows 7 x64

Downloading and installing the vcredist from https://www.microsoft.com/en-us/download/details.aspx?id=48145 makes the exe run fine.

**Comment by voltagex** [comment]
Python 2.7.11 on Windows 10
```
(27-env) PS C:\Temp> pyinstaller.exe .\hello.py
1128 INFO: PyInstaller: 3.3.dev0+g1804636
1128 INFO: Python: 2.7.0
1128 INFO: Platform: Windows-post2008Server-6.2.9200
1131 INFO: wrote C:\Temp\hello.spec
1138 INFO: UPX is not available.
1138 INFO: Extending PYTHONPATH with paths
['C:\\Temp', 'C:\\Temp']
1138 INFO: checking Analysis
1167 INFO: checking PYZ
1217 INFO: checking PKG
1220 INFO: Bootloader c:\temp\27-env\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
1220 INFO: checking EXE
1226 INFO: checking COLLECT
WARNING: The output directory "C:\Temp\dist\hello" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
4879 INFO: Removing dir C:\Temp\dist\hello
4889 INFO: Building COLLECT out00-COLLECT.toc

(27-env) PS C:\Temp> .\dist\hello\hello.exe
Error loading Python DLL: C:\Temp\dist\hello\python27.dll (error code 126)
```

**Comment by dagheyman** [comment]
@voltagex Using the `https://github.com/pyinstaller/pyinstaller/archive/develop.zip` install solved the issue for me. Will try to reproduce the issue with a minimal example next week.

**Comment by spyoungtech** [comment]
My understanding, from the documentation, is that you may need to build your application for each specific OS, including different Windows operating systems. As far as I know there is no guarantee or indication that a build from *any* Windows OS will work on *any* other Windows OS.

Depending on what dependencies you have and how similar or dissimilar the Windows versions are, it's not surprising to me that you would run across something like this. You may get lucky if the dependencies happen to be unchanged between versions.

> The output of PyInstaller is specific to the active operating system and the active version of Python. This means that to prepare a distribution for:
>
> * a different OS
> * a different version of Python
> * a 32-bit or 64-bit OS

**Comment by dimaqq** [comment]
https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows

**Comment by htgoebel** [comment]
Please read the manual about special care to be taken for windows.

**Comment by zdenop** [comment]
@htgoebel: can you be please more specific about special care to be taken for windows?
I tried use the latest upx (3.95 - 64bit) and pyinstaller (3.5.dev0+955d79e3c), but I still get error, when I run:
```
pyinstaller simple_gui.py
dist\simple_gui\simple_gui.exe
```

![image](https://user-images.githubusercontent.com/574156/50598718-eb37a600-0eab-11e9-8cff-aea6347a7194.png)

Using `pyinstaller --onefile --clean simple_gui.py` does no help.  
`--noupx` build works.
I am testing it on Windows 10 (64bit) and  python 3.6.6 (64bit).

**Comment by zdenop** [comment]
I read [this](https://pythonhosted.org/PyInstaller/usage.html?highlight=upx#using-upx).
But I found there no solution or explanation. 
As far as I understand error, problem is that upx compressed vcruntime140.dll is wrong.
Can you be please more specific, what should I read in manual? Or provide link to specific part?

**Comment by htgoebel** [comment]
This is an outdated manual (which I can not update since uploading new versions is no longer supported.) As stated at PyPI, in the READme, on the website, etc. the current manual is hosted at ishttps://pyinstaller.readthedocs.io/. You may also wan to read the [Known issues](https://pyinstaller.readthedocs.io/en/stable/CHANGES.html#known-issues)

**Comment by zdenop** [comment]
Thanks for response and pointing to right manual. 
I think my issue is not related to problem. I have problem only upx compressed project. Maybe I should open other issue?

**Comment by tidus4400** [comment]
@zdenop I had exactly the same: 
.exe compiled on WIN7 + UPX --> not running on WIN10
.exe compiled on WIN7 w/o UPX --> running properly on WIN10

You actually saved my day :)

**Comment by ghost** [comment]
hi
my windows is 10 pro
python 3.9
pyinstaller is last version
after create exe file , file worked in win 10 but can not run in win 7 and see error 
please help
"the version of this file is not compatible with the version of windows you're running. check your computer's system info to see whether you need an x86 (32Bit) or x64 (64 bit) version of the program, and then contact the software publisher."

**Comment by rokm** [comment]
@sirdash Python 3.9 (and its components) cannot be used on Windows 7 or earlier. Every [python release](https://www.python.org/downloads/windows/) goes out of its way to make a note of that...

**Comment by chris-mck** [comment]
> Python 3.9 (and its components) cannot be used on Windows 7 or earlier.

@rokm Can you please clarify: does this mean an exe made on a Windows 10 machine with Python 3.9 and the --onefile option can not work on Windows 7?

Edit: this part of [the docs ](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html) could cause confusion:

> To your users, the app is self-contained. They do not need to install **any particular version of Python** or any modules. They do not need to have Python installed at all.
(emphasis mine)

The Note just under that talks about cross-OS support is not guaranteed, but until recently Windows exe's worked across different versions of Windows. It would be helpful to add a note that the installing/bundling machine needs to use a Python version compatible with desired target machines, even though the target machines don't need Python installed.

**Comment by rokm** [comment]
> > Python 3.9 (and its components) cannot be used on Windows 7 or earlier.
> 
> @rokm Can you please clarify: does this mean an exe made on a Windows 10 machine with Python 3.9 and the --onefile option can not work on Windows 7?

Yes, that's exactly what it means. The python shared library (which PyInstaller takes from your build system's python installation and uses to set up embedded python interpreter when you run your frozen program) from Python 3.9 will not load on Windows 7.

> Edit: this part of [the docs ](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html) could cause confusion:
> 
> > To your users, the app is self-contained. They do not need to install **any particular version of Python** or any modules. They do not need to have Python installed at all.
> > (emphasis mine)
> 
> The Note just under that talks about cross-OS support is not guaranteed, but until recently Windows exe's worked across different versions of Windows. It would be helpful to add a note that the installing/bundling machine needs to use a Python version compatible with desired target machines, even though the target machines don't need Python installed.

The frozen app is self-contained, and the user does not need to install python and the modules, because they are collected into the application. But that by itself has nothing to do with compatibility with older Windows, because those collected files themselves may be incompatible with Windows 7 (e.g., collected DLLs and python extension modules were built with support for newer Windows only). 

This is not limited to Python, though; you could have python 3.8 and a package with extension modules that are built with support for newer Windows, and that won't work on older Windows, either. 

I think this requirement should not come as a surprise to anyone, but on the other hand, a note about it in the docs could not hurt, either...
