### ISSUE TITLE
PyQt5.7 program cannot run  with Segmentation fault after packaged on Linux Mint

### ISSUE THREAD

**Issue by redstoneleo** [pyinstaller/pyinstaller#2154]
I am using 
PyInstaller: 3.3.dev0+1804636
Python: 3.5.2+
Platform: Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18-sarah
PyQt5.7

after packaged this little program

```
import sys

from PyQt5.QtWidgets import *
from PyQt5.QtCore import *


def main():
    app = QApplication(sys.argv)

    w = QWidget()
    w.show()

    app.exec()

if __name__ == '__main__':
    main()
```

It cannot run  with Segmentation fault

> i@i ~/下载 $ pyinstaller w.py
> 120 INFO: PyInstaller: 3.3.dev0+1804636
> 120 INFO: Python: 3.5.2+
> 121 INFO: Platform: Linux-4.4.0-21-generic-x86_64-with-LinuxMint-18-sarah
> 122 INFO: wrote /home/i/下载/w.spec
> 126 INFO: An exception occured when testing for UPX:
> 126 INFO:   NotADirectoryError(20, 'Not a directory')
> 127 INFO: UPX is not available.
> 182 INFO: Extending PYTHONPATH with paths
> ['/home/i/下载', '/home/i/下载']
> 182 INFO: checking Analysis
> 183 INFO: Building Analysis because out00-Analysis.toc is non existent
> 183 INFO: Initializing module dependency graph...
> 185 INFO: Initializing module graph hooks...
> 198 INFO: Analyzing base_library.zip ...
> 8038 INFO: running Analysis out00-Analysis.toc
> 8175 INFO: Caching module hooks...
> 8200 INFO: Analyzing /home/i/下载/w.py
> 8255 INFO: Loading module hooks...
> 8256 INFO: Loading module hook "hook-xml.py"...
> 8915 INFO: Loading module hook "hook-PyQt5.py"...
> 8931 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
> 9065 INFO: Loading module hook "hook-encodings.py"...
> 9252 INFO: Loading module hook "hook-pydoc.py"...
> 9256 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
> 9259 INFO: Loading module hook "hook-PyQt5.Qt.py"...
> 9262 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
> 9384 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
> 10230 INFO: Looking for ctypes DLLs
> 10248 INFO: Analyzing run-time hooks ...
> 10259 INFO: Including run-time hook 'pyi_rth_qt5.py'
> 10291 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
> 10332 INFO: Looking for dynamic libraries
> 13913 INFO: Looking for eggs
> 13913 INFO: Python library not in binary depedencies. Doing additional searching...
> 14177 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython3.5m.so.1.0
> 14186 INFO: Warnings written to /home/i/下载/build/w/warnw.txt
> 14250 INFO: checking PYZ
> 14251 INFO: Building PYZ because out00-PYZ.toc is non existent
> 14251 INFO: Building PYZ (ZlibArchive) /home/i/下载/build/w/out00-PYZ.pyz
> 15264 INFO: checking PKG
> 15265 INFO: Building PKG because out00-PKG.toc is non existent
> 15265 INFO: Building PKG (CArchive) out00-PKG.pkg
> 15391 INFO: Bootloader /usr/local/lib/python3.5/dist-packages/PyInstaller-3.3.dev0+1804636-py3.5.egg/PyInstaller/bootloader/Linux-64bit/run
> 15391 INFO: checking EXE
> 15391 INFO: Building EXE because out00-EXE.toc is non existent
> 15392 INFO: Building EXE from out00-EXE.toc
> 15399 INFO: Appending archive to ELF section in EXE /home/i/下载/build/w/w
> 15428 INFO: checking COLLECT
> 15428 INFO: Building COLLECT because out00-COLLECT.toc is non existent
> 15429 INFO: Building COLLECT out00-COLLECT.toc
> i@i ~/下载 $ 
> i@i ~/下载/dist/w $ ./w
> Segmentation fault

**Comment by apatrushev** [comment]
Same here.

```
# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:   	Ubuntu 16.04 LTS
Release:       	16.04
Codename:      	xenial

# python --version
Python 3.5.1+

# pip freeze
PyInstaller==3.3.dev0+b78bfe5
PyQt5==5.7
sip==4.18.1
```

**Comment by dridk** [comment]
Same here : 

     python 3.5.2 
     PyQt5-5.7-cp35-cp35m-manylinux1_x86_64.whl
     Ubuntu 16.04.1 LTS 
     sip 4.19.dev1610061700

**Comment by redstoneleo** [comment]
the issue is gone with
PyInstaller-3.2.1
PyQt5.7.1
Python 3.5.2
