### ISSUE TITLE
hook PyQt5: Add import of styles on linux

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#2156]
Please add import of styles plugin on linux to fix freezed apps theme. By default they isn't use system widgets style.

**Comment by htgoebel** [comment]
What are "styles plugins"?

**Comment by DjKrip** [comment]
styles binary in hook-PyQt5.QtGui.py

**Comment by bjones1** [comment]
I'm closing this, since #3233 should fix it -- see the [instructions](https://github.com/pyinstaller/pyinstaller/pull/3233#issuecomment-362094587) there.
