### ISSUE TITLE
the executable created by pyinstall displays "failed to execute script"

### ISSUE THREAD

**Issue by MekuHila** [pyinstaller/pyinstaller#2157]
I am on progress to develop some simple GUI using python 3.5.1 tkinter. the .py script works fine but when I convert it to .exe using pyinstaller 3.2 the executable file doesn't start so in order to see what the problem is I convert the .py file without --windowed and I observe the below message on the command line
![command](https://cloud.githubusercontent.com/assets/12391190/17995921/383ba570-6b6e-11e6-8b55-5b952249b3c9.jpg)
is there any solution

**Comment by Legorooj** [comment]
This is a support question. Please ask on stackoverflow or somewhere else.
