### ISSUE TITLE
Pyinstaller with RPy libraries

### ISSUE THREAD

**Issue by clacri** [pyinstaller/pyinstaller#2159]
Hi,

we are trying to compile with pyinstaller a script that imports and use RPy2. The environment is managed trough conda, and we have used pyinstaller 3.2. However, when trying to execute the linux binary, the following traceback and error is raised:

  File "anaconda/envs/ourenvironment/lib/python2.7/site-packages/rpy2/rinterface/**init**.py", line 81, in <module>
RuntimeError: The R home directory could not be determined.

```
Try to install R <https://www.r-project.org/>,
set the R_HOME environment variable to the R home directory, or
add the directory of the R interpreter to the PATH environment variable.
```

Do you have any clue of what could be happening in this case?

**Comment by Legorooj** [comment]
Sorry but we can't support this type of issue anymore! Please use stackoverflow or somewhere else.
