### ISSUE TITLE
Create several executables files

### ISSUE THREAD

**Issue by JPFrancoia** [pyinstaller/pyinstaller#2163]
Is it possible to obtain this kind of architecture with Pyinstaller ?

```
MyProgram/
    launcher.exe
    MyProgram/
        myprogram.exe
        some_datas/
```

launcher.exe would be the entry point, and would start myprogram.exe.

**Comment by tallforasmurf** [comment]
If treated as two different programs, it should work. One program, launcher.exe, uses perhaps `subprocess.run()` to launch some other executable, which just happens to be one built by PyInstaller. The path to the `some_datas` folder could be passed in using a command-line argument.

If you want `some_datas\*` bundled into myprogram.exe, see https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle however in that case, they are unpacked into the temp dir made when myprogram.exe launches.

In general read https://pyinstaller.readthedocs.io/en/stable/runtime-information.html before planning this system in detail.

**Comment by JPFrancoia** [comment]
thanks for your answer. However, it is not exactly what I want:
Can pyinstaller create by itself this kind of architecture ?

From

```
launcher.py
myprogram.py
some_datas/
```

I would like to get:

```
MyProgram/
    launcher.exe
    MyProgram/
        myprogram.exe
        some_datas
```

That's the kind of architecture I had with Esky. The purpose of all this is to be able to auto-update MyProgram. If a new version exists, myprogram.exe would download the new version:

```
MyProgram/
    launcher.exe
    MyProgram/
        myprogram.exe
        some_datas
    MyProgram_new_version/
        myprogram.exe
        some_datas
```

And at boot, ```launcher.exe``` would choose the most recent ```myprogram.exe```

**Comment by tallforasmurf** [comment]
Hmmm. Is it a good idea, or even allowed, to have a folder contain a folder of the same name? I can see you building this:

    MyProgram/
        myprogram.exe
        MyRealProgram/
            myrealprogram.exe
            some_datas

As follows,

1. Using one-folder mode, package `MyRealProgram`, including data files as described [in the manual](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle)

2. Using one-folder mode, package `MyProgram`, including the entire `MyRealProgram` folder as a folder of data, see previous reference.

There would be some fiddling at run time to figure out where things are, see [run time info](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html) for suggestions. Also, there will be as usual a lot of other stuff in the two folders, all the support files, and now I think about it, there would be duplication of support files adding up to quite a few MB. (You could maybe get around this with a custom script that runs through and turns every matching name in `MyProgram` into a link to the support file in `MyRealProgram`...)

For something completely different there is at least one auto-update package for PyInstaller, see [updater4pyi](https://pypi.python.org/pypi/updater4pyi/0.7). It seems to me there is maybe another similar package but I can't find it in a quick search.

**Comment by htgoebel** [comment]
You can achieve this by writing an appropriate .spec file. It might be easier if you think about being two different programs, the launcher and Myprogram, which get frozen interdependently.
