### ISSUE TITLE
Failed to execute script error when using click on OS X.

### ISSUE THREAD

**Issue by nmcbride** [pyinstaller/pyinstaller#2164]
**\* I'm sorry guys - reading through the "how to submit a bug" page more I tried the development version and this bug appears to be fixed in version PyInstaller==3.3.dev0+1804636.  Wish I had seen the before I made the bug. ***

I made a python app to hash files.  I have built it for windows and it runs perfectly after making a few tweaks.  It also runs fine on OS X as a python script.  I attempted to make it into a standalone executable for OS X and it actually runs perfectly.  HOWEVER, I still get an error saying "Failed to execute script ProgramX"

```
MacBook-Pro:ProgramX myself$ ./programx --help
Usage: programx [OPTIONS] PATH

Options:
  -p, --processes INTEGER  How many processes to use for calculations.
  -h, --hash [md5|sha1]        What hash type to calculate.
  --version                             Show the version and exit.
  --help                                  Show this message and exit.
Failed to execute script programx
```

I am not sure why I am seeing this error.  I've tested all the functions and it works fine.  I've checked the warn file and there are no missing imports... which I assumed since all the features work as expected.

I am building this on OS X 10.11.6 with python 2.7.12 and I am testing the built package on OS X 10.11.6.

Ok so after reading through the "how to submit a bug" page I've tried to narrow it down a bit more.  It appears to be an issue when using the click library on OS X.  Remember it works fine when built on windows.  To reproduce you can make the most simplistic click program possible.  I am using click version 6.6 which you can find [here](https://pypi.python.org/pypi/click). 

```
import click
@click.command()
def main(): pass
if __name__ == '__main__': main()
```

Which produces the output:

```
MacBook-Pro:ProgramX myself$ dist/test/test
Failed to execute script test
```

Please let me know if there is anything else I can do to help solve this out.

**Comment by csaintc** [comment]
I'm having the same issue with the click library.

👍

**Comment by bwoodsend** [comment]
It's working ok for me with PyInstaller 4.1 so I'll assume this has cleared itself up. Comment below if you still get this issue with modern Python/PyInstaller/
