### ISSUE TITLE
Can't use pyinstaller work with pyqt5

### ISSUE THREAD

**Issue by littor** [pyinstaller/pyinstaller#2172]
Hi all the following is my log for my task, could you take a look at it?

1686 INFO: Loading module hook "hook-encodings.py"...
1692 INFO: Loading module hook "hook-xml.py"...
1844 INFO: Loading module hook "hook-pydoc.py"...
1844 INFO: Loading module hook "hook-httplib2.py"...
1845 INFO: Loading module hook "hook-PyQt5.py"...
1908 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
1908 INFO: Loading module hook "hook-PyQt5.Qt.py"...
1909 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
2005 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
2086 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
2419 INFO: Looking for ctypes DLLs
2425 INFO: Analyzing run-time hooks ...
2428 INFO: Including run-time hook 'pyi_rth_qt5.py'
2429 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
2435 INFO: Looking for dynamic libraries
2437 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.dylib)
2437 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqjpeg.dylib)
2439 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.dylib)
2439 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtiff.dylib)
2441 ERROR: Can not find path ./QtDBus.framework/Versions/5/QtDBus (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.dylib)
2441 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.dylib)
2441 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqminimal.dylib)
2443 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.dylib)
2443 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqtga.dylib)
2445 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.dylib)
2445 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwebp.dylib)
2446 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.dylib)
2447 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqicns.dylib)
2448 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.dylib)
2449 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqgif.dylib)
2450 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqdds.dylib)
2450 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqdds.dylib)
2452 ERROR: Can not find path ./QtDBus.framework/Versions/5/QtDBus (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib)
2452 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib)
2453 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib)
2469 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)
2469 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)
2469 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)
2470 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)
2470 ERROR: Can not find path ./QtDBus.framework/Versions/5/QtDBus (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqcocoa.dylib)
2473 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)
2474 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)
2474 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)
2474 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib)
2476 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)
2476 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)
2476 ERROR: Can not find path ./QtSvg.framework/Versions/5/QtSvg (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)
2476 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqsvg.dylib)
2478 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.dylib)
2478 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqwbmp.dylib)
2479 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)
2479 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)
2479 ERROR: Can not find path ./QtSvg.framework/Versions/5/QtSvg (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)
2480 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib)
2481 ERROR: Can not find path ./QtDBus.framework/Versions/5/QtDBus (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib)
2481 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib)
2482 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib)
2483 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.dylib)
2483 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/Qt/plugins/imageformats/libqico.dylib)
2486 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtCore.so)
2488 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)
2488 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)
2488 ERROR: Can not find path ./QtPrintSupport.framework/Versions/5/QtPrintSupport (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)
2488 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtPrintSupport.so)
2491 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtGui.so)
2491 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtGui.so)
2550 ERROR: Can not find path ./QtWidgets.framework/Versions/5/QtWidgets (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtWidgets.so)
2550 ERROR: Can not find path ./QtCore.framework/Versions/5/QtCore (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtWidgets.so)
2551 ERROR: Can not find path ./QtGui.framework/Versions/5/QtGui (needed by /usr/local/lib/python3.5/site-packages/PyQt5/QtWidgets.so)

**Comment by tallforasmurf** [comment]
From the references to `.framework/Versions` I'm guessing this is Mac OS? Anyway it looks like a problem in the installation of Qt, or PyQt5, or both. The location of the Qt components is linked into the PyQt parts when they are installed. It is puzzling to me why the needed paths are relative (start with `./`).
* tell us the platform
* tell us how you installed PyQt5 and Qt and their specific versions
* write a minimal example (you can create the QApplication and open an empty QMainWindow in about 6 lines of code) and verify it works from the command line

**Comment by littor** [comment]
Hi Tallforasmurf,

Yes, this is the Mac os.

I just download the qt from official site, and click and click.

After that I use pip to install the pyqt5.

And then, I use pythcarm as a IDE to write my qt application in python.

Actually, I can run the application in IDE.

But when I use pyinstaller to package it, the problem happened.

Should I uninstall qt and pyqt, and reinstall them again?

Thanks
Fox

**Comment by littor** [comment]
Hi Hi Tallforasmurf,

Thank you for your response.

I reinstall the pyqt by home-brew, now it works fine.

The steps are here:

1, brew install qt5
2, brew install pyqt5

And it works, sorry to raise this stupid problem here.

The root cause is that I both use pip and brew to install pyqt and qt, it make the system messy.

Very thanks.

Thanks
Fox

**Comment by tallforasmurf** [comment]
Glad you got it straightened out!
