### ISSUE TITLE
PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#2174]
Pyinstaller finished the compilation successfully but when I load the file on a mac I get the below error:

st/main ; exit;
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_qt5.py", line 61, in <module>
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 634, in _load_backward_compatible
  File "/Users/nicolas/anaconda/lib/python3.5/site-packages/PyInstaller-3.3.dev0+g64c6172.mod-py3.5.egg/PyInstaller/loader/pyimod03_importers.py", line 573, in load_module
    module = loader.load_module(fullname)
RuntimeError: the PyQt5.QtCore and PyQt4.QtCore modules both wrap the QObject class
Failed to execute script pyi_rth_qt5

**Comment by tallforasmurf** [comment]
WTF are both `PyQt5.QtCore and PyQt4.QtCore modules` doing in one program? Are you quite sure that somewhere in your app you don't have a `from PyQt4.Qsomething import...` left over from a prior version?

**Comment by dickreuter** [comment]
Yes I checked and there's nothing in my code, but could the culprit be matplotlib which I import?

**Comment by tallforasmurf** [comment]
I've no experience with matplotlib. But looking at [the install instructions](http://matplotlib.org/users/installing.html) it mentions PyQt4 and PyQt5 at different places as optional. So the relationship between matplotlib, Qt4, Qt5, Tk, and all the many many matplotlib add-ons looks like kind of a mess. So I'd say, yes, that is a very good candidate for the source of this problem.

**Comment by dickreuter** [comment]
I'm quite sure it is. Matplotlib offers the option that the user can
specify what engine to use. In my case I have at the beginning of the code:
matplotlib.use('Qt5Agg'). Pyinstaller would somehow need to pick that up
and only use Qt5. No idea how this can be implemented.

**Comment by dickreuter** [comment]
is there a way I can force pyinstaller to ignore pyqt4 and pyside?

**Comment by tallforasmurf** [comment]
PyInstaller parses imports (and hook files), period. `matplotlib.use('Qt5Agg')` implies there is some kind of run-time, dynamic selection among GUI platforms. That strikes me as crazy because it implies bundling more than one GUI (which indeed appears to be happening), a huge waste of space.

In your situation, I would think about creating a new VENV and carefully installing into it exactly and only what my app needs. You can do a PyQt5 install inside the VENV. And just the parts of matplotlib you need. At some point, running from the command line or IDE inside that VENV, matplotlib will trap out trying to load the PyQt4 that is not installed.

**Comment by dickreuter** [comment]
I'm using anaconda so I have plenty of stuff in there, but I now completely
removed pyqt4 from it, but the error is still there. Is there no way to
prevent pyinstaller from bundling pyqt4? Not sure where it's getting it
from anyway.

**Comment by dickreuter** [comment]
After correctly removing pyqt4 from my python distribution I found a new error message that's generated from the compiled exe file: importError: No module names PyQt4.QtCore', failed to execute script pyi_rth_qt4plugins. It seems like pyinstaller keeps forcing to input that package even though it's not needed. Any way I can prevent that from happening without having to take apart matplotlib?

**Comment by dickreuter** [comment]
106610 INFO: Loading module hook "hook-matplotlib.backends.py"...
107793 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
108685 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
109185 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
109925 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
110643 INFO:   Matplotlib backend "Qt4Agg": added
111365 INFO:   Matplotlib backend "Qt5Agg": added
112146 INFO:   Matplotlib backend "TkAgg": added
113245 INFO:   Matplotlib backend "WX": ignored

**Comment by tallforasmurf** [comment]
If you can figure out the right module(s), see the [--exclude-module](http://pythonhosted.org/PyInstaller/usage.html?highlight=excluded#what-to-bundle-where-to-search) option.

**Comment by dickreuter** [comment]
This will only exclude the module from loading into the bundle. But how can
I prevent it trying to import a module (i.e. PyQt4 is not bundled as it's
no longer available in my package, but pyinstaller still tries to import
it).

**Comment by tallforasmurf** [comment]
I note you are now seeing an error related to `pyi_rth_qt4plugins` which is a PyInstaller "run-time hook" that is only included in the bundle because there was some reference to PyQt4 in the modules scanned by PyInstaller. That pretty well proves that in some module imported by your code, there is an import of some element of PyQt4. Since you say you've removed PyQt4, most likely PyInstaller did not actually find the requested PyQt4 module (there is probably a "missing module" noted in build/myapp/warn*.txt), however it still includes the run-time hook. The run-time hook fails because the PyQt4 module(s) are not in the bundle, but that's not the problem. PyInstaller did not just decide to look for PyQt4 on its own initiative; there's an import for it somewhere.

to review, the initial situation was that both PyQt4 and PyQt5 were included in the bundle, causing the "both wrap the QObject class" error. Now you've eliminated PyQt4 from the bundle but unfortunately there's still an attempt to import it, causing the failure in the PyQt4 run-time hook.

Look at build/*appname*/warn*appname*.txt for the list of missing modules. I bet there are PyQt4 ones listed, and it will show what module tried to import them.

**Comment by dickreuter** [comment]
PyQt4 is mentioned as follows in warn*appname*.txt

missing module named PyQt4 - imported by matplotlib.backends.qt_compat,
pandas.util.clipboard
missing module named 'PyQt4.QtGui' - imported by matplotlib.pyplot
missing module named 'PyQt4.QtCore' - imported by PIL.ImageQt

**Comment by tallforasmurf** [comment]
searching the matplotlib git for matplotlib.backends.qt_compat, I see references to a matplotlibrc file, which apparently can contain `backend qt4agg` or `backend qt5agg`. This is me poking around more or less at random in some complicated module I've never used, so ymmv. But based on that I'd say you should investigate your matplotlib configuration and maybe ask in a matplotlib forum why it ends up trying to import both qt4 and qt5.

**Comment by tacaswell** [comment]
mpl ships with code to, via run-time configuration, integrate with PyQt4, PyQt5, pyside, pyside2, wx, wx-phoenix, gtk2, gtk3 and  native-osx (and there is also a third-party backend for kivy).  This is one of the biggest selling points of the library.

`qt_compat` is an mpl-internal shim module to smooth over the API differences between the 4 (will 4.5, if you include the api version mechanism in pyqt4) and to centralize the lookup.  All of our internal use of qt bindings is imported from `qt_compat`.   Maybe pyinstaller should patch out `qt_compat` during the bundling process to only contain the user requested imports?

**Comment by tallforasmurf** [comment]
so... try `--exclude-module=matplotlib.backends.qt_compat` ? I'm not sure of that option's syntax, whether it wants the fully qualified name or just qt_compat. Anyone?

**Comment by dickreuter** [comment]
I've tried to simply exclude ['matplotlib.backends.qt_compat'] but that gives another error now: Import error, no module named PySide. Not sure why pyinstaller is still trying to import PySide. I found:
missing module named PySide - imported by pandas.util.clipboard, missing module named 'PySide.QtCore' - imported by PIL.ImageQt, missing module named 'PyQt4.QtCore' - imported by PIL.ImageQt

**Comment by dickreuter** [comment]
corrected: I've excluded that module (the correct syntax is excludes=['matplotlib.backends.qt_compat'],). The new error message is:  exec(bytecode, module.__dict__)
  File "site-packages\matplotlib\backends\backend_qt5.py", line 31, in <module>
ImportError: No module named 'matplotlib.backends.qt_compat'
Failed to execute script main

**Comment by tallforasmurf** [comment]
`excludes=[list]` is the syntax when modifying the spec file. Good for you for finding that. `--exclude-module=name` is the command-line option, which basically just feeds into the `excludes=` parameter in the spec file.

So you successfully excluded `qt_compat` and turns out, it is required by `backend_qt5`.  OK, bad idea. See next comment.

**Comment by tallforasmurf** [comment]
@tacaswell, you said "pyinstaller is just searching the code for imports and can not cope with conditional conflicting imports."

It is exactly the case the PyInstaller searches the code for imports. What else could it do?

What do you mean by "conditional conflicting imports"? If you are talking about imports that are dynamically executed at run-time -- as opposed to appearing in the static code -- then that is definitely a [documented restriction](http://pythonhosted.org/PyInstaller/operating-mode.html#analysis-finding-the-files-your-program-needs).

If you are talking about imports that appear inside a Python if-statement, again there is no way at the time of bundling the app, to determine whether a given branch of an if will be executed or not, so yes, it takes them all.

Can you explain how MPL figures out which GUI to include, and what imports are done at run-time?

**Comment by tacaswell** [comment]
In `qt_compat`, the code basically boils down to (modulo API patch up and some fallback behavior)

```python
if use_pyqt4:
    from PyQt4 import QtGui, QtCore
elif use_pyqt5:
    from PyQt5 import QtGui, QtCore
elif use_pyside:
    from pyside import QtGui, QtCore
elif use_pyside2:
    from pyside2 import QtGui, QtCore
else:
    raise Exception()
```

In the rest of the code base when we need Qt bindings we do `from mpl.backend.qt_compat import QtCore, QtGui`.  So long as you know that the `use_*` conditions are mutually exclusive, this is safe to do at the module level. 

The backend is selected via what ever is in `mpl.rcParms['backend']` when `pyplot` is imported.

https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages says that mpl is supported out of the box via the hook mechanism.  

https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-matplotlib.backends.py looks like the solution is to ensure only the qt binding you are about is importable in the enviroment that you run pyinstaller in.

**Comment by tallforasmurf** [comment]
Wow, that is a hook and a half, eh?

@dickreuter please run PyInstaller with `--log-level INFO` and we should see some messages of the form 'Matplotlib backend "%s": added/ignored'.

**Comment by bjones1** [comment]
FWIW, the general problem of PyQt4 and PyQt5 imports was discussed at https://github.com/pyinstaller/pyinstaller/issues/2024#issuecomment-224410240. As I recall (without some serious modulegraph fixing), the solution was, as mentioned in this thread, isolate the two via a virtual environment. If PyQt4 is still somehow getting found, I would first assume there are still bits of it hiding around that PyInstaller finds and is then confused by.

**Comment by dickreuter** [comment]
I have again completely removed all pyqt4 things from my computer and it now works fine.

**Comment by tallforasmurf** [comment]
Excellent! Close issue?

**Comment by dickreuter** [comment]
I'm ok with closing it. It might be worth noting that when using anaconda removing it with conda uninstall pyqt4 and pip uninstall pyqt4 is not enough. It's necessary to scan all the folders and manually delete some of the pyqt4 folders.
