### ISSUE TITLE
Pyinstaller3.2: SyntaxError when building even small scripts

### ISSUE THREAD

**Issue by EPeterE** [pyinstaller/pyinstaller#2179]
I tried building a very simple test application but failed with this traceback:

The simple test script "test.py" is
>
import os
print(os.getcwd())

and building with
>
pyinstaller "test.py"

The output is 
>
272 INFO: PyInstaller: 3.2
273 INFO: Python: 2.7.12
276 INFO: Platform: Windows-10-10.0.14393
278 INFO: wrote c:\Python27\Scripts\test.spec
280 INFO: UPX is not available.
285 INFO: Extending PYTHONPATH with paths
['c:\\Python27\\Scripts', 'c:\\Python27\\Scripts']
286 INFO: checking Analysis
289 INFO: Building Analysis because out00-Analysis.toc is non existent
289 INFO: Initializing module dependency graph...
296 INFO: Initializing module graph hooks...
417 INFO: running Analysis out00-Analysis.toc
424 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
644 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
647 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
650 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
653 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4967_none_f4803212f65533a5.manifest
654 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
661 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
864 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9247_none ...
865 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35.manifest
869 INFO: Searching for file msvcr90.dll
871 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcr90.dll
871 INFO: Searching for file msvcp90.dll
872 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcp90.dll
872 INFO: Searching for file msvcm90.dll
874 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcm90.dll
1072 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_60a5df56e60dc5df.manifest
1075 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
1076 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
1078 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4967_none_f4803212f65533a5.manifest
1079 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_f480bfaef65491a5.manifest
1082 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
1085 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
14434 INFO: Caching module hooks...
14451 INFO: Analyzing c:\Python27\Scripts\test.py
17443 INFO: Loading module hooks...
17446 INFO: Loading module hook "hook-encodings.py"...
18520 INFO: Looking for ctypes DLLs
18522 INFO: Analyzing run-time hooks ...
18548 INFO: Looking for dynamic libraries
22029 INFO: Looking for eggs
22029 INFO: Using Python library C:\WINDOWS\system32\python27.dll
22030 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9247), publicKeyToken=u'1fc8b3b9a1e18e3b')]
22043 INFO: Warnings written to c:\Python27\Scripts\build\test\warntest.txt
22164 INFO: checking PYZ
22164 INFO: Building PYZ because out00-PYZ.toc is non existent
22164 INFO: Building PYZ (ZlibArchive) c:\Python27\Scripts\build\test\out00-PYZ.pyz
23138 INFO: checking PKG
23140 INFO: Building PKG because out00-PKG.toc is non existent
23140 INFO: Building PKG (CArchive) out00-PKG.pkg
Traceback (most recent call last):
  File "c:\Python27\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2', 'console_scripts', 'pyinstaller')()
  File "c:\python27\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\python27\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\python27\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 26, in <module>
  File "c:\python27\lib\site-packages\PyInstaller\building\api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "c:\python27\lib\site-packages\PyInstaller\building\api.py", line 189, in __init__
    self.__postinit__()
  File "c:\python27\lib\site-packages\PyInstaller\building\datastruct.py", line 178, in __postinit__
    self.assemble()
  File "c:\python27\lib\site-packages\PyInstaller\building\api.py", line 274, in assemble
    pylib_name=pylib_name)
  File "c:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 329, in __init__
    super(CArchiveWriter, self).__init__(archive_path, logical_toc)
  File "c:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 59, in __init__
    self._add_from_table_of_contents(logical_toc)
  File "c:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 84, in _add_from_table_of_contents
    self.add(toc_entry)  # The guts of the archive.
  File "c:\python27\lib\site-packages\PyInstaller\archive\writers.py", line 370, in add
    code = get_code_object(nm, pathnm)
  File "c:\python27\lib\site-packages\PyInstaller\building\utils.py", line 545, in get_code_object
    co = _load_code(modname, filename)
  File "c:\python27\lib\site-packages\PyInstaller\building\utils.py", line 521, in _load_code
    assert loader and hasattr(loader, 'get_code')
AssertionError

Any help??

**Comment by ajitpeter** [comment]
I noticed the "AssertionError" in version 3.2 of the pyinstaller. The fix for it is to `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip` which resolves the issue. I got the same issue on a simple program which prints to the console.

**Comment by AraHaan** [comment]
Or people smart enough to make a script that they do not have to recompile every time they change something (unless they import files it does not include) that it would compile the main file they want into a code object and ``exec(c)`` when they do 
``c = compile(open('path to file they want here.').read(), self.filename, 'exec')``. This is a smart idea where the file they do this they import all the modules it says import Error on and Done. 😛

**Comment by EPeterE** [comment]
Thanks Ajit Peter
Pyinstaller works now on my sample code and on my scripts

**Comment by EPeterE** [comment]
Thanks AraHaan
Unfortunately I am a bit of a beginner at python and pyinstaller, so I am
not sure exactly what you are trying to tell me.

**Comment by htgoebel** [comment]
Solves in development-version already.

**Comment by mooncoindev** [comment]
haha! was having this exact issue, however it stopped whilst searching for DLL's for 2-3 minutes before breaking. just confirming that '_pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip_' not only fixes the issue but also speeds things up.

**Comment by AraHaan** [comment]
PyInstaller's Setup.py needs to check if Python is < ``3.0`` and if it is not then it should not try to install pywin32 as that package is python 2 only and does not support Python 3 when you try to pip install pyinstaller in any version of Python 3 including 3.6. Bsides you can actually get python 3 code to work on the print function if you do:

```py
from __future__ import print_function
```
or at least something like that.

**Comment by simonvanderveldt** [comment]
> Solves in development-version already.

@htgoebel shouldn't this be released as a patch version? This broke my build when upgrading to 3.2 coming from 3.1.1

**Comment by keepwakinwind** [comment]
@mooncoindev  the same issue I had as EPeterE put has been fixed, "it not noly fixes the issue but  also speeds things up, great"! thanks a lot!
