### ISSUE TITLE
Django1.9 trouble finding static folder location

### ISSUE THREAD

**Issue by curtwagner1984** [pyinstaller/pyinstaller#2181]
Hello, I'm trying to get Django1.9 working with Pyinstaller 3.2 on windows 10 64bit.

I managed to make a functioning exe using Pyinstaller. 
It doesn't crush and seem to launch fine when I do `manage.exe runserver 0:8000`

However, the server can't seem to find the projects static files.
In my `manage.py` I made a printout to see where it looks for the static files:

``` python

    print("Static files dir is: {}".format(YAPO.settings.STATIC_ROOT))
    print("Media files dir is: {}".format(YAPO.settings.MEDIA_ROOT))

```

Thoese are the relevant settings in **settings.py**:

``` python
STATIC_ROOT = os.path.abspath(os.path.join(BASE_DIR, "videos/static"))
STATIC_URL = '/static/'


MEDIA_ROOT = os.path.abspath(os.path.join(BASE_DIR, 'videos/media'))
MEDIA_URL = '/media/'
```

So when I run my server I get:

> E:\Django-github\dist\YAPO>yapo runserver 0:8001
> Static files dir is: E:\Django-github\dist\YAPO\videos\static
> Media files dir is: E:\Django-github\dist\YAPO\videos\media
> Static files dir is: E:\Django-github\dist\YAPO\videos\static
> Media files dir is: E:\Django-github\dist\YAPO\videos\media
> Performing system checks...

However when I'm trying to actually navigate to the webpage, I get only 404's:

> [08/Sep/2016 18:35:31] "GET / HTTP/1.1" 200 9236
> Not Found: /static/bower/bower_components/jquery/dist/jquery.min.js
> Not Found: /static/bower/bower_components/bootstrap/dist/css/bootstrap.min.css
> [08/Sep/2016 18:35:48] "GET /static/bower/bower_components/jquery/dist/jquery.min.js HTTP/1.1" 404 3426
> Not Found: /static/bower/bower_components/angular-xeditable/dist/css/xeditable.css
> [08/Sep/2016 18:35:48] "GET /static/bower/bower_components/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 404 3459
> Not Found: /static/bower/bower_components/bootstrap/dist/js/bootstrap.min.js
> [08/Sep/2016 18:35:48] "GET /static/bower/bower_components/angular-xeditable/dist/css/xeditable.css HTTP/1.1" 404 3471
> Not Found: /static/bower/bower_components/angular/angular.js
> [08/Sep/2016 18:35:48] "GET /static/bower/bower_components/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 404 3453
> Not Found: /static/css/angular/styles.css

I had a simular problem with the server failing to find the template files:

> Template-loader postmortem
> Django tried loading these templates, in this order:
> Using engine django:
> django.template.loaders.app_directories.Loader: E:\Django-github\dist\YAPO\django\contrib\admin\templates\videos\angular\index.html (Source does not exist)
> django.template.loaders.app_directories.Loader: E:\Django-github\dist\YAPO\django\contrib\auth\templates\videos\angular\index.html (Source does not exist)

But because it gave me the path where it was looking for the templates, I just copy/pasted them from the original project and it seems to work.

I'm not sure if it's a bug or if I'm just doing something wrong (probably the later).

**Comment by yanyixing** [comment]
i meet same problem
one question, where are you copy the static file(css, js and images)?

**Comment by RaginiDahihande** [comment]
Hello I am also facing same problem, Didi you got solution for this ?

**Comment by curtwagner1984** [comment]
@RaginiDahihande Nope, No solution thus far, tried to put the static files in every conceivable folder, no luck.

**Comment by RaginiDahihande** [comment]
@curtwagner1984 I also did same copied static files in every directory. I have printed static files path also its correct.But its not working.I also tried by changing django settings.py but didn't worked. If you get solution please notify.Thanks

**Comment by RaginiDahihande** [comment]
@curtwagner1984 One thing to tell you what I did I have created exe using **pyinstaller --onefile manage.py**, this will create exe in dist folder no other files will be there only one file. When I run exe pyinstaller will environment in Temp folder.
location of env C:\Users\sanjad\AppData\Local\Temp
I used sys._MEIPASS to get location of temp environment.
I modified template path see I added this **'DIRS': [sys._MEIPASS],** line in settings.py.
```
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [sys._MEIPASS],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
```

One more thing added datas in spec file so what you are doing now is copying templates I am not copying templates exe automaticaly extract it.My templates are working fine only thing is static files
```
datas=[
					('../mysite/polls/templates','polls/templates'),
					('../mysite/static/polls','static/polls'),
					],
```

**Comment by htgoebel** [comment]
Somebody needs to provide proper hooks, see https://github.com/pyinstaller/pyinstaller/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+django.

**Comment by bwoodsend** [comment]
Closing as we no longer support django1.x. If this issue persists in django2.x then raise a new issue.
