### ISSUE TITLE
Hook for statsmodels

### ISSUE THREAD

**Issue by dangitall** [pyinstaller/pyinstaller#2183]
Running this minimal script using statsmodels:

```
import statsmodels.api as sm
import numpy as np

print(sm.add_constant(np.array([1, 2, 3])))
```

I'm getting this error after bundling it with pyinstaller:

```
Traceback (most recent call last):
  File "smtest.py", line 1, in <module>
    import statsmodels.api as sm
  File "/Users/dan/.virtualenvs/smtest/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/statsmodels/api.py", line 19, in <module>
  File "/Users/dan/.virtualenvs/smtest/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "site-packages/statsmodels/__init__.py", line 8, in <module>
ImportError: No module named 'statsmodels.__init__.tools'
Failed to execute script smtest
```

These are the packages I have installed:

```
numpy==1.11.1
pandas==0.18.1
patsy==0.4.1
PyInstaller==3.3.dev0+b78bfe5
python-dateutil==2.5.3
pytz==2016.6.1
scipy==0.18.0
six==1.10.0
statsmodels==0.6.1
```

I am having this problem on OS X running python 3.5.2 and  the dev release pyinstaller (3.3.dev0+b78bfe5) in `--onedir` mode.

Looking in `out00-PYZ.pyz` I see, amongst other things:

```
 'statsmodels': (1, 5553918, 1412),
 'statsmodels.__init__': (1, 5555330, 1412),
 'statsmodels.api': (0, 5556742, 1173),
 'statsmodels.tools': (1, 6242133, 160),
 'statsmodels.tools.sm_exceptions': (0, 6269677, 964),
```

The troublesome import in statsmodels seems to be

```
from .tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
                                  IterationLimitWarning, InvalidTestWarning)
```

It looks like everything is working as it should up until the ImportError. Any clue on what else I can try here?

**Comment by Tryph** [comment]
I am encountering the axact same problem with the same Python module.
I use the anaconda package statsmodels-0.6.1-np111py27_1.

The is no problem during the app packaging but at runtime I get the following error:
```
File "site-packages\statsmodels\__init__.py", line 8, in <module>
ImportError: No module named tools.sm_exceptions
```

It seems Pyinstaller is not able to handle correclty relative imports:

```
# statsmodels\__init__.py, line 8
from .tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
                                  IterationLimitWarning, InvalidTestWarning)
```

changing the statsmodels module this way fixes the problem:
```
# statsmodels\__init__.py, line 8
from statsmodels.tools.sm_exceptions import (ConvergenceWarning, CacheWriteWarning,
                                  IterationLimitWarning, InvalidTestWarning)
```

**Comment by lopezco** [comment]
The patch has been merged into statsmodels
https://github.com/statsmodels/statsmodels/pull/3823

You can close this issue.

**Comment by ukdixit** [comment]
import statsmodels.api solved the problem for me.

**Comment by htgoebel** [comment]
I'm reopening this after having a look at. PyInstaller is able to handle relative imports, so I really wonder what is going on here.

**Comment by digdig** [comment]
@htgoebel I have similar issue here: https://github.com/pyinstaller/pyinstaller/issues/3921

**Comment by htgoebel** [comment]
@obsidianm Thanks for posting a hook. Would be great if you could provide a pull-request for it.

Please check if these modules are actually imported by `statsmodels` or by another module (e.g. `statsmodels.tsa`. Maybe `collect_submodules()` would be more future proof. Also mind the copyright header, the commit messages text to comply to our [Commit Message Rules](https://pyinstaller.readthedocs.io/en/latest/development/commit-messages.html#commit-messages). and the [changelog entry](https://pyinstaller.readthedocs.io/en/latest/development/changelog-entries.html) so our users can learn about your change. Thanks.

**Comment by htgoebel** [comment]
I'm closing this. Looks lik @obsidianm will not provide a pull-request.
