### ISSUE TITLE
Script not found building with spec file

### ISSUE THREAD

**Issue by Chaoste** [pyinstaller/pyinstaller#2199]
Hey guys,
I'm working on a python package with consists of 4 files an a __main__.py so I can run "python -m app". A few weeks ago I setup a pyinstaller spec file which worked for my purposes. But I'm having multiple problems on my new laptop. I have Windows 10 Home (64 Bit).

Output for `pyinstaller attachment-collector.spec`:

    644 INFO: PyInstaller: 3.3.dev0+b78bfe5
    645 INFO: Python: 3.5.2
    652 INFO: Platform: Windows-10-10.0.14393-SP0
    657 INFO: UPX is not available.
    Traceback (most recent call last):
      File "pyinstaller-pyinstaller-b78bfe5\pyinstaller.py", line 15, in <module>
        run()
      File "C:\Users\Thomas\Projekte\pyinstaller-pyinstaller-b78bfe5\PyInstaller\__main__.py", line 90, in run
        run_build(pyi_config, spec_file, **vars(args))
      File "C:\Users\Thomas\Projekte\pyinstaller-pyinstaller-b78bfe5\PyInstaller\__main__.py", line 46, in run_build
        PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
      File "C:\Users\Thomas\Projekte\pyinstaller-pyinstaller-b78bfe5\PyInstaller\building\build_main.py", line 788, in main
        build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
      File "C:\Users\Thomas\Projekte\pyinstaller-pyinstaller-b78bfe5\PyInstaller\building\build_main.py", line 734, in build
        exec(text, spec_namespace)
      File "<string>", line 16, in <module>
      File "C:\Users\Thomas\Projekte\pyinstaller-pyinstaller-b78bfe5\PyInstaller\building\build_main.py", line 162, in __init__
        raise ValueError("script '%s' not found" % script)
    ' not found script 'C:\Users\Thomas\Projekte\merge-documents\attachment-collector.spec

Pip installation of pyinstaller:

`Successfully installed future-0.15.2 pefile-2016.3.28 pyinstaller-3.2 pypiwin32-219`

Python version:

`Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900 64 bit (AMD64)] on win32`

My spec file attachment-collector.spec:

    # -*- mode: python -*-
    block_cipher = None
    a = Analysis(['attachment-collector.spec\r'],
                 pathex=['C:\\Users\\Thomas\\Projekte\\merge-documents'],
                 binaries=None,
                 datas=None,
                 hiddenimports=[],
                 hookspath=[],
                 runtime_hooks=[],
                 excludes=[],
                 win_no_prefer_redirects=False,
                 win_private_assemblies=False,
                 cipher=block_cipher)
    pyz = PYZ(a.pure, a.zipped_data,
                 cipher=block_cipher)
    exe = EXE(pyz,
              a.scripts,
              exclude_binaries=True,
              name='attachment-collector',
              debug=False,
              strip=False,
              upx=True,
              console=False )
    coll = COLLECT(exe,
                   a.binaries,
                   a.zipfiles,
                   a.datas,
                   strip=False,
                   upx=True,
                   name='attachment-collector')

What I tried:
- Install Python 3.4 (64Bit)
- Add quotation marks to the spec file: `"attachment-collector.spec"`
- Use the absolute path: `"C:\Users\Thomas\Projekte\merge-documents\attachment-collector.spec"`
- Try the development version: `python pyinstaller-pyinstaller-b78bfe5\pyinstaller.py "attachment-collector.spec"`
- Move Python to a path without spaces in the path: `"C:\Python\Python35"`

Any suggestion?
Greets, Thomas

**Comment by htgoebel** [comment]
> a = Analysis(['attachment-collector.spec\r'],

I assume the trailing `\r` here ist wrong :-)

**Comment by Chaoste** [comment]
Thank you! I don't know how this could happen but now It's working :)

**Comment by TravStu22** [comment]
I ran into this problem as well. I have a shell script that calls pyinstaller with a spec file. Turns out the line endings in my shell script got converted from LF to CR LF and this caused the \r to appear in the spec file in that same spot. I suspect git caused the EOL change, but no idea why CR LF line endings would cause the \r to appear in the spec file like that.
