### ISSUE TITLE
Dr. Web false positive

### ISSUE THREAD

**Issue by OctoNezd** [pyinstaller/pyinstaller#2200]
![2016-09-17 16 43 30](https://cloud.githubusercontent.com/assets/15308404/18608579/13c8350c-7cf6-11e6-97eb-c4194e617413.png)

**Comment by OctoNezd** [comment]
Also, false positive happens on compiled files

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is nothing(!) we can do here.

See [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
