### ISSUE TITLE
Clamscan show a malware in PyInstaller-3.2.tar.gz

### ISSUE THREAD

**Issue by andersonpy** [pyinstaller/pyinstaller#2209]
when i run clamav in my Linux, i get this infected file:

/home/Boss/Downloads/PyInstaller-3.2.tar.gz: Osx.Malware.Agent-1500020 FOUND

so its a false positive? can someone explain that?

**Comment by parabird** [comment]
when i build a py file to exe, anti-virus software reported look like u:
![360reportvirus](https://cloud.githubusercontent.com/assets/22056217/19219997/66f3bcf4-8e55-11e6-8508-9c060b0e9928.JPG)
platform:win7 
python version:3.5
pyinstaller version:3.2
the python's script file is just a simple file :(

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
