### ISSUE TITLE
pyinstaller packaging into DLL or PYD file?

### ISSUE THREAD

**Issue by denfromufa** [pyinstaller/pyinstaller#2218]
Can pyinstaller be used to package a library into DLL (Windows DLL) or PYD (Python C-Extension), but not into executable?

**Comment by htgoebel** [comment]
Short answer: No.

**Comment by denfromufa** [comment]
How about a long answer? :) Do you recommend other tools such nuitka or
cython for generating DLLs?

**Comment by htgoebel** [comment]
No, since I do not have any experience for building dlls.

**Comment by codewarrior0** [comment]
PyInstaller might serve as a starting point, if what you want to do is compact an entire Python interpreter and standard library into the DLL (such that it can be loaded into a non-Python application), but you will have to write a great deal of C code to manage the unpacking and loading of the Python interpreter into the process that is hosting the DLL as well as expose whatever entry points it expects. This part is far beyond PyInstaller's scope.

If all you want to do is create a PYD that can be loaded into an existing Python interpreter, Cython or Nuitka is your best bet.

**Comment by denfromufa** [comment]
btw, here is how someone managed to do this using nuitka with simple
instructions:

http://stackoverflow.com/a/39952006/2230844
