### ISSUE TITLE
Cannot find PyQt4 plugin directories

### ISSUE THREAD

**Issue by sasicDHH** [pyinstaller/pyinstaller#2224]
I have learn python for several weeks.

I try Micheal1.py convert to exe, But can't build Micheal1.exe

something about Micheal1.py:
1.produce a .gif photo
2.modules 
import pandas as pd
from pylab import mpl
import matplotlib.pyplot as plt
import numpy as np
from moviepy.video.io.bindings import mplfig_to_npimage
import moviepy.editor as mpy

HERE THE Problem

e:\work>pyinstaller -F Micheal1.py
124 INFO: PyInstaller: 3.3.dev0+b78bfe5
125 INFO: Python: 3.5.2
126 INFO: Platform: Windows-7-6.1.7601-SP1
129 INFO: wrote e:\work\Micheal1.spec
131 INFO: UPX is not available.
134 INFO: Extending PYTHONPATH with paths
['e:\work', 'e:\work']
136 INFO: checking Analysis
137 INFO: Building Analysis because out00-Analysis.toc is non existent
138 INFO: Initializing module dependency graph...
141 INFO: Initializing module graph hooks...
144 INFO: Analyzing base_library.zip ...
2848 INFO: running Analysis out00-Analysis.toc
3296 INFO: Caching module hooks...
3302 INFO: Analyzing e:\work\Micheal1.py
3333 INFO: Processing pre-find module path hook   distutils
3463 INFO: Processing pre-safe import module hook   six.moves
5884 INFO: Processing pre-find module path hook   site
5886 INFO: site: retargeting to fake-dir 'c:\users\administrator\appdata\loc
al\programs\python\python35\lib\site-packages\PyInstaller\fake-modules'
5906 INFO: Processing pre-safe import module hook   win32com
17790 INFO: Loading module hooks...
17792 INFO: Loading module hook "hook-distutils.py"...
17794 INFO: Loading module hook "hook-xml.py"...
17797 INFO: Loading module hook "hook-pkg_resources.py"...
18339 INFO: Loading module hook "hook-matplotlib.py"...
18710 INFO: Loading module hook "hook-lib2to3.py"...
18715 INFO: Loading module hook "hook-pythoncom.py"...
18979 INFO: Loading module hook "hook-scipy.linalg.py"...
18982 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
18984 INFO: Loading module hook "hook-sqlite3.py"...
19090 INFO: Loading module hook "hook-matplotlib.backends.py"...
19945 INFO:   Matplotlib backend "GTK": ignored
    Gtk\* backend requires pygtk to be installed.
20513 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk\* backend requires pygtk to be installed.
20917 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
21464 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
22761 INFO:   Matplotlib backend "Qt4Agg": added
23359 INFO:   Matplotlib backend "Qt5Agg": added
24009 INFO:   Matplotlib backend "TkAgg": added
24646 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
25320 INFO:   Matplotlib backend "WXAgg": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
64099 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
64660 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
65091 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\matplotlib\backends\backend_webagg.py", line 28, in <module>
    import tornado
ImportError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\matplotlib\backends\backend_webagg.py", line 30, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
65511 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'tornado'
66042 INFO:   Matplotlib backend "agg": added
66440 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
66806 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
67415 INFO:   Matplotlib backend "pdf": added
68088 INFO:   Matplotlib backend "pgf": added
68711 INFO:   Matplotlib backend "ps": added
69332 INFO:   Matplotlib backend "svg": added
69878 INFO:   Matplotlib backend "template": added
70378 INFO: Loading module hook "hook-sysconfig.py"...
70387 INFO: Loading module hook "hook-pywintypes.py"...
70650 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
70665 INFO: Loading module hook "hook-pytz.py"...
70739 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
70743 INFO: Loading module hook "hook-PyQt4.QtCore.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ImportError: DLL load failed: 鎵句笉鍒版寚瀹氱殑妯″潡銆?
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python35\Scripts\py
installer-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.3.dev0+b78bfe5', 'console_scripts', 'pyinst
aller')()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller__main__.py", line 90, in run
    run_build(pyi_config, spec_file, *_vars(args))
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, *_kwargs)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'
))
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\building\build_main.py", line 212, in **init**
    self.**postinit**()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\building\datastruct.py", line 161, in **postinit**
    self.assemble()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\building\build_main.py", line 470, in assemble
    module_hook.post_graph()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\building\imphook.py", line 409, in post_graph
    self._load_hook_module()
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\building\imphook.py", line 376, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\compat.py", line 744, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 388, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 809, in load_module
  File "<frozen importlib._bootstrap_external>", line 668, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\hooks\hook-PyQt4.QtCore.py", line 13, in <module>
    binaries = qt_plugins_binaries('codecs', namespace='PyQt4')
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\utils\hooks\qt.py", line 65, in qt_plugins_binaries
    pdir = qt_plugins_dir(namespace=namespace)
  File "c:\users\administrator\appdata\local\programs\python\python35\lib\site-p
ackages\PyInstaller\utils\hooks\qt.py", line 39, in qt_plugins_dir
    raise Exception('Cannot find {0} plugin directories'.format(namespace))
Exception: Cannot find PyQt4 plugin directories

**Comment by htgoebel** [comment]
Have you tried with a recent version of PyInstaller? Is the error still present?

**Comment by ankit1997** [comment]
Did somebody find any solution to this?

**Comment by programerTobyLai** [comment]
I uninstalled pyqt4
but it's useless...

**Comment by BoboTiG** [comment]
Closing as PyQt4 support has been removed since #5118.
