### ISSUE TITLE
Python 3.5 + PyQt5 to standalone exe error

### ISSUE THREAD

**Issue by semechKO** [pyinstaller/pyinstaller#2241]
I'm new to coding and I need to transform my py file to an exe. I tried py2exe and it didn't work with python 3.5. Then I tried pyinstaller and it worked, but when I added PyQt5 to the program, pyinstaller also failed. I need an exe which shows a gui after being activated. Here are the modules that I used in the program:

```
import P4
import time
from datetime import datetime,date
import traceback
import os
import sys
import threading
from PyQt5 import QtCore
from PyQt5 import QtGui
from PyQt5.QtWidgets import *
from PyQt5.QtCore import QCoreApplication, QTimer
```

I added QtDll's to the spec file and builded exe from it, but still I get the same mistake: 

![image](https://cloud.githubusercontent.com/assets/2655989/19766820/901eb820-9c58-11e6-8c38-05fdd5c37f36.png)

**Comment by akej74** [comment]
Not sure if this may be related to #2152...?

**Comment by xoviat** [comment]
Can you post the section in your spec file containing the QT DLLS?

**Comment by HuberTRoy** [comment]
May be you could try:
```
....
from PyQt5.QtCore import *
from PyQt5.QtGui import *
....
```

**Comment by htgoebel** [comment]
Following xoviat's advice https://github.com/pyinstaller/pyinstaller/issues/2455#issuecomment-279270584 closing this one as duplicate of #2455
