### ISSUE TITLE
Pyinstaller not able to add Icon on Windows 10

### ISSUE THREAD

**Issue by nirarad** [pyinstaller/pyinstaller#2245]
When running Pyinstaller on windows 10 the compilation fails when trying to add the icon file.

I'm using Python 2.7 with the following modules:
appdirs==1.4.0
colorama==0.3.7
cycler==0.10.0
future==0.15.2
lxml==3.6.0
matplotlib==1.5.3
netifaces==0.10.5
numpy==1.11.1
pefile==2016.3.28
Pillow==3.3.1
psutil==4.3.1
PyInstaller==3.2
PyMySQL==0.7.9
pyparsing==2.1.9
pypiwin32==219
PySide==1.2.2
python-dateutil==2.5.3
pytz==2016.6.1
PyYAML==3.12
redis==2.10.5
six==1.10.0
WMI==1.4.9
xlrd==1.0.0

On Windows 7 this issue does not happen (with the same python version and modules).
It might be that on windows 10 the relative icon path is not resolved.
Attached the full log file and the spec file.

[pyinstaller_log.txt](https://github.com/pyinstaller/pyinstaller/files/562026/pyinstaller_log.txt)
[spec file.zip](https://github.com/pyinstaller/pyinstaller/files/562072/spec.file.zip)

**Comment by dhyams** [comment]
Sorry to ask the obvious, but are you doubly sure that the icon file is there on your Windows 10 box?

What if you put the full path to the .ico file in your spec file; does that work?

And are you using the same version of PyInstaller on both Windows 7 and Windows 10 boxes?

**Comment by nirarad** [comment]
I'm sorry, I had an issue with the version control on my system.
It's was my mistake.
