### ISSUE TITLE
"zlib.error: Error -3 while decompressing data: incorrect header check" when trying to run the exe which is encrypted with pyinstaller.

### ISSUE THREAD

**Issue by Murtaza0xFF** [pyinstaller/pyinstaller#2247]
I'm packaging the exe using pyinstaller, and I'm also providing a key to encrypt it. But on trying to run the exe, I get the following error:

```
Traceback (most recent call last):
  File "<string>", line 25, in <module>
  File "C:\Users\Admin\Desktop\PyInstaller-3.0\PyInstaller\loader\pyimod03_importers.py", line 297, in load_module
    is_pkg, bytecode = self._pyz_archive.extract(real_fullname)
  File "C:\Users\Admin\Desktop\PyInstaller-3.0\PyInstaller\loader\pyimod02_archive.py", line 327, in extract
    obj = zlib.decompress(obj)
zlib.error: Error -3 while decompressing data: incorrect header check
pyiboot01_bootstrap returned -1
```

I don't get this error when I package it without a key.

**Comment by happlebao** [comment]
I just encountered same error.
it turns out I enable exclude the Crypto module.
hope it helps.

**Comment by derkan** [comment]
Run with `--clean` option after you change `block_cipher` value.

**Comment by BrendanSimon** [comment]
> Run with `--clean` option after you change `block_cipher` value.

@derkan : what do you mean by this?

I have this exact same issue (on Mac).  I invoke the pyinstaller script with `--key=ABCDEF0123456789`.

I have the `--clean` option in the same command.  I've tried putting `--key=` before and after the `--clean` but it makes no difference.

I also do an `rm -rf build dist` before invoking pyinstaller.

**Comment by htgoebel** [comment]
You are using an outdated version of PyInstaller. Only the newest version is supported. But encrypted bytecode is not working, see #3531

**Comment by BrendanSimon** [comment]
I'm using pyinstaller v3.4, which is the latest release.  The download page says:
> Release 3.4: stable, supports Python 2.7, 3.4–3.7

If the `--key=` option is no longer supported then the documentation needs to be updated to reflect that.  If it is supported and working on Python 2, but not on Python 3, then the documentation should reflect that.

That is the quickest way to clarify the issue and will make these reports and comments less frequent ;-)
