### ISSUE TITLE
build on an old MacOS fails to run on a new one

### ISSUE THREAD

**Issue by mingyuan-xia** [pyinstaller/pyinstaller#2249]
Hi I want to report some MacOS compatibility issues.
I packed a simple Helloworld app with Pyinstaller 3.2, python 2.7 (from brew) on different MacOSes and test compatibility. 
Here are some issues:
packed on 10.11 and run on 10.12.1: killed 9 (should work)
packed on 10.12.1 and run on 10.12: SIGILL illegal instruction (not compatible even between revisions?)

Much thanks.

**Comment by dhyams** [comment]
I've not seen this at all; I have a fairly complex app that I package with Pyinstaller 3.2 (slightly modified to add the OpenDocument capability).  It's built on El Capitan (10.11), and I've run it on Sierra (10.12), Yosemite (10.10), and Mavericks (10.9) successfully.  I've not been able to try anything older than Mavericks.

My Python 2.7 comes from the Anaconda distribution; is there any chance you could try that distro with your hello world app, and see if you have the same issue?

**Comment by mingyuan-xia** [comment]
It happens that our virtualenv was pinned to pyinstaller 3.1.1. After changing that to 3.2, our big program bundles and runs well. I will let our users use the 3.2-bundled version on different OSes for a while and report if any one encounter and OS problem. Thanks and sorry for the confusion.

**Comment by mingyuan-xia** [comment]
no more crash reports, thx, closing this
