### ISSUE TITLE
.EXE File created with pyinstaller works in Windows 7 but doesn't works in Windows 10

### ISSUE THREAD

**Issue by MrRushh** [pyinstaller/pyinstaller#2253]
Hi i have made a very simple script with python 3.5 and to use it in pc's that doesnt have Python I created a .exe using pyinstaller. It works perfectly in my computer that's using Windows 7 but when i pass the .exe to my dad's laptop with Windows 10 it doesnt work. It says: "failed to run script". My dad's laptop doesn't have Python installed but come on thats why i made the .exe file with pyinstaller. I need help. This is the command i use to create the .exe file

Pyinstaller --onefile myscript.py

The .exe file works in my computer but it doesn't work in other computer. What i'm doing wrong?

**Comment by chris-relaxing** [comment]
I have the same problem, but the opposite. I created a .exe on Windows 10 and it doesn't seem to work on Windows 7. Did you ever find out what the solution was?

**Comment by AndreFelipeCL** [comment]
I have the same issue here: created on W10 and doesn't runs on W7. 👎

**Comment by tallforasmurf** [comment]
@AndreFelipeCL see note on #3573
