### ISSUE TITLE
Windows defender reports runw as malware

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2255]
I am currently unsure of why this is the case, but runw.exe is classified as malware. 
![image](https://cloud.githubusercontent.com/assets/15351036/20113467/2a64cb5c-a5b6-11e6-8401-e5fb2525117a.png)

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by ProjectThreepio** [comment]
FWIW, compiling your own bootloader (possibly changing the source in an insignificant way) would give your bootloader a unique signature, which would be very unlikely to match the signature of any malware out there that may be using the same PyInstaller bootloader, and would probably do a pretty good job of preventing your executables from being seen as malware.

You should contact the AV vendor too, though.

**Comment by xoviat** [comment]
Wow, this is old.

**Comment by ProjectThreepio** [comment]
Whoops, sorry.  I didn't see that as I was commenting.  I recently reported this as a false positive to Symantec, then found this issue.
