### ISSUE TITLE
Fatal Error! Failed to execute Script

### ISSUE THREAD

**Issue by MrRushh** [pyinstaller/pyinstaller#2257]
I just built an executable for windows from a python scripts that imports modules like sys, os, pyhook and etc.

The executable works in my own computer but it doesnt works in other computers. It says "Failed to execute script" i don't know why is this happening. Here's my warn.txt file. it says that some moduls are missing but i don't know because it works perfectly in my pc but doesn't work in other machine.

HERE THE WARN.TXT

missing module named resource - imported by posix, C:\Users\Roberto\Desktop\beta1.pyw
missing module named posix - imported by os, C:\Users\Roberto\Desktop\beta1.pyw
missing module named _posixsubprocess - imported by subprocess, C:\Users\Roberto\Desktop\beta1.pyw
missing module named 'org.python' - imported by pickle, C:\Users\Roberto\Desktop\beta1.pyw, xml.sax
missing module named readline - imported by cmd, code, pdb, C:\Users\Roberto\Desktop\beta1.pyw
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\Users\Roberto\Desktop\beta1.pyw
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\Users\Roberto\Desktop\beta1.pyw
missing module named _winreg - imported by platform, C:\Users\Roberto\Desktop\beta1.pyw
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, C:\Users\Roberto\Desktop\beta1.pyw
missing module named 'java.lang' - imported by platform, C:\Users\Roberto\Desktop\beta1.pyw, xml.sax._exceptions
missing module named vms_lib - imported by platform, C:\Users\Roberto\Desktop\beta1.pyw
missing module named termios - imported by tty, C:\Users\Roberto\Desktop\beta1.pyw, getpass
missing module named grp - imported by tarfile, shutil, C:\Users\Roberto\Desktop\beta1.pyw
missing module named pwd - imported by posixpath, tarfile, shutil, http.server, webbrowser, C:\Users\Roberto\Desktop\beta1.pyw, netrc, getpass
missing module named ce - imported by os, C:\Users\Roberto\Desktop\beta1.pyw
missing module named _dummy_threading - imported by dummy_threading, C:\Users\Roberto\Desktop\beta1.pyw
missing module named org - imported by copy, C:\Users\Roberto\Desktop\beta1.pyw

**Comment by htgoebel** [comment]
is this still an open issue? If so, please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.
