### ISSUE TITLE
How can I add dynamic python modules to pyinstaller specs?

### ISSUE THREAD

**Issue by brupelo** [pyinstaller/pyinstaller#2259]
I've been trying to figure out [how to add dynamic python modules to pyinstallersspecs](http://stackoverflow.com/questions/40516042/how-to-add-dynamic-python-modules-to-pyinstallers-specs) for quite a while without succeeding, any help?

In the above link you'll also find a simple mcve in order to reproduce the issue.

Thanks in advance.

**Comment by bwoodsend** [comment]
[`collect_submodules("module.name")`](https://pyinstaller.readthedocs.io/en/stable/hooks.html#useful-items-in-pyinstaller-utils-hooks) is your go-to solution. Or write a hook if you want more control.
