### ISSUE TITLE
How to exactly pack Visual C++ Redistributable with Py 3.5+Pyinst. as standalone exe

### ISSUE THREAD

**Issue by Popkultur** [pyinstaller/pyinstaller#2260]
I am trying to package into a single executable, but it always says "DLL is not found" until I install Visual C++ Redistributable 2015. However, I want to make it run on a freshly installed WIndows (10). Is there a way to solve this problem? I tried with Python 3.5 on fully updated Windows 10 with SDK Kit and newest dev version 3.3

Thanks a lot for some help.

//edit: Seems like I managed to pack the correct DLLs.

**Comment by Helyux** [comment]
@Popkultur did you solve this yourself?
