### ISSUE TITLE
Hook For sound_lib

### ISSUE THREAD

**Issue by chrisnorman7** [pyinstaller/pyinstaller#2264]
Hi,
I've just written a hook for sound_lib, a project which I use quite a lot from:
http://hg.q-continuum.net/sound_lib

I'll attach the hook (which I tested) to this issue. Not sure if you want it as a PR or whatever, or if there's anything else I need to do to make the hook better.

Cheers,

Chris
[hook-sound_lib.zip](https://github.com/pyinstaller/pyinstaller/files/589198/hook-sound_lib.zip)

**Comment by chrisnorman7** [comment]
And here's the associated pull request:

#2267

**Comment by Legorooj** [comment]
Linked PR has been merged
