### ISSUE TITLE
Hook for accessible_output2

### ISSUE THREAD

**Issue by chrisnorman7** [pyinstaller/pyinstaller#2265]
Hi,
I've put together a hook for [accessible_output2](http://hg.q-continuum.net/accessible_output2).

Here it is:
[hook-accessible_output2.zip](https://github.com/pyinstaller/pyinstaller/files/589242/hook-accessible_output2.zip)

**Comment by htgoebel** [comment]
Thanks. We would appreciate an pull request we can easily merge.

**Comment by chrisnorman7** [comment]
OK, it's there at #2266.


HTH,

**Comment by Legorooj** [comment]
The linked PR has been merged.
