### ISSUE TITLE
unknown url type on https urllib2.urlopen 

### ISSUE THREAD

**Issue by jim-kelly** [pyinstaller/pyinstaller#2271]
Pyinstaller (version 3.2) executed on raspberry pi with default stock image which uses python 2.7.9

Executable produced by pyinstaller works fine on local machine and on another remote raspberry. The executable fails on a third party remote ARM box that is loaded with the equivalent of ubuntu 12.04 and python 2.7.3.  Failure is the same using a one file executable or a one directory build. The libraries provided by both of these are identical containing:
-rwxr-xr-x 1 callcabinet callcabinet  132568 Sep 17 21:54 _codecs_cn.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet  144872 Sep 17 21:54 _codecs_hk.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   26080 Sep 17 21:54 _codecs_iso2022.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet  226776 Sep 17 21:54 _codecs_jp.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet  124376 Sep 17 21:54 _codecs_kr.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   95704 Sep 17 21:54 _codecs_tw.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   19548 Sep 17 21:54 _hashlib.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   36668 Sep 17 21:54 _multibytecodec.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   80908 Sep 17 21:54 _ssl.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   40336 Sep 17 21:54 bz2.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   66008 Aug  6  2014 libbz2.so.1.0
-rwxr-xr-x 1 callcabinet callcabinet 1190108 Sep 27 06:50 libcrypto.so.1.0.0
-rwxr-xr-x 1 callcabinet callcabinet 3170180 Sep 17 21:54 libpython2.7.so.1.0
-rwxr-xr-x 1 callcabinet callcabinet  227624 Aug 12  2014 libreadline.so.6
-rwxr-xr-x 1 callcabinet callcabinet  248352 Sep 27 06:50 libssl.so.1.0.0
-rwxr-xr-x 1 callcabinet callcabinet  121252 Sep 29  2014 libtinfo.so.5
-rwxr-xr-x 1 callcabinet callcabinet   91888 Nov 29  2014 libz.so.1
-rwxr-xr-x 1 callcabinet callcabinet   21396 Sep 17 21:54 readline.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   10152 Sep 17 21:54 resource.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   17804 Sep 17 21:54 termios.arm-linux-gnueabihf.so

The following python code reproduces the problem:
import urllib2
import time

while 1:
    time.sleep(120)
    page_contents = urllib2.urlopen(                   "https://atmoscapture.callcabinet.com/RecordingInformationService.svc?wsdl")
    for line in page_contents.readlines():
        print line

If the open request is http, the script works.
If the script is run directly from the source, it works on all 3 target machines.

Raspberry uname -a and cat /etc/os-release:
Linux raspberrypi 4.4.17-v7+ #902 SMP Mon Aug 15 12:21:29 BST 2016 armv7l GNU/Linux
PRETTY_NAME="Raspbian GNU/Linux 8 (jessie)"
NAME="Raspbian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

3rd party box uname -a and cat /etc/os-release
Linux FSN8X00027 3.0.36-0-mx #3 SMP PREEMPT Thu Oct 1 16:11:32 SAST 2015 armv7l armv7l armv7l GNU/Linux
NAME="Ubuntu"
VERSION="12.04.5 LTS, Precise Pangolin"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu precise (12.04.5 LTS)"
VERSION_ID="12.04"

The stack trace at the time of the failure:
Traceback (most recent call last):
  File "wandertest.py", line 6, in <module>
  File "urllib2.py", line 154, in urlopen
  File "urllib2.py", line 431, in open
  File "urllib2.py", line 454, in _open
  File "urllib2.py", line 409, in _call_chain
  File "urllib2.py", line 1265, in unknown_open
urllib2.URLError: <urlopen error unknown url type: https>

**Comment by htgoebel** [comment]
1) The exact error message is missing
2) Please try the current development version.

**Comment by jim-kelly** [comment]
File "urllib2.py", line 1265, in unknown_open
urllib2.URLError: <urlopen error unknown url type: https>

**Comment by jim-kelly** [comment]
It appears that there is a problem with the past operation. The error text is placed between a less than and a greater than characters. Only after submitting with the comment button do you see that the error text has been deleted.  I removed them in this paste.

File "urllib2.py", line 1265, in unknown_open
urllib2.URLError:  urlopen error unknown url type: https

**Comment by jim-kelly** [comment]
Thanks for the quick follow up. The results were the same with the development version. I did notice that the 3 of the libraries that were loaded have their names changed:
              from
-rwxr-xr-x 1 callcabinet callcabinet   21396 Sep 17 21:54 readline.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   10152 Sep 17 21:54 resource.arm-linux-gnueabihf.so
-rwxr-xr-x 1 callcabinet callcabinet   17804 Sep 17 21:54 termios.arm-linux-gnueabihf.so
                         to
-rwxr-xr-x 1 callcabinet callcabinet   21396 Sep 17 21:54 readline.so
-rwxr-xr-x 1 callcabinet callcabinet   10152 Sep 17 21:54 resource.so
-rwxr-xr-x 1 callcabinet callcabinet   17804 Sep 17 21:54 termios.so
