### ISSUE TITLE
Inspect module behaves differently when double clicked vs launched from cmd line in Win

### ISSUE THREAD

**Issue by coolarm** [pyinstaller/pyinstaller#2272]
I am using `inspect` module in `package.py` to obtain callee function in `Main.py`. When I double click `Main.exe`, the code context is not received in `printargs()`. However, it is perfectly normal when I launch `Main.exe` from cmd line. 

https://gist.github.com/coolarm/81ce27a11164a8bd640a3c5863a26c95

System configuration:
Python 3.5.2 Jun 25 2016 Build
Win 7
Pyinstaller development version 

I would like to be able to address this difference

Thank you for your time!

**Comment by Legorooj** [comment]
@coolarm is this still a valid issue? With PyInstaller 4.0.dev?

**Comment by coolarm** [comment]
Sorry. I dont manage that package or PyInstaller anymore. I am unable to verify if it is an issue on 4.0dev.

**Comment by Legorooj** [comment]
@coolarm ok thanks. I'll close this issue, and we can deal with it if someone else reports it.
