### ISSUE TITLE
how to import relative path in pyinstaller?

### ISSUE THREAD

**Issue by yu-yang2** [pyinstaller/pyinstaller#2273]
I have write `from .settings import APISERVER_IP`  in my code, after build success, when I excute the file, python told me `ImportError: cannot import name 'APISERVER_IP'`, Can I use hidden import or hook? I can't find this in the document.

**Comment by jxltom** [comment]
For me, relative import is working perfectly.

**Comment by htgoebel** [comment]
Please check your setup.

What you describe is not a relative input. The `.settings` part is a relative input, but it fails on `.APISERVER_IP`. So you either imprt the wrong `.stettings` packge/module, or `APISERVER_IP` is not defined there.
