### ISSUE TITLE
How to both exclude a module and have a build-time hook run for it?

### ISSUE THREAD

**Issue by blah238** [pyinstaller/pyinstaller#2275]
If I add a module to my spec file's Analysis `excludes` parameter, my build-time hook for said module is skipped.

If I don't exclude it in the spec file, but put it in the `excludedmodules` property of the build-time hook, it is not excluded because the module is directly imported in the program. This results in a whole bunch of DLL dependencies being packaged which I definitely don't want.

I want to exclude it because it's part of a commercial application (ArcGIS Desktop) that will be already installed on the end user's machine.

Note that I *was* able to [get it working](https://github.com/pyinstaller/pyinstaller/issues/576#issuecomment-261419085) using only the spec file and a runtime hook but I'd like to formalize the module's exclusion and hidden imports with a build-time hook that I might then be able contribute back to PyInstaller as an official hook for the benefit of other users.

If it matters, I'm using version [`3.3.dev0+483c819`](https://github.com/pyinstaller/pyinstaller/tree/483c819d6a256b58db6740696a901bd41c313f0c) on Windows 7.

**Comment by bwoodsend** [comment]
Sounds like you should break your package up into smaller packages or split the hook if you only want one but not the other.
