### ISSUE TITLE
Python exception on a simple pywebview code

### ISSUE THREAD

**Issue by dedablio** [pyinstaller/pyinstaller#2277]
I find an error when freezing python code with pywebview, 
The problem is when you run the .exe file. _Using windows 7, Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18), pyinstaller 3.3.dev0+483c819_

Here is a simple code that shows the bug:
```
#! /usr/bin/env python
import webview    ### https://github.com/r0x0r/pywebview
print ("starting...")
webview.create_window('Teste','http://google.com',1000,800)
sys.exit(0)
```

This code runs ok on Idle. 
Here is what one gets when running the .exe file:
```
C:\Python\Musica\dist\teste>teste
starting...
INFO:webview:Using .NET

Exceção Sem Tratamento: Python.Runtime.PythonException: ArgumentException : O identificador do Win32 transmitido para Icon é inválido ou tem tipo errado.
   em System.Drawing.Icon..ctor(IntPtr handle, Boolean takeOwnership)
   em System.Drawing.Icon..ctor(IntPtr handle)
   em System.Drawing.Icon.FromHandle(IntPtr handle)
   em Python.Runtime.Dispatcher.Dispatch(ArrayList args)
   em __System_Threading_ThreadStartDispatcher.Invoke()
   em System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()

C:\Python\Musica\dist\teste>
```

Already tryed to erase pyinstaller cache, upgrade it (had older version before), checking logs...

Anyone has ideas what else I can check to find the problem? 
Does it look like a pyinstaller bug?

Thanks,
Djony

**Comment by anasofgo** [comment]
I got the same error, windows 10 (64 bit), python 3.43, pyinstaller 3.3.dev0+483c819

**Comment by htgoebel** [comment]
The traceback is not created by Python. I don't understand what "O identificador do Win32 transmitido para Icon é inválido ou tem tipo errado." mean, but maybe this is the key. Maybe the pywebview developers can help?

I'm afraid, there is nobody around who can help you on this. So I'm closing the ticket now. If somebody find a solution, feel free to add a comment.

**Comment by htgoebel** [comment]
Also see #2278.
