### ISSUE TITLE
Extracting an application icon from pyinstaller executable using Win32 causes a crash

### ISSUE THREAD

**Issue by r0x0r** [pyinstaller/pyinstaller#2278]
The author of [pywebview](https://github.com/r0x0r/pywebview) is here.
A standard way to extract an icon from the Windows executable causes the program frozen with Pyinstaller to crash.

```
handler = windll.kernel32.GetModuleHandleW(None)
icon_handler = windll.user32.LoadIconW(handler, 1)
```

This code works fine in an unfrozen program.  Is this a bug in how pyinstaller packs an application icon in an executable? Or is any other way to extract an icon from?

The motivation fo this is to set to the application icon in Win32/Winforms based GUIs.

**Comment by htgoebel** [comment]
Have you tried --onedir more (which is the default)?

Please note that when using this in a unfrozen application, the icons of python.exe are used, while in the frozen app, the icons from the pyinstaller bootloader. So to properly test unfrozen, you'll need e.g. GetModuleHandleW("PyInstaller\bootloader\Windows-64bit\run.exe"). Maybe Winodws does not like the icons included in the bootloader?

HTH.
