### ISSUE TITLE
Failed to execute script pyi_rth_qt5plugins

### ISSUE THREAD

**Issue by MagicalBomb** [pyinstaller/pyinstaller#2279]
I use : Python3.5.2-64bit , Window 8.1 64bit

I'm sure I had installed all packages required ( PyWin32 , pypiwin32 and pefile  ).
but when I run my program (chartorserv.exe), it told me “Failed to execute script pyi_rth_qt5plugins”
I dont know why. 

The following lines is pyinstaller's output:

W:\Tools\Python\Python3.5.2_64\Scripts>pyinstaller -w -F C:\Users\Magicalbomb\De
sktop\Work\myPyLab\Projections\Chator\chatorserv.py
111 INFO: PyInstaller: 3.3.dev0+483c819
111 INFO: Python: 3.5.2
112 INFO: Platform: Windows-8.1-6.3.9600-SP0
113 INFO: wrote W:\Tools\Python\Python3.5.2_64\Scripts\chatorserv.spec
115 INFO: UPX is not available.
119 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Magicalbomb\\Desktop\\Work\\myPyLab\\Projections\\Chator',
 'W:\\Tools\\Python\\Python3.5.2_64\\Scripts']
119 INFO: checking Analysis
120 INFO: Building Analysis because out00-Analysis.toc is non existent
120 INFO: Initializing module dependency graph...
122 INFO: Initializing module graph hooks...
123 INFO: Analyzing base_library.zip ...
2914 INFO: running Analysis out00-Analysis.toc
3323 INFO: Caching module hooks...
3330 INFO: Analyzing C:\Users\Magicalbomb\Desktop\Work\myPyLab\Projections\Chato
r\chatorserv.py
3347 INFO: Loading module hooks...
3347 INFO: Loading module hook "hook-pydoc.py"...
3348 INFO: Loading module hook "hook-PyQt5.py"...
3350 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
3810 INFO: Loading module hook "hook-xml.py"...
4009 INFO: Loading module hook "hook-PyQt5.Qt.py"...
4010 INFO: Loading module hook "hook-encodings.py"...
4121 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
4122 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
4195 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
4285 INFO: Looking for ctypes DLLs
4293 INFO: Analyzing run-time hooks ...
4297 INFO: Including run-time hook 'pyi_rth_qt5.py'
4299 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
4306 INFO: Looking for dynamic libraries
4415 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qico.dll
4519 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qico.dll
4632 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qwindows.dll
4747 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qwindows.dll
4919 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qdds.dll
5043 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qdds.dll
5155 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qgif.dll
5263 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qgif.dll
5378 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qoffscreen.dll
5497 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qoffscreen.dll
5612 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qtga.dll
5731 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qtga.dll
5852 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qtiff.dll
5962 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qtiff.dll
6094 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qwbmp.dll
6205 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qwbmp.dll
6322 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\iconengines\qsvgicon.dll
8085 WARNING: lib not found: Qt5Svg.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\iconengines\qsvgicon.dll
8191 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\iconengines\qsvgicon.dll
8305 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qjpeg.dll
8415 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qjpeg.dll
8542 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qminimal.dll
8657 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qminimal.dll
8772 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qsvg.dll
8882 WARNING: lib not found: Qt5Svg.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qsvg.dll
8983 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qsvg.dll
9094 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qicns.dll
9200 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qicns.dll
9310 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qwebp.dll
9414 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qwebp.dll
9524 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\printsupport\windowsprintersupport.dll
9627 WARNING: lib not found: Qt5PrintSupport.dll dependency of W:\Tools\Python\P
ython3.5.2_64\lib\site-packages\PyQt5\Qt\plugins\printsupport\windowsprintersupp
ort.dll
9741 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\printsupport\windowsprintersupport.dll
10002 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.
5.2_64\lib\site-packages\PyQt5\QtCore.pyd
10120 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.
5.2_64\lib\site-packages\PyQt5\QtPrintSupport.pyd
10227 WARNING: lib not found: Qt5PrintSupport.dll dependency of W:\Tools\Python\
Python3.5.2_64\lib\site-packages\PyQt5\QtPrintSupport.pyd
10329 WARNING: lib not found: Qt5Widgets.dll dependency of W:\Tools\Python\Pytho
n3.5.2_64\lib\site-packages\PyQt5\QtPrintSupport.pyd
10434 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\QtPrintSupport.pyd
10550 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.
5.2_64\lib\site-packages\PyQt5\QtGui.pyd
10656 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\QtGui.pyd
10773 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.
5.2_64\lib\site-packages\PyQt5\QtWidgets.pyd
10879 WARNING: lib not found: Qt5Widgets.dll dependency of W:\Tools\Python\Pytho
n3.5.2_64\lib\site-packages\PyQt5\QtWidgets.pyd
10984 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\QtWidgets.pyd
10990 INFO: Looking for eggs
10991 INFO: Using Python library W:\Tools\Python\Python3.5.2_64\python35.dll
10991 INFO: Found binding redirects:
[]
10995 INFO: Warnings written to W:\Tools\Python\Python3.5.2_64\Scripts\build\cha
torserv\warnchatorserv.txt
11016 INFO: checking PYZ
11016 INFO: Building PYZ because out00-PYZ.toc is non existent
11016 INFO: Building PYZ (ZlibArchive) W:\Tools\Python\Python3.5.2_64\Scripts\bu
ild\chatorserv\out00-PYZ.pyz
11752 INFO: checking PKG
11753 INFO: Building PKG because out00-PKG.toc is non existent
11753 INFO: Building PKG (CArchive) out00-PKG.pkg
16661 INFO: Bootloader W:\Tools\Python\Python3.5.2_64\lib\site-packages\pyinstal
ler-3.3.dev0+483c819-py3.5.egg\PyInstaller\bootloader\Windows-64bit\runw.exe
16661 INFO: checking EXE
16662 INFO: Building EXE because out00-EXE.toc is non existent
16662 INFO: Building EXE from out00-EXE.toc
16662 INFO: Appending archive to EXE W:\Tools\Python\Python3.5.2_64\Scripts\dist
\chatorserv.exe

W:\Tools\Python\Python3.5.2_64\Scripts>pyinstaller -w -F C:\Users\Magicalbomb\De
sktop\Work\myPyLab\Projections\Chator\chatorserv.py
122 INFO: PyInstaller: 3.3.dev0+483c819
122 INFO: Python: 3.5.2
123 INFO: Platform: Windows-8.1-6.3.9600-SP0
124 INFO: wrote W:\Tools\Python\Python3.5.2_64\Scripts\chatorserv.spec
126 INFO: UPX is not available.
130 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Magicalbomb\\Desktop\\Work\\myPyLab\\Projections\\Chator',
 'W:\\Tools\\Python\\Python3.5.2_64\\Scripts']
130 INFO: checking Analysis
131 INFO: Building Analysis because out00-Analysis.toc is non existent
131 INFO: Initializing module dependency graph...
133 INFO: Initializing module graph hooks...
135 INFO: Analyzing base_library.zip ...
2854 INFO: running Analysis out00-Analysis.toc
3310 INFO: Caching module hooks...
3315 INFO: Analyzing C:\Users\Magicalbomb\Desktop\Work\myPyLab\Projections\Chato
r\chatorserv.py
3330 INFO: Loading module hooks...
3330 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
3749 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
3750 INFO: Loading module hook "hook-xml.py"...
3948 INFO: Loading module hook "hook-encodings.py"...
4059 INFO: Loading module hook "hook-PyQt5.py"...
4060 INFO: Loading module hook "hook-pydoc.py"...
4060 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
4139 INFO: Loading module hook "hook-PyQt5.Qt.py"...
4141 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
4227 INFO: Looking for ctypes DLLs
4236 INFO: Analyzing run-time hooks ...
4239 INFO: Including run-time hook 'pyi_rth_qt5.py'
4241 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
4247 INFO: Looking for dynamic libraries
4371 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qwbmp.dll
4473 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qwbmp.dll
4588 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\printsupport\windowsprintersupport.dll
4691 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\printsupport\windowsprintersupport.dll
4801 WARNING: lib not found: Qt5PrintSupport.dll dependency of W:\Tools\Python\P
ython3.5.2_64\lib\site-packages\PyQt5\Qt\plugins\printsupport\windowsprintersupp
ort.dll
4912 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qdds.dll
5012 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qdds.dll
5126 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\iconengines\qsvgicon.dll
5232 WARNING: lib not found: Qt5Svg.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\iconengines\qsvgicon.dll
5335 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\iconengines\qsvgicon.dll
5446 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qgif.dll
5567 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qgif.dll
5680 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qwebp.dll
5795 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qwebp.dll
5909 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qjpeg.dll
6015 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qjpeg.dll
6132 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qicns.dll
6238 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qicns.dll
6355 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qminimal.dll
6458 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qminimal.dll
6571 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qoffscreen.dll
6672 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qoffscreen.dll
6802 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qtga.dll
6906 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qtga.dll
7018 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qwindows.dll
7137 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\platforms\qwindows.dll
7274 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qsvg.dll
7376 WARNING: lib not found: Qt5Svg.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qsvg.dll
7479 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qsvg.dll
7593 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qtiff.dll
7693 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qtiff.dll
7805 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qico.dll
7906 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\Qt\plugins\imageformats\qico.dll
8178 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\QtCore.pyd
8294 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\QtPrintSupport.pyd
8397 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\QtPrintSupport.pyd
8498 WARNING: lib not found: Qt5Widgets.dll dependency of W:\Tools\Python\Python
3.5.2_64\lib\site-packages\PyQt5\QtPrintSupport.pyd
8601 WARNING: lib not found: Qt5PrintSupport.dll dependency of W:\Tools\Python\P
ython3.5.2_64\lib\site-packages\PyQt5\QtPrintSupport.pyd
8709 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\QtGui.pyd
8810 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\QtGui.pyd
8920 WARNING: lib not found: Qt5Gui.dll dependency of W:\Tools\Python\Python3.5.
2_64\lib\site-packages\PyQt5\QtWidgets.pyd
9021 WARNING: lib not found: Qt5Core.dll dependency of W:\Tools\Python\Python3.5
.2_64\lib\site-packages\PyQt5\QtWidgets.pyd
9141 WARNING: lib not found: Qt5Widgets.dll dependency of W:\Tools\Python\Python
3.5.2_64\lib\site-packages\PyQt5\QtWidgets.pyd
9153 INFO: Looking for eggs
9153 INFO: Using Python library W:\Tools\Python\Python3.5.2_64\python35.dll
9153 INFO: Found binding redirects:
[]
9158 INFO: Warnings written to W:\Tools\Python\Python3.5.2_64\Scripts\build\chat
orserv\warnchatorserv.txt
9174 INFO: checking PYZ
9175 INFO: Building PYZ because out00-PYZ.toc is non existent
9175 INFO: Building PYZ (ZlibArchive) W:\Tools\Python\Python3.5.2_64\Scripts\bui
ld\chatorserv\out00-PYZ.pyz
9930 INFO: checking PKG
9931 INFO: Building PKG because out00-PKG.toc is non existent
9931 INFO: Building PKG (CArchive) out00-PKG.pkg
14857 INFO: Bootloader W:\Tools\Python\Python3.5.2_64\lib\site-packages\pyinstal
ler-3.3.dev0+483c819-py3.5.egg\PyInstaller\bootloader\Windows-64bit\runw.exe
17406 INFO: checking EXE
17408 INFO: Building EXE because out00-EXE.toc is non existent
17408 INFO: Building EXE from out00-EXE.toc
17408 INFO: Appending archive to EXE W:\Tools\Python\Python3.5.2_64\Scripts\dist
\chatorserv.exe

**Comment by buha** [comment]
I subscribe, experiencing the same issue.

**Comment by buha** [comment]
The fix for me was to add Qt libs dir to Windows `PATH`. That is, `C:\Qt\5.7\msvc2015\bin` for me.
