### ISSUE TITLE
If you make a script with the same name as module, it will not work. (no error)

### ISSUE THREAD

**Issue by EloiseSeverin** [pyinstaller/pyinstaller#2285]
If you make a script with the same name as module, it will not work. (There is no error.)
like this.
(Python 3.5.2 / PyInstaller-3.3.dev0+g483c819)

> sample.py
> sample/__init__.py

pyinstaller creates an exe file successfully. but nothing happens when executed
and no error.

**Comment by htgoebel** [comment]
In Python you can not have a scripted called like a package in the same directory.  The script will overwrite the package.
