### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by AleksVan** [pyinstaller/pyinstaller#2292]
Hello!
FreeBSD 11.0-RELEASE-p1 amd64
Installing mod_security for apache24 and get the error. What to do?
![img_20161129_105522](https://cloud.githubusercontent.com/assets/24237988/20693667/43ff0578-b623-11e6-8995-efdc8761c5ff.jpg)

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

Please provide more details (not a screenshot), see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by htgoebel** [comment]
BTW: When looking at this screen-photo, I can't see hos this should be related to pyinstaller. Closing as invalid.
