### ISSUE TITLE
pls bundle python3.dll automatically

### ISSUE THREAD

**Issue by sglebs** [pyinstaller/pyinstaller#2293]
Some modules with C code link against python3.dll so they can run against Python 3.4, 3.5 etc. Unfortunately PyInstaller is not bundling in this file (python3.dll). I had to manually add it to the *datas* section, after much trial-and-error. Please see https://github.com/pyinstaller/pyinstaller/issues/2261 , at the end.

Can this be done automatically please? Thanks!

**Comment by htgoebel** [comment]
Bundling this sould not be much of a problem. Would you like to submit a pull-request?

`PyInstaller.building.build_main.Analysis._check_python_library()` would be a good place for this.
