### ISSUE TITLE
ImportError: No module named _xml

### ISSUE THREAD

**Issue by dinesh2501** [pyinstaller/pyinstaller#2295]
Hello ,
I have some python script which included GUI based on wxPython.It works fine when run my script in IDLE and pyscripter.
When I built it using pyInstaller to create EXE, ended up with below error.
Even though _xml.pyd is present in "Python27\Lib\site-packages\wx"

python version 2.7
pyInstaller 3.2

Traceback (most recent call last):
  File "Test.py", line 56, in <module>
  File "c:\users\dinesh\appdata\local\temp\pip-build-bj9xp0\pyinstaller\PyInstal
ler\loader\pyimod03_importers.py", line 389, in load_module
  File "GUI.py", line 18, in <module>
  File "c:\users\dinesh\appdata\local\temp\pip-build-bj9xp0\pyinstaller\PyInstal
ler\loader\pyimod03_importers.py", line 389, in load_module
  File "site-packages\wx\xrc.py", line 10, in <module>
  File "c:\users\dinesh\appdata\local\temp\pip-build-bj9xp0\pyinstaller\PyInstal
ler\loader\pyimod03_importers.py", line 546, in load_module
ImportError: No module named _xml

**Comment by htgoebel** [comment]
Please try the current development version.

**Comment by dinesh2501** [comment]
Hi,
you mean current development version of python(Python 3.5)?

**Comment by htgoebel** [comment]
I mean the current development version of PyInstaller, see [How ro report bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by dinesh2501** [comment]
I tried with current development version .Still it gives the same error.
also tried --onedir. Same  issue.

**Comment by grzanka** [comment]
I am experiencing similar problem with pyinstaller 3.2.1. 
@dinesh2501 did you get any solution ?

**Comment by dinesh2501** [comment]
Hello grzanka,
I just removed "import xrc" from my code and it worked.
import xrc was unnecessarily added by wxformbuilder tool in my code.

**Comment by grzanka** [comment]
Finally I've also fixed this issue by adding `--hidden-import wx --hidden-import wx._xml` flags to pyinstaller command. But thanks anyway !

**Comment by skywhat** [comment]
what a great suggestion.
removed "import xrc" from my code and it worked.
Thanks a lot for helping me get through.
