### ISSUE TITLE
Mistype in the help?

### ISSUE THREAD

**Issue by alex-pobeditel-2004** [pyinstaller/pyinstaller#2297]
Hi!  
I think there is string with a mistype in the pyinstaller help:  
```
--exclude-module EXCLUDES  
Optional module or package (his Python names, not path names) that will be ignored
```
Wasn't "**his Python name, not path name**" meant here?

**Comment by htgoebel** [comment]
Yes, you are right. Thanks for pointing this out. To make this correct English, it should even read **it's Python name, not it's path name**, as in English there is no grammatical gender for things.

(Side-note: When fixing we should set metavar="MODULE", too.)

**Comment by tallforasmurf** [comment]
Caution! In English there is an unfortunate confusion which affects many native speakers as well.

The possessive form of **it** is **its** (no apostrophe). This is like the possessives of **he**, **her**, **their** (his, hers, theirs).

The contraction of **it is** to a single word is spelled **it's**, as in "It's a shame how English reveals its complexity."

**Comment by xoviat** [comment]
This issue has already been fixed; I would recommend it be closed.
