### ISSUE TITLE
assertion 'G_IS_OBJECT (object)' failed

### ISSUE THREAD

**Issue by gpraceman** [pyinstaller/pyinstaller#2300]
When trying to run my packaged Python Gtk app, it crashes and I get the following error:

/Users/gpraceman/Documents/workspace/derbyManager/dist/GrandPrix/main/winMain.py:106: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
Abort trap: 6

This error occurs on the line where Gtk should show the main screen of the app.

I’ve tried disabling UPX, installing the latest dev release of PyInstaller and clearing the PyInstaller cache.  Same error occurs with a onedir and onefile build.

OS X Yosemite 10.10.5
Python 3.5.2
Gtk 3.22.4
PyInstaller 3.3.dev0+483c819

I have successfully packaged and run this same app under Windows.  I can also successfully run this app from my OS X development environment.

Not so sure how you could reproduce this unless I give you my whole app, which I cannot do.  Trying to run a very simple Python Gtk3 app that has been packaged does not give that error.

I’ve really struggled to get this working under OS X and really would appreciate some guidance.  I’ve tried posting twice to the PyInstaller Google Group and the posts have never shown up there.

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.

**Comment by gpraceman** [comment]
Must be clearing out old bug reports, seeing as I opened up this one 4
years ago.  I didn't see the query back in July.  Anyways, I was later able
to get PyInstaller 3.4 working on that Mac but only on Python 3.6.8.  Got
some "Security-Alert: try to store file outside of dist-directory.
Aborting. '../../../include/python3.7m/pyconfig.h'" error on Python 3.7.3,
but at this point, that is water under the bridge.

Randy
