### ISSUE TITLE
Fatal error! When I make a script with --noconsole

### ISSUE THREAD

**Issue by willyamyep** [pyinstaller/pyinstaller#2302]
I try to make an executable with the --noconsole option but when i launch it it makes a "Fatal error!" message.
Otherwise, if i make the same executable without the --noconsole option it works. I have always make scripts with --noconsole but it worked fine. In my script I am using os and socket module.

Please can someone help me, I don't know how to do...

**Comment by tallforasmurf** [comment]
Lots more detail needed. Suggest you review https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs, especially the bottom part, "Information we need".

**Comment by willyamyep** [comment]
Okey I'll give you more details,
The problem comes when i launch the .exe, i see a message pop up stating : "Fatal Error! Failed to execute script ..."
I use python version 3.4.4 and pyinstaller 3.3.
I'm working on Windows 10.
I exactly use this command line : "pyinstaller.exe --onefile --noconsole SD.py" and when I launch the exe I've got the error. If I launch without the "--noconsole" option I have the console which pop and all works fine. If I change my .py in .pyw and launch it with pythonw the console doesn't pop and all is good. It's just a "--noconsole" bug and I'd like to fix it.
Thx for your answers.

**Comment by tallforasmurf** [comment]
When you have a console, what appears in it?

Is there any more to the "Fatal Error" message? Something to indicate what module is failing?

**Comment by willyamyep** [comment]
When I launch the exe with console nothing appears in it because nothing must appear. My program just open a port as a server and wait for connections. That's why I don't want an useless console..

No it's a little pop up wich just say "Fatal Error ! Failed to execute the script SD".

**Comment by tallforasmurf** [comment]
Ok... the message is created in [pyi_globalc](https://github.com/pyinstaller/pyinstaller/blob/b78bfe530cdc2904f65ce098bdf2de08c9037abb/bootloader/src/pyi_global.c#L61)...

It is given the name FATALERROR [here](https://github.com/pyinstaller/pyinstaller/blob/b78bfe530cdc2904f65ce098bdf2de08c9037abb/bootloader/src/pyi_global.h#L89)

And it is called in [a number of places](https://github.com/pyinstaller/pyinstaller/search?utf8=%E2%9C%93&q=FATALERROR&type=Code).

All of those calls seem to pass message texts which ought to appear. So I'm baffled. Anybody else?

**Comment by willyamyep** [comment]
All this is too complicated for me so I tryed to use py2exe and I have finaly succeeded to create an exe without console which works fine.
Thank you for helping me.
