### ISSUE TITLE
No module named tools.packaging.pyinstaller_hooks

### ISSUE THREAD

**Issue by DaytonaJohn** [pyinstaller/pyinstaller#2311]
Running Python 2.7.12 with Kivy 1.9.1 under Kubuntu 16.04 (64 bit).

I installed PyInstaller using pip, but when I try to run PyInstaller I get an error:

'No module named tools.packaging.pyinstaller_hooks'

Here is the complete traceback:

> Traceback (most recent call last):
7234 WARNING: stderr: Traceback (most recent call last):
   File "/usr/local/bin/pyinstaller", line 9, in <module>
7234 WARNING: stderr:   File "/usr/local/bin/pyinstaller", line 9, in <module>
     load_entry_point('PyInstaller==3.2', 'console_scripts', 'pyinstaller')()
7234 WARNING: stderr:     load_entry_point('PyInstaller==3.2', 'console_scripts', 'pyinstaller')()
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 90, in run
7234 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 90, in run
     run_build(pyi_config, spec_file, **vars(args))
7234 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 46, in run_build
7234 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 46, in run_build
     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
7234 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 788, in main
7235 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 788, in main
     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
7235 WARNING: stderr:     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 734, in build
7235 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 734, in build
     exec(text, spec_namespace)
7235 WARNING: stderr:     exec(text, spec_namespace)
   File "<string>", line 16, in <module>
7235 WARNING: stderr:   File "<string>", line 16, in <module>
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 212, in __init__
7235 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 212, in __init__
     self.__postinit__()
7235 WARNING: stderr:     self.__postinit__()
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/datastruct.py", line 178, in __postinit__
7235 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/datastruct.py", line 178, in __postinit__
     self.assemble()
7235 WARNING: stderr:     self.assemble()
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 470, in assemble
7236 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 470, in assemble
     module_hook.post_graph()
7236 WARNING: stderr:     module_hook.post_graph()
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/imphook.py", line 409, in post_graph
7236 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/imphook.py", line 409, in post_graph
     self._load_hook_module()
7236 WARNING: stderr:     self._load_hook_module()
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/imphook.py", line 376, in _load_hook_module
7236 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/imphook.py", line 376, in _load_hook_module
     self.hook_module_name, self.hook_filename)
7236 WARNING: stderr:     self.hook_module_name, self.hook_filename)
   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/hooks/hook-kivy.py", line 14, in <module>
7236 WARNING: stderr:   File "/usr/local/lib/python2.7/dist-packages/PyInstaller/hooks/hook-kivy.py", line 14, in <module>
     from kivy.tools.packaging.pyinstaller_hooks import (
7236 WARNING: stderr:     from kivy.tools.packaging.pyinstaller_hooks import (
 ImportError: No module named tools.packaging.pyinstaller_hooks
7236 WARNING: stderr: ImportError: No module named tools.packaging.pyinstaller_hooks

It appears that tools.packaging.pyinstaller_hooks was not installed when I installed PyInstalller. Re-installed with same issue. Tried to install from source, but it appears that lsbcc is not available for Ubuntu 16.04.

**Comment by htgoebel** [comment]
`tools.packaging.pyinstaller_hooks` is not part of PyInstaller. I assume it belongs to Kivy. Please check your Kivy istallation.
