### ISSUE TITLE
GTK3 StatusIcon

### ISSUE THREAD

**Issue by filonenko-mikhail** [pyinstaller/pyinstaller#2316]
I have small python gtk3 gui application with status bar icon. I use GtkStatusIcon class, and all things work fine. But after i bundle app with pyinstaller, there is problem. When I run bundled application, there is no image in the status bar, but probably one pixel area is using for events, like mouse click and others.

It seems that some of image codecs are missed, but i am not familiar with gtk3.

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.
