### ISSUE TITLE
(Gtk+3) Gtk.Window.self.set_icon_from_file() 

### ISSUE THREAD

**Issue by thekswenson** [pyinstaller/pyinstaller#2318]
I've constructed a minimal Gtk+3 example that has only a window but associates with the window a png using Gtk.Window.self.set_icon_from_file().
The program runs normally when called with the python interpreter.

After compilation with the appropriate datas line as
   `datas=[('graph.png','.')],`
I get the following error:

> => dist/set_icon_from_file/set_icon_from_file 
> Gtk-Message: Failed to load module "canberra-gtk-module"
> Traceback (most recent call last):
>   File "set_icon_from_file.py", line 24, in <module>
>     main()
>   File "set_icon_from_file.py", line 18, in main
>     window = DotWindow()
>   File "set_icon_from_file.py", line 14, in __init__
>     self.set_icon_from_file('graph.png')
> GLib.Error: gdk-pixbuf-error-quark: Couldn't recognize the image file format for file 'graph.png' (3)
> Failed to execute script set_icon_from_file

The code for "set_icon_from_file.py" is here:
```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import GObject
from gi.repository import Gtk


class DotWindow(Gtk.Window):
    def __init__(self):
        GObject.GObject.__init__(self)

        self.set_title('A Window')
        self.show_all()

        self.set_icon_from_file('graph.png')


def main():
    window = DotWindow()
    window.connect('destroy', Gtk.main_quit)
    Gtk.main()


if __name__ == "__main__":
    main()
```

The icon is here: ![graph](https://cloud.githubusercontent.com/assets/9959942/21233770/b4ae2b6c-c2f0-11e6-8ae4-4524c8e07f35.png)

**Comment by thekswenson** [comment]
This may be a duplicate of https://github.com/pyinstaller/pyinstaller/issues/2317.

**Comment by thekswenson** [comment]
There is the same problem with one of the default examples from the [PyGObject tutorial](http://python-gtk-3-tutorial.readthedocs.io/en/latest/iconview.html).

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
from gi.repository.GdkPixbuf import Pixbuf

icons = ["edit-cut", "edit-paste", "edit-copy"]

class IconViewWindow(Gtk.Window):

  def __init__(self):
    Gtk.Window.__init__(self)
    self.set_default_size(200, 200)

    liststore = Gtk.ListStore(Pixbuf, str)
    iconview = Gtk.IconView.new()
    iconview.set_model(liststore)
    iconview.set_pixbuf_column(0)
    iconview.set_text_column(1)

    for icon in icons:
        pixbuf = Gtk.IconTheme.get_default().load_icon(icon, 64, 0)
        liststore.append([pixbuf, "Label"])

    self.add(iconview)

win = IconViewWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```

**Comment by danjjl** [comment]
As mentioned in some of the duplicate bug reports this crash happens when any icon is loaded.

Here is a minimal example that does not explicitly load an icon (though the `Gtk.SpinButton` does load some internally):

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

win = Gtk.Window()
win.add(Gtk.SpinButton())  # loads an icon
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```

Here is the error log when executing the program just before the segfault:
```
(test-spin:16032): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:/build/gtk+3.0-j0Vp0u/gtk+3.0-3.20.8/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
```

Tests were done under Ubuntu 16.04 and macOS 10.12.3 both tests were done with python 3.5.2 and PyInstaller: 3.3.dev0+g483c819. The Ubuntu system was running Gtk 3.20.8 and the macOS Gtk 3.22.4

**Comment by danjjl** [comment]
This bug is most likely a problem when linking to **pixbuf**.

The `lib/gdk-pixbuf-2.0/2.10.0/` directory is correctly built by PyInstaller in the `dist/` folder. The folder contains both the `loaders.cache` file and the `loaders/` directory with the `libpixbufloader-*.so` library files.

Pixbuf correctly finds these libraries as this small script demonstrates:

```python
from gi.repository import GdkPixbuf

for fmt in GdkPixbuf.Pixbuf.get_formats():
    print(fmt.get_extensions())
```
*(Packaged using PyInstaller and returns : `['gdkp'], ['tiff', 'tif'], ['wmf', 'apm'], ['xbm'], ['png'], ['tga', 'targa'], ['jpeg', 'jpe', 'jpg'], ..., ['ani']`)*

However, loading an image file:
```python
from gi.repository import GdkPixbuf
pixbuf = GdkPixbuf.Pixbuf.new_from_file('image.jpg')
```

Fails with the following message: `GLib.Error: gdk-pixbuf-error-quark: Couldn't recognize the image file format for file 'image.jpg' (3)`

**Comment by danjjl** [comment]
Manually setting the environment variables `GDK_PIXBUF_MODULE_FILE` and `GDK_PIXBUF_MODULEDIR` (see [Gnome doc](https://developer.gnome.org/gdk-pixbuf/stable/gdk-pixbuf-query-loaders.html)) to:
```python
os.environ['GDK_PIXBUF_MODULE_FILE'] = os.path.join(sys._MEIPASS, 'lib/gdk-pixbuf-2.0/2.10.0/loaders.cache')
os.environ['GDK_PIXBUF_MODULEDIR'] = os.path.join(sys._MEIPASS, 'lib/gdk-pixbuf-2.0/2.10.0/loaders/')
```

Give the same error.

@virtuald to you have any idea what might be going wrong?

**Comment by danjjl** [comment]
@htgoebel Any how we can move on with this issue?

This issue has for consequence that nearly all Gtk applications will not work with PyInstaller.

**Comment by virtuald** [comment]
Sorry, I've been busy, so I haven't been able to look into this.

**Comment by danjjl** [comment]
I have been trying to dig into Gtk+ source code to debug this issue. *(Probably too low level to be useful)*. Here are my findings: 

- `GdkPixbuf.Pixbuf.new_from_file` is defined in [/gdk-pixbuf/gdk-pixbuf-io.c](gdk-pixbuf-io.c)
- `GdkPixbuf * gdk_pixbuf_new_from_file(...)` calls `GdkPixbufModule * _gdk_pixbuf_get_module(...)` which gives the **"Couldn't recognize the image file format for file '%s'"**. The error is raised if no module (image loader) is `selected`. The only 'good' reason I see for this to happen is if the list of modules is empty.
- `static GSList * get_file_formats ()` calls `static void gdk_pixbuf_io_init ()` which in turn calls `static gchar * gdk_pixbuf_get_module_file (void)` to populate a list modules. This is done by loading the environmental variable **"GDK_PIXBUF_MODULE_FILE"** (as I had showed in [this comment](https://github.com/pyinstaller/pyinstaller/issues/2318#issuecomment-270070443) manually setting the variable does not seem to change anything). Also calling `GdkPixbuf.Pixbuf.get_formats()` in python returns the correct list of formats.

I am actually even more lost at finding what could be going wrong :disappointed: 

---
Related?

**dist/test/lib/gdk-pixbuf-2.0/2.10.0/loaders.cache**
lists modules located in **/usr/lib/x86_64-linux-gnu/gdk-pixbuf-2.0/2.10.0/loaders** shouldn't the path be **dist/test/lib/gdk-pixbuf-2.0/2.10.0/loaders**?

**Comment by danjjl** [comment]
This bug and https://github.com/pyinstaller/pyinstaller/issues/1833 appear to be duplicates

**Comment by htgoebel** [comment]
> This bug appear to be duplicates

it is. Closing as such.
