### ISSUE TITLE
(Gtk+3) Gtk stock icons not found

### ISSUE THREAD

**Issue by thekswenson** [pyinstaller/pyinstaller#2319]
Here is a minimal example that has a toolbar with a single icon.  The icon is not found.  What is created instead is a blank button.

The following messages are printed to the terminal:

> => dist/iconwindow/iconwindow 
> Gtk-Message: Failed to load module "canberra-gtk-module"
> 
> (iconwindow:981): Gtk-WARNING **: Could not load a pixbuf from icon theme.
> This may indicate that pixbuf loaders or the mime database could not be found.
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> iconwindow.py:54: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
>   self.show_all()
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> iconwindow.py:63: Warning: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
>   Gtk.main()
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'media-floppy' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gtk-WARNING **: Error loading theme icon 'image-missing' for stock: Unrecognized image file format
> 
> (iconwindow:981): Gdk-CRITICAL **: gdk_cairo_surface_create_from_pixbuf: assertion 'GDK_IS_PIXBUF (pixbuf)' failed

The code to produce this is the following:

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import GObject
from gi.repository import Gtk


class DotWindow(Gtk.Window):
    """
    The main window.
    """

    toolbar_spec = '''
    <ui>
        <toolbar name="ToolBar">
            <toolitem action="Save"/>
        </toolbar>
    </ui>
    '''

    def __init__(self):
        GObject.GObject.__init__(self)

        self.set_title('The Window')
        self.set_default_size(200, 200)

        self.vbox = Gtk.VBox()
        self.add(self.vbox)

        # Create a UIManager instance
        uimanager = self.uimanager = Gtk.UIManager()

        # Create an ActionGroup
        actiongroup = Gtk.ActionGroup('Actions')
        self.actiongroup = actiongroup

        # Create actions
        actionlist = [
            ('Save', Gtk.STOCK_FLOPPY, 'Save', None,
             "Save the graph [ctrl-s]", helloWorld),
        ]
        actiongroup.add_actions(actionlist)

        ## Add the actiongroup to the uimanager
        uimanager.insert_action_group(actiongroup, 0)

        # Add a UI description
        uimanager.add_ui_from_string(self.toolbar_spec)

        # Create a Toolbar
        toolbar = uimanager.get_widget('/ToolBar')
        toolbar.set_style(Gtk.ToolbarStyle.ICONS)
        self.vbox.pack_start(toolbar, False, False, 0)

        self.show_all()


def helloWorld(arg):
    print('Hello World.')

def main():
    window = DotWindow()
    window.connect('destroy', Gtk.main_quit)
    Gtk.main()


if __name__ == "__main__":
    main()
```

**Comment by tallforasmurf** [comment]
It certainly looks to me as if you have opened three issues for what very strongly looks like a single problem: failure to bundle some needed Gtk resource. Based on your use of the `datas` assignment in #2318 you have been reading the manual, good! But why are you opening multiple issues? #2318 has a nice simple example, suggest you close the other two and let people focus on that one.

**Comment by thekswenson** [comment]
I'm less familiar with pyinstaller than you are...
   they all have different error messages and different symptoms (some crash completely and some still run, for example).

I'll take your advice and close two of the three.

**Comment by thekswenson** [comment]
Duplicate of https://github.com/pyinstaller/pyinstaller/issues/2318.
