### ISSUE TITLE
Issue with portaudio

### ISSUE THREAD

**Issue by eadward** [pyinstaller/pyinstaller#2321]
I am compiling a binary in OS X using PyInstaller. It used to work fine, until the moment I added a PortAudio dependant library (sound device). Error is shown below. Can anybody help with this? Thank you.

`OSError: cannot load library /var/folders/jc/trvjp7t51cb2qb8qn6d_8p3w0000gn/T/_MEIJipIaA/_sounddevice_data/libportaudio.dylib: dlopen(/var/folders/jc/trvjp7t51cb2qb8qn6d_8p3w0000gn/T/_MEIJipIaA/_sounddevice_data/libportaudio.dylib, 2): image not found`

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.
