### ISSUE TITLE
Missing wiki page How-to-Report-Bugs

### ISSUE THREAD

**Issue by jonnojohnson** [pyinstaller/pyinstaller#2326]
I'm running into issues and was trying to do the right thing before opening an issue. I see lots of references pointing to this wiki page that doesn't exist: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
Including a section on making sure everything is packaged correctly.

**Comment by htgoebel** [comment]
Thanks for this pointer. Some ignorant deleted this page.

@dibifirst: Hey, its you! The wiki is not for posting help request! If you do not know how to use tools, you should abstain.
