### ISSUE TITLE
pyinstaller uses wrong Qt DLLs

### ISSUE THREAD

**Issue by lishunan246** [pyinstaller/pyinstaller#2328]
I am using pyinstaller with python 3.5 and pyqt5 on Windows 10. And There are qt binaries compiled by myself in system paths. It is fine when running python scripts directly, but pyinstaller will copy the dlls complied by me rather than the those of pyqt to the dist folder.
I know removing qt from path can help, but is it possible that the dll searching strategy can be improved?
And thanks a lot for your works!

**Comment by htgoebel** [comment]
We are not going to change the strategy for searching DLLs. If you need to modify %PATH%, you can do this in the .spec-file or in a .bat file wrapping.your call to PyInstaller.
