### ISSUE TITLE
Python 3.6 compatibility

### ISSUE THREAD

**Issue by nchammas** [pyinstaller/pyinstaller#2329]
It looks like PyInstaller has some issues running on Python 3.6.

With PyInstaller 3.2:

```
  File ".../venv/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1505, in _scan_bytecode_stores
    name = co.co_names[oparg]
IndexError: tuple index out of range
```

With PyInstaller on the `develop` branch:

```
  File ".../venv/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2723, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range
```

I am not seeing this on Python 3.5.2.

I don't have a minimal repro to share, but I imagine the problem will be easy to find by anyone running PyInstaller on Python 3.6. If not, I would be happy to do the work to boil this down to a minimal repro.

**Comment by htgoebel** [comment]
Python 3.6 is not yet supported, see http://pyinstaller.org.

**Comment by nchammas** [comment]
Right, but I assume support is planned. Doesn't it make sense to leave this issue open to track when it gets added?

**Comment by htgoebel** [comment]
Of course, support is planed. I closed this issue since it is a bug report for a very obvious bug we will step over when working in Python 3.6 support. (And it's a duplicate, too.)

**Comment by htgoebel** [comment]
To get notified when Python 3.6 is finished, just follow the releases :-) Or watch #2331 (which I jut added.

**Comment by nchammas** [comment]
> (And it's a duplicate, too.)

Ah, I see now this was reported in #2286. I missed it when searching through the existing issues.

OK cool, I'll follow #2331. 👍
