### ISSUE TITLE
Hook for 'django.contrib.admin.apps'

### ISSUE THREAD

**Issue by RaginiDahihande** [pyinstaller/pyinstaller#2332]
I have created new virtual environment.
In that virtual environment I have installed django , djangorestframework and PyInstaller.
I have created new project in virtual environment. I have tested project  using python manage.py runserver its working fine.
I have executed  pyinstaller - -name=demo test1/manage.py, this command generated exe file. But when I am running exe file I am getting Error as follow

```

C:\The_Incredibles\Pyinstaller Story\test_proj>.\dist\demo\demo.exe runserver
Unhandled exception in thread started by <function check_errors.<locals>.wrapper
at 0x03A15978>
Traceback (most recent call last):
  File "site-packages\django-1.10.4-py3.5.egg\django\utils\autoreload.py", line
226, in wrapper
  File "site-packages\django-1.10.4-py3.5.egg\django\core\management\commands\ru
nserver.py", line 113, in inner_run
  File "site-packages\django-1.10.4-py3.5.egg\django\utils\autoreload.py", line
249, in raise_last_exception
  File "site-packages\django-1.10.4-py3.5.egg\django\utils\six.py", line 685, in
reraise
  File "site-packages\django-1.10.4-py3.5.egg\django\utils\autoreload.py", line
226, in wrapper
  File "site-packages\django-1.10.4-py3.5.egg\django\__init__.py", line 27, in s
etup
  File "site-packages\django-1.10.4-py3.5.egg\django\apps\registry.py", line 85,
in populate
  File "site-packages\django-1.10.4-py3.5.egg\django\apps\config.py", line 116,
in create
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 956, in _find_and_load_unlocked
ImportError: No module named 'django.contrib.admin.apps'
```

**Comment by xoviat** [comment]
You need to add all of the hidden imports to your spec file. You can identify the hidden imports by putting this code somewhere in your application after everything has been loaded:

```
import sys
print(sys.modules.keys()​​​)
```

[You can also use the `-v` flag to get the hidden imports.](https://pythonhosted.org/PyInstaller/when-things-go-wrong.html#getting-python-s-verbose-imports)

The bottom line is that `django.contrib.admin.apps` is one hidden import, but there are probably others. You need to add all of these to the `hiddenimports` in the spec file that has been generated, and then you need to run PyInstaller referencing the spec file.

**Comment by RaginiDahihande** [comment]
Hey,
Thanks for replying
here is my manage.py
I am not importing djnago.contrib here or any djnago module
Can you please help me to solve this problem
```
#!/usr/bin/env python
import os
import sys

if __name__ == "__main__":
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "demo.settings")
    try:
        from django.core.management import execute_from_command_line
    except ImportError:
        # The above import may fail for some other reason. Ensure that the
        # issue is really that Django is missing to avoid masking other
        # exceptions on Python 2.
        try:
            import django
        except ImportError:
            raise ImportError(
                "Couldn't import Django. Are you sure it's installed and "
                "available on your PYTHONPATH environment variable? Did you "
                "forget to activate a virtual environment?"
            )
        raise
    execute_from_command_line(sys.argv)
```

**Comment by xoviat** [comment]
Add the following to the top of manage.py and run it (do not run the compiled version). Then post the output.

import sys
import thread

def list_imports(a):
    printed_imports = []
    while True:
        for key in sys.modules.keys():
            if key not in printed_imports:
                printed_imports.append(key)
                print(key)

thread.start_new_thread( list_imports, (1,))

**Comment by RaginiDahihande** [comment]
Hey

Thanks for helping
that issue got resolved
What I did I created one hook-django.contrib.py file under (PyInstaller/hooks/)f which will import hidden modules

following code I added to hook file
```
#-----------------------------------------------------------------------------
# Copyright (c) 2005-2016, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('django.contrib')

```

**Comment by htgoebel** [comment]
We should include this hook.

**Comment by htgoebel** [comment]
> We should include this hook.

After rethinking this changed my mind. I don't think adding all contrib modules even if they are not used is a good idea. See https://github.com/pyinstaller/pyinstaller/pull/2336#issuecomment-276402265 for details.
