### ISSUE TITLE
Pyinstaller error with requests version > 2.11.1

### ISSUE THREAD

**Issue by Sattar1** [pyinstaller/pyinstaller#2334]
Hi.
I opened an issue here: https://github.com/kennethreitz/requests/issues/3793 It's related to pyinstaller community too.

I would appreciate if you help.
Thanks.

**Comment by xoviat** [comment]
Have you looked at adding those [hidden imports][1] to your spec file?

[1]: https://pythonhosted.org/PyInstaller/when-things-go-wrong.html#listing-hidden-imports

**Comment by htgoebel** [comment]
This is caused by requests' bundling it's own copy of `six`.
