### ISSUE TITLE
Gtk3 application is very large on linux

### ISSUE THREAD

**Issue by danjjl** [pyinstaller/pyinstaller#2337]
Packaging this minimal Gtk application using pyinstaller results in an very large executable.

Minimal Gtk3 python script:

```python
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

win = Gtk.Window()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```

The resulting binary is 417.655.000 bytes (417.7MB).

The pyinstaller packaging log does not show anything I identify as problematic: [log file](https://gist.github.com/danjjl/3d6da739f9cda06a109e88c574d21a19)

I am using:
- Ubuntu: 16.04 (x86_64)
- Python: 3.5.2
- Pyinstaller: 3.3.dev0+g483c819 (installed using pip - then recompiled the bootloader cf. https://github.com/pyinstaller/pyinstaller/issues/2232)
- Gtk: 3.20.8

The same procedure on a macOS  10.12.3, running the same version of python and pyinstaller but Gtk 3.22.4 results in an executable of 34.117.641 bytes (34.1MB).

**Comment by danjjl** [comment]
Packaging as a directory and not as a file gives some clues on why the package is so large:

- All my system icon themes are included (204 MB)
- All my system themes are included (28.8 MB)
- All my locales are included (9.5 MB)

**Comment by xoviat** [comment]
Have you looked at the [build time dependency graph][1]?

[1]: https://pythonhosted.org/PyInstaller/when-things-go-wrong.html#build-time-dependency-graph

**Comment by morphsx** [comment]
I can confirm this behavior, same setup but with PyInstaller 3.2 installed through pip.
Executable created with 419MB

**Comment by danjjl** [comment]
I probably don't fully understand how to read the build time dependency graph. In the graph I do not see the large icons that are imported. As far as I can understand the graph, I do not see any imports that would seem outrageous.

Here is the full build time dependency graph: [xref-test.html](https://gist.github.com/danjjl/79b79d8b26a684b3e562af441f15518f)

**Comment by htgoebel** [comment]
The data files are jot part of the dependency graph. They are included by some hook.

**Comment by danjjl** [comment]
Thank you for pointing in the right direction :smiley: 

The *problematic* piece of code is in `utils/hooks/gi.py` (called by `hooks/hook-gi.repository.Gtk.py
`)

```python
def collect_glib_share_files(*path):
    """path is relative to the system data directory (eg, /usr/share)"""
    glib_data_dirs = get_glib_system_data_dirs()
    if glib_data_dirs is None:
        return []

    destdir = os.path.join('share', *path[:-1])

    # TODO: will this return too much?
    collected = []
    for data_dir in glib_data_dirs:
        p = os.path.join(data_dir, *path)
        collected += collect_system_data_files(p, destdir=destdir, include_py_files=False)

return collected
```

The problem is that the full `icons` folder and `themes` folders are copied to the PyInstaller archive. These folders are relatively large on a default Ubuntu installation and can grow much larger once the user installed several themes and icons.

---

Not sure what the best solution would be.

Possible solutions could include:

- Only include the default Gnome icon and theme (Adwaita and gnome-icon-theme)
- Only include the user selected icons and theme

*(Both these solutions have the downside that if the user selects a custom theme in his Gtk application the theme will not be available - It could also be his responsibility to add that theme to the `share/` folder)*

Should I submit a PR that implements one of the proposed solutions?

**Comment by xoviat** [comment]
One other option (and this would require some brief but fundamental modifications to the API) is to look for `gtk.rc_parse` in the added modules.

**Comment by JoshKisb** [comment]
Is there a way to tell pyinstaller not to include all locales and themes. i dont understand why they are included in the first place

**Comment by lemarec** [comment]
Hello 
I try to exclude locales,themes and icons
is anybody find how to since Dec 2017 ?

**Comment by mendhak** [comment]
Please can this get some attention.  

I'm running into the same issue.  For info I'm on:  
pyinstaller version 3.6  
Ubuntu 20.04  
Python 3.8.2  
pip3 version 20.1.1  

I tried the author's example script, I then ran: 

```
pyinstaller -F -w --clean sizetest.py
```

And the final file size is ~238M (249437208)

**Comment by acmpo6ou** [comment]
@mozbugbox Hi! I've tried to use your hook in my spec file on Linux mint 20.2 like this:
```python
from PyInstaller.config import CONF
CONF["hooks"] = {
    "themes": ["Adwaita"],
    "icons":["Adwaita"]
    "languages": ["en"],
}
```
Then I run pyinstaller:
`pyinstaller --onefile test.spec`
But it didn't work, the file is still big. Can you help me, maybe I'm missing something?

**Comment by bwoodsend** [comment]
You shouldn't be touching `PyInstaller.config.CONF` (which has nothing to do with this anyway). You should be setting the `hooksconfig` paramenter [as it says in the docs](https://pyinstaller.readthedocs.io/en/stable/hooks-config.html#gobject-introspection-gi-hooks).

**Comment by acmpo6ou** [comment]
@bwoodsend Thanks a lot! It works! I was trying to find this in documentation with google but failed, so thank you for the link to the docs.

**Comment by RichardJECooke** [comment]
@danjjl  What was your final app size? 

I don't want to learn GTK if a five line app is going to be 200MB  :-@
