### ISSUE TITLE
Upload module graph from failed tests to location for inspection

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2342]
This is not a bug with PyInstaller per se, but it would significantly aid debugging some test failures. When a test failure occurs, the testing engine outputs the following (among other things):

```
593 INFO     Graph cross-reference written to /tmp/pytest-of-travis/pytest-0/popen-gw0/test_python_makefile_onefile_0/build/pyi_python_makefile/xref-pyi_python_makefile.html
```

The problem is of course that this file remains on travis and is unreadable to developers. It would be very nice if these reports could be uploaded somewhere (and possibly removed after 24 hours). Possibly a GitHub repository or something like Google Drive. Whatever.

**Comment by xoviat** [comment]
Another option (possibly more realistic) would be to simply output the contents of the file to the shell.

**Comment by xoviat** [comment]
See https://gist.github.com/domenic/ec8b0fc8ab45f39403dd

**Comment by htgoebel** [comment]
Uploading the data somewhere seems to be the better solution. From our experience, even for failing tests the debug files are not so relevant. So I'd avoid cluttering the already cluttered test-output even further. But how to get rid of old build-logs? Keeping them is of little use.

OTOH this feature will make even more people misuse the CI infrastructure for testing their code and cluttering pull-requests with unfinished code, blocking tests for finished pull-requests and  wasting time of core developers. If I imagine we'd had this feature when you develeoped Python 3.6 support, the imagination you'd developed this on a pull-request makes me shiver.

So maybe its not a good idea to implement this feature this.

**Comment by xoviat** [comment]
> So maybe its not a good idea to implement this feature this.

On second thought, I agree.
