### ISSUE TITLE
Windows bootloaders in releases posted on PyPI requires msvcr*.dll

### ISSUE THREAD

**Issue by NathanDunfield** [pyinstaller/pyinstaller#2343]
The [documentation](https://pythonhosted.org/PyInstaller/bootloader-building.html#building-for-windows) says that the Windows bootloader "is a self-contained static executable that imposes no restrictions on the version of Python being used".  In fact, this is not the case for the bootloaders that are posted on PyPI: the ones for PyInstaller 3.2 depend on `msvcr100.dll` and the ones for PyInstaller 3.1.* (which I was using to get around a bug in 3.2) depend on `msvcrt.dll`.  Anyway, this can result in "crash on startup" for some PyInstaller Windows apps based on Python 2.7 (which uses `msvcr90.dll`) when one imports certain other binary Python modules. 

Following the documentation, compiled my own Windows bootloaders using the MSVC compilers on AppVeyor, and these were free of any reference to `msvcr*.dll` and eliminated the crashes I was having completely.  So perhaps the official releases were built with some other toolchain?  Regardless, it would be great if future releases were truly static, as it took a lot of time to track down what was causing my problem.  Here is my [AppVeyor build script](https://bitbucket.org/nathan_dunfield/pyinstaller_windows) as well as a [wheel](https://bitbucket.org/nathan_dunfield/pyinstaller_windows/downloads) built off the current tip in case this is helpful to someone.

**Comment by marcelstoer** [comment]
> the ones for PyInstaller 3.2 depend on `msvcr100.dll`

Yep, just hit that as well.

**Comment by marcelstoer** [comment]
Using the latest dev through `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip` fixes this but GitHub ain't PyPI I know...

**Comment by htgoebel** [comment]
I take the last comment as "fixed", esp since 3.2.1 is released in the meantime.

**Comment by NathanDunfield** [comment]
@htgoebel: Unfortunately, both PyInstaller 3.2.1 and the development version still depend on "msvcrt.dll", so I think you should reopen this ticket.  I believe what @marcelstoer is referring to is that they no longer depend on "msvcr100.dll", which fixed his problem, but it doesn't fix mine.  

You can use `dumpbin.exe /dependents` on the contents of `PyInstaller/bootloader/Windows/-*/run*.exe` to see the current references to "msvcrt.dll" in contrast to the version I compiled by hand.

**Comment by htgoebel** [comment]
Thanks for coming back to this. I'm sorry that 3.2.1 does not solve the problem.

We are using MinGW for building the boolader since this can be used for cross-building. I just found [this blog entry](https://arrayfire.com/cross-compile-to-windows-from-linux/) saying:
> When compiling C projects, use {i686,x86_64}-w64-mingw32-gcc. The resulting binary will depend on at least KERNEL32.DLL and whatever MSVCRT.DLL is on clients' systems. Therefore, you'll need to make sure clients have the Microsoft C Runtime installed to use your software.

This is not a good news :-(

**Comment by htgoebel** [comment]
@codewarrior0 Any idea how we can solve this? E.g. by using clang?

**Comment by htgoebel** [comment]
Maybe we can got a long these lines: http://stackoverflow.com/questions/7301995/windows-gnu-compiler-suite-without-external-dependencies

**Comment by codewarrior0** [comment]
@NathanDunfield Which version of Windows does this issue happen on?

**Comment by NathanDunfield** [comment]
@codewarrior0: I have the issue on both Win7 and Win10, haven't tried other versions.

I don't know how you're building the bootloaders now, but [AppVeyor provides both MinGW and every version of the Microsoft compilers](https://www.appveyor.com/docs/installed-software/).   I have used it to build various Python modules using both toolchains.  Here is the [AppVeyor build script](https://bitbucket.org/nathan_dunfield/pyinstaller_windows/src/tip/appveyor.yml) that I used to produce [bootloaders that don't depend on msvcr*.dll](https://bitbucket.org/nathan_dunfield/pyinstaller_windows/downloads).

**Comment by codewarrior0** [comment]
So the only thing you changed is to build with MSVC 9.0?

**Comment by NathanDunfield** [comment]
Yes, switching to MSVC solves the problem.  It doesn't have to be MSVC 9.0, I also tested with MSVC 14.0 (=Visual Studio 2015).   In fact, for the 64-bit bootloader, you need to use the more recent version.  In particular, the `--msvc_version` flag on line 10 of [my build script](https://bitbucket.org/nathan_dunfield/pyinstaller_windows/src/tip/appveyor.yml) isn't needed, though MSVC 9.0 produces somewhat smaller binaries than MSVC 14.0.  On line 11 of the build script, it just uses AppVeyor's default which is MSVC 14.0.

**Comment by codewarrior0** [comment]
That's a bit surprising. I remember building the bootloader using MSVC 9.0, 10.0, and 14.0 about a year ago and the resulting binaries always depended on the MSVCR??.DLL appropriate to the compiler. Something must have changed with our wscript between then and now to cause MSVC to start linking the C runtime statically.

**Comment by htgoebel** [comment]
I prefer to find a solution which does *not* require proprietary software (mvsc) to build.

**Comment by ThomasWaldmann** [comment]
Move milestone? 3.2.1 is already released.

**Comment by htgoebel** [comment]
I spent quite some time on this again again and chatted the mingw-guys:
- When using MSVC compiler, it links *statically* with msvcrt.
- When using mingw (as we do), there is no static msvcrt, thus it links to msvcrt.dll.
- Option would be to statically link with some other runtime-library, but I'm not aware of one.
   - I tried building [newlib](https://en.wikipedia.org/wiki/Newlib) with mingw, but this failed. I also tries to use the pre-build newlib coming with cygwin, but linking failed with "multiple definition" errors.

**Comment by htgoebel** [comment]
Another possibility would be to used some stub c-library like https://github.com/nothings/stb which we used earlier already.

**Comment by htgoebel** [comment]
I updated our Vagrantfile's Windows machine so we can build the bootloader using Visual C++ (see https://github.com/pyinstaller/pyinstaller/pull/2415#issuecomment-311465407). I ask you to try the bootloaders in that branch and maybe even the Vagrantfile and building the bootloaders. Instructions how to test this easily are in teh aforementioned comment.

Thanks a lot.

**Comment by NathanDunfield** [comment]
@htgoebel  I checked out the new bootloaders with "dumpbin /dependents" and they all look great --- no references to any msvc*.dll as desired.  I also tried them out in the application that prompted my initial report, and they work fine there as well.  So I definitely think #2415 would solve #2343, which is excellent news!
