### ISSUE TITLE
Matplotlib is not available on Python 3.6

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2362]
Matplotlib is currently not tested because binaries were not available at the time of implementation. Matplotlib should be tested when binaries become available.

**Comment by htgoebel** [comment]
Closed by 88daeea99022d775778e437fd16d5fe35bda07d3

@xoviat Please do no only close such issues, but also add a reverence. Thanks.

**Comment by xoviat** [comment]
Sorry; I looked at the tests and saw that they were now passing.
