### ISSUE TITLE
modulegraph: imp is deprecated and should be replaced in favor of importlib

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2366]
[Modulegraph](https://github.com/pyinstaller/pyinstaller/blob/6ec7181578eed6dc7a4345efd76b84fe402e14ee/PyInstaller/lib/modulegraph/modulegraph.py) currently depends on the `imp` package, which will be removed in future Python version. @ronaldoussoren has mentioned rewriting the `imp` functionality with the assistance of `importlib2` for backwards compatibility. 

What needs to happen is to decide the type of module based on the type of loader:

- BuiltinImporter (builtins)
- ExtensionFileLoader (.so/.pyd/etc.)
- SourceFileLoader (.py) 
- SourcelessFileLoader 

We also need to load code directly from `loader.get_code` rather than `marshal.loads`.

**Comment by xoviat** [comment]
See https://github.com/pyinstaller/pyinstaller/blob/b78bfe530cdc2904f65ce098bdf2de08c9037abb/tests/functional/scripts/pyi_hooks/hook-pkg_without_hook_for_pkg.sub1.py

**Comment by xoviat** [comment]
This is @leycec's answer:

```python
import inspect, os
from importlib.machinery import ExtensionFileLoader, EXTENSION_SUFFIXES
from types import ModuleType

def is_c_extension(module: ModuleType) -> bool:
    '''
    `True` only if the passed module is a C extension implemented as a
    dynamically linked shared library specific to the current platform.

    Parameters
    ----------
    module : ModuleType
        Previously imported module object to be tested.

    Returns
    ----------
    bool
        `True` only if this module is a C extension.
    '''
    assert isinstance(module, ModuleType), '"{}" not a module.'.format(module)

    # If this module was loaded by a PEP 302-compliant CPython-specific loader
    # loading only C extensions, this module is a C extension.
    if isinstance(getattr(module, '__loader__', None), ExtensionFileLoader):
        return True

    # Else, fallback to filetype matching heuristics.
    #
    # Absolute path of the file defining this module.
    module_filename = inspect.getfile(module)

    # "."-prefixed filetype of this path if any or the empty string otherwise.
    module_filetype = os.path.splitext(module_filename)[1]

    # This module is only a C extension if this path's filetype is that of a
    # C extension specific to the current platform.
    return module_filetype in EXTENSION_SUFFIXES
```

**Comment by xoviat** [comment]
Duplicate #2763

**Comment by htgoebel** [comment]
Well spotted :-)

**Comment by htgoebel** [comment]
@xoviat BTW: Did you know this: https://help.github.com/articles/about-duplicate-issues-and-pull-requests/

**Comment by xoviat** [comment]
I don't have write access.
