### ISSUE TITLE
Where Pyinstaller will look for static files of django project

### ISSUE THREAD

**Issue by RaginiDahihande** [pyinstaller/pyinstaller#2368]
Pyinstaller not able to load css and js files
Pyinstaller able to find templates(html files) But not able to find css and js files
following error I am getting

This is my static dir path its correct I printed it run time
```
/static/ ['C:\\Users\\sanjad\\AppData\\Local\\Temp\\_MEI58082\\static']
/static/ ['C:\\Users\\sanjad\\AppData\\Local\\Temp\\_MEI52082\\static']
```

```
System check identified no issues (0 silenced).
January 10, 2017 - 15:13:20
Django version 1.10.2, using settings 'ProtectPointTools.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[10/Jan/2017 15:13:26] "GET / HTTP/1.1" 200 20800
Not Found: /static/css/globalnav.min.css
Not Found: /static/jsscript/jquery-2.2.0.js
[10/Jan/2017 15:13:26] "GET /static/jsscript/jquery-2.2.0.js HTTP/1.1" 404 12642
Not Found: /static/css/support.css
[10/Jan/2017 15:13:26] "GET /static/css/globalnav.min.css HTTP/1.1" 404 12633
[10/Jan/2017 15:13:26] "GET /static/css/support.css HTTP/1.1" 404 12615

```

But I am not able to find where pyinstaller will look for static files of django project
I tried lots of solution but nothing works for me

I already posted this issue still not able to solve it
https://github.com/pyinstaller/pyinstaller/issues/2348

**Comment by xoviat** [comment]
https://pythonhosted.org/PyInstaller/spec-files.html#adding-data-files

**Comment by RaginiDahihande** [comment]
Yes I have added hidden imports and data files

**Comment by htgoebel** [comment]
> I already posted this issue still not able to solve it

So this is a duplicate. Why should opening a new issue solve your problem?

**Comment by fpx006** [comment]
I found add static url to the code , and static is worked. 
But it is not recommended in django document.

from django.conf import settings
from django.contrib.staticfiles import views

if settings.DEBUG:
    urlpatterns += [
        url(r'^static/(?P<path>.*)$', views.serve),
    ]

**Comment by htgoebel** [comment]
@fpx006  https://pyinstaller.readthedocs.io/en/stable/runtime-information.html

**Comment by WillowireDave** [comment]
Alertnative solution that is very close to FPX006's that worked for me was to add this to my top level urls.py urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT).

I had done the same thing to get my media files served with urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

And then add both of those to my spec file, along with my migrations folder as follows 
datas=[('filter/filter/core/migrations','filter/core/migrations'),('filter/media_root','media_root'),('filter/static','static_root')],

where filter is the name of the only app in this Django project.

**Comment by agent909** [comment]
@WillowireDave 

I'm having an import error 

urlpatterns += **static**(settings.STATIC_URL, document_root=settings.STATIC_ROOT).

name 'static' is not defined

**Comment by triple07even** [comment]
> @WillowireDave
> 
> I'm having an import error
> 
> urlpatterns += **static**(settings.STATIC_URL, document_root=settings.STATIC_ROOT).
> 
> name 'static' is not defined

After running the collectstatic, i added the following in the project url

from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.storage import staticfiles_storage

#I put this rest under the urlpattern 
urlpatterns += static(settings.STATIC_URL, document_root = settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

**Comment by gabrielwong1991** [comment]
Hi all, I tried all the methods mentioned above and it does not work... Anyone have success in PyInstaller: 5.1 and Django version 4.0.5?

I am really out of clues...

What is your settings in STATIC_ROOT? currently it is pointing to staticfiles after running `collectstatic` but whenever I add the data file in manage.spec as `('app/static', 'static_root')` it saids the directory is not found but do not have warning with `(app/static, 'app/static')`...  Still, all css and js do not loads...

My templates file, bootstrap files are totally fine.... Just this static file...
