### ISSUE TITLE
Compile bootloader with --no-lsb by default (and document it)

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2369]
While the documentations says ["the bootloaders on Linux are LSB binaries"](https://pyinstaller.readthedocs.io/en/3.1/bootloader-building.html#building-for-linux), for PyInstaller 3.1 and 3.2 they are not but compiled with `--no-lsb`. So today I tried to bring back LSB binaries in the [virtual machines](https://github.com/pyinstaller/pyinstaller/blob/1804636abc13/bootloader/Vagrantfile) I use to build the GNU/Linux bootloaders. The effort was not fruitful :-(. For this:

**I suggest no longer building the bootloaders for LSB**

For PyInstaller 3.2.1 I will (again) deliver bootloaders compiled with `--no-lsb`.

#### Rational

I see only minor benefits compared to a huge effort for maintaining LSB compiler usage. We are not LSB compliant since PyInstaller 3.1 and nobody complained. So the effort seems not to be worth the result.

The LSB package are not available for most GNU/Linux distributions (Source: [Wikipedia](https://en.wikipedia.org/wiki/Linux_Standard_Base#Reception)). So most users will use `--no-lsb` anyway and so this sould become the default.

##### Possible benefits vs. drawbacks

1. LSB compliance could ensure PyInstaller bootloaders are running on almost all GNU/Linux platforms. Using `lscbb` and the "correct" header-files would inhibit that the bootloader "suddenly" requires a newer version of glibc (see issue #2160).

2. The aim of not requiring "new" versions of glibc and be achieved by other means, too.

3. LSB is followed only by few Linux distributions (Source: [Wikipedia](https://en.wikipedia.org/wiki/Linux_Standard_Base#Reception)). In autumn 2015 both the Debian project and Ubuntu dropped  support for LSB (Source: [Wikipedia](https://en.wikipedia.org/wiki/Linux_Standard_Base#Limitations_on_Debian)).

Issue #165 lists some more pros, cons and work-arounds.

##### huge effort for maintaining LSB compiler usage

1. Setting up `lsbcc` is complicated: The LSB packages are no longer provided by Debian or Ubuntu, so a separate repository needs to be added.

2. The packages from this official LSB repository are broken: They'll create a directory tree which non-root users can not access. For me this is a sign of no being interested in quality.

3. When running our wscript on a current Debian I get these errors:
```
[ 1/13] Compiling src/main.c
warning: dangerous include path /usr/include
unrecognized gcc version: "4.9.2"
```
Since the Python includes reside in `/usr/include` and current Debian only ships gcc 4.9.2, there is rare chance to solve this. And id it is to be solved, solving will most probably be laborious.

4. Documentation about the usage of the LSB tools is hard to find, and terse, very terse.

5. The tool `lsbappchk` can not analyse 32-bit applications on a 64-bit platform, which is not a good sign on code quality of the tools, as e.g. `objdump` would allow it.

6. I did not find a way how to specify which version of LSB should be complied to. /opt/lsb/lib64 (which I assume is the relevant one) point to lib64-5.0. As said: Documentation is hard to find.

##### We are not LSB compliant since PyInstaller 3.1

We are not shipping LSB compilant bootloaders since at least Release 3.1. But nobody complained.

Both 3.1 and 3.2 have been build using --no-lsb as you can verify using this snippet, which does not include `ld-lsb`.

This can be verified by this snippet:
```
venv/bin/pip install pyinstaller==3.2
for i in venv/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-*/* ; \
   do echo '===' $i ; strings $i | grep -P '/lib(64)?/ld.*\.so' ; \
done
```

For PyInstaller 2.1 and 3.0 the snippet above will show `ld-lsb`. But nevertheless `lsbappchk --lsb-version=4.0` reports
>   Incorrect program interpreter: /lib64/ld-linux-x86-64.so.2, expected: /lib64/ld-lsb-x86-64.so.3

##### Do It Yourself LSB is still possible

We are keeping the feature for building LSB compliant bootloaders in the `wscript` file. So if somebody urgently needs LSB compliance, he/she can compile the bootloader his/herself.

@pyinstaller/core-developers What do you think?

**Comment by bjones1** [comment]
If Debian and Ubuntu have dropped support, and that support requires much hacking, let it die. Leaving code in waf makes sense for any brave souls trying to resurrect it.

**Comment by htgoebel** [comment]
Since nobody complained, I'll drop support for lsbcc.
