### ISSUE TITLE
archive_viewer enhancements (bugs)

### ISSUE THREAD

**Issue by dshmgh** [pyinstaller/pyinstaller#2370]
This affects the use of archive_viewer.py -- two issues:
1. In the 3.2 release of pyinstaller in archive/readers.py at lines 147 and 149 there is a constant of 4096 hardcoded for the range of searching for the "MAGIC" value back from the end of the archive.  In my case, I had a certificate of length 7248 bytes appended to the archive and it never found the "MAGIC" value location.  Perhaps a better way is to start with 4096 and if MAGIC is not found, keep doubling the "EndBlockLength" and search again until the "EndBlockLength" is greater than the file length (or some algorithm like that).

2. My windows .exe type archive still used the older 24 byte MAGIC cookie format and this release does not appear to support that.  Perhaps that could be added back so that both formats are supported?
See archive/readers.py lines 112, 155, 156, 167, 168

I am pretty new to Python so not sure my code would good enough for release purposes.

**Comment by htgoebel** [comment]
Thanks for the report. Please submit a separate issue for each of the two topic, as they are different and differently important. Or even better: Submit a pull-request :-)

**Comment by htgoebel** [comment]
Thanks :-)
