### ISSUE TITLE
archive_viewer support for 24 byte MAGIC cookie

### ISSUE THREAD

**Issue by dshmgh** [pyinstaller/pyinstaller#2373]
This affects the use of archive_viewer.py

My windows .exe type archive still used the older 24 byte MAGIC cookie format and this release does not appear to support that. Perhaps that could be added back so that both formats are supported?
See archive/readers.py lines 112, 155, 156, 167, 168

**Comment by htgoebel** [comment]
Please add a link to a blob in this repo where he old cookie format was defined. This would help implementing it. Also: What is the exact problem you are experiencing?

**Comment by dshmgh** [comment]
While trying the new code for issue 2372 (archive_viewer not able to find CArchive), unless I change the cookie format, the extracted archive length is incorrect and the TOC is not found properly.  I thought I could just use the new code and let the pylib_name get set to junk, but when I saw more errors, I realized that the differing cookie length causes the archive offsets to be wrong.  I think its around version 2.0 to 2.1 where it changed.  I'll research and post again.
Cookie size is simple to fix in the code - although detection of which cookie size to use could be tricky.  I'm curious as to why the same MAGIC value was kept when the cookie size changed -- seems like that's what a MAGIC value is for, to define the format.
I'm working with a windows .exe file from an external source - curious that it was generated less than a year ago and they apparently are still using a version 2.0 or less ...

**Comment by htgoebel** [comment]
> although detection of which cookie size to use could be tricky.

This is what the `version` field list for.

But when rethinking about this issue: I'm in favour of *not* adding backward-compatibility to archive/readers.py. There is not much use for it. The archive-viewer is meant for debugging, not for analysing old archives. And if you start putting rarely used outdated code we'll end up maintaining legacy code forever.

If you really need to analyse an old archive, just install an old version of PyInstaller.

I *may* accept a pull-request  adding legacy code to `archive_viewer.py`, but not to `archive/readers.py`.

**Comment by jack17529** [comment]
So no change is needed to be done for this issue ?

**Comment by htgoebel** [comment]
@jack17529 No, just use an old version of PyInstaller.
