### ISSUE TITLE
Syntax mistake in pipiwin32 setup.py

### ISSUE THREAD

**Issue by sharpvik** [pyinstaller/pyinstaller#2374]
File "C:\Users\Victor\AppData\Local\Temp\easy_install-a1vk9wm3\pypiwin32-219\setup.py", line 121
    print "Building pywin32", pywin32_version
                                         ^
SyntaxError: Missing parentheses in call to 'print'

**Comment by xoviat** [comment]
See GitHub.com/pywin32

**Comment by htgoebel** [comment]
This problem is not related to PyInstaller.

**Comment by xoviat** [comment]
@sharpvik BTW this should be fixed now because I have uploaded a wheel for py36.

**Comment by sharpvik** [comment]
Thank you
