### ISSUE TITLE
ImportError: mpl_toolkits.mplot3d

### ISSUE THREAD

**Issue by chanduch06** [pyinstaller/pyinstaller#2378]
when i tried importing in mac

from mpl_toolkits.mplot3d import axes3D

I'm getting this error.
 from mpl_toolkits.mplot3d import Axes3D
ImportError: No module named mpl_toolkits.mplot3d

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

We would appreciate if you'd submit a hook for this. See https://pyinstaller.readthedocs.org/en/latest/hooks.html for more information about how to implement hooks.

**Comment by htgoebel** [comment]
New news in this for more then a year. closing. If you feel this is still an issue with the current release, please open a brand new issue.
