### ISSUE TITLE
the same problem but no solution:  "No module named 'HTMLParser'"

### ISSUE THREAD

**Issue by jisooyu** [pyinstaller/pyinstaller#2385]
I run the program on Python 3.6 (32-bit) on Windows 10, 64-bit. I came up with the following error. I tried other suggestion like delete or remove html.py but they don't work. Please help me to fix the problem. 

line of codes:
from HTMLParser import HTMLParser
import urllib

error message: 
Traceback (most recent call last):
  File "C:\Users\user\workspace\python_for_ss\link_parsing.py", line 9, in <module>
    from HTMLParser import HTMLParser
ModuleNotFoundError: No module named 'HTMLParser'

**Comment by xoviat** [comment]
Python 3.6 has a different HTML parser than Python 2.7. See [the example][1].


[1]: https://docs.python.org/3.6/library/html.parser.html?highlight=htmlparser#example-html-parser-application

**Comment by htgoebel** [comment]
Python 3.6 is not yet supported, see http://pyinstaller.org.
