### ISSUE TITLE
'python' is not recognized as an internal or external command, operable program or batch file. 

### ISSUE THREAD

**Issue by RaginiDahihande** [pyinstaller/pyinstaller#2391]
I have created exe of python file using pyinstaller.From that file I am calling another python script.when I run my project on clean VM where python is not installed I am getting error like python is not recognised

```
import subprocess
import time
import sys
import os
print ("Hello")
python_path = "python"
args = [python_path,'test.py']
print(args)
subprocess.Popen(args)
time.sleep(100)

```

Where pyinstaller will look for python.When exe is frozen I found only python35.dll.How can i run python script from exe without installing python.

**Comment by htgoebel** [comment]
No, this is not possible. Please see the answer in the FAQ in the Wiki.

BTW: Posting the same question here and on the mailinglist only make duplicate work :-(
