### ISSUE TITLE
Load external pyz files

### ISSUE THREAD

**Issue by HelloZeroNet** [pyinstaller/pyinstaller#2392]
I want create as small .exe as possible, so in the .spec file I moved the `pyz` reference to the `COLLECT` function call.
Everything fine, the exe is only a few KB and a out00-PYZ.pyz generated, but how can I use this file to load the bundled modules? I tried `sys.path.insert(0, "out00-PYZ.pyz")`, but it does not helps.

 (or is there any way to generate standard zipimport compatible package)

Thanks!

**Comment by xoviat** [comment]
See [here][1].

[1]: https://github.com/pyinstaller/pyinstaller/blob/c778285b0f153548e2974f6bd675a4e33991f65b/tests/functional/test_basic.py#L41

**Comment by HelloZeroNet** [comment]
@xoviat Thanks! It's working! Is it possible to move this file into another directory?

On macOS it's not possible to sign .app bundles that have non-Mach-O binary files (executable or .so) in the Content/MacOS directory.

**Comment by xoviat** [comment]
I don't believe so. The code is probably located in the bootloader somewhere.

**Comment by springermac** [comment]
@HelloZeroNet you can put the file in another directory and symlink it into the MacOS directory.

**Comment by HelloZeroNet** [comment]
Thanks for suggestions, it works with symlink!
