### ISSUE TITLE
import error for xlrd, XlsxWriter-0.7.6, openpyxl-2.3.0-b1 and pyserial-2.7.win32_py3k

### ISSUE THREAD

**Issue by anwesh55** [pyinstaller/pyinstaller#2399]
i have a python code i compiled it using pyinstaller UEControler.py. After that i have taken UEControler folder from build folder. when i run the UEControler.exe file it is throwing error

Traceback (most recent call last):
  File "UEControler.py", line 30, in <module>
  File "C:\Python34\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 389, in load_module
  File "OamRange.py", line 3, in <module>
ImportError: No module named 'xlrd'
Failed to execute script UEControler

C:\GOST\scripts>PAUSE
Press any key to continue . . .

**Comment by htgoebel** [comment]
This looks like not all required modules are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by anwesh55** [comment]
i have already gone through the above link and i tried --onedir and --noupx. But still i was getting the same issue. i am using Python 3.4.2 version. My project needed XlsxWriter-0.7.6,openpyxl-2.3.0-b1,pyserial-2.7.win32_py3k and xlrd-0.9.2. All these modules i had installed manually and then tried to create an exe.
One more i observed is, i have a linux version of EXE which i used pyinstaller itself. There i am using pexpect module and i didnt face any issue when i converted into EXE mode. I am facing this issue only in windows PC. Please suggest me how to proceed further. When i looked into the folder after converting to EXE i saw only openpyxl folder rest 3 folders i didnt get.

**Comment by htgoebel** [comment]
The warnings-file does not warn about that "xlrd" has not been found, but warns about "missing module named … - imported by … xlrd.biffh …". Thus `xlrd` is found an should be included. Please verify by usingg ther archive-viewer as described in "Make sure everything is packaged correctly".

Then try a *minimal* program. Are you using threads of multiprocessing? Then look at the receipts.

**Comment by htgoebel** [comment]
Nothing new since 7 month. I assume this is not longer an iusse.

**Comment by xushaozhi** [comment]
Adding ‘import xlrd’ to the script，although 'xlrd' isnot really used，can solve the problem.
