### ISSUE TITLE
Share .pkg between multiple exe applications

### ISSUE THREAD

**Issue by HelloZeroNet** [pyinstaller/pyinstaller#2405]
It would be nice to share the .pkg (generated by `append_pkg=False`) between multiple .exe files. 

eg. one exe for gui and another one for cli version of the application.

**Comment by xoviat** [comment]
Duplicate #1527.

**Comment by HelloZeroNet** [comment]
Ok, closing it then...
(btw if someone want to do the same: renaming the second exe to `pakagename.com` works as a ugly workaround)
