### ISSUE TITLE
How to add data files(datas) to spec file at runtime?

### ISSUE THREAD

**Issue by RaginiDahihande** [pyinstaller/pyinstaller#2406]

**Comment by tallforasmurf** [comment]
Suggest you read this section,

http://pythonhosted.org/PyInstaller/operating-mode.html#analysis-finding-the-files-your-program-needs

Then this section,

http://pythonhosted.org/PyInstaller/spec-files.html#adding-files-to-the-bundle

and then add a comment with more information about what you are trying to do.

**Comment by RaginiDahihande** [comment]
I have created python script which will create pyinstaller exe. I want to add datas to spec file from python script. Because there is no option available at command line. Manually I need to edit spec file and need to copy datas.I am looking for is there any option which will add datas when pyinstaller called at run time.

**Comment by htgoebel** [comment]
You simply need to create the spec-file once and use it as a template. Then you can fill in any options you want using [string formatting](https://docs.python.org/3.4/library/string.html#string-formatting).

**Comment by RaginiDahihande** [comment]
I have refereed this one https://github.com/pyinstaller/pyinstaller/issues/703 to solve issue
