### ISSUE TITLE
Execution of unicode system commands doesn't work after compilation with pyinstaller

### ISSUE THREAD

**Issue by TheTrollKing** [pyinstaller/pyinstaller#2410]
I'm using pyinstaller 3.2.1 with python 3.6.0
when i run this scripy in the pycharm environment, it runs fine:

----------------------
```
import os
import time

try:
    os.system(u'echo אבד')
except Exception as e:
    print(e.__doc__)
    print(e.message)
time.sleep(10)
```
---------------------------

but if i compile the file containing this command using pyinstaller:  

`pyinstaller --onefile test.py`

and run the exe, the following error is generated:

> Unicode encoding error.

Please help me solve this problem. It repeats in every place where i try to pass unicode characters to the external process. The code works fine in python, but doesn't work after compilation with pyinstaller

**Comment by xoviat** [comment]
PyInstaller 3.2.1 doesn't work with Python 3.6.

**Comment by TheTrollKing** [comment]
will check with python 3.5.3

**Comment by htgoebel** [comment]
I doubt, your program is running properly outside of pycharm. `os.system` most probably is not unicode-aware, so you need to encode the unicode strings first. Please make yourself familiar how to create a proper python program which runs "outside" of Pycharm and ensure your program does.

Then, if it still fails after freezing with PyInstaller, follw *all* the tips at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) prior to reopening this issue. Thanks.

**Comment by TheTrollKing** [comment]
After considerable research on this topic, it seems that the problem is non the less in pyinstaller.
there was a unicode problem in python 2.7, but it was solved in python 3.x. No further encoding and decoding is needed.

When I run the python script directly from the command line (not using pycharm), no error is reported. The only time the error is reported is when running the executable created with pycharm. Is it possible pycharm uses old python 2.7 procedures instead of the fixed 3.x procedures?

Furthermore, when i change the os.system() call to subprocess.popen(), the same problem remains.

In any case, please reopen this issue, as I can't find a solution otherwise
Thanks

**Comment by htgoebel** [comment]
This is a locale issue:

When using a UTF-8 capable locate, the script runs fine, while when using an ASCII-only locale (`C`), you get an unicode error.
```
$ LC_ALL=en_GB.UTF-8 python3.4 /tmp/issue2410.py 
אבד
[hartmut@thisbe tmp]$ LC_ALL=C python3.4 /tmp/issue2410.py 
Unicode encoding error.
Traceback (most recent call last):
  File "/tmp/issue2410.py", line 5, in <module>
    os.system(u'echo \u05d0\u05d1\u05d3')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 5-7: ordinal not in range(128)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/issue2410.py", line 8, in <module>
    print(e.message)
AttributeError: 'UnicodeEncodeError' object has no attribute 'message'
```

So check your locate settings within your application. On Windows, `site.aliasmbcs()` adds some aliases for encodings. PyInstaller's `site` packages does not include such code. So maybe this is the error. For a first test copy the coode of `site.aliasmbcs()` into your script.

**Comment by htgoebel** [comment]
@TheTrollKing any news? Otherwise I'm closing this ticket.
