### ISSUE TITLE
Can't run a PyGI Python3 frozen app

### ISSUE THREAD

**Issue by kostich** [pyinstaller/pyinstaller#2412]
Can’t properly run PyGI GTK3 application frozen via PyInstaller, under macOS Sierra 10.12.3.

The freeze completes properly but the application fails to run with the following:

> $ ./gtk3test
> 
> ** (process:758): WARNING **: Failed to load shared library '@loader_path/libgtk-3.0.dylib' referenced by the typelib: dlopen(@loader_path/libgtk-3.0.dylib, 9): Library not loaded: @loader_path/libfreetype.6.dylib
>   Referenced from: /Users/marko/gtk3test/dist/gtk3test/libfreetype.6.dylib
>   Reason: image not found
> 
> ** (process:758): WARNING **: Failed to load shared library '@loader_path/libgdk-3.0.dylib' referenced by the typelib: dlopen(@loader_path/libgdk-3.0.dylib, 9): Library not loaded: @loader_path/libfreetype.6.dylib
>   Referenced from: /Users/marko/gtk3test/dist/gtk3test/libfreetype.6.dylib
>   Reason: image not found
> Traceback (most recent call last):
>   File "gtk3test.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "site-packages/gi/importer.py", line 159, in load_module
>   File "site-packages/gi/overrides/__init__.py", line 111, in load_overrides
>   File "importlib/__init__.py", line 109, in import_module
>   File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
>   File "/usr/local/lib/python3.4/site-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
>     exec(bytecode, module.__dict__)
>   File "site-packages/gi/overrides/Gtk.py", line 118, in <module>
>   File "site-packages/gi/module.py", line 181, in __getattr__
>   File "site-packages/gi/module.py", line 107, in get_interfaces_for_object
>   File "site-packages/gi/overrides/__init__.py", line 38, in __getattr__
>   File "site-packages/gi/module.py", line 220, in __getattr__
>   File "site-packages/gi/types.py", line 234, in __init__
> TypeError: must be an interface
> Failed to execute script gtk3test

Freeze output:

> $ pyinstaller ./gtk3test.py
> 97 INFO: PyInstaller: 3.2.1
> 97 INFO: Python: 3.4.3
> 105 INFO: Platform: Darwin-16.4.0-x86_64-i386-64bit
> 107 INFO: wrote /Users/marko/gtk3test/gtk3test.spec
> 109 INFO: UPX is not available.
> 110 INFO: Extending PYTHONPATH with paths
> ['/Users/marko/gtk3test', '/Users/marko/gtk3test']
> 111 INFO: checking Analysis
> 111 INFO: Building Analysis because out00-Analysis.toc is non existent
> 111 INFO: Initializing module dependency graph...
> 113 INFO: Initializing module graph hooks...
> 115 INFO: Analyzing base_library.zip ...
> 1759 INFO: Processing pre-find module path hook   distutils
> 3112 INFO: running Analysis out00-Analysis.toc
> 3122 INFO: Caching module hooks...
> 3125 INFO: Analyzing /Users/marko/gtk3test/gtk3test.py
> 3201 INFO: Processing pre-safe import module hook   gi.repository.Gio
> 3202 INFO: Processing pre-safe import module hook   gi.repository.Gtk
> 3204 INFO: Loading module hooks...
> 3205 INFO: Loading module hook "hook-distutils.py"...
> 3206 INFO: Loading module hook "hook-gi.repository.Gtk.py"...
> 6058 INFO: Processing pre-safe import module hook   gi.repository.GObject
> 6061 INFO: Processing pre-safe import module hook   gi.repository.Gdk
> 6062 INFO: Processing pre-safe import module hook   gi.repository.Atk
> 6063 INFO: Loading module hook "hook-encodings.py"...
> 6133 INFO: Loading module hook "hook-gi.repository.Gdk.py"...
> 6792 INFO: Processing pre-safe import module hook   gi.repository.cairo
> 6794 INFO: Processing pre-safe import module hook   gi.repository.Pango
> 6795 INFO: Processing pre-safe import module hook   gi.repository.GdkPixbuf
> 6796 INFO: Loading module hook "hook-gi.py"...
> 6808 INFO: Loading module hook "hook-xml.py"...
> 7044 INFO: Loading module hook "hook-pydoc.py"...
> 7045 INFO: Loading module hook "hook-gi.repository.Pango.py"...
> 7391 INFO: Loading module hook "hook-gi.repository.Atk.py"...
> 7768 INFO: Loading module hook "hook-gi.repository.Gio.py"...
> 8754 INFO: Processing pre-safe import module hook   gi.repository.GLib
> 8758 INFO: Loading module hook "hook-gi.repository.GObject.py"...
> 9124 INFO: Loading module hook "hook-gi.repository.cairo.py"...
> 9302 INFO: Loading module hook "hook-gi.repository.GdkPixbuf.py"...
> 9892 INFO: Processing pre-safe import module hook   gi.repository.GModule
> 9893 INFO: Loading module hook "hook-gi.repository.GLib.py"...
> 10373 INFO: Loading module hook "hook-gi.repository.GModule.py"...
> 10650 INFO: Looking for ctypes DLLs
> 10650 INFO: Analyzing run-time hooks ...
> 10653 INFO: Including run-time hook 'pyi_rth_gtk.py'
> 10655 INFO: Including run-time hook 'pyi_rth_glib.py'
> 10656 INFO: Including run-time hook 'pyi_rth_gdkpixbuf.py'
> 10658 INFO: Including run-time hook 'pyi_rth_gio.py'
> 10659 INFO: Including run-time hook 'pyi_rth_gi.py'
> 10665 INFO: Looking for dynamic libraries
> 10946 INFO: Looking for eggs
> 10946 INFO: Using Python library /usr/local/Frameworks//Python.framework/Versions/3.4/Python
> 10949 INFO: Warnings written to /Users/marko/gtk3test/build/gtk3test/warngtk3test.txt
> 12046 INFO: checking PYZ
> 12046 INFO: Building PYZ because out00-PYZ.toc is non existent
> 12046 INFO: Building PYZ (ZlibArchive) /Users/marko/gtk3test/build/gtk3test/out00-PYZ.pyz
> 12445 INFO: Building PYZ (ZlibArchive) /Users/marko/gtk3test/build/gtk3test/out00-PYZ.pyz completed successfully.
> 12475 INFO: checking PKG
> 12475 INFO: Building PKG because out00-PKG.toc is non existent
> 12475 INFO: Building PKG (CArchive) out00-PKG.pkg
> 12487 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
> 12491 INFO: Bootloader /usr/local/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/PyInstaller/bootloader/Darwin-64bit/run
> 12491 INFO: checking EXE
> 12492 INFO: Building EXE because out00-EXE.toc is non existent
> 12492 INFO: Building EXE from out00-EXE.toc
> 12492 INFO: Appending archive to EXE /Users/marko/gtk3test/build/gtk3test/gtk3test
> 12494 INFO: Fixing EXE for code signing /Users/marko/gtk3test/build/gtk3test/gtk3test
> 12504 INFO: Building EXE from out00-EXE.toc completed successfully.
> 12522 INFO: checking COLLECT
> 12522 INFO: Building COLLECT because out00-COLLECT.toc is non existent
> 12522 INFO: Building COLLECT out00-COLLECT.toc
> 20034 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

I’m using PyInstaller 3.2.1 (installed via pip) and custom compiled Python 3.4.3. 

Python was compiled with:
`./configure --enable-framework=/usr/local/Frameworks/ --enable-loadable-sqlite-extensions --with-ensurepip LDFLAGS="-L/usr/local/lib -L/usr/local/ssl/macos-x86_64/lib" CPPFLAGS="-I/usr/local/include -I/usr/local/ssl/macos-x86_64/include”`

Program does run from the source, as seen in the screen shot bellow.
![screenshot at jan 25 22-52-44](https://cloud.githubusercontent.com/assets/4953862/22311293/1bf5afc0-e353-11e6-8dd7-d324a25b37a0.png)

The source example can be found [here (5.5.1 example)](https://python-gtk-3-tutorial.readthedocs.io/en/latest/layout.html#headerbar). Note, I have used shebang ‘`#!/usr/local/bin/python3`’.

If you need additional information, I will happily provide it.

**Comment by htgoebel** [comment]
What ever is happening there, I suggest using a standard python installation like from homebrew instead using your self.made one.

The error message looks like there is something missing for GTK. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing. And follow *all* of the tips there.

**Comment by kostich** [comment]
I have removed my custom compiled Python and installed one via HomeBrew. Brew installed Python 3.6.0. After that I've installed PyInstaller via pip3.6.

Sadly, I'm now not able to freeze the application at all. Freeze output:

`$ pyinstaller gtk3test.py
52 INFO: PyInstaller: 3.2.1
52 INFO: Python: 3.6.0
58 INFO: Platform: Darwin-16.4.0-x86_64-i386-64bit
59 INFO: wrote /Users/marko/gtk3test/gtk3test.spec
61 INFO: UPX is not available.
64 INFO: Extending PYTHONPATH with paths
['/Users/marko/gtk3test', '/Users/marko/gtk3test']
64 INFO: checking Analysis
64 INFO: Building Analysis because out00-Analysis.toc is non existent
64 INFO: Initializing module dependency graph...
66 INFO: Initializing module graph hooks...
67 INFO: Analyzing base_library.zip ...
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 212, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/building/build_main.py", line 317, in assemble
    excludes=self.excludes, user_hook_dirs=self.hookspath)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 560, in initialize_modgraph
    graph.import_hook(m)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1509, in import_hook
    source_package, target_module_partname, level)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1661, in _find_head_package
    target_module_headname, target_package_name, source_package)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/depend/analysis.py", line 209, in _safe_import_module
    module_basename, module_name, parent_package)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2077, in _safe_import_module
    module_name, file_handle, pathname, metadata)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2167, in _load_module
    self._scan_code(m, co, co_ast)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2585, in _scan_code
    module, module_code_object, is_scanning_imports=False)
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2831, in _scan_bytecode
    global_attr_name = get_operation_arg_name()
  File "/usr/local/lib/python3.6/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2731, in get_operation_arg_name
    return module_code_object.co_names[co_names_index]
IndexError: tuple index out of range`

**Comment by tallforasmurf** [comment]
Now see #2394.

**Comment by htgoebel** [comment]
>  52 INFO: Python: 3.6.0

Sorry, butt PyInstaller is not supporting Python 3.6 yet. Please try to install Python 3.5. You may need to ask the homebrew guys how to do this, though.

**Comment by htgoebel** [comment]
Now new infos since 8 month, I assume this can be closed.
