### ISSUE TITLE
Clarify status of mailing list and IRC on PyInstaller website.

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#2414]
These forms of communication do not seem to be functional. A note should be added to the PyInstaller website to use the GitHub issue tracker if they aren't working.

**Comment by htgoebel** [comment]
Why is irc not functional? Well, the developers are there very seldom, but the channel is up and running so users can help each other.

**Comment by xoviat** [comment]
This is what @TTimo said:

> Unfortunately I have not been able to get any feedback from core developers on this. My posts to pyinstaller google group are not going through, and the irc channel is utterly dead.

**Comment by xoviat** [comment]
Perhaps change this:

> If you have problems to get your application running, please have a look at If Things Go Wrong and How to Report Bugs, which will help us a lot on solving the bug.


To this:

> If you have problems to get your application running, please have a look at If Things Go Wrong and How to Report Bugs, which will help us a lot on solving the bug. If the mailing list or IRC are unattended, you may be more likely to find help on the bug tracker.

**Comment by TTimo** [comment]
The irc channel I understand. I've been on there for two weeks now and clearly there are no knowledgeable developers, which is something that happens with those channels. I've been wondering if core devs were hiding somewhere else maybe.

The pyinstaller group is more a concern, I've sent several posts there and none got through. Google says I'm subscribed though :-(
