### ISSUE TITLE
Error : Failed to execute script  when using ( -w )command 

### ISSUE THREAD

**Issue by rijudewan** [pyinstaller/pyinstaller#2419]
Python 2.7 
windows 8.1
pyinstaller 3.2.1

when building exe with  -w option its giving error Failed to execute script  but if  i dint use -w option  exe will run fine with no error ..

does anyone has this error ..

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by jmason86** [comment]
This seems to be the same error occurring on Mac, as listed [here](https://github.com/pyinstaller/pyinstaller/issues/1804) and elsewhere.

**Comment by htgoebel** [comment]
No more information since 10 months. Closing.
