### ISSUE TITLE
Switch byte-code analysis to use `Instruction` (like dis3 does)

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2423]
I assume, the only feature of `dis3` we are using in #2418 is the `Instruction` class. So we should not rely on dis3 as this makes the code [more complicated](https://github.com/pyinstaller/pyinstaller/pull/2418/files#diff-5f9ee1e62ab5d182b523ba452ed0dba8R126). As you may have seen, I've added such a thing to `PyInstaller/depend/utils.py` (see aab279f3741398bcb71c43167a1abd1e3329d029). For now I'd just copy the code from there into modulegraph, adjusting and adding what is needed (e.g. this code currently does not provide `argval`).

**Comment by xoviat** [comment]
I _may_ take this depending on the outcome of [what I said][1].

[1]: https://github.com/pyinstaller/pyinstaller/pull/2418#issuecomment-277014561

**Comment by htgoebel** [comment]
We are not using our implementation of `Instruction`, but dis3 for Python2.7 and xdis for Python 3.3..
This is implemented as of 656fae0af179064e97b68d19734263b6083bf734.
