### ISSUE TITLE
Make modulegraph  non-recursive

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2426]
We have several issues hitting the maximum recursion depth of CPython, e.g. #2194, #2142.

So only solution solving the root cause is to change the modulegraph algorithm from recursive to non-recursive. Also see https://github.com/pyinstaller/pyinstaller/issues/1919#issuecomment-216016176

**Comment by xoviat** [comment]
I will submit a PR that does this for Python 3. Something odd is happening with Python 2.7, and I cannot debug that because I don't use Python 2.7.

**Comment by xoviat** [comment]
Associated PR is now #2428.

**Comment by adizhol** [comment]
Still get error in PyInstaller 3.3. Was it fixed in that version?

Thx

**Comment by Legorooj** [comment]
This will be fixed in the modulegraph rewrite.
