### ISSUE TITLE
Idea: semi-automatic way of updating the hooks.

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2431]
Right now we have an excellent test suite that checks a wide variety of plugins. If a test fails, we have to figure out what is missing. What I am proposing is this: if a test fails _and_  this is a nightly build, we can have the test suite actually run the python (unfrozen) script and based on the resources that it accesses, find out what is actually missing. The simplest (most robust) way would probably to literally monitor all file access calls and then compare that to what is frozen.

**Comment by htgoebel** [comment]
Oh, I completely missed this. Would be a good idea, even if quite some effort to develop.
