### ISSUE TITLE
TypeError: Unicode-objects must be encoded before hashing

### ISSUE THREAD

**Issue by 2819936788** [pyinstaller/pyinstaller#2444]
If you have problems to get your application running, please first

* follow the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If you problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.

**Otherwise we will not be able to help you.**

1, pyinstaller work on some "small" python program, but don't work on some "big" python.
   Actually I don't how to identify which one will be ok, and which one will be failed.

   However I got a patch to fix it and make it work.
   Attached  is the wrong message:
[pyinstaller.error.log.txt](https://github.com/pyinstaller/pyinstaller/files/760991/pyinstaller.error.log.txt)

   And my working patch is for "site-packages\PyInstaller\building\utils.py":

def cacheDigest(fnm, redirects):
    data = open(fnm, "rb").read()
    hasher = hashlib.md5(data)
    if redirects:
        #ERROR
        #hasher.update(str(redirects))
        #OK
        hasher.update(str(redirects).encode())
    digest = hasher.digest()
    return digest

**Comment by xoviat** [comment]
Thanks for this report:

```
Traceback (most recent call last):
  File "d:\apps\Anaconda3-win64\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.3.dev0+g8756735', 'console_scripts', 'pyinstaller')()
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 28, in <module>
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\building\api.py", line 398, in __init__
    strip_binaries=self.strip, upx_binaries=self.upx,
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\building\api.py", line 189, in __init__
    self.__postinit__()
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\building\api.py", line 252, in assemble
    dist_nm=inm)
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\building\utils.py", line 190, in checkCache
    digest = cacheDigest(fnm, redirects)
  File "d:\apps\Anaconda3-win64\lib\site-packages\PyInstaller\building\utils.py", line 337, in cacheDigest
    hasher.update(str(redirects))
TypeError: Unicode-objects must be encoded before hashing
```

> pyinstaller work on some "small" python program, but don't work on some "big" python.

That's fairly common. What we're trying to do here is very complicated and requires some very intricate algorithms. Sometimes we fail.

**Comment by xoviat** [comment]
Actually, you appear to be using an older version of PyInstaller. This issue has already been fixed in the latest version in d3e0cb4aa45493ab27a23953d72cd5f3ba50167d.

**Comment by zhengfish** [comment]
Sounds good. and Thanks for your fast feedback.
I use 3.2.3 and install it using conda:
conda install -c acellera pyinstaller=3.2.3

The version is right or not? I noticed that your latest version is 3.2.1 in the github repo.

Thanks again.

**Comment by xoviat** [comment]
How do you have version 3.2.3 when it hasn't been released yet?

**Comment by xoviat** [comment]
Anaconda doesn't appear to have the latest version of PyInstaller available. You can install from pypi or the github repository.

**Comment by 2819936788** [comment]
Hello,

I just search and got the "3.2.3" version from the anaconda channels.

The following command and its output are just for your reference.

c:\ > anaconda search -t conda pyinstaller

Run 'anaconda show <USER/PACKAGE>' to get more details:
Packages:
     Name                      |  Version | Package Types   | Platforms      
     ------------------------- |   ------ | --------------- | ---------------
     acellera-basic/pyinstaller |    3.2.3 | conda           | linux-64       
     acellera/pyinstaller      |    3.2.3 | conda           | linux-64, win-64
     auto/pyinstaller          |      2.1 | conda           | linux-64       
                                          : http://www.pyinstaller.org
     clg_boar/pyinstaller      |      3.2 | conda           | win-64         
     conda-forge/pyinstaller   |      3.2 | conda           | linux-64, win-32, win-64, osx-64
     silg2/pyinstaller         |      3.2 | conda           | linux-64, win-64
                                          : PyInstaller bundles a Python application and all its dependencies into a single package.
     snorfalorpagus/pyinstaller |    3.1.1 | conda           | win-64         
                                          : PyInstaller bundles a Python application and all its dependencies into a single package.
     trung/pyinstaller         |      3.1 | conda           | linux-64, osx-64
                                          : Converts (packages) Python programs into stand-alone executables, under Windows, Linux, Mac OS X, AIX and Solaris.
Found 8 packages
Using Anaconda API: https://api.anaconda.org

**Comment by xoviat** [comment]
> I just search and got the "3.2.3" version from the anaconda channels.

Yeah. I looked at that package and the version is not correct.

**Comment by htgoebel** [comment]
@2819936788 There is not PyInstaller 3.2.3. Throw it away and follow the instructions in the first comment of this ticket - the text you did not even care to delete, so I have doubt you have read it.

**Otherwise we will not be able to help you.**
