### ISSUE TITLE
Document running PyInstaller with `-O`

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2447]
Document how to make PyInstaller creating optimized (`-O`, `-OO`) code, see #2442.

You can simply run `python -O /path/to/pyinstaller/` or `python -O -m PyInstaller`.

I have to admit that this is not obvious since pyinstaller is installed via pip, but it still works. I'd not spend too much effort on this as `.pyo` files are bound to be removed soon (no source at hand ATM).

**Comment by xoviat** [comment]
The issue that I opened had nothing to do with optimizing Python code. It was about setting the `__debug__` flag, in here:

https://github.com/python/cpython/blob/a9c6fa3fe6e63c85da0c7214f2a280838e897d39/Python/bltinmodule.c#L2739

**Comment by htgoebel** [comment]
[`-O`](https://docs.python.org/3/using/cmdline.html#cmdoption-O) sets `__debug__` to `False`, see https://docs.python.org/3/library/constants.html#__debug__.

Doe to byte-code optimizations, this will also eliminate all code within a `if __debug__` block (this behavior may vary between Python versions).

**Comment by xoviat** [comment]
> -O sets `__debug__` to False, see https://docs.python.org/3/library/constants.html#__debug__.

Yes. My proposal was to set debug to False for the standard bootloaders and to True for the debug bootloaders.

**Comment by htgoebel** [comment]
This ticket is about documenting how to to it, not about changing the bootloader.

**Comment by xoviat** [comment]
I understand that, but you closed the ticket that I opened about changing the bootloader. If you want me to drop the issue, that's fine. I won't discuss it further.

**Comment by htgoebel** [comment]
> but you closed the ticket that I opened about changing the bootloader

I'm curious: Isn't it possible to comment on a closed ticket? (I rarely do, so I don't know.)

**Comment by nejch** [comment]
Hi @htgoebel, I just submitted a PR as I think this will remain relevant. I checked [PEP 488](https://www.python.org/dev/peps/pep-0488/), which was implemented to eliminate `.pyo` files, but this does not affect the optimization options, only the files generated. See below:

CPython 3.5 changelog:

> - `.pyo` files are no longer used and have been replaced by a more flexible scheme that includes the optimization level explicitly in `.pyc` name. 

PEP 488:
> For example, a source file named foo.py in CPython 3.5 could have the following bytecode files based on the interpreter's optimization level (none, `-O`, and `-OO`):
> 
> - 0: `foo.cpython-35.pyc `(i.e., no change)
> - 1: `foo.cpython-35.opt-1.pyc`
> - 2: `foo.cpython-35.opt-2.pyc`
