### ISSUE TITLE
Resource file missing?

### ISSUE THREAD

**Issue by kkar** [pyinstaller/pyinstaller#2449]
Hello,
as I mentioned [here](http://stackoverflow.com/questions/42163205/pyinstaller-resource-file-missing), I am trying to have an extra resource file packed within the main PE but it seems that it isn't working this way. I need to include my resource file in the resulting executable, to be ... ready-to-be-deployed ... on all my workstations in my domain.

The only way of achieving my task for now, is to extra-upload my resource file and put it in the EXE's directory, which is not practical at all.

Is there any wayarround? Thanks.

**Comment by JMSwag** [comment]
See [adding data files](https://pythonhosted.org/PyInstaller/spec-files.html#adding-files-to-the-bundle).

**Comment by htgoebel** [comment]
I assume this answers the question.
