### ISSUE TITLE
“Failed to execute script pyi_rth_qt4plugins” error when import any Python Data Stack library

### ISSUE THREAD

**Issue by ebonat** [pyinstaller/pyinstaller#2461]
Hi Hartmut,

This error occurred when application is running. I used:

- PyInstaller 3.3
- Python 3.5.2
- Windows 10
- Anaconda Bundle for data analysis library (pandas, numpy, etc.)

Here is the Python code:
```
import sys
from helper.helper import Helper
from PyQt5 import QtCore, QtGui, QtPrintSupport, QtWidgets

import numpy as np
import pandas as pd
import seaborn as sns

class MainWindow(QtWidgets.QMainWindow):
   
    def __init__(self):        
        super(MainWindow, self).__init__()
        self.setObjectName("MainWindow")
        self.resize(300, 60)
        self.setWindowTitle("Testing PyInstaller")
        self.centralwidget = QtWidgets.QWidget(self)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButtonExit = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonExit.setGeometry(QtCore.QRect(200, 10, 75, 23))
        self.pushButtonExit.setObjectName("pushButtonExit")
        self.pushButtonExit.setText("Exit")
        self.pushButtonExit.clicked.connect(self.close_main_window)
        self.setCentralWidget(self.centralwidget)    
            
    def close_main_window(self):               
        self.close()         
            
if __name__ == "__main__":  
    application = QtWidgets.QApplication(sys.argv)
    main_window = MainWindow()
    main_window.show()
    sys.exit(application.exec_())
```
Without these lines:
```
import numpy as np
import pandas as pd
import seaborn as sns
```
there is not error at all.

Below is the result of running the installer:

1098 INFO: PyInstaller: 3.3.dev0+c3a3758
1098 INFO: Python: 3.5.2
1099 INFO: Platform: Windows-10-10.0.14393-SP0
1107 INFO: wrote C:\Users\Ernest\workspace\qt_designer_test\src\test_py_install.spec
1111 INFO: UPX is not available.
1114 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Ernest\\workspace\\qt_designer_test\\src',
 'C:\\Users\\Ernest\\workspace\\qt_designer_test\\src']
1114 INFO: checking Analysis
1114 INFO: Building Analysis because out00-Analysis.toc is non existent
1115 INFO: Initializing module dependency graph...
1123 INFO: Initializing module graph hooks...
1130 INFO: Analyzing base_library.zip ...
12525 INFO: running Analysis out00-Analysis.toc
13442 INFO: Caching module hooks...
13452 INFO: Analyzing C:\Users\Ernest\workspace\qt_designer_test\src\test_py_installer_for_windows.py
16376 INFO: Processing pre-find module path hook   distutils
24019 INFO: Processing pre-find module path hook   site
24025 INFO: site: retargeting to fake-dir 'C:\\Users\\Ernest\\AppData\\Local\\Continuum\\lib\\site-packages\\PyInstaller\\fake-modules'
24088 INFO: Processing pre-safe import module hook   win32com
29083 INFO: Processing pre-safe import module hook   six.moves
49705 INFO: Processing pre-safe import module hook   requests.packages.urllib3.packages.six.moves
141835 INFO: Loading module hooks...
141836 INFO: Loading module hook "hook-PyQt4.py"...
141841 INFO: Loading module hook "hook-jinja2.py"...
141888 INFO: Loading module hook "hook-scipy.linalg.py"...
141894 INFO: Loading module hook "hook-babel.py"...
142056 INFO: Loading module hook "hook-lib2to3.py"...
142064 INFO: Loading module hook "hook-PIL.py"...
142077 INFO: Excluding import 'PySide'
142086 WARNING:   Removing import PIL.ImageQt from module PySide
142086 INFO: Excluding import 'tkinter'
142094 INFO: Excluding import 'PyQt5'
142103 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtCore
142103 WARNING:   Removing import PIL.ImageQt from module PyQt5.QtGui
142104 INFO: Import to be excluded not found: 'FixTk'
142104 INFO: Excluding import 'PyQt4'
142113 INFO: Loading module hook "hook-_tkinter.py"...
142450 INFO: checking Tree
142451 INFO: Building Tree because out00-Tree.toc is non existent
142451 INFO: Building Tree out00-Tree.toc
142589 INFO: checking Tree
142589 INFO: Building Tree because out01-Tree.toc is non existent
142590 INFO: Building Tree out01-Tree.toc
142618 INFO: Loading module hook "hook-distutils.py"...
142624 INFO: Loading module hook "hook-PyQt5.QtSvg.py"...
142631 INFO: Loading module hook "hook-requests.py"...
142643 INFO: Loading module hook "hook-sysconfig.py"...
142650 INFO: Loading module hook "hook-matplotlib.backends.py"...
144357 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
145719 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
146209 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
146937 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
147939 INFO:   Matplotlib backend "Qt4Agg": added
148746 INFO:   Matplotlib backend "Qt5Agg": added
149537 INFO:   Matplotlib backend "TkAgg": added
150272 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
150994 INFO:   Matplotlib backend "WXAgg": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
151489 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
152221 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
154517 INFO:   Matplotlib backend "WebAgg": added
158787 INFO:   Matplotlib backend "nbAgg": added
159507 INFO:   Matplotlib backend "agg": added
159996 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
160546 INFO:   Matplotlib backend "emf": ignored
    No module named 'matplotlib.backends.backend_emf'
161029 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
161785 INFO:   Matplotlib backend "pdf": added
163015 INFO:   Matplotlib backend "pgf": added
163744 INFO:   Matplotlib backend "ps": added
164520 INFO:   Matplotlib backend "svg": added
165245 INFO:   Matplotlib backend "template": added
165941 INFO: Loading module hook "hook-pycparser.py"...
166401 INFO: Loading module hook "hook-openpyxl.py"...
166416 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
166421 INFO: Loading module hook "hook-jsonschema.py"...
166428 INFO: Loading module hook "hook-zmq.py"...
170080 INFO: Excluding import 'zmq.libzmq'
170089 WARNING:   Removing import zmq from module zmq.libzmq
170092 INFO: Loading module hook "hook-pydoc.py"...
170099 INFO: Loading module hook "hook-pygments.py"...
174200 INFO: Loading module hook "hook-numpy.core.py"...
174379 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
174384 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
175036 INFO: Loading module hook "hook-xml.dom.domreg.py"...
175042 INFO: Loading module hook "hook-PyQt5.py"...
175053 INFO: Loading module hook "hook-tables.py"...
175061 INFO: Loading module hook "hook-sphinx.py"...
188932 INFO: Loading module hook "hook-encodings.py"...
189081 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
189087 INFO: Loading module hook "hook-pywintypes.py"...
189869 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
190001 INFO: Loading module hook "hook-setuptools.py"...
190007 INFO: Loading module hook "hook-pythoncom.py"...
190788 INFO: Loading module hook "hook-sqlalchemy.py"...
191670 INFO:   Found 2 sqlalchemy hidden imports
191673 WARNING: Hidden import "MySQLdb" not found!
191674 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
191684 INFO: Excluding import 'sqlalchemy.testing'
191694 WARNING:   Removing import sqlalchemy.testing.exclusions from module sqlalchemy.testing
191694 WARNING:   Removing import sqlalchemy.testing.exclusions from module sqlalchemy.testing.config
191695 WARNING:   Removing import sqlalchemy.testing.warnings from module sqlalchemy.testing
191696 WARNING:   Removing import sqlalchemy.testing.warnings from module sqlalchemy.testing.assertions
191699 WARNING:   Removing import sqlalchemy.orm.util from module sqlalchemy.testing.util
191700 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing.exclusions
191701 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing.warnings
191702 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing
191703 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing.util
191704 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing.config
191704 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing.engines
191705 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing.assertions
191706 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing.assertsql
191707 WARNING:   Removing import sqlalchemy.testing from module sqlalchemy.testing.mock
191708 WARNING:   Removing import sqlalchemy.testing.util from module sqlalchemy.testing
191709 WARNING:   Removing import sqlalchemy.testing.util from module sqlalchemy.testing.engines
191710 WARNING:   Removing import sqlalchemy.testing.util from module sqlalchemy.testing.config
191713 WARNING:   Removing import sqlalchemy.testing.assertions from module sqlalchemy.testing.exclusions
191713 WARNING:   Removing import sqlalchemy.testing.assertions from module sqlalchemy.testing
191714 WARNING:   Removing import sqlalchemy.testing.assertions from module sqlalchemy.testing.util
191714 WARNING:   Removing import sqlalchemy.testing.assertions from module sqlalchemy.testing.config
191715 WARNING:   Removing import sqlalchemy.testing.assertions from module sqlalchemy.testing.assertsql
191716 WARNING:   Removing import sqlalchemy.testing.assertions from module sqlalchemy.testing.mock
191717 WARNING:   Removing import sqlalchemy.testing.engines from module sqlalchemy.testing
191717 WARNING:   Removing import sqlalchemy.testing.engines from module sqlalchemy.testing.assertions
191718 WARNING:   Removing import sqlalchemy.testing.engines from module sqlalchemy.testing.util
191718 WARNING:   Removing import sqlalchemy.testing.engines from module sqlalchemy.testing.config
191719 WARNING:   Removing import sqlalchemy.testing.mock from module sqlalchemy.testing
191720 WARNING:   Removing import sqlalchemy.testing.assertsql from module sqlalchemy.testing
191722 WARNING:   Removing import sqlalchemy.testing.config from module sqlalchemy.testing
191725 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
191828 INFO: Loading module hook "hook-patsy.py"...
191833 INFO: Loading module hook "hook-lxml.etree.py"...
191862 INFO: Loading module hook "hook-sqlite3.py"...
192026 INFO: Loading module hook "hook-matplotlib.py"...
192536 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
192551 INFO: Loading module hook "hook-xml.py"...
192556 INFO: Loading module hook "hook-pytz.py"...
192694 INFO: Loading module hook "hook-win32com.py"...
193013 INFO: Loading module hook "hook-pkg_resources.py"...
194671 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
194677 INFO: Loading module hook "hook-boto.py"...
194711 INFO: Loading module hook "hook-docutils.py"...
197539 INFO: Loading module hook "hook-IPython.py"...
197568 INFO: Excluding import 'PySide'
197585 WARNING:   Removing import IPython.external.qt_loaders from module PySide
197587 INFO: Excluding import 'tkinter'
197602 WARNING:   Removing import IPython.lib.clipboard from module tkinter
197607 INFO: Excluding import 'matplotlib'
197623 WARNING:   Removing import IPython.core.pylabtools from module matplotlib._pylab_helpers
197624 WARNING:   Removing import IPython.core.pylabtools from module matplotlib
197626 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.pyplot
197628 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.figure
197629 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.pylab
197632 INFO: Excluding import 'gtk'
197651 INFO: Excluding import 'PyQt4'
197667 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtSvg
197667 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtGui
197668 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtCore
197669 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4
197674 INFO: Excluding import 'PyQt5'
197690 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5
197691 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5.QtSvg
197692 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5.QtWidgets
197693 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5.QtCore
197694 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5.QtGui
197697 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
197702 INFO: Loading module hook "hook-shelve.py"...
197735 INFO: Loading module hook "hook-cryptography.py"...
201886 INFO: Loading module hook "hook-PIL.Image.py"...
202771 INFO: Loading module hook "hook-scipy.io.matlab.py"...
202778 INFO: Loading module hook "hook-gevent.monkey.py"...
202801 INFO: Loading module hook "hook-PyQt5.Qt.py"...
202809 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
202826 INFO: Excluding import 'tkinter'
202836 INFO: Import to be excluded not found: 'FixTk'
204536 INFO: checking Tree
204537 INFO: Building Tree because out02-Tree.toc is non existent
204538 INFO: Building Tree out02-Tree.toc
204551 INFO: Looking for ctypes DLLs
204562 WARNING: library dllpaths required via ctypes not found
205026 INFO: Analyzing run-time hooks ...
205102 INFO: Including run-time hook 'pyi_rth_traitlets.py'
205112 INFO: Including run-time hook 'pyi_rth_pkgres.py'
205121 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
205133 INFO: Including run-time hook 'pyi_rth__tkinter.py'
205143 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
205155 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
205164 INFO: Including run-time hook 'pyi_rth_mpldata.py'
205172 INFO: Including run-time hook 'pyi_rth_qt5.py'
205182 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
205322 INFO: Looking for dynamic libraries
205752 WARNING: lib not found: tbb.dll dependency of C:\Users\Ernest\AppData\Local\Continuum\Library\bin\mkl_tbb_thread.dll
210080 WARNING: lib not found: libzmq.cp35-win_amd64.pyd dependency of C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\zmq\backend\cython\_p
oll.cp35-win_amd64.pyd
210288 WARNING: lib not found: libzmq.cp35-win_amd64.pyd dependency of C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\zmq\backend\cython\so
cket.cp35-win_amd64.pyd
210525 WARNING: lib not found: libzmq.cp35-win_amd64.pyd dependency of C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\zmq\backend\cython\me
ssage.cp35-win_amd64.pyd
210728 WARNING: lib not found: libzmq.cp35-win_amd64.pyd dependency of C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\zmq\backend\cython\er
ror.cp35-win_amd64.pyd
210926 WARNING: lib not found: libzmq.cp35-win_amd64.pyd dependency of C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\zmq\backend\cython\co
ntext.cp35-win_amd64.pyd
211157 WARNING: lib not found: libzmq.cp35-win_amd64.pyd dependency of C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\zmq\backend\cython\_v
ersion.cp35-win_amd64.pyd
211355 WARNING: lib not found: libzmq.cp35-win_amd64.pyd dependency of C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\zmq\backend\cython\ut
ils.cp35-win_amd64.pyd
211552 WARNING: lib not found: libzmq.cp35-win_amd64.pyd dependency of C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\zmq\backend\cython\_d
evice.cp35-win_amd64.pyd
215907 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_18f8a87fd1919cd9.manifest
215913 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
215921 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
215922 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_acd10521e1dac77d.manifest
216076 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9247_none ...
216076 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_08e394a1a83e212f.manifest
216080 INFO: Searching for file msvcr90.dll
216081 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_08e394a1a83e212f\msvcr90.dll
216081 INFO: Searching for file msvcp90.dll
216082 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_08e394a1a83e212f\msvcp90.dll
216083 INFO: Searching for file msvcm90.dll
216084 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_08e394a1a83e212f\msvcm90.dll
216242 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.21022.8_none_18f8a87fd1919cd9.manifest
216244 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
216245 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
216248 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_acd10521e1dac77d.manifest
216250 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
217454 INFO: Looking for eggs
217454 INFO: Using Python library C:\Users\Ernest\AppData\Local\Continuum\python35.dll
217455 INFO: Found binding redirects:
[BindingRedirect(name='Microsoft.VC90.CRT', language=None, arch='amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9247), publicKeyToken='
1fc8b3b9a1e18e3b')]
217521 INFO: Warnings written to C:\Users\Ernest\workspace\qt_designer_test\src\build\test_py_install\warntest_py_install.txt
218171 INFO: checking PYZ
218171 INFO: Building PYZ because out00-PYZ.toc is non existent
218173 INFO: Building PYZ (ZlibArchive) C:\Users\Ernest\workspace\qt_designer_test\src\build\test_py_install\out00-PYZ.pyz
232547 INFO: Building PYZ (ZlibArchive) C:\Users\Ernest\workspace\qt_designer_test\src\build\test_py_install\out00-PYZ.pyz completed successfully.
232966 INFO: checking PKG
232967 INFO: Building PKG because out00-PKG.toc is non existent
232971 INFO: Building PKG (CArchive) out00-PKG.pkg
233123 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
233132 INFO: Bootloader C:\Users\Ernest\AppData\Local\Continuum\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
233132 INFO: checking EXE
233133 INFO: Building EXE because out00-EXE.toc is non existent
233137 INFO: Building EXE from out00-EXE.toc
233141 INFO: Appending archive to EXE C:\Users\Ernest\workspace\qt_designer_test\src\build\test_py_install\test_py_install.exe
233230 INFO: Building EXE from out00-EXE.toc completed successfully.
233253 INFO: checking COLLECT
233253 INFO: Building COLLECT because out00-COLLECT.toc is non existent
233254 INFO: Building COLLECT out00-COLLECT.toc
272606 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

This is all I have. I know this project is voluntary, so please let me know how can I help you to fix this issue. This is very important for Python Data Science community today!

Thank you very much in advanced.

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Scientist

**Comment by htgoebel** [comment]
> please let me know how can I help you to fix this issue.

Please check the other issues and pull-requests related to Qt and help solving them.

**Comment by ebonat** [comment]
I did not found any related issue closed to this bug. There is not any issues with PyQT library at all. This error appears with Python Data Stack libraries as I explained before like pandas, seaborn, numpy, etc.

**Comment by xoviat** [comment]
> PyInstaller 3.3

Alarm bells!!!

**Comment by ebonat** [comment]
I did install it as: pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip. As it was recommended and this version is 3.3. 

I'm very active on this issues because is very important for the whole Python Data Science community today! It needs to be fixed as soon as we can. Let's help each other to fix it! I'm open for any thing to do!

Thanks all,

Ernest Bonat, Ph.D.
Senior Software Engineer
Senior Data Scientist

**Comment by htgoebel** [comment]
> I did install it as: pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip. As it was recommended and this version is 3.3.

I doubt, since 3.3  its not releases yet. Please post the *full* output  od `pyinstaller --version` This should report something like "3.3.dev0+g463d40b.mod".

**Comment by htgoebel** [comment]
BTW: There is not need to put your signature into every message.

**Comment by ebonat** [comment]
The pyinstaller version I use is: **3.3.dev0+c3a3758**

**Comment by xoviat** [comment]
@ebonat For future reference, please learn markdown and use the code tags correctly.

**Comment by ebonat** [comment]
sure! thank you for the remaining!

**Comment by xoviat** [comment]
I was not able to reproduce this on my win10 amd64 py36 platform. The possibilities for this are:

1. Qt binaries are not added ( #2403 ).
2. Something is not installed correctly.
3. Problems with anaconda

**Comment by ebonat** [comment]
About:

**Comment by ebonat** [comment]
Hi,

I forgot to mention, just in case, we can chat via Skype at any time if necessary. My Skype account is ebonatcupdx.

**Comment by xoviat** [comment]
What is your application directory structure?

```
PS> ls -Recurse
```

**Comment by ebonat** [comment]
All the code is in:

C:\Users\Ernest\workspace\qt_designer_test\src\test_py_installer_for_windows.py

main folder: qt_designer_test
second folder: qt_designer_test

And the file is test_py_installer_for_windows.py

That's all!

**Comment by xoviat** [comment]
No, I mean the dist directory that pyinstaller generates.

**Comment by htgoebel** [comment]
Please provide the Python traceback showing the exact error message.

**Comment by ebonat** [comment]
About: _No, I mean the dist directory that pyinstaller generates_. Explain what do you need specific? The dist folder has 19 folders and 267 files. Let me know!

About: _Please provide the Python traceback showing the exact error message._ Need more explanation in how to get the traceback. I run the installer and the test_py_install.exe file is created. I double-click on the file and the message box appears with the info: “Failed to execute script pyi_rth_qt4plugins”. Let me know?

**Comment by xoviat** [comment]
Copy me:

```
PS C:\Users\User\Downloads\dist> ls -Recurse | Out-File structure.txt
```

https://gist.github.com/xoviat/42eb48cbcc820d07ef3e31538c1565fb

**Comment by ebonat** [comment]
Here is the error:

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\Users\Ernest>cd C:\Users\Ernest\workspace\qt_designer_test\src\dist

C:\Users\Ernest\workspace\qt_designer_test\src\dist>ls -Recurse | Out-File structure.txt
'ls' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\Ernest\workspace\qt_designer_test\src\dist>

**Comment by xoviat** [comment]
See that:

```
PS
```

That means I'm using powershell. You should too because microsoft says so.

**Comment by ebonat** [comment]
trying now...microsoft?

**Comment by xoviat** [comment]
> PowerShell in the Shell: In an effort to bring the best command line experiences to the forefront for all power users, PowerShell is now the defacto command shell from File Explorer. It replaces Command Prompt (aka, “cmd.exe”) in the WIN + X menu, in File Explorer’s File menu, and in the context menu that appears when you shift-right-click the whitespace in File Explorer. Typing “cmd” (or “PowerShell”) in File Explorer’s address bar will remain a quick way to launch the command shell at that location. For those who prefer to use Command Prompt, you can opt out of the WIN + X change by opening Settings > Personalization > Taskbar, and turning “Replace Command Prompt with Windows PowerShell in the menu when I right-click the Start button or press Windows key+X” to “Off“.

**Comment by xoviat** [comment]
@htgoebel is probably going to be irritated at me for giving tutor lessons.

**Comment by ebonat** [comment]
no, don't say that! you're providing an excellent support. if you come to portland, oregon  some day, let me know and we'll go for free lunch!

**Comment by ebonat** [comment]
ok, the structure.txt file is created, how to post it for you?

**Comment by xoviat** [comment]
gist.github.com

**Comment by ebonat** [comment]
Here: https://gist.github.com/ebonat/2c916539c71931fd76099b8732c5ef82

let me know if you need something else?

**Comment by xoviat** [comment]
Build the app without --windowed and run it from a command prompt to get the full error output.**

**Comment by ebonat** [comment]
Here is the traceback running from the command prompt:

```
PS C:\Users\Ernest\workspace\qt_designer_test\src> C:\Users\Ernest\workspace\qt_designer_test\src\dist\test_py_install\test_py_install.exe
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt4plugins.py", line 41, in <module>
ImportError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt4plugins.py", line 43, in <module>
ImportError: No module named 'PyQt4.QtCore'
Failed to execute script pyi_rth_qt4plugins
```

**Comment by ebonat** [comment]
As you can see from my code, I'm using PyQt5 as:

`from PyQt5 import QtCore, QtGui, QtPrintSupport, QtWidgets`

**Comment by xoviat** [comment]
In site packages (where PyInstaller is located) edit following file

`PyInstaller/loader/rthooks.dat`

Remove this line:

`    'PyQt4':      ['pyi_rth_qt4plugins.py'],`

**Comment by ebonat** [comment]
ok, doing now... and testing...

**Comment by ebonat** [comment]
no errors occurred at the command prompt. testing with --windowed  to run on windows now...

**Comment by ebonat** [comment]
and no errors on windows occurred too! - `excellent news!` 

but here is a concern. let's look at the rthooks.dat

```
{
    'django':     ['pyi_rth_django.py'],
    'enchant':    ['pyi_rth_enchant.py'],
    'gi':         ['pyi_rth_gi.py'],
    'gi.repository.Gio':    ['pyi_rth_gio.py'],
    'gi.repository.GLib':   ['pyi_rth_glib.py'],
    'gi.repository.GdkPixbuf':    ['pyi_rth_gdkpixbuf.py'],
    'gi.repository.Gtk':    ['pyi_rth_gtk.py'],
    'gi.repository.Gst':    ['pyi_rth_gstreamer.py'],
    'gst':        ['pyi_rth_gstreamer.py'],
    'kivy':       ['pyi_rth_kivy.py'],
    'kivy.lib.gstplayer': ['pyi_rth_gstreamer.py'],
    'matplotlib': ['pyi_rth_mplconfig.py', 'pyi_rth_mpldata.py'],
    'osgeo':      ['pyi_rth_osgeo.py'],
    'pkg_resources':  ['pyi_rth_pkgres.py'],
    'PyQt5':      ['pyi_rth_qt5.py', 'pyi_rth_qt5plugins.py'],
    'PyQt5.QtQuick':  ['pyi_rth_qml.py'],
    'PyQt5.QtWebEngineWidgets': ['pyi_rth_qt5webengine.py'],
    'PySide':      ['pyi_rth_qt4plugins.py'],
    '_tkinter':    ['pyi_rth__tkinter.py'],
    'traitlets':  ['pyi_rth_traitlets.py'],
    'twisted.internet.reactor':        ['pyi_rth_twisted.py'],
    'usb':        ['pyi_rth_usb.py'],
    'win32com':   ['pyi_rth_win32comgenpy.py'],
}
```
where are the lines for:

```
import numpy as np
import pandas as pd
import seaborn as sns
```

do we need them on this dat file? this is the question.

**Comment by xoviat** [comment]
> do we need them on this dat file? this is the question.

Runtime hooks are used for specific cases where PyInstaller cannot work without runtime module modifications. Not all modules require runtime module modifications; in fact PyInstaller would not be a viable project if most did.

The root cause is that PyInstaller included the pyqt4 runtime hook when it should not have. @htgoebel Do we test whether the package exists before including the runtime hook in the TOC? If not, then we probably should.

**Comment by ebonat** [comment]
I have the my question too. We may have PyQT6 this year 2017?

Do we test whether the package exists before including the runtime hook in the TOC? If not, then we probably should.

**Comment by xoviat** [comment]
> I have the my question too. We may have PyQT6 this year 2017?

I hope not. PyQt requires a lot of work on our side to get running properly. Once PyQt6 is released, people (like you) will be asking for it which means we will have more work on our plate.

**Comment by ebonat** [comment]
I know!

I just want to say THANK YOU VERY MUCH for your deduction fixing this bus today. Now the Python Data Stack community can deploy windows application using Data Science Libraries! - very important!

**Comment by bjones1** [comment]
Some older notes on modulegraph, pandas, and pyqt4/5 confusion: https://github.com/pyinstaller/pyinstaller/issues/2024#issuecomment-224410240.

**Comment by htgoebel** [comment]
> probably going to be irritated at me for giving tutor lessons.

Yes, tutoring a "Senior Software Engineer, Senior Data Scientist" is not what I would spend my time on - except if been paid for. But your mileage may vary :-)

> Do we test whether the package exists before including the runtime hook in the TOC? If not, then we probably should.

The inclusion of rt-hooks is triggered if the respective  module is included. Maybe this need to be fixed for the case that the module is imported but not actually included – e.g. since it's actually excluded be something else.

**Comment by htgoebel** [comment]
I take https://github.com/pyinstaller/pyinstaller/issues/2461#issuecomment-280225146 as "solved.

**Comment by w4sevens** [comment]
> 
> 
> In site packages (where PyInstaller is located) edit following file:
> 
> `PyInstaller/loader/rthooks.dat`
> 
> Remove this line:
> 
> ` 'PyQt4': ['pyi_rth_qt4plugins.py'],`
> 
> Then re-run PyInstaller.

i met the same issue, and it already solved, thankyou, i spent almost 7 day ........
