### ISSUE TITLE
PyInstaller should not check for modules specific for other than the current platform

### ISSUE THREAD

**Issue by henrykironde** [pyinstaller/pyinstaller#2462]
**Python extensions for Windows**

We should not be checking for these modules in os x and linux.

**Comment by htgoebel** [comment]
This should work in either directions.

Can you please provide a list of modules to specific to each platform and thus to be excluded on other platforms. These should then be added to `excludes` somewhere reasonable - preferable in `depend/analysis.py.

And of course, a pull-request would be fine :-)
