### ISSUE TITLE
openpyxl trips on data file

### ISSUE THREAD

**Issue by ahed87** [pyinstaller/pyinstaller#2465]
Awesome piece of tool this pyinstaller, struggled a bit to get over the initial hurdle, but not too much.
```
312 INFO: PyInstaller: 3.2.1
312 INFO: Python: 3.4.3 (32-bit)
312 INFO: Platform: Windows-8-6.2.9200 (64-bit)
20983 INFO: Loading module hook "hook-openpyxl.py"...
```
It tripped on a file in a test folder > [Content_Types].xml < (yepp, it has square brackets in the name).
`openpyxl.__version__ = 2.4.2`

I got past it by simply removing the file, and the generated .exe seems to work fine.

Feel free to close this one wo action, it's just a small awareness thing and hopefully help for others.

**Comment by xoviat** [comment]
Would you mind providing a traceback?

**Comment by htgoebel** [comment]
"test folder" sounds like the package includes a sub-package "tests". If this is the case, we could add it `excluded_imports` of that hook (if we have one).

**Comment by ahed87** [comment]
I believe htgoebel is on the right track.
It was a pip installed openpyxl out of the box.
Location & file that tripped it was:
C:\Python34\Lib\site-packages\openpyxl\openpyxl\writer\tests\data\[Content_Types].xml

So I'm guessing everyone is subjected to it, and there is a hook.

I have to be honest and say that I have looked around for a while and have not yet found an example of how to exclude a file or a folder (adding there are examples of), also the docs only mention packages/modules when using exclude in the spec-file.

If you give me a hint on what path to go I could do an attempt to see if I can get it working on my computer and if so I could do a PR on the current hook-file on the repository.

Cheers

**Comment by htgoebel** [comment]
> It tripped on a file in a test folder > [Content_Types].xml <

What exactly you you mean with "tripped"? Your initial message does not show any error.

**Comment by htgoebel** [comment]
The [hook](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/hooks/hook-openpyxl.py) uses [`collect_datafiles`](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/utils/hooks/__init__.py#L694) which does not have an exclude option yet.  Maybe we should implement this like for [`TOC`](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/building/datastruct.py#L260)?!

**Comment by ahed87** [comment]
C:\...\the>pyinstaller tk_gui_openpyxl.py
300 INFO: PyInstaller: 3.2.1
300 INFO: Python: 3.4.3
300 INFO: Platform: Windows-8-6.2.9200
316 INFO: wrote C:\...\the\tk_gui_openpyxl.spec
316 INFO: UPX is not available.
316 INFO: Extending PYTHONPATH with paths
['C:\\...\\the',
 'C:\\...\\the']
316 INFO: checking Analysis
316 INFO: Building Analysis because out00-Analysis.toc is non existent
338 INFO: Initializing module dependency graph...
338 INFO: Initializing module graph hooks...
359 INFO: Analyzing base_library.zip ...
6261 INFO: Processing pre-find module path hook   distutils
10483 INFO: running Analysis out00-Analysis.toc
10730 INFO: Caching module hooks...
10762 INFO: Analyzing C:\...\the\tk_gui_openpyxl.py
19624 INFO: Loading module hooks...
19624 INFO: Loading module hook "hook-openpyxl.py"...
Traceback (most recent call last):
  File "C:\Python34\Scripts\pyinstaller-script.py", line 9, in <module>
    load_entry_point('PyInstaller==3.2.1', 'console_scripts', 'pyinstaller')()
  File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 90, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Python34\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 788, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 734, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 212, in __init__
    self.__postinit__()
  File "C:\Python34\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "C:\Python34\lib\site-packages\PyInstaller\building\build_main.py", line 470, in assemble
    module_hook.post_graph()
  File "C:\Python34\lib\site-packages\PyInstaller\building\imphook.py", line 409, in post_graph
    self._load_hook_module()
  File "C:\Python34\lib\site-packages\PyInstaller\building\imphook.py", line 390, in _load_hook_module
    attr_value = sanitizer_func(attr_value)
  File "C:\Python34\lib\site-packages\PyInstaller\building\utils.py", line 466, in format_binaries_and_datas
    src_root_path_or_glob))
FileNotFoundError: Path or glob "C:\Python34\lib\site-packages\openpyxl\openpyxl\writer\tests\data\[Content_Types].xml"
not found or matches no files.

C:\...\the>

**Comment by ahed87** [comment]
the file is obviously there and can be opened from a regular python promt, and the error goes away if the file is removed from the folder.

**Comment by htgoebel** [comment]
Thanks for the trace-back. This looks like a duplicate of #2314 and may we much easier to solve than adding some `exclude` argument. Can you please apply #2375 and test. (Add `.patch` to the URL to get the raw patch.)

**Comment by ahed87** [comment]
works, thanks (did it the oldfashion way of copy paste into local source).

**Comment by htgoebel** [comment]
@ahed87 Thanks for the info. I just merged the pull-request into the develop branch, so you'll not need to maintain you patched version.
