### ISSUE TITLE
Bootloader: DEBUG: Print PID of current process.

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2466]
Current behavior:

```
LOADER: message
```

Suggested behavior:

```
[123] LOADER: message
```

@codewarrior0 Should be simple to implement, but you're better at c than I am, so I thought I would give this to you.

**Comment by htgoebel** [comment]
https://docs.python.org/2/library/logging.html#logrecord-attributes:
processName 	| %(processName)s 	| Process name (if available).

Search the source and the tests-source for `format` to find where we are defining the log format.

**Comment by xoviat** [comment]
@htgoebel When I opened this, I was talking about the debug bootloaders, but we can do both.

**Comment by htgoebel** [comment]
Closed by 108706c23776f0f4e7e4c89bcb50aaba0cffb1cb
