### ISSUE TITLE
file hello.py shadowed by module/subdirectory hello

### ISSUE THREAD

**Issue by htniemann** [pyinstaller/pyinstaller#2467]
My source files are
```
            hello.py and identical hello1.py
                       import hello.do
                       hello.do.doit()
            hello\__init__.py (empty)
            hello\do.py
                        def doit():
                                    print 'hello world'
 ```

I run pyinstaller on hello1.py and the resulting program works as expected, it prints “hello world”
I run pyinstaller on hello.py and the resulting program does nothing and has return code 0.

Is the hello.py shadowed by the hello module/subdirectory?
Version is pyinstaller 3.2.1 on python 2.7.13 on Windows 7.

IIRC it used to work with pyinstaller 3.0

I was told that this setup is illegal in python (although it works perfectly as long as hello.py
is started directly, i.e. on the command line), but one of the list files in the build directory
correctly lists hello.py and hello/* so an error message should be possible to create.

**Comment by htgoebel** [comment]
I'm not convinced that it's worth spending time on this.

**Comment by htgoebel** [comment]
No other comments. Closing.
