### ISSUE TITLE
[Question] Can't add binary

### ISSUE THREAD

**Issue by vikingiwan** [pyinstaller/pyinstaller#2470]
I have these files in a directory ![files](http://i.imgur.com/swWxi91.png)
but when I use
`pyinstaller --add-binary 'ffmpeg.exe;' --add-binary 'ffprobe.exe;' --onefile --noconsole --icon=icon2.ico SongSaver.py`

It errors with `FileNotFoundError: Path or glob "D:\Dev\Python\SongSaver\'ffmpeg.exe" not found or matches no files.`

What am I doing wrong?

**Comment by htgoebel** [comment]
```
"D:\Dev\Python\SongSaver\'ffmpeg.exe" not found 
                         ^^
```
Looks like you must not single-quote the argument. Windows Cmd-line woes.

**Comment by RANUX** [comment]
Try:
```
--add-binary ffmpeg.exe;ffmpeg.exe
```
or:
```
--add-binary=ffmpeg.exe;ffmpeg.exe
```

**Comment by bw4sz** [comment]
@RANUX can you give a corresponding osx example?

I have ffmpeg

```
MacBook-Pro:moviepy ben$ which ffmpeg
/usr/local/bin/ffmpeg
MacBook-Pro:moviepy ben$ ffmpeg
ffmpeg version 3.3.4 Copyright (c) 2000-2017 the FFmpeg developers
  built with Apple LLVM version 8.1.0 (clang-802.0.42)
  configuration: --prefix=/usr/local/Cellar/ffmpeg/3.3.4 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-libmp3lame --enable-libx264 --enable-libxvid --enable-opencl --enable-videotoolbox --disable-lzma --enable-vda
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libavresample   3.  5.  0 /  3.  5.  0
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
  libpostproc    54.  5.100 / 54.  5.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

and I went to add it binary

```
pyinstaller  --windowed --onedir DeepMeerkat.spec --add-binary ffmpeg.osx
```
yields

```
pyinstaller: error: argument --add-binary: invalid add_data_or_binary value: 'ffmpeg.osx'
```
I've tried just ffmpeg, or "/usr/local/bin/ffmpeg", but can't seem to get the syntax correct.

**Comment by htgoebel** [comment]
@bw4sz Please read the manual.

**Comment by tallforasmurf** [comment]
it appears what you all are overlooking is that both `--add-binary` and `--add-data` are two-part values, with a SRC and a DEST, in both the spec file and in the command line (which just feeds the spec file). It [is documented](http://pyinstaller.readthedocs.io/en/stable/spec-files.html?highlight=add-binary#adding-files-to-the-bundle) as @htgoebel said.

**Comment by aop4** [comment]
Another thing to be aware of is that PyInstaller gives files added to one-file executables an unexpected base path. This might cause file I/O errors if your code doesn't account for it. There's a nice solution for that issue [here](https://stackoverflow.com/questions/7674790/bundling-data-files-with-pyinstaller-onefile). This would be something to explore if you're using the `--onefile` option.
Something not clearly illustrated here is that the SRC and DEST mentioned above are a little different. SRC can be a file, but DEST is a folder to put the file in for access by the executable:
`--add-data path/to/file.png:path/to`
I found it a little easier to leave the --onefile option out, check out what it was doing, fix the issues, and then use --onefile again.

**Comment by rahatzamancse** [comment]
I am also getting the same error.

**Comment by Malte0621** [comment]
have you tried adding it to . ?   Like this:  pyinstaller --add-binary ffmpeg.exe;. --add-binary ffprobe.exe;. --onefile --noconsole --icon=icon2.ico SongSaver.py 

Remove ' and add . after ;
