### ISSUE TITLE
Feature request: PySide2 support

### ISSUE THREAD

**Issue by YimingYAN** [pyinstaller/pyinstaller#2472]
[PySide2](http://wiki.qt.io/PySide2) is a python bounding that aims to provide a complete port of PySide to Qt 5.x. The development of PySide2 has gained support from The Qt Company.  

PyInstaller has hooks for PySide and PyQt5. It would be great to support PySide2 as well.

**Comment by htgoebel** [comment]
Please provide a pull-request submitting the required hook. Thanks.

**Comment by YimingYAN** [comment]
I will try to make a hook and send the pull-request when finish.

**Comment by cbenhagen** [comment]
https://github.com/pyinstaller/pyinstaller/pull/2744 ;)

**Comment by htgoebel** [comment]
Merged #2744 in 47aa4174fb182fdca1b8ac8736da688edac884f5
