### ISSUE TITLE
ImportError: No module named message

### ISSUE THREAD

**Issue by Avinapster** [pyinstaller/pyinstaller#2481]
I am running this command: `pyinstaller --name=myapp --windowed "/path/to/myapp.py" -y --hiddenimport email --clean --onedir`

My pyinstaller script creates binary in dist/myapp folder successfully but when I am trying to run that binary,
I am getting following error

```
Traceback (most recent call last):
File "/path/to/myapp.py", line 369, in 
app.run(debug=True, host=os.getenv('IP', '0.0.0.0'), port=int(os.getenv('PORT', 56789)))
File "flask/app.py", line 841, in run
File "werkzeug/serving.py", line 706, in run_simple
File "werkzeug/_reloader.py", line 263, in run_with_reloader
File "werkzeug/_reloader.py", line 144, in run
File "werkzeug/_reloader.py", line 22, in _iter_module_files
File "email/init.py", line 79, in getattr
ImportError: No module named message
Failed to execute script myapp
```

I used `--hiddenimport email` `--hiddenimport email.message` still I am getting this error.

```
PyInstaller: 3.2.1
Python: 2.7.10
```

Here is myapp.py

```
import os
from flask import *

template_dir = "/path/to/myapp/static"
app = Flask(__name__, template_folder=template_dir)
app.secret_key = "secret-key"

if __name__ == '__main__':
	app.run(debug=True, host=os.getenv('IP', '0.0.0.0'), port=int(os.getenv('PORT', 56789)))

```

**Comment by htgoebel** [comment]
This looks like some all required module is not packaged.

Please have a look at this "email/init.py" file, line 79. The Python standard library does not include such a file. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out which module PyInstaller failed to find.

**Comment by Avinapster** [comment]
Hi htgoebel,

Issue is fixed for me. Actually, message module is in email.mime folder.

So, I used  `--hiddenimport email.mime.message`.

Thanks for the help!

**Comment by AnkurThakur** [comment]
For any other User coming to the same issue, Disabling the Debug mode in Flask application was more helpful and clean way to do it as there were many such other hidden imports which were difficult to find.

See here: https://stackoverflow.com/a/48092358/3565756
