### ISSUE TITLE
[question] [bug] Binaries are not installed incorrectly

### ISSUE THREAD

**Issue by kwshoemaker2** [pyinstaller/pyinstaller#2482]
I have a .spec file where I install a binary from "wherever\\lib.dll" to "lib.dll". However, the tool creates a directory called "lib.dll" that contains the actual DLL. This isn't the behavior I would expect, and the guide doesn't say how to just install the binary itself to the same directory as the executable.

**Comment by htgoebel** [comment]
Please post the relevant part of you .spec-file.

Where do you expect this t be documented? Where have you searched for the documentation? Maybe we need to improve the docs.

**Comment by tallforasmurf** [comment]
Probably relevant: http://pythonhosted.org/PyInstaller/spec-files.html#adding-binary-files

**Comment by kwshoemaker2** [comment]
@htgoebel see @tallforasmurf's comment. That's the part that I read, but for me it would put the "libiodbc.2.dylib" into a folder called libiodbc.2.dylib. This is running on Windows.

**Comment by kwshoemaker2** [comment]
Here's the .spec file:
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['pyrand\\__main__.py'],
             pathex=['C:\\Users\\Kyle\\Desktop\\dev\\python\\pywrap'],
             binaries=[('pyrand\plugins\myrand.dll', 'myrand.dll')],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='rand',
          debug=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='rand')
```

**Comment by kwshoemaker2** [comment]
Also, I tried changing the destination for the DLL to "." for the top-level directory, but that just causes this strange error:
![error](https://cloud.githubusercontent.com/assets/9089192/23590947/ade502c4-019d-11e7-9fa0-84b38aa16446.PNG)

**Comment by htgoebel** [comment]
Maybe there are some artefacts (directories) left in the cache. Please try PyInstaller `--clean`.

**Comment by htgoebel** [comment]
No reaction for several month, assume this is solves.
