### ISSUE TITLE
multi package script error

### ISSUE THREAD

**Issue by aprudnik** [pyinstaller/pyinstaller#2486]
Hello,

I am getting error when I am trying to use merge option on my centos 7 box.
I tried running test from pyinstaller repo. After packages are build running executable i get error : *** Error in `./dist/test_multipackage1.exe': free(): invalid pointer: 0x00007f4506b8ef48 ***.
Although first executable runs ok.

I tried with release 3.2.1 and with dev version the same issue.

Debug information :

PyInstaller Bootloader 3.x
LOADER: executable is /root/alex/pyinstaller/tests/old_suite/multipackage/dist/test_multipackage1.exe
LOADER: homepath is /root/alex/pyinstaller/tests/old_suite/multipackage/dist
LOADER: _MEIPASS2 is NULL
LOADER: archivename is /root/alex/pyinstaller/tests/old_suite/multipackage/dist/test_multipackage1.exe
LOADER: Extracting binaries
LOADER: Extracting dependencies
LOADER: Splitting item into path and filename
LOADER: Checking if file exists
LOADER: File /root/alex/pyinstaller/tests/old_suite/multipackage/dist/.././_codecs_cn.so not found, assuming is onefile.
LOADER: Getting file from archive.
LOADER: archivename is /root/alex/pyinstaller/tests/old_suite/multipackage/dist/multipackage1_B.exe
*** Error in `./dist/test_multipackage1.exe': free(): invalid pointer: 0x00007f4506b8ef48 ***
======= Backtrace: =========
/lib64/libc.so.6(+0x7d023)[0x7f4506851023]
/lib64/libc.so.6(_IO_free_wbackup_area+0x3f)[0x7f450684487f]
/lib64/libc.so.6(+0x6d52c)[0x7f450684152c]
/lib64/libc.so.6(fseek+0x77)[0x7f4506847a47]
./dist/test_multipackage1.exe[0x401e54]
./dist/test_multipackage1.exe[0x402715]
./dist/test_multipackage1.exe[0x402884]
./dist/test_multipackage1.exe[0x402f25]
/lib64/libc.so.6(__libc_start_main+0xf5)[0x7f45067f5b15]
./dist/test_multipackage1.exe[0x40191e]
======= Memory map: ========
00400000-00408000 r-xp 00000000 fd:00 80414840 /root/alex/pyinstaller/tests/old_suite/multipackage/dist/test_multipackage1.exe
00608000-00609000 rw-p 00008000 fd:00 80414840 /root/alex/pyinstaller/tests/old_suite/multipackage/dist/test_multipackage1.exe
00609000-00619000 rw-p 00000000 00:00 0
02006000-0202b000 rw-p 00000000 00:00 0 [heap]
7f4500000000-7f4500021000 rw-p 00000000 00:00 0
7f4500021000-7f4504000000 ---p 00000000 00:00 0
7f45065be000-7f45065d3000 r-xp 00000000 fd:00 67109062 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f45065d3000-7f45067d2000 ---p 00015000 fd:00 67109062 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f45067d2000-7f45067d3000 r--p 00014000 fd:00 67109062 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f45067d3000-7f45067d4000 rw-p 00015000 fd:00 67109062 /usr/lib64/libgcc_s-4.8.5-20150702.so.1
7f45067d4000-7f450698a000 r-xp 00000000 fd:00 67238612 /usr/lib64/libc-2.17.so
7f450698a000-7f4506b8a000 ---p 001b6000 fd:00 67238612 /usr/lib64/libc-2.17.so
7f4506b8a000-7f4506b8e000 r--p 001b6000 fd:00 67238612 /usr/lib64/libc-2.17.so
7f4506b8e000-7f4506b90000 rw-p 001ba000 fd:00 67238612 /usr/lib64/libc-2.17.so
7f4506b90000-7f4506b95000 rw-p 00000000 00:00 0
7f4506b95000-7f4506baa000 r-xp 00000000 fd:00 67307445 /usr/lib64/libz.so.1.2.7
7f4506baa000-7f4506da9000 ---p 00015000 fd:00 67307445 /usr/lib64/libz.so.1.2.7
7f4506da9000-7f4506daa000 r--p 00014000 fd:00 67307445 /usr/lib64/libz.so.1.2.7
7f4506daa000-7f4506dab000 rw-p 00015000 fd:00 67307445 /usr/lib64/libz.so.1.2.7
7f4506dab000-7f4506dae000 r-xp 00000000 fd:00 67238618 /usr/lib64/libdl-2.17.so
7f4506dae000-7f4506fad000 ---p 00003000 fd:00 67238618 /usr/lib64/libdl-2.17.so
7f4506fad000-7f4506fae000 r--p 00002000 fd:00 67238618 /usr/lib64/libdl-2.17.so
7f4506fae000-7f4506faf000 rw-p 00003000 fd:00 67238618 /usr/lib64/libdl-2.17.so
7f4506faf000-7f4506fd0000 r-xp 00000000 fd:00 68631655 /usr/lib64/ld-2.17.so
7f45071c1000-7f45071c4000 rw-p 00000000 00:00 0
7f45071ce000-7f45071d0000 rw-p 00000000 00:00 0
7f45071d0000-7f45071d1000 r--p 00021000 fd:00 68631655 /usr/lib64/ld-2.17.so
7f45071d1000-7f45071d2000 rw-p 00022000 fd:00 68631655 /usr/lib64/ld-2.17.so
7f45071d2000-7f45071d3000 rw-p 00000000 00:00 0
7ffd7c965000-7ffd7c986000 rw-p 00000000 00:00 0 [stack]
7ffd7c9a3000-7ffd7c9a5000 r-xp 00000000 00:00 0 [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0 [vsyscall]
Aborted (core dumped)

Build log. :

39 INFO: PyInstaller: 3.3.dev0-8b491de
40 INFO: Python: 2.7.5
40 INFO: Platform: Linux-3.10.0-327.13.1.el7.x86_64-x86_64-with-centos-7.2.1511-Core
43 INFO: UPX is not available.
45 INFO: Extending PYTHONPATH with paths
['/root/alex/pyinstaller/tests/old_suite/multipackage',
'/root/alex/pyinstaller/tests/old_suite/multipackage']
45 INFO: checking Analysis
45 INFO: Building Analysis because out00-Analysis.toc is non existent
45 INFO: Initializing module dependency graph...
47 INFO: Initializing module graph hooks...
101 INFO: running Analysis out00-Analysis.toc
118 INFO: Caching module hooks...
122 INFO: Analyzing test_multipackage1.py
2244 INFO: Loading module hooks...
2246 INFO: Loading module hook "hook-encodings.py"...
3084 INFO: Looking for ctypes DLLs
3085 INFO: Analyzing run-time hooks ...
3103 INFO: Looking for dynamic libraries
3965 INFO: Looking for eggs
3966 INFO: Using Python library /lib64/libpython2.7.so.1.0
3968 INFO: Warnings written to /root/alex/pyinstaller/tests/old_suite/multipackage/build/test_multipackage1/warntest_multipackage1.txt
4066 INFO: Extending PYTHONPATH with paths
['/root/alex/pyinstaller/tests/old_suite/multipackage',
'/root/alex/pyinstaller/tests/old_suite/multipackage']
4067 INFO: checking Analysis
4067 INFO: Building Analysis because out01-Analysis.toc is non existent
4067 INFO: Initializing module dependency graph...
4069 INFO: Initializing module graph hooks...
4151 INFO: running Analysis out01-Analysis.toc
4179 INFO: Caching module hooks...
4187 INFO: Analyzing multipackage1_B.py
7341 INFO: Loading module hooks...
7343 INFO: Loading module hook "hook-encodings.py"...
8407 INFO: Looking for ctypes DLLs
8407 INFO: Analyzing run-time hooks ...
8421 INFO: Looking for dynamic libraries
11363 INFO: Looking for eggs
11363 INFO: Using Python library /lib64/libpython2.7.so.1.0
11367 INFO: Warnings written to /root/alex/pyinstaller/tests/old_suite/multipackage/build/test_multipackage1/warntest_multipackage1.txt
11539 INFO: Common prefix: /root/alex/pyinstaller/tests/old_suite/multipackage/
11542 INFO: checking PYZ
11542 INFO: Building PYZ because out00-PYZ.toc is non existent
11543 INFO: Building PYZ (ZlibArchive) /root/alex/pyinstaller/tests/old_suite/multipackage/build/test_multipackage1/out00-PYZ.pyz
11995 INFO: Building PYZ (ZlibArchive) /root/alex/pyinstaller/tests/old_suite/multipackage/build/test_multipackage1/out00-PYZ.pyz completed successfully.
12115 INFO: checking PKG
12115 INFO: Building PKG because out00-PKG.toc is non existent
12116 INFO: Building PKG (CArchive) out00-PKG.pkg
12189 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
12228 INFO: Bootloader /usr/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
12228 INFO: checking EXE
12228 INFO: Building EXE because out00-EXE.toc is non existent
12229 INFO: Building EXE from out00-EXE.toc
12229 INFO: Appending archive to ELF section in EXE /root/alex/pyinstaller/tests/old_suite/multipackage/dist/test_multipackage1.exe
12237 INFO: Building EXE from out00-EXE.toc completed successfully.
12314 INFO: checking PYZ
12315 INFO: Building PYZ because out01-PYZ.toc is non existent
12315 INFO: Building PYZ (ZlibArchive) /root/alex/pyinstaller/tests/old_suite/multipackage/build/test_multipackage1/out01-PYZ.pyz
12812 INFO: Building PYZ (ZlibArchive) /root/alex/pyinstaller/tests/old_suite/multipackage/build/test_multipackage1/out01-PYZ.pyz completed successfully.
12919 INFO: checking PKG
12919 INFO: Building PKG because out01-PKG.toc is non existent
12919 INFO: Building PKG (CArchive) out01-PKG.pkg
16598 INFO: Building PKG (CArchive) out01-PKG.pkg completed successfully.
16631 INFO: Bootloader /usr/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
16631 INFO: checking EXE
16631 INFO: Building EXE because out01-EXE.toc is non existent
16631 INFO: Building EXE from out01-EXE.toc
16632 INFO: Appending archive to ELF section in EXE /root/alex/pyinstaller/tests/old_suite/multipackage/dist/multipackage1_B.exe
16664 INFO: Building EXE from out01-EXE.toc completed successfully.

**Comment by aprudnik** [comment]
Also I don't have the issue on my ubuntu box where I have python 2.7.6

**Comment by xoviat** [comment]
multipackage is not a supported option at this time. I'm currently working on implementing the feature, but it's quite complex and will take some time to review the PR.

**Comment by aprudnik** [comment]
Thank you xoviat for fast replay. Will use single package meantime, hope to see it soon.
