### ISSUE TITLE
[Question] How to use the packaged python interpreter within executable

### ISSUE THREAD

**Issue by sarahmarshy** [pyinstaller/pyinstaller#2490]
Hello!

I am bundling my python script as a windows executable. I want to use `sys.executable` within my packaged script. Basically I want to call other Python scripts with this interpreter binary. However, this seems to return `myscript.exe`.

I'd like to avoid hard-coding this, as I will eventually make executables for other platforms. Also, I'd like for the script to maintain it's ability to be executed as normal with a user installation of Python. 

I noticed a step in the bootloader described [here](http://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#the-bootstrap-process-in-detail) is "set sys.executable".

I was digging around the source code, but I wondered if someone here might have any suggestions. 

Cheers,
Sarah

**Comment by xoviat** [comment]
Only the code frozen script can load the interpreter without major architecture changes. You can load other scripts with this:

`exec(open('my script.py'))`

**Comment by sarahmarshy** [comment]
@xoviat I'd thought about this, but it removes the possibility of passing arguments to the script :(

**Comment by tallforasmurf** [comment]
Clever! Apply the built-in `exec()` function to the text of a script as read from a file. Consider however the possible security hole. This script can do *anything* that your app is permitted to do, create or delete files, open internet connections, whatever. So you need to be sure it is a script you expect to run and has not been corrupted or modified from what you expect (e.g. by having a hash value that you obtain from some other source, and verifying the hash before calling `exec()`.

**Comment by sarahmarshy** [comment]
Very clever! Though, I think this eliminates the ability to pass arguments to the script, but I am looking into it.

**Comment by tallforasmurf** [comment]
Is there a way to pass a modified sys.argv via the globals argument to exec?

**Comment by sarahmarshy** [comment]
I just modified sys.argv before running exec, and this seems to work!
