### ISSUE TITLE
AV false positives or what?

### ISSUE THREAD

**Issue by Python360** [pyinstaller/pyinstaller#2500]
I just downloaded pyinstaller zip.Download was clean on Microsoft edge scanner when downloading.I went to virustotal and uploaded the zip.But there are 9 reports of trojan.Here is the link:
https://www.virustotal.com/en/file/6c84a62b21d80c4384c27d2dd113b79e05f1bcf4a9d2bd54427e39db77d3b402/analysis/1489406176/

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
