### ISSUE TITLE
support a standardized package data method for developers to avoid hook files

### ISSUE THREAD

**Issue by paulmueller** [pyinstaller/pyinstaller#2510]
I am a software developer. Instead of creating pull requests for hooks (or writing hooks in the first place) for all of my packages, I would like to have a standardized way to add package data in PyInstaller. I would propose a method called `_get_data_path` at the top level of the package, as it is the case for matplotlib:
https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-matplotlib.py

Does this functionality already exist (I could not find any docs on this)? Are you in principle interested? Do you have any reservations?
I could make a start with a pull request.

Cheers,
Paul

**Comment by htgoebel** [comment]
There is some code for reading package meta-data, marked with a lot TODOs, see [PyInstaller/building/toc_conversion.py](https://github.com/pyinstaller/pyinstaller/blob/v3.2.1/PyInstaller/building/toc_conversion.py).

But there currently is no functionality to call some function and there are not plans for implementing such a thing.

While the idea sounds compelling, I think the better place for defining such extensions would be the [Python Packaging Authority](https://www.pypa.io/) (PyPA). There are currently some draft PEPs on their roadmap which might be a good place to add this. Thus I suggest you talk to them.

If a PEP for such a thing gets accepted, we will implement it (and appreciate a pull-request, of course :-)
