### ISSUE TITLE
Unable to build with matplotlib (RuntimeError: maximum recursion depth exceeded)

### ISSUE THREAD

**Issue by tteekkar** [pyinstaller/pyinstaller#2513]
I'm unable to make any executable containing matplotlib. Tried to add matplotlib to hidden imports, but it didn't help either. Reading from the debug output, it seems that pyinstaller is not recognizing and therefore not importing matplotlib. Managed successfully to create executables  with other libraries such as numpy, but not with matplotlib.

Running the following:
Python 3.4.4
Pyinstaller 3.2.1
Matplotlib 2.0.0
WinPython-32bit-3.4.4.6Qt5

The code I'm compiling is the following :
`import matplotlib`
`print('hello')`

Compiled using the command:
`pyinstaller --onefile --log-level DEBUG bigcatcher.py > out.txt 2>&1`

But all I got was a RuntimeError. Full debug output can be found here:
https://gist.github.com/tteekkar/d517e4f95405f158b380519cbb893327

**Comment by xoviat** [comment]
```
git clone git://github.com/pyinstaller/pyinstaller.git
cd pyinstaller
git pull +refs/pull/2428/merge
pip install .
```

**Comment by xoviat** [comment]
Duplicate #2426.

**Comment by htgoebel** [comment]
RuntimeError: maximum recursion depth exceeded while calling a Python object

**Comment by htgoebel** [comment]
@tteekkar Next time please paste at least the error message, as this saves us a lot of time. Thanks.

**Comment by htgoebel** [comment]
@tteekkar Sorry, my fault . It's in the title already.
