### ISSUE TITLE
Windows, dir build, kivy running into OpenGL detection error

### ISSUE THREAD

**Issue by jegger** [pyinstaller/pyinstaller#2520]
**What is the problem**
On Windows I try to build an executable based on Kivy.
I am running into an issue when I try to launch the exe on a different machine than the one I have built the exe initially. (On the machine on which I have built the folder-based exe it is working fine) I have tried launching the app on different windows machines (and different hardware configurations) - no machine was able to run it.

Using the single executable with pyinstaller (I am using version based on 3cb0e94) it works fine. But the folder based one does not run. Somehow Kivy can not detect the OpenGL version properly. See this Kivy issue: https://github.com/kivy/kivy/issues/5071 and the crash-log: http://codepad.org/UBEnc80U

**How I built the folder based exe**
1. Cloned this simple kivy touchtracer app: https://bitbucket.org/rentouch/touchtracer
2. Created a virtualenv
3. Installed the following into it:  docutils pygments pypiwin32==219 kivy.deps.sdl2==0.1.17 kivy.deps.glew==0.1.9 kivy==1.9.2.dev0.20170308.ca9eb0bb pyinstaller (This new kivy version is available on --index-url https://wheels.rentouch.ch)
4.  Created a version.txt and Touchtracer.spec file with the following content: http://codepad.org/OeirKvsz and http://codepad.org/3qNdGKmq
5. venv/scripts/pyinstaller Touchtracer.spec => Creates the folder exe

As I said, this .exe works fine on the machine I have built it. But does not work on a different machine. The build is available on: https://drive.google.com/file/d/0B3txMaz1dfuwWTZYemVNQUphS2M/view?usp=sharing

What could lead to such a behavior?
I do not really know where to start debugging this issue. It is really tedious, as it involves copying the executable to a different machine after every build.

**Comment by htgoebel** [comment]
> There should be no reason to add a Tree here 

I just discovered, this si the way kivy recommends.

**Comment by jegger** [comment]
Yes exactly. Of course I used a different .spec file for the onefile build: http://codepad.org/qaOVM1LY

Yes I created the .spec files myself (at least edited them) as it is written here: https://kivy.org/docs/guide/packaging-windows.html

The curious thing is, that the build which is failing on the target machine(s), is working on the machine (environment) which I used to build the executable.

**Comment by dessant** [comment]
@jegger, this is just a random test, but you could check how it behaves without upx, `upx=True` is set in your spec files.

**Comment by jegger** [comment]
@dessant Sadly, this has no effect. It behaves exactly the same.

**Comment by jegger** [comment]
I just changed my .spec file that it does not contain the Tree in collect anymore. http://codepad.org/5ExJZGYY 
Sadly no success either.

@dessant, Could you share a .spec file which is working for you? Which version of pyinstaller, kivy, python (2 or 3, 32/64bit?) and what version of windows are you using to build the exe?

**Comment by dessant** [comment]
The rest of my spec file will be of no help here, it has custom hooks and mostly everything is collected as a hidden import because the app is cythonized before packaging. I've been using pyinstaller develop with kivy master on win10 x64, py34 32bit.

**Comment by Zen-CODE** [comment]
Please see the tail of https://github.com/kivy/kivy/issues/5071 for a full discussion.

Essentially, we discovered that removing the manifest file alongside the exe fixes it.

**Comment by htgoebel** [comment]
No reaction for several month, assume this is solves.
