### ISSUE TITLE
@htgoebel Auto-cancel pull request builds

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2523]
See here: 

https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

**Comment by htgoebel** [comment]
Oh, another one I missed. After reading the blog-entry, I think activating this for pull-requests would be got. What do you think?

**Comment by xoviat** [comment]
I think so.

**Comment by grajsor** [comment]
I am pretty surprised to read this is something that has come up now. Even
in Jenkins 1.x I think I used "silence period" of 5 minutes on any hooks or
trigger, today I use 10 minutes to the developers dismay (one might get
dispensation if it is a mission critical project aka. hot-fix branch).

Then again, one might also use the local git-proxy that wont push anything
forward, unless you have stopped committing for the past 15 minutes --
whatever floats your boat :)

Cheers, thanks to both of you for your incredible work.
