### ISSUE TITLE
Pyinstaller not packaging textract parser

### ISSUE THREAD

**Issue by Pika-Boo** [pyinstaller/pyinstaller#2528]
Pyinstaller is not able to convert the textract parse. Any other supported parser or methodlogy to convert to exe

**Comment by tallforasmurf** [comment]
Just a little teeny bit more information would be helpful... 

Do you refer to [this textract](https://github.com/deanmalmgren/textract) documented [here](http://textract.readthedocs.io/en/stable/)?

It looks like quite a normal sort of package. So what do you mean "not able to convert"? Don't answer that! Go now and read:

 https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong

https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs

and then add some information as directed there.

**Comment by Pika-Boo** [comment]
Yes, the sa,e textract. 
Let me clarify the issue, once the build is created, the package is not able to refer to its dependent files, giving the default package error.
Used pyi-archive-viewer to open the pyz file and the dependent packages, haven't been installed. 
Any way I can include the dependent packages?

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by DeastinY** [comment]
Hey, sorry for jumping in on this, but I just stumbled upon the same error (although it may just be me). 
I am using the current dev version 3.3.dev0+964547c and Python 3.5.3.
Textract works properly from the console and everything seems fine with the build.
When launching my program everything works until textract is used, then I get 

    textract.exceptions.ExtensionNotSupported: The filename extension .pdf is not yet supported by
    textract.

Textract is using different tools for pdf extraction, like PdfMiner or pdftotext. Maybe I just failed in packaging those ? But from console it works like a charm :/

**Comment by DeastinY** [comment]
Not exactly sure why the issue occurred but I was able to solve it by including the textract parser as an hidden import.

**Comment by tallforasmurf** [comment]
Excellent! @Pika-Boo does this work for you?

What was the `--hidden-import` parameter you used?  You have discovered something that was not visible to PyInstaller as a dependency. Probably the textract module that is visibly imported, does something sneaky to import something else. So this should be documented, maybe by adding it to [the list of recipes](https://github.com/pyinstaller/pyinstaller/wiki/Recipes) in the wiki.

**Comment by DeastinY** [comment]
Thanks a bunch for the pointers @tallforasmurf !
I described what I did [here](https://github.com/deanmalmgren/textract/issues/156). The hidden import was e.g. `textract.parsers.pdf_parser` for the pdf parser.
While I managed to get it to work I still don't have a good understanding of what's going on exactly. I believe the maintainer of Textract (@deanmalmgren) doesn't either.
I wanted to add documentation on the issue to the Textract wiki anyways, so maybe it's better to add a recipe here and link that ? 
The issue discussed here is solely about the hidden import, but the issue I was facing was also about the combination with Windows, so I'll have to separate them properly

**Comment by tallforasmurf** [comment]
What is happening is that PyInstaller determines what to put in the package by **static analysis** of the import statements, recursively. So you `import textract` and it analyzes that module for imports, and so on. However in Python there are ways of dynamically fiddling with the import mechanism, that are not visible to analysis of the source. Such imports are "hidden" (from PyInstaller analysis) and that's why there are multiple ways to provide that info, the simplest being `--hidden-import`. Another is the "hook" file which is automatically applied based on the imported name. [Here is a simple example](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-babel.py), the hook for babel, whatever that is.

Maybe @deanmalmgren would like to [read about hooks](http://pyinstaller.readthedocs.io/en/stable/hooks.html) and then provide a textract hook as a pull request.

**Comment by deanmalmgren** [comment]
Hey everybody! I'm happy to chime in here with some details, but @DeastinY or @Pika-Boo is probably in a better position to put together a PR for pyinstaller as I haven't used it before.

`textract` dynamically imports just about everything under [`textract.parsers`](https://github.com/deanmalmgren/textract/tree/master/textract/parsers) with some fanciness in [`textract.parsers.process`](https://github.com/deanmalmgren/textract/blob/master/textract/parsers/__init__.py#L67-L72), which looks for a file called `EXTENSION_parser.py` in the `textract.parsers` python package where `EXTENSION` is the filename extension that is being extracted. In @DeastinY's case, this happens to be a `pdf` file so it is looking for a file called `pdf_parser.py` in the `textract.parsers` package, but there are many other modules within that python package that should also be installed for textract to have its full capability.

It's also worth mentioning that the `textract.parsers` package [is explicitly installed in the setup.py](https://github.com/deanmalmgren/textract/blob/master/setup.py#L57). 

Hopefully this helps get you started!

**Comment by htgoebel** [comment]
Looks like this has been solved. If anybody wants to submit a pull-request or write a recipe for the wiki: feel free.
