### ISSUE TITLE
.app doesnt start on Mac

### ISSUE THREAD

**Issue by dominhtri1995** [pyinstaller/pyinstaller#2531]
Hi,
I'm using Pyinstaller 3.2.1. When I use -w/--noconsole/--windowed option on Mac OSx 10.12, the .app file start then shut down immediately without showing the PyQt5 Gui. However, I can start and use the executable version(with console) normally. I can't think of any possible error for this. Plz help.

Thanks

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error. Here are auite some tickets open related to PyQt5. please check these, too.

For now I assume this is a duplicate and close the ticket. If you provide more details, I may reopen it.

**Comment by tallforasmurf** [comment]
Just an added tip: you can launch the windowed app manually from the Terminal. Just tunnel down to the executable in Contents/MacOS and execute it, e.g.

    cd dist/myscript.app/Contents/MacOS
    ./myscript &

Then if there is any kind of return code or message you can see it.
