### ISSUE TITLE
Windows executable does not signal child process

### ISSUE THREAD

**Issue by RaymondKYLiu** [pyinstaller/pyinstaller#2533]
Like this issue.   <https://github.com/pyinstaller/pyinstaller/issues/448>
When a PyInstaller build Windows executable with **--one-file** is run it create a child process. When the parent process is send a SIGTERM or SIGKILL the child process is unaffected.
I try to build with --one-dir mode, everything is ok.

PyInstaller Version: 3.2.1
Python 2.7.10
Windows 7 64 bit

```
# child.py
#!/usr/bin/python
import time

if __name__ == "__main__":
    while True:
        print "Hello"
        time.sleep(1)

```

```
# parent.py
#!/usr/bin/python
import os
import sys
import time
from subprocess import Popen

if __name__ == "__main__":
    print 'Start child process'
    child_process = Popen('child.exe')
    time.sleep(5)

    print 'Kill child process'
    child_process.kill()

```

**Comment by virsystem** [comment]
I guess this help you https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing

**Comment by tzarebczan** [comment]
We are running into this same issue on the https://github.com/lbryio/lbry project - on Linux/Mac, closing the parent process kills both processes. On Windows, closing the parent process leaves the child running. This is an issue for us because our autoupgrade tool only kills the parent process expecting the child to be cleaned up automatically. 

Any updates on this problem?

**Comment by tzarebczan** [comment]
@virsystem in our case we are not using multiprocessing, do you have any other suggestions? 

 @htgoebel would it be possible for you to take a look into this? We've tried a few different debugging steps on our end and we believe its a bug in pyinstaller, specifically on Windows.

**Comment by htgoebel** [comment]
@tzarebczan Some Windows developer has to have a look at this.

**Comment by tzarebczan** [comment]
@htgoebel do you know any that you can tag here?

**Comment by Legorooj** [comment]
@tzarebczan is the problem still there?

**Comment by robertoetcheverryr** [comment]
@Legorooj 
I have just checked and the problem still exists on:
Windows 10 x64
PyInstaller 3.6
Python 3.8.2

Code modified from the initial example:
```
# parent.py
#!/usr/bin/python
import os
import sys
import time
from subprocess import Popen

if __name__ == "__main__":
    print('Start child process')
    child_process = Popen('child.exe')
    time.sleep(5)
    print('Kill child process')
    child_process.kill()
    time.sleep(25)
    sys.exit(0)

# child.py
#!/usr/bin/python
import time

if __name__ == "__main__":
    while True:
        print("Hello")
        time.sleep(10)
```

After the parent dies, the child remains.
If I can help to isolate the problem, I'd be happy to.

**Comment by Legorooj** [comment]
@robertoetcheverryr if you could try the development version, then if it persists open a new issue with all the details. I'll help look into it.

Also, python 3.8 is unsupported, so please try another version (support is enroute).
