### ISSUE TITLE
create/write to file on Mac

### ISSUE THREAD

**Issue by dominhtri1995** [pyinstaller/pyinstaller#2535]
Hi,
So pyinstaller works beautifully and create an executable file and a no-console file ( I use -w --onefile). However, the .app file can NOT write or create for example a .csv or do logging at the directory without crashing the program. The executable with console can do it without any error. I'm think about some sort of permission to create file on Mac.

I'm trying to add this to my program and the .app file will crash.
`logging.basicConfig(filename='/Users/process.log', level=logging.INFO)`

I'm on Mac OS 10.12 . Lastest version of pyinstaller. I can't provide an error log because it only happens on the no-console .app file.

**Comment by tallforasmurf** [comment]
There's something bogus here. If I attempt the above statement in interactive mode even, I get a permission error. `/Users` is not anybody-writeable, and for good reason. Did you leave out part of the file path?

**Comment by dominhtri1995** [comment]
I found the problem. The .app file at runtime will make the path look like path-to-directory/Users/process.log.  That's why it crashes.

**Comment by tallforasmurf** [comment]
> The .app file at runtime will make the path look like path-to-directory/Users/process.log. 

Sorry, that's not making any sense to me. Are you saying this is something that PyInstaller does? Or the logging code?
