### ISSUE TITLE
Need the final script to deploy my Python program on Linux Ubuntu 16.04 64-bit and Mac iOS

### ISSUE THREAD

**Issue by ebonat** [pyinstaller/pyinstaller#2539]
Hi,

I got script for Windows as:

pyinstaller --onedir --name=app_name --windowed "C:\python_file.py"

And it works!

What's the script for Linux Ubuntu 16.04 and Mac iOS?

**Comment by tallforasmurf** [comment]
Read this: http://pyinstaller.readthedocs.io/en/stable/usage.html#supporting-multiple-operating-systems

> If you need to distribute your application for more than one OS, for example both Windows and Mac OS X, you must install PyInstaller on each platform and bundle your app separately on each.
