### ISSUE TITLE
Numpy hook misses MKL libs in OS X

### ISSUE THREAD

**Issue by adam-iris** [pyinstaller/pyinstaller#2544]
Related to #1881, and this particular issue is mentioned in #2111 -- the hook to include the MKL libs doesn't look for .dylib files, so these libraries are missing on Mac builds. I just modified the regex used to find the libraries and this fixed the issue for me.

**Comment by andyfaff** [comment]
I just rebased on the develop branch but I'm still getting problems with bundling a program (that uses numpy) into a single app. (conda, python=3.6.1, tip of pyinstaller develop branch)

The error I get when opening the app from the terminal is:

    Intel MKL FATAL ERROR: Cannot load libmkl_avx.dylib or libmkl_mc.dylib.

When I look into `build\<progname>\out00-EXE.toc` those dylibs are missing. I can see:

      ('libmkl_intel_lp64.dylib',
      '/Users/anz/miniconda3/envs/dev3/lib/libmkl_intel_lp64.dylib',
      'BINARY'),
      ('libmkl_core.dylib',
      '/Users/anz/miniconda3/envs/dev3/lib/libmkl_core.dylib',
      'BINARY'),
      ('libmkl_intel_thread.dylib',
       '/Users/anz/miniconda3/envs/dev3/lib/libmkl_intel_thread.dylib',
       'BINARY'),
