### ISSUE TITLE
Need the ability to put multiple programs in one folder

### ISSUE THREAD

**Issue by Felix-neko** [pyinstaller/pyinstaller#2547]
I'm developing a Python package and have about 10 demo Python scripts that show its capabilities.

I want to distribute the demo scripts with PyInstaller: create 10 exe files and put them in one folder with all libraries they depend on.

Can it be somehow supported?

**Comment by tallforasmurf** [comment]
You are describing the [multipackage feature](http://pyinstaller.readthedocs.io/en/stable/spec-files.html?highlight=multiprogram#multipackage-bundles) which is currently broken. See #1527 and feel free to help investigate and fix.

**Comment by htgoebel** [comment]
Why not simply copy all dist/* directories into the same destination directory. This costs a bit of space, but solves the problem.

**Comment by Felix-neko** [comment]
Well, just now we are using it as a temporary workaround, but it look a bit ugly...

**Comment by xoviat** [comment]
github.com/xoviat/subzero may be of help.

**Comment by xoviat** [comment]
Also, did you miss this? I understand that reviewing the MERGE PR will take some time, I think that there should at least be a plan to get it done.

> @htgoebel What do you think about breaking out the bootloader changes into a separate PR?

**Comment by htgoebel** [comment]
Stale since long, closing.
