### ISSUE TITLE
Incredibly slow opening of an exe file

### ISSUE THREAD

**Issue by ombschervister** [pyinstaller/pyinstaller#2550]
On one of the user's computers, app build by pyinstaller opens incredibly slowly.

Here's what cprofile produces:

| ncalls  | tottime | percall | cumtime | percall | filename:lineno(function) |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| 1 | 0.000 | 0.000 | 3638.830 | 3638.830 | run.py:20(run_for_profile) |
| 2611/61 | 0.024 | 0.000 | 3634.331 | 59.579 | <frozen importlib._bootstrap>:2234(_find_and_load) |
| 2611/61 | 0.021 | 0.000 | 3634.328 | 59.579 | <frozen importlib._bootstrap>:2207(_find_and_load_unlocked) |
| 5640 | 0.161 | 0.000 | 3619.606 | 0.642 | J:\rex_secured_build\WinPython-32bit-3.4.4.2Qt5\python-3.4.4\lib\site-packages\pyinstaller-3.2.1+5b84a8d-py3.4.egg\PyInstaller\loader\pyimod02_archive.py:342(extract) |
| 5640 | 0.048 | 0.000 | 3614.505 | 0.641 | J:\rex_secured_build\WinPython-32bit-3.4.4.2Qt5\python-3.4.4\lib\site-packages\pyinstaller-3.2.1+5b84a8d-py3.4.egg\PyInstaller\loader\pyimod02_archive.py:89(__enter__) |
| 5834 | 3614.438 | 0.620 | 3614.439 | 0.620 | {built-in method open} |

The "open" method works for more than 3000 seconds!
And, if you create a debug build (spec debug = True in the spec file),
Then everything works fine.

On my computer and the normal build works fine:
5893 0.404 0.000 0.405 0.000 {built-in method open}

Because of what it can happen and how it can be circumvented?

**Comment by htgoebel** [comment]
Please restore the text. pictures woe!

**Comment by ombschervister** [comment]
Can there be an antivirus problem?

**Comment by vinayak618** [comment]
Hi @ombschervister 
Facing the same issue while running the pyinstaller exe on windows.
Did you disable the windows default anti virus or any third party anti virus software?

**Comment by ombschervister** [comment]
No, I noticed that it was blocked only if the console was hidden.  I left the show_console = True flag

**Comment by vinayak618** [comment]
@ombschervister.
Sorry I didn't get you.
Did you add the flag show_console in spec file or gave it in command line while creating exe?

Thank you for the response

**Comment by ombschervister** [comment]
@vinayak618 
In spec file.
exe = EXE(pyz,
          ...
          **console=True** )
