### ISSUE TITLE
Pyinstaller with c++ shared libraries

### ISSUE THREAD

**Issue by epetsalis** [pyinstaller/pyinstaller#2551]
I am trying to use pyinstaller on  ubuntu machine to package a python app that uses, among other things, the graph-tool package. Graph-tool is a package that heavily depends on shared libraries (it provides an interface to accessing c++-written optimized code). 
It seems that pyinstaller is not able to pick up those dependancies, so when I try to run the final app, it complains that it can not load the library.
Is there a work around, for this type of issues? 

Thanks

**Comment by htgoebel** [comment]
Please read the fine manual.
