### ISSUE TITLE
Problem with the Python stdlib executing external programs

### ISSUE THREAD

**Issue by hillu** [pyinstaller/pyinstaller#2552]
Hi,

I have been trying to debug some symptoms with the Linux client of [GRR](https://github.com/google/grr) which is built using PyInstaller. The binary from the RPM (which is apparently built on CentOS5) emits error messages on startup when run on SuSE 11:
```
sh: symbol lookup error: /usr/lib64/grr/grr_3.1.0.2_amd64/libreadline.so.5: undefined symbol: PC
```
I have traced the cause of this particular problem to the Python standard library where a shell with `uname -p` is called to determine the `processor` part of the `platform.uname` tuple (using `os.popen`, therefore using the shell). I found a cure for the symptom -- I just patched `platform.py` for my build.

The deeper issue I see here is that `LD_LIBRARY_PATH`, a PyInstaller implementation detail, leaks when spawning external programs.

**Comment by xoviat** [comment]
> I have traced the cause of this particular problem to the Python standard library where a shell with uname -p is called to determine the processor part of the platform.uname tuple (using os.popen, therefore using the shell). I found a cure for the symptom -- I just patched platform.py for my build.

Would you mind submitting a PR with this patch?

**Comment by xoviat** [comment]
> The deeper issue I see here is that LD_LIBRARY_PATH, a PyInstaller implementation detail, leaks when spawning external programs.

The variables need to be set because we use a parent-child model. However, we could patch subbprocess.

**Comment by hillu** [comment]
My strictly works-for-me patch was this:
``` diff
--- platform.py.orig    2017-04-11 00:09:07.522089816 +0200
+++ platform.py 2017-04-11 00:09:44.497152134 +0200
@@ -1252,7 +1252,7 @@
                 processor = 'VAX'
     if not processor:
         # Get processor information from the uname system command
-        processor = _syscmd_uname('-p','')
+        processor = machine
 
     #If any unknowns still exist, replace them with ''s, which are more portable
     if system == 'unknown':
```
I have to admit that I'm not familiar with the PyInstaller codebase at all: what would one have to do to patch bits of `platform.py` or `subprocess.py` or `os.popen()` (which is used in `platform.py` to call _uname_)?

**Comment by xoviat** [comment]
> My strictly works-for-me patch was this:

Oh, so you patched python system files. Well, it's not that much work to create a runtime hook from that.

**Comment by htgoebel** [comment]
@hillu You did not state which version of PyInstaller you are using. Your problem should be fixed in release 3.2.1, see 639fcec992d753db20.

**Comment by htgoebel** [comment]
This is the documented behaviour, see https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#ld-library-path-libpath-considerations

**Comment by hillu** [comment]
@htgoebel The version of PyInstaller I used was 3.2.1.

**Comment by htgoebel** [comment]
@hillu You should have mentioned that - this is why we have instructions even in the issue template. So you wasted us volunteers time.

**Comment by hillu** [comment]
@htgoebel Thank you for the documentation link. To clarify, I do not have any problem with unsetting `LD_LIBRARY_PATH` (or other variables) in my own application. The problem is that code in `platform.py` from the Python stdlib executes programs without doing so. What options do I have to modify `platform.py` as it is bundled with my application? (I'd rather not modify my system-wide Python installation for this.)

**Comment by htgoebel** [comment]
IC. Hmm, maybe we really should add a run-time hook for subprocess - but to be consistent we would need to patch all other functions spawning process, too.

So for your case, I'd try to implement some work-around like this:

- in the .spec-file generate and include a small module holding the result of whatever you need
- in your program, when running frozen, don't use platform but the data of the moduel generated in the first step.

**Comment by xoviat** [comment]
> IC. Hmm, maybe we really should add a run-time hook for subprocess - but to be consistent we would need to patch all other functions spawning process, too.

Another alternative is we could remove `LD_LIBRARY_PATH_ORIG` from os.env.
