### ISSUE TITLE
from mpl_toolkits.basemap import Basemap

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#2554]
I am trying to import **Basemap** from **mpl_toolkits.basemap** showing error No module named 'mpl_toolkits.basemap' in Python3
but the same is working in Python2
Can anyone help me 
thanks in advance

**Comment by giumas** [comment]
I have recently moved to Python 3.6 from 2.7, and I didn't get issues from `basemap`. 

Can you provide more information? https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#when-submitting-a-bug

**Comment by jilesingh** [comment]
sudo su
[sudo] password for jile: 
Cannot execute /bin/ksh: No such file or directory
# can anyone please solve this issue I couldn't get to root directory
