### ISSUE TITLE
yowsup Cli Command not working  

### ISSUE THREAD

**Issue by manojrao** [pyinstaller/pyinstaller#2557]
Hello Sir/mam
i  am working on (recivenig whatsup message).
my issue is i get profile pic and get all information of group but i can not this task without cli coomand but this command is not working properly.
i got error this as:-ImportError: No module named pyreadline

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.
