### ISSUE TITLE
PyQT4 script is packed ok, but is run looking like a Tkinter GUI

### ISSUE THREAD

**Issue by ullix** [pyinstaller/pyinstaller#2561]
The package is built without error message. When the package is run on the packaging computer (Ubuntu Mate 16.04.02), it has the proper PyQt4 look. But when the package is run on a different computer (virtual machine with default Ubuntu Mate 16.04.02 install) it looks like a Tkinter GUI, and  GTK errors are being reported. 
> Gtk-Message: Failed to load module "gail"
Gtk-Message: Failed to load module "atk-bridge"
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "topmenu-gtk-module"
(geiger:4677): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine",
(geiger:4677): Gtk-WARNING **: Unable to locate theme engine in module_path: "murrine"

last line is repeated ~20 times
GtK is not called in my scripts. PyQt4 is imported in the script as (redundant, but just for trying):

> from PyQt4 import QtGui, QtCore
import PyQt4

matplotlibrc specifies :
> backend      : Qt4Agg
backend.qt4 : PyQt4  

and the *.spec file loads PyQt4 also as hidden-import
> hiddenimports=['PyQt4', 'Tkinter', 'FileDialog' ],

When Tkinter and FileDialog are not loaded as hiddenimports the program does not run at all. But no sign of PyQt4 look.

**Comment by tallforasmurf** [comment]
Seems bizarre. This program must include statements like `from PyQt4.QtWidgets import QApplication` and so forth. These execute without error?

Note that [Py]Qt tries to look like its host environment. Possibly what you are calling a Tkinter look is simply the style of the window manager on this system. Do host system windows look different?

Note also that you can set the desired style from the list of styles [supported by QStyle](http://doc.qt.io/qt-5/qstyle.html#details) when you create the QApplication object. I notice that one of my apps has this,

~~~~
args = []
if sys.platform == 'linux' :
    # avoid a GTK bug in Ubuntu Unity
    args = ['','-style','Cleanlooks']
the_app = QApplication( args )
~~~~

so apparently at some point I used this as a way to avoid using GTK at all. Don't remember any details.

**Comment by ullix** [comment]
No errors **when running**, neither on the building machine nor on the one running the package. I use Ubuntu Mate 16.04.02 on both (to avoid Unity), and Mate is also based on GTK. My theme is 'Ambiant-MATE'. So I used your code snippet with both my theme and your 'Cleanlooks'. 

Results were identical for both and my original. Same error messages from the package, and ugly look as before.

**Comment by ullix** [comment]
Stupid mistake: on my platform `sys.platform == 'linux2'` , so your snippet code never got executed :-/, but it got me on the track. 

I now use `app = QtGui.QApplication(sys.argv)` and therefore can start on the command line with `myapp -style newstyle` , with newstyle e.g. Cleanlooks.

Doing `for a in QtGui.QStyleFactory.keys(): print a` tells me the following styles are available on my building computer: Breeze, Windows, Motif, CDE, Plastique, GTK+, Cleanlooks. On the computer where the package is run, it is the same, **except** that Breeze is missing, which I unknowingly seem to have used. But Breeze is the nicest style, and GTK the ugly one (windows one step better than gtk).

Now the question is : why is Breeze not packed and how can I tell PyInstaller to collect Breeze stuff?

**Comment by tallforasmurf** [comment]
> on my platform `sys.platform == 'linux2'`

Oh, good tip. I've changed my code to `sys.platform.startswith( 'linux' )`.

> Now the question is : why is Breeze not packed and how can I tell PyInstaller to collect Breeze stuff?

Too lazy to fire up a linux VM but running the following code on Mac OS:

~~~~
from PyQt5.QtWidgets import QApplication, QStyleFactory
app = QApplication([])
for a in QStyleFactory.keys(): print( a )
~~~~

Produces

~~~~
Windows
Fusion
Macintosh
~~~~

and going into the Qt 5.4 distribution folder and doing a find, I see,

~~~~
[08:54 /Developer/qt] find . -name '*fusi*'
./5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/5.4.1/QtWidgets/private/qfusionstyle_p.h
./5.4/clang_64/lib/QtWidgets.framework/Versions/5/Headers/5.4.1/QtWidgets/private/qfusionstyle_p_p.h
~~~~

With that as a clue, I would

1. bundle my app as --onedir so I could see the contents
2. look inside to see if any of the style headers were included at all, e.g. Plastique.

If some were bundled but Breeze not, that would be one problem. If none were bundled, that would be another.

**Comment by ullix** [comment]
I searched my whole bundling computer for any occurrence of `*cleanlooks*, *windows*, *motif*, *plastique*` - not a single hit, neither in file-path nor in file-name. Yet the styles are present and I can switch between them. 

On the other hand, there are plenty of Breeze files. But only the icons make it into the bundle, of which I use none. All other styles are available when the bundle is run on the test computer (a VM in the bundling computer), but Breeze style is not. 

There is some significant bloat in the bundle. The bundle is over 800MB (!), of which some 600MB are icons and themes - none of it is used - plus some further ~100MB of GTK*, Tk*, wx.*, wayland, cairo, ...  files. All can be deleted, and the bundle still works. Various fonts are also in the bundle - except the one I actually use.

So, using the --onedir, as you suggested, allows me to delete all this bloat. But how do I get the stuff in I want and is not present?

There is one more thing which looks like a conceptual bug in PyInstaller: the file matplotlibrc is absolutely needed. Without it, starting the bundle attempts to load defaults and crashes right away. My rc file contains only these two lines:
> backend      : Qt4Agg
backend.qt4 : PyQt4

the rest is comments. I add this to the bundle by `datas=[('matplotlibrc', '.')],` which puts it into the program directory of the bundle. As a consequence you can't start the bundle from a different directory, because then the *rc is not found; I have no control over how and when matplotlibrc is called.  And copying elsewhere is possible, but contradicts the purpose of having all in one bundle.

Is there any way to tell the bundle "look here first" for config files such as *rc?

**Comment by tallforasmurf** [comment]
> I searched my whole bundling computer for any occurrence of *cleanlooks*, *windows*, *motif*, *plastique* - not a single hit, neither in file-path nor in file-name. Yet the styles are present and I can switch between them.

OK, so my guess at how the Qt styles are implemented was off the mark, a/o finding the fusion header in the Darwin distro was a red herring. Sorry. Qt styles implementation in general, and why you don't get Breeze, is an open question.

>  ~100MB of GTK*, Tk*, wx.*, 

I *speculate* that the GTK is being pulled in by Qt as part of its platform support, and would expect it to be required on the target machine. (Any linux gurus want to comment?)

You mention matplotlib, maybe it is responsible for Tk and wx being included? Looking at the [matplotlib.backends hook](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-matplotlib.backends.py) suggests it might be getting every possible display platform??

Also take a look at the PyQt4 hooks in the [hooks dir](https://github.com/pyinstaller/pyinstaller/tree/develop/PyInstaller/hooks), esp. the hook for [PyQtGui](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-PyQt4.QtGui.py).

> I add this to the bundle by datas=[('matplotlibrc', '.')], which puts it into the program directory of the bundle. As a consequence you can't start the bundle from a different directory, because then the *rc is not found

I am not sure "starting the bundle from a different directory" is supported. In the --onedir case, there is a presumption that a lot of things will be in the same folder as the executable, and --onefile merely recreates --onedir in temp space. You can make an alias of the executable and the user can drag that to a different folder, e.g. the desktop, and still launch it.

**Comment by ullix** [comment]
I am slowly beginning to understand what PyInstaller can and cannot do :-/. I installed KDE's Okular, and style Breeze was there; I uninstalled Okular, and Breeze was gone.  So, while Okular was bringing its style, PyInstaller does not pack it. Nor any other style; you only get to use what is on the system. OK; but one has to know.

Becomes a bit laboroius, as some things need to be adapted to work at least acceptably with the various styles potentially on the user's computer.

For the future I hope PyInstaller will do a deeper inspection of what to include and what not, like not loading Tkinter, when PyQt4 is loaded explicitly, and other. For now I have settled to just guessing what things might be called, and adding 
> excludes=['wx', 'gtk+', 'Tkinter', 'gtk', 'gdk', 'gtk2', 'gtk3', 'cairo', 'wayland', 'xinerama', 'share', 'icons', 'atk', 'pango', 'pil', 'PIL'],

to get rid of most things (successfully to a degree).

There is still a share folder with well over 500MB(!) of icons and else, of which none(!) is used in my program. I delete this folder (hence I need the --onedir option to be able to see this folder.)

I end up with a single zip file of some 45MB. Could be smaller, but I can live with that.

The result is here in version 0.9.03 as "script" and "bundle", resp. : https://sourceforge.net/projects/geigerlog/files/

Thanks for helping.

**Comment by tallforasmurf** [comment]
So Qt gets its style sets from the local system using some means within the C++ code that is invisible to Python/PyInstaller. So the only hope for bundling styles is for somebody to dive into the Qt sources and figure WTF that mechanism is. Then there would be a chance of adding hook code to pick up the relevant files and bundle them to the proper target folder. But that would be a big job for a small gain.

Re Tkinter, [quite a few hooks exclude it](https://github.com/pyinstaller/pyinstaller/search?utf8=%E2%9C%93&q=modname_tkinter&type=) and I see no obvious reason why the same code shouldn't be added to the hooks for PyQt4/5.QtGui. A tested pull request to that effect would be welcome.

Why your bundle picks up all the gt* stuff is beyond me; it/they must be linked from some binaries that PyInstaller needs to include. Why it is getting PIL (Python Imaging Library) is also a puzzle. Qt wouldn't know about that, and PyQt shouldn't either.

Since you are into this so deep already, would you be willing to make a  "hello world" PyQt4 program and see how big a onedir bundle it makes? Just display a main window with a label as its central widget.

**Comment by ullix** [comment]
matplotlib is the file-hog! Looks like there are several issue with it, not just one.

This is the stripped down version of my program:

    #!/usr/bin/python
    # -*- coding: utf-8 -*-
    """
    gtest - testing PyInstaller
    """
    import sys
    from PyQt4 import QtGui, QtCore

    #import matplotlib.backends.backend_qt4agg
    #import matplotlib.pyplot as plt
    #import matplotlib.dates as mpld
    #import matplotlib.colors as mplc

    class ggeiger(QtGui.QMainWindow):

        def __init__(self):
            super(ggeiger, self).__init__()

            exitAction = QtGui.QAction('Exit', self)
            exitAction.triggered.connect(self.close)
            # file menu
            fileMenu = self.menuBar().addMenu('&File')
            fileMenu.addAction(exitAction)
            # NotePad
            notePad = QtGui.QTextEdit()
            notePad.append("Hello ")
            # centralwidget
            self.setCentralWidget(notePad)
            # show
            self.show()

    def main():
        app = QtGui.QApplication(sys.argv)
        ex = ggeiger()
        sys.exit(app.exec_())

    if __name__ == '__main__':
        main()

With none of the matplotlib imports active, the total after Pyinstaller is 60MB (unzipped), of which some 75% of the files have "Qt" in their names. I don't recognize the other files. After zipping the total is 22MB, so this is the basis, and not too bad.

But once any of the matplotlib imports is active - I thought the matplotlib.colors is the most innocent, but it does not matter - PyInstaller goes berserk! Note that I am just doing the import of mpl; nothing of mpl is actually used! 

PyInstaller imports every mpl backend and its brother it can get hold of, although import PyQt4 is clearly set in the code. It also creates the famous "share" directory of 588.8MB, having 586.8MB of "themes" and "icons"! But not a single bit of the complete "share" folder is in use anywhere. Since Pyinstaller doesn't even pack any style, why is it so keen to package each and every theme and icon, which make sense only with certain styles?

My /etc/matplotlibrc file on this computer has only comments, except for this line:

> backend      : TkAgg

Again, Tkinter is not asked for in my program. But this makes PyInstaller demand Tkinter, and since it is not present on this computer, the bundle crashes.

Hence it is important to provide a local matplotlibrc file with this content:

> backend      : Qt4Agg
backend.qt4 : PyQt4 

To make PyInstller use this local file, I need to add to the *spec file under Analysis:

> datas=[('matplotlibrc', '.')],

Now my total bundle is 146.4MB (as opposed to 60MB). With my further addtion of my wild-guessed exclude statments - fortunatly, PyInstaller does not complain about nonsense at this stage - 

> excludes=['wx', 'gtk+', 'Tkinter', 'gtk', 'gdk', 'gtk2', 'gtk3', 'cairo', 'wayland', 'xinerama', 'share', 'icons', 'atk', 'pango', 'pil', 'PIL'],

I am now getting - after deletion of the 588.8MB 'share' folder - a total of 107.6MB for still the same functionality as with the original 60MB. Oh dear.

I wish you all the best getting a  hook into this !

**Comment by tallforasmurf** [comment]
Paging @leycec -- you did some interesting work on [hook-matplotlib.backends](https://github.com/pyinstaller/pyinstaller/commit/f592547309723614c25bcad84f783de74bcf03f1) that might possibly be relevant?

**Comment by bjones1** [comment]
I suspect this is the nature of the beast: Pyinstaller can't (as of now) determine what backends your application needs, so it packages everything. The best approach I can think of is to add excludes, as you've done.

**Comment by ullix** [comment]
PyInstaller does not need to make a decision on what it needs, because it is being told, what it needs. When I have "import GUIxyz" in my program, what are the chances I need any other as well? (Not sure it is even possible to have 2 GUIs running simultaneously).

But an even much, much bigger fish to hook is the famous "share" directory.

Take a file with absolutely nothing in it except this single line 

> import matplotlib

and PyInstall it as --onedir. It gets you a folder of 734.0MB, in which a "share" folder of 563.6MB exists, of which 99.6% is "themes" + "icons". As far as I can see this is all of that stuff existing on this computer (The very existence of such masses is a different issue, but I have not intentionally installed any themes; this is all auto-included stuff, and deleting it deletes stuff that I want)

I have no idea why this is imported via matplotlib. In my work with it, and from googling, I don't see mpl using such themes and icons. 

And it is not due to packaging Tkinter:  a single line "import Tkinter" file gives only 18.9MB.

Such a mega folder also prevents the use of the --onefile option, because then you can't delete the "share" folder, and are stuck with 100s of useless Megabytes.

Me thinks this is worth a big hook. No?

**Comment by bjones1** [comment]
A hook that excludes unnecessary matplotlib data would be great! Please provide one!

**Comment by tallforasmurf** [comment]
OK so all mention of PyQt above can be disregarded. This is an issue with bundling matplotlib. Which I have no experience with so I'm bowing out of the discussion. But do take a look at that hook-matplotlib code I linked earlier. It should be logging info about included backends. Does it?

**Comment by ullix** [comment]
Just for completeness: a single line "`import PyQt4`" file packs to 17.5MB, similar to the Tkinter case.

Some more review: after bundling of "import matplotlib"  I get in the build directory file `out00-Analysis.toc` (similar in `out00-COLLECT.toc`) , which contains:

      ('libncursesw.so.5', '/lib/x86_64-linux-gnu/libncursesw.so.5', 'BINARY'),
      ('libpython2.7.so.1.0', '/usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0', 'BINARY')],
     [],
    --> line #2304
     [],
     [('share/icons/oxygen/16x16/status/mail-sent.png',
       '/usr/share/icons/oxygen/16x16/status/mail-sent.png',      'DATA'),
      ('share/icons/breeze/actions/16/view-process-own.svg',
       '/usr/share/icons/breeze/actions/16/view-process-own.svg',     'DATA'),
     ... -->line 255 000

Up to line 2304 there are various PYMODULE, EXTENSION and BINARY files - looks kind of meaningful - the next 250 000 (!) lines are all share/icon/* and share/themes/* related, and it all is categorized as DATA. Where does PyInstaller get this info from?

I went through the hooks on this site: https://github.com/pyinstaller/pyinstaller/tree/develop/PyInstaller/hooks . Four hooks relate to matplotlib (hook-matplotlib* and hook-mpl*); none have any (direct) bearing on the monster "share" folder. 

Then I ran searches for "share", "theme", and "icon" in all matplotlib files. Nothing. 

When searching all "dist-packages" only file  `IconTheme.py` in xdg popped up, where all three keywords are found. But attempts to achieve anything by excluding this from bundling via `excludes=['xdg', 'IconTheme'] ` failed (but not sure that it was actually excluded).

So, that's the end for my pay grade. My hope now rests on others ;-)

**Comment by tallforasmurf** [comment]
Well, because of the code [starting here](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-matplotlib.backends.py#L72), if you do the one-line matplotlib test again with `--log-level=INFO` the output should have some lines with `matplotlib` in them. Which might tell if the code in that hook is generating all that stuff, or something else.

**Comment by ullix** [comment]
...it starts and ends with `hiddenimports=` and I printed those, they are:

> [u'matplotlib.backends.backend_gtk', u'matplotlib.backends.backend_gtkagg', u'matplotlib.backends.backend_gtkcairo', u'matplotlib.backends.backend_qt4agg', u'matplotlib.backends.backend_qt5agg', u'matplotlib.backends.backend_tkagg', u'matplotlib.backends.backend_wx', u'matplotlib.backends.backend_wxagg', u'matplotlib.backends.backend_gtk3cairo', u'matplotlib.backends.backend_gtk3agg', u'matplotlib.backends.backend_agg', u'matplotlib.backends.backend_cairo', u'matplotlib.backends.backend_gdk', u'matplotlib.backends.backend_pdf', u'matplotlib.backends.backend_pgf', u'matplotlib.backends.backend_ps', u'matplotlib.backends.backend_svg', u'matplotlib.backends.backend_template']

and those are the ones I tried to exclude, but that failed. 

Actually I used this from the output of line 54 of that hook:

>excludes=['xdg', 'GTK', 'GTKAgg', 'GTKCairo', 'MacOSX', 'Qt5Agg', 'TkAgg', 'WX', 'WXAgg', 'CocoaAgg', 'GTK3Cairo', 'GTK3Agg', 'WebAgg', 'nbAgg', 'agg', 'cairo', 'emf', 'gdk', 'pdf', 'pgf', 'ps', 'svg', 'template'],

But since the backends Tkinter and PyQt4 are benign, I don't expect much from the others. And at any rate, should I not be able to find something when search all text in the files?

**Comment by ullix** [comment]
Not sure what you mean with ` --log-level=INFO `. It tried `pyinstaller --log-level=INFO mpltest.spec`, but that gives exact same output (see attached) as if I had run it w/o the log-level option, except for the number at the beginning of the line. Anyway, the result is attached; is that helpful? I don't see anything.

Any other option(s)?

The *.spec file is: [mpltest.spec.zip](https://github.com/pyinstaller/pyinstaller/files/974000/mpltest.spec.zip)

[mpl.log3.zip](https://github.com/pyinstaller/pyinstaller/files/973996/mpl.log3.zip)

**Comment by tallforasmurf** [comment]
OK, I'm confused (not unexpectedly...), clearly the log statements in the hook are working and it reports,

~~~~
8544 INFO:   Matplotlib backend "GTK": added
8718 INFO:   Matplotlib backend "GTKAgg": added
8892 INFO:   Matplotlib backend "GTKCairo": added
9031 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name _macosx
9195 INFO:   Matplotlib backend "Qt4Agg": added
9361 INFO:   Matplotlib backend "Qt5Agg": added
9504 INFO:   Matplotlib backend "TkAgg": added
9712 INFO:   Matplotlib backend "WX": added
9915 INFO:   Matplotlib backend "WXAgg": added
10118 INFO:   Matplotlib backend "GTK3Cairo": added
10319 INFO:   Matplotlib backend "GTK3Agg": added
10405 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/usr/lib/python2.7/dist-packages/matplotlib/backends/backend_webagg.py", line 30, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
10494 INFO:   Matplotlib backend "nbAgg": ignored
    No module named tornado.ioloop
10641 INFO:   Matplotlib backend "agg": added
10788 INFO:   Matplotlib backend "cairo": added
10871 INFO:   Matplotlib backend "emf": ignored
    No module named backend_emf
11044 INFO:   Matplotlib backend "gdk": added
11184 INFO:   Matplotlib backend "pdf": added
11343 INFO:   Matplotlib backend "pgf": added
11485 INFO:   Matplotlib backend "ps": added
11636 INFO:   Matplotlib backend "svg": added
11775 INFO:   Matplotlib backend "template": added
~~~~

Are these not exactly the excess stuff you don't want, and are so inflating the output bundle?

**Comment by ullix** [comment]
Good thing is you are not lonesome, when you feel confused ...

But remember, the original post was about the Look&Feel of the bundle vs the original. But this was due to "styles" not being present on the target computer, and the mistaken belief that PyInstaller would bundle the style also. It does not. And so the bundle depends on the target computer's offerings. The same would apply when just the original scripts were run on the target (which then of course needed the proper Python environment). 

So, once you know it, it is ok, but it requires extra work, because the various styles are not completely compatible, and you need to test at least the style you have access to, and you need to make adjustments to your code to accommodate some of the nasty differences.

The second issue was that the size of the bundle was completely out of proportion, approaching 1 GB for a comparably simple program. And this had two reasons: one was some 100MB due to the inclusion of every GUI and their brother (GTK*, Tk*, wx.*, wayland, cairo, ...) plus all the matching backends to matplotlib.

I can see why PyInstaller does this when my whole program consists of only `import matplotlib`. But I had an `import PyQt4` also in my program, which I think clearly stated my intentions ;-). PyInstaller is lacking here in not taking a note that all the other GUI stuff is NOT needed, and excludes it itself.

Fortunately, that stuff I got mostly - but not fully - rid-off by wild-guessing what modules to exclude with this line in the spec file:
> excludes=['wx', 'gtk+', 'Tkinter', 'gtk', 'gdk', 'gtk2', 'gtk3', 'cairo', 'wayland', 'xinerama', 'share', 'icons', 'atk', 'pango', 'pil', 'PIL'],

I don't even know what spelling is correct; it would be helpful if PyInstaller wasn't fully quiet but told me like "not recognizing module xyz". 

The other reason for the size explosion is the infamous "share" folder of ~600MB, which is 100% unnecessary! More than 99% of it is "themes" and "icons", and I have still no idea why this is included. I delete it and my program works fine, but it prevents a --onefile bundle.

It comes in when matplotlib is imported, though matplotlib does not want it (mpl needs some stuff in the mpl-data folder of ~3MB, ok ).  

In comparison, doing single line programs of import `Tkinter`, or `PyQt4` gives you bundles of ~18MB, `gtk` gives you 60MB (huh?), and of course no "share" folder is present.

What stealthy command pulls in all those unwanted themes and icons ?

**Comment by BoboTiG** [comment]
Closing as PyQt4 support has been removed since #5118. Please open a specific issue if you encounter other problems.
