### ISSUE TITLE
How to not generate executable bundles on macOS

### ISSUE THREAD

**Issue by aaron-elkins** [pyinstaller/pyinstaller#2563]
I have a python script that use some third party modules (some of them are not  pure python modules) on macOS, let's say my script is `main.py`. Now I want PyInstaller to generate a folder in which I can have a Python interpreter and my `main.py`, and some dependence modules (both built-in and third party) used by my `main.py`.

Is this possible with PyInstaller on macOS?

I know how to generate executable bundles with PyInstaller on macOS.

Any help?

**Comment by tallforasmurf** [comment]
What would you need different from the output of --onedir?

As an aside, wouldn't this be more appropriate for the mailing list than as an issue?

**Comment by aaron-elkins** [comment]
@tallforasmurf thanks, --onedir works fine, this issue should close.
