### ISSUE TITLE
Fatal Error! Failed to execute script -- (only shows up on a prd version and not debug)

### ISSUE THREAD

**Issue by sversage** [pyinstaller/pyinstaller#2567]
I have an .exe that will run the application from end to end - however at the end of the process after the app has finished querying a database the pop up window Fatal Error! .... will show up and I need to click OK to go onto the next action in the app. 

This only shows up when I have the EXE args passed as (even if I switch just console to True it won't appear):
debug=False,
console=False,

Otherwise the app will run (w/ the console open) and the Fatal Error will not be displayed. 

I also receive no warnings during the build -- only INFO logging statements, so I can't see anything up front that would provide insight into the error. 

Any thoughts on the cause of the Fatal Error?

**Comment by htgoebel** [comment]
Possible Duplicate of #2562?

**Comment by htgoebel** [comment]
Is this still an issue? If this still is an issue
- Please try the latest release and the latest development version.
- try with "debug=True"
- try one of the tools listed at <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly>. e.e dependencywalker.

**Comment by htgoebel** [comment]
No update since 3 month, Closeing
