### ISSUE TITLE
compiling python script that uses python pptx error 

### ISSUE THREAD

**Issue by thebeancounter** [pyinstaller/pyinstaller#2574]
Hi! 
I am using a windows 7 machine, updated with .net, c++ and c++ for python installed.
I am using pyinstaller to compile a python script that uses python pptx module to build a pptx file. 
The script is callerd master2.py and i compile it with the command 
`pyinstaller --onefile --noupx master.py`
It compiles with no errors
When i run I am getting that error:
> pptx.exc.packagenotfounderror: package not found at ....\default.pptx
When compiling and running it on a Linux machine, it runs smoothly, seems that the issue is the default pptx template missing. 

When i am running the script with python on the same machine it run smoothly so i assume that the machine has all the files and installation that are needed to the run and dependency tree

Apparently it happens in different close modules, note [github issue](https://github.com/python-openxml/python-docx/issues/289)
I found [here](https://pythonhosted.org/PyInstaller/spec-files.html#adding-data-files) how to add a file to the .exe file.
I got stuck looking where to add it to... when the pptx module runs it's looking for the file in './templates/default.pptx'
When adding the file to the .exe, where do i need to add it to? or is there any other solution?

Thanks!

**Comment by htgoebel** [comment]
> When adding the file to the .exe, where do i need to add it to? or is there any other solution?

You need to add it in the .spec file, like the manual section you found describes.

**Comment by thebeancounter** [comment]
@htgoebel  could you please be more clear about it? what path should i give it in the .spec file? i don't know where the exe would look for it... 
thanks

**Comment by htgoebel** [comment]
Huh? You wrote:
> when the pptx module runs it's looking for the file in './templates/default.pptx'

So `templates` should the path to add. Like this:
```
a = Analysis(...
     datas= [ ('templates/default.pptx', 'templates' ) ],
     ...
     )
```

**Comment by fescate** [comment]
I used this specfile to succefully works with docx library
For use you have to run 

> pyinstaller myspecfile.spec

```
# myspecfile.spec
# -*- mode: python -*-

block_cipher = None

a = Analysis(['docx-example.py'],
             pathex=[],
             binaries=[],
             datas=[('.\\env\\Lib\\site-packages\\docx\\templates\\default.docx', '.\\docx\\templates\\')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='docx-example',
          debug=False,
          strip=False,
          upx=True,
          console=True )
```

**Comment by aatwork** [comment]
I do not get an error when I use pyinstaller but the generated .exe does not do anything and does not complain about a problem either.

I use python-pptx installed via PIP (0.6.5) on a Windows 64-bit PC

Does this really work for anyone?

If so, would you please post your spec file and the pyinstaller command line that generated a working .exe with pptx functionality actually working?

Thank you!

**Comment by thebeancounter** [comment]
Happened to me. Was a missing dll issue. Try to install .net framework

**Comment by aatwork** [comment]
Thank you for the feedback.

I have the .NET Frameworks 4.5.1 installed.

I can create other executables with PyInstaller just fine, so I would be surprised to learn that the .NET framework is causing this issue that is specific to the pptx module.

**Comment by thebeancounter** [comment]
I found a way to debug it, i added to the python code print statements in
many stages of the run, and watched those while running in the cmd to
monitor where it crashes.

One point the compiled python script using python pptx crashed for me, is
when i tried to create a pptx file from the default template, try to open
an existing pptx file and add to it. this did the trick for me.

and try printing stuff to debug when it crashes and give us more info about
the issue

**Comment by aatwork** [comment]
Nevermind. The problem was in front of the screen (aka myself). I messed up my code and pptx generation is working now without any changes of either pyinstaller or python-pptx

**Comment by blukhand** [comment]
this answer solve this issue in my env.
(https://github.com/python-openxml/python-docx/issues/289)
import the data in spec file 
----------------------------------------------------------------------------
import sys
from os import path
site_packages = next(p for p in sys.path if 'site-packages' in p)


a = Analysis([''],
             pathex=[''],
             binaries=[],
             datas=[(path.join(site_packages,"docx","templates"), "docx/templates")],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)

**Comment by htgoebel** [comment]
@blukhand We'd appreciate is you could provide a hook for this package. Please use `collect_data_files()`, as you can seen in other hooks. Thanks.

**Comment by thenonspec** [comment]
@fescate , thank you so math it's working for me :)
