### ISSUE TITLE
backward compatibility - packaging .exe on modern OS, execute on old OS

### ISSUE THREAD

**Issue by jossef** [pyinstaller/pyinstaller#2575]
Thanks for this awesome project.

I would like to suggest a **new build flag** `--backward-compatibility` - will affect the compiled assembly to be backward compatible for old operating systems

**For instance**, it would be awesome to compile on `Windows 10 x64` and to be able to execute on old Windows machines such as `Windows XP x86, no service pack, 2001 release` without errors.

### Windows 8 x86 -> Windows XP x86 SP0
![image](https://cloud.githubusercontent.com/assets/1287098/25389910/897219da-29da-11e7-80cf-bdef6948fb5d.png)

### Windows 10 x64 -> Windows XP x86 SP0

![x64 issues](https://cloud.githubusercontent.com/assets/1287098/25380050/97be5b20-29b7-11e7-9221-d66311204aad.png)

----

FYI I had to do some hackish troubleshooting in order to package a valid exe for old operating systems such as using Windows XP as a "build machine"; installing old release of pyinstaller (`2.1` - only this version workes on XP SP0)

**Comment by tallforasmurf** [comment]
PyInstaller has a general principle of "build it where it runs" as documented in

https://pythonhosted.org/PyInstaller/usage.html#supporting-multiple-operating-systems

Maybe others would disagree but to me the idea of trying to build for target that is different from the host just opens multiple cans of worms. As you can see by scanning this issues list there is more than enough difficulty just trying to bundle every possible package in the *same* environment.

**Comment by htgoebel** [comment]
As tallforasmurf already explained, we have enough trouble keeping PyInstaller working on the same environment. So we will not implement such a beast. Additionally Win XP is end-of-life since three years now, so there are few reasons for us for supporting it.

**Comment by andreped** [comment]
@htgoebel @tallforasmurf Out of curiousity, as I do not own a Win8 machine myself, do you believe an executable built on Win10 might work well "out of the box" on Win8 (Win XP is out of the question)? From the discussion above it might be tempting to say **no**, or, but perhaps you might have had some experience with that specifically?

Nonetheless, I might be able to get in touch with someone who owns such a historical machine. I could report my findings here, if it would be of interest. However, the project I am working in is quite complex, so it is probably not the best way of testing this.

But at least I have tested the forward compatibility on macOS and it is working brilliantly, which it should according to the docs :]

**Comment by bwoodsend** [comment]
I still run Windows 8 (easily my favorite Windows) and I've only found one issue because of it. 
- Python 3.9.0 dropped support for Windows 8. So to be backwards compatible you must build using Python 3.8 or lower. 

For Windows 7 or Vista:
- You need to roll back another Python version to 3.7 (see https://bugs.python.org/issue32592)
- And `multiprocessing` doesn't work - we never did work out why (and likely never will). Other than that, I haven't noticed anything it can't run.

In a rather ironic way, Windows is actually the best OS for backwards compatibility, not because their SDK is the most stable, but because not even modern Windows 10s provide much usable SDK to depend on...

**Comment by bwoodsend** [comment]
I forgot to mention: If you've got Linux, install [Vagrant](https://www.vagrantup.com/) and have a good 40GB of free disk space then there are [plenty of ancient Windows virtual machines](https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=windows+xp) you can test on. That was, until very recently, how we compiled the Windows and macOS bootloaders.
