### ISSUE TITLE
PyQt5 searching for accessible dir on Mac

### ISSUE THREAD

**Issue by thiagofmam** [pyinstaller/pyinstaller#2577]
Hi,
When I try to execute the .app on Mac and get this error:

QFactoryLoader::QFactoryLoader() checking directory path "/Users/thiagomeneses/PycharmProjects/interact-ii/main.app/Contents/MacOS/accessible" ...
Could not find QtWebEngineProcess
Abort trap: 6

**Comment by xoviat** [comment]
Does this work with #2519 applied?

**Comment by xoviat** [comment]
See https://github.com/pyinstaller/pyinstaller/wiki/how-to-apply-pull-requests

**Comment by thiagofmam** [comment]
I got this error:
 
git pull +refs/pull/2519/merge
fatal: '+refs/pull/2519/merge' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights

**Comment by xoviat** [comment]
How about this?

```
git pull origin +refs/pull/2519/merge
```

**Comment by thiagofmam** [comment]
Perfect.

Now I got other error.

This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "/Users/thiagomeneses/Qt5.8.1/plugins/platforms".

Available platform plugins are: cocoa (from /Users/thiagomeneses/Qt5.8.1/plugins/platforms), minimal (from /Users/thiagomeneses/Qt5.8.1/plugins/platforms), offscreen (from /Users/thiagomeneses/Qt5.8.1/plugins/platforms), cocoa, minimal, offscreen.

Reinstalling the application may fix this problem.

**Comment by xoviat** [comment]
Googling the problem revealed [this on stackoverflow](http://stackoverflow.com/questions/25188153/this-application-failed-to-start-because-it-could-not-find-or-load-the-qt-platfo).

As a side note, we may consider adding a dependency on [osxrelocator](https://pypi.python.org/pypi/osxrelocator/1.0.1). Perhaps you can help on this matter if you have time?

**Comment by thiagofmam** [comment]
Yes. I can verify.

Thank you very much.

**Comment by bjones1** [comment]
I'm closing this, since #3233 should fix it -- see the [instructions](https://github.com/pyinstaller/pyinstaller/pull/3233#issuecomment-362094587) there.
