### ISSUE TITLE
Packaged exe file fails with ImportErrors or File not found

### ISSUE THREAD

**Issue by sarakuma** [pyinstaller/pyinstaller#2579]
Team, I am using Python 3.5 32 bit version in Windows 7 64 bit machine. My pyinstaller version is 3.2.1. My application uses ibm_db, pandas, openpyxl modules (found with latest and stable versions). Although the build completes successfully (using pyinstaller), the issue pops up while I am trying to run the exe file. The app fails in the module that imports ibm_db. Please find attached 'pyinstaller_debug_output_Apr27' text file for the failure messages. I have tried the below as mentioned in the 'how to report bugs' wiki page

1. ran the exe in command window
2. tried --onedir and --onefile options. Both didn't resolve my issue
3. tried --noupx option. Didn't resolve my issue
4. tried --debug option (directed the output to pyinstaller_debug_output_Apr27.txt)
5. Used 'dependency walker' (attached the PNG screenshot) but couldn't able to figure the errors
6. not sure how to use pyi-archive_viewer as I was not sure of missing module name. 
7. Similarly couldn't able to figure with warn messages as I was not sure of missing module name (also attached the warn text file)
8. Couldn't able to find build/logdict*.log folder
9. Tried develop version but it too yielded the same failure messages. 

Can you please help me on resolving the above issue. Any directions/guidance will save a lot of time from my end. Many thanks. Please let me know if you need any other details

[warnBIS_reports_1_UI.txt](https://github.com/pyinstaller/pyinstaller/files/962176/warnBIS_reports_1_UI.txt)

![pyinstaller_depends_apr27](https://cloud.githubusercontent.com/assets/28106400/25492616/92e1f022-2b41-11e7-974e-e9020721a8cd.png)

[pyinstaller_debug_output_Apr27.txt](https://github.com/pyinstaller/pyinstaller/files/962100/pyinstaller_debug_output_Apr27.txt)

**Comment by sarakuma** [comment]
All, I also have tried using the pyviewer. Was able to locate both ibm_db and imp.py (modules that were listed in the failure messages). Seems like a catch-77 situation

**Comment by sarakuma** [comment]
[depends_profiling_apr28.txt](https://github.com/pyinstaller/pyinstaller/files/964275/depends_profiling_apr28.txt)

please find attached the dependency profiling output

**Comment by htgoebel** [comment]
This issue is one year old now, I'm closing this now. This till an issue when using the current development version, please reopen and provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.
