### ISSUE TITLE
ImportError: No module named garden.graph

### ISSUE THREAD

**Issue by AllARTSoftworks** [pyinstaller/pyinstaller#2581]
I have a problem creating an .exe file with PyInstaller from my Kivy App.

I use Garden Graph to display some plots in my app.

I develop under Linux but I have to deploy my app for Windows.

I did install all needed dependencies under Win and I can execute my app with no problems, indeed.

When I try to compile it in order to create an executable file it succeeds but when I launch my .exe I get this error:

```
ImportError: No module named garden.graph
Failed to execute script myapp
```

I tried --onefile, --onefolder, tried adding module with hiddenimports, added module path... with no luck.

Any ideas?

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by htgoebel** [comment]
No reaction for several month, assume this is solves.
