### ISSUE TITLE
lib not found: tc85.dll tcl85.dll when i use pyInstaller to package a  wxpython app

### ISSUE THREAD

**Issue by soulsoul** [pyinstaller/pyinstaller#2582]
hello, the error show next: 
env:    OS: win7 64     
          Python: 2.7.13
          PyInstaller: 3.2.1(laseted version also has the problem)

288 INFO: PyInstaller: 3.2.1
296 INFO: Python: 2.7.13
300 INFO: Platform: Windows-7-6.1.7601-SP1
306 INFO: wrote D:\PyWorkspaces\mypython\autoMetaTrader\UIManager.spec
325 INFO: UPX is not available.
336 INFO: Extending PYTHONPATH with paths
['D:\\PyWorkspaces\\mypython', 'D:\\PyWorkspaces\\mypython\\autoMetaTrader']
341 INFO: checking Analysis
344 INFO: Building Analysis because out00-Analysis.toc is non existent
345 INFO: Initializing module dependency graph...
355 INFO: Initializing module graph hooks...
645 INFO: running Analysis out00-Analysis.toc
652 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by d:\python27\python.exe
977 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_
1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
986 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_
1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
993 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_
1fc8b3b9a1e18e3b_9.0.30729.4940_none_acd19a1fe1da248a.manifest
1000 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt
_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
1382 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.
30729.6161_none ...
1388 INFO: Found manifest C:\Windows\WinSxS\Manifests\amd64_microsoft.vc90.crt_1
fc8b3b9a1e18e3b_9.0.30729.6161_none_08e61857a83bc251.manifest
1395 INFO: Searching for file msvcr90.dll
1398 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3
b_9.0.30729.6161_none_08e61857a83bc251\msvcr90.dll
1401 INFO: Searching for file msvcp90.dll
1404 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3
b_9.0.30729.6161_none_08e61857a83bc251\msvcp90.dll
1408 INFO: Searching for file msvcm90.dll
1411 INFO: Found file C:\Windows\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3
b_9.0.30729.6161_none_08e61857a83bc251\msvcm90.dll
1838 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt
_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
1844 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt
_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
1848 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt
_1fc8b3b9a1e18e3b_9.0.30729.4940_none_acd19a1fe1da248a.manifest
1852 INFO: Found C:\Windows\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt
12726 INFO: Loading module hook "hook-PIL.py"...
12727 INFO: Excluding import 'FixTk'
12730 INFO: Excluding import 'Tkinter'
12733 INFO: Import to be excluded not found: 'PyQt5'
12733 INFO: Import to be excluded not found: 'PySide'
12734 INFO: Import to be excluded not found: 'PyQt4'
12736 INFO: Loading module hook "hook-httplib.py"...
12737 INFO: Loading module hook "hook-_tkinter.py"...
15197 WARNING: lib not found: tcl85.dll dependency of d:\python27\DLLs\_tkinter.
pyd
17917 WARNING: lib not found: tk85.dll dependency of d:\python27\DLLs\_tkinter.p
yd
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "d:\python27\lib\lib-tk\Tkinter.py", line 38, in <module>
    import FixTk
  File "d:\python27\lib\lib-tk\FixTk.py", line 68, in <module>
    import _tkinter
ImportError: DLL load failed: 设备未就绪。
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: DLL load failed: 设备未就绪。
18348 ERROR: Tcl/Tk improperly installed on this system.
18349 INFO: Loading module hook "hook-PIL.Image.py"...
19443 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
19444 INFO: Excluding import 'FixTk'
19447 INFO: Excluding import 'Tkinter'
19448 INFO: Loading module hook "hook-encodings.py"...
20533 INFO: Looking for ctypes DLLs
20543 INFO: Analyzing run-time hooks ...
20552 INFO: Including run-time hook 'pyi_rth__tkinter.py'
20559 INFO: Looking for dynamic libraries
22269 INFO: Searching for assembly x86_Microsoft.VC90.DebugCRT_1fc8b3b9a1e18e3b_
9.0.21022.8_none ...
22269 WARNING: Assembly not found
22269 ERROR: Assembly x86_Microsoft.VC90.DebugCRT_1fc8b3b9a1e18e3b_9.0.21022.8_n
one not found
24078 WARNING: lib not found: tcl85.dll dependency of d:\python27\lib\site-packa
ges\PIL\_imagingtk.pyd
25109 WARNING: lib not found: tk85.dll dependency of d:\python27\lib\site-packag
es\PIL\_imagingtk.pyd
27210 WARNING: lib not found: tcl85.dll dependency of d:\python27\DLLs\_tkinter.
pyd
31553 INFO: Warnings written to D:\PyWorkspaces\mypython\autoMetaTrader\build\UI
Manager\warnUIManager.txt
31789 INFO: checking PYZ
31792 INFO: Building PYZ because out00-PYZ.toc is non existent
31792 INFO: Building PYZ (ZlibArchive) D:\PyWorkspaces\mypython\autoMetaTrader\b
uild\UIManager\out00-PYZ.pyz
34779 INFO: Building PYZ (ZlibArchive) D:\PyWorkspaces\mypython\autoMetaTrader\b
uild\UIManager\out00-PYZ.pyz completed successfully.
34855 INFO: checking PKG
34855 INFO: Building PKG because out00-PKG.toc is non existent
34857 INFO: Building PKG (CArchive) out00-PKG.pkg
34973 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30
729, 6161)
46207 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
46220 INFO: Bootloader d:\python27\lib\site-packages\PyInstaller\bootloader\Wind
ows-64bit\run.exe
46220 INFO: checking EXE
46220 INFO: Building EXE because out00-EXE.toc is non existent
46221 INFO: Building EXE from out00-EXE.toc
46221 INFO: Appending archive to EXE D:\PyWorkspaces\mypython\autoMetaTrader\dis
t\UIManager.exe
46239 INFO: Building EXE from out00-EXE.toc completed successfully.

the EXE file runs , then show the error next ：

Traceback (most recent call last):
File "site-packages\PyInstaller\loader\rthooks\pyi_rth__tkinter.py", line 28,  in <module>
IOError: Tcl data directory "C:\Users\hadoop\AppData\Local\Temp\_MEI62~1\tcl" not found.
Failed to execute script pyi_rth__tkinter

what‘s wrong with this, can somebody help me ?  is the cause of  TCL/TK ? but,
that is embeded in python2.7 packages, all right ? 
many thanks.

**Comment by soulsoul** [comment]
when i reinstall the python 2.7, it can run successfully.

**Comment by Derano** [comment]
Seems that reinstall also works for my program too.Thanks a lot.
