### ISSUE TITLE
LD_LIBRARY_PATH modified by pyinstaller causes forked process to crash

### ISSUE THREAD

**Issue by dyadav7** [pyinstaller/pyinstaller#2583]
When i fork a process by python script the process find the LD_LIBRARY_PATH as /usr/X11R6/lib:/usr/lib:/lib.
When i execute the pyinstaller version of the python script - the forked process find the LD_LIBRARY_PATH set to  /tmp/_MEIv4cmly:/usr/X11R6/lib:/usr/lib:/lib. 

This causes the cp command in the forked process to fail with this error message:
/bin/cp: /lib64/libc.so.6: version `GLIBC_2.8' not found (required by /tmp/_MEIv4cmly/libselinux.so.1)

**Comment by htgoebel** [comment]
This is documented behaviour, see https://pyinstaller.readthedocs.io/en/stable/runtime-information.html?highlight=ld_library_path#ld-library-path-libpath-considerations and#2552.

**Comment by dyadav7** [comment]
Thanks, i have used the _ORIG environment variable and it works fine.
