### ISSUE TITLE
Asocciation of file type to created exe 

### ISSUE THREAD

**Issue by tibor-vavra** [pyinstaller/pyinstaller#2600]
Hi PyInstaller team,

Thank you for your hard work on this project.

I´m working on project for 3d printers and I can´t find way how to associate some file type to exe created by pyinstaller from python3.5 code. Its complex app created with PyQt4, 3d model viewer with drag&drop and many other features.

I think problem is in windows style of starting program, when I manualy put some file(with absolute/relative path) as argv to my exe file its working but from debug logs when I try to associate some file type and just double click on this file in his path windows take only exe file and run this exe file from place where associated file is and give him file as argument but this exe file dont have dlls and rest of dist folder...

I have no idea what to do with that. 

Thanks for any idea.

**Comment by xoviat** [comment]
This is not a pyinstaller issue. You will need to follow these steps using the winreg module (or my YARW package on pypi, which should be simpler):

Extensions are associated in HKEY_CLASSES_ROOT key.

Follow these steps to create a your own association:

- Open HKEY_CLASSES_ROOT and create a key for extension (if it doesn't exist)
- Open that key and write into DefaultValue name of your "handler" - somthing like MyApp_ext
- Close current key and create another key inside HKEY_CLASSES_ROOT with the name of your handler (MyApp_ext)
- Open that key and write into DefaultValue description of this extension.
- Create a key DefaultIcon inside the handler key.
- Open that key and write into DefaultValue full path to the file containing an icon.
- Close the current key and create \shell\Open\Command keys inside the handler key
- Open that key and write into DefaultValue full path to your application including parameter.
- If you face troubles creating the file extension association, open a regedit and take a look at the structure inside HKEY_CLASSES_ROOT key.

**Comment by xoviat** [comment]
Actually what would be better is if you would publish a pypi package that would do this for an arbitrary executable and extension, so that the next person who needs to do this only has to call a single function.

**Comment by htgoebel** [comment]
This is not a pyinstaller issue.
