### ISSUE TITLE
error no 2: no such file or directory

### ISSUE THREAD

**Issue by panosss** [pyinstaller/pyinstaller#2608]
I 've made an exe with Pyinstaller.
But when I try to run it, I get an error: error no 2: no such file or directory: 'betws.ui'
This is the name of my form ( 'betws.ui'), so I should also include it in my .spec file?
I tried this, after 'binaries=[],' I added:
`datas= [('betws.ui','gui')],`

But I get the same error when I try to run it.
So, how can I include my form?

My form is in the same folder with the .py file.
The .py file loads the ui ('betws.ui') with this code:

`class MyApp(QtGui.QMainWindow, QtGui.QWidget):`
`   def __init__(self):`
`       QtGui.QMainWindow.__init__(self)`
`      self.ui = uic.loadUi('betws.ui', self)`

EDIT: I solved it [this way](https://github.com/pyinstaller/pyinstaller/issues/1826).

**Comment by htgoebel** [comment]
Please have a look at https://pyinstaller.rtfd.org/en/latest/runtime-information.html, which describe the correct way to access data-files at run-time. Alternatively you can use `pkg_resources.resource_filename()` (and related). In your case, you are putting the file into an sub-directory, so it should be `gui/betws.ui` anyway.

**Comment by panosss** [comment]
The link you posted and the link I posted, describe the same thing.
Thanks anyway!
