### ISSUE TITLE
GLIBC version issue

### ISSUE THREAD

**Issue by akbhat** [pyinstaller/pyinstaller#2611]
Froze script on CentOS6.6 using a pretty old glibc (2.12) to ensure compatibility with all linux systems. Ran it on a Ubuntu system and got the following error message: 
ImportError: /lib64/libc.so.6: version `GLIBC_2.7' not found (required by /tmp/_MEINUlbGd/libxml2.so.2)

Just want to make sure I am interpreting this correctly. glibc2.7 is needed on the Ubuntu server because libxml2 package which is included in the binary is built with it despite the fact that the frozen binary was built on a system with glibc=2.12?  

Possible solutions are:
Rebuild libxml2 on CentOS to use a older version of glibc? If I build libxml2 from source on my CentOS system, will it automatically link with the system glibc version which is 2.12?
Ensure every server the binary is executed on has glibc>=2.7?

$ ldd ./dist/jcollect 
	linux-vdso.so.1 =>  (0x00007fffc09ff000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00000037f0200000)
	libz.so.1 => /lib64/libz.so.1 (0x00000037f1a00000)
	libc.so.6 => /lib64/libc.so.6 (0x00000037f0600000)
	/lib64/ld-linux-x86-64.so.2 (0x00000037efe00000)

**Comment by htgoebel** [comment]
> Rebuild libxml2 on CentOS to use a older version of glibc?

I assume this is the solution.

But this is not an PyInstaller issue, but an issue related to either CentOS or libxml2. So please go and ask there.
