### ISSUE TITLE
How to generate an executable on Linux for Windows?

### ISSUE THREAD

**Issue by Drakota** [pyinstaller/pyinstaller#2613]
I'm trying to generate an executable from Linux for Windows.

pyinstaller --onefile --windowed montecarlo.py
I run this command and get a single executable that works on Linux just fine, I can open it and use my program, but if I try on Windows, it's just a simple file. On Linux it's a executable (application/x-executable), but on Windows it's a Type of file: File Why?

**Comment by xoviat** [comment]
Come back when you've completed CS50.

**Comment by Drakota** [comment]
Why this arrogant response? The file created on Linux is executable, but if I copy it to Windows it's just a File changing the file extension to .exe doesn't work.

**Comment by xoviat** [comment]
Well, let me just copy and paste what wikipedia says:

```
Binary compatible operating systems are OSes that aim to implement binary compatibility with another OS, or another variant of the same brand. This means that they are ABI-compatible (for application binary interface). As the job of an OS is to run programs, the instruction set architectures running the OSes have to be the same or compatible. Otherwise, programs can be employed within a CPU emulator or a faster dynamic translation mechanism to make them compatible.

For example, the Linux kernel is not compatible with Windows. This does not mean that Linux can't be binary compatible with Windows applications. Additional software, Wine, is available that does that to some degree. The ReactOS OS development effort, seeks to create an open source, free software OS that is binary compatible with Microsoft's Windows NT family of OSes using Wine for application compatibility and reimplementing the Windows kernel for additional compatibility such as for drivers whereas Linux would use Linux drivers not Windows drivers. FreeBSD and other members of the BSD family have binary compatibility with the Linux kernel in usermode by translating Linux system calls into BSD ones. This enables the application and libraries code that run on Linux-based OSes to be run on BSD as well.

Note that a binary compatible OS is different from running an alternative OS through virtualization or emulation, which is done to run software within the alternative OS in the case when the host OS isn't compatible. Sometimes virtualization is provided with the host OS (or such software can be obtained), which effectively makes the host OS compatible with programs. For example, Windows XP Mode for Windows 7 allows users to run a 64-bit version of Windows 7 and enable old software to still work in a 32-bit virtual machine running Windows XP; VMware Workstation/VMware Fusion, Parallels Workstation, and Windows Virtual PC allow other OSes to be run on Windows, Linux, and OS X.

For another example, Mac OS X on the PowerPC had the ability to run Mac OS 9 and earlier application software through Classic—but this did not make OS X a binary compatible OS with Mac OS 9. Instead, the Classic environment was actually running Mac OS 9.1 in a virtual machine, running as a normal process inside of OS X.[1][2]

```

**Comment by xoviat** [comment]
Or I could copy from the PyInstaller manual:

>PyInstaller is tested against Windows, Mac OS X, and Linux. However, it is not a cross-compiler: to make a Windows app you run PyInstaller in Windows; to make a Linux app you run it in Linux, etc. PyInstaller has been used successfully with AIX, Solaris, and FreeBSD, but is not tested against them.

**Comment by xoviat** [comment]
Also, please do close this issue so as not to waste other's time.

**Comment by virtuald** [comment]
@xoviat that was a bit much. Simply copy/pasting the piece from the pyinstaller manual would have been sufficient. We were all new to this once.

**Comment by xoviat** [comment]
I'm sorry.

**Comment by Drakota** [comment]
Alright, a simple pyinstaller is not cross-platform would have done the trick for me, I looked at [this stackoverflow question](http://stackoverflow.com/questions/2950971/cross-compiling-a-python-script-on-linux-into-a-windows-executable) wondered why it was not working, sorry for this.

**Comment by xoviat** [comment]
> Alright, a simple pyinstaller is not cross-platform 

But that's not accurate. It is cross-platform. It isn't a cross-compiler.

**Comment by virtuald** [comment]
@Drakota according to the comments in that answer it appears the ability to cross-compile was removed in 1.5, which was many releases ago. However, the secondary answer mentioning wine is correct -- you can usually create working Windows executables if you run pyinstaller under wine.

And as @xoviat mentioned, pyinstaller is cross-platform -- the compilation program works on Linux, OSX, and Windows. However, the resulting executables are platform specific.

**Comment by Drakota** [comment]
@virtuald Thanks for clearing this up. I'll figure the rest on my own, I'll use Wine.

**Comment by virtuald** [comment]
I've found that using pyinstaller + wine under docker can work well in many circumstances. https://github.com/cdrx/docker-pyinstaller is one such example of this -- then you don't need to spend time setting up wine or pyinstaller yourself, since it's already in the docker image.

**Comment by oz123** [comment]
@virtuald this is awesome! This should actually be in the official docs.

**Comment by htgoebel** [comment]
@oz123 Feel free to submit a pull-request. Search the existing docs for "wine" to find the correct place. (AFAIR it's in the FAQ, which is in the wiki anyway.)

**Comment by dwcaraway** [comment]
:tada: @virtuald excellent use of pyinstaller docker image worked for building our Windows 10 executable with python 3.5. under Centos

**Comment by theremedy** [comment]
@virtuald more decent answer compared to savage [heckoverflow](https://i.redd.it/2k1ut81gpcl01.png) answers (ifyouknowwhatimean) :roll_eyes:  
Thank you for your suggestion. I've been looking for something that lets you create standalone executables for python in windows using even when using linux as dev environment  (like Golang)

**Comment by Shivam23Thaman** [comment]
> I've found that using pyinstaller + wine under docker can work well in many circumstances. https://github.com/cdrx/docker-pyinstaller is one such example of this -- then you don't need to spend time setting up wine or pyinstaller yourself, since it's already in the docker image.

how to run it. can anybody tell me?

**Comment by Shivam23Thaman** [comment]
> I've found that using pyinstaller + wine under docker can work well in many circumstances. https://github.com/cdrx/docker-pyinstaller is one such example of this -- then you don't need to spend time setting up wine or pyinstaller yourself, since it's already in the docker image.

do we have to put our source code  folder in /user/src. can anybody explain me how to run it step by step . I am using ubuntu 18.04 and python3.6.6 and pyinstaller 3.4 .

**Comment by virtuald** [comment]
@Shivam23Thaman if you're using https://github.com/cdrx/docker-pyinstaller then read the README, it's very easy to understand. If you find it isn't easy to understand, then file an issue on that repository.

**Comment by mrbig033** [comment]
> Come back when you've completed CS50.

Maybe you should work with a less beginner friendly language such as assembly...

**Comment by NoName57** [comment]
> 
> 
> I'm sorry.



> 
> 
> Come back when you've completed CS50.

Necromancing this to call you a dickhead. That is all.

**Comment by kingmak** [comment]
> Come back when you've completed CS50.

What a dumbass.

**Comment by shahriar0247** [comment]
> I'm sorry.

Dude, everyone is a beginner at some point. He is tryna learn and thats a good thing. For people like you we get demotivaed. There was a time when you didnt know the meaning of kernal. And same for me and same for bill gates, elon musk, and the world's great hacker kevin mitnick. And you are being a waste of time. We can discurss good stuff here.

**Comment by shahriar0247** [comment]
> I'm trying to generate an executable from Linux for Windows.
> 
> pyinstaller --onefile --windowed montecarlo.py
> I run this command and get a single executable that works on Linux just fine, I can open it and use my program, but if I try on Windows, it's just a simple file. On Linux it's a executable (application/x-executable), but on Windows it's a Type of file: File Why?

Hey so, there is only way. You need a to create a windows vm inside linux and then make linux executable. And same for linux. Go to windows and wsl and make it for Linux. Creating for mac and andorid might be hard, but not impossible. And I dont really think andorid will support it (but technically it should).

**Comment by shahriar0247** [comment]
> I've found that using pyinstaller + wine under docker can work well in many circumstances. https://github.com/cdrx/docker-pyinstaller is one such example of this -- then you don't need to spend time setting up wine or pyinstaller yourself, since it's already in the docker image.

Oh yes wine, perfect win vm in linux

**Comment by uriencedric** [comment]
> Come back when you've completed CS50.

You're a dick. That's was uncessary.

**Comment by uriencedric** [comment]
> > I'm sorry.
> 
> Dude, everyone is a beginner at some point. He is tryna learn and thats a good thing. For people like you we get demotivaed. There was a time when you didnt know the meaning of kernal. And same for me and same for bill gates, elon musk, and the world's great hacker kevin mitnick. And you are being a waste of time. We can discurss good stuff here.

This is exactly why I hated myself when I started and made mistakes, because some jackass would comment like that and destroy your morale.
I used that to become a better engineer and help the less experienced engineers. 
Ain't nothing like a dumb question.

**Comment by mrbig033** [comment]
This issue is from 2017 and the asshole deleted their account a long time ago. What's even the point anymore? :P

**Comment by szindel** [comment]
> Come back when you've completed CS50.

Shame on you sir! Perfectly valid question. I don't care if Ghost reads this, if he removed his account or that it's 2 years ago. I care about other people who might still read this. And that it's not cool to comment on questions like this.

**Comment by OgiBalboa** [comment]
Guyz any solution ?

**Comment by YuehChuan** [comment]
@OgiBalboa  
pip installPyInstaller

pyinstaller -F -w YOURPYTHON.py

it should work.
It's OS dependent.

You can build linux executable on ubuntu linux.
If you want to build on window7 
Please install  PyInstaller on window. 
Do the samething.

Both should work.
I tested on ubuntu18.04.3 
window7 
a week ago.

**Comment by oz123** [comment]
@YuehChuan the whole point of the question was how to do it from Linux for windows. Telling someone that it works on Windows is pointless. Not everyone can afford or are willing to buy a Windows license.

**Comment by YuehChuan** [comment]
@oz123 
 It is clearly not a content for you. Please just run docker with wine and come back.

**Comment by AgustinPardo** [comment]
Here is a tutorial to compile on Linux from Windows!

https://www.andreafortuna.org/2017/12/27/how-to-cross-compile-a-python-script-into-a-windows-executable-on-linux/

**Comment by ErmiaMoghadamy** [comment]
add .exe extention and chmod (whatever in fcking windows called)
and test that via wine in linux too

**Comment by L0nm4r** [comment]
there is a ready-made docker image: https://hub.docker.com/r/cdrx/pyinstaller-windows

**Comment by somedeveloper00** [comment]
> > I'm sorry.
> 
> Dude, everyone is a beginner at some point. He is tryna learn and thats a good thing. For people like you we get demotivaed. There was a time when you didnt know the meaning of kernal. And same for me and same for bill gates, elon musk, and the world's great hacker kevin mitnick. And you are being a waste of time. We can discurss good stuff here.

hey. back 2 years later. I was surprised Elon Musk was still a thing back then!

**Comment by fuad-daoud** [comment]
> Come back when you've completed CS50.

Again you are a dickhead there is a first time for everything everyone is a beginner at some point but also everyone is a bad person at some point I just hope you got the point you are dealing with such issues more conveniently because no one was born a bad person people change.
