### ISSUE TITLE
Python Accept OpenGL 3.0 but PyInstaller take OpenGL 1.1 When Produce EXE 

### ISSUE THREAD

**Issue by tejastank** [pyinstaller/pyinstaller#2620]
![openglerror](https://cloud.githubusercontent.com/assets/311413/26308525/425fb1e0-3f17-11e7-962d-9edbff17c007.png)
* Followed previouse steps for varification on pyinstallation.
Problem persists, 

* Try the latest development version, using the following command:
Kivy 1.10 and pyinstall latest in window 10.0. 
When we run kivy python application it works fine and use OpenGL 3.0 version doing perfect
But when we try to generate exectutable via pyinstaller it takes OpenGL 1.1.

So when we run executable it gives OpenGL 1.1 issue, even python direct execution make it work better.

*** Please do not update status of bug, I am going to submit more details here.

**Comment by bwoodsend** [comment]
Presumably you need to track down your `opengl3.0.dll` and `--add-binary` it.

**Comment by tejastank** [comment]
I dropped Kivy framework from our primarily desktop application development.
