### ISSUE TITLE
problem restarting myapp.exe from within

### ISSUE THREAD

**Issue by mprosperi** [pyinstaller/pyinstaller#2622]
hello, I have a wxpython application that I want to restart from within itself (just for cleanup, not for updating it). Somewhere in the app there is an exec(script) where script is like this:

import sys
import os
myapp= sys.executable
os.execl(myapp, myapp,*sys.argv)

If I run myapp from source the application stops and restarts as expected but if I package it with pyinstaller then the application runs correctly, when executing the script it exits as expected but doesn't restart (win7, python2.7). Is it a limitation of pyinstaller exes or some other approach must be used?

thank you in advance for hints

Marco

**Comment by tallforasmurf** [comment]
You might want to run the test script in [this section of the doc](http://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-sys-executable-and-sys-argv-0) to see if sys.executable is what you want in the frozen app.

**Comment by mprosperi** [comment]
I've found that spaces in the executable path create problems with execl, not pyinstaller. This works:

import sys
import os
myapp= str(sys.executable).replace('Program Files','Progra~1')
sys.argv[0]=myapp
os.execl(myapp, *sys.argv)
