### ISSUE TITLE
--onefile option doesn't work with *.pyd files

### ISSUE THREAD

**Issue by Chenjunchao** [pyinstaller/pyinstaller#2624]
Hello, 
    I am using Cython to compile my python code to a few *.pyd files and call them by a shell.py file. When I try to package them with pyinstaller, it works fine with --onedir option. However, I tried with --onefile option, it seems pyinstaller always generate a dist folder instead of a single shell.exe file. I really want to generate a single executable file to hide my code structure.  I tried --onefile with pure python code, it works fine. Is this a limitation of pyinstaller or is there a solution to this?

    Here is my environment:
    Platform: Windows 64-bit
    Python version: 3.6.1
    Pyinstaller version: latest develop version (I got them from github)

Thanks you in advance for hints.

Billy

**Comment by ManPython** [comment]
I'm suggesting to provide more details about procedure, eg. how looks the comand or maybe .bat file (sometimes comand are not reconized corectly eg \ shlash /enter and skips some options eg. --hidden-import which I experienced very often).

**Comment by Chenjunchao** [comment]
Thanks for your reply. I found an issue in my spec file, the issue has been fixed.

**Comment by waitwhatisthis97** [comment]
What was the issue? How did it get solved?
