### ISSUE TITLE
import of pymssql

### ISSUE THREAD

**Issue by ChiliMax90** [pyinstaller/pyinstaller#2625]
I've experienced some troubles with the latest development version and python 3.6.1.
importing pymssql leads to the following errors. I have to separately include _mssql and decimal.
```
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "_mssql.pxd", line 10, in init pymssql (pymssql.c:12429)
ModuleNotFoundError: No module named '_mssql'
Failed to execute script main
```
```
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "_mssql.pxd", line 10, in init pymssql (pymssql.c:12429)
  File "c:\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "_mssql.pyx", line 50, in init _mssql (_mssql.c:24363)
ModuleNotFoundError: No module named 'decimal'
Failed to execute script main
```

**Comment by htgoebel** [comment]
There is an unfinished pull-request for mssql #2158. It would be great i you'd complete it (which in this case means: provide a new pull-request, solving the issues mentioned in #2158).

I'm closing this, waiting for somebody to provide a hook.mssql is a commercial product, so i you have money to pas MS, you should have resources to provide a hook.

**Comment by Miyasgi** [comment]
Does this mean we can't run it with **Import pymssql** in python file?

**Comment by htgoebel** [comment]
@Miyasgi 2158 has been merged, thus pymssql should work.

**Comment by apecnascimento** [comment]
I have PyInstaller==3.3.1 and pymssql==2.1.3 and the problem persists.

**Comment by otomazeli** [comment]
#To whom might help
#I got lots of issues trying to user pymssql with Pyinstaller and 
#I finally got it right so posting here might help someone
#after you install pymssql using pip install pymssql

#use this parameters in pyinstaller to get it included

--onefile --paths=.\venv\ --hidden-import='pymssql' --hidden-import='uuid' --collect-all='pymssql' --collect-all='uuid'
