### ISSUE TITLE
the out of bin file can't get realpath by os.path.realpath(__file__) on mac

### ISSUE THREAD

**Issue by yuangu** [pyinstaller/pyinstaller#2626]
env:
python 2.7.13
pyinstaller 3.2.1
macos sieera 10.12.4

1、create a main.py at ~/Documents/code/main.py
########
import os
print os.path.realpath(__file__)
########
2、create a bin 
cd  ~/Documents/code
pyinstaller --consloe --onfile main.py
3、 run out bin file
./dist/main

#this ret is ~/Documents/code/main.py

cd .. 
.code/dist/main
#this ret is ~/Documents/main.py

In a word,  the out of bin file can't get realpath by os.path.realpath(__file__) on mac.。

**Comment by yuangu** [comment]
Similar problems  #2626

**Comment by vdolbakyan** [comment]
Try 

```
import sys, os
frozen = 'not'
if getattr(sys, 'frozen', False):
        # we are running in a bundle
        frozen = 'ever so'
        bundle_dir = sys._MEIPASS
else:
        # we are running in a normal Python environment
        bundle_dir = os.path.dirname(os.path.abspath(__file__))
print( 'we are',frozen,'frozen')
print( 'bundle dir is', bundle_dir )
print( 'sys.argv[0] is', sys.argv[0] )
print( 'sys.executable is', sys.executable )
print( 'os.getcwd is', os.getcwd() )
```

**Comment by yuangu** [comment]
@vdolbakyan tks

**Comment by yuangu** [comment]
sys.executable  instead of os.path.realpath(__file__)

**Comment by BoboTiG** [comment]
@yuangu can you close the issue if it is fixed for you?

**Comment by yuangu** [comment]
@BoboTiG I'm sorry to close the issue so late.  I fixed my problem.
