### ISSUE TITLE
Does pyinstaller support python3.6?

### ISSUE THREAD

**Issue by coloer** [pyinstaller/pyinstaller#2631]
Hello, I want to know whether pyinstaller supports python3.6 or not?
I can't find any useful information about it in the issue list, so i decide to ask about it .
Can anybody help me? ^_^

**Comment by anton-petrov** [comment]
It will support Python 3.6 soon. The authors are working on this and you could help him ;)

**Comment by anton-petrov** [comment]
Look here https://github.com/pyinstaller/pyinstaller/pull/2341
