### ISSUE TITLE
Single-file noconsole executable loses main window focus

### ISSUE THREAD

**Issue by ProjectThreepio** [pyinstaller/pyinstaller#2632]
Tested with PyInstaller 3.2.1 and Python 3.4.6 on Windows 10 64-bit (32-bit executable).

Code:
import win32api
win32api.MessageBox("DEBUG","Test")

When the script is executed via Python, the window is in the foreground with focus.  When frozen into a console executable, the window is also in the foreground with focus.  When frozen into a noconsole executable, the window is in the foreground but does not have focus--and I think it should.

I'm wondering if this is a bootloader issue.

**Comment by xoviat** [comment]
onefile does not support foreground focus. If you want that, use onedir.

**Comment by ProjectThreepio** [comment]
Really not trying to belabor the point--just trying to figure out the underlying cause.

Onefile gets foreground focus in console mode, just not in noconsole mode.  Is there a significant different in how these are invoked, leading to the different behaviors?

**Comment by xoviat** [comment]
> Really not trying to belabor the point--just trying to figure out the underlying cause.

The underlying cause is that onefile spawns a subprocess that creates the onedir directory in a temporary folder and then runs the onedir executable. However, it is the onefile executable that has focus in this case because it was started by explorer. If you want to change this, then be prepared for a week of bootloader hacking and a month's (at least) of pull request review. I don't even have a viable solution off the top of my head that would work and I'm also personally against onefile because it makes the source more complicated.

**Comment by ProjectThreepio** [comment]
Got it.  You can go ahead and close this then.

For the reference of people running into similar issues, you can kinda-sorta work around this on Windows only, under certain circumstances, using something like:

```
def grab_focus():
    pid=os.getpid()
    vbscript_file="some_path.vbs"
    with open(vbscript_file, "w") as vbs_script:
        vbs_script.write("CreateObject(\"wscript.shell\").appactivate WScript.Arguments.Item(0)\n")
    arg_list=["start","/min","","cscript.exe", VBScriptFile, str(pid)]
    time.sleep(0.3)
    subprocess.Popen(arg_list, shell=True)
```

The sleep call appears to be necessary, even if it (or because it) blocks your GUI thread, and the function has to return while the cscript is still running.  Pretty ugly really, but it works on my tkinter dialogs.

**Comment by htgoebel** [comment]
@ProjectThreepio Thanks for sharing the code. Would you mind puttint it into into the wiki as a receipt? This would make it easier to find for others than within this ticket.

**Comment by ProjectThreepio** [comment]
I'll work on that.  I had no idea there was a wiki ;)
