### ISSUE TITLE
pygobject gtk3 linux typelib xlib2 not found

### ISSUE THREAD

**Issue by thiolliere** [pyinstaller/pyinstaller#2634]
with pyinstaller develop on linux when packaging:
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

print("tototototo")
```

on another linux machine the result is:
`gi.RepositoryError: Typelib file for namespace 'xlib', version '2.0' not found`

add `xlib-2.0.typelib` in gi_typelibs seems to solve the issue.

**Comment by thiolliere** [comment]
well on a virtual machine with debian jessie I have now a segmentation fault

**Comment by virtuald** [comment]
Hm, that typelib should have been picked up. What version of pygobject/gtk is it?

**Comment by thiolliere** [comment]
well I don't remember in what environment I made it.
It may be that I build on a system that hasn't gtk installed.
