### ISSUE TITLE
License clarification for importing PyInstaller

### ISSUE THREAD

**Issue by JonathonReinhart** [pyinstaller/pyinstaller#2645]
I've written a tool named [staticx](https://github.com/JonathonReinhart/staticx) whose purpose is to bundle up all of the dynamic libraries required for an application to run, and use them at runtime. Currently, this only works for 64-bit Linux, although I may expand it to other platforms in the future.

One reason this may be interesting to the PyInstaller team is that using StaticX to wrap a PyInstaller-generated executable allows it to be run on *any* Linux system, eliminating the problems identified in the FAQ under this section:

> **Under Linux, I get runtime dynamic linker errors, related to libc. What should I do?**

In order to make this technique work out-of-the-box with PyInstaller executables, [I use `PyInstaller.archive.readers.CArchiveReader` to examine the archive](https://github.com/JonathonReinhart/staticx/blob/78db958aa05af98ca6a0823524bb4eb189a23a14/staticx/api.py#L108), and bring along any additional dynamic library dependencies not found there.

Now, I'm trying to apply a license to my software. I would prefer to license it with a permissive license like MIT. However, I'm not sure if this is possible due to my (optional) PyInstaller "hook". I am not modifying PyInstaller in any way, simply using the programmatic equivalent of `pyi-archive_viewer`.

Am I ok to license my code as MIT? I've read the license and the [license section of the FAQ](https://github.com/pyinstaller/pyinstaller/wiki/FAQ#license), and I believe that I can.

**Comment by htgoebel** [comment]
PyInstaller is licensed under the GNU Public License. This means: as soon as your are using something like `import PyInstaller` or `from PyInstaller import …` (as you do) your software is to be GPL'ed, too.

Only the result (output) of your tool may be licensed differently – like the output of PyInstaller.
