### ISSUE TITLE
New release for 3.6 support?

### ISSUE THREAD

**Issue by mkleehammer** [pyinstaller/pyinstaller#2646]
I see the latest development version has Python 3.6 support - can you make an official release on PyPI with this?

It would be greatly appreciated.  While I can use the development version for one-off executables, I need to allow them to be created on build machines which pull everything down from scratch, including PyInstaller.  These machines don't have the latest Visual Studio, so official releases with binary executables would really help.

Thanks.

**Comment by skys215** [comment]
It seems that Python 3.6 will be supported on PyInstaller 3.3.
I'm not sure, just made a conclusion by the thread I read in the GIthub issues.

**Comment by htgoebel** [comment]
> can you make an official release on PyPI with this

Yes, as soon as it's ready. There are still few thing to do.

**Comment by htgoebel** [comment]
Duplicate, see #2331.
