### ISSUE TITLE
Onefile on linux make AppImage file

### ISSUE THREAD

**Issue by tibor-vavra** [pyinstaller/pyinstaller#2647]
Hi,
Im using pyinstaller in my multiplatform projects, I like it :-)

It will be nice if pyinstaller with parameter --onefile create on linux platform AppImage file.

Thanks

**Comment by tallforasmurf** [comment]
TIL what [appimage](http://appimage.org/) is. Don't have time to read in detail. What are the features of an appimage file that are different from a --onefile PyInstaller file?

**Comment by tallforasmurf** [comment]
According to the appimage page,

> The key idea of the AppImage format is one app = one file. Every AppImage contains an app and all the files the app needs to run. In other words, each AppImage has no dependencies other than what is included in the targeted base operating system(s).

This is exactly the principle behind --onefile. However the implementation is quite different. According to the [rather minimal wiki entry](https://en.wikipedia.org/wiki/AppImage):

> An AppImage is an ISO 9660 file with zisofs compression containing a minimal AppDir and a tiny runtime.

Where PyInstaller has [`pyi-archive_viewer`](http://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#using-pyi-archive-viewer), for appimage there is `appimagetool` for inspecting and extracting parts of an appimage (it is also the tool for generating one).

Something PyInstaller does not offer is `appimaged`,

> an optional daemon that watches locations like ~/bin and ~/Downloads for AppImages and if it detects some, registers them with the system, so that they show up in the menu, have their icons show up, MIME types associated, etc.

If one were to start the PyInstaller project from scratch today, it would make good sense to use appimage as the output format, so as to take advantage of these tools. However, it seems to me that today, it would be a massive change to go away from the existing --onefile  output format to a different format, needing a completely different bootloader and changes in how Python imports are handled at run-time. Run-time hooks would have to be competely re-thought, for example.

Unless somebody wants to step up and start designing this big coding effort, I recommend this issue be closed.

**Comment by htgoebel** [comment]
This is out of scope for PyInstaller. PyInstaller is not a tool for building any type of container.

**Comment by htgoebel** [comment]
For the records: We also will not implement a packer for snappy and other kinds.
