### ISSUE TITLE
Problems with PyInstaller with tkinter app on python 3.5

### ISSUE THREAD

**Issue by sealyons** [pyinstaller/pyinstaller#2648]
Just getting started with Pyinstaller (and somewhat with Tk windowing) and having trouble getting my tkinter windows app (under python 3.5.3) running successfully.  I may be doing something stupid but I've tried everything I know and I really need to get this running, so any help is greatly appreciated.  I've tried several forums and nobody has been able to help so I'm trying here as a last resort.  Just a note, all of my code runs fine under normal python 3.5.1 & 3.5.3. Have latest version of PyInstaller installed (3.2.1) and it appears to be running OK. I also tried the latest development version of PyInstaller (3.3) but it gave the same issues.  As you'll see below, I've backed this out to a simple py program, which still doesn't work, so I don't believe this is a bug issue, but I can't figure out what the problem is so PLEASE help.

I switched over to the following simple windowed "Hello World!" app to see if I could get this to work,

```
  from tkinter import *
   root = Tk()
   root.title("Test Window")
    
   #Setup window widgets and place on window
   l1 = Label(root,text='Hello World!',font=("Verdana",18))
   l2 = Label(root,text='Hello World!',font=("Times New Roman",9))
   b1 = Button(root, text='Button 1', font=("Verdana",12), state=DISABLED)
   b1.pack()
   b1.place(x=220, y=180)
    
   l1.pack()
   l1.place(x=170, y=10)
   l2.place(x=200, y=60)
    
   root.mainloop()
```
but it appears to be having the same issues as my original application.  

Maybe it's just because I'm new to PyInstaller but I'm not finding the docs really easy to find specific answers from.  But looking a little deeper, I decided to add the -d option to the command line to see the debug output as it tried to execute my app, so the complete command line I'm using is: > pyinstaller -F -w -d c:\PythonApps\Hello.py . That gave me lots of info (but nothing really helpful at this point) ending in this error message:

**Failed to execute script pyi_rth_tkinter.**

I was able to find 'pyi_rth_tkinter.py' on my system (actually 2 versions of the file), not sure why PyInstaller is having problems executing it.  But since that file spits out error messages about path problems for Tcl & Tk data directories, guessing it would have failed on that anyway even if it had found & ran the file (due to the following).  

OK, looking more closely at the output during the running of PyInstaller, I see that there are a few lines that look like they may be leading to my problem:

> 3541 INFO: Loading module hook 'hook-_tkinter.py'
> ImportError: cannot import name 'Tcl'
> 3659 ERROR: Tcl/Tk improperly installed on this system.

I looked at the "hook-_tkinter.py" hook file (and read through the PyInstaller docs) but didn't see anything obviously amiss.  But I'm not fully aware of all the details of the hook files and exactly what they need to contain (can anyone help with this???). Not exactly sure what the problem is but it appears PyInstaller is having an issue with linking into tkinter and that is causing my app(s) not to run. HAS ANYONE GOTTEN PyInstaller 3.2.1 TO EXECUTE EVEN A SIMPLE PYTHON 3.5 WINDOWS APP?  IF SO, PLEASE SHARE HOW!  I've done a ton of searching and reading but have not been able to uncover what the problem is yet.  If anyone has a clue, please help.  Any guidance is greatly appreciated!

A bit of additional info.  Not sure why PyInstaller is saying Tcl/Tk is not properly installed. I just installed Python 3.5.3 and tkinter was installed automatically.  Executed **'tkinter._text()'** in a shell and it appears to work fine.  All my uses of tkinter also appear to work fine under all versions of 3.5 under normal use of python. Only tkinter problem I'm having is with PyInstaller.  Verified the exact version of Tcl/Tk installed with **'tkinter.Tcl().eval('info patchlevel')'** and it reported **'8.6.4'**.  Does anyone know of any other installation issues with Tcl/Tk that may be a problem?  I did not do anything special to install tkinter, I just did a normal install of pyinstaller via **'pip install pyinstaller'** after doing a fresh install of **'python 3.5.3'**. Was there anything else I should have done?  Any help is greatly appreciated!!!

Again, I don't believe this is a bug and I apologize for posting this here, but I need to resolve this ASAP and nobody else has been able to help.  PLEASE forgive me and lend a a couple minutes and help me out.  Thank you very much.

**Comment by tallforasmurf** [comment]
Not a solution, just helping you analyze the problem. Thank you for posting these messages,

~~~
3541 INFO: Loading module hook 'hook-_tkinter.py'
ImportError: cannot import name 'Tcl'
3659 ERROR: Tcl/Tk improperly installed on this system.
~~~

They point specifically to the unusually complex hook (most hooks are one-liners), [hook-_tkinter](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-_tkinter.py#L196)  That link opens where the error message is issued.

The function starts by calling `_handle_broken_tcl_tk()` which does nothing if this is not a virtual env -- you don't mention using VENV so presumably it does not change anything?

Then it calls `_find_tcl_tk()` which, this not being OS X, calls  `_find_tcl_tk_dir()` which does this to get `tcl_root`:

~~~
    tcl_root = exec_statement(
'from %s import Tcl; print(Tcl().eval("info library"))' % modname_tkinter)
~~~

Wait, what is that `%s` substitution?

~~~
# In Python 3 'Tkinter' has been made lowercase - 'tkinter'. Keep Python 2
# compatibility.
if is_py2:
    modname_tkinter = 'Tkinter'
else:
    modname_tkinter = 'tkinter'
~~~

So this being python3, the code amounts to

~~~
    tcl_root = exec_statement(
'from tkinter import Tcl; print(Tcl().eval("info library")) )' 
~~~

The result fails the test 

~~~
    if not tcl_root:
        logger.error('Tcl/Tk improperly installed on this system.')
~~~

So, what does `from tkinter import Tcl; print(Tcl().eval("info library"))` do on your system?

**Comment by sealyons** [comment]
Thanks for looking into this.  On my system, `from tkinter import Tcl; print(Tcl().eval("info library"))` provides the following 

> C:\Users\<ME>\AppData\Local\Programs\Python\Python35\tcl\tcl8.6

**Comment by tallforasmurf** [comment]
That's too bad. Something is different while PyInstaller or more specifically, that hook, is running but I have no idea what or why. I have to suspect something is different about your installation, as the hook hasn't been messed with since 2015. Or maybe something has changed in Windows -- what version of Windows are you running? How did you install Python, e.g. from python.org, or ActiveState?

Paging @htgoebel or @matysek who worked on the hook back when.

**Comment by sealyons** [comment]
Running on Win7PRO SP1 (32-bit).  Python 3.5.3 installed from python.org.

**Comment by sealyons** [comment]
Sorry, this issue was (64-bit).  And there is an update.  I re-stalled python 3.5.3 & PyInstaller 3.2.1 on a new system (without any python installs) and everything worked OK.  So, there is something amiss with my machine that has lots of different installations of various development environments.  So since this problem is definitely due to that issue I'm going to close this issue for now.
