### ISSUE TITLE
error with subprocess.Popen when launching a Nuke file

### ISSUE THREAD

**Issue by flabbyThoroughbred** [pyinstaller/pyinstaller#2649]
Hi,

The problem I am having is trying to launch a Nuke file using subprocess.Popen within my pyinstaller build.
Specs are: PyQt5 on Python 2.7, Pyinstaller 3.2.1

If I try and run the code from a compiler, it's always worked fine i.e. subprocess.call('start c:\my_file.nk', shell=True)

I even tried building it with a simple script that just ran the subprocess command and it still failed *if* I built it as a one folder option.
If I built it as a one_file option, it works.

The unfortunate thing is, for my actual program that runs the subprocess script, I can't run a onefile build for QtWebProcessEngine issues. It has to be a one folder option.

Has anyone run into issues of this kind? I know it's rather specific.

Thanks!
-Mark

**Comment by htgoebel** [comment]
> Has anyone run into issues of this kind? I know it's rather specific.

To be honest, I'd call this report rather unspecific :-\ You not even mentioned the error you are facing.

Anyway: maybe https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess helps.

**Comment by htgoebel** [comment]
No reaction for several month, assume this is solves.
