### ISSUE TITLE
Pyinstaller onefile executable cannot find QtWebEngineProcess.exe

### ISSUE THREAD

**Issue by flabbyThoroughbred** [pyinstaller/pyinstaller#2650]
Hi,

I'm trying to build an exe for a program that utilizes QtWebEngineProcess. This works fine if I go for a one_folder solution but when I try a one file it can't locate QtWebEngineProcess.exe. I'm fairly certain it's dumping all the files to the temp directory and I'm explicitly copying over all the necessary files needed when I do the build.

My guess is that there's a problem locating the file in the temp directory after it gets unpacked. I tried creating a qt.conf file during the build but that still doesn't seem to work.

Has anyone run into this problem and found a solution? I've tried several things already to no avail.

Thanks! -Mark

**Comment by flabbyThoroughbred** [comment]
I should mention this is on a PC

**Comment by htgoebel** [comment]
Try tracing your file, see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged for tips how to do this.

**Comment by bjones1** [comment]
I'm closing this, since #3233 should fix it -- see the [instructions](https://github.com/pyinstaller/pyinstaller/pull/3233#issuecomment-362094587) there.
