### ISSUE TITLE
setup.py: missing requirement `past`.

### ISSUE THREAD

**Issue by Metallicow** [pyinstaller/pyinstaller#2651]
OS: Windows7 32bit
wxPython 4.0.0a4.dev3150+888e0ef msw (phoenix)
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32

Calls pyinstaller with subprocess like so...
```python
        if PHOENIX:
            wxBuildStr = 'Phoenix'
        else:
            wxBuildStr = 'Classic'
        consoleBuildStr = PyInstallerLocation + osSep + 'SourceCoder-Console-Standalone' + '-' + wxBuildStr
        subprocess.call(['python', #'-OO',
            os.path.join(PyInstallerLocation, 'pyinstaller.py'),
            '-F',
            '-n',
            consoleBuildStr,
            '-c',
            '-i',
            os.path.join(gAppDir, 'src', 'build_files', 'sourcecoder-console.ico'),
            '--version-file',
            os.path.join(gAppDir, 'src', 'build_files', 'SourceCoderVersionFile.py'),
            '-m',
            os.path.join(gAppDir, 'src', 'build_files', 'SourceCoder.exe.manifest'),
            os.path.join(gAppDir, 'SourceCoder.py'),
            ])
```
causes this traceback.
```
Traceback (most recent call last):
  File "C:\pyinstaller-develop\pyinstaller.py", line 14, in <module>
    from PyInstaller.__main__ import run
  File "C:\pyinstaller-develop\PyInstaller\__main__.py", line 21, in <module>
    import PyInstaller.building.build_main
  File "C:\pyinstaller-develop\PyInstaller\building\build_main.py", line 34, in <module>
    from .api import PYZ, EXE, COLLECT, MERGE
  File "C:\pyinstaller-develop\PyInstaller\building\api.py", line 38, in <module>
    from PyInstaller.utils.win32 import winmanifest, icon, versioninfo, winresource
  File "C:\pyinstaller-develop\PyInstaller\utils\win32\versioninfo.py", line 18, in <module>
    from ...lib import pefile
  File "C:\pyinstaller-develop\PyInstaller\lib\pefile.py", line 26, in <module>
    from past.builtins import cmp, long
ImportError: No module named past.builtins
```

**Comment by Metallicow** [comment]
I do not see a pip requirements.txt in the top of the project. Please make one.
see https://pip.pypa.io/en/stable/user_guide/#requirements-files

Does this ImportError refer to this package? https://pypi.python.org/pypi/past/

**Comment by htgoebel** [comment]
`past` is part of `future`, which should be installed when you install PyInstaller using setup.py or `pip install`. If you uses one of these, please reopen the tickat.

We are not providing a requirements-file as none of the use-cases listed at https://pip.pypa.io/en/stable/user_guide/#requirements-files is relevant for PyInstaller. The documented way to install PyInstaller is either `python setup.py …` or `pip install …`.

**Comment by Metallicow** [comment]
Thr docs say it works out-of-the-box, so I would assume downloading and extracting the zip from github would do that.
Just because the documented way to install PyInstaller is either `python setup.py …` or `pip install ….` doesn't mean you shouldn't include a requirements.txt. Some people do things manually.
`pip install -r requirements.txt` works also if you provide it with the same requirements as the others.
It is just another way to install.  And it is a quick way to look at a projects requirements also without digging into setup.py. Also pip is basically an online thing, and doesn't cater much for offliners much. Most of the computers we setup are done offline, with installers saved on thumb drive.
