### ISSUE TITLE
Pyinstaller automatically includes unneeded modules

### ISSUE THREAD

**Issue by ManPython** [pyinstaller/pyinstaller#2652]
1. What is the reason that Pyinstaller automatically includes unneeded modules?
Following the old topic via link:
https://stackoverflow.com/questions/36678903/pyinstaller-automatically-includes-unneeded-modules

2. Eg. I must create pyi1.bat file which create .spec file with exludes
--exclude-module=_bz2
--exclude-module=_ctypes
--exclude-module=_hashlib
--exclude-module=_lzma
--exclude-module=_socket 
--exclude-module=_ssl
...ad many from PyQt5
- _but there are limits for how long can be commands_ 
a) this made a app.spec file with:
`excludes=['_bz2', '_ctypes', '_hashlib', '_lzma', '_socket', '_ssl'],`
- but if we want add more excludes, and we add this to the app.spec, eg.
`excludes=['_bz2', '_ctypes', '_hashlib', '_lzma', '_socket', '_ssl','other_lib'],`
- then  app.spec is created again and 'other_lib' will be ignored
b) how to easy operate with pyi2.bat to use app_.spec where is 'other_lib'? Like:
`excludes=['_bz2', '_ctypes', '_hashlib', '_lzma', '_socket', '_ssl','other_lib'],`

3. In _MEIxxx is folder: **Include** with file: pyconfig.h
- We need this? Why?

4. In _MEIxxx is folder **qt5_plugins** with folders:
bearer: qgenericbearer.dll, qnativewifibearer.dll  
iconengines: qsvgicon.dll
imageformats: (many dlls)
platforms: qminimal.dll, qoffscreen.dll, qwindows.dll (this last is required like in py2exe, but why can't be with rest of .dll's in main catalog with optimal count of dll's?)
printsupport: windowsprintersupport.dll
- We need this? Why?
a) ..
b) can we exculde something from this automaticly (as procedure for future similar work)? How?

5. In _MEIxxx is folde is file base_library.zip
- We need this? Why? 
Maybe is wrong question, coz if this be deleted then app not working, but:
a) can we have this in .exe or one other formt file eg dll or something ? (how to do this?)
b) can we exculde something from this automaticly (as procedure for future similar work)? How?

6. And last question about files. There is few files as .pyd which are related with PyQt .dll  inside _MEIxxx, eg: 
pyexpat.pyd
PyQt5.Qt.pyd
PyQt5.QtCore.pyd
PyQt5.QtGui.pyd
PyQt5.QtNetwork.pyd
PyQt5.QtPrintSupport.pyd
PyQt5.QtWebKit.pyd
PyQt5.QtWebKitWidgets.pyd
PyQt5.QtWidgets.pyd
select.pyd
sip.pyd
unicodedata.pyd
win32api.pyd
win32evtlog.pyd

- We need this? Why? 
Maybe is wrong question, coz if this be deleted then app not working, but:
a) can we have this in .exe or one other formt file eg dll or something ? (how to do this?)

This questions are motivated in relation to py2exe where after "compilation" some PyQt5 app to one single file we have:
app.exe
platforms: qwindows.dll
..and PyQt5 .dll's files depend of used lib (5dll or 15dlls), but in pyinstaller always is as in upper lines (full of files).

Thanx for explanation. I realy read docs etc.. but I not found answers for this all.
https://media.readthedocs.org/pdf/pyinstaller/latest/pyinstaller.pdf

**Comment by htgoebel** [comment]
For asking this kind of questions, the mailing-list is more appropriate, since one can quote much easier. Please ask there. Thanks,

**Comment by ManPython** [comment]
Looks like my posts on Google Group are not accepted even content of questions looks this same as here.

**Comment by htgoebel** [comment]
> Looks like my posts on Google Group are not accepted even content of questions looks this same as here.

Argl. Google Group are a pain in the a**. You are not the only one hit by this :-( I will try answering here:

> 1. What is the reason that Pyinstaller automatically includes unneeded modules?

PyInstaller does it's best to include only the needed modules - that's what PyInstaller is about :-). But many packages have optional dependencies which for *your* program might not be necessary, but are for other programs. PyInstaller can't know this and if PyInstaller would remove to much, other programs might fail. Please use option `--exclude` for this.

Please keep in mind, that alone Python's feature "full unicode support" add a lot of codecs modules, which look unecessary but are required for Python to work properly.

> 2. Eg. I must create pyi1.bat file which create .spec file with exludes
> a) this made a app.spec file with:
> b) how to easy operate with pyi2.bat to use app_.spec where is 'other_lib'? Like:

PyInstaller is not able to update you spec-file – if calling `pyinstaller app_.py`, the spec-file gets overwritten. If you have modified the .spec-file, you need to run `pyinstaller app_.spec`, as described in the manual. 

> 3. In _MEIxxx is folder: **Include** with file: pyconfig.h
> - We need this? Why?

Some module needs it. I think it's `platform`. Please check the PyInstaller source if you need to know in detail.

> 4. In _MEIxxx is folder **qt5_plugins** with folders:
> - We need this? Why?

These are requirements for Qt5, I assume. Packaging Qt5 is complicated, there might be errors. Please refer to all the open tickets regarding QT5, comment there and – in case – provide a pull-request (or go in toch with another pull-request's author).

> b) can we exculde something from this automaticly (as procedure for future similar work)? How?

Simply add the appropriate `os.remove()` calls to you spec-file.

> 5. In _MEIxxx is folde is file base_library.zip
> - We need this? Why? 

This is required for Python 3 to work at all. It includes the "bootstrap" libraries.

> a) can we have this in .exe or one other formt file eg dll or something ? (how to do this?)

no.

> b) can we exculde something from this automaticly (as procedure for future similar work)? How?

I may try removing stuff there (e.g. some codecs), but this might break thinks. See my explanation at the top.

> 6. And last question about files. There is few files as .pyd which are related with PyQt .dll  inside _MEIxxx, eg: 
> PyQt5.Qt.pyd
> - We need this? Why? 

I assume you application is using PyQt5?!

> a) can we have this in .exe or one other formt file eg dll or something ? (how to do this?)

no.

> This questions are motivated in relation to py2exe where after "compilation" some PyQt5 app to one single file we have:
app.exe
platforms: qwindows.dll
..and PyQt5 .dll's files depend of used lib (5dll or 15dlls), but in pyinstaller always is as in upper lines (full of files).

As written above, the Qt5-stuff might have room for improvement. We appreciate improvements on this, so feel free to submit a pull-request.

**Comment by htgoebel** [comment]
No further questions, assumed to be solved.

**Comment by fingoldo** [comment]
This is unbelievable. I tried your product, pyinstaller, to package simple Tkinter app which only shows some UI, reads a csv file using Pandas and plots it using matplotlib. pyinstaller ended up creating a 3GB (yes, 3 Gigabytes) folder which contains torch,PyQt5, botocore, selenium, all flavours of cuda binaries, and pretty sure every other module available in my system, 99% from which are 100% unneeded for the deployment. What is the value of your package if I have to manually exclude everything? Am I missing something?

Python 3.6 on Anaconda, Windows x64

**Comment by FrancescoSaverioZuppichini** [comment]
Unbelievable there is no option to just include what you need.

**Comment by Dev-I-J** [comment]
> on Anaconda

It's a problem with anaconda; Just Create A VirtualEnv only including the modules you want.

**Comment by aminPial** [comment]
> Unbelievable there is no option to just include what you need.

> This is unbelievable. ........What is the value of your package if I have to manually exclude everything?

The thing that is unbelievable is that you didn't do enough research on your problem. Here is the simple step to exclude unnecessary files and as a bonus how to reduce size in general:

1. Create a `virtual environment` and install necessary packages under this virtual env. And then run pyinstaller from the command line with being **`venv active`**
2.  use -O or -OO flag to add some basic optimizations. See [Running PyInstaller with Python optimizations](https://pyinstaller.readthedocs.io/en/stable/usage.html#running-pyinstaller-with-python-optimizations)
3.  Use UPX. (this is a great boost to reduce size)
4. check for `unnecessary assets`(image, text, doc, video, etc.) and `caches` in the `dist` folder.

Cheers!

**Comment by bwoodsend** [comment]
> reads a csv file using Pandas and plots it using matplotlib.

Matplotlib supports a wide range of GUI backends meaning that it contains imports to tkinter, PyQt 4 and 5, PySide 1 and 2, every other UI library in existence. Its IPython and Jupyter notebooks integration mean that it also imports IPython and Jupyter which contain integrations for (and therefore imports to) all kinds of popular libraries.

If you can suggest a way that PyInstaller could differentiate between imported modules you need and imported modules you don't then we're all ears. Otherwise, do what it says in the docs and create minimal environments to build in.

**Comment by lastmjs** [comment]
I'm trying to use pyinstaller to just bundler the .pyc files directly imported from my entry point Python file and any of its imports. Even if I import nothing, I get a ton of .pyc files in the build. I don't need the bootloader or anything, is there a way to turn off whatever extra code is being imported? I assume there is some extra Python code being written to my entry point file that pyinstaller assumes is necessary, but I would like to turn off.

**Comment by rokm** [comment]
> I'm trying to use pyinstaller to just bundler the .pyc files directly imported from my entry point Python file and any of its imports. 

Sounds like you might want to use `modulegraph` directly to analyze your code and collect your .pycs instead of trying to (mis)use pyinstaller. Especially if you do not want to bundle python standard library.

> Even if I import nothing, I get a ton of .pyc files in the build. 

Even if you import nothing, there are parts of python standard lib that are needed to initialize the embedded python interpreter that PyInstaller sets up in the stand-alone frozen executable.

> I don't need the bootloader or anything, is there a way to turn off whatever extra code is being imported? 

No.

> I assume there is some extra Python code being written to my entry point file that pyinstaller assumes is necessary, but I would like to turn off.

The entry point is collected as-is. But yes, parts of python standard library are collected in order to provide a functioning stand-alone executable. And since that's what PyInstaller does, there is no way to turn it off, as there is no reasonable use case for it being turned off. 

That doesn't prevent you from taking the relevant parts of PyInstaller and repurpuse them for your use case, though.

**Comment by ManPython** [comment]
Sorry for the comment, but to Moon you can fly on broomstick.. theoretical, in practical not.. (probably).
And this is the comment to the Python now and open source. Try Nuitka.

**Comment by lastmjs** [comment]
> Sounds like you might want to use modulegraph directly to analyze your code and collect your .pycs instead of trying to (mis)use pyinstaller. Especially if you do not want to bundle python standard library.

Great I will look into `modulegraph`

**Comment by lastmjs** [comment]
@rokm `modulegraph` looks like exactly what I need, if you don't mind, can you point me to how pyinstaller consumes the output? I'm not sure how to parse the output and get it into a usable data structure.

**Comment by rokm** [comment]
> @rokm `modulegraph` looks like exactly what I need, if you don't mind, can you point me to how pyinstaller consumes the output? I'm not sure how to parse the output and get it into a usable data structure.

PyInstaller has a vendored copy of `modulegraph` where some names have been changed for easier transition to `modulegraph2` (back when that was still on the table). And then `PyInstaller.depend.analysis` contains a subclass that integrates the hooks functionality and such...

Once you pass a modulegraph a script to analyze, it returns the node in the constructed graph; you can then either traverse the graph from that node, or you can flatten it to obtain the list of all nodes in it (as done for example [here](https://github.com/pyinstaller/pyinstaller/blob/b3087846a35a799d60b17c85cce480f42dcedb55/PyInstaller/depend/analysis.py#L492-L519) - but mind the changed names compared to original `modulegraph`).

Using the original `modulegraph`, the analysis would look roughly as follows:

```python
import sys

import modulegraph.modulegraph

mg = modulegraph.modulegraph.ModuleGraph()
entry_point_node = mg.run_script(sys.argv[1])  # Analyze entry-point script file, passed via argv[1]

# a) Flatten the graph and iterate over all nodes
for node in mg.flatten(start=entry_point_node):
    print(node)
    # Do something with node based on its type

# b) Traverse the graph from entry-point node towards leaf nodes
for child_node in mg.getReferences(entry_point_node):
    print(child_node)
    # Do something with node, e.g., obtain its references by calling mg.getReferences() again
```
