### ISSUE TITLE
tests: requests connection pool failure

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#2656]
I don't have time to investigate this as of now, but the issue appears to be potentially serious. This is because the failure states that there is `no module named requests` when the script has the following import:

```python
import requests.connectionpool.something
```

This cannot be a hook failure because modulegraph should pick up that import. I think.

**Comment by xoviat** [comment]
Yeah, here are the worrying lines:

```
[95537] LOADER: Cleaning up Python interpreter.
Traceback (most recent call last):
  File "/tmp/pytest-of-travis/pytest-0/popen-gw2/test_requests_urllib3_six_oned0/test_requests_urllib3_six.py", line 3, in <module>
    import requests.packages.urllib3.connectionpool
ModuleNotFoundError: No module named 'requests'
```
