### ISSUE TITLE
Failed to install new pyinstaller. 'is_module_satisfies' import still happens

### ISSUE THREAD

**Issue by wxcsdhr** [pyinstaller/pyinstaller#2662]
I tried to use the latest version of pyinstaller on CentOS 7 for development. I installed pyinstaller by command `pip install pyinstaller`. However, the import issue for `is_module_satisfies` is still there under `hook-botocore.py`. Here is what I got from hook-botocore.py under my directory.  Have no idea why it is different from yours in the repo

```
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.compat import is_py2, is_module_satisfies
```

**Comment by htgoebel** [comment]
> Here is what I got from hook-botocore.py under my directory.

Looks like you have conflicting instances of PyInstaller. Please remove the one "under your directory".
