### ISSUE TITLE
UAC Elevation not working on windows 10

### ISSUE THREAD

**Issue by Messiah93** [pyinstaller/pyinstaller#2663]
When I use PyInstaller with my project on Windows 10, UAC Elevation doesn't work. Example:

```
# Windows 7 : C:\\python_projects\\test\\bin\\test.exe
# Windows 10: C:\\python_projects\\test\\bin\\test.exe
#
# Python27
# PyInstaller 3.2.1 (tested with dev-version too)

import ctypes
import os
import sys

this = os.path.abspath(sys.argv[0])

class UAC:
    def __init__ (self):
        try:
            self.UACStatus = ctypes.windll.shell32.IsUserAnAdmin()
        except Exception as error:
            print("Unable to retrieve UAC Elevation level: %s" % error)
            self.UACStatus = 0
    
    def get (self):
        print("UAC Level: %s" % self.UACStatus)
        return bool(self.UACStatus)
    
    def set (self):
        if not self.get():
            try:
                ctypes.windll.shell32.ShellExecuteW(None, "runas", this, "", None, 1)
            except Exception as error:
                print("Unable to request UAC Elevation: %s" % error)

if __name__ == "__main__":
    print(this)
    Elevation = UAC()
    Elevation.set()
```

No error happend...

When I compile and run with PyInstaller on Windows 7, it's working, my program is reloading with UAC Elevation.. But when I compile and run with PyInstaller on Windows 10, nothing happend. The exe file is bigger on Windws 7 than Windows 10 (+ 1mb ~). 

OS Tested: Windows 7 familial x64 (python 2.7 - pyinstaller 3.2.1 - pyinstaller-dev)
OS Tested: Windows 10 x64 (python 2.7 - pyinstaller 3.2.1 - pyinstaller-dev)

So, I'm forced to compile my projects require UAC Elevation on my Windows 7 VM.

**Comment by htgoebel** [comment]
Please make sure you have *exactly* the same setup on both machines. If the size differs so much, this is a clear sign that something is missing on one  machine.
- Try --one-dir mode
- Compare the warn* files in the `build` folder to find differences.
- Use the archive-viewer to spot differences

**Comment by Messiah93** [comment]
Mea culpa, It was the same setups and project, but, on windows 7, I was compiling with py -3 and on the windows 10, with py -2. So, UAC Elevation is working only with Python3. With Python 3, now it's working on Windows 7 and Windows 10, but with Python2, it's not working on both. Maybe it's normal UAC Elevation won't work on Python2.7...

**Comment by htgoebel** [comment]
I consider this to be not a PyInstaller iusse.
