### ISSUE TITLE
pyinstaller no module errore 

### ISSUE THREAD

**Issue by danielepemy** [pyinstaller/pyinstaller#2664]
Hi,

I have 2 python versions installed under my mac osx sierra: python 3.5 python 2.7

I installed pyinstaller under python3.5 with this command:

python3.5 -m pip install pyinstaller
If I run again the same command I'm getting:

Requirement already satisfied: pyinstaller in ./lib/python3.5/site-packages Requirement already satisfied: setuptools in ./lib/python3.5/site-packages (from pyinstaller)
(sounds good to me)

When I run this command:

python3.5 -m pyinstaller mypython35script.py
I'm getting: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5: No module named pyinstaller

I can see the pyinstaller if I navigate into this folder:
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5

why? What I'm doing wrong?

Cheers D.

**Comment by htgoebel** [comment]
> python3.5 -m pyinstaller mypython35script.py

The correct use is just `pyinstaller mypython35script.py`

> I'm getting: /Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5: No module named pyinstaller

This error message is correct: PyInstaller does not provide a module `pyinstaller`.
