### ISSUE TITLE
ImportError: cannot import name 'MappingProxyType'

### ISSUE THREAD

**Issue by Kaseaa** [pyinstaller/pyinstaller#2667]
Windows 10 64 bit, Python 3.6.1 32 bit, Pyinstaller dev build

Note: Went with screenshots, because i can't seem to get github's text editor to look readable

Fresh python 3.6.1 32 bit install with development build. In addition fresh MySQLClient version.

Code that's being compiled.

![](https://i.gyazo.com/bc4425580710344f754e07f153574225.png)

Compiling it with pyinstaller test.py

![](https://i.gyazo.com/8b278fc02b95eda80c890445e9b877f9.png)

When running it I get the following error

![](https://i.gyazo.com/3b3df55850151f6ba5b98351634c5bce.png)

Since it runs fine in the normal python compiler, I'm assuming it's an issue with pyinstaller

**Comment by tallforasmurf** [comment]
You are running Python 3.6 -- see #2331.

**Comment by Kaseaa** [comment]
I am aware that pyinstaller isn't officially python 3.6 compatiable, however their working on it and it works on most projects afaik, even in python 3.6. So i thought I should atleast put it up as an issue (especially considering it's dev build)

**Comment by htgoebel** [comment]
@Kaseaa Please make yourself familiar with the github test-editor – the help is hidden behind "Styling with Markdown is supported" just below the edit-box. One simply can not quote images :-)

**Comment by htgoebel** [comment]
Looks like the module "MappingProxyType" is missing. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by Kaseaa** [comment]
MappingProxyType is an import from the types standard library. I tried to recreate this problem using just the std.lib and i found that this code is sufficient to break pyinstaller.
`from types import MappingProxyType`
I tried to hidden import it aswell as use --runtime-hook and hook the types.py file.

Note: I am aware that this issue could be caused by locale types.py files, however it's a single project with no other files in the directory, so that's out of the question.

The actual implementation runs on the python interpreter, which means the code should be runnable

**Comment by tallforasmurf** [comment]
FWIW that does not fail on MacOS.

~~~~
[06:37 /Developer/MISC] cat > testmapping.py
from types import MappingProxyType
[06:37 /Developer/MISC] pyinstaller --version
3.2
[06:37 /Developer/MISC] pyinstaller --log-level=ERROR testmapping.py
[06:38 /Developer/MISC] dist/testmapping/testmapping 
[06:38 /Developer/MISC] 
~~~~

**Comment by Kaseaa** [comment]
@tallforasmurf Could you try it with development build and not the stable one? Also are you running python 3.6(.1)?

**Comment by tallforasmurf** [comment]
I pulled in version 3.3.dev0+abfc80661 and tried again, same result. However, and important, this system is still on Python 3.4.3.  So I tried it again, dev version on a system that has Python 3.5.1, same.

**Comment by htgoebel** [comment]
Please try this:
```
import types
print(repr(types))   # should point to the `types` module in the standard library
from types import MappingProxyType
```

**Comment by Kaseaa** [comment]
It gave me the following

```
<module 'types' from 'D:\\Programming\\Python\\Prosjekter\\Small Programs\\pyinstaller_test\\temp\\dist\\test\\types.pyd'>
Traceback (most recent call last):
  File "test.py", line 3, in <module>
ImportError: cannot import name 'MappingProxyType'
Failed to execute script test
```

**Comment by htgoebel** [comment]
I assume, this `types.pyd` file should not be there.

Please run pyinstaller with `--clean --log-level DEBUG`, which will give you a `xref-x.html` file in the build directory. There you can analyse where this file which module imported this and where it's original location is. If this does not suffice: In the build folder you will find `.toc` files, please try to find this very file there. There must be an entry showing where this file is coming from. I suggest searching in  out*-Analysis.toc first.

**Comment by Kaseaa** [comment]
Found the issue, apperently some old site-packages where leftover from an old python installation(pretty sure it was python 3.6 32 bit aswell). The pyinstaller got the `types.pyd` from `lib/site-packages/win32` for some reason, however after deleting that, aswell as reinstalling pypiwin32 and pyinstaller it works.

**Comment by WonderMr** [comment]
Got the same issue. Anaconda 3.6.4. I was helped by reinstalling pywin32
```
pip uninstall pywin32
pip install pywin32
```
