### ISSUE TITLE
Tests: make use of /var/ramfs on travis

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2668]
I'm not sure where the executables are currently created on travis. However, /var/ramfs is a fake 512MB filesystem that is stored in-memory. Since much of the time spend on executables is disk access, creating the executables in this folder should significantly speed up the tests.

**Comment by xoviat** [comment]
This is currently on hold pending resolution of travis-ci/travis-ci#7979. It may not be possible after all.

**Comment by htgoebel** [comment]
Would have been a good thing.
