### ISSUE TITLE
create executable with python and  Tensorflow framework

### ISSUE THREAD

**Issue by alfredeep** [pyinstaller/pyinstaller#2672]
Hello,

I have a project with python and tensorflow framework for deeplearning and many others modules in ubuntu.
I want create a executable with pyinstaller, it'is possible or no ? 
NB! for excute my project is in command line : python test.py  image_input image_output
How i can convert the total project in executable with pyinstaller and after convert how i used with command line.

Thank you very much

**Comment by tallforasmurf** [comment]
The mailing list is here: https://groups.google.com/forum/#!forum/pyinstaller
that's a better place for "how to" questions.

The manual is here: http://pyinstaller.readthedocs.io/en/stable/
