### ISSUE TITLE
--icon/-i not implementing .ico on OSX

### ISSUE THREAD

**Issue by DylanAlloy** [pyinstaller/pyinstaller#2674]
So disclaimer, this is my first time compiling to a package on OSX using pyinstaller. Done it tons on Windows. Bare with me and I did Google.

So I've got a terminal script I wrote and it works great on its own as a .py file.

I'm doing `pyinstaller script.py -i icon.ico -n name --onefile` with various attempts throwing `--console`, `--nowindowed` and whatnot. Nothing seems to apply the image, it just keeps the default terminal application icon. 

edit: additionally, looking for files in the directory using python as such does not work when it's compiled:

`files = (file for file in os.listdir('./')`
         `if os.path.isfile(os.path.join('./', file)))`

**Comment by tallforasmurf** [comment]
I have an app I build with on OSX with an icon, however the icon file type is `.icns` not `.ico` (which I used on linux and windows).

I believe I started with the graphic I wanted as a .png and used the [GraphicConverter](https://www.lemkesoft.de/en/products/graphicconverter/) app, which allows doing "Save As" to `.ico` and to `.icns` formats.

**Comment by DylanAlloy** [comment]
@tallforasmurf did not resolve the issue :( there is what's called a "Finder-ready" format (.hqx) but its not mentioned in the documentation.

**Comment by dgehlhaar** [comment]
This isn't working for me on Windows. I specify the icon file, it seems to be doing something in the log:

45840 INFO: Updating icons from ['icons\\MVT.ico'] to C:\Users\gehlhaar\AppData\Local\Temp\1\tmp0rqlg56w
45866 INFO: Writing RT_GROUP_ICON 0 resource with 76 bytes
45866 INFO: Writing RT_ICON 1 resource with 296 bytes
45866 INFO: Writing RT_ICON 2 resource with 1384 bytes
45867 INFO: Writing RT_ICON 3 resource with 744 bytes
45867 INFO: Writing RT_ICON 4 resource with 2216 bytes
45867 INFO: Writing RT_ICON 5 resource with 3752 bytes

But I don't see the icon showing up properly.

**Comment by htgoebel** [comment]
`.icn` is a file-extension used for Windows icon-files. For OS X you need a different file-format (`.icns` extension). [Search the web](https://startpage.com/do/search?query=osx%20icons%20.icns) for more information and converters.

**Comment by jonathanmetz** [comment]
@DylanAlloy I'm having the same problem. Did you get it to work?
