### ISSUE TITLE
Unable to make executable with pdbpp and pytest

### ISSUE THREAD

**Issue by durden** [pyinstaller/pyinstaller#2676]
I'm running PyInstaller 3.2.1 with pytest 2.9.2 and trying to make an executable on OS 10.11.6.  I've boiled it down to a simple script:

```
import pytest

def main():
    print 'hi hi'

if __name__ == '__main__':
    main()
```

The exe builds, but I get the following error when running it:

```
Traceback (most recent call last):
  File "broken_cli.py", line 1, in <module>
  File "/private/var/folders/6p/4f79y8156pn1ynxm_x4m5n000000gn/T/pip-build-5APVBf/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/pytest.py", line 17, in <module>
  File "/private/var/folders/6p/4f79y8156pn1ynxm_x4m5n000000gn/T/pip-build-5APVBf/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "site-packages/_pytest/debugging.py", line 3, in <module>
  File "/private/var/folders/6p/4f79y8156pn1ynxm_x4m5n000000gn/T/pip-build-5APVBf/PyInstaller/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
  File "pdb.py", line 4, in <module>
IOError: [Errno 2] No such file or directory: '/Users/durden/Documents/work/engine/dist/pdb.py'
```

**Comment by durden** [comment]
I've tried upgrading to pytest 3.1.2 but the same thing happens.  Here's what I've verified so far:

- pytest.freeze_includes() is being called and gets the following list:

```python
['py.__metainfo',
'py._apipkg',
'py._builtin',
'py._code._assertionnew',
'py._code._assertionold',
'py._code._py2traceback',
'py._code.assertion',
'py._code.code',
'py._code.source',
'py._error',
'py._iniconfig',
'py._io.capture',
'py._io.saferepr',
'py._io.terminalwriter',
'py._log.log',
'py._log.warning',
'py._path.cacheutil',
'py._path.common',
'py._path.local',
'py._path.svnurl',
'py._path.svnwc',
'py._process.cmdexec',
'py._process.forkedfunc',
'py._process.killproc',
'py._std',
'py._xmlgen',
'py.test',
'_pytest._argcomplete',
'_pytest._code._py2traceback',
'_pytest._code.code',
'_pytest._code.source',
'_pytest._pluggy',
'_pytest.assertion.reinterpret',
'_pytest.assertion.rewrite',
'_pytest.assertion.util',
'_pytest.cacheprovider',
'_pytest.capture',
'_pytest.config',
'_pytest.doctest',
'_pytest.genscript',
'_pytest.helpconfig',
'_pytest.hookspec',
'_pytest.junitxml',
'_pytest.main',
'_pytest.mark',
'_pytest.monkeypatch',
'_pytest.nose',
'_pytest.pastebin',
'_pytest.pdb',
'_pytest.pytester',
'_pytest.python',
'_pytest.recwarn',
'_pytest.resultlog',
'_pytest.runner',
'_pytest.skipping',
'_pytest.standalonetemplate',
'_pytest.terminal',
'_pytest.tmpdir',
'_pytest.unittest',
'_pytest.vendored_packages.pluggy']
```

Maybe this an issue with the pytest `pdb.py` and the standard python `pdb.py` having the same name?

**Comment by durden** [comment]
I'm only seeing this issue in OS X.  I've tested it successfully on Windows 7 and CentOS 6/7.

**Comment by durden** [comment]
Started browsing around in my Analysis output and noticed the issue is because I have `pdbpp` installed in OS X and not the other environments:

```
  ('_pytest.pdb',
   '/Users/durden/.virtualenvs/engine/lib/python2.7/site-packages/_pytest/pdb.py',
   'PYMODULE'),
```

and

```
  ('pdb',
   '/Users/durden/.virtualenvs/engine/lib/python2.7/site-packages/_pdbpp_path_hack/pdb.py',
   'PYMODULE'),
```

I uninstalled `pdbb` and everything worked fine.  Is there a way we could add an error or warning when we there are duplicate module names found?  Guessing PyInstaller only includes one of them so this will always be an error if it happens.  This could be pretty tough for users to track down.

What's the policy for dealing with modules that have name collisions?

**Comment by DylanAlloy** [comment]
You're not going to have a good time making a windows .exe with MacOS... it required dlls and redistributables that are usually inside of Windows packages.

**Comment by durden** [comment]
@DylanAlloy I'm not trying to cross-compile an application for Windows on OS X, as far as I know cross-compiling has never been supported with PyInstaller. I've tested the same base script compiling on each OS.  The issue is my OS X setup had a name collision with pdb.py.  This could happen on any Operating System; it's not specific to Windows or OS X.

**Comment by DylanAlloy** [comment]
You said .exe...

Did you mean to say something else? .exe is a windows binary so of course it would not run on a mac

**Comment by durden** [comment]
I'm trying to make an `executable` not specifically a .exe file on OS X.  Guess the title could have been worded better.

**Comment by bwoodsend** [comment]
There's really nothing we can do if modules hack about with `sys.path`. Naming collisions shouldn't cause any issues to PyInstaller because, whilst something will be masked to PyInstaller, that something will be masked to Python too. `pdb` seems to be rather bad for these packaging hacks which is ironic considering that _better packaging_ is what they do...
