### ISSUE TITLE
RuntimeError: error executing torch_shm_manager 

### ISSUE THREAD

**Issue by dthboyd** [pyinstaller/pyinstaller#2688]
If you have problems to get your application running, please first

* try the latest development version, using the following command:

```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If you problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for github's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.

**Otherwise we will not be willed to help you.**

Please mind that PyInstaller is a voluntary project. We spent quite some time
for writing these guides to make both you and us lifes easier. Please
understand that we are not willed to spend our spare time to help you if you
are not willed to help on your side. (Sorry for having to said this, but we
are tired about asking the same question over and over again.)

**Comment by dthboyd** [comment]
RuntimeError: Traceback (most recent call last):
  File "//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 41, in _worker_loop
    samples = collate_fn([dataset[i] for i in batch_indices])
  File "//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 110, in default_collate
    return [default_collate(samples) for samples in transposed]
  File "//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 110, in <listcomp>
    return [default_collate(samples) for samples in transposed]
  File "//anaconda/lib/python3.5/site-packages/torch/utils/data/dataloader.py", line 90, in default_collate
    storage = batch[0].storage()._new_shared(numel)
  File "//anaconda/lib/python3.5/site-packages/torch/storage.py", line 111, in _new_shared
    return cls._new_using_filename(size)
RuntimeError: error executing torch_shm_manager at "//anaconda/lib/python3.5/site-packages/torch/lib/torch_shm_manager" at /Users/soumith/miniconda2/conda-bld/pytorch_1493757035034/work/torch/lib/libshm/core.cpp:125


​

**Comment by htgoebel** [comment]
@dthboyd You added the issue template without any changes, instead or filling it and providing the required information. Due to the total lck of information IÄm closing this now. If you provide the information please feel free to reopen the ticket.
