### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 110: invali d continuation byte

### ISSUE THREAD

**Issue by zaipeng** [pyinstaller/pyinstaller#2693]
The problem happens when I enter command on Windows 7 with PyInstaller: 3.2.1 or PyInstaller: 3.3.dev0+89dc7ebce (It used to work just fine before I upgrade PyInstaller) :

pyinstaller "New_ui_Aerodynamic_design.py" -a -y --clean --debug > output.txt

The error message shown on the screen is attached here:
```
125 INFO: PyInstaller: 3.3.dev0+89dc7ebce
125 INFO: Python: 3.4.4
125 INFO: Platform: Windows-7-6.1.7600-SP0
125 INFO: wrote Z:\BTSync\PyCode\proj12C\New_ui_Aerodynamic_design.spec
140 INFO: UPX is not available.
…
75890 INFO: Loading module hook "hook-zmq.py"...
…
  File "c:\python34\lib\site-packages\PyInstaller\hooks\hook-zmq.py", line 18, in <module>
    hiddenimports.extend(collect_submodules('zmq.backend'))
  File "c:\python34\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 619, in collect_submodules
    repr(pkg_dir), package))
  File "c:\python34\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 90, in exec_statement
    return __exec_python_cmd(cmd)
  File "c:\python34\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 77, in __exec_python_cmd
    txt = exec_python(*cmd, env=pp_env)
  File "c:\python34\lib\site-packages\PyInstaller\compat.py", line 539, in exec_python
    return exec_command(*cmdargs, **kwargs)
  File "c:\python34\lib\site-packages\PyInstaller\compat.py", line 346, in exec_command
    out = out.decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 110: invalid continuation byte
```

**Comment by htgoebel** [comment]
What exactly does "before I upgrade PyInstaller" mean?

Hmm, this comes down to this: The code used to search the submodules, for some reason when run returns non-valid UTF-8 data.

Please try:
1. Use a *minimal* program consisting of only `import zmq`. This should show the same error.
2. Adding `import pdb; pdb.set_trace()` to `c:\python34\lib\site-packages\PyInstaller\compat.py` just before line 346.
3. Run pyinstaller and when the debugger triggers (called be the hook), inspect `out`. This should contain the illegal character.

**Comment by zaipeng** [comment]
"before I upgrade PyInstaller" means I was using an older version of PyInstaller and it worked just fine. This problem came up after I upgraded PyInstaller to the latest version.

I have tried the steps as you suggested and the results are:
1. Yes,  the same error occurred.
2. It started the pyinstaller and the Windows command prompt shows the follow messages:
Z:\>pyinstaller testPyinstaller.py -a -y --clean --debug > output.txt
151 INFO: PyInstaller: 3.3.dev0+89dc7ebce
152 INFO: Python: 3.4.4
153 INFO: Platform: Windows-7-6.1.7600-SP0
156 INFO: wrote Z:\BTSync\PyCode\proj12C\testPyinstaller.spec
163 INFO: UPX is not available.
165 INFO: Removing temporary files and cleaning cache in C:\Users\zaipeng\AppDat
a\Roaming\pyinstaller
184 INFO: Extending PYTHONPATH with paths
['Z:\\BTSync\\PyCode\\proj12C', 'Z:\\BTSync\\PyCode\\proj12C']
190 INFO: checking Analysis
192 INFO: Building Analysis because out00-Analysis.toc is non existent
193 INFO: Initializing module dependency graph...
208 INFO: Initializing module graph hooks...
214 INFO: Analyzing base_library.zip ...

now it has been keeping at this state for hours...

The output.txt shows the following information:

> c:\python34\lib\site-packages\pyinstaller\compat.py(348)exec_command()
-> out = out.decode(encoding)
(Pdb)

**Comment by zaipeng** [comment]
I reinstalled Anaconda3-4.3.1-Windows-x86_64bit and PyInstaller: 3.3.dev0+89dc7ebce on a brand-new Window7 OS on VMware Workstation. Then, I executed the script "pyinstaller testPyinstaller.py -a -y --clean --debug > output.txt"

This time it worked fine and no error was reported.

**Comment by htgoebel** [comment]
> Z:>pyinstaller testPyinstaller.py -a -y --clean --debug > output.txt
…
> now it has been keeping at this state for hours...
>
>The output.txt shows the following information:
>
>> c:\python34\lib\site-packages\pyinstaller\compat.py(348)exec_command()
>-> out = out.decode(encoding)
>(Pdb) 

Of course you must *not* redirect the output when you want to use the debugger.

Anyway:
> I reinstalled … This time it worked fine and no error was reported.

I assume this was a problem with your installation.
