### ISSUE TITLE
Out of the blue: OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'

### ISSUE THREAD

**Issue by equihuam** [pyinstaller/pyinstaller#2695]
I am really puzzled by this error. The script I am packing runs perfectly on my PC (Windows 10, Python 3.5 - 64, Anaconda). **pyinstaller** run all the way until:
`121789 INFO: Building COLLECT out00-COLLECT.toc completed successfully.`
Then I try the exe file and I get this error message that refers to the Crypto module I am not using and as far as I can tell neither is called by any of the libraries I am calling, and in any event the missing module should show when running in my machine, and such error is not reported anywhere:

> `import wx`
> `#### begin wxGlade: dependencies`
> `import gettext`
> `import os`
> `import re`
> `import csv`
> `import subprocess`
> `import bs4`
> `import shutil`
>
> `from io import StringIO`
> `from pdfminer.pdfinterp import PDFResourceManager, PDFPageInterpreter`
> `from pdfminer.converter import TextConverter`
> `from pdfminer.layout import LAParams`
> `from pdfminer.pdfpage import PDFPage`

So, I really not know where to seek for help, but the use of **pyinstaller** is what is showing the problem!!!! I tried the developer version, and the problem remains. So.... I am really lost!!!! The last few lines of the attempt to run the frozen script are these:

>   `File "site-packages\Crypto\Cipher\__init__.py", line 78, in <module>`
>   `File "<frozen importlib._bootstrap>", line 969, in _find_and_load`
>   `File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked`
>   `File "<frozen importlib._bootstrap>", line 673, in _load_unlocked`
>   `File "c:\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module exec(bytecode, module.__dict__)`
>   `File "site-packages\Crypto\Cipher\_mode_ecb.py", line 46, in <module>`
>   `File "site-packages\Crypto\Util\_raw_api.py", line 171, in load_pycryptodome_raw_lib`
> `OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'`
> `Failed to execute script IPBES_Mineria_PDF`
> `LOADER: OK.`
> `LOADER: Cleaning up Python interpreter.`

Any help to understand this will be most appreciated.

**Comment by pupattan** [comment]
I am also facing same issue. Any update on this ?

**Comment by htgoebel** [comment]
Some of the packages you use imports Crypto.Cipher. Look at the trace back to see which one it is.

**Comment by yooongchun** [comment]
I also have the same trouble!  Have you solved it?
