### ISSUE TITLE
Put all data into a sub-directory?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2702]
```
rm -rf build/ dist/
echo "import pytz" > test.py
pyinstaller.py test.py --clean --name pytz
```
crashes with
```
8898 INFO: Building COLLECT because out00-COLLECT.toc is non existent
8898 INFO: Building COLLECT out00-COLLECT.toc
Traceback (most recent call last):
…
  File "…/Python.framework/Versions/3.5/lib/python3.5/os.py", line 241, in makedirs
    mkdir(name, mode)
NotADirectoryError: [Errno 20] Not a directory: '/private/tmp/pyinst/dist/pytz/pytz/zoneinfo'
```
This is caused by the executable having the same name as the data-directory (`pytz`). See #2697.

The only solution I can think about is to put all data into some sub-directory. Then the name of this sub-directory could be make configurable. I'm not clear in my mind about the implications of such a change.

**Comment by kratzert** [comment]
Was having the same problem and want to add that it seems like this is only an issue on Linux (maybe macOS, can't test this) but not on Windows (at least Win 10). I'm comparing similar Python environments, so this shouln't be any issue.

**Comment by marioortizmanero** [comment]
This will happen when both the generated binary and the directory you want to create have the same name. In Unix, there can't be a directory and a file with the same name at once, so it prints an error.
