### ISSUE TITLE
Vagrant box boxcutter/debian82 no longer exists

### ISSUE THREAD

**Issue by jck** [pyinstaller/pyinstaller#2704]
This is the box used to build the bootloader. It appears to have been renamed to boxcutter/debian8

**Comment by htgoebel** [comment]
Shouldn't we take the chance and go to Debian 9 then?

**Comment by htgoebel** [comment]
[Looks](https://github.com/boxcutter/debian) like Debian 9 is not yet available. Also so https://app.vagrantup.com/boxes/search?utf8=%E2%9C%93&sort=downloads&provider=&q=boxcutter+debian.

So I'll change the box to be used to "debian8" for now.
