### ISSUE TITLE
ImportError: DLL load failed: Invalid access to memory location

### ISSUE THREAD

**Issue by ReddyKilowatt** [pyinstaller/pyinstaller#2705]
Using Python 2.7.13 on Windows 7 Professional, 64-Bit
After bundling my app with pyinstakker with UPX compression,

when importing SimpleXMLRPCServer, 
the following exception is thrown:

``Traceback (most recent call last):
  File "upx_bug.py", line 6, in <module>
  File "C:\ProgramData\Anaconda2\envs\py27dbg_pyinstaller\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "SimpleXMLRPCServer.py", line 102, in <module>
  File "C:\ProgramData\Anaconda2\envs\py27dbg_pyinstaller\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "xmlrpclib.py", line 143, in <module>
  File "C:\ProgramData\Anaconda2\envs\py27dbg_pyinstaller\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "socket.py", line 47, in <module>
  File "C:\ProgramData\Anaconda2\envs\py27dbg_pyinstaller\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 688, in load_module
    module = imp.load_module(fullname, fp, filename, ext_tuple)
ImportError: DLL load failed: Invalid access to memory location.
Failed to execute script upx_bug
``

In order to see which file had the import error, I've added a simple print() statement
on line 687 of C:\ProgramData\Anaconda2\envs\py27dbg_pyinstaller\lib\site-packages\PyInstaller\loader\pyimod03_importers.py

Line 687:
print('TONY DEBUG: fulname={0}, filename={1}'.format(fullname, filename))

TONY DEBUG: fulname=_ctypes, filename=C:\Users\z48176zz\AppData\Local\Temp\_MEI99~1\_ctypes.pyd
TONY DEBUG: fulname=_socket, filename=C:\Users\z48176zz\AppData\Local\Temp\_MEI99~1\_socket.pyd

>>Does the error occur when bundling the application or when running it?
running

>>If you have an import error, please submit the last part of the traceback. This helps a lot to see which >>modules tried to import which other one.
See above

>>Is there anything striking in the debug-output? 
Not from what I can see.

Python 2.7.13 |Anaconda 4.4.0 (32-bit)| (default, May 11 2017, 14:07:41) [MSC v.1500 32 bit (Intel)] on win32

Pyinstaller:
Pyinstaller 3.2.1

OS:
Windows 7 Pro, 64-Bit

The exe of my app was created using pyinstaller -F

gist with source & logs
https://gist.github.com/ReddyKilowatt/a9b4f476c3c50c4e9de92b399d0286aa

**Comment by htgoebel** [comment]
Thanks for you bug report. According to you description this error occurs when UPX, but doe not occur when not using UPX. Right? So I'm afraid, this is not really related to PyInstaller but to UPX. Please see https://github.com/upx/upx/issues/107 and #2659.

I'm closing this now. If I understood you wrong, please feel free to reopen and provide more insights.

**Comment by ReddyKilowatt** [comment]
Hello Hartmut,

>>but doe not occur when not using UPX. Right?
Correct.

I did forget to mention that the error does not occur if I use Python 3,
even though the upx version
is the same as I used with Python 2.

I will open a bug report in upx then.

thanks

Tony

**Comment by htgoebel** [comment]
> I did forget to mention that the error does not occur if I use Python 3,

Not all .dlls are effected by this problem – many are (de)compressed well, a few fail. For the bug-report at upx, this information and the differences between 2.7 _socket.pyd and the 3.x version could be helpful. You may want to ask there whether to attach both binaries to the ticket.
