### ISSUE TITLE
App built on Ubuntu 14.04 segfaults on 16.04

### ISSUE THREAD

**Issue by jck** [pyinstaller/pyinstaller#2707]
We are building a PySide application on Travis CI - Ubuntu 14.04

The build succeeds, and works on Ubuntu 14.04. However, it segfaults on 16.04 when run as an unprivileged user:

```
Program received signal SIGSEGV, Segmentation fault.
0x00007ffff7624428 in __GI_raise (sig=11)
    at ../sysdeps/unix/sysv/linux/raise.c:54
54	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
```

However, the built version works as unprivileged user on Archlinux or as root on Ubuntu 16.04

I have tried with Pyinstaller 3.2.1. and development version.

## Pyinstaller 3.2.1
Build Log: https://travis-ci.org/swift-nav/piksi_tools/jobs/258006782
Artifact: https://s3-us-west-2.amazonaws.com/console-ci-builds/swift-nav/piksi_tools/1794/1794.1/console/pyinstaller/dist/swift_console_v1.1.13.dev60%2Bg91238b2_linux.tar.gz

## pyinstaller @ 84efdf6 
Build Log: https://travis-ci.org/swift-nav/piksi_tools/jobs/258652408
Artifact: https://s3-us-west-2.amazonaws.com/console-ci-builds/swift-nav/piksi_tools/1798/1798.1/console/pyinstaller/dist/swift_console_v1.1.13.dev61%2Bg3ecb9e2_linux.tar.gz

**Comment by htgoebel** [comment]
Are you sure these are the correct build logs? Both build did pass and I was not able to find "SIGSEGV" in the raw logs.

**Comment by jck** [comment]
The builds pass, the problem is that the application segfaults when run on Ubuntu 16.04

**Comment by htgoebel** [comment]
IC. Why you are pointing to the travis logs then if they are not containing any relevant information? (I know, I asked for them when I asked you to open a separate issue for this. But you already pointed to some travis build there.)

Please provide more informaion. Otherwise we have no chance to reproduce anything.

**Comment by jck** [comment]
I apologize for not being clear earlier.

The executable generated by a successful build on Ubuntu 14.04 fails to run on Ubuntu 16.04. However, the executable works as root on Ubuntu 16.04. The gdb output is included in the first post.

Please let me what additional information you need.

**Comment by htgoebel** [comment]
The Segmentation fault you posted first is not pointing to anything I've ever seen in PyInstaller. So I don't think this is related to PyInstaller. Have you ever tried running your program *unfrozen* on Ubuntu 16.04?

**Comment by jck** [comment]
By trial and error, I found that I need to bundle three additional libraries for the frozen app to work on Ubuntu 16.04 - 'libgtk-x11-2.0.so.0', 'libgio-2.0.so.0', 'libatk-1.0.so.0'. As far as I can tell, none of the pyside libraries actually link to these libraries and there is nothing PyInstaller can do to work around this.

**Comment by htgoebel** [comment]
But it is curious: Why should PySide require the lib? all three are GTK related AFAIK, and not Qt related.

**Comment by jck** [comment]
In ubuntu 16.04, the default qt4 style is gtk. This requires the above libraries.

**Comment by htgoebel** [comment]
Rethinking this I don't think we should unconditionally include the libs you found to be needed.

Any other idea? WIki-Reciept?

BTW: Next time you have such issues, I strongly suggest using `strace`.

**Comment by drewm1980** [comment]
I ran into this same segfault when building and deploying on the same Ubuntu 16.04 machine. The build was in an encfs encrypted folder with a conda environment enabled. I think I have at least one Qt related dependency through vispy; not sure which flavor of Qt binding is getting pulled in, though. 

All three of libraries listed above by @jck are present in my Ubuntu 16.04 installation. I happen to also have a libgio-2.0.so.0 in my conda environment. libgtk-x11-2.0.so.0 was the only library of the threee that wasn't already present in the frozen application directory. Copying it into the frozen application's directory didn't help. "source deactivate" to disable my conda environment didn't help either.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved. Otherwise please try PyInstaller v3.4 and the current development version.
