### ISSUE TITLE
Trying to get the icon to work properly

### ISSUE THREAD

**Issue by FineMoss** [pyinstaller/pyinstaller#2714]
pyinstaller built my code correctly and everything is working fine, with the exception the -icon tag when building my application.

I am building with python 3.6.2 and the latest version of pyinstaller.

pyinstaller myapp.py -n name -F -w -i icon.ico

also tried

pyinstaller myapp.py -n name -F -w -icon icon.ico

When I check the dist folder the icon shows up but when I distribute the single .exe file (even to another folder) the icon reverts back to the pyinstaller default.

small issue, yes. But any help would be appreciated

**Comment by tallforasmurf** [comment]
One, you don't mention the platform. Very different implementations. Two, there are two dashes before --icon, although the -i should have worked. Three, Python 3.6 is not yet supported, can you try with 3.5?

**Comment by Jakedjoe** [comment]
The platform is windows 10. (The .exe should have hinted)
I tried it with --icon, above was a typo. 
I don't think the version of python is the issue.

Like I said before, everything works how it is suppose to. After the build the icon appears in the final .exe as long as it's in the dist folder. Once I take it out of that folder the icon reverts back to the default.

**Comment by grajsor** [comment]
Pretty sure the version of python "matters" when you are using an
unsupported version. Try with 3.5.

**Comment by Jakedjoe** [comment]
I'm not using any depandacies from 3.6. I could compile with 2.7 if I wanted. That isn't the issue. The program runs fine. It's literally just the icon. And only when I take it out the dist folder. Even if I make a shortcut to the program, the icon will show up. But once I move the deliverable elsewhere it reverts back to the default.

**Comment by grajsor** [comment]
Awesome, then try it with Python 2.7 and PyInstaller 3.2.1 and see if it
works.

**Comment by htgoebel** [comment]
I assume, this is related to #870 (for which a pull-request is appreciated).

**Comment by htgoebel** [comment]
Questions: Does this occur only on Windows 10 or also when moving the .exe to e.g. Windows 7?

**Comment by Jakedjoe** [comment]
Correct me if I am wrong, but it shouldn't matter which version of python I am using to test my program... I would assume pyinstaller has its own built in compiler that compiles the code in its own version of python... So I am very confused when you say "try a different version of python"

**Comment by Jakedjoe** [comment]
The icon works properly with windows server 2008

**Comment by skys215** [comment]
My icon is not working properly too.
I'm also in Windows 10 with Python3.5.

There was few times pyinstaller packed icon properly with same/not same configuration, I'm not sure.

**Comment by Jakedjoe** [comment]
My problem has been localized to only the desktop (windows 10). That is the only place the icon does not work. It works on the windows server 2008 desktop.

**Comment by skys215** [comment]
I tried again, and seems icon was set properly after I pass the ABSOLUTE path of the .ico file.
But my resource files is not working. It's not a icon problem, so I'll search around for the solution for the resource file.

**Comment by htgoebel** [comment]
@Jakedjoe The version oy Python does *not* matter since the bootloader is the same for all versions and PyInstaller behaves (almost) the same, too.

It looks like this is a new behavior in Win10 then. If one/some of you could investigate what is the root cause for this, this would be great.

**Comment by Jakedjoe** [comment]
@htgoebel I did some more digging and It seems the problem was with my .ico file. That being said I tried to use a new .ico... When I build with the same -n name, the final .exe has the same logo as before. I tried building with --clean and that did not help. The only thing that worked was giving the -n name a new name like -n name2 .

This is even happening when I remove the build and dist folder along with the old .ico. This problem has more even more puzzled.

**Comment by htgoebel** [comment]
@Jakedjoe Maybe you want implement #870 (Do not have a default-icon in the bootloader, add it when freezing), which for a windows developer should be easy.

**Comment by nikhilkotian22** [comment]
@FineMoss I find this workaround to work (i.e. -n name2). Confusing!

**Comment by richardwesthaver** [comment]
sorry I'm late to the party.. I found the root cause though: this isn't an issue with pyinstaller, it's just windows caching the icon. To delete the windows explorer icon cache you can just delete all the 'iconcache' files in \User\AppData\Local\Microsoft\Windows\Explorer and refresh windows explorer. If you're changing icons a lot you can also just r-click the .exe generated > Properties > see the icon applied in the General tab

**Comment by htgoebel** [comment]
@richardwesthaver Thanks for investigating. For the records:

### This isn't an issue with PyInstaller, it's just windows caching the icon.
To delete the windows explorer icon cache you can just delete all the 'iconcache' files in \User\AppData\Local\Microsoft\Windows\Explorer and refresh windows explorer. If you're changing icons a lot you can also just r-click the .exe generated > Properties > see the icon applied in the General tab

**Comment by sudofox** [comment]
@FineMoss Thank you, this workaround fixes the issue for me as well!

**Comment by sunsudio** [comment]
Still, the same issue with the icon not showing in the desktop and @FineMoss workaround help me!

**Comment by riverbr** [comment]
> 
> 
> @htgoebel I did some more digging and It seems the problem was with my .ico file. That being said I tried to use a new .ico... When I build with the same -n name, the final .exe has the same logo as before. I tried building with --clean and that did not help. The only thing that worked was giving the -n name a new name like -n name2 .
> 
> This is even happening when I remove the build and dist folder along with the old .ico. This problem has me even more puzzled.

did exactly the same thing, changing the -n to my app name and it works.
ex: pyinstaller pyfile -w -i "icon_name.ico" -n app_name

**Comment by rod-hendricks** [comment]
I have been trying for a while and I can't seem to get the .ico file to work on Ubuntu 18.04. I have no issues with it when using it for Windows 10. Is there something special i need to do in ubuntu to have this working well for me?

**Comment by Avasam** [comment]
> I have been trying for a while and I can't seem to get the .ico file to work on Ubuntu 18.04. I have no issues with it when using it for Windows 10. Is there something special i need to do in ubuntu to have this working well for me?

@rod-hendricks  I am no professional on the matter. But my understanding is that the GNOME desktop stores file icons separately, so there's no way really to ship an executable file with an icon. At best you could set the app's own icon during boot using `gio set path-to-your-app metadata::custom-icon file://path-to-icon`

**Comment by bwoodsend** [comment]
Avasam is correct. There is no such thing as icons for UNIX executables hence the `--icon` option does nothing on Linux. Instead you have [.desktop](https://www.baeldung.com/linux/desktop-entry-files) files which act like a desktop/start menu/dock menu shortcut on desktop environments.
