### ISSUE TITLE
Windows 10 Python 3.5 --onefile -w and --icon= do not work.

### ISSUE THREAD

**Issue by mapircamera** [pyinstaller/pyinstaller#2721]
Hello, I've gone through all of the troubleshooting steps I could find. I successfully used the onefile and no window options on windows 8, but I can't seem to get them to work now that I've upgraded to windows 10.

I have tried both the latest stable and latest dev releases. I've also run this on Mac and Linux with the same versions without any luck.

Also as a side note, the "_gdal" module is still not being found in the osgeo hook.

**Comment by Jakedjoe** [comment]
I've had great success using those tags with windows 10. Make sure you get rid of the old build folders and .spec file when you rebuild, I found that this helps. Also look at the .spec and see if those tags are actually being used..  (console=False , icon='MyIcon.ico').

**Comment by jftuga** [comment]
Try adding --noupx. If that does not work, then try the --noupx without the -w

**Comment by htgoebel** [comment]
@mapircamera Any news?

**Comment by htgoebel** [comment]
I'm closing this ticket. Feel free to re-open it, when adding the requested information.
