### ISSUE TITLE
notice: tar.bz2 has been deprecated

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2724]
From the [PEP 527](https://www.python.org/dev/peps/pep-0527/)
> Looking at the three extensions we do have in current use, it's also fairly easy to conclude that .tar.bz2 can be disallowed as well. It has a fairly small number of files ever uploaded with it and it requires an additional optional C library to handle the bzip2 compression.

**Comment by xoviat** [comment]
I do not think @htgoebel will be able to upload these files for the next release.

**Comment by htgoebel** [comment]
Thanks for the info.

**Comment by htgoebel** [comment]
This PEP also [says](https://www.python.org/dev/peps/pep-0527/#limiting-number-of-sdists-per-release):
>Having multiple sdists often times can account for strange bugs that only expose themselves based on which sdist that the person used.
>
> This PEP proposes to allow one, and only one, sdist per release of a project.

So the question is: should we also only provide a single sdist at github? I can not remember we ever experienced any problem depending on the sdist. OTOH the argument true for github, too, and having only one sdist simplifies the release process.

So I'd restrict the releases to sdist .tar.gz and bdist wheel.

What do you think?

**Comment by xoviat** [comment]
`bdist_wheel` will not work wiith our `setup.py` for distribution. I never used the github source distributions; I don't even think you need to upload them because github autogenerates a copy.

**Comment by htgoebel** [comment]
> bdist_wheel will not work wiith our setup.py for distribution

Hmm, I was able to generate a wheel using `python setup.py bdist_wheel`. What did I miss?

Releases autogenerated by github are not signed. Since we use github's release list as an archive, we should upload all files here. The question for me is: do we still need a zip?

**Comment by xoviat** [comment]
To generate a wheel that can be used for distribution, you must correctly specify environment markers in `setup.py` and you MUST use the latest version of setuptools.

**Comment by xoviat** [comment]
See pypa/setuptools#1108

**Comment by apatrushev** [comment]
Is this the only issue left for the 3.3 release? Could someone (me or anyone else) helps with it? I think that 3.3 release is really important for the community because of support of py3.6.

**Comment by htgoebel** [comment]
Am 19.09.2017 um 14:59 schrieb Anton Patrushev:
>
> Is this the only issue left for the 3.3 release? Could someone (me or
> anyone else) helps with it? I think that 3.3 release is really
> important for the community because of support of py3.6.
>
This is already done on my private release branch. I Just need to find a
few hours to actually release.

If you have a company: what about granting a few development days?

**Comment by htgoebel** [comment]
Done in 5c1628e66e18e2bb1c44faa88387b1f627181b43.
