### ISSUE TITLE
Pyinstaller combined with os.execl to restart itself behaves oddly

### ISSUE THREAD

**Issue by gregoff82** [pyinstaller/pyinstaller#2726]
Hi,

I'm using Python 2.7 together with Pyinstaller 3.2.1

When using os.execl the following way:
`os.execl(sys.argv[0], sys.argv[0], * sys.argv)`
The command results in an another thread but is supposed to replace the current thread. 

How should the arguments look like in order to allow the binary to restart itself?

The binary has been compiled the following way:
`python ~/PyInstaller-3.2.1/pyinstaller.py --onefile ~/script.py`

The binary is run by:
`nohup /path/to/binary &`

**Comment by tallforasmurf** [comment]
Is any of [this info](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing) relevant?

**Comment by gregoff82** [comment]
Hi,

I'm not sure of what you mean. I'm using linux and not the multiprocessing module

**Comment by htgoebel** [comment]
Please read the manual:
* http://pyinstaller.readthedocs.io/en/stable/runtime-information.html?highlight=ld_library_path#ld-library-path-libpath-considerations 
* http://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html?highlight=ld_library_path
