### ISSUE TITLE
pip fails to install pyinstaller - "No module named 'PyInstaller'"

### ISSUE THREAD

**Issue by LeftyAce** [pyinstaller/pyinstaller#2730]
Hi all,

I am trying to install pyinstaller, and am getting the following error:
```

C:\Users\Lefty\WinPython-64bit-3.6.0.1Qt5\python-3.6.0.amd64> pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Downloading https://github.com/pyinstaller/pyinstaller/archive/develop.zip (4.0MB)
    100% |████████████████████████████████| 4.0MB 241kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Lefty\AppData\Local\Temp\pip-ryy4ly_2-build\setup.py", line 16, in <module>
        from PyInstaller import (__version__ as version, is_linux, is_win, is_cygwin,
    ModuleNotFoundError: No module named 'PyInstaller'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\Lefty\AppData\Local\Temp\pip-ryy4ly_2-build\
```

It seems like the pyinstaller installer can't find pyinstaller during the installation. I tried this with just 
`pip install pyinstaller` as well as the github option above.

My python installation is WinPython, installed on a Windows 10 machine if that makes a difference.

Any suggestions much appreciated!

**Comment by htgoebel** [comment]
Can you please try this:
- unzip the [archive](https://github.com/pyinstaller/pyinstaller/archive/develop.zip)
- cd into that directory
- `pip install .`

If this fails, add this line near the top of setup.py `import sys; print(sys.path)` and run `pip install .` again. The first element should be `''` – or at least there should be such an element in the list.

**Comment by htgoebel** [comment]
I had this problem just yesterday when I tried running the test-suite via tox. I found that I had several "pointers" to PyInstaller hanging around in site-packages. There was a `.egg-link` and also an entry in one of the `.pth` files.

HTH

**Comment by htgoebel** [comment]
Did this help? I want to close the issue.

**Comment by htgoebel** [comment]
I'm closing this ticket. Feel free to re-open it, when adding the requested information.

**Comment by derula** [comment]
I have the same issue trying to install PyInstaller with the Windows embedded version of Python.

This is the output you asked for:

```
['C:\\<user dir>\\<project folder>\\python\\python37.zip', 'C:\\<user dir>\\<project folder>\\python']
```

It took me a while to figure out that the embedded version ignores `PYTHONPATH` etc. and just uses the settings from `python37._pth`, which is:
```
python37.zip
.

# Uncomment to run site.main() automatically
#import site
```

So it makes sense at least while the `sys.path` looks like this...

**Comment by htgoebel** [comment]
Well, I'd say, "embedded Python" is not a development platform.

**Comment by derula** [comment]
Well, I was probably doing it wrong, but my intent in doing so was to build a Windows-targeted deployable application from my mostly *nix-flavored development environment, while making sure that the Python used to build the application is the same as what's running on the target system, and all that without writing how-to guides for future developers to inform them of how to set up the right Python environment.

I found a different solution now, I just thought this information might be useful to address an actual bug. Feel free to ignore it if it's not :)

**Comment by htgoebel** [comment]
@derula  Cross-building from windows to linux (and vice-vresa) is only possible when using virtual machines, docker, etc. - as stated in the manual or wiki.

**Comment by derula** [comment]
I wasn't trying to cross-build :) anyway, it doesn't matter, since I found a solution that worked for me.

**Comment by kjanko** [comment]
Can confirm here as well, unable to install with pip19.0

**Comment by htgoebel** [comment]
@rt121212121 @jeanlaroche @kjanko As this happens after updating pip and nothing changed for PyInstaller you should report this bug tip pip, shoulnt't you?
