### ISSUE TITLE
Problem with ssl.py import

### ISSUE THREAD

**Issue by tangb** [pyinstaller/pyinstaller#2737]
Hi

I'm trying to make distributable my application and I'm facing a problem when I try to launch generated stuff on other computer. I got this error:
```
tang@tangdesktop:[temp/cleep-desktop]> ./cleep-desktop                                                                                                                                          14:20 Fri 11/08/2017
2017-08-11 14:20:18,848 Cleep-desktop.<module> +28: INFO     [15088] Config file location: <built-in method fileName of QSettings object at 0x7fec71dbc438>
2017-08-11 14:20:18,849 Cleep-desktop.<module> +54: DEBUG    [15088] Launch processes
Traceback (most recent call last):
  File "rpcserver", line 4, in <module>
    from cleep import rpcserver
  File "/home/tang/temp/cleep-desktop/cleep/rpcserver.py", line 17, in <module>
    from gevent import monkey; monkey.patch_all()
  File "/home/tang/.local/lib/python3.5/site-packages/gevent/monkey.py", line 621, in patch_all
    patch_ssl()
  File "/home/tang/.local/lib/python3.5/site-packages/gevent/monkey.py", line 463, in patch_ssl
    patch_module('ssl')
  File "/home/tang/.local/lib/python3.5/site-packages/gevent/monkey.py", line 152, in patch_module
    gevent_module = getattr(__import__('gevent.' + name), name)
  File "/home/tang/.local/lib/python3.5/site-packages/gevent/ssl.py", line 23, in <module>
    from gevent import _ssl3 as _source # pragma: no cover
  File "/home/tang/.local/lib/python3.5/site-packages/gevent/_ssl3.py", line 13, in <module>
    import ssl as __ssl__
  File "/usr/lib/python3.5/ssl.py", line 102, in <module>
    from _ssl import _SSLContext, MemoryBIO
ImportError: cannot import name 'MemoryBIO'
2017-08-11 14:20:19,354 Cleep-desktop.<module> +70: INFO     [15088] One of process is terminated. Stop application
2017-08-11 14:20:19,354 Cleep-desktop.<module> +89: INFO     [15088] Cleep-desktop terminated
```
What is shocking me is gevent module is loading ssl.py from local path instead of lib packaged by pyinstaller ("/usr/lib/python3.5/ssl.py", line 102). I think this file was missing but the problem is I don't understand why (gevent is packaged).

Here is what I tried to do to fix that:
- add in hiddenimports spec file variable 'ssl' and '_ssl'
- try to use hooks (but I think it's not the way to do because hooks are used when launching application not when building package)
- add useless import of ssl in main Analysis file
- some others i don't remember
But nothing. Now this issue is driving me nuts after 2 days finding a way to fix that :(

Other weird think according to my app output is decompressed pyinstaller files are located in "/home/tang/.local/lib/python3.5" while in my building environment is only have python3.4 installed (to confirm that I got libpython3.4m.so.1.0 on dist dir). But python3.5 is the version installed on my run test computer.

**Several extra infos:**
My application has a bottle server and a pyqt5 app running at the same time. Both of these apps communicates by socket.
I configured main entry of my spec file with the launcher python script (that init default config, launch rpc and ui processes using submodule and monitor end of one of them to kill the other). So I don't know if pyinstaller is able to parse those 2 "external" programs.

Here some files:
- My [build.log](https://gist.github.com/tangb/b9910ace0fdf030f16d586a1e74373ad) file with pyinstaller log level in debug
- my [spec file](https://gist.github.com/tangb/1c0f18e7699f402a6ca3ab25bb9e7a94)
- [content](https://gist.github.com/tangb/f84db8b1ab85407fc8eb19d0b18d7d02) of dist/cleep-desktop dir
- dev computer installed [pip modules](https://gist.github.com/tangb/b242d2d27728a3eba9b3e800e5167176)

For now I'm running under debian (not ubuntu) version. My dev computer is stable version while test computer is running debian testing. But I intend to deploy my app at least on windows.

Thank you very much for your help.

**Comment by tangb** [comment]
I'm running latest pyinstaller release
> pyinstaller -v
> 3.2.1

Is it missing files or problem with OS version? I got this problem when I run pyinstaller generated package (from debian jessie 8.9) onto debian testing (buster)

Nobody got this problem ?
Nobody can help me investigating? snif :cry:

**Comment by htgoebel** [comment]
This looks more like some problem on your system. The `_ssl.so` is included in your dist-directory and this is the one raising the error. The error is *not* "Can't import _ssl", but the error is "Can't import name …".

Have you tried building a *minimal* example? E.g. only importing ssl? Or only `from gevent import monkey; monkey.patch_all()`

**Comment by tangb** [comment]
Hi and first of all thank you for your help :smile: 

I just working on it and I completely reinstall Qt to latest one (5.9.1) followed by PyQt. This removed my nss and opengl issues.

I also patched manually installed pyinstaller files according to [this patch](https://github.com/pyinstaller/pyinstaller/pull/2514/files#diff-254d289fadd12387346b09de164c9321R26) because I encountered ICU errors.

But now I got this error
> ./cleep-ui                                         21:41 Tue 22/08/2017
> This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".
> Reinstalling the application may fix this problem.
> zsh: abort      ./cleep-ui
I saw there is [an issue](https://github.com/pyinstaller/pyinstaller/issues/1906) already opened about that but unfortunately no solution yet.

Maybe you can help me ?

Thanks again

**Comment by tangb** [comment]
Here is my build file that add some extra files to dist directory as adviced [here](https://github.com/pyinstaller/pyinstaller/issues/1930) to fix opengl issues and my new spec files [file1](https://gist.github.com/tangb/ff9b694ec523e407b3715bf4acc526bc) [file2](https://gist.github.com/tangb/fe35b1fb84cb59fcc7ba4ab7893fd771)

**Comment by htgoebel** [comment]
Just discovered that you are using v3.2.1. The very first advice in out "If thinks go wrong" guide is : Use the recent development head. There has been some work on QT plugins recently.

**Comment by tangb** [comment]
I installed pyinstaller dev version (PyInstaller: 3.3.dev0+e05a2cf10), relaunched my script [build.sh](https://gist.github.com/tangb/caa0a8e323a8f863642f027a1d531e20) and I encountered again NSS issue.

I tested on [small sample](https://gist.github.com/tangb/ddb22745e67fa3895e1a8a841f56af23) and it's the same problem
> [18659:18683:0824/114845.374627:ERROR:nss_util.cc(712)] Error initializing NSS with a persistent database (sql:/home/tbonneau/.pki/nssdb): NSS error code: -8023
> [18659:18683:0824/114845.374760:ERROR:nss_util.cc(201)] Error initializing NSS without a persistent database: NSS error code: -8023
> [18659:18683:0824/114845.374775:FATAL:nss_util.cc(203)] nss_error=-8023, os_error=0

Launching application directly from command line works perfectly (python3 test.py)

Somebody can test my sample?
Maybe it's something weird on my host, but I have chrome (not chromium) running well.

My env:
- Python3.4
- Pyinstaller 3.3dev
- PyQt 5.9
- Qt 5.9.1
- Debian 8.9 (old stable)

**Comment by htgoebel** [comment]
> Error initializing NSS without a persistent database: 

This sounds like some cert-db is missing. Please run the frozen app under control of `strace -e trace=file`.

**Comment by htgoebel** [comment]
> Error initializing NSS without a persistent database: 

This sounds like some cert-db is missing. Please run the frozen app under control of `strace -e trace=file`.

> I tested on small sample and it's the same problem

I can not spot any SSL in this example, nor any NSS. Please try to strip this down to not use any Qt. For implementing a hook we need to figure out which Python module is leading to NSS being used, thus the example needs to be much more focused. What is the traceback of the current example?

**Comment by htgoebel** [comment]
Also your build-scripts tires to build two applications ate ones. While this is what you are aiming for, it makes it hard to debug. Focus on *one* *minimal* example.

**Comment by tangb** [comment]
Thank you for your help @htgoebel 

[Here](https://gist.github.com/tangb/66fe0627de2bcdb7c2cf991aaaf042ce) is output of the [previous small sample](https://gist.github.com/tangb/ddb22745e67fa3895e1a8a841f56af23) using QWebEngineView.

Effectively there is no SSL in this small example. I removed request import that need ssl (from urllib3).
It was my initial issue but now it seems not to be a problem (or it will be after nss will be resolved). To be honest I'm really lost with all different errors that appear. I think I'm facing 2 or 3 different issues depending on spec options and build environment (pyinstaller version and pyqt/qt versions). Now I have my build environment with all latest versions for all different products and I hope this will stabilize the pyinstaller process to focus on the real issues.

I tested with [another sample file](https://gist.github.com/tangb/cd30e1469e7b2747f82adda3f97410f6) still using Qt but without QWebEngineView widget and it runs fine. No nss error. According to google results NSS talks about chrome or firefox.

About my build-scripts, it builds 2 differents projects because I didn't manage to merge them. Si I decided to focus on individual problems before trying again to package them together. But my ui needs to cummunicate with the other app, it's why I'm building the 2 projects.

**Comment by htgoebel** [comment]
You need to run `strace` with `-f`, sorry, I missed that.

**Comment by tangb** [comment]
Hi @htgoebel 

[Here the output](https://gist.github.com/tangb/11e88faafeca785f2eafebe7735b8646) of strace -f of my bin execution. (~3Mo)

Thank you again for your help.

**Comment by htgoebel** [comment]
And what are your insights from the strace output? Please do not expect us to track this bug down. We can guide you, but we will are not going to track this issue down for you and not do your work. We are all volunteers here.

**Comment by tangb** [comment]
Ok no problem for situation clarification ;-)
I don't know what to look for in this log output. Can you guide me?

And to be honest, I switched my application from pygtk to electron to completely avoid this specific pyqtk issue. But it's not a problem I can still try to find a solution to this issue for other people that will encounter it. Just tell me how to proceed to find a fix. Thank you.

**Comment by kalikaneko** [comment]
I was hitting the same issue with the development version of pyinstaller (3.4.dev0+gab8fd975), and a minimal example using pyqtwebengine:

```
from PyQt5 import QtCore, QtGui
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView as QWebView

url = "http://debian.org"

class BrowserWindow(QWebView):

    def __init__(self, *args, **kw):
        super(QWebView, self).__init__(*args, **kw)
        _url = QtCore.QUrl(url)
        self.load(_url)

def launch_gui():
    qApp = QApplication([])
    browser = BrowserWindow(None)
    qApp.setQuitOnLastWindowClosed(True)
    browser.show()
    sys.exit(qApp.exec_())

if __name__ == "__main__":
    launch_gui()
```

The relevant info in the strace above was:

```
[pid 17881] open("/home/tbonneau/cleep-desktop.new/dist/cleep-ui/libfreeblpriv3.so", O_RDONLY|O_CLOEXEC <unfinished ...>
[pid 17853] mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0 <unfinished ...>
[pid 17881] <... open resumed> )        = -1 ENOENT (No such file or directory)
```
So, it was missing some nss libraries. After copying these two libraries into the dist folder, the bundled app was working properly again:

```
/usr/lib/x86_64-linux-gnu/nss/libsoftokn3.so
/usr/lib/x86_64-linux-gnu/nss/libfreeblpriv3.so
```

@htgoebel how should this finding be turned into a proper patch? does the pyqt5-qtwebengine hook need to copy this libs, or is there some other place where this should be worked on?

**Comment by bjones1** [comment]
Thanks for the great job of debugging this. I'm working on a fix which incorporates this; see https://github.com/bjones1/pyinstaller/tree/pyqt5_testing, along with #2991 and comments I made there. If you have any suggestions on ways to include NSS's libraries on other Linux platforms (I'm guessing the path `/usr/lib/x86_64-linux-gnu/nss/` with vary with the distro), please comment!
