### ISSUE TITLE
MSE Detects false positive when scanning executables compiled with -F

### ISSUE THREAD

**Issue by SilicaAndPina** [pyinstaller/pyinstaller#2741]
using python2.7
i wrote a little hello world program
   import tkMessageBox
   import Tkinter
   import tkSimpleDialog
   window = Tkinter.Tk()
   window.wm_withdraw()
   tkMessageBox.showinfo(title="Hello!", message="Hello World")
   window.destroy()

when i compile w pyinstaller.exe -W -F hello.py 
MSE says its a trojan.

**Comment by xoviat** [comment]
See #2501

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by htgoebel** [comment]
What ever this ["MSE" thing](https://de.wikipedia.org/wiki/MSE) is.

**Comment by SilicaAndPina** [comment]
Microsoft Security Essentials ...
