### ISSUE TITLE
Not running as sudo even added sudo when running under macOS(not sure for linux)

### ISSUE THREAD

**Issue by skys215** [pyinstaller/pyinstaller#2742]
Env:
macOS Sierra
Python3.5.4 (using installer from the python.org)

`pip3 install keyboard`

`pip3 install pyinstaller`

`pip3 install pyobjc-framework-Quartz`

```python
import sys
import keyboard

if __name__ == '__main__':
    keyboard.add_hotkey("alt+shift+c", lambda: print('hello'))
    keyboard.wait()
```
save this code as `kb.py`(short for keyboard).

This may occur under macOS after running `sudo python3 kb.py`,
if there's no error like this, jump to next step:
```
ImportError: No module named 'Quartz'
```
Follow [this](https://stackoverflow.com/questions/42530309/no-such-file-requirements-txt-error-while-installing-quartz-module) instruction to install the `quartz` module.

Spec file:
```python
# -*- mode: python -*-
import sys
block_cipher = None

a = Analysis(['kb.py'],
             pathex=['./'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='kb',
          debug=True,
          strip=False,
          upx=False,
          console=True )

app = BUNDLE(exe,
        name='kb.app',
	bundle_identifier='com.skys215.kb',
        info_plist={
            'CFBundleVersion' : '1.0.0',
        })
```

Run `pyinstaller kb.spec`.

After building, there's two files in the `dist/` folder.

One is the executable file, the other one is the .app file.

Run the executable file with `./dist/kb` and you can see the warning on the console.

```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 914, in _bootstrap_inner
  File "threading.py", line 862, in run
  File "site-packages/keyboard/__init__.py", line 138, in listen
  File "site-packages/keyboard/_darwinkeyboard.py", line 400, in listen
OSError: Error 13 - Must be run as administrator
```
Ok, then we run with `sudo` as `sudo ./dist/kb`. ( Run `open ./dist/kb` with or without `sudo` will always report this error.)

Now when we press `alt+shift+c`, we can see the `hello` print on the console.

So far so good.

But when we run `.app` from console, to see the debug output, nothing is output to the console.

If run the `.app` with `sudo`, program exit automatically with no any output.

So the problem is, the python program is not running with sudo even I added sudo on running.

**Comment by codewarrior0** [comment]
> But when we run .app from console, to see the debug output, nothing is output to the console.

Which command is this? Is it `sudo open kb.app` or `sudo kb.app/Contents/MacOS/kb`?

**Comment by skys215** [comment]
It's `sudo open kb.app` only,  no`/Contents/MacOS/kb` in behind.

**Comment by skys215** [comment]
Any progress?
Or any idea how to debug?

**Comment by skys215** [comment]
I recompiled the bootloader, added the code to check the uid and gid, they are not `0` even I run with 'sudo kb.app/Contents/MacOS/kb'.
I'll try to analyze the code to understand how this thing works, in order to gain root privilege.

**Comment by htgoebel** [comment]
PyInstaller does not change the uid or gid.

**Comment by skys215** [comment]
In that case, I don't understand.
I ran the program with `sudo`, but the result of `geteuid` is not `0`. It can't gain root access.

**Comment by skys215** [comment]
The problem was with `open` command. It will not pass the `sudo` when running.
It will run `kb.app/Contents/MacOS/kb; exit;` rather then `sudo kb.app/Contents/MacOS/kb; exit;`.
That's could be the reason why it's not running as root.

**Comment by htgoebel** [comment]
> The problem was with open command

This means, this issue can be closed? If not: Which "open" you are talking about?

**Comment by skys215** [comment]
Yeah, I think this issue can be closed.
I'll manage to get admin privilege with `osascript`.
Thanks

**Comment by amloewi** [comment]
@skys215 I'm having exactly this issue (with both pyinstaller and keyboard); would you mind please explaining what you did to solve the issue, in a little more detail? I'm also going the osascript route right now, thanks to this SO answer, https://stackoverflow.com/a/6463738/1055658, but don't understand things like exactly WHAT to give access to (the whole .app? A script within it?), when (AS it launches? after?), etc (a naive implementation isn't working).

**Comment by amloewi** [comment]
Thanks!

Is the problem that the script doesn't actually exist anymore, since it's part of the binary that's been created? I've poked around inside of the .app that pyinstaller creates, and there appears to be mostly just a single compiled file. (I've also tried to read the How PyInstaller Works, but am getting bogged down.) 

The closest idea I've had so far is to write in-line and factor just out the add_hotkey part (also for security reasons, https://stackoverflow.com/questions/25791196/forcing-a-gui-application-to-run-as-root), as in

    script = """python -c "import keyboard; import callback; keyboard.add_hotkey('cmd+x', callback)"""
    os.system("""osascript -e 'do shell script "{}" with administrator privileges'""".format(script))

The problem NOW is that I'm assuming there IS a 'python' on the user's system, which maybe, but there's MUCH less likely to be `python3` which I need -- is there a way to use the python that's been included in the pyinstaller itself? (I haven't been able to find it.)

**Comment by skys215** [comment]
Yeah, I'm facing the same problem.
I tried to print `ls -al` and `pwd` before calling the `osascript`, the script exists, but it still return with `No such file or directory`. 
Maybe I should try run `pwd` inside the `do shell script` command?

Ps. I have Mac in office, not my home, so I cannot debug it frequently.
Plus, it's my side project to study using PyQt, so I'm lack of motivation to debug it in the past few months/years.

**Comment by skys215** [comment]
Still failed to run as sudo

**Comment by htgoebel** [comment]
@amloewi @skys215 The way both of you create the command to run is **extremely insecure**! You are opening a door for shell-escape attacks! You should use the subprocess module to create secure code.
