### ISSUE TITLE
pinning libraries

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#2745]
As I'm sure everyone knows, the test suite is notoriously unreliable and constantly breaks when libraries release new versions. This makes it difficult to discern whether changes introduce new regressions. 

What I am suggesting here is a combination of two ideas, which are already implemented at [pypa/warehouse](https:///github.com/pypa/warehouse.git):
1. Pin all requirements-libraries to prevent library upgrades from breaking the test suite.
2. Subscribe to the @pyup-bot service to upgrade libraries. 
3. [OPTIONAL] Auto-merge pull requests from @pyup-bot that pass the test suite (these would be changes to requirements.txt only).

**Comment by xoviat** [comment]
@htgoebel Do you need assistance adding the pyup service?

**Comment by htgoebel** [comment]
This sounds like a very good idea :-) Some questions:
- How can we pin the current (resp. last passing) version most easily?
- Can we automatically tag the pull-requests from pyup-bot?
- pyio seems to service based solely on github infrastructure and service. Why dos it what access to my email-Adresse? Where is the issue-tracker for that project to ask this question?

**Comment by xoviat** [comment]
> How can we pin the current (resp. last passing) version most easily?

The pyup-bot will submit pull requests and then you will need to merge those that pass. We can implement a cron job that checks PRs and then merges them automatically using an API token.

> Can we automatically tag the pull-requests from pyup-bot?

Yes. See https://pyup.io/docs/bot/config/

> pyio seems to service based solely on github infrastructure and service. Why dos it what access to my email-Adresse? Where is the issue-tracker for that project to ask this question?

> https://github.com/pyupio/pyup

All sites that I sign up for usually want my email. If you don't like that bit, then it's not difficult to use a disposable address.

**Comment by xoviat** [comment]
For clarification, the auto merge is simple with PyGithub:

```python
from github import Github

g = Github("user", "password")  # TODO: Update to API key
repository = g.get_repo("pyinstaller/pyinstaller")
for pull_request in repository.get_pulls(state=):
    if pull_request.user.login == 'pyup-bot':
        commit = pull_request.get_commits()[-1]
        statuses = commit.get_statuses()
        if len(statuses) != 2:
            break
        for status in statuses:
             if status.state != success:
                 break
         else:
             pull_request.merge()
```

**Comment by htgoebel** [comment]
>> How can we pin the current (resp. last passing) version most easily?

>The pyup-bot will submit pull requests and then you will need to merge those that pass. We can implement a cron job that checks PRs and then merges them automatically using an API token.

I meant: How do we get the initial pinning? Maybe we need to go back to an old version which is working:

**Comment by springermac** [comment]
@htgoebel I've started that process in my `my-develop` branch. I'll split the changes out tonight so there easier to see but you can at least get an idea. Files to look at are .pyup.yml, requirements-tools, and requirements-libraries.

**Comment by xoviat** [comment]
AFAIK requirements-tools should not be pinned. We want those updated.

**Comment by xoviat** [comment]
@springermac The pypiwin32 builds will need to be pinned to 220 or 219 based on the python version. 220 is for python 3.6.

**Comment by xoviat** [comment]
If you can't do that then you can break it out into a separate requirements file and then include it in requirements-libraries.

**Comment by htgoebel** [comment]
pyup can be made to ignore entries, see https://pyup.io/docs/bot/filter/

**Comment by htgoebel** [comment]
@springermac I'm eager to lean about the result of you test.
> requirements-tools should not be pinned. We want those updated

Why not? If we pin these, we will get a stable environment for the test-suite, not only for the packages we are bundling.

**Comment by springermac** [comment]
I've put what I have in my  [pyup](https://github.com/springermac/pyinstaller/tree/pyup) branch. Its still a work in progress but you should be able to get an idea from it. 
There are currently several open pull requests that pyup has created if you want to see what they look like.

**Comment by springermac** [comment]
Pull request #2750 has been opened.

**Comment by htgoebel** [comment]
#2750 has been merged.
