### ISSUE TITLE
Doesn't work right when __import__ is used in the code

### ISSUE THREAD

**Issue by nateshmbhat** [pyinstaller/pyinstaller#2746]
The below code is taken from a function in pkg_resources module from the __init__.py file. Here the function imports modules dynamically ( self.module_name = "babefish.converters.alpha2" for example ) . This is causing the compiled exe not to work properly. The print("Module") statement after the __import__ statement doesn't execute everytime the function is called when compared to the non compiled exe . I have looked into the pyinstaller docs about including run-time hooks and hidden imports . I can't seem to get the exact command to work with this . 

```
    def resolve(self):
        """
        Resolve the entry point from its module and attrs.
        """
        module = __import__(self.module_name, fromlist=['__name__'], level=0)

        print("Module = {}".format(module)) ;
        print("functools = {}".format(functools.reduce(getattr, self.attrs, module)))
        try:
            return functools.reduce(getattr, self.attrs, module)
        except AttributeError as exc:
            raise ImportError(str(exc))
```

**Comment by tallforasmurf** [comment]
I'm sorry, I'm just confused. This is not taken from PyInstaller code. It is apparently a method, but of what class? Some class that has members `module_name` and `attrs` but I don't know what class that would be. If you want somebody to try this out, you need to provide more.

**Comment by htgoebel** [comment]
Please Read the Fine Manual http://pyinstaller.readthedocs.io/en/stable/operating-mode.html?highlight=__import__
