### ISSUE TITLE
Problem with subliminal

### ISSUE THREAD

**Issue by nateshmbhat** [pyinstaller/pyinstaller#2747]
Python code containing subliminal module , gives multiple errors after compiling from pyinstaller.

Here is a small code which works when run in a python interpreter but doesn't work after compiling . 

    import subliminal
    import sys,os,requests
    import argparse;
    import logging;
    from babelfish import Language
    import dbm.dumb
    
    
    # configure the cache
    subliminal.region.configure('dogpile.cache.dbm', arguments={'filename': 'cachefile.dbm'})
    
    
    parser = argparse.ArgumentParser()
    parser.add_argument('--Path' , type=str , default=None,help="Path for the video or a directory of videos.")
    args=parser.parse_args()
    
    if not args.Path:
    	args.Path = input("Enter the path for the video file or a directory containing videos : ") ;
    
    if os.path.isfile(args.Path):
    	videos = [subliminal.scan_video(args.Path)];
    else:
    	videos = subliminal.scan_videos(args.Path) ;
    
    subs = subliminal.download_best_subtitles(videos,{Language('eng')} ) ;
    print(list(subs.values()))
    for v in videos:
    	subliminal.save_subtitles(v, subs[v]) ;

The subtitle downloads perfectly when run from IDE or console directly. But it fails to get any subtitle , after compiling .

**Comment by tallforasmurf** [comment]
Suggest you add info: Platform, Python level. Also a "path" argument to use in order to try the code. 

Also, is it correct that one branch of the `isfile` test has `scan_video` and the other branch has `scan_videos` (with an s)?

Also is the failure that it does not return any videos (`videos` is empty), or that `subs` is empty, or that `save_subtitles` fails?

**Comment by nateshmbhat** [comment]
The subs list will be empty when the pool.list_subs() returns. I found that the main problem was in how pkg_resources is handles in a compiled executable. I assigned the entries based on the group name myself since the exe couldn't find any module in the init.py of pkg_resources.  

Now another problem arises. When the load_plugin is called, it also returns empty.

**Comment by nateshmbhat** [comment]
I think the problem lies with dynamically importing modules in the Extensions file using __import__() 
method. Somehow this is not working right after compilation. Any help I would be very grateful.

**Comment by nateshmbhat** [comment]
I had opened a separate issue #2746 along with the code that's causing the problem.

**Comment by nateshmbhat** [comment]
I think I found the main issue : - its the same as discussed in 

https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Setuptools-Entry-Point

subliminal also used entry points with multiple group names during its execution . The recipe you provided above doesn't say how to include multiple group names for a dist or how to use multiple dists . This narrow's the whole problem with subliminal . Can u please update the above recipe  ?

**Comment by htgoebel** [comment]
What are "multiple group names"?
> Can u please update the above recipe ?

It's a wiki, you can update it yourself :-)

**Comment by htgoebel** [comment]
I'm closing this ticket. Feel free to re-open it, when adding the requested information.
