### ISSUE TITLE
What is the timescale for support for python3.6

### ISSUE THREAD

**Issue by TNT-Samuel** [pyinstaller/pyinstaller#2751]
If you have problems to get your application running, please first

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If your problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for GitHub's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.

**Otherwise we will not be willing to help you.**

Please be aware that PyInstaller is a voluntary project. We spent quite some time
writing these guides to make both of our lives easier. Please
understand that we are not willing to spend our spare time to help you if you
are not willing to help on your side. (Sorry for having to said this, but we
are tired of being asked the same questions over and over again.)

**Comment by TNT-Samuel** [comment]
lol 420 issue

420: What you smoking

Sorry, I couldn't help myself

**Comment by xoviat** [comment]
Did you even read the issue template? It the *first* instruction.

**Comment by ZroXorZ** [comment]
Not an issue - just a hopefully helpful comment for someone having issues with pyinstaller on Python 3.6 : I was having issues with pyinstaller on a script where I was importing os, sys, csv, tkinter (and some other things in the tkinter library).  Long story short, I'm pretty much a newb at writing code, so I had no idea where to even begin looking at how to fix my issue.  Instead, I came here, saw that pyinstaller officially supports up to Python 3.5.... Uninstalled Python 3.6, installed Python 3.5, reinstalled pyinstaller, problem solved.....  I have no doubt that these remarkable code writers will get all the bugs ironed out of the 3.6 compatibility, but in the meantime, you can save yourself a WHOLE LOT of effort by just using a different version of Python...

ZroXorZ

**Comment by htgoebel** [comment]
@TNT-Samuel stop trolling, better provide pull-requests for open issues.
