### ISSUE TITLE
How do I donate? 

### ISSUE THREAD

**Issue by ErikBjare** [pyinstaller/pyinstaller#2755]
Hi there, 

I really like the idea of PyInstaller and use it in my project [ActivityWatch](https://github.com/ActivityWatch/activitywatch) (which is getting pretty stable). PyInstaller works good, but sometimes it could work better. I was surprised when I couldn't find a way to donate or fund the project. 

I was wondering what the main contributors think about donations/funding, would it increase development work? If so, where can I donate?

One software solution for managing donated funds is OpenCollective.com (I really like recurring payments and the focus on transparency).

Not sure if this could really be considered an issue, but I thought this would be the best place to ask. 

💸 💸 💸

**Comment by xoviat** [comment]
We use bountysource at https://www.bountysource.com/teams/pyinstaller. You need to select a specific issue that you want worked on and then place an adequate bounty.

**Comment by xoviat** [comment]
> PyInstaller works good, but sometimes it could work better. 

It's always going to be a game of cat and mouse with the hooks. The lasting contributions are making [modulegraph](https://github.com/pyinstaller/pyinstaller/blob/6ec7181578eed6dc7a4345efd76b84fe402e14ee/PyInstaller/lib/modulegraph/modulegraph.py) more intelligent and robust.

**Comment by ErikBjare** [comment]
Oh, weird how I didn't find it. It would be nice with a link to bountysource from the README, website, and docs.

**Comment by ErikBjare** [comment]
Added a monthly donation of $10 👍

**Comment by ErikBjare** [comment]
Should I file a PR with the links?

**Comment by xoviat** [comment]
If you want, the best place would probably be on the README. My guess is
that we'll get significantly more money if it's on the front page.

2017-08-21 17:04 GMT-05:00 Erik Bjäreholt <notifications@github.com>:

**Comment by htgoebel** [comment]
Erik: Thank you very much. :-)

Bu regarding bountysource: I'm not convinced that bountysource is an effective way to collect donations.To be frank, I personally am not interested in "virtual" money, that I can spend on other software-projects. I need to make my living and so am interested in money on my bank-account. But withdrawing from bountysource takes 10%, and PayPal takes another ~3%.

So it would be more efficient to transfer the money directly to me (I have to admit that this model is is not useful for apportioning the money to contributors) or directly to some PayPal donation account (yet to be created). Transferring money to me within the European Union is even for free when using SEPA. For companies wanting to contribute larger amounts, I could write a bill.

The main reason there is no donation section in the readme and the docs is, that I have not yet a good idea what to write there.

**Comment by htgoebel** [comment]
I thing, the best place for asking for donations is the web-site, the readme could point there.

**Comment by ErikBjare** [comment]
@htgoebel Understood. I think SEPA is partially out of the question due to the inconvenience (no one would bother). The reason Bountysource can take such exorbitant fees (just like Patreon et al) is because their service actually works. The 10% they take in fees tend to be worth it since they offer recurring payments (usually favored by donators) as well as transparency about who donated and how much. I think it would be a mistake to not likt to it, as it's the preferred method of donating for some (despite the fees).

I've been having my own idea for how to fund content online with no middlemen and therefore minimal fees. I've called it [Thankful](https://github.com/ActivityWatch/thankful), but it's a long way off.

If you want low-fee donations I'd suggest accepting Bitcoin or other cryptocurrency directly. There are plenty of Bitcoin holders in the Python space and some have gotten pretty significant gains (and tend to be big spenders). The downside to Bitcoin right now is the [exorbitant transaction fees](https://bitcoinfees.21.co/) (~$3 per tx), but people who donate with Bitcoin rarely donate less than $30 anyway so not worse than Bountysource. Another argument for adding a Bitcoin address to the README would be that automated systems (such as Thankful) could crawl for the donation address easily.

One other cryptocurrency I'd suggest is Ether. Their transaction fees are [~$0.3](https://bitinfocharts.com/comparison/ethereum-transactionfees.html) and they are the second largest cryptocurrency by market cap (~1/3 to 1/2 that of BTC) so makes the most sense to offer.

If you don't want to personally hold Bitcoin/Ether but instead EUR/USD you could set up an automatic sell on Coinbase or something similar.

Therefore, my recommendation:

  - Add to README
    - [ ] Bitcoin (and Ethereum?) address
    - [ ] Link to Bountysource
    - [ ] Link to website
  - Add to website
    - [ ] Same donation methods as in README
    - [ ] Paypal/SEPA
    - [ ] Potentially a list of past donations (seeing their name/avatar on a page incentivizes people to donate)

The argument for why all this should go in the README is pretty simple: Lowering the number of clicks needed to donate increases the number of donations (as @xoviat said "we'll get significantly more money if it's on the front page")

If you want I could put up a PR with the basics (README links) and then we could fix the website later on (assuming that's more work). The only thing I'd need is for you to set up a Bitcoin/Ethereum account on Coinbase or similar.

**Comment by htgoebel** [comment]
Thanks, the website now has a donation page: http://www.pyinstaller.org/donate.html and the README links there (README is on my WIP release branch currently). Feel free to suggest enhancements. maybe link to the donations on the website-front-page, too?

**Comment by htgoebel** [comment]
Of, I missed closing this issue when implementing.
