### ISSUE TITLE
Rework modulgraph to work like a PEP-451 loader / ModuleSpec

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2763]
Modulegraph way to find and load modules was become quite ugly code, e.g. it is passing around file-handles, which sometimes point to source, othertimes point to byte-code.

[PEP-451](https://www.python.org/dev/peps/pep-0451/) describes a `ModuleSpec` and related importer functions. PEP-451 has some `find_spec` step, returning a `ModuleSpec`, which then can be used to load the code. The PEP also include example code for dealing with importers not yet complying to the PEP.

xiovat implemented a PEP-451 compatible loader for PyInstaller in 702c9c2f5419e8a3ce2a6effc71431fa93ff9ea8. The code looks sound and clear.

We should rework modulegraph to implement a mechanism like this using modern import machinery (if available for this version of Python). In the long run (when dropping support for old Python versions) this would allow to get rid of the loader implementation within modulegraph. Maybe we could implement a compatibility-layer for Python versions not supporting PEP-451 and keep compatibility code out of `modulgraph/modulgraph.py`

Mind pushing the changes upstream :-)

**Comment by xoviat** [comment]
> Maybe we could implement a compatibility-layer for Python versions not supporting PEP-451 and keep compatibility code out of modulgraph/modulgraph.py

The compatibility layer mentioned here is adding a dependency on `importlib2` for Python 2.7. The developer of this package is not likely to pull it from pypi as happened for dis3.

**Comment by Legorooj** [comment]
I'm closing this, it's invalid now.
