### ISSUE TITLE
Re-vendoring our external dependencies?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2764]
A few weeks ago, we started removing external modules from our `lib/` directory and install them via setuptools requirements (in `setup.py`). While this eases the maintenance of PyInstaller, it also introduces a potential issue:

PyInstaller is collecting the modules to be frozen from `sys.path` (plus paths given on the command-line). Now assume some project requiring `pefile` version `A`, which makes PyInstaller fail. And any version of `pefile` being okay for PyInstaller (`B`) makes the project fail (or may not be used by the project for other reasons). In such a case PyInstaller needs to import version `B` for it's own use, bur must include version `A` into the bundle.

How can this be solved? There are two possibilities:
1) The user needs to install version `A` somewhere else (e.g. in a separate venv) and pass the path to this place using `--path`. This is very cumbersome.
2) PyInstaller is made to *not* search the required modules on sys.path, but is vendoring in required packages.

Opinions?

**Comment by tallforasmurf** [comment]
such is my ignorance that I do not understand why this could not be solved by the user: install pyinstaller directly into a venv that has the correct libs installed for the app. Wouldn't the pyinstaller installation than contain and use the right libs?

**Comment by htgoebel** [comment]
PyInstaller searches the apps packages on sys.path, thus PyInstaller and the app share the same sys.path, but both may need incompatible versions of some package. If you install PyInstaller and the app in different venv, then you have to pass the app-venv's site-packages path to PyInstaller (using `--path`).

Maybe this is a non-issue, that's why I ask for opinions.

**Comment by xoviat** [comment]
I don't think that we should address this until someone brings up this issue.

**Comment by htgoebel** [comment]
Okay, so let's wait until someone brings up this issue.
