### ISSUE TITLE
Pyinstaller having problem with glade files (Not the same issues that I have seen before)

### ISSUE THREAD

**Issue by BaconCow4** [pyinstaller/pyinstaller#2786]
Hello, I am a beginner on PyInstaller and trying to pack my .py files into an executable using pyinstaller, but I have spent a whole day on it and it can't be able to solve, also can't find answer which can solve my problem.

The problem is that I am trying to use pyinstaller to pack application, it works totally fine with Gtk GUI application, and I have successfully pack it into an executable but when my program try to load a .glade(gtk_builder_add_from_file) file in my program, it returns the error 

```
**_### **"Gtk-Message: Failed to load module "canberra-gtk-module"

(PyLearner:14882): Gtk-WARNING **: Could not load a pixbuf from icon theme.
This may indicate that pixbuf loaders or the mime database could not be found.
**
Gtk:ERROR:/build/gtk+3.0-qPyWJl/gtk+3.0-3.22.11/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)
Aborted (core dumped)
"**_**
```

One reason that I am not including my .glade file in datas=[] in the spec file is that my program downloads .glade files from a host server every time it starts(app content need to be keep updated) and put it in "tmp" folder. Not only that, when I am trying to remove all part which load glade file in my program(only the splash screen is left) and repack those py files into executable, I find out that pyinstaller also having problem with it, it does return the same error. (No error with pure GUI, I mean no splash screen and not using .glade file)

Down is the code that run into error after converting to executable with pyinstaller:
**Splash screen class**
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

#splash screen window
class splashScreen(Gtk.Window):
    def update_progress(self, progress):
        self.progress_bar.pulse()
        self.progress_bar.set_fraction((progress * (100 / 12)) / 100)
        print("File ", progress, "downloaded!")

    def __init__(self):
        Gtk.Window.__init__(self, title="splash", type=Gtk.WindowType.TOPLEVEL)

        vbox = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)

        image = Gtk.Image()
        image.set_from_file("splash.png")

        self.progress_bar = Gtk.ProgressBar()
        self.progress_bar.set_text("Loading necessary file...\nThis wouldn't take you too long.\n")
        self.progress_bar.set_show_text(True)

        vbox.pack_start(image, True, True, 0)
        vbox.pack_start(self.progress_bar, False, True, 0)

        self.add(vbox)
```

**main class**
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk
import urllib.request
import threading, time, Handler, splashScreen, os
import sqlite3

loading_progress = 0

class GuiLoader:
    def load(self):

        builder = Gtk.Builder()
        builder.add_from_file("/tmp/main_gui.glade")
        builder.connect_signals(Handler.Handler())

        window = builder.get_object("window")
        window.connect("delete-event", Gtk.main_quit)
        window.show_all()

        Gtk.main()

class init(threading.Thread):
    def run(self):
        ...
        for i in range(12):
            if i == 11:             #run the main program when files are downloaded
                main_app_init = GuiLoader()
                main_app_init.load()
            ...

if __name__ == '__main__':

    w = splashScreen.splashScreen()
    w.set_size_request(720, 405)
    w.set_decorated(False)
    w.set_position(Gtk.WindowPosition.CENTER)
    w.show_all()

    initialization = init()
    initialization.start()

    while loading_progress < 11:           #loading progress will be added when a file is downloaded
        Gtk.main_iteration()                     #not starting main app when all file have not been downloaded

    w.destroy()                                       #end splash screen when files are downloaded
```

Please tell me what can I do, I am using PygObject for my application, Gtk3, Ubuntu 17.04, python3.5  and pyinstaller 3.3.dev0+c45dabfeb. I will be appreciated if anyone can answer my question!

**Comment by tallforasmurf** [comment]
I understand you are a beginner (at what? programming? or just PyInstaller?) and sympathize with your frustration. However, PyInstaller is 100% supported by volunteers, and you need to give LOTS more information to get help.

You need to specify the platform (I'm guessing Linux from the GTK reference, but which distro and version?), the version of Python, and the version of PyInstaller (`pyinstaller --version`).

Then you need to read [If Things Go Wrong](https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) which summarizes a lot of experience, and then [How to report bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

Then try to cut your app down to the tiniest bit of code that will fail.

**Comment by BaconCow4** [comment]
Oh, sorry @tallforasmurf I have update the post, hope enough information is included. Thanks for reminding me. :)

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by tallforasmurf** [comment]
Well thank you for that, although you didn't mention the one thing emphasized repeatedly in the references I gave, are you bundling in --onedir mode? So you end up with a folder with the executable and all dependencies visible inside?

Maybe somebody else can understand what is going on, but the basic problem remains opaque to me. You say it involves `gtk_builder_add_new_file` but I don't see that being called in the code you show. Can you possibly make a copy of the script and cut it down to the absolute minimum code that fails? No threading (I see a remark about threading) and fewest possible widgets hopefully just the main window? And, at the very least, at what statement in the Python code is this error being raised? Also it does not appear to be a Python type of exception but rather something rather serious (assertion failure) from deep inside the GUI toolkit. So you might google the message "Gtk-WARNING : Could not load a pixbuf from icon theme" -- I did and see a couple of other people had the issue.

**Comment by htgoebel** [comment]
And please provide a *minimal* example. Since your problem is ASAIU not related to using glade, provide an example without.

**Comment by BaconCow4** [comment]
Sorry @tallforasmurf , I have mistyped gtk_builder_add_new_file, it should be gtk_builder_add_from_file, below is the code that cause error(hope the code below is a minimal example @htgoebel )

First is the code that calls the splash screen(I am thinking if the error is raised because of the code "Gtk.main_iteration()" because it works when I use Gtk.main() but not Gtk.main_iteration().)

```
    w = splashScreen.splashScreen()
    w.set_size_request(720, 405)
    w.set_decorated(False)
    w.set_position(Gtk.WindowPosition.CENTER)
    w.show_all()

    while loading_progress < 11:
        Gtk.main_iteration()

    w.destroy()

```

Next is the code that build up the GUI with glade file(I really have no idea about what cause the error, I have searched Google and tried before I post, but seems that they are having different error with me, although the error message is likely the same, I don't know why it gives me the "Could not load pixbuf..." error but I think the error is not made by pixbuf problem actually)
```
class GuiLoader:
    def __init__(self):

        builder = Gtk.Builder()
        builder.add_from_file("/tmp/pylearner.glade")
        builder.connect_signals(Handler.Handler())

        window = builder.get_object("window")
        window.connect("delete-event", Gtk.main_quit)
        window.show_all()

        Gtk.main()

```

I am not using --one-dir mode but I am using a spec file to include multiple files

**Comment by BaconCow4** [comment]
@htgoebel below is the codes that run into problem after packing using pyinstaller (If I did not guess it wrong)
`        Gtk.main_iteration()`
in
```    w = splashScreen.splashScreen()

    w.set_size_request(720, 405)
    w.set_decorated(False)
    w.set_position(Gtk.WindowPosition.CENTER)
    w.show_all()

    while loading_progress < 11:
        Gtk.main_iteration()

    w.destroy()

```
and
`        builder.add_from_file("/tmp/pylearner.glade")`
in
```
class GuiLoader:
    def __init__(self):

        builder = Gtk.Builder()
        builder.add_from_file("/tmp/pylearner.glade")
        builder.connect_signals(Handler.Handler())

        window = builder.get_object("window")
        window.connect("delete-event", Gtk.main_quit)
        window.show_all()

        Gtk.main()

```

**Comment by htgoebel** [comment]
Please provide a minimal example *without using glade*, which I can copy and paste. At best it only includes a *single* call, the one triggering "Gtk:ERROR:/build/gtk+3.0-qPyWJl/gtk+3.0-3.22.11/./gtk/gtkiconhelper.c:493:ensure_surface_for_gicon: assertion failed: (destination)".

If this error only shows up when using glade, try to build another example.

Also I can not see that you followed the guide "Make sure everthing" is packed, since you report about the insights from running strace.

We can guide you, but we will are not going to track this issue down for you and not do your work. We are all volunteers here.

**Comment by tallforasmurf** [comment]
> I am not using --one-dir mode but I am using a spec file to include multiple files

I am not sure we are communicating here. [The option is `--onedir` or `-D`](http://pyinstaller.readthedocs.io/en/stable/usage.html#what-to-generate) (click that) and you end up with a **folder** containing a bunch of files including an executable *scriptname*. This is a valid way of bundling; you zip up that folder and send it out and it contains everything that *scriptname* needs to run.

The alternative, `--onefile` produces a single executable file. You would use a spec file in either case. Either results in an executable, but `--onedir` is much easier to figure out what's going on.

I appreciate the effort you have gone to, pasting code and commenting it, but it really is no help because nobody can replicate it to test it locally. It's way too complex. I just spent 20 minutes pasting the two chunks, main and splashscreen, into an editor and trying to just follow the logic and I can't. When is loading_progress updated? Some global that is updated out of where? Then you mention that it works if you don't use `gtk_main_iteration` and I tried googling that and per [this SO answer](https://stackoverflow.com/questions/3961977/gtk-why-do-gtkmainiteration#3962429) it has to do with explicit control of the main loop when you are threading. if you need that you are multi-threading and taking explicit control of the GTK event loop -- that's another whole can of worms. Give me a break.

You have been asked repeatedly to provide a simple piece of code that will fail, so that somebody else with a Unix system could paste it and run it and see a failure. You need to do that to get further help. a/orun the strace as you were asked.

**Comment by BaconCow4** [comment]
Thank you guys and spending your times, I am going to reinstall pyinstaller and try again all things in "Make sure everything is packaged correctly" to get more informations

**Comment by BaconCow4** [comment]
Thank you @tallforasmurf and @htgoebel keep guiding me, I have packaging it successfully, below is what I have done.
First, I installed a virtual machine. Second, I remake the app and is better coded. Third, I compile it from PyCharm, it has succeed. Then, I install the latest development version of PyInstaller and using Python 3.5. Since it is using --onedir mode by default so I just type the command `pyinstaller main.py`. Next, I edit spec file to pack all of the .py file, and it is working! Though I haven't try it on other system... Anyway, thank you @tallforasmurf and @htgoebel , although I have to sorry about that I don't know if it is a bug or not and I haven't gave out enough information to help you determine what is going on... Really sorry that it just like I'm wasting your time but please, please accept a great appreciation from me. :) 💯

**Comment by xoviat** [comment]
Excellent, so is this issue resolved?

**Comment by BaconCow4** [comment]
yes

**Comment by sukesh-g** [comment]
hi @baconcowa i am also facing same problem, can you please help me by sharing spec file
