### ISSUE TITLE
exe can't run

### ISSUE THREAD

**Issue by seghier** [pyinstaller/pyinstaller#2794]
hi i do that step by step:
i create main window in qt designer
i save "ui" file
i convert the ui file to "py"
i create python file of my application and load "ui+py" created before
i save the new python file and create exe with pyinstaller
but i can't run the exe file ; why ?

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by seghier** [comment]
hi
i upload all files to dropbox ; pyinstaller when create exe file i can't open it until i copy the ui file inside the new exe folder ; and when i try open it in other system don't work and always error message : 
failed to execute script ...
it look like some files are missing but i don't know why pyinstaller don't compile all file used with the script ?!
link of the files : https://www.dropbox.com/s/ggwdds4afo6n8s3/py%20test.rar?dl=0
please when you test it copy the folder pymaxwell to 'your_drive':\Python27\Lib\site-packages\
and i use pyqt4.

**Comment by htgoebel** [comment]
I'm not going to download some archive from anywhere. Sorry, but we are all volunteers here. Please provide all requested information *here*. If you missed what we need, you can find it at https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE.md

**Comment by seghier** [comment]
You asked me for example and details and i send you everything you need
How you know where is the problem if you don't check the files ?!
And with this link i will spend days with trying without confirmation if that solve my problem or not or it is problem can solved or bug !

**Comment by htgoebel** [comment]
No reaction for several month, assume this is solves.
