### ISSUE TITLE
utils.hooks.is_module_satisfies() fails when package is installed using "pip install develop.zip"

### ISSUE THREAD

**Issue by cztomczak** [pyinstaller/pyinstaller#2802]
This works fine:
```cmd
git clone https://github.com/pyinstaller/pyinstaller
cd pyinstaller/
python setup.py install
pip show pyinstaller
> Version: 3.3.dev0+g5dc9557c
> Location: c:\python27\lib\site-packages
python: > is_module_satisfies("pyinstaller >= 3.3") === True
```

This one fails:
```cmd
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
pip show pyinstaller
> Version: Version: 3.3.dev0+5dc9557c9
> Location: c:\python27\lib\site-packages\pyinstaller-3.3.dev0+g5dc9557c-py2.7.egg
python: > is_module_satisfies("pyinstaller >= 3.3") === False
```

**Comment by cztomczak** [comment]
Edited first comment to display versions from "pip show".

**Comment by cztomczak** [comment]
Worth noting that "python setup.py install" is running on Windows 7, while "pip install develop.zip" is running on Windows 10.

**Comment by htgoebel** [comment]
Hmm, this is curious. Can you please step through `is_module_satisfies()` as see what is the difference? On both systems should take the first [`if`-branch](https://github.com/pyinstaller/pyinstaller/blob/5dc9557c9/PyInstaller/utils/hooks/__init__.py#L473) and use the result provided by `pkg_resources.get_distribution()`.

What versions of setuptools and pkg_resources are installed on the resp. machines?
