### ISSUE TITLE
How to import efficiently all cython modules?

### ISSUE THREAD

**Issue by chenk17** [pyinstaller/pyinstaller#2814]
Hey guys,

slowly I make progress with my exe. I have only troubles (so far) with all the cython modules my script needs.

I found that it works if I add all those modules in hiddenimports or explictly imprt them via from ... import.

But I have top do this step by step. Impiort only one module to find the next missing module which is very time intensive...

How can I add to the spec file the proper paths where all cython modules are lying such that I don't need to name every single module?

So not explicit single module in spacy.serialize as spacy.serialize.bits, etc.

Instead give the path to spacy.serialize...

**Comment by chenk17** [comment]
To specifiy more: In Python packages there are commonly a lot of cython modukles llike for sklearn. Is there any method to give a path simply to those modules in the .spec file instead of manually imorting them step by step? or is there any way to know beforehand whta modules are missing. So far I have for every module run the exe to konow which are  missing...

**Comment by htgoebel** [comment]
The .spec-file is just a Python-script, so if all the *.pyd you know are required are at a known place, you can scan this directory in the .spec-file and pass these modules to `Analyze()` using the `hiddenimports` parameter.

If these packages are commonly used (like sklearn), you can make other's life easier by providing or updating the respective  hook.

Following imports within compiled cython-modules is not possible, see #293.

HTH.

**Comment by chenk17** [comment]
But doesn't the -v gives the missing modules before running the exe? Or is this not working for hidden import?

**Comment by htgoebel** [comment]
You mean `python -v your-app.py`? This should work, too, in 98% of the cases.

**Comment by chenk17** [comment]
I thought it would the for the executable. Because the Python comilation for my script works. But the missing modules error occur of course onl y at runtime of the exe...

Or does this also output the missing cython modules?

**Comment by htgoebel** [comment]
> I thought it would the for the executable.

I strongly suggest reading the PyInstaller manual, esp. the how it works section.

> Or does this also output the missing cython modules?

`python -v your-app.py` should also output the imorted cython modules.
