### ISSUE TITLE
WARNING: Internal error: early pywin32 import was introduce

### ISSUE THREAD

**Issue by onsunsl** [pyinstaller/pyinstaller#2815]
>pyinstaller  server.py
6 WARNING: Internal error: early pywin32 import was introduced
75 INFO: PyInstaller: 3.3.dev0+c45dabfeb
75 INFO: Python: 3.5.3
78 INFO: Platform: Windows-10-10.0.14393-SP0
79 INFO: wrote xxxx\project\server.spec
83 INFO: UPX is not available.

**Comment by chenk17** [comment]
Can you give more information? This warning is not important. If you google it you find this same problem on the proper github page where I asked this too. So are there other errors?

**Comment by onsunsl** [comment]
Active code page: 65001

D:\project>pyinstaller server.py
7 WARNING: Internal error: early pywin32 import was introduced
77 INFO: PyInstaller: 3.3.dev0+c45dabfeb
77 INFO: Python: 3.5.3
78 INFO: Platform: Windows-10-10.0.14393-SP0
78 INFO: wrote D:\project\server.spec
80 INFO: UPX is not available.
82 INFO: Extending PYTHONPATH with paths
['D:\\project',
 'D:\\project']
82 INFO: checking Analysis
82 INFO: Building Analysis because out00-Analysis.toc is non existent
82 INFO: Initializing module dependency graph...
86 INFO: Initializing module graph hooks...
88 INFO: Analyzing base_library.zip ...
6762 INFO: running Analysis out00-Analysis.toc
6764 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Anaconda3\python.exe
7714 INFO: Caching module hooks...
7721 INFO: Analyzing D:\project\server.py
10487 INFO: Processing pre-find module path hook   distutils
14638 INFO: Processing pre-find module path hook   site
14645 INFO: site: retargeting to fake-dir 'C:\\Anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
19912 INFO: Processing pre-safe import module hook   six.moves
28985 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
65528 INFO: Loading module hooks...
65529 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
65551 INFO: Loading module hook "hook-xml.dom.domreg.py"...
65552 INFO: Loading module hook "hook-PIL.py"...
65555 INFO: Excluding import 'PySide'
65558 WARNING:   Removing import PIL.ImageQt from module PySide
65559 INFO: Excluding import 'PyQt5'
65562 WARNING:   Removing import PIL.ImageQt from module PyQt5
65562 INFO: Excluding import 'PyQt4'
65566 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtCore
65566 WARNING:   Removing import PIL.ImageQt from module PyQt4.QtGui
65567 INFO: Import to be excluded not found: 'FixTk'
65567 INFO: Excluding import 'tkinter'
65570 INFO: Loading module hook "hook-jinja2.py"...
65602 INFO: Loading module hook "hook-_tkinter.py"...
65883 INFO: checking Tree
65883 INFO: Building Tree because out00-Tree.toc is non existent
65883 INFO: Building Tree out00-Tree.toc
66049 INFO: checking Tree
66050 INFO: Building Tree because out01-Tree.toc is non existent
66050 INFO: Building Tree out01-Tree.toc
66079 INFO: Loading module hook "hook-pycparser.py"...
66389 INFO: Loading module hook "hook-sqlite3.py"...
66543 INFO: Loading module hook "hook-PyQt4.QtGui.py"...
67023 INFO: Loading module hook "hook-numpy.core.py"...
67143 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
67146 INFO: Loading module hook "hook-lxml.etree.py"...
67168 INFO: Loading module hook "hook-distutils.py"...
67175 INFO: Loading module hook "hook-certifi.py"...
67185 INFO: Loading module hook "hook-PyQt4.py"...
67191 INFO: Loading module hook "hook-sysconfig.py"...
67202 INFO: Loading module hook "hook-requests.py"...
67204 INFO: Loading module hook "hook-PIL.Image.py"...
67875 INFO: Loading module hook "hook-pygments.py"...
70871 INFO: Loading module hook "hook-pydoc.py"...
70872 INFO: Loading module hook "hook-matplotlib.py"...
71261 INFO: Loading module hook "hook-matplotlib.backends.py"...
71927 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
72411 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
72736 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
73210 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
73724 INFO:   Matplotlib backend "Qt4Agg": added
74239 INFO:   Matplotlib backend "Qt5Agg": added
74898 INFO:   Matplotlib backend "TkAgg": added
75381 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
75851 INFO:   Matplotlib backend "WXAgg": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
76193 INFO:   Matplotlib backend "GTK3Cairo": ignored
    Gtk3 backend requires pygobject to be installed.
76679 INFO:   Matplotlib backend "GTK3Agg": ignored
    Gtk3 backend requires pygobject to be installed.
80081 INFO:   Matplotlib backend "WebAgg": added
81157 INFO:   Matplotlib backend "nbAgg": added
81621 INFO:   Matplotlib backend "agg": added
81949 INFO:   Matplotlib backend "cairo": ignored
    Cairo backend requires that cairocffi or pycairo is installed.
82322 INFO:   Matplotlib backend "emf": ignored
    No module named 'matplotlib.backends.backend_emf'
82670 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
83260 INFO:   Matplotlib backend "pdf": added
83866 INFO:   Matplotlib backend "pgf": added
84385 INFO:   Matplotlib backend "ps": added
84938 INFO:   Matplotlib backend "svg": added
85426 INFO:   Matplotlib backend "template": added
85988 INFO: Loading module hook "hook-lib2to3.py"...
86025 INFO: Loading module hook "hook-IPython.py"...
86159 INFO: Excluding import 'matplotlib'
86165 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.pyplot
86165 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.figure
86176 WARNING:   Removing import IPython.core.pylabtools from module matplotlib.pylab
86216 WARNING:   Removing import IPython.core.pylabtools from module matplotlib._pylab_helpers
86218 WARNING:   Removing import IPython.core.pylabtools from module matplotlib
86266 INFO: Excluding import 'tkinter'
86295 WARNING:   Removing import IPython.lib.clipboard from module tkinter
86323 WARNING:   Removing import IPython.lib.inputhook from module tkinter
86327 INFO: Excluding import 'PyQt4'
86369 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtCore
86393 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtSvg
86425 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4.QtGui
86462 WARNING:   Removing import IPython.external.qt_loaders from module PyQt4
86467 INFO: Excluding import 'PySide'
86511 WARNING:   Removing import IPython.external.qt_loaders from module PySide
86538 INFO: Excluding import 'PyQt5'
86549 WARNING:   Removing import IPython.external.qt_loaders from module PyQt5
86608 INFO: Excluding import 'gtk'
86650 WARNING:   Removing import IPython.lib.inputhook from module gtk
86675 WARNING:   Removing import IPython.lib.inputhookgtk from module gtk
86680 INFO: Loading module hook "hook-PyQt4.QtCore.py"...
86842 INFO: Loading module hook "hook-PyQt4.QtSvg.py"...
86842 INFO: Loading module hook "hook-zmq.py"...
89318 WARNING: Hidden import "C:\Anaconda3\lib\site-packages\zmq\backend\cffi\__pycache__\_cffi_ext.c(209):" not found!
89437 WARNING: Hidden import "_cffi_ext.c" not found!
89439 WARNING: Hidden import "fatal" not found!
89441 WARNING: Hidden import "No" not found!
89446 WARNING: Hidden import "directory" not found!
89447 WARNING: Hidden import "Cannot" not found!
89482 WARNING: Hidden import "open" not found!
89730 WARNING: Hidden import "file" not found!
89847 WARNING: Hidden import "error" not found!
89848 WARNING: Hidden import "or" not found!
89851 WARNING: Hidden import "'sys/un.h':" not found!
89866 WARNING: Hidden import "C1083:" not found!
89901 WARNING: Hidden import "file:" not found!
89940 WARNING: Hidden import "such" not found!
89948 INFO: Excluding import 'zmq.libzmq'
89981 WARNING:   Removing import zmq from module zmq.libzmq
90048 INFO: Loading module hook "hook-setuptools.py"...
90150 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
90156 INFO: Import to be excluded not found: 'FixTk'
90156 INFO: Excluding import 'tkinter'
90189 INFO: Loading module hook "hook-cryptography.py"...
90603 INFO: Loading module hook "hook-jsonschema.py"...
90619 INFO: Loading module hook "hook-pkg_resources.py"...
91672 INFO: Processing pre-safe import module hook   win32com
92012 INFO: Loading module hook "hook-pywintypes.py"...
92497 INFO: Loading module hook "hook-xml.py"...
92498 INFO: Loading module hook "hook-encodings.py"...
92608 INFO: Loading module hook "hook-pytz.py"...
92745 INFO: Loading module hook "hook-pythoncom.py"...
93219 INFO: Loading module hook "hook-win32com.py"...
94351 INFO: Looking for ctypes DLLs
94400 WARNING: ignoring voice/msc.dll - ctypes imports only supported using bare filenames
94400 WARNING: ignoring voice/msc_x64.dll - ctypes imports only supported using bare filenames
94402 WARNING: ignoring /home/turingos/robot3d/server/voice/libmsc_x64.so - ctypes imports only supported using bare filenames
94407 WARNING: library LibraryLoader.dll required via ctypes not found
94485 INFO: Analyzing run-time hooks ...
94502 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
94521 INFO: Including run-time hook 'pyi_rth__tkinter.py'
94568 INFO: Including run-time hook 'pyi_rth_pkgres.py'
94599 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
94602 INFO: Including run-time hook 'pyi_rth_traitlets.py'
94636 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
94706 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
94749 INFO: Including run-time hook 'pyi_rth_mpldata.py'
94850 INFO: Looking for dynamic libraries
126687 WARNING: lib not found: tbb.dll dependency of C:\Anaconda3\Library\bin\mkl_tbb_thread.dll
378118 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
378130 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
378144 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
378251 INFO: Searching for assembly x86_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9247_none ...
378251 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35.manifest
378263 INFO: Searching for file msvcr90.dll
378264 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcr90.dll
378264 INFO: Searching for file msvcp90.dll
378264 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcp90.dll
378264 INFO: Searching for file msvcm90.dll
378265 INFO: Found file C:\WINDOWS\WinSxS\x86_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_5090cb78bcba4a35\msvcm90.dll
378362 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_8550c6b5d18a9128.manifest
378363 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_f47e1bd6f6571810.manifest
378364 INFO: Found C:\WINDOWS\WinSxS\Manifests\x86_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9247_none_f47e3bf8f656f083.manifest
378365 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9247)
379683 INFO: Looking for eggs
379683 INFO: Using Python library C:\Anaconda3\python35.dll
379683 INFO: Found binding redirects:
[BindingRedirect(name='Microsoft.VC90.CRT', language=None, arch='x86', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9247), publicKeyToken='1fc8b3b9a1e18e3b')]
379700 INFO: Warnings written to D:\project\build\server\warnserver.txt
379812 INFO: checking PYZ
379812 INFO: Building PYZ because out00-PYZ.toc is non existent
379812 INFO: Building PYZ (ZlibArchive) D:\project\build\server\out00-PYZ.pyz
383856 INFO: Building PYZ (ZlibArchive) D:\project\build\server\out00-PYZ.pyz completed successfully.
386949 INFO: checking PKG
386949 INFO: Building PKG because out00-PKG.toc is non existent
386950 INFO: Building PKG (CArchive) out00-PKG.pkg
387027 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
387029 INFO: Bootloader C:\Anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
387029 INFO: checking EXE
387029 INFO: Building EXE because out00-EXE.toc is non existent
387029 INFO: Building EXE from out00-EXE.toc
387030 INFO: Appending archive to EXE D:\project\build\server\server.exe
387042 INFO: Building EXE from out00-EXE.toc completed successfully.
387049 INFO: checking COLLECT
387050 INFO: Building COLLECT because out00-COLLECT.toc is non existent
387050 INFO: Building COLLECT out00-COLLECT.toc
387148 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\python35.dll
387149 INFO: Updating resource type 24 name 2 language 1033
389740 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\pywintypes35.dll
389740 INFO: Updating resource type 24 name 2 language 1033
394107 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\_ssl.pyd
394108 INFO: Updating resource type 24 name 2 language 1033
394225 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\unicodedata.pyd
394225 INFO: Updating resource type 24 name 2 language 1033
394271 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\_ctypes.pyd
394272 INFO: Updating resource type 24 name 2 language 1033
394319 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\pyexpat.pyd
394320 INFO: Updating resource type 24 name 2 language 1033
394339 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\_hashlib.pyd
394340 INFO: Updating resource type 24 name 2 language 1033
394360 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\select.pyd
394361 INFO: Updating resource type 24 name 2 language 1033
394441 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\_bz2.pyd
394441 INFO: Updating resource type 24 name 2 language 1033
394457 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\_lzma.pyd
394458 INFO: Updating resource type 24 name 2 language 1033
394474 INFO: Updating manifest in C:\Users\onsun\AppData\Roaming\pyinstaller\bincache00_py35_32bit\_socket.pyd
394474 INFO: Updating resource type 24 name 2 language 1033
410825 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

**Comment by onsunsl** [comment]
The following error message when running exe file:
Runtime Error！
Program:
D:\project\dist\server.exe
R6034 
An application has made an attempt to load C runtime library incorrectly.
Please contact the application's support team for more information.

**Comment by grajsor** [comment]
Please read the FAQ: https://github.com/pyinstaller/pyinstaller/wiki/FAQ

Can I use PyInstaller with other Python distributions?
The primary development and testing of PyInstaller is focused on official
Python releases available from Python website <http://python.org/> . Other
Python distributions like ActivePython
<http://www.activestate.com/activepython>, Anaconda
<http://continuum.io/>, Enthought
Canopy <https://store.enthought.com/>, Python(x,y)
<https://python-xy.github.io/>, WinPython <https://winpython.github.io/> or
Pyzo <http://www.pyzo.org/> may or may not work.
