### ISSUE TITLE
question about compile the script

### ISSUE THREAD

**Issue by seghier** [pyinstaller/pyinstaller#2816]
hi 
when i create a script i need to import some modules from a folder 
and than i install the executable in the same folder ; is it possible to compile the script and use the exist modules without need to compile them again with pyinstaller ?

**Comment by htgoebel** [comment]
This should be possible by prepending `sys.path` with sys._MEIPASS. See `runtime information` in the manual for more information.

**Comment by seghier** [comment]
thank you ; i tried without success
