### ISSUE TITLE
"datas" is "binaries"?

### ISSUE THREAD

**Issue by HuberTRoy** [pyinstaller/pyinstaller#2826]
I created a spec file,
```
a = Analysis(...
             datas=[('imgs/logo.png', 'imgs')],
             ...)

....
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          ...)

coll = COLLECT(exe,
               a.datas
)
```

"binaries" has too many files, so I want to make it in exe, but imgs folder was not created.
I got the dist
```
base_library.zip
name.exe
name.exe.manifest
```
I printed the datas and got this
`[('base_library.zip', 'build\\make\\base_library.zip', 'DATA')]`
I checked `building/build_main.py` and found this at line 218
```
       if binaries:
            logger.info("Appending 'binaries' from .spec")
            for name, pth in format_binaries_and_datas(binaries, workingdir=spec_dir):
                self.binaries.append((name, pth, 'BINARY'))
        if datas:
            logger.info("Appending 'datas' from .spec")
            for name, pth in format_binaries_and_datas(datas, workingdir=spec_dir):
                self.**binaries**.append((name, pth, 'DATA'))
```

"binaries" and "datas" are added to binaries? so, "datas" is "binaries"?

**Comment by htgoebel** [comment]
Thanks for you bug-report. Seems like you found a long standing bug which has been in the code since this feature was added, see a3555a1eab6c147fb74ffc9e022bbdb4a3f014dd.

Indeed, `a.datas` is empty and the image is contained in `a.binaries`.

Beside this I do not understand what you mean with:
> "binaries" has too many files, so I want to make it in exe, but imgs folder was not created.

**Comment by HuberTRoy** [comment]
@htgoebel 
e...sorry, I'm still in learning English...

I want to make an exe with this:
```
other_files
--- xxx.png
--- yyy.jpg
name.exe
```

if "a.binaries" is ```[('x/y.dll', 'x/y.dll', 'BINARY')]``` that will produce ```x/y.dll``` in dist. And if  "a.datas" is ```[('x/y.dll', 'x/y.dll', 'DATA')]``` that will also produce ```x/y.dll``` in dist.
I don't know what the difference with them.

But "a.binaries" has too many files by default, such as ```api-ms-win-core-datetime-l1-1-0.dll....```,
so
```
exe = EXE(pyz,
          a.binaries,
          ...)
```
will contains ```api-ms-win-core-datetime-l1-1-0.dll.``` in one-file.

And
```
a.datas =[('imgs/logo.png', 'imgs')]
 coll = COLLECT(exe,
               a.datas
)
```
will produce 
```
imgs
--- logo.png
```

But when I use "a.datas", it is not worked. So I had this issue and thanks for your answer.( • ̀ω•́ )✧

**Comment by htgoebel** [comment]
> if "a.binaries" is [('x/y.dll', 'x/y.dll', 'BINARY')] that will produce x/y.dll in dist. And if "a.datas" is [('x/y.dll', 'x/y.dll', 'DATA')] that will also produce x/y.dll in dist.
I don't know what the difference with them.

This currently missing in the documentations. For now please see https://github.com/pyinstaller/pyinstaller/issues/2733#issuecomment-321866672 for an explanation about the difference.

> But "a.binaries" has too many files by default … will contains ….dll. in one-file.

I assume you mean: When using one-file mode, the .dll is included into the .exe? This is how one-file mode is working: Everything is packed into a single file.

> But when I use "a.datas", it is not worked. So I had this issue and thanks for your answer.

Now I think, I understood what you mean: You want to add `logo.png`, but when you pass it as `Analysis(…, datas=[('imgs/logo.png', 'imgs')])` it will end up in `a.binaries`. This is why you want to add it using `a.datas =[('imgs/logo.png', 'imgs')]; COLLECT(…)`. Did I understand this correctly?

If the later is the case: You need use `a.datas =[('imgs/logo.png', 'imgs', 'DATA')]`. But for beeing futer-proof I suggest to write it as
```
my_datas = [('imgs/logo.png', 'imgs', 'DATA')] # <-- do no *overwrite* a.datas
 coll = COLLECT(exe,
               a.datas,
       my_datas   # <---
)
```

Over all, this looks like you are mixing one-file mode and one-dir mode: Using "EXE(…, a.binaries)" plus `COLLECT()` does not make much sense for me. But your use-case may be special.

**Comment by HuberTRoy** [comment]
@htgoebel 
( • ̀ω•́ )✧Yes, I mean this. And I also want to make all files in one-file. But I cannot success.

If I had a `test.py`:
```x = open('doc/help.txt', 'r'); print(x.read(10)); x.close()```.
And I make a spec file
```
a = Analysis(['test.py'],
                     ...)

my_datas = [[('doc/help.txt', 'doc', 'DATA')]]  # it should be [[('doc/help.txt', 'doc/help.txt', 'DATA')]] , I wrote wrong before, sorry.
exe = EXE(pyz,
          a.binaries,
          a.datas,
          my_datas,
          ...)
```
without coll. 
The dist is
```
test.exe
```

When I run this exe, it will be not worked. Although `%temp%/_MEIxxxx/` has ```doc/help.txt``` but it cannot find it.(╯︵╰)

 I need to add `import os; os.chdir(%temp%/_MEIxxxx)` in `test.py`.
Or use coll to make this kind of dist:
```
doc
---help.txt
test.exe 
```
Whether I miss something in the documentations?

**Comment by tallforasmurf** [comment]
Read [this page](http://pythonhosted.org/PyInstaller/runtime-information.html) and try the code at the end. That may help.

**Comment by HuberTRoy** [comment]
@tallforasmurf 
Thanks, now I know how to get the folder of `%temp%/_MEIxxxx`.

**Comment by htgoebel** [comment]
I assume this is solved now.

**Comment by htgoebel** [comment]
Uh, wrong, we still need to fix "datas" is "binaries". Pull-request anybody? We just need to think about any possible consequences. I assume there are non, but we need to check in the code. Volunteers are welcome!
