### ISSUE TITLE
Pyinstaller with Tensorflow takes incorrect path for _checkpoint_ops.so file

### ISSUE THREAD

**Issue by piyushshri** [pyinstaller/pyinstaller#2828]
I am trying to make an executable of my Python code which uses Tensorflow . The executable gets generated correctly but when I try to run it, I get the following error:

```
Traceback (most recent call last):
  File "detection_init.py", line 14, in <module>
    import lib.tensorboxDetector as tensorboxDetector
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "lib/tensorboxDetector.py", line 26, in <module>
    from lib.train import build_forward
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "lib/train.py", line 4, in <module>
    import tensorflow.contrib.slim as slim
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/__init__.py", line 22, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/bayesflow/__init__.py", line 24, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/bayesflow/python/ops/csiszar_divergence.py", line 26, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/bayesflow/python/ops/csiszar_divergence_impl.py", line 42, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/framework/__init__.py", line 89, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/framework/python/ops/__init__.py", line 24, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "tensorflow/contrib/framework/python/ops/checkpoint_ops.py", line 32, in <module>
  File "tensorflow/contrib/util/loader.py", line 55, in load_op_library
  File "tensorflow/python/framework/load_library.py", line 64, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: tensorflow/contrib/util/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so: cannot open shared object file: No such file or directory
[11241] Failed to execute script detection_init
```
If we look carefully, Pyinstaller is expecting the file `_checkpoint_ops.so` in directory `tensorflow/contrib/util/tensorflow/contrib/framework/python/ops/` but there's no directory like this. `_checkpoint_ops.so` is located at `tensorflow/contrib/framework/python/ops/`.

## What I have tried:
1. I am running dev version of Pyinstaller `27 INFO: PyInstaller: 3.3.dev0+7de49a263`
2. Tried using both `--onefile` and `--onedir` option
3. Tried including _checkpoint_ops.so in spec by adding the binary `pyinstaller --add-binary '/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so' detection_init.py`
4. Tried adding `Tensorflow` as a hidden import
5. Running without UPX `31 INFO: UPX is not available.`
6. Running with `--clean` option
7. The file `detection_init.py` works fine when run directly in Python

**Comment by htgoebel** [comment]
Please try to find out what it is happening at File "tensorflow/python/framework/load_library.py", line 64, in load_op_library or at File "tensorflow/contrib/framework/python/ops/__init__.py", line 24. It looks like – for whatever reason – an absolute path is used there: "tensorflow/contrib/util/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so: cannot open shared object file: No such file or directory".

Maybe this needs to be "adopted to been frozen" (see the manual).

Adding Tensorflow as hidden import is of no use since tensorflow is included as you can see in the traceback. Mayby adding `_checkpoint_ops.so` as `binaries` would help.

If you solved this, we *really* appreciate if you'd contribute a hook, so others will not step into the same trap.

**Comment by nejch** [comment]
@piyushshri I'm on mobile now but if you can't get the hook to work I can also try and have a look later and see if I can help.

**Comment by piyushshri** [comment]
Line 24 at `tensorflow/contrib/framework/python/ops/__init__.py` is 

`from tensorflow.contrib.framework.python.ops.checkpoint_ops import *`

and line 64 at `tensorflow/python/framework/load_library.py` is raising the said exception.

I am reading through https://pyinstaller.readthedocs.io/en/stable/hooks.html page to understand hooks, however, can there be a direct way to tell pyinstaller to load this shared object file from the correct path?

**Comment by htgoebel** [comment]
You need to understand tensorflow/python/framework/load_library.py does *around* line 64. Why is it running into raising an error. It's like debugging :-)

**Comment by vbadri** [comment]
I have the same issue. I did notice that there is actually a _checkpoint_ops.so file elsewhere. 

Actual path:  <python-site-packages>/tensorflow/contrib/framework/python/ops/_checkpoint_ops.so
Assumed path: <python-site-packages>/tensorflow/contrib/util/tensorflow/contrib/framework/python/ops?_checkpoint_ops.so

Baiscally pyinstaller is looking until tensorflow/contrib/util, where it should be looking under site-packages

So how does one tell pyinstaller the correct path?

**Comment by vbadri** [comment]
I'm not sure exactly why pyinstaller throws a fit about this. python itself is able to load the path correctly. 

However, it turns out the libraries are loaded and then not used at all. In fact, recent tensorflow source code does not include this useless library loading anyway. 

A simple one line work around is this: 

edit ..tensorflow/python/framework/load_library.py
change the function load_op_library so it just returns None

works just fine..

**Comment by goodloop** [comment]
I update tensorflow to version 1.4, and seems other looking for other so, such as site-`packages/tensorflow/contrib/util/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so`
seems the same problem here.

IMHO, I think there are some problem with pyinstaller with support tensorflow's `resource_loader.get_path_to_datafile(...)` methods.
Any solutions for this?

**Comment by noe** [comment]
Until we find what's going on, I monkey patched tensorflow to _fix_ the path and it works. I just overwrite function `load_op_library` to simply remove the first part of the path, till the last occurrence of `'site-packages'`, and call the original function with the amended path.

<pre lang="py">
# monkey patch tensorflow
under_pyinstaller = getattr(sys, 'frozen', False)
if under_pyinstaller:
    from tensorflow.python.framework import load_library
    old_load_op_library = load_library.load_op_library
    def new_load_op_library(library_filename):
        if library_filename.count('site-packages') > 1:
            library_filename = library_filename[library_filename.rfind('site-packages'):]
        return old_load_op_library
    load_library.load_op_library = new_load_op_library
</pre>

**Comment by bloodbare** [comment]
A hacky solution it works for us is to copy site-packages on the place were the pyinstaller binary is (you only need tf/contrib/util pythonpath) and then copy again site-packages again inside site-packages/tensorflow/contrib/util (again you only need tensorflow .so if you want to reduce the amount of load).

On Dockerfile:

```
COPY pybinary /
RUN cp -r /usr/local/lib/python3.5/site-packages /
RUN cp -r /usr/local/lib/python3.5/site-packages /site-packages/tensorflow/contrib/util/
```
The problem is due to how tensorflow loads dynamic libraries based on path and how pyinstaller packages them.

**Comment by hadikazemi** [comment]
@bloodbare Do you mean `dist-packages`? and could you please make it more clear?
Do you mean I need to copy `/usr/local/lib/python3.5/dist-packages` to where the pyinstaller created the binary file? I mean something like `dist/main/`when my python filename is `main.py`? and then?
Thank you,

BTW, I have the same problem: 
`tensorflow.python.framework.errors_impl.NotFoundError: tensorflow/contrib/util/tensorflow/contrib/framework/python/ops/_gru_ops.so: cannot open shared object file: No such file or directory
[11241] Failed to execute script detection_init`

**Comment by hadikazemi** [comment]
I found a way to get it run. I added the following line of code at the beginning of the Tensorflow `load_op_library` function:
`library_filename = library_filename.split('/')[-1]`
**Keep in mind that you need to remove this line after you are done with PyInstaller.**
Now, you need to add the following binary files to the `.spec` file (replace `/home/hadi/.local/` with your path):

`binaries=[('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/_gru_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/rnn/python/ops/_lstm_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/layers/python/ops/_sparse_feature_cross_op.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/tpu/python/ops/_tpu_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/cudnn_rnn/python/ops/_cudnn_rnn_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/image/python/ops/_distort_image_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/input_pipeline/python/ops/_input_pipeline_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/image/python/ops/_image_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/factorization/python/ops/_clustering_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/image/python/ops/_single_image_random_dot_stereograms.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/factorization/python/ops/_factorization_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/memory_stats/python/ops/_memory_stats_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_tensor_forest_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/nccl/python/ops/_nccl_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/seq2seq/python/ops/_beam_search_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/resampler/python/ops/_resampler_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_stats_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/tensor_forest/python/ops/_model_ops.so', '.'), ('/home/hadi/.local/lib/python2.7/site-packages/tensorflow/contrib/tensor_forest/libforestprotos.so', '.')],`

Now everything works great. I tried to follow @bloodbare  approach and do not change the Tensorflow function, but for any reason, it didn't work for me.

**Comment by jongiambi** [comment]
In addition to adding the binaries as @hadikazemi mentioned I also had to get tensorflow to point to the relative path of the `.so` files while running as a native OSX .app. 

I added/modified the `load_library.py` file in tensorflow to use the relative path of the .app.

```
def resource_path(relative_path):
    """Due to pyinstaller changing root dir of project filenames need to be processed in order to open properly

    Parameters
    ----------
    relative_path : str
        String containing filename of project data file

    Returns
    -------
    path : str
        path relative to .exe/.app on local computer
    """
    import sys
    import os

    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    path = os.path.join(base_path, relative_path)
    return path

def load_op_library(library_filename):
  """Loads a TensorFlow plugin, containing custom ops and kernels.

  Pass "library_filename" to a platform-specific mechanism for dynamically
  loading a library. The rules for determining the exact location of the
  library are platform-specific and are not documented here. When the
  library is loaded, ops and kernels registered in the library via the
  `REGISTER_*` macros are made available in the TensorFlow process. Note
  that ops with the same name as an existing op are rejected and not
  registered with the process.

  Args:
    library_filename: Path to the plugin.
      Relative or absolute filesystem path to a dynamic library file.

  Returns:
    A python module containing the Python wrappers for Ops defined in
    the plugin.

  Raises:
    RuntimeError: when unable to load the library or get the python wrappers.
  """ 
  # REMOVE AFTER PYINSTALLER USE
  library_filename = resource_path(library_filename.split('/')[-1])
  
```

I also added the following to my spec file to find/bundle the tensorflow binaries automatically:

```
import os

tensorflow_location = '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/tensorflow'

tensorflow_binaries = []

for dir_name, sub_dir_list, fileList in os.walk(tensorflow_location): 
  for file in fileList:
    if file.endswith(".so"):
      full_file = dir_name + '/' + file
      print(full_file)
      tensorflow_binaries.append((full_file, '.'))

```

**Comment by andrewjong** [comment]
For anyone who stumbles into this in the future, copying all the *.so files from tensorflow/contrib/** to where your executable looks for them works! 

Just have to read the Error output carefully. Mine said: 
```bash
tensorflow.python.framework.errors_impl.NotFoundError: dist/test_Sony/tensorflow/contrib/util/_dataset_ops.so: cannot open shared object file: No such file or directory
```
so I just moved all the *.so files to `dist/test_Sony/tensorflow/contrib/util/` using the `find` bash command to recursively find files:
```bash
find ~/.conda/envs/YOUR_ENVIRONMENT/lib/python3.6/site-packages/tensorflow/contrib -name "*.so" -exec cp {} tensorflow/contrib/util \;
```

**Comment by aodiwei** [comment]
@andrewjong 's way works for me, more efficient way for all tensorflow so file copy
`find /usr/local/lib/python3.5/dist-packages/tensorflow -name *.so |xargs -i cp --parents {}  ./dist/app_name/tensorflow/`

**Comment by htgoebel** [comment]
@hadikazemi @jongiambi Now that sou found a solution: We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.
