### ISSUE TITLE
GDAL import error with newer versions of conda gdal

### ISSUE THREAD

**Issue by davidh-ssec** [pyinstaller/pyinstaller#2829]
Yet another problem with gdal and pyinstaller. I'm using current develop branch and first noticed this issue on mac, but now have it failed on linux for newer versions of gdal. Both are installed via conda with conda-forge channel added using python 3.6. It could be possible that my application has never run on mac after being bundled by pyinstaller (I guess I need more users). Here's the example script:

```
from osgeo import gdal_array
```

Running `pyinstaller test.py` and running it gives you:

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    from osgeo import gdal_array
  File "/Users/davidh/repos/git/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/osgeo/gdal_array.py", line 164, in <module>
ImportError: cannot import name '_gdal_array'
```

The line numbers very depending on gdal version. Currently testing with gdal 2.1.4 and 2.2.x. On linux gdal 2.1.3 works, on mac gdal 2.1.3 gives a different error. The issue seems to be that `osgeo/gdal_array.py` tries to import `_gdal_array.so` multiple ways depending on what works and what doesn't:

1. `fp, pathname, description = imp.find_module('_gdal_array', [dirname(__file__)])`
2. `import _gdal_array`
3. `from . import _gdal_array`

Some or all of these fail because the `gdal_array.py` file thinks its in `.../osgeo`, but its not so that path stuff fails. The second import usually works because it finds it in the current directory. The `from . import _gdal_array` seems to fail in most cases. If I comment it out the entire module imports fine. That third import seems redundant but there has to be a reason they are doing it. I'm going to try a few things out and try to get a fix that isn't completely gross.

**Comment by davidh-ssec** [comment]
This is the change that breaks things: https://trac.osgeo.org/gdal/ticket/6801

**Comment by htgoebel** [comment]
So this is gasl error, isn't it? What do you expect PyInstaller to do then?

**Comment by davidh-ssec** [comment]
See my gdal issue on this issue for details on GDAL: https://trac.osgeo.org/gdal/ticket/7044

Also notice that this will be fixed in GDAL 2.2.2. For anyone needing a fix in the mean time you have two options:

1. Install pyinstaller from a git clone and edit the `hook-osgeo.py`:

```from glob import glob
binaries += [(glob(os.path.join(root_path, 'lib', 'python*', 'site-packages', 'osgeo', '_gdal_array*.*'))[0], 'osgeo/')]
```

You may have to initialize `binaries = []` further up the hook module.

2. Edit your install of gdal `site-packages/osgeo/gdal_array.py` and find the `from . import _gdal_array` line and comment it out.

**Comment by Guts** [comment]
Thanks to report, I'll keep in mind until next GDAL release.

**Comment by davidh-ssec** [comment]
@htgoebel FYI the reason this is technically something pyinstaller *could have* fixed is that GDAL works in every other environment except pyinstaller's.

**Comment by htgoebel** [comment]
@davidh-ssec Well, in your first post you describe some problem and how to fix it by changing gdal. This might be a problem with relative imports in PyInstaller or the the gdal hooks, but this is not what you are describing. When I asked what you expect PyInstaller to do, you pointed to the GDAL bug-report. So for I don't see any task for PyInstaller.

Please understand that I'm not able to track down each and every issue reported, or have a look at the effected package's source. I need the information prepared. If you think, this is a PyInstaller issue, please describe it in a way that I can see what the problem with PyInstaller is and what needs to be changed.

So the very first question is: What's going on at File "site-packages/osgeo/gdal_array.py", line 164 and why does PyInstaller not include this .so file?

**Comment by davidh-ssec** [comment]
@htgoebel I think there was a major misunderstanding here. Bottom line pyinstaller does not need to do anything to fix this.

In my last comment I was just trying to describe that the original reason I made this issue was because it seemed like GDAL worked everywhere except when I used it with pyinstaller. I had found a "fix" for it by manipulating the pyinstaller hook. BUT later on I found out the issue *seen* by pyinstaller is actually an issue with GDAL.

Issue closed. Good to go.

**Comment by htgoebel** [comment]
@davidh-ssec Thanks for clarifying. Indeed I understood "works everywhere EXCEPT PyInstaller".

**Comment by awa5114** [comment]
I am using gdal 2.2.2 and this problem still occurs

**Comment by tgmueller** [comment]
I'm using 2.3.2 and am having the same problem.
