### ISSUE TITLE
3.3 maintenance branch / 3.3.1 milestone

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#2832]
It looks like pyinstaller 3.3(.0) is at the horizon, yay! (thanks for cleaning up the milestone)

https://github.com/pyinstaller/pyinstaller/milestone/16

Guess quite some projects are already waiting for that release (as it supports py36), but at the same time, there is the usual issue with .0 releases that they include rather big changes and thus there is some probability for new bugs or other issues.

To minimize risk and improve projectability, it would be nice if there would be some `3.3-maint` maintenance branch and also a 3.3.1 milestone created directly at 3.3(.0) release time. Only pressing issues that come up with 3.3(.0) would get adopted into the 3.3.1 milestone, so it can be released near-term.

Then potential users could see that if they jump on 3.3(.0) and there is some bug or issue, that there are precautions taken that it can be fixed near-term without having to wait for 3.4(.0) (which might take longer and basically has the same problem).

**Comment by htgoebel** [comment]
How is going to maintain this branch? Volunteers are welcome *hint, hint*.

**Comment by ThomasWaldmann** [comment]
I don't think that the decision what stuff gets backported into the maintenance branch can be delegated to people not very much involved into the project.

Also, doing a maintenance-backport of some changeset is of course usually best / easiest done by the developer who made the changeset in the first place.

**Comment by htgoebel** [comment]
I created a milestone for [Hostfix 3.3.1](https://github.com/pyinstaller/pyinstaller/milestone/18). But as long as there is nobody volunteering to maintain release 3.3, there will be not maintenance branch.
