### ISSUE TITLE
Prepare using towncrier

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#2837]
Following up the discussion (see #2756) about implementing the use of [towncrier](https://pypi.org/project/towncrier/): Things we need for **towncrier**:

- [x] decide about where to collect the newsfragments (`docs/news`, `news`, `news.d`, `changes.d`, …)
- [x] decide about types of changes, section titles, etc. Esp. we need a section "hooks". These [seem to be configurable](https://github.com/python-attrs/attrs/blob/0d04d5e7fc6de9eb6d70839dfda994d2a4bfa80f/pyproject.toml)
        For reference: sections in the 3.3 changelog will be "Incompatible changes", "Hooks" (new and updated, fixed), "Bootloader", "Bootloader build", "Module loader" (since this effects e.g. pkgressources), "PyInstaller core" (with subsections "modulegraph" and "Included 3rd-party libraries"), "Test-suite and Continuous Integration", "Documentation", "Known Issues"
- [X] learn how to specify the platform in a type (if this is useful).
  This can not be done using a "type". The adequate solution is to prefix the newsfragment text with the platform, etc in parenthesis.
- [x] find out how we can keep the whole changelog in the file, not only the "news"
- [x] create a template matching our layout
- [x] update the developer documentation
- [x] update the release documentation

@xoviat I'd appreciate if you'd provide a proposal for the first points. I'll take care of updating the documentation.

**Comment by htgoebel** [comment]
@xoviat I'd like follow your idea and use towncrier so we can speed up the release process (as you originally pushed to do). Can you please prepare this so we can put it in place after the 3.3.1 release?! Thanks.

**Comment by htgoebel** [comment]
We might also need a section "Relaese process" or so, where we can collect changes to setup.py, towncrier setup, etc.

**Comment by xoviat** [comment]
The only changes required to add towncrier for now are to add a "news" folder with the changes as seen here:

https://github.com/pypa/pip/tree/5d951b2a94b9b3e07e3ed23b6d39a882f8f364aa/news

We would also ideally have a bot to check this, but we can have a script run that checks the diff, I guess.

**Comment by htgoebel** [comment]
I'm afraid, there is more todo :-) Please have a look at the first entry of this ticket.

**Comment by htgoebel** [comment]
This is done.
