### ISSUE TITLE
Python 3.6 on the horizon?

### ISSUE THREAD

**Issue by BjornFJohansson** [pyinstaller/pyinstaller#2845]
Hi, I understood that there is not yet a pyinstaller for python 3.6 ?
Is one on the horizon?
cheers,
Bjorn

**Comment by nejch** [comment]
You need to install the develop branch to use pyinstaller with 3.6: https://github.com/pyinstaller/pyinstaller/wiki#downloads

It looks like pyinstaller 3.3 stable will be released soon, though.

**Comment by BjornFJohansson** [comment]
Thanks for the response! I will try it out now.

**Comment by htgoebel** [comment]
See https://github.com/pyinstaller/pyinstaller/milestone/16

**Comment by htgoebel** [comment]
Release 3.3 is out now.
