### ISSUE TITLE
Error on AARCH64 

### ISSUE THREAD

**Issue by ddcien** [pyinstaller/pyinstaller#2848]
I had a try pyinstaller on my aarch64 platform with a very simple python script, and it is not working.

Below is the python script
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-

if __name__ == '__main__':
    print("Hello PyInstaller")
```

And here is the result of `uname -a`:
```
dietpi@DietPi:/tmp/test$ uname -a
Linux DietPi 4.10.0-sun50iw2 #1 SMP Tue May 2 12:07:11 BST 2017 aarch64 GNU/Linux
```
 
The output of the command `pyinstaller -F test.py` is as below
```
dietpi@DietPi:/tmp/test$ pyinstaller -F test.py 
276 INFO: PyInstaller: 3.3.dev0-g8e199eb
277 INFO: Python: 3.4.2
278 INFO: Platform: Linux-4.10.0-sun50iw2-aarch64-with-debian-8.9
280 INFO: wrote /tmp/test/test.spec
289 INFO: UPX is available.
293 INFO: Extending PYTHONPATH with paths
['/tmp/test', '/tmp/test']
294 INFO: checking Analysis
294 INFO: Building Analysis because out00-Analysis.toc is non existent
295 INFO: Initializing module dependency graph...
298 INFO: Initializing module graph hooks...
313 INFO: Analyzing base_library.zip ...
14326 INFO: Processing pre-find module path hook   distutils
25520 INFO: running Analysis out00-Analysis.toc
25611 INFO: Caching module hooks...
25639 INFO: Analyzing /tmp/test/test.py
25664 INFO: Loading module hooks...
25666 INFO: Loading module hook "hook-pydoc.py"...
25668 INFO: Loading module hook "hook-xml.py"...
27813 INFO: Loading module hook "hook-sysconfig.py"...
27820 INFO: Loading module hook "hook-encodings.py"...
28179 INFO: Loading module hook "hook-distutils.py"...
28241 INFO: Looking for ctypes DLLs
28241 INFO: Analyzing run-time hooks ...
28290 INFO: Looking for dynamic libraries
28885 INFO: Looking for eggs
28886 INFO: Python library not in binary dependencies. Doing additional searching...
28985 INFO: Using Python library /usr/lib/aarch64-linux-gnu/libpython3.4m.so.1.0
28999 INFO: Warnings written to /tmp/test/build/test/warntest.txt
29097 INFO: checking PYZ
29097 INFO: Building PYZ because out00-PYZ.toc is non existent
29097 INFO: Building PYZ (ZlibArchive) /tmp/test/build/test/out00-PYZ.pyz
31402 INFO: Building PYZ (ZlibArchive) /tmp/test/build/test/out00-PYZ.pyz completed successfully.
31470 INFO: checking PKG
31471 INFO: Building PKG because out00-PKG.toc is non existent
31471 INFO: Building PKG (CArchive) out00-PKG.pkg
38667 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
38699 INFO: Bootloader /usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/bootloader/Linux-64bit/run
38700 INFO: checking EXE
38700 INFO: Building EXE because out00-EXE.toc is non existent
38701 INFO: Building EXE from out00-EXE.toc
38702 INFO: Appending archive to ELF section in EXE /tmp/test/dist/test
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 9, in <module>
    load_entry_point('PyInstaller==3.3.dev0-g8e199eb', 'console_scripts', 'pyinstaller')()
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/building/build_main.py", line 790, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/building/build_main.py", line 736, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/building/api.py", line 420, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/building/api.py", line 581, in assemble
    raise SystemError("objcopy Failure: %s" % stderr)
SystemError: objcopy Failure: objcopy: Unable to recognise the format of the input file `/tmp/test/dist/test'
```

And the result of the `file /tmp/test/dist/test` is 
```
dietpi@DietPi:/tmp/test$ file /tmp/test/dist/test 
/tmp/test/dist/test: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=e8962f138a6e900c9fde0f0c3a9ab9e8b58de3e9, stripped
```

**Comment by htgoebel** [comment]
Did you recompile the bootloader for aarch64?

**Comment by ddcien** [comment]
Yes. I had recompiled the booloader on the target platform. 

Here is the result:
```
python ./waf distclean all
'distclean' finished successfully (0.002s)
'all' finished successfully (0.001s)
'distclean' finished successfully (0.001s)
Setting top to                           : /tmp/pyinstaller/bootloader 
Setting out to                           : /tmp/pyinstaller/bootloader/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Checking size of pointer                 : 8 
Platform                                 : Linux-64bit detected based on compiler 
Checking for program '/usr/bin/strip'    : /usr/bin/strip 
Checking for program 'strip'             : /usr/bin/strip 
Checking for library dl                  : yes 
Checking for library m                   : yes 
Checking for library z                   : yes 
Checking for function unsetenv           : yes 
Checking for function mkdtemp            : yes 
Checking for flags -Wl,--as-needed       : yes 
'configure' finished successfully (2.701s)
'make_all' finished successfully (0.019s)
Waf: Entering directory `/tmp/pyinstaller/bootloader/build/debug'
[ 1/13] Compiling src/main.c
[ 2/13] Compiling src/pyi_archive.c
[ 3/13] Compiling src/pyi_global.c
[ 4/13] Compiling src/pyi_launch.c
[ 5/13] Compiling src/pyi_main.c
[ 6/13] Compiling src/pyi_path.c
[ 7/13] Compiling src/pyi_python.c
[ 8/13] Compiling src/pyi_python27_compat.c
[ 9/13] Compiling src/pyi_pythonlib.c
[10/13] Compiling src/pyi_utils.c
[11/13] Compiling src/pyi_win32_utils.c
[12/13] Linking build/debug/run_d
[13/13] Processing build/debug/run_d
Waf: Leaving directory `/tmp/pyinstaller/bootloader/build/debug'
'build_debug' finished successfully (1.927s)
Waf: Entering directory `/tmp/pyinstaller/bootloader/build/release'
[ 1/13] Compiling src/main.c
[ 2/13] Compiling src/pyi_archive.c
[ 3/13] Compiling src/pyi_global.c
[ 4/13] Compiling src/pyi_launch.c
[ 5/13] Compiling src/pyi_main.c
[ 6/13] Compiling src/pyi_path.c
[ 7/13] Compiling src/pyi_python.c
[ 8/13] Compiling src/pyi_python27_compat.c
[ 9/13] Compiling src/pyi_pythonlib.c
[10/13] Compiling src/pyi_utils.c
[11/13] Compiling src/pyi_win32_utils.c
[12/13] Linking build/release/run
[13/13] Processing build/release/run
Waf: Leaving directory `/tmp/pyinstaller/bootloader/build/release'
'build_release' finished successfully (1.804s)
Waf: Entering directory `/tmp/pyinstaller/bootloader/build/debug'
[14/14] Processing build/debug/run_d
+ install /tmp/pyinstaller/PyInstaller/bootloader/Linux-64bit-aarch/run_d (from build/debug/run_d)
Waf: Leaving directory `/tmp/pyinstaller/bootloader/build/debug'
'install_debug' finished successfully (0.063s)
Waf: Entering directory `/tmp/pyinstaller/bootloader/build/release'
[14/14] Processing build/release/run
+ install /tmp/pyinstaller/PyInstaller/bootloader/Linux-64bit-aarch/run (from build/release/run)
Waf: Leaving directory `/tmp/pyinstaller/bootloader/build/release'
'install_release' finished successfully (0.063s)
```

And here is the information of all the bootloaders installed:
```
$ ls -l /usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/bootloader
total 28
drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Darwin-64bit
drwxr-sr-x 2 root staff 4096 Sep 21 12:14 images
drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Linux-32bit
drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Linux-64bit
drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Linux-64bit-aarch
drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Windows-32bit
drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Windows-64bit
```
```
$ file Linux-64bit/*
Linux-64bit/run:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=e8962f138a6e900c9fde0f0c3a9ab9e8b58de3e9, stripped
Linux-64bit/run_d: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=0c31ae6dbad230a5fbabc748b9530d25679a5b1f, stripped
```
```
$ file Linux-64bit-aarch/*
Linux-64bit-aarch/run:   ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=fb0e05036e98d8df78286fc9a82e2bd100fb98ef, stripped
Linux-64bit-aarch/run_d: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=68ce2e0146630d66630c96e14a8e78781a0b8ba1, stripped
```

And now I copy `run` and `run_d` in `Linux-64bit-aarch` to `Linux-64bit`. 
IT WORKS!!!

**Comment by htgoebel** [comment]
> It uses the WRONG bootloader on Linux-64bit-aarch platform.

Not really :-) It uses *the* Linux bootloader, while there is none for 64bit-aarch. See #2849. Maybe you want to work on that issue?!

**Comment by pikeszfish** [comment]
I got this error too.
I have recompile the bootloader for aarch64.
When I ran pyinstaller on `143 INFO: Platform: Linux-4.10.0-26-generic-aarch64-with-debian-8.9`,
 it still use bootloader in Linux-64bit
`111681 INFO: Bootloader /usr/local/lib/python2.7/site-packages/PyInstaller-3.3+4e8e0ff7a-py2.7.egg/PyInstaller/bootloader/Linux-64bit/run`
rather than `....../Linux-64bit-aarch`.
So I copy `run` and `run_d` in Linux-64bit-aarch to Linux-64bit.
IT WORKS!!!

**Comment by anagha-ana** [comment]
> Yes. I had recompiled the booloader on the target platform.
> 
> Here is the result:
> 
> ```
> python ./waf distclean all
> 'distclean' finished successfully (0.002s)
> 'all' finished successfully (0.001s)
> 'distclean' finished successfully (0.001s)
> Setting top to                           : /tmp/pyinstaller/bootloader 
> Setting out to                           : /tmp/pyinstaller/bootloader/build 
> Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
> Checking size of pointer                 : 8 
> Platform                                 : Linux-64bit detected based on compiler 
> Checking for program '/usr/bin/strip'    : /usr/bin/strip 
> Checking for program 'strip'             : /usr/bin/strip 
> Checking for library dl                  : yes 
> Checking for library m                   : yes 
> Checking for library z                   : yes 
> Checking for function unsetenv           : yes 
> Checking for function mkdtemp            : yes 
> Checking for flags -Wl,--as-needed       : yes 
> 'configure' finished successfully (2.701s)
> 'make_all' finished successfully (0.019s)
> Waf: Entering directory `/tmp/pyinstaller/bootloader/build/debug'
> [ 1/13] Compiling src/main.c
> [ 2/13] Compiling src/pyi_archive.c
> [ 3/13] Compiling src/pyi_global.c
> [ 4/13] Compiling src/pyi_launch.c
> [ 5/13] Compiling src/pyi_main.c
> [ 6/13] Compiling src/pyi_path.c
> [ 7/13] Compiling src/pyi_python.c
> [ 8/13] Compiling src/pyi_python27_compat.c
> [ 9/13] Compiling src/pyi_pythonlib.c
> [10/13] Compiling src/pyi_utils.c
> [11/13] Compiling src/pyi_win32_utils.c
> [12/13] Linking build/debug/run_d
> [13/13] Processing build/debug/run_d
> Waf: Leaving directory `/tmp/pyinstaller/bootloader/build/debug'
> 'build_debug' finished successfully (1.927s)
> Waf: Entering directory `/tmp/pyinstaller/bootloader/build/release'
> [ 1/13] Compiling src/main.c
> [ 2/13] Compiling src/pyi_archive.c
> [ 3/13] Compiling src/pyi_global.c
> [ 4/13] Compiling src/pyi_launch.c
> [ 5/13] Compiling src/pyi_main.c
> [ 6/13] Compiling src/pyi_path.c
> [ 7/13] Compiling src/pyi_python.c
> [ 8/13] Compiling src/pyi_python27_compat.c
> [ 9/13] Compiling src/pyi_pythonlib.c
> [10/13] Compiling src/pyi_utils.c
> [11/13] Compiling src/pyi_win32_utils.c
> [12/13] Linking build/release/run
> [13/13] Processing build/release/run
> Waf: Leaving directory `/tmp/pyinstaller/bootloader/build/release'
> 'build_release' finished successfully (1.804s)
> Waf: Entering directory `/tmp/pyinstaller/bootloader/build/debug'
> [14/14] Processing build/debug/run_d
> + install /tmp/pyinstaller/PyInstaller/bootloader/Linux-64bit-aarch/run_d (from build/debug/run_d)
> Waf: Leaving directory `/tmp/pyinstaller/bootloader/build/debug'
> 'install_debug' finished successfully (0.063s)
> Waf: Entering directory `/tmp/pyinstaller/bootloader/build/release'
> [14/14] Processing build/release/run
> + install /tmp/pyinstaller/PyInstaller/bootloader/Linux-64bit-aarch/run (from build/release/run)
> Waf: Leaving directory `/tmp/pyinstaller/bootloader/build/release'
> 'install_release' finished successfully (0.063s)
> ```
> 
> And here is the information of all the bootloaders installed:
> 
> ```
> $ ls -l /usr/local/lib/python3.4/dist-packages/PyInstaller-3.3.dev0_g8e199eb-py3.4.egg/PyInstaller/bootloader
> total 28
> drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Darwin-64bit
> drwxr-sr-x 2 root staff 4096 Sep 21 12:14 images
> drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Linux-32bit
> drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Linux-64bit
> drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Linux-64bit-aarch
> drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Windows-32bit
> drwxr-sr-x 2 root staff 4096 Sep 21 12:14 Windows-64bit
> ```
> 
> ```
> $ file Linux-64bit/*
> Linux-64bit/run:   ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=e8962f138a6e900c9fde0f0c3a9ab9e8b58de3e9, stripped
> Linux-64bit/run_d: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=0c31ae6dbad230a5fbabc748b9530d25679a5b1f, stripped
> ```
> 
> ```
> $ file Linux-64bit-aarch/*
> Linux-64bit-aarch/run:   ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=fb0e05036e98d8df78286fc9a82e2bd100fb98ef, stripped
> Linux-64bit-aarch/run_d: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=68ce2e0146630d66630c96e14a8e78781a0b8ba1, stripped
> ```
> 
> And now I copy `run` and `run_d` in `Linux-64bit-aarch` to `Linux-64bit`.
> IT WORKS!!!
> 
 hello , i am trying to get aarch64 bootloader . iam using ubuntu 64 bit os . i followed the process which you have mentioned  here but i am not getting the bootloader for aarch64 . Can you please help me ?

**Comment by anagha-ana** [comment]
intern@digitallab:~/pyinstaller-3.3/bootloader$ python ./waf distclean all --target-arch=aarch64
'distclean' finished successfully (0.001s)
'all' finished successfully (0.000s)
'distclean' finished successfully (0.000s)
Setting top to                           : /home/intern/pyinstaller-3.3/bootloader 
Setting out to                           : /home/intern/pyinstaller-3.3/bootloader/build 
Checking for 'gcc' (C compiler)          : /usr/bin/gcc 
Platform                                 : Linux-aarch64 manually chosen 
Unrecognized target architecture: aarch64
(complete log in /home/intern/pyinstaller-3.3/bootloader/build/config.log)


This the error i am facing

**Comment by efynn** [comment]
> intern @ digitallab：〜/ pyinstaller-3.3 / bootloader $ python ./waf distclean all --target-arch = aarch64'distclean 
> '成功完成（0.001s）
> 'all'成功完成（0.000s）
> 'distclean'成功完成（0.000 s）
> 设置为：/home/intern/pyinstaller-3.3/bootloader 
> 设置为：/home/intern/pyinstaller-3.3/bootloader/build 
> 检查“ gcc”（C编译器）：/ usr / bin / gcc 
> 平台：手动选择的Linux-aarch64 
> 无法识别的目标体系结构：aarch64 
> （在/home/intern/pyinstaller-3.3/bootloader/build/config.log中的完整日志）
> 
> 这是我面临的错误

I have the same problem. Have you solved it?
