### ISSUE TITLE
Virus reported when installing Version 3.3

### ISSUE THREAD

**Issue by NHades** [pyinstaller/pyinstaller#2866]
When trying to use pip to upgrade from 3.2.1 to 3.3 I get a virus alert and installation fails, here are details:

1. Windows 7 Enterprise 
2. McAfee VirusScan Enterprise 8.8, DAT version 8664 (9/24/17)
3. See attached image for details about what virus scan program reports
![error](https://user-images.githubusercontent.com/6215392/30815621-b961f65e-a1e1-11e7-84d0-fa16859a96ee.PNG)

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
