### ISSUE TITLE
xtrapath not used for binary dependencies

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#287]
**Original date**: 2010/11/18
**Original reporter**: _anonymous_

Hey,

when running PyInstaller I occasionally get errors like "lib not found: my.dll". However, the dll can be found in the xtrapath in my config.dat.
Debugging a bit further, I found the problem to be in Build.py. Target.assemble contains this code:

```
        binaries.extend(bindepend.Dependencies(binaries,
                                               platform=target_platform,
                                               manifest=depmanifest))
```

I've changed this to:

```
        binaries.extend(bindepend.Dependencies(binaries,
                                               xtrapath=config['xtrapath'],
                                               platform=target_platform,
                                               manifest=depmanifest))
```

and everything works.

If there are not any bad side-effects (can't see any, first time I use PyInstaller), can you include this patch?

I am using current trunk on Windows.

**Comment by htgoebel** [comment]
I'm closing this ticket. I is years old, reported by anonymous, nobody worked on it and there are no examples to reproduce it.
