### ISSUE TITLE
AVG detect virus

### ISSUE THREAD

**Issue by seghier** [pyinstaller/pyinstaller#2871]
Hello
i use pyinstaller to create an application; i scanned my system with many antivirus and nothing found.
but when i try to run the app AVG show a message that the exe file was infected with a virus called : 
Win64:Evo-gen

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by seghier** [comment]
hi ; thanks 
i asked you to confirm if this file is inside pyinstaller and it is not a virus .
because just avg show this strange message

**Comment by htgoebel** [comment]
I did not verify anything. Please download the archive, check the signature and compare the included bootloader with the one on your system.

**Comment by seghier** [comment]
hello
again windows defender in windows 10 detect a virus in pyinstaller/bootloader
![vir](https://user-images.githubusercontent.com/6026588/30950212-b262ad58-a41b-11e7-81a7-1e3d34cc42a5.JPG)

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is **nothing** we can do about this false positive.
