### ISSUE TITLE
import pyinstaller runs code

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#2872]
while debugging some other issue, I wanted to look at `pyinstaller.__file__`, so started a python shell and ran `import pyinstaller`.

couldn't do that as it automatically ran the main function, printed usage help and terminated my shell again.

feels like the usual `if __name__ == '__main__':` is missing.

**Comment by htgoebel** [comment]
`pyinstalelr` is just a small helper script. You want to import `PyInstaller`. HTH.
