### ISSUE TITLE
Hiding the window when running?

### ISSUE THREAD

**Issue by DaCurse** [pyinstaller/pyinstaller#2874]
Is there a way to do that? Like .pyw files

**Comment by nejch** [comment]
If you mean the console window (like .pyw), you can add the `--noconsole` (or `-w`) option.

For example:
`pyinstaller --noconsole myscript.py`

See documentation [here](https://pyinstaller.readthedocs.io/en/stable/usage.html#windows-and-mac-os-x-specific-options).
