### ISSUE TITLE
Last bootloader update broke Windows XP compatibility

### ISSUE THREAD

**Issue by alteman** [pyinstaller/pyinstaller#2876]
Commit b5ec3f653020835508b98fbb394272176f927908 updated Windows 32-bit bootloader stubs to have 6.0 as minimum OS version in the PE header. As a result, they don't start on Windows XP.

**Comment by htgoebel** [comment]
Please tell us how we should fix this. Section "building the bootloader" in the manual might be helpful.

**Comment by tenuki** [comment]
@htgoebel can I help you in some way in order to close this one?

**Comment by bwoodsend** [comment]
Even our oldest supported Python version no longer supports XP so this is no longer applicable.
