### ISSUE TITLE
Need to exclude module from build that gets loaded from network - Can't find module after build

### ISSUE THREAD

**Issue by flabbyThoroughbred** [pyinstaller/pyinstaller#2877]
Hi,

I have a script that imports a custom module that I don't want to add to the compiled version for the purposes of updating the module without re-compiling.
I tried to add the module to 'excludes' in the analysis portion of my spec file but the compiled version throws a 'module not found' error when run.
I'm using 3.2.1 (It has to be 3.2.1 for consistency with other tools we build).
The custom module is part of the python path. It's nothing I can't see normally. I can import it from the terminal python and it loads fine when I run my script from the command line.

Is there a step I'm missing? Do I have to explicitly include the append path or something in my code?

Thanks in advance!
-Mark

**Comment by tallforasmurf** [comment]
This is an interesting problem. If I understand you, you want to be able to be able to replace a module of code in the field, perhaps by just emailing a new module to your users. Right? I looked into this for an app of mine once but did not find any solution. The only way to do maintenance I know, is to make a new complete app and have users download the whole thing. So a solution would be useful(*).

PyInstaller finds all imported Python code modules and tucks them away in its special ZLib archive, which is packed at the end of the executable. (See http://pythonhosted.org/PyInstaller/advanced-topics.html#inspecting-archives) They are not in the usual places. The run-time import mechanism is modified to look first in the archive. It is not clear to me where an import will search next, when a module is not in the Zlib.

The challenge is to find a way to (1) exclude a module from the normal bundle; (2) add the module to the bundle but outside of the archive (as a data file maybe?) such that (3) it will be found by import at run-time.

I do not know a solution but maybe someone else has an idea.

(*) Realize that being able to field-replace a module introduces a big security hole! A bad guy could send out a module with evil code in it, and your users would install and run it. You need to have some way to "sign" or validate the replacement code.

**Comment by htgoebel** [comment]
Scratch:
1) Remove the module from a.pure (but remember the entry)
2) Add `TOC(<remembered entry>` to BUNDLE
3) set sys,path to sys.executable in your app (see adopting to be frozen in the manual)
