### ISSUE TITLE
Clarify documentation on __file__

### ISSUE THREAD

**Issue by yagebu** [pyinstaller/pyinstaller#2882]
The section "Run-time Information" of the documentation makes it sound like `__file__` does not work at all when running a frozen Python program:

> For example, you might have data files that are normally found based on a module’s `__file__` attribute. That will not work when the code is bundled.

That doesn't seem to be true though - PyInstaller synthesizes a `__file__` for frozen apps that should "just work" in most cases (see https://github.com/pyinstaller/pyinstaller/issues/1598#issuecomment-147753507). For the babel Python package for example it worked (in conjunction with the hook) quite well and an attempt to introduce PyInstaller support actually broke it (https://github.com/python-babel/babel/issues/529).

I think the main thing to point out here is that if one copies data files to the root of the bundled data directory (`datas=[('/path/to/mypackage/data/', 'data')]`) it won't work  - one has to use `datas=[('/path/to/mypackage/data/', 'mypackage/data')]`.

**Comment by htgoebel** [comment]
Please suggest a new woding by providing a pull-request.

**Comment by yagebu** [comment]
Will do.
