### ISSUE TITLE
Failed to execute script **

### ISSUE THREAD

**Issue by dollarzhaole** [pyinstaller/pyinstaller#2890]
packages' version list as follows:
pyinstaller: 3.4.dev0+3c87c135a
python: 3.6.2 (32bit)
platform: windows-10-10.0.14393-sp0 (32bit)
matplotlib: 2.0.2(installed by `pip install matplotlib`)

whether I use the 3.4.dev or 3.3 from pip install pyinstaller, the error remains the same.

and my script import matplotlib, the script plot.py is 

`import matplotlib.pyplot as plt
plt.plot([1,2,3,4])
plt.ylabel('some numbers')
plt.show()`

when I run the built exe plot.exe, the error shows up:
Failed to execute script plot

I search from the Internet and none works for me.

**Comment by nejch** [comment]
Can you post the full stack trace that shows up when you run the executable (leading up to `Failed to execute script plot`)?

**Comment by dollarzhaole** [comment]
when I double click the exe file, no stack trace info.
Now I don't have that envirement, so I can't test whether run the exe file on the command line shows the statck. After three days, I'll test that and responce

**Comment by am05mhz** [comment]
Hi I have the same issue, but probably with a different cause.

when I freeze / pack my app without UPX, the executable can be run with no error, but when frozen / packed with UPX 3.94, the executable throw `Failed to execute script scriptname`

I am using python 3.6.2 with pyinstaller 3.3 and upx 3.94
My OS is Win 7 32bit

my command to make the executable is:

    pyinstaller --noconsole --onefile scriptname.py

and

    pyinstaller --noconsole --onefile --upx-dir=path/to/upx scriptname.py

**Comment by htgoebel** [comment]
So obviously you need to include `fontList.json` into the frozen app. See https://pyinstaller.readthedocs.io/en/stable/usage.html#what-to-bundle-where-to-search
