### ISSUE TITLE
can we make LD_LIBRARY_PATH env var processing easier?

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#2892]
See there for some context:
- https://github.com/borgbackup/borg/issues/3077
- https://github.com/borgbackup/borg/pull/3078/files

Considering that it took me 3 tries to get this (hopefully) right for all the cases (and I wrote that part of the pyinstaller bootloader), I guess it is not easy enough yet to work with.

**Comment by ThomasWaldmann** [comment]
Maybe it would be better, if the pyinstaller bootloader would set up LDLP_ORIG in any case.

Problem(?):
- LDLP is not in original env, then LDLP_ORIG == '' (1)
- LDLP is in original env, but empty, then LDLP_ORIG == '' also (2)
- LDLP is in original env, but not empty, then LDLP_ORIG == '...'

Do we need to differentiate between (1) and (2)?

When using a shell and setting a env var to empty, it is removed from the env, but is there a use case to have an empty string in an env var?

Would the system behave differently when LDLP is the empty string vs. when LDLP is not present?

Can we even set a env var to an empty string and the subprocess will get it exactly like that or will the OS remove empty env vars from the environment?

**Comment by ThomasWaldmann** [comment]
Alternatively, there could be a magic value in LDLP_ORIG (like `$$NOT_PRESENT$$`) to represent the case when it was not present in the original env, but that would be incompatible with existing code using LDLP_ORIG (and expecting a valid LDLP in it, if present).

**Comment by htgoebel** [comment]
> Maybe it would be better, if the pyinstaller bootloader would set up LD_LIBRARY_PATH_ORIG in any case.

This sounds like a good solution. It may simplify some code in PyInstaller, too.

> When using a shell and setting a env var to empty, it is removed from the env,

Not exactly:
```
$ export foo=
$ env | grep foo
foo=
$ bash
$ env | grep foo
foo=
$ exit
exit
$ 
```

> Would the system behave differently when LD_LIBRARY_PATH is the empty string vs. when LD_LIBRARY_PATH is not present?

The [ld.so(8) manpage has](http://man7.org/linux/man-pages/man8/ld.so.8.html) only says "Similar to the PATH environment variable". But (quoting from [this stakoverflow answer](https://unix.stackexchange.com/a/354296):
> If LD_LIBRARY_PATH is empty, [it is ignored](https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-load.c;h=c1b6d4ba0f133409c749944fea989ea89822560d;hb=HEAD#l801). If it is set to empty values (with LD_LIBRARY_PATH=: for example), those empty values are [interpreted as the current directory](https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/dl-load.c;h=c1b6d4ba0f133409c749944fea989ea89822560d;hb=HEAD#l446).

So I'd say, it should be save always setting `LD_LIBRARY_PAT_ORIG=''`. @codewarrior0 What's your point of view?

**Comment by ThomasWaldmann** [comment]
@htgoebel thanks for the info. guess that means processing of LDLP_ORIG is ok as it is now, but what's needed is some additional information that this processing has happened.

Not sure about names yet, but something like:
```
# True means that LDLP_ORIG *could* be available (except for the (*) case).
# pyinstaller would always set this to True. This not being present is for (*) case w/o pyinstaller.
LD_LIBRARY_PATH_ORIG_AVAIL=True

# not present means: LDLP originally not present (*)
# some value means: LDLP originally had that value (can be empty string)
LD_LIBRARY_PATH_ORIG=...
```

Instead of ..._AVAIL there could be also some other means to detect "we are running under pyinstaller" (assuming that pyi always does this processing).

**Comment by ThomasWaldmann** [comment]
Alternatively, pyi could setup `MEI_PATH=/tmp/_MEIxxxxxx` (name to be discussed) so code running under pyi can remove parts of LDLP that point into / below that path.

**Comment by EfremBraun** [comment]
I think that this issue should be marked as a bug. Lots of people are having this issue and don't know how to fix it. See:
#3668 
https://stackoverflow.com/questions/53354232/pyinstaller-and-xdg-open/66592237#66592237
https://answers.launchpad.net/kathaikalam/+question/206392

And there are use cases which can't be fixed by the method given in #3668, such as when using Qt's QDesktopServices.openUrl() (https://doc.qt.io/archives/qtforpython-5.12/PySide2/QtGui/QDesktopServices.html), which calls the OS's default program to open a file and doesn't allow one to change the environment variables.

**Comment by bwoodsend** [comment]
Naive question: Why are we even touching `LD_LIBRARY_PATH`? I understand we'd possibly want to prepend the root of the app to it but I don't understand why we'd remove anything?

**Comment by ThomasWaldmann** [comment]
@bwoodsend if you want to invoke a system-installed binary (e.g. ssh) from your pyinstaller-bundled app, the system app needs to load system libs (not: libs from pyinstaller bundle). See https://github.com/borgbackup/borg/issues/5897 for example.

**Comment by ThomasWaldmann** [comment]
Do we agree that this could be improved like:

- always set LD_LIBRARY_PATH_ORIG (to avoid bugs like linked in previous comment)
- if LD_LIBRARY_PATH is not present in original env, set LD_LIBRARY_PATH_ORIG to the empty string
- fix example code in docs to set LD_LIBRARY_PATH to LD_LIBRARY_PATH_ORIG (if not empty) and to remove LD_LIBRARY_PATH (if LD_LIBRARY_PATH_ORIG is empty [which is invalid as LDLP])

**Comment by ThomasWaldmann** [comment]
OK, I'll close this and just use the code recommended by pyinstaller docs.
