### ISSUE TITLE
problem with pyinstaller and PyQt5 / python 2.7

### ISSUE THREAD

**Issue by seghier** [pyinstaller/pyinstaller#2909]
Hello
my code with python 2.7 and pyqt4 work fine and compiled without problem and because pyqt5 has more feature i download a version for python 2.7 and it work fine from python ide or when i run the code from cmd.
when i compile it with pyinstaller don't launch and no error message and when i compile with this code : 
```
PyInstaller -y -F --distpath="." test.py
```
the cmd window appear than an error message : test.exe has stop working
this is a very simple code but don't work:
```
import sys
from PyQt5 import QtWidgets
app = QtWidgets.QApplication(sys.argv)
button = QtWidgets.QPushButton("Hello")
button.setFixedSize(100, 50)
button.show()
app.exec_()
```
i use : python 2.7.6 / pyqt5 (available in github) and pyinstaller 3.2.1
with PyInstaller: 3.4.dev0-54ed99110 the same problem

**Comment by htgoebel** [comment]
Which version of PyQT and which version of Qt are you using?

`test.exe has stop working` is to less information to help you. You not even stated wich platform you are using. Commodore 64? Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by seghier** [comment]
thanks ; did you read the last line ? i use : python 2.7.6 / pyqt5 [()](https://github.com/pyqt/python-qt5) and pyinstaller 3.2.1
and i use windows 10 64bits

**Comment by seghier** [comment]
how i can tell pyinstaller where the module ?
this version of pyqt5 include sip in the pyqt5 folder and when pyinstaller rename the module to PyQt5.sip.pyd and when i rename it to sip.pyd the error message disappear but the app don't work

**Comment by bjones1** [comment]
PyInstaller supports only Python 3 with PyQt5. You're on your own with Python 2.
