### ISSUE TITLE
Python 3.5 and later programs packaged under Wine crash on Windows 7

### ISSUE THREAD

**Issue by lvu** [pyinstaller/pyinstaller#2914]
If Python version is 3.4 or when packaging under "real" Windows, everything works fine. To reproduce, do this (python distro should be downloaded; `test.py` is just `print('Hello, world!')`):
```bash
rm -rf ~/.wine7-32/
env WINEARCH=win32 WINEPREFIX=$HOME/.wine7-32/ wine python-3.5.4.exe  /quiet InstallAllUsers=1 PrependPath=1 Include_test=0 Include_doc=0
env WINEARCH=win32 WINEPREFIX=$HOME/.wine7-32/ wine python -m pip install --upgrade pip setuptools pypiwin32 https://github.com/pyinstaller/pyinstaller/archive/develop.zip
env WINEARCH=win32 WINEPREFIX=$HOME/.wine7-32/ wine pyinstaller --debug test.py
```
I got PyInstaller-3.4.dev0+133d18156, and my Wine is `wine-2.17 (Staging)`. The packaged program runs under Windows 10, but under Windows 7 it outputs to console (in debug mode) the following:
```
E:\Projects\ecoreg\dist\test>E:\Projects\ecoreg\dist\test\test.exe
[3452] PyInstaller Bootloader 3.x
[3452] LOADER: executable is E:\Projects\ecoreg\dist\test\test.exe
[3452] LOADER: homepath is E:\Projects\ecoreg\dist\test
[3452] LOADER: _MEIPASS2 is NULL
[3452] LOADER: archivename is E:\Projects\ecoreg\dist\test\test.exe
[3452] LOADER: No need to extract files to run; setting extractionpath to homepath
[3452] LOADER: SetDllDirectory(E:\Projects\ecoreg\dist\test)
[3452] LOADER: Already in the child - running user's code.
[3452] LOADER: Python library: E:\Projects\ecoreg\dist\test\python35.dll
```

and then crashes with "test.exe stopped working" dialog box and the following details:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	test.exe
  Application Version:	0.0.0.0
  Application Timestamp:	597f4a75
  Fault Module Name:	StackHash_fbc4
  Fault Module Version:	0.0.0.0
  Fault Module Timestamp:	00000000
  Exception Code:	c0000005
  Exception Offset:	00000000
  OS Version:	6.1.7601.2.1.0.256.48
  Locale ID:	1033
  Additional Information 1:	fbc4
  Additional Information 2:	fbc4990dd55bbb1363cad46071a0ce01
  Additional Information 3:	c22a
  Additional Information 4:	c22acb50ac07827d6a95f2f29d8cedf0

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by htgoebel** [comment]
The "Problem Signature" provides much too less information to be useful. You need to put some debugger on this problem. The wikipage [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) might have some hints for it.

**Comment by lvu** [comment]
@htgoebel I'm afraid I don't see any debugging tips in wiki besides the `sxstrace`-related one, which doesn't seem relevant here. Here is the `pyinstaller --log-level=DEBUG` output, together with wine's warnings: https://gist.github.com/lvu/ea0ac09a7272c62f5ba489548e9e1a21.

What else can I debug? Can you give me some hints of what I can do?

**Comment by htgoebel** [comment]
The only idea I have is: Run the application under debugger control (like gdb). But I can not tell you how-to on Windows.

**Comment by htgoebel** [comment]
No nore information since 5 month, Closing.
