### ISSUE TITLE
Pyinstaller and macOS 10

### ISSUE THREAD

**Issue by seghier** [pyinstaller/pyinstaller#2917]
Hi 
i compile a script in windows 10 64bits (python 3.5.4/PyQT5) and it work fine.
The same script in macOS 10.12 work fine when i launch it from pycharm .
After create the app with pyinstaller under macOS; the app don't work 
- with this command : 
pyinstaller -w -F -D --exclude-module=tkinter -i images/script.icns application.py
**always error : application quit unexpectedly**
- with this command : pyinstaller application.py
**Fatal Python error: PyThreadState_Get: no current thread
Abort trap: 6
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.**

[Process completed]**
-macOS 10.12
-Python 3.5.4
-PyQt5.9
-Pyinstaller 3.3

**Comment by GarlandM** [comment]
Also having this issue.

Code works fine directly, but once creating an executable, any data sent to the PyInstaller (libzmq) fails with Abort trap: 6
