### ISSUE TITLE
ModuleNotFoundError: No module named 'requests' (windows)

### ISSUE THREAD

**Issue by ckalas** [pyinstaller/pyinstaller#2920]
This issue seems to have been supposedly solved a year or two ago, but with requests 2.18 and pyinstaller 3.3/4 I still get this error when running my exe. This only happens on windows for me, on macOS everything runs fine.

**Comment by akej74** [comment]
I did a quick test packaging the following code with PyInstaller 3.3 (official):

```
import requests
r = requests.get('http://www.gp.se')
print(r.text)
```

This small example works without problems using requests 2.18.4 and Python 3.6.3.

**Comment by BoboTiG** [comment]
`requests` is no more an issue since years. Please reopen with a concrete example if the issue arise again.
