### ISSUE TITLE
bug-report - cannot bundle icon - difference between console=True and False - am convinced a bug exists

### ISSUE THREAD

**Issue by marfeljoergsen** [pyinstaller/pyinstaller#2922]
Dear all,

I'm filing in, what I think is a bug report. I'm using (YES, I did try the latest development version also):

   PyInstaller-3.4.dev0+133d18156
   Python 3.6.2 :: Continuum Analytics, Inc.
   Platform: Windows.

When I use Pyinstaller, I discovered that if I use the option "console=False" it does NOT work. But if I use "console=True" it DOES work. This I suspect is a bug. I have another program where neither works (larger program). For the larger program, neither
--onedir or --onefile mode works. I suspect there's a severe bug here.

If it isn't - or if there's a work-around - please let me know.

I include .spec-file + simple Python program using Tkinter below. You need to download and use an arbitrary icon-file (*.ico extension).

``` #The python-program:
from tkinter import *           # Importing the Tkinter (tool box) library
root = Tk()                     # Create a background window

if True: # for debugging:
    import os
    iconFile = "tk_inter_logo.ico"
    if getattr(sys, 'frozen', False): # we are running in a bundle (we are frozen)
        iconFilePath = os.path.join(sys.prefix, iconFile)
        bundle_dir = sys._MEIPASS
    else: # we are running in a normal Python environment
        iconFilePath = os.path.join(os.path.dirname(__file__), iconFile)
        bundle_dir = os.path.dirname(os.path.abspath(__file__))
    print('bundle dir is', bundle_dir)
    print(" ")
    print('sys.argv[0] is', sys.argv[0])
    print('sys.executable is', sys.executable)
    print('os.getcwd is', os.getcwd())
    print(" ")
    print("iconFilePath =", iconFilePath)
    if os.path.isfile(iconFilePath):
        print("file exist:", iconFilePath) # "console=True" it DOES work
    else:
        print("file does NOT exist:", iconFilePath) # "console=False" it does NOT work
    if True:
        input("Press Enter to continue and check output of temporary dir...")
    root.iconbitmap(iconFilePath)


li = 'Carl Patrick Lindsay Helmut Chris Gwen'.split()
listb = Listbox(root)           # Create a listbox widget
for item in li:                 # Insert each item within li into the listbox
    listb.insert(0,item)

listb.pack()                    # Pack listbox widget
root.mainloop()                 # Execute the main event handler
```

Below is the .spec-file:
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['tk_inter.py'],
             pathex=['C:\\Users\\MFJ\\Downloads\\PythonDevel\\tk_inter'],
             binaries=[],
             datas=[('tk_inter_logo.ico', '.')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='tk_inter',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False, icon='tk_inter_logo.ico')
```
In the last line, you can try to replace console=False with console=True - at my system this makes the WHOLE difference. I think this is not the intended behaviour of pyinstaller.
I also tried upx=False. As said, for my larger program, neither console option works - the icon doesn't get bundled in any case. I think pyinstaller seems pretty unreliable here, I'm convinced there's a bug here.

Please let me know your comments/suggestions/advice/ideas, thanks a lot!

Br,
M

**Comment by tallforasmurf** [comment]
Thanks for lots of detail but you omit a couple of key facts. One, WHAT "does not work"? PyInstaller? or the bundled program when you try to run it? Two, how does "it" fail, e.g. is there a stack trace to show?

**Comment by marfeljoergsen** [comment]
Oh, sorry - my mistake, you're right. I wasn't clear on that. The problem is that the included icon-file doesn't get bundled and therefore the program fails when executing (and I don't see severe error messages while running pyinstaller or alternatively, I don't understand them). Sample output from program execution:

```
sys.argv[0] is runlog_analysis.exe
sys.executable is C:\Users\User\Downloads\runlog_analysis\dist\runlog_analysis\runlog_analysis.exe
os.getcwd is C:\Users\User\Downloads\runlog_analysis\dist\runlog_analysis

iconFilePath = C:\Users\User\Downloads\runlog_analysis\dist\runlog_analysis\runlog_analysis_logo.ico
file does NOT exist: C:\Users\User\Downloads\runlog_analysis\dist\runlog_analysis\runlog_analysis_logo.ico
Traceback (most recent call last):
  File "runlog_analysis.py", line 316, in <module>
  File "runlog_analysis.py", line 68, in __init__
  File "tkinter\__init__.py", line 1865, in wm_iconbitmap
_tkinter.TclError: bitmap "C:\Users\User\Downloads\runlog_analysis\dist\runlog_analysis\runlog_analysis_logo.ico" not defined
[4516] Failed to execute script `runlog_analysis
```
So I'm using (and outputting) the lines/variables iconFilePath = C:\Users\User\Downloads\runlog_analysis\dist\runlog_analysis\runlog_analysis_logo.ico to first show where the icon-file should be. Next, the program shows if the file exists - and often it doesn't: file does NOT exist: C:\Users\User\Downloads\runlog_analysis\dist\runlog_analysis\runlog_analysis_logo.ico

But this file should exist... I don't understand why this icon file doesn't become bundled and/or why pyinstaller doesn't complain or outputs an error message ? And then there's a difference between using console=True and console=False, which just makes things even more strange...? I hope someone can confirm this behaviour, I think this is rather weird...

**Comment by htgoebel** [comment]
> iconFilePath = …\runlog_analysis_logo.ico

This is a different name as used in the script and spec-file you posted.

Since you are using one-dir-mode, you can verify the file is present by jsut looking at the dist/… folder.

> and often it doesn't: file does NOT exist

What exactyl doe you mean with "often"? How is this related to console-mode? Please try removing both the build and the dist directory when switching from/to console-mode – just to be sure we are searching at the right place.

**Comment by marfeljoergsen** [comment]
Yes, I feared this would cause a misunderstanding. The problem is that I was posting the output from two different computers with two different paths - because I wanted to quickly reply and get going. This problem appeared on both computers - with the same path. So you can ignore the output path, which I modified to compensate and to illustrate the problem, I hope you understand. Also in one-dir mode I agree, I should be able to see the icon-file inside the dist-folder, but it doesn't appear there. 

About "often it doesn't appear there": I've tried a lot of things, many different combinations. Generally the icon-file doesn't appear under the dist-folder, so obviously when it tries to find the file and cannot, the program aborts with an error. So "often it doesn't appear there" means: in around 90% of the different combinations of settings and code I tried, the icon file doesn't appear. You might find this formulation strange. That's also why I wrote that with exact the rather simple code I posted and when I use console=True, for some strange reason - then the icon file DO appear where it should, inside the dist-directory, hence in this case, the program will run as it is supposed to do with no errors...

I hope this cleared things up a bit... It's so strange that I'm considering switching to cx_freeze or one of the alternatives...

**Comment by htgoebel** [comment]
ACK to the different filenames.

Side-note: I just discovered that you are using --onefile-mode. Out [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) guide says to *first of all* use --onedir-mode.

Suggested systematic way of debugging:
1. Add `print(os.listdir(bundle_dir))` to your program. We will need it later.
2. Use --onedir-mode for the following tests.
3. Make sure, the icon file is put into the dist-folder with `console=True`, like this: `pyinstaller --onedir --add-data tk_inter_logo.ico:. tk_inter.py --console`. (This of course assumes that `tk_inter_logo.ico´ resides in the current directory.)
   a. look into the dist-folder using e.g. explorer or `dir`. If the file is not here, fix this problem *first*.
   b. Run you program. It should output a list of files, including the .exe and the icon-file.
4. Make sure, the icon file is put into the dist-folder with `console=False` like this: `pyinstaller --onedir --add-data tk_inter_logo.ico:. tk_inter.py --noconsole` - look into the dist-folder using e.g. explorer or `dir`.
   a. Again look into the dist-folder using e.g. explorer or `dir`. I'm very confident, that if the icon file was there in case (3) it also will be now.
   b. Run you program. Again it should output a list of files, including the .exe and the icon-file.

If this passes, you may want to try `onefile`-mode. In this case for steps (a) you need to use [pyi-archive_viewer](https://pythonhosted.org/PyInstaller/advanced-topics.html#using-pyi-archive-viewer) to inspect the .exe.

**Comment by marfeljoergsen** [comment]
htgoebel, sorry for slow reply. I've used pyinstaller for around 2-3 weeks now. The problem as I see it, is that I've generally used pyinstaller using the spec-file instead using command-line, i.e:

`pyinstaller --clean tk_inter.py tk_inter.spec`

This is a big mistake, as this has caused me a lot of trouble... Independent of what you wrote, I have good success with command line (I should have known that from the beginning, but I kept struggling for figuring out what I must've/had done wrong). What I believe is a bug is entirely related to using the spec-file - not the command line... When that is said, I tried your suggestions and also WHEN I use the command line suggestions you write, it works - thanks a lot (I also found out earlier, however). Now, I just had to confirm - after upgrading all packages, re-installing pip and upgrading to latest and newest windows 10, I still have a problem with pyinstaller, the python-program above and the spec-file above together with this command:

`pyinstaller --clean tk_inter.py tk_inter.spec`

I don't know if it's because I've upgraded all packages (I had a problem with pip and conda-installation) but in any case I don't get the icon bundled using this spec-file - neither using console=True or False and neither using onedir or onefile (and the onedir is the easiest to debug)... Is there an obvious problem with my spec-file? If so, why don't I see any error messages related to the missing icon-file? This is what I think is very strange... I appreciate your time spent, thanks a lot. And now we are where we should be - what is wrong?

**Comment by htgoebel** [comment]
> Is there an obvious problem with my spec-file? 

Have you tried `diff`- the spec-file generated by the commend line with your your spec-file?

> If so, why don't I see any error messages related to the missing icon-file?

I assume because PyInstaller find the icon-file and puts it into the dist-folder – so for PyInstaller there is no problem.

>  what is wrong?

`diff` is your friend ;-)

I'm closing this now, since the original issue is solved. Feel free to open a new ticket if necessary.

**Comment by marfeljoergsen** [comment]
Thanks for your help. It is not clear to me, what the problem is - I see nothing wrong with the spec-file and diff shows no difference. It's like sometimes it caches something wrong and then it doesn't work from the spec-file. I've had much better luck with passing the options from the command-line. As I can run from the command line and make things work, I appreciate your help and time and suspect something is wrong. If not with pyinstaller - then with my system or miniconda or something causing a conflict. I'll open a new ticket, if I experience something more concrete and reproducible, thanks.
