### ISSUE TITLE
Can't find a reliable quit method on OSX

### ISSUE THREAD

**Issue by axfelix** [pyinstaller/pyinstaller#2929]
Hi,

I don't remember having had this problem in the past, but with current pyinstaller 3.3 and Python 3.5.3, I can't get pyinstaller-built binaries on OSX to acknowledge any quit commands. None of `quit(), sys.exit(), or os._exit()` seem to work for me. I found some older issues about this but there don't seem to be any outstanding bugs that I'm aware of, so I think it might be on my end, but I'm not sure what to do about it...

My app only runs a single process (it spawns Cocoadialog windows but those shouldn't be the ones receiving the exit signal) and I'm building with --noconsole, I can't really tell what the problem is.

**Comment by axfelix** [comment]
Ping -- is this a known issue, or definitely something wrong on my end?

**Comment by tallforasmurf** [comment]
if you have a console, and write something like

    sys.exit()
    print( 'ha ha just kidding' )

what happens? Or keep the --noconsole option, but invoke it from the terminal with `dist/myscript.app/Contents/MacOS/myscript`?

**Comment by axfelix** [comment]
That exits cleanly -- it seems to be specifically an issue with using Pyinstaller together with Cocoadialog. Something about the combination means that some input from a Cocoadialog dialog that I want to be able to throw a "quit" means that a Pyinstallered script doesn't seem to receive the quit signal properly, or it's not elevated to the parent process. Cocoadialog in a non-compiled Python script works fine, and your example by itself works fine.

**Comment by axfelix** [comment]
Let me know if I should provide an example so a maintainer can duplicate...

**Comment by BoboTiG** [comment]
It is quite late, but yes an example would help a lot.

**Comment by axfelix** [comment]
Ah, sorry, I can close this -- I've switched from using cocoadialog to using zerorpc to put graphical layers on my python apps, and I don't have this issue anymore.
