### ISSUE TITLE
Autofollow hidden imports in Cython/Pyrex modules

### ISSUE THREAD

**Issue by rasky** [pyinstaller/pyinstaller#293]
**Original date**: 2010/11/19

All !Cython/Pyrex compiled modules have hidden imports; basically, each and every "import" statement in the source pyx file becomes a hidden import after compilation.

PyInstaller could try and discover these dependencies automatically by using some tricks, in the case the Cython module was compiled on the same computer (so this would mostly apply to user-written !Cython/Pyrex code). This is a description of a tentative algorithm that might work:

1) In bindepend.py, for every binary file, grep the string `__pyx_vtable__`. If it is found, it is probably a Pyrex-compiled module.

2) Grep the name of the binary module with the extension replaced with ".c". For instance, if the module is called "foobar.so" or "foobar.pyd", grep for "foobar.c". If you are lucky, you should end up with the full pathname of the ".c" file.

3) Try and open the .c file. If it's found, than we are lucky! Grep for all instances of `__Pyx_Import` and `__Pyx_ImportType`, and extract the first argument from the call. If it's a literal string, you're done; if it's a symbol, try to follow it to its definition.

**Comment by htgoebel** [comment]
#438 was closed with the https://github.com/pyinstaller/pyinstaller/issues/438#issuecomment-126305941
> Closing since this is not applicable.

The same is true here.
