### ISSUE TITLE
Pyinstaller 3.3 is not working on Windows XP. Pyinstaller 3.2.1 works.

### ISSUE THREAD

**Issue by jairo4** [pyinstaller/pyinstaller#2931]
Bundled application crashes with an error message: "<path>script.exe is not a valid Win32 application."

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by jairo4** [comment]
I tested PyInstaller 3.3 with a "Hello Word" app and it failed. I used a clean Python 3.4.4 install.
________________________________

**Comment by mgjk** [comment]
Win XP sp2 did very similar for me.  The application builds.  When run, "Access Denied" on the command line.   A dialog appears "test.exe is not a valid Win32 application.".   pyinstaller 3.2.1 works fine, I'm happy with the workaround for now.   

My example program was 

`print 'hello"`

I'll try to find an XP SP3 target (these are lab systems) and post a proper report.

**Comment by htgoebel** [comment]
Windows XP is out of maintenance since long. Please understand that we can not voluntary support these age-old operating system. If PyInstaller 3.2.1 works for you, just stay with that version.

**Comment by jairo4** [comment]
I can understand that. 
By the way, thank you for your voluntary work!

**Comment by mgjk** [comment]
Thanks for the update.  I’ll stick to 3.2.1 then.  It’s a great tool.
