### ISSUE TITLE
django and pyinstaller encoding issue

### ISSUE THREAD

**Issue by kwstaskara** [pyinstaller/pyinstaller#2932]
Hello so i tried pyinstaller with django and i tried to make my app one  file so what i did 
pyinstaller manage.py --onefile i also tried pyinstaller -D -F -n main -c "manage.py".
it packaged fine into sigle exe. But whenever i try to run "python3 main runserver" i get error
File "main", line 1
SyntaxError: Non-UTF-8 code starting with '\xe8' in file main on line 2, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by htgoebel** [comment]
`main` is an executable, not a Python script. You can not run it via python.

**Comment by kwstaskara** [comment]
Normal opening not working too when I open it normal nothing happens
