### ISSUE TITLE
.exe  couldn't open xxxx.png

### ISSUE THREAD

**Issue by YuexiWangwei** [pyinstaller/pyinstaller#2935]
Hi,
There is a problem which troubled me for 2 days. I had pyinstallered  my files .  There are some png pictures in the floder. But when I run the file of .exe(main.exe),there are some words of couldn't open the "background.png".So,what should I do? Please help me as soon as possible!

python3.6

![673317779969281959](https://user-images.githubusercontent.com/33046794/31923016-f56bed32-b8aa-11e7-8b5a-47101d8dda59.jpg)

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by YuexiWangwei** [comment]
I've settled the problem.What I've done is keep the main.exe file out of the folder of dist. You can try it.

**Comment by ChingChang9** [comment]
@YuexiWangwei Thanks for the solution, but unfortunately it still doesn't work for me.
