### ISSUE TITLE
warning from Windows  Program Compatibility Assistant

### ISSUE THREAD

**Issue by Shaunchenzhaojin** [pyinstaller/pyinstaller#2938]
I am a newcomer of pyinstaller.
I make a exe file via pyinstaller 3.4 . when I run my exe and exit the exe, I get a warning from Windows  Program Compatibility Assistant. 
If I have any mistake? 

Thanks a lot

**Comment by Shaunchenzhaojin** [comment]
![bd9f92a1-bb0a-4481-b858-3452210dc677](https://user-images.githubusercontent.com/20035768/31983296-44b515fa-b98f-11e7-8001-07d2f4c95186.png)

**Comment by htgoebel** [comment]
What is this "Windows Program Compatibility Assistant" thing? I can't spot anything related in the scrennshot. Please do not post pictures but text as pictures can't be quoted not searched.

**Comment by Shaunchenzhaojin** [comment]
OK，my mistake. How about this pictures:
![image002](https://user-images.githubusercontent.com/20035768/31984563-98c98f7c-b994-11e7-9141-4ddcba118aef.gif)

I have successfully make a exe by the pyinstaller.
Thanks again!

**Comment by Shaunchenzhaojin** [comment]
Thanks htgoebel for help. I have solved this error.
My exe name is contain a [install] word, windows UAC will raise a warning with the  Program Compatibility Assistant.
For detail: [](https://msdn.microsoft.com/zh-cn/bb756937)
[](https://msdn.microsoft.com/EN-US/library/bb756960(v=VS.10,d=hv.2).aspx)
Thanks again!

**Comment by Shaunchenzhaojin** [comment]
Thanks htgoebel for help. I have solved this error.
My exe name is contain a [install] word, windows UAC will raise a warning with the Program Compatibility Assistant.
For detail: https://msdn.microsoft.com/zh-cn/bb756937
https://msdn.microsoft.com/EN-US/library/bb756960(v=VS.10,d=hv.2).aspx
Thanks again!

**Comment by tenuki** [comment]
If you want to still keep the "install" word in your program name, or by other condition start to trigger the PCA again, there's a way to prevent definitely the PCA. 

It is to add specifically which OS versions is your software compatible with, by using/creating/updating your app's manifest:

https://msdn.microsoft.com/en-us/library/windows/desktop/dd371711(v=vs.85).aspx

**Comment by Shaunchenzhaojin** [comment]
I have add the support platform version in my manifest file, but there is not help for my problem. 
So I have to rename my exe file name instand.
Thanks tenuki. I will closed this issue.
