### ISSUE TITLE
Something wrong with the file 'mkl_intel_thread.dll',and I make a new hooks

### ISSUE THREAD

**Issue by LittleWhite-Carry** [pyinstaller/pyinstaller#2946]
I have Python3.5 and Anaconda3. I installed numpy+mkl.whl, but I also have 'mkl_*' files in *\Anaconda3\Library\bin\. 
So everytime I pack my file to .exe, those files of 'mkl_*' have something wrong. So I make a little change of your file 'hook-numpy.core.py'. 
I try to upload it, but I can't. Sorry. I mark the part of my change. I hope it can help a lot.

    import os
    import os.path
    import re
    from PyInstaller.utils.hooks import get_package_paths
    from PyInstaller import log as logging
    from PyInstaller import compat

    binaries = []

    pkg_base, pkg_dir = get_package_paths('numpy.core')
    re_anylib = re.compile(r'\w+\.(?:dll|so|dylib)', re.IGNORECASE)
    dlls_pkg = [f for f in os.listdir(pkg_dir) if re_anylib.match(f)]
    binaries += [(os.path.join(pkg_dir, f), '') for f in dlls_pkg]

    if compat.is_win:
        if os.path.exists(os.path.join(compat.base_prefix, 'Lib\\site-packages\\numpy\core')):   ###Here is the change
            lib_dir = os.path.join(compat.base_prefix, 'Lib\\site-packages\\numpy\core')         ###Here is the change
        else:
            lib_dir = os.path.join(compat.base_prefix, "Library", "bin")
    else:
        lib_dir = os.path.join(compat.base_prefix, "lib")
    if os.path.isdir(lib_dir):
        re_mkllib = re.compile(r'^(?:lib)?mkl\w+\.(?:dll|so|dylib)', re.IGNORECASE)
        dlls_mkl = [f for f in os.listdir(lib_dir) if re_mkllib.match(f)]
        if dlls_mkl:
            logger = logging.getLogger(__name__)
            logger.info("MKL libraries found when importing numpy. Adding MKL to binaries")
            binaries += [(os.path.join(lib_dir, f), '') for f in dlls_mkl]

**Comment by htgoebel** [comment]
Thanks for the updated hook. You promised to mark the change, but I can not spot it.
