### ISSUE TITLE
OpenCV fails to load video on Windows without any error

### ISSUE THREAD

**Issue by kratzert** [pyinstaller/pyinstaller#2950]
I have the following problem that occurs when I try to bundle a Python program that makes use of OpenCV for e.g. loading and processing a video frame by frame: Pyinstaller runs and packs the programm without any error and when I start the program (from within the same environment I used to pack the software) the program runs without a problem. When I leave the environment (which would be the same as passing my software to another computer I guess) the program fails to read the video, but loads OpenCV without import error. The same goes for starting the program by double-click. But in the console there is no error, not while packing the program with Pyinstaller and not while running.

I'm not sure if this is due to some linking to a video codec file, which is not correctly linked when the program is packed but I'm not sure how to approach the debugging of this problem. 

### Computer Specs:
- Windows 10
- Python 3.6 
- Latest Pyinstaller dev version
- OpenCV 3.3.0

This problem only occurs on Windows for me. On my main working station running Ubuntu 16.04 the program runs inside and outside of the environment and also by starting the program by double-click.

### Steps to reproduce the problem:

1) Setup new environment (e.g. for conda `conda create -n cv2_pyinstaller_test python=3.6`
2) Activate environment
3) Install OpenCV (with anaconda `conda install -c conda-forge opencv`)
4) Install last dev version of pyinstaller `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`

5) Save this code into a file e.g. cv2_test.py

```python
import cv2
import os

# read full path of avi files
print(os.getcwd())
avi_files = [os.path.join(os.getcwd(), f) for f in os.listdir(os.getcwd()) if f.endswith('avi')]

print("%i video/videos found" %len(avi_files))

# take first and try to read one frame
vid = cv2.VideoCapture(avi_files[0])
ret, frame = vid.read()

if ret:
    print("Sucessfully read one frame.")
else:
    print("Failed to read one frame.")
```

6) run `pyinstaller cv2_test.py --onedir --debug`

7) Place one avi file in the same folder (free samples can be found [here](http://www.engr.colostate.edu/me/facil/dynamics/avis.htm). Direct download link for one avi file (1.42MB) [Link](http://www.engr.colostate.edu/me/facil/dynamics/files/bird.avi)

8) Now run the .exe from the shell with the environment still active. E.g. `dist\cv2_test\cv2_test.exe` This should output something like:
```
1 video/videos found.
Sucessfully read one frame.
```

9) Deactivate environment and run the .exe file again like above. Now you will see:
```
1 video/videos found.
Failed to read one frame.
```

**Comment by kratzert** [comment]
I guess I have found the problem. Seems like pyinstaller isn't copying all of opencvs *.dll to the dist folder. While in {python-env}/Lib/site-packages 43 dlls corresponding to the OpenCV package can be found, in the bundled folder of pyinstaller only 27 are present. The complete list of missing dlls is (note that the installed version is OpenCV3.3.0):
- opencv_datasets330.dll
- opencv_dnn330.dll
- opencv_dpm330.dll
- opencv_ffmpeg330.dll
- opencv_fuzzy330.dll
- opencv_img_hash330.dll
- opencv_phase_unwrapping330.dll
- opencv_plot330.dll
- opencv_reg330.dll
- opencv_saliency330.dll
- opencv_stereo330.dll
- opencv_structured_light330.dll
- opencv_superres330.dll
- opencv_surface_matching330.dll
- opencv_videostab330.dll
- opencv_xobject330.dll

So it seems like the ffmpeg codec file isn't copied, which matches my first guess. Putting a copy of `opencv_ffmpeg330.dll` in the dist folder solved my problem.

How could we make pyinstaller aware of the rest of the .dll files and copy them as well, so the user doesn't need to copy them manually (or configure the .spec file). Would love to help, but don't know where I have to start.

**Comment by AlexS12** [comment]
Same issue for me, but in my case, opencv is not installed in any other conda environment. It seems that pyinstaller is just skipping opencv_ffmpeg*.dll (tried with 3.3, 3.4 and 3.1).
How does pyinstaller now which dlls to copy? I thought it was via cv2 hook, but I don't think so after having a look.

**Comment by gabycperezdias** [comment]
@AlexS12 Did you find any fix? Or at least a workaround?

**Comment by TechnoConserve** [comment]
FYI, I had a similar issue in which OpenCV would fail to load video in Windows 10 because of a missing dll, though I couldn't find any output from pyinstaller to indicate this was the issue.

I was able to solve it by adding the missing binary in my spec file. For me, the missing dll located at `C:\path\to\python\environment\Lib\site-packages\cv2`.

Other relevant info:
- Using opencv-contrib-python==3.4.4.19
- No other python or OpenCV installs on computer
- Single missing dll was named `opencv_ffmpeg344.dll`

**Comment by frascuelillo** [comment]
> @AlexS12 Did you find any fix? Or at least a workaround? I've copied the 2 dlls mentioned by @kratzert but this didn't fix... I also don't have a conda environment

I solved it adding the .dll in the pyinstaller command: **pyinstaller  -F --add-data opencv_ffmpeg341_64.dll;.  script.py**

**Comment by Santhosh1509** [comment]
> 
> 
> FYI, I had a similar issue in which OpenCV would fail to load video in Windows 10 because of a missing dll, though I couldn't find any output from pyinstaller to indicate this was the issue.
> 
> I was able to solve it by adding the missing binary in my spec file. For me, the missing dll located at `C:\path\to\python\environment\Lib\site-packages\cv2`.
> 
> Other relevant info:
> 
>     * Using opencv-contrib-python==3.4.4.19
> 
>     * No other python or OpenCV installs on computer
> 
>     * Single missing dll was named `opencv_ffmpeg344.dll`

Could you please elaborate as to how you solved it?

**Comment by rokm** [comment]
The issue with pyinstaller not picking up the `opencv_videio_ffmpeg*.dll` on Windows has been fixed by pyinstaller/pyinstaller-hooks-contrib#13.

**Comment by veesohoni** [comment]
I was using:

Worked for me after I removed -i 0
