### ISSUE TITLE
.spec file documentation: what are the debug and console options for?

### ISSUE THREAD

**Issue by purplekrayons** [pyinstaller/pyinstaller#2954]
Can someone please shed some light on the available options within a .spec file.

In particular, what do the `debug=false` and `console=false` options do (as found in the below code chunk)? I dug through your documentation (found here: https://pyinstaller.readthedocs.io/) but there is no mention of what `strip`, `upx`, `runtime_tmpdir`, `debug` or `console` do.

```
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='Engine',
          icon='engine.ico',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=False)
```

**Comment by tallforasmurf** [comment]
I believe they all correspond directly to command line options documented [here](https://pyinstaller.readthedocs.io/en/stable/usage.html#general-options).

**Comment by purplekrayons** [comment]
Thank you, I appreciate you linking that. I would have hoped that such a link, or note, would have been made in the .spec file section of documentation.

**Comment by htgoebel** [comment]
@purplekrayons Feel free to submit a pull-request adding the API documentation :-)
