### ISSUE TITLE
Not a Valid WIN32 Application on Windows XP

### ISSUE THREAD

**Issue by arcan25** [pyinstaller/pyinstaller#2972]
**Pyinstaller Version**: 3.3 as well latest development branch 3.4.dev0_133d18156
**Error Occurs**:  While executing application
**Python version**: 2.7.13 and 2.7.14 --32bit
**Host OS**: Win7 64bit and Win XP 32bit
**Target OS**: Win XP 32bit

**Sample code**: 'raw_input('Hello')

I have been trying to pack my application(onedir or onefile) from host os, and trying to run into WIN XP, buy it get detected as invalid win32 application. whereas pyinstaller version 3.2.1 works perfectly fine.

for temporary moved to working pyinstaller version, but thought that, should have report as an issue.

**Comment by tenuki** [comment]
looks like dup of #2876

**Comment by tenuki** [comment]
@arcan25  if you want, you can try the PR linked in #2876  ;-) !

**Comment by arcan25** [comment]
@tenuki yes, i did try and its working fine now, so as a result i closed the issue but forgot mention reason for doing so. Thanks for your efforts.
