### ISSUE TITLE
Pandas missing `pandas._libs.tslibs.timedeltas.so`

### ISSUE THREAD

**Issue by jamesstidard** [pyinstaller/pyinstaller#2978]
I'm using `pandas==0.21.0` as `pyinstaller==3.3` and `pyinstaller==3.4.dev`'

When building with `pyinstaller` the `/path/to/venv/lib/python3.4/site-packages/pandas/_libs/tslibs/timedeltas.cpython-34m.so` is not copied over to the `dist` directory, like its over counterparts. Instead, I'm manually renaming and putting this into dist myself as `dist/myapp/pandas._libs.tslibs.timedeltas.so`.

Unsure which package is "at fault" for this or how I should go about resolving this. For example if this should be handled in a update of the project or I use something like the `--add-binary` flag to handle this case (assuming that's an appropriate usage of the command option).

UPDATE: `--add-binary` doesn't appear to help as the right-hand side of the `binary_path:to_path` doesn't appear to let you specifically the renamed binary and just uses the exact name from the package - in this case is incorrect. So I'm probably doing that wrong.

Thanks

**Comment by mdigi** [comment]
I'm also having the same problem when upgrading from pandas 0.20.3 to 0.21.0.

**Comment by myeol2** [comment]
Having same problem with @jamesstidard , and can solve this problem thanks to his advice.

But still i have same problem with `--onefile` !

**Comment by lneuhaus** [comment]
+1 having the same problem as @jamesstidard

**Comment by lneuhaus** [comment]
I added a pull-request that fixes this issue: https://github.com/pyinstaller/pyinstaller/pull/2998

Tested with pandas 0.21 and python 3.5 on a linux machine (travis).

**Comment by jamesstidard** [comment]
Very much appreciated @Ineuhaus, thanks. I'm using hidden imports for some other library I'm using but didn't think to try it with a *.so. I guess these are c compiled libraries with one of the python bindings - still not to familier with that. Thanks again

**Comment by lneuhaus** [comment]
@jamesstidard it was your comment that pointed me to this issue so all the thanks goes back to you i guess :)

**Comment by su79eu7k** [comment]
@lneuhaus your solution worked in Windows also. (Windows / Python3.5 / Pandas 0.21.0 / Conda env) 
More detail about my problem #2999

**Comment by eskemojoe007** [comment]
Still having this issue.  Running `pyi-makespec -c -F --hidden-import *.so process_reports.py` with no luck.  Still getting:

`ImportError: C extension: No module named 'pandas._libs.tslibs.timedeltas' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.`

Python - 3.6.4
pyinstaller - 3.3.1
pandas - 0.22.0

**Comment by joshjacobson** [comment]
@lneuhaus This is not working on MacOS (10.13.2) for me. Per the pull request, I created that hook file and included it in the `PyInstaller/Hooks/ `directory.

**Comment by htgoebel** [comment]
Pull-request merged.

**Comment by arnabsinha99** [comment]
My issue got solved after visiting :- 

[](https://pandas.pydata.org/pandas-docs/stable/contributing.html#creating-a-development-environment)

**Comment by soerendip** [comment]
How was this solved???
