### ISSUE TITLE
Load data from external module - how to

### ISSUE THREAD

**Issue by Draqun** [pyinstaller/pyinstaller#2979]
Hi.
I want close my app as a binary file excluding configuration. Configuration is a python file with set of variables. I know I have to exclude this file from build process but how to avoid ImportError? 

Best regards.
Draqun

**Comment by tallforasmurf** [comment]
Not the suggestion you want: change configuration method. There are good reasons not to use `import` to load configuration data (security for one, a bad guy could put any kind of evil code whatever into the configure.py file and your import would execute it for him).
Use a data file, maybe in JSON format, and read it as a data file.

**Comment by Draqun** [comment]
I forgot about this vulnerability because this is internal tool and we close it only for our convenience but you have right. Thanks for help.

Best regards!
Draqun
