### ISSUE TITLE
Excluding runtime hooks

### ISSUE THREAD

**Issue by Leryan** [pyinstaller/pyinstaller#2983]
Hello,

I have the runtime hook `pyi_rth__tkinter.py` that fail because of missing binaries.

I don't want nor need to embed them in the binary, so for now i just deleted this hook from the venv containing PyInstaller.

How about a `--runtime-exclude-hook` option?

Thanks

Also many thanks for that project, it's is really saving us a huge amount of time.

**Comment by htgoebel** [comment]
The run-time hook should be included only if it is needed. So either the "is needed" detection is wrong and should be fixed, or the "missing binaries" should be fixed.

Please search the other issue about whether there is a related one and report back here. If there is non, pleas provide more info (esp. a minimal example).

**Comment by Leryan** [comment]
Unfortunately i cannot reproduce on a minimal example because this happen on a project with many dependencies.

May i ask you if it's ok to give you the procedure to reproduce with that project? It is opensource and only requires Python 2.7 and a virtualenv.

**Comment by htgoebel** [comment]
If you are not taking your time tracking this down, why should I spend my time? If a company is backing this project, you may want to contact me for commercial support.

I'm closing this now and will reopen when you provide more information.

**Comment by Leryan** [comment]
I think my question is still relevant. Would PyInstaller accept such option as `--exclude-rthook` or not? I don't know yet why PyInstaller wants to embed tk/tcl in the binary for now but I think that having a way to exclude hooks would be nice, at least to temporarily workaround errors.

Also sorry for the lack of information, first here is the output when running the binary:

```
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 28, in <module>
IOError: Tcl data directory "/tmp/_MEIcuKOXK/tcl" not found.
[11945] Failed to execute script pyi_rth__tkinter
```

The code of `pyi_rth__tkinter.py` is straightforward, and the hook `_tkinter` get this result: https://gist.github.com/Leryan/84a8ca30f0e79d66047ac57a215d8e68

Tell me if you need anything else.

**Comment by htgoebel** [comment]
If a run-time hook is included but the modules this hook is for are not. this is a bug which should be fixed. An option `--exclude-rthook` would just whitewash the cause of this bug.

**Comment by Leryan** [comment]
I couldn't agree more, so in that case how can i help you?

The `_tkinter` hook seems to do it's job but for some reason the data cannot be found at runtime.

Also i got the same problem with the `jsonschema` package, but i noticed something: when the data is added from a hook, it is embeded in the binary/directory (i prefer to use the "directory" mode, but the result is the same with a single binary file) but cannot be used.

When i manually add the data in the `Analysis()` call from the `.spec` file it's ok, at least for `jsonschema`, didn't try with `tk`.

I also have the same kind of problem with `hiddenimports` inside a hook, PyInstaller cannot find `kombu.transport.pyamqp` if added from a hook but succeeds when added to the `Analysis()` call.

And another strange thing is that if I setup a minimal example (for kombu) i do not have this problem.

**Comment by Leryan** [comment]
Well… i found why the `kombu.transport.pyamqp` fails when imported from a hook, in the application we had a `kombu` subpackage and the graph seems to have trouble with such things.

So, I think i can reproduce this in a minimal setup.

But for tkinter even when using `excludedimports` from the hook it doesn't change anything.

Also for now no luck with `jsonschema`.

I close this issue as you answered the initial question, and will open new issues if necessary.

Thanks

**Comment by Leryan** [comment]
@htgoebel in my spec file i was running `pyz = PYZ(a.pure)` instead of `pyz = PYZ(a.pure, a.zipped_data)`… i saw this as i've regenerated a `spec` from pyinstaller.

This has also solved the problem with tkinter.

Sorry for the noise.
