### ISSUE TITLE
False-Positive

### ISSUE THREAD

**Issue by HellnoRO** [pyinstaller/pyinstaller#2988]
One File, EXE File, Python 3.5, used libraries: tkinter, socket, os, sys, random, queue, threading, time, webbrowser.

False Positives:
```
Antiy-AVL - Trojan/Win32.Shelma
Avast - Win32:Evo-gen [Susp]
AVG - Win32:Evo-gen [Susp]
Jiangmin - Trojan.Shelma.bbh
Panda - Trj/Genetic.gen
Sophos ML - heuristic
VBA32 - Trojan.Shelma
Yandex - Trojan.Shelma!
Zillya - Trojan.Shelma.Win32.911
```

**Comment by grajsor** [comment]
So, I presume this means you have mailed the AV-vendors, provided them with
samples and opened a ticket about it? Good on you, if so. If not, do it
already.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by HellnoRO** [comment]
but its not one, its like 9 antiviruses, and 5 of them detect the same thing. there has to be something you can do

**Comment by htgoebel** [comment]
We can't do anything. Please contact your anti-virus vendor.

**Comment by HellnoRO** [comment]
I think you should contact the anti-virus vendor. After all it's your product causing the false-positives, and if I report the false positive on this build and get it whitelisted it will detect it when I update it and so on, which would be a problem to make a false positive removal request every single time I update.

**Comment by htgoebel** [comment]
> which would be a problem to make a false positive removal request every single time I update.

So you think, **I **should spend my spare time?! This is a voluntary project, and I'll not do this. Sorry for being harsh, but if you want this problem to be solved, you have tho contribute your mite.

**Comment by HellnoRO** [comment]
I wish I could send a few emails that take 10 minutes containing the files that trigger the false-positive if you can't but I don't know which are the ones causing it.

**Comment by Ninjamasque** [comment]
> So you think, **I **should spend my spare time?! This is a voluntary project, and I'll not do this. Sorry for being harsh, but if you want this problem to be solved, you have tho contribute your mite.

chill out bro if it was really a voluntary project you would have contributed your mite too

**Comment by htgoebel** [comment]
@Ninjamasque I assume you had had a look on this page http://www.pyinstaller.org/development.html?#maintainers
