### ISSUE TITLE
Windows 10 - Shortcut icon different of the exe one

### ISSUE THREAD

**Issue by Goczilla** [pyinstaller/pyinstaller#2995]
Hello,

I use your wonderful tool to make an executable of my python code. It is a GUI with `PyQt5` and `Python 3.6`. When I compile to an executable, on Windows 7 all is working fine.

But, on Windows 10, after copying/pasting my folder with the exe and all the libraries, when I add a shortcut on the desktop, this shortcut has the default icon of pyinstaller. If I right-click on the shortcut, change the icon to the default one, and set back my own icon, it is working. But if the user want to do another shortcut, he will have the problem again.

Also, I can add the parameter `--onefile` because in this case the executable file will do 170Mo and the GUI is long to launch.

I use the last version of pyinstaller (3.4.dev0+133d18156) and to do my exe I use the spec file :

```# -*- mode: python -*-
block_cipher = None
a = Analysis(['Lancement_IHM.py'],
             pathex=['C:\\MG\\Excelcar'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='Excelcar 2017-v1',
          debug=False,
          strip=False,
          upx=True,
          console=False,
          icon='Logo-E.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='Excelcar 2017-v1')
```

Thank in advance for your help.

**Comment by htgoebel** [comment]
I assume this could be solved by #870 (Do not have a default-icon in the bootloader, add it when freezing). Maybe you want to implement it, which for a windows developer should be easy.
