### ISSUE TITLE
No module named 'pandas._libs.tslibs.timedeltas'

### ISSUE THREAD

**Issue by su79eu7k** [pyinstaller/pyinstaller#2999]
Thank you for the great library and all of your effort.

I've encountered unfamiliar error with pandas and I'm using below two libraries only. pyinstaller worked well with pandas before as I remember. Any idea or suggestion will be my appreciation. Thank you.

**[Environment]**

windows 7
python=3.5 (conda env)

**[Library]**

pandas                    0.21.0           py35h0510043_1
PyInstaller               3.3                       <pip>

**[ERROR while EXE file execution]**

...
  File "pandas/_libs/tslib.pyx", line 1, in init pandas._libs.tslib
ImportError: No module named 'pandas._libs.tslibs.timedeltas'

During handling of the above exception, another exception occurred:

...
ImportError: C extension: No module named 'pandas._libs.tslibs.timedeltas' not b
uilt. If you want to import pandas from the source directory, you may need to ru
n 'python setup.py build_ext --inplace --force' to build the C extensions first.

**[My attempt]**
pyinstaller --onefile --hidden-import pandas._libs.tslibs myapp.py
pyinstaller --onefile --hidden-import pandas._libs.tslibs.timedeltas myapp.py
pandas: C extension pandas.lib not included #1580

**Comment by su79eu7k** [comment]
Sorry didn't know there is similar topic for this.

Pandas missing `pandas._libs.tslibs.timedeltas.so` #2978

**Comment by iliketrainz98** [comment]
Hi Guys,
Forgive me if I am wrong, but I think there may be additional items needed to be added to the 'hook-pandas.py'. Such as shown at [This Link](https://stackoverflow.com/questions/50560436/pyinstaller-and-pandasmultiple-hooks-missing).
For my code to work, I had to edit my 'hook-pandas.py' to the following:
`hiddenimports = ['pandas._libs.tslibs.timedelta', 'pandas._libs.tslibs.np_datetime', 'pandas._libs.tslibs.nattype',  'pandas._libs.skiplist']`
Do these needed to be added in another pull request?
Thanks so much
(P.S. Although I have used GitHub for ages, this is my first time commenting so if I have made any mistakes on what I have done I apologise. Let me know and I won't do it again aha).

**Comment by eskemojoe007** [comment]
Like @iliketrainz98, I needed to add all of those packages to my hidden imports after upgrading my python and pandas packages.  I did it locally in my `spec` file instead of the core `hooks-pandas.py`

Pandas 0.23.1
Python 3.6.5-32
pyinstaller 3.3.1

**Comment by k90mirzaei** [comment]
just run: conda install pandas

**Comment by RohitKankhedia** [comment]
I am still facing issue with same error mentioned in above case. Please help

**Comment by htgoebel** [comment]
@iliketrainz98 If the updared hook does not work four you, pleae provide a pull-request. Otehrwise this will get lost. Thanks.

**Comment by sirasao2** [comment]
My code was fine Friday. Monday I have this issues

Traceback (most recent call last):
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas._libs import (hashtable as _hashtable,
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\pandas\_libs\__init__.py", line 4, in <module>
    from .tslib import iNaT, NaT, Timestamp, Timedelta, OutOfBoundsDatetime
  File "pandas\_libs\tslibs\conversion.pxd", line 11, in init pandas._libs.tslib
ModuleNotFoundError: No module named 'pandas._libs.tslibs.conversion'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "randomForest.py", line 5, in <module>
    import pandas as pd
  File "C:\Users\USER\AppData\Roaming\Python\Python37\site-packages\pandas\__init__.py", line 35, in <module>
    "the C extensions first.".format(module))
ImportError: C extension: No module named 'pandas._libs.tslibs.conversion' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

**Comment by su79eu7k** [comment]
Did you guys checked you're already using virtual environment like `conda` to avoid library interference? 

And did you also checked build error message and added it to the `hiddenimports = [...]` in `hook-pandas.py`? I mean @sirasao2 in your case, `pandas._libs.tslibs.conversion` should be manually added to it. 

This is quite old but please check this(https://github.com/pyinstaller/pyinstaller/pull/2998/commits/017b247064f9bd51a620cfb2172c05d63fc75133) commit which clearly solved my problem long ago.
