### ISSUE TITLE
Unable to Integrate Cython and Pyinstaller

### ISSUE THREAD

**Issue by tysondogerz** [pyinstaller/pyinstaller#3004]
I am attempting to convert Python to Cython to run my pyinstaller executable to speed up the job and for obfuscation purposes. I have noticed however, that when I do this, it can be easily decompiled, the C files do not seem to be loaded correctly. 

On windows I am yet to get it working at all.

Here’s the steps I have undertaken. I am doing so on windows.

HA.Py to Pyx with:

```
driver = webdriver.Chrome(chrome_options = options)
driver.get('https://google.com')
driver.close()
I then Convert to pyx (rename Py -> Pyx)
Set up.py
from distutils.core import setup
from Cython.Build import cythonize
setup(
    ext_modules = cythonize("HA.pyx")
)
```
```
python setup.py build_ext –inplace  (pyd, I got a so file in Unix)
C:\Python31\python.exe C:\Python31\Scripts\cython.py smalltest1.py --embed
CMD:
python setup.py develop
```

`pyinstaller -r file_a.so,dll,file_a.so -r file_b.so,dll,file_b.so -F /C:/ANDAR`

In the folder it contains the pyx, as well as the setup file.

**Comment by htgoebel** [comment]
Did you follw the instruction in the manual? https://pyinstaller.readthedocs.io/en/stable/search.html?q=cython&check_keywords=yes&area=default

What exactly is the problem?

**Comment by tysondogerz** [comment]
I have re-gone through process on windows.

I get: Pyinstaller + Cython PermissionError: [Errno 13] Permission denied:

My original file:

from selenium.webdriver import Firefox
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.support import expected_conditions as expected
from selenium.webdriver.support.wait import WebDriverWait

if __name__ == "__main__":
    options = Options()
    options.add_argument('-headless')
    driver = Firefox(executable_path='geckodriver', firefox_options=options)
    wait = WebDriverWait(driver, timeout=10)
    driver.get('http://www.google.com')
    wait.until(expected.visibility_of_element_located((By.NAME, 'q'))).send_keys('headless firefox' + Keys.ENTER)
    wait.until(expected.visibility_of_element_located((By.CSS_SELECTOR, '#ires a'))).click()
    print(driver.page_source)
    driver.quit()


1 h1test.py -> h1test.pyx (Pyx file)
2 cython -a h1test.pyx which creates cython -a yourmod.pyx the C, pyd file.


3 Create setup.py file

Creating Cython setup...
setup(
    name="test",
    scripts=glob("*"),
    ext_modules=cythonize("h1test.pyx")
)


Output:

usage: Setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: Setup.py --help [cmd1 cmd2 ...]
   or: Setup.py --help-commands
   or: Setup.py cmd --help

error: no commands supplied

Process finished with exit code 1


python setup.py develop


Which creates test.egg-info folder 



Lastly I do the command and I copy paste all to nest egg folder:

I copy everything into C:\Users\Stan\test.egg-info
I then run:
pyinstaller -r h1test.cp36-win_amd64.pyd,dll,h1test.cp36-win_amd64.pyd -r h1test.cp36-win_amd64.pyd,dll,h1test.cp36-win_amd64.pyd -F C:\Users\Stan\test.egg-info

C:\Users\Stan\test.egg-info
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Stan'


C:\WINDOWS\system32>pyinstaller -r h1test.cp36-win_amd64.pyd,dll,h1test.cp36-win_amd64.pyd -r h1test.cp36-win_amd64.pyd,dll,h1test.cp36-win_amd64.pyd -F C:\Users\Stan\test.egg-info
357 INFO: PyInstaller: 3.3
358 INFO: Python: 3.6.3
360 INFO: Platform: Windows-10-10.0.16299-SP0
362 INFO: wrote C:\WINDOWS\system32\test.spec
364 INFO: UPX is not available.
365 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Stan', 'C:\\WINDOWS\\system32']
366 INFO: checking Analysis
366 INFO: Building Analysis because out00-Analysis.toc is non existent
366 INFO: Initializing module dependency graph...
374 INFO: Initializing module graph hooks...
375 INFO: Analyzing base_library.zip ...
3521 INFO: running Analysis out00-Analysis.toc
3523 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\Stan\anaconda3\python.exe
4066 INFO: Caching module hooks...
4070 INFO: Analyzing C:\Users\Stan\test.egg-info
Traceback (most recent call last):
  File "c:\users\Stan\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\Stan\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Stan\Anaconda3\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 92, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 213, in __init__
    self.__postinit__()
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in __postinit__
    self.assemble()
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 415, in assemble
    priority_scripts.append(self.graph.run_script(script))
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 201, in run_script
    self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
  File "c:\users\Stan\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1326, in run_script
    with open(pathname, 'rb') as fp:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\Stan\\test.egg-info'

**Comment by htgoebel** [comment]
> pyinstaller […] C:\Users\Stan\test.egg-info

You must not run PyInstaller in a`.egg-info`-file.
