### ISSUE TITLE
missing VCRUNTIME140.dll

### ISSUE THREAD

**Issue by masoudr** [pyinstaller/pyinstaller#3005]
Hi,
I want to create a 32bit executable app from my script to run on both X86 and X64 Windows machines. I generated the X64 version of my script and it was fine. My host machine is X64 but I installed Python 32bit version with 32bit libraries. Then I generated the executable with Pyinstaller but when I run the exe it throws the following error in a window:

> C:\Users\Name\Appdata\local\Temp_MEI51162\VCRUNTIME140.dll is either not designed to run on Windows or it contains an error...

and in the console I see this error:

> Error loading Python DLL 'C:\Users\Name\AppData\Local\Temp_MEI51162\python36.dll'. LoadLibrary:

I checked the `_MEI51162`, both `VCRUNTIME140.dll` and `python36.dll` is there but the `python36.dll` has a size about 1 MB instead of 3 MB. It doesn't matter if I check the `onefile` or not both of them give me the same error.
Thanks.

**Comment by htgoebel** [comment]
Not much I can help here, jst:
0) Which version of Windows?
1) Read the manual: https://pyinstaller.readthedocs.io/en/stable/usage.html#windows
2) Verify PyInstaller picked the correct (32-bit) version of all libraries, see the .toc files in the the build directory.
3) According to the error-message this is an issue with VCRUNTIME140.dll, not with the python36.dll

**Comment by masoudr** [comment]
@htgoebel I'm using windows 10, but my aim is to create app for 7/8/10.
I tried to build without `--onefile` and then replace the `vcruntime140.dll` from `C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\redist\x86\Microsoft.VC140.CRT` to build dir and the problem solved but I must create a single executable.

**Comment by htgoebel** [comment]
> I think it is including the wrong dll.

So you need to verify this :-) I'm no visionary.

For including the dll see "adding binaires" in the manual

**Comment by masoudr** [comment]
@htgoebel Thanks, I tried to add the `vcruntime140.dll` manually with both `--add-binaries` and `--add-data` but It seems that it cant overwrite the system's `vcruntime140.dll` with the new one I added (I always see the old one which is X64 version). I use this command:
`pyinstaller --add-binary vcruntime140.dll;. hello.py`
Is there a way to force Pyinstaller to use my specific dll instead of system path dll?

**Comment by masoudr** [comment]
After a lot of struggling, I couldn't find a way to replace the `vcruntime140.dll`, but I found a workaround by adding this file manually to `C:\Users\<User>\AppData\Roaming\pyinstaller` directory and rebuild with Pyinstaller then It will be replaced with the new one just copied. This will fix the issue temporary.

**Comment by jftuga** [comment]
I had a similar problem so I removed the entire `C:\Users\<User>\AppData\Roaming\pyinstaller` folder.  The next time I ran `pyinstaller -F --noupx pgm.py`, it built & ran without any errors.

**Comment by masoudr** [comment]
@jftuga Glad to hear that. I think the problem is when you install Pyinstaller twice as X64 and X86 so the first version should take control of the dlls and actually they cant do anything about it because there is only one same directory for both architectures. But I think the `add-binary` option must have the ability to replace existing dlls with new ones which currently not working.

**Comment by xp4xbox** [comment]
This issue still happens for me.

**Comment by masoudr** [comment]
@xp4xbox Yes it is. You should just use the workaround.

**Comment by xp4xbox** [comment]
problem is, the file size increases by 3mb.

**Comment by masoudr** [comment]
No, the first step is to create your executable normally then replace the missing or faulty dlls to get your app running. Finally, copy that dlls to roaming directory.

**Comment by meanpossum** [comment]
UPX compression strips the SHA Digital Signature form vcruntime140.dll so it is no longer seen as valid (AV software?).
Use --noupx to stop modifying (compressing) the files.

**Comment by truekonrads** [comment]
Considering @meanpossum's conclusion, this issue should not be consider closed as pyinstaller/upx doesn't work in a default situation for Windows.

**Comment by masoudr** [comment]
@truekonrads As @meanpossum said the UPX would mess DLLs sometimes but not for `vcruntime140.dll`. This issue suffers from generating X86 executable on an X64 host. Disabling UPX didn't help me as PyInstaller try to grab X64 version of DLLs and thus results as a failure.
