### ISSUE TITLE
Cython integration with pyinstaller

### ISSUE THREAD

**Issue by tysondogerz** [pyinstaller/pyinstaller#3012]
I've seen a bit of talk around Cython lately...

Does Pyinstaller Support it?  I get error below... when running: `pyinstaller -r my_module.c,dll,my_module.cp36-win_amd64.pyd -F my_module.cp36-win_amd64.pyd`

```
from setuptools import find_packages, Extension
from subzero import setup

setup(
name='hello_world',
ext_modules=[
Extension(
'my_module',
sources=['my_module.pyx'],
)
])
```

Renamed Standard python -> Pyx. You can do this in any ide. E.g Pycharm

python set.py build_ext --inplace
(as above)

`pyinstaller -r my_module.c,dll,my_module.cp36-win_amd64.pyd -F my_module.cp36-win_amd64.pyd`

And...

```
`C:\Users\dan>pyinstaller -r my_module.c,dll,my_module.cp36-win_amd64.pyd -F my_module.cp36-win_amd64.pyd`
410 INFO: PyInstaller: 3.3
410 INFO: Python: 3.6.3
411 INFO: Platform: Windows-10-10.0.16299-SP0
414 INFO: wrote C:\Users\dan\my_module.cp36-win_amd64.spec
416 INFO: UPX is not available.
417 INFO: Extending PYTHONPATH with paths
['C:\Users\dan', 'C:\Users\dan']
418 INFO: checking Analysis
418 INFO: Building Analysis because out00-Analysis.toc is non existent
418 INFO: Initializing module dependency graph...
422 INFO: Initializing module graph hooks...
424 INFO: Analyzing base_library.zip ...
3777 INFO: running Analysis out00-Analysis.toc
3780 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
required by c:\users\dan\anaconda3\python.exe
4331 INFO: Caching module hooks...
4335 INFO: Analyzing C:\Users\dan\my_module.cp36-win_amd64.pyd
Traceback (most recent call last):
File "c:\users\dan\anaconda3\lib\runpy.py", line 193, in run_module_as_main
"main", mod_spec)
File "c:\users\dan\anaconda3\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "C:\Users\dan\Anaconda3\Scripts\pyinstaller.exe_main.py", line 9, in 
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller_main.py", line 92, in run
run_build(pyi_config, spec_file, **vars(args))
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller_main_.py", line 46, in run_build
PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 791, in main
build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 737, in build
exec(text, spec_namespace)
File "", line 16, in 
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 213, in init
self.postinit()
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 161, in postinit
self.assemble()
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 415, in assemble
priority_scripts.append(self.graph.run_script(script))
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller\depend\analysis.py", line 201, in run_script
self._top_script_node = super(PyiModuleGraph, self).run_script(pathname)
File "c:\users\dan\anaconda3\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1330, in run_script
contents = fp.read() + '\n'
File "c:\users\dan\anaconda3\lib\codecs.py", line 321, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte

C:\Users\dan>
```

**Comment by htgoebel** [comment]
> … my_module.cp36-win_amd64.pyd

pyd files are binaries/dlls.You can not pass them to PyInstaller as script.

**Comment by tysondogerz** [comment]
Can you provide example I don't understand what you mean

**Comment by htgoebel** [comment]
Correct: `pyinstaller … my_module.py`  <-- script
Wrong: `pyinstaller … my_module….pyd`  <-- dll

**Comment by tysondogerz** [comment]
Wouldn't that just bundle the python without the cython though? What would be the need for bundling .dll and c for if you are just going to run decompile python? I don't understand.

**Comment by htgoebel** [comment]
Quoting from https://pyinstaller.readthedocs.io/en/stable/operating-mode.html
> PyInstaller reads a Python **script** written by you

.pyd is no python script but a dll.

Yes, the code of this script can be decompiled. Search the manual about this.

**Comment by tysondogerz** [comment]
Can you explain how adding cython files + dll files makes any difference? I will look into this thank you :).  If you add cython + dll + python file.  The python file still exists regardless if cython is included.  One option is just larger.

**Comment by tysondogerz** [comment]
Some of your modules.  I see.  So does that mean I'd have to rewrite a lot of my jobs in cython or would   from selenium.webdriver import chrome
import selenium
from selenium import webdriver
driver = webdriver.Chrome()
Have to be re-written as cython.  Sorry I'm a bit confused.  As HMM.  So you have to include a .py file but that can be re-written in cython..?  So I'd have to redesign the above and translate that to cython and its harder to decode?  Sorry I'm confused LOL

**Comment by htgoebel** [comment]
> So you have to include a .py file 

yes

> but that can be re-written in cython..?

no.

I strongly suggest you first learn how to use PyInstaller properly, then think about any Cython stuff.
