### ISSUE TITLE
Patoolib integration with Pyinstaller

### ISSUE THREAD

**Issue by Alegom** [pyinstaller/pyinstaller#3013]
Hi!

I'm using patoolib in one of my projects for extracting archives. I used Pyinstaller to get a single executable and the it does't work. My MWE is the following:

```
from patoolib import extract_archive
extract_archive('Test.zip',verbosity=-1)
```

Where "Test.zip" only contains a "Test.txt" inside. The executable was built with:

```
pyinstaller .\Zip.py -F
```

Running the script directly works, however with the executable I get the following error:

> Traceback (most recent call last):
>   File "site-packages\patoolib\__init__.py", line 553, in get_archive_cmdlist_func
>   File "importlib\__init__.py", line 126, in import_module
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 941, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "<frozen importlib._bootstrap>", line 994, in _gcd_import
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
> ModuleNotFoundError: No module named 'patoolib.programs'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "Zip.py", line 3, in <module>
>     extract_archive('Test.zip',verbosity=-1)
>   File "site-packages\patoolib\__init__.py", line 684, in extract_archive
>   File "site-packages\patoolib\__init__.py", line 472, in _extract_archive
>   File "site-packages\patoolib\__init__.py", line 555, in get_archive_cmdlist_func
> patoolib.util.PatoolError: No module named 'patoolib.programs'
> [3748] Failed to execute script Zip

I'm guessing it has to do with the way Pyinstaller incorporates patoolib into the executable, since the script runs nicely.

I'm using Windows 10 x64, with Python 3.6.3 x64 and Pyinstaller 3.3. Any questions I may answer, let me know. However, I believe the MWE can reproduce the issue quite well.

Thank you!

**Comment by htgoebel** [comment]
This looks like not all required modules are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by tallforasmurf** [comment]
Yes, as @htgoebel  says, something is missing. `patoolib__init__.py` appears to be the initial setup code, executed at the start of importing patool. (Incidentally is [this](https://pypi.python.org/pypi/patool/1.12) the lib you are trying to use?).

Something called `_gcd_import` (whatever that is) is trying to find something called `patoolib.programs` -- which from the name, is probably NOT a Python script. Maybe some kind of DLL or command-line program? Anyway, PyInstaller would not know to include such a thing, as it is not referenced from an import statement.

You need to dive into the patool code a bit (or maybe just poke around in the patool module folder and look at what non-Python files are in it) and figure out what are the extra data files? modules? it needs at run time, and add them using `--add-data` or `--add-binary` options.

**Comment by Kerang** [comment]
The error you are getting is, because pyinstaller isn't packaging the required submodules.

Specifically it's choking on the importlib statement:
```
    try:
        module = importlib.import_module(modulename, __name__)
    except ImportError as msg:
        raise util.PatoolError(msg)
```

There are various ways to fix this, but the seemingly accepted way to fix it in pyinstaller is to create a hook for the patoolib package.

Essentially it's not finding the programs directory in the patoolib package directory along with all of the files in the programs subdirectory. site-packages/patoolib/programs/*

Hook that should fix the issue:
```
#-----------------------------------------------------------------------------
# Copyright (c) 2013-2017, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


"""
patoolib uses importlib and pyinstaller doesn't find it and add it to the list of needed modules
"""


hiddenimports = [
    'patoolib.programs',
    'patoolib.programs.ar',
    'patoolib.programs.arc',
    'patoolib.programs.archmage',
    'patoolib.programs.bsdcpio',
    'patoolib.programs.bsdtar',
    'patoolib.programs.bzip2',
    'patoolib.programs.cabextract',
    'patoolib.programs.chmlib',
    'patoolib.programs.clzip',
    'patoolib.programs.compress',
    'patoolib.programs.cpio',
    'patoolib.programs.dpkg',
    'patoolib.programs.flac',
    'patoolib.programs.genisoimage',
    'patoolib.programs.gzip',
    'patoolib.programs.isoinfo',
    'patoolib.programs.lbzip2',
    'patoolib.programs.lcab',
    'patoolib.programs.lha',
    'patoolib.programs.lhasa',
    'patoolib.programs.lrzip',
    'patoolib.programs.lzip',
    'patoolib.programs.lzma',
    'patoolib.programs.lzop',
    'patoolib.programs.mac',
    'patoolib.programs.nomarch',
    'patoolib.programs.p7azip',
    'patoolib.programs.p7rzip',
    'patoolib.programs.p7zip',
    'patoolib.programs.pbzip2',
    'patoolib.programs.pdlzip',
    'patoolib.programs.pigz',
    'patoolib.programs.plzip',
    'patoolib.programs.py_bz2',
    'patoolib.programs.py_echo',
    'patoolib.programs.py_gzip',
    'patoolib.programs.py_lzma',
    'patoolib.programs.py_tarfile',
    'patoolib.programs.py_zipfile',
    'patoolib.programs.rar',
    'patoolib.programs.rpm',
    'patoolib.programs.rpm2cpio',
    'patoolib.programs.rzip',
    'patoolib.programs.shar',
    'patoolib.programs.shorten',
    'patoolib.programs.star',
    'patoolib.programs.tar',
    'patoolib.programs.unace',
    'patoolib.programs.unadf',
    'patoolib.programs.unalz',
    'patoolib.programs.uncompress',
    'patoolib.programs.unrar',
    'patoolib.programs.unshar',
    'patoolib.programs.unzip',
    'patoolib.programs.xdms',
    'patoolib.programs.xz',
    'patoolib.programs.zip',
    'patoolib.programs.zoo',
    'patoolib.programs.zopfli',
    'patoolib.programs.zpaq',
]
```

I tested it and it extracts the test.txt file from a 7-zip zip file I created.

**Comment by Alegom** [comment]
I'm not so experienced in this, so can you tell me exactly where should this hook be placed? In which file, I mean.

I'm assuming that after a possible update to this library I should re-apply the fix to be able to continue to run my script. Do you know how or if we should contact the developers and warn them about this incompatibility?

**Comment by Kerang** [comment]
You would create a new hook file in the hooks folder.
Location for Python 3.6 install on Windows 10:
C:\Users\your_username\AppData\Local\Programs\Python\Python36\Lib\site-packages\PyInstaller\hooks

Generic Path:
%Path to your python installation%\Lib\site-packages\Pyinstaller\hooks

You would create a hook with the filename "hook-patoolib.py" in the hooks folder and copy+paste the hook I created in the post above.

**Comment by Alegom** [comment]
Perfect, I had no idea how to do it. Thank you so much for your help!

I just read the header of the hook more closely, you're with the PyInstaller development team. Then I guess this will be part of the next release? Just confirming.

**Comment by htgoebel** [comment]
> can you tell me exactly where should this hook be placed?

You did read the manual, did you?

@Kerang Did I miss your pull-request?

**Comment by Kerang** [comment]
I haven't made a pull-request. I'm pretty new to git, so it'll take me a bit to get one done.

I was mostly bored and went looking for bugs similar to the one I came across. (Issues with pyttsx3 and dynamically loading modules with importlib.)

**Comment by Alegom** [comment]
> You did read the manual, did you?

Is there a manual for this kind of issue? Honestly, I'm learning as I go along and as problems come by. Never needed to look into something called "hooks" so far. Do you recommend some specific reading into this that might help in the future?

**Comment by tallforasmurf** [comment]
I imagine @htgoebel had [this section of the manual](http://pyinstaller.readthedocs.io/en/stable/hooks.html) in mind. I'm not sure if it is mentioned in that section, but it is not necessary to place the hook in the PyInstaller hooks folder. While you are testing it you can use the `--additional-hooks-dir` command parameter to place it anywhere convenient.

**Comment by Alegom** [comment]
Thank you for the link, it was an interesting read.

**Comment by htgoebel** [comment]
@Alegom Are you goint to provide a pull-request for this? Otherwise I'll close this issue.

**Comment by Alegom** [comment]
I don't understand what you want me to do.

**Comment by Legorooj** [comment]
I'm going to close this issue because there is a fix above. A PR can still be added at a later date.
