### ISSUE TITLE
pyinstaller and pandas._libs.tslibs.timedeltas

### ISSUE THREAD

**Issue by j-h-m** [pyinstaller/pyinstaller#3015]
I tried asking this question first on the IRC channel but got no responses.

**Machine setup:**
OS: Debian 9.2 stretch
Kernel: x86_64 Linux 4.9.0-4-amd64
DE: XFCE
WM: Xfwm4
WM Theme: Default
CPU: Intel Core i7 CPU 860 @ 2.801GHz
GPU: GeForce 8400GS/PCIe/SSE2
RAM: 7946MiB

**Python setup:**
Python 3.5.3
pip version:
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
venv version:
python3-venv/stable,stable,stable,now 3.5.3-1 amd64 [installed]

**pyinstaller command** (searches all directories in venv for modules)
> pyinstaller --clean --paths /home/workit/Programming/pd-project-main/:/home/workit/Programming/pd-project-main/Plant-Digitization-Project/:/home/workit/Programming/pd-project-main/Plant-Digitization-Project/kraldesk/ -w --distpath /home/workit/Programming/pd-project-main/kraldesk-build --workpath /home/workit/Programming/pd-project-main/kraldesk-build-temp/ --specpath /home/workit/Programming/pd-project-main/kraldesk-build ./kraldesk.py

**Error (caused by running created executable)**
> ImportError: C extension: No module named 'pandas._libs.tslibs.timedeltas' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.

**python REPL in same venv**

>>> import pandas._libs.tslibs.timedeltas as pt_td
>>> help(pt_td)

> Help on module pandas._libs.tslibs.timedeltas in pandas._libs.tslibs:
> 
> NAME
>     pandas._libs.tslibs.timedeltas
> 
> FUNCTIONS
>     cast_from_unit(...)
>         return a casting of the unit represented to nanoseconds
>         round the fractional part of a float to our precision, p
> 
> DATA
>     __pyx_capi__ = {'cast_from_unit': <capsule object "__pyx_t_5numpy_int6...
>     __test__ = {}
> 
> FILE
>     /home/workit/Programming/pd-project-main/lib/python3.5/site-packages/pandas/_libs/tslibs/timedeltas.cpython-35m-x86_64-linux-gnu.so
> 
> 
> >>>

**Comment by su79eu7k** [comment]
Hello, did you checked following issue page? I've experienced the simillar problem but solved with proposed hook file on Pandas missing `pandas._libs.tslibs.timedeltas.so` #2998

**Comment by j-h-m** [comment]
So until he merges the pull request I should clone the repo and use the file you added?

**Comment by j-h-m** [comment]
I added the hook file in the referenced pull request [https://github.com/pyinstaller/pyinstaller/pull/2998](#2998) and that fixed my issue with pandas!

**Comment by htgoebel** [comment]
Duplicate of #2978
