### ISSUE TITLE
Repackaging executable?

### ISSUE THREAD

**Issue by tysondogerz** [pyinstaller/pyinstaller#3016]
Pyinstaller not recognising path inside the executable.
I have setup.py, main.py and cython.pyx

RUN: pyinstaller main.spec

Does not work unless I add chrome inside folder.  Any workaround for this?

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by htgoebel** [comment]
Beside of this I strongy recommend starting with *simple* programs, Neither Cython nor selenium are simple.
