### ISSUE TITLE
I have an error when exporting a project with tkinter

### ISSUE THREAD

**Issue by Moriand** [pyinstaller/pyinstaller#3018]
hello creators, my problem is the following, when I export to exe, I get error, I currently have a windows 10 and python 3.6. I'll leave some liks where I posted and I do not have a solution

https://github.com/Moriand/trabajos-Unprg-Lep1/blob/master/program.py

**pyinstaller --windowed --onedir -i icono.ico ui.py**
          image preview
https://i.stack.imgur.com/FyqBt.png
https://i.stack.imgur.com/EIj2t.png
https://i.stack.imgur.com/bx5Ci.png

can you export it and tell me how it works for export, I need to know what supplements are necessary

**Comment by htgoebel** [comment]
Please past the text here, not images. Images can not be quoted. Thanks.

> can you export it and tell me how it works for export

If you want commercial support for finishing you project, please drop ma a mail.

**Comment by Moriand** [comment]
It's not for commercial, it's a university student project

**Comment by htgoebel** [comment]
So I suggest studying :-) the manual, esp. section If things go wrong, the resp. page in the wiki and  [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly).
