### ISSUE TITLE
Tkinter not working - Any solutions?

### ISSUE THREAD

**Issue by Happyquack** [pyinstaller/pyinstaller#3019]
I've been reading previous issues about this, and it was established in one of them (Too many to remember which one) that this was a bug on Python's part. Still, does anyone have any solutions for this?

I am trying to import graphics.py, which then imports Tkinter. Here is the error message when trying to run the file after using PyInstaller:

> Traceback (most recent call last):
  File "graphics.py", line 155, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "tkinter/__init__.py", line 35, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: dlopen(/var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIZBJPMY/_tkinter.so, 2): Library not loaded: @loader_path/Tcl
  Referenced from: /var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIZBJPMY/_tkinter.so
  Reason: no suitable image found.  Did find:
	/var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIZBJPMY/Tcl: not a file
	/private/var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIZBJPMY/Tcl: not a file
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "checkers.py", line 8, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "graphics.py", line 157, in <module>
ImportError: No module named 'Tkinter'
[30748] Failed to execute script checkers
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
[Process completed]

I have never seen an exception happen during the handling of another exception, so this is quite (pun not originally intended) exceptional.
Any thoughts?

EDIT:
I just realized I haven't added any specs.
OS: Macbook Air OS X El Capitan
Python: Version 3.5.2
PyInstaller version: 3.3
Anything else you want to know?

**Comment by Happyquack** [comment]
I'm doing some troubleshooting right now and found this segment in the log when building the bundle:
> 5445 INFO: Loading module hooks...
5445 INFO: Loading module hook "hook-pydoc.py"...
5447 INFO: Loading module hook "hook-_tkinter.py"...
5463 INFO: checking Tree
5485 INFO: checking Tree
5508 INFO: Loading module hook "hook-encodings.py"...
5605 INFO: Loading module hook "hook-xml.py"...
6002 INFO: Looking for ctypes DLLs
6027 INFO: Analyzing run-time hooks ...
6030 INFO: Including run-time hook 'pyi_rth__tkinter.py'
6038 INFO: Looking for dynamic libraries
6269 INFO: Looking for eggs
6270 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.5/Python

I think PyInstaller is hooking tkinter instead of Tkinter.

**Comment by tallforasmurf** [comment]
Just looking at your original comment "I think PyInstaller is hooking tkinter instead of Tkinter." Well, yeah, it should. Because in Python 3, that is the proper name of the module. In Python **2.x** it is named Tkinter. Could it be that you somehow have a Python 2 version of some module mixed into your installation? Suggest perhaps building a clean virtual environment with Python 3.5, and inside it do pip install of any third party modules and PyInstaller.

**Comment by Happyquack** [comment]
Thanks! That fixed the second error. graphics.py was try/excepting importing tkinter and Tkinter, to be compatible for Python 2 and 3. Replacing that with "import tkinter" gave me one less error. Also, the giant spam of warning messages during the bundling is gone. However, this still happens at runtime:

> Traceback (most recent call last):
  File "checkers.py", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "graphics.py", line 154, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "tkinter/__init__.py", line 35, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: dlopen(/var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIe6rblg/_tkinter.so, 2): Library not loaded: @loader_path/Tcl
  Referenced from: /var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIe6rblg/_tkinter.so
  Reason: no suitable image found.  Did find:
	/var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIe6rblg/Tcl: not a file
	/private/var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIe6rblg/Tcl: not a file
[3025] Failed to execute script checkers
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...106 completed.
[Process completed]

I'm guessing this is the bug in the Tcl code?

**Comment by rokm** [comment]
Closing this issue do to the age and because the issues with (older) python.org builds that use system Tcl/Tk should be fixed now
(99c6e8bd07cb14dbb3e307d36ade0c021147cf37).

The problem, also indicated here in the follow-up report, was that the built program was looking for the system Tcl/Tk library in the
application directory and not in its original system directory:
```
ImportError: dlopen(/var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIe6rblg/_tkinter.so, 2): Library not loaded: @loader_path/Tcl
```
which also caused a name clash with the directory used for Tcl/Tk data in the application directory:
```
/var/folders/n4/y536ndjx32g552kvf698qw04mlrmct/T/_MEIe6rblg/Tcl: not a file
```

The underlying issue should be taken care of by the afore-mentioned commit.
