### ISSUE TITLE
Error Loading Python.dll

### ISSUE THREAD

**Issue by DaytonaJohn** [pyinstaller/pyinstaller#3020]
Getting the subject error when I try to run an app packaged with the -F option. Here is the entire error when I move main.exe to 'C:\Users\John\PycharmProjects\KivyTest:

Error loading Python DLL 'C:\Users\John\PycharmProjects\KivyTest\python36.dll'.
LoadLibrary: The specified module could not be found.

I am using Pyinstaller version 3.4.dev0+97ce49bad
Python  3.6.2 (v3.6.2:5fd33b5, Jul  8 2017, 04:57:36) [MSC v.1900 64 bit (AMD64)] on win32
kivy  v1.10.0

Here is the app (main.py):

    from kivy.app import App
    from kivy.uix.label import Label

    class TestApp(App):
        def build(self):
            return Label(text='Test')

    if __name__ == '__main__':
        app = TestApp()
        app.run()

Here is my main.spec:

    # -*- mode: python -*-
    from kivy.deps import sdl2, glew

    block_cipher = None

    options = [ ('v', None, 'OPTION'), ('W ignore', None, 'OPTION') ]

    a = Analysis(['main.py'],
             pathex=['C:\\Users\\John\\PycharmProjects\\KivyTest'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
    pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
    exe = EXE(pyz,
          a.scripts,
          options,
          exclude_binaries=True,
          name='main',
          debug=False,
          strip=False,
          upx=False,
          console=True )
    coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
               strip=False,
               upx=False,
               name='main')

The log of my Pyinstaller run (pyinstaller -F main.spec):
https://gist.github.com/DaytonaJohn/19e7274b7804f237704f46603ebaec5b

It does not appear to make any difference whether I use the '-F', '-D', '--onefile', or '--onedir' options. The output in the 'dist' directory is always the same and the log file is nearly identical (except for line prefix numbers). The app runs fine if I execute it from `dist\main\main.exe`, but fails with the above error if main.exe is moved out of that directory. The python36.dll file is in that same directory. Obviously, python36.dll is not being bundled in main.exe. I have seen several reports of this problem, but none of the fixes worked for me. I encountered this problem with a much more complicated app, but it appears with this simple app also. Am I doing something wrong? Any help is appreciated.

**Comment by DaytonaJohn** [comment]
Not apparent in the documentation, but the "-F", "-D", "--onefile", and "--onedir" are ignored by pyinstaller if you pass a spec file as the argument.  So the answer to my question is to do `pyi-makespec --onefile main.py`. Now the spec file will create a onefile bundle regardless of which of the above options are passed to pyinstaller.

**Comment by tallforasmurf** [comment]
Maybe not "apparent" but it is there. See the lines just preceding [this heading](http://pyinstaller.readthedocs.io/en/stable/spec-files.html#spec-file-operation): "Only the following command-line options have an effect when building from a spec file:"

**Comment by DaytonaJohn** [comment]
In fact, it is so not apparent, that the documentation shows examples like:
`pyinstaller --noconfirm --log-level=WARN ^
    --onefile --nowindow ^
    --add-data="README;." ^
    --add-data="image1.png;img" ^
    --add-binary="libfoo.so;lib" ^
    --hidden-import=secret1 ^
    --hidden-import=secret2 ^
    --icon=..\MLNMFLCN.ICO ^
    myscript.spec`

**Comment by htgoebel** [comment]
@DaytonaJohn Of course, this needs to be fixed. May I ask you to provide a pull-request? Maybe you even have an idea how to emphasize that most options will not work when using he .spec file.

**Comment by DaytonaJohn** [comment]
@htgoebel I have never done a pull request, but I will research how it is done and give it my best shot. Pyinstaller is an awesome tool and clear documentation is essential for any tool.
