### ISSUE TITLE
Help: Default system icon

### ISSUE THREAD

**Issue by xp4xbox** [pyinstaller/pyinstaller#3021]
Is there a way to use the default system icon for the .exe?

**Comment by htgoebel** [comment]
What is the "default system icon"?
Possible duplicate of #2995.

**Comment by xp4xbox** [comment]
I mean, when there is no icon, and window gives the .exe icon which varies depending on the windows version.

**Comment by htgoebel** [comment]
The .exe generated by PyInstaller always has an icon. You can replace the icon by using `--icon` and providing a proper .ico file. I don't understand what you mean.

**Comment by xp4xbox** [comment]
For example, if you use py2exe to generate an icon, it will give the program no icon, which means that windows automatically gives it an icon that is registered to a .exe file.

**Comment by htgoebel** [comment]
This is not supported. PyInstaller always includes an icon. If you want this to be changed, please implement #870 and plus an option `--icon=NONE`.

**Comment by xp4xbox** [comment]
I guess i will just use resource hacker for the time being
