### ISSUE TITLE
No module named 'csv' adding bulk imports

### ISSUE THREAD

**Issue by tysondogerz** [pyinstaller/pyinstaller#3030]
ModuleNotFoundError: No module named 'csv'
I am wanting to load lots of imports. I have read you can add modules individually through the spec file, but I have lots of imports. Any ideas how I can add a collection of imports so my job can run

Spec file: - Tried to Adjust pathex, in the hopes it would grab hiddenimports, hookspath to include Miniconda library but I don't think this is supported.

```
block_cipher = None

a = Analysis(['main.py'],
             pathex=['C:\\Users\\H1\\example-of-cython-pyinstaller-and-subzero', 'C:\\Users\\H1\\AppData\\Local\\Continuum\\miniconda3\\Lib'],
             binaries=[],
             datas=None,
             hiddenimports=['Main.py', 'C:\\Users\\H1\\AppData\\Local\\Continuum\\miniconda3\\Lib'],
             hookspath=['C:\\Users\\H1\\AppData\\Local\\Continuum\\miniconda3\\Lib'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
a.datas += [('logo.ico','C:\\vv.ico','DATA')]
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='VB BABY',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True , icon='C:\\vv.ico')
```

**Comment by htgoebel** [comment]
Please provide more information, esp. the traceback (last 20 lines) of your application.

**Comment by htgoebel** [comment]
> I am wanting to load lots of imports. I have read you can add modules individually through the spec file, but I have lots of imports.

This and the obvious errors in your .spec-file leads me to the impression that you should read the manual to get a understanding of how PyInstaller is working.

**Comment by tysondogerz** [comment]
>>>>>>>>>>>>>>>>>>>IMPORTS<<<<<<<<<<<<<<<<<<<<<

import csv
import inspect
import os
import random
import sys
import time
import selenium
import selenium.common.exceptions as SeleniumExceptions
from selenium import webdriver


>>>>>>>>>>>>>>>>>>>ERROR CODE<<<<<<<<<<<<<<<<<<<<<


DevTools listening on ws:
Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "main.py", line 22, in main
  File "C:\Users\H1\AppData\Local\Continuum\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "myapp\cython_module.pyx", line 3, in init myapp.cython_module
ModuleNotFoundError: No module named 'csv'
[14952] Failed to execute script main 




>>>>>>>>>>>>>>>>>>>MODULES<<<<<<<<<<<<<<<<<<<<<

Missing imports text file:
Missing imports text file:
missing module named resource - imported by posix, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named posix - imported by os, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _posixsubprocess - imported by subprocess, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named readline - imported by cmd, code, pdb, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _winreg - imported by platform, selenium.webdriver.firefox.firefox_binary, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named 'java.lang' - imported by platform, xml.sax._exceptions, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named vms_lib - imported by platform, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named termios - imported by tty, getpass, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named grp - imported by shutil, tarfile, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _dummy_threading - imported by dummy_threading, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named 'org.python' - imported by copy, xml.sax, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named pwd - imported by posixpath, shutil, tarfile, http.server, webbrowser, netrc, getpass, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named org - imported by pickle, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named urllib2 - imported by selenium.webdriver.common.utils, selenium.webdriver.remote.remote_connection, selenium.webdriver.common.service
missing module named StringIO - imported by selenium.webdriver.remote.webelement
missing module named urlparse - imported by selenium.webdriver.remote.remote_connection
missing module named httplib - imported by selenium.webdriver.firefox.webdriver, selenium.webdriver.remote.remote_connection, selenium.webdriver.safari.webdriver, selenium.webdriver.blackberry.webdriver
missing module named cStringIO - imported by selenium.webdriver.firefox.firefox_profile
missing module named copy_reg - imported by cStringIO

**Comment by htgoebel** [comment]
@tysondogerz No links, paste the text here.

**Comment by tysondogerz** [comment]
>>>>>>>>>>>>>>>>>>>IMPORTS<<<<<<<<<<<<<<<<<<<<<

```
import csv
import inspect
import os
import random
import sys
import time
import selenium
import selenium.common.exceptions as SeleniumExceptions
from selenium import webdriver
```


>>>>>>>>>>>>>>>>>>>ERROR CODE<<<<<<<<<<<<<<<<<<<<<


```
DevTools listening on ws:
Traceback (most recent call last):
  File "main.py", line 28, in <module>
  File "main.py", line 22, in main
  File "C:\Users\H1\AppData\Local\Continuum\miniconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "myapp\cython_module.pyx", line 3, in init myapp.cython_module
ModuleNotFoundError: No module named 'csv'
[14952] Failed to execute script main 

```



>>>>>>>>>>>>>>>>>>>MODULES<<<<<<<<<<<<<<<<<<<<<

```
Missing imports text file:
Missing imports text file:
missing module named resource - imported by posix, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named posix - imported by os, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _posixsubprocess - imported by subprocess, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named readline - imported by cmd, code, pdb, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
excluded module named _frozen_importlib - imported by importlib, importlib.abc, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _frozen_importlib_external - imported by importlib._bootstrap, importlib, importlib.abc, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _winreg - imported by platform, selenium.webdriver.firefox.firefox_binary, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _scproxy - imported by urllib.request
missing module named java - imported by platform, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named 'java.lang' - imported by platform, xml.sax._exceptions, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named vms_lib - imported by platform, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named termios - imported by tty, getpass, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named grp - imported by shutil, tarfile, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named _dummy_threading - imported by dummy_threading, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named 'org.python' - imported by copy, xml.sax, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named pwd - imported by posixpath, shutil, tarfile, http.server, webbrowser, netrc, getpass, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named org - imported by pickle, C:\Users\H1\example-of-cython-pyinstaller-and-subzero\main.py
missing module named urllib2 - imported by selenium.webdriver.common.utils, selenium.webdriver.remote.remote_connection, selenium.webdriver.common.service
missing module named StringIO - imported by selenium.webdriver.remote.webelement
missing module named urlparse - imported by selenium.webdriver.remote.remote_connection
missing module named httplib - imported by selenium.webdriver.firefox.webdriver, selenium.webdriver.remote.remote_connection, selenium.webdriver.safari.webdriver, selenium.webdriver.blackberry.webdriver
missing module named cStringIO - imported by selenium.webdriver.firefox.firefox_profile
missing module named copy_reg - imported by cStringIO 
```

**Comment by htgoebel** [comment]
To be frank, I become bored by all the tickets you are opening. They show that you are lacking knowledge about what Cython does and how it works, and about what PyInstaller does and how it works. Please take *your* time to learn this, instead of wasting *my* time. I'm not going to teach you what is already written in the manual. Thank. If you want commercial support, please drop my an email.
