### ISSUE TITLE
Infinite recursion in "import decimal"

### ISSUE THREAD

**Issue by dcolascione** [pyinstaller/pyinstaller#3040]
With Ubuntu 14.04 Python 3.4 and latest pyinstaller (3.4.dev0+d258d2882), running pyinstaller on a file containing "import decimal" fails. The reason is that this system distribution of Python doesn't have a "_decimal" module for whatever reason. decimal tries to import _decimal and fails gracefully if it fails. Pyinstaller thinks _decimal is some kind of SWIG candidate, however, and so retries to import it over and over, eventually running off the end of the stack.

**Comment by htgoebel** [comment]
To verify this, please revert commit 711e9e77c93a979a63648ba05f725b30dbb7c3cc (which is the one introducing this behaviour). Try is this solve the issue and report back here. Thanks.

**Comment by htgoebel** [comment]
I tried reproducing this (by moving _decimal.so out of the way), but this error is not triggered here. So I nee you help to track this down. Please do the following:
1. Add these lines to the top of PyInstaller/lib/modulegraph/modulegraph.py  -> `is_swig_candidate()` (should be line 2183):
```
            if target_module_partname == "_decimal":
                import pdb ; pdb.set_trace()
```
2. Run pyinstaller
3. When the debugger steps in, check the values, which are checked in `is_swig_candidate()`, like this
```
(Pdb) p source_module
SourceModule('decimal', '/usr/lib64/python3.5/decimal.py')
(Pdb) p target_attr_names
[]
(Pdb) p level, ABSOLUTE_IMPORT_LEVEL
(0, 0)
(Pdb) p type(source_module)
<class 'PyInstaller.lib.modulegraph.modulegraph.SourceModule'>
(Pdb) p target_module_partname, '_' + source_module.identifier.rpartition('.')[2]
('_decimal', '_decimal')
(Pdb) p sys.version_info[0]
3
```
4. Report what differs on your system form the values shown above. Thanks.

**Comment by htgoebel** [comment]
This should be solved now. Please try the current development version. If the problem still persists, please drop a note and reopen the ticket. Thanks.
