### ISSUE TITLE
execute to exe. successful by pyinstaller, but the exe. is not work.

### ISSUE THREAD

**Issue by dat8866** [pyinstaller/pyinstaller#3044]
It's work on Spyder (Anaconda3) and execute script to exe by pyinstaller without any #errors, but nothing happens when I double click exe  (also try cx_freeze, but still not work either).How can I debug it? Appreciate for your help.
```
import os,shutil
cur_path=os.path.dirname(__file__)
sample_tree=os.walk(cur_path)
for dirname,subdir,files in sample_tree:
    allfiles=[]
    basename=os.path.basename(dirname)

    for file in files:
        ext=file.split('.')[-1]
        if ext=="csv":#讀取.csv to allfiles
            allfiles.append(file)
        elif ext=='log':#讀取.log to allfiles
            allfiles.append(file)

    for file in allfiles:#Copy csv and log of sample_tree to destfolder
        destfile = cur_path
        srcfile=dirname + "/" + file
        shutil.move(srcfile,destfile)
```
p.s. python 3.6/pyinstaller 3.3/Win 10

**Comment by htgoebel** [comment]
First of all you should run you program from the command line (shell, cmd) to see errors. Then please follow the guides at https://pyinstaller.readthedocs.io/en/latest/when-things-go-wrong.html and https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong

**Comment by htgoebel** [comment]
No more reaction, I assume this is solved.
