### ISSUE TITLE
Disable the pyinstaller-osx-tests respository on Travis CI

### ISSUE THREAD

**Issue by xoviat** [pyinstaller/pyinstaller#3059]
The [osx tests](https://travis-ci.org/pyinstaller/pyinstaller-osx-tests) repository is not helping anyone, and is in fact taking up precious OSX slots. It should be disabled.

**Comment by htgoebel** [comment]
ACK, I'll disable it. (But beside the change to the readme yesterdays, this did not run for month, if not years.)

**Comment by htgoebel** [comment]
I renamved the `.travis.yml` (see https://github.com/pyinstaller/pyinstaller-osx-tests/commit/9b06856750b3fafd34f12899b8da4d98875d14ea) and also disabled the repository at travis.
