### ISSUE TITLE
No matching distribution found for dis3

### ISSUE THREAD

**Issue by stephensolis** [pyinstaller/pyinstaller#3065]
From a clean Python 2.7 install:

```
$ pip install pyinstaller
Collecting pyinstaller
  Downloading PyInstaller-3.3.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 268kB/s 
Collecting setuptools (from pyinstaller)
  Downloading setuptools-38.2.3-py2.py3-none-any.whl (489kB)
    100% |████████████████████████████████| 491kB 1.7MB/s 
Collecting pefile>=2017.8.1 (from pyinstaller)
  Downloading pefile-2017.11.5.tar.gz (61kB)
    100% |████████████████████████████████| 71kB 7.1MB/s 
Collecting macholib>=1.8 (from pyinstaller)
  Downloading macholib-1.9-py2.py3-none-any.whl (40kB)
    100% |████████████████████████████████| 40kB 5.8MB/s 
Collecting dis3 (from pyinstaller)
  Could not find a version that satisfies the requirement dis3 (from pyinstaller) (from versions: )
No matching distribution found for dis3 (from pyinstaller)
```

It seems dis3 has been pulled from PyPI (https://pypi.python.org/pypi/dis3), and its repo no longer exists (https://github.com/tomxtobin/python-dis3)

**Comment by KeyWeeUsr** [comment]
Confirmed. The author apparently nuked his work. Google cache to the rescue:

[dis3-0.1.1.tar.gz](https://github.com/pyinstaller/pyinstaller/files/1524688/dis3-0.1.1.tar.gz)

**Comment by htgoebel** [comment]
Thanks!

**Comment by andrewbollen** [comment]
Since dis3 v0.1.1 disappeared, I have been on v0.1.2. Every executable generated is now flagged by google as containing a virus....

**Comment by stephensolis** [comment]
@andrewbollen I think this is something else in your app/site/computer, my executables are showing as clean on VirusTotal, and a diff shows no code differences between [dis3 0.1.1](https://github.com/pyinstaller/pyinstaller/files/1524688/dis3-0.1.1.tar.gz) and [dis3 0.1.2](https://github.com/KeyWeeUsr/python-dis3/archive/v0.1.2.tar.gz).

**Comment by htgoebel** [comment]
@andrewbollen 
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by htgoebel** [comment]
For the records: KeyWeeUsr took over the maintenance of dis3. The PyPI entry is pointing to the new repo and there is even a new release (with changes to meta-data only).
