### ISSUE TITLE
Drop undocumened "feature" of  destination-path for `--add-data` and `--add-binary`?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#3066]
Currently (v3.3), the destination-path `--add-data` and `--add-binary` as well as the `Analysis()` parameters `data` and `binaries` have an undocumented "feature" (*):

The destination-path (second element) can be an empty string, in which case the target directory's name is the source directory's basename.

I propose to **remove this behavior**. Instead, if an empty string is passed, PyInstaller should terminate with a useful message. E.g. `"Empty target not allowed. Maybe you want to used %r" % os.curdir`

### Rational

- The behavior is not documented in the manual and is not documented well in the code.
- The behavior is not obvious.
- This only works if the source is a directory or the source-glob only contains directories. As soon as
  the source is a file (of a glob resulting in a file), the empty string is not handled in the code and files
   will end up somewhere.
- The same can be achieved easily by just adding the directory basename as destination.
- This is a source of errors, see e.g. #3062 .

What do you think?

(*) To be more precise: The behavior of the empty string only [documented in the code](https://github.com/pyinstaller/pyinstaller/blob/v3.3/PyInstaller/building/utils.py#L449), but the manual does not mention it. Also the manual does not contain an example with an empty target path.

**Comment by tallforasmurf** [comment]
FIne by me. Minor comments on the message. One, it should use the same term as in the docs, which is consistently "DEST" ("--add-binaries SRC:DEST"). Two, I do not understand suggesting `os.curdir` as a DEST argument. Would that be valid for a bundled app on another machine?

Another bit of tidy-up (maybe need a different issue#) would be clarify the sections [Adding Data Files](http://pyinstaller.readthedocs.io/en/stable/spec-files.html?highlight=add-data#adding-data-files) and [Adding Binary Files](http://pyinstaller.readthedocs.io/en/stable/spec-files.html?highlight=add-data#adding-binary-files) by using the terms "SRC" and "DEST" in those sections. To more clearly associate them to the command syntax used earlier in the manual.
