### ISSUE TITLE
PyInstaller Error: Crypto.Cipher._raw_ecb not CryptoDemo

### ISSUE THREAD

**Issue by wcraig2012** [pyinstaller/pyinstaller#3067]
Has anyone solved the problem "OSError: Cannot load native module 'Crypto.Cipher._raw_ecb'", but not the CryptoDemo problem when using web3.py package?
I am in a quite hurry.
Thanks a lot.

**Comment by htgoebel** [comment]
Duplicate of #1983

**Comment by htgoebel** [comment]
This is a bug tracker, not a forum!
