### ISSUE TITLE
gtk3 (pygobject): invisible CheckButton

### ISSUE THREAD

**Issue by thekswenson** [pyinstaller/pyinstaller#3069]
CheckButtons are invisible after using pyinstaller on my system Ubuntu 17.10.

Without pyinstaller:
![goodone](https://user-images.githubusercontent.com/9959942/33561713-b07169bc-d913-11e7-91a6-b00b7e414eee.png)
With pyinstaller:
![badone](https://user-images.githubusercontent.com/9959942/33561721-b852534e-d913-11e7-8928-039ef6a129b1.png)

Here is the minimal example to reproduce the problem:

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk

class ToggleButtonWindow(Gtk.Window):

    def __init__(self):
        Gtk.Window.__init__(self, title="CheckButton Demo") 
        self.set_border_width(10)

        hbox = Gtk.Box(spacing=6)
        self.add(hbox)

        button = Gtk.CheckButton("Check This")
        button.connect("toggled", self.on_button_toggled, "1")
        hbox.pack_start(button, True, True, 0)

    def on_button_toggled(self, button, name):
        if button.get_active():
            state = "on"
        else:
            state = "off"
        print("Button", name, "was turned", state)

win = ToggleButtonWindow()
win.connect("delete-event", Gtk.main_quit)
win.show_all()
Gtk.main()
```

=> pyinstaller --version
3.4.dev0+gd2fbf77a

**Comment by htgoebel** [comment]
This looks like not all required files are packaged and some image is missing. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing. Esp. you may use `strace -o /tmp/trace.txt -e trace=%file` to check which files are not found.

**Comment by thekswenson** [comment]
Here is the output of `strace -o /tmp/trace.txt -e trace=file dist/checkbutton_demo/checkbutton_demo`

>execve("dist/checkbutton_demo/checkbutton_demo", ["dist/checkbutton_demo/checkbutto"...], [/* 79 vars */]) = 0
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> access("/etc/ld.so.preload", R_OK)      = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libz.so.1", O_RDONLY|O_CLOEXEC) = 3
> access("/etc/ld.so.nohwcap", F_OK)      = -1 ENOENT (No such file or directory)
> openat(AT_FDCWD, "/lib/x86_64-linux-gnu/libc.so.6", O_RDONLY|O_CLOEXEC) = 3
> readlink("/proc/self/exe", "/home/kms/home/gdkpyinstaller/di"..., 4096) = 68
> openat(AT_FDCWD, "/home/kms/home/gdkpyinstaller/dist/checkbutton_demo/checkbutton_demo", O_RDONLY) = 3
> --- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=5931, si_uid=1000, si_status=0, si_utime=12, si_stime=2} ---
> +++ exited with 0 +++

It appears as though some files give a "No such file or directory" message, but these files don't exist on my system and the scripts works normally!?

**Comment by htgoebel** [comment]
Oh, i missed the `-f` option (you may even better use `-ff`, see the man page). And please **do not post the strace output here**. It is long! You need to analyze it yourself, may compare with the output of the unfrozen application.

BTW: Did you follow https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Gtk-Application

**Comment by thekswenson** [comment]
Thanks for the quick reply!
The link you sent me is entitles "Bundling a GTK Application (in OS X)", but I'm running Ubuntu 17.10.

I see the "Support" tag on this issue...
   are you sure it is not a bug.  This is a minimal example with a CheckButton.  Won't any GTK3 application have this problem?

**Comment by thekswenson** [comment]
OK.  I'm looking into those strace outputs.
All I'm saying is that I have a basic Ubuntu 17.10 installation and I'm using the standard GTK3, so someone is bound to have the same problem as I do...
   I'll do my best to compare those strace outputs.

**Comment by thekswenson** [comment]
It turns out that the files:

- backdrop-check-unselected.png
- check-unselected.png
- check-unselected-hover.png
- check-selected-hover.png

aren't getting copied into the dist directory "share/themes/Ambiance/gtk-3.20/assets/".

How would I ensure that pyinstaller imports these?
I'm guessing there would be a similar problem for other like "radio-selected.png"?

**Comment by thekswenson** [comment]
I found the issue:  hook-gi.repository.Gtk.py imports the icons from the directory "/usr/share/themes/Ambiance/gtk-3.0/assets", whereas the frozen version of the program is looking for "share/themes/Ambiance/gtk-3.20/assets" which is not imported.  Curiously, everything else in "share/themes/Ambiance/gtk-3.20/" is imported.

**Comment by thekswenson** [comment]
It turns out that we're dealing with a soft link:
```
=> ll /usr/share/themes/Ambiance/gtk-3.20/assets
lrwxrwxrwx 1 root root 17 Oct  7  2016 /usr/share/themes/Ambiance/gtk-3.20/assets -> ../gtk-3.0/assets/
```
So in collect_system_data_files() of "PyInstaller/utils/hooks/__init__.py", at line 756 we have ` for dirpath, dirnames, files in os.walk(path):` which does not follow symlinks.

I'm not sure what your preference is for fixing this.

**Comment by thekswenson** [comment]
So, you would want a replacement for `collect_glib_share_files()` (e.g.  `collect_glib_theme_files()`) that is specifically meant for theme files?

**Comment by thekswenson** [comment]
I could get the current theme name using `Gtk.Settings.get_default().get_property("gtk_theme_name")`, thereby avoiding the importation of the non-used themes.   I'm not sure how to programmatically find the directory of the theme though.  In this case the theme exists under both the "gtk-3.20" and "gtk-3.0" directories, yet only the "gtk-3.20" directory is being used by the program.

Since we're limiting the theme to only the current theme, we could afford to follow symlinks with `os.walk()`, keeping a dictionary to ensure that we don't revisit directories.  This would avoid the problem of having to know the exact theme directory.

What do you think @htgoebel ?

**Comment by htgoebel** [comment]
> I could get the current theme name

Sounds okay.

Regarding the other things, I have no strong opinion as long as the tests pass. And of course, some (unit) tests would be great!

For discussion this in detail, I ask you to open a new ticket, like "Implementing GTK theme support". Thus this topic can be found easily later. Thanks.
