### ISSUE TITLE
Exception: Cannot find PyQt4 plugin directories. Happens while I'm trying to make use pyinstaller on a script with pillow import.

### ISSUE THREAD

**Issue by AnkanDas22** [pyinstaller/pyinstaller#3080]
Everytime it fails to successfully make the executable because of an error "Exception: Cannot find PyQt4 plugin directories."
I can't quite understand what it means, I tried reinstalling PyQt4 but to no avail, now I'm posting here.

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by AnkanDas22** [comment]
Okay I'll try but the problem is I'll have to reinstall Python 3.6 again.
I actually deleted Python 3.6 and installed 3.4.3 and that seems to have fixed the problem.
Although I tried with py2exe and py2exe again required Python 3.4.3 but just installing Python 3.4.3 seems to have fixed all the problems.
Okay I'll try it out on my lappy tomorrow and get back to you.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solves.
