### ISSUE TITLE
Implementing GTK theme support

### ISSUE THREAD

**Issue by thekswenson** [pyinstaller/pyinstaller#3084]
This ticket will be associated with the implementation of GTK theme support.
The goal is to import the files only for the current them, instead of all the themes.

My main motivation is to take care of the issue https://github.com/pyinstaller/pyinstaller/issues/3069 where a symbolic link is not collected in a way that it can be used by the frozen application.

**Comment by thekswenson** [comment]
@htgoebel :  I have implemented a fix and am wondering how to properly test it.  I notice that the development branch fails many unit tests.

Should I just make sure no additional failures are induced by the new code?
Also, could you give me a hint on how you would like me to add new unit tests?  The code depends on having links in the directory structure.  Should I commit a test directory structure to the repo or something?

**Comment by stormbeforesunsetbee** [comment]
Guys, why don't we close this issue already, as now we have a better Gtk hook with icon, theme, and language options?

**Comment by bwoodsend** [comment]
Agreed, theme limitation was done ages ago.
