### ISSUE TITLE
[Question] How to list and extract bundled files dynamically after freezing using --onefile

### ISSUE THREAD

**Issue by Code-ReaQtor** [pyinstaller/pyinstaller#3092]
Hello PyInstaller devs,

Is there a way to list and extract bundled files dynamically after freezing an application using the `--onefile` parameter? I would like to allow the user to save bundled files to target directories. Are the "assets" or embedded data extracted somewhere at run time?

Cheers!

**Comment by tallforasmurf** [comment]
The data and binary files in a —onefile bundle are unpacked into a temporary folder, recreating the one-folder layout, as described in the manual. So whatever you bundle could potentially be copied from there while the app is running. Note there is a mailing list which might be better for non-problem queries like this.
