### ISSUE TITLE
Pyinstaller no window does not work in windows

### ISSUE THREAD

**Issue by jytinjalmon** [pyinstaller/pyinstaller#3095]
Converting to pyw does nothing

pyinstaller --noconsole myscript.py

Does nothing

using pyinstaller  -W -F name.py  creates a script that cannot work.

Using it with console works.

I get spammed with so many error messages its unbelievable.   I cannot find a way on windows to suppress error messages in pyinstaller or disable.  I read this is common issue.  What is work around?  Is there work around?

Danke.

**Comment by htgoebel** [comment]
> pyinstaller --noconsole myscript.py
> Does nothing

I just do not belief this does nothing. If so, please check you setup.

> I get […] so many error messages its unbelievable.

I suggest trying to read the error messages and try to solve them.

I'm closing this ticket now due to the lack of useful information and due to lack of a real problem description.
