### ISSUE TITLE
Doc: pull request doc misleading somehow

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#3097]
I followed the instructions in https://github.com/pyinstaller/pyinstaller/blob/develop/doc/development/pull-requests.rst multiple times and the result is to erase my work.

* I forked PyInstaller ([here](https://github.com/tallforasmurf/pyinstaller))
* On my local system I did,

~~~
$ git clone git@github.com:tallforasmurf/pyinstaller.git
Cloning into 'pyinstaller'...
remote: Counting objects: 37814, done.
remote: Compressing objects: 100% (65/65), done.
remote: Total 37814 (delta 45), reused 41 (delta 21), pack-reused 37728
Receiving objects: 100% (37814/37814), 38.33 MiB | 131.00 KiB/s, done.
Resolving deltas: 100% (27546/27546), done.
$ cd pyinstaller
$  git remote add upstream https://github.com/pyinstaller/pyinstaller.git
$ git checkout -b fix_2039
Switched to a new branch 'fix_2039'
# now edited PyInstaller/utils/win32/icon.py in BBEdit and saved
$  git diff PyInstaller/utils/win32/icon.py 
# expected changes are there
$ git add PyInstaller/utils/win32/icon.py 
$ git commit -m 'utils/win32 fix #2039 by trapping any error opening the icon file and terminating with a message.'
[fix_2039 8650ad35] utils/win32 fix #2039 by trapping any error opening the icon file and terminating with a message.
 1 file changed, 14 insertions(+), 1 deletion(-)
$ git pull --rebase upstream develop # AS DIRECTED!!
From https://github.com/pyinstaller/pyinstaller
 * branch              develop    -> FETCH_HEAD
 * [new branch]        develop    -> upstream/develop
Current branch fix_2039 is up to date.
$ git push
Everything up-to-date
# everything is NOT up to date!!!!
$ git diff PyInstaller/utils/win32/icon.py
# no diff output
~~~

My changes are gone, the branch fix_2039 is gone, when I refresh the github page for my PyInstaller repo, there is no record of my commit.

Something is wrong with the instructions given, or possible they are not specific enough?

**Comment by xoviat** [comment]
I always checkout devel before starting work:

```
git fetch upstream
git checkout upstream/devel[op]
git checkout -b fix_2039
[maybe add/remove/edit files]
git commit -m 'message'
git push -u
```

**Comment by xoviat** [comment]
@tallforasmurf 

Please post `git remove -v` output.

**Comment by htgoebel** [comment]
@tallforasmurf Re. https://github.com/pyinstaller/pyinstaller/pull/3116#discussion_r157285818 Git does a lot to ensure you are *not* loosing your work or history.

First there is `git reflog`, which shows every change to the repo (commit, rebase, checkout, change of branch). Here you can find old commits which you thought are lost.

Second you can add (local) branches as much as you like at (almost) no cost. So you if you are going to do thing you are not confident about, create a branch and you are quickly able to go back there. As long as you are not pushing the branch (more precisely not creating a pull-request from it), it does not harm. Alternatively you would use tags and delete them later, although for me this seems a but weird.

And when there is `git gui`, which IMHO is a great tool for visualization and often also branch manipulation.

If you have anything we should add to the [the fine manual](https://github.com/pyinstaller/pyinstaller/blob/develop/doc/development/pull-requests.rst): Feel free. It's just that we should not create another git tutorial there :-) But you can refer to good ones.

**Comment by htgoebel** [comment]
Stale for long, I'm not expecting to get any documentation update :-). Closing
