### ISSUE TITLE
Problem with signing on MacOs

### ISSUE THREAD

**Issue by nigredo13** [pyinstaller/pyinstaller#3101]
Hi all,

I already bundled a couple of pygtk applications working on windows and now I am struggling with MacOs...

Gtk has some modules, images loaders, theme engines etc, that are dynamically loaded on demand with 
dlopen. It is possible to specify the path where they are located via environment variables in a rt_hook.

Now I'm facing two scenarios:

- if I collect them as binaries all works fine but then cannot sign the bundle because the "lib" folder 
under Contents/MacOS is a real folder, not a symlink.

- if collect as data signing works, but the application doesn't.

I tried, bundling as binaries, moving the directories to Resources and symlinking them on MacOS, again, 
signing works but the app not.

Since in the source of PyInstaller is stated that signing only works if there are not real folders under 
Contents/MacOS I'm wondering why they are bundled in a folder.

I don't know if this is a bug or if I am doing something wrong, any cue ?

Using: 
Python 2.7.10 and pygtk 2.24 from Homebrew
PyInstaller: 3.4.dev0+5f92e6d16

**Comment by robclewley** [comment]
Did you ever figure this out?

**Comment by nigredo13** [comment]
Yes,
with a hack...
I made a script like this:`

#!/bin/bash
cd dist/YourApp.app/Contents/Resources/lib
mkdir -p gtk-2.0/2.10.0
mkdir -p gdk-pixbuf-2.0/2.10.0
cd gtk-2.0/2.10.0
ln -sf ../../../../MacOS engines
ln -sf ../../../../MacOS immodules
cd ../../gdk-pixbuf-2.0/2.10.0
ln -sf ../../../../MacOS loaders`

**Comment by danyeaw** [comment]
@nigredo13 These steps should no longer be needed with the latest PyInstaller. Signing a Gtk app should work in macOS without manual moving and linking files. Can we close this?

**Comment by nigredo13** [comment]
Hi,
I know, it worked for a while, but it seems that on Catalina doesn't work anymore.
Now I cannot provide details, when back to work I'll post something.
