### ISSUE TITLE
Permanent location for one file?

### ISSUE THREAD

**Issue by beepboop123133131** [pyinstaller/pyinstaller#3120]
Is there a way to extract onefile into permanent folder (not temp every time) similar to: https://github.com/pyinstaller/pyinstaller/issues/1782.  This was asked 1 year ago so just wondering if anything has changed.

I have imports e.g import numpy.  This is a huge module so I rather not package that for each exe.  I could use one folder but this does not compress so that's like 80mb and also its quite messy and exe cannot leave that folder

**Comment by htgoebel** [comment]
#2221 should do this.

**Comment by beepboop123133131** [comment]
@htgoebel  I see.  For me that did not do anything.  I will investigate path --dir .
