### ISSUE TITLE
Pyinstaller onedir lump of files

### ISSUE THREAD

**Issue by jytinjalmon** [pyinstaller/pyinstaller#3129]
I see that this issue https://github.com/pyinstaller/pyinstaller/issues/1048  is not solved years later.
The issue is that the files look ugly as and not nice to look at take this image: https://i.stack.imgur.com/A7i9G.png for example.
Two possible fixes for: https://github.com/pyinstaller/pyinstaller/issues/1048

A) http://unafaltadecomprension.blogspot.com/2014/07/pyinstaller-separating-executable-from.html
This requires mucking around with spec file and can be dangerous where some imports do not work

B) Easier solution:

```
import os, shutil
import ctypes
folder = 'C:\\Users\\1441441'
for the_file in os.listdir(folder):
    file_path = os.path.join(folder, the_file)
    try:
        if os.path.isfile(file_path):
            ctypes.windll.kernel32.SetFileAttributesW(file_path, 2)
    except Exception as e:
        print(e)
```

This hides files in a folder cross platform.  Well, nearly.  For me it hides exe, all files, and not folders.  I'm struggling to get it to hide files, folders and not exe.  If this can be fixed, it is an easy workaround for this issue.

**Comment by htgoebel** [comment]
> I see that this issue #1048 is not solved years later.

Why are you opening a now ticket? Please comment there.
