### ISSUE TITLE
can not find C:\Users\Administrator.SKY-20170806ADG\AppData\Roaming\pyinstaller\bincache00_py36_32bit\api-ms-win-crt-runtime-l1-1-0.dll

### ISSUE THREAD

**Issue by fym0121** [pyinstaller/pyinstaller#3130]
can not find C:\Users\Administrator.SKY-20170806ADG\AppData\Roaming\pyinstaller\bincache00_py36_32bit\api-ms-win-crt-runtime-l1-1-0.dll

resolve: 
C:\Windows\System32>copy api-ms-win-crt-runtime-l1-1-0.dll C:\Users\Administrator.SKY-20170806ADG\AppData\Roaming\pyinstaller\bincache00_py36_32bit

**Comment by fym0121** [comment]
In addition: the system is less msvcr90.dll, so I downloaded one, solved it

**Comment by htgoebel** [comment]
1) What "can not find" this dll?  Please post more details.

2) You should not use PyInstaller as Administrator, as you should not develop or do you daily work as Administrator. This is extremely insecure!

**Comment by fym0121** [comment]
When I was packing the program, I was hinting thatcan not find …\bincache00_py36_32bit\api-ms-win-crt-runtime-l1-1-0.dll. I've been using the administrator account.
So I think if you pack the program, if you can't find a file in the bincache00_py36_32bit directory, go down to the system32 directory, so it won't be wrong.

**Comment by htgoebel** [comment]
The CRT for windows is a big mess, please read https://pyinstaller.readthedocs.io/en/stable/usage.html#windows for explanation. If you think PyInstaller should support option (3) mentioned there, please provide a pull-request.

And again: You should not work as Administrator!
