### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by mherrmann** [pyinstaller/pyinstaller#3149]
I just wanted to say thank you for this amazing project. It's helped me so much over the past two years. Before then, I tried all the alternatives (py2app, py2exe, cx_Freeze, bbfreeze, ...) and they suck in comparison. You are doing an amazing job @htgoebel (and others?) and I really appreciate your work. I also just paid an (admittedly very tiny) donation via BountySource. Thanks!

**Comment by htgoebel** [comment]
Thanks.
