### ISSUE TITLE
Big executable and VCRUNTIME140 error

### ISSUE THREAD

**Issue by luisiacc** [pyinstaller/pyinstaller#3150]
First i want to point out the great job you guys are doing. Thanks.
## 1
If i dont use the --noupx in the command line, when I run the exe it give me an error of VCRUNTIME140.dll, saying it is not for windows. Im now using this command and works perfect:
`pyinstaller -D -F -w -i icon.ico --noupx myscript.pyw`
That project imports PyQt5, requests and bs4
## 2
Ok, that works cool, but i want to know if it is normal to get a 24.9 mb size, could yo guys help me, if it can be done, to reduce that size, 
## 3
I also want to know if there is a way, with pyinstaller , to make an exe that doesnt bundle python, and that can be ran into a computer that only needs to have the Python interpreted installed on their machine.

**Comment by tallforasmurf** [comment]
1. So when UPX is used (not forbidden by --noupx) there is a problem with VCRUNTIME140. That DLL was just added in #2487. There appears to be some history to this. Please add information about exactly what Windows, Python, PyInstaller installations you are using.

2. 25MB is a typical size for a PyInstaller bundle of a PyQt app. On MacOS it will be bigger, probably.

3. That's a bad idea. One, for compactness, PyInstaller bundles compiled modules, and the bytecode is unique to the Python version that created it. If the receiver has a slightly different version they won't run. You can't be sure the receiver will have the right Python, and if not the app will crash with obscure messages and people will blame you.

Anyway, the Python support is not the largest portion of a PyQt app, I'm pretty sure.

**Comment by htgoebel** [comment]
@tallforasmurf Thanks for answering this :-)

**Comment by tallforasmurf** [comment]
he might have a real problem, if he gives more info. Or are you sure it's a #2487 dup?

**Comment by luisiacc** [comment]
Im using Windows10 [Versión 10.0.16299.15], pyinstaller 3.3.1 and Python 3.6.3 on Anaconda

**Comment by luisiacc** [comment]
oh I forgot, 64 bit .

**Comment by htgoebel** [comment]
If it works with `--noupx`, I'd say it's a victim of https://github.com/upx/upx/issues/107
