### ISSUE TITLE
windows PyInstaller-3.3.1.tar.gz -> win32/tiggre!plock

### ISSUE THREAD

**Issue by pavelek** [pyinstaller/pyinstaller#3157]
installing  / updating via pip or downloading from webpage pyinstaller v.3.3.1 rise virus windows devenfer alert (win32/tiggre!plock)

**Comment by grajsor** [comment]
Hello.

Please contact the AV-vendor and let them know this is a false alert and
have them fix it.

Thank you.

**Comment by attibalazs** [comment]
i am experiencing the same issue, but only in my python 2.7 conda environment. It works in the base python 3.6 environment. When i try to extract the local\temp\PyInstaller-3.3.1.tar.gz i get a warning from Windows Defender it thinks the archive has a Trojan (win32/tiggre!plock)

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by mherrmann** [comment]
Just another data point: I am experiencing this problem as well after updating from PyInstaller 3.3 to 3.4. I'm using Python 3.5. I wrote a [blog post](https://fman.io/blog/fman-144-and-windows-defender/) about the issue. I submitted my app to Windows Defender as a false positive, via their [online form](https://www.microsoft.com/en-us/wdsi/filesubmission). Hopefully this will help.
