### ISSUE TITLE
pyinstaller pick wrong binaries on circle-ci

### ISSUE THREAD

**Issue by tardyp** [pyinstaller/pyinstaller#3162]
circle-ci uses python virtualenvs with python compiled without shared libraries, which they store in /opt/circle/python

when using python2.7, pyinstaller succeeds, but generates a binary that fails to load hmac module.
in my case, the error was:

    from operator import _compare_digest as compare_digest

which is supposed to load the _operator.so library.

When using python3.6, pyinstaller fails, suggesting the dynamic libraries cannot be found.

I guess that on py2.7, pyinstaller is finding system binaries (but I am not sure)

Now I am using the system python, and things work well. I wanted to share the solution which works for me:

```
    - sudo apt-get update; sudo apt-get install libenchant-dev python3-dev
    - virtualenv -p /usr/bin/python3.4 .venv/
    - .venv/bin/pip install twisted[tls] -e worker pyinstaller
    - .venv/bin/pyinstaller -F pyinstaller/buildbot-worker.spec

```

**Comment by htgoebel** [comment]
PyInstaller always uses the Python installation it is running with. And PyInstaller includes quite some code to detect the resp. installation, even in virtual envs of different kinds).

Unfortunately you only shred your "guess", but neither how you did install and run PyInstaller, not any proof for your guess. Thus please provide more details and not just "guesses". Thanks.

**Comment by tardyp** [comment]
Thanks for answering. I will setup an example project so that you can easily reproduce

**Comment by tardyp** [comment]
See the example:

https://github.com/tardyp/pyinstaller_circle

with failing build:
https://circleci.com/gh/tardyp/pyinstaller_circle/1

The artifacts of the builds are here:
https://circleci.com/gh/tardyp/pyinstaller_circle/1#artifacts/containers/0

The test fails for both onefile and onedir mode.

```
./dist/hmac_test/hmac_test
Traceback (most recent call last):
  File "hmac_test.py", line 1, in <module>
    import hmac
  File "/tmp/pip-build-aDICPF/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "hmac.py", line 8, in <module>
ImportError: cannot import name _compare_digest
[14867] Failed to execute script hmac_test

./dist/hmac_test/hmac_test returned exit code 255
```

**Comment by htgoebel** [comment]
Thanks for this small example.

File "hmac.py", line 8 says:
```
from operator import _compare_digest as compare_digest
```
which means, that for some reason the `operator` module gets overwritten or mixed up.

This also means that the error should also occur if you are changing your example to only this line.

Please check
a) if there is another module "operator" in `build/hmac_test/out00-PYZ.pyz` (archive-viewer is your friend)
b) for some hint regarding "operator" in `build/hmac_test/xref-hmac_test.html`
c) if the included `operator.so` is the one belonging to the Python version used.

**Comment by tardyp** [comment]
@htgoebel The thing is there is no operator.so belonging to the Python version used. (need to check if that operator.so is the one of the distro)
That version of python that circleci is shipping is without dynamic libraries (only libpython.a is found).

**Comment by htgoebel** [comment]
> That version of python that circleci is shipping is without dynamic libraries (only libpython.a is found).

So this is the solution. PyInstaller does not support statically linked python.

**Comment by tardyp** [comment]
> So this is the solution. PyInstaller does not support statically linked python.

I understand pyinstaller does not support statically linked python, but IMHO it should at least detect it, and report an error instead of taking the wrong binaries in the system.

**Comment by htgoebel** [comment]
Agreed, although this might not be easy and there seem to be different levels of "statically". Any idea how to do this? Volunteering for a pull-request? :-)
