### ISSUE TITLE
Fatal error in launcher: Unable to create process using '"'

### ISSUE THREAD

**Issue by eputin2** [pyinstaller/pyinstaller#3163]
Whenever running the command Pyinstaller from the command prompt, the following is returned:
_Fatal error in the launcher: Unable to create process using '"'_

The same issue applies with pip. This issue hasn't bothered me before, but now it happens whenever I use Pip normally (pip install x). 

Any help is appreciated. 
Many thanks.

**Comment by htgoebel** [comment]
> it happens whenever I use Pip normally (pip install x)

Obviously this is not a PyInstaller issue.

**Comment by alsonh** [comment]
Came across the same issue today...uninstalled Pyinstaller and then reinstalled it and it started working again. Strange...

**Comment by cddxcdx** [comment]
@alsonh Strange... Reinstalling PyInstaller solved this issue...

**Comment by instantname** [comment]
I saw that behaviour with Anaconda 3 when:

- installing pyinstaller in an environment A
- cloning env A to env B
- try using pyinstaller in env B

**Comment by instantname** [comment]
Still on the cloning test, I found [here](https://github.com/conda/conda/issues/3097#issuecomment-314244115) that the problem can be tracked to an absolute path in the pyinstaller executable that is not updated when cloning. Unless there is a good reason to have an absolute path, I think this is a pyinstaller issue.

**Comment by evertonstz** [comment]
Was anyone able to solve this?

**Comment by TorchofFire** [comment]
I am having the same issue except I reinstalled python, pip, and pyinstaller and pyinstaller is the only thing that refuses to work. Reinstalling didn't help me.

**Comment by newlinuxhelper** [comment]
> Whenever running the command Pyinstaller from the command prompt, the following is returned:
> _Fatal error in the launcher: Unable to create process using '"'_
> 
> The same issue applies with pip. This issue hasn't bothered me before, but now it happens whenever I use Pip normally (pip install x).
> 
> Any help is appreciated.
> Many thanks.

I think this would be a perfect solution for this issues of [Unable to create process using in venv](https://webmatrices.com/d/503-unable-to-create-process-using-virtualenv)
