### ISSUE TITLE
Application console does not appear

### ISSUE THREAD

**Issue by johnroper100** [pyinstaller/pyinstaller#3171]
i have written a script that I want to use pyinstaller to package into a onefile application. It works, however, the console does not show up when the application is started. My full configuration can be found here: https://github.com/johnroper100/Tonalite/blob/master/tonalite.spec

**Comment by tallforasmurf** [comment]
OS platform and version?

**Comment by johnroper100** [comment]
Latest pyinstaller, both windows 10 and Linux

**Comment by htgoebel** [comment]
> the console does not show up when the application is started

Hm, I have to admit that [the manual](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#using-a-console-window) leaves the impression, the application would open a console window. But this might not be true.

- For GNU/Linux and other Unix-flavors there is only one bootloader, thus `console` does not have any effect. To the best of my knowledge, no X11 desktop (KDE, Gnome, etc.) will inspect the executable to determine if it should open console window for the application. You can use `Terminal=true` and `TerminalOptions=\s--noclose` in the `.desktop` file.
- For OS X I can't tell.
- For Windows I have seen application opening up a console window automatically, and this is why PyInstaller has the `console` parameter. The console window is opened by Windows, not by the application.
  - AFAIK this console is only opened, if you run the executable via the window system. If you run the executable from some console window (e.b. powershell or cmd), this does not happen. Which way did you use?
  - Please try if it works for you when using PyInstaller 3.3, as we changed some compilation options for 3.3.1 which *might* effect this behavior.

**Comment by johnroper100** [comment]
I ran from the window system. This application is a headless server, so without the console there is not way to stop it without stopping the computer or going into the system processes. This application is supposed to be distributed to multiple artists who do not have the technical know-how to edit the .desktop file.

**Comment by htgoebel** [comment]
You are revering to GNU/Linux, I assume. So *you* need to provide the .desktop-file. Or add some GUI to start and stop the application.

And what is about Windows?

**Comment by johnroper100** [comment]
Oh, I thought a .desktop file was config for the windows manager. I will be able to provide it myself.

**Comment by Kerang** [comment]
This seems odd to me as I have a console only game that seems to run fine. I assume, you don't require any user input. Perhaps include a input('Press any key to quit') kind of statement, and have the program terminate when someone presses a button?

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved. Otherwise please try PyInstaller v3.4 and the current development version.

**Comment by dexman545** [comment]
Using PyInstaller 3.4, I also have this issue.
in my scripts I have several input("your input here"), yet after building and trying to run in windows via double-clicking the application, it fails to run. The console opens for fraction of a second, and then closes. Tried with --console option when building, and without
