### ISSUE TITLE
AttributeError: LooseVersion instance has no attribute 'version'

### ISSUE THREAD

**Issue by vishnusuman** [pyinstaller/pyinstaller#3172]
I'm working on a python program which reads parquet type file and converts it in to pandas dataframe. It works fine while i use the python command to run it (python framework1.py arg1 arg2). But after converting it to an executable file using pyinstaller and when the executable file is ran , it gives the following error.
```
Traceback (most recent call last):
  File "framework1.py", line 325, in <module>
  File "filetype.py", line 24, in fileTypeSelector
  File "pandas/io/parquet.py", line 256, in read_parquet
  File "pandas/io/parquet.py", line 38, in get_engine
  File "pandas/io/parquet.py", line 89, in __init__
  File "distutils/version.py", line 296, in __cmp__
AttributeError: LooseVersion instance has no attribute 'version'
[17249] Failed to execute script framework1
```

Can anyone please help me resolve the issue

**Comment by htgoebel** [comment]
The question is: *why* does the LooseVersion instance not have an attribute 'version'? When looking at the code of `distutils.version.LooseVersion` you can see that this `version` attribute is always set, except if there was no version passed when instantiating the object.

I assume, `pandas.io.parquet.get_engine()` tries to read some meta-data-file which is missing. Please have a look at the code of this function (and `read_parquet`, and `__init__`) to figure this out. https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly has some hints for finding out which file is missing.

**Comment by vishnusuman** [comment]
So my issue was solved by using fastparquet engine instead of pyarrow.

df1=pd.read_parquet(filepath,engine='fastparquet')
