### ISSUE TITLE
there are two processes while running the exe generated by pyinstaller with -F

### ISSUE THREAD

**Issue by xuezhipeng-12sigma** [pyinstaller/pyinstaller#3173]
OS:  win10
version: 3.3.1+8ea39be13

I found kinds of solutions about multiprocess program, but all of them didn't work for me.
my script is very simple, just for test, like this(test.py):
```
# -*- coding=utf8 -*-

if __name__ == "__main__":
    while True:
        c = 4
```
then I execute the command "pyinstaller -F test.py"
then I run the exe and I can see two processes in windows task manager.
and if the command changes to "pyinstaller test.py", there is only one process found.
I tried the solutions in [https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing](url) but it didn't work.
I have uploaded the log for executing  "pyinstaller -F test.py"
[out.txt](https://github.com/pyinstaller/pyinstaller/files/1599944/out.txt)

I think it's a bug to be fixed.
Thank you very much for your help and suggestion!

**Comment by htgoebel** [comment]
If I understand this correctly, you are worrying about there are two processes running. This is the exacted behavior, see https://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#the-bootstrap-process-in-detail.

**Comment by htgoebel** [comment]
Nevertheless: Thanks for sharing :-)
