### ISSUE TITLE
Executable crashes

### ISSUE THREAD

**Issue by David94Atlas** [pyinstaller/pyinstaller#3174]
### What is the exact problem?
The error occurs when running it.
[PowerShellOutput.txt](https://github.com/pyinstaller/pyinstaller/files/1599946/PowerShellOutput.txt)

### Software versions I'm using
**pyInstaller version:** 3.4.dev0+ab8fd9753
**Python version:** 3.7.0a2 (v3.7.0a2:f7ac4fe, Oct 17 2017, 17:06:29) [MSC v.1900 64 bit (AMD64)]

### What platform and which version I'm working on
**Windows version:** Windows 10 Pro (64-bit)

### Minimal example program which shows the error
    # test.py
    print("Hello World!")

### Did I try implementing a hook or run-time-hook (rthook) to solve the problem?
No.

### Any other information
The command
`pyinstaller test.py --onedir --log-level DEBUG > out.txt`
did result in an empty out.txt file.

PyInstaller did create a standalone test.exe, but when I tried to execute it, the console window opened, empty, and was followed by the Windows message that the program test.exe has stopped working.
Executing the test.exe with PowerShell resulted in the same situation, except that the PowerShell console keeps open and outputs the following: [PowerShellOutput.txt](https://github.com/pyinstaller/pyinstaller/files/1599946/PowerShellOutput.txt)

**Comment by htgoebel** [comment]
Python 3.7. is not yet supported. If you want to work on it, please submit a pull-request. Thanks.
