### ISSUE TITLE
VPython and Pyinstaller 

### ISSUE THREAD

**Issue by mohamed-tayeh** [pyinstaller/pyinstaller#3187]
Hi!
i am creating a projectile motion simulation using VPython and Tkinter. 
Is VPython compatible with pyinstaller?
I wanted to make sure, because on the list of compatible packages it says incomplete.

**Comment by Kerang** [comment]
Did you try looking on google and running a test? [how to make vpython exe using pyinstaller](https://stackoverflow.com/questions/39818847/how-to-make-vpython-exe-using-pyinstaller)

**Comment by momo6aye3** [comment]
It was me who asked the stackoverflow question. It didn't work.

**Comment by H-Richard** [comment]
have u tried turning it off and turning it back on?
