### ISSUE TITLE
pyinstaller scipy

### ISSUE THREAD

**Issue by masoudr** [pyinstaller/pyinstaller#3197]
Hi,
I want to freeze a script. Script  has `face_recognition` module which has `scipy` built in. But when I run the executable I see this error:

> Traceback (most recent call last):                                                                                        File "web_service_fin.py", line 19, in <module>                                                                         File "c:\users\masoud\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module                                                                                                exec(bytecode, module.__dict__)                                                                                       File "site-packages\face_recognition\__init__.py", line 7, in <module>                                                  File "c:\users\masoud\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module                                                                                                exec(bytecode, module.__dict__)                                                                                       File "site-packages\face_recognition\api.py", line 3, in <module>                                                       File "c:\users\masoud\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module                                                                                                exec(bytecode, module.__dict__)                                                                                       File "site-packages\scipy\misc\__init__.py", line 67, in <module>                                                       File "c:\users\masoud\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module                                                                                                exec(bytecode, module.__dict__)                                                                                       File "site-packages\scipy\interpolate\__init__.py", line 175, in <module>                                               File "c:\users\masoud\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module                                                                                                exec(bytecode, module.__dict__)                                                                                       File "site-packages\scipy\interpolate\interpolate.py", line 21, in <module>                                             File "c:\users\masoud\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module                                                                                                exec(bytecode, module.__dict__)                                                                                       File "site-packages\scipy\special\__init__.py", line 640, in <module>                                                   File "c:\users\masoud\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module                                                                                                module = loader.load_module(fullname)                                                                                 File "_ufuncs.pyx", line 1, in init scipy.special._ufuncs                                                               File "c:\users\masoud\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module                                                                                                module = loader.load_module(fullname)                                                                               ImportError: DLL load failed: The parameter is incorrect.                                                               [1560] Failed to execute script web_service_fin  

and here is my config file:

```
# -*- mode: python -*-

block_cipher = None



a = Analysis(['C:\\Users\\Masoud\\Desktop\\Fin v5.2 documented\\web_service_fin.py'],
             pathex=['C:\\Users\\Masoud\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages\\scipy\\extra-dll', 'C:\\Users\\Masoud\\Desktop\\Fin v5.2 documented'],
             binaries=[],
             datas=[('C:\\Users\\Masoud\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages\\scipy\\special\\_ufuncs_cxx.cp36-win_amd64.pyd','.'),],
             hiddenimports=['scipy._lib.messagestream',
                            'scipy.special._ufuncs',
                            'scipy.special._ufuncs_cxx',
                            'scipy.linalg.cython_blas',
                            'scipy.linalg.cython_lapack',
                            'scipy.integrate',
                            'scipy.integrate.quadrature',
                            'scipy.integrate.odepack',
                            'scipy.integrate._odepack',
                            'scipy.integrate.quadpack',
                            'scipy.integrate._quadpack',
                            'scipy.integrate._ode',
                            'scipy.integrate.vode',
                            'scipy.integrate._dop',
                            'scipy.integrate.lsoda',
                            #'scipy._lib.messagestream', 'scipy', 'fixtk', 'scipy.signal', 'scipy.signal.bsplines', 'scipy.special', 'scipy.special._ufuncs', 'scipy.special._ufuncs_cxx',
                            #'scipy.linalg.cython_blas',
                            #'scipy.linalg.cython_lapack',
                            #'scipy.integrate',
                            #'scipy.integrate.quadrature',
                            #'scipy.integrate.odepack',
                            #'scipy.integrate._odepack',
                            #'scipy.integrate.quadpack',
                            #'scipy.integrate._quadpack',
                            #'scipy.integrate._ode',
                            #'scipy.integrate.vode',
                            #'scipy.integrate._dop', 'scipy._lib', 'scipy._build_utils','scipy.__config__',
                            #'scipy.integrate.lsoda', 'scipy.cluster', 'scipy.constants','scipy.fftpack','scipy.interpolate','scipy.io','scipy.linalg','scipy.misc','scipy.ndimage','scipy.odr','scipy.optimize','scipy.setup','scipy.sparse','scipy.spatial','scipy.special','scipy.stats','scipy.version'
                            ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='web_service_fin',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )

```

**Comment by htgoebel** [comment]
Please provide a **minimal** example and a **readable** traceback. Thanks.

**Comment by htgoebel** [comment]
I'm closing this now. Since the author did not care about posting the requested information, why should I care?

**Comment by masoudr** [comment]
Hi,
I forgot this issue. I solved it by just editing the spec file and manually add `scipy` as `hidden imports`. here is my spec file:
```
# -*- mode: python -*-

block_cipher = None

face_models = [
('.\\face_recognition_models\\models\\dlib_face_recognition_resnet_model_v1.dat', './face_recognition_models/models'),
('.\\face_recognition_models\\models\\mmod_human_face_detector.dat', './face_recognition_models/models'),
('.\\face_recognition_models\\models\\shape_predictor_5_face_landmarks.dat', './face_recognition_models/models'),
('.\\face_recognition_models\\models\\shape_predictor_68_face_landmarks.dat', './face_recognition_models/models'),
]

a = Analysis(['<your python script name.py>'],
             pathex=['<path to working directory>'],
             binaries=face_models,
             datas=[],
             hiddenimports=['scipy._lib.messagestream', 'scipy', 'scipy.signal', 'scipy.signal.bsplines', 'scipy.special', 'scipy.special._ufuncs_cxx',
                            'scipy.linalg.cython_blas',
                            'scipy.linalg.cython_lapack',
                            'scipy.integrate',
                            'scipy.integrate.quadrature',
                            'scipy.integrate.odepack',
                            'scipy.integrate._odepack',
                            'scipy.integrate.quadpack',
                            'scipy.integrate._quadpack',
                            'scipy.integrate._ode',
                            'scipy.integrate.vode',
                            'scipy.integrate._dop', 'scipy._lib', 'scipy._build_utils','scipy.__config__',
                            'scipy.integrate.lsoda', 'scipy.cluster', 'scipy.constants','scipy.fftpack','scipy.interpolate','scipy.io','scipy.linalg','scipy.misc','scipy.ndimage','scipy.odr','scipy.optimize','scipy.setup','scipy.sparse','scipy.spatial','scipy.special','scipy.stats','scipy.version'],

             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)

a.datas += Tree('./scipy-extra-dll', prefix=None)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='<your python script name>',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )

```

**Comment by htgoebel** [comment]
Good to know. We would appreciate if you'd submit a pull-request for a hook for this, thus others will not get into this issue.

See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.
