### ISSUE TITLE
Pythoncom keys not found

### ISSUE THREAD

**Issue by JReuling** [pyinstaller/pyinstaller#3206]
Hello,
I'm having an issue with packaging pythoncom using pyinstaller 3.3.1. on Windows 10 (no anaconda environment or something similar).  At first I had issues as mentioned in #1803 so I tried the workarounds mentioned. They work fine for os and pywintypes (or at least appear to) but when I set pythoncom to `None` the following stacktrace prints (starting from OpenOPC):

File "site-packages\win32com\client\gencache.py", line 544, in EnsureDispatch
File "site-packages\win32com\client\CLSIDToClass.py", line 46, in GetClass
KeyError: '{F8582D25-88FB-11D0-B850-00C0F0104305}'
[17328] Failed to execute script runner

Would you have an idea how to fix this? I couldn't find another issue like this but if I missed that just pointing me at it would already be greatly appreciated.

**Comment by htgoebel** [comment]
I assume `CLSIDToClass` should match `{F8582D25-88FB-11D0-B850-00C0F0104305}` into some "class". So you need too find out, what this class is and why it can't be found. One of the tracking tools listed in [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) might be of help in case some file is missing.

Did you try pywin32 from pypi?

**Comment by JReuling** [comment]
I did not know pywin32 was available on pypi, switching to that (and deleting the previous installation) did not help unfortunately. The classs seems to be a generated OPC DA file. If I remove the `sys.modules['win32com.gen_py.pythoncom'] = None`  it will resolve but the generated file refers to properties that do not exist in pythoncom (pythoncom.Missing ironically).

**Comment by Legorooj** [comment]
Stale
