### ISSUE TITLE
In windows Pyinstaller can not find pywin32 in Conda's python3.5 environment

### ISSUE THREAD

**Issue by jxltom** [pyinstaller/pyinstaller#3213]
Installing pyinstaller will install pypiwin32 automatically. But in conda's python35 environment, pyinstaller can not start and it will raise ```PyInstaller cannot check for assembly dependencies. Please install PyWin32 or pywin32-ctypes. pip install pypiwin32``` error. But if I try to install pypiwin32 by ```pip install pypiwin32```, ```Requirement already satisfied``` will return which means it is already installed.

If I change Conda's environment to python34, everything is fine.

I am using ```conda 4.3.31``` with fresh Python35 environment created by ```conda create --name py35 python=3.5```. Operation system is Windows 7 Enterprise.

**Comment by htgoebel** [comment]
You need to install PyInsaller into the environment you are using. HTH.

**Comment by jxltom** [comment]
@htgoebel Thanks for the reply. I didn't explain the issue clearly.

I **did create** a conda environment and **install pyinstaller inside it**. But for Python35 environment, installing pyinstaller does not work and ```PyInstaller cannot check for assembly dependencies. Please install PyWin32 or pywin32-ctypes. pip install pypiwin32``` error will be raised even though pyinstaller will install pywin32 automatically.

But if I create a python34 env, installing pyinstalling works fine.

So this issue may related to Conda's python35 env in Windows.

**Comment by rth** [comment]
I can confirm. This is unrelated to conda, the printed error message in,

https://github.com/pyinstaller/pyinstaller/blob/07ab024c395619e7a220628f99173ca64e044d88/PyInstaller/compat.py#L207-L217

is inaccurate. pypiwin32 will not allow to import `win32ctypes`, the solution is install pywin32-ctypes,
```
pip install pywin32-ctypes
```

It looks like this was changed in https://github.com/pyinstaller/pyinstaller/commit/085cd85c493dd7d8387cda2c92528e0444c8d767 but the error message wasn't updated...
