### ISSUE TITLE
[9820] Failed to execute script GUI

### ISSUE THREAD

**Issue by limitforever** [pyinstaller/pyinstaller#3235]
Could you tell me why this problem occured?
Traceback (most recent call last):
  File "GUI.py", line 7, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\misc\__init__.py", line 67, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\interpolate\__init__.py", line 175, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\interpolate\interpolate.py", line 20, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\linalg\__init__.py", line 186, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\linalg\misc.py", line 5, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\linalg\blas.py", line 196, in <module>
  File "c:\program files\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: DLL load failed: 找不到指定的模块。
[9820] Failed to execute script GUI

**Comment by htgoebel** [comment]
1) Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

The tracebck looks like the `linalg.blas` package has some problem, thus is the minimal example might only import some `linalg.blas`.

2) Also please translate the the chinese(?) error message.

3) This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by smileboywtu** [comment]
the chinese means can't find the module

**Comment by limitforever** [comment]
@htgoebel 
You mean I should import all the extension modules in the scipy\misc,scipy\linalg,scipy\interpolate?

Well,since I used the command "pyinstaller -D /../GUI.py", I could find the extension modules
in the dist folder,such as 
scipy.linalg._decomp_update.pyd;    scipy.linalg._fblas.pyd;   scipy.linalg._flapack.pyd;
scipy.linalg._flinalg.pyd;     scipy.linalg._solve_toeplitz.pyd;   scipy.linalg.cython_blas.pyd;
scipy.linalg.cython_lapack.pyd
and I have checked the site -packages "scipy/linalg",all its  extension modules have been imported.

**Comment by limitforever** [comment]
@htgoebel Yes ,the chinese means can't find the module @smileboywtu thanks for translating.

**Comment by limitforever** [comment]
@smileboywtu Have you solved your problems? My pyinstaller and python's version are the same as yours.   I did install the apscheduler,and added two python files,the one is CronTrigger.py,and the other is hook-ctypes.macholib.py.
But the problems still remains.

**Comment by smileboywtu** [comment]
@limitforever I have try, but i have found that `cython_blas.cp36-win_amd64.pyd` have not been added, i think this is the truely binary module.

**Comment by smileboywtu** [comment]
```
import numpy as np
from PIL import Image
from skimage import morphology
def auto_find_crop_area(source_file):
    """
    1. convert to gray picture
    2. find pixel > 200 (white) and connect
    3. if > image/4 
    4. find edge of question and answer
    
    :param source_file:
    :return: 
    """
    image = Image.open(source_file)
    width, height = image.size[0], image.size[1]
    array_img = np.array(image)
    ot_img = (array_img > 200)
    obj_dtec_img = morphology.remove_small_objects(ot_img, min_size=width * height / 4, connectivity=1)
    if np.sum(obj_dtec_img) < 1000:
        return []
    return [
        np.where(obj_dtec_img * 1.0 > 0)[1].min() + 20,
        np.where(obj_dtec_img * 1.0 > 0)[0].min(),
        np.where(obj_dtec_img * 1.0 > 0)[1].max(),
        np.where(obj_dtec_img * 1.0 > 0)[0].max()]
```

**Comment by smileboywtu** [comment]
i provide my minimal function here, hope someone will help me

**Comment by smileboywtu** [comment]
truely problem:

``` shell

46658 WARNING: lib not found: libspecfun.PT6DS3HUOGYNSXUO4OUKK6ATA7B5KP2K.gfortran-win_amd64.dll dependency of c:\python36\lib\site-packages\scipy\special\specfun.cp36-win_amd64.pyd
47130 WARNING: lib not found: libdgamln.HCGQFIEXCOZOROCO5Y4HSBVSKT76OCHM.gfortran-win_amd64.dll dependency of c:\python36\lib\site-packages\scipy\special\_ufuncs.cp36-win_amd64.pyd
```

**Comment by smileboywtu** [comment]
please follow this to resolve problem, but you will get other problem soon, then add import to hidden import.

`https://stackoverflow.com/questions/47065295/pyinstaller-with-scipy-signal-importerror-dll-load-failed`

**Comment by htgoebel** [comment]
@smileboywtu https://github.com/pyinstaller/pyinstaller/issues/3235#issuecomment-359826361 is still to big. Does PIL contribute to the error? Does skimiage contribute to the error? What is this function, which never gets called? Which statement is raising the error?

If you have a solution, please post it here (instead of stackunderflow) or even better: provide a pull-request.

Also for all tests, please [install the develepment version of pyinstaller](https://pyinstaller.readthedocs.io/en/latest/installation.html].

**Comment by limitforever** [comment]
I have solved my problem!
The issue was lots of missing dlls!!! PyInstaller has issues finding most of Scipy's dlls, so I had to specify a heck of a lot of them. I'll post my .spec file below in case anyone else wants to see / copy which dlls I had to bring in. Some things might not have been necessary, but it works so I'm not going to mess with it. Make sure that you are pointing to the correct directory for your system though - it won't be the same as mine, so don't just copy/paste :) 
mkl_dlls = [('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\lib_arpack-.E27K2SF75AFV2JAJA2UCDNNFYUB5PRKN.gfortran-win_amd64.dll','.'),
            ('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\lib_blas_su.SU77LBR3GCSGWOMPF2EOOUNRTVGOH5QW.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\lib_test_fo.JF5HTWMUPBXWGAYEBVEJU3OZAHTSVKCT.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libansari.R6EA3HQP5KZ6TAXU4Y4ZVTRPT7UVA53Z.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libbanded5x.GRJEXVLV2RZBSTTPFWQOQINCAR6VPZCI.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libbispeu.5N2XSD7URZS4WTOSLTOG4DDMA4HGB46U.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libblkdta00.G3LQYBY5GAOR5JJGRXYUWYKKDP4OKP2G.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libchkder.6HLXPVTQJEGRZGLI5DFRMNW3SS76BHP6.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libcobyla2.JEGTSUUFJ7DFXWZN5PAYZTTLBDATC4WD.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libd_odr.RVVJB6VEKU75HMLZ5VWMHFXDESN2K6A7.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdcosqb.K4J3XBR4PEETMRHZICUWW4LXG5UONZ34.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdcosqb.QRGA36MB6CFHWLQN6ETWARR4M4E6P3C2.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdcsrch.I2AOPDCXAPDRFNPWY55H5UE7XZSU5CVN.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdet.CF6EYFUDEYPH43I3Z6PMABQVSHN33WMB.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdfft_sub.L7RK2BXXS6VZ7XREQ326OSAIHHPLPCMK.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdfitpack.KTCF3EOE66VRDKN45KBQA4VBAIS552IF.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdgamln.HCGQFIEXCOZOROCO5Y4HSBVSKT76OCHM.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdop853.6TJTQZW3I3Q3QIDQHEOBEZKJ3NYRXI4B.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libdqag.XYDTZMPTRTODHGZ2AIXJLHZ6K7SZTGO7.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\liblbfgsb.OPNUZO4Z277J7J477DF55KBT2666RE7H.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libmvndst.FJYIV5KRHEB6IA4GIU6HFBYCEDXO3WN4.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libnnls.5LTQOLAJY5PFO6MOEXWNMRWVFRWHYHKT.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libslsqp_op.NNY57ZXZ43A4RH3YWFA7BKHP5PC2K3I5.gfortran-win_amd64.dll	','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libspecfun.PT6DS3HUOGYNSXUO4OUKK6ATA7B5KP2K.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libSTOPTEST.B2ZVH7DO5DVZYDS75ZSCHXD5G43HCYD4.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libvode.EZHESKPEGK6QRJZO64W6EHM63B4RVTTZ.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libwrap_dum.26QQ3L55FU6KXMGPYDA53KYMCT2TU35H.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\libwrap_dum.JPPGMGH3MZCSHXFMQQGFOSCGZ7ZEQKKE.gfortran-win_amd64.dll','.'),
			('G:\CV2\Python36\Lib\site-packages\scipy\extra-dll\msvcp140.dll','.')]
Besides,I have added some neccesary hiddenimports and data to my spec file.
       datas=[‘skimage.io._plugins’],
       hiddenimports=['scipy'，‘skimage.io._plugins’],

**Comment by htgoebel** [comment]
> The issue was lots of missing dlls!!! PyInstaller has issues finding most of Scipy's dlls, so I had to specify a heck of a lot of them.

PyInstaller should be able to find teh dlls automatically. Please help improving PyInstaller and find out
- which modules *exactly* require the hidden imports you added
- why does PyInstaller not find these automatically.
- why does PyInstaller not find the DLLs? Is it because of the hashes included in the filename? (The tools listed in [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) should help you inspecting this,

**Comment by smileboywtu** [comment]
the problem finally solved, if pyinstaller do not correct it , i will give it a try soon and pr

**Comment by FossenWang** [comment]
@limitforever [(comment on 24 Jan)](https://github.com/pyinstaller/pyinstaller/issues/3235#issuecomment-360054183)
I had the same problem which was finally solved.
PyInstaller didn't find all required sicpy's dlls.
And i don't write all the verbose paths of dlls in .sepc file.
I just copy all the dlls in "extra-dll" file folder, which maybe  in :
\path\to\Python36\Lib\site-packages\scipy\extra-dll\
then put them into /disc/name/.

**Comment by bhagyashripachkor** [comment]
@limitforever I too got the same missing scipy dll's while building exe file. I have used PyInstallerGUI to build exe file. As suggested by you, I added the dll's path in.spec file as pasted below. 
spec file:-
# -*- mode: python -*-

block_cipher = None

a = Analysis(['C:/Users/bpachkor/Desktop/prog-2/app-3-adv.py'],
             pathex=['C:\\Users\\bpachkor\\Desktop\\PyInstallerGUI-1.0.0.2'],
             binaries=[],
             datas=[],
	     mkl_dlls = [(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\lib_arpack-.E27K2SF75AFV2JAJA2UCDNNFYUB5PRKN.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\lib_blas_su.SU77LBR3GCSGWOMPF2EOOUNRTVGOH5QW.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\lib_test_fo.JF5HTWMUPBXWGAYEBVEJU3OZAHTSVKCT.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libansari.R6EA3HQP5KZ6TAXU4Y4ZVTRPT7UVA53Z.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libbanded5x.GRJEXVLV2RZBSTTPFWQOQINCAR6VPZCI.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libbispeu.5N2XSD7URZS4WTOSLTOG4DDMA4HGB46U.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libblkdta00.G3LQYBY5GAOR5JJGRXYUWYKKDP4OKP2G.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libchkder.6HLXPVTQJEGRZGLI5DFRMNW3SS76BHP6.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libcobyla2.JEGTSUUFJ7DFXWZN5PAYZTTLBDATC4WD.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libd_odr.RVVJB6VEKU75HMLZ5VWMHFXDESN2K6A7.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdcosqb.K4J3XBR4PEETMRHZICUWW4LXG5UONZ34.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdcosqb.QRGA36MB6CFHWLQN6ETWARR4M4E6P3C2.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdcsrch.I2AOPDCXAPDRFNPWY55H5UE7XZSU5CVN.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdet.CF6EYFUDEYPH43I3Z6PMABQVSHN33WMB.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdfft_sub.L7RK2BXXS6VZ7XREQ326OSAIHHPLPCMK.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdfitpack.KTCF3EOE66VRDKN45KBQA4VBAIS552IF.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdgamln.HCGQFIEXCOZOROCO5Y4HSBVSKT76OCHM.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdop853.6TJTQZW3I3Q3QIDQHEOBEZKJ3NYRXI4B.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libdqag.XYDTZMPTRTODHGZ2AIXJLHZ6K7SZTGO7.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\liblbfgsb.OPNUZO4Z277J7J477DF55KBT2666RE7H.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libmvndst.FJYIV5KRHEB6IA4GIU6HFBYCEDXO3WN4.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libnnls.5LTQOLAJY5PFO6MOEXWNMRWVFRWHYHKT.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libopenblas.BNVRK7633HSX7YVO2TADGR4A5KEKXJAW.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libslsqp_op.NNY57ZXZ43A4RH3YWFA7BKHP5PC2K3I5.gfortran-win_amd64.dll	','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libspecfun.PT6DS3HUOGYNSXUO4OUKK6ATA7B5KP2K.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libSTOPTEST.B2ZVH7DO5DVZYDS75ZSCHXD5G43HCYD4.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libvode.EZHESKPEGK6QRJZO64W6EHM63B4RVTTZ.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libwrap_dum.26QQ3L55FU6KXMGPYDA53KYMCT2TU35H.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\libwrap_dum.JPPGMGH3MZCSHXFMQQGFOSCGZ7ZEQKKE.gfortran-win_amd64.dll','.'),
(C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\Lib\site-packages\scipy\extra-dll\msvcp140.dll','.')],
             hiddenimports=['scipy'],
             hookspath=[],
	     runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
	  a.mkl_dlls,
          name='app-3-adv',
          debug=False,
          strip=False,
          upx=False,
          runtime_tmpdir=None,
          console=True )

After making changes to spec file i just saved it and tried opening the already built exe file and got below errors:-

Traceback (most recent call last):
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 715, in load_module
    module = loader.load_module(fullname)
  File "<frozen importlib._bootstrap_external>", line 385, in _check_name_wrappe
r
  File "<frozen importlib._bootstrap_external>", line 806, in load_module
  File "<frozen importlib._bootstrap_external>", line 665, in load_module
  File "<frozen importlib._bootstrap>", line 268, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 693, in _load
  File "<frozen importlib._bootstrap>", line 666, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 577, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 903, in create_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "app-3-adv.py", line 25, in <module>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\__init__.py", line 134, in <module>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\base.py", line 13, in <module>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\utils\__init__.py", line 11, in <module>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\utils\validation.py", line 18, in <module>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\sklearn\utils\fixes.py", line 144, in <module>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\sparse\linalg\__init__.py", line 114, in <module>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\sparse\linalg\isolve\__init__.py", line 6, in <modul
e>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\scipy\sparse\linalg\isolve\iterative.py", line 7, in <modu
le>
  File "C:\Users\bpachkor\AppData\Local\Programs\Python\Python35\lib\site-packag
es\pyinstaller-3.4.dev0+9f4eca801-py3.5.egg\PyInstaller\loader\pyimod03_importer
s.py", line 717, in load_module
    raise ImportError('%s: %s' % (e, fullname))
ImportError: DLL load failed: The specified module could not be found.: scipy.sp
arse.linalg.isolve._iterative
[7672] Failed to execute script app-3-adv

I'm new to this process. Did I missed any step? Is there anything missing in my spec file?
Please guide me to rectify this error.
Thanks

**Comment by FossenWang** [comment]
@bhagyashripachkor  just copy dlls into your dist folder where exe file lives

**Comment by xiboli** [comment]
Hi all,
I have tried all the methods before and still did not solve my problem. Finally, I solve it by this way.
when compiling the exe files in cmd window, my command is written as follows:

pyinstaller -F --paths C:\\Users\\lixib\\Desktop\\Hiwi_job\\Code\\2018.04.23\\venv\\Lib\\site-packages\\scipy\\extra-dll  pdf_num_detect.py

Hope this small tricks can help you all.

**Comment by phonygene** [comment]
Same problem with @jh0w3l05, did you get solution ?

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved. Otherwise please try PyInstaller v3.4 and the current development version. You also may want to have a look at `--hidden-imports` in the manual.
