### ISSUE TITLE
failed to compile python scripts in parallel

### ISSUE THREAD

**Issue by jingjun4361** [pyinstaller/pyinstaller#3244]
Hi all:
  I have an issue when compile python script in parallel, here are error messages:

_Traceback (most recent call last):
11:38:17   File "D:\Program Files\Python27\Scripts\pyinstaller-script.py", line 8, in <module>
11:38:17     load_entry_point('PyInstaller==3.3', 'console_scripts', 'pyinstaller')()
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\__main__.py", line 92, in run
11:38:17     run_build(pyi_config, spec_file, **vars(args))
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\__main__.py", line 46, in run_build
11:38:17     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\building\build_main.py", line 791, in main
11:38:17     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\building\build_main.py", line 737, in build
11:38:17     exec(text, spec_namespace)
11:38:17   File "<string>", line 33, in <module>
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\building\api.py", line 661, in __init__
11:38:17     self.__postinit__()
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\building\datastruct.py", line 161, in __postinit__
11:38:17     self.assemble()
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\building\api.py", line 691, in assemble
11:38:17     dist_nm=inm)
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\building\utils.py", line 276, in checkCache
11:38:17     res = winmanifest.GetManifestResources(os.path.abspath(cachedfile))
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\utils\win32\winmanifest.py", line 1005, in GetManifestResources
11:38:17     return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
11:38:17   File "D:\Program Files\Python27\lib\site-packages\pyinstaller-3.3-py2.7.egg\PyInstaller\utils\win32\winresource.py", line 168, in GetResources
11:38:17     hsrc = win32api.LoadLibraryEx(filename, 0, LOAD_LIBRARY_AS_DATAFILE)
11:38:17 pywintypes.error: (32, 'LoadLibraryEx', 'The process cannot access the file because it is being used by another process.')_

**we use pyinstaller 3.3. The fold "C:\Users\xxxxx\AppData\Roaming\pyinstaller\bincache00_py27_32bit" will be created when compiling a python script, while this fold is used by each compile thread, which may cause an exception when using the files in this fold concurrency.
so my question is: does pyinstaller-3.3 supports to compile python scripts in parallel?**

**Comment by htgoebel** [comment]
> does pyinstaller-3.3 supports to compile python scripts in parallel

Obviously it does not.You can work around it by setting `PYINSTALLER_CONFIG_DIR` (see the [man-page](https://pyinstaller.readthedocs.io/en/v3.3.1/man/pyinstaller.html))
