### ISSUE TITLE
WARNING: lib not found when exporting the python script with qt5 and pytorch 

### ISSUE THREAD

**Issue by gnawJ** [pyinstaller/pyinstaller#3259]
#### Warning parts:
47895 INFO: Looking for dynamic libraries
48787 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_mpich2_lp64.dll
48989 WARNING: lib not found: impi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_intelmpi_lp64.dll
59748 WARNING: lib not found: impi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_intelmpi_ilp64.dll
61514 WARNING: lib not found: pgc14.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_pgi_thread.dll
61669 WARNING: lib not found: pgf90.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_pgi_thread.dll
61829 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_pgi_thread.dll
63671 WARNING: lib not found: tbb.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_tbb_thread.dll
63985 WARNING: lib not found: msmpi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_msmpi_lp64.dll
64140 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_mpich2_ilp64.dll
67819 WARNING: lib not found: msmpi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_msmpi_ilp64.dll
68942 WARNING: lib not found: THS.dll dependency of C:\Users\JW\Anaconda3\Lib\site-packages\torch\_C.cp36-win_amd64.pyd
69172 WARNING: lib not found: shm.dll dependency of C:\Users\JW\Anaconda3\Lib\site-packages\torch\_C.cp36-win_amd64.pyd
69331 WARNING: lib not found: TH.dll dependency of C:\Users\JW\Anaconda3\Lib\site-packages\torch\_C.cp36-win_amd64.pyd
69516 WARNING: lib not found: ATen.dll dependency of C:\Users\JW\Anaconda3\Lib\site-packages\torch\_C.cp36-win_amd64.pyd

#### Full output 
436 INFO: PyInstaller: 3.3.1
437 INFO: Python: 3.6.1
440 INFO: Platform: Windows-10-10.0.16299-SP0
446 INFO: wrote C:\Users\JW\Documents\chatbot_interface4\LightBlue.spec
448 INFO: UPX is not available.
454 INFO: Extending PYTHONPATH with paths
['C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Scripts',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\__pycache__',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\torch',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\PyQt5\\Qt\\bin',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\torch\\optim',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\torch\\nn',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\torch\\autograd',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\torch\\distributions.py',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\torch\\_C.cp36-win_amd64.pyd',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\site-packages\\torch\\nn\\functional.py',
 'C:\\Users\\JW\\Documents\\chatbot_interface4',
 'C:\\Users\\JW\\Anaconda3\\Lib\\pickle.py',
 'C:\\Users\\JW\\Documents\\chatbot_interface4']
456 INFO: checking Analysis
479 INFO: Building because pathex changed
480 INFO: Initializing module dependency graph...
500 INFO: Initializing module graph hooks...
506 INFO: Analyzing base_library.zip ...
6920 INFO: running Analysis out00-Analysis.toc
6923 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\jw\anaconda3\python.exe
7866 INFO: Caching module hooks...
7876 INFO: Analyzing C:\Users\JW\Documents\chatbot_interface4\LightBlue.py
12668 INFO: Processing pre-find module path hook   distutils
15396 INFO: Processing pre-find module path hook   site
15397 INFO: site: retargeting to fake-dir 'c:\\users\\jw\\anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
40416 INFO: Loading module hooks...
40416 INFO: Loading module hook "hook-distutils.py"...
40419 INFO: Loading module hook "hook-encodings.py"...
40581 INFO: Loading module hook "hook-lib2to3.py"...
40584 INFO: Loading module hook "hook-numpy.core.py"...
40703 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
40707 INFO: Loading module hook "hook-pkg_resources.py"...
41959 INFO: Processing pre-safe import module hook   win32com
42882 INFO: Loading module hook "hook-pycparser.py"...
43217 INFO: Loading module hook "hook-pydoc.py"...
43218 INFO: Loading module hook "hook-PyQt5.py"...
43223 INFO: Loading module hook "hook-PyQt5.Qt.py"...
43224 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
43411 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
44339 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
44544 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
44545 INFO: Loading module hook "hook-pythoncom.py"...
45130 INFO: Loading module hook "hook-pywintypes.py"...
45707 INFO: Loading module hook "hook-setuptools.py"...
45744 INFO: Loading module hook "hook-sqlite3.py"...
45890 INFO: Loading module hook "hook-sysconfig.py"...
45891 INFO: Loading module hook "hook-win32com.py"...
47667 INFO: Loading module hook "hook-xml.dom.domreg.py"...
47668 INFO: Loading module hook "hook-xml.py"...
47770 INFO: Looking for ctypes DLLs
47858 INFO: Analyzing run-time hooks ...
47867 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
47872 INFO: Including run-time hook 'pyi_rth_pkgres.py'
47873 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
47876 INFO: Including run-time hook 'pyi_rth_qt5.py'
47895 INFO: Looking for dynamic libraries
48787 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_mpich2_lp64.dll
48989 WARNING: lib not found: impi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_intelmpi_lp64.dll
59748 WARNING: lib not found: impi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_intelmpi_ilp64.dll
61514 WARNING: lib not found: pgc14.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_pgi_thread.dll
61669 WARNING: lib not found: pgf90.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_pgi_thread.dll
61829 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_pgi_thread.dll
63671 WARNING: lib not found: tbb.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_tbb_thread.dll
63985 WARNING: lib not found: msmpi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_msmpi_lp64.dll
64140 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_mpich2_ilp64.dll
67819 WARNING: lib not found: msmpi.dll dependency of c:\users\jw\anaconda3\Library\bin\mkl_blacs_msmpi_ilp64.dll
68942 WARNING: lib not found: THS.dll dependency of C:\Users\JW\Anaconda3\Lib\site-packages\torch\_C.cp36-win_amd64.pyd
69172 WARNING: lib not found: shm.dll dependency of C:\Users\JW\Anaconda3\Lib\site-packages\torch\_C.cp36-win_amd64.pyd
69331 WARNING: lib not found: TH.dll dependency of C:\Users\JW\Anaconda3\Lib\site-packages\torch\_C.cp36-win_amd64.pyd
69516 WARNING: lib not found: ATen.dll dependency of C:\Users\JW\Anaconda3\Lib\site-packages\torch\_C.cp36-win_amd64.pyd
70071 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_acce041fe1dd7bc9.manifest
70183 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9317_none ...
70184 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b.manifest
70192 INFO: Searching for file msvcr90.dll
70192 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\msvcr90.dll
70193 INFO: Searching for file msvcp90.dll
70194 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\msvcp90.dll
70194 INFO: Searching for file msvcm90.dll
70195 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_08e0939fa840d57b\msvcm90.dll
70338 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9317_none_acce041fe1dd7bc9.manifest
70339 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9317)
70507 WARNING: lib not found: MSVCR90.dll dependency of c:\users\jw\anaconda3\Library\bin\zlib.dll
71208 INFO: Looking for eggs
71209 INFO: Using Python library c:\users\jw\anaconda3\python36.dll
71212 INFO: Found binding redirects:
[BindingRedirect(name='Microsoft.VC90.CRT', language=None, arch='amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9317), publicKeyToken='1fc8b3b9a1e18e3b')]
71231 INFO: Warnings written to C:\Users\JW\Documents\chatbot_interface4\build\LightBlue\warnLightBlue.txt
71459 INFO: Graph cross-reference written to C:\Users\JW\Documents\chatbot_interface4\build\LightBlue\xref-LightBlue.html
71548 INFO: checking PYZ
71556 INFO: Building because toc changed
71556 INFO: Building PYZ (ZlibArchive) C:\Users\JW\Documents\chatbot_interface4\build\LightBlue\out00-PYZ.pyz
79601 INFO: Building PYZ (ZlibArchive) C:\Users\JW\Documents\chatbot_interface4\build\LightBlue\out00-PYZ.pyz completed successfully.
79644 INFO: checking PKG
79645 INFO: Building because C:\Users\JW\Documents\chatbot_interface4\build\LightBlue\out00-PYZ.pyz changed
79647 INFO: Building PKG (CArchive) out00-PKG.pkg
79721 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
79724 INFO: Bootloader c:\users\jw\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
79725 INFO: checking EXE
79727 INFO: Rebuilding out00-EXE.toc because pkg is more recent
79728 INFO: Building EXE from out00-EXE.toc
79731 INFO: Appending archive to EXE C:\Users\JW\Documents\chatbot_interface4\build\LightBlue\LightBlue.exe
79787 INFO: Building EXE from out00-EXE.toc completed successfully.
79798 INFO: checking COLLECT
WARNING: The output directory "C:\Users\JW\Documents\chatbot_interface4\dist\LightBlue" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
89260 INFO: Removing dir C:\Users\JW\Documents\chatbot_interface4\dist\LightBlue
89502 INFO: Building COLLECT out00-COLLECT.toc
95025 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

**Comment by htgoebel** [comment]
And what is the problem? Please provide a proper description and a **minimal** example.

BTW: Your path extensions are garbage:, e.g. 'C:\Users\JW\Anaconda3\Lib\site-packages\torch\autograd',

**Comment by jorgesmok** [comment]
I get the same warnings

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved. Otherwise please try PyInstaller v3.4 and the current development version.
