### ISSUE TITLE
Pyinstaller imports outside exe

### ISSUE THREAD

**Issue by Hectorvass** [pyinstaller/pyinstaller#3262]
I notice that pyinstaller packages most imports inside exe even in one dir.  My question is as I can't find much on docs, is there a way to package all imports so that they are visible and outside of the main.exe

**Comment by tallforasmurf** [comment]
It's a very old feature of PyInstaller that it packages all imported modules in an archive inside the executable. Then it modifies the import process to look in the archive first. This is documented [here](http://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#inspecting-archives). Read that section to learn how to inspect and list the bundled modules using the archive viewer.

Possibly you are hoping to be able to update one imported module without having to distribute an entire new bundle? You could possibly do that for specific modules by using the `--exclude-module` option and then manually adding the excluded modules to a one-folder bundle. However if you did this you would introduce a major security hole in your app. Any bad person could distribute a modified module with arbitrary code that your app would execute blindly.

**Comment by Hectorvass** [comment]
@tallforasmurf  That's exactly what I was going for.  I'm wanting to make updates a lot smaller.

I tried to do it just then.
I even uses pyinstractor to get the relevant files.  It appears that it will not read imports properly when you copy them that way.

I get when using pandas:

  File "lib\site-packages\pandas\__init__.py", line 19, in <module>
ImportError: Missing required dependencies ['numpy', 'pytz', 'dateutil']

Well considering how easy it is to use pyinstractor, there isn't too much of a difference between compiled exe and leaving them outside exe.

**Comment by Hectorvass** [comment]
Actually I think it is possible, but it's not as much spaced saved as I thought.  The exe compiles everything neetly and saves you mucking around with finding right files for which library.
