### ISSUE TITLE
How to exclude specific imports

### ISSUE THREAD

**Issue by Hectorvass** [pyinstaller/pyinstaller#3265]
Am I missing something when excluding pandas?  It seems to put this goes in main.exe in no matter what

I try to add:
             excludes=['C:\\Users\\da\\AppData\\Local\\Programs\\Python\\Python\\Lib\\site-packages\\pandas'],

To spec file.

As well as 
pyinstaller --onefile --exclude pandas
in command line

No luck.  Am I missing something here or is better to create a separate virtual environment of python installation and use only needed modules with pyinstaller?  Or even separate python and swap when needed.

```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['Main.py'],
             pathex=[],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['C:\\Users\\da\\AppData\\Local\\Programs\\Python\\Python\\Lib\\site-packages\\pandas'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='win',
          debug=False,
          strip=False,
          upx=True,
          console=True)
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='win')
```

**Comment by htgoebel** [comment]
Excludes are defined as package names, not as path. Thus `--exclude pandas` would be the right one.
Please have a look at the xref .html file in the build-directory to learn more why this package is still included.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solves.
