### ISSUE TITLE
fixed / workaround for pyttsx3 test won't work once compiled with pyinstaller

### ISSUE THREAD

**Issue by Kerang** [pyinstaller/pyinstaller#3268]
I was having issues with pyttsx3 (current version) and pyinstaller (current version) on Windows 10 64-bit with Python 3.6.4 64-bit.

I got pyttsx3 to work with pyinstaller by doing the following two things.
I created a new hook-pyttsx3.py file and commented out everything in the pyi_rth_win32comgenpy.py file.

I'm not sure, if older versions of python or the old version of pyttsx need what's in pyi_rth_win32omgenpy.py, but it wasn't working with the new versions.

The example script:
```
"""
The pyttsx3 module is a cross-platform text to speech module that uses the OS's built-in tts program.
"""
# import the speech to text module
import pyttsx3

# Initialize the Speech Engine
engine = pyttsx3.init()
# Set the words per minute rate of the Speech engine
engine.setProperty('rate', 105)
# Tell the engine what you want it to say.
engine.say('Sally sells seashells by the seashore.')
engine.say('The quick brown fox jumped over the lazy dog.')
# Tell the engine to start saying what you wanted it to and stop when it reaches the end of the queued sayings.
engine.runAndWait()
print('Finished')
```

The example spec file:
```
# -*- mode: python -*-
block_cipher = None


a = Analysis(['pyttsx3_example.py'],
             pathex=['C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
		  a.zipfiles,
		  a.datas,
          name='pyttsx3_example',
          debug=True,
          strip=False,
          upx=False,
          console=True )
```

New hook-pyttsx3.py file:
```
#-----------------------------------------------------------------------------
# Copyright (c) 2013-2017, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


"""
pyttsx3 imports drivers module based on specific platform.
Fount at https://github.com/nateshmbhat/pyttsx3/issues/6
"""


hiddenimports = [
    'pyttsx3.drivers',
    'pyttsx3.drivers.dummy',
    'pyttsx3.drivers.espeak',
    'pyttsx3.drivers.nsss',
    'pyttsx3.drivers.sapi5',
]
```

Here's the **error** the new hook-pyttsx3.py file fixed:
```
Traceback (most recent call last):
File "site-packages\pyttsx3_init_.py", line 44, in init
File "c:\users\MyUser\appdata\local\programs\python\python36\lib\weakref.py", line 137, in getitem
o = self.datakey
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "pyttsx3_example.py", line 9, in
File "site-packages\pyttsx3_init_.py", line 46, in init
File "site-packages\pyttsx3\engine.py", line 52, in init
File "site-packages\pyttsx3\driver.py", line 75, in init
File "importlib_init_.py", line 126, in import_module
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 941, in _find_and_load_unlocked
File "", line 219, in _call_with_frames_removed
File "", line 994, in _gcd_import
File "", line 971, in _find_and_load
File "", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pyttsx3.drivers'
[10288] Failed to execute script pyttsx3_example
```

Here's the **error** that commenting out the pyi_rth_win32comgenpy.py file fixed:
```
Traceback (most recent call last):
File "site-packages\pyttsx3_init_.py", line 44, in init
File "c:\users\my_user\appdata\local\programs\python\python36\lib\weakref.py", line 137, in getitem
o = self.datakey
KeyError: 'sapi5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "pyttsx3_example.py", line 9, in
engine = pyttsx3.init('sapi5')
File "site-packages\pyttsx3_init_.py", line 46, in init
File "site-packages\pyttsx3\engine.py", line 52, in init
File "site-packages\pyttsx3\driver.py", line 77, in init
File "site-packages\pyttsx3\drivers\sapi5.py", line 22, in buildDriver
File "site-packages\pyttsx3\drivers\sapi5.py", line 41, in init
File "site-packages\pyttsx3\drivers\sapi5.py", line 83, in setProperty
File "site-packages\win32com\client\dynamic.py", line 549, in setattr
pywintypes.com_error: (-2147352573, 'Member not found.', None, None)
[2244] Failed to execute script pyttsx3_example
```

**Comment by egor4ik279** [comment]
Thanks! Worked for me

**Comment by Kerang** [comment]
It seems that commenting out the pyi_rth_win32comgenpy.py file breaks compatibility with Python 2.X.

Adding a check to the pyi_rth_win32comgenpy.py fixes the pywintypes.com_error I was getting:
```
#-----------------------------------------------------------------------------
# Copyright (c) 2013-2017, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


# The win32.client.gencache code must be allowed to create the cache in %temp%
# (user's temp). It is necessary to get the gencache code to use a suitable
# directory other than the default in lib\site-packages\win32com\client\gen_py.
# PyInstaller does not provide this directory structure and the frozen
# executable could be placed in a non-writable directory like 'C:\Program Files.
# That's the reason for %temp% directory.
#
# http://www.py2exe.org/index.cgi/UsingEnsureDispatch


import sys
# The win32com fixes aren't needed for Python 3.X
if sys.version_info >= (3, 0):
    pass
else:
    import atexit
    import os
    import shutil
    import tempfile


    # Put gen_py cache in temp directory.
    supportdir = tempfile.mkdtemp()
    # gen_py has to be put into directory 'gen_py'.
    genpydir = os.path.join(supportdir, 'gen_py')


    # Create 'gen_py' directory. This directory does not need
    # to contain '__init__.py' file.
    try:
        # win32com gencache cannot be put directly to 'supportdir' with any
        # random name. It has to be put in a directory called 'gen_py'.
        # This is the reason why to create this directory in supportdir'.
        os.makedirs(genpydir)
        # Remove temp directory at application exit and ignore any errors.
        atexit.register(shutil.rmtree, supportdir, ignore_errors=True)
    except OSError:
        pass


    # Override the default path to gen_py cache.
    import win32com
    win32com.__gen_path__ = genpydir


    # The attribute __loader__ makes module 'pkg_resources' working but On Windows
    # it breaks pywin32 (win32com) and test 'basic/test_pyttsx' will fail. Just
    # removing that attribute for win32com fixes that and gencache is created properly.
    if hasattr(win32com, '__loader__'):
        del win32com.__loader__


    # Ensure genpydir is in 'gen_py' module paths.
    import win32com.gen_py
    win32com.gen_py.__path__.insert(0, genpydir)
```

**Comment by blindguydiy** [comment]
day

Can you please explain to a dummy blind beginner the steps.  Do I create a hook-pyttsx3.py file in the site packages and copy the example code
#-----------------------------------------------------------------------------
# Copyright (c) 2013-2017, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------


"""
pyttsx3 imports drivers module based on specific platform.
Fount at https://github.com/nateshmbhat/pyttsx3/issues/6
"""


hiddenimports = [
    'pyttsx3.drivers',
    'pyttsx3.drivers.dummy',
    'pyttsx3.drivers.espeak',
    'pyttsx3.drivers.nsss',
    'pyttsx3.drivers.sapi5',
]
into it.

Then do i create a spec file, what must I call it? and copy 
# -*- mode: python -*-
block_cipher = None


a = Analysis(['pyttsx3_example.py'],
             pathex=['C:\\Program Files (x86)\\Windows Kits\\10\\Redist\\ucrt\\DLLs\\x64'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
		  a.zipfiles,
		  a.datas,
          name='pyttsx3_example',
          debug=True,
          strip=False,
          upx=False,
          console=True )
into the spec file.

Do I put the spec file into the folder where my .py file is that I want to run through pyinstaller.

Or do I not understand correctly.  
Also what must I comment out everything in the pyi_rth_win32comgenpy.py file.
Do I just open that file and comment all code out of it?  Then run through pyinstaller --onefile filename.py

**Comment by Kerang** [comment]
1.) The hook-pyttsx3.py file you create goes with the rest of the hook files in the pyinstaller site-packages folder.
Example Location in Windows 10:
`C:\Users\YOUR_USERNAME\AppData\Local\Programs\Python\Python36\Lib\site-packages\PyInstaller\hooks`

2.) Commenting out things in the pyi_rth_win32comgenpy.py file broke compatibility with Python 2.X. Checking for 3.X and skipping everything, fixed the error I was getting and should keep compatibility with Python 2.X.
> Adding a check to the pyi_rth_win32comgenpy.py fixes the pywintypes.com_error I was getting:

```
# The win32com fixes aren't needed for Python 3.X
if sys.version_info >= (3, 0):
    pass
else:
```

3.) See pyinstaller help, if you don't understand how to use a .spec file.
Basic example:
`pyinstaller --clean --onefile --windowed NameOfYourApplication.spec`

**Comment by blindguydiy** [comment]
Thank you.  Will try it and see if I come rite.

**Comment by bic096** [comment]
work for me without modifing on 

> python 38

> pyi_rth_win32omgenpy.py

**Comment by ReihanHaekal** [comment]
Thanks :)

**Comment by Macromux** [comment]
Try:
    `pip install "pyinstaller-hooks-contrib>=2021.2"`

or when converting:
    `pyinstaller --hidden-import=pyttsx3.drivers main.py`
