### ISSUE TITLE
app can't excute on other computers

### ISSUE THREAD

**Issue by hubery05** [pyinstaller/pyinstaller#3270]
I use pyinstaller  generate the implementation of the app as one-folder, in my own computer it  can run, but when I copy the folder to other computers it can not run.(I use ubuntu14.04,python2.6.7)

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by hubery05** [comment]
hubery@Hubery:~/ubuntu/python/PyQt$ pyinstaller psw.py
51 INFO: PyInstaller: 3.3.1
52 INFO: Python: 2.7.6
52 INFO: Platform: Linux-4.4.0-31-generic-x86_64-with-Ubuntu-14.04-trusty
52 INFO: wrote /home/hubery/ubuntu/python/PyQt/psw.spec
55 INFO: UPX is not available.
56 INFO: Extending PYTHONPATH with paths
['/home/hubery/ubuntu/python/PyQt', '/home/hubery/ubuntu/python/PyQt']
56 INFO: checking Analysis
56 INFO: Building Analysis because out00-Analysis.toc is non existent
56 INFO: Initializing module dependency graph...
59 INFO: Initializing module graph hooks...
103 INFO: running Analysis out00-Analysis.toc
119 INFO: Caching module hooks...
122 INFO: Analyzing /home/hubery/ubuntu/python/PyQt/psw.py
1120 INFO: Loading module hooks...
1120 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
1121 INFO: Loading module hook "hook-PyQt5.py"...
1122 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
1149 INFO: Loading module hook "hook-PyQt5.Qt.py"...
1150 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
1335 INFO: Loading module hook "hook-encodings.py"...
1762 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
1793 INFO: Looking for ctypes DLLs
1793 INFO: Analyzing run-time hooks ...
1795 INFO: Including run-time hook 'pyi_rth_qt5.py'
1798 INFO: Looking for dynamic libraries
2916 INFO: Looking for eggs
2916 INFO: Python library not in binary dependencies. Doing additional searching...
2960 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
2962 INFO: Warnings written to /home/hubery/ubuntu/python/PyQt/build/psw/warnpsw.txt
2971 INFO: Graph cross-reference written to /home/hubery/ubuntu/python/PyQt/build/psw/xref-psw.html
3012 INFO: checking PYZ
3012 INFO: Building PYZ because out00-PYZ.toc is non existent
3012 INFO: Building PYZ (ZlibArchive) /home/hubery/ubuntu/python/PyQt/build/psw/out00-PYZ.pyz
3179 INFO: Building PYZ (ZlibArchive) /home/hubery/ubuntu/python/PyQt/build/psw/out00-PYZ.pyz completed successfully.
3201 INFO: checking PKG
3201 INFO: Building PKG because out00-PKG.toc is non existent
3201 INFO: Building PKG (CArchive) out00-PKG.pkg
3231 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
3233 INFO: Bootloader /usr/local/lib/python2.7/dist-packages/PyInstaller/bootloader/Linux-64bit/run
3233 INFO: checking EXE
3233 INFO: Building EXE because out00-EXE.toc is non existent
3233 INFO: Building EXE from out00-EXE.toc
3233 INFO: Appending archive to ELF section in EXE /home/hubery/ubuntu/python/PyQt/build/psw/psw
3239 INFO: Building EXE from out00-EXE.toc completed successfully.
3242 INFO: checking COLLECT
3242 INFO: Building COLLECT because out00-COLLECT.toc is non existent
3242 INFO: Building COLLECT out00-COLLECT.toc
3412 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved.
