### ISSUE TITLE
possible packaging bug?

### ISSUE THREAD

**Issue by remdragon** [pyinstaller/pyinstaller#3292]
I have a minor issue with pyinstaller not grabbing a package's data file.

I installed the latest development version PyInstaller-3.4.dev0+5f9190544

I approached the module author about it, and their response was:

> If you can, investigate the exact issue with pyinstaller. It sounds to me like it's ignoring MANIFEST.in and/or the include_package_data flag from setup.py.
>
> I would be surprised if pyinstaller would have problems with "package data" as it is a standard feature for Python packages.

I know I could build and submit a hook, but before I go down that road, can someone please comment whether pyinstaller is supposed to be inspecting the package setup files as the author is suggesting? This would inform whether a hook is required or whether I need to dig deeper into pyinstaller.

Here is the issue I submitted on the project in question, in case it helps:

https://github.com/exhuma/puresnmp/issues/34

**Comment by htgoebel** [comment]
PyInstalle currenty does not automatically include all package data. So you'll need to provide a hook.

But anyway PyInstaller will never ever inspect any setup.py, MANIFEST or MANIFEST.in, as there are not available after you installed a package. PyInstaller might be able to analyse the packages meta-data, but this is heavily depending on how the package is installed (distutils, setuptools, pip, which version thereof, etc.). See #2065.

Anyway, I'm looking forward for you pull-request dor puresnmp.

**Comment by Xonshiz** [comment]
+1. Having issues with cfscrape.
