### ISSUE TITLE
temp files being deleted

### ISSUE THREAD

**Issue by Dan203** [pyinstaller/pyinstaller#3301]
I have a pyinstaller app that is designed to run in the tray 24/7. (using wx UI) Included with the app are some image files which are used to change the tray icon based on the status of the actual process. After the tray app has been running for a few days I start getting errors that the image files cannot be found. If I look in the current temp directory for the app I can see that they are in fact gone. (as are some other files that are typically there after a fresh start of the program)

I assume this is because Windows is automatically deleting temp files that have not been accessed in X days/hours. These image files are only used when the status changes so they could possibly go untouched for days/weeks.

Although I've also seen the same issue with the Mac build of my app, so this is not specific to Windows. It seems you must be using a similar temp folder on the Mac and it's doing a similar auto-cleanup.

Is there any way you could extract the temp files you need to a directory that is not going to be auto-cleaned by the OS so this doesn't happen?

**Comment by htgoebel** [comment]
`--runtime-tmpdir` does this, see https://pyinstaller.readthedocs.io/en/stable/usage.html#rarely-used-special-options

**Comment by Dan203** [comment]
Thanks. I figured there was an option for that, but didn't see it

**Comment by m3nu** [comment]
Looks useful. Next question is which temp dir to use...?

> Where to extract libraries and support files in onefile-mode. If this option is given, the bootloader will ignore any temp-folder location defined by the run-time OS. The _MEIxxxxxx-folder will be created here. Please use this option only if you know what you are doing.
