### ISSUE TITLE
Edit doc to show -F not required with -w for mac

### ISSUE THREAD

**Issue by tallforasmurf** [pyinstaller/pyinstaller#3304]
The [doc for MacOS bundles](https://pyinstaller.readthedocs.io/en/stable/usage.html#building-mac-os-x-app-bundles) strongly suggests that --onefile is needed. This is not the case, or at least will not be the case when #3233 is finally implemented, rather --onedir would be preferred and --onefile may not work at all (this remains to be seen). When #3233 is finished, edit the docs for that section.

**Comment by Legorooj** [comment]
Closing - the docs no longer suggest that and are clearer.
