### ISSUE TITLE
QtWebEngineProcess not found by app created with Pyinstaller

### ISSUE THREAD

**Issue by EightLegs** [pyinstaller/pyinstaller#3308]
My PyQt5 app apparently compiles correctly with Pyinstaller.  The resulting app starts up properly, but upon reaching a point in the code that calls upon a QtWebEngine widget, it crashes with the error report:

Could not find QtWebEngineProcess
Aborted (core dumped)

I've searched this forum and found mention of other people having problems with QtWebEngine calls, but I can't find a solution on the forum. 

I'm running:

Ubuntu Linux 16.04.02
PyQt5 5.10
SIP 4.19.7
Pyinstaller 3.3.1
Python 3.5.2

Please let me know if I need to post more details to help troubleshoot.

Can I copy a file into the directory structure created by Pyinstaller? In which case, which file and which location?

Thanks!

**Comment by bjones1** [comment]
Try the PR at #3233 to see if that fixes it. If not, please re-open the issue.

**Comment by EightLegs** [comment]
@bjones1 Thanks. I'd very much like to try the new code, but I don't know how to download it from the forum thread you referenced. I can read the thread, but I don't see a download link for the changed code. Sorry for being a noob.

**Comment by bjones1** [comment]
Go to [my branch](https://github.com/bjones1/pyinstaller/tree/pyqt5_fix) and click the "clone or download" button, then install that.

**Comment by EightLegs** [comment]
@bjones1 
Thanks for the pointer.  Sorry, but the problem persists.

 I downloaded the .zip file, and unzipped it into its own folder.  I then opened a Linux terminal and navigated to the folder of my python app and ran your Pyinstaller code as follows:

richard@richard-Lemur:~/Dropbox/Documents/Personal/Python/ebird/src$ python3 /home/richard/Dropbox/Downloads/pyinstaller-pyqt5_fix/pyinstaller.py eBirdMain.py
152 INFO: PyInstaller: 3.4.dev0+a954790b6
152 INFO: Python: 3.5.2
152 INFO: Platform: Linux-4.13.0-32-generic-x86_64-with-Ubuntu-16.04-xenial
153 INFO: wrote /home/richard/Dropbox/Documents/Personal/Python/ebird/src/eBirdMain.spec
155 INFO: UPX is not available.
156 INFO: Extending PYTHONPATH with paths
['/home/richard/Dropbox/Documents/Personal/Python/ebird',
 '/home/richard/Dropbox/Documents/Personal/Python/ebird/src']
156 INFO: checking Analysis
170 INFO: checking PYZ
172 INFO: checking PKG
172 INFO: Building because toc changed
172 INFO: Building PKG (CArchive) out00-PKG.pkg
262 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
263 INFO: Bootloader /home/richard/Dropbox/Downloads/pyinstaller-pyqt5_fix/PyInstaller/bootloader/Linux-64bit/run
263 INFO: checking EXE
264 INFO: Building because toc changed
264 INFO: Building EXE from out00-EXE.toc
265 INFO: Appending archive to ELF section in EXE /home/richard/Dropbox/Documents/Personal/Python/ebird/src/build/eBirdMain/eBirdMain
271 INFO: Building EXE from out00-EXE.toc completed successfully.
275 INFO: checking COLLECT
280 INFO: Building COLLECT out00-COLLECT.toc
1422 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

Then I navigated in the terminal to the resulting executable, and ran it.  The same problem with QtWebEngine not being found persists.

richard@richard-Lemur:~/Dropbox/Documents/Personal/Python/ebird/src/dist/eBirdMain$ ./eBirdMain
QXcbIntegration: Cannot create platform OpenGL context, neither GLX nor EGL are enabled
Could not find QtWebEngineProcess
Aborted (core dumped)

How do I reopen this thread? Does replying to you (as I'm doing now) automatically reopen it?

**Comment by bjones1** [comment]
Try again -- you didn't fully rebuild your binary. Remove all the files PyInstaller produces and run it again.

**Comment by EightLegs** [comment]
@bjones1 Huzzah!  It works beautifully!  Thanks again for your kind support.

**Comment by bjones1** [comment]
Great! My pleasure.

**Comment by craigstar** [comment]
@bjones1 why did you delete the branch? pyqt5_fix. I still have this problem. 
```
Could not find QtWebEngineProcess
./run.sh: line 2: 27738 Aborted 
```
