### ISSUE TITLE
PyInstaller generated executable for linux is not cleaning up so files in tmp

### ISSUE THREAD

**Issue by jay-dihenkar** [pyinstaller/pyinstaller#3315]
PyInstaller `.so` files in tmp dir are not cleaning up!

I've also observed that it's when we do not close the program gracefully.

I have added the gist of debugging here: https://gist.github.com/jay-dihenkar/7a12e448abd2784d1df91ad6f03dcf35

INFO provided in gist:

1. `readelf` output
2. tmp file dir
3. checked no longer open using `lsof`

Let me know if I'm missing something?

**Comment by jay-dihenkar** [comment]
I basically need a starting point to troubleshoot this problem.....

**Comment by htgoebel** [comment]
I don not understand the issue. What is the exact problem? What are the actual results in detail? What did you expect?
Beside this, gdb is your friend :-)

**Comment by htgoebel** [comment]
No new infos since several months, closing.
