### ISSUE TITLE
Pyinstaller 

### ISSUE THREAD

**Issue by JoeHelp** [pyinstaller/pyinstaller#3317]
Test.py
import encodings
print('Test')

**Sample of Compilations Warning**

    102 INFO: PyInstaller: 3.3.1
    102 INFO: Python: 3.7.0b1
    104 INFO: Platform: Windows-10-10.0.14393-SP0
    2771 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\apps\python\python37\python.exe
    2801 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\apps\python\python37\python.exe

**Error - executing the program** 
Fatal Python error: initfsencoding:
    unable to load the file system codec zipimport.ZipImportError:
    can't find module 'encodings' Current thread 0x0000289c (most recent call first):

**Comment by abravetti** [comment]
duplicate of https://github.com/pyinstaller/pyinstaller/issues/3219?

**Comment by htgoebel** [comment]
Python 3.7 is not yet supported. Did you read the README, the manual, or at least the website?

**Comment by yun9157** [comment]
only reinstall it?  is it have solve other  way?

**Comment by pvanik1** [comment]
Even though 3.7 now seems to be supported, I'm still getting the same zipimport encodings error

**Comment by amritkp89** [comment]
I am not sure 3.7 is still supported yet!! I got this error now.. :(

**Comment by erotavlas85** [comment]
+1

**Comment by htgoebel** [comment]
PyInstaller supports Python 3.7 Up to a few minutes ago you have had to build the bootloaders yourself, as already written e.g https://github.com/pyinstaller/pyinstaller/issues/3642#issuecomment-408619680. Bootloaders are now rebuild, so please use the current development head.
