### ISSUE TITLE
PySide QSystemTrayIcon not visible

### ISSUE THREAD

**Issue by wemoloh** [pyinstaller/pyinstaller#3327]
The following code runs fine when run directly from the python interpreter, but when packaged with PyInstaller, the icon does not show up in the system tray.  I couldn't find any errors or warnings, it just seems to silently fail.

Possible duplicate of https://github.com/pyinstaller/pyinstaller/issues/805 -- which was closed but not resolved.

Python 3.4.8
PySide 1.2.4
PyInstaller 3.4.dev0+d4798a98a
Ubuntu 16.04 with Unity

```python
from PySide import QtGui


def main():
    app = QtGui.QApplication([])
    
    tray = QtGui.QSystemTrayIcon(QtGui.QIcon('/absolute/path/to/icon.png'))
    tray.show()
    
    app.exec_()


if __name__ == '__main__':
    main()
```

**Comment by wemoloh** [comment]
I was able to work around this on my system by adding the following to my pyinstaller command:

```
--add-binary=/usr/lib/x86_64-linux-gnu/qt4/plugins/systemtrayicon/libsni-qt.so:qt4_plugins/systemtrayicon
```

**Comment by htgoebel** [comment]
@bjones1 Is this handled by your PyQt fixes?

**Comment by bjones1** [comment]
@htgoebel, no, since this is Qt4 and also PySide -- my PR is PyQt5. @cbenhagen will hopefully provide PySide2 (similar to PyQt5) functionality. The fix (as missing binary) seems simple. @cbenhagen, as the PySide maintainer, might be able to help.

**Comment by quangvu3** [comment]
> I was able to work around this on my system by adding the following to my pyinstaller command:

> `--add-binary=/usr/lib/x86_64-linux-gnu/qt4/plugins/systemtrayicon/libsni-qt.so:qt4_plugins/systemtrayicon`

It worked for me. Thanks @wemoloh

**Comment by Rishi16** [comment]
How to fix the same for windows then?

**Comment by Rishi16** [comment]
I was able to work it out on windows as well. The trick is to use a use resource file generated from a .qrc file and import it in your code.
test.qrc: 
```
<!DOCTYPE RCC><RCC version="1.0">
<qresource prefix="/">
   <file>images/icon.png</file>
</qresource>
</RCC>
```
images above is a folder in which the icon is present

Use the following command (pyrcc3/4/5 depends on your version of pyqt)  in cmd to generate and a resource file:
`pyrcc5 "path/test.qrc" -o test_rc.py`

Usage:
`import test_rc.py`
wherever you are setting the icon use this. ':/images/jira.png' is from the resource file.
`self.icon = QIcon(':/images/jira.png')`

**Comment by RobLW** [comment]
> 
> 
> I was able to work it out on windows as well. The trick is to use a resource file generated from a .qrc file and import it in your code.
> test.qrc:
> 
> ```
> <!DOCTYPE RCC><RCC version="1.0">
> <qresource prefix="/">
>    <file>images/icon.png</file>
> </qresource>
> </RCC>
> ```
> 
> 'images' above is a folder in which the icon is present
> 
> Use the following command (pyrcc3/4/5 depends on your version of pyqt) in cmd to generate a resource file:
> `pyrcc5 "path/test.qrc" -o test_rc.py`
> 
> Usage:
> `import test_rc.py`
> _wherever you are setting the icon use this. ':/images/icon.png' is from the resource file._
> `self.icon = QIcon(':/images/icon.png')`

Thanks @Rishi16 this worked a treat. Bit of a pain to have to do it, but only takes a minute or two to complete.

**Comment by bjones1** [comment]
Looks like this was fixed by https://github.com/pyinstaller/pyinstaller/issues/3327#issuecomment-417831244.

**Comment by git-chenjiqing** [comment]
在树莓派上此方式图片也不能正常显示

**Comment by git-chenjiqing** [comment]
.qrc文件生成的资源文件在树莓派上不起作用
