### ISSUE TITLE
works on ppc64le-suse-linux

### ISSUE THREAD

**Issue by christianhaessler** [pyinstaller/pyinstaller#3339]
This is only a information:
I've tested pyinstaller (latest build):
```
user@server:~/pyinstaller$ ~/git/pyinstaller/pyinstaller.py --version
3.4.dev0+g1934b771.mod
```
With SuSe Linux Enterprise Server 12 Little Endian on Power.

Python Version:
```
user@server:~/pyinstaller$ python --version
Python 2.7.13
```

After compiling the bootloader manually:
```
cd bootloader
python ./waf distclean all
```
Works fine. Thanks for developing this smart tool.

**Comment by htgoebel** [comment]
Thanks for the info :-)
