### ISSUE TITLE
Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->pyinstaller)

### ISSUE THREAD

**Issue by vincentcox** [pyinstaller/pyinstaller#3340]
Since a few days I have issues with installing pyInstaller. It's running on a continious deployment platform, so I am surprised it appeared.

The error I am having is: `Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->pyinstaller) (from versions: ) No matching distribution found for pywin32>=223 (from pypiwin32->pyinstaller)`

I tried to bypass this by installing the pythonwheel manually. I downloaded `https://pypi.python.org/packages/65/83/0b14690d70bcd193a67c8b0a640129717e37a11d8e6a3e28a01e47910737/pywin32-223-cp27-cp27m-win_amd64.whl#md5=c9d2d260ef87592bb04cbc59f1ffe2d2` but the installation is failing because `pywin32-223-cp27-cp27m-win_amd64.whl is not a supported wheel on this platform.`

The full error trail:

```
wine64 c:\\Python-64\\python.exe c:\\Python-64\\scripts\\pip.exe install pyinstaller --upgrade
e:heap:HeapSetInformation 0x3b4000 0 0x32fcd0 4
fixme:heap:HeapSetInformation 0x8e0000 0 0x329110 4
Collecting pyinstaller
fixme:toolhelp:CreateToolhelp32Snapshot Unimplemented: heap list snapshot
fixme:toolhelp:Heap32ListFirst : stub
  Downloading PyInstaller-3.3.1.tar.gz (3.5MB)
    100% |################################| 3.5MB 121kB/s 
fixme:heap:HeapSetInformation 0x3b4000 0 0x32fcd0 4
fixme:heap:HeapSetInformation 0x8e0000 0 0x3252a0 4
Collecting setuptools (from pyinstaller)
  Downloading setuptools-38.5.1-py2.py3-none-any.whl (489kB)
    100% |################################| 491kB 685kB/s 
Collecting pefile>=2017.8.1 (from pyinstaller)
  Downloading pefile-2017.11.5.tar.gz (61kB)
    100% |################################| 65kB 3.1MB/s 
fixme:heap:HeapSetInformation 0x3b4000 0 0x32fcd0 4
fixme:heap:HeapSetInformation 0x8e0000 0 0x3252a0 4
Collecting macholib>=1.8 (from pyinstaller)
  Downloading macholib-1.9-py2.py3-none-any.whl (40kB)
    100% |################################| 40kB 3.7MB/s 
Collecting future (from pyinstaller)
  Downloading future-0.16.0.tar.gz (824kB)
    100% |################################| 827kB 468kB/s 
fixme:heap:HeapSetInformation 0x3b4000 0 0x32fcd0 4
fixme:heap:HeapSetInformation 0x8e0000 0 0x3252a0 4
Collecting pypiwin32 (from pyinstaller)
  Downloading pypiwin32-223-py3-none-any.whl
Collecting altgraph>=0.15 (from macholib>=1.8->pyinstaller)
  Downloading altgraph-0.15-py2.py3-none-any.whl
Collecting pywin32>=223 (from pypiwin32->pyinstaller)
  Could not find a version that satisfies the requirement pywin32>=223 (from pypiwin32->pyinstaller) (from versions: )
No matching distribution found for pywin32>=223 (from pypiwin32->pyinstaller)
```

Any idea what is causing this?

The full build log can be found here, if you need more context information on the issue: https://travis-ci.org/vincentcox/StaCoAn/jobs/346428154 (but as far I can see I posted all the relevant information here).

**Comment by htgoebel** [comment]
@xoviat Is this related to #3141?

**Comment by vincentcox** [comment]
Any action on my side I can do? Screenshots, logs,... 
Let me know if so. 

Already thanks for looking into this!

**Comment by vincentcox** [comment]
https://github.com/pyinstaller/pyinstaller/commit/466a470d748dce452ab4e925369678d950146fed

Seems python 3.4 is not supported anymore. In my wine deployment I use an .msi installer to install the latest python. But an .msi installer is only available for python 3.4. (https://github.com/vincentcox/StaCoAn/blob/master/.travis.yml#L48)

Is there a way to install it in wine without .msi installer?

**Comment by htgoebel** [comment]
> Any action on my side I can do?

Just retry it. According to PyPI, pypiwin32 223 is available since 2018-02-16, which is yesterday.

Even if the original error message suggests so, this is *not* related to PyInstaller. PyInstaller requires `pypiwin32`, but not a specific version. See https://github.com/pyinstaller/pyinstaller/blob/v3.3.1/setup.py#L51


> Seems python 3.4 is not supported anymore.

Since you are referring to commit 466a470 I assume you mean "supported by PyInstaller". This is wrong. Pyinstaller still supports Python 3.4 and will support it until its end-of-life. This commit is dropping support for Python 3.3, as the commit message says.

**Comment by htgoebel** [comment]
Addendum: "223" does not occur in PyInstaller's code.
```
{pyinsaller (develop)]$ git grep -l 223
PyInstaller/bootloader/Windows-32bit/run.exe
PyInstaller/bootloader/images/icon-console.icns
PyInstaller/bootloader/images/icon-console.svg
PyInstaller/bootloader/images/icon-windowed.icns
PyInstaller/bootloader/images/icon-windowed.svg
bootloader/src/msvc_stdint.h
bootloader/zlib/crc32.h
bootloader/zlib/inffixed.h
doc/CHANGES-3.rst
doc/_static/pyinstaller-draft1a.ico
doc/usage.rst
tests/functional/data/set_icon/pyi_icon.icns
```
