### ISSUE TITLE
PyInstaller runs, packaged program runs with no errors but incorrect output

### ISSUE THREAD

**Issue by gitdjc** [pyinstaller/pyinstaller#3341]
I want to convert into a standalone Windows executable a Python script PCE.py, which is in an isolated directory. The script works with the installed Python 3.6.4, making use of a third-party package "phonenumbers" which I installed and which the program uses the usual way:

    import phonenumbers

along with some other common imports. I installed the latest development version of PyInstaller, 3.4.dev0, and ran it on the script several different ways:

    pyinstaller PCE.py
    pyinstaller --onedir PCE.py
    pyinstaller --onefile PCE.py
    pyinstaller --noupx PCE.py

Each of those produced PCE.exe in a subdirectory. Each time, positioned at the command line in the original directory where PCE.py is found, I ran PCE.exe, and each time it seemed to run, produced debugging output (from "print()" in the script), but produced incorrect output.

Naively, the way the output is incorrect suggests to me that the program couldn't correctly use things that should have been imported from "phonenumbers".

I'm attaching an image of the .spec file.

Do you see what's not working?  Can you suggest where I can begin to look to fix this and get a true standalone executable from this program?

![pce-spec](https://user-images.githubusercontent.com/36742399/36701019-f5ec521a-1b51-11e8-9dea-c4f1e2dc6d5e.gif)

**Comment by tallforasmurf** [comment]
Is this regarding the pypi package [phonenumbers 8.9.0](https://pypi.python.org/pypi/phonenumbers/8.9.0)? Looking at its code [on github](https://github.com/daviddrysdale/python-phonenumbers/tree/dev/resources) I note it has a number of aux. files which probably need to be included in the bundle.

If that is the case, look in your --onefile folder to see if they are there (probably not) and [read the docs](https://pythonhosted.org/PyInstaller/spec-files.html#adding-files-to-the-bundle) to see how to add them.

If that's not the problem, reopen this issue and supply more info.
