### ISSUE TITLE
How to debug No module named issue after generated the exe files by pyinstaller? Thanks!

### ISSUE THREAD

**Issue by harte2018** [pyinstaller/pyinstaller#3344]
Hello,

 May I have a question. I met issue after used ssh2-python lib when run the exe file which using pyinstaller to build one. with the error info "ImportError: No module named 'ssh2.agent'".
 Any suggestion are welcome. 
 Like how to debug this kind issue first by myself.  And additional parameter -p to do the work around etc.

Best Regards
Harte

File "main.py", line 13, in 
 File "D:\Python34\lib\site-packages\pyinstaller-3.3.1-py3.4.egg\PyInstaller\lo
 ader\pyimod03_importers.py", line 631, in exec_module
 exec(bytecode, module.dict)
 File "SSHcm.py", line 30, in 
 File "D:\Python34\lib\site-packages\pyinstaller-3.3.1-py3.4.egg\PyInstaller\lo
 ader\pyimod03_importers.py", line 714, in load_module
 module = loader.load_module(fullname)
 File "ssh2\agent.pxd", line 24, in init ssh2.session
 ImportError: No module named 'ssh2.agent'
 [13140] Failed to execute script main

**Comment by htgoebel** [comment]
This looks like ssh2\agend.pxd being a Cython file, which PyInstaller can not analyse. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

We would appreciate if you'd submit a hook for this. See https://pyinstaller.readthedocs.org/en/latest/hooks.html for more information about how to implement hooks.

**Comment by htgoebel** [comment]
Closing, since this was a support question :-)

**Comment by harte2018** [comment]
Thanks htgoebel  :) 
+1:

**Comment by harte2018** [comment]
Hello htgoebel,   May I have one more question, which SSH lib you think is good and  support by pyinstaller in current.  The paramiko is have many lib dependency in windows. and the ssh2-python has not been supported correctly by pyinstaller.

**Comment by htgoebel** [comment]
I can't recommend a SSH lib, since I did not look at them for several years. Fixing ssh2-python should be easy as you simply need to add an hidden-import.

**Comment by harte2018** [comment]
Thanks htgoebel,    I have raise one issue to ssh2-python through the web: https://github.com/ParallelSSH/ssh2-python.
  But not get the feedback. They might not interesting on this kind of support. From a normal user view, does this hook files are very hard to generated, as I am not clear the details need involved into hook file. Any guide or suggestion are welcome..

**Comment by htgoebel** [comment]
Hooks are easy to implement, see https://pyinstaller.readthedocs.org/en/latest/hooks.html.

But you can start with `--hidden-import` and hen implement hook later.

**Comment by harte2018** [comment]
Hello Htgoebel,
Like this kind of ssh2\agend.pxd ,  How I do the -- hidden -import or hooks file.  Thanks in advance.
--------------------------------------------------------------------------------
from session cimport Session
cimport c_ssh2


cdef object PyAgent(c_ssh2.LIBSSH2_AGENT *agent, Session session)


cdef class Agent:
    cdef c_ssh2.LIBSSH2_AGENT *_agent
    cdef Session _session


cdef int auth_identity(const char *username,
                       c_ssh2.LIBSSH2_AGENT *agent,
                       c_ssh2.libssh2_agent_publickey **identity,
                       c_ssh2.libssh2_agent_publickey *prev) nogil except -1

cdef void clear_agent(c_ssh2.LIBSSH2_AGENT *agent) nogil

cdef int agent_auth(char * _username,
                    c_ssh2.LIBSSH2_AGENT * agent) nogil except 1

cdef c_ssh2.LIBSSH2_AGENT * init_connect_agent(
    c_ssh2.LIBSSH2_SESSION *_session) nogil except NULL

cdef c_ssh2.LIBSSH2_AGENT * agent_init(
    c_ssh2.LIBSSH2_SESSION *_session) nogil except NULL

**Comment by harte2018** [comment]
Any suggestion for this file are really welcome.

**Comment by htgoebel** [comment]
As already written: Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

Please understand that we are not going to do your job.

**Comment by harte2018** [comment]
Hello htgoebel, I have check the guide, but not list the detail way that how to handle *.pyd files.
Would you please give me some more help .
Example:
There have two files agent.pyd anget.pxd in lib which pyinstaller can not analysis.
And the Pyinstaller report "No module named 'ssh2.agent'"

I am using "from ssh2.session import Session" is the python file when coding.

Then, How I develop my hook file: hook-ssh2.session.session.py to addese into running environment.

Many thanks.
