### ISSUE TITLE
hylang support

### ISSUE THREAD

**Issue by umlaeute** [pyinstaller/pyinstaller#3353]
trying to create an application that uses [hy](https://github.com/hylang), I'm having a hard-time getting the imports right.

The code is fairly trivial:
~~~python
import hy
~~~

Which gives me
> `ModuleNotFoundError: No module named 'hy.core.language'`

Which *should* be easy enough to fix by adding `hy.core.language` to the hidden-imports (see below on how the imports work in hy).

Unfortunately, this only gives me:

~~~
[...]
4750 DEBUG: Hidden import: hy.core.language
4750 INFO: Analyzing hidden import 'hy.core.language'
5218 INFO: Processing pre-safe import module hook   win32com
5218 DEBUG: win32com: extending __path__ with dir 'C:\\Python34\\lib\\site-packages\\win32comext'
5375 ERROR: Hidden import 'hy.core.language' not found
[...]
~~~

and analysing the resulting binary (and it's embedded .pyz) with `pyi-...` confirms that the module is not embedded:

~~~
$ pyi-archive_viewer dist/wrapper/wrapper
 pos, length, uncompressed, iscompressed, type, name
[(0, 265, 342, 1, 'm', 'struct'),
 (265, 1123, 1833, 1, 'm', 'pyimod01_os_path'),
 (1388, 4284, 9238, 1, 'm', 'pyimod02_archive'),
 (5672, 7308, 18588, 1, 'm', 'pyimod03_importers'),
 (12980, 1859, 4171, 1, 's', 'pyiboot01_bootstrap'),
 (14839, 78, 95, 1, 's', 'wrapper'),
 (14917, 0, 0, 0, 'o', 'W ignore'),
 (14917, 0, 0, 0, 'o', 'v'),
 (14917, 1344875, 1344875, 0, 'z', 'out00-PYZ.pyz')]
? O out00-PYZ.pyz
 [...]
 'http.server': (0, 505073, 15246),
 'hy': (1, 520319, 443),
 'hy._compat': (0, 520762, 681),
 'hy.compiler': (0, 521443, 23985),
 'hy.core': (1, 545428, 130),
 'hy.errors': (0, 545558, 1647),
 'hy.importer': (0, 547205, 4140),
 'hy.lex': (1, 551345, 524),
 'hy.lex.exceptions': (0, 551869, 930),
 'hy.lex.lexer': (0, 552799, 865),
 'hy.lex.parser': (0, 553664, 4280),
 'hy.macros': (0, 557944, 2847),
 'hy.models': (0, 560791, 5844),
 'hy.version': (0, 566635, 102),
 'imp': (0, 566737, 4690),
 [...]
~~~

### non-working example
I've setup a repository (https://github.com/umlaeute/hy-test) that reproduces the problem on [travis-ci](https://travis-ci.org/umlaeute/hy-test/jobs/347970040)

As you can see I pull the latest and greatest dev-version of pyinstaller into a virtualenv (using Python3)
running the [hy-lang code directly](https://travis-ci.org/umlaeute/hy-test/jobs/347970040#L484) or via a [python-wrapper](https://travis-ci.org/umlaeute/hy-test/jobs/347970040#L492) works fine, as does [importing the `hy.core.language`](https://travis-ci.org/umlaeute/hy-test/jobs/347970040#L501) module into python.

So why is the `hy.core.language` module [not found by `pyinstaller`](https://travis-ci.org/umlaeute/hy-test/jobs/347970040#L852)?

### some details
The main problem seems to come from the `hy.core` module, which uses both relative imports (which gives me sorrow on W32, but luckily not on Linux) and manual imports via `importlib` (hurting on both W32 and Linux)

the `hy/core/__init__.py`:
~~~python
from . import reserved   # noqa

STDLIB = [
    "hy.core.language",
    "hy.core.shadow"
]
~~~

and STDLIB are imported like:
~~~python
    for module in hy.core.STDLIB:
        mod = importlib.import_module(module)
~~~

**Comment by htgoebel** [comment]
1) The hidden import is not found since there is no Python module `hy.core.language`, see https://github.com/hylang/hy/tree/master/hy/core. There is a corresponding .hy-file, not no .py-file.

2) I assume these .hy-files need to be added as `data`. Hopefully this works since the [`hy` importer](https://github.com/hylang/hy/blob/0.14.0/hy/importer.py#L243) seems to rely on these files exit in the file-systeman and to not be able to use get_data().

**Comment by umlaeute** [comment]
aye, that was the right clue.

the following `hook-hy.py` fixes my problem:

~~~py
# -*- mode: python -*-
import hy
import os.path

datas=[(os.path.dirname(hy.__file__), 'hy')]
~~~

**Comment by htgoebel** [comment]
Obviously this is solved.
