### ISSUE TITLE
ModuleNotFoundError: No module named 'nltk.chunk.named_entity'

### ISSUE THREAD

**Issue by rw171069** [pyinstaller/pyinstaller#3356]
Hi,
I have a tkinter python program and I have converted it into an '.exe' program. This program contains NLTK. However, when I use the .exe program it comes up with

```
Traceback (most recent call last):
File "tkinter_init.py", line 1699, in __call_
File "Completedcode.py", line 142, in highlightermode
File "Completedcode.py", line 75, in highlight_text
File "Completedcode.py", line 226, in get_continuous_chunks
File "site-packages\nltk\chunk\init_.py", line 176, in ne_chunk
File "site-packages\nltk\data.py", line 839, in load
ModuleNotFoundError: No module named 'nltk.chunk.named_entity'
```
Any ideas what I can do?

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by rw171069** [comment]
Hi, 
Thanks. I am dyslexic and struggle to understand. I looked in my 'dist' folder and I could not see anything to do with NLTK. What should I do?

**Comment by htgoebel** [comment]
The trace back says: `No module named 'nltk.chunk.named_entity'`, thus you need to make PyInstaller to include that module. Either by adding `--hidden-import nltk.chunk.named_entity` on the command line or by adding `"nltk.chunk.named_entity"` to the `hidden_imports` in your `spec`-file.
