### ISSUE TITLE
Modify / update / add new scripts to .exe

### ISSUE THREAD

**Issue by kreamas** [pyinstaller/pyinstaller#3358]
Hi, I’m wondering (once the python program has been converted to .exe) what if I modify some of my scripts and / or add a new script, is there a way to “compile” or “update” the .exe only with those new / modified scripts?

Thanks a lot

**Comment by tallforasmurf** [comment]
There is no ability to update. You make a new .exe based on the changed script.

**Comment by kreamas** [comment]
Thanks a lot for your response :)

 

Do you know if there’s a way / package to achieve that goal?

**Comment by tallforasmurf** [comment]
Ask on the mailing list, giving more details about what you need to accomplish.
