### ISSUE TITLE
OS X app bundles don't run

### ISSUE THREAD

**Issue by tycho** [pyinstaller/pyinstaller#3359]
Running into a problem with PyInstaller 3.3.1 (also tried current develop branch). The project I'm building uses PyQt 5.10.1. I can build a working PyInstaller distribution on Windows, but I'm having trouble on the Mac side. This same project built fine with a much older PyInstaller + PyQt5.

If I just try to run the app bundle, it aborts immediately. So here's the result of trying to run it in a terminal:
```
$ Yubico\ Authenticator.app/Contents/MacOS/yubioath-gui
This application failed to start because it could not find or load the Qt platform plugin "cocoa"
in "".

Reinstalling the application may fix this problem.
Abort trap: 6
```

The plugins appear to be present, though (find run from inside the .app bundle):
```
$ find . | grep plugins
./Contents/MacOS/PyQt5/Qt/plugins
./Contents/MacOS/PyQt5/Qt/plugins/platforms
./Contents/MacOS/PyQt5/Qt/plugins/platforms/libqwebgl.dylib
./Contents/MacOS/PyQt5/Qt/plugins/platforms/libqoffscreen.dylib
./Contents/MacOS/PyQt5/Qt/plugins/platforms/libqminimal.dylib
./Contents/MacOS/PyQt5/Qt/plugins/platforms/libqcocoa.dylib
./Contents/MacOS/PyQt5/Qt/plugins/printsupport
./Contents/MacOS/PyQt5/Qt/plugins/printsupport/libcocoaprintersupport.dylib
./Contents/MacOS/PyQt5/Qt/plugins/bearer
./Contents/MacOS/PyQt5/Qt/plugins/bearer/libqgenericbearer.dylib
./Contents/MacOS/PyQt5/Qt/plugins/iconengines
./Contents/MacOS/PyQt5/Qt/plugins/iconengines/libqsvgicon.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqgif.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqwbmp.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqwebp.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqico.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqjpeg.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqtiff.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqsvg.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqicns.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqtga.dylib
./Contents/MacOS/PyQt5/Qt/plugins/imageformats/libqmacjp2.dylib
```

Any idea what is happening here? Seems like it just has some plugin search path problem, but I'm not sure how that's plumbed through.

**Comment by tycho** [comment]
So the above is the result if I use the `pyqt` package from Homebrew. If I `pip install pyqt5` into the Homebrew Python install, it gets farther, but looks all wrong:

![screen shot 2018-03-04 at 3 12 24 pm](https://user-images.githubusercontent.com/29616/36951950-744786c8-1fbe-11e8-80c1-9d7c25232eda.png)

First, it's using Windows-style controls (?) and second, it's not scaling with high DPI properly.

**Comment by tycho** [comment]
Also just tried the Python.org distribution of Python, and pip installed the dependencies into that. Same as the result in my previous post: windows-style controls, no DPI scaling.

**Comment by xoviat** [comment]
Does it work with this?

```
pip install git+https://github.com/bjones1/pyinstaller.git@pyqt5_fix
```

**Comment by tycho** [comment]
@xoviat Yes, that works with both the Python.org distribution and the Homebrew packages!

It looks like DPI scaling is still wonky, but that is apparently not a -new- issue. My old build has the same scaling problem. Hmm...

**Comment by bjones1** [comment]
@tycho, thanks for testing! I'll go ahead and close this. @xoviat, thanks for the pointer.

@tallforasmurf, where's a good place to put this `Info.plist` find -- somewhere in the Wiki? Or should PyInstaller auto-generate this? Again, I'm clueless about Mac things...

**Comment by tycho** [comment]
@bjones1 In my case I just added it to the spec. https://github.com/tycho/python-yubicommon/commit/f3b13a7f2bbcc777c256e925536a0d9cc36aaddd Probably a good idea to mention it on the wiki somewhere.

Will those changes from the pyqt5_fix branch make their way into the main pyinstaller tree sometime soon?

**Comment by bjones1** [comment]
Probably. I'd like some code review from @htgoebel (any anyone else who can review and help improve the code - @xoviat, any thoughts/suggestions?). Plus, there's one fix I still need to make before it's complete.

**Comment by bjones1** [comment]
@tycho, I see something similar at http://pyinstaller.readthedocs.io/en/stable/spec-files.html#spec-file-options-for-a-mac-os-x-bundle in terms of PyQt5. Should this be updated? Or can the `'NSPrincipalClass': 'NSApplication',` be removed and the app still work on retina screens?

**Comment by tallforasmurf** [comment]
As it happens, we already document plist generation, and the example is of the same NSHighResolutionCapable key:
    http://pyinstaller.readthedocs.io/en/stable/spec-files.html#spec-file-options-for-a-mac-os-x-bundle
@tycho what else should be done to avoid the waste of your time?

**Comment by tycho** [comment]
I don't think there's anything more you guys could do for the highDPI stuff. I just needed to RTFM.
