### ISSUE TITLE
Making .exe from pyInstaller working from desktop icon

### ISSUE THREAD

**Issue by kreamas** [pyinstaller/pyinstaller#3370]
Hi.

I've created my .exe file successfully within the folder where all of my scripts exists.

It created successfully both dist and build folders.

However I want to create an icon in my desktop to run the .exe file that pyInstaller created within dist folder.  My first silly thought was just "copy-paste" the .exe in the desktop...but it didn't work.

Is there a way to create an icon in the desktop that runs the .exe?

Thanks

**Comment by htgoebel** [comment]
For the records: No, this is out of scope for PyInstaller. Use some tool like the NullSoft installer.
