### ISSUE TITLE
Ubuntu Pack Two processes 

### ISSUE THREAD

**Issue by lauixData** [pyinstaller/pyinstaller#3388]
Start Pack file 

> ps -ef | grep client 

Appear Two processes 

```
root     32677 26265  4 19:12 pts/0    00:00:00 ./client
root     32678 32677 12 19:12 pts/0    00:00:00 ./client
```

**Comment by tallforasmurf** [comment]
Does [this section of the doc](http://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#the-bootstrap-process-in-detail) answer this question? If not, explain.

**Comment by misuzu** [comment]
@tallforasmurf 
Is there a reason why parent process not using exec when one-file mode is not used?

**Comment by tallforasmurf** [comment]
One-file and one-folder are the same. One-file is just a one-folder app that is zipped up as a self-extracting archive. When you run it, it unpacks itself to make a one-folder app in temp disk space, and then calls the executable in that folder. So the same bootloader runs in all cases. Its actions are described in the doc section I linked.
