### ISSUE TITLE
Use --clean option alone

### ISSUE THREAD

**Issue by ShyPixie** [pyinstaller/pyinstaller#3391]
I would like to use --clean just like --clean option from distutils after build, to clean temp/cache files, or remove dist folder. Currently it's more like --clean-and-build option.

**Comment by arthurspa** [comment]
Is anyone working on this? If not, I can start.

@htgoebel , as we already have an --clean option that performs a clean and build, what do you think of a `--clean-only` option? This option would remove `dist` folder and do exactly what is done in `PyInstaller/building/build_main.py`  :

```python
    # Clean PyInstaller cache (CONF['cachedir']) and temporary files (workpath)
    # to be able start a clean build.
    if clean_build:
        logger.info('Removing temporary files and cleaning cache in %s', CONF['cachedir'])
        for pth in (CONF['cachedir'], workpath):
            if os.path.exists(pth):
                # Remove all files in 'pth'.
                for f in glob.glob(pth + '/*'):
                    # Remove dirs recursively.
                    if os.path.isdir(f):
                        shutil.rmtree(f)
                    else:
                        os.remove(f)
```

As this --clean-only would not be a build step, I'd add it to `__add_options` in `PyInstaller/__main__.py` instead of `PyInstaller/building/build_main.py`.

**Comment by htgoebel** [comment]
Thanks for working on this.

For cleaning the `dist` directory, there is code already, too. See PyInstaller/building/utils.py.

Some of my thoughts:
1. distutils has a sub command `clean`, not an option (AFAIK) - pyinstaller does not have subcommands. Thus the behavior is different
2. pyinstaller requires a filename, even if `--clean` removes the cache only
   * This is easy to change and shall be done
   * When implementing this, `--clean` should move into PyInstaller/building/build_main.py
3. Do we really need an option `--clean-only` to remove the `build` and `dist` directories?
   * `--clean-only` would require a filename to know which paths to remove Would it even need to run parts of the code, to get e.g. the "name" defined in a spec-file.

     Buh, this would require passing `clean=` to *all* classes used in spec-files and inhibit them executing. I doubt this change is worth teh benefit. What do you think?

What do you think?

**Comment by arthurspa** [comment]
Hey @htgoebel ,

I took a look in the code again and agree that the effort isn't worth the benefit.

**Comment by htgoebel** [comment]
What do you think about moving `--clean` to PyInstaller/building/build_main.py makeing the filename optional, like this(pseudo-code):
```
if options.clean:
    clean-cache()
elif not options.filename:
    parser.error("Required argument missing: filename"=
If options.filename:
   build()
```

**Comment by Legorooj** [comment]
Closing this because it's stale and not being looked at.
