### ISSUE TITLE
Pyinstaller --noconsole is not working

### ISSUE THREAD

**Issue by skysoft999** [pyinstaller/pyinstaller#3392]
I am using pyinstaller to wrap my django project . I'm using sub-process library inside view.py file. I suspect because of this sub-process library i cant run application in no-console mode. What is the solution for this.?
when i remove subprocess part from views file its working as desired. I went through  many discussion about this issue but since im a absolute beginner i couldn't crack solution out.
https://github.com/pyinstaller/pyinstaller/issues/2056

issue:
```
Internal Server Error: /
Traceback (most recent call last):
  File "crumbs_tableau\views.py", line 286, in parser
  File "crumbs_tableau\views.py", line 248, in mac_list
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 403, in run
  File "subprocess.py", line 667, in __init__
  File "subprocess.py", line 905, in _get_handles
  File "subprocess.py", line 955, in _make_inheritable
OSError: [WinError 6] The handle is invalid

During handling of the above exception, another exception occurred:
```

**Comment by hsumerf** [comment]
In Python 2.7 use subprocess like this:
```
DEVNULL = open(os.devnull,"wb")
output = subprocess.check_output(command, shell=True,stderr=DEVNULL,stdin=DEVNULL)

```

In Python 3 use subprocess like this:
```
DEVNULL = subprocess.DEVNULL
output=subprocess.check_output(command,shell=True, stderr = DEVNULL , stdin = DEVNULL )

```

**Comment by htgoebel** [comment]
@hsumerf Thanks for providing this solution
