### ISSUE TITLE
Removing datas from binary

### ISSUE THREAD

**Issue by mouuff** [pyinstaller/pyinstaller#3410]
Hello
I have a binary built with pyinstaller with datas in the binary (built with --add-data and --onefile)
I would like to remove the datas from this binary (without rebuilding it)
How could I achieve that?
It might sounds like a stupid idea but we really need to do that.

Thank you for your awesome project

**Comment by htgoebel** [comment]
PyInstaller does not provide any support for this. You can implement it based on bits and pieces in PyInstaller, but I'm afraid this is quite some effort.
- "extract" the .pkg from the exe, see PyInstaller.building.api.py::EXE.assemble()
- create a copy of the .pkg while not copying files to be stripped (see archiveviewer and PyInstaller.building.api.py::PKG.assemble()
- strip the old pkg from the exe
- append the new pkg to the exec.

Another path would be to
- extract all "top-level" content from the exe using a tool based on archiveviewer, while writing a list of all elements in the archive plus extraction-filename
- write a new spec-file for assembling the EXE passing a list of all elements which shall go into thenew exe.

Hmm, the later seems to be much easier and much less effort.

Good luck!
