### ISSUE TITLE
Problem when code include tensorflow package

### ISSUE THREAD

**Issue by RyanYChen** [pyinstaller/pyinstaller#3411]
When I import tensorflow in my script, pyinstaller can correctly compile script. But I can not run the executable file: segmentation fault occurs.

It only shows:  Segmentation fault (core dumped) , and nothing else is shown. 

My script is really simple:
```
import tensorflow as tf
print("helloworld")
```
and I can run it normally by python. 

What can I do to fix the segmentation fault? 

Environment: 
Ubuntu 16.04
python 3.6
tensorflow: 1.6.0, cpu version
pyinstaller: 3.3.1

**Comment by Overdrivr** [comment]
- Is your tensorflow installation healthy ? Does running this script with python runs fine ?
- Have you tried latest pyinstaller 3.4 ?

**Comment by htgoebel** [comment]
PyInstaller 3.4 has been release a few weeks ago. Please try that one. Also search the open and closed bugs for tensorflow.
