### ISSUE TITLE
pyinstall to exe，the GUI  is different

### ISSUE THREAD

**Issue by hillar1988** [pyinstaller/pyinstaller#3412]
to exe,the GUI looks ugly ,different from the windows form,how to solve this

**Comment by htgoebel** [comment]
Obviously some files are not packages, e.g. Icons, themes, etc. Without more information we are not able to help you. Please look at the https://github.com/pyinstaller/pyinstaller/wiki/Recipes or search the open and closed issue about the gui system you are using.
