### ISSUE TITLE
Symbol not found: _futimens

### ISSUE THREAD

**Issue by abulka** [pyinstaller/pyinstaller#3418]
Creating a pyinstaller one file app based on the simplest possible hello world app, and running the resulting onefile app on a brand new virgin install of high sierra results in 

```
[589] Error loading Python lib '/var/folders/qq/dxz2jqpx09q1d79pl8mrjyxc0000gn/T/_MEIyCfFXj/.Python': dlopen: dlopen(/var/folders/qq/dxz2jqpx09q1d79pl8mrjyxc0000gn/T/_MEIyCfFXj/.Python, 10): Symbol not found: _futimens
  Referenced from: /var/folders/qq/dxz2jqpx09q1d79pl8mrjyxc0000gn/T/_MEIyCfFXj/.Python (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /var/folders/qq/dxz2jqpx09q1d79pl8mrjyxc0000gn/T/_MEIyCfFXj/.Python
```
My proper and more complex app also does this, which is why I was curious and created the simplest app possible in order to reproduce the problem viz:
simplest.py 
```
print('hello')
```
pyinstaller simplest.py --onefile

I used the latest development build of PyInstaller as recommended. 

Running the ``simplest`` onefile app on my seasoned iMac worked fine, however.  But as I say, not in my pure virgin High Sierra install, which is running in a vmware host.  I am trying to test my app assuming my users have no python installed, no nothing installed, which is why I created a vmware high sierra installation.  Why the error?

**Comment by abulka** [comment]
The issue seems to be same as #1191 - that you need to compile and build your app using PyInstaller on an old Mac running an old versions of OSX if you want your app to run on older versions of OSX/MacOS. Sad but true.  

Even a small upgrade to an OS e.g. High Sierra will move its version forward and any apps built by PyInstaller on that upgraded MacOS version will refuse to run on High Sierra that hasn't had that small upgrade.

So get your copy of VMware, create a Mac virtual machine installation of e.g. Mavericks, install your code, Python and PyInstaller in that virtual machine and build your app there - 'in the past'.  Then the resulting app  will work on Mavericks right up to High Sierra. Worked for me and is documented:
http://pythonhosted.org/PyInstaller/usage.html#making-mac-os-x-apps-forward-compatible

**Comment by htgoebel** [comment]
Duplicate of #1191
