### ISSUE TITLE
Problem in Pyinstaller with PyQt5 on Windows 10

### ISSUE THREAD

**Issue by adebisit** [pyinstaller/pyinstaller#3421]
I try to convert my PyQt5 GUI enabled script with pyinstaller, but I always getting a warning saying some APIs are missing. 
Eventually, the EXE generated does not work.

I have tried cx freeze researched solutions but there is no solution that works for me.

Please help me.

I use a windows 10.

**Comment by bjones1** [comment]
Try the branch at #3233 -- that fixes many PyQt5 problems.
