### ISSUE TITLE
Use Something like Virtualenv as the Executable

### ISSUE THREAD

**Issue by jfftck** [pyinstaller/pyinstaller#3425]
I think that most of the issues could be solved by using the same technique that virtualenv uses and have the executable just unpack a completely new virtual environment and run the scripts. 

This could be something that the people working on virtualenv might want to help out with.

This is just a thought, but it should remove many issues related to how pyInstaller is not the same as using Python and running the scripts.

**Comment by htgoebel** [comment]
PyInstaller tries to include a minimal set of required modules, which is opposite to including a complete virtual env. But not everything needed is included in the virtual env, esp. not dependent dlls.
