### ISSUE TITLE
Pyinstaller with python-opencv issue

### ISSUE THREAD

**Issue by shootsoft** [pyinstaller/pyinstaller#3426]
Python: 3.6
pyinstaller: 3.3.1
Windows: 10
macOS: High Sierra 
With virtual environment.

My application uses Qt5, QMediaPlayer, python-opencv.
python-opencv: 3.4.0.12

On windows, it didn't pack `opencv_ffmpeg340.dll`, I somehow figured it out, successfully build it with `--add-data`

```batch
pyinstaller -F -w --icon=res/pluto.ico ^
          --add-data "src\windows;windows" ^
          --add-data "venv/v36/Lib/site-packages/cv2/opencv_ffmpeg340.dll;./"  ^
          --path "C:\Program Files (x86)\Windows Kits\10\Redist\ucrt\DLLs\x86" ^
          --version-file=file_version_info.txt "src\app.py"
```

However, on Mac, the build was success, but application can't be executed:

```bash
pyinstaller --clean -D -w \
        --icon=res/pluto.icns \
        --add-data "src/windows:windows"  \
        "src/app.py" 
```

When launching app in dist\app folder, it throws out

```
/Users/dev/work/github/PlutoVidoeSnapshoter/dist/app/app ; exit;
➜  ~ /Users/dev/work/github/PlutoVidoeSnapshoter/dist/app/app ; exit;
Traceback (most recent call last):
  File "app.py", line 10, in <module>
  File "/Users/dev/work/github/PlutoVidoeSnapshoter/venv/pluto36/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "pluto/ui/player/controllers.py", line 11, in <module>
  File "/Users/dev/work/github/PlutoVidoeSnapshoter/venv/pluto36/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "pluto/common/media/snapshot.py", line 3, in <module>
  File "/Users/dev/work/github/PlutoVidoeSnapshoter/venv/pluto36/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/cv2/__init__.py", line 4, in <module>
  File "/Users/dev/work/github/PlutoVidoeSnapshoter/venv/pluto36/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ImportError: dlopen(/Users/dev/work/github/PlutoVidoeSnapshoter/dist/app/cv2.cv2.so, 2): Symbol not found: __ZN10QByteArray11shared_nullE
  Referenced from: /Users/dev/work/github/PlutoVidoeSnapshoter/dist/app/QtTest
  Expected in: /Users/dev/work/github/PlutoVidoeSnapshoter/dist/app/QtCore
 in /Users/dev/work/github/PlutoVidoeSnapshoter/dist/app/QtTest
[2347] Failed to execute script app
```

I think the key error message is 

```
ImportError: dlopen(/Users/dev/work/github/PlutoVidoeSnapshoter/dist/app/cv2.cv2.so, 2): Symbol not found: __ZN10QByteArray11shared_nullE
```

I checked cv2.cv2.so, it is the same size of original file 
venv/pluto36/lib/python3.6/site-packages/cv2/cv2.cpython-36m-darwin.so

**Comment by shootsoft** [comment]
Two issues:
1. On windows, it didn't pickup a required dll of opencv `opencv_ffmpeg340.dll`
2. On Mac, the built app can't run (neither `-F` nor `-D`).

**Comment by htgoebel** [comment]
Thanks for tracking this down to which file is missing. This looks like a hooks would be great! :-)

1. You need to add the .dll as `--add-binary' to make PyInstaller collect the dependencies of this .dll, too.
2. Maybe some dynlib ist missing here, too. `strace -f -e trace=file -o $TMP/trace.txt mxapp.app` is your friend.

We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by shootsoft** [comment]
Thanks @htgoebel 

Not found the root cause on Mac yet, but indeed you introduced a good friend to me `dtruss` (I'm using mac)

**Comment by shootsoft** [comment]
@htgoebel 

I found the issue, looks like the issue is in opencv-python, I also got `__ZN10QByteArray11shared_nullE ` as https://stackoverflow.com/questions/46050377/unable-to-bundle-opencv-and-pyqt5

In my case, I tried an earlier version opencv-python==3.3.0.9 it works.

**Comment by htgoebel** [comment]
Glad you solved it :-)

**Comment by i2023u** [comment]
Can anyone fix this issue ? There is no 3.3.09 version available anymore. It's almost a year still I'm having a problem with cv2 __ZN10QByteArray11shared_nullE Referenced error.

**Comment by olivierfriard** [comment]
Same issue with Python 3.7, OpenCV 4.0.0.21 and PyQT5.12.

**Comment by skvark** [comment]
Multiple different Qt versions don't work together due to symbol clashes. This is a known issue in Qt if Qt has not been built with a custom namespace. Opencv-python ships with Qt4 binaries (https://github.com/skvark/opencv-python/issues/46). 

If you do not need OpenCV imshow / GUI functionality, you can most probably avoid the issue by installing the headless version of opencv-python: ``opencv-python-headless`` which does not include Qt. The reason why version 3.3.0.9 works is that Qt was included in the pre-built wheels after that release (https://github.com/skvark/opencv-python/releases).

**Comment by olivierfriard** [comment]
Installing `opencv-python-headless` fixes the problem. Now it is working with PyQt5 (5.12) and OpenCV 4.0.0.21.
Thank you
