### ISSUE TITLE
libncurses not bundled

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#3427]
Trying to make sense of https://github.com/borgbackup/borg/issues/3732 .

This is pyinstaller 3.2.1, python 3.5.4 - build running on Debian "Wheezy" 7, 64bit.

What I am unsure about: is the correct fix to bundle libncurses and libncursesw?

Is there a dependency discovery issue in pyinstaller so that this does not automatically get bundled?

borg does not use ncurses, so I guess this is python itself that requires this.

**Comment by htgoebel** [comment]
I commented there. According my analysis to be found there) this is an issue outside of PyInstaller. So I'm closing this now. If new insights appear, I'll reopen.
