### ISSUE TITLE
Hidden imports not found

### ISSUE THREAD

**Issue by kkar** [pyinstaller/pyinstaller#3431]
```
135 INFO: checking Analysis
135 INFO: Building Analysis because out00-Analysis.toc is non existent
135 INFO: Initializing module dependency graph...
140 INFO: Initializing module graph hooks...
148 INFO: Analyzing hidden import 'binascii,'
151 ERROR: Hidden import 'binascii,' not found
152 INFO: Analyzing hidden import 'code,'
156 ERROR: Hidden import 'code,' not found
156 INFO: Analyzing hidden import 'os,'
159 ERROR: Hidden import 'os,' not found
161 INFO: Analyzing hidden import 'platform,'
161 ERROR: Hidden import 'platform,' not found
162 INFO: Analyzing hidden import 'random,'
166 ERROR: Hidden import 'random,' not found
167 INFO: Analyzing hidden import 're,'
169 ERROR: Hidden import 're,' not found
171 INFO: Analyzing hidden import 'select,'
172 ERROR: Hidden import 'select,' not found
173 INFO: Analyzing hidden import 'socket,'
175 ERROR: Hidden import 'socket,' not found
176 INFO: Analyzing hidden import 'struct,'
179 ERROR: Hidden import 'struct,' not found
179 INFO: Analyzing hidden import 'subprocess,'
184 ERROR: Hidden import 'subprocess,' not found
184 INFO: Analyzing hidden import 'sys,'
190 ERROR: Hidden import 'sys,' not found
191 INFO: Analyzing hidden import 'threading,'
201 ERROR: Hidden import 'threading,' not found
201 INFO: Analyzing hidden import 'time,'
204 ERROR: Hidden import 'time,' not found
```

None of the hidden import that i give in CMD is found. I am trying to create a single executable (**--onefile**) with **--hidden-import** for each of them. I am using **Win10** with **Python 2.7**, and the latest version of PyInstaller.

**Comment by htgoebel** [comment]
As far as I can the, all of these are modules from the standard library. Why are you passing them as hidden-imports? Anyway, this look like your environment is severely damaged.

**Comment by kkar** [comment]
@htgoebel I am passing them as hidden-imports because i "exec()" my script after base64 decoding. I suppose I should pass them to help PyInstaller include them. Btw, when I execute the script as a ".py", it works well. Should it run normally if my environment were damaged?

Thank you for the quick answer.

**Comment by htgoebel** [comment]
> I am passing them as hidden-imports because i "exec()" my script after base64 decoding. I suppose I should pass them to help PyInstaller include them.

IC. Yes, his is correct.

Okay, now I see: you have commas appended to these module names.

**Comment by kkar** [comment]
In the source code? Uhm, nope. I don't. I import one module at each line...
