### ISSUE TITLE
pyi-archive_viewer file format in EXE container is not pyc?

### ISSUE THREAD

**Issue by bodagetta** [pyinstaller/pyinstaller#3435]
My apologies for posting this an issue, but I'm not sure where else to go for help.

I have lost the source to a project that I compiled using pyinstaller and I'm trying to recover it. It was packaged as a single folder executable.

I was able to use pyi-archive_viewer to list the contents of the EXE file, shown below
```
[(0, 283, 371, 1, 'm', 'struct'),
 (283, 1174, 2025, 1, 'm', 'pyimod01_os_path'),
 (1457, 4281, 9523, 1, 'm', 'pyimod02_archive'),
 (5738, 6077, 15633, 1, 'm', 'pyimod03_importers'),
 (11815, 1670, 3786, 1, 's', 'pyiboot01_bootstrap'),
 (13485, 477, 672, 1, 's', 'pyi_rth_win32comgenpy'),
 (13962, 268, 339, 1, 's', 'pyi_rth_pkgres'),
 (14230, 440, 624, 1, 's', 'pyi_rth__tkinter'),
 (14670, 347, 449, 1, 's', 'pyi_rth_mplconfig'),
 (15017, 260, 315, 1, 's', 'pyi_rth_mpldata'),
 (15277, 659, 1010, 1, 's', 'pyi_rth_qt5'),
 (15936, 460, 633, 1, 's', 'pyi_rth_qt5plugins'),
 (16396, 5785, 11626, 1, 's', 'EGM-IMPACT2'),
 (22181, 6719096, 6719096, 0, 'z', 'out00-PYZ.pyz')]
```

I am able to open the out00-PYZ.pyz file and extract pyc files from it then decompile them using uncompyle6. However, my main file of interest is EGM-IMPACT2 at the top level of the archive. I've tried extracting it to a pyc file, but then uncompyle6 gives the following error

```
c:\Users\micha\OneDrive\Desktop\main>uncompyle6 EGM-IMPACT.pyc
Traceback (most recent call last):
  File "c:\users\micha\appdata\local\programs\python\python35\lib\site-packages\xdis\load.py", line 106, in load_module
    version = float(magics.versions[magic][:3])
KeyError: b'\xe3\x00\x00\x00'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\micha\AppData\Local\Programs\Python\Python35\Scripts\uncompyle6-script.py", line 11, in <module>
    load_entry_point('uncompyle6==2.11.5', 'console_scripts', 'uncompyle6')()
  File "c:\users\micha\appdata\local\programs\python\python35\lib\site-packages\uncompyle6\bin\uncompile.py", line 163, in main_bin
    **options)
  File "c:\users\micha\appdata\local\programs\python\python35\lib\site-packages\uncompyle6\main.py", line 146, in main
    decompile_file(infile, outstream, showasm, showast, showgrammar)
  File "c:\users\micha\appdata\local\programs\python\python35\lib\site-packages\uncompyle6\main.py", line 63, in decompile_file
    source_size) = load_module(filename, code_objects)
  File "c:\users\micha\appdata\local\programs\python\python35\lib\site-packages\xdis\load.py", line 110, in load_module
    (ord(magic[0])+256*ord(magic[1]), filename))
TypeError: ord() expected string of length 1, but int found
```

Given that uncompyle6 works on other files in the pyz archive, this makes me wonder if the EGM-IMPACT file is actually **not** a pyc file.

If I open it with a text editor I can see my function names, but it looks like compiled code otherwise.

Thank you for your time and consideration.

**Comment by htgoebel** [comment]
Please gt in touch with the authors of that tool

**Comment by bodagetta** [comment]
I should have been more clear

My question is about pyi-archive_viewer which is part of pyinstaller.

Is there a way to tell the file format of the files in the archive? There are no extensions listed.

**Comment by htgoebel** [comment]
If it looks like byte-code, it is byte-code :-) Things changed in the last 10 years, in earlier days the script was source, later byte-code. Maybe the magic header is missing, while AFAIK we never stripped it. Try to load the file with `marshal.load()` - if you don't know the Python version you used, play with `xdist.unmarshal.load_code()`. Good luck
