### ISSUE TITLE
"Edit on GitHub" leads to 404 - page not found

### ISSUE THREAD

**Issue by Stevoisiak** [pyinstaller/pyinstaller#3440]
The "Edit on Github" link for [PyInstaller's documentation](https://pyinstaller.readthedocs.io/en/stable/index.html) directs users to a _404 - Page not found_ error.

### Steps to reproduce

1. Navigate to https://pyinstaller.readthedocs.io/en/stable/.
2. Click **Edit on GitHub** in the top-right corner.

### Expected result

The link should point to the "Edit" page for the current file on GitHub. (https://github.com/pyinstaller/pyinstaller/edit/master/doc/index.rst)

### Actual result

Link points to a _404 - Page not found_ error. (https://github.com/pyinstaller/pyinstaller/blob/6ed6dd2f52f3d4409292a484e8f19a8ce1daef43/doc/index.rst)

**Comment by htgoebel** [comment]
Thanks for reporting. I was not able to fix this, as this seams to be a bug at readthedocs. I opened an issue for this https://github.com/rtfd/readthedocs.org/issues/3926

As an workaround I changes the config at readthedocs so hat the link https://pyinstaller.readthedocs.io/ redirects to v.3.3.1.

**Comment by bwoodsend** [comment]
This is resolved now.
