### ISSUE TITLE
prelink breaks pyinstaller binaries on pyinstaller >= 3.3

### ISSUE THREAD

**Issue by ningirsu** [pyinstaller/pyinstaller#3441]
This issue was already reported and fixed in #1812, but it seems to still appear on pyinstaller >= 3.3.0

```
(AgentDaemon)  moutix@pistache ~/project/test $ cat a.py 
print("hello")
(AgentDaemon)  moutix@pistache ~/project/test $ pyinstaller -F a.py 
106 INFO: PyInstaller: 3.3.1
106 INFO: Python: 2.7.12
106 INFO: Platform: Linux-4.14.9-041409-generic-x86_64-with-LinuxMint-18.3-sylvia
106 INFO: wrote /home/moutix/project/test/a.spec
109 INFO: UPX is not available.
109 INFO: Extending PYTHONPATH with paths
['/home/moutix/project/test', '/home/moutix/project/test']
109 INFO: checking Analysis
112 INFO: checking PYZ
113 INFO: checking PKG
113 INFO: Bootloader /home/moutix/.virtualenvs/AgentDaemon/local/lib/python2.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
113 INFO: checking EXE
114 INFO: Rebuilding out00-EXE.toc because a missing
114 INFO: Building EXE from out00-EXE.toc
114 INFO: Appending archive to ELF section in EXE /home/moutix/project/test/dist/a
120 INFO: Building EXE from out00-EXE.toc completed successfully.
(AgentDaemon)  moutix@pistache ~/project/test $ ./dist/a 
hello
(AgentDaemon)  moutix@pistache ~/project/test $ sudo prelink dist/a 
(AgentDaemon)  moutix@pistache ~/project/test $ ./dist/a 
[26886] Cannot open self /home/moutix/project/test/dist/a or archive /home/moutix/project/test/dist/a.pkg
```

**Comment by htgoebel** [comment]
`prelink` adds another section at the end of the executable, thus PyInstallers bootloader code does not find the frozen data, which is expected at the end of the file. Solving this would require to include an ELF-file reader into the bootloader. I'm afraid this will not happen anytime soon (except if somebody is [sponsoring the development](http://www.pyinstaller.org/donate.html)). If anybody wants to implement this: contributions are welcome! Starting points could be https://wiki.osdev.org/ELF_Tutorial and https://github.com/eklitzke/parse-elf.

Possible work-arounds:
1. Prelink the bootloader prior to freezing: prelink PyInstaller/bootloader/Linux*/*
2. In your spec-file use `EXE(…, append_pkg=False)` (this is an undocumented but supported feature). Mind that you need to run `pyinstaller a.spec` then.
