### ISSUE TITLE
Environment variable support for runtime_tmpdir

### ISSUE THREAD

**Issue by plu83** [pyinstaller/pyinstaller#3457]
Hi,

I have a Windows  taskbar application which is intended to run continuously and it has been victim to the issue of missing icon files due to assumed temp folder clean up (https://github.com/pyinstaller/pyinstaller/issues/3301).  As such, I would like to use the runtime_tmpdir argument to extract the content of the bundle into a path built from the USERPROFILE environment variable.  Attempts at specifying the environment variable have not worked, so can anyone confirm that it does not support environment variable expansion?

Thanks,
Peter

**Comment by htgoebel** [comment]
Yes, it does not support environment variable expansion
