### ISSUE TITLE
Using image files in my app

### ISSUE THREAD

**Issue by frakman1** [pyinstaller/pyinstaller#3459]
On Windows 7 64bit . Python 3.6.4. PyInstaller 3.3.1

[This is my github project ](https://github.com/frakman1/lifx-lan-gui)that I am trying to use pyinstaller with.

I have a question about using supporting image files for my python app. Note, the file happens to be an image file, it could be any local file that my script needs to open.

My app/script expects an image file to be in its current directory eg. `bulb_off.gif`. Everything works when I run the python script normally as a python script (not a binary). However, when I use pyinstaller to create a binary, the resultant binary can no longer find the image file. 

I get the error message:

`Image C:\Users\username\Documents\bulb_off.gif does not exist`

The above path is where the binary happens to be running from.

I use this .spec file to generate the binary:

https://github.com/frakman1/lifx-lan-gui/blob/master/pyinstaller/win_lights.spec

```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['lights.py'],
             pathex=['c:\\dev\\lifx-lan-gui','C:\\Users\\username\\AppData\\Local\\Programs\\Python\\Python36\\Lib\\site-packages\\scipy\\extra-dll'],
             binaries=[],
             datas=[('bulb_off.gif', 'bulb_on.gif')],
             hiddenimports=['scipy._lib.messagestream'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='lights',
          debug=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True , icon='lifxgui.ico')
```

I know there is a clever way to read an environment variable and extract the image from there but if I do that, then the original python script wouldn't be able to find the file. The idea is that I want those files to be part of the binary and the embedded script just open it as if it was in that folder. 

Sorry if I am missing something obvious here.

**Comment by htgoebel** [comment]
Please read the manual.

**Comment by frakman1** [comment]
Can you please be more specific/helpful?
