### ISSUE TITLE
windowed option not working with registry

### ISSUE THREAD

**Issue by Ahmed7fathi** [pyinstaller/pyinstaller#3460]
Trying to execute this script to add key in registry its working fine in python and pyinstaller also but when i add -w option to hide the console its not working i mean the program ran fine without any error messages but not adding the key in registry 

```
import subprocess

try:
    reg_key = 'REG ADD "HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\Run" /V "SFX" /t REG_SZ /F /D "C:\Program Files\SFX Compiler\SFXCompiler.exe"'
    subprocess.Popen(reg_key, shell=True, stdout=subprocess.PIPE)
except Exception as error:
    print(error)
```

how  i build my program ?
`pyinstaller -F -w key.py`

I'm using windows 7 32bit
python 3.4.3
pyinstaller 3.4.dev0+eea47968c

i appreciate you guys and thanks

**Comment by htgoebel** [comment]
Some idea
- Why are you passing `shell=true`? Maybe you shell-string is wron. BTW: Passing a list of arguments is preferred anyway.
- To find out whether this is related to the subprocess call or to actually setting the registry-key  please try using pywin32 (or such) to set he reg key.
- Did you read the "subprocess" recipe in the wike?

**Comment by Ahmed7fathi** [comment]
you are right i just did the same steps with winreg and created the key without any troubles 
but i need to make the shell true actually its not my program its part of it and i executing more than one command in subporcess 
so what should i do  
and why shell-string run in interpreter without any problems
i guess i should use winreg in this step but i don't wanna import more libraries  the size of program gets big

**Comment by htgoebel** [comment]
> you are right

On which o the three points? What are the answers to all of them?

Possible solutions:
- Run one command after each other using subprocess.
- Write out a .at file and and execute that.

**Comment by Ahmed7fathi** [comment]
> On which o the three points? What are the answers to all of them?

here and  i used winreg: 

> try using pywin32 (or such) to set he reg key.

unfortunately i tried the both Possible solutions and not working
