### ISSUE TITLE
Bug with windowed mode and subprocess.check_output

### ISSUE THREAD

**Issue by xp4xbox** [pyinstaller/pyinstaller#3462]
This is a weird bug, but after months I was able to track it down to this line of code while running the program in **windowed mode** (not console mode). 

`command = subprocess.check_output("tasklist", shell=True)`

This line crashes the program every time.

UPDATE: This seems to crash using `subprocess.Popen` as well but only in this certain spot. As so I feel this is too rare to happen again so I will close this.

**Comment by htgoebel** [comment]
Sad you removed the original error description, since this could be the same as  #3460.

If I understand your update correctly, neither `shell=False` nor running a different program would solve the issue?!
