### ISSUE TITLE
PyInstallerImportError: Failed to load dynlib/dll

### ISSUE THREAD

**Issue by dineshkumarsr** [pyinstaller/pyinstaller#3463]
Hi,

Here is the link https://github.com/cztomczak/cefpython/b...ython.py.I am running ubuntu 16.04 and attempting to build an application that uses CEFPython3. Everything compiles fine, but when I try to create exec file using pyinstaller then I execute it, getting an error of libcef.so: cannot open shared object file: No such file or directory.

**Version using:**

`CEF Python 57.0 
Python 2.7.12 64bi
t wxPython 4.0.0 gtk2 (phoenix)
 pyinstaller 3.3.1`

**Create Exec file:**

`ex: pyinstaller --onefile wxpython.py`

**Error:**

```
 File "ESSBMain.py", line 5, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "ESSBFrame.py", line 7, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "cefpython3/__init__.py", line 45, in <module>
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll '/tmp/_MEIslUgPM/cefpython3/libcef.so'. Most probably this dynlib/dll was not found when the application was frozen.
```

**Comment by htgoebel** [comment]
There is a quite clear error message:
> Failed to load dynlib/dll '/tmp/_MEIslUgPM/cefpython3/libcef.so'. Most probably this dynlib/dll was not found when the application was frozen.

Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by dineshkumarsr** [comment]
I have installed the development version `sudo pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz` . Package my program into --onedir mode and tried. Same error retaining. I am new to this technology .please help on this issue.

**Comment by tallforasmurf** [comment]
The documentation page [Listing Hidden Imports](http://pyinstaller.readthedocs.io/en/v3.3.1/when-things-go-wrong.html#listing-hidden-imports) should also be helpful here.
