### ISSUE TITLE
Infinite loop after using pyinstaller with qtconsole

### ISSUE THREAD

**Issue by kakirolooooo** [pyinstaller/pyinstaller#3468]
I'm trying to make a .exe of an application created with pyqt and qtconsole. I get the same error with my code as with this example -> https://github.com/jupyter/qtconsole/blob/master/examples/embed_qtconsole.py
Here is a picture of the execute.
![38863687-b6e3900c-4238-11e8-88e8-69d2a83e744b](https://user-images.githubusercontent.com/12657528/38915800-4eae880e-42e5-11e8-9a21-064f936ffaa6.png)

The program works fine executing the code in the normal way. I tried to add this line: multiprocessing.freeze_support() like the wiki says but without any effect
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing

Can anybody help?
So much thanks

**Comment by tallforasmurf** [comment]
What is this QtKernelManager? I cannot find any mention of it in the [Qt class reference](http://doc.qt.io/qt-5/classes.html). Also don't see it at pypi. So what is it and from where?

**Comment by kakirolooooo** [comment]
@tallforasmurf here you got https://github.com/jupyter/qtconsole/blob/master/qtconsole/manager.py its a part of the qtconsole proyect -> https://github.com/jupyter/qtconsole I also asked them but...they said that cannot help me...

**Comment by hansonap** [comment]
I can verify this issue. Has there been any more progress with this issue?

Thanks!

**Comment by bjones1** [comment]
Not that I'm aware of. I'd encourage someone who needs this (@kakirolooooo or @hansonap?) to write a hook to support it. I'm closing this, waiting for a PR containing this hook.

**Comment by kakirolooooo** [comment]
I'm asking for help because i don't know whats the problem and how to work around it. How i'm going to write a hook to support it? :/

**Comment by hansonap** [comment]
Took another stab at this, and while it didn't express the infinite loop symptom, the frozen app would fail to run, resulting in the following error:
`ModuleNotFoundError: No module named 'qtconsole.client'`

I was able to solve it using a hook, and will make a merge request on GitHub (unless there is a better way).

While trying to diagnose, I established the following:
- qtconsole.client contains QtKernelClient which inherits from QtKernelClientMixin and ThreadKernalClient. 
- QtKernelClient's signature is `class QtKernelClientMixin(MetaQObjectHasTraits('NewBase', (HasTraits, SuperQObject), {})):`. 
- I don't know the qtconsole code well, but that looks complex enough to be causing the issue. 
- From our script, QtKernelClient is referenced in qtconsole.manager.QtKernelManager with the class call of `client_class = DottedObjectName('qtconsole.client.QtKernelClient')`. This might also be the route cause.

The hook is for qtconsole.manager and contains the hidden import qtconsole.client.

**Comment by arielja87** [comment]
So I'm also suffering from this. adding qtconsole.client as a hidden import solved the ModuleNotFoundError, but i still get an infinite "Kernel Died" loop. @kakirolooooo did you ever have any luck with this?

**Comment by hansonap** [comment]
I was multitasking, using [PowerShell](https://github.com/vors/jupyter-powershell) kernel while debugging. I thought I had solved all issues, but after switching back to the IPython kernel, the infinite loop still persist. I believe the pyinstaller hook I proposed does fix the freezing issue with qtconsole, and that the infinite loop issues is most likely an IPython kernel issue. @arielja87, I won't be able to spend much time on this, but perhaps you can open an issue (mention myself so I can track it please!) with the IPython team?

I haven't had time lately to work on this, but my new approach will to try and embed just the kernel(s) in my frozen application, then freeze just Jupyter (there are several links of people doing this successfully). Another approach would be to check out [Briefcase](https://pybee.org/project/projects/tools/briefcase/), yet another distribution method.

Full list of [kernels].(https://github.com/jupyter/jupyter/wiki/Jupyter-kernels)

**Comment by arielja87** [comment]
@hansonap thanks for the response. Yeah @kakirolooooo opened this same issue https://github.com/jupyter/qtconsole/issues/281 with jupyter qtconsole, but apparently it was out of scope for them as well. I may try a different kernel and see if the issue persists. I was just using "python3"  ID as in the  original example. I've used IPython for years, but this is the first time I'm attempting to incorporate it into an app that I'm developing.

**Comment by kakirolooooo** [comment]
Hi! I didn't have any luck. It's a little out of my limits but maybe this time we can have some help!
