### ISSUE TITLE
How to call Verbose Imports?

### ISSUE THREAD

**Issue by dineshkumarsr** [pyinstaller/pyinstaller#3469]
By pass a -v (verbose imports) flag to the embedded Python interpreter. Have given in documentation.
I have tried with `pyinstaller -v wxpython.py`. It was displaying pyinstaller version. I am new to python, I don't know how to find these hidden imports, build the app with the -v flag.

**Comment by tallforasmurf** [comment]
This is **exactly** the kind of question that should be asked on the [PyInstaller email list](https://groups.google.com/forum/#!forum/PyInstaller). Issues are for bugs.

Ask your question on the email list and someone will answer it there.

**Comment by zxpeter** [comment]
I tried to add the fllowing lines into xxx.spec (you can generate this file after run pyinstaller xxx.py and then delete the build/ and dist/ folders, re-run pyinstaller xxx.spec)
options = [ ('v', None, 'OPTION'), ('W ignore', None, 'OPTION') ]
a = Analysis( ...
            )
...
exe = EXE(pyz,
      a.scripts,
      options,   <--- added line
      exclude_binaries=...
      )
