### ISSUE TITLE
Packaged program fails to execute - MACOSX

### ISSUE THREAD

**Issue by JoshMB8** [pyinstaller/pyinstaller#3473]
Hi I'm currently having a problem with a program that I am packaging on MacOSX.
I have successfully packaged the same program on a Windows 10 machine without any problems.
I am packaging from Anaconda on both systems using the same environment.
The mac is OS High Sierra Version 10.13.4

I seem to be able to package the program on the mac, creating the build and dist directories. But when I then go into the dist directory and try to run my 'main' (the Unix executable created). A terminal window appears runs for a moment and then returns the message: "Failed to execute script main"
The original code does run successfully without an issue so I am a bit stumped considering that I managed to get a packaged version to work on windows. 

Here is the run log for packaging:
[PyInstaller_Run_Log.txt](https://github.com/pyinstaller/pyinstaller/files/1927418/PyInstaller_Run_Log.txt)

Here is the Error I get when I run main:
[Running_main.txt](https://github.com/pyinstaller/pyinstaller/files/1927425/Running_main.txt)

And here is my warnmain file if it helps:
[warnmain.txt](https://github.com/pyinstaller/pyinstaller/files/1927426/warnmain.txt)

I may be missing something obvious but any help would be appreciated. 
I am aware that in the run-log there is a runtime error for matplotlib and python about python not being a framework but all solutions I have googled do not seem to make any difference.

Thanks, 
Josh.

**Comment by tallforasmurf** [comment]
I have no idea, but a couple of debugging tips: one, open the MacOS Console app (in Applications/Utilities), click "Clear Display" and run your app. Any MacOS errors will be displayed there. (It probably quits with a return code of 255.) Two, bundle with the `--debug` option which gets you more detailed messages from the bootloader. And maybe try the Python [run time option `-v`](http://pyinstaller.readthedocs.io/en/stable/spec-files.html#giving-run-time-python-options) to see which module is last loaded.

**Comment by JoshMB8** [comment]
@tallforasmurf thanks for the advice. I had run the --debug option in my packaging of the program but it was not really giving any useful information when I ran the Unix executable. 

I will definitely try the console and run time options you have suggested. 
Annoyingly I carried on looking for solutions on google, tried a couple, and annoyingly now both my matplotlib and pandas have somehow gotten corrupted. So will be starting again form scratch. 

I'll post back with any new info once I've sorted it all out.

**Comment by JoshMB8** [comment]
So starting from scratch with a new anaconda install an env seems to have progressed things... a bit... 
I ended up having to build and install pandas, scikit-image, and seaborn from source (as the latter two require pandas and tried to install a separate version).

Ran pyinstaller again with --debug option and I now have a new error I haven't come across before...

> AttributeError: type object 'cytoolz.itertoolz.remove' has no attribute '__reduce_cython__' 

[error_log.txt](https://github.com/pyinstaller/pyinstaller/files/1931791/error_log.txt)

If anyone has and thoughts/ advice for fixing this that would be great.

Thanks,
Josh

**Comment by tallforasmurf** [comment]
The `error_log.txt` shown above ends in a Python traceback. That's typical; and if you look in the Console app, that's when you'd see the app started and then ended with error code 255.

That traceback pointed to "cytoolz", which [looks like a mess of Cython](https://github.com/pytoolz/cytoolz), which is very likely to be doing sneaky imports that PyInstaller can't see. Oh wait, there is [a hook for it](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-cytoolz.itertoolz.py). I wonder if it is out of date ("Tested with cytoolz 0.9.0"). Anyway how could uninstalling it help, doesn't your code need it?

But if we are back to the "original" error, build with `--debug` and look for a traceback, similar to what you showed in `error_log.txt`.

**Comment by JoshMB8** [comment]
The cytoolz thing is a bit odd to me too. I don't actually have anywhere, in my code, that I use it... Probably be a dependency for another package so I best reinstall it and use the hook.

With the original error issue. I did package with `--debug` and what you see in `Running_main.txt` is what is given when run from terminal. You can see why I don't know what to do as even with `--debug` there is no traceback.

**Comment by JoshMB8** [comment]
Ran with console open but couldn't see anything useful. I'm not really used to Mac though.
I'll keep cracking away at it and post if I find out anything of use or a solution. 
Thanks for the help.

**Comment by taosean** [comment]
@JoshMB8 Hi, did you solve the problem? I have the same error `AttributeError: type object 'cytoolz.itertoolz.remove' has no attribute 'reduce_cython'` as yours when I was using `import caffe`. Below is my trackback, do you have any suggestions?
![default](https://user-images.githubusercontent.com/17960909/42433287-3a791264-8381-11e8-81f0-ef0a4e63c6f9.PNG)

**Comment by JoshMB8** [comment]
@taosean Hi, sorry for the delay in my reply. I didn't really get to a conclusion on this one unfortunately. I tried adding cytoolz.itertoolz.remove as a hidden import but to no success... You could try this and see if it helps? 

In the end, due to deadlines, I had to give up and ended up using py2app instead. When I have some more free time I will likely come back to this in PyInstaller and try give updates/ findings.
