### ISSUE TITLE
Unable to access jarfile 

### ISSUE THREAD

**Issue by Jaquedeveloper** [pyinstaller/pyinstaller#3480]
# python 3.6.5
    # java 1.8.0_144

I am trying to generate an executable which uses tabula-py lib. This library requires a jar file, tabula-1.0.1-jar-with-dependencies, which I have in my file.py folder.
    
    # this is for pandas lib
    def get_pandas_path():
        import pandas
        pandas_path = pandas.__path__[0]
        return pandas_path

    dict_tree = Tree(get_pandas_path(), prefix='pandas', excludes=["*.pyc"])
    a.datas += dict_tree
    a.binaries = filter(lambda x: 'pandas' not in x[0], a.binaries)

    # this is for tabula-py
    jar = 'tabula-1.0.1-jar-with-dependencies'
    jar_path = 'C:\\Users\\jaquedeveloper\\Documents\\freelancer\\bot\\' + jar
    coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               [(jar, jar_path, 'PKG')],
               strip=None,
               upx=True,
               name='test')

Still, the error persists.
When I run my code from command line, the function read_pdf(), from tabula-py, which uses the java jar, works all right, perfectly.

But when I generate the executable with pyinstaller spec command, it fails to execute this function, giving the error below:
**Unable to access jarfile ** C:\\Users\\jaquedeveloper\\AppData\\Local\\Temp\\_MEI58442\tabula\tabula-1.0.1-jar-with-dependencies.jar

How can I import the jar from a specific path to the executable file, instead of using _MEI folder?
The file is not under this folder, nor the tabula folder exists.
I have the file under the same folder of the executable file.How can I force the script to use it?

Same issue is repported here:
https://github.com/chezou/tabula-py/issues/22

And here:
https://stackoverflow.com/questions/44516039/how-to-build-exe-for-python-3-5-3-6-if-possible

**Comment by htgoebel** [comment]
1) Why are you hacking your own hook for pandes? Does the one provided not work?
2) For adding data-files, please read the manual https://pyinstaller.readthedocs.io/en/latest/spec-files.html#adding-data-files
3) > How can I import the jar from a specific path to the executable file, instead of using _MEI folder?

   This question needs to go to the tabule-py project.

**Comment by Jaquedeveloper** [comment]
1 - When I compile and run the .exe file, if it has pandas, it does'nt works. I've found this workaround at stackoverflow and included in my .spec file.

2-I am not sure if it is a data file. I believe it is a 'java executable' file, or similar, since tabula-py is a java wrapper.

3- Ok.

**Comment by Jaquedeveloper** [comment]
I dont believe this is a tabula-py issue, since when I run it via command line, the script works perfectly well. However, after I generate the .exe file, using the same machine, same everything, running the .exe file does'nt work at all.

**Comment by htgoebel** [comment]
2. For PyInstaller this is a data file. Please read the manual.
3. You are asking about whether *tabular-py* is able to search or import this file from a different place. it is not PyInstaller importing it, it is *tabluar-py*. Thus you need to check with them. If you know how you wan make *tabular-py* search the jar-file at certain places or how to tell it where to search, *then* you can see how *you* can make you application to do this.

Anyway. This discussion should be continued on the mailinglist. This is an issue tracker, no discussion forum.

**Comment by tresormhd** [comment]
@indiancharlzz  i got the same error , do you have any solution to solve this ??

**Comment by bleirdalag** [comment]
I had this error and fixed it by specifically downloading tabula-1.0.4-jar-with-dependencies.jar from https://github.com/tabulapdf/tabula-java/releases/ and moving it into the tabula/ directory (previously the directory only contained a more general 'tabula.jar'  file)
