### ISSUE TITLE
Work with other Python packages

### ISSUE THREAD

**Issue by ShuaiW** [pyinstaller/pyinstaller#3482]
Is there a way to work with packages other than those listed here (https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages)?

**Comment by ShuaiW** [comment]
@htgoebel

**Comment by htgoebel** [comment]
This is an issue-tracker, not a froum! This kind of questions should go to the mailinglist. But yes, as it is written there: "Most packages will work out of the box with PyInstaller.".
