### ISSUE TITLE
pyaudio issue with PyInstaller

### ISSUE THREAD

**Issue by melzoghbi** [pyinstaller/pyinstaller#3488]
Hi,
I am using pyinstaller to compile my app. i have a direct import on my main.py that import pyadio package. 

When i try to run the app, I get this error:

No module named 'pyaudio'

How can i solve this?

**Comment by htgoebel** [comment]
As the issue template stated, 

*    follow all the instructions in our "If Things Go Wrong" Guide
    (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

*    make sure everything is packaged correctly
    https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

All further questions regarding this should go to the mailingslist. This is not a support forum, but an issue tracker.
