### ISSUE TITLE
Run two instances of an executable simultaneously?

### ISSUE THREAD

**Issue by 2press** [pyinstaller/pyinstaller#3490]
Hello,
is it possible to somehow run two instances of the same executable that was generated with pyinstaller as a on-file program simultaneously?

For me on Window 10, it only works if I make a distinct copy of the executable.

**Comment by htgoebel** [comment]
Yes this is possible. Buld with `--debug` and see that the files are extracted to different locations. If this is not the case, please report more details here.

BTW: This is a support questions. Please ask this on the mailingslist in future. Thanks.
