### ISSUE TITLE
Statically linked single-file?

### ISSUE THREAD

**Issue by elad** [pyinstaller/pyinstaller#3497]
This isn't as much as a problem as it is a question. I'm sure the subject of producing a statically linked single binary has come up in the past. I'm almost sure I saw an issue about it... but couldn't find it now. Are you considering this option as a feature for PyInstaller? Are there any showstoppers or reasons not to implement it?

**Comment by htgoebel** [comment]
This is an issue-tracker. Questions shall be discussed on the mailinglist.
