### ISSUE TITLE
AttributeError: 'str' object has no attribute 'items'

### ISSUE THREAD

**Issue by 2607861760** [pyinstaller/pyinstaller#3507]
Using python36+pyqt5 development, there are multiple files, a master file, and pyinstaller3.3.1 package.
Package command pyinstaller -F filename file name file name
Wrong RecursionError: maximum recursion depth exceeded
The solution adds import sys sys.setrecursionlimit (5000) in the generated.Spec file.
Generating the EXE file
Click on EXE file times wrong Fatal Error! Failed to execute script

Update pyinstaller:>pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Pack
Report errors：
File "f:\anaconda\lib\site-packages\PyInstaller\hooks\pre_safe_import_module\hook-setuptools.extern.six.moves.py", line 34, in pre_safe_import_module
    for real_module_name, six_module_name in real_to_six_module_name.items():
AttributeError: 'str' object has no attribute 'items'

**Comment by lamourj** [comment]
Ran into the same issue on Windows. Same environnement works on Mac.

**Comment by htgoebel** [comment]
@2607861760 Please update to the latest setuptools. Setuptools are moving fast and we can not support every version. Sorry.

**Comment by crmchan** [comment]
Dear lamourj @lamourj
I update the setuptools to latest version but it still fails.

  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\lib\modulegraph\mo
dulegraph.py", line 2085, in _load_module
    self._scan_code(m, co, co_ast)
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\lib\modulegraph\mo
dulegraph.py", line 2547, in _scan_code
    self._process_imports(module)
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\lib\modulegraph\mo
dulegraph.py", line 2746, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\lib\modulegraph\mo
dulegraph.py", line 2224, in _safe_import_hook
    target_attr_names=None, level=level, edge_attr=edge_attr)
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\lib\modulegraph\mo
dulegraph.py", line 1425, in import_hook
    target_module = self._load_tail(target_package, target_module_partname)
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\lib\modulegraph\mo
dulegraph.py", line 1638, in _load_tail
    submodule = self._safe_import_module(head, mname, submodule)
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\depend\analysis.py
", line 260, in _safe_import_module
    hook_module.pre_safe_import_module(hook_api)
  File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\hooks\pre_safe_imp
ort_module\hook-setuptools.extern.six.moves.py", line 34, in pre_safe_import_mod
ule
    for real_module_name, six_module_name in real_to_six_module_name.items():
AttributeError: 'str' object has no attribute 'items'

================================================
# packages in environment at D:\Anaconda3\envs\intel:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.11                   py36_0    defaults
altgraph                  0.15                       py_0    conda-forge
altgraph                  0.15                      <pip>
asn1crypto                0.24.0             py36_intel_1  [intel]  intel
astroid                   1.6.5                    py36_0    defaults
babel                     2.6.0                    py36_0    defaults
backcall                  0.1.0              py36_intel_0  [intel]  intel
backports                 1.0                py36_intel_6  [intel]  intel
bleach                    2.1.3              py36_intel_0  [intel]  intel
bzip2                     1.0.6             vc14_intel_14  [intel vc14]  intel
ca-certificates           2018.4.16                     0    conda-forge
certifi                   2018.1.18          py36_intel_0  [intel]  intel
cffi                      1.11.5             py36_intel_1  [intel]  intel
chardet                   3.0.4              py36_intel_0  [intel]  intel
cloudpickle               0.5.3                    py36_0    defaults
colorama                  0.3.9              py36_intel_0  [intel]  intel
cryptography              2.2.2              py36_intel_1  [intel]  intel
cycler                    0.10.0             py36_intel_5  [intel]  intel
cython                    0.28.2             py36_intel_4  [intel]  intel
daal                      2018.0.3.20180405               0    intel
decorator                 4.3.0              py36_intel_0  [intel]  intel
distarray                 0.6.0              py36_intel_4  [intel]  intel
docutils                  0.14             py36h6012d8f_0    defaults
entrypoints               0.2.3              py36_intel_0  [intel]  intel
freetype                  2.9                vc14_intel_1  [intel vc14]  intel
future                    0.16.0                   py36_0    conda-forge
future                    0.16.0                    <pip>
get_terminal_size         1.0.0              py36_intel_5  [intel]  intel
hdf5                      1.10.1             vc14_intel_0  [intel vc14]  intel
html5lib                  1.0.1              py36_intel_1  [intel]  intel
icc_rt                    2018.0.3                intel_0  [intel]  intel
icu                       58.2                     vc14_0  [vc14]  conda-forge
idna                      2.6                py36_intel_0  [intel]  intel
imagesize                 1.0.0                    py36_0    defaults
impi_rt                   2018.0.3                intel_0  [intel]  intel
intel-openmp              2018.0.3                      0    defaults
intelpython               2018.0.3                      0    intel
intelpython3_core         0.0.0.custom                  0    intel
intelpython3_full         0.0.0.custom                  0    intel
ipykernel                 4.6.1              py36_intel_0  [intel]  intel
ipyparallel               6.0.2              py36_intel_0  [intel]  intel
ipython                   6.3.1              py36_intel_1  [intel]  intel
ipython_genutils          0.2.0              py36_intel_0  [intel]  intel
ipywidgets                7.0.0              py36_intel_0  [intel]  intel
isort                     4.3.4                    py36_0    defaults
jedi                      0.12.0             py36_intel_0  [intel]  intel
jinja2                    2.9.6              py36_intel_0  [intel]  intel
jpeg                      9b                       vc14_2  [vc14]  conda-forge
jsonschema                2.6.0              py36_intel_0  [intel]  intel
jupyter                   1.0.0              py36_intel_5  [intel]  intel
jupyter_client            5.1.0              py36_intel_0  [intel]  intel
jupyter_console           5.1.0              py36_intel_0  [intel]  intel
jupyter_core              4.4.0              py36_intel_1  [intel]  intel
kiwisolver                1.0.1                    py36_1    intel
lazy-object-proxy         1.3.1            py36hd1c21d2_0    defaults
libpng                    1.6.34             vc14_intel_1  [intel vc14]  intel
llvm-meta                 6.0.0                         0    conda-forge
llvmlite                  0.20.0             py36_intel_0  [intel]  intel
m2w64-gcc-libgfortran     5.3.0                         6    defaults
m2w64-gcc-libs            5.3.0                         7    defaults
m2w64-gcc-libs-core       5.3.0                         7    defaults
m2w64-gmp                 6.1.0                         2    defaults
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    defaults
macholib                  1.8                        py_0    conda-forge
macholib                  1.9                       <pip>
markupsafe                1.0                py36_intel_0  [intel]  intel
matplotlib                2.2.2           np114py36_intel_1  [intel]  intel
mccabe                    0.6.1            py36hb41005a_1    defaults
menuinst                  1.4.14           py36hfa6e2cd_0    defaults
mistune                   0.7.4              py36_intel_1  [intel]  intel
mkl                       2018.0.3                      1    defaults
mkl-devel                 2018.0.1             h470d631_5    defaults
mkl-include               2017.0.4                intel_0    intel
mkl-lb                    2017.0.3                intel_5    intel
mkl-lb-static             2017.0.3                intel_6    intel
mkl-mic                   2017.0.4                intel_0    intel
mkl-mic-static            2017.0.4                intel_0    intel
mkl-rt                    11.1                         p0    defaults
mkl-static                2017.0.4                intel_0    intel
mkl_fft                   1.0.2           np114py36_intel_0  [intel]  intel
mkl_random                1.0.1           np114py36_intel_0  [intel]  intel
mpi4py                    3.0.0              py36_intel_0  [intel]  intel
mpmath                    1.0.0              py36_intel_0  [intel]  intel
msgpack                   0.5.6                     <pip>
msys2-conda-epoch         20160418                      1    defaults
nbconvert                 5.2.1              py36_intel_0  [intel]  intel
nbformat                  4.4.0              py36_intel_0  [intel]  intel
nose                      1.3.7             py36_intel_16  [intel]  intel
notebook                  5.2.2              py36_intel_0  [intel]  intel
numba                     0.35.0             py36_intel_0  [intel]  intel
numexpr                   2.6.4           np114py36_intel_0  [intel]  intel
numpy                     1.14.3             py36_intel_0  [intel]  intel
numpydoc                  0.8.0                    py36_0    defaults
openmp                    2017.0.4                intel_0    intel
openmp-mic                2017.0.4                intel_0    intel
openssl                   1.0.2o             vc14_intel_0  [intel vc14]  intel
packaging                 17.1                     py36_0    defaults
pandas                    0.22.0          np114py36_intel_4  [intel]  intel
pandocfilters             1.4.1              py36_intel_0  [intel]  intel
parso                     0.2.0              py36_intel_0  [intel]  intel
path.py                   11.0.1             py36_intel_0  [intel]  intel
patsy                     0.5.0                    py36_0    defaults
pefile                    2017.11.5                 <pip>
pefile                    2017.11.5                  py_0    conda-forge
pickleshare               0.7.4              py36_intel_1  [intel]  intel
pip                       9.0.1              py36_intel_1  [intel]  intel
pip                       10.0.1                    <pip>
prompt_toolkit            1.0.15             py36_intel_0  [intel]  intel
psutil                    5.4.6            py36hfa6e2cd_0    defaults
pycodestyle               2.4.0                    py36_0    defaults
pycosat                   0.6.3            py36h413d8a4_0    defaults
pycparser                 2.18               py36_intel_0  [intel]  intel
pycrypto                  2.6.1            py36hfa6e2cd_8    defaults
pydaal                    2018.0.3.20180405 np114py36_intel_1  [intel]  intel
pyflakes                  2.0.0                    py36_0    defaults
pygments                  2.2.0              py36_intel_1  [intel]  intel
PyInstaller               3.4.dev0+84c1aaf96           <pip>
pylint                    1.9.2                    py36_0    defaults
pyopenssl                 17.5.0             py36_intel_0  [intel]  intel
pyparsing                 2.2.0              py36_intel_0  [intel]  intel
pypiwin32                 223                       <pip>
pyqt                      5.9.2            py36h1aa27d4_0    defaults
PyQt5                     5.10.1                    <pip>
pyqt5-tools               5.9.0.1.2                 <pip>
pysocks                   1.6.7              py36_intel_0  [intel]  intel
pytables                  3.4.2           np114py36_intel_4  [intel]  intel
python                    3.6.3                  intel_12  [intel]  intel
python-dateutil           2.6.0              py36_intel_3  [intel]  intel
pytz                      2018.4             py36_intel_0  [intel]  intel
pywin32                   223                       <pip>
pywin32                   223              py36hfa6e2cd_1    defaults
pywin32-ctypes            0.1.2                     <pip>
pywinpty                  0.5.4                    py36_0    defaults
pyyaml                    3.12               py36_intel_4  [intel]  intel
pyzmq                     16.0.2             py36_intel_4  [intel]  intel
qt                        5.9.6            vc14h62aca36_0    defaults
qtawesome                 0.4.4            py36h5aa48f6_0    defaults
qtconsole                 4.3.1            py36h99a29a9_0    defaults
qtpy                      1.4.2                    py36_0    defaults
requests                  2.18.4             py36_intel_0  [intel]  intel
rope                      0.10.7           py36had63a69_0    defaults
scikit-learn              0.19.1          np114py36_intel_29  [intel]  intel
scipy                     1.0.1           np114py36_intel_3  [intel]  intel
seaborn                   0.8.1            py36h9b69545_0    defaults
setuptools                39.2.0                    <pip>
setuptools                39.2.0                   py36_0    defaults
simplegeneric             0.8.1              py36_intel_5  [intel]  intel
singledispatch            3.4.0.3          py36h17d0c80_0    defaults
sip                       4.19.8           py36h6538335_0    defaults
sip                       4.19.8                    <pip>
six                       1.11.0                   py36_2    intel
six                       1.11.0                    <pip>
snowballstemmer           1.2.1            py36h763602f_0    defaults
sphinx                    1.7.5                    py36_0    defaults
sphinxcontrib             1.0              py36hbbac3d2_1    defaults
sphinxcontrib-websupport  1.1.0                    py36_1    defaults
spyder                    3.2.8                    py36_0    defaults
sqlite                    3.23.1             vc14_intel_0  [intel vc14]  intel
statsmodels               0.9.0                    py36_0    conda-forge
sympy                     1.1.1              py36_intel_3  [intel]  intel
tbb                       2018.0.4                 vc14_0  [vc14]  intel
tbb4py                    2018.0.4            py36_vc14_0  [vc14]  intel
tcl                       8.6.4             vc14_intel_19  [intel vc14]  intel
testpath                  0.3.1              py36_intel_0  [intel]  intel
tk                        8.6.4             vc14_intel_27  [intel vc14]  intel
tornado                   4.5.2              py36_intel_0  [intel]  intel
traitlets                 4.3.2              py36_intel_1  [intel]  intel
urllib3                   1.22               py36_intel_0  [intel]  intel
vc                        14.0                          2    intel
vs2015_runtime            14.0.25420              intel_0  [intel]  intel
wcwidth                   0.1.7              py36_intel_5  [intel]  intel
webencodings              0.5.1                    py36_0    intel
wheel                     0.31.0             py36_intel_0  [intel]  intel
widgetsnbextension        3.2.0                    py36_0    intel
win_inet_pton             1.0.1              py36_intel_0  [intel]  intel
win_unicode_console       0.5                py36_intel_0  [intel]  intel
wincertstore              0.2                py36_intel_0  [intel]  intel
winpty                    0.4.3                         4    defaults
wrapt                     1.10.11          py36he5f5981_0    defaults
xz                        5.2.3              vc14_intel_1  [intel vc14]  intel
zlib                      1.2.11             vc14_intel_4  [intel vc14]  intel

**Comment by jcwill23** [comment]
I have the same issue

    PyInstaller\hooks\pre_safe_import_module\hook-urllib3.packages.six.moves.py", line 31, 
   in pre_safe_import_module
    for real_module_name, six_module_name in real_to_six_module_name.items():
    AttributeError: 'str' object has no attribute 'items'

with setuptools 39.2 py36_0

**Comment by sibrionicslucw** [comment]
I solved it by updating requests ,because while I import requests, it failed,and pyintaller  sucessed while I didn't import it.

**Comment by jcwill23** [comment]
Which version of requests? 
I can get either pyinstaller to fail to build OR it builds but the Smartsheet functionality does not work when executing the exe

Craig

**Comment by MiloshBo** [comment]
I updated setuptools but the problem remains.

**Comment by emmanuel97** [comment]
This fixed my problem, I had this 2 errors:
pyinstaller : AttributeError: module 'enum' has no attribute 'IntFlag'

and

AttributeError: 'str' object has no attribute 'items'

fixing the first with "pip uninstall enum34" it now works

**Comment by QtRoS** [comment]
Thanks @emmanuel97, your suggestion worked for me too! I was having two the same issues as you.

**Comment by htgoebel** [comment]
Duplicate of #3806. Should be fixed now in 0ffa574bf87e2e37b0df2a4e2d60cb616f9ff2f2

**Comment by YuchenGUOGYC** [comment]
> @jcwill23 @MiloshBo 可以通过写替代代码实现。原始代码就是循环而已

can you explain it more in detial

**Comment by sc-patric** [comment]
> Ran into the same issue on Windows using the latest commit on `develop` branch. Same environnement works on Mac (able to generate the script and launch it). PyInstaller can't complete on Windows.
> 
> Edit: I solved it by updating `setuptools` (found that it could be related after reading [this stackoverflow post](https://stackoverflow.com/questions/35613300/pyinstaller-compile-to-exe)):
> `setuptools: 27.2.0-py36_1 --> 39.1.0-py36_0`
> 
> @2607861760 did you try updating `setuptools` (run `conda update setuptools`) ? That might allow you to close this issue .

i can't update my setuptools,cmdlog says setup have been done ,but version isn't changed when i find it in cmd-window by order pip list,do you know why?thanks...

**Comment by fig2018** [comment]
垃圾的PY

**Comment by fig2018** [comment]
垃圾的PYthon

**Comment by vijay-vimal** [comment]
Django Version: | 2.2.7
AttributeError
'str' object has no attribute 'items'
C:\ProgramData\Anaconda3\lib\site-packages\requests\models.py in prepare_headers, line 446

how to solve that problem
