### ISSUE TITLE
gitpython can not package with no console

### ISSUE THREAD

**Issue by Nriver** [pyinstaller/pyinstaller#3509]
I can not package a scirpt using gitpython module. The environment is python 2.7(and 3.6) on windows.

Reporduce the problem:

First create a simple python file named: dnd_git_clone_url.py
with content:
`# -*- coding: utf-8 -*-`
`import git`

then run the following in cmd:
pyinstaller --noconsole dnd_git_clone_url.py

After that try execute the generated exe file in cmd (double click on exe will display nothing),
should give you the following error.
![image](https://user-images.githubusercontent.com/6752679/39903802-90d36fcc-5507-11e8-96d5-c5bcbe5b4694.png)

I've tried using debug=1 and after whole bunch of message boxes and get the same error without other useful information.

The motivation of making gitpython without console is that I'm using wxpython to create a GUI program with gitpython. Removing the noconsole argument results in a exe program with GUI window and an extra console window which I would like to remove.

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by gsemet** [comment]
Fixed by replacing:
```
pypi_wheels =
    ...
    GitPython==4.0
```
By:
```
pypi_wheels =
    ...
    gitpython==4.0
```

**Comment by htgoebel** [comment]
@Nriver Can you confirm this? Then please close the ticket. Otherwise please provide more details.

**Comment by gsemet** [comment]
I see some packages has weird behavior on pypi, for example pipenv maintain a [list of mapping](https://github.com/pypa/pipenv/blob/a108093d2efe52bf03827d6d13ba250827b1cf0a/pipenv/vendor/pipreqs/mapping). So I have a jinja script that extract requirements.txt (with frozen version) to feed pyinstaller with, works great, i just have to change the case of gitpython for some reason

**Comment by NotInControl** [comment]
Hi,

I am receiving the same message, however it wasn't clear to me which file was updates in @gsemet post above. So I haven't tried that yet. 

I have a pyQT5 Application that will build correctly as a one file if import git is not used, but as soon as import git is added (gitpython library) the exe packaged with --one file shows the error in the OP.

if the application is packaged without --one file, the exe create does work. It is only when using the --one file flag that the message above occurs. 

However, not sure how to work around it. The --one file is a requirement for this application. 

Fails:
```
pyinstaller --onefile -w --paths C:\Users\T595968\AppData\Local\Continuum\Miniconda3\Lib\site-packages GitHubMain.py
```

Works
```
pyinstaller --clean -w --paths C:\Users\T595968\AppData\Local\Continuum\Miniconda3\Lib\site-packages GitHubMain.py
```

Python = 3.6.1
pyInstaller = 3.4
Windows = 7.0
gitPython = 2.1.11

**Comment by htgoebel** [comment]
I take https://github.com/pyinstaller/pyinstaller/issues/3509#issuecomment-400772938 as "resolved".

**Comment by NotInControl** [comment]
> I take [#3509 (comment)](https://github.com/pyinstaller/pyinstaller/issues/3509#issuecomment-400772938) as "resolved".

Hello, could you please tell me what file this comment supposed to be implemented?  At least for me this issue is not re-solved. Any help would be much appreciated. 

Thanks.

**Comment by htgoebel** [comment]
Sorry, I quoted the wrong comment. Should be https://github.com/pyinstaller/pyinstaller/issues/3509#issuecomment-400755510

**Comment by NotInControl** [comment]
I am unable to determine where this modification is to occur, as as such cannot package a program using gitpython with no console. If the -w flag is removed, the application runs correctly. If -w flag is added, the same error in the OP is show (Failed to Execute.)

Running with console shows no errors on startup. Could you please tell me what file gets modified based on the comment referenced. I do not know where pypi_wheels =
    ...
    gitpython==4.0

**Comment by skycity233** [comment]
> Fixed by replacing:
> 
> ```
> pypi_wheels =
>     ...
>     GitPython==4.0
> ```
> 
> By:
> 
> ```
> pypi_wheels =
>     ...
>     gitpython==4.0
> ```

Could please tell me where can i modify it.

**Comment by gsemet** [comment]
My mistake. pypi_wheels is for nsist, not pyinstaller. Just set gitpython in one hook file

**Comment by IgorGra** [comment]
Cannot resolve it too, can somebody explain how to fix it?

**Comment by QSane** [comment]
Has this issue been resolved?
Which problem is "--noconsole" or "--onefile"?
I'm having the same problem trying to use it with GitPython.

**Comment by correojon** [comment]
> My mistake. pypi_wheels is for nsist, not pyinstaller. Just set gitpython in one hook file
I've spent the last hour trying to do this with no success, has anyone managed to make this work? I'm at a point where I may just remove GitPython from my app and try to use something else.

**Comment by gsemet** [comment]
I gave my solution on 14 dev 2019. Still work. Beware of the case "gitpython" instead of "GitPython"

**Comment by correojon** [comment]
> I gave my solution on 14 dev 2019. Still work. Beware of the case "gitpython" instead of "GitPython"

Could you please elaborate a bit? I tried creating a **hook-gitpython.py** file with content _hiddenimports = ['gitpython']_ but it didn't work. I also tried referencing it in the spec file but nothing.

**Comment by gsemet** [comment]
Actually, I have `hiddenimports = ['git']` in my hook file

**Comment by correojon** [comment]
> Actually, I have `hiddenimports = ['git']` in my hook file


Thanks a lot for not giving up on this 😊

I tried using **hook-git.py** with _hiddenimports = ['git']_ with no success 😢 The hook is called during the build process and the module seems to be found and loaded, but once I click on the .exe it just yields the "Failed to execute script" error. If I remove the git import from my program or build the installer with console=False the generated executable works flawlessly.

If I use **hook-gitpython.py** it just gets ignored and isn't loaded and if I try hiddenimports = ['gitpython'] I get an error during the build process saying that the module can't be found.

I am using a spec file and a **hooks** directory where I place my hook-git.py file, and which is referenced in the **hookspath** field of the spec file, are you do it differently? At this point I don't know what more I can try.

**Comment by htgoebel** [comment]
We would appreciate if you'd submit a pull-request for a hook for this in the https://github.com/pyinstaller/pyinstaller-hooks-contrib repo.

See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by iPwnXX** [comment]
> > Actually, I have `hiddenimports = ['git']` in my hook file
> 
> Thanks a lot for not giving up on this 😊
> 
> I tried using **hook-git.py** with _hiddenimports = ['git']_ with no success 😢 The hook is called during the build process and the module seems to be found and loaded, but once I click on the .exe it just yields the "Failed to execute script" error. If I remove the git import from my program or build the installer with console=False the generated executable works flawlessly.
> 
> If I use **hook-gitpython.py** it just gets ignored and isn't loaded and if I try hiddenimports = ['gitpython'] I get an error during the build process saying that the module can't be found.
> 
> I am using a spec file and a **hooks** directory where I place my hook-git.py file, and which is referenced in the **hookspath** field of the spec file, are you do it differently? At this point I don't know what more I can try.

Having exactly the same problem. 'import git' with 'noconsole'  cause the fatal error.
