### ISSUE TITLE
support ActiveState python distribution

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#351]
**Original date**: 2011/05/20

Main focus with pyinstaller is on official python distribution from http://www.python.org.

There are some technical limits preventing us from supporting ActiveState.

I'm not sure how much work it would be to support activestate in pyinstaller and if it would be even possible.

Related tickets: #303

**Comment by htgoebel** [comment]
Closing: Much too old, no demand, nobody else reported such a problem adn Anaconda seams now be more relevant than Activestate.
