### ISSUE TITLE
No way to only run .app test on OSX?

### ISSUE THREAD

**Issue by glennra** [pyinstaller/pyinstaller#3522]
On OSX programs that use QtWebEngineWidgets need many other files and must be packaged as a .app to work correctly.

The test framework by default creates a onefile and onedir build and for OSX also creates a .app[1]. In test_PyQt5_QWebEngine [2] the onefile and/or onedir builds fail and therefore the .app never gets run.

Is there a way to tell the test framework to only run the .app build if it is on OSX? If not, then this is required for test_PyQt5_QWebEngine to work. 

[1] https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/conftest.py#L302
[2] https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/test_libraries.py#L249

**Comment by bjones1** [comment]
I think this may fix it, but can only test on Travis, which is a bit slow. Would you mind testing this and providing feedback?

This is the updated version of `_find_executables` in `conftest.py`.

``` Python
    def _find_executables(self, name):
        """
        Search for all executables generated by the testcase.

        If the test-case is called e.g. 'test_multipackage1', this is
        searching for each of 'test_multipackage1.exe' and
        'test_multipackage1_?.exe' in both one-file- and one-dir-mode.

        If a Mac OS X app bundle is found, the onefile executable is not
        returned.

        :param name: Name of the executable to look for.

        :return: List of executables.
        """
        exes = []
        onedir_pt = os.path.join(self._distdir, name, name)
        onefile_pt = os.path.join(self._distdir, name)
        patterns = [onedir_pt, onefile_pt,
                    # Multipackage one-dir
                    onedir_pt + '_?',
                    # Multipackage one-file
                    onefile_pt + '_?']
        # For Windows append .exe extension to patterns.
        if is_win:
            patterns = [pt + '.exe' for pt in patterns]
        # Apply file patterns.
        for pattern in patterns:
            for prog in glob.glob(pattern):
                if os.path.isfile(prog):
                    exes.append(prog)
        # Replace a one-file executable with a Mac OS X .app bundle if it exists.
        if is_darwin:
            # e.g:  ./dist/name.app/Contents/MacOS/name
            pt = os.path.join(self._distdir, name + '.app', 'Contents', 'MacOS', name)
            if exes == [onefile_pt] and os.path.isfile(pt):
                exes = [pt]
        return exes
```

**Comment by glennra** [comment]
Thanks @bjones1 I have updated the PR for #3506 with a modified version of your code above. The test works if I do`py.test -k test_PyQt5_QWebEngine[onedir]` but it fails if I do `py.test -k test_PyQt5_QWebEngine[onefile]`. I don't see how this is happening because my change replaces both the onefile and/or onedir executables with the .app if it exists.

**Comment by bjones1** [comment]
I don't think the onedir executable will ever work -- as I understand it from https://pyinstaller.readthedocs.io/en/v3.3.1/usage.html#building-mac-os-x-app-bundles, the app bundle is only built for onefile executables. I assume the onedir fails because it's not running an app bundle, but the application (with no `Info.plist` provided).

**Comment by glennra** [comment]
Other way around `test_PyQt5_QWebEngine[onedir]` succeeds `test_PyQt5_QWebEngine[onefile]` fails.  However in both cases, in my updated PR, the exe should be getting replaced by the .app so not sure why that is as the test should effectively ignore the `[one*]` parameter.

**Comment by bjones1** [comment]
I'm closing this, since #3506 provides this ability.
