### ISSUE TITLE
Reproducible-Build not working with PyPI version 3.3.1

### ISSUE THREAD

**Issue by gsbabil** [pyinstaller/pyinstaller#3526]
#### ## Short Summary

  - Reproducible-Build broken on PyPI `3.3.1`
  - Reproducible-Build fixed on current `develop` head [1033a877]

#### ## Details

Dear Maintainers,

Reproducible-Build with PyInstaller [as advised here][0] seems to be broken both on Linux and Windows with the latest PyPI release of version `3.3.1`. Running the following would produce different SHA-256 digest in each new iteration (with or without `--clean`):

```
$ pip install pyinstaller ## installs version 3.3.1 from PyPI

$ PYTHONHASHSEED=1
$ export PYTHONHASHSEED

$ mkdir tmp && cd tmp
$ echo 'import this' > zen.py

$ pyinstaller \
    --clean \
    --console \
    --onefile \
    --noupx \
    --noconfirm \
    zen.py 2> /dev/null \
    && sha256sum dist/zen
```

_**P.S.**_

I was able to test PyInstaller latest on `master` [1033a877] with the following on both Linux and windows. Reproducible-Build with `PYTHONHASHSEED` seems to work as expected. 

I think the issue can be immediately closed. I'm just leaving the details as here as reference for who are still on `3.3.1` and struggling with reproducible-build. 

Thanks for this very useful tool!

```
$ git clone https://github.com/pyinstaller/pyinstaller.git

$ cd pyinstaller
$ python3 setup.py build

$ mkdir tmp && cd tmp
$ echo 'import this' > zen.py
$ PYTHONHASHSEED=1 python3 ../pyinstaller.py \
    --clean \
    --console \
    --onefile \
    --noupx \
    --noconfirm zen.py 2>/dev/null \
    && sha256sum dist/zen
```

[0]: https://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#creating-a-reproducible-build

**Comment by htgoebel** [comment]
Hmm current master is 8ea39be13dd1186bd93b035d32d65b45394350ed (which is tagged 3.3.1), so I you mean the current development head. I updated your message accordingly.

So thanks to taking the time to report this. As this is fixed already on our development head, what you you expect?

**Comment by htgoebel** [comment]
Ups, not read you message in details: You just wanted this to be documents. Thanks!

**Comment by gsbabil** [comment]
Hi, @htgoebel,

> Ups, not read you message in details: You just wanted this to be documents. Thanks!

No problem. Do you have a tentative ETA when the next release of PyInstaller may land in PyPI? Thanks a lot.
