### ISSUE TITLE
Python dll conflict running another python instance with subprocess

### ISSUE THREAD

**Issue by Sup3rGeo** [pyinstaller/pyinstaller#3529]
Hi guys,

I have a very simple python code for which I am creating an executable file:
https://github.com/typhoon-hil/LibreOfficeToPDF

It basically locates LibreOffice's own python and spawns a subprocess by running it with a defined py file:
https://github.com/typhoon-hil/LibreOfficeToPDF/blob/master/src/LibreOfficeToPDF/cli.py

    print("Calling LibreOffice python\n")
    print(check_output(["{}".format(OPENOFFICE_PYTHON), script, source], shell=True).decode())

It work when just running normally but once I package using PyInstaller, I get the following error:

```
Traceback (most recent call last):
  File "C:\Users\victo\AppData\Local\Temp\_MEI87882\script.py", line 2, in <module>
    import socket
  File "C:\Program Files\LibreOffice 5\program\python-core-3.5.0\lib\socket.py", line 49, in <module>
    import _socket
ImportError: Module use of python36.dll conflicts with this version of Python.
Traceback (most recent call last):
  File "LibreOfficeToPDF\cli.py", line 39, in <module>
  File "lib\site-packages\click\core.py", line 722, in __call__
  File "lib\site-packages\click\core.py", line 697, in main
  File "lib\site-packages\click\core.py", line 895, in invoke
  File "lib\site-packages\click\core.py", line 535, in invoke
  File "LibreOfficeToPDF\cli.py", line 36, in main
  File "subprocess.py", line 336, in check_output
  File "subprocess.py", line 418, in run
subprocess.CalledProcessError: Command '['C:\\Program Files\\LibreOffice 5\\program\\python', 'C:\\Users\\victo\\AppData\\Local\\Temp\\_MEI87882\\script.py', 'C:\\WORK\\101_microgrid_examples_tests\\report.docx']' returned non-zero exit status 1.
```
I am running Python 3.6 and LibreOffice's python is version 3.5. I believe this is the cause of the problem.

Is there any tricks for running `subprocess` from PyInstaller that could be related to this issue? I thought that spawning from `subprocess` would always create an environment isolated from the executing python process, but somehow then running from a PyInstaller executable this does not seem to be true.

Thanks!

**Comment by htgoebel** [comment]
You need to set [`LD_LIBRARY_PATH`](https://pyinstaller.readthedocs.io/en/latest/runtime-information.html?highlight=ld_library_path#ld-library-path-libpath-considerations) before calling `checkoutput`

> `"{}".format(OPENOFFICE_PYTHON)`

Shiver! Why use format hare at all? If OPENOFFICE_PYTHON is not a string anyway, `str()` would doe the same.

**Comment by Sup3rGeo** [comment]
@htgoebel, thanks for the help. 

> You need to set LD_LIBRARY_PATH before calling checkoutput

Actually the problem was something else. I checked the `sys.path` variables in the python subprocess spawned and the `_MEIPASS` folder was the first item in the list, regardless of any `env` dictionary I sent to the process.

I had to manually send the MEIPASS folder to the script ran by this python subprocess so it could `pop` it from `sys.path` in the beginning of the script.

Is this expected? Does not seem like the most sensitive behavior for this case.

**Comment by Sup3rGeo** [comment]
So, caller:
- `os.getcwd()` = `C:\Users\victo\Desktop`
- No `PYTHONPATH` or other python related path
- `sys.path`: 
  - `C:\Users\victo\AppData\Local\Temp\_MEI93002\base_library.zip`
  - `C:\Users\victo\AppData\Local\Temp\_MEI93002`

script:
- `os.getcwd()` = `C:\Users\victo\Desktop`
- `PYTHONPATH = C:\Program Files\LibreOffice 5\program\;C:\Program Files\LibreOffice 5\program\\python-core-3.5.0\lib;C:\Program Files\LibreOffice 5\program\\python-core-3.5.0\lib\site-packages`
- `PYTHONHOME = C:\Program Files\LibreOffice 5\program\\python-core-3.5.0`
- `sys.path`:
  - `C:\Users\victo\AppData\Local\Temp\_MEI93002`
  - `C:\Program Files\LibreOffice 5\program`
  - `C:\Program Files\LibreOffice 5\program\python-core-3.5.0\lib`
  - `C:\Program Files\LibreOffice 5\program\python-core-3.5.0\lib\site-packages`
  - `C:\Program Files\LibreOffice 5\program\python35.zip`
  - `C:\Program Files\LibreOffice 5\program\python-core-3.5.0\DLLs`
  - `C:\Program Files\LibreOffice 5\program\python-core-3.5.0\bin`
  - `C:\Program Files\LibreOffice 5\program\python-core-3.5.0`

Also tried to change the cwd in the `subprocess.Popen` call to the LibreOffice python but didn't change anything.
I really have no good knowledge on Python to understand why the `sys.path[0]` is being set to the temp folder.

**Comment by Sup3rGeo** [comment]
I just started manually LibreOffice python and `sys.path[0]` is just `' '`, so it doesn't seem to be doing anything funny itself.

**Comment by htgoebel** [comment]
I had a deeper look at your code now, and the solution is simple: You are running $MEIPASS/script.py, which will add $MAIPASS to the front off sys.path, see https://docs.python.org/3/library/sys.html#sys.path. To avoid this, you need to move your script into a sub-directory.

Other remarks:
1. I wonder if you really need this `cli.py` at all. It is only calling LibreOffice's python, passing on some parameters. Maybe a .bat file would do the job without the overhead of another python interpreter
2. I suggest you learn about the `print()` function. You are using `.format()` a lot, which is useless in `print()` as you are using it.

Closing, assume this is solved now.
