### ISSUE TITLE
Not Loading hook-Crypto.py

### ISSUE THREAD

**Issue by jhave21** [pyinstaller/pyinstaller#3533]
Hi, I am using pycryptodome in my project and done extensive researchon how to use it but it's not loading  hook-Crypto.py [https://imgur.com/a/fLIaod9] why?

I am getting ImprotError no module name Crypto

**Comment by jyc511** [comment]
I have the same problem but Am bypassing it by using pycryptodomex instead. Did u mAnage to load the hook?

**Comment by htgoebel** [comment]
I doubt, the hook is not loaded, if there your program imports a module `Crypto`. I assume the hook does not work as you expect.

Unfortunately you did not provide of the details requested in issue template, thus weare not able to help any further. Maybe searching the issues for "crypto" or "pycryptodome" help. I'm closing this now.
