### ISSUE TITLE
Update documentaion about info_plist

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#3540]
After merging #3532, the [respective documentation](https://github.com/pyinstaller/pyinstaller/blob/f605e236461a31a361fc4e714e237b0bf0931a7a/doc/spec-files.rst#spec-file-options-for-a-macosx-bundle)  needs to be updated:
- Remove the part about "cannot handle nested XML arrays" and the following paragraphs, refer to https://docs.python.org/3/library/plistlib.html instead
- Fix the example: `'NSHighResolutionCapable': True` -- boolean value
- Think about adding example-values for LSUIElement and LSBackgroundOnly

**Comment by itsayellow** [comment]
I didn't put any examples for LSUIElement and LSBackgroundOnly.  My thought was maybe this is getting to deep into what is how to program macOS applications, and less about how to use pyinstaller.

**Comment by htgoebel** [comment]
Oh, this acually is merged since quite some time now. Closing.
