### ISSUE TITLE
Pyinstaller fails to import modules in windows 

### ISSUE THREAD

**Issue by shonakhan** [pyinstaller/pyinstaller#3542]
I have installed and successfully converted the python file to exe but when i run the file i got the error that failed to load module mechanize whats the matter ? i figured out that pyinstaller is not importing the libraries which are in python file please let me know if there is any way

**Comment by lamourj** [comment]
Hi @shonakhan, you are far from giving enough information for helping there. You can try adding `mechanize` to the hidden-imports I guess, but helping further is not possible with this amount of details.
Please take a look at [the When Things Go Wrong](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html) section.
