### ISSUE TITLE
Run script error

### ISSUE THREAD

**Issue by OldShadow** [pyinstaller/pyinstaller#3543]
I tried to convert an py script to exe, all went right, but I cant run the script
It keeps giving me the error 
`Traceback (most recent call last):
  File "anyname.py", line 1, in <module>
  File "<string>", line 9
    s.connect(('XXX.XXX.X.XXX',XXXX))
    ^
SyntaxError: invalid syntax
[10716] Failed to execute script anyname`
I am fairly sure my code is right

**Comment by lamourj** [comment]
Hi @OldShadow 
This is not a lot of details for helping out.
You are mentioning:
> I am fairly sure my code is right

Did you actually test the code without PyInstaller (just running with Python)?
Please take a look at the [When Things Go Wrong section](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html).

**Comment by htgoebel** [comment]
I'm fairly sure your code wrong. PyInstaller does not change your code, thus if there is an syntax error showing up, this is a bug in your code.
