### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by vonlippmann** [pyinstaller/pyinstaller#3547]
my platform:
WIN 10 64 bit , python 3.6

i try to installer my PyQt5 application , but i meet the following error:
![image](https://user-images.githubusercontent.com/25638200/40820846-95f5031e-6595-11e8-9115-a8bec9a54ff2.png)
when i try to install another simple PyQt5 application ,it works ,although there are some similar warning such as:
![image](https://user-images.githubusercontent.com/25638200/40820907-fcf11918-6595-11e8-9b71-4d72b7a29991.png)
I don't know how to deel with this kind of error, are there something to do with my win10 system or python packages such as scipy?

**Comment by tangjiuqi097** [comment]
I get the same problem. Can you show me some details? And I am not sure which module is missing. May be skimage... But when I add it to hidden import, it does not work.
