### ISSUE TITLE
pyinstaller - GUI is not launching if we have pandas import

### ISSUE THREAD

**Issue by vasan123** [pyinstaller/pyinstaller#3549]
If you have problems to get your application running, please first

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If your problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for GitHub's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.

**Otherwise we will not be willing to help you.**

Please be aware that PyInstaller is a voluntary project. We spent quite some time
writing these guides to make both of our lives easier. Please
understand that we are not willing to spend our spare time to help you if you
are not willing to help on your side. (Sorry for having to said this, but we
are tired of being asked the same questions over and over again.)

Env I am using is:

714 INFO: PyInstaller: 3.3.1
714 INFO: Python: 3.6.4
715 INFO: Platform: Windows-7-6.1.7601-SP1

After packaged  by running this pyinstaller --windowed echo.py command, try to launch echo.exe from dist folder, got a fatal error, "Failed to execute a script test"

(base) C:\Downloads\Python\package>pyinstaller --windowed echo.py

714 INFO: PyInstaller: 3.3.1
714 INFO: Python: 3.6.4
715 INFO: Platform: Windows-7-6.1.7601-SP1
716 INFO: wrote C:\Downloads\Python\package\echo.spec
720 INFO: UPX is not available.
733 INFO: Extending PYTHONPATH with paths
['C:\Downloads\Python\package',
'C:\Downloads\Python\package']
733 INFO: checking Analysis
734 INFO: Building Analysis because out00-Analysis.toc is non existent
734 INFO: Initializing module dependency graph...
740 INFO: Initializing module graph hooks...
742 INFO: Analyzing base_library.zip ...
6737 INFO: running Analysis out00-Analysis.toc
6740 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
required by C:\AppData\Local\Continuum\anaconda3\python.exe
7564 INFO: Caching module hooks...
7569 INFO: Analyzing C:\Downloads\Python\package\echo.py
9304 INFO: Processing pre-find module path hook distutils
10258 INFO: Processing pre-safe import module hook six.moves
23773 INFO: Processing pre-find module path hook site
23776 INFO: site: retargeting to fake-dir 'C:\AppData\Local\Continuum\anaconda3\lib\site-packages\PyInstaller\fake-modules'
38456 INFO: Processing pre-safe import module hook urllib3.packages.six.moves
72567 INFO: Processing pre-safe import module hook win32com
121886 INFO: Loading module hooks...
121886 INFO: Loading module hook "hook-babel.py"...
122038 INFO: Loading module hook "hook-certifi.py"...
122041 INFO: Loading module hook "hook-cryptography.py"...
122775 INFO: Loading module hook "hook-distutils.py"...
122777 INFO: Loading module hook "hook-docutils.py"...
125570 INFO: Loading module hook "hook-encodings.py"...
125807 INFO: Loading module hook "hook-IPython.py"...
125832 INFO: Excluding import 'PySide'
125844 INFO: Removing import of PySide from module IPython.external.qt_loaders
125846 INFO: Excluding import 'matplotlib'
125857 INFO: Removing import of matplotlib.pyplot from module IPython.core.pylabtools
125857 INFO: Removing import of matplotlib from module IPython.core.pylabtools
125857 INFO: Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
125857 INFO: Removing import of matplotlib.figure from module IPython.core.pylabtools
125860 INFO: Excluding import 'gtk'
125875 INFO: Excluding import 'PyQt4'
125890 INFO: Removing import of PyQt4 from module IPython.external.qt_loaders
125891 INFO: Excluding import 'tkinter'
125901 INFO: Removing import of tkinter from module IPython.lib.clipboard
125905 INFO: Excluding import 'PyQt5'
125918 INFO: Removing import of PyQt5.QtCore from module IPython.external.qt_loaders
125918 INFO: Removing import of PyQt5.QtWidgets from module IPython.external.qt_loaders
125918 INFO: Removing import of PyQt5.QtSvg from module IPython.external.qt_loaders
125920 INFO: Removing import of PyQt5.QtGui from module IPython.external.qt_loaders
125921 INFO: Removing import of PyQt5 from module IPython.external.qt_loaders
125928 INFO: Loading module hook "hook-jinja2.py"...
125969 INFO: Loading module hook "hook-jsonschema.py"...
125974 INFO: Loading module hook "hook-lib2to3.py"...
125981 INFO: Loading module hook "hook-lxml.etree.py"...
125983 INFO: Loading module hook "hook-matplotlib.backends.py"...
127261 INFO: Matplotlib backend "GTK": ignored
Gtk* backend requires pygtk to be installed.
128146 INFO: Matplotlib backend "GTKAgg": ignored
Gtk* backend requires pygtk to be installed.
128739 INFO: Matplotlib backend "GTKCairo": ignored
No module named 'gtk'
129472 INFO: Matplotlib backend "MacOSX": ignored
cannot import name '_macosx'
130269 INFO: Matplotlib backend "Qt4Agg": added
131091 INFO: Matplotlib backend "Qt5Agg": added
131925 INFO: Matplotlib backend "TkAgg": added
132811 INFO: Matplotlib backend "WX": ignored
Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
133630 INFO: Matplotlib backend "WXAgg": ignored
Matplotlib backend_wx and backend_wxagg require wxPython >=2.8.12
134145 INFO: Matplotlib backend "GTK3Cairo": ignored
Cairo backend requires that cairocffi or pycairo is installed.
134879 INFO: Matplotlib backend "GTK3Agg": ignored
Gtk3 backend requires pygobject to be installed.
136132 INFO: Matplotlib backend "WebAgg": added
138821 INFO: Matplotlib backend "nbAgg": added
139587 INFO: Matplotlib backend "agg": added
140121 INFO: Matplotlib backend "cairo": ignored
Cairo backend requires that cairocffi or pycairo is installed.
140728 INFO: Matplotlib backend "gdk": ignored
No module named 'gobject'
141503 INFO: Matplotlib backend "pdf": added
142525 INFO: Matplotlib backend "pgf": added
143260 INFO: Matplotlib backend "ps": added
143986 INFO: Matplotlib backend "svg": added
144722 INFO: Matplotlib backend "template": added
145258 INFO: Loading module hook "hook-matplotlib.py"...
145806 INFO: Loading module hook "hook-numpy.core.py"...
145949 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
145954 INFO: Loading module hook "hook-openpyxl.py"...
145968 INFO: Loading module hook "hook-PIL.Image.py"...
146853 INFO: Loading module hook "hook-PIL.py"...
146860 INFO: Excluding import 'PySide'
146866 INFO: Removing import of PySide from module PIL.ImageQt
146868 INFO: Excluding import 'PyQt4'
146876 INFO: Removing import of PyQt4 from module PIL.ImageQt
146878 INFO: Excluding import 'tkinter'
146887 INFO: Removing import of tkinter from module PIL.ImageTk
146891 INFO: Import to be excluded not found: 'FixTk'
146892 INFO: Excluding import 'PyQt5'
146903 INFO: Removing import of PyQt5.QtCore from module PIL.ImageQt
146908 INFO: Removing import of PyQt5.QtGui from module PIL.ImageQt
146910 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
146921 INFO: Excluding import 'tkinter'
146928 INFO: Import to be excluded not found: 'FixTk'
146929 INFO: Loading module hook "hook-pkg_resources.py"...
149693 INFO: Loading module hook "hook-pycparser.py"...
150126 INFO: Loading module hook "hook-pydoc.py"...
150128 INFO: Loading module hook "hook-pygments.py"...
153199 INFO: Loading module hook "hook-PyQt5.py"...
153203 INFO: Loading module hook "hook-PyQt5.Qt.py"...
153206 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
153445 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
154724 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
154941 INFO: Loading module hook "hook-PyQt5.QtSvg.py"...
154942 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
154944 INFO: Loading module hook "hook-pytest.py"...
156511 INFO: Loading module hook "hook-pythoncom.py"...
157428 INFO: Loading module hook "hook-pytz.py"...
157570 INFO: Loading module hook "hook-pywintypes.py"...
158502 INFO: Loading module hook "hook-requests.py"...
158505 INFO: Loading module hook "hook-scipy.linalg.py"...
158509 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
158511 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
158513 INFO: Loading module hook "hook-setuptools.py"...
158556 INFO: Loading module hook "hook-sphinx.py"...
164723 INFO: Loading module hook "hook-sqlalchemy.py"...
165166 INFO: Found 3 sqlalchemy hidden imports
165168 WARNING: Hidden import "MySQLdb" not found!
165169 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
165191 INFO: Excluding import 'sqlalchemy.testing'
165202 INFO: Removing import of sqlalchemy.testing.util from module sqlalchemy.orm.util
165203 INFO: Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing
165204 INFO: Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing
165208 INFO: Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing
165212 INFO: Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing
165214 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing
165217 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing
165220 INFO: Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing
165225 INFO: Removing import of sqlalchemy.testing.util from module sqlalchemy.testing
165229 INFO: Removing import of sqlalchemy.testing.warnings from module sqlalchemy.testing
165230 INFO: Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.warnings
165230 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.warnings
165231 INFO: Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing.assertions
165232 INFO: Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing.assertions
165236 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertions
165238 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.assertions
165243 INFO: Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing.assertions
165246 INFO: Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.assertions
165249 INFO: Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing.util
165252 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.util
165255 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.util
165259 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.config
165262 INFO: Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.engines
165265 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.engines
165268 INFO: Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.engines
165271 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.engines
165279 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.exclusions
165279 INFO: Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.exclusions
165282 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertsql
165284 INFO: Removing import of sqlalchemy.testing from module sqlalchemy.testing.mock
165288 INFO: Loading module hook "hook-sqlite3.py"...
165537 INFO: Loading module hook "hook-sysconfig.py"...
165538 INFO: Loading module hook "hook-tables.py"...
165542 INFO: Loading module hook "hook-win32com.py"...
165842 INFO: Loading module hook "hook-xml.dom.domreg.py"...
165846 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
165848 INFO: Loading module hook "hook-xml.py"...
165851 INFO: Loading module hook "hook-zmq.py"...
169000 INFO: Excluding import 'zmq.libzmq'
169006 INFO: Removing import of zmq.libzmq from module zmq
169008 INFO: Loading module hook "hook-_tkinter.py"...
169405 INFO: checking Tree
169406 INFO: Building Tree because out00-Tree.toc is non existent
169406 INFO: Building Tree out00-Tree.toc
169500 INFO: checking Tree
169501 INFO: Building Tree because out01-Tree.toc is non existent
169502 INFO: Building Tree out01-Tree.toc
169528 INFO: Loading module hook "hook-gevent.monkey.py"...
169860 INFO: Looking for ctypes DLLs
170045 INFO: Analyzing run-time hooks ...
170072 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
170079 INFO: Including run-time hook 'pyi_rth_pkgres.py'
170086 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
170090 INFO: Including run-time hook 'pyi_rth_traitlets.py'
170093 INFO: Including run-time hook 'pyi_rth_qt5.py'
170098 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
170103 INFO: Including run-time hook 'pyi_rth_mpldata.py'
170105 INFO: Including run-time hook 'pyi_rth__tkinter.py'
170183 INFO: Looking for dynamic libraries
182835 WARNING: lib not found: mpich2mpi.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_blacs_mpich2_lp64.dll
185145 WARNING: lib not found: mpich2mpi.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_blacs_mpich2_ilp64.dll
185449 WARNING: lib not found: impi.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_blacs_intelmpi_lp64.dll
186225 WARNING: lib not found: msmpi.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_blacs_msmpi_ilp64.dll
186359 WARNING: lib not found: msmpi.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_blacs_msmpi_lp64.dll
188017 WARNING: lib not found: tbb.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_tbb_thread.dll
189460 WARNING: lib not found: pgc14.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
189592 WARNING: lib not found: pgf90.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
189721 WARNING: lib not found: pgf90rtl.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
190016 WARNING: lib not found: impi.dll dependency of C:\AppData\Local\Continuum\anaconda3\Library\bin\mkl_blacs_intelmpi_ilp64.dll
194761 INFO: Looking for eggs
194761 INFO: Using Python library C:\AppData\Local\Continuum\anaconda3\python36.dll
194762 INFO: Found binding redirects:
[]
194799 INFO: Warnings written to C:\Downloads\Python\package\build\echo\warnecho.txt
195581 INFO: Graph cross-reference written to C:\Downloads\Python\package\build\echo\xref-echo.html
195975 INFO: checking PYZ
195975 INFO: Building PYZ because out00-PYZ.toc is non existent
195976 INFO: Building PYZ (ZlibArchive) C:\Downloads\Python\package\build\echo\out00-PYZ.pyz
204280 INFO: Building PYZ (ZlibArchive) C:\Downloads\Python\package\build\echo\out00-PYZ.pyz completed successfully.
204400 INFO: checking PKG
204401 INFO: Building PKG because out00-PKG.toc is non existent
204401 INFO: Building PKG (CArchive) out00-PKG.pkg
204474 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
204476 INFO: Bootloader C:\AppData\Local\Continuum\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
204476 INFO: checking EXE
204479 INFO: Building EXE because out00-EXE.toc is non existent
204482 INFO: Building EXE from out00-EXE.toc
204485 INFO: Appending archive to EXE C:\Downloads\Python\package\build\echo\echo.exe
204512 INFO: Building EXE from out00-EXE.toc completed successfully.
204523 INFO: checking COLLECT
204523 INFO: Building COLLECT because out00-COLLECT.toc is non existent
204525 INFO: Building COLLECT out00-COLLECT.toc
206030 INFO: Updating manifest in C:\AppData\Roaming\pyinstaller\bincache00_py36_64bit\zmq\backend\cython\libzmq.cp36-win_amd64.pyd
206032 INFO: Updating resource type 24 name 2 language 1033
208578 INFO: Updating manifest in C:\AppData\Roaming\pyinstaller\bincache00_py36_64bit\zmq.backend.cython.libzmq.pyd
208579 INFO: Updating resource type 24 name 2 language 1033
210125 INFO: Updating manifest in C:\AppData\Roaming\pyinstaller\bincache00_py36_64bit\libzmq.cp36-win_amd64.pyd
210126 INFO: Updating resource type 24 name 2 language 1033
229115 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

### Steps to Reproduce

```
1. Save the below code as echo.py

import tkinter as Tk
from tkinter import *
from xml.dom import minidom
import xml.etree.ElementTree as ET
import webbrowser as wb
import random
import pandas as pd
#import requests
import urllib.request
#import datetime
from dateutil.relativedelta import relativedelta
from urllib.error import URLError, HTTPError
import tkinter.font as tkFont
import ssl
from numpy import arange, sin, pi
#matplotlib.use('TkAgg')
import matplotlib.pyplot as plt
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg, NavigationToolbar2TkAgg
from matplotlib.backend_bases import key_press_handler
from matplotlib.figure import Figure

from tkinter import scrolledtext
from threading import Thread
from time import sleep

root = Tk()
root.title('A Tk Application')
root.mainloop()

Step 2:  run pyinstaller --windowed echo.py

Step 3. After package is complete, launch echo.exe from dist folder.

Step 4: Try comment out the below imports from echo.py
                #import pandas as pd
Step 5: Save echo.py and try recreate the package again by running pyinstaller --windowed echo.py

Step 6:  After package is created launch echo.exe you'll see the TK Gui with empty Window.

```

When I launch echo.exe from command line, 

(base) C:\Downloads\Python\package\TEST\dist\echo>echo.exe
Traceback (most recent call last):
  File "site-packages\pandas\__init__.py", line 26, in <module>
  File "C:\AppData\Local\Continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pandas\_libs\__init__.py", line 4, in <module>
  File "C:\AppData\Local\Continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
  File "pandas/_libs/tslib.pyx", line 1, in init pandas._libs.tslib
ModuleNotFoundError: No module named 'pandas._libs.tslibs.timedeltas'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "echo.py", line 8, in <module>
  File "C:\AppData\Local\Continuum\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pandas\__init__.py", line 35, in <module>
ImportError: C extension: No module named 'pandas._libs.tslibs.timedeltas' not built. If you want to import pandas from the source directory, you may need to run 'python setup.py build_ext --inplace --force' to build the C extensions first.
[11676] Failed to execute script test

Can somebody help please?

**Comment by bjones1** [comment]
Try the current development versions -- the pandas hook was updated recently.
