### ISSUE TITLE
Move to GitLab or another alternative

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#3553]
github has been acquired by Microsoft, awarded with several Big Brother Awards already and being one of the biggest data leeches, it is time to move away from github. Fortunately gitlab is offering a migration service.

https://bigbrotherawards.de/en/2018/technology-microsoft-germany (windows 10)
https://bigbrotherawards.de/2002/lebenswerk-microsoft (life-time award)
https://de.wikipedia.org/wiki/Big_Brother_Awards#2013_2 (xbox)

**Comment by tallforasmurf** [comment]
You won't find me defending M'soft (I've hated that company since the 1980s!). However, in practical terms what do you actually fear? Since PyInstaller is completely open, there's nothing to steal.

**Comment by htgoebel** [comment]
Privacy breaches

**Comment by htgoebel** [comment]
Downvotes without reasoning are not helpful.

**Comment by Legorooj** [comment]
I'm closing this. GitHub is a fine platform, and microsoft have really turned around to support open source (eg Azure DevOps gives Unlimited minutes to open source).
