### ISSUE TITLE
 I try build exe in MAC OS it don't work

### ISSUE THREAD

**Issue by wangfpp** [pyinstaller/pyinstaller#3556]
mac os 10.12.6
python 2.7 
pyinstaller 3.3.1
[warngame.txt](https://github.com/pyinstaller/pyinstaller/files/2074590/warngame.txt)
[error.txt](https://github.com/pyinstaller/pyinstaller/files/2074591/error.txt)

**Comment by htgoebel** [comment]
Please post the *relevant* parts here.

**Comment by wangfpp** [comment]
![image](https://user-images.githubusercontent.com/35289556/41074069-d6c73acc-6a38-11e8-806a-56a9a9019a71.png)
error detail

**Comment by htgoebel** [comment]
Okay, maybe my answer was to terse.
Please post the **relevant part** here as a test, thus it can be quoted easily. The warn-file is *not* relevant. The exact error meassge *is* relevant.

Also you should follow the instructions of the issue-template and use the latest version.

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
