### ISSUE TITLE
Any option to build alias for my bundle on macOS

### ISSUE THREAD

**Issue by orklann** [pyinstaller/pyinstaller#3557]
Currently, I am using py2app to build my Mac app from python code, now I want to try pyinstaller,
but I can not find any option to build my app which just link all resources file to the original files to speed up the building process like `python setup.py py2app -A`

Any help?

**Comment by htgoebel** [comment]
PyInstaller does not have such an option yet.
Can you please explain what exactly this option does? Maybe someone wants to implement this.
