### ISSUE TITLE
Pyinstaller not able to find custom command in django.

### ISSUE THREAD

**Issue by bhargavpatel431997** [pyinstaller/pyinstaller#3569]
I am using [runsslserver ](https://github.com/teddziuba/django-sslserver)(custom) command to run django on HTTPS. before creating executable it is working fine and it is shows me message like,

`Validating models...`
`System check identified no issues (0 silenced).`
`June 11, 2018 - 16:57:54`
`Django version 2.0.4, using settings 'XApp.settings'`
`Starting development server at https://0:8002/`
`Quit the server with CTRL-BREAK.`

i already included app in Installed apps.
**Settings.py**
`INSTALLED_APPS = [...
"sslserver",
...
]`

In **spec** file, i already mentioned package like,
**`Analysis(hiddenimports=[...,'sslserver',...])`**

After generating executable,
I am trying to use it e.g,

`XApp.exe runsslserver 0:8000`

And it shows,
`Unknown command: 'runsslserver'`
`Type 'manage.py help' for usage.`

Also i tried to use it with `XApp.exe runserver 0:8000` and its working fine. so, what is wrong with `runsslserver`. 

please help me, how do i resolve it?

**Comment by htgoebel** [comment]
Django is not fully supported, see [the open issue about django](https://github.com/pyinstaller/pyinstaller/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+django). Somebody needs to take the time and provide a pull-request.

**Comment by bhargavpatel431997** [comment]
I posted answer here. Issue has been solved.
https://stackoverflow.com/questions/50808934/runsslserver-command-not-working-in-django-with-executable-built-with-pyinstalle/50907767#50907767
