### ISSUE TITLE
django.db.utils.operational error

### ISSUE THREAD

**Issue by karthickvalentino** [pyinstaller/pyinstaller#3586]
Hi,
I am developing a image comparison app. I am using django, postgress, dlib, opencv and few other modules. When I bundled it initially I had some hidden import errors, I fixed them. It is running as expected in my system. I am using windows 10 64 bit. It is a one directory build.
But when I run it on different machine( windows 10 64 bit ) I am getting this error, "**django.db.utils.OperationalError: FATAL password authentication failed for user 'user1'** "
and sometimes it throws 
'**django.db.utils.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)Is the server running on host "localhost" (::1) and acceptingTCP/IP connections on port 5432?
could not connect to server: Connection refused (0x0000274D/10061)
Is the server running on host "localhost" (127.0.0.1) and accepting
TCP/IP connections on port 5432?**'

Did I miss any module during build. Should other system install postgress exclusively?

**Comment by aakash9112000** [comment]
n
