### ISSUE TITLE
Encoding issues happening only in macOS .app bundles

### ISSUE THREAD

**Issue by tfeldmann** [pyinstaller/pyinstaller#3592]
Hi! I had encoding problems with a macOS .app bundle made with pyinstaller so I created a minimal example that reproduces the error.

To reproduce first create the virtualenv:
```sh
python3 -m venv .venv
source .venv/bin/activate
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
pip install --index-url=http://download.qt.io/snapshots/ci/pyside/5.11/latest/ pyside2 --trusted-host download.qt.io
```

My setup:
```
$ locale
LANG="de_DE.UTF-8"
LC_COLLATE="de_DE.UTF-8"
LC_CTYPE="de_DE.UTF-8"
LC_MESSAGES="de_DE.UTF-8"
LC_MONETARY="de_DE.UTF-8"
LC_NUMERIC="de_DE.UTF-8"
LC_TIME="de_DE.UTF-8"
LC_ALL=
$ python
Python 3.6.5 (default, Jun 17 2018, 12:13:06)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin
```
macOS 10.13.5 (17F77)

Unzip the example files:
[encoding-bug.zip](https://github.com/pyinstaller/pyinstaller/files/2132474/encoding-bug.zip)
(The application loads the file input.txt and shows it in a QPlainTextEdit) 

Freeze with pyinstaller:
```
pyinstaller test.spec
dist/test
```
[pyi-output.txt](https://github.com/pyinstaller/pyinstaller/files/2132509/pyi-output.txt)

Finally we come to the bug.
Running the application within the bundle from the command line works fine:
```
dist/test.app/Contents/MacOS/test
```
![bildschirmfoto 2018-06-25 um 10 56 05](https://user-images.githubusercontent.com/385566/41841909-c507f06c-7869-11e8-858c-69fad9b8443e.png)

But double-clicking the .app bundle does not:
![bildschirmfoto 2018-06-25 um 11 28 25](https://user-images.githubusercontent.com/385566/41842377-ec8bcce8-786a-11e8-8163-60dcc058cd8e.png)

So I guess there are some issues with the default encoding?
A workaround is to specify utf-8 encoding in every `open()` call but I guess this could be the source of other bugs.

Anyway, thanks for your work on pyinstaller!

**Comment by tallforasmurf** [comment]
So it comes down to this:

        with open(APP_DIR / 'input.txt', 'r') as f:
            edit.setPlainText(f.read())

with different results when bundled vs. not. The [open docs](https://docs.python.org/3.6/library/functions.html#open) say,

> In text mode, if encoding is not specified the encoding used is platform dependent: `locale.getpreferredencoding(False)` is called to get the current locale encoding.

Could you do an even simpler test case that drops all the pyside/Qt machinery and simply reports that value?

**Comment by tfeldmann** [comment]
My new minimal example:

```python
import os
import locale
from pathlib import Path

if __name__ == '__main__':
    output = (Path('~') / 'Desktop' / 'output.txt').expanduser()
    with open(output, 'w') as f:
        f.write(locale.getpreferredencoding(do_setlocale=True) + '\n')
        f.write(locale.getpreferredencoding(do_setlocale=False) + '\n')
        f.write('\n')
        for k, v in os.environ.items():
            f.write(f'{k}: {v}\n')
```

With this version locale and env vars can be compared:

Running via double click (complete output):
```
US-ASCII
US-ASCII

TMPDIR: /var/folders/lt/sg8874fn2lz5y3wcphs91j440000gn/T/
__CF_USER_TEXT_ENCODING: 0x1F5:0x0:0x3
HOME: /Users/thomasfeldmann
SHELL: /bin/zsh
Apple_PubSub_Socket_Render: /private/tmp/com.apple.launchd.j1yBG5oaNZ/Render
SSH_AUTH_SOCK: /private/tmp/com.apple.launchd.EoIzLGOq96/Listeners
PATH: /usr/bin:/bin:/usr/sbin:/sbin
LOGNAME: thomasfeldmann
DISPLAY: /private/tmp/com.apple.launchd.1IWwtKmaJJ/org.macosforge.xquartz:0
XPC_SERVICE_NAME: 0
USER: thomasfeldmann
XPC_FLAGS: 0x0
```

Running via terminal (part of the output, I removed some of my env vars):
```
UTF-8
UTF-8

TERM_SESSION_ID: w0t0p0:3170C4F7-012B-4BE3-B1DB-8DED3286B1FC
XPC_FLAGS: 0x0
LANG: de_DE.UTF-8
LC_CTYPE: de_DE.UTF-8
PWD: /Users/thomasfeldmann/Desktop/pyi-bug
SHELL: /bin/zsh
TERM_PROGRAM_VERSION: 3.1.6
TERM_PROGRAM: iTerm.app
DISPLAY: /private/tmp/com.apple.launchd.1IWwtKmaJJ/org.macosforge.xquartz:0
COLORTERM: truecolor
TERM: xterm-256color

any many more...
```

So it seems when starting a macOS bundle via double click the default encoding is ASCII and LANG variables are not set.

**Comment by tallforasmurf** [comment]
I don't know the bootloader well (and the ANSI C locale stuff is a black hole to me) but I suspect the code [starting here](https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_launch.c#L571) may be relevant. I note some debug messages there, so perhaps run with --debug. Beyond that, I'm butting out.

**Comment by htgoebel** [comment]
Thanks for the small example. PyInstaller does not fiddle with the encoding. Obviously you need to solve this in your environment. 

BTW: You should use `print(..., file=f)` instead of `f.write()`. print is more obvious and you save both building the string and appending the LF.

**Comment by tfeldmann** [comment]
I found a solution to the problem. I set the needed environment variables in the Info.plist:

```python
app = BUNDLE(
    exe,
    name='test.app',
    icon=None,
    bundle_identifier=None,
    info_plist={
        'LSEnvironment': {
            'LANG': 'de_DE.UTF-8',
            'LC_CTYPE': 'de_DE.UTF-8'
        }
    })
```

Now the bundled application behaves like it should.

**Comment by htgoebel** [comment]
Thanks for sharing this.

**Comment by tallforasmurf** [comment]
I added this as a recipe: https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-set-default-language-and-encoding
