### ISSUE TITLE
Cannot run pyinstaller 3.3.1 if virtual environment is installed in path with non-latin characters

### ISSUE THREAD

**Issue by me21** [pyinstaller/pyinstaller#3594]
When I run `pyinstaller my_file.py` it crashes with the following message:

```
File "C:\Users\Зарубкин\Documents\Python Projects\uno-db\venv\Scripts\pyinstaller-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xc7' in file C:\Users\Зарубкин\Documents\Python Projects\uno-db\venv\Scripts\pyinstaller-script.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details
```

The file `pyinstaller-script.py` contains the path to the virtual environment Python executable, but it has some non-latin characters.

PyInstaller version is 3.3.1.

**Comment by htgoebel** [comment]
I understand this is caused by the cyrilic characters in your path. But this is done before PyInstaller even starts. This errors is not related to Pyinstaller but to Python resp. your Python (venv) setup.

**Comment by me21** [comment]
@htgoebel Previous versions of PyInstaller did work for me, so this looks like a regression in PyInstaller.

Won't specifying the file encoding help?

I mean, adding the string in the beginning of `pyinstaller-script.py` and similar files:
```
# coding=cp1251
```
They are now encoded in cp1251 on my machine.

**Comment by htgoebel** [comment]
This file is generated by pip (or whatever command you used for installation). Please try updating pip and setuptools in your virtual environment. if this does not help, please open an issue in one of these project.

**Comment by me21** [comment]
For future reference: a workaround is possible.
1. `pip wheel pyinstaller` (maybe `pip install wheel` first).
2. `pip install <pyinstaller wheel file>`.

Looks like this bug came from setuptools, not from pip.

**Comment by htgoebel** [comment]
Thanks for documenting this.
