### ISSUE TITLE
Independent, PATH-friendly unzipped installation

### ISSUE THREAD

**Issue by gsemet** [pyinstaller/pyinstaller#3596]
Hello

Is it possible to have a pyinstaller executable to install somehow so it won't be unzipped each time it is executed.

I am trying to provide a self contained Command Line Interface user would like to have it somewhere like in `~/.local/bin`, but I would like to avoid the executable to unzip all package each time. I would imagine something like:
- at first execution, unzip somewhere in `~/.local/share/myapp` and this will not be deleted after execution
- next execution skips the unzip.
- any change of version would clean the unzip area to force reunzip

Do you think this is something that can work with pyinstaller?

**Comment by tallforasmurf** [comment]
This would be a very interesting question to ask on the [mailing list](http://www.pyinstaller.org/support.html) as it is not a bug or an issue.

Though I would think you could achieve this using a one-**folder** bundle, zipping it yourself, and telling your user to make an alias to the executable after they unzip the folder.

**Comment by htgoebel** [comment]
As tallforasmurf wrote: You want to use one-folder mode.

**Comment by gsemet** [comment]
I understand, is there a bootstraper for single folder mode so user only click on the installer ?

**Comment by htgoebel** [comment]
No.

**Comment by htgoebel** [comment]
Bu you could write your own spec-file including both exectables along this scratch:

- build sub as a one-folder app, but do not COLLECT
- manipulate the TOCs (see the manual) you would pass to sub-COLLECT() (a.binaries, a.zipfile, a.datas)  thus that every destination path includes an additional path-component. Mind the `exe` path.
- feed this manipulated TOC to main-EXE().

This should give you a huge onefile-exe extracting the bundled sub-exe.

If you find this tip useful, consider donating. Thanks.
