### ISSUE TITLE
-F vary slow and -D Cannot run in the Chinese path

### ISSUE THREAD

**Issue by yihuiyu** [pyinstaller/pyinstaller#3601]
Pyinstaller very convenient software, but now I have two problems, when I use the -f command, start very slow about 14 to 16 seconds, when I use the -d command under the contains the path of the Chinese can't run, I hope someone can help me to solve one problem.Thank you very much

The following is the error message when I use the -d command

F:\pythonstudy\打包基地\0412>F:\pythonstudy\打包基地\0412\dist\Jizhi30412（Demo
）\Jizhi30412.exe
ffffTime 2018-06-28 10:26:19.708725
Qt WebEngine ICU data not found at F:/pythonstudy/??????????/0412/dist/Jizhi3041
2??Demo???/PyQt5/Qt/resources. Trying parent directory...
Qt WebEngine ICU data not found at F:/pythonstudy/??????????/0412/dist/Jizhi3041
2??Demo???/PyQt5/Qt. Trying application directory...
Installed Qt WebEngine locales directory not found at location F:/pythonstudy/??
????????/0412/dist/Jizhi30412??Demo???/PyQt5/Qt/translations\qtwebengine_locales
. Trying application directory...
Qt WebEngine locales directory not found at location F:/pythonstudy/????????/041
2/dist/Jizhi30412??Demo??\qtwebengine_locales. Trying fallback directory... Tran
slations MAY NOT not be correct.
Qt WebEngine resources not found at F:/pythonstudy/??????????/0412/dist/Jizhi304
12??Demo???/PyQt5/Qt/resources. Trying parent directory...
Qt WebEngine resources not found at F:/pythonstudy/??????????/0412/dist/Jizhi304
12??Demo???/PyQt5/Qt. Trying application directory

**Comment by htgoebel** [comment]
If your have a huge package, start-up times for one-file mode are longer, od course, since everything needs to be extracted.

For the other issue:  Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by leeoo** [comment]
Had the same 2nd issue on MacOS months ago. :(

**Comment by yihuiyu** [comment]
@htgoebel I have already submitted the error message, I use - onedir command under the Windows package, and then run under a full English path, this software runs very well, but when I run in the directory contains Chinese For example F:\pythonstudy\打包基地\0412\dist\Jizhi30412（Demo）\Jizhi30412.exe When I run My console will tell me Qt WebEngine ICU data not found at F:/pythonstudy/??????????/0412/dist/Jizhi30412??Demo???/PyQt5/Qt/resources. Trying parent directory... Look at the Chinese in my path being turned into question marks.All the console information has been recorded in my question.I think this may be a bug in pyinstaller. I hope you can help me

**Comment by htgoebel** [comment]
@yihuiyu Can you please check whether this is still an issue when using current PyInstaller v3.6. Please report back. Thanks.

**Comment by yihuiyu** [comment]
I update pyinstaller from 3.4 to 3.6 when use -F my desktop application it much faster，When I use -D ，Chinese is no longer gibberish。However, in the Chinese path, the error is still reported on pyqt, but I don't know whether there is a problem with pyqt or whether pyinstaller is still not compatible with pyqt

**Comment by Legorooj** [comment]
@yihuiyu PyInstaller supports PyQt5 just fine. This bug is unicode related.

**Comment by HackHarry** [comment]
Is this problem solved? I have this problem too.

**Comment by HackHarry** [comment]
My pyinstaller is v4.1

**Comment by BoboTiG** [comment]
@HackHarry could you post a very small repodcutible example of your code? I had such issues but they were fixed long time ago. Also, what is your PyQt version?

**Comment by yihuiyu** [comment]
I still haven't solved the problem but my project is over

**Comment by HackHarry** [comment]
@BoboTiG I found the reason. The problem about Chinese path is caused by QWebEngineView(). I will ask the PySide2 for help.
