### ISSUE TITLE
bokeh can't find the 'subcommands' path

### ISSUE THREAD

**Issue by axil** [pyinstaller/pyinstaller#3602]
I'm packaging a bokeh-based project with pyinstaller.

Using https://github.com/DominicAntonacci/pyinstaller_bokeh_example with bokeh 0.13.0 on Windows 7 x64.

In `commands/subcommands/__init__.py` it uses `listdir` to get all available subcommand python files, which naturally fails: 

```
  File "d:\utilities\development\python36-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 631, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\bokeh\command\subcommands\__init__.py", line 31, in <module>
  File "site-packages\bokeh\command\subcommands\__init__.py", line 13, in _collect
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'D:\\8\\pyinstaller_bokeh_example\\dist\\run_all\\bokeh\\command\\sub
commands'
[21136] Failed to execute script run_all
```

I tried copying the whole bokeh library from my site-packages to the `dist` dir, as suggested by @DominicAntonacci which works, but I'm pretty sure there must be a better way. For example I can't think of how to do it with `--onefile` option.

What is the preferred way of dealing with it with pyinstaller?

**Comment by htgoebel** [comment]
What is this bokeh-think? I assume that bokeh is not adopted to be frozen. Please check the PyInstaller manual, then get in touch with the bokeh project.

**Comment by axil** [comment]
`bokeh` is the second-popular visualization library for python after `matplotlib`. 

Around three times more popular than pyinstaller.

Its author is also unaware of 'this pyinstaller-think'.

This is essentially the same question as #1905. Do you consider the toc-trick described there an official way of listing frozen python files?

PS Not a fantastically helpful answer. The docs are nice, though.

**Comment by htgoebel** [comment]
So if bokeh is using pkgutil.iter_modules, then this is just a duplicate of #1905.

**Comment by axil** [comment]
It isn't. I was going to add `iter_modules` to it, but now it looks suboptimal to me.

I've found a 10 days old PR in bokeh where they discuss pyinstaller support: https://github.com/bokeh/bokeh/pull/8008. 

The example quoted above works fine the hook from my PR #3607. The bokeh lib needs to be patched a little bit: I think the _template dir should better stay in its original place than in the root of the project.
