### ISSUE TITLE
PyInstaller\compat.py:    UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 121: invalid continuation byte

### ISSUE THREAD

**Issue by crmchan** [pyinstaller/pyinstaller#3605]
Dear sir

- Original Code：\Lib\site-packages\PyInstaller\compat.py

> def exec_command(*cmdargs, **kwargs):
    encoding = kwargs.pop('encoding', None)
    out = subprocess.Popen(cmdargs, stdout=subprocess.PIPE, **kwargs).communicate()[0]
    # Python 3 returns stdout/stderr as a byte array NOT as string.
    # Thus we need to convert that to proper encoding.
    if is_py3:
        try:
            if encoding:
                out = out.decode(encoding)
            else:
                # If no encoding is given, assume we're reading filenames from
                # stdout only because it's the common case.
                out = os.fsdecode(out)
        except UnicodeDecodeError as e:
            # The sub-process used a different encoding,
            # provide more information to ease debugging.
            print("CRMtest exec_command cmdargs=%s out=%s"%(cmdargs,out))
            print('--' * 20, file=sys.stderr)
            print(str(e), file=sys.stderr)
            print('These are the bytes around the offending byte:',
                  file=sys.stderr)
            print('--' * 20, file=sys.stderr)
            raise

-  What does it execute?  when execute zmq and we encouter with this issue.

> **exec_command cmdargs=**('D:\\Anaconda3\\envs\\intel\\python.exe', '-c', "\nimport sys\nimport pkgutil\n\n# ``pkgutil.walk_packages`` doesn't walk subpackages of
> zipped files\n# per https://bugs.python.org/issue14209. This is a workaround.\ndef walk_packages(path=None, prefix='', onerror=None):\n    def seen(p, m={}):\n
> if p in m:\n            return True\n        m[p] = True\n\n    for importer, name, ispkg in pkgutil.iter_modules(path, prefix):\n        if not name.startswith(prefix
> ):   ## Added\n            name = prefix + name          ## Added\n        yield importer, name, ispkg\n\n        if ispkg:\n            try:\n                __import
> __(name)\n            except ImportError:\n                if onerror is not None:\n                    onerror(name)\n            except Exception:\n                i
> f onerror is not None:\n                    onerror(name)\n                else:\n                    raise\n            else:\n                path = getattr(sys.modu
> les[name], '__path__', None) or []\n\n                # don't traverse path items we've seen before\n                path = [p for p in path if not seen(p)]\n\n
>          ## Use Py2 code here. It still works in Py3.\n                for item in walk_packages(path, name+'.', onerror):\n                    yield item\n
>      ## This is the original Py3 code.\n                #yield from walk_packages(path, name+'.', onerror)\n\nfor module_loader, name, ispkg in walk_packages(['D:\\\\A
> naconda3\\\\envs\\\\intel\\\\lib\\\\site-packages\\\\zmq\\\\backend'], 'zmq.backend.'):\n    print(name)\n") 
> 
> 
> **out=b'**_cffi_ext.c\r\nD:\\Anaconda3\\envs\\intel\\Lib\\site
> -packages\\zmq\\backend\\cffi\\__pycache__\\_cffi_ext.c(213): fatal error C1083: \xce\xde\xb7\xa8\xb4\xf2\xbf\xaa\xb0\xfc\xc0\xa8\xce\xc4\xbc\xfe: \xa1\xb0sys/un.h\xa1
> \xb1: No such file or directory\r\nzmq.backend.cffi\r\nzmq.backend.cython\r\nzmq.backend.cython._device\r\nzmq.backend.cython._poll\r\nzmq.backend.cython._version\r\nz
> mq.backend.cython.constants\r\nzmq.backend.cython.context\r\nzmq.backend.cython.error\r\nzmq.backend.cython.message\r\nzmq.backend.cython.socket\r\nzmq.backend.cython.
> utils\r\nzmq.backend.select\r\n'
> 

- Package Info
# packages in environment at D:\Anaconda3\envs\intel:
> pyzmq                     17.0.0           py36hfa6e2cd_1
> PyInstaller               3.4.dev0+c0819ddbe           <pip>

- Error Message：

>  DEBUG: collect_data_files - Found files: [('D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\alabaster\\about.html', 'alabaster'), ('D:\\Anaconda3\\envs\\intel\\
> lib\\site-packages\\alabaster\\donate.html', 'alabaster'), ('D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\alabaster\\layout.html', 'alabaster'), ('D:\\Anaconda3\\en
> vs\\intel\\lib\\site-packages\\alabaster\\navigation.html', 'alabaster'), ('D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\alabaster\\relations.html', 'alabaster'), (
> 'D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\alabaster\\theme.conf', 'alabaster'), ('D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\alabaster\\_version.pyo', 'ala
> baster'), ('D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\alabaster\\__init__.pyo', 'alabaster'), ('D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\alabaster\\static
> \\alabaster.css_t', 'alabaster\\static'), ('D:\\Anaconda3\\envs\\intel\\lib\\site-packages\\alabaster\\static\\custom.css', 'alabaster\\static')]
> 179817 DEBUG: Collecting submodules for sphinx.environment.collectors
> 
> 180539 DEBUG: collect_submodules - Found submodules: {'sphinx.environment.collectors.dependencies', 'sphinx.environment.collectors.indexentries', 'sphinx.environment.c
> ollectors.metadata', 'sphinx.environment.collectors.asset', 'sphinx.environment.collectors.title', 'sphinx.environment.collectors', 'sphinx.environment.collectors.toct
> ree'}
> 
> 183530 INFO: Loading module hook "hook-sqlite3.py"...
> 183532 DEBUG: Collecting submodules for sqlite3
> 
> 183820 DEBUG: collect_submodules - Found submodules: {'sqlite3.dump', 'sqlite3.test.factory', 'sqlite3.test.transactions', 'sqlite3.test.types', 'sqlite3.test.userfunc
> tions', 'sqlite3.test.regression', 'sqlite3', 'sqlite3.test.dump', 'sqlite3.test', 'sqlite3.dbapi2', 'sqlite3.test.dbapi', 'sqlite3.test.hooks'}
> 183825 INFO: Loading module hook "hook-sysconfig.py"...
> 183828 INFO: Loading module hook "hook-tables.py"...
> 183829 INFO: Loading module hook "hook-win32com.py"...
> 
> 184114 INFO: Loading module hook "hook-xml.dom.domreg.py"...
> 184115 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
> 
> 184117 INFO: Loading module hook "hook-xml.py"...
> 184124 INFO: Loading module hook "hook-zmq.py"...
> 184125 DEBUG: Collecting submodules for zmq.backend
> 
> 
> 
> CRMtest exec_command cmdargs=('D:\\Anaconda3\\envs\\intel\\python.exe', '-c', "\nimport sys\nimport pkgutil\n\n# ``pkgutil.walk_packages`` doesn't walk subpackages of
> zipped files\n# per https://bugs.python.org/issue14209. This is a workaround.\ndef walk_packages(path=None, prefix='', onerror=None):\n    def seen(p, m={}):\n
> if p in m:\n            return True\n        m[p] = True\n\n    for importer, name, ispkg in pkgutil.iter_modules(path, prefix):\n        if not name.startswith(prefix
> ):   ## Added\n            name = prefix + name          ## Added\n        yield importer, name, ispkg\n\n        if ispkg:\n            try:\n                __import
> __(name)\n            except ImportError:\n                if onerror is not None:\n                    onerror(name)\n            except Exception:\n                i
> f onerror is not None:\n                    onerror(name)\n                else:\n                    raise\n            else:\n                path = getattr(sys.modu
> les[name], '__path__', None) or []\n\n                # don't traverse path items we've seen before\n                path = [p for p in path if not seen(p)]\n\n
>          ## Use Py2 code here. It still works in Py3.\n                for item in walk_packages(path, name+'.', onerror):\n                    yield item\n
>      ## This is the original Py3 code.\n                #yield from walk_packages(path, name+'.', onerror)\n\nfor module_loader, name, ispkg in walk_packages(['D:\\\\A
> naconda3\\\\envs\\\\intel\\\\lib\\\\site-packages\\\\zmq\\\\backend'], 'zmq.backend.'):\n    print(name)\n") 
> 
> 
> 
> out=b'_cffi_ext.c\r\nD:\\Anaconda3\\envs\\intel\\Lib\\site
> -packages\\zmq\\backend\\cffi\\__pycache__\\_cffi_ext.c(213): fatal error C1083: \xce\xde\xb7\xa8\xb4\xf2\xbf\xaa\xb0\xfc\xc0\xa8\xce\xc4\xbc\xfe: \xa1\xb0sys/un.h\xa1
> \xb1: No such file or directory\r\nzmq.backend.cffi\r\nzmq.backend.cython\r\nzmq.backend.cython._device\r\nzmq.backend.cython._poll\r\nzmq.backend.cython._version\r\nz
> mq.backend.cython.constants\r\nzmq.backend.cython.context\r\nzmq.backend.cython.error\r\nzmq.backend.cython.message\r\nzmq.backend.cython.socket\r\nzmq.backend.cython.
> utils\r\nzmq.backend.select\r\n'
> ----------------------------------------
> 'utf-8' codec can't decode byte 0xce in position 121: invalid continuation byte
> These are the bytes around the offending byte:
> ----------------------------------------
> Traceback (most recent call last):
>   File "setup.py", line 413, in <module>
> 
>     run(opts)
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\__main__.py", line 111, in run
>     run_build(pyi_config, spec_file, **vars(args))
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
>     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
>     exec(text, spec_namespace)
>   File "<string>", line 17, in <module>
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
>     self.__postinit__()
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
>     self.assemble()
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
>     module_hook.post_graph()
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
>     self._load_hook_module()
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
>     self.hook_module_name, self.hook_filename)
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\compat.py", line 734, in importlib_load_source
>     return mod_loader.load_module()
>   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
>   File "<frozen importlib._bootstrap_external>", line 823, in load_module
>   File "<frozen importlib._bootstrap_external>", line 682, in load_module
>   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
>   File "<frozen importlib._bootstrap>", line 684, in _load
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\hooks\hook-zmq.py", line 18, in <module>
>     hiddenimports = ['zmq.utils.garbage'] + collect_submodules('zmq.backend')
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 618, in collect_submodules
>     repr(pkg_dir), package))
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 85, in exec_statement
>     return __exec_python_cmd(cmd)
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 72, in __exec_python_cmd
>     txt = exec_python(*cmd, env=pp_env)
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\compat.py", line 578, in exec_python
> 
>     return exec_command(*cmdargs, **kwargs)
>   File "D:\Anaconda3\envs\intel\lib\site-packages\PyInstaller\compat.py", line 367, in exec_command
>     out = out.decode(encoding)
> UnicodeDecodeError: 'utf-8' codec can't decode byte 0xce in position 121: invalid continuation byte`

**Comment by htgoebel** [comment]
Please clean up your original posting. It is very hard to read due to funny characters and wrong line breaks. Thanks.

**Comment by crmchan** [comment]
https://stackoverflow.com/questions/47692960/error-when-using-pyinstaller-unicodedecodeerror-utf-8-codec-cant-decode-byt

**Comment by tallforasmurf** [comment]
In S.O. the fix proposed is to add `errors='ignore'` to [this line in compat.py](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/compat.py#L367). But the line is only executed if this function `exec_command()` is called with an explicit `encoding` argument. And if you read the extensive docstring preceding it, when an explicit `encoding` is passed, "this value is guaranteed to be safely usable."

Also note that UnicodeDecodeError is mentioned in the [release notes for 3.4](https://github.com/pyinstaller/pyinstaller/blob/6ab6c28ae2baa01a520651ef7e87ab38afb7743c/doc/CHANGES.rst) and if you search there are several places where `except UnicodeDecodeError` appears in the code. Based on all that I would say that adding `errors='ignore'` is NOT an appropriate fix; the error is in the code that calls this function and passes an incorrect encoding name, and does not guard against the exception.

So from where was `exec_command()` called, and what was that encoding value? I can't tell anything from the unformatted mess at the top of this bug.

**Comment by frakman1** [comment]
Sorry if this is not the right place to put this note (I can make a new issue if you want) but I get almost the same error when I try to put emojis in my .spec file as a way to generate constants to import into my .py file. The emojis look junky because it's on Windows 7. I copied them from an emoji website  using their `copy to clipboard` functionality into Notepad++. They work in that they render on-screen when used within my .py file and running the program. When I moved them to the .spec file, I get the error below when launching pyinstaller.

PyInstaller 3.4
Win 7 64 bit

excerpt from .spec file:

```python
# -*- mode: python -*-
# -*- encoding: utf-8 -*-

name_emoji = "ðŸ‘¤"
title_emoji = "ðŸŽ–ï¸"
ID_emoji = "ðŸ†”"
office_emoji = "ðŸ’º"
phone_emoji = "ðŸ“ž"
mobile_emoji = "ðŸ“±"
email_emoji = "ðŸ“¬"
group_emoji = "ðŸ‘¥"
phone2_emoji = "â˜Žï¸"
room_emoji = "ðŸ "


# Write version info into _constants.py resource file
with open('_constants.py', 'w') as f:
    f.write("name_emoji = {}\n".format(name_emoji))
    f.write("title_emoji = {}\n".format(title_emoji))
    f.write("ID_emoji = {}\n".format(ID_emoji))
    f.write("office_emoji = {}\n".format(office_emoji))
    f.write("phone_emoji = {}\n".format(phone_emoji))
    f.write("mobile_emoji = {}\n".format(mobile_emoji))
    f.write("email_emoji = {}\n".format(email_emoji))
    f.write("group_emoji = {}\n".format(group_emoji))
    f.write("phone2_emoji = {}\n".format(phone2_emoji))
    f.write("room_emoji = {}\n".format(room_emoji))
 
```

```bash
Traceback (most recent call last):
  File "C:\Users\frak\AppData\Local\Programs\Python\Python37\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.4', 'console_scripts', 'pyinstaller')()
  File "c:\users\frak\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\frak\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\frak\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\frak\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\building\build_main.py", line 783, in build
    text = f.read()
  File "c:\users\frak\appdata\local\programs\python\python37\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 6556: character maps to <undefined>
```

**Comment by bjones1** [comment]
Thanks! I'll work on a fix.

**Comment by htgoebel** [comment]
@crmchan Maybe you cleaned up our original posting, But it still hard to read. Please take your time putting this into popper mark-down, thus it is ease to read and emphasizes on the important points. Otherwise I will not take *my* time working on this.

@frakman1 The original post is such a clutter, one can not tell what it is about and thus not whether your issue is related. But I assume your issue is separate. Thus please open a separate issue (even if bjones already started working on this) You issue looks important and precise enough to become mentioned in the changelog.

**Comment by frakman1** [comment]
@htgoebel [done](https://github.com/pyinstaller/pyinstaller/issues/3899)

**Comment by Ali6259** [comment]
I have an issue of when using pyinstaller --onefile filename.py i get an error: UnicodeDecodeError: 'charmap' codec can't decode byte.

import glob
import os.path, time
from collections import defaultdict
from datetime import datetime
from zipfile import BadZipFile
from openpyxl import load_workbook

FOLDER_PATH = 'K:/'  # Relative or absolute Path to the folder to be scanned.
DB_PATH = 'K:/MelnicomUtils/DB.xlsx'  # Path to the database excel file.
LOG_PATH = 'K:/MelnicomUtils/log.xlsx'

""" FOLDER_PATH = 'C:/Users/melni/Desktop/לקוחות/momentum/files/'  # Relative or absolute Path to the folder to be scanned.
DB_PATH = 'C:/Users/melni/Desktop/לקוחות/momentum/DB.xlsx'  # Path to the database excel file.
LOG_PATH = 'C:/Users/melni/Desktop/לקוחות/momentum/log.xlsx' """

logWB = load_workbook(filename=LOG_PATH, data_only=True)
log_row= 2
fileC = 0 #File counter

reports_sheet = 'ניתוח דוחות'
obligo_sheet = 'אובליגו'
analyse_sheet_db = 'ניתוח דוחות-מאזנים'
needed_sheetnames = [reports_sheet, obligo_sheet]
year_cells = ['C2', 'E2', 'G2', 'I2', 'K2']


def isvalid(wb,file):
    """
    Checks if the supplied excel workbook is valid.
    :param wb: The excel workbook
    :type wb: Workbook
    :return: Returns True if the workbook is valid and should be used for data extraction.
    :rtype: bool
    """
    try:
        sheetnames = list(map(str.strip, wb.sheetnames))
        if not all(elem in sheetnames for elem in needed_sheetnames):
            write_to_log_file(file ,"חסר גליון ניתוח דוחות או אובליגו או ניתוח דוחות-מאזנים")
            return False

        reports = wb[reports_sheet]
        try:
            if not any('מאזנים' in cell.value for cell in reports['B'] if cell.value is not None):
                write_to_log_file(file,"חסרה המילה מאזנים בעמודה B")
                return False
        except:  
            write_to_log_file(file,"תקלה בזמן חיפוש המילה מאזנים בעמודה B")
            return False

        
        a1 = reports['A1'].value
        if not a1 or 'תאריך הבוחן' not in a1:
            write_to_log_file(file,"חסר תאריך הבוחן")
            return False

        try:
            obligo = wb['אובליגו']
        except KeyError:
            obligo = wb['אובליגו ']  # TODO: Should this be like that?

        if 'שם הבנק:' != obligo['C2'].value:
            write_to_log_file(file,"חסר שם הבנק")
            return False

        return True
    except:
        return False


def rec_dd():
    return defaultdict(rec_dd)


def get_data(wb):
    """
    Gets data from the supplied Excel workbook.
    :param wb: The supplied Excel workbook
    :type wb: Workbook
    :return: Returns a dict containing the extracted data
    :rtype: dict
    """
    data = rec_dd()

    ws = wb[reports_sheet]
    try:
        specified_date = ws['C1'].value.date()
        data['date'] = specified_date
    except AttributeError:
        return None
    last_day_of_year = datetime.today().date().replace(month=12, day=31, year=specified_date.year)

    company = ws['E1'].value

    # Sheet 1 - Table 1
    for i, cell in enumerate(year_cells):
        year = ws[cell].value

        if year == specified_date.year and specified_date != last_day_of_year:
            continue

        for row in ws.iter_rows(min_row=5, max_col=12):

            if row[1].value == 'מאזנים':
                break

            value = row[i * 2 + 2].value
            percentage = row[i * 2 + 3].value
            header = row[1].value

            if not value:
                continue

            data[reports_sheet][company][year][header] = {
                'value': value,
                'percentage': percentage
            }
            #print("Added to sheet " + reports_sheet + " for company " + company + " year " + year + " header " + header + ":")
            #print("Value: " + value + ", Percentage: " + percentage)

    for cell in ws['B']:
        if cell.value == 'מאזנים':
            year_row = cell.row + 2
            year_cells_table2 = [s + str(year_row) for s in ['C', 'E', 'G']]

    # Sheet 1 - Table 2
    for i, cell in enumerate(year_cells_table2):
        year = ws[cell].value

        if year == specified_date.year and specified_date != last_day_of_year:
            continue

        for row in ws.iter_rows(min_row=year_row, max_col=8):

            value = row[i * 2 + 2].value
            percentage = row[i * 2 + 3].value
            header = row[1].value

            if not value or not header:
                continue

            data[analyse_sheet_db][company][year][header] = {
                'value': value,
                'percentage': percentage
            }

    # Sheet 2 - Table 3
    try:
        ws = wb['אובליגו']
    except KeyError:
        ws = wb['אובליגו ']
    values = {}
    oldest = None
    for row in ws.iter_rows(min_row=2, min_col=3):
        header = row[0].value
        if not header:
            break
        elif header == 'מעודכן לתאריך:':
            try:
                oldest = max(entry.value for entry in row if isinstance(entry.value, datetime))
            except ValueError:
                break
            continue
        elif header == 'שם הבנק:':
            try:
                col = next(entry.column for entry in row if entry.value == 'סה"כ') - 3
            except:
                break
            continue

        try:
            value = row[col].value
        except:
            break

        if value == 'סה"כ' or not value:
            continue

        values[header] = value

    if oldest is not None:
        data[obligo_sheet] = {
            'company': company,
            'year': oldest.year,
            'values': values
        }
    else:
        data[obligo_sheet] = {
        }

    return data


def add_reports(ws, data, date=None,file=""):
    """
    Adds data to the first two sheets.
    :param ws: The worksheet
    :param data: The dict containing the data from the original excel file
    """

    # set default values
    date_column = 5
    year_column = 4
    company_column = 3
    updateF = False
    # Get Year column
    for row in ws.iter_rows(min_row=1, max_row=1):
        for cell in row:
            if cell.value == 'שנה':
                year_column = cell.column
            elif cell.value == 'shtDate':
                date_column = cell.column
            elif cell.value == 'חפ':
                company_column = cell.column

    for company, years in data.items():
        for year, entries in years.items():
            row_to_be_changed = 0
            for row in ws.iter_rows(min_col=company_column, max_col=year_column):
                if row[0].value == company and row[1].value == year:
                    row_to_be_changed = row[0].row
                    try:
                        if date < row[2].value and date:
                            return False
                    except TypeError:
                        write_to_log_file(file,"נכשל שורה 220")
                        pass
                    except:
                        pass
                    break

            if row_to_be_changed == 0:
                row_to_be_changed = ws.max_row + 1
                ws.cell(row_to_be_changed,date_column).value = date
                updateF = True
            else:
                DBshtDate = ws.cell(row_to_be_changed,date_column).value
                srcShtDate = date
                if DBshtDate is None or str(srcShtDate) >   str(DBshtDate):
                    updateF = True

            ws.cell(row_to_be_changed, year_column).value = year  
            ws.cell(row_to_be_changed, company_column).value = company
            # write_to_log_file(file,"sucess")
            
            
            if date:
                ws.cell(row_to_be_changed, year_column + 1).value = date

            for header, entry in entries.items():
                if header == None:
                    header = ""
                for row in ws.iter_rows(min_row=1, max_row=1):
                    for cell in row:
                        if header == cell.value:
                            ws.cell(row_to_be_changed, cell.column).value = entry['value']
                        elif str(header) + "P" == cell.value:
                            ws.cell(row_to_be_changed, cell.column).value = entry['percentage']
    return updateF
def write_to_log_file(FileName,Status):
    logWS = logWB['log'] 
    log_row =  logWS.max_row+1
    logWB['log'].cell(log_row,1).value = FileName
    logWB['log'].cell(log_row,2).value = datetime.now()
    logWB['log'].cell(log_row,3).value = Status
    logWB['log'].cell(log_row,4).value = datetime.fromtimestamp(os.path.getmtime(FileName))
    if  log_row % 3 == 0:
        logWB.save(LOG_PATH)
    # logWB.close

    
def add_obligo_reports(ws, data, file):
    """
    Adds data to the third ("obligo") sheet
    :param ws: The worksheet
    :param data: The dict containing the data from the original excel file
    :return:
    """
    if not data:
        return

    for row in ws.iter_rows(min_row=1, max_row=1):
        for cell in row:
            if cell.value == 'שנה':
                year_column = cell.column
            elif cell.value == 'חפ':
                company_column = cell.column

    row_to_be_changed = 0
    for row in ws.iter_rows(min_col=company_column, max_col=year_column):
        if row[0].value == data['company'] and row[1].value == data['year']:
            row_to_be_changed = row[0].row
            break

    if row_to_be_changed == 0:
        row_to_be_changed = ws.max_row + 1
    ws.cell(row_to_be_changed, year_column).value = data['year']
    ws.cell(row_to_be_changed, company_column).value = data['company']

    for header, entry_value in data['values'].items():
        for row in ws.iter_rows(min_row=1, max_row=1):
            for cell in row:
                if header == cell.value:
                    ws.cell(row_to_be_changed, cell.column).value = entry_value


def add_to_db(data,file):
    """
    Adds the dict data to database excel.
    :param data: A dict containing the extracted data
    :type data: dict
    """
    
    if add_reports(DBwb[reports_sheet], data[reports_sheet], data['date'],file):
        add_reports(DBwb[analyse_sheet_db], data[analyse_sheet_db],file)
        add_obligo_reports(DBwb[obligo_sheet], data[obligo_sheet],file)
        print("Saving database file to " + DB_PATH)
        DBwb.save(DB_PATH)
   


def scan_folder(path):
    """
    Scans folder and all subfolders of supplied path for .xlsx files.
    Then every file is checked for its validity. If it is valid, the
    data gets extracted and added to the database excel file.
    :param path: Path that should be scanned
    :type path: str
    """
    global fileC
    files = glob.glob(path + '/**/*.xlsx', recursive=True)
    print("Scanning " + str(len(files)) + " files.")

    for file in files:
        file.__getattribute__
        if '.xlsx' not in file:
            continue

        try:
            wb = load_workbook(filename=file, data_only=True)
        except:
            write_to_log_file(file,"לא מצליח לטעון את הקובץ")
            continue

        if not isvalid(wb,file):
           continue

        write_to_log_file(file,"קובץ תקין")
        fileC += 1
        data = get_data(wb)

        if not data:
            continue

        add_to_db(data,file)


if __name__ == "__main__":
    DBwb = load_workbook(filename=DB_PATH, data_only=True)
    scan_folder(FOLDER_PATH)
    print("Scan complete.")
    #Update log file
    """   fo = open(file="./log.txt",mode="a",encoding="utf-8")
    dt = datetime.now()
    fo.write("\n" + str(dt) + ": Scan of " + str(fileC) + " valid files is complete.")
    fo.close()
    print("Log updated.") """
else:
    print("ERROR, cannot scan.")

**Comment by htgoebel** [comment]
@Ali6259 I suggest you to learn how to contribute to a bug report. Just pasting a *huge* pile of code *does not help* in any way. Not formatting as code and posting the same huge pile of code to severl issues is even worse,. The only effect is that you are wasting volunteers valuable time.

**Comment by Legorooj** [comment]
Stale.
