### ISSUE TITLE
No module named path

### ISSUE THREAD

**Issue by DaytonaJohn** [pyinstaller/pyinstaller#3609]
Have been using `Pyinstaller` to produce an `exe` for my app for some time, but recently, I started getting a ` ImportError: No module named path` when running the resulting `exe`. Not sure when it changed, since I haven't had to use it recently. I tried the stable `Pyinstaller` version and a development version, and got the same error. The error seems to be triggered by the line `import kivy.garden.filebrowser` that has worked fine in the past. 

 OS: Windows 10
Pyinstaller: 3.4.dev0+fd00db32b
Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)] on win32
Kivy: v1.10.0

The `Pyinstaller` log is [here](https://gist.github.com/DaytonaJohn/0873aa0284daab3ae76d2ddea6ca868c)

I believe the relevant section of the verbose output from the `exe` is:

```
 # kivy.garden.errno not found in PYZ
 # kivy.garden.nt not found in PYZ
 import ntpath as kivy.garden.ntpath # PyInstaller PYZ (__path__ override: )
 import stat as kivy.garden.stat # PyInstaller PYZ (__path__ override: )
 import genericpath as kivy.garden.genericpath # PyInstaller PYZ (__path__ override: )
 import warnings as kivy.garden.warnings # PyInstaller PYZ (__path__ override: )
 import linecache as kivy.garden.linecache # PyInstaller PYZ (__path__ override: )
 import types as kivy.garden.types # PyInstaller PYZ (__path__ override: )
 # kivy.garden._warnings not found in PYZ
 Traceback (most recent call last):
   File "main.py", line 4, in <module>
     import kivy.garden.filebrowser
   File "c:\users\john\appdata\local\temp\pip-install-cvsew6\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
   File "site-packages\kivy\garden\__init__.py", line 68, in <module>

   File "c:\users\john\appdata\local\temp\pip-install-cvsew6\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 161, in load_module
   File "c:\users\john\appdata\local\temp\pip-install-cvsew6\PyInstaller\PyInstaller\loader\pyimod03_importers.py", line 395, in load_module
   File "os.py", line 120, in <module>
 ImportError: No module named path
[4960] Failed to execute script main
```
A simple app that demonstrates the issue:

```
import kivy
from kivy.app import App
from kivy.uix.label import Label
import kivy.garden.filebrowser

import sys


class PyinstallerBugApp(App):

    def build(self):
        return Label(text='Bug Test')

if __name__ == '__main__':
    app = PyinstallerBugApp()
    try:
        print('running Python: ' + str(sys.version))
        print('running Kivy: ' + str(kivy.__version__))
        app.run()
    except Exception:
        print('caught exception')

```

And my `spec` file:
```
# -*- mode: python -*-

from kivy.deps import sdl2, glew

block_cipher = None
options = [ ('v', None, 'OPTION')]

a = Analysis(['main.py'],
             pathex=['C:\\Users\\John\\Documents\\PyCharmProjects\\pyinstallerbug'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          options,
          a.binaries,
          a.zipfiles,
          a.datas,
          *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins)],
          name='possibleBug',
          debug=True,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True)

```

**Comment by DaytonaJohn** [comment]
Turns out to be a path issue, was getting the wrong pyinstaller.

**Comment by taosean** [comment]
I have the same error as yours when I have the code `import os` in my script. How did you solve this error.
>   File "os.py", line 120, in <module>
 ImportError: No module named path

**Comment by DaytonaJohn** [comment]
I have both Python2 and Python3 installed and Python2 was first in my path. I modified my system PATH environment variable to put Python3 before Python2, and now it all works as expected.

**Comment by assslove** [comment]
i meet the same error, can you explian details, or list the config?

**Comment by letoncse** [comment]
I'm getting the same issue , I'm using Python 2.7.11 version
`File "os.py", line 120, in <module>
from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep,
ImportError: No module named path`

How can i resolve this ? 
Thanks in advance !
