### ISSUE TITLE
pyinstaller --onefile build on Win7_32b is reporting missing DLL on Win7_64b

### ISSUE THREAD

**Issue by Peter812606** [pyinstaller/pyinstaller#3613]
I have build a set of VirtualBox machines made of Windows 7 up to 10 in both 32 and 64 bit to test tools that we are developing for internal use. I have created simple "hello world" script to see how well it will work across different platforms. My development machine is Windows 7 32bit English running Python  3.6.5 and pyInstaller 3.3.1
When I create package with "--onefile" option it works correctly on 32bit test machine, but on 64bit it says:
"The procedure entry point ucrtbase.terminate could not be located in dynamic link library api-ms-crt-runtime-l1-1-0.dll"

I have checked temp folder and all the DLL files are there (as per screenshot and list below). If I use "-D" and run the test it works fine, but fails when "--onefile" is used. I have copied "ucrtbase.dll" from temp directory to file location and it has fixed the problem. Is there a way to force packed script to look for that file in temp directory or do I have to distribute ucrtbase.dll separately? 

Debug from console:

> C:\Users\test\Desktop\test>test
> [3004] PyInstaller Bootloader 3.x
> [3004] LOADER: executable is C:\Users\test\Desktop\test\test.exe
> [3004] LOADER: homepath is C:\Users\test\Desktop\test
> [3004] LOADER: _MEIPASS2 is NULL
> [3004] LOADER: archivename is C:\Users\test\Desktop\test\test.exe
> [3004] LOADER: Extracting binaries
> [3004] LOADER: Executing self as child
> [3004] LOADER: set _MEIPASS2 to C:\Users\test\AppData\Local\Temp\_MEI30042
> [3004] LOADER: Setting up to run child
> [3004] LOADER: Creating child process
> [3004] LOADER: Waiting for child process to finish...
> [3016] PyInstaller Bootloader 3.x
> [3016] LOADER: executable is C:\Users\test\Desktop\test\test.exe
> [3016] LOADER: homepath is C:\Users\test\Desktop\test
> [3016] LOADER: _MEIPASS2 is C:\Users\test\AppData\Local\Temp\_MEI30042
> [3016] LOADER: archivename is C:\Users\test\Desktop\test\test.exe
> [3016] LOADER: SetDllDirectory(C:\Users\test\AppData\Local\Temp\_MEI30042)
> [3016] LOADER: Already in the child - running user's code.
> [3016] LOADER: manifestpath: C:\Users\test\AppData\Local\Temp\_MEI30042\test.exe
> .manifest
> [3016] LOADER: Activation context created
> [3016] LOADER: Activation context activated
> [3016] LOADER: Python library: C:\Users\test\AppData\Local\Temp\_MEI30042\python
> 36.dll
> Error loading Python DLL 'C:\Users\test\AppData\Local\Temp\_MEI30042\python36.dl
> l'.
> LoadLibrary: The specified procedure could not be found.
> [3004] LOADER: Back to parent (RC: -1)
> [3004] LOADER: Doing cleanup
> [3004] LOADER: Freeing archive status for C:\Users\test\Desktop\test\test.exe

Directory containing temporary files:

>  Volume in drive C has no label.
>  Volume Serial Number is E8A7-D11D
> 
>  Directory of C:\Users\test\AppData\Local\Temp\_MEI30042
> 
> 02/07/2018  16:39    <DIR>          .
> 02/07/2018  16:39    <DIR>          ..
> 02/07/2018  16:39             3,072 api-ms-win-core-console-l1-1-0.dll
> 02/07/2018  16:39             3,072 api-ms-win-core-datetime-l1-1-0.dll
> 02/07/2018  16:39             3,072 api-ms-win-core-debug-l1-1-0.dll
> 02/07/2018  16:39             3,072 api-ms-win-core-errorhandling-l1-1-0.dll
> 02/07/2018  16:39             5,120 api-ms-win-core-file-l1-1-0.dll
> 02/07/2018  16:39            11,608 api-ms-win-core-file-l1-2-0.dll
> 02/07/2018  16:39            11,608 api-ms-win-core-file-l2-1-0.dll
> 02/07/2018  16:39             3,072 api-ms-win-core-handle-l1-1-0.dll
> 02/07/2018  16:39             3,584 api-ms-win-core-heap-l1-1-0.dll
> 02/07/2018  16:39             3,584 api-ms-win-core-interlocked-l1-1-0.dll
> 02/07/2018  16:39             3,584 api-ms-win-core-libraryloader-l1-1-0.dll
> 02/07/2018  16:39            14,168 api-ms-win-core-localization-l1-2-0.dll
> 02/07/2018  16:39             3,584 api-ms-win-core-memory-l1-1-0.dll
> 02/07/2018  16:39             3,584 api-ms-win-core-namedpipe-l1-1-0.dll
> 02/07/2018  16:39             3,584 api-ms-win-core-processenvironment-l1-1-0.dll
> 02/07/2018  16:39             4,608 api-ms-win-core-processthreads-l1-1-0.dll
> 02/07/2018  16:39            12,120 api-ms-win-core-processthreads-l1-1-1.dll
> 02/07/2018  16:39             3,072 api-ms-win-core-profile-l1-1-0.dll
> 02/07/2018  16:39             3,072 api-ms-win-core-rtlsupport-l1-1-0.dll
> 02/07/2018  16:39             3,072 api-ms-win-core-string-l1-1-0.dll
> 02/07/2018  16:39             4,096 api-ms-win-core-synch-l1-1-0.dll
> 02/07/2018  16:39            12,120 api-ms-win-core-synch-l1-2-0.dll
> 02/07/2018  16:39             4,096 api-ms-win-core-sysinfo-l1-1-0.dll
> 02/07/2018  16:39            11,608 api-ms-win-core-timezone-l1-1-0.dll
> 02/07/2018  16:39             3,072 api-ms-win-core-util-l1-1-0.dll
> 02/07/2018  16:39            12,632 api-ms-win-crt-conio-l1-1-0.dll
> 02/07/2018  16:39            15,704 api-ms-win-crt-convert-l1-1-0.dll
> 02/07/2018  16:39            12,120 api-ms-win-crt-environment-l1-1-0.dll
> 02/07/2018  16:39            13,656 api-ms-win-crt-filesystem-l1-1-0.dll
> 02/07/2018  16:39            12,632 api-ms-win-crt-heap-l1-1-0.dll
> 02/07/2018  16:39            12,120 api-ms-win-crt-locale-l1-1-0.dll
> 02/07/2018  16:39            22,360 api-ms-win-crt-math-l1-1-0.dll
> 02/07/2018  16:39            12,632 api-ms-win-crt-process-l1-1-0.dll
> 02/07/2018  16:39            16,216 api-ms-win-crt-runtime-l1-1-0.dll
> 02/07/2018  16:39            17,752 api-ms-win-crt-stdio-l1-1-0.dll
> 02/07/2018  16:39            17,752 api-ms-win-crt-string-l1-1-0.dll
> 02/07/2018  16:39            14,168 api-ms-win-crt-time-l1-1-0.dll
> 02/07/2018  16:39            12,120 api-ms-win-crt-utility-l1-1-0.dll
> 02/07/2018  16:39           739,333 base_library.zip
> 02/07/2018  16:39           157,184 pyexpat.pyd
> 02/07/2018  16:39         3,295,744 python36.dll
> 02/07/2018  16:39            16,384 select.pyd
> 02/07/2018  16:39             1,027 test.exe.manifest
> 02/07/2018  16:39           922,944 ucrtbase.dll
> 02/07/2018  16:39           888,832 unicodedata.pyd
> 02/07/2018  16:39            83,784 VCRUNTIME140.dll
> 02/07/2018  16:39            71,168 _bz2.pyd
> 02/07/2018  16:39         1,114,112 _hashlib.pyd
> 02/07/2018  16:39           176,640 _lzma.pyd
> 02/07/2018  16:39            56,320 _socket.pyd
> 02/07/2018  16:39         1,452,544 _ssl.pyd
>               51 File(s)      9,308,184 bytes
>                2 Dir(s)  24,824,385,536 bytes free
> 

![pyinstaller-single-file-32b-python3 -on-vb-win7_64b](https://user-images.githubusercontent.com/40768401/42174567-b752a1a4-7e1a-11e8-8dcb-b8e5c0de6862.jpg)

**Comment by htgoebel** [comment]
Please read https://pyinstaller.readthedocs.io/en/v3.3.1/usage.html#windows
