### ISSUE TITLE
Executable crashes due to ucrtbase.DLL on Python 3.7

### ISSUE THREAD

**Issue by NHades** [pyinstaller/pyinstaller#3615]
When using Python 3.4.4 my executable runs ok. 
After upgrading to Python 3.7 I started seeing this issue:

Problem signature:
  Problem Event Name:   APPCRASH
  Application Name:     xxxx.exe
  Application Version:  0.0.0.0
  Application Timestamp:        5a2e9fe6
  Fault Module Name:    ucrtbase.DLL
  Fault Module Version: 10.0.14393.2247
  Fault Module Timestamp:       5adc1a6f
  Exception Code:       40000015
  Exception Offset:     000891fa
  OS Version:   6.1.7601.2.1.0.256.4
  Locale ID:    1033
  Additional Information 1:     9612
  Additional Information 2:     9612f0a8079e8be00e043cbb1ac8ab11
  Additional Information 3:     214f
  Additional Information 4:     214f965d178e9721368d0b109431385c

OS:  Windows 7 64-bit
Python: 3.7-32bit
pyinstaller: 3.3.1

I noticed that the (ucrtbase.DLL) copied is the 64-bit one.

**Comment by htgoebel** [comment]
Python 3.7 is not yet supported. Also see the manual https://pyinstaller.readthedocs.io/en/v3.3.1/usage.html?#windows

**Comment by antlu** [comment]
Am I right that Python 3.7 is now supported?
I face the same issue with PyInstaller 3.4 and Python 3.7.1 x32 on Windows 10 x64. Periodically.

**Comment by htgoebel** [comment]
> Am I right that Python 3.7 is now supported?

Yes.

**Comment by 32kda** [comment]
I just faced the same problem with Python 3.6.8. Why could this happen?

**Comment by linzhi** [comment]
I solved this problem by change pip source...

**Comment by meichthys** [comment]
@linzhi Could you elaborate on what you mean by 'pip source'?

**Comment by jesse77169** [comment]
Oh, my God， I   just faced the same problem with Python 3.6.8.    The problem has not been solved yet?

**Comment by bwoodsend** [comment]
The universal C runtime (`ucrtbase`) is a Windows 11 only feature. Later versions of Windows 10 can opt into installing it. So if you've found an installation of Python which is linked against it then you shouldn't expect any application you build to work on anything other than Windows 11.
