### ISSUE TITLE
Why are api-ms-win-core*.dll now added?

### ISSUE THREAD

**Issue by mrgou** [pyinstaller/pyinstaller#3618]
Not really an issue, but something I'd like to understand. I've run pyInstaller on my Python program, and contrary to the last time, it now adds a bunch of api-ms-win-core*.dll files, along with a cryptography-2.2.2-py3.6.egg-info folder and ucrtbase.dll.

Last time I ran it (on the same PC), I only had VCRUNTIME140.dll and python36.dll.

What could have changed (in my program or in my environment) to cause this (e.g. an update in the the C runtime library)?

Thanks!

R.

**Comment by htgoebel** [comment]
Please read the manual. https://pyinstaller.readthedocs.io/en/v3.3.1/usage.html?#windows

**Comment by mrgou** [comment]
I understand that, but what I'd like to understand is what could have caused it to happen now and not the previous time I packaged my program (which underwent only very minor changes).
