### ISSUE TITLE
exe shows msg "No Disk, There is no disk in the drive...." when drive is no longer available

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#362]
**Original date**: 2011/06/16
**Original reporter**: *alarmz AND gmail DOT  COOM *

step to reproduce
1. I have 3 hard disks driver.
2. I copy pyInstaller1.5 to Disk2 rather than Disk0
3. execute python Makespec.py -D F:\Myprogram\demo.py
4. execute python Build.py ..\demo\demo.spec
5. pyInstaller will make a exe file for me
6. I copy that file to client machine, and client machine have USB card reader, it have Disk2 already mount but no memory card inside.
7. When I execute the demo.exe in the client machine, it will show fallow message
   
   > "No Disk, There is no disk in the drive.  Please insert a disk into drive \Device\Harddisk3\DR3" [cancel][Try Again][Continue]
   
   under windows 2008, and show 
   
   > "No Disk, Exception Processing Message" [cancel][TryAgain][Continue] 
   
   under windows XP sp3

[Image](https://lh3.googleusercontent.com/EDKSsmqfjm_C4R0w6kc8G1EugzHaLUKENlo8kBfsPYJnMoVX-8AP00Un9lj8EJLL9rRf8k913EWDjDTRkYGpMLqzXQ=s512)
##### What happened instead

Execute binary program created by pyInstaller1.5 or trunk version under windows, will popup error message

> "No Disk, There is no disk in the drive. Please insert a disk into drive \Device\Harddisk3\DR3" [cancel][Try Again][Continue]

[Image](https://lh4.googleusercontent.com/jZb9hjw8M_YfBUrkezUJl0LrZqInBEXgmivqpndc8a2nFzhpjgrBoXDZtPkSnPBYK7mYPEQr7b0wUDIaxkVobfBInA=s512)
##### What you expect to happen

When copy pyInstaller program into Disk0 and rebuild the binary file, the error message just gone. this problem cost me a lot of time, hop pyInstaller develop team can take a look.

**Comment by c1728p9** [comment]
Hi @matysek , I have seen this issue as well.  This happens to me if an exception occurs and the file would have been located on the drive that isn't present.  I'm using pyinstaller 2.1.  Let me know if there is anything you would like me to try out.

**Comment by lsnk** [comment]
Hello, same error on only one machine (win7 x64). I've compiled 2 exe files (both with 32 bit pythons), One from winXP and other one from win10. Same messages for both. "No Disk, There is no disk in the drive. Please insert a disk into drive \Device\Harddisk3\DR3". 

I have other win7 x64 machine. Same exe file - no error. Other winXP machines also work fine. Don't know what can possibly be a reason error. I have no staic disk paths in a program.

**Comment by tallforasmurf** [comment]
I googled the phrase "No Disk, There is no disk in the drive. Please insert a disk into drive" and got many, many hits. This is an error message that comes up from many different apps including Notepad.

Many of the hits are in Microsoft.com support forums. Please review some of these for possible fixes. They seem to be advising running virus checks.

**Comment by htgoebel** [comment]
This issue is six years old now and we still have no clue what to do. Nobody worked on it and comments are rare and not helpful for solving this issue. So I'm closing this now.

**Comment by c1728p9** [comment]
Hi @htgoebel, with 2.1 I was able to reliably reproduce this issue. I can provide you with any info you need to reproduce this problem. Just let me know how I can help.

**Comment by htgoebel** [comment]
@c1728p9 Thanks for this offer, but PyInstaller 2.1 is no longer supported. We are only interested if the error shows up with 3.2.1. But even then, this is hard to reproduce, so you would need to provide a concrete place in the bootloader-code – or even a pull-request.
