### ISSUE TITLE
rewrap one exe and one binary file to one new exe file in windows

### ISSUE THREAD

**Issue by orangeSi** [pyinstaller/pyinstaller#3623]
Hi~
    I first used pyinstall to wrap my python script to one exe,  then I want to rewrap to one new exe with the old exe and anthor one binary file(sqlite db file) ? Is that possible ?

thanks~
Si

**Comment by htgoebel** [comment]
Yes

**Comment by orangeSi** [comment]
thanks! Could you give me a example command?

**Comment by orangeSi** [comment]
I want to add sqlite.db to old.exe,  so tried ` pyinstaller -r sqlite.db old.exe `, but it didn't work...

thanks for help~

**Comment by htgoebel** [comment]
Please read the manual.
