### ISSUE TITLE
PyInstaller fails to import module created using F2PY (Mac OSX 10.6, Python2.7)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#363]
**Original date**: 2011/06/18
**Original reporter**: *escheu2*

I'm trying to bundle a PyQt4 gui script into a standalone app using PyInstaller.  So far, I've had good success in creating these standalone apps but just recently found a problem when trying to import modules created uisng SciPy's f2py (Fortran --> Python)...

The idea is to connect a gui button click to the execution of compiled Fortran code all wrapped up using Python and PyInstaller...

PyInstaller seems to build everything without error, but the app will not launch.  The Traceback following failure to launch the app is:
```
ImportError: numpy.core.multiarray failed to import

Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/Users/Edward/pyinstaller/iu.py", line 436, in importHook
    mod = _self_doimport(nm, ctx, fqname)
  File "/Users/Edward/pyinstaller/iu.py", line 505, in doimport
    mod = director.getmod(nm)
  File "/Users/Edward/pyinstaller/iu.py", line 297, in getmod
    mod = owner.getmod(nm)
  File "/Users/Edward/pyinstaller/iu.py", line 109, in getmod
    mod = imp.load_module(nm, fp, attempt, (ext, mode, typ))
ImportError: numpy.core.multiarray failed to import
([0x0-0x13c13c].Mactestgui[2902]): Exited with exit code: 255
```

Any ideas would be helpful.

**Comment by htgoebel** [comment]
This is old and outdated, solution is simple (import numpy), so we do not care.
