### ISSUE TITLE
Update waf to 2.0.9 & new python37 merge is not properly working.

### ISSUE THREAD

**Issue by Loggan08** [pyinstaller/pyinstaller#3631]
Latest waf is [here](https://gitlab.com/ita1024/waf), it behaves normally on python 3.6.6 when pyinstaller is built against that.

Second note is that the new python37 merge is not completely working.

I get errors about pyimod01 , 02 and 03

Hope this issue-report helps.

**Comment by htgoebel** [comment]
Sorry to say, but this isse-report is of no help.

0) Do not mix unrelated topics in one issue. This hinders working with them.
1) Re waf: any reason e should update.
2) Re "python37 merge is not completely working" is useless without details.
