### ISSUE TITLE
The interface of packaged software is very old, not win10 style. How can I solve it?

### ISSUE THREAD

**Issue by paper2Fox** [pyinstaller/pyinstaller#3635]
Hi,The interface style of packaged software is very old when I code with pyqt5 is very beautiful
I mean, the style is  not win10 style. 
How can I solve it?
Thank U~

**Comment by NHades** [comment]
Have you tried setting style in your code? 
PyQt5.QtWidgets.QApplication('WindowsVista') 

for a list of supported styles, use:
aList = PyQt5.QtWidgets.QStyleFactory.keys()
print(aList)

**Comment by htgoebel** [comment]
1) This is not related to PyInstaller
2) Why are you not closing the ticket, as it obviously is solved? You are wasting my time, as I need to to the clean-up!
