### ISSUE TITLE
Failed to execute script pyi_rth_qt5

### ISSUE THREAD

**Issue by samjonson2019** [pyinstaller/pyinstaller#3637]
Hello

When i builld a exe i get this
82 INFO: checking Analysis
82 INFO: Building Analysis because out00-Analysis.toc is non existent
83 INFO: Initializing module dependency graph...
85 INFO: Initializing module graph hooks...
87 INFO: Analyzing base_library.zip ...
3549 INFO: running Analysis out00-Analysis.toc
3552 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\owner\appdata\local\programs\python\python36\python.exe
4349 INFO: Caching module hooks...
59285 INFO: Analyzing C:\Users\Owner\Desktop\backup\start.py
59387 INFO: Processing pre-find module path hook   PyQt5.uic.port_v3
59409 INFO: Processing pre-find module path hook   PyQt5.uic.port_v2
59783 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
65486 INFO: Processing pre-safe import module hook   six.moves
66057 INFO: Processing pre-find module path hook   distutils
68057 INFO: Loading module hooks...
68057 INFO: Loading module hook "hook-certifi.py"...
68059 INFO: Loading module hook "hook-distutils.py"...
68060 INFO: Loading module hook "hook-encodings.py"...
68160 INFO: Loading module hook "hook-httplib2.py"...
68162 INFO: Loading module hook "hook-lib2to3.py"...
68169 INFO: Loading module hook "hook-pkg_resources.py"...
68486 INFO: Processing pre-safe import module hook   win32com
68834 INFO: Loading module hook "hook-pydoc.py"...
68835 INFO: Loading module hook "hook-PyQt5.py"...
68838 INFO: Loading module hook "hook-PyQt5.Qt.py"...
68839 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
68934 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
69461 INFO: Loading module hook "hook-PyQt5.QtPrintSupport.py"...
69551 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
69552 INFO: Loading module hook "hook-PyQt5.uic.py"...
69557 INFO: Loading module hook "hook-pythoncom.py"...
69840 INFO: Loading module hook "hook-pywintypes.py"...
70138 INFO: Loading module hook "hook-requests.py"...
70140 INFO: Loading module hook "hook-sysconfig.py"...
70141 INFO: Loading module hook "hook-win32com.py"...
70773 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
70774 INFO: Loading module hook "hook-xml.py"...
70962 INFO: Looking for ctypes DLLs
71110 INFO: Analyzing run-time hooks ...
71120 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
71124 INFO: Including run-time hook 'pyi_rth_pkgres.py'
71126 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
71128 INFO: Including run-time hook 'pyi_rth_qt5.py'
71152 INFO: Looking for dynamic libraries
72508 INFO: Looking for eggs
72508 INFO: Using Python library c:\users\owner\appdata\local\programs\python\python36\python36.dll
72509 INFO: Found binding redirects:
[]
72527 INFO: Warnings written to C:\Users\Owner\Desktop\backup\build\start\warnstart.txt
72825 INFO: Graph cross-reference written to C:\Users\Owner\Desktop\backup\build\start\xref-start.html
72943 INFO: checking PYZ
72944 INFO: Building PYZ because out00-PYZ.toc is non existent
72945 INFO: Building PYZ (ZlibArchive) C:\Users\Owner\Desktop\backup\build\start\out00-PYZ.pyz
74648 INFO: Building PYZ (ZlibArchive) C:\Users\Owner\Desktop\backup\build\start\out00-PYZ.pyz completed successfully.
74722 INFO: checking PKG
74722 INFO: Building PKG because out00-PKG.toc is non existent
74723 INFO: Building PKG (CArchive) out00-PKG.pkg
74752 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
74759 INFO: Bootloader c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
74760 INFO: checking EXE
74760 INFO: Building EXE because out00-EXE.toc is non existent
74761 INFO: Building EXE from out00-EXE.toc
74762 INFO: Appending archive to EXE C:\Users\Owner\Desktop\backup\build\start\start.exe
74893 INFO: Building EXE from out00-EXE.toc completed successfully.
74905 INFO: checking COLLECT
74905 INFO: Building COLLECT because out00-COLLECT.toc is non existent
74905 INFO: Building COLLECT out00-COLLECT.toc
77047 INFO: Building COLLECT out00-COLLECT.toc completed successfully.

as you can see there is no warning but when i run the exe i get this: 

Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5.py", line 61, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 656, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 626, in _load_backward_compatible
  File "c:\users\owner\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 714, in load_module
    module = loader.load_module(fullname)
ValueError: PyCapsule_GetPointer called with incorrect name
[18624] Failed to execute script pyi_rth_qt5
_______________________________________________________________________________________________________________
Q1: Does the error occur when bundling the application or when running it?
as you can see buillding the program has zero warring but when i run the prorgram i get the problem
_______________________________________________________________________________________________________________
Q2: Software versions you are using ?
1. Python3.6
2.PyInstaller 3.3.1
3.PyQt5  5.11.2
_______________________________________________________________________________________________________________

Q3:What platform and which version you are working on (Windows, Linux, OS X)?
Windows, and i am using Arabic Language 

_______________________________________________________________________________________________________________
Q4:A minimal example program which shows the error. Ideally this is a one-liner ?
Pyinstaller Worked great with me before installing pyqt5

_______________________________________________________________________________________________________________

Q5:Did you try implementing a hook or run-time-hook (rthook) to solve the problem? If so, please include the hook file.
No, i didn't

_______________________________________________________________________________________________________________

Q6:Please include any other information which you think may by helpful for fixing, while reducing as much a possible. Please add logfiles as attachments. Please make sure to attach the log output generated by PyInstaller:

as i said before, first time i tried pyinstaller it was without using pyqt5 and i was working great, but after installing pyqt5 i start getting a lot of errors , and i for everyone of them i found solutions online but this one i couldn't find anything

_______________________________________________________________________________________________________________

**Comment by htgoebel** [comment]
Please provide the information as requested in the issue template. Otherwise I'm not going to spend any time on this.

**Comment by samjonson2019** [comment]
Hi @htgoebel, thanks for the reply, i did everything in the wiki, i don't understand what do you mean by need more info

**Comment by The-Compiler** [comment]
> ValueError: PyCapsule_GetPointer called with incorrect name

I've seen this happen in PyQt if there's a `PyQt5.sip` around (which is the case for PyQt 5.11), but there's still a stray `sip` module lying around (e.g. from an older build with an earlier PyQt version).

**Comment by samjonson2019** [comment]
@The-Compiler  Thanks a lot man, i moved sip.pyd and to the folder of the exe and it is working now

**Comment by bjones1** [comment]
@The-Compiler, thanks! That's very helpful; I'd hadn't seen this before.

**Comment by cpeusteuche** [comment]
@samjonson2019 I encounter the same error but your trick does not work. Did you moved the `sip.pyd` from the 
`C:\Users\XXX\AppData\Roaming\Python\Python36\site-packages\PyQt5`
to
` C:\Users\XXX\AppData\Roaming\Python\Python36\Scripts`

Thanks
