### ISSUE TITLE
PyInstaller pylint, run failed

### ISSUE THREAD

**Issue by chwma** [pyinstaller/pyinstaller#3647]
**1, pylint.__main__.py work good**

pylint$ python -m pylint.__main__.py pylint/config.py -E
No config file found, using default configuration
************* Module pylint.config
E:294,37: Instance of 'Option' has no 'hide' member (no-member)
E:299,15: Instance of 'Option' has no 'choices' member (no-member)
E:302,32: Instance of 'Option' has no 'choices' member (no-member)
E:305,31: Instance of 'Option' has no 'choices' member (no-member)
E:306,13: Instance of 'Option' has no 'choices' member (no-member)

**2, pyinstaller success**
pylint$ pyinstaller --clean -F pylint/__main__.py 
22 INFO: PyInstaller: 3.3.1
23 INFO: Python: 2.7.6
23 INFO: Platform: Linux-4.4.0-31-generic-x86_64-with-Ubuntu-14.04-trusty
23 INFO: wrote devel/pylint/__main__.spec
28 INFO: UPX is not available.
28 INFO: Removing temporary files and cleaning cache in ~/.cache/pyinstaller
29 INFO: Extending PYTHONPATH with paths
['~/asr/common/devel/pylint',
 '~/asr/common/devel/pylint']
30 INFO: checking Analysis
30 INFO: Building Analysis because out00-Analysis.toc is non existent
30 INFO: Initializing module dependency graph...
32 INFO: Initializing module graph hooks...
108 INFO: running Analysis out00-Analysis.toc
129 INFO: Caching module hooks...
134 INFO: Analyzing ~/asr/common/devel/pylint/pylint/__main__.py
1200 INFO: Processing pre-find module path hook   distutils
1327 INFO: Processing pre-safe import module hook   _xmlplus
3108 INFO: Processing pre-find module path hook   site
3108 INFO: site: retargeting to fake-dir '/usr/local/lib/python2.7/dist-packages/PyInstaller/fake-modules'
3881 INFO: Processing pre-safe import module hook   six.moves
4278 INFO: Loading module hooks...
4278 INFO: Loading module hook "hook-distutils.py"...
4278 INFO: Loading module hook "hook-sysconfig.py"...
4279 INFO: Loading module hook "hook-xml.py"...
4326 INFO: Loading module hook "hook-httplib.py"...
4326 INFO: Loading module hook "hook-encodings.py"...
4669 INFO: Loading module hook "hook-pkg_resources.py"...
4899 INFO: Processing pre-safe import module hook   win32com
5087 INFO: Loading module hook "hook-astroid.py"...
5132 WARNING: Hidden import "astroid.utils" not found!
5133 WARNING: Hidden import "astroid.inspector" not found!
5134 INFO: Loading module hook "hook-pylint.py"...
6017 INFO: Loading module hook "hook-setuptools.py"...
6120 INFO: Looking for ctypes DLLs
6229 INFO: Analyzing run-time hooks ...
6234 INFO: Including run-time hook 'pyi_rth_pkgres.py'
6235 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
6243 INFO: Looking for dynamic libraries
6471 INFO: Looking for eggs
6471 INFO: Python library not in binary dependencies. Doing additional searching...
6486 INFO: Using Python library /usr/lib/x86_64-linux-gnu/libpython2.7.so.1.0
6490 INFO: Warnings written to ~/asr/common/devel/pylint/build/__main__/warn__main__.txt
6520 INFO: Graph cross-reference written to ~/asr/common/devel/pylint/build/__main__/xref-__main__.html
6592 INFO: checking PYZ
6592 INFO: Building PYZ because out00-PYZ.toc is non existent
6592 INFO: Building PYZ (ZlibArchive) ~/asr/common/devel/pylint/build/__main__/out00-PYZ.pyz
7039 INFO: Building PYZ (ZlibArchive) ~/asr/common/devel/pylint/build/__main__/out00-PYZ.pyz completed successfully.
7096 INFO: checking PKG
7096 INFO: Building PKG because out00-PKG.toc is non existent
7096 INFO: Building PKG (CArchive) out00-PKG.pkg
9335 INFO: Building PKG (CArchive) out00-PKG.pkg completed successfully.
9349 INFO: Bootloader /usr/local/lib/python2.7/dist-packages/PyInstaller/bootloader/Linux-64bit/run
9349 INFO: checking EXE
9349 INFO: Building EXE because out00-EXE.toc is non existent
9349 INFO: Building EXE from out00-EXE.toc
9349 INFO: Appending archive to ELF section in EXE ~/asr/common/devel/pylint/dist/__main__
9372 INFO: Building EXE from out00-EXE.toc completed successfully.

**3,  run failed, and pyinstall dir is same error, why ?**
pylint$ ./dist/__main__ pylint/config.py
Traceback (most recent call last):
  File "pylint/__main__.py", line 15, in <module>
    import pylint
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "pylint/__init__.py", line 11, in <module>
    from .__pkginfo__ import version as __version__
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "pylint/__pkginfo__.py", line 26, in <module>
    from setuptools import __version__ as setuptools_version
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "setuptools/__init__.py", line 14, in <module>
    
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
    exec(bytecode, module.__dict__)
  File "setuptools/dist.py", line 21, in <module>
  File "setuptools/extern/__init__.py", line 61, in load_module
    
ImportError: The 'packaging' package is required; normally this is bundled with this package so if you get this warning, consult the packager of your distribution.
[147129] Failed to execute script __main__

**Comment by htgoebel** [comment]
Which version of setuptools are you using?

**Comment by htgoebel** [comment]
I forgot: Use the current development version of PyInstaller.

**Comment by lucabecchetti** [comment]
Pyinstaller 4.0 same error, pylint do not run inside .exe, any ideas?

**Comment by htgoebel** [comment]
This issue is closed already. If you experience an related issue, please search for an *open* issue that matches your problem. If you can't find eone, please open a *new issue* - and be sure to include as much debug info as you have in your report.
