### ISSUE TITLE
Program closes after starting

### ISSUE THREAD

**Issue by AndreWicked** [pyinstaller/pyinstaller#3649]
Good afternoon, there is a problem. I use opencv and pyqt5 in my application, I display the capture window from opencv to pyqt, in idle it works fine, after compilation it also starts and works, but after connecting to the camera, the image is displayed for a few seconds, and then the program just closes, what should I do?

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.
