### ISSUE TITLE
Making Pyinstaller unrecoverable

### ISSUE THREAD

**Issue by masoudr** [pyinstaller/pyinstaller#3651]
Hi,
As you might know, executables that have been frozen by PyInstaller can be easily reversed as already mentioned [here](https://reverseengineering.stackexchange.com/questions/160/how-do-you-reverse-engineer-an-exe-compiled-with-pyinstaller). I think it is because of the freezing method which uses simple compile methods like `.pyz` and `.pyc`. So is there any method to prevent this or make it harder to reverse?
Thanks.

**Comment by melvyn2** [comment]
There are options to encrypt the bytecode, but I am not sure if this is too effective.

**Comment by masoudr** [comment]
@melvyn2 If you mean using `exec` and `base64decode`, it can be easily recovered.

**Comment by melvyn2** [comment]
https://pyinstaller.readthedocs.io/en/stable/man/pyinstaller.html?highlight=encrypt#what-to-bundle-where-to-search

**Comment by masoudr** [comment]
@melvyn2 Thanks I didn't know that. Actually, I was thinking about using `Cython` to create a library first then bundle it to my code.  Do you know what is the encryption type is?

**Comment by melvyn2** [comment]
It seems to be some sort of AES CBC block cipher.

**Comment by masoudr** [comment]
OK, I have another question, I tried to create project modules with `Cython` (as `.pyd` files`) then I import it and freezed the code with encryption flag. Then when I extract the executable I see two files for my imported module (`my_module`) `my_module.pyc.encrypted` and `my_module.my_module.pyd`  So what is the difference between the two? I think this method only encrypt python code files not Cython libraries.

**Comment by htgoebel** [comment]
@masoudr This is an issue tracker, not a support forum. Please use the mailinglist.
