### ISSUE TITLE
ERROR:service_manager_context.cc(252)] Attempting to run unsupported native service: /Users/melvyn/PySteamAuth/dist/PySteamAuth/content_renderer.service

### ISSUE THREAD

**Issue by melvyn2** [pyinstaller/pyinstaller#3652]
- [x]  try the latest development version, using the following command:
```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
- [x] follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

- [x] make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

---

Python 3.6.6
PyInstaller 3.4.dev0+7817d3fac
Build log: https://gist.github.com/melvyn2/ba69bfc6b945d6df268544a26935552d
Run log: https://gist.github.com/melvyn2/816322140c175c733d5b15b4a86a4bf4

---

This issue does not happen when running from the original script, only when running the frozen version. This issue can be reproduced with this minimal example: 
```
import os
os.environ['QTWEBENGINEPROCESS_PATH'] = os.path.abspath(os.path.curdir)
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QUrl
app = QApplication( [] )
view = QWebEngineView()
view.load( QUrl( "http://www.pyinstaller.org" ) )
view.show()
app.exec_()
```
This does **not** crash the program, only show blank (gray) space where the `QWebEngineView` should be. The `/BuildRoot/Library/Caches/com.apple.xbs/Sources/AppleGVA/AppleGVA-11.3.7/Sources/Slices/Driver/AVD_loader.cpp: failed to get a service for display #` messages also happen when running from script and do not affect anything.

**Comment by bjones1** [comment]
QtWebEngine on Mac doesn't (yet) work with PyInstaller -- help is needed! See #3506.

**Comment by melvyn2** [comment]
Does the other issue have the same error message? This isn't about QWebEngineProcess or the ICU data: I already fixed that. Plus, qutebrowser seems to be working fine with it.

**Comment by melvyn2** [comment]
Also, calling `reload()` on the `QWebEngineView`  makes if briefly flash white.

**Comment by bjones1** [comment]
Hmm, I can't offer any more help. I don't have a Mac to develop on. If you can determine how qutebrowser packages itself, please share by submitting a PR to fix PyInstaller!

**Comment by melvyn2** [comment]
Yep, that is what I am working on.

**Comment by bjones1** [comment]
If you can spot any fixes for this regression, please let me know! Or provide a test case. Or both.

**Comment by melvyn2** [comment]
Here is a video of the regression in action: https://drive.google.com/file/d/1NBut6ItoKfgjxjRQILlUqsIaqAsvfvvx

**Comment by bjones1** [comment]
What code are you referring to? A file/line number would help.

**Comment by melvyn2** [comment]
I removed that line from my own code: it was in the minimal example too. However, I am not sure when the regression happened, but I am looking into it.

**Comment by melvyn2** [comment]
The regression is in commit 97b39e425fd4a9548484028657503466affe95b5.
The commit right before it (ba9d1b50bd4fa2c1ad9b3adb42006cae8bb4375f) works, as in the QtWebEngineView works, but any after it don't.

**Comment by bjones1** [comment]
Thanks! Good progress. Can you find the line(s) that cause the issue in this commit?

**Comment by melvyn2** [comment]
Ok, I will try!

**Comment by melvyn2** [comment]
The regression is in PyInstaller/loader/rthooks/pyi_rth_qt5webengine.py.Tthe QtWebEngineProcess located in the new location (Bundle.app/Contents/Resources/PyQt5/Qt/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app) can not find its required files. When I replaced the PyQt5 folder with the entire PyQt5 library folder, the QtWebEngineView worked. Instead of moving it back, I suggest copying the required files in.

**Comment by melvyn2** [comment]
The required folders, with ALL of their files in them, are:
PyQt5/Qt/translations
PyQt5/Qt/lib/QtCore.framework
PyQt5/Qt/lib/QtGui.framework
PyQt5/Qt/lib/QtNetwork.framework
PyQt5/Qt/lib/QtPositioning.framework
PyQt5/Qt/lib/QtQml.framework
PyQt5/Qt/lib/QtQuick.framework
PyQt5/Qt/lib/QtWebChannel.framework
PyQt5/Qt/lib/QtWebEngineCore.framework
