### ISSUE TITLE
Use Cython generated libraries

### ISSUE THREAD

**Issue by masoudr** [pyinstaller/pyinstaller#3654]
I'm trying to create a `pyd` library for my python library and then use it in my project. After that create an executable from the whole project using `Pyinstaller`.
Here is a simple example:

    project_folder\
    -----main.py
    ------\my_module
    ----------------\__init__.py
    ----------------\my_module.py
    ----------------\setup.py
    ----------------\depend
    -----------------------\__init__.py
    -----------------------\depend.py

**main.py**

    from my_module import my_module
    
    if __name__ == '__main__':
        print(my_module.time_())

**my_module.py**

    from .depend import depend
    
    def time_():
        return depend.current_time()
    
    if __name__ == "__main__":
        print(time_())
**depend.py**

    import datetime
    
    
    def current_time():
        return datetime.datetime.now()
**setup.py**

    from distutils.core import setup
    from distutils.extension import Extension
    from Cython.Distutils import build_ext
    
    ext_modules = [
        Extension("my_module",  ["my_module.py"]),
        Extension("depend.depend",  ["./depend/depend.py"]),
    ]
    
    setup(
        name = 'My Program',
        cmdclass = {'build_ext': build_ext},
        ext_modules = ext_modules
    )
Then in `my_module` folder I used `python setup.py build_ext --inplace` to generate lib files and `pyd` files for both `my_module` and `depend` created successfully.
Then I created the library directory `new_module` in `project_folder`:

    project_folder\
    ------new_main.py
    ------new_module\
    -----------------my_module.cp36-win32.pyd
    -----------------depend\
    ------------------------\depend.cp36-win32.pyd

**new_main.py**

    from new_module import my_module
    
    if __name__ == '__main__':
        print(my_module.time_())
And works fine without any problem.
Then I used `pyinstaller ./new_main.py` to generate the executable but when I run it I see this:

> Traceback (most recent call last):   File "main.py", line 1, in
> <module>   File "...\pyimod03_importers.py", line 714, in load_module
>     module = loader.load_module(fullname)   File "my_module.py", line 1, in init my_module ModuleNotFoundError: No module named
> 'new_module.depend' [14616] Failed to execute script main

I'm not sure my problem is related to `Pyinstaller` or `Cython`. I don't want to change the library structure. I used `hiddenimports` to add `pyd` files manually with the same error.

**Comment by htgoebel** [comment]
Please read the manual https://pyinstaller.readthedocs.io/en/v3.3.1/feature-notes.html#cython-support

**Comment by masoudr** [comment]
I tried to use `hidden-import` but it gave the same error. `hidden-import` only works for one separate module, not for nested modules. I think the only option here is to use `Tree` to bring the whole library directory.

**Comment by htgoebel** [comment]
Oh, sorry, I did not read your message detailed enough. Looks more like you missed copying the `depend/__init__.py` file.

**Comment by masoudr** [comment]
@htgoebel Thanks. Also I should add modules with `hidden-import` as relative imports like `new_module.depend.depend`.
