### ISSUE TITLE
Multiple executables in different directories

### ISSUE THREAD

**Issue by Siecje** [pyinstaller/pyinstaller#3663]
I am trying to build multiple executables. I have a `main.py` and a `main2.py` with this spec file[0].

After running PyInstaller I get `dist\main\main.exe` and `dist\main2\main2.exe`.

Is it possible for PyInstaller to put all of the executables in the same directory?

0: https://github.com/Siecje/qml-testing/blob/8c3449b5a41c1d700ab2562afe7a5e5c54db2f8d/main.spec

**Comment by Siecje** [comment]
If I set the `COLLECT` `name='main'` to be the same it will output to the same directory but the second time it wants to delete the directory not merge them.

```
108525 INFO: checking COLLECT
WARNING: The output directory "C:\path\dist\main" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)n
User aborted
```
If I don't abort only the second executable will be in that directory.


```
coll_main = COLLECT(exe_main,
                    a_main.binaries,
                    a_main.zipfiles,
                    a_main.datas,
                    strip=False,
                    upx=True,
                    name='main')

coll_main2 = COLLECT(exe_main2,
                     a_main2.binaries,
                     a_main2.zipfiles,
                     a_main2.datas,
                     strip=False,
                     upx=True,
                     name='main')
```

**Comment by htgoebel** [comment]
You are using MEREGE, which is broken and seeking somebody to fix it. Search the open issues if you want to help.

Beside this, PyInstaller is able to put several executables into one directory. Of course you have to use a single COLLECT.

**Comment by Siecje** [comment]
How do you use a single collect?

**Comment by Siecje** [comment]
Thanks to @altendky for pointing out that you can just give everything to one `COLLECT` as `*args`[0].

Where is `COLLECT` documented?

```
coll_main = COLLECT(exe_main,
                                  a_main.binaries,
                                  a_main.zipfiles,
                                  a_main.datas,
                                  exe_main2,
                                  a_main2.binaries,
                                  a_main2.zipfiles,
                                  a_main2.datas,
                                  strip=False,
                                  upx=True,
                                  name='main')
```

0: https://github.com/pyinstaller/pyinstaller/blob/5c2fe6ca5521627a41ea4a78fb67062f41db4f21/PyInstaller/building/api.py#L648

**Comment by htgoebel** [comment]
`COLLECT` is not documented. Maybe you want to help on #1371 .
