### ISSUE TITLE
ImportError: No module named 'gevent.__hub_local'

### ISSUE THREAD

**Issue by ishandutta2007** [pyinstaller/pyinstaller#3664]
`pip freeze
`
> altgraph==0.16.1
> dis3==0.1.2
> future==0.16.0
> gevent==1.3.5
> greenlet==0.4.14
> macholib==1.10
> msgpack-python==0.5.6
> pefile==2017.11.5
> PyInstaller==3.4.dev0+g7817d3fa
> pyzmq==17.1.0
> zerorpc==0.6.1
> 

```
sudo pyinstaller pycalc3/api.py --distpath pycalcdist3 --hidden-import=pkg_resources
```

> ........
> ........
> ........
> 24133 WARNING: failed to copy flags of /System/Library/Frameworks/Tk.framework/Versions/8.5/Resources/Scripts/ttk/defaults.tcl
> 24135 WARNING: failed to copy flags of /System/Library/Frameworks/Tk.framework/Versions/8.5/Resources/Scripts/ttk/notebook.tcl
> 24135 INFO: Building COLLECT COLLECT-00.toc completed successfully.
> 

```
sudo open pycalcdist3/api/api
```
> Last login: Tue Jul 31 23:53:00 on ttys002
> You have new mail.
> /Users/ishandutta2007/Documents/Projects/electron-python-example/pycalcdist3/api/api ; exit;
> ishandutta2007@MacBook-Pro:~$ /Users/ishandutta2007/Documents/Projects/electron-python-example/pycalcdist3/api/api ; exit;
> Traceback (most recent call last):
>   File "pycalc3/api.py", line 4, in <module>
>   File "/Users/ishandutta2007/Documents/Projects/electron-python-example/env3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
>     exec(bytecode, module.__dict__)
>   File "env3/lib/python3.5/site-packages/zerorpc/__init__.py", line 29, in <module>
>   File "/Users/ishandutta2007/Documents/Projects/electron-python-example/env3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
>     exec(bytecode, module.__dict__)
>   File "env3/lib/python3.5/site-packages/zerorpc/context.py", line 32, in <module>
>   File "/Users/ishandutta2007/Documents/Projects/electron-python-example/env3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
>     exec(bytecode, module.__dict__)
>   File "env3/lib/python3.5/site-packages/zerorpc/gevent_zmq.py", line 36, in <module>
>   File "/Users/ishandutta2007/Documents/Projects/electron-python-example/env3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
>     exec(bytecode, module.__dict__)
>   File "env3/lib/python3.5/site-packages/gevent/__init__.py", line 87, in <module>
>   File "/Users/ishandutta2007/Documents/Projects/electron-python-example/env3/lib/python3.5/site-packages/PyInstaller/loader/pyimod03_importers.py", line 631, in exec_module
>     exec(bytecode, module.__dict__)
>   File "env3/lib/python3.5/site-packages/gevent/_hub_local.py", line 101, in <module>
>   File "env3/lib/python3.5/site-packages/gevent/_util.py", line 105, in import_c_accel
>   File "env3/lib/python3.5/importlib/__init__.py", line 126, in import_module
> ImportError: No module named 'gevent.__hub_local'
> [26467] Failed to execute script api
> logout
> Saving session...
> ...copying shared history...
> ...saving history...truncating history files...
> ...completed.
> 
> [Process completed]
> 
>

**Comment by ChuhC** [comment]
Try to add missing modules  with "--hidden-import"  parameter may help you  @ishandutta2007

**Comment by Andrew-Shay** [comment]
I too am facing this issue. Adding the following did not change anything. I tried separately and together.  
`--hidden-import gevent --hidden-import gevent.__hub_local`

gevent       1.3.6
PyInstaller  3.3.1
Python       3.6. 4

**Comment by bjones1** [comment]
My branch should work -- https://github.com/bjones1/pyinstaller/tree/nspkg_fix.

**Comment by LefterisJP** [comment]
I am also facing this issue. Pyinstaller used to work fine for previous versions of gevent 2 months ago so I can only assume it's something on the gevent side. Anyone has any idea how to fix this?

@bjones1 your link to your branch gives a 404

**Comment by LefterisJP** [comment]
Adding a hook like below with the filename `hook-gevent.py` to populate the hidden_imports solves the problem for me.

```
from pathlib import Path

import gevent


# This is temporarily needed until https://github.com/pyinstaller/pyinstaller/pull/3534 is fixed
def _get_gevent_imports():
    package_path = Path(gevent.__file__).parent

    imports = []
    imports.extend(
        'gevent.{}'.format(
            str(module.relative_to(package_path)).replace('.py', '').replace('/', '.'),
        )
        for module in package_path.glob('**/*.py')
    )
    imports.extend(
        'gevent.{}'.format(
            str(module.relative_to(package_path)).partition('.')[0].replace('/', '.'),
        )
        for module in package_path.glob('**/*.so')
    )

    return imports


hiddenimports = _get_gevent_imports()
```

**Comment by bjones1** [comment]
I've merged my branch into develop and deleted it. Just install the latest from develop -- it should work.
