### ISSUE TITLE
Inconsistent use of system versus conda libraries

### ISSUE THREAD

**Issue by djhoese** [pyinstaller/pyinstaller#3667]
I have a PyQt4 based application (soon to move to PyQt5 after the next release) that I build from a conda python 3.6 environment on a CentOS 7 machine. I've encountered a weird situation where pyinstaller will sometimes use the system libraries instead of the libraries in the conda environment. I'm using current develop.

1. test.py

```python
from PyQt4 import QtGui, QtCore
```

2. Run pyinstaller

```bash
rm -r test test.spec; pyinstaller -y --clean test.py; diff test/dist/test/libQtCore.so.4 /data/users/davidh/anaconda3/envs/sift/lib/libQtCore.so
```

If you run the above repeatedly you get inconsistent results. I expect the files to not differ (the Qt put in to the distribution is the same as the one in the conda environment), but it seems to change every couple executions. The other Qt it uses is from `/usr/lib64/`. This may also be related to #3659 where my libz from conda may not be compatible with the pyinstaller bootloader.

@htgoebel Any idea when pyinstaller would decide to use the system libraries over ones in the current python environment?

NOTE: You have to install pyqt by doing `conda install -c conda-forge "pyqt<5"` since PyQt5 is the default for conda/conda-forge now.

**Comment by djhoese** [comment]
Small update, whenever I get it to use the conda qt libraries I get this warning:

```
3015 INFO: Analyzing /data/users/davidh/repos/git/pyinstaller/test.py
3069 INFO: Loading module hooks...
3069 INFO: Loading module hook "hook-PyQt4.py"...
3070 INFO: Loading module hook "hook-xml.py"...
3301 INFO: Loading module hook "hook-PyQt4.QtGui.py"...
3547 INFO: Loading module hook "hook-PyQt4.QtCore.py"...
3585 INFO: Loading module hook "hook-encodings.py"...
3644 INFO: Loading module hook "hook-pydoc.py"...
3671 INFO: Looking for ctypes DLLs
3671 INFO: Analyzing run-time hooks ...
3675 INFO: Including run-time hook 'pyi_rth_qt4plugins.py'
3684 INFO: Looking for dynamic libraries
ldd: warning: you do not have execution permission for `/data/users/davidh/anaconda3/envs/sift/plugins/inputmethods/../../lib/libgcc_s.so.1'
```

If I don't see that warning then it uses the system library which is surprising.

**Comment by djhoese** [comment]
I looked in to this and found out that the main issue is that the PyQt4 (or maybe just Qt4) provided by conda is returning the library paths for the system Qt's plugins. Something like `/usr/lib64/plugins` and those link against the system Qt libraries needed by KDE on this system. My hack right now is to modify the qt utils in pyinstaller to not include any library paths that include `/usr/` and that is working so far.

The hook in pyinstaller essentially uses the pyinstaller qt utils to ask a QApplication what paths are associated with it and uses those to find the `.so` binaries that should be included. If the plugins in the system libraries are processed first then the system Qt is bundled instead of the one provided by my conda environment.

I'm not sure if this is a Qt build issue or a pyinstaller needing to be more careful about what it uses from PyQt.

**Comment by bjones1** [comment]
For some reason, Conda's PyQt installs are messed up. I have the same problem in PyQt5. IMHO, if the PyQt install can't correct report information about itself, it's just plain broken. I wish someone would file a bug report / fix to get this fixed on the Conda side.

**Comment by bjones1** [comment]
Since I don't use Conda, would you mind filing it with my assistance? I can provide test code that returns incorrect values for QLibraryInfo on PyQt5 on Conda (based on reports from other PyInstaller users), but don't have a patch/suggested fix for it.

**Comment by djhoese** [comment]
@bjones1 I'm confused. You say you have the same issue with your environment which I assumed was conda, but you don't use conda?

To file a bug you don't need to have a suggested fix or anything. Just let them know. I can make the bug report, but would have to create a new conda environment. Since it sounded like you already have one I was hoping you would do it. Just copying and pasting the QLibraryInfo usage/results should be enough of a start.

**Comment by djhoese** [comment]
@bjones1 Another thing is that pyinstaller has some pretty fancy handling of PyQt5 QLibraryInfo in `PyInstaller/utils/hooks/qt.py`. If you're still having issues with your application then you should definitely be the person to file a bug.

**Comment by bjones1** [comment]
I'm passing on bug reports / diagnoses of PyInstaller users with Conda that had trouble packaging PyQt5 because of Conda's incorrect values from QLibraryInfo. But I don't use it personally.

**Comment by bjones1** [comment]
@djhoese, would you mind running this on your Conda install to see what it reports?

``` Python
from pprint import pprint
from PyQt5.QtCore import QLibraryInfo
paths = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
location = {x: QLibraryInfo.location(getattr(QLibraryInfo, x))
            for x in paths}
pprint(location)
```

For me (Windows 10, Python 3.6.1 64 bit, PyQt 5.11.2 installed from pip:

```
{'ArchDataPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt',
 'BinariesPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/bin',
 'DataPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt',
 'DocumentationPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/doc',
 'ExamplesPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/examples',
 'HeadersPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/include',
 'ImportsPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/imports',
 'LibrariesPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/lib',
 'LibraryExecutablesPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/bin',
 'PluginsPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/plugins',
 'PrefixPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt',
 'Qml2ImportsPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/qml',
 'SettingsPath': '',
 'TestsPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/tests',
 'TranslationsPath': 'E:/Downloads/Python36-64/lib/site-packages/PyQt5/Qt/translations'}
```

... all of which is correct for my install. I'm guessing that this would also work on PyQt4, if you don't mind running it there as well. I think this would then be all we need for a bug report. I'd be happy to open it, but you're also welcome to.

**Comment by djhoese** [comment]
Output looks good to me:

```
$ ipython
Python 3.6.6 | packaged by conda-forge | (default, Jul 26 2018, 09:53:17) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.5.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: from pprint import pprint
   ...: from PyQt5.QtCore import QLibraryInfo
   ...: paths = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
   ...: location = {x: QLibraryInfo.location(getattr(QLibraryInfo, x))
   ...:             for x in paths}
   ...: pprint(location)
   ...:             
{'ArchDataPath': '/data/users/davidh/anaconda3/envs/pyqt5_only',
 'BinariesPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/bin',
 'DataPath': '/data/users/davidh/anaconda3/envs/pyqt5_only',
 'DocumentationPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/doc',
 'ExamplesPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/examples',
 'HeadersPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/include/qt',
 'ImportsPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/imports',
 'LibrariesPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/lib',
 'LibraryExecutablesPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/libexec',
 'PluginsPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/plugins',
 'PrefixPath': '/data/users/davidh/anaconda3/envs/pyqt5_only',
 'Qml2ImportsPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/qml',
 'SettingsPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/etc/xdg',
 'TestsPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/tests',
 'TranslationsPath': '/data/users/davidh/anaconda3/envs/pyqt5_only/translations'}
```

**Comment by djhoese** [comment]
This is what I get for PyQt4 from conda-forge (which isn't updated anymore):

```
In [2]: from pprint import pprint
   ...: from PyQt4.QtCore import QLibraryInfo
   ...: paths = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
   ...: location = {x: QLibraryInfo.location(getattr(QLibraryInfo, x))
   ...:             for x in paths}
   ...: pprint(location)
   ...:             
{'BinariesPath': '/home/carlos/miniconda/envs/_build/bin',
 'DataPath': '/home/carlos/miniconda/envs/_build',
 'DemosPath': '/home/carlos/miniconda/envs/_build/demos',
 'DocumentationPath': '/home/carlos/miniconda/envs/_build/doc',
 'ExamplesPath': '/home/carlos/miniconda/envs/_build/examples',
 'HeadersPath': '/home/carlos/miniconda/envs/_build/include/qt',
 'ImportsPath': '/home/carlos/miniconda/envs/_build/imports',
 'LibrariesPath': '/home/carlos/miniconda/envs/_build/lib',
 'PluginsPath': '/home/carlos/miniconda/envs/_build/plugins',
 'PrefixPath': '/home/carlos/miniconda/envs/_build',
 'SettingsPath': '/etc/xdg',
 'TranslationsPath': '/home/carlos/miniconda/envs/_build/translations'}
```

So that is obviously wrong since my username is not carlos, but if I understand the pyinstaller code well enough this isn't the method used for PyQt4 anyway. It uses:

```python
from PyQt4.QtCore import QCoreApplication;
app = QCoreApplication([]);
# For Python 2 print would give <PyQt4.QtCore.QStringList
# object at 0x....>", so we need to convert each element separately
str = getattr(__builtins__, 'unicode', str);  # for Python 2
print([str(p) for p in app.libraryPaths()])
```

```
In [1]: from PyQt4.QtCore import QCoreApplication;
   ...: app = QCoreApplication([]);
   ...: # For Python 2 print would give <PyQt4.QtCore.QStringList
   ...: # object at 0x....>", so we need to convert each element separately
   ...: str = getattr(__builtins__, 'unicode', str);  # for Python 2
   ...: print([str(p) for p in app.libraryPaths()])
   ...: 
   ...: 
['/data/users/davidh/anaconda3/envs/pyqt4_only/plugins', '/data/users/davidh/anaconda3/envs/pyqt4_only/bin', '/usr/lib64/kde4/plugins', '/usr/lib/kde4/plugins']
```

However, I just noticed when the above PyQt4 code is run again in the same python session you get:

```['/usr/lib64/kde4/plugins', '/usr/lib/kde4/plugins']```

**Comment by bjones1** [comment]
Thanks for looking. I know other PyInstaller users have reports problems in Windows with PyQt5. Perhaps this is fixed now? For now, I'll consider PyQt5 stuff working.

For your original bug report, would you like to submit a patch? Since it's old PyQt4 code, I'm not interested in fixing / maintaining it.

**Comment by djhoese** [comment]
I think pyinstaller is working as it should (I think) and that the conda-forge package for PyQt4 is incorrectly built (links to system plugins when it shouldn't). I think this issue can be closed and I'll just put my current hack to pyinstaller below. I'm not sure my fix would be useful to anyone else. I would assume that anyone else outside of a conda environment would want everything that their PyQt is linked to (system installed or custom). My fix is just the simple last line in the below code which lives in `PyInstaller/utils/hooks/qt.py`:

```python
def qt_plugins_dir(namespace):
    """
    Return list of paths searched for plugins.

    :param namespace: Import namespace, i.e., PyQt4, PyQt5, PySide, or PySide2

    :return: Plugin directory paths
    """
    if namespace not in ['PyQt4', 'PyQt5', 'PySide', 'PySide2']:
        raise Exception('Invalid namespace: {0}'.format(namespace))
    if namespace == 'PyQt5':
        paths = [pyqt5_library_info.location['PluginsPath']]
    else:
        paths = eval_statement("""
            from {0}.QtCore import QCoreApplication;
            app = QCoreApplication([]);
            # For Python 2 print would give <PyQt4.QtCore.QStringList
            # object at 0x....>", so we need to convert each element separately
            str = getattr(__builtins__, 'unicode', str);  # for Python 2
            print([str(p) for p in app.libraryPaths()])
            """.format(namespace))
        paths = [p for p in paths if not p.startswith('/usr')]
```
