### ISSUE TITLE
Exe with logging support?

### ISSUE THREAD

**Issue by szczuru** [pyinstaller/pyinstaller#3669]
Is there any way to build exe with output log support?
Eg when running it with "compiled_program.exe -log" parameter ?
I want to log everything from cli window to file.

**Comment by tallforasmurf** [comment]
The standard Python logging module allows for logging to a file. However your program must supply the path to the file. You could write your program to take a `--logfile=` parameter, or you could just choose a name in `C:\WINDOWS\TEMP`. You should study the "Basic Tutorial" and the "Advanced Tutorial" that are linked from the [logging documentation](https://docs.python.org/3.6/library/logging.html#module-logging).

To discuss this further please use the mailing list, this is not an "issue".
