### ISSUE TITLE
Lib not found: api-ms-win-crt-*

### ISSUE THREAD

**Issue by itsjax** [pyinstaller/pyinstaller#3670]
### What is the exact problem?

- When building an app pyinstaller prints the error Lib not Found: api-ms-win-crt-* (for a lot of libs) (issue already refered in [issue 1566](https://github.com/pyinstaller/pyinstaller/issues/1566) but none of the fixes worked. [Link to output without--log-level DEBUG](https://gist.github.com/itsjax/8705d64067f905360281de0a69bbc242) 

### Software versions you are using

- Windows 10 Version 1803

- Python 3.6.6

- PyInstaller 3.3.1

### What platform and which version you are working on (Windows, Linux, OS X)

- Windows 10 Version 1803

### A minimal example program which shows the error. Ideally this is a one-liner :-)

- [Code i was using](https://gist.github.com/itsjax/0081312ff6ef395d42611aa706d478fe)

### Did you try implementing a hook or run-time-hook (rthook) to solve the problem? If so, please include the hook file.

- No.

### Please include any other information which you think may by helpful for fixing, while reducing as much a possible. Please add logfiles as attachments. Please make sure to attach the log output generated by PyInstaller.

- Attached log without --log-level DEBUG > out.txt [out.txt](https://github.com/pyinstaller/pyinstaller/files/2260680/out.txt)

**Comment by pavi2410** [comment]
Using Visual Studio 2015 build worker image in AppVeyor has solved this problem for me.

**Comment by tjt263** [comment]
@danielalexis 
Did you find a solution?

**Comment by danielalexis** [comment]
on my computer, nope. I had to use a virtual machine
