### ISSUE TITLE
Using the PyInstaller bundled python for subprocess calls

### ISSUE THREAD

**Issue by burglarhobbit** [pyinstaller/pyinstaller#3673]
I wanted to use the subprocess to call another python script separately since the another script is outputting a from a DLL into stdout separate from the stdout of the calling script. So only a parent script where we capture the outputs into the subprocess call could help. But the problem is I would like to run the script as subprocess using the Python distribution bundled into the exe itself. How can I do that without using the system python?

Here is a simplified example:
-> script1.py uses DLL. DLL outputs in stdout separate from script1.py stdout. Therefor cannot catch the output in program script1.py. 
-> script2.py uses subprocess Popen to call script1.py and is able to catch all the outputs associated with the script1.py and its respective DLL.
-> Bundled one-file exe is created which will call script2.py using the bundled Python distribution. 
-> Using the same bundled python distribution, I want the subprocess to call script1.py. 

I'm using Windows 7 and Python 3.6.2 amd64.

**Comment by tallforasmurf** [comment]
There is a [PyInstaller email list](http://www.pyinstaller.org/support.html) and a lot of smart people are on it and could help with hypothetical questions like this. This is an issue tracker and it doesn't look like you have an issue yet.

**Comment by burglarhobbit** [comment]
@tallforasmurf Seems like a lot of smart people are either busy or just non-existent on the email list. Just a quick glance on the email list shows an almost dead group. Same for the issue tracker. But you're quick to respond and reject this at first glance. The irony.

Hopefully for future users, I have solved this by creating a separate exe for script1.py and calling it in script2.py which was again bundled in a parent exe. Hence, a nested exe solution solved what I wanted to accomplish.
