### ISSUE TITLE
pyinstaller OSError: [Errno 22] Invalid argument: 'E:\\Project\\DCexe\\*.spec'

### ISSUE THREAD

**Issue by fuhongyun55** [pyinstaller/pyinstaller#3679]
What's the reason?
TXT is my code
The error message is as follows:

DCexe) E:\Project\DCexe>pyinstaller -F -w *.py
75 INFO: PyInstaller: 3.0
76 INFO: Python: 3.6.5
76 INFO: Platform: Windows-10-10.0.17134-SP0
Traceback (most recent call last):
  File "C:\Users\Administrator\venv\DCexe\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.0', 'console_scripts', 'pyinstaller')()
  File "C:\Users\Administrator\venv\DCexe\lib\site-packages\PyInstaller\__main__.py", line 97, in run
    spec_file = run_makespec(opts, args)
  File "C:\Users\Administrator\venv\DCexe\lib\site-packages\PyInstaller\__main__.py", line 41, in run_makespec
    spec_file = PyInstaller.building.makespec.main(args, **opts.__dict__)
  File "C:\Users\Administrator\venv\DCexe\lib\site-packages\PyInstaller\building\makespec.py", line 334, in main
    specfile = open(specfnm, 'w')
OSError: [Errno 22] Invalid argument: 'E:\\Project\\DCexe\\*.spec'

[main.txt](https://github.com/pyinstaller/pyinstaller/files/2273106/main.txt)
[lei.txt](https://github.com/pyinstaller/pyinstaller/files/2273107/lei.txt)
[s_lei.txt](https://github.com/pyinstaller/pyinstaller/files/2273108/s_lei.txt)

**Comment by BoboTiG** [comment]
Are you giving a file named only `.py` to pyinstaller? If so, it will look for the `.spec` file, which is not found. You should use a complete filename like `example.py`: `pyinstaller -F -w example.py`

Could you format the code and give a simple and little example so we can try from our side?

**Comment by fuhongyun55** [comment]
It's three files. I also tried to specify the filename, which doesn't work

At 2018-08-09 17:38:08, "Mickaël Schoentgen" <notifications@github.com> wrote:


Are you giving a file named only .py to pyinstaller? If so, it will look for the .spec file, which is not found. You should use a complete filename like example.py: pyinstaller -F -w example.py

Could you format the code and give a simple and little example so we can try from our side?

**Comment by bwoodsend** [comment]
You should be giving your main script to PyInstaller. `main.py` imports `lei.py` and `s_lei.py` so those will be included automatically. Your command should be:
```shell
PyInstaller main.py
```
Which builds fine for me.

**Comment by bwoodsend** [comment]
I'm closing this as I'm almost certain this is just misuse as opposed to a bug. Comment below if otherwise.
