### ISSUE TITLE
Support for encrytion dongles

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#368]
**Original date**: 2011/06/29
**Original reporter**: *mike DOT waldeyer AND videlco DOT eu*

Add native support for software protection dongles, like Feitian, Wibu, etc.:

The packed ELF will be encrypted using the USB dongle, and can only be executed, when the dongle is present.

Add runtime hooks, that check that the dongle is still present.

In case of using such a dongle extract - in case of onefile - the ELF to a RAMFS which again is encrypted using the dongle via loopback device.

Probably add check hooks to the application that use the dongle.

The mountpoint of the loopback on encrypted RAMFS shall be randomly located and limited to a given user (somtimes in /etc/..., /var/lib, /home/.neu, ...)

**Comment by matysek** [comment]
We will not implement this unless anyone is willing to contribute this feature.
