### ISSUE TITLE
after  pyintaller , subprocess not run in my code

### ISSUE THREAD

**Issue by Hjy20255** [pyinstaller/pyinstaller#3690]
hi~
first,i run 
pyinstaller --onefile -w  --hidden-import pandas._libs.tslibs.timedeltas gui.py
i get my exe successfully.
then， i run my exe ，
in gui.py has some “subprocess ”codes not run ！！！

p = subprocess.Popen(command_CANinfobase, shell=True,stdin=subprocess.PIPE, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)

how to solve this issue？

**Comment by Hjy20255** [comment]
command_CANinfobase is：
cd /d E:\PycharmProjects\04b_coverinfo\tools\bin&E:\PycharmProjects\04b_coverinfo\tools\build\gnumips\bin\mipsel-elf-g++.exe -O0 -g -Wall -c -fmessage-length=0 -mlong-calls E:\PycharmProjects\04b_coverinfo\CANinfobase.cpp&move E:\PycharmProjects\04b_coverinfo\tools\bin\CANinfobase.o E:\PycharmProjects\04b_coverinfo\CANinfobase.o

it can run by  windows cmd or pycharm  sucessfully!!!

**Comment by Hjy20255** [comment]
@bjones1

**Comment by Siecje** [comment]
Do you have minimal file that shows the problem?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
