### ISSUE TITLE
Using --noconsole flashes CMD window

### ISSUE THREAD

**Issue by GrahamboJangles** [pyinstaller/pyinstaller#3692]
I have a script that uses the CPU load to dynamically decide whether the computer should be in power saving mode or high performance mode. 

Here is the whole script:

    import os, os.path
    import sys
    import psutil
    import subprocess

    def subprocess_args(include_stdout=True):
        # The following is true only on Windows.
        if hasattr(subprocess, 'STARTUPINFO'):
            # On Windows, subprocess calls will pop up a command window by default
            # when run from Pyinstaller with the ``--noconsole`` option. Avoid this
            # distraction.
            si = subprocess.STARTUPINFO()
            si.dwFlags |= subprocess.STARTF_USESHOWWINDOW
            # Windows doesn't search the path by default. Pass it an environment so
            # it will.
            env = os.environ
        else:
            si = None
            env = None

   
        if include_stdout:
            ret = {'stdout': subprocess.PIPE}
        else:
            ret = {}

     
        ret.update({'stdin': subprocess.PIPE,
                    'stderr': subprocess.PIPE,
                    'startupinfo': si,
                    'env': env })
        return ret

    # A simple test routine. Compare this output when run by Python, Pyinstaller,
    # and Pyinstaller ``--noconsole``.
    if __name__ == '__main__':
        # Save the output from invoking Python to a text file. This is the only
        # option when running with ``--noconsole``.
        with open('out.txt', 'w') as f:
            try:
                txt = subprocess.check_output(['python', '--help'],
                                              **subprocess_args(False))
                f.write(txt)
            except OSError as e:
                f.write('Failed: ' + str(e))
			
    # subprocess.Popen("A:\\Python27\\Scripts\\dist\\auto2.exe", close_fds=True)
    # """ Now my python code can exit, and no nothing of itself will remain lingering """

    while True:

	    CPUload = (psutil.cpu_percent(interval=4))
	    RAMload = (psutil.virtual_memory().percent)

	    os.system('cls')

	    print("CPU Load: {}%".format(CPUload))
	    print("RAM Load: {}%".format(RAMload))

	    # planlist = subprocess.check_output(["powercfg", "/list"], shell=False, stderr=subprocess.PIPE, stdin=subprocess.PIPE).split('\n')
	    planlist = subprocess.check_output(["powercfg", "/list"], shell=False, **subprocess_args(False)).split('\n')	# Both of these lines seem to give the same result

	    firstplan = planlist[3]
	    secondplan = planlist[4]
	    thirdplan = planlist[5]

	    firstplanID = firstplan.split(": ")[1].split("  (")[0]
	    secondplanID = secondplan.split(": ")[1].split("  (")[0]
	    thirdplanID = thirdplan.split(": ")[1].split("  (")[0]

	    activeplan = subprocess.check_output(["powercfg", "/getactivescheme"], shell=False, stderr=subprocess.PIPE, stdin=subprocess.PIPE)

	    activeplanNAME = activeplan.split("(")[1].split(")")[0]
	    firstplanNAME = firstplan.split("(")[1].split(")")[0]
	    secondplanNAME = secondplan.split("(")[1].split(")")[0]
	    thirdplanNAME = thirdplan.split("(")[1].split(")")[0]

	    if "High performance" in firstplanNAME:
		    HighPerformance = firstplanNAME
		    HighPerformanceID = firstplanID

	    if "High performance" in secondplanNAME:
		    HighPerformance = secondplanNAME
		    HighPerformanceID = secondplanID

	    if "High performance" in thirdplanNAME:
		    HighPerformance = thirdplanNAME
		    HighPerformanceID = thirdplanID

	    if "Power saver" in firstplanNAME:
		    PowerSaver = firstplanNAME
		    PowerSaverID = firstplanID

	    if "Power saver" in secondplanNAME:
		    PowerSaver = secondplanNAME
		    PowerSaverID = secondplanID

	    if "Power saver" in thirdplanNAME:
		    PowerSaver = thirdplanNAME
		    PowerSaverID = thirdplanID

	    if activeplanNAME == PowerSaver:
		    print("Active plan: Power saver")
	    else:
		    if activeplanNAME == HighPerformance:
			    print("Active plan: High Performance")
		    else:
			    subprocess.call(["powercfg", "/s", HighPerformanceID])

	    if CPUload < 44:
		    if RAMload > 90:
			    if activeplanNAME == PowerSaver:
				    subprocess.call(["powercfg", "/s", HighPerformanceID])
				    print("Switching to High Performance by RAM load...")

	    if CPUload < 44:
		    if RAMload < 90:
			    if activeplanNAME == HighPerformance:
				    subprocess.call(["powercfg", "/s", PowerSaverID])
				    print("Switching to Power saver...")

	    if CPUload > 55:
		    if activeplanNAME == PowerSaver:
			    subprocess.call(["powercfg", "/s", HighPerformanceID])
			    print("Switching to High Performance...")

The script itself works fine, but when put into a Pyinstaller using `pyinstaller --noconsole --onefile scriptname.py`, the exe will run in the background, then flash the command window, then run in the background, then flash again periodically. 
I'm pretty sure that this line is causing the flashing:

    planlist = subprocess.check_output(["powercfg", "/list"], shell=False, **subprocess_args(False)).split('\n')

but it could be something else because the command window flashes more than once at a time, so it could be multiple lines.

Any help is appreciated.

**Comment by bjones1** [comment]
Try removing the call to `os.system`.

**Comment by bjones1** [comment]
You're on your own. Read your code carefully -- all calls to subprocess must have the arguments provided by `subprocess_args`, but they don't. This is not a get-your-code-fixed forum.

**Comment by GrahamboJangles** [comment]
@bjones1 Are you not here to help people with Pyinstaller issues? My code works perfectly fine without Pyinstaller. I would just like to use it with Pyinstaller.

**Comment by karolyi** [comment]
@GrahamboJangles I hope you have found the problem by now, if not then here's the solution:
https://stackoverflow.com/a/7006424/1067833
