### ISSUE TITLE
Option to pass libpython location to command line tool.

### ISSUE THREAD

**Issue by feluxe** [pyinstaller/pyinstaller#3697]
Hi there,

I've been fiddling with *pyinstaller* on the weekend and it's such an amazing project!

I just wanted to give some feedback and make a suggestion.

I complied a bunch of tools that run on different versions of Python on different machines and every time I had to set the `LD_LIBRARY_PATH` envvar in order to get the builds to work.

I was wondering if there is an option for `pyinstaller` to set the lib directory path, but I couldn't find one (please excuse me if I didn't read the docs carefully enough).

I think an option like this would be very useful:

    pyinstaller --libpy "/usr/local/lib" ...

Any love for something like this?

Cheers! :)

**Comment by htgoebel** [comment]
PyInstaller uses the pythonlib the python executable you are using is linked to. Please note the statically linked python executables are not supported. Why does a virtual environment not work for you?

**Comment by feluxe** [comment]
Thanks for your reply!

> Why does a virtual environment not work for you?

I'm using virtual environments via `pipenv`, but its not working. When I run `pipenv run pyinstaller ...` I get the *"Python library not found"* error from `pyinstaller`.

**Steps to reproduce the issue**

Download (e.g.) `Python3.6` and install it from source:
    
    $ cd /tmp
    $ wget https://www.python.org/ftp/python/3.6.6/Python-3.6.6.tgz
    $ tar -xvzf Python-3.6.0.tgz 
    $ cd Python-3.6.0
    $ ./configure
    $ make altinstall

Create a new virtualenv (`Python3.6`) in `/tmp/test`, and install `pyinstaller` in it:

    $ mkdir /tmp/test
    $ cd /tmp/test
    $ pipenv --python 3.6
    $ pipenv install --dev pyinstaller

Create a simple Python script in the same dir and try to build it via `pyinstaller` from within the virtualenv:

    $ echo "print('hello')" > test.py
    $ pipenv run pyinstaller test.py

I get this result:

> OSError: Python library not found: libpython3.6m.so.1.0, libpython3.6.so.1.0, libpython3.6mu.so.1.0

**Workaround**

What I did as a workaround:

Build `Python3.6` with this configuration:

    /configure --prefix=/usr/local/python3.6 --enable-shared

This creates the missing files (`libpython3.6m.so.1.0`, `libpython3.6.so.1.0`, `libpython3.6mu.so.1.0`) in `/usr/local/python3.6/`.

Then run this script from within the virtual env to build `test.py`:

```python
env = os.environ.copy()

env['LD_LIBRARY_PATH'] = '/usr/local/python3.6'

cmd = ['pyinstaller -y test.py']

subprocess.run(cmd, env=env, shell=True)
```
This works but, its somewhat complicated.

I ran into this with different machines and different OSes.

**Comment by htgoebel** [comment]
As I wrote: statically linked python executables are not supported. So you need to build with `--enable-shared` in the first place.

If you have different e.g. 3.6 versions installed on your system you might need to but additional efforts into isolating the environments. Maybe [Guix](https://www.gnu.org/software/guix/) would be a great help. It allows keeping different versions of some software around without interfering. See https://www.gnu.org/software/guix/manual/en/html_node/Features.html for details.

**Comment by feluxe** [comment]
Guix looks interesting, but the workaround I posted works fine when set up and I can't change the OS for some environments that I need to run pyinstaller on. It's easier for me to build with `--enable-shared` and stick to `LD_LIBRARY_PATH`.

**Comment by htgoebel** [comment]
You could install Guix in parallel to your existing operating system. This is actually what I'm doing.

But it came to my mind that you might get into other issues when transferring the frozen application to another system: All executables and  libraries within guix require to find the *exact* version in /gnu/store. While in normal cases this is a good thing (as this is how isolating different versions works) it inhibits running an application frozen under guix on another system.

**Comment by feluxe** [comment]
So far `pipenv` and the `altinstall`s of Python served me well for Python development. If I need an environment with specific requirements that I can't achieve on the host OS of machine I use Docker, which works very well :)
