### ISSUE TITLE
zipimport.ZipImportError: can't find module 'encodings'

### ISSUE THREAD

**Issue by 2424004764** [pyinstaller/pyinstaller#3699]
i use it pyinstaller compile error 
zipimport.ZipImportError: can't find module 'encodings'

complete error info:
Fatal Python error: initfsencoding: unable to load the file system codec
zipimport.ZipImportError: can't find module 'encodings'

Current thread 0x00004a7c (most recent call first):

**Comment by htgoebel** [comment]
Duplicate of #3642
