### ISSUE TITLE
Platforms File Issue

### ISSUE THREAD

**Issue by ubeytdemirr** [pyinstaller/pyinstaller#3700]
### **Hi Everyone!** 

> I am  quite rookie on python and github community. If I am breaking some basic rules please tolerate me.

I  got this error today:

Failed to start because it could not find or load the Qt platform plugin "windows"

If I add  C:\Python35\Lib\site-packages\PyQt5\plugins\platforms file to my .exe path, 
Its working otherwise its not working.

how can I add this files to my  platform file by editing pyinstaller  or is there another way to fix it ?

**Comment by bjones1** [comment]
Use the latest development version. It should be fixed there.

**Comment by ubeytdemirr** [comment]
Thanks for fast reply
