### ISSUE TITLE
pyinstaller is not working/supporting with SimpleCV

### ISSUE THREAD

**Issue by 6292santosh** [pyinstaller/pyinstaller#3706]
I am using pyinstaller of version 3.4.dev0+bbf964c6b on python 2.7.15 . I made a python script that takes the picture from webcam and sent it to my email address. I have used SimpleCV module to take the picture from webcam. After I finished  writing my program, I compiled my program using pyinstaller using command **pyinstaller -w -i 'myicon.ico' -F**. And pyinstaller compiled my program correctly but when I ran the same compiled file to another I am getting **fatal error failed to execute my_program**. I tried by removing everything related with SimpleCV and compiled again but this time it worked perfectly without throwing **fatal error**. I think pyinstaller is not able to compile or recognize the SimpleCV module. 
### How can I fix this error?

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

**Comment by 6292santosh** [comment]
Thank you @htgoebel for your reply. I want my script to be compiled where my compiled .exe program to run without console so  I followed your instruction and compiled my program using **pyinstaller --onedir Spyder.py -i icon.ico -w**. After compiling my script I got two folder **build and dist** where there is required package for my program. I made the setup file for my program using Inno Setup and included all the files as well as folders that were in **build and dist**. Everything went perfect. I installed the program from my setup where there is no python and pyinstaller installed but got this error:
![upload](https://user-images.githubusercontent.com/22255426/45067472-21723e00-b0e3-11e8-821a-ff8523d6a58c.jpg)

### Here is my source code of my script
[https://pastebin.com/g404psYh](url)

### Please help me to compile my program correctly.

**Comment by 6292santosh** [comment]
I have found the fix for my own problem. My program gave me fatal error because my script needs **opencv_ffmpeg342.dll** which should be placed in same directory where I have my executable file. Thank you very much for your time.

**Comment by Iamanorange** [comment]
I have similar problem.

Develop machine:
Windows 10 1809
Python 3.7.2
Pyinstaller 3.4
opencv-python 4.0.0

pyins_test.py
```python
import cv2
video_path = input()
cap = cv2.VideoCapture(video_path)
print(cap.get(3)) # width
print(cap.get(4)) # height
print(cap.get(7)) # frame count
```

Build with:
`pyinstaller --onedir --clean .\pyins_test.py`

Copy to deploy machine and run, result:
```
0.0
0.0
0.0
```

Manually move `opencv_ffmpeg400_64.dll` from develop machine to deploy machine, and result:
```
1920.0
1080.0
1514.0
```

Trying to build with `--noupx`. Doesn't help.

However, what I want is a one-executable-file to deploy, any suggestions?

**Comment by Iamanorange** [comment]
Solved by:
```powershell
$cv_path = & python -c "import cv2; print(cv2.__path__[0])"
pyinstaller --clean --add-binary $cv_path"\opencv_ffmpeg400_64.dll;." xxx.py
```
