### ISSUE TITLE
Use tox or invoke to ease some tasks

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#3715]
tox could be used for simplifying some tasks, e.g.

* render the current changelog to the terminal if you have any doubts.
* build the documentation
* support the release process
* run tests - maybe we could use tox to simplify CI configuration

The charming point about tox is that it automatically sets up virtual environments for each of these tasks, thus simplifying installation a lot. Experiences anybody?

The pip project uses [invoke](https://pypi.org/project/invoke/) and some [tasks](https://github.com/pypa/pip/tree/master/tasks). Maybe we can do this, too.

**Comment by bjones1** [comment]
Looking at the manual, tox doesn't seems to integrate well with Travis and Appveyor -- tox wants to run multiple environments, as does the CI tools.

I would like to use Python scripts for CI tasks, though. Bash/Windows batch file syntax is such a pain. I have some Python libraries and ideas from doing this on another project that I could contribute.

**Comment by Legorooj** [comment]
I'm going to close this - it's stale and as @bjones1 pointed out, `tox wants to run multiple environments`. True, this could simplify CI in the long run, but it isn't worth the effort for such little gain.
