### ISSUE TITLE
Hook for pyarrow (includes code for hook)

### ISSUE THREAD

**Issue by tomanizer** [pyinstaller/pyinstaller#3720]
I have created a pyarrow hook file.
Can you include it in your package, please?

hook-pyarrow.py
```
from PyInstaller.utils.hooks import collect_data_files, collect_dynamic_libs

hiddenimports = [
    "pyarrow._parquet",
    "pyarrow.formatting",
    "pyarrow.lib",
    "pyarrow.compat",
    "pyarrow.compat.*"
]

datas = collect_data_files('pyarrow')

binaries = collect_dynamic_libs('pyarrow')
```

**Comment by htgoebel** [comment]
Thank you for the code. Please provide a pull-request. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html).
