### ISSUE TITLE
Script using requests module fails with "getaddrinfo failed" when frozen, but works when unfrozen

### ISSUE THREAD

**Issue by tim-at-work** [pyinstaller/pyinstaller#3721]
This simple script works when run as a python script but fails when run as an exe frozen with the latest development version of pyinstaller on Windows 7 using the command line `pyinstaller --clean --onedir --noupx --debug all test-requests.py`

```
import requests
url = "http://www.example.com"
print("Visiting url(%s)" % (url))

r = requests.get(url, verify=False)
print("success")
```
 I'm using Python 3.7.0, requests 2.19.1, PyInstaller 3.4.dev0+cf9e6687f

The error looks like this:
```
`Visiting url(http://www.example.com)
Traceback (most recent call last):
  File "site-packages\urllib3\connection.py", line 171, in _new_conn
  File "site-packages\urllib3\util\connection.py", line 56, in create_connection
  File "socket.py", line 748, in getaddrinfo
socket.gaierror: [Errno 11003] getaddrinfo failed`
```

[full-error.txt](https://github.com/pyinstaller/pyinstaller/files/2358767/full-error.txt)

**Comment by htgoebel** [comment]
`getaddrinfo` is just using a operating system function, see https://github.com/python/cpython/blob/3.7/Lib/socket.py#L748. I can not see how this should be related to PyInstaller.

Are you freezing and running on the same machine?

**Comment by tim-at-work** [comment]
Thanks for looking at this. Yes, I'm freezing and running the exe on the same machine. And I'm testing the pre-frozen script on the same machine too.

**Comment by DavidVentura** [comment]
I am facing the exact same issue on python3.7, pyinstaller3.4 (from pip) on windows 10.

**Comment by htgoebel** [comment]
No new infos since several months, so I assume this is solved.

**Comment by tim-at-work** [comment]
No, the problem is still there on 3.5.dev0+d5a902d9e.

**Comment by klukonin** [comment]
@htgoebel 

I have the same issue with FLENT 2.0.1 version
Binary build fails when trying to call socket.getaddrinfo.
Unfrozen script works normally.


$ python --version
Python 3.8.10


$ pyinstaller --version
4.3

**Comment by klukonin** [comment]
@htgoebel 
Please reopen this issue.
