### ISSUE TITLE
PySide2 from conda-forge, using qt 5.6, after packaging with pyinstaller keyboard input does not work, and fonts dont get loaded.

### ISSUE THREAD

**Issue by mjscosta** [pyinstaller/pyinstaller#3724]
After packaging an application with pyinstaller, using pyside2, the keyboard input did not worked, nor the fonts could be loaded, outputting the error:

### Keyboard input error ###
similar error to https://github.com/lneuhaus/pyrpl/issues/333.

### Fonts error ###
`Fontconfig error: Cannot load default config file`

Used fixed, mentioned here: https://tutel.me/c/programming/questions/42595685/this+application+failed+to+start+because+it+could+not+find+or+load+the+qt+platform+plugin+quotxcbquot+in+quotquot

### Context ###

OS: ubuntu 16.04 Lts

 package | version | build 
------------ | ---------- | -------
https://anaconda.org/conda-forge/pyside2 | 5.6.0a1 | py36h45ccf91_3
https://anaconda.org/anaconda/qt | 5.6.2 | h974d657_12

I'll add a pull request with the fix for these two issues.

**Comment by mjscosta** [comment]
@htgoebel , splited pull request from https://github.com/pyinstaller/pyinstaller/pull/3620#pullrequestreview-152144741.

**Comment by bjones1** [comment]
This was fixed in 5b5791285332003940f4bc70c32bb0cf10a32917. Please reopen if there are still problems.
