### ISSUE TITLE
build exe is ok,but running the exe file error

### ISSUE THREAD

**Issue by jiangmingwen** [pyinstaller/pyinstaller#3727]
os：win10
python: 3.6.6

I want to write some scripts to quickly generate directories，So I have some *.zip files here,When I run a command, the *.zip file will be uncompressed.  

my dirs:
  initproject.py
  main.py
  main.spec
  template.zip   
  
i use pyinstaller -F main.spec build to exe, everything is ok!
this is my main.spec :
```
>  # -*- mode: python -*-
> block_cipher = None
> a = Analysis(['main.py'],
>             pathex=['H:\\topweb\\tool-cli\\topibd-mmd'],
>             binaries=[],
>             datas=[('./*.zip','.')],
>             hiddenimports=[],
>             hookspath=[],
>             runtime_hooks=[],
>             excludes=[],
>             win_no_prefer_redirects=False,
>             win_private_assemblies=False,
>             cipher=block_cipher)
> pyz = PYZ(a.pure, a.zipped_data,
>             cipher=block_cipher)
> exe = EXE(pyz,
>          a.scripts,
>          a.binaries,
>          a.zipfiles,
>          a.datas,
>          name='mmd',
>          debug=False,
>          strip=False,
>          upx=True,
>          runtime_tmpdir=None,
>          console=True 
>）
```
the exe size is 25MB, so i guess my zip is build in the exe

i use 7zip to uncompressed zip file  in initproject.py, there is my initproject.py:
```
>       source_dir = './template.zip'
>        cmd = 'call C:/"Program Files"/7-Zip/7z.exe x   %s -o%s ' % (source_dir, _source_dir)
>        p = subprocess.Popen(cmd, stdin=None, stdout=None, stderr=subprocess.PIPE, shell=True)
>        data = p.communicate()
>        if p.returncode:
>            print('\n【 Error 】: ' + data[1].decode('GBK'))
>            print('program returned code error {0}'.format(p.returncode))
>            sys.exit(1)
```
every thing is ok by  `python main.py `  for test

when i run the exe build by pyinstaller,   path  './tempalte.zip' is not found

**Comment by htgoebel** [comment]
> so i guess my zip is build in the exe

No, the zip is not build into the exe. It should have been copied beside the exe. If not, please check your pathes.

BTW: I suggest you use https://docs.python.org/3/library/zipfile.html instead of spawning a subprocess.
