### ISSUE TITLE
Windows issues with v3.4

### ISSUE THREAD

**Issue by gmyers18** [pyinstaller/pyinstaller#3730]
When installing v3.4 on Windows and then attempting to bundle I receive:
```
PyInstaller cannot check for assembly dependencies.
Please install PyWin32 or pywin32-ctypes.

pip install pypiwin32
```

This appears to be due to the v3.4 wheel (PyInstaller-3.4-py2.py3-none-any.whl) not including a dependency on pywin32-ctypes.  METADATA file only shows:

```
Requires-Dist: setuptools
Requires-Dist: pefile (>=2017.8.1)
Requires-Dist: macholib (>=1.8)
Requires-Dist: altgraph
```

I assume this is not the intended behavior and probably stems from the wheel being created on a non-Windows system (I don't have a lot of experience building wheels, so this is just a guess).  The logic in [setup.py](https://github.com/pyinstaller/pyinstaller/blob/v3.4/setup.py#L34) seems to support this:

```
if sys.platform.startswith('win'):
    REQUIREMENTS.append('pywin32-ctypes')
```

Perhaps [environment markers](https://hynek.me/articles/conditional-python-dependencies/) should be used here?

Also when forcing use of the source package (via `pip install --no-binary :all: --no-cache-dir PyInstaller`), so that pywin32-ctypes is correctly recognized as a dependency, I see errors related to `win32com` when bundling:

```
10490 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
10535 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
```

This doesn't seem to impact the creation of the bundle, but this did not occur with v3.3.1.  I assume this is due to the transition from pywin32/pypiwin32 to pywin32-ctypes, but I don't understand the purpose of win32com well enough to fully comprehend the implications here.

This is somewhat related to #3729 and #3513 in regards to pypiwin32 references and it seems like the installation documentation (https://github.com/pyinstaller/pyinstaller/blob/v3.4/doc/installation.rst#installing-in-windows) needs some minor updates as well.

**Comment by htgoebel** [comment]
The wheel is broken, I removed it just a few minutes ago. Please install PyInstaller again using
```
pip install --force-reinstall --no-binary :all: pyinstaller
```
This should install from source.

**Comment by htgoebel** [comment]
Now a more verbose answer: Thank you for your report. It made my aware that I must not publish universal wheels - which is why I removed the wheel.

Regarding environment markers: Unfortunately these require a somewhat new version of setuptools (I can't remember which version, I checked this quite some time ago), so we might not be able to use them for some more time.

Regarding the win32com: Please open a separate ticket for this issue. This is easier to track then. Also given an appropriate title this might attract people with know-how in this area.

**Comment by gmyers18** [comment]
@htgoebel Thanks.  I opened #3733 for the win32com issue.  Also, FWIW while the wheel is removed from PyPi it is still available as a GitHub asset at https://github.com/pyinstaller/pyinstaller/releases/tag/v3.4.

**Comment by htgoebel** [comment]
@gmyers18 Thaanks for both. I now removed the wheel from github, too.
