### ISSUE TITLE
pyinstaller exclude-module exception 

### ISSUE THREAD

**Issue by redstoneleo** [pyinstaller/pyinstaller#3732]
One can test the issue with [somedir.zip](https://github.com/pyinstaller/pyinstaller/files/2370264/somedir.zip).

I import the the Zip archive `ykdl.zip` using `ykdlParse.py` with the following code 

    import sys
    sys.path.insert(0, 'ykdl.zip')
    import ykdl.common as common
    sourceUrl = "https://www.miaopai.com/show/DqFsOZrew8VgFrvEr30nZkZhZJ~pn8YCngFvEg__.htm"
    site, new_url = common.url_to_module(sourceUrl)
    videoInfoList = site.parser(new_url)
    videoInfo = videoInfoList.streams[videoInfoList.stream_types[0]] 
    print('------------', videoInfo)  # videoSize  , baseName, videoUrls,

After freezed the program into an executable using pyinstaller with 

    pyinstaller  --noconfirm   --exclude-module ykdl ykdlParse.py

I got the following exception when run ykdlParse.exe from command prompt ,

    >C:\dist\ykdlParse.exe
    Traceback (most recent call last):
      File "ykdlParse.py", line 5, in <module>
        import ykdl.common as common
      File "ykdl.zip\ykdl\common.py", line 7, in <module>
    ImportError: cannot import name 'get_location'
    [7068] Failed to execute script ykdlParse

Any solutions?  I got the exception with  Win7 32 bit ,PyInstaller: 3.4, Python: 3.6.5.

**Comment by htgoebel** [comment]
Since you are excluding `ykdl`, dependencies for `ykdl` will not be collected - as written in the manual. Look at ykdl.zip\ykdl\common.py", line 7 to get the missing module, then add it using `--hidden-import`. Do the same for all other missing modules.

A more robust way would be to *not* exclude `ykdl`, but adjust the spec-file (see manual) and remove `ykdl` and all entries starting with `ykdl.` (mind the dot) from `a.pure`. `a.pure` is a `TOC`, see manual-section about TOC for more information.

**Comment by redstoneleo** [comment]
Perhaps I found a bug.
One can test the issue with [D.zip](https://github.com/pyinstaller/pyinstaller/files/2371611/D.zip).

After freezed the same  `ykdlParse.py` in each directory  separately   into an executable using pyinstaller with 

    pyinstaller  --noconfirm   --exclude-module ykdl ykdlParse.py

I got the following exception when run ykdlParse.exe from command prompt  in `BaiduYunDownload2` but not in `somedir`,

    >C:\dist\ykdlParse.exe
    Traceback (most recent call last):
      File "ykdlParse.py", line 5, in <module>
        import ykdl.common as common
      File "ykdl.zip\ykdl\common.py", line 7, in <module>
    ImportError: cannot import name 'get_location'
    [7068] Failed to execute script ykdlParse

so I guess it is the length of the directory name that caused the problem .

**Comment by htgoebel** [comment]
This is the same error message as above. Nothing changed. Please read the manual.

Please not that for security reasons I'm not going to download any zip-file.

**Comment by redstoneleo** [comment]
I added code between the two lines of hash (#) characters to exclude ykdl and all entries starting with ykdl.(mind the dot), is this right ?

    D:\BaiduYunDownload2\ykdlParse.spec 
    # -*- mode: python -*-
    
    block_cipher = None
    
    
    a = Analysis(['ykdlParse.py'],
                 pathex=['D:\\BaiduYunDownload2'],
                 binaries=[],
                 datas=[],
                 hiddenimports=['json', 'queue'],
                 hookspath=[],
                 runtime_hooks=[],
                 excludes=['ykdl'],
                 win_no_prefer_redirects=False,
                 win_private_assemblies=False,
                 cipher=block_cipher,
                 noarchive=False)
    ##############code to exclude ykdl and all entries starting with ykdl.(mind the dot)#########################################
    excludedTOCobject = []
    for TOCobject in a.pure:
      name, path, typecode = TOCobject
      if name.startswith('ykdl'):
        excludedTOCobject.append(TOCobject)
        # print('---------a.pure-------', name)
    
    # a.binaries -= excludedTOCobject  # [('ykdl', None, None), ('ykdl.', None, None)]
    a.pure -= excludedTOCobject  # [('ykdl', None, None), ('ykdl.', None, None)]
    ########################################################################
    pyz = PYZ(a.pure, a.zipped_data,
              cipher=block_cipher)
    exe = EXE(pyz,
              a.scripts,
              [],
              exclude_binaries=True,
              name='ykdlParse',
              debug=False,
              bootloader_ignore_signals=False,
              strip=False,
              upx=True,
              console=True)
    coll = COLLECT(exe,
                   a.binaries,
                   a.zipfiles,
                   a.datas,
                   strip=False,
                   upx=True,
                   name='ykdlParse')

As I tested with `pyinstaller D:\BaiduYunDownload2\ykdlParse.spec` , the exception still exists .

**Comment by htgoebel** [comment]
Please do not expect us to do you programming job. We can guide you, but we will are not going to solve this for you and not do your work. We are all volunteers here.
