### ISSUE TITLE
Module 'PyQt5.QtPrintSupport' not imported 

### ISSUE THREAD

**Issue by totocaca123** [pyinstaller/pyinstaller#3738]
I use Pyinstaller 03.04 with PyQt5 version 5.11.2 (both latest official version). 
Exe file is build successully (I added PyQt5 in hiddenimports)

In my code, I use QScintilla (part of PyQt5) and after launching exe file, I have following error:
ModuleNotFoundError: No module named 'PyQt5.QtPrintSupport'

Part of my code which is not supported
`from PyQt5 import Qsci`

After adding PyQt5.QtPrintSupport' in hiddenimport, issue was solved.

**Comment by bjones1** [comment]
Currently, PyInstaller doesn't support QScintilla. Would you be interested in contributing hooks and tests to support it?

**Comment by bjones1** [comment]
Supply a PR if you'd like to contribute. I'm closing this issue.

**Comment by kurtjohnsonADA** [comment]
I have an application I have compiled using PyInstaller that uses QScintilla and I plan to augment my use of QScintilla going forward.  If still needed, I would be glad to contribute toward PyIntaller supporting QScintilla by contributing hooks and tests.  Please contact me or let me know next steps.

**Comment by bjones1** [comment]
Contributions are welcome! See https://pyinstaller.readthedocs.io/en/stable/development/index.html. It looks like this needs a `hook-QSci.py` with contents of `hiddenimports = PyQt5.QtPrintSupport`, then a test like [this](https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/test_libraries.py#L346) that simply imports `QSci`.

**Comment by simzhangbest** [comment]
from PyQt5.Qsci import QsciScintilla
my Main.py file need this import file and using pyinstaller (version 4.0) to package my python-project to exe, when I run my Main.exe "ModuleNotFoundError: No module named 'PyQt5.QtPrintSupport'". can you help me to find how can I fix this? THX

**Comment by kurtjohnsonADA** [comment]
Hi simzhangbest,

I created a spec file and added it to my list of hiddenImports as shown below:

a = Analysis(['ADAMain.py'],
             pathex=['C:\\Users\\Kurt\\Desktop\\PythonScripts\\ADA Repository\\code'],
             binaries=[],
             datas=added_files,
             hiddenimports=['cython', 'sklearn', 'sklearn.ensemble', 'sklearn.neighbors.typedefs', 'sklearn.neighbors.quad_tree', 'sklearn.tree._utils', 'PyQt5.QtPrintSupport'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

**Comment by securityhigh** [comment]
MacOS Monterey, Pyinstaller 5.3, Python 3.10.6, PyQT5
I added HiddenImports in main.spec, don't work for me :(

`ModuleNotFoundError: No module named 'PyQt5.QtPrintSupport'`
`[80322] Failed to execute script 'main' due to unhandled exception!`

**Comment by bwoodsend** [comment]
Did you actually rebuild using `pyinstaller main.spec` or did you use `pyinstaller main.py`?
