### ISSUE TITLE
PyQt5 Plugins path not found with anaconda

### ISSUE THREAD

**Issue by JothanChanes** [pyinstaller/pyinstaller#3740]
The plugin path is determined incorrectly in hooks/qt.py. Qt requires that QApplication is instantiated first, before any other calls (see [1]).

Changing json_str in qt.py resolves this ([patch](https://github.com/pyinstaller/pyinstaller/files/2378518/qt.py.patch.txt)):

            json_str = exec_statement("""
                import sys

                # exec_statement only captures stdout. If there are
                # errors, capture them to stdout so they can be displayed to the
                # user. Do this early, in case PyQt5 imports produce stderr
                # output.
                sys.stderr = sys.stdout

                import json
                from %s import QtWidgets # import for QApplication
                from %s.QtCore import QLibraryInfo

                QtWidgets.QApplication([]) # Instantiate first to get correct paths
                paths = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
                location = {x: QLibraryInfo.location(getattr(QLibraryInfo, x))
                            for x in paths}
                try:
                    version = QLibraryInfo.version().segments()
                except AttributeError:
                    version = None
                print(str(json.dumps({
                    'isDebugBuild': QLibraryInfo.isDebugBuild(),
                    'version': version,
                    'location': location,
                })))
            """ % (self.namespace, self.namespace)) # %s is needed twice

[1] https://forum.qt.io/topic/46214/qt-conf-since-5-3-1-ignored/7

This may also be relevant to #2857 and #3479. I'd like to mention that Qt is not broken in anaconda and that it is not required to set paths manually.

**Comment by smazoyer** [comment]
Thanks it solved my problem that was similar to #3479

**Comment by bjones1** [comment]
@JothanChanes, thanks. I'm testing this fix to make sure all tests pass. See also a comment at https://forum.qt.io/post/224720 that explains this as well.

**Comment by JothanChanes** [comment]
@bjones1, thanks for testing. I realized that we may need to check whether we have PyQt4 or PyQt5 as QApplication was moved from QtGui(4) to QtWidgets(5).

**Comment by bjones1** [comment]
@JothanChanes, would you mind testing my branch to make sure it works on Anaconda? I don't hae that installed on my PC. It's at https://github.com/bjones1/pyinstaller/tree/issue_3740.

This code is only used for Qt5. Also, I imported QCoreApplication, which is in QtCore for both Qt5 and Qt4.

**Comment by JothanChanes** [comment]
@bjones1, no problem. I can test it on Monday when I'm back in office again.

**Comment by bjones1** [comment]
Sounds good. Thanks!

**Comment by JothanChanes** [comment]
@bjones1, thanks, it works, also with a QCoreApplication instance.

I wonder whether it's a design decision on behalf of Qt to require a
QApplication instance, though, and whether a QCoreApplication will also
suffice in future versions...

**Comment by bjones1** [comment]
Great! `QCoreApplication` should be fine, since that's where all the library path handling functions are defined.

**Comment by bjones1** [comment]
Fixed in 268f57a06b2ccb4b6e97b2f26f135efd4985dec6.

**Comment by awa5114** [comment]
@bjones1 This change is not yet reflected in the distribution I got from [conda ](https://anaconda.org/conda-forge/pyinstaller) (version 3.4) although it seems to have been made before the last anaconda upload (25 days ago). Could anyone explain why its not in there? I prefer not modifying my local copy of `pyinstaller` before I use it.

**Comment by bjones1** [comment]
This change is in develop, not in a released version. For this feature, use develop or wait for the next release.

**Comment by rayjgold** [comment]
@bjones1   Hi, just wanted to let you know that this thread helped me solve my plugin issues.   However, your patch did not work for me until I added :  """ % (self.namespace, self.namespace))    to the end of the json statement.

This is tested from the current version/install of anaconda, as of today, as well as a conda install of pyinstaller.

Thanks
