### ISSUE TITLE
Build bootloader with ASLR support

### ISSUE THREAD

**Issue by sundarsan** [pyinstaller/pyinstaller#3743]
is there any flags to enable ASLR while generating binaries.

Please see my spec file attached for your reference 

`# -*- mode: python -*-

block_cipher = None
import sys, os
import datetime
from os import path
site_packages = next(p for p in sys.path if 'site-packages' in p)

site_packages = next(p for p in sys.path if 'site-packages' in p)

frozen = 'not'
if getattr(sys, 'frozen', False):
        # we are running in a bundle
        frozen = 'ever so'
        bundle_dir = sys._MEIPASS
else:
        # we are running in a normal Python environment
        bundle_dir = bundle_dir = os.path.join(os.path.dirname(sys.argv[0]))

with open("version.txt", 'w') as f:
        f.write("")

with open("version.txt", 'w') as f:
        f.write("")

a = Analysis(['run.py','app/__init__.py','app/settings.py','app/api/main/endpoints/common.py'],
             pathex=['/Users/balaaravind/Development/git/Backend'],
             binaries=[],
             datas=[(os.path.join(site_packages,"docx","templates"), "docx/templates"), ("version.txt", "."),
             ('static','static'),( ('app/api/main/endpoints/templates','app/api/main/endpoints/templates'))],
             hiddenimports=['engineio.async_gevent','gevent-websocket','aniso8601','bcrypt','cffi','click','python-docx','Flask','Flask-Bcrypt','flask-restplus','Flask-SocketIO','ipaddr','itsdangerous','Jinja2','jsonschema','MarkupSafe','pycparser','PyJWT','pytz','requests','six','sqlalchemy','sqlalchemy.ext.baked','Werkzeug','flask-cors', 'flask_wtf', 'wx', 'win32api', 'cryptography'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
import migcore.core.version as version
with open("version.txt", 'w') as f:
        f.write(version.get_development_version())
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
import migcore.core.version as version
with open("version.txt", 'w') as f:
        f.write(version.get_development_version())
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name='Tool-%s-[BUILD_TYPE]-%s'%(version.get_development_version(),datetime.datetime.today().strftime('%Y%m%d')),
          debug=True,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True ,
          icon='256x256.ico')
`

**Comment by kingsawyer** [comment]
Looking into the same thing. I think we will have to rebuild the bootloaders (there are 4 windows stub exe files) see https://pyinstaller.readthedocs.io/en/latest/bootloader-building.html. Those exes are not rebuilt when you build your application, so there isn't a way to pass linker settings to them. Someone else correct me if I'm wrong.

**Comment by rokm** [comment]
Closing this because, as far as I know, bootloader binaries should support ASLR on all three major platforms:
* the toolchain used to build pre-built Windows bootloader executables seems to have both `/DYNAMICBASE` and `/HIGHENTROPYVA` enabled by default (for 64-bit version; the 32-bit version has only `/DYNAMICBASE` enabled)
* the toolchain used to build pre-built Linux bootloader executables enables PIE by default, so they are relocatable
* the toolchain on macOS enables relocation (PIE) by default as well
