### ISSUE TITLE
Exe file do not import system installed modules while running:

### ISSUE THREAD

**Issue by Nikson-A** [pyinstaller/pyinstaller#3744]
Some modules are excluded while pyinstaller make exe file to minimize file size
After .exe file created, it should not use system installed modules, will throw an Exception while running .exe file,
ImportError: No module named "system installed module name"

**Comment by htgoebel** [comment]
> Some modules are excluded while pyinstaller make exe file to minimize file size

As PyInstaller does not exclude module to try to minimize the fie size, this is not a PyInstaller issue.
