### ISSUE TITLE
turbodbc, dll load failed: The specified module could not be found

### ISSUE THREAD

**Issue by VUXIAOCHEN** [pyinstaller/pyinstaller#3747]
I manually created a hook_turbodbc.py, Also adding turbodbc as hiddenimport.
But I got error: "DLL load failed: The specified module could not be found" when my application try to import module 'turbodbc.connect' from \AppData\Local\Temp\xx\turbodbc\connect.pyc

**my .spec:**

 -*- mode: python -*-

block_cipher = None

a = Analysis(['src\\cli.py'],
             pathex=['...\\Lib\\site-packages', '...\SCFS_TXT_TO_SQL_Py'],
             binaries=[],
             datas=[],
             hiddenimports=['turbodbc', 'psutil', 'upit', 'upit.sqlEngine', 'upit.conf.settings'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='cli',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )

**my hook file:**

from PyInstaller.utils.hooks import get_pyextension_imports
hiddenimports = get_pyextension_imports('turbodbc')

Can anyone help or provide hook_turbodbc?

Thanks a lot!

**Comment by bjones1** [comment]
This *might* work for your hook:

``` Python
from PyInstaller.utils.hooks import collect_all, get_pyextension_imports

datas, binaries, hiddenimports = collect_all('turbodbc')
hiddenimports += get_pyextension_imports('turbodbc')
```

**Comment by VUXIAOCHEN** [comment]
> This _might_ work for your hook:
> 
> ```python
> from PyInstaller.utils.hooks import collect_all, get_pyextension_imports
> 
> datas, binaries, hiddenimports = collect_all('turbodbc')
> hiddenimports += get_pyextension_imports('turbodbc')
> ```

Hi bjones1,
Thank you for your help and reply!
I included the hook from you and rebuild/reinstall pyinstaller, use it to create new .exe file but still get dll issue as attached screeshot which is the same problem

<img width="259" alt="166" src="https://user-images.githubusercontent.com/42323371/45737215-7cc92380-bbed-11e8-9058-8ef61f417769.PNG">
<img width="257" alt="177" src="https://user-images.githubusercontent.com/42323371/45737221-805caa80-bbed-11e8-97f7-2de51e91b822.PNG">

The 6th line of turbodbc.connect.py: "from turbodbc_intern import connect as intern_connect"
turbodbc_intern exists in .PyCharmCE2018.2\system\python_stubs\-1824449559\turbodbc_intern.py
It seems to me this file brings complexity and problem but I haven't found solution for this :-/
Can you please help?

Also more info, the .exe file works locally, but the dll problem happens in server.
The server environment: Windows Server 2012 R2 Standard, 64-bit Operating Syste, x64-based processor

**Comment by bjones1** [comment]
I don't have much time to devote to this, unfortunately. Finding and including the missing DLL should help.
