### ISSUE TITLE
Show a picture while Booting

### ISSUE THREAD

**Issue by sorush-khajepor** [pyinstaller/pyinstaller#3748]
The app I made with PyInstaller on my laptop (Win 7 64bit, core i7 3632QM 2.2Ghz , 8GB ram, SATA HDD) takes 4-8 seconds to boot. The app is made in folder style (not one-file). I use several libraries including WxPython, Matplotlib, Numpy, Pickle, and  SciPy. 

1) Is it normal to have this start-up overhead?
2) Is it possible that PyInstaller shows an app logo/picture while booting (preferably with progress bar) that the user knows it is working in the background?

I know this is not an issue, actually PyInstaller is very stable and great application in my experience. I just didn't know where to ask these.

**Comment by tallforasmurf** [comment]
The obvious first question is, how long does it take to start up when running directly under python (`python myapp.py` in the command window)? Really there is no reason for one-folder mode to take any longer than that. One-**file** mode has the additional step of unpacking the zipped archive onto temp disk space, but this is not true of one-folder.

**Comment by htgoebel** [comment]
Thus said: Put everything you need to display the image at the very beginning of your main script.

**Comment by sorush-khajepor** [comment]
A Freshly booted Windows, I ran the script via command, python app.py. I added a print("Hello") on screen on top of all imports. I timed it with my phone, 
1- "Hello" Appeared after 3 seconds
2- GUI appeared after 6 seconds
Next runs takes only 2 seconds to see the GUI.
So I think you are right, it is python being slow to start for the first time.
