### ISSUE TITLE
--add-data pack .txt  file faile on Win10

### ISSUE THREAD

**Issue by 625781186** [pyinstaller/pyinstaller#3749]
I have a python file name "pyi.py" and a txt file name "read.txt"  in 'F://' ; 
```
#pyi.py
# -*- coding: utf-8 -*-

if __name__ == "__main__":
    import sys, os
    with open("./read.txt", "r+", encoding="utf-8") as f:
        text = f.read()
        print(text)
```
I use command 
```
pyinstaller -F --add-data "read.txt;." pyi.py
```
or
```
pyinstaller -F --add-data "read.txt;dist" pyi.py
```
Packing successfull , but when I run pyi.exe ,  cmd show one error  is:
```
FileNotFoundError: [Errno 2] No such file or directory: './read.txt'
```
I don't know how to solve it.
Thank you.

**Comment by htgoebel** [comment]
Please read the manual on how to access files at run-time.

**Comment by 625781186** [comment]
> 请阅读有关如何在运行时访问文件的手册。

Sorry , I read the Doc of pyinstaller , it told me this ok .
I use command No -F
```
pyinstaller  --add-data "read.txt;." pyi.py
```
OK ,  I run pyi.exe is OK ;
but I use command
```
pyinstaller  -F --add-data "read.txt;." pyi.py
```
It's error.
The Doc of pyinstaller told me it;s OK.
But I don't know why , if you know , please told me , thanks.

**Comment by 625781186** [comment]
> Please read the manual on how to access files at run-time.

Sorry , I read the Doc of pyinstaller , it told me this ok .
I use command No -F

pyinstaller  --add-data "read.txt;." pyi.py
OK , I run pyi.exe is OK ;
but I use command

pyinstaller  -F --add-data "read.txt;." pyi.py
It's error.
The Doc of pyinstaller told me it's OK.
But I don't know why , if you know , please told me , thanks.
or give me a right command !

**Comment by tallforasmurf** [comment]
I think @htgoebel is referring to [this manual topic](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-sys-executable-and-sys-argv-0). Key for you is what you get from `os.getcwd()` which is where the program will look for `./filename`. Maybe just put `print( 'os.getcwd is', os.getcwd() )` in pyi.pi to see.

**Comment by 625781186** [comment]
> I think @htgoebel is referring to [this manual topic](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-sys-executable-and-sys-argv-0). Key for you is what you get from `os.getcwd()` which is where the program will look for `./filename`. Maybe just put `print( 'os.getcwd is', os.getcwd() )` in pyi.pi to see.

Thank you very much ! I'm success !'

**Comment by 625781186** [comment]
> So what was the answer? What did you have to change in your script?

Like this :
```
#pyi.py
# -*- coding: utf-8 -*-

import os

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)

if __name__ == "__main__":
    import sys, os
    with open(resource_path("read.txt"), "r+", encoding="utf-8") as f:
        text = f.read()
        print(text)
```

**Comment by 625781186** [comment]
简单说一下 ， 使用单文件 -F 打包 ，运行的时候会把app解压到临时目录 ， [官方解释](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file-and-sys-meipass)
但是运行程序的时候工作目录没有切换 到解压目录 ， 所以造成相对路径的资源文件没找到 ，
以上是两种办法 ，
还有一种更简便的办法 ，  只要在运行的加一句代码`os.chdir(os.getcwd())` 切换工作目录即可
