### ISSUE TITLE
macOS: Pyinstaller spoils the graphics(Gtk3)

### ISSUE THREAD

**Issue by Dedekind125** [pyinstaller/pyinstaller#3755]
Hello, I have successfully build my Python Gtk+3 application ([source code](https://github.com/Dedekind125/python-chess-claims-check)) with the -w option for my macOS.
But the problem is, when i run the .app file the graphics seems to be spoiled (i can even see the pixels). 
On the contrary when i run the exec file (located at /dist directory) the graphics are ok.

When i run it from the terminal:
<img width="623" alt="screen shot 2018-09-21 at 00 19 56" src="https://user-images.githubusercontent.com/7364814/45850209-e9ebce80-bd3d-11e8-8cde-4767e460fd3a.png">
When i open the app file: 
<img width="625" alt="screen shot 2018-09-21 at 00 20 17" src="https://user-images.githubusercontent.com/7364814/45850210-e9ebce80-bd3d-11e8-908f-5afc153f96ed.png">

Platform: macOS High Siera (10.13.6)
Python 3.6.5

Any ideas?

**Comment by tallforasmurf** [comment]
I think you'll find an answer here:
https://pyinstaller.readthedocs.io/en/stable/spec-files.html#spec-file-options-for-a-mac-os-x-bundle
You need to add a plist with  'NSPrincipleClass': 'NSApplication' as shown. I can't say why the default is different for a .app versus command line.

**Comment by Dedekind125** [comment]
Adding` 'NSPrincipleClass': 'NSApplication'` to my info_plist as the documentation says didn't worked.
But it worked when i added '`NSHighResolutionCapable':True`

Thanks for the help!

**Comment by htgoebel** [comment]
@Dedekind125 Thansk for reading the manual before wasting your spare time.
