### ISSUE TITLE
PyInstaller+Python3.7.0 sys.path[0]  error.

### ISSUE THREAD

**Issue by aozima** [pyinstaller/pyinstaller#3757]
I have a python script and a binary exe

```
>dir
package.py
tools.exe
```

in package.py work fine.

```
    cmd = sys.path[0] + '\\' + 'tools.exe'
    print('execute cmd:%s' % cmd)
```

I want get a single exe.
modify the package.spec
```
a.datas += [('tools.exe','tools.exe','.')]
```
use PyInstaller: 3.3 and python 2.7.14 work fine.

but when I upgrade to python3.

try PyInstaller 3.4 

```
62 INFO: PyInstaller: 3.4
62 INFO: Python: 3.7.0
62 INFO: Platform: Windows-7-6.1.7601-SP1
```
and the latest development version,

```
46 INFO: PyInstaller: 3.5.dev0+268f57a06
46 INFO: Python: 3.7.0
46 INFO: Platform: Windows-7-6.1.7601-SP1
``` 

the single exe run error:
```
execute cmd:C:\Users\user\AppData\Local\Temp\_MEI18842\base_library.zip\tools.exe
not found.
```

I found tools.exe in `C:\Users\user\AppData\Local\Temp\_MEI18842\tools.exe`
not in zip archive base_library.zip

**Comment by htgoebel** [comment]
Please read the manual how to access data at run-time.
