### ISSUE TITLE
BIG-Time Thank you!

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [pyinstaller/pyinstaller#3761]
Hope it's appropriate to post a **_"THANK YOU"_** message here....

PyInstaller is working beautifully with my project and has propelled it into a whole new world!  The ability to distribute a single EXE file is nothing short of a miracle.  I'm able to launch straight into a GUI that looks like a "real Windows program".  

Thank you to all the volunteers working on PyInstaller! 💯

**Comment by denravonska** [comment]
Are the issues on this project monitored? While appreciation is neat, maybe this should be closed?

**Comment by Metallicow** [comment]
thankee sai
