### ISSUE TITLE
Installation fails (no module cffi / invalid syntax)

### ISSUE THREAD

**Issue by pvanik1** [pyinstaller/pyinstaller#3763]
I tried this with the latest development version as well. "pip install pyinstaller" fails with the following error:

```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
  File "c:\program files\python37\lib\site-packages\win32ctype
    import cffi
ModuleNotFoundError: No module named 'cffi'

During handling of the above exception, another exception occurred

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\...~1\AppData\Local\Temp\pip-req-build-1kx
    from PyInstaller import __version__ as version, HOMEPATH,
  File "C:\Users\...~1\AppData\Local\Temp\pip-req-build-1kx
    from . import compat
  File "C:\Users\...~1\AppData\Local\Temp\pip-req-build-1kx
    from win32ctypes.pywin32 import pywintypes  # noqa: F401
  File "c:\program files\python37\lib\site-packages\win32ctype
    from win32ctypes.pywin32 import win32api
  File "c:\program files\python37\lib\site-packages\win32ctype
    from win32ctypes.core import _common, _kernel32, _backend
  File "c:\program files\python37\lib\site-packages\win32ctype
    from .ctypes import _advapi32, _common, _kernel32
  File "c:\program files\python37\lib\site-packages\win32ctype

    ^
SyntaxError: invalid syntax

----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\...
```

When I installed cffi, I tried reinstalling pyinstaller and again got the same error as after Traceback above.

**Comment by bjones1** [comment]
I can't reproduce this. Please provide more information per https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#when-submitting-a-bug.

**Comment by pvanik1** [comment]
I deleted the cache and tried again with `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip` but the same thing happened.

I'm using Python 3.7 on Windows 10 Enterprise 64-bit. My version of win32ctypes (mentioned in the log) is 
```
pywin32           223
pywin32-ctypes    0.1.2
```
I'd gone through the guide and I believe this is all the useful information I can provide, since I haven't even gotten past the installation of pyinstaller.

**Comment by bjones1** [comment]
You have an older version of `pywin32-ctypes`. Try `pip install -U pywin32-ctypes` then reinstall PyInstaller.

**Comment by htgoebel** [comment]
@bjones1 Shall we require a minimum version of pywin32-ctypes?

**Comment by bjones1** [comment]
Probably. Version 0.2.0 is required for Python 3.7, but not for older versions of Python.

**Comment by pvanik1** [comment]
> You have an older version of `pywin32-ctypes`. Try `pip install -U pywin32-ctypes` then reinstall PyInstaller.

After doing it, installation completed successfully. Thank you!
