### ISSUE TITLE
How to convert Python package to exe ?

### ISSUE THREAD

**Issue by GoodPal** [pyinstaller/pyinstaller#3764]
Our Programs is not always a Python source file !. The Python may be associated with a file or an image, that is located inside the source of the application to the file path inside the package. For example, when setting the application icon in Tkinter Or Include image for app background Or add a database file to the program!
```
    root.iconbitmap('favicon.ico')
    PhotoImage(file = 'python_logo.gif')
```
Most of the time it is necessary to include multiple files in the program.
In Pyinstaller only the source file expires in the exe format. If the program contains a file or image path inside the source, then the program will not be executed , In that event,The source of the application and files are in a package (on a route).

Please provide a solution to this problem, So as possible convert a package containing source and file into exe

**Comment by htgoebel** [comment]
Please read the manual.

**Comment by htgoebel** [comment]
> Please put a link to it

If you are too lazy to red the readme, why should I wast my time helping you? Should I also feed you?
