### ISSUE TITLE
macOS mojave, tkinter and PyInstaller not playing nice...

### ISSUE THREAD

**Issue by tazzben** [pyinstaller/pyinstaller#3765]
I believe there might be a an issue with the interaction of PyInstaller, tkinter and the release version of macOS mojave.   Specifically, it seems any python 3 application that relies on tkinter will either not start or will appear all black after being bundled with PyInstaller (this is about the resulting files, not the build process).  This has been tested on a mojave on both the release version of pyinstaller (3.4) and the current development version.

As an example script, consider the hello world script posted on python.org:

```
import tkinter as tk

class Application(tk.Frame):
    def __init__(self, master=None):
        super().__init__(master)
        self.pack()
        self.create_widgets()

    def create_widgets(self):
        self.hi_there = tk.Button(self)
        self.hi_there["text"] = "Hello World\n(click me)"
        self.hi_there["command"] = self.say_hi
        self.hi_there.pack(side="top")

        self.quit = tk.Button(self, text="QUIT", fg="red",
                              command=root.destroy)
        self.quit.pack(side="bottom")

    def say_hi(self):
        print("hi there, everyone!")`


root = tk.Tk()
app = Application(master=root)
app.mainloop()
```

Just to clarify, using the standard anaconda build (python 3.6) on mojave, this script executes as expected.  However, after building the file(s) using pyinstaller, you get one of three outcomes (depending on the python version).

1. In python 3.6.1, the resulting app launches, however, the interface is blanked out
2. In later anaconda python 3.6.x versions, the directory version launches if the executable is launched directly, the standalone executable launches, but the ".app" bundle does not (even when the standalone executable is identical to what's in the bundle).
3. In the latest anaconda python version (3.6.6), the resulting executable in the directory will launch, but it will be all black.  The resulting ".app" will not launch.

Thank you to all of the folks who work on this project.  It is of great value to me.  Please let me know if you want more details.

**Comment by htgoebel** [comment]
Anaconda is know to cause issue due ti how anaconda works. Please use a proper Python installation from python.org.

**Comment by rostyslavb** [comment]
@htgoebel I have a similar problem, but I use python=3.6.8 from python.org, as you pointed. Can you check out the results https://stackoverflow.com/questions/56092383/how-to-fix-msgcatmc-error-after-running-app-from-pyinstaller-on-macos-mojave?
