### ISSUE TITLE
Limitation: spec file must be contiguous to entrypoint

### ISSUE THREAD

**Issue by Alphapage** [pyinstaller/pyinstaller#3769]
Hello,

I try pyinstaller and it works great if the current working directory and the spec file are in the same directory as `main.py`, but as soon as I change the current working directory or change the spec file location, then pyinstaller isn't able to find static modules resulting in `Module not found error`.

Is it a limitation for now ?

Thank you in advance for your answers.

**Comment by htgoebel** [comment]
As you can see in the spec-file,it contains some paths. If you change locasions, you need to adopt he paths in the spec-file.
