### ISSUE TITLE
PyInstaller generated executable make all my system files unreadable

### ISSUE THREAD

**Issue by dm02** [pyinstaller/pyinstaller#3776]
I am trying to build an application using [(CTPN)](https://github.com/tianzhi0549/CTPN) which uses caffe framework. I was able to build it successfully and obtained the executable. 

Initially I was able to run the executable successfully too. However, now while running the executable all my system files and folders are getting locked (becomes unreadable) and I am getting permission error.

Is it because something in my system getting corrupted because of the executable? If it is so then how come I was able to run it successfully earlier?

If I run the same executable built in my system in some other system, it is running properly. So what might be causing the change in read permission in my system while running the executable?

**Comment by htgoebel** [comment]
PyInstaller does not change any permissions (outside the temp folder). I have no clue what can cause this, But I'm confident, it is not PyInstaller causing this.

Try freezing a simple program liek this and see:
```
import time
print("Helo")
time.sleep(100) # 1000 seconds
```
