### ISSUE TITLE
Include binary executable in pyinstaller bundle

### ISSUE THREAD

**Issue by djhoese** [pyinstaller/pyinstaller#3780]
I have an application that is using the imageio library to save images and videos. Imageio is a wrapper around other common libraries like pillow (PIL), but also has the option to call "ffmpeg" for some of the fancier stuff. I don't expect pyinstaller to pick up on the use of ffmpeg, but I was hoping that I could add it to the list of binaries in my `.spec` file. After trying that the binary was copied over but the shared libraries that it needed weren't. Is there a utility function that I can use in my spec file to analyze the ffmpeg binary executable and provide me with a list of shared libraries to include?

**Comment by htgoebel** [comment]
PyInstaller is for freezing **Python** allocations, nor for arbitrary programs. You can try adding the ffmpeg programm using `--add-binary`.
