### ISSUE TITLE
Can a module be included in the final package but still be used as if it were imported in a way other than 'import namehere'?

### ISSUE THREAD

**Issue by MostHated** [pyinstaller/pyinstaller#3781]
Hello,
  I don't have an actual issue per se, but I was wondering if/how I might be able to go about this. I have a module that is in a subdirectory but it is imported at runtime with:

    modules = ['modules.module1','modules.module2']
    for modules in modules:
        try:
            load_extension(module)

(it looks like load_extension eventually gets to importlib.import_module() according to my traceback)

If I try to just do `import module.module1` it doesn't work properly. It works fine if I include the modules path in the datas such as this:

    `datas=[('modules/','modules/')],`

but that leaves the folder and code uncompiled and exposed, which I am trying to avoid. Is there a way I can have the code in the modules folder still be called in my main script using `load_modules(module)` but also have it included in the compiled end result as if it were called by using `import modules.module`?

I figured it would not work, but I tried the following anyways just to see.

    module1=import module
    load_extension(module1)

and also: 

    load_extension(import modules.module)

I appreciate any assistance anyone might be able to provide,
Thanks

**Comment by htgoebel** [comment]
> I have a module that is in a subdirectory

This sounds like `modules` is not a proper package or the package is lot located in a directory part of sys.path. Thus `--hidden-imports` and `import module.module1` is not able to find the module. You need to fix your `load_extension()` function

**Comment by MostHated** [comment]
You will have to forgive me, I am either not understanding what I should do or possibly not explaining properly.  [`load_extension` is part of discordpy](https://github.com/Rapptz/discord.py), I just looked through the code for it and this is what constitutes `load_extension()`:

    def load_extension(self, name):
        if name in self.extensions:
            return

        lib = importlib.import_module(name)
        if not hasattr(lib, 'setup'):
            del lib
            del sys.modules[name]
            raise discord.ClientException('extension does not have a setup function')

        lib.setup(self)
        self.extensions[name] = lib

Below is a sample of code from my extension / module that is being loaded via the load_extension() command. 

    @commands.command()
    @commands.is_owner()
    # Test/template for new command
    async def test(self, ctx):
        test = 'test text'
        await ctx.author.send(test)

This only works if I load my module by using `load_extension()`, not by using `import module1`. So I guess my question is more of, can my module1 be included in such a way that it is compiled into the end result, but still able to be called by `load_extension()`? As of now, simply adding the path in datas leaves the end result like this below which ends up just being exposed source.  

    dist/myapplication/modules/module1/__pycache__/
    dist/myapplication/modules/module1/__init__.py
    dist/myapplication/modules/module1/module1.py
