### ISSUE TITLE
Rolling back

### ISSUE THREAD

**Issue by Mradr** [pyinstaller/pyinstaller#3782]
Hi I like to install a older version of pyinstaller as 3.4 seems to be missing or not importing all files into the --onefile option like it use to. I'm not sure what version I was using before - but whatever reason this one doesn't seem to be working. Either way, I like to try and go back and see if that might fix the issue. 

Running python 2.7 and pyinstaller 3.4. No errors in log. Running on Mac 10.14. Missing module that is located in the same folder as the created single file.

**Comment by htgoebel** [comment]
> I like to install a older version of pyinstaller

Just go ahead and fetch the version you want from PyPI.

**Comment by Mradr** [comment]
Sorry what I am asking is : what command can I run to go back and pick a different version? All over the site it only gives pip install pyinstaller.

**Comment by htgoebel** [comment]
Please understand that I'm not going to teach "how to use PyPI and pip". Please have a lokk at the resprective tutorials.
