### ISSUE TITLE
Missing modules

### ISSUE THREAD

**Issue by Mradr** [pyinstaller/pyinstaller#3784]
Hi, running python 2.7 and pyinstaller 3.4. No errors in log when building. Running on Mac 10.14.
When I run the command version it reports back an error that a module is missing, but this module is located inside the same folder as the rest of the files. Maybe something different than I did before - but tried using the newest 3.5 and going back a few versions now and still no luck. What maybe am I doing wrong or is there way to see the log if it's having a hard time building it? Also, I'm sure there will be some growth between when I last build to now - but it seems to have almost double in size when I build now, but yet, still missing modules?

Tried the following: https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly
tips, but still getting the same results. These are not hidden import either - they're at the top of the program being call as import xyz

cd /Users/pc/Desktop/CodeProject & pyinstaller --name CodeProject-Setup --noconsole --icon=app.icns --onefile /Users/pc/Desktop/CodeProject/gui.py --distpath dist

Found this: Looks like it's not importing top level modules? Why? How can I fix that?
missing module named _subprocess - imported by subprocess (conditional), multiprocessing.forking (conditional), multiprocessing.reduction (conditional)
missing module named msvcrt - imported by subprocess (conditional), getpass (delayed, optional), multiprocessing.forking (conditional), click._compat (conditional, optional), click._winconsole (top-level), click._termui_impl (conditional)
missing module named org - imported by pickle (optional)
missing module named 'org.python' - imported by copy (optional), xml.sax (delayed, conditional)
missing module named 'multiprocessing.popen_fork' - imported by /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py (conditional, optional)
missing module named 'multiprocessing.popen_spawn_win32' - imported by /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py (conditional, optional)
missing module named 'multiprocessing.spawn' - imported by /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py (conditional)
missing module named pyimod03_importers - imported by /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/PyInstaller/loader/rthooks/pyi_rth_pkgres.py (top-level)
missing module named 'pkg_resources.extern.pyparsing' - imported by pkg_resources._vendor.packaging.requirements (top-level), pkg_resources._vendor.packaging.markers (top-level)
missing module named netbios - imported by uuid (delayed)
missing module named win32wnet - imported by uuid (delayed)
missing module named ordereddict - imported by pkg_resources._vendor.pyparsing (optional)
missing module named _thread.RLock - imported by _thread (optional), pkg_resources._vendor.pyparsing (optional)
missing module named 'win32com.shell' - imported by pkg_resources._vendor.appdirs (conditional, optional)
missing module named 'com.sun' - imported by pkg_resources._vendor.appdirs (delayed, conditional, optional)
missing module named com - imported by pkg_resources._vendor.appdirs (delayed)
missing module named win32api - imported by pkg_resources._vendor.appdirs (delayed, conditional, optional)
missing module named win32com - imported by pkg_resources._vendor.appdirs (delayed)
missing module named _winreg - imported by mimetypes (optional), urllib (delayed, conditional, optional), winreg (conditional), requests.utils (delayed, conditional, optional), platform (delayed, optional), werkzeug.debug (delayed, optional), selenium.webdriver.firefox.firefox_binary (delayed, optional), pkg_resources._vendor.appdirs (delayed)
missing module named pkg_resources.extern.packaging - imported by pkg_resources.extern (top-level), pkg_resources (top-level)
missing module named pkg_resources.extern.appdirs - imported by pkg_resources.extern (top-level), pkg_resources (top-level)
missing module named importlib.machinery - imported by importlib (conditional), Crypto.Util._raw_api (conditional), pkg_resources (optional)
missing module named 'pkg_resources.extern.six.moves' - imported by pkg_resources (top-level), pkg_resources._vendor.packaging.requirements (top-level)
missing module named pkg_resources.extern.six - imported by pkg_resources.extern (top-level), pkg_resources (top-level)
missing module named _imp - imported by pkg_resources (optional)
missing module named OverrideFrom23 - imported by Carbon.Res (optional)
missing module named rourl2path - imported by urllib (conditional)
missing module named vms_lib - imported by platform (delayed, conditional, optional)
missing module named 'java.lang' - imported by platform (delayed, optional), xml.sax._exceptions (conditional)
missing module named java - imported by platform (delayed)
missing module named winreg.HKEY_LOCAL_MACHINE - imported by winreg (delayed, optional), platform (delayed, optional), selenium.webdriver.firefox.firefox_binary (delayed, optional)
missing module named winreg.CloseKey - imported by winreg (delayed, optional), platform (delayed, optional)
missing module named winreg.QueryValueEx - imported by winreg (delayed, optional), platform (delayed, optional)
missing module named winreg.OpenKeyEx - imported by winreg (delayed, optional), platform (delayed, optional)
missing module named winreg.HKEY_CURRENT_USER - imported by winreg (delayed, optional), selenium.webdriver.firefox.firefox_binary (delayed, optional)
missing module named winreg.QueryValue - imported by winreg (delayed, optional), selenium.webdriver.firefox.firefox_binary (delayed, optional)
missing module named winreg.OpenKey - imported by winreg (delayed, optional), selenium.webdriver.firefox.firefox_binary (delayed, optional)
missing module named win32pipe - imported by platform (delayed, conditional, optional)
missing module named 'collections.abc' - imported by urllib3._collections (optional), requests.compat (conditional), PIL.Image (optional), PIL.TiffImagePlugin (optional), bs4.element (optional), bs4.builder._lxml (optional)
missing module named iconv_codec - imported by bs4.dammit (optional)
missing module named cchardet - imported by bs4.dammit (optional)
missing module named lxml - imported by bs4.builder._lxml (top-level)
missing module named 'html5lib.treebuilders' - imported by bs4.builder._html5lib (optional)
missing module named 'html5lib.constants' - imported by bs4.builder._html5lib (top-level)
missing module named html5lib - imported by bs4.builder._html5lib (top-level)
missing module named 'dbm.ndbm' - imported by future.moves.dbm.ndbm (conditional)
missing module named gdbm - imported by anydbm (top-level), future.moves.dbm.gnu (conditional)
missing module named 'dbm.gnu' - imported by future.moves.dbm.gnu (conditional)
missing module named 'dbm.dumb' - imported by future.moves.dbm.dumb (conditional)
missing module named bsddb3 - imported by bsddb (conditional, optional)
missing module named _pybsddb - imported by bsddb (conditional, optional), bsddb.db (conditional)
missing module named _dummy_threading - imported by dummy_threading (top-level)
missing module named reprlib.recursive_repr - imported by reprlib (conditional), future.backports.misc (conditional)
missing module named _thread.get_ident - imported by _thread (conditional, optional), future.backports.misc (conditional, optional), werkzeug.local (optional)
missing module named _datetime - imported by future.backports.datetime (optional)
missing module named 'six.moves.urllib' - imported by 'six.moves.urllib' (top-level)
**runtime module named six.moves - imported by /Users/pc/Desktop/Newlibimobiledevice/gui.py (top-level)**
missing module named numpy - imported by PIL.ImageFilter (optional)
missing module named olefile - imported by PIL.MicImagePlugin (top-level), PIL.FpxImagePlugin (top-level)
missing module named 'PySide.QtCore' - imported by PIL.ImageQt (conditional, optional)
missing module named 'PyQt4.QtCore' - imported by PIL.ImageQt (conditional, optional)
missing module named 'PyQt5.QtCore' - imported by PIL.ImageQt (conditional, optional)
missing module named pathlib2 - imported by PIL.Image (optional)
missing module named pathlib - imported by PIL.Image (optional)
missing module named cffi - imported by Crypto.Util._raw_api (optional), PIL.Image (optional), PIL.PyAccess (top-level), PIL.ImageTk (optional)
missing module named ipaddress - imported by urllib3.packages.ssl_match_hostname.implementation (optional), urllib3.util.ssl (conditional, optional)
runtime module named urllib3.packages.six.moves - imported by httplib (top-level), urllib3.connectionpool (top-level), urllib3.util.response (top-level), 'urllib3.packages.six.moves.urllib' (top-level), urllib3.response (top-level), urllib3.util.queue (top-level)
missing module named backports - imported by urllib3.packages.ssl_match_hostname (optional)
missing module named "'urllib3.packages.six.moves.urllib'.parse" - imported by urllib3.request (top-level), urllib3.poolmanager (top-level)
missing module named _xmlplus - imported by xml (optional)
missing module named 'urllib.parse' - imported by requests.compat (conditional), werkzeug.http (optional), jinja2._compat (optional)
missing module named 'urllib.request' - imported by requests.compat (conditional), werkzeug.http (optional), werkzeug.test (optional), werkzeug.debug.tbtools (delayed, optional)
missing module named simplejson - imported by requests.compat (optional), itsdangerous (optional)
missing module named blinker - imported by flask.signals (optional)
missing module named greenlet - imported by werkzeug.local (optional)
missing module named 'werkzeug.http.cookiejar' - imported by werkzeug.test (optional)
missing module named colorama - imported by click._compat (conditional, optional)
missing module named 'watchdog.events' - imported by werkzeug._reloader (delayed)
missing module named watchdog - imported by werkzeug._reloader (delayed)
missing module named 'OpenSSL.SSL' - imported by werkzeug.serving (delayed, optional)
missing module named 'werkzeug.http.server' - imported by werkzeug.serving (optional)
missing module named OpenSSL - imported by urllib3.contrib.pyopenssl (top-level), flask.cli (delayed, conditional, optional), werkzeug.serving (delayed, optional)
missing module named termcolor - imported by werkzeug.serving (optional)
missing module named dotenv - imported by flask.cli (optional)
invalid module named jinja2.asyncsupport - imported by jinja2 (delayed, conditional)
missing module named pretty - imported by jinja2.utils (delayed, optional)
missing module named 'jinja2.debugrenderer' - imported by jinja2.debug (delayed)
missing module named pypy - imported by jinja2.debug (optional)
missing module named _xmlrpclib - imported by xmlrpclib (optional)
**missing module named pyicloud - imported by /Users/pc/Desktop/Newlibimobiledevice/gui.py (top-level)**
**missing module named backup_tool - imported by /Users/pc/Desktop/Newlibimobiledevice/gui.py (top-level)**
**missing module named get_mail - imported by /Users/pc/Desktop/Newlibimobiledevice/gui.py (top-level)**
missing module named psutil._psutil_aix - imported by psutil (top-level), psutil._psaix (top-level)
missing module named psutil._psutil_sunos - imported by psutil (top-level), psutil._pssunos (top-level)
missing module named ElementC14N - imported by xml.etree.ElementTree (optional)
missing module named psutil._psutil_bsd - imported by psutil (top-level), psutil._psbsd (top-level)
missing module named enum - imported by psutil._common (conditional), psutil._pslinux (conditional), psutil._pswindows (conditional)
missing module named psutil._psutil_windows - imported by psutil (conditional, optional), psutil._pswindows (top-level)
missing module named _psutil_linux - imported by psutil (conditional)
**missing module named parse_manifest - imported by /Users/pc/Desktop/Newlibimobiledevice/gui.py (top-level)**
**missing module named parse_csv - imported by /Users/pc/Desktop/Newlibimobiledevice/gui.py (top-level)**
missing module named socks - imported by urllib3.contrib.socks (optional)
missing module named cryptography - imported by urllib3.contrib.pyopenssl (top-level), requests (optional)
missing module named 'OpenSSL.crypto' - imported by urllib3.contrib.pyopenssl (delayed)
missing module named 'cryptography.x509' - imported by urllib3.contrib.pyopenssl (delayed, optional)
missing module named 'cryptography.hazmat' - imported by urllib3.contrib.pyopenssl (top-level)
missing module named nt - imported by os (conditional, optional), ntpath (optional)
missing module named SOCKS - imported by ftplib (optional)
missing module named _sha512 - imported by hashlib (delayed, conditional, optional)
missing module named _sha256 - imported by hashlib (delayed, conditional, optional)
missing module named _md5 - imported by hashlib (delayed, conditional, optional)
missing module named _sha - imported by hashlib (delayed, conditional, optional)
missing module named riscosenviron - imported by os (conditional, optional)
missing module named riscospath - imported by os (conditional)
missing module named riscos - imported by os (conditional, optional)
missing module named ce - imported by os (conditional, optional)
missing module named _emx_link - imported by os (conditional)
missing module named os2 - imported by os (conditional, optional)

**Comment by htgoebel** [comment]
Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

BTW: Did you read what's written on top of the "Found this:" file?

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved.
