### ISSUE TITLE
No module named dis3 Raspberry Pi

### ISSUE THREAD

**Issue by mbates14** [pyinstaller/pyinstaller#3789]
Python 2.7 and trying to install pyinstaller. 

I never had issues in the past until now. Clean install of Raspbian Stretch and etc. 

Soon as I try to run pyinstaller --onefile with my script, I get the No Module named dis3 error. 

I have not had this happen in the past. I found a closed topic with a command I tried to run here: 

pip install --force-reinstall --no-binary :all: pyinstaller

But same thing. Any ideas?

**Comment by htgoebel** [comment]
I assume `--force-reinstall` does not check for dependencies. Uninstalling andd re-installing PyInstaller should fix this.

**Comment by JensTimmerman** [comment]
I had the same issue on a clean install of kali linux, pip3 install pyinstaller did not install dis3

**Comment by htgoebel** [comment]
Please provide logs

**Comment by JensTimmerman** [comment]
```
root@kali:~# pyinstaller
bash: pyinstaller: command not found
root@kali:~# pip3 install pyinstaller
Collecting pyinstaller
  Downloading https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 271kB/s 
Collecting altgraph (from pyinstaller)
  Downloading https://files.pythonhosted.org/packages/0a/cc/646187eac4b797069e2e6b736f14cdef85dbe405c9bfc7803ef36e4f62ef/altgraph-0.16.1-py2.py3-none-any.whl
Collecting macholib>=1.8 (from pyinstaller)
  Downloading https://files.pythonhosted.org/packages/41/f1/6d23e1c79d68e41eb592338d90a33af813f98f2b04458aaf0b86908da2d8/macholib-1.11-py2.py3-none-any.whl
Requirement already satisfied: pefile>=2017.8.1 in /usr/lib/python3/dist-packages (from pyinstaller)
Requirement already satisfied: setuptools in /usr/lib/python3/dist-packages (from pyinstaller)
Building wheels for collected packages: pyinstaller
  Running setup.py bdist_wheel for pyinstaller ... done
  Stored in directory: /root/.cache/pip/wheels/09/ee/0a/94ef5d39074625f49e2e9cf97ac30cb7a87e1a7458ed195b8d
Successfully built pyinstaller
Installing collected packages: altgraph, macholib, pyinstaller
Successfully installed altgraph-0.16.1 macholib-1.11 pyinstaller-3.4
root@kali:~# pip install pyinstaller
Collecting pyinstaller
Requirement already satisfied: pefile>=2017.8.1 in /usr/lib/python2.7/dist-packages (from pyinstaller)
Collecting altgraph (from pyinstaller)
  Using cached https://files.pythonhosted.org/packages/0a/cc/646187eac4b797069e2e6b736f14cdef85dbe405c9bfc7803ef36e4f62ef/altgraph-0.16.1-py2.py3-none-any.whl
Collecting macholib>=1.8 (from pyinstaller)
  Using cached https://files.pythonhosted.org/packages/41/f1/6d23e1c79d68e41eb592338d90a33af813f98f2b04458aaf0b86908da2d8/macholib-1.11-py2.py3-none-any.whl
Requirement already satisfied: setuptools in /usr/lib/python2.7/dist-packages (from pyinstaller)
Installing collected packages: altgraph, macholib, pyinstaller
Successfully installed altgraph-0.16.1 macholib-1.11 pyinstaller-3.4
root@kali:~# which pip
/usr/bin/pip
root@kali:~# which pip3
/usr/bin/pip3
root@kali:~# pyinstaller -h
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/__main__.py", line 79, in run
    import PyInstaller.building.build_main
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/building/build_main.py", line 33, in <module>
    from ..depend import bindepend
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/bindepend.py", line 26, in <module>
    from . import dylib, utils
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/depend/utils.py", line 25, in <module>
    from ..lib.modulegraph import util, modulegraph
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/lib/modulegraph/util.py", line 16, in <module>
    from ._compat import StringIO, BytesIO, get_instructions, _READ_MODE
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/lib/modulegraph/_compat.py", line 29, in <module>
    from dis3 import get_instructions
ImportError: No module named dis3
```

**Comment by JensTimmerman** [comment]
installing with pip3 doens't install the dependency

installing with pip for python2 also doesn't install the dependency when asked, because py2.py3-none-any.whl version is found.

**Comment by mbates14** [comment]
I dont use python 3 on any of my stuff, matter of fact, I think I uninstalled python3. All my stuff is Python 2.7

**Comment by htgoebel** [comment]
> installing with pip3 doens't install the dependency

which is absolutely okay,

> installing with pip for python2 also doesn't install the dependency when asked, because py2.py3-none-any.whl version is found.

IC. So this is an issue in our release process. I will need to think about how to solve this. As a workyorund please install using `pip install --no-binary=:all: pyinstaller`.

> pyinstaller has it's shebang set to #!/usr/bin/python and thus alwasy selecting python2 instead of python3 even when installed with pip3.

"pyinstaller" is generated by pip resp. pip3 (from a setup.py entry_point) and pip will set the shebang-line to the python interpreter used by pip resp. pip3 itself.

**Comment by JensTimmerman** [comment]
Aha, pip creates pytinstaller, in that case this seems like this should be sufficient for most use cases, my use of first using pip3 and then pip seems a bit of an edge case, And I was able to quickly correct it by running `pip install dis3`

I gather my run of pip instlal pyinstaller has overwritten the first correctly generated version of pyinstaller which was created by pip3?

**Comment by mattthechef** [comment]
> "IC. So this is an issue in our release process. I will need to think about how to solve this. As a workyorund please install using `pip install --no-binary=:all: pyinstaller`."
> This worked for me. Thanks!
