### ISSUE TITLE
Unable to install Pyinstaller 

### ISSUE THREAD

**Issue by prakashssp** [pyinstaller/pyinstaller#3791]
Hi,..
 I am using Pyhton 2.7.14. I am trying to install Pyinstaller using "pip install pyinstaller" command but I am not able to do it. it is giving the below error.

 Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x069B2290>, 'Connection to pypi.python.org timed out. (connect timeout=15)')': /simple/pyinstaller/
![pyinstaller](https://user-images.githubusercontent.com/43845459/46465508-6e325d00-c7e6-11e8-9a7a-457a962ad1ff.PNG)

**Comment by melvyn2** [comment]
This is a problem with your internet connection, firewall, or PyPI, not us.

**Comment by prakashssp** [comment]
yeah.. it is because of windows firewall only. now I am able to install. 
thank you very much!!...
