### ISSUE TITLE
Please install PyWin32 or pywin32-ctypes.

### ISSUE THREAD

**Issue by tgikal** [pyinstaller/pyinstaller#3793]
I've looked through the issues and seen this issue pop up a few times, but never really seen any resolution.

I have a fresh install of python 3.7 on windows 10.
Did a `pip install pyinstaller`, which succeeded.

typing `pyinstaller --version` returns:
```
PyInstaller cannot check for assembly dependencies.
Please install PyWin32 or pywin32-ctypes.

pip install pypiwin32
```
If I do another `pip install pyinstaller` I get:
```
Requirement already satisfied: pyinstaller in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (3.4)
Requirement already satisfied: setuptools in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller) (39.0.1)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller) (2018.8.8)
Requirement already satisfied: macholib>=1.8 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller) (1.11)
Requirement already satisfied: altgraph in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller) (0.16.1)
Requirement already satisfied: pywin32-ctypes in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from pyinstaller) (0.2.0)
Requirement already satisfied: future in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from pefile>=2017.8.1->pyinstaller) (0.16.0)
```
At this point I'm stuck, it was working with python 3.6 and pyinstaller 3.3.

**Comment by bjones1** [comment]
This is fixed in the development version. Try `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip` and re-open if that fails.

**Comment by tgikal** [comment]
No change,

```
H:\>py -m pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Downloading https://github.com/pyinstaller/pyinstaller/archive/develop.zip
     / 17.5MB ...
  Installing build dependencies ... done
Requirement already satisfied: setuptools in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from PyInstaller==3.5.dev0+0b6f1ec6f) (39.0.1)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from PyInstaller==3.5.dev0+0b6f1ec6f) (2018.8.8)
Requirement already satisfied: macholib>=1.8 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from PyInstaller==3.5.dev0+0b6f1ec6f) (1.11)
Requirement already satisfied: altgraph in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from PyInstaller==3.5.dev0+0b6f1ec6f) (0.16.1)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from PyInstaller==3.5.dev0+0b6f1ec6f) (0.2.0)
Requirement already satisfied: future in c:\users\user\appdata\local\programs\python\python37\lib\site-packages (from pefile>=2017.8.1->PyInstaller==3.5.dev0+0b6f1ec6f) (0.16.0)
Installing collected packages: PyInstaller
  Found existing installation: PyInstaller 3.4
    Uninstalling PyInstaller-3.4:
      Successfully uninstalled PyInstaller-3.4
  Running setup.py install for PyInstaller ... done
Successfully installed PyInstaller-3.5.dev0+0b6f1ec6f

H:\>py -m PyInstaller --version
PyInstaller cannot check for assembly dependencies.
Please install pywin32-ctypes.

pip install pywin32-ctypes
```

**Comment by tgikal** [comment]
I take that back, some change, the error message is now pointing out only pywin32-ctypes.

**Comment by bjones1** [comment]
Strange. I just tested this in a clean venv, Python 3.7 x64, Windows 10, and it worked just fine. Would you re-try in a clean environment?

**Comment by tgikal** [comment]
Yep... Looks like I have something else going on:
```
H:\>C:\Temp\Scripts\python.exe -m pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Downloading https://github.com/pyinstaller/pyinstaller/archive/develop.zip
     | 16.6MB 101kB/s
  Installing build dependencies ... done
Requirement already satisfied: setuptools in c:\temp\lib\site-packages (from PyInstaller==3.5.dev0+0b6f1ec6f) (39.0.1)
Collecting pefile>=2017.8.1 (from PyInstaller==3.5.dev0+0b6f1ec6f)
  Using cached https://files.pythonhosted.org/packages/ed/cc/157f20038a80b6a9988abc06c11a4959be8305a0d33b6d21a134127092d4/pefile-2018.8.8.tar.gz
Collecting macholib>=1.8 (from PyInstaller==3.5.dev0+0b6f1ec6f)
  Using cached https://files.pythonhosted.org/packages/41/f1/6d23e1c79d68e41eb592338d90a33af813f98f2b04458aaf0b86908da2d8/macholib-1.11-py2.py3-none-any.whl
Collecting altgraph (from PyInstaller==3.5.dev0+0b6f1ec6f)
  Using cached https://files.pythonhosted.org/packages/0a/cc/646187eac4b797069e2e6b736f14cdef85dbe405c9bfc7803ef36e4f62ef/altgraph-0.16.1-py2.py3-none-any.whl
Collecting pywin32-ctypes>=0.2.0 (from PyInstaller==3.5.dev0+0b6f1ec6f)
  Using cached https://files.pythonhosted.org/packages/9e/4b/3ab2720f1fa4b4bc924ef1932b842edf10007e4547ea8157b0b9fc78599a/pywin32_ctypes-0.2.0-py2.py3-none-any.whl
Collecting future (from pefile>=2017.8.1->PyInstaller==3.5.dev0+0b6f1ec6f)
  Using cached https://files.pythonhosted.org/packages/00/2b/8d082ddfed935f3608cc61140df6dcbf0edea1bc3ab52fb6c29ae3e81e85/future-0.16.0.tar.gz
Installing collected packages: future, pefile, altgraph, macholib, pywin32-ctypes, PyInstaller
  Running setup.py install for future ... done
  Running setup.py install for pefile ... done
  Running setup.py install for PyInstaller ... done
Successfully installed PyInstaller-3.5.dev0+0b6f1ec6f altgraph-0.16.1 future-0.16.0 macholib-1.11 pefile-2018.8.8 pywin32-ctypes-0.2.0
You are using pip version 10.0.1, however version 18.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

H:\>C:\Temp\Scripts\python.exe -m PyInstaller --version
3.5.dev0+0b6f1ec6f
```
Not sure what to do, uninstall everything, delete the folder, and reinstall?

**Comment by bjones1** [comment]
Probably.

**Comment by tgikal** [comment]
Well thank you for the suggestions, I feel better knowing it can work.

**Comment by bjones1** [comment]
OK, thanks.

**Comment by BrendanSimon** [comment]
The solution of brute force delete of the files did not work for me.

I've tried so many combinations of PyInstaller (release and develop), pywin32, pywin32-ctypes, pypiwin32.

Nothing seems to get rid of this problem.

I have multiple installs of Python.  Python36-32, Python36, Python37-2 and Python37.  None of the pythons are in my PATH.  I have uninstalled PyInstaller from all installations, and reinstalled PyInstaller only for the install I'm interested in (Python36-32).

How, How, How can I get rid of this road-blocking issue ?

**Comment by raffam** [comment]
I also have this problem and I have installed pyinstaller from the git repository as instructed

**Comment by chwba** [comment]
I have the same issue, tried all fixes that were suggested here: https://github.com/pyinstaller/pyinstaller/issues/4212

**Comment by srikrishnansrinivasan** [comment]
Piling on. Seeing this error. Has this been resolved?

**Comment by julianKD** [comment]
Hi everybody,

In my case the solution was to upgrade the cffi package:
`pip install --upgrade cffi`

How to check:
In python try importing e.g.: `from win32ctypes.pywin32.pywintypes import pywin32error`

```
File "C:\Program Files\Python37\lib\site-packages\win32ctypes\pywin32\__init__.py", line 11, in <module>
    from win32ctypes.pywin32 import win32api
  File "C:\Program Files\Python37\lib\site-packages\win32ctypes\pywin32\win32api.py", line 12, in <module>
    from win32ctypes.core import (
  File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\__init__.py", line 36, in load_module
    module = importlib.import_module(self.redirect_module)
  File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\cffi\_common.py", line 12, in <module>
    from ._util import ffi
  File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\cffi\_util.py", line 16, in <module>
    ffi = FFI()
  File "C:\HdM-DT\PythonLibs\python37lib\site-packages\cffi\api.py", line 48, in __init__
    import _cffi_backend as backend
```

So it is not pywin32-ctypes but actually the cffi that is used by pywin32.
After the update of the cffi package, pyinstaller worked.

**Comment by subramanianramajayam** [comment]
i face similar problem after trying to pyinstall an already compiled python scripts,of course from a different python version.
C:\Users\user>python -m PyInstaller --name "ml.stock.py" "C:\Users\user\ml.stock.py"
PyInstaller cannot check for assembly dependencies.
Please install pywin32-ctypes.

pip install pywin32-ctypes

**Comment by THEGOLDENPRO** [comment]
> Hi everybody,
> 
> In my case the solution was to upgrade the cffi package:
> `pip install --upgrade cffi`
> 
> How to check:
> In python try importing e.g.: `from win32ctypes.pywin32.pywintypes import pywin32error`
> 
> ```
> File "C:\Program Files\Python37\lib\site-packages\win32ctypes\pywin32\__init__.py", line 11, in <module>
>     from win32ctypes.pywin32 import win32api
>   File "C:\Program Files\Python37\lib\site-packages\win32ctypes\pywin32\win32api.py", line 12, in <module>
>     from win32ctypes.core import (
>   File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\__init__.py", line 36, in load_module
>     module = importlib.import_module(self.redirect_module)
>   File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\cffi\_common.py", line 12, in <module>
>     from ._util import ffi
>   File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\cffi\_util.py", line 16, in <module>
>     ffi = FFI()
>   File "C:\HdM-DT\PythonLibs\python37lib\site-packages\cffi\api.py", line 48, in __init__
>     import _cffi_backend as backend
> ```
> 
> So it is not pywin32-ctypes but actually the cffi that is used by pywin32.
> After the update of the cffi package, pyinstaller worked.

Holy, this worked for me. Thanks so much.

**Comment by matan-h** [comment]
for me, the only thing that work was reinstall cffi by 
```shell
pip uninstall cffi  -y && pip install cffi  
```

**Comment by tmt313** [comment]
it works the command 'pip install --upgrade cffi'

**Comment by ch1nj33** [comment]
> Hi everybody,
> 
> In my case the solution was to upgrade the cffi package: `pip install --upgrade cffi`
> 
> How to check: In python try importing e.g.: `from win32ctypes.pywin32.pywintypes import pywin32error`
> 
> ```
> File "C:\Program Files\Python37\lib\site-packages\win32ctypes\pywin32\__init__.py", line 11, in <module>
>     from win32ctypes.pywin32 import win32api
>   File "C:\Program Files\Python37\lib\site-packages\win32ctypes\pywin32\win32api.py", line 12, in <module>
>     from win32ctypes.core import (
>   File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\__init__.py", line 36, in load_module
>     module = importlib.import_module(self.redirect_module)
>   File "C:\Program Files\Python37\lib\importlib\__init__.py", line 127, in import_module
>     return _bootstrap._gcd_import(name[level:], package, level)
>   File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\cffi\_common.py", line 12, in <module>
>     from ._util import ffi
>   File "C:\Program Files\Python37\lib\site-packages\win32ctypes\core\cffi\_util.py", line 16, in <module>
>     ffi = FFI()
>   File "C:\HdM-DT\PythonLibs\python37lib\site-packages\cffi\api.py", line 48, in __init__
>     import _cffi_backend as backend
> ```
> 
> So it is not pywin32-ctypes but actually the cffi that is used by pywin32. After the update of the cffi package, pyinstaller worked.

Appreciate it！
