### ISSUE TITLE
Pyinstaller Smartsheet API Not Loading

### ISSUE THREAD

**Issue by sdresche17** [pyinstaller/pyinstaller#3794]
Hello all, I've posted about this in Stack, but no one has been able to help thus far. I have a python file that runs fine in pycharm and on pythonanywhere.

The code requires access to the Smartsheet API and has an import for smartsheet. Unfortunately whenever I run the code, the following error is returned: 
`ERROR:smartsheet.smartsheet:ImportError! Could not load api or model class Sheets`

Current Settings: Python 3.6.5 and tried venv with 3.4 Pyinstaller: tried both developer release and most recent stable release
OS: Windows 7

Things I've tried:
1. Adding hidden imports to the following packages:
    smartsheet, urllib3, requests
using:
`pyinstaller --hidden-import=package_name`
2. Adding files with relevant methods to the spec file using:
`pyi-makespec --paths=directory\smartsheet\smartsheet.py myapp_name.py`
3. I read through the packing and didn't see anything that stood out as wrong in the project
4. updating requests
5. updating setup tools
6. uninstalling enum34 (this solved a previous issue)
Here's the installer printout:

`path>pyinstaller barcode_generator_v2.py
79 INFO: PyInstaller: 3.5.dev0+0b6f1ec6f
80 INFO: Python: 3.6.5
80 INFO: Platform: Windows-7-6.1.7601-SP1
81 INFO: wrote C:\Users\SamuelD\PycharmProjects\WebMetTest\python-read-write-she
et-master\QR Code\barcode_generator_v2.spec
83 INFO: UPX is not available.
85 INFO: Extending PYTHONPATH with paths
['C:\\Users\\SamuelD\\PycharmProjects\\WebMetTest\\python-read-write-sheet-maste
r\\QR '
 'Code',
 'C:\\Users\\SamuelD\\PycharmProjects\\WebMetTest\\python-read-write-sheet-maste
r\\QR '
 'Code']
86 INFO: checking Analysis
87 INFO: Building Analysis because Analysis-00.toc is non existent
87 INFO: Initializing module dependency graph...
92 INFO: Initializing module graph hooks...
95 INFO: Analyzing base_library.zip ...
4700 INFO: running Analysis Analysis-00.toc
4723 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of f
inal executable
  required by c:\users\samueld\appdata\local\continuum\anaconda3\python.exe
5413 INFO: Caching module hooks...
5419 INFO: Analyzing C:\Users\SamuelD\PycharmProjects\WebMetTest\python-read-wri
te-sheet-master\QR Code\barcode_generator_v2.py
6595 INFO: Processing pre-find module path hook   distutils
6847 INFO: Processing pre-find module path hook   site
6848 INFO: site: retargeting to fake-dir 'c:\\users\\samueld\\appdata\\local\\co
ntinuum\\anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
9702 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
15207 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
18645 INFO: Processing pre-safe import module hook   six.moves
21021 INFO: Loading module hooks...
21021 INFO: Loading module hook "hook-certifi.py"...
21023 INFO: Loading module hook "hook-Crypto.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'Crypto.Math'
21093 INFO: Loading module hook "hook-cryptography.py"...
21504 INFO: Loading module hook "hook-distutils.py"...
21506 INFO: Loading module hook "hook-encodings.py"...
21596 INFO: Loading module hook "hook-lib2to3.py"...
21606 INFO: Loading module hook "hook-pkg_resources.py"...
22461 INFO: Processing pre-safe import module hook   win32com
22901 INFO: Loading module hook "hook-pycparser.py"...
23145 INFO: Loading module hook "hook-pydoc.py"...
23146 INFO: Loading module hook "hook-pythoncom.py"...
23769 INFO: Loading module hook "hook-pywintypes.py"...
24383 INFO: Loading module hook "hook-setuptools.py"...
33151 INFO: Loading module hook "hook-sysconfig.py"...
33152 INFO: Loading module hook "hook-win32com.py"...
34062 INFO: Loading module hook "hook-xml.dom.domreg.py"...
34063 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
34063 INFO: Loading module hook "hook-xml.py"...
34064 INFO: Loading module hook "hook-numpy.core.py"...
34307 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
34317 INFO: Loading module hook "hook-numpy.py"...
34319 INFO: Loading module hook "hook-pytest.py"...
35483 INFO: Loading module hook "hook-scipy.py"...
35559 INFO: Looking for ctypes DLLs
35611 INFO: Analyzing run-time hooks ...
35623 INFO: Including run-time hook 'pyi_rth_pkgres.py'
35625 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
35626 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
35646 INFO: Looking for dynamic libraries
36471 WARNING: lib not found: msmpi.dll dependency of c:\users\samueld\appdata\l
ocal\continuum\anaconda3\Library\bin\mkl_blacs_msmpi_ilp64.dll
48728 WARNING: lib not found: pgc14.dll dependency of c:\users\samueld\appdata\l
ocal\continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
48764 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\samueld\appdat
a\local\continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
48803 WARNING: lib not found: pgf90.dll dependency of c:\users\samueld\appdata\l
ocal\continuum\anaconda3\Library\bin\mkl_pgi_thread.dll
48853 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\samueld\appda
ta\local\continuum\anaconda3\Library\bin\mkl_blacs_mpich2_ilp64.dll
49622 WARNING: lib not found: impi.dll dependency of c:\users\samueld\appdata\lo
cal\continuum\anaconda3\Library\bin\mkl_blacs_intelmpi_lp64.dll
51233 WARNING: lib not found: impi.dll dependency of c:\users\samueld\appdata\lo
cal\continuum\anaconda3\Library\bin\mkl_blacs_intelmpi_ilp64.dll
52192 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\samueld\appda
ta\local\continuum\anaconda3\Library\bin\mkl_blacs_mpich2_lp64.dll
52400 WARNING: lib not found: msmpi.dll dependency of c:\users\samueld\appdata\l
ocal\continuum\anaconda3\Library\bin\mkl_blacs_msmpi_lp64.dll
54549 WARNING: lib not found: tbb.dll dependency of c:\users\samueld\appdata\loc
al\continuum\anaconda3\Library\bin\mkl_tbb_thread.dll
56305 INFO: Looking for eggs
56305 INFO: Using Python library c:\users\samueld\appdata\local\continuum\anacon
da3\python36.dll
56305 INFO: Found binding redirects:
[]
56324 INFO: Warnings written to C:\Users\SamuelD\PycharmProjects\WebMetTest\pyth
on-read-write-sheet-master\QR Code\build\barcode_generator_v2\warn-barcode_gener
ator_v2.txt
56610 INFO: Graph cross-reference written to C:\Users\SamuelD\PycharmProjects\We
bMetTest\python-read-write-sheet-master\QR Code\build\barcode_generator_v2\xref-
barcode_generator_v2.html
56775 INFO: checking PYZ
56775 INFO: Building PYZ because PYZ-00.toc is non existent
56775 INFO: Building PYZ (ZlibArchive) C:\Users\SamuelD\PycharmProjects\WebMetTe
st\python-read-write-sheet-master\QR Code\build\barcode_generator_v2\PYZ-00.pyz
59016 INFO: Building PYZ (ZlibArchive) C:\Users\SamuelD\PycharmProjects\WebMetTe
st\python-read-write-sheet-master\QR Code\build\barcode_generator_v2\PYZ-00.pyz
completed successfully.
59067 INFO: checking PKG
59067 INFO: Building PKG because PKG-00.toc is non existent
59067 INFO: Building PKG (CArchive) PKG-00.pkg
59102 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
59105 INFO: Bootloader c:\users\samueld\appdata\local\continuum\anaconda3\lib\si
te-packages\PyInstaller\bootloader\Windows-64bit\run.exe
59105 INFO: checking EXE
59106 INFO: Building EXE because EXE-00.toc is non existent
59106 INFO: Building EXE from EXE-00.toc
59107 INFO: Appending archive to EXE C:\Users\SamuelD\PycharmProjects\WebMetTest
\python-read-write-sheet-master\QR Code\build\barcode_generator_v2\barcode_gener
ator_v2.exe
59170 INFO: Building EXE from EXE-00.toc completed successfully.
59176 INFO: checking COLLECT
59177 INFO: Building COLLECT because COLLECT-00.toc is non existent
59179 INFO: Building COLLECT COLLECT-00.toc
80275 INFO: Building COLLECT COLLECT-00.toc completed successfully.

C:\Users\SamuelD\PycharmProjects\WebMetTest\python-read-write-sheet-master\QR Co
de>python
Python 3.6.5 |Anaconda, Inc.| (default, Mar 29 2018, 13:32:41) [MSC v.1900 64 bi
t (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>`

Also I apologize if this isn't formatted correctly I tried to abide by your guidelines as much as possible, but this is the first time I've ever opened an issue.

**Comment by htgoebel** [comment]
Sadly you are not providing any traceback. Also I don't know what "smartsheet" is. But I assume there are some modules or data files missing. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by sdresche17** [comment]
`
C:\Users\SamuelD\PycharmProjects\Test\python-read-write-sheet-master\QR Co
de\dist\barcode_generator_v2>barcode_generator_v2.exe
Starting ...
Traceback (most recent call last):
  File "barcode_generator_v2.py", line 58, in <module>
AttributeError: 'str' object has no attribute 'list_sheets'
[11224] Failed to execute script barcode_generator_v2
`

I apologize, here's the trace back and I've tried the suggestions in the packaged correctly document I'm now running a clean environment using the onedir flag and noupx flag and as I stated above I've tried adding the hidden imports with its flag and modifying the spec file to point to the python files that are stated as missing in the build/warning file

**Comment by htgoebel** [comment]
This is not a pyinstaller issue, but a bug in your program. Read the error message.
