### ISSUE TITLE
cannot open self exe or archive pkg

### ISSUE THREAD

**Issue by GagarinR** [pyinstaller/pyinstaller#3797]
Pyinstaller 3.4
Windows 10 Home

I created an exe file, on my system with Windows 10 Home its works, but diff Windows 10 Home it doesn't work with this error [3896] cannot open self exe or archive pkg

**Comment by appleUserName** [comment]
Hi, i get the same error after i used vmproject to protect the exe-file. And i donot know ho to fix it. Will you tell me how to fix it???
