### ISSUE TITLE
Cannot spawn new processes after a couple of days -  any ideas?

### ISSUE THREAD

**Issue by nmoehrle** [pyinstaller/pyinstaller#3798]
First of all thanks for your hard work and especially the batteries included approach, getting a running executable was a breeze!

This is a question, not directly an issue since I am not sure whether pyinstaller has an influence in this matter. Further, since I haven't found a reliable way to reproduce the issue feel free to close it immediately, I just hope that you could give me a hint.

I have a one-file app that is unable to spawn new processes after a couple of days on windows.
The error message I get is:
Fatal Python error: Py_Initialize: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'

PyInstaller: 3.3
Python: 3.6.6
Platform: Windows-10-10.0.17134-sp0

I can trigger this exact error message by removing the _base_library.zip_ in the MEI folder while the process is running. After removing the file the app is no longer able to spawn further processes using the multiprocessing module. However, I am unaware of any process that is automatically deleting files in the _%TMP%_ folder after a couple of days. CCleaner or other such tools might do it but I don't think any of those tools were running.

So to my question: is there a way that my python script can alter globals to cause that error?

After looking into cpython and the bootloader I came to the conclusion that if I get to the error (that is
raised in _Py_InitializeEx_Private) the dll must have been successfully loaded meaning that the `mainpath` of the `ARCHIVE_STATUS` must have been pointing to the correct MEI folder and thus the loading of the 'encodings' lib from the _base_library.zip_ should also be successful if it has not been deleted by an external program.

Am I missing something?
Is my assumption that a correct `mainpath` and an existing within that _base_library.zip_ are the only preconditions that are required for the successful initialization of python?
Is it possible that I skewed up my globals in a way that an exiting child process "cleans up" the _base_library.zip_?

The next time it happens I will hopefully be able to analyze the MEI folder to see if something has been messing with it.

Any hints or corrections of my assumptions would be appreciated :-)

Thank you, 
Nils

**Comment by htgoebel** [comment]
Short answer: No idea.

But you should
a) use the most current version of PyInstaller
b) use `--one-dir` mode to avoid having files im %TMP%

**Comment by nmoehrle** [comment]
Although the issue persisted for weeks I have never been able to determine which process is deleting the _base_library.zip_ after roughly seven days. In the end switching to `--one-dir` solved the issue while making the distribution only slightly more complicated.

Thanks you for thinking about it :-)
