### ISSUE TITLE
Pyinstaller bootloader error on termux

### ISSUE THREAD

**Issue by stefan9999991** [pyinstaller/pyinstaller#3800]
Hello,

When I try to install pyinstaller on my termux console with:
`pip2 install pyinstaller`
It gives the following error:
`ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.py`

`    ----------------------------------------
Command "/data/data/com.termux/files/usr/bin/python2 -u -c "import setuptools, tokenize;__file__='/data/data/com.termux/files/usr/tmp/pip-install-PHynu1/pyinstaller/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /data/data/com.termux/files/usr/tmp/pip-record-uIlFfd/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /data/data/com.termux/files/usr/tmp/pip-install-PHynu1/pyinstaller/`

So I downloaded pyinstaller with `pip2 download pyinstaller`

I went into the pyinstaller folder, the bootloader and run this:
`python2 ./waf all`
And it gives me this:
`[10/13] Compiling src/pyi_win32_utils.c                            ../../src/pyi_launch.c:569:23: warning: implicit declaration of function 'nl_langinfo' is invalid in C99 [-Wimplicit-function-declaration]
        loc_codeset = nl_langinfo(CODESET);                                              ^
../../src/pyi_launch.c:569:35: error: use of undeclared identifier 'CODESET'
        loc_codeset = nl_langinfo(CODESET);                                                          ^
1 warning and 1 error generated.                                   
Waf: Leaving directory ``/data/data/com.termux/files/home/PyInstaller-3.4/bootloader/build/debug'
Broken revdeps detected on set([                                           {task 480281846080: strip run_d -> },
        {task 480281845960: cprogram main.c.1.o,pyi_archive.c.1.o,pyi_global.c.1.o,pyi_launch.c.1.o,pyi_main.c.1.o,pyi_path.c.1.o,pyi_python.c.1.o,pyi_python27_compat.c.1.o,pyi_pythonlib.c.1.o,pyi_utils.c.1.o,pyi_win32_utils.c.1.o -> run_d}])`

Please help. I use termux on the oneplus 6

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
