### ISSUE TITLE
apps with OpenCV fails in MacOS  Mojave

### ISSUE THREAD

**Issue by manuelf23** [pyinstaller/pyinstaller#3801]
I have built an application with kivy 1.11, OpenCV 3.3.1 and Pyinstaller 3.4. This application worked perfectly on MacOS Sierra and MacOS high Sierra, however when you upgrade to MacOS Mojave the application opened its interface, but when you asked it to open the laptop's camera or a USB camera that did not work anymore. I went back to compiling the application in Mojave with Pyinstaller, but the error persisted and I tried again in another Mac with High Sierra and the application returned to work perfectly, when I tried again in MacOS Mojave, I used the Debug flag and I got an error of "Segmentation fault 11". Also I tried compiling the applications with versions of OpenCV from version 3.1 to the one that is in development but the error persists in the same way tried with Pyinstaller the version that is in development but the error persists.

MacBook Pro retina 13 inch 2015 
MacOS Mojave 10.14
Python version is 3.6.5
Requirement.txt is:
absl-py==0.4.0
adal==1.1.0
altgraph==0.16.1
asn1crypto==0.24.0
astor==0.7.1
astroid==2.0
autopep8==1.3.5
cachetools==2.1.0
certifi==2018.8.24
cffi==1.11.5
chardet==3.0.4
click==6.7
cryptography==2.3.1
Cython==0.26.1
docutils==0.14
future==0.16.0
gast==0.2.0
google-api-core==1.4.1
google-auth==1.5.1
google-cloud-core==0.28.1
google-cloud-storage==1.13.0
google-resumable-media==0.3.1
googleapis-common-protos==1.5.3
grpcio==1.14.1
idna==2.7
isort==4.3.4
itsdangerous==0.24
Jinja2==2.10
Kivy==1.10.1
Kivy-Garden==0.1.4
kubernetes==7.0.0
lazy-object-proxy==1.3.1
macholib==1.10
Markdown==2.6.11
MarkupSafe==1.0
mccabe==0.6.1
netifaces==0.10.7
numpy==1.14.5
oauthlib==2.1.0
opencv-python==3.4.3.18
pbr==4.1.0
pefile==2018.8.8
pexpect==4.6.0
Pillow==5.2.0
protobuf==3.6.1
psutil==5.4.7
ptyprocess==0.6.0
pyasn1==0.4.4
pyasn1-modules==0.2.2
pycodestyle==2.4.0
pycparser==2.19
pyenchant==2.0.0
Pygments==2.2.0
PyInstaller==3.5.dev0+0b6f1ec6f
PyJWT==1.6.4
pylint==2.0.0
python-dateutil==2.7.3
python-vlc==3.0.102
pytz==2018.5
PyYAML==3.13
requests==2.19.1
requests-oauthlib==1.0.0
rsa==4.0
six==1.11.0
socketIO-client-nexus==0.7.6
stevedore==1.28.0
termcolor==1.1.0
typed-ast==1.1.0
urllib3==1.23
virtualenv==16.0.0
virtualenv-clone==0.3.0
virtualenvwrapper==4.8.2
websocket-client==0.51.0
Werkzeug==0.14.1
wrapt==1.10.11

The easiest way to reproduce this error is making a Kivy screen with a button that turn on the built in camera, compile it in MacOS Mojave and you will see that the button is not going to work.

**Comment by manuelf23** [comment]
I found the problem and it is that Mojave has a new feature that stop the access to the camera and microphone for apps, and the only apps than can access to those components need to be with permission so as terminal app has permission this is the reason why running the app exe through the terminal  works. To see the apps that have permission you can go to "Preferences -> Security & Privacy -> Privacy -> Camera.
I have not found a solution to grant permission to my app yet, so if anyone knows how to do it I appreciate it.

**Comment by bjones1** [comment]
Thanks for the helpful debug. Since this isn't (directly) a PyInstaller issue, I'm closing it. However, if you do find a fix, please post as a recipe since that's an important part of the packaging process.

**Comment by anirudhbagri** [comment]
@manuelf23, Did you find a way to resole this error?
I am using pyautoui to enter file path in `finder` (macos), but the app immediately crashes... probably due to no access to `file and folder` and no `accessibility` permission. 
How can I give these permissions to the app pyinstaller generates at /dist?
