### ISSUE TITLE
PyInstaller does not seem to work with packages that use pbr

### ISSUE THREAD

**Issue by andy-maier** [pyinstaller/pyinstaller#3805]
One of the users of our [pywbem project](https://github.com/pywbem/pywbem) tries to use PyInstaller on Ubuntu to create an executable from their Python script using our pywbem package. See issue https://github.com/pywbem/pywbem/issues/1410.

This fails for him when transporting the resulting executable onto another Ubuntu system, with:

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "pywbem/__init__.py", line 47, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "pywbem/_listener.py", line 141, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 396, in load_module
  File "pywbem/_version.py", line 46, in <module>
  File "pbr/version.py", line 457, in release_string
  File "pbr/version.py", line 462, in semantic_version
  File "pbr/version.py", line 449, in _get_version_from_pkg_resources
  File "pbr/packaging.py", line 812, in get_version
Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name pywbem was given, but was not able to be found.
[19695] Failed to execute script name.py
```

pywbem uses the [pbr package](https://pypi.org/project/pbr/) to determine its own package version.

pbr uses several possible sources to determine the version of the project using it, including:

* the latest tag on the checked out branch of a git repo (useful when developing the project),
* the metadata of the installed package (the normal case when using a released version of the project),
* a PKG-INFO or METADATA file in the current directory (a not so optimal fallback).

Note that it is possible that I got the order wrong in which these options are attempted by pbr, and maybe I missed additional options, but that does not matter for this issue.

The somewhat cryptic exception message shown above means that pbr was unable to determine the version of the pywbem package, after having exhausted its options listed above for determining the package version.

When pywbem is installed using pip into some target Python environment (of any kind, e.g. virtual or system or user), the package metadata is used by pbr to determine the package version.

I have the following questions:

1. Does PyInstaller put the Python package metadata files into its generated executable?

2. Can you recommend a way to make PyInstaller work with packages that use pbr for determining its package version?

3. I have tried to debug this, but have not yet found a way to make PyInstaller reveal the exact set of files it puts into the generated executable. The PyInstaller option `--debug noarchive` advertizes to produce a subtree of python source files that are put into the executable, but I could not get it to actually do that. The option seems to have no effect at all. How do I get this option to work?

More details:

The environment in which I tried to reproduce the issue of our user that had the original issue, is:
* MacOS HighSierra
* Python 2.7.15 in a virtualenv
* Some Python package versions:
  * pyinstaller 3.4
  * pip 18.1
  * pbr 4.3.0
  * setuptools 40.4.3
  * wheel 0.32.1

In that environment, I can reproduce the exception our user had.

Let me know if you need more information.
I could provide a small project using pbr that demonstrates the issue, if that is helpful.

I have looked at the following other issues reporting the same symptom, with no success:
* https://bugs.launchpad.net/python-keystoneclient/+bug/1397554
* https://stackoverflow.com/questions/46369902/how-to-package-tensorflow-with-pyinstaller-on-macosx
* https://github.com/pyinstaller/pyinstaller/issues/2868

**Comment by bjones1** [comment]
Thanks for a very helpful bug report. To answer your questions:

1. Not be default. A [hook](https://pyinstaller.readthedocs.io/en/stable/hooks.html) like the following named `hook-pbr.py` should work:

``` Python
from PyInstaller.utils.hooks import copy_metadata

copy_metadata('pbr')
```

To use this, run PyInstaller with the [--additional-hooks-dir](https://pyinstaller.readthedocs.io/en/stable/usage.html) option.

2. Include this hook.

3. Use [--debug all](https://www.ftdichip.com/Drivers/VCP.htm).

Does `import pbr` produce this failure? Or does it take a more complicated script?

**Comment by andy-maier** [comment]
It takes a script that imports pywbem to reproduce this.
Pywbem then imports pbr to let it determine its own version.

I'll check out your answers soon. Thanks!!

**Comment by DevOpsJon** [comment]
@andy-maier  Did you get this working? I'm having a similar issue with pbr.

**Comment by Legorooj** [comment]
Closing. This requires a hook to fix; please write one. See above link (https://github.com/pyinstaller/pyinstaller/issues/3805#issuecomment-429884433) for details and doc links.
