### ISSUE TITLE
documentation request for GUI applications that won't start

### ISSUE THREAD

**Issue by moonshoes87** [pyinstaller/pyinstaller#3811]
I have a suggestion for a section to add to the "If Things Go Wrong" Guide.

I use Pyinstaller about once every few months, so I am not a super user by any means.  I maintain a GUI wxPython application, which I periodically recompile for OSX and Windows using Pyinstaller.  However, a situation I commonly encounter is that my GUI application simply doesn't boot up, with no error message.  It has taken me a while figuring out what to do and how to get useful output to assess the problem.

With OSX, I've learned that I can run `./dist/my_gui` to get an actual error message.  Now I am trying to get the same information on Windows, so far without success.  Using the --debug flag hasn't done anything, and without a runtime error message it is very hard to figure out if there are actually any missing imports.

So, what would be helpful to me (and I imagine to others), would be a checklist for what to do with a windowed app that just doesn't start at all.  In general I think the "When Things Go Wrong" guide is great, it just isn't super clear where to start if you're not getting any error output at all.

Thanks for making this tool!

**Comment by bjones1** [comment]
Good point. I assume that building without the `--noconsole` / `--windowed` [flags](https://pyinstaller.readthedocs.io/en/stable/usage.html#windows-and-mac-os-x-specific-options) provides the output you're looking for?

**Comment by moonshoes87** [comment]
Actually, not on windows.  I tried making a minimal script with a simple problem (missing an import).  

Running `python wx_minimal.py` I get the error:
    
    Traceback (most recent call last):
      File "wx_minimal.py", line 9, in <module>
        class simpleapp_wx(wx.Frame):
    NameError: name 'wx' is not defined


I then used Pyinstaller to package wx_minimal into wxGUI (with --windowed) and wxCONSOLE (without --windowed).  When I open wxGUI, I get this uninformative failure message:

<img width="293" alt="screen shot 2018-10-18 at 10 58 53 am" src="https://user-images.githubusercontent.com/1836578/47174278-05a6ae00-d2c5-11e8-92eb-778e822d020b.png">

When I run wxCONSOLE, the console pops open but nothing happens:

<img width="987" alt="screen shot 2018-10-18 at 11 01 30 am" src="https://user-images.githubusercontent.com/1836578/47174360-3e468780-d2c5-11e8-91c4-6418e1f2c96f.png">


It's possible I'm missing something straightforward, but having a documented protocol for this situation would help!

.spec files generated with:  `pyi-makespec --onefile --name=wxCONSOLE wx_minimal.py`

[wxGUI.spec.txt](https://github.com/pyinstaller/pyinstaller/files/2493091/wxGUI.spec.txt)
[wxCONSOLE.spec.txt](https://github.com/pyinstaller/pyinstaller/files/2493092/wxCONSOLE.spec.txt)
[wx_minimal.py.txt](https://github.com/pyinstaller/pyinstaller/files/2493093/wx_minimal.py.txt)

**Comment by bjones1** [comment]
Do you see any output if you run wxCONSOLE from a Windows command prompt?

**Comment by moonshoes87** [comment]
Ah, yes.  In that case I do get the NameError.  That's useful.  It took about 2 minutes, though, so I initially thought it was just hung.

**Comment by bjones1** [comment]
Would you mind providing some suggestions or changes to the [PyInstaller manual](https://github.com/pyinstaller/pyinstaller/blob/develop/doc/when-things-go-wrong.rst)?

**Comment by htgoebel** [comment]
```
#!/usr/bin/env python
# -*- coding: iso-8859-1 -*-

import wx.lib.buttons as buttons
import sys
import os
import pandas

class simpleapp_wx(wx.Frame):
    def __init__(self, parent, wx_id, title):
```

Your programm is missing the `wx` import. Try this:
```
>>> import wx.lib.buttons as buttons
/usr/lib64/python2.7/site-packages/wx-3.0-gtk2/wx/_core.py:16629: UserWarning: wxPython/wxWidgets release number mismatch
  warnings.warn("wxPython/wxWidgets release number mismatch")
>>> wx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'wx' is not defined
```

**Comment by moonshoes87** [comment]
The missing import was intentional -- I was creating a bug that would result in the bundled app being built, but then failing to start without an error message.

**Comment by moonshoes87** [comment]
Yes, I understand your point.  It's just difficult to come up with a *minimal* example that works when run in Python but fails in Pyinstaller, but with my complex GUI it happens all the time.  At any rate, I've made a pull request with a suggestion for the additional documentation that would have saved me some time.
