### ISSUE TITLE
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp36-win_amd64.pyd': Failed to load dynlib/dll 

### ISSUE THREAD

**Issue by aaonline** [pyinstaller/pyinstaller#3812]
I am writing a basic engine to parse PDF files, and use pdfminer as:

from pdfminer.pdfpage import PDFPage

But when I try building an exe using PyInstaller 3.3.1 on Windows 10 (Home), inside a virtualenv in Anaconda, I get following error:-
```
OSError: Cannot load native module 'Crypto.Cipher._raw_ecb': Trying '_raw_ecb.cp36-win_amd64.pyd': Failed to load dynlib/dll 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI222122\\Crypto\\Util\\..\\Cipher\\_raw_ecb.cp36-win_amd64.pyd'. Most probably this dynlib/dll was not found when the application was frozen., Trying '_raw_ecb.pyd': Failed to load dynlib/dll 'C:\\Users\\User\\AppData\\Local\\Temp\\_MEI222122\\Crypto\\Util\\..\\Cipher\\_raw_ecb.pyd'. Most probably this dynlib/dll was not found when the application was frozen.
[18920] Failed to execute script
```
And if I do not include the import above, exe is built success. 

I went to the site packages and it looks like

site-packages\pycryptodome-3.6.3-py3.6-win-amd64.egg\Crypto\Util

Please any suggestions here.

**Comment by htgoebel** [comment]
> Most probably this dynlib/dll was not found when the application was frozen

This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by htgoebel** [comment]
No reaction for several months, assume this is solved.
