### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'objcopy': 'objcopy'

### ISSUE THREAD

**Issue by eduardoHoefel** [pyinstaller/pyinstaller#3815]
I was able to successfully build my package on Windows and another Linux machine.
Now, I was trying to build it from a Linux VM and got this message:

sudo pyinstaller -y src/main.py 
30 INFO: PyInstaller: 3.5.dev0+ea8e55dec
30 INFO: Python: 3.7.0
31 INFO: Platform: Linux-4.14.67-1-MANJARO-x86_64-with-arch-Manjaro-Linux
33 INFO: wrote /media/sf_workspace/JAEL/main.spec
35 INFO: UPX is not available.
39 INFO: Extending PYTHONPATH with paths
['/media/sf_workspace/JAEL/src', '/media/sf_workspace/JAEL']
39 INFO: checking Analysis
112 INFO: checking PYZ
138 INFO: checking PKG
144 INFO: Building because /usr/lib/python3.7/site-packages/PyInstaller/loader/pyimod01_os_path.pyc changed
144 INFO: Building PKG (CArchive) PKG-00.pkg
218 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
221 INFO: Bootloader /usr/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit/run
221 INFO: checking EXE
229 INFO: Building because name changed
229 INFO: Building EXE from EXE-00.toc
248 INFO: Appending archive to ELF section in EXE /media/sf_workspace/JAEL/build/main/main
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5.dev0+ea8e55dec', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3.7/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3.7/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 29, in <module>
  File "/usr/lib/python3.7/site-packages/PyInstaller/building/api.py", line 433, in __init__
    self.__postinit__()
  File "/usr/lib/python3.7/site-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3.7/site-packages/PyInstaller/building/api.py", line 587, in assemble
    self.name)
  File "/usr/lib/python3.7/site-packages/PyInstaller/compat.py", line 509, in exec_command_all
    stdout=subprocess.PIPE, stderr=subprocess.PIPE, **kwargs)
  File "/usr/lib/python3.7/subprocess.py", line 756, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.7/subprocess.py", line 1499, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'objcopy': 'objcopy'

**Comment by htgoebel** [comment]
Please read the requirements section in the manual and install the required binaries provided by your Linux distribution.

**Comment by cdgriffith** [comment]
Link to requirements page: https://pyinstaller.readthedocs.io/en/stable/requirements.html#gnu-linux

There is currently nothing on the [installation](https://pythonhosted.org/PyInstaller/installation.html) or [quickstart](https://www.pyinstaller.org/) sections that mention additional Linux requirements, and this is currently top result for this issue so wanted to add easy link.

**Comment by handflucht** [comment]
Additional information: _glibc_ might be called _libc6_. Both of the following worked for me:
* apt-get install -y binutils libc6
* apt-get install -y binutils libc-bin

**Comment by jgstew** [comment]
Also, "FileNotFoundError: [Errno 2] No such file or directory: 'objcopy': 'objcopy'" isn't a great error message for missing dependencies / requirements.

**Comment by gowhari** [comment]
It's written in the [requirements](https://pyinstaller.readthedocs.io/en/stable/requirements.html#gnu-linux) list that it needs `objcopy`. On ubuntu you can install it by:

`sudo apt install binutils`
