### ISSUE TITLE
Tkinter button text does not appear on Apple's Mojave OS

### ISSUE THREAD

**Issue by mhgoldfarb** [pyinstaller/pyinstaller#3818]
When creating a bundle or one file with pyinstaller (whether packaing on older Mac OS or on Mojave) my Tkinter button text does not seem to be appearing. Labels, dropdowns, etc. work fine on Mojave and the buttons are working as expected on all other Mac OS except the new Mojave. Button functionality does still work, just the text does not work. When I run the program before packaging with pyinstaller, the button text works fine on Mojave (and all other Mac OS of course)

<img width="487" alt="screen shot 2018-10-21 at 11 20 42 pm" src="https://user-images.githubusercontent.com/22826414/47276807-f440f880-d587-11e8-95b8-28bae9dd5d27.png">
<img width="1189" alt="screen shot 2018-10-21 at 11 19 26 pm" src="https://user-images.githubusercontent.com/22826414/47276808-f4d98f00-d587-11e8-88e8-5192137425d5.png">

**Comment by melvyn2** [comment]
You've made two almost identical issues; please close one of them. You also haven't provided necessary information.

**Comment by bjones1** [comment]
@melvyn2 is right. Closing this one.

**Comment by mhgoldfarb** [comment]
My apologies, first time creating an issue and after submitting and refreshing page I was being redirected to 404 page so i thought there was an issue posting. Also, one the issue that is still open, please let me know what other information I may need to add!
