### ISSUE TITLE
pyinstaller cannot work along with ibm-cos-sdk-python?

### ISSUE THREAD

**Issue by thetime1102** [pyinstaller/pyinstaller#3822]
I'm using ibm-cos-sdk-python, in behavior it's use boto3. (https://github.com/IBM/ibm-cos-sdk-python)
Does there anyone use pyinstaller to generate execution file for ibm-cos-sdk-python?

**Comment by htgoebel** [comment]
Why not ask your commertion support contact at ibm?

**Comment by thetime1102** [comment]
> upport contact at ibm?

because, i found boto3's problem was fixed in https://github.com/pyinstaller/pyinstaller/pull/1639
but not working when i use pyinstaller to generate execution file from ibm-cos-sdk.

**Comment by htgoebel** [comment]
Obviously ibm_botocore\docs\bcdoc\restdoc.py tries to import a package which was not bundled. Please have look at hook-botocore and adopt it to your needs. All further questions should IMHO go to IBM, since they deliver a custom version of botocore.
