### ISSUE TITLE
Byte-code encryption support in v3.4? 

### ISSUE THREAD

**Issue by mofahead** [pyinstaller/pyinstaller#3826]
Hi,

First, thanks so much to all contributors to this project. 

I know that byte-code encryption (--key option) is not supported going forward, what about latest stable (v3.4)?

If not, should the [docs](https://pyinstaller.readthedocs.io/en/v3.4/usage.html  ) be updated to reflect that?

Thanks again!

**Comment by htgoebel** [comment]
Duplicate of #3531

**Comment by htgoebel** [comment]
Regarding the doc-update: Plese provide a pull-request.
