### ISSUE TITLE
Appveyor test_zope_interface tests failing

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#3831]
@htgoebel, these failures originated with 6f9a9126c754101b737667b1cbecf967f39cdb51 per https://ci.appveyor.com/project/matysek/pyinstaller/builds/19649436. It only fails on Windows Python 2.7. Would you take a look?

**Comment by htgoebel** [comment]
Oha! Looks like I mixed things up when bringing in modulegraph 0.17. I only looked for travis-ci when merging that. Very curious, why this fails on windows.

**Comment by htgoebel** [comment]
My analysis was to short: It is setuptools causing the different code in the.pth file. The different versions for wheel are only showing there are different environment versions used to build the package.

Reopening, since we need to fix this in modulgraph.

**Comment by htgoebel** [comment]
Fixed. Basically it was a stupid typo introduced by myself when wrapping long lines in b7ed5db. It remained undetected since there was no test-case for. I added respective test-cases in 4ac89c6d262d6.

**Comment by bjones1** [comment]
Thanks again! Looks good.
