### ISSUE TITLE
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by msw0126** [pyinstaller/pyinstaller#3833]
Here's what my code file says:
"""
# -*- coding:utf-8 -*-
import datetime
import pandas as pd

# content_1
now_time = datetime.datetime.now()
with open('first.txt', 'a+') as f1:
    f1.write(str(now_time) + "\n")

# content_2
df = pd.read_csv("F:/learn/jingsai/o2o/data/ccf_offline_stage1_test_revised.csv")
df.to_csv("./test.csv")
"""
If you comment out content_2, use the following command（pyinstaller -F demo_pg.py）It can be successfully packed normally.Otherwise, an error will appear.The following：

$  /f/tools/Anaconda3/Scripts/pyinstaller -F demo_pg.py
84 INFO: PyInstaller: 3.5.dev0+0ffa574bf
84 INFO: Python: 3.6.2
85 INFO: Platform: Windows-7-6.1.7601-SP1
85 INFO: wrote F:\learn\jingsai\o2o\demo_pg.spec
89 INFO: UPX is not available.
90 INFO: Extending PYTHONPATH with paths
['F:\\learn\\jingsai\\o2o', 'F:\\learn\\jingsai\\o2o']
91 INFO: checking Analysis
92 INFO: Building because F:\learn\jingsai\o2o\demo_pg.py changed
93 INFO: Initializing module dependency graph...
99 INFO: Initializing module graph hooks...
101 INFO: Analyzing base_library.zip ...
5577 INFO: running Analysis Analysis-00.toc
5603 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by F:\tools\Anaconda3\python.exe
6503 INFO: Caching module hooks...
6512 INFO: Analyzing F:\learn\jingsai\o2o\demo_pg.py
6815 INFO: Processing pre-find module path hook   distutils
7880 INFO: Processing pre-safe import module hook   six.moves
17418 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
18398 INFO: Processing pre-find module path hook   site
18399 INFO: site: retargeting to fake-dir 'F:\\tools\\Anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
27170 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
90615 INFO: Loading module hooks...
90615 INFO: Loading module hook "hook-botocore.py"...
90773 INFO: Loading module hook "hook-certifi.py"...
90774 INFO: Loading module hook "hook-cryptography.py"...
91172 INFO: Loading module hook "hook-distutils.py"...
91173 INFO: Loading module hook "hook-encodings.py"...
91286 INFO: Loading module hook "hook-IPython.py"...
91303 INFO: Excluding import 'PyQt5'
91312 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
91312 INFO:   Removing import of PyQt5.QtCore from module IPython.external.qt_loaders
91312 INFO:   Removing import of PyQt5.QtWidgets from module IPython.external.qt_loaders
91312 INFO:   Removing import of PyQt5.QtGui from module IPython.external.qt_loaders
91312 INFO:   Removing import of PyQt5.QtSvg from module IPython.external.qt_loaders
91313 INFO: Excluding import 'gtk'
91323 INFO: Excluding import 'matplotlib'
91331 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
91331 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
91331 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
91331 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
91331 INFO:   Removing import of matplotlib.pylab from module IPython.core.pylabtools
91333 INFO: Excluding import 'PySide'
91341 INFO:   Removing import of PySide from module IPython.external.qt_loaders
91342 INFO: Excluding import 'PyQt4'
91351 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
91352 INFO: Excluding import 'tkinter'
91359 INFO:   Removing import of tkinter from module IPython.lib.clipboard
91362 INFO: Loading module hook "hook-jinja2.py"...
91384 INFO: Loading module hook "hook-jsonschema.py"...
91387 INFO: Loading module hook "hook-lib2to3.py"...
91391 INFO: Loading module hook "hook-lxml.etree.py"...
91392 INFO: Loading module hook "hook-matplotlib.backends.py"...
92097 INFO:   Matplotlib backend "GTK": ignored
    Gtk* backend requires pygtk to be installed.
92626 INFO:   Matplotlib backend "GTKAgg": ignored
    Gtk* backend requires pygtk to be installed.
92983 INFO:   Matplotlib backend "GTKCairo": ignored
    No module named 'gtk'
93516 INFO:   Matplotlib backend "GTK3Agg": ignored
    The Gtk3 backend requires PyGObject or pgi
93869 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
94396 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
F:\tools\Anaconda3\lib\site-packages\IPython\kernel\__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated. You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
95720 INFO:   Matplotlib backend "nbAgg": ignored
    cannot import name 'constants'
Fatal Python error: PyThreadState_Get: no current thread
96227 INFO:   Matplotlib backend "Qt4Agg": added
96583 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
Fatal Python error: PyThreadState_Get: no current thread
97088 INFO:   Matplotlib backend "Qt5Agg": added
97444 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
97990 INFO:   Matplotlib backend "TkAgg": added
98362 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
99251 INFO:   Matplotlib backend "WebAgg": added
99785 INFO:   Matplotlib backend "WX": ignored
    Matplotlib backend_wx and backend_wxagg require wxPython>=2.9
100147 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
100502 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
101036 INFO:   Matplotlib backend "agg": added
101409 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
101768 INFO:   Matplotlib backend "gdk": ignored
    No module named 'gobject'
102303 INFO:   Matplotlib backend "pdf": added
102905 INFO:   Matplotlib backend "pgf": added
103435 INFO:   Matplotlib backend "ps": added
103968 INFO:   Matplotlib backend "svg": added
104496 INFO:   Matplotlib backend "template": added
104979 INFO: Loading module hook "hook-matplotlib.py"...
105370 INFO: Loading module hook "hook-numpy.core.py"...
105469 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
105477 INFO: Loading module hook "hook-numpy.py"...
105478 INFO: Loading module hook "hook-openpyxl.py"...
105486 INFO: Loading module hook "hook-pandas.py"...
106550 INFO: Loading module hook "hook-PIL.Image.py"...
106946 INFO: Loading module hook "hook-PIL.py"...
106951 INFO: Import to be excluded not found: 'FixTk'
106951 INFO: Excluding import 'PyQt5'
106956 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
106956 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
106957 INFO: Excluding import 'PySide'
106961 INFO:   Removing import of PySide from module PIL.ImageQt
106962 INFO: Excluding import 'PyQt4'
106967 INFO:   Removing import of PyQt4 from module PIL.ImageQt
106968 INFO: Excluding import 'tkinter'
106974 INFO:   Removing import of tkinter from module PIL.ImageTk
106975 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
106979 INFO: Import to be excluded not found: 'FixTk'
106979 INFO: Excluding import 'tkinter'
106983 INFO: Loading module hook "hook-pkg_resources.py"...
108026 INFO: Processing pre-safe import module hook   win32com
108556 INFO: Loading module hook "hook-pycparser.py"...
108915 INFO: Loading module hook "hook-pydoc.py"...
108916 INFO: Loading module hook "hook-pygments.py"...
110856 INFO: Loading module hook "hook-PyQt5.py"...
Fatal Python error: PyThreadState_Get: no current thread
110948 WARNING: Cannot read QLibraryInfo output: raised Expecting value: line 1 column 1 (char 0) when decoding:

Traceback (most recent call last):
  File "F:\tools\Anaconda3\Scripts\pyinstaller-script.py", line 11, in <module>
    load_entry_point('PyInstaller==3.5.dev0+0ffa574bf', 'console_scripts', 'pyinstaller')()
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
    exec(text, spec_namespace)
  File "<string>", line 17, in <module>
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
    self.__postinit__()
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
    module_hook.post_graph()
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
    self._load_hook_module()
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
    self.hook_module_name, self.hook_filename)
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
    return mod_loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 823, in load_module
  File "<frozen importlib._bootstrap_external>", line 682, in load_module
  File "<frozen importlib._bootstrap>", line 251, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 675, in _load
  File "<frozen importlib._bootstrap>", line 655, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\hooks\hook-PyQt5.py", line 23, in <module>
    collect_system_data_files(pyqt5_library_info.location['PrefixPath'],
  File "F:\tools\Anaconda3\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 70, in __getattr__
    qli = json.loads(json_str)
  File "F:\tools\Anaconda3\Lib\json\__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "F:\tools\Anaconda3\Lib\json\decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "F:\tools\Anaconda3\Lib\json\decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by wangyarui** [comment]
+1.....
