### ISSUE TITLE
WARNING: Hidden import "PyQt5.sip" not found!

### ISSUE THREAD

**Issue by JimmyTheNerd** [pyinstaller/pyinstaller#3837]
Hi there,

first I'd like to thank you for the great project that you're building in your spare time.

**What is the exact problem?**
The application is running well on the command line, but imports fail while packaging. 

Full command line log of `pyinstaller app.py`:
https://gist.github.com/JimmyTheNerd/9ccbe06341dfd74642cdff8b6635e0a6

*For some reason `pyinstaller app.py --log-level DEBUG > out.txt` writes an empty `out.txt`.*

**First error**: 
> WARNING: Hidden import "PyQt5.sip" not found!

I found **many related posts** on GitHub and SO and followed the suggestions, nothing worked so far. I added the library as a **hidden import** in the [*.spec-file](https://pythonhosted.org/PyInstaller/spec-files.html) and got the **following error**:
> NameError: name 'PyQt5' is not defined

I checked `my_virtual_environment/lib/python3.5/site-packages/PyQt5/*`, but couldn't find the file `PyQt5.sip`, which I was hoping to link in a [hook](https://pythonhosted.org/PyInstaller/hooks.html).

**I'm not importing PyQt5** anywhere in my app, it's probably `pywebview`.

PyInstaller worked like a charm before I used 3rd-party dependencies, but I did a **fresh installation** anyways.

**Software versions you are using.**

- Python 3.5.2
- PyInstaller 3.5.dev0+g04bb630 (latest)

Output of `pip list`:
```
Package       Version          
------------- -----------------
altgraph      0.16.1           
Babel         2.6.0            
Click         7.0              
Flask         0.12.1           
Flask-Babel   0.12.2           
future        0.17.0           
itsdangerous  0.24             
Jinja2        2.9.6            
macholib      1.11             
MarkupSafe    1.0              
pefile        2018.8.8         
pip           18.1             
pkg-resources 0.0.0            
psutil        5.4.7            
PyInstaller   3.5.dev0+g04bb630
pynput        1.4              
PyQt5         5.8.2            
python-xlib   0.23             
pytz          2018.6           
pywebview     2.2.1            
setuptools    40.5.0           
sip           4.19.8           
six           1.11.0           
WebUI         0.2.0            
Werkzeug      0.12.1 
```
**What platform and which version you are working on?**
- Ubuntu 16.04. LTS

Thanks in advance!

**Comment by bjones1** [comment]
This is a warning, not an error -- you're OK. The way PyQt5 was packaged between 5.8 and the current release (5.11) changed, and the warning (as I remember) reflects the facts that SIP is now packaged as a part of PyQt5 in current installs. However, old installs will still work, albeit with a warning.

**Comment by JimmyTheNerd** [comment]
@bjones1 Thank you! I was too focused on these warnings that I missed the actual error, which is now fixed. :-)

**Comment by santosh1432007** [comment]
@bjones1 Hello Brayan. Thanks a lot for the great work you are doing with PyInstaller. I have a similar problem. I followed the tutorial and the guide to create executable for Python. I am using Python 3.5, PyQt5 and PyInstaller 4. PyInstaller is not able to build executable properly. There is an error:
**from PyQt5.Qsci import QsciScintilla
ImportError: No module named 'PyQt5.Qsci'
[1016] Failed to execute script Interface.** 

I tried to hidenimport=PyQt5.Qsc as well and it didn't help. When it building the script, I found that 
**796243 INFO: Analyzing hidden import 'PyQt5.Qsc'
796280 ERROR: Hidden import 'PyQt5.Qsc' not found.**
Could you please tell me how to bypass this problem and build the executable for windows. 
PyIntaller works fine without the PyQt5.Qsc import and it is working. I need to fix this issue. I tried a lot, couldn't find a way to solve it. 
Thanks a lot.

Best Regards
Santosh

**Comment by Busby09** [comment]
Hi, having problems with pyinstaller every time I create the EXE file get the error filed to execute script I have tried all the possible solutions found online  adding environment variable ect. but nothing works 

Windows 10 
Python 3.1
pyQT5 

I do get warnings on various missing modules but no errors
