### ISSUE TITLE
Gtk Icons on Target System not Found

### ISSUE THREAD

**Issue by ole-de** [pyinstaller/pyinstaller#3840]
PyInstaller 3.4
Python 3
Packeting OS: Ubuntu-18
Target OS: Gentoo

Maybe I am getting something wrong, but I think the way PyInstaller behaves is not the way it should be. Anyway, thanks for this great thing first of all!

I am packeting a Python3 Gtk3 app for Linux. Works fine so far (not counting some trouble here...). Packeting is done in a minimal Ubuntu-18 Docker container for the sake of better portability. When I then try to execute the one-file binary on my host system, I get the following kind of error:

(main:25204): Gtk-WARNING **: 17:52:42.591: Error loading theme icon 'document-new' for stock: Icon 'document-new' not present in theme breeze

None of the icons in my app is displayed. The above is an example only.

The cause is, my target system has the theme set to breeze (KDE theme) which is not available on the packeting container. But it IS available on the target system and should - from my understanding - be used. I cannot packetize each and every theme some guy is using on his system when running my app.

The reason seems to be, the whole theme/icon trees are packetized with the generated binary and Gtk somehow instructed to use (only) these file trees.

I am not doubting SOME useful scenario for this behavior, but I think usually the theme/icons should be taken from the target, i.e. executing system.

Thanks for reading/commenting.

**Comment by danyeaw** [comment]
@ole-de Gtk apps should work with the latest version of PyInstaller, and it packages the Gtk theme with the app. Is this still an issue, or can this be closed?

**Comment by ole-de** [comment]
Hi Dan,
this is a rather old issue and I do not have the system where I encountered the problem in reach. I think I somehow worked around the issue. Let's close this.
Thanks anyway!
