### ISSUE TITLE
Error when running the script in an older linux system. bash: ./filename : Cannot execute binary file.

### ISSUE THREAD

**Issue by vineethsai** [pyinstaller/pyinstaller#3846]
Hi,
The program works like a charm when I run it on Terminal on multiple different Macs but when I run it on an older Linux system, it gives the following
bash: ./filename : Cannot execute binary file.

There were no other problems. What do you think is the problem and are there any solutions?

**Comment by pavi2410** [comment]
You need to make the file executable by running this command:

`chmod +x <your file>`

**Comment by htgoebel** [comment]
Executables build on OS X can not be run on Linux.

**Comment by vineethsai** [comment]
> You need to make the file executable by running this command:
> 
> ```
> chmod +x <your file>
> ```
I have, of course, done that.

**Comment by vineethsai** [comment]
> Executables build on OS X can not be run on Linux.

Will building the executable on Linux, run the code on Linux?

**Comment by htgoebel** [comment]
> Will building the executable on Linux, run the code on Linux?

Exactly. Of course only if your application is platform independent.
