### ISSUE TITLE
Cannot find existing PyQt5 plugin directories

### ISSUE THREAD

**Issue by germayneng** [pyinstaller/pyinstaller#3852]
> 196 INFO: PyInstaller: 3.4
> 196 INFO: Python: 3.6.7
> 196 INFO: Platform: Windows-10-10.0.17134-SP0
> 196 INFO: wrote C:\Users\Germayne\Desktop\data_science\testing\script.spec
> 200 INFO: UPX is not available.
> 207 INFO: Extending PYTHONPATH with paths
> ['C:\\Users\\Germayne\\Desktop\\data_science\\testing',
>  'C:\\Users\\Germayne\\Desktop\\data_science\\testing']
> 212 INFO: checking Analysis
> 219 INFO: Building Analysis because Analysis-00.toc is non existent
> 224 INFO: Initializing module dependency graph...
> 240 INFO: Initializing module graph hooks...
> 247 INFO: Analyzing base_library.zip ...
> 5172 INFO: running Analysis Analysis-00.toc
> 5192 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
>   required by c:\users\germayne\anaconda3\envs\shire\python.exe
> 5892 INFO: Caching module hooks...
> 5900 INFO: Analyzing C:\Users\Germayne\Desktop\data_science\testing\script.py
> 6176 INFO: Processing pre-find module path hook   distutils
> 6948 INFO: Processing pre-safe import module hook   six.moves
> 12209 INFO: Processing pre-find module path hook   site
> 12213 INFO: site: retargeting to fake-dir 'c:\\users\\germayne\\anaconda3\\envs\\shire\\lib\\site-packages\\PyInstaller\\fake-modules'
> 17231 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
> 32340 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
> 80511 INFO: Loading module hooks...
> 80516 INFO: Loading module hook "hook-babel.py"...
> 80707 INFO: Loading module hook "hook-certifi.py"...
> 80711 INFO: Loading module hook "hook-cryptography.py"...
> 82644 INFO: Loading module hook "hook-distutils.py"...
> 82648 INFO: Loading module hook "hook-docutils.py"...
> 86068 INFO: Loading module hook "hook-encodings.py"...
> 86280 INFO: Loading module hook "hook-IPython.py"...
> 86324 INFO: Excluding import 'gtk'
> 86332 INFO: Excluding import 'PyQt5'
> 86340 INFO:   Removing import of PyQt5.QtSvg from module IPython.external.qt_loaders
> 86344 INFO:   Removing import of PyQt5 from module IPython.external.qt_loaders
> 86344 INFO:   Removing import of PyQt5.QtGui from module IPython.external.qt_loaders
> 86356 INFO:   Removing import of PyQt5.QtCore from module IPython.external.qt_loaders
> 86360 INFO:   Removing import of PyQt5.QtWidgets from module IPython.external.qt_loaders
> 86360 INFO: Excluding import 'PyQt4'
> 86384 INFO:   Removing import of PyQt4 from module IPython.external.qt_loaders
> 86384 INFO: Excluding import 'tkinter'
> 86392 INFO:   Removing import of tkinter from module IPython.lib.clipboard
> 86404 INFO: Excluding import 'PySide'
> 86420 INFO:   Removing import of PySide from module IPython.external.qt_loaders
> 86428 INFO: Excluding import 'matplotlib'
> 86440 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
> 86444 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
> 86452 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
> 86464 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
> 86484 INFO: Loading module hook "hook-jedi.py"...
> 86512 INFO: Loading module hook "hook-jinja2.py"...
> 86540 INFO: Loading module hook "hook-jsonschema.py"...
> 86548 INFO: Loading module hook "hook-lib2to3.py"...
> 86560 INFO: Loading module hook "hook-matplotlib.backends.py"...
> 95180 INFO:   Matplotlib backend "GTK3Agg": ignored
>     cairo backend requires that cairocffi or pycairo is installed
> 95904 INFO:   Matplotlib backend "GTK3Cairo": ignored
>     cairo backend requires that cairocffi or pycairo is installed
> 98116 INFO:   Matplotlib backend "MacOSX": ignored
>     cannot import name '_macosx'
> 100299 INFO:   Matplotlib backend "nbAgg": added
> 106315 INFO:   Matplotlib backend "Qt4Agg": added
> 107039 INFO:   Matplotlib backend "Qt4Cairo": ignored
>     cairo backend requires that cairocffi or pycairo is installed
> 108055 INFO:   Matplotlib backend "Qt5Agg": added
> 108787 INFO:   Matplotlib backend "Qt5Cairo": ignored
>     cairo backend requires that cairocffi or pycairo is installed
> 111403 INFO:   Matplotlib backend "TkAgg": added
> 112339 INFO:   Matplotlib backend "TkCairo": ignored
>     cairo backend requires that cairocffi or pycairo is installed
> 113496 INFO:   Matplotlib backend "WebAgg": added
> 114392 INFO:   Matplotlib backend "WX": ignored
>     No module named 'wx'
> 115120 INFO:   Matplotlib backend "WXAgg": ignored
>     No module named 'wx'
> 115852 INFO:   Matplotlib backend "WXCairo": ignored
>     No module named 'wx'
> 116588 INFO:   Matplotlib backend "agg": added
> 117320 INFO:   Matplotlib backend "cairo": ignored
>     cairo backend requires that cairocffi or pycairo is installed
> 118492 INFO:   Matplotlib backend "pdf": added
> 119392 INFO:   Matplotlib backend "pgf": added
> 120124 INFO:   Matplotlib backend "ps": added
> 120872 INFO:   Matplotlib backend "svg": added
> 121768 INFO:   Matplotlib backend "template": added
> 122288 INFO: Loading module hook "hook-matplotlib.py"...
> 122972 INFO: Loading module hook "hook-numpy.core.py"...
> 123476 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
> 123484 INFO: Loading module hook "hook-numpy.py"...
> 123488 INFO: Loading module hook "hook-pandas.py"...
> 137024 INFO: Loading module hook "hook-pkg_resources.py"...
> 138020 INFO: Processing pre-safe import module hook   win32com
> 138520 INFO: Loading module hook "hook-pycparser.py"...
> 138792 INFO: Loading module hook "hook-pydoc.py"...
> 138796 INFO: Loading module hook "hook-pygments.py"...
> 140860 INFO: Loading module hook "hook-PyQt5.py"...
> 141093 WARNING: Hidden import "PyQt5.sip" not found!
> 141093 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
> 141208 WARNING: Unable to find Qt5 translations C:/Miniconda3/conda-bld/qt_1535195524645/_h_env/Library/translations\qtbase_*.qm. These translations were not packaged.
> 141208 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
> Traceback (most recent call last):
>   File "c:\users\germayne\anaconda3\envs\shire\lib\runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "c:\users\germayne\anaconda3\envs\shire\lib\runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\Germayne\Anaconda3\envs\shire\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\__main__.py", line 111, in run
>     run_build(pyi_config, spec_file, **vars(args))
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\building\build_main.py", line 838, in main
>     build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\building\build_main.py", line 784, in build
>     exec(text, spec_namespace)
>   File "<string>", line 17, in <module>
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\building\build_main.py", line 241, in __init__
>     self.__postinit__()
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
>     self.assemble()
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\building\build_main.py", line 500, in assemble
>     module_hook.post_graph()
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\building\imphook.py", line 410, in post_graph
>     self._load_hook_module()
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\building\imphook.py", line 377, in _load_hook_module
>     self.hook_module_name, self.hook_filename)
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\compat.py", line 736, in importlib_load_source
>     return mod_loader.load_module()
>   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
>   File "<frozen importlib._bootstrap_external>", line 823, in load_module
>   File "<frozen importlib._bootstrap_external>", line 682, in load_module
>   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
>   File "<frozen importlib._bootstrap>", line 684, in _load
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\hooks\hook-PyQt5.QtGui.py", line 11, in <module>
>     hiddenimports, binaries, datas = add_qt5_dependencies(__file__)
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 514, in add_qt5_dependencies
>     more_binaries = qt_plugins_binaries(plugin, namespace=namespace)
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 132, in qt_plugins_binaries
>     pdir = qt_plugins_dir(namespace=namespace)
>   File "c:\users\germayne\anaconda3\envs\shire\lib\site-packages\PyInstaller\utils\hooks\qt.py", line 117, in qt_plugins_dir
>     """.format(namespace, ", ".join(paths)))
> Exception:
>             Cannot find existing PyQt5 plugin directories
>             Paths checked: C:/Miniconda3/conda-bld/qt_1535195524645/_h_env/Library/plugins

Just a simple print script to test but its not working. I have seen a similar thread but am not able to resolve. So I need to reinstall pyinstaller somehow?

**Comment by germayneng** [comment]
ok fixed this by doing this: 

> pip install PyQt5

**Comment by tchugh** [comment]
Add `--exclude-module PyQt5` if your solution is not using PyQT5. Also helps in reducing the final size.

**Comment by FlorianFranzen** [comment]
You are running pyinstaller inside a conda environment and your python executable seems to uses ipython which again requires PyQy5. Conda's PyQt5 however seems to be be build improperly and as a result pyinstaller is unable to locate the plugin directory. This can also been seen in the additional warnings:
```
WARNING: Hidden import "PyQt5.sip" not found!
WARNING: Unable to find Qt5 translations C:/qt64/qt_1544645195969/_h_env/Library/translations\qtbase_*.qm. These translations were not packaged.
```

That is why installing PyPi PyQt5 fixes the issue.

**Comment by sofdit76139** [comment]
What finally did it for me was to copy the files from the Anaconda directory to the Python one: C:\Users\<user>\AppData\Local\Python\Python39\site-packages\PyQt5 and C:\Users\<user>\AppData\Roaming\Python\Python39\site-packages\PyQt5

I am not sure which copy it was that fixed it, but afterwards I could start Anaconda from cmd and it showed up on the Start menu.
