### ISSUE TITLE
Pyinstaller: problem with subprocess.check_output() in --noconsole mode

### ISSUE THREAD

**Issue by sbmdkl** [pyinstaller/pyinstaller#3861]
I am using subprocess.check_output() in my program.
The program runs well in console but gives error in noconsole.
```shell
pyinstaller  --onefile --noconsole  fetch.py
```

How can use subprocess.check_output() in noconsole???

**Comment by htgoebel** [comment]
Please see https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess
