### ISSUE TITLE
Hook for lightgbm

### ISSUE THREAD

**Issue by germayneng** [pyinstaller/pyinstaller#3863]
Hi,

I have created a script that creates a machine learning model using microsoft's LGBM. However, after successful compiling via pyinstaller, when i run the exe, it seems that the lgbm module cannot be found. I tried using a new environment and installed everything. (i can run the .py file just fine) 

This is the error: 

> Traceback (most recent call last):
>   File "script.py", line 18, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "c:\users\germayne\anaconda3\envs\xxxx\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\lightgbm\__init__.py", line 8, in <module>
>   File "<frozen importlib._bootstrap>", line 971, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "c:\users\germayne\anaconda3\envs\xxxx\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\lightgbm\basic.py", line 34, in <module>
>   File "site-packages\lightgbm\basic.py", line 26, in _load_lib
>   File "site-packages\lightgbm\libpath.py", line 37, in find_lib_path
> Exception: Cannot find lightgbm library file in following paths:
> C:\Users\Germayne\AppData\Local\Temp\_MEI208762\lightgbm\lib_lightgbm.dll
> C:\Users\Germayne\AppData\Local\Temp\lib_lightgbm.dll
> C:\Users\Germayne\AppData\Local\Temp\_MEI208762\lightgbm\compile\lib_lightgbm.dll
> C:\Users\Germayne\AppData\Local\Temp\_MEI208762\compile\lib_lightgbm.dll
> C:\Users\Germayne\AppData\Local\Temp\lib\lib_lightgbm.dll
> C:\Users\Germayne\AppData\Local\Temp\_MEI208762\compile\Release\lib_lightgbm.dll
> C:\Users\Germayne\AppData\Local\Temp\_MEI208762\compile\windows\x64\DLL\lib_lightgbm.dll
> C:\Users\Germayne\AppData\Local\Temp\Release\lib_lightgbm.dll
> C:\Users\Germayne\AppData\Local\Temp\windows\x64\DLL\lib_lightgbm.dll
> [20576] Failed to execute script script

**Comment by germayneng** [comment]
i added 

pathex=['C:\\Users\\Germayne\\Desktop\\data_science\\xxxxx_tool','C:\\Users\\Germayne\\Anaconda3\\Lib\\site-packages']


but it still does not work and seems to be looking for lib_lightgbm.dll. (this is in the site-packages/lightgbm folder )

**Comment by germayneng** [comment]
Ok so what i did was this: 

when building the exe, either define it in the cmd or from spec file: 

pyinstaller -F --add-data lib_lightgbm.dll;. script.py

After building, make sure the dll is in the same folder as the exe. 

reference: https://stackoverflow.com/questions/38791685/how-do-i-include-dll-file-in-executable-using-pyinstaller


Is there anyway to build the dll inside the exe? or dll are suppose to be complementing?

**Comment by htgoebel** [comment]
We would appreciate if you'd submit a pull-request for a hook for this. The respective module is `lightgbm.libpath` - according to your traceback. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by germayneng** [comment]
@htgoebel  Thanks for answer, so basically to summary, there is no solution at this point in time for this right? 

I will submit the pull request in the meantime.

**Comment by germayneng** [comment]
I tried hidden import for lightgbm but i get the error of infinite recursion or something. 
https://stackoverflow.com/questions/27947639/how-to-properly-create-a-pyinstaller-hook-or-maybe-hidden-import

**Comment by alianoroozi** [comment]
@germayneng Did you find a solution to this problem?

**Comment by germayneng** [comment]
unfortunately no. Did you have the same error on your side?

**Comment by alianoroozi** [comment]
Yes. I tried adding lib_lightgbm.dll using the option :
`--add-data lib_lightgbm.dll;\compile`
This resolves the error on the machine that lightgbm is installed, but on other machines, it gives the following error:
`Traceback (most recent call last):
  File "pro2.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\mahsa\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\lightgbm\__init__.py", line 8, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\mahsa\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\lightgbm\basic.py", line 34, in <module>
  File "site-packages\lightgbm\basic.py", line 29, in _load_lib
  File "ctypes\__init__.py", line 426, in LoadLibrary
  File "site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\...\\AppData\\Local\\Temp\\_MEI7562\\lightgbm\\../compile\\lib_lightgbm.dll'. Most probably this dynlib/dll was not found when the application was frozen.`

**Comment by gongxijun** [comment]
sombody had solved this?

**Comment by ansonuser** [comment]
I revised local script of lightgbm\libpath.py by adding "."  in searching path list which located line 26 and the script location is C:\ProgramData\Anaconda3\Lib\site-packages\lightgbm in Window10s.

**Comment by Legorooj** [comment]
Closing; there is a finished PR waiting to be merged: #4634
