### ISSUE TITLE
I found a little error in the file 'hook-PyQt5.QtQml.py'

### ISSUE THREAD

**Issue by LittleWhite-Carry** [pyinstaller/pyinstaller#3864]
Hi.

Sorry, I don't know how to use the Pull request. @bjones1 

There is a small problem in this file 'hook-PyQt5.QtQml.py'.

I think it should be like this
```Python
if qmldir:
    logger.warning('Unable to find Qt5 QML files. QML files not packaged.')
```

not like this:
```Python
if not qmldir:
    logger.warning('Unable to find Qt5 QML files. QML files not packaged.')
```

This `not` should be removed

This causes the file to not be properly packaged when the QML path does not exist.

Then when I modified this, the package finally appeared:
```
Security-Alert: try to store file outside of dist-directory. Aborting. 'C:\\anaconda3\\lib\\site-packages\\PyQt5\\QtWebEngineProcess.exe'
```

I don't know how this affects, but my program works fine.

This is some information about my environment.
···
Python:3.6
pyinstaller:3.4
PyQt:3.5
···

This is the original question #3229 

Thanks

**Comment by bjones1** [comment]
Thanks for the note. However, the logic seems correct to me: `if qmldir` means that Qt claims to have QML files and provides a valid path to them. However, the directory may not actually exist. I would instead propose the following:

``` Python

if not os.exists(qmldir):
    logger.warning('Unable to find Qt5 QML files. QML files not packaged.')
```

Would you mind testing this?

In terms of the other error, I think tracking this down isn't worth the effort -- your version of PyQt5 is old and you're using Anaconda, which sometimes causes problems.

**Comment by bjones1** [comment]
Thanks for your report and checking the fix. I'm running this through the standard test suite, then will include these changes.

**Comment by bjones1** [comment]
@amoh-godwin, I don't understand your question. First, are you asking about this issue, or your PR? If you're asking about this issue, are you wanting to add support for PyQt 3.5 on Anaconda? If so, why -- it's easy to use current PyQt5 under Anaconda, and this is fully supported.

**Comment by bjones1** [comment]
The location of the QML directory comes from Qt (`QLibraryInfo`) and should be correct, regardless of which install (Anaconda's PyQt5 packages vs. PyPI's package).

**Comment by amoh-godwin** [comment]
ok
