### ISSUE TITLE
Can't close console on frozen Windows gui app

### ISSUE THREAD

**Issue by RyanHope** [pyinstaller/pyinstaller#3865]
I am trying to make a hybrid console/gui app. If no command line arguments are passed I would like to close the console when the gui starts. However, I cant get the window to close, it always stays open. I can close the console window manually without it killing my application now that I call FreeConsole(), but it seems like something is still hanging around preventing that window from closing. What am I missing? Below is a minimal example the demonstrates the issue. 

Python 3.7.0 (default, Aug 14 2018, 19:12:50) [MSC v.1900 32 bit (Intel)] :: Anaconda, Inc. on win32
PyInstaller: 3.4
Platform: Windows-7-6.1.7601-SP1 

```
import sys
import os
import wx
import win32console as con

class MyFrame(wx.Frame):
    def __init__(self):
        wx.Frame.__init__(self, None, size=(350, 200))
        panel = wx.Panel(self)
        sizer = wx.BoxSizer(wx.VERTICAL)
        panel.SetSizer(sizer)
        panel.Layout()
        self.Center()
        self.Show()

def main():
    sys.__stdin__.close()
    sys.__stdout__.close()
    sys.__stderr__.close()
    os.close(0)
    os.close(1)
    os.close(2)
    con.FreeConsole()
    app = wx.App(redirect=False)
    f = MyFrame()
    app.MainLoop()

if __name__ == '__main__':
    main()
```

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by RyanHope** [comment]
OP updated with min-example and system info.

**Comment by RyanHope** [comment]
This post  below suggested closing the standard handles but that is not helping:
https://social.msdn.microsoft.com/Forums/vstudio/en-US/c8b63202-257d-4339-935f-b47c8042834e/windows-api-freeconsole-not-closing-a-console-before-an-hwnd-is-made?forum=windowsgeneraldevelopmentissues

**Comment by htgoebel** [comment]
Information required still  ot provided, stale since long, closing.
