### ISSUE TITLE
pyinstaller in centos4.3 report “Floating Point Exception”

### ISSUE THREAD

**Issue by chi2liu** [pyinstaller/pyinstaller#3878]
in centos4.3，pyinstaller can package the python scritps， but when execute，it report the error “ Floating Point Exception”， what is wrong with that？pyinstaller do not support centos4.3？

hello.py
`print ‘hello， world’`

![image](https://user-images.githubusercontent.com/19861628/48767812-83aa0a80-ecf2-11e8-8a51-45be2bf375b2.png)

![image](https://user-images.githubusercontent.com/19861628/48768048-1f3b7b00-ecf3-11e8-8f83-d909473e0b5c.png)

gdb debug:
`Starting program: /home/work/hello
Program received signal SIGFPE, Arithmetic exception.
0x0000003f0ae07487 in do_lookup_x () from /lib64/ld-linux-x86-64.so.2`

**Comment by htgoebel** [comment]
PyInstaller's bootloader does not use  floating point anywhere AFSIK. Please try to track this down. Since you are using `gsb`, I assume you are able to find the exact place there this error occurs.
