### ISSUE TITLE
Need help on packing backports.os

### ISSUE THREAD

**Issue by jaimemachado** [pyinstaller/pyinstaller#3879]
Im trying to execute a very simple prof of concept for a larger project.
The python scripts is:
```
#!/usr/bin/env python

from PyQt4 import QtGui
import sys
import os
import backports.os
from fs.osfs import OSFS


class MainViewUI(QtGui.QMainWindow):

    def __init__(self, parent=None):
        super(MainViewUI, self).__init__(parent)


class MainApplication(QtGui.QApplication):
    def __init__(self, name):
        super(MainApplication, self).__init__(name)


def test(args):
    app = MainApplication(["kyber"])
    app.setStyle(QtGui.QStyleFactory.create("mac"))

    mainView = MainViewUI()

    fp = OSFS(os.path.abspath(os.path.dirname(args[1])), "utf-8")

    with fp.open(unicode(str(os.path.split(args[1])[-1]), "utf-8")) as filefp:
        print filefp.read()

    mainView.show()
    app.exec_()


if __name__ == "__main__":

    test(sys.argv)
```

Executed:
pyinstaller -D main.py

When trying to execute the package generated i get an error:

Traceback (most recent call last):
  File "main.py", line 6, in <module>
    import backports.os
ImportError: No module named backports.os

Can anyone help me with this?

**Comment by jayvdb** [comment]
Have you tried to do it in a virtualenv?  It could be a problem with the outer python environment, as `backports` is often a fictitious (broken) module when it comes from a distro rather than from pip.

**Comment by bwoodsend** [comment]
I'm considering this no longer relevant since we long ago dropped support for any Python version which required a backport to `os`.
