### ISSUE TITLE
i386 unsupported architecture after uploading to AppStore

### ISSUE THREAD

**Issue by VladLimbean** [pyinstaller/pyinstaller#3882]
**Context:**

I am trying to put an electron app on the App Store. The app features a web frontend and a python backend. Nothing fancy so far.

The backend however features a separate server written in python. This server is a standalone application.

The electron app bundles the main app together with the python standalone server.

**The problem:**

When building the server as an executable I use pyinstaller on a python 3.5 development environment. Upon uploading to the AppStore I receive the following error:

```
1 package(s) were not uploaded because they had problems:
/var/folders/39/3v0phzy173s3qxkbxzvcpd5c0000gn/T/82AB662A-44C8-41E9-A213-8BF672F3DF10/1443777291.itmsp - Error Messages:
    ERROR ITMS-90240: "Unsupported Architectures. Your executable contained the following disallowed architectures:
 '[i386 (in com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/AppKit._AppKit.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/AppKit._inlines.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/CoreFoundation._CoreFoundation.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/CoreFoundation._inlines.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/Foundation._Foundation.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/Foundation._inlines.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/PIL._imaging.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/PIL._imagingtk.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/PIL._webp.so, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/libjpeg.9.dylib, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/libopenjp2.2.1.0.dylib, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/libtiff.5.dylib, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/libwebp.7.dylib, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/libwebpdemux.2.dylib, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/libwebpmux.3.dylib, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/libz.1.2.11.dylib, 
com.ShapeRobotics.FableMac.pkg/Payload/Fable.app/Contents/Resources/app/app/app/server/objc._objc.so)]'. 
New apps submitted to the Mac App Store must support 64-bit starting January 2018, and Mac app updates and existing apps must support 64-bit starting June 2018."

```
We tried building the server using this:

`pyinstaller server.spec --distpath ../app/app --noconfirm`

It didn't work.

Another incantation I use to bundle the python server trying to force 64bit is:

`arch -64 python ~/anaconda3/envs/shape/bin/pyinstaller server.spec -s --osx-bundle-identifier com.ShapeRobotics.FableMac --distpath ../app/app --noconfirm"`

**Why I'm sure it's the server:**

I was successful in signing the app and getting it uploaded to the AppStore w/o the server packed in.

After packing in the server the 'i386' architecture error popped up.

Consequently my efforts so far have been focused to eliminate any shred of 32bit code in the server.

I assume that in order to do this I must properly configure the .spec file used by pyInstaller.

**Does this make sense?**

**Is there a way to configure the spec file to force exclusive 64bit on anything bundled inside?**

**Is there some clear cut way to make the AppStore upload not vomit the 'i386' error?**

Thank you!

**Comment by arunbuduri** [comment]
@VladLimbean were you able to solve this? We just ran into the same issue.

**Comment by VladLimbean** [comment]
@arunbuduri no fix in sight yet. Do let me know if you figure something out please.

**Comment by htgoebel** [comment]
What AppSstore are you talking about? Assuming everybody knows is a bit ignorant.

> I assume that in order to do this I must properly configure the .spec file used by pyInstaller.

You need to make sure the python and all dynlibs used are 64-bit. Maybe installing a fresh anaconda environment under `arch -64` solves the issue. Check the .toc-files in the `build`-directory to learn where the dynlibs are copied from

> Is there a way to configure the spec file to force exclusive 64bit on anything bundled inside?

No.

> Is there some clear cut way to make the AppStore upload not vomit the 'i386' error?

Please ask the app-store support.
