### ISSUE TITLE
matplotlib script does not work with Pyside2 but it does with Pyqt5

### ISSUE THREAD

**Issue by imbunche** [pyinstaller/pyinstaller#3883]
Hello,

I´m attaching a minimal example of a matplotlib + Pyside2 script that does not work with Pyinstaller
It´s interesting that just changing PySide2 to PyQt5 then it just wotks.

I don´t know if I should contact Pyside2 developers as well?
The script is a shorter version of a matplotlib example.

import sys
import time

import numpy as np

#from matplotlib.backends.qt_compat import QtCore, QtWidgets, is_pyqt5
#from PyQt5 import QtCore, QtWidgets
from PySide2 import QtCore, QtWidgets

from matplotlib.backends.backend_qt5agg import (
        FigureCanvas, NavigationToolbar2QT as NavigationToolbar)
from matplotlib.figure import Figure

class ApplicationWindow(QtWidgets.QMainWindow):
    def __init__(self):
        super().__init__()
        self._main = QtWidgets.QWidget()
        self.setCentralWidget(self._main)
        layout = QtWidgets.QVBoxLayout(self._main)

        static_canvas = FigureCanvas(Figure(figsize=(5, 3)))
        print("canvas", static_canvas, isinstance(static_canvas, QtWidgets.QWidget))
        layout.addWidget(static_canvas)
        #self.addToolBar(NavigationToolbar(static_canvas, self))

        self._static_ax = static_canvas.figure.subplots()
        t = np.linspace(0, 10, 501)
        self._static_ax.plot(t, np.tan(t), ".")

if __name__ == "__main__":
    qapp = QtWidgets.QApplication(sys.argv)
    app = ApplicationWindow()
    app.show()
    qapp.exec_()

**Comment by imbunche** [comment]
I forgot to add, this is under Windows 10. All packages including pyinstaller come from anaconda.

**Comment by bjones1** [comment]
PySide2 support in PyInstaller needs work. Please submit a PR!

**Comment by fj11** [comment]
The same issue that I encountered. Do you have plan to fix it?
