### ISSUE TITLE
Build: Need Mac retina HiDPI support for Pyqt5 GUI app bundled.

### ISSUE THREAD

**Issue by Cody-Chen** [pyinstaller/pyinstaller#3884]
I make a pyqt5 gui for my mac retina. But the .app running on low dpi mode. But the exec file is fine.

Check the 'info.plist' file: 

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>CFBundleDisplayName</key>
	<string>test</string>
	<key>CFBundleExecutable</key>
	<string>MacOS/test</string>
	<key>CFBundleIconFile</key>
	<string>icon-windowed.icns</string>
	<key>CFBundleIdentifier</key>
	<string>test</string>
	<key>CFBundleInfoDictionaryVersion</key>
	<string>6.0</string>
	<key>CFBundleName</key>
	<string>upload_tool</string>
	<key>CFBundlePackageType</key>
	<string>APPL</string>
	<key>CFBundleShortVersionString</key>
	<string>0.0.0</string>
</dict>
</plist>
```

I have to manual adding following string into it.
``` <key>NSHighResolutionCapable</key><true/> ```
then make a copy for this .app file,  Let the system reflash ".app" cache.
Then it fix this issue for the .app.

**Comment by bjones1** [comment]
Mac folks, what's the best approach here? There's a [section of the manual](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#spec-file-options-for-a-mac-os-x-bundle) that discusses `info.plist`, but doesn't talk about this entry. There are several recipes that use `info.plist`:
- https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing
- https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing-Qt
- https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-set-default-language-and-encoding

Should we have some central place that discusses OS X `info.plist` settings? Or should this be added as a separate recipe?

**Comment by Cody-Chen** [comment]
I think this issue is easy to solve. adding ```<key>NSHighResolutionCapable</key><true/>``` to info.plist. Or add a args to enable the `NSHighResolutionCapable` , like"--osx-hidpi" .

**Comment by BoboTiG** [comment]
You can set this property (and others) in the .spec file:
```python
info_plist = {
    ...,
    "NSHighResolutionCapable": True,
}

app = BUNDLE(
    coll,
    ...,
    info_plist=info_plist,
)
```
If you need a complete example, you can check the [ndrive.spec](https://github.com/nuxeo/nuxeo-drive/blob/dd020f81d28c2a346f75a7fb6fda834ebf718b0a/ndrive.spec#L94-L112) file.

**Comment by Cody-Chen** [comment]
Thanks a lot. That is what i want.

**Comment by htgoebel** [comment]
I can't see how this should be relatred to PyInstaller and why PytInstaller should provide a Apple tutorial. PyInstaller is not your nany,

**Comment by Cody-Chen** [comment]
Sorry for misunderstand. I just want PytInstaller be better.
