### ISSUE TITLE
Hi, I have no codec found error, help?

### ISSUE THREAD

**Issue by JIwonHn** [pyinstaller/pyinstaller#3886]
When I open the terminal and enter python, it just came up with this error message:

Fatal Python error: initfsencoding: unable to load the file system codec
LookupError: no codec search functions registered: can't find encoding

Current thread 0x00007fffb4a653c0 (most recent call first):
Abort trap: 6

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.
