### ISSUE TITLE
Pyinstaller can't find tesserocr and ocrmypdf on Ubuntu

### ISSUE THREAD

**Issue by atinesh-s** [pyinstaller/pyinstaller#3887]
I have a python application where I'm using **[tesserocr](https://pypi.org/project/tesserocr/)**, **[ocrmypdf](https://pypi.org/project/ocrmypdf/)**. I am trying to create a stand-alone executable of it by using **PyInstaller**.

I can successfully create the executable by using the following command

`$ pyinstaller -F --clean code.py`

But when I run it

`$ ./code`

I get this error

> ModuleNotFoundError: No module named 'tesserocr'
> 
> ModuleNotFoundError: No module named 'ocrmypdf'

**code.py**

```
from tesserocr import PyTessBaseAPI
import ocrmypdf

...
```

I have cross checked **tesserocr** and **ocrmypdf** are successfully installed in my system.

I checked the documentation and tried below things, but none worked

1. Used a virtual environments
2. Used the latest development version. Downloaded from https://github.com/pyinstaller/pyinstaller/archive/develop.zip
3. Used flag `--onedir` instead of `--onefile` or `-F`

**Comment by bwoodsend** [comment]
You're mixing up virtual environments.
