### ISSUE TITLE
Python3.6 function open() to create file is not working on OS X

### ISSUE THREAD

**Issue by sh141** [pyinstaller/pyinstaller#3904]
Hi.
I have built to .exec and .app such following code using latest pyinstaller on OS X:
```
with open("sample.txt", "a") as f:
    f.write('hello')
```

Then I tried .exec and .app, I could not create sample.txt using .app bundle.

There are codes which I added to spec file:
```
app = BUNDLE(exe,
    name='Sample.app',
    icon=None,
    debug=True,
    bundle_identifier=None)
```

On the other hand, I can create sample.txt using .exec (it works via console).

Why .app cannot create file but .exec can create file?

Thanks.

**Comment by htgoebel** [comment]
Please read the manual on how to pack your data-files.
