### ISSUE TITLE
How to reference pyinstaller in a paper

### ISSUE THREAD

**Issue by djhoese** [pyinstaller/pyinstaller#3905]
My team is working on a paper for our software package that benefits from pyinstaller. We would like to reference pyinstaller in the paper. Is there a DOI or other published work about pyinstaller?

**Comment by htgoebel** [comment]
I'm not aware of any publication about PyInstaller.

**Comment by djhoese** [comment]
One thing you could do is link this github repository to https://zenodo.org/

Once linked, this automatically takes github releases and publishes them with DOIs and suggestions for how people can cite/reference the software in a published paper.

**Comment by jat255** [comment]
I would highly recommend using something like Zenodo to obtain a free DOI for this library. Allowing academics to easily cite the package with a persistent identifier will help enhance the discoverability of the project (and it's very little work to set up Zenodo).
