### ISSUE TITLE
sys.path[0] in exe is not Relative directory？

### ISSUE THREAD

**Issue by aabababb** [pyinstaller/pyinstaller#3915]
pickle_file = open(sys.path[0]+'\\my.txt', 'w')
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\X\\AppData\\Local\\Temp\\_MEI3090402\\base_library.zip\\my.txt'
[310588] Failed to execute script 

.py file is ok
but
.exe file have this error
sys.path[0] in exe is not Relative directory

**Comment by htgoebel** [comment]
Please read the manual on how to access your data file.

Assuming `sys.path[0]` to be a directory is wrong, even if not using PyInstaller. Python does not define this.
