### ISSUE TITLE
pyinstaller tries to package everything in source folder

### ISSUE THREAD

**Issue by Jhsmit** [pyinstaller/pyinstaller#3916]
I've recently updated to pyinstaller 3.4. I'm on python 2.7.10 32 bit. I experience some problems where it seems that pyinstaller tries to package everything in the source dir. When building the exe:
```
217578 INFO: Looking for dynamic libraries
217629 DEBUG: Analyzing .git\objects\9e\4d30b1f163afe2fcac10d66bee16e6c5b5ffaa
```
Which seems to me that its trying to pack the `.git` folder. This then leads to the error:

```
  File "c:\python27\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (2, 'LoadLibraryEx', 'The system cannot find the file specified')
```

I run pyinstaller by:
```
C:\Python27\Scripts\pyinstaller --name=SNR_Tools ^
--runtime-hook rthook_pyqt4.py --clean --noconfirm --log-level DEBUG ^
SNR_exe.spec
```

The spec file is as follows:
```python

# -*- mode: python -*-

import enaml
import os
import pickle

enaml_filepath = os.path.split(enaml.__file__)[0]
parser_filepath = os.path.join(enaml_filepath, 'core', 'parser.py')
fields_filepath = os.path.join(enaml_filepath, 'stdlib', 'fields.enaml')

a = Analysis(['snr/main.py'],
             pathex=['C:\\Users\\Smit\\PycharmProjects\\SNR\\snr'],
             binaries=None,
             hiddenimports=['scipy.special._ufuncs_cxx', 'skimage.transform'],
             hookspath=['.\\hooks\\'],
             runtime_hooks=['rthook_pyqt4.py'],
             excludes=['.git'])


a.datas += [('enaml/core/parser.py', parser_filepath, 'DATA')]
a.datas += [('enaml/stdlib/fields.enaml', fields_filepath, 'DATA')]

gui_tree = Tree('snr/gui', prefix='gui', excludes=['*.enamlc'])

pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='SNR_tools.exe',
          debug=True,
          strip=None,
          upx=False,
          console=True )

coll = COLLECT(exe,
               a.datas,
               gui_tree,
               strip=None,
               upx=False,
               name='SNR_Tools')
```

I seem to be unable to convince pyinstaller to leave the git file alone. When I remove the .git folder it moves on to something else which then gives an error. I've tried the most recent build, 3.5.dev0+d90621395, but this gives the same problem.

**Comment by htgoebel** [comment]
Well, I can't spot why the .git directory is included. You need track this down yourself by stripping down the .spec-file.

Regarding the `Analysis`:
```
        excludes
                An optional list of module or package names (their Python names,
                not path names) that will be ignored (as though they were not found).
```

**Comment by Jhsmit** [comment]
Thanks for the quick reply. I've managed to get things to work now with pyinstaller 2.1.
I might come back to pyinstaller 3.4 at some point but for now I'm happy its working after hours of struggle so for this project I might leave it at that.

**Comment by peractio** [comment]
Just wanted to check, any solutions for this besides downgrading to pyinstaller 2.1? I've had a similar problem, same errror and .git\objects\... too

But downgrading doesn't work for me as I'm using Python 3

**Comment by peractio** [comment]
Found a workaround for Python 3 here: https://stackoverflow.com/a/58195896/9379924
