### ISSUE TITLE
Problem with hook-PyQt5.py

### ISSUE THREAD

**Issue by primasanjaya** [pyinstaller/pyinstaller#3917]
I installed pyinstaller and all my python libraries including PyQt via conda command in Windows.

when i tried to run pyinstaller, i got this error message:

File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\hooks\hook-PyQt5.py", line 23, in <module>
    collect_system_data_files(pyqt5_library_info.location['PrefixPath'],
TypeError: 'NoneType' object is not subscriptable

i have rewritten the code as mentioned [here](https://github.com/bjones1/pyinstaller/blob/a617a4eb866272d3aba68f52e9a1ca677fceca72/PyInstaller/hooks/hook-PyQt5.Qt.py) but i got this error:

File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\hooks\hook-PyQt5.py", line 50, in <module>
    binaries += find_all_or_none(angle_files, 3)
  File "C:\ProgramData\Anaconda3\lib\site-packages\PyInstaller\hooks\hook-PyQt5.py", line 38, in find_all_or_none
    dll_path = os.path.join(pyqt5_library_info.location['BinariesPath'],
NameError: name 'pyqt5_library_info' is not defined

is there any solution for this problem? Thank you.

**Comment by bjones1** [comment]
Follow https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#when-submitting-a-bug.

**Comment by primasanjaya** [comment]
i solved it. i've rewritten the json in qt.py wrongly.
