### ISSUE TITLE
Mismatch information in PyInstaller/loader/rthooks.dat and PyInstaller/loader/rthooks directory

### ISSUE THREAD

**Issue by yeulam1thienthan** [pyinstaller/pyinstaller#3925]
When I run pyinstaller to generate executable file in Ubuntu, I got this error. The log said that:
 
**FileNotFoundError: [Errno 2] No such file or directory: ../PyInstaller/loader/rthooks/pyi_rth_nltk.py**

I take a look into the directory ../PyInstaller/loader/rthooks/ and no file pyi_rth_nltk.py, then I copy the file from:

 (https://github.com/pyinstaller/pyinstaller/tree/48995a2f3eb4c78130786a39c472e7c79c92ae5a/PyInstaller/loader/rthooks) 

and paste it into my local directory., the file is: **pyi_rth__nltk.py**

We have a "_" redundant. I fixed it and it works. Pls consider and fix this mismatch.

Thanks.

**Comment by htgoebel** [comment]
This looks like your setup is corrupt. Please reinstall PyInstaller and ensure you are using the correct version.

**Comment by htgoebel** [comment]
Oh, sorry. The important point as a bit hdden in your report: `PyInstaller/loader/rthooks/pyi_rth_nltk.py` is actually named `pyi_rth__nltk.py` (two underscores).
