### ISSUE TITLE
Binary file attributes change when bundled

### ISSUE THREAD

**Issue by conradek** [pyinstaller/pyinstaller#3926]
I have a question about adding binary files when bundling.  When using a Linux box, can I expect that the bundled binary file has the attributes as the original binary file?  I am creating a one-file bundled executable.

I have noticed that the bundled binary file:

- does not have the same permissions as the original.  The original file's permissions are 744.  When launching the executable and checking the binary in in the _MEI directory, the binary file's permissions are 700.

- the same bundled binary file does not have the setuid bit set

- when running getcap on the same bundled binary file, expected capabilities are not set

This occurs when using version 3.4 and also with 3.5.dev0+d90621395.

I tried --one-dir and --one-file with 3.5.dev0+d90621395 and had the same result.

Any ideas?

**Comment by htgoebel** [comment]
> can I expect that the bundled binary file has the attributes as the original binary file? I am creating a one-file bundled executable.

No. Preserving attributes is not supported in onefile-mode. If you want this to be implemented, please submit a pull-request or [fund implementing it](http://www.pyinstaller.org/funding.html).
