### ISSUE TITLE
Socket cannot connect after bundling

### ISSUE THREAD

**Issue by Bersh** [pyinstaller/pyinstaller#3927]
I have a simple python script that connects to the socket opened by Photoshop on the same machine. It always works just fine when executed by python but after creating binary it doesn't connect anymore. In fact, it still can connect sometimes, probably 1 out of 5 attempts, in all other cases I get a connection error.

Here is PyInstaller output: 

> ssss-iMac:test_in_pythontutor sss$ pyinstaller --clean --console --debug all script.spec
> 210 INFO: PyInstaller: 3.4
> 210 INFO: Python: 3.7.1
> 224 INFO: Platform: Darwin-17.7.0-x86_64-i386-64bit
> 231 INFO: UPX is not available.
> 233 INFO: Removing temporary files and cleaning cache in /Users/sss/Library/Application Support/pyinstaller
> 247 INFO: Extending PYTHONPATH with paths
> ['/Users/sss/Desktop/test_in_pythontutor',
> '/Users/sss/Desktop/test_in_pythontutor']
> 247 INFO: checking Analysis
> 248 INFO: Building Analysis because Analysis-00.toc is non existent
> 248 INFO: Initializing module dependency graph...
> 250 INFO: Initializing module graph hooks...
> 252 INFO: Analyzing base_library.zip ...
> 6141 INFO: running Analysis Analysis-00.toc
> 6153 INFO: Caching module hooks...
> 6159 INFO: Analyzing script.py
> 6168 INFO: Loading module hooks...
> 6169 INFO: Loading module hook "hook-encodings.py"...
> 6264 INFO: Loading module hook "hook-pydoc.py"...
> 6266 INFO: Loading module hook "hook-xml.py"...
> 6692 INFO: Looking for ctypes DLLs
> 6692 INFO: Analyzing run-time hooks ...
> 6728 INFO: Looking for dynamic libraries
> 6871 INFO: Looking for eggs
> 6871 INFO: Using Python library /usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/Python
> 6875 INFO: Warnings written to /Users/sss/Desktop/test_in_pythontutor/build/script/warn-script.txt
> 6911 INFO: Graph cross-reference written to /Users/sss/Desktop/test_in_pythontutor/build/script/xref-script.html
> 6932 INFO: checking PYZ
> 6932 INFO: Building PYZ because PYZ-00.toc is non existent
> 6932 INFO: Building PYZ (ZlibArchive) /Users/sss/Desktop/test_in_pythontutor/build/script/PYZ-00.pyz
> 7451 INFO: Building PYZ (ZlibArchive) /Users/sss/Desktop/test_in_pythontutor/build/script/PYZ-00.pyz completed successfully.
> 7463 INFO: checking PKG
> 7463 INFO: Building PKG because PKG-00.toc is non existent
> 7463 INFO: Building PKG (CArchive) PKG-00.pkg
> 7494 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
> 7496 INFO: Bootloader /usr/local/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
> 7496 INFO: checking EXE
> 7497 INFO: Building EXE because EXE-00.toc is non existent
> 7497 INFO: Building EXE from EXE-00.toc
> 7497 INFO: Appending archive to EXE /Users/sss/Desktop/test_in_pythontutor/build/script/script
> 7499 INFO: Fixing EXE for code signing /Users/sss/Desktop/test_in_pythontutor/build/script/script
> 7507 INFO: Building EXE from EXE-00.toc completed successfully.
> 7509 INFO: checking COLLECT
> 7509 INFO: Building COLLECT because COLLECT-00.toc is non existent
> WARNING: The output directory "/Users/sss/Desktop/test_in_pythontutor/dist/script" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
> 31157 INFO: Removing dir /Users/sss/Desktop/test_in_pythontutor/dist/script
> 31165 INFO: Building COLLECT COLLECT-00.toc
> 32448 INFO: Building COLLECT COLLECT-00.toc completed successfully.
> 32453 INFO: checking BUNDLE
> 32453 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
> WARNING: The output directory "/Users/sss/Desktop/test_in_pythontutor/dist/script.app" and ALL ITS CONTENTS will be REMOVED! Continue? (y/n)y
> 34771 INFO: Removing dir /Users/sss/Desktop/test_in_pythontutor/dist/script.app
> 34782 INFO: Building BUNDLE BUNDLE-00.toc
> 35963 INFO: moving BUNDLE data files to Resource directory
> ssss-iMac:test_in_pythontutor sss$

The python code itself is very simple: 
```
import socket

conn = socket.socket()
try:
    hostname = socket.gethostname()
    HOST = socket.gethostbyname(hostname)
    conn.connect((HOST, 8123))
    conn.send("new_cmd = 1;".encode('ascii'))
    result = conn.recv(4096)
    print('result1 : ' + str(result))
    conn.send("new_cmd = 0;".encode('ascii'))
    result = conn.recv(4096)
    print('result2 : ' + str(result))
finally:
    conn.close()
```

The errors I get look like
> File "script.py", line 8, in <module>
> ConnectionRefusedError: [Errno 61] Connection refused

Can be a "broken pipe" sometimes as well.

Do you have any ideas on what can be wrong?

**Comment by htgoebel** [comment]
I can not see how this should be related to PyInstaller. Please check `gethostbyname()`  is actually returning the correct ip-address.
