### ISSUE TITLE
QAudio and QSoundEffect do not detect OS's audio devices

### ISSUE THREAD

**Issue by davinellulinvega** [pyinstaller/pyinstaller#3928]
I am currently trying to package a program that uses `QAudio` and `QSoundEffect` to record and replay sound through the OS's audio devices (microphone and speakers).
When executing the python script on its own, I do not have any issues and can easily record sounds and later replay them.
However, once packaged using `PyInstaller`, no audio device are detected from within the program. This means that recording and playing sound is impossible from within the packaged application.
I have tried to implement and package a similar script which uses `PyAudio`, rather than `PyQt5`. Using `PyAudio` works just fine.
Is there a way `PyQt5` has to be added to the executable for it to be able to detect audio devices? For further information, when executing `pyinstaller`, I am using a spec file and already made sure to include the binaries corresponding to the `audio` and `multimediaservice` plugins.
Any help with this issue would be much appreciated.

**Comment by bjones1** [comment]
Follow the steps in https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html first, then report back.
