### ISSUE TITLE
[Question] How do I re-write this to work within my .exe?

### ISSUE THREAD

**Issue by frakman1** [pyinstaller/pyinstaller#3933]
PyInstaller 3.4
Win 7-64 bit

I made a .exe using python code that has the following logic. The goal is to launch the http server in a new console window on Windows. This is to avoid locking up the main application and the user can just close the newly launched console window when they are finished with the http server.

```python
p = subprocess.call('start "" python  -m http.server --directory {} {} --bind {}'.format(web_server_path, web_server_port, web_bind_ip), shell=True)
```

This works on my machine that has Python installed but naturally does not work on a PC without Python.

Since the goal is to distribute this `.exe` to people without a python installation, can you please recommend the correct method to accomplish the above behavior with pyinstaller? I'm not sure how to proceed. Your assistance is greatly appreciated.

**Comment by frakman1** [comment]
Is there way to load the pythonX.dll file and use it that way? I know that the python interpreter is bundled with the .exe but I don't know how to call it directly like in the above call.

**Comment by AndCycle** [comment]
well, to avoid blocking main app you can just use `threading` module to do the job, 
unless you have some specific requirement you have to fork another process.

**Comment by frakman1** [comment]
@AndCycle Yes, threading will avoid blocking the main app. 
How about calling the bundled python within the .exe? Is there a way to do that?

**Comment by AndCycle** [comment]
@frakman1 you will mess up by the cleanup process if main app close first.

**Comment by frakman1** [comment]
Good points. Thank you for your insight.

**Comment by frakman1** [comment]
@AndCycle I have a related question about exe bundling strategy. 

If I do nothing and just include binary exe files via the binaries= field in the spec file, then they end up going to the ..\AppData\Local\Temp\x\MEIxxxx folder in Windows. They also disappear when I exit the app.

Is it a good idea to zip all the exes and include just that zip file as a binary and then unzip once to the local directory of the .exe when it is launched?

**Comment by frakman1** [comment]
That explains the slow startup. Thanks.

Fortunately those exe are opened using something like:

```pythong
subprocess.call('start "" {}'.format(path_to_exe), shell=True)
```

so they stay running after I exit the main app.

**Comment by vinayak618** [comment]
Hi @frakman1 @AndCycle 
Facing the same issue of slow start up while running the pyinstaller exe on windows.
Did you disable the windows default anti virus or any third party anti virus software?

**Comment by frakman1** [comment]
The slow start is unavoidable for me. I'm just happy it actually works! haha
