### ISSUE TITLE
PyQt5 daemon created in 'onefile' mode fails to execute "because no Qt platform plugin could be initialized"

### ISSUE THREAD

**Issue by aydwi** [pyinstaller/pyinstaller#3937]
### Problem

When PyInstaller is used to freeze [a program](https://gist.github.com/aydwi/efc61d7bf27640ccf00528171e556b8a) which implements a simple PyQt5 daemon with [`python-daemon`](https://pypi.org/project/python-daemon/) in *onefile* mode, and the resulting executable is ran, it throws - 

`qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""`
`This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`

This happens specifically with *onefile*, and the executable created with *onedir* works fine.

### Versions

Linux - `4.18.0-3-amd64`
Distribution - `Debian buster/sid`
Python - `3.7.2rc1`
PyInstaller - `3.5.dev0+5edb4f7de`
PyQt5 - `5.11.3`
python-daemon - `2.2.0`

### Debug Log

See [this gist](https://gist.github.com/aydwi/323fcfe0e70bf7c64fb41c9726d6d70d) for the log output generated by PyInstaller when freezing the above program.

**Comment by bjones1** [comment]
Thanks for this detailed report. Would you be willing to help track this down? My thoughts:

1. Try a simpler program, to verify there's no interaction with other code -- just create a qapplication then exit. Something like:

```
from PyQt5.QtWidgets import QApplication
from PyQt5.QtCore import QTimer

app = QApplication([])
QTimer.singleShot(0, app.exit)
app.exec_()
```

2. Perhaps the run-time hooks aren't working properly -- see https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/loader/rthooks/pyi_rth_qt5.py for code run before user code during startup. Would you print the values of the `QT_PLUGIN_PATH` environment variable to see if it's correct?
3. Odd permissions errors? A wild guess, but does the onedir app run correctly if executed from `/tmp` (where the onefile will be unpacked, I believe)?

**Comment by aydwi** [comment]
I got the executable to work correctly by setting the environment variable QT_PLUGIN_PATH manually to the `plugins` directory of my Qt installation (`ENV/lib/python3.7/site-packages/PyQt5/Qt/plugins`).

**Comment by bjones1** [comment]
OK, so the core issue is that the `QT_PLUGIN_PATH` isn't set correctly in your case. I don't know how `python-daemon` works, but I'm guessing that the temporary directory gets deleted when the main application exits and the daemon runs in another process, causing the error.  You might confirm that `/tmp/_MEImkxgPB/PyQt5/Qt/plugins` (or whatever temp directory is used by a specific execution of your program) actually exists when your Qt code needs it.

Your workaround is fine, but (of course) will only work on your PC, not on other machines.

**Comment by bjones1** [comment]
No, this is by design -- see the [docs](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#how-the-one-file-program-works). Your application requires onedir.
