### ISSUE TITLE
Use variables in SPEC file of PyInstaller

### ISSUE THREAD

**Issue by ttrasn** [pyinstaller/pyinstaller#3941]
I want to use the variable %appdata% in the runtime_tmpdir part of my PyInstaller SPEC file like that:

`exe = EXE(pyz,`
      `    a.scripts,`
        `  a.binaries,`
       `   a.zipfiles,`
      `    a.datas,`
   `       [],`
      `    name='oky',`
       `   debug=False,`
       `   bootloader_ignore_signals=False,`
      `    strip=False,`
       `   upx=True,`
     `     runtime_tmpdir="%appdata%\\MyFolder",`
      `    console=False )`
But I think that it doesn't understand %appdata%, is there's any way to use the variables inside the SPEC file?

Any help would be appreciated.

Thanks!

[stackoverflow](https://stackoverflow.com/questions/52704284/use-variables-in-spec-file-of-pyinstaller)

**Comment by bjones1** [comment]
1. Read the [manual](https://pyinstaller.readthedocs.io/en/stable/index.html). The spec file is written in Python.
2. Learn Python

`appdata` is a Windows environment variable. Use `os.environ['appdata']`.
