### ISSUE TITLE
Some configurations build very slowly, report "WARNING: lib not found"

### ISSUE THREAD

**Issue by jimbo1qaz** [pyinstaller/pyinstaller#3962]
Bundling the program is very slow and produces lots of warnings. This issue only appears on certain environments.

The warnings appear after "Analysis-00.toc" and "Looking for dynamic libraries". They look like `WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\jimbo1qaz\dropbox\encrypted\code\lolinstaller\venv\scripts\python.exe`

https://github.com/pyinstaller/pyinstaller/issues/3712 mentions https://pyinstaller.readthedocs.io/en/v3.4/usage.html#windows. I assume the warnings are because the output is missing a needed DLL on Windows < 10...

The warnings seem to make PyInstaller 6x as slow, with a ~350ms pause after each warning. On Appveyor, x64 versions of Python have no warnings and much faster execution.

Project: https://github.com/jimbo1qaz/corrscope

## Appveyor

PyInstaller: 3.4. All .exe files work fine on Windows 10, regardless of warnings. I created a branch with `--log-level DEBUG` enabled.

Python 3.7 x64
-  52 seconds. https://ci.appveyor.com/project/jimbo1qaz/corrscope/builds/21378143/job/ns62b9ngewd8huc4#L50

Python 3.6 x64
- 44 seconds. https://ci.appveyor.com/project/jimbo1qaz/corrscope/builds/21378143/job/c8gw3g64i6759yfb#L50

Python 3.7 x86
- 258 seconds. https://ci.appveyor.com/project/jimbo1qaz/corrscope/builds/21378143/job/2sf42abseq4f3lmf#L50

Python 3.6 x86
- 316 seconds. https://ci.appveyor.com/project/jimbo1qaz/corrscope/builds/21378143/job/wsft5v5vs39bjd20#L50

## Local build
- Windows 10 x64
- `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`
- python 3.7 x64 builds in 3 minutes (178772 ms) with the same warnings as appveyor x86.
- the exe works.

## Minimal example

Hello World produced a smaller number of errors and took 23 seconds.

- 171 INFO: PyInstaller: 3.5.dev0+1844d69f5
- Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
- 171 INFO: Platform: Windows-10-10.0.16299-SP0 {x64}

https://gist.github.com/jimbo1qaz/744181a8476c495987c64c905292535c

Commands:
- python -m virtualenv venv
- venv\Scripts\activate
- pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  - PyInstaller-3.5.dev0+1844d69f5
- build_pyinstaller.py

`--loglevel debug` improves the output. https://gist.github.com/jimbo1qaz/744181a8476c495987c64c905292535c#file-output-stderr

-----------

Is this related to https://github.com/pyinstaller/pyinstaller/issues/1920 ? Maybe https://github.com/pyinstaller/pyinstaller/issues/3259 ?

**Comment by htgoebel** [comment]
Thanks for your analysis. Please understand that I not going to spend my spare time just to speed up building a few seconds. Thus I'm closing this issue.

Re. #1920: This is done and out optimizations have been merged upstreams.
Re. #3259: I can't see any relaation

**Comment by jimbo1qaz** [comment]
I think it's closer to 3-4 minutes of potential savings (over 80% of runtime), than a few seconds. And I may not be the only user to benefit. Will you accept a pull request to reduce time (and maybe cpu) wasted, if I write one?
