### ISSUE TITLE
pyinstaller3.4 download blocked by zscaler firewall - marked as trojan

### ISSUE THREAD

**Issue by drafter250** [pyinstaller/pyinstaller#3964]
While trying to install pyinstaller the download was interrupted by our company cloud based firewall by [zscaler](https://www.zscaler.com/). When i tried to download directly from the browser on pypi.org https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz I get a warning that the file I may be trying to access is a trojan, unfortunately there is no extra info about what specific files in the release may be triggering the trojan warning. I have submitted a help desk ticket with my company's IT department on whether or not this is a false positive. I will update this issue if i get a response.

I also tried downloading every file from the release page here on github and each of those was blocked as well. I then attempted to download the previous versions from pypi.org for 3.3.1 and 3.3 which i was successfully able to download without any warnings. 

I read through the mailing list and other issues listed in #3960 and understand false positives seem to be frequent with this library, However if i want to use pyinstaller I have to do my due diligence on the part of my employer. Thank you for all your efforts! I am sorry for any inconvenience.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor resp. zscaler. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by bmerkle** [comment]
meanwhile zscaler has reviewed the URL and classified it as a false positive. 
Now our download through zscaler works for 
packages/82/96/21ba3619647bac2b34b4996b2dbbea8e74a703767ce24192899d9153c058/pyinstaller-4.0.tar.gz

I think you can change the resolution to fixed now :-)
