### ISSUE TITLE
Generated executable cannot be run with "ld.so executable"

### ISSUE THREAD

**Issue by espindola** [pyinstaller/pyinstaller#3965]
On linux, pyi_path_executable finds the main executable by reading the /proc/self/exe. This works for ./foo and /full/path/foo, but fails if the dynamic linker is invoked explicitly:

$ /lib64/ld-linux-x86-64.so.2 ./t

since it detects /lib64/ld-linux-x86-64.so.2 as being the executable.

The only reliable way I found to handle this case is to look for the address of a function in the main binary in /proc/self/map_files.

The attached file illustrates the technique. Would a pull request using it be OK?

[test.c.txt](https://github.com/pyinstaller/pyinstaller/files/2728758/test.c.txt)

**Comment by htgoebel** [comment]
Huh, what is the use-case for doing this?

Please note that pending #3829 eliminated the use of /proc/self/exe and will use the argv[0]. This might also eliminate your issue.

**Comment by espindola** [comment]
The use case is similar to what pyinstaller provides: a self contained package. It just takes "self contained" to the extreme by including every used library and the dynamic linker.

#3829  would fix this.
