### ISSUE TITLE
SyntaxError: Non-UTF-8 code starting with '\xec'

### ISSUE THREAD

**Issue by m1233** [pyinstaller/pyinstaller#3966]
I get this error while trying to convert from .py to .exe. I've been trying for over an hour to solve this issue but I've yet to find a fix. I have looked at the docs and some youtube tutorials as well and even though I follow the instructions I get the same error over and over again. Any help would be appreciated. In the file that I'm trying to convert I have used Python 3.5 and Pygame

Here is the full error:

File "C:\Users\Μάνος\AppData\Local\Programs\Python\Python35\Scripts\pyinstaller-script.py", line 1
SyntaxError: Non-UTF-8 code starting with '\xec' in file C:\Users\Μάνος\AppData\Local\Programs\Python\Python35\Scripts\pyinstaller-script.py on line 1, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by htgoebel** [comment]
This file is generated by pip when installing PyInstaller. Please try reinstalling or check your environment.

**Comment by m1233** [comment]
1. I have the newest version of pip
2. I have reinstalled pyinstaller at least 5 times
3. My enviroment variables are fine

**Comment by m1233** [comment]
Ok, I'm gonna look into it! Thanks for the help! Oh and yes the user name is in greek
