### ISSUE TITLE
Missing or misplace .jar file after packing

### ISSUE THREAD

**Issue by Westlife1002** [pyinstaller/pyinstaller#3969]
There is a problem to include a folder of files during the packing process. The main problem is associated with missing this folder called "pyNetlogo" (a python library to control simulation model). To check where does pyNetlogo think the folder should be? **I have add **two print statements at the beginning of my codes** to check before/after packaging. Here is the differences**. 

1). Before packing, the script is run in Pycharm which is working fine, the right path for which the folder should be is reported at:
C:\Users\Jie\AppData\Local\Programs\Python\Python36\lib\site-packages\pyNetLogo 
![3](https://user-images.githubusercontent.com/34776946/50771599-0e0bf500-12c6-11e9-976b-e1d9c0b3cc89.png)

2). After packing, the right path for which the folder should be is reported at: C:\Users\Jie\AppData\Local\Temp\_MEI78242\pyNetLogo
![1](https://user-images.githubusercontent.com/34776946/50771665-385db280-12c6-11e9-911d-644a58ecc03d.png)
This wont's be working since The file uses a temporary directory.

How to fix this problem? How to make sure the folder is properly incorporated in the right path? (please also refer to #3972 for an update of debug and new issues.

**Comment by Westlife1002** [comment]
tried again without -F. It ouputs two folders: dist and build. this is how they look like:
![8](https://user-images.githubusercontent.com/34776946/50776979-5b439300-12d5-11e9-8fcc-c66fc878f315.png)

![9](https://user-images.githubusercontent.com/34776946/50776998-5f6fb080-12d5-11e9-9d8f-6f72cf9885ff.png)

I searched "netlogo" or "link" and find nothing.

**Comment by htgoebel** [comment]
Please refer to the manual on how to include and access data files.
