### ISSUE TITLE
Use pyinstaller to build single .exe interpreter bundle

### ISSUE THREAD

**Issue by Harvie** [pyinstaller/pyinstaller#3975]
Hello. I would like to use pyinstaller to build python interpreter without bundling the python script inside.
So we can have python.exe with all python modules bundled in our git, but don't have to rebuild every time we make a change. I love how pyinstaller automaticaly analyzes the code and bundles all requirements to .exe. But in development setup it might be better if we could edit the .py files without having to rebuild .exe using pyinstaller each time we change something.

I tried to write loader script and build that into .exe, but that way pyinstaller only analyzes the loader script and does not analyze the code that will be loaded by loader script.

Maybe if i could bundle one script, but analyze more scripts to also budle their requirements, so i can load the later from the first script. I know i can probably do this using spec files, but i prefer single command that automaticaly analyzes everything.

Something like this:

`pyinstaller --onefile --distpath . --hidden-import tkinter --paths bCNC --icon bCNC/bCNC.ico --name bCNC loader.py --analyze-extra-requremens bCNC.py --analyze-extra-requremens more.py`

It should bundle loader.py, but also compile-in requirements for bCNC.py and more.py. In case that i will want to use loader.py to load bCNC.py using runpy.

**Comment by htgoebel** [comment]
You can add any number of scripts to be analyzed, see <https://pyinstaller.readthedocs.io/en/stable/spec-files.html>. Guiding you to this is far over what we can provide voluntary. If you need commercial support see http://www.pyinstaller.org/support.html

But to be frank: You do not want to have any executable in your git-repo. This is not what git is build for.  Imagine this file to be 500 MB huge and updated 1 a month. Then you git-repo will become 6GB within a singel year. Create some simple "setup-development-environment.bat" which will download and Install Python (or some .exe you mean) for the developer. You developers should learn how to work with python properly.

**Comment by Harvie** [comment]
> You can add any number of scripts to be analyzed

If i manualy add one script to be analyzed, will it also automaticaly analyze all files included in that script?
