### ISSUE TITLE
Pyinstaller==3.4 OSError: Python library not found: libpython3.4.so.1.0, libpython3.4mu.so.1.0, libpython3.4m.so.1.0

### ISSUE THREAD

**Issue by elijahjude** [pyinstaller/pyinstaller#3976]
I have installed rh-python34 from redhat,installed pyinstaller==3.3.4 using pip,tried to  pack simple print("Hello") using pyinstaller --onefile hello.py.build failed with following error and empty dist folder.I have installed python34-devel and even tried changing LD_LIBRARY_PATH, 

`65 INFO: PyInstaller: 3.3.1
65 INFO: Python: 3.4.2
66 INFO: Platform: Linux-2.6.32-358.el6.x86_64-x86_64-with-redhat-6.4-Santiago
66 INFO: wrote /root/Desktop/pyinstaller/hello.spec
68 INFO: UPX is not available.
70 INFO: Extending PYTHONPATH with paths
['/root/Desktop/pyinstaller', '/root/Desktop/pyinstaller']
70 INFO: checking Analysis
70 INFO: Building Analysis because out00-Analysis.toc is non existent
70 INFO: Initializing module dependency graph...
72 INFO: Initializing module graph hooks...
73 INFO: Analyzing base_library.zip ...
4436 INFO: Processing pre-find module path hook   distutils
7696 INFO: running Analysis out00-Analysis.toc
7712 INFO: Caching module hooks...
7720 INFO: Analyzing /root/Desktop/pyinstaller/hello.py
7731 INFO: Loading module hooks...
7732 INFO: Loading module hook "hook-encodings.py"...
7816 INFO: Loading module hook "hook-pydoc.py"...
7817 INFO: Loading module hook "hook-xml.py"...
8459 INFO: Loading module hook "hook-distutils.py"...
8488 INFO: Looking for ctypes DLLs
8488 INFO: Analyzing run-time hooks ...
8501 INFO: Looking for dynamic libraries
8814 INFO: Looking for eggs
8815 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "/opt/rh/rh-python34/root/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.3.1', 'console_scripts', 'pyinstaller')()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/PyInstaller/__main__.py", line 94, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/PyInstaller/__main__.py", line 46, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 791, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 737, in build
    exec(text, spec_namespace)
  File "<string>", line 16, in <module>
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 213, in __init__
    self.__postinit__()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/PyInstaller/building/datastruct.py", line 161, in __postinit__
    self.assemble()
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 545, in assemble
    self._check_python_library(self.binaries)
  File "/opt/rh/rh-python34/root/usr/lib/python3.4/site-packages/PyInstaller/building/build_main.py", line 629, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: libpython3.4.so.1.0, libpython3.4mu.so.1.0, libpython3.4m.so.1.0
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.

* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
`
I tried resolving this from two days. any help ?

**Comment by htgoebel** [comment]
> I tried resolving this from two days. any help ?

Whyt dd you try?

**Comment by elijahjude** [comment]
i tried changing LD_LIBRARY_PATH and installing devel tools. am a new bie.

**Comment by htgoebel** [comment]
I assume Redhat fiddled around with the library name, see #3881.

Please ty the most recent development version, as written in the issue template.

**Comment by elijahjude** [comment]
am sorry am new to github, can you please help me on how to try the most recent version.thanks

**Comment by htgoebel** [comment]
I assume you are a developer, are you? So you should be able to solve these kind o problems yourself. Esp,.you should be able to read the manual https://pyinstaller.readthedocs.io/en/stable/installation.html or look at the wiki. This is an issue-travcker, not a tutorial.

If you need commercial support see http://www.pyinstaller.org/support.html

**Comment by elijahjude** [comment]
completely my mistake. i tried without /tarball/develop at the end.i should have not ask you.a big thanks for the help. really appreciate your work.
