### ISSUE TITLE
distutils.command.bdist_egg not found in PYZ

### ISSUE THREAD

**Issue by paleozogt** [pyinstaller/pyinstaller#3979]
**Platform:** Reproduced on Mac and Ubuntu with Python 2.x and 3.x
**PyInstaller:** 3.5.dev0+24cac328f
**Gist to reproduce:** https://gist.github.com/paleozogt/33468e62f999cfba29625c632fbd4a6c

I'm trying to use PyInstaller to package up a script that generates egg/whl files, like this:
```
...

setup(name = generated_name,
    version = '1.0',
    description = generated_name,
    py_modules = [generated_name],
    script_args = ["bdist_egg"]   # or "bdist_wheel"
)
```

But I'm getting errors like 
`error: invalid command 'bdist_egg'` 
or
`error: invalid command 'bdist_wheel'`

Turning on PyInstaller's `--debug` shows
`# distutils.command.bdist_egg not found in PYZ`
or
`# distutils.command.bdist_wheel not found in PYZ`

The weird thing is that these don't seem to be real modules so I'm not sure how to add them to the hidden imports.  For example:
```
python -c 'import distutils.command.bdist_egg'                 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: No module named bdist_egg
```

How can I add these strange packages to PyInstaller's packaging?

**Comment by htgoebel** [comment]
These "strange packages" are the "command" implementations, which most probably are importing using `__import__`. See https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#listing-hidden-imports

**Comment by htgoebel** [comment]
IC. So I was wrong about `__imoort__`, setuptools uses a different approach ot hook into distutils. The interaction between setuptools and distutils are complicated and not easy to get. 

> from setuptools.command import bdist_egg

Is the module this line come from frozen into the PYZ? If not, you need to add this as a hidden import.

> Does pyinstaller support sys.modules.setdefault?

You should b able to answer this yourself, at least after reading the Python documentation.

**Comment by paleozogt** [comment]
Yes, `setuptools.command.bdist_egg` is in the PYZ.  The call to `setdefault` down in `setuptools.command.easy_install` doesn't seem to be working tho.

**Comment by htgoebel** [comment]
Is the module **this line comes from** frozen into the PYZ?

**Comment by paleozogt** [comment]
Yes.  The line is from `setuptools.command.easy_install`.  I've explicitly added 

```
from setuptools.command import bdist_egg, easy_install
```

so that its frozen into the PYZ.

**Comment by htgoebel** [comment]
You need to fins out how setuptools resp. distutils is collection its known commands, why bdist_egg is no known. Then I might be able to help you making setuptools resp. distutils recognize the command.

I'm sorry, I can not spend my spare time tracking this down for you.  If you need [commercial support](http://pyinstaller.org/support), please drop me a note.
