### ISSUE TITLE
NumPy 1.16.0 caused ModuleNotFoundError

### ISSUE THREAD

**Issue by KmolYuan** [pyinstaller/pyinstaller#3982]
The new version of NumPy (`1.16.0`) has changed API of `dtype` module.

My example is written in Cython. When I using:

```python
# my_cython_module.pyx
from numpy cimport ndarray
```

And import it in Python script:

```python
# my_package/__init__.py
from .my_cython_module import ...
```

No errors occurred at runtime, but caused this error after "compiled" into an executable:

```bash
  File "__init__.pxd", line 206, in init my_cython_module
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\numpy\__init__.py", line 151, in <module>
  File "C:\Users\me\AppData\Local\Programs\Python\Python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\numpy\ctypeslib.py", line 369, in <module>
  File "site-packages\numpy\ctypeslib.py", line 358, in _get_typecodes
  File "site-packages\numpy\ctypeslib.py", line 358, in <dictcomp>
ModuleNotFoundError: No module named 'numpy.core._dtype_ctypes'
```

After imported that module manually in Python script, the error had been solved.

```python
# my_package/__init__.py
import numpy.core._dtype_ctypes
from .my_cython_module import ...
```

**Comment by leyhline** [comment]
Had the same problem.

My current workaround is adding `hiddenimports=['numpy.core._dtype_ctypes']` to my `build.spec`

**Comment by htgoebel** [comment]
@leyhline I'd appreciative if you'd provide a pull-request for fixing the hook.

**Comment by leyhline** [comment]
@leyhline Alright, I'll take a look where to add the hook since I currently just placed this in the `build.spec` of my package.

**Comment by KmolYuan** [comment]
It seems like this issue occurred with both Python and Cython module.

**Comment by chrisjbremner** [comment]
@htgoebel, looks like @lstolcman made a patch in https://github.com/pyinstaller/pyinstaller/pull/3985

**Comment by mattip** [comment]
NumPy dev here. Are you sure you have a clean installation of NumPy 1.16? There should be no `numpy.core.multiarray*.pyd` file, only a `numpy.core._multiarary_umath*.pyd` file

**Comment by KmolYuan** [comment]
@mattip I'm sure the environment is clean, the error caused with CI too.

**Comment by mattip** [comment]
Ahh, is this due to `numpy.core._dtype_ctype.py` only being imported via the c-extension module `PyImport_ImportModule("numpy.core._dtype_ctypes")`, and not via any python import? Would it help if we import it explicitly through python?

**Comment by KmolYuan** [comment]
The analyzer of PyInstaller seems to missed `numpy.core._dtype_ctypes` when packing modules.

When try to run the packed scripts, the launcher cannot find it.

**Comment by mattip** [comment]
For the more general issue of NumPy analysis hooks, I see there is [code to detect MKL](https://github.com/pyinstaller/pyinstaller/blob/v3.4/PyInstaller/hooks/hook-numpy.core.py) and [code to add dlls on windows](https://github.com/pyinstaller/pyinstaller/blob/v3.4/PyInstaller/hooks/hook-numpy.py). Perhaps you could open issues to get these included in future versions of NumPy? The MKL libraries are actually added by Intel (and distributed by Anaconda), but opening issues on the numpy tracker explaining what must be done to support PyInstaller would at least get the ball rolling and provoke discussion.

**Comment by KmolYuan** [comment]
@lstolcman Yes, the issue has been sloved at NumPy `1.16.1`.

**Comment by shortpoet** [comment]
@KmolYuan I just upgraded to 1.16.1 and having the same issue.

**Comment by KmolYuan** [comment]
@shortpoet What is the way you import modules? Pure Python can import NumPy directly. Cython module should be imported NumPy in Python script or add a hidden import of NumPy if it is not used in script.

**Comment by shortpoet** [comment]
@KmolYuan I usually use pip.  I'm using conda overall and recently did conda upgrade python and a couple others.  That's when I ran into the issue with pandas (in jupyter, not sure if that matter, i'm a bit of a noob sorry lol).  I downgraded to numpy 1.154, if I got that correct, as suggested in one of the answers (on SO I think), and it's working again.
