### ISSUE TITLE
NLTK hook Issue 

### ISSUE THREAD

**Issue by AshishDhadwal** [pyinstaller/pyinstaller#3983]
I was creating an exe using Pyinstaller .
Whenever i try to run its says nltk _data not found .i had installed all the nltk_data but its not working 
First its ask for c drive and now D drive .I was not able to find the solution  

- 217386 INFO:   Matplotlib backend "pdf": added
- 218010 INFO:   Matplotlib backend "pgf": added
- 218514 INFO:   Matplotlib backend "ps": added
- 219060 INFO:   Matplotlib backend "svg": added
- 219592 INFO:   Matplotlib backend "template": added
- 220289 INFO: Loading module hook "hook-matplotlib.py"...
- 220617 INFO: Loading module hook "hook-nltk.py"...
- Unable to find "D:\nltk_data" when adding binary and data files.

**Comment by Axemen** [comment]
Had the same issue and found that the hook-nltk.py hook was grabbing all possible nltk_data paths and giving them to pyinstaller. My Solution to this was to change the code inside of the hook from 
https://github.com/pyinstaller/pyinstaller/blob/96897fc78d9cbb5b8be9d353499b25295badbc9f/PyInstaller/hooks/hook-nltk.py#L14-L25

To 

```
import nltk
from pathlib import Path
from PyInstaller.utils.hooks import collect_data_files

# add datas for nltk
datas = collect_data_files('nltk', False)

# loop through the data directories and add them
for p in nltk.data.path:
    if Path(p).exists():
        datas.append((p, "nltk_data"))

# nltk.chunk.named_entity should be included
hiddenimports = ["nltk.chunk.named_entity"]
```

The only change that i made was checking if the path exists using the pathlib library.
