### ISSUE TITLE
Pyinstaller 3.4 in Python 3.7. AttributeError 

### ISSUE THREAD

**Issue by ALEERQUESON2DIAS** [pyinstaller/pyinstaller#3986]
Hello all, 

I have last develop of Pyinstaller as mentioned installed by zip ( PyInstaller==3.5.dev0+0d289e49b ) running in Python 3..7.2.

I have a program source with python v3.7.2 that uses ONEDRIVESDK and works fine using the python interpreter and the source program

CMD------> py -3 odacce.py a:/odparm.json QUO
RESULTS--> Total Size: 115.0GiB, Used: 48.9GiB, Remaining: 66.1GiB, Deleted: 159.6KiB,
Your state is: normal
CMD-------> py -3 odacce.py a:/odparm.json FID od:/DAT/A/file.txt
RESULTS---> file.txt<>file.6EA482G9EM79G808!120935

I am trying to generate an executable through PYINSTALLER. Some actions such as obtaining the QUOTA (previous example) works fine, but access to files show the following error

CMD------> odacce.exe a:/odparm.json QUO
RESULTS--> Total Size: 115.0GiB, Used: 48.9GiB, Remaining: 66.1GiB, Deleted: 159.6KiB,
Your state is: normal
CMD------> odacce.exe a:/odparm.json FID od:/DAT/A/file.txt
**### **RESULTS--> Traceback (most recent call last):
File "odacce.py", line 556, in
File "odacce.py", line 442, in do_fid
File "odacce.py", line 274, in get_remote_item**
**AttributeError: 'OneDriveClient' object has no attribute 'item'****
[5864] Failed to execute script odacce

The instruction that fails is f = **client.item(drive = 'me', path = path).get()**

I suppose I need to manage the "*.spec" file to give special parameters to PYINSTALLER builder tool. I saw some information in member .gitignore ( ignore PyCharm) but I do not know how to translate it effectively for the correct generation of the executable module (.exe).

I have revised logs and warnings and  read many similar comments about this error in the last two days, but none of the solutions provided have worked or probably I have not been able to interpret them correctly.

Please, could someone give me some indication on this matter?

Thank you very much and best regards

**Comment by htgoebel** [comment]
Without knowing anything about the onedrivesdk thing, I assume this ia what happens:
- OneDriveClient is missing some module or file
- thus the `client` object will not initiated properly
- thus `client.item is not set.

I suggest reading the code of OneDriveClient, find the place where it is set and find the reason why it is not set. HTH

**Comment by htgoebel** [comment]
I forgot: If you fixed this issue, We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by htgoebel** [comment]
@ALEERQUESON2DIAS Any news?
