### ISSUE TITLE
MultiOS package + OS detection executable

### ISSUE THREAD

**Issue by nintyfan** [pyinstaller/pyinstaller#3988]
Hi. This is not bug report, but rather feature report.
I created hybrid cmd/bash script builder. Output is script, which is both cmd and bash script (it could been interpreted by cmd and bash). I told the world about the tool (also on Python forum) and someone told me, that you could use my method to made bash/cmd script, that detects OS and performs task related to detected OS as runner. Instead generating an archive with only GNU/Linux or Windows files, you could generate one big bundle and add script to detect OS and run correct executable.

My idea was quite different - just create a script containing program written in python and script to download and install Windows/Linux Python VM. It will detect OS, check Python is installed, install it if not, extract our program and ran it.

What do you prefer?
Read this: https://python-forum.io/Thread-In-place-of-py2exe-for-GNU-Linux-systems-and-MultiOS-executables-Yes?pid=69198#pid69198

**Comment by htgoebel** [comment]
If you want to build a wrapper around PyInstaller doing all this stuff, go ahead. But this is out of scope for PyInstaller. PyInstaller is not a deployment tools.
