### ISSUE TITLE
Pyinstaller cannot locate basic modules

### ISSUE THREAD

**Issue by CombatVolcano** [pyinstaller/pyinstaller#3989]
I try to build with pyinstaller
My script begins
Import traceback
Import inspect
Import xmltodict

I run pyinstaller using 
Python -m eel program.py web --onefile

When I run exe I get
No module named 'xmltodict'

Why can't it find normal local modules now? ????????

Xmltodict definitely is installed.

Why can't this thing just have a file that is a list of paths to check for imports, why it gatta be so crazy

This is killing me, maybe literally. Please help. Please please

**Comment by htgoebel** [comment]
>   Import traceback

This is no valid Python code.

>  Python -m eel program.py web --onefile

This command is wrong and can not work.

Beside this: Obviously pyinstaller does not find xmltodict. Check your environment and read what is written in the wiki,
