### ISSUE TITLE
Freezed python program that implements scipy.interpolate in one Windows10 machine cannot be executed in another Windows10 machine.

### ISSUE THREAD

**Issue by nazrifuad2008** [pyinstaller/pyinstaller#3992]
I created a simple python script that runs the example from scipy.interpolate.interp1d. The name of my script is test_interpolate.py and the contents of the script are as follow:

import numpy as np
import scipy
from scipy import interpolate
print("Scipy version: " + str(scipy.__version__))
x = np.arange(0, 10)
y = np.exp(-x/3.0)
f = interpolate.interp1d(x, y)
xnew = np.arange(0, 9, 0.1)
ynew = f(xnew)
print(ynew)

First, i run it as usual from my Windows10 machine using python Anaconda prompt:

![snapshot](https://user-images.githubusercontent.com/46857173/51436052-61b41080-1cc0-11e9-8d2f-2e7617741d7c.png)

As you can see, nothings problem there. Then I froze the application using pyinstaller development version:

![snapshot 2](https://user-images.githubusercontent.com/46857173/51436115-c02dbe80-1cc1-11e9-9e4d-0eb48978345b.png)

Again nothing unusual there. Then I run the froze python script using the generated exe file in the corresponding dist directory:

![snapshot 3](https://user-images.githubusercontent.com/46857173/51436157-8c9f6400-1cc2-11e9-88aa-1aca7d830deb.png)

As you can see, the application run smoothly. Good job pyinstaller. But then when I copy the file (and of course the whole folder where my exe is located) and transfer it to another Windows10 machine to test it, suddenly it gives the following errors:

![snapshot 4](https://user-images.githubusercontent.com/46857173/51436273-0afd0580-1cc5-11e9-95f4-ec19137f7527.png)

and please take note that the paths that show in the Traceback refer to the paths in the original Window10 machine where the application was already frozen and run successfully. What caused this issue?

**Comment by htgoebel** [comment]
You did not provide the information the isseu-template is asking for, esp. which version of PyInstaller you are using. So you will have to track this down yourself.

Obviously you missed packaging some DLL. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing. Also please try the most recent development version and have look at the open pull-request,
