### ISSUE TITLE
This might be a simpler solution for all and seems to work like a charm for me. No homebrew or anaconda or copying files into folder or modifying any files needed. One file shareable app created. Works with both regular tkinter based gui or pysimplegui.

### ISSUE THREAD

**Issue by PradyumnaDahal** [pyinstaller/pyinstaller#3994]
This might be a simpler solution for all and seems to work like a charm for me. No homebrew or anaconda or copying files into folder or modifying any files needed. One file shareable app created. Works with both regular tkinter based gui or pysimplegui.

**Pyinstaller instructions Mac**

1) Navigate to directory where the script/s is/are saved using terminal

2) Copy and paste the following
pyinstaller --onefile --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' xyz.py

3) Remember to change the xyz and hit return

(Mac OS 10.11.6, python 3.7.1, pyinstaller 3.4)

_Originally posted by @Nutshell1 in https://github.com/pyinstaller/pyinstaller/issues/1350#issuecomment-445515792_

This worked for my personal computer but when I transfer files to a different computer it created a similar problem

Traceback (most recent call last):
  File "main.py", line 29, in <module>
  File "tkinter/__init__.py", line 2023, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories: 
    /var/folders/05/hhh_g_5n09v45__1n7pd9cbw0000gn/T/_MEIz3HNc1/tcl /var/folders/05/hhh_g_5n09v45__1n7pd9cbw0000gn/T/_MEIz3HNc1/tcl8.6 /Library/Frameworks/Python.framework/Versions/3.7/lib/tcl8.6 /Users/user/lib/tcl8.6 /Users/lib/tcl8.6 /Users/user/library /Users/library /Users/tcl8.6.8/library /tcl8.6.8/library

This probably means that Tcl wasn't installed properly.

**Comment by htgoebel** [comment]
This is an issue-tracker, not a forum. Please abstain from posting talk.

**Comment by pepperpo** [comment]
I have the same issue: when moving the app to another Mac, Tcl is not working.
I do not understand why this was closed saying that this is not a forum.

**Comment by gangsh9** [comment]
seeing same issue. when run on othe macOS

**Comment by nwalter82** [comment]
Have the same issue when run on another mac.
