### ISSUE TITLE
Error in conda env: tries to find a pyinstaller.exe\__main__.pyo

### ISSUE THREAD

**Issue by revesansparole** [pyinstaller/pyinstaller#3995]
I have some troubles while trying to compile a project with the latest version of pyinstaller.
I have created a small project that reproduce the bug with a readme that summarize all the steps to reproduce it:
 - platform windows 10 professional
 - https://github.com/revesansparole/bug_pyinst

Thanks for your help
Jerome

PS: It used to work correctly with the conda package (pyinstaller 3.4  py36h7602738_0 conda-forge) if I modify by hand the qt hook to create a QCoreApplication first (change that has been added since in pyinstaller code).

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a **traceback**.

**Comment by revesansparole** [comment]
# Traceback

Traceback (most recent call last):
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\jchopard\AppData\Local\Continuum\miniconda3\envs\bug_pyinst2\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "n_ferti.spec", line 23, in <module>
    noarchive=True)
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\site-packages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\site-packages\PyInstaller\building\build_main.py", line 597, in assemble
    for name, path, typecode in compile_py_files(new_toc, CONF['workpath']):
  File "c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\lib\site-packages\PyInstaller\utils\misc.py", line 150, in compile_py_files
    with open(obj_fnm, 'rb') as fh:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\jchopard\\AppData\\Local\\Continuum\\miniconda3\\envs\\bug_pyinst2\\Scripts\\pyinstaller.exe\\__main__.pyo'

# software versions
Name                    Version                   Build  Channel
altgraph                  0.16.1                    <pip>
blas                      1.0                         mkl
certifi                   2018.11.29               py36_0
future                    0.17.1                    <pip>
icc_rt                    2019.0.0             h0cc432a_1
intel-openmp              2019.1                      144
macholib                  1.11                      <pip>
mkl                       2019.1                      144
mkl_fft                   1.0.10           py36h14836fe_0
mkl_random                1.0.2            py36h343c172_0
nitrogen-ferti            0.1.0                     <pip>
numpy                     1.15.4           py36h19fb1c0_0
numpy-base                1.15.4           py36hc3f5095_0
pandas                    0.23.4           py36h830ac7b_0
pefile                    2018.8.8                  <pip>
pip                       18.1                     py36_0
PyInstaller               3.5.dev0+d5a902d9e           <pip>
python                    3.6.8                h9f7ef89_0
python-dateutil           2.7.5                    py36_0
pytz                      2018.9                   py36_0
pywin32-ctypes            0.2.0                     <pip>
setuptools                40.6.3                   py36_0
six                       1.12.0                   py36_0
sqlite                    3.26.0               he774522_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.15.26706          h3a45250_0
wheel                     0.32.3                   py36_0
wincertstore              0.2              py36h7fe50ca_0

# full logs

82 INFO: PyInstaller: 3.5.dev0+d5a902d9e
82 INFO: Python: 3.6.8
84 INFO: Platform: Windows-10-10.0.16299-SP0
88 INFO: UPX is not available.
96 INFO: Extending PYTHONPATH with paths
['C:\\Users\\jchopard\\Documents\\eval\\pkging\\pyinst\\bug\\bug_pyinst\\example',
 'C:\\Users\\jchopard\\Documents\\eval\\pkging\\pyinst\\bug\\bug_pyinst']
97 INFO: checking Analysis
100 INFO: Building Analysis because Analysis-00.toc is non existent
101 INFO: Initializing module dependency graph...
104 INFO: Initializing module graph hooks...
108 INFO: Analyzing base_library.zip ...
3214 INFO: running Analysis Analysis-00.toc
3219 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\python.exe
3921 INFO: Caching module hooks...
3930 INFO: Analyzing example\cmp_strategies.py
4022 INFO: Processing pre-find module path hook   distutils
4336 INFO: Processing pre-safe import module hook   six.moves
6116 INFO: Processing pre-find module path hook   site
6117 INFO: site: retargeting to fake-dir 'c:\\users\\jchopard\\appdata\\local\\continuum\\miniconda3\\envs\\bug_pyinst2\\lib\\site-packages\\PyInstaller\\fake-modules'
7375 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
13451 INFO: Loading module hooks...
13452 INFO: Loading module hook "hook-distutils.py"...
13454 INFO: Loading module hook "hook-encodings.py"...
13567 INFO: Loading module hook "hook-lib2to3.py"...
13572 INFO: Loading module hook "hook-numpy.core.py"...
13917 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
13924 INFO: Loading module hook "hook-numpy.py"...
13926 INFO: Loading module hook "hook-pandas.py"...
15221 INFO: Loading module hook "hook-pkg_resources.py"...
15539 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
15616 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
15886 INFO: Loading module hook "hook-pydoc.py"...
15888 INFO: Loading module hook "hook-pytz.py"...
16010 INFO: Loading module hook "hook-setuptools.py"...
16603 INFO: Loading module hook "hook-sqlite3.py"...
16741 INFO: Loading module hook "hook-sysconfig.py"...
16743 INFO: Loading module hook "hook-xml.dom.domreg.py"...
16744 INFO: Loading module hook "hook-xml.py"...
16814 INFO: Looking for ctypes DLLs
16857 INFO: Analyzing run-time hooks ...
16866 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
16870 INFO: Including run-time hook 'pyi_rth_pkgres.py'
16887 INFO: Looking for dynamic libraries
16965 WARNING: lib not found: impi.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_blacs_intelmpi_ilp64.dll
19082 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_pgi_thread.dll
19132 WARNING: lib not found: pgf90.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_pgi_thread.dll
19179 WARNING: lib not found: pgc14.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_pgi_thread.dll
19273 WARNING: lib not found: msmpi.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_blacs_msmpi_lp64.dll
19326 WARNING: lib not found: impi.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_blacs_intelmpi_lp64.dll
19620 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_blacs_mpich2_ilp64.dll
21343 WARNING: lib not found: tbb.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_tbb_thread.dll
21393 WARNING: lib not found: msmpi.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_blacs_msmpi_ilp64.dll
32563 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\Library\bin\mkl_blacs_mpich2_lp64.dll
33071 INFO: Looking for eggs
33071 INFO: Using Python library c:\users\jchopard\appdata\local\continuum\miniconda3\envs\bug_pyinst2\python36.dll
33072 INFO: Found binding redirects:
[]

**Comment by htgoebel** [comment]
The traceback does not match what you have written in https://github.com/revesansparole/bug_pyinst. According to the traceback PyInstaller tries to read a .pyo file, which means your are running with `python -O`. But the readme does not state thus.

Further:
>  FileNotFoundError: [Errno 2] No such file or directory: '**pyinstaller.exe**\main.pyo'

This looks more like there is something mixed up in your environment.

**Comment by revesansparole** [comment]
The traceback is an exact copy of the one produced following the steps explained in https://github.com/revesansparole/bug_pyinst.

To my knowledge, I am not running python -O anywhere.

Everything was working fine with pyinstaller 3.4 installed with pip. The error happened once I installed the latest version of pyinstaller from develop.

Do you have any pointer on where I'm supposed to look to start understanding the problem?

**Comment by AndCycle** [comment]
I got similar issue with `--debug` flag, and only happened with `--debug`.
