### ISSUE TITLE
LoadLibrary: PyInstaller: FormatMessageW failed. 

### ISSUE THREAD

**Issue by badbob** [pyinstaller/pyinstaller#3999]
I'm trying to cross-compile (using `Wine`) as a single file (or directory, no matter) my simple downloader Python tool. Here is a source code of that script on [GitHub](https://github.com/badbob/elib-dl).

Here what I was doing:
```
me$ git clone https://github.com/badbob/elib-dl
me$ cd elib-dl
me:~/elib-dl$ wget https://www.python.org/ftp/python/3.4.4/python-3.4.4.amd64.msi
me:~/elib-dl$ wine64 msiexec /i python-3.4.4.amd64.msi
me:~/elib-dl$ wine64 pip install PyInstaller
me:~/elib-dl$ wine64 pyinstaller -F elib-dl.py
```
The resulting `elib-dl.exe` from `dist` folder could be found [here](https://github.com/badbob/elib-dl/releases/download/v0.2/elib-dl.exe). It works fine in `Wine` environments. But when I try to run it on VirtualBox, it fails with the error message:

```
C:\Users\admin\Desktop\elib-dl>elib-dl.exe                     
Error loading Python DLL 'C:\Users\admin\Desktop\elib-dl\python34.dll'.                                                 
No error messages generated.                                                                                            
FormatMessageW: The parameter is incorrect.                                                                             
LoadLibrary: PyInstaller: FormatMessageW failed. 
```
I found only one same question on [StackOverflow](https://stackoverflow.com/questions/54214600/) but it has no answers. 

Please, advice.

**Comment by mancej** [comment]
We are also experiencing this issue with Windows 7. Windows 10 seems fine.

**Comment by badbob** [comment]
@mancej 

> We are also experiencing this issue with Windows 7. Windows 10 seems fine.

I reproduced this bug on `Windows 10` and `Windows 8`.

**Comment by headrx** [comment]
Is there a resolution ? Im trying to 'compile' py 3.7 application that utilizes PyQt5. Appreciated.

**Comment by htgoebel** [comment]
Cross-building using wine is not officially supported, thus this is not a bug.

**Comment by htgoebel** [comment]
Cross-building using wine is not officially supported, thus I'm closing this a not-a-bug.

**Comment by erezsh** [comment]
I am getting this error on Windows 7 for a PyInstaller exe compiled on  Windows 10.

No wine involved in any way.

**Comment by sahilcool-nsut** [comment]
> I am getting this error on Windows 7 for a PyInstaller exe compiled on Windows 10.
> 
> No wine involved in any way.

Exactly the same problem.. Is there no fix till now?

**Comment by bwoodsend** [comment]
Are you using Python 3.9 by any chance? It doesn't support Windows 7.

**Comment by sahilcool-nsut** [comment]
> Are you using Python 3.9 by any chance? It doesn't support Windows 7.

Ah yes, I am using that version. Dang! In that case, can you explain how can I use pyinstaller using a different python version while keeping 3.9 installed too?

**Comment by bwoodsend** [comment]
Probably the safest way (albeit not the most streamlined) is to grab a 3.8 installer from [https://www.python.org/downloads](), install it making sure that you **disable the option to add Python to `PATH`**. Then just use full paths whenever you want to reference it.

* Instead of `python` use `C:\path\to\python3.8\python.exe`
* Instead of `pip` use `C:\path\to\python3.8\python.exe -m pip`
* Instead of `pyinstaller` use `C:\path\to\python3.8\python.exe -m PyInstaller`

If you need to do this a lot, [pyenv-win](https://pyenv-win.github.io/pyenv-win/) is decent enough.
