### ISSUE TITLE
PyInstaller not found after upgrading pip is a PyInstaller issue

### ISSUE THREAD

**Issue by kbrown** [pyinstaller/pyinstaller#4006]
@rt121212121 @jeanlaroche @kjanko As this happens after updating pip and nothing changed for PyInstaller you should report this bug tip pip, shoulnt't you?

Perhaps PyInstaller is doing something non-standard.  If PyInstaller is relying on pip18 behavior that happens to work that's a PyInstaller bug.  At the very least it's good to have a tracking issue.

This is what I get in my docker linux build:

root@2c27187d77e0:/opt/reporting# cat ./req.txt                    
pyinstaller >= 3.3.1
root@2c27187d77e0:/opt/reporting# pip3 install -r ./req.txt        
Collecting pyinstaller>=3.3.1 (from -r ./req.txt (line 1))
  Using cached https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  Complete output from command /usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpprfz6qmc:
  Traceback (most recent call last):
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
      main()
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-jln53ug6/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 115, in get_requires_for_build_wheel
      return _get_build_requires(config_settings, requirements=['wheel'])
    File "/tmp/pip-build-env-jln53ug6/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 101, in _get_build_requires
      _run_setup()
    File "/tmp/pip-build-env-jln53ug6/overlay/lib/python3.6/site-packages/setuptools/build_meta.py", line 85, in _run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 20, in <module>
      from PyInstaller import __version__ as version, HOMEPATH, PLATFORM
  ModuleNotFoundError: No module named 'PyInstaller'
  
  ----------------------------------------
Command "/usr/local/bin/python /usr/local/lib/python3.6/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpprfz6qmc" failed with error code 1 in /tmp/pip-install-q6m4bcpk/pyinstaller
root@2c27187d77e0:/opt/reporting# lsb_release -a
bash: lsb_release: command not found
root@2c27187d77e0:/opt/reporting# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

**Comment by jeanlaroche** [comment]
I did open a bug with pip and they are looking at it. I think this is an issue with setuptools, from the discussion over there. I'm thinking you shouldn't waste too much time on this until they figure it out . See this: https://github.com/pypa/pip/issues/6163

**Comment by kbrown** [comment]
FWIW, pip19 works with pyinstaller == 3.2.1

**Comment by htgoebel** [comment]
This as **not** a bug in PyInstaller. This is obviously caused by some change to pip. Many other projects are affected, see pypa/pip/issues/#6163
