### ISSUE TITLE
pyinstaller import error _distributor_init(numpy + MKL 1.16 python27)

### ISSUE THREAD

**Issue by PabloBeranger** [pyinstaller/pyinstaller#4008]
The build is OK.
   
When i execute the exe file i have this error
   ImportError: cannot import name _distributor_init

I put 'numpy._distributor_init', 'numpy.__init__','numpy' in the hiddenimports but nothing change. i always the same error

**Comment by wackxu** [comment]
@PabloBeranger Have you solved this problem?

**Comment by bwoodsend** [comment]
We'd need a full traceback to answer but it looks like `--hiddenimport=_distributor_init` is what you're after.
