### ISSUE TITLE
@DaytonaJohn  I have the same error as yours when I have the code `import os` in my script. How did you solve this error?

### ISSUE THREAD

**Issue by assslove** [pyinstaller/pyinstaller#4012]
@DaytonaJohn  I have the same error as yours when I have the code `import os` in my script. How did you solve this error?
>   File "os.py", line 120, in \<module\>
  from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep,
 ImportError: No module named path

_Originally posted by @taosean in https://github.com/pyinstaller/pyinstaller/issues/3609#issuecomment-403718961_

**Comment by assslove** [comment]
import socket
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 161, in load_module
    return self._importer.load_module(fullname, self._entry_name)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "socket.py", line 86, in <module>
    import os, sys, warnings
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 161, in load_module
    return self._importer.load_module(fullname, self._entry_name)
  File "/usr/local/lib/python2.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 395, in load_module
    exec(bytecode, module.__dict__)
  File "os.py", line 120, in <module>
    from os.path import (curdir, pardir, sep, pathsep, defpath, extsep, altsep,
ImportError: No module named path

**Comment by assslove** [comment]
spec list:
# -*- mode: python -*-

block_cipher = None


a = Analysis(['check_local.py'],
             pathex=['/data1/home/genryhou/DChecker/bin'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [], 
          name='check_local',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )

**Comment by htgoebel** [comment]
See https://github.com/pyinstaller/pyinstaller/issues/3609#issuecomment-402232126
> Turns out to be a path issue, was getting the wrong pyinstaller.

**Comment by htgoebel** [comment]
@assslove BTW: Please stop missusing the issue tracker as a forum. You already  Added a commetn to the original issue. Opening a new issue is wasting developers time. Thanks!
