### ISSUE TITLE
PyInstaller problems (images not displayed) on MacOSX

### ISSUE THREAD

**Issue by ekdmekdm** [pyinstaller/pyinstaller#4019]
Hello,

I realized an application that works very well under GNU / Linux and Windows (both the execution with the main script, as with the executable made with PyInstaller).
I would like the software to distribute under MacOSX ... and there I encounter a lot of difficulties by running my_application.app ; the last problem is that PNG, JPEG and GIF images are not deployed ... while executing the main script everything is ok.

I am under MacOSX Mavericks (virtualized under Kubuntu):

Python 3.6.7, PyQt 5.7.1 and Qt 5.7.1
PyInstaller : 3.5.dev0 + 260f04698
Platform : Darwin-13.4.0-x86_64-i386-64bit.
Python was installed with the package : python-3.6.7-macosx10.9.pkg ...
PyQt5 and PyInstaller with pip3. 

Should I install Python, PyQt5, ... PyInstaller with brew for it to work ?, it is better ?

This is my script for creating an executable (which works very well under GNU / Linux and Windows) ... and executables work well too (tested on other machines).

In my script of creation of executable I integrated a system of copy of the directories containing images, it works very well under GNU / Linux and under windows ... the directories in question are copied where the executable is.

My PyInstaller script :

https://pastebin.com/DEJxwaCD

The tree of my project :

https://pastebin.com/d9ef4CxY

The return of PyInstaller (no error detected):

https://pastebin.com/rLkCYNXd

Why so many difficulties with PyInstaller under MacOSX?

Can you help me ?

See you soon.

**Comment by htgoebel** [comment]
This looks like you eitehr did not pacakge all required images or did not adopt your application to be frozen. Please see https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly
