### ISSUE TITLE
Missed module if syntax error

### ISSUE THREAD

**Issue by pohmelie** [pyinstaller/pyinstaller#4021]
pyinstaller 3.4
python 3.6.5
windows 10/ubuntu 18.04

If imported module have syntax errors, it will be silently ignored.

mod.py:
``` python
def foo():
    await bar()
```
main.py:
``` python
from mod import foo
print(foo())
```

Builds successfully, but runtime:
```
$ ./dist/main
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from mod import foo
ModuleNotFoundError: No module named 'mod'
[10447] Failed to execute script main
```

Suggest to fail in build time in such cases.

**Comment by bjones1** [comment]
PyInstaller doesn't (and shouldn't) run the program being frozen, so it can't check for this class of errors.

**Comment by pohmelie** [comment]
@bjones1 
Okay, but why there is no syntax error but `ModuleNotFoundError`? I mean if pyinstaller blindly pack modules, why there is no `mod` inside?

**Comment by htgoebel** [comment]
@pohmelie Since the module is no t frozen. Have a look at the "warn.txt" file in the build directory. The buggy module should be listed there as an "InvalidSourcePackage" or something like this.

PyInstaller does not test xour program for you. It assumes you did your job prior to freezing.

**Comment by pohmelie** [comment]
@bjones1 
> PyInstaller doesn't (and shouldn't) run the program being frozen, so it can't check for this class of errors.

Actually, it call `compile`, so it can and do detect syntax errors. https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/lib/modulegraph/modulegraph.py#L2098

@htgoebel 
What is the reason for ignoring syntax broken files? If syntax error is in main file it is error, but syntax error in imported files is not. I understand, that there are conditional imports, but why not to include even broken files, so I will see actual error, not mystic `ModuleNotFoundError`?

We use pyinstaller to deploy our project to windows and I spent hour until I tried import module from python and saw syntax error exception. Of course this was mistake of committer, that there were no tests until push, but, informative errors counts.

**Comment by bjones1** [comment]
Without certainty on this, sometimes Python 2 and 3 sources are in the same tree, so an error in compiling might be OK (the appropriate module will be run-time imported). Hence, check your warnings.

**Comment by pohmelie** [comment]
@bjones1 
Since they are runtime dispatched, then nothing will go wrong if both will be added, but in my case I will see proper exception.

> Hence, check your warnings.

This can't be automated without huge time invest:
* They are "for human", no strict format (json, yaml, etc.) to parse them on CI process
* Can't distinguish "proper" syntax error (two files for py2 and py3 for example) and real syntax error of my code

**Comment by pohmelie** [comment]
Oh, I see... we can't add module since we can't compile it. But there is nice solution: compile module as raising `SyntaxError`. This requires modification of modulegraph.py at place linked above:
``` python
try:
    co = compile(contents, pathname, 'exec', ast.PyCF_ONLY_AST, True)
    if sys.version_info[:2] == (3, 5):
        # In Python 3.5 some syntax problems with async
        # functions are only reported when compiling to bytecode
        compile(co, '-', 'exec', 0, True)
except SyntaxError as e:
    co = compile(f"raise {e!r}", pathname, 'exec', ast.PyCF_ONLY_AST, True)
cls = SourceModule
```

Resulting binary for example in first post will produce output:
```
$ ./main/dist/main
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from mod import foo
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/home/broomrider/pro/kron/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "mod.py", line 1, in <module>
    def foo():
  File "/home/broomrider/pro/kron/pyinstaller/mod.py", line 2
    await bar()
            ^
SyntaxError: invalid syntax
[6499] Failed to execute script main
```

I think this looks promising.

**Comment by htgoebel** [comment]
As bjohones already wrote: If PyInstaller would fail on a syntax error in some module, it would be impossible to have Py2 and Py3 code in the same source-package. Since the package would (conditionally) import both versions, PyInstaller would, too, then raise teh syntax error and quit. This is nnot what you want. Better ensure your code does not contain syntax errors prior to freezing.
