### ISSUE TITLE
BUG！！！

### ISSUE THREAD

**Issue by dlml** [pyinstaller/pyinstaller#4024]
![default](https://user-images.githubusercontent.com/35597616/51906366-fa543a00-23fe-11e9-8fc6-840d62eab428.png)
![default](https://user-images.githubusercontent.com/35597616/51906386-03450b80-23ff-11e9-9a0f-6e5cb539db7f.png)

**Comment by bjones1** [comment]
Follow https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs first.

**Comment by htgoebel** [comment]
@dlml You should learn hot to report bugs. Posting pictures is very, very unfriendly, we will not help you!

**Comment by QiPython** [comment]
I got the same problem，have u fixed this?
