### ISSUE TITLE
Fatal Python error: Py_Initialize: Unable to get the locale encoding

### ISSUE THREAD

**Issue by mitsuix** [pyinstaller/pyinstaller#4025]
Fatal Python error: Py_Initialize: Unable to get the locale encoding
zipimport.ZipImportError: can't find module 'encodings'

My script is very simple,just one line:
print("hello")
I can run pyinstaller successfully, but when I run./hello, the above  error occurs.
Can you help me with this?

env:python3.5.6+ubuntu16.04

Thank you a lot~

**Comment by htgoebel** [comment]
Please follow [How-to-Report-Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) first.

**Comment by mitsuix** [comment]
I tried other computer, it works.

Maybe some envs in my computer confilt with pyinstaller.

3ks~
