### ISSUE TITLE
WORKAROUND: pip 19 - No module named 'PyInstaller'

### ISSUE THREAD

**Issue by bcarroll** [pyinstaller/pyinstaller#4028]
The related issues (#2730 and #4003) have been closed, but I wanted to share this workaround that worked for me.

In the pyinstaller/setup.py file, add this line after the `from __future__ import print_function` line:
`import sys; sys.path.append('.')`

That should allow `pip install .` to successfully install pyinstaller with pip 19

**Comment by htgoebel** [comment]
See #4007
