### ISSUE TITLE
Can't package program with azure.storage.blob installed from github

### ISSUE THREAD

**Issue by ddzialak** [pyinstaller/pyinstaller#4036]
PyInstaller fails to package azure-storage-blob project installed from github:

Steps to reproduce:
```
mkvirtualenv tpyi -p `which python3.6`
pip install -e 'git://github.com/Azure/azure-storage-python.git#egg=azure-storage-blob&subdirectory=azure-storage-blob'
pip install pyinstaller
pyinstaller --onedir t.py
```
 NOTE: installing last devel doesn't work, see #4035 

Running `t.py` that uses azure-storage-blob in created virtual environment works properly but running `build/t/t` fails with `ModuleNotFoundError: No module named 'azure.storage.common'`. File `build/t/warn-t.txt` has information about missed module: `azure.storage.common` but that module is installed(!)

All works properly when installing `azure-storage-blob` directly from `PyPi`:
```
- pip install -e 'git://github.com/Azure/azure-storage-python.git#egg=azure-storage-blob&subdirectory=azure-storage-blob'
+ pip install azure-storage-blob
```

My guess the reason when it fails is that `azure.storage.blob` depends on `azure.storage.common` and `azure.common` that are installed in different paths:
```
(tpyi) dzialak@tad-38 ~/PycharmProjects/pyinstaller_bug $ python -c 'import azure; print(azure.__path__)'
['/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure', '/home/dzialak/.virtualenvs/tpyi/lib/python3.6/site-packages/azure']
```
and that cause that PyInstaller can't find `storage` module because it tried to find it in first found `azure` (from `azure.common`):
```
4050 TRACE: safe_import_module 'azure' 'azure' None
4050 TRACE: safe_import_module -> Package('azure', '/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure/__init__.py', ['/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure'])
4050 TRACE: find_head_package -> (Package('azure', '/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure/__init__.py', ['/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure']), 'common')
4050 TRACE: load_tail Package('azure', '/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure/__init__.py', ['/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure']) 'common'
4050 TRACE: safe_import_module 'common' 'azure.common' Package('azure', '/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure/__init__.py', ['/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure'])
4050 TRACE: _find_module_path <- 'azure.common' ['/home/dzialak/.virtualenvs/tpyi/src/azure-storage-blob/azure-storage-blob/azure']
4050 TRACE: _find_module_path -> None
4050 TRACE: safe_import_module -> None (ImportError("No module named 'common'",)) 
```

**Comment by ddzialak** [comment]
```from azure.storage.blob import BlockBlobService, PublicAccess

block_blob_service = BlockBlobService(account_name='devstoreaccount1',
                                      account_key='any=',
                                      protocol='http', custom_domain='localhost:10000', is_emulated=True,
                                      endpoint_suffix='http://127.0.0.1:10000/devstoreaccount1')

for c in block_blob_service.list_containers():
    print(c.name)
```

**Comment by ollamh** [comment]
Hi @ddzialak , have you got any solution to this issue? I'm using azure-storage-blob and azure-indentity installed via PyPI and I see similar issue.

**Comment by ddzialak** [comment]
In my case azure-* libraries are installed from `PyPi` and it works (problem was, when I've tried to install them directly from github).
Currently using versions:
```
Python              3.11.5
azure-core               1.27.1
azure-storage-blob       12.16.0
PyInstaller              5.13.0
```

**Comment by bwoodsend** [comment]
What if you get rid of the `-e` flag to pip? Editable installs for `pyproject.toml` based projects are known to be undiscoverable by PyInstaller (#7524).

**Comment by ollamh** [comment]
In my case I'm packing app for windows by using wine inside docker in gitlab ci. The azure packages are not installed as editable apps, just regular poetry install. The issue was that some packages were installed at system wide level and some inside poetry virtualenv, so pyinstaller probably couldn't look in both paths. Got configured poetry to install packages system wide and that did it.

**Comment by bwoodsend** [comment]
That's expected and nothing to do with this issue then. If PyInstaller is not installed into the same environment as your packages then there's no way for it to find them.

**Comment by bwoodsend** [comment]
In the absence of any comment to the contrary, I'll assume that this is just #7524 again.
