### ISSUE TITLE
atexit doesn't work under latest svn release on windows

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#404]
**Original date**: 2011/08/19
**Original reporter**: *jeremy AND jeremysanders DOT net*

Functions registered by atexit do not appear to be called on exit of the program, using the latest svn release on Windows. I'm using Python 2.7.

Attached is an example program.

**Comment by matysek** [comment]
Please test this with python3 branch and reopen this issue if it is still not fixed there.
