### ISSUE TITLE
Dark mode support for macos with Qt5

### ISSUE THREAD

**Issue by prsolucoes** [pyinstaller/pyinstaller#4043]
Hi,

Im trying make dark mode works with pyside2 latest version. 

If i run manually, it works:

```
python3 main.py
```

![image](https://user-images.githubusercontent.com/395096/52241068-ed7d8d80-28b9-11e9-9702-7111c262288e.png)

But if i generate app with pyinstaller, it doesnt work, but assume light gray color:

![image](https://user-images.githubusercontent.com/395096/52241138-0f771000-28ba-11e9-9292-c77d3b3c50be.png)

Im using branch "develop" and install it manually with:

```
python3 setup.py install
```

Can anyone help me?

**Comment by htgoebel** [comment]
Obviously this is not relaqted to PyInstaller but to OS X only.
