### ISSUE TITLE
Shiboken2 not found when using PySide2

### ISSUE THREAD

**Issue by prsolucoes** [pyinstaller/pyinstaller#4044]
Hi,

Im using the branch "develop" of pyinstaller and creating a sample app with PySide2.

Everything is working and the application works too. 

But on log i see:

```
...
...
...
9985 INFO: Looking for ctypes DLLs
10025 INFO: Analyzing run-time hooks ...
10032 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
10045 INFO: Including run-time hook 'pyi_rth_pkgres.py'
10046 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
10061 INFO: Looking for dynamic libraries
10288 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /usr/local/lib/python3.7/site-packages/PySide2/QtWidgets.abi3.so)
10291 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /usr/local/lib/python3.7/site-packages/PySide2/QtGui.abi3.so)
10295 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /usr/local/lib/python3.7/site-packages/PySide2/QtCore.abi3.so)
10330 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /usr/local/lib/python3.7/site-packages/PySide2/QtNetwork.abi3.so)
10406 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /usr/local/lib/python3.7/site-packages/PySide2/libpyside2.abi3.5.12.dylib)
10472 INFO: Looking for eggs
...
...
...
```

I got error:

```
ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib
```

But it exists inside the folder "/usr/local/lib/python3.7/site-packages/shiboken2":

```
$ find / -name libshiboken2.abi3.5.12.dylib  

/usr/local/lib/python3.7/site-packages/shiboken2/libshiboken2.abi3.5.12.dylib
```

Anyone can help me with this?

Thanks.

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by htgoebel** [comment]
So it work when *not* using PySide. Try to find out what is different when using PySide.

**Comment by prsolucoes** [comment]
Hi,

I know that open source project owner don't have time, like me that have a lot (github.com/prsolucoes and ezored.com), but i first search and try a lot to find the problem. 

I think that is an internal problem of hook or pyinstaller (i dont know). I have added the folder of required .dylib but the same problem happen:

```
pathex=[        
        '/usr/local/lib/python3.7/site-packages/shiboken2',
        current_path,
],
```

Second, i put the desired .dylib into pyside2 folder like in the error message, and it work:

```
cp /usr/local/lib/python3.7/site-packages/shiboken2/libshiboken2.abi3.5.12.dylib /usr/local/lib/python3.7/site-packages/PySide2/
```

But i think that has a problem when find the dylib, since it exists in correct folder "/usr/local/lib/python3.7/site-packages/shiboken2".

Thanks anyway.

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing. Then we'd apprechiate if you'd provide a hook.

**Comment by Vyeadiai** [comment]
I am also experiencing this issue using pyinstaller with PySide2/QtQuick

**Comment by Vyeadiai** [comment]
Still spinning my wheels on this one

```
Thrive-MacBook-Air:client thrive$ pyinstaller --onefile main.py 
183 INFO: PyInstaller: 3.4
183 INFO: Python: 3.6.8
192 INFO: Platform: Darwin-18.5.0-x86_64-i386-64bit
193 INFO: wrote /Users/thrive/repos/cell_report_app/client/main.spec
196 INFO: UPX is not available.
199 INFO: Extending PYTHONPATH with paths
['/Users/thrive/repos/cell_report_app/client',
 '/Users/thrive/repos/cell_report_app/client']
199 INFO: checking Analysis
199 INFO: Building Analysis because Analysis-00.toc is non existent
199 INFO: Initializing module dependency graph...
203 INFO: Initializing module graph hooks...
208 INFO: Analyzing base_library.zip ...
4132 INFO: running Analysis Analysis-00.toc
4145 INFO: Caching module hooks...
4151 INFO: Analyzing /Users/thrive/repos/cell_report_app/client/main.py
4723 INFO: Loading module hooks...
4723 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
4726 INFO: Loading module hook "hook-sqlite3.py"...
4824 INFO: Loading module hook "hook-PySide2.QtQml.py"...
4867 INFO: Loading module hook "hook-PySide2.QtGui.py"...
6058 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
6223 INFO: Loading module hook "hook-encodings.py"...
6307 INFO: Loading module hook "hook-PySide2.QtCore.py"...
6474 INFO: Loading module hook "hook-PySide2.py"...
6701 WARNING: Hidden import "numpy.core.multiarray" not found!
6702 INFO: Loading module hook "hook-xml.py"...
6977 INFO: Loading module hook "hook-pydoc.py"...
6979 INFO: Loading module hook "hook-PySide2.QtQuick.py"...
6984 ERROR: Cannot find QT_INSTALL_QML directory, "qmake -query QT_INSTALL_QML" returned nothing
7284 INFO: Looking for ctypes DLLs
7303 INFO: Analyzing run-time hooks ...
7306 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
7309 INFO: Including run-time hook 'pyi_rth_qml.py'
7315 INFO: Looking for dynamic libraries
7981 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtCore.abi3.so)
7984 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtNetwork.abi3.so)
7998 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtWidgets.abi3.so)
8005 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtGui.abi3.so)
8010 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtQml.abi3.so)
8013 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/QtQuick.abi3.so)
8331 ERROR: Can not find path ./libshiboken2.abi3.5.12.dylib (needed by /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PySide2/libpyside2.abi3.5.12.dylib)
8334 INFO: Looking for eggs
8334 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.6/Python
8337 INFO: Warnings written to /Users/thrive/repos/cell_report_app/client/build/main/warn-main.txt
8370 INFO: Graph cross-reference written to /Users/thrive/repos/cell_report_app/client/build/main/xref-main.html
8436 INFO: checking PYZ
```

**Comment by karolyi** [comment]
Same here, but with bundling a package on windows. I get the missing import error when trying to use PySide2. It seems that `shiboken2` is somehow not packaged right:

```python
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", line 47, in <module>
ModuleNotFoundError: No module named 'PyQt5'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_qt5plugins.py", lin
e 49, in <module>
  File "c:\users\user\work\project\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "lib\site-packages\PySide2\__init__.py", line 51, in <module>
  File "lib\site-packages\PySide2\__init__.py", line 21, in _setupQtDirectories
ImportError: DLL load failed: The specified module could not be found.
[3780] Failed to execute script pyi_rth_qt5plugins
```

This traces back to https://code.qt.io/cgit/pyside/pyside-setup.git/tree/sources/pyside2/PySide2/__init__.py.in?h=5.12.2#n21

This is where I give up now. Any suggestions?

**Comment by karolyi** [comment]
Alright, this seems to be an issue of `shiboken2`, not pyinstaller itself. After investigating some more, I found out that other than windows 8.1, windows 7 and windows 10 can import `shiboken2`. I'll try to open an issue for for `shiboken2`.

**Comment by karolyi** [comment]
For anyone interested, here's the PySide2 shiboken2 issue: https://bugreports.qt.io/browse/PYSIDE-1002

**Comment by bjones1** [comment]
Closing per @karolyi.

**Comment by mwfong** [comment]
Re: https://github.com/pyinstaller/pyinstaller/issues/4044#issuecomment-487375312 and https://github.com/pyinstaller/pyinstaller/issues/4044#issuecomment-487383245, I'm seeing the same failure but think it _is_ pyinstaller-specific.  Under Windows 10, Python 3.6.8 successfully independently runs 'import shiboken2'. However, the pyinstaller dist/*.exe runs on the build platform but fails with a 'DLL load failed' error on the _non-development_ (viz., clean) machine.

**Comment by AbhimanyuHK** [comment]
Still getting for `PySide2==5.15.0`

```
$ pyinstaller --onefile pyside2_main.py

122 INFO: PyInstaller: 3.6
122 INFO: Python: 3.7.2
124 INFO: Platform: Windows-10-10.0.18362-SP0
126 INFO: wrote pyside2_main.spec
135 INFO: UPX is not available.
137 INFO: checking Analysis
137 INFO: Building Analysis because Analysis-00.toc is non existent
137 INFO: Initializing module dependency graph...
145 INFO: Initializing module graph hooks...
148 INFO: Analyzing base_library.zip ...
5468 INFO: running Analysis Analysis-00.toc
5505 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by venv\scripts\python.exe
5533 INFO: Caching module hooks...
5546 INFO: Analyzing pyside2_main.py
6030 INFO: Processing pre-safe import module hook   six.moves
7026 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
9034 INFO: Loading module hooks...
9035 INFO: Loading module hook "hook-boto3.py"...
10674 INFO: Loading module hook "hook-botocore.py"...
11070 INFO: Loading module hook "hook-encodings.py"...
11248 INFO: Loading module hook "hook-pydoc.py"...
11250 INFO: Loading module hook "hook-PySide2.py"...
11467 WARNING: Cannot read QLibraryInfo output: raised Expecting value: line 1 column 1 (char 0) when decoding:
PySide2/__init__.py: Unable to import shiboken2 from , 

```

**Comment by Ri773r** [comment]
Environment:
`Python3.7.5`  
`PySide2==5.15.0`   
`PyInstaller==3.6`  
 `shiboken2==5.15.0`
this problem still exists
![NSTXIH.png](https://s1.ax1x.com/2020/06/14/NSTXIH.png)
I have included the shiboken2 module in the spec file, and the compiled folder can also find shiboken2.pyd, but the error is still reported
[![NSTRZF.png](https://s1.ax1x.com/2020/06/14/NSTRZF.png)](https://imgchr.com/i/NSTRZF)

**Comment by karolyi** [comment]
@Ri773r, it's a strange coincidence but I encountered this error today again, when I went to touch on one of my Qt projects.  I even had a former bugreport at the Qt official issue list (linked above).

The solution seems to be to use a newer version of Python. Shiboken seems to be super sensitive to the Python version you use. I had 3.7.7 from the Windows store, and the problem disappeared when I updated to 3.8.8 (also from the windows store). Guys from Qt said you can also give it a go with an installed version from python.org (non windows store version).

Upgrading to 3.8 from 3.7 should not be an issue, not much has changed there.

**Comment by karolyi** [comment]
Addition: PyInstaller started to fail compiling a usable binary, it will complain about a missing shiboken binary. PySide 5.15 might have changed some code around how it detects its shiboken, [looking at the code](https://code.qt.io/cgit/pyside/pyside-setup.git/tree/sources/pyside2/PySide2/__init__.py.in#n21) I realized you need to copy over your locally installed shiboken2 directory from under your virtual environment.

In my case, I achieved it with adding it as a `data` entry in the `Analysis` instantiation:

```
    datas=[
        ('venv/Lib/site-packages/shiboken2', 'shiboken2'),
    ],

```

This will copy the entire shiboken2 directory into the `dist` directory that PyInstaller creates, and thus PySide will be able to start.

**Comment by karolyi** [comment]
So now it seems the `QtCore.dll` from `PySide2==5.15.0` is not recognized in the built binary directory. I'm kinda stuck here:

`ImportError: DLL load failed while importing QtCore: The specified module could not be found.`

**Comment by Ri773r** [comment]
@karolyi ok,I'll try your suggestion, thank you

**Comment by karolyi** [comment]
I can't get the  `PySide2==5.15.0` version to work.

Version `PySide2==5.14.2.2` (the last before `5.15`. basically) will work, with the aforementioned copying over of the shiboken2 libs, AND using python 3.8.

**Comment by Ri773r** [comment]
@karolyi hi, I tried your suggestion，Add the following code to the spec file under Python 3.7.5, but unfortunately, he still reported an error
```
datas=[
        ('venv/Lib/site-packages/shiboken2', 'shiboken2'),
    ],
```
Then I didn't try to upgrade Python (for some special reasons), by chance, I saw another issue
https://github.com/pyinstaller/pyinstaller/issues/4913#issuecomment-641621169
he said the latest PySide2/Shiboken2 on PyPI don't have Qt statically compiled in, the last version that does is PySide2==5.14.2.Then I tried to downgrade Pyside2 to 5.14.2 and then repackaged using Pyinstaller, the magic is that it worked.I don’t know if this is a BUG, but I’m lucky to find the answer, thank you and him again

**Comment by karolyi** [comment]
@Ri773r if you read the comments I made after my initial reply, you'll see that I bumped into the same problem. Python3.8 and PyInstaller will work only with PySide 5.14.x, unfortunately.

**Comment by rokm** [comment]
I was looking into similar problem with the latest PySide2 (`5.15.0`) and Python 3.8.3.

The application was working fine on the development machine (where it was frozen), but on the test deployment VM, it gave the following error: `ImportError: DLL load failed while importing QtCore: The specified module could not be found.`

It turned out that Qt `5.15.0` shipped with PySide2 is (among other) linked against `MSVCP140.DLL`, `MSVCP140_1.DLL`, `VCRUNTIME140.DLL`, and `VCRUNTIME140_1.DLL`. Of these four files, `MSVCP140_1.DLL` is missing from the dist directory.

Installing [the latest VC runtime](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) fixed the issue on deployment VM (since the missing DLLs is then found in system path; on development machine, this has already been installed before). Alternatively, the file could be copied into the dist directory (which is probably what PyInstaller should be doing).

(For the reference, Qt5 shipped with PySide2 `5.14.x` is not linked against `MSVCP140_1.DLL', and therefore does not have this problem).

**Comment by karolyi** [comment]
@rokm this is very helpful, thank you. I'll store the link of your comment for myself for later reference.

**Comment by MikeBusuttil** [comment]
Had the same problem.  Upgrading Python from 3.6 to 3.9 fixed the issue for me
