### ISSUE TITLE
Force executable to use specific dll instead of environment dlls

### ISSUE THREAD

**Issue by masoudr** [pyinstaller/pyinstaller#4050]
Hi,
I'm using python3.7 X64 with PyInstaller v3.4.
I'm trying to release a simple app with `PyInstaller` to work on windows7-X64 without any dependencies like VCRedist. In my build PC, I installed VCRedist 2015 and generated executable normally (not standalone). The windows redist dll files (api-ms-win*) was included as expected in the generated directory and it worked fine on the target machine (Windows7). Then I tried to generate a standalone app but this time when I executed it on target machine I got this error:

> The procedure entry point ucrtbase_putch couldnot be located in the dynamic link library api-ms-win-crt-conio-l1-1-0.dll.

I checked the generated Temp folder (_MEI*) and found out that the right dlls are right there and somehow the executable cannot use them. I created a copy of (_MEI*) folder and put the standalone executable next to it and surprisingly it worked. So It seems that some of those dlls exist in the windows directory of the target machine and it is trying to load them instead of (_MEI*) directory. I search and found that some of them exist in `C:\Windows\winsxs\amd64...`.
I'm not sure if this is the problem but I need to generate a standalone executable with any dependencies.
I also found out that if I add the (_MEI*) directory to system path, the executable would run without any problem.
Thanks.

**Comment by ohk2kt3t4** [comment]
Did you ever figure this one out?

**Comment by masoudr** [comment]
@ohk2kt3t4 No I didn't. I think those DLLs should be first removed from environment variables before the app starts.

**Comment by try-6-me** [comment]
I have the exactly same problem I really don't know what to do more

**Comment by masoudr** [comment]
@try-6-me I really forgot how did I fix the problem but one solution that I think will work is to add the DLLs manually to the PyInstaller local path (e.g. `C:/Users/<User>/AppData/Roaming/PyInstaller/bincache**`) and PyInstaller would take those DLLs first. This should fix any potential environment pick-up problems.

**Comment by bwoodsend** [comment]
I imagine the original issue was mopped up in #5778 and #5770. @try-6-me What are your Python/OS versions? Trying to run something built with Python 3.9 on Windows 7 or 8 or even older Windows 10s can cause a similar error.

**Comment by try-6-me** [comment]
Sorry for the delay I'm not really used to github.

When I try to execute the .exe I got a missing dll and a pop up box where I need to click the ok button, then the dll is found and loaded.

I'm on Python3.7 and I'm trying to build something for windows 10, I'm using pyinstaller from wine 6.0 running from debian 10 thus I think the problem, I will try @masoudr solution.

> I imagine the original issue was mopped up in #5778 and #5770. @try-6-me What are your Python/OS versions? Trying to run something built with Python 3.9 on Windows 7 or 8 or even older Windows 10s can cause a similar error.
