### ISSUE TITLE
PyQt5 imports require original Qt install location to be present

### ISSUE THREAD

**Issue by gehlhaarPfizer** [pyinstaller/pyinstaller#4052]
The PyQt5 hooks query the QLibraryInfo class to detect the installation location of the Qt binaries. This location isn't always available. In my case, Qt is built on one computer, then the various include and binary files are put in a repository. The builds happen on a "pristine" computer where the repository is pulled via an automated process and the build proceeds from there.

Qt has a mechanism for redirecting these hard-coded paths via the "qt.conf" file; see http://doc.qt.io/qt-5/qt-conf.html

However, given how PyInstaller is invoking QLibraryInfo, the qt.conf is not utilized. Specifically, a QCoreApplication object needs to be present because QCoreApplication::applicationDirPath() is used.

It took a lot of tinkering, and diving into both the Qt and PyInstaller source code to figure this out, but the fix is simple. In the Qt source code it does this check:

    if (QCoreApplication::instance()) {
        QDir pwd(QCoreApplication::applicationDirPath());
        qtconfig = pwd.filePath(QLatin1String("qt.conf"));
        if (QFile::exists(qtconfig))
            return new QSettings(qtconfig, QSettings::IniFormat);

This check always returns 'false' for the PyInstaller check because no QCoreApplication object exists.

In 'qt.py' in PyInstaller:

                # exec_statement only captures stdout. If there are
                # errors, capture them to stdout so they can be displayed to the
                # user. Do this early, in case PyQt5 imports produce stderr
                # output.
                sys.stderr = sys.stdout

                import json
                from %s.QtCore import QLibraryInfo

                paths = [x for x in dir(QLibraryInfo) if x.endswith('Path')]
                location = {x: QLibraryInfo.location(getattr(QLibraryInfo, x))
                            for x in paths}

If you insert an instantiation of QCoreApplication, e.g.
               from PyQt5.QtCore import QCoreApplication
               coreApp = QCoreApplication([""])

before the calls to QLibraryInfo, the qt.conf file gets read properly and the new paths are used.

**Comment by bjones1** [comment]
This should already be fixed in the develop branch.

**Comment by gehlhaarPfizer** [comment]
Verified.
