### ISSUE TITLE
Executable failed with ModuleNotFoundError: No module named 'cymem'

### ISSUE THREAD

**Issue by erotavlas** [pyinstaller/pyinstaller#4053]
Hello,
I used pyinstaller to package a simple test script that uses spaCy on a Windows 10 machine.

```
import spacy
import io
import sys
ner_model = spacy.load("C:/en_core_web_lg-2.0.0")
while True:
	a = input();
	if a == 'q':
		break;
	else:
		doc = ner_model(a)
		ent = doc.ents[0];
		print(ent.text, ent.start_char, ent.end_char, ent.label_);
```

It seemed to create the executable without problems in the 'dist' folder.  But when I went to run the executable it failed with the following error

```
Traceback (most recent call last):
  File "ner.py", line 1, in <module>
  File "d:\anaconda3\envs\spacy\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\spacy\__init__.py", line 8, in <module>
  File "d:\anaconda3\envs\spacy\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\thinc\neural\__init__.py", line 1, in <module>
  File "d:\anaconda3\envs\spacy\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\thinc\neural\_classes\model.py", line 11, in <module>
  File "d:\anaconda3\envs\spacy\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\thinc\neural\util.py", line 3, in <module>
  File "cymem.pxd", line 4, in init preshed.maps
ModuleNotFoundError: No module named 'cymem'
[11744] Failed to execute script ner
```

Any ideas how to go about fixing this?

I'm running everything in a conda environment with python version 3.6.8 ans spacy version .2.0.16.
And pyinstaller installed from pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip

**EDIT**:  I tried doing conda update --all then rebuilding the package, but I got the same result as before after running the exe

**Comment by luke4u** [comment]
Hi erotavlas, i am getting the same error. wondering if you may have solved it? may I ask how you solved the problem? Thanks so much.

**Comment by erotavlas** [comment]
I got a bit further.  Using spacy version 2.0.18 I ran the following command based on this issue 
https://github.com/explosion/spaCy/issues/2536

`pyinstaller ner.py --hidden-import cymem.cymem --hidden-import thinc.linalg --hidden-import murmurhash.mrmr --hidden-import cytoolz.utils --hidden-import cytoolz._signatures --hidden-import spacy.strings --hidden-import spacy.morphology --hidden-import spacy.lexeme --hidden-import spacy.tokens --hidden-import spacy.gold --hidden-import spacy.tokens.underscore --hidden-import spacy.parts_of_speech --hidden-import dill --hidden-import spacy.tokens.printers --hidden-import spacy.tokens._retokenize --hidden-import spacy.syntax --hidden-import spacy.syntax.stateclass --hidden-import spacy.syntax.transition_system --hidden-import spacy.syntax.nonproj --hidden-import spacy.syntax.nn_parser --hidden-import spacy.syntax.arc_eager --hidden-import thinc.extra.search --hidden-import spacy.syntax._beam_utils --hidden-import spacy.syntax.ner --hidden-import thinc.neural._classes.difference --hidden-import spacy.vocab --hidden-import spacy.lemmatizer --hidden-import spacy._ml`

I had to add each module it said it could not find manually to the command until it finally found all of them.

I was also getting this error 

```
Exception:
            Cannot find existing PyQt5 plugin directories
            Paths checked: C:/qt64/qt_1544645195969/_h_env/Library/plugins
```
and I solved that by running `pip install PyQt5` in my conda environment

so then finally package builds but when i run the executable I'm getting a different error 

```
Traceback (most recent call last):
  File "ner.py", line 6, in <module>
  File "site-packages\spacy\__init__.py", line 21, in load
  File "site-packages\spacy\util.py", line 109, in load_model
OSError: [E049] Can't find spaCy data directory: 'None'. Check your installation and permissions, or use spacy.util.set_data_path to customise the location if necessary.
[29396] Failed to execute script ner
```
Well that is discussed in the link above, but I don't understand their solution at the moment

**Comment by rajbala** [comment]
I am also trying to use pyinstaller with spacy and running into issues.  I get the following error:

>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "gold.pyx", line 13, in init spacy.gold
> ImportError: cannot import name _align

I have added a bunch of imports using hidden_imports, but _align is imported within gold.pyx using this format:

`from . import _align`

So the hidden imports setting doesn't help for that module.  I have tried this using pyinstaller 3.4 and the latest dev version of 3.5 to no avail.  This is all being built on Windows 10.

Any thoughts?

**Comment by erotavlas** [comment]
@rajbala  Which version of spacy?

**Comment by rajbala** [comment]
Holy smokes!  That worked!  Thank you kindly!  

I am using spacy 2.1.4 btw.

**Comment by htgoebel** [comment]
I'm closing this issue as it is solved.

Anyway we would appreciate if you'd submit a pull-request for a hook for `spacy.gold`. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.
