### ISSUE TITLE
pyqt5+QsciScintilla don't work pyinstaller  

### ISSUE THREAD

**Issue by Pirnazar** [pyinstaller/pyinstaller#4055]
Hello. I write project in pyqt5 with using QsciScintilla(PyQt5.Qsci). When I create exe file with pyinstaller, i see error "Failed to execute script blabla.py". I try --hidden-import=PyQt5.Qsci but it's don't work.

**Comment by Hemmelfort** [comment]
Try this:
`--hidden-import=PyQt5.QtPrintSupport`

**Comment by SteveDoyle2** [comment]
Not the OP, but I just tried this and it worked.  I also have the PyQt5.Qsci as a hidden import, but I'm not sure if that's required.

**Comment by santosh1432007** [comment]
Hello everyone, 

I have installed PyInstaller 3.4 and PyQt5 5.13.0 in virtual environment. I wonder why PyInstaller is not able to support Scintilla . Just a line from PyQt5.Qsci import * in python. The created execuatble doesn't support the script.  Without that line it works fine. I want to create an executable for QSciScintilla and support for customelexer. Please let me know, how can I fix. Thanks a lot in advance.

**Comment by bjones1** [comment]
Closing -- QScintilla isn't supported. PRs are welcome.
