### ISSUE TITLE
At the time of executing .exe ImportError: Missing requiered dependencies : ['numpy']

### ISSUE THREAD

**Issue by Jor-G-ete** [pyinstaller/pyinstaller#4056]
I'm kind of a newbie in python and building .exe from a .py. So excuse me for the possible mistakes.

I made a little python program ,in order to extract data( csv files  )from a several compressed gzip files using pandas , gzip and shutil  libraries. Once they are extracted the csv files are joined in one big  csv unique file. 

My program supports python versions **2.7** and **3.7**.

At the time of building a .exe due to make easier the use of these  little program and also compatible with computers which doesn't have  python installed, i'm making mistakes because it doesn't work.  This is the main folder in which i'm executing the .exe i got from  pyinstaller.
![imagen](https://user-images.githubusercontent.com/40428136/52411646-d074d480-2adc-11e9-9623-22d565630c28.png)

Note: The dat1 and dat2 are gzip  wihtout extension which inside them there are just one .csv file without exetension either.

***Do you have any idea, problem related or a way of solving this?***

This is what I obtained from the terminal at the time of real execution: 
![imagen](https://user-images.githubusercontent.com/40428136/52410787-d0bfa080-2ad9-11e9-9a48-1a1c88e33e30.png)

Terminal command to create the .exe:

```
pyinstaller.exe --clean --onefile Convierte_Rar_En_Csv_Final.py --name Transforma2 --hidden-import numpy
```

Versions: 

* ` Python : 2.7.15`
* ` pyinstaller: 3.4` ( for installing this library , i just downloaded the folder from here: <https://www.pyinstaller.org/downloads.html>  , then move it to  C:\YourPythonEnviroment\Lib\site-packages\PyInstaller-3.4, and finally  made from the terminal once I'm inside the folder PyInstaller-3.4 `python setup.py install` ) 
* ` pandas: 0.24.0`
* `numpy: 1.16.0` 
* `pytz: 2018.9`
* `wxPython 4.0.4`
* `setuptools: 40.8.0` 
* ` python-dateutil: 2.8.0 `

Code of my program:

```py
def DescomprimeYUne(path):
    import pandas as pd
    import gzip , shutil
    import numpy

    results = pd.DataFrame([])

    for filename in os.listdir(path):
        pathFile = path + filename
        if filename != __file__.split("/")[-1] and not os.path.isdir(pathFile):
            # # Descomprimo fichero
            with gzip.open(pathFile, 'rb') as f_in:
                with open(pathFile + '.csv', 'wb') as f_out:
                    shutil.copyfileobj(f_in, f_out)

            # Borro fichero original
            os.remove(pathFile)

            # Concateno a CSV final
            namedf = pd.read_csv(pathFile + ".csv", skiprows=0)
            results = results.append(namedf)

           # Borro fichero csv
           os.remove(pathFile + '.csv')

    results.to_csv(path + "final.csv")
if __name__ == "__main__":
DescomprimeYUne("./")
```

I followed also this tutorial: <https://github.com/pyinstaller/pyinstaller/issues/1886> but it didn't work for me.

**Thank you very much in advance**

Any other information that you need just ask me :) .

I'll leave here the files i used and aslso with my python program which uncompress , extract and join them into one single csv.

[ExtractData.zip](https://github.com/pyinstaller/pyinstaller/files/2840784/ExtractData.zip)

**Comment by lstolcman** [comment]
Making import in a function looks suspicious for me

I doubt `--hidden-import numpy` is necessary

**Comment by Jor-G-ete** [comment]
It worked!! Thanks a lot!
