### ISSUE TITLE
Failing CI tests on Python 2.7

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#4060]
I noticed that the CI tests on Appveyor and Travis have started failing on Python 2.7. @htgoebel, I see you've made a few commits to look at this. If you've already solved it, let me know so I can stop spending time on it. Here are my notes;  any thought you have would be welcome.

1. The last Travis CI that passed was build [3038](https://travis-ci.org/pyinstaller/pyinstaller/builds/478402122). Failures started with [3847](https://travis-ci.org/pyinstaller/pyinstaller/builds/484273158). However, there are no significant changes to the code (only e984fe18bdd85b45ed24dad62ac88cd3cb9c5e03) between these two commits.
1. Since Appveyor is failing in a similar way, I don't think the failures results from a build system change or something non-Python-related in the environment.
1. I re-ran the Travis CI on the last passing commit (0d289e49bf28b2e3717e090499884a94cefa6d3e) and it failed (see build [295](https://travis-ci.org/bjones1/pyinstaller/builds/491156786). Therefore, the failure is caused by something in the environment, not in the repo.
1. Looking at these two builds of the same commit, the differences I see are in the installed packages. Here are a list only of differing packages between the two CI runs. (This was manually generated; there may be errors.)

    Fails: pip-19.0.2 setuptools-40.8.0 atomicwrites-1.3.0 configparser-3.7.1 dis3-0.1.3 entrypoints-0.3 flake8-3.7.5 functools32-3.2.3.post2 lxml-4.3.1 psutil-5.5.0 pycodestyle-2.5.0 pyflakes-2.1.0 pytest-4.2.0 pytest-drop-dup-tests-0.1.0 pytest-forked-1.0.1 pytest-xdist-1.26.1 typing-3.6.6

    Works: pip-18.1 setuptools-40.6.3 atomicwrites-1.2.1 configparser-3.5.0 dis3-0.1.2 flake8-3.6.0 lxml-4.3.0  psutil-5.4.8 pycodestyle-2.4.0 pyflakes-2.0.0 pytest-4.1.0 pytest-drop-dup-tests-0.1.0 pytest-forked-0.2 pytest-xdist-1.25.0

1. Given that the first failing build involving pinning pip to < 19.0, I doubt pip's version causes the failure.
1. On my Windows PC, I downgraded my Python 2 setup to the passing packages, but the test still fails.

One thing this points to: instead of a manually-maintained list, we should be using `pip freeze` so that any version changes will be known.

**Comment by htgoebel** [comment]
@bjones1 Yes, I have been working on this, expect a workaround to be merged tomorrow latest. This is an issue introduced in pytest-xdist-1.26.0, see https://github.com/pytest-dev/pytest-xdist/issues/414.

**Comment by bjones1** [comment]
Thanks! This one had my mystified. I'm not sure why a local revert to older pytest-xdist failed. Thanks again for the debug effort.

**Comment by cclauss** [comment]
Was this issue fixed?

**Comment by bjones1** [comment]
Yes, thanks for the reminder.
