### ISSUE TITLE
Symantec antivirus finds virus SONAR.Heuristic.159 in the compiled file

### ISSUE THREAD

**Issue by Vlone12536** [pyinstaller/pyinstaller#4062]
Hello, I compiled my code into one file (pyinstaller -F -i file.ico file.py) on Windows 7, I use Python 3.7.2

When you run this file on Windows 10 antivirus Symantec says that in this file trojan(SONAR.Heuristic.159)

* Why does he write that there is a virus?
* How to react to it and what to do about it?
* Maybe who had it and what did you do with it?

***In this archive that exe file***
[archive.zip](https://github.com/pyinstaller/pyinstaller/files/2852640/3Point.1.zip)

I hope for your answer.
Thank.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
