### ISSUE TITLE
distutils not included with latest virtualenv (16.4.0)

### ISSUE THREAD

**Issue by lsoica** [pyinstaller/pyinstaller#4064]
This was already reported in #4031. The issue was closed without a fix so I'm creating this one.

**With virtualenv 16.4.0, pyinstaller reports :**

```
3583 INFO: distutils: retargeting to non-venv dir '/usr/lib64/python3.6/distutils/__init__.py'
```
and then during "Loading module hook" sequence, the `hook-distutils.py` is missing and distutils modules are not included into the final executable binary.

When executing the binary the error is:

```
ModuleNotFoundError: No module named 'distutils'
[10373] Failed to execute script <name here>
```

**With virtualenv 16.1.0, pyinstaller reports :**

```
3157 INFO: Processing pre-find module path hook   distutils
5053 INFO: Loading module hook "hook-distutils.py"...
```

and distutils modules are included into the final executable binary.

**Comment by gsemet** [comment]
Reproduced with 16.3 as well.

**Comment by gsemet** [comment]
I also have a pbl with disutils on 16.3. Pyinstaller does not says anything:
```
5055 INFO: Processing pre-find module path hook   distutils
5055 INFO: distutils: retargeting to non-venv dir '/usr/local/lib/python3.6/distutils/__init__.py'
```

But later on 
```
16793 WARNING: Hidden import "distutils.command.build_ext" not found!
...
17570 DEBUG: Collecting submodules for distutils
17676 DEBUG: collect_submodules - Found submodules: {'distutils'}
```

But at execution I still get:
```
ModuleNotFoundError: No module named 'distutils'
```

Worked fine on 16.1

**Comment by gsemet** [comment]
Solution for the moment: force the system's virtualenv to be 16.1 (freeze the virtualenv package version inside the virtualenvironment is not enough)

**Comment by tappi287** [comment]
Just to pinpoint the problem a bit further: `<virtual_env>/Lib/distutils/__init__.py` attribute `distutils_path` returns a path to a file `<system_interpreter>/Lib/distutils/__init__.py` from virtualenv 16.4.0 on, but previously returned a path to the directory `<system_interpreter>/Lib/distutils/`.

PyInstaller hook [hook-distutils](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/pre_find_module_path/hook-distutils.py) uses `os.path.dirname` to expand the search directorys which will result in `<system_interpreter>/Lib/distutils/` with virtualenv 16.4.0 which would result with `<system_interpreter>/Lib/` with previous version of virtualenv.

**Comment by cpbotha** [comment]
Downgrading my system virtualenv to 16.1 did not seem to help.

However, based on @tappi287 's great analysis, I came up with the following work-around. Close to the start of your spec file, add the following:

```python
# work-around for https://github.com/pyinstaller/pyinstaller/issues/4064
import distutils
if distutils.distutils_path.endswith('__init__.py'):
    distutils.distutils_path = os.path.dirname(distutils.distutils_path)
```

This will temporarily override the distutils_path to what pyinstaller expects, resulting in working builds.

**Comment by Ziqi-Li** [comment]
I also had this problem with `virtualenv`. So i switch to use python's built in `venv`.

**Comment by jce94** [comment]
Does anyone know something? I am working with jenkins. I build a virtualenv with this packages:

- altgraph==0.16.1
- cx-Freeze==5.1.1
- cycler==0.10.0
- distutils-pytest==0.1
- future==0.17.1
- kiwisolver==1.0.1
- macholib==1.11
- matplotlib==3.0.2
- numpy==1.15.0
- pandas==0.23.4
- pefile==2018.8.8
- PyInstaller==3.4
- pyparsing==2.3.1
- python-dateutil==2.7.5
- pytz==2018.9
- pywin32-ctypes==0.2.0
- six==1.12.0
- tornado==6.0.1
- virtualenv==16.2.0

But my problem is that in jenkins fails becaouse my app said: "ModuleNotFoundError: No module named 'distutils' after buids the my app. I exetue this app (is .exe to Windows) but the console said that. 

If i build the app wit pyinstaller in a console with virtualenv and the same packacts as befere, the build app NOT FAILD. Help me please!

**Comment by Bernardoow** [comment]
Same probleam here.

**Comment by jce94** [comment]
> Same probleam here.

Hi @Bernardoow . My problem appear when I am executing pyinstaller to generate my app in jenkins  job into a virtualenv. I don´t know because it happens. 
If I execute the pyinstaller in my local machine into a virtualenv the promblem not appear and my app is built successfully. I appreciate any help

**Comment by gsemet** [comment]
Did you tried installing virtualenv 16.1 on your system (pip install —user virtualenv==16.1)?

**Comment by Bernardoow** [comment]
After I sent the message I was testing on the linux and pyinstaler not running after compiled. 

Now I'm testing on the windows and pyinstaler is working normally.

I'm Using virtualenv 16.1.0 in the boths os and the same requirements.txt. Python 3.6.8

**Comment by maxslimmer** [comment]
How about a small variation on @cpbotha's suggestion and putting the workaround directly in the hook?

```python
def pre_find_module_path(api):
    # Absolute path of the system-wide "distutils" package when run from within
    # a venv or None otherwise.
    distutils_dir = getattr(distutils, 'distutils_path', None)
    if distutils_dir is not None:
        # workaround for https://github.com/pyinstaller/pyinstaller/issues/4064
        if distutils_dir.endswith('__init__.py'):
            distutils_dir = os.path.dirname(distutils_dir)
            
        # Find this package in its parent directory.
        api.search_dirs = [os.path.dirname(distutils_dir)]
            
        logger.info('distutils: retargeting to non-venv dir %r' % distutils_dir)
```

NB: reverting system virtualenv AND re-creating the venv also worked for me.

**Comment by meidachen** [comment]
virtualenv 16.1 worked for me, thanks!

**Comment by jce94** [comment]
Thanks to all, I am going to try revet my virtualevn 16.1, when I finish I explain here the results. Maybe be util to all. But I think that the problem is being create virtualenv into Jenkins 😄

**Comment by j9ac9k** [comment]
Ran this error, and can confirm the change to virtualenv 16.1.0 was required, but it had to be the virtualenv module that was used by `pipenv` in my case, which is in line with @gsemet 's comment earlier.

**Comment by jce94** [comment]
Hi all! 
It's impossible generate into a virtualen one app with pyinstaller in a job jenkins with this packages:
https://github.com/pyinstaller/pyinstaller/issues/4064#issuecomment-478358441
I changes to virtualenv==16.1.0 but the problem persists.

 "ModuleNotFoundError: No module named 'distutils', I feel frustrated :man_facepalming: 
If someone could give me some idea I would be enormously grateful. Thanks to all!

**Comment by j9ac9k** [comment]
> Hi all!
> It's impossible generate into a virtualen one app with pyinstaller in a job jenkins with this packages:
> [#4064 (comment)](https://github.com/pyinstaller/pyinstaller/issues/4064#issuecomment-478358441)
> I changes to virtualenv==16.1.0 but the problem persists.
> 
> "ModuleNotFoundError: No module named 'distutils', I feel frustrated 🤦‍♂️
> If someone could give me some idea I would be enormously grateful. Thanks to all!

you probably need to change the virtualenv on the system level of your jenkins build environment, not the virtualenv version of whatever package you're developing

**Comment by JaySoyer** [comment]
I'm still getting this issue with virtualenv 16.4.3.  Down grading to 16.2.0 has worked in the interim.

**Comment by jce94** [comment]
Hi guys! it was impossible to solve my problem with 
_"ModuleNotFoundError: No module named 'distutils'_. (I was trying to build a .exe through pyinsteller). I found a new option to build my python app: Azure DevOps Pipelines. It is similar to Jenkins (I was building my app in a Jenkins server in my local machine but it was impossible for that problem). The .exe works perfect!

Thanks to all for try to help me with problem! 👍

**Comment by oberstet** [comment]
@maxslimmer 's solution (thanks!) worked for me (on a cpy373 based venv), as in (it needs to be in a `pre_find_module_path` subdir within the hooks dir):

```
(cpy373_1) oberstet@intel-nuci7:~/scm/crossbario/crossbarfx$ cat pyinstaller/pre_find_module_path/hook-distutils.py 
import distutils
import os

from PyInstaller.utils.hooks import logger

# https://github.com/pyinstaller/pyinstaller/issues/4064
# https://pythonhosted.org/PyInstaller/hooks.html#the-pre-find-module-path-pfmp-api-method

def pre_find_module_path(api):
    # Absolute path of the system-wide "distutils" package when run from within
    # a venv or None otherwise.
    distutils_dir = getattr(distutils, 'distutils_path', None)
    if distutils_dir is not None:
        # workaround for https://github.com/pyinstaller/pyinstaller/issues/4064
        if distutils_dir.endswith('__init__.py'):
            distutils_dir = os.path.dirname(distutils_dir)

        # Find this package in its parent directory.
        api.search_dirs = [os.path.dirname(distutils_dir)]

        logger.info('>>>>>>> CUSTOM >>>>>>>>> distutils: retargeting to non-venv dir %r' % distutils_dir)
```

**Comment by Hassanzadeh-sd** [comment]
create exe without virtualenv , worked for me.

**Comment by AlmogCohen** [comment]
Same exception while running pipenv + python 3.7. Couldn't quite understand how to solve that yet...

**Comment by AlmogCohen** [comment]
@oberstet You rock!!!!!! Your solution made it! Would it be assimilated into pyinstaller officially?

**Comment by truuuuegate** [comment]
> Downgrading my system virtualenv to 16.1 did not seem to help.
> 
> However, based on @tappi287 's great analysis, I came up with the following work-around. Close to the start of your spec file, add the following:
> 
> ```python
> # work-around for https://github.com/pyinstaller/pyinstaller/issues/4064
> import distutils
> if distutils.distutils_path.endswith('__init__.py'):
>     distutils.distutils_path = os.path.dirname(distutils.distutils_path)
> ```
> 
> This will temporarily override the distutils_path to what pyinstaller expects, resulting in working builds.

Thank you! This solution solve my problem in pipenv+python3.7+pyinstaller3.4

**Comment by jmbruges** [comment]
@truuuuegate can you tell me where excatly did you made the change? I have my app.spec and I add these lines. However, nothing change. 
I am using the same solution (pipenv+P3+Pyinst)
Should I add these lines in my app.py?

**Comment by truuuuegate** [comment]
@jmbruges 
I add that code at the beginning of the *.spec file. 
Then the pyinstaller process in pipenv could find the `distutils` module path that in native enviroment.

**Comment by jmbruges** [comment]
> @jmbruges
> I add that code at the beginning of the *.spec file.
> Then the pyinstaller process in pipenv could find the `distutils` module path that in native enviroment.

Thanks, I tried that and did not work. I will see if cx_freeze can resolve it but so far I have other issues trying to install that package.

**Comment by asakiasako** [comment]
Is there any automatic methods to solve this problem, such as using pyinstaller hook?

**Comment by asakiasako** [comment]
> @maxslimmer 's solution (thanks!) worked for me (on a cpy373 based venv), as in (it needs to be in a `pre_find_module_path` subdir within the hooks dir):
> 
> ```
> (cpy373_1) oberstet@intel-nuci7:~/scm/crossbario/crossbarfx$ cat pyinstaller/pre_find_module_path/hook-distutils.py 
> import distutils
> import os
> 
> from PyInstaller.utils.hooks import logger
> 
> # https://github.com/pyinstaller/pyinstaller/issues/4064
> # https://pythonhosted.org/PyInstaller/hooks.html#the-pre-find-module-path-pfmp-api-method
> 
> def pre_find_module_path(api):
>     # Absolute path of the system-wide "distutils" package when run from within
>     # a venv or None otherwise.
>     distutils_dir = getattr(distutils, 'distutils_path', None)
>     if distutils_dir is not None:
>         # workaround for https://github.com/pyinstaller/pyinstaller/issues/4064
>         if distutils_dir.endswith('__init__.py'):
>             distutils_dir = os.path.dirname(distutils_dir)
> 
>         # Find this package in its parent directory.
>         api.search_dirs = [os.path.dirname(distutils_dir)]
> 
>         logger.info('>>>>>>> CUSTOM >>>>>>>>> distutils: retargeting to non-venv dir %r' % distutils_dir)
> ```

Thanks for your tip, I searched pyinstaller docs and finally understand how it works

**Comment by htgoebel** [comment]
Since there is a solution pointed out here, anybody going to create a pull-request? See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html).

**Comment by tangm** [comment]
I ran into this, but I'm not sure continuing to rely on the internal `distutils_path` is a good idea... maybe the hook should be doing its own system `distutils` detection instead? Something like:

```
    # opcode is not a virtualenv module, so we can use it to find the stdlib
    # Technique taken from virtualenv's "distutils" package detection at
    # https://github.com/pypa/virtualenv/blob/0ab032ce1a/virtualenv_embedded/distutils-init.py#L5
    import opcode

    system_module_path = os.path.normpath(os.path.dirname(opcode.__file__))
    loaded_module_path = os.path.normpath(os.path.dirname(distutils.__file__))
    if system_module_path != loaded_module_path:
        # Find this package in its parent directory.
        api.search_dirs = [system_module_path]
        logger.info('distutils: retargeting to non-venv dir %r' % system_module_path)
```

**Comment by htgoebel** [comment]
@tangm I'm still waiting for someone providing a pull-request. Then we can discuss teh code there.

**Comment by htgoebel** [comment]
Also I'd appreciate a **summary** of the caus for this issue, so I can understand and comment on the solution.

**Comment by tangm** [comment]
@htgoebel I've created https://github.com/pyinstaller/pyinstaller/pull/4372 , with a description of the problem.

**Comment by mxnsrengler** [comment]
Thanks @tangm for your pull request.  I was able to implement your code myself and fix the distutils issue for me!

**Comment by txoof** [comment]
This bug appears to be closed, but the problem still exists in PyInstaller 3.5. 

I can reliably reproduce this with PyInstaller 3.5 in virtualenv 16.7.7 as documented [here](https://stackoverflow.com/questions/59444914/pyinstaller-failing-to-import-distuitls-when-used-with-pipenv/59444915#59444915)

Is there an accepted solution that remedies this?

**Comment by AndCycle** [comment]
> 
> 
> This bug appears to be closed, but the problem still exists in PyInstaller 3.5.
> 
> I can reliably reproduce this with PyInstaller 3.5 in virtualenv 16.7.7 as documented [here](https://stackoverflow.com/questions/59444914/pyinstaller-failing-to-import-distuitls-when-used-with-pipenv/59444915#59444915)
> 
> Is there an accepted solution that remedies this?

the fix probably sitting in git tree waiting for release, have you tried the head version?

**Comment by txoof** [comment]
@AndCycle 
I'm a novice when it comes to Git, I'm not sure how I would do that.

Can you point me to the relevant documentation/instructions?

**Comment by txoof** [comment]
> > This bug appears to be closed, but the problem still exists in PyInstaller 3.5.
> > I can reliably reproduce this with PyInstaller 3.5 in virtualenv 16.7.7 as documented [here](https://stackoverflow.com/questions/59444914/pyinstaller-failing-to-import-distuitls-when-used-with-pipenv/59444915#59444915)
> > Is there an accepted solution that remedies this?
> 
> the fix probably sitting in git tree waiting for release, have you tried the head version?

@AndCycle
I'm a novice when it comes to Git, I'm not sure how I would do that.

Can you point me to the relevant documentation/instructions?

**Comment by AndCycle** [comment]
@txoof 
maybe just take the shortcut, 
the pull req https://github.com/pyinstaller/pyinstaller/pull/4372 is just a patched hook file,
replace the one should do the job.

**Comment by elyou027** [comment]
> > > This bug appears to be closed, but the problem still exists in PyInstaller 3.5.
> > > I can reliably reproduce this with PyInstaller 3.5 in virtualenv 16.7.7 as documented [here](https://stackoverflow.com/questions/59444914/pyinstaller-failing-to-import-distuitls-when-used-with-pipenv/59444915#59444915)
> > > Is there an accepted solution that remedies this?
> > 
> > 
> > the fix probably sitting in git tree waiting for release, have you tried the head version?
> 
> @AndCycle
> I'm a novice when it comes to Git, I'm not sure how I would do that.
> 
> Can you point me to the relevant documentation/instructions?

This is working for me:
`pip install https://github.com/pyinstaller/pyinstaller/tarball/develop`

**Comment by oberstet** [comment]
just wanted to note: the workarounds above don't work on pyinstaller 3.6 anymore.

pyinstaller 3.6 has changed its behavior, adding an internal check:

```
        # Safety check, see above
        global HOOKS_MODULE_NAMES
        assert self.hook_module_name not in HOOKS_MODULE_NAMES
        HOOKS_MODULE_NAMES.add(self.hook_module_name)
```

to the new file `cpy381_1/lib/python3.8/site-packages/PyInstaller/depend/imphook.py`.

**Comment by vivekvardhanadepu** [comment]
A workaround https://github.com/pypa/pipenv/issues/2922#issuecomment-660516533
