### ISSUE TITLE
How to Run a Function with PyInstaller???

### ISSUE THREAD

**Issue by rsocor01** [pyinstaller/pyinstaller#4065]
Hi all,

I have a Python function that I run like this,

python -c "import myfunction; myfunction.myfunction('HELLO WORLD')"

It works fine. But, then when I make the executable file myfunction.exe I'm unable to feed the parameter 'HELLO WORLD' into the function. I have tried different combinations like myfunction.exe('HELLO WORLD'), but they don't work. I used the ONEFILE option when using PyInstaller. Any help is greatly appreciated.

Thank you,

Robert

**Comment by htgoebel** [comment]
PyInstaller only runs scripts/programms. Please read some Python tutorial to learn how to pss argumetns to a Python script.

**Comment by rsocor01** [comment]
I tried passing arguments using sys.argv and it works. Thanks.
