### ISSUE TITLE
Pyinstaller not bundle images to GUI on Windows7

### ISSUE THREAD

**Issue by r-sankar** [pyinstaller/pyinstaller#4068]
I am facing an issue like if i created .exe file using pyinstaller it is not bundle images to GUI on windows7

**Comment by htgoebel** [comment]
Please read the manual.

**Comment by r-sankar** [comment]
If a create .exe using Pyinstaller with out --onefile command it is able to bundle images to GUI, But if i use 
--onefile command then it is unable to bundle images to GUI

**Comment by htgoebel** [comment]
I doubt this, since collecting files is done the same way in both cases. check the .toc files in the buils directory for differences.
