### ISSUE TITLE
plaidML

### ISSUE THREAD

**Issue by MichaelFomenko** [pyinstaller/pyinstaller#4072]
Hello people, my name is Michael Fomenko and I am trying to deploy plaidML with pyinstaller.
My App working fine with plaidML without pyinstaller. When I using pyinstaller:

**pyinstaller App.py --clean**

it creates a Pyinstaller App.exe, and the when I trying to run it produces this Error:

**> C:\PyPaket\dist\App>App.exe**
> Traceback (most recent call last):
>   File "App.py", line 103, in <module>
>   File "lib\site-packages\plaidml\__init__.py", line 858, in Context
>   File "lib\site-packages\plaidml\__init__.py", line 758, in _lib
>   File "lib\site-packages\plaidml\__init__.py", line 173, in __init__
>   File "lib\site-packages\plaidml\__init__.py", line 165, in load_library
>   File "ctypes\__init__.py", line 426, in LoadLibrary
>   File "lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py", line 151, in __init__
> __main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\PyPaket\\dist\\App\\Library\\bin\\plaidml.dll'. Most probably this dynlib/dll was not found when the application was frozen.
> [14060] Failed to execute script App

after this Problem I done the manual import of the plaidml.dll

**pyinstaller App.py --add-binary "plaidML-env\library\bin\plaidml.dll;." --clean**

it creates a new Pyinstaller App.exe with the plaidml.dll library, and the when I trying to run it produces this Error:

**> C:\PyPaket\dist\App>App.exe**
> Traceback (most recent call last):
>   File "App.py", line 108, in <module>
>   File "lib\site-packages\plaidml\__init__.py", line 1042, in devices
>   File "lib\site-packages\plaidml\__init__.py", line 1000, in __init__
>   File "lib\site-packages\plaidml\__init__.py", line 746, in _check_err
>   File "lib\site-packages\plaidml\library.py", line 131, in raise_last_status
> plaidml.exceptions.Unknown: unable to resolve type:
> [7320] Failed to execute script App

when I try to Analyse this Error 

>   File "App.py", line 108, in <module>
```
 99   import plaidml
101   import plaidml.exceptions
102   import plaidml.settings
103   ctx = plaidml.Context()
104   plaidml.quiet()
105   # Operate as if nothing is set
106   plaidml.settings._setup_for_test(plaidml.settings.user_settings)
107   plaidml.settings.experimental = False
108   devices, _ = plaidml.devices(ctx, limit=100, return_all=True)
109   plaidml.settings.experimental = True
101   exp_devices, unmatched = plaidml.devices(ctx, limit=100, return_all=True)
```

with the plaidml.dll this time 103  could be called but in 108 it created an error.
This means that the plaidml was sucessfully loaded and called sucesfully functions of them in 104, 106 and 107. The Problem musst be in the plaidml.devices function.

But it can be that 103   ctx = plaidml.Context() giving a bad result, so that 108 plaidml.devices(ctx, limit=100, return_all=True) cant handel it.

Pyinstaller need to uninstall Enum34 modul to Packaging my App,  but plaidML require it in this Function? But why does plaidML running without Enum34 outside the Pyinstaller Packaging and dont with Pyinstaller Packaging? Can this be the Reason? I have Python 3.6.8 and it have Enum as a Standart library build in, this is very strange.

>   File "lib\site-packages\plaidml\__init__.py", line 1042, in devices
```
1039 def devices(ctx, limit=1, return_all=False):
1040    """Returns a tuple of lists valid devices or aborts the program."""
1041    plaidml.settings.start_session()
1042    enumerator = _Enumerator(ctx)
1043    config_source = _lib().plaidml_get_enumerator_config_source(enumerator)
1044    if return_all:
1045        return enumerator.valid_devs, enumerator.invalid_devs
1046    else:
1047        if len(enumerator.valid_devs) == 0:
1048            _setup_fail("No devices found.", enumerator.invalid_devs)
1049        if limit and len(enumerator.valid_devs) > limit:
1050            _setup_fail("Too many devices configured (limit={})".format(limit),
1051                        enumerator.valid_devs)
1052        return enumerator.valid_devs
```

>   File "lib\site-packages\plaidml\__init__.py", line 1000, in __init__
```
 991 def __init__(self, ctx):
 992         self._ctx = ctx
 993         if settings.config:
 994             self._as_parameter_ = _lib().plaidml_alloc_device_enumerator_with_config(
 995                 ctx, settings.config.encode(), ctypes.cast(None, _ENUM_DEVICES_FUNCTYPE), None)
 996         elif settings.config_file and os.path.exists(settings.config_file):
 997             with open(settings.config_file) as cf:
 998                 config = cf.read()
 999             self._as_parameter_ = _lib().plaidml_alloc_device_enumerator_with_config(
1000                 ctx, config.encode(), ctypes.cast(None, _ENUM_DEVICES_FUNCTYPE), None)
1001          else:
1002              self._as_parameter_ = _lib().plaidml_alloc_device_enumerator(
1003                  ctx, ctypes.cast(None, _ENUM_DEVICES_FUNCTYPE), None)
1004          self._free = _lib().plaidml_free_device_enumerator
1005          self._valid_devs = None
1006          self._invalid_devs = None
```

>   File "lib\site-packages\plaidml\__init__.py", line 746, in _check_err
```
 739    def _check_err(self, result, func, args):
 740        if result:
 741            return result
 742        if func == self.plaidml_alloc_device_enumerator and args[2]:
 743            return None
 744        if func == self.plaidml_map_buffer_current and args[2]:
 745            return None
 746        self.raise_last_status()
```

when I debug the Code I notice that in my normal plaidml execution the variable Result is set and the first **740 if Result statement is True** but in my Pyinstaller Paket it is **False** and is going to the self.raise_last_status() what is wrong.

in the original Result is: <plaidml.LP__C_DeviceEnumerator object at 0x0000028373E66D48>
and **Result.__dict __ is: {}**
and in the Pyinstaller version it is the same but is not going in the  740 if Result statement, but why?

And if I forse plaidML in Pyinstaller to go to the if Result, it works but another Error appears in the
if _impl_lib: <plaidml._Library object at 0x00000198C5522828>
Error: ('exception: access violation reading 0x0000000000000018',)
but I think that the if Result statement is working right and I just cant see the Result Value because it is a Pointer to a C Variable but the if statement can see it somehow and the problem must be in something else. perhaps the ctx variable or something other have problems.

Maibe, but I am not sure, the Pointer to in the the Result to a C Variable is reverencing to static librara that Pyinstaller not included, but I dont know what library plaidML referensing static.

>   File "lib\site-packages\plaidml\library.py", line 131, in raise_last_status
```
130    def raise_last_status(self):
131        raise self.last_status()
```

I tryed to run App.exe as a Administrator, but it dont help.
This problem Appear only in Pyinstaller App with plaidML, without plaidML it works fine.

**Comment by MichaelFomenko** [comment]
here is the Solution i found for my Problem: 
**pyinstaller App.py  --add-data 'compile-env\Include;Include' --add-data 'compile-env\library;library'  --add-data 'compile-env\share;share' --clean**

**Comment by htgoebel** [comment]
We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by Algy** [comment]
I stumbled upon the same issue in linux and found a solution after struggling for a couple of hours. For anyone who has the same issue in linux, you should include both libplaidml.so and `share` directory  so plaidml can load its configuration files. 
With python3.7 running inside virtualenv, this worked for me:
```
#!/bin/sh
PYBASE="$(dirname $(dirname $(which python)))"
PYLIB="$PYBASE/lib"
PYSHARE="$PYBASE/share"
PYINCLUDE="$PYBASE/include"

pyinstaller \
--add-binary "$PYLIB/libplaidml.so:." \
--add-data "$PYLIB:./lib" \
--add-data "$PYINCLUDE:./include" \
--add-data "$PYSHARE:./share" \
app.py
```

**Comment by Johannes0Horn** [comment]
@MichaelFomenko May I ask on which OS you made it work?

**Comment by MichaelFomenko** [comment]
> @MichaelFomenko May I ask on which OS you made it work?

Ubuntu and Windows 10, but I dont recomend deploying your apps as exe files, deploy with tensorflow,js because webgl is everywhere supported.

**Comment by Johannes0Horn** [comment]
Thank you @MichaelFomenko,
For me this command worked with Anaconda Python 3.7, Windows 10 64 bit, pyinstaller 4.0.dev0+g86906259 and plaidml 0.7.0:
1.) cd to App.py
2.)
`pyinstaller "App.py" --add-data ./Include;Include --add-data ./library;library. --add-data ./share;share --clean`

Include, Library and Share folders had to be in the same directory as App.py.
