### ISSUE TITLE
Integrating C++ exe and dll with python using pyinstaller

### ISSUE THREAD

**Issue by kapil-iitk** [pyinstaller/pyinstaller#4073]
I have four files, (1.) C++ exe for the scientific computing, (2.) dll file used in the C++, (3.) a python based GUI as a frontend and (4.) a python script to plot the data and other required processing. I wanted to make a single exe file package containing all four required file. I am unable to include C++ exe in the single archive created by pyinstaller. How I can embed C++ exe and dll within the single archive?

**Comment by MichaelFomenko** [comment]
pyinstaller App.py --add-data 'pathtoexe\your.exe;.' --add-binary "pathtodll\your.dll;."  --onefile --noconsole --clean

and in your python code you cann get your real path

if getattr(sys, 'frozen', False):
	basedir = sys._MEIPASS
else:
	basedir = os.path.dirname(os.path.abspath(__file__))
basedir = str(basedir)
print(basedir)

**Comment by kapil-iitk** [comment]
With the packaging as shared (pyinstaller App.py --add-data 'pathtoexe\your.exe;.' --add-binary "pathtodll\your.dll;." --onefile --noconsole --clean) the exe will also included in the onefile?
I wish to include the exe and dll within the onefile so that I can share the single exe for the data processing.

**Comment by MichaelFomenko** [comment]
pyinstaller dont really create one singe Exe, it is a self extracting Archive. when you open the Exe in windows it creates an Folder in temp and opening the real App.exe there. but the user have the illusion of one exe file. this is why it is important the code I written to you, the basedir is the path where you can reference your included exe and other includet things.

**Comment by kapil-iitk** [comment]
Thank you. I will try this.
