### ISSUE TITLE
Feedback/Question - Is Tkinter supported? 

### ISSUE THREAD

**Issue by nu-fulla** [pyinstaller/pyinstaller#4075]
Tkinter isn't listed here:

https://github.com/pyinstaller/pyinstaller/wiki/Supported-Packages

It's also not installed by default with CPython anymore so I was unsure if it was considered a "standard library".

When I Googled the terms TKinter pyinstaller, to clarify if it was supported or not, the majority of the results were issues people have had over the years. It would be really nice to clarify it is indeed supported. (Added to the above list.)

**Comment by MichaelFomenko** [comment]
Yes tkinter working fine try:
python -m pip install --upgrade pip
pip3 install --upgrade setuptools 
pip3 install --upgrade yourmodules
.
-
-
pip3 uninstall enum34
pyinstaller App.py

**Comment by htgoebel** [comment]
> Tkinter isn't listed here

tkintr is part of the standard lib, this is why it is not listed on that page.
