### ISSUE TITLE
XGBoost shared DLL not bundled

### ISSUE THREAD

**Issue by kjanko** [pyinstaller/pyinstaller#4076]
Python: 3.7.2
PyInstaller: 3.4
XGBoost: 0.81

OS: Windows 10, CentOS7

Windows 10 log:
```
xgboost.libpath.XGBoostLibraryNotFound: Cannot find XGBoost Library in the candidate path, did you install compilers and run build.sh in root path?
List of candidates:
C:\Users\kjankosk\AppData\Local\Temp\_MEI103562\xgboost\xgboost.dll
C:\Users\kjankosk\AppData\Local\Temp\_MEI103562\xgboost\../../lib/xgboost.dll
C:\Users\kjankosk\AppData\Local\Temp\_MEI103562\xgboost\./lib/xgboost.dll
C:\Users\kjankosk\AppData\Local\Temp\_MEI103562\xgboost\xgboost.dll
C:\Users\kjankosk\AppData\Local\Temp\_MEI103562\xgboost\../../windows/x64/Release/xgboost.dll
C:\Users\kjankosk\AppData\Local\Temp\_MEI103562\xgboost\./windows/x64/Release/xgboost.dll
```

Seems like PyInstaller is not bundling the .dll/.so dependency that's needed by XGboost. Is this an issue with the library, or do I need to give specific instructions to PyInstaller during the bundling process?

I've tried building with --onedir, --onefile, --noupx, adding it as a hook but none of these efforts had any success.

**Comment by kjanko** [comment]
Using collect_dynamic_libs on the hook solved the issue.

**Comment by htgoebel** [comment]
We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by LeZhengThu** [comment]
@kjanko  Hi, I have the same problem. Can you provide more details about your solution? Thanks.

**Comment by kjanko** [comment]
@LeZhengThu check the pull request I referenced, you need a hook.

**Comment by LeZhengThu** [comment]
@kjanko  Thanks. I make it right with your method. However, if I want to create one file for the exe, i.e.if I use "pyinstaller --onefile xx.py", the same error rises again.
