### ISSUE TITLE
Pyodbc insert 

### ISSUE THREAD

**Issue by FunnyGoofy** [pyinstaller/pyinstaller#4082]
my script.py can correctly run. but get error when I run exe which is generated by pyinstaller. Welcome any feedback. thanks a lot

`       connection = connect_to_database()
        if connection is None:
            logger.info("~~~~~~~~~~~~~~~~~ ERROR: connection is None ~~~~~~~~~~~~~~~~~~~~~~~~")
            
        cursor = connection.cursor()
        cursor.fast_executemany = True  # new in pyodbc 4.0.19
        try:
            cursor.executemany(u"INSERT INTO DrillConnectionTest(DKey, \
                                                                 HoleDepth, \
                                                                 Rig, \
                                                                 Job, \
                                                                 StartDate, \
                                                                 EndDate, \
                                                                 StartTime, \
                                                                 EndTime, \
                                                                 StandLength, \
                                                                 Driller, \
                                                                 OtherDriller, \
                                                                 Operator, \
                                                                 WtoW, \
                                                                 TotalPre, \
                                                                 PreSlip, \
                                                                 TotalReam, \
                                                                 Ream, \
                                                                 BackReam,\
                                                                 StoS, \
                                                                 PostSlip, \
                                                                 Inc, \
                                                                 OnBottom, \
                                                                 BaseHook)\
											VALUES(?, ?, ?, ?, ?, ?, ?, ?, ?, ?,\
												   ?, ?, ?, ?, ?, ?, ?, ?, ?, ?,\
												   ?, ?, ?)", \
											all_rows_list)
        except pyodbc.Error as ex:
            sqlstate = ex.args[0]
            if sqlstate == '23000': # already exist
                logger.info("records from {} already exists in database".format(file))`

![2019-02-20_13-56-09](https://user-images.githubusercontent.com/27033943/53123946-77af2e00-3517-11e9-8c91-e7b14d60baf4.png)

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.
We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.
