### ISSUE TITLE
pyinstaller does not correctly package the neo library

### ISSUE THREAD

**Issue by SebastianOltmanns** [pyinstaller/pyinstaller#4086]
I use the [neo library](https://neo.readthedocs.io/en/latest/) in my project and bundle it with pyinstaller.

There occurs an error when the bundled application is running and the functionality of the neo library is called. The Traceback of that error is as follows (replaced my project stuff with `...`):

```
Traceback (most recent call last):
  File "...", line ..., in ...
  File "site-packages\neo\io\axonio.py", line 45, in __init__
  File "site-packages\neo\io\basefromrawio.py", line 73, in __init__
  File "site-packages\neo\rawio\baserawio.py", line 152, in parse_header
  File "site-packages\neo\rawio\baserawio.py", line 382, in _group_signal_channel_characteristics
ModuleNotFoundError: No module named 'numpy.lib.recfunctions'
```

I fixed this by explicitly importing the named module in one of my python files: `import numpy.lib.recfunctions`. 

Please note that I was not able to test this with the latest development version since the install failed for me.

My software versions:
Windows 7, 64 bit
Python 3.7.1 (64 bit, standalone from the python website, no Anaconda)
pyinstaller 3.4 (stable)
neo 0.7.1

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by htgoebel** [comment]
We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

**Comment by Legorooj** [comment]
Thanks for letting us know about this. Unfortunately, we are unable to focus on hooks at the moment. Feel free to submit a PR though!
