### ISSUE TITLE
pyinstaller does not want to install XMLSchema lib

### ISSUE THREAD

**Issue by vnahmias** [pyinstaller/pyinstaller#4091]
Hello i have an issue with pyinstaller module, i have follow all of your instructions (working with the last dev version, having my project working in a venv and everything else). I have made a post on stackoverflow : https://stackoverflow.com/questions/54870373/pyinstaller-missing-files-when-executing but then i guessed that pyinstaller just doesn not add the lib i want. if someone can take a look that would be nice !

**Comment by bwoodsend** [comment]
Use the maling list in future if you want help.
