### ISSUE TITLE
Trying to install PyInstaller on Windows 10 and Anaconda

### ISSUE THREAD

**Issue by bjce** [pyinstaller/pyinstaller#4099]
I'm trying to install `PyInstaller` with Python 3.7 from Anaconda 2018.12 on Windows 10

I typed: `conda install -c conda-forge pyinstaller`
and got the following error message:

    Solving environment: failed
    
    UnsatisfiableError: The following specifications were found to be in conflict:
      - anaconda==2018.12=py37_0
      - pyinstaller
    Use "conda info <package>" to see the dependencies for each package.

I then typed `conda info pyinstaller` but there was no special output. I also did the same with `pyinstaller=3.2.1` instead of `pyinstaller` but that did not change anything

What should I do?

**Comment by htgoebel** [comment]
Please contact your conda support, hey earn money with their software.
