### ISSUE TITLE
jsonschema hook is broken for jsonschema 3.x

### ISSUE THREAD

**Issue by LelandWeathers** [pyinstaller/pyinstaller#4100]
Looks like last weeks jsonschema release of 3.x does not work with the hooks that are in place and working for jsonschema 2.6

Output when running packaged application (Python 3.7 and jsonschema 3.0.0 or 3.0.1):
Traceback (most recent call last):
  File "tableauserveretl\tableauserveretl.py", line 13, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\XXX\.virtualenvs\XXX-fqo3x53x\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "tableauserveretl\configuration\__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\XXX\.virtualenvs\XXX-fqo3x53x\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "tableauserveretl\configuration\configuration.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\XXX\.virtualenvs\XXX-fqo3x53x\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\jsonschema\__init__.py", line 33, in <module>
  File "site-packages\pkg_resources\__init__.py", line 481, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 357, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 900, in require
  File "site-packages\pkg_resources\__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'jsonschema' distribution was not found and is required by the application
[15020] Failed to execute script XXX

**Comment by chibby0ne** [comment]
Ditto. I have a similar error message for a PR I opened to update docker-compose's jsonschema to 3.0.1 (https://github.com/docker/compose/pull/6631):

```
16:08:37 18803 INFO: Building EXE from EXE-00.toc completed successfully.
16:08:37 ++ mv dist/docker-compose dist/docker-compose-Linux-x86_64
16:08:37 ++ dist/docker-compose-Linux-x86_64 version
16:08:37 Traceback (most recent call last):
16:08:37   File "bin/docker-compose", line 5, in <module>
16:08:37     from compose.cli.main import main
16:08:37   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
16:08:37   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
16:08:37   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
16:08:37   File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
16:08:37     exec(bytecode, module.__dict__)
16:08:37   File "compose/cli/main.py", line 22, in <module>
16:08:37     from ..bundle import get_image_digests
16:08:37   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
16:08:37   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
16:08:37   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
16:08:37   File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
16:08:37     exec(bytecode, module.__dict__)
16:08:37   File "compose/bundle.py", line 12, in <module>
16:08:37     from .config.serialize import denormalize_config
16:08:37   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
16:08:37   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
16:08:37   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
16:08:37   File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
16:08:37     exec(bytecode, module.__dict__)
16:08:37   File "compose/config/__init__.py", line 6, in <module>
16:08:37     from .config import ConfigurationError
16:08:37   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
16:08:37   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
16:08:37   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
16:08:37   File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
16:08:37     exec(bytecode, module.__dict__)
16:08:37   File "compose/config/config.py", line 50, in <module>
16:08:37     from .validation import match_named_volumes
16:08:37   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
16:08:37   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
16:08:37   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
16:08:37   File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
16:08:37     exec(bytecode, module.__dict__)
16:08:37   File "compose/config/validation.py", line 12, in <module>
16:08:37     from jsonschema import Draft4Validator
16:08:37   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
16:08:37   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
16:08:37   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
16:08:37   File "/code/.tox/py37/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
16:08:37     exec(bytecode, module.__dict__)
16:08:37   File "site-packages/jsonschema/__init__.py", line 33, in <module>
16:08:37   File "site-packages/pkg_resources/__init__.py", line 481, in get_distribution
16:08:37   File "site-packages/pkg_resources/__init__.py", line 357, in get_provider
16:08:37   File "site-packages/pkg_resources/__init__.py", line 900, in require
16:08:37   File "site-packages/pkg_resources/__init__.py", line 786, in resolve
16:08:37 pkg_resources.DistributionNotFound: The 'jsonschema' distribution was not found and is required by the application
```

**Comment by kieranlea** [comment]
I was able to work around this by modifying [hook-jsonschema](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-jsonschema.py) and adding:
```python
datas += copy_metadata('jsonschema')
```
I then loaded this new one using the `--additional-hooks-dir` flag.

**Comment by chibby0ne** [comment]
> I was able to work around this by modifying [hook-jsonschema](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-jsonschema.py) and adding:
> 
> ```python
> datas += copy_metadata('jsonschema')
> ```
> 
> I then loaded this new one using the `--additional-hooks-dir` flag.

Thanks for your idea @kieranlea 
Just a question though, why did you need to add an `--additional-hook-dir`? You mentioned you modified the hook, so the location should be the same right?

Also if we only need to add that one line to the hook-jsonschema that would be great for a PR! I tried digging into the code a bit but honestly didn't get too far... Thanks again for offering alternatives :D

**Comment by kieranlea** [comment]
You could modify the hook in PyInstaller itself if you prefer, but I didn't want to modify the installed library, I just wanted to overload it with the fix. No problem, I'll look into making a PR.

**Comment by chibby0ne** [comment]
@kieranlea I hoped you don't mind but I took the liberty to create a PR for this fix, since I needed it urgently. I also tried it with the issue I referenced in docker-compose, and it seems it works like a charm. Thank you @kieranlea

**Comment by kieranlea** [comment]
> @kieranlea I hoped you don't mind but I took the liberty to create a PR for this fix, since I needed it urgently. I also tried it with the issue I referenced in docker-compose, and it seems it works like a charm. Thank you @kieranlea

No problem!

**Comment by bjones1** [comment]
Closed by 4f051b301b0ed0a79b8605a07719222c19459e3d.

**Comment by kentgray** [comment]
@chibby0ne :  where are you adding datas += copy_metadata('jsonschema')?

I'm new to exe files.  Did you add it to one of your .py files?

**Comment by samanthaLink** [comment]
@kentgray It also took me a while to find out how this works...

 1. You go to the location where the hook-files are stored (mine is C:\Users\Link\AppData\Roaming\Python\Python36\site-packages\PyInstaller\hooks)

2. Then search for hook-jsonschema.py (and you will see that the version is from 2017)

3. Open it with PyCharm and delete its content, then paste the whole stuff below in there and save!

#-----------------------------------------------------------------------------
# Copyright (c) 2005-2019, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------

# This is needed to bundle draft3.json and draft4.json files that come
# with jsonschema module

from PyInstaller.utils.hooks import collect_data_files, copy_metadata
datas = collect_data_files('jsonschema')
datas += copy_metadata('jsonschema')
