### ISSUE TITLE
Exe not working after compilation 

### ISSUE THREAD

**Issue by Mandrilux** [pyinstaller/pyinstaller#4103]
I Create an application and i want share my application. This application us QT.

When generated a executable application with pyinstaller, all it's ok but when i want start this application , i have one error.

- Python 3.7.2
- Windows 10 64 bit
-pyinstaller 3.5.dev0+cb8d10af6

i use Pyside2

from PySide2.QtWidgets import QApplication, QLabel, QProgressBar, QWidget, QTextEdit, QPushButton
from PySide2 import *

traceback:
 Pyinstaller --paths="C:\Users\baptiste\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\shiboken2" --paths="C:\Users\baptiste\AppData\Local\Programs\Python\Python37-32\Lib\site-packages\PySide2" .\update.py
45 INFO: PyInstaller: 3.5.dev0+cb8d10af6
45 INFO: Python: 3.7.2
45 INFO: Platform: Windows-10-10.0.17763-SP0
46 INFO: wrote D:\ProjetUpdater\update.spec
48 INFO: UPX is not available.
49 INFO: Extending PYTHONPATH with paths
['D:\\ProjetUpdater',
 'C:\\Users\\baptiste\\AppData\\Local\\Programs\\Python\\Python37-32\\Lib\\site-packages\\shiboken2',
 'C:\\Users\\baptiste\\AppData\\Local\\Programs\\Python\\Python37-32\\Lib\\site-packages\\PySide2',
 'D:\\ProjetUpdater']
49 INFO: checking Analysis
49 INFO: Building Analysis because Analysis-00.toc is non existent
50 INFO: Initializing module dependency graph...
52 INFO: Initializing module graph hooks...
54 INFO: Analyzing base_library.zip ...
2720 INFO: running Analysis Analysis-00.toc
2722 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\baptiste\appdata\local\programs\python\python37-32\python.exe
3801 INFO: Caching module hooks...
13704 INFO: Analyzing D:\ProjetUpdater\update.py
13892 INFO: Loading module hooks...
13892 INFO: Loading module hook "hook-encodings.py"...
13962 INFO: Loading module hook "hook-pydoc.py"...
13963 INFO: Loading module hook "hook-PySide2.py"...
13964 WARNING: Hidden import "numpy.core.multiarray" not found!
13965 INFO: Loading module hook "hook-PySide2.QtNetwork.py"...
14064 INFO: Loading module hook "hook-PySide2.QtWidgets.py"...
14065 INFO: Loading module hook "hook-xml.py"...
14113 INFO: Loading module hook "hook-PySide2.QtCore.py"...
14188 INFO: Loading module hook "hook-PySide2.QtGui.py"...
14722 INFO: Looking for ctypes DLLs
14722 INFO: Analyzing run-time hooks ...
14726 INFO: Including run-time hook 'pyi_rth_qt5plugins.py'
14731 INFO: Looking for dynamic libraries
24710 INFO: Looking for eggs
24711 INFO: Using Python library c:\users\baptiste\appdata\local\programs\python\python37-32\python37.dll
24712 INFO: Found binding redirects:
[]
24722 INFO: Warnings written to D:\ProjetUpdater\build\update\warn-update.txt
24759 INFO: Graph cross-reference written to D:\ProjetUpdater\build\update\xref-update.html
24780 INFO: checking PYZ
24780 INFO: Building PYZ because PYZ-00.toc is non existent
24782 INFO: Building PYZ (ZlibArchive) D:\ProjetUpdater\build\update\PYZ-00.pyz
25316 INFO: Building PYZ (ZlibArchive) D:\ProjetUpdater\build\update\PYZ-00.pyz completed successfully.
25330 INFO: checking PKG
25330 INFO: Building PKG because PKG-00.toc is non existent
25330 INFO: Building PKG (CArchive) PKG-00.pkg
25345 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
25347 INFO: Bootloader c:\users\baptiste\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
25347 INFO: checking EXE
25349 INFO: Building EXE because EXE-00.toc is non existent
25350 INFO: Building EXE from EXE-00.toc
25351 INFO: Appending archive to EXE D:\ProjetUpdater\build\update\update.exe
25408 INFO: Building EXE from EXE-00.toc completed successfully.
25415 INFO: checking COLLECT
25415 INFO: Building COLLECT because COLLECT-00.toc is non existent
25415 INFO: Building COLLECT COLLECT-00.toc
26199 INFO: Building COLLECT COLLECT-00.toc completed successfully.
PS D:\ProjetUpdater>

When i start the application /dist\update\update.exe
i see the black console one second and and the program closes

So, what's wrong? I am new one for pyinstaller and Github. Any help is appreciated!

**Comment by danuker** [comment]
Try running from a console:

Shift-right-click the dist directory, then click "Open PowerShell window here", then type update\update.exe, to see the output of the script.

Then, paste the run output here.

**Comment by bjones1** [comment]
This was fixed in 5b5791285332003940f4bc70c32bb0cf10a32917. Please reopen if there are still problems.

**Comment by amineo99** [comment]
Hi Mandrilux Did you fix that ??? I have the same problem here
