### ISSUE TITLE
Added data files missing when using --onefile option

### ISSUE THREAD

**Issue by tbharber** [pyinstaller/pyinstaller#4107]
Hi all,

I believe I am seeing a bug.  When packaging my application normally using the following syntax, my image files are included correctly and everything works just fine...

_pyinstaller --clean -y --windowed --add-data="*.png;." myapp.py_

When I run Pyinstaller with the --onefile option, I receive missing .png errors within my application such as ([Errno 2] No such file or directory: 'applogo.png').  The full command I am running to build when errors occur is:

_pyinstaller --clean -y --onefile --windowed --add-data="*.png;." myapp.py_

Any thoughts to if this is a bug, or a problem on my part?
Thanks!!!

**Comment by htgoebel** [comment]
1. Put something like `print(os.cwd(), os.listdir())` near the place you are accessing the file. And check the result.
2. Use archive-viewer to check if the file is included into the archive - which I strongly assume.

**Comment by tbharber** [comment]
> 1. Put something like `print(os.cwd(), os.listdir())` near the place you are accessing the file. And check the result.
> 2. Use archive-viewer to check if the file is included into the archive - which I strongly assume.

Thank you very much for the suggestions.  

I checked and the .png files are included in the top level directory using archive-viewer.  The directory that comes back when I build as a folder is "C:\Users\Tim\Desktop\myapp".  The directory that comes back when I build as a folder is "C:\Users\Tim\Desktop\"  This explains why my application cannot see the attached files.  

I looked over the PyInstaller documentation and do not see what needs to be done to tell my code to actually look into the .exe file structure to get to those files.  Can you point me in the right direction on how to do this?

**Comment by htgoebel** [comment]
Herer it is: https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file-and-sys-meipass
