### ISSUE TITLE
Failed to execute script...

### ISSUE THREAD

**Issue by SaowaluckT** [pyinstaller/pyinstaller#4113]
![image](https://user-images.githubusercontent.com/38277831/54099880-14197180-43ee-11e9-9ff7-83fcd1fe97bd.png)

I built my programe success, but it can't open.
Then I have this error 

Help me pls... 
Thank you
--------------------------------------------------------------
python 3.7
window 64

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.
