### ISSUE TITLE
One binary added with two internal issues.

### ISSUE THREAD

**Issue by wxinbeings** [pyinstaller/pyinstaller#4116]
Building PKG (CArchive) PKG-00.pkg
28720 WARNING: One binary added with two internal names.
28720 WARNING: ('libGLESv2.dll',
 'C:\\Users\\Arvind1\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyQt5\\Qt\\bin\\libGLESv2.dll',
 'BINARY')
28720 WARNING: was placed previously at
28720 WARNING: ('PyQt5\\Qt\\bin\\libGLESv2.dll',
 'C:\\Users\\Arvind1\\AppData\\Roaming\\Python\\Python37\\site-packages\\PyQt5\\Qt\\bin\\libGLESv2.dll',
 'BINARY')

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.
