### ISSUE TITLE
OSError: [Errno 9] Bad file descriptor  os.write(1,b'.')

### ISSUE THREAD

**Issue by 1191149398** [pyinstaller/pyinstaller#4122]
use https://github.com/pyinstaller/pyinstaller/archive/develop.zip

OSError: [Errno 9] Bad file descriptor

use  “os.write(1,b'.')”  print information

pyinstaller -F -w -i

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.
