### ISSUE TITLE
Opencv import not working correctly

### ISSUE THREAD

**Issue by Wtcheesecakes** [pyinstaller/pyinstaller#4124]
This is the error i get, latest pyinstaller, python 3.7.2 64bit
compiled on windows 10 and run on windows 7
```

C:\Users\admin\AppData\Local>rat.exe
Traceback (most recent call last):
  File "rat.py", line 2, in <module>
  File "c:\users\thetr\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "site-packages\cv2\__init__.py", line 3, in <module>
ImportError: DLL load failed: The specified module could not be found.
[1292] Failed to execute script rat
```

**Comment by lstolcman** [comment]
use opencv-python version 3.4.5.20:
`pip uninstall opencv-python`, then `pip install opencv-python==3.4.5.20`

**Comment by m0beenali** [comment]
Any solution guys?

**Comment by martin0258** [comment]
@Wtcheesecakes  @m0beenali Our company has solved the same issue recently, compiled on windows 10 and run on windows server 2008 r2. Our approach may need some additional tuning for your cases, please contact me if you are interested to know.

**Comment by gmywq392** [comment]
@martin0258 exactly same case here, please help! We use pyinstaller v3.4 to build on windows 10 and run the .exe on the client server which is windows server 2008 r2! We run perfectly on our own computers and there was "ImportError: DLL load failed" on the client side...

**Comment by gmywq392** [comment]
well, after some efforts, I simply fix the problem :rofl:

If anybody faced the same situation, maybe the following links will be helpful:
https://social.technet.microsoft.com/Forums/en-US/f7cac36d-cf58-40e8-8509-d36c10ee2a8c/dll-files-missing-inwindow-server-2012-r2?forum=winserver8gen 

https://manage.accuwebhosting.com/knowledgebase/2190/How-to-Install-Desktop-Experience-On-Windows-Server.html

btw,  my develop environment is 中文, so I want to paste the information here too: 

"ImportError: Dll load failed: 找不到指定的模块"

**Comment by bwoodsend** [comment]
Unless there's any evidence to the contrary, I'm going to assume that opencv is incompatible with old windows irregardless of using PyInstaller.
