### ISSUE TITLE
Mismatch between docs and execution (today's version of each)

### ISSUE THREAD

**Issue by kcrossen** [pyinstaller/pyinstaller#4132]
Application does run and is correctly and functioningly packaged already.
https://github.com/kcrossen/CloudWatch_Remote_Monitor

According to here:
https://pyinstaller.readthedocs.io/en/stable/usage.html
and immediately after:
$ pip install --upgrade pyinstaller

this should be legal:
$ pyinstaller -–onefile -–windowed CW_Remote.py

but this is the result:
usage: pyinstaller [-h] [-v] [-D] [-F] [--specpath DIR] [-n NAME]
                   [--add-data <SRC;DEST or SRC:DEST>]
                   [--add-binary <SRC;DEST or SRC:DEST>] [-p DIR]
                   [--hidden-import MODULENAME]
                   [--additional-hooks-dir HOOKSPATH]
                   [--runtime-hook RUNTIME_HOOKS] [--exclude-module EXCLUDES]
                   [--key KEY] [-d [{all,imports,bootloader,noarchive}]] [-s]
                   [--noupx] [-c] [-w]
                   [-i <FILE.ico or FILE.exe,ID or FILE.icns>]
                   [--version-file FILE] [-m <FILE or XML>] [-r RESOURCE]
                   [--uac-admin] [--uac-uiaccess] [--win-private-assemblies]
                   [--win-no-prefer-redirects]
                   [--osx-bundle-identifier BUNDLE_IDENTIFIER]
                   [--runtime-tmpdir PATH] [--bootloader-ignore-signals]
                   [--distpath DIR] [--workpath WORKPATH] [-y]
                   [--upx-dir UPX_DIR] [-a] [--clean] [--log-level LEVEL]
                   scriptname [scriptname ...]
pyinstaller: error: unrecognized arguments: -–onefile -–windowed

While this works as documented:
$ pyinstaller -F -w CW_Remote.py

Certainly hope I've posted this in the right place, pyinstaller has improved enormously since I last used it. Kudos.

**Comment by htgoebel** [comment]
Wow, this is very interesting. It only happens if the scriptname is not given or the provided one does not exist. Try:
```
python3 -m PyInstaller -–onefile -–windowed adjksdjf
python3 -m PyInstaller -–onefile -–windowed
```
Both print the short help as shown above. And some options are missing there.

Which means that argparse does not generate the correct help. Uff.

**Comment by htgoebel** [comment]
> pyinstaller -–onefile -–windowed CW_Remote.py

The second character of your option string is not a dash but a en-dash. I was trapped by this, too, when copying your code.

Now if you wonder why the help doe not show --windows and --onefile: This is becausee both have a short version  (-w and -F), and only one version is shown.
