### ISSUE TITLE
Help me some file .toc is non existent(Window 7)

### ISSUE THREAD

**Issue by KryCool** [pyinstaller/pyinstaller#4137]
When i used pyinstaller -F -w .py it's not working and show message" Failed to execute script ["](url
![Untitled](https://user-images.githubusercontent.com/43307723/54762304-7102fc00-4c26-11e9-9e6d-8286f6834571.png)
)

**Comment by htgoebel** [comment]
This is not en error, but a info-message. "Building ... because missing"
