### ISSUE TITLE
Pyinstaller is creating single exe for one folder mode 

### ISSUE THREAD

**Issue by ntirupathirao18** [pyinstaller/pyinstaller#4139]
The pyinstaller is creating exe rather than folder of libraries,exe in one folder mode (-D) is it  dependent on the libraries size or import packages in the py file

**Comment by ArunAug** [comment]
By running `pyinstaller file.py` will create a disc folder with all the site-packages along with it.
SO the size will be huge.
Use `--onefile` flag will help to create an optimized executable.

Eg: Initially found size 254MB, after converting to single executable using `--onefile` the size reduced to 42MB.

**Comment by ntirupathirao18** [comment]
Thank you @Arunaug One file results in two exe generation while it is running as the exe size is very large its taking time  to call child process itself .By this I got to know that we can't create one folder mode by using spec file of our own.. Correct me if I'm wrong
