### ISSUE TITLE
Pyinstaller not reconised

### ISSUE THREAD

**Issue by MrAWard** [pyinstaller/pyinstaller#4142]
I have added the path to my environment and have installed pyinstaller with pip, but it will not run when called, either in the scripts folder or where my code files are. Needing help to convert my code to an executable.

 The error I get every time is "pyinstaller is not recognised as an internal or external command, operable program or batch file"

I'm using the Anaconda packages and spyder as  my IDE. If there is another convert that works with anaconda, i'll try that

**Comment by ntirupathirao18** [comment]
Well for anaconda environments go the installation path of anaconda if you're using  environments go to environment and open open scripts folder try to open command prompt in there ,later on try uninstaller it will the environment python exe

**Comment by htgoebel** [comment]
No a PyInstaller issue. Please contact your conda support, hey earn money with their software.
