### ISSUE TITLE
AppVeyor fails on Python 3.7 test_stderr_encoding()

### ISSUE THREAD

**Issue by cclauss** [pyinstaller/pyinstaller#4144]
These changes were made in https://github.com/pyinstaller/pyinstaller/commit/af2cc1bb0ad61acd7951b10058f247522fd2cf47#diff-9246853a4b245670cf00a686ae8ddf9d  @bjones1

**Comment by bjones1** [comment]
Thanks for tracking this down! I've reverted it in 824559fb0f25c14e599650c1662e882e06aa0efd.
