### ISSUE TITLE
Copy entire package if no hook exists

### ISSUE THREAD

**Issue by lkollar** [pyinstaller/pyinstaller#4145]
We are running PyInstaller in a sandbox environment where only the application's (and PyInstaller's) dependencies are installed. Some of the dependencies are internal libraries which contain several native extensions, so at the moment many of these need a hook file. I'm looking for ways to remove the need for hooks to simplify the workflow.

Is there a way in PyInstaller to specify that any imported package without a hook should be copied with all its contents? I spent some time looking through the documentation and source code, but couldn't find anything like this.

If this is not possible today, but it would be considered as an enhancement, I'd be interested in contributing to this feature.

**Comment by bjones1** [comment]
I once wrote this and got it working, but was disappointed with the results -- the packaged files it produces are huge, because EVERYTHING without a hook gets copied. Unfortunately, I don't think I kept my WIP. Instead, I recommend generous use of the collect_all function in a hook; it will make most packages work with just a two-line hook (import collect_all then call it).

**Comment by lkollar** [comment]
My current solution is to use `collect_submodules` and that seems to do the job for all our extensions. Like you said it takes only two lines, but we have copy these two lines across a growing number of hook files.

I'm still interested in finding a way to eliminate the hooks entirely or at least reduce the duplication and somehow reuse the same hook implementation for multiple packages.

**Comment by bjones1** [comment]
That sounds reasonable. One way to eliminate hooks is to add dummy imports, typically in an `__init__.py`.

``` Python
if false:
    # Freeze support -- list all dynamically-imported modules.
    import foo
    import foo.bar
```

**Comment by lkollar** [comment]
@bjones1 when you say your implementation copied everything, did you still rely on tracking imports to identify dependencies, or you mean that you copied all packages? If it still tracked imports, I'm surprised that caused a big jump in size, since only packages which are actually used by the application should be copied. I might be missing something.

**Comment by bjones1** [comment]
Hmmm. I looks like I actually didn't delete the branch where I was playing with this. It's at https://github.com/bjones1/pyinstaller/tree/default_hook if you're interested.

**Comment by lkollar** [comment]
Thanks, that's really interesting, I will definitely check it out.

**Comment by bjones1** [comment]
Sounds good. I'll go ahead and close this for now, but feel free to comment / reopen.
