### ISSUE TITLE
Unable to start application on double-clic since macOS 10.14.4

### ISSUE THREAD

**Issue by ardeidae** [pyinstaller/pyinstaller#4152]
I develop an application for my personnal use:
https://github.com/ardeidae/taskcounter

It works fine. 

I've just updated my macOS to the 10.14.4 and now, I am not able to start the application.
It starts and closes immediately.

It works if I run `open Taskcounter.app` but not on double-clic on the .app.

I'm using latest develop version for pyinstaller.

```
python --version
Python 3.6.6
```

I tried to rebuild with `--onedir`: I can start the application.
I tried to rebuild with `--onfile`: I can start the application.
I tried to rebuild with `--onedir -w`: FAILED to start application.
I tried to rebuild with `--onfile -w`: FAILED to start application.

From the console.app, here are the logs when I try to start the application:

```
par défaut	13:44:35.460029 +0200	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Taskcounter, ready, updating active tracking timer
par défaut	13:44:35.460258 +0200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Taskcounter
par défaut	13:44:35.901615 +0200	launchservicesd	CHECKIN:0x0-0x134134 12693 com.ardeidae.taskcounter
par défaut	13:44:35.904699 +0200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Taskcounter
erreur	13:44:35.985295 +0200	tccd	Failed to copy signing info for 12693, responsible for file:///Applications/Taskcounter.app/Contents/MacOS/Taskcounter: #-67062: Error Domain=NSOSStatusErrorDomain Code=-67062 "(null)"
par défaut	13:44:35.988856 +0200	tccd	-[TCCDAccessIdentity staticCode]: static code for: identifier com.ardeidae.taskcounter, type: 0: 0x7fea8443a890 at /Applications/Taskcounter.app
par défaut	13:44:36.052727 +0200	launchservicesd	CHECKIN:0x0-0x135135 12694 com.ardeidae.taskcounter
par défaut	13:44:36.056521 +0200	loginwindow	-[PersistentAppsSupport applicationReady:] | App: Taskcounter, ready, updating active tracking timer
par défaut	13:44:36.056954 +0200	loginwindow	-[ApplicationManager checkInAppContext:refCon:eventData:] |      checked in app : Taskcounter
par défaut	13:44:36.354244 +0200	Taskcounter	Current system appearance, (HLTB: 1), (SLS: 0)
par défaut	13:44:36.355066 +0200	Taskcounter	Post-registration system appearance: (HLTB: 1)
par défaut	13:44:36.519057 +0200	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Taskcounter, _appTrackingState = 2
par défaut	13:44:36.519083 +0200	loginwindow	-[PersistentAppsSupport applicationQuit:] | App: Taskcounter, quit, updating active tracking timer
par défaut	13:44:36.546610 +0200	loginwindow	-[PersistentAppsSupport applicationQuit:] | for app:Taskcounter, _appTrackingState = 2
```

Is it an already known problem? Is there a workaround?

**Comment by ardeidae** [comment]
Does anyone have the same problem?
Can this be an isolated case?

**Comment by ehendrix23** [comment]
Just tried to create an app bundle myself. Compiled app works. I can also execute it directly from Terminal <App Bundle>.app/Contents/MacOS/<executable>

But, if I just do open <App Bundle> it quits immediately. In console I can see the same error: "Failed to copy signing info for".

**Comment by ehendrix23** [comment]
FYI,
Just followed the instructions as provided here: https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing

Still exists immediately but not getting that issue reported anymore.

**Comment by htgoebel** [comment]
Make sure your application is not writing any data to stdout or stderr.
