### ISSUE TITLE
pyinstaller cannot find pywin32-ctypes

### ISSUE THREAD

**Issue by BrendanSimon** [pyinstaller/pyinstaller#4153]
I'm reopening this as a new issue, as there was no response to a comment on and older closed issue (#3892).

Pyinstaller 3.4 and the development version cannot find pywin32-ctypes, even though it is installed.  If I manually run the python interpreter and manually import the module then the module is successfully imported.

The solution of brute force delete of the files did not work for me (reported in #3892).

I've tried so many combinations of PyInstaller (release and develop), pywin32, pywin32-ctypes, pypiwin32.

Nothing seems to get rid of this problem.

I have multiple installs of Python. Python36-32, Python36, Python37-2 and Python37. None of the pythons are in my PATH. I have uninstalled PyInstaller from all installations, and reinstalled PyInstaller only for the install I'm interested in (Python36-32).

How, How, How can I get rid of this road-blocking issue ?

**Comment by chrisdoman** [comment]
Same issue with 2.7

**Comment by chrisdoman** [comment]
Worked for me - https://stackoverflow.com/questions/14718414/pyinstaller-does-not-recognize-downloaded-pywin32?rq=1#

**Comment by htgoebel** [comment]
solution provided.
