### ISSUE TITLE
Pyinstaller and Mixer

### ISSUE THREAD

**Issue by Bernardoow** [pyinstaller/pyinstaller#4156]
Hi!

I tried use mixer and pyinstaler but when I execute the program this error happen AttributeError: 'MixerProvider' object has no attribute 'pybool'.

I think I need create some hook to use this. (https://pythonhosted.org/PyInstaller/hooks.html)

Someone have been use these both libs?

**Comment by htgoebel** [comment]
This is a issue tracker, not a forum. Question shall go to the mailinglist.
