### ISSUE TITLE
after freeze：multiprocess start many many mainprocess on suse12

### ISSUE THREAD

**Issue by JackYangzg** [pyinstaller/pyinstaller#4157]
pyinstaller: 3.4
python: 3.7 (anaconda5.3.1)
linux: suse12
library: pandas, sklearn, multiprocess and so on

I using pyinstaller to freeze my script, when run the freeze binary, the mainprocess start many times. when I using "ps -ef | grep ***" I can find many many processes. but direct run the script It's Ok.

**Comment by JMSwag** [comment]
@JackYangzg Did you follow the [recipe](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing)?

**Comment by JackYangzg** [comment]
> @JackYangzg Did you follow the recipe?

Thanks。
I have solve it.

previous: I write my boot.py like this:
```
import xxx
import  xxx
import multiprocess

if __name__ == "__main__":
    multiprocessing.freeze_support()
    xxxxxxxx
    xxxxxxxx
```

Now I modify it like:

```
if __name__ == "__main__":
    import multiprocess
    multiprocessing.freeze_support()
    import xxx
    import  xxx
    xxxxxxxx
    xxxxxxxx
```

**Comment by JMSwag** [comment]
👍🏾
