### ISSUE TITLE
application restart a main process while run with multiProcess module

### ISSUE THREAD

**Issue by testerclub** [pyinstaller/pyinstaller#4159]
pyinstaller : 3.4
python : 3.6.8 64
os : windows10 64

I run application packaged by pyinstaller v3.4, it restart a new main UI, view logs found the code abort in multiprocess module

**Comment by galeo** [comment]
I have met the same problem.

**Comment by stravassac** [comment]
Same problem
Python 3.6.7
PyInstaller==3.4
os: Ubuntu 18.04
code to reproduce:
'''
from joblib import Parallel, delayed

def main():
    print("ok")

if __name__ == "__main__":
    main()
'''

**Comment by stravassac** [comment]
after read https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing
it work now with
```
import multiprocessing
from joblib import Parallel, delayed
import sys

def main():
    print(sys.argv)

if __name__ == "__main__":
    multiprocessing.freeze_support()
    main()
```

**Comment by bwoodsend** [comment]
The processes still running in background issue is #4104.
