### ISSUE TITLE
How to use pyinstaller to process multiple files

### ISSUE THREAD

**Issue by liguangzi** [pyinstaller/pyinstaller#4160]
My main.py contains a lot of libraries, using pyinstaller main.py to generate exe files, but there will be no module name problem after execution.

**Comment by henrykironde** [comment]
@liguangzi, is that an open source project, and if so could you just paste the link here to see exactly what you mean. Many folks here could be of help

**Comment by htgoebel** [comment]
THis feature is calles "MERGE" and is currentyl not working. See #4303
