### ISSUE TITLE
linux Segmentation Fault when runing without sudo 

### ISSUE THREAD

**Issue by Czaki** [pyinstaller/pyinstaller#4161]
I have problem with build my program under ubuntu 16.04. I normally work on ubuntu 18.04 and when I build program on it and then it run. But When I build it on docker image of ubuntu 16,04 then it fails with segmentation fault when runned by normal user (but it runs with sudo privileges) 

here is gdb output
 
```Starting program: /home/czaki/Pobrane/tmp/PartSeg/PartSeg_exec 

Program received signal SIGSEGV, Segmentation fault.
__GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
51	../sysdeps/unix/sysv/linux/raise.c: Nie ma takiego pliku ani katalogu.
(gdb) bt
#0  __GI_raise (sig=<optimized out>) at ../sysdeps/unix/sysv/linux/raise.c:51
#1  0x000000000040531c in ?? ()
#2  0x0000000000403170 in ?? ()
#3  0x00007ffff75e4b97 in __libc_start_main (main=0x401a70, argc=1, argv=0x7fffffffdc78, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdc68) at ../csu/libc-start.c:310
#4  0x0000000000401a9e in ?? ()
```

The source code is here: https://github.com/4DNucleome/PartSeg/tree/develop
Docker file is in `build_utils` directory 
after creating docker image the `build_partseg.sh` need to be launch inside docker. 

Have you any suggestion how to debug it? I try under pyinstaller3.4 and current develop.

**Comment by htgoebel** [comment]
Most probably the libc on 16.04 is too old. Try building there

If this fails, too, you shoudl run with LC_ALL=C so the error messages are in english.
