### ISSUE TITLE
libeay32 DLL Error -> Could not find QtWebEngineProcess.exe

### ISSUE THREAD

**Issue by sha-fuq** [pyinstaller/pyinstaller#4163]
Hi, Due to a problem using Pyinstaller (which i was using without an issue for a very long time) i reinstalled Anaconda and created a new virtual environment. I got past 10 other issues that i faced but this one is just driving me crazy. When I try to run pyinstaller with the following command:

    pyinstaller -w --name=project --clean "C:\Users\ME\Documents\_My Documents\my_project\Build\1.10\mainform.py"

I get the result (and error):

```
75 INFO: PyInstaller: 3.4
76 INFO: Python: 3.7.1
77 INFO: Platform: Windows-10-10.0.17134-SP0
78 INFO: wrote C:\Users\ME\Documents\_My Documents\my_project\Build\Compile\project.spec
84 INFO: UPX is not available.
84 INFO: Removing temporary files and cleaning cache in C:\Users\ME\AppData\Roaming\pyinstaller
88 INFO: Extending PYTHONPATH with paths
['C:\\Users\\ME\\Documents\\_My Documents\\my_project\\Build\\1.10',
 'C:\\Users\\ME\\Documents\\_My Documents\\my_project\\Build\\Compile']
88 INFO: checking Analysis
89 INFO: Building Analysis because Analysis-00.toc is non existent
89 INFO: Initializing module dependency graph...
95 INFO: Initializing module graph hooks...
98 INFO: Analyzing base_library.zip ...
4542 INFO: running Analysis Analysis-00.toc
4564 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\ME\Anaconda3\python.exe
5339 INFO: Caching module hooks...
5345 INFO: Analyzing C:\Users\ME\Documents\_My Documents\my_project\Build\1.10\mainform.py
5386 INFO: Processing pre-find module path hook   distutils
5994 INFO: Processing pre-safe import module hook   win32com
12112 INFO: Processing pre-safe import module hook   six.moves
14354 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
15231 INFO: Processing pre-find module path hook   site
15232 INFO: site: retargeting to fake-dir 'C:\\Users\\ME\\Anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
19853 INFO: Loading module hooks...
19853 INFO: Loading module hook "hook-distutils.py"...
19856 INFO: Loading module hook "hook-encodings.py"...
19967 INFO: Loading module hook "hook-lib2to3.py"...
19971 INFO: Loading module hook "hook-numpy.core.py"...
20073 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
20083 INFO: Loading module hook "hook-numpy.py"...
20084 INFO: Loading module hook "hook-pkg_resources.py"...
21217 INFO: Loading module hook "hook-pycparser.py"...
21487 INFO: Loading module hook "hook-pydoc.py"...
21488 INFO: Loading module hook "hook-PyQt5.py"...
22060 WARNING: Hidden import "PyQt5.sip" not found!
22060 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
22171 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
22358 INFO: Loading module hook "hook-PyQt5.QtWebEngineWidgets.py"...
23312 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
23759 INFO: Loading module hook "hook-pytest.py"...
25255 INFO: Loading module hook "hook-pythoncom.py"...
25917 INFO: Loading module hook "hook-pywintypes.py"...
26586 INFO: Loading module hook "hook-scipy.py"...
26589 INFO: Loading module hook "hook-setuptools.py"...
27565 INFO: Loading module hook "hook-sysconfig.py"...
27567 INFO: Loading module hook "hook-win32com.py"...
27732 INFO: Loading module hook "hook-xml.dom.domreg.py"...
27733 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
27734 INFO: Loading module hook "hook-xml.py"...
27735 INFO: Loading module hook "hook-PyQt5.QtNetwork.py"...
Unable to find "C:\Users\ME\Anaconda3\Library\bin\libeay32.dll" when adding binary and data files.
```

I tried it in both the virtual environment terminal and the root one. I Googled for the libeay32.dll error but nothing valuable showed up. I found this https://github.com/pyinstaller/pyinstaller/issues/3511 but the dll files are not located under the Anaconda directory (which is what i have and am using).

I really don't know what to do. Please help if you can. Thanks!

**Comment by sha-fuq** [comment]
I found this: https://github.com/pyinstaller/pyinstaller/issues/4048

But when I change the file hook-PyQt5.QtNetwork.py located in C:\Users\ME\Anaconda3\Lib\site-packages\PyInstaller\hooks to the code given at that reference, even though pyinstaller completes without an error, when I try to launch the exe file under dist it prompts an error saying: Failed to execute script mainform

I could provide the whole output if need be.

**Comment by sha-fuq** [comment]
I changed my environment to the Anaconda root. then built the program with pyinstaller. it built as it did before with no errors (couple of warnings but no errors). but this time when i ran the exe it didnt give any errors. instead it did nothing. This (nothing happening/launching when exe is ran) was the main reason i had reinstalled anaconda in the first place. So after days of struggling i'm at the same point i started!

https://github.com/pyinstaller/pyinstaller/issues/1767 this is pretty much what i'm facing. I did a conda update --all with no success towards my problem. I have no clue how to continue since i get no errors. Like the case above i only see my exe under the resource manager for a couple of seconds, then it changes its status to terminating and clears from there too. nothing under the task manager what-so-ever.

should i downgrade something? any other ideas?

**Comment by sha-fuq** [comment]
i learned that i could see the error if i removed the -w from the launch command and ran the program under the command prompt. now i see where my error is:

Could not find QtWebEngineProcess.exe

i found this: https://github.com/pyinstaller/pyinstaller/pull/3233

it says to change to the development branch. i have version 3.4. how can i change pyinstaller version to development version using anaconda? I have been reading online but couldn't find the solution yet. everything is explained via pip but i'm using conda. Any help will be appreciated.

**Comment by bjones1** [comment]
See https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#getting-the-latest-version.

**Comment by sha-fuq** [comment]
I did read it. As i mentioned before im using conda not pip. Its updated fully. Pyinstaller is already at version 3.4. This is the version that had your bug fix implemented. But the issue persists in my case.

I tried downloading the latest development from tgis github. With it i tries changing only the two files that had the mentioned qtwebengineprocess in it. I copies and overwrited the ones that were there. It didnt work. Then i copied all of the files and folders and replaced the original ones. Again it didnt work.

I tried downgrading pyinstaller. It still didnt work. I have a pure anaconda environment. Im using the python thats in it 3.7.3 if i recall. I have a fully updated windows. The pyqt installed is 5.9.2 (im writing this from mobile so i cant check it right now). I read on the other case that you tested kt on pyqt 5.11? Maybe that it the case? But my pyqt is the latest anaconda (conda cloud) offers.

I really would appreciate any help.

**Comment by bjones1** [comment]
I don't use or know Anaconda, so I can't help there. Did you install pyinstaller via conda or pip? The bug fix you need is in the development version.

**Comment by sha-fuq** [comment]
I use conda not pip. Here is the link that shows the pyinstaller version im using. 

https://anaconda.org/conda-forge/pyinstaller

Its the latest one. If there is a fix within the code i could try that (like in this file change this to that). Im really lost. I have a new version of my application that i need to compile. But due to this issue its bee. Waiting for about 2 weeks. 

Thank you for your reply.

**Comment by bjones1** [comment]
Either figure out how to install from github using conda, or uninstall using conda and reinstall using pip.
