### ISSUE TITLE
Alpine Can not find libc.musl-x86_64.so.1 in path ldd 

### ISSUE THREAD

**Issue by dsanchezseco** [pyinstaller/pyinstaller#4164]
Hi i'm trying to pack my scripts in a jenkins worker running an alpine container and when running pyinstaller the following is printed https://hastebin.com/nenobajivi which fininsh without errors but when executing the binary there's the following error

`dist/script: line 1: syntax error: unexpected "("`

i tried with the lattest development version of pyinstaller, --noupx, --onedir and --onefile with the same result.
 
But on an ubuntu machine works out of the box. I guess the problem is with the glibc/musl problem of alpine, but trying different docker images with various fixes didn't work, so i'm not 100% of that being the problem.

the versions are:

python:3.7-alpine - python 3.7.3
python:3.6-alpine - python 3.6.8
pyinstaller 3.4 and lattest dev

**Comment by dsanchezseco** [comment]
can be because is being executed with sh instead of bash? i didn't try it cause is not my image but on ubuntu when doing a 

> sh script 

returns the same error so maybe is related

**Comment by DevOpsJon** [comment]
Have you seen https://github.com/gliderlabs/docker-alpine/issues/48

Sadly the workaround doesn't seem to work at the moment: https://github.com/six8/pyinstaller-alpine

But its promising until we can maybe get some official Alpine support for pyinstaller.

**Comment by alexks02** [comment]
Hi there! Any updates? (-:

**Comment by htgoebel** [comment]
@dsanchezseco 
1. The hatbin is not available, please post the *relevant* parts her at github.
2. You try to run the exe as a shell script, while it is no shell-script, but an executable. I can not see how this should be  related to pyinstaller. Closing.
