### ISSUE TITLE
pefile and macholib should be only required on the respective platforms

### ISSUE THREAD

**Issue by lkollar** [pyinstaller/pyinstaller#4166]
`pefile` should only be needed on Windows and `macholib` on macOS, but they are required on all platforms:

https://github.com/pyinstaller/pyinstaller/blob/317aac20c4f6f6d3aa1aa626c26d2a1266aa94fa/setup.py#L25-L26

Would it make sense to move these under platform-dependent code paths in `setup.py`?

**Comment by bjones1** [comment]
Closed by 8365f1b95c8b01a674ac0ea36a18eb900a97cf65.
