### ISSUE TITLE
Having been run as an .exe django admin panel hides models

### ISSUE THREAD

**Issue by Aroxed** [pyinstaller/pyinstaller#4167]
I created a Django project by adding some apps with models and admin.py.
My environment is Python 3.7, Pyinstaller 3.4, Windows 7.
I try to use Django admin panel but after compiling with PyInstaller they have been disappeared. Actually I can see User and User groups models only.
'python manage.py runserver' works normally: I'm able to edit all the models I have. 
Did anyone run into that problem? Is there any workaround to it?

Thanks.

**Comment by Aroxed** [comment]
Could anyone explain how pyInstaller or Django detects which apps to show in the Admin Panel?

**Comment by Aroxed** [comment]
I've figured out. The source files (admin.py and models.py) or their compiled .pyc versions of each model must be presented in the "dist\<project name>\apps\<app name>\" folder at least when the .exe file is being started. After that these files might be deleted. Please tell me if there is another workaround.

**Comment by JoveCat** [comment]
> I created a Django project by adding some apps with models and admin.py.
> My environment is Python 3.7, Pyinstaller 3.4, Windows 7.
> I try to use Django admin panel but after compiling with PyInstaller they have been disappeared. Actually I can see User and User groups models only.
> 'python manage.py runserver' works normally: I'm able to edit all the models I have.
> Did anyone run into that problem? Is there any workaround to it?
> 
> Thanks.

I encountered this problem, can you tell me how to solve it

**Comment by jamestch** [comment]
> > I created a Django project by adding some apps with models and admin.py.
> > My environment is Python 3.7, Pyinstaller 3.4, Windows 7.
> > I try to use Django admin panel but after compiling with PyInstaller they have been disappeared. Actually I can see User and User groups models only.
> > 'python manage.py runserver' works normally: I'm able to edit all the models I have.
> > Did anyone run into that problem? Is there any workaround to it?
> > Thanks.
> 
> I encountered this problem, can you tell me how to solve it

You should copy  "<appname>/admin.py" and "<appname>/model.py", these files of your django app to the "dist/manage/<app name>" folder. Then you run "manage.exe runserver", Django Admin Panel works fine.
