### ISSUE TITLE
Problem creating .exe when importing Pandas

### ISSUE THREAD

**Issue by ozoraa** [pyinstaller/pyinstaller#4169]
Hi there,

I am trying to create an .exe-file from an existing python file via PyInstaller. For the sake of simplicity I wrote a very simple file called hello.py which looks like this:

---------------------------------
# hello.py
import pandas
print('hello')
---------------------------------

Leaving out "import pandas" I don't have a problem at all, PyInstaller will create a perfectly working hello.exe. However, if I do import pandas, I always get an exception:

Exception: Cannot find existing PyQt5 plugin directories.

Of course I googled this issue and tried various suggestions like installing PyQt5, updating Pandas, Python and PyInstaller or even manipulating the hook-pandas.py file as described in another GitHub issue (#2978), but none of it worked, the error message stays the same.

I also thought that the problem might lie in incompatible versions, which are:
Python 3.7.0
PyInstaller 3.4
Pandas 0.24.2
Anaconda 5.3.0

It would be great if someone had solved this problem and could help me out with this!
Thank you :)

**Comment by bjones1** [comment]
This is (probably) fixed in the development version. Use that instead -- see https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html#getting-the-latest-version.

**Comment by ozoraa** [comment]
Thank you I think this solved my problem :)
