### ISSUE TITLE
Modules Using "VERSION" File Will Fail To Run

### ISSUE THREAD

**Issue by leomoon** [pyinstaller/pyinstaller#4172]
There are a few modules that have started using external file `VERSION` to define version number inside their `__init__` file like below:
`__version__ = (Path(__file__).parent / 'VERSION').read_text().strip()`

Compiled PyInstaller project will fail to run.

These are the modules:
tinycss2
cairocffi
cairosvg

I know we can change that line to something like below and that will solve the problem:
`__version__ = '1.0.0'`

Or write a hook to include the `VERSION` file but is there a better way to do this?

**Comment by leomoon** [comment]
I've written this very quickly. This script will check the module you want and it will read the version number from `VERSION` file if it exists and insert it into the line that has `__version__` in the `__init__` file. This way you will not get PyInstaller error that the `VERSION` file is not found...

To use it, just add `verFix('MODULE-NAME')` at the end of this script and run it. It should be compatible with Windows, Linux and macOS.

The example below will fix `cairocffi`, `cairosvg` and `tinycss2` modules.

```
#!usr/bin/env python
#-*- coding: utf-8 -*-

import os
import sys
import fileinput

def lineReplace(filename, search, replace, unixEol=False):
    x = fileinput.input(files=filename, inplace=1)
    for line in x:
        line = line.strip('\r\n')
        if search in line:
            line = replace
        print(line)
    x.close()
    if unixEol:
            fileContents = open(filename,"r").read()
            f = open(filename,"w", newline="\n")
            f.write(fileContents)
            f.close()

def verFix(moduleName):
    if sys.platform.startswith('win32'): #if win, use backslash for path
        slash = '\\'
    else:
        slash = '/'
    spackages = next(p for p in sys.path if 'site-packages' in p) #find site-packages forlder
    spackages = spackages+slash+moduleName+slash
    if os.path.isfile(spackages+'VERSION'):
        ver = open(spackages+'VERSION').readline()
    lineReplace(spackages+'__init__.py' , 'VERSION =', 'VERSION = __version__ = "'+ver+'"', True)

verFix('cairocffi')
verFix('cairosvg')
verFix('tinycss2')
```

**Comment by leomoon** [comment]
I've written this very quickly. This script can check the module you want and if `VERSION` file exists, it will read the version number and edit its `__init__` file so PyInstaller will not give `VERSION file not found` error.

This will work in Windows, Ubuntu, and macOS.

```
#!usr/bin/env python
#-*- coding: utf-8 -*-

import os
import sys
import fileinput

def lineReplace(filename, search, replace, unixEol=False):
    x = fileinput.input(files=filename, inplace=1)
    for line in x:
        line = line.strip('\r\n')
        if search in line:
            line = replace
        print(line)
    x.close()
    if unixEol:
            fileContents = open(filename,"r").read()
            f = open(filename,"w", newline="\n")
            f.write(fileContents)
            f.close()

def verFix(moduleName):
    search = 'site-packages'
    if sys.platform.startswith('linux'):
        search = 'local'
    if sys.platform.startswith('win32'): #if win, use backslash for path
        slash = '\\'
    else:
        slash = '/'
    spackages = next(p for p in sys.path if search in p) #find site-packages forlder
    spackages = spackages+slash+moduleName+slash
    if os.path.isfile(spackages+'VERSION'):
        ver = open(spackages+'VERSION').readline()
        lineReplace(spackages+'__init__.py' , 'VERSION =', 'VERSION = __version__ = "'+ver+'"', True)

verFix('cairocffi')
verFix('cairosvg')
verFix('tinycss2')
```

**Comment by htgoebel** [comment]
Please see the manual on how to add data-files and how to access files at runtime
