### ISSUE TITLE
the module cv2 cann't work

### ISSUE THREAD

**Issue by LKMMKL** [pyinstaller/pyinstaller#4176]
### but I find some methods of cv2 cann't work after packaged.
`import cv2
cap = cv2.VideoCapture("E:/pythonPro/paper1/source/tianqi.mpg")
size = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))
print("size: "+str(size))`
### Can you give me some advice?

**Comment by Nyanyan** [comment]
I have a little different bug, too. When I get the frame count of the video, it always returns bigger number than the real frame count.
Someone please help us...!

**Comment by Nyanyan** [comment]
I found how to fix it.
Use cx_Freeze(https://anthony-tuininga.github.io/cx_Freeze/) instead of pyinstaller.
it worked successfully!

**Comment by rokm** [comment]
Very likely fixed by pyinstaller/pyinstaller-hooks-contrib#13.
