### ISSUE TITLE
Latest Windows Update Broke PyInstaller

### ISSUE THREAD

**Issue by calonmerc** [pyinstaller/pyinstaller#4183]
PyInstaller worked to generate a .exe file last week, Windows updates were performed over the weekend and attempting to build now gives a permissions error. 

Command that previously worked from `C:\users\calonmerc\`: `pyinstaller C:\Users\calonmerc\Nextcloud\Private\Python\encrypt.py`

[Output of error](https://gist.github.com/calonmerc/532c09ce588777bd08ee3b3250a34cee)

Have verified that encrypt.py script runs correctly when run natively from Python.

*Versions*
PyInstaller: 3.5.dev0+b54a15d72e
Python: 3.7.0
Platform: Windows-10-10.0.17763-SP0

**Comment by htgoebel** [comment]
Please contact your administrator.

**Comment by calonmerc** [comment]
Unsure how this is invalid when an update to PyInstaller is what fixed it. Great support!

**Comment by htgoebel** [comment]
> Great support!

You get what you pay for. Quick question: How much did you pay me for providing support?
