### ISSUE TITLE
adding data in subfolder does not work with pkg_resource or importlib

### ISSUE THREAD

**Issue by gsemet** [pyinstaller/pyinstaller#4185]
Hi,

If I want to use jinja with pyinstaller I need to have my data available in a subfolder, for example "templates", of my application.

I can add them so they could be loaded at the root of my application:
```
tpl_loc = os.path.dirname(get_module_file_attribute('mylib.subm1.subm2.templates'))
data = [(os.path.join(tpl_loc, 'master.html.j2'), 'mylib'),
```

It creates in the bundle a folder named `mylib` with my file within.

They can then be loaded by `pkgutil.get_data`, unfortunately, jinja only provides `PackageLoader` that wants a subfolder, defaulted to "templates"). 

I tried:
```
data = [(os.path.join(tpl_loc, 'master.html.j2'), 'mylib.subm1.subm2.templates'),
```
and
```
data = [(os.path.join(tpl_loc, 'master.html.j2'), 'mylib/subm1/subm2/templates'),
```
In both cases, the resource loader cannot find it (pkg_resource says me: `NotImplementedError: Can't perform this operation for unregistered loader type`).

My opinion is that everybody should migrate to `importlib.resource`.

**Comment by gsemet** [comment]
My solution for the moment:
add a try/catch using PackageResource, on `NotImplementedError`, use a `FileSystemLoader`, reconstructing the folder using `sys._MEIPASS`.

**Comment by htgoebel** [comment]
Please see #2748 and #2717. Ad long as #2717 is not implemented (want to help?) there will be no other solution.
