### ISSUE TITLE
psapi.GetModuleBaseNameA returning question mark after freezing with PyInstaller

### ISSUE THREAD

**Issue by Donaldduck8** [pyinstaller/pyinstaller#4186]
Environment:
Windows 10 Home V1803 (Build 17134.706)
Python v2.7.15:ca079a3ea3
PyInstaller 3.5.dev0+b54a15d72e
LiClipse 5.2.2.201903261549

Hello! Just wanted to say thank you for all the work on PyInstaller, it's much less clunky and much more elegant to use than the alternatives I found.

The following code is taken from the memorpy project, just cut down slightly for brevity. It opens a process using windll.kernel32, then uses windll.psapi.getModuleBaseNameA to obtain the process name. I apologize that the sample code is not as tiny as possible.
```python
from ctypes import  sizeof, windll, create_string_buffer, c_ulong, byref
import time

psapi       = windll.psapi
kernel32    = windll.kernel32

hModule = c_ulong()
count = c_ulong()
modname = create_string_buffer(100)
PROCESS_QUERY_INFORMATION = 0x0400
PROCESS_VM_READ = 0x0010

hProcess = kernel32.OpenProcess(PROCESS_QUERY_INFORMATION | PROCESS_VM_READ, False, PID)
if hProcess:
    #These two lines are the important ones
    psapi.EnumProcessModules(hProcess, byref(hModule), sizeof(hModule), byref(count))
    psapi.GetModuleBaseNameA(hProcess, hModule.value, modname, sizeof(modname))
    print(modname.value)
    time.sleep(2) 
kernel32.CloseHandle(hProcess)
```

You can replace PID with the PID of any named process currently running on your system, such as your web browser. When running this code inside LiClipse, it correctly prints the process name. After freezing the code with `pyinstaller --noupx`, it only prints a question mark. Freezing the same code with `py2exe` does actually print the process name correctly, but it does not properly support one-file mode on win64. Hence my posting the issue here.

I compared the contents of PYZ-00.pyz after using PyInstaller with the contents of library.zip after using py2exe and found that py2exe froze these additional .pyc files:
* _ctypes.pyc
* _hashlib.pyc
* bz2.py
* select.py
* StringIO.pyc
* struct.pyc
* unicodedata.pyc

I tried adding these to the `hiddenimports` but I'm not sure if I did it correctly since it did not fix the problem. I'm new to python and quite honestly I'm in over my head with this issue. Any help would be greatly appreciated!

**Comment by bjones1** [comment]
Perhaps this will help? https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Win-Load-External-DLL Different (DLLs) but possibly related?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
