### ISSUE TITLE
ModuleNotFoundError: No module named 'wx'

### ISSUE THREAD

**Issue by stef-pellegrino** [pyinstaller/pyinstaller#4188]
With

- PyInstaller 3.4
- Python 3.7
- wxPython 4.0.4 (fedora 28) 

test.py
```
import wx

app = wx.App()

frame = wx.Frame(None, title='Simple application')
frame.Show()
app.MainLoop()
```

```shell
pyinstaller --clean --windowed --onefile test.py
```
When I try to launch "test", I get
**ModuleNotFoundError: No module named 'wx'**

Of course, it works with a "simple"
`python3 test.py`

**Comment by stef-pellegrino** [comment]
My fault, env error

**Comment by lopes-gustavo** [comment]
How was it an `env error`. I'm getting this very same error and I cannot manage to understand where I may be doing something wrong

**Comment by guysoft** [comment]
Getting this too, more info would help
