### ISSUE TITLE
Don't want a librarie be frozen

### ISSUE THREAD

**Issue by Loumardes** [pyinstaller/pyinstaller#4189]
I want to keep an imported file as a .py 

I don't know how
Is this code the right way to proceed ?

```
    def _make_spec_file(self):
        specFile = distutils.command.bdist_rpm.bdist_rpm._make_spec_file(self)
        specFile.insert(0, "import_script.py")     #"%define _unpackaged_files_terminate_build 0%{nil}"
        return specFile
```
I want user be able to add content without python installed trough theses files

Thanks you for the work done, pyinstaller work just fine

**Comment by bjones1** [comment]
A simple approach is to use the --debug=noarchive command-line option, which keeps all frozen files out of the archive. See https://pyinstaller.readthedocs.io/en/stable/usage.html#how-to-generate.

**Comment by Loumardes** [comment]
Thanks you, it worked
