### ISSUE TITLE
PyInstaller cannot check for assembly dependencies.

### ISSUE THREAD

**Issue by EPXer** [pyinstaller/pyinstaller#4194]
PyInstaller cannot check for assembly dependencies.
Please install pywin32-ctypes.

pip install pywin32-ctypes

安装了也不起作用

**Comment by lphamduy** [comment]
You Need to download and install Git in your PC..( make sure download right one 32/64 bits)

**Comment by archarchon** [comment]
I had Git installed, but I downloaded the latest version. I still have the same error
