### ISSUE TITLE
Is PySide2 hooking numpy by default for any reason?

### ISSUE THREAD

**Issue by cishisedis** [pyinstaller/pyinstaller#4198]
https://github.com/pyinstaller/pyinstaller/blob/b54a15d72e81e39cde0811d2b7442b09e658801d/PyInstaller/hooks/hook-PySide2.py#L27

So why does this funny hiddenimports ever exist if the author knew perfectly that it shouldn't?
If there is a very good reason for not removing it, please document the reason.

**Comment by bjones1** [comment]
This was fixed in 5b5791285332003940f4bc70c32bb0cf10a32917. Please reopen if there are still problems.
