### ISSUE TITLE
pip install pyinstaller produces Error:  AttributeError: module 'enum' has no attribute 'IntFlag'

### ISSUE THREAD

**Issue by doverradio** [pyinstaller/pyinstaller#4199]
If you have problems to get your application running, please first

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If your problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for GitHub's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.

**Otherwise we will not be willing to help you.**

Please be aware that PyInstaller is a voluntary project. We spent quite some time
writing these guides to make both of our lives easier. Please
understand that we are not willing to spend our spare time to help you if you
are not willing to help on your side. (Sorry for having to said this, but we
are tired of being asked the same questions over and over again.)

First, I tried finding this specific issue by first searching the issues and checking the if things go wrong guide: a solution was not found in either.

I simply wanted to install pyinstaller, so I did a pip install:

`pip install pyinstaller`

This resulted in this:

```
Downloading https://files.pythonhosted.org/packages/03/32/0e0de593f129bf1d1e77eed562496d154ef4460fd5cecfd78612ef39a0cc/PyInstaller-3.4.tar.gz (3.5MB)
    100% |████████████████████████████████| 3.5MB 6.4MB/s
  Installing build dependencies ... error
  Complete output from command c:\programdata\anaconda3\python.exe c:\programdata\anaconda3\lib\site-packages\pip install --ignore-installed --no-user --prefix C:\Users\USER\AppData\Local\Temp\pip-build-env-imeyh_am\overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools wheel:
  Traceback (most recent call last):
    File "c:\programdata\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
      "__main__", mod_spec)
    File "c:\programdata\anaconda3\lib\runpy.py", line 85, in _run_code
      exec(code, run_globals)
    File "c:\programdata\anaconda3\lib\site-packages\pip\__main__.py", line 16, in <module>
      from pip._internal import main as _main  # isort:skip # noqa
    File "c:\programdata\anaconda3\lib\site-packages\pip\_internal\__init__.py", line 4, in <module>
      import locale
    File "c:\programdata\anaconda3\lib\locale.py", line 16, in <module>
      import re
    File "c:\programdata\anaconda3\lib\re.py", line 142, in <module>
      class RegexFlag(enum.IntFlag):
  AttributeError: module 'enum' has no attribute 'IntFlag'
```

I'm running python anaconda 3.6

**Comment by doverradio** [comment]
HOLD UP

I solved it by removing enum:

`pip uninstall enum34`

Is this fine?  Will this cause issues using pyinstaller?

**Comment by DingGuodong** [comment]
I am also suffering this problem and have no luck.
**Why not author or dev team support a wheel package(.whl) for multiple system platform?**

**Comment by BoboTiG** [comment]
Closing the issue as this is not PyInstaller related, but pip+anaconda.

**Comment by 7qlice** [comment]
> HOLD UP
> 
> I solved it by removing enum:
> 
> `pip uninstall enum34`
> 
> Is this fine? Will this cause issues using pyinstaller?
you are right
