### ISSUE TITLE
Support statical linking of Python library

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#420]
**Original date**: 2011/09/22
**Original reporter**: *martindawids AND deltek DOT  COOM *

Add code to support linking the Python library statically. This is necessary if using a version of Python that does have a shared library.

**Comment by htgoebel** [comment]
This issue is six years old now, nobody worked on it and demand seems to be rare. So I'm closing this now. If somebody wants to implement this, feel free to provide a pull-request.

**Comment by htgoebel** [comment]
Idea for a solution:
- If the shared lib can not be found by analyzing the python executable, search the executable RPATH and RUN_PATH, LD_LIBARARY_PATH and some standard directories for the lib. (Equivalent mechanisms for win32 and osx are required, too.)
- Add an option to overwrite this path.
- Add a warning, if this option is used while the shared lib is be found by analyzing the python executable.
