### ISSUE TITLE
'google-cloud-firestore' distribution was not found and other google-cloud services

### ISSUE THREAD

**Issue by strangemind** [pyinstaller/pyinstaller#4209]
Hello PyInstaller
We are getting an error when packaging our app.
    exec(bytecode, module.__dict__)
  File "site-packages/google/cloud/firestore_v1/__init__.py", line 19, in <module>
  File "site-packages/pkg_resources/__init__.py", line 472, in get_distribution
  File "site-packages/pkg_resources/__init__.py", line 344, in get_provider
  File "site-packages/pkg_resources/__init__.py", line 892, in require
  File "site-packages/pkg_resources/__init__.py", line 778, in resolve
pkg_resources.DistributionNotFound: The 'google-cloud-firestore' distribution was not found and is required by the application
[13063] Failed to execute script app
The same error occurs with "google-cloud-core".   This the same error reported at
https://stackoverflow.com/questions/55848884/google-cloud-firestore-distribution-doesnt-get-added-to-pyinstaller-build
similar to 
from https://github.com/pyinstaller/pyinstaller/pull/3450/commits/b33e73941689c373a4807f6ecaf8d4154b43d6ab
https://github.com/MartinSahlen/cloud-functions-python/issues/56

It looks like many are having problems packaging google-cloud imports.  It may be to way google name 
there packages with "-".
If you follow the trace to line 778.   It appears that code attempting to read file "-" for google.py and google/cloud.py

We create the following hook file to attempt to capture the package:

#tsd 5-1-19
# from https://github.com/MartinSahlen/cloud-functions-python/issues/56
#-----------------------------------------------------------------------------
# Copyright (c) 2013-2018, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------

from PyInstaller.utils.hooks import copy_metadata, copytree, get_package_dir
datas += copy_metadata('google-cloud-firestore')
datas += copy_metadata('google_cloud_firestore')  #alt

hiddenimports += ['google-cloud-firestore_v1']
#pythonhosted.org/pyinstaller/hooks.html#understanding-pyinstaller-hooks
#get_package_dir returns tuple (where pkg stored, abs path to pkg)
pkg_dir = get_package_dir('google-cloud-firestore')

datas += (pkg_dir[1], 'google-cloud-firestore')

We first did the datas = copy_metadata('google-cloud-firestore') by itself.  After search google,
we saw others have tried different variation of the spelling for google-cloud-firestore such as
google_cloud_firestore, google-cloud_firestore or google.cloud.firestore

we are packaging on Rasberry Pie III with 
with 
2012 INFO: PyInstaller: 3.5.dev0+06f7da789
2015 INFO: Python: 3.7.0
2041 INFO: Platform: Linux-4.14.79-v7+-armv7l-with-debian-9.6

our spec file
-*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['app.py'],
             pathex=['/usr/local/opt/python-3.7.0/lib/python3.7/site-packages', '/home/pi/source/pal-base-3'],
             binaries=[],
             datas=[('config', 'config'), ('SQL', 'SQL'), ('main', 'main'), ('libs', 'libs'), ('license', 'license'), ('heartBeat', 'heartBeat'), ('localEvent', 'localEvent'), ('eventGarbage', 'eventGarbage'), ('persistEvent', 'persistEvent'), ('escalation', 'escalation'), ('eventMgr', 'eventMgr'), ('cron', 'cron'), ('scheduler', 'scheduler'), ('general', 'genereal'), ('internal', 'internal'), ('eventAdd', 'eventAdd'), ('eventRemove', 'eventRemove'), ('outComms', 'outComms'), ('notifierFPM', 'notifierFPM'), ('notifierV1', 'notifierV1'), ('notifierV2', 'notifierV2'), ('Email', 'Email'), ('firebase_msg', 'firebase_msg'), ('firestore', 'firestore'), ('pager', 'pager'), ('xmpp', 'xmpp'), ('report', 'report'), ('serialFP', 'SerialFP'), ('serialHWired', 'serialHWired'), ('serialOut', 'serialOut'), ('templateThread', 'templateThread'), ('templates', 'templates'), ('static', 'static')],
             hiddenimports=['google-cloud-core'],
             hookspath=['/home/pi/source/pal-base-3/hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='pal-service-5001',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='pal-service-5001')

we can find the distribution for google-cloud-firestore at 
usr/local/opt/python-3.7.0/lib/python3.7/site-packages/google_cloud_firestore-1.0.0.dist-info
it has following metadata file
Metadata-Version: 2.1
Name: google-cloud-firestore
Version: 1.0.0
Summary: Google Cloud Firestore API client library
Home-page: https://github.com/GoogleCloudPlatform/google-cloud-python
Author: Google LLC
Author-email: googleapis-packages@google.com
License: Apache 2.0
Platform: Posix; MacOS X; Windows
Classifier: Development Status :: 4 - Beta
Classifier: Intended Audience :: Developers
Classifier: License :: OSI Approved :: Apache Software License
Classifier: Programming Language :: Python
Classifier: Programming Language :: Python :: 2
Classifier: Programming Language :: Python :: 2.7
Classifier: Programming Language :: Python :: 3
Classifier: Programming Language :: Python :: 3.5
Classifier: Programming Language :: Python :: 3.6
Classifier: Programming Language :: Python :: 3.7
Classifier: Operating System :: OS Independent
Classifier: Topic :: Internet
Requires-Python: >=2.7,!=3.0.*,!=3.1.*,!=3.2.*,!=3.3.*
Requires-Dist: google-api-core[grpc] (<2.0.0dev,>=1.9.0)
Requires-Dist: google-cloud-core (<0.30dev,>=0.29.0)
Requires-Dist: pytz

Python Client for Google Cloud Firestore
========================================

|beta| |pypi| |versions|

The `Google Cloud Firestore`_ API is a flexible, scalable
database for mobile, web, and server development from Firebase and Google
Cloud Platform. Like Firebase Realtime Database, it keeps your data in
sync across client apps through realtime listeners and offers offline support
for mobile and web so you can build responsive apps that work regardless of
network latency or Internet connectivity. Cloud Firestore also offers seamless
integration with other Firebase and Google Cloud Platform products,
including Cloud Functions.

-  `Product Documentation`_
-  `Client Library Documentation`_

.. |beta| image:: https://img.shields.io/badge/support-beta-silver.svg
   :target: https://github.com/googleapis/google-cloud-python/blob/master/README.rst#beta-support
.. |pypi| image:: https://img.shields.io/pypi/v/google-cloud-firestore.svg
   :target: https://pypi.org/project/google-cloud-firestore/
.. |versions| image:: https://img.shields.io/pypi/pyversions/google-cloud-firestore.svg
.. _Google Cloud Firestore: https://cloud.google.com/firestore/
.. _Product Documentation: https://cloud.google.com/firestore/docs/
.. _Client Library Documentation: https://googleapis.github.io/google-cloud-python/latest/firestore/index.html

Quick Start
-----------

In order to use this library, you first need to go through the following steps:

1. `Select or create a Cloud Platform project.`_
2. `Enable billing for your project.`_
3. `Enable the Google Cloud Firestore API.`_
4. `Setup Authentication.`_

.. _Select or create a Cloud Platform project.: https://console.cloud.google.com/project
.. _Enable billing for your project.: https://cloud.google.com/billing/docs/how-to/modify-project#enable_billing_for_a_project
.. _Enable the Google Cloud Firestore API.:  https://cloud.google.com/firestore
.. _Setup Authentication.: https://googleapis.github.io/google-cloud-python/latest/core/auth.html

Installation
~~~~~~~~~~~~

Install this library in a `virtualenv`_ using pip. `virtualenv`_ is a tool to
create isolated Python environments. The basic problem it addresses is one of
dependencies and versions, and indirectly permissions.

With `virtualenv`_, it's possible to install this library without needing system
install permissions, and without clashing with the installed system
dependencies.

.. _`virtualenv`: https://virtualenv.pypa.io/en/latest/


Supported Python Versions
^^^^^^^^^^^^^^^^^^^^^^^^^
Python >= 3.5

Deprecated Python Versions
^^^^^^^^^^^^^^^^^^^^^^^^^^
Python == 2.7. Python 2.7 support will be removed on January 1, 2020.


Mac/Linux
^^^^^^^^^

.. code-block:: console

    pip install virtualenv
    virtualenv <your-env>
    source <your-env>/bin/activate
    <your-env>/bin/pip install google-cloud-firestore


Windows
^^^^^^^

.. code-block:: console

    pip install virtualenv
    virtualenv <your-env>
    <your-env>\Scripts\activate
    <your-env>\Scripts\pip.exe install google-cloud-firestore


Example Usage
~~~~~~~~~~~~~

.. code:: python

    from google.cloud import firestore

    # Add a new document
    db = firestore.Client()
    doc_ref = db.collection(u'users').document(u'alovelace')
    doc_ref.set({
        u'first': u'Ada',
        u'last': u'Lovelace',
        u'born': 1815
    })

    # Then query for documents
    users_ref = db.collection(u'users')
    docs = users_ref.get()

    for doc in docs:
        print(u'{} => {}'.format(doc.id, doc.to_dict()))

Next Steps
~~~~~~~~~~

-  Read the `Client Library Documentation`_ for Google Cloud Firestore API
   API to see other available methods on the client.
-  Read the `Product Documentation`_ to learn
   more about the product and see How-to Guides.


you can test with above example or

import firebase
from firebase_admin import messaging
from firebase_admin import credentials

cred = credentials.Certificate('pagerreplacement-firebase-adminsdk-ne76n-e2444cc09e.json')
default_app = firebase_admin.initialize_app(cred)

from google.cloud import firestore
DB = firestore.Client.from_service_account_json('pagerreplacement-firebase-adminsdk-ne76n-e2444cc09e.json')
USERS_COL = DB.collection('users')
FAC_COL = ""


Please inform me on what we need in our hook file.   Please look into deeper how package google-cloud
because I see many are experiencing similar issue with different parts of google-cloud.

Thank
tdavis@palcare.com


ps you can use the following for hook-firebase_admin.py
#tsd 4-3-19
# from https://github.com/pyinstaller/pyinstaller/pull/3450/commits/b33e73941689c373a4807f6ecaf8d4154b43d6ab
#-----------------------------------------------------------------------------
# Copyright (c) 2013-2018, PyInstaller Development Team.
#
# Distributed under the terms of the GNU General Public License with exception
# for distributing bootloader.
#
# The full license is in the file COPYING.txt, distributed with this software.
#-----------------------------------------------------------------------------

from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('google-api-core')

**Comment by strangemind** [comment]
Searching the issues logs,  I found related issues:
https://github.com/pyinstaller/pyinstaller/issues/4127
https://github.com/pyinstaller/pyinstaller/issues/4034
jmakitalo was able fix his/her issue by 

 # Fix case when fnm represents a namespace.
        if fnm in ('-', None):
            continue

on line 128 in file misc.py

**Comment by cbenhagen** [comment]
You can add a hook containing this:

```python
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('google-cloud-firestore')
```

Sorry haven't had the time to create a PR for this yet. Please do if you have.

**Comment by strangemind** [comment]
Did that already.  It still fails when attempting to read 4 bytes to determine if "-" needs to be compiled.  "-" is invalid filename.  When parsing "google-cloud-firestore", a "-" is determined as filename or die in misc.py

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by cbenhagen** [comment]
You could also check this PR: https://github.com/pyinstaller/pyinstaller/pull/4221

**Comment by strangemind** [comment]
We did those changes already.  Still get the same error.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by strangemind** [comment]
was able to fix this issue be creating 3 hook files
hook-firestore.py not hook-google-cloud-firestore.py
hook-firebase_admin.py
hook-grpc.py

hook-firestore.py 
# from https://github.com/MartinSahlen/cloud-functions-python/issues/56
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('google-cloud-core')
datas += copy_metadata('google-cloud-firestore')
datas += copy_metadata('google-api-core')

hook-firebase_admin.py
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('google-api-core')
datas += copy_metadata('firebase-admin')

hook-grpc.py
# from stackoverflow.com/questions/55848884/google-cloud-firestore-doesnt-get-added-to-pyinstaller-build
from PyInstaller.utils.hooks import copy_metadata, collect_data_files

datas = collect_data_files('grpc')
# needs all the recources not just the py files

can close this issue
will submit above hook file as Pull Request.

**Comment by Aquila-f** [comment]
hi @strangemind  First Congratulation you already solve the problem
I also got the same problem.
so created that three new .py file in venv\Lib\site-packages\PyInstaller\hooks ?
how about the content? 
should I put something in?

**Comment by strangemind** [comment]
Aquila-f,
Create the three hook files by retrieve from the pull request #4314 or from the commits above.
Create your own hook folder in your project    Use  
`--additional-hooks-dir "[our path]"`  option or in the spec file modify "
`hookspath=[]`" to your path to the hook file

**Comment by Aquila-f** [comment]
hi @strangemind thank u for answer that

so I go to the \venv\Lib\site-packages\PyInstaller\hooks
and created these three .py files and  the code

hook-firestore.py
    from PyInstaller.utils.hooks import copy_metadata
    datas = copy_metadata('google-cloud-core')
    datas += copy_metadata('google-cloud-firestore')
    datas += copy_metadata('google-api-core')

hook-firebase_admin.py
    from PyInstaller.utils.hooks import copy_metadata
    datas = copy_metadata('google-api-core')
    datas += copy_metadata('firebase-admin')

hook-grpc.py
    from PyInstaller.utils.hooks import copy_metadata, collect_data_files
    datas = collect_data_files('grpc')

and I run the pyinstaller -F XXX.py
Unfortunately that's not work 
or I got some misunderstand? QQ
 
it also print this--
pkg_resources.DistributionNotFound: The 'google-cloud-firestore' distribution was not found and is required by the application

**Comment by strangemind** [comment]
In https://github.com/pyinstaller/pyinstaller/pull/4314,  the hook files that you will need to use are located there.   They are similar to what you wrote.  You will want to place the files in the mentioned path “\venv\Lib\site-packages\PyInstaller\hooks” or your reference in –additional-hook-dir option.

You may need to have the bugfix found in https://github.com/pyinstaller/pyinstaller/pull/4221/files added to a fork till PyInstaler adds the needed IO traps.

I found following reference useful, https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html.
