### ISSUE TITLE
module 'win32ctypes.pywin32.win32api' has no attribute 'error'

### ISSUE THREAD

**Issue by niuzhenjiang** [pyinstaller/pyinstaller#4217]
![捕获](https://user-images.githubusercontent.com/42111602/57266266-d3686c80-70ad-11e9-9548-3ac290a24800.PNG)
请告诉我该如何解决，谢谢！

**Comment by davidanger** [comment]
我也有这问题 你怎么解决的？！~ @niuzhenjiang

**Comment by davidanger** [comment]
解决了--icon= 参数的图标文件名没写对。。。
