### ISSUE TITLE
bootloader/waf: special data in the executable 

### ISSUE THREAD

**Issue by blshkv** [pyinstaller/pyinstaller#4220]
It was highlighted by @linxon in our tracker (https://github.com/pentoo/pentoo-overlay/issues/459) that something weird is going on at the end of waf file:
https://github.com/pyinstaller/pyinstaller/blob/ad3d2d46804d2d955c17eae740b8c2eac529611e/bootloader/waf#L168
The data is encoded in the binary and getting extracted during runtime. This is a typical behaviour of malware.

Out of curiosity, I have unpacked that t.bz2 and found out that this is just a copy waf (https://gitlab.com/ita1024/waf/tree/master/waflib).

There is also a script ```update-waf.sh``` which supposed to be able to update waf but it points to a old location (github).

I suggest redesigning that. The archived copy of waf should be distributed as a separate file, installed together with waf into a shared directory and extracted as necessary. In this way, it would be easier to update it as well.

**Comment by htgoebel** [comment]
> It was highlighted by @linxon in our tracker (pentoo/pentoo-overlay#459) that something weird is going on at the end of waf file:

This is how waf work. If you want to redisign this, please provide a pull-request.

**Comment by blshkv** [comment]
I would suggest keeping this bug open until it is fixed. I also disagree with "this is how waf work". 
Also, remove the label "wont fix".

**Comment by htgoebel** [comment]
I do not consider this a bug.

waf is a self-contained script which extracts itself when run. This is the intended behavior, works as designed and thus no a bug.

It this behaviour bugs you ;-) please provide a pull-reqeest. I will not spend another minute on this.
