### ISSUE TITLE
PyInstaller generated executable crashes with GStreamer on Windows 10

### ISSUE THREAD

**Issue by desolaser** [pyinstaller/pyinstaller#4222]
I'm trying to package a program that uses GStreamer in an .exe file, i have not problems with the build process, but when the .exe runs it crashes at startup with no error message. I'm sure the problem is not the `import gi` line at the beginning of the code, because the program crashes after that. (i tested using prints to see when the app crashes).

I tried to do the same on msys2 environment and it works perfectly, but i want to do the same on windows 10.

### Specifications:
Windows 10
Pyinstaller 3.5.dev0+170550e0c
Python 2.7.16
PyGObject for windows: pygi-aio-3.24.1_rev1

### Code:
```
import gi
import time
gi.require_version('Gst', '1.0')
from gi.repository import GLib, Gst

Gst.init(None)
pipeline = Gst.Pipeline()
test = Gst.ElementFactory.make("videotestsrc") # HERE THE APP CRASHES
videosink = Gst.ElementFactory.make("autovideosink")
pipeline.add(test)
pipeline.add(videosink)
test.link(videosink)
pipeline.set_state (Gst.State.PLAYING)
loop = GLib.MainLoop()
print (loop)
try:
	loop.run()
except KeyboardInterrupt:
	traceback.print_exc()
finally:
	pipeline.set_state (Gst.State.NULL)
```
As you can see, the app crashes at line 8.
I tried using try except statements to handle the error, but even with that the app crashes.

### Console output:

This is the output of `pyinstaller -y --clean --log-level DEBUG test.spec`:
[debug.txt](https://gist.github.com/desolaser/bb3e73a09e2027049295c50884b217b1)

This is the output of the .exe file and using `debug=True` on .spec file:
[debug-exe.txt](https://gist.github.com/desolaser/091220fd07b9703a532194204de1fe31)

**Comment by htgoebel** [comment]
Without any error message, nobody will be able to help you.Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.
