### ISSUE TITLE
fail to convert with Crypto.Cipher

### ISSUE THREAD

**Issue by joker8989** [pyinstaller/pyinstaller#4225]
i made a little script with python 2.7 that includes Crypto.Cipher AES-256 bit encryption

The encrypted file workes well in idle/pycharm but when i try to convert it to exe with pyinstaller i get an error relates to ntpath.py

Object type NoneType has no len()..

And it refused to create the file, i tried many version of pyinstaller...

pyinstaller works i tried to convert something that does not have crypto inside and it worked i think its about the cryptography that refused to make it executable

Any help?

again the file workes in IDLE/pycharm as usual only when i try to make it executable it fails

**Comment by htgoebel** [comment]
I assume you tra to write to some path you are not permitted to write.
