### ISSUE TITLE
setting runtime environment variables in pyinstaller-created exe 

### ISSUE THREAD

**Issue by bonnyjainkinta** [pyinstaller/pyinstaller#4227]
Hi,

I want my pyinstaller-created exe to use a hash seed of 0, and I have tried setting the PYTHONHASHSEED environment variable before calling the .exe, but it does not seem to be getting passed through. Is there a way to set environment variables for runtime pyinstaller-created exe's, or a way to call it to turn hash seed randomization off?

Thanks,
Frustrated pyinstaller user

**Comment by htgoebel** [comment]
Please read the manual for which options are supported https://pythonhosted.org/PyInstaller/spec-files.html#giving-run-time-python-options If you need more, please submit a pull-request.
