### ISSUE TITLE
Moving hooks to the packages they support

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#4232]
This is a follow-up on #2692 by providing a concrete proposal which would enable the authors of a package to include PyInstaller hooks for their package and run tests to ensure the hooks include all the files necessary in the frozen result. Specifically, I propose:

# Changes for package authors

1. Modify `setup.py` to specify the following entry points:

``` Python
setup(
    # All of the following entry points are optional.
    entry_points={
        'PyInstaller.hooks': [
            # The ``some_module.some_func`` entry point refers to a function 
            # that will be invoked with no parameters. It must return a sequence 
            # of strings, each element of which provides an additional absolute 
            # path to search for hooks. This is equivalent to passing the 
            # ``additional-hooks-dir`` command-line option to PyInstaller for 
            # each string in the sequence.
            'unique_name1 = some_module:some_func',

            # An arbitrary number of additional entries, each with a unique name 
            # and following the same format, may follow. The name need only be
            # unique to this distribtuions's entry point.
        ],

        'PyInstaller.tests' : [
            # The ``a_module:a_func`` entry point must return a sequence of 
            # strings, each of which is an absolute path to a directory tree to 
            # pass to pytest for test discovery or an absolute path to a Python
            # source file to pass to pytest for test discovery.
            'unique_name1 = a_module:a_func'

            # An arbitrary number of additional entries, each with a unique name 
            # and following the same format, may follow. The name need only be
            # unique to this distribtuions's entry point.
        ]
    }
)
```

2. Modify their tests to:
    1. Invoke `subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-U', 'PyInstaller[test]')` to install the latest version of PyInstaller and its optional test requirements. Use `subprocess.check_call([sys.executable, '-m', 'pip', 'install', '-e', 'git+https://github.com/pyinstaller/pyinstaller.git#master[test]')` to install and test the latest development version.
    2. Run `pytest` using the standard PyInstaller test fixtures:

``` Python
import pytest
pytest.main(<tests -- typically, a_module.a_func() will return the correct list>)
```

# PyInstaller changes

To support these changes, PyInstaller would:

1. Update its `setup.py`:

``` Python
setup(
    extras_require={'test': [
        # Everything currently in requirements-tools.txt.
    ]}
    # Provide ``conftest.py`` as a Pytest plugin. See
    # https://docs.pytest.org/en/latest/writing_plugins.html#setuptools-entry-points.
    entry_points={
        "pytest11": "PyInstaller-fixtures = PyInstaller.utils.conftest [test]"
    },
)
```

2. Move `tests/functional/conftest.py` to `PyInstaller/utils`.
3. Include additional hook directories from entry points by modifing `PyInstaller.building.build_main.Analysis.__init__`:

``` Python
        self.hookspath = hookspath
        for entry_point in pkg_resources.iter_entry_points('PyInstaller.hooks', 'hooks'):
            hookspath += list(entry_point.load()())
```

4. Use the additional hooks path to load rthooks as well as hooks. **This changes the meaning** of the `--additional-hooks-dir` command-line argument. However, since few people will happen to have a file named `rthooks.dat` in a hook directory, I expect little impact. To do so, modify `PyInstaller.depend.analysis.PyiModuleGraph.__init__`:

``` Python
        self._available_rthooks = defaultdict(list)
        for uhd in self._user_hook_dirs:
            uhd_path = os.path.join(uhd, 'rthooks.dat')
            try:
                with compat.open_file(uhd_path, compat.text_read_mode, 
                                      encoding='utf-8') as f:
                    available_rthooks = ast.literal_eval(f.read())
            except FileNotFoundError:
                # Ignore if this hook path doesn't have run-time hooks.
                continue
            except Exception as e:
                logger.error('Unable to read run-time hooks from %s: %s' % 
                             (uhd_path, str(e)))
                continue

            # TODO: Use ``available_rthooks.items()`` after Python 2 is retired.
            for key in list(available_rthooks):
                # Ensure the key is a string.
                assert (isinstance(key, compat.text_type), 
                        '%s must be a dict of keys; the key "%s" '
                        'must be a string.' % (uhd_path, key)
                # Ensure the value is a list.
                value = available_rthooks[key]
                assert (isinstance(value, list), 'The value of %s key "%s" must '
                        'be a list.' % (uhd_file, key))
                # Merge this with existing run-time hooks.
                for _ in value:
                    # Ensure each item in the list is a string.
                    assert (isinstance(_, compat.text_type), '%s key "%s", '
                            'item "%s" must be a string.' % (uhd_path, key, _))
                    self._available_rthooks[key].append(_)
```

5. Move all hooks and non-core tests to a separate package/repo, and run tests there, by discovering PyInstaller tests for all installed distributions. Set up a hook to trigger a CI build of this repo when PRs are submitted to the main pyinstaller repo.

@htgoebel, @codewarrior0, @matysek, @rasky, any thoughts?

**Comment by htgoebel** [comment]
@bjones1 Thanks for stepping forward by providing a concrete solution.

1. I like the idea of providing PyInstaller fixtures as pytest-plugin. This change could be applied quickly.
2. It's not clear for me, what the `PyInstaller.tests` entry-point is used for. I understand we could use it to make PyInstaller's test-suite find other hooks. But is this really useful? I'd expect that packaged providing hooks run the pyinstaller-test suite in an appropriate way.
3. I suggest writing step 2 in a more "CI" like way, using shell commands. This would be easier to understand IMHO.

Regarding the `PyInstaller.hooks` entry-point: I thought about different methods to collect name-space packages would be a simpler solution for package developers. Let's discuss this in #4301.

**Comment by bjones1** [comment]
1. Great!
2. When packages define `PyInstaller.tests`, then PyInstaller can run tests on them. For example, if the numpy team implements this, then they will be providing both a hook for numpy (if necessary) and tests to ensure that numpy is frozen properly. We then discover these tests in CI and run them, ensuring any changes to the PyInstaller code base don't break existing hooks.
3. Good point. The sequence would be:

    - `python -m pip install -U PyInstaller[test]` (to set up for testing with the currently-released version of PyInstaller)
    - `pytest` (in the appropriate directory or with command-line parameters to select packaging tests using PyInstaller).

I'll make comments in #4301 as well.

**Comment by htgoebel** [comment]
Please go ahead and provide a pull-request.

Some remarks already:
- I suggest the entry-point group to be named "pyinstaller34" (like "pytest11") and use the names "hooks-dirs" and "tests".
  - According to https://packaging.python.org/specifications/entry-points/#data-model, the "group should use names starting with a PyPI name owned by the consumer project".
  - We (currently) only have these two entry-points, thus there is no need to name the groups e.g. "pytinstaller34.hooks-dirs" (and using some non-obvious "unique" identifier).
  - I'm not sure about "tests" for this - see below. So maybe for tests we actually need "pyinstaller34.tests".
- "pyinstaller34" > "tests" could be a function returning a list of tests to be run. Depending on how tests could be feed to pyinstaller most easily, this could be a list of file/directory-names to be search or a list of functions to be called. I assume file/directory-names to be easier for both PyInstaller and package authors.
- Of course we need tests for this as part of the test-suite. The tricky part would be that one test needs to run the test-suite checking that a test is actually picked up.
- We should also provide a sample project showing how to use this mechanism (in both directions). I already prepared some example for my #4301 tests and am happy to publish this.
- Of course we need documentation, too :-)

**Comment by bjones1** [comment]
If we select a group of `pyinstaller34` and a name of `tests`, there's one case I can think of that's not covered: a distribution that consists of more than one package, each of which contains tests for PyInstaller. My thoughts on this:

Using group `pyinstaller34`, name `tests`:
- Pro: Simple, easy to document, covers most cases.
- Con: Doesn't provide a nice way to specify more than one function. This could be an obstacle for multipackage distributions, in which each package has its own function to returns a list of tests,

Using group `pyinstaller34.tests`, name of anything:
- Pro: sill simple, covers all cases.
- Con: A bit more difficult to document, since the name being unspecified seems a bit odd.

How important is covering the (probably unusual) corner case?

**Comment by htgoebel** [comment]
My thoughts:

* When installing the distribution (no matter if normal or development `-e …`) all included packages get installed.
* When calling the entry-point, the package needs to be imported - which might not be desired. But when calling an entry-point for each package, each package needs to be imported - which is no improvement.
* The code would be cleaner when having one entry-point for each package.
* Multi-package distributions seem to be rare: The only multipackage distribution I know is [setuptools](https://github.com/pypa/setuptools).

Overall IMO it is not important to cover this corner case.

BTW: The `34` will of course be replaced be the PyInstaller version we introduce this feature in. I expect this to become `40`.

**Comment by htgoebel** [comment]
@bjones1 Any progress on this? Did I miss something?

**Comment by bjones1** [comment]
Unfortunately, no. I'm unlikely to make progress on this until the semester is over (mid-December). Too many other projects...

**Comment by bjones1** [comment]
I'm finally working on this.

**Comment by bjones1** [comment]
I've submitted a PR for this as #4582. I'm closing this issue, so we can continue the discussion there.

**Comment by htgoebel** [comment]
Thanks for the pull-request. Reopening this one, since it is not yet implemented :-)
