### ISSUE TITLE
modulenotfounderror no module named 'win32com.gen_py' 

### ISSUE THREAD

**Issue by cristianmarian95** [pyinstaller/pyinstaller#4233]
After i build the exe file, on run the exe file i get : 
![Capture](https://user-images.githubusercontent.com/11537683/57848607-f8618b80-77e1-11e9-9f00-55f9ef207ba7.PNG)

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

When posting a issue, please post text, Image war hard to read and can not be searched.
