### ISSUE TITLE
ModuleNotFoundError: No module named 'wsgiref'

### ISSUE THREAD

**Issue by rmohamedfazil** [pyinstaller/pyinstaller#4236]
I got an error like how to resolve it? anyone help me out this asap?

File "C:\Users\Gayathri\dist\Testing\django\core\management\commands\runserver.py", line 10, in <module>
    from django.core.servers.basehttp import (
  File "C:\Users\Gayathri\dist\Testing\django\core\servers\basehttp.py", line 14, in <module>
    from wsgiref import simple_server
ModuleNotFoundError: No module named 'wsgiref'
[14744] Failed to execute script manage

**Comment by cbenhagen** [comment]
* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If your problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for GitHub's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.

**Comment by Smallfi** [comment]
i want to know if i have installer the develop
but how to use the develop? 
who can tell me?

**Comment by htgoebel** [comment]
See [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).
