### ISSUE TITLE
how get noconsole output

### ISSUE THREAD

**Issue by lisabrauns** [pyinstaller/pyinstaller#4248]
I used the noconsole parameter, how to get the contents of the console output?

**Comment by cowo78** [comment]
Depends also on the OS. If you're on windows and used the windowed mode then there's no console attached to the process. Either you use the console mode or change your code (i.e. a logger).

**Comment by Sup3rGeo** [comment]
@cowo78 could you explain with more details how it would work using a logger?

I have a GUI program that we also want to use as a command line tool. When you just double click the executable, we would like the UI to show without any console window.

But when you open a cmd and type "myprogram --help" we would like to be able to see the contents and etc..

**Comment by htgoebel** [comment]
PyInstaller does not support this. AFAIK this is not possible on Windows neither on OS X. If you know a low-level solution for this, feel free to provide a pull-request.

**Comment by cowo78** [comment]
@Sup3rGeo I don't quite understand what you mean. If you have a GUI program (and it's a specific flag in the binary, not something that can be changed at runtime) on win32 then it does NOT have a console on startup. You can of course handle the command line and allocate a new console to display help but this has nothing to do with pyinstaller.
