### ISSUE TITLE
My program won't run properly

### ISSUE THREAD

**Issue by aoviedo77** [pyinstaller/pyinstaller#4249]
What is the exact problem?
I executed the following command:
pyinstaller --onefile --paths=./Back --paths=./Cartas --paths=./Front app.py
And the exe file was generated properly. However, If I execute it in the folder dist, we get an exception that app.py (original file) can't find one of the modules in the project that I created myself and is imported and needed in app.py
If I move app.exe to the same folder as app.py, we start the program but we display the initial window of the program all in black and after some seconds the execution finishes but no error is displayed.
I tried to do:

Software versions you are using:
python 3.7.1
pyinstaller 3.5.dev0+d74052489
Windows 10
matplotlib 3.0.3
pandas 0.24.2

What platform and which version you are working on (Windows, Linux, OS X).
Windows 10 in Spanish (Spain)

A minimal example program which shows the error. Ideally this is a one-liner :-)
As this seems to be a problem with other modules created by me I can't put all the code here. However, I tried to do:
sxstrace trace -logfile:trace.log
And got this error:
Error de StartTrace. Mensaje de error:
Acceso denegado.

I don't know what to do as everything should work fine...

**Comment by hong6914** [comment]
Open a DOS prompt and run the generated exe, and run the command "echo %errorlevel%" right after the program finishes --- what's the value you get?

**Comment by hong6914** [comment]
More: once you get that value --- typically a negative one, type it in the calculator, and google the displayed hex value, the actual error code, for the possible cause.

**Comment by htgoebel** [comment]
> can't find one of the modules in the project that I created myself and is imported and needed in app.py

Obviously the modules have not been found then freezing app.py. Check `xref-*.html` in the build directory..

So solve this I suggest you install all dependencies and PyInstaller into a virtual environment and use this for running PyInstaller.
