### ISSUE TITLE
Make IBM MQ work with PyInstaller

### ISSUE THREAD

**Issue by Smallfi** [pyinstaller/pyinstaller#4252]
very sorry to tell you  when i run the code in eclipse,it work well.
but when i make it to a  exe run on windows it cannot work well.
it says cannot connect to IBM MQ  
I use the library pymqi 1.9.2
i meet the problem look like this

![image](https://user-images.githubusercontent.com/7116142/58606092-b863d380-82cc-11e9-867a-9c0f07e8e712.png)
I think the reason maybe when i make to exe , it occur some problem,
can you help me about this issue
I want to build an exe for others to use 
so I need to reslove this problem

**Comment by Smallfi** [comment]
I think pyinstaller really a great project in the world . 
So I hope you to make the project  better.

**Comment by Smallfi** [comment]
can anyone can help me about this thing?

**Comment by htgoebel** [comment]
IBM MQ is typically used in bigger companies, thus I assume you are are working for a company. [Please fund some days of development](http://www.pyinstaller.org/funding.html) thus I can effort spending more time on PyInstaller and might try to fix this. Thanks.

**Comment by Legorooj** [comment]
Please provide a pull request if you'd like support added.
