### ISSUE TITLE
'Could not find QtWebEngineProcess' with PyQt5 5.12 on MacOS X

### ISSUE THREAD

**Issue by astrofrog** [pyinstaller/pyinstaller#4260]
*Note: I'm running into an issue that looks like it's been reported before (e.g. https://github.com/pyinstaller/pyinstaller/issues/2276 and https://github.com/pyinstaller/pyinstaller/issues/3890) but the discussion in those threads indicate that the issues were fixed. The issue I'm running into is with the latest developer version of pyinstaller, with the latest version of PyQt5, so as a result I'm opening this issue*

I'm trying to build an app with:

```python
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
from PyQt5 import QtCore

app = QApplication([''])
web = QWebEngineView()
page = QWebEnginePage()
page.setView(web)
web.setPage(page)
web.setUrl(QtCore.QUrl('http://www.google.com/'))
web.show()
```

I installed PyQt5 with:

```
pip install PyQt5 PyQtWebEngine
```

and ``pip freeze`` shows:

```
altgraph==0.16.1
macholib==1.11
PyInstaller==3.5.dev0+gd7405248
PyQt5==5.12.2
PyQt5-sip==4.19.17
PyQtWebEngine==5.12.1
```

I built the script above with PyInstaller using:

```
pyinstaller --onedir qtonly.py
```

Once the build is completed, I run ``dist/qtonly/qtonly``, which gives:

```
Could not find QtWebEngineProcess
Abort trap: 6
```

To make sure I'm using a clean environment, I set this up on Azure Pipelines:

https://dev.azure.com/thomasrobitaille/voila-qt-app/_build/results?buildId=320

As you can see from this specific build, the error happens on MacOS X but not Windows or Linux (which both work fine). So this is a MacOS X-specific issue.

If you are interested in the repo with the Azure configuration, you can find it [here](https://github.com/astrofrog/voila-qt-app).

Also wanted to say thanks for working on such a great tool! :)

**Comment by bjones1** [comment]
On a Mac, the QtWebEngine requires building with `--windowed`.

**Comment by astrofrog** [comment]
Ah yes that fixes it, thanks!

**Comment by JohnABC** [comment]
> Ah yes that fixes it, thanks!

How did you fix it?

**Comment by astrofrog** [comment]
@JohnABC - I included the ``windowed`` flag when running pyinstaller

**Comment by stanislav-tikhomirov** [comment]
Encountered the similar problem, so tried to reproduce your case
Trying to build the same (main.py):
```python
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
from PyQt5 import QtCore

app = QApplication([''])
web = QWebEngineView()
page = QWebEnginePage()
page.setView(web)
web.setPage(page)
web.setUrl(QtCore.QUrl('http://www.google.com/'))
web.show()
```
Packages:
```
altgraph==0.17
macholib==1.14
PyInstaller==3.6
PyQt5==5.15.0
PyQt5-sip==12.8.0
PyQtWebEngine==5.15.0
```
First try - building with the following: `pyinstaller --onedir --windowed main.py` gives the same error `Could not find QtWebEngineProcess`

Second try - building with the following: `pyinstaller --windowed main.spec`, main.spec:
```
block_cipher = None

a = Analysis(['main.py'],
             pathex=['/Users/stanislav.tikhomirov/Desktop/Temp'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='main')
app = BUNDLE(coll,
             name='main.app',
             icon=None,
             bundle_identifier='org.qt-project.Qt.QtWebEngineCore',
             info_plist={
                'NSPrincipalClass': 'NSApplication',
                'NSHighResolutionCapable': 'True'
                }
             )
```
Result - the same error `Could not find QtWebEngineProcess`

**Comment by stanislav-tikhomirov** [comment]
So, after some investigation I think I've found an issue:
`pyi_rth_pyqt5webengine.py` is setting `os.environ['QTWEBENGINEPROCESS_PATH']` in the following way:
```python
os.environ['QTWEBENGINEPROCESS_PATH'] = os.path.normpath(os.path.join(
        sys._MEIPASS, '..', 'MacOS', 'PyQt5', 'Qt', 'lib',
        'QtWebEngineCore.framework', 'Helpers', 'QtWebEngineProcess.app',
        'Contents', 'MacOS', 'QtWebEngineProcess'
    ))
```
However it seems a wrong path, as QtWebEngineProcess is located at `sys._MEIPASS/PyQt5/Qt/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess`

With Pyinstaller 4.0.dev0 the workaround is just to change path somewhere (e.g. main.py)
```python
import os
import sys
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage
from PyQt5 import QtCore

if hasattr(sys, '_MEIPASS'):
    os.environ['QTWEBENGINEPROCESS_PATH'] = os.path.normpath(os.path.join(
                sys._MEIPASS, 'PyQt5', 'Qt', 'lib',
                'QtWebEngineCore.framework', 'Helpers', 'QtWebEngineProcess.app',
                'Contents', 'MacOS', 'QtWebEngineProcess'
            ))
app = QApplication([''])
web = QWebEngineView()
page = QWebEnginePage()
page.setView(web)
web.setPage(page)
web.setUrl(QtCore.QUrl('http://www.google.com/'))
web.show()
sys.exit(app.exec_())
```
And build with `pyinstaller --onedir --windowed main.py`

Packages:
```
altgraph==0.17
macholib==1.14
pyinstaller @ https://github.com/pyinstaller/pyinstaller/tarball/develop
PyQt5==5.15.0
PyQt5-sip==12.8.0
PyQtWebEngine==5.15.0
```
However at startup there are still some errors with finding resources:
```
Qt WebEngine resources / locales not found at /Users/stanislav.tikhomirov/Desktop/Temp/dist/main//Users/stanislav.tikhomirov/Desktop/Temp/dist/main. Trying parent directory...
Qt WebEngine resources not found at /Users/stanislav.tikhomirov/Desktop/Temp/dist/main/PyQt5/Qt. Trying application directory...
Installed Qt WebEngine locales directory not found at location /Users/stanislav.tikhomirov/Desktop/Temp/dist/main//Users/stanislav.tikhomirov/Desktop/Temp/dist/main/qtwebengine_locales. Trying application directory...
```
But it finds them in application directory (so everything works). It looks like that path strings are duplicated:
```
/Users/stanislav.tikhomirov/Desktop/Temp/dist/main//Users/stanislav.tikhomirov/Desktop/Temp/dist/main - duplicated
/Users/stanislav.tikhomirov/Desktop/Temp/dist/main/ - correct application directory, where all resources are
```

**Comment by bjones1** [comment]
Does this work on PyQt5 5.14.1 or earlier? Our CI passes on OS X, but for this version of PyQt5. The newer version may have a different layout.

See https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_pyqt5webengine.py for what needs updating if so. We may also need fixes at https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py#L26.

**Comment by stanislav-tikhomirov** [comment]
@bjones1 yes - tried PyQt5 5.14.1 and PyQtWebEngine 5.14.0 - with path changed everything works (with the same console output about missing resourses / locales), without path changed - error `Could not find QtWebEngineProcess`

**Comment by bjones1** [comment]
Strange -- OS X with the current code [passes on Travis](https://travis-ci.org/github/pyinstaller/pyinstaller/jobs/702828685). Did you install using pip?

**Comment by stanislav-tikhomirov** [comment]
Yes (https://pypi.python.org/simple repository)
