### ISSUE TITLE
jinja2.exceptions.TemplateNotFound: form.html

### ISSUE THREAD

**Issue by bbartling** [pyinstaller/pyinstaller#4264]
Hello,

Is it possible to use pyinstaller to create .exe from a Flask app that uses a templates and static directory?

Any tips help here and thank you if you have the time to respond. When I run the cmd `pyinstaller -F --add-data "templates;templates" --add-data "static;static" app.py`

It appears to compile the app.exe correctly, and when I run it & try to bring up my webpage running Flask on local host 127.0.0.1 I get an error `jinja2.exceptions.TemplateNotFound: form.html`. The Flask server starts just fine it appears to be able not find the templates folder...

Could I be doing something incorrect for not specifying my template & static folders?

Thank you.
Ben

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs).

**Comment by htgoebel** [comment]
Not more information since 2 month. Closing.
