### ISSUE TITLE
Python COM server

### ISSUE THREAD

**Issue by qbarinsights** [pyinstaller/pyinstaller#4266]
I have reading articles that PyInstaller cannot be used to build Python COM servers.
Is it true?
If it is true then do you have any suggestions for me?

**Comment by htgoebel** [comment]
I'm not a windows programmer and have no clue about COM. (AFAIK this is outdated technology, though). AFAIR there has been a bootloader for COM-programs some years ago, but nobody cared about it. If you really need it, you should be able to find it in the code history. Search doc/ChangeLog* first to learn when it has been dropped. Good luck

**Comment by qbarinsights** [comment]
I have a situation where vbscript needs to call python functions.
Can you plesse suggest any other way than COM to achieve it?
