### ISSUE TITLE
Pyinstaller and PyQt5 macOS Mojave compatibility issue

### ISSUE THREAD

**Issue by testronic** [pyinstaller/pyinstaller#4272]
My application, created with Pyinstaller, worked fine until I upgraded from High Sierra to Mojave. In order to demonstrate the issue I create a simple application. Main window has only one button. When you press the button its text should be changed to "Button is clicked...". When I run this program as .py script, everything works fine, but after creating .app file with Pyinstaller it behaves differently. The text is not updating until you click anywhere outside of the window. I could see this behavior only on macOS Mojave. 
Any suggestions?... 

```
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(303, 304)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(80, 170, 150, 32))
        self.pushButton.setObjectName("pushButton")
        self.pushButton.setDefault(True)
        
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)

        self.pushButton.clicked.connect(self.click)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("MainWindow", "Click me"))


    def click(self):
        self.pushButton.setEnabled(False)
        self.pushButton.setText("Button is clicked...")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

```

![Screen Shot 2019-06-13 at 3 28 15 PM](https://user-images.githubusercontent.com/34661453/59471509-21c90380-8df0-11e9-88b5-4654faa5974d.png)
![Screen Shot 2019-06-13 at 3 28 40 PM](https://user-images.githubusercontent.com/34661453/59471548-360d0080-8df0-11e9-9180-9e9459b6da10.png)

**Comment by testronic** [comment]
I found the solution for this problem. In order to solve this rendering issue you need to add the following line for a ui element, which needs to be updated. In my case it is required only if I need to run this application on macOS Mojave.

`<element>.repaint()`

For example:


```
def click(self):             
        self.pushButton.setEnabled(False)
        self.pushButton.setText("Button is clicked...")
        self.pushButton.repaint()
```

**Comment by crwood** [comment]
Related/duplicate: #4308

**Comment by BoboTiG** [comment]
Closing as duplicate.
