### ISSUE TITLE
PyInstaller created exe is not working with fiona, geopandas

### ISSUE THREAD

**Issue by supadhayay-rms** [pyinstaller/pyinstaller#4277]
I am using simple code to create exe using pyinstaller using geopandas and fiona as imports.
Sample code:

import glob
import geopandas as gpd
from pyproj import _datadir, datadir
import fiona
from osgeo import gdal, ogr, osr
from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
from geopandas import GeoDataFrame
print("Hello")

This allowed me to create exe somehow using following .spec file content:

# -*- mode: python -*-

block_cipher = None

import os
from PyInstaller.utils.hooks import collect_data_files # this is very helpful
from osgeo import gdal, ogr, osr
from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
from geopandas import GeoDataFrame
rTreeDlls = 'C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\rtree'

paths = [
    'C:\\Users\\supadhayay',
    rTreeDlls,
	'C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\DLLs',
	'C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\osgeo'
]

_osgeo_pyds = collect_data_files('osgeo', include_py_files=True)
_osgeo_pyds  = _osgeo_pyds  + collect_data_files('fiona', include_py_files=True)

osgeo_pyds = []
for p, lib in _osgeo_pyds:
    if '.pyd' in p or '.pyx' in p or '.pyc' in p:
        osgeo_pyds.append((p, '.'))
		
print(osgeo_pyds)

# these binary paths might be different on your installation. 
# modify as needed. 
# caveat emptor
binaries = osgeo_pyds +[
    (os.path.join(rTreeDlls,'spatialindex-64.dll'), '.'),
    (os.path.join(rTreeDlls,'spatialindex_c.dll'),'.'),
]

hidden_imports = [
    'fiona',
    'gdal',
    'shapely',
    'shapely.geometry',
    'pyproj',
    'rtree',
    'geopandas.datasets',
    'pytest',
    'pandas._libs.tslibs.timedeltas',
]

a = Analysis(['D:\\SDR\\Repo\\Main\\DBEngg\\Spatial Data Repository\\States_Data_Processing_With_Geometry\\States_Data_Processing_With_Geometry_MP.py'],
             pathex=paths,
             binaries=osgeo_pyds +[('C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\shapely\\DLLs\\geos_c.dll', '.'),('C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\rtree\\spatialindex_c.dll', '.'), ('C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\rtree\\spatialindex-64.dll', '.')],
             datas=collect_data_files('geopandas', subdir='datasets') + [('D:\\SDR\\Repo\\Main\\DBEngg\\Spatial Data Repository\\States_Data_Processing_With_Geometry\\lg-logo-rms.png','.'),('D:\\SDR\\Repo\\Main\\DBEngg\\Spatial Data Repository\\States_Data_Processing_With_Geometry\\SQL_States_Data_Processing.sql','.')],
             hiddenimports=hidden_imports,
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='States_Data_Processing_With_Geometry_MP',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )

After exe is getting created, I am not able to execute exe as it gives following error:

  File "fiona\ogrext.pyx", line 1, in init fiona.ogrext
ModuleNotFoundError: No module named 'fiona._shim'

I installed fiona using https://www.lfd.uci.edu/~gohlke/pythonlibs   version: Fiona‑1.8.6‑cp37‑cp37m‑win_amd64.whl

**Comment by ToddEmonster** [comment]
Hi,
Try adding this line to your sample code : 

`from fiona import _shim, schema`

On my config it works.

I followed this logic : 
`import pyproj` raises an import error stating that `pyproj._datadir` could not be found, so we explicitly import `pyproj._datadir` (and `pyproj.datadir`) and it works. => I did that because of [this answer](https://stackoverflow.com/a/55839597/11724795)
So if `import fiona` raises an import error about not finding `fiona._shim`, we might explicitly import it as well.
And then it raises a `fiona.schema` import error, that's why I imported both __shim_ and _schema_.


It's a dirty and quick solution, and unfortunately I have NO IDEA how it works - I'm a newbie programmer, and I'm also struggling with geopandas + pyinstaller right now, so I'm crisscrossing every issue record that look like mine and I've come with this solution for _this_ part of the problem. 
_After_ I 'solved' this error this way, on more elaborate programs I then get a Stop Iteration error...

At least it does not hurt to try, maybe it'll work for you.

**Comment by htgoebel** [comment]
Obviously this is a Cython module. Python can not determine if the Cython C object module is importing some Python module. Please [read the manual](https://pyinstaller.readthedocs.io/en/stable/feature-notes.html#cython-support) for details and a solution.

@ToddEmonster Since you fould the solution already, we would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks .

**Comment by ToddEmonster** [comment]
@htgoebel  Ok, I can't do this today but it will be done tomorrow or the day after (I need some time to understand how it works, install and configure everything and do it correctly)

**Comment by kurt-rhee** [comment]
@ToddEmonster  Did you ever figure out how to run pyinstaller with geopandas?  I'm running into the same problems.

**Comment by ToddEmonster** [comment]
@kurt-rhee 
From what I remember, when I had a "No module named 'fiona._shim' " error, it worked when I added this line to my code : `from fiona import _shim, schema`  

Since then I stopped trying to turn my program into an executable due to deadlines (it was an optional feature) so I can't help you much, but here are the imports of a code that I think worked, maybe it can help you : 

```
## Setting environment variables
import os
dirpath = os.getcwd()
path_gdal = repr(dirpath+"\gdal'")
path_proj= repr(dirpath+"\proj'")

import pyproj
pyproj.datadir.set_data_dir(path_proj)
os.environ['GDAL_DATA'] = path_gdal

## Imports

from pyproj import _datadir, datadir
from fiona import _shim, schema

import geopandas as gpd
from shapely.geometry import Point, LineString 
```

(I set "environment variables" there was because I got pyproj problems, so I had to set GDAL and PROJ environment variables to fix this.)

I have no time to help you more now, but I'll have more time in mid-October. I will FINALLY do the pull-request and if you're still stuck and no one has helped you still, I can try.

**Comment by supadhayay-rms** [comment]
Yes, I was able to fix it using changes in .spec file. I shared answer on following link:
https://stackoverflow.com/questions/56644056/pyinstaller-not-able-to-create-exe-using-geopandas-and-fiona-even-if-i-create-w

**Comment by kurt-rhee** [comment]
@supadhayay-rms I have already tried this and it does not work.  Can you please reopen?

```
import sys
sys.setrecursionlimit(5000)
block_cipher = None


a = Analysis(['Auto_Layout.py'],
             pathex=['G:\\General\\Solar\\R_and_D\\CodeLibrary\\Python\\AutoLayout'],
             binaries=[],
             datas=[],
             hiddenimports=['fiona._shim','fiona.schema'],
             hookspath=[r"G:\General\Solar\R_and_D\CodeLibrary\Python\AutoLayout"],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='Auto_Layout',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='Auto_Layout')
```

**Comment by supadhayay-rms** [comment]
@kurt-rhee If you check my pathex, you will see I am importing/adding packages like rtree, osgeo etc.
In hidden imports you have used only 'fiona._shim','fiona.schema' but I am having followings:
   'fiona',
    'gdal',
    'shapely',
    'shapely.geometry',
    'pyproj',
    'rtree',
    'geopandas.datasets',
    'pytest',
    'pandas._libs.tslibs.timedeltas',
    'fiona._shim'.

My whole spec file looks like following (change the paths as per your machine):

block_cipher = None

import os
from PyInstaller.utils.hooks import collect_data_files # this is very helpful
from osgeo import gdal, ogr, osr
from fiona.ogrext import Iterator, ItemsIterator, KeysIterator
from geopandas import GeoDataFrame
rTreeDlls = 'C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\rtree'

paths = [
    'C:\\Users\\supadhayay',
    rTreeDlls,
    'C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\DLLs',
    'C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\osgeo'
]

_osgeo_pyds = collect_data_files('osgeo', include_py_files=True)
_osgeo_pyds  = _osgeo_pyds  + collect_data_files('fiona', include_py_files=True)

osgeo_pyds = []
for p, lib in _osgeo_pyds:
    if '.pyd' in p or '.pyx' in p or '.pyc' in p:
        osgeo_pyds.append((p, '.'))

print(osgeo_pyds)

binaries = osgeo_pyds +[
    (os.path.join(rTreeDlls,'spatialindex-64.dll'), '.'),
    (os.path.join(rTreeDlls,'spatialindex_c.dll'),'.'),
]

hidden_imports = [
    'fiona',
    'gdal',
    'shapely',
    'shapely.geometry',
    'pyproj',
    'rtree',
    'geopandas.datasets',
    'pytest',
    'pandas._libs.tslibs.timedeltas',
    'fiona._shim',
]


a = Analysis(['D:\\SDR\\Repo\\Main\\DBEngg\\Spatial Data Repository\\States_Data_Processing_With_Geometry\\States_Data_Processing_With_Geometry_MP.py'],
             pathex=paths,
             binaries=osgeo_pyds +[('C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\shapely\\DLLs\\geos_c.dll', '.'),('C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\rtree\\spatialindex_c.dll', '.'), ('C:\\Users\\supadhayay\\AppData\\Local\\Programs\\Python\\Python37\\Lib\\site-packages\\rtree\\spatialindex-64.dll', '.')],
             datas=collect_data_files('geopandas', subdir='datasets') + [('D:\\SDR\\Repo\\Main\\DBEngg\\Spatial Data Repository\\States_Data_Processing_With_Geometry\\lg-logo-rms.png','.'),('D:\\SDR\\Repo\\Main\\DBEngg\\Spatial Data Repository\\States_Data_Processing_With_Geometry\\SQL_States_Data_Processing.sql','.')],
             hiddenimports=hidden_imports,
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='States_Data_Processing_With_Geometry_MP',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          runtime_tmpdir=None,
          console=True )

**Comment by kurt-rhee** [comment]
@supadhayay-rms Ah I see.  I've added the rest of the files to my spec but then get the following error:

C:\Users\simon.rhee\AppData\Local\Continuum\anaconda3\envs\geo_env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:627: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
G:\Projects\USA_North\Holliday_Creek\04_Solar\044_EPEs\EPE_Holliday Creek_20190923_V32.xlsm
Traceback (most recent call last):
  File "Auto_Layout.py", line 99, in <module>
  File "site-packages\geopandas\geodataframe.py", line 443, in to_crs
  File "site-packages\geopandas\geoseries.py", line 304, in to_crs
  File "site-packages\pyproj\__init__.py", line 362, in __new__
  File "_proj.pyx", line 129, in _proj.Proj.__cinit__
RuntimeError: b'no arguments in initialization list'

The error occurs on line:
        ```gf = gf.to_crs(epsg=epsg_code)```
where gf is a geodataframe from geopandas

**Comment by kurt-rhee** [comment]
Okay I was able to get rid of the no arguments in initialization list error by following the steps in here:

https://stackoverflow.com/questions/55390492/runtimeerror-bno-arguments-in-initialization-list

But now I get:
Traceback (most recent call last):
  File "Auto_Layout.py", line 342, in <module>
  File "site-packages\geopandas\geodataframe.py", line 413, in to_file
  File "site-packages\geopandas\io\file.py", line 116, in to_file
  File "site-packages\fiona\env.py", line 396, in wrapper
  File "site-packages\fiona\__init__.py", line 263, in open
  File "site-packages\fiona\collection.py", line 162, in __init__
  File "fiona/ogrext.pyx", line 922, in fiona.ogrext.WritingSession.start
  File "fiona/_shim.pyx", line 97, in fiona._shim.gdal_create
fiona.errors.DriverError: Failed to find template header file header.dxf for reading, is GDAL_DATA set properly?
[17112] Failed to execute script Auto_Layout

**Comment by samuel-johnston-tcc** [comment]
For anyone who is running into the "No Module found: fiona._shim" (and/or fiona.schema) issue and the above steps don't work, I had to add the related .so files to the list of binaries in my .spec file:

`binaries=[('[YOUR_PATH]/lib/python3.9/site-packages/fiona/_shim.cpython-39-darwin.so', 'fiona'), ('[YOUR_PATH]/lib/python3.9/site-packages/fiona/schema.cpython-39-darwin.so', 'fiona')],`

I did not need to add the modules to `hiddenimports` after doing this.

**Comment by nside** [comment]
just adding `from fiona import _shim, schema` fixed it for me on windows. thanks
