### ISSUE TITLE
Imported library but pyinstaller didn't build and add .PYD files

### ISSUE THREAD

**Issue by salembream** [pyinstaller/pyinstaller#4282]
So I am trying to build an app wich uses **dash** library, the codes work great but when i build it the **dash** library and its dependency libraries are not packaged, tho they are imported fine as they are present in " xref-*.html " file, I also added a hook file for it's  dependency libraries.

If I manually copy their directories from site-packages into my dist directory the program recognize them and works fine. but hey they are .PY file not .PYD,  and this is not an automated packaging "^^.

--------------------------------------

My setup:
**Miniconda3**
      tried both venv and the base interepter
**python3.6.8**

tried both **pyinstaller from pip** and **development version**

------------------------------------------------

maybe this is a silly question but how I can force pyinstaller to package a library?! 
all the tutorials and how-tos are about hidden imports and hook files, but my problem is the next step since pyinstaller recognize the libraries' import but doesn't package them

here is the output of build command ... nothing important really :( 
https://justpaste.it/7kt5d

I didn't find any .log file inside build directory...  

------ 
my program uses other big libraries , PyQt5, Matplotlib, Scipy... they all works fine but when i added the **dash** library, pyinstaller didn't package it :3

**Comment by hong6914** [comment]
The setup log shows that:

File "c:\programdata\miniconda3\lib\site-packages\matplotlib\backends\backend_webagg.py", line 26, in <module>
import tornado
ModuleNotFoundError: No module named 'tornado'

Traceback (most recent call last):
File "<string>", line 12, in <module>
File "c:\programdata\miniconda3\lib\site-packages\matplotlib\backends\backend_webagg.py", line 28, in <module>
raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.
