### ISSUE TITLE
Misleading description of 'binaries' in the doc of spec files

### ISSUE THREAD

**Issue by KenTsui** [pyinstaller/pyinstaller#4283]
The following code is an example provided in the [documentation of spec files](https://pythonhosted.org/PyInstaller/spec-files.html#adding-binary-files) to introduce how to use `binaries`.

```
a = Analysis(...
         binaries=[ ( '/usr/lib/libiodbc.2.dylib', 'libiodbc.dylib' ) ],
         ...
```

It seems to suggest that the syntax is `binaries = [ (<binary path>, <destination path>) ]`.

But after inspecting the unzipped executable in a temp folder compiled using Pyinstaller 3.5.dev0 under Python 3.7 in Windows 10, it is discovered that the actual syntax is `binaries = [ (<binary path>, <destination **folder**>) ]`.

For example, if you specify `binaries = [ ( 'C:\\helloworld.exe', 'helloworld.exe' ) ]`. You would find the folder structure of the unarchived executable as follows

unarchived-exe-temp-folder
├──  helloworld.exe (*this is a folder)
│                  └──helloworld.exe (*this is an executable)

P.S. My first time to open an issue in GitHub, please let me know if I need to provide any extra info.

**Comment by htgoebel** [comment]
Thanks for reporting. Indeed the documentation could be improved here.

For generating the destination names for both data and binaries, the same code is used ([`format_binaries_and_datas`](https://github.com/pyinstaller/pyinstaller/blob/v3.5/PyInstaller/building/utils.py#L447)), thus they behave the same.

> P.S. My first time to open an issue in GitHub, please let me know if I need to provide any extra info.

Well done! :-) Now what about submitting you first pull-request :-) See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.

You could adopt (correct) the example, maybe even add a second one, and refer to the [Adding Data Files](https://pythonhosted.org/PyInstaller/spec-files.html#adding-data-files) section for details.
