### ISSUE TITLE
Using Pyinstaller with Anaconda 3.7.3 needs PyQt5 even if not imported in code

### ISSUE THREAD

**Issue by skbobade** [pyinstaller/pyinstaller#4290]
Same issue reported in -
Anaconda-Platform/anaconda-project#207

I am writing a test code with Python and tested that it works on both Python 3.7 and 3.7.3
The code uses tkinter, and does not use PyQT5
I use pyinstaller 3.4 I convert the python to exe.

With the same code and and same dependencies (including version number) - while converting code to exe using pyinstaller 3.4, with Python 3.7.3 - Pyinstaller asks for additional imports related to PyQt5 (and maybe more). This causes executable to expand in size with unwanted dependencies bundled in output.

Doing same thing with Python 3.7 removes the issue.
Not sure if this is Anaconda specific or general Python issue.

Both tests were done in virtual environment with Anaconda Python 3.7.3 as base.
Attached logs from pyinstaller for both versions.

PyQt5 was installed when trying to make exe with Python 3.7.3 because without it pyinstaller will fail to produce output.

[withpy3.7.3 -without PyQt5.txt](https://github.com/pyinstaller/pyinstaller/files/3335830/withpy3.7.3.-without.PyQt5.txt)
[withpy3.7.3.txt](https://github.com/pyinstaller/pyinstaller/files/3335831/withpy3.7.3.txt)
[withpy3.7.txt](https://github.com/pyinstaller/pyinstaller/files/3335832/withpy3.7.txt)

**Comment by bjones1** [comment]
Try the latest version -- this should work if you don't have PyQt5 in your venv.
