### ISSUE TITLE
Pyinstaller packs a flask that contains a socketio

### ISSUE THREAD

**Issue by qxqxq** [pyinstaller/pyinstaller#4292]
spec file：hiddenimports=['pymysql', 'threading', 'flask_socketio', 'flask_socketio.SocketIO', 'gevent', 'geventwebsocket', 'gevent.ssl', 'gevent.builtins', 'engineio.async_gevent']

After successful packaging, run the executable file and report the following error.

Traceback (most recent call last):
  File "manage.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/flask_socketio/__init__.py", line 7, in <module>
  File "site-packages/gevent/monkey.py", line 976, in patch_all
  File "site-packages/gevent/monkey.py", line 178, in ignores
  File "site-packages/gevent/monkey.py", line 588, in patch_thread
  File "site-packages/gevent/monkey.py", line 487, in _patch_existing_locks
  File "site-packages/django/utils/functional.py", line 238, in inner
  File "site-packages/django/conf/__init__.py", line 39, in _setup
django.core.exceptions.ImproperlyConfigured: Requested settings, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
[73086] Failed to execute script manage

I haven't used Django yet, so why are there any Django errors.

**Comment by qxqxq** [comment]
I executed the command first.
pyinstaller -F manage.py --hidden-import=pymysql --add-data 'rgc/templates:templates' --add-data 'rgc/static:static' -n remotecenter

The output is as follows.

105 INFO: PyInstaller: 3.4
105 INFO: Python: 3.6.5
112 INFO: Platform: Darwin-18.0.0-x86_64-i386-64bit
113 INFO: wrote /Users/qxq/Desktop/remote-center/remotecenter.spec
117 INFO: UPX is not available.
119 INFO: Extending PYTHONPATH with paths
['/Users/qxq/Desktop/remote-center', '/Users/qxq/Desktop/remote-center']
119 INFO: checking Analysis
119 INFO: Building Analysis because Analysis-00.toc is non existent
119 INFO: Initializing module dependency graph...
122 INFO: Initializing module graph hooks...
124 INFO: Analyzing base_library.zip ...
3735 INFO: Analyzing hidden import 'pymysql'
4130 INFO: running Analysis Analysis-00.toc
4138 INFO: Caching module hooks...
4142 INFO: Analyzing /Users/qxq/Desktop/remote-center/manage.py
4958 INFO: Processing pre-find module path hook   distutils
8667 INFO: Processing pre-safe import module hook   six.moves
10274 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
13694 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
14271 INFO: Processing pre-find module path hook   site
14272 INFO: site: retargeting to fake-dir '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/fake-modules'
38690 INFO: Loading module hooks...
38690 INFO: Loading module hook "hook-sqlite3.py"...
38794 INFO: Loading module hook "hook-pkg_resources.py"...
39480 INFO: Processing pre-safe import module hook   win32com
39482 INFO: Loading module hook "hook-mako.codegen.py"...
39483 INFO: Loading module hook "hook-django.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/admin/__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/admin/options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/admin/widgets.py", line 3, in <module>
    from django.contrib.gis.gdal import GDALException
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 45, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
40761 INFO: Determining a mapping of distributions to packages...
75991 INFO: Packages required by django:
['pytz']
75992 WARNING: No django root directory could be found!
84053 INFO: Loading module hook "hook-pytz.py"...
84076 INFO: Loading module hook "hook-django.core.management.py"...
84774 INFO: Excluding import 'matplotlib'
84780 INFO: Excluding import 'IPython'
84784 INFO:   Removing import of IPython from module django.core.management.commands.shell
84785 INFO: Excluding import 'tkinter'
84791 INFO: Loading module hook "hook-django.db.backends.py"...
85282 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
85712 INFO: Loading module hook "hook-lib2to3.py"...
85715 INFO: Loading module hook "hook-_tkinter.py"...
85718 ERROR: Tcl/Tk improperly installed on this system.
85718 INFO: Loading module hook "hook-cryptography.py"...
86082 INFO: Loading module hook "hook-encodings.py"...
86168 INFO: Loading module hook "hook-jinja2.py"...
86198 INFO: Loading module hook "hook-IPython.py"...
86215 INFO: Excluding import 'PyQt4'
86224 INFO: Excluding import 'PySide'
86232 INFO: Excluding import 'PyQt5'
86239 INFO: Excluding import 'tkinter'
86246 INFO:   Removing import of tkinter from module IPython.lib.clipboard
86248 INFO: Excluding import 'matplotlib'
86254 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
86254 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
86254 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
86254 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
86256 INFO: Import to be excluded not found: 'gtk'
86256 INFO: Loading module hook "hook-PIL.py"...
86260 INFO: Excluding import 'PyQt4'
86264 INFO:   Removing import of PyQt4 from module PIL.ImageQt
86264 INFO: Excluding import 'PySide'
86268 INFO:   Removing import of PySide from module PIL.ImageQt
86268 INFO: Excluding import 'PyQt5'
86272 INFO:   Removing import of PyQt5 from module PIL.ImageQt
86272 INFO: Excluding import 'tkinter'
86276 INFO: Import to be excluded not found: 'FixTk'
86276 INFO: Loading module hook "hook-setuptools.py"...
87029 INFO: Loading module hook "hook-pycparser.py"...
87354 INFO: Loading module hook "hook-gevent.py"...
87526 WARNING: Unable to find package for requirement greenlet from package gevent.
87526 INFO: Packages required by gevent:
[]
87868 INFO: Loading module hook "hook-matplotlib.py"...
88179 INFO: Loading module hook "hook-selenium.py"...
88182 INFO: Loading module hook "hook-xml.dom.domreg.py"...
88183 INFO: Loading module hook "hook-PIL.Image.py"...
88510 INFO: Loading module hook "hook-jedi.py"...
88513 INFO: Loading module hook "hook-certifi.py"...
88514 INFO: Loading module hook "hook-matplotlib.backends.py"...
89157 INFO:   Matplotlib backend "GTK3Agg": ignored
    cairo backend requires that cairocffi or pycairo is installed
89501 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
90170 INFO:   Matplotlib backend "MacOSX": added
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
90942 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'ipykernel'
91282 INFO:   Matplotlib backend "Qt4Agg": ignored
    Failed to import any qt binding
91614 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
91951 INFO:   Matplotlib backend "Qt5Agg": ignored
    Failed to import any qt binding
92273 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
92720 INFO:   Matplotlib backend "TkAgg": added
93144 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
93493 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_webagg.py", line 27, in <module>
    import tornado
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_webagg.py", line 29, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
94072 INFO:   Matplotlib backend "WX": added
94530 INFO:   Matplotlib backend "WXAgg": added
94882 INFO:   Matplotlib backend "WXCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
95181 INFO:   Matplotlib backend "agg": added
95488 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
95963 INFO:   Matplotlib backend "pdf": added
96373 INFO:   Matplotlib backend "pgf": added
96682 INFO:   Matplotlib backend "ps": added
97006 INFO:   Matplotlib backend "svg": added
97403 INFO:   Matplotlib backend "template": added
98081 INFO: Loading module hook "hook-_mysql.py"...
98082 INFO: Loading module hook "hook-django.db.backends.oracle.base.py"...
98085 INFO: Loading module hook "hook-pytest.py"...
98758 INFO: Loading module hook "hook-sqlalchemy.py"...
99037 INFO:   Found 6 sqlalchemy hidden imports
99039 WARNING: Hidden import "sqlalchemy.orm.state", "sqlalchemy.orm.strategies" not found!
99070 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
99084 INFO: Excluding import 'sqlalchemy.testing'
99092 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.orm.util
99093 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing.warnings from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing
99093 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.warnings
99093 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.warnings
99093 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.assertions
99094 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing.assertions
99094 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing.assertions
99094 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing.assertions
99094 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.assertions
99094 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertions
99094 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.util
99094 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing.util
99094 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.util
99094 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.config
99095 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.engines
99095 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.engines
99095 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.engines
99095 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.engines
99097 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.exclusions
99097 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.exclusions
99097 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertsql
99097 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.mock
99098 INFO: Loading module hook "hook-django.core.mail.py"...
99151 INFO: Loading module hook "hook-django.core.cache.py"...
99252 INFO: Loading module hook "hook-sysconfig.py"...
99262 INFO: Loading module hook "hook-numpy.core.py"...
99320 INFO: Loading module hook "hook-xml.py"...
99321 INFO: Loading module hook "hook-pydoc.py"...
99322 INFO: Loading module hook "hook-numpy.py"...
99322 INFO: Loading module hook "hook-distutils.py"...
99323 INFO: Loading module hook "hook-pygments.py"...
100767 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
100774 INFO: Import to be excluded not found: 'FixTk'
100774 INFO: Excluding import 'tkinter'
100779 INFO: Loading module hook "hook-django.db.backends.mysql.base.py"...
100922 INFO: Looking for ctypes DLLs
100976 WARNING: library librt.so.1 required via ctypes not found
100977 WARNING: library librt.so.0 required via ctypes not found
100980 WARNING: library librt.so.1 required via ctypes not found
100989 WARNING: library ktmw32.dll required via ctypes not found
101018 WARNING: library user32 required via ctypes not found
101104 INFO: Analyzing run-time hooks ...
101126 INFO: Including run-time hook 'pyi_rth_django.py'
101128 INFO: Including run-time hook 'pyi_rth_pkgres.py'
101130 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
101133 INFO: Including run-time hook 'pyi_rth__tkinter.py'
101136 INFO: Including run-time hook 'pyi_rth_traitlets.py'
101189 INFO: Looking for dynamic libraries
101576 INFO: Looking for eggs
101576 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.6/Python
101608 INFO: Warnings written to /Users/qxq/Desktop/remote-center/build/remotecenter/warn-remotecenter.txt
101902 INFO: Graph cross-reference written to /Users/qxq/Desktop/remote-center/build/remotecenter/xref-remotecenter.html
102196 INFO: Appending 'datas' from .spec
102203 INFO: checking PYZ
102203 INFO: Building PYZ because PYZ-00.toc is non existent
102203 INFO: Building PYZ (ZlibArchive) /Users/qxq/Desktop/remote-center/build/remotecenter/PYZ-00.pyz
105371 INFO: Building PYZ (ZlibArchive) /Users/qxq/Desktop/remote-center/build/remotecenter/PYZ-00.pyz completed successfully.
105484 INFO: checking PKG
105484 INFO: Building PKG because PKG-00.toc is non existent
105484 INFO: Building PKG (CArchive) PKG-00.pkg
123139 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
123315 INFO: Bootloader /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/run
123315 INFO: checking EXE
123315 INFO: Building EXE because EXE-00.toc is non existent
123315 INFO: Building EXE from EXE-00.toc
123316 INFO: Appending archive to EXE /Users/qxq/Desktop/remote-center/dist/remotecenter
123383 INFO: Fixing EXE for code signing /Users/qxq/Desktop/remote-center/dist/remotecenter
123388 INFO: Building EXE from EXE-00.toc completed successfully.

Then modify the spec file.
From hiddenimports=['pymysql'] to hiddenimports = ['pymysql'，'threading'，'flask_socketio'，'flask_socketio.SocketIO'，'gevent'，'geventwebsocket'，'gevent.ssl'，'gevent.builtins'，'engineio.async_gevent'] .

Then execute the following command.
 pyinstaller remotecenter.spec

The output is as follows.

88 INFO: PyInstaller: 3.4
88 INFO: Python: 3.6.5
96 INFO: Platform: Darwin-18.0.0-x86_64-i386-64bit
99 INFO: UPX is not available.
101 INFO: Extending PYTHONPATH with paths
['/Users/qxq/Desktop/remote-center', '/Users/qxq/Desktop/remote-center']
101 INFO: checking Analysis
183 INFO: Building because inputs changed
183 INFO: Initializing module dependency graph...
186 INFO: Initializing module graph hooks...
188 INFO: Analyzing base_library.zip ...
3924 INFO: Analyzing hidden import 'pymysql'
4344 INFO: running Analysis Analysis-00.toc
4352 INFO: Caching module hooks...
4356 INFO: Analyzing manage.py
5094 INFO: Processing pre-find module path hook   distutils
8902 INFO: Processing pre-safe import module hook   six.moves
10610 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
14121 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
14721 INFO: Processing pre-find module path hook   site
14722 INFO: site: retargeting to fake-dir '/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/fake-modules'
39847 INFO: Loading module hooks...
39847 INFO: Loading module hook "hook-sqlite3.py"...
39924 INFO: Loading module hook "hook-pkg_resources.py"...
40368 INFO: Processing pre-safe import module hook   win32com
40561 INFO: Loading module hook "hook-mako.codegen.py"...
40562 INFO: Loading module hook "hook-django.py"...
Traceback (most recent call last):
  File "<string>", line 41, in <module>
  File "<string>", line 36, in walk_packages
  File "<string>", line 36, in walk_packages
  File "<string>", line 20, in walk_packages
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/admin/__init__.py", line 5, in <module>
    from django.contrib.gis.admin.options import GeoModelAdmin, OSMGeoAdmin
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/admin/options.py", line 2, in <module>
    from django.contrib.gis.admin.widgets import OpenLayersWidget
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/admin/widgets.py", line 3, in <module>
    from django.contrib.gis.gdal import GDALException
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/__init__.py", line 28, in <module>
    from django.contrib.gis.gdal.datasource import DataSource
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/datasource.py", line 39, in <module>
    from django.contrib.gis.gdal.driver import Driver
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/driver.py", line 5, in <module>
    from django.contrib.gis.gdal.prototypes import ds as vcapi, raster as rcapi
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/prototypes/ds.py", line 9, in <module>
    from django.contrib.gis.gdal.libgdal import GDAL_VERSION, lgdal
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/django/contrib/gis/gdal/libgdal.py", line 45, in <module>
    % '", "'.join(lib_names)
django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
41725 INFO: Determining a mapping of distributions to packages...
73967 INFO: Packages required by django:
['pytz']
73968 WARNING: No django root directory could be found!
81371 INFO: Loading module hook "hook-pytz.py"...
81395 INFO: Loading module hook "hook-django.core.management.py"...
81940 INFO: Excluding import 'matplotlib'
81946 INFO: Excluding import 'tkinter'
81950 INFO: Excluding import 'IPython'
81954 INFO:   Removing import of IPython from module django.core.management.commands.shell
81955 INFO: Loading module hook "hook-django.db.backends.py"...
82400 WARNING: Hidden import "django.db.backends.__pycache__.base" not found!
82759 INFO: Loading module hook "hook-lib2to3.py"...
82761 INFO: Loading module hook "hook-_tkinter.py"...
82765 ERROR: Tcl/Tk improperly installed on this system.
82765 INFO: Loading module hook "hook-cryptography.py"...
83039 INFO: Loading module hook "hook-encodings.py"...
83115 INFO: Loading module hook "hook-jinja2.py"...
83136 INFO: Loading module hook "hook-IPython.py"...
83152 INFO: Excluding import 'PySide'
83160 INFO: Excluding import 'matplotlib'
83166 INFO:   Removing import of matplotlib._pylab_helpers from module IPython.core.pylabtools
83166 INFO:   Removing import of matplotlib from module IPython.core.pylabtools
83166 INFO:   Removing import of matplotlib.pyplot from module IPython.core.pylabtools
83166 INFO:   Removing import of matplotlib.figure from module IPython.core.pylabtools
83168 INFO: Excluding import 'PyQt4'
83174 INFO: Excluding import 'tkinter'
83180 INFO:   Removing import of tkinter from module IPython.lib.clipboard
83181 INFO: Excluding import 'PyQt5'
83188 INFO: Import to be excluded not found: 'gtk'
83188 INFO: Loading module hook "hook-PIL.py"...
83192 INFO: Excluding import 'PySide'
83196 INFO:   Removing import of PySide from module PIL.ImageQt
83196 INFO: Excluding import 'PyQt4'
83200 INFO:   Removing import of PyQt4 from module PIL.ImageQt
83200 INFO: Excluding import 'tkinter'
83204 INFO: Import to be excluded not found: 'FixTk'
83204 INFO: Excluding import 'PyQt5'
83208 INFO:   Removing import of PyQt5 from module PIL.ImageQt
83208 INFO: Loading module hook "hook-setuptools.py"...
83903 INFO: Loading module hook "hook-pycparser.py"...
84181 INFO: Loading module hook "hook-gevent.py"...
84344 WARNING: Unable to find package for requirement greenlet from package gevent.
84344 INFO: Packages required by gevent:
[]
84625 INFO: Loading module hook "hook-matplotlib.py"...
84931 INFO: Loading module hook "hook-selenium.py"...
84935 INFO: Loading module hook "hook-xml.dom.domreg.py"...
84936 INFO: Loading module hook "hook-PIL.Image.py"...
85316 INFO: Loading module hook "hook-jedi.py"...
85319 INFO: Loading module hook "hook-certifi.py"...
85320 INFO: Loading module hook "hook-matplotlib.backends.py"...
85931 INFO:   Matplotlib backend "GTK3Agg": ignored
    cairo backend requires that cairocffi or pycairo is installed
86243 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
86792 INFO:   Matplotlib backend "MacOSX": added
/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/IPython/kernel/__init__.py:13: ShimWarning: The `IPython.kernel` package has been deprecated since IPython 4.0.You should import from ipykernel or jupyter_client instead.
  "You should import from ipykernel or jupyter_client instead.", ShimWarning)
87542 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'ipykernel'
87867 INFO:   Matplotlib backend "Qt4Agg": ignored
    Failed to import any qt binding
88185 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
88539 INFO:   Matplotlib backend "Qt5Agg": ignored
    Failed to import any qt binding
88865 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
89320 INFO:   Matplotlib backend "TkAgg": added
89769 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
90085 INFO:   Matplotlib backend "WebAgg": ignored
    Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_webagg.py", line 27, in <module>
    import tornado
ModuleNotFoundError: No module named 'tornado'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 12, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/matplotlib/backends/backend_webagg.py", line 29, in <module>
    raise RuntimeError("The WebAgg backend requires Tornado.")
RuntimeError: The WebAgg backend requires Tornado.
90697 INFO:   Matplotlib backend "WX": added
91181 INFO:   Matplotlib backend "WXAgg": added
91571 INFO:   Matplotlib backend "WXCairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
91912 INFO:   Matplotlib backend "agg": added
92246 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that cairocffi or pycairo is installed
92697 INFO:   Matplotlib backend "pdf": added
93133 INFO:   Matplotlib backend "pgf": added
93459 INFO:   Matplotlib backend "ps": added
93781 INFO:   Matplotlib backend "svg": added
94216 INFO:   Matplotlib backend "template": added
94911 INFO: Loading module hook "hook-_mysql.py"...
94911 INFO: Loading module hook "hook-django.db.backends.oracle.base.py"...
94915 INFO: Loading module hook "hook-pytest.py"...
95619 INFO: Loading module hook "hook-sqlalchemy.py"...
95891 INFO:   Found 6 sqlalchemy hidden imports
95892 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
95892 WARNING: Hidden import "sqlalchemy.orm.state", "sqlalchemy.orm.strategies" not found!
95926 INFO: Excluding import 'sqlalchemy.testing'
95932 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.orm.util
95933 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing.warnings from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing
95933 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.warnings
95933 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.warnings
95933 INFO:   Removing import of sqlalchemy.testing.assertsql from module sqlalchemy.testing.assertions
95933 INFO:   Removing import of sqlalchemy.testing.mock from module sqlalchemy.testing.assertions
95933 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.assertions
95934 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.assertions
95934 INFO:   Removing import of sqlalchemy.testing.exclusions from module sqlalchemy.testing.assertions
95934 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertions
95934 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.util
95934 INFO:   Removing import of sqlalchemy.testing.engines from module sqlalchemy.testing.util
95934 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.util
95934 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.config
95934 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.engines
95934 INFO:   Removing import of sqlalchemy.testing.assertions from module sqlalchemy.testing.engines
95934 INFO:   Removing import of sqlalchemy.testing.util from module sqlalchemy.testing.engines
95934 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.engines
95936 INFO:   Removing import of sqlalchemy.testing.config from module sqlalchemy.testing.exclusions
95936 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.exclusions
95936 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.assertsql
95936 INFO:   Removing import of sqlalchemy.testing from module sqlalchemy.testing.mock
95937 INFO: Loading module hook "hook-django.core.mail.py"...
95983 INFO: Loading module hook "hook-django.core.cache.py"...
96072 INFO: Loading module hook "hook-sysconfig.py"...
96082 INFO: Loading module hook "hook-numpy.core.py"...
96137 INFO: Loading module hook "hook-xml.py"...
96139 INFO: Loading module hook "hook-pydoc.py"...
96139 INFO: Loading module hook "hook-numpy.py"...
96140 INFO: Loading module hook "hook-distutils.py"...
96141 INFO: Loading module hook "hook-pygments.py"...
97550 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
97556 INFO: Excluding import 'tkinter'
97560 INFO: Import to be excluded not found: 'FixTk'
97560 INFO: Loading module hook "hook-django.db.backends.mysql.base.py"...
97704 INFO: Looking for ctypes DLLs
97754 WARNING: library librt.so.0 required via ctypes not found
97755 WARNING: library librt.so.1 required via ctypes not found
97757 WARNING: library librt.so.1 required via ctypes not found
97765 WARNING: library ktmw32.dll required via ctypes not found
97789 WARNING: library user32 required via ctypes not found
97869 INFO: Analyzing run-time hooks ...
97891 INFO: Including run-time hook 'pyi_rth_django.py'
97894 INFO: Including run-time hook 'pyi_rth_pkgres.py'
97896 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
97899 INFO: Including run-time hook 'pyi_rth__tkinter.py'
97901 INFO: Including run-time hook 'pyi_rth_traitlets.py'
97952 INFO: Looking for dynamic libraries
98341 INFO: Looking for eggs
98341 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.6/Python
98368 INFO: Warnings written to /Users/qxq/Desktop/remote-center/build/remotecenter/warn-remotecenter.txt
98641 INFO: Graph cross-reference written to /Users/qxq/Desktop/remote-center/build/remotecenter/xref-remotecenter.html
98909 INFO: Appending 'datas' from .spec
98916 INFO: checking PYZ
98947 INFO: Building because toc changed
98948 INFO: Building PYZ (ZlibArchive) /Users/qxq/Desktop/remote-center/build/remotecenter/PYZ-00.pyz
102058 INFO: Building PYZ (ZlibArchive) /Users/qxq/Desktop/remote-center/build/remotecenter/PYZ-00.pyz completed successfully.
102155 INFO: checking PKG
102205 INFO: Building because toc changed
102206 INFO: Building PKG (CArchive) PKG-00.pkg
120159 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
120347 INFO: Bootloader /Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/run
120347 INFO: checking EXE
120402 INFO: Building because toc changed
120402 INFO: Building EXE from EXE-00.toc
120402 INFO: Appending archive to EXE /Users/qxq/Desktop/remote-center/dist/remotecenter
120490 INFO: Fixing EXE for code signing /Users/qxq/Desktop/remote-center/dist/remotecenter
120496 INFO: Building EXE from EXE-00.toc completed successfully.

**Comment by htgoebel** [comment]
Read this error meaasge:
> django.core.exceptions.ImproperlyConfigured: Could not find the GDAL library (tried "gdal", "GDAL", "gdal2.1.0", "gdal2.0.0", "gdal1.11.0", "gdal1.10.0", "gdal1.9.0"). Is GDAL installed? If it is, try setting GDAL_LIBRARY_PATH in your settings.
