### ISSUE TITLE
No output or results of any kind when I run the executable built by PyInstaller

### ISSUE THREAD

**Issue by monocongo** [pyinstaller/pyinstaller#4297]
I have built my application with PyInstaller with no apparent errors. However, when I run the application on the same system where it was built it appears to do nothing. I get no output whatsoever so it is impossible to diagnose the issue. I initially built the executable as `--onefile` but after reading the guide regarding what to do when things go wrong I have tried using `--onedir` instead, as well as `--noupx`. I have also tried the `strace` command suggested in the guide but I cannot see anything there that indicates my error. For example:
```
$ pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
$ rm -rf build/ dist/
$ rm -rf ~/.local/share/pyinstaller
$ pyinstaller --onedir --noupx --log-level=DEBUG deep_monitor.py > out.txt 2>&1
$ ./dist/deep_monitor/deep_monitor  # no output whatsover here
$ strace -f -e trace=open ./dist/deep_monitor/deep_monitor 
strace: Process 19827 attached
[pid 19827] +++ exited with 0 +++
--- SIGCHLD {si_signo=SIGCHLD, si_code=CLD_EXITED, si_pid=19827, si_uid=1000, si_status=0, si_utime=8, si_stime=2} ---
+++ exited with 0 +++
```

The script file:
```
from deep_monitor.__main__ import main


# CLI code for use with pyinstaller
if __name__ == "__main__":

    main()
```

The output file containing the output and debug messages from the PyInstaller build is [here](https://gist.github.com/monocongo/2a54e177933f3c858c43596858b700db).

I am performing this build on Linux (Ubuntu 18.04), with plans to repeat the process on Windows and MacOS once the bugs are worked out.

Please advise if there is anything further I can provide to help diagnose this issue. Thanks in advance for any suggestions, I really appreciate your help.

Also in general thanks for the substantial effort that goes into developing and supporting PyInstaller as a free open-source project.

**Comment by htgoebel** [comment]
```
$ ./dist/deep_monitor/deep_monitor  # no output whatsover here
```
Your program contains not `print`, thus obviously there is no output.

```
$ strace -f -e trace=open ./dist/deep_monitor/deep_monitor 
```
`open` might be too restrictive. Please try `file` or `all`. `man strace` is your friend.

Closing since I can not spot any real issue here.

**Comment by monocongo** [comment]
When I run my code from the command line I see plenty of output, primarily log messages from within the `deep_monitor.__main__.main` function, as well as various informational and innocuous warning messages from TensorFlow and OpenCV. Why I don't see any of this when I run the executable built by PyInstaller is not clear, but for certain, there is expected output at the console when I run the code normally (i.e. `$ python deep_monitor.__main__.py`).

**Comment by htgoebel** [comment]
Maybe `deep_monitor.__main__.main` terminates without any error message for some reason, Try adding `import  pdb ; pdb.set_trace()` to the very top of the script you showed above. Then step through the code.

**Comment by monocongo** [comment]
Yes, this is the issue -- why is it terminating unexpectedly and without any error message when I run the executable produced by PyInstaller?

Thanks for your suggestion about using `pdb`. I will give that a whirl and hopefully it will reveal the cause of this issue.
