### ISSUE TITLE
Can not find path ./libc++.1.dylib

### ISSUE THREAD

**Issue by hargun-singh** [pyinstaller/pyinstaller#4298]
PyInstaller throws the following errors:
Can not find path ./libc++.1.dylib (needed by /venv/lib/python3.6/site-packages/torch/_C.cpython-36m-darwin.so)
Can not find path ./libiomp5.dylib (needed by /venv/lib/python3.6/site-packages/torch/lib/libmklml.dylib)

As you can see, the errors are caused while using torch package. No such error takes place if I don't use this package. 

To reproduce the problem, simply try 'import torch' in any script.

I looked into #1514 and #1965 but they don't seem to solve my problem.

OS Version - MacOs 10.14.5
Python Version - 3.6.5
PyInstaller version - 3.4

I also tried installing the developer version of pyInstaller but that didn't solve my issue as well

**Comment by bwoodsend** [comment]
There have been some hook contributions since. They appear to have fixed this as it now works for me.
