### ISSUE TITLE
exception handler that logs exceptions to log files if bundled app crashes

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#430]
**Original date**: 2011/10/04

From http://groups.google.com/group/pyinstaller/browse_thread/thread/7ba7b9efad7feb01

The only way to implement such a feature is to install an exception handler in Python. I think it's a feature that could make sense for PyInstaller: when console is disabled, an exception handler should be installed that logs exceptions to log files and/or display a message box using the OS native GUI support, possibly through a different process not to create weird interactions with any running GUI in the user's application.

Obviously this would be a debug feature that can be disabled if not needed.

**Comment by matysek** [comment]
@htgoebel Is this still relevant feature?

**Comment by htgoebel** [comment]
It's bee a suggestion on the mailinglist back in 2011. If you think, this is useful. Otherwise just close the ticket.

**Comment by matysek** [comment]
I'm closing this. This feature is up to every app to implement any logging. And on OS X in debug mode pyinstaller debug messages are sent to syslog so it is easy to see those messages.
