### ISSUE TITLE
Automated release process

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#4300]
This is a copy of https://github.com/pyinstaller/pyinstaller/issues/2692#issuecomment-323542787 (by @xoviat) to avoid this gets buried in an unrelated issue:

* [x]  Pin libraries so that the test suite works.
* [x]  Implement towncrier to build NEWS over time with each PR
  * [ ] implement unittest that fails if TRAVIS_PULL_REQUEST is present and news files are note well formatted or not all news files are processed by towncrier.
  * [ ] implement unittest that fails if TRAVIS_PULL_REQUEST is present and news file is not present.
* [ ]  Implement cron to recompile bootloaders and commit changes back to the repository automatically.
  Please note: Policy is still to compile bootloaders on a trusted environment - which excludes all cloud services. I'm *not* trusting bootloaders build on some system we have no control over. No, I'm not trusting cloud services. Our users need to trust us so we need to take care that the bootloaders are not contaminated. Thus this would have to be implemented on a core-developer's machine.
* [ ]  Implement cron to automatically check tags and post new releases on web site.
* [ ]  Implement autogeneration of announcements on mailing list (announcement can be a simple "x has been released, with the following changes: {NEWS}).

The bot is at pypa/browntruck.

**Comment by htgoebel** [comment]
(Copied from https://github.com/pyinstaller/pyinstaller/issues/2692#issuecomment-325274500)
On the [debops/debop](http://github.com/debops/debops) mailinglist I just got this information. Maybe this is useful for us:

> https://help.github.com/articles/about-codeowners/.
In short, it's a file in the root directory of the repository that specifies
what files or paths are maintained by who, and when a new PR is published that
changes one of these files, a person is added as a reviewer of that PR. Of
course this works only on GitHub, but could be scripted elsewhere. Linux
kernel uses a similar system with the MAINTAINERS file, which was an
inspiration for the CODEOWNERS on GitHub.

And a reply on this:
> > That would solve it. [Being much more difficult to watch only parts of DebOps]
>
> Hm, at least partly. People will still open issues I guess which would notify
all people watching the repo. At least for that case, a issue template might be
useful.

**Comment by Legorooj** [comment]
@htgoebel #4688 might be of interest. I know you're not a microsoft fan, but...

**Comment by bwoodsend** [comment]
The release process as it is now is streamlined enough.
