### ISSUE TITLE
Hooks provided by 3rd party: Methods to collect hooks

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#4301]
Related to https://github.com/pyinstaller/pyinstaller/issues/4232#issuecomment-508412773

This is a comparison of methods to collect hooks. My conclusion after compiling this is: Entry-points are the most flexible method, even allowing for version-specific changes (in the future)

### Namespaces

* Pro: Easy to implement for distributors: Simply add `"pyinstaller_hooks"` to the list of packages in `setup.py` like this
  ```python
  setup(…
      packages=['packageA', 'pyinstaller_hooks']
  )
  ```
* Con: Requires *all* distributions to use the same namespace style (pkg_resources-style for highest compatibility).
* Con: Requires the package delimiter (".") to be replaced by some other symbol - which is at least ugly.
* Pro: Easy to implement for PyInstaller.
* Pro: Low chance of freezing the hooks by accident. (The hooks will not be part of the package modules or package data and thus not be including by `collect_submodules()` or `collect_data_files()`.)
* Pro: pre-find-module-path and pre-safe-import-module hooks could simply be collected the same way.
* Pro: PyInstaller could *not* warn about duplicate hooks (since conflicts are (not) handled ar install-time.
* Con; For runtime-hooks we either need a new naming-convention for `.dat`-files or a new convention how to specify the rt-hooks.
* Con: Hook files must use a different namneed to comply to the expectations if `pkgutil.iter_modules()`: Can't use the dot (`.`) as package delimiter any longer.

### Entry Points for hook-directories

* Pro: Easy to implement for PyInstaller
* Pro: Leverage existing `additional-hooks-dir` mechanism, incl. pre-find-module-path and pre-safe-import-module hooks.
* Con: Distributors need to implement a function to provide the list of hook-dirs. (But this might be easy, esp. when we provide an example project.)
* Con: Distributors need to explicitly specify every hook-dir like this:
```python
setup(...
    entry_points = {
	'pyinstaller34': [
            'hooks-dirs = myPackage.pyinstaller_hooks:hooks_dirs',
        ],
    },
)
```
* Pro: Distributors can choose the hooks-dir place much more freely.
* Pro: PyInstaller could warn about duplicate hooks or rt-hooks.
* Con: Hooks actually need to be files - packages can not be installed as a zipped egg. This could cause problems at the end-developer. (Side note: Does PyInstaller actually support freezing from zipped egg? I know there is some provisioning for this, but doe this *actually* work?)
* Con: Medium chance of freezing the hooks by accident. (The hooks will be part of the package modules or package data and thus be including by `collect_submodules()`.
* Neutral: More overhead at PyInstaller run-time since all installed distributions will be scanned for entry-points. OTOH this should be negligible.

### Entry points for each hooks

* Pro: Easy to implement for PyInstaller.
* Con: Entry-points need to be importable, which means: Hook files need to comply to the Python module naming conventions (esp. no dots).
* Con: Distributors need to explicitly specify *every* hook like this:
```python
setup(...
    entry_points = {
	'pyinstaller.hooks': [
	    'myPackage = myPackage.pyinstaller_hooks.myPackage',
	    'myPackage.sub.module1 = myPackage.pyinstaller_hooks.module1',
        ],
	'pyinstaller.pre-safe-import-module-hooks': [
	    'myPackage = myPackage.pyinstaller_hooks.psimhook',
        ],
    },
)
```
* Pro: Distributors can name the hooks files (modules) much more freely.
* Pro: PyInstaller could warn about duplicate hooks or rt-hooks.
* Con: Medium chance of freezing the hooks by accident. (The hooks will be part of the package modules or package data and thus be including by `collect_submodules()`.
* Neutral: More overhead at PyInstaller run-time since all installed distributions will be scanned for entry-points. OTOH this should be negligible.

### Package-Data (without Entry Points)

* Con: Hard to implement for PyInstaller: No efficient way to get a list of all existing hooks.
* Con: High chance of freezing the hooks by accident. (The hooks will be part of the package data and thus be including by `collect_data_files()`.)
* Pro: Hook files don't need to comply to any naming-convention beside the one defined by PyInstaller. (We could keep our existing naming-convention.)

### Hooks as Additional Metadata

Since hooks are actually no "code", the idea is to store them as meta-data.

* Con: Either hard to implement for distributors or would require every distribution providing PyInstaller hooks to `setup_requires` some supporting packages.

The idea is described in
https://setuptools.readthedocs.io/en/latest/setuptools.html#defining-additional-metadata.
But to make the packagers' life easy, this would required some setuptool
extension (see
https://setuptools.readthedocs.io/en/latest/setuptools.html#adding-new-egg-info-files)
- which then would be a `setup_requires` for this package.

**Comment by bjones1** [comment]
I agree with your conclusion: entry-points are the best approach. In particular, I favor entry points for hook directories. If we allow this function to return a list, then that removes one con (distributors need to explicitly specify every hook-dir). One weakness of the current approach is, as you say, that hooks actually need to be files. In the future, it would be good to rewrite this to specify hook directories in terms of two strings: a package and then a resource name, enabling use of setuptools' [basic resource access](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#basic-resource-access). However, given our limited time, I don't want to do this now.

If you like this approach, I can put together a PR.

**Comment by htgoebel** [comment]
Please go ahead and provide a pull-request.

I plasn to do a release the next days, and another release as soon as his pull-request is merged.
