### ISSUE TITLE
'_MEIPASS' gives short version on windows

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4304]
When using `getattr(sys, "_MEIPASS")` on windows the return value is the short version

This is a small test:
```
import os
import sys
import win32api

print("_MEIPASS: %s" % getattr(sys, "_MEIPASS"))
print("GetLongPathName: %s" % win32api.GetLongPathName(getattr(sys, "_MEIPASS")))
print("sys.executable: %s" % os.path.dirname(sys.executable))
```
Output:
```
(test) PS C:\Users\Amir Rossert\test> .\dist\test\test.exe
_MEIPASS: C:\Users\AMIRRO~1\test\dist\test
GetLongPathName: C:\Users\Amir Rossert\test\dist\test
sys.executable: C:\Users\Amir Rossert\test\dist\test
```

So my otions are to use `win32api.GetLongPathName` or `os.path.dirname(sys.executable)`
Using `win32api` is not portable so I will be using the `sys.executable` option for now.
Is this behavior is expected?

**Comment by BoboTiG** [comment]
First, the short path version is Windows only, so there is no portable issue.
I do not know if it is intended, but it is well done because it fixes issues with long patsh and unicode paths.

Then, you could do:
```python
meipass = getattr(sys, "_MEIPASS", "")

# using os;path:
full_path = os.path.abspath(meipass)

# or using pathlib.Path:
full_path = Path(meipass).resolve()
```

**Comment by htgoebel** [comment]
Yes, this is intended for exactly the reason you say.
