### ISSUE TITLE
Failing import when using module name in hiddenimports to trigger another hook

### ISSUE THREAD

**Issue by lkollar** [pyinstaller/pyinstaller#4306]
I have a C-extension built with Cython which imports `six.moves.queue`. `six.moves` is a module which dynamically creates attributes so the [`six.moves` pre_safe_import_module](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py) has to be used to properly handle it in PyInstaller.

As this import occurs inside a C-extension PyInstaller does not see it, thus the hook doesn't get activated. If I create a hook for the C-extension and add `six.moves` as a `hiddenimport` , the `six.moves` hook is activated but the resulting binary still fails on the `six.moves.queue` import. The only way I was able to fix this was by adding the full `six.moves.queue` import name in `hiddenimports`. Even with this change a warning is emitted:

`runtime module named six.moves - imported by queue (top-level)`.

Ideally the hook should only need `"six.moves"` in `hiddenimports` so that every `six.moves` attribute will work without needing to modify the hook when a new import is added.

I am puzzled by the behaviour as when the `six.moves` hook is triggered by a pure Python file the `add_runtime_package` function seems to get the package name and not the module, so I would expect this to work the same way when forcing the hook by specifying `six.moves` as a hidden import. I'm sure I'm missing something here.

TRACE logs from using
- `hiddenimports = ["six.moves"]` (failure): https://gist.github.com/lkollar/6a4679c33a08c303c320230fef664bd4 
- `hiddenimports = ["six.moves.queue"]` (success): https://gist.github.com/lkollar/401d97f4e283968b3058b93b62117705

You can see that the following line invoking `safe_import_module` only gets called in the second case:
`safe_import_module 'queue' 'six.moves.queue' RuntimePackage('six.moves',)`

If there is a different way to get PyInstaller to pick up a hook from inside another hook let me know. If that is the case this probably just needs documented.

```
PyInstaller: 3.5
Python: 3.7.2
Platform: Linux-4.9.125-linuxkit-x86_64-with-redhat-6.10-Santiago
```

**Comment by htgoebel** [comment]
six.moves are very special as they are generated at run-time. This requires a lot of hacking, see PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py.. Maybe this triggers a different execution path, even if it should behave the same.

Tracking this down is very time consuming and IMHO not worth the effort. Thus I'm closing this as "wont fix". If you feel this case should be solve, feel free to submit a pull-request.

Anyway I'd appreciate if you could document this briefly in a recipe in the wiki.
