### ISSUE TITLE
progame crashed with flag -w/--noconsole

### ISSUE THREAD

**Issue by lovejunjie1** [pyinstaller/pyinstaller#4307]
![34E4(KCN61_8V 5378{OH_P](https://user-images.githubusercontent.com/8145477/61061339-9ebabd80-a42e-11e9-82a2-dbd4daf50fd3.png)

when i use pyinstaller .package my script.

the error will appear. cause i use flag --noconsole/-w.

my env -> python 2.7.16/windows10

I removed the flag --noconsole/-w.the program worked greate.

could you help me to fix the bug.or give me a way to hide console?

**Comment by htgoebel** [comment]
No change, given this few information. I assume you ae using GUI in your programm and thus it requires --windowed.

**Comment by unwenliu** [comment]
I encountered the same problem. Is it resolved now?
