### ISSUE TITLE
pyinstaller packed error : no module found

### ISSUE THREAD

**Issue by rkzlym** [pyinstaller/pyinstaller#4309]
Hi, I have one problem to pack my project to exe

I go to my directory and input command : pyinstaller -F run.py

Then a lot of warning show LIKE THIS: 
15280 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of e:\python\DLLs\_decimal.pyd

But finally It shows : Building EXE from EXE-00.toc completed successfully.
I think it's completed.

But when I run my exe file It shows :
**ModuleNotFoundError : No module named 'win32gui'**
I am sure I installed this module and run successfully in my Debug Environment, but pyinstaller cannot found and I have no idea how to solve this problem.

By the way, My Enviroment is : win10, Python3.7.3

**Comment by htgoebel** [comment]
Given the few information you provided, I guess you need tom hidden import. Please read the manual for this.
