### ISSUE TITLE
How to use pyinstaller to write the completed program on the macos platform and publish it to the Linux platform?

### ISSUE THREAD

**Issue by ReadRou** [pyinstaller/pyinstaller#4313]
Recently, I was writing a flask program. I don't want to install the environment on the Linux (server) platform, so I used pyinstaller to package my program and then released it to the Linux platform, but I got a mistake.

```shell
-bash: ./blog: cannot execute binary file: Exec format error
```

I have tried a lot of methods that have not been solved. What should I do?

**Comment by htgoebel** [comment]
You can't cross-build. Please read the manual, this is what we wrote it for.
