### ISSUE TITLE
missing bootloader python37-32 on 64bit machine

### ISSUE THREAD

**Issue by atsju** [pyinstaller/pyinstaller#4318]
Installing pyinstaller on a 64bit machine with a 32bit python version (see log bellow) with pip or with setup.py results in only the 64bit bootloader to be present. Thus, executing pyinstaller on a simple helloWorld.py (one liner) results in following error:

```
88 INFO: PyInstaller: 3.5+498e6ee05
88 INFO: Python: 3.7.4
88 INFO: Platform: Windows-10-10.0.17134-SP0
---
4772 INFO: Bootloader C:\Users\xxxxxxx\AppData\Local\Programs\Python\Python37-32\lib\site-packages\pyinstaller-3.5+498e6ee05-py3.7.egg\PyInstaller\bootloader\Windows-32bit\run.exe
4772 INFO: checking EXE
4775 INFO: Building because manifest changed
4775 INFO: Building EXE from EXE-00.toc

Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>
```

`Python37-32\Lib\site-packages\PyInstaller\bootloader\Windows-64bit `contains 4 files :

- run.exe 
- run_d.exe 
- runw.exe 
- runw_d.exe

`Python37-32\Lib\site-packages\PyInstaller\bootloader\Windows-32bit` only one: 

- runw_d.exe

**Bootloader shall be built according to python version (32/64) and not according to system version (32/64).**

**Comment by The-Compiler** [comment]
Works fine for me FWIW.

**Comment by atsju** [comment]
> Works fine for me FWIW.

Strange because I reproduced on a different computer than mine. But same setup win10 64bits.
Have you installed the 32bit version on Python ?

**Comment by The-Compiler** [comment]
Yep, no issues with a 32bit Python 3.7.4 on a 64bit Windows 10.

**Comment by piranhaphish** [comment]
I'm having the same issue on Windows 10 (64-bit) with Python 3.7.3 (32-bit) and PyInstaller 3.5 . I only have `runw_d.exe` in ...\bootloader\Windows-32bit and missing the others that do appear in the Windows-64bit folder. I installed via pipenv.

Of course, specifying the `-w` (windowed) and `-d bootloader` options allowed the build to succeed using the runw_d.exe bootloader, but I can't imagine this is an intended limitation. Are you using those options by chance, @The-Compiler?

**Comment by The-Compiler** [comment]
I do use `console=False` but also `debug=False`. I do have `run.exe`, `run_d.exe`, `runw.exe` and `runw_d.exe` in `.../Lib/site-packages/PyInstaller/bootloader/Windows-32bit`.

The [PyPI download](https://pypi.org/project/PyInstaller/#files) contains all of those in `./PyInstaller/bootloader/Windows-32bit/` so I have no idea why you'd be missing those files.

**Comment by bjones1** [comment]
As @The-Compiler says, the files are there in PyPI. Closing as a non-Pyinstaller issue.

**Comment by piranhaphish** [comment]
Okay, I think I might have identified the problem, and it's anti-virus.

Since the files were missing, I tried copying them from a downloaded tarball of PyInstaller 3.5. After placing them in the appropriate folder, all but runw_d.exe were shortly thereafter quarantined (albeit not removed as they appear to have been during pip installation).

I've seen other references to anti-virus causing issues with these files, so I'll take this up with my IT group.

**Comment by kyleleedixon** [comment]
I just wanted to further confirm that the culprit here is anti-virus. I had the same issue and found anti-virus blocking the 32-bit runw.exe.

**Comment by IM4KA7** [comment]
I have the same issue. Even manually copying over runw.exe, in seconds it disappears from the folder! I have had this happen with other files.
