### ISSUE TITLE
RuntimeError: Cannot find the MXNet library

### ISSUE THREAD

**Issue by Santhosh1509** [pyinstaller/pyinstaller#4320]
**Python: 3.7.2
OS: Windows 10
Pyinstaller: 3.5**

I am new to this, saw [PyInstaller Documentation](https://buildmedia.readthedocs.org/media/pdf/pyinstaller/stable/pyinstaller.pdf) might not have understood properly. Please point the right direction.

Created virtual environment using [virtualwrapper](https://virtualenvwrapper.readthedocs.io/en/latest/)

To point the `site-packages` inside the virtualenv for building `myscript.py`
Used this
`pyinstaller --paths C:\Users\Plato\Envs\testenv\Lib\site-packages interface.py`

Ran into this Error when tried to run `myscript.exe` inside `dist/myscript`

> Traceback (most recent call last):
>   File "interface.py", line 3, in <module>
>   File "c:\users\plato\envs\testenv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "pandas\__init__.py", line 23, in <module>
>   File "c:\users\plato\envs\testenv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "pandas\compat\__init__.py", line 32, in <module>
> ModuleNotFoundError: No module named 'distutils'
> [12040] Failed to execute script interface

Saw this [distutils not included with latest virtualenv (16.4.0) #4064](https://github.com/pyinstaller/pyinstaller/issues/4064)
As [suggested](
https://github.com/pyinstaller/pyinstaller/issues/4064#issuecomment-471063543) by [cpbotha](https://github.com/cpbotha) added 

```
# work-around for https://github.com/pyinstaller/pyinstaller/issues/4064
import distutils
if distutils.distutils_path.endswith('__init__.py'):
    distutils.distutils_path = os.path.dirname(distutils.distutils_path)
```
After `block_cipher = None` inside the `myscript.spec`

Ran `pyinstaller --paths C:\Users\Plato\Envs\testenv\Lib\site-packages interface.spec`

Now when I run `myscript.exe` inside `dist/myscript`

Gave me this error

> File "c:\users\plato\envs\testenv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "mxnet\base.py", line 213, in <module>
>   File "mxnet\base.py", line 203, in _load_lib
>   File "mxnet\libinfo.py", line 74, in find_lib_path
> RuntimeError: Cannot find the MXNet library.
> List of candidates:
> D:\testing\dist\myscript\mxnet\libmxnet.dll
> D:\testing\dist\myscript\mxnet\../../lib/libmxnet.dll
> D:\testing\dist\myscript\mxnet\../../build/libmxnet.dll
> D:\testing\dist\myscript\mxnet\../../build\libmxnet.dll
> D:\testing\dist\myscript\mxnet\../../build\Release\libmxnet.dll
> D:\testing\dist\myscript\mxnet\../../windows/x64\Release\libmxnet.dll
> [3536] Failed to execute script interface

Saw this [pyinstaller missing mxnet dll](https://stackoverflow.com/questions/53286509/pyinstaller-missing-mxnet-dll) but didn't help, so copied the entire 
`mxnet` inside `C:\Users\Plato\Envs\testenv\Lib\site-packages\` into `D:\testing\dist\myscript\` now i don't get this error.

How can i change my **spec** file or how can i specify in command during the **build** to grab MXNet from inside `C:\Users\Plato\Envs\testenv\Lib\site-packages\`?

**Comment by ritdubal3011** [comment]
Python 3.5.2
Ubuntu 16.04
PyInstaller 3.4
mxnet 1.4.0


```
File "mxnet/libinfo.py", line 74, in find_lib_path
RuntimeError: Cannot find the MXNet library.
List of candidates:
/home/rit/test/exe/dist/test/libmxnet.so
/home/rit/test/exe/dist/test/libmxnet.so
/home/rit/test/exe/dist/test/mxnet/libmxnet.so
/home/rit/test/exe/dist/test/mxnet/../../lib/libmxnet.so
/home/rit/test/exe/dist/test/mxnet/../../build/libmxnet.so
```

Created executable for my project. While importing mxnet library gave me runtime error and couldn't find libmxnet.so.
libmxnet.so file is manually added though spec file, but after this i have got PyInstallerImportError.


```
File "PyInstaller/loader/pyiboot01_bootstrap.py", line 151, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll '/home/rit/test/exe/dist/test/libmxnet.so'. Most probably this dynlib/dll was not found when the application was frozen.
```

Any luck to resolve this issue.

Thanks

**Comment by ritdubal3011** [comment]
@Santhosh1509 

[MXNet](https://mxnet.incubator.apache.org/api/python/index.html) needs external binaries to be fed when you freeze it. You can use [add-data](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-data-files) flag to add libmxnet files to your executable:

Try this
`pyinstaller -F --add-data="<python_path>/lib/python3.7/site-packages/mxnet/*.so*:./mxnet" script.py `

Worked for me

**Comment by xidianwang412** [comment]
@ritdubal3011
hi, do you solved this problem. i have the same question

**Comment by Santhosh1509** [comment]
@ritdubal3011 
Just small alteration to what you suggested
`pyinstaller -F --add-data="<python_path>/lib/python3.7/site-packages/mxnet/*;./mxnet" script.py`

Worked for me too.

**Comment by ritdubal3011** [comment]
> @ritdubal3011
> hi, do you solved this problem. i have the same question

yes.

**Comment by ritdubal3011** [comment]
> @ritdubal3011
> Just small alteration to what you suggested
> `pyinstaller -F --add-data="<python_path>/lib/python3.7/site-packages/mxnet/*;./mxnet" script.py`
> 
> Worked for me too.

This one is for windows and i'm using linux.
In linux we need to explicitly get all "*.so*" files of library packages while in windows by just writing "../*" that is enough.
