### ISSUE TITLE
Unable to capture video after building successfully 

### ISSUE THREAD

**Issue by Santhosh1509** [pyinstaller/pyinstaller#4323]
**Python: 3.7.2
Pyinstaller: 3.5
OpenCV: 4.1.0.25**

Tried it with Opencv version 3.4.4.19 as well but having the same issue

I get this
`'NoneType' object has no attribute 'shape'`
 in the `cmd` after executing the exe file generated after the build

Found a similar issue 
[OpenCV fails to load video on Windows without any error](https://github.com/pyinstaller/pyinstaller/issues/2950)

As mentioned by them

I gave the `opencv_ffmpeg410_64.dll` path in the

```
binaries=face_models+[('C:\\Users\\Plato\\Envs\\test\\Lib\\site-packages\\cv2\\opencv_ffmpeg410_64.dll','opencv_ffmpeg410_64.dll')]
```
Then again did `pyinstaller --clean myscript.spec`

But issue is not resolved

Would appreciate guidance from anyone to resolve the issue

Similar issues posted but none have a proper solution that works 
https://stackoverflow.com/questions/29811423/opencv-with-standalone-python-executable-py2exe-pyinstaller
https://stackoverflow.com/questions/46050377/unable-to-bundle-opencv-and-pyqt5
https://stackoverflow.com/questions/57107860/unable-to-capture-video-after-creating-exe

**Comment by jainrocky** [comment]
i have this same issue and solved by adding dll path from cmd
`pyinstaller -F --add-data C:\Python3.7.4\Lib\site-packages\cv2\opencv_ffmpeg410_64.dll;. PyRecorder.py`

**Comment by htgoebel** [comment]
Obviosly some .dll is not bundled. Please read the manual how to solve this
