### ISSUE TITLE
soundfile hook has osx/windows specific behaviour

### ISSUE THREAD

**Issue by 3ll3d00d** [pyinstaller/pyinstaller#4325]
hook-soundfile.py was added in 3.5 but it blows up on linux as follows

    9727 INFO: Loading module hook "hook-soundfile.py"...
    Unable to find "/home/matt/.virtualenvs/beqdesigner-entpycF3/lib/python3.7/site-packages/_soundfile_data" when adding binary and data files.

on OSX, it also fails but with a different error

    ValueError: Unknown Mach-O header: 0x20202020 in <_io.BufferedReader 
    name='/Users/travis/build/3ll3d00d/beqdesigner/.venv/lib/python3.7/site-packages/_soundfile_data/COPYING'>

It completes successfully on Windows

The problem is that pysoundfile packages libsndfile on Windows and OSX (as per https://pysoundfile.readthedocs.io/en/0.9.0/#installation) but relies on a system package on Linux so the mentioned directory (`_soundfile_data`) will not exist on Linux. On OSX only a certain file is required (`_soundfile_data/libsndfile.dylib`)

Minimal test case can be found at https://github.com/3ll3d00d/pyinstaller-pysoundfile-bug

**Comment by Christilut** [comment]
I had the same OSX error and solved it with adding my own soundfile hook that adds the files to `datas` instead of `binaries` so that the COPYING file isn't interpreted as a binary. The hook overrides the default soundfile hook.

```
import os
from PyInstaller.utils.hooks import get_package_paths

# get path of soundfile
sfp = get_package_paths('soundfile')

# add the binaries
bins = os.path.join(sfp[0], "_soundfile_data")
datas = [(bins, "_soundfile_data")]
binaries = []
```

**Comment by Overdrivr** [comment]
@Christilut How can you override a hook, I thought this was not possible at the time ? (see https://github.com/pyinstaller/pyinstaller/issues/1835)

@htgoebel Thanks a lot for fixing this issue, has this been released yet ?

**Comment by Christilut** [comment]
I think I ended up removing the hook and going with this in my spec file:
```
             datas=[
    ('../COPYRIGHT', '.'),
],
```

**Comment by Overdrivr** [comment]
@Christilut That means removing the hook manually from pyinstaller install folder ? In this case, this solution won't work in a CI environment.
