### ISSUE TITLE
AttributeError: type object 'neuralcoref.neuralcoref.array' has no attribute '__reduce_cython__'

### ISSUE THREAD

**Issue by ameyn21** [pyinstaller/pyinstaller#4329]
pyinstaller version: PyInstaller-3.5
OS: Windows10
python version 3.6.7
Cython 0.27.3
spacy 2.1.0. 
NeuralCoref 4.0

I am using pyinstaller to package a working code. I get no errors or warnings when running pyinstaller but when trying to execute the resulting .exe file I get the following error:

![l](https://user-images.githubusercontent.com/8626077/61708770-355e7700-ad6b-11e9-9a37-276763acd9e3.png)

Also tried with the development version of Pyinstaller but no luck.

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). Esp. please provide a *minimal* example to reproduce the error.

Esp. don't use images as these are ahrd to read, can not be quoted nor comments.

**Comment by ameyn21** [comment]
A minimal version of my code,
```
def ApplyCorefResolutionToPreProcessedMail(text, nlp):
    # load NeuralCoref and add it to the pipe of SpaCy's model
    coref = neuralcoref.NeuralCoref(nlp.vocab) 
    nlp.add_pipe(coref, name='neuralcoref')
    doc = nlp(text)
    corefresolvedmail = doc._.coref_resolved
    return corefresolvedmail
```

I have used this function in my code and the application works fine. 
But the executable created by Pyinstaller throws an error when executed.
The error is,

    

> File "site-packages\neuralcoref\__init__.py", line 14, in <module>
>     File "stringsource", line 105, in init neuralcoref.neuralcoref
>     AttributeError: type object 'neuralcoref.neuralcoref.array' has no attribute '__reduce_cython__

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please inspect the code of "site-packages\neuralcoref\__init__.py" to learn what is going on there. maybe the codes tried to search the file-system for some files.

 Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by htgoebel** [comment]
Stale since long, closing.
