### ISSUE TITLE
PySide2 QtWebEngine missing files

### ISSUE THREAD

**Issue by steveway** [pyinstaller/pyinstaller#4331]
When packaged with Pyinstaller importing QtWebEngine fails.
The hook for this does not fetch the needed files.
If you manually copy these files from PySide2 to the directory where your generated .exe is then it will work:
- QtWebEngineProcess.exe

This folder is in the translations folder of PySide2:
- qtwebengine_locales

These files are in the resources folder of PySide2:
- icudtl.dat
- qtwebengine_devtools_resources.pak
- qtwebengine_resources.pak
- qtwebengine_resources_100p.pak
- qtwebengine_resources_200p.pak

I've also created a modified version of the hook that copies the needed files:
https://github.com/steveway/papagayo-ng/blob/master/hooks/hook-PySide2.QtWebEngineWidgets.py
That hook works if you create a one dir version of your project but fails on the one file version.
If used with the one file version it says 
> Could not find QtWebEngineProcess.exe

I'm using Pyinstaller 3.5 with Python 3.7.2 on Windows 10

It should be easy to reproduce, likely a script that only tries to `import PySide2.QtWebEngineWidgets` will already fail.

The existing hook likely needs to be changed, possibly in the direction I have already with my costum hook.

**Comment by bjones1** [comment]
Thanks for taking a look. I'd like to keep this hook similar to the (working) PyQt5 hook at https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py. Would you be available to adapt this code to PySide2?

**Comment by tangm** [comment]
I ran into this as well, but found I had to override a runtime hook explicitly to make it work on macos (https://github.com/tangm/pyinstaller-pyside2webview-sample/blob/master/main.py#L9). The layout for the `PySide2`. I also used a custom hook, but started from the newer PyQt5 hook (https://github.com/tangm/pyinstaller-pyside2webview-sample/blob/master/hooks/hook-PySide2.QtWebEngineWidgets.py). 

I'm not sure if PyQt5 has the same issue, but I found that the Pyside2 module distribution has significantly different layouts between windows and mac/linux, so some ugly dir hackery was required :(

**Comment by steveway** [comment]
Hi, I was going to look into adapting the PyQt5 version as recommended today and with the hook from tangm here it seems to work (on Windows 10 at least):
https://github.com/tangm/pyinstaller-pyside2webview-sample/blob/master/hooks/hook-PySide2.QtWebEngineWidgets.py
So I'd recommend integrating that if it also works for macOs and Linux.
Thank you @tangm !

**Comment by tangm** [comment]
Glad it worked for you @steveway ! @bjones1 I've raised https://github.com/pyinstaller/pyinstaller/pull/4377 to update the hooks, but will probably need to lean heavily on your expertise with Qt and the codebase to get it in shape :/
