### ISSUE TITLE
from PyQt5.Qsci import * not supported by PyInstaller 3.4

### ISSUE THREAD

**Issue by santosh1432007** [pyinstaller/pyinstaller#4336]
Hello everyone,

I have installed PyInstaller 3.4 and PyQt5 5.13.0 in virtual environment. I wonder why PyInstaller is not able to support Scintilla . Just a line from PyQt5.Qsci import * in python. The created execuatble doesn't support the script. Without that line it works fine. I want to create an executable for QSciScintilla and support for customelexer. Please let me know, how can I fix. Thanks a lot in advance.

**Comment by santosh1432007** [comment]
I also tried with PyInstaller 3.5 but gives the same error. The executable can't execute. Pop-ups Dialog Box Fatal Error Detected with message Failed to execute script interface. With just a line in python with from PyQt5.Qsci import *. I don't know how to fix it. Please let me know. Thanks a lot in advance.

**Comment by santosh1432007** [comment]
When I tried with command without windowed, I found the following error:
ImportError: No module named 'PyQt5.Qsci'
[12724] Failed to execute script Interface

**Comment by bjones1** [comment]
QScintilla isn't supported. Closing.
