### ISSUE TITLE
ImportError: No module named 'PyQt5.Qsci' [1016] Failed to execute script Interface

### ISSUE THREAD

**Issue by santosh1432007** [pyinstaller/pyinstaller#4339]
I followed updating the PyInstaller  4.0.dev0+ffb1ff369 tried hidden imports as well. It couldn't recognise QsciScintilla. I don't know how to fix it. Here is the error I am getting after the execuatble file is run without windowed mode:

**PyInstaller\loader\pyimod03_importers.py", line 621, in exec_module
    exec(bytecode, module.__dict__)
  File "Window.py", line 10, in <module>
    from PyQt5.Qsci import QsciScintilla
ImportError: No module named 'PyQt5.Qsci'
[1016] Failed to execute script Interface**

Please help me fix this. I tried hidden imports and exclude as well. Didn't work. 

Thanks a lot in advance.

**Comment by santosh1432007** [comment]
@bjones1 Hello Bryan. Thanks a lot for the great work you are doing with PyInstaller. I have a problem. I followed the tutorial and the guide to create executable for Python. I am using Python 3.5, PyQt5 and PyInstaller 4. PyInstaller is not able to build executable properly. There is an error:
from PyQt5.Qsci import QsciScintilla
ImportError: No module named 'PyQt5.Qsci'
[1016] Failed to execute script Interface.

I tried using hidenimport=PyQt5.Qsc as well and it didn't help. When it building the script, I found that
796243 INFO: Analyzing hidden import 'PyQt5.Qsci'
796280 ERROR: Hidden import 'PyQt5.Qsci' not found.
Could you please tell me how to bypass this problem and build the executable for windows.
PyIntaller works fine without the PyQt5.Qsci import and it is working. I need to fix this issue. I tried a lot, couldn't find a way to solve it.
Thanks a lot.

Best Regards
Santosh

**Comment by bjones1** [comment]
Sorry, PyInstaller doesn't support QScintilla (and neither do I). You're on your own. Read the manual!
