### ISSUE TITLE
Can't bundle using pyinstaller because of a relative import issue.

### ISSUE THREAD

**Issue by ozeno** [pyinstaller/pyinstaller#4340]
Currently, when I try to use pyinstaller to bundle a project which has a "statsmodels" dependency I get an error about "from ._version import get_versions" in "\_\_init\_\_.py" because of the other import statement in api.py "from .\_\_init\_\_ import test", pyinstaller adds two entries to it's Analysis.toc file as below. And because of this duplication relative ._version import in \_\_init\_\_.py tries to import from "statsmodels.\_\_init\_\_._version" instead of "statsmodels._version".

Entries from Analysis.toc file:
```
('statsmodels.__init__',
   'c:\\program files\\python37\\lib\\site-packages\\statsmodels\\__init__.py',
('statsmodels',
   'c:\\program files\\python37\\lib\\site-packages\\statsmodels\\__init__.py',
```

Either refactoring the test function out of \_\_init\_\_.py or turning ._version relative import into an absolute import like so "statsmodels._version" seem to solve the issue. Can you please address this relative import issue. And is there a workaround that I can benefit from in my .spec file for the time being.

**Comment by htgoebel** [comment]
> "from .__init__ import test"

This is invalid Python.
