### ISSUE TITLE
QWebEngineView still not working on OS X

### ISSUE THREAD

**Issue by 3rdcycle** [pyinstaller/pyinstaller#4341]
I was hopeful when I read that pyinstaller 3.5 would fix the QWebEngine issues on OS X. However this still fails for me with the old `Could not find QtWebEngineProcess` error.

To test this, I modified `pyinstaller/tests/functional/scripts/pyi_lib_PyQt4-QtWebKit` to use `QWebEngineView` instead of `QWebView`:

```python
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView
from PyQt5.QtCore import QTimer

app = QApplication([])
view = QWebEngineView()
view.show()
# Run the main loop, displaying the WebKit widget.
app.exec_()
```

I built the app on OS X with `pyinstaller --windowed --onefile test.py` and got the error above. I'm on PyInstaller 3.5 in a venv with Python 3.7.3 and PyQt 5.13.0 (running on macOS Mojave 10.14.6 fwiw)

**Comment by bjones1** [comment]
Onefile on Mac doesn't work. You must use onedir for QWebEngineView.

**Comment by 3rdcycle** [comment]
Is this documented somewhere? It doesn't seem to make a difference.

```bash
(venv) ➜  pyinstaller --windowed --onedir test.py
...
(venv) ➜  cd dist
(venv) ➜  test/test
Could not find QtWebEngineProcess
[1]    34890 abort      test/test
(venv) ➜  test.app/Contents/MacOS/test
Qt WebEngine ICU data not found at . Trying parent directory...
Qt WebEngine ICU data not found at /[...]/dist/test.app/Contents/MacOS/PyQt5/Qt. Trying application directory...
Installed Qt WebEngine locales directory not found at location /qtwebengine_locales. Trying application directory...
Qt WebEngine resources not found at . Trying parent directory...
Qt WebEngine resources not found at /[...]/dist/test.app/Contents/MacOS/PyQt5/Qt. Trying application directory...
```

**Comment by 3rdcycle** [comment]
Never mind, double clicking the bundle seems to work. Maybe this should be documented or the hook could output INFO messages with usage instructions.

**Comment by bjones1** [comment]
PRs / documentation improvements welcome! Please suggest an edit!

**Comment by xzhacker123** [comment]
> Never mind, double clicking the bundle seems to work. Maybe this should be documented or the hook could output INFO messages with usage instructions.

hi,What does "bundle" mean? 
I also encountered the same problem.
