### ISSUE TITLE
Binaries created using 3.5 flagged as trojan

### ISSUE THREAD

**Issue by Alrighttt** [pyinstaller/pyinstaller#4343]
Hello, I realize this is very likely a false positive, but I felt the need to share this in the slight chance it's not. I've read similar git issues, but I've not seen someone report this in particular. 

Here are 3 virustotal results for the same python file compiled using `pyinstaller --onefile` on Windows 10 

```shell 
#!/usr/bin/env python3
print('test')
```

[dev](https://www.virustotal.com/gui/file/204c445bfaf46d74fac1e81327b77b764de19397c39d5de178481320d932619e) (pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip)
 
[3.5](https://www.virustotal.com/gui/file/fb5d2e623edf33af6df9ad76f4f7c6dc25b06d297b19f7f37311610e26961196) (pip install pyinstaller)
 
[3.4](https://www.virustotal.com/gui/file/f7ee8dc22ff087e758dd2c7f099531caefb170a1e358a5c1f913ea31c8549806) (pip install PyInstaller==3.4)

I believe it's unrelated to the AV scan(as it also happens on 3.4), but I'm also looking for information on why these binaries are creating then running a binary at `C:\Users\<USER>\Downloads\<NAME>.exe `. It seems to be a different file name each time. So far I've seen `invoice.exe`, `sample.exe`, `factura.exe` and `important_document.exe`. Couldn't find any information on this in the docs or the code.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by Alrighttt** [comment]
Could you please give me information on this `invoice.exe`, `sample.exe`, `factura.exe` and `important_document.exe` thing?

**Comment by EchterAgo** [comment]
I've also seen this in 2 binaries we built with PyInstaller 3.4. I'm actually quite sure those are not malicious, our whole build is reproducible from source and we rebuild the PyInstaller bootloader. This seems to be an issue with the VirusTotal sandbox. I've done local tests on real machines and virtual machines, tracing filesystem operations and I saw no indication that these files actually get created / executed.

**Comment by EchterAgo** [comment]
From the full log on VT (top right) it looks like the uploaded exe file itself is what gets saved as `important_document.exe` and executed.

**Comment by EchterAgo** [comment]
This [does not just affect PyInstaller users](http://www.vbforums.com/showthread.php?876741-VB6-testing-in-virustotal-the-new-quot-Behaviour-quot-tab&p=5403357#post5403357). Scanning the binary in [OPSWAT MetaDefender](https://metadefender.opswat.com) Dynamic Analysis also shows no such file access. I'm confident that the generated binaries are clean.

**Comment by htgoebel** [comment]
Locking the issue as this is not a PyInstaller issue.
