### ISSUE TITLE
Question about certifi runtime hook changing environment

### ISSUE THREAD

**Issue by Hanaasagi** [pyinstaller/pyinstaller#4344]
Hello, I have a question about the `certifi` runtime hook. Recently I bump pyinstaller to 3.5. I found a strange behavior in my code. I create a process to prepare environment, do something like creating a self signed certificate, then the process exit and start another process. It will using `requests` to get some data.

I create a little case here.

```Python
import os
import requests
from OpenSSL import crypto
from socket import gethostname

CERT_FILE = os.getenv("SSL_CERT_FILE", "./test.crt")
KEY_FILE = os.getenv("SSL_PKEY_FILE", "./test.key")


def create_self_signed_cert():
    k = crypto.PKey()
    k.generate_key(crypto.TYPE_RSA, 1024)

    cert = crypto.X509()
    cert.get_subject().C = "UK"
    cert.get_subject().ST = "London"
    cert.get_subject().L = "London"
    cert.get_subject().O = "Dummy Company Ltd"
    cert.get_subject().OU = "Dummy Company Ltd"
    cert.get_subject().CN = gethostname()
    cert.set_serial_number(1000)
    cert.gmtime_adj_notBefore(0)
    cert.gmtime_adj_notAfter(10 * 365 * 24 * 60 * 60)
    cert.set_issuer(cert.get_subject())
    cert.set_pubkey(k)
    cert.sign(k, "sha256")

    with open(CERT_FILE, "wb") as f:
        f.write(crypto.dump_certificate(crypto.FILETYPE_PEM, cert))
    with open(KEY_FILE, "wb") as f:
        f.write(crypto.dump_privatekey(crypto.FILETYPE_PEM, k))


create_self_signed_cert()
resp = requests.get("https://httpbin.org/get")
print(resp.status_code)
```

Unfortunately, I used the `SSL_CERT_FILE` environment variable. After pyinstaller bundle, the new runtime hook will change `SSL_CERT_FILE`

https://github.com/pyinstaller/pyinstaller/blob/d37b36a34ad332a4c6c5b04e255660f19f7df1a8/PyInstaller/loader/rthooks/pyi_rth_certifi.py#L15-L16

So, I overwrite the `certifi`'s cert path accidentally. It causes request certificate verify failed. I known change the env name will work. But is it a good idea to modify user's env?

Thanks a lot.

**Comment by htgoebel** [comment]
The run-time hook change the env variable only if  `ssl.get_default_verify_paths().cafile is None`.
So you can either ensure the file exists (check the docs for `ssl.get_default_verify_paths` how to, seem like setting some env-variables is enough) of re-set `SSL_CERT_FILE` near the top of your program.

I you found a solution, I suggest you to put a recipe into the wiki. Thanks.

**Comment by Hanaasagi** [comment]
The GitHub wiki? https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OpenSSL-Certificate

**Comment by htgoebel** [comment]
If this fits. I'm not following all changes in the wiki

**Comment by Hanaasagi** [comment]
Update.
