### ISSUE TITLE
[Pyinstaller Slow Startup Update]

### ISSUE THREAD

**Issue by vinayak618** [pyinstaller/pyinstaller#4348]
Any Updates on improving the slow startup of pyinstaller application, apart from disabling the anti virus of the system.
In the production environment that is not a ideal situation to run the application by disabling the anti virus.

@bjones1 
@codewarrior0 
@ctismer 
@htgoebel 
@matysek 
@rasky 

Any help would be much appreciated.
Thank you.

**Comment by htgoebel** [comment]
First of all you should not use `--onefile` as this requires unpacking on every startup.

If you have further idea how to speed this up, please share and consider funding the development, See https://www.pyinstaller.org/funding.html
