### ISSUE TITLE
can't use pyinstaller  with python3.6 in ubantu

### ISSUE THREAD

**Issue by Adhders** [pyinstaller/pyinstaller#4349]
I have installed the pyinstaller by 'pip install pyinstaller'  successfully , but when I input pyinstaller
there is  "-bash: /usr/local/bin/pyinstaller: No such file or directory"

anyone can help me, plenty thanks to you!

**Comment by Adhders** [comment]
when I use pip2 install pyinstaller ,there will no error .

**Comment by htgoebel** [comment]
Please check your installation and ensure you installed PyInstaller für the correct version of Python. virtual envs are recommended. this is not a PyInstaller issue.
