### ISSUE TITLE
 Error loading Python lib '/tmp/_MEIDkWNne/libpython3.6m.so'

### ISSUE THREAD

**Issue by Adhders** [pyinstaller/pyinstaller#4351]
dlopen: /tmp/_MEIDkWNne/libpython3.6m.so: cannot open shared object file: No such file or directory

**Comment by IlyasAzeem** [comment]
Hey @Adhders,
You have closed this issue and I have the same problem. Could you please let me know what is the solution to this problem?

**Comment by zsc1220** [comment]
I have also encountered this problem. Has anyone solved it? Thank you very much

**Comment by zsc1220** [comment]
Hi @IlyasAzeem 
Have you solved the problem,I have the same problem. Could you please let me know how to solve this problem?

**Comment by owenljn** [comment]
@IlyasAzeem @zsc1220 I encountered this issue, so I did a search in the folder and find libpython3.6m.so.1.0, then I renamed it to libpython3.6m and the program runs

**Comment by jxltom** [comment]
Fixed in https://github.com/pyinstaller/pyinstaller/commit/0c3112a1d3e541c017dc860de825e12b2f5d13c0

Refer to https://github.com/pyinstaller/pyinstaller/issues/4674
