### ISSUE TITLE
Having trouble getting pyinstaller error when importing DBSCAN from sklearn.cluster

### ISSUE THREAD

**Issue by MuhammadKamal1996** [pyinstaller/pyinstaller#4353]
I've been making a GUI application using PyQt5 and I'm trying to make it into a standalone application. The most common way I've seen people try to do this is by using pyinstaller. The import statement that has been causing issues for me is "from sklearn.cluster import DBSCAN". The reason I think its this line causing the issue is because when I the application from the command prompt it tells me that the error is happening on that line. Also when I comment the line out and try making my python file into an application it actually runs. I'm not sure what is causing the issue so I'll try including as much information as possible including my attempts at trying to resolve the issue. 

**Output when running pyinstaller on file from anaconda powershell prompt**

[Anaconda Powershell Output 1][1]

[Anaconda Powershell Output 2][2]

[Anaconda Powershell Output 3][3]

[Anaconda Powershell Output 4][4]

[Anaconda Powershell Output 5][5]

**sklearn Folder within dist contents**

[sklearn folder][6]

[Cluster folder contents within sklearn][7]

**Command prompt error when running application**

[Command Prompt Error 1][8]

[Command Prompt Error 2][9]

[Command Prompt Error 3][10]

**Attempts at trying to resolve the issue**

Attempt 1: [Stackoverflow answer 1][11]

I tried following the advice of chris and made the hook files with the code that he said to add. When I tried running pyinstaller it lead to the same error and the one I pasted in the command prompt. 

Attempt 2: [Data science blogpost answer][12]

I followed the instructions within the scikit-learn section. Unfortunately it lead to the same error as the one in the command prompt. 

Attempt 3: [Stackover answer 2][13] 

Tried following Vaibhav answer but that lead to the same error in the command prompt. 

**My hook files**

hook-scipy

    import os
    import glob
    from PyInstaller.utils.hooks import get_module_file_attribute
    from PyInstaller.compat import is_win

    binaries = []

    # package the DLL bundle that official scipy wheels for Windows ship

    if is_win:
        dll_glob = os.path.join(os.path.dirname(
            get_module_file_attribute('scipy')), 'extra-dll', "*.dll")
        if glob.glob(dll_glob):
            binaries.append((dll_glob, "."))

    # collect library-wide utility extension modules

    hiddenimports = ['scipy._lib.%s' % m for m in [
    'messagestream', "_ccallback_c", "_fpumode"]]

hook-sklearn.metrics.cluster

    from PyInstaller.utils.hooks import collect_data_files

    hiddenimports = ['sklearn.utils.sparsetools._graph_validation',
                 'sklearn.utils.sparsetools._graph_tools',
                 'sklearn.utils.lgamma',
                 'sklearn.utils.weight_vector',
		 'sklearn.utils.fixes',
     		 'sklearn.utils.extmath',
     		 'sklearn.metrics.ranking',
     		 'sklearn.neighbors',
     		 'sklearn.neighbors.typedefs',
     		 'sklearn.neighbors.quad_tree']

    datas = collect_data_files('sklearn')

hook-sklearn

    from PyInstaller.utils.hooks import collect_submodules
    hiddenimports = collect_submodules('sklearn')

hook-sklearn.tree

    hiddenimports = ['sklearn.tree._utils']

Here are the hook files that I have at the moment. They are saved the in the following location:

C:\Users\Admin\Miniconda3\pkgs\pyinstaller-3.4-py37h2a8f88b_1\Lib\site-packages\PyInstaller\hooks

I've been stuck on this for quite sometime. I would really appreciate if someone can tell me how to resolve this error. Let me know if you need anymore information about the issue I've been dealing with. 

  [1]: https://i.stack.imgur.com/o65IK.png
  [2]: https://i.stack.imgur.com/5ucnq.png
  [3]: https://i.stack.imgur.com/9qRdb.png
  [4]: https://i.stack.imgur.com/8Rg7M.png
  [5]: https://i.stack.imgur.com/Eqf5p.png
  [6]: https://i.stack.imgur.com/Khr1d.png
  [7]: https://i.stack.imgur.com/VvL1G.png
  [8]: https://i.stack.imgur.com/p4iMw.png
  [9]: https://i.stack.imgur.com/yBJTi.png
  [10]: https://i.stack.imgur.com/E4G1U.png
  [11]: https://stackoverflow.com/questions/49559770/how-do-you-resolve-hidden-imports-not-found-warnings-in-pyinstaller-for-scipy
  [12]: http://datasciencefortress.blogspot.com/2018/02/creating-executables-for-machine.html
  [13]: https://stackoverflow.com/questions/20602721/pyinstaller-a-module-is-not-included-into-onefile-but-works-fine-with-oned

**Comment by wedesoft** [comment]
I had this problem and the error message about 'DBSCAN' turned out to be misleading.
I managed to fix the problem by downgrading pytest (from 5.0.1 to 3.3.1), pluggy (from 0.12.0 to 0.6.0), and attrs (from 19.1.0 to 17.3.0).

**Comment by bwoodsend** [comment]
That error should be fixed automatically by #5866.
