### ISSUE TITLE
[question] How to change the application displayName on windows10 Notication area

### ISSUE THREAD

**Issue by QingMings** [pyinstaller/pyinstaller#4355]
There are no mistakes here. There are some questions.

I'm try to  write a system tray app using `PyQt5` . Send some notice to Win10 Notication Area ,I use `PyInstaller` to package my program into 'exe' files.
It's work file. But I noticed that the notification from my program display as `downloader.exe`.
Other programs do not have suffixes. Maybe alias? the `exe` file name is different from Application DisplayName.
![Notication Area screenshot](https://i.imgur.com/1HFu1kg.png)

I looked up some instructions for PyInsteller, searched on Google, and tried to use pyQT5 to set the Application name.  Couldn't solve my problem.

I`m try to set ApplicationName or DisplayName ,but it not work!
```python
    app = QtWidgets.QApplication(sys.argv)
    """
     set application name 
    """
    app.setApplicationName("病例库下载器")
    app.setApplicationDisplayName("病例库下载器")
    app.setDesktopFileName("病例库下载器")
    w = QtWidgets.QWidget()
    tray_icon = SystemTrayIcon(QtGui.QIcon(":/icon.png"), w)
    tray_icon.show()
    tray_icon.showMessage('病例库下载器', '欢迎使用病例库下载器')

```

**Comment by htgoebel** [comment]
Please read the Qt documentation. This is not a PyInstaller issue.
