### ISSUE TITLE
Multiple Tcl warnings

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4356]
I'm getting multiple WARNINGS when building my project on mac:
```
20:05:23  137731 WARNING: failed to copy flags of /System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources/Scripts/msgs/hi.msg
20:05:23  137740 WARNING: failed to copy flags of /System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources/Scripts/encoding/iso2022.enc
20:05:23  137742 WARNING: failed to copy flags of /System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources/Scripts/encoding/cp737.enc
20:05:23  137769 WARNING: failed to copy flags of /System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources/Scripts/msgs/gl_es.msg
20:05:23  137782 WARNING: failed to copy flags of /System/Library/Frameworks/Tcl.framework/Versions/8.5/Resources/Scripts/msgs/es_py.msg
```

As far as I know, this warning is related to `Tkinter` but the issue is that I'm not using it in my project, my application is a non-GUI app.
It might be imported by one of my 3rd-party dependencies but I cannot find it.

How can I discover the source of this?

**Comment by Legorooj** [comment]
This is not a PyInstaller issue; if it's causing you trouble, we can't help. (Though maybe see if `--exclude-module=tkinter` helps - if it doesn't crash the app, then none of your dependencies use it)
