### ISSUE TITLE
[Pyinstaller Packaging --onedir]

### ISSUE THREAD

**Issue by vinayak618** [pyinstaller/pyinstaller#4359]
Hi.
I was searched a lot about the issue of packaging --onedir application.
Speed up is achieved by using onedir instead of onefile.
But how do i package it well to distribute the app to the customer?

@bjones1
@codewarrior0
@ctismer
@htgoebel
@matysek
@rasky

Any help would be much appreciated.
Thank you.

**Comment by htgoebel** [comment]
Either distriubte a zip-file or use e.g. Null-Soft Installer.
