### ISSUE TITLE
Bug: Importing .pyd modules after freezing the application.

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#436]
**Original date**: 2011/10/13
**Original reporter**: *esttecb AND hotmail DOT  COOM *

Hi! After freezing my application with --onefile option, it cant import .pyd modules.
i know I can embed them into my frozen app, but my goal is to have them in separated packages.

It works fine if I change the pyd (cython) files by the original pyc or py files. Otherwise, the modules are not detected (I get the no module named... error).

I tried pyinstaller 1.5.1 and the one in the svn trunk.

Thanks.

**Comment by matysek** [comment]
too old bug report.
