### ISSUE TITLE
is there a way to run pyinstaller flask app with nginx

### ISSUE THREAD

**Issue by lohithn4** [pyinstaller/pyinstaller#4362]
I have a python flask built file which i built with pyinstaller on my linux system successfully by following this [link](https://elc.github.io/posts/executable-flask-pyinstaller)

this is the command

`(venv)$pyinstaller -w -F --add-data "static:static" testapp.py
`
Now i need to run this built app from supervisor in production mode but it always in the development mode.

I can simply run the built file with this command in supervisor conf file 

`command=/home/user/test_app_installer/.testapp `

but it runs with development server and outputs this message.

`WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:8080/ (Press CTRL+C to quit)`

without built file i can make use of source code and virtual-environment and i can from supervisor with this command
`command=/home/user/test_app_installer/venv/uwsgi --ini /home/user/test_app_installer/testapp.ini `
but i have no idea now how i can run the built app with production server.

following is the complete supervisor script which runs app in developer mode.

`[program:TESTAPP]

command=/home/user/test_app_installer/./testapp

directory=/home/user/test_app_installer

autostart=true

autorestart=true

user=user

umprocs=1

redirect_stderr=true

stdout_logfile=/home/user/testapp.log
`

**Comment by htgoebel** [comment]
This is not a pyinstaller issue. You want to learn how to properly set up flask for production.
