### ISSUE TITLE
Saving debug information 

### ISSUE THREAD

**Issue by christina-zhou-96** [pyinstaller/pyinstaller#4367]
This command is not working for me:

$ pyinstaller --log-level=DEBUG cli.py 2> build.txt

My terminal hangs.

I want to make sure my team is able to see debug information (eg. on the level of a Pandas error such as `get_loc value failed`) if they try to open this app and it fails. I am open to other solutions.

This command works fine:

$ pyinstaller --onefile --windowed myscript.py

Running a Windows 10 Educational Version and Python 3.7

**Comment by danyeaw** [comment]
Hi @christina-zhou-96 thanks for submitting the issue. I don't think this is an issue with pyinstaller, I think you may just be using the wrong bash command. If you want to see the debug to a log file and see it on screen you need to run `pyinstaller --log-level=DEBUG cli.py 2>&1 | tee build.txt`.
