### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by Mikami382** [pyinstaller/pyinstaller#4368]
Hi,

I'm working on a project and this is my first time trying out pyinstaller and I have encountered this issue upon opening my compiled program: ImportError: numpy.core.multiarray failed to import

I'm using the following versions:
- Python 3.7.4
- Numpy 1.17.0
- PyInstaller-4.0.dev0+515bf55a4

I am running this in a virtual environment, and I have tried to use hiddenimport for "numpy" and specifically "numpy.core.multiarray", but to no avail. Still same error.

This is the program's console output in Windows Powershell.

> PS D:\Documents\EasyAK\dist\main> .\main.exe
> ImportError: numpy.core.multiarray failed to import
> Traceback (most recent call last):
>   File "main.py", line 5, in <module>
>   File "d:\documents\easyak\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 621, in exec_module
>     exec(bytecode, module.__dict__)
>   File "imagesearch.py", line 1, in <module>
>   File "d:\documents\easyak\venv\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 621, in exec_module
>     exec(bytecode, module.__dict__)
>   File "lib\site-packages\cv2\__init__.py", line 3, in <module>
> ImportError: numpy.core.multiarray failed to import
> [7632] Failed to execute script main
> PS D:\Documents\EasyAK\dist\main>

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by Mikami382** [comment]
Hi, 

Thank you for replying, I have just downgraded numpy to version 1.16.4 and it seems to be working fine without any issues.

I'm sorry, I do not understand what you mean by "not all required files are packages". I have looked over the website you linked, I did try both --onedir and --onefile. And --noupx or set upx=False. They all did not work.

**Comment by atvKumar** [comment]
I recently did numpy and had simmilar issues. Add the module in hidden imports and try again.
e.g -  hiddenimports=['numpy.random.common', 'numpy.random.bounded_integers', 'numpy.random.entropy']

**Comment by htgoebel** [comment]
That's a good start. Now continue debugging by following the other hints. (Or close this issue.)

**Comment by Mikami382** [comment]
@atvKumar It works, thank you.
