### ISSUE TITLE
PyInstaller failing in Alpine linux  Can not find libc.musl-x86_64.so.1 in path ldd (needed by /usr/lib/libpython3.6m.so.1.0)

### ISSUE THREAD

**Issue by Kalanamith** [pyinstaller/pyinstaller#4371]
I am using the following Dockerfile to build an executable for alpine linux

```
FROM alpine:3.7
WORKDIR /app/proj
COPY . /app/proj
RUN apk update && apk add build-base python3 python3-dev --no-cache bash &&  \
    pip3 install --upgrade pip && \
    pip3 install --trusted-host pypi.python.org --no-cache-dir -e. && \
    pip3 install pyinstaller==3.5 && \
    pip3 install PyCrypto && \
    rm -rf tests instance tmp myapp.egg-info Docker && \
    pyinstaller ./myapp/cli.py  --name myapp_binary --exclude-module scripts --exclude-module tests --exclude-module docker --exclude-module build --onefile



EXPOSE 5000 3306
```

This will throw an error saying

```
4136 ERROR: Can not find libc.musl-x86_64.so.1 in path ldd (needed by /usr/lib/libpython3.6m.so.1.0)
```

As a workaround, I have added 
```
    ln -s /lib/libc.musl-x86_64.so.1 ldd && \
    ln -s /lib /lib64 && \
```

After rebuilding image again and when I am trying to execute the file I am getting the following error

```
 ./myapp_binary 
./myapp_binary: line 1: syntax error: unexpected "("

```

**Comment by htgoebel** [comment]
Please provide more context fir the error-message. I can't see where it happens.

The second error is your fault: myapp_binary is not a shell-script.

**Comment by Kalanamith** [comment]
Context for the error message , this is what I can get
```
69 INFO: Analyzing base_library.zip ...
4219 INFO: running Analysis Analysis-00.toc
4226 ERROR: Can not find libc.musl-x86_64.so.1 in path ldd (needed by /usr/lib/libpython3.6m.so.1.0)
4230 INFO: Caching module hooks...

```

**Comment by Hanaasagi** [comment]
Is this like https://github.com/gliderlabs/docker-alpine/issues/48 ?

**Comment by Kalanamith** [comment]
@Hanaasagi  dont what what gliderlabs though the issue persists

**Comment by htgoebel** [comment]
Thanks for providing the context.

Do I understand code right?
```
    ln -s /lib/libc.musl-x86_64.so.1 ldd && \
    ln -s /lib /lib64 && \
```
* You are linking ldd -> /lib/libc.musl-x86_64.so.1
  This means, `ldd` is not part of your installation. I assume you need to install the binutils package. Please see the requirements section in the manual.

* Shure the /lib64 -> /lib link ins required? /lib64 is not used above.

**Comment by wanghaiqing2015** [comment]
use frolvlad/alpine-glibc:glibc-2.29
