### ISSUE TITLE
pyinstaller “Failed to Execute Script”? in windows Task Scheduler

### ISSUE THREAD

**Issue by ebonat** [pyinstaller/pyinstaller#4373]
i got the error: “Failed to Execute Script”? in Task Scheduler in windows 7 and 10. The EXE file run fine from command prompt and from windows explorer. 

the exe file was created as:

1. command prompt
pyinstaller --onedir --name=etl_installer "C:\some_path\src\etl.py" 

2. windows 7 and 10
pyinstaller --onedir --name=etl_installer --windowed "C:\some_path\src\etl.py" 

used:

python 3.6.7
pyinstaller 4.0.dev
windows 7 and 10

is there any specific requirement(s) to run a pyinstaller created EXE file in windows task scheduler?

thank you for your help!

**Comment by ebonat** [comment]
hi all,

any ideas or work around how to fix this issue?

thank you for your help!

**Comment by ebonat** [comment]
hi all,

any ideas or work around how to fix this issue?

thank you for your help!

**Comment by 846948768** [comment]
[Failed to execute script. #4317](https://github.com/pyinstaller/pyinstaller/issues/4317)
[How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

Maybe you can try to pass the option --debug and --console to pyinstaller, then debug it.

**Comment by ebonat** [comment]
good point, i'll do that!

thank you for your help!
