### ISSUE TITLE
Repack Exe

### ISSUE THREAD

**Issue by applke** [pyinstaller/pyinstaller#4376]
Hi, i want to unpack exe make some changes and pack it back. 
I found repo **[python-exe-unpacker](https://github.com/countercept/python-exe-unpacker)** and sucessfuly unpacked exe. But how i can pack back? I waste a lot of time, but no success!

In upacked archive i found .pyz archive with py code. I need just modify entry.py of the exe. Who can help me?

**Comment by htgoebel** [comment]
This is not our business. Ask the author of the other tool.
