### ISSUE TITLE
Failed execute an (*.exe) based on win32serviceutil.ServiceFramework

### ISSUE THREAD

**Issue by Ayad-Ben-Saliem** [pyinstaller/pyinstaller#4378]
I have a windows service based on (win32serviceutil.ServiceFramework) it works pretty well as Python script, however, when I convert it to *.exe file some functionalities fail to execute.

`debug`/`install`/`remove`/`update `commands executed successfully, but `start `option fails, it prints the following:

`Error starting service: The service did not respond to the start or control request in a timely fashion.`

I hope this fixed as soon as possible.

Thank you.

**Comment by htgoebel** [comment]
> I hope this fixed as soon as possible.

Please provide a solution. We are not your service crew!
