### ISSUE TITLE
When I package script to exe,there is a arg-question.

### ISSUE THREAD

**Issue by VanreaTsingting** [pyinstaller/pyinstaller#4380]
part 0. envr
    win10
    python 3.6.5

part 1. question
    as the bottom code you see，there is a windows-gui program.
    I try this code running in pycharm and It gets ok.
   
    When I package to exe without showing dos-window,it didn't response well.
    open the dos-windows input and it packages: 
        pyinstaller -F -w tarTes.py
    I try clicking the button many times,it didn't open the browser,and responses nothing.

    However,I edit the packaging-script with this:
        pyinstaller -F tarTes.py
    It run well and response corectly.

   May I ask why this situaction happen?

part 2. code
【Python】
##################################################

# readme:run before install PyQT5
# dos scropts:
# pip3 install PyQt5 -i https://pypi.douban.com/simple
# pip3 install PyQt5-tools -i https://pypi.douban.com/simple

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLabel, QPushButton
import sys,os
from threading import *

class TarWidget(QtWidgets.QWidget):

    runTask = None
    def __init__(self, parent=None):
        super().__init__(parent)
        self.initUi()
        self.loadConfig()

    def initUi(self):
        self.setMinimumSize(600, 200)
        self.lb_tip = QtWidgets.QLabel(self)
        self.lb_tip.setGeometry(QtCore.QRect(20, 20, 50, 20))
        self.lb_tip.setText( "Data:")

        self.btn_openBrowser = QPushButton(self)
        self.btn_openBrowser.setGeometry(QtCore.QRect(300, 65, 90, 30))
        self.btn_openBrowser.setText( "open in browser" )

    def loadConfig(self):
        self.btn_openBrowser.clicked.connect( self.openBrowser )

    def openBrowser(self):
        if self.runTask:
            pass
        else:
            try:
                tarConmand = "start www.baidu.com"
                method = lambda :os.popen( tarConmand )
                self.runTask = Thread(target=method)
                self.runTask.start()
            except BaseException as e:
                with open("error.log", 'wb') as file:
                    file.write(e)
                    file.close()
            self.runTask = None

if __name__=="__main__":
    from PyQt5 import QtWidgets, QtGui
    import sys
    app = QtWidgets.QApplication(sys.argv)
    window = TarWidget()
    window.show()
    sys.exit(app.exec_())

##################################################

【Dos bat Script】
##################################################

: pyinstaller -F -w -i FRo.ico tarTes.py
pyinstaller -F -i FRo.ico tarTes.py

##################################################

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). **Follow all the steps described there.** Especially don't use `-F`/`--onefile`, run from a console windows and provide a *minimal* example to reproduce the error.

**Comment by htgoebel** [comment]
Stale since long, closing.
