### ISSUE TITLE
VSVersionInfo argument to EXE instead of a path

### ISSUE THREAD

**Issue by tneukom-alstom** [pyinstaller/pyinstaller#4381]
In previous versions (3.4) it was possible to pass a VSVersionInfo object as the version argument to EXE. In 3.5 this raises an exception. It seems to be the following code in api.py on line 426 which expects the argument to be a path.

```Python
if self.versrsrc:
	if not os.path.isabs(self.versrsrc):
		# relative version-info path is relative to spec file
		self.versrsrc = os.path.join(
			CONF['specpath'], self.versrsrc)
```

I'm not sure if it was ever intended that passing a VSVersionInfo would work.

**Comment by htgoebel** [comment]
> I'm not sure if it was ever intended that passing a VSVersionInfo would work.

Please use `git blame` (or `blame` on github) to learn about this. Anyway, you are welcome to provide a pull-requests changing thsi behavior to what you need.

**Comment by Chrisg2000** [comment]
The ability to pass a VSVersionInfo was a feature forgotten in the attempt to make paths relative.
In the responsible function in `utils/win32/versioninfo.py` this is explicitly implemented as an option:
```py3
def SetVersion(exenm, versionfile):
    if isinstance(versionfile, VSVersionInfo): #      <- explicit test
        vs = versionfile
    else:
        with codecs.open(versionfile, text_read_mode, 'utf-8') as fp:
            txt = fp.read()
        vs = eval(txt)
```

**Comment by htgoebel** [comment]
@Chrisg2000 Looks like you created a ull-request for you own repository?! Please edit it and provide it to pytinstaller/PyInstaller. Thanks

**Comment by Chrisg2000** [comment]
Good to know that one should not use Github's "One-Button" solution to create a pull request -_-
My fault, now it is correct.
