### ISSUE TITLE
OSError: Could not find a suitable TLS CA certificate

### ISSUE THREAD

**Issue by JJJJShen** [pyinstaller/pyinstaller#4382]
If you have problems to get your application running, please first

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If your problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for GitHub's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.

**Otherwise we will not be willing to help you.**

Please be aware that PyInstaller is a voluntary project. We spent quite some time
writing these guides to make both of our lives easier. Please
understand that we are not willing to spend our spare time to help you if you
are not willing to help on your side. (Sorry for having to said this, but we
are tired of being asked the same questions over and over again.)

**Comment by JJJJShen** [comment]
I have tried according to the method in the Wrong document, but I still have the following error. I did check the path "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI88922\facebook_business\fb_ca_chain_bundle.crt". But there is no "_MEI88922" folder on my computer. There was no problem with using the pyinstaller module to package files before, but after I updated the facebook-business module, I had this problem.
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\ADMINI~1\AppData\Local\Temp\_MEI88922\facebook_business\fb_ca_chain_bundle.crt
[9520] Failed to execute script listcam

**Comment by JJJJShen** [comment]
I have tried according to the method in the Wrong document, but I still have the following error. I did check the path "C:\Users\ADMINI~1\AppData\Local\Temp\_MEI88922\facebook_business\fb_ca_chain_bundle.crt". But there is no "_MEI88922" folder on my computer. There was no problem with using the pyinstaller module to package files before, but after I updated the facebook-business module, I had this problem.

**Comment by JJJJShen** [comment]
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: C:\Users\ADMINI1\AppData\Local\Temp_MEI88922\facebook_business\fb_ca_chain_bundle.crt
[9520] Failed to execute script listcam

**Comment by yishangfei** [comment]
hi, How did you solve this problem？

**Comment by m-rashwan** [comment]
@yishangfei  you can use data_added section in spec file to copy fb_ca_chain_bundle.crt from [facebook_business] located in $python_root\Lib\site-packages\site_packages to correct path {the path you got in the error}.

**Comment by bwoodsend** [comment]
Adding `--collect-data=facebook_business` to your PyInstaller command should do it.
