### ISSUE TITLE
use modulegraph library for dependency analysis

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#439]
**Original date**: 2013/03/19

Use [modulegraph](http://pypi.python.org/pypi/modulegraph) for module dependency analysis. Another benefit would be easier maintenance of pyinstaller code.

**Comment by htgoebel** [comment]
Given the problem we have in modulegraph at the moment (see https://github.com/pyinstaller/pyinstaller/issues/1412#issuecomment-131576369), can you remember what have been the reasons for using it?

**Comment by matysek** [comment]
> the reasons for using it?

* for me it was harder to understand the code
* maintainability - I wanted to rather use a library with some documentation
* python3 - modulegraph was already working with Python 3
* graph data representation - better expresses module dependencies, old  code was flat data structure
* old code had many shortcomings or was not suitable for adding new features and long-term improvements

Modulegraph is not perfect but is better than the old code and I'm glad that now more people understands it and how it works.

**Comment by htgoebel** [comment]
Thanks.
