### ISSUE TITLE
The `-onefile` option does not include files in the `datas` spec 

### ISSUE THREAD

**Issue by kakyoism** [pyinstaller/pyinstaller#4390]
Running PyInstaller 3.5 on macOS Mojave, I found that my datas section will be consider only when using `--onedir` (default). The `--onefile` switch simply ignores the `datas` section in my .spec. By "ignoring", I mean I cannot find the data file in the generated app bundle.

Is this by design?

**Comment by kakyoism** [comment]
I'm asking because I prefer using the onefile distribution. The package generated by `--onefile` is a lot smaller than with `--onedir`.

**Comment by michielz** [comment]
I also had a problem using `--onfile`. Pyinstaller failed to grab a python file from the collectables directory. This resulted in the application to crash during startup.

The way I solved this was by adding a line to the spec file, see line in bold. Now the file that is in the collectables directory gets packed.

I have no idea if this is the correct way to solve collecting files during packing. But it works for me.

```

exe = EXE(pyz,
          **Tree('/home/michiel/projects/some_project/collectables'),**
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
```
