### ISSUE TITLE
How to reduce the -onedir app size on macOS?

### ISSUE THREAD

**Issue by kakyoism** [pyinstaller/pyinstaller#4391]
To reduce app size, I know that there is the `--exclude-module` to exclude python packages. But what I need is to exclude whatever libs/binaries that the app code does not refer to. 

The reason why I'm asking is that I noticed that the `--onefile` option generates an app bundle that's three times smaller than the default `--onedir` version. Without digging into why, I'm wondering how I could achieve the small size with `--onedir` because currently `--onefile` breaks my app by ignoring any data file I include with my .spec, not sure if it's a bug itself.

**Comment by atvKumar** [comment]
you can exclude modules, in your spec file this is assuming you have different third party libs installed. Which by the fact most people will recommend you to have venv and only install what you need.

Data files will be copied, there is no bugs. Please read the documentation and have a proper spec file.

Smaller file size in --onedir, don't think is possible, unless you want to try UPX, but i think thats quite broken in MacOS.

**Comment by Legorooj** [comment]
Onedir will be bigger, because the C object libraries (DLL/SO/PYD) aren't compressed. In one file it's all compressed. We can't help with this
