### ISSUE TITLE
ctypes error with PyInstaller

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4395]
I'm trying to use `ctypes` with PyInstaller to use the windows crypto API.
My code works fine when running with python but when compiled with PyInstaller it gives error 87 

```
import ctypes

PROV_RSA_AES = 0x18
CRYPT_VERIFYCONTEXT = 0xF0000000

provider = ctypes.c_void_p()
if 0 == ctypes.windll.advapi32.CryptAcquireContextW(ctypes.byref(provider), 0, 0, PROV_RSA_AES, CRYPT_VERIFYCONTEXT):
    print(ctypes.GetLastError())
```
It is only happening on Python2, on Python3 it seems to work.
I know that Python2 is going to be deprecated soon, I'm in a process to convert it to Python3 but it will take some time and I need it to work ASAP.

Is there anything that I can do to find the source of this?

PyInstaller: 3.5
Python: 2.7.16
Windows: 10

**Comment by htgoebel** [comment]
Please provide a trace back.

**Comment by arossert** [comment]
I don't have a trace, the return value is 87 (ERROR_INVALID_PARAMETER) instead of 0 when running without PyInstaller.
I have found out that when using `None` instead of 0 for the pointers it fixes this specific call but failed on others, is this make any sense?

**Comment by htgoebel** [comment]
This sound like you are passing the wron parameters to your functions - and not a PyInstaller issue. 

Please make you application run unfrozen first.

I'm closing this now.Please reopen if you find this is y PyInstaller issue and able to provide a traceback.
