### ISSUE TITLE
wrong results for pyradiomics

### ISSUE THREAD

**Issue by zhang-qiang-github** [pyinstaller/pyinstaller#4407]
When I run pyradiomics in python, it would calculate 122 values. After pyinstaller, it can only calculate 22 values. No bug, no crush, just wrong results. 

The environment is:
win7
pyinstaller 3.5
pyradiomics 1.2.2

I have updated the tested code in [github](https://github.com/zhang-qiang-github/radiomicsBug) so that you can reappear the bug. I think the reason may be that the pyinstaller missed some files. I have discussed this problem with the developer of pyradiomics, and there are some [details](https://github.com/Radiomics/pyradiomics/issues/523). Any suggestion is helpful.

**Comment by htgoebel** [comment]
Please understand that I'm not going to read through some issue discussion for another project. Please provide all relevant information here.

I assume not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

**Comment by htgoebel** [comment]
Stale since long, closing.
