### ISSUE TITLE
Python library problemas, can't create exe file with Pyinstaller

### ISSUE THREAD

**Issue by uriielfl** [pyinstaller/pyinstaller#4410]
Hi, There! How are you? So, sorry if I'm doing something wrong, this is my first post here.
Well, i'm trying to compile this application, but I having this trouble: 

`Microsoft Windows [versão 10.0.17763.678]
(c) 2018 Microsoft Corporation. Todos os direitos reservados.
 
C:\WINDOWS\system32>cd C:\Users\Pichau\Documents\bsc
 
C:\Users\Pichau\Documents\bsc>pyinstaller NeverPedent.py
742 INFO: PyInstaller: 3.5
742 INFO: Python: 3.7.3
743 INFO: Platform: Windows-10-10.0.17763-SP0
759 INFO: wrote C:\Users\Pichau\Documents\bsc\NeverPedent.spec
775 INFO: UPX is not available.
777 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Pichau\\Documents\\bsc', 'C:\\Users\\Pichau\\Documents\\bsc']
777 INFO: checking Analysis
778 INFO: Building Analysis because Analysis-00.toc is non existent
778 INFO: Initializing module dependency graph...
792 INFO: Initializing module graph hooks...
808 INFO: Analyzing base_library.zip ...
5689 INFO: running Analysis Analysis-00.toc
5754 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\pichau\pycharmprojects\teste\venv\scripts\python.exe
6244 WARNING: lib not found: VERSION.dll dependency of c:\users\pichau\pycharmprojects\teste\venv\scripts\python.exe
7175 INFO: Caching module hooks...
7180 INFO: Analyzing C:\Users\Pichau\Documents\bsc\NeverPedent.py
7452 INFO: Loading module hooks...
7453 INFO: Loading module hook "hook-encodings.py"...
7572 INFO: Loading module hook "hook-pydoc.py"...
7577 INFO: Loading module hook "hook-sqlite3.py"...
7726 INFO: Loading module hook "hook-xml.py"...
8093 INFO: Loading module hook "hook-_tkinter.py"...
8732 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_tkinter.pyd
9539 WARNING: lib not found: tk86t.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_tkinter.pyd
9836 WARNING: lib not found: tcl86t.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_tkinter.pyd
10351 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_tkinter.pyd
10824 INFO: checking Tree
11220 INFO: checking Tree
11321 INFO: Looking for ctypes DLLs
11321 INFO: Analyzing run-time hooks ...
11324 INFO: Including run-time hook 'pyi_rth__tkinter.py'
11347 INFO: Looking for dynamic libraries
11956 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_ssl.pyd
12785 WARNING: lib not found: libssl-1_1.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_ssl.pyd
13224 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_ssl.pyd
13522 WARNING: lib not found: libcrypto-1_1.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_ssl.pyd
15203 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\pyexpat.pyd
16346 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\pyexpat.pyd
17169 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\unicodedata.pyd
18145 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\unicodedata.pyd
18959 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_hashlib.pyd
19834 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_hashlib.pyd
20129 WARNING: lib not found: libcrypto-1_1.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_hashlib.pyd
20832 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\select.pyd
21696 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\select.pyd
22978 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_bz2.pyd
24147 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_bz2.pyd
25030 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_lzma.pyd
26153 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_lzma.pyd
26958 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_socket.pyd
27897 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_socket.pyd
29222 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_sqlite3.pyd
30362 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_sqlite3.pyd
31312 WARNING: lib not found: VCRUNTIME140.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_tkinter.pyd
32158 WARNING: lib not found: tk86t.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_tkinter.pyd
32471 WARNING: lib not found: tcl86t.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_tkinter.pyd
32936 WARNING: lib not found: python37.dll dependency of C:\Users\Pichau\AppData\Local\Programs\Python\Python37\DLLs\_tkinter.pyd
33554 INFO: Looking for eggs
33554 INFO: Python library not in binary dependencies. Doing additional searching...
Traceback (most recent call last):
  File "C:\Users\Pichau\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\Pichau\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Pichau\PycharmProjects\Teste\venv\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\users\pichau\pycharmprojects\teste\venv\lib\site-packages\PyInstaller\__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\pichau\pycharmprojects\teste\venv\lib\site-packages\PyInstaller\__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\pichau\pycharmprojects\teste\venv\lib\site-packages\PyInstaller\building\build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\pichau\pycharmprojects\teste\venv\lib\site-packages\PyInstaller\building\build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "C:\Users\Pichau\Documents\bsc\NeverPedent.spec", line 17, in <module>
    noarchive=False)
  File "c:\users\pichau\pycharmprojects\teste\venv\lib\site-packages\PyInstaller\building\build_main.py", line 243, in __init__
    self.__postinit__()
  File "c:\users\pichau\pycharmprojects\teste\venv\lib\site-packages\PyInstaller\building\datastruct.py", line 158, in __postinit__
    self.assemble()
  File "c:\users\pichau\pycharmprojects\teste\venv\lib\site-packages\PyInstaller\building\build_main.py", line 575, in assemble
    self._check_python_library(self.binaries)
  File "c:\users\pichau\pycharmprojects\teste\venv\lib\site-packages\PyInstaller\building\build_main.py", line 681, in _check_python_library
    raise IOError(msg)
OSError: Python library not found: libpython37.dll, libpython3.7m.dll, libpython3.7.dll, python37.dll, libpython37m.dll
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.
 
* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with `--enable-shared` (or, `--enable-framework` on Darwin)
 
 
C:\Users\Pichau\Documents\bsc>`

I've already tried to search for these dll files, but I couldn't :(
If someone could help me, i'd be too much thankful haha!

**Comment by atvKumar** [comment]
VCRUNTIME140.dll, you need to include in the spec file, for the rest. In windows, either go with Conda or go vannila (direct from python.org) Not sure what is your installation of python. Make sure your python x86/x64 and versions are in check with your Windows OS. Oh and also you might want to git clone the dev branch of pyinstaller as to pip installing it. They have patches for issues.

**Comment by uriielfl** [comment]
> VCRUNTIME140.dll, you need to include in the spec file, for the rest. In windows, either go with Conda or go vannila (direct from python.org) Not sure what is your installation of python. Make sure your python x86/x64 and versions are in check with your Windows OS. Oh and also you might want to git clone the dev branch of pyinstaller as to pip installing it. They have patches for issues.

Sorry, do i need to install the dlls? I'm using pip, could i solve with the same?

**Comment by atvKumar** [comment]
Please read the documentation and include it in spec for pyinstaller to copy over from your windows installation to the exe location.

**Comment by MaxineXiong** [comment]
Hi uriielfl,
I tried the following steps and successfully converted my python file to .exe application (for WINDOWS 10 64-bit:

1) add C:\Users\(username)\AppData\Roaming\Python\Python37\Scripts to user path:

open 'Run' app -> Open 'sysdm.cpl' -> 'Advanced' -> 'Environment Variables' -> Edit 'path' in User Variable

2) copy the .py file (the one holding your python code) to C:\Users\(username)\AppData\Roaming\Python\Python37\Scripts

3) run `python -m pip install pyinstaller` in terminal to install pyinstaller

4. run `.\pyinstaller -w -F (your file name).py` in your terminal to convert python file to .exe

5. Now the .exe tool should already be available in 'C:\Users\(username)\AppData\Roaming\Python\Python37\Scripts\dist' folder

**Comment by htgoebel** [comment]
As the error message clearly says:
> Python library not found: libpython37.dll, libpython3.7m.dll, libpython3.7.dll, python37.dll, libpython37m.dll
This would mean your Python installation doesn't come with proper library files.
This usually happens by missing development package, or unsuitable build parameters of Python installation.
>
>    If you're building Python by yourself, please rebuild your Python with --enable-shared (or, --enable-framework on Darwin)

Please set up a proper python installation. See "Build-Time Python Errors" in the manual for more.

**Comment by indiangamex** [comment]
i am facing the same problem but unable to fix the issue by above method

**Comment by bwoodsend** [comment]
How did you install Python? And what OS are you using?
