### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'scipy' distribution was not found 

### ISSUE THREAD

**Issue by shenzhuangwudi** [pyinstaller/pyinstaller#4418]
Hello Experts,

I meet "pkg_resources.DistributionNotFound: The 'scipy' distribution was not found " error when try to run my created app.  I googled and it seems I need to add the hook in such case. But there is already a hook-scipy.py with Pyinstaller.   Is that due to my scipy version is too low ? (1.1.0)

My logs: 

(C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops) C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops>pyinstaller -p C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\Lib\site-packages   --hidden-import theano.tensor.shared_randomstreams Structured_Aug19_No_Plot.py
67 INFO: PyInstaller: 3.5
68 INFO: Python: 3.6.9
68 INFO: Platform: Windows-10-10.0.17134-SP0
73 INFO: wrote C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\Structured_Aug19_No_Plot.spec
74 INFO: UPX is not available.
75 INFO: Extending PYTHONPATH with paths
['C:\\Users\\zxu14\\Desktop\\DrillOps\\nanzhe\\drillops',
 'C:\\Users\\zxu14\\Desktop\\DrillOps\\nanzhe\\drillops\\Lib\\site-packages',
 'C:\\Users\\zxu14\\Desktop\\DrillOps\\nanzhe\\drillops']
76 INFO: checking Analysis
76 INFO: Building Analysis because Analysis-00.toc is non existent
76 INFO: Initializing module dependency graph...
79 INFO: Initializing module graph hooks...
80 INFO: Analyzing base_library.zip ...
2925 INFO: Analyzing hidden import 'theano.tensor.shared_randomstreams'
3666 INFO: Processing pre-find module path hook   distutils
4748 INFO: Processing pre-find module path hook   site
4749 INFO: site: retargeting to fake-dir 'c:\\users\\zxu14\\desktop\\drillops\\nanzhe\\drillops\\lib\\site-packages\\PyInstaller\\fake-modules'
6004 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
8185 INFO: Processing pre-safe import module hook   six.moves
17813 INFO: running Analysis Analysis-00.toc
17815 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\zxu14\desktop\drillops\nanzhe\drillops\python.exe
18040 INFO: Caching module hooks...
18045 INFO: Analyzing C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\Structured_Aug19_No_Plot.py
24095 INFO: Loading module hooks...
24095 INFO: Loading module hook "hook-distutils.py"...
24096 INFO: Loading module hook "hook-encodings.py"...
24178 INFO: Loading module hook "hook-h5py.py"...
24180 INFO: Loading module hook "hook-lib2to3.py"...
24182 INFO: Loading module hook "hook-mako.codegen.py"...
24182 INFO: Loading module hook "hook-matplotlib.backends.py"...
24793 INFO:   Matplotlib backend "GTK3Agg": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
25081 INFO:   Matplotlib backend "GTK3Cairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
25479 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx'
25846 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'IPython'
26328 INFO:   Matplotlib backend "Qt4Agg": added
26635 INFO:   Matplotlib backend "Qt4Cairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
27097 INFO:   Matplotlib backend "Qt5Agg": added
27405 INFO:   Matplotlib backend "Qt5Cairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
27889 INFO:   Matplotlib backend "TkAgg": added
28333 INFO:   Matplotlib backend "TkCairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
28925 INFO:   Matplotlib backend "WebAgg": added
29322 INFO:   Matplotlib backend "WX": ignored
    No module named 'wx'
29627 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
29939 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
30248 INFO:   Matplotlib backend "agg": added
30553 INFO:   Matplotlib backend "cairo": ignored
    cairo backend requires that pycairo>=1.11.0 or cairocffiis installed
30989 INFO:   Matplotlib backend "pdf": added
31397 INFO:   Matplotlib backend "pgf": added
31698 INFO:   Matplotlib backend "ps": added
32004 INFO:   Matplotlib backend "svg": added
32401 INFO:   Matplotlib backend "template": added
32841 INFO: Loading module hook "hook-matplotlib.py"...
33104 INFO: Loading module hook "hook-numpy.core.py"...
33193 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
33196 INFO: Loading module hook "hook-numpy.py"...
33197 INFO: Loading module hook "hook-pandas.py"...
34173 INFO: Loading module hook "hook-patsy.py"...
34174 INFO: Loading module hook "hook-pkg_resources.py"...
34601 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
34662 INFO: Processing pre-safe import module hook   win32com
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'win32com'
34728 INFO: Loading module hook "hook-pydoc.py"...
34729 INFO: Loading module hook "hook-PyQt5.py"...
35143 WARNING: Hidden import "PyQt5.sip" not found!
35143 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
35207 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
35371 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
35586 INFO: Loading module hook "hook-pytz.py"...
35645 INFO: Loading module hook "hook-scipy.linalg.py"...
35647 INFO: Loading module hook "hook-scipy.py"...
35650 INFO: Loading module hook "hook-scipy.sparse.csgraph.py"...
35653 INFO: Loading module hook "hook-scipy.special._ellip_harm_2.py"...
35654 INFO: Loading module hook "hook-scipy.special._ufuncs.py"...
35655 INFO: Loading module hook "hook-setuptools.py"...
36147 INFO: Loading module hook "hook-sqlite3.py"...
36235 INFO: Loading module hook "hook-sysconfig.py"...
36236 INFO: Loading module hook "hook-xml.dom.domreg.py"...
36238 INFO: Loading module hook "hook-xml.py"...
36239 INFO: Loading module hook "hook-_tkinter.py"...
36380 INFO: checking Tree
36381 INFO: Building Tree because Tree-00.toc is non existent
36382 INFO: Building Tree Tree-00.toc
36441 INFO: checking Tree
36442 INFO: Building Tree because Tree-01.toc is non existent
36444 INFO: Building Tree Tree-01.toc
36553 INFO: Looking for ctypes DLLs
36658 INFO: Analyzing run-time hooks ...
36673 INFO: Including run-time hook 'pyi_rth_pkgres.py'
36674 INFO: Including run-time hook 'pyi_rth_mplconfig.py'
36676 INFO: Including run-time hook 'pyi_rth_mpldata.py'
36677 INFO: Including run-time hook 'pyi_rth__tkinter.py'
36678 INFO: Including run-time hook 'pyi_rth_pyqt5.py'
36682 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
36714 INFO: Looking for dynamic libraries
36818 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_blacs_mpich2_lp64.dll
36884 WARNING: lib not found: impi.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_blacs_intelmpi_lp64.dll
36928 WARNING: lib not found: msmpi.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_blacs_msmpi_lp64.dll
37207 WARNING: lib not found: tbb.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_tbb_thread.dll
37272 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_blacs_mpich2_ilp64.dll
37355 WARNING: lib not found: impi.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_blacs_intelmpi_ilp64.dll
37566 WARNING: lib not found: msmpi.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_blacs_msmpi_ilp64.dll
37775 WARNING: lib not found: pgf90.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_pgi_thread.dll
37815 WARNING: lib not found: pgc14.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_pgi_thread.dll
37855 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\zxu14\desktop\drillops\nanzhe\drillops\Library\bin\mkl_pgi_thread.dll
39150 INFO: Looking for eggs
39151 INFO: Using Python library c:\users\zxu14\desktop\drillops\nanzhe\drillops\python36.dll
39153 INFO: Found binding redirects:
[]
39223 INFO: Warnings written to C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\build\Structured_Aug19_No_Plot\warn-Structured_Aug19_No_Plot.txt
39506 INFO: Graph cross-reference written to C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\build\Structured_Aug19_No_Plot\xref-Structured_Aug19_No_Plot.html
39659 INFO: checking PYZ
39659 INFO: Building PYZ because PYZ-00.toc is non existent
39662 INFO: Building PYZ (ZlibArchive) C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\build\Structured_Aug19_No_Plot\PYZ-00.pyz
42469 INFO: Building PYZ (ZlibArchive) C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\build\Structured_Aug19_No_Plot\PYZ-00.pyz completed successfully.
42524 INFO: checking PKG
42525 INFO: Building PKG because PKG-00.toc is non existent
42526 INFO: Building PKG (CArchive) PKG-00.pkg
42562 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
42572 INFO: Bootloader c:\users\zxu14\desktop\drillops\nanzhe\drillops\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
42572 INFO: checking EXE
42572 INFO: Building EXE because EXE-00.toc is non existent
42573 INFO: Building EXE from EXE-00.toc
42573 INFO: Appending archive to EXE C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\build\Structured_Aug19_No_Plot\Structured_Aug19_No_Plot.exe
42713 INFO: Building EXE from EXE-00.toc completed successfully.
42723 INFO: checking COLLECT
42723 INFO: Building COLLECT because COLLECT-00.toc is non existent
42724 INFO: Building COLLECT COLLECT-00.toc
56108 INFO: Building COLLECT COLLECT-00.toc completed successfully.

(C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops) C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops>cd dist\Structured_Aug19_No_Plot

(C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops) C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\dist\Structured_Aug19_No_Plot>Structured_Aug19_No_Plot.exe
c:\users\zxu14\desktop\drillops\nanzhe\drillops\lib\site-packages\PyInstaller\loader\pyimod03_importers.py:627: MatplotlibDeprecationWarning:
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Traceback (most recent call last):
  File "Structured_Aug19_No_Plot.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\zxu14\desktop\drillops\nanzhe\drillops\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\pymc3\__init__.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\zxu14\desktop\drillops\nanzhe\drillops\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "Lib\site-packages\pymc3\stats.py", line 19, in <module>
  File "Lib\site-packages\pkg_resources\__init__.py", line 481, in get_distribution
  File "Lib\site-packages\pkg_resources\__init__.py", line 357, in get_provider
  File "Lib\site-packages\pkg_resources\__init__.py", line 900, in require
  File "Lib\site-packages\pkg_resources\__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'scipy' distribution was not found and is required by the application
[16836] Failed to execute script Structured_Aug19_No_Plot

(C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops) C:\Users\zxu14\Desktop\DrillOps\nanzhe\drillops\dist\Structured_Aug19_No_Plot>python
Python 3.6.9 |Anaconda, Inc.| (default, Jul 30 2019, 14:00:49) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import scipy as sp
>>> print(sp.__version__)
1.1.0
>>>

**Comment by atvKumar** [comment]
You need to provide more information (minimum example, spec file, debug output), and have you tried writing a better spec file? Including the modules and hooks?

**Comment by shenzhuangwudi** [comment]
I solve this issue by add a hook-ctypes.macholib.py with below content:

from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('scipy')

But now it givies me another error.
