### ISSUE TITLE
Qt translations on Windows package are placed in wrong directory

### ISSUE THREAD

**Issue by phw** [pyinstaller/pyinstaller#4429]
On Windows PyInstaller is placing the Qt translation files in `PyQt5\translations`, but `QtCore.QLibraryInfo.TranslationsPath` points to `PyQt5\Qt\translations`. This causes the default translations to fail loading.

Tested with latest PyInstaller from git and PyQt 5.13

**Comment by bjones1** [comment]
Thanks for pointing this out. Would you edit line 559 of `pyinstaller/utils/hooks/qt.py` to be `namespace, 'Qt' if not is_PyQt5 and is_win else '',` and see if that fixed it for you?

**Comment by phw** [comment]
Sorry for the delay. No, the above does not fix it for me, because this is PyQt5 on Windows.

What would do the trick is for the condition to be:

    'Qt' if is_PyQt5 else ''

Now I don't exactly know what use case the `is_win` check did tries to capture, the comment above indicates that the path would be different on Windows. But at least for current PyQt this is not the case. So if this gets changed the comment should probably be removed as well, but we probably break something else.

**Comment by phw** [comment]
I tested with PyQt 5.8, the oldest PyQt5 version available via pip. And also there placing it in the `Qt` subfolder is correct. So my assumption is that Windows no longer is a special case here and we can simplify the condition. I will submit a PR.

**Comment by phw** [comment]
See https://github.com/pyinstaller/pyinstaller/pull/4451

**Comment by bjones1** [comment]
Thanks for your help. I took a slightly different approach and fixed this in feeccf33e34892abbba00591a4970879243aad02.
