### ISSUE TITLE
Git tag signing key

### ISSUE THREAD

**Issue by micahflee** [pyinstaller/pyinstaller#4430]
Could you upload the PGP public key you use to sign git tags to key servers (particularly https://keys.openpgp.org/)? I have documentation that involves building PyInstaller from source, but only after verifying the git tag, by as of `v3.5` I can't find the public key anywhere:

```
$ git tag -v v3.5
object 498e6ee058915e5eb5f170f7a17f918c1f4d4cce
type commit
tag v3.5
tagger Hartmut Goebel <h.goebel@crazy-compilers.com> 1562699638 +0200

PyInstaller 3.5
gpg: Signature made Tue 09 Jul 2019 12:13:58 PM PDT
gpg:                using RSA key B943509D633E80DD27FC4EED634A8DFFD3F631DF
gpg: Can't check signature: No public key
```

Thanks!

**Comment by JJK96** [comment]
Even github does not know the key. 

![image](https://user-images.githubusercontent.com/11193274/72803463-72d68b00-3c4e-11ea-866d-9114fb91232a.png)

**Comment by micahflee** [comment]
The `v3.6` tag was signed by the same key, but the public key is still nowhere to be found:

```
$ git tag -v v3.6
object 6d4cce1f8eb80c0bf49d35876d28daa55a05800f
type commit
tag v3.6
tagger Hartmut Goebel <h.goebel@crazy-compilers.com> 1578593132 +0100

PyInstaller 3.6
gpg: Signature made Thu Jan  9 10:05:32 2020 PST
gpg:                using RSA key B943509D633E80DD27FC4EED634A8DFFD3F631DF
gpg: Can't check signature: No public key
```

**Comment by yochananmarqos** [comment]
PyPI has no signature for the 3.6 release, either: https://pypi.debian.net/pyinstaller

**Comment by Legorooj** [comment]
Please email harmut (htgoebel) at h.goebel@crazy-compilers.com to discuss this. This is not a PyInstaller issue.

**Comment by htgoebel** [comment]
I uploaded the key to https://keys.openpgp.org/. But since this server allows a single key to be associated with an e-mail-addresse, I have bo ID attached.
