### ISSUE TITLE
win32com presafe import module hook is causing unnecessary tracebacks

### ISSUE THREAD

**Issue by mstobie-seequent** [pyinstaller/pyinstaller#4431]
hooks/pre_safe_import_module/hook-win32com.py is causing tracesbacks in otherwise successful builds which breaks buildsystems. The presafe import module hooks are all always run and on windows this will attempt to import win32com which isn't actually required by pyinstaller anymore after the transition to pywin32-ctypes instead of pywin32. So on windows ImportError tracebacks will be logged when all required components are present but the build will still be successful.

This was indirectly discussed in issue 3733 and users are adding an unnecessary component pypiwin32 which isn't needed except to work around the traceback being logged.

I assume this hook was left here for when people include pywin32 for their own reasons, but it should only run when the component is used rather than always as py(pi)win32 is no longer required.

**Comment by rokm** [comment]
This was addressed by pyinstaller/pyinstaller-hooks-contrib#67.
