### ISSUE TITLE
Add binary doesnt work!

### ISSUE THREAD

**Issue by GhostFire90** [pyinstaller/pyinstaller#4432]
Hello! I've seen this question a few times but they never seem to be having EXACTLY the same issue as i am
This is the code: https://hastebin.com/vecogibuyo.py (tried changing the search path at line 157 but it says the same thing)
and the command I'm running (pyinstaller isnt set to path): .\pyinstaller --add-binary 'hidapi.dll;.' "path to my script"
```
'C:\\Users\\Evan Anderson\\Desktop\\Programs\\Python3.6.8\\Scripts\\dist\\r6controller\\hidapi.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[7732] Failed to execute script r6controller
```

**Comment by lkollar** [comment]
Unfortunately your issue does not contain sufficient information to be able to help you. Please open a new issue and make sure you follow the steps outlined in the issue template. As mentioned in the template, please provide the information requested in the [When submitting a bug](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#when-submitting-a-bug) section of the manual.

You might want to have a look at the [When things go wrong](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html) section of the manual as well for general troubleshooting tips.
