### ISSUE TITLE
Provide a way to exclude DLLs in the resulting bundle/exe

### ISSUE THREAD

**Issue by bluebird75** [pyinstaller/pyinstaller#4433]
Hi,

I am packaging a small PyQt application as a .exe .  The problem I have is that the resulting application is huge. The main reason is that it embarks many "just-in-case-we-need-it" DLL.

When packaging as a directory, I can manually delete them. But not when doing a single .exe .

It would be nice to have an option to manually exclude these dll from the final application.

In my case, I ended up doing the ugly thing but better support would be nice :  
```
del /q Qt5dbus.dll Qt5Network.dll Qt5Qml.dll Qt5Quick.dll Qt5Svg.dll Qt5WebSockets.dll
cd PyQt5\Qt
rmdir /s /q translations bin plugins\iconengines plugins\imageformats plugins\platformthemes
cd plugins\platforms
del /q qminimal.dll qoffscreen.dll qwebgl.dll
```

**Comment by bjones1** [comment]
There's no standard way to do this, unfortunately. PRs welcome.

**Comment by bluebird75** [comment]
I might look into this sometimes. Because I keep doing it for all my PyQt packaged applications.

**Comment by bwoodsend** [comment]
You can't do this from shell but you can using the spec file:

Inject something like the following between the a = Analysis(...) and the pyz = PYZ(...):

```python
to_keep = []
to_exclude = {'Qt5dbus.dll', 'Qt5Network.dll', 'Qt5Qml.dll', 'Qt5Quick.dll', 'Qt5Svg.dll', 'Qt5WebSockets.dll'}

# Iterate through the list of included binaries.
for (dest, source, kind) in a.binaries:
    # Skip anything we don't need.
    if os.path.split(dest)[1] in to_exclude:
        continue
    to_keep.append((dest, source, kind))

# Replace list of data files with filtered one.
a.binaries = to_keep
```
And then use `PyInstaller test.spec` instead of `PyInstaller test.py`. It isn't pretty put it gives you total flexibility.

**Comment by bluebird75** [comment]
That's exactly what I did for my project. Thanks for the suggestion.
