### ISSUE TITLE
PyQt is embarking too many DLL

### ISSUE THREAD

**Issue by bluebird75** [pyinstaller/pyinstaller#4434]
I am packaging a small PyQt5 application under Windows. The PyQt did a fine job of reducing the pyd which I need, it contains only :
```
sxtool\PyQt5\QtCore.pyd
sxtool\PyQt5\QtGui.pyd
sxtool\PyQt5\QtWidgets.pyd
sxtool\PyQt5\sip.pyd
```

However, it stills takes all the DLL required by the excluded pyd modules : 
```
sxtool\Qt5Core.dll
sxtool\Qt5DBus.dll
sxtool\Qt5Gui.dll
sxtool\Qt5Network.dll
sxtool\Qt5Qml.dll
sxtool\Qt5Quick.dll
sxtool\Qt5Svg.dll
sxtool\Qt5WebSockets.dll
sxtool\Qt5Widgets.dll
```

That's a pity because some of those unneeded DLLs have quite a big size.

**Comment by bjones1** [comment]
DLLs are included based on the dependencies stated within those DLLs.

**Comment by therealrahulsahu** [comment]
QtPrintSupport.dll is also not working properly.
Including all those *.dll mentioned by @bluebird75
