### ISSUE TITLE
"THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE"  error when installing pyinstaller release 3.5 with pip under Windows 10 with python 3.7.3

### ISSUE THREAD

**Issue by pythonaddict** [pyinstaller/pyinstaller#4436]
I use Windows 10 and python 3.7.3.
I try to install the latest version of pyinstaller (3.5) with pip.
I get the following error:

```
python.exe -m pip install --upgrade --user pyinstaller

Collecting pyinstaller
  Downloading https://files.pythonhosted.org/packages/e2/c9/0b44b2ea87ba36395483a672fddd07e6a9cb2b8d3c4a28d7ae76c7e7e1e5/PyInstaller-3.5.tar.gz
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pyinstaller from https://files.pythonhosted.org/packages/e2/c9/0b44b2ea87ba36395483a672fddd07e6a9cb2b8d3c4a28d7ae76c7e7e1e5/PyInstaller-3.5.tar.gz#sha256=ee7504022d1332a3324250faf2135ea56ac71fdb6309cff8cd235de26b1d0a96:
        Expected sha256 ee7504022d1332a3324250faf2135ea56ac71fdb6309cff8cd235de26b1d0a96
             Got        329bbf8cdef1528d50274261a8d109dc467b0230988e8d2dbcf744f5a24d6c46
```

**Comment by BoboTiG** [comment]
Could you retry? It works for me on 3 different OS. You OS may alter the contents of the download If so, check for a possible virus or something that can alter files you are downloading.

**Comment by danyeaw** [comment]
@pythonaddict Try creating a new [virtual environment](https://docs.python.org/3/tutorial/venv.html) and then try using `pip install pyinstaller --no-cache-dir`. I don't think this is an issue with PyInstaller.

**Comment by htgoebel** [comment]
"THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE"

No clue where this requirements file should come from. I assume this is not a pyinstaller issue.

**Comment by sgauert** [comment]
I get the same error under Windows 7 Python 3.7.3.
installing with --no-chache-dir does not solve it. 
Any ideas? 
`>pip install --no-cache-dir pyinstaller
Collecting pyinstaller
  Downloading PyInstaller-3.6.tar.gz (3.4 kB)
ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; someone may have tampered with them.
    pyinstaller from https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz#sha256=3730fa80d088f8bb7084d32480eb87cbb4ddb64123363763cf8f2a1378c1c4b7:
        Expected sha256 3730fa80d088f8bb7084d32480eb87cbb4ddb64123363763cf8f2a1378c1c4b7
             Got        84a7bd6816c362cbe408d24302f2bf25058a8937f6774b90f968f10936940d15


>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>`

**Comment by sgauert** [comment]
Same with:
`pip install pyinstaller==3.1.1`

BUT 
works with 
`pip install pyinstaller==3.1`

**Comment by andreynovikov** [comment]
Windows 10
```pip install pyinstaller==3.6``` - fails
```pip install pyinstaller==3.5``` - works
