### ISSUE TITLE
pyinstaller having trouble bundling a package containing SWIG modules

### ISSUE THREAD

**Issue by muhammeteminturgut** [pyinstaller/pyinstaller#4439]
`from pocketsphinx import *`
This is how I import sphinx in my project. Normally it works fine but when I package it with pyinstaller it always gives this error:
`ImportError: No module named 'sphinxbase._ad_win32'`
I've tried different paths and hidden imports. But the result does not change

In addition, someone else experienced the same problem, but it was not solved:

https://stackoverflow.com/questions/53937930/pyinstaller-having-trouble-bundling-a-package-containing-swig-modules
https://github.com/Uberi/speech_recognition/issues/400

**Comment by danyeaw** [comment]
@muhammeteminturgut Thanks for reporting the issue.

Tell help us triage this issue, could you please check out the [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). We need more details about what your setup is, and a minimum example. When are you getting this error? Do you have debug enabled, and what is the output from building the app?

**Comment by htgoebel** [comment]
This issue is one year old now, and required information is still missing. Closing.
