### ISSUE TITLE
Mac/PySide2: qt.qpa.plugin: Could not load the Qt platform plugin "cocoa" in "" even though it was found

### ISSUE THREAD

**Issue by vancouvermichael** [pyinstaller/pyinstaller#4442]
I have the above error on MAC with Pyinstaller 3.4 or 4.0.dev0+8196c57ab;  and I don't have the error on Windows 10 with Pyinstaller 3.4.

 On both OS, I am using (Miniconda) PySide2 5.13.1, qt 5.12.1, python 3.7.3. 

I read quite a few threads on this back and forth, and cannot make progress -:)

**Comment by BoboTiG** [comment]
Could you share a minimal script and the associated spec file or the command line used to generate the executable?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
