### ISSUE TITLE
Compiling QML files into single executable

### ISSUE THREAD

**Issue by RESP3CT88** [pyinstaller/pyinstaller#4443]
How can I bundle view.qml into my Python project as a single executable? When I run "pyinstaller --onefile main.py", running the executable results in an error that the QML file is not found. Unless I use an absolute path or place view.qml in the same directory as my executable. I don't want to have a separate QML file, I want it combined into the executable.

***main.py:***

    if __name__ == "__main__":
      app = QGuiApplication(sys.argv)
      engine = QQmlApplicationEngine()
      engine.load(QUrl("view.qml"))
      sys.exit(app.exec_())

***view.qml:***

    import QtQuick 2.0

    ApplicationWindow {
      id: window
      title: "Window"
      width: 900
      height: 600
      visible: true
    }

**Comment by BoboTiG** [comment]
PyInstaller does no magic. If the script needs an external file, then the executable too.

A possible solution, not tested, is to write the contents of `view.qml` from the script into a temporary file.

**Comment by Systemcluster** [comment]
When you need additional files packaged alongside your executable, add them to the `datas` property in your spec file or use `--add-data` on the command line. See [this section in the docs](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-data-files). They will then be extracted alongside your scripts, and you can get the runtime path [as described here](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html).
