### ISSUE TITLE
"exit()" is not defined, but is valid in script in Python 3.7.4

### ISSUE THREAD

**Issue by Thomasedv** [pyinstaller/pyinstaller#4448]
To keep it short, i have a script with uses this:

`exit(0)`

**I know in older python versions, you had to use `sys.exit(0)`.** But this is apparently fully valid and working in a simple python script i've tested, and i'm running **Python 3.7.4** on **Windows 10**. I'm not sure if it's intentional for this python version or not, but i'm surprised it works for my script up until pyinstaller tries to run that line. Aka, i get a script failed to execute when i try to close my script with that line. 

Pyinstaller is also running python 3.7.4 to be clear. The python file can be run on it's own, but not when compiled to a .exe. 

# Example script:
```python
import sys
print(sys.version)
exit(2)
```
# Output
```
PS C:\Users\Redacted\dist> .\test.exe
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
Traceback (most recent call last):
  File "test.py", line 3, in <module>
    exit(2)
NameError: name 'exit' is not defined
[14024] Failed to execute script test

PS C:\Users\Redacted\dist> python .\test.py
3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
```
Note, no error on running test .py. Exectuable compiled with command:
`python -m PyInstaller .\test.py --onefile` (don't need the --onefile tag. Crashes either way)
Pyinstaller version: `PyInstaller: 4.0.dev0+8196c57ab` (should be latest)
All things run in the same PowerShell window, to prove that it's the same python version that's being used for all things.

**Comment by lkollar** [comment]
The `exit()` call and a few other symbols are defined by the [`site`](https://docs.python.org/3/library/constants.html#constants-added-by-the-site-module) module as a convenience for using them in the interpreter. PyInstaller does not load the `site` module to avoid picking up arbitrary libraries, so none of these symbols will work in frozen applications. The Python documentation says that these should not be used in programs, so I would not consider this as a bug in PyInstaller.

It would be good to document this behaviour though. I will close this issue but if you would like to submit a PR to add this to the docs that would be great.

**Comment by Thomasedv** [comment]
I'm not familiar with either making pull requests nor writing the documentation, but it could be as simple as throwing your first paragraph,  (minus part after the last comma), and maybe say something like, it's recommended to use `sys.exit()` instead of just `exit`. Throw it into the #"When things go wrong" section and it would be in a decent spot in my opinion. Just need someone that knows how to.
