### ISSUE TITLE
pyinstaller cannot read outlook email datetime

### ISSUE THREAD

**Issue by criuskent** [pyinstaller/pyinstaller#4453]
I am using python 3.7.2 and try to iterate outlook inbox to search out some emails. However the .py runs good but error after compiled using pyinstaller. I check for some time and found that the pyinstaller cannot get the outlook datetime, e.g.: ReceivedTime and SentOn:
    for message in messages:
        subject = message.Subject
        RTime = message.ReceivedTime   <- error here and cannot get the datetime

May I know, are there any solution on this problem?

**Comment by lkollar** [comment]
Unfortunately your issue does not contain sufficient information for us to help you. Please open a new issue and make sure you follow the steps outlined in the issue template. As mentioned in the template, please provide the information requested in the [When submitting a bug](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#when-submitting-a-bug) section of the manual.

You might want to have a look at the [When things go wrong](https://pyinstaller.readthedocs.io/en/stable/when-things-go-wrong.html) section of the manual as well for general troubleshooting tips.
