### ISSUE TITLE
Missing required dependencies ['numpy'] in windows 8

### ISSUE THREAD

**Issue by NBronina** [pyinstaller/pyinstaller#4456]
I create exe file on windows 10. My exe works on computer with windows 10 without python but not works on computers with windows 8. 
I use:
numpy.__version__  1.17.2
pandas.__version__ 0.20.3
PyInstaller.__version__  3.5
sys.version_info  sys.version_info(major=3, minor=6, micro=3, releaselevel='final', serial=0)

I have error:
`Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "c:\programdata\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_i
mporters.py", line 627, in exec_module
  File "site-packages\pandas\__init__.py", line 19, in <module>
ImportError: Missing required dependencies ['numpy']
[5720] Failed to execute script main`

I do not understand why my prog works on one computer and not works on another. Help me, please.

**Comment by NBronina** [comment]
line 3 in code: import pandas as pd

**Comment by bwoodsend** [comment]
Sounds like a repeat of #4968 which was fixed in #5213.
