### ISSUE TITLE
Multiprocessing in PyInstaller: 4.0.dev0+00f1ee519

### ISSUE THREAD

**Issue by PapaTim68** [pyinstaller/pyinstaller#4457]
Was using PyInstaller in Python 3.7.3 on Win7 had problem with using Multiprocessing, looked up the Issues with PyInstaller and Multiprocessing found the link below:
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing

The artikel states that adding multiprocessing.freeze_support() is no longer needed since version 3.3 this seems to be wrong, because adding it fixed my Problem with the frozen application

**Comment by lkollar** [comment]
The article you are referring to states that you *must* add that line in your code. Additionally, under Python 3.3 on Windoes you need the steps outlined in https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing#additional-code-for-pyinstaller--33-and-windows. Feel free to reopen if you think something is still incorrect.
