### ISSUE TITLE
CV2 Module Missing (fix)

### ISSUE THREAD

**Issue by akai-katto** [pyinstaller/pyinstaller#4461]
I was getting this error:

"ModuleNotFoundError: No module named 'cv2'"

![image](https://user-images.githubusercontent.com/28079088/66185591-cc319480-e634-11e9-9441-554d946c66ee.png)

Then adding the --hidden-import and --add-binary seemed to fix it.

`pyinstaller --add-binary C:\Users\windwoz\Desktop\dandere2x_building_folder\virtual\Lib\site-packages\cv2\opencv_ffmpeg400_64.dll;opencv_ffmpeg400_64.dll --hidden-import opencv-python -F gui_driver.py`

**Comment by danyeaw** [comment]
@aka-katto It would help us if you posted the actual minimum example and the output instead of a screenshot. If adding a imports and a binary fixes it, then creating a hook would help the next person package whatever you are packaging.

**Comment by JapinderSandhu** [comment]
I am having this issue, I dont full understand how to fix it. Many people are saying create a hook file will help but I dont know what to add in my hook file exactly 

ex.https://stackoverflow.com/questions/49232117/using-pyinstaller-to-package-python-program-and-there-is-a-nomodulefinderror


ex.https://stackoverflow.com/questions/47607315/modulenotfounderror-no-module-named-pandas-libs-tslibs-timedeltas


hiddenimports = ['pandas._libs.tslibs.timedeltas']

What would the openCV equivalent be to the 'pandas._libs.tslibs.timedeltas',

What does this line even mean?

**Comment by Osmar-Gael-Sanchez-Loeza** [comment]
"¿Cuál sería el equivalente de openCV a los 'pandas._libs.tslibs.timedeltas',"

¿Pudiste resolverlo?
