### ISSUE TITLE
cannot get outlook message received time

### ISSUE THREAD

**Issue by criuskent** [pyinstaller/pyinstaller#4463]
I wrote a python 3.7.2 small program (on Windows 10 x64) to iterate my outlook emails, it runs good under interpreter. However it runs (run as admin) failed to get the received_time property after compiled with pyinstaller 3.5. Here under is my code:

****************************************************************************************

```
import win32com.client
import win32com
import os, sys, time, datetime, os.path

outlook = win32com.client.Dispatch("Outlook.Application").GetNamespace("MAPI")
inbox = outlook.GetDefaultFolder(6)
messages = inbox.Items
for message in messages:
	if message.messageclass == "IPM.Note":       # get email message only
		try:
			print(message.ReceivedTime.strftime('%Y-%m-%d %H:%M:%S')[0:19])
		except:
			print("error to get received time")   # always show this message after compiled
```

*****************************************************************************************
Below are the pyinstaller compiler message:
*****************************************************************************************

C:\Users\user\Desktop\> pyinstaller -y -F "C:/Users/user/Desktop/1.py"

80 INFO: PyInstaller: 3.5
80 INFO: Python: 3.7.2
81 INFO: Platform: Windows-10-10.0.18362-SP0
82 INFO: wrote C:\Users\user\Desktop\1.spec
85 INFO: UPX is not available.
87 INFO: Extending PYTHONPATH with paths
['C:\\Users\\user\\Desktop', 'C:\\Users\\user\\Desktop']
87 INFO: checking Analysis
88 INFO: Building Analysis because Analysis-00.toc is non existent
88 INFO: Initializing module dependency graph...
92 INFO: Initializing module graph hooks...
94 INFO: Analyzing base_library.zip ...
3583 INFO: running Analysis Analysis-00.toc
3605 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\program files (x86)\python37-32\python.exe
6229 INFO: Caching module hooks...
6238 INFO: Analyzing C:\Users\user\Desktop\1.py
6241 INFO: Processing pre-safe import module hook   win32com
6295 INFO: Processing pre-find module path hook   distutils
9867 INFO: Processing pre-find module path hook   site
9868 INFO: site: retargeting to fake-dir 'c:\\program files (x86)\\python37-32\\lib\\site-packages\\PyInstaller\\fake-modules'
12473 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
17492 INFO: Loading module hooks...
17492 INFO: Loading module hook "hook-distutils.py"...
17494 INFO: Loading module hook "hook-encodings.py"...
17603 INFO: Loading module hook "hook-lib2to3.py"...
17613 INFO: Loading module hook "hook-numpy.core.py"...
17768 INFO: Loading module hook "hook-numpy.py"...
17769 INFO: Loading module hook "hook-PIL.Image.py"...
18199 INFO: Loading module hook "hook-PIL.py"...
18201 INFO: Excluding import 'PySide'
18203 INFO:   Removing import of PySide from module PIL.ImageQt
18205 INFO: Excluding import 'PyQt4'
18207 INFO:   Removing import of PyQt4 from module PIL.ImageQt
18208 INFO: Excluding import 'PyQt5'
18211 INFO:   Removing import of PyQt5 from module PIL.ImageQt
18212 INFO: Excluding import 'tkinter'
18215 INFO:   Removing import of tkinter from module PIL.ImageTk
18216 INFO: Import to be excluded not found: 'FixTk'
18216 INFO: Loading module hook "hook-PIL.SpiderImagePlugin.py"...
18220 INFO: Excluding import 'tkinter'
18221 INFO: Import to be excluded not found: 'FixTk'
18221 INFO: Loading module hook "hook-pkg_resources.py"...
19014 INFO: Loading module hook "hook-pycparser.py"...
19015 INFO: Loading module hook "hook-pydoc.py"...
19016 INFO: Loading module hook "hook-pythoncom.py"...
19461 INFO: Loading module hook "hook-pywintypes.py"...
19840 INFO: Loading module hook "hook-setuptools.py"...
20453 INFO: Loading module hook "hook-sysconfig.py"...
20454 INFO: Loading module hook "hook-win32com.py"...
20535 INFO: Loading module hook "hook-xml.dom.domreg.py"...
20536 INFO: Loading module hook "hook-xml.py"...
20536 INFO: Loading module hook "hook-_tkinter.py"...
21016 INFO: checking Tree
21016 INFO: Building Tree because Tree-00.toc is non existent
21016 INFO: Building Tree Tree-00.toc
21110 INFO: checking Tree
21110 INFO: Building Tree because Tree-01.toc is non existent
21110 INFO: Building Tree Tree-01.toc
21182 INFO: Looking for ctypes DLLs
21228 INFO: Analyzing run-time hooks ...
21237 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
21241 INFO: Including run-time hook 'pyi_rth_pkgres.py'
21243 INFO: Including run-time hook 'pyi_rth__tkinter.py'
21245 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
21264 INFO: Looking for dynamic libraries
44835 INFO: Looking for eggs
44835 INFO: Using Python library c:\program files (x86)\python37-32\python37.dll
44836 INFO: Found binding redirects:
[]
44848 INFO: Warnings written to C:\Users\user\Desktop\build\1\warn-1.txt
45017 INFO: Graph cross-reference written to C:\Users\user\Desktop\build\1\xref-1.html
45081 INFO: checking PYZ
45082 INFO: Building PYZ because PYZ-00.toc is non existent
45082 INFO: Building PYZ (ZlibArchive) C:\Users\user\Desktop\build\1\PYZ-00.pyz
46865 INFO: Building PYZ (ZlibArchive) C:\Users\user\Desktop\build\1\PYZ-00.pyz completed successfully.
46898 INFO: checking PKG
46899 INFO: Building PKG because PKG-00.toc is non existent
46899 INFO: Building PKG (CArchive) PKG-00.pkg
56321 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
56367 INFO: Bootloader c:\program files (x86)\python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
56367 INFO: checking EXE
56367 INFO: Building EXE because EXE-00.toc is non existent
56368 INFO: Building EXE from EXE-00.toc
56368 INFO: Appending archive to EXE C:\Users\user\Desktop\dist\1.exe
56397 INFO: Building EXE from EXE-00.toc completed successfully.

****************************************************************************************************

Will anyone please have any solution? Thank you.

**Comment by danyeaw** [comment]
@criuskent Thanks for submitting the issue :+1:.

Have you checked out the wiki page about [How to Report a Bug](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs), that will help us triage the issue. Things in there that are recommended include using a virtualenv, turning on debug, using the `--onedir` mode instead of `-F`, and trying with the latest development version.

What happens when it fails to get the time. Is there an error message?

**Comment by dylan1218** [comment]
I'm not 100% sure but I believe I'm running into a related bug. When running my program under the PyInstaller .exe, accessing Outlook.Application.File.Mailitems properties/methods don't seem to be working. 

Linking the code I'm trying to convert to .exe with Pyinstaller for reference: https://github.com/dylan1218/ArchiveOutlook/blob/master/archiveoutlook.py

When I have some additional time I'll go through the formal bug submittal process documented at https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.

**Comment by criuskent** [comment]
I added the 'win32timezone' to the top of my example here:

###*****************************************************************************************************
import win32timezone
import win32com.client
import win32com
import os, sys, time, datetime, os.path

outlook = win32com.client.Dispatch("Outlook.Application").GetNamespace("MAPI")
inbox = outlook.GetDefaultFolder(6)
messages = inbox.Items
for message in messages:
	if message.messageclass == "IPM.Note":       # get email message only
		try:
			print(message.ReceivedTime.strftime('%Y-%m-%d %H:%M:%S')[0:19])
		except:
			print("error to get received time")   # always show this message after compiled
###*****************************************************************************************************

result:
====
1. no error and successful if run under python 3.7.2 interpreter
2. no error, no any message displayed if run the compiled .exe that compiled with pyinstaller
    (even the "error to get received time" not displayed and the program ends within 1 second)
3. still no luck at the moment

**Comment by dylan1218** [comment]
@Criuskent I had a similar issue when _**not**_ compiling under the one file paramater. After compiling to one .exe file my script ran sucessfully.

**Comment by dylan1218** [comment]
> I added the 'win32timezone' to the top of my example here:
> 
> ###*****************************************************************************************************
> import win32timezone
> import win32com.client
> import win32com
> import os, sys, time, datetime, os.path
> 
> outlook = win32com.client.Dispatch("Outlook.Application").GetNamespace("MAPI")
> inbox = outlook.GetDefaultFolder(6)
> messages = inbox.Items
> for message in messages:
> if message.messageclass == "IPM.Note": # get email message only
> try:
> print(message.ReceivedTime.strftime('%Y-%m-%d %H:%M:%S')[0:19])
> except:
> print("error to get received time") # always show this message after compiled
> ###*****************************************************************************************************
> 
> # result:
> 1. no error and successful if run under python 3.7.2 interpreter
> 2. no error, no any message displayed if run the compiled .exe that compiled with pyinstaller
>    (even the "error to get received time" not displayed and the program ends within 1 second)
> 3. still no luck at the moment

@criuskent I had a similar issue when not compiling under the one file paramater. After compiling to one .exe file my script ran sucessfully.

**Comment by criuskent** [comment]
@dylan1218,

really appreciate for your help....

I ALWAYS compiled with 'one file' option and never success. However, I also tried the 'one directory' option and have no luck too.

But... with your idea, I got SUCCESSFUL run if I selected the 'console base' other than the 'window base' option....

I really want the 'window base' will also ok....

Thanks for your help and idea.

**Comment by htgoebel** [comment]
@criuskent Your application is *printing* information, thus it is required to be run in console-mode.
For window-mode you first need to add some small GUI ti display the message.

**Comment by Legorooj** [comment]
@htgoebel why did you reopen?
