### ISSUE TITLE
Licenses, esp GPL readline with onefile

### ISSUE THREAD

**Issue by jayvdb** [pyinstaller/pyinstaller#4471]
I see pyinstaller happily includes GPL libreadline.so.x into the "onefile".  A common reading of that action is that it would make all other source code linking to it also GPL, which may not be what the user was expecting, and may not be legal if the included source are incompatible with GPL.  IMO there should be a strong warning if readline was needed.

Python itself skirts around this issue by making it an optionally loadable module, but is dancing on the line by loading that module by default.

https://github.com/conda-forge/python-feedstock/issues/191 is nice read on the specific issue of libreadline - lots of links to relevant info, including from RMS on the specific issue of python and libreadline, which presumably is close to the official FSF position.

There is a libedit which is supported.  Python has some info about this at https://docs.python.org/3/library/readline.html

https://github.com/indygreg/python-build-standalone#readline--libedit--ncurses has some more info, by a similar project which gets around this problem by using pre-built Python that include libedit on at least macOS and Linux.

There is also the broader issue that pyinstaller does not include the license text of any of the objects it builds into the onedir binary. https://github.com/indygreg/python-build-standalone and https://github.com/indygreg/PyOxidizer do have a licensing component which would be a useful guide, however they only automatically handle licensing of the runtime components, not the Python packages included -- I have raised  https://github.com/indygreg/PyOxidizer/issues/142 about the latter set of licenses.

**Comment by jayvdb** [comment]
https://velovix.github.io/post/lgpl-gpl-license-compliance-with-pyinstaller/ is a nice post by @velovix covering what is needed to be compliant with LGPL, roughly doing what https://github.com/pyinstaller/pyinstaller/issues/664 suggested but was closed down.

It briefly touches on the GPL readline problem and their solution for LGPL could be the basis of a hacky-workaround GPL readline solution.  An internal copy in the onefile could be used for distribution only, and then at startup it is extracted to a specific path known to the user and always loaded from there - the internal copy should not be loaded into the runtime directly, otherwise the build has bound it together, even if they are all dumped to a tempdir and loaded from there.

But that only provides a way to skirt around the technical restrictions imposed by the license -- the built app still needs to comply with the licenses, which includes distributing the license texts and noticed.  In addition, GPL (and maybe LGPL) also has requirements that the user must also be provided with the build process.  Very likely most pyinstaller users would prefer to not have readline and thus GPL included by default, so they can avoid those problems.

**Comment by velovix** [comment]
Thanks for creating this issue and bringing a lot of helpful links together @jayvdb!

Suffice to say it's very difficult right now to deploy a PyInstaller executable in a license-compliant way, and doing so requires a fair bit of knowledge of Python's import system and PyInstaller itself. It's not clear to me what exactly PyInstaller can do to make this situation better, but an easier way to exclude GNU Readline would be a great start.

A more complete solution could involve defining hook-like licensing directives that instructs PyInstaller on how each dependency should be handled (i.e. excluded to a lib directory, packaged in, removed with an error, etc). Just a thought. I would be interested to hear what a PyInstaller contributor thinks about this problem.

**Comment by htgoebel** [comment]
This is an issue tracker and not a discussion forum. 
The easiest solution is to publish free software.
Otherwise see #4502.

**Comment by jayvdb** [comment]
@htgoebel , I do publish free software.  The problem described isnt whether the software is free or not free.  That is irrelevant.  It is the terms of the GPL and LGPL and their effect on `onefile` as opposed to `onedir`.

I am not wanting a discussion, nor help, but would like PyInstaller's generated onefile to comply with the GPL when it includes GPL libraries, and it currently does.  At the moment, PyInstaller is actively encouraging users to violate of the GPL.  I think that is an area that needs an enhancement.
