### ISSUE TITLE
--add-binary

### ISSUE THREAD

**Issue by retro-desert** [pyinstaller/pyinstaller#4473]
Hello. Immediately, I apologize for the fact that I may have read the manual inattentively. Two pictures are needed in the script, but when compiling through the pinstaller, an error is obtained. I use windows. I tried
```
pyinstaller -F -w --add-binary "image.jpg" "logo.ico" script.py
```
and

`... --add-binary "image.jpg;IMG" "logo.ico;IMG"`

Honestly, I don’t know what the problem is. Help me) Thanks
Sorry again

**Comment by lkollar** [comment]
What you want is `--add-data`. `--add-binary` is for adding binaries and libraries to the package. See this section in the documentation on how to add data files: [Adding files to the bundle](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#adding-files-to-the-bundle).

**Comment by retro-desert** [comment]
I did as written in the docs.

`pyinstaller -F -w --icon=logo.ico --add-data 'image.jpg:.'`

And get error:

`pyinstaller: error: argument --add-data: invalid add_data_or_binary value: 'image.jpg:.'`

**Comment by danyeaw** [comment]
@retro-desert I don't think you want the :. at the end. Did you try `--add-data 'image.jpg'`?

**Comment by retro-desert** [comment]
I also tried https://github.com/brentvollebregt/auto-py-to-exe

**Comment by htgoebel** [comment]
Plesae read the docs and the help. The separator is different in windows.
