### ISSUE TITLE
[ Linux ] Removing the console

### ISSUE THREAD

**Issue by rllola** [pyinstaller/pyinstaller#4474]
I am looking for clarification on the console appearing in linux. According to the documentation the `--noconsole` will only work for Windows and macOS. Does it mean I can't stop the console opening when starting my application when using linux ?

**Comment by danyeaw** [comment]
@rllola It just means that this option isn't applicable in Linux. You can launch a GUI app in Linux by double clicking on the executable. If you launch it in this way, there will be no visible console.

**Comment by rllola** [comment]
@danyeaw Thank you!

I have installed my application on my system (debian package) and I have a .desktop file to add it to my launcher. I start it from the launcher and it automatically open the console. I am doing something wrong ?

**Comment by danyeaw** [comment]
@rllola Do you have a minimum working example?

**Comment by rllola** [comment]
@danyeaw The project is public. You can check directly on it : https://github.com/rllola/ZeronetBrowser

If needed I can make a minimum working example so it would be a bit more easier to navigate.

I think you might want to check the .desktop file which is file used on ubuntu to add to the launcher.

It is generated here : 
https://github.com/rllola/ZeronetBrowser/blob/master/scripts/generate_deb_files.sh

And you can check line 23 how we start the application : 
```
Exec=ZeronetBrowser %u
```

**Comment by danyeaw** [comment]
@rllola Yes a minimum example would be great to help try to reproduce this.

**Comment by rllola** [comment]
Hi @danyeaw,

I have found the solution to my problem and it is not link to PyInstaller. I just forgot that for debugging purpose I have activated the terminal in my `.desktop` file : 

https://github.com/rllola/ZeronetBrowser/blob/master/scripts/generate_deb_files.sh#L26

Changing this to `false` solved my issue!

Thank you for you patience and sorry for the inconvenience. Closing this.
