### ISSUE TITLE
symbol lookup error: /tmp/_MEIX5HCtb/libmkl_intel_thread.so

### ISSUE THREAD

**Issue by zsc1220** [pyinstaller/pyinstaller#4478]
This keeps happening when I execute the packaged program：

symbol lookup error: /tmp/_MEIX5HCtb/libmkl_intel_thread.so: undefined symbol: omp_get_num_procs

Can someone help me? Thank you very much

**Comment by zsc1220** [comment]
问题解决了，记录一下：
查看文件/home/software/anaconda3/lib/libiomp5.so 文件是否存在？
1.如果不存在或损坏：窗口运行 conda update intel-openmp
2.如果存在：窗口运行 gedit .bashrc 打开.bashrc文件，添加libiomp5.so文件路径，比如：
export LD_IBRARY_PATH=$LD_IBRARY_PATH:/home/xxx/anaconda3/lib
3.保存.bashrc文件并关闭，在窗口运行 source .bashrc
4.重新打开窗口就可正常运行打包程序了

**Comment by sureatgithub** [comment]
请问为什么是要确定libiomap5.so这个文件呢？我的报错如下
xxx/打包程序: symbol lookup error: /xxx/打包程序/libmkl_intel_thread.so: undefined symbol: __kmpc_global_thread_num
按照你的记录没有解决。谢谢！
