### ISSUE TITLE
NullWriter does not play nice with faulthandler in windowed mode

### ISSUE THREAD

**Issue by sveinse** [pyinstaller/pyinstaller#4481]
Running `pyinstaller 4.0.dev0+a9b299995` in virtualenv on Windows 10, Python 3.7.5 32-bit.

The `faulthandler.enable()` method makes the application crash with the following error if the application is built in windowed mode. However, if the app is started in another terminal, such as windows git bash, the application works fine.

```
Traceback (most recent call last):
  File "app.py", line 30, in <module>
    faulthandler.enable()
AttributeError: 'NullWriter' object has no attribute 'fileno'
```

I am uncertain if this is a bug. Reading the docs for `faulthandler` it will by default dump its output to the default file `sys.stderr` (which is a `NullWriter` object in a pyinstaller generated exe). If `--noconsole` is used, then this faulthandler doesn't really make any sense, since there is nowhere useful place to send the error output. The other argument for this being a bug is that the code should ideally work independent of having an available console or not, which I assume is the reason for using the `NullWriter` in the first place. 

The following snippet demonstrates the failure. It will generate an `app.log` file which shows that the error has occurred.

```
# Build with:  venv\Scripts\pyinstaller.exe --noconfirm --onefile --noconsole app.py

import sys
import faulthandler
import logging

logger = logging.getLogger(__name__)

def start_logging():

    rootlogger = logging.getLogger()
    rootlogger.setLevel(logging.DEBUG)

    filelog = logging.FileHandler(filename='app.log', mode='w')
    filelog.setLevel(logging.DEBUG)
    logger.addHandler(filelog)

    console = logging.StreamHandler()
    console.setLevel(logging.DEBUG)
    logger.addHandler(console)

print(f"STDERR: {sys.stderr}")
start_logging()
logger.error("START")
try:
    faulthandler.enable()
except:
    logger.exception("Faulthandler failed")
logger.error("STOP")
```

**Comment by rokm** [comment]
> I am uncertain if this is a bug. 

I'd argue it is not.

If you run your example code in no-console python interpreter (`pythonw.exe`), `faulthandler.enable()` also fails, as indicated in the app.log:
```
START
Faulthandler failed
Traceback (most recent call last):
  File "app.py", line 24, in <module>
    faulthandler.enable()
RuntimeError: sys.stderr is None
STOP
```

So the only difference between non-frozen and frozen no-console application is that in latter, [the error occurs one check later](https://github.com/python/cpython/blob/7591d9455eb37525c832da3d65e1a7b3e6dbf613/Modules/faulthandler.c#L146-L177). We could add a `fileno`attribute with an invalid value, but that would just postpone the error to the next check.
