### ISSUE TITLE
Cross-Compiling Bootloader for ARM32

### ISSUE THREAD

**Issue by abhiarora4** [pyinstaller/pyinstaller#4487]
I have successfully cross-compiled bootloader for ARM32 on Ubuntu x86_64 Platform. My TARGET doesn't have `gcc` and earlier I was facing this issue: [https://github.com/pyinstaller/pyinstaller/issues/1619](url). But I resolved it as mentioned in this link.

 It is showing under ./bootloader/build/debug/run_d & ./bootloader/build/release/run. After this, I moved the directory to my TARGET machine and tried python3.5 setup.py install but it is unable to find the binaries created. It is showing 

```
No precompiled bootloader found. Trying to compile it for you ...
Setting top to                           : /home/root/PyInstaller-3.5/bootloader
Setting out to                           : /home/root/PyInstaller-3.5/bootloader/build
Python Version                           : 3.5.6 (default, Sep  5 2019, 14:03:50) [GCC 7.3.0]
Checking for 'gcc' (C compiler)          : not found
Checking for 'clang' (C compiler)        : not found
Checking for 'icc' (C compiler)          : not found
could not configure a C compiler!
(complete log in /home/root/PyInstaller-3.5/bootloader/build/config.log)
ERROR: Failed compiling the bootloader. Please compile manually and rerun setup.py
```

Please help.

**Comment by htgoebel** [comment]
Great to hear PyInstaller build on ARM32.

`waf install` copies the build binaries into `PyInstaller/bootloader`, which is the directory you need to copy. But I suggest to run `python setup.py sdist` to build you own package including the build binaries.
