### ISSUE TITLE
Small file on windows but huge in linux

### ISSUE THREAD

**Issue by ezalorpro** [pyinstaller/pyinstaller#4494]
Hello, i'm making a stand alone PySide2 application with PyInstaller, but the file size is huge on linux, in windows the .exe size is just 70mb while in linux is 194.6MB (510.8MB on Dir mode). In both cases the build was made using a virtual environment only with the necessary modules. Apparently it is adding all the files of the modules in linux.

> Windows 10: Python 3.7.4 32 bits
> Linux Mint 19.2: Python 3.7.5 64 bits
> Modules:
> altgraph==0.16.1
>cycler==0.10.0
>decorator==4.4.0
>kiwisolver==1.1.0
>matplotlib==3.1.1
>networkx==2.3
>numpy==1.17.3
>parse==1.12.1
>PyInstaller==4.0.dev0+a9b299995
>pyparsing==2.4.2
>PySide2==5.13.0
>python-dateutil==2.8.0
>scipy==1.3.1
>shiboken2==5.13.0
>six==1.12.0

Also, the control module, scikit fuzzy and PyQtGraph are included in my code folder.

command for spec file : ```../venv/bin/pyi-makespec --icon="icono.ico" --add-data="icono.ico:." --add-data="Esquemas:Esquemas" main.py``` 

command for pyinstaller: ```../venv/bin/pyinstaller --clean --log-level DEBUG main.spec```

Output: https://gist.github.com/ezalorpro/d894f8858078e7e128930a4cbaefc7b8

**Comment by bcyran** [comment]
I'm struggling with the same problem right now. wxPython application, almost no dependencies: on Windows 26MB, on Linux 120 MB.

**Comment by bwoodsend** [comment]
This is likely fixed by #5110?

**Comment by stansotn** [comment]
Perhaps I am doing something wrong, but I am still struggling with this issue. I am using `flask` and `pywebview` and getting 110MB on Linux and only 20MB on windows

**Comment by bwoodsend** [comment]
@stansotn Unless you're using a very old version of PyInstaller, create a new bug report.

**Comment by rokm** [comment]
> pywebview

Also, are you sure you're not comparing apples to oranges? `pywebview` clearly states that it uses different toolkits on linux vs Windows...

**Comment by stansotn** [comment]
I suppose `pywebview` on Ubuntu uses gtk by default on linux..

My pyinstaller version is 4.3.

Could this be related to using `pipenv` to handle the virtual environment? Here is my Pipfile
```
[packages]
flask = "*"
flask-cors = "*"
pyserial = "*"
pywebview = "*"
pygobject = "*"

[dev-packages]
pyinstaller = "*"
```

**Comment by rokm** [comment]
Can you open a new issue and attach the build log for linux?
