### ISSUE TITLE
boot loader error: windows\run.rc.o: No such file or directory

### ISSUE THREAD

**Issue by chandudasari1988** [pyinstaller/pyinstaller#4501]
Hi ,
I have tried follow the bootloader guide and installed everything as suggested and tried all the existing branches from github(master,develop,bootloader-works,etc)
But every time i'm facing the same issue, i didn't even find solution for the same in any of the issues.
while doing build install i'm getting below modules as no. I think these might be the issue please suggest me a solution to move forward.
**Checking for function unsetenv                      : no
Checking for function mkdtemp                       : no**

Master:
'distclean' finished successfully (0.015s)
'all' finished successfully (0.000s)
'distclean' finished successfully (0.001s)
Setting top to                           : C:\Users\Administrator\Downloads\pyinstaller-master\bootloader
Setting out to                           : C:\Users\Administrator\Downloads\pyinstaller-master\bootloader\build
Python Version                           : 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Checking for 'msvc' (C compiler)         : not found
Checking for 'gcc' (C compiler)          : C:\TDM-GCC-64\bin\gcc.exe
Checking size of pointer                 : 8
Platform                                 : Windows-64bit detected based on compiler
Checking for flags -m64                  : yes
Checking for program 'C:\\TDM-GCC-64\\bin\\windres' : C:\TDM-GCC-64\bin\windres.exe
Checking for program 'C:\\TDM-GCC-64\\bin\\strip'   : C:\TDM-GCC-64\bin\strip.exe
Checking for program 'strip'                        : C:\TDM-GCC-64\bin\strip.exe
Checking for library user32                         : yes
Checking for library comctl32                       : yes
Checking for library kernel32                       : yes
Checking for library ws2_32                         : yes
Checking for function unsetenv                      : no
Checking for function mkdtemp                       : no
'configure' finished successfully (3.811s)
'make_all' finished successfully (0.012s)
Waf: Entering directory `C:\Users\Administrator\Downloads\pyinstaller-master\bootloader\build\debug'
[ 1/23] Compiling zlib\unzip.c
[ 2/23] Compiling zlib\inffast.c
[ 3/23] Compiling zlib\adler32.c
[ 4/23] Compiling zlib\ioapi.c
[ 5/23] Compiling zlib\inftrees.c
[ 6/23] Compiling zlib\crc32.c
[ 7/23] Compiling zlib\inflate.c
[ 8/23] Compiling zlib\zutil.c
[ 9/23] Compiling src\pyi_python.c
[10/23] Compiling src\main.c
[11/23] Compiling windows\run.rc
C:\TDM-GCC-64\bin\windres.exe: windows\run.rc.o: No such file or directory
..\..\src\pyi_utils.c: In function 'pyi_setenv':
..\..\src\pyi_utils.c:199:10: error: implicit declaration of function '_wputenv_s' [-Werror=implicit-function-declaration]
     rc = _wputenv_s(wvar, wval);
          ^
cc1.exe: all warnings being treated as errors

Waf: Leaving directory `C:\Users\Administrator\Downloads\pyinstaller-master\bootloader\build\debug'
Broken revdeps detected on {
        {task 1978714465216: strip run_d.exe -> },
        {task 1978714465104: cprogram main.c.2.o,pyi_archive.c.2.o,pyi_global.c.2.o,pyi_launch.c.2.o,pyi_main.c.2.o,pyi_path.c.2.o,pyi_python.c.2.o,pyi_python27_compat.c.2.o,pyi_pythonlib.c.2.o,pyi_utils.c.2.o,pyi_win32_utils.c.2.o,run.rc.o -> run_d.exe}}

develop:

'distclean' finished successfully (0.001s)
'all' finished successfully (0.000s)
'distclean' finished successfully (0.001s)
Setting top to                           : C:\Users\Administrator\Downloads\pyinstaller-develop\bootloader
Setting out to                           : C:\Users\Administrator\Downloads\pyinstaller-develop\bootloader\build
Python Version                           : 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:37:50) [MSC v.1916 64 bit (AMD64)]
Checking for 'msvc' (C compiler)         : not found
Checking for 'gcc' (C compiler)          : C:\TDM-GCC-64\bin\gcc.exe
Checking size of pointer                 : 8
Platform                                 : Windows-64bit detected based on compiler
Checking for compiler flags -m64         : yes
Checking for program 'C:\\TDM-GCC-64\\bin\\windres' : C:\TDM-GCC-64\bin\windres.exe
Checking for program 'C:\\TDM-GCC-64\\bin\\strip'   : C:\TDM-GCC-64\bin\strip.exe
Checking for program 'strip'                        : C:\TDM-GCC-64\bin\strip.exe
Checking for library user32                         : yes
Checking for library comctl32                       : yes
Checking for library kernel32                       : yes
Checking for library ws2_32                         : yes
Checking for function unsetenv                      : no
Checking for function mkdtemp                       : no
'configure' finished successfully (3.545s)
'make_all' finished successfully (0.027s)
Waf: Entering directory `C:\Users\Administrator\Downloads\pyinstaller-develop\bootloader\build\debug'
[ 1/23] Compiling zlib\unzip.c
[ 2/23] Compiling zlib\inffast.c
[ 3/23] Compiling zlib\adler32.c
[ 4/23] Compiling zlib\ioapi.c
[ 5/23] Compiling zlib\inftrees.c
[ 6/23] Compiling zlib\crc32.c
[ 7/23] Compiling zlib\inflate.c
[ 8/23] Compiling zlib\zutil.c
[ 9/23] Compiling src\pyi_launch.c
[10/23] Compiling src\pyi_global.c
[11/23] Compiling src\pyi_pythonlib.c
[12/23] Compiling src\pyi_python27_compat.c
[13/23] Linking build\debug\libstatic_zlib.a
[14/23] Compiling src\pyi_utils.c
[15/23] Compiling windows\run.rc
C:\TDM-GCC-64\bin\windres.exe: windows\run.rc.o: No such file or directory

..\..\src\pyi_utils.c: In function 'pyi_setenv':
..\..\src\pyi_utils.c:199:10: error: implicit declaration of function '_wputenv_s' [-Werror=implicit-function-declaration]
     rc = _wputenv_s(wvar, wval);
          ^
cc1.exe: all warnings being treated as errors

Waf: Leaving directory `C:\Users\Administrator\Downloads\pyinstaller-develop\bootloader\build\debug'
Build failed
 -> task in 'run_d' failed with exit status 1 (run with -v to display more information)
 -> task in 'run_d' failed with exit status 1 (run with -v to display more information)

**Comment by htgoebel** [comment]
Closing as invalid. Python 3.8 is not yet supported.
