### ISSUE TITLE
Don't include dependencies and VCRUNTIME

### ISSUE THREAD

**Issue by stef-pellegrino** [pyinstaller/pyinstaller#4502]
Hi,
Is it possible, under Windows

- Not to include VCRUNTIME140.dll 
- Disable all the ctypes dependencies ??

Thanks

**Comment by danyeaw** [comment]
@stef-pellegrino Could you please provide more information about what your use case is and what you are trying to achieve? Are you asking for a new Feature to limit what PyInstaller packages?

**Comment by htgoebel** [comment]
@stef-pellegrino THis is not what PyInstaller is builds for. But in the `.spec`-file you can manipulate the `binaries` list:
```
a = Analysis(…)
# Remove unwanted files from `a.binaries`
… 
```
Please read the TOC section in the manual.
