### ISSUE TITLE
Executable is not working on windows7 with Python3

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4510]
I'm building my app using Pyinstaller on Windows10 and try to execute in on Windows7, this is the error that I'm getting.
```
Fatal Python error: initfsencoding: unable to load the file system codec
ModuleNotFoundError: No module named 'encodings'
```
On a different Windows10 machine (or the same one that it was built on) it is working as expected.

This only happens with Python3.7.5, when building the same app with Python2.7.16 it is working on both OS types (10 &  7).

I tried to add `--hidden-import=encodings` but it did not change the result.

Pyinstaller: 3.5
Python: 3.7.5 / 2.7.16
OS: Windows 10 & 7

**Update:**
I tried with Python 3.6.8 and got the same results.
When building on Windows7 with Python 3.7.5 and running on Windows 10 it is working without any issues.

Is this a compatibility issue like in Linux with glibc? When you need to build on the lowest platform you want to support? 

**Update2**
I tried again with Python 3.8.0 and the latest "develop" branch and it seems to be working.
Is there any official release date for Python 3.8 support?
I still want to try and find the issue with Python 3.7 but don't know where to look.

**Comment by danyeaw** [comment]
@arossert Could you provide a [minimum example](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs)? I'm not sure how many people have access to both Windows 7 and Windows 10 machines to try to reproduce this.

**Comment by arossert** [comment]
@danyeaw I'm using VM's for running the different Windows machines.
For managing the Python version I'm using [pyenv-win](https://github.com/pyenv-win/pyenv-win) + virtualenv.

Even a simple `print("Hello World)` file that is built with Python 3.7/3.6 on Windows10 giving me the `ModuleNotFoundError: No module named 'encodings'` error when executed on Windows7 machine.

I'm building without any specific PyInstaller configuration as one directory.

`pyinstaller hello.py`

As mentioned, this is working in the opposite way (Build on Windows 7 does execute on Windows 10).

Testing with the latest `develop` version is still giving the same error on Python 3.7 but is working on Python 3.8.

**Comment by htgoebel** [comment]
> I tried […] the latest "develop" branch and it seems to be working.

Then please use this until a new release is available.

**Comment by arossert** [comment]
@htgoebel the latest develop version is only working with Python 3.8.0 and not Python 3.7.x.
I currently not using Python 3.8 so I would like to make it work with Python 3.7

**Comment by arossert** [comment]
@htgoebel I know that this was closed but I'm still facing this issue.
I was mistaken and the machine that created the "bad" executable is Windows Server 2012. When building on Windows10 it does work properly.

I have compared the created directories from the Windows10 and WindowsServer2012 with WinDiff and it looks like there are many more DLLs included in the bad version.
```
.\api-ms-win-core-console-l1-1-0.dll	
.\api-ms-win-core-datetime-l1-1-0.dll	
.\api-ms-win-core-debug-l1-1-0.dll	
.\api-ms-win-core-errorhandling-l1-1-0.dll	
.\api-ms-win-core-file-l1-1-0.dll	
.\api-ms-win-core-file-l1-2-0.dll	
.\api-ms-win-core-file-l2-1-0.dll	
.\api-ms-win-core-handle-l1-1-0.dll	
.\api-ms-win-core-heap-l1-1-0.dll	
.\api-ms-win-core-interlocked-l1-1-0.dll	
.\api-ms-win-core-libraryloader-l1-1-0.dll	
.\api-ms-win-core-localization-l1-2-0.dll	
.\api-ms-win-core-memory-l1-1-0.dll	
.\api-ms-win-core-namedpipe-l1-1-0.dll	
.\api-ms-win-core-processenvironment-l1-1-0.dll	
.\api-ms-win-core-processthreads-l1-1-0.dll	
.\api-ms-win-core-processthreads-l1-1-1.dll	
.\api-ms-win-core-profile-l1-1-0.dll	
.\api-ms-win-core-rtlsupport-l1-1-0.dll	
.\api-ms-win-core-string-l1-1-0.dll	
.\api-ms-win-core-synch-l1-1-0.dll	
.\api-ms-win-core-synch-l1-2-0.dll	
.\api-ms-win-core-sysinfo-l1-1-0.dll	
.\api-ms-win-core-timezone-l1-1-0.dll	
.\api-ms-win-core-util-l1-1-0.dll	
.\api-ms-win-crt-conio-l1-1-0.dll	
.\api-ms-win-crt-convert-l1-1-0.dll	
.\api-ms-win-crt-environment-l1-1-0.dll	
.\api-ms-win-crt-filesystem-l1-1-0.dll	
.\api-ms-win-crt-heap-l1-1-0.dll	
.\api-ms-win-crt-locale-l1-1-0.dll	
.\api-ms-win-crt-math-l1-1-0.dll	
.\api-ms-win-crt-multibyte-l1-1-0.dll	
.\api-ms-win-crt-process-l1-1-0.dll	
.\api-ms-win-crt-runtime-l1-1-0.dll	
.\api-ms-win-crt-stdio-l1-1-0.dll	
.\api-ms-win-crt-string-l1-1-0.dll	
.\api-ms-win-crt-time-l1-1-0.dll	
.\api-ms-win-crt-utility-l1-1-0.dll	
```

Is this making any sense? 
I'm building the same way on both machines using `pyenv-win` with `Python3.7.5` and `virtualenv`

Will appreciate if you can give me any leads on how to debug this.
