### ISSUE TITLE
3.6 Release

### ISSUE THREAD

**Issue by jakirkham** [pyinstaller/pyinstaller#4515]
Am interested in knowing the plan for making a 3.6 release of PyInstaller. In particular it seems `master` has some fixes for Python 3.8. ( https://github.com/pyinstaller/pyinstaller/issues/4311 ) So am curious when this release might be made.

**Comment by arossert** [comment]
The `develop` branch is marked as `4.0.dev0` [(here)](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/__init__.py#L23) so I assume the next version will be `4.0`.
Is there any scheduled release date?

**Comment by alexander-manley** [comment]
Python 3.8 has only recently been released, and is not yet distribution repo supported by IBM Redhat Linux 8 and derivatives as an appstream.  This will likely not happen for at least a year or longer, so why rush the 3.6/4.0 release? Having a release by the end of 1H 2020 would be good though for those enterprises using Debian based distributions or Anaconda python environments, since they repackage/rebuild on a more accelerated schedule.

**Comment by keelung-yang** [comment]
@alexander-manley Python 3.8 has one lovely feature at least: assignment expressions, and there are many people install python by themselves.

More and more packages are adding 3.8 support, here is my monitoring data:
[Packages support 3.8 on PyPI](https://pypi.org/search/?q=&o=&c=Programming+Language+%3A%3A+Python+%3A%3A+3.8)

> data time count
10.31 18:31	1,539
11.01  08:53    	1,561
11.01  18:02	1,566 
11.04  08:52	1,625
11.04  12:51	1,630
11.05  09:51	1,663
11.05  14:56	1,670
11.06  10:51	1,699

**Comment by jakirkham** [comment]
@alexander-manley, FWIW I'm raising this issue as we have already built Python 3.8 in the Conda community and are rolling out builds of other packages with Python 3.8, but weren't able to do this with PyInstaller yet. A release would help unblock us. Though it's worth noting I'm only asking the question. 😉

**Comment by ivysrono** [comment]
https://github.com/pyinstaller/pyinstaller/issues/4513

**Comment by htgoebel** [comment]
Duplicate #4311

**Comment by htgoebel** [comment]
As lang as there is no reasonable funding (see #4404), I can not take my time creating a new release. Esp. since nobody implemented *full* Python 3.8 support yet, see #4311

**Comment by alexander-manley** [comment]
@jakirkham Ubuntu 20 LTS is out with Python 3.8 as the default, along with most other new mainstream OS distros at this point.  Anaconda also has rebuilt their suite packages with Python 3.8, so it is prudent to consider all options.  One path forward is writing new application components/modules in Go, and using compiled Cython as a bridge.  That way you can continue to use legacy code that still bundles via Pyinstaller, but move forward with new features that are cross-compile capable and likely exhibit better performance, especially those parts of your code base that you would have previously written in Python and that don't call out to C/C++/Rust.  

Making a significant donation to Hartmut Goebel to further support the development of PyInstaller for future Python compatibility would be another option, as the minimum funding threshold has not been met: https://www.pyinstaller.org/funding.html

**Comment by jakirkham** [comment]
I'm not sure I follow. In any event Conda-forge won't update the package for Python 3.8 until it is supported.
