### ISSUE TITLE
Trojan Fuery.B!cl detected in windows 10

### ISSUE THREAD

**Issue by Jaime02** [pyinstaller/pyinstaller#4518]
I created a .exe program from a .py file which uses PyOpenGL, PyQt5 and sympy. When I run that exe in a system with windows defender, it detects a trojan called "Fuery.B!cl"
It's safe, don't worry.
File: https://drive.google.com/open?id=1lUCvIS9lYS6IWRyH24yfopqqIlwrQQHW
Source code: https://drive.google.com/open?id=19MkRq-fQzOSpwbjhbGocGBT2QCCGCXCT

**Comment by keelung-yang** [comment]
Which version of win10 are you using?
I'm using PyInstaller 3.5 and  Python 3.7 64 bit on  win10, both 10.0.17134.1009 and 10.0.18362.449, and all software updated. No this issue
Maybe you should update windows or it's defender

**Comment by Jaime02** [comment]
@keelung-yang  Windows 10 Pro 1909. It seems like after the last update of windows defender the issue has been fixed

**Comment by Jaime02** [comment]
No info about any fuery trojan here: https://www.microsoft.com/en-us/wdsi/definitions/antimalware-definition-release-notes
I hope it is not a pyinstaller problem
