### ISSUE TITLE
after generated .exe using pyinstaller it give me error (no module named exchangelib)

### ISSUE THREAD

**Issue by Hesham-XQ** [pyinstaller/pyinstaller#4522]
I am writing python code to fetch inbox mails using credentials and I am using exchangelib and importing some modules but when I generate .exe file using pyinstaller it give me this error after run the .exe file (ModuleNotFoundError : No module named 'exchangelib')

I tried to solve it by change hidden imports in .spec file but it failed .

here is my impot libraries

```
from exchangelib import Account , Credentials , Configuration
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
```
any help please ??

**Comment by keelung-yang** [comment]
try explicitly _import_ before _from_ in your .py:
```python
import exchangelib
```

**Comment by Hesham-XQ** [comment]
I am tried this too but failed also 
any other suggestions please ??

**Comment by Hesham-XQ** [comment]
OK Guys I figured it out : first explicitly import libraary before from in .py: then generate EXE by this line : (pyinstaller.exe --onefile -w script_name.py) but write it in the terminal in Pycharm not in command window in the project folder .. here is my impot libraries : 
```
import exchangelib 
from exchangelib import Account , Credentials , Configuration 
from exchangelib.protocol import BaseProtocol, NoVerifyHTTPAdapter
```

**Comment by alpha332** [comment]
Thanks. this saves a lot of my time.

**Comment by htgoebel** [comment]
We would appreciate if you'd submit a pull-request for a hook for this. See [this section of the manual](https://pyinstaller.readthedocs.org/en/latest/hooks.html) for more information about how to implement hooks. See our Development Guide on [how to create pull-requests for PyInstaller](https://pyinstaller.readthedocs.io/en/stable/development/pull-requests.html). Thanks.
