### ISSUE TITLE
installation error of pyinstaller

### ISSUE THREAD

**Issue by Rasjah63** [pyinstaller/pyinstaller#4524]
I can't install pyinstaller, and I get this error

`
C:\pyinstaller>pip install pyinstaller
Collecting pyinstaller
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.
connection.VerifiedHTTPSConnection object at 0x02B24E50>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pyinstaller/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.
connection.VerifiedHTTPSConnection object at 0x02B24CA0>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pyinstaller/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.
connection.VerifiedHTTPSConnection object at 0x02B24CE8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pyinstaller/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.
connection.VerifiedHTTPSConnection object at 0x02B24AD8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pyinstaller/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.
connection.VerifiedHTTPSConnection object at 0x02B24970>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed')': /simple/pyinstaller/
  
ERROR: Could not find a version that satisfies the requirement pyinstaller (from versions: none)
ERROR: No matching distribution found for pyinstaller

`
why this mistake, where am I wrong ??

**Comment by htgoebel** [comment]
You network is broken
