### ISSUE TITLE
Проблема с cv2 в pyinstaller

### ISSUE THREAD

**Issue by ivan-sudo** [pyinstaller/pyinstaller#4525]
Здравствуйте. проблема в том что при сборке в exe пишет name 'cv2' is not defined

WEBCAM.spec

# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['WebCam.py'],
             pathex=['PATCH'],
             binaries=[],
             datas=[('C:\\Python35\\Lib\\site-packages\\cv2\\', 'cv2')],
             hiddenimports=['cv2', 'opencv-python'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='WebCam',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True , icon='PATCH')

------------------------------
C:\Python35\Scripts>pyinstaller C:\Users\user100\Desktop\webCam\WebCam.spec
94 INFO: PyInstaller: 3.5
94 INFO: Python: 3.5.0
96 INFO: Platform: Windows-7-6.1.7601-SP1
98 INFO: UPX is not available.
100 INFO: Extending PYTHONPATH with paths
['C:\\Users\\user100\\Desktop\\webCam', 'C:\\Users\\user100\\Desktop\\webCam']
100 INFO: checking Analysis
149 INFO: Appending 'datas' from .spec
166 INFO: checking PYZ
197 INFO: checking PKG
199 INFO: Building because toc changed
199 INFO: Building PKG (CArchive) PKG-00.pkg
40626 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
40635 INFO: Bootloader c:\python35\lib\site-packages\PyInstaller\bootloader\Wind
ows-64bit\run.exe
40636 INFO: checking EXE
40638 INFO: Building because manifest changed
40639 INFO: Building EXE from EXE-00.toc
40651 INFO: Copying icons from ['C:\\Users\\user100\\Desktop\\webCam\\mfc.ico']
40652 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
40652 INFO: Writing RT_ICON 1 resource with 14732 bytes
40655 INFO: Updating manifest in C:\Users\user100\AppData\Local\Temp\tmpnxl3r62v
40656 INFO: Updating resource type 24 name 1 language 0
40658 INFO: Appending archive to EXE C:\Python35\Scripts\dist\WebCam.exe
40739 INFO: Building EXE from EXE-00.toc completed successfully.

pls Help

**Comment by htgoebel** [comment]
English please.
