### ISSUE TITLE
Permission Denied while using -onefile and referencing temp resource for reading

### ISSUE THREAD

**Issue by jiveman** [pyinstaller/pyinstaller#4532]
I'm having an issue reading a zip file added via the --add-data option. I read various threads talking about getting the temp directory location and reading from there. However I seem to raise [Errno 13] Permission denied when attempting to read the zip file, yet can package a simple text file and read that with no problem.  

- I'm running this script on Windows 10 platform.
- I had to downgrade to pyinstaller v3.4.  Version 3.5 was producing executables causing Windows Defender to trigger deletion because this matches Trojan:Win32/Wacatac.B!ml signature.
- I've verified the path returned from resource_path() exists

Steps to reproduce:

- create a zip file called `foo.zip`
- create a txt file called `foo.txt` with a few lines of text
- save the code sample below as `foo.py`

Run `pyinstaller --uac-admin --onefile --add-data "foo.txt;." --add-data "foo.zip;." foo.py`

```python3
import os

from zipfile import ZipFile

# resource_path used to derive PyInstaller's temp dir where code/data is extracted to
def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)


print('Test 1 - datas reading .txt file')
tf = resource_path('foo.txt')
with open(tf, 'r') as fp:
	line = fp.readline()
	cnt = 1
	while line:
		print("Line {}: {}".format(cnt, line.strip()))
		line = fp.readline()
		cnt += 1


print('Test 2 - datas reading .zip file')
install_path = 'C:\\foo'
zf = resource_path('foo.zip')
print('attempting to unzip {} to {}'.format(zf, install_path))
zipfile = ZipFile(zf)
zipfile.extractall(install_path)
```

**Comment by htgoebel** [comment]
* PyInstaller 3.4 is no longer supported. If your anti-virus does not like the current version, please contact its vendor.

* Thanks or the minimal example. But the traceback is missing . No chance to debug this without.

Beside this, your code ist wrong. Please read the manual on how to access file at run-time. In short:
* check for sys.frozen, not sys._MEIPASS
* if not frozen, you must nut use ".", as this is the current working directory.

**Comment by Legorooj** [comment]
@jiveman pinging

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.

**Comment by iumyx2612** [comment]
> Closing due to lack of response from the original author. Will re-open if you (or anyone else who has this issue) gets back to us by commenting below.

I run into this issue.
First I created the .spec file using `pyi-makespec -F -d all -c test.py` 
Then I modified my .spec file like below
```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['test.py'],
             pathex=['yolov5'],
             binaries=[],
             datas=[("yolov5/utils", "yolov5/utils"),
                    ("yolov5/models", "yolov5/models"),
                    ("yolov5/weights/yolov5s.pt", "yolov5/weights/yolov5s.pt")],
             hiddenimports=[],
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=True)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,  
          [('v', None, 'OPTION')],
          name='test',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True,
          disable_windowed_traceback=False,
          target_arch=None,
          codesign_identity=None,
          entitlements_file=None )
```
I successfully built it into one file
And I have these lines in the `test.py` script 
```
    weights = "yolov5/weights/yolov5s.pt"
    path_to_weight = path.abspath(path.join(path.dirname(__file__), weights))
```
And I use a custom loader function to load that `path_to_weight`
And this is the full image where the bug happened 

![image](https://user-images.githubusercontent.com/69593462/147050538-d6996e5b-11a6-49d4-bc5d-9501f4a57a76.png)

**Comment by rokm** [comment]
> ("yolov5/weights/yolov5s.pt", "yolov5/weights/yolov5s.pt")],

When you want to collect a single file, the second tuple element must be its destination parent directory, not destination file name. The above results in `yolov5/weights/yolov5s.pt` being collected as `yolov5/weights/yolov5s.pt/yolov5s.pt` in the application bundle, and you get permission error because the code is trying to open the directory. Changing the above rule to

> ("yolov5/weights/yolov5s.pt", "yolov5/weights")],

should solve the problem. 

(The rules that collect whole `utils` and `models` directories are OK as they are).

**Comment by iumyx2612** [comment]
> > ("yolov5/weights/yolov5s.pt", "yolov5/weights/yolov5s.pt")],
> 
> When you want to collect a single file, the second tuple element must be its destination parent directory, not destination file name. The above results in `yolov5/weights/yolov5s.pt` being collected as `yolov5/weights/yolov5s.pt/yolov5s.pt` in the application bundle, and you get permission error because the code is trying to open the directory. Changing the above rule to
> 
> > ("yolov5/weights/yolov5s.pt", "yolov5/weights")],
> 
> should solve the problem.
> 
> (The rules that collect whole `utils` and `models` directories are OK as they are).

Oh, thanks, it's working now
