### ISSUE TITLE
SciPy 1.3.2 has moved Windows DLLs to new location

### ISSUE THREAD

**Issue by efahl** [pyinstaller/pyinstaller#4533]
PyInstaller 3.5, hooks up to date with respect to master.
Python 3.7.4 x64, Windows 10 1903.

After installing SciPy 1.3.2 (previously using 1.3.1), I started getting start up errors from my .exe about 'scipy.linalg.blas' not loading and all the usual noise you get when DLLs aren't found.

I think I have it fixed with a simple hack to hooks/hook-scipy.py: just duplicate the existing four lines that grab binaries from 'extra-dll' and duplicate them for '.libs'.

```
    dll_glob = os.path.join(os.path.dirname(
        get_module_file_attribute('scipy')), '.libs', "*.dll")
    if glob.glob(dll_glob):
        binaries.append((dll_glob, "."))
```
I'm not confident about this and have no way to test other than my example, but it appears to work for me...

**Comment by Nizarazo** [comment]
I got the same issue working on it for about two days just put scipy == 1.3.1 in your requirements.txt file until Pyinstaller developers fix it.

**Comment by carandraug** [comment]
I had the same issue but fixed it in a slightly different manner. Instead of adding the dlls to binaries, I added the directory where they are to `pathext`, like so:

    import scipy
    import os.path
    scipy_libs = os.path.join(os.path.dirname(scipy.__file__), '.libs')

    a = Analysis(...,
                 pathex=[scipy_libs],
                 ...

**Comment by lstolcman** [comment]
issue is fixed by https://github.com/pyinstaller/pyinstaller/pull/4593

**Comment by paulmueller** [comment]
I can confirm that I don't have this issue with PyInstaller 3.6.

**Comment by Legorooj** [comment]
This is fixed.
