### ISSUE TITLE
Don't use `imp` for Python >= 3.8 in moduelgraph

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#4536]
Python 3.8 started to emit "DeprecationWarning" for module `imp`, which is used in `PyInstaller/lib/modulegraph/util.py`. This is annoying for users, thus I added a filter as a temporary solution. But in the long run we should either move forward to `importlib` or to `modulegraph2`.

This is a temporary fix, until #4535 is implemented:  Thus you might want to work on #4535 instead of spending time here :-)

**Comment by bonysureliya** [comment]
Hello I am New to opensource can someone guide me on this issue i want to solve this issue

**Comment by bwoodsend** [comment]
Hmm, developer docs are [here](https://pyinstaller.org/en/stable/development/index.html). But contrary to the label, this is probably quite an ambitious first pull request. Especially if _New to opensource_ also means new to git, GitHub, CI/CD, the developer side of Python packaging, pytest, etc. If you just want to get involved, the hooks repo is a better place to learn the process (https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/278 and https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/362 should be easy pickings) then you can tackle a more significant issue once you know what you're doing.
