### ISSUE TITLE
Better error message for hook utility functions

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#4538]
If hook utility functions within a hook fails, you might get tracebacks like this:
```
  File "…\site-packages\PyInstaller\hooks\hook-pendulum.py", line 16, in <module>
    datas = collect_data_files("pendulum.locales", include_py_files=True)
  File "…\site-packages\PyInstaller\utils\hooks\__init__.py", line 721, in collect_data_files
    pkg_base, pkg_dir = get_package_paths(package)
  File "…\site-packages\PyInstaller\utils\hooks\__init__.py", line 535, in get_package_paths
    file_attr = get_module_file_attribute(package)
  File "…\site-packages\PyInstaller\utils\hooks\__init__.py", line 337, in get_module_file_attribute
    raise ImportError
ImportError
```
Hook utility functions, e.g. `get_module_file_attribute`, `collect_data_files`, `collect_submodules` should catch errors and raise a more expressive one instead.

In the example above, this could raise some `ModuleExpectedByHookImportError("pendulum.locales")` with an message like "Failed to import module {modulename}. Please check whether module {modulename} actually exists."

When impementing this, please put new exceptions into `PyInstaller.exceptions`.

**Comment by Legorooj** [comment]
Good idea on this. I've dealt with many issues that are based around this. It took weeks to track the root ofsome of them down.

**Comment by motatoes** [comment]
This seems identical to https://github.com/pyinstaller/pyinstaller/issues/4537 so I think it is safe to close this one in favour of that which already has a PR being merged

**Comment by Legorooj** [comment]
@motatoes they're different issues; one is about hook utility functions, other general failure.

**Comment by htgoebel** [comment]
This issue basically says: In all hook utility functions, raise specific exceptions.
Maybe #4537 could also catch and report these errors? Nvertheless, the point here is to say "Utilty-function here. I found this issue: …" so developers can spot the relevant place quickly.

**Comment by colin-fsa** [comment]
Was this already completed? It looks like #5077 took care of it?

Current output from the original example:
`PyInstaller.exceptions.ImportErrorWhenRunningHook: Failed to import module __PyInstaller_hooks_0_pendulum required by hook for module c:\Development\pyinstaller\env\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pendulum.py. Please check whether module __PyInstaller_hooks_0_pendulum actually exists and whether the hook is compatible with your version of c:\Development\pyinstaller\env\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pendulum.py: You might want to read more about hooks in the manual and provide a pull-request to improve PyInstaller.`

**Comment by bwoodsend** [comment]
Yeah, I consider this one finished.
