### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by MaTianlai** [pyinstaller/pyinstaller#4540]
I install `pyinstaller` using pip:
`pip install pyinstaller --user`
And then, I pip listed, and discovered there is a pyinstaller there.
and then, I:
`pyinstaller /Users/alex/PycharmProjects/abc/abc.py`
but:
`-bash: pyinstaller: command not found`
What a fk?

**Comment by uriielfl** [comment]
try to use the command cd to your application folder like: 
![image](https://user-images.githubusercontent.com/49736581/70854019-e093d800-1e94-11ea-9509-badc01b5d476.png)

and then use the command. Instead of your directory, you just need to use the name of your application.py

**Comment by Legorooj** [comment]
It'll be because the command isn't available from your environment - virtual it not. This is not an issue with PyInstaller, it's an issue with your system.
