### ISSUE TITLE
Mac: --windowed app version could not run, --onefile could

### ISSUE THREAD

**Issue by Hordon13** [pyinstaller/pyinstaller#4547]
Hi,
I am not sure how I could debug this kind of behavior since I didn't get any error message and every version except the --windowed runs perfectly.

I use:

- Python 3.7.4
- Tkinter 8.6 via PySimpleGui
- latest PyInstaller
- latest macOS Catalina

I create the executables with the command:

`pyinstaller --onefile --windowed --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' --icon="/Users/hordon/Documents/app_icon.icns" my_app.py`

The bundling process runs without errors, I got the 2 files: the windowed Mac app and the simple command-line version one file. When I click the windowed one, the app popups a few times in the Dock like it should when launching an app but then nothing happens. The console version runs without any problem.

I checked the system.log and I got this entry every time I open the windowed:

`Nov 21 08:55:06 hordon com.apple.xpc.launchd[1] (user_interface.4992[49893]): Service exited with abnormal code: 255`

Do you have any suggestions on how to fix this? I'm not even sure that I messed up the packaging somehow or it's a bug.

**Comment by csatt** [comment]
This may be Issue #3820.

It is useful in debugging this kind of case to put your code in a "try" and in the "except" write the traceback to a file and then open that file in your editor.

See: https://github.com/pyinstaller/pyinstaller/issues/3820#issuecomment-702448356

**Comment by rokm** [comment]
The `tkinter` issues on macOS should now be fixed (see #5013, #5172, and #5175).

The `onedir`/`onefile` build working but `application bundle` not working is due to issue explained in #3820 and addressed by #5175, so I'm closing this issue. If your problem persists, please open a new issue with updated details.
