### ISSUE TITLE
Pyinstaller app doesn't launch, no error (worked previously)

### ISSUE THREAD

**Issue by conlin-matt** [pyinstaller/pyinstaller#4550]
Hello,

Thanks for developing and maintaining such a useful tool. I'm having what seems to be a strange issue and I'm hoping some expert advice could help me solve it. I have a PyQt app, e.g. this:
`   

    from PyQt5.QtWidgets import *
    from PyQt5.QtGui import QFont

    class WelcomeWindow(QWidget):
    
        def __init__(self):
            super().__init__()    
        
            if not QApplication.instance():
                app = QApplication(sys.argv)
            else:
                app = QApplication.instance()    
            
            
            # Left menu box setup #
            bf = QFont()
            bf.setBold(True)
            leftBar1 = QLabel('• Welcome!')
            leftBar1.setFont(bf)
            leftBar2 = QLabel('• Get imagery')
            leftBar3 = QLabel('• Get lidar data')
            leftBar4 = QLabel('• Pick GCPs')
            leftBar5 = QLabel('• Calibrate')
        
            leftGroupBox = QGroupBox('Contents:')
            vBox = QVBoxLayout()
            vBox.addWidget(leftBar1)
            vBox.addWidget(leftBar2)
            vBox.addWidget(leftBar3)
            vBox.addWidget(leftBar4)
            vBox.addWidget(leftBar5)
            vBox.addStretch(1)
            leftGroupBox.setLayout(vBox)
            ########################    
            
            # Right contents box setup #      
            txt = QLabel('Text1')
            txt2 = QLabel('Text2')      
            txt3 = QLabel('Text3')
            contBut = QPushButton('Continue >')
        
            rightGroupBox = QGroupBox()
            hBox1 = QHBoxLayout()
            hBox1.addWidget(txt3)
            hBox1.addWidget(contBut)
            vBox = QVBoxLayout()
            vBox.addWidget(txt)
            vBox.addWidget(txt2)
            vBox.addLayout(hBox1)
            rightGroupBox.setLayout(vBox)
            ############################
        
            # Connect widgets with signals #
            contBut.clicked.connect(self.StartTool)
            ################################
        
            # Full widget layout setup #
            fullLayout = QHBoxLayout()
            fullLayout.addWidget(leftGroupBox)
            fullLayout.addWidget(rightGroupBox)
            self.setLayout(fullLayout)

            self.setWindowTitle('Title')
            self.show()
            ###############################
         
        def StartTool(self):
            self.close()

    if __name__ == '__main__':
        import sys
        from PyQt5 import QtWidgets
    
        if not QtWidgets.QApplication.instance():
            app = QtWidgets.QApplication(sys.argv)
        else:
            app = QtWidgets.QApplication.instance()

        w = WelcomeWindow()
        sys.exit(app.exec_())`

I can successfully freeze this using `pyi-makespec --debug all --onefile -n test --icon icon3.ico test.py` and `pyinstaller test.py`. When I launch the program, however, whether it be through the command line or by running the app directly, the app fails to start. I don't get any error messages, the last 4 lines of the output are as follows:

`   

    # PyQt5.QtWidgets not found in PYZ

    [2820] LOADER: Back to parent (RC: -1073741819)

    [2820] LOADER: Doing cleanup

    [2820] LOADER: Freeing archive status for C:\Users\conli\Documents\SurfRCaT\dist\test.exe`

I'm on a Windows 10 machine, running Python 3.6 with Anaconda (64 bit). I've tried using the most recent development version of PyInstaller. I've tried creating a clean environment. I've tried invoking the app differently. I've tried using --onedir instead. All same result. The strangest part is that this worked just fine before my computer restarted. I'm at quite a loss here as to why the app refuses to launch- any ideas?

**Comment by rafael-mq** [comment]
I'm also facing this problem on some Windows 7 and Windows 10 computers.
Python 3.7.4 - 32bits
PyInstaller 4.0 dev
I'm building my program on a single executable.
I tried building it with debug mode on (--debug all) and at some point an error message appears saying it failed to execute script "pyiboot01_bootstrap" just like what was reported at #4213. 
I'm reaaly looking forward for an answer on this topic.

**Comment by rafael-mq** [comment]
> I'm also facing this problem on some Windows 7 and Windows 10 computers.
> Python 3.7.4 - 32bits
> PyInstaller 4.0 dev
> I'm building my program on a single executable.
> I tried building it with debug mode on (--debug all) and at some point an error message appears saying it failed to execute script "pyiboot01_bootstrap" just like what was reported at #4213.
> I'm reaaly looking forward for an answer on this topic.

I solved the problem in my case downgrading both Python to 3.6.8 and PyInstaller to 3.4.

**Comment by JarekParal** [comment]
I have the same issue. 
When I create an app with pyinstaller (setting `onefile`, `onedir` don't matter) and run the app, the app just opens a console window and without any message close the window. 
I tested it with Conda 32-bit, Python 3.6.4/3.7.4 and pyinstaller 3.4/3.5/3.6 and everytime a get the same behaviour.

For testing I used just simple script:
```python
# test.py file
if __name__ == '__main__':
    print('__main__ - start')
```

and call pyinstaller like that: `pyinstaller test.py` with `--onefile` or with `--onedir` flag.

In all of these configurations, the app just opens console windows and close. I also check the output with `--debug all`, where I got the same output as @conlin-matt:
```sh
[28600] LOADER: Running test.py
[28600] LOADER: OK.
[28600] LOADER: Cleaning up Python interpreter.
```

But when I move the `test.py` file to subfolder `test` and call the pyinstaller: `pyinstaller test\test.py` it suddenly solves this issue and the app start work (show the message `__main__ - start` in the console window).

Then this could be a workaround.

**Comment by Legorooj** [comment]
@JarekParal try opening a command prompt and running the exe from there - unless you were already doing that? And the subdir thing shouldn't change anything.

**Comment by JarekParal** [comment]
@Legorooj I'm not sure if I tried to run the app from command prompt but that isn't a solution for me. I moved the file `test.py` to a subfolder and it works well for me. But I had to change the `import` structure.

**Comment by Legorooj** [comment]
Hmm. Could you type out a file structure for us (For both the working and not working config)? Eg:
```
- data-folder
  - data-file.json
  - _another_data.yml
- my_module
  - __init__.py
- main.py
```
And tell us which pyinstaller command you used?

**Comment by JarekParal** [comment]
I tried to [create MCVE](https://github.com/JarekParal/pyinstaller-project-structure-issue) but I couldn't reproduce this issue on any simple MCVE, which mean that my previous comment about simple test file isn't correct:
```
# test.py file
if __name__ == '__main__':
    print('__main__ - start')
```

But I can still reproduce the issue in my code. As it is an internal project, I couldn't share the code base, but [I exported at least the build log files](https://github.com/JarekParal/pyinstaller-project-structure-issue/tree/build-files). 
I tried to build this project first time with file name `calmanimo.py` and second time with file `test.py`.
Second build works but the first not.

I found one difference in the `xref...` files:
1. https://github.com/JarekParal/pyinstaller-project-structure-issue/blob/build-files/build/calmanimo/xref-calmanimo.html
2. https://github.com/JarekParal/pyinstaller-project-structure-issue/blob/build-files/build/test/xref-test.html

But I don't understand what is the difference and if that could be an issue.

My project structure is:
```
- `test.py` or `calmanimo.py
- calmanimo folder
  - __init__.py
  - all other folders with implementation for this app 
```

The app is base on `WxPython` and I'm using `ctype` library for C DLL binding and `pythonnet` for C# DLL binding + other libraries specify in [environment.yml](https://github.com/JarekParal/pyinstaller-project-structure-issue/blob/build-files/environment.yml).

**Comment by Legorooj** [comment]
Wait a sec. Your saying the following folder structure doesn't work:

```
- calmanimo.py
- calmanimo (dir)
  - __init__.py
  - GUI.py
  - etc
```
Am I right?

**Comment by JarekParal** [comment]
Actually it is more like that:
```
- calmanimo.py
- calmanimo (dir)
  - __init__.py
  - gui (dir)
    - __init__.py
    - GUI.py
  - etc
```

But yes, you are right.

**Comment by Legorooj** [comment]
Try renaming `calmanimo.py` to `main.py` and building. Don't change anything else. @JarekParal

**Comment by JarekParal** [comment]
Yes, this seems to fix this issue. Do you know why that happens?

**Comment by Legorooj** [comment]
When you import `calmanimo`, python is trying to import itself, ie calmanimo.py. If you name a python file `os.py`, and try to import the `os` module, it'll fail. If you want the python file named that, change the name of the directory to something like `_calmanimo`

**Comment by Legorooj** [comment]
@conlin-matt have you tried with the latest version of PyInstaller?

**Comment by conlin-matt** [comment]
I haven't tried since November. I ended up having so many issues with this that I switched gears to fbs, a great package that puts a nice wrapper on Pyinstaller. That being aid, I've had success building some (simpler) apps with Pyinstaller since then, so I don't think whatever was going on here serves as an Issue for Pyinstaller anymore. As far as I'm concerned this issue seems resolved.

**Comment by Legorooj** [comment]
@conlin-matt I'll close then. In case you're interested, I've got a PyInstaller GUI I'm in late development stages with. It'll be released soon.
