### ISSUE TITLE
WARNING: Hidden import "distutils.command.build_ext" not found!

### ISSUE THREAD

**Issue by gitfourteen** [pyinstaller/pyinstaller#4553]
### Question
When running `pyinstaller -Fw xxx.py` with `virtual environment`, got the WARNING:
```
WARNING: Hidden import "distutils.command.build_ext" not found!
```
**Is this WARNNING a big deal? How to handle it?**

- Other problem
`app` did not work, exit immediately,  the same like[ this link](https://github.com/pyinstaller/pyinstaller/issues/4511#issue-515658690) reported.

<details>
<summary>
More INFO when running `pyinstaller`
</summary>
(XXX-project) ➜  XXX-project pyinstaller -Fw xxx.py

92 INFO: PyInstaller: 3.5
92 INFO: Python: 3.7.5
97 INFO: Platform: Darwin-19.0.0-x86_64-i386-64bit
98 INFO: wrote /Users/username/Downloads/XXX-project/xxx.spec
100 INFO: UPX is not available.
101 INFO: Extending PYTHONPATH with paths
['/Users/username/Downloads/XXX-project', '/Users/username/Downloads/XXX-project']
101 INFO: checking Analysis
110 INFO: Building because hookspath changed
110 INFO: Initializing module dependency graph...
112 INFO: Initializing module graph hooks...
114 INFO: Analyzing base_library.zip ...
2853 INFO: running Analysis Analysis-00.toc
2861 INFO: Caching module hooks...
2865 INFO: Analyzing /Users/username/Downloads/XXX-project/xxx.py
3297 INFO: Processing pre-find module path hook   distutils
3298 INFO: distutils: retargeting to non-venv dir '/Users/username/.pyenv/versions/3.7.5/Python.framework/Versions/3.7/lib/python3.7/distutils/__init__.py'
3864 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
4213 INFO: Processing pre-find module path hook   site
4214 INFO: site: retargeting to fake-dir '/Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_/lib/python3.7/site-packages/PyInstaller/fake-modules'
6139 INFO: Loading module hooks...
6139 INFO: Loading module hook "hook-pkg_resources.py"...
6481 INFO: Processing pre-safe import module hook   win32com
6541 INFO: Loading module hook "hook-_tkinter.py"...
6642 INFO: checking Tree
6665 INFO: checking Tree
6675 INFO: Loading module hook "hook-encodings.py"...
6726 INFO: Loading module hook "hook-setuptools.py"...

**6923 WARNING: Hidden import "distutils.command.build_ext" not found!**

7182 INFO: Loading module hook "hook-cv2.py"...
7183 INFO: Loading module hook "hook-sysconfig.py"...
7191 INFO: Loading module hook "hook-numpy.core.py"...
7362 INFO: Loading module hook "hook-xml.py"...
7402 INFO: Loading module hook "hook-pydoc.py"...
7403 INFO: Loading module hook "hook-numpy.py"...
7427 INFO: Looking for ctypes DLLs
7457 INFO: Analyzing run-time hooks ...
7461 INFO: Including run-time hook 'pyi_rth__tkinter.py'
7464 INFO: Including run-time hook 'pyi_rth_pkgres.py'
7466 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
7476 INFO: Looking for dynamic libraries
7986 INFO: Looking for eggs
7986 INFO: Using Python library /Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_/bin/../.Python

7994 INFO: Warnings written to /Users/username/Downloads/XXX-project/build/xxx/warn-xxx.txt

8037 INFO: Graph cross-reference written to /Users/username/Downloads/XXX-project/build/xxx/xref-xxx.html
8066 INFO: checking PYZ
8069 INFO: Building because toc changed
8069 INFO: Building PYZ (ZlibArchive) /Users/username/Downloads/XXX-project/build/xxx/PYZ-00.pyz
8710 INFO: Building PYZ (ZlibArchive) /Users/username/Downloads/XXX-project/build/xxx/PYZ-00.pyz completed successfully.
8725 INFO: checking PKG
8730 INFO: Building because toc changed
8730 INFO: Building PKG (CArchive) PKG-00.pkg
31299 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
31313 INFO: Bootloader /Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
31313 INFO: checking EXE
31318 INFO: Building because toc changed
31318 INFO: Building EXE from EXE-00.toc
31319 INFO: Appending archive to EXE /Users/username/Downloads/XXX-project/dist/xxx
31365 INFO: Fixing EXE for code signing /Users/username/Downloads/XXX-project/dist/xxx
31368 INFO: Building EXE from EXE-00.toc completed successfully.
31380 INFO: checking BUNDLE

35437 INFO: Building BUNDLE BUNDLE-00.toc
35542 INFO: moving BUNDLE data files to Resource directory
</details>

### Check `distutils` module
However, there does exist `distutils` folder in `virtual env`
```
(XXX-project) ➜  XXX-project find /Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_/ -name 'distutils'
/Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_//lib/python3.7/distutils
/Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_//lib/python3.7/site-packages/numpy/distutils
```

### Check `hook-distutils.py` file
```
(XXX-project) ➜  XXX-project find /Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_/ -name 'hook-distutils.py'
/Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_//lib/python3.7/site-packages/PyInstaller/hooks/hook-distutils.py
/Users/username/.local/share/virtualenvs/XXX-project-hvjEaZe_//lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py
```

### System info
`macOS Catalina`
`pyenv 1.2.15` + `pipenv version 2018.11.26` + `Python 3.7.5` to create virtual environment.
```
PyInstaller==3.5
  - altgraph [required: Any, installed: 0.16.1]
  - macholib [required: >=1.8, installed: 1.11]
    - altgraph [required: >=0.15, installed: 0.16.1]
  - setuptools [required: Any, installed: 42.0.1]
```

**Comment by astaruch** [comment]
I had similar a problem and found the issue https://github.com/pyinstaller/pyinstaller/issues/4064 where are some workarounds

**Comment by gitfourteen** [comment]
### Warning Issue addressed. Here is what I did. 

1. install an upgraded `Python 3.8.0` with **Pyenv**

2. `pipenv install` a virtualenv, `pipenv, version 2020.6.2`

```
➜  playpy pipenv graph
pyinstaller==4.0
  - altgraph [required: Any, installed: 0.17]
  - macholib [required: >=1.8, installed: 1.14]
    - altgraph [required: >=0.15, installed: 0.17]
  - pyinstaller-hooks-contrib [required: >=2020.6, installed: 2020.7]
  - setuptools [required: Any, installed: 49.2.1]
```

### Note
* Though virtualenv is `3.8.0`, the log info is NOT.
```
(playpy) ➜  playpy pipenv run pyinstaller -Fw sgqt_test.py
48 INFO: PyInstaller: 4.0
48 INFO: Python: 3.7.5
......
```
* We found one more line `pyinstaller-hooks-contrib` when `pipenv graph`
* `app` still could not work,  double click and exit immediately.


Anyway, I would like to close this issue.
