### ISSUE TITLE
Egg link no longer working

### ISSUE THREAD

**Issue by christina-zhou-96** [pyinstaller/pyinstaller#4554]
For the past month and a half I've used pyinstaller with no problem with an egg link to a utilities library I develop locally.

Today, I tried running the .exe after some code changes, and to my surprise the .exe didn't work. The program itself worked fine out of my IDE, just not from the pyinstaller .exe. The issue I got after running it in terminal was that my utilities module was not found.

I tried reverting to previous commits, but that didn't help. The path to my utilities library is there, same as always.

In the end I just copy pasted my library over to the top level directory of my app, which isn't the ideal solution because then I'd always be doing that rather than it dynamically checking for the latest updates.

I'm running python 3.7.4 and Windows 10. Let me know if you need me to provide any more detail.

**Comment by danyeaw** [comment]
@christina-zhou-96 If we are going to debug this, we would need a minimal example. This sounds like an issue with your local development environment, but if you can provide an example of egg links not working we could try to reproduce this.

**Comment by htgoebel** [comment]
No new information since 2 month. I assume this is solved.
