### ISSUE TITLE
install with pip fails if offline

### ISSUE THREAD

**Issue by carandraug** [pyinstaller/pyinstaller#4557]
Installing the latest release (v3.5) with pip fails if doing so offline.  To reproduce:

1. get a fresh windows install (I've done so with windows 10) on a computer without internet connection
2. install python (I installed version 3.7.5 from python.org)
3. download the [future](https://files.pythonhosted.org/packages/45/0b/38b06fd9b92dc2b68d58b75f900e97884c45bedd2ff83203d933cf5851c9/future-0.18.2.tar.gz), [pefile](https://files.pythonhosted.org/packages/36/58/acf7f35859d541985f0a6ea3c34baaefbfaee23642cf11e85fe36453ae77/pefile-2019.4.18.tar.gz), [pywin32_ctypes](https://files.pythonhosted.org/packages/9e/4b/3ab2720f1fa4b4bc924ef1932b842edf10007e4547ea8157b0b9fc78599a/pywin32_ctypes-0.2.0-py2.py3-none-any.whl), and [altgraph](https://files.pythonhosted.org/packages/0a/cc/646187eac4b797069e2e6b736f14cdef85dbe405c9bfc7803ef36e4f62ef/altgraph-0.16.1-py2.py3-none-any.whl) from PyPI
4. install each one with `pip install --no-index path-to-package`
5. download [PyInstaller](https://files.pythonhosted.org/packages/e2/c9/0b44b2ea87ba36395483a672fddd07e6a9cb2b8d3c4a28d7ae76c7e7e1e5/PyInstaller-3.5.tar.gz) from PyPI
6. install it with `pip install --no-index path-to-pyinstaller.tar.gz`

This errors with `Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions:none)`. Setuptools is definitely installed. I also upgrade the setuptools version that came with the python installation to the latest on PyPI which is 42.0.1 and the error continues.

I have worked around this by manually opening the tarball and running the setup.py instead of relying on pip. Windows does not have a program to extract tarballs so I used python for that too. LIke so:

```
$ python
>> import tarfile
>> t = tarfile.open('PyInstaller-3.5.tar.gz', 'mode='r|gz')
>> t.extractall()
>> exit()
$ cd PyInstaller-3.5
$ python setup.py install
```

**Comment by danyeaw** [comment]
@carandraug I don't think this is an issue with PyInstaller, this is just how pip works - it doesn't install packages when offline. There is an [issue](https://github.com/pypa/pip/issues/4753) about this on the pip repo, and they aren't planning on changing this behavior. You could setup your own [local index](https://packaging.python.org/guides/hosting-your-own-index/) on your computer as a workaround.

Since this isn't PyInstaller related, could you please close this Issue?

**Comment by carandraug** [comment]
> this is just how pip works - it doesn't install packages when offline.

pip does install packages when offline, I do it all the time. The steps I gave to reproduce this issue even install futures, pefile, pywin32_ctypes, and altgraph all offline. The issue you mention is about the behaviour of `--no-index` while configuring how to automatically find the packages.

The issue is about how installing PyInstaller with the `--no-index` option fails. Somehow it complains about lack of setuptools which is definitely installed. It may be a pip issue but it's odd that I've only seen it on PyInstaller.

**Comment by carandraug** [comment]
Here's the full error message and confirmation that setuptools is indeed installed:

```
$ pip3 list | grep setuptools
setuptools                                             40.8.0         
$ pip3 install --no-index PyInstaller-3.5.tar.gz 
Processing ./PyInstaller-3.5.tar.gz
  Installing build dependencies ... error
  Complete output from command /usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hy6jtfl4 --no-warn-script-location --no-binary :none: --only-binary :none: --no-index -- setuptools>=38.2.5 wheel:
  Collecting setuptools>=38.2.5
    Could not find a version that satisfies the requirement setuptools>=38.2.5 (from versions: )
  No matching distribution found for setuptools>=38.2.5
  
  ----------------------------------------
Command "/usr/bin/python3 -m pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-hy6jtfl4 --no-warn-script-location --no-binary :none: --only-binary :none: --no-index -- setuptools>=38.2.5 wheel" failed with error code 1 in None
```

As I mentioned above, I would be tempt to report this to pip but this I do this type of installation and all the time and it's the first time I've seen this which is why I'm thinking that it's PyInstaller doing something funny.

**Comment by danyeaw** [comment]
I don't think it is something funny, PyInstaller depends on setuptools. Did you download setuptools and use `pip install --find-links /path/to/setuptools PyInstaller-3.5.tar.gz`?

**Comment by carandraug** [comment]
setuptools is already installed, as show in the output of `pip list`, so I shouldn't have to download it again.

I noticed the use of pip of `--ignore-installed` and found on pip where that came from. PEP517 suggests that the package build should be done on an isolated environment which pip does by using `--ignore-installed`.

So it works again by using the `--no-build-isolation` flag, like so:

```
$ pip install --no-index --no-build-isolation PyInstaller-3.5.tar.gz
```

**Comment by danyeaw** [comment]
Glad you resolved this :+1:

**Comment by fhabermacher** [comment]
> setuptools is already installed, as show in the output of `pip list`, so I shouldn't have to download it again.
> 
> I noticed the use of pip of `--ignore-installed` and found on pip where that came from. PEP517 suggests that the package build should be done on an isolated environment which pip does by using `--ignore-installed`.
> 
> So it works again by using the `--no-build-isolation` flag, like so:
> 
> ```
> $ pip install --no-index --no-build-isolation PyInstaller-3.5.tar.gz
> ```

Thanks @carandraug, I had a very similar issue with setuptools being installed but not being properly recognized/used (when installing sqlalchemy offline on windows), and simply adding your `--no-build-isolation` in `pip install -r requirements.txt --no-index --find-links=whl\ --no-build-isolation` or in `pip install sqlalchemy --no-index --find-links=whl\ --no-build-isolation` saved me

**Comment by Seaseemy** [comment]
> setuptools is already installed, as show in the output of `pip list`, so I shouldn't have to download it again.
> 
> I noticed the use of pip of `--ignore-installed` and found on pip where that came from. PEP517 suggests that the package build should be done on an isolated environment which pip does by using `--ignore-installed`.
> 
> So it works again by using the `--no-build-isolation` flag, like so:
> 
> ```
> $ pip install --no-index --no-build-isolation PyInstaller-3.5.tar.gz
> ```
> this really help me, thanks a lot
