### ISSUE TITLE
--noconfirm hint printed even when --noconfirm option is used

### ISSUE THREAD

**Issue by tinjaw** [pyinstaller/pyinstaller#4558]
Use the --noconfirm option for pyinstaller and the hint for its usage is printed.

**Comment by danyeaw** [comment]
@tinjaw I have noticed this as well. Are you interested in submitting a PR?

**Comment by Legorooj** [comment]
@tinjaw thanks for letting us know.  I'm going to close this issue, as I've tracked it down and will include it in my next PR
