### ISSUE TITLE
WARNING: file already exists but should not: C:\Users\320068~1\AppData\Local\Temp\_MEI1103602\torch\_C.cp37-win_amd64.pyd

### ISSUE THREAD

**Issue by Araid0628** [pyinstaller/pyinstaller#4561]
Python version: 3.7
pyinstaller version: 3.5 / develop (tried both)

I trained a segmentation model with PyTorch and built a GUI with PyQt. 
When I run pyinstaller command in Anaconda Prompt(gui.py is the GUI):

`pyinstaller -F -w gui.py`

It worked. But when I click the EXE file, it shows the following error message:

`WARNING: file already exists but should not: C:\Users\320068~1\AppData\Local\Temp\_MEI1103602\torch\_C.cp37-win_amd64.pyd`

**Comment by Araid0628** [comment]
I used ONXX to transform PyTorch model and avoided this warning.

**Comment by ChenyijunAaron** [comment]
I got the same problem

**Comment by ChenyijunAaron** [comment]
use --onedir instead of --onefile can avoid this problem.

**Comment by kcsekhar14** [comment]
Still i didn't work for me, still it is showing warning when i click on the exe file to open

**Comment by fu050409** [comment]
I got the same: [46296] WARNING: file already exists but should not: C:\Users\12935\AppData\Local\Temp\_MEI462962\Crypto\Cipher\_AES.cp36-win_amd64.pyd

**Comment by kk0087** [comment]
> I got the same: [46296] WARNING: file already exists but should not: C:\Users\12935\AppData\Local\Temp_MEI462962\Crypto\Cipher_AES.cp36-win_amd64.pyd

Maybe crypto and pycryptodome are both installed and conflicted

**Comment by jugal5** [comment]
I'm also facing the same issue. The .exe file created but as soon as i open the file it gives error.

[13868] WARNING: file already exists but should not: C:\Users\user1\AppData\Local\Temp\_MEI138682\torch\_C.cp38-win_amd64.pyd
Traceback (most recent call last):
  File "site-packages\torch\_utils_internal.py", line 46, in get_source_lines_and_file
  File "inspect.py", line 967, in getsourcelines
  File "inspect.py", line 798, in findsource
OSError: could not get source code

**Comment by kk0087** [comment]
Jugal Nathani <notifications@github.com> 于 2020年6月2日周二 下午10:53写道：

**Comment by bfoe** [comment]
try to include the following in your .spec file:

#avoid warning
for d in a.datas:
    if '_C.cp37-win_amd64.pyd' in d[0]: 
        a.datas.remove(d)
        break

**Comment by super233** [comment]
> try to include the following in your .spec file:
> 
> #avoid warning
> for d in a.datas:
> if '_C.cp37-win_amd64.pyd' in d[0]:
> a.datas.remove(d)
> break

Thanks, save my days, may be this is better readable:
```python
for d in a.datas:
    if '_C.cp37-win_amd64.pyd' in d[0]:
        a.datas.remove(d)
        break
```

**Comment by cnstntn-kndrtv** [comment]
Not a good idea - remove part of the list that you are iterating.  
  
```python
from PyInstaller.building.datastruct import TOC

# ...
# a = Analysis(...)

x = 'cp36-win_amd64'
datas_upd = TOC()

for d in a.datas:
    if x not in d[0] and x not in d[1]:
        datas_upd.append(d)

a.datas = datas_upd

```
