### ISSUE TITLE
Incorrect platform.dist() when running with PyInstaller

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#4562]
I'm facing a wired bug when using `platform` module to get the system platform, I'm using a docker with precompiled python 2.7.16 with `PyInstaller` to build a Linux executable for my app, when doing this the result of `platform.dist()` is incorrect on the target machine, this is a simple example:
```
import platform
print(platform.dist())
```
When building this with `PyInstaller` in the container and running on a `Ubuntu 16` server this is  the result:
```
ubuntu:~$ test_dist/test_dist
('debian', 'stretch/sid', '')
```
When running from `Python`
```
ubuntu:~$ python -c "import platform; print(platform.dist())"
('Ubuntu', '16.04', 'xenial')
```
The incorrect platform result is the same on the container.

When using the `distro` module with `distro.linux_distribution()` it is working on the target machine as expected:
```
ubuntu:~$ test_distro/test_distro
(u'Ubuntu', u'16.04', u'xenial')
```

Is the `platfom` module pre-compile something in the executable?

**Comment by danyeaw** [comment]
@arossert Thanks for submitting the Issue, that is a weird one, since I'm not sure why PyInstaller would be messing with that. Does `platform.linux_distribution()` work correctly? `platform.dist()` was deprecated in Python 2.6 which was 11 years ago.

**Comment by arossert** [comment]
@danyeaw thanks for the replay, I forgot to mention that the build is done on an old `ubuntu 10.04` docker image, I'm doing this to support old distro with old `glibc` version.

this is a small example:
```
import distro
import platform

print("platform.dist:               " + str(platform.dist()))
print("platform.linux_distribution: " + str(platform.linux_distribution()))
print("distro.linux_distribution:   " + str(distro.linux_distribution()))
```

When running this on the same container:
```
platform.dist:               ('debian', 'squeeze/sid', '')
platform.linux_distribution: ('debian', 'squeeze/sid', '')
distro.linux_distribution:   ('', '', '')
```

When running this on a different `ubuntu 18.04` container:
```
platform.dist:               ('debian', 'buster/sid', '')
platform.linux_distribution: ('debian', 'buster/sid', '')
distro.linux_distribution:   (u'Ubuntu', u'18.04', u'bionic')
```

Is it possible that the `platform` module is saving the information from the compiled machine? 
Maybe it is because this is a Python version that was compiled from the source (maybe some flags that I need to pass during build time)?

**Comment by rokm** [comment]
> Is it possible that the platform module is saving the information from the compiled machine?
Maybe it is because this is a Python version that was compiled from the source (maybe some flags that I need to pass during build time)?

The difference in behavior is result of Ubuntu 18.04 (and probably 16) patching their python to provide correct identification.

Here's the original [platform.linux_distribution implementation from Python 2.7.17](https://github.com/python/cpython/blob/v2.7.17/Lib/platform.py#L325-L377):

<details><summary>Code</summary>
<p>

```python
def linux_distribution(distname='', version='', id='',


                       supported_dists=_supported_dists,
                       full_distribution_name=1):


    """ Tries to determine the name of the Linux OS distribution name.

        The function first looks for a distribution release file in
        /etc and then reverts to _dist_try_harder() in case no
        suitable files are found.

        supported_dists may be given to define the set of Linux
        distributions to look for. It defaults to a list of currently
        supported Linux distributions identified by their release file
        name.

        If full_distribution_name is true (default), the full
        distribution read from the OS is returned. Otherwise the short
        name taken from supported_dists is used.

        Returns a tuple (distname,version,id) which default to the
        args given as parameters.

    """
    try:
        etc = os.listdir('/etc')
    except os.error:
        # Probably not a Unix system
        return distname,version,id
    etc.sort()
    for file in etc:
        m = _release_filename.match(file)
        if m is not None:
            _distname,dummy = m.groups()
            if _distname in supported_dists:
                distname = _distname
                break
    else:
        return _dist_try_harder(distname,version,id)


    # Read the first line
    f = open('/etc/'+file, 'r')
    firstline = f.readline()
    f.close()
    _distname, _version, _id = _parse_release_file(firstline)


    if _distname and full_distribution_name:
        distname = _distname
    if _version:
        version = _version
    if _id:
        id = _id
    return distname, version, id
```

</p>
</details>

So what this does it, it goes over all files in `/etc` and picks up the first one that matches `_release_filename = re.compile(r'(\w+)[-_](release|version)')` regex. On Ubuntu 18.04, the matching files are `/etc/debian_version`, `/etc/lsb-release`, and `/etc/os-release`. So it ends up picking `debian_version`, which contains `buster/sid`. (And `platform.dist` is just a wrapper for `platform.linux_disribution`, so it gives the same result).

That's why Ubuntu python patches their python 2.7.17 `platform.linux_distribution` to explicitly check `/etc/lsb-release` first:

<details><summary>Code</summary>
<p>

```python
def linux_distribution(distname='', version='', id='',

                       supported_dists=_supported_dists,
                       full_distribution_name=1):

    """ Tries to determine the name of the Linux OS distribution name.

        The function first looks for a distribution release file in
        /etc and then reverts to _dist_try_harder() in case no
        suitable files are found.

        supported_dists may be given to define the set of Linux
        distributions to look for. It defaults to a list of currently
        supported Linux distributions identified by their release file
        name.

        If full_distribution_name is true (default), the full
        distribution read from the OS is returned. Otherwise the short
        name taken from supported_dists is used.

        Returns a tuple (distname,version,id) which default to the
        args given as parameters.

    """
    # check for the LSB /etc/lsb-release file first, needed so
    # that the distribution doesn't get identified as Debian.
    try:
        with open("/etc/lsb-release", "rU") as etclsbrel:
            for line in etclsbrel:
                m = _distributor_id_file_re.search(line)
                if m:
                    _u_distname = m.group(1).strip()
                m = _release_file_re.search(line)
                if m:
                    _u_version = m.group(1).strip()
                m = _codename_file_re.search(line)
                if m:
                    _u_id = m.group(1).strip()
            if _u_distname and _u_version:
                return (_u_distname, _u_version, _u_id)
    except (EnvironmentError, UnboundLocalError):
        pass

    try:
        etc = os.listdir('/etc')
    except os.error:
        # Probably not a Unix system
        return distname,version,id
    etc.sort()
    for file in etc:
        m = _release_filename.match(file)
        if m is not None:
            _distname,dummy = m.groups()
            if _distname in supported_dists:
                distname = _distname
                break
    else:
        return _dist_try_harder(distname,version,id)

    # Read the first line
    f = open('/etc/'+file, 'r')
    firstline = f.readline()
    f.close()
    _distname, _version, _id = _parse_release_file(firstline)

    if _distname and full_distribution_name:
        distname = _distname
    if _version:
        version = _version
    if _id:
        id = _id
    return distname, version, id
```

</p>
</details>

So if you're freezing on Debian (or an old version of Ubuntu that did not patch their python), your frozen application will end up using the original, unpatched implementation of `platform.linux_distribution` that will report the Ubuntu system as a Debian one.
