### ISSUE TITLE
Initial startup time with --onedir

### ISSUE THREAD

**Issue by saschahofmann** [pyinstaller/pyinstaller#4563]
I was observing long startup times for my packaged executable. We were packaging as `--onefile` and had startup times of over a minute. So after reading up on it, I decided to use the "one direction" option instead. Now I am curious, when I run the executable for the first time I still have a similar length startup time as before. But consecutive runs are starting in the second range. 

It looks to me like the bootloader is still unpacking some packages but persists the results rather than deleting the tmp folder as for a --onefile packaged executable. Is that correct?
Just in case, here is my pyinstaller command:
```bash
pyinstaller --additional-hooks-dir=src/hooks \
                -p=./src/core  \
                -n="App" \
                --add-data=./src/core/formula/formula.lark:./core/formula \
                ./src/prod.py
```
pyinstaller version is 3.5, python 3.7.3

**Comment by danyeaw** [comment]
@saschahofmann Does using --noarchive impact initial start performance?

**Comment by Legorooj** [comment]
@saschahofmann with `--onedir` the longer startup time is to do with caching, size of the app, etc. There are loads of factors. But `--onedir` will always be faster than `--onefile`. There is a PR that is adding a splash screen option, that shows a splash screen while starting up.
