### ISSUE TITLE
How to include opencv when compiled from source??

### ISSUE THREAD

**Issue by krunal704** [pyinstaller/pyinstaller#4564]
I have installed OpenCV v4.1 from source. I have created binary file using PyInstaller. While running binary file it give Improt Error.
`ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.`

Platform: Jetson Nano running on Ubuntu 18.04
Python 3.6
OpenCV 4.1 (compiled from source)
PyInstaller 3.5

I know OpenCV is not listed in supported package list but is there any workaround to include OpenCV?

**Comment by chalesguo** [comment]
The same problem, I hope there is a solution

**Comment by krunal704** [comment]
@chalesguo Yes, there is a solution for this,
Get the path of CV2 using python
```
import cv2
print(cv2.__file__)
# /usr/local/lib/python3.6/dist-packages/cv2/python-3.6/cv2.so
```
include this cv2 installation path as --paths in pyinstaller
pyinstaller main.py -n myApp --paths="/usr/local/lib/python3.6/dist-packages/cv2/python-3.6"

I hope this works for you also

**Comment by dhgokul** [comment]
@krunal704  I am also facing same issue. after include paths argument 

Platform: Jetson Nano running on Ubuntu 18.04 - jetson pack (4.4)
>>> import cv2
>>> cv2.__version__
'4.3.0'
>>> print(cv2.__file__)
/root/opencv-4.3.0/release/lib/python3/cv2.cpython-36m-aarch64-linux-gnu.so

**cmd:**
pyinstaller --onefile sample.py --paths "/root/opencv-4.3.0/release/lib/python3/cv2.cpython-36m-aarch64-linux-gnu.so"


**Error :**
Traceback (most recent call last):
  File "tt.py", line 12, in <module>
    import cv2
  File "/usr/local/lib/python3.6/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "cv2/__init__.py", line 96, in <module>
  File "cv2/__init__.py", line 58, in bootstrap
  File "cv2/__init__.py", line 56, in load_first_config
ImportError: OpenCV loader: missing configuration file: ['config.py']. Check OpenCV installation.

**Comment by KimYC1223** [comment]
Hi, @dhgokul 

I think your path is wrong.

try this :

```pyinstaller --onefile sample.py --paths "/root/opencv-4.3.0/release/lib/python3/cv2"```

not this :

```pyinstaller --onefile sample.py --paths "/root/opencv-4.3.0/release/lib/python3/cv2.cpython-36m-aarch64-linux-gnu.so"```

**Comment by FatemehEsfahani** [comment]
@KimYC1223 I have the same problem. I get the following for path to my cv2:
C:/Users/simin/anaconda3/Lib/site-packages/cv2\python-3.8\cv2.cp38-win_amd64.pyd
I tried this: pyinstaller --onefile untitled3.py --paths "C:/Users/simin/anaconda3/Lib/site-packages/cv2", but still I get the same error. I am on windows. Do you know how I can solve this? Thank you.

**Comment by terrynx** [comment]
> @KimYC1223 I have the same problem. I get the following for path to my cv2:
> C:/Users/simin/anaconda3/Lib/site-packages/cv2\python-3.8\cv2.cp38-win_amd64.pyd
> I tried this: pyinstaller --onefile untitled3.py --paths "C:/Users/simin/anaconda3/Lib/site-packages/cv2", but still I get the same error. I am on windows. Do you know how I can solve this? Thank you. I am on windows.

你好，我也遇到了相似的问题，请问你解决了么？

**Comment by pwuertz** [comment]
I wonder if we can find a proper solution by adding a fix for this problem within a cv2 hook.

Could we detect the presence of those OpenCV import wrapper scripts in a hook script and bypass them by delegating the cv2 import to the so/pyd module?

**Comment by FatemehEsfahani** [comment]
For me the following worked:
import cv2
print(cv2.__file__)
then I got this output: C:/Users/PC/anaconda3/Lib/site-packages/cv2/python-3.8/cv2.cp38-win_amd64.pyd
Also, you need to find the path to OpenCV libraries. For me it is located at: C:\Users\PC\OpenCV\build\install\x64\vc16\bin
Next, in python environment I cd to the directory where my python is. Then,
``
pyinstaller --onedir filename.py --paths "C:\Users\PC\anaconda3\Lib\site-packages\cv2\python-3.8" --paths       "C:\Users\PC\OpenCV\build\install\x64\vc16\bin"
``
It solved my problem.

**Comment by pwuertz** [comment]
@FatemehEsfahani Right, this is a manual workaround to make sure that pyinstaller only sees the compiled cv2 module on `import cv2`, not the OpenCV loader script.

I was thinking about a more permanent solution via `hook-cv2.py`. Nowadays all the module specific fixes are maintained at https://github.com/pyinstaller/pyinstaller-hooks-contrib, with a [hook-cv2.py](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cv2.py) apparently already present for fixing a problem with `opencv_videoio_ffmpeg*.dll` on Windows.

I opened an issue there https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/110.

**Comment by Mithranda** [comment]
I got a different problem when i installed OpenCV v4.5.4 from source and try to use it in pyinstaller, and i think the it is the same kind of problem.
OpenCV v4.5.4
Python 3.9.9
Pyinstaller 4.8
OpenCV v4.5.4 from source run in pycharm is no problems,but when i try to pick it to my exe, i got this problem and troubled me for a week.
Locate to if only import cv2,this problem will be happened.
**This is the track:**
['D:\\CodeProject\\Python\\CamerasTrack\\test\\dist\\cvtest\\base_library.zip', 'D:/opencv-4.5.4/build/lib/python3/Release', 'D:\\CodeProject\\Python\\CamerasTrack\\test\\dist\\cvtest\\lib-dynload', 'D:\\CodeProject\\Python\\CamerasTrack\\test\\dist\\cvtest']
Traceback (most recent call last):
  File "cvtest.py", line 5, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "cv2\__init__.py", line 180, in <module>
    bootstrap()
  File "cv2\__init__.py", line 152, in bootstrap
    native_module = importlib.import_module("cv2")
  File "importlib\__init__.py", line 127, in import_module
  File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
  File "cv2\__init__.py", line 180, in <module>
    bootstrap()
  File "cv2\__init__.py", line 75, in bootstrap
    raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.')
ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

**Comment by mj-haghighi** [comment]
> I got a different problem when i installed OpenCV v4.5.4 from source and try to use it in pyinstaller, and i think the it is the same kind of problem. OpenCV v4.5.4 Python 3.9.9 Pyinstaller 4.8 OpenCV v4.5.4 from source run in pycharm is no problems,but when i try to pick it to my exe, i got this problem and troubled me for a week. Locate to if only import cv2,this problem will be happened. **This is the track:** ['D:\CodeProject\Python\CamerasTrack\test\dist\cvtest\base_library.zip', 'D:/opencv-4.5.4/build/lib/python3/Release', 'D:\CodeProject\Python\CamerasTrack\test\dist\cvtest\lib-dynload', 'D:\CodeProject\Python\CamerasTrack\test\dist\cvtest'] Traceback (most recent call last): File "cvtest.py", line 5, in File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module File "cv2__init__.py", line 180, in bootstrap() File "cv2__init__.py", line 152, in bootstrap native_module = importlib.import_module("cv2") File "importlib__init__.py", line 127, in import_module File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module File "cv2__init__.py", line 180, in bootstrap() File "cv2__init__.py", line 75, in bootstrap raise ImportError('ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.') ImportError: ERROR: recursion is detected during loading of "cv2" binary extensions. Check OpenCV installation.

I had the same issue with 'Pyinstaller':
os==windows10
python==3.7.4
Pyinstaller==5.2
opencv-python==4.6

+ --path to cv2 in site-package
+ installing opencv-python-headless instead

not worked for me ...

thanks to  [SimonAlpaca](https://www.reddit.com/user/SimonAlpaca/) to share solution in [reddit](https://www.reddit.com/r/learnpython/comments/r1yk9o/is_opencv_and_pyinstaller_not_compatible/).
opencv-python==4.5.3.56 is compatible with the configs above.

**Comment by inacio-dev** [comment]
to use cv2 with pyinstaller I used the command 'pyinstaller --windowed --noconsole main.py --paths="C:\Users\[name]\AppData\Local\Programs\Python\Python310\Lib\site-packages \cv2" --exclude-module _bootlocale'. Then I opened the 'main' folder and deleted all the files from the 'cv2' folder and pasted the 'opencv_videoio_ffmpeg460_64.dll' file in 'cv2' folder. And it worked.
