### ISSUE TITLE
cannot not open self xxxx.vmp.exe or archive xxx.vmp.pkg after i use vmprotect

### ISSUE THREAD

**Issue by appleUserName** [pyinstaller/pyinstaller#4567]
python 3.7
pyinstaller 3.5
pyqt5 5.13
I created an exe file, on my system with Windows 7 and it worked, but after i use vmp, everything changed. I get an error 'cannot not open self xxx.vmp.exe or archive xxx.vmp.pkg', and i donot know how to fix it. Did it need something special setting when i pyinstalling???

**Comment by amifunny** [comment]
@bwoodsend @Legorooj was it resolved in the new version?

**Comment by bwoodsend** [comment]
> was it resolved 

I can't actually tell what *it* was so your guess is as good as mine - probably no. @appleUserName If you're still with us we'd need quite a bit more info than what you've provided. See the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by wangyexiang** [comment]
Dear sir. Is it resolved？@appleUserName

**Comment by rokm** [comment]
I doubt VMP is compatible with PyInstaller-generated executables. Modifying the executable may prevent PyInstaller's bootloader from discovering and loading its executable-embedded archive (which in this case is probably transformed/encrypted by VMP anyway). Hence the `cannot open self xxx.vmp.exe or archive xxx.vmp.pkg'` error.

I suppose one could generate executable without embedded archive (i.e., using archive side-loading), but then the executable will be just plain bootloader executable, and there would be nothing for VMP to really "protect"...
