### ISSUE TITLE
Keyring hook does not work

### ISSUE THREAD

**Issue by toyg** [pyinstaller/pyinstaller#4569]
Environment: 
- MacOS 10.14.6
- Python 3.7.4 (from homebrew)
- PyInstaller==4.0.dev0+9dd34bdfba
- keyring==20.0.0

Configure the virtualenv with keyring and pyinstaller
```bash
python3 -m venv venv
source ./venv/bin/activate
pip install keyring 
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

Have a simple file called `test.py`:
```python
import keyring
print(keyring.get_password('test','test'))
```
This prints "None" when executed.

Package it and run:
```bash
pyinstaller --clean --log-level DEBUG -d all --noupx -y test.py
```

Build log: https://pastebin.com/raw/VeEtsZge
Content of build and dist: https://www.dropbox.com/s/79s7fe8dpkij717/pyinstbug.tgz?dl=1

Result:
```
$> ./dist/test/test

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/toyg/Dev/tmp/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "keyring/__init__.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "/Users/toyg/Dev/tmp/venv/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "keyring/core.py", line 192, in <module>
  File "keyring/core.py", line 96, in init_backend
  File "keyring/util/__init__.py", line 22, in wrapper
  File "keyring/backend.py", line 216, in get_all_keyring
  File "keyring/backend.py", line 199, in _load_plugins
KeyError: 'keyring.backends'
[55646] Failed to execute script test
```

From the various logs it looks like keyring is somewhat detected, but then it's not actually fully imported at runtime. I have tried explicitly setting all keyring submodules as hiddenimports, it does not make any difference.

**Comment by anasofiapaixao** [comment]
For reference for anyone who like me landed here out of the blue, @msk849 has submitted a [PR for this issue](https://github.com/jaraco/keyring/pull/416), and until it makes its way to master to keyring release to pyinstaller to pyinstaller release to pypi, ...... there's a horrible workaround to get it to work _right now_ that in theory you should not do, which is altering the library yourself with the contents of their PR directly in your own `site-packages` python package cache.

Open `site-packages/keyring-x.x.x-pyx.x.egg/keyring/backend.py` and replace
```
    entry_points = metadata.entry_points()['keyring.backends']
```
with
```
    try: entry_points = metadata.entry_points()['keyring.backends']
    except Exception:
        entry_points = (
            metadata.EntryPoint(name='KWallet',value='keyring.backends.kwallet',group='keyring.backends'),
            metadata.EntryPoint(name='SecretService',value='keyring.backends.SecretService',group='keyring.backends'),
            metadata.EntryPoint(name='Windows',value='keyring.backends.Windows',group='keyring.backends'),
            metadata.EntryPoint(name='chainer',value='keyring.backends.chainer',group='keyring.backends'),
            metadata.EntryPoint(name='macOS',value='keyring.backends.OS_X',group='keyring.backends'))
```
which should be around line 199.

Clear pyinstaler build and dist cache, rerun pyinstaller, and the error should be gone.

**Comment by arossert** [comment]
@anasofiapaixao thanks for the update, I'm facing the same issue.
Is there anything that can be done in a PyInstaller hook to overcome this issue?
My issue is that I'm currently using Python2 and even if this fix will find its way to master it will only be for Python3 (18.0.1 is the last release that supports Python2).

**Comment by reactivatecx** [comment]
Doesn't look like that Keyring PR is going to be merged, maintainers have mentioned that PyInstaller should be able to follow [these instructions](https://docs.python.org/3/library/importlib.metadata.html#extending-the-search-algorithm) to improve the discoverability of the metadata.

**Comment by MAKOMO** [comment]
Newer Keyrings also fail to work in apps bundled with py2app. Can't find any workaround despite modifying the keyring lib. Monkey patching seems not to be possible.  So I downgrade to `keyring==19.2.0` again. Bad.

**Comment by DK26** [comment]
BTW, stumbling upon this error myself while I'm also learning the Rust programming language (A systems language like C\C++), I've made an attempt to port Rust's own most popular keyring library to Python and it seems to be working fine with PyInstaller.
It's cross-platform as well but I've mainly tested it on windows.

`pip install rskeyring`

**Comment by anatolio-deb** [comment]
> BTW, stumbling upon this error myself while I'm also learning the Rust programming language (A systems language like C\C++), I've made an attempt to port Rust's own most popular keyring library to Python and it seems to be working fine with PyInstaller.
> It's cross-platform as well but I've mainly tested it on windows.
> 
> `pip install rskeyring`

Thank you for your workaround. Does it support Linux platforms? Secret Service or KWallet?

**Comment by DK26** [comment]
> > BTW, stumbling upon this error myself while I'm also learning the Rust programming language (A systems language like C\C++), I've made an attempt to port Rust's own most popular keyring library to Python and it seems to be working fine with PyInstaller.
> > It's cross-platform as well but I've mainly tested it on windows.
> > 
> > `pip install rskeyring`
> 
> Thank you for your workaround. Does it support Linux platforms? Secret Service or KWallet?  

Since it was created mainly for a workaround for PyInstaller to create windows EXE, it was not well tested on Linux. It does compile on Linux and the underlying `keyring` does support Linux. I think it uses `SecretService`. You may try
