### ISSUE TITLE
I can't seem to install pyinstaller on MSYS2

### ISSUE THREAD

**Issue by iheartcoffee** [pyinstaller/pyinstaller#4570]
```
$ pip install pyinstaller
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/e2/c9/0b44b2ea87ba36395483a672fddd07e6a9cb2b8d3c4a28d7ae76c7e7e1e5/PyInstaller-3.5.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3.exe /usr/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpd14xppal
       cwd: /tmp/pip-install-pz_0neg3/pyinstaller
  Complete output (1 lines):
  Your platform is not yet supported. Please define constant PYDYLIB_NAMES for your platform.
  ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3.exe /usr/lib/python3.7/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmpd14xppal Check the logs for full command output.
```

That's the error I get

------------------------

If you have problems to get your application running, please first

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

* make sure everything is packaged correctly
  https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly

If your problem persists, please provide all information as stated in our "How to Report Bugs" guide.
https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs.
The help for GitHub's text-editor is hidden behind "Styling with Markdown is
supported" just below the edit-box.

**Otherwise we will not be willing to help you.**

Please be aware that PyInstaller is a voluntary project. We spent quite some time
writing these guides to make both of our lives easier. Please
understand that we are not willing to spend our spare time to help you if you
are not willing to help on your side. (Sorry for having to said this, but we
are tired of being asked the same questions over and over again.)

**Comment by seanmadawala** [comment]
I get a similar error. I don't know why. I tried compiling the bootloader too but I still get errors.

**Comment by danyeaw** [comment]
@iheartcoffee Can we close this issue as well now that your msys2 issues are resolved?

**Comment by iheartcoffee** [comment]
@danyeaw yes, you may close this issue
