### ISSUE TITLE
Skip automatic source selection, specify source manually

### ISSUE THREAD

**Issue by looooo** [pyinstaller/pyinstaller#4571]
Is it possible to select sources manually and use a bat file as initialization script?

I would like to select a conda environment as the source directory and use a bat file to initialize an executable inside the environment. We are doing this for Linux with appimages [1] and for osx with .app bundle [2]. But we are struggling to do the same for windows.
So what we need is:
1. Select sources manually
2. Use bat/bash file as entry point instead of a py file

If this is possible I guess we could use pyinstaller for all 3 platforms.

[1] https://github.com/FreeCAD/FreeCAD-AppImage/blob/master/conda/linux_dev/linux_dev.sh
[2] https://github.com/FreeCAD/FreeCAD-AppImage/blob/master/conda/osx_dev/osx_dev.sh

**Comment by bwoodsend** [comment]
No.
