### ISSUE TITLE
binary crashes when using multidict >= 4.7

### ISSUE THREAD

**Issue by etam** [pyinstaller/pyinstaller#4572]
I have followed "When Things Go Wrong" and "How to Report Bugs > Before submitting a report".

## What is the exact problem?

When running application using multidict >= 4.7 and packaged with pyinstaller, it crashes on startup (`Segmentation fault (core dumped)`). Multidict version 4.6.1 works fine. Changelog for 4.7 says "Replace Cython optimization with pure C".

It may be important, that if application is built with `--debug=all`, when running it shows
```
# multidict._multidict not found in PYZ
# multidict._multidict_base not found in PYZ
```

## Software versions you are using.

I have it reproduced with Python 3.6 on Linux, Windows and MacOS. I also checked this with Python 3.7 on Linux. 
I tried pyinstaller versions 3.5 and development (currently 4.0.dev0+9dd34bdfba).
I tried multidict 4.6.1, 4.7.0 and 4.7.1.

## A minimal example program which shows the error. Ideally this is a one-liner :-)

main.py:
``` python
import multidict
```

compile (all flags are optional, because I haven't found anything changed, except for more debugging output): 
``` shell
pyinstaller --log-level=DEBUG --debug=all --onedir --noupx main.py
```
Output: [compilation.log](https://github.com/pyinstaller/pyinstaller/files/3956318/compilation.log)

run:
``` shell
./dist/main/main
```
Output: [running.log](https://github.com/pyinstaller/pyinstaller/files/3956319/running.log)

**Comment by fivepapertigers** [comment]
Can confirm that I am experience the same issue - took me a while to track it down.

**Comment by Legorooj** [comment]
Hi guys. Sorry for this getting minimal attention - there are alot of issues here and they can get buried. This looks like you need a hook file for `multidict` now, or the current one needs updating. I'll look into it.

**Comment by Legorooj** [comment]
Ok this issue has been picked up by the multidict developers a few months ago. 

Please try with `multidict==4.7.4`. If that doesn't fix it, then you need to write a custom hook (see [here](https://pyinstaller.readthedocs.io/en/stable/hooks.html))
