### ISSUE TITLE
macOS icon not working properly

### ISSUE THREAD

**Issue by DinRigtigeFar** [pyinstaller/pyinstaller#4574]
When I try to add an icon to my app it doesn't work. Instead it shows the default icon.

I'm using PyInstaller 3.5 and Python 3.7.
The icon is found and placed inside dist/my.app/resources folder.

This is the icon my app gets.
<img width="189" alt="Standard icon" src="https://user-images.githubusercontent.com/26553764/70864659-9a9e4900-1f54-11ea-917a-54b06a995122.png">

When running PyInstaller I use this command:
`pyinstaller --windowed --clean GUI.spec`

My .spec file looks like this:
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['GUI.py'],
             pathex=['/Users/christian/Documents/Dev/Pystuff/AutoYTDownload'],
             binaries=[("/usr/local/Cellar/ffmpeg/4.2.1_2/bin/ff*","ffmpeg")],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          icon='done.icns',
          exclude_binaries=True,
          name='AutoYTDownload',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='AutoYTDownload')
app = BUNDLE(coll,
             name='AutoYTDownload.app',
             icon='done.icns',
             bundle_identifier=None,
	     info_plist={
        'NSHighResolutionCapable': 'True'
        })
```

As far as I can see this should have worked?
Do you need any more info to be able to help me?

Thanks in advance

**Comment by xylix** [comment]
Also having the same issue. I tried manually multiple ways of setting the icon in the info_plist part of the .spec too, to no solution.

**Comment by Legorooj** [comment]
Can you try building again, but override the icon with a command line option?

**Comment by xylix** [comment]
Passing it from the command line worked. Thanks for the help :)

I think I tried it before, but probably did a mistake somewhere if it didn't work back then but worked now.
