### ISSUE TITLE
Console not support TEXT COLOR and time.sleep PRoblem

### ISSUE THREAD

**Issue by muhendis80** [pyinstaller/pyinstaller#4577]
-Colored texts are not supported..

-writes another unnneccesary text messages which are not seen in pycharm python console

- if codes like that: print(".") time.sleep(1) print(".") time.sleep(1)
it sleeps 2 seconds and writes all of them

**Comment by danyeaw** [comment]
@muhendis80 Thanks for submitting the issue. This seems like at least two different problems. Could you please submit separate issues for them? Also please reference the [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs) page. We need minimal example we can reproduce and much more information if we are going to help address these issues.

**Comment by muhendis80** [comment]
import time
for x in range(0,10,1):
    print(x,end="")
    time.sleep(1)


This is the sample code, after making exe by installer and run it
it waits 10 seconds and writes suddenly all numbers

i think that textcolor support is not needs a sample

**Comment by Legorooj** [comment]
Can you try changing the print statement to `print(x, end='', flush=True)`?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
