### ISSUE TITLE
_MEIPASS and multiprocessing

### ISSUE THREAD

**Issue by kjanko** [pyinstaller/pyinstaller#4578]
I have an application that keeps a lot of processes alive. Each time a process is forked, a new temporary _MEIPASS folder is created (each one is 200 MB on average - and they add up quite fast). Is there a way to force a subprocess to use the content from the parent process's _MEIPASS instead of creating It's own? And do I need to manually clean the children's temporary folders after they die?

**Comment by Crypter** [comment]
I'm experiencing similar issues and so far couldn't find an elegant solution to this.

Any help would be appreciated.

**Comment by kjanko** [comment]
https://github.com/mherrmann/fbs/issues/87#issuecomment-508011649 solved the issue.
