### ISSUE TITLE
temp files being deleted

### ISSUE THREAD

**Issue by Dan203** [pyinstaller/pyinstaller#4579]
Reported this in [#3301](https://github.com/pyinstaller/pyinstaller/issues/3301) but it still doesn't work the --runtime_tmpdir command nor the .spec option work for Windows builds. It still extracts to the regular system TEMP folder and if left running long enough the "unused" files get cleaned up by Windows (mostly icons and graphics files that are only loaded at startup) and then the program is all messed up.

In my case it's a tray app that's intended to run all the time, so after a week or so the tray icon gets messed up and the user has to restart the program for it to function properly again. 

Any chance we could get the runtime_tmpdir functioning in Windows?

**Comment by Dan203** [comment]
A user just pointed out that this is in fact working, kind of. Instead of extracting to the folder I specified in the .spec file it's extractinging to the root of C:\. So the flag is doing something, maybe my path syntax is just wrong? I'll have to play with it and see if can get it to work correctly.

**Comment by Dan203** [comment]
I couldn’t figure out any path format that worked for this. If I had any path in there at all it caused the temp files to be extracted to the root of C:, which is an issue for standard user accounts because they’re not allowed to write directly to the root, or if I remove it then it goes back to temp. I tried both the command line switch and a line in the .spec file with the same results. 

Ultimately I reverted to using temp and dealing with the issues that causes. If anyone has a hint on how to make this work for a Windows app please let me know.

**Comment by htgoebel** [comment]
The code is in `pyi_utils.c`:
`pyi_create_temp_path()` just takes the value of option `pyi-runtime-tmpdir` and passes it on to `pyi_get_temp_path()`. The later temporary changes `%TMP%` to the value of `pyi-runtime-tmpdir`. 

Since the value is not toughed in any case, there might be some issues between characters and long characters. Do you have non-ascii in you path?

PS: Mind: PyInstaller is still in need of funding, see #4404

**Comment by Dan203** [comment]
No. I tried hard coding just a simple path like c:\pyTivo, I tried using the appdata folder, I tried using the programdata folder. I tried with and without quotes. I tried with and without escaping the slashes. It either created them in the normal temp directory or created it right in the root of C. I was actually going to just leave it in the root of C as I thought that was better than files getting randomly getting deleted from the temp folder and causing issues, but then I started getting complaints that non-admin accounts aren’t allowed to just write to the root of C so the program would just fail. 

This was for a Windows only build. I do have a Mac version of the app, but I wasn’t trying to update it yet.

**Comment by mcsimps2** [comment]
I'll also add to the conversation that I'm experiencing this bug - in my case, I'm actually getting `cacert.pem` deleted, which is causing TLS issues with the `requests` library.  I can also vouch that, trying to use `--runtime-tmpdir` only moves the `_MEI` extraction folder to the root of the drive and not to the specified location.

**Comment by mcsimps2** [comment]
Wrote a patch for this, will open up a PR tomorrow so that maintainers who have a more detailed understanding of the workings can verify that everything is sound.

**Comment by mcsimps2** [comment]
PR open.  If you need to, checkout that branch; the following tests work:
 - `pyinstaller --onefile --runtime-tmpdir ^%LOCALAPPDATA^%\MyNewApp app.py`
 - `pyinstaller --onefile --runtime-tmpdir C:\Users\ms\randomfolder app.py`

`app.py`:
```
import sys
if __name__ == "__main__":
    print(f"The app is running in directory {sys._MEIPASS}")
```
