### ISSUE TITLE
I try the -d option,but there's no detailed information about where the error occured

### ISSUE THREAD

**Issue by a709046532** [pyinstaller/pyinstaller#4587]
PS D:\code> pyinstaller -D D:\code\zhihu.py -d all
47 INFO: PyInstaller: 3.5
47 INFO: Python: 3.7.4
48 INFO: Platform: Windows-10-10.0.17763-SP0
49 INFO: wrote D:\code\zhihu.spec
61 INFO: UPX is not available.
63 INFO: Extending PYTHONPATH with paths
['D:\\code', 'D:\\code']
63 INFO: checking Analysis
63 INFO: Building Analysis because Analysis-00.toc is non existent
63 INFO: Initializing module dependency graph...
65 INFO: Initializing module graph hooks...
70 INFO: Analyzing base_library.zip ...
2069 INFO: running Analysis Analysis-00.toc
2082 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\program files\python 3.7.4\python.exe
2323 INFO: Caching module hooks...
2327 INFO: Analyzing D:\code\zhihu.py
2461 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
pre-safe-import-module hook failed, needs fixing.

I wrote a small spider but when I try to pack it up , there seems to be a problem , and there is no detailed information about the exact place where this error occured. I use the -d options, but nothing happens , I search for the whole Internet but still couldn't solve my problem..

**Comment by danyeaw** [comment]
Thanks for submitting the issue. It seems like you are getting an error caused by the pre-safe-import-module hook. This hook is run when the hooked module is first seen, but before it is added to the module graph. It is tripping up on the use of six.moves.

Do you have a [minimum example](http://sscce.org/) you can provide to help troubleshoot?

**Comment by a709046532** [comment]
Thanks for the reply ! I think the example in the  first comment could be the minimum example ,  I try many times with different py files  and I always receive the same error report , it's weird that there's no any tracebacks .  And the error report above is all the information I've got.  I also tried reinstalling pyinstaller but nothing happens.

And I finally solve the problem by running the pyinstaller in a virtual machine. I build another packing environment in Windows7 Home Basic using python 3.6 and it works well.  

It would be great if the information provided is useful.

**Comment by danyeaw** [comment]
@a709046532 So if you have `print("Hello World")` in a temp.py file and run `pyinstaller temp.py`, you get that error?

**Comment by a709046532** [comment]
@danyeaw no, it's packed successfully..

**Comment by a709046532** [comment]
@danyeaw I think I found the problem. 

Statements like "from selenium import webdriver" trigger the error , but statements like "import Selenium" works well . I wondered whether it's the compatibility so I try several modules, and I found that modules like pyquery can have the same problem. But some other modules like lxml do not.

That's all I've got,  still there's no tracebacks so I still couldn't figure out why it happened..

**Comment by a709046532** [comment]
@danyeaw  And in the virtual machine I mentioned above , that problem is not found

**Comment by htgoebel** [comment]
Did you read this?
```
 2461 INFO: Processing pre-safe import module hook urllib3.packages.six.moves
pre-safe-import-module hook failed, needs fixing.
```
Workaround: Try an older or an newer version of urllib3.
Digging down the error: In `PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py`

Thansk for working on this, I appreciate your pull-request.

**Comment by htgoebel** [comment]
@a709046532 Any follow up? Pull-request?
