### ISSUE TITLE
Failed to execute script

### ISSUE THREAD

**Issue by yishangfei** [pyinstaller/pyinstaller#4589]
Production Environment：
1. windows 10
2. python      3.7.3
3. pyinstaller  3.5   or   pyinsltaller-dev

![image](https://user-images.githubusercontent.com/15099278/71465838-98f83f00-27f8-11ea-8c06-e2527a06633f.png)

Code does not report an error in pycharm, use pyinstaller to report an error

help me~

**Comment by Legorooj** [comment]
Could you please provide details of your issue?

**Comment by Legorooj** [comment]
@yishangfei pinging

**Comment by yishangfei** [comment]
@Legorooj  First, I ran the code shown in pycharm to compress autojump.png. Then I packaged it into exe through pyinstaller -F -w b.py, and Failed to execute script b appeared. I do n’t know if it was not accessible to https  
![a](https://user-images.githubusercontent.com/15099278/75126325-58337e00-56f4-11ea-95b0-aa24abee67cc.png)

code：
import tinify
tinify.key = 'mhDgfkycPsLfqZyrB5D8TrqlXR8fKPt2'

if __name__ == '__main__':
    source = tinify.from_file("autojump.png").to_file("autojump.png")

**Comment by Legorooj** [comment]
@yishangfei try adding the option `--add-data=autojump.png;.`. (Don't run in powershell, only cmd).

**Comment by yishangfei** [comment]
sorry, I didn't understand

**Comment by Legorooj** [comment]
See if `pyinstaller -F -w b.py --add-data=autojump.png;.` works

**Comment by yishangfei** [comment]
![image](https://user-images.githubusercontent.com/15099278/75140049-196beb00-5729-11ea-8369-8b34e58fc4ef.png)
![image](https://user-images.githubusercontent.com/15099278/75140056-1e309f00-5729-11ea-9170-162ca28b2f82.png)

Still the same，My photos are generated every time

**Comment by Legorooj** [comment]
No you changed the option. Please try with the exact option a pointed out.

**Comment by Legorooj** [comment]
I'm going to close this, seeing as SO and the docs will help you fix this.
