### ISSUE TITLE
Pyinstaller error: invalid command

### ISSUE THREAD

**Issue by Rego0116** [pyinstaller/pyinstaller#4594]
I tried installing the pyinstaller for py to exe, but i get lots of errors code.
Here is the code:
`Microsoft Windows [Version 10.0.18362.535]
(c) 2019 Microsoft Corporation. All rights reserved.

C:\Users\Regő>pip install pyinstaller
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/e2/c9/0b44b2ea87ba36395483a672fddd07e6a9cb2b8d3c4a28d7ae76c7e7e1e5/PyInstaller-3.5.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'd:\python\python.exe' 'd:\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\REG~1\AppData\Local\Temp\tmpdm3k7rpk'
         cwd: C:\Users\Regő\AppData\Local\Temp\pip-install-wujnzx8k\pyinstaller
    Complete output (36 lines):
    running dist_info
    creating C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info
    writing C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info\dependency_links.txt
    writing entry points to C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info\entry_points.txt
    writing requirements to C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info\requires.txt
    writing top-level names to C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info\top_level.txt
    writing manifest file 'C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xf5 in position 0: invalid start byte (sitecustomize.py, line 21)
    no previously-included directories found matching 'bootloader\build'
    no previously-included directories found matching 'bootloader\.waf-*'
    no previously-included directories found matching 'bootloader\.waf3-*'
    no previously-included directories found matching 'bootloader\waf-*'
    no previously-included directories found matching 'bootloader\waf3-*'
    no previously-included directories found matching 'bootloader\_sdks'
    no previously-included directories found matching 'bootloader\.vagrant'
    warning: no previously-included files found matching 'bootloader\.lock-waf*'
    no previously-included directories found matching 'doc\source'
    no previously-included directories found matching 'doc\_build'
    warning: no previously-included files matching '*.tmp' found under directory 'doc'
    warning: no files found matching 'news\_template.rst'
    no previously-included directories found matching 'news'
    no previously-included directories found matching 'old'
    no previously-included directories found matching 'scripts'
    no previously-included directories found matching 'tests\scripts'
    no previously-included directories found matching '.github'
    warning: no previously-included files found matching '.*'
    warning: no previously-included files found matching '*.yml'
    warning: no previously-included files found matching '*~'
    warning: no previously-included files found matching '.directory'
    writing manifest file 'C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.egg-info\SOURCES.txt'
    creating 'C:\Users\Regő\AppData\Local\Temp\pip-modern-metadata-_ncmfdo5\PyInstaller.dist-info'
    error: invalid command 'bdist_wheel'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'd:\python\python.exe' 'd:\python\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\REG~1\AppData\Local\Temp\tmpdm3k7rpk' Check the logs for full command output.

C:\Users\Regő>`

**Comment by Rego0116** [comment]
Anybody?

**Comment by danyeaw** [comment]
@Rego0116 I would highly recommend using a [virtualenv](https://docs.python.org/3/tutorial/venv.html). Since this error is coming from pip, once you have a virtualenv setup, I suggest trying to  run:
`pip install --upgrade pip`
`pip install --upgrade setuptools`

If you want to join [IRC](https://webchat.freenode.net/?channels=pyinstaller&prompt=1), I can help you get things setup properly. Since this isn't an issue with PyInstaller itself, could you please close this issue?

**Comment by Legorooj** [comment]
@Rego0116 is this issue cloasable?

**Comment by Rego0116** [comment]
Yes it is.

Legorooj <notifications@github.com> ezt írta (időpont: 2020. febr. 7., P
6:32):
