### ISSUE TITLE
System reboots while compiling using pyinstaller

### ISSUE THREAD

**Issue by krunal704** [pyinstaller/pyinstaller#4596]
Python: 3.6
Pyinstaller: 3.5
System: Jetson Nano Development Board
I have installed OpenCV 4.1 using compiling from the source.
Command: pyinstaller app.py -n App --add-data="data:data" --paths="/usr/local/lib/python3.6/dist-packages/cv2/python-3.6"

Logs:
...
...
building COLLECT COLLECT-00.toc

After this line system reboots suddenly and there is no such a log or crash report for that
What is causing the system to reboot?

**Comment by htgoebel** [comment]
PyInstaller is a simple application doing nothing special.

>  System: Jetson Nano Development Board

So maybe you are just out of memory?
