### ISSUE TITLE
After compiling and run give "[Errno 2] No such file or directory" 

### ISSUE THREAD

**Issue by nurlan0508** [pyinstaller/pyinstaller#4599]
After compiling programm and run it I have error. Error on line when I creating file like that:
```open('master.zip', 'w').close()```

Can you say me how should I fix it?

I compile like that:
```pyinstaller - F downloader.py```
and see ready .exe file in 'dist' folder

**Comment by Legorooj** [comment]
Closing this. I'll happily reopen if you can:
* Prove it's a PyInstaller bug
* And give us more information

If this is a support question, please go elsewhere (eg StackOverflow)
