### ISSUE TITLE
print&time.sleep Problem

### ISSUE THREAD

**Issue by muhendis80** [pyinstaller/pyinstaller#4603]
import time
for x in range(0,10,1):
print(x,end="")
time.sleep(1)

This is the sample code, after making exe by pyinstaller and run it
it waits 10 seconds and writes suddenly all numbers

**Comment by zwzhen** [comment]
You should flush output manually. it's not an issue of pyinstaller.

**Comment by muhendis80** [comment]
The use of "flush" in python not needed caused this error, thank you
