### ISSUE TITLE
Not able to install via pip 19.3.1

### ISSUE THREAD

**Issue by varunrocxx** [pyinstaller/pyinstaller#4604]
The error I got after trying to install pyinstaller through pip version 19.3.1 :
"Installing build dependencies ... error"
But When I revert to Pip version 18.1 it worked.

**Comment by ErikBjare** [comment]
You haven't followed the issue template so we can't help you. It installs fine for me.

**Comment by anthion** [comment]
I ran into this behavior. In my case it was caused by having enum34 installed. pip uninstall enum34 then install pyinstaller. worked for me. I'm running pip ver 19.3.1 and python 3.7
