### ISSUE TITLE
Can't exclude ucrtbase, what is its use?.不能排除ucrtbase，它的用途是？

### ISSUE THREAD

**Issue by bzsome** [pyinstaller/pyinstaller#4605]
I have a program that is just a service, without an interface and console (to not display the console, I used the configuration console = False). When I configure excludes = ['win32ui', 'mfc140u', 'ucrtbase'] and use the onedir build method, I can see that win32ui.dll and mfc140u.dll have been excluded, but ucrtbase.dll has not been excluded. I manually deleted ucrtbase.dll and the program still worked. When I use the onefile method, how can I exclude ucrtbase to minimize my program?

 我有一个程序，仅仅是服务，没有界面和控制台(为了不显示控制台，使用了配置console=False)。当我配置 excludes=['win32ui','mfc140u','ucrtbase']，并使用onedir构建方式，我可以看到win32ui.dll和mfc140u.dll已经被排除，但是ucrtbase.dll却没有被排除。我手动删除ucrtbase.dll，程序依然可以正常运行。  请问我使用onefile方式构建时，怎么排除ucrtbase以使我的程序最小化。

    - mode: python -*-

    block_cipher = None

    a = Analysis(['bin\\MainStart.py'],
             pathex=['C:\\Users\\chao\\PycharmProjects\\Control_NoIcon'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=['win32ui','mfc140u','ucrtbase'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=True) # to exe
    pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
    exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='MainStart',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          runtime_tmpdir=None,
          console=False)

**Comment by AndCycle** [comment]
ucrtbase exist as a workaround for legacy windows, pyinstaller need it to work under win7,
that's due to the main python version switched to a newer version of visual studio.

unless you fallback to old python and pyinstaller there is no simple solution for that.
