### ISSUE TITLE
Can the pyinstaller pack a executables for Linux in Windows?

### ISSUE THREAD

**Issue by conero** [pyinstaller/pyinstaller#4606]
*Can the pyinstaller pack a executables for Linux in Windows? Like this and more, sometime I really meet the case, so ask for help.*

**Comment by KahJun0** [comment]
No, PyInstaller cannot pack a executable for Linux in Windows. Easiest way to go about doing so would be to use a Linux VM.

**Comment by conero** [comment]
@KahJun0 Got it, and thanks for ur help.
