### ISSUE TITLE
--noconsole flag, fatal error.

### ISSUE THREAD

**Issue by enfshin** [pyinstaller/pyinstaller#4607]
fisrt of all, thank you for such a wonderful work, pyinstaller.

please see [my stackoverflow](https://stackoverflow.com/questions/59484223/pyinstaller-noconsole-option-makes-exe-fatal-error)

I made script with atom,
Window 10, 64bit, anaconda venv, 
python 3.5.6, pyinstaller 3.5, selenium 3.141, pyqt 5.13.2, pymysql 0.9.3 pandas 0.25.3
I sepereted main.py with Qthread (there is 4 thread) and chromedriver 79.

I have also tried 
 1. install lastest version (4.0) and tried everything I did with version 3.5
 2. make --onedir and find every error, fixed
 3. make --onefile and fine every error, fixed 
 4. tried pyw
 5. read some article that say, pycharm opened make error. so I even tried everything again with atom closed(just hope to be work)

work with fine when I made exe by `pyinstaller --onefile (onedir too) myapp.py.`
since onefile flag does work, I don't think there is problem with module or importerror or missing dll. for now I don't even have ico. so there is no img or ico missing. 
I even tested my exe with 10 different computer, 10 different person. woking fine with console.

I am sorry that I cannot paste my script here, it's thousand of thousand of code. 
but if you need, I can send you my script. 

I am new to programming. If this is not bug... I am sincerely sorry. 
but I am stock here for weeks... pls help me. 
if you need any find of more infomation please notice me.

**Comment by Legorooj** [comment]
Have you tried with the `--windowed` flag instead? They're pretty much the same thing, but it's worth a go. 

You're saying that your script works fine without this flag? Could you open a command line and run the executable from there, and then post the traceback?

**Comment by enfshin** [comment]
I soleved this 
https://stackoverflow.com/questions/59484223/pyinstaller-noconsole-option-makes-exe-fatal-error-solved
