### ISSUE TITLE
Executable failed during execution - Second chance exception ntdll

### ISSUE THREAD

**Issue by daralex31** [pyinstaller/pyinstaller#4608]
Dear Support,
Sorry to disturb you but i have an issue on my current project,  I spend many days trying to overcome it but I don't manage to go through.

I managed to build an executable folder with pyinstaller 3.5  perfectly working on my computer (Windows 7 + anaconda is installed with python 2.7). 

However, when i try to run it on another computer(Windows 7), I have a windows error message (APPCrash, on NTDLL module).
I used dependency walker to check dependencies and profile the executable. 

Here are enclosed the error pointed by dependency walker.
_00:01:34.459: LoadLibraryW("C:\Windows\system32\gdi32.dll") called from "d:\atlas_~1\QT5CORE.DLL" at address 0x00000000667EAE65 by thread 1.
00:01:34.459: LoadLibraryW("C:\Windows\system32\gdi32.dll") returned 0x000007FEFE720000 by thread 1.
0:01:34.474: GetProcAddress(0x000007FEFE720000 [c:\windows\system32\GDI32.DLL], "GetCharWidthI") called from "d:\atlas_~1\pyqt5\qt\plugins\platforms\QWINDOWS.DLL" at address 0x000007FEC68D9401 and returned 0x000007FEFE7456AC by thread 1.
00:01:34.584: Second chance exception 0xC0000005 (Access Violation) occurred in "c:\windows\system32\NTDLL.DLL" at address 0x0000000076D3A365 by thread 1._

This access violation made the code crash.  It looks like the exe try to access a second time to NTDLL.DLL

_On the other hand, for the sucessfull case, the corresponding lines are
00:01:56.345: GetProcAddress(0x000007FEFD900000 [c:\windows\system32\GDI32.DLL], "GetCharWidthI") called from "k:\atlas_~1\pyqt5\qt\plugins\platforms\QWINDOWS.DLL" at address 0x000007FEE3D69401 and returned 0x000007FEFD92568C.
00:01:57.859: LoadLibraryW("C:\Windows\system32\shell32.dll") called from "k:\atlas_~1\QT5CORE.DLL" at address 0x00000000677EAE65._

It seems the loading of GDI32.dll which needs NTDLL.dll have worked on my computer. 

Do you have any idea of how to make it work ? Does this problem already occurs ? 
Please guys,  your help would be very great ! 

And thanks for this great module :)

**Comment by Legorooj** [comment]
We can't support this; this is a windows permission error. And it shouldn't be failing because `ntdll.dll` is part of windows, and every program can read it. If a program can't then something is wrong.
