### ISSUE TITLE
Use PEP 508 environment markers in setup.py

### ISSUE THREAD

**Issue by absassi** [pyinstaller/pyinstaller#4609]
Please use [PEP 508](https://www.python.org/dev/peps/pep-0508/) environment markers in `setup.py` instead of `if` clauses to add platform-specific requirements (dis3, pywin32-ctypes, pefile and macholib), so that dependency manager tools that can create platform-independent lock files (such as [Poetry](https://python-poetry.org/)) are able to correctly detect all PyInstaller dependencies and lock them appropriately.

**Comment by bjones1** [comment]
Looks like this is already done, thanks to @htgoebel's hard work -- see https://github.com/pyinstaller/pyinstaller/blob/develop/setup.cfg#L60.
