### ISSUE TITLE
PyInstaller cannot check for assembly dependencies

### ISSUE THREAD

**Issue by omar18881** [pyinstaller/pyinstaller#4611]
**i am trying to make tkinter gui module with build option to build Exes after the usr put some inputs & i don't want him to install python and pyinstaller to be able to Compile the code to Exe **

Using Python 3.6.0

I made 2 python scripts first named compiler.py & other hello.py
hello.py`print("Hello World")`

compiler.py 

    import PyInstaller.__main__
    import ctypes
    import win32ctypes
    from win32ctypes import pywin32
    from win32ctypes.pywin32 import pywintypes
    import os

    def compiling():
        PyInstaller.__main__.run([
            # '--name=%s' % package_name,
            '--onefile',
            '--windowed',
            # '--add-binary=%s' % os.path.join('resource', 'path', '*.png'),
            # '--add-data=%s' % os.path.join('resource', 'path', '*.txt'),
            # '--icon=%s' % os.path.join('resource', 'path', 'icon.ico'),
            os.path.join('hello.py'),  # my_package is a Directory
            # '--version-file=%s' % os.path.join('assembly.txt'),
        ])
    compiling()

when i try to Compile compiler.py with pyinstaller it compiles successfully
with -->pyinstaller --onefile --console compiler.py

but when i try to run the exe it throws 

    PyInstaller cannot check for assembly dependencies.
    Please install pywin32-ctypes.

    pip install pywin32-ctypes

What i Have Tried ?
1-i installed pywin32-ctypes successfully
2-Tried to compile compiler.py with different alternatives other than pyinstaller
3-cx-freeze & nuitka both of them throws the same error when i Run after compiling.
4- tried using Python 3.7.5 on other machine start new & fresh, Throw the Same Error
the reason i choose pyinstaller because it can build 1 EXE

https://github.com/pyinstaller/pyinstaller/issues/3892 

https://github.com/pyinstaller/pyinstaller/issues/3793

https://stackoverflow.com/questions/52194396/unable-to-run-pyinstaller-please-install-pywin32-or-pywin32-ctypes

All those Failed As Well is it something i am Doing Wrong or is Pyinstaller Problem

**Comment by Legorooj** [comment]
You need hook files and runtime hook files. We can't and won't support using PyInstaller from a frozen app.
