### ISSUE TITLE
Sqlalchemy not applying transactions

### ISSUE THREAD

**Issue by Abdur-rahmaanJ** [pyinstaller/pyinstaller#4619]
## Description of the issue
Not an error, but sqlalchemy not applying any transaction in packaged mode (like deleted etcJ. Works fine in normal python mode.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0.dev0+a97628fba9```
* Version of Python: 3.8
* Platform: Windows

**Comment by Legorooj** [comment]
We can't help with this. It does sound like it could be a bug, but if you can track it down, let us know. We don't have time to help with this. (Also python 3.8 isn't supported)

**Comment by Abdur-rahmaanJ** [comment]
My take is that since pyinstaller extracts everything, at next run everything is wiped then reextracted resulting in a new db same as original

**Comment by Legorooj** [comment]
That's probably the case when using `--onefile` mode. Have you tried omitting that option?

**Comment by Abdur-rahmaanJ** [comment]
That's the case with onefile mode. I'm using folder mode right now.  A pity you can't use sqlalchemy on onefile mode.
