### ISSUE TITLE
Documentation of `--onedir` for spec files

### ISSUE THREAD

**Issue by peteristhegreat** [pyinstaller/pyinstaller#4620]
**Is your feature request related to a problem? Please describe.**
I want to use the `--onedir` option from within a spec file, but it doesn't appear to be supported or documented.  The output of `pyi-makespec --onedir myapp.py` ended up being what I needed.

**Describe the solution you'd like**
Documentation on how to get the `--onedir` equivalent from a spec file.

**Describe alternatives you've considered**
I tried toggling `external_binaries` in the parameters of `EXE()` and also toggling `append_pkg` in the parameters of `EXE()`.  I also tried running with `--onedir` in the command of `pyinstaller --onedir myapp.py`.  Finally I found this example that the onefile and onedir sample spec files side by side and I was able to use the `COLLECT` command to get it work.

https://github.com/readbeyond/aeneas/blob/master/pyinstaller-onefile.spec

https://github.com/readbeyond/aeneas/blob/master/pyinstaller-onedir.spec

The output of `pyi-makespec --onedir myapp.py` ended up being what I needed.

**Additional context**
Python 3.7.5 with PyInstaller 3.5, Windows 10, x64

**Comment by Legorooj** [comment]
You already can. If it has a `COLLECT` call, it's `onedir`. If not, and `a.datas` etc is passed to the `EXE` call, it's `onefile`. Use the `pyi-makespec` command to generate spec files. You run it the same as the `pyinstaller` command, it just doesn't run the build.
