### ISSUE TITLE
Import hook for argon2 (password hashing library)

### ISSUE THREAD

**Issue by IlyaOrson** [pyinstaller/pyinstaller#4625]
**Is your feature request related to a problem? Please describe.**
I could not use password authentication easily.

**Describe the solution you'd like**
Make it easier to use a good password hashing library.

**Describe alternatives you've considered**
I tried to use `passlib` but the pull-request I found did not work for me and it was easier to fix this library directly.

**Additional context**
This seems to be a good password hashing algorithm, would be great to support it by default.

**Comment by luchiago** [comment]
Can I work on this?

**Comment by IlyaOrson** [comment]
I created this issue after opening a pull-request with my proposed solution. It would be helpful though if you can test it locally to double check it works.

**Comment by Legorooj** [comment]
Why not use [Cryptography](https://cryptography.io)?

**Comment by Legorooj** [comment]
@IlyaOrson also have you tried actually compiling it? It might work without a hook. Some libs do.

**Comment by IlyaOrson** [comment]
Password hashing functions are [specialized](https://en.wikipedia.org/wiki/Cryptographic_hash_function#Password_verification) to [avoid brute force attacks](https://auth0.com/blog/hashing-passwords-one-way-road-to-security/#Limitations-of-Hash-Functions) and Argon2 is [currently the best](https://en.wikipedia.org/wiki/Argon2) for this use case.

This library fails to load without the hidden import of `_cffi_backend`.

**Comment by Legorooj** [comment]
@IlyaOrson I know my stuff when it comes to cryptography. It's my favourite speciality.

To fix that, try building with the cmdline option `--hidden-import _cffi_backend` for a tempory fix.

**Comment by IlyaOrson** [comment]
> @IlyaOrson I know my stuff when it comes to cryptography. It's my favourite speciality.

I did not mean to imply otherwise.

> Also `Argon2` isn't just "the best" function in this use case. It just won a competition.

Point taken, I am just learning about this field. Could you elaborate why Cryptography would be better for this use case? (Also, pinning me is not really necessary)

> To fix that, try building with the cmdline option `--hidden-import _cffi_backend` for a tempory fix.

That is what I am currently doing. The intention of my pull request was to let the library handle this automatically in future versions. Is there anything wrong with that solution?

**Comment by Legorooj** [comment]
@IlyaOrson nope - your pull request looks ok - and my original comment was simply curiosity about why the`argon2` library, and not `cryprography` and `pycryptodome`. 

Also let me clarify - `argon2` is a good password hash, but that doesn't make it the *best*, even though it's probably in the top 5 for this use case. 

Could I have a link to the specific `argon2` library you are using? And if I'm understanding correctly `cryptography` would only be better if you need other Cryptographic tools.

**Comment by Legorooj** [comment]
We are no longer accepting issues like this. PRs are welcome though.

**Comment by IlyaOrson** [comment]
This is the library I used: https://pypi.org/project/argon2-cffi/
