### ISSUE TITLE
When running frozen PyQt5 app on macOS, window appears blank if NSRequiresAquaSystemAppearance is false

### ISSUE THREAD

**Issue by drinkitup777** [pyinstaller/pyinstaller#4627]
# Description of the issue
When running a frozen PyQt5 app, the window will appear completely blank if `NSRequiresAquaSystemAppearance` was set to `false` in the app's `Info.plist`.

# Context Information
Output of pyinstaller --version: `4.0.dev0+g3d331fda`
Version of Python: 3.7.6
Platform: macOS Catalina 10.15.1

# Code to demo the problem

```python3
#!/usr/bin/env python3

import sys
from PyQt5.QtWidgets import *


class MainApp(QApplication):
    def __init__(self, argv):
        super().__init__(argv)

        widget = QPushButton('test')

        window = QMainWindow()
        window.setCentralWidget(widget)

        window.show()

        self.window = window


app = MainApp(sys.argv)
app.exec_()
```

Running from source works just fine.

But after freezing into an app bundle with `pyinstaller --onedir --windowed --noupx --noconfirm --log-level DEBUG ./main.py` and editing `NSRequiresAquaSystemAppearance` to `false` in Info.plist, the window appears without its widgets.

If the frozen app bundle is run from the command line, the blank app window will pop up and the terminal will will display the following error message:

```log
2020-01-12 08:28:55.515 main[15055:252052] It does not make sense to draw an image when [NSGraphicsContext currentContext] is nil.  This is a programming error. Break on void _NSWarnForDrawingImageWithNoCurrentContext(void) to debug.  This will be logged only once.  This may break in the future.
```

Contents of `pyinstaller.log`

```
36 INFO: PyInstaller: 4.0.dev0+g3d331fda
36 INFO: Python: 3.7.6
39 INFO: Platform: Darwin-19.0.0-x86_64-i386-64bit
40 INFO: wrote /Users/bucko/Projects/testapp/main.spec
40 DEBUG: Testing for UPX ...
42 INFO: UPX is available.
43 DEBUG: script: /Users/bucko/Projects/testapp/main.py
44 INFO: Extending PYTHONPATH with paths
['/Users/bucko/Projects/testapp', '/Users/bucko/Projects/testapp']
44 INFO: checking Analysis
49 INFO: checking PYZ
51 INFO: checking PKG
51 INFO: Bootloader /usr/local/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
51 INFO: checking EXE
52 INFO: checking COLLECT
52 INFO: Removing dir /Users/bucko/Projects/testapp/dist/main
59 INFO: Building COLLECT COLLECT-00.toc
897 INFO: Building COLLECT COLLECT-00.toc completed successfully.
900 INFO: checking BUNDLE
901 INFO: Removing dir /Users/bucko/Projects/testapp/dist/main.app
909 INFO: Building BUNDLE BUNDLE-00.toc
1811 INFO: moving BUNDLE data files to Resource directory
On your own risk, you can use the option `--noconfirm` to get rid of this question.
On your own risk, you can use the option `--noconfirm` to get rid of this question.
```

**Comment by MAKOMO** [comment]
Running from source does not respect the macOS dark mode and thus runs fine.

**Comment by jonathannaguin** [comment]
I am also having this issue, if I run the app from sources, it does have the dark mode and the window is rendered correctly. After freezing it, the window is transparent and nothing is rendered or visible.
Using PyQt5==5.13.2.

**Comment by jonathannaguin** [comment]
I've just upgraded to PyQt5==5.14.1 and the problem remains. Having 'NSRequiresAquaSystemAppearance' set to False breaks the rendering.
I am now re-evaluating the fact we need NSRequiresAquaSystemAppearance on the Plist at all, according to the docs we only need the app built using SDK >= 10.14:
```
Apps linked against macOS 10.14 or later should support both light and dark appearances. If you build your app against an earlier SDK, you can still enable Dark Mode support by including the NSRequiresAquaSystemAppearance key (with a value of false) in your app's Info.plis file. Do so only if your app's appearance looks correct when running in macOS 10.14 and later with Dark Mode enabled.
```
And actually, the PyQT code seems to honour that statement as well: https://codereview.qt-project.org/gitweb?p=qt/qtbase.git;a=blob;f=src/corelib/kernel/qcore_mac.mm;hb=7e9481f1fb00bee9d20e8c13d761c0f16ee04973#l342

**Comment by MAKOMO** [comment]
I can confirm that linking my PyQt 5.14.2 app to macOS SDK 10.5 and not adding that additional Info.plist entry made it work in dark mode as expected (SDK 10.4 should work as well) .

However, as I bundle my app with py2app instead of pyinstaller I have no recipe on how to achieve this with pyinstaller. I assume that also for pyinstaller some bootloader needs to be recompiled accordingly.

The steps on how I tweaked py2app is described here:
[https://github.com/ronaldoussoren/py2app/issues/271](https://github.com/ronaldoussoren/py2app/issues/271)

**Comment by crwood** [comment]
My solution to this problem was to recompile both the PyInstaller bootloader and the Python interpreter with a `MACOSX_DEPLOYMENT_TARGET=10.13` (overriding the PyInstaller default of 10.7) and to use Xcode version 11 or higher while doing so. I now have a PyInstaller-frozen (Py)Qt 5.14 application with working dark mode _and_ binary-compatibility with macOS 10.13, 10.14, and 10.15. See [this comment](https://github.com/gridsync/gridsync/issues/267#issuecomment-609980411) for further details.
