### ISSUE TITLE
Trojan in Pyinstaller over PIP

### ISSUE THREAD

**Issue by Lecatron** [pyinstaller/pyinstaller#4633]
Dear Team, 

yesterday, i tried to install the pyinstaller over pip for my 32-Bit VM.
While the installation McAfee found an trojan in the runw.exe.

Maybe this is a false positive, but this should be checked, and then transmitted to McAfee to fix this.

Within I send you the screenshot.

Thank you =)
![image](https://user-images.githubusercontent.com/56350725/72501523-4dedac80-3837-11ea-9985-9925c503262a.png)

**Comment by grajsor** [comment]
So why didn't you do just that?

**Comment by Lecatron** [comment]
Hi Grajsor, 

cause I'm not so deep in the project to know, which files or codes are underlying in this .exe

If you can tell me this, I can check this for you.

**Comment by hubuser404** [comment]
Hi Lecatron,

I encountered same problem with McAfee yesterday while installing via pip.
Also windows security founds following threat: Trojan:Win32/Wacatac.C!ml
file: C:\Users\xxx\AppData\Local\Temp\pip-install-07ehm9se\PyInstaller\build\lib\PyInstaller\bootloader\Windows-32bit\runw.exe

**Comment by jaaaaviiieer** [comment]
Hi

i have the same problem, bot with windows defender. every time i try to install via pip says that found a trojan: Wacatac.C!ml

**Comment by emddudley** [comment]
This is almost certainly a false-positive detection by the antivirus vendors. It's [perennial](Other issue: https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

Anyone who encounters this should report it to their antivirus vendors. That way the vendors can updated their software to remove the false positive.

See also https://github.com/pyinstaller/pyinstaller/issues/2501.

**Comment by pwuertz** [comment]
If PyInstaller is a popular tool among malware authors, that would certainly cause false-positive reactions among antivirus vendors due to the shared bootloader code :(.

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).

**Comment by Ep1cfy** [comment]
it said one for Downloads/ALLER...DEVELOP.ZIP
and another for Downloads/Staller...develop.lnk
i just download pip and i got this error
it was mbam

**Comment by htgoebel** [comment]
Please contact you anti-virus vendor. There is *nothing* we can do about this false positive.

If your anti-virus vendor considers one of the files included in the PyInstaller distribution or a file generated by PyInstaller to be malicious, there is *nothing* we can do about this. Even if we'd change our code, they'd change their pattern and the race starts again.

See [this mailing-list thread](http://www.mail-archive.com/pyinstaller@googlegroups.com/msg05002.html) and [other tickets for his topic](https://github.com/pyinstaller/pyinstaller/issues?q=is%3Aissue+virus+is%3Aclosed).
