### ISSUE TITLE
Ability to load different Tensorflow file according to parameter value.

### ISSUE THREAD

**Issue by KamalChhirang** [pyinstaller/pyinstaller#4638]
**Is your feature request related to a problem? Please describe.**

I have two virtual environments. One uses Tensorflow GPU, and another one Tensorflow CPU. I created an exe file for both the environments. The only difference in both the exe files is that "_pywrap_tensorflow_internal.pyd" file is different for both GPU & CPU version. So I either need to keep two exe for gpu & cpu or manually (or via code) copy/paste the gpu/cpu _pywrap_tensorflow_internal.pyd  into the exe folder. 

**Describe the solution you'd like**

Any way to load the GPU/CPU TensorFlow file using a command at runtime? Something like this:
"exename.exe --loadTensorFlowFilePath=abcPathHere". Just used Tensorflow example here, I guess, we can add this feature for all type of files.

**Describe alternatives you've considered**

**Additional context**

**Comment by htgoebel** [comment]
Thanks for this suggestions. Implementing this in PyInstaller in a generic way ist much too much effort, given there is a simple workaround one can easily adopt to her/his needs:

For your frozen app to be able to load different versions of the module, you need
1. the different versions of the module *named* differently - say: they need be different modules
2. a helper module which
   1.  imports the respective module based on some switch/env-var/command-line-option
   2. add the imported module under the desired name into sys.modules

Rough scratch of helper module
```
import sys, os
if os.getenv("USE_GPU"):
   mod = __import__("_module_for_gpu")
else:
   mod = __import__("_module_for_cpu")
sys.modules["_pywrap_tensorflow_internal"] = mod
````

And run `pyinstaller --hidden-import _module_for_gpu --hidden-import _module_for_cpu ....`

Anyway, I'd appreciate if you could put this into a recipt into the wii.
