### ISSUE TITLE
PyInstaller breaks CEF Engine

### ISSUE THREAD

**Issue by TheDemystifier** [pyinstaller/pyinstaller#4639]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue

CEF not packaged correctly, It works prior to packaging, but once packaged using PyInstaller, it throws an error.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0.dev0+55c8855d9d```
* Version of Python: 3.7
* Platform: Windows 10 64Bit English US
* Did you also try this on another platform? No!

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

[https://gist.github.com/TheDemystifier/0692b3a6252a188c0693328daca050f7](https://gist.github.com/TheDemystifier/0692b3a6252a188c0693328daca050f7)

### Stacktrace / full error message

```
[0117/164120.680:ERROR:icu_util.cc(133)] Invalid file descriptor to ICU data received.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by htgoebel** [comment]
Please provide more details, see [How to report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs). **Follow all the steps described there.** Especially don't use `-F`/`--onefile`, run from a console windows, provide a *minimal* example to reproduce the error and provide `relevant` parts of the traceback.

**Comment by Legorooj** [comment]
Stale

**Comment by alibaltschun** [comment]
did you find the solution?
thanks

**Comment by TheDemystifier** [comment]
> did you find the solution?
> thanks

Nope, I switched to PyQt instead. Not the best solution since PyQt needs a license, but my little project was for non-commercial use, so it was fine.

**Comment by Legorooj** [comment]
@TheDemystifier https://wxpython.org. Free for commercial use; widely used; python bindings to the toolkit Audacity, FileZilla, and a few other programs.
