### ISSUE TITLE
Add pyinstaller.exe that runs without python

### ISSUE THREAD

**Issue by graysuit** [pyinstaller/pyinstaller#4642]
Please add **pyinstaller** windows binaries that can run independent of python. Not all people have python installed.Please PleasePleasePleasePleasePleasePleasePlease.

**Comment by Legorooj** [comment]
You could build these yourself...

**Comment by Legorooj** [comment]
There would be too much work involved; PyInstaller uses the python interpreter and installed libraries when building. That means there would be too much work involved.

Also the target users are python developers **who already have python installed**. 

We can safely say that sorry, but this won't be added.

**Comment by graysuit** [comment]
Yeah I know it will be very hard as there are **tons of python libraries** to add,
But must try adding it as it is **hard** but **not impossible**.<br>
**And I also reporting a bug that I found**<br>
It will not compile correctly if file path has spaces like
`C:\Users\root\source\repos\Python Pyinstaller Bug.py`<br>
Works fine if path has no spaces like
`C:\Users\root\source\repos\Python_Pyinstaller_Bug.py`

Thanks for replying.

**Comment by Legorooj** [comment]
@graysuit the bug you need to put paths with spaces inside double quotes; ie. `"C:\Users\root\documents\path with spaces\bug.py"`. If you want to do something like this, do it, get it working, and we'll take a look and maybe include it. It's just something that we won't have time to implement, but if you do...

**Comment by graysuit** [comment]
No I was not talking about script path,
I was talking about current directory path,
If a directory where we are going to compile our script have spaces like that
`C:\Users\root\My folder path/newfolder`

But should works fine in
`C:\Users\root\My_folder_path/newfolder`

**Comment by Legorooj** [comment]
@graysuit I'm confused - can you tell me the full command you used to compile and failed? and the one that works.

**Comment by graysuit** [comment]
This works fine<code><pre>C:\Users\root\Example_folder_path/newfolder>pyinstaller example.py</pre></code>
This fails<code><pre>C:\Users\root\Example folder path/newfolder>pyinstaller example.py</pre></code>

See the path difference

**Comment by Legorooj** [comment]
This works fine for me... Spaces shouldnt matter.

**Comment by graysuit** [comment]
But must review your code one time whether you are missing some single/double quotes,
Because this is testing many times,
Thanks for helping
