### ISSUE TITLE
Pyinstaller can't find .dll files 

### ISSUE THREAD

**Issue by iamMHZ** [pyinstaller/pyinstaller#4644]
```
15636 WARNING: lib not found: api-ms-win-core-winrt-l1-1-0.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\plugins\audio\qtaudio_wasapi.dll
15771 WARNING: lib not found: api-ms-win-core-winrt-string-l1-1-0.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\plugins\audio\qtaudio_wasapi.dll
15898 WARNING: lib not found: Qt53DCore.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
16018 WARNING: lib not found: Qt53DLogic.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
16143 WARNING: lib not found: Qt53DRender.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
16269 WARNING: lib not found: Qt53DInput.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
16392 WARNING: lib not found: Qt53DAnimation.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtQuick\Scene3D\qtquickscene3dplugin.dll
16809 WARNING: lib not found: Qt53DCore.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtQuick\Scene2D\qtquickscene2dplugin.dll
16932 WARNING: lib not found: Qt53DRender.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtQuick\Scene2D\qtquickscene2dplugin.dll
17057 WARNING: lib not found: Qt53DQuickScene2D.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtQuick\Scene2D\qtquickscene2dplugin.dll
17544 WARNING: lib not found: Qt5MultimediaQuick.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\qml\QtMultimedia\declarative_multimedia.dll
18106 WARNING: lib not found: LIBPQ.dll dependency of D:\program files\python37\lib\site-packages\PyQt5\Qt\plugins\sqldrivers\qsqlpsql.dll
19230 WARNING: lib not found: api-ms-win-core-winrt-l1-1-0.dll dependency of C:\Users\hMd\Desktop\create EXE from pytohn files\Scripts\Controller\qt5bluetooth.dll
19351 WARNING: lib not found: api-ms-win-core-winrt-string-l1-1-0.dll dependency of C:\Users\hMd\Desktop\create EXE from pytohn files\Scripts\Controller\qt5bluetooth.dll
19554 INFO: Looking for eggs
19555 INFO: Using Python library d:\program files\python37\python37.dll
19556 INFO: Found binding redirects:
[]
19568 INFO: Warnings written to C:\Users\hMd\Desktop\create EXE from pytohn files\Scripts\Controller\build\Main\warn-Main.txt
19668 INFO: Graph cross-reference written to C:\Users\hMd\Desktop\create EXE from pytohn files\Scripts\Controller\build\Main\xref-Main.html
19728 INFO: checking PYZ
19728 INFO: Building PYZ because PYZ-00.toc is non existent
19729 INFO: Building PYZ (ZlibArchive) C:\Users\hMd\Desktop\create EXE from pytohn files\Scripts\Controller\build\Main\PYZ-00.pyz
20912 INFO: Building PYZ (ZlibArchive) C:\Users\hMd\Desktop\create EXE from pytohn files\Scripts\Controller\build\Main\PYZ-00.pyz completed successfully.
20933 INFO: checking PKG
20934 INFO: Building PKG because PKG-00.toc is non existent
20935 INFO: Building PKG (CArchive) PKG-00.pkg
21912 WARNING: One binary added with two internal names.
21912 WARNING: ('libGLESv2.dll',
 'D:\\program '
 'files\\python37\\lib\\site-packages\\PyQt5\\Qt\\bin\\libGLESv2.dll',
 'BINARY')
21914 WARNING: was placed previously at
21917 WARNING: ('PyQt5\\Qt\\bin\\libGLESv2.dll',
 'D:\\program '
 'files\\python37\\lib\\site-packages\\PyQt5\\Qt\\bin\\libGLESv2.dll',
 'BINARY')
56741 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
59502 INFO: Bootloader d:\program files\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
59502 INFO: checking EXE
59502 INFO: Building EXE because EXE-00.toc is non existent
59503 INFO: Building EXE from EXE-00.toc
59504 INFO: Appending archive to EXE C:\Users\hMd\Desktop\create EXE from pytohn files\Scripts\Controller\dist\Main.exe
60074 INFO: Building EXE from EXE-00.toc completed successfully.

```
                   

                  
              

### And also when i run .exe file it shows 

![Capture](https://user-images.githubusercontent.com/45208866/73121048-1dbab200-3f8b-11ea-99e8-f8ccb97e58ca.JPG)

**Comment by Legorooj** [comment]
@iamMHZ could you run the exe from the command prompt? Post the traceback.

**Comment by iamMHZ** [comment]
@Legorooj 
![Capture](https://user-images.githubusercontent.com/45208866/74026743-0a144000-49bc-11ea-9295-94adaf827b3e.JPG)

**Comment by Legorooj** [comment]
Hmm. Probably won't make a difference but try just plain old `.\Main.exe`. Are you building with `--onefile`?

**Comment by iamMHZ** [comment]
@Legorooj 

yeah i'm using `--onefile ` and `--windowed`

**Comment by Legorooj** [comment]
@iamMHZ And without those? Does the error persist? If so, when not using one file, in the exe folder there'll be a `running.log` or similar. If you could stick it in a gist?

**Comment by Legorooj** [comment]
@iamMHZ And without those? Does the error persist? If so, when not using one file, in the exe folder there'll be a `running.log` or similar. If you could stick it in a gist?

**Comment by iamMHZ** [comment]
@Legorooj 
I still  have same issues  and 
there is no log file in any folder

**Comment by Legorooj** [comment]
Right two more things:

* Try running from the CLI on a build without `--windowed`
* If there is still no traceback, when you build the app, you get two folders, dist and build. Go into build and find a `warn-****.txt` file, and post that.

**Comment by Legorooj** [comment]
@iamMHZ pinging

**Comment by Jalkhov** [comment]
@Legorooj  I don't know if I can do this but I will publish my problem (which is similar to this one) so as not to create a new topic. First of all, my application works with **PyQt5**, the command line I use to generate the executable is the following: 

`pyinstaller --icon=icono.ico --upx-dir=c:\upx --name myapp main.py`

Then, when I execute the .exe the console closes automatically, to be able to see the message of the console I have to execute the .exe executable from CMD, and the message that throws me is the following one:

```
ImportError: DLL load failed: Invalid access to the memory location was performed.
[3004] Failed to execute main script
```

I'm aware that pyinstaller has (or had) certain problems with PyQt5, the issue that most promises to solve that is the following #3233, but I don't understand absolutely anything they talk about there, the truth is I don't understand much about Github, so what can I do?

**Comment by Legorooj** [comment]
Ok... Could @bjones1 take a look at this? He is the local PyQt expert.

**Comment by bjones1** [comment]
I don't have time to support this.

**Comment by abizinoto** [comment]
Having the asbe issue here

**Comment by zht452432830** [comment]
1. Download .dll files (start with api) from [download website](https://www.exefiles.com/en/extensions/dll/all-files/) (maybe other websites)
2. Install Qt app such as qt-opensource-windows-x86-5.14.2 and find .dll files (start with Qt)
3. Copy all those .dll files to one dir such as C:\Windows\System32\downlevel
4. Then，`pyinstaller -p C:\Windows\System32\downlevel -Fw  --clean your.py`

Summary：download all “not found” .dll files （**right version**） and use -p param

**Comment by Legorooj** [comment]
Please open a new issue if you're still having this problem.
