### ISSUE TITLE
hook for Bleak missing

### ISSUE THREAD

**Issue by vilvo** [pyinstaller/pyinstaller#4649]
## Description of the issue

Using `pyinstaller` with `bleak`-module on Windows creates an executable which fails with "System.IO.FileNotFoundException: Unable to find assembly 'BleakUWPBridge'

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.6
* Platform: Windows 10 (English)
* Did you also try this on another platform? No Does it work there? No (platform-specific hooks for platform-specific Bleak backends are needed)

No need to test with the latest PyInstaller. 
It can be seen from PyInstaller/hooks/ that bleak is missing.

**Comment by Legorooj** [comment]
If you can add a hook that works on *all* platforms, please submit it in a PR.

**Comment by Legorooj** [comment]
We are no longer accepting issues like this. PRs are welcome though.
