### ISSUE TITLE
Add option to automatically bundle the entire stdlib

### ISSUE THREAD

**Issue by jpakkane** [pyinstaller/pyinstaller#4650]
In [Meson](https://github.com/mesonbuild/meson) we would like to be able to run arbitrary Python scripts with our embedded Python. Currently this does not work, because only modules that we use ourselves are put in the distribution package. Trying to use any other module from a third party script fails.

A command line option that would embed all of stdlib would be useful for this case.

This can be worked around by having a fake script that just does:

```python
import re
import path
...
```

would work, but maintaining it by hand in every project that needs this is not particularly nice.

**Comment by Legorooj** [comment]
You mean a new command line option (eg `--include-stdlib`) that means the compiled enviroment would be like a default python install? Plus the other modules you've included of course.

**Comment by jpakkane** [comment]
Yes, exactly.

**Comment by Legorooj** [comment]
@bjones1 what do you think of this?

**Comment by bjones1** [comment]
I don't think this is used frequently enough to merit a command-line option, but would perhaps make a good [recipe](https://github.com/pyinstaller/pyinstaller/wiki/Recipes). A script to iterate through all modules in `sys.prefix + '/lib'`, for example, would probably work.

**Comment by Legorooj** [comment]
Could we bundle another import package with PyInstaller called "pyinstaller_stdlib" that doesn't actually do anything but has a hook file that bundles the stdlib?

**Comment by bjones1** [comment]
That doesn't make sense to me -- how would users specify that they want this package? What would it hook on to? Etc.

However, I can see this being placed in a hook (for meson, etc.) that gathers all the stdlib using code similar to:

``` Python
import sys
import pkgutil

hiddenimports = [x.name for x in pkgutil.walk_packages(sys.prefix + "/lib")]
```

**Comment by Legorooj** [comment]
@bjones1 you have library that does absolutely nothing and is part of PyInstaller (`PyIndstaller.stdlib`) and the user imports it in their script. It has a hook which includes the stdlib in the bundle.

**Comment by bjones1** [comment]
I see. Although this seems like a roundabout approach -- a program imports from PyInstaller, which has no actual effect on the program but does trigger a hook. Perhaps more direct would be adding a hook utility to gather the stdlib, then allowing hooks to call that -- the hook could then be something like 

``` Python
from PyInstaller.hooks import collect_stdlib

hiddenimports = collect_stdlib()
```

... but is the common enough to include in PyInstaller? Again, it seems like a recipe...

**Comment by Legorooj** [comment]
I'm going to close this. @jpakkane if this is a feature you really want, submit a PR. We don't have time to put towards such a little used feature.
