### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by kivdev** [pyinstaller/pyinstaller#4651]
Windows 10 x64
Python 3.8.1 x32
PyInstaller==4.0.dev0+55c8855d9d
CMD: pyinstaller --onefile test_for_build.py
test_for_build.py:

```
import PyInstaller.__main__

PyInstaller.__main__.run([
    '--name=test',
    '--onefile',
    '--windowed',
    '--icon=icon.ico',
    os.path.join('my_package', 'main.py'),
])
```

main.py:

```
print('Hello World')
input()
```
test_for_build.exe:

```
Traceback (most recent call last):
  File "test_for_build.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "c:\python38\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\PyInstaller\__init__.py", line 55, in <module>
  File "site-packages\pkg_resources\__init__.py", line 481, in get_distribution
  File "site-packages\pkg_resources\__init__.py", line 357, in get_provider
  File "site-packages\pkg_resources\__init__.py", line 900, in require
  File "site-packages\pkg_resources\__init__.py", line 786, in resolve
pkg_resources.DistributionNotFound: The 'PyInstaller' distribution was not found and is required by the application
[5292] Failed to execute script test_for_build
```

**Comment by kivdev** [comment]
```
....
11484 INFO: Loading module hook "hook-distutils.py"...
11487 INFO: Loading module hook "hook-encodings.py"...
11626 INFO: Loading module hook "hook-pkg_resources.py"...
11983 INFO: Excluding import '__main__'
11984 INFO:   Removing import of __main__ from module pkg_resources
...
```
maybe this is the problem?

**Comment by Legorooj** [comment]
Umm what exactly are you trying to do? Run compile PyInstaller using PyInstaller? And compile stuff with that?

**Comment by kivdev** [comment]
> Umm what exactly are you trying to do? Run compile PyInstaller using PyInstaller? And compile stuff with that?

I want to create an executable file that takes the name of the script through a parameter, collects everything necessary for it(images, files, etc.) and builds it.

**Comment by Legorooj** [comment]
That won't work - PyInstaller collects stuff from your environment when building. That means that if your script has a library import your exe doesn't, it won't work. Sorry, but we can't offer support for this use of PyInstaller because it won't work.

**Comment by kivdev** [comment]
Do you know what is the most interesting? I had a version of Python 3.7.2 and everything worked, then I replaced it with 3.8, I got an error, I rolled back completely to 3.7.2 - it did not help, I installed all versions of setuptools to the version released before the release of 3.7.2, this did not solve my problem ... It worked, it stopped right now, it's a bug.

**Comment by Legorooj** [comment]
@kivdev I had that at one point - it's a windows caching error. If the PyInstaller build was failing, then try the `--clean` option.

**Comment by kivdev** [comment]
Windows 10 x64
Python 3.7.2 x32
PyInstaller==4.0.dev0+d08a42c612
CMD: pyinstaller --onefile --clean test_for_build.py
test_for_build.py:
```

import PyInstaller.__main__
import os
PyInstaller.__main__.run([
    '--name=test',
    '--clear',
    '--icon=icon.ico',
    os.path.join('main.py'),
])
print(1)
input()
```


The error has not changed.

**Comment by Legorooj** [comment]
To do this you'd need a hook for PyInstaller - we don't have one and won't create one. You'd also need to mod the bootloader process, create runtime hooks, and loads more. We can't, won't and don't support or encourage this.

**Comment by kivdev** [comment]
Suppose I need hooks, but how did it work before, if it cannot work without them?

**Comment by dasiimwe** [comment]
Run into a similar issue. found out pyinstaller is not yet supported on python 3.8.  #4311
