### ISSUE TITLE
Repeatedly building same exe generates different base_library.zip

### ISSUE THREAD

**Issue by dtmaidenmueller** [pyinstaller/pyinstaller#4654]
## Description of the issue
We had previously been using pyinstaller on Python 2.7.  We just recently migrated a codebase to Python 3 and started noticing that the hashes of the resulting build output are no longer the same when the build is re-run with the same code/environment.  We were relying on these hashes, which were previously stable as long as the environment and packaged code remained the same.

The differences seem to be in the base_library.zip file, and it appears that files are being written to that zip file in a different order each time.

## Context information (for bug reports)
* Output of `pyinstaller --version`: ```3.5```
* Version of Python: 3.7.5
* Platform: Windows 10 (v1809)

**Comment by Legorooj** [comment]
Is this actually a bug? Is it affecting your app? If not, then I will close this issue.

**Comment by dtmaidenmueller** [comment]
We would consider it a bug and a regression compared to previous versions of pyinstaller.  Previously, the build was repeatable, now it is not.  We use the hash of the build package to be able to differentiate between builds.

When I get the chance, I'm planning to upload a script + py file that demonstrates the problem without our actual code in the loop.

**Comment by dtmaidenmueller** [comment]
Tested with:
[test_pyinstaller_repeat.zip](https://github.com/pyinstaller/pyinstaller/files/4167362/test_pyinstaller_repeat.zip)

**Comment by Legorooj** [comment]
Looks good. Requested a review from @bjones1
