### ISSUE TITLE
Need arm-linux-gnueabi-objcopy support for arm (cross compile)

### ISSUE THREAD

**Issue by arjuncr** [pyinstaller/pyinstaller#4656]
Currently pyinstaller  supports objcopy (for x86_64/i386) need same for arm (in case of cross compile).    

while cross compile for arm need arm-linux-gnueabi-objcopy instead of objcopy.

**Comment by Legorooj** [comment]
This is unclear. `objcopy` has nothing to do with PyInstaller. How is this related?

**Comment by arjuncr** [comment]
> This is unclear. `objcopy` has nothing to do with PyInstaller. How is this related?

when we are creating executable file for arm using x86 host, during this time pyinstaller should use arm-linux-gnu-objcopy instead of objcopy (its for x86) other wise error will come (unrecognized file format).

**Comment by Legorooj** [comment]
How does PyInstaller know you're building for arm? And which arm platform are you talking?

**Comment by arjuncr** [comment]
> How does PyInstaller know you're building for arm? And which arm platform are you talking?

i am talking about 32 bit soft float arm platform, have to add one provision to pass ( entry inside spec file) target platform related info in pyinstaller so if x86/i386 pyinstaller can use  objcopy or arm 32/64 bit use arm-linux-gnueabi-objcopy (soft float) / arm-linux-gnueabihf-objcopy (hard float).

**Comment by Legorooj** [comment]
I think I see what you mean. This is something for @htgoebel to look at.

**Comment by arjuncr** [comment]
@Legorooj    any update ?

**Comment by Legorooj** [comment]
@arjuncr afraid not. Like I said last comment, you need @htgoebel for something like this.

**Comment by Legorooj** [comment]
@arjuncr might have an update. You want to build for arm Linux from non-arm Linux, correct?

**Comment by arjuncr** [comment]
> @arjuncr might have an update. You want to build for arm Linux from non-arm Linux, correct?

yes, i want to build for arm from non-arm machine.

**Comment by Legorooj** [comment]
@htgoebel please take a look at this.

@arjuncr the possible update turned out to be a dead end. Sorry.

**Comment by arjuncr** [comment]
@Legorooj @htgoebel 
is it possible to add one entry in spec file like,

cross_platform_objcopy = <cross paltform objcopy>

Note: if cross_platform_objcopy is " "  then the code will take default objcopy.   

i think is possible.

**Comment by Legorooj** [comment]
@arjuncr yes something like that would be doable. But I'd recommend `True`/`False` over strings unless there's a reason to use strings?

**Comment by Legorooj** [comment]
@arjuncr sorry, but we can't support this feature at this time. If you want to build for arm, please build on arm.
