### ISSUE TITLE
pyinstaller causes weird behaviour of the app

### ISSUE THREAD

**Issue by chwba** [pyinstaller/pyinstaller#4658]
Using the following commands to pack our applciation.

`pyarmor pack -e " --clean -F -p MRTFiles -p plugins --noupx --onefile" .`

Note, that in MRT.py, there are calls, that will start a python file located in the MRTFiles folder(subprocess.popen(executeable, "./MRTFiles/attack_controller", ...)

The main app does start but once I start a feature it will just start the main application again.

**Comment by Legorooj** [comment]
Can you please provide tracebacks, what's the bug, etc. We can't help if you can't provide info.

**Comment by chwba** [comment]
Check https://github.com/dashingsoft/pyarmor/issues/180 for details

**Comment by jondy** [comment]
Just ignore pyarmor, it should be same to run this command by PyInstaller:
```
pyinstaller  --clean -F -p MRTFiles -p plugins --noupx --onefile MRT.py
```

**Comment by jondy** [comment]
This problem could be described by another way. How PyInstaller to pack these 2 scripts to one bundle?

The main scripts is `MRT.py`:
```python
import sys
import subprocess

if len(sys.argv) > 2 and sys.argv[1] == "./MRTFiles/attack_controller.py":
    subprocess.Popen(sys.executeable, "./MRTFiles/attack_controller.py")
else:
    print('Main program')
```

The other script is `./MRTFiles/attack_controller.py`:
```
print('This is a feature')
```

One problem is that `sys.executeable` is not python interpreter in the final bundle, the other problem is that the final bundle always reports the following error when start the feature
```
PyInstaller cannot check for assembly dependencies.
Please install pywin32-ctypes.

pip install pywin32-ctypes
```

**Comment by Legorooj** [comment]
Ok I think I understand. `sys.executable` is what it is meant to be. Could you send a *minimal* zipped example that showcases this to legorooj@protonmail.com? Ready to unzip and poke at?

**Comment by Legorooj** [comment]
Hello?

**Comment by jondy** [comment]
@Legorooj 
I have list 2 files for one minimal example above, main script is  `MRT.py`, and the other is `MRTFiles/attack_controller.py`. Actually this is not my problem, I just help @chwba to fix this problem, I may not know the more details.

**Comment by Legorooj** [comment]
I need a bit more help from @chwba to fix this.

**Comment by chwba** [comment]
Sorry, there was a lot of work the past 2 weeks, sending the full source to legorooj@protonmail.com now

**Comment by chwba** [comment]
@Legorooj sent

**Comment by Legorooj** [comment]
@chwba I've received the msg. I'll have a look when on PC.

**Comment by chwba** [comment]
@Legorooj let me know if there is anything I can do to help

**Comment by chwba** [comment]
@Legorooj any news?

**Comment by Legorooj** [comment]
@chwba yes. So I've figured out how to fix you're problem. You said that every time you started a feature, the main app starts again. The problem is, when compiled, `sys.executable` is the compiled program. In other words, every time you start a new feature, you start the app again. You'll need to recreate the app structure, using imports like `myfeature.py` is import `MRTFiles.myfeature` and `myfeature.main()` to run it.

**Comment by chwba** [comment]
Actually thats not the problem, everytime when I start the feature nothing happens

**Comment by chwba** [comment]
Also sys.executable is supposed to be the python executable which is passed to the subprocess to open a different python script when a button is clicked

**Comment by Legorooj** [comment]
@chwba `sys.executable` when frozen is the exe; we don't bundle the python executable, only the DLL. 

> The main app does start but once I start a feature it will just start the main application again.

Please try using imports instead, or wait a bit until `MERGE` is fixed.

**Comment by chwba** [comment]
@Legorooj When will MERGE be fixed (and what is it? :D)

**Comment by Legorooj** [comment]
@chwba MERGE allows you to create multiple executables in the same environment. Each executable file has access to the same imports. https://pyinstaller.readthedocs.io/en/stable/spec-files.html#multipackage-bundles

**Comment by chwba** [comment]
@Legorooj so if we wait until this is released we dont have to rewrite the application?

**Comment by Legorooj** [comment]
@chwba yes - but you need to manually edit the spec file. It's doable, just *very* complex.
