### ISSUE TITLE
Cannot dlsym for Py_SetPath 

### ISSUE THREAD

**Issue by hathemi** [pyinstaller/pyinstaller#4665]
i have creat an exe file with pyinstaller command, but it won't be execute due this error.how can i fix it?

**Comment by Legorooj** [comment]
This is unclear. Please can you post the whole error, your OS, python version, and PyInstaller version?

**Comment by hathemi** [comment]
thank you @Legorooj for respond. 
that was the only line showed up on terminal.
i found out that i have to put the absolute path of document not relative path.
