### ISSUE TITLE
Travis test failures with Python 3.7 and PyQt 5.14.1

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#4666]
I'm seeing intermittent test failures under Python 3.7 and PyQt 5.14.1 only when testing QtWebEngine, wihch started in f40a8d84abded8ea8ac1ed7277b6d3e40ed74b4b. The failure message is ``Inconsistency detected by ld.so: dl-tls.c: 493: _dl_allocate_tls_init: Assertion `listp->slotinfo[cnt].gen <= GL(dl_tls_generation)' failed!``. This produced by a [known glibc bug](https://sourceware.org/bugzilla/show_bug.cgi?id=19329), which has been open for 4+ years. I don't know of an easy workaround for this.

**Comment by Legorooj** [comment]
Let me guess that there is no way to remove `glibc`. It's gonna be a dependency of Qt isn't it?

**Comment by bjones1** [comment]
It's a dependency of pretty much any program. I opened this for informational purposes, to document what I knew and where the problem is.

**Comment by Legorooj** [comment]
Damn. Is there any workaround short of fixing the `glibc` bug?

**Comment by bjones1** [comment]
Not that I know of. However, it's intermittent...

**Comment by Legorooj** [comment]
@bjones1 really? Hmm. Let me see if I can see a pattern. All the analytical data I'd need is public isn't it?

**Comment by bjones1** [comment]
Yes, it's in the Travis CI results.

**Comment by Legorooj** [comment]
@bjones1 Can you link to some of them? I'm unable to find PyQt5 related failiures *at all*.

**Comment by bjones1** [comment]
I'll have to dig some...but if current PRs/commits aren't affected, perhaps this occurs very occasionally. I'd suggest closing it for now, but reopening if it pops up again.

**Comment by Legorooj** [comment]
I'll close then. If you notice one failing because of that again, let me know.

**Comment by Legorooj** [comment]
https://travis-ci.org/pyinstaller/pyinstaller/jobs/651959687?utm_medium=notification&utm_source=github_status

**Comment by Legorooj** [comment]
@bjones1 I'll try and raise this error on my Linux VM. It'll be interesting to see if it occurs on Debian(Well Kali).

**Comment by Legorooj** [comment]
@bjones1 what are the chances of this being completely unrelated to PyInstaller? As in nothing we do will fix it?

**Comment by bjones1** [comment]
Very high -- it seems like a race condition, based on the bug report. The only thing I know to do is find ways to avoid triggering this.

**Comment by Legorooj** [comment]
@bjones1 can we make the test fail and not fail at the same time if you mean? Eg "All checks passed successfully" but if you go into Travis you can see the error?

**Comment by bjones1** [comment]
We can mark this one test as xfail or even skip it, but then that leaves testing holes.

**Comment by Legorooj** [comment]
Can we get Travis to pass but with a warning?

**Comment by bjones1** [comment]
We can mark it as [xfail](http://doc.pytest.org/en/latest/skipping.html#xfail-mark-test-functions-as-expected-to-fail), but this means it's allowed to fail for any reason (an actual bug in PyInstaller or this internal error we don't care about).

**Comment by Legorooj** [comment]
Is it possible to, in the test, fail silently if it's that specific bug? If we can trace the specific error, we can xfail with the raises parameter or similar. Let me have a look into that.

**Comment by bjones1** [comment]
Probably -- perhaps we could catch the exception that pytest.fail raises [here](https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/conftest.py#L268)? But this doesn't provide a way to look at the stderr. So, that sounds messy.

Perhaps we should just mark this as an xfail in Linux only and move on.

**Comment by Legorooj** [comment]
One more idea. `with contextlib.suppress(TypeError):`. You can suppress any exception. It simply won't be raised. Is there a way that could be worked in?

If not, then marking it as xfail on Linux is probably the best option.

**Comment by bjones1** [comment]
I don't think it would help -- xfail is a more descriptive way to do the same thing.

**Comment by Legorooj** [comment]
Ok then. PR needed.
