### ISSUE TITLE
Enable long file path support in Windows executables

### ISSUE THREAD

**Issue by logan-pugh** [pyinstaller/pyinstaller#4668]
**Is your feature request related to a problem? Please describe.**
On Windows, when a file system path over 260 characters is encountered by a PyInstaller application, an error occurs *unless* [long path support](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file#enable-long-paths-in-windows-10-version-1607-and-later) is enabled.

Attempting to enable long path support using a manifest and the `--manifest` option fails because the generated manifest file omits the necessary contents even when contained in the specified manifest file.

**Describe the solution you'd like**
Either add an explicit option similar to the `--uac-admin` and `--uac-uiaccess` options or rework the `--manifest` option to work in a way that honors the `longPathAware` setting in the specified manifest file. The latter option may be preferable if [additional manifest options](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests) such as [`dpiAware` ](https://docs.microsoft.com/en-us/windows/win32/sbscs/application-manifests)are desired and additional PyInstaller command line options are difficult to add.

**Describe alternatives you've considered**
A workaround to the issue is to create an external application manifest file, named `<program_name>.exe.manifest`, in the directory containing the PyInstaller-built executable:

```xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
    </windowsSettings>
  </application>
</assembly>
```

However this is less portable than a correctly-defined, embedded manifest.

**Additional context**
See this StackOverflow question for more details: https://stackoverflow.com/questions/59742078/enabling-windows-long-file-path-support-in-pyinstaller-application

**Comment by Legorooj** [comment]
We can't do this unfortunately. This is a system problem, not a PyInstaller one. Most users don't need long path support, and the few who do can mod their *system* themselves. PyInstaller can't be playing with the registry.

**Comment by logan-pugh** [comment]
@Legorooj I am not asking for anything to do with the registry, only the application manifest. Could you reopen the issue?

**Comment by Legorooj** [comment]
@logan-pugh there are minimal users who need this. Would adding something to the docs be helpful, so that users can do this themselves?

**Comment by logan-pugh** [comment]
@Legorooj I agree would be good to document the workaround I mentioned (perhaps in the [Recipes](https://github.com/pyinstaller/pyinstaller/wiki/Recipes) section of the wiki), as well as the registry setting the end user (or their administrator) would need to enable.

However PyInstaller should let the developer embed the application manifest with the necessary contents, that way they don't need to distribute or require the user to create an external manifest file.

I would also somewhat consider it to be a bug that the `--manifest` option does not honor all of the contents of the provided manifest file (at least it does not seem to in my attempts). Fixing that would resolve this issue, and as I mentioned there are other manifest settings, such as `dpiAware`, that have the same issue.

I'm guessing the logic that merges the manifests would just need to be updated to include the `application` element of the provided manifest file, but I have not looked too deeply at the code yet.

**Comment by Guts** [comment]
> @logan-pugh there are minimal users who need this. Would adding something to the docs be helpful, so that users can do this themselves?

Not so minimal, I'm pretty interested by the @logan-pugh proposal :).

**Comment by Legorooj** [comment]
@Guts @logan-pugh I'll look into this more. (Apologies about last comment; apparently I was cranky.) 

The `--manifest` option could do with an upgrade. I'll add this to my plate... ETA a few months before I actually get round to it.
