### ISSUE TITLE
Hooks for the smartsheet-python-sdk module

### ISSUE THREAD

**Issue by MaddiLoo** [pyinstaller/pyinstaller#4669]
I am not sure if this is a bug or a feature request.... but I'm pretty sure it's a feature request.

I have seen a lot of questions on the internet about how to get the smartsheet-python-sdk module running in pyinstaller with no solution. I have been trying for a while to create my own hook for it but can't figure it out. It's not a very complicated module and I feel like if I was more familiar with creating pyinstaller hooks it would be an easy one to do. Maybe you could make more sense of what I've found so far and shared in this [Stackoverflow post](https://stackoverflow.com/questions/60106700/need-to-create-a-hook-for-the-smartsheet-python-sdk-and-pyinstaller)

**Comment by Legorooj** [comment]
@MaddiLoo unfortunately we don't have time to build hooks for libraries. I will have to close this, but we can keep talking and offer guidance.

**Comment by MaddiLoo** [comment]
Ok that's fair. Do you have any idea where I'm going wrong in the Stackoverflow post I linked? It feels like I'm close to figuring it out. If I do figure it out I'll share the results.

**Comment by Legorooj** [comment]
What are the imports on your file? Just plain old `import smartsheet`?

**Comment by MaddiLoo** [comment]
I've tried `import smartsheet` and `from smartsheet import models`

**Comment by Legorooj** [comment]
Try adding the hidden import option on the command line multiple times, ie once for each import from the requirements listed in the [smartsheet readme](https://github.com/smartsheet-platform/smartsheet-python-sdk/blob/master/README.md)
* `--hidden-import=MODULE_NAME`

**Comment by MaddiLoo** [comment]
Ok that broke it completely but I think I know what the issue is now. It seems like some of the pyinstaller hooks aren't.... hooking things. There are a lot of missing modules from urllib3, pkg_resources, and the wincom32.gen_py module is missing. I attached my warning file below.
[warn-snow_gps.txt](https://github.com/pyinstaller/pyinstaller/files/4195920/warn-snow_gps.txt)

**Comment by Legorooj** [comment]
@MaddiLoo at least we know (think) that this is just missing imports. You'll need to trace all of the modules you're missing. Basically you have to dependency walk the smart sheet modules you're using, and their dependencies, etc. Write those down, imports in functions or if statements as well, then check if any of those are in the warn file. Then add missing dependencies with hidden imports. Ignore dependencies you don't have installed at first - only try those if the others don't work.
