### ISSUE TITLE
TrojanDropper:Win32/CryptInject!MSR

### ISSUE THREAD

**Issue by ArveLomsland** [pyinstaller/pyinstaller#4670]
There is a Trjoan in \bootloader\Windows-32bit\runw.exe

TrojanDropper:Win32/CryptInject!MSR

**Comment by lstolcman** [comment]
@ArveLomsland not a bug: https://github.com/pyinstaller/pyinstaller/issues/4343#issuecomment-516817073

**Comment by Legorooj** [comment]
Please see https://github.com/pyinstaller/pyinstaller/issues/4343#issuecomment-516817073

**Comment by NHades** [comment]
I had same issue last week with Microsoft Defender.  
I reported it to them and they fixed issue with latest definitions update.

**Comment by Legorooj** [comment]
@NHades awesome.
