### ISSUE TITLE
Add another hooks repo

### ISSUE THREAD

**Issue by Legorooj** [pyinstaller/pyinstaller#4673]
PyInstaller is getting an extraordinary amount of hook related pull requests. I think we should migrate hooks to another repo, and add a command line app (`pyi-addhook`) that installs the extra hooks from said repo. Maybe even support something like `pyi-addhook django`, which installs the hook for Django?

**Comment by Legorooj** [comment]
To be clear we should still include a select set of hooks, but a cut down version of the expanse we have.

**Comment by Legorooj** [comment]
An an update:

* I have an FTP server - I could make a public folder with read access for everyone.
* This folder would automatically get refreshed from the repo every 7 days - I can code an app to do that from the same server.

**Comment by bjones1** [comment]
I agree that hook requests dominate PRs and issues, distracting from core development. These need to go elsewhere. Some ideas:

- A lot of hooks have questionable quality and come with no testing. Perhaps we could create a separate package that accepts third-party, untested hooks. This would be the first destination for all untested hooks.
- Hooks that include a test, including many hooks currently provided by PyInstaller, should be integrated with the library they support. This new feature is almost complete; see #4582.
- On a side note, I think that all issues with hooks not working or not present should be closed. We should no longer maintain hooks, but instead maintain PyInstaller. Any hook support would come from library maintainers / 3rd party hook authors in a separate package.

**Comment by Legorooj** [comment]
@bjones1 so maybe close all current hook requests (and remove some minor hooks from the core) with the message that the library developers need to maintain them? 

Even so I still think that we need a centralised place to store hooks. Would a pypi like web service be helpful?

**Comment by bjones1** [comment]
I'd wait on this until #4582 is merged, then start working to move hooks out of PyInstaller and into libraries (tested) or another hooks-only package (untested).

**Comment by Legorooj** [comment]
@bjones1 sounds good.

**Comment by htgoebel** [comment]
Sounds good for me :-)
@Legorooj This idea basically already come in #4232, which nobody worked on. Now that @bjones1 implemented it #4582, this is a good point to pick this up again. There already is a repo https://github.com/pyinstaller/pyinstaller-hooks which could be used as a base. We could also an another repoo (e.g. pyinstaller-hooks-contrib) for untested/contributed hooks, as @bjones1 suggested. For both we could set up automated releases (which I do not want for PyInstaller core due to the bootloaders).

Re teh command line tool: IMHO there is no need for it as there already is pip :-)

**Comment by Legorooj** [comment]
@htgoebel I agree; with the new entry point, we just release a package (PyInstaller-hooks-contrib) that installs extra hooks. I'd be happy to manage the whole thing - I've experience with auto releases - and it saves your time. I think I've learned PyInstaller well enough to run a hooks repo.

**Comment by Legorooj** [comment]
@htgoebel heres an idea:

* PyInstaller-hooks-contrib. A sister package that uses the new entry point - and testing entry points.
* Incremental builds via CI; every couple of days, the maintainer triggers a new build (eg 3.6.build-no) with the first part of the version number the current stable PyInstaller version.
* Looser commit messages and changelog requirements; they're the biggest bottleneck on hook merges at the moment
* It's community maintained - with one/two moderators who merge stuff in.

Once something like that is setup, we migrate most hooks out of PyInstaller and into that package. There'll be a few exceptions, eg PyQt5 etc - hooks heavily integrated into PyInstaller - but we move most stuff, then redirect all current hook PRs to that repo.

Finally, I'll set it all up if you want. I'd just need a new repo (`pyinstaller-hooks-contrib`) in the org, and owner level permissions on it.

**Comment by bjones1** [comment]
I second this proposal -- that makes a lot of sense. When I finally get around to finishing this PR, let's do this, then also move as many hooks "upstream" into the packages they support as we can.

**Comment by Legorooj** [comment]
@bjones1 I can do that - if I do end up running something like a contrib package, I'll migrate hooks to there, and over time migrate them upstream.

**Comment by htgoebel** [comment]
@Legorooj @bjones1 I just created https://github.com/pyinstaller/pyinstaller-hooks-contrib/ and made you Administrators there. (If one can tell me how to make you "owners", I can to this, too.) You should have gotten an invite already.

@Legorooj I perfectly fine with your proposal. Please go ahead!
- [ ] Please state the different policy in the Readme.
. [ ] Please provide a (short) paragraph for the manual
- [ ] Please provide a changelog entry ;-)
- [ ] Whare shlla this alos be noted? Readme? wiki?

Only open point is: Which hooks to move to pyinstaller-hooks-contrib. I propose
- All currently open new hook requests (please let me know if you need extra permissions to do so)
- All hooks where we do not have a test for in PyInstaller.
- All "small" hooks, where we have a test for, but which are contributed and not maintained by us. These are only a few, located in `test_libraries`, e.g. boto, tensorflow, enchant, zmq and some near the end. I have no strong criteria about, anyway one could be whether "we" changed it.
  For now I would leave "big" hooks, like Qt, which (currently) require extra support in PyInstaller with PyInstaller. (We can rethink pyinstaller-hooks #2692 later.
- All issues about packages not working which we do not provice a hook for in core.

@Legorooj @bjones1 Please also send give me your PyPi  account name, so i can grant you access to https://pypi.org/project/pyinstaller-hooks-contrib/ and https://pypi.org/project/pyinstaller-hooks.

**Comment by Legorooj** [comment]
@htgoebel the PyPI name is also legorooj. (https://pypi.org/user/Legorooj/).

RE which hooks to move, I think all of the hooks not integrated into PyInstaller (eg PyQt5; it has its own section of the utils).

I'll submit a PR removing hooks (and tests) from this repo as soon as I've got the others ready. I'll also close issues and PRs in this repo, with a note to copy them across to hooks-contrib, when it's all ready for PRs.

I'll have clear instructions in the new repos README with a clear policy. I'll also, when (re)moving hooks, submit an edit to the docs/README here pointing to the new repo.

Give me a few days to get this setup. :wink:

**Comment by bjones1** [comment]
This sounds great! I agree on moving all hooks not deeply tied to PyInstaller. I'm bjones on PyPi (https://pypi.org/user/bjones/).

**Comment by htgoebel** [comment]
1. I would *not* move hooks for major packages to "contrib", when if they are not "deeply tied to PyInstaller". Hooks for major packages I would keep in PyInstaller until we can push upstreams. I'm not confident there will be a community maintaining these, so we will still be reponsible and this will not be "contributed".

  I suggest keeping: babel,  future, gevent,,  gi.*, Pillow, numpy, scipy, pygments, PySide*, PyQt*, pytz, requests, sphinx, sqlalchemy, zope.interface, pandas, Django, mtploglib, keyring.

2. Hooks for the standard lib IMHO shall remain parts of PyInstaller.

3. Github seems to allow moving issues to other repos. Thus I suggest doing to instead of closing the issues.

**Comment by Legorooj** [comment]
@htgoebel I can't move issues - I'd need admin permissions on both repositories.
