### ISSUE TITLE
Segmentation fault (core dumped) Error while running EXE .

### ISSUE THREAD

**Issue by sameerCoder** [pyinstaller/pyinstaller#4675]
Hi, 
I have created EXE of python file using auto-py-to-exe . While running the exe half of the python program is working fine but after some time i am getting **Error :** 
**(base) username@username-Desktop:~/cartopy2$ ./cartopy2
run fun
/home/username/anaconda3/lib/python3.7/site-packages/PyInstaller/loader/pyimod03_importers.py:623: MatplotlibDeprecationWarning: 
The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
  exec(bytecode, module.__dict__)
Segmentation fault (core dumped)**
All the modules are ok , autopytoexe is also ok as other python exe is working fine only while running this exe i am getting error - Segmentation fault (core dumped)
**Can you please tell me How to solve this Segmentation fault (core dumped )**

**Comment by Legorooj** [comment]
@sameerCoder this is unclear. Can we please have more info?

**Comment by sameerCoder** [comment]
Hi,
    Actually i made exe of my python script using autopyexe , there is no error in making  autopyexe  exe as other simple programe exe is working fine but this matplotlib , cartopy exe while running is giving Error :- Segmentation fault (core dumped ) after running half of the code of script ,

**For More details you can go to this link https://github.com/brentvollebregt/auto-py-to-exe/issues/87**
Kindly let me know how to solve this segmentation fault while running the Exe.
Thank you

**Comment by Legorooj** [comment]
@htgoebel you're the Linux guru. Could you take a look at this?
