### ISSUE TITLE
pyinstaller doesn't pack my own modules

### ISSUE THREAD

**Issue by paulgr2008** [pyinstaller/pyinstaller#4676]
I have a project like this:
proj -
       main.py
       another.py

and I have in main.py 'import' string like this:
import another
...

Pyinstaller doesn't include file another.py to the final .exe file (and running script failed) and I have to copy it to the folder with .exe file by myself. Then it's working properly. Is it possible to do something with that or it's normal practice for modules which doesn't be installed by setuputils etc.?

**Comment by zachbateman** [comment]
@paulgr2008 what command do you use to package your project with PyInstaller, and what error does the .exe throw when it fails?

You shouldn't have to copy another.py to the .exe folder.  As long as you have "import another" at the top of main.py, Pyinstaller should include another.py in the resulting file or folder.

**Comment by Legorooj** [comment]
If it works when you copy the files, then the `--add-data` option is what you need.
