### ISSUE TITLE
Use Python >= 3.5 on Windows < 10

### ISSUE THREAD

**Issue by aglpy** [pyinstaller/pyinstaller#4679]
There is a known issue, when compile a python script with Python higher than 3.5 to run the exe file on Windows 7 (for example), it doesn't run.

Here on docs it is explained 3 ways to solve this issue: https://pyinstaller.readthedocs.io/en/stable/usage.html#platform-specific-notes-windows

I prefer to use the solution 2, because I use windows 10 and I can't install software on the final pc (with windows 7). 

Which are the exact binaries files I need to include on the script compilation? And where to get that files?

**Comment by Legorooj** [comment]
Method 2 doesn't mean PyInstaller. It means a tool like innosetup, or an installation wizard. Then the software that installs your software will also install the needed DLLs.

You'll have to find the DLLs yourself, but they'll probably be in system32 or another windows folder.
