### ISSUE TITLE
Improved requirements management

### ISSUE THREAD

**Issue by bjones1** [pyinstaller/pyinstaller#4681]
We should move away from simply installing from `requirements-*.txt`, and instead use a `requirements-*.in` along with [pip-compile](https://pypi.org/project/pip-tools/) to avoid surprises when a version change of the dependencies of our requirements change. We should also change pyup to then update requirements in these in files, then regenerate the .txt files (probably manually).

**Comment by bwoodsend** [comment]
Honestly, I can count the number of times an update to an indirect dependency caused (relatively minor) disruption on one finger so I don't consider this worth it.
