### ISSUE TITLE
Qt not copying libs into .app bundle

### ISSUE THREAD

**Issue by RichsJeson** [pyinstaller/pyinstaller#4683]
When I build a .app bundle, PyInstaller doesn't copy the required libraries into it. 

4036 WARNING: Hidden import "PyQt5.QtWebSockets.abi3" not found!
4037 WARNING: Hidden import "PyQt5.QtRemoteObjects.abi3" not found!
4037 WARNING: Hidden import "PyQt5.QtWidgets.abi3" not found!
4037 WARNING: Hidden import "PyQt5.QtHelp.abi3" not found!
4037 WARNING: Hidden import "PyQt5.QtPositioning.abi3" not found!
4037 WARNING: Hidden import "PyQt5.QtGui.abi3" not found!
4037 WARNING: Hidden import "PyQt5.QtOpenGL.abi3" not found!
4037 WARNING: Hidden import "PyQt5.QtPrintSupport.abi3" not found!
4038 WARNING: Hidden import "PyQt5.QtSerialPort.abi3" not found!
4038 WARNING: Hidden import "PyQt5.QtSql.abi3" not found!
4038 WARNING: Hidden import "PyQt5.QtQml.abi3" not found!
4038 WARNING: Hidden import "PyQt5.QtBluetooth.abi3" not found!
4038 WARNING: Hidden import "PyQt5.QtLocation.abi3" not found!
4038 WARNING: Hidden import "PyQt5.QtSvg.abi3" not found!
4039 WARNING: Hidden import "PyQt5.QtWebEngineWidgets.abi3" not found!
4039 WARNING: Hidden import "PyQt5.QtMacExtras.abi3" not found!
4039 WARNING: Hidden import "PyQt5.QtSensors.abi3" not found!
4039 WARNING: Hidden import "PyQt5.QtDesigner.abi3" not found!
4039 WARNING: Hidden import "PyQt5.QtXmlPatterns.abi3" not found!
4040 WARNING: Hidden import "PyQt5.QtNetworkAuth.abi3" not found!
4040 WARNING: Hidden import "PyQt5.QtMultimediaWidgets.abi3" not found!
4040 WARNING: Hidden import "PyQt5.QtWebChannel.abi3" not found!
4040 WARNING: Hidden import "PyQt5.QtNetwork.abi3" not found!
4040 WARNING: Hidden import "PyQt5.QtCore.abi3" not found!
4040 WARNING: Hidden import "PyQt5.QtNfc.abi3" not found!
4040 WARNING: Hidden import "PyQt5.QtTest.abi3" not found!
4041 WARNING: Hidden import "PyQt5.QtQuick.abi3" not found!
4041 WARNING: Hidden import "PyQt5.QtWebEngine.abi3" not found!
4041 WARNING: Hidden import "PyQt5.Qt.abi3" not found!
4041 WARNING: Hidden import "PyQt5.QtDBus.abi3" not found!
4041 WARNING: Hidden import "PyQt5.QtMultimedia.abi3" not found!
4041 WARNING: Hidden import "PyQt5.QtQuickWidgets.abi3" not found!
4041 WARNING: Hidden import "PyQt5.QtXml.abi3" not found!
4041 WARNING: Hidden import "PyQt5.QtWebEngineCore.abi3" not found!
4042 INFO: Loading module hook "hook-PyQt5.QtMultimedia.py"...
4080 INFO: Loading module hook "hook-PyQt5.QtSql.py"...
4123 INFO: Loading module hook "hook-PyQt5.QtQml.py"...
4204 INFO: Loading module hook "hook-PyQt5.QtQuickWidgets.py"...
4267 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
4308 INFO: Loading module hook "hook-PyQt5.QtNetwork.py"...
4326 INFO: Loading module hook "hook-xml.py"...
4582 INFO: Loading module hook "hook-pydoc.py"...
4583 INFO: Loading module hook "hook-PyQt5.QtTest.py"...
4626 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
4636 INFO: Loading module hook "hook-PyQt5.QtSvg.py"...
4674 INFO: Loading module hook "hook-PyQt5.QtXml.py"...
4694 INFO: Loading module hook "hook-PyQt5.QtSerialPort.py"...
4718 INFO: Loading module hook "hook-PyQt5.QtHelp.py"...
4772 INFO: Loading module hook "hook-PyQt5.QtQuick.py"...
4830 INFO: Loading module hook "hook-PyQt5.QtSensors.py"...
4855 INFO: Loading module hook "hook-PyQt5.QtOpenGL.py"...
4919 INFO: Looking for ctypes DLLs
4919 INFO: Analyzing run-time hooks ...
4922 INFO: Including run-time hook 'pyi_rth_pyqt5webengine.py'
4923 INFO: Including run-time hook 'pyi_rth_pyqt5.py'
4927 INFO: Looking for dynamic libraries
5040 ERROR: Can not find path ./Qt3DRender.framework/Versions/5/Qt3DRender (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
5040 ERROR: Can not find path ./Qt3DAnimation.framework/Versions/5/Qt3DAnimation (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
5040 ERROR: Can not find path ./Qt3DLogic.framework/Versions/5/Qt3DLogic (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
5040 ERROR: Can not find path ./QtGamepad.framework/Versions/5/QtGamepad (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
5041 ERROR: Can not find path ./Qt3DInput.framework/Versions/5/Qt3DInput (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
5041 ERROR: Can not find path ./Qt3DCore.framework/Versions/5/Qt3DCore (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
5126 ERROR: Can not find path ./Qt3DRender.framework/Versions/5/Qt3DRender (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
5127 ERROR: Can not find path ./Qt3DQuick.framework/Versions/5/Qt3DQuick (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
5127 ERROR: Can not find path ./Qt3DLogic.framework/Versions/5/Qt3DLogic (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
5127 ERROR: Can not find path ./QtGamepad.framework/Versions/5/QtGamepad (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
5127 ERROR: Can not find path ./Qt3DQuickScene2D.framework/Versions/5/Qt3DQuickScene2D (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
5127 ERROR: Can not find path ./Qt3DInput.framework/Versions/5/Qt3DInput (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
5127 ERROR: Can not find path ./Qt3DCore.framework/Versions/5/Qt3DCore (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
5140 ERROR: Can not find path ./QtMultimediaQuick.framework/Versions/5/QtMultimediaQuick (needed by /usr/local/lib/python3.7/site-packages/PyQt5/Qt/qml/QtMultimedia/libdeclarative_multimedia.dylib)

**Comment by bjones1** [comment]
Already fixed in master.

**Comment by Sandural** [comment]
i still have the problem

**Comment by coldfire79** [comment]
I think it's not fixed yet.

**Comment by gauthierbuttez** [comment]
I confirm. It is not fixed at all!

**Comment by bwoodsend** [comment]
Fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) properly. Tell us your macOS specs. Tell us how you installed Python + Qt. Then we'll reopen this. At the moment this is just useless noise.

**Comment by rokm** [comment]
That's probably #5638, and unrelated to this issue.
