### ISSUE TITLE
lint check on CI six incompatability error

### ISSUE THREAD

**Issue by Legorooj** [pyinstaller/pyinstaller#4686]
https://travis-ci.org/pyinstaller/pyinstaller/jobs/651034980?utm_medium=notification&utm_source=github_status line 727 shows that pyinstaller needs `six`. 

Why do we need this anymore? We don't support py2.

**Comment by bjones1** [comment]
py3 code that hasn't migrated away from six still needs it.

**Comment by Legorooj** [comment]
@bjones1 expected a PR soon then.
