### ISSUE TITLE
Switch to Azure pipelines for CI instead of Travis and Appveyor

### ISSUE THREAD

**Issue by Legorooj** [pyinstaller/pyinstaller#4688]
I think we ought to consider moving CI to Azure Pipelines for open source, due to the fact we can therefore run on one CI, not two, we get unlimited minutes in Pipelines, and 10 concurrent jobs. Thoughts @bjones1 and @htgoebel?

**Comment by bjones1** [comment]
Not free for PyInstaller-scale usage (1800 minutes/month free tier = 30 hours); given 8 1 hour build per PR, this is nothing. Also, I suspect @htgoebel isn't a big Microsoft fan.

**Comment by Legorooj** [comment]
@bjones1 maybe you didn't see that open source organisations - if you register as one - get unlimited minutes? And 10 concurrent jobs, not 3. Harmut may not, or may, but if we can get something like this *for free*, it's worth considering.

**Comment by bjones1** [comment]
I see that now. But it will take dev work to get this going...

**Comment by Legorooj** [comment]
@bjones1 I could definitely do the switch. I just need @htgoebel's approval...

**Comment by Legorooj** [comment]
Oh and @bjones1 could you send me an email at legorooj@protonmail.com? I'd like to discuss a PyInstaller GUI I have in development.

**Comment by Legorooj** [comment]
Just for info we already use Microsoft. I found out that ReadTheDocs is hosted on Microsoft Azure. Microsoft cover the costs, equalling about USD$3000/month. I think Msoft are quite good now. (They didn't used to be though - a lot of open source people don't like them, because of what they did over a decade ago)

@bjones1 did you send me an invite for that google hangout? I didn't get one.

**Comment by bjones1** [comment]
@Legorooj invitation sent.

**Comment by Legorooj** [comment]
Actually, this isn't needed.
