### ISSUE TITLE
(How to) Ensure only 1 process / disallow parallelism / detect running process?

### ISSUE THREAD

**Issue by gotexis** [pyinstaller/pyinstaller#4690]
Hi, I have searched a lot of places, but I don't think this is mentioned as far as I have searched.

I am running a `flask` server inside a pyinstaller which is called by an `electron` instance. I am uncertain about the `electron` `will-quit` hook, but it doesn't seem to terminate my flask service properly as I have coded. (Could any `electron` users please advice)?

So I would have a pile of background service running, so long as I close `electron` app and reopen.

Thanks, and please advise!

**Comment by gotexis** [comment]
Update: I see what's happening. The process.ID recorded by node when spawning pyinstaller instance is not the same one as the real python process id, so it seems like pyinstaller has a wrapper that futher spawn the real program.

With that said, I am yet to find a solution.

**Comment by Legorooj** [comment]
@gotexis Sorry, but the pyinstaller team doesn't have time or funding to help you with this. StackOverflow or freenode#pyinstaller are the best places to ask for help
