### ISSUE TITLE
AV detecting it as malicious file

### ISSUE THREAD

**Issue by tbhaxor** [pyinstaller/pyinstaller#4694]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
I am building my `app.py`, which is a selenium driven application using pyinstaller 3.6 (also used the development version). As soon as it creates an executable in dist directory, the windows defender detects it as malicious code and immediately quarantines that. I want to publish this application for my customers. 

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.1
* Platform: Windows
* Did you also try this on another platform? Does it work there? In Linux there is no antivirus installed, its working fine there

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with celan installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
Windows defender detected app.exe as a malicious file.
```

### Stacktrace / full error message

```
139 INFO: PyInstaller: 3.6
140 INFO: Python: 3.7.1
142 INFO: Platform: Windows-10-10.0.18362-SP0
146 INFO: wrote C:\pythonprograms\linkedinv1\app.spec
152 DEBUG: Testing for UPX ...
192 INFO: UPX is not available.
221 DEBUG: script: C:\pythonprograms\linkedinv1\app.py
223 INFO: Extending PYTHONPATH with paths
['C:\\pythonprograms\\linkedinv1', 'C:\\pythonprograms\\linkedinv1']
249 INFO: checking Analysis
348 INFO: checking PYZ
428 INFO: checking PKG
456 INFO: Building because C:\pythonprograms\linkedinv1\build\app\app.exe.manifest changed
456 INFO: Building PKG (CArchive) PKG-00.pkg
2754 DEBUG: Compiling c:\users\deven\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py
2754 DEBUG: Compiling c:\users\deven\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py
2763 DEBUG: Compiling c:\users\deven\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pyqt5.py
2772 DEBUG: Compiling c:\users\deven\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_pyqt5.py
2779 DEBUG: Compiling C:\pythonprograms\linkedinv1\app.py
2787 DEBUG: Compiling C:\pythonprograms\linkedinv1\app.py
21676 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
21686 INFO: Bootloader c:\users\deven\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
21687 INFO: checking EXE
21703 INFO: Rebuilding EXE-00.toc because app.exe missing
21703 INFO: Building EXE from EXE-00.toc
21713 INFO: Appending archive to EXE C:\pythonprograms\linkedinv1\dist\app.exe
22579 INFO: Building EXE from EXE-00.toc completed successfully.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by Legorooj** [comment]
As many issues have reported before, this can happen. Unfortunately this is a sporadic problem (I get no issues with windows defender) and we can offer no support for it. You might be able to "report file as false positive" or similar.

**Comment by tbhaxor** [comment]
@Legorooj is there anything your team could do, except closing issues?

**Comment by Legorooj** [comment]
@tbhaxor we can't help with this unfortunately. For instance, we can't replicate it, etc. I use windows defender and it works fine for me. The only suggestion I have is to contact Microsoft and report it as a false positive.

**Comment by tbhaxor** [comment]
Let me alert you if this is a reason. Any script kiddie can compromise your
system.

**Comment by NHades** [comment]
@tbhaxor I had same issue two weeks ago (along with others) (see #4670 ). 
I reported issue to Microsoft and they updated their AV definitions.  Pyinstaller team can't do anything here, so no blame game.
