### ISSUE TITLE
WARNING: file already exists but should not: C:\Users\105067~9\AppData\Local\Temp\_MEI1103602\torch\_C.cp37-win_amd64.pyd

### ISSUE THREAD

**Issue by kcsekhar14** [pyinstaller/pyinstaller#4695]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: e.g. 3.7
* Platform: e.g GNU/Linux (distribution), Windows (language settings), OS X, conda, FreeBSD
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with celan installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by kcsekhar14** [comment]
This issue is similar to [(https://github.com/pyinstaller/pyinstaller/issues/4561)] but it doesn't solve for me - 
Python 3.5.4
PyInstaller 3.6

I have tried various option like - 
1. use --onedir instead of --onefile can avoid this problem. -> Doesn't Worked
2. --hidden-import ctypes -> Doesn't Worked
3. for d in a.datas:
    if '_C.cp37-win_amd64.pyd' in d[0]: 
        a.datas.remove(d)
        break
-> Doesn't Worked

It worked. But when I click the EXE file, it shows the following error message:

WARNING: file already exists but should not: C:\Users\105067~9\AppData\Local\Temp\_MEI1103602\torch\_C.cp37-win_amd64.pyd

**Comment by Legorooj** [comment]
Wait a sec - this happens in one folder mode? Try one folder, but build with the `--clean` option.

**Comment by kcsekhar14** [comment]
@Legorooj I am sorry, one correction. with --onedir it is working fine. I am not having issue. But i want to compile it as --onefile so that all others will be loaded in temp folder. 
Is it possible to build the application with --onefile option

**Comment by Legorooj** [comment]
@kcsekhar14 good. I thought something was really wrong for a sec. I'll look into this.

**Comment by kcsekhar14** [comment]
Libraries used inside the Python - 
from PyQt5 import QtCore, QtGui, QtWidgets
import tkinter as tk
from tkinter import filedialog
from tkinter import messagebox
import os,sys
from mat4py import loadmat
from matplotlib import pyplot as plt

**Comment by Legorooj** [comment]
@kcsekhar14 thanks that might help.

**Comment by Legorooj** [comment]
Try building with `--exclude-module=torch`?

**Comment by kcsekhar14** [comment]
@Legorooj Sorry for the last reply. I have compiled and tested, now it is working without any popup messages, Thank you for the reply

**Comment by Legorooj** [comment]
I'll close then. Could you please edit the original comment with the solution?

**Comment by zhangchi621** [comment]
> How did you fix it? I have the same problem.

How did you fix it? I have the same problem.

**Comment by Dariusz1989** [comment]
The same problem here, back in 3.x and 4.x version of pyinstaller.

**Comment by AdrienLF** [comment]
Same problem here

**Comment by Dariusz1989** [comment]
ok I have a fix!
It means that... the file already exists! But to understand it... we have to look at extra assests!
So here is the deal..
Because pyd do not allow pyinstaller to check each import, we add the files manually right?
So our Starter.py imports X/Y/Z. And X Y Z imports K D B and so on.
Now the thing is... thet it looks like pyinstaller can import the 1st layer of files...
so pyinstaller is aware of Starter.py + X Y Z. Its only the recursive imports from that points that are lost. 
That mean that when you make ur collector, make sure that you DO NOT collect, Starter.py + X Y Z.
As when installer starts he unpacks the manually collected files 1st... and then he unpacks the one he found himself... so Starter + X Y Z. At this points you get the warning, because he is unpacking file he already unpacked early...

Does it make sense?! :D
Hope it helps...
