### ISSUE TITLE
Cannot make hardened runtime for Catalina

### ISSUE THREAD

**Issue by gwhenne** [pyinstaller/pyinstaller#4701]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

When I try to notarize my app, I get this message back from Apple:
```
"path": "AppStudio.dmg/AppStudio.app/Contents/MacOS/AppStudio",
"message": "The executable does not have the hardened runtime enabled.",
```

Before attempting to notarize, I do this:
```
codesign --force --verify --verbose=4 --timestamp --entitlements ./entitlements.plist --sign "Developer ID Application: NS BASIC Corporation" ./dist/AppStudio.app/Contents/MacOS/AppStudio
```

I'm using the tips in #4629.

This is important: Since sometime in January, MacOS Catalina requires all apps to be notarized, and that the executables be hardened.

**Comment by phw** [comment]
On our project we run this command on the app folder itself with the `--deep` flag. Also to enable the hardened runtime you need to pass the `--options runtime` argument. So this works here for my app:

```
codesign --verify --verbose --deep \
  --options runtime \
  --entitlements entitlements.plist \
  --sign "Developer ID Application: NS BASIC Corporation" \
  "./dist/AppStudio.app"
```

**Comment by gwhenne** [comment]
That was it - thank you!

**Comment by gubatron** [comment]
Thank you @phw, this also helped me with a PyInstaller executable I thought I was not going to be able to sign with hardened runtime, it had nothing to do with how my executable was compiled, it was just this "--options runtime" missing from the codesign call.
