### ISSUE TITLE
PyInstaller3.6 got an error "No module named 'PyQt5.sip‘ ”

### ISSUE THREAD

**Issue by leileigong** [pyinstaller/pyinstaller#4705]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)
i got an executeable bin file on raspberry successfully.
But when i try to run it, got an error:

```
ModuleNotFoundEror: No module named 'PyQt5.sip‘ 
[2016] Failed to execute scrpt
```

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.6
* Platform: Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

* i try  pyinstaller 3.6 and python3.6 on win10, it works fine.

**Comment by leileigong** [comment]
on raspberry, i use pyinstaller 3.4 and python3.6, it works fine.

**Comment by bjones1** [comment]
Already fixed in develop.
