### ISSUE TITLE
"Security-Alert" due to subtle difference in os.path.dirname()

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#4707]
I stepped of a subtle error, where `os.path.normpath()` behaves different on Windows (resp. package `ntpath` does, so one can reproduce this even on non-Windows systems).

 On Windows, `normpath` does not remove a trailing (back-)slash in all cases:
```
>>> from ntpath import normpath
>>> print(normpath("//aaa/bbb/"))
\\aaa\bbb\
>>> print(normpath("//aaa/"))
\\aaa\
>>> print(normpath("//aaa/bbb/ccc/"))
\\aaa\bbb\ccc
```

This inhibits [`collect_data_files()`](https://github.com/pyinstaller/pyinstaller/blob/v3.6/PyInstaller/utils/hooks/__init__.py#L697) and [`collect_system_data_files()` to ](https://github.com/pyinstaller/pyinstaller/blob/v3.6/PyInstaller/utils/hooks/__init__.py#L744) to actually remove the prefix in these case.

This might lead to Errors like these:

> Security-Alert: try to store file outside of dist-directory. Aborting. '\\\\vboxsvr\\vagrant\\flyer_composer\\locale\\flyer-composer.pot'

**Comment by htgoebel** [comment]
This analysis correct, but this is not the reason for the Security-Alert, as `normpath` is not used in `collect_data_files()`. But the same subtle difference exists for `dirname()`. On Windows the trailing slash is kept in some cases, while on Posix it is always removed:
```
>>> import ntpath
>>> print(ntpath.dirname("//aaa/bbb/"))
//aaa/bbb/
>>> print(ntpath.dirname("//aaa/"))
//aaa/
>>> import posixpath
>>> print(posixpath.dirname("//aaa/bbb/"))
//aaa/bbb
>>> print(posixpath.dirname("//aaa/"))
//aaa
```

**Comment by bjones1** [comment]
Hmm -- strange. I'm not sure what `//aaa/bbb` means on Windows -- if it were `\\aaa\bbb`, that's a network share. Playing with the newer `pathlib.Path.resolve()`:

``` 
(venv) F:\hooksample>python
Python 3.7.3 (v3.7.3:ef4ec6ed12, Mar 25 2019, 22:22:05) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from pathlib import Path
>>> print(Path("//aaa/bbb/").resolve())
\\aaa\bbb\
>>> print(Path("//aaa/").resolve())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Python37\lib\pathlib.py", line 1144, in resolve
    s = self._flavour.resolve(self, strict=strict)
  File "D:\Python37\lib\pathlib.py", line 201, in resolve
    s = self._ext_to_normal(_getfinalpathname(s))
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: '\\\\'
>>> print(Path("//aaa/bbb/ccc/").resolve())
\\aaa\bbb\ccc
>>> print(Path("\\\\aaa\\bbb\\").resolve())
\\aaa\bbb\
>>> print(Path("\\\\aaa").resolve())
F:\aaa
>>> print(Path("\\\\aaa\\bbb\\ccc").resolve())
\\aaa\bbb\ccc
```

So, the behavior of these two functions is consistent, and probably varies on the backslash based on if it's interpreted as a network share or not.
