### ISSUE TITLE
Empty DEST not allowed when adding binary and data files. Maybe you want to used '.'.

### ISSUE THREAD

**Issue by olegmitrakhovich** [pyinstaller/pyinstaller#4708]
## Description of the issue

I am attempting to build an older version of SPMT - v0.4.2, here is the link to the release:

https://github.com/PIVX-Project/PIVX-SPMT/releases/tag/v0.4.2a

when I run **pyinstaller SecurePivxMasternode.spec**, I get 

**Empty DEST not allowed when adding binary and data files. Maybe you want to used '.'.
Caused by 'C:\\Windows\\system32\\vcruntime140.dll'.**

not sure what the issue is?

## Context information

* Output of `pyinstaller --version`:  4.0.dev0+a1f92c6a08
* Version of Python: Python 3.7.3
* Platform: Windows 
* Never tried on any other platform, need it work with Windows, combined with another project in the future

**Comment by Legorooj** [comment]
Please upload the spec file.

**Comment by olegmitrakhovich** [comment]
Thank you for the response, @Legorooj 

`# -*- mode: python -*-
import sys
import os
import os.path
import simplejson as json

os_type = sys.platform
block_cipher = None
base_dir = os.path.dirname(os.path.realpath('__file__'))

# look for version string
version_str = ''
with open(os.path.join(base_dir, 'src', 'version.txt')) as version_file:
	version_data = json.load(version_file)
version_file.close()
version_str = version_data["number"] + version_data["tag"]

add_files = [('src/version.txt', '.'), ('img', 'img')]

lib_path = next(p for p in sys.path if 'site-packages' in p)
if os_type == 'win32':
    qt5_path = os.path.join(lib_path, 'PyQt5\\Qt\\bin')
    sys.path.append(qt5_path)
    # add file vcruntime140.dll manually, due to not including by pyinstaller
    found = False
    for p in os.environ["PATH"].split(os.pathsep):
        file_name = os.path.join(p, "vcruntime140.dll")
        if os.path.exists(file_name):
            found = True
            add_files.append((file_name, ''))
            print('Adding file ' + file_name)
            break
    if not found:
        raise Exception('File vcruntime140.dll not found in the system path.')

	
# add bitcoin library data file
add_files.append( (os.path.join(lib_path, 'bitcoin/english.txt'),'bitcoin') )
	
a = Analysis(['spmt.py'],
             pathex=[base_dir, 'src', 'src/qt'],
             binaries=[],
             datas=add_files,
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)

exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='SecurePivxMasternodeTool',
          debug=False,
          strip=False,
          upx=False,
          console=False,
          icon=os.path.join(base_dir, 'img', 'spmt.%s' % ('icns' if os_type=='darwin' else 'ico')) )

coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='app')

if os_type == 'darwin':
	app = BUNDLE(coll,
             name='SecurePivxMasternodeTool.app',
             icon=os.path.join(base_dir, 'img', 'spmt.icns'),
             bundle_identifier=None,
             info_plist={'NSHighResolutionCapable': 'True'})
             
   
# Prepare bundles
dist_path = os.path.join(base_dir, 'dist')
app_path = os.path.join(dist_path, 'app')
os.chdir(dist_path)

# Copy Readme Files
from shutil import copyfile, copytree
print('Copying README.md')
copyfile(os.path.join(base_dir, 'README.md'), 'README.md')
copytree(os.path.join(base_dir, 'docs'), 'docs')


if os_type == 'win32':
	# Copy Qt5 Platforms
	os.system('xcopy app\PyQt5\Qt\plugins\platforms app\platforms\ /i')
	os.chdir(base_dir)
	# Rename dist Dir
	dist_path_win = os.path.join(base_dir, 'SPMT-v' + version_str + '-Win64')
	os.rename(dist_path, dist_path_win)
	# Compress dist Dir
	print('Compressing Windows App Folder')
	os.system('"C:\\Program Files\\7-Zip\\7z.exe" a %s %s -mx0' % (dist_path_win + '.zip', dist_path_win))
	
	
if os_type == 'linux':
	os.chdir(base_dir)
	# Rename dist Dir
	dist_path_linux = os.path.join(base_dir, 'SPMT-v' + version_str + '-gnu_linux')
	os.rename(dist_path, dist_path_linux)
	# Compress dist Dir
	print('Compressing Linux App Folder')
	os.system('tar -zcvf %s -C %s %s' % ('SPMT-v' + version_str + '-x86_64-gnu_linux.tar.gz', 
                base_dir, 'SPMT-v' + version_str + '-gnu_linux'))


if os_type == 'darwin':
    os.chdir(base_dir)
    # Rename dist Dir
    dist_path_mac = os.path.join(base_dir, 'SPMT-v' + version_str + '-MacOSX')
    os.rename(dist_path, dist_path_mac)
    # Remove 'app' folder
    print("Removin 'app' folder")
    os.chdir(dist_path_mac)
    os.system('rm -rf app')
    os.chdir(base_dir)
    # Compress dist Dir
    print('Compressing Mac App Folder')
    os.system('tar -zcvf %s -C %s %s' % ('SPMT-v' + version_str + '-MacOSX.tar.gz',
                base_dir, 'SPMT-v' + version_str + '-MacOSX'))`

**Comment by Legorooj** [comment]
I can't read that - could you format it like so:
~~~
```
SpecFileContents
```
~~~
That will render it as code. (PS you could use tildes instead - ie `~~~`)

**Comment by olegmitrakhovich** [comment]
Sorry, I updated my previous comment, I hope its easier to read now. @Legorooj

**Comment by Legorooj** [comment]
Can you post the full traceback? That will help me know what is going on.

**Comment by olegmitrakhovich** [comment]
Sorry not really sure how to get a traceback when doing a build, but this is all I'm getting on my console when running "pyinstaller SecurePivxMasternode.spec" 

2494 INFO: PyInstaller: 4.0.dev0+a1f92c6a08
2495 INFO: Python: 3.7.3
2495 INFO: Platform: Windows-10-10.0.17763-SP0
2668 INFO: UPX is not available.
Adding file C:\Windows\system32\vcruntime140.dll
2958 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Oleg Mitrakhovich\\Documents\\GitHub\\SPMT',
 'C:\\Users\\Oleg Mitrakhovich\\Documents\\GitHub\\SPMT',
 'C:\\Users\\Oleg Mitrakhovich\\Documents\\GitHub\\SPMT\\src',
 'C:\\Users\\Oleg Mitrakhovich\\Documents\\GitHub\\SPMT\\src\\qt']
2960 INFO: checking Analysis
5407 INFO: Appending 'datas' from .spec
Empty DEST not allowed when adding binary and data files. Maybe you want to used '.'.
Caused by 'C:\\Windows\\system32\\vcruntime140.dll'.

@Legorooj

**Comment by Legorooj** [comment]
Is `datas.img` a folder?

**Comment by olegmitrakhovich** [comment]
Don't see a folder like that... where do you expect it to be? @Legorooj

**Comment by Legorooj** [comment]
`add_files = [('src/version.txt', '.'), ('img', 'img')]`. Is `img` a folder?

**Comment by Legorooj** [comment]
Hi?

**Comment by olegmitrakhovich** [comment]
hey man sorry for the late response, I was busy at work with something ... Do I need to add that line somewhere in the code... give me a little more detail Ill have it done monday. Again I apologize. @Legorooj

**Comment by Legorooj** [comment]
@olegmitrakhovich it's fine - just need a yes or no. In the above line of code, is `img` a file or directory?

**Comment by olegmitrakhovich** [comment]
yes "img" is a folder with images in it. @Legorooj

**Comment by Legorooj** [comment]
@olegmitrakhovich you can't add directories. You'll need to either add each and every file like:
`add_datas.append(('img/IMG.jpg', 'img'))` or look at the Tree class described [here](https://pyinstaller.readthedocs.io/en/stable/advanced-topics.html#the-tree-class)
