### ISSUE TITLE
Getting error while running bind hooks from pytest-assume plugin while running the executable

### ISSUE THREAD

**Issue by ptrivedi2610** [pyinstaller/pyinstaller#4713]
Hi @itszero ,

Recently I have been working on a Project that requires to create an executable that includes the source code and some hooks from pytest-assume plugin of pytest library.
When the .exe file is executed, there arises an error regarding the usage of hooks, as below

collecting ... INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "_pytest\main.py", line 185, in wrap_session
INTERNALERROR>   File "_pytest\main.py", line 224, in _main 
INTERNALERROR>   File "pluggy\hooks.py", line 258, in __call__  
INTERNALERROR>   File "pluggy\manager.py", line 67, in _hookexec 
INTERNALERROR>   File "pluggy\manager.py", line 61, in <lambda> 
INTERNALERROR>   File "pluggy\callers.py", line 201, in _multicall 
INTERNALERROR>   File "pluggy\callers.py", line 76, in get_result 
INTERNALERROR>   File "pluggy\callers.py", line 180, in _multicall 
INTERNALERROR>   File "_pytest\main.py", line 234, in pytest_collection 
INTERNALERROR>   File "_pytest\main.py", line 448, in perform_collect  
INTERNALERROR>   File "pluggy\manager.py", line 241, in check_pending 
INTERNALERROR> pluggy.manager.PluginValidationError: unknown hook 'pytest_assume_fail' in plugin <module 'conftest' from 'C:\\Users\\PT\\Desktop\\dist\\conftest.py'>

Is there a proper method in a way that such hooks from plugins are detected. Note that the pytest-assume plugin is successfully found by the executable. Seems the hooks are not registered. 

Kindly help for the same.
Pasting spec file content for reference.

========================================================
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['main.py'],
             pathex=[
			 os.path.join(DISTPATH, 'obf', 'temp'),
			 '.\\',
			 'C:\\Python37\\Lib\\site-packages\\',		 			 
			 'C:\\Python37\\Lib\\site-packages\\pytest-assume\\',
			 'C:\\Python37\\Lib\\site-packages\\py',
			 'C:\\Python37\\Lib\\site-packages\\pluggy\\',
			 'C:\\Python37\\Lib\\site-packages\\xmlschema\\',			 
			 'C:\\Python37\\Lib\\urllib\\',
			 'C:\\Python37\\Lib\\site-packages\\xmlschema\\validators\\schemas\\XSD_1.0'],
             binaries=[],
             datas=[],
             hiddenimports=['pytransform', 'py.io'],
             hookspath=[os.path.join(DISTPATH, 'obf', 'temp')],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='main')

**Comment by ptrivedi2610** [comment]
@itszero 
Any help will be much appreciated.

**Comment by Legorooj** [comment]
@ptrivedi2610 you'll need a hook for the module. Please refer to the docs ("Understanding PyInstaller hooks")

**Comment by ptrivedi2610** [comment]
@itszero 
I referred the same and did my changes in the zuth.spec file, but was unsuccessful. 
Are there any samples available that uses specific custom created hooks integration flow with pyinstaller?

Please point to if any.

**Comment by Legorooj** [comment]
@ptrivedi2610 you don't modify the spec file at all when using hooks. The docs are perfectly clear on that. Please re read them.

**Comment by ptrivedi2610** [comment]
@Legorooj 
Yes I have gone through the document again to iterate over the hook details. However, still unable to progress further.

Let me summarize the issue.
1. I am trying to create installer out of my application that extensively uses pytest and its **3rd party plugin pytest-assume**.
2. The created executable is unable to find pytest-assume. I have tried every single way possible, namely creating hook file as well.
3. I read the **standard pytest doc Section 27.2.13** This is what it says
**If you freeze your application using a tool like PyInstaller in order to distribute it to your end-users, it is a good idea to also package your test runner and run your tests using the frozen application. This way packaging errors such as dependencies not being included into the executable can be detected early while also allowing you to send test files to users so they can run them in their machines, which can be useful to obtain more information about a hard to reproduce
bug.
Fortunately recent PyInstaller releases already have a custom hook for pytest, but if you are using another tool to freeze executables such as cx_freeze or py2exe, you can use pytest.freeze_includes() to obtain the full list of internal pytest modules. How to configure the tools to find the internal modules varies from tool to tool, however.
Instead of freezing the pytest runner as a separate executable, you can make your frozen program work as the pytest runner by some clever argument handling during program startup. This allows you to have a single executable, which
is usually more convenient. Please note that the mechanism for plugin discovery used by pytest (setupttools entry points) doesn’t work with frozen executables so pytest can’t find any third party plugins automatically. To include third party plugins like pytest-timeout they must be imported explicitly and passed on to pytest.main.**

Can you let me know how exactly 3rd party plugins and hooks work in-case of pyinstaller. Any help to proceed will be appreciated.

P.S. I tried to integrate other 3rd party plugins of pytest, all of them causes the same behavior,

**Comment by Legorooj** [comment]
Can you post the traceback that the executeable generates?
