### ISSUE TITLE
PyInstaller 打包app报错：LSOpenURLsWithRole() failed with error -10810

### ISSUE THREAD

**Issue by fullback555** [pyinstaller/pyinstaller#4715]
我使用PyInstaller 3.6打包一个PyQt5的程序，打包过程指示有一个错误：
/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zmq/backend/cffi/__pycache__/_cffi_ext.c:269:10: fatal error: 
      'zmq.h' file not found

但依然能生成可执行文件：exam.app，双击该文件，无法打开，使用终端打开也无法打开，并且报错：LSOpenURLsWithRole() failed with error -10810 for the file /Users/wenlong/GitHub/exam_demo/dist/exam.app.

试过PyInstaller 3.6/3.5这个两个版本，结果都一样。
环境：python 3.7.6
macOS 10.13.6

请问各位大神，这个问题怎么解决？

**Comment by Legorooj** [comment]
Translated version:
```
I used PyInstaller 3.6 to package a PyQt5 program, and the packaging process indicated an error:
 /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/zmq/backend/cffi/pycache/_cffi_ext.c:269:10: fatal error:
 'zmq.h' file not found

 But still can generate executable file: exam.app, double-click the file, it cannot be opened, it cannot be opened with the terminal, and an error is reported: LSOpenURLsWithRole () failed with error -10810 for the file / Users / wenlong / GitHub / exam_demo / dist  /exam.app.

 Tried both versions of PyInstaller 3.6 / 3.5, the results are the same.
 Environment: Python 3.7.6
 macOS 10.13.6

 Excuse me, how can this problem be solved?
```

**Comment by Legorooj** [comment]
Please read the following documentation link: https://pyinstaller.readthedocs.io/en/stable/hooks.html

<hr>

请阅读以下文档链接：https://pyinstaller.readthedocs.io/en/stable/hooks.html

**Comment by fullback555** [comment]
总算解决了。
第一个问题使用：brew install zeromq
第二个问题：将代码中读写文件使用到的相对路径改为绝对路径即可。

**Comment by Legorooj** [comment]
English:

Finally resolved.
 The first question uses: brew install zeromq
 The second problem: change the relative path used to read and write files in the code to an absolute path.

**Comment by M0nd0liay** [comment]
> 总算解决了。
> 第一个问题使用：brew install zeromq
> 第二个问题：将代码中读写文件使用到的相对路径改为绝对路径即可。

Im still struggle with this. Question where do you place this code to change the path? 

os.path.join(os.path.dirname(sys.argv[0]), 'your_name.db')

And way is the name now your_name.db and not your_name.py?

thnx

**Comment by aaronsu** [comment]
How to solve it in the end? I also met this problem, just Hello world
