### ISSUE TITLE
Exception when importing a CPython extension module with Python 3.8

### ISSUE THREAD

**Issue by danielhrisca** [pyinstaller/pyinstaller#4717]
## Description of the issue
When loading a CPython extension (_cutils_ from the traceback) I get the exception. Running the main application script using the python interpreter does not raise an exception.

With Python 3.7 this error did not occur.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.8
* Platform: Windows 
* Did you also try this on another platform? Does it work there? The code is Windows only

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with celan installation
  * [x] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
I don't think I could add something here. The only issue is with the import.
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "c:\program files\python38\lib\runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\program files\python38\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python38\Scripts\pyinstaller.exe\__main__.py", line 9, in <module>
  File "c:\program files\python38\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\program files\python38\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\program files\python38\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\program files\python38\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
    exec(code, spec_namespace)
  File "DAXil_console.spec", line 7, in <module>
    from daxil.version import get_packages_details
  File ".\daxil\__init__.py", line 25, in <module>
    from .xil import Recorder
  File ".\daxil\xil\__init__.py", line 1, in <module>
    from .devices import get_signal_info_from_a2l, NI, XCP, CAN, HBM
  File ".\daxil\xil\devices\__init__.py", line 1, in <module>
    from .xcp import XCP
  File ".\daxil\xil\devices\xcp.py", line 30, in <module>
    from ..cutils import xcp_acquire
ImportError: DLL load failed while importing cutils: The parameter is incorrect.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by Legorooj** [comment]
Python 3.8 is unsupported. Please let me know if the issue persists in 3.5-3.7. If so, I'll reopen.

**Comment by danielhrisca** [comment]
Can you at least give your opinion if the error comes from pyinstaller or Cpython?

**Comment by Legorooj** [comment]
Your `daxil` module or pyinstaller.

**Comment by danielhrisca** [comment]
ok, thank you
