### ISSUE TITLE
shapely can't find libgeos from conda-based environment

### ISSUE THREAD

**Issue by djhoese** [pyinstaller/pyinstaller#4718]
## Description of the issue

I'm building an application that uses the shapely package. I create my environment with conda using packages from conda-forge. This means that shapely is not installed from a wheel and does not include a bundled libgeos. I plan on making a pull request to fix this, but wanted to get feedback and help before trying anything.

The issue stems from how shapely looks for librarie and the libraries that the pyinstaller hook are looking for. Conda-forge's libgeos has the following libraries:

```
libgeos-3.8.0.so
libgeos_c.so
libgeos_c.so.1
libgeos_c.so.1.13.1
libgeos.so
```

But pyinstaller's hook looks for files with names `libgeos_c*.so` in a `.libs` directory inside the installed shapely package. My understanding is that this `.libs` directory only exists if shapely was installed from a wheel.

If I update the hook to look for the plain old `<prefix>/lib/libgeos_c*.so` then shapely will fail to import geos. This is because it expects the libraries to be `libgeos_c-*.so*`. As can be seen at the code linked below it looks for `.libs` first, then if it is frozen it looks for the `libgeos_c-*.so` pattern, or if not frozen it checks if it is in a conda environment and loads the proper names.

https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L66-L81

The actual error you get when trying to run the application is:

```
  File "/data/users/davidh/repos/git/pyinstaller/PyInstaller/loader/pyimod03_importers.py", line 489, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages/shapely/geos.py", line 196, in <module>
  File "site-packages/shapely/geos.py", line 184, in _geos_version
AttributeError: 'NoneType' object has no attribute 'GEOSversion'
```

## Possible solutions

I can update the hook to find the files in my conda environment but they will have the wrong name from what shapely expects. So do I:

1. Update the hook in such a way that it renames these files? Is that even possible? This feels like a bad idea for anything else using libgeos.
2. Submit a PR to shapely to be more flexible about what `.so` files it looks for?
3. Other suggestion?

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0.dev0+ga1f92c6.mod```
* Version of Python: 3.7
* Platform: CentOS 7

CC @sgillies

**Comment by Legorooj** [comment]
@sgillies will need to help here.

**Comment by ssfabiopicchi** [comment]
How can I manually solve this issue? I have very little understanding of how pyInstaller does its awesome magic :/

**Comment by Legorooj** [comment]
@ssfabiopicchi you'll need to rewrite the shapely hook to look in different directories when using a conda-based environment. Use the copies of the hooks that are in the `pyinstaller/pyinstaller-hooks-contrib` repository, and if you can, submit fixes there.

**Comment by ssfabiopicchi** [comment]
Thanks! I managed to do that but unfortunately it didn't work :/

I put the necessary libgeos files in the same level as the executable using hooks but that wasn't enough. I guess I need to figure out how `shapely` figures out the path to these files.

**Comment by Legorooj** [comment]
@ssfabiopicchi yes, you'll need to manipulate the destination of the binary files so shapely can find them. Diving into shapely's code would be the fastest method to do this.

**Comment by nmaxwell** [comment]
Just ran into this issue my self. 

look into .../site-packages/shapely/geos.py, around line 66, where they are finding _lgeos, 

```
if sys.platform.startswith('linux'):
    # Test to see if we have a wheel repaired by 'auditwheel' containing its
    # own libgeos_c
    geos_whl_so = glob.glob(os.path.abspath(os.path.join(os.path.dirname(
        __file__), '.libs/libgeos_c-*.so.*')))
    if len(geos_whl_so) == 1:
        _lgeos = CDLL(geos_whl_so[0])
        LOG.debug("Found GEOS DLL: %r, using it.", _lgeos)
    elif hasattr(sys, 'frozen'):
        geos_pyinstaller_so = glob.glob(os.path.join(sys.prefix, 'libgeos_c-*.so.*'))
        if len(geos_pyinstaller_so) == 1:
            _lgeos = CDLL(geos_pyinstaller_so[0])
            LOG.debug("Found GEOS DLL: %r, using it.", _lgeos)
    elif os.getenv('CONDA_PREFIX', ''):
```

the condition that gets hit when deployed with pyinstaller is `elif hasattr(sys, 'frozen'):`  

In my anaconda distribution, there is no geos library with a name matching 

```libgeos_c-*.so.*```

I'm not sure where that pattern comes from. The solution I used in my build script is this:

```
    libdir = Path(sys.prefix) / 'lib'
    geos_ver = '1.13.3'
    geos_linked = libdir / f"libgeos_c-.so.{geos_ver}" # notice the subtle dash
    geos_linked.symlink_to(libdir / f"libgeos_c.so.{geos_ver}")
```

then later when calling pyinstaller, using ` f"--add-data={geos_linked}{os.pathsep}." `

This is a bit hacky; I'm not too happy about making an additional symlink in my lib dir, but it works.

**Comment by Legorooj** [comment]
@bwoodsend you use conda alot - if you could take a look at this when you have time. (Finish the stuff you're working on already)

**Comment by bwoodsend** [comment]
> you use conda alot 

[Groan] Not by choice I promise. But Ok I'll look into it...

**Comment by bwoodsend** [comment]
I think a PR  to shapely is the most sensible option. If it looks for a dll named `libgeos_c.so` when running normally (Conda or otherwise) then it should look for that name when running frozen as the `if conda` check will mislead it when frozen.

I'd probably rewrite the [elif frozen and elif conda](https://github.com/Toblerity/Shapely/blob/master/shapely/geos.py#L72-L79) bit into something like the following (not tested):

```python
    elif hasattr(sys, 'frozen') or exists_conda_env():
        # Abstract the prefix to avoid repeated if logic.
        prefix = sys.prefix if hasattr(sys, 'frozen') else os.path.join(sys.prefix, 'lib')

        # First try the full Conda name.
        geos_so = os.path.join(prefix, 'libgeos_c.so')

        # Then fall back to globbing if it fails.
        if not os.path.exists(geos_so):
            geos_pyinstaller_so = glob.glob(os.path.join(prefix, 'libgeos_c-*.so.*'))
            if len(geos_pyinstaller_so) == 1:
                geos_so = geos_pyinstaller_so[0]
            else:
                raise FileNotFoundError("error message here")
   
        _lgeos = CDLL(geos_so)
        LOG.debug("Found GEOS DLL: %r, using it.", _lgeos)
```

**Comment by bwoodsend** [comment]
If we were to try to fix it on PyInstaller's side I don't many appealing options.

1. Just rename the file as @djhoese initally suggested. This is possible and I don't think would break other packages that use that dll provided that the dll is marked as a `binaries` for those other packages. At worst I think we may end up with multiple copies of the same file.
2. We could in theory write put the dll where it first searches for it based on `__file__`, add a run-time hook which deletes `sys.frozen`, imports `shapely`, then replaces `sys.frozen`.
3. Use @nmaxwell 's symlink hack.

Option 1 is feasible albeit wasteful. 2 - I only list to point out how impractical it would be. 3 - I imagine this will work nicely on Linux, which handles symlinks almost seamlessly, but will be a total disaster on Windows, which may as well not have symlinks at all - even Python's OS abstraction is weak there.

**Comment by bwoodsend** [comment]
Closing this now as I feel we've answered the original question. The fix would be far more appropriate applied to shapely than to PyInstaller.
