### ISSUE TITLE
Crash when bundling package on github actions

### ISSUE THREAD

**Issue by nathanielatom** [pyinstaller/pyinstaller#4721]
## Description of the issue

I was hoping to setup github actions to run pyinstaller for bundling my exe. I'm using the `windows-latest` runner / VM which has this [software configured](https://github.com/actions/virtual-environments/blob/master/images/win/Windows2019-Readme.md). It bundles successfully locally on Windows 10. I looked but didn't see anything to indicate windows server isn't supported. 

It crashes very early on, without a traceback, before even logging the python version. Is there a way I can get more debug info?

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0.dev0+a751f7417d``` (also `3.6`)
* Version of Python: Python 3.7.6
* Platform: Windows Server 2019, from Github Actions
* Successfully bundles executable on Windows 10

## Sample Code

```
echo "print('pyinstaller test')" > sample.py
pyinstaller sample.py --onedir --noupx --log-level DEBUG --debug all
```

Output:
```
156 INFO: PyInstaller: 4.0.dev0+a751f7417d
[error]Process completed with exit code 1.
```
compared to the first few lines from Windows 10:
```
109 INFO: PyInstaller: 3.6
109 INFO: Python: 3.7.3
109 INFO: Platform: Windows-10-10.0.17763-SP0
109 DEBUG: Testing for UPX ...
109 INFO: UPX is not available.
...
```

**Comment by Legorooj** [comment]
`--log-level=TRACE`? This will only output a few lines if it's crashing this early on. Only run this once; just compiling `from sympy import *` outputs 100000+ lines.

**Comment by nathanielatom** [comment]
Oh wow. In this case, still the same result:
```
46 INFO: PyInstaller: 4.0.dev0+a751f7417d
[error]Process completed with exit code 1.
```
What does the integer on the left signify? Could it be an issue finding the correct python location? Python itself seems to be on the PATH and works fine.

**Comment by Legorooj** [comment]
Sorry - misclick. The `46` is to do with logging, and is normal. Hmm. Can you link to the GitHub action? And can you run with system diagnostics enabled? I'd like to have a look. (technically we don't support usage like this but this might be a bug...)

**Comment by nathanielatom** [comment]
I created a mimal repo that reproduces it here: https://github.com/nathanielatom/pyinstaller-github-actions-test/runs/486348747?check_suite_focus=true
How can system diagnostics be enabled? I set `ACTIONS_RUNNER_DEBUG` and `ACTIONS_STEP_DEBUG` to true.

**Comment by Legorooj** [comment]
Hmm nothing else I can find - I use Azure DevOps and you can enable system diagnostics which prints all sorts of useful info. I tracked down a bug because the sys had an old lib on it, and sys diagnostics printed the lib's version.

Thanks for the link. As it's a seperate repo, could you give me write access so I can change and try a few things?

**Comment by Legorooj** [comment]
Whaaat...? That's weird. The next line in the PyInstaller code logs something else, so how it's failing I don't know. If you can give me access to the repo I'll try something - I could talk you through it but that'd be really slow.

**Comment by nathanielatom** [comment]
Ok I invited you under Manage Access, hopefully that includes write permissions. Let me know if not. Thanks for taking a look!

**Comment by Legorooj** [comment]
@nathanielatom I can push, so that's good enough. I'll try a few things over the next few days.

**Comment by Legorooj** [comment]
Hmm - fails on windows but not Ubuntu. Very odd. https://github.com/nathanielatom/pyinstaller-github-actions-test/runs/488865251?check_suite_focus=true

**Comment by Legorooj** [comment]
@nathanielatom can you try using Azure DevOps instead? They give unlimited minutes to public repos.

**Comment by nathanielatom** [comment]
Sorry, our priorities have shifted, and I don't think I will have the bandwidth for continuing with that approach. I appreciate your time spent investigating this issue.

**Comment by Legorooj** [comment]
@nathanielatom all right then.

**Comment by nelsonjchen** [comment]
I'm kinda uncertain if this issue was actually resolved but as a big fan of PyInstaller *and* GitHub Actions, I would like to shill my repository demonstrating a reverse RDP setup for debugging a Windows GitHub Action build interactively:

https://github.com/nelsonjchen/reverse-rdp-windows-github-actions

Unfortunately, I currently must use older versions of PyInstaller but hopefully that shill-out above might help pave the path forward when I am unblocked from using newer versions.

**Comment by nathanielatom** [comment]
Thanks!

**Comment by nathanielatom** [comment]
I'm not completely certain, but I think this issue is actually resolved in the latest version of pyinstaller. The workflow that used to seg fault as soon as it ran any pyinstaller command crashes no longer. I haven't had a chance yet to review in detail and finish developing the workflow though - I'm also planning to add a WSL Action that tests the executable that pyinstaller builds.
