### ISSUE TITLE
WIN32COM MODULES

### ISSUE THREAD

**Issue by MiaoSamaCoder** [pyinstaller/pyinstaller#4726]
| These words are translated into English using Google Translate, so there will be grammatical issues. | I run pyinstaller on 32-bit windows7, and the traceback list tells me that there is no win32com module. And some of the packaged modules are not needed by me. I only used pygame, time and other modules, but added SciPy, 2to3 and other modules. How can I fix this? I did not reinstall it.

**Comment by MiaoSamaCoder** [comment]
Also, things like fake-dir are added.

**Comment by MiaoSamaCoder** [comment]
here is
Traceback (most recent call last) :
File "<string>" line 2, in Knodule>
ModuleNotFoundErorr: No module namedwin32com
56667 INFO: Processing pre-safe import module lhook   win32com
Traceback most recent call last) :
File '<string>". line 2, in <module>
ModuleNotFoundErorr: No nodule named' win32com'

**Comment by Legorooj** [comment]
@MiaoSamaCoder try `pip install pywin32` and run again.

**Comment by MiaoSamaCoder** [comment]
The problem was weird. When I restarted the computer, it was packaged, but it worked again.

**Comment by Legorooj** [comment]
@MiaoSamaCoder I've tried to reproduce this and failed. Let me know if it reappears in a traceable way.
