### ISSUE TITLE
Pyinstaller(3.6) uses a variable before setting it - and this breaks applications

### ISSUE THREAD

**Issue by aixtools** [pyinstaller/pyinstaller#4728]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Short description
9012 INFO: Building COLLECT COLLECT-00.toc completed successfully.
(py37) aixtools@x064:[/home/aixtools/aixpert]./dist/demo02/demo02
[5242980] DLL name length exceeds buffer

Basically, the packaging succeeds
* Output of `pyinstaller --version`: ```3.6```
* Version of Python: e.g. 3.7.4
* Platform: e.g AIX
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:
latest version does not build (on AIX)

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Fix

The resolution seems fairly simple. See line 60:
File: bootloader/src/pyi_pythonlib.c

```
   +50  /*
   +51   * Load the Python DLL, and get all of the necessary entry points
   +52   */
   +53  int
   +54  pyi_pylib_load(ARCHIVE_STATUS *status)
   +55  {
   +56      dylib_t dll;
   +57      char dllpath[PATH_MAX];
   +58      char dllname[64];
   +59      char *p;
   +60      int len = 0;
   +61
```
Depending on the shared library object used - len might not be initiated (to zero) before being tested

```
   +70  #ifdef AIX
   +71      /*
   +72       * Determine if shared lib is in libpython?.?.so or libpython?.?.a(libpython?.?.so) format
   +73       */
   +74      if ((p = strrchr(status->cookie.pylibname, '.')) != NULL && strcmp(p, ".a") == 0) {
 ...
   +86        len = snprintf(dllname, 64,
   +87                "libpython%01d.%01d.a(libpython%01d.%01d.so)",
   +88                pyvers_major, pyvers_minor, pyvers_major, pyvers_minor);
   +89      }
   +90      else {
   +91        strncpy(dllname, status->cookie.pylibname, 64);
   +92      }
   +93  #else
   +94      len = 0;
   +95      strncpy(dllname, status->cookie.pylibname, 64);
   +96  #endif
   +97
   +98      if (len >= 64 || dllname[64-1] != '\0') {
   +99          FATALERROR("DLL name length exceeds buffer\n");
  +100          return -1;
  +101      }
```

So, it appears len needs to be initialized (as in line 60, or move line 94 up before the #ifdef, and also be sure that len is set to the value returned by snprintf() AND strncpy()

I have tested (only) initiating the variable in line 60.

**_Note**: I am happy to submit a PR - but what is the correct process to post a PR against non-develop? atm, develop has issues that make it very hard to have a working .dev version._

**Comment by Legorooj** [comment]
PR wise, develop is our default branch. If you could get it working on that, that would be best, but if not, then you'll need @bjones1 to answer that. Also, thanks for finding this bug - this is actually quite major. 

What issues are you encountering in develop? Due to our workflow, `develop` is actually almost as stable as a release. Nothing gets published to that which hasn't been tested thouroghly.

**Comment by aixtools** [comment]
I'll try develop again, and write issues (and hopefully PR) as I find them.

**Comment by Legorooj** [comment]
@aixtools tag me on them.
