### ISSUE TITLE
(AIX) wheel name does not include pep425 tag

### ISSUE THREAD

**Issue by aixtools** [pyinstaller/pyinstaller#4739]
## Wheels and binary content

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: e.g. 3.6.10
* Platform: AIX
* Did you also try this on another platform? Does it work there?
No. Only testing AIX

* try the latest development version, using the following command:
Will try later...
```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

## Results
```

adding 'PyInstaller-3.6.dist-info/entry_points.txt'
adding 'PyInstaller-3.6.dist-info/top_level.txt'
adding 'PyInstaller-3.6.dist-info/RECORD'
removing build/bdist.aix-5307-0747-64/wheel
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6]
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6]ls -l dist
total 5912
-rw-r--r--   1 aixtools aixtools    3026257 Mar 09 21:08 PyInstaller-3.6-py3-none-any.whl
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6]
```

## Comments

As can be seen from the build directory being deleted `bdist.aix-5307-0747-64` the process does know the pep425 tag, just does not use it when naming the wheel in dist.

FYI - the wheel made DOES work, but it could never be used in a pypa(like) repository.

### Start situation

(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6]pip list
Package     Version
----------- -------
altgraph    0.17
pip         20.0.2
pycparser   2.20
PyInstaller 3.6
setuptools  46.0.0
wheel       0.34.2
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6]

(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]find ~/py36 | grep bootloader
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/AIX-64bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/AIX-64bit/run
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/AIX-64bit/run_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/run
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/run_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/runw_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-32bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-32bit/run
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-32bit/run_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit/run.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit/run_d.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit/runw.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit/runw_d.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit/run.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit/run_d.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit/runw.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit/runw_d.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/github_logo.png
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-console.icns
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-console.ico
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-console.svg
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-windowed.icns
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-windowed.ico
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-windowed.svg

### remove PyInstaller
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]pip uninstall pyinstaller
Found existing installation: PyInstaller 3.6
Uninstalling PyInstaller-3.6:
  Would remove:
    /home/aixtools/py36/bin/pyi-archive_viewer
    /home/aixtools/py36/bin/pyi-bindepend
    /home/aixtools/py36/bin/pyi-grab_version
    /home/aixtools/py36/bin/pyi-makespec
    /home/aixtools/py36/bin/pyi-set_version
    /home/aixtools/py36/bin/pyinstaller
    /home/aixtools/py36/lib/python3.6/site-packages/PyInstaller-3.6.dist-info/*
    /home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/*
Proceed (y/n)? y
  Successfully uninstalled PyInstaller-3.6

### Verify bootloaders are not there

(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]find ~/py36 | grep bootloader

### wheel made by python setup.py bdist_wheel (but no aix pep425 tag)

(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]ls *.whl
PyInstaller-3.6-py3-none-any.whl

### Install the wheel
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]pip install *.whl
Processing ./PyInstaller-3.6-py3-none-any.whl
Requirement already satisfied: altgraph in /home/aixtools/py36/lib/python3.6/site-packages (from PyInstaller==3.6) (0.17)
Requirement already satisfied: setuptools in /home/aixtools/py36/lib/python3.6/site-packages (from PyInstaller==3.6) (46.0.0)
Installing collected packages: PyInstaller
Successfully installed PyInstaller-3.6
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]find ~/py36 | grep bootloader
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/AIX-64bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/AIX-64bit/run
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/AIX-64bit/run_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/run
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/run_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Darwin-64bit/runw_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-32bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-32bit/run
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-32bit/run_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run_d
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit/run.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit/run_d.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit/runw.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-32bit/runw_d.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit/run.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit/run_d.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit/runw.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/Windows-64bit/runw_d.exe
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/github_logo.png
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-console.icns
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-console.ico
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-console.svg
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-windowed.icns
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-windowed.ico
/home/aixtools/py36/lib/python3.6/site-packages/PyInstaller/bootloader/images/icon-windowed.svg
(py36) aixtools@x065:[/home/aixtools/pyinstaller/PyInstaller-3.6/dist]

**Comment by Legorooj** [comment]
This isn't a bug in PyInstaller at all. I've encountered this in other similar situations. Have you tried Dev?
