### ISSUE TITLE
同一套源码，用pyinstaller3.6版本打包后360杀毒软件报毒，而3.5版本的不报毒

### ISSUE THREAD

**Issue by anshingy** [pyinstaller/pyinstaller#4745]
Please use the mailing list see <http://www.pyinstaller.org/support.html#mailing-list> for details.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker, but closed.
如上题

**Comment by Legorooj** [comment]
抱歉，如果您的防病毒软件将此报告为恶意软件。 请与供应商联系以解决问题。

Sorry if your antivirus software reports this as malware.  Contact the vendor to resolve the issue.

**Comment by keelung-yang** [comment]
@anshingy 是360这个SB跟进不及时，有时你编个Hello,world它也报病毒。也听说过人家正常的软件360就是不认，加一段360的代码它就不报了。360就是个免费广告机；很多功能看起来有用似的，实际没多少用，装过一段时间卸载了。怀疑病毒就去[virscan.org](https://www.virscan.org/language/zh-cn/about)或[VirusTotal](https://www.virustotal.com/gui/home)扫一下。远离流氓变警察的360
