### ISSUE TITLE
pytest.assume causes exception from its library when used with PyInstaller

### ISSUE THREAD

**Issue by ptrivedi2610** [pyinstaller/pyinstaller#4747]
@itszero @Legorooj 

Currently in my project, I have used pytest-assume 3rd party plugin using the hook of pyinstaller. I have created hook-pytest_assume.py to fetch the plugin from system.

The issue here is that when my project code is executed, pytest-assume library crashes from within. If I don't create executable it works fine.

Is there any specific process that happens when I include pytest-assume via hooks ?

I am attaching both hook file and the crash that arises.

===========================
**Hook File Content**

from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all('pytest_assume')

===========================
**Crash**

_____________________________________________________________________ Test_1.test_trigger _____________________________________________________________________
:550: in read_func
???
pytest_assume\plugin.py:121: in call
assert expr
pytest_assume\plugin.py:79: in exit
context = contextlist[0].lstrip()
E TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:
pytest_assume\plugin.py:119: in call
assert expr, msg
E AssertionError: read_func ERROR : 'NoneType' object is not subscriptable
E assert False

During handling of the above exception, another exception occurred:
..\Test_1.py:56: in test_trigger
status, response = read_func(params)
:630: in read_func
???
E TypeError: 'NoneType' object is not subscriptable

**Comment by Legorooj** [comment]
Does this script definitely work as source?

**Comment by ptrivedi2610** [comment]
@Legorooj 
Also I need one fundamental information 

1. When pyInstaller searches for pytest and pytest-assume, does it modify these libraries in any format ? Or they are taken just as is ?
2. Is it possible that since my source file is converted to exe file, the inspect module doesn't find file and its context from stack as in error mentioned above ?

Meanwhile, I will post the code in sometime

**Comment by Legorooj** [comment]
@ptrivedi2610 PyInstaller doesn't modify the library in any way, but it might not include all of it - but the hook file should fix that.

> Is it possible that since my source file is converted to exe file, the inspect module doesn't find file and its context from stack as in error mentioned above ?

Do you mean that are you not seeing the full stack trace?

**Comment by ptrivedi2610** [comment]
@Legorooj 
Yes, that's right. It loses stack info.
I have tried with both Pyinstaller as well as Pyarmor.

The moment I remove that single file using pytest-assume from bundling into executable, or obfuscation (in case of Pyarmor), it works fine.

Any thoughts on the same ?

**Comment by Legorooj** [comment]
You shouldn't lose any traceback whatsoever. (In fact, it's almost impossible you do). Can you send source code for said file, or a new file to reproduce the issue?

**Comment by ptrivedi2610** [comment]
Please use below steps
1. pip3 install pytest==4.0.2
2. pip3 install pytest-assume

Please create a file test_source.py using below code
==============================================
import pytest

def test_1():
    pytest.assume(True)
    pytest.assume(False)
==============================================

4. Run using below command
   pytest -s test_source.py

5. Now create exe out of the source and run the same command. It will crash with the below output.
========================================================================= test session starts =========================================================================
platform win32 -- Python 3.7.5, pytest-4.0.2, py-1.7.0, pluggy-0.7.1
rootdir: E:\zuth\assume_demo_for_installer\dist, inifile:
plugins: assume-2.2.0, metadata-1.8.0, mccabe-0.1, html-1.19.0, dependency-0.4.0, cov-2.7.1
collected 1 item

test_source.py F

============================================================================== FAILURES ===============================================================================
_______________________________________________________________________________ test_1 ________________________________________________________________________________

>   ???
E   TypeError: 'NoneType' object is not subscriptable

<frozen test_source>:5: TypeError
====================================================================== 1 failed in 0.07 seconds =======================================================================

**Comment by ptrivedi2610** [comment]
@Legorooj 

Did you get a chance to reproduce the issue ?

**Comment by Legorooj** [comment]
Not yet. I need a few more days; my workload is high.

**Comment by ptrivedi2610** [comment]
@Legorooj 
Sure, no hurry. Meanwhile, we did changes in pytest-assume library as a workaround for the same. Please look at your convenience.

Also, one more question

I observed that the python script I executed took almost double time after I obfuscated and converted to .exe using Pyarmor and Pyinstaller

Are there any optimization flags/options in Pyinstaller that can help achieve speed optimization even with the .exe ?

**Comment by Legorooj** [comment]
About the second Q:

Are you using onefile? The speed will be much slower if you are. PyArmor will also slow things down - and I'd recommend using Cython and extension modules; much faster, free, and it obsfuscates the bytecode as well. 

Otherwise, no, there aren't any more flags/options/methods.

I'll have a look at pytest assume, see if I can find the cause of the problem.

**Comment by ptrivedi2610** [comment]
@Legorooj No I am not using onefile mode

Besides,
1. Document says PYTHONOPTIMIZE is not safe ? I ran one of my script and it worked fine. How can we verify if our entire  code can be bundled with PYTHONOPTIMIZE safely ?
2. UPX compresses the code, which means it will decompress during execution.
Does using --noupx saves sometime (time that gets spend in compress/decompress)?

**Comment by Legorooj** [comment]
@ptrivedi2610 in the pytest assume code, I couldn't find the problem, before realising that astraw38/pytest-assume#33 (by you) fixed the problem, the day before I managed to look at the code. 

>    Does using --noupx saves sometime (time that gets spend in compress/decompress)?

Decompression will slow it down, yes. Also PYTHONOPTIMIZE will only remove assert statements and a few things, so barely speed it up. Cython is your best bet by far - it speeds up code by up to 150x, and obsfuscates the code.
