### ISSUE TITLE
Bundled Python package not found in pkg_resources.working_set

### ISSUE THREAD

**Issue by gthb** [pyinstaller/pyinstaller#4751]
## Description of the issue

A package I'm bundling with my application in a pyinstaller build checks for another package by looking it up in `pkg_resources.working_set`. This doesn't work in the pyinstaller-built executable, as `pkg_resources.working_set` contains only one entry, `importlib-metadata` (discovered by poking in a `print(...)` call into the loop over `pkg_resources.working_set` in `spacy/util.py`), so it does not reflect what packages are importable (or distributions active, as setuptools has it).

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.6
* Platform: Windows (English)
* Did you also try this on another platform? Does it work there? Yes, tried on Ubuntu Linux (`Linux 4.15.0-1060-aws #62-Ubuntu SMP Tue Feb 11 21:23:22 UTC 2020`) with Python 3.6.9, same results.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

Did that, same result.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

Done. This is a type-2 problem, as verified by hacking the spacy `is_package` check (see below) and seeing everything working.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with celan installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Minimal example posted as https://gist.github.com/gthb/0a1695b80f7ebd973baab597e4fa60a8

### Stacktrace / full error message

On Linux (but it's much the same on Windows), 
```
$ ./dist/linux/Foo/foo_r
Traceback (most recent call last):
  File "run.py", line 2, in <module>
    lm = spacy.load('en_core_web_sm')
  File "spacy/__init__.py", line 30, in load
  File "spacy/util.py", line 169, in load_model
OSError: [E050] Can't find model 'en_core_web_sm'. It doesn't seem to be a shortcut link, a Python package or a valid path to a data directory.
[3353] Failed to execute script run
```

What's behind that stack trace is, in `spacy/util.py`:
```
    if isinstance(name, basestring_):  # in data dir / shortcut
        if name in set([d.name for d in data_path.iterdir()]):
            return load_model_from_link(name, **overrides)
        if is_package(name):  # installed as package
            return load_model_from_package(name, **overrides)
        if Path(name).exists():  # path to model data directory
            return load_model_from_path(Path(name), **overrides)
    elif hasattr(name, "exists"):  # Path or Path-like to model data
        return load_model_from_path(name, **overrides)
    raise IOError(Errors.E050.format(name=name))
```

where `is_package` returned `False` but _should have_ returned `True` for `name == "en_web_core_md"` as that _is_ a Python package that's present and importable ... but `is_package` in that same module is based on `pkg_resources.working_set`:

```
def is_package(name):
    """Check if string maps to a package installed via pip.

    name (unicode): Name of package.
    RETURNS (bool): True if installed package, False if not.
    """
    import pkg_resources

    name = name.lower()  # compare package name against lowercase name
    packages = pkg_resources.working_set.by_key.keys()
    for package in packages:
        if package.lower().replace("-", "_") == name:
            return True
    return False
```

and it turns out that `pkg_resources.working_set` in the pyinstaller-bootstrapped environment contains only one entry, `importlib-metadata`. Per [`setuptools` documentation](https://setuptools.readthedocs.io/en/latest/pkg_resources.html#workingset-objects): 

> The WorkingSet class provides access to a collection of “active” distributions. In general, there is only one meaningful WorkingSet instance: the one that represents the distributions that are currently active on sys.path. This global instance is available under the name working_set in the pkg_resources module.

The terminology there is a little unfamiliar but I believe “distribution” means a Python (top-level) package, and “active” to mean importable — and `en_core_web_md` is indeed an importable Python top-level package; if I modify `spacy/util.py` to hardcode the assumption that `en_core_web_sm` is an importable package, without consulting `pkg_resources.working_set`, and rerun the `pyinstaller` build (see the above-linked gist for details), then the program runs just fine :

```
$ ./dist/linux/Foo/foo_r
Hi interjection
```

**Comment by Legorooj** [comment]
There's another function inside `PyInstaller.utils.hooks`. It's called `copy_metadata`. Can you give it a try? https://pyinstaller.readthedocs.io/en/stable/hooks.html#useful-items-in-pyinstaller-utils-hooks - one of the last items under that heading.

**Comment by Legorooj** [comment]
The metadata needs copying to fix this.

**Comment by gthb** [comment]
Yes, that looks like it's exactly what's needed, thanks (and I should have found this in docs before posting an issue). I haven't verified it in my use case, as I had already worked around this by importing the module directly instead of calling `spacy.load`.

**Comment by Legorooj** [comment]
@gthb it'd be great if you could verify this directly, and - when the repo is ready - provide a PR with the hooks.

**Comment by gthb** [comment]
Verified with spacy 2.2.3 and 2.2.4, and with pyinstaller 3.6 and pyinstaller tip-of-develop, with `hook-en_core_web_md.py` like this:

```python
from PyInstaller.utils.hooks import collect_data_files, copy_metadata

datas = collect_data_files("en_core_web_md")
datas.extend(copy_metadata("en_core_web_md"))
```

I'm happy to put up a PR with the Spacy hook that I have working, but note that the fix for this issue is in the hook for the language model (that's where the metadata is). Spacy language models are distributed separately and there's a bunch of them, see https://spacy.io/models and https://spacy.io/universe/category/models ... and looks like the hooks would all look identical except for the package names. Is there a neater way than to just make near-identical hooks for all of the models?

**Comment by Legorooj** [comment]
Hmm. Unfortunately not... The PR will need to be targeted at https://github.com/PyInstaller/PyInstaller-hooks-contrib, which isn't ready for PRs yet. And when using spacy with models, you'll need to `import model;model.load()`, or add the models to hiddenimports. For loading to work. I've dealt with quite a few issues about spacy so, when the new repo is ready, I'll ping you, and if we could work on getting compatibility together? I don't actually use spacy, so it'd be easier to have someone who does.

**Comment by gthb** [comment]
Sure, ping me and I'll try to help.

**Comment by Legorooj** [comment]
@gthb would you be able to provide a PR for https://github.com/pyinstaller/pyinstaller-hooks-contrib? I can do the work myself, but it'd be easier if a spacy user did it.

**Comment by gthb** [comment]
@Legorooj yes, I can cook that up next week.

**Comment by Legorooj** [comment]
Sounds good. I'll be waiting.

**Comment by gthb** [comment]
(Draft ready, minor holdup while I get company open source contribution rules clarified...)

**Comment by LUFC999** [comment]
I had this problem that has stumped me for weeks for a model using Spacy and converting into .exe using PyInstaller. I kept getting the error OS could not find en_core_web_sm. After trying everything that I could find anywhere on the internet, nothing worked until I tried the above.  Thanks for the above help!

I amended the file util.py (in my spacy folder (under ....site-packages) and added a couple of names to the is_package function. Amended code is below:

def is_package(name):
    """Check if string maps to a package installed via pip.

    name (unicode): Name of package.
    RETURNS (bool): True if installed package, False if not.
    """
    import pkg_resources

    name = name.lower()  # compare package name against lowercase name
    packages = pkg_resources.working_set.by_key.keys()
    for package in packages:
        if package.lower().replace("-", "_") == name:
            return True
        elif name == "en_core_web_sm":
            return True
    return False

**Comment by gthb** [comment]
> (Draft ready, minor holdup while I get company open source contribution rules clarified...)

Oboy, I have realized this never happened, and I have now left that company. Sorry @Legorooj, this is not forthcoming from me. 😞

**Comment by Legorooj** [comment]
@gthb no worries, I'll do this myself.
