### ISSUE TITLE
Pyinstaller not working with VLC

### ISSUE THREAD

**Issue by Sumit1673** [pyinstaller/pyinstaller#4753]
I created an app using Python3.7 and PyQt5. Then I created a .exe for the app using Pyinstaller and ran the following commands:

pyinstaller --paths=. --onefile ./controller.py --hidden-import vlc

But it failed to find the VLC module.

Below is the image of the error:
![error](https://user-images.githubusercontent.com/29515440/76795562-e654ce80-679f-11ea-8d38-81f3f298d93a.PNG)

I even tried copying the windows VLC plugins folder in the dist folder of the APP but didn't work.

Thanks.

**Comment by Legorooj** [comment]
Minimal, reproducable example please.

**Comment by Sumit1673** [comment]
> Minimal, reproducable example please.
Hi,
I was able to solve the above error because the VLC installed was 32 bit instead of 64. But there is a new error which I am facing. Here is **my script which works:**

from ctypes import windll
windll.kernel32.SetDllDirectoryW(None)
import vlc
import time
import sys
if __name__ == '__main__':

	import sys
	player = vlc.MediaPlayer("File1.wav")
	player.play()
	# time.sleep(10)
	sys.exit(0)

This code works only if I add the first two lines.
 Following this idea which I found from here:
[https://github.com/pyinstaller/pyinstaller/issues/4506#issuecomment-600492106](url)

However, **my actual application does not run** whatever I do. The second script is below:

from ctypes import windll
windll.kernel32.SetDllDirectoryW(None)
from vlc import MediaPlayer
# import vlc
import os
import sys
import re

from google.cloud import speech
from google.cloud.speech import enums
from google.cloud.speech import types
from text2speech import convert_text
from google_audio import file_speech2text as fs2t
from google_live import MicrophoneStream

os.environ["GOOGLE_APPLICATION_CREDENTIALS"] = "key23.json"
RATE = 16000 # 10000
CHUNK = int(RATE / 10)  # 100ms


class BackendModel:
    """ Backend code to update the information to be presented in the viewer"""

    def __init__(self):
        pass

    def play_audio_file(self, audio_file, prev_player_obj):
        try:
            if audio_file is not None:
                player = MediaPlayer(audio_file)
                if player is None:
                    return None
                else:
                    player.play()
                return player
        except Exception as e:
            print(e)

    def set_microphone(self, text_box):
        # See http://g.co/cloud/speech/docs/languages
        # for a list of supported languages.
        language_code = 'fr-FR'  # a BCP-47 language tag

        client = speech.SpeechClient()
        config = types.RecognitionConfig(
            encoding=enums.RecognitionConfig.AudioEncoding.LINEAR16,
            sample_rate_hertz=RATE,
            language_code=language_code)
        streaming_config = types.StreamingRecognitionConfig(
            config=config,
            interim_results=True)

        with MicrophoneStream(RATE, CHUNK) as stream:

            # format = stream._audio_interface.get_sample_size(FORMAT)
            audio_generator = stream.generator()
            requests = (types.StreamingRecognizeRequest(audio_content=content)
                        for content in audio_generator)
            responses = client.streaming_recognize(streaming_config, requests)
            self.listen_print_loop(responses, text_box)

    def listen_print_loop(self, responses, text_box):
        num_chars_printed = 0
        for response in responses:
            if not response.results:
                continue
            result = response.results[0]
            if not result.alternatives:
                continue
            transcript = result.alternatives[0].transcript
            overwrite_chars = ' ' * (num_chars_printed - len(transcript))
            if not result.is_final:
                sys.stdout.write(transcript + overwrite_chars + '\r')
                sys.stdout.flush()
                num_chars_printed = len(transcript)
            else:
                text_box.append(transcript + overwrite_chars)
                if re.search(r'\b(exit|quit)\b', transcript, re.I):
                    print('Exiting..')
                    break
                num_chars_printed = 0
                # if self._timer.join():
                return

    def speech_to_text(self, audio_file):
        return fs2t(audio_file)

    @staticmethod
    def text_to_speech(output_folder, text):
        tts, filename = convert_text(text)
        filename = output_folder + filename
        tts.save(filename)
        player = MediaPlayer(filename)
        player.play()
        return filename

if __name__ == "__main__":
    c= BackendModel()
    c.play_audio_file("File1.wav", 0)

**Error:**
![error2](https://user-images.githubusercontent.com/29515440/77073823-3e6d1a00-69c6-11ea-957d-cfbfd74e147e.PNG)

**Comment by Legorooj** [comment]
Can you try writing a hook for vlc? And the other modules.

**Comment by Sumit1673** [comment]
> Can you try writing a hook for vlc? And the other modules.

I don't know how to create a hook but I will find out, try and let you know.

**Comment by Legorooj** [comment]
@Sumit1673 https://pyinstaller.readthedocs.io/en/stable/hooks.html

**Comment by Legorooj** [comment]
I'm closing; this can be fixed by:

* Making sure the VLC version installed is the same architecture as your python install.
And/Or
* Writing hooks: https://pyinstaller.readthedocs.io/en/stable/hooks.html

**Comment by Sumit1673** [comment]
@Legorooj 
Hi,
Sorry for the delay. I tried using --hidden-import=vlc, it didn't work
Also, I created a mediaplayer.py a script for hook and mentioned the following line:

hiddenimports = ['vlc', 'vlc.MediaPlayer']

But the above methods didn't have any effect. Is anything else I am missing.

**Comment by Legorooj** [comment]
Try:
```
- your.code.file.py
- hooks
  - hook-vlc.py
```
And in `hook-vlc`:
```
from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = collect_all('vlc')
```
And when building add the option: `--additional-hooks-dir=hooks`.

**Comment by Sumit1673** [comment]
> 
> 
> Try:
> 
> ```
> - your.code.file.py
> - hooks
>   - hook-vlc.py
> ```
> 
> And in `hook-vlc`:
> 
> ```
> from PyInstaller.utils.hooks import collect_all
> 
> datas, binaries, hiddenimports = collect_all('vlc')
> ```
> 
> And when building add the option: `--additional-hooks-dir=hooks`.

Thanks for the help. The error is still same. Here is the log
[(base) D:\Speechrecog\16march_2020\Frenchuolinguo-master\Frenchuolinguo>pyinstaller --additional-hooks-dir=hooks --onefile controller.py
74 INFO: PyInstaller: 3.6
75 INFO: Python: 3.7.3 (conda)
75 INFO: Platform: Windows-10-10.0.17763-SP0
76 INFO: wrote D:\Speechrecog\16march_2020\Frenchuolinguo-master\Frenchuolinguo\controller.spec
78 INFO: UPX is not available.
79 INFO: Extending PYTHONPATH with paths
['D:\\Speechrecog\\16march_2020\\Frenchuolinguo-master\\Frenchuolinguo',
 'D:\\Speechrecog\\16march_2020\\Frenchuolinguo-master\\Frenchuolinguo']
81 INFO: checking Analysis
97 INFO: Building because hiddenimports changed
98 INFO: Initializing module dependency graph...
104 INFO: Caching module graph hooks...
115 INFO: Analyzing base_library.zip ...
6230 INFO: Caching module dependency graph...
6379 INFO: running Analysis Analysis-00.toc
6404 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\garud\anaconda3\python.exe
6783 INFO: Analyzing D:\Speechrecog\16march_2020\Frenchuolinguo-master\Frenchuolinguo\controller.py
7127 INFO: Processing pre-find module path hook   PyQt5.uic.port_v3
7226 INFO: Processing pre-find module path hook   PyQt5.uic.port_v2
8600 INFO: Processing pre-find module path hook   distutils
8601 INFO: distutils: retargeting to non-venv dir 'c:\\users\\garud\\anaconda3\\lib'
8818 INFO: Processing pre-find module path hook   site
8819 INFO: site: retargeting to fake-dir 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
11782 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
16427 INFO: Processing pre-safe import module hook   six.moves
22775 INFO: Processing pre-safe import module hook   urllib3.packages.six.moves
27310 INFO: Processing module hooks...
27310 INFO: Loading module hook "hook-certifi.py"...
27315 INFO: Loading module hook "hook-Crypto.py"...
Traceback (most recent call last):
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'Crypto.Math'
27397 INFO: Loading module hook "hook-cryptography.py"...
27747 INFO: Loading module hook "hook-distutils.py"...
27749 INFO: Loading module hook "hook-encodings.py"...
27853 INFO: Loading module hook "hook-google.api.py"...
27856 INFO: Loading module hook "hook-google.api_core.py"...
27859 INFO: Loading module hook "hook-google.cloud.py"...
27862 INFO: Loading module hook "hook-google.cloud.speech.py"...
27865 INFO: Loading module hook "hook-grpc.py"...
27871 INFO: Loading module hook "hook-lib2to3.py"...
27875 INFO: Loading module hook "hook-lxml.etree.py"...
27877 INFO: Loading module hook "hook-pkg_resources.py"...
28900 INFO: Processing pre-safe import module hook   win32com
29153 INFO: Excluding import '__main__'
29156 INFO:   Removing import of __main__ from module pkg_resources
29157 INFO: Loading module hook "hook-pycparser.py"...
29159 INFO: Loading module hook "hook-pydoc.py"...
29159 INFO: Loading module hook "hook-PyQt5.py"...
29308 INFO: Loading module hook "hook-PyQt5.QtCore.py"...
29408 INFO: Loading module hook "hook-PyQt5.QtGui.py"...
29585 INFO: Loading module hook "hook-PyQt5.QtWidgets.py"...
29799 INFO: Loading module hook "hook-PyQt5.uic.py"...
29804 INFO: Loading module hook "hook-pythoncom.py"...
30419 INFO: Loading module hook "hook-pytz.py"...
30503 INFO: Loading module hook "hook-pywintypes.py"...
31132 INFO: Loading module hook "hook-setuptools.py"...
40100 INFO: Loading module hook "hook-sysconfig.py"...
40101 INFO: Loading module hook "hook-win32com.py"...
40926 INFO: Loading module hook "hook-xml.dom.domreg.py"...
40928 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
40930 INFO: Loading module hook "hook-xml.py"...
40933 INFO: Loading module hook "hook-vlc.py"...
41027 WARNING: Unable to copy metadata for vlc: The 'vlc' distribution was not found and is required by the application
49562 INFO: Determining a mapping of distributions to packages...
124358 WARNING: Unable to determine requirements for vlc: The 'vlc' distribution was not found and is required by the application
132150 INFO: Loading module hook "hook-importlib_metadata.py"...
132153 INFO: Loading module hook "hook-numpy.core.py"...
132282 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
132290 INFO: Loading module hook "hook-numpy.py"...
132292 INFO: Loading module hook "hook-pytest.py"...
133896 INFO: Loading module hook "hook-scipy.py"...
134261 INFO: Looking for ctypes DLLs
134476 INFO: Analyzing run-time hooks ...
134486 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
134491 INFO: Including run-time hook 'pyi_rth_certifi.py'
134493 INFO: Including run-time hook 'pyi_rth_pkgres.py'
134495 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
134497 INFO: Including run-time hook 'pyi_rth_pyqt5.py'
134519 INFO: Looking for dynamic libraries
136937 WARNING: lib not found: LIBPQ.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\plugins\sqldrivers\qsqlpsql.dll
137339 WARNING: lib not found: Qt5MultimediaQuick.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\qml\QtMultimedia\declarative_multimedia.dll
137561 WARNING: lib not found: api-ms-win-core-winrt-l1-1-0.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\plugins\position\qtposition_winrt.dll
137567 WARNING: lib not found: api-ms-win-core-winrt-string-l1-1-0.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\plugins\position\qtposition_winrt.dll
139106 WARNING: lib not found: api-ms-win-core-winrt-l1-1-0.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\plugins\audio\qtaudio_wasapi.dll
139112 WARNING: lib not found: api-ms-win-core-winrt-string-l1-1-0.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\plugins\audio\qtaudio_wasapi.dll
141078 WARNING: lib not found: api-ms-win-core-winrt-l1-1-0.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\bin\Qt5Bluetooth.dll
141084 WARNING: lib not found: api-ms-win-core-winrt-string-l1-1-0.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\bin\Qt5Bluetooth.dll
142131 WARNING: lib not found: api-ms-win-core-winrt-l1-1-0.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\bin\Qt5Bluetooth.dll
142135 WARNING: lib not found: api-ms-win-core-winrt-string-l1-1-0.dll dependency of c:\users\garud\anaconda3\lib\site-packages\PyQt5\Qt\bin\Qt5Bluetooth.dll
143374 INFO: Looking for eggs
143374 INFO: Using Python library c:\users\garud\anaconda3\python37.dll
143376 INFO: Found binding redirects:
[]
143391 INFO: Warnings written to D:\Speechrecog\16march_2020\Frenchuolinguo-master\Frenchuolinguo\build\controller\warn-controller.txt
143585 INFO: Graph cross-reference written to D:\Speechrecog\16march_2020\Frenchuolinguo-master\Frenchuolinguo\build\controller\xref-controller.html
146071 INFO: checking PYZ
146080 INFO: Building because toc changed
146081 INFO: Building PYZ (ZlibArchive) D:\Speechrecog\16march_2020\Frenchuolinguo-master\Frenchuolinguo\build\controller\PYZ-00.pyz
147913 INFO: Building PYZ (ZlibArchive) D:\Speechrecog\16march_2020\Frenchuolinguo-master\Frenchuolinguo\build\controller\PYZ-00.pyz completed successfully.
148062 INFO: checking PKG
148073 INFO: Building because toc changed
148073 INFO: Building PKG (CArchive) PKG-00.pkg
148789 WARNING: One binary added with two internal names.
148789 WARNING: ('site-packages\\win32\\pywintypes37.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\win32\\pywintypes37.dll',
 'BINARY')
148791 WARNING: was placed previously at
148795 WARNING: ('pywintypes37.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\win32\\pywintypes37.dll',
 'BINARY')
154889 WARNING: One binary added with two internal names.
154889 WARNING: ('Qt5Core.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Core.dll',
 'BINARY')
154891 WARNING: was placed previously at
154894 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Core.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Core.dll',
 'BINARY')
154917 WARNING: One binary added with two internal names.
154918 WARNING: ('Qt5Widgets.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Widgets.dll',
 'BINARY')
154919 WARNING: was placed previously at
154923 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Widgets.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Widgets.dll',
 'BINARY')
154942 WARNING: One binary added with two internal names.
154943 WARNING: ('Qt5Multimedia.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Multimedia.dll',
 'BINARY')
154944 WARNING: was placed previously at
154947 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Multimedia.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Multimedia.dll',
 'BINARY')
154977 WARNING: One binary added with two internal names.
154977 WARNING: ('Qt5Gui.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Gui.dll',
 'BINARY')
154979 WARNING: was placed previously at
154982 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Gui.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Gui.dll',
 'BINARY')
155011 WARNING: One binary added with two internal names.
155012 WARNING: ('Qt5Network.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Network.dll',
 'BINARY')
155013 WARNING: was placed previously at
155017 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Network.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Network.dll',
 'BINARY')
155025 WARNING: One binary added with two internal names.
155026 WARNING: ('Qt5Qml.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Qml.dll',
 'BINARY')
155026 WARNING: was placed previously at
155029 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Qml.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Qml.dll',
 'BINARY')
155048 WARNING: One binary added with two internal names.
155049 WARNING: ('Qt5Quick.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Quick.dll',
 'BINARY')
155055 WARNING: was placed previously at
155055 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Quick.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Quick.dll',
 'BINARY')
155723 WARNING: One binary added with two internal names.
155724 WARNING: ('Qt5DBus.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5DBus.dll',
 'BINARY')
155725 WARNING: was placed previously at
155729 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5DBus.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5DBus.dll',
 'BINARY')
155736 WARNING: One binary added with two internal names.
155737 WARNING: ('Qt5Location.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Location.dll',
 'BINARY')
155737 WARNING: was placed previously at
155740 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Location.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Location.dll',
 'BINARY')
155763 WARNING: One binary added with two internal names.
155763 WARNING: ('Qt5Bluetooth.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Bluetooth.dll',
 'BINARY')
155765 WARNING: was placed previously at
155768 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Bluetooth.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Bluetooth.dll',
 'BINARY')
155876 WARNING: One binary added with two internal names.
155877 WARNING: ('Qt5QuickTest.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickTest.dll',
 'BINARY')
155879 WARNING: was placed previously at
155882 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5QuickTest.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickTest.dll',
 'BINARY')
155906 WARNING: One binary added with two internal names.
155906 WARNING: ('Qt5Test.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Test.dll',
 'BINARY')
155908 WARNING: was placed previously at
155911 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Test.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Test.dll',
 'BINARY')
156028 WARNING: One binary added with two internal names.
156028 WARNING: ('Qt5QuickShapes.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickShapes.dll',
 'BINARY')
156030 WARNING: was placed previously at
156034 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5QuickShapes.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickShapes.dll',
 'BINARY')
156055 WARNING: One binary added with two internal names.
156055 WARNING: ('Qt5QuickControls2.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickControls2.dll',
 'BINARY')
156057 WARNING: was placed previously at
156060 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5QuickControls2.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickControls2.dll',
 'BINARY')
156077 WARNING: One binary added with two internal names.
156077 WARNING: ('Qt5QuickTemplates2.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickTemplates2.dll',
 'BINARY')
156079 WARNING: was placed previously at
156084 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5QuickTemplates2.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickTemplates2.dll',
 'BINARY')
156109 WARNING: One binary added with two internal names.
156109 WARNING: ('Qt5Svg.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Svg.dll',
 'BINARY')
156110 WARNING: was placed previously at
156114 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Svg.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Svg.dll',
 'BINARY')
156122 WARNING: One binary added with two internal names.
156122 WARNING: ('Qt5WebSockets.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5WebSockets.dll',
 'BINARY')
156123 WARNING: was placed previously at
156126 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5WebSockets.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5WebSockets.dll',
 'BINARY')
156133 WARNING: One binary added with two internal names.
156133 WARNING: ('Qt5Sql.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Sql.dll',
 'BINARY')
156134 WARNING: was placed previously at
156135 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Sql.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Sql.dll',
 'BINARY')
156152 WARNING: One binary added with two internal names.
156153 WARNING: ('Qt5QuickParticles.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickParticles.dll',
 'BINARY')
156155 WARNING: was placed previously at
156155 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5QuickParticles.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5QuickParticles.dll',
 'BINARY')
156177 WARNING: One binary added with two internal names.
156177 WARNING: ('Qt5Xml.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Xml.dll',
 'BINARY')
156179 WARNING: was placed previously at
156182 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Xml.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Xml.dll',
 'BINARY')
156200 WARNING: One binary added with two internal names.
156200 WARNING: ('libcrypto-1_1-x64.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\libcrypto-1_1-x64.dll',
 'BINARY')
156202 WARNING: was placed previously at
156205 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\libcrypto-1_1-x64.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\libcrypto-1_1-x64.dll',
 'BINARY')
156219 WARNING: One binary added with two internal names.
156219 WARNING: ('Qt5Sensors.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Sensors.dll',
 'BINARY')
156220 WARNING: was placed previously at
156222 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Sensors.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Sensors.dll',
 'BINARY')
156241 WARNING: One binary added with two internal names.
156242 WARNING: ('Qt5Positioning.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Positioning.dll',
 'BINARY')
156243 WARNING: was placed previously at
156246 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Positioning.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Positioning.dll',
 'BINARY')
156263 WARNING: One binary added with two internal names.
156263 WARNING: ('Qt5OpenGL.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5OpenGL.dll',
 'BINARY')
156267 WARNING: was placed previously at
156270 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5OpenGL.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5OpenGL.dll',
 'BINARY')
156291 WARNING: One binary added with two internal names.
156291 WARNING: ('Qt5PositioningQuick.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5PositioningQuick.dll',
 'BINARY')
156293 WARNING: was placed previously at
156296 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5PositioningQuick.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5PositioningQuick.dll',
 'BINARY')
156332 WARNING: One binary added with two internal names.
156333 WARNING: ('Qt5RemoteObjects.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5RemoteObjects.dll',
 'BINARY')
156335 WARNING: was placed previously at
156338 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5RemoteObjects.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5RemoteObjects.dll',
 'BINARY')
156369 WARNING: One binary added with two internal names.
156369 WARNING: ('Qt5Nfc.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Nfc.dll',
 'BINARY')
156371 WARNING: was placed previously at
156371 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5Nfc.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5Nfc.dll',
 'BINARY')
156391 WARNING: One binary added with two internal names.
156392 WARNING: ('mfc140u.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\pythonwin\\mfc140u.dll',
 'BINARY')
156393 WARNING: was placed previously at
156396 WARNING: ('site-packages\\pythonwin\\mfc140u.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\pythonwin\\mfc140u.dll',
 'BINARY')
156936 WARNING: One binary added with two internal names.
156936 WARNING: ('Qt5PrintSupport.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5PrintSupport.dll',
 'BINARY')
156939 WARNING: was placed previously at
156941 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5PrintSupport.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5PrintSupport.dll',
 'BINARY')
157483 WARNING: One binary added with two internal names.
157484 WARNING: ('Qt5WebChannel.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5WebChannel.dll',
 'BINARY')
157488 WARNING: was placed previously at
157491 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5WebChannel.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5WebChannel.dll',
 'BINARY')
157534 WARNING: One binary added with two internal names.
157535 WARNING: ('Qt5SerialPort.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5SerialPort.dll',
 'BINARY')
157536 WARNING: was placed previously at
157540 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5SerialPort.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5SerialPort.dll',
 'BINARY')
157560 WARNING: One binary added with two internal names.
157560 WARNING: ('Qt5XmlPatterns.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5XmlPatterns.dll',
 'BINARY')
157562 WARNING: was placed previously at
157565 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\Qt5XmlPatterns.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\Qt5XmlPatterns.dll',
 'BINARY')
157593 WARNING: One binary added with two internal names.
157593 WARNING: ('libvlccore.dll', 'D:\\Software\\VLC\\libvlccore.dll', 'BINARY')
157594 WARNING: was placed previously at
157598 WARNING: ('libvlccore.dylib', 'D:\\Software\\VLC\\libvlccore.dll', 'BINARY')
157610 WARNING: One binary added with two internal names.
157611 WARNING: ('libssl-1_1-x64.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\libssl-1_1-x64.dll',
 'BINARY')
157611 WARNING: was placed previously at
157614 WARNING: ('site-packages\\PyQt5\\Qt\\bin\\libssl-1_1-x64.dll',
 'c:\\users\\garud\\anaconda3\\lib\\site-packages\\PyQt5\\Qt\\bin\\libssl-1_1-x64.dll',
 'BINARY')
633915 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
636281 INFO: Bootloader c:\users\garud\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
636282 INFO: checking EXE
636333 INFO: Building because toc changed
636333 INFO: Building EXE from EXE-00.toc
636334 INFO: Appending archive to EXE D:\Speechrecog\16march_2020\Frenchuolinguo-master\Frenchuolinguo\dist\controller.exe
638128 INFO: Building EXE from EXE-00.toc completed successfully.](url)

I have also copied all the plugins from the vlc to the executable folder.

**Comment by Legorooj** [comment]
@Sumit1673 I don't have the time to debug this app. You'll need to build it from the ground up, and try and find what's causing the error. Sorry I can't help more, but this is too large & time consuming.

**Comment by Sumit1673** [comment]
Thanks for your help.
