### ISSUE TITLE
Exe applications created using this library do not run on Windows

### ISSUE THREAD

**Issue by EkS2018** [pyinstaller/pyinstaller#4756]
The pywin32 227 library only works normally with Python versions up to 3.7.x, and starting from branch 3.8.x (on Windows), the exe files that it creates do not run. Can you fix it?  Below is a text of the error that appears when you try to run an exe file created using this library:
Failed to execute script "name of my file"

**Comment by Legorooj** [comment]
Python 3.8 isn't supported.
