### ISSUE TITLE
i have faced  `GLIBC_2.25' not found

### ISSUE THREAD

**Issue by themeswordpress** [pyinstaller/pyinstaller#4758]
I have faced the following issue 
plz advice 

dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.25' not found (required by /tmp/_MEIgGJyYB/libpython3.6m.so.1.0)

**Comment by Legorooj** [comment]
@themeswordpress we can't fix that; python needs a newer version of glibc. Please build on the oldest system you have available.
