### ISSUE TITLE
Compiled GNU / Linux program does not start

### ISSUE THREAD

**Issue by Salim9304** [pyinstaller/pyinstaller#4759]
The compiled program does not work on other Linux distributions.
The compilation itself is successful.

> OS Linux kali 5.3.0-kali2-amd64 #1 SMP Debian 5.3.9-3kali1 (2019-11-20) x86_64 GNU/Linux
> Python 3.7.5
> pyinstaller 3.6

1)Directory assembly
2)Assembly to file

```
cd ~/dir
./program
```

> [9323] Error loading Python lib '/tmp/_MEIP2EuGq/libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIP2EuGq/libpython3.7m.so
```
cd ~/dir
./program

```
`libpython3.7m.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version GLIBC_2.29' not found (required by /dir/program/libpython3.7m.so.1.0)`

**Comment by Legorooj** [comment]
Is this the machine you built it on?

**Comment by Salim9304** [comment]
No, on the machine on which he built everything works.  
Does not work on the same machine, but on other Linux distributions.

**Comment by Legorooj** [comment]
Which OS did you build on? We need to know both the target and the build system's details

**Comment by Salim9304** [comment]
ldd --version
2.29

In other distributions 2.28, apparently therefore an error.
