### ISSUE TITLE
Please add hook of pyuserinput (pykeyboard and pymouse) or what's a good way to generate hook by yourself.

### ISSUE THREAD

**Issue by LYF511** [pyinstaller/pyinstaller#4763]
Please add hook of pyuserinput (pykeyboard and pymouse) or what's a good way to generate hook by yourself.
I recently encountered a difficulty in developing a project: my project uses pykeyboard, but pyinstaller doesn't have his hook. This module is very easy to use, and I can't bear to let users configure Python environment.
Please add hook of pyuserinput (pykeyboard and pymouse).
Or what's a good way to generate hook by yourself.

Tip: I am a Chinese, not very good at English, so I use Baidu translation, there may be errors, please understand.

**Comment by Legorooj** [comment]
What is the problem/traceback you're getting?
