### ISSUE TITLE
Building bootloader fails with LNK1169/LNK2005

### ISSUE THREAD

**Issue by TilmanK** [pyinstaller/pyinstaller#4767]
## Description of the issue
I'm trying to build the bootloader since building my application with the current version from pypi will generate an executable that is detected as Trojan by Windows Defender.

The build fails with the following error:
`libucrt.lib(strnlen.obj) : error LNK2005: strnlen ist bereits in pyi_utils.c.2.o definiert.
C:\Users\krumm-ti\Documents\PycharmProjects\pyinstaller-develop\bootloader\build\debug\run_d.exe : fatal error LNK1169: Mindestens ein mehrfach definiertes Symbol gefunden.
 
Waf: Leaving directory `C:\Users\krumm-ti\Documents\PycharmProjects\pyinstaller-develop\bootloader\build\debug'
Build failed`

Full log: https://pastebin.com/Ep41V0bR
## Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: 3.8.2 (64 bit)
* Platform: e.g GNU/Linux (distribution), Windows (language settings), Windows 10 64bit
* Did you also try this on another platform? Does it work there? No

I'm using the lastest dev branch to build. I also tried with the pypi version - same error there
Build is done with MSVC 14.25.28610.

**Comment by Legorooj** [comment]
Try python 3.7; we don't support 3.8

**Comment by jay0lee** [comment]
I saw this issue also recently. I noticed that with Visual Studio 2017, waf configuration would fail to detect strnlen, thus on make bootloader the strnlen from pyi_utils.c would be included and you would get this error.

I switched to VS 14.0 and the package from Chocalatey and it worked for me:

https://chocolatey.org/packages/vcbuildtools

this is also the route recommended in the bootloader build guide:

https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html

**Comment by jay0lee** [comment]
Here's a build on Travis CI that was showing this problem. You can see bootloader build configure is failing to find strnlen here:

https://travis-ci.org/github/jay0lee/GAM/jobs/667814988#L228

and here's the dump of config.log that shows the failure when testing for strnlen:

https://travis-ci.org/github/jay0lee/GAM/jobs/667814988#L885

hope this helps.

**Comment by Legorooj** [comment]
Can you try using the installer from https://visualstudio.microsoft.com/downloads/#build-tools-for-visual-studio-2019? Those are the latest build tools, which work fine on my system - It all builds sucessfully. (If using chocolatey, please uninstall all choco packages first)

**Comment by TilmanK** [comment]
@Legorooj I currently have installed (and had while creating the bug):
![grafik](https://user-images.githubusercontent.com/8856390/78886025-dc9c4f00-7a5d-11ea-8c07-138ea07fa898.png)

**Comment by Legorooj** [comment]
@TilmanK can you try the link I posted? If you don't have the compilers installed it won't do anything.

**Comment by Chrisg2000** [comment]
I experienced the same problem in the past too. A very strange workaround worked for me, and I'm not completely sure why it did.

I had to move/copy the project to another hard drive. So `msvc` was installed on my `C:`-disk and the project was on `D:`.

The error occurred suddenly from one day to the other on both of my computers and took me a long time to fix. I don't know if it was a Windows, msvc or waf update, which caused it to break. At least I was able to compile the project on D: and on C: I still got the same error.

**Comment by Legorooj** [comment]
@Chrisg2000 odd - I compiled it fine on my D: drive - though it's technically a micro-sd (ie a removable drive)

**Comment by htgoebel** [comment]
Checking for `strnlen` was added in 8461e962fdb4cb1719ff1d89935fafa2c997c403. It assumes `strnlen` to be available in `string.h`. And for Windows our test-builds also detect it, see e.g. https://ci.appveyor.com/project/matysek/pyinstaller/builds/32125381/job/9slq0liec9wbptxy. So I wonder why `strnlen` it not detected on your system.

Please compare the command in your pasted log with the one https://ci.appveyor.com/project/htgoebel/pyinstaller/builds/32131317#L41 - which I just made t print the output verbose, too.

Otherwise you need to find out, why "waf configure" on your system does not detect `strnlen` in `string.h`. Maybe some wrongly set environment variables? Maybe some file missing?

If this does not help:
So other observations (I do not expect the to be relevant, tough, but want to exclude this as an reason)
-  In your build the arch is detected, while in our build it is fixed. Please try running waf with `--target-arch=64bit`
- Please try running waf with python 3.5, 3.6 or 3.7 

@Legorooj FYI: While the bootloader does not support Python 3.8 yet, building the bootloader with 3.8 should work (as long as waf supports it), since bootloader at build-time is agnostic of the Python version. At least building should not fail since some "configure" check works wrong, as this is pure waf code.

**Comment by jay0lee** [comment]
@htgoebel here's the specific failure I see in config.log when checking for strnlen:

```
Checking for function strnlen
==>
    #include <string.h>
    int main(int argc, char **argv) {
        void (*p)();
        (void)argc; (void)argv;
        p=(void(*)())(strnlen);
        return !p;
    }
<==
[1/2] Compiling build\conf_check_21240939c9ddbcc20d9e6d66cf882183\test.cpp
['C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX64\\x64\\CL.exe', '/nologo', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\ATLMFC\\include', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\include', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.6.1\\include\\um', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\ucrt', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\shared', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\um', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\winrt', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.18362.0\\cppwinrt', '/DWIN32', '..\\test.cpp', '/FC', '/c', '/FoC:\\Users\\travis\\build\\jay0lee\\GAM\\pyinstaller-develop\\bootloader\\build\\conf_check_21240939c9ddbcc20d9e6d66cf882183\\testbuild\\test.cpp.1.o']
out: test.cpp
c:\program files (x86)\windows kits\10\include\10.0.18362.0\ucrt\corecrt.h(10): fatal error C1083: Cannot open include file: 'vcruntime.h': No such file or directory
from C:\Users\travis\build\jay0lee\GAM\pyinstaller-develop\bootloader: Test does not build: Traceback (most recent call last):
  File "C:\Users\travis\build\jay0lee\GAM\pyinstaller-develop\bootloader\waf3-2.0.19-9054d7a7f551c4b14b458abcd389b706\waflib\Configure.py", line 333, in run_build
    bld.compile()
  File "C:\Users\travis\build\jay0lee\GAM\pyinstaller-develop\bootloader\waf3-2.0.19-9054d7a7f551c4b14b458abcd389b706\waflib\Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 2 (run with -v to display more information)
```

**Comment by htgoebel** [comment]
@TilmanK 
>  the current version from pypi will generate an executable that is detected as Trojan by Windows Defender.

Please contact you anti-virus vendor. Thei did a bad job in detecting what the actual Trojan is.

**Comment by htgoebel** [comment]
> c…\include\10.0.18362.0\ucrt\corecrt.h(10): fatal error C1083: Cannot open include file: 'vcruntime.h': No such file or directory

This looks like some include directory is missing. Please try to figure out what has changed here. Maybe this file has been moved into another directory which is not part of the include path. I would expect to find a note about this in the release notes. (But well, hey, this is Microsoft)

**Comment by htgoebel** [comment]
Maybe this gives a hint: https://forum.juce.com/t/missing-corecrt-h-and-windows-h-files-vs-2017/29195

**Comment by Legorooj** [comment]
@htgoebel `vcruntime.h` should always be accessible - it's part of the "system includes". If the user(s compiler) can't find it, their system is messed up.

**Comment by Legorooj** [comment]
Hey all. Can you please try what's described in https://github.com/pyinstaller/pyinstaller/issues/4824#issuecomment-620301709

**Comment by Legorooj** [comment]
I'm going to close this issue; see #4824. There's no point having two identical issues open.
