### ISSUE TITLE
Why 'help' function is not working in pyinstaller distribution?

### ISSUE THREAD

**Issue by lgervich** [pyinstaller/pyinstaller#4768]
When I'm calling python 'help' function from pyinstaller binary I get an error:
> NameError: name 'help' is not defined

Is this a bug or limitations of the framework?

**Comment by Chrisg2000** [comment]
This is a restriction set intentionally by PyInstaller.
 `help` is implemented in the module `site,` which is replaced by the fakemodul `fake-modules/site` when compiling with PyInstaller. This does not seem to work at the moment.
Use `pydoc.help` or similar instead to get the same functionality.

**Comment by Legorooj** [comment]
> This is a restriction set intentionally by PyInstaller.
> `help` is implemented in the module `site,` which is replaced by the fakemodul `fake-modules/site` when compiling with PyInstaller. This does not seem to work at the moment.
> Use `pydoc.help` or similar instead to get the same functionality.

Is the correct solution @Chrisg2000
