### ISSUE TITLE
The command line window is displayed without the Windows taskbar icon

### ISSUE THREAD

**Issue by ruxia-TJY** [pyinstaller/pyinstaller#4770]
Please use the mailing list see <http://www.pyinstaller.org/support.html#mailing-list> for details.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker, but closed.

A command line program, I want to display the command line window, but not the Windows taskbar icon.
Just like VB.net's ShowInTaskBar property
Use Google Translate to speak inappropriately, please forgive me
thank you!

**Comment by Legorooj** [comment]
Please use a third party tool. All the GUI toolkits support this, and you can do it with other methods, but I don't know them. 

This is not a feature for PyInstaller.
