### ISSUE TITLE
filename.py conflicts with filename/__init__.py

### ISSUE THREAD

**Issue by mightymercado** [pyinstaller/pyinstaller#4771]
When compiling for **Windows 10** with `pyinstaller filename.py`, and having a sub-module coincidentally named `filename` with an `__init__.py`, the compiler will treat the starting point to be `__init__.py` instead of `filename.py`. The issue doesn't occur with other OS'es.

**Comment by Legorooj** [comment]
Can you provide a working example? Minimal, reproducible etc

**Comment by Legorooj** [comment]
@mightymercado thanks for letting us know.

**Comment by Legorooj** [comment]
Confirmed. This is a valid issue. I'll work on a fix.

**Comment by shoshber** [comment]
Not just on Windows--I just ran into this exact issue on Ubuntu 16.

**Comment by Legorooj** [comment]
@shoshber this is an issue with ModuleGraph and Python imports. I'm looking into a fix.
