### ISSUE TITLE
Failed to execute pyiboot01_bootstrap

### ISSUE THREAD

**Issue by Venusguy** [pyinstaller/pyinstaller#4772]
Hello guys,

First of all I'm not a programmer or anything like that. I'm just trying to open an .exe file (that was creating with python I guess). My friends could open it in their laptop, but I get the error message: failed to execute pyiboot01_bootstrap
My friends don't have python, they don't even know what python is.
It might be something related to my settings ? I have no idea what to do to open the file :(
I hope you can help me :)
Thanks much!

**Comment by Legorooj** [comment]
What's the program called? I'm closing this issue, but I'll help track down the provider of the exe; they're the ones to contact at the moment.

**Comment by Venusguy** [comment]
why close the issue ? 
the program is a tool for a game called onmyoji

**Comment by Venusguy** [comment]
but it's a chinese tool cause the game is from china originally
i used this tool a few months ago but now it doesnt work while it works for others so i dont think the problem is the exe

**Comment by Legorooj** [comment]
Which OS are you running? Windows 7, 8, or 10? 

I closed the issue because it's officially out of our support scope.

**Comment by Venusguy** [comment]
ok thanks. Im on windows 10

**Comment by Legorooj** [comment]
Ok, I can't think of any reason for it to be failing off the top of my head - I'd need some source code, which the company would never let me have. I'd suggest you contact the provider. Sorry I can't help more!

**Comment by Venusguy** [comment]
ok sad
