### ISSUE TITLE
AssertionError when running frozen program using Lark.

### ISSUE THREAD

**Issue by zurgeg** [pyinstaller/pyinstaller#4776]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.5```
* Version of Python: 3.7
* Platform: Windows (English)
* Did you also try this on another platform? Does it work there? No, and it doesn't appear to be a platform problem.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import lark
grammer = '''
?start = value
?value = WORD
%import common.word

p = lark.Parser(grammer)

```
import lark
grammer = '''
?start = value
?value = WORD
%import common.word

p = lark.Parser(grammer)

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "runner1_0.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "c:\users\zurge\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "parser1_0.py", line 54, in <module>
  File "site-packages\lark\lark.py", line 204, in __init__
  File "site-packages\lark\load_grammar.py", line 791, in load_grammar
  File "site-packages\lark\load_grammar.py", line 568, in import_grammar
AssertionError
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by Legorooj** [comment]
This is a problem with `Lark`, not PyInstaller. `Lark`'s code is raising this error.

**Comment by zurgeg** [comment]
No, the code works when not frozen so I think it’s a problem with the way
pyinstaller freezes. Before it gave me an error about not finding
common.lark which I then put in the CWD.

**Comment by zurgeg** [comment]
See the issue that mentions this one for a fix.

**Comment by MegaIng** [comment]
The problem is a single data file that is not being included. How is the best way to solve this? I guess this would be with a hook. Should this hooked be placed inside PyInstaller. the problem with that is the package `lark-parser` has the the same import name as the less used package `lark`.

**Comment by zurgeg** [comment]
@Megalng I think the solution is to put lark-hook.py in lark-parser itself.

**Comment by MegaIng** [comment]
The question is whether or not PyInstaller will search for hooks there. I am not sure, and I didn't manage to find information about that.

**Comment by Legorooj** [comment]
@MegaIng you can integrate hooks straight into your package, but note that feature is in final Dev and will only go live next release. Would you be willing to give it a go? We'd like some feedback on it's usability.

**Comment by MegaIng** [comment]
So #831 did get implemented in some form? Then of course, that would be the most optimal solution. Notice however that I am not the actual user of PyInstaller, that is @zurgeg.

Where should the hook be placed? (@erezsh is the actual maintainer of lark-parser. He might be interested in this discuss as well)

**Comment by Legorooj** [comment]
@MegaIng (@erezsh) the exact issue is #4582. It's almost complete, and the details for adding hooks in the setup.py is [here](https://pyinstaller-sample-hook.readthedocs.io/en/latest/setup.py.html). It's very much alpha/beta so feedback would be great.

**Comment by erezsh** [comment]
@Legorooj 

Isn't there another way for packages to specify their essential data files, say through `setup.py`? Lark can't be the first package to require files that don't end in `py`..

How did you solve this before this new feature?

**Comment by erezsh** [comment]
I mean, you're already reading `setup.py`, looking for `entry_points/pyinstaller40`. Why not just read `package_data`? It's part of the Python standard and it's right there. Excuse me if I misunderstood.

**Comment by Legorooj** [comment]
@erezsh no, we aren't reading setup.py. When a package installs, it registers the entry point in
the enviroment. We (will, as of next release,) read it from the env. RE first comment, you use a
hook file, which collects the data files, or binary extensions if required.

Currently, hooks are integrated into pyinstaller - we have over 100 included. (We'll probably be
moving those to another package soon, which works alongside pyinstaller)

What I was asking, is if you'd be willing to integrate the hook directly into Lark, so that when lark is installed, the hook is installed. This allows you to maintain it, instead of us moderating community maintenance. If you'd like to have it maintained by the community, we'll merge the linked PR.

**Comment by erezsh** [comment]
It seems a little elaborate, but I don't mind adding it to Lark, as long as it's unobtrusive. Since the solution is very simple, and the only complication arises from having to install the hooks correctly, is there any chance that you could spare a minute and do it?

**Comment by MegaIng** [comment]
I did just added a PR: https://github.com/lark-parser/lark/pull/553. But I would like @Legorooj to look over it to check if I understood the example correctly.

**Comment by Legorooj** [comment]
@MegaIng looks great! I've left a review. I'm going to close the PR into PyInstaller - I can always reopen if needed.
