### ISSUE TITLE
Annot color, page background color

### ISSUE THREAD

**Issue by PCarle** [pyinstaller/pyinstaller#4780]
I create a Qt(PySide) color picker and try use picked color for create annotation.  annotation rendering seem's wrong from color selected, for confirming this i created the minimum script bellow:
```Python 
## demande GitHub pymupdf 
import fitz
print(fitz.__doc__)
import numpy as np

r = fitz.Rect(20, 20, 100, 40)

doc = fitz.open()
page = doc.newPage()


page.insertText(r.br , "selector (image in background) colors last color selected:", color=red)
page.insertText(r.br +(0,15), "background Qt(PySide)Color rgba( 0, 0, 127, 102 )", color=red)
page.insertText(r.br +(0,30), "border Qt(PySide)Color rgba( 0, 85, 0, 102 )", color=red)
words = page.getTextWords()
xx0=155565666
yy0=155565666
xx1=0
yy1=0
for (x0,y0,x1,y1,w,blocknum ,line,wordnum) in words:
    xx0=min(xx0,x0)
    yy0=min(y0,yy0)
    xx1=max(xx1,x1)
    yy1=max(yy1,y1)

print(xx0,yy0,xx1,yy1)

xx0-=2
yy0-=0
xx1+=2
yy1+=65
print(xx0,yy0,xx1,yy1)
opacity=102./255.
c2=(0,85./255.,0)
c1=(0,0,127./255.)


xx_off,yy_off =(0,0)
annot = page.addPolygonAnnot([[xx0+xx_off,yy0+yy_off],
                                  [xx1+xx_off,yy0+yy_off],
                                  [xx1+xx_off,yy1+yy_off],
                                  [xx0+xx_off,yy1+yy_off],
                                  [xx0+xx_off,yy0+yy_off]])
annot.setOpacity(opacity)
annot.setBlendMode(fitz.PDF_BM_Multiply)
annot.setBorder(width=3)
annot.setColors(stroke=c2, fill=c1)
annot.update()

image_shrink=0.9
page.insertImage(fitz.Rect(10,45,516.*image_shrink,393.*image_shrink),"./image_annot_sel_color.jpg",keep_proportion=True,overlay=False)



page = doc.reload_page(page)  # refresh the page before taking pictures
pix=page.getPixmap(matrix=fitz.Matrix(fitz.Identity).preScale(3,3),alpha=True,colorspace="RGBA")

from PIL import Image, ImageTk
mode = "RGBA"
img = Image.frombytes(mode, [pix.width, pix.height], pix.samples)

from matplotlib import pyplot as plt
import matplotlib as mpl
mpl.rc("savefig", dpi=300)
plt.figure(figsize = (20,20))
fig, ax = plt.subplots(figsize=(18, 20))
axes = plt.gca()
axes.set_xlim([0,1500])
axes.set_ylim([1000,-20])
ax.imshow(np.asarray(img))
```
where "./image_annot_sel_color.jpg" is: 
![image_annot_sel_color](https://user-images.githubusercontent.com/16350743/78234379-5f119580-74d7-11ea-90b0-33aef5781537.jpg)

a screen dump of the PySide color picker (the selected color (border and background are showed in left rectangle, full white color is selected in right rectangle) 
The result of the script is: 
![color pymupdf](https://user-images.githubusercontent.com/16350743/78234396-63d64980-74d7-11ea-8f38-a130951efccd.png)

Colors are a mysteris from me. With html development tool  and https://www.w3schools.com/colors/colors_hexadecimal.asp?color=00bfff for rgb conversion : 
blue on page background = #9a9aad = rgb(154, 154, 173)
blue in Qt rectangle = #9090c2 = rgb(144, 144, 194)
blue on white rectangle = #9a9acc = rgb(154, 154, 204)
 green on background page = #9aa79a = rgb(154, 167, 154), 
green on white rectangle = #9abb9a = rgb(154, 187, 154)

So Question is :  how explain rendering colors ? i'm 
![dubitatif](https://user-images.githubusercontent.com/16350743/78237005-0e03a080-74db-11ea-8d20-bcc57f420c00.jpg)

**Comment by htgoebel** [comment]
This does not belong to PyInstaller.

**Comment by PCarle** [comment]
sorry wrong github
