### ISSUE TITLE
provide a list of paths for runtime tmp dir

### ISSUE THREAD

**Issue by MstWntd** [pyinstaller/pyinstaller#4787]
Scenarios:

1. Poorly setup envs have differences
2. /tmp/ and /var/tmp are noexec on some boxes
3. An expected tmp dir is missing or is full

Expectation:
In all scenarios I would still like the pyinstaller packaged binary to still somehow extract itself and run. To facilitate this the --runtime-tmpdir option should take a list of paths as it's arg, the binary can extract to the first one, if not found then move on to second path and so forth.

Also would like this moment to say you guys are doing an amazing job, the features and reliability of pyinstaller are nothing short impressive. Thank you all very much.

**Comment by Legorooj** [comment]
@MstWntd interesting feature idea. @bjones1 what do you think? PR wanted?

**Comment by bjones1** [comment]
I'll pass this on to @htgoebel.

**Comment by htgoebel** [comment]
@MstWntd Not sure if we really want to implement this. This would basically make PyInstaller a bomb, extracting file to random places - easy job for a virus. (Maybe we should rethink --runtime-tmpdir, too)

**Comment by Legorooj** [comment]
@htgoebel doesn't PyInstaller currently have a list of temporary directories to try? Well couldn't we just use `--runtime-tmpdir` like `--additional-hooks-dir` and append the extra user provided directories to the list?

**Comment by MstWntd** [comment]
@htgoebel I appreciate what you are saying, but imho:

a) There is a 100 ways a virus can currently do that
b) This is why I explicitly didn't ask for pyinstaller to create the missing directories
c) Portability is fundamental to why people use pyinstaller and this makes that feature more robust and honestly increases reliability overall.

**Comment by MstWntd** [comment]
Any further thoughts?

**Comment by Legorooj** [comment]
@MstWntd I think your idea has merit, but I understand @htgoebel's concerns. We need his input here; he's the project lead.

**Comment by MstWntd** [comment]
@Legorooj np, thank you.

@htgoebel any further thoughts on the issue?

hope you both are doing well in these covid times!..

**Comment by MstWntd** [comment]
@htgoebel if there is nothing further to discuss - then this issue is approved for feature request?..

**Comment by Legorooj** [comment]
@MstWntd expect a bit of a wait. @htgoebel needs to approve this, and doesn't have as much time to devote to PyInstaller. Something like this needs approval from @htgoebel.

**Comment by rokm** [comment]
I don't think the amount of additional logic and introduced potential corner cases justifies the benefit of being able to work around non-standard system configurations. In such cases, it should be up to the user to take the appropriate action to meet the minimum runtime environment requirements (such as setting TMPDIR to appropriate location or cleaning up temporary directory).

And personally, I wouldn't want an application to be trying to unpack itself in various alternative locations if the configured temporary directory is unsuitable for whatever reason. 

So I agree with Harmut's earlier opinion regarding this feature.
