### ISSUE TITLE
Error loading Python DLL 'python37.dll'

### ISSUE THREAD

**Issue by SolomonLeon** [pyinstaller/pyinstaller#4790]
Recently I tried to use pyinstaller's upx mode to package program. The first time I succeeded, but since the second attempt, the program packaged by pyinstaller kept reporting error `Error loading Python DLL 'python38.dll'`

It used to be successful without UPX, but after that attempt, pyinstaller doesn't work at all. Now I have tried to delete upx.exe and even reinstall python37 to python38, but all the new programs packaged by pyinstaller keeps reporting the same errors.

This is t.py:
`print("try")`

This is the packaging log:
> F:\ME\todo\LockerTODO>pyinstaller t.py
116 INFO: PyInstaller: 3.6
116 INFO: Python: 3.8.2
116 INFO: Platform: Windows-10-10.0.18362-SP0
117 INFO: wrote F:\ME\todo\LockerTODO\t.spec
120 INFO: UPX is not available.
127 INFO: Extending PYTHONPATH with paths
['F:\\ME\\todo\\LockerTODO', 'F:\\ME\\todo\\LockerTODO']
127 INFO: checking Analysis
127 INFO: Building Analysis because Analysis-00.toc is non existent
127 INFO: Initializing module dependency graph...
130 INFO: Caching module graph hooks...
139 INFO: Analyzing base_library.zip ...
3457 INFO: Processing pre-find module path hook   distutils
3459 INFO: distutils: retargeting to non-venv dir 'c:\\program files (x86)\\python38-32\\lib'
6649 INFO: Caching module dependency graph...
6824 INFO: running Analysis Analysis-00.toc
6828 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\program files (x86)\python38-32\python.exe
7229 INFO: Analyzing F:\ME\todo\LockerTODO\t.py
7231 INFO: Processing module hooks...
7232 INFO: Loading module hook "hook-distutils.py"...
7234 INFO: Loading module hook "hook-encodings.py"...
7339 INFO: Loading module hook "hook-lib2to3.py"...
7347 INFO: Loading module hook "hook-pydoc.py"...
7348 INFO: Loading module hook "hook-sysconfig.py"...
7350 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
7351 INFO: Loading module hook "hook-xml.py"...
7412 INFO: Loading module hook "hook-_tkinter.py"...
7582 INFO: checking Tree
7582 INFO: Building Tree because Tree-00.toc is non existent
7587 INFO: Building Tree Tree-00.toc
7689 INFO: checking Tree
7690 INFO: Building Tree because Tree-01.toc is non existent
7692 INFO: Building Tree Tree-01.toc
7738 INFO: Looking for ctypes DLLs
7784 INFO: Analyzing run-time hooks ...
7791 INFO: Including run-time hook 'pyi_rth__tkinter.py'
7795 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
7819 INFO: Looking for dynamic libraries
8189 INFO: Looking for eggs
8189 INFO: Using Python library c:\program files (x86)\python38-32\python38.dll
8190 INFO: Found binding redirects:
[]
8205 INFO: Warnings written to F:\ME\todo\LockerTODO\build\t\warn-t.txt
8281 INFO: Graph cross-reference written to F:\ME\todo\LockerTODO\build\t\xref-t.html
8339 INFO: checking PYZ
8340 INFO: Building PYZ because PYZ-00.toc is non existent
8342 INFO: Building PYZ (ZlibArchive) F:\ME\todo\LockerTODO\build\t\PYZ-00.pyz
9325 INFO: Building PYZ (ZlibArchive) F:\ME\todo\LockerTODO\build\t\PYZ-00.pyz completed successfully.
9340 INFO: checking PKG
9341 INFO: Building PKG because PKG-00.toc is non existent
9341 INFO: Building PKG (CArchive) PKG-00.pkg
9384 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
9389 INFO: Bootloader c:\program files (x86)\python38-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
9391 INFO: checking EXE
9392 INFO: Building EXE because EXE-00.toc is non existent
9393 INFO: Building EXE from EXE-00.toc
9393 INFO: Appending archive to EXE F:\ME\todo\LockerTODO\build\t\t.exe
9409 INFO: Building EXE from EXE-00.toc completed successfully.
9422 INFO: checking COLLECT
9423 INFO: Building COLLECT because COLLECT-00.toc is non existent
9424 INFO: Building COLLECT COLLECT-00.toc
11192 INFO: Building COLLECT COLLECT-00.toc completed successfully.

And this is the error:
> F:\ME\todo\LockerTODO\build\t>t
Error loading Python DLL 'F:\ME\todo\LockerTODO\build\t\python38.dll'.
LoadLibrary: 找不到指定的模块。

`找不到指定的模块` meas `The specified module cannot be found`

File list: 

> 2020/04/05  21:56           153,244 Analysis-00.toc
2020/04/05  21:56           783,217 base_library.zip
2020/04/05  21:56           125,000 COLLECT-00.toc
2020/04/05  21:56             2,541 EXE-00.toc
2020/04/05  21:56         1,957,102 PKG-00.pkg
2020/04/05  21:56             1,500 PKG-00.toc
2020/02/25  23:30         3,930,184 python38.dll
2020/04/05  21:56         1,939,956 PYZ-00.pyz
2020/04/05  21:56            27,810 PYZ-00.toc
2020/04/05  21:56         2,201,838 t.exe
2020/04/05  21:56             1,024 t.exe.manifest
2020/04/05  21:56           107,559 Tree-00.toc
2020/04/05  21:56             9,773 Tree-01.toc
2020/04/05  21:56             3,989 warn-t.txt
2020/04/05  21:56           441,731 xref-t.html

[warn-t.txt](https://github.com/pyinstaller/pyinstaller/files/4434123/warn-t.txt) (I have read it, but since I have no idea about this problem, hope this can help you :) )

**Comment by Legorooj** [comment]
@SolomonLeon please can you reproduce this issue with 3.7? 3.8 isn't supported yet. There are major changes that need to be fixed.

**Comment by SolomonLeon** [comment]
@Legorooj 
Still can't work

> F:\ME\todo\LockerTODO>pyinstaller --clean t.py
100 INFO: PyInstaller: 3.6
100 INFO: Python: 3.7.6
100 INFO: Platform: Windows-10-10.0.18362-SP0
100 INFO: wrote F:\ME\todo\LockerTODO\t.spec
103 INFO: UPX is not available.
103 INFO: Removing temporary files and cleaning cache in C:\Users\Administrator\AppData\Roaming\pyinstaller
140 INFO: Extending PYTHONPATH with paths
['F:\\ME\\todo\\LockerTODO', 'F:\\ME\\todo\\LockerTODO']
140 INFO: checking Analysis
140 INFO: Building Analysis because Analysis-00.toc is non existent
144 INFO: Initializing module dependency graph...
148 INFO: Caching module graph hooks...
160 INFO: Analyzing base_library.zip ...
3100 INFO: Caching module dependency graph...
3204 INFO: running Analysis Analysis-00.toc
3208 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\program files (x86)\python37-32\python.exe
3511 INFO: Analyzing F:\ME\todo\LockerTODO\t.py
3519 INFO: Processing module hooks...
3519 INFO: Loading module hook "hook-encodings.py"...
3622 INFO: Loading module hook "hook-pydoc.py"...
3625 INFO: Loading module hook "hook-xml.py"...
3866 INFO: Looking for ctypes DLLs
3866 INFO: Analyzing run-time hooks ...
3878 INFO: Looking for dynamic libraries
4001 INFO: Looking for eggs
4001 INFO: Using Python library c:\program files (x86)\python37-32\python37.dll
4006 INFO: Found binding redirects:
[]
4009 INFO: Warnings written to F:\ME\todo\LockerTODO\build\t\warn-t.txt
4057 INFO: Graph cross-reference written to F:\ME\todo\LockerTODO\build\t\xref-t.html
4089 INFO: checking PYZ
4089 INFO: Building PYZ because PYZ-00.toc is non existent
4093 INFO: Building PYZ (ZlibArchive) F:\ME\todo\LockerTODO\build\t\PYZ-00.pyz
4562 INFO: Building PYZ (ZlibArchive) F:\ME\todo\LockerTODO\build\t\PYZ-00.pyz completed successfully.
4574 INFO: checking PKG
4577 INFO: Building PKG because PKG-00.toc is non existent
4577 INFO: Building PKG (CArchive) PKG-00.pkg
4597 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
4597 INFO: Bootloader c:\program files (x86)\python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
4597 INFO: checking EXE
4606 INFO: Building EXE because EXE-00.toc is non existent
4606 INFO: Building EXE from EXE-00.toc
4609 INFO: Appending archive to EXE F:\ME\todo\LockerTODO\build\t\t.exe
4693 INFO: Building EXE from EXE-00.toc completed successfully.
4698 INFO: checking COLLECT
4698 INFO: Building COLLECT because COLLECT-00.toc is non existent
4698 INFO: Building COLLECT COLLECT-00.toc
6016 INFO: Building COLLECT COLLECT-00.toc completed successfully.

F:\ME\todo\LockerTODO>cd build

F:\ME\todo\LockerTODO\build>cd t

F:\ME\todo\LockerTODO\build\t>t
Error loading Python DLL 'F:\ME\todo\LockerTODO\build\t\python37.dll'.
LoadLibrary: 找不到指定的模块。

**Comment by Legorooj** [comment]
> @SolomonLeon please can you reproduce this issue with 3.7?

**Comment by SolomonLeon** [comment]
@Legorooj 

> @Legorooj
> Still can't work
> 
> > F:\ME\todo\LockerTODO>pyinstaller --clean t.py
> > 100 INFO: PyInstaller: 3.6
> > 100 INFO: **Python: 3.7.6**
> > 100 INFO: Platform: Windows-10-10.0.18362-SP0
> > 100 INFO: wrote F:\ME\todo\LockerTODO\t.spec
> > 103 INFO: UPX is not available.
> > 103 INFO: Removing temporary files and cleaning cache in C:\Users\Administrator\AppData\Roaming\pyinstaller
> > 140 INFO: Extending PYTHONPATH with paths
> > ['F:\ME\todo\LockerTODO', 'F:\ME\todo\LockerTODO']
> > 140 INFO: checking Analysis
> > 140 INFO: Building Analysis because Analysis-00.toc is non existent
> > 144 INFO: Initializing module dependency graph...
> > 148 INFO: Caching module graph hooks...
> > 160 INFO: Analyzing base_library.zip ...
> > 3100 INFO: Caching module dependency graph...
> > 3204 INFO: running Analysis Analysis-00.toc
> > 3208 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
> > required by c:\program files (x86)\python37-32\python.exe
> > 3511 INFO: Analyzing F:\ME\todo\LockerTODO\t.py
> > 3519 INFO: Processing module hooks...
> > 3519 INFO: Loading module hook "hook-encodings.py"...
> > 3622 INFO: Loading module hook "hook-pydoc.py"...
> > 3625 INFO: Loading module hook "hook-xml.py"...
> > 3866 INFO: Looking for ctypes DLLs
> > 3866 INFO: Analyzing run-time hooks ...
> > 3878 INFO: Looking for dynamic libraries
> > 4001 INFO: Looking for eggs
> > 4001 INFO: Using Python library c:\program files (x86)\python37-32\python37.dll
> > 4006 INFO: Found binding redirects:
> > []
> > 4009 INFO: Warnings written to F:\ME\todo\LockerTODO\build\t\warn-t.txt
> > 4057 INFO: Graph cross-reference written to F:\ME\todo\LockerTODO\build\t\xref-t.html
> > 4089 INFO: checking PYZ
> > 4089 INFO: Building PYZ because PYZ-00.toc is non existent
> > 4093 INFO: Building PYZ (ZlibArchive) F:\ME\todo\LockerTODO\build\t\PYZ-00.pyz
> > 4562 INFO: Building PYZ (ZlibArchive) F:\ME\todo\LockerTODO\build\t\PYZ-00.pyz completed successfully.
> > 4574 INFO: checking PKG
> > 4577 INFO: Building PKG because PKG-00.toc is non existent
> > 4577 INFO: Building PKG (CArchive) PKG-00.pkg
> > 4597 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
> > 4597 INFO: Bootloader c:\program files (x86)\python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
> > 4597 INFO: checking EXE
> > 4606 INFO: Building EXE because EXE-00.toc is non existent
> > 4606 INFO: Building EXE from EXE-00.toc
> > 4609 INFO: Appending archive to EXE F:\ME\todo\LockerTODO\build\t\t.exe
> > 4693 INFO: Building EXE from EXE-00.toc completed successfully.
> > 4698 INFO: checking COLLECT
> > 4698 INFO: Building COLLECT because COLLECT-00.toc is non existent
> > 4698 INFO: Building COLLECT COLLECT-00.toc
> > 6016 INFO: Building COLLECT COLLECT-00.toc completed successfully.
> 
> F:\ME\todo\LockerTODO>cd build
> 
> F:\ME\todo\LockerTODO\build>cd t
> 
> F:\ME\todo\LockerTODO\build\t>t
> Error loading Python DLL 'F:\ME\todo\LockerTODO\build\t\python37.dll'.
> LoadLibrary: 找不到指定的模块。

@Legorooj This is the result with python3.7.6

**Comment by Legorooj** [comment]
Sorry. The exe in the dist folder is the output. The build one never works.

**Comment by c896** [comment]
I also had the same problem ,have you finally solved it?

**Comment by Legorooj** [comment]
Please open a new issue if you're having this problem.
