### ISSUE TITLE
Error loading Python Lib, using pyinstaller on Mac OS

### ISSUE THREAD

**Issue by onej98** [pyinstaller/pyinstaller#4793]
Hello,

First off, I am fairly new to Python so please go easy on me.
I am trying to create a .app executable from my python script that uses PyQt5 and numpy.
I am using a MacBook running OSX Yosemite 10.10.5. I have Python 3.8.2 installed (terminal: python3) and Python 2.7.10 (terminal: python).
I pip installed pyinstaller and ran: " pyinstaller --onefile -w program.py
I get an app and executable file. When running the app file, it closes immediately. The terminal executable however shows this error:
![Screen Shot 2020-04-05 at 7 18 53 PM](https://user-images.githubusercontent.com/45119508/78517553-8932b400-7772-11ea-849a-8b3857085182.png)

I can see that it is not important a certain library but I am quite stuck and not sure how to fix this.
If anyone can help, I really appreciate it.

**Comment by Legorooj** [comment]
@onej98 Is your app python 3 or python 2? You don't actually specify. Also, did you install with `pip`, or `pip3`? Please post the output of `<pip-command-you-used> --version`. 

Also, python 3.8 won't be supported until next release.

**Comment by damufo** [comment]
Hello:
Same problem 
so: 10.15 catalina
python 3.8.2
pyinstaller: 3.6
installed in virtualenv with pipenv

[1613] Error loading Python lib '/Users/catalina/proba/dist/proba/Python': dlopen: dlopen(/Users/catalina/proba/dist/proba/Python, 10): no suitable image found.  Did find:
	/Users/catalina/proba/dist/proba/Python: code signature invalid for '/Users/catalina/proba/dist/proba/Python'

Please add support for python 3.8.
Very thanks.

**Comment by damufo** [comment]
Hello:
Hello:
Same in python 3.7
macos: 10.15 catalina
Python 3.7.7
Pyinstaller 3.6

(myapp) catalina@catalinas-iMac myapp % ./myapp 
[1159] PyInstaller Bootloader 3.x
[1159] LOADER: executable is /Users/catalina/myapp/dist_mac/myapp/myapp
[1159] LOADER: homepath is /Users/catalina/myapp/dist_mac/myapp
[1159] LOADER: _MEIPASS2 is NULL
[1159] LOADER: archivename is /Users/catalina/myapp/dist_mac/myapp/myapp
[1159] LOADER: No need to extract files to run; setting extractionpath to homepath
[1159] LOADER: Already in the child - running user's code.
[1159] LOADER: Python library: /Users/catalina/myapp/dist_mac/myapp/Python
[1159] Error loading Python lib '/Users/catalina/myapp/dist_mac/myapp/Python': dlopen: dlopen(/Users/catalina/myapp/dist_mac/myapp/Python, 10): no suitable image found.  Did find:
	/Users/catalina/myapp/dist_mac/myapp/Python: code signature invalid for '/Users/catalina/myapp/dist_mac/myapp/Python'

(myapp) catalina@catalinas-iMac myapp % python
Python 3.7.7 (v3.7.7:d7c567b08f, Mar 10 2020, 02:56:16) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by Legorooj** [comment]
@damufo PyInstaller generated a `build` folder. Inside it, there is a file `warn-***.txt`. Can you post the output?

**Comment by onej98** [comment]
> 
> 
> @onej98 Is your app python 3 or python 2? You don't actually specify. Also, did you install with `pip`, or `pip3`? Please post the output of `<pip-command-you-used> --version`.
> 
> Also, python 3.8 won't be supported until next release.

I used both pip and pip3 to install pyinstaller, pyqt5, and numpy

**Comment by Legorooj** [comment]
@onej98 can you install python 3.7 and use that instead? Python 3.8 isn't supported.

**Comment by onej98** [comment]
> @onej98 can you install python 3.7 and use that instead? Python 3.8 isn't supported.

Hi Legorooj,

In addition to updating to OS X 10.13.6, I installed Python 3.7.7
![Screen Shot 2020-04-08 at 7 39 11 AM](https://user-images.githubusercontent.com/45119508/78729281-44726d00-796c-11ea-8cd6-6024459ceb29.png)

and updated pip3
![Screen Shot 2020-04-08 at 7 38 53 AM](https://user-images.githubusercontent.com/45119508/78729294-49cfb780-796c-11ea-8574-5274805c2dec.png)

And I get a new error:
![Screen Shot 2020-04-08 at 7 38 15 AM](https://user-images.githubusercontent.com/45119508/78729311-518f5c00-796c-11ea-9408-ac847f162f0a.png)

I really appreciate your help!

**Comment by Legorooj** [comment]
@onej98 right. This *appears* to be related to code signing. Did you sign the executable?

**Comment by damufo** [comment]
Hello:
Uninstall python 3.8 and python 3.7.

Reinstall python with homebrew and python (3.7) is signed.
Now work fine.
Very thanks.

**Comment by harshithdwivedi** [comment]
I was facing the same issue and turns out that adding the -f flag while codesigning the app works in my case without having to reinstall python.

```
codesign -f -s "Certificate" dist/AfterShoot.app --deep
```
