### ISSUE TITLE
Pyinstaller not building applications

### ISSUE THREAD

**Issue by CyberDomeBlue** [pyinstaller/pyinstaller#4796]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: e.g. 3.7
* Platform: e.g GNU/Linux (distribution), Windows (language settings), OS X, conda, FreeBSD
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with celan installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```
Repeatedly created an application that is AES protected and base 64 encoded outside of native encryption support and even without and see repeated failures when running Pyinstaller when enabling debugging it keeps complaining about logging.cp347 unsure what this is but it has repeatedly caused issues with pyinstaller, cx-freeze, and py2exe. Even without anything crazy just a print hello world have seen this issue for multiple days now. When attempting to build a application. Running python version 3.7.2 and pyinstaller 3.6 have yet to get a working application since pyinstaller 3.6 was released and also keeps making files that are 15mb in size for something as simple as print hello world not sure what logic is going on but that is absurd.

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by CyberDomeBlue** [comment]
The program used was the following 

Import os 
Import time 
time.sleep(15) 
print(“hello world”)
time.sleep(15) 

Just to be sure was not my code and have yet to make a usable pyinstaller executable using that code as a script named test.py

**Comment by Legorooj** [comment]
@CyberDomeBlue please can you tell us how you built it? With the `--key` option?

**Comment by CyberDomeBlue** [comment]
Finally figured out the issue it’s related to importing impacket modules. When I took impacket out of the code it finally works. Seems to not like the from impacket import some module way down in the code. Can you test and see if you are able to reproduce by doing a file with impacket and doing import of dcerpc from impacket and see if it works. Once i removed that it seems to work finally. Even with my custom
Code protection script.

**Comment by CyberDomeBlue** [comment]
This was not done with - - key option but script run before pyinstaller that mangles functions, calls, and encrypts the code and provides a way to decrypt the code.

**Comment by dreamnyj** [comment]
Confusion, you can also try to use cyphon, translated into C, basically no one can understand.

**Comment by Legorooj** [comment]
@dreamnyj that's not relevant at the moment.

@CyberDomeBlue could you please provide an example? A script which raises the error, and instructions on how to reproduce this? I can't help otherwise.

**Comment by CyberDomeBlue** [comment]
https://github.com/SecureAuthCorp/impacket/blob/master/examples/getArch.py

Script was having issues with pyinstaller building while you can directly import impacket you can’t import individual items from it would seem like DCERPC which is needed for this script.

**Comment by CyberDomeBlue** [comment]
Example script only works with impacket installed

**Comment by Legorooj** [comment]
@CyberDomeBlue you need to write a hook file for `impacket`. See https://pyinstaller.readthedocs.io/en/stable/hooks.html for more information.
