### ISSUE TITLE
[windows] Generate feedback with PYD program showing R6034 C++ runtime error

### ISSUE THREAD

**Issue by dreamnyj** [pyinstaller/pyinstaller#4797]
Always using pyinstaller, we find that when we generate some PYD on windows platform, if we use-F to generate a separate run, the program will have the problem of not import ***.pyd.

Later, an attempt was made to generate one dir and it was found that if the <program name.manifest> generated was replaced.

Environmental：
125 INFO: PyInstaller: 3.5
125 INFO: Python: 3.4.3
125 INFO: Platform: Windows-XP-5.1.2600-SP3
125 INFO: UPX is not available.

VS 2005(8.0)OR VS2008 (9.0)

**Unusable manifest generated by pyinstaller：**
```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
<assemblyIdentity name="aliyun_load_d" processorArchitecture="x86" type="win32" version="1.0.0.0"/>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
    </application>
  </compatibility>
</assembly>
```

**The manifest that can be used after replacement：**

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1">
  <noInheritable/>

  <assemblyIdentity name="Microsoft.VC80.CRT" processorArchitecture="x86" publicKeyToken="1fc8b3b9a1e18e3b" type="win32" version="8.0.50727.6195"/>
  <file name="msvcr80.dll"/>
  <file name="msvcp80.dll"/>
  <file name="msvcm80.dll"/>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
 <application>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
    </application>
  </compatibility>
</assembly>
```

Test whether there is any manifest in the directory can be run without compiling to PYD.

If you have PYD, you must have these two manifest

I know that this problem may be more related to Python and the report may not be improved, but I love pyinstaller and hope my findings are useful.

Thanks to the developers of pyinstaller, your product has helped python, which is more environment dependent.

**Comment by Legorooj** [comment]
@dreamnyj this might be a bug. Can you provide an example - source code, not compiled PYDs - so I can try and reproduce?

**Comment by dreamnyj** [comment]
> @dreamnyj this might be a bug. Can you provide an example - source code, not compiled PYDs - so I can try and reproduce?

Because it's just a gadget that can provide exactly the same source code, whether to provide an email address, or how to provide it.

**Comment by dreamnyj** [comment]
The file has been sent to the mailbox.          legorooj@protonmail.com

**Comment by Legorooj** [comment]
@dreamnyj I've been unable to reproduce the problem, after many attempts. However, seeing some of the source code and build config, I can say that the MANIFEST errors are something to do with the DLLs you're using. 

However, a useful tip would be the `--manifest` option of PyInstaller - it allows you to add your own manifests.
