### ISSUE TITLE
EXE file will not run: ModuleNotFoundError: No module named 'pandas_datareader

### ISSUE THREAD

**Issue by mbucher28** [pyinstaller/pyinstaller#4798]
I got this same error with pandas and I pip installed pandas before creating the exe file with pyinstaller and that seemed to work. Tried the same thing with  pandas datareader and the exe file still will not run. Says, "ModuleNotFoundError: No module named 'pandas_datareader [2368] Failed to execute script"

**Comment by Legorooj** [comment]
@mbucher28 please provide some actual information. What's the *full* traceback? Can you provide us with source code?

**Comment by mbucher28** [comment]
It is working now, I installed data_reader from Anaconda. I think initially I was using a different version of Python that I had downloaded. Thanks!
