### ISSUE TITLE
Why pyinstaller breaks appium code when making executables?

### ISSUE THREAD

**Issue by Karraya** [pyinstaller/pyinstaller#4802]
So when I run my code from the commandline everything work as expected. It when I try to make the .exe file using:

Pyinstaller -w -F mypythoncode.py

The GUI shows up as expected but the code breaks on this line.

Service = AppiumService ()

Service.start() # The code breaks here. Any idea???

Code ...

Service.stop()

**Comment by Legorooj** [comment]
@Karraya you'll have to debug this yourself; we don't have the time. You'll need to look inside the `Service.start` method and see what it's doing, and figure out the cause.
