### ISSUE TITLE
Commit 042d21cec6 cause ValueError

### ISSUE THREAD

**Issue by azuwis** [pyinstaller/pyinstaller#4807]
# Description of the issue

After commit 042d21cec6, pyinstaller give error message `ValueError: Can't mix absolute and relative paths`, even if run against non-existing py files.

Version f877f3eb8a(previous commit of 042d21cec6) works fine.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0.dev0+042d21cec6```
* Version of Python: 3.8.2
* Platform: GNU/Linux
* Did you also try this on another platform? Does it work there?

Tried on Windows 10 python 3.7.7, same error.

* try the latest development version, using the following command:

Latest development version give same error.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with celan installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
$ python3 -m venv /tmp/test
$ source /tmp/test/bin/activate
$ pip3 install https://github.com/pyinstaller/pyinstaller/tarball/042d21cec66308f39ef530bf0e6dbd5de3fa442c
$ pyinstaller non-existing.py
```

### Stacktrace / full error message

```
34 INFO: PyInstaller: 4.0.dev0+042d21cec6
35 INFO: Python: 3.8.2
44 INFO: Platform: Linux-5.4.0-4-amd64-x86_64-with-glibc2.29
Traceback (most recent call last):
  File "/tmp/test/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/tmp/test/lib/python3.8/site-packages/PyInstaller/__main__.py", line 112, in run
    spec_file = run_makespec(**vars(args))
  File "/tmp/test/lib/python3.8/site-packages/PyInstaller/__main__.py", line 58, in run_makespec
    spec_file = PyInstaller.building.makespec.main(filenames, **opts)
  File "/tmp/test/lib/python3.8/site-packages/PyInstaller/building/makespec.py", line 463, in main
    specfile.write(onedirtmplt % d)
  File "/tmp/test/lib/python3.8/site-packages/PyInstaller/building/makespec.py", line 101, in __repr__
    self.variable_prefix, self.filename_suffix = make_variable_path(self.path)
  File "/tmp/test/lib/python3.8/site-packages/PyInstaller/building/makespec.py", line 84, in make_variable_path
    if os.path.commonpath([filename, from_path]) == from_path:
  File "/usr/lib/python3.8/posixpath.py", line 510, in commonpath
    raise ValueError("Can't mix absolute and relative paths") from None
ValueError: Can't mix absolute and relative paths
```

**Comment by Legorooj** [comment]
Thanks for reporting this bug. I'll fix this in a day or two.

Also, python 3.8 isn't yet supported.

**Comment by Legorooj** [comment]
@htgoebel can I have your input here? My thoughts are just use absolute paths; but the comments in the code say it's intentionally not doing that.

**Comment by htgoebel** [comment]
Only one of the paths has been absolute, `filename` was not.

@Legorooj In these cases I run `python -m pdb bin/pyinstaller …` to get to the place quickly.

**Comment by htgoebel** [comment]
@azuwis Thansk for reporting and for the good report. This was easy to reproduce :-)

**Comment by Legorooj** [comment]
@htgoebel I generally prefer the PyCharm debugger, but it's harder to debug things like that (something that's not `__name__ == '__main__'` for the script your debugging). I'll give PBD a go.

I thought `filename` might be the problem.
