### ISSUE TITLE
pyinstaller with matlab : ImportError No module named 'mlarray'

### ISSUE THREAD

**Issue by tingfenghanlei** [pyinstaller/pyinstaller#4814]
I am trying to package my script with pyinstaller. My script interacts with matlab, so matlab python API is imported. I got below error when i run the executable file. 
You can see the error in this fig. 
https://i.stack.imgur.com/bVIMJ.jpg

**Comment by Legorooj** [comment]
@tingfenghanlei please write a hook for matlab: https://pyinstaller.readthedocs.io/en/stable/hooks.html

Once you've got it working, submit a PR to https://github.com/pyinstaller/pyinstaller-hooks-contrib so other users can use it.
