### ISSUE TITLE
No support for twisted and yield

### ISSUE THREAD

**Issue by OceanFireSoftware** [pyinstaller/pyinstaller#4815]
## Description of the issue

Pyinstaller .exe file can't run with scrapy and yield

## Context information (for bug reports)

Output of `pyinstaller --version`: >= 3.6
Version of Python:  3.7
Platform: Windows

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "site-packages\twisted\internet\defer.py", line 1418, in _inlineCallbacks
  File "site-packages\scrapy\core\downloader\middleware.py", line 42, in process_request
  File "site-packages\twisted\internet\defer.py", line 1362, in returnValue
twisted.internet.defer._DefGen_Return: <200 https://www..... rest of domain>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages\scrapy\utils\defer.py", line 55, in mustbe_deferred
  File "site-packages\scrapy\core\spidermw.py", line 60, in process_spider_input
  File "site-packages\scrapy\core\scraper.py", line 148, in call_spider
  File "site-packages\scrapy\utils\misc.py", line 202, in warn_on_generator_with_return_value
  File "site-packages\scrapy\utils\misc.py", line 187, in is_generator_with_return_value
  File "inspect.py", line 973, in getsource
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code
```

When I remove yield everything works correctly

**Comment by Legorooj** [comment]
What do you mean, when you remove yieldm

**Comment by OceanFireSoftware** [comment]
I replace yield with return

**Comment by Legorooj** [comment]
That will break stuff. Replace it where? Which file? In scrapy? twisted?

**Comment by OceanFireSoftware** [comment]
I simply replaced yield with return in my Scrapy project. It didn't break anything because I knew what I did (scrapy allows use return).

I mean, when trying to create an exe file with a normal scrapy project, pyinstaller interprets yield inconsistently within the twisted library on which scrapy is based.

I think this is due to bad generator support.

**Comment by Legorooj** [comment]
@OceanFireSoftware PyInstaller uses standard python. Anything supported in python's standard syntax is supported. Generators are fully supported, with no bugs. Can I please have some source code? The version that broke *and* the version that didn't. I'm willing to bet this is hook related - ie pyinstaller isn't being told how to bundle twisted properly.

**Comment by Legorooj** [comment]
@OceanFireSoftware?

**Comment by Panexis** [comment]
I have the same issue on my project, yield is not working with the .exe but if I change yield to return it works but doesn´t complete the loop so useless... any idea how to fix this?

**Comment by Legorooj** [comment]
@Panexis I've figured this out - well the problem, not a fix. PyInstaller doesn't include the source code, and scrapy is trying to find it, raising an `OSError` via the `inspect` module. A basic fix (it's very hacky atm) can be found in #4764. A pull request with the changes would be nice.

And if there's a `yeild` statement, don't _**ever**_ replace it with `return`. They do entirely different things.

**Comment by OceanFireSoftware** [comment]
I'm sorry for the lack of response. I will insert the error log tomorrow

**Comment by OceanFireSoftware** [comment]
@Legorooj I'm sorry for the lack of response. I will insert the error log tomorrow

**Comment by Panexis** [comment]
@Legorooj thanks!!! following #4764.

**Comment by DCNick3** [comment]
This monkeypatch can be used as an easier workaround

```
import scrapy.utils.misc
import scrapy.core.scraper

def warn_on_generator_with_return_value_stub(spider, callable):
    pass

scrapy.utils.misc.warn_on_generator_with_return_value = warn_on_generator_with_return_value_stub
scrapy.core.scraper.warn_on_generator_with_return_value = warn_on_generator_with_return_value_stub
```
