### ISSUE TITLE
Where does pyinstaller install custom python packages when I use python from executable?

### ISSUE THREAD

**Issue by ptrivedi2610** [pyinstaller/pyinstaller#4816]
Hi @Legorooj 

I have created dist/ folder on Windows, using pyinstaller. Python3.7 is bundled inside dist/.
Now I am taking this dist/ folder in separate machine where no Python in installed.

I have my custom python package PKG, inside dist/ which I need to install in the system using executable, using "python setup.py install --user".

When I run my executable, it shows the package is installed successfully.
My question is, normally in a machine where Python is installed, such packages goes to "site-packages"
But in my case, where would the package have been installed ?

**Comment by Legorooj** [comment]
Into the internal PYZ of libraries.

**Comment by ptrivedi2610** [comment]
@Legorooj So runtime what path shall I give to fetch the installed package that was installed using executable ?

**Comment by Legorooj** [comment]
@ptrivedi2610 what do you mean? If you wan't the source code of the installed package - as `.py` files, that's not possible - without what is currently a hack, but may soon be a supported feature. We only store bytecode currently, inside the executable.

**Comment by ptrivedi2610** [comment]
@Legorooj 
Thanks for the info and help. 
Summarizing my scenario again
1. I have my custom package X, with its own setup.py file
2. I have a file script.py, which internally installs this package X into my system
3. I am creating installer out of script.py (let's say script.exe)
4. I am running script.exe on machine having python. It installs package X into site-packages/
5. Now I am taking same script.exe on machine with no python installed. When I execute script.exe, it says package X is installed successfully. 
But since there is no python on the system, hence no site-packages, so where will package X be installed ?

The requirement is I need to fetch where package X is installed and get it's path

**Comment by Legorooj** [comment]
Umm... `import X; X.__file__`? That should return the code.
