### ISSUE TITLE
App gives PermissionDenied when launched on a different machine wrt the build one

### ISSUE THREAD

**Issue by cttlfsh** [pyinstaller/pyinstaller#4817]
I am trying to build a python app with pyinstaller. Everything goes fine, the build is successfull and I am able to run it on my machine, but when I try to give the app to a friend to test it it gives `permission denied` when launched.

Anyone knows how to fix this problem? Am I missing something in the build command?

The command I use is:

`pyinstaller --onefile --windowed --add-data "data1:data1" --add-data "data2:data2" --hidden-import=hi app.py`

**Comment by Legorooj** [comment]
Which platform are you using?

**Comment by cttlfsh** [comment]
My Apoogize, both systems are macOS Mojave v10.14.6

**Comment by Legorooj** [comment]
@cttlfsh and the exact error?

**Comment by cttlfsh** [comment]
it is not properly an error. It gives Permission Denied and does not let me run the executable. I tried with `sudo` and also to temporary modify system preferences, but still gives permission denied. Only when launched in a computer different than the one where it was built

**Comment by Legorooj** [comment]
@cttlfsh have you codesigned the executable?

**Comment by cttlfsh** [comment]
nope

**Comment by Legorooj** [comment]
Have you tried codesigning it? macOS is flighty with permissions for non-codesigned apps

**Comment by cttlfsh** [comment]
I tried code sign the project. Since I have both the `.app` and the executable I codesigned both. The `.app` works almost fine but gives some errors relative to Flask (which are not related) but the executable gives always permission denied

**Comment by Legorooj** [comment]
Hmmm. I don't have a mac. Maybe @micahflee if you've a few minutes to look at this?

**Comment by cttlfsh** [comment]
I actually solved it, just a few minutes age. I did not know that sending the executable directly without zipping it does some kind of damage to it.

Zipping the executable and then sending it worked perfectly. Now everything runs.
Thank you again very much for the quick responses

**Comment by ruslanways** [comment]
I have same problem..
But when I try to send My.app to another Mac - it zips itself automatically. As a result - same problem occurred once run unzipped app on another Mac - permission denied. 
Someone solves?

**Comment by bwoodsend** [comment]
Does opening it via right-click -> open work? Unless you've codesigned your application, it's normal for macOS to refuse to run anything unless it was built on your own machine.

**Comment by ruslanways** [comment]
> Does opening it via right-click -> open work? Unless you've codesigned your application, it's normal for macOS to refuse to run anything unless it was built on your own machine. 

No. Neither Control+right-click -> open doesn't work. ☹️

**Comment by bwoodsend** [comment]
If you zip then unzip on the same mac, what happens?

**Comment by ruslanways** [comment]
> If you zip then unzip on the same mac, what happens?

In that case all works perfect.

**Comment by bwoodsend** [comment]
Ok, so zip/unzip is most likely to be a red herring. How do you know it's a permission error? What does the error output/stacktrace look like?

**Comment by rokm** [comment]
Has the OS flagged your app with quarantine flag?

You can check by running `xattr -r program.app/` and see if the output is `com.apple.quarantine`.

And you can recursively remove the flag by running `xattr -r -d com.apple.quarantine program.app/`

**Comment by dropcunt** [comment]
i'm having the same issue with a Pyinstaller app. It seems to be a permission denied error in Notify.app/Contents/MacOS/ whenever i try to write something there. Did anyone find a workaround?

**Comment by rokm** [comment]
> i'm having the same issue with a Pyinstaller app. It seems to be a permission denied error in Notify.app/Contents/MacOS/ whenever i try to write something there. Did anyone find a workaround?

You cannot write into app bundle, because when you run it, the OS translocates it to a read-only location as a security measure. Signed apps might not be subject to this, but writing to app bundle should be avoided nevertheless.

**Comment by dropcunt** [comment]
ok i see thank you for your answer! Sorry i'm new with macOS development what is the standard practice in macOS for writing log files?  Would you write in /Users/User/Applications folder?

**Comment by rokm** [comment]
> Would you write in /Users/User/Applications folder?

According to [`appdirs`](https://pypi.org/project/appdirs/), the persistent application data (settings, logs, etc.) should go into `/Users/user/Library/Application Support/<AppName>`. If you are developing a cross-platform application, I suggest you use `appdirs` or equivalent for handling user data directories abstraction.
