### ISSUE TITLE
Missing exception log data when using pyinstaller and loguru

### ISSUE THREAD

**Issue by jacobthetechy** [pyinstaller/pyinstaller#4826]
## Description of the issue

I'm using loguru in one of my projects while using pyinstaller to create an EXE to run it on several Windows machines. I noticed some log data missing from exceptions when running the EXE. Here is an example of what I'm seeing.

```python 
# test.py

from loguru import logger

logger.add('test.log')

def div(n, d):
    try:
        return n / d
    except Exception as e:
        logger.exception(e)

div(2, 0)
```

When running this from the terminal it will produce this log file as expected. `python test.py`

```log
2020-04-20 12:46:32.123 | ERROR    | __main__:div:9 - division by zero
Traceback (most recent call last):

  File "test.py", line 11, in <module>
    div(2, 0)
    └ <function div at 0x7f81f5ee43b0>

> File "test.py", line 7, in div
    return n / d
           │   └ 0
           └ 2

ZeroDivisionError: division by zero
```

But once you use pyinstaller (`pyinstaller test.py`) and run the resulting EXE this is what is in the log file.

```log
2020-04-20 12:45:19.427 | ERROR    | __main__:div:9 - division by zero
Traceback (most recent call last):

  File "test.py", line 11, in <module>

> File "test.py", line 7, in div

ZeroDivisionError: division by zero
```

I have been able to reproduce this with python 3.8 & 3.7 on Windows 10 and python 3.7 on Fedora 30 using loguru==0.4.1 & PyInstaller==3.6

[https://github.com/Delgan/loguru/issues/250](https://github.com/Delgan/loguru/issues/250)

**Comment by Legorooj** [comment]
Huh? This shouldn't be happening. What's wrong with the except clause? Can you try `except ZeroDivisionError as e` instead?

**Comment by Delgan** [comment]
Hi @Legorooj.

I don' know if you have read the comment I left on Delgan/loguru#250, but I noticed the script only works correctly if it is executed from the same place where it was compiled.

I'm using `traceback.print_exc()` instead of `loguru` for the demonstration:

```python
import traceback

def div(n, d):
    try:
        return n / d
    except ZeroDivisionError as e:
        traceback.print_exc()

div(2, 0)
```
While running `./test` from within the generated `dist` folder:
```bash
Traceback (most recent call last):
  File "test.py", line 5, in div
ZeroDivisionError: division by zero
```
While running `./dist/test` from the parent folder:
```
Traceback (most recent call last):
  File "test.py", line 5, in div
    return n / d
ZeroDivisionError: division by zero
```
I thought this was related to [`linecache.getline()`](https://docs.python.org/fr/3/library/linecache.html#linecache.getline) maybe?

**Comment by Legorooj** [comment]
@Delgan you're probably right. PyInstaller doesn't bundle plain `.py` files, it bundles `.pyc` files which it compiles itself using the std library. So when you're running `./dist/test` it's finding the source code file - `test.py` - because the interpreter is told that that is the file it's running. 

How to work around this... You'd have to extract the full traceback info from the `e` object. 

(Note: `traceback.print_exc()` will work with just plain `except ERRORTYPE:`. It reads from the underlying stack, so you'd just need to get to it before the garbage collecter does.)

**Comment by Delgan** [comment]
The thing is that both `loguru.exception()` and `traceback.print_exc()` already extract the full traceback. The frames thus retrieved contain references to filename, lineno and function, but to access the line of code, we need to use `linecache.getline()`: [cpython/traceback.py#L285-L289](https://github.com/python/cpython/blob/bcc136ba892e62078a67ad0ca0b34072ec9c88aa/Lib/traceback.py#L285-L289)

It makes sense that `pyinstaller` does not bundle actual source code, but I'm not sure there is any possible workaround. This must be a "drawback" of `pyinstaller`, right?

**Comment by Legorooj** [comment]
@Delgan yes, but there's few occasions that this can't be worked around. The traceback still includes the line number, after all. You could, if it's an open source project, bundle the source with `--add-data=test.py;.` which would include the plain source in a findable location. But in commercial programs, this isn't desirable. I'm going to have to close this issue, seeing as we can't work on this.

(PS: Loguru is quite a nice peice of code. +:star:)

**Comment by Delgan** [comment]
Actually, `--add-data` **is** the kind of workaround I expected! Sorry, I was not aware of this parameter, I just tried to help @jacobthetechy with the issue he faced.

Thanks for your help, and kudos to all the team for `pyinstaller`. :+1:

**Comment by jacobthetechy** [comment]
Y'all are awesome. Thankfully there is no issue with me using `--add-data` to include the source files. After testing, this solution worked for me! 

@Legorooj for anyone else coming across this in the future, would adding the `--key=` flag also encrypt the files under `--add-data` or does it only encrypt the `.pyc` files? Could that be an added feature to help with this work around?

**Comment by Legorooj** [comment]
@jacobthetechy no, `--key` wouldn't include the data files in encryption. Is this program commercial? (IE closed source?)

**Comment by jacobthetechy** [comment]
No, it will be internal use only. I was more or less asking out of curiosity and clarification because I just stumbled upon that feature.

**Comment by Legorooj** [comment]
@jacobthetechy then including the source should be fine. `--key` is more of a difficulty layer; the key is extractable from the bytecode. It's possible to circumvent it (with what would be ease to a hacker). Just a note: if you want a closed source app, that the source can't be extracted from, use Cython to create an extension.

**Comment by zhfkt** [comment]
> @Delgan yes, but there's few occasions that this can't be worked around. The traceback still includes the line number, after all. You could, if it's an open source project, bundle the source with `--add-data=test.py;.` which would include the plain source in a findable location. But in commercial programs, this isn't desirable. I'm going to have to close this issue, seeing as we can't work on this.
> 
> (PS: Loguru is quite a nice peice of code. +⭐)

This solution seems not sensible for me because I have more than 200+ python files. It is not possible to carry 200 source files which just to support printing loguru in details

**Comment by Legorooj** [comment]
It's also the only solution, really. Loguru pulls the details from the source files so if there are no source files there are no details.
