### ISSUE TITLE
The ‘humanize’ distribution was not found and is required by the application

### ISSUE THREAD

**Issue by pengyanbing84** [pyinstaller/pyinstaller#4833]
The ‘humanize’ distribution was not found and is required by the application
Pyinstaller == 3.6 
humanize == 2.4
Please answer my question, thanks
python3.7

**Comment by Legorooj** [comment]
Which repo is humanize? What's the full traceback?

**Comment by pengyanbing84** [comment]
![snipaste20200424_102732](https://user-images.githubusercontent.com/34937085/80183145-e36cb980-863a-11ea-9ddf-fc0704d47850.png)

How can I solve this problem?

**Comment by pengyanbing84** [comment]
![snipaste20200424_102732](https://user-images.githubusercontent.com/34937085/80183272-1c0c9300-863b-11ea-9af2-a964b721e21b.png)


How can I solve this problem?

**Comment by Legorooj** [comment]
@pengyanbing84 you need to write a hook for pyinstaller. See https://pyinstaller.readthedocs.io/en/stable/hooks.html

**Comment by pengyanbing84** [comment]
> @ pengyanbing84，您需要为pyinstaller编写一个钩子。参见https://pyinstaller.readthedocs.io/en/stable/hooks.html

Hello, I am using pyinstaller for the first time, how to construct hooks, there are examples? Can you give me an example, thank you, thank you very much, for my hook example of this question. Thank you very much

**Comment by Legorooj** [comment]
```
- myprogram.py
- hooks
  - hook-humanize.py
```
And inside `hook-humanize.py`:
```
from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = collect_all('humanize')
```
Then build with `--additional-hooks-dir=hooks`.

**Comment by pengyanbing84** [comment]
> ```
> - myprogram.py
> - hooks
>   - hook-humanize.py
> ```
> 
> And inside `hook-humanize.py`:
> 
> ```
> from PyInstaller.utils.hooks import collect_all
> 
> datas, binaries, hiddenimports = collect_all('humanize')
> ```
> 
> Then build with `--additional-hooks-dir=hooks`.



> ```
> - myprogram.py
> - hooks
>   - hook-humanize.py
> ```
> 
> And inside `hook-humanize.py`:
> 
> ```
> from PyInstaller.utils.hooks import collect_all
> 
> datas, binaries, hiddenimports = collect_all('humanize')
> ```
> 
> Then build with `--additional-hooks-dir=hooks`.

Thank you very much

**Comment by Legorooj** [comment]
@pengyanbing84 did it work?

**Comment by abmaymic** [comment]
same problem here, hook did work. Many thanks!
