### ISSUE TITLE
[46518] Error loading Python lib

### ISSUE THREAD

**Issue by salarsf** [pyinstaller/pyinstaller#4841]
Hii

I upgraded to python 3.8.2 from 3.7.4 and now when I run a exec file (which is exported from pycharm using pyinstaller 3.6) I get this error in Terminal:

[46518] Error loading Python lib '/var/folders/gk/38xsfm3j3yv9wslgvcz2s2hh0000gn/T/_MEIjH4hjc/Python': dlopen: dlopen(/var/folders/gk/38xsfm3j3yv9wslgvcz2s2hh0000gn/T/_MEIjH4hjc/Python, 10): no suitable image found.  Did find:
	/var/folders/gk/38xsfm3j3yv9wslgvcz2s2hh0000gn/T/_MEIjH4hjc/Python: code signature invalid for '/var/folders/gk/38xsfm3j3yv9wslgvcz2s2hh0000gn/T/_MEIjH4hjc/Python'

HELP ME PLEASEEEE

**Comment by Legorooj** [comment]
@salarsf python 3.8 is unsupported. It won't be for a few months.

**Comment by salarsf** [comment]
> @salarsf python 3.8 is unsupported. It won't be for a few months.

Thanks for your reply. But I tested using python 3.7 and this error came up:



Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 30, in <module>
FileNotFoundError: Tcl data directory "/var/folders/gk/38xsfm3j3yv9wslgvcz2s2hh0000gn/T/_MEIxaV3p9/tcl" not found.
[16121] Failed to execute script pyi_rth__tkinter
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

**Comment by Legorooj** [comment]
That's really odd. Tkinter shouldn't be having problems. Can you try a fresh environment? New venv/conda-env, with `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip` instead?

**Comment by salarsf** [comment]
> pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip

Using python 3.7 (conda), the .app file opens and then closes immediately but exec file inside /myapp.app/Contents/MacOS works

**Comment by salarsf** [comment]
> That's really odd. Tkinter shouldn't be having problems. Can you try a fresh environment? New venv/conda-env, with `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip` instead?

Using python 3.7 (conda), the .app file opens and then closes immediately but exec file inside /myapp.app/Contents/MacOS works

**Comment by Legorooj** [comment]
Can you build without windowed mode? Eg don't use `-w/--windowed/--noconsole`, before opening a terminal, and running the application from it?

**Comment by salarsf** [comment]
> Can you build without windowed mode? Eg don't use `-w/--windowed/--noconsole`, before opening a terminal, and running the application from it?

Tried that. Didn't work neither. 
These are the messages while creating the file:



(venv) salkhashs-MBP:untitled salkhash$ pyinstaller --onefile py37.py
769 INFO: PyInstaller: 3.6
769 INFO: Python: 3.7.4
868 INFO: Platform: Darwin-16.7.0-x86_64-i386-64bit
891 INFO: wrote /Users/salkhash/Documents/My Programs/untitled/py37.spec
935 INFO: UPX is not available.
938 INFO: Extending PYTHONPATH with paths
['/Users/salkhash/Documents/My Programs/untitled',
 '/Users/salkhash/Documents/My Programs/untitled']
939 INFO: checking Analysis
939 INFO: Building Analysis because Analysis-00.toc is non existent
939 INFO: Initializing module dependency graph...
992 INFO: Caching module graph hooks...
1073 INFO: Analyzing base_library.zip ...
7614 INFO: Caching module dependency graph...
7851 INFO: running Analysis Analysis-00.toc
7922 INFO: Analyzing /Users/salkhash/Documents/My Programs/untitled/py37.py
8316 INFO: Processing module hooks...
8316 INFO: Loading module hook "hook-_tkinter.py"...
8380 ERROR: Tcl/Tk improperly installed on this system.
8381 INFO: Loading module hook "hook-encodings.py"...
8542 INFO: Loading module hook "hook-pydoc.py"...
8565 INFO: Loading module hook "hook-sqlite3.py"...
8782 INFO: Loading module hook "hook-xml.py"...
9286 INFO: Looking for ctypes DLLs
9287 INFO: Analyzing run-time hooks ...
9290 INFO: Including run-time hook 'pyi_rth__tkinter.py'
9311 INFO: Looking for dynamic libraries
10204 INFO: Looking for eggs
10204 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.7/Python
10208 INFO: Warnings written to /Users/salkhash/Documents/My Programs/untitled/build/py37/warn-py37.txt
10260 INFO: Graph cross-reference written to /Users/salkhash/Documents/My Programs/untitled/build/py37/xref-py37.html
10312 INFO: checking PYZ
10319 INFO: Building PYZ because PYZ-00.toc is non existent
10319 INFO: Building PYZ (ZlibArchive) /Users/salkhash/Documents/My Programs/untitled/build/py37/PYZ-00.pyz
10885 INFO: Building PYZ (ZlibArchive) /Users/salkhash/Documents/My Programs/untitled/build/py37/PYZ-00.pyz completed successfully.
10894 INFO: checking PKG
10894 INFO: Building PKG because PKG-00.toc is non existent
10894 INFO: Building PKG (CArchive) PKG-00.pkg
17341 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
17347 INFO: Bootloader /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
17348 INFO: checking EXE
17348 INFO: Building EXE because EXE-00.toc is non existent
17348 INFO: Building EXE from EXE-00.toc
17348 INFO: Appending archive to EXE /Users/salkhash/Documents/My Programs/untitled/dist/py37
17516 INFO: Fixing EXE for code signing /Users/salkhash/Documents/My Programs/untitled/dist/py37
17549 INFO: Building EXE from EXE-00.toc completed successfully.



And this is the error I get when I open the exec file:

Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 30, in <module>
FileNotFoundError: Tcl data directory "/var/folders/gk/38xsfm3j3yv9wslgvcz2s2hh0000gn/T/_MEIbtwXtQ/tcl" not found.
[47273] Failed to execute script pyi_rth__tkinter
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.
Deleting expired sessions...none found.


And this one is the warn txt:
[warn-py37.txt](https://github.com/pyinstaller/pyinstaller/files/4550693/warn-py37.txt)

**Comment by Legorooj** [comment]
> 8380 ERROR: Tcl/Tk improperly installed on this system.

How did you install python?

**Comment by salarsf** [comment]
> > 8380 ERROR: Tcl/Tk improperly installed on this system.
> 
> How did you install python?

I installed the official 2.7.4 version for mac from python.org

**Comment by Legorooj** [comment]
@salarsf could you try python 3.7? Or does your app not support python 3?

**Comment by salarsf** [comment]
> @salarsf could you try python 3.7? Or does your app not support python 3?

Sorry I ment 3.7.4

**Comment by Legorooj** [comment]
@salarsf well TK wasn't installed properly. So you need to fix that; it's not a PyInstaller error. And I can't help because I'm not a Mac developer - nor do I own a Mac.

**Comment by salarsf** [comment]
> @salarsf well TK wasn't installed properly. So you need to fix that; it's not a PyInstaller error. And I can't help because I'm not a Mac developer - nor do I own a Mac.

Thanks a lot for your time. But I have no problem using py2app. If it was a problem with the system, shouldnt I faced the same problem using py2app?

**Comment by Legorooj** [comment]
@salarsf I don't know. I'm not a Mac developer, and don't understand. However, I just found #3753 and a specific comment that should fix your solution at https://github.com/pyinstaller/pyinstaller/issues/3753#issuecomment-432464838
