### ISSUE TITLE
Mac OS Catalina App launch too slow

### ISSUE THREAD

**Issue by JoeSuen** [pyinstaller/pyinstaller#4843]
Hi.
I use pyinstaller for packing pyqt app. The app launch too slow(almost 20s) after I update to Catalina. Before updating the app launch within 2s. I don't know if it is common problem or I missing some config. If you have any idea, please let me know. Thx

**Comment by JoeSuen** [comment]
I have just found out changing -F to -D making launch speed fast as normal, so it may be the one file problem.

**Comment by Legorooj** [comment]
@JoeSuen we can't help with app launch speeds. Everything is as optimised as we can make it for now. 

> I have just found out changing -F to -D making launch speed fast as normal, so it may be the one file problem.

That will always help with launch speed; when using `-F` the executable has to decompress all of your code before it can run.

**Comment by cculianu** [comment]
Catalina runs a security check on the extracted app that's placed in the tmp folder.  If you disable internet it launches instantly. With internet enabled it has to "phone home" to Apple to get approval to run the bundled app.

What does -F vs -D do?

**Comment by Legorooj** [comment]
@cculianu `-F/--onefile` `-D/--onedir`
