### ISSUE TITLE
Unable to find 'C:\Users\user\nltk_data'

### ISSUE THREAD

**Issue by donquibeats** [pyinstaller/pyinstaller#4844]
It appears that this old bug report: [https://github.com/pyinstaller/pyinstaller/issues/3799](https://github.com/pyinstaller/pyinstaller/issues/3799) might have been closed without being resolved?

When running PyInstaller 3.6 on Windows via PyCharm, this error is still being thrown:
`25602 INFO: Loading module hook "hook-nltk.py"...
Unable to find "C:\Users\[user name]\nltk_data" when adding binary and data files.`

Please let me know whether I can provide more information that would help fix the issue.

**Comment by Legorooj** [comment]
@donquibeats this issue had been resolved in the development version. We haven't released it yet.
