### ISSUE TITLE
Cannot install pyinstaller with pip

### ISSUE THREAD

**Issue by EdwardChamberlain** [pyinstaller/pyinstaller#4845]
## Description of the issue
pip hangs during install of pyionstaller: 
```(gcode-venv) PS path> pip install pyinstaller
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz
  Installing build dependencies ... /
```

It hangs here indefinetly (tested for 6 hours.)

## Context information (for bug reports)

* Output of `pyinstaller --version`: 
```pyinstaller : The term 'pyinstaller' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.```
* Version of Python: 
3.7 (windows store)
* Platform: 
Windows 10 (1903), 
* Did you also try this on another platform? Does it work there?
Works fine on my linux install. 

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Same issue

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

**Comment by Legorooj** [comment]
@EdwardChamberlain when it freezes, is the window title something like `Select command prompt...`? If so, select the window and press space.

**Comment by EdwardChamberlain** [comment]
@Legorooj I am using the powershell from VSCode but the issue is the same on stand alone powershell. The full powershell output is:

```PS C:\Users\Ed> pip3 install pyinstaller
Collecting pyinstaller
  Downloading https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz (3.5MB)
     |████████████████████████████████| 3.5MB 3.3MB/s
  Installing build dependencies ... -
```

or running in VSCode (also in a venv):

```
(gcode-venv) PS D:\User Area\Documents\GitHub\GCODE-Arc-Converter-1> pip3 install pyinstaller
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz
  Installing build dependencies ... /
```
This has been sat on this step for 3 Days now.

**Comment by EdwardChamberlain** [comment]
When I cancel the operation with a keyboard interrupt (I have to do it twice) I get this error: 

```
(gcode-venv) PS D:\User Area\Documents\GitHub\GCODE-Arc-Converter-1> pip3 install pyinstaller
Collecting pyinstaller
  Using cached https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz
  Installing build dependencies ... canceled
ERROR: Operation cancelled by user
Traceback (most recent call last):
  File "d:\user area\documents\github\gcode-arc-converter-1\venv\gcode-venv\lib\site-packages\pip\_vendor\lockfile\linklockfile.py", line 31, in acquire
    os.link(self.unique_name, self.lock_file)
OSError: [WinError 17] The system cannot move the file to a different disk drive: 'C:\\Users\\Ed\\AppData\\Local\\pip\\Cache\\DESKTOP-N34EJRE-2310.30008-33659502938547267' -> 'C:\\Users\\Ed\\AppData\\Local\\pip\\Cache\\selfcheck.json.lock'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.2032.0_x64__qbz5n2kfra8p0\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\User Area\Documents\GitHub\GCODE-Arc-Converter-1\venv\gcode-venv\Scripts\pip3.exe\__main__.py", line 9, in <module>
  File "d:\user area\documents\github\gcode-arc-converter-1\venv\gcode-venv\lib\site-packages\pip\_internal\__init__.py", line 77, in main
    return command.main(cmd_args)
  File "d:\user area\documents\github\gcode-arc-converter-1\venv\gcode-venv\lib\site-packages\pip\_internal\cli\base_command.py", line 240, in main
    pip_version_check(session, options)
  File "d:\user area\documents\github\gcode-arc-converter-1\venv\gcode-venv\lib\site-packages\pip\_internal\utils\outdated.py", line 148, in pip_version_check
    state.save(pypi_version, current_time)
  File "d:\user area\documents\github\gcode-arc-converter-1\venv\gcode-venv\lib\site-packages\pip\_internal\utils\outdated.py", line 65, in save
    with lockfile.LockFile(self.statefile_path):
  File "d:\user area\documents\github\gcode-arc-converter-1\venv\gcode-venv\lib\site-packages\pip\_vendor\lockfile\__init__.py", line 197, in __enter__
    self.acquire()
  File "d:\user area\documents\github\gcode-arc-converter-1\venv\gcode-venv\lib\site-packages\pip\_vendor\lockfile\linklockfile.py", line 50, in acquire
    time.sleep(timeout is not None and timeout / 10 or 0.1)
KeyboardInterrupt```

**Comment by EdwardChamberlain** [comment]
When running pip with the `-v` flag for verbose output I end up with this line: 

`  Given no hashes to check 137 links for project 'pip': discarding no candidates`

Full log: https://pastebin.com/GUpga9We

**Comment by Legorooj** [comment]
Ok. Please open an issue in https://github.com/pypa/pypi-support and tag me on it.

**Comment by Legorooj** [comment]
Try `pip install https://github.com/pyinstaller/pyinstaller/archive/master.tar.gz`. that's the same release as PyPI

**Comment by htgoebel** [comment]
OP writes;
> pip hangs during install of pyionstaller

THis is a pip issue then, not related to PyInstaller.

**Comment by Legorooj** [comment]
Closing; a pip upgrade fixed the problem.
