### ISSUE TITLE
Error in running exe program

### ISSUE THREAD

**Issue by fantasyyxw2020** [pyinstaller/pyinstaller#4846]
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\_MEI155402\\pyecharts\\datasets\\map_filename.json'
[6216] Failed to execute script pyecha
This is my code
`import xlrd
from pyecharts.charts import Bar
data = xlrd.open_workbook('xiaoshoushuju.xls')
table = data.sheets()[0]  
names = []
sales = []
for i in range(1, table.nrows):
    name = table.row_values(i)[0]
    names.append(name)
    sale = table.row_values(i)[2]
    sales.append(sale)
bar = Bar()
bar.add_xaxis(names)
bar.add_yaxis('details', sales)
bar.render('1.html')`

**Comment by Legorooj** [comment]
@fantasyyxw2020 you need to write a hook for PyInstaller. See https://pyinstaller.readthedocs.io/en/stable/hooks.html
