### ISSUE TITLE
Huge File Sizes on Medium Sized App

### ISSUE THREAD

**Issue by arrudagates** [pyinstaller/pyinstaller#4847]
So, i am running this:
`/home/arruda/.temp_venvs/neo/bin/python -m PyInstaller /home/arruda/projects/musicplayer/neoplayer.py --workpath /home/arruda/.temp_venvs/neo/dist_cache --specpath /home/arruda/.temp_venvs/neo/dist_cache --name neoplayer --noconfirm --onefile --clean --exclude-module PyQt5 --hidden-import packaging.requirements --hidden-import pkg_resources.py2_warn --exclude-module numpy --exclude-module scipy`
in the Virtualenv i installed just the packages i need and still my executable is way bigger than it should be, i don't know what other files/logs i can provide.

**Comment by Legorooj** [comment]
@arrudagates package it without onefile, and look inside the generated folder. Which files are the largest?
