### ISSUE TITLE
PySide2 app blank screen when using web view on OSX

### ISSUE THREAD

**Issue by Cross22** [pyinstaller/pyinstaller#4848]
Minimal example below. Running `pyinstaller main.py` on OSX creates an executable that launches but it is just a blank screen instead of the web page you see when running `python main.py`
```
$ python --version
Python 3.7.7

$ uname -v
Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64

$ cat requirements.txt 
PyInstaller==3.6
PySide2==5.14.0

$ cat main.py 
from PySide2.QtCore import QUrl
from PySide2.QtWidgets import QApplication
from PySide2.QtWebEngineWidgets import QWebEngineView

if __name__ == '__main__':
    import sys
    app = QApplication(sys.argv)
    w = QWebEngineView()
    w.load(QUrl("https://google.com"));
    w.show()
    sys.exit(app.exec_())
```

**Comment by Legorooj** [comment]
@Cross22 can you please try `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`?

**Comment by Cross22** [comment]
Thanks Legorooj, the dev branch indeed fixes the blank screen issue! 
I still see warnings at build time (missing shiboken library) and at runtime (PySide2 looking for data files in malformed path) but it does work.

**Comment by Legorooj** [comment]
@Cross22 I'll close this issue then. It's relatively safe to use the development branch; we only merge stable work into it. It's just full of new features and bugfixes. 

Maybe those need fixing, maybe they don't. Feel free to open new issues if they're bugs.
