### ISSUE TITLE
Use github actions for running lint phase

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#4850]
As suggested by @Legorooj https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/3#issuecomment-618176711

**Comment by Legorooj** [comment]
@htgoebel I'll set this up tomorrow on my fork and get it working, then check with you it's fine.

**Comment by Legorooj** [comment]
Took me more than a day. If @htgoebel is happy with https://github.com/pyinstaller/pyinstaller/compare/develop...Legorooj:add_lint-1 I'll merge in the changes tomorrow. (Well, replicate them. GitHub actions is picky with actions creation.)
