### ISSUE TITLE
Exception: Cannot find PyQt4 plugin directories

### ISSUE THREAD

**Issue by programerTobyLai** [pyinstaller/pyinstaller#4851]
Exception: Cannot find PyQt4 plugin directories

So I uninstalled pyqt4
But it's useless！
the error still
Exception: Cannot find PyQt4 plugin directories

**Comment by Legorooj** [comment]
Can we have the full traceback?

**Comment by programerTobyLai** [comment]
pyinstaller -F server.py


server.py is not a gui program
but.........
nnot find PyQt4 plugin directories
Toby 
On 5/4/2020 08:24，Legorooj<notifications@github.com> wrote：

Can we have the full traceback?

**Comment by programerTobyLai** [comment]
135 INFO: PyInstaller: 3.6
135 INFO: Python: 3.7.4
136 INFO: Platform: Windows-10-10.0.18362-SP0


Toby 
On 5/4/2020 08:24，Legorooj<notifications@github.com> wrote：

Can we have the full traceback?

**Comment by Legorooj** [comment]
@programerTobyLai that's not the full traceback. Can you copy and paste the entire output into a GitHub gist?

**Comment by bjones1** [comment]
PyInstaller doesn't support PyQt4 under Python 3.

**Comment by programerTobyLai** [comment]
i uninstalled pyqt4！


On 05/04/2020 10:57, Bryan A. Jones wrote:

PyInstaller doesn't support PyQt4 under Python 3.
