### ISSUE TITLE
importlib_metadata.packagenotfounderror: audio metadata

### ISSUE THREAD

**Issue by harshnagar** [pyinstaller/pyinstaller#4853]
This Error occur while running my exe file of my python program. I have created the exe file using auto-to-py-exe

**Comment by Legorooj** [comment]
You need to collect the metadata for the package with a hook. See https://pyinstaller.readthedocs.io/en/stable/hooks.html for more details.

**Comment by harshnagar** [comment]
Can you tell me step by step how can i do it?

**Comment by Legorooj** [comment]
@harshnagar an overview is:

1. Write a hook file. Inside the file import the correct utils and collect the metadata. Refer to the link I sent above for more info.

2. Add the hook into building with `--additional-hooks-dir=dir/with/hook-file`.

**Comment by harshnagar** [comment]
@Legorooj
Thanks for your help, but it would be a great help if you tell me what i have to write in the hook file, I am unable to understand from the site. Please a humble request.

**Comment by Legorooj** [comment]
What's the exact traceback? I can't write the hook without it.

**Comment by harshnagar** [comment]
@Legorooj thanks for your help but i have solved my problem by using python build and after that manually adding the required files.
But again thanks for your replies 👍
