### ISSUE TITLE
Improve docu about __file__ usage with relative paths in bundled mode

### ISSUE THREAD

**Issue by schwingkopf** [pyinstaller/pyinstaller#4854]
I encountered inconsistent behavior between running a bundle on win10 vs linux when using relative paths and `__file__` to locate resources at run-time.

My particular problem ocurred when using relative paths that navigate to the parent or sibling folders to access data files, e.g. like :
```
from os import path
path_to_dat = path.join(path.dirname(__file__), './../myFiles/file.dat') 
```
with a folder structure like:
```
.
├── main.py
├── myModule
|   ├── myTestCode.py
├── myFiles
|   ├── file.dat
├── myFilesMixedWithPyCode
|   ├── myTestCode2.py
|   └── barfile.dat
```
Running the above code within myTestCode2.py, the resolving of `path_to_file` works on win10 and linux.
Running the above code within myTestCode.py, the resolving of `path_to_file` works on win10, but not on linux. 

The problem is that the full path in this case reads `sys._MEIPASS/myModule/../myFiles/file.dat`, that tries to access the "myModule" folder which is no longer present in bundled mode. Windows somehow can handle this, probably by a "late binding" approach when path resolving (not actually accessing "/myModule", but applying the parent navigation before).

Trying to access `barfile.dat` using the same approach would succeed in both cases, since the `myFilesMixedWithPyCode` folder would actually exist in bundled mode, as long as `barfile.dat` is part of the bundle.
 
I think this is a caveat worth mentioning in the docs in the section where the usage of relative paths to resources using `__file__` is mentioned. Would you agree?

**Comment by Legorooj** [comment]
This is unclear... How did you compile it? Which command? Which folders did you import? What did you add as a data/binary?

**Comment by schwingkopf** [comment]
I prepared a full minimal project for you in the attached .zip file. Feel free to explore.
[pyinstaller_problem_with_file_import.zip](https://github.com/pyinstaller/pyinstaller/files/4582909/pyinstaller_problem_with_file_import.zip)

The resulting program output is:
Linux (non-bundled):
```
Hello from /myFiles/file.dat
Hello from /myFilesMixedWithPyCode/file.dat
Hello from /myFiles/file.dat
Hello from /myFilesMixedWithPyCode/file.dat
```
Linux (bundled):
```
[Errno 2] No such file or directory: '/work/myModule/./../myFiles/file.dat'
[Errno 2] No such file or directory: '/work/myModule/./../myFilesMixedWithPyCode/file.dat'
Hello from /myFiles/file.dat
Hello from /myFilesMixedWithPyCode/file.dat
```
Windows (non-bundled):
```
Hello from /myFiles/file.dat
Hello from /myFilesMixedWithPyCode/file.dat
Hello from /myFiles/file.dat
Hello from /myFilesMixedWithPyCode/file.dat
``` 
Windows (bundled):
```
Hello from /myFiles/file.dat
Hello from /myFilesMixedWithPyCode/file.dat
Hello from /myFiles/file.dat
Hello from /myFilesMixedWithPyCode/file.dat
``` 

I'm running pyInstaller 3.6 with python 3.7.5

**Comment by Legorooj** [comment]
@schwingkopf I'll take look.

**Comment by Legorooj** [comment]
@schwingkopf I've taken a look... You should be using absolute paths.

From:
```
from os import path
path_to_dat = path.abspath(path.join(path.dirname(__file__), './../myFiles/file.dat'))
```
To:
```
from os import path
path_to_dat = path.abspath(path.join(path.dirname(__file__), './../myFiles/file.dat'))
```
Does that work? I don't have a Linux box to try it out on.

**Comment by schwingkopf** [comment]
@Legorooj , thanks for the suggestion, that actually does work! Resolving the path before linux has to do it solves the problem.

So adding a little note about this in the doc would be nice.

**Comment by Legorooj** [comment]
https://github.com/pyinstaller/pyinstaller/commit/5e33cce158816b9780d5456c6430a2dce1df0345
