### ISSUE TITLE
Failed to execute script pyi_rth_multiprocessing, ImportError: DLL load failed while importing _socket: The parameter is incorrect.

### ISSUE THREAD

**Issue by klienn** [pyinstaller/pyinstaller#4855]
I am trying to run my python ```.exe``` file on another machine but unable to. I tested it on my machine and the application works but on running it in other machine outputs the following error:

```
Traceback (most recent call last):
  File "C:\Users\klien\AppData\Local\Programs\Python\Python38-32\Lib\site-packa
es\PyInstaller\loader\rthooks\pyi_rth_multiprocessing.py", line 18, in <module>
  File "c:\users\klien\appdata\local\programs\python\python38-32\lib\site-packa
es\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "c:\users\klien\appdata\local\programs\python\python38-32\lib\site-packa
es\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "c:\users\klien\appdata\local\programs\python\python38-32\lib\site-packa
es\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "c:\users\klien\appdata\local\programs\python\python38-32\lib\site-packa
es\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: The parameter is incorrec
.
[1640] Failed to execute script pyi_rth_multiprocessing
```

Any help will be greatly appreciated, Thanks!

**Comment by erezsh** [comment]
I'm getting the same error on Windows 7 32-bit, for PyInstaller compiled on Windows 10 64-bit.

**Comment by klienn** [comment]
@erezsh I fixed this problem by updating the windows on its latest update. Hope it helps!

**Comment by xiaojeff721** [comment]
This problem exists in Python 3.8.3, and I fall back to 3.7.8 to solve the problem

**Comment by fzuccolo** [comment]
Installing security update [KB2533623](https://www.microsoft.com/en-us/download/details.aspx?id=26767) in Win7x86 host should solve this issue, tested for python 3.8.5.

**Comment by ManPython** [comment]
Installing security update KB2533623 in Win7x64 host should solve this issue, tested for python 3.8.5.
https://www.microsoft.com/en-us/download/confirmation.aspx?id=26764
The KB2533623 as Win7x64 wan't install due to some problems 0x80070422 if win update is turned of.

**Comment by nejch** [comment]
So, we're getting the same issue but it works in `git-bash`, powershell, and when running the .exe directly from a file explorer, but it doesn't work from a `cmd` shell. Is anyone getting the same behavior?

**Comment by fbosio** [comment]
@ManPython 

> 
> 
> Installing security update KB2533623 in Win7x64 host should solve this issue, tested for python 3.8.5.
> https://www.microsoft.com/en-us/download/confirmation.aspx?id=26764
> The KB2533623 as Win7x64 wan't install due to some problems 0x80070422 if win update is turned of.

KB2533623 did not work for me in Windows 7 Home Basic SP1 64 bits with Python 3.8.6 (got an "Update not applicable" message) but [KB3126587](https://www.catalog.update.microsoft.com/Search.aspx?q=KB3126587%20windows%207) _did_!

Hope it helps someone! :grin:

**Comment by stolz55** [comment]
KB3126587 also worked for me. I was getting a similar message when trying to start Cura 4.9

**Comment by bwoodsend** [comment]
Officially, PyInstaller has pulled the plug on Windows 7. If you want to support Windows 7 you should build on Windows 7 so that you don't find yourself dependent on DLLs that aren't there.

**Comment by liudonghua123** [comment]
I have the same problems recently.

![image](https://user-images.githubusercontent.com/2276718/180486801-5d68013d-9f57-49bc-a21b-8365e0465fef.png)

I tried to install [KB3126587](https://www.catalog.update.microsoft.com/Search.aspx?q=KB3126587) while [KB2533623](https://www.catalog.update.microsoft.com/Search.aspx?q=KB2533623) is not available for my win7 x64. And it worked for me.

Thanks!

**Comment by qianhangkang** [comment]
> 

this link is unavailable... so sad
