### ISSUE TITLE
Fixed : AssertionError: Hook Conflict. Please remove the following custom hook: __PyInstaller_hooks_0_ PySide2

### ISSUE THREAD

**Issue by samlefeon** [pyinstaller/pyinstaller#4856]
Hi, 

When freezing my app, I had the following error : 
`AssertionError: Hook Conflict. Please remove the following custom hook: __PyInstaller_hooks_0_ PySide2`

Fixed by removing `hook-PySide2.py` from `Project\venv\Lib\site-packages\PyInstaller\hooks`

Hope it will help you!

**Comment by Legorooj** [comment]
@samlefeon you're using the development version right?

**Comment by samlefeon** [comment]
@Legorroj Do you mean the development version of Pyinstaller ? 
I installed it with this : pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip

**Comment by Legorooj** [comment]
@samlefeon yes, the development version of PyInstaller.

Which command are you using to build? What is the full output of the build?

**Comment by samlefeon** [comment]
It is pyinstaller 3.4

I build with "fbs freeze"

No custom hooks.

**Comment by Legorooj** [comment]
We/I can't help then. `fbs` is using an outdated version of PyInstaller, and we don't offer support for it. And this error is caused by `fbs`, not PyInstaller.

**Comment by samlefeon** [comment]
Ok. Should I install pyinstaller with this command ?
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip

I have another problem : my executable is told to be a virus by some antiviruses (on my colleagues computers). Do you know why ?

**Comment by Legorooj** [comment]
@samlefeon that - the antivirus issue - comes and goes. Rebuilding the bootloader can fix it (see the docs). 

`pip install -U PyInstaller` first. That will install PyInstaller 3.6, the latest stable version.

**Comment by samlefeon** [comment]
Ok. Thanks for all these information!

Regards

**Comment by samlefeon** [comment]
I installed pyinstaller 3.6 but received this message when launching my app : 

"failed to execute script pyi_rth_pkgres"

**Comment by Legorooj** [comment]
@samlefeon google the error and if you can't find anything open a new issue.
