### ISSUE TITLE
gevent hook unnecessarily bundles ~17MB of "stuff"

### ISSUE THREAD

**Issue by ulope** [pyinstaller/pyinstaller#4857]
## Description of the issue

The included `gevent` hook bundles about 17MB of unnecessary files.
These include:
- HTML documentation
- `__pycache__` folders
- tests
- Generated `.c` and `.h` files

## Context information (for bug reports)

* Output of `pyinstaller --version`: `3.6`
* Version of Python: `3.7.7`
* Platform: macOS 10.15.4 / Ubuntu 18.04

### A minimal example program which shows the error

`test.py`:
```
import gevent
```

Commands
```shell
$ pip install gevent pyinstaller
[...]
$ pyinstaller -D test.py
[...]
$ find dist/test/gevent -name "*.c" -or -name "*.h" -or -name "*.html" -or -path "*/__pycache__/*" -or -path "*/tests/*" | xargs du -shc
[...]
 17M	total
```

**Comment by Legorooj** [comment]
Hmm. Looks like the hook needs updating to remove files like that. If you'd be able to provide a PR?

**Comment by mihirsn** [comment]
Hi, I want to pick this up.

**Comment by Legorooj** [comment]
@mihirsn I've tracked this issue down and I'm in the process of fixing it. Thanks for the offer though!
