### ISSUE TITLE
Executable file builts in Windows 10 doesnt work in Windows 7

### ISSUE THREAD

**Issue by Kocaak** [pyinstaller/pyinstaller#4863]
Hello all,

I am having trouble with make my executable PyQT5 project created by PyInstaller with --onefile command (Python 3.8, PyQT5 5.14.2, PyInstaller 3.6) work in Windows 7 since It works in Windows 10 without any problem. In latest Visual C++ Redistribution and Universal C Runtime packages installed Windows 7, I got "Failed to execute script pyi_rth_multiprocessing" error. Couldnt find any solution on web. All helps and advices are welcome. Thank you in advance

**Comment by Legorooj** [comment]
What's the full traceback? And we don't support python 3.8 yet.

**Comment by Kocaak** [comment]
Hi, I dont have any traceback except error pop-up. I tried to re-run app with built console=True attribute and got this: 

(https://i.stack.imgur.com/ZnLIS.png)

The thing that makes me confuse is file path on command prompt is actually my computer's path. (C:\users\Asus is my username not installed user's)

**Comment by Legorooj** [comment]
@Kocaak there was a bug in strip-paths, which removes paths leftover from your PC. Apparently it wasn't fixed.

Hmm. That error needs looking into.

**Comment by Legorooj** [comment]
And just to check, you're running the executable from the `dist` folder, not the `build` folder right?

**Comment by Kocaak** [comment]
Yes, I am running the exe in dist folder but then how can it be possible works in w10 but not w7. It has no sense

**Comment by Legorooj** [comment]
@Kocaak it'll be related to runtime libraries. I'm afraid that all I can do to help is say try `--win-private-assemblies` and/or `--win-no-prefer-redirects`. Otherwise, a development decision was made the other day not to offer support for EOL products. IE windows 7 is supported by PyInstaller, but the developers (us) won't offer support for it in bug tickets/PRs. Sorry!

**Comment by Kocaak** [comment]
I am not sure if its about runtime libraries or packaging bug since I saw my computer's path on other computers but anyway I will check your advice for sure. Thank you

**Comment by Legorooj** [comment]
@Kocaak the computer paths are intentionally pulled from your PC. However, they should have been stripped to non-revealing paths. (Remove your username, drive, etc)
