### ISSUE TITLE
Can't install on my computer. Pip errors out with exit status 1.

### ISSUE THREAD

**Issue by Akaj-lab** [pyinstaller/pyinstaller#4864]
## Description of the issue
I can't install `pyinstaller` on my computer. 
## Context information (for bug reports)

* Version of Python: 3.8
* Platform: Windows (Slovenščina/Slovenian)
* Pyinstaller branch: develop and master
* pip version: 19.7 and 20.1

##SuperShell output
![SuperShell output](https://github.com/Akaj-lab/desktop-tutorial/blob/jaka/Opomba%202020-05-10%20174747.png)

**Comment by Legorooj** [comment]
Please open an issue in https://github.com/pypa/pip. They'll be more help.

**Comment by Akaj-lab** [comment]
## Solved
I solved it by installing it py `python setup.py install`.
