### ISSUE TITLE
Reoccurrence of #2322? Multiprocessing spawn in python 3 does not work on macOS

### ISSUE THREAD

**Issue by andyfaff** [pyinstaller/pyinstaller#4865]
## Description of the issue
There looks to be a reoccurrence of #2322 on macOS with spawn + multiprocessing. I came across this issue with a package that I develop (that uses PyQt5). When I try and use multiprocessing within my program I get multiple GUI windows displaying. This has only happened since building the executable with Py3.8 (spawn is default), it doesn't happen with Py3.7 (fork is default). I tried using the MWE from #2322 and it is failing on my computer.

## Context information

macOS 10.13.6
Python 3.8.2 (from conda)
PyInstaller: tip of the development branch (3.6)

  * [Y] start with clean installation
  * [Y] use the latest development version
  * [Y] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [Y] Package your program in **--onedir mode**
  * [Y] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [Y] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
Running `test.py` from bash is fine, and gives the expected result. However, running the packaged executable results in processes spawning continuously.

**test.py**
```
import sys
from multiprocessing import freeze_support, set_start_method, Process

def test():
    print('In subprocess')

if __name__ == '__main__':
    print(sys.argv,)
    freeze_support()
    set_start_method('spawn')

    print('In main')
    proc = Process(target=test)
    proc.start()
    proc.join()
```
**test.spec**
```
# -*- mode: python -*-

block_cipher = None


a = Analysis(['test.py'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='test',
          debug=True,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='test')
```
### Stacktrace / full error message
Log at https://gist.github.com/andyfaff/c8402452e7bf4d27a1c86c1c486a736e

**Comment by andyfaff** [comment]
BTW the issue also exists for:
```
import sys
from multiprocessing import freeze_support, set_start_method, Pool

def test(s):
    print(s)


if __name__ == '__main__':
    print(sys.argv,)
    freeze_support()
    set_start_method('spawn')

    print('In main')
    with Pool() as p:
        p.map(test, 'in pool')
```

**Comment by andyfaff** [comment]
I've just tested the MWE on Windows 7 | Python 3.8.0 | PyInstaller 3.6, it works without issue.

**Comment by andyfaff** [comment]
Amongst other failures the pyinstaller test suite also hangs at `tests/functional/test_multiprocess.py::test_multiprocess[onedir]`.

**Comment by andyfaff** [comment]
I *think* I know what the error is caused by here (after spending several hours on it). If you look at my log file on [L99](https://gist.github.com/andyfaff/c8402452e7bf4d27a1c86c1c486a736e#file-log-L99) you see:
```
['/Users/anz/Documents/Andy/programming/refnx/dist/test/test', '-B', '-S', '-E', '-s', '-c', 'from multiprocessing.resource_tracker import main;main(4)']
```
Note the presence of `multiprocessing.resource_tracker` in the last entry.

This should be dealt with by the patched [`freeze_support`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L24), but the function fails to do that. This is because the function tries to looking for:
```
sys.argv[-1].startswith('from multiprocessing.semaphore_tracker
````

In the transition Py3.7 to Py3.8 `semaphore_tracker` went to `resource_tracker` in CPython.

Thus the multiprocessing hook needs to be changed to:

```
    if len(sys.argv) >= 2 and \
            set(sys.argv[1:-2]) == set(_args_from_interpreter_flags()) and \
            sys.argv[-2] == '-c' and \
            (sys.argv[-1].startswith('from multiprocessing.semaphore_tracker import main') or \
             sys.argv[-1].startswith('from multiprocessing.resource_tracker import main') or \
             sys.argv[-1].startswith('from multiprocessing.forkserver import main')):
```

I'll work up a patch, test locally, and submit a PR if I'm correct.

**Comment by Legorooj** [comment]
Yay. More issues about multiprocessing. 

On the upside, you've tracked it down! But we need python 3.8 support first.

**Comment by htgoebel** [comment]
@andyfaff Can you please summarize the issue? AFAIU, the process is running in an endless-loop. Is this the issue?

**Comment by htgoebel** [comment]
@andyfaff And can you please check whether the test-suite triggers an error. Otherwise we need new test-cases.
```
python3.8 -m venv /tmp/venv
. /tmp/venv/bin/activate
pip install -r tests/requirements-tools.txt
pip install -e .
pytest tests/functional/test_multiprocess.py
```

**Comment by htgoebel** [comment]
@andyfaff @reritom I added test-case replicating your examples. I could not reproduce the need patching spawning.Popen being required for Py 3.8 on MacOS. Please 
* clone https://github.com/hgoebel/pyinstaller.git, 
* run `git checkout issue-4865`
* perform the commands in the comment above and 
* report the result.
Thanks

**Comment by reritom** [comment]
@htgoebel I will perform the commands and report the result, however the linked repo https://github.com/hgoebel/pyinstaller.git is not found, could you check that please?

**Comment by htgoebel** [comment]
@reritom Sorry, there is a typo in the repo (missing t). Here is the correct one: https://github.com/htgoebel/pyinstaller.git,

**Comment by andyfaff** [comment]
@htgoebel I ran:

```
python3.8 -m venv /tmp/venv
. /tmp/venv/bin/activate
pip install -r tests/requirements-tools.txt
pip install -e .
pytest tests/functional/test_multiprocess.py
```

the test suite doesn't pass, with a fail in `FAILED tests/functional/test_multiprocess.py::test_multiprocess_pool[onefile]`. The log file is [here](https://gist.github.com/andyfaff/44f7f99a8a7f528a988471cf3ab48710)

**Comment by andyfaff** [comment]
> @andyfaff Can you please summarize the issue? AFAIU, the process is running in an endless-loop. Is this the issue?

I'll attempt to summarise the issue as best I can.

- I am trying to use `multiprocessing` in a standalone pyinstaller packaged executable.
- On macOS 3.8 the default start method for multiprocessing is `spawn`. On macOS 3.7 it was `fork`.
- With the original example I supplied (test.py and test.spec) if I make the pyinstaller single folder distribution using the `develop` branch and run the `test` executable from the command line (i.e. `cd dist/test; ./test`) there I get continuous spawning of processes which I then have to kill.
- If I use the `issue-4865` branch then I see the expected behaviour:
```
192-168-1-103:test andrew$ ./test 2>/dev/null
['./test']
In main
['/Users/andrew/Documents/Andy/programming/pyinstaller/testy/dist/test/test', '-B', '-S', '-E', '-s', '-c', 'from multiprocessing.resource_tracker import main;main(4)']
['/Users/andrew/Documents/Andy/programming/pyinstaller/testy/dist/test/test', '--multiprocessing-fork', 'tracker_fd=5', 'pipe_handle=7']
In subprocess
```
i.e. there is a print of `sys.argv`, followed by a print of `In main`, then there is a print of `sys.argv` from the spawned process, followed by a print of `In subprocess`, then the program exits. There is no continuous spawning of new processes.

- From the output of the program using either the `develop` or `issue-4865` branch you'll see a line that has `sys.argv[-1] == 'from multiprocessing.resource_tracker import main;main(4)'`. i.e. the spawn process is importing main from `resource_tracker`. The [`_freeze_support` function in pyi_rth_multiprocessing](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L40) is meant to deal with that, as it's called by freeze_support in the test.py program. In the `develop` branch it [can't deal](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L41) with a string beginning with `from multiprocessing.resource_tracker`, but in the [issue-4865 branch it can](https://github.com/htgoebel/pyinstaller/blob/issue-4865/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L39).

 - The [Python `freeze_support` documentation](https://docs.python.org/3.8/library/multiprocessing.html#multiprocessing.freeze_support) states that `freeze_support` has no effect on platforms other than Windows. This is incorrect (at least in this situation). If the `freeze_support` line is commented out in test.py then I get continuous spawning of processes on macOS 3.8. If `freeze_support` is called (using issue-4865) then the program works.

**Comment by andyfaff** [comment]
I should qualify that test run a bit more. That was on branch `issue-4865`. It did run to completion, even if there was a failure. With branch `develop` the test run never gets pass the first one, and new processes are continually being spawned that requires a reboot to stop them.

**Comment by htgoebel** [comment]
@andyfaff Thanks for providing the information. Just to double check:
- Using branch `develop`,  both examples (https://github.com/pyinstaller/pyinstaller/issues/4865#issue-615555063 and https://github.com/pyinstaller/pyinstaller/issues/4865#issuecomment-626456657) can be frozen, but the frozen executables do not terminate (they keep spwaning new processes over and over again)
- Using branch `issue-4865`, both examples can be frozen and the frozen executable work as expected (this is: spawning once and then terminate)

Correct?

**Comment by andyfaff** [comment]
@htgoebel your statement is correct, except today I didn't check the second example, just the first.

**Comment by htgoebel** [comment]
Thnx

**Comment by JapinderSandhu** [comment]
How do I solve this issue? I have the same problem I am using 

python 3.8.5 
opencv-python 4.4.0.44
pyinstaller 4.0

please let me know as this is major issue as I use pyinstaller for my backend server.

Is there any workarounds?

**Comment by JapinderSandhu** [comment]
i solved!

 This actually worked for me:

https://github.com/pyinstaller/pyinstaller/issues/2322 

> https://github.com/mherrmann/fbs/issues/87#issuecomment-471489980


Before:

```python
multiprocessing.set_start_method('spawn')
```

After:

```python
multiprocessing.freeze_support()
multiprocessing.set_start_method('spawn')
```

**Comment by Legorooj** [comment]
@JapinderSandhu the development branch should work. `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`.

**Comment by JapinderSandhu** [comment]
> @JapinderSandhu the development branch should work. `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`.

@Legorooj  I installed this as you suggested:

`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip.`

Python 3.7.9
pyinstaller   4.1.dev0
opencv-python   4.4.0.44


and commented out 
```python

#multiprocessing.freeze_support()
multiprocessing.set_start_method('spawn')

```

the executable crashes so installing the dev pyinstaller did not work.

**Comment by Legorooj** [comment]
@JapinderSandhu what's the error it crashes with?

**Comment by andyfaff** [comment]
From memory the freeze_support should be used.

**Comment by JapinderSandhu** [comment]
> From memory the freeze_support should be used.
@andyfaff  @Legorooj 

Without using freeze_support I get 

```bash
> Starting server...
> Server started.
EXCEPTION PRINT: Traceback (most recent call last):
  File "server.py", line 135, in <module>

```
the traceback is not really informative 

using freeze_support everything works fine.

so I will go back to regular pyinstaller 4.0 instead of pyinstaller 4.1.dev0

thanks

**Comment by andyfaff** [comment]
If using freeze_support works then why aren't you using it?

**Comment by JapinderSandhu** [comment]
> If using freeze_support works then why aren't you using it?

@andyfaff I am using freeze_support and it works with pyinstaller 4.0 everything works.

i dont want to use pyinstaller 4.1.dev0 because its unstable at the moment? I dont want to ship unstable dev library in my production code.

**Comment by Legorooj** [comment]
@JapinderSandhu our development branch is much more stable than most development branches. But if freeze_support works, that's fine.
