### ISSUE TITLE
application bundle is denied permission to run mac os x lion

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#487]
**Original date**: 2012/01/05
**Original reporter**: *jagadish123 AND gmail DOT  COOM *

Hi;

i used pyinstaller latest trunk to build a app bundle of my gui done in pyqt, under snow leopard, it runs fine on leopard but fails to run on my other mac which is running lion, the Console says permission denied, and the app exits..

i also tried using pyinstaller version 1.6d which worked a while ago for a prototype but for some reason it does not run now..

please help.

**Comment by matysek** [comment]
User reported it works so closing.
