### ISSUE TITLE
executing error if freezing in windowed mode: "Failed to execute script pyi_rth_pkgres"

### ISSUE THREAD

**Issue by maxschmi** [pyinstaller/pyinstaller#4870]
I have a module that is writen in python3. When I install it with pip I can start my GUI. Now I tried to create a compiled executable with pyinstaller(3.6) on Windows 10.

If I do the compilation without the argument --windowed ican start my executable from the console and everything works fine. 
But if I add this option I always get the error mesage "Failed to execute script pyi_rth_pkgres", when I try to start the .exe.

My script file (run.py) that i compile looks like this:
```python
import chatwolf

root = chatwolf.GUI()
root.mainloop()
```

My Powershell command for compiling looks like this:

```
pyinstaller --add-data="README.md;." --add-data="LICENSE.txt;." 
--add-data="doc/pdf/chatwolf.pdf;doc" --add-data="chatwolf/data/messages;data/messages" 
--add-data="chatwolf/data/conf_root.json;data/" --add-data="chatwolf/data/icon.png;data/" 
--name="Chatwolf" --icon=install/icon.ico --onefile --clean --windowed --noconfirm run.py
```
Here are the Warnings:
[warn-Chatwolf.txt](https://github.com/pyinstaller/pyinstaller/files/4617285/warn-Chatwolf.txt)
and the .spec file:
[Chatwolf.spec.txt](https://github.com/pyinstaller/pyinstaller/files/4617291/Chatwolf.spec.txt)

Is this a bug or is it me? :-)

From searching I got already, that this is do to the pkg_resource model.

I tried: 
- changing my module code, so I don't use the pkg_resource module in my chatwolf module. 
- added --hidden-import="pkg_resource.py2_warn" 
- updated pyinstaller and pkg_resource

Nothing helped!

**Comment by Legorooj** [comment]
Build without `--windowed` and run it from a command prompt. What's the traceback?

**Comment by maxschmi** [comment]
the same building commands without `--windowed`, gives me this Traceback, when executing:
```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
  File "c:\users\max\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[9912] Failed to execute script pyi_rth_pkgres
```

if I add also the `--hidden-import="pkg_resource.py2_warn"` I get this:

```
Traceback (most recent call last):
  File "site-packages\PyInstaller\loader\rthooks\pyi_rth_pkgres.py", line 13, in <module>
  File "c:\users\max\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\pkg_resources\__init__.py", line 86, in <module>
ModuleNotFoundError: No module named 'pkg_resources.py2_warn'
[21692] Failed to execute script pyi_rth_pkgres
```

**Comment by maxschmi** [comment]
okay I realised that I had a spelling error.
The `--hidden-import="pkg_resources.py2_warn"` solves the problem!
