### ISSUE TITLE
PyCrypto/PyCryptodome replacement...

### ISSUE THREAD

**Issue by Dariusz1989** [pyinstaller/pyinstaller#4871]
Hey

Would it be possible for pyinstaller to be able to use pycryptodome as well ? Installing pycrypto is fairly painful. 

I tried ussing pyCryptodome but I'm getting the same errors as this guy > https://stackoverflow.com/questions/56911760/pyinstaller-problem-when-using-key-command

TIA

**Comment by Legorooj** [comment]
@Dariusz1989 please see #4652, which will fix this issue.

**Comment by Salim9304** [comment]
Have you updated the 'Encryption Theater'?
Could you add a mini instruction on how to encrypt byte code using the new library?
The documentation still has `--key 'probably this does not work.

**Comment by Legorooj** [comment]
@Salim9304 all the necessary changes have been made. You can install the development version to use it, and use the `latest` version of the docs.
