### ISSUE TITLE
Release hook to fix `setuptools==45.0.0`

### ISSUE THREAD

**Issue by bwoodsend** [pyinstaller/pyinstaller#4872]
**Is your feature request related to a problem? Please describe.**
Hi, I've been on the PyInstaller support Google group for about a month and I've already lost count of the number of times we've been asked about the ` ModuleNotFoundError: No module named 'pkg_resources.py2_warn' ` bug cause by a hidden import added in `setuptools==45.0.0`. This has been addressed in #4672 and the hook updated in [this commit](https://github.com/pyinstaller/pyinstaller/commit/91481570517707fc70aa70dca9eb986c61eac35d) but it still hasn't made its way into a release.

**Describe the solution you'd like**
The first thing everyone seems to do when they encounter this issue is to try upgrading setuptools and PyInstaller. So I believe all we'd really need to do is just create a patch release PyInstaller 3.6.1 with this hook included and we should never see this issue again. Would this be doable?

**Alternatives**
Ideally people would be able to just look at previous answers to this problem but it doesn't look like our support conversations get much priority in Google searches because even if you search the exact title, they're still hard to find.

**Comment by Legorooj** [comment]
@bwoodsend we're prepping for a release as we speak. Expect release 4.0 to land early June.

**Comment by rjaduthie** [comment]
Any update on this release?  It's now mid-June and the bug that this issue relates to means we have CI.  The project I'm working on is new, so the urgency is not high (yet!).  

Where can we get updates on release or perhaps lend a hand?

**Comment by Legorooj** [comment]
@rjaduthie we're pushing for the end of June at the latest there's only a couple of things left to do. In the meantime, you can use the development version - it's pretty stable.

Thanks for the offer to lend a hand, but we should be fine. I hope to have the work we need done by the end of the week - hopefully. I can guarantee the end of June though.
