### ISSUE TITLE
Python - pyinstaller - executable project by pyinstaller has error Failed to execute script pyi_rth_pkges

### ISSUE THREAD

**Issue by blourabie** [pyinstaller/pyinstaller#4877]
exe?noredirect=1#comment109363088_61809279

**Comment by Legorooj** [comment]
You don't build the `setup.py` with PyInstaller, you build the `main.py` with PyInstaller.

**Comment by blourabie** [comment]
I do it thanks all work fine, but in Interface I have image but after convert by pyinstaller I don't see this image why?
this is the code :
         
![image into](https://user-images.githubusercontent.com/53751601/82149048-8fbe4c00-9845-11ea-9cb2-86bc0707950b.JPG)


this is the app.spec file:

![GITHUB](https://user-images.githubusercontent.com/53751601/82149009-48d05680-9845-11ea-8079-a50859c0e19d.JPG)

I use Pycharm this image work fine in script but after convert by pyinstaller I don't see this image why?

**Comment by Legorooj** [comment]
What's the output from building?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
