### ISSUE TITLE
base_library.zip disappears after first run of program

### ISSUE THREAD

**Issue by huangguifeng** [pyinstaller/pyinstaller#4880]
If pyinstaller packages the program into multiple files, it can only run once after closing the program

Base_library.zip is missing, causing the second time to fail to run

**Comment by Legorooj** [comment]
@huangguifeng can you please give us steps to reproduce? This shouldn't be happening.

**Comment by huangguifeng** [comment]
找到问题了，是权限问题。需要将Base_library.zip设置为只读
