### ISSUE TITLE
Improve pkg_resources support

### ISSUE THREAD

**Issue by Legorooj** [pyinstaller/pyinstaller#4881]
PyInstaller's support of `pkg_resources` is, at the best, sketchy, and isn't very effective. I've got a couple of examples which need fixing:
## Providers
When using `pkg_resources`, PyInstaller registers `NullProvider` as the resource provider for the pyinstaller importer class.

I took a quick stab at this in legorooj/pyinstaller@fe88a39c, by replacing `NullProvider` with `DefaultProvider`. However, it 
looks like `DefaultProvider` causes some tests to fail. I'll look into this more, but I think this will require writing our own 
Provider class. 

The Providers allow the `pkg_resources` module to access metadata and file contents among other things like resource files (eg fonts, images).

## Metadata

PyInstaller currently has a function `collect_metadata` in our hook-utils. Unfortunately the function doesn't cover all use cases. The following extract from the functions comments can sum up a few of the problems quite nicely:

https://github.com/pyinstaller/pyinstaller/blob/6cd98f93aa13b385b40e102c9c5b10a93e965922/PyInstaller/utils/hooks/__init__.py#L869-L892

A list of current known problems including those mentioned in the comment:

* Metadata directories are, in some cases, not easily copiable - they might be in a ZIP file (a zipped-egg if you're wondering), they might not be found by our directory patterns.
* This doesn't copy all of the metadata sometimes; sometimes there are multiple sources.

And there's also:

* Minimal to no documentation on how the internals of pkg_resources work. It's surprisingly bad for the packing which has nearly double the yearly downloads of any other single package on PyPI (See https://pypistats.org/top. `pkg_resources` is part of setuptools)
* A multitude of little quirks introduced by things like conda.

I'm sure I'm only scratching the surface here, but I'll stop now. This issue will take a _lot_ of work, and, because most packages will work with(out) the `copy_metadata` function, this falls to medium priority, and the `4.x` milestone. Things like the modulegraph move and more prominent bugs need fixing first.

**Comment by bwoodsend** [comment]
This is done.
