### ISSUE TITLE
Question about pywrap_tensorflow in tf2.1 environment

### ISSUE THREAD

**Issue by wangwenchao-job** [pyinstaller/pyinstaller#4882]
## My environment is ：
ubuntu 18.04
pyinstaller 3.6
tensorflow 2.1

## My error is
ImportError: cannot import name 'pywrap_tensorflow' from 'tensorflow_core.python' 

----
I have tested many versions of tensorflow. It can be used normally under 1.14. If it exceeds 1.14, this problem will be reported.

Someone mentioned here that pyinstaller currently only supports tensorflow version below 1.14?
https://github.com/tensorflow/tensorflow/issues/33722

**Comment by Legorooj** [comment]
PyInstaller only supports tensorflow 1.14 and below in PyInstaller 3.6. There's hooks added in the development version, which work with tensorflow 2. 

We plan to release this in a month or two.
