### ISSUE TITLE
pyinstaller --icon option occured pywin32error

### ISSUE THREAD

**Issue by Sawada1908** [pyinstaller/pyinstaller#4883]
I want to use icon which I created for .py file.
So, I entered 'pyinstaller test.py --onefile --icon=test.icon' command.
But Command Prompt returned error below.
```
File "c:\python27\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
    raise error(exception.winerror, exception.function, exception.strerror)
win32ctypes.pywin32.pywintypes.error: (87, 'UpdateResourceW', '\x83p\x83\x89\x83\x81\x81[\x83^\x81[\x82\xaa\x8a\xd4\x88\xe1\x82\xc1\x82\xc4\x82\xa2\x82\xdc\x82\xb7\x81B')
```
It's My Develop environment.
OS : Window 10 Pro 1909
python : 2.7.18
pywin32 : 227
pywin32-ctypes : 0.2.0
pyinstaller : 3.6

I would like to solve this problem.
Please help me. Thanks.

**Comment by Sawada1908** [comment]
> I want to use icon which I created for .py file.
> So, I entered 'pyinstaller test.py --onefile --icon=test.icon' command.
> But Command Prompt returned error below.
> 
> File "c:\python27\lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 37, in pywin32error
> raise error(exception.winerror, exception.function, exception.strerror)
> win32ctypes.pywin32.pywintypes.error: (87, 'UpdateResourceW', '\x83p\x83\x89\x83\x81\x81[\x83^\x81[\x82\xaa\x8a\xd4\x88\xe1\x82\xc1\x82\xc4\x82\xa2\x82\xdc\x82\xb7\x81B')
> 
> It's My Develop environment.
> OS : Window 10 Pro 1909
> python : 2.7.18
> pywin32 : 227
> pywin32-ctypes : 0.2.0
> pyinstaller : 3.6
> 
> I would like to solve this problem.
> Please help me. Thanks.

**Comment by Legorooj** [comment]
@Sawada1908 I've been unable to reproduce - though I am running python 3. Can you try and use python 3?

**Comment by amifunny** [comment]
@Sawada1908 Did you resolved the issue? I think the .icon extension might be the problem I guess. For ICON, .ico is used.

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.

**Comment by Stanford2299** [comment]
I also encountered this problem. My windows platform is also 10pro

**Comment by bwoodsend** [comment]
Are you able to share the icon file?

**Comment by Stanford2299** [comment]
the question is resolved.the ico is too big,i choose a another ico. The program is running well
