### ISSUE TITLE
Targeting an old version of macOS when building the bootloaders causes GUI theming to break.

### ISSUE THREAD

**Issue by adamurban** [pyinstaller/pyinstaller#4886]
I have a small GUI app made using pyside2/Qt. When I launch the .py from the terminal, dark mode is supported and switches correctly as the OS does. However, when I launch the same code compiled to a .app using pysintaller (created via `pyinstaller --windowed`), the UI shows only the light interface.

**Comment by Legorooj** [comment]
@adamurban I can't explain this off the top of my head. Have you tried to figure out the cause?

**Comment by adamurban** [comment]
Adding `'NSRequiresAquaSystemAppearance': 'No'` to my spec makes it so the app switches now:
`             info_plist={
                'NSHighResolutionCapable': 'True',
                'NSRequiresAquaSystemAppearance': 'No'
                },`
However, it is completely broken and none of the UI elements show up.
It throws this error:
`It does not make sense to draw an image when [NSGraphicsContext currentContext] is nil.  This is a programming error. Break on void _NSWarnForDrawingImageWithNoCurrentContext(void) to debug.  This will be logged only once.  This may break in the future.`

Searching for this, I found this, which appears to be the same issue: https://github.com/pyinstaller/pyinstaller/issues/4627

**Comment by adamurban** [comment]
And for reference, I am running Python 3.7.7 with pyinstaller 3.6, pyside2 version is 5.14.2.1 and Qt version is 5.14.2 (these are the latest availble via homebrew today). macOS version is Catalina 10.15.4

**Comment by adamurban** [comment]
NSRequiresAquaSystemAppearance shouldn't even be required... seems like this issue is because pyinstaller is targeting too old of an SDK:

```
$ otool -l /usr/local/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run

...
         cmd LC_VERSION_MIN_MACOSX
  cmdsize 16
  version 10.7
      sdk 10.11
...
```

**Comment by adamurban** [comment]
And indeed, just recompiling the bootloader fixes everything:
```
git clone https://github.com/pyinstaller/pyinstaller.git pyinstaller
cd pyinstaller
cd bootloader
export MACOSX_DEPLOYMENT_TARGET=10.13
export CFLAGS=-mmacosx-version-min=10.13
export CPPFLAGS=-mmacosx-version-min=10.13
export LDFLAGS=-mmacosx-version-min=10.13
export LINKFLAGS=-mmacosx-version-min=10.13
python3 ./waf all
cd ..
pip3 install .
```

**Comment by Legorooj** [comment]
@htgoebel can you take a look? We might want to adjust supported platforms etc so this is fixed. 

@adamurban thanks for figuring out the cause(?) and the fix.

**Comment by chen-zehua** [comment]
just use macos 10.14 recompile the bootloader solves the problem and the dark mode work as well，no need to set `MACOSX_DEPLOYMENT_TARGET=10.13`.

but another problem appear after i use the recompiled bootloader, i use the subprocess.Popen() api created a daemon process, but it always exited unexpectedly after started a while. which works well before i recompile the bootloader.  below 
 is the demo code:
```Python
         my_proc = subprocess.Popen(cmd,
                                         stdin=subprocess.PIPE,
                                         stdout=subprocess.PIPE,
                                         stderr=subprocess.STDOUT,
                                         shell=True
                                         )
        for line in iter(my_proc.stdout.readline, ""):
            if sys.version_info[0] == 3:
                line = line.decode("utf8").strip()
            if line:
                Log.d("PROC OUTPUT", line)
            if "Server did start" in line:
                break
        o, _ = recorder_proc.communicate() # it is expected to wait forever here, before i teminate the proc manually
        if sys.version_info[0] == 3:
            o = o.decode("utf8")
        code = my_proc.returncode
        if code not in [0, -15]:
            Log.i("TAG", "My unexpectedly exited:[%s]\n%s" % (code, o))
```
i always got the log message 
```
My unexpectedly exited:[-6]
... [some other process output] ...
```
could anyone give me some tips, why it behaves different?

**Comment by Legorooj** [comment]
@chen-zehua which version of python are you running?

**Comment by chen-zehua** [comment]
> @chen-zehua which version of python are you running?

python 3.7

**Comment by Legorooj** [comment]
Hmm. Try the latest release on PyPI? (4.0)

**Comment by chen-zehua** [comment]
> Hmm. Try the latest release on PyPI? (4.0)

you mean try python 4.0? but many dependencies may not support python 4.0.

**Comment by Legorooj** [comment]
@chen-zehua no - I mean try PyInstaller 4.0
