### ISSUE TITLE
Can't run the .exe file: ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by klienn** [pyinstaller/pyinstaller#4890]
I'm pretty sure i have the module included in the dist folder.
This is the part of the code that have this error (this is the line 7 of the test.py):
```
from PyQt5.QtCore import Qt
```

after running ```pyinstaller test.spec``` and running the ```test.exe``` it gives this error:

```
Traceback (most recent call last):
  File "test.py", line 7, in <module>
ImportError: DLL load failed: The specified procedure could not be found.
[6488] Failed to execute script test
```

Any help will be much appreciated.

**Comment by Legorooj** [comment]
@bjones1

**Comment by bjones1** [comment]
Provide the usual details requested in the issue template: what version of Python, PyInstaller, OS, Qt, etc.

**Comment by klienn** [comment]
@bjones1 . I had python version 3.6 64-bit and solved the problem by uninstalling the python and installing python version 3.8 32-bit. Was it because of the python version that caused the problem?

**Comment by Legorooj** [comment]
@klienn maybe. Note that support for python 3.8 is non-existant at the moment. If it works, great! But we can't offer support for it.

**Comment by Neel125** [comment]
i had the same problem with windows 10 64-bit and python 3.6

**Comment by bzsometest** [comment]
i had the same problem with win1903 64-bit and python 3.7，is only use upx。我也有相同的问题，当前是使用upx。

[11352] LOADER: Running pyiboot01_bootstrap.py
[11352] LOADER: Running pyi_rth_pyqt5.py
[11352] LOADER: Running QmlAndQssMain.py
Traceback (most recent call last):
  File "QmlAndQssMain.py", line 3, in <module>
ImportError: DLL load failed: 参数错误。

**Comment by bwoodsend** [comment]
PyQr breaks if you use UPX. You have to turn it off.
