### ISSUE TITLE
Pyinstaller --distpath broken for Mac.Not making the .app file at -distpath.

### ISSUE THREAD

**Issue by SHAANBHAYA** [pyinstaller/pyinstaller#4892]
While working with Pyinstaller 3.5 and 3.6 (have not worked on older versions),found out that .app is being made in the same place where .spec file is placed.Did some digging and think that the file
osx.py at line number 95 is the problem which is joining the spec file path with dest path .

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```VERSION 3.5 and 3.6```
* Version of Python: 3.5
* Platform: OS X
* Did you also try this on another platform? Does it work there?
N/A

### A minimal example program which shows the error
To simulate the same issue :

- Decompress the files below
[smallexample.zip](https://github.com/pyinstaller/pyinstaller/files/4666539/smallexample.zip)
- pip install -r requirement.txt
- to make spec file :  pyinstaller --noconsole --windowed small.py
-Now run the spec file from outside the smallexmaple folder.
command to run :  `pyinstaller smallexample/small.spec --distpath small_dist/small_dist2/`
The .app file will be made inside the smallexample folder even though the --distpath is provided.

As mentioned above the spec path is being joined with the dest path ,which should not be the case.

**Comment by SHAANBHAYA** [comment]
One way to get around this problem is using the absolute path instead of relative path as the join operation done join the spec path if its absolute .

**Comment by Legorooj** [comment]
@SHAANBHAYA I'll try and replicate this. In theory, a bug like this would show up on other platforms, but it might not.

**Comment by SHAANBHAYA** [comment]
@Legorooj Did you get the time to verify ?

**Comment by Legorooj** [comment]
Yes - I've been unable to replicate on Windows 10. However, windows doens't use the `BUNDLE` class in the spec file so I had to remove that. I'm pretty sure that that is the issue. Could you try figuring out what the issue is exactly? I can help then, but it'd take ages to track this down on non-macOS platforms.

**Comment by Legorooj** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.

**Comment by SHAANBHAYA** [comment]
I am really sorry for the late response .This is not a bug that can not be reproduced on windows as the problem lies in osx.py file ,where we are joining the  spec file path with dest path,which leads to the behavior mentioned above. 
We use pyinstaller for making the executables for both windows and osx and with the same spec files and this happens only in osx.
 Here is the code that i think is causing this  :

`

        for inm, name, typ in self.toc:
            if typ == "EXECUTABLE":
                self.exename = name
                if self.name is None:
                    self.appname = "Mac%s" % (os.path.splitext(inm)[0],)
                    self.name = os.path.join(CONF['specpath'], self.appname + ".app") <--------------Problem lies here.
                else:
                    self.name = os.path.join(CONF['specpath'], self.name)<-----------------------Problem lies here. 
                break
`
As you can see its joining the specpath with the appname and not the dest path.

**Comment by Legorooj** [comment]
@SHAANBHAYA yes it is. Good find. Could @cjakuc take a look at this?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.

**Comment by Legorooj** [comment]
@BoboTiG could you take a look?

**Comment by BoboTiG** [comment]
@Legorooj yes I will 👍

**Comment by BoboTiG** [comment]
OK, issue reproduced. Working on a patch.

**Comment by BoboTiG** [comment]
@SHAANBHAYA Could you install the version and confirm this fixes your issue?
```shell
python -m pip install https://github.com/BoboTiG/pyinstaller/archive/fix-4892-distpath-argument-not-effective-on-macos.zip
```
