### ISSUE TITLE
MatplotlibDeprecationWarning

### ISSUE THREAD

**Issue by YLBFDEV** [pyinstaller/pyinstaller#4894]
mporters.py:623: MatplotlibDeprecationWarning:The MATPLOTLIBDATA environment variable was deprecated in Matplotlib 3.1 and will be removed in 3.3.
-----------------------------------------------------------------------
my environment :
> -- Python 3.8.2
> -- matplotlib      3.2.1
> -- PyInstaller     3.6

It's not working 
`warnings.filterwarnings("ignore", category=mplDeprecation)`

**Comment by Legorooj** [comment]
Duplicate #3959
