### ISSUE TITLE
Signing binary on macOS

### ISSUE THREAD

**Issue by waleedhammam** [pyinstaller/pyinstaller#4896]
I've tried to sign the binary by following https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing
but it's with self-signed certificate. It didn't work on other machines.
then I've tried to sign it with a certificate generated from my apple developer id using xcode it didn't work either on other machines giving this error

![image](https://user-images.githubusercontent.com/10658229/82931683-96586c00-9f87-11ea-9d46-4def3f280c08.png)

- I tried to sign the binary using the following and got this error
![image](https://user-images.githubusercontent.com/10658229/82932105-34e4cd00-9f88-11ea-95f9-607652fc0230.png)
![image](https://user-images.githubusercontent.com/10658229/82931926-ef280480-9f87-11ea-85de-fc6b0b046a1b.png)

- When i checked the signed binary
![image](https://user-images.githubusercontent.com/10658229/82931747-ac662c80-9f87-11ea-87e4-130df67ceb30.png)
![image](https://user-images.githubusercontent.com/10658229/82931754-aff9b380-9f87-11ea-8faa-354732773468.png)

- Could you please provide docs for how to sign and running on other machines

**Comment by Legorooj** [comment]
Yay. This again. Try adding the `--deep` option to the codesign? This apparently has some effect; I don't use apple.

**Comment by waleedhammam** [comment]
> Yay. This again. Try adding the `--deep` option to the codesign? This apparently has some effect; I don't use apple.
> 
> Also see #4629.

I've tried all these options and didn't work with me :(

**Comment by Legorooj** [comment]
Hmm. I don't have an apple... Could @micahflee help if they have a minute?

**Comment by papr** [comment]
This pop-up also appears if the software is signed correctly. You also need to notarize it if you want the pop-up to go away.

**Comment by Legorooj** [comment]
@papr that looks to be helpful. If you have the time could you update our code-signing tutorial in the Wiki?
