### ISSUE TITLE
ability to specify `exe` location when building with --onedir

### ISSUE THREAD

**Issue by tybug** [pyinstaller/pyinstaller#4899]
**Is your feature request related to a problem? Please describe.**
When bundling with `--onefile`, the exe opens slowly. I understand this is because pyinstaller copies everything to a temp folder before running. Because of this I've switched to `--onedir`, which is fine speed-wise, but end users now see the guts of the application and have to search for the exe file. Not ideal.

**Describe the solution you'd like**
I would like a way to bring the exe up a level. That is, if pyinstaller builds my application to `dist/circleguard/internals`, I'd like to have everything but the exe built normally to `dist/circleguard/internals`, and the exe built to `dist/circleguard`. Then the `circleguard` folder would be zipped up and distributed to end users, who would only see two files - an `internals` folder and `circleguard.exe` - upon opening the zip, making it obvious how they should run the application.

**Describe alternatives you've considered**
I've tried using a `.lnk` file for this by leaving the `.exe` in the onedir directory and creating a `.lnk` one directory up which links to it. This works when built locally but the `.lnk` retains its path when zipped and distributed, so the link that worked for me (`c:\Users\tybug\Desktop\circleguard\internals\circleguard.exe`) would not work for anyone else, as they don't have a user named `tybug`.

As is, moving the exe breaks references to the dlls. Is there any way to do what I want currently (moving the exe while preserving dll references)?

**Comment by Legorooj** [comment]
Duplicate #1048. See the latest edit of the main comment - or take "we can't do this ourselves but would happily accept someone else doing the work and adding the feature" as a summary.
