### ISSUE TITLE
Deterministic Freeze

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#490]
**Original date**: 2012/01/11
**Original reporter**: *bwhite AND dappervision DOT  COOM *

Two invocations of pyinstaller appear to produce different results in the frozen executable.  There are instances where it is important to know that the resulting executable is identical to one made in a previous run and an intuitive way of doing that is by having deterministic output.

For example, if you have a set of worker machines that take a frozen python script and run it, you need to know if a change has been made or you need to keep pushing the frozen script and reloading (wasteful).  I haven't had a chance to dig into it but the resulting binary files have the same byte size but different values.  This is probably due to directory listing or dictionary iteration differences somewhere in the code.

**Comment by htgoebel** [comment]
Closing: Too less information, too old.

**Comment by phelixbtc** [comment]
This would be very helpful. The resulting executable looks like it is ordered differently (not in onefile mode). Everything else is relatively easy to match.
