### ISSUE TITLE
Unable to find lib\site-packages\PyQt5\Qt\translations\qtwebengine_locales" when adding binary and data files.

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#4900]
I'm having issues packagine an application using pyqt5. The error is as follows:

Unable to find ...lib\site-packages\PyQt5\Qt\translations\qtwebengine_locales" when adding binary and data files.

I'm using pyqt5 5.14.2 with python 3.7 and I can confirm that the above qtwebengine_locales is indeed not present in that folder. Any suggestions what I can do? thanks

**Comment by bjones1** [comment]
Please provide the info requested in the issue template (OS, PyInstaller version, etc.). Also, how did you install PyQt5 (pip, conda, etc.)?

**Comment by dickreuter** [comment]
122 INFO: PyInstaller: 3.6
122 INFO: Python: 3.7.0 (conda)
122 INFO: Platform: Windows-10-10.0.18362-SP0

**Comment by bjones1** [comment]
Try to pip install PyQt5 and see if that helps -- Conda's install deviates from the PyQt5 wheel; PyInstaller only supports the wheel's layout.

**Comment by bjones1** [comment]
Sorry, missed your previous comment (PyQt5 installed via Pip). For fun, does installing and building from plain Python work (as opposed to Conda's Python)? The CI tests use that and pass.

**Comment by dickreuter** [comment]
yes that seems to solve the problem

**Comment by x011** [comment]
I'm having the same error , but the folder `"C:\Anaconda3\lib\site-packages\PyQt5\Qt\translations\qtwebengine_locales"` exists.
Any idea how to fix this?
