### ISSUE TITLE
Qt Quick Material style messed up after freezing on Linux

### ISSUE THREAD

**Issue by Pathfinder216** [pyinstaller/pyinstaller#4901]
I have a PyQt5/QML application that uses the material style for the UI. When I freeze the application with PyInstaller on Linux, it runs fine, but the material style is messed up. For example, buttons lose their background and lose the highlight on mouse hover. Interestingly, it works fine on Windows 10.

## Context
Python versions: 3.8.0, 3.7.*
PyInstaller versions: 3.6, 4.0.dev0
PyQt5 versions: 5.14.* , 5.13.* , 5.12.0
Platform: Ubuntu 20.04 LTS, 64-bit
Works on Windows 10.

Note: I didn't try every combination of Python version, PyInstaller version, and PyQt5 version listed.

### A minimal example program which shows the error
main.py
```python
import sys

from PyQt5.QtQml import QQmlApplicationEngine
from PyQt5.QtWidgets import QApplication

if __name__ == "__main__":
    args = sys.argv + ["--style", "material"]
    app = QApplication(args)
    engine = QQmlApplicationEngine()

    engine.load("main.qml")

    sys.exit(app.exec_())
```

main.qml
```
import QtQuick 2.14
import QtQuick.Controls 2.14

ApplicationWindow {
    visible: true

    // This doesn't work entirely as expected
    header: TabBar {
        TabButton { text: "A" }
        TabButton { text: "B" }
    }

    // Neither does this
    Button { text: "test" }

    // But this does work as expected
    TextField { y: 50 }
}
```

Note: I had to include `pkg_resources.py2_warn` and `PyQt5.QtQuick` to `hidden-imports`. Also, I did run it in debug mode and looked at the output. Nothing jumped out at me, but I also don't really know what to look for.

**Comment by bjones1** [comment]
It sounds like there are two issues:

1. Missing files
2. Missing imports

Do you need to add the `hidden-imports` on both Windows and Linux, or just Linux?

Missing imports may be fixed by changing:

https://github.com/pyinstaller/pyinstaller/blob/15ecf7474fbb735cc6a2de2db78ae32ba16a5178/PyInstaller/utils/hooks/qt.py#L415

to

```
    "qt5qml":                   (".QtQml",                 "qtdeclarative",    "qmltooling":               (None,                     None,               "scenegraph", "qmltooling", "xcbglintegrations", "egldeviceintegrations"),
),
```

Does this help with the hidden imports?

For the non-working styles, I'm guessing there are some Qt QML-related files that Linux needs. Does reading https://doc.qt.io/qt-5/linux-deployment.html provide any ideas to you? I don't package QML, so I'm not as familiar with it.

**Comment by Pathfinder216** [comment]
So after testing it again, it turns out I don't actually need the `PyQt5.QtQuick` hidden import (for Windows or Linux). I must have accidentally thought that fixed something when I was first getting pyinstaller to work for my project. The `pkg_resources.py2_warn` hidden import might be a Python 3.8 thing, but I do still need that.

I'll take a closer look at that article tomorrow to see if that helps me with the styling issue.

**Comment by Legorooj** [comment]
@Pathfinder216 did you manage to take a closer look?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
