### ISSUE TITLE
incomplete documentation: how to share/use the bundle?

### ISSUE THREAD

**Issue by dianekaplan** [pyinstaller/pyinstaller#4902]
I'm helping out a friend who needs to transform some data in csvs, so I made a little python program called "csv_converter.py"- it takes a csv input file and csv output file and everything's peachy. I want to be able to give them a file they can run on their machine (without necessarily needing python and pandas) so I was so excited to find PyInstaller! The steps to run it are super clear, and according to the docs, it'll make a 'dist' folder where I can "find the bundled app you distribute to your users." Sounds great!

I ran Pyinstaller and I see a 'dist' folder containing a sub-folder with the same of my program 'csv_converter': it contains a bunch of libraries and also a file with the program name (with no file extension, I'm not sure what it is). 

**The key question I don't see anywhere in the docs**: what's the right way to send this bundle to someone to run it?  Am I supposed to zip up the dist folder? (or the folder with my program name?) Or is there supposed to be an independently-runable exe file in there somewhere? 

thanks in advance for your help!

**Comment by Legorooj** [comment]
When building in onedir mode - you are - run `dist/name/name.exe` or the extension for your platform. Make sure to send the whole `name` folder.

Or use `--onefile`. It'll create a single file next to the `name` folder in `dist`. But beware that this is slower to start; it has to decompress everything every run. This can take minutes for large programs.

**Comment by dianekaplan** [comment]
thanks for your quick response!  Okay it sounds like the key file to run will be:  dist/csv_converter/csv_converter

And then I can either send the whole csv_converter folder, or just the file if I use the --onefile argument. Glad to have that clarified!

When I try to run that file from within dist/csv_converter/ (before trying to send anything), it's giving the following error: 
```
Dianes-MacBook-Pro:csv_converter dkaplan$ ./csv_converter -h
Traceback (most recent call last):
  File "site-packages/PyInstaller/loader/rthooks/pyi_rth__tkinter.py", line 30, in <module>
FileNotFoundError: Tcl data directory "/Users/dkaplan/PycharmProjects/chris_csv_converter/src/dist/csv_converter/tcl" not found.
[36637] Failed to execute script pyi_rth__tkinter
```

Have you seen this issue before?

**Comment by Legorooj** [comment]
Yes. Are you using Tkinter? The easiest fix if you are is to use another GUI toolkit. Tk/Tcl is a nightmare on Darwin.

If you're not using Tkinter, which libraries do you import?

**Comment by dianekaplan** [comment]
Ahh- that's good to know. My program has these imports:
import sys, getopt
import pandas as pd

**Comment by Legorooj** [comment]
@dianekaplan PyCharm doesn't pull in other stuff; that's not how the python ecosystem works. Can you try building with `--exclude-module=tkinter`? Assuming you're using python 3. Python 2 needs `Tkinter` - a capital T instead.

**Comment by dianekaplan** [comment]
that was it! THANK YOU SO MUCH! NOW I'M ALL SET!!!!! 
:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D:D
