### ISSUE TITLE
Problems between Cx_freeze and module tkcalendar

### ISSUE THREAD

**Issue by SylvanusMounk** [pyinstaller/pyinstaller#4903]
Hello
First of all I am on windows10 and python 3.8 and I make my executable with cx_freeze.

My issue is the following.
As my application requires the use of the tkcalendar module, so I installed it. In the Python interpreter everything working, but as soon as I create an executable, it doesn't work and the error message is "No module named 'tkinter'"
When I comment on the line from "from tkcalendar import Calendar, DateEntry" everything works fine, but with this module it works more. 
I need help

**Comment by johnthagen** [comment]
This issue tracker is for Pyinstaller. Did you mean to submit this to cx_freeze? https://github.com/anthony-tuininga/cx_Freeze/issues

**Comment by Legorooj** [comment]
Wrong issue tracker :-).

**Comment by SylvanusMounk** [comment]
Ok, I'm sorry! I'm new User.

**Comment by Legorooj** [comment]
File an issue [here](https://github.com/anthony-tuininga/cx_Freeze/issues)
