### ISSUE TITLE
Add setuptools extra_requires for easy --key dependency install

### ISSUE THREAD

**Issue by johnthagen** [pyinstaller/pyinstaller#4904]
Currently the README says: 

https://github.com/pyinstaller/pyinstaller#requirements-and-tested-platforms

> Python:
        - 3.5-3.7
        - tinyaes 1.0+ (only if using bytecode encryption)

Which was updated in #4652.

[`setuptools.extra_requires`](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies) could be used to simplify installing this optional depedency for the user.

This could be done by modifying `setup.py` similar to:

```py
setup(
    ...
    extras_require={
        "encryption":  ["tinyaes>=1.0.0"],
    }
)
```

And then users could install / add to `requirements.txt`:

```bash
$ pip install pyinstaller[encryption]
```

**Comment by Legorooj** [comment]
_Nice idea_. @bjones1 what do you think? Shall I add this?

**Comment by johnthagen** [comment]
Just curious, do you know when a release will be produced with this new `tinyaes` support? Looks really nice for users.

**Comment by Legorooj** [comment]
@johnthagen the plan is the 4.0 milestone. Then we'll release.

**Comment by Legorooj** [comment]
Added in https://github.com/pyinstaller/pyinstaller/commit/15ecf7474fbb735cc6a2de2db78ae32ba16a5178.
