### ISSUE TITLE
ModuleNotFoundError: No module named '_ssl'

### ISSUE THREAD

**Issue by jamestch** [pyinstaller/pyinstaller#4906]
Hi,
I want to make  Executable Package for my django project on windows7.  I did as follows：
pip install pyinstaller
pyi-makespec -D manage.py
pyinstaller manage.spec
But when run “manage.exe runerver”, error is occured：

Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_certifi.py", line 13, in <module>
  File "e:\env\document_manager\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "ssl.py", line 98, in <module>
ModuleNotFoundError: No module named '_ssl'
[19780] Failed to execute script pyi_rth_certifi

**Comment by Legorooj** [comment]
Add `--hidden-import=_ssl` when making the spec file? Does that change anything?

**Comment by jamestch** [comment]
It works,thanks! But I met another problem：
[simpleUI](https://github.com/newpanjing/simpleui/blob/master/doc/en/README_en.md) was used in my project since I want to make my django-admin  simple and firendly. If directly run my django project with "python manage.py runserver", simpleUI  works fine.However when I package my django project with pyinstaller, and then run with "manage.exe runserver", simpleUI did not work, it just shows default admin page of django. no errors were reported.
