### ISSUE TITLE
Building pyinstaller without strip to get all symbols

### ISSUE THREAD

**Issue by AnitaNayak** [pyinstaller/pyinstaller#4915]
Trying to build pyinstaller on s390x platform to debug one conda issue. To investigate further, I am trying to build pyinstaller without strip option. 
Tried to build with below option:
Patched file bootloader/wscript as below:
```
--- a/bootloader/wscript        2020-05-28 09:30:11.469939111 -0700
+++ b/bootloader/wscript        2020-05-28 09:56:45.879692703 -0700
@@ -724,7 +724,7 @@
             includes='zlib')

     # By default strip final executables to make them smaller.
-    features = 'strip'
+    features = ''
     if ctx.env.CC_NAME == 'msvc':
         # Do not strip bootloaders when using MSVC.
         features = ''
```
But with above change getting error `cannot run self or archive` 
```
5186 INFO: checking COLLECT
5187 INFO: Building COLLECT because COLLECT-00.toc is non existent
5187 INFO: Building COLLECT COLLECT-00.toc
5218 INFO: Building COLLECT COLLECT-00.toc completed successfully.
[2154] Cannot open self /opt/zconda/conda-bld/pyinstaller_1591161298185/test_tmp/dist/hello/hello or archive /opt/zconda/conda-bld/pyinstaller_1591161298185/test_tmp/dist/hello/hello.pkg
Tests failed for pyinstaller-3.6-py37_1.tar.bz2 - moving package to /opt/zconda/conda-bld/broken
WARNING:conda_build.build:Tests failed for pyinstaller-3.6-py37_1.tar.bz2 - moving package to /opt/zconda/conda-bld/broken
```
Not able to proceed further. Could any one please help to build pyinstaller without `strip` option, where I can get all symbol information and relocatable executable details.

Thanks in Advance. Appreciate for a quick reply.

**Comment by ravigumm** [comment]
If strip=False is given in spec file, still the same error is seen for the executable.

**Comment by Legorooj** [comment]
s390x is not supported. If you want PyInstaller to support it please submit a PR so we can fix PyInstaller for this platform.

**Comment by AnitaNayak** [comment]
Hi @Legorooj , we just need to build pyinstaller properly without strip enabled. Could you please help with that. Do you mean without `strip` enabled on other linux platform, the issue is not the same?

**Comment by Legorooj** [comment]
> Do you mean without `strip` enabled on other linux platform(x86), the issue is not the seen?

As far as I know. 

> Hi @Legorooj , we just need to build pyinstaller properly without strip enabled to get the symbols to debug further. Could you please help with that.

You'll need to edit the wscript to not use `strip` for your specific platform. That _should_ work, but there are likely other bugs you'll encounter. 

I can't offer much more than that I'm afraid.
