### ISSUE TITLE
google.protobuf

### ISSUE THREAD

**Issue by ScottYueqiang** [pyinstaller/pyinstaller#4918]
sorry, i can not find the hook protobuf file now, is it disabled? looking forward to your answer, thanks.
p.s. my solution is
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('google') + copy_metadata('protobuf')
but still not work
the error msg is ImportError: cannot import name 'descriptor' from 'google.protobuf' (/root/kungfu2/core/build/kfc/google/protobuf/__init__.pyc)

**Comment by Legorooj** [comment]
You can't find the hook because there isn't one. If you want PyInstaller to work out of the box with `google.protobuf` please submit a PR to https://github.com/pyinstaller/pyinstaller-hooks-contrib with the hook.

**Comment by bobatsar** [comment]
The following did help on my side.
https://stackoverflow.com/questions/13862562/google-protocol-buffers-not-found-when-trying-to-freeze-python-app
