### ISSUE TITLE
How can I fix this warning

### ISSUE THREAD

**Issue by JustAnotherNerdHeHeHe** [pyinstaller/pyinstaller#4921]
207260 WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!

Please help Thanks

**Comment by Legorooj** [comment]
Unless your program doesn't work, ignore this warning. I'll reopen if you actually have an error.

**Comment by JustAnotherNerdHeHeHe** [comment]
i have this warning and an utf 8 error encoding warning and no the exe doesnt run but the scrip on anaconda does work sorry didnt answer earlier

**Comment by JustAnotherNerdHeHeHe** [comment]
here are the imports i used if it could help i would really appreciate u helping me  i know some of them are redondent thanks in advance
import tkinter as tk
from tkinter.filedialog import askopenfilename
from tkinter import *
from tkinter.ttk import *
import os
import numpy as np
import torch
import cv2
import pydicom
from PIL import  ImageTk
import PIL
from tkinter import messagebox
import time
import pretrainedmodels
import torch.nn as nn
import torchvision
import albumentations
from collections import OrderedDict
import warnings

**Comment by Legorooj** [comment]
What's the error/warning you're getting?
