### ISSUE TITLE
sqlalchemy.sql.functions.func not found

### ISSUE THREAD

**Issue by JustAnotherNerdHeHeHe** [pyinstaller/pyinstaller#4924]
when i try to import torch and make an .exe with pyinstaller i get this error : 
WARNING: Hidden import "sqlalchemy.sql.functions.func" not found!
please help me

**Comment by Legorooj** [comment]
Does the script run? Does the compiled executable actually run?

**Comment by JustAnotherNerdHeHeHe** [comment]
when i run it in anaconda it does work but i couldnt make the exe file from pyinstaller

**Comment by JustAnotherNerdHeHeHe** [comment]
here are the imports i used if it could help i would really appreciate u helping me  i know some of them are redondent thanks in advance
import tkinter as tk
from tkinter.filedialog import askopenfilename
from tkinter import *
from tkinter.ttk import *
import os
import numpy as np
import torch
import cv2
import pydicom
from PIL import  ImageTk
import PIL
from tkinter import messagebox
import time
import pretrainedmodels
import torch.nn as nn
import torchvision
import albumentations

**Comment by Legorooj** [comment]
What's the error/warning you get?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
