### ISSUE TITLE
pytorch pack error: OSError: Can't get source for <function _rejection_sample as ....>

### ISSUE THREAD

**Issue by ArtyZe** [pyinstaller/pyinstaller#4926]
Hello, when I pack my pytroch project, exe generate successfully, but it occurs errors when run to "import torch". Can you kindly give me some advice?
**Error:**
OSError: Can't get source for <function _rejection_sample at 0x0000000018402D08>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available. Original error: could not get source code

**Enviroments:** windows 7, 
                      torch:   1.5.0+cpu,
                      torchvision:   0.2.2.post3,
                      numpy: 1.18.5

![image](https://user-images.githubusercontent.com/32027268/84013973-39f44400-a9ac-11ea-8cff-f6d14c0c9131.png)

**Comment by Legorooj** [comment]
See #4764 for a hack to fix this temporarily. Hopefully we'll add support for including source files via hooks soon.
