### ISSUE TITLE
Failed to execute script main

### ISSUE THREAD

**Issue by netsys-it** [pyinstaller/pyinstaller#4929]
After pyarmor code i was trying to pyinstaller, but after successful build i got Failed to execute script main

## Context information (for bug reports)
pyinstaller.exe version is 3.6
Python 3.8.0 (tags/v3.8.0:fa919fd, Oct 14 2019, 19:21:23) [MSC v.1916 32 bit (Intel)] on win32
Platform: Windows 10 Home
I need to work this on windows, not other platform.

### A minimal example program which shows the error

```
from pytransform import pyarmor_runtime
pyarmor_runtime()
__pyarmor__(__name__, __file__, b'\x50\x59\x41\x52\x4d\x4...', 1)
```

### Stacktrace / full error message
```
C:\Users\XXXX\Projects\python\dist\dist>main.exe
Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "pytransform\__init__.py", line 340, in pyarmor_runtime
  File "pytransform\__init__.py", line 335, in pyarmor_init
  File "pytransform\__init__.py", line 300, in _load_library
pytransform.PytransformError: Could not find "C:\Users\XXXX\AppData\Local\Temp\_MEI104762\pytransform\platforms\windows\x86\_pytransform.dll"
[15816] Failed to execute script main
```

**Comment by Legorooj** [comment]
How did you pack the executable? Which command did you use?

**Comment by netsys-it** [comment]
pyinstaller.py --onefile main.py

**Comment by Legorooj** [comment]
@netsys-it pinging

**Comment by Legorooj** [comment]
@netsys-it we can't help with this. Please contact the developers of `pyarmor`.

**Comment by netsys-it** [comment]
pyarmor code works well, after pyinstaller not working, thats not problem of pyarmor but pyinstaller...

**Comment by Legorooj** [comment]
What's the error once pyarmor is working properly?
