### ISSUE TITLE
Cannot open self abc or archive abc.pkg when running on another PC

### ISSUE THREAD

**Issue by Shaggun45** [pyinstaller/pyinstaller#4931]
Hello everyone, I am making an exe file from python(.py) using pyinstaller. The code requires connection to SQL database through cx_Oracle. Exe file gets created successfully and runs on my PC properly. However, when I share it with a team member of mine, it does not run on some other PC and gives this error: "cannot open self abc or archive abc.pkg" (abc being the name of exe). It would be very nice if someone could help on the same.

**Comment by Legorooj** [comment]
Which pyinstaller version are you using?

**Comment by htgoebel** [comment]
This looks like not all required files are packages. Please have a look at [Make sure everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly) for tips to find out what is missing.

Closing as there was not answer on a simple wuateion for 6 weeks now, also besic information requested in the bug-template was not given.
