### ISSUE TITLE
PyInstaller + macOS + codesign

### ISSUE THREAD

**Issue by sshah254** [pyinstaller/pyinstaller#4934]
Hi,

I am using a piece of software to flash my ESP8266 (https://github.com/marcelstoer/nodemcu-pyflasher).  The software does not run on macOS and the developer is too busy to help, so I started looking into it.

PyFlasher (PF from now on) is built using PyInstaller.  The latest version has 4 bugs which I fixed on my machine.

The build(.sh) script creates a "one file" executable which is in .app/Contents/MacOS folder.

Of course, PyInstaller unpacks this in /var/tmp somewhere and tries to run the executables - but crashes on my macOS Catalina 10.15.5 because they are not "codesign"ed.

If I rebuild the app by removing the "onefile" option, and codesign all of them with my own generated codesign certificate using the KeyChain, then the code launches properly.

This makes me think that this will be an issue with most of the apps that are built using PyInstaller, on macOS for sure, but sure enough this problem will follow on all the other OSes too.

I am wondering if someone is aware of this issue and is working on a feature.  What is recommended here - https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing - did not work in my case (of course it wouldn't because one is signing the app, not the binaries that the app contains which will be unpacked by PyInstaller when the app is launched; unless I am misunderstanding macOS security).

If not, I am thinking a command line option to specify a "certificate" at build time should work.  Something like

pyinstaller --cert my_cert my_script.py

PyInstaller could then loop through all the executables that it creates (executables and libraries) and have the OS certify each of them before the app is built.

Of course, we run into issues of what a valid cert is, and a cert on my machine would not be acceptable on other machines and all that.

But the point is that wherever the app is build (in this case, on my machine), at least there it is guaranteed to run.

And then developers can get valid certs that hey can use to sign their apps which they can confidently distribute.

If someone can work on this, SUPER!

If I can help, let me know.

Thanks,

SS

**Comment by Legorooj** [comment]
Did you try using the `--deep` option when signing?

**Comment by sshah254** [comment]
Yes, of course.

Thanks,

SS

**Comment by Legorooj** [comment]
@sshah254 hang on a second; I'm confused. Have you gotten the code signing to work manually?

**Comment by sshah254** [comment]
Yes.

If I do not use the "onefile" option, then it creates all the executables
that are needed.  I sign all of them with codesign (with --deep option),
and then the app launches fine.

(I have listed how I got it to work here -
https://github.com/marcelstoer/nodemcu-pyflasher/issues/61 , my id is
sshah254).

With onefile option, it creates just one large executable (ofc, because of
upx).  At runtime it decompresses all these in to a folder in /var/tmp
somewhere and then tries to execute them.  This fails because the
individual files are not codesigned.  I forget the exact error but it is
something like ... looking for image /var/tmp/8s..../Python ... cannot find
valid image ... same path and file.  But the binaries do exist there.

Someone else had a similar problem and they did the same thing.  They
modified the code so that each binary when it is generated is codesigned
and then create the bundle.  This way it works for them.  I got the idea
from them.  Just did not go far enough to create the onefile bundle since
it is not really needed for me.

SS

**Comment by Legorooj** [comment]
@sshah254 right I understand now. You're asking for an option like `--macos-cert=path/to/cert.file` so PyInstaller will auto sign every binary?

**Comment by sshah254** [comment]
Right - before compressing it into a "onefile" executable.

And it should just be a --cert=path/to/cert - not just for macos.

Currently only macos (am pretty sure iOS also does it) checks all binaries,
but down the line all the other oses will also do so - Windows, Linux,
Android, Chrome ... all of them.

SS

**Comment by Legorooj** [comment]
@sshah254 using something generic like `--cert` would be difficult because each OS takes a different certificate and would need to use it at different stages in the build. As it is there's already a lot of work to do something like this for macOS.

Could we have @bjones1 leave an opinion?

**Comment by bjones1** [comment]
Since only Apple requires this, I would only look into signing for MacOS. PR, anyone?

**Comment by sshah254** [comment]
I agree - for now, signing should only be for macOS.  However the command
line parameter could be set as "--cert" as opposed to "--macos-cert".  That
way, we don't have to change it down the line, or add another parameter.

SS

**Comment by bjones1** [comment]
Yes, I agree.

**Comment by dg-chitharthan** [comment]
Yes, I agree too

**Comment by BoboTiG** [comment]
@sshah254 h[ere is my code](https://github.com/nuxeo/nuxeo-drive/blob/f8350079f76bba721a8c7209bd1cc2a2491ae2e8/tools/osx/deploy_ci_agent.sh#L108-L133) that works perfectly, maybe it is not needed to add something to PyInstaller.

**Comment by txoof** [comment]
@BoboTiG 
Just to be clear: are you using `pyinstaller -F myapp.py` which creates exactly one file: `myapp`? 

Or, are you creating a "bundle" that produces a `myapp.app` bundle which includes the executable, an Info.plist and other sub directories?

Does this "Pull-Request Wanted" address this?

In the case of the onefile option (exactly one binary produced) , have you managed to sign **and** notarize the application?  If so, your workflow would be greatly appreciated! 

I referenced this in #4333 with all the details I could think to provide

**Comment by BoboTiG** [comment]
I *think* this may be fixed with #3991 (not yet merged and old but it could be good to check).

**Comment by bwoodsend** [comment]
PyInstaller has codesiging capabilities now (although macOS isn't generally suited to onefile mode - signed or otherwise).
