### ISSUE TITLE
exe. build but cant open

### ISSUE THREAD

**Issue by alanthomass** [pyinstaller/pyinstaller#4936]
hey, i was implementing a tkinter GUI. Just using tkinter import the exe is succefully functioning. But when i import my other libraries and then use pyinstaller, i first encountered an error called maximum recursion depth exeeded.
"c:\program files (x86)\microsoft visual studio\shared\anaconda3_64\lib\ast.py", line 253, in visit return visitor(node)
RecursionError: maximum recursion depth exceeded"

Then using sys command i was able to get rid of the error and succesfully build the exe.

But when i double click the exe or drag it to command prompt.. it opens a new command prompt like screen and the cursur blinks..but the screen remains blank and my gui doesnt open either..

any idea how to solve this issue?

**Comment by Legorooj** [comment]
What command did you use to build the executable?

**Comment by alanthomass** [comment]
Hey, Thanks. All my issues were solved. I created a virtual environment and installed only the necessary packages and ran the file. Recurssion error got solved, as well as my GUI works properly.
