### ISSUE TITLE
Add a hook for pygraphviz

### ISSUE THREAD

**Issue by thekswenson** [pyinstaller/pyinstaller#4938]
**Is your feature request related to a problem? Please describe.**
There does not seem to be support for pygraphviz. The graphviz-related functions for networkx are also effected by this.  The following simple program is not properly bundled, for example.

```
import pygraphviz as pgv

G = pgv.AGraph()
G.add_edge('a', 'b')

G.draw('xdotout.xdot', format='xdot', prog='dot')
```

After packaging with `pyinstaller --noconfirm --windowed --onedir pygraphviztest.py` we get:

```
Traceback (most recent call last):
  File "pygraphviz/agraph.py", line 1321, in _get_prog
  File "pygraphviz/agraph.py", line 1569, in _which
ValueError: No prog dot in path.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "pygraphviztest.py", line 13, in <module>
    G.draw('xdotout.xdot', format='xdot', prog='dot')
  File "pygraphviz/agraph.py", line 1515, in draw
  File "pygraphviz/agraph.py", line 1336, in _run_prog
  File "pygraphviz/agraph.py", line 1323, in _get_prog
ValueError: Program dot not found in path.
[41833] Failed to execute script pygraphviztest
```

**Describe the solution you'd like**
It would be nice to have a hook that properly includes all of the graphviz binaries and dynamic libraries.

**Additional context**
A hook like the following is not sufficient due to the many dependencies of graphviz.

```
binaries=[
          ('/usr/local/bin/dot', '.'),
          ('/usr/local/bin/nop', '.'),
          ('/usr/local/Cellar/graphviz/*/lib/*.dylib', '.'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/*.dylib', 'graphviz'),
         ]

datas=[
       ('/usr/local/Cellar/graphviz/*/lib/graphviz/config6', 'graphviz'),
      ]
```

The dependencies on macOS are numerous:

```
=> brew deps graphviz
cairo
fontconfig
freetype
fribidi
gd
gdbm
gettext
glib
graphite2
gts
harfbuzz
icu4c
jasper
jpeg
libffi
libpng
libtiff
libtool
lzo
netpbm
openssl@1.1
pango
pcre
pixman
python
readline
sqlite
webp
xz
```

So I've been looking for a way to include all of the shared libraries programmatically but am not sure how to do this. I found the function `depend.bindepend.findSystemLibrary`, but did not find a function that does such a recursive crawl of dynamic library dependencies.

**Comment by Legorooj** [comment]
See [here](https://pyinstaller.readthedocs.io/en/latest/hooks.html) for details on the hook utilities. If you get this working, please submit a PR to [this repo](https://github.com/pyinstaller/pyinstaller-hooks-contrib).

**Comment by thekswenson** [comment]
@Legorooj Thanks for the comment. Hi, I've read that document thoroughly, but all the utilities are python module oriented. For example, the function collect_dynamic_libs( 'module-name' ) collects all the dynamic libraries for a python module with the given name.

There is nothing mentioned in that document about collecting dynamic libraries for hidden binary dependencies. In my example pygraphviz depends on graphviz which is a pure C library, which in turn depends on a slew of other C libraries.

The only phrase in that document that may allude to the recursive inclusion of dynamic libraries says 

> Binaries is a special case of datas, in that PyInstaller will check each file to see if it depends on other dynamic libraries.

This makes it sound like pyinstaller does the recursive inclusion automatically, but this doesn't seem to be the case. For example, graphviz depends on libtool, but the libtool dynamic libraries will not be included when I use the above hook to include the graphiz libraries.

Are there utilities that walk the dependencies of the C dynamic libraries?

**Comment by thekswenson** [comment]
I have found the function Dependencies in `depend.bindepend`, and the cli tool `utils/cliutils/bindepend.py`.  Is there no documentation for this?

We'll see how far I can get without help.

**Comment by Legorooj** [comment]
@thekswenson using `PyInstaller.utils.hooks.collect_dynamic_libs` will try to automatically collect all of the dependencies recursively - yes that includes the underlying C libraries. Have you tried using it?

**Comment by Legorooj** [comment]
> ### Additional context
> A hook like the following is not sufficient due to the many dependencies of graphviz.
> ```
> binaries=[
>           ('/usr/local/bin/dot', '.'),
>           ('/usr/local/bin/nop', '.'),
>           ('/usr/local/Cellar/graphviz/*/lib/*.dylib', '.'),
>           ('/usr/local/Cellar/graphviz/*/lib/graphviz/*.dylib', 'graphviz'),
>          ]
> 
> datas=[
>        ('/usr/local/Cellar/graphviz/*/lib/graphviz/config6', 'graphviz'),
>       ]
> ```

Glob patterns aren't valid, which is why this isn't working. The paths need to be absolute, one for each dependency.

**Comment by thekswenson** [comment]
So the wildcard in the basename (e.g. "*.dylib") turned out to be the problem. The wildcard for the directory name is working, and allows flexibility for when the graphviz version will change.

I'm going to try to submit a hook for pygraphviz to the hooks-contrib repo.

**Comment by vmiklos** [comment]
@thekswenson did you submit that PR at the end? I just ran into this problem when trying to bundle graphviz into the ged2dot msi / dmg installers. Thanks.

**Comment by thekswenson** [comment]
> @thekswenson did you submit that PR at the end? I just ran into this problem when trying to bundle graphviz into the ged2dot msi / dmg installers. Thanks.

I actually don't know how to submit a PR. You're welcome to. This is the hook file that worked for me:

(hook-pygraphviz.py)
```
# pygraphviz (and parts of networkx) depends on executable programs like dot.
# Including just this binary is not sufficient since pyinstaller does not find
# the libraries in lib/graphviz/, nor the config file.

binaries=[
          ('/usr/local/bin/dot', '.'),
          ('/usr/local/bin/nop', '.'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_pango.6.dylib', 'graphviz'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_core.6.dylib', 'graphviz'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_dot_layout.6.dylib', 'graphviz'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_core.6.dylib', 'graphviz'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_gd.6.dylib', 'graphviz'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_neato_layout.6.dylib', 'graphviz'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_quartz.6.dylib', 'graphviz'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_visio.6.dylib', 'graphviz'),
          ('/usr/local/Cellar/graphviz/*/lib/graphviz/libgvplugin_webp.6.dylib', 'graphviz'),
         ]

datas=[
       ('/usr/local/Cellar/graphviz/*/lib/graphviz/config6', 'graphviz'),
      ]
```

**Comment by vmiklos** [comment]
Thanks! Submitting a PR is easy: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request

Though I imagine that first you'll have to generalize the above a bit: the user may not have dot from brew and also may not be on macOS. If I get around to do this follow-up improvement and submit a PR, I'll comment here. Thanks again for the config hint, I imagine that's what I missed when I tried this in the past and didn't work for me.

**Comment by vmiklos** [comment]
FWIW I so far use https://github.com/vmiklos/ged2dot/blob/e3926270eecb7b6cf84f8951ed5b73baecce6e03/tools/pack.py#L25-L79, which is far from ideal, but does work. It may happen that the --add-binary and --add-data cmdline switches are not the same as the above hook, but at least with the cmdline switches the recursive bundling didn't work for me, so I added all deps based on the above list. I think the Windows part is reasonably clean, the macOS part is quite ugly...

**Comment by vmiklos** [comment]
Figured out at least, PR is here: https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/86
