### ISSUE TITLE
no module named 'yapf'

### ISSUE THREAD

**Issue by wangwenchao-job** [pyinstaller/pyinstaller#4939]
## Environment and related versions
Ubuntu 18.04
python 3.6.5
pyinstaller 3.5
mmcv 
mmdetection 1.2
yapf 0.30.0

## Main problem
```
"No module named yapf" is reported during program execution
```

## Related attempts
First of all, this module is determined to exist, and can be used normally in pycharm.
```
Name: yapf
Version: 0.30.0
Summary: A formatter for Python code.
Home-page: UNKNOWN
Author: Google Inc.
Author-email: None
License: Apache License, Version 2.0
Location: /home/jc/anaconda3/envs/tf-gpu/lib/python3.6/site-packages
Requires: 
Required-by: mmcv
```

I know that --hidden-import can import modules, so I modified the spec file：
```
hiddenimports=['addict','yapf'],
```
But it has no effect.

 Error reporting when compiling with spec file“ Error:can not find hidden import yapf” 

I find the path of yapf in the virtual environment and index it with - P. the compilation instructions are as follows：
```
pyinstaller my.spec -p=the_dir_of_yapf
```
 But it still doesn't work .

Is there any solution? thank you very much！

**Comment by Legorooj** [comment]
Please upgrade PyInstaller and make sure that you're using the correct environment. You need to install PyInstaller in the same environment that `yapf` is installed in.

**Comment by ScarlettCharlie** [comment]
> Please upgrade PyInstaller and make sure that you're using the correct environment. You need to install PyInstaller in the same environment that `yapf` is installed in.

I have the same issue and the 'lost' module is RIGHT WHERE Pyinstaller was installed.
Making the environment right poses no effect on the result and there should be an effective answer.
