### ISSUE TITLE
Recursive process spawn with asyncio\aiohttp

### ISSUE THREAD

**Issue by koutoftimer** [pyinstaller/pyinstaller#4942]
## Description of the issue

When I'm running script with `python script.py` command, recieving expected behavior. Running bundled `script.exe` file causes infinite process spawn (IMHO fork but I haven't verified that).

External dependency: `aiohttp==3.6.2`

## Context information (for bug reports)

* `pyinstaller --version`: ```3.6```
* `python --version`: ```Python 3.7.3```
* Platform: Windows (Russian)
* Did you also try this on another platform? Does it work there? - Haven't tried.

### A minimal example program which shows the error

```python
import asyncio
import multiprocessing as mp

import aiohttp


async def main():
    async with aiohttp.ClientSession() as session:
        async with session.ws_connect('wss://ws.bitstamp.net/') as ws:
            async for msg in ws:
                pass

    
class WebSocketProcess(mp.Process):
    def run(self):
        loop = asyncio.get_event_loop()
        loop.create_task(main())
        loop.run_forever()
        loop.close()


if __name__ == '__main__':
    WebSocketProcess(daemon=True).start()
    while True:
        pass
```

**Comment by htgoebel** [comment]
Please follow https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing
