### ISSUE TITLE
Pyinstaller with UPX causes a VCRUNTIME140.dll malfunction

### ISSUE THREAD

**Issue by zhou013** [pyinstaller/pyinstaller#4943]
## Description of the issue
I copied upx.exe under Python38 folder and then run pyinstaller to build exe file for my project with command pyinstaller -i ./pic/Logo.ico --version-file file_version_info.txt --uac-admin APCStart.py, then I run the exe file in ./dist/APCStart/. After that the computer shows me an error that tells me vcruntime140.dll does not work properly. After I replace the vcruntime140.dll with the one under Python38 folder, the program works properly. My UPX version is upx-3.96-win64. I tried upx-3.96-win32, and had a same result.

## Context information (for bug reports)

* Output of `pyinstaller --version`: 3.6
* Version of Python: 3.8.3
* Platform: Windows 10 Pro
* Did you also try this on another platform? Does it work there?
No, I only test on Windows 10 Pro

**Comment by Legorooj** [comment]
Please contact the UPX developers. If the executable PyInstaller generates when uncompressed works, then we don't offer support for UPX errors.
