### ISSUE TITLE
HELP:"ImportError: unable to find Qt5Core.dll on PATH"

### ISSUE THREAD

**Issue by GanAH** [pyinstaller/pyinstaller#4948]
>"ImportError: unable to find Qt5Core.dll on PATH"

I try this code to solve the problem, and it work fine on my computer. But the problem recurred on other computers running in the same environment.
```py
if hasattr(sys, 'frozen'):
    os.environ['PATH'] = sys._MEIPASS + ";" + os.environ['PATH']
```

**Comment by Legorooj** [comment]
@GanAH what's the full error?

**Comment by GanAH** [comment]
> @GanAH what's the full error?

See the figure for the complete error message：
![image](https://user-images.githubusercontent.com/48412553/85934970-2b4edc00-b91d-11ea-9f0b-cb1d6f7c9d84.png)

<br>At the same time, I sorted out the common error reporting：
`python
λ XXXXXX.exe
Traceback (most recent call last):
  File "xxxxxx\ui.py", line 4, in <module>
  File "c:\users\remib\.virtualenvs\xxxxxxx-w7udp1ct\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
    exec(bytecode, module.__dict__)
  File "site-packages\PyQt5\__init__.py", line 41, in <module>
  File "site-packages\PyQt5\__init__.py", line 33, in find_qt
ImportError: unable to find Qt5Core.dll on PATH
[12876] Failed to execute script ui
`
<br>
I have solved the problem. After packaging with pyinstaller, the .dll file of PyQt5 will not be collected under project/PyQt5/bin. Is the latest version supported?

**Comment by Legorooj** [comment]
@GanAH what version of PyQt and PyInstaller are you using?

**Comment by GanAH** [comment]
> @GanAH what version of PyQt and PyInstaller are you using?
the version of PyQt is 5.13.0

**Comment by Legorooj** [comment]
@GanAH and the version of PyInstaller? What's that?
