### ISSUE TITLE
Libraries under /lib/x86_64-linux-gnu/ on Ubuntu 18.04 included with executable

### ISSUE THREAD

**Issue by lovleshmalik** [pyinstaller/pyinstaller#4951]
As per Pyinstaller [documentation](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#:~:text=PyInstaller%20reads%20a%20Python%20script,including%20the%20active%20Python%20interpreter!&text=They%20do%20not%20need%20to,of%20Python%20or%20any%20modules.), 
"PyInstaller does not include libraries that should exist in any installation of this OS. For example in GNU/Linux, it does not bundle any file from /lib or /usr/lib, assuming these will be found in every system."

However, on Ubuntu 18.04, this path also contains standard libraries , "/lib/x86_64-linux-gnu/".
Is there a reason why they are not excluded?
Also, is there a way to exclude them when making the executable?

**Comment by Legorooj** [comment]
@lovleshmalik you've only given half of the issue context. What's the problem, log messages, error messages etc.

**Comment by lovleshmalik** [comment]
@Legorooj 
I am using Python: 3.6.9, PyInstaller: 3.6, Platform: Linux-4.15.0-1034-aws-x86_64-with-Ubuntu-18.04-bionic

I have a requirement of updating Ubuntu's packages using apt-get command along with performing some other tasks. I am using PyInstaller to achieve this.
Pyinstaller makes an executable for me. Also I noticed that it brings a lot of .so files in the same directory where executable is kept. (one of the .so is libuuid.so from "/lib/x86_64-linux-gnu/" )
When I am updating packages using this executable, my bootloader is also updated. In ubuntu when a new bootloader is updated, its corresponding initrd image is also generated in /boot/ directory.
The problem is that this initrd image picks the libuuid.so from the directory where executable is kept and not from the standard location "/lib/x86_64-linux-gnu/".
Here is the output from the command :
>>**lsinitramfs /boot/initrd.img-5.3.0-1023-aws | grep uuid**
Output : home/ubuntu/dist/exec/libuuid.so.1
This results in machine unable to reboot itself as when rebooting it tries to pick the dependency from standard location, which in this case is not present.
So, I was looking for a way to not include standard libraries when making Pyinstaller executable.

**Comment by Legorooj** [comment]
Ah I think I understand. You'll need @htgoebel's help with this.

**Comment by Jmennius** [comment]
I think I might also be affected - saw yesterday libGL*.so and other stuff in the application library directory (did not investigate).

**Comment by Legorooj** [comment]
@htgoebel

**Comment by khourig** [comment]
I'm on Centos 7 and I'm building for internal company use on other Centos 7 machines. I see a bunch of `/lib64/*.so` files being included. I would like to omit those because they will exist on the target machines.

**Comment by Jmennius** [comment]
Stumbled into it again, I think I won't be able to ignore it anymore :smile:

I've peeked into the code, and it appears that there is an exclude list in [depend/dylib.py](https://github.com/pyinstaller/pyinstaller/blob/5fc8babbe4e586f19e4d41f8634fa55650928e99/PyInstaller/depend/dylib.py#L114), and looks like it was not revised in a long time.
Maybe it's time we revise it or even make it extensible (there are a lot of libraries one may want to exclude).
From my point of view, `libEGL`, `libGLX` and `libdrm` are to be excluded in addition to existing libraries; `libGLdispatch` is also a candidate.

**Comment by htgoebel** [comment]
@Jmennius 
> exclude list in depend/dylib.py, and looks like it was not revised in a long time.

Yes, this is the place where libraries are removed..

> Maybe it's time we revise it

Yes. please provide a pull-request.

> even make it extensible

Ideas fr how to do this ar very welcome.

**Comment by Jmennius** [comment]
@htgoebel I've opened a PR that removes specific libraries that I had an issue with and a few others that usually come along.
So I've (to my best knowledge) covered graphical stack, but the issue in general stands I believe.

**Comment by Legorooj** [comment]
#5058 @htgoebel
