### ISSUE TITLE
error happen when import CLR

### ISSUE THREAD

**Issue by kkswbq** [pyinstaller/pyinstaller#4953]
Hi   i have meet a issue when import CLR
```
Unhandled Exception: System.Reflection.TargetInvocationException: 
Exception has been thrown by the target of an invocation. ---> 
System.AccessViolationException: Attempted to read or write protected memory. 
This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyObject_GetAttrString(IntPtr pointer, String name)
   at Python.Runtime.Runtime.InitializePlatformData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.initclr()
```
```
# -*- coding: utf-8 -*-
#!/usr/bin/python

import clr
print ("test")
```
```
52 INFO: PyInstaller: 3.0
53 INFO: Python: 2.7.15
55 INFO: Platform: Windows-10-10.0.17763
55 INFO: ""just remove path infor""
140 INFO: UPX is available.
141 INFO: Extending PYTHONPATH with ""just remove path infor""
141 INFO: checking Analysis
141 INFO: Building Analysis because out00-Analysis.toc is non existent
141 INFO: Initializing module dependency graph...
145 INFO: Initializing module graph hooks...
206 INFO: running Analysis out00-Analysis.toc
210 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
334 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
335 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
336 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
336 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_accded0fe1dd960c.manifest
460 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9518_none ...
461 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_08e07c8fa840efbe.manifest
463 INFO: Searching for file msvcr90.dll
463 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_08e07c8fa840efbe\msvcr90.dll
464 INFO: Searching for file msvcp90.dll
464 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_08e07c8fa840efbe\msvcp90.dll
467 INFO: Searching for file msvcm90.dll
467 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_08e07c8fa840efbe\msvcm90.dll
584 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
585 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
586 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
588 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_accded0fe1dd960c.manifest
588 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9518)
"just remove path infor"
743 INFO: Looking for import hooks ...
746 INFO: Processing hook   hook-encodings.py
5296 INFO: Processing hook   hook-clr.py
5309 INFO: Looking for ctypes DLLs
5309 INFO: Analyzing run-time hooks ...
5315 INFO: Looking for dynamic libraries
5407 INFO: Looking for eggs
5407 INFO: Using Python library C:\WINDOWS\system32\python27.dll
5410 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9518), publicKeyToken=u'1fc8b3b9a1e18e3b')]
5414 INFO: Warnings written to "just remove path infor"
5417 INFO: checking PYZ
5418 INFO: Building PYZ because out00-PYZ.toc is non existent
5420 INFO: Building PYZ (ZlibArchive) "just remove path infor"
5530 INFO: checking PKG
5532 INFO: Building PKG because out00-PKG.toc is non existent
5532 INFO: Building PKG (CArchive) out00-PKG.pkg
5565 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9518)
5743 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
5743 INFO: checking EXE
5744 INFO: Building EXE because out00-EXE.toc is non existent
5746 INFO: Building EXE from out00-EXE.toc
5750 INFO: Appending archive to EXE
```

thanks
BQ

**Comment by Legorooj** [comment]
Please upgrade PyInstaller. You're 5 years out of date. You can `pip install -U pyinstaller` to upgrade.

**Comment by kkswbq** [comment]
Hi Legorooj,
 Many thanks, i have updated pyinstaller tools. but issue still happen. What else things i can test.

nhandled Exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyObject_GetAttrString(IntPtr pointer, String name)
   at Python.Runtime.Runtime.InitializePlatformData()
   at Python.Runtime.Runtime.Initialize(Boolean initSigs)
   at Python.Runtime.PythonEngine.Initialize(IEnumerable`1 args, Boolean setSysArgv, Boolean initSigs)
   at Python.Runtime.PythonEngine.InitExt()
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.RuntimeType.InvokeMember(String name, BindingFlags bindingFlags, Binder binder, Object target, Object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, String[] namedParams)
   at clrModule.initclr()

//log pyinstaller.
109 INFO: PyInstaller: 3.6
111 INFO: Python: 2.7.15
112 INFO: Platform: Windows-10-10.0.17763
115 INFO: wrote C:\work\important_\tool_\grep_txt\main_grep.spec
221 INFO: UPX is available.
223 INFO: Extending PYTHONPATH with paths
['C:\\work\\important_\\tool_\\grep_txt',
 'C:\\work\\important_\\tool_\\grep_txt']
223 INFO: checking Analysis
224 INFO: Building Analysis because Analysis-00.toc is non existent
224 INFO: Initializing module dependency graph...
229 INFO: Caching module graph hooks...
238 INFO: Caching module dependency graph...
251 INFO: running Analysis Analysis-00.toc
256 INFO: Adding Microsoft.VC90.CRT to dependent assemblies of final executable
  required by c:\python27\python.exe
393 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
395 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
396 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
397 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_accded0fe1dd960c.manifest
525 INFO: Searching for assembly amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.30729.9518_none ...
526 INFO: Found manifest C:\WINDOWS\WinSxS\Manifests\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_08e07c8fa840efbe.manifest
528 INFO: Searching for file msvcr90.dll
529 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_08e07c8fa840efbe\msvcr90.dll
532 INFO: Searching for file msvcp90.dll
533 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_08e07c8fa840efbe\msvcp90.dll
533 INFO: Searching for file msvcm90.dll
534 INFO: Found file C:\WINDOWS\WinSxS\amd64_microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_08e07c8fa840efbe\msvcm90.dll
703 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.1_none_3da38fdebd0e6822.manifest
704 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.4148_none_acd0e4ffe1daef0a.manifest
706 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.6161_none_acd388d7e1d8689f.manifest
707 INFO: Found C:\WINDOWS\WinSxS\Manifests\amd64_policy.9.0.microsoft.vc90.crt_1fc8b3b9a1e18e3b_9.0.30729.9518_none_accded0fe1dd960c.manifest
708 INFO: Adding redirect Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9518)
822 INFO: Analyzing C:\work\important_\tool_\grep_txt\main_grep.py
896 INFO: Processing module hooks...
896 INFO: Loading module hook "hook-encodings.py"...
6226 INFO: Loading module hook "hook-clr.py"...
6237 INFO: Looking for ctypes DLLs
6238 INFO: Analyzing run-time hooks ...
6245 INFO: Looking for dynamic libraries
6338 INFO: Looking for eggs
6338 INFO: Using Python library C:\WINDOWS\system32\python27.dll
6338 INFO: Found binding redirects:
[BindingRedirect(name=u'Microsoft.VC90.CRT', language=None, arch=u'amd64', oldVersion=(9, 0, 21022, 8), newVersion=(9, 0, 30729, 9518), publicKeyToken=u'1fc8b3b9a1e18e3b')]
6342 INFO: Warnings written to C:\work\important_\tool_\grep_txt\build\main_grep\warn-main_grep.txt
6369 INFO: Graph cross-reference written to C:\work\important_\tool_\grep_txt\build\main_grep\xref-main_grep.html
6408 INFO: checking PYZ
6408 INFO: Building PYZ because PYZ-00.toc is non existent
6409 INFO: Building PYZ (ZlibArchive) C:\work\important_\tool_\grep_txt\build\main_grep\PYZ-00.pyz
6645 INFO: Building PYZ (ZlibArchive) C:\work\important_\tool_\grep_txt\build\main_grep\PYZ-00.pyz completed successfully.
6678 INFO: checking PKG
6678 INFO: Building PKG because PKG-00.toc is non existent
6679 INFO: Building PKG (CArchive) PKG-00.pkg
6708 INFO: Redirecting Microsoft.VC90.CRT version (9, 0, 21022, 8) -> (9, 0, 30729, 9518)
6875 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
6883 INFO: Bootloader c:\python27\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
6883 INFO: checking EXE
6884 INFO: Building EXE because EXE-00.toc is non existent
6884 INFO: Building EXE from EXE-00.toc
6886 INFO: Appending archive to EXE C:\work\important_\tool_\grep_txt\dist\main_grep.exe
6917 INFO: Building EXE from EXE-00.toc completed successfully.

thanks
BQ

**Comment by kkswbq** [comment]
need platform .

**Comment by rqx110** [comment]
face the same error

**Comment by MostafaSoliman** [comment]
Same issue here

**Comment by Legorooj** [comment]
Please open a new issue.
