### ISSUE TITLE
Smart _MEIxxxxxx

### ISSUE THREAD

**Issue by keelung-yang** [pyinstaller/pyinstaller#4957]
Can we reuse _MEIxxxxxx to avoid extracting repeatly?
And then start one-file app quickly without extracting -- almost as quick as one-folder app.

**Comment by bufemc** [comment]
same idea here, by using either the --runtime-tmpdir or a new option like --runtime-permanent-extractdir (too long name I know, just to explain the issue), see also my issue: https://github.com/pyinstaller/pyinstaller/issues/4994

with this different behavior:
- on start check if files are already extracted, then skip extraction, otherwise extract files (once)
- do NOT delete the files after execution

**Comment by Legorooj** [comment]
I'm looking into a few ideas to see if this is possible for the devs to implement, or whether this will be such a lot of work that it'll need a PR from someone else.

**Comment by htgoebel** [comment]
To implement such a feature, the bootloader would need to search TMP for all _MEIxxxxxx directories, create a list of all files there, calculate checksums of these files and then compare it to checksums contained in the executable. This has to be repeated for every _MEIxxxxxx directory. Also the _MEIxxxxxx would need to be kept after terminating the program, which is bad style (never leave litter behind).

Also I don't know about a single self-extracting archive tool supporting such things.

IMHO this should not be implemented, but closes as "won't fix".

**Comment by keelung-yang** [comment]
@htgoebel How about use _MEI_SHA1_OF_ONE_FILE? then bootloader only need to calculate sha1 checksum of itself.

**Comment by bufemc** [comment]
Feels like nobody read my issue and ideas in it, so I try again in short:

Instead of a random dir, extract in a specified one, e.g. by a given parameter. Sha1 is good enough to prevent re-extracting IMHO.

The feature not to re-extract always and waste time is wished since years somehow (just use Google), please do not again just close it.

**Comment by simaoafonso-pwt** [comment]
Why not build using the `--onedir` method then? You can create a setup file using InnoScript or similar to install the folder, and you get the best of both worlds:
- Run from the extracted folder, no performance loss
- Single File distribution
- No spurious antivirus deleting the temporary folder

**Comment by keelung-yang** [comment]
@simaoafonso-pwt It's not portable(copy & run) from the view of end users, even though it's portable actually.

**Comment by simaoafonso-pwt** [comment]
There's always [`--runtime-tmpdir`](https://pyinstaller.readthedocs.io/en/latest/usage.html#rarely-used-special-options)...

**Comment by htgoebel** [comment]
> Instead of a random dir, extract in a specified one, e.g. by a given parameter

As others already mentioned, there is `--runtime-tmpdir` and there is `--onedir` mode.  Please explain why these two options so not fir your needs.

**Comment by keelung-yang** [comment]
@htgoebel @simaoafonso-pwt 
Ok then. If I run app N times, it extract N times with same files, even if `--runtime-tmpdir`

WHAT I WANT TO DO IS: run N times, extract ONLY ONE time.

`--onedir` show too many files to end users, its clear and simple if there is only one file.

**Comment by simaoafonso-pwt** [comment]
> WHAT I WANT TO DO IS: run N times, extract ONLY ONE time.

Build with `--onedir` and distribute that in a zip.

> --onedir show too many files to end users, its clear and simple if there is only one file.

Make an installer or self-extracting ZIP file, if the user is too confused by too many files on a folder, that allows to create a shortcut on the Desktop.

---

Yet another option:
- Build with `--onedir`, on a subfolder
- Make a shortcut to the "main" executable

Something like:

```
- folder/ # contents of `--onedir`
- shortcut.lnk # link to folder/main.exe
```

That way, the user only sees a folder and a thing to double click, and it's still portable.

**Comment by keelung-yang** [comment]
@htgoebel Why not just behaving as .pyc? just add a bool argument `--runtime-cached`. 
If  `_MEI_SHA1_OF_APP` existed then skip extracting, run `_MEI_SHA1_OF_APP/app` directly, or extracting firstly.

@simaoafonso-pwt All you mentioned methods either need additional work for developers or end users, or make things more complicated. There is a simple way as described above.

**Comment by htgoebel** [comment]
So you want to hide these many files from the user?!

This could be solved if one-dir mode could have all files in a sib-dir jsut beside the .exe. Would this suite your needs?

**Comment by keelung-yang** [comment]
@htgoebel Sorry for my poor english. Let's make it clear:
![image](https://user-images.githubusercontent.com/20385450/91558848-993d7100-e969-11ea-9459-b999d936d5b0.png)

**Comment by htgoebel** [comment]
To be frank, this idea IMO is stupid. It is nuch too complicated to make right, it is prone to many kinds of security attacks, (esp. DLL injection), and the same result can be achieved much easier, as proposed in #2702:

You can get the same result if one-dir is able to have te files in a sub-directory:
```
$ pyisntalelr app.py
$ tree
dist/app
├── app.exe
└── _files/
    ├── base_library.zip
    ├──  python37.dll
    ├──  …
```

**Comment by wlievens** [comment]
Is it possible to build a one-dir with everything except the exe in a subdirectory?

**Comment by bwoodsend** [comment]
No, but we would like to. See #5575.
