### ISSUE TITLE
How to add .kv file to assembly?

### ISSUE THREAD

**Issue by UUSR** [pyinstaller/pyinstaller#4958]
add to the file .spec as indicated in the documentation:
`a = Analysis(...`
     `datas=[ ('src/pong.kv', '.') ],`
    `...`
     `)`
I'm building an application: `PyInstaller file-single.spec`
however, the pong.kv file does not get into the assembly.
![Screenshot_1](https://user-images.githubusercontent.com/17599033/86121995-4a916900-bad7-11ea-89c3-dec691ef5f2b.png)

**Comment by Legorooj** [comment]
Actually it does get into the final app; you're probably just accessing it incorrectly. See [here](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file).
