### ISSUE TITLE
PyInstaller pkg_resources.DistributionNotFound: Tendo

### ISSUE THREAD

**Issue by HJB20** [pyinstaller/pyinstaller#4960]
Hi I've tried to implement a hook using examples in other threads but still running in to the same error message

This is the library is the cause of it all
`from tendo import singleton`

This is the error message I always received (before using hooks and after)
pkg_resources.DistributionNotFound: The 'tendo' distribution was not found and is required by the application

Created a hook and hook directory
```
myscript.py
hooks
     - hook-tendo.py (also tried hook-tendo.singleton.py)
```

My hook file is 
```
from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = collect_all('tendo')
```
have also tried collect_all('tendo.singleton')

pyinstaller --F --noupx --nowindowed --additional-hooks-dir=hooks myscript.py

**Comment by Legorooj** [comment]
Just to check, this is a typo?:

> Created a hook and hook directory
> ```
> myscript.py
> hook
>      - hook-tendo.py (also tried hook-tendo.singleton.py)
> ```

You've got the hook directory called `hook` in this, but you're passing `--additional-hooks-dir=hooks`, which is a different directory name.

**Comment by HJB20** [comment]
sorry typo, "hooks" is what it is in both places

myscript.py
hooks
     - hook-tendo.py (also tried hook-tendo.singleton.py)

**Comment by Legorooj** [comment]
@HJB20 I thought it might be. What's the output of the `pyinstaller --F --noupx --nowindowed --additional-hooks-dir=hooks myscript.py` command?

**Comment by HJB20** [comment]
Sorry for the delay in reply just wanted to troubleshoot one last thing in order to not waste your time

I was originally doing it on a network drive s:
Just tried on local c: and it worked (this is where the python folder is stored too)
Went back to trying on s: and **it worked**

Ability to reproduce error: 0, not quite sure what happened here. xD

Off to test if the Tendo functionality is working as expected

**Comment by Legorooj** [comment]
@HJB20 excellent! I had a feeling it would be some cache error or similar - something like this. I'll close; if this reoccurs or anything just comment and I'll repopen.
