### ISSUE TITLE
Html test Runner Reports Not Generated If running with  exe

### ISSUE THREAD

**Issue by LP-Codes** [pyinstaller/pyinstaller#4967]
Please use the mailing list see <http://www.pyinstaller.org/support.html#mailing-list> for details.

Posts that are not a bug report or a feature/enhancement request will not be addressed on this issue tracker, but closed.
Hello guys Kindly help me , i have generated a exe file which implements some unit-test cases & report is generated in html the script runs as expected when running via console but when i have created exe usin Pyinstaller script runs fine upto unittest cases execution but i get error at html report generation i am confused how to fix this     error --IOError: [Errno 2] No such file or directory: ] No such file or directory: 'C:\\Users\\pc1\\AppData\\Local\\Temp\\_MEI24~1\\HtmlTestRunner\\template\\report_template.html'

    """
    import os
    import sys
    import time
    import unittest
    
    import HtmlTestRunner
    
    
    
    class Test_J(unittest.TestCase):
    
        def test_Key1(self):
            
            pass
    
        def test_Key2(self):
            pass
    
    
    
           
          
    
        def test_Key3r(self):
    
            pass
    
      
    if __name__ == '__main__':
    
        try:
            output1 = 'D:\\Reports'
            title1 = ' Testing Ver-1.0'
            name1 = ' Testing '
    
            unittest.main(testRunner=HtmlTestRunner.HTMLTestRunner(output=output1, report_title=title1,
                                                                   report_name=name1), exit=False,
                          verbosity=2)
    
      
            
        else:
    
            print("Thank You Tests Are Finished - Report Generated  )
    
          
            raw_input("Press Enter To Exit")

**Comment by Legorooj** [comment]
You need to write a hook for `HtmlTestRunner`. Please see the docs for more information.

**Comment by LP-Codes** [comment]
> You need to write a hook for `HtmlTestRunner`. Please see the docs for more information.

Hello Lego ,

Thanks For replying On Github Can you kindly assist me in writing hook for HTML test runner i have no idea what to put in  hook 
Below is what i am trying  but it fails

from PyInstaller.utils.hooks import collect_submodules

hiddenimports = collect_submodules('Html-Testrunner')

Actually i have generated a exe file which implements some unit-test cases & report is generated in html the script runs as expected when running via console but when i have created exe usin Pyinstaller script runs fine upto unittest cases execution but i get error at html report generation i am confused how to fix this error --IOError: [Errno 2] No such file or directory: ] No such file or directory: 'C:\Users\pc1\AppData\Local\Temp\_MEI24~1\HtmlTestRunner\template\report_template.html'
inside html in lib/sitepackages i can see there i a html template present but how to use with hook i have no idea please assist

**Comment by Legorooj** [comment]
Like I said in the email you sent me, try using the following contents for the hook:
```python
from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files('HtmlTestRunner')
```

And make sure to call the hook `hook-HtmlTestRunner.py`.
