### ISSUE TITLE
 importlib.import_module missing file

### ISSUE THREAD

**Issue by Mradr** [pyinstaller/pyinstaller#4973]
Looking to use pyinstaller and importlib.import_module. It looks like its not finding the correct path for the imports - is there a way to set a path or what is the correct method to make it work? I see a few others on the topic - but I am a bit lost on what the correct method is. I have a folder full of scripts and they dynamically load, change, remove and add them selves.

**Comment by Legorooj** [comment]
PyInstaller can't detect uses of `importlib`, `imp`, or any method that doesn't use the standard `from ... import ...` or `import ...` syntax.

**Comment by Mradr** [comment]
What's the difference between --hidden-import and --additional-hooks-dir in this case?
