### ISSUE TITLE
[ValueError] time data '2020-07-06 10:52:00' does not match format '%Y-%m-%d %X'

### ISSUE THREAD

**Issue by chen-zehua** [pyinstaller/pyinstaller#4974]
environment info:
> os: macos 10.14.5
> python version: 3.7.0

the code runnings well when debug in pycharm ide:
```
time.strptime(time_str, "%Y-%m-%d %X")
```
but after i use pyinstaller frozen the program, it always raise the error below:
```
[ValueError] time data '2020-07-06 10:52:00' does not match format '%Y-%m-%d %X'
  File "_strptime.py", line 571, in _strptime_time
  File "_strptime.py", line 359, in _strptime
```
could anyone gives me some tips?
i have tryed [this](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-set-default-language-and-encoding)  to set the locale, but it is not a solution.

**Comment by bwoodsend** [comment]
What do you get if you run the following (both in pycharm and PyInstaller)?

```
import locale
print(locale.getlocale(locale.LC_TIME))
```

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
