### ISSUE TITLE
productVersionLS and fileVersionLS: 2279604224 (0x87e00000) only in Azure DevOps CI causes  struct.error: argument out of range.

### ISSUE THREAD

**Issue by FrancescElies** [pyinstaller/pyinstaller#4975]
## Description of the issue
We have been using pyinstaller v3.6 for months without isssues in CI, suddenly without any code changes CI broke with `struct.error: argument out of range`.

I tried:
 - `4.0.dev0+g7a7eb11a` --> `7a7eb11a * develop origin/develop` with python 3.8, that works but later on I saw issue #4311, therefore maybe not a good idea.
 - `4.0.dev0+g7a7eb11a` --> with python 3.7, ok.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python:  3.7
* Platform: e.g GNU/Linux (distribution), Windows 

### Stacktrace / full error message

I added som prints to see what's going on. Since my .spec file works locally but suddenly broke in CI.

<details><summary>Stacktrace (CLICK ME)</summary>
<p>

```
39984 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
39984 INFO: Writing RT_ICON 1 resource with 7450 bytes
Traceback (most recent call last):
struct.pack('L12l', 4277077181, 65536, 131078, 2279604224, 131078, 2279604224, 63, 0, 262148, 1, 0, 0, 0)
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\site-packages\PyInstaller\__main__.py", line 121, in <module>
    run()
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\site-packages\PyInstaller\building\build_main.py", line 734, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\site-packages\PyInstaller\building\build_main.py", line 681, in build
##[error]Cmd.exe exited with code '1'.
    exec(code, spec_namespace)
    rawffi = self.ffi.toRaw()
  File "C:\hostedtoolcache\windows\Python\3.7.7\x64\lib\site-packages\PyInstaller\utils\win32\versioninfo.py", line 320, in toRaw
    self.fileDateLS)
struct.error: argument out of range
```

</p>
</details>

Same Print local vs CI
```
         struct.pack('L12l', self.sig,   self.strucVersion, self.fileVersionMS, self.fileVersionLS, self.productVersionMS, self.productVersionLS, self.fileFlagsMask, self.fileFlags, self.fileOS, self.fileType, self.fileSubtype, self.fileDateMS, self.fileDateLS)
locally: struct.pack('L12l', 4277077181, 65536,             131077,             0,                  131077,                0,                     63,                 0,              262148,      1,             0,                0,               0)
CI:      struct.pack('L12l', 4277077181, 65536,             131078,             2279604224,         131078,                2279604224,            63,                 0,              262148,      1,             0,                0,               0)
```

self.fileVersionLS: 2279604224 (0x87e00000)
self.productVersionLS: 2279604224 (0x87e00000)

How important are `fileVersionLS` and `productVersionLS`.
As a workaround I am thinking of hardcoding them to zero on a fork until the next version of pyinstaller comes out, pyinstaller @develop + python 3.8 seems to work even though work is still to be done with the bootloader.

Suggestions?

**Update**: python3.7 and latest develop works.

**Comment by FrancescElies** [comment]
Latest develop with py3.7 works for me, I am happy taking that as a solution. Therefore, since no one else cares, closing.

**Comment by alexchandel** [comment]
4311 may be fixed soon, check back in a bit.

**Comment by FrancescElies** [comment]
The funny thing with this error is that it used to work, then I guess something got updated in windows and started getting struct errors. My venv nor python packages nor pyinstaller project changed in the meanwhile but my build broke.
