### ISSUE TITLE
PyInstaller can't detect uses of `importlib`, `imp`, or any method that doesn't use the standard `from ... import ...` or `import ...` syntax.

### ISSUE THREAD

**Issue by Mradr** [pyinstaller/pyinstaller#4976]
PyInstaller can't detect uses of `importlib`, `imp`, or any method that doesn't use the standard `from ... import ...` or `import ...` syntax.

Please use the `--hidden-import` option to specify extra imports to include, and the `-p PATH` to specify extra python paths.

_Originally posted by @Legorooj in https://github.com/pyinstaller/pyinstaller/issues/4973#issuecomment-653991044_

Sounds good. What's the difference between --hidden-import and --additional-hooks-dir in this case? Also, I tried adding  --hidden-import "scripts.*" but didn't see to pick up anything - so how should this look? 

Actually, if I may ask as well, is it possible to mix the environments? Like if I was able to get python install it starts using that python install as well? I still want the main program as the exe - but I could install python at will if its just a matter of missing modules.

**Comment by Legorooj** [comment]
> Sounds good. What's the difference between --hidden-import and --additional-hooks-dir in this case? Also, I tried adding --hidden-import "scripts.*" but didn't see to pick up anything - so how should this look?

`--hidden-import=import_name` is used to specify a single import. If you had `import my_package.sub_module` or `from my_package import sub_module` or `from my_package.sub_module import func` then you'd use `--hidden-import=my_package.sub_module` if PyInstaller wasn't finding it for whatever reason.

`--additional-hooks-dir` is used to specify a directory which contains hooks. These specify what to include in the bundle, where to find modules, extra scripts to run when booting the program. Hooks shouldn't be necessary for this problem.

>Actually, if I may ask as well, is it possible to mix the environments? Like if I was able to get python install it starts using that python install as well? I still want the main program as the exe - but I could install python at will if its just a matter of missing modules.

Could you clarify this a bit more? I'm confused.

**Comment by Legorooj** [comment]
Stale.
