### ISSUE TITLE
No Module Named 'xxx'.

### ISSUE THREAD

**Issue by ScarlettCharlie** [pyinstaller/pyinstaller#4977]
OS : macOS Catalina
I pip-installed pyinstaller to pack my app in which one of my .py file has imported xxx
Like this:
import xxx
from xxx import ...

I followed all the steps, opened the app from the terminal and it always says
No Module Named 'xxx'

my main python file is in the first layer of my Sources, while other python files I programmed is underneath it.
and here's my .spec file:
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None
a = Analysis(['1.py','],
             pathex=['/something/myApp'],
             binaries=[],
             datas=[],
             hiddenimports=['xxx'],
<and everything else...>

and xxx in installed in the same environment where I installed pyinstaller(I used pip3 install pyinstaller command)

-------------------------- How it is solved--------------------------

When packaging my app again, I didn't use pyinstaller -Fw myapp.py

instead, to let pyinstaller know where my packages are, I used this
pyinstaller -p the_package_path_pyinstaller_didn't_recogize_before -Fw myapp.py

HOWEVER

New issues showed up, see comments.

**Comment by ScarlettCharlie** [comment]
@Legorooj I installed the pyinstaller right, installed the xxx under the folder site-packages, edited hiddenimports=[] with filling 'xxx' in [], but why in the name of god does [No Module Named 'xxx'] keep showing up?

**Comment by ScarlettCharlie** [comment]
@Legorooj Seems the command [pyinstaller -p path_of_xxx -Fw] works, but new issue shows up.
When running the app via terminal, it says:

Fatal Python error: initfsencoding: unable to load the file system codec
LookupError: unknown encoding: utf-8

Is it caused by the version of python, the version of pyinstaller or any other causes?
Thank you!

**Comment by Legorooj** [comment]
@ScarlettCharlie which version of python and PyInstaller are you running? And what is the default language on your mac?

**Comment by ScarlettCharlie** [comment]
> @ScarlettCharlie which version of python and PyInstaller are you running? And what is the default language on your mac?

Oops, hope it's not because of python version..

Python: 3.7+
Pyinstaller: 3.6
MacOS :10.15.5
Default System Language: Mandarin

**Comment by Legorooj** [comment]
The script runs from PyCharm correct? If so, try building with the development version: `pip install -U https://github.com/pyinstaller/pyinstaller/archive/develop.zip`.

**Comment by ScarlettCharlie** [comment]
Hello


Sorry for the time difference and the delay.
My PyCharm Version:2019.3.4
I'm now trying to use the develop version of PyInstaller to solve this problem.
My scripts are all correct in PyCharm.




Thanks!










At 2020-07-08 10:17:00, "Legorooj" <notifications@github.com> wrote:

The script runs from PyCharm correct? If so, try building with the development version: pip install -U https://github.com/pyinstaller/pyinstaller/archive/develop.zip.

**Comment by Legorooj** [comment]
@ScarlettCharlie did you have any success with the development version?

**Comment by ScarlettCharlie** [comment]
Not yet, I'll try searching it but if you can send me a link, I'll appreciate it a lot.










At 2020-07-09 09:14:15, "Legorooj" <notifications@github.com> wrote:

@ScarlettCharlie did you have any success with the development version?

**Comment by Legorooj** [comment]
`pip install https://github.com/PyInstaller/pyinstaller/archive/develop.zip`.

**Comment by ScarlettCharlie** [comment]
Thank you!!
I will try this out













在 2020-07-09 11:19:59，"Legorooj" <notifications@github.com> 写道：

pip install https://github.com/PyInstaller/pyinstaller/archive/develop.zip.

**Comment by ScarlettCharlie** [comment]
BTW, my app includes sub windows. Why the packed app cannot open those sub windows? Why aren't the buttons respoding?!







在 2020-07-09 11:19:59，"Legorooj" <notifications@github.com> 写道：

pip install https://github.com/PyInstaller/pyinstaller/archive/develop.zip.

**Comment by ScarlettCharlie** [comment]
Sorry for frequent emails, but I am really new to this.
Would you tell me how to install the development version?
I pip uninstalled pyinstaller but why is it still there?
Also, why my packed app has lost all its functions of opening a subwindow? Everything was fine in PyCharm. What did I miss?




Thank you so much!!
Charlie

在 2020-07-09 11:19:59，"Legorooj" <notifications@github.com> 写道：

pip install https://github.com/PyInstaller/pyinstaller/archive/develop.zip.

**Comment by Legorooj** [comment]
@ScarlettCharlie you probably need to include some resources or similar. Did the subwindow depend on files?

**Comment by ScarlettCharlie** [comment]
I agree...yes, my sub windows are programmed as .py files.
How do I add them to the app while packaging with pyinstaller? I edited .spec file but it doesn't seem to work: starting the app by double-clicking the terminal icon worked fine, but double-clicking the app ended up crashing (the app flashes and quits itself). I clicked'Show Contents' and saw no files in the folder 'Frameworks', obviously there were some missing files - what should I do to include them while packaging?



At 2020-07-09 15:13:23, "Legorooj" <notifications@github.com> wrote:

@ScarlettCharlie you probably need to include some resources or similar. Did the subwindow depend on files?

**Comment by Legorooj** [comment]
How do you run your sub-files?

**Comment by ScarlettCharlie** [comment]
My main script is Main.py:


import Files.sub-file
xxx
if __name__ == '__main__':
      blahblahblah


then in the sub-folder Files are stuffs like sub-file.py


everything was perfect in PyCharm...

At 2020-07-09 20:11:00, "Legorooj" <notifications@github.com> wrote:

How do you run your sub-files?

**Comment by ScarlettCharlie** [comment]
Some how the buttons can be clicked again and I HAVE NO IDEA WHY
But the .app still crashes with no errors printed in the terminal.




At 2020-07-09 20:11:00, "Legorooj" <notifications@github.com> wrote:

How do you run your sub-files?

**Comment by Legorooj** [comment]
@ScarlettCharlie any files you load that aren't done through `import ...`, you need to add with `--add-binary` and `--add-data`. See the documentation for more details. Oh and just a note: only use `--add-binary` for DLLs or similar. Use `--add-data` for most files.

**Comment by ScarlettCharlie** [comment]
None or the methods you provided works in a bit.
Where is your doc? Is it only readable for experts?
I used pyinstaller because I thought it can make things EASIER but obviously I didn't find a right path.
I even tried to add images manually in the .spec file but it shows this:

Traceback (most recent call last):

  File "/Users/charleslure/opt/anaconda3/bin/pyinstaller", line 8, in <module>

    sys.exit(run())

  File "/Users/charleslure/opt/anaconda3/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run

    run_build(pyi_config, spec_file, **vars(args))

  File "/Users/charleslure/opt/anaconda3/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build

    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)

  File "/Users/charleslure/opt/anaconda3/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 734, in main

    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))

  File "/Users/charleslure/opt/anaconda3/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 680, in build

    code = compile(f.read(), spec, 'exec')

  File "AddWatermarkApp.spec", line 10

    '(/Volumes/.../Background_MainUI.jpg', '.'),

                               ^

SyntaxError: invalid syntax







Things are getting so much more complicated.
Yes, always the annoying 'invalid syntax' when adding images, and there should be a solution to it as least...Where is it? How??????


At 2020-07-10 07:08:14, "Legorooj" <notifications@github.com> wrote:

@ScarlettCharlie any files you load that aren't done through import ..., you need to add with --add-binary and --add-data. See the documentation for more details. Oh and just a note: only use --add-binary for DLLs or similar. Use --add-data for most files.

**Comment by ScarlettCharlie** [comment]
Here's what happened in the adding-files-to-binary process.
I added them in .spec files in tuples, ERROR;
I added them in 'xxx.py', 'yyy.py' format, ValueError: too many values to unpack.
and NOTHING SHOWS ME HOW TO DO, PERFECT

**Comment by ScarlettCharlie** [comment]
Pyinstaller is the software for many python users including me and we do not really have other options. Being an only option, I find it very disappointing when it crashes all the time. There's no word for me to describe my terrible feelings.

**Comment by ScarlettCharlie** [comment]
> @ScarlettCharlie any files you load that aren't done through `import ...`, you need to add with `--add-binary` and `--add-data`. See the documentation for more details. Oh and just a note: only use `--add-binary` for DLLs or similar. Use `--add-data` for most files.

Update:
CollactedMode works fine EXCEPT the images cannot be packed whatever I try. Sad.

Here's what I did (Note that the spec file is based on collection packaging mode):
pipenv shell
pipinstaller
cd Source_root_of_my_app
ls
pyinstaller myapp.spec --add-data=/Images/aaa.jpg:dest --add-data=/Images/bbb.png:dest --add-data=/Images/ccc.jpg:dest.

Then the packaging finished, app can be started in the terminal (slow for the first time but way smoother afterwards).
HOWEVER, NO IMAGES WERE PACKED.

The apk file under the build folder cannot be openned. I kind of worry that this apk isn't complete.

**Comment by ScarlettCharlie** [comment]
Well, I checked the doc, followed the instructions and the Images are packed.
But these images just won't show in the GUI.
Not to mention the icon.

**Comment by ScarlettCharlie** [comment]
Sorry for frequent emails again but even the doc didn't do much help.
Whichever the freezing mode is, is there any way of avoiding the app from crushing, and making sure that the images are not only packed, but also normally used in the GUI?
PLZ, my app is so close to a successful packaging...
At 2020-07-10 07:08:14, "Legorooj" <notifications@github.com> wrote:

@ScarlettCharlie any files you load that aren't done through import ..., you need to add with --add-binary and --add-data. See the documentation for more details. Oh and just a note: only use --add-binary for DLLs or similar. Use --add-data for most files.

**Comment by ScarlettCharlie** [comment]
@Legorooj Are you available right now?

**Comment by Legorooj** [comment]
@ScarlettCharlie you're probably using incorrect paths when loading the files. How do you load your files?

**Comment by ScarlettCharlie** [comment]
As for the file loading method you mentioned, are you referring to the method in .py files, the method in the packaging process, or the one in the .spec file?

At 2020-07-10 16:08:58, "Legorooj" <notifications@github.com> wrote:

@ScarlettCharlie you're probably using incorrect paths when loading the files. How do you load your files?

**Comment by ScarlettCharlie** [comment]
@Legorooj 

When I ran the packed app which was freeze in one file:
Click the app, it crushes;
Run it in terminal (pipenv shell): slow start but everything else is fine.
In the terminal, it shows this: []

Seems it's getting closer to the answer!

**Comment by Legorooj** [comment]
Give [this](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html) a thorough read.

**Comment by ScarlettCharlie** [comment]
> Give [this](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html) a thorough read.

Are you serious?!

**Comment by Legorooj** [comment]
@ScarlettCharlie that document will tell you exactly what is wrong: You're not accessing the files correctly. You need to use a snippet of code like this:

```python
from os import path
import sys
bundle_dir = getattr(sys, '_MEIPASS', path.abspath(path.dirname(__file__)))
path_to_dat = path.abspath(path.join(bundle_dir, 'other-file.dat'))
```

**Comment by ScarlettCharlie** [comment]
> @ScarlettCharlie that document will tell you exactly what is wrong: You're not accessing the files correctly. You need to use a snippet of code like this:
> 
> ```python
> from os import path
> import sys
> bundle_dir = getattr(sys, '_MEIPASS', path.abspath(path.dirname(__file__)))
> path_to_dat = path.abspath(path.join(bundle_dir, 'other-file.dat'))
> ```

Can you be more specific? ? ?
Where do I place this script? In .py format or what? Just running it?

**Comment by ScarlettCharlie** [comment]
> @ScarlettCharlie that document will tell you exactly what is wrong: You're not accessing the files correctly. You need to use a snippet of code like this:
> 
> ```python
> from os import path
> import sys
> bundle_dir = getattr(sys, '_MEIPASS', path.abspath(path.dirname(__file__)))
> path_to_dat = path.abspath(path.join(bundle_dir, 'other-file.dat'))
> ```

@Legorooj 
Simply a snippet of code didn't answer my question, I don't even know how to use it. It's like my car is broken and you gave me a design drawing of the engine.
At least something like:
A, this this this
B, that that that
C, blah blah blah
.....this doc is really confusing me and I wanted to make things easier, not the other way around.

**Comment by ScarlettCharlie** [comment]
👎

**Comment by ScarlettCharlie** [comment]
I AM ONE STEP TOWARDS SOLVING THE PROBLEM
AND YOU GAVE ME A DOC TO MAKE THINGS WORSE
I CAN'T FEEL BETTER NOW

**Comment by ScarlettCharlie** [comment]
PLEASE GIVE ME A REPLY I CAN UNDERSTAND, THANK YOU

**Comment by ScarlettCharlie** [comment]
@Legorooj Would you treat this issue more seriously?!?!?!?!?!?!?!?

**Comment by ScarlettCharlie** [comment]
@Legorooj Fine, let's discuss this issue right here.
Would you tell me what this doc really means? I didn't mean to make troubles but I wish I could understand all of it.
The Truth is, according to this: [How to Report Bugs](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged), I've tried everything I could, and this is a bug.

Even if it were my bad, this doc is more like for amateurs. But I need to understand what I should do step by step.
I didn't mean to be lazy cause I am willing to view docs before solving problems. But I am a user, not a developer.

**Comment by Legorooj** [comment]
@ScarlettCharlie I am treating this issue as seriously as any other support ticket.

**Comment by Legorooj** [comment]
Yes, I will explain this more thoroughly, just not right now because it's 10pm over here and I'm going to bed. I will address this and write up a decent explanation tomorrow morning.

**Comment by ScarlettCharlie** [comment]
> Yes, I will explain this more thoroughly, just not right now because it's 10pm over here and I'm going to bed. I will address this and write up a decent explanation tomorrow morning.

Thank you, and since now I understand that PyInstaller is made during your spare time, I will slow this process down on the basis of both your free time and mine. My apologies for thinking you were 24/7 developer team, this is my fault. But anyway, my profession is to develop GUI app with related functions, so I really find it impossible to understand some of your docs. Since Pyinstaller is by now the first choice, some big apps are relying on it, so please forgive my high expectations.

**Comment by ScarlettCharlie** [comment]
> Yes, I will explain this more thoroughly, just not right now because it's 10pm over here and I'm going to bed. I will address this and write up a decent explanation tomorrow morning.

Thank you, and since now I understand that PyInstaller is made during your spare time, I will slow this process down on the basis of both your free time and mine. My apologies for thinking you were 24/7 developer team, this is my fault. But anyway, my profession is to develop GUI app with related functions, so I really find it impossible to understand some of your docs. Since Pyinstaller is by now the first choice, some big apps are relying on it, so please forgive my high expectations.

**Comment by Legorooj** [comment]
@ScarlettCharlie you're loading the files wrong. An example:

```
- myscript.py
- image.jpg
- assets/
  - data.json
  - document.xml
```
When running this you'd generally use `open('image.jpg')` or similar. This won't work with PyInstaller, because of how it includes files. You can use the following function to get the path to files:
```python
import os
import sys
def get_path_for_resource(filepath):
    base = getattr(sys, '_MEIPASS', os.path.dirname(__file__))
    return os.path.join(base, filepath)
```
You would then call `get_path_for_resource('image.jpg')` or `get_path_for_resource('assets/data.json')`. This does assume that you've added the files using `--add-data image.jpg:.`, `--add-data assets/data.json:assets`, and `--add-data assets/document.xml:assets`. Please note that on windows you'll need to use a semicolon (`;`) instead of a colon (`:`), and that when using powershell you need to escape the semicolon with a backtick.

Unfortunately I can't offer much more support than this. If you would like more, then please email `h.goebel@crazy-compilers.com` to arrange paid support.

**Comment by ScarlettCharlie** [comment]
> @ScarlettCharlie you're loading the files wrong. An example:
> 
> ```
> - myscript.py
> - image.jpg
> - assets/
>   - data.json
>   - document.xml
> ```
> 
> When running this you'd generally use `open('image.jpg')` or similar. This won't work with PyInstaller, because of how it includes files. You can use the following function to get the path to files:
> 
> ```python
> import os
> import sys
> def get_path_for_resource(filepath):
>     base = getattr(sys, '_MEIPASS', os.path.dirname(__file__))
>     return os.path.join(base, filepath)
> ```
> 
> You would then call `get_path_for_resource('image.jpg')` or `get_path_for_resource('assets/data.json')`. This does assume that you've added the files using `--add-data image.jpg:.`, `--add-data assets/data.json:assets`, and `--add-data assets/document.xml:assets`. Please note that on windows you'll need to use a semicolon (`;`) instead of a colon (`:`), and that when using powershell you need to escape the semicolon with a backtick.
> 
> Unfortunately I can't offer much more support than this. If you would like more, then please email `h.goebel@crazy-compilers.com` to arrange paid support.

Thanks for the reply, and I've been trying out all the possible ways of solving this issue. However, since I'm running out of time, I have to be looking for other solutions for freezing PyQt apps though. But I hope this conversation may help other viewers.
