### ISSUE TITLE
does pyinstaller support python-ffmpeg-video-streaming? if not any tips required

### ISSUE THREAD

**Issue by csrujan** [pyinstaller/pyinstaller#4978]
![Screenshot (336)](https://user-images.githubusercontent.com/42429607/86723050-2be62180-c045-11ea-9896-6e6dd3102250.png)

will pyinstaller support the following package 
pip install python-ffmpeg-video-streaming
as i am facing the issue i posted in the image as ffmpeg video streaming is unable to generate output

**Comment by bwoodsend** [comment]
`python-ffmpeg-video-streaming` doesn't come with ffmpeg. Are you expecting PyInstaller to include it in your build or for the user to have it installed and the build find it at run time? Also could you please give us a minimal example to work with.

**Comment by csrujan** [comment]
yes python-ffmpeg-video-streaming doesn't come with ffmpeg , we need to install that using pip , after writing the code that imports the python-ffmpeg-video-streaming and converting it into exe using pyinstaller it is not including this library in the build

**Comment by bwoodsend** [comment]
> we need to install that using pip 

How did you do this? None of the ffmpeg libraries I can find of PyPi seem to do this. Normally I install ffmpeg by downloading the binaries and adding them to `PATH`. And that seems to be the way `python-ffmpeg-video-streaming` expects it to be judging by its source code.

**Comment by csrujan** [comment]
pip install python-ffmpeg-video-streaming does this and here is link to this project https://pypi.org/project/python-ffmpeg-video-streaming/

**Comment by bwoodsend** [comment]
> pip install python-ffmpeg-video-streaming does this 

Hmm, it didn't for me. But to answer your original question: To get any of the ffmpeg python libraries to work you'll need to tell PyInstaller to include the ffmpeg binaries. If you know their location at build time you can just pass it using:
```shell
PyInstaller --add-binary /path/to/ffmpeg/bin/*.exe:.
```
(Note the trailing dot.) This will place all the ffmpeg executables into the root of your app where `python-ffmpeg-video-streaming` should be able to find it.

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
