### ISSUE TITLE
PySide hooks (Windows)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#498]
**Original date**: 2012/02/01

The pyqt4 hooks are not compatible with pyside. New hooks for pyside has to be written based on current pyqt4 hooks. Maybe some code could be shared between pyside and pyqt4 hooks.

 - One user started some work on pyside hooks at: https://github.com/ssorgatem/pyinstaller
 - This ticket is only for Windows implementation. #299 is for Linux/Mac implementation.

Following pyside phonon example does not work:

Symptom: .exe crashes without any message.[[BR]]
Python script:[[BR]]
---------------------------------

```
#!python
import sys
from PySide.QtGui import QApplication
from PySide.phonon import Phonon
def main():
    if len(sys.argv)< 2: sys.exit()
    app = QApplication([])
    media_src = Phonon.MediaSource(sys.argv[1])
    media_obj = Phonon.MediaObject()
    media_obj.setCurrentSource(media_src)
    media_obj.finished.connect(sys.exit)
    video_widget = Phonon.VideoWidget()
    video_widget.setGeometry(120,100,640,480)
    Phonon.createPath(media_obj, video_widget)
    audio_out = Phonon.AudioOutput(Phonon.VideoCategory)
    Phonon.createPath(media_obj, audio_out)
    video_widget.show()
    media_obj.play()
    app.exec_()
    sys.exit()
    
if __name__ == "__main__": main()    
```
-----------------------------------------
pyinstaller commands used (Python 2.7, Windows 7):[[BR]]

python makespec.py --onefile --debug \mypath\vidplay.py[[BR]]

python build.py vidplay\vidplay.spec[[BR]]

Another example for testing
```python
#!/usr/bin/python
import sys
import PySide
from PySide.QtGui import QApplication
from PySide.QtGui import QMessageBox
app = QApplication(sys.argv)
msgBox = QMessageBox()
msgBox.setText("Hello World - using PySide version " + PySide.__version__)
msgBox.exec_()
```

**Comment by matysek** [comment]
Closing since basic PySide support is already done.
