### ISSUE TITLE
Packed Apps Run Too Slow (And Size Too Big)

### ISSUE THREAD

**Issue by ScarlettCharlie** [pyinstaller/pyinstaller#4980]
@Legorooj 

Thank you for your attention.

Since my docx-related app are unable to be packed, I decided to pack up another app. However, Even I used pipenv shell, the packaging process is still way too far from smoothy.

I tried this process:

pipenv shell
pipenv install pyinstaller
pipenv install packages_needed_by_apps
pipenv installer

then the packaging process

then JUST STARTING my app caused 30secs?!

How is it possible for me to avoid this? 
Thank you!

Charlie

**Comment by ScarlettCharlie** [comment]
I guess it's because I've packed too many Qt Modules but I haven't tried this solution out yet.
Anyway, deleting these unused modules manually worked, which is based on -D packaging method
Will update this post if -F method applies to this solution.

**Comment by Legorooj** [comment]
You're building in onefile mode, which has to decompress the data every time. Try without `-F` or `--onefile`. We can't help much with the speed of starting up an app.
