### ISSUE TITLE
.app CRUSHES ALL THE TIME with a solution I have no idea what is going on

### ISSUE THREAD

**Issue by ScarlettCharlie** [pyinstaller/pyinstaller#4990]
@ScarlettCharlie that document will tell you exactly what is wrong: You're not accessing the files correctly. You need to use a snippet of code like this:

```python
from os import path
import sys
bundle_dir = getattr(sys, '_MEIPASS', path.abspath(path.dirname(__file__)))
path_to_dat = path.abspath(path.join(bundle_dir, 'other-file.dat'))
```

_Originally posted by @Legorooj in https://github.com/pyinstaller/pyinstaller/issues/4977#issuecomment-656596243_

Yes, but that's it? Huh??

**Comment by ScarlettCharlie** [comment]
The moment I opened the doc, I was extremely furious

**Comment by ScarlettCharlie** [comment]
If asking help desperately gets an answer of seeing the docs that is making things worse, then why don't I pay for a commercial software? I use pyinstaller to pack my app, not to get annoyed by answers like: see this doc, see that doc, if I could understand everything of the docs then why are you the developer instead of me?!

**Comment by Legorooj** [comment]
We can discuss this in #4977. Please do not open several bug tickets for the same problem.
