### ISSUE TITLE
Tensorflow.core module is still being referenced 

### ISSUE THREAD

**Issue by zakdia** [pyinstaller/pyinstaller#4993]
In the below issue comment, it was mentioned that 4.0.dev0 version supports tensorflow but when I create the exe with PyInstaller, it is still looking of the Tensorflow.core module. 
https://github.com/pyinstaller/pyinstaller/issues/4400#issuecomment-623072958

tensorflow version being used is 2.2.0 and it only has the below two lines in the py file. 
from tensorflow.keras import models
model = models.Sequential()

Error message: File "tensorflow\python\__init__.py", line 53, in <module>
ModuleNotFoundError: No module named 'tensorflow.core'
[248] failed to execute script

**Comment by Legorooj** [comment]
@zakdia I wrote the original tensorflow hooks myself - true, the ones in PyInstaller have been optimised - and this is one of the errors that I got rid of. 

Can you try `from tensorflow import *`? Does that work?

**Comment by zakdia** [comment]
> @zakdia I wrote the original tensorflow hooks myself - true, the ones in PyInstaller have been optimised - and this is one of the errors that I got rid of.
> 
> Can you try `from tensorflow import *`? Does that work?

**Comment by Legorooj** [comment]
@zakdia did you get this working?

**Comment by zakdia** [comment]
@Legorooj - No. I accidentally closed the issue. Reopening now. 

When I try from tensorflow import * , the exe in the dist folder is automatically getting deleted. May be the antivirus in the machine? (I don't have access to disable it). This doesn't happen if I'm importing a specific library like keras or models. 

Missed to mention in my initial comment that I had also created a 'hook-tensorflow_core.python.py' inside a 'hooks' folder from the directory where .py file is present with the below line of code and called it from the CLI with --additional-hooks-dir=hooks command included. 

from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('tensorflow_core')

**Comment by Legorooj** [comment]
@zadkia the `dist` folder definitely shouldn't get deleted, and it's definitely an external program or something - as bugs go that one can't be in PyInstaller.

Can you post the build log please?

**Comment by zakdia** [comment]
@Legorooj it was the exe inside the dist folder that was getting deleted and not the dist folder

**Comment by zakdia** [comment]
@Legorooj - In the build log, I see a warning that **_Hidden Import "tensorflow_core" not found_** and in the hook file, **_hook-tensorflow_core.python.py_** (which came along with v 4.0.dev0 of PyInstaller), there is a line **_hiddenimports = collect_submodules('tensorflow_core')_**. 

Would this help for the analysis?

**Comment by Legorooj** [comment]
@zakdia yes that is helpful... Can you please:

* Copy and paste the entire build log into a comment
* Run the file you're building with `python -v filename.py` and copy-paste the output. We need to trace the imports.

**Comment by zakdia** [comment]
@Legorooj - I'm closing this issue as it was happening because the Tesorflow package was missing the 'core' and 'compile' sub modules in the distribution. I copied those folders from the _venv_ to the main distribution path and not facing the reference error to tensorflow.core anymore. 
This is not a PyInstaller issue and the Tensorflow developers may have to look into why the core and compile folders are not getting included into the distribution when we install the latest Tensorflow version (2.2.0) via pip.
