### ISSUE TITLE
AttributeError with parsedatetime module

### ISSUE THREAD

**Issue by qburke** [pyinstaller/pyinstaller#4995]
## Context information

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.3
* Platform: Windows-10-10.0.18362-SP0
* Locale: en-us;English (United States)
* I have not yet tried to reproduce on another platform

### Example Program

```
import parsedatetime
```

No flags were passed to pyinstaller to produce the executable i.e.
```
pyinstaller test.py
```

### Stacktrace when running the executable from the command line

```
Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import parsedatetime
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "C:\Users\burke\Workspace\certserve-native\env\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
    exec(bytecode, module.__dict__)
  File "lib\site-packages\parsedatetime\__init__.py", line 69, in <module>
  File "lib\site-packages\parsedatetime\__init__.py", line 69, in <listcomp>
  File "lib\site-packages\parsedatetime\pdt_locales\__init__.py", line 29, in load_locale
AttributeError: module 'parsedatetime.pdt_locales' has no attribute 'de_DE'
[1884] Failed to execute script test
```

**Comment by Legorooj** [comment]
@qburke this runs fine from the command line correct?

**Comment by bwoodsend** [comment]
The problem is a series of locales modules inside `parsedatetime/pdt_locales` which are lazily loaded using `__import__()`. These need to be added as hidden-imports for PyInstaller to include them. Unfortunately there are several so whilst you can fix this with:
```
PyInstaller --hidden-import parsedatetime.pdt_locales.de_DE --hidden-import parsedatetime.pdt_locales.en_AU --hidden-import parsedatetime.pdt_locales.en_US --hidden-import parsedatetime.pdt_locales.es --hidden-import parsedatetime.pdt_locales.nl_NL --hidden-import parsedatetime.pdt_locales.pt_BR --hidden-import parsedatetime.pdt_locales.ru_RU --hidden-import parsedatetime.pdt_locales.fr_FR test.py
```
I would recommend using the spec file instead. Add the following to the top of `test.spec`:
```
from parsedatetime.pdt_locales import locales
hidden_imports = ["parsedatetime.pdt_locales." + i for i in locales]
```
Then in the `a = Analysis(...)` bit change the `hiddenimports=[]` to `hiddenimports=hidden_imports`.

TODO: put this into a hook.

**Comment by Legorooj** [comment]
@bwoodsend or @qburke if you have time to add this in a hook to github.com/pyinstaller/pyinstaller-hooks-contrib via a PR...

**Comment by bwoodsend** [comment]
@Legorooj  I've written I hook but wasn't sure where to put it. I'll PR it now.
