### ISSUE TITLE
Ignore imports behind `if __name__ == "__main__"` in standard library

### ISSUE THREAD

**Issue by alexchandel** [pyinstaller/pyinstaller#4997]
## Description of the issue

Some standard library modules import unrelated things behind `if __name__ == "__main__"` tests, like [heapq.py](https://github.com/python/cpython/blob/3.8/Lib/heapq.py#L600), which imports `doctest` for unit testing.

This sucks in an enormous number of dependencies, including even `ctypes` as of 3.8 due to a long chain of includes.

A frozen app will never run standard library files as `__main__`, so it would make sense for pyinstaller (or perhaps at the modulegraph level?) to ignore these.  It will also shrink the size of small compiled executables by a fair margin.

## Context information (for bug reports)

* Output of `pyinstaller --version`: all, through ```4.0.dev0```
* Version of Python: All, through 3.10 (dev)
* Platform: All

**Comment by Legorooj** [comment]
@alexchandel I'm not sure this is actually possible due to the way modulegraph works with the bytecode. I'll look into it though.

**Comment by Legorooj** [comment]
This isn't possible for either PyInstaller or modulegraph to do with any ease - the only way I can find is going through and
excluding dependencies on a per-module basis after the scanning is complete, which would massively increase the time spent building the executable.
