### ISSUE TITLE
pyinstaller incompatible with setuptools newer than 49.0.1

### ISSUE THREAD

**Issue by thetheo2** [pyinstaller/pyinstaller#5001]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
During packaging there is this warning--

python3.6/site-packages/setuptools/distutils_patch.py:26: UserWarning: Distutils was imported before Setuptools. This usage is discouraged and may exhibit undesirable behaviors or errors. Please use Setuptools' objects directly or at least import Setuptools first.
  "Distutils was imported before Setuptools. This usage is discouraged "

Packaged application fails to load with this error message--

Traceback (most recent call last):
  File "hello_world.py", line 4, in <module>
    import pkg_resources.py2_warn
ModuleNotFoundError: No module named 'pkg_resources'
[54116] Failed to execute script hello_world

## Context information (for bug reports)

* Output of `pyinstaller --version`: 3.6
* Version of Python: e.g. 3.6.10
* Platform: GNU/Linux
* Did you also try this on another platform? Does it work there?
No.

* try the latest development version, using the following command:

We are holding setuptools down to 49.0.1 for the time being.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

pyinstaller --clean -d all -F hello_world.py
~~~~~
# Problem: pyInstaller packaage is not discovering this dependency.
# Trial fix: import the dependency here so it is included in the built application.
#
import pkg_resources.py2_warn
print('hello world')
try :
    import numpy # confirm full suite can be used in packaged app
    print(numpy.sqrt(2))
except (ImportError,AttributeError) :
    pass
try :
    import requests # confirm full suite can be used in packaged app
    r = requests.get('https://api.github.com/repos/psf/requests')
    print(r.json()['description'])
except (ImportError,AttributeError) :
    pass

### Stacktrace / full error message

Traceback (most recent call last):
  File "hello_world.py", line 4, in <module>
    import pkg_resources.py2_warn
ModuleNotFoundError: No module named 'pkg_resources'
[54116] Failed to execute script hello_world

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
This is an old bug which was fixed ages ago but still hasn't been released. Either:

- Pass `--hidden-import pgk_resources.py2_warn`.
- Or install the develop version `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`.

**Comment by bwoodsend** [comment]
You shouldn't be using `import pkg_resources.py2_warn` to fix hidden imports as this will break with `setuptools<45.0.0` when they added it or now that they've removed it again. Use `--hidden-import pkg_resources.py2_warn` or, at the very least, wrap it in a `try: except ImportError:`.

**Comment by htgoebel** [comment]
@thetheo2 Please post a *minimal* example *without bugs* for a *single* issue. Thanks,

**Comment by bwoodsend** [comment]
@thetheo2 Could you also tell us where you got the following information as it is incorrect and needs changing.

> ```
> # Trial fix: import the dependency here so it is included in the built application.
> import pkg_resources.py2_warn
>```

You're not the 1st person I've seen make this error.

**Comment by thetheo2** [comment]
Excellent news, when the next release is available this issue will
disappear.  Thank you for your attention.

**Comment by thetheo2** [comment]
The trial fix was just something I did quickly to try to resolve the
problem.

As I think is typical for users of pyInstaller, it is just a part of an
ecosystem I keep running, so simple hacks are attempted so that I (we) can
return back to my (our) regularly scheduled programming as it were.

I did not find this fix on the web or similar as you may be concerned
about.

Again, thank you for your attention to this matter, I eagerly await the
next release.

The suggestion to use the trunk/master of pyInstaller instead of an
available release is probably a good one, but I very strongly prefer to
pick a known release of pyInstaller so that the wider ecosystem I support
is reproducible.

Best regards,

Ted

**Comment by bwoodsend** [comment]
> I did not find this fix on the web or similar as you may be concerned about.

Thanks, that's a relief to hear. If it was on something like StackOverflow then I'd  expect to be flooded with duplicates of this issue for months into the future.
