### ISSUE TITLE
Error python37.dll module not found

### ISSUE THREAD

**Issue by AllStarsAT** [pyinstaller/pyinstaller#5003]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
I am using pyinstaller to create an .exe that should be working without any dependencies, therefore i use the -F option. Unfortunately, when I try to run this .exe in an environment that doesn't have python installed, I get 2 error popup windows:
1st: api-ms-win-crt-runtime-l1-1-0.dll is missing 
2nd: python37.dll module not found

For some weird reason the same thing happens when i use the -D option. Even though there is a python37.dll in the folder of the .exe it still says that the module was not found. 

Of course this problem leads to my program not working as a standalone application without any dependencies.

I think that this error obviously has nothing to do with my code, but rather with some settings/bugs within Pycharm/pyinstaller

Thanks in advance for any help!

UPDATE: I used the pyi-archive_viewer to check what is wrong and found only a couple of archives ... not including any of the api-ms-win-crt-*.dll and not the python37.dll. Checking out a working .exe that was compiled using pyinstaller with the pyi-archive_viewer I realised that all of these files are included in that .exe file. Does anybody happen to know the root of this issue?

Here is my archive-table:
```
 pos, length, uncompressed, iscompressed, type, name
[(0, 282, 369, 1, 'm', 'struct'),
 (282, 1132, 1850, 1, 'm', 'pyimod01_os_path'),
 (1414, 4033, 8634, 1, 'm', 'pyimod02_archive'),
 (5447, 5350, 12464, 1, 'm', 'pyimod03_importers'),
 (10797, 1820, 4098, 1, 's', 'pyiboot01_bootstrap'),
 (12617, 320, 438, 1, 's', 'pyi_rth__tkinter'),
 (12937, 1984, 3396, 1, 's', 'pictureValidation'),
 (14921, 1263248, 1263248, 0, 'z', 'PYZ-00.pyz')]
```
As you can see there is not a single entry of the type 'b', which seems to be the type that is missing as all of the missing files are type 'b' as seen in another working .exe:
```
 (339010, 5204, 9720, 1, 'b', 'api-ms-win-core-console-l1-1-0.dll'),
 (344214, 5031, 9208, 1, 'b', 'api-ms-win-core-datetime-l1-1-0.dll'),
 (349245, 5046, 9208, 1, 'b', 'api-ms-win-core-debug-l1-1-0.dll'),
 (354291, 5096, 9208, 1, 'b', 'api-ms-win-core-errorhandling-l1-1-0.dll'),
 (359387, 6139, 12792, 1, 'b', 'api-ms-win-core-file-l1-1-0.dll'),
 (365526, 5065, 9208, 1, 'b', 'api-ms-win-core-file-l1-2-0.dll'),
 (370591, 5193, 9208, 1, 'b', 'api-ms-win-core-file-l2-1-0.dll'),
 (375784, 5067, 9208, 1, 'b', 'api-ms-win-core-handle-l1-1-0.dll'),
 (380851, 5236, 9720, 1, 'b', 'api-ms-win-core-heap-l1-1-0.dll'),
 (386087, 5081, 9208, 1, 'b', 'api-ms-win-core-interlocked-l1-1-0.dll'),
 (391168, 5390, 10232, 1, 'b', 'api-ms-win-core-libraryloader-l1-1-0.dll'),
 (396558, 5924, 11768, 1, 'b', 'api-ms-win-core-localization-l1-2-0.dll'),
 (402482, 5235, 9720, 1, 'b', 'api-ms-win-core-memory-l1-1-0.dll'),
 (407717, 5165, 9208, 1, 'b', 'api-ms-win-core-namedpipe-l1-1-0.dll'),
 (412882, 5311, 10232, 1, 'b', 'api-ms-win-core-processenvironment-l1-1-0.dll'),
 (418193, 5817, 11256, 1, 'b', 'api-ms-win-core-processthreads-l1-1-0.dll'),
 (424010, 5261, 9720, 1, 'b', 'api-ms-win-core-processthreads-l1-1-1.dll'),
 (429271, 5024, 8696, 1, 'b', 'api-ms-win-core-profile-l1-1-0.dll'),
 (434295, 5255, 9720, 1, 'b', 'api-ms-win-core-rtlsupport-l1-1-0.dll'),
 (439550, 5121, 9208, 1, 'b', 'api-ms-win-core-string-l1-1-0.dll'),
 (444671, 5642, 11256, 1, 'b', 'api-ms-win-core-synch-l1-1-0.dll'),
 (450313, 5301, 9720, 1, 'b', 'api-ms-win-core-synch-l1-2-0.dll'),
 (455614, 5362, 10232, 1, 'b', 'api-ms-win-core-sysinfo-l1-1-0.dll'),
 (460976, 5220, 9720, 1, 'b', 'api-ms-win-core-timezone-l1-1-0.dll'),
 (466196, 5046, 9208, 1, 'b', 'api-ms-win-core-util-l1-1-0.dll'),
 (471242, 5389, 10232, 1, 'b', 'api-ms-win-crt-conio-l1-1-0.dll'),
 (476631, 6436, 13304, 1, 'b', 'api-ms-win-crt-convert-l1-1-0.dll'),
 (483067, 5224, 9720, 1, 'b', 'api-ms-win-crt-environment-l1-1-0.dll'),
 (488291, 5842, 11256, 1, 'b', 'api-ms-win-crt-filesystem-l1-1-0.dll'),
 (494133, 5365, 10232, 1, 'b', 'api-ms-win-crt-heap-l1-1-0.dll'),
 (499498, 5328, 9720, 1, 'b', 'api-ms-win-crt-locale-l1-1-0.dll'),
 (504826, 8267, 18424, 1, 'b', 'api-ms-win-crt-math-l1-1-0.dll'),
 (513093, 5422, 10232, 1, 'b', 'api-ms-win-crt-process-l1-1-0.dll'),
 (518515, 6603, 13816, 1, 'b', 'api-ms-win-crt-runtime-l1-1-0.dll'),
 (525118, 7042, 15352, 1, 'b', 'api-ms-win-crt-stdio-l1-1-0.dll'),
 (532160, 7209, 15352, 1, 'b', 'api-ms-win-crt-string-l1-1-0.dll'),
 (539369, 5921, 11768, 1, 'b', 'api-ms-win-crt-time-l1-1-0.dll'),
 (545290, 5372, 9720, 1, 'b', 'api-ms-win-crt-utility-l1-1-0.dll'),
...
 (2161064, 1600437, 3751440, 1, 'b', 'python37.dll'),
```
So i wonder why that is

UPDATE: As reading through posts with similar problems, I just want to mention that i am using the .exe from the dist folder and not the .exe from the build folder.

UPDATE: got the python37.dll included in the exe with a spec file and adding a copy of the python37.dll in the binaries array(?)
However, the same error persists, first the win-api-*.dll error pop-up and then even though the python37.dll is included, which i checked with the pyi-archive_viewer, it still says that the module could not be loaded

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0.dev0```
* Version of Python: 3.7.8
* Platform: Windows 
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
C:\Users\j\PycharmProjects\untitled>pyinstaller -F -w --debug=all pictureValidation.py
112 INFO: PyInstaller: 3.6
113 INFO: Python: 3.7.8
116 INFO: Platform: Windows-10-10.0.18362-SP0
126 INFO: wrote C:\Users\j\PycharmProjects\untitled\pictureValidation.spec
129 INFO: UPX is not available.
137 INFO: Extending PYTHONPATH with paths
['C:\\Users\\j\\PycharmProjects\\untitled',
 'C:\\Users\\j\\PycharmProjects\\untitled']
137 INFO: checking Analysis
222 INFO: checking PYZ
242 INFO: checking PKG
320 INFO: Building because C:\Users\j\PycharmProjects\untitled\build\pictureValidation\pictureValidation.exe.manifest changed
320 INFO: Building PKG (CArchive) PKG-00.pkg
3737 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
3830 INFO: Bootloader c:\users\j\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw_d.exe
3831 INFO: checking EXE
3884 INFO: Building because console changed
3885 INFO: Building EXE from EXE-00.toc
3888 INFO: Appending archive to EXE C:\Users\j\PycharmProjects\untitled\dist\pictureValidation.exe
3920 INFO: Building EXE from EXE-00.toc completed successfully.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by AllStarsAT** [comment]
UPDATE: I used the pyi-archive_viewer to check what is wrong and found only a couple of archives ... not including any of the api-ms-win-crt-*.dll and not the python37.dll. Checking out a working .exe that was compiled using pyinstaller with the pyi-archive_viewer I realised that all of these files are included in that .exe file. Does anybody happen to know the root of this issue?

**Comment by bwoodsend** [comment]
I'm not able to reproduce exactly. I get `Fatal error detected: Failed to execute pyiboot01_bootstrap` in a pop-up. I think it's enough just to not have `python37.dll` in your `PATH` to see this as it behaves the same on my machine as it does on another without Python.

| Build Command | Output |
| -----------| ------------|
| `PyInstaller -D --debug=all --clean test.py` | OK |
| `PyInstaller -D --clean test.py` | OK |
| `PyInstaller -D -w --debug=all --clean test.py` | Error |
| `PyInstaller -D -w --clean test.py` | OK |

Using `--onefile` gives the same outcomes. So it seems to be the combination of `-w` and `--debug=all`. @AllStarsAT How does this correlate with what your getting?

As for your `pyi-archiive-viewer` logs - Your not very clear where each of them came from. A `--onefile` exe should contain all those dlls but a `-D` shouldn't as their left just in the bundle folder rather than the executable. Again, is that what you're seeing?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
