### ISSUE TITLE
Make the process simpler.

### ISSUE THREAD

**Issue by ThisIsACoolBoy** [pyinstaller/pyinstaller#5005]
Im working on an installer for my repos but this thing is so advanced.

plz let me know when it finishes ^v^

**Comment by bwoodsend** [comment]
Uhmm. We are trying. Anything specific you can point to?

**Comment by htgoebel** [comment]
@ThisIsACoolBoy Please read the manual. If you need more support, please ask on the mailinglist. This is not a forum, but a bug tracker.

**Comment by ThisIsACoolBoy** [comment]
@bwoodsend, something like an GUI / Menu.

**Comment by bwoodsend** [comment]
@ThisIsACoolBoy [auto-py-to-exe](https://pypi.org/project/auto-py-to-exe/) is exactly that - Although it's quite minimal. There is another, more comprehensive, GUI in the making but it's only just started so you'll have to wait before it's even available.
