### ISSUE TITLE
compiled exe keeps coming back to the user input part

### ISSUE THREAD

**Issue by digilevi2006** [pyinstaller/pyinstaller#5007]
Hi,

I did compiled my script using pyinstaller, but when I double click it, it keeps coming back to the str(input part...
I'm using multiprocessing

But it's working fine on double clicking the py script.

I was successful in my other script but this one, no luck... I've tried to comment  out all user inputs but still the same.

Can you help me figure out please?

Thanks

**Comment by Legorooj** [comment]
@digilevi2006 can you please post the build log?

**Comment by digilevi2006** [comment]
Hi @Legorooj,

Thank you for your reply. Here it is... By the way, I was successful in mac using virtualenv. 


[xref-viewYout-win.txt](https://github.com/pyinstaller/pyinstaller/files/4943325/xref-viewYout-win.txt)
[warn-viewYout-win.txt](https://github.com/pyinstaller/pyinstaller/files/4943326/warn-viewYout-win.txt)


The xref should be html...

By the way, why is it in Mac that I need to run it though terminal? Can i not just double click it like windows? Thanks.

**Comment by Legorooj** [comment]
@digilevi2006 when I say build log I mean the output you get when you run the pyinstaller command, not the warnfile and dependency cross-reference.

What do you mean, you have to run it from the command line? You should be able to double click. Where did you hear this?

**Comment by digilevi2006** [comment]
@Legorooj,

Sorry about that. Where should I get the log? in my build folder, I have these

![build](https://user-images.githubusercontent.com/34555101/87869240-a5302d80-c9d0-11ea-8689-874df5cf060c.jpg)


Which one of them? should i zip them all and upload?



 

> What do you mean, you have to run it from the command line? You should be able to double click. Where did you hear this?

Let me try this again later. :)

**Comment by digilevi2006** [comment]
Hi @Legorooj ,

When I double click the executable in MAC... I get this error:

So it's a module error?


 File "site-packages/selenium/webdriver/firefox/firefox_profile.py", line 80, in __init__
  File "shutil.py", line 309, in copytree
FileNotFoundError: [Errno 2] No such file or directory: ' /Users/dad/Library/Application Support/Firefox/Profiles/
[641] Failed to execute script viewYout-mac
zsh: failed to write history file /Users/dad/.zsh_history: permission denied

**Comment by digilevi2006** [comment]
@Legorooj 

I think you were talking about the cmd log? here it is


[log.txt](https://github.com/pyinstaller/pyinstaller/files/4943400/log.txt)

**Comment by digilevi2006** [comment]
Please everyone.

Anyone with a kind heart to support :)

**Comment by Legorooj** [comment]
@digilevi2006 the multiproccessing bug is a known issue with python 3.8. Python 3.8 is also currently unsupported, so until support is added we can't help. If this error occurs on python 3.7, then we can help. Otherwise, you'll have to wait.

**Comment by digilevi2006** [comment]
@Legorooj,

I'm sorry, I want to reopen this... I've tested it on python 3.7.7 using virtualenv and it seems result is the same.

here is the log

[log 3.7.txt](https://github.com/pyinstaller/pyinstaller/files/4943822/log.3.7.txt)


the cmd i envoke was 

`(viewYout_Common3.7) C:\Users\dad\Downloads\BOTS\viewYout_Common3.7\Scripts>pyinstaller.exe --onefile --paths C:\Users\dad\Downloads\BOTS\viewYout_Common3.7\Lib\site-packages C:\Users\dad\Downloads\BOTS\viewYout_Common3.7\viewYout-win.py`

**Comment by Legorooj** [comment]
@digilevi2006 please can you post an example program which I can use to reproduce this locally?

**Comment by digilevi2006** [comment]
@Legorooj 
Thanks for your reply bro.

Here are the 2 versions I made, I also tried to compile it using 3.4 but it's the same... did you want the py files? 

[made with 3.4.zip](https://github.com/pyinstaller/pyinstaller/files/4948185/made.with.3.4.zip)
[made with 3.7.zip](https://github.com/pyinstaller/pyinstaller/files/4948186/made.with.3.7.zip)

**Comment by Legorooj** [comment]
@digilevi2006 yes, the python source is what I need.

**Comment by digilevi2006** [comment]
@Legorooj 

I'm not a very good programmer, please be kind.  I just put these things together 🔢 
I assume there are mistakes to my code... 👍 

[sourcce.zip](https://github.com/pyinstaller/pyinstaller/files/4951900/sourcce.zip)

**Comment by Legorooj** [comment]
@digilevi2006 I've been unable to reproduce with your code. Could you try writing a new script to reproduce? One designed to reproduce this.

**Comment by digilevi2006** [comment]
@Legorooj 

Hi... that is the one I compiled... And I've also mentioned I have no problem with mac... 3.7... So, there's a problem with my windows?

**Comment by digilevi2006** [comment]
@Legorooj 

Hi bro, 

So, the code doesn't have mistakes because it's working on your side right? :)
Maybe I need to compile it from another pc then...

**Comment by Legorooj** [comment]
@digilevi2006 give me a day or two to work on this. No, the code isn't working for me, but I'm tracing the problem.

**Comment by digilevi2006** [comment]
Hi @Legorooj 

Maybe because I've inserted an invalid raw pastebin link
It's under __main__, 
on this line,

`links2 = getLinks2(`


so, it should be` links2 = getLinks2('https://pastebin.com/raw/HEjYza0C')`


Also, the 3.4 version, I'm not so confident about it, as I needed to downgrade some code lines. maybe mistakes are there

**Comment by digilevi2006** [comment]
@Legorooj 

Hi bro,

Any update on this? Thanks in advanced

**Comment by Legorooj** [comment]
@digilevi2006 not yet I'm afraid. I need some more time - hopefully I'll have had a thorough look by next weekend.

**Comment by digilevi2006** [comment]
Thank you for your response bro...

**Comment by digilevi2006** [comment]
Hi @Legorooj ,

I know you're busy, but I'm just following it up... Hope you had time to look on it. Thanks bro.

**Comment by Legorooj** [comment]
@digilevi2006 I've been unable to reproduce, and therefore can't offer any more support on this. Maybe try the mailing list or StackOverflow.

**Comment by digilevi2006** [comment]
@Legorooj 

Is the script not working bro OR working but not able to reproduce the issue? Thanks for your help

**Comment by Legorooj** [comment]
Both at first, but I got your script working - it needed a few minor tweaks. I wasn't able to reproduce the issue.

**Comment by digilevi2006** [comment]
@Legorooj,

Sorry for being persistent but, were you able to compile it and Working without looping to the input OR wasn't able to compile it to exe?

Would you mind to share the one with your tweaks bro? I want to test it on my virtualenv. thanks.

**Comment by Legorooj** [comment]
It wasn't looping for me when I compiled it. And sorry but no I can't share my tweaks; I've already cleared the data. I delete any scripts once an issue has been dealt with.

**Comment by digilevi2006** [comment]
So, it might have been your tweaks that made it working properly... There's a problem with my code then. Would you remember the things changed bro?

**Comment by Legorooj** [comment]
@digilevi2006, sorry, but no. I actually did all the work on this a couple of days ago but forgot to ping on here.

**Comment by digilevi2006** [comment]
Oh alas.

Anyway, thank you for your help, man.
