### ISSUE TITLE
Add test-cases for expected output on exit

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#5009]
Quoting from https://github.com/pyinstaller/pyinstaller/pull/4907#issue-425770243
> The error was that SystemExit - the standard script exit exception, raised by sys.exit and other exit functions, was handled as a normal exception, and the bootloader printed Failed to execute script X, before erroring.

Would be a good idea to have test-cases tsting teh expected behaviour. Cases which come to my mind are:
- `sys.exit(0)`, `sys.exit(1)`
- `raise SystemExit(0)`, `raise SystemExit(1)`
- `raise ValueError` (or any other exception that suites - actually covered by `test_option_w_ignore` which raises an AssertionError)
- … more?

@Legorooj Do you want to take care of this, as you already have been working in this area.
You could use `test_option_w_ignore` as an example. If the exe return-code is non-zero, `pytest.fail()` is called (see `PyInstaller/utils/conftest.py::_test_executables()`), so for these cases you need to something like `with pytest.raises(pytest.fail) as rc:`.

**Comment by Legorooj** [comment]
I'll get to this.
