### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by venustar2015** [pyinstaller/pyinstaller#5011]
I use fbs to pack the pyqt code **fbs run** is OK, but the application which created from **fbs freeze** cannot execute , but it report the error info like that:

> 
> Traceback (most recent call last):
>   File "src\main\python\main.py", line 1, in <module>
>     from fbs_runtime.application_context.PyQt5 import ApplicationContext
>   File "d:\program files\anaconda3\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\fbs_runtime\application_context\PyQt5.py", line 24, in <module>
> ImportError: DLL load failed: The specified procedure could not be found.
> [2308] Failed to execute script main

Does anybody have the same issue?

**Comment by bwoodsend** [comment]
@venustar2015 Can you please provide steps to reproduce as per the [bug report template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md). Otherwise we have no way to help you.

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
