### ISSUE TITLE
Issue pulling numpy.cov

### ISSUE THREAD

**Issue by o-mcelhin** [pyinstaller/pyinstaller#5019]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
When freezing code containing np.cov, program will build but will crash with no error when running the .exe

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```

* Version of Python: e.g. 3.7.3

* Platform: e.g GNU/Linux (distribution), Windows (language settings), OS X, conda, FreeBSD
Windows using an anaconda virtual environment

* Did you also try this on another platform? Does it work there?
Not tested on alternative platform

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
`if __name__ == '__main__':
    ph = np.zeros((10, 100))
    print('Test numpy with zeros')
    cov = np.cov(ph)
    print('Covariance output')`
```

Program was built with:

```pyinstaller test.py --onefile```

### Stacktrace / full error message

```
No error given
```

**Comment by bwoodsend** [comment]
I believe this is #4968 again. Try [this](https://github.com/pyinstaller/pyinstaller/issues/4968#issuecomment-662075970). I'm working on a more permanent solution at the moment.

**Comment by o-mcelhin** [comment]
That fix worked perfectly, thanks for the reply !
