### ISSUE TITLE
support for namespace packages

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#502]
**Original date**: 2012/02/05

PyInstaller fails to package zope.interface.

The workaround is to put an empty `__init__.py` in the zope/ directory.

**Comment by htgoebel** [comment]
Now that we are using modulegraph (#439), we need to check if all cases are covered. Here is a list:

Case | Test-Case | Packages
------|------|-------
1. i. just a directory | test_nspkg-pep420 | nspkg-pep420
1. ii. nspkg.pth file | test_nspkg2 | nspkg2-pkg
2. i. `__init__`-file using `pkg_resources.declare_namespace()` | test_nspkg1 | nspkg1-pkg/nspkg1_aaa.egg (unzipped eggs)
 | test_nspkg1-bbb-zzz | nspkg1-pkg/nspkg1_bbb.egg (zipped egg)
 | test_nspkg1-empty [1] | nspkg1-pkg/nspkg1_empty.egg
2. ii. `__init__`-file using `pkgutil.extend_path()` | **no testcase**

###### Notes
[1] namespace-only packages in an zipped egg. This package only defines namespace, nothing is contained there.

**Comment by htgoebel** [comment]
#1283 requests support for `pkgutil.extend_path()`, so we should implement it :-(

**Comment by matysek** [comment]
@htgoebel Is this already done?

**Comment by htgoebel** [comment]
This is done - according to https://github.com/pyinstaller/pyinstaller/issues/1283#issuecomment-131061632, even support for `pkgutil.extend_path()` is implemented. Thanks for reminding my on this issue.
