### ISSUE TITLE
Problem creating .exe when importing Pandas

### ISSUE THREAD

**Issue by manesh83** [pyinstaller/pyinstaller#5029]
Hi there,

I am trying to create an .exe-file from an existing python file via PyInstaller. For the sake of simplicity I wrote a very simple file called hello.py which looks like this:

hello.py
import pandas
print('hello')

Leaving out "import pandas" I don't have a problem at all, PyInstaller will create a perfectly working hello.exe. 

It would be great if someone had solved this problem and could help me out with this!
Thank you :)

**version**
conda 4.8.2
Python 3.7.6
pyinstaller 4.0.dev0
pandas 1.0.1
# Name                    Version                   Build  Channel
anaconda                  2020.02                  py37_0

**Comment by bwoodsend** [comment]
We need an error message to have any idea what the issue is. Run `dist\hello\hello.exe` from `cmd` and post the output.

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
