### ISSUE TITLE
Python 2.7 test suite fails on sysconfig.get_makefile_filename in CentOS 7

### ISSUE THREAD

**Issue by goodtune** [pyinstaller/pyinstaller#5030]
## Description of the issue

When running the test suite on the latest tag, the Python 2.7 tests fail on CentOS 7.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: 2.7
* Platform: GNU/Linux (CentOS 7.x)

## Example

The test program that ships with PyInstaller exhibits this issue - taken from `tests/functional/scripts/pyi_python_makefile.py`

```
>>> import sysconfig
>>> sysconfig.get_makefile_filename()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'get_makefile_filename'
>>> sysconfig._get_makefile_filename()
'/usr/lib64/python2.7/config/Makefile'
```

There is a solution supplied in pypa/virtualenv#1811 which I will use to address this in a pull request.

**Comment by Legorooj** [comment]
Does this _only_ fail on python 2.7? We don't support that anymore in the development version, so no PRs/fixes for python 2 will be accepted. 3.6 is the last release to support python 2.

**Comment by goodtune** [comment]
It would appear so, I encountered the issue on v3.6 tag of PyInstaller and tested against Python 2.7 and Python 3.6 with only the former failing.

**Comment by Legorooj** [comment]
@goodtune we don't accept python 2 only bug reports anymore I'm afraid, so I'm going to close this issue and the linked PR. Thanks for reporting this - hopefully anyone else who encounters this can use your fix themselves.
