### ISSUE TITLE
PyInstaller: clear log in cmd

### ISSUE THREAD

**Issue by snmnima** [pyinstaller/pyinstaller#5032]
Hi, how do I clear the `log` before starting the main program? I mean, I don't want these to be displayed before the program starts!
_(image attached in this post)_

```
python v3.7.0
PyInstaller v3.6
auto-py-to-exe v2.7.5
os: windows 7
```

my command:
`pyinstaller --noconfirm --onefile --console --key "qXx53d02m2PrszA1" --debug "all"  "<Script Location>"`

![log](https://user-images.githubusercontent.com/26420604/88530314-70e2ef80-d016-11ea-86b6-6c5beef4390b.PNG)

**Comment by snmnima** [comment]
@bwoodsend If I delete it, I get an error: _Failed to execute script_ !

**Comment by bwoodsend** [comment]
Ughh gross. The `--debug` option should never make or break an app. @snmnima Can you share the full error message with us? Run your app from `cmd` and copy paste what is says onto here. If you find copying in `cmd` awkward use `dist\app_name.exe >errors.txt 2>&1` then open the new file `errors.txt` and copy the contents instead.

**Comment by snmnima** [comment]
@bwoodsend This is my error after not using `--debug "all"` : `The system cannot find the path specified.`
and the text shown in cmd:
![text in cmd](https://user-images.githubusercontent.com/26420604/88602322-d3280880-d087-11ea-99ec-bb3e98d8fdbf.png)

**Comment by bwoodsend** [comment]
@snmnima Please copy/paste the error text or use the method from my last reply. Don't use a screenshot as we can only see the end of message. All the above screenshot tells us is that zlib tried to decompress something invalid...

**Comment by snmnima** [comment]
@bwoodsend I sent you both, your method and screenshot. I received this message in the `errors.txt` file: `The system cannot find the path specified.`

**Comment by bwoodsend** [comment]
> The system cannot find the path specified.

That just means you used the wrong filename. You need to replace `dist\appname.exe` with whatever your app's actual file path is.

**Comment by snmnima** [comment]
> 
> 
> > The system cannot find the path specified.
> 
> That just means you used the wrong filename. You need to replace `dist\appname.exe` with whatever your app's actual file path is.

thank you.

**Comment by Legorooj** [comment]
@snmnima is your executable working now?
