### ISSUE TITLE
pyinstaller fails to install with pip behind a proxy

### ISSUE THREAD

**Issue by alexchandel** [pyinstaller/pyinstaller#5035]
## Description of the issue

Pyinstaller fails to install from `pip` behind a proxy, hanging at the "build dependencies."  Even if all dependencies are installed, it still tries & fails to download build dependencies.  Even if the `--no-deps` flag is passed, it still tries & fails to download build dependencies.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```(N/A)```
* Version of Python: 3.7
* Platform: e.g Windows 2016 (English)

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [N/A] start with clean installation
  * [N/A] use the latest development version
  * [N/A] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [N/A] Package your program in **--onedir mode**
  * [N/A] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [N/A] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Use a computer that has no internet access except by HTTP proxy.  `pip` & every other package works fine with that.

```
python -mpip --proxy %MYPROXYIPADDR% install pyinstaller
```

### Stacktrace / full error message

```
call C:\ProgramData\User\\Environments\venv\Scripts\activate && python -mpip --proxy %MYPROXYIPADDR% install --no-deps pyinstaller
Collecting pyinstaller
  Using cached PyInstaller-3.6.tar.gz (3.5 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\User\Environments\venv\Scripts\python.exe' 'C:\ProgramData\User\Environments\venv\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\User\AppData\Local\Temp\pip-build-env-6dwtf8ii\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel
       cwd: None
  Complete output (7 lines):
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024712EEDB08>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
  WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024712EEDC08>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
  WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024712EFA308>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
  WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024712EF5F48>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
  WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ConnectTimeoutError(<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000024712EF5DC8>, 'Connection to pypi.org timed out. (connect timeout=15)')': /simple/setuptools/
  ERROR: Could not find a version that satisfies the requirement setuptools>=40.8.0 (from versions: none)
  ERROR: No matching distribution found for setuptools>=40.8.0
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\User\Environments\venv\Scripts\python.exe' 'C:\ProgramData\User\Environments\venv\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\User\AppData\Local\Temp\pip-build-env-6dwtf8ii\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- 'setuptools>=40.8.0' wheel Check the logs for full command output.
```

Note that compatible versions of `setuptools` and `wheel` are both already installed.  Pyinstaller fails to use pip's proxy, and shouldn't even be installing dependencies in the first place.

**Comment by Legorooj** [comment]
Try upgrading pip with `python -m pip install -U pip`, and if it still doesn't work raise an issue on https://github.com/pypa/pip and tag me on it.

**Comment by Legorooj** [comment]
@alexchandel pinging

**Comment by Legorooj** [comment]
This is a problem with `pip`, not PyInstaller.
