### ISSUE TITLE
ImportError: numpy.core.multiarray failed to import

### ISSUE THREAD

**Issue by WestbrookZero** [pyinstaller/pyinstaller#5042]
My environment is Win10 , Pytorch:1.15.1、Torchvision:0.6.1、numpy：1.19.1 , when i change Torchvision to 0.2.2. Post 3 , hiddenimports=['numpy.core._dtype_ctypes'] and change numpy to 1.18.5 or 1.16.4 or 1.15.0  still have this error :
Traceback (most recent call last):
File "detect.py", line 3, in <module>
File "d:\installpath\develop\anaconda3-5.1.0\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module
File "site-packages\torch\__init__.py", line 136, in <module>
ImportError: numpy.core.multiarray failed to import
[8580] Failed to execute script detect

**Comment by Legorooj** [comment]
Please ask this question on StackOverflow, Reddit, or the Mailing list.

**Comment by karimhasebou** [comment]
@WestbrookZero  Have you been able to find a work around

**Comment by shenyingying** [comment]
> My environment is Win10 , Pytorch:1.15.1、Torchvision:0.6.1、numpy：1.19.1 , when i change Torchvision to 0.2.2. Post 3 , hiddenimports=['numpy.core._dtype_ctypes'] and change numpy to 1.18.5 or 1.16.4 or 1.15.0 still have this error : Traceback (most recent call last): File "detect.py", line 3, in File "d:\installpath\develop\anaconda3-5.1.0\envs\yolov5\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 623, in exec_module File "site-packages\torch__init__.py", line 136, in
> ImportError: numpy.core.multiarray failed to import
> [8580] Failed to execute script detect

i meet the same question,have you solved now?

**Comment by Legorooj** [comment]
If you have this issue, please open a new one.
