### ISSUE TITLE
Compilation for MacOS

### ISSUE THREAD

**Issue by Egor-Dei** [pyinstaller/pyinstaller#5045]
I need to compile two programs on macOS. This requires access to macOS, which I don't have. You are required to unpack the files from the archive https://yadi.sk/d/-nwZzAE-SRnmIw.
[GROUPGAME.zip](https://github.com/pyinstaller/pyinstaller/files/5010282/GROUPGAME.zip)

 There will be files play_game.py and create_full_code.py. The first requires PyGame to be installed. I am not familiar with the poppy, so I ask for help here, the Windows itself is installed, the virtual machine is not installed.

You can do this using pyinstaller by entering the command pyinstaller --onefile --icon = path / to / "icon" play_game.py (preferably with an icon from the same archive), and also the command pyinstaller --onefile create_full_code.py. We only need the received programs, not verbal help. Help me please

**Comment by Legorooj** [comment]
Sorry, but we can't do this for you. I recommend setting up GitHub actions or azure pipelines to do this.
