### ISSUE TITLE
"failed to execute script" problem in the executable

### ISSUE THREAD

**Issue by Goutam-Mukherjee** [pyinstaller/pyinstaller#5048]
## I've faced a problem while opening the executable created by pyinstaller

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.7
* Platform: Windows 10

I got this problem while converting the .py file into .exe

I tried all the possible ways to fix it. I downloaded this from powershell at first but I tried the github developer version also and that didn't fix the problem. I tried the auto-py-to -exe even which was really a wasting of time. I tried it in several python versions by uninstalling each and installing again but I failed.  I searched the web, saw the solutions at stackoverflow and other sites but that didn't help. Finally I completely removed python and its all associate apps and reinstalled and got the same problem. Do find the attachments.
![SharedScreenshot](https://user-images.githubusercontent.com/69003334/89180719-f6831400-d5af-11ea-8c28-09b0102c883c.jpg)

### Whenever the exe is double clicked, it shows "Failed to execute script {script_name}" (for my case "main")

Please somebody fix this. It is taking my dream for a couple of days.

Thanks

**Comment by bwoodsend** [comment]
That's just an issue in your code. No point rearranging your environment. Launching your app from `cmd` usually gives you more information than launching from explorer. If it doesn't then you'll have to do it the long way - i.e. add lots of print statements and comment out lines in your code until you're able to find the exact line of code causing the issue. Raise a separate issue only if you've identified that line and you can't fix it.

**Comment by Goutam-Mukherjee** [comment]
Respected Sir,

You were right. The issue is in my code. I know this is not your subject
but if you have some time please help me out. Actually it is a simple
program to show a notification. The program is running successfully when
executed as a .py file but pyinstaller cannot make its executable. As per
your suggestion I put some print statements and here comes the amaze. When
"pyinstaller -w -F" is run, only the fatal error dialog box is shown but
when  only "pyinstaller" is run, the first two print statements are run. I
am puzzled about what's going on.
Please find the attachments.
Thanks for your time.

Regards,
Goutam Mukherjee

**Comment by bwoodsend** [comment]
Quoting the docs:

> -w, --windowed, --noconsole
> --
>  | Windows and Mac OS X: do not provide a console window for standard i/o. On Mac OS X this also triggers building an OS X > .app bundle. On Windows this option will be set if the first script is a ‘.pyw’ file. This option is ignored in *NIX systems.

That's exactly what _windowed_ means - no console to print into. So `print` does nothing, even when run from `cmd`. Generally you should never use this option unless you trust your code to never fail.
