### ISSUE TITLE
ERROR: gi repository 'GIRepository 2.0' not found. Please make sure libgirepository-gir2.0 resp. lib64girepository-gir2.0 is installed.

### ISSUE THREAD

**Issue by cqray1990** [pyinstaller/pyinstaller#5050]
when i use python3.6 to pack an program the errors comes as follows:

ERROR: gi repository 'GIRepository 2.0' not found. Please make sure libgirepository-gir2.0 resp. lib64girepository-gir2.0 is installed.

**Comment by unknown989** [comment]
which operating system are you using??

**Comment by unknown989** [comment]
if you're using linux, macOS try to find the library, i did only found v1 i don't know where you can find v2 but it's there somewhere, if you're using windows try to build it from the source, if none of these worked let me know

**Comment by unknown989** [comment]
download it manually :
https://distrib-coffee.ipsl.jussieu.fr/pub/linux/Mageia/distrib/cauldron/armv7hl/media/core/release/libgirepository-gir2.0-1.64.1-3.mga8.armv7

if you're using any of .deb distros follow the steps:
- 1 - sudo add-apt-repository universe
- 2 - sudo apt-get update
- 3 - sudo apt-get install alien
- 4 - alien -i packagename.rpm

if you're using any of .rpm distros just do the following :

- rpm -i packagename.rpm
