### ISSUE TITLE
PyInstaller 4.0 is causing extra-large executables

### ISSUE THREAD

**Issue by Legorooj** [pyinstaller/pyinstaller#5051]
This was first reported in #4932. After much confusion, we figured out the problem. However, I managed to replicate with `matplotlib` on Windows (#4932 was Linux-only), which caused a (onefile) executable of 1.02GB in size. When using PyInstaller 3.6, the same script (onefile) is only 27mb, or 60 when onedir.

Safe to say this blocks release 4.0.

This issue **HIGHEST PRIORITY** and takes precendence over any other issues. Please share any update as soon as you have it - even small things. 

Debugging steps:

* Find a smaller example that has a difference of ~20MB (eg tkinter) 
* `git bisect` from the `v3.6` tag

**Comment by bwoodsend** [comment]
@Legorooj I'm not seeing this at all. Using the tip of `PyInstaller/develop` commit 6b3f0efd91e192d7cd038a3e8e7530a9f1808a1c.

I've tried a minimal matplotlib which gives a 76MB bundle or a 32MB onefile:
```python
from matplotlib import pylab as plt
import numpy as np

t = np.linspace(0, 10, 100)
plt.plot(t, np.sin(t))
plt.show() 
```

And our go-to tkinter example which is 19MB bundle or 8MB onefile.

```python
import tkinter
from tkinter import ttk

root = tkinter.Tk()

msg = ttk.Label(root, text='It\'s working just fine.')

msg.grid()

root.mainloop()
```

This is exactly what I get with `PyInstaller==3.6`.

I'm not sure #4932 is related. In that the code depended on GI, which is sizeable part of the Ubuntu operating system. PyInstaller tried to bundle everything and anything GI related.

What's in your huge executables?

**Comment by Legorooj** [comment]
@bwoodsend with a fresh virtual environment and the following script:
```python
import tkinter
```
I'm getting a 20mb OneDir bundle with 4.0, but if I use the same venv with 3.6 I get 15mb.

**Comment by bwoodsend** [comment]
I get 20mb either way. Could you diff the two bundles? I use:

```bash
diff -r dist\pyi36\ dist\pyi40\
```

`diff` is a bash command so you'll probably need to use git bash. Window's analogous `COMP` command is horrible.

**Comment by Legorooj** [comment]
Damn this has vanished. Maybe it is the matplotlib backends. If I notice this again I'll reopen.
