### ISSUE TITLE
Removing console (likely) affects APScheduler execution 

### ISSUE THREAD

**Issue by Isquare1** [pyinstaller/pyinstaller#5052]
I used pyinstaller to bundle my programme and it has worked  great for me, so thanks for the great tool first of all! 

So the app I am freezing uses APScheduler to run several events at the same time. All the testing was done with the console activated, for debugging purposes. Now that I got it to work as it should, I removed the console window using -w or --windowed, so it is ready to be distributed to other people. In this console disabled mode, scheduling of the events is no longer correct and basically no scheduled events are being executed. Otherwise the GUI, SQL tables and all other components seem to work fine. 
I decided to log this here as a potential bug, because the programme has been thoroughly tested on various PCs and proved to work very well in console mode. On the contrary, in -w mode, the scheduling fails on two different PCs. 

Any insight into how console disabling affects pyinstaller bundling/exe performance might also help! Many thanks!

**Comment by amifunny** [comment]
@Isquare1 Delighted that you found it useful! Could you check if it does not work for even a small example including APSchedular?

**Comment by Legorooj** [comment]
@Isquare1 does using https://github.com/pyinstaller/pyinstaller-hooks-contrib/commit/286affd832cc8c781db2e5f6ba235e4de6291535 fix the issue?

**Comment by Isquare1** [comment]
Hi, apologies, I only just got back on this project. I included the the hook @Legorooj suggested but it still does not perform scheduled tasks (although this time the initially calculated scheduled time is correct, so it did help with one aspect). 
I implemented a logger to see what is going on, and here is the traceback : 

```
2020-08-07 11:33:26,723 - apscheduler.executors.default - ERROR - Job "Archiver (trigger: interval[0:01:00], next run at: 2020-08-07 11:34:26 BST)" raised an exception
Traceback (most recent call last):
  File "apscheduler\executors\base.py", line 125, in run_job
  File "script.py", line 478, in Archiver
  File "patoolib\__init__.py", line 521, in _create_archive
  File "patoolib\__init__.py", line 421, in run_archive_cmdlist
  File "patoolib\util.py", line 224, in run_checked
  File "patoolib\util.py", line 216, in run
  File "subprocess.py", line 339, in call
  File "subprocess.py", line 753, in __init__
  File "subprocess.py", line 1054, in _get_handles
OSError: [WinError 6] The handle is invalid
```

So this seems to be more of an issue with the patool library I use for archiving the files?

**Comment by Legorooj** [comment]
@Isquare1 patoolib doesn't work with PyInstaller  - and it can't be fixed by hooks of any kind. I suggest you use another library. So seeing as the hooks fixed the APScheduler issue, I'm going to close this.

**Comment by Isquare1** [comment]
It works fine with the console, I found a hook online which made it work very well :)

**Comment by Legorooj** [comment]
Hang on there's two patoolib's now... How are you installing it?

**Comment by Isquare1** [comment]
@Legorooj I just use pip install patool (if this is what you meant). I can try to find a link to the hook I am using, or I can post it directly here? 
Btw, has no one else encountered  **OSError: [WinError 6] The handle is invalid**  when calling a subprocess, while trying to run pyinstaller .exe without a console? 
The suggestion I've read online, to pass stdin as devnull does not work for me :(
