### ISSUE TITLE
Crypto module cause problem to run executable package

### ISSUE THREAD

**Issue by ashkanz77** [pyinstaller/pyinstaller#5055]
I am using the pyrebase to use Google Firebase but when I make the executable file, it's impossible run. 
Exists some problem with the module Crypto. Here is the minimal code

import crypto
import sys
sys.modules['Crypto'] = crypto
import pyrebase
print('Hello')

**Comment by amifunny** [comment]
@ashkanz77 Can you post the error log? Is it working without conversion to executable?

**Comment by ashkanz77** [comment]
Yes, it is working without conversion to executable. I installed the gcloud, but I get the following error when running the executable file:
pkg_resources.DistributionNotFound: The 'gcloud' distribution was not found and is required by the application

**Comment by amifunny** [comment]
Similar to https://github.com/googleapis/google-cloud-python/issues/4780. This comment will help - https://github.com/googleapis/google-cloud-python/issues/4780#issuecomment-484468542. 

Do consider submitting a PR to help others.

**Comment by Legorooj** [comment]
Closing - this issue has nothing to do with the `Crypto` module, and to fix the pyrebase error you need to write a hook. @amifunny has linked to the resources you need.
