### ISSUE TITLE
pyinstaller failed to find the resource file in library even though it is loaded in setup.py

### ISSUE THREAD

**Issue by vitsensei** [pyinstaller/pyinstaller#5056]
Hi,
I tried creating an executable that used [trimesh ](https://github.com/mikedh/trimesh) package.

However, I soon realised that one of the resource file for the package is not loaded in properly even though it is already specified in the [setup.py](https://github.com/mikedh/trimesh/blob/master/setup.py) file.

To recreate this problem, you can simply install the trimesh package and write a two line code:

```
import trimesh
print("Hi.")
```

The error I'm getting is:

> FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\ANHTRA~1\\AppData\\Local\\Temp\\_MEI10042\\trimesh\\resources\\units_to_inches.json'
> [7928] Failed to execute script Project

And here is the command line used:
`pyinstaller --onefile trimesh_test.py`

I used Pycharm's virtual environment so I'm not sure if that has any effect on this.

**Comment by amifunny** [comment]
@vitsensei Hi,
See similar issue https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/20. 

> The error is caused by PyInstaller not including the data files of `trimesh`. This error can be fixed by writing a hook for `trimesh.` 
> See [here ](https://pyinstaller.rtfd.io/en/latest/hooks.html)and a hook similar to what you'd need [here](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-dclab.py).

`C:\Users\ANHTRA~1\AppData\Local\Temp\_MEI10042\trimesh\resources\units_to_inches.json` is a data file of `trimesh` that hook will include.

Simple code for hook-
```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('trimesh'`)
```

Name this file as `hook-trimesh.py`. Add to a folder `hooks `in your work directory.

Now for conversion to executable use command -
`pyinstaller --onefile trimesh_test.py --additional-hooks-dir hooks`

Its that simple. Do consider submitting a PR with your `hook-trimesh.py` file to help others.

**Comment by vitsensei** [comment]
Worked like a charm. Thank you @amifunny :).
