### ISSUE TITLE
utils.hooks.collect_system_data_files() scans parent of the given path instead of the path itself

### ISSUE THREAD

**Issue by rokm** [pyinstaller/pyinstaller#5058]
I believe this could also be the cause of #5051 and #4932.

**The symptoms**

Trying to package a simple Gtk program:

```python
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

using `pyinstaller program.py --clean` using the current development version.

On linux (Fedora 32, using system-installed python and libraries), the above build command succeeds, but results in the whole `/usr/share` being pulled in.

On Windows (msys2/mingw64 environment), the packaging attempt fails, with a puzzling and a seemingly completely unrelated nonsensical error:
```
PermissionError: [Errno 13] Permission denied: 'C:/ProgramData/Microsoft/Windows Defender/IMpService77BDAF73-B396-481F-9042-AD358843EC24.lock'
```

**The cause**

On linux, the slew of `/usr/share` entries seems to come from the following lines in the [hook-gi.repository.Gtk.py](https://github.com/pyinstaller/pyinstaller/blob/d8e4621df273233ca379222e9a9425af0937fb3a/PyInstaller/hooks/hook-gi.repository.Gtk.py#L24):

```python
datas += collect_glib_share_files('fontconfig')
datas += collect_glib_share_files('icons')
datas += collect_glib_share_files('themes')
```

[collect_glib_share_files](https://github.com/pyinstaller/pyinstaller/blob/d8e4621df273233ca379222e9a9425af0937fb3a/PyInstaller/utils/hooks/gi.py#L213) in turn attempts to scan the given path as a sub-directory of the GLib data directories, as obtained from `GLib.get_system_data_dirs()`.

On linux, these are `['/home/rok/.local/share/flatpak/exports/share/', '/var/lib/flatpak/exports/share/', '/usr/local/share/', '/usr/share/']`. 

And on Windows, they are `['C:\\ProgramData', 'C:\\Users\\Public\\Documents', 'C:\\msys64\\mingw64\\share', 'C:\\msys64\\home\\Rok\\test\\program\\venv\\share']`.

So for the first call, we try scanning:
`/home/rok/.local/share/flatpak/exports/share/fontconfig`,
`/var/lib/flatpak/exports/share/fontconfig`,
`/usr/local/share/fontconfig`, and 
`/usr/share/fontconfig` [one by one using `collect_system_data_files()`](https://github.com/pyinstaller/pyinstaller/blob/d8e4621df273233ca379222e9a9425af0937fb3a/PyInstaller/utils/hooks/gi.py#L225).

However, the `collect_system_data_files` ends up scanning not the given path, but its parent instead. This is why whole `/usr/share` is picked up on linux (instead of `/usr/share/fontconfig`), and why whole `C:\ProgramData` is picked up on Windows (instead of `C:\ProgramData\fontconfig`).

Specifically, [this `os.path.dirname()` call](https://github.com/pyinstaller/pyinstaller/blob/d8e4621df273233ca379222e9a9425af0937fb3a/PyInstaller/utils/hooks/__init__.py#L789) strips the last component of the input path, causing the remainder of the function to operate on its parent instead. 

This seems to be a regression introduced by 5d6715a24a51928658e38c26df596ca8ed7de386.

**Comment by Legorooj** [comment]
Ahah! It looks like you've tracked down the issue. I'll look at this in more detail when I have some time in the next few days. Thanks for figuring this out!

**Comment by Legorooj** [comment]
@rokm does Legorooj/pyinstaller@4af297efb65ee0cbb fix this?

**Comment by rokm** [comment]
Yes, removing the `dirname()` fixes the issue.

But I'm not entirely sure why it was added in the first place, and whether its removal reintroduces the issue that 5d6715a fixed...

**Comment by Legorooj** [comment]
@rokm I'll merge my commit in; if it causes a recurrence I'll dive into the problem more deeply.

**Comment by Legorooj** [comment]
Damn. CI isn't working (grr). Had to yank that commit.

**Comment by rokm** [comment]
I took a look at the `test_Qt5_QTranslate` that's failing on the AppVeyor.

The problem is that after the fix, the `qt.conf` file ends up in the `distroot`, and translations are therefore looked for in `distroot\translations` instead of `distroot\PySide2\translations`. Prior to the fix, the  `qt.conf` is correctly placed into `distroot\PySide2` and translations are therefore correctly looked for in `distroot\PySide2\translations`.

Now, although the pre-fix situation gives the correct result, it arrives there in an incorrect way:

[In `hook-PySide2.py`, we use `collect_system_data_files` to scan the PySide2's `PrefixPath`.](https://github.com/pyinstaller/pyinstaller/blob/0a59d8c4936ac04b88668beeea674e7bcf2afe33/PyInstaller/hooks/hook-PySide2.py#L26), and then pick the `qt.conf` file from the gathered files list. [On Windows, we also specify target directory to be the distroot instead of its PySide2 subdirectory.](https://github.com/pyinstaller/pyinstaller/blob/0a59d8c4936ac04b88668beeea674e7bcf2afe33/PyInstaller/hooks/hook-PySide2.py#L21)

With the version installed by PyPI on Windows, the `PrefixPath` is `'path-to-venv/lib/site-packages/PySide2/.'` The [path normalization](https://github.com/pyinstaller/pyinstaller/blob/0a59d8c4936ac04b88668beeea674e7bcf2afe33/PyInstaller/utils/hooks/__init__.py#L788) in `collect_system_data_files` cleans it into `'path-to-venv/lib/site-packages/PySide2'`. Then, due to the [problematic `dirname`](https://github.com/pyinstaller/pyinstaller/blob/0a59d8c4936ac04b88668beeea674e7bcf2afe33/PyInstaller/utils/hooks/__init__.py#L789), the function ends up scanning the parent `site-packages` instead of `site-packages/PySide2`. So when it finds `site-packages/PySide2/qt.conf`, the resulting target path becomes `./PySide2/qt.conf`, which is correct - but only because the starting path for the search was the parent `site-packages`.

On the other hand, after the fix, the function finds the `qt.conf` file in the starting directory, and places it directly into target directory. The target directory, in turn, should be `PySide2` instead of `os.curdir` (i.e, the special case for Windows should be removed).

**Comment by rokm** [comment]
As a side note, without 4eba630 applied, if both PySide2 and PyQt5 are installed (e.g., on the CI), the `qt.conf` files from both are pulled into distribution directory ('`.\PyQt5\Qt\bin\qt.conf'` and `'.\PySide2\qt.conf'`) when packaging a PySide2 application. The file from PyQt5 has no effect, except for possible confusion...

**Comment by Legorooj** [comment]
I need to take a deeper look at this - give me a few days.

**Comment by LeighKorbel** [comment]
Yes, this is precisely the *additional* issue coming up in MSYS2/MinGW on https://github.com/pyinstaller/pyinstaller/issues/4996.

**Comment by bwoodsend** [comment]
For what it's worth: `collect_system_data_files()` isn't used very much.
```shell
λ grep -r --include=*.py collect_system_data_files ./PyInstaller
./PyInstaller/hooks/hook-PyQt5.py:from PyInstaller.utils.hooks import collect_system_data_files
./PyInstaller/hooks/hook-PyQt5.py:             collect_system_data_files(pyqt5_library_info.location['PrefixPath'],
./PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py:    collect_system_data_files
./PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py:            datas += collect_system_data_files(
./PyInstaller/hooks/hook-PySide2.py:from PyInstaller.utils.hooks import collect_system_data_files
./PyInstaller/hooks/hook-PySide2.py:         collect_system_data_files(pyside2_library_info.location['PrefixPath'],
./PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py:    collect_system_data_files
./PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py:            datas += collect_system_data_files(
./PyInstaller/utils/hooks/gi.py:from ..hooks import collect_submodules, collect_system_data_files, eval_statement, exec_statement
./PyInstaller/utils/hooks/gi.py:        collected += collect_system_data_files(p, destdir=destdir, include_py_files=False)
./PyInstaller/utils/hooks/gi.py:        collected += collect_system_data_files(p, destdir=destdir, include_py_files=False)
./PyInstaller/utils/hooks/__init__.py:def collect_system_data_files(path, destdir=None, include_py_files=False):
```
So the only hooks we need to worry about (and test still work) are the PyQt5/PySide2 ones and gi.

**Comment by rokm** [comment]
I did some investigation into implications of fixing this issue. The main issue is that fixing the jump to parent directory changes the path of the returned collected files. Before the fix, due to the jump, they are prefixed with the last component of the input search path. After the fix, this prefix is gone, but all hooks are relying on it to be there (they shorten their target/destination paths to match the behavior). 

Below, there's a list of occurrences of `collect_system_data_files()`, along with the notes on the current behavior and proposed fixes.


------------------------------------------------------------------------


```
./PyInstaller/utils/hooks/gi.py
14:from ..hooks import collect_submodules, collect_system_data_files, eval_statement, exec_statement
225:        collected += collect_system_data_files(p, destdir=destdir, include_py_files=False)
242:        collected += collect_system_data_files(p, destdir=destdir, include_py_files=False)
```

Both `collect_glib_share_files` and `collect_glib_etc_files` need to be fixed.

Each of them accepts `*path` - components of path relative to shared data dir. For example, `[ 'glib-2.0', 'schemas' ]`, to scan the `/usr/share/glib-2.0/schemas` (with `/usr/share` being one of possible paths returned by `get_glib_system_data_dirs()`).

Then it explicitly sets the `destdir`:
```python
destdir = os.path.join('share', *path[:-1])
```

It omits the last element of the path, because it assumes that the paths collected by `collect_system_data_files` will include it. This was true due to #5058 and consequent scanning of the parent dir. In the above example, `/usr/share/glib-2.0` was scanned instead of `/usr/share/glib-2.0/schemas`, so the discovered files looked like this: `schema/gschema.dtd`.

After fixing #5058, `/usr/share/glib-2.0/schemas` is scanned as intended, and discovered file from the above example becomes: `gschema.dtd`

So the `destdir` needs to be fixed to include the full search path:
```python
destdir = os.path.join('share', *path)
```

------------------------------------------------------------------------


```
./PyInstaller/hooks/hook-PySide2.py
13:from PyInstaller.utils.hooks import collect_system_data_files
26:         collect_system_data_files(pyside2_library_info.location['PrefixPath'],
```

The `target_qt_conf_dir` needs to be adjusted.

The `qt.conf` needs to be stored to the `PrefixPath` (i.e., the path returned by `pyside2_library_info.location['PrefixPath']`).

In Windows version of PySide2 (5.15), `PrefixPath` corresponds to `<site-packages>/PySide2`, and due to #5058, we end up scanning `<site-packages>`. So the `qt.conf` file is collected as `PySide2/qt.conf`, and `target_qt_conf_dir` up until now has been `'.'`.

In Linux version, `PrefixPath` is `<site-packages>/PySide2/Qt`. We end up scanning `<site-packages>/PySide2`, and so `qt.conf` is collected as `Qt/conf.conf`. Hence, `target_qt_conf_dir` up until now has been set to `PySide2`.

(On MacOS, the `qt.conf` does not seem exist, so this hook is not affected there.)

After fixing #5058, we scan the `PrefixPath` as intended, and on both OSes, `qt.conf` is collected simply as `qt.conf`, as expected. Which means that the `target_qt_conf_dir` needs to be adjusted accordingly, to `PySide2` on Windows and `PySide2/Qt` on Linux.


------------------------------------------------------------------------


```
./PyInstaller/hooks/hook-PySide2.QtWebEngineWidgets.py
16:    collect_system_data_files
53:            datas += collect_system_data_files(
```

The `collect_system_data_files` is used only on MacOS.

```
        # This is based on the layout of the Mac wheel from PyPi.
        data_path = pyside2_locations['DataPath']
        libraries = ['QtCore', 'QtWebEngineCore', 'QtQuick', 'QtQml',
                     'QtNetwork', 'QtGui', 'QtWebChannel',
                     'QtPositioning']
        for i in libraries:
            datas += collect_system_data_files(
                os.path.join(data_path, 'lib', i + '.framework'),
                prefix_with_path(rel_data_path, 'lib'), True)
```

For each entry in `libraries`, we try to collect its `.framework` data directory. For example, `<site-packages>/PySide2/Qt/lib/QtCore.framework`.

The target data path is set by `prefix_with_path(rel_data_path, 'lib')`, which becomes `PySide2/Qt/lib`.

Again, `collect_system_data_files` scans whole `<site-packages>/PySide2/Qt/lib/` and collects files with their .framework directory prefix (e.g., `QtCore.framework/Resources/Info.plist`).

This effectively identical scan is performed multiple times, and in turn collects all directories in `<site-packages>/PySide2/Qt/lib/`, not just those belonging to the specified libraries.

After fixing #5058, only requested directories are scanned, and the collected files' path shift accordingly (e.g., `Resources/Info.plist`).

Therefore, target path needs to be adjusted to
```
prefix_with_path(rel_data_path, 'lib', i + '.framework')
```

Note that because only requested directories are scanned, fewer data is collected. Which, albeit correct, might cause additional issues.

------------------------------------------------------------------------

```
./PyInstaller/hooks/hook-PyQt5.py
13:from PyInstaller.utils.hooks import collect_system_data_files
27:             collect_system_data_files(pyqt5_library_info.location['PrefixPath'],
```

Similar situation as with `hook-PyQt5.py`, except that `PrefixPath` is `<site-packages>/PyQt5/Qt` on both Windows and Linux. On Windows, `qt.conf` is located under `PrefixPath/bin`, while on linux, it is located under `PrefixPath/libexec`.

Therefore, after fixing #5058, the target path needs to be adjusted from `PyQt5` to `PyQt5/Qt` to prevent the file ending up in `PyQt5/bin` or `PyQt5/libexec`.

Interestingly enough, the `test_Qt5_QTranslate` on Windows seems to pass even if `qt.conf` is misplaced. But `test_PySide2_QWebEngine` does not.

------------------------------------------------------------------------

```
./PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py
15:    collect_system_data_files
32:            datas += collect_system_data_files(
```

Similarly to `hook-PySide2.QtWebEngineWidgets.py`, `collect_system_data_files` is used only on MacOS. The target path should be adjusted to
```
prefix_with_path(rel_data_path, 'lib', i + '.framework')
```

However, it looks like the pyinstall'd version  of test program from `test_PySide2_QWebEngine` does not work under Catalina and PyQt5/PyQtWebEngine 5.15 regardless of #5058 (it's looking for `QtWebEngineProcess` in wrong path - so that's a fight for another day...).

**Comment by rokm** [comment]
An alternative solution to adjusting the hooks for the new behavior of ```collect_system_data_files``` would be to prevent the jump to the parent directory during scanning, but return the collected filenames as if scan was performed on parent (i.e., prefixed with the last component of the input search path, which corresponds to current behavior).

This appears to be less invasive as it involves fewer (if any) adjustments to the hooks themselves.

On the other hand, the new behavior looks more correct, and the adjusted target paths in hooks correspond more closely to the actual situation.

**Comment by rokm** [comment]
Lastly, regardless of which approach we take, we might be in for at least some short-term pain, because under the old behavior, additional data was being pulled in, and some of that might actually be required.

For example, under MacOS Catalina with PySide 2 5.15, the following program,

```python
from PySide2.QtWidgets import QApplication
from PySide2.QtWebEngineWidgets import QWebEngineView
from PySide2.QtCore import QUrl

app = QApplication([])
view = QWebEngineView()
view.load(QUrl.fromLocalFile('nonexistant.html'))
view.show()
app.exec_()
```

which should display a "Your file was not found" page, display a blank window and spams the console with:

```
dyld: Library not loaded: @rpath/QtQmlModels.framework/Versions/5/QtQmlModels
dyld: Library not loaded: @rpath/QtQmlModels.framework/Versions/5/QtQmlModels
  Referenced from: /Users/rok/Development/pyinst-5058/program2/dist/web/PySide2/Qt/lib/QtWebEngineCore.framework/Helpers/QtWebEngineProcess.app/Contents/MacOS/QtWebEngineProcess
  Reason: image not found
```

Which is caused by `QtQmlModels` missing from the `libraries` in libraries `hook-PySide2.QtWebEngineWidgets.py`; and before the #5058 fix, it was picked up because whole `<site-packages>/PySide2/Qt/lib` was scanned...

**Comment by bwoodsend** [comment]
For the destination of the `collect_system_data_files()` output I think it should mirror the behaviour of `--add-data=source;dest`. I thinks it's easier to explain in `pathlib` than English here. With `source_dir` and `dest` as the input parameters and `source_file` an output from globbing `source_dir`:

```python
dest = destdir / Path(source_file).relative_to(source_dir)
```

And I guess we'll just have to live with the short-term pain. It sounds pretty minor to me.
