### ISSUE TITLE
importlib_resources: "Unable to find '<...>/site-packages/importlib_resources/version.txt' when adding binary and data files."

### ISSUE THREAD

**Issue by nathanielmanistaatgoogle** [pyinstaller/pyinstaller#5059]
## Description of the issue
With `Pyinstaller` 3.6, attempting to build an executable that contains `import importlib_resources` fails with `Unable to find '<...>/site-packages/importlib_resources/version.txt' when adding binary and data files.`. **WITH `pyinstaller 4.0.dev0` I AM NOT ABLE TO REPRODUCE THE ISSUE.**

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.8.2
* Platform: Ubuntu 20.04 LTS
* Did you also try this on another platform?
My employer's customized workstation Linux.

* Does it work there?
No.

* try the latest development version, using the following command:
```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
**HEY! USING THE LATEST DEVELOPMENT VERSION APPEARS TO REMEDY THE PROBLEM!!**

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
```python
import importlib_resources
```

### Stacktrace / full error message
```
nathaniel@pyinstaller-importlib-resources-defect:~/temp-temp$ ./my_venv/bin/pip freeze
altgraph==0.17
importlib-resources==3.0.0
pkg-resources==0.0.0
PyInstaller==3.6
nathaniel@pyinstaller-importlib-resources-defect:~/temp-temp$ ./my_venv/bin/pyinstaller --onefile --name=lol lol.py 
43 INFO: PyInstaller: 3.6
44 INFO: Python: 3.8.2
56 INFO: Platform: Linux-5.4.0-1021-gcp-x86_64-with-glibc2.29
57 INFO: wrote /home/nathaniel/temp-temp/lol.spec
60 INFO: UPX is not available.
61 INFO: Extending PYTHONPATH with paths
['/home/nathaniel/temp-temp', '/home/nathaniel/temp-temp']
61 INFO: checking Analysis
62 INFO: Building Analysis because Analysis-00.toc is non existent
62 INFO: Initializing module dependency graph...
63 INFO: Caching module graph hooks...
67 INFO: Analyzing base_library.zip ...
2260 INFO: Processing pre-find module path hook   distutils
2261 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'
4058 INFO: Caching module dependency graph...
4142 INFO: running Analysis Analysis-00.toc
4165 INFO: Analyzing /home/nathaniel/temp-temp/lol.py
4186 INFO: Processing module hooks...
4187 INFO: Loading module hook "hook-sysconfig.py"...
4195 INFO: Loading module hook "hook-xml.py"...
4227 INFO: Loading module hook "hook-pydoc.py"...
4228 INFO: Loading module hook "hook-encodings.py"...
4267 INFO: Loading module hook "hook-lib2to3.py"...
4268 INFO: Loading module hook "hook-xml.etree.cElementTree.py"...
4269 INFO: Loading module hook "hook-distutils.py"...
4270 INFO: Loading module hook "hook-importlib_resources.py"...
Unable to find "/home/nathaniel/temp-temp/my_venv/lib/python3.8/site-packages/importlib_resources/version.txt" when adding binary and data files.
```

**Comment by Legorooj** [comment]
Please use the development version; this bug has been fixed there.
