### ISSUE TITLE
Interact after running script

### ISSUE THREAD

**Issue by sean85914** [pyinstaller/pyinstaller#5060]
Hi, I have successfully used PyInstaller to build my console .exe file, 
but the console just closed after the script was run.

I wonder if it is possible that the console can interact with the user, 
i.e., execute XXX.exe as the command `> python -i XXX.py` in a Python-installed device, 
after the script was run?

**Comment by Legorooj** [comment]
@sean85914 could you clarify exactly what you mean by "interact with the user"? And you say the console just closes - is your script working or is it an error?

**Comment by bwoodsend** [comment]
@sean85914 You can always just slap the following into your code:

```python
import code
code.interact(local=globals())
```

This will switch to interactive mode with all your variables from your code still defined.

You can wrap it in with a `if "-i" in sys.argv: ...`  if you want to mimic the `python -i` behaviour.

**Comment by sean85914** [comment]
@bwoodsend  Sorry for my late reply.
The console is closed as expected since all lines are executed.
As you mentioned, after I added `code.interact(local=globals())`, 
the console can interact with user just like `python -i`
What I am developing now is an API, but currently only console-mode supported.
GUI would be the future work 😄
