### ISSUE TITLE
Adding icon or version causes pyside2  app to crash on start

### ISSUE THREAD

**Issue by Dariusz1989** [pyinstaller/pyinstaller#5066]
Hey

This is fairly interesting... I'm using spec with >

```
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          options,
          name='testApp',
          uac_admin=True,
          uac_uiaccess=True,
          strip=False,
          upx=False,
          icon = "default_icon.ico",
          version="S:/versionFileX.rc",
```

When ever I add either icon or version when I try to start the app windows just give me
`A referral was returned from the server.`
Nothing more is being said. I can see correct icon in explorer and corect details when I get file details. But the app will not start any more.

Win 10x64
Python 3.7x
PyInstaller 3.6
PySide2 + lots of other libs.

Any ideas how to bite it?

**Comment by bwoodsend** [comment]
>  PySide2 + lots of other libs.

We can't do anything without a minimal working example to reproduce the error. There could be no end of possible problems. 

> Any ideas how to bite it?

Try writing the smallest program you can which has this issue. Chances are you'll work it out for yourself just doing that.

We'll happily reopen this when you provide that minimal program.
