### ISSUE TITLE
Building docs yields "WARNING: unknown option: --additional-hooks-dir"

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#5069]
This seem to be caused by Shinx wanting to create a cross-reference to command-line-options, while we do not provide respective targets. See https://github.com/sphinx-doc/sphinx/issues/6221 and https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#directive-program.

Solution is to enhance `doc/help2rst.py` to augment the output. Maybe this can be done by monkey-patching PyInstaller to use a custom ArgumentParser (search the itnernet whether ther already is some).

Note: `doc/help2rst.py` is run automatically when building the manual (or the man-pages) using Sphinx. It is hooked into `doc/conf.py` and created the files `doc/man/_pyinstaller-options.tmp`, `doc/man/_pyi-makespec-options.tmp` and `doc/pyinstaller-options.tmp`.

**Comment by Legorooj** [comment]
Hmm this is a bit more complex than I thought. I think I'll rewrite the whole `help2rst` scheme - it will be less work overall.

**Comment by htgoebel** [comment]
Fixed in ad4a3d4809eaafdde0be5298400ee7ecbe2157a4 (which is referencing a wrong issue, which luckily does not yet exist.

**Comment by htgoebel** [comment]
Follow up: #5459
