### ISSUE TITLE
Add check for correct names of new-fragments

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#5070]
While releasing the last version, I was hindered by some news-fragments having the wrong filename. While this is not much of an issue, it  costs yet another few minutes to solve. But for a possible (half-)automated release pipeline, this would make some entries vanish from the change log.

The check could be part of the linting step.

Valid names are in <https://github.com/pyinstaller/pyinstaller/blob/develop/doc/development/changelog-entries.rst>

draft pattern: `([^.]+)\.(feature|bugfix|…)\.rst` -> validate with towncrier

**Comment by Legorooj** [comment]
@bwoodsend stick this in another new action instead of linting. It's neater.
