### ISSUE TITLE
build version not works and dist version works

### ISSUE THREAD

**Issue by isdito** [pyinstaller/pyinstaller#5081]
hello,

I execute pyinstaller interface.py and the buid version

![image](https://user-images.githubusercontent.com/602151/89996738-75044380-dc8b-11ea-873e-3cfde29b65d9.png)
 and the dist version

![image](https://user-images.githubusercontent.com/602151/89996831-949b6c00-dc8b-11ea-8b51-59e67ca449d4.png)

for extension I have problems with pyarmor with pyinstaller

https://youtu.be/tFSuwXfuqOo

I install the last dev verison of pyinstaller 4.1

reggards

**Comment by bwoodsend** [comment]
@isdito Please read the docs or we're going to have to block you. As I also told you in the last issue you raised, the executable in the `build` folder is not meant to be run (nor is anything else in that folder). You run and distribute the `dist` folder.

**Comment by isdito** [comment]
ok thank you.
