### ISSUE TITLE
import skimage.transform causes crash

### ISSUE THREAD

**Issue by elysoto** [pyinstaller/pyinstaller#5082]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
pyinstaller 4.0 and pyinstaller-hooks-contrib 2020.7 
Attempted on scikit-image 0.16.2 and 0.15.0

Program crashes without any detailed error when importing skimage.transform

Narrowed it down to skimage.transform.histogram_matching.py
possibly from warnings import warn
which would make it related to https://stackoverflow.com/questions/48712154/pyinstaller-warning-lib-not-found

or from ..exposure import match_histograms as mh

However, no warning or error is given anywhere.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: 3.7.7
* Platform: Windows-10-10.0.16299-SP0 with conda
* Did you also try this on another platform? Does it work there? Did not try.

warnings sourcemodule is included and shows up in warn-server

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
Just a simple

import skimage.transform

```

### Stacktrace / full error message

```
Popup message. No stacktrace caught.
xxx has stopped working
A problem caused the program to stop working correctly. Please close program
```

**Comment by bwoodsend** [comment]
If I had to guess it's probably [this numpy dll issue](https://github.com/pyinstaller/pyinstaller/issues/4968#issuecomment-662075970) but we don't support Conda so I'm closing this.

**Comment by elysoto** [comment]
Yes that was the issue. Thank you!
