### ISSUE TITLE
ImportError: No module named zope.interface

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#5083]
In continue to #5080, after applying the fix I encounter a different issue when compiled with the `noarchive` flag everything is working but when running the `exe` I get this error:
```
(test_debug) C:\Users\arossert\test_debug>dist\app\app.exe
Traceback (most recent call last):
  File "lib\site-packages\PyInstaller\loader\rthooks\pyi_rth_twisted.py", line 25, in <module>
    from twisted.internet import default
  File "C:\Users\arossert\test_debug\Lib\site-packages\twisted/internet/default.py", line 56, in <module>
    install = _getInstallFunction(platform)
  File "C:\Users\arossert\test_debug\Lib\site-packages\twisted/internet/default.py", line 52, in _getInstallFunction
    from twisted.internet.selectreactor import install
  File "C:\Users\arossert\test_debug\Lib\site-packages\twisted/internet/selectreactor.py", line 15, in <module>
    from zope.interface import implementer
ImportError: No module named zope.interface
[10208] Failed to execute script pyi_rth_twisted
```

Again the `zope.interface`, I tried to add `--hidden-import=zope` or `--hidden-import=zope.interface`, nothing worked.
I also tried to add a `hook` with `datas = collect_data_files('zope')` but this ends up with `ImportError` while trying to apply the hook

The only thing that worked (after reading on this on-line) is adding `__init__.py` to the `zope` root dir in my `site-packages`.
When compiling without the `noarchive` flag everything works without any patching.

Is there any way to solve this without adding files?

PyInstaller: 3.6
Pyhton: 2.7.18
Platform: Windows10

**Comment by bwoodsend** [comment]
`--hidden-import=zope.interface` is what you should be using. Or in a hook you'd use `hiddenimports = collect_submodules("zope")`.

**Comment by arossert** [comment]
@bwoodsend Thanks for the reply, I did try to use `--hidden-import=zope.interface` (had a typo in the original message) and it did not work, the same error appeared.

I did try it with Python 3.7.7 and PyInstaller 4.0 and it seems to work without adding any flags to the command.
My simple app script that reproduces this issue is:
```
from twisted.internet import reactor
```

As mentioned, this worked is the `-d noarchive` flag is not set, but when setting it in Python2 it gives this error.
I'm using a custom PyInstaller 3.6 with this patch applied for it to work on Python2 https://github.com/pyinstaller/pyinstaller/commit/f7168c866d7f2d583bf6eb00fbab647a513f64c1.

I guess that it might be another patch that needs to be applied in order for it to work but I can't find it

**Comment by bwoodsend** [comment]
Some logs to get you started.

```shell 
E:\notebooks\pyinstaller (develop)
λ git log --oneline | grep zope
6ceb91aa Tests: Requirements: Update zope.interface from 4.4.2 to 4.4.3
7341c83e Tests: Enhance test_zope_interface.
cc8aa73a Issue #1437: Remove old zope.interface test.
86ff9464 Issue #1437: Move zope.interface test to test_libraries.py.
2cf7654e Add support for `nspkg.pth`-style namespaces, used by e.g. zope.interface.
5822040f Add test-cased for namespace-pkg zope and zope.interface.
```
```shell
E:\notebooks\pyinstaller (develop)
λ git log --oneline | grep twisted
54ed9911 Tests: Requirements: Update twisted from 17.5.0 to 17.9.0
2c720d59 Issue #1402: Mark test_twisted and test_pyexcelerate as xfail.
e9b91f96 Issue #1402: Mark test_twisted and test_pyexcelerate as xfail.
c26325b2 Issue #1402: Mark test_twisted and test_pyexcelerate as xfail.
d5d884f1 Enh: Add tests for twisted reactor and qt4reactor.
5dc89af8 Enh: Add runtime hook for module twisted.internet.reactor.
```

2cf7654e looks a likely candidate. I'm afraid we really have ditched Python 2 support so I'm going to close this (although we can keep chatting on here if you think I can help).

**Comment by arossert** [comment]
@bwoodsend Thanks, I looked at the mentioned commit and it looks like a pretty old one (May 26, 2014) so most of the files there no longer exist in the current version, It looks like a lot of work to make it compatible to Python2.
As we are in a process to move to Python3, I will just create the `__init__.py` file in `zope` directory until we will stop using Python2.
