### ISSUE TITLE
ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

### ISSUE THREAD

**Issue by nimo94** [pyinstaller/pyinstaller#5087]
## ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.

* Output of `pyinstaller --version`: ```2020.something```
* Version of Python: e.g. 3.7
* Platform:, Windows 10 64bit
* Did you also try this on another platform? Does it work there?:No

### Stacktrace / full error message

```
(ERROR: ffprobe/avprobe and ffmpeg/avconv not found. Please install one.)
```

**Comment by bwoodsend** [comment]
Well that's an improvement from #5084 one but you're still missing the minimal example to reproduce and we need the full stacktrace - not just the last line. Just edit this issue - don't create a new one.
