### ISSUE TITLE
Another "Failed to execute script" while building with matplotlib and numpy

### ISSUE THREAD

**Issue by quentinemusee** [pyinstaller/pyinstaller#5088]
## When i'm trying to build with one dir, I get a fatal error "Failed to execute script".
Indeed, my distpath has this essue while my workpath has an "error loading Python DLL".

## I'm using the following console command : 
pyinstaller.exe --clean --noconfirm --noconsole --onedir --noupx --distpath ".\dist_onedir" --workpath ".\build_onedir" Simulationv3.py

* Output of `pyinstaller --version`: 4.0
* Version of Python: 3.8
* Platform: Windows (french), without conda

* I tried the latest development version (4.1.dev0), but this is still wrong.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Importing my modules is enough to makes the error : 
import turtle
import numpy as np 
import matplotlib.pyplot as plt  
import matplotlib.animation as animation

### Fatel error : failed to execute script + filename

This is just a personnal project, but I would like to achieve it.

Have a nice day,

  Quentin

**Comment by bwoodsend** [comment]
> Platform: without conda

:rocket: :rocket: :rocket:

**Comment by bwoodsend** [comment]
Can we have the stack trace (the full error message when you run it)?

**Comment by bwoodsend** [comment]
Closing due to lack of response from the original author. Will re-open if you
(or anyone else who has this issue) gets back to us by commenting below.
