### ISSUE TITLE
Anaconda Installation: [2812] failed to execute script pyibbot01_bootstrap

### ISSUE THREAD

**Issue by Mohamed-Sharif** [pyinstaller/pyinstaller#5096]
Hello,
I have been trying to install Anaconda for several days and I have always got the same message error: `"Failed to create menus"`. I have tried all the available solutions to this problem from changing the path variable to delete my Java environment, this came without any success. I finally decided to set up a new windows and I got the same error. with the same problem. I think it is a problem with python installation rather than conda. 
![image](https://user-images.githubusercontent.com/68668775/90935728-23cf1f00-e404-11ea-995f-d1012b27258e.png)

**Comment by liupx1988** [comment]
Try to install KB2533623.
