### ISSUE TITLE
Error on launching index.exe

### ISSUE THREAD

**Issue by GamiDPC** [pyinstaller/pyinstaller#5100]
Error on launching index.exe

code
`
from pyrogram import Client
from flask import Flask, request
import base64
import urllib.parse
import config

flask = Flask(__name__)

app = Client(config.session_name, config.api_id, config.api_hash)

app.start()

@flask.route('/eval')
def eval_data():
    response = 'response:error'
    data = request.args.get('data')
    data = urllib.parse.unquote(data)
    data = base64.b64decode(data)
    response=eval(data)
    return str(response)

if __name__ == "__main__":
    flask.run(port=config.app_port)
`

![image](https://user-images.githubusercontent.com/17031085/90990718-4ef47280-e5ac-11ea-9b8c-04d34c81c1e4.png)

**Comment by bwoodsend** [comment]
You need to `--add-data` your `mime.types` file so PyInstaller knows to include it. See [adding data files](https://pyinstaller.readthedocs.io/en/stable/spec-files.html?highlight=add%20data#adding-data-files). I strongly recommend you debug `FileNotFoundError`s in `--onedir` mode then switch to `--onefile` when it's working.
