### ISSUE TITLE
Code signing and notarization fails on macOS .app bundles

### ISSUE THREAD

**Issue by scheffle** [pyinstaller/pyinstaller#5112]
When using the pyinstaller to create an .app bundle, the installer places a file called base_library.zip into Contents/MacOS. This file is the reason that notarization will fail. As already done with other non executable files, the base_library.zip must be placed into the Contents/Resources/ folder and a link must be made in Contents/MacOS, as described here: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/osx.py#L193

**Comment by motatoes** [comment]
Hey, I want to work on this issue. I am trying to reproduce a notorization issue so I compiled a python script with

`pyinstaller  -w --onedir  script.py`

which generated a script.app in the dist/ folder.

Now I want to perform Notorization. Do I need to create an Apple Developer account to get a developer_id from apple @scheffle or is there a way for me to reproduce this without going through this?

Platform: Macos Mojave

**Comment by scheffle** [comment]
For notarization you need to have a paid developer account at Apple. I don't think that there's another way to reproduce it, sorry.

**Comment by BoboTiG** [comment]
FTR I am using codesign + noatrization with success since the beginning. You just need to codesign every files in the "MacOS" and some of the "Resources" subfolder of the app. Here is my [working script](https://github.com/nuxeo/nuxeo-drive/blob/c87b627361d73590d810bfde68d33e2b30c2530f/tools/osx/deploy_ci_agent.sh#L108-L133), if it can help.

**Comment by scheffle** [comment]
We are also able to code sign and notarize by changing the outcome of the installer. So it looks like your pull request will solve the issue we have.
