### ISSUE TITLE
Add `exclude` to utils.hooks.collect_all()

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#5113]
hook-gevent includes the complete test suite: `gevent.testing` and `gevent.tests`. These are collected by `utils.hooks.collect_all()`. While the modules can be excluded using `excludedimports = ["gevent.testing", "gevent.tests"]`, the datafile will still be collected and added to the bundle.

Please add an option to `utils.hooks.collect_all()` to allow excluding directories or files (based on glob). Some of the hook utils (e.g. `collect_data_files`) already can exclude files, these functions can be sued as a blueprint.

**Comment by RS357** [comment]
Hi @htgoebel, I took a look at this. 

The issue I can see is, `gevent.testing` and `gevent.tests` are collected in `collect_all` by `[collect_submodules](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/hooks/__init__.py#L1043`, and `collect_submodules` [returns](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/hooks/__init__.py#L529)  a list that contains the file names only - not their paths. 

As a result, I can't see a way to use glob to filter out modules from what is returned by `collect_modules` [here](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/utils/hooks/__init__.py#L1043). 

We can filter them out on the basis of filename alone, without using a path (which would mean not needing to use glob).  

Or am I not seeing something here?

**Comment by RS357** [comment]
@bwoodsend do you have any thoughts regarding my last comment?

**Comment by bwoodsend** [comment]
Hmm, I'm guessing what @htgoebel means is add and propagate the `excludes` and `includes` parameters from `collect_data_files` and the `filter` parameter from `collect_submodules`. (Maybe rename them to `exclude_datas` or something to make it clear what goes where.)

Then we could fix the `gevent` hook using something like:
```python
collect_all("gevent", filter_submodules=lambda x: "test" not in x)
```
