### ISSUE TITLE
gevent hook pulls in complete test suite and test-cases

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#5114]
How to reproduce:
- Install gevent
- In `tests/functional/test_libraries.py` add some line to the script in `test_gevent` to make the script fail. E.g. add "raise SystemExit(1)"
    This is only to keep the build data after the test run.  Our test-suite removes data on successful runs. (There might ne another way to keep the data, but I can't remember and have no time for searching for it.)
- Run `pytest tests/functional/test_libraries.py -k _gevent[onedir]`
- View the graph-xref in the browser, like this (path might vary):
    `xdg-open $TMP/pytest-of-*/pytest-current/test_gevent_onedir_current/build/test_source/xref-test_source.html`
- Result: You will see many modules in package `gevent.testing` and `gevent.test`.

A a quick work-around I added `excludedimports = ["gevent.testing", "gevent.tests"]` to hook-gevent (on my own branch ATM). Anyway these modules are collected to become hidden imports and thus being analyzed.We could save this time and electronic power.

Proposed solution:

These modules should be excluded in the first place, Implement `exclude` to utils.hooks.collect_all() (see #5113) to exclude these modules.

**Comment by bwoodsend** [comment]
Fixed by #5201.
