### ISSUE TITLE
Remove support for PyQt4 and PySide?

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#5118]
When shall we remove support for PyQt4?

Qt4 is [unsupported since 2015](https://en.wikipedia.org/wiki/Qt_version_history#Qt_4), the [last package of PyQt is from 2015](https://pypi.org/project/PyQt4/#history), while the current release of [Debian (Buster) still includes the packages](https://packages.debian.org/source/buster/python-qt4).

**Comment by bwoodsend** [comment]
In my opinion PyQt4 is a long distant memory. And last I tried, the hooks for it didn't work anyway. I'd certainly vote we remove then now.

**Comment by Legorooj** [comment]
@motatoes can you tackle this?

**Comment by motatoes** [comment]
@Legorooj I am on it
