### ISSUE TITLE
Rearrange test-suite: Move library test into other directory

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#5121]
Currently "core" tests, tests for the python standard library and external packages are mixed. I suggest rearranging this:
- `tests/functional`:
   - core tests
   - tests for the python standard library
   - tests near-standard packages (e.g. setuptools, pkg_resource, six, future, pkgutil)
- `tests/library`  - rethink name
  - tests for all other libraries and packages
  - preferably one file per library (Qt-related in one, of course)

This rearrangement esp. effects:
- django (currently `tests/functional/test_django`
- PyQtX and PySideX (currently in several files in `tests/functional`
- functional/test_import -> carve out Pyqt5 and others
- function/test_interactive -> split into libararies/test_ipython, libraries/test_pyside
   Maybe even drop the later, which is for Qt4 and xfail anyway.
- `functional/test_hooks/*`

**Comment by Legorooj** [comment]
I'm going to give this to @RS357. Can you manage this?

**Comment by htgoebel** [comment]
Addendum: Whle waiting for tests to finish, I had a closer look: 

For the tests in `functional/test_hooks/` I suggest
- keep here
  - test_hooks/test_pkg_resources.py
  - test_hooks/test_six.py
- move to `tests/library` (or how it will be called)
  - test_hooks/test_pil.py  (also see PIL-tests in tests_libraries)
  - test_hooks/test_gi.py
  - test_hooks/test_matplotlib.py
  - test_hooks/test_scipy.py
  - test_hooks/test_wx_lib_pubsub.py

- I'm unsure about requests, urllib3.packages.six (in tests_libraries)

**Comment by amifunny** [comment]
`test/external` would be good name?
Should `modules` and `data` folders be moved outside of both `functional` and `external` tests' folder?

**Comment by Legorooj** [comment]
@amifunny only what's needed for the tests that you move.

**Comment by htgoebel** [comment]
Thans for suggesting a name. Anyway for me "external" sounds like "things not belonging to us", maybe hooks pulled in from elsewhere. YMMV.

> Should modules and data folders

I'd copy the structure of these from one dir to the other (relative to the test-case). Then the test-fixtures should still be able to finde these files. If moving, we most probably would need to adjust fixtures.

**Comment by Legorooj** [comment]
@htgoebel we don't need to adjust fixtures; the hooks-contrib suite uses our fixtures without any adjustments.

@amifunny call it something like `tests/libraries`.

**Comment by Gairick52** [comment]
@Legorooj can you please assign this issue to me,i want to work on this

**Comment by bwoodsend** [comment]
Have fun.

**Comment by Legorooj** [comment]
Beat me to it :P. Have fun with this one!

**Comment by Gairick52** [comment]
@bwoodsend please share me guide for developers

**Comment by bwoodsend** [comment]
https://pyinstaller.org/en/stable/development/index.html

**Comment by Gairick52** [comment]
@bwoodsend thank you

**Comment by OmarEid451** [comment]
Do you still need help with this? I would like to be assigned to the issue, please.

**Comment by bwoodsend** [comment]
I'm not really convinced that it's worth the trouble but it's yours if you want it.

**Comment by tejaswini4996** [comment]
I want to work on this issue . would you like to assign me @legorooj

**Comment by Legorooj** [comment]
I would not recommend working on this issue - in fact I'm going to close this out for now, as it's not something that needs solving on it's own. Yes, PyInstaller's tests need work, however it should be done as part of a larger cleanup & rearrangement, and is not a good issue for a new contributor to work on.
