### ISSUE TITLE
exe run about 5 seconds in task list, then it exit, no tips in cmd,  it drives me crazy

### ISSUE THREAD

**Issue by MrWindWz** [pyinstaller/pyinstaller#5137]
## Version
Python 3.7.6
Pyinstaller 4.0
PyQt5                              5.12.1
PyQt5-sip                          4.19.19
pyqt5-tools                        5.12.1.1.5rc4
PyQtWebEngine                      5.12

## Problem: 
windows 10, It run ok in pycharm，it run ok in cmd by using "python client.py", but after use pyinstaller, no any tips when drag exe to run in cmd, you can see a process created in system  tasks list, then it exit after about 5 seconds!

## pyinstaller
- pyinstaller client.py -D -c 
- no tips in cmd

## Code
- "multiprocessing.freeze_support()" used
- "import PyQt5.sip" used

**Comment by MrWindWz** [comment]
![image](https://user-images.githubusercontent.com/15726324/92003584-ccba3a00-ed73-11ea-8f12-47da8755357c.png)

**Comment by htgoebel** [comment]
Pleas folliw the instructions in the issue template: No Images!

**Comment by MrWindWz** [comment]
> Pleas folliw the instructions in the issue template: No Images!

Sorry, I didn't notice
