### ISSUE TITLE
oct2py saving files from octave

### ISSUE THREAD

**Issue by gonebanana** [pyinstaller/pyinstaller#5139]
Hello!
I have python file that use oct2py via 
`import oct2py`
`oct = oct2py.Oct2Py(temp_dir=resource_path("."))`
`res = oct.test_writing(os.path.abspath(".")) `
According to test_writing.m octave function, a message in the output should be displayed and file saved_from_octave.csv should appear.
When I'm running this through PyCharm, it displays all Octave outputs and creates file, but if I make an .exe and run, it just skip these actions like there is nothing, and finihed program with only python output. On this way, I have no saved from Octave files (and also outputs). 
***saving path i send to the octave function correctly, so it should appear at the directory with .exe
I really need to have an opportunity to save data inside octave code, without necessity to  transfer data from Octave to Python.
Can you please help?

**Comment by bwoodsend** [comment]
You're using the current working directory which, if you're using `--onefile`, is probably some temporary dir. But either way you don't know where it's put them. I'm closing this as it's not an issue. If you just want to ask questions, use StackOverflow.

**Comment by gonebanana** [comment]
Temp folder I'm using only for the core of octave. 
Yes, I'm using `--onefile`, but I send to the func saving path  `os.path.abspath(".")`, which is that folder where exe is (i checked it several times). 
But if it is not the quastion for this place, I'm sorry.

**Comment by bwoodsend** [comment]
> which is that folder where exe is

Yes but the real exe isn't the one you think it is. A `--onefile` exe is just a shell round a `--onedir` build (see [here](https://pyinstaller.readthedocs.io/en/stable/operating-mode.html?highlight=onefile#how-the-one-file-program-works)). But you shouldn't assume the working directory even without PyInstaller. PyCharm gives you the illusion that it is fixed but in reality it could be anything.

**Comment by gonebanana** [comment]
Yes, but while running exe via console, it makes output from python code and `print(os.path.abspath("."))`  prints the directory with .exe file, and it also saves .scv file to this dirrectory.
It brokes when i'm trying to save file  to the same directory inside octave code! :(
