### ISSUE TITLE
bootloader add targets (--target-arch) 

### ISSUE THREAD

**Issue by necrose99** [pyinstaller/pyinstaller#5142]
**--target-arch=arm   --target-arch=arm64** --target-arch=risc-v (linux only atm)  
windows/linux 

https://github.com/benfogle/crossenv  would also be usefull..  ie pipeenv myarch 

https://sysprogs.com/ / https://gnutoolchains.com/download/ 

windows VS 2019 has some crude clang/windows / linux arm/arm64 support , can also point to gcc-corsstools or even linero too kits.. 

for Gentoo on RPI 64 bit , the tool dies often..  if figured if i can at least get boat-loader built i can drop **bdist_tarball** for **bootloader/s**  and be done with it.. 

however crossenv or etc might be of use to enable linux desktop or windows to cross-build the whole pkg to wheels or etc..

**Comment by bwoodsend** [comment]
This is redundant since we now ship arm compatible Linux wheels.

**Comment by necrose99** [comment]
pyinstaller-4.7-py3-none-musllinux_1_1_aarch64.whl 
And not glibc , 
And again gentoo has dev-lang/py2exe , eselet python,  to set shims. 
As one can pick pypy3 , 3.9 , 3.10 , 3.8 etc.. 
Hopefully it will compile on native aarch64 glibc. 
Gentoo builds all from sources and wheels are user only and not ever system level.

**Comment by bwoodsend** [comment]
I'm not sure what you're trying to say but [pyinstaller-4.7-py3-none-manylinux2014_aarch64.whl](https://files.pythonhosted.org/packages/64/73/550a84b35121c93ff2cb62374b1fe39776ecfe7e00c6b398c779f34f4fca/pyinstaller-4.7-py3-none-manylinux2014_aarch64.whl#sha256=5a130e2cf694975787026db1839b53c833b8d4922d850703c7076a06774cb6af) is glibc + aarch64.

**Comment by necrose99** [comment]
Pip install on gentoo is DANGEROUS.  Or can be ..
So it will require more manual means least temporarily.  And hopefully it
will rebuild from srcs correctly.  Or i can test a newer ebuild see if it
builds.


https://wiki.gentoo.org/wiki/Pip
☆☆《Warning
Running pip as root is not advised. It can render important system tools
like emerge useless.[1] <https://wiki.gentoo.org/wiki/Pip#cite_note-1>》


Michael R Lawrence m: 3179092009 a: 1901 Oak Creek Ln, Bedford Texas,
76022, Apt G.
https://www.linkedin.com/in/itsecmichaelrlawrence/
www.youracclaim.com/users/michael-lawrence.914a25b3/badges  e:
***@***.*** security Engineer Securonix

sent from mobile

**Comment by bwoodsend** [comment]
Only if you're running pip as the super user, which you should never be doing anyway on any platform, or if you're mixing pip with the system package manager.
