### ISSUE TITLE
Avoid unnecessary compiling disk path destinations entirely before including them from .py to .pyc into base_library.zip while using --onedir to build application.

### ISSUE THREAD

**Issue by web-sys1** [pyinstaller/pyinstaller#5143]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I want to build a one directory based python app while I use `--onedir` or `--onefile` , the `pyinstaller` (sub)command. The `base_library.zip` archive contains a large number of .pyc files with encodings. However, the situation is odd, because it may include source path from computer entirely (for instance, it might settle `c:\users\<username>\appdata\local\programs\python\<python-version>\lib\` in `*.pyc` files of that `base_library` archive), which becomes more confused.

**Describe the solution you'd like**
Maybe, you should look to review the [PyInstaller/building/makespec.py](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/makespec.py) and entire package. When `--clean` command is set, it cleans Pyinstaller cache while building an executable app. An spec file should follow conditions: analyzing source files and its library, not including `c:\` entirely, but include compiled files what to be specified in `base_library` archive.

**Comment by bwoodsend** [comment]
I'm sorry but you'll have to try to rephrase - I don't understand what you're saying. 

> The base_library.zip archive contains a large number of .pyc files with encodings.

This is how PyInstaller works - it includes compiled Python modules (`.pyc`s) instead of the original source code (`.py`s). Remove `functools.pyc` and `import functools` will raise a `ModuleNotFoundError`. Similarly, if you took away some or all the encodings then your app will be break depending on target machine locale. But don't take my word for it - delete them and you'll see for yourself.

**Comment by web-sys1** [comment]
@bwoodsend I am not sure, but please specify cause and make sure that `base_library.zip` will have amount of `.pyc` files 100% accurate. It depends on what source it is, if it is migrated to the library. Or, if not, it may be from that Python software.

**Comment by bwoodsend** [comment]
Again, I don't understand what you're saying...

**Comment by web-sys1** [comment]
@bwoodsend Embedded file from source path?

**Comment by web-sys1** [comment]
Otherwise, you should cloese this issue.

**Comment by Legorooj** [comment]
@web-sys1 can you include a screenshot of what you mean? It may clarify things.

**Comment by web-sys1** [comment]
![screenshoot2020_09_06_1306](https://user-images.githubusercontent.com/61905565/92325364-8fdf9300-f052-11ea-9eda-3710908fb052.png)

**Comment by web-sys1** [comment]
This is an screenshot related to ”contents” of compiled `.pyc` file.

**Comment by web-sys1** [comment]
@bwoodsend 
![Captură ecran (11)](https://user-images.githubusercontent.com/61905565/92325563-87885780-f054-11ea-9ed8-eb13ac96ac5a.png)

**Comment by BoboTiG** [comment]
Oh OK, I think I got it. You would like to include only revelant files in the archive, thoss actually used by your project and not the whole standard library. Right?

**Comment by web-sys1** [comment]
Alright.

**Comment by Legorooj** [comment]
@BoboTiG the whole std lib isn't included. Every file that's in `base_library.zip` is needed by the core python interpreter to run.

**Comment by BoboTiG** [comment]
@Legorooj yes I know, I just wanted to make the request clearer for everyone :)

**Comment by web-sys1** [comment]
> @BoboTiG the whole std lib isn't included. Every file that's in `base_library.zip` is needed by the core python interpreter to run.

> @Legorooj yes I know, I just wanted to make the request clearer for everyone :)

Have you done working on this? I've been waiting month-by-month to expect the results and I wonder that the repository is at point of new improvements. The last argument is enough to close the issue.

**Comment by rokm** [comment]
Hmm, if this issue was actually not about collecting modules but rather about leaking source file paths in the compiled pyc modules that are collected into `base_library.zip`, then this can be closed, as it was fixed in #5564.

**Comment by bwoodsend** [comment]
I'm not sure we ever did work out what the issue was but all the possible meanings I could see either already happen or shouldn't happen.
