### ISSUE TITLE
Facing issue to create app on Alpine

### ISSUE THREAD

**Issue by alpana17** [pyinstaller/pyinstaller#5151]
I created app using cmd: 'pyinstaller test.py' And also, with cmd 'pyinstaller  --exclude-module pycrypto --exclude-module PyInstaller test.py' on alpine container image.

It created app in /dist/test/test

When I tried to execute it, I got same error in both cases:
![image](https://user-images.githubusercontent.com/8611615/92452865-37d49800-f1dc-11ea-857b-002069b67b31.png)

Why is it so?

Here is my test.py
![image](https://user-images.githubusercontent.com/8611615/92453011-5fc3fb80-f1dc-11ea-9f2c-b1bce4b49e16.png)

**Comment by alpana17** [comment]
I tried one more thing..
launched fresh alpine container, then executed following cmds:

installing glibc
wget -q -O /etc/apk/keys/sgerrand.rsa.pub https://alpine-pkgs.sgerrand.com/sgerrand.rsa.pub
wget https://github.com/sgerrand/alpine-pkg-glibc/releases/download/2.32-r0/glibc-2.32-r0.apk
apk add glibc-2.32-r0.apk
------
apk add binutils
apk add python3
apk add py3-pip
pip3 install pyinstaller
vi test.py
	import os
	os.system('whoami')
pyinstaller  test.py

It created /dist/test/test
But getting following error on executing dist/test/test
![image](https://user-images.githubusercontent.com/8611615/92602664-0f2bcb80-f2cc-11ea-84f7-dfd000b35bbe.png)

**Comment by alpana17** [comment]
anyone looking into this?????

**Comment by htgoebel** [comment]
Also: The issue template clearly state to not post images, which you dod not care about. So why should anyone care about your problem then?

**Comment by bwoodsend** [comment]
I take it you're not using `mutliprocessing`? In which case `--exclude=multiprocessing` would (hopefully) skip `pyi_rth_multiprocessing`. As for why `pyi_rth_multiprocessing` raises a seg-fault... worry about that another time.

**Comment by alpana17** [comment]
@bwoodsend Thanks.. It worked to some extent..
Here are the commands that I executed:
    1  apk update
    2  apk add python3
    3  apk add binutils
    4  apk add zlib-dev
    5  apk add musl-dev
    6  ldd /usr/lib/libpython3.8.so.1.0
    7  ldd /usr/lib/libpython3.8.so.1.0
    8  apk add py3-pip
    9  pip3 install pyinstaller
   10  vi test.py
   11  pyinstaller --exclude=multiprocessing  test.py
   12  /dist/test/test

Output is:
![image](https://user-images.githubusercontent.com/8611615/92722501-55913100-f385-11ea-9518-05299c5ae42b.png)

Can you help me resolve this Segmentation fault also?

**Comment by htgoebel** [comment]
@alpana17 Please stop posting images!

**Comment by Legorooj** [comment]
@alpana17 please can you copy and post the output instead of posting images?

**Comment by bwoodsend** [comment]
@alpana17 Is that all it says? 

I take is `os.system('whoami')` is the breaking line? If you omit it then it works? A segfault is actually quite vague in that it could originate anywhere. Could you compile with the `--debug` flag, run, and paste the output?

It may be worth trying to compile a bootloader for Alphine on an Alphine machine but I'm guessing here.

Also can we please have plain text copy/pastes of errors in future - not screenshots? I want to be able to copy or quote fragments of stacktrace but I can't with a screenshot. I know copy/paste is awkward on Windows's shells.

**Comment by rokm** [comment]
At a quick glance, I'd say the problem is that Alpine builds against `musl` libc instead of `glibc`. And even if you install `glibc` manually, you're probably still using the official python build, which is built against `musl`...

So as @bwoodsend suggested, you should rebuild PyInstaller's bootloader in your Alpine container to have it linked against `musl`.

**Comment by alpana17** [comment]
@bwoodsend where do you want me to add --debug flag? Please mention the cmd.

@rokm yeah, I tried with https://github.com/six8/pyinstaller-alpine
It works

But I am trying to make pyinstaller work

**Comment by rokm** [comment]
Unless I missed something, you are installing pyinstaller via `pip` into a `musl`-based Alpine container (i.e., not using pyinstaller-alpine anymore). PyInstaller installed from pip comes with bootloader that was built against `glibc`, so I don't expect that combination to work.

(For the reference, bootloader is `run` (or `run_d` for debug version) executable that's located in `${prefix}/lib64/python3.8/site-packages/PyInstaller/bootloader/Linux-64bit`).

So you should follow https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html to build the bootloader from source, and then replace the bootloader files installed by pip with the resulting files in `build/release/run`  and `build/debug/run_d` .

Or, alternatively, check [the commands pyinstaller-alpine uses to checkout the pyinstaller source, build the bootloader, and then install it via pip](https://hub.docker.com/layers/six8/pyinstaller-alpine-linux-amd64/alpine-3.6-pyinstaller-v3.4/images/sha256-7acbe4778b4e0072e30d9327e839f96d47ca54a8e42b616a404a8a6ad4df2abc?context=explore) (see layer 17).

**Comment by bwoodsend** [comment]
@alpana17 My bad. `PyInstaller --debug=all  test.py`.

But I think @rokm is on the right track. You should clone this repo, build the bootloader yourself then install and run your newly built PyInstaller rather than the one from PyPI.

**Comment by alpana17** [comment]
here is the output:

bash-5.0# /dist/test/test
[222] PyInstaller Bootloader 3.x
[222] LOADER: executable is /dist/test/test
[222] LOADER: homepath is /dist/test
[222] LOADER: _MEIPASS2 is NULL
[222] LOADER: archivename is /dist/test/test
[222] LOADER: Extracting binaries
[222] LOADER: Executing self as child
[222] LOADER: set _MEIPASS2 to /dist/test
[222] LOADER: LD_LIBRARY_PATH=/dist/test
[222] LOADER: Registering signal handlers
[223] PyInstaller Bootloader 3.x
[223] LOADER: executable is /dist/test/test
[223] LOADER: homepath is /dist/test
[223] LOADER: _MEIPASS2 is /dist/test
[223] LOADER: archivename is /dist/test/test
[223] LOADER: Already in the child - running user's code.
[223] LOADER: Python library: /dist/test/libpython3.8.so.1.0
[223] LOADER: Loaded functions from Python library.
[223] LOADER: Manipulating environment (sys.path, sys.prefix)
[223] LOADER: sys.prefix is /dist/test
[223] LOADER: Pre-init sys.path is /dist/test/base_library.zip:/dist/test
[223] LOADER: Setting runtime options
[223] LOADER: Runtime option: v
[223] LOADER: Initializing python
import _frozen_importlib # frozen
import _imp # builtin
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import '_warnings' # <class '_frozen_importlib.BuiltinImporter'>
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
import '_frozen_importlib_external' # <class '_frozen_importlib.FrozenImporter'>
import '_io' # <class '_frozen_importlib.BuiltinImporter'>
import 'marshal' # <class '_frozen_importlib.BuiltinImporter'>
import 'posix' # <class '_frozen_importlib.BuiltinImporter'>
import _thread # previously loaded ('_thread')
import '_thread' # <class '_frozen_importlib.BuiltinImporter'>
import _weakref # previously loaded ('_weakref')
import '_weakref' # <class '_frozen_importlib.BuiltinImporter'>
# installing zipimport hook
import 'time' # <class '_frozen_importlib.BuiltinImporter'>
import 'zipimport' # <class '_frozen_importlib.FrozenImporter'>
# installed zipimport hook
# zipimport: found 148 names in '/dist/test/base_library.zip'
import '_codecs' # <class '_frozen_importlib.BuiltinImporter'>
import codecs # loaded from Zip /dist/test/base_library.zip/codecs.pyc
import encodings.aliases # loaded from Zip /dist/test/base_library.zip/encodings/aliases.pyc
import encodings # loaded from Zip /dist/test/base_library.zip/encodings/__init__.pyc
import encodings.utf_8 # loaded from Zip /dist/test/base_library.zip/encodings/utf_8.pyc
import '_signal' # <class '_frozen_importlib.BuiltinImporter'>
import encodings.latin_1 # loaded from Zip /dist/test/base_library.zip/encodings/latin_1.pyc
import '_abc' # <class '_frozen_importlib.BuiltinImporter'>
import abc # loaded from Zip /dist/test/base_library.zip/abc.pyc
import io # loaded from Zip /dist/test/base_library.zip/io.pyc
[223] LOADER: Overriding Python's sys.path
[223] LOADER: Post-init sys.path is /dist/test/base_library.zip:/dist/test
[223] LOADER: Setting sys.argv
[223] LOADER: setting sys._MEIPASS
[223] LOADER: importing modules from CArchive
[223] LOADER: extracted struct
[223] LOADER: callfunction returned...
# extension module '_struct' loaded from '/dist/test/_struct.cpython-38-x86_64-linux-gnu.so'
# extension module '_struct' executed from '/dist/test/_struct.cpython-38-x86_64-linux-gnu.so'
import '_struct' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7fa12f6222b0>
[223] LOADER: extracted pyimod01_os_path
[223] LOADER: callfunction returned...
[223] LOADER: extracted pyimod02_archive
[223] LOADER: callfunction returned...
# extension module 'zlib' loaded from '/dist/test/zlib.cpython-38-x86_64-linux-gnu.so'
# extension module 'zlib' executed from '/dist/test/zlib.cpython-38-x86_64-linux-gnu.so'
import 'zlib' # <_frozen_importlib_external.ExtensionFileLoader object at 0x7fa12f622d90>
[223] LOADER: extracted pyimod03_importers
[223] LOADER: callfunction returned...
[223] LOADER: Installing PYZ archive with Python modules.
[223] LOADER: PYZ archive: PYZ-00.pyz
[223] LOADER: Running pyiboot01_bootstrap.py
# PyInstaller: FrozenImporter(/dist/test/test?47656)
import os # PyInstaller PYZ
import stat # PyInstaller PYZ
import '_stat' # <class '_frozen_importlib.BuiltinImporter'>
import 'stat' # <pyimod03_importers.FrozenImporter object at 0x7fa12ecf5700>
# _collections_abc not found in PYZ
import _collections_abc # loaded from Zip /dist/test/base_library.zip/_collections_abc.pyc
import posixpath # PyInstaller PYZ
import genericpath # PyInstaller PYZ
import 'genericpath' # <pyimod03_importers.FrozenImporter object at 0x7fa12ecf5700>
import 'posixpath' # <pyimod03_importers.FrozenImporter object at 0x7fa12ecf5700>
import 'os' # <pyimod03_importers.FrozenImporter object at 0x7fa12ecf5700>
# ctypes not found in PYZ
[223] LOADER: Running test.py
testing here
[223] LOADER: OK.
[223] LOADER: Manually flushing stdout and stderr
[223] LOADER: Cleaning up Python interpreter.
# clear sys.audit hooks
# clear builtins._
# clear sys.path
# clear sys.argv
# clear sys.ps1
# clear sys.ps2
# clear sys.last_type
# clear sys.last_value
# clear sys.last_traceback
# clear sys.path_hooks
# clear sys.path_importer_cache
# clear sys.meta_path
# clear sys.__interactivehook__
# restore sys.stdin
# restore sys.stdout
# restore sys.stderr
# cleanup[2] removing sys
# cleanup[2] removing builtins
# cleanup[2] removing _frozen_importlib
# cleanup[2] removing _imp
# cleanup[2] removing _warnings
# cleanup[2] removing _frozen_importlib_external
# cleanup[2] removing _io
# cleanup[2] removing marshal
# cleanup[2] removing posix
# cleanup[2] removing _thread
# cleanup[2] removing _weakref
# cleanup[2] removing time
# cleanup[2] removing zipimport
# destroy zipimport
# cleanup[2] removing _codecs
# cleanup[2] removing codecs
# cleanup[2] removing encodings.aliases
# cleanup[2] removing encodings
# cleanup[2] removing encodings.utf_8
# cleanup[2] removing _signal
# cleanup[2] removing __main__
# destroy __main__
# cleanup[2] removing encodings.latin_1
# cleanup[2] removing _abc
# cleanup[2] removing abc
# cleanup[2] removing io
# destroy io
# cleanup[2] removing struct
# cleanup[2] removing _struct
# cleanup[2] removing pyimod01_os_path
# cleanup[2] removing pyimod02_archive
# cleanup[2] removing zlib
# cleanup[2] removing pyimod03_importers
# cleanup[2] removing _stat
# cleanup[2] removing stat
# cleanup[2] removing _collections_abc
# destroy _collections_abc
# cleanup[2] removing genericpath
# cleanup[2] removing posixpath
# cleanup[2] removing os.path
# cleanup[2] removing os
# destroy _signal
# destroy encodings
# destroy _abc
# destroy abc
# destroy posixpath
# destroy _stat
# destroy os
# destroy stat
# destroy genericpath
# cleanup[3] wiping pyimod03_importers
# cleanup[3] wiping zlib
# cleanup[3] wiping pyimod02_archive
# destroy zlib
# cleanup[3] wiping pyimod01_os_path
# cleanup[3] wiping _struct
# cleanup[3] wiping struct
# destroy _struct
# cleanup[3] wiping encodings.latin_1
# cleanup[3] wiping encodings.utf_8
# cleanup[3] wiping encodings.aliases
# cleanup[3] wiping codecs
# cleanup[3] wiping _codecs
# cleanup[3] wiping time
# cleanup[3] wiping _weakref
# cleanup[3] wiping _thread
# cleanup[3] wiping posix
# cleanup[3] wiping marshal
# cleanup[3] wiping _io
# cleanup[3] wiping _frozen_importlib_external
# destroy posix
# cleanup[3] wiping _warnings
# cleanup[3] wiping _imp
# cleanup[3] wiping _frozen_importlib
# destroy _thread
# destroy _warnings
# destroy _weakref
# cleanup[3] wiping sys
# cleanup[3] wiping builtins
[222] LOADER: Restoring signal handlers
[222] LOADER: freeing args
[222] LOADER: re-raising child signal 11
Segmentation fault

**Comment by bwoodsend** [comment]
Hmm, I don't see anything obvious in that runtime log. Try compiling the bootloader if you haven't already and if that doesn't work then I think we're stuck...

**Comment by Legorooj** [comment]
@bwoodsend you can run alpine on docker AFAIK

**Comment by alpana17** [comment]
yeah, I tried with https://github.com/six8/pyinstaller-alpine
It works

I am working on alpine container only
