### ISSUE TITLE
How to include C++ redist

### ISSUE THREAD

**Issue by w1-naserieh** [pyinstaller/pyinstaller#5152]
Hi all,
I'm working on a exe but I'm facing an issue.
The machine needs to have [vc_redist.x64.exe](https://support.microsoft.com/nl-nl/help/2977003/the-latest-supported-visual-c-downloads) installed, I want that python somehow auto installs the redist instead of me installing it manual.

What is the best way to approach this, is there a DLL that I can include in the .spec file or should I make something custom?

Thanks in advance!

**Comment by w1-naserieh** [comment]
bump

**Comment by htgoebel** [comment]
@w1-naserieh Your you impatient to get an answer? Just get a support contract: http://www.pyinstaller.org/funding.html

**Comment by bwoodsend** [comment]
This applies to any additional binary. 

If `vc_redist.x64.exe` is stand-alone (you can move it around without breaking it and doesn't depend on any other files) then you'd just `--add-binaries=/path/to/vc_redist.x64.exe;.` it. If it's normally found using `PATH` then you can use `binaries=[(ctypes.util.find_library("vc_redist.x64", ".")]` in your spec to avoid having to hard-code a full path to `vc_redist.x64.exe`. 

If `vc_redist.x64.exe` requires other files but is still portable (you can move it as long as you bring its dependents with it) then you need to `--add-binaries` or `--add-datas` it and any other file it depends on to preserve the directory structure. If `vc_redist.x64.exe` ends up not in the root of your app and your app requires it to be `PATH` findable then you will have to put something like the following at the top of your code to add it to `PATH` at runtime:
```python
if getattr(sys, "frozen", False):
    os.environ["PATH"] += os.pathsep + os.path.join(sys.MEIPASS, "directory in app containing vc_redist")
```

If `vc_redist.x64.exe` isn't portable then I'm afraid your stuffed. The best you can do is put a check with an informative error message at the top of your code.

I'm going to close this as this issue board is not a support forum. Questions like this are for StackOverflow.
