### ISSUE TITLE
Cannot run crosscompiled pyinstaller image on external device

### ISSUE THREAD

**Issue by jolatadla** [pyinstaller/pyinstaller#5153]
I am using pyinstaller 3.6 and python 2.7.

I wanted  to cross compile pyinstaller for mlinux. I used mlinux toolchain for installing arm-mlinux-linux-gnueabi-gcc and load environment:
```shell
curl http://www.multitech.net/mlinux/sdk/3.3.6/mlinux-eglibc-x86_64-mlinux-factory-image-arm926ejste-toolchain-3.3.6.sh > mlinux-toolchain-install.sh
chmod +x mlinux-toolchain-install.sh
./mlinux-toolchain-install.sh
source /path/to/sdk/environment-setup-arm926ejste-mlinux-linux-gnueabi
```
I downloaded pyinstaller3.6, went into that directory and build bootloader:
```shell
cd bootloader
sudo python ./waf all
```
After it I saw configured gcc:
![MicrosoftTeams-image](https://user-images.githubusercontent.com/38700255/92624529-e73a6900-f2c7-11ea-9a79-d14944a1f761.png)

Later I did two different ways and they both didn't end with success.

#### 1) compress whole pyinstaller directory and put on the external device with mLinux 5.1.8. I extracted files, went into main pyinstaller directory and instll it:
```shell
sudo python setup.py install
```
I got information `'No precompiled bootloader found.'`
![11](https://user-images.githubusercontent.com/38700255/92625769-60868b80-f2c9-11ea-8e6a-2b850b31c45f.png)

#### 2) I built own package including the build binaries with:
```shell
python setup.py sdist
```
Later I copied compressed package from dist directory and put it on the external device with mLinux 5.1.8. There I installed it with:
```shell
sudo pip install <name_of_package>.tar.gz
```
And got result:
![MicrosoftTeams-image (1)](https://user-images.githubusercontent.com/38700255/92626569-5b760c00-f2ca-11ea-8b93-0dfed9d1221b.png)

I can add that there is no gcc compiler on that external device.

**Comment by htgoebel** [comment]
> I am using pyinstaller 3.6 and python 2.7.

We are not loger supporting these version. Sorry.

Also: The issue tample clearly state to *not* post images, which you dod not care about. So why should I care abour your problem then?
