### ISSUE TITLE
exe file does nothing, only print("hello") in script

### ISSUE THREAD

**Issue by ma7heuzzz** [pyinstaller/pyinstaller#5159]
i'm using:
- Pyinstaller 4.0 
- Python 3.8
- Windows 10

my main script after create exe file does nothing, and then i try with a simple script with only print("hello") and does nothing too... 

no error, no messages in cmd, nothing in tasks, nothing... 

what i'm doing wrong?
i'm searching for help about 2 days in google, but any solutions fit to me...

Thanks...

**Comment by bwoodsend** [comment]
Are you using the `--windowed` option by any chance?

Regardless can we have the commands your using to build and run your app?

**Comment by ma7heuzzz** [comment]
Was incompatibility with python 3.8m5
i install py 3.8.6r and works fine.

i used windowed and not windowed options

Em sex, 11 de set de 2020 18:06, Brénainn Woodsend <notifications@github.com>
escreveu:
