### ISSUE TITLE
[Linux] Pyinstaller v-4.0 Creates a project> 1GB in size (Linux). Pyinstaller v-3.6 works correctly (project size 100MB)

### ISSUE THREAD

**Issue by Salim9304** [pyinstaller/pyinstaller#5160]
https://github.com/pyinstaller/pyinstaller/issues/4932
The problem is not actually solved

New parts.
Python3.7

Pyinstaller v4.0.
If you create a project in a virtual environment (pipenv), then the project takes up a size of 20MB. I can’t say for sure if it works correctly afterwards.
If you create a project in the system, then the project takes **1.5 GB.**

Pyinstaller v3.6.
If you create a project in a virtual environment (pipenv), then the project takes up a size of 20MB. I can’t say for sure if it works correctly afterwards.
If you create a project in the system, then the project takes up **100MB**

I tried pyinstaller v3.6 on another Linux distro. In pipenv, the project is created 20MB, but if you create a project in the system, then the project is created 400MB.

The conclusion is that the pyinstaller behaves inadequately in the system. It is the same in pipenv (but I suspect that the project does not work correctly after compilation, I cannot test it on other machines because of the new GLIB).

**Comment by rokm** [comment]
This is very likely due to #5058. In the system case, it probably ends up pulling in whole `/usr/share`.

**Comment by benjaminforest** [comment]
> This is very likely due to #5058. In the system case, it probably ends up pulling in whole `/usr/share`.

My opinion too. I had the same problem on macosx

**Comment by rokm** [comment]
With #5110 merged, this issue should be fixed now. If not, please open a new issue with updated details.
