### ISSUE TITLE
Using Pyinstaller with Pygubu GUI-builder

### ISSUE THREAD

**Issue by TimRi91** [pyinstaller/pyinstaller#5170]
After using the pygubu-GUI-module I would like to get an exe by using Pyinstaller.

Somehow pyinstaller does not include pygubu.

Does anybody know how this can be done?

My python-template-code with which i am trying to generate a exe:
In the same folder is the `pyapp.ui`-file for the GUI

```
import tkinter as tk
import pygubu


class Menu:
 
    def __init__(self, master):

        self.master=master
        #Create builder
        self.builder = builder = pygubu.Builder()
        #Load ui file
        builder.add_from_file('pyapp.ui')
        #Create a widget, using master as a parent
        self.mainwindow = builder.get_object('mainframe', master)

        #Connect callbacks
        builder.connect_callbacks(self)
    
    def but1(self):
        pass

    def but2(self):
        pass
    

if __name__ == '__main__':
    #Start Menu GUI
    root = tk.Tk()
    app = Menu(root)
    root.mainloop()`
```

**Comment by bwoodsend** [comment]
Can you be more specific as to what the error is? Please copy/paste the full error message so we don't have to guess.

> Somehow pyinstaller does not include pygubu.

Do you mean you get a `ModuleNotFoundError` for `pygubu` or something else?

A `pyapp.ui` isn't a Python source file so you have to explicitly add it as a data file using `--add-data=pyapp.ui;.` on Windows or `--add-data=pyapp.ui:.` on Unix. Did you do that?
