### ISSUE TITLE
Tensorflow error - (ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.)

### ISSUE THREAD

**Issue by ApurvaDani** [pyinstaller/pyinstaller#5173]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
I have installed tensorflow using conda and it works fine in the conda environment. I converted my app into binary file using pyinstaller. While running .exe file, it throws ImportError

Exact Steps Followed:
Used pyarmor pack command to convert my flask app to .exe file
First issue encountered: No module named tensorflow
Copied the tensorflow folder from the conda environment and pasted it in directory where app.exe is located. (Is there a better way to solve the import tensorflow issue?)
Now facing the Import Error
Is there something else, I need to copy to the working directory or a path to set?

## Context information (for bug reports)

* Output of `pyinstaller --version`: 3.6
* Version of Python: e.g. 3.7.8
* Platform: e.g GNU/Linux (distribution), Windows
* Did you also try this on another platform? Does it work there? Have not tried

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "<dist\obf\app.py>", line 3, in <module>
  File "<frozen app>", line 16, in <module>
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow.py", line 59, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow_internal.py", line 35, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "R:\armorfinal\cheque_locate_ws\dist\app\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "imp.py", line 242, in load_module
  File "imp.py", line 342, in load_dynamic
ImportError: DLL load failed while importing _pywrap_tensorflow_internal: The specified module could not be found.
[9200] Failed to execute script app
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
> No module named tensorflow

That just means your using a PyInstaller installed in the wrong environment. Using `python -m PyInstaller` instead of `PyInstaller` guarantees that you don't make this mistake.

And we [just fixed tensorflow](https://github.com/pyinstaller/pyinstaller-hooks-contrib/commit/15632f4eea9b639949b6bdc3fefd1325424b5c84) but this hasn't been released yet so you'll have to install the hooks repo from github.
```shell
pip install -U PyInstaller
pip install https://github.com/pyinstaller/pyinstaller-hooks-contrib/archive/master.zip
```
