### ISSUE TITLE
Errno 22 Invalid argument

### ISSUE THREAD

**Issue by JanStarman** [pyinstaller/pyinstaller#5174]
File "c:\users\name\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\building\api.py", line 622, in assemble
    with open(exe, 'rb') as infh:
OSError: [Errno 22] Invalid argument: 'C:\\Users\\name\\PycharmProjects\\excel_script\\build\\main\\run.exe.y1smt00n'

Hi, can someone help with this problem?
It occurs when i run $pyinstaller -F main.py
I have only one python file but with multiple dependencies on libraries such as Pandas etc. and its also working with few excel files.

Interestingly the problem doesnt occur when I run same command without -F / --onefile.

The directory where I try tu run pyinstaler looks like this:
 | .idea
 | venv
 | excel1.xlsx
 | excel2.xlsx
 | main.py

Thank you very much!

**Comment by bwoodsend** [comment]
@JanStarman Please fill in the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md). We can't diagnose anything based on the last 3 lines of a stacktrace.
