### ISSUE TITLE
Gtk Hooks collects whole /usr/share folder on macosx

### ISSUE THREAD

**Issue by benjaminforest** [pyinstaller/pyinstaller#5176]
Hi,
Thanks a lot for the great works done here.
I'm packaging a gtk app under macos, and it seems that the function `collect_glib_share_files` from PyInstaller/utils/hooks/gi.py is collecting ['/usr/local/share/', '/usr/share/']. Which is quite too much, as commented below in the code.

I'm using a gtk installed using Homebrew.
It seems that the problem is that there is a missing trailing "/" when os.path.join(data_dir, *path) is called, leading to a misunderstanding with collect_system_data_files().

Am I missing something or is this a bug ? If so, I can help to solve it but I'm quite new to PyInstaller.
All the best,

**Comment by rokm** [comment]
This sounds like #5058 (collecting the `/usr/share` instead of e.g., `/usr/share/fontconfig` for Gtk applications). 

Can you try using the branch from #5110 to see if it fixes the problem for you? I.e., install the pyinstaller via:
```pip install https://github.com/rokm/pyinstaller/archive/fix-5058.zip```

(If not, then it is a separate issue).

**Comment by benjaminforest** [comment]
That's it !
Thanks a lot
