### ISSUE TITLE
Trying to bundle geckodriver.exe but doesn't work

### ISSUE THREAD

**Issue by digilevi2006** [pyinstaller/pyinstaller#5177]
Hi everyone,

Is the --add-binary option still working?

I've tried `-F --add-binary "geckodriver.exe;."` but the converted file still try to look for the executable in the path... 
`Message: 'geckodriver.exe' executable needs to be in PATH.`

I've also tried `-F --add-binary ".\\geckodriver.exe;.\\"`

I'm on windows and I tried python 3.8.3 and 3.7 in virtualenv.

Would appreciate any insight on the problem. Thanks.

**Comment by bwoodsend** [comment]
The `--add-binary` doesn't search your computer for you. You must give it a full path. e.g. `--add-binary "C:\program files\gecko\geckodriver.exe";.` (note single `\`s in shell).
