### ISSUE TITLE
Support for python 3.8.3

### ISSUE THREAD

**Issue by Dihfahsih1** [pyinstaller/pyinstaller#5185]
I am trying to use current pyinstaller with python 3.8.3 but when i run pyinstaller --onefile filename.py, it creates an empty dist folder without the exe. Is the support for the python 3.8.3 out yet or not supported for now?

**Comment by bwoodsend** [comment]
Python 3.8.3 is supported and works fine for me. Whatever your issue is, it's unlikely to be Python version specific.

**Comment by johnthagen** [comment]
Doesn't there latest version published to PyPI only support 3.5-3.7? Isn't using the `master` branch currently required for Python 3.8?

**Comment by bwoodsend** [comment]
@johnthagen It's the `develop` branch but yes, PyInstaller 4.0 isn't strictly speaking compatible with Python 3.8 but only just. We had a couple of 3.8 only issues when we released 4.0 so most people get away with using it anyway. But @Dihfahsih1's issue doesn't sound like a 3.8 issue.
