### ISSUE TITLE
Error while freezing with PyObjC/PySide2

### ISSUE THREAD

**Issue by Merkwurdichliebe** [pyinstaller/pyinstaller#5188]
## Description of the issue

When freezing I get an error apparently related to the import of PyObjC and/or PySide2.

## Context information

* Output of `pyinstaller --version`: ```4.1.dev0```
* Version of Python: 3.7.6 in virtual environment
* Platform: macOS 10.15.6
* Did not try on another platform.

### Stacktrace / full error message

```
File "epidemic.py", line 108, in <module>
  File "epidemic.py", line 103, in main
  File "epidemic.py", line 35, in __init__
  File "game.py", line 13, in __init__
  File "game.py", line 67, in read_decks_from_file
  File "utility.py", line 15, in get_path
  File "/var/folders/tp/t5drkg4j2fbf29s48m_816_m0000gn/T/embedded._g_j84hf.zip/shibokensupport/__feature__.py", line 146, in _import
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "AppKit/__init__.py", line 10, in <module>
  File "/var/folders/tp/t5drkg4j2fbf29s48m_816_m0000gn/T/embedded._g_j84hf.zip/shibokensupport/__feature__.py", line 146, in _import
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "Foundation/__init__.py", line 9, in <module>
  File "/var/folders/tp/t5drkg4j2fbf29s48m_816_m0000gn/T/embedded._g_j84hf.zip/shibokensupport/__feature__.py", line 146, in _import
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "CoreFoundation/__init__.py", line 9, in <module>
  File "/var/folders/tp/t5drkg4j2fbf29s48m_816_m0000gn/T/embedded._g_j84hf.zip/shibokensupport/__feature__.py", line 146, in _import
  File "/usr/local/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
  File "objc/__init__.py", line 6, in <module>
ImportError: cannot import name '_objc' from partially initialized module 'objc' (most likely due to a circular import) (/Users/me/Files/Docs/Code/Python/Epidemic/dist/Epidemic.app/Contents/MacOS/objc/__init__.pyc)
[82607] Failed to execute script epidemic
```
`.spec` file has the following path added to pathex:
```
/Users/me/Files/Docs/Code/Python/Epidemic/.venv376/lib/python3.7/site-packages
```
There is a reference in the error output to Python 3.8 but I'm not sure why. PySide2 and PyObjC are installed only the inside the virtual environment, as well as Python 3.7.6.

I am only using PyObjC as per the solution to the file access problem on macOS proposed in [#5109](https://github.com/pyinstaller/pyinstaller/issues/5109).

Thanks for your help.

**Comment by rokm** [comment]
This looks like an issue with your environment. You probably also have `pyinstaller` installed with your python 3.8 in `/usr/local/lib/python3.8`, and that one is being picked up when you run the `pyinstaller` command (check the output of `which pyinstaller`).

Try using `python -m PyInstaller ...` instead of `pyinstaller ...`.

**Comment by Merkwurdichliebe** [comment]
From outside of my environment, I did:
```
brew uninstall pyinstaller
```
Which gave me:
```
Uninstalling /usr/local/Cellar/pyinstaller/4.0... (1,234 files, 12MB)
```
Then, from within the environment, I ran the usual command and got the same error. I noticed this among the messages during compile:
```
2930 INFO: Processing pre-find module path hook distutils from '/usr/local/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
2932 INFO: distutils: retargeting to non-venv dir '/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8'
```
How come it's still going back to the 3.8 version?

I tried `python -m PyInstaller` and got:
```
/Users/me/Files/Docs/Code/Python/Epidemic/.venv376/bin/python: No module named PyInstaller
```

**Comment by bwoodsend** [comment]
@Merkwurdichliebe You're confusing your virtual environments without realising. The PyInstaller that you are using is not in the same environment as the Python you're using. And the Python you're using doesn't have PyInstaller installed. If you have multiple environments on your machine you should use:
```shell
python -m pip installer PyInstaller
```
to install PyInstaller. And
```shell
python -m PyInstaller ....
```
to run it. Doing so makes it impossible to get them mixed up.

**Comment by Merkwurdichliebe** [comment]
Apologies. I was absolutely positive that I had installed pyinstaller in the environement but indeed this was not the case. I've installed it through PyCharm and now the application compiles and runs fine.

I am curious about two things: how come pyinstaller was even executed (from outside the environment) after I had uninstalled it through brew, and what is the meaning of the following error that I still get (although, as mentioned, the application compiles and runs). My application uses both NSBundle and QTWidgets.

#### Terminal output

```
6594 ERROR: Can not find path ./libshiboken2.abi3.5.15.dylib (needed by /Users/me/Files/Docs/Code/Python/Epidemic/.venv376/lib/python3.7/site-packages/PySide2/QtCore.abi3.so)
6596 ERROR: Can not find path ./libshiboken2.abi3.5.15.dylib (needed by /Users/me/Files/Docs/Code/Python/Epidemic/.venv376/lib/python3.7/site-packages/PySide2/QtNetwork.abi3.so)
6601 ERROR: Can not find path ./libshiboken2.abi3.5.15.dylib (needed by /Users/me/Files/Docs/Code/Python/Epidemic/.venv376/lib/python3.7/site-packages/PySide2/QtWidgets.abi3.so)
6605 ERROR: Can not find path ./libshiboken2.abi3.5.15.dylib (needed by /Users/me/Files/Docs/Code/Python/Epidemic/.venv376/lib/python3.7/site-packages/PySide2/QtGui.abi3.so)
6658 ERROR: Can not find path ./libshiboken2.abi3.5.15.dylib (needed by /Users/me/Files/Docs/Code/Python/Epidemic/.venv376/lib/python3.7/site-packages/PySide2/libpyside2.abi3.5.15.dylib)
```

#### warn.txt

```
missing module named AppKit.NSBundle - imported by AppKit (delayed, conditional), utility (delayed, conditional)
missing module named AppKit.__bundle__ - imported by AppKit (top-level), AppKit._nsapp (top-level)
missing module named objc.nosuchclass_error - imported by objc (top-level), objc._lazyimport (top-level)
missing module named objc.loadBundle - imported by objc (top-level), objc._lazyimport (top-level)
missing module named objc.getClassList - imported by objc (top-level), objc._lazyimport (top-level)
missing module named objc.NULL - imported by objc (top-level), objc._properties (top-level)
missing module named objc._C_BOOL - imported by objc (top-level), objc._properties (top-level)
missing module named Foundation.NSBundle - imported by Foundation (top-level), Foundation._functiondefines (top-level)
```

Thank you very much for your continued help and support.

**Comment by bwoodsend** [comment]
> how come pyinstaller was even executed (from outside the environment) after I had uninstalled it through brew

You can install PyInstaller using brew?

As for the libshiboken2 error - it is quite worrying that you're seeing that. Are there any libshiboken2 dylibs in you compiled app? I'm surprised it works at all if there not there somewhere.

You can break PyQt5 and PySide2 up into bits and take only the components you need. For most applications you only need QtCore, QtGui, and QtWidgets. We do have a rather elaborate dependency graph mapping them all out but it's broken and drags in everything anyway. The best I can suggest is that you remove them from `a.binaries` in the spec file.

**Comment by Merkwurdichliebe** [comment]
> You can install PyInstaller using brew?

Apparently. Just tried it again.
```
me@mac ~ % brew install pyinstaller
==> Downloading https://homebrew.bintray.com/bottles/pyinstaller-4.0.catalina.bottle.tar.gz
Already downloaded: /Users/me/Library/Caches/Homebrew/downloads/b5fb95c6e399af648d39461aa0248b17aeb89ddc679091cf69306ff22c483371--pyinstaller-4.0.catalina.bottle.tar.gz
==> Pouring pyinstaller-4.0.catalina.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/pyi-archive_viewer
Target /usr/local/bin/pyi-archive_viewer
already exists. You may want to remove it:
  rm '/usr/local/bin/pyi-archive_viewer'

To force the link and overwrite all conflicting files:
  brew link --overwrite pyinstaller

To list all files that would be deleted:
  brew link --overwrite --dry-run pyinstaller

Possible conflicting files are:
/usr/local/bin/pyi-archive_viewer
/usr/local/bin/pyi-bindepend
/usr/local/bin/pyi-grab_version
/usr/local/bin/pyi-makespec
/usr/local/bin/pyi-set_version
/usr/local/bin/pyinstaller
==> Summary
🍺  /usr/local/Cellar/pyinstaller/4.0: 1,234 files, 12MB

me@mac ~ % brew install pyinstaller
Warning: pyinstaller 4.0 is already installed, it's just not linked
You can use `brew link pyinstaller` to link this version.
```
> As for the libshiboken2 error - it is quite worrying that you're seeing that. Are there any libshiboken2 dylibs in you compiled app? I'm surprised it works at all if there not there somewhere.
```
MyApp.app % find ./Contents -iname "*shiboken*"
./Contents/MacOS/shiboken2
./Contents/MacOS/shiboken2/shiboken2.abi3.so
./Contents/MacOS/libshiboken2.abi3.5.15.dylib
```
> The best I can suggest is that you remove the unwanted libraries from `a.binaries` in the spec file.

`a.binaries` is just an empty list in my `.spec` file. Nothing to remove there. I'd rather not touch `a.datas` either, since I finally got the app to compile and I'm not knowledgeable enough in either Python or PyInstaller to attempt that for the moment. It's no big deal, though. I can live with a 100mb executable. I was just curious, and compile results will probably improve in future versions.

BTW, PyInstaller also includes 23 `.qm` files in `MyApp.app/Contents/MacOS/PySide2/Qt/translations`, which is weird in a small, monolingual application :) If I manually delete them from within the bundle the app launches just fine (which isn't the case if I delete all the Qt files mentioned above, such as `QtNetwork` etc).

Thanks a lot for your help and support.

**Comment by rokm** [comment]
The `shiboken2` dynamic library errors should be harmless. 

The PySide2 dynamic libraries are linked against it with `@rpath`, 
```
(venv) aether:pyi-shiboken rok$ otool -L venv/lib/python3.7/site-packages/PySide2/QtCore.abi3.so
venv/lib/python3.7/site-packages/PySide2/QtCore.abi3.so:
	@rpath/libpyside2.abi3.5.15.dylib (compatibility version 5.15.0, current version 5.15.1)
	@rpath/QtCore.framework/Versions/5/QtCore (compatibility version 5.15.0, current version 5.15.1)
	@rpath/libshiboken2.abi3.5.15.dylib (compatibility version 5.15.0, current version 5.15.1)
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 400.9.4)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1252.200.5)
```
but the `@rpath` entries actually point at either `@loader_path` or `@loader_path/Qt/lib`, so we end up looking for it in the library's current location.

The library is actually located in `site-packages/shiboken2/libshiboken2.abi3.5.15.dylib`. I guess we still manage to pick it up correctly due to `shiboken2` `hiddenimport` in the `PySide2` hook...

**Comment by rokm** [comment]
> BTW, PyInstaller also includes 23 .qm files in MyApp.app/Contents/MacOS/PySide2/Qt/translations, which is weird in a small, monolingual application :) If I manually delete them from within the bundle the app launches just fine (which isn't the case if I delete all the Qt files mentioned above, such as QtNetwork etc).

The translations are for the Qt framework itself, though. So if your user had a non-English locale, some parts of the application (e.g., error messages from the Qt itself) would end up translated. (Which may or may not be desirable).

The "Qt files" (e.g., `QtNetwork`) are dynamic libraries. Some may be safe to remove if you are not using that functionality, but you'll need to determine those experimentally (there may be some hidden dependencies between them, even if that functionality is not actually used). For example, if your application is a classic widgets application, you can try removing `QtQuick`...
