### ISSUE TITLE
warnings when using pyinstaller and numpy please help

### ISSUE THREAD

**Issue by KarikalStrom** [pyinstaller/pyinstaller#5193]
Warnings are :
29900 WARNING: Hidden import "pkg_resources.markers" not found!
.
.
41173 WARNING: lib not found: impi.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_blacs_intelmpi_ilp64.dll
41417 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_blacs_mpich2_lp64.dll
41465 WARNING: lib not found: impi.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_blacs_intelmpi_lp64.dll
41593 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_blacs_mpich2_ilp64.dll
41801 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_pgi_thread.dll
41801 WARNING: lib not found: pgf90.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_pgi_thread.dll
41809 WARNING: lib not found: pgc14.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_pgi_thread.dll
42485 INFO: Looking for eggs
42485 INFO: Using Python library c:\users\omen\anaconda3\python37.dll
42485 INFO: Found binding redirects:
[]
42501 INFO: Warnings written to C:\Users\OMEN\build\interface\warn-interface.txt

the python file I am trying to make exe has only two lines 
import numpy as np
print('hello')

Full execution : 
PS C:\Users\OMEN> pyinstaller --onefile C:\Users\OMEN\Desktop\xec\interface.py
507 INFO: PyInstaller: 4.0
515 INFO: Python: 3.7.3 (conda)
515 INFO: Platform: Windows-10-10.0.18362-SP0
515 INFO: wrote C:\Users\OMEN\interface.spec
515 INFO: UPX is not available.
515 INFO: Extending PYTHONPATH with paths
['C:\\Users\\OMEN\\Desktop\\xec', 'C:\\Users\\OMEN']
587 INFO: checking Analysis
627 INFO: Building because C:\Users\OMEN\Desktop\xec\interface.py changed
627 INFO: Initializing module dependency graph...
635 INFO: Caching module graph hooks...
651 INFO: Analyzing base_library.zip ...
6091 INFO: Caching module dependency graph...
6267 INFO: running Analysis Analysis-00.toc
6283 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\omen\anaconda3\python.exe
6547 INFO: Analyzing C:\Users\OMEN\Desktop\xec\interface.py
8345 INFO: Processing pre-find module path hook distutils from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\
hooks\\pre_find_module_path\\hook-distutils.py'.
8345 INFO: distutils: retargeting to non-venv dir 'c:\\users\\omen\\anaconda3\\lib'
8608 INFO: Processing pre-find module path hook site from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks
\\pre_find_module_path\\hook-site.py'.
8616 INFO: site: retargeting to fake-dir 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\fake-modules'
11572 INFO: Processing pre-safe import module hook setuptools.extern.six.moves from 'c:\\users\\omen\\anaconda3\\lib\\site-pa
ckages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-setuptools.extern.six.moves.py'.
25953 INFO: Processing module hooks...
25954 INFO: Loading module hook 'hook-pycparser.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\_pyinstaller_hooks_
contrib\\hooks\\stdhooks'...
25954 INFO: Loading module hook 'hook-pytest.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\_pyinstaller_hooks_con
trib\\hooks\\stdhooks'...
27917 INFO: Loading module hook 'hook-distutils.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'
...
27917 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'
...
28036 INFO: Loading module hook 'hook-importlib_metadata.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstalle
r\\hooks'...
28036 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'..
.
28076 INFO: Loading module hook 'hook-numpy.core.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks
'...
28196 INFO: MKL libraries found when importing numpy. Adding MKL to binaries
28204 INFO: Loading module hook 'hook-numpy.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
28204 INFO: Loading module hook 'hook-packaging.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'
...
28204 INFO: Loading module hook 'hook-pkg_resources.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\ho
oks'...
29148 INFO: Processing pre-safe import module hook win32com from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\_pyinstalle
r_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
29772 INFO: Processing pre-safe import module hook six.moves from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstalle
r\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
29900 WARNING: Hidden import "pkg_resources.markers" not found!
29900 INFO: Excluding import '__main__'
29908 INFO:   Removing import of __main__ from module pkg_resources
29908 INFO: Loading module hook 'hook-pygments.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'.
..
32044 INFO: Loading module hook 'hook-PyQt5.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
37068 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hoo
ks'...
37171 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hook
s'...
37340 INFO: Loading module hook 'hook-pytz.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
37532 INFO: Loading module hook 'hook-scipy.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
37532 INFO: Loading module hook 'hook-setuptools.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks
'...
38541 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'
...
38541 INFO: Loading module hook 'hook-wcwidth.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'..
.
38549 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\h
ooks'...
38549 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInst
aller\\hooks'...
38549 INFO: Loading module hook 'hook-xml.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
38549 INFO: Loading module hook 'hook-pythoncom.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\_pyinstaller_hooks_
contrib\\hooks\\stdhooks'...
38780 INFO: Loading module hook 'hook-pywintypes.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\_pyinstaller_hooks
_contrib\\hooks\\stdhooks'...
39013 INFO: Loading module hook 'hook-win32com.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\_pyinstaller_hooks_c
ontrib\\hooks\\stdhooks'...
39877 INFO: Loading module hook 'hook-PIL.Image.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'
...
40589 INFO: Loading module hook 'hook-PIL.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'...
40589 INFO: Excluding import 'tkinter'
40597 INFO:   Removing import of tkinter from module PIL.ImageTk
40597 INFO: Import to be excluded not found: 'PyQt4'
40597 INFO: Import to be excluded not found: 'PySide'
40597 INFO: Import to be excluded not found: 'FixTk'
40597 INFO: Excluding import 'PyQt5'
40597 INFO:   Removing import of PyQt5.QtCore from module PIL.ImageQt
40597 INFO:   Removing import of PyQt5.QtGui from module PIL.ImageQt
40605 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInsta
ller\\hooks'...
40605 INFO: Import to be excluded not found: 'FixTk'
40605 INFO: Excluding import 'tkinter'
40605 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks'.
..
40821 INFO: checking Tree
40877 INFO: checking Tree
40965 INFO: Looking for ctypes DLLs
41077 INFO: Analyzing run-time hooks ...
41093 INFO: Including run-time hook 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkg
res.py'
41093 INFO: Including run-time hook 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_win
32comgenpy.py'
41093 INFO: Including run-time hook 'c:\\users\\omen\\anaconda3\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mul
tiprocessing.py'
41125 INFO: Looking for dynamic libraries
41173 WARNING: lib not found: impi.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_blacs_intelmpi_ilp64.dll
41417 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_blacs_mpich2_lp64.dll
41465 WARNING: lib not found: impi.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_blacs_intelmpi_lp64.dll
41593 WARNING: lib not found: mpich2mpi.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_blacs_mpich2_ilp64.dll
41801 WARNING: lib not found: pgf90rtl.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_pgi_thread.dll
41801 WARNING: lib not found: pgf90.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_pgi_thread.dll
41809 WARNING: lib not found: pgc14.dll dependency of c:\users\omen\anaconda3\Library\bin\mkl_pgi_thread.dll
42485 INFO: Looking for eggs
42485 INFO: Using Python library c:\users\omen\anaconda3\python37.dll
42485 INFO: Found binding redirects:
[]
42501 INFO: Warnings written to C:\Users\OMEN\build\interface\warn-interface.txt
42695 INFO: Graph cross-reference written to C:\Users\OMEN\build\interface\xref-interface.html
42767 INFO: checking PYZ
42791 INFO: Building because toc changed
42791 INFO: Building PYZ (ZlibArchive) C:\Users\OMEN\build\interface\PYZ-00.pyz
44933 INFO: Building PYZ (ZlibArchive) C:\Users\OMEN\build\interface\PYZ-00.pyz completed successfully.
44981 INFO: checking PKG
45013 INFO: Building because toc changed
45013 INFO: Building PKG (CArchive) PKG-00.pkg
119760 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
119784 INFO: Bootloader c:\users\omen\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
119784 INFO: checking EXE
119808 INFO: Building because toc changed
119808 INFO: Building EXE from EXE-00.toc
119832 INFO: Appending archive to EXE C:\Users\OMEN\dist\interface.exe
120048 INFO: Building EXE from EXE-00.toc completed successfully.

any help would be really appreciated thanks !!!!

**Comment by bwoodsend** [comment]
PyInstaller doesn't support and is incompatible with Anaconda's numpy. Please use pip instead.

**Comment by KarikalStrom** [comment]
thanks so much
