### ISSUE TITLE
PySide2 freeze OK on Catalina, not when copied to El Capitan

### ISSUE THREAD

**Issue by Merkwurdichliebe** [pyinstaller/pyinstaller#5196]
## Description of the issue

When freezing a PySide2 application, the macOS bundle works on Catalina but crashes when copied to a system running El Capitan (even when run from Terminal).

## Context information

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: 3.7.6 in virtual environment
* Platform: macOS Catalina 10.15.6
* Other platform (crashed): OS X El Capitan 10.11.6

### Stacktrace / full error message
```
MacPro:MacOS elcap$ /Users/elcap/Public/Drop\ Box/MyApp.app/Contents/MacOS/MyApp
Traceback (most recent call last):
  File "myapp.py", line 27, in <module>
ImportError: dlopen(/Users/elcap/Public/Drop Box/MyApp.app/Contents/MacOS/PySide2/QtWidgets.abi3.so, 2): Symbol not found: __os_activity_create
  Referenced from: /Users/elcap/Public/Drop Box/MyApp.app/Contents/MacOS/PySide2/../QtCore (which was built for Mac OS X 10.13)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Users/elcap/Public/Drop Box/MyApp.app/Contents/MacOS/PySide2/../QtCore
[46358] Failed to execute script myapp
```
The issue might be related to my earlier (solved) issue [#5188](https://github.com/pyinstaller/pyinstaller/issues/5188#issuecomment-696546960), where the pyinstaller outputs several messages like this one:
```Can not find path ./libshiboken2.abi3.5.15.dylib```

**Comment by rokm** [comment]
According to [this](https://github.com/biolab/orange3/issues/4323), Qt 5.9 is the last Qt release that supports El Capitan. 

Your error message also seems to support this: ```Referenced from: /Users/elcap/Public/Drop Box/MyApp.app/Contents/MacOS/PySide2/../QtCore (which was built for Mac OS X 10.13)``` 

So I wouldn't expect that Qt library to work on macOS older than 10.13... 

(Unless you can maybe get around it by bundling the system library with your application, but then you'll need to rewrite the path to it in all shared libraries in your compiled program.)

**Comment by Merkwurdichliebe** [comment]
I missed that. The [supported platforms](https://doc.qt.io/qt-5/supported-platforms.html) indeed start with 10.13. Unfortunately this rules out even displaying an info dialog box saying that the system isn't supported (unless I also import Tkinter for this...) Thanks a lot.
