### ISSUE TITLE
Allow cross-building Windows EXE on Linux

### ISSUE THREAD

**Issue by schlomo** [pyinstaller/pyinstaller#5198]
**Problem**: I have a Linux CI/CD pipeline and need to build a command line tool for Windows.

**Idea**: Use [wenv](https://github.com/pleiszenburg/wenv) to run pyinstaller in [wine](https://www.winehq.org/).

**Problem**: It doesn't fully work, the resulting Windows EXE doesn't work with a `ModuleNotFoundError: No module named 'codecs'` error.

**Please** help to get this working, being able to build a Windows EXE without having a Windows build machine is super useful.

I reported this also at https://github.com/pleiszenburg/wenv/issues/14 and created a simple Docker-based demo/test case at https://gist.github.com/schlomo/7f3c65969ca06f384e85accb8c88bff4#file-dockerfile

Any help is appreciated!

"develop" pyinstaller & Python 3.8.4 seems to be the best combination that at least builds an EXE, with Python 3.8.5 pyinstaller doesn't manage to create an EXE on wine. The demo provides setting the Python version via Docker build arg.

**Comment by SomberNight** [comment]
We have been building [Windows exes for Electrum using pyinstaller in wine](https://github.com/spesmilo/electrum/tree/aae06116f9cff9e3540c20a8fb6e51011ca9b3ab/contrib/build-wine) for several years.
Have not tried to bundle Python 3.8 yet though (currently using 3.7.9).

**Comment by schlomo** [comment]
Wow! Thanks @SomberNight for this link, very interesting to see how you install Python from MSI.

**Comment by johnthagen** [comment]
This project uses Wine inside of Docker to build Windows exe. Might also be of interest: https://github.com/cdrx/docker-pyinstaller

**Comment by bwoodsend** [comment]
In practice I don't think this is feasible for PyInstaller to do directly. If you're imagining it just being a case of swapping a few `.so`s for their Windows equivalents and using the Windows bootloader then I'm afraid that's not the case.

PyInstaller relies heavily on being able to run snippets of code to locate which resources to include and where to put them. If Python installations were identical across platforms i.e same filenames (minus the suffix) in the same places, then in theory it could run code on the host Python installation but bundle files from a Python of the target OS. But that certainly isn't the case. So we have to be able to run a Python for the target OS, and doing that requires either building on the target OS or virtualisation.

Feel free to discus virtualisation approaches here (maybe we'll add them to the docs at some point)...
