### ISSUE TITLE
Failed to execute script with tensorflow2

### ISSUE THREAD

**Issue by AhmedAbd-ElFattah** [pyinstaller/pyinstaller#5200]
I have the problem of failed to execute script when I use tensorflow  2 library on my script.
Print on cmd. 

File "tensorflow\lite\experimental\microfrontend\python\ops\audio_microfrontend_op.py", line 29, in <module>
  File "tensorflow\python\framework\load_library.py", line 58, in load_op_library
tensorflow.python.framework.errors_impl.NotFoundError: C:\Users\ahmed\output\main_class2\tensorflow\lite\experimental\microfrontend\python\ops\_audio_microfrontend_op.so not found
[21312] Failed to execute script main_class

* Output of `pyinstaller --version`: 4.0
* Version of Python: e.g. 3.7
* Platform: Windows 10 (English US )

**Comment by bwoodsend** [comment]
We made some fixed to the tensoflow hook yesterday. Could you:
```shell
pip install https://github.com/pyinstaller/pyinstaller-hooks-contrib/archive/master.zip
```
Then try rebuilding. Make sure you use the `--clean` option. i.e.
```shell
PyInstaller --clean my_code.py
```

**Comment by AhmedAbd-ElFattah** [comment]
@bwoodsend  Problem solved thanks a lot .
