### ISSUE TITLE
Can not use tensorflow-gpu version in other machine.(Ubuntu)

### ISSUE THREAD

**Issue by QixianX** [pyinstaller/pyinstaller#5207]
While packaging the code as an executable file, the file work well on the machine which build it. The GPU can be called smoothly even though I have removed the cuda soft connection in /usr/local/, but when testing on other machines, I can only use  CPU version.
Packaging environment:
- system: Ubuntu 16.04

- python: 3.6.0

- tensorflow: 1.12.0

- cuda: 9.0

- cudnn: 7.6.5

**Comment by rokm** [comment]
Do you have (correct version of) CUDA and cuDNN libraries installed on the target/test machines? 

PyInstaller does not pick those up because they are not link-time dependencies, but rather run-time ones (i.e., opened via `dlopen()`). So either you need to bundle them manually or ensure they are available in the target environment.

**Comment by QixianX** [comment]
> Do you have (correct version of) CUDA and cuDNN libraries installed on the target/test machines?
> 
> PyInstaller does not pick those up because they are not link-time dependencies, but rather run-time ones (i.e., opened via `dlopen()`). So either you need to bundle them manually or ensure they are available in the target environment.

Thanks! 
I've already installed cuda and cudnn on my target machines. They have cuda 10 and cuda 9, but their Nvidia driver version is higher than packaging one. I‘m not sure if this will affect the execution of the program.

**Comment by QixianX** [comment]
> Do you have (correct version of) CUDA and cuDNN libraries installed on the target/test machines?
> 
> PyInstaller does not pick those up because they are not link-time dependencies, but rather run-time ones (i.e., opened via `dlopen()`). So either you need to bundle them manually or ensure they are available in the target environment.

And how could I bundle them manually ?

**Comment by rokm** [comment]
> > Do you have (correct version of) CUDA and cuDNN libraries installed on the target/test machines?
> > PyInstaller does not pick those up because they are not link-time dependencies, but rather run-time ones (i.e., opened via `dlopen()`). So either you need to bundle them manually or ensure they are available in the target environment.
> 
> Thanks!
> I've already installed cuda and cudnn on my target machines. They have cuda 10 and cuda 9, but their Nvidia driver version is higher than packaging one. I‘m not sure if this will affect the execution of the program.

I think you'll need cuda 9 on the target machine; i.e., the version that was used to build tensorflow that you're using. 

But you can try increasing tensorflow's log verbosity and see if it says anything about trying to open cuda libraries (and potential errors there). It might already be complaining about missing cuda libraries at the default verbosity...

**Comment by rokm** [comment]
> > Do you have (correct version of) CUDA and cuDNN libraries installed on the target/test machines?
> > PyInstaller does not pick those up because they are not link-time dependencies, but rather run-time ones (i.e., opened via `dlopen()`). So either you need to bundle them manually or ensure they are available in the target environment.
> 
> And how could I bundle them manually ?

First build your program in `onedir` mode and manually copy cuda/cudnn libraries into the resulting program's directory. Then check if that solves the problem on your target machine.

If it does, it'll be probably easiest to build your program using .spec file, where you can add the libraries either via `datas` or `binaries`.

**Comment by QixianX** [comment]
> First build your program in `onedir` mode and manually copy cuda/cudnn libraries into the resulting program's directory. Then check if that solves the problem on your target machine.
> 
> If it does, it'll be probably easiest to build your program using .spec file, where you can add the libraries either via `datas` or `binaries`.

Thanks! I'will try it.

**Comment by 1chimaruGin** [comment]
@QixianX 
Did you fixed it?

**Comment by QixianX** [comment]
> @QixianX
> Did you fixed it?
No, the program still cannot call the GPU

**Comment by rokm** [comment]
What error are you getting, then?

I tried building a test tensorflow program in `onedir` mode with `tensorflow-gpu==1.12.0` in a Ubuntu 16.04 VM, and then running it on Fedora 32. As expected, it kept raising import errors like `ImportError: libcusolver.so.9.0: cannot open shared object file: No such file or directory` because the target system has `cuda 10.2` installed. 

After copying the following .so files from cuda 9 installer to the program directory, it works:
* `libcublas.so.9.0`
* `libcublas.so.9.0.176`
* `libcudart.so.9.0`
* `libcudart.so.9.0.176`
* `libcufft.so.9.0`
* `libcufft.so.9.0.176`
* `libcurand.so.9.0`
* `libcurand.so.9.0.176`
* `libcusolver.so.9.0`
* `libcusolver.so.9.0.176`

You need to copy both the short-version symlink (e.g., `libcusolver.so.9.0`) because that's what tensorflow is trying to open, and the actual long-version library file (e.g., `libcusolver.so.9.0.176`).

**Comment by QixianX** [comment]
> What error are you getting, then?
> 
> I tried building a test tensorflow program in `onedir` mode with `tensorflow-gpu==1.12.0` in a Ubuntu 16.04 VM, and then running it on Fedora 32. As expected, it kept raising import errors like `ImportError: libcusolver.so.9.0: cannot open shared object file: No such file or directory` because the target system has `cuda 10.2` installed.
> 
> After copying the following .so files from cuda 9 installer to the program directory, it works:
> 
> * `libcublas.so.9.0`
> * `libcublas.so.9.0.176`
> * `libcudart.so.9.0`
> * `libcudart.so.9.0.176`
> * `libcufft.so.9.0`
> * `libcufft.so.9.0.176`
> * `libcurand.so.9.0`
> * `libcurand.so.9.0.176`
> * `libcusolver.so.9.0`
> * `libcusolver.so.9.0.176`
> 
> You need to copy both the short-version symlink (e.g., `libcusolver.so.9.0`) because that's what tensorflow is trying to open, and the actual long-version library file (e.g., `libcusolver.so.9.0.176`).
Thanks!
After update cuda version to 10.0 and copy .so file  to the program directory, the program can use GPU.

**Comment by rokm** [comment]
Good to hear!
