### ISSUE TITLE
add PySide / PyQt path to system PATH on Windows

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#521]
On Windows PATH doesn't include the PySide install folder (in this case `C:\Python26\lib\site-packages\PySide`). However, it does have QtCreator bin folder containing a newer version of Qt than that which came with PySide.

When I run my pyside iconengines test it fails because PyInstaller is picking up the QtCreator dlls, and for the most part this doesn't seem to matter, yet the svg dll seems sensitive, doesn't load, and so the icon doesn't load.

the code similar to the following might work.
```
#!python
# file: hook-PySide.py

import os
import site

from PyInstaller import is_win
from PyInstaller import compat

# On Windows system PATH has to be extended to point to the PySide directory.
# The PySide directory contains Qt dlls. We need to avoid including different
# version of Qt libraries when there is installed another application (e.g. QtCreator)
if is_win:
    env_path = compat.getenv('PATH')
    site_paths = site.getsitepackages()
    pyside_paths = [os.path.join(p, 'PySide') for p in site_paths]
    for p in pyside_paths:
        env_path = p + os.pathsep + env_path
    # Update system PATH
    compat.setenv('PATH', env_path)
```

If this code or anything similar works then we need to implement that also for PyQt4.

 *PyInstaller/compat.py*. You could add code like:
```
#!python
import site

# Use native function if available.
if hasattr(site, 'getsitepackages')
    getsitepackages = site.getsitepackages
# Backported implementation
else:
    def getsitepackages():
        ...
```

In *hooks/hook-PySide.py* use it just like:
```
from PyInstaller import compat

site_dirs = compat.getsitepackages()
```

**Comment by matysek** [comment]
Related pull request #1136.
