### ISSUE TITLE
Trait all tests as flaky by default

### ISSUE THREAD

**Issue by BoboTiG** [pyinstaller/pyinstaller#5214]
**Is your feature request related to a problem? Please describe.**

Test are randomly failing, making harder to spot real regression introduced in a PR and making the whole process of proposing a patch more time/energy consuming.

**Describe the solution you'd like**

I propose to use [flaky](https://pypi.org/project/flaky/) and trait all tests as being flaky by default. The implementation is very easy, it is only a matter of adding `flaky` to [requirements-tools.txt](https://github.com/pyinstaller/pyinstaller/blob/develop/tests/requirements-tools.txt) and declare `pytest` arguments.

https://github.com/pyinstaller/pyinstaller/blob/81d7e6a761fada855eb9a4b7e29a12c1da8a6075/setup.cfg#L157 becomes:
```ini
addopts = "-v" "-rsxXfE" "--doctest-glob=" "--force-flaky" "--no-success-flaky-report"
```

WDYT? If you are OK, I will open a PR.

**Comment by bwoodsend** [comment]
Can you point to any tests in particular that would benefit from this? The failing tests I see are at least consistent so adding flaky wouldn't help us...

@rokm You've been looking at the failing tests - did you notice any that were failing sometimes but passing on others?

**Comment by rokm** [comment]
> @rokm You've been looking at the failing tests - did you notice any that were failing sometimes but passing on re-runs?

I've seen the PySide2 QtWebEngine test fail couple of times on one run but not one subsequent one. Couldn't reproduce it locally, though.

And there's `test_osx_custom_protocol_handler` sometimes failing on macOS CI on python versions other than 3.5 (which has its own issue). But I'm pretty sure that's a timing issue - there are two 2-second sleeps in there, and that wait interval should probably be increased to 5 or even 10 s.

**Comment by BoboTiG** [comment]
@bwoodsend as an example, take my current PR (#5208).

First run, I had those failures:
```
CI: GitHub Actions
    env: macOS 3.6
        - tests/functional/test_multiprocess.py::test_multiprocess_spawn_process[onedir]

CI: AppVeyor
    env: PYTHON=C:\Python38, PYTHON_VERSION=3.8, PYTHON_ARCH=32
        - tests/functional/test_libraries.py::test_gevent[onedir]
        - tests/functional/test_libraries.py::test_gevent[onefile]
        - tests/functional/test_libraries.py::test_gevent_monkey[onedir]
        - tests/functional/test_libraries.py::test_gevent_monkey[onefile] 
    env: PYTHON=C:\Python37-x64, PYTHON_VERSION=3.7, PYTHON_ARCH=64
        - tests/functional/test_libraries.py::test_gevent[onedir]
        - tests/functional/test_libraries.py::test_gevent[onefile]
    env: PYTHON=C:\Python37, PYTHON_VERSION=3.7, PYTHON_ARCH=32
        - tests/functional/test_libraries.py::test_gevent[onedir]
        - tests/functional/test_libraries.py::test_gevent[onefile]
        - tests/functional/test_libraries.py::test_gevent_monkey[onedir]
        - tests/functional/test_libraries.py::test_gevent_monkey[onefile]
```

I then closes/re-opened the PR to relaunch all tests (no code change in-between):
```
CI: GitHub Actions
    env: macOS 3.6
        - tests/unit/test_hookutils.py::test_collect_data_all_included[package]
```
On the second run, we do not have same failures on GH macOS 3.6. Both are passing locally.

Note: AppVeyot test restults of the second run are not going to be available soon, so posting right now the answer to highlight at least macOS runner instabilities.

**Comment by bwoodsend** [comment]
OK fair enough. Go ahead then...

**Comment by htgoebel** [comment]
On the downside, we now get duplicate error-logs and a useless traceback on failing tests. See https://ci.appveyor.com/project/PyInstaller/pyinstaller/builds/36321105 as an example.

**Comment by Legorooj** [comment]
@htgoebel that test failure is completely unrelated to flaky - that test has been bugging me for ages, I stuck an xfail on it shortly after the flaky addition was merged. It was definitely happening before that though.
