### ISSUE TITLE
C Run-Time Error R6034 when renaming --onefile executable

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#522]
**Original date**: 2012/02/19
**Original reporter**: *cryzed AND googlemail DOT  COOM *

When renaming an executable file created by PyInstaller with the `--onefile` option the C Run-Time Error R6034 ([http://msdn.microsoft.com/library/ms235560%28v=vs.80%29.aspx]) is raised. The executable continues to run normally after the error is raised.

It seems that the manifest file doesn't match the running executable after the renaming anymore -- I don't know much about PyInstaller's code but maybe the loader component could dynamically adapt the manifest file configuration during each start?

**Comment by codewarrior0** [comment]
Duplicate of #1106, which has a more in-depth discussion of problem and solution.
