### ISSUE TITLE
Pyinstaller runable on MacOS not finding pdf2txt.py when using textract

### ISSUE THREAD

**Issue by y2d2** [pyinstaller/pyinstaller#5220]
Hi all, 

I'm trying to generate a an executable for Mac OS on a Mac Os with pyinstaller using the textract library. 
I followed the instructions of the issue here: https://github.com/pyinstaller/pyinstaller/issues/2528 

But it does not work for me since I get know the following error: 
"""
The command `pdf2txt.py /Users/secretary/Documents/Svenomation/Collaterals/TestFolder/MacTest/new_cases/test.pdf` failed because the executable
`pdf2txt.py` is not installed on your system. Please make
sure the appropriate dependencies are installed before using
textract:

    http://textract.readthedocs.org/en/latest/installation.html
"""
The .spec file looks like this: 
"""
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(['importGui.py'],
             pathex=['/Users/secretary/Documents/Svenomation/SvenOmation/Frontend'],
             binaries=[],
             datas=[('/Users/secretary/Documents/Svenomation/svenonatonSA/bin/pdf2txt.py','.')],
             hiddenimports=['textract.parsers.pdf_parser', 'pdf2txt'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='importGui',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='importGui')

"""

Though I have tried with different combinations of datas and hidden imports for the pdf2txt.py file. 
I can confirm that the pdf2txt.py file is inside of the generated file of pyinstaller (when not using the --one-file option.) 

I have searched the internet for an answer, but have not been succesful with finding one. Anybody has an idea of how to fix it ?

The program runs fine if the python file is triggered directly in the terminal. (using python 3.8) 

Thanks in advance,

**Comment by rokm** [comment]
`textract` is calling `pdf2txt.py` via `subprocess.Popen()`, i.e., as a regular program. Therefore, the path to the `pdf2txt.py` needs to be in `PATH`, otherwise it will not be found, even though you have packed the `pdf2txt.py` file with your program via `datas`.

A possible approach to modifying `PATH` would be placing the following block at the start of your program (or before using `textract`):
```python
# Ensure that directory containing pdf2txt.py is in PATH
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    # Works for macOS and linux; for Windows, semi-colon needs to be used as separator
    os.environ["PATH"] = os.environ["PATH"] + ":" + sys._MEIPASS
```

**Comment by y2d2** [comment]
Hello rokm, 

Thanks this worked! (Indeed I also figured out it use the pdf2txt.py in a "terminal".) but was not sure how to cope with it. 
Thank you for being so fast as well. 

Cheers!
