### ISSUE TITLE
Issue with pyInstaller and AstroPy -- Longitude?

### ISSUE THREAD

**Issue by dondonddon** [pyinstaller/pyinstaller#5223]
Simple code attached, showing the  one single line that is causing the issue!

Background: Small GUI was created with wxFormBuilder, which auto-generates most of the code in the attachment (lines 25-75). 
The code has been tested in Spyder and works as expected.   

If you set debug line #88 to FALSE in the code below,  PyInstaller will work as expected: The executable will display the GUI and the button will function to present a string to the textbox.    

If you set that debug line to TRUE, the code works correctly in Spyder.  However,  PyInstaller will create the .exe in Windows and the GUI will appear, but pushing the single button will dismiss the GUI and console window instead of correctly processing the sidereal time method.  
[DTpyDebug.txt](https://github.com/pyinstaller/pyinstaller/files/5324142/DTpyDebug.txt)

That method returns an object of type Longitude, which might be the issue?  Note that Longitude is a sub-type of Angle.  I believe Angle is in a Coordinates package/ folder (?) within AstroPy. 

Currently running Windows 10,  Using Anaconda3 (Individudal Edition) with Python 3.8.5 and PyInstaller 3.6 (both of which are the latest available as of Oct 4,2020 on Anaconda3).  I know Python 3.8.5  is not approved for PyInstaller 3.6 but I think there is an issue here that needs to get fixed.

[DTpyDebug.txt](https://github.com/pyinstaller/pyinstaller/files/5324145/DTpyDebug.txt)

**Comment by rokm** [comment]
I can't seem to reproduce this; neither with provided code, nor with the following minimal example based on the provided code:
```python
from astropy.time import Time

UTCstring = "2020-10-04 18:08:32.278373"
astroTime = Time(UTCstring, format='iso', scale= 'utc')

lon = "-123.0d"
siderealTime = astroTime.sidereal_time('apparent', "-123.0d")
print(f"Done: {siderealTime}")
```
Both run fine when build in Anaconda3 environment with python 3.8.5, pyinstaller 3.6 and astropy 4.0.1.post1. I did have some issues with AstroPy retrieving data from server(s) due to invalid certificate - but that happened before building the program...

If you run your built program from command prompt, do you see any errors in the console when you press the button and the application closes?

**Comment by dondonddon** [comment]
Wow, thanks for the quick turnaround!   Always good to have another set of eyes looking at things from a different perspective.  In my initial post, I had executed the .exe file by double-clicking the .exe file found within the dist folder.  The goal has been to simply copy that file (eventually using --oneFile) and distributing that single executable. 

I repeated the results you have found above -- if I execute either my program (or your shortened version) from the command line within Anaconda command window, I get the desired outcome !   But in both cases, if I execute the .exe file from a windows File Explorer folder,  I get the results that I reported earlier.    

For simplicity, if we focus on your shortened version, should I not see the printed result in the console window if I execute the .exe file by double clicking the file in File Explorer?     That is what I want to do -- not having to open Anaconda and then open a conde command window, and then running the .exe file.

**Comment by rokm** [comment]
The minimal example is a simple script that will exit after printing the result. So if you double click on the .exe in File Explorer, it will open a terminal, run its course, and then close the terminal again. Similarly, if an uncaught exception occurs, the program crashes and closes (both the UI and terminal).

Therefore, to see what the error was, you should open the command prompt (for most representative results, this should be "regular" command prompt / `cmd` instead of conda prompt, so you're not accidentally using any of non-packaged conda libs) and run the exe from command line.

(Alternatively, you could also wrap the code block with astropy calls into a try/except and display a dialog with information about caught exception. But I think running the exe from cmd will be easier and faster.)

**Comment by bwoodsend** [comment]
@dondonddon You must launch your executable from a non-conda command prompt which you have not called `conda activate` from. Otherwise conda will add its various `lib`/`bin` folders to `PATH` where your executable can find them - meaning that you won't see the errors you should be getting.

**Comment by dondonddon** [comment]
Thanks -- I understand what you are saying.   I am relatively new to Python and this is my first attempt at PyInstaller, so there is a bit of a learning curve here.  My problem remains though -- if you take my code and put it in Spyder and execute it, you will see that there is no error thrown by the sidereal function.   In fact, I guess you see that in your simpler example.   I edited your simple example with one more line:

from astropy.time import Time

UTCstring = "2020-10-04 18:08:32.278373"
astroTime = Time(UTCstring, format='iso', scale= 'utc')

lon = "-123.0d"
print("Howdy")
siderealTime = astroTime.sidereal_time('apparent', "-123.0d")
print(f"Done: {siderealTime}")

And I do see the HOWDY being printed in the console window, but not your print statement before the window closes (if executed by double clicking the .exe file).  The effect is more obvious in my  program since in one case the GUI stays up with the correct information displayed, and in the other case it all goes away -- although clearly we are not getting an uncaught exception since the rest of the code is the same.   

I will experiment a bit more too.   I really appreciate your help on this.

**Comment by rokm** [comment]
OK, but is there anything printed after howdy if you run .exe manually from command prompt instead of running it by double-clicking on it)? Or does it just quietly finishes and returns you to prompt? 

I still think the `astroTime.sidereal_time()` call in the .exe version is throwing an exception for some reason, but you're not seeing the traceback because the console closes. That's why we want you to run the .exe manually from command prompt instead of double-clicking on it.

**Comment by dondonddon** [comment]
Yes, I understand where you are going with this, and I can use a batch program to launch the .exe from a command window.   I have done that in the past for some of the Java apps that I have written,  precisely because of what you are saying.   For now, I took your small app (with the HOWDY edition) and launched it via a simple command window outside of Anaconda.   It prints the HOWDY and then nothing more.  The window does stay up (as we expect) but your print statement is not executed.  Yet, as you note, it DOES work correctly if we use a command window from within Anaconda.  

For some reason (beyond me), the Anaconda command window knows something that an external "Windows 10" window does not know.

**Comment by bwoodsend** [comment]
That's a missing DLL issue then. Not much you can do about it. We recommend against using Anaconda for exactly this reason.

**Comment by dondonddon** [comment]
I am pretty sure that it is something like a missimg DLL issue or missing package associated with the AstroPy coordinate package since all other aspects of my program work correctly actually.  The code specific to the AstroPy Time.sidereal_time() method is trying to access that thing. When I look in that method, I see only about 10 lines of code, and one of them is:

from astropy.coordinates import Longitude

and this is the only time I am access that Longitude item, since the rest of my application doesn't use it.  But I expected PyInstaller to find all of these import statements.  Is there a way I can somehow force that inclusion and see if that is the problem?

**Comment by rokm** [comment]
Hm, can you build the exe from the small app, zip the whole dist directory, and attach it here (or upload it somewhere)? I'd like to see what's different from the build that I made, which seems to work as expected...

**Comment by bwoodsend** [comment]
The Python imports are all being found (or if they aren't, that's not the current issue). The issue is one (or several) of the DLLs in any of:
```
[conda root]
[conda root]\Library\mingw-w64\bin
[conda root]\Library\usr\bin
[conda root]\Library\bin
conda root]\Scripts
[conda root]\bin
[conda root]\condabin
```
should be in your app. But PyInstaller can't track Conda DLLs so all we can really do is guess...

**Comment by bwoodsend** [comment]
@rokm There's a good chance that there's no difference in the builds but a difference in your run environment. A lot of Conda's DLLs are standard enough to be put in `PATH` by other programs. Git for Windows, all the msys2 family and a lot of C compilers do this heavily which makes a developer's pc the worst place to test missing DLL issues. It's highly likely that whatever is missing for @dondonddon, you already have in `PATH`.

**Comment by dondonddon** [comment]
Here are :  
(1) the program itself 
[DTdebugShort.zip](https://github.com/pyinstaller/pyinstaller/files/5324498/DTdebugShort.zip)

(2) the printout of the pyinstaller processing:
[pyinstaller_messages.txt](https://github.com/pyinstaller/pyinstaller/files/5324501/pyinstaller_messages.txt)

(3) the zip of the dist folder:
-- well, that won't work -- it is 403MB.  
In lieu of that, here is the directory of the dist folder which may help....
[datetimeFiles.txt](https://github.com/pyinstaller/pyinstaller/files/5324531/datetimeFiles.txt)

**Comment by rokm** [comment]
Ufff, that looks like a lot of unrelated stuff being pulled in for the short example program... But then again, if they are optionally imported by astropy, and available in your environment, they end up pulled in.

Can you try creating new conda environment and installing just astropy and pyinstaller?

**Comment by rokm** [comment]
Here's the filelist from my build: [filelist.txt](https://github.com/pyinstaller/pyinstaller/files/5324551/filelist.txt)

**Comment by dondonddon** [comment]
I have never created a new environment, but will do so tomorrow (can't be that hard...).    Wife says I have to quit on the computer for rest of today and pay attention to her.  Hmmm....    

For what it is worth, I did slightly modify the small program to see if there is an exception being thrown that is not being caught somehow.  Again, though the Anaconda cmd window shows the correct data being printed and the normal cmd window outside of Anaconda is not showing an exception being thrown but still is not proceeding to print the desired time/angle. 

Here is the tweaked code.  I will put into a new environment tomorrow.

[dateTimeShortCode.txt](https://github.com/pyinstaller/pyinstaller/files/5324669/dateTimeShortCode.txt)

**Comment by dondonddon** [comment]
I have now created a new environment in Anaconda and only put AstroPy and PyInstaller in it.  I ran PyInstaller and here are the contents of the dist folder:

[myListDon.txt](https://github.com/pyinstaller/pyinstaller/files/5329208/myListDon.txt)

I put both Rok's list and my list into Word and did a compare.  Here are the results:

[compareLists.docx](https://github.com/pyinstaller/pyinstaller/files/5329212/compareLists.docx)

At first glance, the only difference I see is that in my list, I have a couple more .dll files (I have a tcl and a tk directories with one .dll file each), and Rok does not have those directories.  

Rok, please confirm: when you run the .exe file within an Anaconda prompt, your program works correctly (you see the time string) and when you run it outside of Anaconda in a Windows command prompt, your program does NOT show the desired time string.  That is the behavior I am seeing in my executions.

**Comment by dondonddon** [comment]
One other "note of interest" , perhaps obvious since I am using PyInstaller:   I only do python development within Anaconda using the Spyder IDE.   I do NOT have a separate python installation on my PC outside of Anaconda.

**Comment by rokm** [comment]
No, it seems to work correctly for me (i.e., it displays the desired time string) in both cases. 

It might be due to differences in environments like @bwoodsend suggested (extra installed programs and their libraries), but it also works for me in a very minimal Windows 10 VM (that has no Anaconda or any other development tools installed).

The first time I run it in the minimal VM, there's the certificate error again:
```
C:\Users\Rok\Desktop\program>program.exe
Downloading https://www.ietf.org/timezones/data/leap-seconds.list [Done]
Howdy
Downloading ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all
|========>----------------------------------| 655k/3.3M (19.51%) ETA     1s
WARNING: failed to download ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all and https://datacenter.iers.org/data/9/finals2000A.all, using local IERS-B: <urlopen error Unable to open any source! Exceptions were {'ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all': timeout('timed out'), 'https://datacenter.iers.org/data/9/finals2000A.all': URLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1108)'))}> [warnings]
Traceback (most recent call last):
  File "program.py", line 8, in <module>
  File "site-packages\astropy\time\core.py", line 1312, in sidereal_time
  File "site-packages\astropy\time\core.py", line 1326, in _erfa_sidereal_time
  File "site-packages\astropy\time\core.py", line 1326, in <listcomp>
  File "site-packages\astropy\time\core.py", line 1708, in __getattr__
  File "site-packages\astropy\time\core.py", line 796, in _set_scale
  File "site-packages\astropy\time\core.py", line 1826, in _get_delta_ut1_utc
  File "site-packages\astropy\utils\iers\iers.py", line 271, in ut1_utc
  File "site-packages\astropy\utils\iers\iers.py", line 401, in _interpolate
  File "site-packages\astropy\utils\iers\iers.py", line 344, in _check_interpolate_indices
astropy.utils.iers.iers.IERSRangeError: (some) times are outside of range covered by IERS table.
[5460] Failed to execute script program
```

but after once visiting https://datacenter.iers.org with Internet Explorer, it goes through:
```
C:\Users\Rok\Desktop\program>program.exe
Downloading https://www.ietf.org/timezones/data/leap-seconds.list [Done]
Howdy
Downloading ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all
|========>----------------------------------| 655k/3.3M (19.51%) ETA     1s
Downloading ftp://cddis.gsfc.nasa.gov/pub/products/iers/finals2000A.all from https://datacenter.iers.org/data/9/finals2000A.all
|===========================================| 3.3M/3.3M (100.00%)         0s
Done: 10.86802611676726 hourangle
```
and then on subsequent runs:
```
C:\Users\Rok\Desktop\program>program.exe
Downloading https://www.ietf.org/timezones/data/leap-seconds.list [Done]
Howdy
Done: 10.86802611676726 hourangle
```

**Comment by rokm** [comment]
Here's the `dist` from my build, if you want to try it out yourself: https://rokm.dynu.net/tmp/pyi-5223-dist.7z

**Comment by rokm** [comment]
Hmm, I've noticed that I've been using python 3.8.0 to get the above results:

```
(pyi-5223) C:\Users\Rok\Development\pyi-5223>conda list
# packages in environment at C:\Users\Rok\anaconda3\envs\pyi-5223:
#
# Name                    Version                   Build  Channel
altgraph                  0.17                       py_0
astropy                   4.0.1.post1      py38he774522_1
blas                      1.0                         mkl
brotlipy                  0.7.0           py38h1e8a9f7_1000    conda-forge
ca-certificates           2020.6.20            hecda079_0    conda-forge
certifi                   2020.6.20        py38h32f6830_0    conda-forge
cffi                      1.14.3           py38hba49e27_0    conda-forge
chardet                   3.0.4           py38h32f6830_1007    conda-forge
cryptography              3.1.1            py38hba49e27_0    conda-forge
future                    0.18.2                   py38_1
idna                      2.10               pyh9f0ad1d_0    conda-forge
intel-openmp              2020.2                      254
m2w64-gcc-libgfortran     5.3.0                         6
m2w64-gcc-libs            5.3.0                         7
m2w64-gcc-libs-core       5.3.0                         7
m2w64-gmp                 6.1.0                         2
m2w64-libwinpthread-git   5.0.0.4634.697f757               2
macholib                  1.14                       py_1
mkl                       2020.2                      256
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.2.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
msys2-conda-epoch         20160418                      1
numpy                     1.19.1           py38h5510c5b_0
numpy-base                1.19.1           py38ha3acd2a_0
openssl                   1.1.1h               he774522_0    conda-forge
pathlib2                  2.3.5            py38h32f6830_1    conda-forge
pefile                    2019.4.18                  py_0
pip                       20.2.3                   py38_0
pthread-stubs             0.4               h301d43c_1001    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pycryptodome              3.9.8            py38he774522_0
pyinstaller               3.6              py38h62dcd97_5
pyopenssl                 19.1.0                     py_1    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pysocks                   1.7.1            py38h32f6830_1    conda-forge
python                    3.8.0                hff0d562_2
python_abi                3.8                      1_cp38    conda-forge
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
requests                  2.24.0             pyh9f0ad1d_0    conda-forge
setuptools                49.6.0                   py38_1
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
urllib3                   1.25.10                    py_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1                     py_0
win_inet_pton             1.1.0                    py38_0    conda-forge
wincertstore              0.2                      py38_0
wxpython                  4.0.7.post2      py38h6fd17b8_3    conda-forge
zlib                      1.2.11               h62dcd97_4
```

**Comment by rokm** [comment]
But I get the same results by building in a new conda environment with 3.8.5 (again, tested by running in the minimal VM):

```
(pyi-5223-v2) C:\Users\Rok\Development\pyi-5223\v2>conda list
# packages in environment at C:\Users\Rok\anaconda3\envs\pyi-5223-v2:
#
# Name                    Version                   Build  Channel
altgraph                  0.17                       py_0
astropy                   4.0.1.post1      py38he774522_1
blas                      1.0                         mkl
ca-certificates           2020.7.22                     0
certifi                   2020.6.20                py38_0
future                    0.18.2                   py38_1
intel-openmp              2020.2                      254
macholib                  1.14                       py_1
mkl                       2020.2                      256
mkl-service               2.3.0            py38hb782905_0
mkl_fft                   1.2.0            py38h45dec08_0
mkl_random                1.1.1            py38h47e9c7a_0
numpy                     1.19.1           py38h5510c5b_0
numpy-base                1.19.1           py38ha3acd2a_0
openssl                   1.1.1h               he774522_0
pefile                    2019.4.18                  py_0
pip                       20.2.3                   py38_0
pycryptodome              3.9.8            py38he774522_0
pyinstaller               3.6              py38h62dcd97_5
python                    3.8.5                h5fd99cc_1
pywin32                   227              py38he774522_1
pywin32-ctypes            0.2.0                 py38_1000
setuptools                49.6.0                   py38_1
six                       1.15.0                     py_0
sqlite                    3.33.0               h2a8f88b_0
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_3
wheel                     0.35.1                     py_0
wincertstore              0.2                      py38_0
zlib                      1.2.11               h62dcd97_4
```

Build: https://rokm.dynu.net/tmp/pyi-5223-v2-dist.7z

**Comment by dondonddon** [comment]
Curios-er and Courios-er...
I downloaded you dist folder and unzipped it and ran it in a windows cmd window.   I get my same results:  HOWDY shows up and then the program terminates without presenting the time information.   Which version of PyInstaller are you using?  Since I generally am in Anaconda, the latest version of PyInstaller that it finds is version 3.6

Still, that is probably just a rabbit hole we don't need to go down.   One should be able to take your dist folder and use it "as is" regardless of how it is constructed, and we should both get the same result.   But we don't?

Regarding you other note above about accessing websites at Goddard Space Flight Center, etc -- I have never gotten those messages in any work that I have done.   Having worked at NASA for 40+ years myself and some familiarity with the code, it doesn't surprise me that the application needs to have access to some of that data (for example: leap seconds are accounted for when determining sidereal time which is essentially how the stellar coordinates are rotated with respect to GPS coordinates at any particular time).   

Do you get that sort of web accessing everytime you first run your .exe after generating the dist folder using PyInstaller?   Again, I have never seen that sort of web accessing.

**Comment by dondonddon** [comment]
Maybe my Windows command shell won't allow "certificates" ?  Not sure why.   And not sure how to check.  I think it is intriguing that you are getting those web access messages.   There might be a key to my problem there....

**Comment by dondonddon** [comment]
Perhaps one more useful though--just to be clear-- t:  When I said I created a simple environment with just AstroPy and PyInstaller, I did that as a new environment created within Anaconda.  I ran PyInstaller from a Cmd window in that simple environment within Anaconda to generate the executable.

**Comment by rokm** [comment]
No, I think the certificate issue is not really at play here. If it were, you'd be seeing the traceback similar to the one I got. But it appears to be a known issue - there are several tickets opened at astropy's issue tracker, and one of them had the suggestion to visit the site with IE to get the certificate sorted out...

Anyway, the application quietly crashing mid-running is usually a symptom of a missing DLL. And if my dist doesn't work for you, this confirms @bwoodsend's suspicion that your Windows environment (outside conda) is missing a DLL that I have available on my system (outside conda as well). 

Seeing how numpy is being pulled in during the build - can you check the work-around from this comment helps any: https://github.com/pyinstaller/pyinstaller/issues/4968#issuecomment-662075970 ?

**Comment by dondonddon** [comment]
YES !!!!   That solves my problem with the small testcase you and I have.   I will go back and see if it solves the full application problem now.  I am getting my hopes up.

**Comment by dondonddon** [comment]
YES AGAIN.  I confirmed that this solves my problem.   By copying that single .dll found by executing:  python -c "from ctypes.util import find_library; print(find_library('libiomp5md'))"   into the dist folder, the .exe file now works as intended, even when just double-clicking the executable.     Many many thanks to Rokm and bwoodsend !!!   I would have NEVER figured this out on my own.  I hope there is a permanent solution to this problem since others have seen the similar issue.   Thanks again!!!!

**Comment by rokm** [comment]
Glad to hear it's working now!

As for the permanent solution, @bwoodsend is currently working on improved support for conda, which will hopefully solve issues like this one: #5213.

**Comment by dondonddon** [comment]
Truly amazing that y'all have been so helpful.  I blew half your weekend away Rokm.    Thanks again.

**Comment by bwoodsend** [comment]
Ughhh, can't believe it was just `libiomp5md` again. I think it has had at least 12 issues and a nabble thread.

**Comment by rokm** [comment]
> Ughhh, can't believe it was just `libiomp5md` again. I think it has had at least 12 issues and a nabble thread.

The interesting part is that it seems to depend on hardware, too. I failed to reproduce it in both "development" VM and its clean-installation snapshot, but when I later tried on my Windows laptop, it failed there. 

So there could be some dynamic backend selection going on, either based on supported instruction sets or the number of cores (I think `libiomp5md` is related to OpenMP).

**Comment by bwoodsend** [comment]
Does `where libiomp5md` not yield anything then on your VM? I am surprised that a VM without dev tools couldn't reproduce this. Unlike some of the openssl dlls which are also hidden Conda dependencies, `libiomp5md` isn't that common. I have one from LLMV C compiler. But I've not seen it anywhere else.

**Comment by rokm** [comment]
Nope, it's nowhere to be found:
```
c:\>where libiomp5md*
INFO: Could not find files for the given pattern(s).

c:\>where lib*
C:\Windows\System32\libcrypto.dll
```

**Comment by dondonddon** [comment]
When I found it I found it in anaconda3/envs/.../library/bin.   I had to copy it from there into the dist folder.
