### ISSUE TITLE
os.dup2, works in pycharm but not pyinstaller

### ISSUE THREAD

**Issue by devstoy** [pyinstaller/pyinstaller#5227]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
**os.dup2, works in pycharm but not pyinstaller**

As you can see, this is a simple python code that sends stdout to a file.
And it works in pycharm.
However, it does not work after creating an exe file with pyinstaller.
I tested on python 3.7.9 + pyinstaller 4.0 and python 3.6.9 + pyinstaller 3.6

> pyinstaller stdout_dup2_test.py

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: **3.7.9**
* Platform: **Windows**
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import os
import sys

if __name__ == '__main__':
    out_fd = os.open('out.txt', os.O_CREAT | os.O_WRONLY)
    os.dup2(out_fd, sys.stdout.fileno())
    print('test')
    os.close(out_fd)
```

### Stacktrace / full error message

```
> stdout_dup2_test.exe
Traceback (most recent call last):
  File "stdout_dup2_test.py", line 7, in <module>
OSError: [WinError 6] The handle is invalid
[6436] Failed to execute script stdout_dup2_test
Traceback (most recent call last):
  File "<string>", line 1, in <module>
OSError: [WinError 6] The handle is invalid
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 6] The handle is invalid
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
The provided example does not work when ran in python from command-line, either:
```
(venv) C:\Users\Rok\Development\pyi-5227>python program.py
Traceback (most recent call last):
  File "program.py", line 7, in <module>
    print('test')
OSError: [WinError 6] The handle is invalid
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
OSError: [WinError 6] The handle is invalid
```

[This SO thread](https://stackoverflow.com/questions/52373180/python-on-windows-handle-invalid-when-redirecting-stdout-writing-to-file) seems to provide reasonable explanation for it.

My guess would be that it works in PyCharm IDE because it does some additional stdout and stderr redirection...

**Comment by devstoy** [comment]
Thanks~ rokm

By referring to [the article](https://stackoverflow.com/questions/52373180/python-on-windows-handle-invalid-when-redirecting-stdout-writing-to-file) you gave me, I confirmed that if 'PYTHONLEGACYWINDOWSSTDIO =1' is set in the windows environment variable, it operates as a legacy console and there is no problem.

Can I ask you one more thing? Can pyinstaller set environment variables before the actual code is executed?

I also considered "[Run-time Python Options](https://pyinstaller.readthedocs.io/en/stable/spec-files.html#giving-run-time-python-options)"  in the spec file and "[Hooks](https://pyinstaller.readthedocs.io/en/stable/hooks.html)", but I couldn't set environment variables before the python interpreter runs. (Because it must be set before the python interpreter is executed)

**Comment by bwoodsend** [comment]
> Can pyinstaller set environment variables before the actual code is executed?

Unfortunately not. Short of modifying and compiling to bootloaders yourself, I think the closest you could get is to write a wrapper script (in shell or C) which sets the variable then launches the app.

**Comment by devstoy** [comment]
Thanks everyone

The OSError was not fixed on the program created with pyinstaller, even in the PC where the environment variable was set with "PYTHONLEGACYWINDOWSSTDIO=1".

There seems to be no way at this time.
