### ISSUE TITLE
Need to use Pyinstaller with Python3.8 on Ubuntu 20

### ISSUE THREAD

**Issue by alpana17** [pyinstaller/pyinstaller#5246]
What can I do?

**Comment by rokm** [comment]
Python 3.8 should work with `development` branch. You can likely use it with 4.0 release, too.

**Comment by alpana17** [comment]
ok. but I get error 
![Uploading image.png…]()

**Comment by rokm** [comment]
As far as I can tell, you're using a custom hook (`hook-salt.py`) that's incompatible with recent (?) versions of PyInstaller. 

The missing symbol it is trying to import (`PY_EXECUTABLE_SUFFIXES`) was available in PyInstaller 3.3, but is not available in 3.4 or later.

**Comment by alpana17** [comment]
you are right.
how can I handle it?

**Comment by rokm** [comment]
>  how can I handle it?

You have to fix/update your `hook-salt.py` hook. That hook is not part of PyInstaller, so there is nothing we can do about it.

If you did not write that hook and it came from a 3rd party repository or software stack, then you should probably check with them for an updated version.
