### ISSUE TITLE
When there is a module with the same name as the main program script, the packaged program cannot run without any error message

### ISSUE THREAD

**Issue by liangjihua** [pyinstaller/pyinstaller#5249]
Like the title, a program with the following structure:

---- pyinstallertest
 &nbsp; &nbsp; &nbsp; &nbsp;| ---- pyinstallertest
 &nbsp; &nbsp; &nbsp; &nbsp;| &nbsp; &nbsp; &nbsp; &nbsp;|---- __init__.py
 &nbsp; &nbsp; &nbsp; &nbsp;| ---- main.py
 &nbsp; &nbsp; &nbsp; &nbsp;| ---- pyinstallertest.py

Use `pyinstaller -F`  to package `main.py` and `pyinstallertest.py`  to generate `main.exe` and `pyinstallertest.exe`.  Run them in powershell, where `main.exe` runs normally, and `pyinstallertest.exe` exits directly without any message output.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: 3.8.5
* Platform: Windows 10

This is a repository that can reproduce the problem: [https://github.com/liangjihua/pyinstallertest](https://github.com/liangjihua/pyinstallertest)

**Comment by bwoodsend** [comment]
Thanks for taking the time to set up an example but we are already aware of this. See #4771. The best I can suggest is to rename `pyinstallertest.py` to something else then use `PyInstaller --name=pyinstallertest somethingelse.py` to change your app back again,
