### ISSUE TITLE
Broken path resolution of the archive, if it is not located in `PATH` (for Unix only)

### ISSUE THREAD

**Issue by ozelikov** [pyinstaller/pyinstaller#5257]
The following code line seems to have a bug:
https://github.com/pyinstaller/pyinstaller/blob/19fb799a11d2d796fc8758808f873c40e2bf5118/bootloader/src/pyi_path.c#L296
I believe double-quotes around `appname` in the following line are unnecessary:
`  if (snprintf(buffer, PATH_MAX, "%s", "appname") >= PATH_MAX) {`
This way instead of creating path with application, we are getting `appname` string.

The error message looks like:
`Cannot open self /some_path/appname or archive /some_path/appname.pkg`

**Comment by rokm** [comment]
Good catch! Care to open a PR with a fix?

**Comment by ozelikov** [comment]
Created PR https://github.com/pyinstaller/pyinstaller/pull/5258
