### ISSUE TITLE
Error with Folium with unregistered loader type involving  list_templates

### ISSUE THREAD

**Issue by hscj87** [pyinstaller/pyinstaller#5262]
## Description of the issue

I am new to Python and I am trying to make an exe using pyinstaller. My application uses folium to display a coordinate on map with below code:

**map = folium.Map(location=[3.474087, 108.370123], zoom_start=5)**

I am getting error to compile the my program but i can't figure out what wrong. The error messages from pyinstaller as below:

**Traceback (most recent call last):
  File "app2.py", line 1970, in <module>
  File "app2.py", line 946, in __init__
  File "app2.py", line 1231, in loadPageInitial
  File "folium\folium.py", line 282, in __init__
  File "folium\raster_layers.py", line 97, in __init__
  File "jinja2\environment.py", line 810, in list_templates
  File "jinja2\loaders.py", line 286, in list_templates
  File "jinja2\loaders.py", line 278, in _walk
  File "pkg_resources\__init__.py", line 1441, in resource_listdir
  File "pkg_resources\__init__.py", line 1484, in _listdir
NotImplementedError: Can't perform this operation for unregistered loader type
[18720] Failed to execute script app2**

Previously I have encountered with simillar error that involved in get_template and  _load_template in "jinja2\environment.py", I  manage to solve after changed **_template = ENV.get_template('color_scale.js')** to  **_template = ENV.from_string('color_scale.js')** as shared by other. 

Anyone have encountered this before?

## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.0
* Version of Python: 3.7.6
* Platform:  Windows 10 64bit

**Comment by rokm** [comment]
Take a look at #5256.

**Comment by rokm** [comment]
It's a similar issue, and for now, you'll need to patch your `folium\raster_layers.py` to use `FileSystemLoader` instead of `PackageLoader` for frozen applications. I.e., expand the line 

```python
ENV = Environment(loader=PackageLoader('folium', 'templates'))
```

into

```python
import sys
if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
    import os
    from jinja2 import FileSystemLoader
    bundle_dir = getattr(sys, '_MEIPASS')
    data_dir = os.path.abspath(os.path.join(bundle_dir, 'folium', 'templates'))
    ENV = Environment(loader=FileSystemLoader(data_dir))
else:
    ENV = Environment(loader=PackageLoader('folium', 'templates'))
```

**Comment by hscj87** [comment]
Hi rokm,

I have patched my raster_layers.py. But i get another error:
**Traceback (most recent call last):
  File "app2.py", line 1970, in <module>
  File "app2.py", line 946, in __init__
  File "app2.py", line 1231, in loadPageInitial
  File "folium\folium.py", line 282, in __init__
  File "folium\raster_layers.py", line 116, in __init__
ValueError: Custom tiles must have an attribution.
[14412] Failed to execute script app2**

The code in my application **map = folium.Map(location=[3.474087, 108.370123], zoom_start=5)** is not specifying tiles. How to solve this error?

**Comment by rokm** [comment]
> ValueError: Custom tiles must have an attribution.

The data files from `folium` package are not collected.

You need to collect them using either `collect_data_files()` or `collect_all()`, either in your spec file (with passing the resulting `datas` to `Analysis`) or in a custom `hook-folium.py` hook.

**Comment by hscj87** [comment]
After i use collect_data_files(), i manage to create the exe file without error. But when i open the exe, the folium map is empty. Below is my .spec code:

**from PyInstaller.utils.hooks import collect_data_files
datas=collect_data_files('geopandas', subdir='datasets')
datas += collect_data_files('branca')
datas += collect_data_files('folium', subdir='templates')

block_cipher = None

a = Analysis(['app.py'],
             pathex=['C:\\Users\\s54187\\Desktop\\Microwave - Copy'],
             binaries=[],
             datas=datas,
             hiddenimports=['geopandas.datasets','branca','folium'],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='app',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='app')**

Is it correct to pass the whole directory like this --> collect_data_files('folium', subdir='templates')

**Comment by rokm** [comment]
> Is it correct to pass the whole directory like this --> collect_data_files('folium', subdir='templates')

Yes, that is correct. (You can check if files are correctly copied by building in `onedir` mode, and then checking the `dist\program\folium` folder).

I'm not really familiar with `folium` though, so I cannot say why the map is empty, except that there's likely something else missing. Could you prepare a minimum example that exhibits the issue?

**Comment by hscj87** [comment]
My folium map is saved as html and  displayed in QtWebEngineView. I tried to comment out the folium map and replaced with setHtml(QUrl(“www.google.com”)). When run in python i can see the google page, but in exe generated by pyinstaller still blank. 

I think this issue is due to QWebEngineView.

**Comment by mishrakeshav** [comment]
> My folium map is saved as html and displayed in QtWebEngineView. I tried to comment out the folium map and replaced with setHtml(QUrl(“www.google.com”)). When run in python i can see the google page, but in exe generated by pyinstaller still blank.
> 
> I think this issue is due to QWebEngineView.

You need to save the file at a location where you can access it later when the application is packaged. 
I used sys._MEIPASS as a PATH to store the HTML file generated by folium and this worked perfectly fine for me. 


```
PATH = sys._MEIPASS
class Map:
    def generate_map(self, lats, long):
        loc = list(zip(lats, long))
        m = folium.Map(location=[lats[-1], long[-1]],
                      zoom_start=15, tiles="Stamen Toner")
        folium.PolyLine(loc, color='red', weight=5).add_to(m)
        print(sys.path)
        print(sys._MEIPASS)
        m.save(os.path.join(PATH, ".." , "index.html"))
```
