### ISSUE TITLE
Pyinstaller still detected as virus after build the bootloader

### ISSUE THREAD

**Issue by Mose3c** [pyinstaller/pyinstaller#5263]
Hi i have search from weeks ago to fix my big issue with my clients is my apps still detected as virus

Last fix i was found is , i have to download the pyinstaller and build the bootloader on my computer 

i do and fix all issue i got success with build the bootloader .

but still anti virus detect the app as virus and 17 anti virus was detect the app as virus after build the bootloader . 

Can any one help me pleas .

**Comment by Legorooj** [comment]
@Mose3c we can't do anything, only your antivirus provider can do anything about that. You should be able to report it as a "false positive".
