### ISSUE TITLE
pyinstaller exe: QWebEngineView() blank content

### ISSUE THREAD

**Issue by hscj87** [pyinstaller/pyinstaller#5265]
## Description of the issue

I am developing an application that view folium map in QWebEngineView. Below is part of my codes:

**self.webEngineView = QWebEngineView()
map = folium.Map(location=[3.474087, 108.370123], zoom_start=5)
data = io.BytesIO()
map.save(data, close_file=False)
self.webEngineView.setHtml(data.getvalue().decode())**

These codes no problem when opened in .py but show blank content in .exe. After i faced the problem, i tried to comment out the folium map replaced with url link still face the same problem. Codes below:

**self.webEngineView = QWebEngineView()
self.URL = 'http://www.google.com'
self.webEngineView.setUrl(QUrl(self.URL))** 

Anyone faced the same problem before? Hopefully someone can share on how to solve this.

## Context information (for bug reports)

Output of pyinstaller --version: 4.0
Version of Python: 3.7.6
Platform: Windows 10 64bit

**Comment by rokm** [comment]
Hmm, I cannot reproduce this. The following program:
```python
import folium
from PyQt5 import QtWidgets, QtWebEngineWidgets, QtCore
#from PySide2 import QtWidgets, QtWebEngineWidgets, QtCore

import sys
import signal
import io

app = QtWidgets.QApplication(sys.argv)

signal.signal(signal.SIGINT, signal.SIG_DFL)

view = QtWebEngineWidgets.QWebEngineView()
m = folium.Map(location=[3.474087, 108.370123], zoom_start=5)
data = io.BytesIO()
m.save(data, close_file=False)
view.setHtml(data.getvalue().decode())

view.show()

app.exec_()
```
displays a map as expected, in both `onedir` and `onefile` mode. Tested on Windows 10, python 3.7.9, pyinstaller 4.0 (and `develop`) with `PyQt5`+`PyQtWebEngine` 5.15.1 as well as with `PySide2` 5.15.1.

**Comment by hscj87** [comment]
I am closing this cos i found that some of the folder in the folium package was missing. After i delete and re-install the package, my app working fine. Thanks
