### ISSUE TITLE
pyinstaller bootloader infinite loop while handling signal

### ISSUE THREAD

**Issue by w1z2g3** [pyinstaller/pyinstaller#5270]
When kill a pyinstaller app, it hangs on infinite loop and consumes 100% CPU:
```
$ strace -p 8152
...
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=8152, si_uid=0} ---
write(2, "[8152] ", 7)                  = -1 EPIPE (Broken pipe)
write(2, "LOADER: Forwarding signal 13 to "..., 47) = -1 EPIPE (Broken pipe)
kill(8153, SIGPIPE)                     = -1 ESRCH (No such process)
rt_sigreturn({mask=[]})                 = -1 EPIPE (Broken pipe)
--- SIGPIPE {si_signo=SIGPIPE, si_code=SI_USER, si_pid=8152, si_uid=0} ---
```

We killed process 8153 before killing 8152 with SIGTERM.

By reading the source code in pyi_utils.c, does it mean we re-raise the signal in this case and causes this dead loop?

```
    /* Process ended abnormally */
    if (WIFSIGNALED(rc)) {
        VS("LOADER: re-raising child signal %d\n", WTERMSIG(rc));
        /* Mimick the signal the child received */
        raise(WTERMSIG(rc));
    }
```

I don't fully understand the logic. Please help to analyze this issue.

**Comment by elbie1** [comment]
write(2, ..)  is writing stderr ..stderr is a pipe for which the reading end no longer exist, hence the EPIPE.

The signal handler in pyinstaller/bootloader/src/pyi_utils.c catches the SIGPIPE, and forwards it to the child,
but it also attempts to write a message on stderr, which again fails with  EPIPE and causes a new SIGPIPE signal.

static void
_signal_handler(int signum)
{
    VS("LOADER: Forwarding signal %d to child pid %d\n", signum, child_pid); /* writing to stderr, which is the broken pipe, causes a new SIGPIPE signal to be queued to be delivered */
    kill(child_pid, signum);
}
