### ISSUE TITLE
Problem using skimage.morphology

### ISSUE THREAD

**Issue by claudiourbina** [pyinstaller/pyinstaller#5271]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue

Im trying to compile my script using pyinstaller, but, when the script uses the library skimage.morphology, the executable just close. I have been trying the following options:

- I create a new env with pyinstaller and skimage (to verify the problem is between those libraries). Create a new script.py with the code: 

```py
print(1)
from skimage import morphology
print(2)

if __name__=='__main__':
	print(3)
```
And this simple example still not work, just print "1". When i open the executable console does not show any error, just closes. 

- I tried to hook skimage.morphology creating a new folder called hooks with the following script inside:

```py
from PyInstaller.utils.hooks import collect_data_files, collect_submodules

datas = collect_data_files("skimage.morphology")
hiddenimports = collect_submodules('skimage.morphology')
```

Still not working.

## Context information (for bug reports)

* I'm using conda.
* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.7.9
* Platform: Windows
* Did you also try this on another platform? Does it work there?

I have not try in another platform yet.

### A minimal example program which shows the error

There is no error shows in console. The executable just closes.

**Comment by rokm** [comment]
Are you using conda?

**Comment by claudiourbina** [comment]
> Are you using conda?

I forgot to mention it. But yes, im using conda. Im going to edit the original post.

**Comment by rokm** [comment]
In that case, this is probably due to missing `libiomp5md`. Try this: #4968 (comment)

**Comment by claudiourbina** [comment]
> In that case, this is probably due to missing `libiomp5md`. Try this: [#4968 (comment)](https://github.com/pyinstaller/pyinstaller/issues/4968#issuecomment-662075970)

It worked. Now i have other errors printed in console, but now i know what is the problem haha. Thanks!
