### ISSUE TITLE
Error occurred when running compiled application

### ISSUE THREAD

**Issue by stevenang** [pyinstaller/pyinstaller#5272]
## Description of the problem
Error occurred when running the application built using pyinstaller.

## Context information (for bug reports)
* Output of `pyinstaller --version`: ```(4.0 and 4.1.dev0)```
* Version of Python: 3.7.9
* Platform: macOS Catalina 10.15.7
* Did you also try this on another platform? Does it work there?
   I did build same application in exe form using windows and it works.

## Error Message: 
`
[7905] Error loading Python lib '/var/folders/r2/fy_tw_fd40l6w0mrkdrmr16c0000gn/T/_MEIv5ENZF/Python': dlopen: 
	dlopen /var/folders/r2/fy_tw_fd40l6w0mrkdrmr16c0000gn/T/_MEIv5ENZF/Python, 10 : no suitable image found.  
	Did find:	/var/folders/r2/fy_tw_fd40l6w0mrkdrmr16c0000gn/T/_MEIv5ENZF/Python: code signature invalid for 	
	'/var/folders/r2/fy_tw_fd40l6w0mrkdrmr16c0000gn/T/_MEIv5ENZF/Python'
	/var/folders/r2/fy_tw_fd40l6w0mrkdrmr16c0000gn/T/_MEIv5ENZF/Python: stat() failed with errno=3
`

**Comment by BoboTiG** [comment]
Could you give a minimal reproduction example with the exact command used to freeze the code?

**Comment by stevenang** [comment]
The command i used was

`
sudo pyinstaller --windowed --onefile --clean --noconfirm main.py
`

And the spec file is

`
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['main.py'],
             pathex=['/Users/steven.ang/workspace/python/Test'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=False )
app = BUNDLE(exe,
             name='main.app',
             icon=None,
             bundle_identifier=None)

`

**Comment by BoboTiG** [comment]
I'll need the output of the command and a minimal `main.py` to reproduce on my side. Also, is it required to use `sudo`? Can you do without?

**Comment by stevenang** [comment]
Here is my main.py:

`
# This is a sample Python script.

# Press ⌃R to execute it or replace it with your code.
# Press Double ⇧ to search everywhere for classes, files, tool windows, actions, and settings.

import sys

from PyQt5.QtWidgets import (QApplication, QWidget)

if __name__ == '__main__':

    app = QApplication(sys.argv)

    widget = QWidget()
    widget.resize(250, 150)
    widget.move(300, 300)
    widget.setWindowTitle('Sample Application')

    widget.show()
    sys.exit(app.exec_())

`

Output of executing pyinstaller:

`
(venv) steven.ang@StevendeiMac Test % sudo pyinstaller --windowed --onefile --clean --noconfirm main.py
Password:
61 INFO: PyInstaller: 4.1.dev0
62 INFO: Python: 3.7.9
68 INFO: Platform: Darwin-19.6.0-x86_64-i386-64bit
69 INFO: wrote /Users/steven.ang/workspace/python/Test/main.spec
72 INFO: UPX is not available.
72 INFO: Removing temporary files and cleaning cache in /Users/steven.ang/Library/Application Support/pyinstaller
87 INFO: Extending PYTHONPATH with paths
['/Users/steven.ang/workspace/python/Test',
 '/Users/steven.ang/workspace/python/Test']
92 INFO: checking Analysis
92 INFO: Building Analysis because Analysis-00.toc is non existent
92 INFO: Initializing module dependency graph...
94 INFO: Caching module graph hooks...
100 INFO: Analyzing base_library.zip ...
1263 INFO: Processing pre-find module path hook distutils from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1264 INFO: distutils: retargeting to non-venv dir '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7'
2022 INFO: Caching module dependency graph...
2088 INFO: running Analysis Analysis-00.toc
2093 INFO: Analyzing /Users/steven.ang/workspace/python/Test/main.py
2100 INFO: Processing module hooks...
2101 INFO: Loading module hook 'hook-PyQt5.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2189 WARNING: Hidden import "sip" not found!
2189 INFO: Loading module hook 'hook-encodings.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2232 INFO: Loading module hook 'hook-pickle.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2233 INFO: Excluding import 'argparse'
2234 INFO:   Removing import of argparse from module pickle
2234 INFO: Loading module hook 'hook-heapq.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2234 INFO: Excluding import 'doctest'
2235 INFO:   Removing import of doctest from module heapq
2235 INFO: Loading module hook 'hook-difflib.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2235 INFO: Excluding import 'doctest'
2235 INFO:   Removing import of doctest from module difflib
2236 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2274 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2283 INFO: Loading module hook 'hook-xml.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2428 INFO: Loading module hook 'hook-distutils.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2429 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2437 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
2459 INFO: Looking for ctypes DLLs
2459 INFO: Analyzing run-time hooks ...
2461 INFO: Including run-time hook '/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
2464 INFO: Looking for dynamic libraries
2627 INFO: Looking for eggs
2627 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.7/Python
2628 INFO: Warnings written to /Users/steven.ang/workspace/python/Test/build/main/warn-main.txt
2641 INFO: Graph cross-reference written to /Users/steven.ang/workspace/python/Test/build/main/xref-main.html
2648 INFO: checking PYZ
2648 INFO: Building PYZ because PYZ-00.toc is non existent
2648 INFO: Building PYZ (ZlibArchive) /Users/steven.ang/workspace/python/Test/build/main/PYZ-00.pyz
2855 INFO: Building PYZ (ZlibArchive) /Users/steven.ang/workspace/python/Test/build/main/PYZ-00.pyz completed successfully.
2858 INFO: checking PKG
2858 INFO: Building PKG because PKG-00.toc is non existent
2858 INFO: Building PKG (CArchive) PKG-00.pkg
10298 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
10301 INFO: Bootloader /Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/runw
10301 INFO: checking EXE
10301 INFO: Building EXE because EXE-00.toc is non existent
10301 INFO: Building EXE from EXE-00.toc
10301 INFO: Appending archive to EXE /Users/steven.ang/workspace/python/Test/dist/main
10321 INFO: Fixing EXE for code signing /Users/steven.ang/workspace/python/Test/dist/main
10324 INFO: Building EXE from EXE-00.toc completed successfully.
10327 INFO: checking BUNDLE
10327 INFO: Building BUNDLE because BUNDLE-00.toc is non existent
10327 INFO: Removing dir /Users/steven.ang/workspace/python/Test/dist/main.app
10328 INFO: Building BUNDLE BUNDLE-00.toc
10354 INFO: moving BUNDLE data files to Resource directory
(venv) steven.ang@StevendeiMac Test % 
`

The error will occurred if I did it without sudo:
`
(venv) steven.ang@StevendeiMac Test % pyinstaller --windowed --onefile --clean --noconfirm main.py 
36 INFO: PyInstaller: 4.1.dev0
36 INFO: Python: 3.7.9
40 INFO: Platform: Darwin-19.6.0-x86_64-i386-64bit
40 INFO: wrote /Users/steven.ang/workspace/python/Test/main.spec
42 INFO: UPX is not available.
43 INFO: Removing temporary files and cleaning cache in /Users/steven.ang/Library/Application Support/pyinstaller
Traceback (most recent call last):
  File "/Users/steven.ang/workspace/python/Test/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 720, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/Users/steven.ang/workspace/python/Test/venv/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 615, in build
    shutil.rmtree(f)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 516, in rmtree
    return _rmtree_unsafe(path, onerror)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 400, in _rmtree_unsafe
    onerror(os.unlink, fullname, sys.exc_info())
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/shutil.py", line 398, in _rmtree_unsafe
    os.unlink(fullname)
PermissionError: [Errno 13] Permission denied: '/Users/steven.ang/Library/Application Support/pyinstaller/bincache00_py37_64bit/index.dat'
(venv) steven.ang@StevendeiMac Test % 
`

**Comment by BoboTiG** [comment]
How was the venv created?

**Comment by stevenang** [comment]
I used PyCharm IDE for my project and it was created by the IDE.  I have another actual project with the same environment.  I was successfully created an exe file under windows environment using the same setup and commands.  But not work with the MacOS.

**Comment by rokm** [comment]
This is a problem with recent python.org builds that provide signed `Python` shared library on macOS. Moving (or in this case copying) the shared library breaks the signature - see https://github.com/pyinstaller/pyinstaller/issues/5062#issuecomment-683743556.

**Comment by stevenang** [comment]
The problem solved after I downgrade my python based on #5062 (comment).
