### ISSUE TITLE
Exe fail to start if builded with --noconsole option

### ISSUE THREAD

**Issue by Ujifman** [pyinstaller/pyinstaller#5280]
I use pytinstaller to pack small app for upgrading another apps. `Updater` app is console app, it takes console params and show progress in console. But sometimes I need to start it silent, without console. So I build two executables with the only difference: `--noconsole` build parameter. Executable **without** `--noconsole` works OK. Executable **with** `--noconsole` fail with message _"Failed to execute script..."_

It worked some time ago, so I started to downgrade pyinstaller to find version, which builds working executable. Finally I found out that with `pyinstaller v3.3.1 and lower` both executable versions work good. But started from `v3.4` `--noconsole` parameter builds broken executable. 
I don't use `stdin`, but I use `print`, so I use `stdout`. I tried to redirect `stdout` by adding `sys.stdout = open("test.txt", "w")` at the very begining of main script, but it didn't help.

Full build command
```
pyinstaller --clean ^
    --onefile ^
    --noconsole ^
    --icon=..\icon.ico ^
    --manifest manifest.xml ^
    --name improver_silent ^
    --distpath .\bin ^
    --workpath .\build_UpdaterApp ^
    --specpath .\build_UpdaterApp ^
    .\src\client.py
```
## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: e.g. 3.7.3
* Platform: Windows 10 (RU)
* Didn't try another platforms

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

**Comment by rokm** [comment]
Are you sure that `print` is what is causing the issue? (Does the problem also occur with a simple hello world app, built with `noconsole`)?

Does you application use `subprocess.Popen` (or equivalent) that does not redirect stdin/stdout/stderr?

**Comment by Ujifman** [comment]
@rokm, I'm not shure about `print`, I found in some other bug report such an idea, that using stdout without console can cause such problem. 
Just tried "Hello world" example on v4.0 works OK (without Popen)
Yes I'm using Popen without stdout. Just 
```
subprocess.Popen(self_full_path + " --remove_file " + self_runtime_path)
```
I'm sure that builded exe fail even when it doesn't go through lines that use `subprocess.Popen'

**Comment by rokm** [comment]
> Yes I'm using Popen without stdout. Just
> ```subprocess.Popen(self_full_path + " --remove_file " + self_runtime_path)```

If you don't redirect `stdin`, `stdout`, and/or `stderr` explicitly (by setting them `subprocess.DEVNULL`, the child process will inherit the ones from the parent. And if I recall correctly, for noconsole builds, inherited `stdin` will be invalid and will likely cause issues.

> I'm sure that builded exe fail even when it doesn't go through lines that use subprocess.Popen.

Then I'm afraid you'll need to identify the problematic lines in your code yourself. But you should start checking for any 3rd party libraries that might internally also be using `subprocess` calls without redirected standard streams.

**Comment by BLKSerene** [comment]
I have the same problem on Windows 10 20H2. It works fine without `--noconsole` but failed with `--noconsole` on older versions of Win10.

**Comment by rokm** [comment]
In PyInstaller 4.2, if you build with `--noconsole --debug bootloader`, the bootloader should display additional error information dialogs with error message and traceback. This might help tracking down the issue.

But at any rate, if you plan to use `--noconsole` with PyInstaller, you should also test your python script with `pythonw.exe` interpreter (windowed variant) instead of the classic `python.exe`...
