### ISSUE TITLE
运行pyinstaller中出现upx is not availabil，怎么回事？

### ISSUE THREAD

**Issue by Crazy59** [pyinstaller/pyinstaller#5282]
(venv) C:\Users\28050\PycharmProjects\pythonProject1>pyinstaller 练习.py
68 INFO: PyInstaller: 4.0
68 INFO: Python: 3.7.9
69 INFO: Platform: Windows-10-10.0.18362-SP0
69 INFO: wrote C:\Users\28050\PycharmProjects\pythonProject1\练习.spec
75 INFO: UPX is not available.
script 'C:\Users\28050\PycharmProjects\pythonProject1\练习.py' not found

(venv) C:\Users\28050\PycharmProjects\pythonProject1>

**Comment by Crazy59** [comment]
哪位大佬帮帮我，我想把代码打包出来，求教，pyinstaller出现好多问题

**Comment by BoboTiG** [comment]
Could you use English please? Also, please follow the issue template, there is a lot of missing information to be able to give a hand here.

**Comment by Crazy59** [comment]
> 你能用英语吗？另外，请按照问题模板进行操作，这里有很多缺少的信息可以提供帮助。sure,but I have a little

**Comment by Crazy59** [comment]
sure, but I have a little, if difficult  i will translate it

**Comment by bwoodsend** [comment]
>  script 'C:\Users\28050\PycharmProjects\pythonProject1\练习.py' not found

This just means the script `练习.py` doesn't exist. Can you confirm that the following works?
```shell
python C:\Users\28050\PycharmProjects\pythonProject1\练习.py
```
I should also point out that Window's cmd prompt doesn't use `utf-8` by default so it's quite probable that just having `练习` in the filename would break it.
