### ISSUE TITLE
[28682] Failed to execute script pyi_rth__tkinter

### ISSUE THREAD

**Issue by projectintel-anon** [pyinstaller/pyinstaller#5293]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue

When building an EXE for script using Tkinter, error arises:

**Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth__tkinter.py", line 28, in <module>
FileNotFoundError: Tcl data directory "/tmp/_MEIjoMf0U/tcl" not found.
[28682] Failed to execute script pyi_rth__tkinter**

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.1.dev0```
* Version of Python: 3.8.6
* Platform: Ubuntu 20.10 Groovy Gorilla
* Did you also try this on another platform? Does it work there? Haven't been able to try on another platform.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
^^^ That is the version I am already using ^^^

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth__tkinter.py", line 28, in <module>
FileNotFoundError: Tcl data directory "/tmp/_MEIjoMf0U/tcl" not found.
[28682] Failed to execute script pyi_rth__tkinter```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
I cannot reproduce this, with Ubuntu 20.10 Groovy Gorilla, its python 3.8.6 and pyinstaller `develop`.

Does `/usr/share/tcltk` directory exist on your system? And does it contain `tcl8.6` and `tk8.6` subdirectories? (Those should be provded by `libtcl8.6` and `libtk8.6` packages, respectively).

Alternatively, what is the output if you open python interpreter and run the following commands?
```python
from tkinter import Tcl
print(Tcl().eval("info library"))
```

**Comment by projectintel-anon** [comment]
Hello,

Thanks for responding! I do actually have those directories and they are both populated by what both look like normal files.

>>> print(Tcl().eval("info library"))
/usr/share/tcltk/tcl8.6
>>>

**Comment by projectintel-anon** [comment]
I thought the full log of what happens during the building process would be useful here.

Here is a Pastebin of what happens from the moment I type the build command (I hope it helps!): https://pastebin.com/EeSgn4FF

**Comment by rokm** [comment]
> I thought the full log of what happens during the building process would be useful here.

It would, but the line of interest appears to be garbled.

Take a look at the line that starts with `24824 ERROR: Tcl data directory "b'<html><body><script type="text/javascript" src="/aes.js" [...] </body></html>'
/usr/share/tcltk/tcl8.6" not found.`

Looks like some HTML code got injected into the path string - somehow? Or is that an artifact from copy&paste?

**Comment by projectintel-anon** [comment]
Oh! I didn't even see that; it shouldn't be there as I migrated site hosting. Give me two minutes and I'll fix that.

**Comment by projectintel-anon** [comment]
`root@enigmamachine:/home/enigmapr0ject/Desktop/misc# pyinstaller --onefile -w BinBoot2_1_1Halloween.py
93 INFO: PyInstaller: 4.1.dev0
93 INFO: Python: 3.8.6
109 INFO: Platform: Linux-5.8.0-26-generic-x86_64-with-glibc2.32
110 INFO: wrote /home/enigmapr0ject/Desktop/misc/BinBoot2_1_1Halloween.spec
114 INFO: UPX is not available.
116 INFO: Extending PYTHONPATH with paths
['/home/enigmapr0ject/Desktop/misc', '/home/enigmapr0ject/Desktop/misc']
143 INFO: checking Analysis
163 INFO: checking PYZ
173 INFO: checking PKG
175 INFO: Bootloader /usr/local/lib/python3.8/dist-packages/PyInstaller/bootloader/Linux-64bit/run
175 INFO: checking EXE
176 INFO: Rebuilding EXE-00.toc because BinBoot2_1_1Halloween missing
176 INFO: Building EXE from EXE-00.toc
177 INFO: Appending archive to ELF section in EXE /home/enigmapr0ject/Desktop/misc/dist/BinBoot2_1_1Halloween
283 INFO: Building EXE from EXE-00.toc completed successfully.
root@enigmamachine:/home/enigmapr0ject/Desktop/misc# cd dist/
root@enigmamachine:/home/enigmapr0ject/Desktop/misc/dist# ./BinBoot2_1_1Halloween 
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth__tkinter.py", line 28, in <module>
FileNotFoundError: Tcl data directory "/tmp/_MEIf2afR0/tcl" not found.
[10565] Failed to execute script pyi_rth__tkinter`


This is the new output after removing the old spec file (that was the cause of the HTML line).

**Comment by rokm** [comment]
Can you either remove `build` and `dist` directories and rebuild again, or try building with added `--clean` argument?

**Comment by rokm** [comment]
> Edit: I am guessing the TCL stuff it wants to find is being searched for in the wrong directory. I suppose it wants the /usr/share/tcltk... directories rather than a /tmp one seeing as that is cleared every time the system boots.

No, the `tcl8.6` and `tk8.6` directories from `/usr/share/tcltk` are collected to program's directory as `tcl` and `tk`. In the case of `onefile` build, the whole thing is unpacked to a temporary directory (e.g., `/tmp/_MEIf2afR0`), hence it's looking for `/tmp/_MEIf2afR0/tcl`. 

So this is correct, and the issue is that those directories haven't been copied in the first place - hopefully your build log will shed some light on why.

**Comment by projectintel-anon** [comment]
Where do I get the build log? The only build log I have is the one I most recently sent - that was after deleting the dist directory and rebuilding, hence the messy Javascript is gone.

**Comment by rokm** [comment]
You should delete *both* `dist` and `build` directories (or build with `--clean` to force full rebuild).

**Comment by projectintel-anon** [comment]
Ok I'll try that when I am at my PC and let you know what happens :)
