### ISSUE TITLE
pip install pyinstaller fails

### ISSUE THREAD

**Issue by CMTaylor** [pyinstaller/pyinstaller#5297]
pip install pyinstaller
Collecting pyinstaller
  Downloading https://files.pythonhosted.org/packages/82/96/21ba3619647bac2b34b4996b2dbbea8e74a703767ce24192899d9153c058/pyinstaller-4.0.tar.gz (3.5MB)
    100% |################################| 3.5MB 353kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\mtaylor\appdata\local\temp\pip-build-so6pka\pyinstaller\setup.py", line 63
        file=sys.stderr)
            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\mtaylor\appdata\local\temp\pip-build-so6pka\pyinstaller\

**Comment by rokm** [comment]
> File "c:\users\mtaylor\appdata\local\temp\pip-build-so6pka\pyinstaller\setup.py", line 63
file=sys.stderr)
^
SyntaxError: invalid syntax

That's a python2 syntax error. Your `pip` command is coming from a python2 installation, which is not supported.

**Comment by BoboTiG** [comment]
You should prefer that command, always:
```shell
python -m pip ...
```
Replace "python" with "python3" if needed.

**Comment by CMTaylor** [comment]
I've gone back to an earlier version of pyinstaller that did support Python
2.

**Comment by AstralPresence** [comment]
which version is that?

**Comment by 2314samship** [comment]
I had this same issue, it seems it wants to install on Python 2.  I used this command and it worked like a charm:
**python3 -m pip install pyinstaller**

**Comment by ErnHem** [comment]
> which version is that?

pyinstaller==3.6
