### ISSUE TITLE
Unable to access Jarfile

### ISSUE THREAD

**Issue by indiancharlzz** [pyinstaller/pyinstaller#5298]
**## Description of the issue:**
Experiencing an issue with the ".exe" being created to extract data from PDF file using tabula-py

Error Message
*******
Error from tabula-java:
Error: Unable to access jarfile C:\Users\AppData\Local\Temp\_MEI119562\tabula\tabula-1.0.4-jar-with-dependencies.jar
**********
**## Context information (for bug reports)**

* Output of `pyinstaller --version`:  4.0
* Version of Python: e.g. 3.7
* Platform: Windows 10
* Did you also try this on another platform? **No**

**### A minimal example program which shows the error**

import tabula
import pandas as pd

def get_transaction_line_items(pdf_file_path):
    df_trans = pd.DataFrame()
    try:
        df_all = tabula.read_pdf(pdf_file_path, lattice=True, guess=False, pages='all', pandas_options={'header': None})
        for df in df_all:
            df_trans = df_trans.append(df)
    except FileNotFoundError:
        raise FileNotFoundError('File Not Found: ' + pdf_file_path)

Need help or possible solution step in getting this issue fixed. The script works fine but the issue arises after an ".exe" being created.

**Comment by bwoodsend** [comment]
You just need to add the jar file as a data file. It's easiest to do this with the spec file. Edit the `.spec` file that should have been generated automatically. Put `from PyInstaller.utils.hooks import collect_data_files` at the top. And replace the `datas=[]` with `datas=collect_data_files("tabula")`. Then rebuild using `PyInstaller your-app-name.spec` from now on.

**Comment by eugenesamoylovdev** [comment]
I had the same problem and it helped, thank you so much!

**Comment by liu-jian-xin** [comment]
> You just need to add the jar file as a data file. It's easiest to do this with the spec file. Edit the `.spec` file that should have been generated automatically. Put `from PyInstaller.utils.hooks import collect_data_files` at the top. And replace the `datas=[]` with `datas=collect_data_files("tabula")`. Then rebuild using `PyInstaller your-app-name.spec` from now on.

I had the same problem and it helped,thank you so much!

**Comment by brunotombolini** [comment]
Hey, I had the same problem, and this solution worked perfectly!!

**Comment by brunotombolini** [comment]
Hey, I had the same problem, and this solution worked perfectly!! In the case at the end it tells you that you have Permission Errors, you should use the Prompt as an Administrator or disconnect the VPN (In the case you are using your work computer)

**Comment by lauSeoHua** [comment]
Thank you. This solution works. :)

> You just need to add the jar file as a data file. It's easiest to do this with the spec file. Edit the `.spec` file that should have been generated automatically. Put `from PyInstaller.utils.hooks import collect_data_files` at the top. And replace the `datas=[]` with `datas=collect_data_files("tabula")`. Then rebuild using `PyInstaller your-app-name.spec` from now on.
