### ISSUE TITLE
Searching for incorrect DLL file name

### ISSUE THREAD

**Issue by daheise** [pyinstaller/pyinstaller#5299]
## Description of the issue

A project I am I building on Windows 10 is looking for a `.dllc` file when it should be looking for a `.dll` file. The DLL is put into the `dist` folder correctly, but is searched for/linked incorrectly. Renaming the dll to dllc allows the exe to run.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```, also tried ```4.1.dev0```
* Version of Python: Python 3.8.5
* Platform: Windows 10 2004
* Did you also try this on another platform? No

### A minimal example program which shows the error

[Project in question is here](https://github.com/daheise/msfs_utils)

It contains this for binaries: `binaries=[(SPECPATH + "/env/Lib/site-packages/SimConnect/SimConnect.dll", './SimConnect/')]`

### Stacktrace / full error message

```
PyInstallerImportError Failed to load dynlib/dll '...\\simrate_control\\SimConnect\\SimConnect.dllc'. Most probably this dynlib/dll was not found when the application was frozen.
```

**Comment by rokm** [comment]
This is a bug in SimConnect. It is trying to find its library via:

https://github.com/odwdinc/Python-SimConnect/blob/b5cf4ef94c5f9d0ddf7db08582dec3dc39383453/SimConnect/SimConnect.py#L10-L12

```python
_library_path = os.path.abspath(__file__).replace(".py", ".dll")
```

In a frozen application, `__file__` in question becomes `SimConnect.pyc`, so the substitution above results in `SimConnect.dllc`...

**Comment by daheise** [comment]
Good find. Thanks! I'll take this to them.

**Comment by daheise** [comment]
I have confirmed your diagnosis with a local fix. I will close this issue.
