### ISSUE TITLE
lxml not fully included

### ISSUE THREAD

**Issue by doudz** [pyinstaller/pyinstaller#5306]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
Adding lxml to hiddenimports doesn't include the whole lxml library

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: 3.8.5
* Platform:  Windows 10

To solve the problem I add the following in the spec file :
```
from PyInstaller.utils.hooks import collect_submodules

hiddenimports=[......]

hiddenimports += collect_submodules('lxml')     
```

**Comment by bwoodsend** [comment]
If you want it fixed permanently then write a hook containing your fix snippet and add it to the [hooks repo](https://github.com/pyinstaller/pyinstaller-hooks-contrib/).
