### ISSUE TITLE
Error when running .exe

### ISSUE THREAD

**Issue by PETEROLO291** [pyinstaller/pyinstaller#5307]
## Description of the issue
When i run my code works fine, but when I compile and run the exe I get this error:

Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "reconnect_PSG.py", line 44, in check_ping
  File "subprocess.py", line 376, in check_output
  File "subprocess.py", line 455, in run
  File "subprocess.py", line 907, in communicate
  File "c:\users\peter\appdata\local\programs\python\python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 277: invalid start byte

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: e.g. 3.7
* Platform: Windows 10 Pro
* Did you also try this on another platform? Does it work there?
Didn't try

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Same error

### A minimal example program which shows the error
https://paste.pythondiscord.com/soliwesudu.py

### Stacktrace / full error message

```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 917, in _bootstrap_inner
  File "threading.py", line 865, in run
  File "reconnect_PSG.py", line 44, in check_ping
  File "subprocess.py", line 376, in check_output
  File "subprocess.py", line 455, in run
  File "subprocess.py", line 907, in communicate
  File "c:\users\peter\appdata\local\programs\python\python37\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 277: invalid start byte

```

**Comment by rokm** [comment]
Can you try running that `check_output()` without `universal_newlines` and check what the returned bytes are? I suppose the easiest way would be to add a try-except block around the original `check_output()` command, catch the `UnicodeDecodeError` and re-run the `check_output()` without `universal_newlines` to see what kind of output is triggering the error.

**Comment by PETEROLO291** [comment]
@rokm Can you write that for me, didn0t undertand what exactly to do

**Comment by BoboTiG** [comment]
@PETEROLO291 you should try to reduce the Python code to only the revelant part that cause the failure. It will be easier for us to help then.

**Comment by rokm** [comment]
In the example you provided, you have this `check_output` call that is failing, because `universal_newlines=True` is forcing bytes -> string conversion (with incompatible encoding, I assume):
```python
    try:
        response = check_output(
            ['ping', '-c', '1', host],
            stderr=STDOUT,  # get all output
            universal_newlines=True  # return string not bytes
        )


        if 'Destination host unreachable' in response:
            response = None
        else:
            response = 0
    except CalledProcessError:
        response = None
```

I would like to see what the output that triggers the message actually is (I suspect it is a message in non-English locale, with a non-Latin character causing the error during decode. So the idea is to capture the raw message (as bytes) and print it. For example:
```python
    try:
        response = check_output(
            ['ping', '-c', '1', host],
            stderr=STDOUT,  # get all output
            universal_newlines=True  # return string not bytes
        )


        if 'Destination host unreachable' in response:
            response = None
        else:
            response = 0
    except CalledProcessError:
        response = None
    except UnicodeDecodeError:
        raw_response = check_output(
            ['ping', '-c', '1', host],
            stderr=STDOUT,  # get all output
            universal_newlines=False # return bytes
        )
        print("Problematic output:", raw_response)
        raise
```

**Comment by PETEROLO291** [comment]
Hum, now for juat no reason """works""". No error, but the try element doent apear, and it consumes 30%cpu and there constatly pop up ping windows and desapear. Why if the python file works, the exe doesnt?

**Comment by PETEROLO291** [comment]
Hum, now for juat no reason """works""". No error, but the try element doent apear, and it consumes 30%cpu and there constatly pop up ping windows and desapear. Why if the python file works, the exe doesnt?

**Comment by rokm** [comment]
Like @BoboTiG suggested, you should try to isolate the offending code in a small stand-alone program to reproduce the issue - it will make it much easier to figure out what's going on. I.e, a simple program with no GUI that makes the `check_output()` call...

For what is worth, you can try calling `check_output()` with `universal_newlines=False` and then try decoding the bytes to string yourself, with option to replace the invalid characters with '?', e.g.:
```python
    ...
    try:
        response = check_output(
            ['ping', '-c', '1', host],
            stderr=STDOUT,  # get all output
            universal_newlines=False  # return bytes
        )
        response = response.decode(encoding="utf-8", errors="replace")

        if 'Destination host unreachable' in response:
            response = None
        else:
            response = 0
    except CalledProcessError:
        response = None
    ...
```

But if you are getting non-Latin characters in the output, there's probably some locale-related things going on that you are not anticipating, and looking for `Destination host unreachable` in response will not do you any good (since the response message is likely localized).

**Comment by PETEROLO291** [comment]
Well, now the problem is no longer that. The error disappeared, The problem is the UI:

```
import PySimpleGUIWx as sg
import PySimpleGUIQt as sg
from PySimpleGUI import SystemTray, popup
from time import sleep
from os import system
from random import choice
from threading import Thread
from subprocess import check_output, CalledProcessError, STDOUT



hosts = ['1.1.1.1', 'google.es', '8.8.4.4']

veces_reconectado = 0

running = True

pingstatus = ""

noti_status = False







menu_def = ['BLANK', ['Reconexiones', 'Estado', 'Alertas', ['Activadas', 'Desactivadas', '---', '¿Qué es?'], 'Info', '---', 'Salir']]




tray = sg.SystemTray(menu=menu_def, filename=r"unnamed.ico")



while True:  # The event loop
    event = tray.read()

    if event == 'Salir':
        running = False
        break

    elif event == 'Reconexiones':
        sg.popup('Has sido reconectado ' + str(veces_reconectado) + ' veces.', icon="unnamed.ico", title="Reconexiones", font=('Helvetica 13'))



    elif event == "Estado":
        if pingstatus == "":
            sg.popup("Comprobando... Intentalo de nuevo mas tarde.", icon="unnamed.ico", title="Estado", font=('Helvetica 13'))

        
        elif pingstatus == "activo" or "inactivo":
            sg.popup("El estado de el wifi es: " + pingstatus, icon="unnamed.ico", title="Estado", font=('Helvetica 13'))



    elif event == "Info":
        sg.popup("Con mucho amor por parte de Peter <3 uwu", icon="unnamed.ico", title="Info", font=('Helvetica 13'))




    elif event == "Activadas":
        noti_status = True



    elif event == "Desactivadas":
        noti_status = False



    elif event == "¿Qué es?":
        sg.popup("Al activar las alertas recibirás una notificación al perder la conexión a internet.", icon="unnamed.ico", title="¿Qué es?", font=('Helvetica 13'))


tray.close()
```

If you run this as a pie file will work and appear an icon on the tray, converted to exe, absolutely nothing, to stop the program I must go to Task manager and kill the exe

**Comment by rokm** [comment]
The following minimal example based on PySimpleGui's documentation works just fine in frozen version:
```python
import PySimpleGUIQt as sg

menu_def = ['BLANK', ['&Open', '---', '&Save', ['1', '2', ['a', 'b']], '&Properties', 'E&xit']]

tray = sg.SystemTray(menu=menu_def, data_base64=sg.DEFAULT_BASE64_ICON)

while True:  # The event loop
    menu_item = tray.read()
    if menu_item == 'Exit':
        break
    elif menu_item == 'Open':
        sg.popup('Menu item chosen', menu_item)
```

**Comment by rokm** [comment]
> tray = sg.SystemTray(menu=menu_def, filename=r"unnamed.ico")

Have you included the icon file (`unnamed.ico`) in the data to be collected by PyInstaller? Because if the icon file is missing, you will get the behavior you're describing...

And also instead of just providing the icon filename, you will probably also need to [provide the full path, relative to the _MEIPASS dir](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html).

But for the start, you can try using `data_base64=sg.DEFAULT_BASE64_ICON` instead of `filename=r"unnamed.ico"` to confirm that the missing icon is indeed the problem...

**Comment by PETEROLO291** [comment]
The icon its not the problem, and yes, I have already tested with def icon

**Comment by PETEROLO291** [comment]
Well... Now im thinking, and.. Mybe the important thing is to add an extra file when compileing and add the icon image. Mybe thats the prob idk. (auto-py-to-exe)

**Comment by PETEROLO291** [comment]
Hello? @rokm

**Comment by PETEROLO291** [comment]
K now works. Had to move thr ico into the same folder hahaha sorry
