### ISSUE TITLE
How to use splash feature ?

### ISSUE THREAD

**Issue by superuser789** [pyinstaller/pyinstaller#5310]
Hi,
I want to use the 'splash' feature of pyinstaller. It is not available in pip version. So ,I  built and installed the latest pyinstaller sources. But still  `--splash` is not there. 
Could anybody guide me how can I run the build with splash feature  and its documentation/usage  ?

Thanks.

**Comment by BoboTiG** [comment]
Such feature does not exist yet, but a PR exists: #4887.
