### ISSUE TITLE
pipinstaller build qt application error

### ISSUE THREAD

**Issue by mr-tan4** [pyinstaller/pyinstaller#5311]
> System environment:
>
> > System: Mac os x
> >
> > version: 10.15.7 (19H2)
> >
> > python
> > 	version: 3.7
> >
> > pyinstaller:
> >
> > ​	version: 4.0

> Command: pyinstaller -F run.py
>
> ```172 INFO: PyInstaller: 4.0
> 173 INFO: Python: 3.7.5
> 180 INFO: Platform: Darwin-19.6.0-x86_64-i386-64bit
> 181 INFO: wrote /Users/robert/PycharmProjects/BigScreen/run.spec
> 184 INFO: UPX is not available.
> 185 INFO: Extending PYTHONPATH with paths
> ['/Users/robert/PycharmProjects/BigScreen',
>  '/Users/robert/PycharmProjects/BigScreen']
> 195 INFO: checking Analysis
> 228 INFO: Building because inputs changed
> 228 INFO: Initializing module dependency graph...
> 231 INFO: Caching module graph hooks...
> 238 INFO: Analyzing base_library.zip ...
> 3300 INFO: Caching module dependency graph...
> 3393 INFO: running Analysis Analysis-00.toc
> 3400 INFO: Analyzing /Users/robert/PycharmProjects/BigScreen/run.py
> 3437 INFO: Processing module hooks...
> 3437 INFO: Loading module hook 'hook-cv2.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
> 3867 INFO: Processing pre-find module path hook distutils from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
> 3869 INFO: distutils: retargeting to non-venv dir '/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7'
> 4965 INFO: Processing pre-find module path hook site from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks/pre_find_module_path/hook-site.py'.
> 4966 INFO: site: retargeting to fake-dir '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/fake-modules'
> 6978 INFO: Loading module hook 'hook-pkg_resources.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 7184 INFO: Processing pre-safe import module hook win32com from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
> 7407 WARNING: Hidden import "pkg_resources.py2_warn" not found!
> 7407 WARNING: Hidden import "pkg_resources.markers" not found!
> 7408 INFO: Excluding import '__main__'
> 7409 INFO:   Removing import of __main__ from module pkg_resources
> 7409 INFO: Loading module hook 'hook-PyQt5.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 7532 WARNING: Hidden import "sip" not found!
> 7532 INFO: Loading module hook 'hook-lib2to3.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 7567 INFO: Loading module hook 'hook-encodings.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 7624 INFO: Loading module hook 'hook-setuptools.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 8138 INFO: Loading module hook 'hook-PyQt5.QtWebEngineWidgets.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 8719 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 8761 INFO: Loading module hook 'hook-PyQt5.QtPrintSupport.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 8825 INFO: Loading module hook 'hook-PyQt5.QtQml.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 8921 INFO: Loading module hook 'hook-PyQt5.QtQuickWidgets.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9025 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9073 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9081 INFO: Loading module hook 'hook-numpy.core.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9300 INFO: Loading module hook 'hook-PyQt5.QtNetwork.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9322 INFO: Loading module hook 'hook-xml.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9380 INFO: Loading module hook 'hook-numpy.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9381 INFO: Loading module hook 'hook-distutils.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9382 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9393 INFO: Loading module hook 'hook-PyQt5.QtQuick.py' from '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks'...
> 9478 INFO: Looking for ctypes DLLs
> 9517 INFO: Analyzing run-time hooks ...
> 9522 INFO: Including run-time hook '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
> 9525 INFO: Including run-time hook '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5webengine.py'
> 9527 INFO: Including run-time hook '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
> 9531 INFO: Including run-time hook '/Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
> 9543 INFO: Looking for dynamic libraries
> 9840 ERROR: Can not find path ./Qt3DInput.framework/Versions/5/Qt3DInput (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
> 9840 ERROR: Can not find path ./Qt3DCore.framework/Versions/5/Qt3DCore (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
> 9841 ERROR: Can not find path ./Qt3DQuick.framework/Versions/5/Qt3DQuick (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
> 9841 ERROR: Can not find path ./Qt3DLogic.framework/Versions/5/Qt3DLogic (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
> 9841 ERROR: Can not find path ./Qt3DQuickScene2D.framework/Versions/5/Qt3DQuickScene2D (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
> 9841 ERROR: Can not find path ./Qt3DRender.framework/Versions/5/Qt3DRender (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
> 9841 ERROR: Can not find path ./QtGamepad.framework/Versions/5/QtGamepad (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)
> 9949 ERROR: Can not find path ./QtMultimediaQuick.framework/Versions/5/QtMultimediaQuick (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtMultimedia/libdeclarative_multimedia.dylib)
> 10069 ERROR: Can not find path ./Qt3DInput.framework/Versions/5/Qt3DInput (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
> 10069 ERROR: Can not find path ./Qt3DCore.framework/Versions/5/Qt3DCore (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
> 10070 ERROR: Can not find path ./Qt3DLogic.framework/Versions/5/Qt3DLogic (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
> 10070 ERROR: Can not find path ./Qt3DAnimation.framework/Versions/5/Qt3DAnimation (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
> 10070 ERROR: Can not find path ./Qt3DRender.framework/Versions/5/Qt3DRender (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
> 10070 ERROR: Can not find path ./QtGamepad.framework/Versions/5/QtGamepad (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene3D/libqtquickscene3dplugin.dylib)
> 11549 INFO: Looking for eggs
> 11549 INFO: Using Python library /Library/Frameworks/Python.framework/Versions/3.7/Python
> 11555 INFO: Warnings written to /Users/robert/PycharmProjects/BigScreen/build/run/warn-run.txt
> 11606 INFO: Graph cross-reference written to /Users/robert/PycharmProjects/BigScreen/build/run/xref-run.html
> 11688 INFO: checking PYZ
> 11693 INFO: Building because toc changed
> 11693 INFO: Building PYZ (ZlibArchive) /Users/robert/PycharmProjects/BigScreen/build/run/PYZ-00.pyz
> 12390 INFO: Building PYZ (ZlibArchive) /Users/robert/PycharmProjects/BigScreen/build/run/PYZ-00.pyz completed successfully.
> 12406 INFO: checking PKG
> 12427 INFO: Building because toc changed
> 12427 INFO: Building PKG (CArchive) PKG-00.pkg
> 105265 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
> 105324 INFO: Bootloader /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyInstaller/bootloader/Darwin-64bit/run
> 105324 INFO: checking EXE
> 105340 INFO: Building because console changed
> 105341 INFO: Building EXE from EXE-00.toc
> 105370 INFO: Appending archive to EXE /Users/robert/PycharmProjects/BigScreen/dist/run
> 105804 INFO: Fixing EXE for code signing /Users/robert/PycharmProjects/BigScreen/dist/run
> 105812 INFO: Building EXE from EXE-00.toc completed successfully.
> (venv)
> ```

**Comment by rokm** [comment]
If you are referring to error messages like:
> 9840 ERROR: Can not find path ./Qt3DInput.framework/Versions/5/Qt3DInput (needed by /Users/robert/PycharmProjects/BigScreen/venv/lib/python3.7/site-packages/PyQt5/Qt/qml/QtQuick/Scene2D/libqtquickscene2dplugin.dylib)

then there's nothing we can do about those. The plugin file `libqtquickscene2dplugin.dylib` does indeed reference these dynamic libraries, but they are not included in the PyQt5 package. 

You very likely are not using that plugin in your application (because you wouldn't be able to load it in the unfrozen program anyway, due to the missing libraries), so those messages are harmless...
