### ISSUE TITLE
When python executable file does not display the console ,command code will not execute

### ISSUE THREAD

**Issue by yuwan1994** [pyinstaller/pyinstaller#5312]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue

use -w to shut down console window，click commit button, command code does not run.

## Context information (for bug reports)

Output of pyinstaller --version: 4.0

Version of Python: 3.9

Platform: windows10
* Did you also try this on another platform? Does it work there?
No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
def runjscripts():
    """
    运行脚本
    @return:
    @rtype:
    """

    res = os.popen(f'jmeter -n -t {uploadfile} -l {testfile} -e -o {folder}')
    for item in res:
        self.listbox_add_info(info_box, item)

commit = Button(self.run_jmeter_script_frame, text='运行脚本', command=runjscripts, height=1)
commit.grid(row=15, column=2)

```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Can you implement proper error handling for your `popen` call? I.e., put the `popen` in a try/except block and display a dialog with the exception message (or save it to a file) to see what the error is?
