### ISSUE TITLE
pkg_resources.DistributionNotFound: The 'gcloud' distribution was not found 

### ISSUE THREAD

**Issue by happyeric77** [pyinstaller/pyinstaller#5316]
## To repreduce :

1. Install google firebase python sdk
```
pip install pyrebase 
```

2. create the python script:
foo.py
```
touch foo.py
```

3. In the script, import pyrebase
```
echo 'import pyrebase' >> foo.py
```
4. Use pyinstaller trying to pack it as executable file.
```
pyinstaller -F foo.py
```
5. Following error shows:
```
pkg_resources.DistributionNotFound: The 'gcloud' distribution was not found and is required by the application ​​[52934] Failed to execute script
```

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```

* Version of Python: 3.7.3

* Platform: Windows10 by anaconda env

* Did you also try this on another platform? Does it work there?  yes, but all shows the same error code.
  - Linux(raspberrypiOS) by pyvenv env
  - OS X (Catalina) by anaconda env

I found the cause and successfully fixed it (as below), ***could you assign it to me and I will fork it and contribute.***

1. touch hook-gcloud.py into hooks directory

2. Add following content:

```
from PyInstaller.utils.hooks import copy_metadata
datas = copy_metadata('gcloud')
```

### Then everything work out on all the platforms listed above.
If it is reasonable, please assign the issue to me. thanks!

**Comment by rokm** [comment]
Your proposed fix is indeed the correct one. 

Can you please contribute the hook to the [pyinstaller-hooks-contrib repository](https://github.com/pyinstaller/pyinstaller-hooks-contrib)? Thanks!
