### ISSUE TITLE
Supply encryption key separately from the distribution

### ISSUE THREAD

**Issue by mlmarius** [pyinstaller/pyinstaller#5317]
I figure it would be nice to have the ability to distribute the encryption key separately from the actual compiled application sources. This way the application could be publicly made available for download but only trusted clients could run it.

The key could be supplied via environment variables, passed as command line argument, or special (dot)file in the same dir as the executable.

**Comment by bwoodsend** [comment]
Why not just put your application in an encrypted zip file or, for onefile applications, encrypt the file yourself? That way, the person using it wouldn't have to pass the decryption key every time they want to run it.
