### ISSUE TITLE
The 'prettytable' distribution was not found 

### ISSUE THREAD

**Issue by anojalax** [pyinstaller/pyinstaller#5319]
I am trying to create an executable from a python file that has prettytable module.

> C:\Users\XXX> pyinstaller --onefile Main.py
> 38 INFO: PyInstaller: 3.4
> 38 INFO: Python: 3.7.7
> 38 INFO: Platform: Windows-10-10.0.18362-SP0
> 49 INFO: wrote C:\Users\XXX\Main.spec
> 49 INFO: UPX is not available.
> 53 INFO: Extending PYTHONPATH with paths
> ['C:\Users\XXX',
>  'C:\Users\XXX']
> 53 INFO: checking Analysis
> 53 INFO: Building Analysis because Analysis-00.toc is non existent
> 53 INFO: Initializing module dependency graph...
> 53 INFO: Initializing module graph hooks...
> 53 INFO: Analyzing base_library.zip ...
> 1455 INFO: Processing pre-find module path hook   distutils
> 2229 INFO: running Analysis Analysis-00.toc
> 2242 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
>   required by c:\users\xxx\appdata\local\programs\python\python37\python.exe
> 2286 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python.exe
> 2322 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python.exe
> 2361 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python.exe
> 2399 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python.exe
> 2435 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python.exe
> 2475 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\VCRUNTIME140.dll
> 2513 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\VCRUNTIME140.dll
> 2551 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\VCRUNTIME140.dll
> 2588 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\VCRUNTIME140.dll
> 2625 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\VCRUNTIME140.dll
> 2674 WARNING: lib not found: api-ms-win-crt-conio-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 2711 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 2751 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 2787 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 2825 WARNING: lib not found: api-ms-win-crt-process-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 2862 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 2905 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 2943 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 2982 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 3016 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 3050 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 3087 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of C:\Users\XXX\appdata\local\programs\python\python37\python37.dll
> 3087 INFO: Caching module hooks...
> 3101 INFO: Analyzing C:\Users\XXX\Main.py
> 3267 INFO: Processing pre-find module path hook   site
> 3267 INFO: site: retargeting to fake-dir 'C:\Users\XXX\\appdata\\local\\programs\\python\\python37\\lib\\site-packages\\PyInstaller\\fake-modules'
> 4357 INFO: Processing pre-safe import module hook   setuptools.extern.six.moves
> 5826 INFO: Loading module hooks...
> 5826 INFO: Loading module hook "hook-distutils.py"...
> 5834 INFO: Loading module hook "hook-encodings.py"...
> 5906 INFO: Loading module hook "hook-lib2to3.py"...
> 5906 INFO: Loading module hook "hook-pkg_resources.py"...
> 6145 INFO: Processing pre-safe import module hook   win32com
> 6326 INFO: Loading module hook "hook-pycparser.py"...
> 6326 INFO: Loading module hook "hook-pydoc.py"...
> 6332 INFO: Loading module hook "hook-pythoncom.py"...
> 6563 INFO: Loading module hook "hook-pywintypes.py"...
> 6795 INFO: Loading module hook "hook-setuptools.py"...
> 7179 INFO: Loading module hook "hook-sysconfig.py"...
> 7183 INFO: Loading module hook "hook-win32com.py"...
> 7566 INFO: Loading module hook "hook-xml.dom.domreg.py"...
> 7566 INFO: Loading module hook "hook-xml.py"...
> 7585 INFO: Looking for ctypes DLLs
> 7601 INFO: Analyzing run-time hooks ...
> 7601 INFO: Including run-time hook 'pyi_rth_pkgres.py'
> 7601 INFO: Including run-time hook 'pyi_rth_win32comgenpy.py'
> 7614 INFO: Including run-time hook 'pyi_rth_multiprocessing.py'
> 7617 INFO: Looking for dynamic libraries
> 7667 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pythoncom37.dll
> 7700 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pythoncom37.dll
> 7733 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pythoncom37.dll
> 7780 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pythoncom37.dll
> 7817 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pythoncom37.dll
> 7849 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pywintypes37.dll
> 7899 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pywintypes37.dll
> 7933 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pywintypes37.dll
> 7980 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pywintypes37.dll
> 8019 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pywintypes37.dll
> 8049 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\pywin32_system32\pywintypes37.dll
> 8100 WARNING: lib not found: api-ms-win-crt-locale-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_decimal.pyd
> 8133 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_decimal.pyd
> 8166 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_decimal.pyd
> 8216 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_decimal.pyd
> 8251 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_decimal.pyd
> 8283 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_decimal.pyd
> 8320 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_decimal.pyd
> 8365 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_ctypes.pyd
> 8399 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_ctypes.pyd
> 8449 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_ctypes.pyd
> 8482 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_queue.pyd
> 8538 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_multiprocessing.pyd
> 8566 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32trace.pyd
> 8614 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32trace.pyd
> 8649 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\win32ui.pyd
> 8700 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\win32ui.pyd
> 8733 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\win32ui.pyd
> 8766 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\win32ui.pyd
> 8799 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\win32ui.pyd
> 8849 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\win32ui.pyd
> 8883 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\_win32sysloader.pyd
> 8933 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32api.pyd
> 8966 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32api.pyd
> 9016 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32api.pyd
> 9049 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32api.pyd
> 9083 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32wnet.pyd
> 9133 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32wnet.pyd
> 9166 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32\win32wnet.pyd
> 9199 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32comext\shell\shell.pyd
> 9249 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32comext\shell\shell.pyd
> 9283 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\win32comext\shell\shell.pyd
> 9333 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\_cffi_backend.cp37-win_amd64.pyd
> 9367 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\_cffi_backend.cp37-win_amd64.pyd
> 9399 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\_cffi_backend.cp37-win_amd64.pyd
> 9432 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\_cffi_backend.cp37-win_amd64.pyd
> 9481 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\_cffi_backend.cp37-win_amd64.pyd
> 9515 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\_cffi_backend.cp37-win_amd64.pyd
> 9549 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_ssl.pyd
> 9599 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_ssl.pyd
> 9633 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_ssl.pyd
> 9666 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\pyexpat.pyd
> 9716 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\pyexpat.pyd
> 9749 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\pyexpat.pyd
> 9808 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\pyexpat.pyd
> 9849 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\pyexpat.pyd
> 9891 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_hashlib.pyd
> 9933 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_lzma.pyd
> 9966 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_lzma.pyd
> 10016 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_socket.pyd
> 10051 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_socket.pyd
> 10100 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\unicodedata.pyd
> 10166 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\unicodedata.pyd
> 10199 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\unicodedata.pyd
> 10233 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_bz2.pyd
> 10283 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_bz2.pyd
> 10317 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_bz2.pyd
> 10349 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_bz2.pyd
> 10396 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\_bz2.pyd
> 10433 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\select.pyd
> 10483 WARNING: lib not found: api-ms-win-crt-multibyte-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10516 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10549 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10598 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10632 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10665 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10716 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10750 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10783 WARNING: lib not found: api-ms-win-crt-math-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10817 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\Pythonwin\mfc140u.dll
> 10866 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libssl-1_1.dll
> 10899 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libssl-1_1.dll
> 10981 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libssl-1_1.dll
> 11016 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libssl-1_1.dll
> 11049 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libssl-1_1.dll
> 11099 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libssl-1_1.dll
> 11150 WARNING: lib not found: api-ms-win-crt-utility-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11183 WARNING: lib not found: api-ms-win-crt-convert-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11233 WARNING: lib not found: api-ms-win-crt-heap-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11266 WARNING: lib not found: api-ms-win-crt-filesystem-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11299 WARNING: lib not found: api-ms-win-crt-string-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11333 WARNING: lib not found: api-ms-win-crt-stdio-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11366 WARNING: lib not found: api-ms-win-crt-environment-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11416 WARNING: lib not found: api-ms-win-crt-time-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11451 WARNING: lib not found: api-ms-win-crt-runtime-l1-1-0.dll dependency of c:\users\xxx\appdata\local\programs\python\python37\DLLs\libcrypto-1_1.dll
> 11451 INFO: Looking for eggs
> 11451 INFO: Using Python library c:\users\xxx\appdata\local\programs\python\python37\python37.dll
> 11466 INFO: Found binding redirects:
> []
> 11476 INFO: Warnings written to C:\Users\XXX\build\Main\warn-Main.txt
> 11533 INFO: Graph cross-reference written to C:\Users\XXX\build\Main\xref-Main.html
> 11550 INFO: checking PYZ
> 11550 INFO: Building PYZ because PYZ-00.toc is non existent
> 11550 INFO: Building PYZ (ZlibArchive) C:\Users\XXX\build\Main\PYZ-00.pyz
> 12335 INFO: Building PYZ (ZlibArchive) C:\Users\XXX\build\Main\PYZ-00.pyz completed successfully.
> 12353 INFO: checking PKG
> 12353 INFO: Building PKG because PKG-00.toc is non existent
> 12356 INFO: Building PKG (CArchive) PKG-00.pkg
> 14665 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
> 14671 INFO: Bootloader c:\users\xxx\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
> 14671 INFO: checking EXE
> 14672 INFO: Building EXE because EXE-00.toc is non existent
> 14673 INFO: Building EXE from EXE-00.toc
> 14673 INFO: Appending archive to EXE C:\Users\XXX\dist\Main.exe
> 14695 INFO: Building EXE from EXE-00.toc completed successfully.

The exe was created successfully, but while running it, distribution is not found error happens.

> C:\Users\anoja.rajalakshmi>C:\Users\XXX\dist\Main.exe
> Traceback (most recent call last):
>   File "Main.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "c:\users\anoja.rajalakshmi\appdata\local\programs\python\python37\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
>     exec(bytecode, module.__dict__)
>   File "site-packages\prettytable.py", line 48, in <module>
>   File "site-packages\pkg_resources\__init__.py", line 481, in get_distribution
>   File "site-packages\pkg_resources\__init__.py", line 357, in get_provider
>   File "site-packages\pkg_resources\__init__.py", line 900, in require
>   File "site-packages\pkg_resources\__init__.py", line 786, in resolve
> pkg_resources.DistributionNotFound: The 'prettytable' distribution was not found and is required by the application
> [12304] Failed to execute script Main

Here is the python script I ran.

```
import prettytable
outputTable = prettytable.PrettyTable(["Sr No"])
print("Hello")
```

I was running Pyinstaller 3.4 but updating it to 4.0 also has no luck.

**Comment by rokm** [comment]
You will need to use `collect_metadata()` to collect metadata for `prettytable`, either by writing a custom hook or by modifying the `.spec` file.

Take a look at #5316, which describes the solution for the same problem with a different package.
