### ISSUE TITLE
reset of PYTHONHOME as early as possible

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#532]
**Original date**: 2012/03/20

Move the reset of PYTHONHOME as early as possible, that is immediately after Py_Initialize. Ideally, there should be some code like:
```
   save PYTHOHOME current value
   set PYTHONHOME
   Py_Initialize()
   reset PYTHONHOME to original value
```
that immediately makes clear where PYTHONHOME is useful.

I just checked the code in launch.c and PYTHONHOME is set immediately before Py_Initialize(). So we just need to reset it back to the original value a few lines after.

**Comment by codewarrior0** [comment]
This is already done: PyInstaller is neither affected by nor affects the PYTHONHOME and PYTHONPATH environs. The C API is used to pass PyInstaller's own settings to Python and to tell Python to ignore the environs.
