### ISSUE TITLE
pyinstaller doesn't work with Big Sur 

### ISSUE THREAD

**Issue by MichaelHein65** [pyinstaller/pyinstaller#5320]
Hello I just installed Big Sur on my Macbook.
Yesterday pyinstaller worked without any issue.
Today it shows UPX not available.

**Can someone help?**

_67 INFO: PyInstaller: 4.0
67 INFO: Python: 3.8.3 (conda)
74 INFO: Platform: macOS-10.16-x86_64-i386-64bit
75 INFO: wrote /Users/michaelhein/Spyder/py-files/Bilder-move2.spec
77 INFO: UPX is not available.
script '/Users/michaelhein/Spyder/py-files/—onefile' not found
(base) michaelhein@Michaels-MacBook-Pro py-files %_

**Comment by rokm** [comment]
>  script '/Users/michaelhein/Spyder/py-files/—onefile' not found

This looks like a typo in the parameters you put on the command-line, i.e., instead of `--onefile` (with two short dashes), you put in `—onefile` (with U+2014 em dash), which is therefore incorrectly interpreted as (an additional) filename.

**Comment by MichaelHein65** [comment]
Thank you.
It works now.
Howe stupid not looking for the minor thinks.
