### ISSUE TITLE
I cant convert my python file to exe using pyinstaller.

### ISSUE THREAD

**Issue by YegorGuy** [pyinstaller/pyinstaller#5325]
So I used a simple file name test.py with this code: 
`print("Hi")`

Then I tiped "pyinstaller test.py" in my cmd.
it gived me this "Fatal error in launcher:" and thats is all.

How do i fix this error?

**Comment by SunHxiao** [comment]
![image](https://user-images.githubusercontent.com/56060401/99469879-aa04ee00-297e-11eb-8924-2d6008f0af63.png)
I am very interested in pyinstaller.
But when I am going to use the pyinstaller, I met these issues.
Would you kindly fix this issue for me?
Thanks.

**Comment by Legorooj** [comment]
@SunHxiao please open a new issue, and fill out the issue template.

@YegorGuy please fill out the issue template, at which point we can reopen.
