### ISSUE TITLE
EXE crashes when run outside build environment

### ISSUE THREAD

**Issue by EBenkler** [pyinstaller/pyinstaller#5326]
## Description of the issue
I have written a Pyqt5 GUI python script that I want to bundle using pyinstaller. I use a conda env 
## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.0```
* Version of Python: 3.86
* Platform: Windows (language settings)
* Did you also try this on another platform? No
I tried to use the dev version, but could not install it, as I am using conda and pip installation failed because I'm behind a proxy.

The EXE suddenly crashes without any error message. Below I attach the debug outputs for a) starting the EXE from within the conda environment in which I have built the pyinstaller bundle, and for b)  starting the EXE outside the conda env, where it crashes right before the line 
import 'numpy' # <pyimod03_importers.FrozenImporter object at 0x000002D704C7F2B0>
outside env:
[knoten.txt](https://github.com/pyinstaller/pyinstaller/files/5550241/knoten.txt)
inside env:
[knoten_env.txt](https://github.com/pyinstaller/pyinstaller/files/5550242/knoten_env.txt)

**Comment by EBenkler** [comment]
Similar to [https://github.com/pyinstaller/pyinstaller/issues/4984](https://github.com/pyinstaller/pyinstaller/issues/4984)

**Comment by rokm** [comment]
Since your logs suggest you're using `numpy` and `conda`, this is probably the issue of missing `libiomp5md`. Take a look at https://github.com/pyinstaller/pyinstaller/issues/4968#issuecomment-662075970.

**Comment by EBenkler** [comment]
Thanks for the quick response, that was the issue.
