### ISSUE TITLE
[5939] Failed to execute script train

### ISSUE THREAD

**Issue by PingHGao** [pyinstaller/pyinstaller#5331]
I am using pyinstaller to pack a python gui program to train yolov5. The python script runs normally in pycharm and cmd with conda environment. But when running the exe file packed by pyinstaller, errors below appears:
```
Traceback (most recent call last):
  File "train.py", line 14, in <module>
    import torch.distributed as dist
  File "/home/gph/anaconda3/envs/py38_pth16/lib/python3.8/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "torch/__init__.py", line 189, in <module>
ImportError: /tmp/_MEIebgYfG/./libstdc++.so.6: version `CXXABI_1.3.11' not found (required by /tmp/_MEIebgYfG/torch/lib/libtorch_python.so)
[32356] Failed to execute script train
```
My environment is:

- Ubuntu 16.04
- python 3.8
- pytorch 1.6
- pyinstaller 4.1
- conda 4.8.3 

Please help, Thanks a lot!

**Comment by rokm** [comment]
Sounds like pyinstaller ended up collecting incorrect version of `libstdc++.so.6` (e.g., the one from the base system instead of the one from your conda environment). No idea why, though - I did a quick test in xenial VM with conda, and it sees to pick the correct one for me...

Can you attach the full build log when running pyinstaller with `--log-level DEBUG` (please attach the log as a file, as opposed to copying the contents in a reply).

**Comment by PingHGao** [comment]
> Sounds like pyinstaller ended up collecting incorrect version of `libstdc++.so.6` (e.g., the one from the base system instead of the one from your conda environment). No idea why, though - I did a quick test in xenial VM with conda, and it sees to pick the correct one for me...
> 
> Can you attach the full build log when running pyinstaller with `--log-level DEBUG` (please attach the log as a file, as opposed to copying the contents in a reply).

Sorry @rokm , I can not reproduce this problem after I saw your suggestion. I tried both `pyinstaller -F train.py` and `pyinstaller -F train.py --log-level DEBUG`, both works fine now. But I do encountered the problem described above for days. LOL
Now I encounter a new problem when excuting the excutable of pyinstaller. Another problem to search and learn. Any suggestions ? ^_^. Thanks 
```
Exception in thread Thread-2:
Traceback (most recent call last):
  File "threading.py", line 932, in _bootstrap_inner
  File "threading.py", line 870, in run
  File "train.py", line 443, in runs
    raise e
  File "train.py", line 441, in runs
    train(GlobalVar['train'], GlobalVar['test'])
  File "train.py", line 561, in train
    run(hyp, opt, device, tb_writer)
  File "train.py", line 323, in run
    results, maps, times = test(opt['data'],
  File "tester.py", line 120, in test
    output = non_max_suppression(inf_out, conf_thres=conf_thres, iou_thres=iou_thres, merge=merge)
  File "utils/general.py", line 657, in non_max_suppression
    i = torchvision.ops.boxes.nms(boxes, scores, iou_thres)
  File "torchvision/ops/boxes.py", line 40, in nms
  File "torch/_ops.py", line 61, in __getattr__
RuntimeError: No such operator torchvision::nms
```

**Comment by rokm** [comment]
Could be a problem with yolov5 codebase itself (see [this](https://github.com/pytorch/vision/issues/1405) and [this](https://github.com/ultralytics/yolov5/issues/1272)). 

On the other hand, it's equally likely that some (sub)modules are not collected by PyInstaller. In which case, you'll either need to identify the missing modules yourself and add them to `hiddenimports` in your .spec file (or write custom hooks), or use `collect_submodules` to try to collect all submodules automatically.

E.g. at the top of the .spec file, add
```python
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('torch')
hiddenimports += collect_submodules('torchvision')
```
and then pass `hiddenimports` to `Analysis`.
