### ISSUE TITLE
Compile pickled sklearn model to EXE file but it requires sklearn module 

### ISSUE THREAD

**Issue by Polarbear1026** [pyinstaller/pyinstaller#5342]
I'm using pickle to load voting regressor model so I don't want to import pandas, sklearn at all (to minimize file size)
When I run my code at Spyder, it works well.

The problem is when I warpped my code to EXE using pyinstaller and execute EXE file, it occurred error below

**Traceback (most recent call last) : File "test.py", Line 92, in ModuleNotFoundError : No module named 'sklearn' [11316] Failed to execute script test**

I thought my pickled model file included sklearn, but seems it's not and didn't work when EXE file form.

Is there any way to execute file without importing sklearn module? file size is 18.5mb now, but if import sklearn, file size will be 150~250mb. I don't want to make my file so huge...

OS: Win10
Python: 3.7.4 
Numpy: 1.19.2 
Pandas: 1.1.0
pyinstaller: 4.1 

My Code 

`

    import PySimpleGUI as sg
    import pickle
    import sys, os
    import math    
    sys.setrecursionlimit(5000)

    title = 'Calculation'
    sg.theme('Default')

    def start_menu () :
        start_layout = [ [sg.Text('Input your data',size =(30,2), font=20)],
                 [sg.Text('Input 1', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))],     # 0
                 [sg.Text('Input 2', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))],     # 1 log1p
                 [sg.Text('Input 3', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))],          # 2
                 [sg.Text('Input 4', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))],  # 3
                 [sg.Text('Input 5', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 4
                 [sg.Text('Input 6', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 5 log1p
                 [sg.Text('Input 7', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 6 
                 [sg.Text('Input 8', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 7 
                 [sg.Text('Input 9', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 8 log1p
                 [sg.Text('Input 10', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 9
                 [sg.Text('Input 11', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 10 log1p
                 [sg.Text('Input 12', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 11 log1p
                 [sg.Text('Input 13', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))],  # 12
                 [sg.Text('Input 14', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 13
                 [sg.Text('Input 15', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))], # 14 log1p          
                 [sg.Text('Input 16', size=(24,1)), sg.InputText(size=(10,1),pad=(40,10))],  # 15
                 [sg.Button('Confirm')] ]
    window = sg.Window(title, start_layout)
    event, value = window.read()
    window.close()
    return event, value 

    def result_menu (pred_value) : 
    
         result_layout = [[sg.Text('Prediction Value is '+str(pred_value), size=(30,2))],
                         [sg.Button('ReCalculation')],
                         [sg.Button('End')] ]
     window2 = sg.Window(title, result_layout)
     event, value = window2.read()
     window2.close()
     return event, value 
                
    skew = [1, 5, 8, 10, 11, 14]
     
    while True :  
        while True :
        
            event, values = start_menu()
        
            num = 1
    
            for i in range(16) :
                if values[i] == '' :
                     sg.popup_timed('Check your input', auto_close_duration=5)
                    num = 0 
                    break 
            
            if num == 1 : break # go to Calculation
        
        if event == sg.WIN_CLOSED : break 
        val = []
        for i in values.values() :
            val.append(float(i))
        
    # loading Data / Model
    
    def resource_path(relative_path) :
        if hasattr(sys, '_MEIPASS') :
            return os.path.join(sys._MEIPASS, relative_path)
        return os.path.join(os.path.abspath("."), relative_path)
    
    if __name__ == "__main__" :
        model_file = resource_path('vt_model.pkl') # Voting Regresson
        table_file = resource_path('table.pkl')    # DataFrame (for Prediction)
        scaler_file = resource_path('scaler.pkl')  # Minmax scaler
    
    model = pickle.load(open(model_file, 'rb'))
    table = pickle.load(open(table_file, 'rb'))
    scaler = pickle.load(open(scaler_file, 'rb'))
    
    # DataFrame /  log1p 
    for i,j in enumerate(table.columns) :
        if i in skew : table[j] = math.log(val[i] + 1)
        else : table[j] = val[i]
    
    # MinMax 
    scale_table = scaler.transform(table)
    for i,j in enumerate(table.columns) : 
        table[j] = scale_table[0][i]
    
    # Predict
    sg.popup_timed('   Predict...   ' , '                       ', auto_close_duration=2, button_type=5)
    pred_value = model.predict(table)
    pred_value = int(pred_value.round(0))  # np.round
    
    event, values2 = result_menu(pred_value) 
    if event == sg.WIN_CLOSED or event in ('End') : break
`

**Comment by rokm** [comment]
> I'm using pickle to load voting regressor model so I don't want to import pandas, sklearn at all (to minimize file size)

When you unpickle your regressor model, `sklearn` is implicitly imported, because pickling serializes only object's data, and not its code. 

When you freeze your script, PyInstaller sees no references to `sklearn`, and therefore does not collect any `sklearn` modules, leading to the error when you run the exe. So you will need to add `sklearn` (or rather, the `sklearn` subpackage in which the model resides) to `hiddenimports`. 

Otherwise, you're creating a situation similar to pickling the model on your computer and then trying to unpickle it on another computer without `sklearn` installed, which will not work, either...

**Comment by Polarbear1026** [comment]
> > I'm using pickle to load voting regressor model so I don't want to import pandas, sklearn at all (to minimize file size)
> 
> When you unpickle your regressor model, `sklearn` is implicitly imported, because pickling serializes only object's data, and not its code.
> 
> When you freeze your script, PyInstaller sees no references to `sklearn`, and therefore does not collect any `sklearn` modules, leading to the error when you run the exe. So you will need to add `sklearn` (or rather, the `sklearn` subpackage in which the model resides) to `hiddenimports`.
> 
> Otherwise, you're creating a situation similar to pickling the model on your computer and then trying to unpickle it on another computer without `sklearn` installed, which will not work, either...

So sad that I have to import sklearn to make exe file..  thanks anyway.

**Comment by mesuga-reymond** [comment]
Hi @rokm, i am running with the same issue. I already imported `sklearn` in my `main.py` file but the `model.pkl` file still can't be read by `pyinstaller`. Also, during the creation of installler, i didn't observed any error.

Here is the error that i'm getting when i run the executable file using `./app` (i'm using ubuntu linux, btw):

`FileNotFoundError: [Errno 2] No such file or directory: 'model.pkl'
[92462] Failed to execute script 'app' due to unhandled exception!`

**Comment by mesuga-reymond** [comment]
Hi @Polarbear1026, are you able to solve the issue?

**Comment by max0tt0** [comment]
Hi guys! I have the same problem. Has anyone found a solution? Import sklearn does not help ...

**Comment by max0tt0** [comment]
I solved the problem. For example, for a model of random forest, you need to add --hidden-import "sklearn.ensemble". Because the module is used
`from sklearn.ensemble import RandomForestClassifier`
