### ISSUE TITLE
Linux shared library instead of application

### ISSUE THREAD

**Issue by Axel-Erfurt** [pyinstaller/pyinstaller#5344]
Mint 20 (Ubuntu 20.04)
Python 3.8.5

pyinstaller 3.6 creates an application

pyinstaller 4.x creates a shared library

Is there an explanation?

**Comment by rokm** [comment]
Are you referring to the type reported in the ELF headers, as reported by `readelf`?

E.g.,
`  Type:                              EXEC (Executable file)` (built with pyinstaller 4.0)
vs
`  Type:                              DYN (Shared object file)` (built with pyinstaller 4.1)

In that case, the difference is that the bootloaders in 4.1 were apparently built with PIE enabled:
`dist40/program/program: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=4485007e1df54173663f148d5840c963a7e868ee, stripped`
vs.
`dist41/program/program: ELF 64-bit LSB pie executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=3507aa01d32c34dc8e8c6462b764adb90a82768d, stripped`

**Comment by Axel-Erfurt** [comment]
Thanks for the explanation.

**Comment by Roy027** [comment]
How to use pyinstaller to make executable instead of shared library?

**Comment by Dlitosh** [comment]
> How to use pyinstaller to make executable instead of shared library?

I'd like to know that as well.

**Comment by bwoodsend** [comment]
Again, it's already an executable rather than a shared library. You're desktop needs to be updated to recognise it as such.

**Comment by Axel-Erfurt** [comment]
Many file managers in Linux show it as a shared library.
This means that it cannot be started with a double click.
You can run it in the terminal.
