### ISSUE TITLE
Frozen application FAILS on numpy sanity check - When Distributed to other PCs

### ISSUE THREAD

**Issue by roninpawn** [pyinstaller/pyinstaller#5345]
Doesn't look like this is in the 'Issues' yet, so a quick heads up to PyInstaller users.
```
RuntimeError: The current Numpy installation [...] fails to pass a sanity check due to a bug in the windows runtime.
```

Numpy, Microsft, and MS Visual Studio aren't seeing eye to eye right now on how the process fmod() is meant to work. In October, 2020, Microsoft pushed an OS update (I think) that fixed one thing and broke another thing worse than the thing it fixed... You know -- a typical Microsoft update.

See: https://developercommunity.visualstudio.com/content/problem/1207405/fmod-after-an-update-to-windows-2004-is-causing-a.html?childToView=1243113#comment-1243113 for more details.

They don't expect to fix it until January 2021... making it a VERY typical windows update. Anyway, PyInstaller will carry over these issues when it freezes your application for distribution. What works fine on YOUR Windows 10 system, may or may not manage to get passed the 'import numpy' line in your script on someone else's.

At this point in time, the simple solution seems to be to roll back your Numpy library to 1.19.3.
```
pip uninstall numpy

pip install numpy==1.19.3
```

I pushed my first PyInstaller 'compiled' Release in ages to github yesterday - working fine on my system with numpy 1.19.4 installed - only to find out from the first user to download it, that it crashed as quickly as they could double-click the executable. So, be aware! Microsoft... is still Microsoft. And you can't just trust that this 50-years-making-the-same-operating-system company's low-level processes will - ya know - FUNCTION across updates.

**Comment by bwoodsend** [comment]
Hmm great. Just what I want to hear...

Well thanks for pointing that out to us. I see [here](https://developercommunity.visualstudio.com/comments/1244066/view.html) it says we can't just collect and ship a working copy of the offending DLL (`ucrtbase.dll`). So I guess there's really not much PyInstaller can do but warn users.

**Comment by maubreville** [comment]
Thanks for providing the workaround. Have this issue as well.

**Comment by rokm** [comment]
Closing this as underlying issue seems to have been fixed in KB4598291 (and has also been worked around in numpy 1.19.5).
