### ISSUE TITLE
matplotlib saving figures

### ISSUE THREAD

**Issue by R0lls** [pyinstaller/pyinstaller#5356]
I have a py script using matplotlib. This script takes as user-input a filename and saves a plot as png into a pre-defined target directory. When packaging this script by using pyinstaller, a png file gets already created with filename ".png.png" in the target dir.

When running the exe, the query for the filename works fine, but a png file is not created at all.

No error messages during building the exe or while running it.

Help is much appreciated. I'm not a s/w engineer, please excuse if I've overseen something obvious. Many Thanks!

## Context information (for bug reports)
* Output of `pyinstaller --version`: ```4.1```
* Version of Python: 3.7.4
*Version of matplotlib: 3.3.2
* Platform: Windows 10 Pro (German),
* Didn't try on any other platform

### A minimal example program which shows the error
import matplotlib.pyplot as plt
x= input ("filename: ")
print ("Thats the filename: ",x)
labels = ['G1', 'G2', 'G3', 'G4', 'G5']
men_means = [20, 35, 30, 35, 27]
women_means = [25, 32, 34, 20, 25]
fig, ax = plt.subplots()
ax.bar(labels, men_means, width=0.35, label='Men')
ax.bar(labels, women_means, width=0.35, bottom=men_means,label='Women')
plt.savefig("C:\\Users\\User1\\Desktop\\"+x+".png")

**Comment by bwoodsend** [comment]
Are you using Anaconda?

**Comment by R0lls** [comment]
yes, I am using Anaconda. Version is custom.

**Comment by rokm** [comment]
In that case, the program could be silently crashing somewhere after the `print()` statement (and before `savefig()`) due to missing `libiomp5md` - see https://github.com/pyinstaller/pyinstaller/issues/4968#issuecomment-662075970

**Comment by R0lls** [comment]
@rokm is right. the program silently crashes after the print() statement prior completing savefig(). Adding the missed _libiomp5md_ as described in #4968 fixes it.

Many thanks, much appreciated!!
