### ISSUE TITLE
libjpeg-ba7bf5af.so.9.4.0

### ISSUE THREAD

**Issue by busrakb** [pyinstaller/pyinstaller#5366]
I toke this error . How i will solve i dont know. Can you help me,please? 

File "/tmp/_MEITv8xDk/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: libjpeg-ba7bf5af.so.9.4.0: cannot open shared object file: No such file or directory
[24209] Failed to execute script main

**Comment by rokm** [comment]
Please fill in the issue template. Or at least, provide the full stack trace.

**Comment by Joshuaj2804** [comment]
Having the same issue here, very very confused as to where I went wrong

**Comment by bwoodsend** [comment]
@Joshuaj2804 You can fill in the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md). We can't help either of you based on one line of stacktrace.

**Comment by thinksmart88** [comment]
Leaving this comment here in case someone else runs into a similar issue. The files in folder Pillow.libs libjpeg-ba7bf5af.so.9.4.0 are located outside of PIL folder in site-package. So if you are like me and ran into this issue by blindly copying only the PIL folder from site-packages, make sure you copy Pillow.libs as well
