### ISSUE TITLE
Pyinstall installation error

### ISSUE THREAD

**Issue by Someone-Of-Liu** [pyinstaller/pyinstaller#5367]
When I execute pip install pyinstaller, an error occurs when the file is downloaded and ready to install, and this error only appears on pyinstaller. This error message cannot be found on the Internet. Whether it is offline or online installation will report an error. But when the OS update to the Windows10, it can work normally. However, I need Windows8, because my compute's configuration is very low. 
![Snipaste_2020-12-05_11-37-23](https://user-images.githubusercontent.com/69884931/101232726-5c161700-36ee-11eb-9671-2ff73f5d6939.png)
![Snipaste_2020-12-05_11-37-32](https://user-images.githubusercontent.com/69884931/101232731-689a6f80-36ee-11eb-9cff-90cc77f3e086.png)

What should I do?

Python version: 3.8.6
OS: Windows8.1 x32 for Chinese
Pip version: 20.3.1
The pyinstaller version: ALL

**Comment by Someone-Of-Liu** [comment]
HELP!!!

**Comment by rokm** [comment]
Does this happen only when you try to install `pyinstaller`, or for other packages as well?

The most obvious candidate for triggering the error are non-ASCII characters in your username - can you try creating a new user name using only ASCII characters?

**Comment by Someone-Of-Liu** [comment]
Sorry, I only reply to the email now. Because I need go to school from Monday to Friday. And I only can come back on Friday. So I don’t have time to reply you. Sorry...

I created a user named John and can install Pyinstaller now. I will rename my Microsoft account to Zhijun Liu.  Then it should be ready for normal use.  But it seems that the user folder name on the disk does not change.  However, I will find a way.

Thank you very much. This problem has bothered me for a long time.

Goodbye.

Send from my iPad

在 2020年12月6日，上午4:29，Rok Mandeljc <notifications@github.com> 写道：

﻿

Does this happen only when you try to install pyinstaller, or for other packages as well?

The most obvious candidate for triggering the error are non-ASCII characters in your username - can you try creating a new user name using only ASCII characters?

**Comment by Someone-Of-Liu** [comment]
Should I close it after the problem is resolved?

**Comment by rokm** [comment]
> emmm. Should I close it after the problem is resolved?

Yes, please.
