### ISSUE TITLE
Exception: Python.Runtime not found

### ISSUE THREAD

**Issue by yurma29** [pyinstaller/pyinstaller#5369]
Please, someone can help to fix this problem?
Python version: 3.7.3
Windows 7  
 File "d:\anaconda\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-clr.py", line 40, in <module>
    raise Exception(pyruntime + ' not found')
Exception: Python.Runtime not found

**Comment by rokm** [comment]
`Python.Runtime.dll` should be located in your environment's `site-packages` (along with `clr.pyd` and `pythonnet-X.Y.Z.dist-info` directory). So either you do not have `pythonnet` properly installed in you environment, or you are using wrong environment (e.g., you created a conda environment and installed `pythonnet` into it, but you are running `pyinstaller` from conda's base environment).
