### ISSUE TITLE
Import problem with contextlib.asynccontextmanager

### ISSUE THREAD

**Issue by rappongy** [pyinstaller/pyinstaller#5371]
Hi! Facing a problem with importing `asynccontextmanager` from `contextlib`.

### Context

pyinstaller --version: 4.1
Python 3.9
Windows 10

### example:

I've created hook.

```py
# installer/extra-hooks/

from PyInstaller.utils.hooks import collect_data_files

datas = collect_data_files('contextlib', include_py_files=True)
```

It works well in `one-dir` mode. But in `one-file` mode I am facing `ImportError: cannot import name \'asynccontextmanager\'`

So, this works:

```cmd
pyinstaller -y --clean --additional-hooks-dir installer/extra-hooks app/main.py
```

But not this:

```cmd
pyinstaller -y -F --clean --additional-hooks-dir installer/extra-hooks app/main.py
```

Can you give me any hint please?

**Comment by rokm** [comment]
Could you please provide a minimal example that triggers this error?
