### ISSUE TITLE
Couldn't find python39.dll

### ISSUE THREAD

**Issue by mathstar13** [pyinstaller/pyinstaller#5372]
Pyinstaller Version: 4.1
Version of Python: 3.9.0
Platform: Windows 10 English
No, I did not try this on another platform.

### A minimal example program which shows the error

```python
print('Hello World')
input('')
```

### Stacktrace / full error message

```
Error loading Python DLL 'C:\Users\myname\Documents\Me\Python\build\Hello_World\python39.dll'.
LoadLibrary: The specified module could not be found.
```

**Comment by rokm** [comment]
> Error loading Python DLL 'C:\Users\myname\Documents\Me\Python\build\Hello_World\python39.dll'.

According to the above path you are trying to run the executable in the `build` directory instead of the one in the `dist` directory.

**Comment by mathstar13** [comment]
That was the problem! Thank you!
