### ISSUE TITLE
AUTH_USER_MODEL refers to model 'Sistema.User' that has not been installed - Django

### ISSUE THREAD

**Issue by marcelodelta** [pyinstaller/pyinstaller#5375]
AUTH_USER_MODEL refers to model 'Sistema.User' that has not been installed with Pyinstaller

I'm using a custom User to add fields to this model.

However, I was unable to solve the problem with pyinstaller.

Could anyone help?

Very grateful for the attention.

server@srvr:~/app$ ./dist/sistema
Traceback (most recent call last):
  File "django/apps/config.py", line 178, in get_model
KeyError: 'user'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "django/contrib/auth/__init__.py", line 157, in get_user_model
  File "django/apps/registry.py", line 211, in get_model
  File "django/apps/config.py", line 180, in get_model
LookupError: App 'Sistema' doesn't have a 'User' model.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "manage.py", line 21, in <module>
  File "manage.py", line 17, in main
  File "django/core/management/__init__.py", line 401, in execute_from_command_line
  File "django/core/management/__init__.py", line 377, in execute
  File "django/__init__.py", line 24, in setup
  File "django/apps/registry.py", line 122, in populate
  File "django/contrib/auth/apps.py", line 22, in ready
  File "django/contrib/auth/__init__.py", line 161, in get_user_model
django.core.exceptions.ImproperlyConfigured: AUTH_USER_MODEL refers to model 'Sistema.User' that has not been installed
[694099] Failed to execute script manage

**Comment by bwoodsend** [comment]
Can you tell us what this 'Sistema.User' thing is? You'll just need to tell PyInstaller to include it. If it's a Python library you just need to `--hiddenimport=Sistema.User`. If it's some kind of data file you'll need `--add-data` etc.

**Comment by marcelodelta** [comment]
hi.

Does not Work

pyi-makespec -F --additional-hooks-dir pyinstaller_hooks --name=rastreabilidade --hidden-import rest_framework.apps --hidden-import corsheaders --hidden-import Sistema --hidden-import Sistema.apps --hidden-import Sistema.User --key test serverapp/manage.py && pyinstaller rastreabilidade.spec

=(

**Comment by bwoodsend** [comment]
> Can you tell us what this 'Sistema.User' thing is?

**Comment by marcelodelta** [comment]
I had to customize Django's default User model.

I needed to add some other fields in this User model.

**Comment by Legorooj** [comment]
Can you provide us with your project tree?

**Comment by marcelodelta** [comment]
INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'rest_framework',
    'corsheaders',

    'Sistema.apps.SistemaConfig',
]


AUTH_USER_MODEL = 'Sistema.User'

**Comment by bwoodsend** [comment]
Ah no, @Legorooj means what files do you have in your project. The output of `ls -R` from the root of your project would be sufficient.

**Comment by marcelodelta** [comment]
Diretório: C:\Users\Ricardo\projetos\aplication_serverapp


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        30/11/2020     23:13                .vscode
d-----        30/11/2020     22:47                Sistema
d-----        19/11/2020     02:07                aplication
d-----        27/10/2020     19:43                templates
-a----        30/01/2020     10:36            627 manage.py
-a----        19/08/2020     16:46             18 README.md
-a----        30/11/2020     23:25            413 requirements.txt
-a----        01/12/2020     14:42             60 workspace.code-workspace


    Diretório: C:\Users\Ricardo\projetos\aplication_serverapp\Sistema


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        27/10/2020     21:57                fixtures
d-----        12/12/2020     22:27                migrations
d-----        15/12/2020     16:01                __pycache__
-a----        30/01/2020     10:36             63 admin.py
-a----        30/01/2020     10:36             89 apps.py
-a----        14/12/2020     21:12           5724 models.py
-a----        14/12/2020     03:26          34885 serializers.py
-a----        30/01/2020     10:36             60 tests.py
-a----        15/12/2020     03:00           7215 urls.py
-a----        15/12/2020     16:01          48429 views.py
-a----        30/01/2020     10:36              0 __init__.py


    Diretório: C:\Users\Ricardo\projetos\aplication_serverapp\Sistema\fixtures


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        29/06/2020     23:36            889 01_estoqueTipoMovimento.json
-a----        30/06/2020     00:17            195 02_estoquePredio.json
-a----        23/06/2020     01:28            547 group.json
-a----        29/06/2020     00:16            675 user.json


    Diretório: C:\Users\Ricardo\projetos\aplication_serverapp\Sistema\migrations


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        12/12/2020     22:27                __pycache__
-a----        14/07/2020     16:56           6930 0001_initial.py
-a----        15/07/2020     01:49            474 0002_produto_token.py
-a----        06/09/2020     10:49            985 0003_auto_20200906_1049.py
-a----        06/09/2020     11:17            567 0004_auto_20200906_1117.py
-a----        12/10/2020     22:24            674 0005_auto_20201012_2224.py
-a----        14/10/2020     21:41           1341 0006_estoque.py
-a----        14/10/2020     22:38            447 0007_produto_estoque.py
-a----        31/10/2020     12:59            327 0008_remove_produto_estoque.py
-a----        07/11/2020     15:32            730 0009_estoquesilo.py
-a----        07/11/2020     16:43            652 0010_auto_20201107_1643.py
-a----        07/11/2020     17:28            373 0011_auto_20201107_1728.py
-a----        13/11/2020     00:29            414 0012_auto_20201113_0029.py
-a----        14/11/2020     16:06           1859 0013_auto_20201114_1606.py
-a----        23/11/2020     17:00            786 0014_producao.py
-a----        23/11/2020     20:39            423 0015_producao_nome.py
-a----        02/12/2020     20:31            931 0016_auto_20201202_2031.py
-a----        12/12/2020     22:27            342 0017_remove_producao_quantidadeproducao.py
-a----        30/01/2020     10:36              0 __init__.py


    Diretório: C:\Users\Ricardo\projetos\aplication_serverapp\aplication


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----        10/12/2020     14:27                __pycache__
-a----        30/01/2020     10:36            391 asgi.py
-a----        23/07/2020     20:26            748 celery.py
-a----        10/12/2020     14:26           6884 settings.py
-a----        25/06/2020     12:12           1342 urls.py
-a----        30/01/2020     10:36            391 wsgi.py
-a----        30/01/2020     10:36              0 __init__.py

**Comment by marcelodelta** [comment]
Resolved with 

from django.contrib.auth.models             import User

In __init__.py


Now another problem is shown.

django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
[81514] Failed to execute script manage

**Comment by Legorooj** [comment]
Can you provide us with your file tree?
