### ISSUE TITLE
Create native arm64 build on Apple Silicon

### ISSUE THREAD

**Issue by Durgaprasad-kelkar** [pyinstaller/pyinstaller#5376]
Setup
1. Apple silicon machine (DTK)
2. Mac OS Big Sur (11.0.1)
3. Python 3.8.2
4. Pyinstaller 4.1 (Installed from source. Also did `python ./waf all`)

Created a simple test.py and added `print ("hi")`
Then `pyinstaller test.py`
Architecture of binary create is x86_64 not arm64. Used `lipo -info dist/test/test"` to check the arch.

Can we add support to create native arm64 binary. 

Secondly I tried same steps using Python 2.7.18 and Pyinstaller 3.6. It also creates x86_64 binary, but that binary do not print the message. It simply exit. Would it be possible to add support for `arm64` in `Pyinstaller=3.6` as well.

**Comment by bwoodsend** [comment]
Even if you changed the `waf` to build an `arm64` bootloader, everything else would still be whatever architecture your Python and libraries are. The bootloader does very little itself - just points various components of your app to each other - so any performance gain would be insignificant.

> Would it be possible to add support for arm64 in Pyinstaller=3.6 as well.

Not a chance. Have you seen the state of our issue board lately?
