### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.sip' 

### ISSUE THREAD

**Issue by leileigong** [pyinstaller/pyinstaller#5381]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.1```
* Version of Python: Python 3.6.6
* Platform: Linux raspberrypi 4.14.50-v7+ #1122 SMP Tue Jun 19 12:26:26 BST 2018 armv7l GNU/Linux

* Did you also try this on another platform? Does it work there?
yes.i try the project on windows with same python version and pyinstaller version.
some log as follows.
```
142 INFO: PyInstaller: 4.1
142 INFO: Python: 3.6.6
143 INFO: Platform: Windows-10-10.0.17134-SP0
....
```

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Stacktrace / full error message

```
647 INFO: PyInstaller: 4.1
648 INFO: Python: 3.6.6
665 INFO: Platform: Linux-4.14.50-v7+-armv7l-with-debian-9.4
671 INFO: wrote /home/pi/code/FNTools/FN70PDownloadTool-armv7l-20201211.spec
687 INFO: UPX is not available.
696 INFO: Removing temporary files and cleaning cache in /root/.cache/pyinstaller
715 INFO: Extending PYTHONPATH with paths
['/home/pi/code/FNTools/apps/FN70P/FN70PFWDL', '/home/pi/code/FNTools']
794 INFO: checking Analysis
795 INFO: Building Analysis because Analysis-00.toc is non existent
796 INFO: Initializing module dependency graph...
811 INFO: Caching module graph hooks...
968 INFO: Analyzing base_library.zip ...
59823 INFO: Caching module dependency graph...
61461 INFO: running Analysis Analysis-00.toc
61691 INFO: Analyzing /home/pi/code/FNTools/apps/FN70P/FN70PFWDL/FN70PDownloadTool.py
93725 INFO: Processing module hooks...
93733 INFO: Loading module hook 'hook-usb.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
94233 INFO: Loading module hook 'hook-Crypto.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
94323 INFO: Loading module hook 'hook-pickle.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
94358 INFO: Excluding import of argparse from module pickle
94361 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
95290 INFO: Loading module hook 'hook-encodings.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
96104 INFO: Loading module hook 'hook-xml.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100680 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100687 INFO: Loading module hook 'hook-PyQt5.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100692 INFO: Loading module hook 'hook-PyQt5.Qt.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100727 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100733 INFO: Loading module hook 'hook-heapq.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100761 INFO: Excluding import of doctest from module heapq
100763 INFO: Loading module hook 'hook-difflib.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100793 INFO: Excluding import of doctest from module difflib
100795 INFO: Loading module hook 'hook-PyQt5.QtOpenGL.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100801 INFO: Loading module hook 'hook-PyQt5.QtTest.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100805 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100821 INFO: Import to be excluded not found: 'test'
100835 INFO: Loading module hook 'hook-PyQt5.QtNetwork.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100842 INFO: Loading module hook 'hook-PyQt5.QtSql.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100846 INFO: Loading module hook 'hook-PyQt5.QtPrintSupport.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
100851 INFO: Loading module hook 'hook-PyQt5.QtXml.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...
101209 INFO: Looking for ctypes DLLs
101848 WARNING: library Advapi32 required via ctypes not found
102010 WARNING: library Cfgmgr32 required via ctypes not found
102173 WARNING: library setupapi required via ctypes not found
102234 WARNING: Ignoring /System/Library/Frameworks/IOKit.framework/IOKit imported from /home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/serial/tools/list_ports_osx.py - ctypes imports are only supported using bare filenames
102235 WARNING: Ignoring /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation imported from /home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/serial/tools/list_ports_osx.py - ctypes imports are only supported using bare filenames
103079 INFO: Analyzing run-time hooks ...
103157 INFO: Including run-time hook '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
103217 INFO: Including run-time hook '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_usb.py'
103276 INFO: Including run-time hook '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
103434 INFO: Looking for dynamic libraries
110637 INFO: Looking for eggs
110638 INFO: Using Python library /usr/lib/arm-linux-gnueabihf/libpython3.6m.so.1.0
110707 INFO: Warnings written to /home/pi/code/FNTools/build/FN70PDownloadTool-armv7l-20201211/warn-FN70PDownloadTool-armv7l-20201211.txt
111533 INFO: Graph cross-reference written to /home/pi/code/FNTools/build/FN70PDownloadTool-armv7l-20201211/xref-FN70PDownloadTool-armv7l-20201211.html
111797 INFO: checking PYZ
111798 INFO: Building PYZ because PYZ-00.toc is non existent
111799 INFO: Building PYZ (ZlibArchive) /home/pi/code/FNTools/build/FN70PDownloadTool-armv7l-20201211/PYZ-00.pyz
120463 INFO: Building PYZ (ZlibArchive) /home/pi/code/FNTools/build/FN70PDownloadTool-armv7l-20201211/PYZ-00.pyz completed successfully.
120634 INFO: checking PKG
120635 INFO: Building PKG because PKG-00.toc is non existent
120636 INFO: Building PKG (CArchive) PKG-00.pkg
120851 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
120865 INFO: Bootloader /home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-32bit-arm/run
120865 INFO: checking EXE
120866 INFO: Building EXE because EXE-00.toc is non existent
120867 INFO: Building EXE from EXE-00.toc
120873 INFO: Appending archive to ELF section in EXE /home/pi/code/FNTools/build/FN70PDownloadTool-armv7l-20201211/FN70PDownloadTool-armv7l-20201211
120933 INFO: Building EXE from EXE-00.toc completed successfully.
120952 INFO: checking COLLECT
120952 INFO: Building COLLECT because COLLECT-00.toc is non existent
120954 INFO: Building COLLECT COLLECT-00.toc
125920 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
You've provided a build log - not the runtime stack trace. Can we have the output of running the built application instead? Also your PyQt5 version?

The go-to fix for `ModuleNotFoundError` is `--hiddenimport=PyQt5.sip`. Did you try that? If it doesn't work then can you confirm that `python -c "from PyQt5 import sip"` does work and using `python -m PyInstaller` instead of just `pyinstaller` has no effect?

**Comment by leileigong** [comment]
@bwoodsend hi bwoodsend ,
i tried `python -c "from PyQt5 import sip"`, it does work.
then i tried `--hidden-import=PyQt5.sip`  built application ,the app can run correctly.
But i know application built by **Pyinstaller3.4**  works fine although i do not use `--hidden-import=PyQt5.sip`.
So i do not sure it's a bug of **Pyinstaller4.1** or not.

**Comment by bwoodsend** [comment]
Yeah that's a bug, albeit a simple one.

**Comment by bwoodsend** [comment]
Actually this is stranger than it looks because the following hook:

https://github.com/pyinstaller/pyinstaller/blob/f9eeaaf9c09ce72cab20165a21dd454be2178c50/PyInstaller/hooks/hook-PyQt5.py#L13-L23

already adds `PyQt5.sip` as a hidden import and I can see from the build log:

> 100687 INFO: Loading module hook 'hook-PyQt5.py' from '/home/pi/code/FNTools/PIPENV_VENV_IN_PROJECT/FNTools-g0ZG0lN2/lib/python3.6/site-packages/PyInstaller/hooks'...

that this hook is being ran.

Could you run the above snippet in a Python console and tell me if the contents of that `if` statement are being ran?

**Comment by leileigong** [comment]
@bwoodsend i run  the above snippet in a Python console, the `pyqt5_library_info.version` get an empty list `[]`, so the ` if `statement are not being ran.

**Comment by bwoodsend** [comment]
Hmm, Ok, digging deeper...

The following block of code is responsible for getting that `pyqt5_library_info.version` list:

https://github.com/pyinstaller/pyinstaller/blob/f9eeaaf9c09ce72cab20165a21dd454be2178c50/PyInstaller/utils/hooks/qt.py#L63-L83

Presumably, that `except AttributeError:` is being tripped to give you a `version = []`.

```python
 try: 
     version = QLibraryInfo.version().segments() 
 except AttributeError: 
     version = [] 
```

If that is the case, are you able to find anything else we can use to get the version?

**Comment by leileigong** [comment]
Pyinstaller3.6 works fine with pyqt5, how does the Pyinstaller3.6 get the pyqt5 version?

**Comment by rokm** [comment]
What do you get if you run the following snippet?
```python
from PyQt5.QtCore import QLibraryInfo
print(QLibraryInfo.version())
print(QLibraryInfo.version().segments())
```

For that matter, what version of PyQt5 are you using, and how did you install it on your raspberry pi?

The earlier versions of PyInstaller retrieved the PyQt5 version in the same way, but older hooks (e.g., in PyInstaller 3.4) did not validate it (e.g., hook from [PyInstaller 3.4](https://github.com/pyinstaller/pyinstaller/blob/v3.4/PyInstaller/hooks/hook-PyQt5.py) vs. the one from [PyInstaller 4.1](https://github.com/pyinstaller/pyinstaller/blob/v4.1/PyInstaller/hooks/hook-PyQt5.py)).

**Comment by leileigong** [comment]
```
pi@raspberrypi:~ $ python3
Python 3.6.6 (default, Feb 26 2020, 12:38:37)
[GCC 6.3.0 20170516] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtCore import QLibraryInfo
print(QLibraryInfo.version())
print(QLibraryInfo.version().segments())>>> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'QLibraryInfo' has no attribute 'version'
>>>
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: type object 'QLibraryInfo' has no attribute 'version'
>>>
>>> exit()
```

my PyQt5 version is `5.13.2`, i install it from source code.

**Comment by rokm** [comment]
> my PyQt5 version is 5.13.2, i install it from source code.

Ah, alright, this is starting to make sense now. I assume your PyQt5 is built against the system version of Qt5, which is probably older than 5.8, in which the `QLibraryInfo::Version()` was added.

Which means that in order to support these old Qt5 versions, we'll need to change those `if pyqt5_library_info.version` checks to explicitly check for `None` instead of falsy-ness, as empty list indicates that the library is available but its version information is not.

**Comment by anla-xu** [comment]
@bwoodsend I encountered the same problem, python 3.6.9 pyinstaller 4.10, pyqt5.15.5, python3 -c "import PyQt5.sip" can work normally, but after packaging it can't find PyQt5.sip, print out hook-PyQt5.py file The pyqt5_library_info.version is [5,12,10], is there any way to deal with it, thank you

**Comment by Legorooj** [comment]
PyInstaller 4.10 is out of date. Please try with the latest version of PyInstaller, and open an issue if the problem still occurs.
