### ISSUE TITLE
can't automatic add   torchvision   to my .exe package

### ISSUE THREAD

**Issue by mishi321** [pyinstaller/pyinstaller#5386]
I try to use pyinstaller to package a absolute python project to run with exe
The project `pytorch --version: 1.7.0, torchvision --version: 0.8.1`
The quote code is `from torchvision.ops import nms`
Finally i finish the `pyinstaller -D` try to run my exe
Throw the torchvision ERROR: `RuntimeError: couldn't load costom C++ ops ....this can happen if your pytorch and torchvison versions are incompatible...`
But i run it in vscode environment is successful
Then i copy the torchvison  `user\programs\python\python38\lib\site-packages\torchvision\` to the pyinstaller generate `\dist\ ` 
It work normally, so I think it may be a bug

**Comment by rokm** [comment]
PyInstaller is failing to pick up `_C` extension module from `torchvision`, hence the error. Does adding `--hidden-import torchvision._C` to `pyinstaller` command solve the error for you? 

Or are we failing to pick up other modules as well, resulting in a different error...?
