### ISSUE TITLE
Possible Bug?  Pyinstaller generates error when installed as a windows service.

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#539]
**Original date**: 2012/03/27
**Original reporter**: *Kyle DOT Flavin "AT" gmail DOT  COOM *

- My issue occurs when running the application.  The exe builds fine.
- Python 2.6.6
- Pyinstaller 1.5.1
- win32traceutil.py captuers the error; it's part of the pywin32 libraries (pywin32.sourceforge.ne)
- Occurs on: Windows XP (looking for another windows version to test on)

I am attempting to make a python windows service using the pywin32 libraries.  The service works when I install it using pywin32's PythonService.exe.  It also seems to work (at least on the surface) when I make an exe using pyinstaller.

When using pyinstaller, I'm able to install and start my service without an issue.  When I shut down the service, the application appears to stop as well.  However, I get a strange error on the console (using win32's win32traceutil.py), as follows:

"Exception KeyError: KeyError(2244,) in <module 'threading' from '2\build\pyi.win32\agentservice\outPYZ1.pyz/threading'> ignored"

When I strip my service down to its most basic components, I find that simply importing the python logging module is causing the error.  The error only occurs on shut down (so the import itself doesn't throw an exception).  No errors are logged to the windows event log.

My code is attached.  If the logging module in SvcDoRun is commented out, the error disappears.

**Comment by matysek** [comment]
Closing since this is too old without enough information and without any response from the author.
