### ISSUE TITLE
'tensorflow_core.python' not found in tensorflow  tensorflow 1.15.2(1.15.3, 1.15.4)

### ISSUE THREAD

**Issue by clark-2000** [pyinstaller/pyinstaller#5401]
I still have the same problem on TX2.
when i pack tensorflow 1.15.2(1.15.3, 1.15.4) + pyonstaller 4.1, This error have been bothering me lot time.
This fixed  [https://github.com/pyinstaller/pyinstaller/issues/5002](https://github.com/pyinstaller/pyinstaller/issues/5002) i have reference ,but it can't solved my problem.
Anyone please help me.

thensrflow installed from nvidia-tensorflow package :
packade download : [https://developer.download.nvidia.com/compute/redist/jp/v44/tensorflow/](https://developer.download.nvidia.com/compute/redist/jp/v44/tensorflow/)

Install command : sudo pip3 install --pre --extra-index-url https://developer.download.nvidia.com/compute/redist/jp/v44 tensorflow==1.15.2+nv20.01

This’s error message :

Traceback (most recent call last):
File “test.py”, line 1, in
File “/home/tx2/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py”, line 493, in exec_module
exec(bytecode, module.dict)
File “tensorflow/init.py”, line 99, in
File “/home/tx2/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py”, line 493, in exec_module
exec(bytecode, module.dict)
File “tensorflow_core/init.py”, line 28, in
File “tensorflow/init.py”, line 50, in getattr
File “tensorflow/init.py”, line 44, in _load
File “importlib/init.py”, line 126, in import_module
ModuleNotFoundError: No module named ‘tensorflow_core.python’
[27712] Failed to execute script test

Out of pip list :

Package Version

absl-py 0.10.0
altgraph 0.17
appdirs 1.4.4
apturl 0.5.2
asn1crypto 0.24.0
astor 0.8.1
astunparse 1.6.3
beautifulsoup4 4.6.0
blinker 1.4
Brlapi 0.6.6
cachetools 4.1.1
certifi 2018.1.18
chardet 3.0.4
click 7.1.2
cryptography 2.1.4
cupshelpers 1.0
Cython 0.29.21
decorator 4.1.2
defer 1.0.6
distro-info 0.18ubuntu0.18.04.1
et-xmlfile 1.0.1
feedparser 5.2.1
Flask 1.1.2
gast 0.2.2
geos 0.2.1
getmac 0.8.2
google-auth 1.23.0
google-auth-oauthlib 0.4.2
google-pasta 0.2.0
graphsurgeon 0.4.5
grpcio 1.32.0
h5py 2.10.0
html5lib 0.999999999
httplib2 0.9.2
idna 2.6
importlib-metadata 2.0.0
itsdangerous 1.1.0
jdcal 1.4.1
jetson-stats 3.0.1
Jetson.GPIO 2.0.8
Jinja2 2.11.2
Keras 2.3.1
Keras-Applications 1.0.8
Keras-Preprocessing 1.1.2
keyring 10.6.0
keyrings.alt 3.0
language-selector 0.1
launchpadlib 1.10.6
lazr.restfulclient 0.13.5
lazr.uri 1.0.3
louis 3.5.0
lxml 4.2.1
macaroonbakery 1.1.3
Mako 1.0.7
Markdown 3.3.1
MarkupSafe 1.0
numpy 1.18.5
oauth 1.0.1
oauthlib 3.1.0
onboard 1.4.1
onnx 1.4.1
openpyxl 3.0.5
opt-einsum 3.3.0
pandas 0.22.0
pbr 5.5.0
pip 20.2.4
protobuf 3.13.0
psutil 5.7.2
pyasn1 0.4.8
pyasn1-modules 0.2.8
pycairo 1.16.2
pycrypto 2.6.1
pycryptodome 3.9.9
pycuda 2019.1.2
pycups 1.9.73
pygobject 3.26.1
pyinstaller 4.1
pyinstaller-hooks-contrib 2020.10
PyJWT 1.5.3
pymacaroons 0.13.0
PyNaCl 1.1.2
pyRFC3339 1.0
python-apt 1.6.5+ubuntu0.3
python-dateutil 2.6.1
python-debian 0.1.32
pytools 2020.4
pytz 2018.3
pyxdg 0.25
PyYAML 3.12
requests 2.25.0
requests-oauthlib 1.3.0
requests-unixsocket 0.1.5
rsa 4.6
scipy 0.19.1
SecretStorage 2.3.1
setuptools 50.3.0
Shapely 1.6.4
simplejson 3.13.2
six 1.15.0
ssh-import-id 5.7
system-service 0.3
systemd-python 234
tensorboard 1.15.0
tensorflow 1.15.2+nv20.4
tensorflow-estimator 1.15.1
tensorrt 7.1.3.0
termcolor 1.1.0
testresources 2.0.1
typing 3.7.4.3
typing-extensions 3.7.4.3
ubuntu-drivers-common 0.0.0
uff 0.6.9
unity-scope-calculator 0.1
unity-scope-chromiumbookmarks 0.1
unity-scope-colourlovers 0.1
unity-scope-devhelp 0.1
unity-scope-firefoxbookmarks 0.1
unity-scope-manpages 0.1
unity-scope-openclipart 0.1
unity-scope-texdoc 0.1
unity-scope-tomboy 0.1
unity-scope-virtualbox 0.1
unity-scope-yelp 0.1
unity-scope-zotero 0.1
urllib3 1.22
urwid 2.0.1
wadllib 1.3.2
webencodings 0.5
Werkzeug 1.0.1
wheel 0.30.0
wrapt 1.12.1
xkit 0.0.0
zipp 3.3.0
zope.
interface 4.3.2

**Comment by bwoodsend** [comment]
Can you try again but use `python -m PyInstaller --clean your_code.py`

**Comment by clark-2000** [comment]
Thank you for you reply .But the same error happened.
I create simple code test.py to testing as below

import tensorflow as tf
print(tf.__version__)

Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "/home/tx2/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow/__init__.py", line 99, in <module>
  File "/home/tx2/.local/lib/python3.6/site-packages/PyInstaller/loader/pyimod03_importers.py", line 493, in exec_module
    exec(bytecode, module.__dict__)
  File "tensorflow_core/__init__.py", line 28, in <module>
  File "tensorflow/__init__.py", line 50, in __getattr__
  File "tensorflow/__init__.py", line 44, in _load
  File "importlib/__init__.py", line 126, in import_module
ModuleNotFoundError: No module named 'tensorflow_core.python'
[21182] Failed to execute script test

**Comment by rokm** [comment]
Hmmm, our [tensorflow tests are passing on 1.15.2, 1.15.3, and 1.15.4 on linux with python 3.6](https://github.com/rokm/pyinstaller-hooks-contrib/actions/runs/439943151) - however, these are PyPI builds and CPU-only.

But the 1.15.0 is failing on linux with the same symptoms as reported above, which are caused by a missing symbol in one of the shared libraries. 

Can you attach your build log, please? Perhaps the NVIDIA's custom builds for Jetson inherited the same issue in later versions...

**Comment by rokm** [comment]
I suspect this issue is similar to the one we observed with PyPI build of tensorflow 1.15.0, where failing to import one of tensorflow sub-packages due to missing symbol in one of its libraries prevented all other sub-packages from being collected. This should be addressed in PyInstaller 4.2 by #5426.

If  the issue persists, re-open the issue with updated details.
