### ISSUE TITLE
Problem with Importing PySide2 from a Network Drive

### ISSUE THREAD

**Issue by MKdays** [pyinstaller/pyinstaller#5405]
## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.1 (and 4.2.dev0)
* Version of Python: 3.9.1
* Platform: Windows10 x64 / Windows7 x32
* on Network Drive
* PySide2: 5.15.2
* PyQt5: 5.15.2

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

The app using PySide2 was interrupted on the network drive without an error message.
Other than C:/, there were no issues with a variety of drives, including USB.
If the app is running on a network drive, a simple script, as shown below, identified the problem at which stage.

### Test.py
```
import os
print("os : OK")
import PyQt5
print("PyQt5 : OK")
import PySide2
print("PtSide2 : OK")
print("OK")
input()
```

### Result : C:/ Drive, USB, Win7 32bit, Win10 64bit
```
os : OK
PyQt5 : OK
PtSide2 : OK
OK
```
### Result : Z:/ (Networkdrive) Win7 32bit, Win10 64bit
```
os : OK
PyQt5 : OK
```

I think the import method of PyQt5 and PySide2 may have made a difference. Please review this problem and give me feedback if you need a test.

**Comment by bwoodsend** [comment]
@MKdays Are you able to verify that PySide2 works if run with regular Python (no PyInstaller) installed on a network drive?

**Comment by rokm** [comment]
@MKDays Does it help if you copy `site-packages\shiboken2\files.dir` directory into your `dist\<program>\shiboken2`?

**Comment by MKdays** [comment]
> @MKdays Are you able to verify that PySide2 works if run with regular Python (no PyInstaller) installed on a network drive?

 PySide2 works with regular Python (no PyInstaller) installed on a network drive.

**Comment by MKdays** [comment]
> @MKdays Does it help if you copy `site-packages\shiboken2\files.dir` directory into your `dist\<program>\shiboken2`?

It works well when I move other files than shiboken2.pyd. It's getting close to a solution.

**Comment by rokm** [comment]
> It works well when I move other files than shiboken2.pyd. It's getting close to a solution.

Yeah, there's a bug in `PySide2` (or rather, their `shiboken2` module), which causes an infinite loop when that `files.dir` directory is missing AND a network-mapped drive is used. Normally (e.g., with local drive), the absence of that directory is handled correctly (and embedded python modules are used).

So there's nothing we can do about it here. You can copy that directory as a work-around if you want to use PySide2 application on a network-mapped drive, and I'll open a bug report with Qt/PySide2 project.

**Comment by rokm** [comment]
For the reference: https://bugreports.qt.io/browse/PYSIDE-1460

**Comment by rokm** [comment]
The PySide bug has been closed with a fix. Although I'm not sure what its availability will be like (especially for PySide2, given the status of the 5.15 branch).

At any rate, I'm closing this as there's nothing more for us to do here.
