### ISSUE TITLE
Pyinstaller is not compatible with PySide6, no Qt platform plugin could be initialized

### ISSUE THREAD

**Issue by L018** [pyinstaller/pyinstaller#5414]
Versions:
pyinstaller  4.1
Python 3.8.6
PySide6 6.0.0
Windows 10 1909

I am testing PySide6. I think I meet a ancient problem, that's the error "This application failed to start because no Qt Platform plugin could be initialized. Reinstalling the application may fix this problem".

I check utils/hooks/qt.py file's code, I think its can't package plugins dir file.

how do I solve problems quickly  for using--add-binary or copy .dll to dist dir?

**Comment by bwoodsend** [comment]
Ughh not another Qt variant.

> how do I solve problems quickly for using--add-binary or copy .dll to dist dir?

No clue. Qt is a complicated beast. I suggest sticking to supported PyQt5 for PySide2 until someone finds the time/motivation to fix this.

**Comment by 3wnbr1** [comment]
Just created https://github.com/pyinstaller/pyinstaller/pull/5418 and reported as fully functional on macOS, feel free to test this

**Comment by space9bug** [comment]
We can temporarily manually copy the missing files to the directory.
File list:
PySide6\plugins
PySide6\translations
PySide6\qt.conf

**Comment by musikis** [comment]
You must distribute with files in 'your Qt folder/6.0.0/mingw81_64/platforms/qwindows.dll' to 'your package folder/platforms'

**Comment by Dariusz1989** [comment]
Hey
So I take these issues > 
`qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.`
Is relevant to the topic? 
I can't make a custom hook-PySide6.py for it? 

it seems that if I copy platforms to be next to my exe then it works... would that be a "temporary valid" solution?
TIA!

**Comment by philimat** [comment]
In the meantime, I've done something like this in my .spec file which is working for me.

```
import PySide6
from os.path import join

pyside6_dir = PySide6.__path__[0]

added_files = [
(join(pyside6_dir, 'plugins'), 'plugins'), 
(join(pyside6_dir, 'translations'), 'translations'),
(join(pyside6_dir, 'qt.conf'), '.')
]

a = Analysis(
...
datas=added_files,
...
)
...
```

**Comment by Tanishq-Banyal** [comment]
**YOU CAN SOLVE THAT ERROR BY INCLUDING THE PLUGINS FOLDER WITH `--add-data` ARGUMENT**

Just add this line to the end of your pyinstaller command :-
`--add-data "PYTHON_DIRECTORY/Lib/site-packages/PySide6/plugins;PySide6/plugins/"`

In my case PYTHON_DIRECTORY WAS "C:\Program Files\Python38", so it becomes :-
`--add-data "C:\Program Files\Python38/Lib/site-packages/PySide6/plugins;PySide6/plugins/"`

**Tested working with both _One-File_ and _One-Dir_ mode**

**Comment by handelxh** [comment]
> **YOU CAN SOLVE THAT ERROR BY INCLUDING THE PLUGINS FOLDER WITH `--add-data` ARGUMENT**
> .
> Just add this line to the end of your pyinstaller command :-
> `--add-data "PYTHON_DIRECTORY/Lib/site-packages/PySide6/plugins;PySide6/plugins/"`
> .
> In my case PYTHON_DIRECTORY WAS "C:/Program Files/Python38", so it becomes :-
> `--add-data "C:/Program Files/Python38/Lib/site-packages/PySide6/plugins;PySide6/plugins/"`
> .
> _(Note : use forward slashes to avoid problems)_
> .
> **Tested working with both _One-File_ and _One-Dir_ mode**
> .
> .
> **FOR AUTO-PY-TO-EXE USERS :-**
> <img alt="" width="80%" src="https://user-images.githubusercontent.com/68330937/113676030-99f56d00-96d9-11eb-9290-ed3e093ab135.png">
> You can add the folder via "Additional Files" Tab :)

According to your method, this error was reported
![image](https://user-images.githubusercontent.com/4266376/114120823-d74b3c00-991f-11eb-84e8-490a6cdadb42.png)

**Comment by space9bug** [comment]
This article I wrote is helpful to you in solving this problem.
[**https://blog.csdn.net/qq_41730930/article/details/112612864**](https://blog.csdn.net/qq_41730930/article/details/112612864)

**Comment by Tanishq-Banyal** [comment]
> According to your method, this error was reported
> ![image](https://user-images.githubusercontent.com/4266376/114120823-d74b3c00-991f-11eb-84e8-490a6cdadb42.png)

Try adding PySide6 as hidden import

and first check if the program even works without packaging

**Comment by SelmaAdjabi** [comment]
> > According to your method, this error was reported
> > ![image](https://user-images.githubusercontent.com/4266376/114120823-d74b3c00-991f-11eb-84e8-490a6cdadb42.png)
> 
> Try adding PySide6 as hidden import
> 
> and first check if the program even works without packaging

Thank you @Tanishq-Banyal, your solution worked for me 🎉

**Comment by rubyon** [comment]
Mac OS 11.3.1 M1 Macbook Pro

Python installed by brew install python@3.9

QT6 installed by brew install qt

PySide6 installed by brew install pyside

pyinstaller installed from https://github.com/rokm/pyinstaller/tree/macos11-arm64-support-cleanup

copy this two folder
/opt/homebrew/Cellar/pyside/6.0.4/lib/python3.9/site-packages/PySide6
/opt/homebrew/Cellar/pyside/6.0.4/lib/python3.9/site-packages/shiboken6

and paste it ( replace )

this folder

YOUR_APP_EXEC_FILE.app/Contents/MacOS

It Works!

**Comment by fbjorn** [comment]
I had the same problem, my application didn't want to start due to absence of "cocoa" plugin (MacOS 11.4, Python 3.9):
```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

@rubyon 's suggestion suddenly helped. "Suddenly" cause I was trying to explicitly copy the content of these 2 folders by defining them in `datas=[],` of my spec. I even tried to diff PySide6/shiboken6 from `dist` and PySide6/shiboken6 from virtualenv. Some libraries had the same size, but had a binary mismatch (how?).

I don't want to dig into that more,  so I'm just copying over these folders after running Pyinstaller. 

Small hint: you can remove some plugins or Qt libs which are not used by the application and reduce your bundle size. 
For me, removing following folders saved me almost 80 MBs of disk space:
```
    rmtree(qt_out / "qml")
    rmtree(qt_out / "translations")
    useless_libs = (
        "Qt3D",
        "QtDesigner",
        "QtQuick",
        "QtShader",
        "QtVirt",
        "QtSql",
        "QtData",
        "QtCharts",
        "QtLabs",
        "QtScxml",
    )
    for d in (qt_out / "lib").glob("*"):
        if d.name.startswith(useless_libs):
            rmtree(d)

    plugins = ("platforms", "styles")
    for d in (qt_out / "plugins").glob("*"):
        if d.name not in plugins:
            rmtree(d)
```

**Comment by SuAnita520** [comment]
For Windows 10, I solved by:
```
import os
from PySide6.QtWidgets import QApplication, QMainWindow, QPushButton, QPlainTextEdit
envpath = r'C:\ProgramData\Anaconda3\envs\CV36\Lib\site-packages\PySide6\plugins\platforms'
os.environ["QT_QPA_PLATFORM_PLUGIN_PATH"] = envpath
```

I cannot set environment variables directly in System. My project is stored in Disk D but my Anaconda folder is in Disk C.

**Comment by bwoodsend** [comment]
Well that's using files from your Conda installation so now your users will not only have to install conda but they'll have to install it in exactly the same place as you did then create a virtual environment with exactly the same name as yours...
