### ISSUE TITLE
Unify code for loading module and code objects.

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#542]
**Original date**: 2012/03/30

Code for loading modules or compiling source is used at several places:

`marshal`:
 - depend/impdirector.py
 - depend/owner.py
 - hooks/hook-distutils.py
 - hooks/hook-xml.py

`py_compile`
 - build.py

`compile`
 - depend/impdirector.py
 - depend/imptracker.py
 - depend/owner.py

In addition there is similar code in loader/iu.py and loader/archive.py which most probably must not by unified.

**Comment by matysek** [comment]
I did some research and it is mostly done.
