### ISSUE TITLE
Unable to Code Sign macOS App Built with GTK

### ISSUE THREAD

**Issue by danyeaw** [pyinstaller/pyinstaller#5422]
## Description of the issue
GTK apps that are packaged with PyInstaller have a gdk-pixbuf-2.0 package in the Contents/Resources/MacOS/lib directory. The period in the name makes Apple's codesign utility thinks that it is a bundle and the signing fails.

According to the [Apple docs](https://developer.apple.com/library/archive/technotes/tn2206/_index.html#//apple_ref/doc/uid/DTS40007919-CH1-TNTAG201), these types of files should be the Resources directory.

Issue #3680 came up with a work around to create symlinks between MacOS and Resources. This solution is posted on the wiki as a [OSX Code Signing recipe for Qt apps](https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing-Qt). I wasn't able to get this to work for a GTK app, probably because the package structure is slightly different. 

## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.1
* Version of Python: 3.9.1
* Platform: macOS
* Did you also try this on another platform? Does it work there? N/A

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk


window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

### Stacktrace / full error message

```
(.venv) danielyeaw@Daniels-MacBook-Pro gtk-helloworld % ls -R dist/helloworld.app/Contents/MacOS/lib                              
gdk-pixbuf-2.0	python3.9

dist/helloworld.app/Contents/MacOS/lib/gdk-pixbuf-2.0:
2.10.0

dist/helloworld.app/Contents/MacOS/lib/gdk-pixbuf-2.0/2.10.0:
loaders		loaders.cache

dist/helloworld.app/Contents/MacOS/lib/gdk-pixbuf-2.0/2.10.0/loaders:
libpixbufloader-ani.so	libpixbufloader-jpeg.so	libpixbufloader-tga.so
libpixbufloader-bmp.so	libpixbufloader-png.so	libpixbufloader-tiff.so
libpixbufloader-gif.so	libpixbufloader-pnm.so	libpixbufloader-xbm.so
libpixbufloader-icns.so	libpixbufloader-qtif.so	libpixbufloader-xpm.so
libpixbufloader-ico.so	libpixbufloader-svg.so
```

I would like to use this issue to collect feedback on whether we can work to have PyInstaller place these types of files for GTK, QT, and others in the Resources directory. I can help by creating a PR once we agree on a potential solution.

**Comment by danyeaw** [comment]
@BoboTiG and @cbenhagen since you helped develop the initial QT workaround, do you have any input on a more proper solution?

**Comment by BoboTiG** [comment]
Sorry for the late answer @danyeaw. In fact, the best option would be to move such data into the `Framework` folder (it is just a guess). But seeing how other apps are done (using something else than PyInstaller), there almost already is a `Framework` folder containing such data (PyQt).

For you specific issue, moving to the `Resources` folder was a good idea too, but your fix is also good ;)

So there may be more work to be done at some point about Qt and other specific dependencies handling.

**Comment by danyeaw** [comment]
@BoboTiG Based on my understanding, PyInstaller already moves all *data* to the `Resources` folder. However the GdkPixbuf libraries were still in the `MacOS` folder, which was fine - except for the fact that the folder names had periods in them.

I think you are right that long term we can think about the ideal place to package everything.
