### ISSUE TITLE
pkg_resources.DistributionNotFound / transformers - Script to ease solving lost modules errors

### ISSUE THREAD

**Issue by cronopioelectronico** [pyinstaller/pyinstaller#5428]
As mentioned in other issues as #4809 or #5247, the error "pkg_resources.DistributionNotFound: The 'module_name' distribution was not found" can be solved by creating a directory `hooks-files` with a file `hook-module_name.py` and running pyinstaller in the main_program with the option:

`pyinstaller main_program.py -D --additional-hooks-dir=hooks-files`

where the content of hook-module_name.py is:

```
from PyInstaller.utils.hooks import collect_all

datas, binaries, hiddenimports = collect_all('module_name')
```

However, there are cases where too many modules are missing, as it is the case when importing the [huggingface transformers](https://github.com/huggingface/transformers) module (in my case when using the Bert model: `from transformers import BertTokenizer, BertModel`). In those cases fixing the case mentioned in the error just triggers the next case, and solving one by one becomes unfeasible.

For those cases with too many missing modules, the `warn-main_program.txt` file generated in the `build` directory contains a reference to most missing modules, but it is difficult to extract all the references and create the relevant hook files.

In order to ease the processing of warn-main_program.txt and generate the needed hook files I share here a brief script:

`python warn_processing.py warn-main_program.txt`

Content of warn_processing.py:

```
### Define next the folder to create the hooks files and the warning file to read the modules from
output_hooks_dir = 'hooks-files'
warning_file = 'warn-main_program.txt'

import re

with open(warning_file) as file:
    files_content = file.readlines()

clean_content = []
for line in files_content:
    if re.search('missing module named',line):        
        temp_line = re.sub('.*imported by ','',line)
        temp_line = re.sub('\n',', ',temp_line)
        clean_content.append(temp_line)
clean_content = list(set(clean_content))
joined_content = ''.join(clean_content)
clean_content = list(set(joined_content.split('), ')))
#print(len(clean_content))
#print(clean_content)

modules_toplevel = []
for line in clean_content:
    if re.search('top-level',line):
        temp_mod = re.sub(' \(.*','',line)
        temp_mod = re.sub('\..*','',temp_mod)
        modules_toplevel.append(temp_mod)
modules_toplevel = list(set(modules_toplevel))

modules_conditional = []
for line in clean_content:
    if re.search('conditional',line):
        temp_mod = re.sub(' \(.*','',line)
        temp_mod = re.sub('\..*','',temp_mod)
        modules_conditional.append(temp_mod)
modules_conditional = list(set(modules_conditional))

modules_delayed = []
for line in clean_content:
    if re.search('delayed',line):
        temp_mod = re.sub(' \(.*','',line)
        temp_mod = re.sub('\..*','',temp_mod)
        modules_delayed.append(temp_mod)
modules_delayed = list(set(modules_delayed))

modules_optional = []
for line in clean_content:
    if re.search('optional',line):
        temp_mod = re.sub(' \(.*','',line)
        temp_mod = re.sub('\..*','',temp_mod)
        modules_optional.append(temp_mod)
modules_optional = list(set(modules_optional))

all_modules = modules_toplevel + modules_conditional + modules_delayed + modules_optional
all_modules = list(set(all_modules))

print(all_modules)
print('Number of modules:',len(all_modules))

### Optional: remove any of the modules
### all_modules.remove('module_to_remove)

### Optional: Change all_modules by any of the other lists, e.g. modules_toplevel
for module in all_modules:
    output_content = 'from PyInstaller.utils.hooks import collect_all\n\ndatas, binaries, hiddenimports = collect_all(\''+module+'\')'
    with open(output_hooks_dir+'/hook-'+str(module)+'.py', 'w') as f:
        f.write(output_content)
```

The previous script can be also changed as explained in the last block, to extract just some types of missing modules (e.g. only the top-level or the conditional modules)

----

For the specific case of the transformers/Bert module, the complete list of missing modules in my case has been:

['importlib_metadata', 'pickle', 'urllib3', 'torch', 'packaging', 'setuptools', 'requests', 'nbconvert', 'matplotlib', 'google', 'unittest', 'send2trash', 'xmlrpc', 'os', 'uuid', 'future', 'posixpath', 'importlib', 'curses', 'pytz', 'wcwidth', 'PyInstaller', 'pstats', 'ipykernel', 'dbm', 'copy', 'jinja2', 'terminado', 'regex', 'ipython_genutils', 'urllib', 'past', 'filelock', 'jupyter_client', 'cycler', 'IPython', 'mpl_toolkits', 'testpath', 'scipy', 'pygments', 'getpass', 'tornado', 'joblib', 'netrc', 'pickleshare', 'transformers', 'markupsafe', 'tqdm', 'pdb', 'test', 'shutil', 'pathlib', 'jedi', 'six', 'distutils', 'cStringIO', 'webbrowser', 'dummy_threading', 'dateutil', 'prompt_toolkit', 'nbformat', 'win32com', 'traitlets', 'platform', 'PIL', 'attr', 'numpy', 'xml', 'pkg_resources', 'sklearn', 'multiprocessing', 'pandas', 'posix', 'tarfile', 'winpty', 'click', 'subprocess', 'tty', 'http', 'code', 'cryptography', 'cPickle', 'caffe2', 'pyparsing', 'defusedxml', 'zmq', 'pycparser', 'jsonschema', 'asyncio', 'tokenizers', 'cmd', 'cffi', 'anydbm', 'notebook', 'prometheus_client', 'entrypoints', 'sacremoses']

Creating hook files for each module with the previous script solved the problem in my case.

## Context information

* pyinstaller 4.1
* Python: 3.7
* Platform: [Windows 8.1 and Windows 10 virtualboxes](https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/) running in a 18.04.1-Ubuntu x86_64

## Minimal program reproducing the error

```
import torch
from transformers import BertTokenizer, BertModel
```

**Comment by RS357** [comment]
Hi @cronopioelectronico - could you push this script in a PR for us to look at please?

**Comment by bwoodsend** [comment]
Actually I don't think we want this. Bryan's tried the collect everything be default approach before. It results in piles of unwanted clutter being collected. Looking at that list I see plenty of things that shouldn't be there (all that IPython/Jupyter stuff).

**Comment by cronopioelectronico** [comment]
Yes @bwoodsend probably other solutions are more elegant. But I think that for some cases could be useful to have the 'collect everything' option as an alternative that can be used (not by default). 

In this case I mention using the transformers module I tried to fix the missing hooks one by one (when the error failed I included just the module mentioned as not found; tried again, then the next module; ...) and it was impossible. There were too many modules lost. And in that particular case each iteration took too much time, so it was also unfeasible to try enough times.

Anyway, even if you don't implement something similar, I just leave the script here in case anybody find it useful.

**Comment by kennynakamura** [comment]
Thank you! 
Help me a lot

**Comment by PhaneendraGunda** [comment]
Hi,

I am getting the following error while creating executable with transformers using PyInstaller

**PyInstaller: 4.3
736 INFO: Python: 3.8.5 (conda)
751 INFO: Platform: macOS-10.15.5**

_413560 INFO: Packages required by datasets:
['dill', 'multiprocess', 'pandas', 'tqdm', 'tqdm', 'requests', 'xxhash', 'pyarrow', 'numpy']
445137 INFO: Packages required by filelock:
[]
  File "<string>", line 2
    import huggingface-hub as p
                      ^
SyntaxError: invalid syntax
Traceback (most recent call last):
  File "/Users/pkgunda/opt/anaconda3/envs/few-shot-torch/lib/python3.8/site-packages/PyInstaller/utils/hooks/__init__.py", line 358, in get_module_file_attribute
    attr = loader.get_filename(package)
AttributeError: 'NoneType' object has no attribute 'get_filename'_


transformers hook file as follows,

from PyInstaller.utils.hooks import collect_all


def hook(hook_api):
    packages = [
        'transformers',
        # "Pillow",
        # "black==21.4b0",
        # "cookiecutter==1.7.2",
        "dataclasses",
        "datasets",
        # "deepspeed>=0.3.16",
        # "docutils==0.16.0",
        # "fairscale>0.3",
        # "faiss-cpu",
        # "fastapi",
        "filelock",
        # "flake8>=3.8.3",
        # "flax>=0.3.2",
        # "fugashi>=1.0",
        "huggingface-hub",
        "importlib_metadata",
        # "ipadic>=1.0.0,<2.0",
        # "isort>=5.5.4",
        # "jax>=0.2.8",
        # "jaxlib>=0.1.59",
        # "jieba",
        # "keras2onnx",
        # "nltk",
        "numpy",
        # "onnxconverter-common",
        # "onnxruntime-tools>=1.4.2",
        # "onnxruntime>=1.4.0",
        "packaging",
        # "parameterized",
        # "protobuf",
        # "psutil",
        # "pydantic",
        # "pytest",
        # "pytest-sugar",
        # "pytest-xdist",
        # "python>=3.6.0",
        # "recommonmark",
        "regex",
        "requests",
        # "rouge-score",
        # "sacrebleu>=1.4.12",
        "sacremoses",
        # "sagemaker>=2.31.0",
        # "scikit-learn",
        # "sentencepiece==0.1.91",
        # "soundfile",
        # "sphinx-copybutton",
        # "sphinx-markdown-tables",
        # "sphinx-rtd-theme==0.4.3",  # sphinx-rtd-theme==0.5.0 introduced big changes in the style.
        # "sphinx==3.2.1",
        # "sphinxext-opengraph==0.4.1",
        # "starlette",
        # "tensorflow-cpu>=2.3",
        # "tensorflow>=2.3",
        # "timeout-decorator",
        "tokenizers",
        # "torch>=1.0",
        # "torchaudio",
        "tqdm",
        # "unidic>=1.0.2",
        # "unidic_lite>=1.0.7",
        # "uvicorn",
    ]

    for package in packages:
        datas, binaries, hiddenimports = collect_all(package)
        hook_api.add_datas(datas)
        hook_api.add_binaries(binaries)
        hook_api.add_imports(*hiddenimports)

**Comment by cronopioelectronico** [comment]
Hi @PhaneendraGunda not sure about your problem, but for sure there is a syntax problem as the error is pointing. It should be `huggingface_hub` instead of `huggingface-hub`.
