### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by htgoebel** [pyinstaller/pyinstaller#5430]
Drop support for Python 3.5 after PyInstaller 4.2 release. 
Python 3.5 will be EOL for 3 months then, and PyInstaller 4.2 will still support it.

**Comment by bwoodsend** [comment]
Ughh, I thought 4.1 was the last to support Python 3.5. I've already scrapped it from #5218. Is this negotiable? 3.5 and its lack of `os.PathLike` is bad for my sanity.

**Comment by Legorooj** [comment]
@bwoodsend @htgoebel I currently have a half completed branch dropping support for python 3.5. Will submit a PR within the next couple of days.

**Comment by johnthagen** [comment]
PR: #5439
