### ISSUE TITLE
Missing module lxml.etree

### ISSUE THREAD

**Issue by alxdrdelaporte** [pyinstaller/pyinstaller#5431]
Hi,

I tried to parse some XML with `bs4` using the `lxml` parser and I can't run the exe.

## Description of the issue

It seems like importing `bs4` works fine, but `lxml`/`lxml.etree` module is missing (the directory containing the freezed program does have `lxml` and `xmlschema` subfolders though, as well as a `_elementtree.pyd` file). 

I am using `--onedir`, `--noupx` and also tried `--hidden-import xml.etree --hidden-import xml.etree.ElementTree`.

As this appears to be similar to issue #5365, I tried to modify my spec file following the suggested workaround:

```python
from PyInstaller.utils.hooks import collect_data_files
hiddenimports = ['xml.etree', 'xml.etree.ElementTree']
datas = collect_data_files('xmlschema')

...
```

This didn't work, I keep getting the exact same outputs.
Using a venv (or not) doesn't seem to help either.

## Context information

* Output of `pyinstaller --version`: ```4.1```
* Version of Python: 3.9.1
* Platform:  Windows-10-10.0.18362-SP0
* Did you also try this on another platform? Does it work there? I did not, as it is work related I have to make it work on my current platform.

* [x] start with clean installation
* [ ] use the latest development version
* [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
* [x] Package your program in **--onedir mode**
* [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
* [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

[Example in this gist](https://gist.github.com/alxdrdelaporte/065aee5eec30d9a73243e7cd585965ce)

### Stacktrace / full error message

Error message when running the exe
```shell
Traceback (most recent call last):
  File "xml_sample_soup.py", line 31, in <module>
  File "bs4\__init__.py", line 242, in __init__
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
[36628] Failed to execute script xml_sample_soup
```

`lxml` related output when freezing with `--debug=imports`
```shell
import bs4.builder._lxml # PyInstaller PYZ
import lxml # PyInstaller PYZ
import 'lxml' # <pyimod03_importers.FrozenImporter object at 0x000001B5461B50D0>
# lxml.etree not found in PYZ
# destroy bs4.builder._lxml
```

`lxml.etree` warning in warn file
```
missing module named lxml.etree - imported by lxml (top-level), bs4.builder._lxml (top-level), lxml.sax (top-level), lxml.builder (top-level), lxml.doctestcompare (top-level), lxml.ElementInclude (top-level), lxml.cssselect (top-level), lxml.isoschematron (top-level), lxml.html (top-level), lxml.pyclasslookup (top-level)
```

pyinstaller output (actual working directory path replaced with "path")
`lxml` hooks fail to load but they actually are in the `_pyinstaller_hooks_contrib` (+ the path is ok too)
```shell
C:\path>pyinstaller --onedir --noupx --hidden-import xml.etree --hidden-import xml.etree.ElementTree --paths=C:\path\site-packages --debug=imports xml_sample_soup.py
47 INFO: PyInstaller: 4.1
47 INFO: Python: 3.9.1
47 INFO: Platform: Windows-10-10.0.18362-SP0
48 INFO: wrote C:\path\xml_sample_soup.spec
49 INFO: UPX is not available.
53 INFO: Extending PYTHONPATH with paths
['C:\\path',
 'C:\\path\\site-packages',
 'C:\\path']
58 INFO: checking Analysis
58 INFO: Building Analysis because Analysis-00.toc is non existent
58 INFO: Initializing module dependency graph...
61 INFO: Caching module graph hooks...
72 INFO: Analyzing base_library.zip ...
2153 INFO: Processing pre-find module path hook distutils from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2155 INFO: distutils: retargeting to non-venv dir 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib'
4057 INFO: Caching module dependency graph...
4128 INFO: running Analysis Analysis-00.toc
4139 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\alex\appdata\local\programs\python\python39\python.exe
4184 WARNING: lib not found: api-ms-win-core-path-l1-1-0.dll dependency of c:\users\alex\appdata\local\programs\python\python39\python39.dll
4204 INFO: Analyzing C:\path\xml_sample_soup.py
4842 INFO: Processing module hooks...
4842 INFO: Loading module hook 'hook-lxml.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
5148 WARNING: Hidden import "lxml.objectify" not found!
5163 INFO: Loading module hook 'hook-difflib.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5166 INFO: Excluding import of doctest from module difflib
5169 INFO: Loading module hook 'hook-distutils.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5170 INFO: Loading module hook 'hook-distutils.util.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5170 INFO: Excluding import of lib2to3.refactor from module distutils.util
5171 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5231 INFO: Loading module hook 'hook-heapq.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5234 INFO: Excluding import of doctest from module heapq
5235 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5280 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5282 INFO: Excluding import of test from module multiprocessing.util
5282 INFO: Excluding import of test.support from module multiprocessing.util
5284 INFO: Loading module hook 'hook-pickle.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5287 INFO: Excluding import of argparse from module pickle
5288 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5289 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5289 INFO: Loading module hook 'hook-xml.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5289 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks'...
5398 INFO: checking Tree
5400 INFO: Building Tree because Tree-00.toc is non existent
5401 INFO: Building Tree Tree-00.toc
5469 INFO: checking Tree
5472 INFO: Building Tree because Tree-01.toc is non existent
5473 INFO: Building Tree Tree-01.toc
5541 INFO: checking Tree
5542 INFO: Building Tree because Tree-02.toc is non existent
5543 INFO: Building Tree Tree-02.toc
5551 INFO: Loading module hook 'hook-lxml.isoschematron.py' from 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
5570 INFO: Looking for ctypes DLLs
5597 INFO: Analyzing run-time hooks ...
5599 INFO: Including run-time hook 'c:\\users\\alex\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
5603 INFO: Looking for dynamic libraries
5822 INFO: Looking for eggs
5822 INFO: Using Python library c:\users\alex\appdata\local\programs\python\python39\python39.dll
5825 INFO: Found binding redirects:
[]
5832 INFO: Warnings written to C:\path\build\xml_sample_soup\warn-xml_sample_soup.txt
5869 INFO: Graph cross-reference written to C:\path\build\xml_sample_soup\xref-xml_sample_soup.html
5881 INFO: checking PYZ
5881 INFO: Building PYZ because PYZ-00.toc is non existent
5882 INFO: Building PYZ (ZlibArchive) C:\path\build\xml_sample_soup\PYZ-00.pyz
6328 INFO: Building PYZ (ZlibArchive) C:\path\build\xml_sample_soup\PYZ-00.pyz completed successfully.
6336 INFO: checking PKG
6336 INFO: Building PKG because PKG-00.toc is non existent
6340 INFO: Building PKG (CArchive) PKG-00.pkg
6355 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
6356 INFO: Bootloader c:\users\alex\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
6356 INFO: checking EXE
6358 INFO: Building EXE because EXE-00.toc is non existent
6359 INFO: Building EXE from EXE-00.toc
6363 INFO: Appending archive to EXE C:\path\build\xml_sample_soup\xml_sample_soup.exe
6364 INFO: Building EXE from EXE-00.toc completed successfully.
6367 INFO: checking COLLECT
6367 INFO: Building COLLECT because COLLECT-00.toc is non existent
6367 INFO: Building COLLECT COLLECT-00.toc
6442 INFO: Building COLLECT COLLECT-00.toc completed successfully.
```

**Comment by rokm** [comment]
Hmm, I cannot seem to reproduce this. What version of `lxml` are you using?

You could try doing a `hiddenimports = collect_submodules('lxml')`, but that should already be done by the `hook-lxml.py`, which we can see firing from your log. But just in case, what is the output if you manually run the following snippet in python?
```python
from PyInstaller.utils.hooks import collect_submodules
collect_submodules('lxml')
```

**Comment by alxdrdelaporte** [comment]
I am using `lxml` version 4.6.

I tried `hiddenimports = collect_submodules('lxml')`, sadly it didn't work, `lxml` is still missing. Running the exe throws the same error as without.

Running the snippet provided generates the following output:

```shell
['lxml.html.html5parser', 'lxml.ElementInclude', 'lxml.sax', 'lxml.html.ElementSoup', 'lxml.html.diff', 'lxml.html.soupparser', 'lxml.usedoctest', 'lxml.html', 'lxml', 'lxml.html._html5builder', 'lxml.objectify', 'lxml.cssselect', 'lxml.builder', 'lxml.html.clean', 'lxml.html._diffcommand', 'lxml.pyclasslookup', 'lxml.html.formfill', 'lxml.html.usedoctest', 'lxml.includes', 'lxml.html.defs', 'lxml._elementpath', 'lxml.isoschematron', 'lxml.doctestcompare', 'lxml.html._setmixin', 'lxml.html.builder', 'lxml.etree']
```

**Comment by rokm** [comment]
On my test system, the `lxml.etree` comes in a form of `.pyd` extension, so most of the warnings about missing `lxml.etree` are red herring (i.e., the module will not be found in PYZ archive, because it should be collected as a separate file in dist folder).

<details><summary>So the import log on working system looks like:</summary><p>

```
import lxml # PyInstaller PYZ
import 'lxml' # <pyimod03_importers.FrozenImporter object at 0x0000023DA38D50D0>
# lxml.etree not found in PYZ
# extension module 'lxml.etree' loaded from 'C:\\[...]\\dist\\program\\lxml\\etree.cp39-win_amd64.pyd'
# backports_abc not found in PYZ
# lxml._elementpath not found in PYZ
# extension module 'lxml._elementpath' loaded from 'C:\\[...]\\dist\\program\\lxml\\_elementpath.cp39-win_amd64.pyd'
```

</p></details>

Can you list the contents of your `dist\xml_sample_soup\lxml` directory - does it contain `etree.cp39-win_amd64.pyd˙?

**Comment by alxdrdelaporte** [comment]
`etree.cp39-win_amd64.pyd` is indeed missing from my `dist\xml_sample_soup\lxml` folder.

Here are all of its contents:

- isoschematron
  - resources
    - rng
      - iso-schematron.rng
    - xsl
      - iso-schematron-xslt1
        - iso_abstract_expand.xsl
        - iso_dsdl_include.xsl
        - iso_schematron_message.xsl
        - iso_schematron_skeleton_for_xslt1.xsl
        - iso_svrl_for_xslt1.xsl
        - readme.txt
      - RNG2Schtrn.xsl
      - XSD2Schtrn.xsl

**Comment by rokm** [comment]
Hmm, is it present in the `site-packages\lxml`?

**Comment by alxdrdelaporte** [comment]
It is, and thanks to your comments I found the source of the problem and was able to fix it easily.

So I checked the contents of the additional paths I passed to freeze the program and it appeared that one of them also had a `lxml` subfolder, in addition to the one already in `site-packages\lxml`. Removing it solved the problem.

So I'm totally at fault here, but I probably wouldn't have been able to fix that without your help.
Thanks a lot!

**Comment by PSpaulojr** [comment]
Hi, i'm having a similar problem with my program. The problem is with pandas, using the funcion read_html(). It works when a run on a IDLE, but when a freeze a program into a .exe file, it returns an error
Traceback (most recent call last):

  File "main4.py", line 2887, in <module>
    main()
  File "main4.py", line 2799, in main
    pega_dados_nf_sigetplus(
  File "main4.py", line 337, in pega_dados_nf_sigetplus
    dados_tabela_sitgetplus(driver, path_download,
  File "main4.py", line 122, in dados_tabela_sitgetplus
    tabela_pagina = pd.read_html(driver.page_source)[0]
  File "pandas\util\_decorators.py", line 311, in wrapper
  File "pandas\io\html.py", line 1098, in read_html
  File "pandas\io\html.py", line 902, in _parse
  File "pandas\io\html.py", line 859, in _parser_dispatch
ImportError: lxml not found, please install it

There is a file on my dist on the subfolder lxml named etree.cp39-win_amd64.pyd

Can you guys help me?

**Comment by FattySparks** [comment]
> It is, and thanks to your comments I found the source of the problem and was able to fix it easily.
> 
> So I checked the contents of the additional paths I passed to freeze the program and it appeared that one of them also had a `lxml` subfolder, in addition to the one already in `site-packages\lxml`. Removing it solved the problem.
> 
> So I'm totally at fault here, but I probably wouldn't have been able to fix that without your help. Thanks a lot!

I'm having a similar issue, but I'm calling the standard xml parser. I'm very new to this and am having trouble following what fixed the issue.

Here's my error message:
```
Generating report. Please wait...
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1705, in __call__
  File "main.py", line 41, in enterPressed
    checkForFile()
  File "main.py", line 60, in checkForFile
    buildReport(excelName_Ext, excelName_Path)
  File "main.py", line 86, in buildReport
    parser.dataMiner(background, masters, deviceDef, document, excelName_Ext, excelName_Path, vsdxFilename)
  File "reportBuilder.py", line 641, in dataMiner
    self.openFile(xmlFile)
  File "reportBuilder.py", line 22, in openFile
    self.soup = BeautifulSoup(contents, 'xml')
  File "bs4\__init__.py", line 248, in __init__
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: xml. Do you need to install a parser library?
```

The program works fine when running it through Powershell, but not the .exe. I have a similar program that worked until I updated to Python 3.9. Since then neither program works as a .exe file. I tried downgrading back to 3.7, and no luck.

TYIA

**Comment by bwoodsend** [comment]
The original issue was a bit of a niche case. There was another folder named `lxml` which was shadowing the `lxml` installation causing it to not be collected. You might have that but it's probably something different in your case. Have you tried just adding `--collect-submodules=lxml` to your pyinstaller command?

**Comment by FattySparks** [comment]
> The original issue was a bit of a niche case. There was another folder named `lxml` which was shadowing the `lxml` installation causing it to not be collected. You might have that but it's probably something different in your case. Have you tried just adding `--collect-submodules=lxml` to your pyinstaller command?

That was it! Thank you so much.

**Comment by licy666** [comment]
> The original issue was a bit of a niche case. There was another folder named `lxml` which was shadowing the `lxml` installation causing it to not be collected. You might have that but it's probably something different in your case. Have you tried just adding `--collect-submodules=lxml` to your pyinstaller command?

Thanks a lot!!! I have spend 24 hours to solve this problem. You are my hero!!!!!

**Comment by Llaves** [comment]
I had this issue as well and the solution was yet different. Although the .exe would run in the Anaconda env it was built in, it would not run in a simple cmd shell. (This is Windows, in case it wasn't clear yet.) I finally checked and the build env didn't include lxml. No idea why it ran from the shell, but once I added lxml to the env, the bundled .exe runs in a simple cmd shell. 

Moral of the story - check if the env you're building in actually includes lxml, even if it runs there.

**Comment by mctinker** [comment]
So, I can't use '--collect-submodules=lxml' with .spec file that has numerous 'datas=' files...

option(s) not allowed:
  --collect-submodules
makespec options not valid when a .spec file is given

**Comment by bwoodsend** [comment]
The spec file equivalent of `--collect-submodules` is
```python
from PyInstaller.utils.hooks import collect_submodules

a = Analysis(
    ...
    hiddenimports=collect_submodules("lxml"),
    ...
)
```

**Comment by mctinker** [comment]
Ok, gave it a try but Pyinstaller fails.  Here is the spec file I am using with your recommended change:

 `# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_submodules


block_cipher = None


a = Analysis(
    ['MapTasker.py'],
    pathex=[],
    binaries=[],
    datas=[('tasks.py', '.'), ('outputl.py', '.'), ('config.py', '.'), ('action.py', '.'), ('actionc.py', '.'), ('actiond.py', '.'), ('actione.py', '.'), ('MapTasker.py', '.'), ('outputl.py', '.'), ('progargs.py', '.'), ('proginit.py', '.'), ('shellsort.py', '.'), ('tables.py', '.'), ('taskerd.py', '.'), ('etree_lxml.py', '.')],
    iddenimports=collect_submodules("lxml"),
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='MapTasker',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)`
 
Here is the command I am issuing:

`pyinstaller --clean MapTasker.spec`
 
And here is the output I get:
`mikrubin@Michaels-iMac ~/M/P/MapTasker (default) [1]> pyinstaller --clean MapTasker.spec
69 INFO: PyInstaller: 5.7.0
69 INFO: Python: 3.10.9
78 INFO: Platform: macOS-12.6.2-x86_64-i386-64bit
80 INFO: UPX is not available.
80 INFO: Removing temporary files and cleaning cache in /Users/mikrubin/Library/Application Support/pyinstaller
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 971, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 893, in build
    exec(code, spec_namespace)
  File "MapTasker.spec", line 8, in <module>
    a = Analysis(
TypeError: Analysis.__init__() got an unexpected keyword argument 'iddenimports'
mikrubin@Michaels-iMac ~/M/P/MapTasker (default) [1]>`

**Comment by rokm** [comment]
> ```
>     a = Analysis(
> TypeError: Analysis.__init__() got an unexpected keyword argument 'iddenimports'
> ```

Your `hiddenimports` are missing an "h".

**Comment by mctinker** [comment]
Doh!  Shame on me.
 
Okay, fixed the missing "h" but on module execution, I still get:

` /Users/mikrubin/My\ Drive/Python/MapTasker/dist/MapTasker ; exit;
Traceback (most recent call last):
  File "MapTasker/MapTasker.py", line 36, in <module>
    import tasks as tasks
  File "/var/folders/nb/8twwzmrj3pn_x8kw0w9sz9_h0000gn/T/_MEIR2iD8g/tasks.py", line 16, in <module>
    from MapTasker import my_output
  File "/var/folders/nb/8twwzmrj3pn_x8kw0w9sz9_h0000gn/T/_MEIR2iD8g/MapTasker.py", line 40, in <module>
    from taskerd import get_the_xml_data
  File "/var/folders/nb/8twwzmrj3pn_x8kw0w9sz9_h0000gn/T/_MEIR2iD8g/taskerd.py", line 12, in <module>
    import xml.etree.ElementTree as ET  # This built-in code will parse the xml for us
**ModuleNotFoundError: No module named 'xml'**
[48645] Failed to execute script 'MapTasker' due to unhandled exception!

[Process completed]
`

Any clue as to what I should try next?

**Comment by rokm** [comment]
> Doh! Shame on me.
> 
> Okay, fixed the missing "h" but on module execution, I still get:
> 
> ` /Users/mikrubin/My\ Drive/Python/MapTasker/dist/MapTasker ; exit; Traceback (most recent call last): File "MapTasker/MapTasker.py", line 36, in import tasks as tasks File "/var/folders/nb/8twwzmrj3pn_x8kw0w9sz9_h0000gn/T/_MEIR2iD8g/tasks.py", line 16, in from MapTasker import my_output File "/var/folders/nb/8twwzmrj3pn_x8kw0w9sz9_h0000gn/T/_MEIR2iD8g/MapTasker.py", line 40, in from taskerd import get_the_xml_data File "/var/folders/nb/8twwzmrj3pn_x8kw0w9sz9_h0000gn/T/_MEIR2iD8g/taskerd.py", line 12, in import xml.etree.ElementTree as ET # This built-in code will parse the xml for us **ModuleNotFoundError: No module named 'xml'** [48645] Failed to execute script 'MapTasker' due to unhandled exception!
> 
> [Process completed] `
> 
> Any clue as to what I should try next?

I see you are adding your .py source files as data files. This means that while they are collected, they do not undergo the import analysis. If you really want to go that route, you will need to manually determine all the imports your added .py files make, and add them as hiddenimports. In this particular case, you are missing `xml` module from stdlib, which has nothing to do with `lxml` package...

**Comment by mctinker** [comment]
Ok, thanks for the clarification.  The reason that I am adding some of my source files as data files is that this is the only way I could get them recognized by Pyinstaller.  I have one for each 'from xxx import yyy' statement.  Without the data files, the 'xxx' was not getting recognized.

**Comment by rokm** [comment]
> The reason that I am adding some of my source files as data files is that this is the only way I could get them recognized by Pyinstaller. I have one for each 'from xxx import yyy' statement. Without the data files, the 'xxx' was not getting recognized.

Yeah, that's suspicious in itself, because PyInstaller should add the parent directory of the entry-point script to the search path, and should pick up those modules automatically (and in a proper way). 

One scenario where this is not the case is if you have an `__init__.py` file next to the entry-point script; in that case, we traverse the parent directories and take the first one that does not contain `__init__.py`. Is that the case here?

**Comment by mctinker** [comment]
Yup, that was the problem. An empty __init__.py was created a few weeks ago by something of which I have no idea.  
 
I deleted it and all is well.  Thanks so much for your help!
