### ISSUE TITLE
Error when freezing a MXNet based Program

### ISSUE THREAD

**Issue by piyumalranawaka** [pyinstaller/pyinstaller#5433]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
I am trying to freeze several MXNet based programs. Freezing process is successful in all cases however when I run it I got some errors. Then after reading previous issues and solutions I added the following to the pyinstaller command
-F --add-data="/home/piyumal/mxnetenv/lib/python3.7/site-packages/mxnet/*.so*:./mxnet"

Then it works well for all cases except two. I am providing outputs of one of them here:

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.1```
* Version of Python: e.g. 3.7
* Platform: e.g GNU/Linux (distribution)
I did not try since I don't have access to another platform

###The program that I am trying to freeze
```
from mxnet.gluon.model_zoo import vision
import mxnet as mx
import matplotlib.pyplot as plt
from mxnet import gluon, nd
from mxnet.gluon.model_zoo import vision
import numpy as np
import json
import os

Some extra code here

def transform(image)

def predict(transformed_image):
    predictions = model(transformed_image).softmax()
    top_pred = predictions.topk(k=k)[0].asnumpy()
    for index in top_pred:
        probability = predictions[0][int(index)]
        category = categories[int(index)]
        print("{}: {:.2f}%".format(category, probability.asscalar()*100))
    print('')

for filename in os.listdir(directory):
  try:
    image = mx.image.imread(os.path.join(directory,filename))
  except:
    continue
  transformed_image= transform(image) 
  predict(transformed_image,)
  if (count==385):
    break

```

### Stacktrace / full error message

```
[9785] Error loading Python lib '/tmp/_MEISNVfL9/libpython3.7m.so.1.0': dlopen: /tmp/_MEISNVfL9/libpython3.7m.so.1.0: cannot open shared object file: No such file or directory
```

e.

**Comment by rokm** [comment]
Does this happen only in `onefile` build, or also in `onedir` one? 
Is the python library properly included in the `onedir` build? 
And, are there any warnings in the `onefile` build log regarding the python library?

**Comment by rokm** [comment]
Can you run pyinstaller with added `--clean --log-level DEBUG` arguments, e.g.

`pyinstaller -F --add-data="/home/piyumal/mxnetenv/lib/python3.7/site-packages/mxnet/*.so:./mxnet" script.py --onefile --clean --log-level DEBUG`

and attach the full build log as a file (please do not copy and paste the text - attach the file instead)?

**Comment by piyumalranawaka** [comment]
Thank you very much for your great support, attached herewith is the log:
[log.txt](https://github.com/pyinstaller/pyinstaller/files/5774876/log.txt)

**Comment by piyumalranawaka** [comment]
I removed all the files created by the build and tried building again, it completed successfully but when I run it I get a different error as seen here:
[build log.txt](https://github.com/pyinstaller/pyinstaller/files/5775241/build.log.txt)
[run log.txt](https://github.com/pyinstaller/pyinstaller/files/5775243/run.log.txt)


Much thankful for your kind advise and support

**Comment by rokm** [comment]
> RuntimeError: Cannot find the MXNet library.
List of candidates:
/tmp/_MEIr7FHGf/libmxnet.so
/tmp/_MEIr7FHGf/mxnet/libmxnet.so
/tmp/_MEIr7FHGf/mxnet/../../lib/libmxnet.so
/tmp/_MEIr7FHGf/mxnet/../../build/libmxnet.so
../../../libmxnet.so
[29534] Failed to execute script script

That's just `libmxnet.so` missing from the distribution - did you forget to add `--add-data` argument or maybe some wildcards (`*`) were missing from there? 

But it seems at least for pure PyPI build (not sure for conda), the `libgfortran.so.*` libraries from `mxnet` need to be placed into distribution root, while `libmxnet.so` can be either placed in distribution root or in `mxnet` subfolder.

So the following two variants seem to work for me:
```
pyinstaller program.py \
    --add-data "venv/lib/python3.9/site-packages/mxnet/libmxnet.so:./mxnet" \
    --add-data "venv/lib/python3.9/site-packages/mxnet/libgfortran.so.*:." \
    --clean --noconfirm
```
or
```
pyinstaller program.py \
    --add-data "venv/lib/python3.9/site-packages/mxnet/*.so*:." \
    --clean --noconfirm
```

PS: you really should first build in `onedir` mode, because it makes it easier to inspect the collected files. Once `onedir` works, you can try building in `onefile` mode...

**Comment by piyumalranawaka** [comment]
Now it's working perfectly :) Thank you very much indeed for your kind help and great support!
