### ISSUE TITLE
[proposed area:bootloader platform:OS X] Mac OS X Application Does Not Receive Drag 'n Drop File Paths

### ISSUE THREAD

**Issue by mwfong-csl** [pyinstaller/pyinstaller#5436]
A Mac OS X application built with PyInstaller 4.1 `--onedir` and `--windowed` is run as single process (cf., a forked child process). Consequently, when it is started by a drag and drop operation, it does not process `OpenDoc` Apple Events and `sys.argv` does not include the dropped path(s).

From `pyi_main.c:pyi_main ()`:
```
#if defined(_WIN32) || defined(__APPLE__)

    /* On Windows and Mac use single-process for --onedir mode. */
    if (!extractionpath && !pyi_launch_need_to_extract_binaries(archive_status)) {
        VS("LOADER: No need to extract files to run; setting extractionpath to homepath\n");
        extractionpath = homepath;
    }

#endif
    :
    :
    if (extractionpath) {
        VS("LOADER: Already in the child - running user's code.\n");
          :
          :
    }
    else {
          :
          :
        /* Run the 'child' process, then clean up. */

        VS("LOADER: Executing self as child\n");
          :
          :
    }
```

**Comment by bwoodsend** [comment]
@cculianu Don't suppose you're in the mood for another #5295 ?

**Comment by cculianu** [comment]
Hi! :) 

Oh I see -- so this is a totally different execution path that ignores the odoc AppleEvent stuff? I'll try and make some time for it this week to investigate.. from 10,000ft view it sounds/looks like this shouldn't be hard .. I hope.

**Comment by mwfong-csl** [comment]
I hacked `pyi_utils.[ch]` and `pyi_main.c:py_main()` to invoke `process_apple_events ()` and then provisionally update `archive_status->arg[cv]`.  It works, but it's not pretty.  Thus, I'll leave it in your capable hands.

**Comment by bwoodsend** [comment]
That's awesome, thanks @cculianu. It's your call if you think it's worth the brainpower to do it.

@mwfong-csl If you can at least show us a git diff of your changes that'll probably save us a lot of time.

**Comment by mwfong-csl** [comment]
Sure.  Here they are:
```
diff --git a/bootloader/src/pyi_main.c b/bootloader/src/pyi_main.c
index 003929f..159c243 100644
--- a/bootloader/src/pyi_main.c
+++ b/bootloader/src/pyi_main.c
@@ -144,26 +144,6 @@ pyi_main(int argc, char * argv[])
     if (extractionpath) {
         VS("LOADER: Already in the child - running user's code.\n");
 
-        #if defined(__APPLE__) && defined(WINDOWED)
-            process_apple_events (true);
-
-            if (argc_pyi /* > 0 */) {
-                char **_argv = (char **) calloc (argc + argc_pyi + 1, sizeof (char *));
-                int    _argc = 0;
-
-                for (char **_arg = argv; *_arg /* != (char *) NULL */; ++_arg)
-                    _argv[_argc++] = *_arg;
-
-                for (char **_arg = argv_pyi; *_arg /* != (char *) NULL */; ++_arg)
-                    _argv[_argc++] = *_arg;
-
-                archive_status->argc = _argc;
-                archive_status->argv = _argv;
-
-                VS("LOADER: Appending OpenDoc paths to argv.\n");
-            }
-        #endif
-
         /*  If binaries were extracted to temppath,
          *  we pass it through status variable
          */
diff --git a/bootloader/src/pyi_utils.c b/bootloader/src/pyi_utils.c
index 50c68e8..fda1a4a 100644
--- a/bootloader/src/pyi_utils.c
+++ b/bootloader/src/pyi_utils.c
@@ -90,13 +90,8 @@ typedef void (*sighandler_t)(int);
  *  (this is argv_emulation).  These variables must be of file global scope to be able to
  *  be accessed inside of the AppleEvents handlers.
  */
-#if 0
 static char **argv_pyi = NULL;
 static int argc_pyi = 0;
-#else
-char **argv_pyi = NULL;
-int argc_pyi = 0;
-#endif
 
 /*
  * Watch for OpenDocument AppleEvents and add the files passed in to the
@@ -106,10 +101,7 @@ int argc_pyi = 0;
  * on the App icon in the OS X dock.
  */
 #if defined(__APPLE__) && defined(WINDOWED)
-#if 0
-static
-#endif
-void process_apple_events(Boolean);
+static void process_apple_events(Boolean);
 #endif
 
 
@@ -1459,10 +1451,7 @@ static OSStatus evt_handler_proc(EventHandlerCallRef href, EventRef eref, void *
 }
 
 /* Apple event message pump */
-#if 0
-static
-#endif
-void process_apple_events(Boolean short_timeout)
+static void process_apple_events(Boolean short_timeout)
 {
     static EventHandlerUPP handler;
     static AEEventHandlerUPP handler_ae;
diff --git a/bootloader/src/pyi_utils.h b/bootloader/src/pyi_utils.h
index 61856bf..88f85a4 100644
--- a/bootloader/src/pyi_utils.h
+++ b/bootloader/src/pyi_utils.h
@@ -52,14 +52,4 @@ int pyi_utils_create_child(const char *thisfile, const ARCHIVE_STATUS *status,
                            const int argc, char *const argv[]);
 int pyi_utils_set_environment(const ARCHIVE_STATUS *status);
 
-#if defined(__APPLE__) && defined(WINDOWED)
-extern char **argv_pyi;
-extern int argc_pyi;
-
-#include <Carbon/Carbon.h>  /* AppleEventsT */
-
-void process_apple_events(Boolean short_timeout);
-
-#endif
-
 #endif  /* HEADER_PY_UTILS_H */
```

**Comment by cculianu** [comment]
Oh I see what's going on. It's swallowing up all the events! In the case where there is no subordinate subprocess (no child process), this bootloader is eating up the events so they never make it to the `exec`'d process that replaces the bootloader, perhaps?

I didn't realize this mode of operation is possible in PyInstaller (while I know C quite well and the Apple API reasonably well -- I was not super familiar with all of PyInstaller's inner workings).  Had I known that such a mode of operation is possible I probably would have handled this in the last set of changes I submitted to PyInstaller.

Ok so still from the 2.,000ft view I have now this sounds quite straightforward -- I'll make time this week (maybe even today) to play around with this and see how `--onedir` + `--windowed`   differs and hopefully remove the event-swallowing in that particular code path, so that it works as expected in all possible usages.

Thanks for the clarification, @mwfong-csl

**Comment by cculianu** [comment]
HI -- update: I haven't had time to look at this yet. Either this weekend or early next week. Soon though!

**Comment by rokm** [comment]
Re-opening this issue as support for onedir events processing / argv emulation has been reverted for now due to unforeseen side effects with `tkinter`-based applications.

**Comment by rokm** [comment]
Support for argv emulation in `onedir` mode has been re-enabled in the `develop` branch via #6089, and will be available in the upcoming PyInstaller 5.x series.

This feature is now disabled by default (in both `onefile` and `onedir` mode) and needs to be explicitly opted-in at build time either via `--argv-emulation` command-line switch or using `argv_emulation` argument to `EXE()` in the .spec file.

This feature also requires bootloader to be rebuilt, so if you want to try using the `develop` branch until 5.0 is released, you will need to rebuild the bootloader yourself.
