### ISSUE TITLE
.vbs file displays window

### ISSUE THREAD

**Issue by PETEROLO291** [pyinstaller/pyinstaller#5437]
## Description of the issue
On my script i need to restart the script to reload some configuracións. So i created a .bat file that runs the py script when gets closed, and linked to it a vbs file to hide the bat file window. Everything works fine untill i compile the script into a folder. (Moved manualy inside the vbs and bat file.

## Context information (for bug reports)

* Last pyinstaller version
* Version of Python: 3.7
* Platform: Windows 10 Pro
* Did you also try this on another platform? Does it work there?
Didn't try

### Minimal Code
How i runed vbs file from the py script
system.("hide.vbs")
Bat file content
@echo off
Python main.py

**Comment by rokm** [comment]
We are missing a lot of context here...

What exactly does `hide.vbs` do? From the above, it sounds like it should minimize the parent console window? And this worked for launcher .bat + unfrozen python script, but it does not work for launcher .bat + frozen/compiled python script? What happens in this case - does the `system("hide.vbs")` call fail?

Also, why are you calling the vbs script from the python script - why not just call it in the launcher .bat file instead, to hide console window before running the python script?

**Comment by PETEROLO291** [comment]
Vbs scripts run without window. So if i run the bat file from the vbs script wont show up any cmd window. Thats hy i dont call the .bat file directly. But this method stops working when i compyle the script. Cuz thrn allwais will apear a cmd window poping up for 0.5s more less

**Comment by rokm** [comment]
Ah, okay... so the problem is that in unfrozen application, running VBS script does not open a window, but in a frozen application, it does.

Are you freezing the python application in windowed (non-console) mode?

**Comment by rokm** [comment]
I think this boils down to using `os.system()` in `noconsole` (windowed) mode. The `os.system()` [call spawns a sub-shell](https://docs.python.org/3/library/os.html#os.system), so if no console is available, it will open one.

Try freezing following example
```python
import os
print("Running command...")
os.system('timeout 10')
print("Command complete!")
```
in both `console` and `noconsole` (windowed) mode, then run the resulting executables. 

In `console` variant, you will see both output from python's `print()` and from the `timeout` command in the opened console, while in `noconsole` variant, you will see only the output of `timeout` command in the opened console. 

It's even more noticeable if you run the executables from `cmd` prompt, because `console` variant will fully reuse the existing console, while the `noconsole` one will open a new one for the `os.system()`-spawned process.

**Comment by PETEROLO291** [comment]
Okay, but i didnt understand how this will help me to hide the poping cmd window. Mybe im just stupid but pleade geave me an example of how should run the exe to hide the cmd win

**Comment by bwoodsend** [comment]
If all you want to do is restart your program I think all you need is to put:
```python
os.startfile(sys.executable)
```
somewhere just before the end of your Python code then forget all this vbs hoo hah. A minimal example using tkinter:
```python
# test.py
import os
import sys
import tkinter as tk


def restart():
    # Launch the next instance.
    os.startfile(sys.executable)
    # Close this one.
    sys.exit()


root = tk.Tk()

# Set title to something unique.
root.title(str(os.getpid()))

tk.Button(text='Restart', command=restart).pack(fill=tk.X)
tk.Button(text='Quit', command=root.quit).pack(fill=tk.X)
tk.mainloop()
```
which can be compiled with:
```bash
pyinstaller -w test.py
```

Unfortunately this will work only on Windows and when PyInstaller-ed.

**Comment by PETEROLO291** [comment]
@bwoodsend And will that run whitout cmd window popping up?

**Comment by bwoodsend** [comment]
Yes.

**Comment by PETEROLO291** [comment]
I have tried os.startfile(sys."My_program.exe) and I get a synax error because I have never used os.startfile() or the sys library. I think I need help to understand what to do. @bwoodsend

**Comment by bwoodsend** [comment]
Umm, did you not put `import os` at the top?

**Comment by PETEROLO291** [comment]
Yes ofc

**Comment by subnut** [comment]
@PETEROLO291 Skip the bat file. Run the compiled binary from the vbs itself.

i.e.
```diff
  Set WshShell = CreateObject("WScript.Shell")
- WshShell.Run chr(34) & "restart.bat" & Chr(34), 0
+ WshShell.Run timeout 0.5, 0, 1
+ WshShell.Run chr(34) & "main.exe" & Chr(34), 0
  Set WshShell = Nothing
```
It should work without window. 
I am using something similar [here](https://github.com/subnut/nvim-ghost.nvim/blob/main/scripts/start_server.vbs) successfully

**Comment by PETEROLO291** [comment]
@subnut Didn't try yet. But what I see in the code you posted is running the restart.bat and the main.exe. Wont that causes the exe running 2 times?

**Comment by subnut** [comment]
I don't mean to be offensive, but haven't you ever looked at your git commits? 

Even if you haven't, isn't it obvious from the coloring and the `+` and `-` signs that I __removed__ the bat file?

**Comment by PETEROLO291** [comment]
K issue solved
