### ISSUE TITLE
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding

### ISSUE THREAD

**Issue by Robstersgaming** [pyinstaller/pyinstaller#5438]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
When running the exe created by pyinstaller with pyinstaller --onefile test.py I get this error:
```
C:\desktop 2\files\Python projects\Pyinstaller testing\dist>test.exe
Python path configuration:
  PYTHONHOME = 'C:\Users\robby\AppData\Local\Temp\_MEI30322'
  PYTHONPATH = (not set)
  program name = 'C:\desktop 2\files\Python projects\Pyinstaller testing\dist\test.exe'
  isolated = 0
  environment = 0
  user site = 0
  import site = 0
  sys._base_executable = 'C:\\desktop 2\\files\\Python projects\\Pyinstaller testing\\dist\\test.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.platlibdir = 'lib'
  sys.executable = 'C:\\desktop 2\\files\\Python projects\\Pyinstaller testing\\dist\\test.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Users\\robby\\AppData\\Local\\Temp\\_MEI30322\\base_library.zip',
    'C:\\Users\\robby\\AppData\\Local\\Temp\\_MEI30322',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
LookupError: unknown encoding: utf-8

Current thread 0x0000204c (most recent call first):
<no Python frame>

C:\desktop 2\files\Python projects\Pyinstaller testing\dist>
```
## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.1```
* Version of Python: e.g. 3.7 ```3.9.0(updating to python 3.9.1 didn't fix my issue```
* Platform: e.g GNU/Linux (distribution), Windows (language settings), OS X, conda, FreeBSD ```Windows 10```
* Did you also try this on another platform? Does it work there?
```I have not ```

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ !] start with clean installation
  * [ !] use the latest development version
  * [ !] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ !] Package your program in **--onedir mode**
  * [ !] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ !] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
Every piece of code I try errors:
```
import time
import encodings
input("Test")
print("hello world")
time.sleep(60) #Time.sleep makes the cmd persist

```
### What I've tried and what I think the cause of the issue is 
After unpacking the .exe file I could see that the encodings folder was missing all of the python encodings which I assume is spitting the error.(it only contains 3 files unrelated to encodings)[The 3 Files](https://i.stack.imgur.com/lqw6r.png) I tried specyfying the path to the encodings module with pyinstaller --onfile --paths="path" test.py to no avail. I also tried importing encodings in my code again issue persisted. Is the issue with the missing files in the unpacked exe? Or is it some other issue? The unpacked exe is [here](https://anonfiles.com/t6ldWb4dp0/test.exe_rar)
### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Hmm, this indeed looks like encodings were not collected for some reason (the files should be in `encodings` folder inside `base_library.zip`)...

Can you try re-building the minimal example with `--log-level DEBUG` enabled, and check the build log for entries like:
```
5917 DEBUG: Collecting submodules for encodings
6085 DEBUG: collect_submodules - Found submodules: {'encodings.cp775', ..., 'encodings.cp1250'}
```

Or, check the output of the following python snippet:
```python
from PyInstaller.utils.hooks import collect_submodules
collect_submodules('encodings')
```

**Comment by Robstersgaming** [comment]
Running with --log-level DEBUG
```
5943 DEBUG: Collecting submodules for encodings
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "c:\users\robby\appdata\local\programs\python\python39\lib\pkgutil.py", line 6, in <module>
    import importlib.util
  File "c:\users\robby\appdata\local\programs\python\python39\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "c:\users\robby\appdata\local\programs\python\python39\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "c:\users\robby\appdata\local\programs\python\python39\lib\site-packages\typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "c:\users\robby\appdata\local\programs\python\python39\lib\site-packages\typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'
5996 DEBUG: collect_submodules - Found submodules: {'encodings'}
```
output of the code snippet:
```
C:\desktop 2\files\Python projects\Pyinstaller testing>test2.py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "C:\Users\robby\AppData\Local\Programs\Python\Python39\lib\pkgutil.py", line 6, in <module>
    import importlib.util
  File "C:\Users\robby\AppData\Local\Programs\Python\Python39\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "C:\Users\robby\AppData\Local\Programs\Python\Python39\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "C:\Users\robby\AppData\Local\Programs\Python\Python39\lib\site-packages\typing.py", line 1359, in <module>
    class Callable(extra=collections_abc.Callable, metaclass=CallableMeta):
  File "C:\Users\robby\AppData\Local\Programs\Python\Python39\lib\site-packages\typing.py", line 1007, in __new__
    self._abc_registry = extra._abc_registry
AttributeError: type object 'Callable' has no attribute '_abc_registry'

C:\desktop 2\files\Python projects\Pyinstaller testing>
```


> Hmm, this indeed looks like encodings were not collected for some reason (the files should be in `encodings` folder inside `base_library.zip`)...
> 
> Can you try re-building the minimal example with `--log-level DEBUG` enabled, and check the build log for entries like:
> 
> ```
> 5917 DEBUG: Collecting submodules for encodings
> 6085 DEBUG: collect_submodules - Found submodules: {'encodings.cp775', ..., 'encodings.cp1250'}
> ```
> 
> Or, check the output of the following python snippet:
> 
> ```python
> from PyInstaller.utils.hooks import collect_submodules
> collect_submodules('encodings')
> ```

**Comment by rokm** [comment]
> AttributeError: type object 'Callable' has no attribute '_abc_registry'

This seems to be due to `typing` package installed under python version where it is not necessary anymore. Uninstalling `typing` should fix the problem. See https://github.com/psf/black/issues/1707#issuecomment-692371268 and the corresponding `typing` issue that's linked there.

**Comment by EdLipson5117** [comment]
I hit the same issue today. I checked my VENV, no typing module included. I did see this, though:

191 DEBUG: Collecting submodules for encodings
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "c:\Users\edlip\AppData\Local\Programs\Python\Python39\lib\pkgutil.py", line 6, in <module>
    import importlib.util
  File "c:\Users\edlip\AppData\Local\Programs\Python\Python39\lib\importlib\util.py", line 2, in <module>
    from . import abc
  File "c:\Users\edlip\AppData\Local\Programs\Python\Python39\lib\importlib\abc.py", line 17, in <module>
    from typing import Protocol, runtime_checkable
  File "c:\Users\edlip\AppData\Local\Programs\Python\Python39\lib\typing.py", line 26, in <module>
    import re as stdlib_re  # Avoid confusion with the re we export.
  File "c:\Users\edlip\AppData\Local\Programs\Python\Python39\lib\re.py", line 145, in <module>
    class RegexFlag(enum.IntFlag):
AttributeError: module 'enum' has no attribute 'IntFlag'

**Comment by rokm** [comment]
>  AttributeError: module 'enum' has no attribute 'IntFlag'

That's caused by another package, `enum34`, which is similarly incompatible with recent python versions: https://stackoverflow.com/a/48125118/1117028

**Comment by Robstersgaming** [comment]
> > AttributeError: type object 'Callable' has no attribute '_abc_registry'
> 
> This seems to be due to `typing` package installed under python version where it is not necessary anymore. Uninstalling `typing` should fix the problem. See [psf/black#1707 (comment)](https://github.com/psf/black/issues/1707#issuecomment-692371268) and the corresponding `typing` issue that's linked there (i.e., [python/typing#573](https://github.com/python/typing/issues/573)).
Thank you so much :) uninstalling the typing package solved my issue

**Comment by nburno** [comment]
After all what is the solution, even for print hello python code, it raises errors, and keep us on loop with trial and errors.
Nothing sharp and straight forward. these issues should be solved before declaring this package is live

**Comment by rokm** [comment]
> After all what is the solution, even for print hello python code, it raises errors, and keep us on loop with trial and errors.
> Nothing sharp and straight forward. these issues should be solved before declaring this package is live

In this particular issue, the solution is to clean up your environment of obsolete packages that conflict with recent python's modules/packages (e.g., `typing` or `enum34`). 

Otherwise, the solution is to open a new issue and provide relevant details there (such as OS, python version, and the error message), instead of posting in closed issues with some vague complaints that nobody can reproduce...

**Comment by nburno** [comment]
At the end I found the solution, by getrid  of bullshit pyinstaller and go through professional way of C++ and Java.

It was a fresh clean environment with python 3.9.6 and latest version with pyinstaller and none of typing or enum34 installed and raise errors for only print(‘hello world’)

try it yourself with fresh installation of python3.9 and pyinstaller 
write any code without any import and see the raised errors by pyinstaller. 

moreover, any special or/and hidden configuration or setup should be clearly mentioned in the first web page. and this is the only professional way.  



The only solution was: 
 
 pip3 uninstall pyinstaller

**Comment by jiangfeizi** [comment]
I change upx to False,it successed.
