### ISSUE TITLE
version 4.1 folder .../bootloader/Windows-64bit miss "runw.exe" Application

### ISSUE THREAD

**Issue by Mr-ZBin** [pyinstaller/pyinstaller#5449]
When I used version 4.1, and I got error message on cmd. But after I copy "runw.exe" from version 4.0 folder(.../bootloader/Windows-64bit/runw.exe) to version 4.1 folder(.../bootloader/Windows-64bit/runw.exe) , it worked fine.

**Comment by bwoodsend** [comment]
Can you remember if `runw.exe` was there originally and you replaced it or it was missing? Both sdists on PyPI contain the same number of bootloaders with the same names.

**Comment by Mr-ZBin** [comment]
Hi,
It was missing on version 4.1 but exist on version 4.0 on my conputer.
![image](https://user-images.githubusercontent.com/22544491/103721720-5b341600-5009-11eb-8b87-4e0ba288dcb3.png)

**Comment by rokm** [comment]
All bootloaders are present in the [PyPI source distribution tarball](https://pypi.org/project/pyinstaller/#files), so if it's missing on your computer, something might have removed it - an overzealous anti-virus program, perhaps?

**Comment by Mr-ZBin** [comment]
Yes, I think it might removed by anti-virus program, thank you.
