### ISSUE TITLE
ModuleNotFoundError even with hook is added

### ISSUE THREAD

**Issue by etjkai** [pyinstaller/pyinstaller#5452]
## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.1
* Version of Python: 3.8
* Platform: Windows 10 (English)
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### A minimal example program which shows the error

```
import dash
import plotly.graph_objs as go
import numpy as np
import dash_core_components as dcc
import dash_html_components as html

external_stylesheets = ["https://codepen.io/chriddyp/pen/bWLwgP.css"]

app = dash.Dash(__name__, external_stylesheets=external_stylesheets)

labels = ["Oxygen", "Hydrogen", "Carbon_Dioxide", "Nitrogen"]
values = [4500, 2500, 1053, 500]
pie_fig = go.Figure(
    data=[go.Pie(labels=labels, values=values)]
)
piechart = dcc.Graph(
    figure=pie_fig
)

app.layout = html.Div(
    [
        html.Div([piechart], className="row"),
    ]
)

if __name__ == "__main__":
    app.run_server(debug=True)

```

### Stacktrace / full error message

```
pkg_resources.DistributionNotFound: The 'flask-compress' distribution was not found and is required by the application
[2852] Failed to execute script script
```

I'm working with a venv in this project, and have added the hooks to the following, as recommended in the following [stackoverflow thread](https://stackoverflow.com/questions/60495030/pyinstaller-searches-in-nonexistent-folder)

- dash_bootstrap_components
- dash_core_components
- dash_html_components
- dash_renderer

It then prompts me with the following error: `pkg_resources.DistributionNotFound: The 'flask-compress' distribution was not found and is required by the application`, for which I do the same and add it as a hook. 

A subsequent ModuleNotFoundError is then found for : `'plotly.validators.pie'`, for which I add `plotly` to hooks as well. 

However, I still get the `ModuleNotFoundError: No module named 'plotly.validators.pie'` error after adding it as a hook.

This is the code I use to run pyinstaller with
`pyinstaller --onedir --noconfirm --additional-hooks-dir=hooks --paths=venv\Lib\site-packages script_min.py`

**Comment by etjkai** [comment]
Okay it seems like I just had to delete my "dist" folder for this to run properly, as `--noconfirm` did not seem to replace some of the existing files properly.

**Comment by bwoodsend** [comment]
PyInstaller is rubbish at detecting hook changes. Always build using the `--clean` option when adding/changing hooks too stop PyInstaller mistakenly caching everything.

**Comment by etjkai** [comment]
Thank you for the tip @bwoodsend.

In totality, I have 6 hooks in total, and I think it is causing my resultant output file/directory size to become quite large, and taking quite some time to run. Other than using `--onedir` instead of `--onefile`, are there any other ways to avoid this unfortunate consequence of many hooks?

**Comment by bwoodsend** [comment]
Just having several hooks shouldn't be an issue. PyInstaller and pyinstaller-hooks-contrib (which you'll also have) together ship hundreds off hooks so having 6 more isn't an issue. If your hooks are all very aggressive (i.e. collect absolutely everything for every package when you only need one missing import) that could drag in bits you don't need but there's no general fix. You'll need to go through what's being collected, work out where they came from, then decide if you need them or not.
