### ISSUE TITLE
Django under Windows 7 simply can't be packaged, and all kinds of errors emerge in endlessly

### ISSUE THREAD

**Issue by batsword** [pyinstaller/pyinstaller#5455]
windows 7下的django根本就是没法打包，各种错误层出不穷
---------------友好翻译:
Django under Windows 7 simply can't be packaged, and all kinds of errors emerge in endlessly

i can't see any advantage in Python!

**Comment by bwoodsend** [comment]
Please use the issue template if you expect us to help you.
