### ISSUE TITLE
OSX .app build fails Gtk error

### ISSUE THREAD

**Issue by akaAndrew** [pyinstaller/pyinstaller#5460]
I am getting this error when opening the .app on a new machine, any pointers to why it is failing.
non standard modules 

from bs4 import BeautifulSoup
import requests
import gi

/Contents/MacOS/gi_typelibs/Gtk-3.0.typelib' for namespace 'Gtk': The specified typelib length 0 is too short

**Comment by rokm** [comment]
The error message suggests that `Contents/MacOS/gi_typelibs/Gtk-3.0.typelib` in your .app bundle somehow ended up empty. Can you verify that?
