### ISSUE TITLE
_main__.PyInstallerImportError: Failed to load dynlib/dll 'D:\\Path\\program\\libzbar-64.dll'

### ISSUE THREAD

**Issue by LakeConcept** [pyinstaller/pyinstaller#5465]
I searched and testes for a week to get a solution but i did not find one.

Python: 3.8.6
Pyinstaller: 4.1
pyzbar: 0.1.8

Following imports are used in the program.py python code:
from imutils.video import VideoStream
from pyzbar import pyzbar
import imutils
import cv2
import winsound
import sys
import os

The code successfully works while executing using PyCharm. 
When i create an exe (one directory) with pyinstaller and put the missing dll's 'libzbar-64.dll' and 'libiconv.dll' manually to the created program folder it works on a Surface Go with OS Windows 10 Pro (10.0.18363 Build 18363).

But when i put this folder to a Surface Go 2 with OS Windows 10 Pro (10.0.18363 Build 18363) i get the following error:
_main__.PyInstallerImportError: Failed to load dynlib/dll 'D:\\Path\\program\\libzbar-64.dll'. Most probably this dynlib/dll was not found when the application was frozen.
[3552] Failed to execute script Program_

When i add the two dll's with 'add-binary' i get the same error.

With the following spec file the missing binaries 'libzbar-64.dll' and 'libiconv.dll' where automatically put to the created folder this works on the Surface Go but again not on the Surface Go 2. The error is the same.

`
# -*- mode: python ; coding: utf-8 -*-
import sys
from pathlib import Path
from pyzbar import pyzbar
block_cipher = None

sys.modules['FixTk'] = None

a = Analysis(['C:/Users/.../PycharmProjects/Program/program.py'],
             pathex=[str(Path('.').absolute())],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)

a.binaries += TOC([
    (Path(dep._name).name, dep._name, 'BINARY')
    for dep in pyzbar.EXTERNAL_DEPENDENCIES
])

MISSING_DYLIBS = (
    Path('/usr/local/lib/libjpeg.8.dylib'),
)
a.binaries += TOC([
    (lib.name, str(lib.resolve()), 'BINARY') for lib in MISSING_DYLIBS
])

pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='Test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True,
		  icon='C:\\Users\\...\\PycharmProjects\\Program\\favicon.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='Test')
` 

Here is the full erorr:
_Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 144, in __init__
  File "ctypes\__init__.py", line 373, in __init__
FileNotFoundError: Could not find module 'C:\Users\...\Program\program\libzbar-64.dll' (or one of its dependencies). Try using the full path with constructor syntax.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "pyzbar\zbar_library.py", line 58, in load
  File "pyzbar\zbar_library.py", line 54, in load_objects
  File "ctypes\__init__.py", line 451, in LoadLibrary
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 146, in __init__
__main__.PyInstallerImportError: Failed to load dynlib/dll 'C:\\Users\\...\\Program\\program\\libzbar-64.dll'. Most probably this dynlib/dll was not found when the application was frozen._

How can i solve this problem? Thank you.

**Comment by rokm** [comment]
`libzbar-64.dll` probably depends on another DLL that is present on the first machine, but not on second. Try opening `libzbar-64.dll` with [`Dependency walker`](https://www.dependencywalker.com/) on the second machine, and see if there's a DLL missing.

(Perhaps your second machine does not have VC runtime installed, and is missing `MSVCR120.dll`?)
