### ISSUE TITLE
error accessing sys.modules

### ISSUE THREAD

**Issue by danielhrisca** [pyinstaller/pyinstaller#5467]
## Description of the issue

Running an application that uses ``canmatrix`` works from normal python, but fails when running from a PyInstaller build. 
In particular [this line](https://github.com/ebroecker/canmatrix/blob/568ed7d11b3875493ba3095826c4b48dcdea02e9/src/canmatrix/formats/__init__.py#L92) fails with ``KeyError: 'canmatrix.formats.dbc'`` but at the same time this does not fail 
``from canmatrix.formats.dbc import loads``

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```the same with 3.6, 4.0 and 4.1```
* Version of Python: 3.7
* Platform: Windows and Linux (appveyor ubuntu 2004 image)
* Did you also try this on another platform? Does it work there? -> The same error occurs on with the linux executable; I don't know about the macos executable

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

* The PyInstaller builds are found [here](https://github.com/danielhrisca/asammdf/releases/tag/6.1.2)
* The spec file is found [here](https://github.com/danielhrisca/asammdf/blob/master/asammdf.spec)
* files needed to reproduce the error are found [here](https://github.com/danielhrisca/asammdf/files/4076869/J1939-DBC-MDF4.zip) and [here](https://github.com/danielhrisca/asammdf/files/4328945/OBD2-DBC-MDF4.zip)

### Stacktrace / full error message

only the KeyError from the description

**Comment by rokm** [comment]
The "indirect" imports like the one in the line that you linked are very likely to cause the PyInstaller's module analysis to miss those modules, so they won't be automatically collected.

You can either manually add the format modules you are interested in to `hiddenimports` in the spec file, or you can use
```python
from PyInstaller.utils.hooks import collect_submodules
canmatrix_fmt_imports = collect_submodules('canmatrix.formats')
```
and append `canmatrix_fmt_imports` to `hiddenimports` if you want to have all of them collected.
