### ISSUE TITLE
Requested setting USE_I18N, but settings are not configured

### ISSUE THREAD

**Issue by xuehua312741499** [pyinstaller/pyinstaller#5470]
Hi, I used PyInstaller: 4.1 in win10 to make one django project, it had one error :

**django.core.exceptions.ImproperlyConfigured: Requested setting USE_I18N, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call
 settings.configure() before accessing settings.**

My project had been setted 'DJANGO_SETTINGS_MODULE', But I did't know why there was such a error.

![image](https://user-images.githubusercontent.com/1667046/104460848-8d390f80-55e9-11eb-9f34-1dd3b6e625fe.png)

**Comment by bwoodsend** [comment]
This is an issue tracker, not a support forum. Please take your questions to StackOverflow.
