### ISSUE TITLE
hidden import 

### ISSUE THREAD

**Issue by dennisnauta98** [pyinstaller/pyinstaller#5473]
please help 

i'm trying to use pyinstaller for the first time.
it makes a .exe file bud if i try to open it, it will show a pop-up messages that says.
failed to execute script pyibooth01_boothstrap

this is the log from my cmd:

C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION>pyinstaller -F -w --debug=all --windowed --add-data="Buret3.jpg;." --add-data="pHMeter.png;." --add-data="magnetic_stirbar3.png;." TitratieKernV5.py
193 INFO: PyInstaller: 4.0
194 INFO: Python: 3.8.6
196 INFO: Platform: Windows-10-10.0.19041-SP0
199 INFO: wrote C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION\TitratieKernV5.spec
205 INFO: UPX is not available.
213 INFO: Extending PYTHONPATH with paths
['C:\\Users\\denni\\Docs\\python\\Titration-sim\\LATEST VERSION',
 'C:\\Users\\denni\\Docs\\python\\Titration-sim\\LATEST VERSION']
256 INFO: checking Analysis
257 INFO: Building Analysis because Analysis-00.toc is non existent
258 INFO: Initializing module dependency graph...
294 INFO: Caching module graph hooks...
391 INFO: Analyzing base_library.zip ...
5026 INFO: Processing pre-find module path hook distutils from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
5032 INFO: distutils: retargeting to non-venv dir 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib'
9623 INFO: Caching module dependency graph...
9903 INFO: running Analysis Analysis-00.toc
9906 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by c:\users\denni\appdata\local\programs\python\python38-32\python.exe
10138 INFO: Analyzing C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION\TitratieKernV5.py
10324 INFO: Processing module hooks...
10327 INFO: Loading module hook 'hook-distutils.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
10336 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
10675 INFO: Loading module hook 'hook-lib2to3.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
10801 INFO: Loading module hook 'hook-PyQt5.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
11185 WARNING: Hidden import "sip" not found!
11186 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
11419 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
11918 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
12754 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
12762 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
12767 INFO: Loading module hook 'hook-xml.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
12948 INFO: Loading module hook 'hook-_tkinter.py' from 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'...
13350 INFO: checking Tree
13351 INFO: Building Tree because Tree-00.toc is non existent
13361 INFO: Building Tree Tree-00.toc
13580 INFO: checking Tree
13582 INFO: Building Tree because Tree-01.toc is non existent
13585 INFO: Building Tree Tree-01.toc
13699 INFO: Looking for ctypes DLLs
13782 INFO: Analyzing run-time hooks ...
13794 INFO: Including run-time hook 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
13803 INFO: Including run-time hook 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
13820 INFO: Including run-time hook 'c:\\users\\denni\\appdata\\local\\programs\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyqt5.py'
13849 INFO: Looking for dynamic libraries
15358 WARNING: lib not found: pywintypes38.dll dependency of c:\users\denni\appdata\local\programs\python\python38-32\lib\site-packages\win32\win32evtlog.pyd
15472 WARNING: lib not found: pywintypes38.dll dependency of c:\users\denni\appdata\local\programs\python\python38-32\lib\site-packages\win32\win32api.pyd
17390 INFO: Looking for eggs
17390 INFO: Using Python library c:\users\denni\appdata\local\programs\python\python38-32\python38.dll
17402 INFO: Found binding redirects:
[]
21603 INFO: Warnings written to C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION\build\TitratieKernV5\warn-TitratieKernV5.txt
46034 INFO: Graph cross-reference written to C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION\build\TitratieKernV5\xref-TitratieKernV5.html
46158 INFO: Appending 'datas' from .spec
46169 INFO: checking PYZ
46170 INFO: Building PYZ because PYZ-00.toc is non existent
46200 INFO: Building PYZ (ZlibArchive) C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION\build\TitratieKernV5\PYZ-00.pyz
46214 INFO: Building PYZ (ZlibArchive) C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION\build\TitratieKernV5\PYZ-00.pyz completed successfully.
46281 INFO: checking PKG
46281 INFO: Building PKG because PKG-00.toc is non existent
46285 INFO: Building PKG (CArchive) PKG-00.pkg
62887 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
63009 INFO: Bootloader c:\users\denni\appdata\local\programs\python\python38-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\runw_d.exe
63012 INFO: checking EXE
63015 INFO: Building EXE because EXE-00.toc is non existent
63022 INFO: Building EXE from EXE-00.toc
63046 INFO: Updating manifest in C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION\build\TitratieKernV5\runw_d.exe.rsi3wut8
63241 INFO: Updating resource type 24 name 1 language 0
63255 INFO: Appending archive to EXE C:\Users\denni\Docs\python\Titration-sim\LATEST VERSION\dist\TitratieKernV5.exe
63485 INFO: Building EXE from EXE-00.toc completed successfully.

if any one knows something that helps please help i'm totally stuck.

**Comment by bwoodsend** [comment]
Never debug with `--windowed`.

**Comment by dennisnauta98** [comment]
> Never debug with `--windowed`.

i have tried it with out --windowd still getting the same results

if i try to run it now it will show a messages with;

failed to execute TitrationKernV5.py
this is the main file of the simulator we have got 2 other .py files that are connected with a import in the TitratioKernV5.py file.

**Comment by bwoodsend** [comment]
Rebuild without `--windowed`. Run your program from `cmd`. Then copy/paste the error message it says in the console.

**Comment by dennisnauta98** [comment]
Thnx for the help but it was  a falt in the code with the 
Jpg en .png files
