### ISSUE TITLE
Build fails on Gitlab CI Windows runner

### ISSUE THREAD

**Issue by DeepSpace2** [pyinstaller/pyinstaller#5479]
I'm **not** sure this is a PyInstaller issue as everything is working as expected locally. However I'd love to see if we can understand where this issue comes from.

## Description of the issue
`pyinstaller script.py` results with error ```OSError: [Errno 22] Invalid argument: 'c:\\users\\gitlab_runner\\.virtualenvs\\project-generator-_focglu2\\lib\\site-packages\\PyInstaller\\bootloader\\Windows-64bit\\run.exe'```

Full trace:

```
40443 INFO: Bootloader c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
40443 INFO: checking EXE
40443 INFO: Building EXE because EXE-00.toc is non existent
40443 INFO: Building EXE from EXE-00.toc
Traceback (most recent call last):
  File "c:\python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\gitlab_runner\.virtualenvs\project-generator-_FoCGLu2\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\building\build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\building\build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "C:\GitLab-Runner\builds\tufinps\tos2\project-generator\tos2-project-generator.spec", line 33, in <module>
    console=True )
  File "c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\building\api.py", line 450, in __init__
    self.__postinit__()
  File "c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\building\datastruct.py", line 160, in __postinit__
    self.assemble()
  File "c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\building\api.py", line 541, in assemble
    self._copyfile(exe, tmpnm)
  File "c:\users\gitlab_runner\.virtualenvs\project-generator-_focglu2\lib\site-packages\PyInstaller\building\api.py", line 654, in _copyfile
    with open(infile, 'rb') as infh:
OSError: [Errno 22] Invalid argument: 'c:\\users\\gitlab_runner\\.virtualenvs\\project-generator-_focglu2\\lib\\site-packages\\PyInstaller\\bootloader\\Windows-64bit\\run.exe'
```

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: ```3.7.9```
* Platform: ```Windows-10-10.0.17763-SP0```

As mentioned, this error only happens when running on gitlab CI. When running locally (also on Windows 10) everything is working as expected.

My ```.gitlab-ci.yml```:

```
stages:
    - build

build-windows:
  stage: build
  tags:
    - windows
  script:
    - choco install python --version=3.7.9 -y
    - $env:PATH+=";C:\Python37;C:\Python37\Scripts"
    - python -m pip install pipenv
    - pipenv update
    - pipenv run pyinstaller script.py --hidden-import gitlab.v4 --hidden-import gitlab.v4.objects --onefile  --noconfirm
  artifacts:
    paths:
      - dist/script.exe
```

**Comment by r0the** [comment]
I get the same error when trying to install pyinstaller 4.2 with pip. Installing pyinstaller 4.1 works fine.

```
> py -m pip install pyinstaller==4.2
Collecting pyinstaller==4.2
  Using cached pyinstaller-4.2.tar.gz (3.6 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\stefan\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller==4.2) (0.2.0)
Requirement already satisfied: setuptools in c:\users\stefan\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller==4.2) (49.2.1)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\users\stefan\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller==4.2) (2020.11)
Requirement already satisfied: altgraph in c:\users\stefan\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller==4.2) (0.17)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\stefan\appdata\local\programs\python\python39\lib\site-packages (from pyinstaller==4.2) (2019.4.18)
Requirement already satisfied: future in c:\users\stefan\appdata\local\programs\python\python39\lib\site-packages (from pefile>=2017.8.1->pyinstaller==4.2) (0.18.2)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Users\Stefan\AppData\Local\Programs\Python\Python39\python.exe' 'C:\Users\Stefan\AppData\Local\Programs\Python\Python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\Stefan\AppData\Local\Temp\tmp37a8l6o_'
       cwd: C:\Users\Stefan\AppData\Local\Temp\pip-install-vtg69zi4\pyinstaller_7bebe8dd07b84daeb97879b49299eb3e
  Complete output (71 lines):
  running bdist_wheel
  running build
  running build_bootloader
  running build_py
  creating build
  creating build\lib
  creating build\lib\PyInstaller
  copying PyInstaller\compat.py -> build\lib\PyInstaller
  copying PyInstaller\config.py -> build\lib\PyInstaller
  copying PyInstaller\configure.py -> build\lib\PyInstaller
  copying PyInstaller\exceptions.py -> build\lib\PyInstaller
  copying PyInstaller\log.py -> build\lib\PyInstaller
  copying PyInstaller\_recursion_to_deep_message.py -> build\lib\PyInstaller
  copying PyInstaller\__init__.py -> build\lib\PyInstaller
  copying PyInstaller\__main__.py -> build\lib\PyInstaller
  running egg_info
  writing pyinstaller.egg-info\PKG-INFO
  writing dependency_links to pyinstaller.egg-info\dependency_links.txt
  writing entry points to pyinstaller.egg-info\entry_points.txt
  writing requirements to pyinstaller.egg-info\requires.txt
  writing top-level names to pyinstaller.egg-info\top_level.txt
  reading manifest file 'pyinstaller.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching 'pyinstaller-gui.py'
  no previously-included directories found matching 'bootloader\build'
  no previously-included directories found matching 'bootloader\.waf-*'
  no previously-included directories found matching 'bootloader\.waf3-*'
  no previously-included directories found matching 'bootloader\waf-*'
  no previously-included directories found matching 'bootloader\waf3-*'
  no previously-included directories found matching 'bootloader\_sdks'
  no previously-included directories found matching 'bootloader\.vagrant'
  warning: no previously-included files found matching 'bootloader\.lock-waf*'
  no previously-included directories found matching 'doc\source'
  no previously-included directories found matching 'doc\_build'
  warning: no previously-included files matching '*.tmp' found under directory 'doc'
  warning: no files found matching 'news\_template.rst'
  no previously-included directories found matching 'news'
  no previously-included directories found matching 'old'
  no previously-included directories found matching 'scripts'
  no previously-included directories found matching 'tests\scripts'
  no previously-included directories found matching '.github'
  warning: no previously-included files found matching '.*'
  warning: no previously-included files found matching '*.yml'
  warning: no previously-included files found matching '*~'
  warning: no previously-included files found matching '.directory'
  writing manifest file 'pyinstaller.egg-info\SOURCES.txt'
  creating build\lib\PyInstaller\archive
  copying PyInstaller\archive\__init__.py -> build\lib\PyInstaller\archive
  copying PyInstaller\archive\pyz_crypto.py -> build\lib\PyInstaller\archive
  copying PyInstaller\archive\readers.py -> build\lib\PyInstaller\archive
  copying PyInstaller\archive\writers.py -> build\lib\PyInstaller\archive
  creating build\lib\PyInstaller\bootloader
  creating build\lib\PyInstaller\bootloader\Darwin-64bit
  copying PyInstaller\bootloader\Darwin-64bit\run -> build\lib\PyInstaller\bootloader\Darwin-64bit
  copying PyInstaller\bootloader\Darwin-64bit\run_d -> build\lib\PyInstaller\bootloader\Darwin-64bit
  copying PyInstaller\bootloader\Darwin-64bit\runw -> build\lib\PyInstaller\bootloader\Darwin-64bit
  copying PyInstaller\bootloader\Darwin-64bit\runw_d -> build\lib\PyInstaller\bootloader\Darwin-64bit
  creating build\lib\PyInstaller\bootloader\Linux-32bit
  copying PyInstaller\bootloader\Linux-32bit\run -> build\lib\PyInstaller\bootloader\Linux-32bit
  copying PyInstaller\bootloader\Linux-32bit\run_d -> build\lib\PyInstaller\bootloader\Linux-32bit
  creating build\lib\PyInstaller\bootloader\Linux-64bit
  copying PyInstaller\bootloader\Linux-64bit\run -> build\lib\PyInstaller\bootloader\Linux-64bit
  copying PyInstaller\bootloader\Linux-64bit\run_d -> build\lib\PyInstaller\bootloader\Linux-64bit
  creating build\lib\PyInstaller\bootloader\Windows-32bit
  copying PyInstaller\bootloader\Windows-32bit\run.exe -> build\lib\PyInstaller\bootloader\Windows-32bit
  copying PyInstaller\bootloader\Windows-32bit\run_d.exe -> build\lib\PyInstaller\bootloader\Windows-32bit
  copying PyInstaller\bootloader\Windows-32bit\runw.exe -> build\lib\PyInstaller\bootloader\Windows-32bit
  copying PyInstaller\bootloader\Windows-32bit\runw_d.exe -> build\lib\PyInstaller\bootloader\Windows-32bit
  creating build\lib\PyInstaller\bootloader\Windows-64bit
  copying PyInstaller\bootloader\Windows-64bit\run.exe -> build\lib\PyInstaller\bootloader\Windows-64bit
  error: could not open 'PyInstaller\bootloader\Windows-64bit\run.exe': Invalid argument
  ----------------------------------------
  ERROR: Failed building wheel for pyinstaller
Failed to build pyinstaller
ERROR: Could not build wheels for pyinstaller which use PEP 517 and cannot be installed directly
```

**Comment by rokm** [comment]
I'd say the most likely cause is the local antivirus program removing/quarantining the bootloader file.

Today my test Windows 10 VM came up with same error: `error: could not open 'build\lib\PyInstaller\bootloader\Windows-64bit\run.exe': Invalid argument` while installing PyInstaller 4.2. And Windows defender log says it identified `Trojan:Win32/Woreflin.A!cl` and removed the file.

**Comment by rokm** [comment]
Aha, restoring VM snapshot and trying again revealed the culprit - after
`Security Intelligence Update for Microsoft Defender Antivirus - KB2267602 (Version 1.329.2358.0)` gets installed, the 4.2 bootloaders end up flagged by Windows Defender.

**Comment by DeepSpace2** [comment]
@rokm Thank you for the research! So, combining with the findings by @r0the, seems like pinning `pyinstaller==4.1` is the temp workaround...

It is also very interesting to note that I'm also randomly getting the same error (`"bad argument ... /run.exe`") when trying to install `pyinstaller 4.2` (rather than when trying to build the exe file), and sometimes everything works.

**Comment by bwoodsend** [comment]
Ah. I see Windows Defender is determined to have itself classified as malware. It installs/updates itself without your permission, fails to do what it's supposed to do, consumes large amounts of resources doing it, leaks user data to microsoft and occasionally breaks other parts of your computer.

**Comment by r0the** [comment]
Here's a workaround I tested for Windows Defender:

1. Disable real-time detection in Defender settings
2. Install pyinstaller 4.2
3. Add `..\Python39\Lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe` to exclusion list in Windows Defender ([how to](https://www.howtogeek.com/671233/how-to-add-exclusions-in-windows-defender-on-windows-10/))
4. Re-Enable real-time detection in Defender settings.

**Comment by r0the** [comment]
(Glad I use Windows only for building & testing).

**Comment by DeepSpace2** [comment]
> Here's a workaround I tested for Windows Defender:
> 
> 1. Disable real-time detection in Defender settings
> 2. Install pyinstaller 4.2
> 3. Add `..\Python39\Lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe` to exclusion list in Windows Defender ([how to](https://www.howtogeek.com/671233/how-to-add-exclusions-in-windows-defender-on-windows-10/))
> 4. Re-Enable real-time detection in Defender settings.

Thanks, but irrelevant for me as I'm using a shared runner on Gitlab CI (unless there is a way to do all that with PS commands  
😂 ).

For me, switching to 4.1 seems to have solved the issue of randomly failing builds, hopefully I won't run into issues that version 4.2 is solving.

**Comment by bwoodsend** [comment]
I'm surprised that GitLab doesn't flat out disable all antiviral software. It's definitely the norm amongst CI/CD. Otherwise, compiling anything for Windows or macOS would be a minefield of authentication errors. 

> Is it worthwhile to understand what changes between 4.1 to 4.2 is triggering this Windows Defender non-sense?

This is almost certainly just that enough people have clicked the *leave it alone!* button for the 4.1 bootloaders that Defender has learnt that it isn't malware.

**Comment by DeepSpace2** [comment]
> This is almost certainly just that enough people have clicked the _leave it alone!_ button for the 4.1 bootloaders that Defender has learnt that it isn't malware.

So to me it feels like part of the pyinstaller CI should be spinning up thousands of jobs that automate that button click 😂

**Comment by rokm** [comment]
It seems the subsequent Security Intelligence Update `1.329.2367.0` (or perhaps it was `1.329.2361.0` before it)  fixed the problem - the bootloaders from git checkout on my machine don't get flagged anymore.

**Comment by andy-held** [comment]
I uploaded the run.exe to virustotal, most scanners think it is fine, but the behavior tab seems a little unsettling to me. It states that a dll is written and registry key is set when it is executed.

https://www.virustotal.com/gui/file/d8ba55f55c2a322bfe0a535ab3822106b2ca3f6992c4234310b9a79da30f5bbb

**Comment by rokm** [comment]
> I uploaded the run.exe to virustotal, most scanners think it is fine, but the behavior tab seems a little unsettling to me. It states that a dll is written and registry key is set when it is executed.

That's the described behavior of the malware that an engine believes has identified, isn't it? If you switch between the engines, you get different behaviors...

But at any rate, you should be rebuilding your own bootloaders if you can - not only to avoid issues with trust, but also to avoid false positives on your frozen programs (since otherwise you're sharing the identical bootloader with everyone else who uses the default, pre-built ones).

**Comment by andy-held** [comment]
Yeah, uploading it several times, from the wheels temporary directory or from the final one yields different behavior.

> (Glad I use Windows only for building & testing).

**Comment by rokm** [comment]
@andy-held out of curiosity, which `run.exe` did you upload? (pyinstaller version and architecture?)

The file checksum in the linked report does not seem to match any pre-built bootloader from 4.0, 4.1, or 4.2.

**Comment by andy-held** [comment]
That was from an installed package or the wheels temporary directory, it had been quarantined by Windows Defender.

I also uploaded the windows x64 one from the 4.2 package: https://www.virustotal.com/gui/file/0367cd6d43be86912de0f30dd118087ac9e79a9b5f7440e496703b1de4c44fd7

**Comment by rokm** [comment]
Closing as the anti-virus situation should have calmed since the 4.2 release. Hopefully setting the PE checksum (#5580) will improve the situation at next release - if not, we'll be seeing new issues opened, so there's no point in keeping this one around.
