### ISSUE TITLE
Windows incorrect process status code (4294967295)

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#5480]
When running an executable compiled with PyInstaller the return code of unhandled exception is changed from 1 to 4294967295 (which probably means -1).

It is pretty easy to reproduce, this is my code:

error.py:
```
raise Exception("ERROR")
```

Now just build with `pyinstaller error.py`

And running this with:
```
p = subprocess.Popen([sys.executable, "error.py"], stderr=subprocess.PIPE, stdout=subprocess.PIPE) 
p.communicate() 
print(p.returncode)

p = subprocess.Popen([r"dist\error\error.exe"], stderr=subprocess.PIPE, stdout=subprocess.PIPE) 
p.communicate() 
print(p.returncode)
```
Output:
```
1
4294967295
```

Running with python return 1 as the returncode and with pyinstaller 4294967295.

PyInstaller: 4.2
OS: Windows
Python: 3.7.9

This only happens in windows, is this expected?

**Comment by rokm** [comment]
You're right, the return code behavior is not consistent with that of python interpreter and unfrozen script.

But this is not limited to Windows - it also happens on linux, where the return code of frozen program is 255 (0xFF), as opposed to 0xFFFFFFFF on Windows.

**Comment by arossert** [comment]
@rokm you are correct, I also tested it on MacOS and it is the same, the return code is changed from `1` to `255`.
Is this the expected behavior?
