### ISSUE TITLE
  File "importlib\resources.py", line 97, in open_binary

### ISSUE THREAD

**Issue by devlop7** [pyinstaller/pyinstaller#5482]
i have this code 
```

from nordvpn_switcher import initialize_VPN, rotate_VPN, terminate_VPN


class nord_vpn_changer:
    def __init__(self):
        self.settings = initialize_VPN(stored_settings=1)

    def get_new_ip(self):
        # print('here')
        try:
            rotate_VPN(self.settings)
        except Exception as e:
            print(e)


nvp = nord_vpn_changer()
nvp.get_new_ip()

```

when i convert it to exe by this command line 

pyinstaller --onefile nord_rand.py

it's work and i get the exd file 

but when i run it i get  this  issue 

File "importlib\resources.py", line 97, in open_binary
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\moh\\AppData\\Local\\Temp\\_MEI18082\\nordvpn_switcher\\NordVPN_options\\countrylist.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "nord_rand.py", line 16, in <module>
  File "nord_rand.py", line 6, in __init__
  File "nordvpn_switcher\nordvpn_switch.py", line 212, in initialize_VPN
  File "importlib\resources.py", line 121, in open_text
  File "importlib\resources.py", line 111, in open_binary
FileNotFoundError: 'countrylist.txt' resource not found in 'nordvpn_switcher.NordVPN_options'
[4948] Failed to execute script nord_rand

**Comment by bwoodsend** [comment]
You need to include the `countrylist.txt` file. Use `--add-data="C:\path\to\nordvpn_switcher.NordVPN_options\countrylist.txt;nordvpn_switcher\NordVPN_options"` like it [says in the docs](https://pyinstaller.readthedocs.io/en/stable/usage.html#what-to-bundle-where-to-search).

**Comment by devlop7** [comment]
this is the pat to it i do it like this 
pyinstaller --onefile --add-data="C:\Users\moh\AppData\Local\Programs\Python\Python39\Lib\site-packages\nordvpn_switcher.NordVPN_options\countrylist.txt;nordvpn_switcher\NordVPN_options" nord_rand.py


and i get this issue 



45 INFO: PyInstaller: 4.1
45 INFO: Python: 3.9.0
45 INFO: Platform: Windows-10-10.0.19041-SP0
45 INFO: wrote C:\Users\moh\Desktop\New folder\New folder\abo_ahm\dist\New folder\nord_rand.spec
45 INFO: UPX is not available.
61 INFO: Extending PYTHONPATH with paths
['C:\\Users\\moh\\Desktop\\New folder\\New folder\\abo_ahm\\dist\\New folder',
 'C:\\Users\\moh\\Desktop\\New folder\\New folder\\abo_ahm\\dist\\New folder']
61 INFO: checking Analysis
109 INFO: Appending 'datas' from .spec
Unable to find "C:\Users\moh\AppData\Local\Programs\Python\Python39\Lib\site-packages\nordvpn_switcher.NordVPN_options\countrylist.txt" when adding binary and data files

**Comment by rokm** [comment]
There's a typo in your path - you have a period in `nordvpn_switcher.NordVPN_options` instead of backslash.

**Comment by devlop7** [comment]
thanks work now thanks
