### ISSUE TITLE
PyInstaller 4.2 run.exe contains a virus?

### ISSUE THREAD

**Issue by schlomo** [pyinstaller/pyinstaller#5490]
Uploading `run.exe` from `pyinstaller-4.2.tar.gz` found at https://github.com/pyinstaller/pyinstaller/releases to [VirusTotal](https://www.virustotal.com/gui/file/0367cd6d43be86912de0f30dd118087ac9e79a9b5f7440e496703b1de4c44fd7/detection) results in a [Virus warning](https://www.virustotal.com/gui/file/0367cd6d43be86912de0f30dd118087ac9e79a9b5f7440e496703b1de4c44fd7/detection):

![image](https://user-images.githubusercontent.com/101384/105098867-041f4e00-5aab-11eb-98a7-24679a3a8d72.png)

```bash
$ shasum -b pyinstaller-4.2.tar.gz
bac8d46737876468d7be607a44b90debd60422b5 *pyinstaller-4.2.tar.gz
```

Software built with PyInstaller 4.2 also reports as a virus.

**Can it be that PyInstaller has been infected?**

#5474 and #5479 also report this.

**Comment by grajsor** [comment]
Yes, you need to gather people and flag the 4.2 bootloader as not a virus
among the vendors. This is not a PyInstaller issue, this is a virus-vendor
issue. Only YOU can solve it by contacting them.

**Comment by bwoodsend** [comment]
See #5474 and #5479. This happens every time we do a release. The dumber antiviral software which just memorize checksums take a while to catch up.

**Comment by schlomo** [comment]
How can we know if your build process hasn't been infected?

If this happens repeatedly, is there a way to build the stubs in a way that won't trigger virus warnings?

If you know this story, maybe you can first inform the virus-vendors of a new version and then release it when they know about it? That way you would probably also save yourselfs a lot of bug reports about this?

Sorry for being a bother about it, PyInstaller is a very important tool for me.

**Comment by rokm** [comment]
> How can we know if your build process hasn't been infected?

You can't. But there's nothing preventing you from rebuilding the bootloaders yourself, in an environment that you trust.

**Comment by bwoodsend** [comment]
I just tried rebuilding the bootloader using my own environment and [uploading that version](https://www.virustotal.com/gui/file/dcdb1d5c3594e579b730e043ea621f30435e7498d466e4bf8bbdf0d17fa69ab4/detection). That also is being classified as malicious. So unless both mine and Harmut's compilers are infected...

> If this happens repeatedly, is there a way to build the stubs in a way that won't trigger virus warnings?

If there was a way to make software look less malware like then all the malware authors would use it. You could try code-signing it but it's costs a lot of money.

> If you know this story, maybe you can first inform the virus-vendors of a new version and then release it when they know about it? That way you would probably also save yourselfs a lot of bug reports about this?

I suppose we probably could do this (although there are an awful lot of vendors to notify). Also it's not just a case of informing the vendors - users will still need to install security patches before their antivirus will stop jumping on our bootloader.

**Comment by The-Compiler** [comment]
> If there was a way to make software look less malware like then all the malware authors would use it.

Looks like that's not the case - see #5579.
