### ISSUE TITLE
windows defender (and other antivirus programs) warnings with pyinstaller>=4 (especially >=4.1)

### ISSUE THREAD

**Issue by rpodgorny** [pyinstaller/pyinstaller#5492]
packed .exe files created by recent versions of pyinstaller are identified by antivirus software to contain malware.

...just try to submit PyInstaller/bootloader/Windows-64bit/runw.exe (and others) to https://www.virustotal.com and you'll see for yourself.

**Comment by schlopp96** [comment]
Yes, this problem of  .py to .exe converters, including py2exe, cx-Freeze, creates a sort of negative connotation in my mind on the professionalism of Python programs not being fully recognized for reasons such as this. 

There is NO reason why creating a program, then freezing your code into a universally accepted, simple, and easy format to use (.exe) should be _THIS_ difficult & bug-ridden. This will force devs to switch to another language that may not perform the intended task in a similair or effective manner at all, unless there is some luck and excellent planning involved.

Absolutely ridiculous. Something NEEDS to be done by the creators.

**Comment by srini-pro** [comment]
same

**Comment by srini-pro** [comment]
like Furbo!s

**Comment by bwoodsend** [comment]
There's nothing we can do about dumb antiviral software. If there was some magic something we could change then malware creators would do it too and the race would start again. The best you can do is submit your applications to the antiviral software vendors as false positives.

**Comment by rpodgorny** [comment]
ok. i was thinking like whenever you build a new runner, submit it right away (so individual users of pyinstaller don't have to submit their programs).

also, even if you decide to do nothing, please keep this issue in mind for the future - being identified as malware is a breaking change (for example windows defender just "steals" the file from you straight away) so whenever you rebuild your binaries please be sure to bump the major version.

thanks!

**Comment by bwoodsend** [comment]
> ok. i was thinking like whenever you build a new runner, submit it right away (so individual users of pyinstaller don't have to submit their programs).

It's not just us submitting it. Users will need to install security updates so their antiviral software can *learn* about this new bootloader.

**Comment by rpodgorny** [comment]
> > ok. i was thinking like whenever you build a new runner, submit it right away (so individual users of pyinstaller don't have to submit their programs).
> 
> It's not just us submitting it. Users will need to install security updates so their antiviral software can _learn_ about this new bootloader.

hmmm, true. :-(

**Comment by srini-pro** [comment]
> There's nothing we can do about dumb antiviral software. If there was some magic something we could change then malware creators would do it too and the race would start again. The best you can do is submit your applications to the antiviral software vendors as false positives.

welll maybe put allow threat still waiting to be frictionless (linux too)
