### ISSUE TITLE
'Could not find the Qt platform plugin "windows" in "" ' when building a project with PySide6

### ISSUE THREAD

**Issue by leoncvlt** [pyinstaller/pyinstaller#5493]
## Description of the issue
When packaging an app which uses [PySide6](https://wiki.qt.io/Qt_for_Python) (which seems to be a recent release, December 2020), the app builds fine but upon execution it crashes with the error `qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""`.

This can be fixed by copying over the `platforms` folder from `[env]\Lib\site-packages\PySide6\plugins` into the pyinstaller dist directory (or where the executable is, if built with `--onefile`)

From googling around, it seems like people had this same problem back in the PyQt5 days, and seemed to have been fixed with 
[this](https://github.com/pyinstaller/pyinstaller/pull/3233/files) pull request. The reason this might still broken might be that all the checks in `pyinstaller/PyInstaller/utils/hooks/qt.py` use an hardcoded "PySide2" string, while the newer package has been renamed to PySide6.

That's made more likely from the fact that using [PySide2](https://pypi.org/project/PySide2/) works (noting that all documentation / homepage links for it redirect to PySide6, pretty confusing naming scheme)

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: 3.9.1
* Platform: Windows-10-10.0.19041-SP0
* Did you also try this on another platform? Does it work there? Haven't tried, but likely not

### A minimal example program which shows the error

```
import sys

import PySide6.QtGui
import PySide6.QtCore
from PySide6.QtWidgets import QApplication, QMainWindow

class MainWindow(QMainWindow):
    def __init__(self, parent=None):
        super(MainWindow, self).__init__(parent)
        self.show()

def main():
    a = QApplication(sys.argv)
    w = MainWindow()
    sys.exit(a.exec_())

if __name__ == "__main__":
    main()
```

### Stacktrace / full error message

```
qt.qpa.plugin: Could not find the Qt platform plugin "windows" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
```

**Comment by bwoodsend** [comment]
See #5414.
