### ISSUE TITLE
Frozen `platform.machine()` returns `x86_64` on Apple Silicon M1 macs

### ISSUE THREAD

**Issue by papr** [pyinstaller/pyinstaller#5494]
Issue: `platform.machine()` seems to return the result belonging to the machine that froze the program instead of the machine running the program.

This is particular problematic if one needs to run different code based on the runtime architecture. 

PyInstaller: 4.2
Python: 3.9.1 (universal2 installer)
Freeze platform: macOS 10.14.6
Runtime platform: macOS 11.1 (M1 chip)

`test_platform_machine.py`
```py
import platform

print(platform.machine())
```
> Returns the machine type, e.g. 'i386'. An empty string is returned if the value cannot be determined

https://docs.python.org/3/library/platform.html#platform.machine

Expected output: `arm64`
Actual output: `x86_64`

I do not know anything about PyInstaller internals but that also might be related to the [compatibility mode causing this issue](https://github.com/pyinstaller/pyinstaller/issues/5491#issuecomment-763589367).

Our current workaround is to use `os.uname().version` instead, which seems to behave correctly.

**Comment by rokm** [comment]
The bootloader is currently built only for x86_64.

Can you check if https://github.com/pyinstaller/pyinstaller/issues/5315#issuecomment-757339560 helps?

**Comment by papr** [comment]
This has indeed solved the issue, see https://github.com/pyinstaller/pyinstaller/issues/5315#issuecomment-764851485
