### ISSUE TITLE
_pywrap_tensorflow_internal.pyd is to big after PyInstaller pack 

### ISSUE THREAD

**Issue by roeyilan** [pyinstaller/pyinstaller#5497]
Hi,

I'm working on packing our Algo pipe Micro-services built from 4 services that are wrapping Algo API's using TensorFlow 2.3.1.
I'm using PyInstaller with a unified spec file to pack all 4 services into one folder so all services executables will use shared resources.

One of the resources is "_pywrap_tensorflow_internal.pyd" file.

The issue is that after the latest version this file size has increased from about 140 MB to 694 MB.
I did not found any related issue yet, I'm thinking that the PyInstaller has increased this file size due to our version progress.

What could be the reason?
Is there an option to decrease this file size?

System information

OS Platform: Win:
TensorFlow installed: from source
TensorFlow version: 2.3.1
Python version: 3.7.6 x64
Installed using virtualenv? pip? conda?: pip
PyInstaler version: 4.2

**Comment by rokm** [comment]
> I did not found any related issue yet, I'm thinking that the PyInstaller has increased this file size due to our version progress.
> What could be the reason?
> Is there an option to decrease this file size?

Have you checked the size of `site-packages\tensorflow\python\_pywrap_tensorflow_internal.pyd` of your tensorflow installation? PyInstaller is just copying that file, it's not enlarging it in any way...

**Comment by roeyilan** [comment]
Anything that can be done to reduce this file? Or split this file up and include only what is used?

**Comment by bwoodsend** [comment]
Nothing PyInstaller can do. That file used to be a lot smaller. I can't remember the exact version but downgrading tensorflow is probably the only thing you can do.

**Comment by bwoodsend** [comment]
You could install UPX which would allow PyInstaller to compress it.
