### ISSUE TITLE
pdfminer.six does not work properly after using Pyinstaller

### ISSUE THREAD

**Issue by gunrosen** [pyinstaller/pyinstaller#5509]
Hi there.
I am using pdfminer.six library to extract text from Japanese PDF file. It works fine when I run in development.
It means it can run with .py 
![image](https://user-images.githubusercontent.com/3174484/106103399-79f27c00-6173-11eb-9221-316ef3db6a31.png)

After I use Pyinstaller to make production (exe) version. It does not extract text. LTRect, LTLine, LTCurve can recognize but LTText, LTContainer can't. 

> pyinstaller --onefile test_pdf.py

![image](https://user-images.githubusercontent.com/3174484/106103737-f9804b00-6173-11eb-9945-b7e66ff63e4a.png)
My environment
> Windows 10 Home Single Language Version 2004 
> Python 3.9.1
> Pyinstaller 4.2
> pdfminer.six==20201018
> six==1.15.0

Pyinstaller log: [pyinstaller.log](https://github.com/pdfminer/pdfminer.six/files/5885466/pyinstaller.log)
SamplePDF file: [ADEM_3.pdf](https://github.com/pdfminer/pdfminer.six/files/5885442/ADEM_3.pdf)
Sample source code: I print text into console
```
from pdfminer.high_level import extract_pages
from pdfminer.layout import LTTextContainer
from pdfminer.layout import LTRect
import sys

print("Read file %s" % sys.argv[1])
if __name__ == '__main__':
    # print("WE TRY TO TEST")
    for page_layout in extract_pages(sys.argv[1]):
        for element in page_layout:
            if isinstance(element, LTTextContainer):
                print(element.get_text())
            elif isinstance(element, LTRect):
                pass
```

I am not sure the issue happen on pdfminer.six or pyinstaller or maybe cause of file format. But I don't know how to find out the solution for this problem.
Please give me a help with this issue. 
Thank you.

**Comment by rokm** [comment]
`pdfminer` package comes with additional data (presumably character maps) that are not packaged by PyInstaller.

To fix this, create a new custom hook:
* create a folder called `extra-hooks` 
* create a file called `extra-hooks\hook-pdfminer.py` with the following content:
```python
# hook-pdfminer.py
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('pdfminer')
```
* run PyInstaller with additional argument: `--additional-hooks-dir extra-hooks`, i.e., 
```pyinstaller --onefile --additional-hooks-dir extra-hooks test_pdf.py```
* (check that your `dist\program\pdfminer\cmap` now contains all `.gz` files)
* the test program should now parse the PDF

**Comment by bwoodsend** [comment]
Be sure to also add the `--clean` option to your pyinstaller command. PyInstaller doesn't notice hook changes so will mistakenly use a cached build.

**Comment by bwoodsend** [comment]
Fixed in (pyinstaller/pyinstaller-hooks-contrib#83).

**Comment by gunrosen** [comment]
Thank you @bwoodsend  @rokm .
It fixed.
