### ISSUE TITLE
ImportError with pyzmq on Win10

### ISSUE THREAD

**Issue by garnetw** [pyinstaller/pyinstaller#5510]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue

I am trying to build a .exe file that requires ZMQ, the resulting package can only work on windows that installed or previously installed python; when tested on a Windows machine that doesn't install Python before, this package failed.

Have tried copying libzmq.cp38-win_amd64.pyd to zmq/backends/cython, which fixed some warnings while compiling; then it reports missing dlls related to MSVCP140.dll, I have tried adding C:\Windows\System32\downlevel to the PATH variable, this fixed almost all the warnings, but there are still three warnings remained: 

8843 WARNING: lib not found: api-ms-win-core-interlocked-l1-2-0.dll dependency of D:\Python38\lib\site-packages\zmq\MSVCP140.dll
8879 WARNING: lib not found: api-ms-win-core-libraryloader-l1-2-0.dll dependency of D:\Python38\lib\site-packages\zmq\MSVCP140.dll
8911 WARNING: lib not found: api-ms-win-core-rtlsupport-l1-2-0.dll dependency of D:\Python38\lib\site-packages\zmq\MSVCP140.dll

I checked System32/downlevel folder and found api-ms-win-core-interlocked-l1-1-0.dl, api-ms-win-core-libraryloader-l1-1-0.dll, api-ms-win-core-rtlsupport-l1-1-0.dll, what's the difference between these two versions? 

Thank you.

## Context information (for bug reports)

* Output of `pyinstaller --version`:  4.2
* Version of Python:  3.7.9 and 3.8.6
* Platform: Windows 10
* Did you also try this on another platform? Does it work there?   - No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import zmq
```

### Stacktrace / full error message

```
Traceback (most recent call last):
       File "main.py", line 8, in <module>
       File "PyInstaller\loader\pyimod03_importers.py", line 531, in exec_module
       File "zmq\__init___.py", line 57, in <module>
       File "zmq\__init__.py", line 32, in _load_libzmq
ImportError: DLL load failed
[5960] Failed to execute script main
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by 000Zer000** [comment]
Could you provide more info, What MSVC version are you using ? Did you install Windows 10 SDK ?

**Comment by rokm** [comment]
> I am trying to build a .exe file that requires ZMQ, the resulting package can only work on windows that installed or previously installed python; when tested on a Windows machine that doesn't install Python before, this package failed.

You should ensure that your target machines have [VC redistributable installed](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) (which is probably also installed if you install python). As far as I can tell, PyInstaller does not manage to collect all DLLs that come from that (especially those that come in multiple, side-by-side, versions).

**Comment by garnetw** [comment]
> Could you provide more info, What MSVC version are you using ? Did you install Windows 10 SDK ?

Yes, the MSVC version I used is 1200 and I didn't install Windows 10 SDK. Are those necessary requirements? 
I tried to generate the package with PyZMQ 20.0 today, finally, it works! No warnings of missing DLLs while generating. It turns out that ZMQ 20+ doesn't work with PyInstaller on my machine currently.

**Comment by garnetw** [comment]
> > I am trying to build a .exe file that requires ZMQ, the resulting package can only work on windows that installed or previously installed python; when tested on a Windows machine that doesn't install Python before, this package failed.
> 
> You should ensure that your target machines have [VC redistributable installed](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) (which is probably also installed if you install python). As far as I can tell, PyInstaller does not manage to collect all DLLs that come from that (especially those that come in multiple, side-by-side, versions).

Thank you, I will test it on other clean machines later. 
I tried to use different version of PyZMQ packages afterwards, as far as I know, the build is successful while using PyZMQ 20 on my machine, and won't work if I upgrade to PyZMQ 21.

**Comment by rokm** [comment]
> I tried to generate the package with PyZMQ 20.0 today, finally, it works! No warnings of missing DLLs while generating. It turns out that ZMQ 20+ doesn't work with PyInstaller on my machine currently.

That's probably because different versions of pyzmq use different versions of VC runtime libraries (i.e., they were built with different version of Visual Studio). If you inspect the `msvcp140.dll` that's included in `pyzmq` package, you'll see:

msvcp140.dll in pyzmq-20.0.0:
```
...
File version: 14.0.24210.0
Product name: Microsof Visual Studio 2015
...
```

msvcp140.dll in pyzmq-21.0.2
```
...
File version: 14.16.27033.0
Product name: Microsof Visual Studio 2017
...
```

(As a side note, the pyzmq 22.0.x versions that were released earlier today do not seem to be compatible with PyInstaller yet)

**Comment by rokm** [comment]
Assuming this is solved. We've also updated our zmq hook for compatibility with zmq 22.0.x (pyinstaller/pyinstaller-hooks-contrib#98), and [our Windows tests are passing](https://github.com/rokm/pyinstaller-hooks-contrib/actions/runs/646553720). 

If you encounter any further problems with zmq (that are not caused by the lack of VC redist on target machine), please open a new issue with updated details.
