### ISSUE TITLE
Simple cmd «pyinstaller --version» fails (No module PyInstaller.utils'

### ISSUE THREAD

**Issue by ALEERQUESON2DIAS** [pyinstaller/pyinstaller#5514]
**## Description of the issue**

After a complete CLEAN installation (python 3.9.1 (32 bits) & pyinstaller 4.2) PYINSTALLER fails

*** Output of `pyinstaller --version`: ```(paste here)```**

C:\Users\ALQS2D>pyinstaller --version
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\PYTHON\Scripts\pyinstaller.exe\__main__.py", line 4, in <module>
  File "C:\Users\ANGEL\AppData\Roaming\Python\Python39\site-packages\PyInstaller\__init__.py", line 19, in <module>
    from .utils.git import get_repo_revision
ModuleNotFoundError: No module named 'PyInstaller.utils'

*** Version of Python:**   

C:\Users\ALQS2D>python --version
Python 3.9.1

*** Platform:

C:\Users\ALQS2D>
Microsoft Windows [Versión 10.0.19042.746]
(c) 2020 Microsoft Corporation. Todos los derechos reservados.

I have tried  last develop WITH NO SUCCESS

pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

**Comment by bwoodsend** [comment]
> File "C:\PYTHON\Scripts\pyinstaller.exe_main.py", line 4, in
> File "C:\Users\ANGEL\AppData\Roaming\Python\Python39\site-packages\PyInstaller_init.py", line 19, in 

Neither of those are valid files. You're installation is definitely bogus. It looks possibly have two broken installations. One as an Admin user and another under your username. You probably want to get rid of both of them. Run:
```
pip uninstall pyinstaller
```
Then run it again as administrator.

Then try:
```
pip install -U https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
to install.

If general, it's best to install Python somewhere you can access without Admin privileges.

**Comment by ALEERQUESON2DIAS** [comment]
Thanks  bwoodsend  for your answer.

I didn't use admin privileges in pyinstaller's install.

I did that you suggested: uninstall and beta install and the problem continues...

C:\WINDOWS\system32>pip install -U https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Using cached https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Requirement already satisfied: setuptools in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (52.0.0)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (2020.11)
Requirement already satisfied: altgraph in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (0.17)
Requirement already satisfied: pefile>=2017.8.1 in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (2019.4.18)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (0.2.0)
Requirement already satisfied: future in c:\python\lib\site-packages (from pefile>=2017.8.1->pyinstaller==5.0.dev0) (0.18.2)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (PEP 517) ... done
  Created wheel for pyinstaller: filename=pyinstaller-5.0.dev0-py3-none-any.whl size=2412457 sha256=b99e5ad2151e413fa76ce340b748a30fabcfb1a06ebfa5c480bd328173026583
  Stored in directory: N:\@@=ANGEL\AppData\Local\Temp\pip-ephem-wheel-cache-hov597w5\wheels\39\c0\2a\3eb6f61d427d961cd8a2d9e378a8c743147b175d79f092cf24
Successfully built pyinstaller
Installing collected packages: pyinstaller
Successfully installed pyinstaller-5.0.dev0

C:\WINDOWS\system32>pyinstaller --version
Traceback (most recent call last):
  File "c:\python\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\PYTHON\Scripts\pyinstaller.exe\__main__.py", line 4, in <module>
  File "C:\Users\ANGEL\AppData\Roaming\Python\Python39\site-packages\PyInstaller\__init__.py", line 19, in <module>
    from .utils.git import get_repo_revision
ModuleNotFoundError: No module named 'PyInstaller.utils'

C:\WINDOWS\system32>

**Comment by rokm** [comment]
Does `python -m PyInstaller --version` work or does it give the same error?

**Comment by ALEERQUESON2DIAS** [comment]
Thanks ROHM for your appointment

It gives the same error


C:\>python -m PyInstaller --version
Traceback (most recent call last):
  File "C:\PYTHON\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\PYTHON\lib\runpy.py", line 147, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\PYTHON\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\ANGEL\AppData\Roaming\Python\Python39\site-packages\PyInstaller\__init__.py", line 19, in <module>
    from .utils.git import get_repo_revision
ModuleNotFoundError: No module named 'PyInstaller.utils'

C:\>

Is a recent installation of PYTHON 3.91 with only PYINSTALLER 4.2 added


C:\>pip list freeze
Package                   Version
------------------------- ---------
altgraph                  0.17
future                    0.18.2
pefile                    2019.4.18
pip                       21.0.1
pyinstaller               4.2
pyinstaller-hooks-contrib 2020.11
pywin32-ctypes            0.2.0
setuptools                52.0.0

C:\>

**Comment by rokm** [comment]
I find it suspicious that `pip` is installing packages into `c:\python\lib\site-packages`:
```
...
Requirement already satisfied: setuptools in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (52.0.0)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (2020.11)
Requirement already satisfied: altgraph in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (0.17)
Requirement already satisfied: pefile>=2017.8.1 in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (2019.4.18)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\python\lib\site-packages (from pyinstaller==5.0.dev0) (0.2.0)
Requirement already satisfied: future in c:\python\lib\site-packages (from pefile>=2017.8.1->pyinstaller==5.0.dev0) (0.18.2)
...
```
but PyInstaller is being loaded from `C:\Users\ANGEL\AppData\Roaming\Python\Python39\site-packages\`
```
File "C:\Users\ANGEL\AppData\Roaming\Python\Python39\site-packages\PyInstaller_init.py", line 19, in
from .utils.git import get_repo_revision
ModuleNotFoundError: No module named 'PyInstaller.utils'
```

Can you check where PyInstaller files are actually installed - in `c:\python\lib\site-packages\PyInstaller` or `c:\Users\ANGEL\AppData\Roaming\Python\Python39\site-packages\PyInstaller`?

**Comment by ALEERQUESON2DIAS** [comment]
A lot of thaks Rokm for your answer.

It's in both directories as you mentioned.

I have installed and uninstalled several times the 3.9.1 version of Python form <<.msi>> Windows installable.

Probably it was a mixed. I ll have a review to quit out all instances de Python from my computer and try again.

Tnaks a lot.

**Comment by ALEERQUESON2DIAS** [comment]
Many thanks to Rokm for his guidance. I have found out what happens.
I am using the standard Windows 10 installer tool to install Python. But when it is uninstalled with the same official tool, some directories (like the one for site-packages) remains on the disk, so if it is installed again in another directory, DUPLICATES are produced.
After uninstalling, it is necessary to manually delete certain directories that remain on the disk to avoid duplication.
Now everything works correctly 

C:\>pyinstaller --version
4.2
C:\>
