### ISSUE TITLE
onefile does not work with noconsole on windows, pyinstaller 4.2

### ISSUE THREAD

**Issue by Dariusz1989** [pyinstaller/pyinstaller#5515]
Hello

So this is an exciting... issue to solve 

PySide6 + many more libe app.

Here is what I'm starting with 
1st I tried with > `pyEnv\Scripts\python.exe -m PyInstaller --noconsole runner.py`
I noticed that he would not copy any of my library files in to the runner folder. So if runner has
```
from General.stuff import someClass
```
he would not create General folder & place py files inside it... so I went to the .spec file it generated and did this >

```
print("CUR DIR : ",os.getcwd())
myDir = os.getcwd()
dataList = []
for dirPath, folderList, fileList in os.walk(myDir):
    relativePath = dirPath[len("S:\\testinstallerSource/"):]
    filePath = ""
    if len(relativePath)>0:
        relativePath = relativePath+"/"
        filePath = relativePath
    else:
        filePath="."
    if "__pycache__"not in dirPath:
        for file in fileList:
            relp = relativePath+file
            relp =relp.replace("\\","/")
            fp = filePath
            fp = fp.replace("\\","/")
            if ".pyd" in file or ".py" in file or ".dll" in file:
                                #first arg is py file, second is path inside collected app structure. Example below :
                                #(someLibary/otherLibrary/file.py, someLibrary/otherLibrary/) we now have path to py and relative path to 
                                #location of it
                dataList.append((relp,fp))
            if ".qss" in file:
                dataList.append((relp,fp))
for a in dataList:
    print(a)
print(myDir,len(dataList))

a = Analysis(['runner.py'],
             pathex=['S:\\testinstallerSource'],
             binaries=[],
             datas=dataList,
```
This would collect all .dll, py, pyd, qss files for me that I need in my project. Once I run this using
`pyEnv\Scripts\python.exe -m PyInstaller --noconsole runner.spec` < notice its spec and not py!

When I go to the folder, all files are there, and when I click on runner.exe everything works! YAY! 

So I've gone and did this as next command >
`pyEnv\Scripts\python.exe -m PyInstaller --noconsole --onefile runner.py`
This time I'm asking him to put it all in one file. 
Now same as before, when I 2x exe I get an error. The exe is about 40mb
So I go in and edit the new .spec file that was generated and add the extra dataList search I did to get all files I need.
Now this seems to "work" as I can now see that new exe is 60 mb! Which means he has included all the missing dlls/ and hopefully py/qss/pyd scripts! However when I click exe it crashes! Using debug mode provided me with strack trace equal to <NULL> which gave me zip.

However, if I do --onefile and --console ( so I enable console in one file) everything works again!!!! Which mean that a onefile without console is not able to run.

Now I read that this can be due to stdout/print issue. So I went over my entire app and remove all prints, however from what I can tell... Qt does this : 

```
C:\Users\Master>S:\01_Code\dist\runner.exe
QFactoryLoader::QFactoryLoader() checking directory path "S:/01_Code/dist/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "S:/01_Code/dist/platforms/qdirect2d.dll"
Found metadata in lib S:/01_Code/dist/platforms/qdirect2d.dll, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "direct2d"
        ]
    },
    "archreq": 0,
    "className": "QWindowsDirect2DIntegrationPlugin",
    "debug": false,
    "version": 393216
}
```
So perhaps its QT that keeps crashing it... Now I tried to run this is my runner script at top of the code>
```
import os
import sys
import traceback
import tempfile



def helper(exctype, value, tb):
    errorData = ""
    errorData = errorData + "extType : " + str(exctype)
    errorData = errorData + "value : " + str(value)
    errorData = errorData + "Traceback : " + str(traceback.format_tb(tb))
    f = tempfile.TemporaryFile(prefix="icpd__")
    f.write(errorData)
    f.close()

sys.excepthook = helper
sys.stdout = tempfile.TemporaryFile()
sys.stderr = tempfile.TemporaryFile()
```
But that did not help.

So I'm out of ideas. The debug print/error from Pyinstaller is just NULL and my app has 300 files and lots of subprocess calls/etc/etc and I've no idea how to bite it...

I have tried a new app, quick few tests, windows etc. So everything runs. This means its specific to my app, I must be calling something somewhere in an odd way and I get a crash due to it... 

Any hints how to bite it? 

TIA!

**Comment by bwoodsend** [comment]
You've totally misunderstood how PyInstaller works and how to use it. Python files are compiled, zipped then archived directly into the EXE - this is why you can't see them. All that `os.walk()`-ing is duplicating everything which will confuse the hell out of Python at runtime.

**Comment by Dariusz1989** [comment]
@bwoodsend without running the os.walk and adding paths/files the app don't run at all. When I run pyinstaller without onefile, and check content of runner folder there is no py filers/folders from my library. I don't know why that happens but pyinstaller does not check imports/add them to the projects. So I had to add them manually. Als from what I remember, any pyd file is not analysed either, so I have to add them manually & add any hidden imports they may do.

**Comment by bwoodsend** [comment]
> content of runner folder there is no py filers/folders from my library

That what I am saying. They won't be there because they're inside the exe so you can't see them. PyInstaller will collect your library if it's visible if you use it correctly.

**Comment by Dariusz1989** [comment]
> > content of runner folder there is no py filers/folders from my library
> 
> That what I am saying. They won't be there because they're inside the exe so you can't see them. PyInstaller will collect your library if it's visible if you use it correctly.

No... I was trying to say when I run `pyinstaller runner.py` with no extra commands.
This will create folder, and put all data in the folder Right? Its not zipped,packed, anything ? Then I should see my library as plain py files there, pyside, numpy, etc etc?
In that mode my library is not included. Nothing get added except for runner.py

**Comment by Dariusz1989** [comment]
@bwoodsend you say `PyInstaller will collect your library if it's visible if you use it correctly.` what does that mean ? Is there a template how that would look like? I tried to edit my imports but none of my changes did anything and pyinstaller still didn't add my files.

**Comment by Dariusz1989** [comment]
I finnaly got an error stack trace after hours of debuging!!! 

This seem to be the problem > 
`id= str(subprocess.check_output('wmic csproduct get uuid')).split('\\r\\n')[1].strip('\\r').strip()`
Gotta see how to fix it now o.O

**Comment by rokm** [comment]
> This seem to be the problem >
id= str(subprocess.check_output('wmic csproduct get uuid')).split('\\r\\n')[1].strip('\\r').strip()
Gotta see how to fix it now o.O

If you're using `subprocess` in `noconsole` build, you probably need to explicitly set `stdin` to ` subprocess.DEVNULL`. Otherwise, the spawned subprocess will inherit stdin from the parent, where it is invalid (due to lack of console).

Also, with PyInstaller 4.2, you should get traceback in one of error dialogs if you build the program with `--debug bootloader` (earlier versions did incorrectly display just NULL, though).

**Comment by Dariusz1989** [comment]
@rokm Thank you! Yeah I was on 4.1 (for some reason I rolled back last week and forgot) and now I finally got debug! But I only did debug=True, not sure how to do debug=True/ bootloader?
In any case I tried with this code>
`        id= str(subprocess.check_output('wmic csproduct get uuid'),stdin = subprocess.DEVNULL).split('\\r\\n')[1].strip('\\r').strip()`
But still erroring, I take the stdin arg does not work for check_output and I need further googling... yay! 
But when I removed the line, the app started! Wohooo! :- D

**Comment by rokm** [comment]
>  id= str(subprocess.check_output('wmic csproduct get uuid'),stdin = subprocess.DEVNULL).split('\\r\\n')[1].strip('\\r').strip()

You gave `stdin = subprocess.DEVNULL` as argument to `str()` instead of `check_output()`.

**Comment by Dariusz1989** [comment]
> > id= str(subprocess.check_output('wmic csproduct get uuid'),stdin = subprocess.DEVNULL).split('\r\n')[1].strip('\r').strip()
> 
> You gave `stdin = subprocess.DEVNULL` as argument to `str()` instead of `check_output()`.

Ah yes, you are right. But still errors :- ) I'll see if I can use popen/call instead and give it stdin there. Not sure whats up with check_output

**Comment by Dariusz1989** [comment]
Got it to run via https://github.com/pyinstaller/pyinstaller/wiki/Recipe-subprocess ! 
Will ping up if any more errors happen in this "happy" project :- ) So far looks sweet!
