### ISSUE TITLE
Pyinstaller not cleaning up tmp folder if app was force quit/terminated

### ISSUE THREAD

**Issue by Dariusz1989** [pyinstaller/pyinstaller#5518]
Hey

It could be related to this > https://stackoverflow.com/questions/60502431/files-built-using-pyinstaller-onefile-no-longer-deletes-their-temporary-mei-d

But it seems that if I go to task manager and murder my app then the temp files will remain in... temp.

Is there any fix for this or we will have to have leftovers in the temp folder?
TIA

**Comment by Dariusz1989** [comment]
As far as I can tell, on windows, it starts 2 processes, and if I kill the small process 1st then the app. The files will remain. So I take the small process is the watcher ?

**Comment by bwoodsend** [comment]
I'm afraid this has been around for ages. See #2379.

Yes there's a parent process which unpacks everything then a child process that runs your code. 

I'll close this as it's a duplicate. Feel free to make noise on #2379.
