### ISSUE TITLE
add static files into generated exe file

### ISSUE THREAD

**Issue by LordST95** [pyinstaller/pyinstaller#5522]
this is the [link](https://github.com/theskumar/python-dotenv/issues/259#issue-649073990) to someone's problem. sth same happened to me.

this is my project's structure:
```
.
├── commandHandlers
│   ├── basics.py
│   ├── __init__.py
├── dbHelper.py
├── __init__.py
├── main.py
├── .env
├── requirements.txt
├── responseTexts
│   ├── agreementResponces.py
│   ├── basicResponces.py
│   ├── __init__.py
│   ├── locales
│   │   ├── default.pot
│   │   ├── fa
│   │   │   └── LC_MESSAGES
│   │   │       ├── default.mo
│   │   │       └── default.po
│   │   └── ReadMe.md
```

And this is how I read those files:
```
# in main.py
load_dotenv(dotenv_path=".env")
```
```
# in responseTexts\basicResponces.py
def setupLanguage(lang):
    domain = 'default'
    localedir = localedir = os.path.join(os.path.abspath(os.path.dirname(__file__)), 'locales')
    translate = gettext.translation(domain, localedir, fallback=True)
    if lang:
        translate = gettext.translation(domain, localedir, fallback=True, languages=[lang])
    translate.install()
    _ = translate.gettext
    return _
```

if I print localedir before and after build, it will be 
`
...../MyProject/responseTexts/locales
`
and
`
/tmp/_MEIXPRtp4/responseTexts/locales
`

As u know, the problem caused by abstractPath and can be fixed by changing it to relative approaches and put those files (".env" and "responseTexts/") next to generated exe file, But I want to say that will be a good idea to compact .env files and locals file into the generated file as we use '--onefile' option and we except only one file as our output ;)

**Comment by 000Zer000** [comment]
Wouldn't `--add-data` solve this ? (Sorry, if this answer is stupid, I really could not understand what your problem is)

**Comment by 000Zer000** [comment]
> As u know, the problem caused by abstractPath and can be fixed by changing it to relative approaches and put those files (".env" and "responseTexts/") next to generated exe file, But I want to say that will be a good idea to compact .env files and locals file into the generated file as we use '--onefile' option and we except only one file as our output ;)

I really cannot understand what is your point. Which problem ??

**Comment by LordST95** [comment]
@000Zer000, based on docs, your previous comment(using --add-data) does the job, so this feature already included and my request should be closed, although I should say that I couldn't get it done by using bellow command:
```
pyinstaller main.py --onefile --name myApp --add-data 'responseTexts/locales:.' --add-data '.env:.'
or
pyinstaller main.py --onefile --name myApp --add-data './responseTexts/locales:.' --add-data './.env:.'
```
As one of our responsibility as a developer is helping each other in open source communities, I will close this topic after adding right command which does the job. thanks for your help and excuse me if I ask a request before reading docs completely.

**Comment by bwoodsend** [comment]
This assumes your `.env` is in the current working directory which it isn't.

```
load_dotenv(dotenv_path=".env")
```
This would break in normal Python just by not running from your project root. You should be [using \_\_file__](pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file).

**Comment by LordST95** [comment]
@bwoodsend, the better approach could be based on this [link](https://stackoverflow.com/a/42145611/4417806).

I change my code to below and everything works fine:
```
if getattr(sys, 'frozen', False):
    extDataDir = sys._MEIPASS
    load_dotenv(dotenv_path=os.path.join(extDataDir, '.env'))
else:
    extDataDir = os.getcwd()
    load_dotenv(dotenv_path=os.path.join(extDataDir, '.env'))
```

```
def setupLanguage(lang):
    domain = 'default'
    extDataDir = None
    if getattr(sys, 'frozen', False):
        extDataDir = sys._MEIPASS
    else:
        extDataDir = os.getcwd()
    localedir = os.path.join(extDataDir, 'responseTexts/locales')
    translate = gettext.translation(domain, localedir, fallback=True)
    if lang:
        translate = gettext.translation(domain, localedir, fallback=True, languages=[lang])
    translate.install()
    _ = translate.gettext
    return _
```

and build by this command:
```
pyinstaller main.py --onefile --name myApp --add-data 'responseTexts/:./responseTexts/' --add-data '.env:.'
```


As everything resolved, I close this topic B-)

**Comment by bwoodsend** [comment]
That would still break if you ran normal Python from command or you wanted to turn your main code into a library which you could use in related projects. But glad you got it working.
