### ISSUE TITLE
assertion failure at modulegraph.py", line 2752, in _scan_bytecode assert prev_insts[-1].opname == 'LOAD_CONST'

### ISSUE THREAD

**Issue by thetheo2** [pyinstaller/pyinstaller#5525]
This assertion fires while trying to package our application.

After some investigation the problematic assertion seems not to be valid for all python source.  
A compiled python file with blended import and assignment statements can trigger the assertion.  

Example below--

from invio_constants import ROOT_PATH
_locals = locals() # this is OK
import invio_search
_get_functions = { key: value for key, value in invio_search.__dict__.items() if key.startswith('get_') } # this will trigger the assertion
from invio_search import LIBRARY

I have avoided the assertion by moving all assignments below the import statements in this file.

Python version and packages are as below--

Python 3.7.6

Package                       Version
----------------------------- ---------
alabaster                     0.7.12
altgraph                      0.17
Babel                         2.9.0
certifi                       2020.12.5
chardet                       4.0.0
Cython                        0.29.21
docutils                      0.16
idna                          2.10
imagesize                     1.2.0
importlib-metadata            3.4.0
Jinja2                        2.11.3
MarkupSafe                    1.1.1
packaging                     20.9
pip                           21.0.1
pycrypto                      2.6.1
Pygments                      2.7.4
pyinstaller                   4.2
pyinstaller-hooks-contrib     2020.11
pyparsing                     2.4.7
pytz                          2021.1
requests                      2.25.1
setuptools                    53.0.0
snowballstemmer               2.1.0
Sphinx                        3.4.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        1.0.3
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.4
typing-extensions             3.7.4.3
urllib3                       1.26.3
wheel                         0.36.2
zipp                          3.4.0

**Comment by bwoodsend** [comment]
Can you provide an example which imports either standard lib libraries or ones we can install? I've created mock files invio_constants.py  invio_search.py but it works for me.

Also please use mardown's codeblocks for code examples otherwise bits of punctuation get interpreted as markup. Notice in your text that `invio_search.__dict__.items()` has become invio_search.__dict__.items().

````
```python
invio_search.__dict__.items()
```
````
Renders as
```python
invio_search.__dict__.items()
```

**Comment by bwoodsend** [comment]
It's also worth mentioning that we're switching to modulegraph2 so this will probably become irrelevant in a few months.

**Comment by thetheo2** [comment]
Hey thanks so much for your attention.  
I will take more care on the markdown going forwards.
As time permits I will try to create a mock package that demonstrates the error.  
On our side the offending file had bad style, now corrected due to this ticket.  
On your side as you note you are updating to modulegraph2 so I think this ticket can be marked 'will not do' or 'cannot reproduce' for the time being.  

Much appreciated, Ted

**Comment by bwoodsend** [comment]
Ping below if you see it again.
