### ISSUE TITLE
NOT WORKING pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz 

### ISSUE THREAD

**Issue by goddamn-manchild** [pyinstaller/pyinstaller#5526]
I've got an error when i try the command to compile the py file. It is the same error listed in this link: https://github.com/pyinstaller/pyinstaller/issues/4265

I've tried to correct the error trying this command on the terminal: `pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz`
But an error is retrieved:
`C:\Users\Sílvia>pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
  Using cached https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\SLVIA~1\AppData\Local\Temp\tmpzk3i3tq6'
         cwd: C:\Users\Sílvia\AppData\Local\Temp\pip-req-build-i1op8e4z
    Complete output (34 lines):
    Error in sitecustomize; set PYTHONVERBOSE for traceback:
    SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xed in position 0: unexpected end of data (sitecustomize.py, line 21)
    running dist_info
    creating C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info
    writing C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info\PKG-INFO
    writing dependency_links to C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info\dependency_links.txt
    writing entry points to C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info\entry_points.txt
    writing requirements to C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info\requires.txt
    writing top-level names to C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info\top_level.txt
    writing manifest file 'C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info\SOURCES.txt'
    reading manifest file 'C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching 'pyinstaller-gui.py'
    no previously-included directories found matching 'bootloader\build'
    no previously-included directories found matching 'bootloader\.waf-*'
    no previously-included directories found matching 'bootloader\.waf3-*'
    no previously-included directories found matching 'bootloader\waf-*'
    no previously-included directories found matching 'bootloader\waf3-*'
    no previously-included directories found matching 'bootloader\_sdks'
    no previously-included directories found matching 'bootloader\.vagrant'
    warning: no previously-included files found matching 'bootloader\.lock-waf*'
    no previously-included directories found matching 'doc\source'
    no previously-included directories found matching 'doc\_build'
    warning: no previously-included files matching '*.tmp' found under directory 'doc'
    no previously-included directories found matching 'old'
    no previously-included directories found matching 'scripts'
    no previously-included directories found matching '.github'
    warning: no previously-included files found matching '.*'
    warning: no previously-included files found matching '*.yml'
    warning: no previously-included files found matching '*~'
    warning: no previously-included files found matching '.directory'
    writing manifest file 'C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.egg-info\SOURCES.txt'
    creating 'C:\Users\Sílvia\AppData\Local\Temp\pip-modern-metadata-cexuawp6\pyinstaller.dist-info'
    error: invalid command 'bdist_wheel'
    ----------------------------------------
WARNING: Discarding https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz. Command errored out with exit status 1: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\SLVIA~1\AppData\Local\Temp\tmpzk3i3tq6' Check the logs for full command output.
ERROR: Command errored out with exit status 1: 'c:\python39\python.exe' 'c:\python39\lib\site-packages\pip\_vendor\pep517\_in_process.py' prepare_metadata_for_build_wheel 'C:\Users\SLVIA~1\AppData\Local\Temp\tmpzk3i3tq6' Check the logs for full command output.`

**### How do i correct the error above?**

**Comment by bwoodsend** [comment]
Can you try copying it so that the line breaks are preserved. I can't read that. Failing that redirect it to a file and upload it:
```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
 > error.log 2>&1
```
Then share or copy/paste the error.log file it created.

**Comment by rokm** [comment]
`error: invalid command 'bdist_wheel'` usually means that you need to install `wheel` into your environment. 

Unless there's another error hidden in that un-readable block of text...

**Comment by goddamn-manchild** [comment]
> `error: invalid command 'bdist_wheel'` usually means that you need to install `wheel` into your environment.
> 
> Unless there's another error hidden in that un-readable block of text...

Hi rokm!!! Thank you so much. I installed wheel and now it is working. For anyone with the same problem:

`pip install wheel`
`python -m pip install --upgrade pip setuptools wheel`

Don't forget to run the terminal as administrator.

**Comment by goddamn-manchild** [comment]
> Can you try copying it so that the line breaks are preserved. I can't read that. Failing that redirect it to a file and upload it:
> 
> ```
> pip install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
>  > error.log 2>&1
> ```
> 
> Then share or copy/paste the error.log file it created.

Thank you for your help. what @rokm suggested corrected my issue.
