### ISSUE TITLE
Pyinstaller add-data doesn't work with json

### ISSUE THREAD

**Issue by devlop7** [pyinstaller/pyinstaller#5527]
i have this code

    scope = ["https://spreadsheets.google.com/feeds", 'https://www.googleapis.com/auth/spreadsheets',
                     "https://www.googleapis.com/auth/drive.file", "https://www.googleapis.com/auth/drive"]
    
            data_json = 'creds_json.json'
            creds = ServiceAccountCredentials.from_json_keyfile_name(
                data_json, scope)
    
            client = gspread.authorize(creds)
    
            sheet = client.open("fruit").sheet1  # Open the spreadhseet
            # print('from sheet')
            sheet.append_row(['banann', 'apple'])

when i make it as a exe file by this command 

    pyinstaller  --onefile --add-data="creds_json.json;." google_sheet.py

i get this message when i run the exe

      File "oauth2client\service_account.py", line 219, in from_json_keyfile_name
    FileNotFoundError: [Errno 2] No such file or directory: 'creds.json'

**Comment by bwoodsend** [comment]
Please [read the docs](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html#using-file).

**Comment by devlop7** [comment]
it dosent work
