### ISSUE TITLE
ImportError: DLL load failed while importing cv2: The specified module could not be found

### ISSUE THREAD

**Issue by FatemehEsfahani** [pyinstaller/pyinstaller#5530]
I have installed OpenCV from source. I can import it in Spyder editor, and run object detection models using cmd windows. I want to create an exe file from my python code. Initially, I got config.py file not found when running my exe file. Then, when i use print(cv2.__file__), I get the following path: 
C:/Users/simin/anaconda3/Lib/site-packages/cv2\python-3.8\cv2.cp38-win_amd64.pyd
So, I used the following command for creating the exe file:
pyinstaller --onefile untitled3.py --paths "C:\Users\simin\anaconda3\Lib\site-packages\cv2\python-3.8"
Now, the above error does not appear. However, I get "ImportError: DLL load failed while importing cv2: The specified module could not be found" error. Does anyone know how I can solve this issue?
Version of Python 3.8 installed using anaconda, OpenCV version 4.4.0 installed using cmake (from source).
Thank you in advance for your help.

**Comment by bwoodsend** [comment]
This is an issue tracker, not a support forum. Please take your questions to StackOverflow.

**Comment by FatemehEsfahani** [comment]
Ok sorry.

**Comment by terrynx** [comment]
> I have installed OpenCV from source. I can import it in Spyder editor, and run object detection models using cmd windows. I want to create an exe file from my python code. Initially, I got config.py file not found when running my exe file. Then, when i use print(cv2.**file**), I get the following path:
> C:/Users/simin/anaconda3/Lib/site-packages/cv2\python-3.8\cv2.cp38-win_amd64.pyd
> So, I used the following command for creating the exe file:
> pyinstaller --onefile untitled3.py --paths "C:\Users\simin\anaconda3\Lib\site-packages\cv2\python-3.8"
> Now, the above error does not appear. However, I get "ImportError: DLL load failed while importing cv2: The specified module could not be found" error. Does anyone know how I can solve this issue?
> Version of Python 3.8 installed using anaconda, OpenCV version 4.4.0 installed using cmake (from source).
> Thank you in advance for your help.

请问，你解决了么
