### ISSUE TITLE
ModuleNotFoundError: No module named models.yolo

### ISSUE THREAD

**Issue by ardeal** [pyinstaller/pyinstaller#5531]
Hi, 

I clone the code from: https://github.com/ultralytics/yolov3, and run detect.py correctly on my computer.

I follow the steps below to generate exe and run it:
1) clone the code: https://github.com/ultralytics/yolov3
2) pip install pyinstaller
3) pyinstaller detect.py
4) run detect.exe <code>dist/detect</code>, I got the following issue:

```python
Traceback (most recent call last):
  File "detect_image.py", line 405, in <module>
  File "detect_image.py", line 365, in main
  File "detect_image.py", line 293, in detection_alertarea
  File "detect_image.py", line 79, in __init__
  File "models\experimental.py", line 137, in attempt_load
  File "torch\serialization.py", line 594, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "torch\serialization.py", line 853, in _load
    result = unpickler.load()
ModuleNotFoundError: No module named 'models.yolo'
[12976] Failed to execute script detect_image

```

in addition, 
detect.py could correctly run in pycharm.
i run the exe in dist/detect folder without moving it.

there is indeed a folder models, and a file named experimental.py in it. The py file could correctly used when I run 
detect.py in pycharm.

there is indeed a file name 
<pre>__init__.py</pre> 
in <code>models</code> folder of the code.

It seems that pyinstaller forgot/missed handling some py files.

**Comment by bwoodsend** [comment]
`--hiddenimport=models.yolo`

**Comment by ardeal** [comment]
It does work!
Thanks @bwoodsend

**Comment by Qinsmmoon** [comment]
@bwoodsend  Can you tell me where to put this code？ thank you

**Comment by bwoodsend** [comment]
In the command you use to build your application.
```
pyinstaller --hiddenimport=models.yolo your-code.py
```

**Comment by Qinsmmoon** [comment]
@bwoodsend  谢谢您的回答 但是我的情况可能有点不同 我使用的是一个开源的代码 使用作者自己训练的模型不会报错 然后我换成自己训练好的yolo-face模型 pt格式的权重。它出现这个错误： ModuleNotFoundError: No module named 'models.yolo' 
`Traceback (most recent call last):
  File "E:/PythonProject/FaceRecognition-master/recognition/test.py", line 375, in <module>
    detect(setOPT())  # step3
  File "E:/PythonProject/FaceRecognition-master/recognition/test.py", line 38, in detect
    model = torch.load(weights, map_location=device)['model'].float()  # load to FP32
  File "D:\Anaconda\envs\face\lib\site-packages\torch\serialization.py", line 607, in load
    return _load(opened_zipfile, map_location, pickle_module, **pickle_load_args)
  File "D:\Anaconda\envs\face\lib\site-packages\torch\serialization.py", line 882, in _load
    result = unpickler.load()
  File "D:\Anaconda\envs\face\lib\site-packages\torch\serialization.py", line 875, in find_class
    return super().find_class(mod_name, name)
ModuleNotFoundError: No module named 'models.yolo'

Process finished with exit code 1
`

**Comment by rokm** [comment]
@zzc14259174 Are you using PyInstaller at all?

**Comment by Qinsmmoon** [comment]
@rokm  no, i didn't

**Comment by rokm** [comment]
> @rokm no, i didn't

Then this is a wrong place to ask, as this is PyInstaller issue tracker, so you'll get PyInstaller-specific answers.

But if you want to load/unpickle a model from file, the packages and modules that the model is using (in this case `models.yolo`) need to be importable. So it seems you're missing yolo code that yolo-face model is using.

**Comment by Qinsmmoon** [comment]
@rokm  Thanks for your answer, I'll try another way
