### ISSUE TITLE
Minimal Qt app attempts to read other app preferences (macOS)

### ISSUE THREAD

**Issue by emlys** [pyinstaller/pyinstaller#5548]
## Description of the issue
A minimal Qt app attempts to read other app preferences in `/Users/user/Library/Containers/`.

Apologies if this is the wrong place to report this issue. This only happens when running the PyInstaller-built binaries, not when using the python package. I came across some unexpected os log messages from our app and confirmed that they still happen with a minimal Qt example (https://github.com/emlys/invest/tree/minimal-qt-test).

## Context information (for bug reports)

* Output of `pyinstaller --version`: 5.0.dev0
* Version of Python: 3.8
* Platform: macOS Catalina 10.15.6

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

To reproduce:
1. Download the latest DMG artifact from https://github.com/emlys/invest/runs/1874415487
2. Open the DMG (may have to right-click > open > open anyway to get around unidentified developer warning)
3. Open the Console app.
3. Open the example app that's in the DMG (should be a small empty window with the title "Example Launcher")
4. Search on "system policy: deny" in the Console app and see that there are several denied attempts to read user preferences:
```
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.VoiceMemos/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.archiveutility/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.Home/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.Safari/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.iChat/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.CloudDocs/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.mail/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.news/Data/Library/Preferences
Sandbox: example(55,805) deny(1) file-read-data /Users/emily/Library/Containers/com.apple.stocks/Data/Library/Preferences
```
This does not happen if the Qt event loop isn't started (if you comment out `APP.exec_()` from `launcher.py`).

**Comment by rokm** [comment]
Do those file-read-data denials still occur (or at least, are still reported) if you:

a) change the layout of your `Example.app/Contents/MacOS` so that the frozen application is not contained within subdirectory (`example_dist`), but rather directly in the `MacOS` directory (side-by-side with launcher script)? (you'll probably need to rename executable `example` to e.g. `example_` and have `Example` launcher script point to it).

b) forego the launcher script altogether. You can set the `QT_MAC_WANTS_LAYER=1` at the top of your python program, before importing PySide2, i.e.:
```python
# src/example/launcher.py
import os
os.environ['QT_MAC_WANTS_LAYER']='1'

import sys
import PySide2
...
```

At any rate, those read attempts are probably coming from Qt5 libraries, so there's nothing we can do about them...

**Comment by rokm** [comment]
Closing this as per discussion in the linked issue.

**Comment by emlys** [comment]
Thanks for the response @rokm. It still happens when I tried your suggestions and observed in unrelated apps. Definitely not a pyinstaller issue.
