### ISSUE TITLE
MacOS app displays icon for queue

### ISSUE THREAD

**Issue by codade** [pyinstaller/pyinstaller#5553]
Thanks to the community help, I was able to build an app-file of my GTK-program for MacOs with pyinstaller.
My program uses multiprocessing and a queue, which works totally fine on all systems, but in the bundled app-file this produces three icons when starting the program. I was able to figure out that two of the three icons belong to the processes, which makes total sense. This also happens while executing the source code. Strangely enough the other icon is created because of the queue and constantly bounces around (I was able to isolate that behavior through not calling the Queue function). This only happens while executing the bundled file. 
I was able to supress showing the icon representing the backgorung process via using AppKit, but unfortunately I can't supress the bouncing "queue-icon". 
Any help is highly appreciated!

Building information:
Big Sur with python 3.9.1, pygobject3 and gtk+3 via homebrew. Queue is used from multiprocessing package; freeze_support is enabled.

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by rokm** [comment]
And most importantly, please provide a minimal self-contained example that exhibits this issue. (Or if the application in question is open source and relatively easy to set up, that works too).

**Comment by codade** [comment]
Thanks for your answers. I have to admit that I'm not a Mac user and used a friend's one. I did a fresh Homebrew install, so everthing should be in the newest possible version. Furthermore what I discovered is not really a bug. The program runs absolutely fine as bundled package. It's more like an aesthetic issue as I'd rather be able to only display one icon. Below you'll find addtional info:

Context information (for bug reports)

* Output of `pyinstaller --version`: 4.2
* Version of Python: 3.9.1
* Platform: OS X Big Sur
* Did you also try this on another platform? Does it work there? Yes it perfectly works on all platforms. It's more like a Mac specific icon displaying issue.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)
Didn't try without UPX and with debug mode on, yet.

### A minimal example program which shows the error
The issue only occurs in the packaged app, not while executing source code.
I haven't got a Mac to test my minimal example, but since I tried commenting out parts of my code and figured out that calling the Queue function leads to a second icon, I guess this code part should be sufficient to reproduce it. I left everything out which seemed not relevant, including the subprocess. 
The line **"progressqueue = mtp.Queue()"** lead to the second icon in my Mac app-bundle.

```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib
import multiprocessing as mtp

PATH_ICON = 'KYSA-Icon_64.icns' 
'''shouldn't matter in my opionon, but for the sake of completeness the original can be found here: https://codeberg.org/codade/KYSA/src/branch/main/suppldata/KYSA-Icon_64.icns'''

class MainWindow(Gtk.ApplicationWindow):
    def __init__(self):
        Gtk.Window.__init__(self, title="KYSA")
        self.connect("delete_event", self.close_window)
        self.set_position(Gtk.WindowPosition.CENTER)
        self.set_resizable(False)
        self.set_default_icon_from_file(PATH_ICON)#
        self.show_all()
    
    def close_window(self, widget, origin):

        Gtk.main_quit()

if __name__ == '__main__':

    mtp.freeze_support()
    progressqueue = mtp.Queue() #<-- calling the Queue function causes another icon in the Mac app-bundle
    win = MainWindow()
    Gtk.main()

```

### Stacktrace / full error message

No error reported

**Comment by rokm** [comment]
That second bouncing icon is coming from the `resource_helper` tracking process, which is spawned when a multiprocessing resource (in this case the `Queue`) is created.

I think this could be avoided by simply ensuring that `mtp.freeze_support` is called at the very top of the entry-point script, i.e., rearranging your sample program as follows:
```python
import multiprocessing as mtp
if __name__ == '__main__':
    mtp.freeze_support()

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib

PATH_ICON = 'KYSA-Icon_64.icns' 

class MainWindow(Gtk.ApplicationWindow):
    def __init__(self):
        Gtk.Window.__init__(self, title="KYSA")
        self.connect("delete_event", self.close_window)
        self.set_position(Gtk.WindowPosition.CENTER)
        self.set_resizable(False)
        self.set_default_icon_from_file(PATH_ICON)#
        self.show_all()
    
    def close_window(self, widget, origin):
        Gtk.main_quit()

if __name__ == '__main__':
    progressqueue = mtp.Queue() #<-- calling the Queue function causes another icon in the Mac app-bundle
    win = MainWindow()
    Gtk.main()
```

This way, the spawned multiprocessing helper programs/processes, which are using the same executable (and hence the same entry point script) as your main program, will avoid importing Gtk, which, as afar as I can tell, is what puts the process in foreground and gives it icon in dock.

**Comment by codade** [comment]
Thank you very much for the trick, it does the job and supresses the second icon. 
Nevertheless it seems to also supress the communication between the two processes. Trying setting the freeze_support at the very top leads to a hang up in my program as the other process is not receiving messages sent via the queue. This is very weird.
Is there a way to normally create the icon and to hide it after generation? At least with my second process I was able to withdraw the icon via AppKit, see below (Queue code is left out):
```
import gi
gi.require_version('Gtk', '3.0')
from gi.repository import Gtk, GLib
import multiprocessing as mtp

PATH_ICON = 'KYSA-Icon_64.icns' 
'''shouldn't matter in my opionon, but for the sake of completeness the original can be found here: https://codeberg.org/codade/KYSA/src/branch/main/suppldata/KYSA-Icon_64.icns'''

class MainWindow(Gtk.ApplicationWindow):
    def __init__(self):
        Gtk.Window.__init__(self, title="KYSA")
        self.connect("delete_event", self.close_window)
        self.set_position(Gtk.WindowPosition.CENTER)
        self.set_resizable(False)
        self.set_default_icon_from_file(PATH_ICON)#
        self.show_all()
    
    def close_window(self, widget, origin):

        Gtk.main_quit()

class SecondWindow(Gtk.ApplicationWindow):
    def __init__(self):
        Gtk.Window.__init__(self, title="Progress")
        self.connect("destroy", Gtk.main_quit)
        main_box = Gtk.Box(orientation=Gtk.Orientation.VERTICAL)
        self.progressbar = Gtk.ProgressBar()
        self.progressbar.pulse()
        main_box.pack_start(self.progressbar, True, True, 0)
        self.show_all()

class ProgressProcess(mtp.Process):
    '''Progressbar Subprocess'''
    def __init__(self, queue):
        mtp.Process.__init__(self)
        self.queue = queue

    def run(self):
        import gi
        from gi.repository import Gtk, GLib

        import AppKit
        NSApplicationActivationPolicyProhibited = 2
        AppKit.NSApp.setActivationPolicy_(NSApplicationActivationPolicyProhibited)
        Gtk.main()

if __name__ == '__main__':

    mtp.freeze_support()
    progressqueue = mtp.Queue() #<-- calling the Queue function causes another icon in the Mac app-bundle
    progressbar = ProgressProcess(progressqueue)
    progressbar.start()
    win = MainWindow()
    Gtk.main()
```

**Comment by rokm** [comment]
> Is there a way to normally create the icon and to hide it after generation? At least with my second process I was able to withdraw the icon via AppKit

I suppose you could try modifying [`_freeze_support()`](https://github.com/pyinstaller/pyinstaller/blob/c24117a98f4322de861f62019fb3c3c869a85245/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L24) implementation in PyInstaller's multiprocessing rthook to include those `AppKit` calls as well.

**Comment by rokm** [comment]
I did some more testing with my own example. The catch is that you need to call `multiprocessing.freeze_support()` after defining your Process class, otherwise you'll get an error about it not being available when multiprocessing attempts to spawn the worker process.

The example below updates the UI with monotonically-increasing counter values that are received via Queue from a worker process. If `freeze_support()` is called in its own block at the top (but after `CounterProcess` is defined, the application gets one icon on the dock. If this block is commented and instead `freeze_support()` is called in the block at the bottom, the application gets three icons (one for main process, one for worker process, and one for resource_tracker helper process).

(As a side note, I don't know what your full `ProgressProcess` implementation looks like, but I find it suspicious that you should need to use `Gtk` functions inside it. And having imported Gtk in there is probably the reason why you need to suppress the icon for that worker process in the first place...).

```python
import multiprocessing

class CounterProcess(multiprocessing.Process):
    def __init__(self, queue):
        super().__init__()
        self.queue = queue
        self.counter = 0

    def run(self):
        import time

        while True:
            time.sleep(1)
            print(f"Submitting value: {self.counter}")
            self.queue.put(self.counter)
            self.counter += 1

# NOTE: must be called after CounterProcess is defined!
if __name__ == '__main__':
    multiprocessing.freeze_support()

import gi
gi.require_version('Gtk', '3.0')
from gi.repository import GLib, Gtk

class MainWindow(Gtk.ApplicationWindow):
    def __init__(self, queue):
        super().__init__(title="Multiprocessing counter example")
        self.connect("delete_event", self.close_window)

        self.set_default_size(800, 600)

        hbox = Gtk.Box(spacing=10)
        hbox.set_homogeneous(False)

        label = Gtk.Label(label="Counter: ")
        hbox.pack_start(label, True, True, 0)

        self.labelCount = Gtk.Label()
        hbox.pack_start(self.labelCount, True, True, 0)

        self.add(hbox)

        # Update in idle function
        self.queue = queue
        GLib.idle_add(self.update_counter)

        self.show_all()

    def close_window(self, widget, origin):
        Gtk.main_quit()

    def update_counter(self):
        try:
            value = self.queue.get_nowait()
        except Exception:
            return True

        print("Received value:", value)
        self.labelCount.set_text(f"{value}")

        return True

if __name__ == '__main__':
    #multiprocessing.freeze_support()
    # Queue for IPC
    queue = multiprocessing.Queue()
    # Counter process
    counter = CounterProcess(queue)
    counter.start()
    # Main window
    win = MainWindow(queue)
    # Main loop
    Gtk.main()
    # Cleanup
    counter.kill()
    counter.join()
```

**Comment by codade** [comment]
Thanks Rok. Unfortunately adding the freeze_support after the class definition didn't change anything with my code. I guess you're right, that the problem comes with using Gtk in the second process. The ProgressProcess basically displays a process bar and prints message dialogs to the user. So actually no big deal. I tried this without multiprocessing, but the main process produces a bunch of plots and this lead to X-Server crash downs on my Linux. I'd rather not open `Gtk` within the second process, but since this construction works stable in Windows and Linux, I stuck to it. So probably I have to live with the second icon bouncing.

**Comment by rokm** [comment]
> Unfortunately adding the freeze_support after the class definition didn't change anything with my code.

But you're probably seeing an error of some sort? (Probably not in the .app bundle as it has no console, but if you run the `onedir` version?)

> The ProgressProcess basically displays a process bar and prints message dialogs to the user. So actually no big deal. I tried this without multiprocessing, but the main process produces a bunch of plots and this lead to X-Server crash downs on my Linux. I'd rather not open Gtk within the second process, but since this construction works stable in Windows and Linux, I stuck to it. So probably I have to live with the second icon bouncing.

So you're displaying GUI in the secondary process? While a bit unorthodox (I guess usually you'd go for submitting progress updates from your worker process or thread and update the UI in the main thread of the main process), I guess that shouldn't be problematic per-se. I think you should still be able to defer Gtk imports in both main program and your secondary process to ensure that the third process (the helper), which will use the same entry point and end up in `_freeze_support` implementation never sees any Gtk imports during its execution. (But yes, if you are using Gtk in secondary process, then you'll need to suppress icon there, as you're doing now).

**Comment by codade** [comment]
Thanks Rok. No, I didn't see an error.
I restructured my code, so that the GUI is only being displayed in the first process. Since I'm importing the GUI class as well as the classes for data manipulation in the second process from other scripts, the only thing that really helped supressing the icon for the Queue is importing those classes just shortly before they are used. Nevertheless this creates a second icon for the worker process the minute I'm starting the script import.

So basically my script looks like that (I left out all irrelevant code):

```
import platform
import multiprocessing as mtp

class PlottingProcess(mtp.Process):
    def __init__(self, queue):

        mtp.Process.__init__(self)
        self.queue = queue

    def run(self):    
        
        self.queue_waiting()

    def queue_waiting(self):
       
        while True:
            try:
                msg, data = self.queue.get(block=True, timeout=0.15)

            except Exception:
                continue

            if msg == 'start_export':
                
                self.start_exportprocess(data)
                break
 
    def start_exportprocess(self, data):
        from basefunctions import plot_preprocessor as pltp <-- this import creates an icon which I then have to withdraw. I can't call the import earlier (i.e. with the process start) because then I'll get three icons.
        
        #hide icon in Mac which is generated after import
        if platform.system() == 'Darwin':
            import AppKit 
            AppKit.NSApp.setActivationPolicy_(2)

           '''In this part a class from pltp will be initialized and relevant methods executed'''


if __name__ == '__main__':

    mtp.freeze_support()

    #set variables
    progressqueue = mtp.Queue() 

    data_proc = DataProcess(progressqueue) 
    data_proc.start()

    from basefunctions import gui_classes as guicl    #<-- calling that earlier causes creation of three icons
    import gi
    gi.require_version('Gtk', '3.0')
    from gi.repository import Gtk
    
    win = guicl.MainWindow(progressqueue)
    Gtk.main()
    data_proc.terminate()
    data_proc.join()
```
The second queue is called inside the GUI class in the gui_classes script. So with that code I'm able to start with one icon without an icon for the queue, but a second one will be displayed as soon as the import in the DataProcess is called (which I'm withdrawing immediatly after generation). As it seems I can't import other scripts at the very beginning of this script as it causes three icons, although only in the "gui_classes" script `Gtk, Glib` is imported to create GUI.

I guess I close the issue
