### ISSUE TITLE
Having trouble with auto-py-to-exe

### ISSUE THREAD

**Issue by RickyAsbury** [pyinstaller/pyinstaller#5556]
I'm having trouble with my .exe I used auto py-to-exe and I'm still having problems here's a screenshot from my raspberrypi 4 running windows 10 let me know if you need my code too
![20210213_181840](https://user-images.githubusercontent.com/75904443/107864337-2d709700-6e29-11eb-8886-7dd7cc030aaa.jpg)

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by rokm** [comment]
Looks like the resources from `pygame_menu` are not collected, and hence the font is missing. Which probably means you're using `pygame_menu` older than 3.5.2, which added support for pyinstaller and should automatically bundle those resources.

Either upgrade `pygame_menu` to version 3.5.2 or later, or ensure that `pygame_menu\resources` is collected (either via --add-data command-line switche, or using `PyInstaller.utils.hooks.collect_data_files` function in either your spec file or in custom hook).

**Comment by RickyAsbury** [comment]
No I figured it out the files in the said directory didn't place
pygame_menu in the directory so in order to fix it I simply had to copy and
paste the pygame_menu folder to the directory
