### ISSUE TITLE
The exe file generated by PyInstaller does not work when importing numpy.linalg.pinv module

### ISSUE THREAD

**Issue by farhanalfin** [pyinstaller/pyinstaller#5557]
I am working over a project using numpy library, using python 3.9 32 bit and pycharm is working, but when I convert it to exe using pyinstaller the exe does not work. To debug I created a simple program, the exe of this program does not work 
my system is windows 10 64 
converting command pyinstaller sim_np.py

the error
Application Error The Exception Unknown Software Exception 0xC06D007E

import numpy as np

from numpy.linalg import linalg
a = np.array([[1., 2.], [3., 4.]])

print(linalg.pinv)

print(linalg.pinv(a))

1799 INFO: PyInstaller: 4.2
1799 INFO: Python: 3.8.5 (conda)
1799 INFO: Platform: Windows-10-10.0.19041-SP0
1799 INFO: wrote C:\Users\Farhan Alfin\pycharmprojects\flour_color\sim_np.spec
1815 INFO: UPX is not available.
1815 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Farhan Alfin\\pycharmprojects\\flour_color',
 'C:\\Users\\Farhan Alfin\\pycharmprojects\\flour_color']
1884 INFO: checking Analysis
2037 INFO: checking PYZ
2150 INFO: checking PKG
2154 INFO: Building because C:\Users\Farhan Alfin\pycharmprojects\flour_color\build\sim_np\sim_np.exe.manifest changed
2154 INFO: Building PKG (CArchive) PKG-00.pkg
2232 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
2235 INFO: Bootloader c:\programdata\anaconda3\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
2236 INFO: checking EXE
2238 INFO: Building because icon changed
2239 INFO: Building EXE from EXE-00.toc
2245 INFO: Copying icons from ['c:\\programdata\\anaconda3\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
2281 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
2281 INFO: Writing RT_ICON 1 resource with 3752 bytes
2282 INFO: Writing RT_ICON 2 resource with 2216 bytes
2282 INFO: Writing RT_ICON 3 resource with 1384 bytes
2282 INFO: Writing RT_ICON 4 resource with 37019 bytes
2282 INFO: Writing RT_ICON 5 resource with 9640 bytes
2282 INFO: Writing RT_ICON 6 resource with 4264 bytes
2282 INFO: Writing RT_ICON 7 resource with 1128 bytes
2289 INFO: Appending archive to EXE C:\Users\Farhan Alfin\pycharmprojects\flour_color\build\sim_np\sim_np.exe
2299 INFO: Building EXE from EXE-00.toc completed successfully.
2305 INFO: checking COLLECT
2308 INFO: Building COLLECT COLLECT-00.toc
12951 INFO: Building COLLECT COLLECT-00.toc completed successfully.

**Comment by bwoodsend** [comment]
This was probably fixed in #5168. Can you retry with the development version?

```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Then rebuild but add the `--clean` option.
