### ISSUE TITLE
PyInstaller not installed correctly although no error during installation

### ISSUE THREAD

**Issue by ctlkkc** [pyinstaller/pyinstaller#5566]
I am on Windows and using Anaconda Python 3.8:
```pip 20.2.4 from C:\ProgramData\Anaconda3\lib\site-packages\pip (python 3.8)```

 I have tried to install pyinstaller:

```
(base) C:\Users\user1>pip install pyinstaller --upgrade
......
Processing c:\users\user1\appdata\local\pip\cache\wheels\20\4a\2c\2ed3296fdad9efddb0c1e0c10666358254423faa2108dee5c7\future-0.18.2-py3-none-any.whl
Installing collected packages: pywin32-ctypes, future, pefile, setuptools, altgraph, pyinstaller-hooks-contrib, pyinstaller
Successfully installed altgraph-0.17 future-0.18.2 pefile-2019.4.18 pyinstaller-4.2 pyinstaller-hooks-contrib-2020.11 pywin32-ctypes-0.2.0 setuptools-53.0.0
```

The PyInstaller folder was added to my site-packages folder:

```
(base) C:\Users\user1\AppData\Local\python-packages>ls -l | grep PyInstaller
drwxrwxrwx   1 user     group           0 Feb 19 18:21 PyInstaller
```

But there is no script created in Anaconda Script folder, all the below command also failed:

```
(base) C:\ProgramData\Anaconda3\Scripts>ls -l | grep -i pyinstaller
[nothing]
(base) C:\ProgramData\Anaconda3\Scripts>pyinstaller
'pyinstaller' is not recognized as an internal or external command,
operable program or batch file.
(base) C:\ProgramData\Anaconda3\Scripts>PyInstaller
'PyInstaller' is not recognized as an internal or external command,
operable program or batch file.
(base) C:\ProgramData\Anaconda3\Scripts>python -m pyinstaller
C:\ProgramData\Anaconda3\python.exe: No module named pyinstaller
(base) C:\ProgramData\Anaconda3\Scripts>python -m PyInstaller
C:\ProgramData\Anaconda3\python.exe: No module named PyInstaller
```

There is no error in pip.log too, I don't know other ways that pyinstaller can be called or troubleshoot if it is actually installed. I really need pyinstaller and could someone please help? Thanks.

**Comment by bwoodsend** [comment]
It looks like anaconda is installed as admin but pyinstaller is installed as a regular user. This shouldn't matter but I wouldn't be surprised if it does. I guess you could try installing pyinstaller in an admin `cmd`. This looks like a conda issue - not pyinstaller.

**Comment by ctlkkc** [comment]
> It looks like anaconda is installed as admin but pyinstaller is installed as a regular user. This shouldn't matter but I wouldn't be surprised if it does. I guess you could try installing pyinstaller in an admin `cmd`. This looks like a conda issue - not pyinstaller.

@bwoodsend I don't think the missing exe in Scripts is related to the anaconda installation, it behaved the same when installed under my username. But one thing could be worth mentioning - the user is not windows administrator. I wonder that could be a problem? or is it reproducible if you debug? 

Thanks!

**Comment by bwoodsend** [comment]
I can't reproduce this. I'm afraid your the only person in any position to solve this. Presumably it's some mismatch in environments. Try looking at the outputs of:
- `python -VV`
- `pip -VV`
- `where python`
- `where pip`
- `pip show PyInstaller`
- `set PYTHONPATH`
- `set PATH`
And see if you can spot any inconsistencies.
