### ISSUE TITLE
GLX_ERROR while running executable in different distros

### ISSUE THREAD

**Issue by darpan5552** [pyinstaller/pyinstaller#5573]
I created a basic program with [kivy](http://kivy.org) GUI framework, then built linux executable with PyInstaller on Zorin OS. It works fine there without any errors, but when same executable ran on Linux Mint, it throws GLX error.
The code independently is running fine on all distros, also executables created by other methods are working fine on all distros. I further confirm that GLX libraries are properly installed as no errors encounterd while running `glxgears` command.

[Logs Attached](https://pastebin.com/XmDdMuQQ)

**Comment by rokm** [comment]
> libGL: MESA-LOADER: failed to open /usr/lib/x86_64-linux-gnu/dri/radeonsi_dri.so: /tmp/_MEIyJ9SnR/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /lib/x86_64-linux-gnu/libLLVM-11.so.1)

Welcome to the wonderful world of cross-distribution ABI incompatibility... 

The target system is using newer `glibc` version than the system where the program was frozen. Therefore, `libstdc++.so.6` that was collected from the build system is missing symbols required by DRI drivers on the target system, preventing them to load. The way to work around this is to either remove the bundled `libstdc++.so.6` (should be doable in a `onedir` build, less so in a `onefile` build), or by forcing the use of system's `libstdc++.so.6` via `LD_PRELOAD`.

**Comment by darpan5552** [comment]
@rokm 

**2 simple questions:**
Does this ABI incompatibility also exists in windows executables? 
What if i recommend users to use wine to eliminate incompatibility issues?

**A suggestion:**
This had been suggested by many users, root of onedir should contain only executable file. Currently there are more than 40 files in main directory, it becomes so hard to find executable file. I believe it can be achieved simply via symlinks.

**Comment by rokm** [comment]
> @rokm
> 
> **2 simple questions:**
> Does this ABI incompatibility also exists in windows executables?

Well, there's always a chance for ABI incompatiblity when you're dealing with shared libraries, but Windows have quite stable ABI for their base libraries. Also, unified VC runtime for VS2015, 2017 and 2019 helps a lot in that respect. Of course, you might still run into corner cases where an application frozen on a up-to-date version of Windows 10 won't run on older version of Windows 10 or where the target system does not have VC runtime installed.

But the situation is better than when freezing for linux, where each distribution has their own version of `glibc` and other base libraries (which could also be distro-patched for distro-specific behavior, e.g., search paths for config and data files).

> What if i recommend users to use wine to eliminate incompatibility issues?

I take it running from source on linux is out of question? (Or distributing the application unfrozen for main distributions, via their packaging systems?)

Using wine would basically serve as platform normalization, but it might introduce other (wine-related) issues.

Perhaps AppImage or Flatpak might do the trick if you're after "universal" linux build (especially later, as it provides a common runtime)?

> 
> **A suggestion:**
> This had been suggested by many users, root of onedir should contain only executable file. Currently there are more than 40 files in main directory, it becomes so hard to find executable file. I believe it can be achieved simply via symlinks.

Hmmm... well, to me, this sounds like a detail that's best handled on the user's side, as they know best what the preferred final layout should be (e.g., whether they're bundling the frozen application with an installer that will create desktop shortcut/launcher; whether they're creating an AppImage out of the frozen application; etc.).

Renaming `dist/program` directory and creating a symlink that points to `dist/renamed_program/program` is rather straightforward to do, if that's the preferred layout. If you want it to be an option in PyInstaller, you could open a feature request, and see what other devs think about it.

**Comment by darpan5552** [comment]
Feature request #5575 opened
