### ISSUE TITLE
Unable to find "/Library/Python/3.8/include/pyconfig.h"

### ISSUE THREAD

**Issue by door5719** [pyinstaller/pyinstaller#5582]
mac11.01 python3.8.2（install with Command_Line_Tools_for_Xcode_12.3.dmg）
when i use : pyinstaller -F player.py
the error like 
.....
6067 INFO: Loading module hook 'hook-sysconfig.py' from '/Users/ddllmac11/Library/Python/3.8/lib/python/site-packages/PyInstaller/hooks'...
Unable to find "/Library/Python/3.8/include/pyconfig.h" when adding binary and data files.This would mean your Python installation doesn't
come with proper library files. This usually happens by missing development
package, or unsuitable build parameters of Python installation.
* On Debian/Ubuntu, you would need to install Python development packages
  * apt-get install python3-dev
  * apt-get install python-dev
* If you're building Python by yourself, please rebuild your Python with
`--enable-shared` (or, `--enable-framework` on Darwin)

how to deal with it?

**Comment by bwoodsend** [comment]
How did you install Python?

**Comment by door5719** [comment]
> How did you install Python?

I solve this proble by using brew install python  。Thanks

**Comment by sebkraemer** [comment]
It's still an issue for me. I tried to satisfy pyinstaller with a brewed python installation, but it still fails the same way, probably because Apples dev tools ship python 3.8 while brew now installs 3.9.

Could we reopen the issue?

**Comment by bwoodsend** [comment]
#5218 should fix this anyway.

**Comment by sebkraemer** [comment]
Just a side note for someone else coming here with the same issue. Pyinstaller run worked fine when running from inside a virtualenv, not sure why.
