### ISSUE TITLE
32 bits windows service not able to start on win 2008 sp 2 64 bits

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#559]
**Original date**: 2012/05/29
**Original reporter**: *huy DOT nguyen AND emc DOT  COOM *

32 bits windows service not able to start on win 2008 sp 2 64 bits. It works fine under 32 bits systems only, but when we tried to install it on a 64 bits systems, it does not start.

The description for Event ID 3 from source nsrmqd cannot be found. Either the component that raises this event is not installed on your local computer or the installation is corrupted. You can install or repair the component on the local computer.

If the event originated on another computer, the display information had to be saved with the event.

The following information was included with the event: 

Traceback (most recent call last):
  File "D:\Ibis\1_8\ucas\nsrmq\target\build\pyi.win32\nsrmqd\outPYZ1.pyz/win32serviceutil", line 806, in SvcRun
  File "<string>", line 105, in SvcDoRun
error: (0, 'RegisterEventSource/ReportEvent', 'No error message is available')

the message resource is present but the message is not found in the string/message table

**Comment by jimying** [comment]
How fix?  I  now use the development version,   the same  error.

**Comment by jimying** [comment]
I see pywin32 source code,  I think that  it's  bug of the function "LogMsg". Please not use this function to report event.
