### ISSUE TITLE
Modules

### ISSUE THREAD

**Issue by Edward-Peng** [pyinstaller/pyinstaller#5598]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when it uses all of the modules.

**Describe the solution you'd like**
Read the file and look for signs of modules.

**Describe alternatives you've considered**
Make sure that it won't use every modules that exist.

**Additional context**
Displays a giant log.

**Comment by Edward-Peng** [comment]
<h1>Response Needed</h1>
<p>Someone else must reply.</p>

**Comment by bwoodsend** [comment]
I suggest you look at the href file located under `build/[your-project-name]/href-[your-project-name].html` which will show you why so much gets collected.
