### ISSUE TITLE
Option to use wt.exe over cmd.exe for console output on Windows

### ISSUE THREAD

**Issue by Jackbennett** [pyinstaller/pyinstaller#5602]
**Is your feature request related to a problem? Please describe.**

Windows terminal text rendering is way faster, supports unicode(emoji) and in general is just great.

**Describe the solution you'd like**

`<program.spec> exe = EXE( ... console=True)` just launch wt.exe for windows terminal host if it's present.

**Describe alternatives you've considered**
If changing the default is too extreme any cross-platform suitable config item would be fine to opt-into.

**Additional context**
I searched around the issues, only other thing I came across is a stackoverflow question https://stackoverflow.com/questions/66136992/how-to-make-a-pyinstaller-executables-console-the-windows-terminal-instead-of-t but sorry if I missed a prior issue.

**Comment by bwoodsend** [comment]
Do other command line applications launch in this Windows terminal? It sounds like something which should be configured on the OS rather than anything on PyInstaller's end. Unix has a default shell configuration. I've never heard of any such option or flag on Windows. I guess you could write a wrapper program which calls `wt your-program.exe`.

**Comment by Jackbennett** [comment]
I've got a little batch->pwsh wrapper to kick it off and set an ENV variable form.

Unless there's a pre-launch hook I can compile in that I've missed in the docs? Happy to write this in python.

```powershell
$env:SETTING = 'dev-switch'
$term = get-command 'wt'

if ($term){
    Start-Process $term -ArgumentList @("-d $pwd",  './myProgram.exe')

} else {
    Start-Process './myProgram.exe'
}
```

No other programs launch native in win terminal I haven't reconfigured windows to do so (don't really want install instructions to do that either)

Maybe it's not pyinstallers' problem, I found there's an included run.exe I presume is used to initial the console?

**Comment by rokm** [comment]
> Maybe it's not pyinstallers' problem, I found there's an included run.exe I presume is used to initiate the console?

`run.exe` is bootloader for console applications, i.e., it's compiled with `/SUBSYSTEM:CONSOLE` option (as opposed to `runw.exe` that's compiled with `/SUBSYSTEM:WINDOWS` and has no console). 

However, the actual opening of console window is done by Windows itself, same as for other console-enabled applications.

**Comment by Jackbennett** [comment]
Thanks for the background on `run.exe` looks like I'll package a `.lnk` with the exe to use the desired terminal and leave it up to users. 

I found the root issue for wt is https://github.com/microsoft/terminal/issues/492 with a cheeky preview on https://github.com/microsoft/terminal/pull/7489#issuecomment-790840343
