### ISSUE TITLE
ModuleNotFoundError: No module named 'dns'

### ISSUE THREAD

**Issue by jimwangzx** [pyinstaller/pyinstaller#5609]
My python code imports "resolver", "reversename" like this:
from dns import resolver, reversename

My code runs normally

But when I use pyinstaller convert the code to application and got the the error:
ModuleNotFoundError: No module named 'dns'

Linux: Ubuntu 20.04
Python 3.8.5
PyInstaller 4.2

Any idea? Thanks in advance.

**Comment by bwoodsend** [comment]
Add `--hiddenimport=dns` to you build command.

**Comment by jimwangzx** [comment]
Thanks bwoodsend.

pyinstaller --hiddenimport=dns xxx.spec
Is this correct?

But still got the error:
![image](https://user-images.githubusercontent.com/44415773/110222156-18fe4800-7e85-11eb-8847-9951f0d5f507.png)

**Comment by bwoodsend** [comment]
Ah no it's ignored from the command line if your using the spec file. There should be a list in the spec file called `hiddenimports=[]`. Add it there (`hiddenimports=['dns']`). 

PS: If you fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) this would be much easier.

**Comment by jimwangzx** [comment]
![image](https://user-images.githubusercontent.com/44415773/110222295-05071600-7e86-11eb-9125-00075f01e50a.png)


Actually, I tried this before I filling out the issue.

Looks like it does not work

**Comment by rokm** [comment]
You probably have `pyinstaller` installed in different (virtual) environment than `dnspython`. Try running `python -m PyInstaller [...]` instead of `pyinstaller [...]` to see if that's the case.

**Comment by jimwangzx** [comment]
I noticed that it did not rebuild.

I tried to made a minor change to the source code, and then everything was rebuilt, and it works now.

Thanks  bwoodsend

**Comment by jimwangzx** [comment]
> You probably have `pyinstaller` installed in different (virtual) environment than `dnspython`. Try running `python -m PyInstaller [...]` instead of `pyinstaller [...]` to see if that's the case.

Thanks rokm


Although it is not the case, I found it did run in a different environment by running "python -m PyInstaller".

Thanks.
