### ISSUE TITLE
retargeting to non-venv dir '/usr/lib/python3.8', is it related to the error "No module named 'backports.configparser"?

### ISSUE THREAD

**Issue by jimwangzx** [pyinstaller/pyinstaller#5612]
I run pyinstaller in a virtual environment, but is retargeted to non-venv, is it normal?
 
**INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'**

**And got the following error:**
    import distutils.core
  File "/usr/lib/python3.8/distutils/core.py", line 18, in <module>
    from distutils.config import PyPIRCCommand
  File "/usr/lib/python3.8/distutils/config.py", line 7, in <module>
    from configparser import RawConfigParser
  File "/home/jwang/ml_project/lib/python3.8/site-packages/configparser.py", line 11, in <module>
    from backports.configparser import (
ModuleNotFoundError: **No module named 'backports.configparser'**

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by jimwangzx** [comment]
I found the solution. It is not related.
