### ISSUE TITLE
Stuck at INFO: Building PKG (CArchive) PKG-00.pkg, is it normal

### ISSUE THREAD

**Issue by jimwangzx** [pyinstaller/pyinstaller#5613]
I ran pyinstaller with --onefile.

It stuck at "INFO: Building PKG (CArchive) PKG-00.pkg", it has been running more than 1 hour.

The project is kind of big, but is this normal? Should I wait for finish?

**Comment by bwoodsend** [comment]
It can take up to a few minutes so no that's not normal. Kill it.

**Comment by jimwangzx** [comment]
Thanks.

**Comment by jimwangzx** [comment]
I used --log-level=DEBUG  and found it sticked at:
Compiling xxxx.py

Is there any way to know what caused the stuck?

**Comment by bwoodsend** [comment]
That's not where I expect it to get bogged down. Is the `--onedir` app huge? 

> Is there any way to know what caused the stuck?

Not without seeing the code. There's more than one `logger.debug('Compiling %s', filename)` in PyInstaller's code so I don't even know what it's running.

**Comment by bobbydyr** [comment]
@bwoodsend Got the same issue here.

MacOS: 11.2.3

```
133556 INFO: Appending 'datas' from .spec
134900 INFO: checking PYZ
134944 INFO: checking PKG
134945 INFO: Building PKG because PKG-00.toc is non existent
134945 INFO: Building PKG (CArchive) PKG-00.pkg
```

Problem Description: I was using Pyinstaller several months ago without any problem. But when I got back with the same setup, it hangs at this step. Please help!

**Comment by bwoodsend** [comment]
> Not without seeing the code. There's more than one logger.debug('Compiling %s', filename) in PyInstaller's code so I don't even know what it's running.

**Comment by jimwangzx** [comment]
I solved the problem by set --log-level=DEBUG and found a lib not installed, after "pip install xxx", the problem solved.

You can try --log-level=DEBUG,  maybe you can find the problm

**Comment by Qxuan-rgb** [comment]
I have the same question.
I also used --log-level=DEBUG and found it sticked at:
Compiling xxxx.py

How to find uninstalled lib?
