### ISSUE TITLE
PyInstaller works on the machine where python is installed not on users machine without python

### ISSUE THREAD

**Issue by snehalnair** [pyinstaller/pyinstaller#5619]
PyInstaller works on the machine where python is installed not on users machine.
Both the machines are 64bit Windows10.

 - On the user machine it doesnt give error, the command line shuts abruptly without showing error.
 - pyinstaller --debug=all --log-level=DEBUG --onedir ccg.py

**User's Machine Command Line Messages:** I have pasted below the last few lines of messages on command line before it shuts the window abruptly. I have attached the entire file incase you want to take a look at it.

import 'numpy.random._generator' # <_frozen_importlib_external.ExtensionFileLoader object at 0x000001B65B1FE8C8>
import 'numpy.random._pickle' # <pyimod03_importers.FrozenImporter object at 0x000001B6580E8348>
import 'numpy.random' # <pyimod03_importers.FrozenImporter object at 0x000001B6580E8348>
import numpy.ctypeslib # PyInstaller PYZ
import 'numpy.ctypeslib' # <pyimod03_importers.FrozenImporter object at 0x000001B6580E8348>
import numpy.ma # PyInstaller PYZ
import numpy.ma.core # PyInstaller PYZ
import 'numpy.ma.core' # <pyimod03_importers.FrozenImporter object at 0x000001B6580E8348>
import numpy.ma.extras # PyInstaller PYZ
import 'numpy.ma.extras' # <pyimod03_importers.FrozenImporter object at 0x000001B6580E8348>
import 'numpy.ma' # <pyimod03_importers.FrozenImporter object at 0x000001B6580E8348>
[cli.txt](https://github.com/pyinstaller/pyinstaller/files/6102339/cli.txt)

**Comment by bwoodsend** [comment]
Did you build it using Anaconda Python? It looks like NumPy/Conda's missing `libiomp5.dll` again...

**Comment by snehalnair** [comment]
Thank you for a quick response!
Yes, I built it using Anaconda Python. How do I fix this error ?

**Comment by bwoodsend** [comment]
It was fixed in #5168 so just install the development version:

```
conda remove pyinstaller
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Then rebuild but add the `--clean` option.

**Comment by rokm** [comment]
> I looked up on the internet and found this solution:
> 
> `pyinstaller --onefile --add-binary='/System/Library/Frameworks/Tk.framework/Tk':'tk' --add-binary='/System/Library/Frameworks/Tcl.framework/Tcl':'tcl' PDT_Admin_Console.py`

That used to be a work-around for certain class of tkinter-related issues on macOS. It has been obsoleted on macOS in PyInstaller 4.x series, and is irrelevant to you anyway, as you're on Windows.

> `pyinstaller Failed to execute script pyi_rth__tkinter`

Can you post the full error message (the preceding lines up until  `Traceback (most recent call last):`)? It's probably missing either `tcl` or `tk` directory...

If you're not using Tcl/Tk via `tkinter` in your program, you can try excluding it via `--exclude-module=tkinter --exclude-module=_tkinter`; but you could also try to work around by simply creating empty `tcl` and `tk` directories in application's `dist/ccg` directory.

If you are using `tkinter`, then please attach full build log, so we can see why its data was not collected.

**Comment by snehalnair** [comment]
Thank you. Now I am getting a different error:
`ModuleNotFoundError: No module named 'os'`
[logs.txt](https://github.com/pyinstaller/pyinstaller/files/6122690/logs.txt)

**Comment by bwoodsend** [comment]
I can't work out where PyInstaller puts `os`. I thought it lived in the `base-library.zip` it doesn't. It must be baked directly into `libpython.so`? No idea why it would get lost. Can you do a file list? `dir /s /b` I think on Windows. Or just `find .` if you have bash.

**Comment by snehalnair** [comment]
I cant find it.

**Comment by rokm** [comment]
> I can't work out where PyInstaller puts `os˙.

It should be in PYZ.

**Comment by rokm** [comment]
And I find it very odd that it wasn't collected; @snehalnair did you perhaps exclude it by accident?

**Comment by snehalnair** [comment]
I tested it on one user machine, I have everything working fine there now. Steps followed based on the suggestions given:
`conda remove pyinstaller`
`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`
`rebuild using --clean command`
`pip install tkinter`

Appreciate your help!
