### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by SamAjibesin** [pyinstaller/pyinstaller#5621]
Hi I'm a beginner trying out a few stuffs, I get this errors each time I run my code and don't know what to do. Kindly help
```python
Traceback (most recent call last):
  File "D:/Work/Project Work/Codes/Codes/Video based vehicle counting using opencv/ivy-master/main.py", line 142, in <module>
    init_logger()
  File "D:\Work\Project Work\Codes\Codes\Video based vehicle counting using opencv\ivy-master\util\logger.py", line 55, in init_logger
    pathlib.Path(log_files_directory).mkdir(parents=True, exist_ok=True)
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 1003, in __new__
    self = cls._from_parts(args, init=False)
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 658, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "C:\ProgramData\Anaconda3\lib\pathlib.py", line 642, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by rokm** [comment]
You probably have `pathlib` package installed in an environment with python version that does not require it anymore, and it conflicts with the python's built-in version of `pathlib`. So uninstall the `pathlib` package from your environment.

**Comment by SamAjibesin** [comment]
I've uninstalled the pathlib package but the problem persist

**Comment by rokm** [comment]
Ah, sorry, I didn't pay enough attention to the error message and mistook it for a similar one that was related to old `pathlib`.

>  TypeError: expected str, bytes or os.PathLike object, not NoneType

In your case, you're passing `None` to `pathlib.Path()`, which means that your `log_files_directory` ended up being `None` somehow. Are you perhaps tying it to module's `__file__` attribute? [That will not work in a frozen application](https://pyinstaller.readthedocs.io/en/stable/runtime-information.html?ld-library-path-libpath-considerations#using-file)...

**Comment by SamAjibesin** [comment]
Ok. Thanks for the prompt response. What can I do to try it to module's _file_ attribute?

**Comment by bwoodsend** [comment]
What's your code doing with it? What do you want it to do?

**Comment by SamAjibesin** [comment]
Here is the example code:


import sys
import time
import cv2

def run():
    '''
    Initialize counter class and run counting loop.
    '''

   
    from util.image import take_screenshot
    from util.logger import get_logger
    from util.debugger import mouse_callback
    from VehicleCounter import VehicleCounter

    logger = get_logger()

    # capture traffic scene video
    is_cam = ast.literal_eval(os.getenv('IS_CAM'))
    video = int(os.getenv('VIDEO')) if is_cam else os.getenv('VIDEO')
    cap = cv2.VideoCapture(video)
    if not cap.isOpened():
        raise Exception('Invalid video source {0}'.format(video))
    ret, frame = cap.read()
    f_height, f_width, _ = frame.shape

    detection_interval = int(os.getenv('DI'))
    mcdf = int(os.getenv('MCDF'))
    mctf = int(os.getenv('MCTF'))
    detector = os.getenv('DETECTOR')
    tracker = os.getenv('TRACKER')
    # create detection region of interest polygon
    use_droi = ast.literal_eval(os.getenv('USE_DROI'))
    droi = ast.literal_eval(os.getenv('DROI')) \
            if use_droi \
            else [(0, 0), (f_width, 0), (f_width, f_height), (0, f_height)]
    show_droi = ast.literal_eval(os.getenv('SHOW_DROI'))
    counting_lines = ast.literal_eval(os.getenv('COUNTING_LINES'))

    vehicle_counter = VehicleCounter(frame, detector, tracker, droi, show_droi, mcdf,
                                     mctf, detection_interval, counting_lines)

    record = ast.literal_eval(os.getenv('RECORD'))
    headless = ast.literal_eval(os.getenv('HEADLESS'))

    if record:
        # initialize video object to record counting
        output_video = cv2.VideoWriter(os.getenv('OUTPUT_VIDEO_PATH'), \
                                        cv2.VideoWriter_fourcc(*'MJPG'), \
                                        30, \
                                        (f_width, f_height))

    logger.info('Processing started.', extra={
        'meta': {
            'label': 'START_PROCESS',
            'counter_config': {
                'di': detection_interval,
                'mcdf': mcdf,
                'mctf': mctf,
                'detector': detector,
                'tracker': tracker,
                'use_droi': use_droi,
                'droi': droi,
                'show_droi': show_droi,
                'counting_lines': counting_lines
            },
        },
    })

    if not headless:
        # capture mouse events in the debug window
        cv2.namedWindow('Debug')
        cv2.setMouseCallback('Debug', mouse_callback, {'frame_width': f_width, 'frame_height': f_height})

    is_paused = False
    output_frame = None

    # main loop
    while is_cam or cap.get(cv2.CAP_PROP_POS_FRAMES) + 1 < cap.get(cv2.CAP_PROP_FRAME_COUNT):
        k = cv2.waitKey(1) & 0xFF
        if k == ord('p'): # pause/play loop if 'p' key is pressed
            is_paused = False if is_paused else True
            logger.info('Loop paused/played.', extra={'meta': {'label': 'PAUSE_PLAY_LOOP', 'is_paused': is_paused}})
        if k == ord('s') and output_frame is not None: # save frame if 's' key is pressed
            take_screenshot(output_frame)
        if k == ord('q'): # end video loop if 'q' key is pressed
            logger.info('Loop stopped.', extra={'meta': {'label': 'STOP_LOOP'}})
            break

        if is_paused:
            time.sleep(0.5)
            continue

        _timer = cv2.getTickCount() # set timer to calculate processing frame rate

        if ret:
            vehicle_counter.count(frame)
            output_frame = vehicle_counter.visualize()

            if record:
                output_video.write(output_frame)

            if not headless:
                debug_window_size = ast.literal_eval(os.getenv('DEBUG_WINDOW_SIZE'))
                resized_frame = cv2.resize(output_frame, debug_window_size)
                cv2.imshow('Debug', resized_frame)

        processing_frame_rate = round(cv2.getTickFrequency() / (cv2.getTickCount() - _timer), 2)
        frames_processed = round(cap.get(cv2.CAP_PROP_POS_FRAMES))
        frames_count = round(cap.get(cv2.CAP_PROP_FRAME_COUNT))
        logger.debug('Frame processed.', extra={
            'meta': {
                'label': 'FRAME_PROCESS',
                'frames_processed': frames_processed,
                'frame_rate': processing_frame_rate,
                'frames_left': frames_count - frames_processed,
                'percentage_processed': round((frames_processed / frames_count) * 100, 2),
            },
        })

        ret, frame = cap.read()

    # end capture, close window, close log file and video object if any
    cap.release()
    if not headless:
        cv2.destroyAllWindows()
    if record:
        output_video.release()
    logger.info('Processing ended.', extra={'meta': {'label': 'END_PROCESS'}})


if __name__ == '__main__':
    from dotenv import load_dotenv
    load_dotenv()

    from util.logger import init_logger
    init_logger()

    run()

**Comment by rokm** [comment]
The error is originating from your `util\logger.py` module, so we'd need to see the code for that. Or at least the part that computes `log_files_directory` that's passed to `init_logger` in line 55 of `util\logger.py`.

**Comment by SamAjibesin** [comment]
Here's the code from the util/logger.py:

import os
import ast
import logging
import pathlib
from pythonjsonlogger import jsonlogger

from .job import get_job_id


class MetaFilter(logging.Filter):
    '''
    Add meta field to log if one doesn't exist.
    '''
    def filter(self, record):
        if not hasattr(record, 'meta'):
            record.meta = {}
        return True

class CustomJsonFormatter(jsonlogger.JsonFormatter):
    '''
    Create custom JSON formatter.
    '''
    def add_fields(self, log_record, record, message_dict):
        super(CustomJsonFormatter, self).add_fields(log_record, record, message_dict)
        # rename fields
        log_record['logger'] = record.name
        log_record['level'] = record.levelname

def init_logger():
    '''
    Setup logger.
    '''

    job_id = get_job_id()

    logger = logging.getLogger(job_id)
    logger.addFilter(MetaFilter())
    logger.setLevel(logging.DEBUG)

    enable_console_logger = ast.literal_eval(os.getenv('ENABLE_CONSOLE_LOGGER', 'True'))
    if enable_console_logger:
        stream_handler = logging.StreamHandler()
        stream_handler.setLevel(logging.INFO) # https://docs.python.org/3/library/logging.html#logging-levels
        stream_formatter = logging.Formatter('[%(asctime)-15s] %(levelname)-8s: %(message)s %(meta)s')
        stream_handler.setFormatter(stream_formatter)
        logger.addHandler(stream_handler)

    enable_file_logger = ast.literal_eval(os.getenv('ENABLE_FILE_LOGGER', 'True'))
    if enable_file_logger:
        log_files_directory = os.getenv('LOG_FILES_DIRECTORY')
        pathlib.Path(log_files_directory).mkdir(parents=True, exist_ok=True)
        file_path = os.path.join(log_files_directory, job_id + '.log')
        file_handler = logging.FileHandler(file_path)
        file_handler.setLevel(logging.DEBUG)
        file_formatter = CustomJsonFormatter('(created) (logger) (level) (message)')
        file_handler.setFormatter(file_formatter)
        logger.addHandler(file_handler)

    enable_logstash_logger = ast.literal_eval(os.getenv('ENABLE_LOGSTASH_LOGGER', 'False'))
    if enable_logstash_logger:
        pass

def get_logger():
    '''
    Fetch logger.
    '''
    return logging.getLogger(get_job_id())

**Comment by rokm** [comment]
> log_files_directory = os.getenv('LOG_FILES_DIRECTORY')
> pathlib.Path(log_files_directory).mkdir(parents=True, exist_ok=True)

So you're trying to get the path from environment, and are not properly handling the case when the environment variable is not defined in the environment.

**Comment by SamAjibesin** [comment]
How do I handle the case properly when the environment variable is not defined in the environment?

**Comment by SamAjibesin** [comment]
How do I handle the case properly when the environment variable is not defined in the environment?

**Comment by bwoodsend** [comment]
That depends on what you want it to do if it's not given a `LOG_FILE_DIRECTORY`. Your choices are either to provide a default:
```python
if not log_files_directory:
    # Default to the current working dir.
    log_files_directory = "."
```
Or disable logging.

**Comment by rokm** [comment]
At any rate, this issue has nothing to do with PyInstaller.
