### ISSUE TITLE
the size of exe file is too big

### ISSUE THREAD

**Issue by mohankumargx** [pyinstaller/pyinstaller#5622]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
The generated exe file is too large(450MB) when i created the exe with 4.1 it's only(70MB). I think there is some issue with 4.2

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```(4.2)```
* Version of Python: 3.8.5
* Platform: Windows 
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
You're going to have to be way more specific. Give us a specific example that is much bigger using 4.2 than 4.1, look at the xref file and toc tables in the `build` folder to tell us what is new.

**Comment by zy63600** [comment]
Is the packing process idempotent？If it is guaranteed that the size of the packaged result is the same？ I  will looking forward to your answer very much ！
