### ISSUE TITLE
The window can not be clicked through (tkinter `wm_attributes("-transparentcolor", color)` method)

### ISSUE THREAD

**Issue by AST07** [pyinstaller/pyinstaller#5624]
## Description of the issue

When using the `tkinter` module's method `wm_attributes("-transparentcolor", color)`, the specified `color` will be treated as transparent (the region of the window containing the color can be clicked through). If the script is run normally / packaged using the `--onedir` mode of `pyinstaller`, the behaviour is as expected but, if `--onefile` mode is used, click-through does not work in the resulting exe.

## Context information (for bug reports)

* Output of `pyinstaller --version`: `4.1`
* Version of Python: 3.8
* Platform: Windows 

### A minimal example program which shows the error

```python
from tkinter import *

def focus(event):
	print(event)

root=Tk()
root.config(bg='blue')
root.wm_attributes('-transparentcolor',root['bg'])
root.attributes('-topmost',True)

root.bind('<FocusIn>',focus)
root.bind('<FocusOut>',focus)

root.mainloop()
```

**Comment by rokm** [comment]
Can you try with PyInstaller 4.2? 

Click-through indeed does not seem to be working in `onefile` with 4.1, but it seems to work with 4.2. According to `git bisect`, 3c3228da89c494f79dc1cead99ab9b4e45a7424e was the commit that fixed it.

**Comment by AST07** [comment]
I don't exactly see how linked commit fixed this, but the click-though does work with 4.2. Thank you and sorry to have wasted your time.

**Comment by bwoodsend** [comment]
That is very weird. Does adding an icon break it by any chance?

**Comment by AST07** [comment]
Just tested, adding an icon does not break it, using `--icon=NONE` does, click-through did not work.

**Comment by rokm** [comment]
> Just tested, adding an icon does not break it, using --icon=NONE does, click-through did not work.

Hmm, that is indeed the case, and a very useful hint.

**Comment by rokm** [comment]
And as is often the case around here, the problem was lying somewhere else, but was triggered by icon being disabled. Or, prior to 3c3228d, by not being specified.
