### ISSUE TITLE
Error hidden import not found pkg_resources.py2_warn, not the same as all the other problems from last year

### ISSUE THREAD

**Issue by Zeebzog** [pyinstaller/pyinstaller#5627]
I am using Pinstaller : 5.0.dev0 since this addressed an issue found with temporary files and staticx
A number of my programs, but not all of them, complain that they cannot find 
 WARNING: Hidden import "pkg_resources.py2_warn" not found!
 WARNING: Hidden import "pkg_resources.markers" not found!
If I include these with --hidden-import='pkg_resources.py2_warn' --hidden-import='pkg_resources.markers' I still get the warnings
but also  ERROR: Hidden import 'pkg_resources.markers' not found for example
I have tried different versions of setuptools  including version 43, 45, 54.1.1
The program does start once built but I am concerned that there is something wrong with it
I have deleted the dist directory, run with --clean etc. always with the same out come. Any advice welcome.

**Comment by bwoodsend** [comment]
Full build log and runtime error traceback please.

**Comment by Zeebzog** [comment]
Thank you for coming back so quickly. The command I am running is:

 pyinstaller --clean -F --add-binary='/lib/x86_64-linux-gnu/libgcc_s.so.1:.' --add-binary='/lib/x86_64-linux-gnu/libdl.so.2:.' --add-binary='/lib/x86_64-linux-gnu/libz.so.1:.' --add-binary='/lib/x86_64-linux-gnu/libc.so.6:.'  main.py 

This is the output of pyinstaller:

18 INFO: PyInstaller: 5.0.dev0
18 INFO: Python: 3.8.5
23 INFO: Platform: Linux-5.8.0-44-generic-x86_64-with-glibc2.29
23 INFO: wrote /home/Zeebzog/Development/NewCom/Services/Administrator/main.spec
25 INFO: UPX is not available.
25 INFO: Removing temporary files and cleaning cache in /home/Zeebzog/.cache/pyinstaller
28 INFO: Extending PYTHONPATH with paths
['/home/Zeebzog/Development/NewCom/Services/Administrator',
 '/home/Zeebzog/Development/NewCom/Services/Administrator']
34 INFO: checking Analysis
34 INFO: Building Analysis because Analysis-00.toc is non existent
34 INFO: Initializing module dependency graph...
35 INFO: Caching module graph hooks...
37 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
38 INFO: Analyzing base_library.zip ...
1344 INFO: Processing pre-find module path hook distutils from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1345 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'
2503 INFO: Caching module dependency graph...
2578 INFO: running Analysis Analysis-00.toc
2603 INFO: Analyzing /home/Zeebzog/Development/NewCom/Services/Administrator/main.py
3849 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-urllib3.packages.six.moves.py'.
4692 INFO: Processing module hooks...
4693 INFO: Loading module hook 'hook-cryptography.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
4777 INFO: Loading module hook 'hook-jinja2.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
4791 INFO: Loading module hook 'hook-certifi.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
4792 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
4908 INFO: Processing pre-safe import module hook win32com from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
5016 WARNING: Hidden import "pkg_resources.py2_warn" not found!
5147 WARNING: Hidden import "pkg_resources.markers" not found!
5149 INFO: Excluding import of __main__ from module pkg_resources
5149 INFO: Loading module hook 'hook-distutils.util.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5150 INFO: Excluding import of lib2to3.refactor from module distutils.util
5150 INFO: Loading module hook 'hook-lib2to3.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5155 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5156 INFO: Excluding import of test from module multiprocessing.util
5156 INFO: Excluding import of test.support from module multiprocessing.util
5156 INFO: Loading module hook 'hook-xml.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5180 INFO: Loading module hook 'hook-difflib.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5182 INFO: Excluding import of doctest from module difflib
5182 INFO: Loading module hook 'hook-sysconfig.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5185 INFO: Loading module hook 'hook-packaging.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5186 INFO: Loading module hook 'hook-heapq.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5187 INFO: Excluding import of doctest from module heapq
5187 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5187 INFO: Loading module hook 'hook-pickle.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5188 INFO: Excluding import of argparse from module pickle
5188 INFO: Loading module hook 'hook-distutils.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5188 INFO: Loading module hook 'hook-encodings.py' from '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks'...
5237 INFO: Looking for ctypes DLLs
5379 INFO: Analyzing run-time hooks ...
5383 INFO: Including run-time hook '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
5385 INFO: Including run-time hook '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_certifi.py'
5385 INFO: Including run-time hook '/home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
5391 INFO: Looking for dynamic libraries
5708 INFO: Looking for eggs
5709 INFO: Python library not in binary dependencies. Doing additional searching...
5722 INFO: Using Python library /lib/x86_64-linux-gnu/libpython3.8.so.1.0
5730 INFO: Warnings written to /home/Zeebzog/Development/NewCom/Services/Administrator/build/main/warn-main.txt
5761 INFO: Graph cross-reference written to /home/Zeebzog/Development/NewCom/Services/Administrator/build/main/xref-main.html
5770 INFO: Appending 'binaries' from .spec
5771 INFO: checking PYZ
5771 INFO: Building PYZ because PYZ-00.toc is non existent
5771 INFO: Building PYZ (ZlibArchive) /home/Zeebzog/Development/NewCom/Services/Administrator/build/main/PYZ-00.pyz
6243 INFO: Building PYZ (ZlibArchive) /home/Zeebzog/Development/NewCom/Services/Administrator/build/main/PYZ-00.pyz completed successfully.
6250 INFO: checking PKG
6251 INFO: Building PKG because PKG-00.toc is non existent
6251 INFO: Building PKG (CArchive) PKG-00.pkg
9275 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
9276 INFO: Bootloader /home/Zeebzog/Development/NewCom/.venv/lib/python3.8/site-packages/PyInstaller/bootloader/Linux-64bit/run
9276 INFO: checking EXE
9276 INFO: Building EXE because EXE-00.toc is non existent
9276 INFO: Building EXE from EXE-00.toc
9277 INFO: Appending archive to ELF section in EXE /home/Zeebzog/Development/NewCom/Services/Administrator/dist/main
9395 INFO: Building EXE from EXE-00.toc completed successfully.

The Administrator program does not fall over, it works. The reason I am concerned is that I have different behaviour on a remote machine, where the program is exiting.

**Comment by rokm** [comment]
> The Administrator program does not fall over, it works. The reason I am concerned is that I have different behaviour on a remote machine, where the program is exiting.

That has nothing to do with those warnings, which, while annoying, are harmless. (And are caused by hooks blindly augmenting hiddenimports with names of modules that do not exist (anymore)).

**Comment by rokm** [comment]
So please provide a run-time log from the remote machine where the program does not run, so we can see what the (run-time) error is.

**Comment by Zeebzog** [comment]
Thanks rokm , this will take a bit of organizing, but I will come back.

**Comment by Zeebzog** [comment]
By changing the code I managed to address this problem. Thank you for your time.
