### ISSUE TITLE
PyQt5 5.15.4 changed Qt installation directory

### ISSUE THREAD

**Issue by The-Compiler** [pyinstaller/pyinstaller#5631]
(Taking the freedom to delete the template as I think I know what the exact issue is)

With [PyQt5 5.15.4 and PyQtWebEngine 5.15.4](https://www.riverbankcomputing.com/pipermail/pyqt/2021-March/043699.html), the directory where its bundled Qt installation is shipped [changed from "Qt" to "Qt5"](https://www.riverbankcomputing.com/pipermail/pyqt/2021-March/043700.html).

This causes PyInstaller to either abort because it couldn't find those files (Windows), or to segfault when trying to create a QApplication (macOS). I haven't tried Linux.

I planned to submit a fix for this, but noticed how it involved a couple of parts of Qt (and operating systems) I'm not really familiar with.

From a quick look, I think the following places would need to be adjusted:

https://github.com/pyinstaller/pyinstaller/blob/27e5bc721e3bee36bb35162ccee8dd276a0c7ead/PyInstaller/utils/hooks/qt.py#L166

https://github.com/pyinstaller/pyinstaller/blob/27e5bc721e3bee36bb35162ccee8dd276a0c7ead/PyInstaller/utils/hooks/qt.py#L553

https://github.com/pyinstaller/pyinstaller/blob/27e5bc721e3bee36bb35162ccee8dd276a0c7ead/PyInstaller/hooks/hook-PyQt5.QtQml.py#L31

https://github.com/pyinstaller/pyinstaller/blob/27e5bc721e3bee36bb35162ccee8dd276a0c7ead/PyInstaller/hooks/hook-PyQt5.py#L28

https://github.com/pyinstaller/pyinstaller/blob/27e5bc721e3bee36bb35162ccee8dd276a0c7ead/PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py#L25

https://github.com/pyinstaller/pyinstaller/blob/27e5bc721e3bee36bb35162ccee8dd276a0c7ead/PyInstaller/hooks/hook-PyQt5.QtWebEngineWidgets.py#L46

I guess there'd need to be some kind of utility method which checks which of the two is available, and prefers the `Qt5` one if both are. Or perhaps a cleaner solution should use `Qt5LibraryInfo` to find the proper location instead?

I might take a stab at it if nobody else beats me to it, but it'll likely take me some time as I have a lot on my plate with my own project already.

cc @bjones1 (let me know if you'd prefer me to not ping you for Qt related issues and I'll avoid that next time!)

**Comment by bwoodsend** [comment]
@RS357 Feeling ambitious?

**Comment by RoadrunnerWMC** [comment]
I'd like to add -- just for the sake of considering a future-proof solution -- that PyQt6 released a couple of months ago and (as of 6.0.3, which released simultaneously with PyQt5 5.15.4) uses a `Qt6` directory for Qt, not `Qt5`. So using a utility method sounds like a good idea, since it'll probably make that change easier to implement when PyQt6 support is added.

**Comment by rokm** [comment]
Indeed; this should probably be tackled together with sorting out support for PyQt6 and PySide6.

**Comment by bwoodsend** [comment]
We've got #5534 which adds support for PyQt6 but I'm not comfortable with the way the Qt support is just multiplying in size/complexity rather than being tidied up and generalised.

**Comment by bjones1** [comment]
As much as I'd like to help, I'm too busy with other projects. I hope that the comments I added and the code written will provide some framework for a good path forward. Trying to support all these PyQt variants is challenge! < PyQt 5.15.3, >= PyQt 5.13.3, PySide2, PyQt6, PySide6, all with significant differences between each version and with significant per-platform differences as well.

**Comment by JulianOrteil** [comment]
I would like to append to this issue. The suggested changes above from @The-Compiler do indeed work, at least in my specific use case. Without the above changes, the error "Could not find qtwebengineprocess.exe" was being thrown.

My environment:
- Windows 10 x64
- Python v3.8.8
- PyInstaller v4.3
- PyQt5 v5.15.4
- PyQtWebEngine v5.15.4
- Using an Anaconda environment
