### ISSUE TITLE
Adding option to --onefile to specify a write to a non-exe file

### ISSUE THREAD

**Issue by mparets** [pyinstaller/pyinstaller#5635]
Antivirus software is blocking PyInstaller from creating an EXE file when using the --onefile option.  A way around this would be to add an option to --onefile to write to a file with a different, non-exe extension.  This would prevent the anti-virus software from getting int he way of process. The file could then be manually renamed to .exe after the build process was completed.

**Comment by bwoodsend** [comment]
I seriously doubt that'll help. Surely the antivirus will dive in once you rename the file or when you try to run it...

In all honesty, if your antivirus is that ineffective then turn it off. It's clearly not effective.

**Comment by Legorooj** [comment]
This isn't a problem with PyInstaller, it's a problem with your antivirus.
