### ISSUE TITLE
Why does Pyinstaller take everything in my folder to put them in my Mac OS app?

### ISSUE THREAD

**Issue by gauthierbuttez** [pyinstaller/pyinstaller#5639]
Hi,

I am developing software with Python 3 on MAC OS Catalina 10.15

A few months ago, I compiled successfully my app.

I made some updates. I wanted to compile my software, and this time, Pyinstaller take all the files of my folder (even the unnecessary ones) in the app folder.

Is there a way to take only the necessary files?

**Comment by rokm** [comment]
With the amount of details you provided, our guess is as good as yours...
