### ISSUE TITLE
Loading time for numpy / scipy

### ISSUE THREAD

**Issue by monschine** [pyinstaller/pyinstaller#5644]
Hi, 

I have made some debugging test on my binary file, and figured out some large times for loading modules such as numpy & scipy

`numpy 5.650085210800171 seconds`
`scipy 8.964370012283325 seconds`

```
np_time = time.time()
import numpy as np
print("--- numpy %s  ---" % (time.time() - np_time))
```

The versions I'm using
```
pyinstaller==4.1
numpy==1.16.4
scipy==1.5.1
```

Is that normal ?  Can we improve that time ?

**Comment by bwoodsend** [comment]
Initialization delays are caused by your antivirus scanning each binary as it's loaded in. NumPy and SciPy each contain a substantial amount of binaries. Your options are:
- Don't use onefile mode. This way it'll be scanned the first time you run but never again (unless you compile again).
- Turn off your antivirus.

**Comment by bwoodsend** [comment]
And an option 3 for Windows only:
- Use the unofficial [*vanilla* versions of NumPy](https://www.lfd.uci.edu/~gohlke/pythonlibs/#numpy) which don't include BLAS and are therefore smaller.

**Comment by monschine** [comment]
Hi and thanks for your answer.

I'm actually not using antivirus.

I was also testing the **--onedir** option, and as you mention first load takes longer but not the next calls, even computer is restarted or shutdown.

```
numpy 0.17561817169189453
image 0.03058004379272461
scipy 0.16325879096984863
```
Just to close the topic, there would be some method to get those loading times with **onefile** flag ?
Thanks and kind regards

**Comment by bwoodsend** [comment]
> I'm actually not using antivirus.

I very much doubt that. Both Windows and Mac come with them baked in whether you want them or not. Unless you're running Linux in which case that 1st time delay would be very abnormal.

> Just to close the topic, there would be some method to get those loading times with `--onefile` flag ?

No not with onefile. A onefile application needs to unpack. The unpacked contents are *new* (to the OS) and therefore the OS will insist on checking them.

**Comment by monschine** [comment]
Ok, I see the system is checking the files, I'm mostly testing in mac.
I will forget about the onefile, as the execution time I get with onedir are just great, and open a new dimension of using the code, which before was very limited by the initial loading / checking time.

Thanks so much for you answers

**Comment by monschine** [comment]
Hi @bwoodsend 
I have made an initial call so all the modules get loaded initially, and after that every call is really fast.
The only issue I have is that scipy seems to be divided into multiples parts

I was expecting to do something like 
`from scipy import *`

But if after that I do 

`from scipy.spatial.transform import Rotation`

it still needs to be scanned...
In that regard there would be some method to import the whole scipy library ?

Thanks again

**Comment by rokm** [comment]
> I was expecting to do something like
> from scipy import *

This would do the trick if `scipy` package imported all its subpackages.

Alas, as noted [here](https://github.com/scipy/scipy/blob/085b766efb054f6529815f8b7b1013c18aaca3bf/scipy/__init__.py#L13-L17), you need to explicitly import each subpackage yourself.
