### ISSUE TITLE
MacOS BigSur Build generates terminal app and .app which fails to open

### ISSUE THREAD

**Issue by PyMarc2** [pyinstaller/pyinstaller#5645]
## Description of the issue
I am building a PyQt5 Application on macOS BigSur (11.1).
I have downgraded PyQt5 to 5.15.3. I still get tons of errors that seem to be related to  #5464.
The program builds, but the dist folder contains  a terminal file and a `.app`

The terminal app launches fine, except it shows the console and doesn't have the app logo.
The `.app` launches, but closes a couple milliseconds after the launch with no console errors or indications.
Anyone has had this behaviour before?

I used these specific commands to generate the build:
`pyinstaller main.py --onefile --noconsole --clean --icon /Path/to/icon.ico`

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: 3.8.4
* Platform: macOS BigSur 11.1
* It works on WIndows 10.

**Comment by rokm** [comment]
>  The .app launches, but closes a couple milliseconds after the launch with no console errors or indications.

.app bundles don't have console, so if application crashes due to uncaught exception, it will "close" without any error indication. To get the traceback, you could try wrapping your whole entry-point script in try-except block that saves exception information to a file.
