### ISSUE TITLE
locale standard library causes macOS app to not start on double-click

### ISSUE THREAD

**Issue by e-caste** [pyinstaller/pyinstaller#5646]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue

A packaged .app on macOS will not start when its icon is double-clicked. In [my app](https://github.com/e-caste/study-planner) everything worked fine as of 2.1.0, so as of 2.2.0 I had to find the culprit that did not allow the app to start. Having excluded any Mac-specific issues (by restarting my machine, trying version 2.1.0 of my app to see if any recent macOS update had broken something, and looking extensively into code signing) and having checked thoroughly the Console logs (finding nothing of interest), I came to the conclusion that the issue was in my code. I had only imported 2 new libraries, so I started with those: commenting out `requests` had no effect, so the library which caused the issue had to be `locale`. And surely enough, after commenting it out the app starts correctly on a double-click.

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: 3.9.1, 3.9.2
* Platform: macOS 11.2.3 (local), macOS 10.15.7 (GitHub runner)
* Did you also try this on another platform? Does it work there? Everything works as expected on Windows 10 and GNU/Linux (Ubuntu 20.04)

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation (tested locally and in a GitHub runner)
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```python
import locale
lang = "it" if "it" in locale.getdefaultlocale()[0] else "en"
```
You can see the full code and my temporary fix [at this link](https://github.com/e-caste/study-planner/blob/b020090cdcd9e3fe2441bc4ef6bbfa3957c5e2c5/translations.py).

### Stacktrace / full error message

There is no stacktrace in this case: the Mac app works perfectly fine running the executable (`./Name.app/Contents/MacOS/Name`) or using the open command (`open Name.app`). The only way to see the issue is by double-clicking the icon in the Finder, and since it's running in windowed mode, no error message can be seen. From the looks of the Console logs, the app simply starts and immediately closes, but no warnings or errors are generated while doing so.

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
[```language code and encoding may be None if their values cannot be determined.```](https://docs.python.org/3/library/locale.html#locale.getdefaultlocale)

Running `"it" in None` raises `argument of type 'NoneType' is not iterable` exception (which is unhandled and crashes the application).

**Comment by e-caste** [comment]
@rokm Thank you, this partially answers my issue, but not completely: on Windows and Ubuntu the language is detected correctly, both when running the Python code and when starting the packaged application. Instead on macOS, I can get the locale information only when running the Python code directly, but not in the packaged app. Why could that be?

**Comment by rokm** [comment]
> Why could that be?

No idea, sorry. But it does seem related to Finder - if I open the frozen program.app from Terminal, e.g.
`open /Applications/program.app`, `locale.getdefaultlocale()` returns `('en_US', 'UTF-8')`, while when ran via double-click, it returns `(None, None)`.

**Comment by rokm** [comment]
I'm closing this as it seems that lack of locale information is due to limited environment when launching via Finder, and as such has nothing to do with PyInstaller. 

https://stackoverflow.com/questions/4719789/how-can-you-get-the-system-default-language-locale-in-a-py2app-packaged-python
