### ISSUE TITLE
Pyinstaller and builder an executable which uses graphviz and networkx 

### ISSUE THREAD

**Issue by Zeebzog** [pyinstaller/pyinstaller#5648]
Hi,

I have developed an application that creates a simple DAG diagram using networkx and graphviz
Everything works as expected
I create the spec file for the app, as shown below
I am using pyinstaller 5.0.dev0
When I run the app from a scratch docker container I get:

"Program dot not found in path"

I am not sure how to fix this. Is it possible to  create a self contained exe on linux for a graphviz reliant app?
When I run this on the linux box outside of a container then it works as expected.

Any help provided is very much appreciated.

________________________________SPEC FILE___________________________________________________________

Analysis(['main.py'],
             pathex=['/home/zeebzog/Development/NewCom/Services/DataProvider'],
             binaries=[
			('/usr/bin/dot','.'),		
			('/usr/bin/nop','.'),		 						    
             		('/lib/x86_64-linux-gnu/libgcc_s.so.1', '.'), 
             		('/lib/x86_64-linux-gnu/libdl.so.2', '.'), 
             		('/lib/x86_64-linux-gnu/libz.so.1', '.'), 
             		('/lib/x86_64-linux-gnu/libc.so.6', '.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_core.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_dot_layout.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_gd.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_gdk.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_gtk.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_neato_layout.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_pango.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_rsvg.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_visio.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_webp.so.6','.'),
			('/usr/lib/x86_64-linux-gnu/graphviz/libgvplugin_xlib.so.6','.'),
             		],
             datas=[
             	('/usr/lib/x86_64-linux-gnu/graphviz/config6a', '.'),
             ],

**Comment by rokm** [comment]
Have you tried adding `sys._MEIPASS` to `PATH` before importing `pygraphviz`? 

E.g.,
```python
import os
import sys
if hasattr(sys, '_MEIPASS'):
    os.environ['PATH'] = sys._MEIPASS + os.pathsep + os.environ['PATH']

from pygraphviz import *
```

**Comment by rokm** [comment]
Also, you'll probably need to collect files from `/usr/lib/x86_64-linux-gnu/graphviz` into `graphviz` instead of `.`

**Comment by Zeebzog** [comment]
Thanks rokm

Does the above still stand if I am calling staticx after building the app?

**Comment by rokm** [comment]
So this is a `onefile` build that's post-processed by `staticx`?

That seems to work for my test case, although I had to patch `staticx` to prevent it from raising error due to misidentification of `graphviz/config6a` as a shared library...

Can you try printing output `os.listdir(sys._MEIPASS)` at the top of your script to see what the contents of _MEIPASS are?

**Comment by Zeebzog** [comment]
Hi Rok,

Sorry for the delay it took some time to build etc.

Yes its a onefile build thats post-processed by staticx. It works outside of a scratch docker container. Inside it fails.
I attach the list of files it sees, and also below is the error that I am getting:

[Errno 2] No such file or directory: '/tmp/_MEIy6wSqK/dot'

[insidecontainer.txt](https://github.com/pyinstaller/pyinstaller/files/6167081/insidecontainer.txt)

**Comment by rokm** [comment]
Hmm, so `dot` is there...
Can you post the whole error traceback, so we can see where the error is coming from?

What's the base for the docker container? Is it the same type of distribution as the one you're freezing under?

**Comment by Zeebzog** [comment]
I build under and statically link under normal linux
I then build create a container by using something like the following dockerfile.

FROM scratch

ENTRYPOINT ["./XXXXXX"]

COPY tmp /tmp
COPY XXXXX /

There is a try except around the calls to networkx (I don't call graphviz directly). Let me put some more info lines in so I can see which lines it fails at. Will take around 10 mins

**Comment by Zeebzog** [comment]
import networkx as nx

So I create a networkx graph by adding some edges and nodes and this is called graph
I then call 

    graphvisdot = nx.nx_agraph.to_agraph(graph)
which works
I then call    
    graphvisdot.layout(prog='dot') # use dot
which throws the error

**Comment by rokm** [comment]
Aha, so the scratch container has no libc, and that's why you need `staticx`. The question is, does `staticx` process the bundled executables in the PyInstaller's archive? If not, they will not work, and that would explain the file-not-found kind of error raised by subprocess call in pygraphviz (note that you get a similar "No such file or directory" error if you try to run original onefile program in the scratch container).

**Comment by Zeebzog** [comment]
So it throws on the 
data = self._run_prog(prog, " ".join([args, "-T", output_fmt]))
in networkx agraph.py
If I replace layout with _layout and draw with _draw in my code, which are both experimental in networkx agraph.py it works....

**Comment by Zeebzog** [comment]
So in terms of exes it looks like these will not work. All the other containers i create only rely on shared libraries and these are all fine. The big benefit of using scratch is that my containers are tiny (8-15mb), but I have a lot of them.
For your reference going forward the experimental calls work by calling libgvc

If you can think of a way to call an exe from the tmp directory then I would be very interested in knowing, I am bound to need it at some point. In the meantime thank you once again for your help. As always your assistance as been fantastic.

**Comment by rokm** [comment]
> If I replace layout with _layout and draw with _draw in my code, which are both experimental in networkx agraph.py it works....

Judging by the documentation, these directly use graphviz' shared libraries and avoid calling executables, which is why they work.

> If you can think of a way to call an exe from the tmp directory then I would be very interested in knowing.

Perhaps you can pre-process the executables to be bundled using `staticx` before collecting them with pyinstaller? Or, take a look at `staticx`' hook for PyInstaller archive, and see if you can trick it into identifying and processing collected executables.
