### ISSUE TITLE
Adding custom macOS About Page from Pyinstaller application

### ISSUE THREAD

**Issue by joalen** [pyinstaller/pyinstaller#5650]
### Problem 

How can I implement my own about page in the macOS menu bar section? What Pyinstaller put was the tcl/tk credits, which is what I don't want. Is there a way I can make my own about page instead of the default tcl/tk credits? 

![Screen Shot 2021-03-18 at 4 04 44 PM](https://user-images.githubusercontent.com/45494246/111708910-b73ec600-8814-11eb-97fa-a3b3d586ef4a.png)

**Comment by rokm** [comment]
> What Pyinstaller put was the tcl/tk credits

Tcl/Tk put the their credits there, and it does the same in an unfrozen application (when you click on About Python), so this has nothing to do with PyInstaller.

You need to override the default dialog in Tcl/Tk. See
* https://stackoverflow.com/questions/35641784/where-to-define-the-about-box-in-a-osx-app
* https://www.tcl-lang.org/man/tcl/TkCmd/tk_mac.htm#M21

**Comment by joalen** [comment]
Thank you!
