### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by lobroadib** [pyinstaller/pyinstaller#5658]
Hello, I am running a fresh install of Kali Linux, recently installed pyinstaller and tried converting a .py file to exe using pyinstaller, however I get the following errors. I have already googled for around two hours trying to find a fix, but cant find one. 

> 30 INFO: PyInstaller: 3.5+498e6ee058
30 INFO: Python: 3.9.2
32 INFO: Platform: Linux-5.10.0-kali3-amd64-x86_64-with-glibc2.31
33 INFO: wrote /home/pwner/Desktop/pytt.spec
35 INFO: UPX is available.
36 INFO: Extending PYTHONPATH with paths
['/home/pwner/Desktop', '/home/pwner/Desktop']
36 INFO: checking Analysis
44 INFO: checking PYZ
44 INFO: Building PYZ because PYZ-00.toc is non existent
44 INFO: Building PYZ (ZlibArchive) /home/pwner/Desktop/build/pytt/PYZ-00.pyz
Traceback (most recent call last):
  File "/usr/bin/pyinstaller", line 11, in <module>
    load_entry_point('PyInstaller==3.5+498e6ee058', 'console_scripts', 'pyinstaller')()
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/lib/python3/dist-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/lib/python3/dist-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "/home/pwner/Desktop/pytt.spec", line 18, in <module>
    pyz = PYZ(a.pure, a.zipped_data,
  File "/usr/lib/python3/dist-packages/PyInstaller/building/api.py", line 98, in __init__
    self.__postinit__()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/datastruct.py", line 158, in __postinit__
    self.assemble()
  File "/usr/lib/python3/dist-packages/PyInstaller/building/api.py", line 128, in assemble
    self.code_dict = {
  File "/usr/lib/python3/dist-packages/PyInstaller/building/api.py", line 129, in <dictcomp>
    key: strip_paths_in_code(code)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/utils.py", line 652, in strip_paths_in_code
    consts = tuple(
  File "/usr/lib/python3/dist-packages/PyInstaller/building/utils.py", line 653, in <genexpr>
    strip_paths_in_code(const_co, new_filename)
  File "/usr/lib/python3/dist-packages/PyInstaller/building/utils.py", line 660, in strip_paths_in_code
    return code_func(co.co_argcount, co.co_kwonlyargcount, co.co_nlocals, co.co_stacksize,
TypeError: an integer is required (got type bytes)

`

Thanks in advance for any sort of help!

**Comment by rokm** [comment]
> 30 INFO: PyInstaller: 3.5+498e6ee058
> 30 INFO: Python: 3.9.2

I doubt PyInstaller 3.5 supports python 3.9. Please try using the latest release.

**Comment by lobroadib** [comment]
> > 30 INFO: PyInstaller: 3.5+498e6ee058
> > 30 INFO: Python: 3.9.2
> 
> I doubt PyInstaller 3.5 supports python 3.9. Please try using the latest release.

That did indeed fix it! I cloned the git and ran pyinstaller from there. However, now when running pyinstaller with --onefile, there is not .exe in the relevant dist folder. There is a file there, but I am unable to open in on my windows system. Am i missing something obvious here?

Thanks

**Comment by rokm** [comment]
> That did indeed fix it! I cloned the git and ran pyinstaller from there. However, now when running pyinstaller with --onefile, there is not .exe in the relevant dist folder. There is a file there, but I am unable to open in on my windows system. Am i missing something obvious here?

You're building on linux, so you get a linux executable.

**Comment by lobroadib** [comment]
Is it possible to build on linux, and make an win executable or do i need to do it on a win system?

**Comment by rokm** [comment]
You need to do it on windows system (or under wine),

**Comment by lobroadib** [comment]
I managed to do it! It works how its supposed to. However, if you dont mind, is there any way to keep my compiled .exe to not close directly after the 'exec' command in the python file has completed? I have tried to add 'input()' in the .py file and then recompile it, but the exe still directly closes after the 'exec' has ran.

Hopefully you understand what i mean....

**Comment by rokm** [comment]
Hmm, can you provide a minimal example of what you're trying to achieve?

**Comment by lobroadib** [comment]
Essentially i generated a backdoor in python order to attack my own windows computer. The only command that this python file includes is "exec(__import__('base64').b64decode(__import__('codecs').getencoder('utf-8')('XXX')[0]". (replaced contents with XXX for obvious reasons). When running this compiled .py file, it closes directly after the exec() has been executed and therefore closes the connection. I want to somehow make it not directly close after the command has been executed as it needs to stay open in order for me to maintain a connection. 

Hopefully im making sense (:

**Comment by lobroadib** [comment]
The weird thing is that whatever i put after this exec() line in the .py does not seem to be executed.

**Comment by rokm** [comment]
Does the stuff inside exec get properly executed?

**Comment by lobroadib** [comment]
> Does the stuff inside exec get properly executed?

Id assume it does since everything works perfecly and stays up if i run it manually with python, the issue arises with the compiled .exe that closes directly after the exec line.

**Comment by rokm** [comment]
And if you comment out the exec statement, is the subsequent `input()` reached? Or if you put `exec` inside try/except block?

**Comment by lobroadib** [comment]
If i comment out the exec statement, the subsequent lines get executed. I tried adding a try/except block and this does actually keep the file open, and i do get a connection however it seems like the exec statement does not get fully read when in the try block. Could this be the case or do you think it could be something else?

**Comment by rokm** [comment]
I think your exec statement is erroring out, for one reason or another. If your payload is using any modules beyond what gets collected by pyinstaller by default, you'll probably need to add them to hiddenimports...

**Comment by lobroadib** [comment]
After some further testing i can confirm that the exec statement doesent work correctly when within the try block. However it does work when i run the python file manually in the terminal. The issue is only with the compiled .exe. Once i run it as a python file everything works perfectly. I'll try to find out if my payload uses modules that arent included within pyinstaller.
