### ISSUE TITLE
Clarify hidden source code claims

### ISSUE THREAD

**Issue by simaoafonso-pwt** [pyinstaller/pyinstaller#5662]
The documentation mentions the source code is hidden when compiling executables.

https://pyinstaller.readthedocs.io/en/stable/operating-mode.html#hiding-the-source-code

However, on runtime when the program exists with an exception, the traceback includes the filename and line numbers for the compiled code.

```
File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "PyInstaller/loader/pyimod03_importers.py", line 531, in exec_module
  File "main.py", line 4, in <module>
  File "<REDACTED_FILE>", line 423, in entrypoint
```

Encrypting the bytecode does nothing.

Where is this information stored, and can I remove it from the generated binaries?

**Comment by rokm** [comment]
The full filename leaking in tracebacks is a bug that's been (hopefully) resolved in `develop` branch.

If you consider tracebacks to be still revealing too much information about your code (line numbers, function and module names), then either [disable traceback](https://docs.python.org/3/library/sys.html#sys.tracebacklimit) or handle the exception yourself.

**Comment by simaoafonso-pwt** [comment]
> The full filename leaking in tracebacks is a bug that's been (hopefully) resolved in develop branch.

That seems to be b9fcbbf86bc71addafc830debe289e7edb2a5697(#5563), thanks.

The `sys.tracebacklimit` option seems to be what I was looking for, thanks for the pointer. Closing this.
