### ISSUE TITLE
HTTP error 403 Client Error: BadReputation

### ISSUE THREAD

**Issue by thuynh323** [pyinstaller/pyinstaller#5664]
Hello,

I was trying to install pyinstaller behind a corporate firewall and got the error below.

```python
$ pip install pyinstaller
Collecting pyinstaller
  ERROR: HTTP error 403 while getting https://files.pythonhosted.org/packages/b4/83/9f6ff034650abe9778c9a4f86bcead63f89a62acf02b1b47fc2bfc6bf8dd/pyinstaller-4.2.tar.gz#sha256=f5c0eeb2aa663cce9a5404292c0195011fa500a6501c873a466b2e8cad3c950c (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.5)
ERROR: Could not install requirement pyinstaller from https://files.pythonhosted.org/packages/b4/83/9f6ff034650abe9778c9a4f86bcead63f89a62acf02b1b47fc2bfc6bf8dd/pyinstaller-4.2.tar.gz#sha256=f5c0eeb2aa663cce9a5404292c0195011fa500a6501c873a466b2e8cad3c950c because of HTTP error 403 Client Error: BadReputation for url: https://files.pythonhosted.org/packages/b4/83/9f6ff034650abe9778c9a4f86bcead63f89a62acf02b1b47fc2bfc6bf8dd/pyinstaller-4.2.tar.gz for URL https://files.pythonhosted.org/packages/b4/83/9f6ff034650abe9778c9a4f86bcead63f89a62acf02b1b47fc2bfc6bf8dd/pyinstaller-4.2.tar.gz#sha256=f5c0eeb2aa663cce9a5404292c0195011fa500a6501c873a466b2e8cad3c950c (from https://pypi.org/simple/pyinstaller/) (requires-python:>=3.5)
```
When I pasted the URL into a browser, I got this.

>This site has been given a poor reputation score which could mean there is malicious or untrusted content on the site that could put [company name] electronic assets at risk. Please consider the risk before submitting a site review request.
>
>User: [my username]
URL: https://files.pythonhosted.org/packages/b4/83/9f6ff034650abe9778c9a4f86bcead63f89a62acf02b1b47fc2bfc6bf8dd/pyinstaller-4.2.tar.gz
URL Categories: Malicious Downloads (Dynamic) Looked up via GTI
Reputation: High Risk

I'm using Python 3.9.1 and I don't have this issue when installing other packages. Is there anything I can do (besides contacting the company IT) to fix this?

Thanks in advance.

**Comment by rokm** [comment]
That's a new twist on the usual anti-virus software issues...

Unfortunately, I suspect you are completely at the mercy of your company's IT and their proxy server intercepting your HTTP(S) requests.

**Comment by thuynh323** [comment]
In case someone has the same issue. Here is my solution.
From my PC, I downloaded the file into a Flask Drive, plugged it into my company computer installed the file from the local directory 😉 

```python
$ pip install file:/path_to/pyinstaller-4.2.tar.gz
```
