### ISSUE TITLE
PyInstlaller and Proper user of Wix Toolset

### ISSUE THREAD

**Issue by maksimu** [pyinstaller/pyinstaller#5665]
I'm trying to figure out what would be the easiest way to create an Installer using [Wix Toolset](https://wixtoolset.org/).

I'm building my app with One Folder (not one file) and then want to package into .msi file. I saw somewhere that I have to use `heat.exe` to create a list of all the files, but when I did that I got like 15,000 lines xml file that lists every single file. Not sure if that's the optimal solution or there could be some other way of properly packaging it.

**Comment by rokm** [comment]
Shouldn't this be a question for Wix Toolset's support?

**Comment by bwoodsend** [comment]
Never used Wix but it looks like that is what they expect you to do. Looking at their [howtos/files_and_registry/add_a_file](https://wixtoolset.org/documentation/manual/v3/howtos/files_and_registry/add_a_file.html) I'd expect to see somthing saying *use \* globs or a folder name to include whole folders* but they seem to be making it quite clear that one file gets its own block of xml.

Might I recommend your use [innosetup](https://jrsoftware.org/isinfo.php) instead? It does allow whole folders and is written in ino which is much more readable than xml. A test inno script I've used before:

```ino
; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!

[Setup]
AppName=Test
DefaultGroupName=tests
AppVersion=0.1.0
DefaultDirName={autopf}\Test
OutputBaseFilename=Test Installer

[Files]
Source: "dist/test/*"; DestDir: "{app}"

[Icons]
Name: "{group}\launch test"; Filename: "{app}\test.exe"; WorkingDir: "{app}"
```
