### ISSUE TITLE
EXE detected as Win32/Wacapew.C!ml by Microsoft Security Essentials on Windows 7

### ISSUE THREAD

**Issue by skoehler** [pyinstaller/pyinstaller#5668]
I created an EXE with Python 3.8.8 32 Bit using PyInstaller 4.2. The program uses pyusb 1.1.1 and pyserial 3.5.
Windows Defender on Windows 10 reports nothing. But Microsoft Security Essentials on Windows immediately reports a problem, specifically is labeled as `Win32/Wacapew.C!ml`. 

On VirtusTotal.com, the EXE has a score of 25/68 positives. Among others, the EXE is detected as `Gen:Variant.Mikey.118444`, `TrojanPSW.Python`, `Trojan.Mikey.D1CEAC`, ...

**Comment by skoehler** [comment]
This is probably a false positive. Can we do anything about that?

**Comment by rokm** [comment]
You can rebuild the bootloader yourself. Or try using the `develop` branch to see if setting the PE checksum helps any. Or, preferably, do both - check out `develop` branch, rebuild its bootloaders, and install from that. Due to changes in the bootloader code since the last release, that is likely do alleviate some false positives on its own...

**Comment by lexelby** [comment]
Do you expect building the bootloader to be helpful in general?  We tried that with Ink/Stitch but it didn't get rid of the false positives :/

**Comment by skoehler** [comment]
Is there some sort of procedure for this case? Can you contact anti-virus software authors somehow?
Anti-virus software should look at the EXE generated by PyInstaller as some sort of self-extracting application. Such are malign if and only if the the bootloader or the contexts of the archive are malign. Labeling all PyInstaller executables as malign, just in case somebody packed his/her Python virus with PyInstaller, is lazy and stupid.

**Comment by bwoodsend** [comment]
> Can you contact anti-virus software authors somehow?

Yes, this is about all you can do. Their website should have a *report false positives* page somewhere.

> Labeling all PyInstaller executables as malign, just in case somebody packed his/her Python virus with PyInstaller, is lazy and stupid.

Tell me about it.
