### ISSUE TITLE
from torch._C import * ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by zapaishchykova** [pyinstaller/pyinstaller#5676]
Hi! I can successfully pack and run executable on my local system. But when I try to run on other computer i get `from torch._C import * ImportError: DLL load failed: The specified module could not be found`
![image](https://user-images.githubusercontent.com/17569461/112831156-d4d12280-9093-11eb-8ca1-d5ef95c1230e.png)

my .spec file looks like:
```
# -*- mode: python ; coding: utf-8 -*-
import sys  
sys.setrecursionlimit(5000)
block_cipher = None
a = Analysis(['scene_selection.py'],
             pathex=['D:\\app'],
             binaries=[...],
             datas=[....],
             hiddenimports=['pkg_resources.py2_warn'],
             hookspath=None,
             runtime_hooks=None,
             excludes=None,
             cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='app',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True)
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=False,
               upx_exclude=[],
               name='app')
```

Any ideas on what is going on there?

**Comment by bwoodsend** [comment]
I'm guessing you're on Conda? If you are, try running it on your local system but in a plain `cmd` prompt - not the special Conda cmd you used to build it.

**Comment by zapaishchykova** [comment]
yes i am on conda, but even if i deactivate everything is ok on my system... could it be that nvidia toolkit needs to be installed prior on the remote?

**Comment by rokm** [comment]
Perhaps the target machine needs [VC runtime](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) installed? Torch DLLs are linked against `vcruntime140_1.dll`, which might not be collected by PyInstaller. You can also check your dist folder if that DLL was collected or not, and if not, try copying it...

**Comment by bwoodsend** [comment]
> but even if i deactivate everything

By *deactivate* do you mean `conda deactivate` or opening a fresh cmd prompt? The former doesn't really deactivate anything - Conda's DLL folder remains in `PATH`.

**Comment by zapaishchykova** [comment]
So, I have 3 systems, 2 of them I tested on and the .exe works without any problem. But these are pc that contain everything for the development - python, anaconda, cuda drivers etc. Tested without conda enviroment.

And then, I have a 3rd system of my client. Client does not have anything dev-related on his pc, and there i get this torch import issue. I have asked to install cuda libraries to see if that will help to resolve the issue .... If you have any other ideas what is going on there please let me know!

**Comment by zapaishchykova** [comment]
The issue was resolved by two extra steps:
1.download the Visual Studio dist:
VC 2017 - https://aka.ms/vs/15/release/VC_redist.x64.exe 

2. Intel openmp - https://anaconda.org/anaconda/intel-openmp/files 
Download win-64/intel-openmp-2018.0.0-8.tar.bz2 and put the dll files in Library\bin into a dir and append the path of it to the environment variable PATH

Thanks to everyone!
