### ISSUE TITLE
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: my_model\frozen_inference_graph.pb : The system cannot find the path

### ISSUE THREAD

**Issue by data-scientist-2020** [pyinstaller/pyinstaller#5677]
tensorflow.python.framework.errors_impl.NotFoundError: NewRandomAccessFile failed to Create/Open: my_model\frozen_inference_graph.pb : The system cannot find the path

Here I am woking on Mask RCNN object masking model. The script is working properly but getting the above issue on running executable file built on top of pyinstaller
tensorflow version: 1.15.0
Pyinstaller version: 4.2

**Comment by data-scientist-2020** [comment]
hi @bwoodsend can u suggest me any solution for this??

**Comment by rokm** [comment]
Check the path to your model; if you're using relative paths, the current working directory is probably not where you think it is.

**Comment by data-scientist-2020** [comment]
@rokm thanks..my issue got resolved
