### ISSUE TITLE
Trouble the logging from macOS app

### ISSUE THREAD

**Issue by RastaDill** [pyinstaller/pyinstaller#5692]
Hello. I ran into a logging problem with app on macOS.
If use logging to file, but if not set forced encoding 'utf-8' - log message may be not written the file if have non ASCII symbol, but if run application from binary all works.
If any case sys.getdefaultencoding() show 'utf-8'

* Python: 3.8.6
* PyInstaller: 4.2
* macOS: 10.13.6

Example:
simple_app.py
```
from tkinter import *
from pathlib import Path
import logging
import sys

def getMyLogger():
    logger = logging.getLogger('app')
    logger.setLevel(logging.DEBUG)
    fh = logging.FileHandler(
        Path.home().joinpath('log-file.log'),
        # encoding='utf-8'
    )
    fh.setFormatter(
        logging.Formatter("%(name)s - %(levelname)s - %(message)s"))
    logger.addHandler(fh)
    logger.info(sys.getdefaultencoding())
    logger.info("Empty message")
    logger.info("Пустое сообщение")
    return logger

def main():
    window = Tk()
    window.title("Test log")
    log = getMyLogger()
    btn = Button(
        window,
        text="Send message to Log",
        # command=lambda: log.info("Click")
        command=lambda: log.info("Клик")
    )
    btn.pack()
    window.mainloop()

if __name__ == '__main__':
    main()
```

simple_app.spec
```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['simple_app.py'],
    pathex=['.'],
    binaries=[],
    datas=[],
    hiddenimports=['logging'],
    hookspath=[],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False
)
pyz = PYZ(
    a.pure,
    a.zipped_data,
    cipher=block_cipher,
)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='SimpleApp',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
)
app = BUNDLE(
    exe,
    name='SimpleApp.app',
)
```

**Comment by bwoodsend** [comment]
>  If any case sys.getdefaultencoding() show 'utf-8'

Are you sure about this for console-less .app applications? I seem to remember it would return `None` in that case.

**Comment by rokm** [comment]
> If any case sys.getdefaultencoding() show 'utf-8'

While this is true, `sys.getdefaultencoding()` does not determine the default encoding for opened files. As per [docs](https://docs.python.org/3/library/functions.html#open), `locale.getpreferredencoding(False)` does.

And when running from terminal (either running `onedir` application or .app bundle via `open dist/program.app`, `locale.getpreferredencoding(False)` returns `UTF-8`. But if you open the .app bundle via Finder, it returns `US-ASCII`, hence the error (and this happens due to limited environment, as discussed in #5646).

**Comment by RastaDill** [comment]
> > If any case sys.getdefaultencoding() show 'utf-8'
> 
> Are you sure about this for console-less .app applications? I seem to remember it would return `None` in that case.

Yes, in log written 'utf-8'

> > If any case sys.getdefaultencoding() show 'utf-8'
> 
> While this is true, `sys.getdefaultencoding()` does not determine the default encoding for opened files. As per [docs](https://docs.python.org/3/library/functions.html#open), `locale.getpreferredencoding(False)` does.
> 
> And when running from terminal (either running `onedir` application or .app bundle via `open dist/program.app`), `locale.getpreferredencoding(False)` returns `UTF-8`. But if you open the .app bundle via Finder, it returns `US-ASCII`, hence the error (and this happens due to limited environment, as discussed in #5646).

Thanks for answering. I checked again and saw for myself.
