### ISSUE TITLE
Executable size using module matplotlib 3.4.x

### ISSUE THREAD

**Issue by interflexo** [pyinstaller/pyinstaller#5695]
Executable size of some project using module matplotlib until 3.3.4 is about 40Mb.
Using module matplotlib 3.4.0 or 3.4.1 the executable size jumps to 400Mb with no other code changes. App always works as expected.

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: 3.8
* Platform: Windows 10
* Did you also try this on another platform? No

**Comment by rokm** [comment]
Matplotlib 3.4.x is not supported by Pyinstaller 4.2 (see #5567); instead you'll have to use `develop` branch which contains the fix (#5568).
