### ISSUE TITLE
Executable file compiles fine but doesn't run

### ISSUE THREAD

**Issue by Nanobot567** [pyinstaller/pyinstaller#5704]
I compiled a python file using pyinstaller, and everything worked fine until I tried to run it. When I double-click it, nothing happens.

Here is my python code:

```
import pyautogui as p

p.alert("sup")
p.alert("this is a lame test")
```

And here is the console output:

[console output.txt](https://github.com/pyinstaller/pyinstaller/files/6267101/console.output.txt)

I am running Windows 10.

**Comment by bwoodsend** [comment]
Run it from terminal to see what's wrong.

**Comment by Nanobot567** [comment]
Thanks!
