### ISSUE TITLE
pyinstaller build package but - unable to get any image provider

### ISSUE THREAD

**Issue by ds2k5** [pyinstaller/pyinstaller#5714]
Hi,
using Windows 10 64bit with Python 3.9.4 (64bit)

if I run my python test script like this:

python test.py   this works.

then using **pyinstaller Version 4.2** to build a onefile-package
the exe I got say "unable to get any image provider"

How to fix this ?

test code:  test.py
```

import os
os.environ['KIVY_GL_BACKEND']='angle_sdl2'
import kivy
kivy.require('1.0.6') # replace with your current kivy version !

from kivy.app import App
from kivy.uix.label import Label


class MyApp(App):

    def build(self):
        return Label(text='Hello world')


if __name__ == '__main__':
    MyApp().run()

```

**pyinstaller --clean --onefile test.py**

when run:  python test.py

![Bildschirmfoto_2021-04-08_09-06-59](https://user-images.githubusercontent.com/11292286/113983086-d21bbd80-9849-11eb-8422-193d841933a7.png)

when run the exe

![Unbenannt](https://user-images.githubusercontent.com/11292286/113983574-58380400-984a-11eb-90c6-a2144d8c012d.PNG)

**Comment by ds2k5** [comment]
why closed ?

**Comment by rokm** [comment]
> os.environ['KIVY_GL_BACKEND']='angle_sdl2'

Are you building in environment without "proper" OpenGL? In that case, you'll need to `set KIVY_GL_BACKEND=angle_sdl2` in console prior to running PyInstaller. Otherwise, you get "Kivy Fatal Errror / GL: Minimum required OpenGL version not found" error dialog, which seems to prevent proper collection of kivy modules.

**Comment by rokm** [comment]
Also don't forget to package contents of `kivy_deps.sdl2.dep_bins` and `kivy_deps.angle.dep_bins` via .spec file, as outlined [here](https://kivy.org/doc/stable/guide/packaging-windows.html).

**Comment by ds2k5** [comment]
>Are you building in environment without "proper" OpenGL? 

without this 2 lines the test.py will not run.


spec file:   test.spec
```


# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['test.py'],
             pathex=['C:\\Users\\admin\\Desktop\\python\\kivy'],
             binaries=[],
             datas=[],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )

```

**Comment by rokm** [comment]
> > Are you building in environment without "proper" OpenGL?
> 
> without this 2 lines the test.py will not run.

Sure, but this also means that if you don't set `KIVY_GL_BACKEND` in your (shell) environment before running PyInstaller, the kivy hook for pyinstaller will also end up with incomplete list of modules to collect. At least that's the case in my VirtualBox VM, where I also need to specify KIVY_GL_BACKEND=angle_sdl2, otherwise I also get `Unable to get any Image provider` error.

> spec file: test.spec that was created by pyinstaller
> 
> ```
> 
> 
> # -*- mode: python ; coding: utf-8 -*-
> 
> block_cipher = None
> 
> 
> a = Analysis(['test.py'],
>              pathex=['C:\\Users\\admin\\Desktop\\python\\kivy'],
>              binaries=[],
>              datas=[],
>              hiddenimports=[],
>              hookspath=[],
>              runtime_hooks=[],
>              excludes=[],
>              win_no_prefer_redirects=False,
>              win_private_assemblies=False,
>              cipher=block_cipher,
>              noarchive=False)
> pyz = PYZ(a.pure, a.zipped_data,
>              cipher=block_cipher)
> exe = EXE(pyz,
>           a.scripts,
>           a.binaries,
>           a.zipfiles,
>           a.datas,
>           [],
>           name='test',
>           debug=False,
>           bootloader_ignore_signals=False,
>           strip=False,
>           upx=True,
>           upx_exclude=[],
>           runtime_tmpdir=None,
>           console=True )
> ```

Yeah, you'll have to modify it as per [kivy documentation](https://kivy.org/doc/stable/guide/packaging-windows.html) to include `sdl2` and `angle` deps.

**Comment by ds2k5** [comment]
made this change in: test.spec

```
# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(['test.py'],
             pathex=['C:\\Users\\admin\\Desktop\\python\\kivy'],
             binaries=[],
             datas=[],
             *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins + gstreamer.dep_bins)],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )

```


python -m PyInstaller test.spec --onefile
```

got this errors:

93 INFO: PyInstaller: 4.2
93 INFO: Python: 3.9.4
93 INFO: Platform: Windows-10-10.0.19041-SP0
93 INFO: UPX is not available.
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 124, in <module>
    run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 114, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\__main__.py", line 65, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 725, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py", line 672, in build
    exec(code, spec_namespace)
  File "test.spec", line 10, in <module>
    *[Tree(p) for p in (sdl2.dep_bins + glew.dep_bins + gstreamer.dep_bins)],
NameError: name 'sdl2' is not defined
```

**Comment by rokm** [comment]
Read the docs properly - I'm not going to fix basic mistakes for you.

**Comment by ds2k5** [comment]
> At least that's the case in my VirtualBox VM, where I also need to specify KIVY_GL_BACKEND=angle_sdl2

yes I it s Virtual Machine where I run Windows 10

**Comment by rokm** [comment]
> yes I it s Virtual Machine where I run Windows 10

So you'll probably need to set KIVY_GL_BACKEND=angle_sdl2 to your shell environment before you run pyinstaller:
```
set KIVY_GL_BACKEND=angle_sdl2
python -m PyInstaller --clean --noconfirm test.spec
```

(as a side note, passing `--onefile` when building from .spec has no effect).

**Comment by ds2k5** [comment]
Bulid the package on a pyh. System with windows 10.
The build is sucessful. exe runs on the phy. system but not in the VM.

**Comment by rokm** [comment]
Sounds like OpenGL issue, although it's difficult to say without knowing the error message.
