### ISSUE TITLE
matplotlib 3.4.x creating a issue

### ISSUE THREAD

**Issue by ask-kumbar** [pyinstaller/pyinstaller#5715]
python 3.8.8
pyinstaller 4.2
matplotlib 3.4.X

 --------This output is for matplotlib 3.4.x version------------------- 
Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib;
>>> print(matplotlib. __version__)
3.4.1
>>> print(matplotlib._get_data_path())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'matplotlib' has no attribute '_get_data_path'

I think u need to update the matplotlib hook for this to work properly because if i try to create a bundle of matplotlib its coping the project files from where i am running the pyinstaller into matplotlib->mpl-data directory

---------matplotlib 3.3.4 is working fine for pyinstaller-------

Python 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import matplotlib;
>>> print(matplotlib._get_data_path())
C:\tools\python3.8\lib\site-packages\matplotlib\mpl-data

please check into it

**Comment by bwoodsend** [comment]
This is already fixed in #5568.
