### ISSUE TITLE
outdated version of pyinstaller on conda channel?

### ISSUE THREAD

**Issue by RubendeBruin** [pyinstaller/pyinstaller#5724]
Just went almost crazy trying to rebuild my previously function .exe on a new machine. Turns out that:

When installing pyinstaller using conda I get version 3.3
when installing pyinstaller using conda in combination with the conda-forge channel I get version 4.4

Version 3.3 does not produce workable Qt guis for me (using pyside2, latest version and previous versions of pyside2).

If there a reason for the older version on conda?

**Comment by bwoodsend** [comment]
We have nothing to do with the conda packages. Try asking [conda-forge/pyinstaller-feedstock](https://github.com/conda-forge/pyinstaller-feedstock/).
