### ISSUE TITLE
16-bit application not compatible

### ISSUE THREAD

**Issue by BernardoB95** [pyinstaller/pyinstaller#5727]
Hi,

I was wondering if there is a way to choose the executable output architecture. In some computers im receiving an imcompatibility error due to the fact that the executable is a 16-bit application. Is there a way to correct this?

Thanks in advance.

**Comment by bwoodsend** [comment]
The architecture is determined by the architecture of the Python installation running PyInstaller. And no - PyInstaller is not and probably never will be a cross compiler so you can't change the architecture. That said, I seriously doubt that you do have a 16 bit executable - unless your running a raspery pi from 2005 or something. They disappeared from desktop PCs a very long ago.

**Comment by BernardoB95** [comment]
Thanks for your quick response!
I was skeptical too, however the error message mentions the architecture being 16-bits. That being said, the computer architecture im using is 64-bits and the python's architecture as well.
![Erro 16 bits](https://user-images.githubusercontent.com/11463758/114397366-00183f00-9b75-11eb-9518-80a976e51d82.png)

**Comment by rokm** [comment]
If you're freezing your application on 64-bit machine with 64-bit python, then the resulting application should also be 64-bit. So this looks like a weird case of mis-identification.

Does this happen only with this frozen application, or any frozen application you create with PyInstaller (e.g., a simple hello world script)?

**Comment by BernardoB95** [comment]
This is my first time creating an executable file with PyInstaller. The .exe runs fine on my machine and some others, however there are a few that display the same error  (all of them 64-bit architecture) which is a bit odd. I'll try to do it with a simple hello world and see what happens.

**Comment by rokm** [comment]
Hmm, what version of PyInstaller are you using, and what kind of build is that, `onefile` or `onedir`?

**Comment by bwoodsend** [comment]
Try and find the simplest example you can which still breaks then fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) so we all know what you're doing.

**Comment by BernardoB95** [comment]
> Hmm, what version of PyInstaller are you using, and what kind of build is that, `onefile` or `onedir`?

I had to create beforehand a spec file to add more recursivity, so the command I used was `pyinstaller --onefile main.spec`

**Comment by BernardoB95** [comment]
> Try and find the simplest example you can which still breaks then fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) so we all know what you're doing.

Perfect! Will do! 

Thank you so much for the support.

**Comment by rokm** [comment]
> pyinstaller --onefile main.spec

`--onefile`has no effect when building from .spec. But if you made your base .spec using `--onefile`, then the spec reflects that (it contains `Analysis`, `PYZ` and `EXE` but no `COLLECT`).

Anyway, for a `onefile` build, this might be issue with missing manifest, which affects some older PyInstaller versions.

**Comment by BernardoB95** [comment]
> Anyway, for a `onefile` build, this might be issue with missing manifest, which affects some older PyInstaller versions.

I forgot to mention before, the version of pyinstaller im using is v4.2.

**Comment by BernardoB95** [comment]
Doing some tests, I realized that this error occurs whenever the repository(contains de .exe) is downloaded as a ZIP, however when it is cloned(Im using Git Bash) it works perfectly. Any thoughts or ideas as to what can I do?

Thank you so much for your help.

**Comment by bwoodsend** [comment]
> this error occurs whenever the repository(contains de .exe) is downloaded as a ZIP

Uhmm you're not giving me much information here! Which repository? PyInstaller? The program your trying to compile? Something else entirely?

**Comment by BernardoB95** [comment]
> > this error occurs whenever the repository(contains de .exe) is downloaded as a ZIP
> 
> Uhmm you're not giving me much information here! Which repository? PyInstaller? The program your trying to compile? Something else entirely?

The link to the repo is the following: https://github.com/BernardoB95/Extrator_SPEDFiscal
If you clone the repo and just run in the cmd `start main.exe -v`, it should run smoothly and you will find the output data on the data directory of the project, however if you try to do the same downloading the repo as a ZIP it will give the error mentioned above.

**Comment by BernardoB95** [comment]
Figured it out.
Main.exe was uploaded using Git LFS, however the option in the repository to enable these files was not selected. Thats why with a clonning operation, git knew to download the file that the .gitattribute was pointing, but during zip downloads the browser didn't.

Im going to close this issue, thank you so much for your help. 
I really appreciate it.
