### ISSUE TITLE
Error importing PIL module in multipackage executable

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#573]
**Original date**: 2012/06/28
**Original reporter**: *ddwiggins AND advpubtech DOT  COOM *

I've found an error trying to run an executable built as part of a multipackage.

In the attached example, I've taken the test_PIL example from buildtests/libraries (with additional imports), added a dummy.py script, and added a MERGE directive in the spec file to build them together.  When this is run, a traceback occurs with the message "ImportError: The _imaging C module is not installed".

I've included the output from the build and the run in the zip file as the file 'execution.out'.

This was done using the 'develop' branch.

**Comment by matysek** [comment]
I believe this is fixed in python3 branch since support for namespace packages was implemented.
