### ISSUE TITLE
Cannot run exe: pyiboot01_bootstrap

### ISSUE THREAD

**Issue by ghostiek** [pyinstaller/pyinstaller#5739]
## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.2
* Version of Python: e.g. 3.9.4
* Platform: Windows 10
* Did you also try this on another platform? Does it work there? No, I haven't.

### A minimal example program which shows the error

I made an application using PySide2 and am trying to distribute it. Here is the command line I ran

`pyinstaller qprojstudio.py --debug all --noupx -w --onedir`

### Stacktrace / full error message

I get 3 error messages when I run the exe.

![qpaprecstudio_0uzxaST7Oz](https://user-images.githubusercontent.com/20328575/114858949-63f76d80-9dea-11eb-859a-870603f821df.png)
![qpaprecstudio_J5hvLv4SdG](https://user-images.githubusercontent.com/20328575/114858957-6659c780-9dea-11eb-89e3-6e4d700d9156.png)
![qpaprecstudio_FoAanS18HK](https://user-images.githubusercontent.com/20328575/114858962-68238b00-9dea-11eb-8fbb-f6fb51fa1932.png)

Here is the full log from the command prompt when I run, its long so I'll use a pastebin https://pastebin.com/DArJKC89

**Comment by rokm** [comment]
That should be fixed in `develop` by #5477. In PyInstaller 4.2 (and earlier), `--debug all` and noconsole (`-w`) are incompatible and result in an error.

**Comment by ghostiek** [comment]
Thanks. Got other issues with PyInstaller that I'll try to work through but they're unrelated to this post.
