### ISSUE TITLE
FreeBSD stopped working on 4.3

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#5745]
Building executable on FreeBSD stopped working on the latest PyInstaller release (4.3)

```
Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>
```

Everything is working perfectly on PyInstaller 4.2

* PtInstaller 4.3
* Python 3.7
* FreeBSD 10.3
* Working on other platforms

I have tried to follow the guide building on docker for FreeBSD but it fails, after importing the image and executing the listed command this is the error
```
➜  freebsd-cross-build git:(master) docker run -v $(pwd):/io -it freebsd-cross-build bash -c "cd /io/bootloader; ./waf all"

bash: line 0: cd: /io/bootloader: No such file or directory
bash: ./waf: No such file or directory
```

**Comment by rokm** [comment]
Does it work if you explicitly ignore the wheel? I.e., `pip install pyinstaller==4.3 --no-binary pyinstaller`

**Comment by bwoodsend** [comment]
> bash: line 0: cd: /io/bootloader: No such file or directory

Are you sure `pwd` is the root of PyInstaller's git repo?

**Comment by bwoodsend** [comment]
> FreeBSD 10.3

That's a very old FreeBSD - older than the `freebsd-cross-build` image targets so it's unlikely that a bootloader built on that docker image will run on 10.3. If you want 10.3 support you should just compile natively on FreeBSD 10.3 and forget about docker.

**Comment by arossert** [comment]
@rokm Looks like the `--no-binary pyinstaller` did the trick, Thanks.
