### ISSUE TITLE
Documentation Error in "bootloader-building.rst" and "usage.rst"

### ISSUE THREAD

**Issue by JordyScript** [pyinstaller/pyinstaller#5752]
In the documentation in 2 places ([here](https://github.com/pyinstaller/pyinstaller/blob/745f03c7277cc2214d2e0ca6e2a9bd81b8c906fe/doc/bootloader-building.rst) and [here](https://github.com/pyinstaller/pyinstaller/blob/87c6f023123ea4e3ecdd2289f4f9bf9c5cb1841d/doc/usage.rst)), the following incorrect line of code is shown:

```bash
$ python -c "import sys; print(sys.maxsize) <= 2**32"
```

It should be:

```bash
$ python -c "import sys; print(sys.maxsize <= 2**32)"
```

The mistake is that in the current version the number on the right is being compared to the return value of the print function, which is None. Placing the parenthesis after the number ensures comparison with sys.maxsize instead. 

Not sure what's easier for you guys, me forking and writing a pull request, or you just implementing the simple fix yourselves. I'm thinking the latter, hence this issue.

Thanks for the excellent tool.

**Comment by bwoodsend** [comment]
Thanks for pointing that one out. It's gone now...
