### ISSUE TITLE
getting something error like this " %1 is not a valid Win32 application. (Error code 193) "

### ISSUE THREAD

**Issue by its-shubham2323** [pyinstaller/pyinstaller#5755]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: e.g. 3.7
* Platform: e.g GNU/Linux (distribution), Windows (language settings), OS X, conda, FreeBSD
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
53243 INFO: Warnings written to D:\NS Word\build\main_complete\warn-main_complete.txt
53468 INFO: Graph cross-reference written to D:\NS Word\build\main_complete\xref-main_complete.html
53587 INFO: checking PYZ
53624 INFO: Building PYZ because PYZ-00.toc is non existent
53639 INFO: Building PYZ (ZlibArchive) D:\NS Word\build\main_complete\PYZ-00.pyz
57333 INFO: Building PYZ (ZlibArchive) D:\NS Word\build\main_complete\PYZ-00.pyz completed successfully.
57528 INFO: checking PKG
57578 INFO: Building PKG because PKG-00.toc is non existent
57591 INFO: Building PKG (CArchive) PKG-00.pkg
109557 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
109587 INFO: Bootloader c:\users\lenovo\appdata\local\programs\python\python39\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
109590 INFO: checking EXE
109591 INFO: Building EXE because EXE-00.toc is non existent
109592 INFO: Building EXE from EXE-00.toc
109915 INFO: Copying icons from D:\NS Word\google_docs.png
Unable to load icon file D:\NS Word\google_docs.png
    %1 is not a valid Win32 application. (Error code 193)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
Ah, that. What it's really trying to say is:

*I can't use PNG images. I can use a .ico file or copy the .ico from another exe file that already has an icon. Please convert your PNG to .ico then try again.*

Unfortunately, it verifies that your PNG is not a .ico but then just assumes that it is a valid EXE (which of course it isn't - it's a picture) and points Windows API at it which raises the cryptic error:

> Unable to load icon file D:\NS Word\google_docs.png
    %1 is not a valid Win32 application. (Error code 193)

**Comment by its-shubham2323** [comment]
> Ah, that. What it's really trying to say is:
> 
> _I can't use PNG images as icons on Windows. I can use a .ico file or copy the .ico from another exe file that already has an icon. Please convert your PNG to .ico then try again._
> 
> Unfortunately, it verifies that your PNG is not a .ico but then just assumes that it is a valid EXE (which of course it isn't - it's a picture) and points Windows API at it which raises the cryptic error:
> 
> > Unable to load icon file D:\NS Word\google_docs.png
> > %1 is not a valid Win32 application. (Error code 193)
> 
> I meant to change that yonks ago but never did...

Alright, I'll try to convert png files to.ico files thanks for the ultimate response.
Happy to use Pyinstaller ...!
