### ISSUE TITLE
Running Kivy on RPi 4

### ISSUE THREAD

**Issue by Enorio** [pyinstaller/pyinstaller#5757]
I have a project that uses kivy and it runs on rpi 3 b+. I use pyinstaller to create an executable and it works fine, even when I run it in a clean buster lite image.

But now I want to use the RPi 4 and I'm having trouble in running the executable.
I installed kivy through documentation (and also all the dev libs and SDL2 needed), and:
- Running `python main.py` works
- Generating the executable through pyinstaller and then running it works
- Use the same executable in a clean buster lite image on RPi 4 does not work, giving the following output:

```[INFO   ] [Logger      ] Record log in /home/pi/.kivy/logs/kivy_21-04-20_1.txt
[INFO   ] [Kivy        ] v2.0.0
[INFO   ] [Kivy        ] Installed at "/tmp/_MEIGxt9Rs/kivy/__init__.pyc"
[INFO   ] [Python      ] v3.7.3 (default, Jan 22 2021, 20:04:44) 
[GCC 8.3.0]
[INFO   ] [Python      ] Interpreter at "/home/pi/foo"
[INFO   ] [Factory     ] 186 symbols loaded
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Could not initialize OpenGL / GLES library'
  File "kivy/core/__init__.py", line 70, in core_select_lib
  File "kivy/core/window/window_sdl2.py", line 152, in __init__
  File "kivy/core/window/__init__.py", line 982, in __init__
  File "kivy/core/window/window_sdl2.py", line 289, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 226, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die
[INFO   ] [Text        ] Provider: sdl2
Segmentation fault
```

Is there something missing? Is pyinstaller not zipping all the necessary .so? I use this [.spec](https://pastebin.com/CErHixra)
I also had to add manually these libs because the audio was not working, and it couldn't find the gstreamer libs.

**Comment by rokm** [comment]
> sdl2 - RuntimeError: b'Could not initialize OpenGL / GLES library'

Can you check if SDL libraries are included in the build?

**Comment by Enorio** [comment]
I printed the binaries, and the output is this https://pastebin.com/ByhXLP8t
I search for sdl2 and got 20 matches.

**Comment by rokm** [comment]
When you run on RPi 3, does it also use `sdl2` as Window backend?

[This](https://kivy.org/doc/stable/installation/installation-rpi.html) seems to suggest that different Window and OpenGL providers are used by default on RPi 3 and on RPi 4. Does it make any difference if you force `gl` OpenGL backend instead of `sdl2` one via `KIVY_GL_BACKEND`?

**Comment by Enorio** [comment]
In RPi 3, the window provider is `egl_rpi` and the gl backend provider is `gl`
```
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: egl_rpi
[INFO   ] [GL          ] Using the "OpenGL ES 2" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 2.0'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'VideoCore IV HW'>
[INFO   ] [GL          ] OpenGL parsed version: 2, 0
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 1.00'>
[INFO   ] [GL          ] Texture max size <2048>
[INFO   ] [GL          ] Texture max units <8>
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [AudioGstplayer] Using Gstreamer 1.14.4.0
```

In RPi 4, the window provider is `sdl2` and gl backend are is `gl` as default
```
[INFO   ] [Image       ] Providers: img_tex, img_dds, img_sdl2, img_pil (img_ffpyplayer ignored)
[INFO   ] [Window      ] Provider: sdl2
[INFO   ] [GL          ] Using the "OpenGL" graphics system
[INFO   ] [GL          ] Backend used <gl>
[INFO   ] [GL          ] OpenGL version <b'OpenGL ES 3.1 Mesa 19.3.2'>
[INFO   ] [GL          ] OpenGL vendor <b'Broadcom'>
[INFO   ] [GL          ] OpenGL renderer <b'V3D 4.2'>
[INFO   ] [GL          ] OpenGL parsed version: 3, 1
[INFO   ] [GL          ] Shading version <b'OpenGL ES GLSL ES 3.10'>
[INFO   ] [GL          ] Texture max size <4096>
[INFO   ] [GL          ] Texture max units <16>
[INFO   ] [Window      ] auto add sdl2 input provider
[INFO   ] [Window      ] virtual keyboard not allowed, single mode, not docked
[INFO   ] [Text        ] Provider: sdl2
[INFO   ] [AudioGstplayer] Using Gstreamer 1.14.4.0
[INFO   ] [Audio       ] Providers: audio_gstplayer, audio_sdl2 (audio_ffpyplayer ignored)
[INFO   ] [Base        ] Start application main loop
[INFO   ] [GL          ] NPOT texture support is available
```

**Comment by rokm** [comment]
Hmm, just to clarify - you are able to freeze your application on RPi4 Buster with development environment and the frozen application runs there, but if you copy it to a clean RPi 4 Buster system, it does not? (So RPi3 is actually irrelevant here.)

**Comment by Enorio** [comment]
In the clean image, the `libGLESv2.so.2` is in fact missing. 
What i did was copy this lib to the clean image (and called `ldconfig`), but now the error is this:

```
[INFO   ] [Window      ] Provider: sdl2
[CRITICAL] [Window      ] Unable to find any valuable Window provider. Please enable debug logging (e.g. add -d if running from the command line, or change the log level in the config) and re-run your app to identify potential causes
sdl2 - RuntimeError: b'Could not get EGL display'
  File "kivy/core/__init__.py", line 70, in core_select_lib
  File "kivy/core/window/window_sdl2.py", line 152, in __init__
  File "kivy/core/window/__init__.py", line 982, in __init__
  File "kivy/core/window/window_sdl2.py", line 289, in create_window
  File "kivy/core/window/_window_sdl2.pyx", line 226, in kivy.core.window._window_sdl2._WindowSDL2Storage.setup_window
  File "kivy/core/window/_window_sdl2.pyx", line 74, in kivy.core.window._window_sdl2._WindowSDL2Storage.die

x11 - ModuleNotFoundError: No module named 'kivy.core.window.window_x11'
  File "kivy/core/__init__.py", line 62, in core_select_lib

[INFO   ] [Text        ] Provider: sdl2
Segmentation fault
```

Maybe I'm missing other libs?

**Comment by rokm** [comment]
If the clean image is missing `libGLESv2.so.2`, which serves as a vendor-neutral dispatch library, I find no reason to believe that the actual driver providing the implementation is available, either. 

You'll probably need to look into setting up a minimal working OpenGL / ES image. Perhaps installing `libegl-mesa0` via `apt` will suffice?

**Comment by rokm** [comment]
Or you could perhaps try installing `libgl1-mesa-dev` and `libgles2-mesa-dev` and observe their mesa-related dependencies.

**Comment by Enorio** [comment]
That was it!!

I installed the `libegl-mesa0` and it did the work :smile: 
Thank you so much for the quick replies, I was with this issue for days :smiley:
