### ISSUE TITLE
pyinstaller in combination with ESRI's arcpy

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#576]
**Original date**: 2012/07/17
**Original reporter**: _herberga AND noord DASH holland DOT nl_

I run into problems with pyinstaller and arcpy. I think the licensing mechanism in arcpy causes the problems. 

Are you aware of this issue and is there a solution to this problem?
I want to ditribute the application using pyQt en arcpy. The user's who use it have a valid arcview license for ArcGIS.

**Comment by blah238** [comment]
I just wanted to update this issue with some additional information.

I came across @JamesRamm's [`archook`](https://github.com/JamesRamm/archook) which helps with locating arcpy's directories and putting them on `sys.path`.

There were still a couple of issues such as needing to add a hidden `glob` import, add a fake `site-modules` directory to `sys.path`, and put a fake `numpy` module in `sys.modules` (could have added it as a hidden import as well but why bloat the filesize for something that won't be used?).

Here's the runtime hook code:

```py
import sys

# Add arcpy's directories to sys.path
from archook import get_arcpy
get_arcpy()

# Additional tweaks to placate arcpy
from types import ModuleType
sys.path.append('./site-packages')  # Add a dummy site-packages folder to sys.path
sys.modules['numpy'] = ModuleType('numpy')  # Add a fake numpy module to sys.modules
```

And here's the relevant part of my `.spec` file:

```py
# ...
    hiddenimports=['glob'],
    runtime_hooks=['./hooks/rthooks/pyi_rth_arcpy.py'],
    excludes=['arcpy'],
# ...
```

Interested in if anyone else has come up with another solution to using arcpy with a frozen executable. An official hook would be welcomed BTW!

One question I have was how to both exclude `arcpy` and have a build-time hook run for it? If I add it to my excludes, my build-time arcpy hook is skipped. If I don't exclude it in the spec file, but put it in the excludedmodules property of the build-time hook, it is not excluded. Catch-22?

Using `3.3.dev0+483c819`.

**Comment by mbishopp** [comment]
@blah238, I tried your method, but got a bunch of errors in the import of arcpy in my main code.  Here is what I see:
![image](https://user-images.githubusercontent.com/6955422/29792303-dbe825b6-8bf4-11e7-9e36-1174250f0455.png)
Any ideas on what I can do to make this work?  (I'm definitely a newby, so please go easy :))

**Comment by channabasavagola** [comment]
Thanks, @blah238 and @jamesRamm for the workaround. It helped me bundle my python script with Arcpy functionalities into a .exe. I'm now able to run the exe on the same computer with ArcGIS installed, but I wanted to run it on a computer where ArcGIS is not installed (Basically Linux using Wine emulator). Can you help me?

**Comment by alanscandrett** [comment]
> Thanks, @blah238 and @JamesRamm for the workaround. It helped me bundle my python script with Arcpy functionalities into a .exe. I'm now able to run the exe on the same computer with ArcGIS installed, but I wanted to run it on a computer where ArcGIS is not installed (Basically Linux using Wine emulator). Can you help me?

That would entail copying the ArcPy libs in whole or partially, in either case that breaks the ArcPy EULA and is not advisable.

**Comment by JamesRamm** [comment]
Hi @channabasavagola 
Running a script that uses ArcPy on a computer where arcGIS is not installed will most certainly not work as they include license checks when you import arcpy

I believe you can install the 'ArcGIS API For Python' on any system (https://developers.arcgis.com/python/), but its functionality, specifically the 'arcpy' functionality will be limited without required licenses.

Unless you have a specific need for reading ArcGIS proprietary data files then my recommendations on linux (or any OS for that matter) is *always* to  use the open source OSGeo software. This includes QGis, but for developing your own scripts/software, GDAL alone will often provide all you need
