### ISSUE TITLE
Error about exe runing on another computer:ImportError:DLL load failed

### ISSUE THREAD

**Issue by saberKafu** [pyinstaller/pyinstaller#5768]
Traceback (most recent call last):
  File "profit_3.0.py", line 2, in <module>
  File "c:\users\zpf\appdata\local\programs\python\python37\lib\site-packages\Py
Installer\loader\pyimod03_importers.py", line 493, in exec_module
  File "wx\__init__.py", line 17, in <module>
  File "c:\users\zpf\appdata\local\programs\python\python37\lib\site-packages\Py
Installer\loader\pyimod03_importers.py", line 493, in exec_module
  File "wx\core.py", line 12, in <module>
ImportError: DLL load failed: 找不到指定的模块。

**Comment by rokm** [comment]
Have you tried installing [VC redistributable](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) on the target computer?

**Comment by saberKafu** [comment]
> Have you tried installing [VC redistributable](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) on the target computer?

I tried download and installing VC 2015,but it not works

**Comment by rokm** [comment]
What's the Windows version on the build and the target machine, then?

And what is the python version, and the wxPython version?

**Comment by saberKafu** [comment]
> What's the Windows version on the build and the target machine, then?
> 
> And what is the python version, and the wxPython version?

Windows version on both build and target computer is windows 10,python version 3.7,wxpython version 4.0.3

**Comment by rokm** [comment]
What's the full python version, i.e., 3.7.x?

**Comment by saberKafu** [comment]
> What's the full python version, i.e., 3.7.x?

python 3.7.8.rcl

**Comment by rokm** [comment]
I think I've managed to reproduce this - in my case, building with wxpython 4.0.3 results in missing `msvcp140.dll`. 

Copying it from `c:\windows\system32` on the build machine to the application's dir should do the trick. 

As should installing [`Microsoft Visual C++ Redistributable for Visual Studio 2015, 2017 and 2019`](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) on the target machine.

**Comment by rokm** [comment]
And as a side note, it seems to work out-of-the box with wxpython 4.1.1, presumably because it bundles its own copy of `msvcp140.dll`.

**Comment by saberKafu** [comment]
> And as a side note, it seems to work out-of-the box with wxpython 4.1.1, presumably because it bundles its own copy of `msvcp140.dll`.

Thanks you for your help,i update wxpython to 4.1.1 and it works
