### ISSUE TITLE
cannot use pyinstaller 

### ISSUE THREAD

**Issue by democraz20** [pyinstaller/pyinstaller#5775]
ive installed pyinstaller on windows10 and python microsoft store on a windows powershell
but when i try to run it 
```shell
pyinstaller --help
```
the error returns as 
```
pyinstaller : The term 'pyinstaller' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ pyinstaller
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pyinstaller:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
so i try to install pyinstaller again and it returns as 
```
Requirement already satisfied: pyinstaller in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (5.0.dev0)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyinstaller) (0.2.0)
Requirement already satisfied: altgraph in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyinstaller) (0.17)
Requirement already satisfied: pyinstaller-hooks-contrib>=2020.6 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyinstaller) (2021.1)
Requirement already satisfied: pefile>=2017.8.1 in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pyinstaller) (2019.4.18)
Requirement already satisfied: setuptools in c:\program files\windowsapps\pythonsoftwarefoundation.python.3.9_3.9.1264.0_x64__qbz5n2kfra8p0\lib\site-packages (from pyinstaller) (49.2.1)
Requirement already satisfied: future in c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0\localcache\local-packages\python39\site-packages (from pefile>=2017.8.1->pyinstaller) (0.18.2)
```
ive gotten stuck for a couple of hours now
yes im using the latest pip
if anyone have a clue of this please help

**Comment by rokm** [comment]
> c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0

Is that python from Windows app store? Even if you do get its Scripts directory into `PATH` and get `pyinstaller` shim script recognized as a command, it probably still won't work anyway, because it tends to hide the python library...

**Comment by democraz20** [comment]
> > c:\users\user\appdata\local\packages\pythonsoftwarefoundation.python.3.9_qbz5n2kfra8p0
> 
> Is that python from Windows app store? Even if you do get its Scripts directory into `PATH` and get `pyinstaller` shim script recognized as a command, it probably still won't work anyway, because it tends to hide the python library...

    Well is there anyway to get it working?

**Comment by rokm** [comment]
> Well is there anyway to get it working?

Not with python from Windows app store.

**Comment by democraz20** [comment]
> > Well is there anyway to get it working?
> 
> Not with python from Windows app store.
> 
> EDIT: FWIW, you can try running it as `python -m PyInstaller` instead of using `pyinstaller` shim...

```python -m Pyinstaller --help```
Will work right? According to your comment

**Comment by rokm** [comment]
> python -m Pyinstaller --help
>  Will work right? According to your comment

It should start the PyInstaller, yes. 

But as I said, you probably won't be able to freeze applications with it, due to python library not being visible.
