### ISSUE TITLE
Problem with scikitimage and _rolling_ball_cy

### ISSUE THREAD

**Issue by PawelDarlak** [pyinstaller/pyinstaller#5777]
Hello Everyone,

When I run exe file on my computer everything works ok but when I try to run on virtual machine I get the error  File "skimage\restoration\rolling_ball.py", line 3, in <module>
ImportError: DLL load failed while importing _rolling_ball_cy: The specified module could not be found.
[2244] Failed to execute script Diopomat

I was trying to add by --hidden-import --hidden-import "skimage.restoration._rolling_ball_cy"
I have spent a couple of hours to resolve this problem but I had to give up :(
Please help me, how to fix it.

Best regards
Pavel

**Comment by rokm** [comment]
Sounds like your VM needs [Visual Studio 2015 / 2017 / 2019 redistributable](https://support.microsoft.com/en-us/topic/the-latest-supported-visual-c-downloads-2647da03-1eea-4433-9aff-95f26a218cc0) installed.

We recently merged a commit that might help with vcredist DLLs (#5770); but I suspect that in this particular case, it is `vcomp140.dll` that's missing, so we'll need to add it to that list...
