### ISSUE TITLE
Can't use pyinstaller

### ISSUE THREAD

**Issue by democraz20** [pyinstaller/pyinstaller#5783]
I did a ```python -m pip install pyinstaller``` because I use the python version from python.org not the microsoft store 
And I also tried to reinstall it to make sure everything was right 
After that I did ```python -m Pyinstaller``` but it returns as ```not a module``` 
I've been met with this problem for a couple of days now 
Please help

**Comment by rokm** [comment]
Upper/lower-case matters, so it should be: `python -m PyInstaller`.
