### ISSUE TITLE
SymPy bug with PyInstaller

### ISSUE THREAD

**Issue by Yannik-developer** [pyinstaller/pyinstaller#5790]
Hello!
I make an exe file of Python project which is using SymPy but get a bug. After running exe I get recursive error and my program doesn't work. Any solutions?

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).
