### ISSUE TITLE
Pyinstaller failed to recognise PyMI module

### ISSUE THREAD

**Issue by zackfair1412** [pyinstaller/pyinstaller#5791]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
recently i try to use pyinstaller with pymi module inside my code. After failed for several time, i try debug the code and it return with "pkg_resources.DistributionNotFound: PyMI..." (using windowed command). I have try several solution i found online but none of them works in my case (such as #4809)

## Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.7.8
* Platform: Windows (English)
* Did you also try this on another platform? Does it work there?
no, i don't have other platform

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
Traceback: [Traceback (most recent call last):\n’, ° File
“cMusers\\ei2101\appdata\\local\\programs\\python\\python
37\\lib\site-packages\\pbr\\version.py’, line 442, in
~get_version_from_pkg_resources\n provider =
pkg_resources.get_provider(requirement)\n’, ° File
“cMusers\\ei2101\appdata\\local\\programs\\python\\python
37\\lib\site-packages\\pkg_resources\\__init__.py’, line 358, in
get_provider\n return working_set.find(moduleOrReq) or
require(str(moduleOrReq))[O}\n’, ° File
“cMusers\\ei2101\appdata\\local\\programs\\python\\python
37\\lib\site-packages\\pkg_resources\\__init__.py’, line 901, in
require\n needed =
self.resolve(parse_requirements(requirements))\n’, ° File
“cMusers\\ei2101\appdata\\local\\programs\\python\\python
37\\lib\site-packages\\pkg_resources\\__init__.py’, line 787, in
resolve\n raise DistributionNotFound(req, requirers)\n’,
“pkg_resources.DistributionNotFound: The ‘PyMI' distribution
was not found and is required by the application\n’,
‘\nDuring handli
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
Add `--copy-metadata PyMI` to your build command.

**Comment by zackfair1412** [comment]
> Add `--copy-metadata PyMI` to your build command.

No, it was just the same.. i tried for several time. The result was the same. It still can't recognize PyMI module

**Comment by bwoodsend** [comment]
In that case provide a minimal example along with your build command so that we can try it out.

**Comment by zackfair1412** [comment]
sorry for the late reply.
Here some code from my build

`import wmi

nic_configs = wmi.WMI().Win32_NetworkAdapterConfiguration(IPEnabled=True)
nic = nic_configs[0]

ip = '192.168.0.11'
subnetmask= '255.255.224.0'
gateway = '192.168.0.1'
dns = '172.15.12.1'

nic.EnableStatic(IPAddress=[ip], SubnetMask=[subnetmask])
nic.SetGateways(DefaultIPGateway=[gateway])
nic.EnableDNS(DNSServerSearchOrder=[dns])`

**Comment by XiaobinZhao** [comment]
@zackfair1412  do you solved the problem ?

**Comment by XiaobinZhao** [comment]
--copy-metadata PyMI solved my problem!
