### ISSUE TITLE
Importing PyNaCl as a hidden import for a discord bot, discord.py module throws error when bot tries to join voice channel

### ISSUE THREAD

**Issue by peeves91** [pyinstaller/pyinstaller#5800]
## Description of the issue
I've got a discord bot that joins a voice channel occasionally.  I've compiled it with pyinstaller, but it fails when trying to join a voice channel with the error ```discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice```.  I'm including PyNaCl in the hidden imports section, and I've also tried including discord.py, and discord.py[voice] as the latter is what is used to ensure it's properly installed with discord.py's module.

## Context information (for bug reports)

* Output of `pyinstaller --version`: 4.3
* Version of Python: 3.9.2
* Platform: Windows 10
* Did you also try this on another platform? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

Tried running latest develop build, doesn't work, error is identical.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

  Went thru all those and nothing worked, I found that PyNaCl isn't included when I ran ```pyi-archive_viewer .\build\bot\PYZ-00.pyz```, whidch just confirms that it isn't being imported properly as best I can tell.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

For the code shown below and the error message below, I'm using the develop branch but it still happens on the latest stable version of pyinstaller.  Also, the install script I'm using to build the exe is ```pyinstaller --hiddenimport win32timezone --hiddenimport pynacl -D --log-level DEBUG --noupx bot_trimmed.py```

```
from discord.ext import commands
import discord
import json
import time

client = commands.Bot(command_prefix = '|')

@client.command()
async def triggered(ctx):
	vc = await ctx.message.author.voice.channel.connect()
	
	time.sleep(1.5)
	await vc.disconnect()

with open('token.json', 'r') as file:
	token = json.load(file)['token']

client.run(token)
```

### Stacktrace / full error message

```
Ignoring exception in command triggered:
Traceback (most recent call last):
  File "discord\ext\commands\core.py", line 85, in wrapped
  File "bot_trimmed.py", line 10, in triggered
  File "discord\abc.py", line 1150, in connect
  File "discord\voice_client.py", line 199, in __init__
RuntimeError: PyNaCl library needed in order to use voice

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "discord\ext\commands\bot.py", line 902, in invoke
  File "discord\ext\commands\core.py", line 864, in invoke
  File "discord\ext\commands\core.py", line 94, in wrapped
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: RuntimeError: PyNaCl library needed in order to use voice
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
You probably just need to collect the binary libraries it ships with it. Add `--collect-binaries=discord` to your pyinstaller command.

**Comment by peeves91** [comment]
Just tried it with ```--collect-binaries=discord```, so the final build line is ```pyinstaller --hiddenimport win32timezone --hiddenimport pynacl --collect-binaries=discord -D --log-level DEBUG --noupx bot_trimmed.py```

and it fails with the same exact error as before.

**Comment by rokm** [comment]
> `--hiddenimport pynacl`

Should probably be `--hiddenimport nacl`.

**Comment by peeves91** [comment]
@rokm nope, didn't fix it, same error as before unfortunately.

**Comment by rokm** [comment]
Is PyNaCl installed in that environment?

**Comment by peeves91** [comment]
yup, I've verified that the script I'm trying to compile to .exe will work on it's own with python.

**Comment by rokm** [comment]
Ahhh, alright, I see what's going on...
`discord.voice_client` is checking for presence of `nacl` by importing `nacl.secret`, and importing `nacl` is failing because it's missing `_cffi_backend` extension.

So it seems you shouldn't need `--hiddenimport nacl`, but rather `--hiddenimport _cffi_backend`.

**Comment by peeves91** [comment]
@rokm worked like a charm, thank you!  Unfortunately, the next line in my actual script (not the trimmed down one), is:

```
vc.play(FFmpegPCMAudio('goodbye.mp3'))
```

which, again, works just fine when I run it as a python script.  But I tried @bwoodsend's solution of ```--collect-binaries``` as I couldn't find it as an import and it's working like a charm.  Thanks for the help with getting the import for pynacl :)
