### ISSUE TITLE
Fatal errors running an EXE in Windows 7 built from Windows 10 (64 bit OSes, 32 bit Python)

### ISSUE THREAD

**Issue by JPLeBreton** [pyinstaller/pyinstaller#5819]
## Description

I use PyInstaller to build Windows EXEs for Playscii, an art tool that I make. A few of my users who are still on Windows 7 are reporting issues running EXEs made with PyInstaller 4.3 (and 4.2) on my Windows 10 system. All systems involved are running 64 bit Windows, though I do build with 32 bit Python. Here are the specific errors they get, in succession in a standard Windows error box:

1. "playscii.exe - System Error" - window text: "The program can't start because api-ms-win-core-path-l1-1-0.dll is missing from your computer. Try reinstalling the program to fix this problem."
followed immediately by:
2. "Fatal error detected" - window text: "Error loading Python DLL 'C:\Users\user\AppData\Local\Temp\_MEI365282\python39.dll'."

The last build I've made that *does* work for Windows 7 users was made with PyInstaller 3.6 and Python 3.7.2, I believe. Did something change between that version of PyInstaller (or Python) and current ones that breaks cross-version build compatibility between Windows 10 and Windows 7?

It's possible this isn't even a PyInstaller issue, I'm just trying to narrow down the range of possible causes. Obviously Win 7 is old and EoL at this point but I'd rather not tell my users they're shut out of future versions unless there's truly no alternative.

## Context information

* PyInstaller version: 4.3
* Python version: 3.9.1
* Platform: Windows
* (issue only occurs on Windows)

**Comment by eric15342335** [comment]
https://pyinstaller.readthedocs.io/en/stable/usage.html#windows

**Comment by bwoodsend** [comment]
You can't use Python 3.9 on Windows 7. Roll back to 3.8 and you should be fine.
