### ISSUE TITLE
How to make linux and Mac executables on windows ??

### ISSUE THREAD

**Issue by Naman23-coder** [pyinstaller/pyinstaller#5828]
Hi there authors of pyinstaller,your package is great and helped me a lot,but there is question,as I am gonna make cross platform software,so how can I create linux/mac executables on my windows machine?

**Comment by rokm** [comment]
You cannot.

**Comment by Naman23-coder** [comment]
Is there any other package/software which can do it??

**Comment by rokm** [comment]
I doubt it, since freezing a python program requires a lot of runtime information. Plus, the installed python packages provide extensions only for the target OS and arch...

**Comment by bwoodsend** [comment]
You're options are:
- Virtualization e.g. using VirtualBox
- Dual booting
- CI/CD e.g. Github Actions

Personally I recommend dual booting Linux then once you've got your code working on both Linux and Windows, macOS is (usually) easy enough to do on CI/CD.

**Comment by Naman23-coder** [comment]
Thanks :-)
