### ISSUE TITLE
How to fix "Could not find QtWebEngineProcess.exe"?

### ISSUE THREAD

**Issue by selimberkin** [pyinstaller/pyinstaller#5829]
I am trying to make PyQt5 application into an executable using Pyinstaller. I have read through these previous issues that this error was resolved. However, after I generated the executable, I still got the same error, "Could not find QtWebEngineProcess.exe".
These are the version I use:

Name: PyQt5
Version: 5.15.4
OS-platform: Windows 10 Home
Python version: 3.9.4

How can I fix this?

**Comment by rokm** [comment]
Support for PyQt5 and PyQtWebEngine 5.15.4 was added in #5811. So you'll either need to downgrade PyQt5/PyQtWebEngine to earlier version, or try installing PyInstaller from `develop` branch (`pip install https://github.com/pyinstaller/pyinstaller/archive/refs/heads/develop.zip`).

**Comment by selimberkin** [comment]
> Support for PyQt5 and PyQtWebEngine 5.15.4 was added in #5811. So you'll either need to downgrade PyQt5/PyQtWebEngine to earlier version, or try installing PyInstaller from `develop` branch (`pip install https://github.com/pyinstaller/pyinstaller/archive/refs/heads/develop.zip`).

Thank you so much!

**Comment by hellobiek** [comment]
@rokm installed pyinstaller 5.0, but still does not work.

**Comment by rokm** [comment]
>@rokm installed pyinstaller 5.0, but still does not work.

Open a new issue and provide all relevant details, then.

**Comment by hellobiek** [comment]
> > @rokm installed pyinstaller 5.0, but still does not work.
> 
> Open a new issue and provide all relevant details, then.

env not exists now, I figure it out by moving qt.conf and QtWebEngineProcess.exe to root dir of the target exe file
