### ISSUE TITLE
Automatically stop .exe without throughing any error.

### ISSUE THREAD

**Issue by Girrajjangid** [pyinstaller/pyinstaller#5831]
## Description of the issue
I am trying to convert linear_model.py to .exe using the command pyinstaller linear_model.spec. I am able to successfully create .exe. But when I try to run it. It automatically terminates or not showing any kind of error.

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.8
* Platform: Windows 10

## The things that I tried.
* Uninstall and reinstall the latest version.
* Added few manual hooks.)
*  Built with --onedir

### A minimal example program which shows the error
It's not showing any error.
How do I check error?

**Comment by bwoodsend** [comment]
Are you running the exe from cmd or double clicking it in explorer?
