### ISSUE TITLE
How to fix "Failed to execute script file_name"?

### ISSUE THREAD

**Issue by selimberkin** [pyinstaller/pyinstaller#5832]
Hi,

I am trying to make PyQt5 application into an executable using Pyinstaller. When I open my .exe file it gives me this error: "Failed to execute script file_name".

How can I fix this error?

**Comment by bwoodsend** [comment]
Turn off windowed mode. Run from terminal. Read the Python exception it gives you.

**Comment by rokm** [comment]
And if the error occurs only in windowed mode, then either implement proper top-level exception handling, or build with `--debug bootloader` enabled, which will give you two more error dialogs with information about the exception that crashed your application.
