### ISSUE TITLE
PyInstaller executable marked as malicious by 6/69 anti-viruses.

### ISSUE THREAD

**Issue by xMistt** [pyinstaller/pyinstaller#5834]
To sum it up, a simple .exe compiled using PyInstaller is making as being malicious by 6/69 of anti-viruses on virustotal. This gives a bad look. Anyway to get around these false positives?

Here is a link to the virus scan if anyone wants: https://www.virustotal.com/gui/file/02b8bea43756cdd98097c40897e0757b145c87d50874039138347d35e5aaa7a8/detection
<img src="https://i.imgur.com/2dmsHju.png" />

**Comment by bwoodsend** [comment]
No there isn't. Report them to the offending anti-virus software providers.
