### ISSUE TITLE
Run onefile executable failed with error: "No such file or directory: '/tmp/_MEIwDORIH/base_library.zip'>"

### ISSUE THREAD

**Issue by Xphobia** [pyinstaller/pyinstaller#5843]
+++ ONLY TEXT +++ DO NOT POST IMAGES +++

## Description of the issue
Run onefile excutable failed with error: "No such file or directory: '/tmp/_MEIwDORIH/base_library.zip'>"

## Context information 

* Output of `pyinstaller --version`: 4,3
* Version of Python: 3.6
* Platform: CentOS Linux release 7.6.1810 (Core)
* Did you also try this on another platform? Does it work there?
   Not yet. But i tried onedir mode excutable, it works fine.

###  More information

1.  What's my goal ?
 I need to pacakge a python daemon program to onefile executable. The source directory shows as follows:
```bash
[root@localhost vm_agent]# ls
conf.yaml  main.py  Makefile  tests
```
The main.py is the daemon program. it's an agent will be run in clound instance and it's used to  collect prometheus metrics periodly. The Makefile is used to excute pyinstaller commands. Its contents is:
```
[root@localhost vm_agent]# cat Makefile 

onefile:
	pyinstaller --onefile --name vm-agent main.py

onedir:
	pyinstaller --onedir --name vm-agent main.py

clean:
	rm -rf build dist __pycache__ *.spec
```
2、How to package ?

(1) Execute `make clean` to clean the last build env.
```
[root@localhost vm_agent]# ls
build  conf.yaml  dist  main.py  Makefile  __pycache__  tests  vm-agent.spec
[root@localhost vm_agent]# 
[root@localhost vm_agent]# 
[root@localhost vm_agent]# make clean
rm -rf build dist __pycache__ *.spec
[root@localhost vm_agent]# 
[root@localhost vm_agent]# 
[root@localhost vm_agent]# ls
conf.yaml  main.py  Makefile  tests
```
(2) Execute `make onefile` to build one file excutable from main.py to vm-agent.
···
[root@localhost vm_agent]# make onefile
pyinstaller --onefile --name vm-agent main.py
81 INFO: PyInstaller: 4.3
81 INFO: Python: 3.6.8
86 INFO: Platform: Linux-3.10.0-957.el7.x86_64-x86_64-with-centos-7.6.1810-Core
86 INFO: wrote /root/vm_agent/vm_agent/vm-agent.spec
101 INFO: UPX is not available.
104 INFO: Extending PYTHONPATH with paths
['/root/vm_agent/vm_agent', '/root/vm_agent/vm_agent']
115 INFO: checking Analysis
115 INFO: Building Analysis because Analysis-00.toc is non existent
115 INFO: Initializing module dependency graph...
118 INFO: Caching module graph hooks...
130 WARNING: Several hooks defined for module 'win32ctypes.core'. Please take care they do not conflict.
134 INFO: Analyzing base_library.zip ...
5610 INFO: Caching module dependency graph...
5868 INFO: running Analysis Analysis-00.toc
5889 INFO: Analyzing /root/vm_agent/vm_agent/main.py
6812 INFO: Processing module hooks...
6814 INFO: Loading module hook 'hook-difflib.py' from '/usr/local/lib/python3.6/site-packages/PyInstaller/hooks'...
6820 INFO: Loading module hook 'hook-encodings.py' from '/usr/local/lib/python3.6/site-packages/PyInstaller/hooks'...
6921 INFO: Loading module hook 'hook-heapq.py' from '/usr/local/lib/python3.6/site-packages/PyInstaller/hooks'...
6925 INFO: Loading module hook 'hook-pickle.py' from '/usr/local/lib/python3.6/site-packages/PyInstaller/hooks'...
6931 INFO: Loading module hook 'hook-xml.py' from '/usr/local/lib/python3.6/site-packages/PyInstaller/hooks'...
7050 INFO: Looking for ctypes DLLs
7050 INFO: Analyzing run-time hooks ...
7065 INFO: Looking for dynamic libraries
7508 INFO: Looking for eggs
7508 INFO: Using Python library /lib64/libpython3.6m.so.1.0
7515 INFO: Warnings written to /root/vm_agent/vm_agent/build/vm-agent/warn-vm-agent.txt
7550 INFO: Graph cross-reference written to /root/vm_agent/vm_agent/build/vm-agent/xref-vm-agent.html
7562 INFO: checking PYZ
7562 INFO: Building PYZ because PYZ-00.toc is non existent
7562 INFO: Building PYZ (ZlibArchive) /root/vm_agent/vm_agent/build/vm-agent/PYZ-00.pyz
8212 INFO: Building PYZ (ZlibArchive) /root/vm_agent/vm_agent/build/vm-agent/PYZ-00.pyz completed successfully.
8215 INFO: checking PKG
8215 INFO: Building PKG because PKG-00.toc is non existent
8215 INFO: Building PKG (CArchive) PKG-00.pkg
11570 INFO: Building PKG (CArchive) PKG-00.pkg completed successfully.
11573 INFO: Bootloader /usr/local/lib/python3.6/site-packages/PyInstaller/bootloader/Linux-64bit/run
11574 INFO: checking EXE
11574 INFO: Building EXE because EXE-00.toc is non existent
11574 INFO: Building EXE from EXE-00.toc
11575 INFO: Appending archive to ELF section in EXE /root/vm_agent/vm_agent/dist/vm-agent
11694 INFO: Building EXE from EXE-00.toc completed successfully.
[root@localhost vm_agent]# echo $?
0
···
(3) Excute the onefile excutable vm-agent 
```
[root@localhost vm_agent]# ./dist/vm-agent 
args: conf_path: /usr/local/hci/vm-agent/conf.yaml, render_conf: store_true
[root@localhost vm_agent]# 
```
(4) Check vm-agent 's log
```
[root@localhost ~]# tail -f /var/log/hci/vm-agent.log 
2021-05-19 14:14:18,785 140623151830848 ERROR [root] unknown error: <urlopen error [Errno 2] No such file or directory: '/tmp/_MEIwDORIH/base_library.zip'>
2021-05-19 14:14:20,659 139919930668864 INFO [root] start to report for vm: bba2fdff667b47c09534d51ed0e33ae3
2021-05-19 14:14:20,659 139919930668864 INFO [root] start collect metrics from node_exporter
2021-05-19 14:14:20,660 139919930668864 ERROR [root] unknown error: <urlopen error [Errno 2] No such file or directory: '/tmp/_MEIp84zQM/base_library.zip'>
2021-05-19 14:14:28,786 140623151830848 INFO [root] start to report for vm: bba2fdff667b47c09534d51ed0e33ae3
2021-05-19 14:14:28,787 140623151830848 INFO [root] start collect metrics from node_exporter
2021-05-19 14:14:28,787 140623151830848 ERROR [root] unknown error: <urlopen error [Errno 2] No such file or directory: '/tmp/_MEIwDORIH/base_library.zip'>
2021-05-19 14:14:30,670 139919930668864 INFO [root] start to report for vm: bba2fdff667b47c09534d51ed0e33ae3

```
I have checked the /tmp directory, there is no directory  /tmp/_MEIwDORIH/
```
2021-05-19 14:21:10,907 139919930668864 INFO [root] start collect metrics from node_exporter
2021-05-19 14:21:10,907 139919930668864 ERROR [root] unknown error: <urlopen error [Errno 2] No such file or directory: '/tmp/_MEIp84zQM/base_library.zip'>
^C
[root@localhost ~]# ls /tmp/_MEIp84zQM
ls: cannot access /tmp/_MEIp84zQM: No such file or directory
[root@localhost ~]# 
```
I have checked the onedir mode executable, it works fine. But I need the onefile mode executable because I don't want expose much infomation about program to user.

**Comment by rokm** [comment]
What is the time frame of the events here? Does the program start and fail immediately? Or does it start and those errors appear in the program's log after a while?

I find it very hard to believe that `base_library.zip` is actually missing (or the `/tmp/_MEIXXXXX` folder, for that matter) - if that was the case, the program wouldn't start at all. (I assume that the line 

> args: conf_path: /usr/local/hci/vm-agent/conf.yaml, render_conf: store_true

was output by frozen python code in `vm-agent`.)

But if this is a long-running program/daemon, it is possible that some scheduled clean-up service empties the /tmp folder and causes this error.  If this is the case, you'll have to change the runtime directory of the frozen program to somewhere else.

Can you add a `print("MEIPASS:", getattr(sys, '_MEIPASS', None))` at the beginning of your program, and check if the indicated folder exists right after you start the program?

**Comment by rokm** [comment]
Ah, so there is actual daemonization involved. That won't work with PyInstaller's onefile mode:

when you start onefile executable, its process unpacks the archive contents to `/tmp/_MEIp84zQM`. Then it starts a child process, which actually runs the frozen python code using the unpacked archive. And when this child finishes, it cleans up the temporary directory.

Daemonization moves the execution to daemon process, and the original main (from PyInstaller's perspective, child) process exits. And since its child stopped, PyInstaller's parent process cleans up its resources, and you're left without /tmp/_MEIp84zQM and its contents.

**Comment by Xphobia** [comment]
> Ah, so there is actual daemonization involved. That won't work with PyInstaller's onefile mode:
> 
> when you start onefile executable, its process unpacks the archive contents to `/tmp/_MEIp84zQM`. Then it starts a child process, which actually runs the frozen python code using the unpacked archive. And when this child finishes, it cleans up the temporary directory.

> Daemonization moves the execution to daemon process, and the original main (from PyInstaller's perspective, child) process exits. And since its child stopped, PyInstaller's parent process cleans up its resources, and you're left without /tmp/_MEIp84zQM and its contents.

Is there a way not to clean the temporay directory and let the daemon do the work when it exits.

> Ah, so there is actual daemonization involved. That won't work with PyInstaller's onefile mode:
> 
> when you start onefile executable, its process unpacks the archive contents to `/tmp/_MEIp84zQM`. Then it starts a child process, which actually runs the frozen python code using the unpacked archive. And when this child finishes, it cleans up the temporary directory.
> 
> Daemonization moves the execution to daemon process, and the original main (from PyInstaller's perspective, child) process exits. And since its child stopped, PyInstaller's parent process cleans up its resources, and you're left without /tmp/_MEIp84zQM and its contents.

Is there a way not to clean the temporay directory ? let the daemon do the work when it exits.

**Comment by Xphobia** [comment]
> What you're suggesting would be the same as using a `onedir` build, would it not?

Yes, thanks.
