### ISSUE TITLE
Apple Silicon | Pyinstaller created arm mach-o codesign fails

### ISSUE THREAD

**Issue by ashalem** [pyinstaller/pyinstaller#5847]
I'm using an arm64-only python 3.9 and PyInstaller version 4.3
I've used PyInstaller to create an arm mach-o of a "hello world" python file. I then tried to sign the file using codesign and got the following error:
`main executable failed strict validation`

When I create an x86_64 mach-o using the same method the codesign works without any issues.
I've tried codesigning on both M1 and intel, and codesigning a "hello world" compiled from C file with gcc works.
This is why I think it is related to the Pyinstaller for Apple silicon process.

P.S: I've also tried compiling and using the bootloader from [ https://github.com/pyinstaller/pyinstaller/pull/5581](https://github.com/pyinstaller/pyinstaller/pull/5581) .
When doing that I got an arm bootloader (Darwin-64bit-arm) but it created an X86 mach-o (instead of the arm mach-o I got in 4.3)

Is this a known issue? Has anybody encountered it?
I'm trying to codesign with "codesign -s"

**Comment by rokm** [comment]
arm64 binaries produced by 4.3 will not be compatible with codesign. (#5581 includes fixes for that).

Can you attach a full build log with #5581 (with rebuilt bootloader)? The bootloader itself should be `universal2` binary (but it may be placed into `Darwin-64bit-arm` folder).

**Comment by bwoodsend** [comment]
Also what's your XCode version? It needs to be very recent for arm to work.

**Comment by ashalem** [comment]
Xcode version is 12.3 (up to date)

I've made sure to be on the branch macos11-arm64-support-cleanup and re-built the bootloaders, this time I got universal binaries in the bootloader folder. I've copied them to my Darwin-64bit-arm folder, and have re-built the mach-o.
Now instead of an arm file I got a universal file! However, the codesign still fails with the same error.

This is the commit I'm on:
`c6c65de4 (HEAD -> macos11-arm64-support-cleanup, origin/macos11-arm64-support-cleanup) building: macOS: attempt to automatically sign the .app BUNDLE`

**Comment by rokm** [comment]
Did you install PyInstaller from that branch, though? (since you mention *copying* bootloader...)

**Comment by rokm** [comment]
> I was using this page: https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html
And ran: python3 ./waf all
But from your answer I understand it doesn't install. How do I install and make sure it was installed correctly?

Yeah, that just builds the bootloader. You need to run `pip install` on the top-level directory of the checked-out repository.

The whole sequence would be:
```
git clone [...]
cd pyinstaller/bootloader
python3 ./waf all
pip install ..
```

**Comment by ashalem** [comment]
I've installed it as you provided, and rebuilt the mach-o.
For some reason now I got arm64 binary instead of Universal2. 
However the codesign didn't fail now! Runninf `codesign -d -vv` does print the correct signature.

The problem is, I tried running the binary and it is still getting blocked by the Os as a file signature error.
Worth mentioning it is different from before as it now showing pop-ups allowing me to run the program anyway.
I'm attaching those to my comment.

However, even after running those popups I get the following error:
`[3920] Error loading Python lib "/Users/ashalem/Downloads/Python": dlopen: dlopen(/Users/ashalem/Downloads/Python, 10): image not found`    (/Users/ashalem/Downloads is the location of the mach-o)

I think it is because the codesign doesn't sign all the files inside the package. I've tried --deep --force flags with codesign but didn't make a change

**Comment by rokm** [comment]
> For some reason now I got arm64 binary instead of Universal2.

That is the correct behavior. We build `universal2` bootloader, but then thin it out to the running platform by default.

> The problem is, I tried running the binary and it is still getting blocked by the Os as a file signature error.

What kind of build is this - `onedir` or `onefile`? Can you paste your PyInstaller command, so we can see what we are talking about here?

**Comment by ashalem** [comment]
This is a one-file build. Running it with `pyinstaller hello_python.py` and then taking the built file from the dist folder

**Comment by rokm** [comment]
Can you first try the `onedir` build to see if that works?

As for `onefile`; #5581 introduces signing of all collected binaries, but by default performs ad-hoc signing. If you want to sign the collected binaries inside the embedded archive to be collected with your signing identity (provided you have one), you can pass it to PyInstaller via --codesign-identity <identity> (where <identity> is the same as what you would pass to your codesign command). 

Sidenote 1: providing `--codesign-identity`  also switches on hardened runtime, and I think that requires actual Apple Developer ID (i.e., self-signed certs don't seem to work, as  discussed in #5581).

Sidenote 2: if everything works correctly, then you shouldn't need to do any manual signing using `codesign` anymore.

**Comment by rubyon** [comment]
Mac OS 11.3.1

Python installed by brew install python@3.9

QT6 installed by brew install qt

PySide6 installed by brew install pyside

pyinstaller install with https://github.com/rokm/pyinstaller/tree/macos11-arm64-support-cleanup


copy this two folder
/opt/homebrew/Cellar/pyside/6.0.4/lib/python3.9/site-packages/PySide6
/opt/homebrew/Cellar/pyside/6.0.4/lib/python3.9/site-packages/shiboken6


and paste it ( replace )

this folder

YOUR_APP_EXEC_FILE.app/Contents/MacOS

It Works!
