### ISSUE TITLE
Trojan:Win32/Wacatac.B!ml after compiling Python script.

### ISSUE THREAD

**Issue by nanohtc** [pyinstaller/pyinstaller#5848]
I installed Pyinstaller recent version (4.3). After running the command `pyinstaller -w --onefile example.py` Mirosoft Defender popup shows security issues with the compiled exe.

I use the `-w` parameter to disable command prompt which pops up after running the compiled exe.

`pyinstaller --onefile example.py`
Removed the `-w` parameter, the compiled file is working.

Because I need to use this parameter I tried another way.
I use the `--onefile` to make only one exe.

`pyinstaller -w example.py`
After removing  `--onefile`  the compiled exe is working.

Unfortunately, this two-parameter is necessary, so I tried another way.
I keep the -w parameter and remove the --onefile parameter, then using Enigma Virtual Box to make the files into a standalone exe.
Finally, the file is working.

My exmaple.py:
```
import tkinter as tkin

root= tkin.Tk()

canvas1 = tkin.Canvas(root, width = 300, height = 300)
canvas1.pack()

def hello ():  
    label1 = tkin.Label(root, text= 'Hello World!', fg='green', font=('helvetica', 12, 'bold'))
    canvas1.create_window(150, 200, window=label1)
    
button1 = tkin.Button(text='Click Me',command=hello, bg='brown',fg='white')
canvas1.create_window(150, 150, window=button1)

root.mainloop()
```

**Comment by bwoodsend** [comment]
Report it to MS Defender then. There's nothing we can do.
