### ISSUE TITLE
pyqt5 error

### ISSUE THREAD

**Issue by EyuphanMandiraci** [pyinstaller/pyinstaller#5859]
Hello, if i make an app with pyqt5 and if i convert with pyinnstaller, while i open the exe app, app gives "ModuleNotFound: PyQt5" error. I used --hidden-import=PyQt5.

pyinstaller version: 4.3
python version: 3.8.5

**Comment by rokm** [comment]
If you're using PyQt5 5.15.4, you'll either need to revert to and earlier version, or use `develop` branch which has #5811 merged.
