### ISSUE TITLE
Virus detected on g-mail

### ISSUE THREAD

**Issue by r-dug** [pyinstaller/pyinstaller#5867]
I was trying to send my first EXE file to a friend, mainly to test if sending it to them would work. While trying to attach the .exe file to an email in gmail, I got a virus detection warning. I've seen some people report that the issue may stem from using a newer version of python... I'm using 3.8.5 and have seen that some people have been successful using up to 3.6 but issues are incurred past that.

**Comment by bwoodsend** [comment]
See [every other issue on the topic](https://github.com/pyinstaller/pyinstaller/issues?q=label%3Aantivirus-false-positives)...
