### ISSUE TITLE
check /bin  and  /lib move to /usr on recent distros

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#587]
**Original date**: 2012/08/13

Some linux distributions (e.g. Fedora) decided to move directories /bin and /lib to _/usr_: https://fedoraproject.org/wiki/Features/UsrMove

We should test the compatibility of PyInstaller with that change and make sure it still works on such linux distributions.

**Comment by htgoebel** [comment]
As of 2b783f6d3871223554653e9454048faf77a21696
* `/bin` is used only by macholib, pefile and PyInstaller/utils/osx.py.
* `/lib` is used only by PyInstaller/depend/bindepend.py which also handles `/usr/lib`.

So nothing to do.
