### ISSUE TITLE
pyinstaller pc-optimizer error

### ISSUE THREAD

**Issue by tecluke** [pyinstaller/pyinstaller#5876]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message
'fatal error, failed to execute script- pc optimizer

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Try rebuilding without `noconsole`/`windowed` option and run from terminal to see details about error. Or, if the issue is specific to `windowed` mode, rebuild with `--debug bootloader`  (assuming you're on the latest PyInstaller version), which should give you additional dialogs with error description.

Otherwise, come back after you've filled the issue template above.

**Comment by tecluke** [comment]
> Try rebuilding without `noconsole`/`windowed` option and run from terminal to see details about error. Or, if the issue is specific to `windowed` mode, rebuild with `--debug bootloader` (assuming you're on the latest PyInstaller version), which should give you additional dialogs with error description.
> 
> Otherwise, come back after you've filled the issue template above.

I downloaded this off a friend so I don't know any of this but it came as an exe so I converted it back to a PY to do what you said but it just came up with this 
![image](https://user-images.githubusercontent.com/85175474/120358218-2b5e1580-c2fe-11eb-89e5-0111ab0bb99b.png)

**Comment by rokm** [comment]
Sorry, I have no idea what you did and what I'm supposed to be looking at.

**Comment by bwoodsend** [comment]
> I downloaded this off a friend so I don't know any of this but it came as an exe so I converted it back to a PY to do what you said but it just came up with this

Report this to you friend then. If you don't even have the source code then you shouldn't be here. We have no idea what the problem is and we wouldn't be able to fix it without source code even if we knew.
