### ISSUE TITLE
No package metadata found for tqdm while generating exe 

### ISSUE THREAD

**Issue by MK096** [pyinstaller/pyinstaller#5878]
Hi,
Whenever i try to make executable file i always get an error : No package metadata found for tqdm >=4.2.7.
I've tried hidden-import tqdm but it didn't work. In python IDLE it works fine but while running exe it doesn't work.

I am using Win 10 (64-bit), tqdm=4.6.1

I am importing transformers

Code: 

import eel
import tqdm  # i thought of importing it to see wheter this solves anything..but it didn't help
from transformers import pipeline

print("Loaded")
eel.init('Web')

// try...Catch to open index.html

Any help will be really appreciated.

Thank You 
![error](https://user-images.githubusercontent.com/20142735/120371531-64fb4480-c32f-11eb-80e0-a273bcdbbe92.PNG)

**Comment by rokm** [comment]
You'll need to collect metadata for all packages that `transformers` [tries to query at runtime](https://github.com/huggingface/transformers/blob/47a98fc4cb6a561576309a57b315b042977d194c/src/transformers/dependency_versions_check.py#L26):
`tqdm`, `regex`, `sacremoses`, `requests`, `packaging`, `filelock`, `numpy`, and `tokenizers`.

If you're using PyInstaller 4.3, you can add corresponding `--copy-metadata <pkg_name> switches to your command, i.e., `--copy-metadata tqdm --copy-metadata regex --copy-metadata sacremoses [etc.]`.

If I remember correctly, at least one of those packages also needs its data files collected (using `--collect-data <pkg_name>`); but I guess you'll be dealing with that once you get the distribution metadata problems out of the way.

**Comment by MK096** [comment]
> You'll need to collect metadata for all packages that `transformers` [tries to query at runtime](https://github.com/huggingface/transformers/blob/47a98fc4cb6a561576309a57b315b042977d194c/src/transformers/dependency_versions_check.py#L26):
> `tqdm`, `regex`, `sacremoses`, `requests`, `packaging`, `filelock`, `numpy`, and `tokenizers`.
> 
> If you're using PyInstaller 4.3, you can add corresponding `--copy-metadata <pkg_name>` switches to your command, i.e., `--copy-metadata tqdm --copy-metadata regex --copy-metadata sacremoses [etc.]`.
> 
> If I remember correctly, at least one of those packages also needs its data files collected (using `--collect-data <pkg_name>`); but I guess you'll be dealing with that once you get the distribution metadata problems out of the way.

Thanks, i'll try that.
--copy-metadata <pkg_name> will come in command prompt right?

**Comment by rokm** [comment]
>  --copy-metadata <pkg_name> will come in command prompt right?

Yes, it should be added to your pyinstaller command in the command prompt.

**Comment by MK096** [comment]
> > --copy-metadata <pkg_name> will come in command prompt right?
> 
> Yes, it should be added to your pyinstaller command in the command prompt.

I was able to solve that problem but now it shows: 

None of PyTorch, TensorFlow >= 2.0, or Flax have been found. Models won't be available and only tokenizers, configuration and file/data utilities can be used.

My TF and Pytorch versions are 2.5.0, 1.8.1+cpu respectively.

I tried uninstalling them and then reinstalling them along with transformers

**Comment by rokm** [comment]
You also need to collect metadata for whichever framework you are using.

**Comment by rokm** [comment]
`transformers` is trying to [determine which of them are available by querying distribution version again](https://github.com/huggingface/transformers/blob/123b597f5da6dd1e54545f9cce1450dc4b401784/src/transformers/file_utils.py#L67-L111), but this time there's exception handling around it, so you don't see the missing distribution error.

**Comment by MK096** [comment]
> You also need to collect metadata for whichever framework you are using.

I added --collect-data tensorflow  --collect-data torch but it still shows the same error.
Here is the full cmd:

 --hidden-import="pkg_resources.py2_warn" --hidden-import="googleapiclient" --hidden-import="apiclient" **--hidden-import=tensorflow --hidden-import=pytorch** --collect-data tensorflow  --collect-data torch --copy-metadata tqdm --copy-metadata regex --copy-metadata sacremoses --copy-metadata requests --copy-metadata packaging --copy-metadata filelock --copy-metadata numpy --copy-metadata tokenizers  --copy-metadata importlib_metadata --hidden-import=“sklearn.utils._cython_blas” --hidden-import=“sklearn.neighbors.typedefs” --hidden-import=“sklearn.neighbors.quad_tree” --hidden-import=“sklearn.tree” --hidden-import=“sklearn.tree._utils”

**Comment by rokm** [comment]
You need to collect metadata, i.e., `--copy-metadata tensorflow --copy-metadata pytorch` (or whatever the distribution names for tensorflow and torch are).

**Comment by ADD-eNavarro** [comment]
Hi.
I'm facing the same situation, only I'm using a spec file. I can't find where in this file should I write the copy-metadata command, there's no such entry in Analysis.
Should I add a new line to get it working?

**Comment by rokm** [comment]
What `--copy-metadata dist_name` does is, it adds

```python
from PyInstaller.utils.hooks import copy_metadata

datas = []
datas += copy_metadata('dist_name')
```

at the top of the spec file, and then ensures that `datas` is passed to the `Analysis` as an argument with the same name.

You can try freezing a simple program with added `--copy-metadata` switch(es) and check the resulting spec file to see the effect...

**Comment by ADD-eNavarro** [comment]
Wow that was fast! 
Thank you very much for the answer, I'll do that and see where it gets me.

EDIT: Yep! That solved it. Now for the next error in line, regex...
