### ISSUE TITLE
Universal 2 Wheels for Apple M1

### ISSUE THREAD

**Issue by bwoodsend** [pyinstaller/pyinstaller#5879]
For anyone reading this who is concerned that this may impede creating M1 compatible applications, don't worry. It's just for us developers to put PyInstaller itself on PyPI. Worst case scenario, we revert to using sdists (which is what we've been using for the last several years anyway).

At some point, we're going to add `univeral2` wheel building to our setup.py.

I'm trying to follow the story for wheel tags so that we know what to do when we amend #5787 to support universal2 wheels and when we can do it. 

* In [the original *what are we going to do about M1* discussion](https://discuss.python.org/t/apple-silicon-and-packaging/4516) they decide that wheels will be called `universal2` and not some `x86_64-arm64` hybrid. I can't find any information on what happens to the `macosx-version-min` part of the tag.
* Then everything happens in `pypa/packaging`:
  - pypa/packaging#319 and pypa/packaging#380 add support for this new tag.
  - These are both released in `packaging==20.9`.
* But in practice, you don't use `packaging` directly. Instead it gets *vendored* (i.e. copy/pasted) into pip.
  - [pypa/pip/commit/c7ace4de391f9970792c3bb83c648b7294b7b720](https://github.com/pypa/pip/commit/c7ace4de391f9970792c3bb83c648b7294b7b720) updates the vendored `packaging` to 20.9
  - This is released in `pip==21.1.2`.
* Similarly, it's vendored into `wheel`.
  - [pypa/wheel/a6fa4839ba1c74a37cb43eefb959c0766594ec63](https://github.com/pypa/wheel/commit/a6fa4839ba1c74a37cb43eefb959c0766594ec63) updated the vendored version.
  - **But**, this has not been released yet.

So it would look like all of the machinery is ready to be played with (provided that you install wheel directly from github). I'll borrow a mac again and see if I can get that working...

**Comment by bwoodsend** [comment]
And to summarise some relevant dialog from [here](https://github.com/pyinstaller/pyinstaller/issues/5315#issuecomment-853046864): We should probably put universal2 bootloaders into the sdist temporarly so that
* if we fumble the wheel tags the user gets the sdist and all is well
* if the user doesn't have a new enough pip to recognise universal2 tags, then they get the sdist and all is well

**Comment by rokm** [comment]
I wonder, would it make sense to include all pre-built bootloaders in the sdist (i.e., after including macOS ones, only Linux ones will be left out), to ensure that whatever happens with the wheels, the fall back installation path still works as it has for years?

**Comment by bwoodsend** [comment]
@rokm if I understand correctly, #5581 will allow you to build a non-universal bootloader if you lack the relevant SDKs. Is there any way of knowing afterwards that the bootloaders in `PyInstaller/bootloader/Darwin-64bit` are either fat or thin without using `lipo` (whose availability we can't garuntee on anything except on mac)?

Ideally `setup.py wheel_darwin_64bit` should be able to detect if the bootloaders it bundles are fat or thin and set its own tag to `universal2` or `x86_64` accordingly. And becuase we like to cross compile wheels, it needs to be able to make this decision even on Windows.

**Comment by bwoodsend** [comment]
> I wonder, would it make sense to include all pre-built bootloaders in the sdist (i.e., after including macOS ones, only Linux ones will be left out), to ensure that whatever happens with the wheels, the fall back installation path still works as it has for years?

We could do. If it did resort to a fall back though then we wouldn't have any way of knowing a) there's a problem with the wheels causing the fallback to be used and b) what that problem is.

**Comment by bwoodsend** [comment]
> > I wonder, would it make sense to include all pre-built bootloaders in the sdist (i.e., after including macOS ones, only Linux ones will be left out), to ensure that whatever happens with the wheels, the fall back installation path still works as it has for years?
> 
> We could do. If it did resort to a fall back though then we wouldn't have any way of knowing a) there's a problem with the wheels causing the fallback to be used and b) what that problem is.

Ah, sod it. That's a weak argument. Let's just do it. 

One thing I can think of is that with bootloaders removed from the sdist, alpine (and its other friends on musl) would do the correct thing and ignore the wheels and build from source but with those incompatible bootloaders in there it'll not bother and therefore fail at runtime like it does currently.

**Comment by rokm** [comment]
Does alpine end up using different tags than glibc-based linux distibutions when installing wheels?

**Comment by rokm** [comment]
> @rokm if I understand correctly, #5581 will allow you to build a non-universal bootloader if you lack the relevant SDKs. Is there any way of knowing afterwards that the bootloaders in PyInstaller/bootloader/Darwin-64bit are either fat or thin without using lipo (whose availability we can't garuntee on anything except on mac)?

> Ideally setup.py wheel_darwin_64bit should be able to detect if the bootloaders it bundles are fat or thin and set its own tag to universal2 or x86_64 accordingly. And becuase we like to cross compile wheels, it needs to be able to make this decision even on Windows.

Yeah, you can provide `--no-universal2` switch to `waf` and it will build regular x86_64 bootloader, as it did before #5581 (note that even on arm64, we built x86_64 bootloader before, and we also do now if --no-universal2 switch is used.).

We have [new utility function](https://github.com/pyinstaller/pyinstaller/blob/660a2e3e0b818862aa7efc158fbfca114377fd02/PyInstaller/utils/osx.py#L264) for detecting architecture. It's used by assembly pipeline (or rather, other utility functions used by assembly pipeline) to validate arch of bootloader and collected binaries. It requires `macholib` (but that's pure python and portable, if I recall correctly).

**Comment by bwoodsend** [comment]
Alpine doesn't yet have its own tags. The `manylinux_[version]` tag is for glibc based distributions only. There's a [work in progress PEP656](https://www.python.org/dev/peps/pep-0656/) which will define a `manymusl` (or something similar) tag which PyPI will learn to accept. Currently, you can build a wheel on alpine but it'll just get a generic `linux` tag which pip will let you install but only because its safetly net is gone - you'll get symbol errors at runtime if you haven't matched build and run platforms.

So the current status is: PyPI (but not pip) blocks anything tagged linux unless it has a manylinux tag. Alpine pip will refuse to install anything labelled manylinux becuase it knows that manylinux implies glibc. There is no way to get Alpine compatible wheels on PyPI. You have to use sdists.

Once the PEP is implemented, we will be able to build special musl wheels tagged `musl` which will be installable and runable on apline.

**Comment by bwoodsend** [comment]
> We have new utility function for detecting architecture. It's used by assembly pipeline (or rather, other utility functions used by assembly pipeline) to validate arch of bootloader and collected binaries. It requires macholib (but that's pure python and portable, if I recall correctly).

OK, if it works on non mac, then we're all good...

**Comment by rokm** [comment]
Hmm, let's leave the linux bootloaders out of sdist, then. In addition to automatically solving problems on alpine, this will also make it easier to install PyInstaller with locally-built bootloader (e.g., with PIE disabled) by adding `--no_binary :pyinstaller:` to `pip` command.
