### ISSUE TITLE
ImportError: '__main__' is not a built-in module

### ISSUE THREAD

**Issue by Spindermoon1** [pyinstaller/pyinstaller#5897]
## Description of the issue

ImportError: '__main__' is not a built-in module
I'm not sure what else should I write here, I just can't access __main__ using dis

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.7
* Platform: Windows 10 Pro Version 20H2
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? -- I have not tried this on another platform but I'm pretty sure it won't work.

```
import dis
import sys

print(sys.modules["__main__"])
print(dis.dis(sys.modules["__main__"].__loader__.get_code("__main__")))
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "decompile code.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 235, in _requires_builtin_wrapper
ImportError: '__main__' is not a built-in module
[18232] Failed to execute script decompile code
```

**Comment by bwoodsend** [comment]
I can reproduce this without PyInstaller just by piping that snippet of code to Python rather than running it.
```python
$ cat test.py | python
<module '__main__' (built-in)>
Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "<frozen importlib._bootstrap>", line 243, in _requires_builtin_wrapper
ImportError: '__main__' is not a built-in module

```

I'm guessing that PyInstaller does something more like `exec()`-ing the bytecode rather than doing whatever it's supposed to do to run an entry point script.
