### ISSUE TITLE
about TF-GPU error 

### ISSUE THREAD

**Issue by zhanghongyong123456** [pyinstaller/pyinstaller#5898]
This is a simple TF-GPU test，cuda  tf-gpu-1.14.0
![101](https://user-images.githubusercontent.com/48466610/121456171-38eb5d80-c9d8-11eb-9f29-922ad7829e49.png)

**Comment by bwoodsend** [comment]
Can you please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).
