### ISSUE TITLE
A large number of processes appear after running

### ISSUE THREAD

**Issue by ANewAnonymous** [pyinstaller/pyinstaller#5902]
Using the PyInstaller packaging program, a large number of processes will appear after running, and the gui interface will automatically restart after turning off the gui interface. These problems will not occur if you run it directly without packaging. Can you help me? I will thank you very much!
![QQ图片20210610203448](https://user-images.githubusercontent.com/17308906/121528795-606d1500-ca2e-11eb-8fda-c0a107a18d12.png)
![QQ图片20210610203454](https://user-images.githubusercontent.com/17308906/121528814-64993280-ca2e-11eb-8033-90633d7441e7.png)

**Comment by rokm** [comment]
If you're using `multiprocessing`, you might be missing a call to [`multiprocess.freeze_support()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support).

Other than that, it's impossible to say without seeing the code or at least a minimum example that reproduces the issue.

**Comment by ANewAnonymous** [comment]
> If you're using `multiprocessing`, you might be missing a call to [`multiprocessing.freeze_support()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support).
> 
> Other than that, it's impossible to say without seeing the code or at least a minimum example that reproduces the issue.

I tried adding multiprocessing.freeze_support() to the first line of main, but it didn’t work, and I found that as long as it was packaged, this would happen regardless of whether the code was called or not, and a large number of processes occurred.

**Comment by rokm** [comment]
Can we see a code example?

**Comment by ANewAnonymous** [comment]
> Can we see a code example?

sure，
![QQ图片20210610215619](https://user-images.githubusercontent.com/17308906/121537697-b9d94200-ca36-11eb-9f06-527288db08a3.png)
![QQ图片20210610215729](https://user-images.githubusercontent.com/17308906/121537847-df664b80-ca36-11eb-8e0e-327a4684e9e7.png)
![QQ图片20210610215810](https://user-images.githubusercontent.com/17308906/121537943-f73dcf80-ca36-11eb-8b8e-a0feaa4de43b.png)
![QQ图片20210610215909](https://user-images.githubusercontent.com/17308906/121538113-1b011580-ca37-11eb-8c2d-eb2bfcfa4b24.png)
As long as the deepsort related code is imported, even if his method is not called, it will cause a large number of process bugs.

This is a target tracking system, which uses the deepsort tracking algorithm to modify the detector into ppyolov2 of paddleDetection
![QQ图片20210610220227](https://user-images.githubusercontent.com/17308906/121538721-94990380-ca37-11eb-84df-2d99cdbd25c1.png)
![QQ图片20210610220229](https://user-images.githubusercontent.com/17308906/121538724-95ca3080-ca37-11eb-9122-e86f3bc795ca.png)

**Comment by bwoodsend** [comment]
Please paste it code as text. I'm not manually copying everything in those screenshots out.

**Comment by bwoodsend** [comment]
What you're really looking for is some usage of either `multiprocessing` or a home-grown variant like `subprocess.run([sys.executable, "blah", "blah", "blah"])`.

**Comment by ANewAnonymous** [comment]
```

import multiprocessing
import os
import sys
import threading
from  ctypes import *

from PyQt5 import QtCore, QtWidgets, QtGui
import cv2
from PyQt5.QtCore import QSize
from PyQt5.QtGui import QIcon
from PyQt5.QtWidgets import QFileDialog, QListWidgetItem, QMessageBox
from deepsort import DeepSort


class Ui_MainWindow(object):
    def getCamera(self):
        arr = getCameraList()
        self.names = locals()
        self.videoNums=0
        i = 0
        for item in arr:
            self.names['v' + str(i)] = QtWidgets.QAction(MainWindow)
            self.names['v' + str(i)].setObjectName('v' + str(i))
            self.menu_4.addAction(self.names['v' + str(i)])
            self.names['v' + str(i)].triggered.connect(lambda: self.connectVideo(i-1))

            i += 1
            self.videoNums+= 1

    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(768, 500)
        MainWindow.setMinimumSize(QtCore.QSize(768, 500))
        MainWindow.setMaximumSize(QtCore.QSize(768, 500))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)






        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.listWidget = QtWidgets.QListWidget(self.centralwidget)
        self.listWidget.setGeometry(QtCore.QRect(10, 20, 201, 431))
        self.listWidget.setObjectName("listWidget")
        self.listWidget.setIconSize(QSize(100, 100))
        self.progressBar = QtWidgets.QProgressBar(self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(260, 130, 221, 23))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(560, 20, 191, 191))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(20, 130, 91, 22))
        self.label.setObjectName("label")
        self.isUseGPU = QtWidgets.QCheckBox(self.groupBox)
        self.isUseGPU.setGeometry(QtCore.QRect(20, 40, 101, 16))
        self.isUseGPU.setObjectName("isUseGPU")

        self.isOutPutTxt = QtWidgets.QCheckBox(self.groupBox)
        self.isOutPutTxt.setGeometry(QtCore.QRect(20, 70, 111, 16))
        self.isOutPutTxt.setObjectName("isOutPutTxt")
        self.isOutPutMp4 = QtWidgets.QCheckBox(self.groupBox)
        self.isOutPutMp4.setGeometry(QtCore.QRect(20, 100, 111, 16))
        self.isOutPutMp4.setObjectName("isOutPutMp4")
        self.isOutPutTxt.setChecked(True)
        self.isOutPutMp4.setChecked(True)
        self.threshold = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.threshold.setGeometry(QtCore.QRect(90, 130, 62, 22))
        self.threshold.setObjectName("threshold")
        self.threshold.setMaximum(1.0)
        self.threshold.setSingleStep(0.05)
        self.threshold.setValue(0.4)

        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(560, 260, 191, 181))
        self.groupBox_2.setObjectName("groupBox_2")
        self.personNums = QtWidgets.QLabel(self.groupBox_2)
        self.personNums.setGeometry(QtCore.QRect(40, 50, 91, 16))
        self.personNums.setObjectName("personNums")
        self.totalNums = QtWidgets.QLabel(self.groupBox_2)
        self.totalNums.setGeometry(QtCore.QRect(50, 80, 91, 16))
        self.totalNums.setObjectName("totalNums")
        self.frames = QtWidgets.QLabel(self.groupBox_2)
        self.frames.setGeometry(QtCore.QRect(40, 110, 111, 16))
        self.frames.setObjectName("frames")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(320, 170, 54, 12))
        self.label_2.setObjectName("label_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 768, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_4 = QtWidgets.QMenu(self.menu_2)
        self.menu_4.setObjectName("menu_4")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.open_video = QtWidgets.QAction(MainWindow)
        self.open_video.setObjectName("open_video")
        self.config = QtWidgets.QAction(MainWindow)
        self.config.setObjectName("config")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.exit = QtWidgets.QAction(MainWindow)
        self.exit.setObjectName("exit")
        self.menu.addAction(self.open_video)
        self.menu.addAction(self.exit)
        self.menu_2.addAction(self.menu_4.menuAction())
        self.menu_3.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.getCamera()


        self.open_video.triggered.connect(self.showDialog)
        self.exit.triggered.connect(lambda: self.wichBtn(self.exit))
        self.config.triggered.connect(lambda: self.wichBtn(self.config))
        self.about.triggered.connect(lambda: self.wichBtn(self.about))
        self.threshold.valueChanged.connect(lambda: self.thresholdValueChanged(self.threshold.value()))
        self.isUseGPU.stateChanged.connect(lambda: self.isUseGPUChanged(self.isUseGPU.isChecked()))
        self.isOutPutTxt.stateChanged.connect(lambda: self.isOutPutTxtChanged(self.isOutPutTxt.isChecked()))
        self.isOutPutMp4.stateChanged.connect(lambda: self.isOutPutMp4Changed(self.isOutPutMp4.isChecked()))
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)






    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "基于百度飞浆平台的目标追踪系统"))
        self.groupBox.setTitle(_translate("MainWindow", "配置区"))
        self.label.setText(_translate("MainWindow", "置信度阈值:"))
        self.isUseGPU.setText(_translate("MainWindow", "是否启用GPU"))
        self.isOutPutTxt.setText(_translate("MainWindow", "是否输出结果txt"))
        self.isOutPutMp4.setText(_translate("MainWindow", "是否输出结果mp4"))
        self.groupBox_2.setTitle(_translate("MainWindow", "结果区"))
        self.personNums.setText(_translate("MainWindow", "当前实时人数:89"))
        self.totalNums.setText(_translate("MainWindow", "总ID数:100"))
        self.frames.setText(_translate("MainWindow", "当前处理帧数:100"))
        self.label_2.setText(_translate("MainWindow", "追踪进度"))
        self.menu.setTitle(_translate("MainWindow", "文件"))
        self.menu_2.setTitle(_translate("MainWindow", "摄像头"))
        self.menu_4.setTitle(_translate("MainWindow", "连接摄像头"))
        self.menu_3.setTitle(_translate("MainWindow", "关于"))
        self.open_video.setText(_translate("MainWindow", "打开视频文件"))
        self.config.setText(_translate("MainWindow", "系统配置"))
        self.about.setText(_translate("MainWindow", "关于我们"))
        self.exit.setText(_translate("MainWindow", "退出"))

        #print(self.videoNums)
        for v in range(0,self.videoNums):
            self.names['v' + str(v)].setText(_translate("MainWindow", getCameraList()[v]))


        # self.action1.setText(_translate("MainWindow", "1"))
        # self.action2.setText(_translate("MainWindow", "2"))
        # self.action2_2.setText(_translate("MainWindow", "2"))

    def showDialog(self):
        #imgName, imgType = QFileDialog.getOpenFileName(None, "打开视频文件", "", "视频文件(*.mp4;*.avi;*.wmv);;All Files(*)")
        imgName, imgType = QFileDialog.getOpenFileName(None, "打开视频文件", "", "视频文件(*.mp4;*.avi;*.wmv)")
        t1 = threading.Thread(target=main, args=(self,imgName,-1,))
        t1.start()



    def wichBtn(self, btn):
        if(btn.text()=="打开视频文件"):
            print("打开视频文件")
            filename,  _ = QFileDialog.getOpenFileName(self, 'Open file', './')
        elif(btn.text()=="退出"):
            print("退出")
            sys.exit(0)
        elif (btn.text() == "系统配置"):
            print("系统配置")
        elif (btn.text() == "关于我们"):
            print("关于我们")

    def connectVideo(self,i):
        print(i)
        pass

    def thresholdValueChanged(self, threshold):
        global deepsort
        deepsort.threshold=round(threshold, 2)
        pass

    def isUseGPUChanged(self, param):
        loadModel(param)
        pass

    def isOutPutTxtChanged(self, param):
        global isOutPutTxt
        isOutPutTxt=param
        pass

    def isOutPutMp4Changed(self, param):
        global isOutPutMp4
        isOutPutMp4 = param
        pass



def getCameraList():
    pDll = CDLL("Camera.dll")
    pDll.getCameraNames.restype = c_char_p
    pChar = pDll.getCameraNames(1, 2)
    result=pChar.decode('utf-8', 'ignore')
    arr=[]
    for item in result.split('|'):
        if item != '':
            arr.append(item)
    return arr


# print(getCameraList())
deepsort=None
isOutPutTxt=True
isOutPutMp4=True

def loadModel(use_gpu):
    global deepsort
    deepsort = DeepSort('model/ppyolov2111', 'model/embedding', use_gpu)




def main(ui,video,cameraId):
    ui.listWidget.clear()
    global deepsort
    global isOutPutTxt
    global isOutPutMp4
    isOutTxt=isOutPutTxt
    isOutMp4=isOutPutMp4
    if video:
        cap = cv2.VideoCapture(video)
        fileName = video[video.rindex(r"/") + 1:]
        fileName = fileName[:fileName.index(".mp4")]
        if(isOutMp4):
            fps = cap.get(cv2.CAP_PROP_FPS)
            w = cap.get(cv2.CAP_PROP_FRAME_WIDTH)
            h = cap.get(cv2.CAP_PROP_FRAME_HEIGHT)
            save_video_path = os.path.join("./output/", fileName + '_output.avi')
            fourcc = cv2.VideoWriter_fourcc(*'MJPG')
            writer = cv2.VideoWriter(save_video_path, fourcc, fps, (int(w), int(h)))

        frames_num = cap.get(7)
        now_frame = 1
        for i in range(int(frames_num)):
            success, frame = cap.read()
            outputs, outputs1,personNums = deepsort.update(frame)
            ui.personNums.setText("当前实时人数:{}".format(personNums))
            ui.totalNums.setText("总ID数:{}".format(len(outputs)))
            ui.frames.setText("当前处理帧数:{}".format(now_frame))
            if outputs is not None:
                for output in outputs:
                    isExist = False
                    try:
                        thisFrame=frame[output[1]:output[3], output[0]:output[2]]
                        shrink = cv2.cvtColor(thisFrame, cv2.COLOR_BGR2RGB)
                    except Exception:
                        continue
                    qt_img = QtGui.QImage(shrink.data,  
                                          shrink.shape[1], 
                                          shrink.shape[0],  
                                          shrink.shape[1] * 3,  
                                          QtGui.QImage.Format_RGB888)

                    for i in range(ui.listWidget.count()):
                        if (ui.listWidget.item(i).text() == "行人ID:" + str(output[4])):
                            ui.listWidget.item(i).setIcon(QIcon(QtGui.QPixmap.fromImage(qt_img)))
                            isExist = True
                    if (isExist == False):
                        itm = QListWidgetItem("行人ID:" + str(output[4]))
                        itm.setIcon(QIcon(QtGui.QPixmap.fromImage(qt_img)))
                        ui.listWidget.addItem(itm)
                    if(isOutPutMp4):
                        font = cv2.FONT_HERSHEY_SIMPLEX
                        cv2.rectangle(frame, (output[0], output[1]), (output[2], output[3]), (0, 0, 255), 2)
                        cv2.putText(frame, str(output[-1]), (output[0], output[1]), font, 1.2, (255, 255, 255), 2)
                if isOutTxt:
                    for output in outputs1:
                        str1 =  "{},{},{},{},{},{},1,-1,-1,-1".format(now_frame,output[0],round(output[1],1),round(output[2],1),round(output[3],1),round(output[4],1))
                        with open("./output/{}.txt".format(fileName), 'a') as f:
                            f.write(str(str1) + "\n")
            ui.progressBar.setValue(int((now_frame / frames_num) * 100))
            now_frame += 1
            if isOutMp4:
                writer.write(frame)
        if isOutMp4 or isOutTxt:
            os.system('explorer.exe ./output/')
      
    else:
        cap = cv2.VideoCapture(cameraId)
    pass







if __name__ == '__main__':
    multiprocessing.freeze_support()
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    loadModel(False)
    sys.exit(app.exec_())

```

**Comment by bwoodsend** [comment]
I don't see anything harmful in that one. You say that you think `from deepsort import DeepSort` is the offending line - is `deepsort` an open source package we can look at?

**Comment by ANewAnonymous** [comment]
> 我没有看到任何有害的东西。你说你认为`from deepsort import DeepSort`是有问题的——是`deepsort`一个我们可以看看的开源包吗？

[deepsort Github](https://github.com/jm12138/deep_sort_paddle)

**Comment by rokm** [comment]
Hmm... can you add a `print('Process launched: %r' % (sys.argv))` statement immediately after `import sys` in your entry-point script, rebuild the program, try to launch it, and see how many times that message it printed (and with what arguments)?

**Comment by rokm** [comment]
I suspect that this code (or its packages) aren't using `multiprocessing`, which is why the `multiprocessing.freeze_support()` does not have any effect.

The [`paddle` package](https://github.com/PaddlePaddle/Paddle) looks like a 3rd party multiprocessing framework - and, like other multiprocess frameworks, it very likely does not play nicely with PyInstaller. So unfortunately, that's unsupported.

**Comment by rokm** [comment]
Sigh... and of course, the issue is something completely different.

[Deep within the bowels of `paddle`](https://github.com/PaddlePaddle/Paddle/blob/ab41a9ee8902dbf461b55ef9347071d7eb71fd76/python/paddle/dataset/image.py#L39-L56), there's this:
```python
if six.PY3:
    import subprocess
    import sys
    import_cv2_proc = subprocess.Popen(
        [sys.executable, "-c", "import cv2"],
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE)
    out, err = import_cv2_proc.communicate()
    retcode = import_cv2_proc.poll()
    if retcode != 0:
        cv2 = None
    else:
        import cv2
else:
    try:
        import cv2
    except ImportError:
        cv2 = None
```

That `subprocess.Popen` is relying on the fact that in unfrozen script, `sys.executable` points to python interpreter executable. In a frozen application, it points to the application executable. So it opens another process and calls the application, which imports `deepcopy` and therefore `paddle`, only to reach this point again, and launch another process with application executable... and so on.

So there's nothing we can do on our side about it, and you can work around it by disabling that ugly fix in your local `paddle` installation. Open your `site-packages\paddle\dataset\image.py˙ and change the `if six.PY3:` into `if False:` (or simplify the whole block accordingly).

**Comment by bwoodsend** [comment]
I wonder if it might be better to remove `sys.executable` - then these kinds of errors would be self explanatory. Maybe add a new attribute to `sys` which points to the PyInstaller exe's location instead in case people genuinely want it.

**Comment by ANewAnonymous** [comment]
> Sigh... and of course, the issue is something completely different.
> 
> [Deep within the bowels of `paddle`](https://github.com/PaddlePaddle/Paddle/blob/ab41a9ee8902dbf461b55ef9347071d7eb71fd76/python/paddle/dataset/image.py#L39-L56), there's this:
> 
> ```python
> if six.PY3:
>     import subprocess
>     import sys
>     import_cv2_proc = subprocess.Popen(
>         [sys.executable, "-c", "import cv2"],
>         stdout=subprocess.PIPE,
>         stderr=subprocess.PIPE)
>     out, err = import_cv2_proc.communicate()
>     retcode = import_cv2_proc.poll()
>     if retcode != 0:
>         cv2 = None
>     else:
>         import cv2
> else:
>     try:
>         import cv2
>     except ImportError:
>         cv2 = None
> ```
> 
> That `subprocess.Popen` is relying on the fact that in unfrozen script, `sys.executable` points to python interpreter executable. In a frozen application, it points to the application executable. So it opens another process and calls the application, which imports `deepcopy` and therefore `paddle`, only to reach this point again, and launch another process with application executable... and so on.
> 
> So there's nothing we can do on our side about it, and you can work around it by disabling that ugly fix in your local `paddle` installation. Open your `site-packages\paddle\dataset\image.py` and change the `if six.PY3:` into `if False:` (or simplify the whole block accordingly).

Thank you very much, through your method, I have solved the problem. wish you a happy life!

**Comment by rokm** [comment]
> I wonder if it might be better to remove `sys.executable` - then these kinds of errors would be self explanatory. Maybe add a new attribute to `sys` which points to the PyInstaller exe's location instead in case people genuinely want it.

Yeah, setting it to `None` would make it a lot easier to spot landmines like that. 

The [docs](https://docs.python.org/3/library/sys.html#sys.executable) say that it should be `a string giving the absolute path of the executable binary for the Python interpreter, on systems where this makes sense`. In our case, it doesn't point to interpreter, and pointing to interpreter doesn't make sense anyway.

The first victim of this will of course be `multiprocessing`, but we can probably handle that in runtime hook by adding  [`multiprocessing.set_executable()`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.set_executable) with that private executable location variable.

**Comment by bwoodsend** [comment]
I've made PaddlePaddle/Paddle#33543 to fix Paddle although I'm not sure if it will ever get merged...

**Comment by demonsliu** [comment]
> 
> 
> > Sigh... and of course, the issue is something completely different.
> > [Deep within the bowels of `paddle`](https://github.com/PaddlePaddle/Paddle/blob/ab41a9ee8902dbf461b55ef9347071d7eb71fd76/python/paddle/dataset/image.py#L39-L56), there's this:
> > ```python
> > if six.PY3:
> >     import subprocess
> >     import sys
> >     import_cv2_proc = subprocess.Popen(
> >         [sys.executable, "-c", "import cv2"],
> >         stdout=subprocess.PIPE,
> >         stderr=subprocess.PIPE)
> >     out, err = import_cv2_proc.communicate()
> >     retcode = import_cv2_proc.poll()
> >     if retcode != 0:
> >         cv2 = None
> >     else:
> >         import cv2
> > else:
> >     try:
> >         import cv2
> >     except ImportError:
> >         cv2 = None
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > That `subprocess.Popen` is relying on the fact that in unfrozen script, `sys.executable` points to python interpreter executable. In a frozen application, it points to the application executable. So it opens another process and calls the application, which imports `deepcopy` and therefore `paddle`, only to reach this point again, and launch another process with application executable... and so on.
> > So there's nothing we can do on our side about it, and you can work around it by disabling that ugly fix in your local `paddle` installation. Open your `site-packages\paddle\dataset\image.py` and change the `if six.PY3:` into `if False:` (or simplify the whole block accordingly).
> 
> Thank you very much, through your method, I have solved the problem. wish you a happy life!

老哥，你怎么搞得成功了
