### ISSUE TITLE
Can I package the Torch-GPU with PyInstaller

### ISSUE THREAD

**Issue by zhanghongyong123456** [pyinstaller/pyinstaller#5903]
I have a question. I have a Python project that is implemented on Torch-GPU. Can I package it with PyInstaller and run it independently on other computers, or what do I need to configure to run it on other computers.

I have tried a demo, which can be used normally on this machine, but this bug appears on other computers, I hope to get your reply
![103](https://user-images.githubusercontent.com/48466610/121663902-7be12a00-cad9-11eb-902e-8ac722525abf.png)

**Comment by rokm** [comment]
You probably need to install [Visual C++ Redistributable](https://aka.ms/vs/16/release/vc_redist.x64.exe) on the target computers. 

Or, try using PyInstaller  `develop` branch, which has improved collection of those VC runtime DLLs.
