### ISSUE TITLE
Shutil.which() and other methods to determine ffmpeg can't fetch it: NoneType or worse

### ISSUE THREAD

**Issue by leifadev** [pyinstaller/pyinstaller#5925]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: **3.9.2**
* Platform: _MacOS 10.15/16_
* How you installed Python: **Pkg installer from python website*

## Reproducing It
  * [ ] Clean install of pyinstaller (also using latest dev version)
  * [ ] Use my script utilizing shutil's which method to detect any binaries (ffmpeg)
  * [ ] Running _this command_ `pyinstaller --onefile --windowed --icon=scout_logo.png --osx-bundle-identifier="com.leifadev.scout" -n="Scout" scout.py`, and all other suggested flags to debug in this template did not work, had \no effect to the inital problem at all
  * [ ] Only using the `--windowed` version, without a console output window does it not work like the shutil statement wasn't even there. Otherwise works great

Right now I am almost finished with my version of [my app][1]. The last thing I am having trouble with is detecting the FFmpeg module, to warn users that they need it for certain features that have been added this version. When I run the script through my python interpreter in terminal, which the directories of it is in my library frameworks directory, The `shutil` will run as expected and return the version or whatever as I do have it installed. However, when I compile it and launch specifically the one windowed, with no console output, it doesn’t work. Now what I mean by that it returns none type. 

From talking to someone in my previous Reddit thread I tried printing out `python3` and seeing what directories that would bring with `shutil.which(‘python3’)`. Interesting enough, when put into my tkinter text field (don't have a console) it would bring up my python binary from the directory `/usr/bin/python3`. The one I have all my modules for it and everything installed on is the one:

    >>> import shutil
    >>> print(shutil.which('python3'))
    /Library/Frameworks/Python.framework/Versions/3.9/bin/python3

So we can see that there are to installations or whatever of python3 interpreters (I believe I am saying this right), and I am confused on maybe I am being hinted to use the python3 binary from /usr/bin/ to compile it with pyinstaller and install the needed modules with /usr/bin/pip3 with it?

A user from the reddit thread I made below made a alternative:

> I tested it on my computer after fixing a bug, and both the shutil and os methods work _(when packaged in --windowed mode)_. It seems to be a problem on your end, which is strange. What version of Python do you have? Also in your script right above testing for ffmpeg, try inserting this line:
> print('ffmpeg' in os.listdir('/usr/local/bin'))

This other method with `os` unfortunately returned a None as well _(when packaged in --windowed mode)_. I am ultimately trying to have some kind of method to reliably detect ffmpegs's binary **on all operating systems**. If anyone can provide some insight as to what may cause problems similar to these or knows other solutions, or can identify some kind of hiccup I can avoid that would be amazing.

I have a hunch since `shutil` when compiled returned the bin directory for python3 instead of the framework one that actually has all the modules installed, that could mean something to me to try using pyinstaller with that one instead?

Thanks!

https://www.reddit.com/r/learnpython/comments/nu3a1d/functionallity_supposedly_of_shutilwhichffmpeg/ 

  [1]: https://github.com/leifadev/scout

**Comment by bwoodsend** [comment]
Where is your `ffmpeg` binary? And if it's not in standard locations (either `/bin` or `/usr/bin`) then how is that directory added to `PATH`? I'm guessing you have a `.profile`/`.zshrc`/(whatever the macOS `.bashrc` is called) which adds it? In which case, this will only be loaded by terminal applications.

**Comment by rokm** [comment]
As Brénainn said, the macOS .app bundles that are launched via UI (i.e., Finder) operate with significantly reduced environment compared to console/POSIX executables. Among other things, the `PATH` is significantly reduced.

Consider the following test program that dumps environment variables:

```python
# program.py
import os
import sys

if getattr(sys, 'frozen', False):
    basedir = os.path.dirname(sys.executable)
else:
    basedir = os.getcwd()

with open(os.path.join(basedir, 'output.txt'), 'w') as fp:
    for key, value in os.environ.items():
        print("%s: %s" % (key, value), file=fp)
```

Try running it from terminal first; as python script, as `onedir` executable and as `onedir` .app bundle, where the latter two are obtained via `pyinstaller --clean --noconfirm program.py --windowed` (and are launched as `./dist/program/program`
 and `open ./dist/program.app`, respectively).

In unfrozen version, the script creates `output.txt` in current working directory. In frozen version, it creates 'output.txt' next to the executable; i.e., `./dist/program/output.txt` for `onedir` build or `./dist/program.app/Contents/MacOS/output.txt`.

Save those output.txt files comparison.

Then move `dist/program.app` to `/Applications/program.app`, and launch `program` from Finder. Check the output in `/Applications/program.app/Contents/MacOS/output.txt`. See how reduced the environment in this case is. And especially, see that `PATH` in this case contains only `/usr/bin:/bin:/usr/sbin:/sbin`.

That's why `shutil` manages to pick up only `python3` in `/usr/bin` (which is probably the 3.8.2 version that Apple ships with Big Sur).

---

> I am ultimately trying to have some kind of method to reliably detect ffmpegs's binary on all operating systems.

Why not just ship it with your frozen application?

**Comment by leifadev** [comment]
> Where is your `ffmpeg` binary? And if it's not in standard locations (either `/bin` or `/usr/bin`) then how is that directory added to `PATH`? I'm guessing you have a `.profile`/`.zshrc`/(whatever the macOS `.bashrc` is called) which adds it? In which case, this will only be loaded by terminal applications.

Sorry if I didn't mention that detail, it is located in /usr/local/bin/ffmpeg. It is an alias that goes to the Cellar folder for homebrew, which I installed it from

**Comment by leifadev** [comment]
> As Brénainn said, the macOS .app bundles that are launched via UI (i.e., Finder) operate with significantly reduced environment compared to console/POSIX executables. Among other things, the `PATH` is significantly reduced.
> 
> Consider the following test program that dumps environment variables:
> 
> ```python
> # program.py
> import os
> import sys
> 
> if getattr(sys, 'frozen', False):
>     basedir = os.path.dirname(sys.executable)
> else:
>     basedir = os.getcwd()
> 
> with open(os.path.join(basedir, 'output.txt'), 'w') as fp:
>     for key, value in os.environ.items():
>         print("%s: %s" % (key, value), file=fp)
> ```
> 
> Try running it from terminal first; as python script, as `onedir` executable and as `onedir` .app bundle, where the latter two are obtained via `pyinstaller --clean --noconfirm program.py --windowed` (and are launched as `./dist/program/program`
> and `open ./dist/program.app`, respectively).
> 
> In unfrozen version, the script creates `output.txt` in current working directory. In frozen version, it creates 'output.txt' next to the executable; i.e., `./dist/program/output.txt` for `onedir` build or `./dist/program.app/Contents/MacOS/output.txt`.
> 
> Save those output.txt files comparison.
> 
> Then move `dist/program.app` to `/Applications/program.app`, and launch `program` from Finder. Check the output in `/Applications/program.app/Contents/MacOS/output.txt`. See how reduced the environment in this case is. And especially, see that `PATH` in this case contains only `/usr/bin:/bin:/usr/sbin:/sbin`.
> 
> That's why `shutil` manages to pick up only `python3` in `/usr/bin` (which is probably the 3.8.2 version that Apple ships with Big Sur).
> 
> > I am ultimately trying to have some kind of method to reliably detect ffmpegs's binary on all operating systems.
> 
> Why not just ship it with your frozen application?

Sorry, what do you mean by shipping _it_ with my frozen app? I kind of followed along with getting the output texts, with their different dirs including the one for ffmpeg's location. Your point is as it being frozen and ran, it PATHs are significantly different? I tried to emulate your instructions for that part but didn't have luck. So you mean to ship ffmpeg with it in some way?

**Comment by rokm** [comment]
Yes, the point of the first part of my reply was to illustrate that PATH is significantly different depending on how you launch the application on macOS; which in turn is the reason why you cannot discover brew-installed ffmpeg (and why system version of python3 is discovered). 

The second part was in reply to your statement that you're trying to find ffmpeg binary on the target system. And yes, my question was why are you relying on system-installed ffmpeg instead of bundling a copy with your frozen application. (Or have the frozen version use bundled copy, while unfrozen version tries to discover the system-installed version). Usually the license would be concern, but your application is GPLv3 anyway.

Or conversely, if you are expecting users to have ffmpeg installed via homebrew, it is not such a large leap to expect them to have all other dependencies installed as well and run your application from source, without pyinstaller involved.

**Comment by leifadev** [comment]
Ah I see what your saying about that. I guess what your implying here is ffmpeg not just installed with homebrew could still have different paths besides in the binaries folder (new to unix file systems)? Also, could this be a means of adding more paths to the app somehow and at least expanding the likelihood of detecting it? 

Also, regarding your second paragraph, how would install ffmpeg as a bundle with my app? Can I use some of ffmpeg's dev tools or stuff they have to do this? It seems this process to fix this problem is only needed for macOS, no other OS it seems. 

But I do see there is a literal binary file I can download of ffmpeg.org. I can ship this with the mac tar file, best solution then. With that being said, mid-writing this post, I can use wget to fetch the binary into the config folder (https://evermeet.cx/ffmpeg/ffmpeg-4.4.7z).

I have solved this, any comment would be appreciated ¯\_(ツ)_/¯

**Comment by leifadev** [comment]
> Yes, the point of the first part of my reply was to illustrate that PATH is significantly different depending on how you launch the application on macOS; which in turn is the reason why you cannot discover brew-installed ffmpeg (and why system version of python3 is discovered).
> 
> The second part was in reply to your statement that you're trying to find ffmpeg binary on the target system. And yes, my question was why are you relying on system-installed ffmpeg instead of bundling a copy with your frozen application. (Or have the frozen version use bundled copy, while unfrozen version tries to discover the system-installed version). Usually the license may be a concern, but your application is GPLv3 anyway.
> 
> Or conversely, if you are expecting users to have ffmpeg installed via homebrew, it is not such a large leap to expect them to have all other dependencies installed as well and run your application from source, without pyinstaller involved.

Ah I see what your saying about that. I guess what your implying here is ffmpeg not just installed with homebrew could still have different paths besides in the binaries folder (new to unix file systems)? Also, could this be a means of adding more paths to the app somehow and at least expanding the likelihood of detecting it? 

Also, regarding your second paragraph, how would install ffmpeg as a bundle with my app? Can I use some of ffmpeg's dev tools or stuff they have to do this? It seems this process to fix this problem is only needed for macOS, no other OS it seems. 

But I do see there is a literal binary file I can download of ffmpeg.org. I can ship this with the mac tar file, best solution then. With that being said, mid-writing this post, I can use wget to fetch the binary into the config folder (https://evermeet.cx/ffmpeg/ffmpeg-4.4.7z).

I have solved this, any comment would be appreciated ¯\_(ツ)_/¯

**Comment by leifadev** [comment]
Added a block of code that downloads latest ffmpeg binary and I use that with some other steps like modding perms. Should find it in the scout.py early on :)
