### ISSUE TITLE
Segmentation fault on another computer using python:3.8 Docker image build

### ISSUE THREAD

**Issue by sshuair** [pyinstaller/pyinstaller#5934]
## Description of the issue

I use the `python:3.8`  docker image to build the executable on my linux(ubuntu:18.04) computer.

The code is simply :
```python
for item in range(10):
    print(item)
```

The executable works fine in the docker container insider. 
But when I copy the executable to my linux computer, It got the following error:

```
$./test
Segmentation fault (core dumped)
```

How can I fix this?

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.3```
* Version of Python: 3.8
* Platform: Linux
* How you installed Python: using official python:3.8 docker image: `docker pull python:3.8`

Update:

- I have tried to build the image from original  image `ubuntu:18.04`, It' not work either.
- and (cdrr/docker-pyinstaller](https://github.com/cdrx/docker-pyinstaller/blob/master/Dockerfile-py3-amd64) also not work.

**Comment by rokm** [comment]
If I try to build your sample program in `python:3.8` container (which seems to be based on debian 10.9) and then try to run it under ubuntu 18.04, I get the following error:
```
[5807] Error loading Python lib '[...]/program/libpython3.8.so.1.0': dlopen: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.28' not found (required by [...]/program/libpython3.8.so.1.0)
```
which is caused by the fact that container is using newer glibc than ubuntu 18.04 and therefore `libpython3.8.so.1.0` originating from the container refuses to load.

Cannot reproduce the segfault, though.

**Comment by bwoodsend** [comment]
What's your own glibc version (you can normally get it just by executing `/lib/libc.so.?` directly)?

**Comment by sshuair** [comment]
- @rokm You can copy the `/lib/x86_64-linux-gnu/libc.so.6` using the binaries in pyinstaller spec.
- @bwoodsend It's `libc-2.28.so`, you can check out the test.spec below.

Here is the all codes I used:

- test.py
  ```
  for item in range(10):
      print(item)
  ``
- test.spec: pyinstaller spec file
  ```python
  # -*- mode: python ; coding: utf-8 -*-
  
  
  block_cipher = None
  
  
  a = Analysis(['test.py'],
               pathex=['/workdir'],
               binaries=[
                   ('/lib/x86_64-linux-gnu/libc.so.6','.'),
                  ('/lib/x86_64-linux-gnu/libc-2.28.so','.')
               ],
               datas=[],
               hiddenimports=[],
               hookspath=[],
               runtime_hooks=[],
               excludes=[],
               win_no_prefer_redirects=False,
               win_private_assemblies=False,
               cipher=block_cipher,
               noarchive=False)
  pyz = PYZ(a.pure, a.zipped_data,
               cipher=block_cipher)
  exe = EXE(pyz,
            a.scripts,
            a.binaries,
            a.zipfiles,
            a.datas,
            [],
            name='test',
            debug=False,
            bootloader_ignore_signals=False,
            strip=False,
            upx=True,
            upx_exclude=[],
            runtime_tmpdir=None,
            console=True )
   ```

- docker image
    ```bash
    docker pull python:3.8
    sudo docker run -ti --rm -v /PATH/TO/CODE/:/workdir python:3.8 bash
    ```

- pyinstaller command in the docker container
   ```bash
     pyinstaller test.spec
   ```

**Comment by rokm** [comment]
> @rokm You can copy the /lib/x86_64-linux-gnu/libc.so.6 using the binaries in pyinstaller spec.

No, you really can't. That's what causing the segfault.

**Comment by sshuair** [comment]
So, how to solve this problem?

**Comment by rokm** [comment]
> So, how to solve this problem?

Build in an older container and do not copy `libc`.

**Comment by sshuair** [comment]
@rokm 
So you mean the offical python docker image not work with pyinstaller?
And I should build an older ubuntu or older python version?

**Comment by rokm** [comment]
>  So you mean the offical python docker image not work with pyinstaller?

No, I mean that libraries built against glibc from Debian 10.9 will not work on Ubuntu 18.04. This has nothing to do with PyInstaller.

>  And I should build an older ubuntu or older python version?

You should build on a system with older glibc. Preferably using the same distribution (or at least distribution flavor) as your target one.

**Comment by sshuair** [comment]
ok, thanks.I will try it later. 
I have checked my computer glibc, It's 2.23.so, mybe that's the problem.
BTW, the python:3.8 docker image is ubuntu:16.04, and my computer is also ubuntu:16.04.

**Comment by rokm** [comment]
>  BTW, the python:3.8 docker image is ubuntu:16.04, and my computer is also ubuntu:16.04.

`docker pull python:3.8` gets you debian buster 10.9 container with glibc 2.28.

**Comment by PePoDev** [comment]
@rokm This means I can't build the exe file that can run in any distros because It can run only on the same distro as the builder right?

P.S. I want to use `Ansible` as a portable version written in Python, Then I think I can use `Pyinstaller` to pack it and run it as a single binary file on another machine.

Do you have any recommendations or suggestions if I don't know the target distribution?
