### ISSUE TITLE
Multiprocessing not working with Pyinstaller [Python 3.9]

### ISSUE THREAD

**Issue by AndresQuiVal** [pyinstaller/pyinstaller#5941]
I need pyinstaller for creating .exe files from command line programs, in some script I used the multiprocessing.Process class for creating a process and acted as expected when executing the script directly, then a different behaviour appeared when creating the .exe file; so I went further in my investigation and created a simple .py script that has a function, that it's called from a manually created process from multiprocessing.Process and what it does is sleeps for 3 seconds and prints before and after the sleep some identifiers that let me know the action of the process, the scripts is like this:

```
from multiprocessing import Process
from time import sleep

def callable():
    print("Starting the callable from Process")
    sleep(3)
    print("Ending the callable from Process")

if __name__ == "__main__":
    print("Starting main program")
    process = Process(target=callable)
    process.start()
    print("In the middle of the process execution")
    process.join() # await
```

the output when executing the.py directly is as expected like this:

```
Starting main program
In the middle of the process execution
Starting the callable from Process
Ending the callable from Process
```

But when creating the .exe file with pyinstaller as follows:

`pyinstaller test.py` (the script is named test.py)

and executing the .exe file, the output is like this:

```
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
Starting main program
In the middle of the process execution
...
```

and never stops

Here is happening one weird thing:

1. the Process is not calling the target that I specified, rather is like executing the whole script and validating the `if __name__ == "__main__"`!

So I concluded that this could be a possible bug in pyinstaller, hope answers please!

**Comment by bwoodsend** [comment]
See [multiprocessing.freeze_support()](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support).

**Comment by AndresQuiVal** [comment]
@bwoodsend Have tried that and doesn't work yet

My code:

```
import multiprocessing as mp
from time import sleep

def callable():
    print("Starting the callable from Process")
    sleep(3)
    print("Ending the callable from Process")

if __name__ == "__main__":
    mp.freeze_support()
    print("Starting main program")
    process = mp.Process(target=callable)
    process.start()
    print("In the middle of the process execution")
    process.join() # await 

```

**Comment by bwoodsend** [comment]
You're second code works for me.
```
λ python37 -m PyInstaller test.py
λ .\dist\test\test.exe
Starting main program
In the middle of the process execution
Starting the callable from Process
Ending the callable from Process
```

**Comment by AndresQuiVal** [comment]
Im using python 3.9 and pyinstaller 4.3, can you try out with that version? seems that you are using python 3.7

**Comment by rokm** [comment]
The version with added `multiprocessing.freeze_support()` works here with python 3.9 (tested with 3.9.1 and 3.9.5) and pyinstaller 4.3:

```
>dist\program\program.exe
Starting main program
In the middle of the process execution
Starting the callable from Process
Ending the callable from Process
``` 

Have you properly rebuild the test program?
