### ISSUE TITLE
Pyinstaller retargets to base installation even when given all the venv it can be given

### ISSUE THREAD

**Issue by AstroFloof** [pyinstaller/pyinstaller#5947]
## Description of the issue

Though I launch a venv install of pyinstaller and give it venv arguments, it retargets to the base interpreter instead of using the venv interpreter. This seems to make it package all the extraneous modules in my base interpreter with the exe, making it unreasonably large (8.8MB for 12KB of script plus some base64 values <100KB).

### Context information (for bug reports)

* Output of `pyinstaller --version`: 4.3
* Version of Python: 
* Platform: Windows 10 21H1 (English)
* How you installed Python: python.org/downloads + venv
* Did you also try this on another platform? Does it work there?
no

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
.\venv\Scripts\pyinstaller.exe main.py -y -F -w --clean -n o_pnguim --distpath .\compile --upx-dir "D:\Program Files\UPX" --paths .\venv\Lib\site-packages

```

### Stacktrace / full error message

```
115 INFO: PyInstaller: 4.3
115 INFO: Python: 3.9.5
127 INFO: Platform: Windows-10-10.0.19043-SP0
...
3278 INFO: distutils: retargeting to non-venv dir 'C:\\Program Files\\Python39\\lib'
... # I don't want it to do that
10448 INFO: Using Python library C:\Program Files\Python39\python39.dll
# or that
```

**Comment by bwoodsend** [comment]
Virtual environments do not contain a Python installation. They contain your 3<sup>rd</sup> party packages and a few redirect executables to glue the environment back to the original Python installation. All the standard library packages are contained in the original Python (`C:\\Program Files\\Python39\\lib`) and Python's own binaries itself (such as `C:\Program Files\Python39\python39.dll`) are likewise only in the master environment.
