### ISSUE TITLE
PyQT4 and pyInstaller 2.0 on MacOS 10.6+

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#595]
**Original date**: 2012/08/21
**Original reporter**: *anonymous*

I wrote a software based on PyQT. I can compile it easily on my Snow Leopard but I does not load on any other mac. Apparently there are missing librairies... It works perfectly on Windows and Linux... Is it a specific problem of Mac??
Also I do not use the python from mac but the one from the website. All my python apps are working correctly on my computer, so I assume this is something else??

**Comment by matysek** [comment]
Closing as outdated.
