### ISSUE TITLE
Avoid Creating Different Memory size executables 

### ISSUE THREAD

**Issue by krishna3008** [pyinstaller/pyinstaller#5950]
**Is your feature request related to a problem? Please describe.**
Hi
I created a python exe using pyinstaller and the memory size of the exe is around 132MB and same file ran in another PC which created a file of size 63MB and in another PC 340MB

**Describe the solution you'd like**
Can you please inform why this variation and how to create a exe with lowest possible size

**Comment by bwoodsend** [comment]
Please don't just post duplicates just to get answers.

**Comment by krishna3008** [comment]
Is there anything wrong in my query?

**Comment by rokm** [comment]
>  Is there anything wrong in my query?

Yes, you already opened exactly the same question [here](https://github.com/pyinstaller/pyinstaller/discussions/5949).
