### ISSUE TITLE
PyInstaller does not show images added at runtime

### ISSUE THREAD

**Issue by danishansari** [pyinstaller/pyinstaller#5958]
I have a simple app running on Flask, which displays images from a directory. Which works fine, until I create an executable using Pyinstaller. This executable also works when there were already some images at the time of creation, but it can't load any later added images, I guess it just bundles all the existing images. I tried with both a single file and a directory, nothing worked. I would be really grateful if somebody can give me some direction on this.

this is my spec file:
```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(['test.py'],
             pathex=['/home/danish/Downloads/danish/code/TestFlask'],
             binaries=[],
             datas=[('templates/index.html', 'templates/'), ('static/images', 'static/images')],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='test',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
```
For more details and sample code, [here](https://stackoverflow.com/questions/68153266/flask-with-pyinstaller-does-not-show-images-added-at-runtime).

**Comment by rokm** [comment]
Copying the code over for reference:
```python
import os
import requests
from flask import Flask
from flask import render_template

app = Flask(__name__)

image_no_ = 0

@app.route('/', methods = ['POST', 'GET'])
def show_image():
    global image_no_

    files = os.listdir('static/images')

    new_image = 'static/images/'+files[image_no_]
    print ('image path:', new_image)
    image_no_ += 1
    if image_no_ == len(files):
        image_no_ = 0

    return render_template("index.html", image=new_image)  

if __name__=='__main__':
    app.run(debug=True, host='127.0.0.1', port=8000)
```

Anyhow, at the first glance:

> files = os.listdir('static/images')

You are listing images from `static/images` in your current working directory instead from the frozen application bundle...

**Comment by rokm** [comment]
Try anchoring the image path to `sys._MEIPASS`, as described in [docs](https://pyinstaller.readthedocs.io/en/latest/runtime-information.html#using-file).
