### ISSUE TITLE
some macOS libraries get corrupted when packaged with pyinstaller

### ISSUE THREAD

**Issue by vachooho** [pyinstaller/pyinstaller#5965]
I have an app packaged with pyinstaller 4.3 on macos 10.15.7, python 3.8.10 and pyinstaller_hooks_contrib-2021.1-py2.py3-none-any.whl

However at run-time some extracted to tmp/ libraries get corrupted.
here is one example - libssl.1.1.dlib is valid in my Python installation:

% codesign -vvv /Library/Frameworks/Python.framework/Versions/3.8/lib/libssl.1.1.dylib
/Library/Frameworks/Python.framework/Versions/3.8/lib/libssl.1.1.dylib: **valid on disk**
/Library/Frameworks/Python.framework/Versions/3.8/lib/libssl.1.1.dylib: satisfies its Designated Requirement

However, in the app packaged with pyinstaller, when extracted, tmp folder contains invalid binary:

sudo codesign -vvv /Library/Application\ Support/*/tmp/_MEIGb4zlO/libssl.1.1.dylib
/Library/Application Support/*/tmp/_MEIGb4zlO/libssl.1.1.dylib: **invalid signature** (code or signature have been modified)
In architecture: x86_64

It seems that pyinstaller's loader is doing something wrong either on packaging stage or on extraction at run time

This is causing Rosetta 2 on Apple M1 machine generate bunch of crash logs (invalid signature, one per invalid dylib) when trying to translate the binary.

**Comment by vachooho** [comment]
Oh well, here is the reason:
dependent libraries install name has been changed: 
- it has to be re-signed again before packaging (may be provide a command line switch to provide a certificate for signing?)
- alternatively, it can be signed with ad-hoc certificate after expanding at runtime (though I am not sure if macOS will not start translating it right after copy and before re-signing)

otool -L  /Library/Frameworks/Python.framework/Versions/3.8/lib/libssl.1.1.dylib
/Library/Frameworks/Python.framework/Versions/3.8/lib/libssl.1.1.dylib:
	/Library/Frameworks/Python.framework/Versions/3.8/lib/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/Library/Frameworks/Python.framework/Versions/3.8/lib/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)


sudo otool -L /Library/Application\ Support/.../tmp/_MEIGb4zlO/libssl.1.1.dylib
/Library/Application Support/.../tmp/_MEIGb4zlO/libssl.1.1.dylib:
	@loader_path/libssl.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	@loader_path/libcrypto.1.1.dylib (compatibility version 1.1.0, current version 1.1.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

**Comment by rokm** [comment]
This should be already taken care of by #5581.
