### ISSUE TITLE
eel .exe file problem 

### ISSUE THREAD

**Issue by saeedmuqsin** [pyinstaller/pyinstaller#5980]
I am created a .exe file for my application which i just created with eel. I run pyinstaller and created a .exe file for my app. But the problem is that when I run that the .exe file it doesn't run the .exe and i don't know why??

**Comment by rokm** [comment]
The issue template is there for a reason. You did not provide an example code, so we have no idea what you are actually doing. And you did not provide any error message (assuming there was one in the first place), so there's no way to tell what's going on.
