### ISSUE TITLE
Pyinstaller doesn't include library on output

### ISSUE THREAD

**Issue by SashaSemenishchev** [pyinstaller/pyinstaller#5989]
pip install pywin32

```
import win32crypt #for example
```
run it with 
```python script.py```
All ok.
Compile it with ```pyinstaller -F script.py```
execute .exe file and get error
```
Traceback (most recent call last):
  File "script.py", line 5, in <module>
    import win32crypt
ModuleNotFoundError: No module named 'win32crypt'
[16332] Failed to execute script script
```

## Description of the issue
When I run script as usual using python script.py all works fine. As I compile this script with ```pyinstaller -F script.py ```
```
Traceback (most recent call last):
  File "script.py", line 5, in <module>
    import win32crypt
ModuleNotFoundError: No module named 'win32crypt'
[16332] Failed to execute script script
```
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```3.6```
* Version of Python: <3.7.4>
* Platform: Windows English
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [+] start with clean installation
  * [+] use the latest development version
  * [+] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [+] Package your program in **--onedir mode**
  * [+] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [+] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "script.py", line 5, in <module>
    import win32crypt
ModuleNotFoundError: No module named 'win32crypt'
[16332] Failed to execute script script
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Does it work if your run `python -m PyInstaller -F script.py` instead?

**Comment by bwoodsend** [comment]
You're mixing up virtual environments. Run `python -m pip install pyinstaller` then `python -m PyInstaller -F scrip.py`.
