### ISSUE TITLE
 'tensorflow.core.protobuf.meta_graph_pb2' not found 

### ISSUE THREAD

**Issue by MK096** [pyinstaller/pyinstaller#5992]
Whenever i try to run my gpt exe file, i get following error:
 'tensorflow.core.protobuf.meta_graph_pb2' module not found .
In editor code works fine

my code :

import gpt_2_simple as gpt2

model_name = "124M"
sess = gpt2.start_tf_sess()
gpt2.generate(sess)

![error](https://user-images.githubusercontent.com/20142735/125151736-b930ea00-e161-11eb-8aa2-a24a28685e54.PNG)

**Comment by rokm** [comment]
What are the versions of python, `tensorflow`, and `PyInstaller`?

**Comment by MK096** [comment]
> What are the versions of python, `tensorflow`, and `PyInstaller`?

Python 3.7
Tf = 1.15 (latest version won't work with gpt2) 
Actually i use eel (v 0.4)to generate exe (bcz it has html as frontend)... Eel makes use of pyinstaller.

**Comment by rokm** [comment]
It might; you would need to add `tensorflow.core.protobuf.meta_graph_pb2` to hiddenimports. Not sure how you do it with eel, but with plain pyinstaller, you would add `--hiddenimport tensorflow.core.protobuf.meta_graph_pb2` to your pyinstaller command.

**Comment by rokm** [comment]
Your test snippet seems to work (as in, gets past importing `gpt_2_simple`) when frozen with PyInstaller. Can you try freezing that snippet yourself, without `eel`?

**Comment by MK096** [comment]
> Your test snippet seems to work (as in, gets past importing `gpt_2_simple`) when frozen with PyInstaller. Can you try freezing that snippet yourself, without `eel`?

Thanks for trying. 
 "frozen with pyinstaller " as in?
Also which version of tf are you using?

**Comment by rokm** [comment]
>  "frozen with pyinstaller " as in?

```python
# program.py
import gpt_2_simple as gpt2

model_name = "124M"
sess = gpt2.start_tf_sess()
# gpt2.generate(sess)
print("Hello world!")
```

```
pyinstaller --clean --noconfirm program.py
```

```
dist\program\program.exe
```

Works without any additional hidden imports.

<details><summary>
Versions:
</summary>
<p>

```
(venv) python --version
Python 3.7.9

(venv) pip freeze
absl-py==0.13.0
altgraph==0.17
astor==0.8.1
cached-property==1.5.2
certifi==2021.5.30
chardet==4.0.0
colorama==0.4.4
future==0.18.2
gast==0.2.2
google-pasta==0.2.0
gpt-2-simple==0.7.2
grpcio==1.38.1
h5py==3.3.0
idna==2.10
importlib-metadata==4.6.1
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.2
Markdown==3.3.4
numpy==1.21.0
opt-einsum==3.3.0
pefile==2021.5.24
protobuf==3.17.3
pyinstaller==4.3
pyinstaller-hooks-contrib==2021.2
pywin32-ctypes==0.2.0
regex==2021.7.6
requests==2.25.1
six==1.16.0
tensorboard==1.15.0
tensorflow==1.15.0
tensorflow-estimator==1.15.1
termcolor==1.1.0
toposort==1.6
tqdm==4.61.2
typing-extensions==3.10.0.0
urllib3==1.26.6
Werkzeug==2.0.1
wrapt==1.12.1
zipp==3.5.0
```

</p>
</details>

**Comment by MK096** [comment]
I tried pyinstaller --hiddenimport tensorflow.core.protobuf.meta_graph_pb2 --clean --noconfirm test.py and i am still getting same error.
205970 ERROR: Hidden import 'tensorflow.core.protobuf.meta_graph_pb2' not found

>Versions:
absl-py==0.13.0
aiohttp==3.7.4.post0
aitextgen==0.5.2
altair==4.1.0
altgraph==0.16.1
appdirs==1.4.4
args==0.1.0
arrow==1.1.0
astor==0.8.1
astunparse==1.6.3
async-timeout==3.0.1
atomicwrites==1.4.0
attrs==19.3.0
auto-py-to-exe==2.9.0
backcall==0.1.0
backports.csv==1.0.7
base58==2.1.0
bcrypt==3.2.0
beautifulsoup4==4.7.1
bleach==3.1.5
blinker==1.4
blis==0.4.1
boto==2.49.0
boto3==1.9.233
botocore==1.12.233
bottle==0.12.17
bottle-websocket==0.2.9
bs4==0.0.1
cached-property==1.5.2
cachetools==4.2.2
catalogue==1.0.0
certifi==2020.12.5
cexprtk==0.3.4
cffi==1.12.3
cfgv==3.1.0
chardet==4.0.0
chart-studio==1.1.0
ChatterBot @ file:///C:/Users/Mayank/ChatterBot
chatterbot-corpus==1.2.0
click==7.1.2
clint==0.5.1
cloudpickle==1.4.1
colorama==0.4.3
colorize==1.0.4
configparser==5.0.2
contextlib2==0.6.0.post1
convert-numbers==0.0.2
cryptography==3.2.1
cycler==0.10.0
cymem==1.31.2
Cython==0.29.19
cytoolz==0.9.0.1
datasets==1.6.2
dateparser==1.0.0
decorator==4.4.2
deep-translator==1.4.2
defusedxml==0.6.0
-e git+https://github.com/conansherry/detectron2@72c935d9aad8935406b1038af408aa06077d950a#egg=detectron2
dill==0.3.3
distlib==0.3.0
dl-translate==0.2.2
docker-pycreds==0.4.0
docopt==0.6.2
docutils==0.15.2
docx==0.2.4
download==0.3.5
dunamai==1.5.5
EasyNMT==2.0.1
Eel==0.12.4
en==0.0.1
en-core-web-sm @ https://github.com/explosion/spacy-models/releases/download/en_core_web_sm-2.0.0/en_core_web_sm-2.0.0.tar.gz
English-to-Hindi==0.0.1
entrypoints==0.3
essential-generators==0.9.2
et-xmlfile==1.0.1
fasttext==0.9.2
filelock==3.0.12
fire==0.4.0
flatbuffers==1.12
Fraction==1.1.0
fsspec==2021.5.0
ftfy==6.0.1
future==0.17.1
futures==3.1.1
fuzzywuzzy==0.17.0
fvcore @ git+https://github.com/facebookresearch/fvcore@fb679749e3ba2714ac66680c9207c96a7e8e06d1
gast==0.2.2
gensim==3.8.0
get-version==3.0
gevent==1.4.0
gevent-websocket==0.10.1
gin-config==0.4.0
gitdb==4.0.7
GitPython==3.1.17
google==2.0.3
google-api-core==1.26.3
google-api-python-client==1.8.0
google-auth==1.30.0
google-auth-httplib2==0.1.0
google-auth-oauthlib==0.4.4
google-colab==1.0.0
google-images-download==2.8.0
google-pasta==0.2.0
googleapis-common-protos==1.53.0
googletrans==3.0.0
goslate==1.5.1
gpt-2-simple==0.7.2
GPUtil==1.4.0
graphviz==0.16
greenlet==0.4.15
grpcio==1.38.1
gTTS==2.0.3
gTTS-token==1.1.3
h11==0.9.0
h2==3.2.0
h5py==3.3.0
happytransformer==2.2.2
hpack==3.0.0
hstspreload==2020.6.16
httpcore==0.9.1
httplib2==0.19.1
httpx==0.13.3
huggingface-hub==0.0.8
hyperframe==5.2.0
ia-markov==0.3.1
identify==1.4.19
idlex==1.18
idna==2.10
imagesize==1.2.0
importlib-metadata==4.6.1
imutils==0.5.3
inexactsearch==1.0.2
inflect==4.1.0
iniconfig==1.1.1
internetarchive==1.8.1
ipykernel==5.5.5
ipython==5.5.0
ipython-genutils==0.2.0
ipywidgets==7.6.3
jdcal==1.4.1
jedi==0.17.0
Jinja2==2.11.2
jmespath==0.9.4
joblib==0.13.2
jsonlines==2.0.0
jsonpatch==1.26
jsonpickle==1.5.2
jsonpointer==2.0
jsonschema==3.2.0
jupyter-client==6.1.3
jupyter-core==4.6.3
jupyterlab-widgets==1.0.0
Keras==2.4.3
Keras-Applications==1.0.8
keras-nightly==2.5.0.dev2021032900
Keras-Preprocessing==1.1.2
kiwisolver==1.1.0
language-check==1.1
lda==1.1.0
llvmlite==0.36.0
lm-dataformat==0.0.19
lxml==4.3.1
Markdown==3.3.4
markovify==0.8.3
MarkupSafe==1.1.1
mathematics-dataset==1.0.1
mathparse==0.1.2
matplotlib==3.1.1
mesh-tensorflow==0.1.18
mingus==0.6.1
mistune==0.8.4
mixed==0.2.1
mock==2.0.0
moment==0.12.1
mpmath==1.1.0
msgpack==0.6.2
msgpack-numpy==0.4.7.1
multidict==5.1.0
multiprocess==0.70.11.1
munch==2.5.0
murmurhash==0.28.0
musicalbeeps==0.2.9
nbconvert==5.6.1
nbformat==5.0.6
nltk==3.4.5
nodeenv==1.4.0
notebook==5.2.2
num2words==0.5.10
numba==0.53.1
numpy==1.21.0
oauth2client==4.1.3
oauthlib==3.1.0
opencv-contrib-python==4.1.0.25
opencv-python==4.2.0.34
openpyxl==2.6.3
opt-einsum==3.3.0
ortools==9.0.9048
packaging==20.4
pandas==0.24.2
pandocfilters==1.4.2
paramiko==2.7.2
parso==0.7.0
pathtools==0.1.2
pbr==3.1.1
pefile==2019.4.18
pickleshare==0.7.5
Pillow==8.2.0
plac==0.9.6
playsound==1.2.2
plotly==4.14.3
pluggy==0.13.1
pocketsphinx==0.1.15
portalocker==1.7.0
portpicker==1.2.0
pre-commit==2.5.1
preshed==1.0.1
promise==2.3
prompt-toolkit==1.0.18
protobuf==3.17.3
psutil==5.8.0
PTable==0.9.2
py==1.8.2
py-cpuinfo==8.0.0
py-expression-eval==0.3.10
py-thesaurus==1.0.5
py-translate==1.0.3
pyarrow==4.0.0
pyasn1==0.4.8
pyasn1-modules==0.2.8
PyAudio==0.2.11
pybind11==2.6.2
pycocotools @ git+https://github.com/philferriere/cocoapi.git@2929bd2ef6b451054755dfd7ceb09278f935f7ad#subdirectory=PythonAPI
pycparser==2.19
pydeck==0.6.2
pyDeprecate==0.3.0
PyDictionary==1.5.2
pydot==1.4.1
pyemd==0.5.1
pyenchant==2.0.0
pygame==1.9.4
Pygments==2.6.1
pyinstaller==4.3
pyinstaller-hooks-contrib==2020.9
pymongo==3.11.4
PyNaCl==1.4.0
pynput==1.6.0
pyparsing==2.4.2
pypiwin32==223
pyrsistent==0.16.0
pyspellchecker==0.5.6
pytest==6.2.4
python-dateutil==2.8.0
python-docx==0.8.10
python-Levenshtein==0.12.0
PythonTurtle==0.3.2
pytorch-lightning==1.3.3
pyttsx3==2.7
pytz==2019.2
pywin32==224
pywin32-ctypes==0.2.0
PyYAML==5.4.1
pyzmq==19.0.1
regex==2017.4.5
requests==2.25.1
requests-oauthlib==1.3.0
retrying==1.3.3
rfc3986==1.4.0
ring==0.7.3
rsa==4.7.2
s3transfer==0.2.1
sacred==0.8.2
sacremoses==0.0.45
schema==0.7.2
scikit-learn==0.21.3
scipy==1.6.3
seaborn==0.10.0
selenium==3.141.0
sentencepiece==0.1.95
sentry-sdk==1.1.0
seqeval==1.2.2
shortuuid==1.0.1
silpa-common==0.3
simpleaudio==1.0.4
simplegeneric==0.8.1
simpletransformers==0.61.6
six==1.16.0
sklearn==0.0
smart-open==1.8.4
smmap==4.0.0
sniffio==1.1.0
soundex==1.1.3
soupsieve==1.8
spacy==2.0.12
SpeechRecognition==3.8.1
SQLAlchemy==1.3.20
srsly==1.0.2
streamlit==0.82.0
subprocess32==3.5.4
sympy==1.5
tabulate==0.8.7
tensorboard==1.15.0
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.0
tensorboardX==2.2
tensorflow==1.15.0
tensorflow-addons==0.13.0
tensorflow-datasets==3.2.1
tensorflow-estimator==1.15.1
tensorflow-metadata==0.30.0
termcolor==1.1.0
testpath==0.4.4
textblob==0.15.3
thinc==6.10.3
times==0.7
tokenizers==0.10.3
toml==0.10.1
toolz==0.11.1
toposort==1.6
torch @ file:///C:/Users/Mayank/torch-1.8.0%2Bcu111-cp37-cp37m-win_amd64.whl
torchmetrics==0.2.0
torchvision==0.9.1
tornado==6.1
tox==3.15.2
tpunicorn==0.5.5
tqdm==4.49.0
traitlets==4.3.3
transformers==4.5.0
translate==3.5.0
typeguard==2.12.1
typing-extensions==3.10.0.0
tzlocal==2.1
ujson==4.0.1
Unidecode==1.1.1
uritemplate==3.0.1
urllib3==1.25.11
validators==0.18.2
versioneer==0.19
virtualenv==20.0.23
Vocabulary==1.0.4
wandb==0.10.32
wasabi==0.6.0
watchdog==2.1.2
wcwidth==0.1.9
weather-api==1.0.7
webencodings==0.5.1
Werkzeug==2.0.1
whichcraft==0.6.1
widgetsnbextension==3.5.1
wikipedia==1.4.0
wirerope==0.3.0
word2number==1.1
wordcloud==1.8.1
wrapt==1.12.1
wxPython==4.0.4
xlrd==1.2.0
XlsxWriter==1.3.7
xxhash==2.0.2
yacs==0.1.7
yarl==1.6.3
zipp==3.5.0
zstandard==0.15.2

![error-2](https://user-images.githubusercontent.com/20142735/125166751-73524100-e1b6-11eb-8874-3878c1fbd712.PNG)

**Comment by rokm** [comment]
Hmmm, yeah, `tensorflow.core.protobuf.meta_graph_pb2` does not really exist - or rather, it exists as `tensorflow_core.protobuf.meta_graph_pb2` and then `tensorflow` creates an alias for it...

So can you try to add that one to hiddenimports instead?

But either way, that's a non-fatal build-time error. Does the generated .exe work or not?

**Comment by MK096** [comment]
> Hmmm, yeah, `tensorflow.core.protobuf.meta_graph_pb2` does not really exist - or rather, it exists as `tensorflow_core.core.protobuf.meta_graph_pb2` and then `tensorflow` creates an alias for it...
> 
> So can you try to add that one to hiddenimports instead?
> 
> But either way, that's a non-fatal build-time error. Does the generated .exe work or not?

I tried hidden-import and it didn't work.
So what i did was i moved the content of tensorflow-core to tensorflow folder and then it worked like charm.
Thanks for the help though
