### ISSUE TITLE
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#5994]
I recently started to get this error with the latest pyinstaller from github (and also prod versions installed via pip): 

It only happens when I run the pyinstalled packaged version of my code. Any suggestions how this could be resolved? thanks
```

ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.
Traceback (most recent call last):
  File "poker\gui\action_and_signals.py", line 275, in <lambda>
  File "poker\gui\action_and_signals.py", line 432, in update_strategy_analyser
  File "poker\gui\action_and_signals.py", line 446, in strategy_analyser_update_plots
  File "poker\gui\plots\bar_plotter_2.py", line 78, in drawfigure
  File "pandas\plotting\_core.py", line 892, in __call__
  File "pandas\plotting\_core.py", line 1814, in _get_plot_backend
  File "pandas\plotting\_core.py", line 1757, in _load_backend
ImportError: matplotlib is required for plotting when the default backend "matplotlib" is selected.
```

**Comment by rokm** [comment]
This seems to be just what the error is saying - `matplotlib` is not present in the frozen application.

Can you check if `build\<name>\Analysis-00.toc` lists any `matplotlib` modules? 
If not, check if the build log contains any `matplotlib` related messages (e.g., `Loading module hook 'hook-matplotlib.py' from ...`). 
If not, check if the environment from which you are running pyinstaller (which may or may not be the same as the one you use when you run source version of your code) has `matplotlib` installed?

**Comment by dickreuter** [comment]
Downgrading to pandas 1.2.4 resolved the issue.

**Comment by michaeleveringham** [comment]
For others having the same issue and don't want to downgrade anything, you can add `import pandas.plotting._matplotlib` to resolve this. 

<hr>

If you're trying to use `plt.show()` you may get `UserWarning: Matplotlib is currently using agg, which is a non-GUI backend, so cannot show the figure.` Explicitly setting the `matplotlib` backend resolves this, however, you'll have to first explicitly import the backend from `matplotlib.backends` and then use it. 


```python
import matplotlib
import matplotlib.backends.backend_tkagg
matplotlib.use('tkagg')
```
