### ISSUE TITLE
Error building pyinstaller bootloader on my windows 10 PC

### ISSUE THREAD

**Issue by ury-j** [pyinstaller/pyinstaller#5998]
Downloaded pyinstaller 4.3 sources from https://github.com/pyinstaller/pyinstaller/releases to my PC.
Tried to build the bootloader according to guidelines in "Building the Bootloader" page.
Process stops almost immediately with return code 1 from pyinstaller-4.3\\bootloader\\build\\waf-print-msvc-1.bat.

After running "python ./waf all" the output is:
**'all' finished successfully (0.000s)
'distclean' finished successfully (0.000s)
Setting top to                           : E:\pyinstaller-4.3\bootloader
Setting out to                           : E:\pyinstaller-4.3\bootloader\build
Python Version                           : 3.9.6 (tags/v3.9.6:db3ff76, Jun 28 2021, 15:26:21) [MSC v.1929 64 bit (AMD64)]
Checking for 'msvc' (C compiler)         : Command ['cmd.exe', '/E:on', '/V:on', '/C', 'E:\\pyinstaller-4.3\\bootloader\\build\\waf-print-msvc-1.bat'] returned 1**

Please note that when running this batch file manually from the command line the return code is 0.
Also Visual Studio 2015 is installed on my PC.

* Output of `pyinstaller --version`: **did not reach this stage yet.**
* Version of Python: **3.9.6**
* Platform: **Windows 10 pro**
* How you installed Python: **Do not remember, was a while ago. Probably using recommended installation .**
* Did you also try this on another platform? **No**

* follow *all* the instructions in our "If Things Go Wrong" Guide - **not relevant**

I attach **config.log**.
[config.log](https://github.com/pyinstaller/pyinstaller/files/6797055/config.log)

Thanks,
Ury

**Comment by rokm** [comment]
Can you try running the test example from https://github.com/pyinstaller/pyinstaller/discussions/5956#discussioncomment-922571? Does msvc check succeed there or does it have the same issue?

The msvc check is not pyinstaller-specific (i.e., comes from `waf` build system itself), so if there's an issue there, it is between `waf` and your VS2015 installation.

**Comment by ury-j** [comment]
Ran the test example and got the same issue. Output is:
**Setting top to                           : E:\pyinstaller-4.3\bootloader\temp
Setting out to                           : E:\pyinstaller-4.3\bootloader\temp\build
Checking for 'msvc' (C compiler)         : Command ['cmd.exe', '/E:on', '/V:on', '/C', 'E:\\pyinstaller-4.3\\bootloader\\temp\\build\\waf-print-msvc-1.bat'] returned 1**

As far as i know, my VS2015 installation is OK, also tested with other versions of VS and got the same issue.
So, if it's a `waf` issue, how can i proceed?

**Comment by rokm** [comment]
Does it help if your run waf command from "VS Tools Command Line Prompt" (or explicitly set up your environment by running `vcvarsall.bat`)? 

Perhaps you can check if you have the C/C++ part of VS installed (it is usually not installed by default)?

Also, the output in your attached `config.log` seems a bit terse; in particular, I'm missing the output JSON from `vswhere.exe` call. Is it actually missing or did you leave it out?

**Comment by bwoodsend** [comment]
You sure you've not just got Visual Studio the fancy text editor rather than the Visual Studio build tools? Does `C:/Program Files (x86)/Microsoft Visual Studio 15.0/VC/vcvarsall.bat` exist and if you run it in `cmd`, can you then run `cl.exe`?

**Comment by ury-j** [comment]
@rokm
1. When running from the vs command prompt getting the same error.
2. I do have the c/c++ of the visual, in fact i have full installations of several VS versions, getting the same result with all the versions.
3. The config.log is complete, nothing left out.

@bwoodsend
I am using VS to build C/C++/C# applications so i am pretty sure it is the full installation. 
Apart from it, when running **waf-print-msvc-1.bat**  manually, no error occurs, the PATH, INCLUDE and LIB parameters are set appropriately and the returned error level is 0.

**Comment by rokm** [comment]
What are the contents of `E:\\pyinstaller-4.3\\bootloader\\build\\waf-print-msvc-1.bat` ?

**Comment by ury-j** [comment]
These are the contents:
**@echo off
set INCLUDE=
set LIB=
call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x64
echo PATH=%PATH%
echo INCLUDE=%INCLUDE%
echo LIB=%LIB%;%LIBPATH%**

**Comment by rokm** [comment]
> These are the contents:

That looks alright, too. But I think the only way for `waf-print-msvc-1.bat` to fail is if `vcvarsall.bat` call failed for whatever reason. 

The [waf docs on msvc](https://waf.io/apidocs/tools/msvc.html) suggest to set codepage in terminal to utf-8 if there are detection problems. Perhaps that is also the case here?

Either way, I'd say the problem is specific to your environment; I tried installing VS2015 Community in clean Windows 10 VM, and it works as expected. So I doubt we'll be able to figure it out from our end.

**Comment by bwoodsend** [comment]
Any reason you can't just use gcc instead? All you have to do is download [a WinLibs build](https://winlibs.com/#download), unzip it, then run:
```cmd
set CC=E:\path\to\winlibs\mingw64\bin\gcc.exe
python waf all
```

**Comment by ury-j** [comment]
Finally managed to build bootloader on another device.
Why it didn't build on my device remains a mystery.
Thanks @rokm and @bwoodsend.
