### ISSUE TITLE
Pyinstaller : Unable to find “anaconda3/lib/libomp-fallback-cassert.o” when adding binary and data files

### ISSUE THREAD

**Issue by zonnalobo** [pyinstaller/pyinstaller#6005]
I got this error when trying to compile my script using Pyinstaller 4.4:

`Unable to find "anaconda3/lib/libomp-fallback-cassert.o" when adding binary and data files.`
The script running on python 3.8.10 with system Red Hat Enterprise Linux 7.7. Modules that I use are:

```
import pandas as pd
import numpy as np
import cx_Oracle
from fuzzywuzzy import process,fuzz
from multiprocessing import Pool
from sqlalchemy import types,create_engine
import datetime
from currency_converter import CurrencyConverter
import gc
```

Is there any suggestion to solve it?

**Comment by rokm** [comment]
Hmm, I cannot reproduce this. In my test environment, that file is provided by `intel-openmp` `2021.2.0` `h06a4308_610`.

Can you try creating a clean python 3.8.10 conda environment, install `numpy` into it, and freeze a simple script that does only `import numpy as np`?

**Comment by zonnalobo** [comment]
hi @rokm , it solved. I create new environment, install all modules and run pyinstaller there.
it ends with:
`21601 INFO: Building COLLECT COLLECT-00.toc completed successfully.`
Thanks.

**Comment by rokm** [comment]
OK, guess it was an environment-related issue, then.

**Comment by zonnalobo** [comment]
the previous environment can be fixed by updating dpcpp-cpp-rt module to last version.
