### ISSUE TITLE
Since `jinja2` is optionally imported by `pandas`, `pyinstaller` does not collect it. So you either need to add `jinja2` to `hiddenimports` (e.g., `pyinstaller --hidden-import jinja2 ...`) or explicitly import `jinja2` somewhere in your program.

### ISSUE THREAD

**Issue by Gaurav7004** [pyinstaller/pyinstaller#6008]
pandas package was not installed in a way that packageloader understands.

**Comment by bwoodsend** [comment]
Yes that's intended behavior. pandas has many huge optional dependencies - would you really prefer if `import pandas` caused your application to automatically become several gigabytes?

**Comment by rokm** [comment]
Strictly speaking, `jinja2` is optional but required if one imports `pandas.io.formats.style` (that errors out if `jinja2` is unavailable). And it is not used anywhere else.

So we could put a hiddenimport in a hook for that specific module...
