### ISSUE TITLE
PyInstaller fails to load Werkzeug modules

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#602]
**Original date**: 2012/09/04
**Original reporter**: _torsten DOT landschoff AND dynamore DOT de_

I am trying to deploy an application that uses Werkzeug but I am unable to get PyInstaller to include the werkzeug.\* modules. Look at this example:

```
#!py
from werkzeug.exceptions import InternalServerError
print "Hello World!"
```

Obviously this works fine when called directly from Python. Using pyinstaller on test.py without any options gives an executable which acts like this:

```
torsten@sharokan:~/pyinstaller-test$ ~/workspace/pyinstaller-2.0/pyinstaller.py test.py
torsten@sharokan:~/pyinstaller-test$ ./dist/test/test 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/torsten/workspace/pyinstaller-2.0/PyInstaller/loader/iu.py", line 409, in importHook
    raise ImportError("No module named %s" % fqname)
ImportError: No module named werkzeug.exceptions
```

I created a hook to make PyInstaller include the werkzeug submodules and placed it into the directory hookspath. I enabled that hook by modifying the generated test.spec to include

```
#!py
a = Analysis(['test.py'],
             pathex=['/home/torsten/pyinstaller-test'],
             hiddenimports=[],
             hookspath="hookspath")
```

But I noticed that this does not make a difference for the build result: The file logdict2.7.3.final.0-2.log is unchanged. In fact, the original version also contains the werkzeug.exceptions module (verified with ArchiveViewer.py).

Why this module can not be loaded is beyond me. I enabled the debug output of iu.py and will attach that file. Perhaps somebody with more insight into PyInstaller internals can go and fix the loader.

The only workaround I found was to replace the **init**.py in the werkzeug package to remove the lazy load feature by commenting out the last lines so that new_module is not written into sys.modules["werkzeug"].

**Comment by htgoebel** [comment]
@bluehorn: Is it you who opened this issue originally at the old trac-instance? If so: Is this still an issue with PyInstaller 3.1.1?

**Comment by Bluehorn** [comment]
@htgoebel: Yep, that's me. I will check if this works in PyInstaller 3.1.1. We are still at our fork from PyInstaller trunk from years ago because we have a lot of local fixes. Not sure if we will upgrade before our switch to CPython 3 which is likely to take a few more years...

**Comment by Bluehorn** [comment]
Just checked with PyInstaller 3.1.1 and the resulting binary worked just fine.

**Comment by htgoebel** [comment]
It's time to finally fix or close this issue.

**Comment by Bluehorn** [comment]
> It's time to finally fix or close this issue.

AFAICT this has been fixed long ago. I can't close the ticket though as I am not listed as the creator on github: The ticket was ported over from trac.
I am all for closing this!
