### ISSUE TITLE
AVG (and other antiviruses) reports exe file as containing virus

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#603]
**Original date**: 2012/09/05
**Original reporter**: *brianboggs AND mchsi DOT  COOM *

I've compiled a script to an exe file, but our PCs equipped with AVG free virus scanner will not execute them, flagging them as containing a Trojan Horse (backdoor.generic.byzx)

**Comment by marcelstoer** [comment]
Can/should be addressed by building your own bootloader: https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html
