### ISSUE TITLE
fix_exe_for_code_signing() should increase the vmsize field of the LINKEDIT segment

### ISSUE THREAD

**Issue by ntamas** [pyinstaller/pyinstaller#6039]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```pyinstaller 4.4```
* Version of Python: 3.8.11
* Platform: macOS 11.4 Big Sur
* How you installed Python: Homebrew
* Not tried it on any other platform as it is relevant for macOS only.

This is not really a bug in the "normal" sense as PyInstaller works correctly in general; however, there is a comment in the `fix_exe_for_code_signing()` function in `utils/osx.py` that ponders whether the `vmsize` field of the `LINKEDIT` segment should be increased or it is enough to increase the `filesize` field. I would like to point out that the `vmsize` field should be increased as well; this can be confirmed by looking at the source code of `dyld`, which clearly complains if the `vmsize` is smaller than the `filesize` (see the source code [here](https://opensource.apple.com/source/dyld/dyld-852/src/ImageLoaderMachO.cpp.auto.html), search for `is larger than vmsize`).

The reason why it still works with PyInstaller-generated executables (I think) is because adding the code signature with `codesign` _after_ the executable was tweaked with `fix_exe_for_code_signing()` will adjust the `vmsize` appropriately so it becomes larger than `filesize` and also becomes aligned to the page size (4096 bytes). However, it would be better if the code did not rely on a later call `codesign` to fix the headers and just produced a valid executable when returning from `fix_exe_for_code_signing()`.

**Comment by bwoodsend** [comment]
Well what you're saying sounds sensible although I wouldn't know either way. Any ideas @rokm? I suggest we just go for it, adjust the size and see what happens on CI.

**Comment by rokm** [comment]
Yeah, let's re-enable modification of vmsize, then. I left it out because it did not seem necessary, but that might indeed be due to the following `codesign` step.

**Comment by rokm** [comment]
@ntamas Do you know if it is enough to just increase the `vmsize`, or do we also need to round it up to the next full page size?

**Comment by ntamas** [comment]
I don't know for sure, but what I know is that `codesign` definitely rounds it up to the nearest multiple of the page size. (Tested in the CLI by stripping the signature, modifying the Mach-O headers to have a smaller `vmsize` by a few bytes, and then re-signing).

**Comment by bwoodsend** [comment]
Well if Apple's own tools are doing it then I say we assume yes - we should round up.

**Comment by bwoodsend** [comment]
@andydhobbs Very specific question but I don't suppose you happen to know if the `vmsize` in a Macho-O header needs to be a multiple of the page size?

**Comment by andydhobbs** [comment]
I am not sure sorry, this is outside my area of expertise

**Comment by andydhobbs** [comment]
https://opensource.apple.com/source/xnu/xnu-2050.18.24/EXTERNAL_HEADERS/mach-o/loader.h

Seems to infer that segments are aligned for efficient paging so it would make sense for vmsize to be a multiple of page size

**Comment by bwoodsend** [comment]
Ok, so possibly not mandatory but still a good idea.
