### ISSUE TITLE
Problem with OSX bundle

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#604]
**Original date**: 2012/09/06
**Original reporter**: *martin AND pipegrep DOT co DOT uk*

I packaged an application in OSX without error using the --windowed flag to generate an application bundle. Running the bundle either with a double click or:

open my_app.app

on the command line does not start the application, or give an error.

Running the following:

./my_app/Contents/MacOS/my_app

works without problems. Is there an issue with the way the bundle is structured?

**Comment by matysek** [comment]
Please test the latest dev version. If that does not work then report a new issue.
