### ISSUE TITLE
Problem with Matplotlib Mathtext Fonts

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#605]
**Original date**: 2012/09/10
**Original reporter**: *jonnojohnson AND gmail DOT  COOM *

When I try to use Matplotlib's mathtext functionality the exe runs fine on the machine it was compiled on but crashes when run on a "clean" machine. The only warnings I get when running pyinstaller are:

```
library python%s%s required via ctypes not found
pythoncom is changing its name to pythoncom27
pywintypes is changing its name to pywintypes27
```

I'm running on Win7 machines, Python 2.7, Matplotlib 1.1.0, PyInstaller 2.0

**Comment by matysek** [comment]
There is no example how to reproduce this issue.
