### ISSUE TITLE
Could not initialize .pyd; aborting

### ISSUE THREAD

**Issue by nsage-creatively** [pyinstaller/pyinstaller#6050]
## Description of the issue

Pyinstaller builds Python application without error, but application cannot initialize .pyd library file.

When Python script is run directly, the .pyd is initialized without error. However, the .exe fails at this point without explanation.

Script used to build .exe: pyinstaller pdf_processing.py.
Command used to run .exe: .\dist\pdf_processing\pdf_processing.exe

### Context information (for bug reports)
pyinstaller --version: 4.4
Version of Python: 3.8
Platform: Windows 10 Pro x64
How you installed Python: Anaconda
Did you also try this on another platform? No

### Minimal example program which shows the error:
```
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
import pdf2img

# omitted

# calling the Pybind11 .pyd with parameters a b c, blah blah...:
x = pdf2img.main(5,
    [exe_dir,
     "-resolution=" + dpi,
     "-output=" + out_dir + '/' + pdf[:-4],
     pdf_path,
     "PNG"])
```

### Stacktrace / full error message
```
ERROR: Could not initialize C:/Users/natap/Logo Detection/pdf2img.pyd; aborting.
```

Apologies if this is not truly a Pyinstaller bug, but please point me to the right direction. If I can run my script from Python but not from the .exe, something in the application is clearly being bundled incorrectly and I must know why.

**Comment by bwoodsend** [comment]
Ughh great. This looks like another Conda DLL error. 

> ERROR: Could not initialize C:/Users/natap/Logo Detection/pdf2img.pyd; aborting.

Was there really nothing before this? I'd expect some sort of Python traceback.

You could try collecting the conda DLLs with [`conda.collect_dynamic_libs()`](https://pyinstaller.readthedocs.io/en/stable/hooks.html#PyInstaller.utils.hooks.conda.collect_dynamic_libs). Edit the `pdf_processing.spec` file it should have generated. Put:
```python
from PyInstaller.utils.hooks import conda_support
```
at the top then in the `a = Analysis(...) ` block change `binaries=[]` to:
```python
binaries = conda_support.collect_dynamic_libs("pdf2img")
```

Then rebuild using:
```
pyinstaller pdf_processing.spec
```

**Comment by Wheelspawn** [comment]
> Was there really nothing before this? I'd expect some sort of Python traceback.
I didn't see anything.

**Comment by nsage-creatively** [comment]
`If that doesn't change anything, then we'll need to have a look at how that pyd file is linked...`

I tried the steps and they didn't work.

**Comment by bwoodsend** [comment]
My mistake. `pdf2img` isn't a conda package - it's `poppler` that is so it should be:
```python
binaries = conda_support.collect_dynamic_libs("poppler")
```
Doing that gets it working for me.

**Comment by nsage-creatively** [comment]
I still get the same issue.

**Comment by bwoodsend** [comment]
Well can we see what you're doing then?

* Your .spec file.
* The commands you're using to build it and run it.
* A proper minimal example program (with no `#omitted` in it) so we're not have to guess what your code contains.

Can you also determine for each of PyInstaller, poppler and pdf2image which you installed via pip and which you installed via conda?

**Comment by nsage-creatively** [comment]
I just attached a file that has all the relevant information in it. You should be able to run it and see what happens.
[Logo Detection (Minimal).zip](https://github.com/pyinstaller/pyinstaller/files/6870502/Logo.Detection.Minimal.zip)

**Comment by rokm** [comment]
Where did the `pdf2img.pyd` come from? The closest-name python packages, `pdf2image` and `pdf2img` both appear to be pure-python packages (and seem to provide package named `pdf2image`)?

Also, `pdf2image.pyd` seems to be  linked against `pdf2imglib.dll` that's not provided in the above minimal sample. Is this shared library properly collected into your frozen application bundle?

**Comment by nsage-creatively** [comment]
> Where did the pdf2img.pyd come from?
I made it using [this tutorial](https://docs.microsoft.com/en-us/visualstudio/python/working-with-c-cpp-python-in-visual-studio?view=vs-2019). Yeah, it's a little confusing that I named it pdf2img considering there is a library called pdf2image that is doing almost the same thing.
> Is this shared library properly collected into your frozen application bundle?
I don't think so. I do have a `pdf2imglib.dll` that I built from the VS project. I just tried adding it to the folder, but it still doesn't seem to work.

**Comment by rokm** [comment]
> I don't think so. I do have a pdf2imglib.dll that I built from the VS project. I just tried adding it to the Logo Detection (Minimal) folder, but it still doesn't seem to work.

Can you upload the updated version of `Logo Detection (Minimal).zip` that includes the `pdf2imglib.dll` as well? Or if you can check its imports yourself using [Dependency Walker](https://www.dependencywalker.com/)?

**Comment by nsage-creatively** [comment]
[Logo Detection (Minimal).zip](https://github.com/pyinstaller/pyinstaller/files/6874442/Logo.Detection.Minimal.zip)

**Comment by rokm** [comment]
Looks like `pdf2imglib.dll` is linked against `dl180pdfl.dll`, although it is marked as delay-load. Do you have [these libraries](https://dev.datalogics.com/adobe-pdf-library/installing-the-software/required-components-c-and-c-applications/) in your PATH when running the working unfrozen script? They should probably be collected into dist (but I suppose if this is not done automatically, they are not visible to PyInstaller during freezing process).

**Comment by nsage-creatively** [comment]
>They should probably be collected into dist
Okay, I tried this and it worked. This issue can be closed now.
