### ISSUE TITLE
runtime_tmpdir set to drive name causes unexpected behavior

### ISSUE THREAD

**Issue by lolMinsoo** [pyinstaller/pyinstaller#6051]
## Description of the issue
Using the flag runtime_tmpdir and setting it to
`runtime_tmpdir='C:'`
will cause unxpected behaviors. If the executable that is created is ran from the C: drive, the temporary directory created will be in the same path as the executable. However, if the executable that is created is ran from a different drive (i.e. E:), then the temporary folder gets created in `C:\`.
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.2```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Hmm, indeed. 

This behavior stems from `_wfullpath` call here
https://github.com/pyinstaller/pyinstaller/blob/89de31834c2ae8ff616ce67df0fdccb2f9b5b281/bootloader/src/pyi_utils.c#L273
which we use to resolve the given runtime path into absolute one. The [docs for the function](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/fullpath-wfullpath?view=msvc-160) state: `If the relPath argument specifies a disk drive, the current directory of this drive is combined with the path.`

So I suppose we should be skipping that call on drive-letter-only paths. 

Although on the other hand, I think we should catch attempts to set runtime paths with hard-coded drive letters in during build and raise error, because this makes unwarranted assumptions about what drive letters are available on target system...

**Comment by parinavputhran** [comment]
Having used pyinstaller in a lot of my projects, I would like to contribute and solve this issue

**Comment by bwoodsend** [comment]
It's all yours then.

**Comment by parinavputhran** [comment]
Hello, needed some help. If you could tell me where can I find the integration of C++ code with Python. I'm assuming ctypes has been used to do that.
And even while building the package using its setup, I think I might have found some other bugs in the code, perhaps I'll have to create a new issue for that as well.

**Comment by rokm** [comment]
> Hello, needed some help. If you could tell me where can I find the integration of C++ code with Python. I'm assuming ctypes has been used to do that.

The way it works is that the bootloader executable (written in C) sets up an embedded python interpreter and runs the frozen script in it. The sources are in [`bootloader` directory](https://github.com/pyinstaller/pyinstaller/tree/develop/bootloader/src). For this specific issue, you should start looking at the line that I referenced earlier: https://github.com/pyinstaller/pyinstaller/blob/89de31834c2ae8ff616ce67df0fdccb2f9b5b281/bootloader/src/pyi_utils.c#L273
