### ISSUE TITLE
A way to know the location of the original .exe file

### ISSUE THREAD

**Issue by stargateaudio** [pyinstaller/pyinstaller#6058]
Thank you for a great project, it works very well.

I would like a way to know the location of the pyinstaller generated .exe file that spawned the current process.  Perhaps it could set an environment variable when launching the Python interpreter:
```
PYINSTALLER_EXE_PATH=C:\Users\somebody\app.exe
```
The use-case is portable application flash drives that the user can plug into any computer and immediately have access to all of their files and settings.

Users install the exe to a flash drive, and have the application intelligently make decisions to store user files on the flash drive instead of the home folder, if the application was launched from the flash drive.

If the user copies the .exe from the flash drive to their hard drive and launches the app from the hard drive, then the application would store files in the users home folder instead of the flash drive.

**Comment by rokm** [comment]
> I would like a way to know the location of the pyinstaller generated .exe file that spawned the current process.

In a frozen application, `sys.executable` points to the application's executable (instead of python interpreter).

**Comment by stargateaudio** [comment]
Great, thank you!  I will close the issue.
