### ISSUE TITLE
Issues when using PyInstaller with Python 3.8.32 + Tkinter + PAGE GUI generator

### ISSUE THREAD

**Issue by jpldezauzie** [pyinstaller/pyinstaller#6063]
I am a very satisfied user of the "PAGE" solution which allowed me to develop an application intended to simplify the back office of home rental companies. My application works fine in the Python 3.8 interpreter environment but until now I never could generate a working executable using PyInstaller (I also abandoned the Py2Exe and cx_Freeze solutions).

As a matter of fact, when executing the generated stand alone application, the windows are displayed without some of the Frames (eg. In a 5 Frames window which is the basis of a renting operation 2 out of 5 Frames are displayed, and some of the buttons which are displayed are not functioning (in the _support module references to the “w” window are lost and the executable generates an exception and error messages when running). As I stated before, the application is giving complete satisfaction in the interpreter environment (no error and a few warnings due to not used included modules).

The same types of problems exist with “cx_Freeze” solution that I also extensively tested but which I no longer try to use because it is less powerful than PyInstaller.
I am of course at your disposal if you need any more information.

Are you aware of such problems? Is there any kind of way to get around them?

Thank you in advance for your interest, Best Regards,
Jean-Pierre Dezauzié

PS:
-	I tried many “path” variables configuration, without any positive outcome, which made me think that either PAGE or PyInstaller, or both of them are not aware of the other’s prerequisites.
-	Python Version : 3.8.2
-	PAGE version : 6.0.1
-	PyInstaller version : 4.3
-	I attached an example of the warnings issued by PyInstaller.
-	I am using windows 10, build 19042.1110
[warn-GestionRBnB2.txt](https://github.com/pyinstaller/pyinstaller/files/6886991/warn-GestionRBnB2.txt)

**Comment by rokm** [comment]
Can you provide a simple example application that exhibits described issues when frozen?

**Comment by jpldezauzie** [comment]
Dear bwoodsend: the application does not freeze. The "only" problem is that for one wiwdow, 3 out of 5Frames are not displayed, and the buttons, text etc... are not available while everything is working fine with the standard 3.8.32 Python interpreter.
Many thanks in advance for your help.

**Comment by bwoodsend** [comment]
We need to see some code. I have no idea how you created these frames and buttons or how you built your application. To solve your problem we need to know how you got to it in the first place.
