### ISSUE TITLE
Option of using a bin folder for Support Files in Single Folder Build

### ISSUE THREAD

**Issue by KarthikAbiram** [pyinstaller/pyinstaller#6075]
I would like to start by thanking the pyinstaller dev community for creating this nice tool :)

**Is your feature request related to a problem? Please describe.**
A typical Windows application has a EXE in the root folder and supporting files are usually not placed parallel to the EXE. I am aware of the single file build option in pyinstaller - but it takes some time for it to launch (since it needs to extract the contents to temp folder). In the past I have also run into issues where the single file EXE was getting flagged by antivirus.

**Describe the solution you'd like**
So, what I was thinking was, in the single folder build, wouldn't it be cool if it was possible to have all the support files and DLLs be put into a folder like bin parallel to the EXE? In this way the installation directory looks cleaner and there is no overhead of extracting files to temp directory.

**Describe alternatives you've considered**
Like mentioned earlier, the single file EXE is the alternative but it has some disadvantages - load up time is more and random flagging by antivirus.

**Comment by eric15342335** [comment]
#5575

**Comment by KarthikAbiram** [comment]
@eric15342335. Will close this as duplicate and continue discussion there. Thanks!
