### ISSUE TITLE
I have the same problem as https://github.com/pyinstaller/pyinstaller/issues/5438

### ISSUE THREAD

**Issue by liaoxuewei** [pyinstaller/pyinstaller#6078]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.4```
* Version of Python: 3.8
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?

```
Python path configuration:
  PYTHONHOME = (not set)
  PYTHONPATH = (not set)
  program name = 'python'
  isolated = 0
  environment = 1
  user site = 1
  import site = 1
  sys._base_executable = 'C:\\Tools\\easytrader01.exe'
  sys.base_prefix = ''
  sys.base_exec_prefix = ''
  sys.executable = 'C:\\Tools\\easytrader01.exe'
  sys.prefix = ''
  sys.exec_prefix = ''
  sys.path = [
    'C:\\Tools\\Python38.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\Tools',
  ]
Fatal Python error: init_fs_encoding: failed to get the Python codec of the file
system encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'

Current thread 0x00001870 (most recent call first):
<no Python frame>
```

But I don't had typing install in python. How should I deal with this problem? thanks!

**Comment by liaoxuewei** [comment]
Using --log-level DEBUG to run pyinstaller. No error messages appear, and the encodings information is listed

**Comment by bwoodsend** [comment]
What do you get if you run:
```python
from PyInstaller.utils.hooks import collect_submodules
print(collect_submodules('encodings'))
```

**Comment by bwoodsend** [comment]
And what are your build and run commands you're typing into the terminal?

**Comment by bwoodsend** [comment]
And does this happen with a simple program like `print("hello")`?

**Comment by liaoxuewei** [comment]
Sorry, I've been busy lately. I didn't notice it.

> What do you get if you run:
> 
> ```python
> from PyInstaller.utils.hooks import collect_submodules
> print(collect_submodules('encodings'))
> ```

encodings info:
['encodings.iso2022_jp_2', 'encodings.big5hkscs', 'encodings.mac_romanian', 'encodings.cp874', 'encodings.raw_unicode_escape', 'encodings.cp949', 'encodings.mac_roman', 'encodings.cp932', 'encodings.utf_32_be', 'encodings.cp1006', 'encodings.punycode', 'encodings.utf_8_sig', 'encodings.mac_centeuro', 'encodings.cp1026', 'encodings.gb18030', 'encodings.cp720', 'encodings.palmos', 'encodings.shift_jis_2004', 'encodings.iso8859_13', 'encodings.cp869', 'encodings.cp1254', 'encodings.cp65001', 'encodings.cp850', 'encodings.uu_codec', 'encodings.shift_jis', 'encodings.cp866', 'encodings.euc_jp', 'encodings.cp1251', 'encodings.iso8859_6', 'encodings.mac_croatian', 'encodings.iso2022_jp_1', 'encodings.iso2022_jp_2004', 'encodings.cp863', 'encodings.cp775', 'encodings.cp856', 'encodings.utf_16', 'encodings.zlib_codec', 'encodings.iso8859_1', 'encodings.tis_620', 'encodings.cp865', 'encodings.cp875', 'encodings.rot_13', 'encodings.gb2312', 'encodings.ptcp154', 'encodings.cp1253', 'encodings', 'encodings.iso2022_jp_3', 'encodings.iso8859_10', 'encodings.idna', 'encodings.mbcs', 'encodings.mac_iceland', 'encodings.euc_kr', 'encodings.iso8859_7', 'encodings.charmap', 'encodings.iso8859_11', 'encodings.undefined', 'encodings.kz1048', 'encodings.cp857', 'encodings.cp858',
'encodings.iso8859_14', 'encodings.cp1257', 'encodings.iso2022_jp_ext', 'encodings.cp1140', 'encodings.cp852', 'encodings.iso8859_16', 'encodings.iso2022_jp', 'encodings.iso8859_9', 'encodings.euc_jis_2004', 'encodings.cp861', 'encodings.iso8859_15', 'encodings.cp500', 'encodings.iso8859_2', 'encodings.iso8859_5', 'encodings.utf_7', 'encodings.cp437', 'encodings.mac_arabic', 'encodings.utf_16_le', 'encodings.cp1250', 'encodings.cp1252', 'encodings.cp737', 'encodings.cp424', 'encodings.cp855', 'encodings.cp950', 'encodings.utf_32_le', 'encodings.cp1255', 'encodings.cp273', 'encodings.cp037', 'encodings.big5', 'encodings.johab', 'encodings.koi8_t', 'encodings.mac_farsi', 'encodings.oem', 'encodings.hex_codec', 'encodings.cp1125', 'encodings.quopri_codec', 'encodings.ascii', 'encodings.mac_turkish', 'encodings.utf_32', 'encodings.unicode_escape', 'encodings.bz2_codec', 'encodings.iso2022_kr', 'encodings.latin_1', 'encodings.base64_codec', 'encodings.mac_cyrillic', 'encodings.iso8859_8', 'encodings.cp1258', 'encodings.mac_greek', 'encodings.mac_latin2', 'encodings.aliases', 'encodings.iso8859_4', 'encodings.utf_16_be', 'encodings.cp864', 'encodings.iso8859_3', 'encodings.hp_roman8', 'encodings.utf_8', 'encodings.koi8_r', 'encodings.gbk', 'encodings.shift_jisx0213', 'encodings.unicode_internal', 'encodings.hz', 'encodings.euc_jisx0213', 'encodings.cp1256', 'encodings.koi8_u', 'encodings.cp860', 'encodings.cp862']

**Comment by liaoxuewei** [comment]
> And what are your build and run commands you're typing into the terminal?

First, I use pyinstaller -F xxxx.py to generate exe and xxxx.spec.
and then use pyinstaller -F xxxx.spec to build next time.

**Comment by liaoxuewei** [comment]
> And does this happen with a simple program like `print("hello")`? If not then you need to provide an example program.

I will try to do it later.

**Comment by liaoxuewei** [comment]
I wonder why the way to generate folders is completely normal, but a single file is not normal? Is it possible to convert a file into a folder and then into a single file?

**Comment by liaoxuewei** [comment]
> Sorry, I've been busy lately. I didn't notice it.
> 
> > What do you get if you run:
> > ```python
> > from PyInstaller.utils.hooks import collect_submodules
> > print(collect_submodules('encodings'))
> > ```
> 
> encodings info:
> ['encodings.iso2022_jp_2', 'encodings.big5hkscs', 'encodings.mac_romanian', 'encodings.cp874', 'encodings.raw_unicode_escape', 'encodings.cp949', 'encodings.mac_roman', 'encodings.cp932', 'encodings.utf_32_be', 'encodings.cp1006', 'encodings.punycode', 'encodings.utf_8_sig', 'encodings.mac_centeuro', 'encodings.cp1026', 'encodings.gb18030', 'encodings.cp720', 'encodings.palmos', 'encodings.shift_jis_2004', 'encodings.iso8859_13', 'encodings.cp869', 'encodings.cp1254', 'encodings.cp65001', 'encodings.cp850', 'encodings.uu_codec', 'encodings.shift_jis', 'encodings.cp866', 'encodings.euc_jp', 'encodings.cp1251', 'encodings.iso8859_6', 'encodings.mac_croatian', 'encodings.iso2022_jp_1', 'encodings.iso2022_jp_2004', 'encodings.cp863', 'encodings.cp775', 'encodings.cp856', 'encodings.utf_16', 'encodings.zlib_codec', 'encodings.iso8859_1', 'encodings.tis_620', 'encodings.cp865', 'encodings.cp875', 'encodings.rot_13', 'encodings.gb2312', 'encodings.ptcp154', 'encodings.cp1253', 'encodings', 'encodings.iso2022_jp_3', 'encodings.iso8859_10', 'encodings.idna', 'encodings.mbcs', 'encodings.mac_iceland', 'encodings.euc_kr', 'encodings.iso8859_7', 'encodings.charmap', 'encodings.iso8859_11', 'encodings.undefined', 'encodings.kz1048', 'encodings.cp857', 'encodings.cp858',
> 'encodings.iso8859_14', 'encodings.cp1257', 'encodings.iso2022_jp_ext', 'encodings.cp1140', 'encodings.cp852', 'encodings.iso8859_16', 'encodings.iso2022_jp', 'encodings.iso8859_9', 'encodings.euc_jis_2004', 'encodings.cp861', 'encodings.iso8859_15', 'encodings.cp500', 'encodings.iso8859_2', 'encodings.iso8859_5', 'encodings.utf_7', 'encodings.cp437', 'encodings.mac_arabic', 'encodings.utf_16_le', 'encodings.cp1250', 'encodings.cp1252', 'encodings.cp737', 'encodings.cp424', 'encodings.cp855', 'encodings.cp950', 'encodings.utf_32_le', 'encodings.cp1255', 'encodings.cp273', 'encodings.cp037', 'encodings.big5', 'encodings.johab', 'encodings.koi8_t', 'encodings.mac_farsi', 'encodings.oem', 'encodings.hex_codec', 'encodings.cp1125', 'encodings.quopri_codec', 'encodings.ascii', 'encodings.mac_turkish', 'encodings.utf_32', 'encodings.unicode_escape', 'encodings.bz2_codec', 'encodings.iso2022_kr', 'encodings.latin_1', 'encodings.base64_codec', 'encodings.mac_cyrillic', 'encodings.iso8859_8', 'encodings.cp1258', 'encodings.mac_greek', 'encodings.mac_latin2', 'encodings.aliases', 'encodings.iso8859_4', 'encodings.utf_16_be', 'encodings.cp864', 'encodings.iso8859_3', 'encodings.hp_roman8', 'encodings.utf_8', 'encodings.koi8_r', 'encodings.gbk', 'encodings.shift_jisx0213', 'encodings.unicode_internal', 'encodings.hz', 'encodings.euc_jisx0213', 'encodings.cp1256', 'encodings.koi8_u', 'encodings.cp860', 'encodings.cp862']

Sorry, I don't think this is accurate because the problem is the environment of another computer.

**Comment by bwoodsend** [comment]
> > And what are your build and run commands you're typing into the terminal?
> 
> First, I use pyinstaller -F xxxx.py to generate exe and xxxx.spec.
> and then use pyinstaller -F xxxx.spec to build next time.

And what do you use to run the executable after building it?

**Comment by liaoxuewei** [comment]
> > > And what are your build and run commands you're typing into the terminal?
> > 
> > 
> > First, I use pyinstaller -F xxxx.py to generate exe and xxxx.spec.
> > and then use pyinstaller -F xxxx.spec to build next time.
> 
> And what do you use to run the executable after building it?

I don't quite understand the meaning of this question. Do you mean under what operating system to run executable?

**Comment by bwoodsend** [comment]
No, just the command you type. Do you run `dist/xxx.exe` or `build/xxx.exe`? The 1st is correct, the second is wrong and leads  to the encodings modules not being found.

**Comment by liaoxuewei** [comment]
> No, just the command you type. Do you run `dist/xxx.exe` or `build/xxx.exe`? The 1st is correct, the second is wrong and leads to the encodings modules not being found.

Yes, I used 1st to run.
Now, I had found out which package cause problem. What should I do?

pip install easytrader #-i https://pypi.tuna.tsinghua.edu.cn/simple/

```
import easytrader

def main():
    print("初始化1")
    user = easytrader.use('ths')
    print("初始化2")

if __name__ == '__main__':
    main()

```

**Comment by rokm** [comment]
The above `easytrader` works for me, using python 3.8.7 and pyinstaller 4.4. Can we see the output of `pip freeze` for the environment you use?

**Comment by liaoxuewei** [comment]
pip freeze output is:

```
altgraph==0.17
anytree==2.8.0
astroid==2.4.2
autopep8==1.5.6
beautifulsoup4==4.9.3
bs4==0.0.1
certifi==2020.12.5
chardet==4.0.0
click==7.1.2
colorama==0.4.4
comtypes==1.1.8
cssselect==1.1.0
cycler==0.10.0
demjson==2.2.4
easyquotation==0.7.4
easytrader==0.23.0
easyutils==0.1.7
et-xmlfile==1.0.1
Flask==1.1.2
future==0.18.2
gopup==0.3.0
idna==2.10
isort==5.7.0
itsdangerous==1.1.0
jdcal==1.4.1
Jinja2==2.11.2
joblib==0.16.0
jsonpath==0.82
kiwisolver==1.3.1
lazy-object-proxy==1.4.3
loguru==0.5.3
lxml==4.6.2
MarkupSafe==1.1.1
matplotlib==3.3.3
mccabe==0.6.1
mysql-connector==2.2.9
numpy==1.19.0
openpyxl==3.0.4
pandas==1.0.5
patsy==0.5.1
pefile==2021.5.24
Pillow==8.1.0
py4j==0.10.9
pycodestyle==2.7.0
PyExecJS==1.5.1
pyinstaller @ https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz
pyinstaller-hooks-contrib==2021.2
pylint==2.6.0
PyMySQL==0.9.3
pyparsing==2.4.7
pypiwin32==223
pyquery==1.4.3
pytesseract==0.3.7
python-dateutil==2.8.1
pytz==2020.1
pywin32==300
pywin32-ctypes==0.2.0
pywinauto==0.6.6
PyYAML==5.4.1
requests==2.25.1
scikit-learn==0.23.1
scipy==1.5.1
selenium==3.141.0
simplejson==3.17.2
six==1.15.0
soupsieve==2.1
SQLAlchemy==1.3.18
statsmodels==0.11.1
threadpoolctl==2.1.0
toml==0.10.2
treelib==1.6.1
tushare==1.2.62
urllib3==1.26.2
websocket-client==0.57.0
Werkzeug==1.0.1
win32-setctime==1.0.3
wrapt==1.12.1
xlrd==1.2.0
XlsxWriter==1.3.7
xlwt==1.3.0
yapf==0.31.0

```

**Comment by liaoxuewei** [comment]
My Python version is 3.8.3

**Comment by rokm** [comment]
Alright, so I tried to reproduce the problem in a clean environment with the above list. And it did not work in either source or frozen form, until I updates `comtypes` to the latest version (it kept complaining about `'UIAutomationCore.dll'` missing). But afterwards, the frozen program works as expected.

---

But looking back at your original report, you have an executable names `C:\\Tools\\easytrader01.exe`. Is this a `onedir` or a `onefile` build? What else is in the `C:\\Tools\\` directory? 

The displayed `sys.path` also does not match the search paths that should be set by PyInstaller:

```
sys.path = [
    'C:\\Tools\\Python38.zip',
    '.\\DLLs',
    '.\\lib',
    'C:\\Tools',
  ]
```

Instead, they look like something that python or embeddable python might use...

---

>How you installed Python: python.org/downloads

Are you using python installer or embeddable python from python.org?

Can you provide exact step by step description of what you are doing, including:
* the PyInstaller command you are running to build the program
* the build lok (with --log-level DEBUG)
* the command you use to run the built program
* full program's output

**Comment by liaoxuewei** [comment]
> Alright, so I tried to reproduce the problem in a clean environment with the above list. And it did not work in either source or frozen form, until I updates `comtypes` to the latest version (it kept complaining about `'UIAutomationCore.dll'` missing). But afterwards, the frozen program works as expected.
> 
> But looking back at your original report, you have an executable names `C:\\Tools\\easytrader01.exe`. Is this a `onedir` or a `onefile` build? What else is in the `C:\\Tools\\` directory?
> 
> The displayed `sys.path` also does not match the search paths that should be set by PyInstaller:
> 
> ```
> sys.path = [
>     'C:\\Tools\\Python38.zip',
>     '.\\DLLs',
>     '.\\lib',
>     'C:\\Tools',
>   ]
> ```
> 
> Instead, they look like something that python or embeddable python might use...
> 
> > How you installed Python: python.org/downloads
> 
> Are you using python installer or embeddable python from python.org?
> 
> Can you provide exact step by step description of what you are doing, including:
> 
> * the PyInstaller command you are running to build the program
> * the build lok (with --log-level DEBUG)
> * the command you use to run the built program
> * full program's output
C:\\Tools\\easytrader01.exe is the onefile build copied from the package the EXE environment. There are some other files in C:\\Tools\\, but other files should not d have an impact, right?

`How you installed Python: python.org/downloads`
Are you talking about the environment for packaging exe or the environment for running exe?
The running exe environment does not have Python installed.
Package the EXE environment, the python is installed by python installer.

`Can you provide exact step by step description of what you are doing, including:`
I need to try later. The computer is not around me now.

**Comment by bwoodsend** [comment]
I'll reopen this if you get back to us.
