### ISSUE TITLE
Latest pyinstaller (4.5.0) version breaks 3rd party lib hooks running

### ISSUE THREAD

**Issue by ankith26** [pyinstaller/pyinstaller#6079]
I am a contributor to pygame, and we maintain our own 3rd party pyinstaller hook in the repo. With the latest 4.5.0 version released a few hours ago, I noticed that pyinstaller generated exes that use pygame crash, complaining about missing DLLs that pygame needs, and with older pyinstaller versions (version 4.0 to 4.4), pyinstaller would load the pygame hook, which in turn, would load all the DLLs and other assets that pygame needs along with the pyinstaller generated exe. With 4.5, it does not run the hook at all, hence, missing data files

### Context information

* Output of `pyinstaller --version`: `4.5`
* Version of Python: `3.9.6`
* Platform: Windows
* How you installed Python: Windows 64-bit installer from python.org
* Did you also try this on another platform? Does it work there? Not tested on other OSes

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Steps to reproduce
- Install pygame with `py -m pip install pygame`
- Put the following minimal reproducer code in a `main.py` file, make an `assets` dir in the same folder, and put a sound file in the assets folder by the name of `blop.ogg` (I cannot attach the sound file because github does not allow me, but any `.ogg` music file can be used to reproduce this issue)
```py
"""
Simple pygame example that loads a sound from ogg file, playes it, and closes.

Demonstates a bug in pyinstaller 4.5
"""

import pygame
import os

pygame.init()

pygame.mixer.music.load(os.path.join("assets", "blop.ogg"))
pygame.mixer.music.play()

pygame.time.delay(500)
pygame.quit()
```
- Verify that simply running this program directly works, and a blop sound is heard
- Install pyinstaller `py -m pip install pyinstaller`
- Make dist with command `pyinstaller --add-data "assets;assets" main.py`
The first few lines of this output is 
```
D:\pyinst>pyinstaller --add-data "assets;assets" main.py
83 INFO: PyInstaller: 4.5
83 INFO: Python: 3.9.6
93 INFO: Platform: Windows-10-10.0.19043-SP0
97 INFO: wrote D:\pyinst\main.spec
101 INFO: UPX is not available.
108 INFO: Extending PYTHONPATH with paths
['D:\\pyinst', 'D:\\pyinst']
373 INFO: checking Analysis
373 INFO: Building Analysis because Analysis-00.toc is non existent
373 INFO: Initializing module dependency graph...
377 INFO: Caching module graph hooks...
382 INFO: Analyzing base_library.zip ...

[Build was successful, extra lines of output skipped]

D:\pyinst>cd dist\\main

D:\pyinst\dist\main>.\\main.exe
pygame 2.0.2.dev1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 12, in <module>
pygame.error: Failed loading libvorbisfile-3.dll: The specified module could not be found.

[8060] Failed to execute script 'main' due to unhandled exception!

D:\pyinst\dist\main>
```
- See the crash is due to a missing DLL, which the pygame hook would have otherwise bundled

- In older pyinstaller versions (v4.4), the output is
```
D:\pyinst>pyinstaller --add-data "assets;assets" main.py
82 INFO: PyInstaller: 4.4
83 INFO: Python: 3.9.6
92 INFO: Platform: Windows-10-10.0.19043-SP0
93 INFO: wrote D:\pyinst\main.spec
95 INFO: UPX is not available.
98 INFO: Extending PYTHONPATH with paths
['D:\\pyinst', 'D:\\pyinst']
pygame 2.0.2.dev1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html
150 INFO: checking Analysis
165 INFO: Building because hookspath changed
165 INFO: Initializing module dependency graph...
169 INFO: Caching module graph hooks...
185 INFO: Analyzing base_library.zip ...

[Build was successful, extra lines of output skipped]

D:\pyinst>cd dist\\main

D:\pyinst\dist\main>.\\main.exe
pygame 2.0.2.dev1 (SDL 2.0.14, Python 3.9.6)
Hello from the pygame community. https://www.pygame.org/contribute.html

D:\pyinst\dist\main>
```

Notice how in the buildlog, the pygame welcome message appears, which means that the pygame hook was loaded correctly in this case.

**Comment by ankith26** [comment]
I am not so sure, but if I were to guess, this is probably a regression introduced after #6032

**Comment by ankith26** [comment]
Okay I identified the bug, and opened a PR to fix it. It turns out, the bug was because path to my python installation had a space in it somewhere, and the hook loader code did not handle that well

**Comment by andrewd18** [comment]
Ran into this on one of my projects; confirming the patch in #6080 resolves my issue. I'm having my other devs hotfix the issue in their venvs but I'd appreciate a pypi release with this (or equivalent patch) in it when you get the chance. :)  Thanks!

**Comment by bwoodsend** [comment]
@Legorooj Given that we don't need to recompile the bootloaders for this, a patch release should just a case of running towncrier, setting the version, then launching the release workflow?

**Comment by Legorooj** [comment]
Yep, I can do a 4.5.1 release today. It's a little more complex than that, but not overly so.

**Comment by ankith26** [comment]
So what's the status with this issue now? I see that my PR to the v4 branch has now somehow been reverted (IDK whether this was accidental or intentional) and a v4.5.1 has not come yet, no hurries on this, but I would rather like to have a 4.5.1 with quickfixes rather than having to wait a long time for v5

**Comment by bwoodsend** [comment]
v4.5.1 is coming in a few days. But you're correct in that your changes appear to have been force-pushed into a black hole. @Legorooj What have you done???

**Comment by Legorooj** [comment]
Oops...

**Comment by Legorooj** [comment]
Fixed it 😄. Will do the release today.

**Comment by Legorooj** [comment]
Released.
