### ISSUE TITLE
Support for creating thin arm64 bootloader

### ISSUE THREAD

**Issue by cho-m** [pyinstaller/pyinstaller#6091]
**Is your feature request related to a problem? Please describe.**
Homebrew formulae expect native binaries rather than universal. The `pyinstaller` formula is installed into single-arch Homebrew Python, so it doesn't seem universal is necessary here.

**Describe the solution you'd like**
An option/flag to create thin arm64 bootloader for macOS. Either modifying `--no-universal2` to check running arch, or use a new option/flag.

**Describe alternatives you've considered**
In https://github.com/Homebrew/homebrew-core/pull/81847, Homebrew formula will end up modifying/patching the `wscript` to do this, probably by changing the else-block for `--no-universal2`. It would be better to avoid having to work around this though.

**Additional context**
Homebrew PR link has some other info.

**Comment by bwoodsend** [comment]
I don't understand. [There's a `--no-universal2` flag already](https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html#building-for-mac-os-x) - why isn't that one enough?

**Comment by bwoodsend** [comment]
Either way, I'd be happy to add this functionality.

**Comment by rokm** [comment]
> @rokm Is this intentional?

Yes, if universal2 is not available, we intentionally fall back to old behavior (forced x86_64-only). 

If available, the idea is to always build universal2 bootloader, and thin it out to single-arch during the freezing process.

**Comment by rokm** [comment]
But as the assembly pipeline works with either universal2 or single-arch bootloaders, I don't see a problem with changing the fixed arch in else branch to `platform.machine()` (or equivalent manual `x86_64`/`arm64` switch), as suggested in linked homebrew PR. The reason why I haven't done so is that I did not see a reason why single-arch arm64 bootloader would be preferable to universal2 one, given the way our assembly pipeline works...

**Comment by bwoodsend** [comment]
To me, the most logical behaviour would be for `--no-universal2` to not explicitly set `-arch` at all. That way you could build a native binary with:
```
./waf --no-universal2 all
```
Or build a specific architecture with the usuall `CC` override:
```
CC='clang -arch x86_64' ./waf all
CC='clang -arch arm64' ./waf all
```

**Comment by rokm** [comment]
> To me, the most logical behaviour would be for `--no-universal2` to not explicitly set `-arch` at all. That way you could build a native binary with:
> 
> ```
> ./waf --no-universal2 all
> ```
> 
> Or build a specific architecture with the usuall `CC` override:
> 
> ```
> CC='clang -arch x86_64' ./waf --no-universal2 all
> CC='clang -arch arm64' ./waf --no-universal2 all
> ```

Yeah, that's an even better approach, as it allows cross-compiling for arm64 on a x86_64 host, which would otherwise be impossible due to our --target-arch allowing only "32bit" and "64bit"...

I suppose we can also drop the 32-bit arch override, then, and set CFLAGS and LINKFLAGS only if building universal2 bootloaders (and nuke the CXXFLAGS setting, as we don't have any c++ code).
