### ISSUE TITLE
can't find cacert.pem

### ISSUE THREAD

**Issue by elieobeid7** [pyinstaller/pyinstaller#6099]
I got many errors. To reproduce, install[ Firestore python library](https://firebase.google.com/docs/firestore/quickstart).

Try to call some function and do some call, then try packaging it.

![Capture](https://user-images.githubusercontent.com/660142/128637591-e5e1cd0c-4964-4cd4-8180-2b72f928822e.PNG)

**Comment by rokm** [comment]
Does the error also occur if you package the following script?
```python
import certifi
print(certifi.where())
```

What is the output if you run this script directly in python interpreter, without packaging it? 

Also, what version of python and PyInstaller are you using?
