### ISSUE TITLE
Windows with GTK Built with gvsbuild Causes WinError on App Launch

### ISSUE THREAD

**Issue by danyeaw** [pyinstaller/pyinstaller#6100]
## Description of the issue

Launching a GTK app by double-clicking is causing a `OSError: [WinError 87] The parameter is incorrect: ''` error show in the GUI window that pops up.

GTK is built from [gvsbuild](https://github.com/wingtk/gvsbuild) using MSVC instead of MINGW / GCC.

It works fine to run it from the console. It also works fine to run it as an administrator.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: 3.9.6
* Platform: Windows 10-10.0.22000-SP0
* How you installed Python: python.org/download
* Did you also try this on another platform? Does it work there? No

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
pyinstaller --noconsole --noupx --debug=all helloworld.py

import gi
gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

window = Gtk.Window(title="Hello World")
window.show()
window.connect("destroy", Gtk.main_quit)
Gtk.main()
```

### Stacktrace / full error message

```
Unhandled exception in script
Failed to execute script 'helloworld' due to unhandled except: [WinError 87] The parameter is incorrect: "
Traceback (most recent call last):
  File "helloworld.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "c:\users\dan\projects\test-gtk\.venv\lib\site-packages\gi\__init__.py", line 45, in <module>
    added_dirs.append(os.add_dll_directory(p))
  File "C:\Users\dan\.pyenv\pyenv-win\versions\3.9.6\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 87] The parameter is incorrect: ''
```

In `gi\__init__.py`, just before line 45:
```
from . import _gi
from ._gi import _API
from ._gi import Repository
from ._gi import PyGIDeprecationWarning
from ._gi import PyGIWarning
```

I would be glad to submit a PR to help fix this if I could get some assistance on troubleshooting, I'm out of ideas at this point.

**Comment by rokm** [comment]
This looks like `os.add_dll_directory()` is being called with an invalid path? (Could be mismatch in separators or something along those lines...)

Maybe you can hack `c:\users\dan\projects\test-gtk\.venv\lib\site-packages\gi\__init__.py` to print the path it is trying to pass to the call?

**Comment by rokm** [comment]
Actually, `p` is probably an empty string, hence the error:

```
>>> os.add_dll_directory('')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]\Python38\lib\os.py", line 1109, in add_dll_directory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 87] The parameter is incorrect: ''
```

**Comment by danyeaw** [comment]
@rokm Thanks for the troubleshooting hints!

I modified the `gi\__init__.py` file to print p. When I run `python -c "import gi"`, it prints: C:\gtk-build\gtk\x64\release\bin. Which isn't a valid path, since the `\` should be `/`. For example, `pathlib.Path("C:\gtk-build\gtk\x64\release\bin").is_dir()` returns false, while `pathlib.Path("C:/gtk-build/gtk/x64/release/bin").is_dir()` returns true.

Maybe this is an issue with the paths returned by the gi hook, because it was only tested with MINGW on Windows?

**Comment by rokm** [comment]
> I modified the `gi\__init__.py` file to print p. When I run `python -c "import gi"`, it prints: C:\gtk-build\gtk\x64\release\bin. 

The question is, what does it return when the program fails (I think it is empty, but perhaps you can figure out how it arrives at being empty?).

> Which isn't a valid path, since the `\` should be `/`. For example, `pathlib.Path("C:\gtk-build\gtk\x64\release\bin").is_dir()` returns false, while `pathlib.Path("C:/gtk-build/gtk/x64/release/bin").is_dir()` returns true.

I don't think that's the case - `\` should be a valid separator on Windows, especially if no mingw is involved. Path literals are a bit tricky, though - do  `pathlib.Path("C:\\gtk-build\\gtk\\x64\\release\\bin").is_dir()` and `pathlib.Path(r"C:\gtk-build\gtk\x64\release\bin").is_dir()` work as expected?

> Maybe this is an issue with the paths returned by the gi hook, because it was only tested with MINGW on Windows?

I think I'll need to set up the test environment and check what's going on...

**Comment by danyeaw** [comment]
>I don't think that's the case - \ should be a valid separator on Windows, especially if no mingw is involved. Path literals are a bit tricky, though - do pathlib.Path("C:\\gtk-build\\gtk\\x64\\release\\bin").is_dir() and pathlib.Path(r"C:\gtk-build\gtk\x64\release\bin").is_dir() work as expected?

Yup, those work.

I think we would be getting a different error if the path wasn't formed correctly:

```
>>> os.add_dll_directory("C:\gtk-build\gtk\x64\release\bin")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\dan\.pyenv\pyenv-win\versions\3.9.6\lib\os.py", line 1111, in add_dll_directory
    cookie = nt._add_dll_directory(path)
OSError: [WinError 123] The filename, directory name, or volume label syntax is incorrect: 'C:\\gtk-build\\gtkd\release\x08in'
```

**Comment by rokm** [comment]
Alright, I've managed to get Gtk3 & PyGObject built... and the built test program seems to work, regardless of how it is started. 

However, observing the problematic block of code in `gi.__init__`:

```python
added_dirs = []
if os.name == 'nt' and hasattr(os, 'add_dll_directory'):
    path = os.environ.get('PATH', '')
    for p in path.split(os.pathsep):
        if os.path.isfile(os.path.join(p, 'girepository-1.0-1.dll')):
            # Found a repository dll -> add to the list
            added_dirs.append(os.add_dll_directory(p))
```

we can see that the only way `add_dll_directory` to be called with an empty path (`p=''`) is if `os.path.isfile(os.path.join(p,  'girepository-1.0-1.dll'))`  evaluates to `True`. That happens only when the DLL is located in current working directory, which is in fact true when you run the program by double-clicking on it (but it should be the same if you `cd` into `dist\program` and run `program` from there).

And I think the only way for empty path to be even considered as a candidate is if `PATH` environment variable contains an "empty" entry, i.e., empty string between two semi-colons (or prepended empty string + semi-colon).

So if I do:
```
set PATH=;%PATH%
```
and try to run `program` from `dist\program`, I get the same `OSError: [WinError 87] The parameter is incorrect: ''` error. But running from anywhere else is fine.

Can you check your `PATH` and see if there are any empty entries in it?

**Comment by danyeaw** [comment]
Hi @rokm, thanks again for your help with this! It is also very impressive that you got a gvsbuild of GTK going that quickly.

Here is my path:
```
PS C:\Users\dan> $env:Path
C:\Program Files\WindowsApps\Microsoft.PowerShell_7.1.3.0_x64__8wekyb3d8bbwe;C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Meson\;C:\Users\dan\AppData\Local\Microsoft\WindowsApps;C:\gtk-build\gtk\x64\release\bin;C:\Users\dan\AppData\Local\Microsoft\WindowsApps;c:\users\dan\appdata\roaming\python\python39\scripts;c:\users\dan\.local\bin
```
I don't think there are any empty strings in it.

- I compared in to the path of the admin account and I don't see any glaring differences that would cause this issue (it launches fine when run as an admin)
- I can `cd dist\helloworld` and `.\helloworld.exe` and it runs fine with no errors
- I tried to also remove `C:\gtk-build\..` from my path
- I also am getting the same error when I build [Gaphor on CI](https://github.com/gaphor/gaphor/pull/912), so I don't suspect it is a local configuration problem.

That is interesting that you are able to get it to work on your computer. How did you build and setup gvsbuild? The steps I took are [posted](https://gaphor.readthedocs.io/en/latest/windows.html).

I also installed DebugView and tried to see if it displayed any further information on the traceback. However, I am just getting the LOADER messages:

```
[27100] [27100] LOADER: Running pyiboot01_bootstrap.py
[27100] [27100] LOADER: Running pyi_rth_pkgutil.py
[27100] [27100] LOADER: Running pyi_rth_multiprocessing.py
[27100] [27100] LOADER: Running pyi_rth_inspect.py
[27100] [27100] LOADER: Running pyi_rth_gtk.py
[27100] [27100] LOADER: Running pyi_rth_glib.py
[27100] [27100] LOADER: Running pyi_rth_gdkpixbuf.py
[27100] [27100] LOADER: Running pyi_rth_gio.py
[27100] [27100] LOADER: Running pyi_rth_gi.py
[27100] [27100] LOADER: Running helloworld.py
```

**Comment by rokm** [comment]
I set up `gvsbuild` in a clean Win 10 VM, using CI steps from the linked `gaphor` PR as a reference (so in essence, it is the same as your instructions, except that VS2019, msys2 and python 3.9 were installed manually, without chocolatey). But given the current evidence, I don't think this is a build-related problem, but rather runtime/environment one.

In another clean Win 10 VM, both the frozen test program and the portable gaphor build (the artifact from the CI) fail when ran from sys._MEIPASS, because the `PATH` on the system contains a trailing semi-colon. Removing that allows me to run gaphor build by double-clicking on the exe.

I think the best way to debug this further is if you modify your local `gi\__init__.py ` and add an `assert(p)` before the
`added_dirs.append(os.add_dll_directory(p))`, and dump os.environ.get('PATH', '') into exception message. Then rebuild the
`helloworld` and try to run it again. This way, you'll see the `PATH` as seen by the `gi` module (and the frozen application) - considering the problematic code, I'd be quite suprised if there was not an empty part in it somewhere (why would there be is a different question, though, as the path printed from PS looks alright... does PS support bash-like profiles, and could that result in a different `PATH`?)

**Comment by danyeaw** [comment]
@rokm Thanks again!

I think you are on the right track. I did install a packaged version of Gaphor on a different Windows laptop, and it runs fine there. Unfortunately, it doesn't work to print or assert the path, because it causes an error when one of the gi hooks is running during the pyinstaller freeze.

I did modify the `gi\__init__.py` file to add a guard against an empty path:

```
        if p != "" and os.path.isfile(os.path.join(p, 'girepository-1.0-1.dll')):
            # Found a repository dll -> add to the list
            added_dirs.append(os.add_dll_directory(p))
```

This works fine, so there is an empty path coming from somewhere. I tried with normal CMD, and I get the same error, so it isn't related to PS directly.

**Comment by rokm** [comment]
> because it causes an error when one of the gi hooks is running during the pyinstaller freeze.

Printing message to `sys.stderr` instead of default `sys.stdout` should take care of those errors:
```python
print('...', file=sys.stderr) 
```
(the hooks are trying to parse sys.stdout, so extra output throws them off. Hopefully we'll get rid of that once #6052 is merged).

Although I find it odd that assert would trigger during freeze, unless you are freezing from a directory that contains `girepository-1.0-1.dll`...

> I did modify the `gi\__init__.py` file to add a guard against an empty path:

Yes, that is ultimately the fix for this issue (or alternatively, `p` should be resolved with `os.path.normpath` so that it is always absolute), which will need to be applied on the `gi` side. Empty PATH segments appear to be legal, so the code needs to account for possibility of `p` being empty.

**Comment by danyeaw** [comment]
I ended up getting an output by checking whether in the frozen app to prevent interfering with the hooks and then raising an exception:

```
if os.name == 'nt' and hasattr(os, 'add_dll_directory'):
    path = os.environ.get('PATH', '')
    if getattr(sys, 'frozen', False) and hasattr(sys, '_MEIPASS'):
        raise Exception(str(path))
    for p in path.split(os.pathsep):
        if os.path.isfile(os.path.join(p, 'girepository-1.0-1.dll')):
            # Found a repository dll -> add to the list
            added_dirs.append(os.add_dll_directory(p))
```

Which gives the following traceback when double clicking on the frozen exe:

```
Traceback (most recent call last):
  File "helloworld.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "gi\__init__.py", line 43, in <module>
Exception: C:\Python39\Scripts\;C:\Python39\;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Program Files\Microsoft VS Code\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Program Files\Meson\;C:\Users\dan\AppData\Local\Microsoft\WindowsApps;C:\Users\dan\AppData\Local\Microsoft\WindowsApps;c:\users\dan\appdata\roaming\python\python39\scripts;c:\users\dan\.local\bin;C:\gtk-build\gtk\x64\release\bin;
```

Notice that there is an extra `;` at the end. Running `python -c "import os; path = print(os.environ.get('PATH', ''))"` does not contain the `;` on the end. The extra `;` does cause the `for p in path.split(os.pathsep)` to set p to "" the last time through the iterable.

**Comment by danyeaw** [comment]
I still am not sure what is unique about my configuration, but because @rokm can't reproduce the extra ; added to my path, I am going to go ahead and close this.

If anyone sees a similar issue in the future, I added the following to my main script file to strip off the ; from the end of the path if it exists:
```
import os
if os.environ['PATH'][-1] == ';':
    os.environ['PATH'] = os.environ['PATH'][:-1]
```

Thanks again @rokm for your help!
