### ISSUE TITLE
PyInstaller website says 4.2 is latest stable release

### ISSUE THREAD

**Issue by ProjectThreepio** [pyinstaller/pyinstaller#6102]
This page says 4.2 is the latest stable release:

https://www.pyinstaller.org/downloads.html

But this page says 4.5.1 has been released:

https://pyinstaller.readthedocs.io/en/stable/CHANGES.html

It's useful to have a page stating what the current version is, with a download link (if it's current).  I periodically check the download page just to see if I should get a new version, and last week I noticed that even though I was on the latest version (4.2), pip wanted to install 4.5.

**Comment by bwoodsend** [comment]
In fact most of the contents of that site are either obsolete, incorrect or explained better on [readthedocs](pyinstaller.readthedocs.io/). @Legorooj You were revamping the website ages ago - would this fall under the revamp? Either way, it's probably best to setup some automation to those variable parts of the website.

**Comment by danyeaw** [comment]
No automation, but I did submit a PR to update the website as a short term fix. 👍

**Comment by danyeaw** [comment]
>  I periodically check the download page just to see if I should get a new version, and last week I noticed that even though I was on the latest version (4.2), pip wanted to install 4.5.

Another solution is that you can select that you want to Watch the project on GitHub, and then set a custom event for releases only. Then GitHub will show you a new notification when a release is made.

**Comment by Legorooj** [comment]
> @Legorooj You were revamping the website ages ago - would this fall under the revamp?

My plan is to completely redesign the site and launch at the same time we release version 5. I was thinking of getting to work on that after I finish up 2 of the contracts I'm currently in & finish the formatting PR.
