### ISSUE TITLE
Windows: v4.5.1 pip installation not working

### ISSUE THREAD

**Issue by m-birke** [pyinstaller/pyinstaller#6113]
Bash - Windows 10 - pip 21.2.3 :

$ pip install pyinstaller
ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: 'C:\\Users\\<...>\\AppData\\Local\\Temp\\pip-unpack-021nitt7\\pyinstaller-4.5.1-py3-none-win_amd64.whl'

install v4.5 working on Windows. Install v4.5.1 working on Linux.

**Comment by bwoodsend** [comment]
Sounds like an overzelous antivirus. Try running:
```
pip download --no-deps pyinstaller
stat pyinstaller-4.5.1-py3-none-win_amd64.whl
pip install pyinstaller-4.5.1-py3-none-win_amd64.whl
```
then check to see if the `pyinstaller-4.5.1-py3-none-win_amd64.whl` has been automatically removed from the current working directory. If it has, you'll need to find how to add an exception to whichever antivirus is wrongfully blocking it.

**Comment by m-birke** [comment]
Hi,

thanks for your answer.
`pip download --no-deps pyinstaller` throws the exact same error. `pip download --no-deps pyinstaller==4.5` again works.

If the file gets blocked, I would expect a FileNotFound Error. For me, invalid argument sounds as if the path would be invalid or something. Really strange...

Maybe its not pyinstaller related.

Edit: But yes, if sth is blocking it already blocks it in the temp dir.

**Comment by bwoodsend** [comment]
> If the file gets blocked, I would expect a FileNotFound Error. For me, invalid argument sounds as if the path would be invalid or something. Really strange...

Windows raises OSError is some pretty strange places. If you try to read/write to a directory rather than a file for instance. An OSError being raised because the antivirus intercepted and blocked the file access sounds relatively normal.

**Comment by m-birke** [comment]
Probably, yes. Maybe it really was the antivirus. Today its working again and we actually have no clue what the reason was.

But thanks for your responses. And sorry that it wasnt a real pyinstaller issue
