### ISSUE TITLE
GUI Images (.png) without background appear with black background in exe

### ISSUE THREAD

**Issue by ML-WI** [pyinstaller/pyinstaller#6117]
Hello, 

I created a small GUI with python 3.9 and implemented some png images without background. After resizing they appear as provided for. After creating the .exe file the images get a black background and the GUI looks very unatractive. Is there some idea to fix this issue?

**Comment by rokm** [comment]
Please provide a minimal example that exhibits this issue.

**Comment by ML-WI** [comment]
The code I use is as follows.

```
from tkinter import *
import time
import os
from PIL import Image
from PIL import ImageTk

root = Tk()
img = Image.open(os.getcwd() + "\\" + "Testdata.PNG")
img = img.resize((40, 40))
picture_testdata = ImageTk.PhotoImage(img)

b = Button(root, text="Test", image=picture_testdata)
b.pack()

root.mainloop()
```
Use this png file to try it.
![Testdata](https://user-images.githubusercontent.com/88834161/129330499-03ea507c-9c8c-413f-bfd5-795ee259e09b.PNG)

The image schould appear on the button without any background. After compiling the exe it appears with a black background.

**Comment by rokm** [comment]
With the provided example code and image, the image appears to have black background even when running unfrozen version.

Adding `img = img.convert('RGBA')` call after loading the image fixes the problem for me, both in unfrozen and frozen version.

(As a side note, the example code assumes the image is located in current working directory, which may or may not be true once you freeze the application. It is best if data file paths are anchored to either `sys._MEIPASS` or `os.path.dirname(__file__)`, and collected into application bundle, to avoid issues with missing data...)
