### ISSUE TITLE
close milestone 4.2

### ISSUE THREAD

**Issue by ThomasWaldmann** [pyinstaller/pyinstaller#6134]
https://github.com/pyinstaller/pyinstaller/milestone/24 long done.

**Comment by bwoodsend** [comment]
Closed. To be honest, I don't really know why we have them. We invariably ignore them - completed or otherwise.

**Comment by ThomasWaldmann** [comment]
Milestone are useful for focussing on a subset of tickets and as a progress indicator -  esp. if the project has many open tickets.

Adding something to a milestone does not necessarily mean it must stay there / must be done - it can be moved to next milestone or removed from milestones again.
