### ISSUE TITLE
Unable to import Shiboken

### ISSUE THREAD

**Issue by zaphbbrox** [pyinstaller/pyinstaller#6145]
## Description of the issue
After bundling the app with `pyinstaller` in `wine`, it gives following error on a Windows machine:  
```
PySide6/__init__.py: Unable to import Shiboken from U:\PROGNAME\base_library.zip, U:\PROGNAME\lib-dynload, U:\PROGNAME
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 474, in exec_module
  File "db_controller.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 474, in exec_module
  File "PySide6\__init__.py", line 111, in <module>
  File "PySide6\__init__.py", line 60, in _setupQtDirectories
  File "PyInstaller\loader\pyimod03_importers.py", line 474, in exec_module
  File "shiboken6\__init__.py", line 25, in <module>
ImportError: DLL load failed while importing Shiboken: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
[56192] Failed to execute script 'main' due to unhandled exception!
[56192] LOADER: OK.
[56192] LOADER: Manually flushing stdout and stderr
[56192] LOADER: Cleaning up Python interpreter.
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev```
* Version of Python: ```Python 3.9.5```
* Platform: Windows (German)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?
  * Yes, the bundled program runs in `wine`
  * also if bundled with Linux it runs without errors 

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and
  * Done

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Stacktrace / full error message

```
PS U:\PROGNAME> .\PROGNAME.exe
[56192] PyInstaller Bootloader 3.x
[56192] LOADER: executable is U:\PROGNAME\PROGNAME.exe
[56192] LOADER: homepath is U:\PROGNAME
[56192] LOADER: _MEIPASS2 is NULL
[56192] LOADER: archivename is U:\PROGNAME\PROGNAME.exe
[56192] LOADER: Cookie found at offset 0x1F0C92
[56192] LOADER: No need to extract files to run; setting extractionpath to homepath
[56192] LOADER: SetDllDirectory(U:\PROGNAME)
[56192] LOADER: Already in the child - running user's code.
[56192] LOADER: Python library: U:\PROGNAME\python38.dll
[56192] LOADER: Loaded functions from Python library.
[56192] LOADER: Manipulating environment (sys.path, sys.prefix)
[56192] LOADER: sys.prefix is U:\PROGNAME
[56192] LOADER: Pre-init sys.path is U:\PROGNAME\base_library.zip;U:\PROGNAME\lib-dynload;U:\PROGNAME
[56192] LOADER: Setting runtime options
[56192] LOADER: Initializing python
[56192] LOADER: Overriding Python's sys.path
[56192] LOADER: Post-init sys.path is U:\PROGNAME\base_library.zip;U:\PROGNAME\lib-dynload;U:\PROGNAME
[56192] LOADER: Setting sys.argv
[56192] LOADER: setting sys._MEIPASS
[56192] LOADER: importing modules from CArchive
[56192] LOADER: extracted struct
[56192] LOADER: running unmarshalled code object for struct...
[56192] LOADER: extracted pyimod01_os_path
[56192] LOADER: running unmarshalled code object for pyimod01_os_path...
[56192] LOADER: extracted pyimod02_archive
[56192] LOADER: running unmarshalled code object for pyimod02_archive...
[56192] LOADER: extracted pyimod03_importers
[56192] LOADER: running unmarshalled code object for pyimod03_importers...
[56192] LOADER: extracted pyimod04_ctypes
[56192] LOADER: running unmarshalled code object for pyimod04_ctypes...
[56192] LOADER: Installing PYZ archive with Python modules.
[56192] LOADER: PYZ archive: PYZ-00.pyz
[56192] LOADER: Running pyiboot01_bootstrap.py
[56192] LOADER: Running pyi_rth_pkgutil.py
[56192] LOADER: Running pyi_rth_multiprocessing.py
[56192] LOADER: Running pyi_rth_inspect.py
[56192] LOADER: Running pyi_rth_pyside6.py
[56192] LOADER: Running main.py
PySide6/__init__.py: Unable to import Shiboken from U:\PROGNAME\base_library.zip, U:\PROGNAME\lib-dynload, U:\PROGNAME
Traceback (most recent call last):
  File "main.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 474, in exec_module
  File "db_controller.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 474, in exec_module
  File "PySide6\__init__.py", line 111, in <module>
  File "PySide6\__init__.py", line 60, in _setupQtDirectories
  File "PyInstaller\loader\pyimod03_importers.py", line 474, in exec_module
  File "shiboken6\__init__.py", line 25, in <module>
ImportError: DLL load failed while importing Shiboken: Eine DLL-Initialisierungsroutine ist fehlgeschlagen.
[56192] Failed to execute script 'main' due to unhandled exception!
[56192] LOADER: OK.
[56192] LOADER: Manually flushing stdout and stderr
[56192] LOADER: Cleaning up Python interpreter.
```

**Comment by rokm** [comment]
Does the generated executable run under the original environment in Wine? And does the original, unfrozen version run in that Wine-based environment?

**Comment by bwoodsend** [comment]
> Yes, the bundled program runs in wine

Looks like a yes.

**Comment by rokm** [comment]
My bad, I overlooked that part. 

This might rule out the first possible cause, i.e., the native VC runtime not having been present at the build time (and thus not being collected, and it being missing on the target machine).

Perhaps one of wine's built-in DLLs ended up collected, and are causing problems in the dependency chain on actual Windows? (E.g., does wine provide their own `vcruntime140.dll` and `vcruntime140_1.dll` in PE form, and those ended up being collected?)

Either way, the next step in debugging this should probably be inspecting the dependencies of shiboken DLL and PYD using Dependency Walker or equivalent tool. Or, you can try packaging a simple PySide6-based hello-world application and, if it exhibits the same problems, upload it somewhere so we can take a look at it.

**Comment by zaphbbrox** [comment]
> Perhaps one of wine's built-in DLLs ended up collected, and are causing problems in the dependency chain on actual Windows? (E.g., does wine provide their own `vcruntime140.dll` and `vcruntime140_1.dll` in PE form, and those ended up being collected?)  

Not sure if in PE form, but both files are being collected.
> Either way, the next step in debugging this should probably be inspecting the dependencies of shiboken DLL and PYD using Dependency Walker or equivalent tool. Or, you can try packaging a simple PySide6-based hello-world application and, if it exhibits the same problems, upload it somewhere so we can take a look at it.

I'll try it out first thing tomorrow morning. Thanks for your support so far!

**Comment by zaphbbrox** [comment]
> Does the generated executable run under the original environment in Wine? And does the original, unfrozen version run in that Wine-based environment?

The unfrozen version is running fine with `wine cmd /c python main.py`.

**Comment by zaphbbrox** [comment]
>Either way, the next step in debugging this should probably be inspecting the dependencies of shiboken DLL and PYD using Dependency Walker or equivalent tool. Or, you can try packaging a simple PySide6-based hello-world application and, if it exhibits the same problems, upload it somewhere so we can take a look at it.

### Hello World test

I created a simple 'Hello World' PySide6 application:  
```
import sys
from PySide6.QtWidgets import QApplication, QWidget, QLabel

def window():
    app = QApplication(sys.argv)
    widget = QWidget()

    textlabel = QLabel(widget)
    textlabel.setText("Hello World")

    widget.show()
    sys.exit(app.exec())

if __name__ == '__main__':
    window()
```
The error stays the same.  

## Dependency Walker

### missing DLLs
```
API-MS-WIN-CORE-APIQUERY-L1-1-0.DLL
API-MS-WIN-CORE-APPCOMPAT-L1-1-1.DLL
API-MS-WIN-CORE-COMM-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L1-1-0.DLL
API-MS-WIN-CORE-CONSOLE-L2-1-0.DLL
API-MS-WIN-CORE-CRT-L1-1-0.DLL
API-MS-WIN-CORE-CRT-L2-1-0.DLL
API-MS-WIN-CORE-DATETIME-L1-1-1.DLL
API-MS-WIN-CORE-DATETIME-L1-1-2.DLL
API-MS-WIN-CORE-DEBUG-L1-1-1.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-1.DLL
API-MS-WIN-CORE-ENCLAVE-L1-1-0.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-1.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-3.DLL
API-MS-WIN-CORE-FIBERS-L1-1-1.DLL
API-MS-WIN-CORE-FIBERS-L2-1-1.DLL
API-MS-WIN-CORE-FILE-L1-2-1.DLL
API-MS-WIN-CORE-FILE-L1-2-2.DLL
API-MS-WIN-CORE-FILE-L2-1-1.DLL
API-MS-WIN-CORE-FILE-L2-1-2.DLL
API-MS-WIN-CORE-HANDLE-L1-1-0.DLL
API-MS-WIN-CORE-HEAP-L1-2-0.DLL
API-MS-WIN-CORE-HEAP-L2-1-0.DLL
API-MS-WIN-CORE-HEAP-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-2-0.DLL
API-MS-WIN-CORE-IO-L1-1-1.DLL
API-MS-WIN-CORE-JOB-L1-1-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-0.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-2-2.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-1.DLL
API-MS-WIN-CORE-LOCALIZATION-L2-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-2.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-0.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-2-2.DLL
API-MS-WIN-CORE-NAMESPACE-L1-1-0.DLL
API-MS-WIN-CORE-NORMALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-PERFCOUNTERS-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-2-0.DLL
API-MS-WIN-CORE-PROCESSSNAPSHOT-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-2.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-3.DLL
API-MS-WIN-CORE-PROCESSTOPOLOGY-L1-2-0.DLL
API-MS-WIN-CORE-PROFILE-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-ANSI-L1-1-0.DLL
API-MS-WIN-CORE-PSAPI-L1-1-0.DLL
API-MS-WIN-CORE-REALTIME-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-REGISTRY-L1-1-1.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-2-0.DLL
API-MS-WIN-CORE-SIDEBYSIDE-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L1-1-0.DLL
API-MS-WIN-CORE-STRING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-0.DLL
API-MS-WIN-CORE-SYNCH-L1-2-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-1.DLL
API-MS-WIN-CORE-SYSINFO-L1-2-3.DLL
API-MS-WIN-CORE-THREADPOOL-L1-2-0.DLL
API-MS-WIN-CORE-THREADPOOL-LEGACY-L1-1-0.DLL
API-MS-WIN-CORE-THREADPOOL-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-TIMEZONE-L1-1-0.DLL
API-MS-WIN-CORE-UTIL-L1-1-0.DLL
API-MS-WIN-CORE-WINDOWSERRORREPORTING-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-0.DLL
API-MS-WIN-CORE-WOW64-L1-1-1.DLL
API-MS-WIN-CORE-XSTATE-L2-1-0.DLL
API-MS-WIN-EVENTING-CONSUMER-L1-1-0.DLL
API-MS-WIN-EVENTING-CONTROLLER-L1-1-0.DLL
API-MS-WIN-EVENTING-PROVIDER-L1-1-0.DLL
API-MS-WIN-SECURITY-APPCONTAINER-L1-1-0.DLL
API-MS-WIN-SECURITY-AUDIT-L1-1-1.DLL
API-MS-WIN-SECURITY-BASE-L1-2-0.DLL
API-MS-WIN-SECURITY-BASE-PRIVATE-L1-1-1.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L1-1-1.DLL
API-MS-WIN-SECURITY-LSAPOLICY-L1-1-0.DLL
API-MS-WIN-SERVICE-CORE-L1-1-1.DLL
API-MS-WIN-SERVICE-CORE-L1-1-2.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L1-1-0.DLL
API-MS-WIN-SERVICE-MANAGEMENT-L2-1-0.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-1.DLL
API-MS-WIN-SERVICE-PRIVATE-L1-1-2.DLL
API-MS-WIN-SERVICE-WINSVC-L1-2-0.DLL
API-MS-WIN-CORE-APPINIT-L1-1-0.DLL
API-MS-WIN-CORE-ATOMS-L1-1-0.DLL
API-MS-WIN-CORE-COM-L1-1-1.DLL
API-MS-WIN-CORE-DATETIME-L1-1-0.DLL
API-MS-WIN-CORE-DEBUG-L1-1-0.DLL
API-MS-WIN-CORE-DELAYLOAD-L1-1-0.DLL
API-MS-WIN-CORE-ERRORHANDLING-L1-1-0.DLL
API-MS-WIN-CORE-FILE-L1-1-0.DLL
API-MS-WIN-CORE-FILE-L1-2-0.DLL
API-MS-WIN-CORE-FILE-L2-1-0.DLL
API-MS-WIN-CORE-HEAP-L1-1-0.DLL
API-MS-WIN-CORE-INTERLOCKED-L1-1-0.DLL
API-MS-WIN-CORE-IO-L1-1-0.DLL
API-MS-WIN-CORE-KERNEL32-LEGACY-L1-1-1.DLL
API-MS-WIN-CORE-KERNEL32-PRIVATE-L1-1-1.DLL
API-MS-WIN-CORE-LIBRARYLOADER-L1-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-1-0.DLL
API-MS-WIN-CORE-LOCALIZATION-L1-2-0.DLL
API-MS-WIN-CORE-LOCALIZATION-OBSOLETE-L1-3-0.DLL
API-MS-WIN-CORE-LOCALREGISTRY-L1-1-0.DLL
API-MS-WIN-CORE-MEMORY-L1-1-0.DLL
API-MS-WIN-CORE-MISC-L1-1-0.DLL
API-MS-WIN-CORE-NAMEDPIPE-L1-1-0.DLL
API-MS-WIN-CORE-PRIVATEPROFILE-L1-1-1.DLL
API-MS-WIN-CORE-PROCESSENVIRONMENT-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-0.DLL
API-MS-WIN-CORE-PROCESSTHREADS-L1-1-1.DLL
API-MS-WIN-CORE-REGISTRY-PRIVATE-L1-1-0.DLL
API-MS-WIN-CORE-RTLSUPPORT-L1-1-0.DLL
API-MS-WIN-CORE-STRING-L2-1-0.DLL
API-MS-WIN-CORE-STRINGANSI-L1-1-0.DLL
API-MS-WIN-CORE-SYNCH-L1-1-0.DLL
API-MS-WIN-CORE-SYSINFO-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-L1-1-0.DLL
API-MS-WIN-CORE-VERSION-PRIVATE-L1-1-0.DLL
API-MS-WIN-CRT-PRIVATE-L1-1-0.DLL
API-MS-WIN-DEVICES-CONFIG-L1-1-1.DLL
API-MS-WIN-DEVICES-QUERY-L1-1-1.DLL
API-MS-WIN-EVENTING-CLASSICPROVIDER-L1-1-0.DLL
API-MS-WIN-EVENTING-OBSOLETE-L1-1-0.DLL
API-MS-WIN-GDI-INTERNAL-UAP-L1-1-0.DLL
API-MS-WIN-POWER-BASE-L1-1-0.DLL
API-MS-WIN-POWER-SETTING-L1-1-0.DLL
API-MS-WIN-SECURITY-BASE-L1-2-1.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L1-1-0.DLL
API-MS-WIN-SECURITY-CREDENTIALS-L2-1-0.DLL
API-MS-WIN-SECURITY-GROUPPOLICY-L1-1-0.DLL
API-MS-WIN-SECURITY-LSALOOKUP-L2-1-1.DLL
API-MS-WIN-SECURITY-PROVIDER-L1-1-0.DLL
API-MS-WIN-SECURITY-SDDL-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NPUSERNAME-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-NTMARTA-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-ADVAPI32-SAFER-L1-1-0.DLL
EXT-MS-WIN-APPMODEL-DAXCORE-L1-1-0.DLL
EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOY-L1-1-0.DLL
EXT-MS-WIN-APPXDEPLOYMENTCLIENT-APPXDEPLOYONECORE-L1-1-0.DLL
EXT-MS-WIN-AUTHZ-CONTEXT-L1-1-0.DLL
EXT-MS-WIN-COM-PSMREGISTER-L1-2-1.DLL
EXT-MS-WIN-CORE-WINRT-REMOTE-L1-1-0.DLL
EXT-MS-WIN-EDPUTIL-POLICY-L1-1-0.DLL
EXT-MS-WIN-EVENTING-RUNDOWN-L1-1-0.DLL
EXT-MS-WIN-FECLIENT-ENCRYPTEDFILE-L1-1-0.DLL
EXT-MS-WIN-GDI-CLIPPING-L1-1-0.DLL
EXT-MS-WIN-GDI-DC-CREATE-L1-1-1.DLL
EXT-MS-WIN-GDI-DC-L1-2-0.DLL
EXT-MS-WIN-GDI-DC-L1-2-1.DLL
EXT-MS-WIN-GDI-DRAW-L1-1-1.DLL
EXT-MS-WIN-GDI-DRAW-L1-1-3.DLL
EXT-MS-WIN-GDI-FONT-L1-1-1.DLL
EXT-MS-WIN-GDI-FONT-L1-1-3.DLL
EXT-MS-WIN-GDI-INTERNAL-DESKTOP-L1-1-0.DLL
EXT-MS-WIN-GDI-METAFILE-L1-1-1.DLL
EXT-MS-WIN-GDI-METAFILE-L1-1-2.DLL
EXT-MS-WIN-GDI-PATH-L1-1-0.DLL
EXT-MS-WIN-GDI-PRINT-L1-1-0.DLL
EXT-MS-WIN-GDI-PRIVATE-L1-1-0.DLL
EXT-MS-WIN-GDI-WCS-L1-1-0.DLL
EXT-MS-WIN-GPAPI-GROUPPOLICY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-APPCOMPAT-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-DATETIME-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-ERRORHANDLING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-FILE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-QUIRKS-L1-1-1.DLL
EXT-MS-WIN-KERNEL32-REGISTRY-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-SIDEBYSIDE-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-0.DLL
EXT-MS-WIN-KERNEL32-WINDOWSERRORREPORTING-L1-1-1.DLL
EXT-MS-WIN-KERNELBASE-PROCESSTHREAD-L1-1-0.DLL
EXT-MS-WIN-MRMCORER-RESMANAGER-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-0.DLL
EXT-MS-WIN-NTDSAPI-ACTIVEDIRECTORYCLIENT-L1-1-1.DLL
EXT-MS-WIN-NTUSER-MESSAGE-L1-1-1.DLL
EXT-MS-WIN-NTUSER-STRING-L1-1-0.DLL
EXT-MS-WIN-NTUSER-SYNCH-L1-1-0.DLL
EXT-MS-WIN-NTUSER-WINDOW-L1-1-1.DLL
EXT-MS-WIN-PROFILE-EXTENDER-L1-1-0.DLL
EXT-MS-WIN-PROFILE-LOAD-L1-1-0.DLL
EXT-MS-WIN-RPC-SSL-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-SYSPARAMS-L1-1-0.DLL
EXT-MS-WIN-RTCORE-NTUSER-WINDOW-EXT-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CAPAUTHZ-L1-1-0.DLL
EXT-MS-WIN-SECURITY-CHAMBERS-L1-1-0.DLL
EXT-MS-WIN-SECURITY-EFSWRT-L1-1-1.DLL
EXT-MS-WIN-SHELL32-SHELLCOM-L1-1-0.DLL
```

Some modules have a different CPU type, although we used `wine64` and the 64-bit version of `python`:

### x86-DLLs
```
ADVAPI32.DLL
BCRYPTPRIMITIVES.DLL
CRYPTBASE.DLL
KERNEL32.DLL
KERNELBASE.DLL
MSVCRT.DLL
NTDLL.DLL
RPCRT4.DLL
SECHOST.DLL
SSPICLI.DLL
BCRYPT.DLL
CABINET.DLL
CFGMGR32.DLL
CRYPT32.DLL
CRYPTSP.DLL
DBGHELP.DLL
DEVOBJ.DLL
DEVRTL.DLL
DHCPCSVC.DLL
DHCPCSVC6.DLL
DNSAPI.DLL
DPAPI.DLL
DSPARSE.DLL
GDI32.DLL
IMAGEHLP.DLL
IPHLPAPI.DLL
MSASN1.DLL
MSIMG32.DLL
NCRYPT.DLL
NSI.DLL
NTASN1.DLL
PROFAPI.DLL
SAMLIB.DLL
UCRTBASE.DLL
USER32.DLL
WIN32U.DLL
WINNSI.DLL
WINSTA.DLL
WINTRUST.DLL
WS2_32.DLL
```
### x64-DLLs
```
HELLO_WORLD.EXE
API-MS-WIN-CRT-RUNTIME-L1-1-0.DLL
API-MS-WIN-CRT-STDIO-L1-1-0.DLL
API-MS-WIN-CRT-STRING-L1-1-0.DLL
API-MS-WIN-CRT-TIME-L1-1-0.DLL
```

**Comment by rokm** [comment]
Does it help if you remove all those x86 DLLs, plus all API-MS-* ones, regardless of the arch? Those are definitely coming from wine, and are likely bad news on native Windows...

**Comment by zaphbbrox** [comment]
> Does it help if you remove all those x86 DLLs, plus all API-MS-* ones, regardless of the arch? Those are definitely coming from wine, and are likely bad news on native Windows...

Sadly not.

**Comment by rokm** [comment]
In that case, can you upload the build of that hello world application somewhere, so I can download and take a look at it?

**Comment by zaphbbrox** [comment]
Yeah, sure:
[nowtransfer.de/be1c28ffb734](https://nowtransfer.de/be1c28ffb734)

**Comment by rokm** [comment]
> ('MSVCP140.dll', 'C:\\windows\\system32\\MSVCP140.dll', 'BINARY'),

`msvcp140.dll` is a wine-provided version, and needs to be replaced with proper native version. The rest of VC runtime DLLs (`msvcp140_1.dll`, `vcruntime140.dll`, and `vcruntime140_1.dll`) seem to be taken from Python installation and/or PySide6 package, so they are OK.

Perhaps the problem can be fixed by ensuring that native version of VC runtime DLLs is available (i.e., by installing VC redist in wine environment). But I'd still keep an eye out on any wine-provided DLLs that might end up collected...

**Comment by bwoodsend** [comment]
I believe that neither `msvcp140.dll` or `vcruntime140.dll` are to be considered system libraries (i.e. we must collect them) in which case both including and excluding those Wine specific DLLs would produce invalid bundles. I though Python brought its own copies of those DLLs so would they be collectable?

**Comment by rokm** [comment]
> I believe that neither `msvcp140.dll` or `vcruntime140.dll` are to be considered system libraries (i.e. we must collect them)

Yeah, VC runtime DLLs are installed in the system location (c:\windows\system32), but they are not system libraries, and we need to collect them in order to avoid missing DLL errors on target systems that do not have VC redist installed.

> in which case both including and excluding those Wine specific DLLs would produce invalid bundles. 

Ending up with `wine`'s own DLL in a PE form is likely a recipe for disaster on actual Windows, especially for the "low-level" stuff (system DLLs, VC runtime ones, etc.). 

I'd say that trying to build PyInstaller-frozen applications for Windows under `wine` is asking for trouble, but I suppose it could be doable once you know what to watch out for...

> I though Python brought its own copies of those DLLs so would they be collectable?

Python brings in `vcruntime140.dll` and `vcruntime140_1.dll`, PySide6 brings in `msvcp140_1.dll`, and we did end up collecting those instead of the `wine`'s versions:

```
('VCRUNTIME140.dll', 'c:\\program files\\Python38\\VCRUNTIME140.dll', 'BINARY'),
('VCRUNTIME140_1.dll', 'c:\\program files\\Python38\\VCRUNTIME140_1.dll', 'BINARY'),
('MSVCP140_1.dll', 'C:\\Program Files\\Python38\\Lib\\site-packages\\PySide6\\MSVCP140_1.dll', 'BINARY'),
```

Nobody brought a copy of `msvcp140.dll`, though - and I don't think it is present on Windows 10 by default (so we still have to collect it), because I had to bring a copy to my "clean-install" Windows 10 VM to make the bundle work (i.e., just removing the bundled copy of the offending DLL was not enough, although it would have been if VC redist had been installed on the system).

**Comment by zaphbbrox** [comment]
Installing the redist package seems to work. The window is showing up! Thanks a lot, now we can do some testing!  
This is an important step, but besides that: is there anything I can do about all these missing DLLs, because I'm currently stick to bundle the app with `wine`.

**Comment by rokm** [comment]
>  is there anything I can do about all these missing DLLs, because I'm currently stick to bundle the app with `wine`

If you are referring to the earlier list of missing `API-MS-*` and `EXT-MS-*` DLLs, those are usually not directly visible/resolvable under Windows (I never bothered to look up when and how they are actually resolved), so PyInstaller cannot collect them (except when using Anaconda python, which brings their own copy of those DLLs).

In your case, you should probably worry about the couple of `API-MS-*` files that did end up collected, because those are clearly `wine`'s files as well. Perhaps they are just harmless dead weight (i.e., Windows ignores them and loads their version, anyway), but you never know... To deal with these, you will probably need to modify your local copy of PyInstaller, and tweak the [_win_includes list](https://github.com/pyinstaller/pyinstaller/blob/0b08d0006cd1b882ade89751ec9962c148f9e07d/PyInstaller/depend/dylib.py#L60) (i.e., remove the `api-ms*` entries from it).

**Comment by zaphbbrox** [comment]
Sorry, yes meant the other way round.

>To deal with these, you will probably need to modify your local copy of PyInstaller, and tweak the _win_includes list (i.e., remove the api-ms* entries from it).

Okay, I'll keep that in mind.

I close the issue for now. If you guys consider this a bug, feel free to reopen.

**Comment by zaphbbrox** [comment]
Thanks a lot for your help!

**Comment by bwoodsend** [comment]
Is it possible to programatically detect if a DLL is a Wine variant? If it were then we could at least add some warnings to help point other Wine users in the right direction.

**Comment by rokm** [comment]
> Is it possible to programatically detect if a DLL is a Wine variant? If it were then we could at least add some warnings to help point other Wine users in the right direction.

It probably is, because `wine` also needs to be able to switch between their built-in (PE-converted or fake) DLLs  and the native ones...
