### ISSUE TITLE
freeze using sqlalchemy crashes in Windows but doesn't in Linux (SqlAlchemy, pyscopg2)

### ISSUE THREAD

**Issue by BartDenOuden** [pyinstaller/pyinstaller#6148]
Hi, 

This example programm crashes when I have frozen it in Windows, but it works in Linux (Ubuntu). It uses sqlalchemy and psycopg2. The programm crashes at "engine.connect()" and gives no messages. The console in which it is running just disappears. In Linux the programm runs, freezing without any parameters or configured spec-file. In Windows I have included 'sqlalchemy.sql.default_comparator' in the hidden imports. 

I have tried: 
- freeze in Windows 10
- freeze in Windows 7
- older versions of psycopg2, sqlalchemy, pyinstaller and the recent versions
- python 3.8 and 3.9
- virtualenv, using pip to install packages including pyinstaller
- miniconda (all packages including pyinstaller installed using channel 'conda-forge', channel_priority = strict)

```
import sys
import sqlalchemy

database = 'db'
user = 'postgres'
password = 'password'
host = 'host'
port = '5432'

engine = sqlalchemy.create_engine(f"postgresql://{user}:{password}@{host}:{port}/{database}")

try:
    # PROGRAMM FROZEN IN WINDOWS CRASHES HERE:
    conn = engine.connect()
except:
    print("Unexpected error:", sys.exc_info()[0])
conn.execute("SELECT * FROM  spatial_ref_sys")
dummy = input("Enter to close. ")

```
Could this be a bug in pyinstaller or must I configure the spec-file in Windows differtently? 

Best regards, Bart

**Comment by rokm** [comment]
> The console in which it is running just disappears.

This sounds like you're running the program by double-clicking on it. What happens if you run it from  Command Prompt (`cmd`)?

**Comment by BartDenOuden** [comment]
Hi Rok, 

If I run it in a console the console doesn't show the "Enter to close. " message. The console doesn't give any message and returns to the prompt.

**Comment by rokm** [comment]
Hmm, I can't reproduce that. In my test environment, consisting of clean python 3.9.1 from python.org and the following packages:

<details><summary> Output of `pip freeze` </summary>

<p>

```
altgraph==0.17
future==0.18.2
greenlet==1.1.1
pefile==2021.5.24
psycopg2==2.9.1
pyinstaller==4.5.1
pyinstaller-hooks-contrib==2021.2
pywin32-ctypes==0.2.0
SQLAlchemy==1.4.23
```
</p>

</details>

your test program raises exception about not being able to resolve host, as expected.

**Comment by rokm** [comment]
Can you trying enabling debug build (use `--debug all` with PyInstaller command if building from .py file, or set `debug=True` to `EXE()` in the .spec file) to see bootloader's messages?

**Comment by BartDenOuden** [comment]
Hi Rok, it now works. I now do get messages in the console. If should have used the console to start the frozen python programm from the start. So sorry to bother you with this and thank you very much for your work and quick responses!
