### ISSUE TITLE
Activate conda environment before python executable runs

### ISSUE THREAD

**Issue by scottwsides** [pyinstaller/pyinstaller#6166]
I have a conda environment with all my dependencies set. I dont want pyinstaller to package these since its complicated and pyinstaller is not getting them correct. I simply need my PyQt app (the one listed in the Analysis class) to be running in a conda environment I've created.. then all imports will be found. I've tried lots of ideas to rig this ... but nothing works. Setting a path for my conda environment in 'pathex' doesnt work either. All attempts to bootstrap this by running scripts in my python executable dont work. Is there a solution?

**Comment by eric15342335** [comment]
> I dont want pyinstaller to package these since its complicated and pyinstaller is not getting them correct.

What is the error you have encountered?
