### ISSUE TITLE
Cannot download pyinstaller 4.5.1 py3-none-win_amd64 wheel - Download error

### ISSUE THREAD

**Issue by humberto-garza** [pyinstaller/pyinstaller#6169]
## Description of the issue

When trying to `pip install pyinstaller==4.5.1` on a Windows 64 system I get this error:

```sh
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\<USERNAME>\\AppData\\Local\\Temp\\pip-unpack-6cwiyc67\\pyinstaller-4.5.1-py3-none-win_amd64.whl'
Installing collected packages: pyinstaller
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: 'C:\\Users\\<USERNAME>\\AppData\\Local\\Temp\\pip-unpack-6cwiyc67\\pyinstaller-4.5.1-py3-none-win_amd64.whl'
```

Even trying to download directly from pypi fails with "Download Error":
https://pypi.org/project/pyinstaller/#files

[pyinstaller-4.5.1-py3-none-win_amd64.whl (1.9 MB)](https://files.pythonhosted.org/packages/12/a9/91a182d5b2541d8b89396f4371151e412246f8e8d6e65954871548a2a14b/pyinstaller-4.5.1-py3-none-win_amd64.whl).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: `3.6.8`
* Platform: `Windows`
* How you installed Python: pyenv
* Did you also try this on another platform? Does it work there?
Downloads for other platforms work.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

N/A

### A minimal example program which shows the error

N/A

### Stacktrace / full error message

(See description)

**Comment by bwoodsend** [comment]
That'll just be your antivirus getting in the way. Try either turning it off or adding an exception.

**Comment by Legorooj** [comment]
Does installing other packages - eg, `tinyaes`, work, or do you get the same issue? aka is this PyInstaller-specific?

**Comment by humberto-garza** [comment]
I am able to install `tinyaes` for example

**Comment by eric15342335** [comment]
@humberto-garza Have you followed what bwoodsend just said?
