### ISSUE TITLE
Unsuccessfully built when using conda-forge

### ISSUE THREAD

**Issue by RoadToDream** [pyinstaller/pyinstaller#6181]
## Description of the issue
I am not sure if it's related to my incorrect configuration or something else, as I am new to Python. So I just post and hope to see if I may get some help. 
When using conda-forge to install package **pyqtads**, PyInstaller will report 

```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtGui'
[44990] Failed to execute script 'app' due to unhandled exception!
```
or when import specific class from PyQt5.QtGui like QPixmap or QImage, it will have errors like 
```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Abort trap: 6
logout
```

Thanks to any help provided! 

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: 3.7.11
* Platform: macOS Mojave version 10.14.6 
* How you installed Python: pip 
* Did you also try this on another platform? Does it work there?
Tried on macOS and Windows 10, both not working correctly. 

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
using following to create environment
```
conda create -y --name test python=3.7
conda activate test
conda install -y -c conda-forge pyqtads
```
```
from PyQt5.QtWidgets import QWidget,QMainWindow,QApplication
from PyQtAds import QtAds
import sys

class MainWindow(QMainWindow):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.m_DockManager = QtAds.CDockManager()

        self.qtadsWidget = QtAds.CDockWidget('qtads')
        self.qtadsWidget.setWidget(QWidget())
        
        self.m_DockManager.addDockWidget(QtAds.TopDockWidgetArea,self.qtadsWidget)
        
        self.setCentralWidget(self.m_DockManager)
        self.show()

if __name__ == '__main__':
    app = QApplication([])

    w=MainWindow()
    w.show()
    sys.exit(app.exec())
```

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "app.py", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.QtGui'
[44990] Failed to execute script 'app' due to unhandled exception!
```
or when import specific class from PyQt5.QtGui like QPixmap or QImage, it will have errors like 
```
qt.qpa.plugin: Could not find the Qt platform plugin "cocoa" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Abort trap: 6
logout
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> Tried on macOS and Windows 10, both not working correctly.

It seems to work correctly on Windows 10.

But on macOS, we indeed do not handle Qt library names when installed from Anaconda correctly, so our Qt dependency scanner is failing to pick up dependent Qt modules (so you end up with missing modules, their plugins, etc.).

**Comment by rokm** [comment]
The macOS problem should be fixed in both `develop` and `v4` branches.

**Comment by RoadToDream** [comment]
> > Tried on macOS and Windows 10, both not working correctly.
> 
> It seems to work correctly on Windows 10.
> 
> But on macOS, we indeed do not handle Qt library names when installed from Anaconda correctly, so our Qt dependency scanner is failing to pick up dependent Qt modules (so you end up with missing modules, their plugins, etc.).

Thank you for the help! Maybe I didn't correctly configure it on Windows, let me try it again. 
I will also try `develop` and `v4` branches on macOS

**Comment by RoadToDream** [comment]
> The macOS problem should be fixed in both `develop` and `v4` branches.

Hi @rokm, I can confirm that patch fixes the macOS issue. 
I redo everything on Windows and it turns out that it's due to my incorrect configuration. 
Thank you for the help!
