### ISSUE TITLE
Application not cleanly exiting on Apple Silicon MacOS

### ISSUE THREAD

**Issue by willwrong** [pyinstaller/pyinstaller#6183]
Issue: PyInstaller executable does not cleanly exit on Apple Silicon Mac: once `os._exit()` or `sys.exit()`  is called. MacOS reports it as "unexpectedly exiting" (similar to if you were to force quit the process) along with a crashlog of the application's process threads, despite the rest of the program appearing to exit perfectly normally. I've tried some alternative ways to "exit" the program but all induce the same crashlog.

### Context information (for bug reports)

* Output of `pyinstaller --version`: Don't have access to my M1 machine right this moment, so will update this evening, but I pulled the most recent version yesterday...
* Version of Python: 3.9
* Platform: MacOS 10.15.7 aarch64 (Apple Silicon)
* How you installed Python: brew
* Did you also try this on another platform? Does it work there? Yes, it exits cleanly on Windows 10 and Manjaro Linux builds.

**Comment by rokm** [comment]
Does this happen with any PyInstaller-frozen application (e.g., simple hello-world program, or a program that does just `sys.exit()`), or a specific one?

**Comment by willwrong** [comment]
Ah, it would appear to be program specific (however I'm only encountering the issue on MacOS). I'll close this as it's probably my fault more than anything!
