### ISSUE TITLE
RunTime Error in winrt: Cannot change thread mode after it is set

### ISSUE THREAD

**Issue by aliencaocao** [pyinstaller/pyinstaller#6198]
I had to use snipping tools to grab a screenshot of the traceback since the console window closes itself after encountering an error, so I have to post a picture here.
![image](https://user-images.githubusercontent.com/20109683/132899844-77688a1c-c7bd-4148-a36b-f3d604bcb643.png)
The Chinese part of the error translates to "Cannot change thread mode after it is set". I have verified that this is the exact same translation from other github issues.
This issue only happens when running a compiled exe. It does not happen when running python script from IDE or command line. It seems like the inclusion of the pandas package triggers a special compiling setting in pyinstaller, which then causes the bleak package to fail. If pandas is not imported, everything is normal.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: 3.9.7
* Platform: Windows 11 Professional (Simplified Chinese)
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there?
Tried on another Windows 10 machine and it does not work.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
pip install bleak pandas
```
from bleak import BleakScanner
import pandas as pd
input()
```

Compiled with `pyinstaller -F test.py`

Tried --onedir same error
Through experimentation, I found 2 other libraries that cause the same issue: wmi, PIL
My research shows that problem should lie in the threading mode. See: https://github.com/pywinauto/pywinauto/issues/445
https://stackoverflow.com/questions/127188/could-you-explain-sta-and-mta

**Comment by rokm** [comment]
Does it work if you add `--exclude win32api --exclude win32com` to your `pyinstaller` command?

**Comment by rokm** [comment]
The problem can be triggered (without pyinstaller) if `win32com` is imported before `bleak`. `win32com` is, in turn (conditionally) imported by `pkg_resources`, so importing that before `bleak`triggers the error as well (if you have `pywin32` installed).

Any use of `pkg_resources` causes PyInstaller's runtime hook for `pkg_resources` to be run, which means that `pkg_resources` ends up being imported before user script is run. So again, if `pywin32` is installed, that means error (and in addition, if `pywin32` is installed and pulled in, hooks for `win32api` and `win32com` are also ran, so the latter triggers the error again).

I think our `pkg_resources` hook should exlude `win32api` and `win32com` to prevent pulling them in; the imports come from [here](https://github.com/pypa/setuptools/blob/fdb818def5e262eee8edc4cc7ba1b79461096bfc/pkg_resources/_vendor/appdirs.py#L479) and [here](https://github.com/pypa/setuptools/blob/fdb818def5e262eee8edc4cc7ba1b79461096bfc/pkg_resources/_vendor/appdirs.py#L560-L561), so if they are unavailable, it ends up using `ctypes`-based codepath.

**Comment by aliencaocao** [comment]
You are right that importing win32com before bleak triggers the issue without pyinstaller. If I only import win32com after bleak, it does not trigger the issue without pyinstaller, but still triggers it after compiled.
As for the command, because I am using some other modules that require the win32com package, it does not work for me:

```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 493, in exec_module
  File "wmi.py", line 105, in <module>
ModuleNotFoundError: No module named 'win32com'
[18552] Failed to execute script 'test' due to unhandled exception!
```

Is that anyway to force it to only import afterwards? I currently have no way to replace those libraries that I use that uses the win32com package.

**Comment by rokm** [comment]
Hmm... if you need `win32com`, then I guess one way to work around the problem would be to edit the runtime hooks for [`pkg_resources`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py) and [`win32com`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_win32comgenpy.py) and add an `import bleak` at the top of each of them. This is the only way I can think of for ensuring that `bleak` is imported before `win32com` in a frozen application. (Another might be to create a runtime hook for `bleak` itself that does the import, but I don't think there is any control over the order in which runtime hooks are executed...).

This might have other ramifications, though; if `import bleak` causes any use of `pkg_resources` or `win32com` that would require the modified behavior (which is monkey-patched in by runtime hooks), then it won't work, either. You'll have to test and see...

**Comment by aliencaocao** [comment]
Tried to add `import bleak` into the 2 hooks and it seems to be working so far. No error when running exe and everything looks fine. However, I will need a bit more time to test out the stability of this 'hack' thus will keep this issue open for the time being. Thank you for your help.

**Comment by bwoodsend** [comment]
I think the ideal fix would be for runtime hooks targetting a particular library to not be loaded until just before they are imported. i.e. Nothing happens on startup, then when our `FrozenImporter` class recieves a request for `import pkg_resources`, it then runs the hook, imports the module and returns it. That would get us as close as we can get to *how it works unfrozen* and mean that the order than runtime hooks are loaded is deterministic on the order `import`s are given in-code.

**Comment by aliencaocao** [comment]
I find the hacky fix pretty stable, so you can close the issue if you wish (in case you want to leave it open for a future PR on the importing mechanism)

**Comment by aliencaocao** [comment]
I think I found a relevant issue to this but this issue never happened before.

When I'm building, pyinstall output these error:
```
C:\Program Files\Python39\lib\site-packages\pyglet\image\codecs\wic.py:289: UserWarning: [WinError -2147417850] 无法在设置线程模式后对其加以更改。(Cannot change thread mode after it is set)
  warnings.warn(str(err))
C:\Program Files\Python39\lib\site-packages\pyglet\media\codecs\wmf.py:838: UserWarning: [WinError -2147417850] 无法在设置线程模式后对其加以更改。(Cannot change thread mode after it is set)
  warnings.warn(str(err))
C:\Program Files\Python39\lib\site-packages\debugpy\_vendored\force_pydevd.py:20: UserWarning: incompatible copy of pydevd already imported:
 C:\Program Files\Python39\lib\site-packages\_pydev_bundle\__init__.py
  C:\Program Files\Python39\lib\site-packages\_pydev_imps\__init__.py
  C:\Program Files\Python39\lib\site-packages\_pydevd_bundle\__init__.py
  C:\Program Files\Python39\lib\site-packages\_pydevd_frame_eval\__init__.py
  C:\Program Files\Python39\lib\site-packages\pydev_ipython\__init__.py
  C:\Program Files\Python39\lib\site-packages\pydevd_concurrency_analyser\__init__.py
  C:\Program Files\Python39\lib\site-packages\pydevd_plugins\__init__.py
  C:\Program Files\Python39\lib\site-packages\pydevd_plugins\extensions\__init__.py
  warnings.warn(msg + ':\n {}'.format('\n  '.join(_unvendored)))
```

Although the compiled exe is still working, but I'm not sure if these warnings are safe to ignore as they have never appeared before. I did upgrade some libraries recently but I cant remember which as I upgraded them many times.

EDIT: I removed the pydevd-pycharm and the error is gone. Might be a incompatibility issue.

**Comment by aliencaocao** [comment]
This seem to be resolved by https://github.com/hbldh/bleak/pull/709
I just tested with pyinstaller latest development build, and without any workarounds, it works perfectly.

**Comment by bwoodsend** [comment]
I'll take your word for it.
