### ISSUE TITLE
pywintypes is not frozen correctly when PyInstaller is run from a virtualenv

### ISSUE THREAD

**Issue by glennra** [pyinstaller/pyinstaller#6206]
When a program that uses pywin32 is packaged (onedir mode) while running Python from a virtualenv the resulting exe fails to start with the following error:
<pre>
[9468] LOADER: Running lineedit.py
import pywintypes # PyInstaller PYZ
Traceback (most recent call last):
  File "lineedit.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "pywintypes.py", line 105, in <module>
  File "pywintypes.py", line 38, in __import_pywin32_system_module__
ImportError: Module 'pywintypes' isn't in frozen sys.path
</pre>
If the same program is packaged using the system Python then it runs as expected.

Example program:
<pre>
import pywintypes
import wmi
c = wmi.WMI()
print(c.Win32_ComputerSystem()[0])
</pre>
When run from the virtualenv PyInstaller doesn't include pywintypes38.dll or pythoncom38.dll in the package dir.

Using PyInstaller 4.5, Python 3.8.10 on Windows 10 19043 for this example, but it's not version specific.

**Comment by rokm** [comment]
I cannot reproduce this; `pywintypes38.dll` and `pythoncom38.dll` are properly collected from a virtual environment, and the frozen example program works. Can you double-check your environment(s) and perhaps try in a completely clean setup?

**Comment by glennra** [comment]
I deleted and recreated my virtualenv using `virtualenv venv`, which uses the Python 3.8 from my PATH.
Installed pefile, altgraph and pywin32-ctypes for PyInstaller in that virtualenv using pip.
Still the same result. What environment things should I be checking?

**Comment by rokm** [comment]
> I deleted and recreated my virtualenv using `virtualenv venv`

Are you using `venv` (provided directly by python3) or `virtualenv` (external package for python2/python3) for your virtual environment?

Can you re-run pyinstaller command with `--log-level DEBUG` and attach the output?

**Comment by filak** [comment]
I have also experienced this with Win10, Python 3.10.1 and 

    pyinstaller==5.4.1
    pywin32==304

installed in venv.

After upgrading pyinstaller to 5.4.1 in the system Python and rebuilding the exes just work fine.
