### ISSUE TITLE
the influence for limit the memory of the python interpreter （32-bytes）to use pyinstaller

### ISSUE THREAD

**Issue by zfy108** [pyinstaller/pyinstaller#6212]
my program depends on large memory, before using pyinstaller, there is some questions for memory error(1.0G), after using pyinstaller, there is no question any more (1.5G). after using pyinstaller ,my program can run successfully. but i don't konw why.
I want to know how to influence python interpreter（32-bytes） for pyinstaller to enlarge memory
any infomation will be appreciated.

**Comment by rokm** [comment]
Please do not open duplicate issues/questions. They will not get answered any faster.
