### ISSUE TITLE
self contain PyInstaller to run on other computer (and/or from USB)

### ISSUE THREAD

**Issue by drakeredwind01** [pyinstaller/pyinstaller#6213]
**description.**
I got the PyInstaller to work perfectly with only the ".exe" file in an alt location on my computer, but then I tried to transfer it via remote access to my desktop, and it didn't work.

**Describe the solution/alternatives you'd like**
Can you please add 2 options: 
    add more data to the ".exe" file to run standalone on an alt computer (no python installed) or from a USB. or...
    add a "virtual python" or "virtual anaconda" to be placed next to the .exe (or somewhere else) that the .exe can use to run 
        properly

**Additional context**
This is my first enhancement request, and I hope I did this properly.
I also hope Github notifies me if this is responded to.
If it doesn't, you can reach me at drakeredwind01@gmail.com
or even sooner by commenting on one of my videos
    https://www.youtube.com/channel/UCvPJKxcTz0h8aP4OgLTFqvw?sub_confirmation=1
    promise I'm not just trying to promote my stuff

**Comment by rokm** [comment]
You're not giving us much to work with here...

> I got the PyInstaller to work perfectly with only the ".exe" file in an alt location on my computer, but then I tried to transfer it via remote access to my desktop, and it didn't work.

What was the error message?

> add more data to the ".exe" file to run standalone on an alt computer (no python installed) or from a USB. or...

What data would that be?

> add a "virtual python" or "virtual anaconda" to be placed next to the .exe (or somewhere else) that the .exe can use to run
properly

Why not just install python or anaconda (or transfer a virtual environment) to the alt computer, then?

---

It sounds like you ended up with an incomplete frozen bundle that's missing one or more files that are available on your build system but not on the other one. There are various reasons why that might happen, but without seeing the error message or knowing what your program does (what packages it uses), we cannot really help you there...
