### ISSUE TITLE
Weird issue when adding product version information.

### ISSUE THREAD

**Issue by jawhien** [pyinstaller/pyinstaller#6219]
## Description of the issue

When building I try to set product information, name and version, and although everything is displayed fine in the file properties, NVDA, the screen reader I use, also reads this information, but for some reason it is wrong, although this does not happen with any other applications.
As a result, the product name looks something like this:
'Myprogram\x00\x004\x10\x01Prod'

I tried to manually create the resource file, compiled it using visual studio, and manually replaced it. After that, the problem went away.

### Context information (for bug reports)

* Output of `pyinstaller --version`: 4.5.1, 5.0.dev0
* Version of Python: 3.7.9, 32bit
* Platform: Windows 7
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?
No, I haven't tried it.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> When building I try to set product information, name and version, and although everything is displayed fine in the file properties, NVDA, the screen reader I use, also reads this information, but for some reason it is wrong, although this does not happen with any other applications.

Any chance you can provide the file-version file that you used to build the program?

When you say "this does not happen with any other application", do you mean that product info is correctly displayed (read out) for other (non-pyinstaller-built) applications? Or that applications other than NVDA correctly display the product information of your built application?

> As a result, the product name looks something like this:
> 'Myprogram\x00\x004\x10\x01Prod'

Is this what NVDA reads out? If so, when (e.g., when you hover mouse over executable, or something else)? Or is this string displayed somewhere?

**Comment by jawhien** [comment]
> 
> Any chance you can provide the file-version file that you used to build the program?
> 

yes, I used the following file:

VSVersionInfo(
ffi=FixedFileInfo(
filevers=(0, 1, 0, 2),
prodvers=(0, 1, 0, 2),
mask=0x3f,
flags=0x0,
OS=0x40004,
fileType=0x1,
subtype=0x0,
date=(0, 0)),
kids=[StringFileInfo([StringTable(
u'040904B0',[
StringStruct(u'FileDescription', u'Myprogram'),
StringStruct(u'FileVersion', u'0.1.0.2'),
StringStruct(u'InternalName', u'Myprogram'),
StringStruct(u'LegalCopyright', u'Copyright'),
StringStruct(u'OriginalFilename', u'myprogram.exe'),
StringStruct(u'ProductName', u'Myprogram'),
StringStruct(u'ProductVersion', u'0.1.0.2'),
StringStruct(u'Language', u'Language Neutral'),
StringStruct(u'LegalTrademarks', u'Myprogram')])]),
VarFileInfo([VarStruct(u'Translation', [1033, 1200])])])

> When you say "this does not happen with any other application", do you mean that product info is correctly displayed (read out) for other (non-pyinstaller-built) applications? 

Yes, NVDA displays information about other applications correctly, even when I was building them with py2exe or cx_freeze.> 

> Is this what NVDA reads out? If so, when (e.g., when you hover mouse over executable, or something else)? Or is this string displayed somewhere?

Usually keyboard shortcuts are used to get this information when the application is in the foreground, but it's easier to look at it in the developer information by pressing INSERT + F1, this is what is displayed for my application:

...
appModule.productName: 'Myprogram\x004\x10\x01Produc'
appModule.productVersion: '0.1.0.2\x00:"\x01Lang'
...

And this is how it is displayed in other applications, for example Github desktop

...
appModule.productName: 'GitHub Desktop'
appModule.productVersion: '2.9.3'
...

**Comment by rokm** [comment]
Thanks for the additional info! I've reproduced the problem with a self-contained example based on the NVDA code.
