### ISSUE TITLE
WindowsError: [Error 3] in some exe

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#622]
**Original date**: 2012/10/26
**Original reporter**: *seewindcn AND gmail DOT  COOM *

some exe make by pyinstaller 2.0, run will raise error:
Traceback (most recent call last):
  File "<string>", line 38, in <module>
WindowsError: [Error 3] : 'C:\\Users\\jcc\\AppData\\Local\\Temp\\_MEI62842\\eggs
/*.*'

I fix it by modify pyinstaller-2.0\support\_pyi_egg_install.py:
+if os.path.exists(d):
    for fn in os.listdir(d):
        sys.path.append(os.path.join(d, fn))

**Comment by matysek** [comment]
This is already fixed. There is already check if 'egg' directory exists.

**Comment by matysek** [comment]
This is already fixed. There is a check if an `egg` directory exists.
