### ISSUE TITLE
ImportError: DLL load failed while importing _core: The specified procedure could not be found.

### ISSUE THREAD

**Issue by JustinDBruce** [pyinstaller/pyinstaller#6229]
I am trying to build a python program with pyinstaller. When I run "python main.py" the program runs fine, but when I make an exe with pyinstaller I get the following error:
Traceback (most recent call last):
File "main.py", line 8, in
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "scrcpy_init_.py", line 6, in
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "scrcpy\core.py", line 12, in
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "av_init_.py", line 9, in
ImportError: DLL load failed while importing _core: The specified procedure could not be found.
[9264] Failed to execute script 'main' due to unhandled exception!

*If this helps my ide is showing that it cannot find the declaration to go to on CodecContext:
from av.codec import CodecContext

From what I have read I needed to make sure the the ffmpeg bin was added to the path, but I am still getting the same error. Any help on this would be great! Thanks!
Also if there is anything else you want me to post just let me know.

### Context information (for bug reports)

* Output of `pyinstaller --version`:  4.5.1
* Version of Python: 3.9.7
* Platform: Windows 10
* How you installed Python: Windows store

**Comment by rokm** [comment]
`The specified procedure could not be found.` usually means that an incompatible version of a DLL ended up being collected...

Can you attach `build\<name>\Analysis-00.toc` so we can check where the files are being collected from?

Also, are you using `upx` by any chance?

**Comment by JustinDBruce** [comment]
[Analysis-00.txt](https://github.com/pyinstaller/pyinstaller/files/7203536/Analysis-00.txt)
 
I don't think I'm using upx, the program I am trying to convert is https://github.com/leng-yue/py-scrcpy-client if that helps at all.

**Comment by rokm** [comment]
Hmm... well, for start, this looks suspicious:

```
  ('avcodec-58.dll',
   'C:\\Users\\Justin\\Desktop\\Augmentalis\\py\\scrcpy_ui\\avcodec-58.dll',
   'BINARY'),
  ('avutil-56.dll',
   'C:\\Users\\Justin\\Desktop\\Augmentalis\\py\\scrcpy_ui\\avutil-56.dll',
   'BINARY'),
  ('avformat-58.dll',
   'C:\\Users\\Justin\\Desktop\\Augmentalis\\py\\scrcpy_ui\\avformat-58.dll',
   'BINARY'),
  ('swscale-5.dll',
   'C:\\Users\\Justin\\Desktop\\Augmentalis\\py\\scrcpy_ui\\swscale-5.dll',
   'BINARY'),
  ('swresample-3.dll',
   'C:\\Users\\Justin\\Desktop\\Augmentalis\\py\\scrcpy_ui\\swresample-3.dll',
   'BINARY'),
  ('avdevice-58.dll',
   'C:\\Users\\Justin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\av\\avdevice-58.dll',
   'BINARY'),
  ('avfilter-7.dll',
   'C:\\Users\\Justin\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python39\\site-packages\\av\\avfilter-7.dll',
   'BINARY'),
```

So some of your `av` DLLs are coming from the `av` package itself, and some of them are coming from `C:\Users\Justin\Desktop\Augmentalis\py\scrcpy_ui`. Where did the DLLs in  `C:\Users\Justin\Desktop\Augmentalis\py\scrcpy_ui` come from?

But if this is a public code, can you attach an archive with the generated onedir bundle, so I can take a look at it? It might be easier to debug that way...

**Comment by JustinDBruce** [comment]
Thanks for the hint. I was able to resolve this issue, by removing the DLL I had placed in there. It was weird, I needed them in there to run the python command, but not when running pyinstaller. 
Thank you for the help!
