### ISSUE TITLE
我用pyinstaller打包成exe，总是卡在：25555 INFO: Building PKG (CArchive) PKG-00.pkg 这 ，并且会不停的申请内存，导致所在盘的空间被占满，请问一下这是怎么回事？

### ISSUE THREAD

**Issue by pjx2019** [pyinstaller/pyinstaller#6232]
![image](https://user-images.githubusercontent.com/53468203/134268153-7c5b14b9-1ad9-453a-a38e-2b9c21b91182.png)

**Comment by rokm** [comment]
Without an example to reproduce this issue, we cannot really help you.

But I see two possibilities here:

a) PKG building step is stuck in an infinite loop for some reason. You could verify this by adding additional `logger.info()` or `print()` statements to the affected codepath, for example [here](https://github.com/pyinstaller/pyinstaller/blob/54083110106d2c20e45364d1f98457880dcbd31e/PyInstaller/building/api.py#L234) and [here](https://github.com/pyinstaller/pyinstaller/blob/54083110106d2c20e45364d1f98457880dcbd31e/PyInstaller/archive/writers.py#L341).

b) you are accidentally pulling in more data than you intended (which I think is more likely). That should be visible from those extra `print()` statements from (a), but you could probably also check `build\<main>\Analysis-00.toc` and/or `build\<main<\PKG-00.toc` to see what files are being collected.

**Comment by eric15342335** [comment]
Or maybe just the OP is using Anaconda and packaging

**Comment by eric15342335** [comment]
I guess the reason is running PyInstaller inside a anaconda environment will likely pack many of the unnecessary dependencies, resulting a large .pkg file. If the user is using hard disk, it will take a long time to load.

@pjx2019 Can you try to pack your app inside a [python.org](https://python.org) python environment?

**Comment by pjx2019** [comment]
> 我想原因是在 anaconda 环境中运行 PyInstaller 可能会打包许多不必要的依赖项，从而导致一个很大的 .pkg 文件。如果用户使用硬盘，加载时间会比较长。
> 
> @pjx2019您可以尝试将您的应用程序打包到[python.org](https://python.org) python 环境中吗？

Thank you very much for your reply. I cleared everything. It's OK to repack it. It may be affected by the cache or. Spec file

**Comment by pjx2019** [comment]
> 我想原因是在 anaconda 环境中运行 PyInstaller 可能会打包许多不必要的依赖项，从而导致一个很大的 .pkg 文件。如果用户使用硬盘，加载时间会比较长。
> 
> @pjx2019您可以尝试将您的应用程序打包到[python.org](https://python.org) python 环境中吗？

Thank you very much for your reply. I cleared everything. It's OK to repack it. It may be affected by the cache or. Spec file
