### ISSUE TITLE
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by JustinDBruce** [pyinstaller/pyinstaller#6236]
I am building a project and running into an issue. I'm at a loss because when I build with "pyinstaller --noconsole main.py" the program runs fine. It also runs fine when building with " pyinstaller --onefile main.py". But when I use "pyinstaller --noconsole --onefile main.py" its seems my adb starts to have issues. Error below:

Traceback (most recent call last):
  File "adbutils\__init__.py", line 103, in _safe_connect
  File "adbutils\__init__.py", line 95, in _create_socket
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 185, in <module>
  File "click\core.py", line 1137, in __call__
  File "click\core.py", line 1062, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 763, in invoke
  File "main.py", line 176, in main
  File "main.py", line 32, in __init__
  File "main.py", line 78, in list_devices
  File "adbutils\__init__.py", line 462, in device_list
  File "adbutils\__init__.py", line 443, in iter_device
  File "adbutils\__init__.py", line 189, in _connect
  File "adbutils\__init__.py", line 88, in __init__
  File "adbutils\__init__.py", line 105, in _safe_connect
  File "adbutils\__init__.py", line 81, in adb_path
  File "adbutils\_utils.py", line 42, in get_adb_exe
RuntimeError: No adb exe could be found. Install adb on your system
os.path.dirname(os.path.abspath(__file__)) = C:\Users\Justin\AppData\Local\Temp\_MEI188722\adbutils
bin_dir = C:\Users\Justin\AppData\Local\Temp\_MEI188722\adbutils\binaries
exe =bin_dir\adb.exe

This is what I am working with https://github.com/leng-yue/py-scrcpy-client if that helps
I also altered the adb utils to give me the Runtime printout. Any help on this would be outstanding, Thanks!

* Output of `pyinstaller --version`: 4.5.1
* Version of Python: 3.9.7
* Platform:  Windows 10
* How you installed Python: Windows store

**Comment by rokm** [comment]
WIth `adb.exe` collected, either via spec or via the hook from pyinstaller/pyinstaller-hooks-contrib#323, the onefile + windowed variant still doesn't work. That's not our bug, though, but rather `adbutils`': their [_is_valid_exe](https://github.com/openatx/adbutils/blob/dccec86376ab3fd741cfedb62c0c9b71a58b4877/adbutils/_utils.py#L66-L75) function is failing in onefile+noconsole mode, because they do not redirect the stdin in the `subprocess` call (so it ends up with an invalid handle). 

Adding `stdin=subprocess.DEVNULL` to the list of arguments to `subprocess.check_call()` should fix the problem.

I'm not sure why it does not exhibit the same problem in onedir + noconsole mode, though...

**Comment by JustinDBruce** [comment]
That was not able to solve the issue.
Looking at these lines in _utils:
    # 2. use buildin adb
    bin_dir = resource_filename("adbutils", "binaries")
    exe = os.path.join("bin_dir", "adb.exe" if os.name == 'nt' else 'adb')
    if os.path.isfile(exe) and _is_valid_exe(exe):
        return exe

    raise RuntimeError("No adb exe could be found. Install adb on your system" + "\nos.path.dirname(os.path.abspath(__file__)) = " + os.path.dirname(os.path.abspath(__file__)) + 
     "\nbin_dir = " + bin_dir + "\nexe =" + exe)

and looking at what the output of the Runtime error is:
    RuntimeError: No adb exe could be found. Install adb on your system
    os.path.dirname(os.path.abspath(file)) = C:\Users\Justin\AppData\Local\Temp_MEI188722\adbutils
    bin_dir = C:\Users\Justin\AppData\Local\Temp_MEI188722\adbutils\binaries
    exe =bin_dir\adb.exe

and then looking in that temp dir, there is no adbutils folders or binaries folder. However, there is the exe and the dlls that it is looking for. I am trying to figure out how to alter it to not look into the folder and look at it just for the exe, any suggestions would be cool.

**Comment by rokm** [comment]
Can you try changing [this `return False`](https://github.com/openatx/adbutils/blob/dccec86376ab3fd741cfedb62c0c9b71a58b4877/adbutils/_utils.py#L75) into `raise` - do you now get exception about invalid handle?

**Comment by rokm** [comment]
> and then looking in that temp dir, there is no adbutils folders or binaries folder. However, there is the exe and the dlls that it is looking for.

That's probably from your attempt to add the files via .spec; but you aren't putting them in the correct place (i.e.,  `adbutils\binaries` subdirectory).

**Comment by JustinDBruce** [comment]
> > and then looking in that temp dir, there is no adbutils folders or binaries folder. However, there is the exe and the dlls that it is looking for.
> 
> That's probably from your attempt to add the files via .spec; but you aren't putting them in the correct place (i.e., `adbutils\binaries` subdirectory).

I removed the line in the spec file, still getting the same path names. Still working on this, just thought I would give an update.

**Comment by rokm** [comment]
Try making a `onedir` build first, and check if you have `dist\<name>\adbutils\binaries` directory with `adb.exe` and `adb*.dll` files in it. If not, you need to update your `pyinstaller-hooks-contrib` to git master (or just save the `hook-adbutils.py` hook from pyinstaller/pyinstaller-hooks-contrib#323 into either `[venv]\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\` or `[venv]\Lib\site-packages\PyInstaller\hooks\`.

Once your `onedir` bundles have `adb.exe` properly collected, move on to solving the onefile+windowed issue.

**Comment by JustinDBruce** [comment]
> Try making a `onedir` build first, and check if you have `dist\<name>\adbutils\binaries` directory with `adb.exe` and `adb*.dll` files in it. If not, you need to update your `pyinstaller-hooks-contrib` to git master (or just save the `hook-adbutils.py` hook from [pyinstaller/pyinstaller-hooks-contrib#323](https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/323) into either `[venv]\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\` or `[venv]\Lib\site-packages\PyInstaller\hooks\`.
> 
> Once your `onedir` bundles have `adb.exe` properly collected, move on to solving the onefile+windowed issue.

yes, I updated the pyinstaller-hooks-contrib. The adbutils folder is there. The problem I am seeing is that the adb _utils.py is looking for adb.exe in a temp folder "C:\Users\Justin\AppData\Local\Temp_MEI188722\adbutils\binaries"(where the adbutils and binaries folders do not exist) instead of in the exe and I'm not sure how to rectify that.

**Comment by rokm** [comment]
> yes, I updated the pyinstaller-hooks-contrib. The adbutils folder is there. 

By "there", you mean that adbutils\binaries directory is collected in `onedir` bundle?

> The problem I am seeing is that the adb _utils.py is looking for adb.exe in a temp folder "C:\Users\Justin\AppData\Local\Temp_MEI188722\adbutils\binaries"(where the adbutils and binaries folders do not exist) instead of in the exe and I'm not sure how to rectify that.

What do you mean "instead of in the exe"? When you make a onefile bundle and run it, it unpacks into a temporary directory (and cleans it up after it stops running). So `adbutils` is correctly looking for `adb.exe` in "C:\Users\Justin\AppData\Local\Temp_MEI188722\adbutils\binaries", because it should end being up unpacked there. 

If it was correctly collected into `adbutils\binaries`  for `onedir` bundle, it should also be for `onefile` bundle. Otherwise, you might be testing with an old (or partially outdated) build - try removing `dist` and `build` folders, and rebuild (or rebuild with `--clean` flag).

**Comment by JustinDBruce** [comment]
Okay, I did as you said and the folders where there this time. It still gave me this error.

Traceback (most recent call last):
  File "adbutils\__init__.py", line 103, in _safe_connect
  File "adbutils\__init__.py", line 95, in _create_socket
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 185, in <module>
  File "click\core.py", line 1137, in __call__
  File "click\core.py", line 1062, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 763, in invoke
  File "main.py", line 176, in main
  File "main.py", line 32, in __init__
  File "main.py", line 78, in list_devices
  File "adbutils\__init__.py", line 462, in device_list
  File "adbutils\__init__.py", line 443, in iter_device
  File "adbutils\__init__.py", line 189, in _connect
  File "adbutils\__init__.py", line 88, in __init__
  File "adbutils\__init__.py", line 105, in _safe_connect
  File "adbutils\__init__.py", line 81, in adb_path
  File "adbutils\_utils.py", line 42, in get_adb_exe
RuntimeError: No adb exe could be found. Install adb on your system
os.path.dirname(os.path.abspath(__file__)) = C:\Users\Justin\AppData\Local\Temp\_MEI178762\adbutils
bin_dir = C:\Users\Justin\AppData\Local\Temp\_MEI178762\adbutils\binaries
exe =bin_dir\adb.exe
 cwdC:\Users\Justin\Desktop\Augmentalis\py-scrcpy-client-main\scrcpy_ui\dist

**Comment by rokm** [comment]
If the `adb.exe` is now in the right place, then `_is_valid_exe()` is failing to validate it due to the invalid stdin error.

**Comment by JustinDBruce** [comment]
yes I saw where you were wanting to change some code. 
def _is_valid_exe(exe: str):
    cmd = [exe, "version"]
    try:
        subprocess.check_call(
            cmd, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
            stderr=subprocess.STDOUT, **_popen_kwargs()
        )
        return True
    except (OSError, ValueError, subprocess.CalledProcessError):
        return False

That is what I currently have.

**Comment by rokm** [comment]
Hmm, it should work, then...

What if you change that `return False` into a `raise`, so it re-raises exception? Do you see the re-raised exception instead of the previous `RuntimeError` now?

**Comment by JustinDBruce** [comment]
Yes still get the Run time error.

Traceback (most recent call last):
  File "adbutils\__init__.py", line 103, in _safe_connect
  File "adbutils\__init__.py", line 95, in _create_socket
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 185, in <module>
  File "click\core.py", line 1137, in __call__
  File "click\core.py", line 1062, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 763, in invoke
  File "main.py", line 176, in main
  File "main.py", line 32, in __init__
  File "main.py", line 78, in list_devices
  File "adbutils\__init__.py", line 462, in device_list
  File "adbutils\__init__.py", line 443, in iter_device
  File "adbutils\__init__.py", line 189, in _connect
  File "adbutils\__init__.py", line 88, in __init__
  File "adbutils\__init__.py", line 105, in _safe_connect
  File "adbutils\__init__.py", line 81, in adb_path
  File "adbutils\_utils.py", line 42, in get_adb_exe
RuntimeError: No adb exe could be found. Install adb on your system

def _is_valid_exe(exe: str):
    cmd = [exe, "version"]
    try:
        subprocess.check_call(
            cmd, stdin=subprocess.DEVNULL, stdout=subprocess.DEVNULL,
            stderr=subprocess.STDOUT, **_popen_kwargs()
        )
        return True
    except (OSError, ValueError, subprocess.CalledProcessError):
        raise

**Comment by rokm** [comment]
In that case, can you undo the `raise`, and instead modify the [RuntimeError thrown in the `get_adb_exe`](https://github.com/openatx/adbutils/blob/dccec86376ab3fd741cfedb62c0c9b71a58b4877/adbutils/_utils.py#L41) to include the return values of `os.path.isfile(exe)` and `_is_valid_exe(exe)`?

E.g.,
```python
raise RuntimeError(f"No adb exe could be found. Install adb on your system. is_file={os.path.isfile(exe)}, is_valid={_is_valid_exe(exe)}")
```

**Comment by JustinDBruce** [comment]
I just want to apologize for being a jr. dev. You have been awesome. At some point in my fiddling this line 

exe = os.path.join(bin_dir, "adb.exe" if os.name == 'nt' else 'adb')

got changed to 

exe = os.path.join("bin_dir", "adb.exe" if os.name == 'nt' else 'adb')

However the fight is not over. Adb does start now, but this is getting thrown 

Traceback (most recent call last):
  File "main.py", line 185, in <module>
  File "click\core.py", line 1137, in __call__
  File "click\core.py", line 1062, in main
  File "click\core.py", line 1404, in invoke
  File "click\core.py", line 763, in invoke
  File "main.py", line 179, in main
  File "core.py", line 148, in start
  File "core.py", line 112, in __deploy_server
  File "adbutils\__init__.py", line 615, in push
  File "adbutils\__init__.py", line 545, in adb_output
  File "subprocess.py", line 424, in check_output
  File "subprocess.py", line 505, in run
  File "subprocess.py", line 829, in __init__
  File "subprocess.py", line 1252, in _get_handles
OSError: [WinError 6] The handle is invalid

I'm looking into it now. Again thanks for being awesome.

**Comment by JustinDBruce** [comment]
Closing. Follow on error is not in scope.

**Comment by rokm** [comment]
> File "subprocess.py", line 424, in check_output
> File "subprocess.py", line 505, in run
> File "subprocess.py", line 829, in **init**
> File "subprocess.py", line 1252, in _get_handles
> OSError: [WinError 6] The handle is invalid

This looks like another case where `subprocess.check_output()` needs its `stdin` redirected to `devnull`...

**Comment by JustinDBruce** [comment]
@rokm Thanks for the continued help! Everything seems to be running now!
