### ISSUE TITLE
set_dynamic_library_path change breaks plugin library use

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#625]
**Original date**: 2012/11/01
**Original reporter**: *Stuart_Mentzer AND objexx DOT  COOM *

A change in PyInstaller 2.0 overwrites the LD_LIBRARY_PATH environment variable on Linux platforms. This breaks the ability to modify the shared library search path and then restart an application, which is a necessary "trick" on Linux to get a user-specified path added to the search path for such use cases as user-generated plugin libraries. The alternative of a wrapper script is not desirable for a production application that must run on a variety of systems that may use different shells.

The issue was discussed in this [Mailing List Discussion](https://groups.google.com/forum/?fromgroups=#!topic/PyInstaller/VemnB7renD8) where I showed this patch for Linux that adds the needed path to the front of LD_LIBRARY_PATH without discarding the existing value. The AIX platform was not addressed by this patch.

```
static int set_dynamic_library_path(const char* path)
{
    int rc = 0;

#ifdef AIX
    /* LIBPATH is used to look up dynamic libraries on AIX. */
    setenv("LIBPATH", path, 1);
    VS("%s\n", path);
#else
    /* LD_LIBRARY_PATH is used on other *nix platforms (except Darwin). */
    char * curpath = getenv("LD_LIBRARY_PATH");
    if ( ! curpath ) { /* Use required path only */
        rc = setenv("LD_LIBRARY_PATH", path, 1);
        VS("%s\n", path);
    } else { /* Append current path onto required path */
        char apath[ strlen(path) + strlen(curpath) + 2 ];
        strcpy(apath, path);
        strcat(apath, ":");
        strcat(apath, curpath);
        rc = setenv("LD_LIBRARY_PATH", apath, 1);
        VS("%s\n", apath);
    }
#endif /* AIX */

    return rc;
}
```

**Comment by ThomasWaldmann** [comment]
I made PR #2148 to fix this, please review.
