### ISSUE TITLE
numpy Matrix multiplication 

### ISSUE THREAD

**Issue by shankslee2021** [pyinstaller/pyinstaller#6262]
python3.8.8
win10 pro

pyinstaller 4.5.1
info：
  File "numpy\matrixlib\defmatrix.py", line 218, in __mul__
  File "<__array_function__ internals>", line 5, in dot
ValueError: shapes (1,0) and (2,406) not aligned: 0 (dim 1) != 2 (dim 0)
[2292] Failed to execute script 'begin' due to unhandled exception!

numpy Matrix multiplication ，Is it not supported?

**Comment by bwoodsend** [comment]
Please fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by rokm** [comment]
>  ValueError: shapes (1,0) and (2,406) not aligned: 0 (dim 1) != 2 (dim 0)

This looks like an attempt to multiply matrices with incompatible dimensions, and not a PyInstaller problem...
