### ISSUE TITLE
sign app on OS X

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#627]
**Original date**: 2012/11/05
**Original reporter**: *Giuseppe Di Martino*

On Apple OS X Snow Leopard I tried to sign a pyinstaller's application by command:
codesign -s XYZ myprogram.app

obtaining the error: 
codesign_allocate: object: myprogram.app/Contents/MacOS/prog malformed object (unknown load command 8)
myprogram.app: object file format invalid or unsuitable

Where XYZ is a valid code signing certificate, myprogram.app is the bundled application and myprogram.app/Contents/MacOS/prog is the executable file generated by pyinstaller

Does code signing on OS X is supported in pyinstaller?
PS: in Windows I had no problems signing the application.

Regards,
Giuseppe

**Comment by matysek** [comment]
Code signing on OSX is already implemented. Closing. See #812 for details.
