### ISSUE TITLE
python-telegram-bot --> pkg_resources.DistributionNotFound

### ISSUE THREAD

**Issue by fabioparodi** [pyinstaller/pyinstaller#6272]
## Description of the issue
I am using the library python-telegram-bot , it works fine from sources, but then when I user Pyinstaller, it reports errors like: 
`pkg_resources.DistributionNotFound: The 'xxx>=yyy' distribution was not found and is required by the application`
Where _xxx_ is in { six, tzlocal, pytz, setuptools } at random.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: Python 3.9.7 (tags/v3.9.7:1016ef3, Aug 30 2021, 20:05:41) [MSC v.1929 32 bit (Intel)] on win32
* Platform: <windows 10 ITA>
* How you installed Python: <python.org/downloads>
* Did you also try this on another platform? Does it work there?
also tried the 64 bit python, and another windows PC, same problem

* I've tried the the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import telegram.ext
updater = telegram.ext.Updater(token="2234234492:AAGAplU3AIdH_zvTXh1D30sdfgrerwfTz-0")
updater.dispatcher.job_queue.run_once(lambda context: print("hello world"), 0)
updater.start_polling()
updater.idle()
```

### Stacktrace / full error message

Build the script with the simple instruction:
`python -m PyInstaller test.py`
Run the resulting program:
```
dist\test\test.exe
Traceback (most recent call last):
  File "apscheduler\schedulers\base.py", line 896, in _create_plugin_instance
KeyError: 'date'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 3, in <module>
    updater.dispatcher.job_queue.run_once(lambda context: print("hello world"), 0)
  File "telegram\ext\jobqueue.py", line 196, in run_once
  File "apscheduler\schedulers\base.py", line 420, in add_job
  File "apscheduler\schedulers\base.py", line 921, in _create_trigger
  File "apscheduler\schedulers\base.py", line 899, in _create_plugin_instance
  File "pkg_resources\__init__.py", line 2449, in load
  File "pkg_resources\__init__.py", line 2472, in require
  File "pkg_resources\__init__.py", line 772, in resolve
pkg_resources.DistributionNotFound: The 'six>=1.4.0' distribution was not found and is required by the application
[17068] Failed to execute script 'test' due to unhandled exception!
```

I've also contacted the telegram bot team, they say the issue is in PyInstaller and they cannot provide support. I have several applications running with PyInstaller and suspect the problem is somewhere in between, so I am willing to spend some time and help if you could provide some hints.

Thanks and regards

Fabio Parodi

**Comment by rokm** [comment]
Try adding `--copy-metadata six` to your PyInstaller command.

**Comment by rokm** [comment]
Or rather, as I see there are several packages whose metadata are queried, try `--recursive-copy-metadata apscheduler` instead.

**Comment by bwoodsend** [comment]
I see that `apscheduler/schedulers/base.py` [is using entry points](https://github.com/agronholm/apscheduler/blob/71c698053524b8d0da52970ddeefa65fb764023d/apscheduler/schedulers/base.py#L66-L71) so, unless you don't actually need any aspscheduler plugins, you'll probably need to collect the entry points' providers using [collect_entry_point()](https://pyinstaller.readthedocs.io/en/v4.5.1/hooks.html#PyInstaller.utils.hooks.collect_entry_point) but that's more complex because there is no command line switch for it.

**Comment by fabioparodi** [comment]
@rokm: 
`--copy-metadata six` did not work.
`--recursive-copy-metadata apscheduler` did work. My script is now frozen and running, thanks!
I have seen PyInstaller has inserted two new lines in the spec file:
```
datas = []
datas += copy_metadata('apscheduler')
```

@bwoodsend:
I did not really understand how to use `collect_entry_point()`. I am going to stop investigation since my problem is solved anyway. If you want me to dig deeper please let me know, I am willing to help.
