### ISSUE TITLE
Wishlist quick search

### ISSUE THREAD

**Issue by 82d** [pyinstaller/pyinstaller#6279]
I think this will greatly speed up and facilitate the process when I most often need to press this button to check if there is any track in the list. then it is searched immediately when typing the first letters of the name. I won't have to press tab every time, and besides, I don't need to copy the result to add it to the list when it's not there.

**Comment by bwoodsend** [comment]
Uhmm, what are you talking about? Searching what? What do you mean by * *track in the list*? Is this even PyInstaller related?

**Comment by 82d** [comment]
I'm sorry the wrong topic
