### ISSUE TITLE
setWindowCommand in qt4

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#628]
**Original date**: 2012/11/14
**Original reporter**: _anonymous_

Simple Qt Application:

``` python
from PyQt4 import QtGui, QtCore
import sys, atexit

class ApplicationWindow(QtGui.QMainWindow):
    def __init__(self):
        QtGui.QMainWindow.__init__(self)
        self.setAttribute(QtCore.Qt.WA_DeleteOnClose)
        self.setWindowTitle("application main window")
        self.file_menu = QtGui.QMenu('&File', self)
        self.menuBar().addMenu(self.file_menu)
        self.menuBar().addSeparator()

        self.main_widget = QtGui.QWidget(self)

qApp = QtGui.QApplication(sys.argv)
aw = ApplicationWindow()   
aw.show()
sys.exit(qApp.exec_())
qApp.exec_()
```

Run's without a problem and I can build an exe using pyInstaller which also runs fine.

I add the lines:

``` python
iconfile = QtGui.QIcon('C:/pyinstaller/img/image1.png')

aw.setWindowIcon() 
```

Just before `aw.show()` (also tried in other places throughout the code)

This run's fine as a python file but when built using pyInstaller the exe crashes at run-time, I've tried using resource files and other image formats but the problem remains.

**Comment by htgoebel** [comment]
I'm closing this ticket. It is years old, for a long outdated version PyInstaller, reported by anonymous, and nobody worked on it.
