### ISSUE TITLE
FileNotFoundError: [WinError 3] The system cannot find the path specified: path\\basicsr\\archs

### ISSUE THREAD

**Issue by gabanib22** [pyinstaller/pyinstaller#6281]
Hi,
I'm using BasicSR in my one of the desktop application.
and It's working and running fine on PyCharm.

But after converting it to EXE file using pyinstaller, I'm getting below error.
I also tried with setting --paths as virtual environment and with system 
please help me to resolve this as I've already spent a lot time..

Traceback (most recent call last):
File "yogeshbhaiDesktop.py", line 7, in
File "", line 991, in _find_and_load
File "", line 975, in _find_and_load_unlocked
File "", line 671, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "basicsr_init.py", line 3, in
File "", line 991, in _find_and_load
File "", line 975, in find_and_load_unlocked
File "", line 671, in load_unlocked
File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
File "basicsr\archs_init.py", line 14, in
File "basicsr\archs_init.py", line 14, in
File "basicsr\utils\misc.py", line 74, in _scandir
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'C:\Users\gbd\AppData\Local\Temp\_MEI45162\basicsr\archs'

Thanks in advance..

  `pyinstaller --version`: ```4.5.1```
* Version of Python: 3.8
* Platform: Windows
* How you installed Python: pyenv
* Did you also try this on another platform? Does it work there? : It workes on pyCharm, but giving me error after pyInstaller created .exe file

**Comment by eric15342335** [comment]
Try putting this on your project directory as ``hook-basicsr.py``:
```python
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files("basicsr", includes=["archs/*_arch.py"])
```
and add ``--additional-hooks-dir .`` to your PyInstaller command-line.
Does it works?

**Comment by gabanib22** [comment]
Hi @eric15342335 ,
Thanks for your response,
I've tried with your solution.
`pyinstaller -w --additional-hooks-dir hook-basicsr.py --onefile yogeshbhaiDesktop.py`

but still getting same error :-(
It Doesn't work!

**Comment by eric15342335** [comment]
Hi @gabanib22 ,
You actually need to run ``--additional-hooks-dir .``  instead of  ``hook-basicsr.py`` .
Because the argument takes a relative path of a directory, not a file.

**Comment by bwoodsend** [comment]
Make that:
`pyinstaller -w --additional-hooks-dir hook-basicsr.py --onefile --clean yogeshbhaiDesktop.py`
PyInstaller doesn't detect changes to hooks so `--clean` is necessary to force it to reload its cache.

**Comment by rokm** [comment]
Also, since this is a `torch`-based package, it may require more (if not all) of its .py files to be collected...

**Comment by gabanib22** [comment]
I tried with all suggestions but still It's not working..
and yes, @rokm , I think this requires more files, and still not able to reach out to the solution.

So, now I'm decided to stop wasting my time, and now I'll install python and all packages on every computers and then run this desktop file using .bat file..


Thanks all of you for your findings and supports..

I'm closing this issue now..
