### ISSUE TITLE
gdk-pixbuf loaders missing when freezing GTK Python script, also path/environment variable issue with matplotlib navigation toolbar icons

### ISSUE THREAD

**Issue by LeighKorbel** [pyinstaller/pyinstaller#6282]
I am coming across two issues here. One is most certainly a PyInstaller issue and the second is probably not. Any assistance with one or both would be incredibly helpful. Thanks in advance.

I have a C GTK application that spawns a matplotlib plot via a python script that is frozen using PyInstaller. In Windows, I am using an MSYS2/MinGW shell to compile the program since the python script is dependent on GTK in python. After everything is compiled, a gdk-pixbuf 'loaders' folder is missing. I have several applications that I compile using PyInstaller and this doesn't always occur, but it does happen often enough to make it annoying. I would like to find out why this is happening. Second, I can run the application from the MinGW shell and everything works fine. However, when I open the program executable by double clicking on it in Windows File Explorer (rather than running through the shell), the icons are missing from matplotlib navigation toolbar. It seems like it would be a path issue or an environment variable, but I haven't been able to determine what the problem is yet. This is probably not due to PyInstaller, but if anyone has any ideas I would appreciate it. A Google search on the issue comes up empty.

I created a minimal example and added it to GitHub with a README. You just need to be on a computer running Windows and download MSYS2/MinGW in order to compile the program to run in Windows. See:

https://github.com/LeighKorbel/pyinstaller_pixbuf_and_path_issue/

The README walks through getting the minimal example to run and outlines the two issues I am having.

**Comment by rokm** [comment]
All those DLLs you placed in the same directory as the python script (which is presumably also your working directory) are poisoning your build environment. So when PyInstaller looks for `Gtk3`/`Gdk` shared libraries, it ends up resolving those DLLs instead of original ones in `'C:/msys64/mingw64/bin'`.

An so when [the `GdkPixbuf` hook tries to find the path to GI library directory](https://github.com/pyinstaller/pyinstaller/blob/5a02f55c696f16b98f23a8b487f3daa8f644a8d2/PyInstaller/hooks/hook-gi.repository.GdkPixbuf.py#L36), it ends up with `'.'` instead of `'C:/msys64/mingw64/bin'`, and consequently fails to collect any pixbuf loaders.

**Comment by rokm** [comment]
I cannot reproduce your second problem, though (aside from issues arising from [relative path to matplotlib window icon](https://github.com/LeighKorbel/pyinstaller_pixbuf_and_path_issue/blob/43a0d8de06a75a61bd8cfdde8cfee2f9c482be8e/plot.py#L17)) - the navigation toolbar has icons regardless of how the frozen application is launched (from shell, from File Explorer, from your launcher launched from shell, from your launcher launched from File Explorer). FWIW, those icons should be collected into `dist/plot/matplotlib/mpl-data/images`, so you can check if they are indeed there...

**Comment by LeighKorbel** [comment]
@rokm I appreciate the timely response. In my actual software (not the minimal example) I have the dll's in the root directory with the makefile, but the source python script buried in /src and this problem still comes up. Any suggestions? I also mention in the README that the icons for the navigation toolbar are indeed located in that precise location, and yet when the example (and my program) are launched outside of the shell I get broken link images for the icons anyway. I'm going to try again from a different computer and see if I get the same result or fail to reproduce it, as was the case with you.

**Comment by rokm** [comment]
> @rokm I appreciate the timely response. In my actual software (not the minimal example) I have the dll's in the root directory with the makefile

So the DLLs are in your current working directory (i.e., from where PyInstaller is launched)? I think it might still be the same problem...

You can verify this by either editing your makefile to not remove the `build` directory, open the generated `build/plot/Analysis-00.toc` with text editor, and see what the source of `libgdk_pixbuf-2.0-0.dll` is. Alternatively, you can also open`python` in the directory you would end up running pyinstaller from, and try to manually run the following snippet:
```python
from PyInstaller.utils.hooks.gi import get_gi_libdir
get_gi_libdir('GdkPixbuf', '2.0')
```
and see if the returned libdir is `'.'` or the actual path to system DLLs.

**Comment by LeighKorbel** [comment]
I am going to close this issue, as I was also not able to reproduce the broken links for missing icons on the navigation toolbar on another Windows computer, so the problem is clearly not PyInstaller. Many thanks @rokm for the assistance!
