### ISSUE TITLE
Unable to import module TensorFlow 2.6.0 in frozen program

### ISSUE THREAD

**Issue by justvasq** [pyinstaller/pyinstaller#6285]
## Description of the issue
Hello, I'm upgrading Tensorflow versions in an inference script from TF 2.1.0 to TF2.6.0. When I run the executable, I get the following error:

`ModuleNotFoundError: No module named 'tensorflow.compat.v1.keras`

I've tried renaming the API to values found in the PYZ-00.pyz:

`ModuleNotFoundError: No module named 'tensorflow._api.v2.compat.v1.keras'
`
with the same error. 

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(4.2)```
* Version of Python: 
3.7
* Platform: 
centos7
* How you installed Python: 
built from source
* Did you also try this on another platform? Does it work there?
No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
# -*- mode: python -*-

block_cipher = None

infer.spec

a = Analysis(['infer.py'],
             pathex=['/project_dir/app', '.'],
             binaries=[],
             datas=[('/usr/local/lib/python3.7/site-packages/tensorflow', 'tensorflow')],
             hiddenimports=['pywt._extensions._cwt', 'wrapt', 'absl.*', 'gast', 'astor', 'termcolor', 'opt_einsum', 'google.protobuf.json_format', 'google.protobuf.wrappers_pb2'],
             hookspath=['hooks'],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
a.binaries = a.binaries - TOC([('libcuda.so.1', None, None)])
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='infer',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          console=True )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               name='infer')

hook-tensorflow.py

from PyInstaller.utils.hooks import collect_all
def hook(hook_api):
    packages = [
        'tensorflow',
        'astor'
    ]
    for package in packages:
        datas, binaries, hiddenimports = collect_all(package)
        hook_api.add_datas(datas)
        hook_api.add_binaries(binaries)
        hook_api.add_imports(*hiddenimports)
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
The missing module seems to be actually mapped to `keras.api._v1.keras`.

So try adding `keras.api._v1.keras` to your `hiddenimports` (or maybe try to do brute/force `collect_all` on `keras` if you get other missing module errors after that).
