### ISSUE TITLE
Match Statement Support

### ISSUE THREAD

**Issue by s4m-mo** [pyinstaller/pyinstaller#6286]
**Is your feature request related to a problem? Please describe.**
This is not exactly related to a problem, but, since Python 3.10 came out earlier this week, I wondered if `match` statement support will come soon.

**Describe the solution you'd like**
I personally think that it may be possible by translating all of the  `match` and `case` statements to a long line of `if` and `elif` statements with `==` for each case. e.g.

```python
x = "hello"
match x:
    case "hello":
        print("hi")
    case "world":
        print("hello world")
```

would become

```python
x = "hello"
if x == "hello":
    print("hi")
elif x == "world":
    print("hello world")
```

**Additional context**
Thanks for your time.

**Comment by rokm** [comment]
That's a python-level feature, not `PyInstaller` one. I.e., if you use PyInstaller with python 3.10 (after #5694 and #6274 are merged to corresponding branches), you get `match` support. Otherwise, you don't.
