### ISSUE TITLE
Support "hidden" import  of a full package (including all sub-packages)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#630]
**Original date**: 2012/11/19
**Original reporter**: *eu AND doxos DOT eu*

Analysis of source code misses hidden imports in complicated packages. It would be handy to have an option to something like
```
    hiddenimports='foo.*'
```

**Comment by htgoebel** [comment]
This is already implemented since release 3.0 by `collect_submodules()`
