### ISSUE TITLE
`Tuple index out of range` with Python 3.10 and `pyinstaller` `5.0.dev0`

### ISSUE THREAD

**Issue by harshil21** [pyinstaller/pyinstaller#6301]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: `Python 3.10.0`
* Platform: `Windows 11, English`
* How you installed Python: `python.org/downloads`
* Did you also try this on another platform? Does it work there? - `Yes works perfectly on python 3.9.7 with same program (see minimal example below)`

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Yes that's how I installed

  * [x] start with clean installation
  * [x] use the latest development version
  * [ ] ~Run your frozen program **from a command window (shell)** — instead of double-clicking on it~ Not applicable
  * [x] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Run `pip install python-telegram-bot-raw` on python 3.10
Minimal example:

``` python
# saved as test.py
import telegram
```

Now try to package this as an exe using the command `pyinstaller test.py` or `pyinstaller test.py -F`

If you follow the same procedure in latest stable pyinstaller with python 3.9.7. Then there is no error and everything compiles perfectly.

### Stacktrace / full error message

<details><summary>Stacktrace / Full error message</summary>

```
C:\Users\Harshil Mehta\Documents\pyprojects\copy_usb>pyinstaller test.py
56 INFO: PyInstaller: 5.0.dev0
56 INFO: Python: 3.10.0
65 INFO: Platform: Windows-10-10.0.22000-SP0
67 INFO: wrote C:\Users\Harshil Mehta\Documents\pyprojects\copy_usb\test.spec
69 INFO: UPX is not available.
77 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Harshil Mehta\\Documents\\pyprojects\\copy_usb']
270 INFO: checking Analysis
271 INFO: Building Analysis because Analysis-00.toc is non existent
271 INFO: Initializing module dependency graph...
274 INFO: Caching module graph hooks...
285 INFO: Analyzing base_library.zip ...
2945 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\Harshil Mehta\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\pyinstaller-5.0.dev0-py3.10.egg\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2948 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\Harshil Mehta\\AppData\\Local\\Programs\\Python\\Python310\\lib'
3742 INFO: Caching module dependency graph...
3876 INFO: running Analysis Analysis-00.toc
3879 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\python.exe
3927 INFO: Analyzing C:\Users\Harshil Mehta\Documents\pyprojects\copy_usb\test.py
Traceback (most recent call last):
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller-script.py", line 33, in <module>
    sys.exit(load_entry_point('pyinstaller==5.0.dev0', 'console_scripts', 'pyinstaller')())
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\building\build_main.py", line 818, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\building\build_main.py", line 750, in build
    exec(code, spec_namespace)
  File "C:\Users\Harshil Mehta\Documents\pyprojects\copy_usb\test.spec", line 7, in <module>
    a = Analysis(
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\building\build_main.py", line 302, in __init__
    self.__postinit__()
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\building\build_main.py", line 464, in assemble
    priority_scripts.append(self.graph.add_script(script))
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\depend\analysis.py", line 265, in add_script
    self._top_script_node = super().add_script(pathname)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1433, in add_script
    self._process_imports(n)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\depend\analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
    self._process_imports(n)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
    target_module = self._safe_import_hook(*import_info, **kwargs)[0]
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
    target_modules = self.import_hook(
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1505, in import_hook
    target_package, target_module_partname = self._find_head_package(
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 1684, in _find_head_package
    target_package = self._safe_import_module(
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\depend\analysis.py", line 387, in _safe_import_module
    return super()._safe_import_module(module_basename, module_name, parent_package)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 2061, in _safe_import_module
    n = self._scan_code(module, co, co_ast)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 2645, in _scan_code
    self._scan_bytecode(
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\modulegraph.py", line 2749, in _scan_bytecode
    for inst in util.iterate_instructions(module_code_object):
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\util.py", line 147, in iterate_instructions
    yield from iterate_instructions(constant)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\site-packages\pyinstaller-5.0.dev0-py3.10.egg\PyInstaller\lib\modulegraph\util.py", line 139, in iterate_instructions
    yield from get_instructions(code_object)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\dis.py", line 338, in _get_instructions_bytes
    argval, argrepr = _get_const_info(arg, constants)
  File "C:\Users\Harshil Mehta\AppData\Local\Programs\Python\Python310\lib\dis.py", line 292, in _get_const_info
    argval = const_list[const_index]
IndexError: tuple index out of range
```

</details>

**Comment by bwoodsend** [comment]
I can reproduce this on Linux too. This is specific to Python 3.10 but not to the development version of PyInstaller (i.e. this is not a recent bug of ours). This is going to be ugly because it's all happening deep inside of modulegraph which none of us really understand. I have triangulated the issue down to calling `PyInstaller.lib.modulegraph.get_instructions()` on the code object starting [here](https://github.com/python-telegram-bot/python-telegram-bot/blob/v13.7/telegram/message.py#L81) which is a very large code object so, at an initial guess, I imagine that Python's bytecode has added a new way to write large code objects (or rather code objects with lots of variable names or constants) more compactly which we need to teach modulegraph.

**Comment by rokm** [comment]
Here's a stand-alone version of the offending code (no `PyInstaller` or its `modulegraph` involved). It doesn't look outright *wrong* to me (and works with 3.9), so perhaps the issue is with python or its `dis` module. But I guess we can do a bisect between 3.9.7 and 3.10 and see if we can pinpoint the problematic change to get better idea what's going on.

```python

import telegram.message  # pip install python-telegram-bot-raw

import inspect
import dis


# Get module's CO
module_co = telegram.message.__loader__.get_code('telegram.message')
print("Module CO:", module_co)

print("Module instructions:", list(dis.get_instructions(module_co)))

# Iterate over consts with CO
for const_co in module_co.co_consts:
    if not inspect.iscode(const_co):
        continue

    print("Const CO:", const_co)
    print("Const CO instructions:", list(dis.get_instructions(const_co)))
```

**Comment by bwoodsend** [comment]
I think it's somewhere in this commit:
https://github.com/python/cpython/commit/40d2ac92f9a28a486156dafdbb613016bb1f6b98#diff-96747735ee3c8aed3dd0f4c1b1ab0310eeb344577b14887cc9f6605892df47a8R425
It fails on that changed line at least.

**Comment by rokm** [comment]
Bisect says this is the offending change: https://github.com/python/cpython/commit/7301979b23406220510dd2c7934a21b41b647119

And indeed using [strip-hints](https://pypi.org/project/strip-hints/) to remove type annotations from `telegram/message.py` makes the above stand-alone example work.

**Comment by andyb415** [comment]
I'm running into this error as well, while using py2app with python3.10 on macOS 10.15.
$python3 setup.py py2app -A ---> works no problem
$python3 setup.py py2app --- does not.  I see same IndexError:
File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/dis.py", line 292, in _get_const_info
    argval = const_list[const_index]
IndexError: tuple index out of range

**Comment by Configger** [comment]
pyinstaller 4.5.1 release also has this bug.

I solved this by simply try-except, and I don't know if this will cause any other bugs:

def iterate_instructions(code_object):
    """Delivers the byte-code instructions as a continuous stream.

    Yields `dis.Instruction`. After each code-block (`co_code`), `None` is
    yielded to mark the end of the block and to interrupt the steam.
    """
    **try:
        yield from get_instructions(code_object)
    except:
        pass**

    yield None

    # For each constant in this code object that is itself a code object,
    # parse this constant in the same manner.
    for constant in code_object.co_consts:
        if inspect.iscode(constant):
            yield from iterate_instructions(constant)

**Comment by bwoodsend** [comment]
> I solved this by simply try-except, and I don't know if this will cause any other bugs:

That just skips chunks of code from the analysis so yes it will cause other bugs. Realistically, I don't think that we can ever support Python 3.10.0 and can't support any later Python 3.10 until this bug in Python's dis module is fixed.

**Comment by lededev** [comment]
I got `IndexError: tuple index out of range` also, so we need wait Python 3.10.1?

**Comment by bwoodsend** [comment]
Well for 3.10.1 to contain a fix we'll need to report this to Python's bug tracker (preferably finding a smaller chunk of bytecode which causes the error first) then I imagine that we'd have to provide a pull request to Python ourselves because I doubt it'll get much priority otherwise. That said, if py2app is also hit by this then its authors might do all the above for us.

**Comment by DummyGNP** [comment]
I have been playing with this today and found this to be interesting:
----

```
def _get_const_info(const_index, const_list):
    """Helper to get optional details about const references
       Returns the dereferenced constant and its repr if the constant
       list is defined.
       Otherwise returns the constant index and its repr().
    """
    argval = const_index
    if const_list is not None:
        try:
            argval = const_list[const_index]
        except BaseException as errormsg:
            print(f'''ERROR: {errormsg} for const_index:{const_index} while {len(const_list)}''')
    return argval, repr(argval)
```
----

The error that is happening is the const_index goes way over the len of const_list. in my example here is the report: 

```
ERROR: tuple index out of range for const_index:131949 while 920
ERROR: tuple index out of range for const_index:33686384 while 920
ERROR: tuple index out of range for const_index:66310 while 920
ERROR: tuple index out of range for const_index:33620851 while 920
ERROR: tuple index out of range for const_index:8606843779 while 920
ERROR: tuple index out of range for const_index:4328653703 while 920
ERROR: tuple index out of range for const_index:33620873 while 920
ERROR: tuple index out of range for const_index:33620886 while 920
ERROR: tuple index out of range for const_index:66178 while 686
ERROR: tuple index out of range for const_index:66181 while 686
ERROR: tuple index out of range for const_index:66198 while 686
ERROR: tuple index out of range for const_index:66203 while 686
```

I hope this helps you in troubleshooting :) 

110 INFO: PyInstaller: 5.0.dev0
110 INFO: Python: 3.10.0
142 INFO: Platform: Windows-10-10.0.19042-SP0
142 INFO: UPX is not available.

**Comment by bwoodsend** [comment]
I'll try to give this a go this weekend but if anyone wants to speed the process up you can setup the following:

* Download [https://raw.githubusercontent.com/python-telegram-bot/python-telegram-bot/v13.7/telegram/message.py]() and save it as `message.py`.
* Copy paste the following into a file called `test.py` in the same folder.
  ```python
  import inspect
  import dis
  
  # Get module's CO
  with open("message.py") as f:
      module_co = compile(f.read(), "telegram.message", "exec")
  
  list(dis.get_instructions(module_co))
  
  # Iterate over consts with CO
  for const_co in module_co.co_consts:
      if not inspect.iscode(const_co):
          continue
      list(dis.get_instructions(const_co))
  ```
  
* Then randomly keep deleting as much code as you can from `message.py` so that, on running `test.py` with Python 3.10, the `compile()` function still works but the `list(dis.get_instructions(const_co)))` still fails. That way we will have hopefully have a much simpler chunk of broken bytecode to diagnose (the current one is based on almost 3000 lines of code so it'd be a nightmare to work through).

**Comment by rokm** [comment]
Alright, think I figured this out.

The invalid index is coming from an attempt to load default values of keyword arguments for a method, and stems from the following sequence of opcodes:

```
EXTENDED_ARG 0x01
NOP
EXTENDED ARG 0x01
LOAD_CONST 0x29
```

This causes `dis` to try loading constant at index 0x010129, whereas the actual target constant should be at 0x129.

```
...
<<<<: offset=4166, op=100 (LOAD_CONST), arg=259 -> argval=<code object parse_caption_entities at 0x7f993e5937e0, file "telegram.message", line 2409>, argrepr=<code object parse_caption_entities at 0x7f993e5937e0, file "telegram.message", line 2409>
>>>>: offset=4168, op=144 (EXTENDED_ARG), arg=1 (0x1)
<<<<: offset=4168, op=144 (EXTENDED_ARG), arg=1 -> argval=1, argrepr=
>>>>: offset=4170, op=100 (LOAD_CONST), arg=260 (0x104)
<<<<: offset=4170, op=100 (LOAD_CONST), arg=260 -> argval=Message.parse_caption_entities, argrepr='Message.parse_caption_entities'
>>>>: offset=4172, op=132 (MAKE_FUNCTION), arg=5 (0x5)
<<<<: offset=4172, op=132 (MAKE_FUNCTION), arg=5 -> argval=5, argrepr=defaults, annotations
>>>>: offset=4174, op=90 (STORE_NAME), arg=105 (0x69)
<<<<: offset=4174, op=90 (STORE_NAME), arg=105 -> argval=parse_caption_entities, argrepr=parse_caption_entities
>>>>: offset=4176, op=101 (LOAD_NAME), arg=106 (0x6a)
<<<<: offset=4176, op=101 (LOAD_NAME), arg=106 -> argval=staticmethod, argrepr=staticmethod
>>>>: offset=4178, op=9 (NOP), arg=None
<<<<: offset=4178, op=9 (NOP), arg=None -> argval=None, argrepr=
>>>>: offset=4180, op=144 (EXTENDED_ARG), arg=1 (0x1)
<<<<: offset=4180, op=144 (EXTENDED_ARG), arg=1 -> argval=1, argrepr=
>>>>: offset=4182, op=9 (NOP), arg=None
<<<<: offset=4182, op=9 (NOP), arg=None -> argval=None, argrepr=
>>>>: offset=4184, op=144 (EXTENDED_ARG), arg=257 (0x101)
<<<<: offset=4184, op=144 (EXTENDED_ARG), arg=257 -> argval=257, argrepr=
>>>>: offset=4186, op=100 (LOAD_CONST), arg=65833 (0x10129)
!!!!: offset=4186, op=100 (LOAD_CONST), arg=65833 (0x10129) -> len(constants)=(299)
Traceback (most recent call last):
  File "/usr/lib64/python3.10/pdb.py", line 1723, in main
    pdb._runscript(mainpyfile)
  File "/usr/lib64/python3.10/pdb.py", line 1583, in _runscript
    self.run(statement)
  File "/usr/lib64/python3.10/bdb.py", line 597, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "/home/rok/tmp/pyi-dis/test.py", line 14, in <module>
    list(dis.get_instructions(const_co))
  File "/home/rok/tmp/pyi-dis/dis.py", line 344, in _get_instructions_bytes
    argval, argrepr = _get_const_info(arg, constants)
  File "/home/rok/tmp/pyi-dis/dis.py", line 292, in _get_const_info
    argval = const_list[const_index]
IndexError: tuple index out of range
Uncaught exception. Entering post mortem debugging
Running 'cont' or 'step' will restart the program
> /home/rok/tmp/pyi-dis/dis.py(292)_get_const_info()
-> argval = const_list[const_index]
(Pdb) len(const_list)
299
(Pdb) const_list[0x129]
(False, 0)
(Pdb)
```

There are two such "problematic" methods in the `message.py` file (coincidentally both `@staticmethods`, too, but that probably plays no role in this mystery), `_parse_html` and `_parse_markdown`. Removing the default argument values from these methods makes the test code pass. Moving both methods at the beginning of the class likewise makes the test code pass, because `EXTENDED_ARG`s aren't used there. Similarly, we probably need a file as large and complex as `message.py` to trigger that unfortunate combination if `EXTENDED_ARG`s. This also means that python/cpython@7301979 is in fact not directly responsible for this issue, but likely only uncovered it...

So the Saturday night quiz question is: is python generating invalid bytecode here, or is `dis` incorrectly handling that particular case? In other words, does a `NOP` instruction "undo" the preceding `EXTENDED_ARG` or not?

I couldn't find any references on this, but fortunately, we can verify this experimentally, with some hand-crafted byte-code:

```python
import types

constants = [None] * (0x010125 + 1)
constants[0x000125] = "nop_reset"  # NOP swallowed the EXTENDED_ARG
constants[0x010125] = "nop_noreset"  # NOP did not swallow the EXTENDED_ARG

# Test 1: no NOP (sanity check)
code1 = types.CodeType(
    0,  # argcount
    0,  # posonlyargcount
    0,  # kwonlyargcount
    0,  # nlocals
    1,  # stacksize
    64,  # flags
    bytes([
        0x90, 0x01,  # EXTENDED_ARG 0x01
        0x90, 0x01,  # EXTENDED_ARG 0x01
        0x64, 0x25,  # LOAD_CONST 0x25
        0x53, 0x00,  # RETURN_VALUE 0x00
    ]),  # codestring
    tuple(constants),  # constants
    (),  # names
    (),  # varnames
    '<no file>',  # filename
    'code1',  # name
    1,  # firstlineno
    b''  # linetable
)

print("Test1:", eval(code1))

# Test 2: added NOP
code2 = types.CodeType(
    0,  # argcount
    0,  # posonlyargcount
    0,  # kwonlyargcount
    0,  # nlocals
    1,  # stacksize
    64,  # flags
    bytes([
        0x90, 0x01,  # EXTENDED_ARG 0x01
        0x09, 0xFF,  # NOP 0xFF
        0x90, 0x01,  # EXTENDED_ARG 0x01
        0x64, 0x25,  # LOAD_CONST 0x25
        0x53, 0x00,  # RETURN_VALUE 0x00
    ]),  # codestring
    tuple(constants),  # constants
    (),  # names
    (),  # varnames
    '<no file>',  # filename
    'code2',  # name
    1,  # firstlineno
    b''  # linetable
)

print("Test2:", eval(code2))
```

And the output is:
```
Test1: nop_noreset
Test2: nop_reset
```

So the `NOP` does, in fact, "reset" the argument extension, and it is the `dis` module that needs to be fixed to handle this correctly.

**Comment by rokm** [comment]
And fixing this in `dis` seems to be pretty straightforward, by adding `extended_arg = 0` [here](https://github.com/python/cpython/blob/91275207296c39e495fe118019a757c4ddefede8/Lib/dis.py#L525). 

This assumes that all no-argument op-codes reset the argument extension as `NOP` does, even if it is probably unlikely that they would appear like that (even that `EXTENDED_ARG` + `NOP` combination feels weird, and might be a bug).

**Comment by bwoodsend** [comment]
Hmm, I can't think why a `NOP` instruction would be needed to begin with so I can't guess what the intended behaviour of a `EXTENDED_ARG` + `NOP` could be. Can we move this to Python's issue tracker now? I don't think we can dig any deeper without answering that question to begin with.

**Comment by rokm** [comment]
> Can we move this to Python's issue tracker now?

Yeah, will do.

**Comment by muhammedaksam** [comment]
I just started to use pyinstaller and come up to this error. I was using python 3.10 as well.

**Comment by rokm** [comment]
Here we go: https://bugs.python.org/issue45757

**Comment by bwoodsend** [comment]
And it looks like they're already fixing it too.

**Comment by andydish** [comment]
I am not as familiar with python update release schedules but does this mean for those affected by this issue, pyinstaller will not function until the next bugfix release on Monday, 2021-12-06?

**Comment by rokm** [comment]
> I am not as familiar with python update release schedules but does this mean for those affected by this issue, pyinstaller will not function until the next bugfix release on Monday, 2021-12-06?

Until python 3.10.x with the fix is released, you can also manually patch the `dis` module in your local python installation.

**Comment by andydish** [comment]
Thank you! I went ahead and did that and that is working for me now.

**Comment by rushmad** [comment]
a simple code with python 3.10 
`
from time import sleep
from tqdm import tqdm

for i in tqdm(range(20)):
  sleep(0.5)
`
pyinstaller can't create .exe file. 
i got the same error message :
  File "C:\Python310-32\lib\dis.py", line 292, in _get_const_info
    argval = const_list[const_index]
IndexError: tuple index out of range

**Comment by elibroftw** [comment]
> I'll try to give this a go this weekend but if anyone wants to speed the process up you can setup the following:
> 
>     * Download https://raw.githubusercontent.com/python-telegram-bot/python-telegram-bot/v13.7/telegram/message.py and save it as `message.py`.
> 
>     * Copy paste the following into a file called `test.py` in the same folder.
>       ```python
>       import inspect
>       import dis
>       
>       # Get module's CO
>       with open("message.py") as f:
>           module_co = compile(f.read(), "telegram.message", "exec")
>       
>       list(dis.get_instructions(module_co))
>       
>       # Iterate over consts with CO
>       for const_co in module_co.co_consts:
>           if not inspect.iscode(const_co):
>               continue
>           list(dis.get_instructions(const_co))
>       ```
> 
>     * Then randomly keep deleting as much code as you can from `message.py` so that, on running `test.py` with Python 3.10, the `compile()` function still works but the `list(dis.get_instructions(const_co)))` still fails. That way we will have hopefully have a much simpler chunk of broken bytecode to diagnose (the current one is based on almost 3000 lines of code so it'd be a nightmare to work through).

I think https://github.com/python/cpython/commit/c5bfb88eb6f82111bb1603ae9d78d0476b552d66#diff-96747735ee3c8aed3dd0f4c1b1ab0310eeb344577b14887cc9f6605892df47a8 fixes some of the issues.
I added `extended_arg=0` to `dis.py` and `test.py` works.

**Comment by elibroftw** [comment]
My own issue is 
```py
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'setuptools._vendor.six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'setuptools.extern.six'
pre-safe-import-module hook failed, needs fixing.
8186 INFO: Analyzing C:\Users\maste\Documents\GitHub\music-caster\src\music_caster.py
8870 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\maste\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
8872 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\maste\\AppData\\Local\\Programs\\Python\\Python310\\lib'
9457 INFO: Processing pre-safe import module hook setuptools.extern.six.moves from 'C:\\Users\\maste\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-setuptools.extern.six.moves.py'.
Traceback (most recent call last):
  File "<string>", line 3, in <module>
ModuleNotFoundError: No module named 'setuptools._vendor.six'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 5, in <module>
ModuleNotFoundError: No module named 'setuptools.extern.six'
pre-safe-import-module hook failed, needs fixing.
```

**Comment by rokm** [comment]
@elibroftw Please do not post unrelated issues. Open a new issue instead.

**Comment by MiguelMLR9** [comment]
so basically you have to go to the folder "Python310\Lib" and edit the file 'dis.py'.
In the 'dis.py' file you have to find this "def _unpack_opargs" and inside the else statement write a new line with this: "extended_arg = 0".

I did something like that:

```
        else:
            arg = None
            extended_arg = 0 
        yield (i, op, arg)
```
and everything is working fine now.

**Comment by Aezore** [comment]
I had the same issue and I can confirm this hotfix works just fine. Thanks!

**Comment by 108174** [comment]
Thank you all!!!!!!

**Comment by zhu258258669** [comment]
@MiguelMLR9 牛逼，多谢了。成功解决问题。

**Comment by nate83300** [comment]
I can also confirm that @MiguelMLR9's hotfix worked! In 'dis.py', I found the "def _unpack_opargs" on line 422. Else statement to edit is a few lines later.

**Comment by rokm** [comment]
With python 3.10.1 released, we can now hopefully forget that this problem ever existed.
