### ISSUE TITLE
Incompatible with Python 3.10.0 - _bootlocale module error (READ FOR MORE INFO)

### ISSUE THREAD

**Issue by sandbands** [pyinstaller/pyinstaller#6302]
Yesterday i finished a project, used auto-py-to-exe (which uses pyinstaller) to make it an executable, and it worked.

I upgraded to Python 3.10.0 right after

I finished another project today, tried auto-py-to-exe but this time it didnt work, i got this error

```
  File "C:\Users\myuser\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1711, in _find_head_package
    raise ImportError("No module named " + target_package_name)
ImportError: No module named _bootlocale

Project output will not be moved to output folder
Complete.
```

so i tried pyinstaller (made sure pip and pyinstaller were up to date), and i got the exact same error

the auto-py-to-exe devs cant fix this as the bug is in your library, so its up to you

**Comment by bwoodsend** [comment]
That's because there are no releases that support Python 3.10. Those changes have been applied here on github but not on PyPI. If you desperately need to use Python 3.10 then use:

```
pip install https://github.com/pyinstaller/pyinstaller/archive/v4.zip
```
Then rebuild but add the `--clean` option.
