### ISSUE TITLE
yolov5:FileNotFoundError: [WinError 3] (Hope to get an answer, thank you!)

### ISSUE THREAD

**Issue by yuan738** [pyinstaller/pyinstaller#6314]
### I ran 'detect.exe' for the first time
C:\Users\yuan>D:\a\dist\detect\detect.exe
detect: weights=best.pt, source=detect, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
**requirements: D:\a\dist\detect\requirements.txt not found, check failed.**
Traceback (most recent call last):
  File "detect.py", line 307, in <module>
  File "detect.py", line 302, in main
  File "site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
  File "detect.py", line 72, in run
  File "utils\torch_utils.py", line 60, in select_device
  File "utils\torch_utils.py", line 45, in date_modified
  File "pathlib.py", line 1183, in stat
**FileNotFoundError: [WinError 3] 系统找不到指定的路径。(The system cannot find the specified path): 'D:\\a\\dist\\detect\\utils\\torch_utils.pyc'**
[15804] Failed to execute script detect

### Then I move 'requirements.txt' to D:\a\dist\detect.
C:\Users\yuan>D:\a\dist\detect\detect.exe
detect: weights=best.pt, source=detect, imgsz=[640, 640], conf_thres=0.25, iou_thres=0.45, max_det=1000, device=, view_img=False, save_txt=False, save_conf=False, save_crop=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\detect, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, half=False, dnn=False
requirements: matplotlib>=3.2.2 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install matplotlib>=3.2.2' skipped (offline)
requirements: numpy>=1.18.5 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install numpy>=1.18.5' skipped (offline)
requirements: opencv-python>=4.1.2 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install opencv-python>=4.1.2' skipped (offline)
requirements: Pillow>=7.1.2 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install Pillow>=7.1.2' skipped (offline)
requirements: PyYAML>=5.3.1 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install PyYAML>=5.3.1' skipped (offline)
requirements: requests>=2.23.0 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install requests>=2.23.0' skipped (offline)
requirements: scipy>=1.4.1 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install scipy>=1.4.1' skipped (offline)
requirements: torch>=1.7.0 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install torch>=1.7.0' skipped (offline)
requirements: torchvision>=0.8.1 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install torchvision>=0.8.1' skipped (offline)
requirements: tqdm>=4.41.0 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install tqdm>=4.41.0' skipped (offline)
requirements: pandas>=1.1.4 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install pandas>=1.1.4' skipped (offline)
requirements: seaborn>=0.11.0 not found and is required by YOLOv5, attempting auto-update...
requirements: 'pip install seaborn>=0.11.0' skipped (offline)
Traceback (most recent call last):
  File "detect.py", line 307, in <module>
  File "detect.py", line 302, in main
  File "site-packages\torch\autograd\grad_mode.py", line 28, in decorate_context
  File "detect.py", line 72, in run
  File "utils\torch_utils.py", line 60, in select_device
  File "utils\torch_utils.py", line 45, in date_modified
  File "pathlib.py", line 1183, in stat
**FileNotFoundError: [WinError 3] 系统找不到指定的路径。(The system cannot find the specified path): 'D:\\a\\dist\\detect\\utils\\torch_utils.pyc'**
[3508] Failed to execute script detect

**Comment by bwoodsend** [comment]
>  requirements: matplotlib>=3.2.2 not found and is required by YOLOv5, attempting auto-update...

You can't update a frozen application's packages. They're *frozen*.

**Comment by rokm** [comment]
The auto-update thing is a red herring, though...

There are a lot of... PyInstaller-incompatible... design choices in the `yolov5` codebase. I suppose the easiest/sanest way to deal with them is to freeze with `--debug noarchive` or setting `noarchive=True` in the spec file (argument to `Analysis`).

**Comment by yuan738** [comment]
> The auto-update thing is a red herring, though...
> 
> There are a lot of... PyInstaller-incompatible... design choices in the `yolov5` codebase. I suppose the easiest/sanest way to deal with them is to freeze with `--debug noarchive` or setting `noarchive=True` in the spec file (argument to `Analysis`).

Thank you very much for your reply!   :)

**Comment by yuan738** [comment]
> > requirements: matplotlib>=3.2.2 not found and is required by YOLOv5, attempting auto-update...
> 
> You can't update a frozen application's packages. They're _frozen_.

Thank you very much.
