### ISSUE TITLE
Packaged app fails to find Pmw

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#632]
**Original date**: 2014/04/22
- Problem occurs when trying to run the packaged app.
- Python 2.6.5
- Linux 2.6.32-45-generic #99-Ubuntu SMP x86_64 GNU/Linux   (Ubuntu 10.04)
- Pyinstaller 2.0
  - Also tried latest dev build
  - Also tried Pyinstaller v1.5.1
- /usr/lib/python2.6/dist-packages/Pmw/Pmw_1_3/  (So Pmw v1.3)
- Output from ArchiveViewer:

```
  $ {PATH}/utils/ArchiveViewer.py out00-PYZ.pyz 
   Name: (ispkg, pos, len)
  {'FixTk': (False, 541896, 1034),
   'Pmw': (True, 81305, 596),
  . . .
```
- Output from running packaged app:

```
  $ ./img_tkgui 
  Traceback (most recent call last):
    File "<string>", line 66, in <module>
    File "/home/voom/python/pyinstaller-2.0/PyInstaller/loader/iu.py", line 386, in importHook
      mod = _self_doimport(nm, ctx, fqname)
    File "/home/voom/python/pyinstaller-2.0/PyInstaller/loader/iu.py", line 480, in doimport
      exec co in mod.__dict__
    File "/home/voom/python/pyinstaller-2.0/img_tkgui/build/pyi.linux2/img_tkgui/out00-PYZ.pyz/Pmw", line 28, in <module>
  OSError: [Errno 2] No such file or directory: '/home/voom/python/pyinstaller-2.0/img_tkgui/dist/img_tkgui/img_tkgui?42197/Pmw'
```

**Comment by HackEduca** [comment]
I would like to know if someone succeed on this?
I am still having problem

**Comment by 4rm** [comment]
@HackEduca 

Try using takaakiaoki's Pmw.py here: https://github.com/takaakiaoki/bundlepmw

I was able to successfully use it to create an exe

**Comment by nihaalnz** [comment]
Can you peeps please explain what to do, cause i dint understand what you guys did, am a beginner :(

**Comment by 4rm** [comment]
@nihaalnz try downloading the files from takaakiaoki's bundlepmw and place them in the same folder as the rest of your files. Then try creating the exe again with pyinstaller

**Comment by nihaalnz** [comment]
yes thanks for the reply managed to get it working , they prev said i have error in line 2 cuz it said from . import PmwBlt while there is no such module or something i got error i removed tht line and its working fine :D
