### ISSUE TITLE
PyInstaller cannot check for assembly dependencies.

### ISSUE THREAD

**Issue by rstudiocode** [pyinstaller/pyinstaller#6340]
Hello, I'm Raphael and i am a python developper. I want to install pyinstaller but it doesn't work. When I type pyinstaller on the terminal (I'm on windows) , there is this error message :
PyInstaller cannot check for assembly dependencies.
Please install pywin32-ctypes.
pip install pywin32-ctypes

I've run the pip install pywin32-ctypescommand on the terminal and it said me that pywin32-ctype was already installed. I retyped the pyinstaller command and always the same error. How can I fix this problem ? I am on windows 10 and i use python 3.9.7

Thanks in advance !
![image](https://user-images.githubusercontent.com/63545838/140058892-682bc386-7192-47d6-9598-f393c7326783.png)

**Comment by rokm** [comment]
What happens if you run `python -m PyInstaller` instead of `pyinstaller`?

> I am on windows 10 and i use python 3.9.7

Your `pip install ` output indicates that your default python/pip is python 3.10, not 3.9.x...

**Comment by rstudiocode** [comment]
![image](https://user-images.githubusercontent.com/63545838/140784990-c125d5e4-6b84-4e75-a28e-f87cf61a9c58.png)
I'm not on py 3.10. I'm on python 3.9. One day, I wanted to test the new version of python but I returned on 3.9 and installed it on the 3.10 folder and it didn't worked so i renamed this folder. That' a long story... And even I use your command , It doesn't work. Always the same problem.

**Comment by rokm** [comment]
So you're telling me that your python 3.9 is using `c:\program files\python310\lib\site-packages` as its site packages directory?

Either way, what happens if your run python and execute the following two commands?
```
from win32ctypes.pywin32 import pywintypes
from win32ctypes.pywin32 import win32api
```

And if you try forcing re-install, using `pip install -I pywin32-ctypes`?

**Comment by rstudiocode** [comment]
I've renamed the folder now as python 3.9 and reinstalled python on it; 
Wheen i run the from
 ```
win32ctypes.pywin32 import pywintypes
from win32ctypes.pywin32 import win32api
```
I have a big error 
![image](https://user-images.githubusercontent.com/63545838/140790605-7495b774-ff5d-45f6-9951-9bc08c950541.png)
I tryed to force install of the package but it didn't helped

**Comment by rokm** [comment]
> I've renamed the folder now as python 3.9 and reinstalled python on it

I suggest you remove everything and perform a clean installation. I have no way of telling what kind of mixture of python 3.9 and python 3.10 python wheels you have lying around there. But this is clearly a problem with your environment, so it's up to you sort it out.

**Comment by rstudiocode** [comment]
If I returned to ^python 3.9 , it was because pyinstaller didn't worked with python 3.10
I didn't copyed the error but I remembered some words : "ERROR : could not find library For this version of python" or something like that
