### ISSUE TITLE
EXE File doesn't open after upgrading to 4.6

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#6356]
### A minimal example program which shows the error

```
just exectuting the exe file created I am getting the below error though it works fine after downgrading to 4.5-  tried with no upx option didn't help
```

### Stacktrace / full error message

```
Windows cannot acess the specified device,path,file you may not have the appropriate permission to access item
```

**Comment by ghost** [comment]
Had tried after downgrading to 4.1 version and the exe are working may I know what I can do to get it to work with 4 .7  my av crowdstike was blocking exe created with ver 4.5-4.7

**Comment by ghost** [comment]
> Had tried after downgrading to 4.1 version and the exe are working may I know what I can do to get it to work with 4 .7  my av crowdstike was blocking exe created with ver 4.5-4.7 

@bwoodsend @Legorooj

**Comment by eric15342335** [comment]
Apparently the anti-virus software was removing your exe. Disable it.
