### ISSUE TITLE
Mac pyinstaller multiprocess is not close

### ISSUE THREAD

**Issue by lycfr** [pyinstaller/pyinstaller#6357]
pyinstaller packaged app unlimited creation process

pyinstaller==4.5.1
macOs Catalina=10.5.7
python3==Python 3.7.5
<img width="875" alt="企业微信截图_a3e62052-c84e-476c-936b-04103f133e80" src="https://user-images.githubusercontent.com/29672247/140738217-a5acc91c-01dc-47e8-a3a5-212ca52ccb6f.png">

**Comment by lycfr** [comment]
I use this method, but I can't solve it
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Multiprocessing

**Comment by rokm** [comment]
We'll need to see sample code, otherwise we can't tell what's going on.
