### ISSUE TITLE
On macOS the `main()` function is called twice

### ISSUE THREAD

**Issue by Safihre** [pyinstaller/pyinstaller#6368]
We updated our build pipeline to the latest PyInstaller (4.7) and Python 3.10.
However, on macOS we notice that our `main()` function is called twice.
Many things could be the cause of this, but I have some evidence the cause is in PyInstaller.

First I downgraded PyInstaller to 4.5.1 and subsequently Python to 3.9 (since the older PyInstaller doesn't support Python 3.10) and the problem disappears.
When I use PyInstaller 4.7 again on Python 3.9, the problem returns.

I used `pdb` and printed `sys.argv`, it shows for the first call what I expect:
```
> /Users/safihre/SABnzbd.py(1762)run()
(Pdb) sys.argv
['Documents/GitHub/sabnzbd/dist/SABnzbd.app/Contents/MacOS/SABnzbd', '--console']
```
But for the second call to `main()`:
```
> /Users/safihre/SABnzbd.py(1762)run()
(Pdb) sys.argv
['/Users/safihre/Documents/GitHub/sabnzbd/dist/SABnzbd.app/Contents/MacOS/SABnzbd', '-B', '-S', '-E', '-s', '-c', 'from multiprocessing.resource_tracker import main;main(9)']
```

I also tested with the PyInstaller `develop` branch, same problem. 
And of course if I just run our program using `python SABnzbd.py`, it also doesn't happen.

**Comment by bwoodsend** [comment]
Are you using multiprocessing at all? In either case we'll need to see some code to be of much help - it clearly doesn't happen generally or our testing CI would be screaming in protest - so something in your code/environment is at play. Do you have any imports with the same name as your top level script?

**Comment by Safihre** [comment]
Yes, we do use `multiprocessing` at one spot [during start-up checks](https://github.com/sabnzbd/sabnzbd/blob/develop/sabnzbd/getipaddress.py#L42-L45). 
The application is named `SABnzbd.py` and it does have a main module `sabnzbd`.
It's a big application so making a reproduction using "plain" code will be hard, I was hoping you might have some pointers where to start.

**Comment by rokm** [comment]
>  It's a big application so making a reproduction using "plain" code will be hard, I was hoping you might have some pointers where to start.

If application itself is difficult to debug/isolate, you could perhaps try running git bisect between PyInstaller 4.5.1 and 4.7 to see what change on our side breaks the behavior for you.

FWIW, that second `main` call looks is an un-intercepted multiprocessing call. But I don't think we had any (intentional) changes in multiprocessing rthook that does the interception...

**Comment by rokm** [comment]
On the other hand, I also don't see your application calling [`multiprocess.freeze_support`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) anywhere, so our runtime hook cannot intercept the multiprocess-spawned calls to the executable at all. 

Is it possible that the difference lies in whether those `@timeout`-annotated functions are called at all or not?

**Comment by Safihre** [comment]
That was it! `multiprocess.freeze_support`
Thank you!
