### ISSUE TITLE
4.7 pyinstaller created exe gives side-by-side error in Windows, 4.6 works

### ISSUE THREAD

**Issue by esitarski** [pyinstaller/pyinstaller#6371]
## Description of the issue

When trying to run the pyinstaller 4.7 .exe, I get the following dialog message:

```
Unable to execute file:
C:\Program Files:\CrossMgrImpinj\CrossMgrImpinj.exe

CreateProcess failed: code 14001.
Ths application has failed to start because its side-by-side configuration is incorrect.
Please see the application event log or use the command-line sxstrace.exe tool for more details.
```

### Context information (for bug reports)

* Output of pyinstaller 4.7:

```
Successful compile (286.140 sec)  Resulting Seup program filename is:
...
```

* Version of Python: 3.8
* Platform: Windows 10, English
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Yes.  Works on Mac

This applicated uses wxPython.

* follow *all* the instructions in our "If Things Go Wrong" Guide.  Yes

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly).  Yes

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

Tried all the above.  4.6 works, 4.7 does not.

### A minimal example program which shows the error

pyinstaller 4.7 called as follows from script (not changed for 5 years).  Script works for pyinstaller 4.6.

```
pyinstaller.exe $program.pyw -p . --icon=$iconpath\$program.ico --distpath=$distpath --workpath=$buildpath --clean --windowed --noconfirm --exclude-module=tcl --exclude-module=tk --exclude-module=Tkinter --exclude-module=_tkinter
```

### Stacktrace / full error message

None.

[StackOverflow](https://stackoverflow.com/questions/69907737/the-application-has-failed-to-start-because-its-side-by-side-configuration-is-in) reports that pyinstaller 4.7 works after removing the --windowed argument.

I noticed that there are some new side-by-side options in pyinstaller but I have not tried them.

**Comment by rokm** [comment]
Can you try with `v4` branch and see if #6367 fixes the problem in your case? (And just to verify: you are using python 3.8, and not 3.9.8 by any chance?)

**Comment by esitarski** [comment]
I got to the v4 branch after cloning pyinstaller on github.
Is there a document that explains how to run pyinstaller from source that you can point me to?
Apologies - I don't know what I am doing here.
I have validated that I am not running 3.9.8.

**Comment by Legorooj** [comment]
@esitarski after you've cloned PyInstaller, navigate to the the root directory (which contains the `PyInstaller` directory and `setup.py`. Then make sure you have the correct virtual environment activated, and `pip install .`.

**Comment by rokm** [comment]
@esitarski If you have Visual Studio installed, can you use the `mt.exe` utility to extract the embedded manifest from the program created by PyInstaller 4.6 and one created by PyInstaller 4.7? And from the `python.exe` executable from the python you are using?

(you can run it as `mt.exe -inputresource:$path_to_exe -out:$output_xml_filename`)

**Comment by bwoodsend** [comment]
I'm going to assume that #6367 fixed it unless told otherwise.
