### ISSUE TITLE
The 'typing' package is an obsolete backport of a standard library package and is incompatible with PyInstaller.

### ISSUE THREAD

**Issue by Note-Liu** [pyinstaller/pyinstaller#6374]
I have installed pyinstaller in Docker,
when i use pyinstaller to package,
the message:

root@c3f31c8382:/yolov5/labelme# pyinstaller -F labelme/__main__.py
The 'typing' package is an obsolete backport of a standard library package and is incompatible with PyInstaller. Please `conda remove typing` then try again.
root@c3f31c8382:/yolov5/labelme# conda remove typing
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are missing from the target environment:
  - typing

root@c3f31c8382:/yolov5//labelme# 

how to solve it? 
Thanks~

**Comment by Note-Liu** [comment]
I have Successfully installed pyinstaller:

Successfully built pyinstaller
Installing collected packages: pyinstaller
Successfully installed pyinstaller

when i use :
pyinstaller --version

i got problems above:
The 'typing' package is an obsolete backport of a standard library package and is incompatible with PyInstaller. Please `conda remove typing` then try again.

**Comment by bwoodsend** [comment]
Just do what it says. Run `conda remove typing` then rerun PyInstaller.

**Comment by bwoodsend** [comment]
Or possibly `pip uninstall typing` if you didn't install it via conda.

**Comment by Note-Liu** [comment]
> Or possibly `pip uninstall typing` if you didn't install it via conda.

Thanks！

**Comment by WiiZARDD** [comment]
having the same issue, I did

`pip uninstall typing`

but it said it wasn't installed..?

**Comment by ElPrg** [comment]
U can in the file compat.py of pyinstaller line:

for name in ["enum34", "typing"]:

and remove "typing"

for name in ["enum34"]:

It seems to work ...
