### ISSUE TITLE
Random Permission issue upon reading a file inside packaged exe

### ISSUE THREAD

**Issue by s-arjun** [pyinstaller/pyinstaller#6375]
Hi, I have successfully created the exe. Everything seems to be working fine. But while running the new exe, occasionally I'm getting a `[Errno 13] Permission denied` error. This doesn't happen when I run the script using `python main.py`. 

In my script I have an area where I read a file. The permission issue occurs at this read. But this is completely random. 
I tried:
* changing the file path to the same directory as the package
* Disabling the antivirus (Win defender)
* adding the `--uac-admin` flag. 
* creating exe using admin previleges in powershell and cmd

Am I missing something here?

* Output of `pyinstaller --version`: ```4.7```
* Version of Python: 3.9
* Platform: Windows 10 
* How you installed Python: tried using conda as well as python.org
* Did you also try this on another platform? Does it work there? -- No it is a win application

### A minimal example program which shows the error

```
pyinstaller gui.py --windowed --name "Lab Report Cleaner" --uac-admin -i "icon.ico" --add-data "../data/;data/" --workpath "prod/dist/temp" --distpath "prod/dist" --specpath "prod/dist" --clean
```
I went through the already reported issues, but the permissions issue mentioned there are all occurring during the packaging.
Any help would be wonderful...

**Comment by bwoodsend** [comment]
`Permission denied error` is cryptic in that it has nothing to do with permissions. Rather it typically happens when you try to read from or write to a file which is actually a folder.

But without a real minimal example and its corresponding traceback we can't help you so you're on your own until you provide one.

**Comment by ghost** [comment]
I have a very similar issue, where I try to export an image I get permission denied. I have tried the same thing. Would CDing into that directory work or not? It would be really inconvenient to have to move the .exe or change the directory to where the file is located.

**Comment by bwoodsend** [comment]
> But without a real minimal example and its corresponding traceback we can't help you so you're on your own until you provide one.

Same applies to you.
