### ISSUE TITLE
universal2 builds codesign failure

### ISSUE THREAD

**Issue by suryakumaran2611** [pyinstaller/pyinstaller#6381]
when creating builds for x86-x64 the codesign is working fine , but when using universal the codesign shows the below error . Any idea on how to fix it?

32924 WARNING: codesign command (['codesign', '-s', '-', '--force', '--all-architectures', '--timestamp', '--entitlements', 'entitlements.plist', '****]) failed with error code 1!
stdout: ''
stderr: '/****: main executable failed strict validation\n'
Traceback (most recent call last):
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "HRAPP-Mac.spec", line 23, in <module>
    exe = EXE(pyz,
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/api.py", line 507, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/api.py", line 750, in assemble
    osxutils.sign_binary(self.name, self.codesign_identity, self.entitlements_file)
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/utils/osx.py", line 348, in sign_binary
    raise SystemError("codesign failure!")
SystemError: codesign failure!

**Comment by suryakumaran2611** [comment]
is there anyway to skip the pyinstaller codesign and I can sign it manually

**Comment by rokm** [comment]
> is there anyway to skip the pyinstaller codesign and I can sign it manually

You can edit PyInstaller code and comment out the calls to `sign_binary` (e.g., line 750 in `/usr/local/lib/python3.9/site-packages/PyInstaller/building/api.py`, as indicated in the traceback).

**Comment by rokm** [comment]
Other than that, can you provide a minimal example that triggers the issue?

**Comment by suryakumaran2611** [comment]
thanks for the info , what part of the code do you require? is the spec file enough?

**Comment by rokm** [comment]
Everything to reproduce the issue locally, so code and spec. If your program is not open-source, try reproducing the problem with a minimal program/code that you can share (e.g., if a simple hello-world program does not trigger the issue per-se, try adding imports of all 3rd party packages you use, etc.).

**Comment by suryakumaran2611** [comment]
Hi @rokm 
System Info :
63 INFO: PyInstaller: 4.7
363 INFO: Python: 3.9.8
405 INFO: Platform: macOS-12.0.1-x86_64-i386-64bit
420 INFO: UPX is not available.

after commenting out the sign_binary I get this error 
  File "/usr/local/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 782, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/build_main.py", line 714, in build
    exec(code, spec_namespace)
  File "HRAPP-Mac.spec", line 37, in <module>
    coll = COLLECT(exe,
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/api.py", line 818, in __init__
    self.__postinit__()
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/datastruct.py", line 155, in __postinit__
    self.assemble()
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/api.py", line 850, in assemble
    fnm = checkCache(
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/building/utils.py", line 360, in checkCache
    osxutils.binary_to_target_arch(cachedfile, target_arch, display_name=fnm)
  File "/usr/local/lib/python3.9/site-packages/PyInstaller/utils/osx.py", line 302, in binary_to_target_arch
    assert target_arch != 'universal2', f"{display_name} is not a fat binary!"
AssertionError: /usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_struct.cpython-39-darwin.so is not a fat binary!

**Comment by suryakumaran2611** [comment]
let me get you a sample

**Comment by rokm** [comment]
> AssertionError: /usr/local/Cellar/python@3.9/3.9.8/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/_struct.cpython-39-darwin.so is not a fat binary!

You cannot build `universal2` frozen applications using homebrew python, because the latter is single arch.

But I'd still be interested in an example that generates executable that fails `codesign` validation.

**Comment by danhuang-ixia** [comment]
I'm also seeing the same behavior with universal2 codesign.

Basic hello world script test.py:
```python
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
print ('hello world')`
```

pyinstaller (4.7) call:
`pyinstaller --target-arch universal2 --onefile test.py`

gives `main executable failed strict validation` error
If I strip the signing call in the api.py file, the pyinstaller call completes.

```python
65 INFO: PyInstaller: 4.7
65 INFO: Python: 3.8.2
76 INFO: Platform: macOS-11.6-x86_64-i386-64bit
78 INFO: wrote /Users/danhuang/projects/pyinstaller_test/test.spec
81 INFO: UPX is not available.
82 INFO: Extending PYTHONPATH with paths
['/Users/danhuang/projects/pyinstaller_test']
228 INFO: checking Analysis
242 INFO: checking PYZ
246 INFO: EXE target arch: universal2
246 INFO: Code signing identity: None
246 INFO: checking PKG
247 INFO: Building because codesign_identity changed
247 INFO: Building PKG (CArchive) test.pkg
2986 WARNING: Cannot find path @executable_path/../Python3 (needed by /Library/Developer/CommandLineTools/usr/bin/python3)
5168 INFO: Building PKG (CArchive) test.pkg completed successfully.
5171 INFO: Bootloader /Library/Python/3.8/site-packages/PyInstaller/bootloader/Darwin-64bit/run
5171 INFO: checking EXE
5171 INFO: Building because codesign_identity changed
5171 INFO: Building EXE from EXE-00.toc
5172 INFO: Copying bootloader EXE to /Users/danhuang/projects/pyinstaller_test/dist/test
5172 INFO: Converting EXE to target arch (universal2)
5174 INFO: Removing signature(s) from EXE
5202 INFO: Appending PKG archive to EXE
5208 INFO: Fixing EXE headers for code signing
5220 WARNING: Cannot find path @executable_path/../Python3 (needed by /Library/Developer/CommandLineTools/usr/bin/python3)
5226 INFO: Rewriting the executable's macOS SDK version (11.3.0) to match the SDK version of the Python library (11.0.0) in order to avoid inconsistent behavior and potential UI issues in the frozen application.
5230 INFO: Re-signing the EXE
5230 INFO: Building EXE from EXE-00.toc completed successfully.
```

Signing separately gives same error for universal2 only.
codesign -s "-" --force --all-architectures --timestamp --options=runtime dist/test                                               
dist/test: main executable failed strict validation

**Comment by rokm** [comment]
Thanks @danhuang-ixia, I've now reproduced the error locally as well.

**Comment by rokm** [comment]
Can you check if the fix in #6398 works for you?

**Comment by danhuang-ixia** [comment]
@rokm Yes, that fix worked for me.
Thanks!

**Comment by dofamin-1** [comment]
@suryakumaran2611 Any solution up there?
I'm getting the same error from 'numpy', cpython-39-darwin.so is not a fat binary!
I tried with Python 3.9  and 3.10 as well ('Unversal2 Python from Python.org')
And with different versions of Pyinstaller, starting from 4.8 to 5.1.
Nothing helps...

Simple script to Reproduce: Just install numpy (any version), import it, and run that with pyinstaller (targ-arch universal2)
I tried with Mac Apple Silicon (M1) and Apple Intel as well, I'm getting the same error anywhere!
Any help will be appreciated, thanks

Getting the similar issues (is not a fat binary!) for Opencv, and Pillow as well....

**Comment by rokm** [comment]
@dofamin-1 You cannot build `universal2` applications using `numpy`, because `numpy` wheels are single-arch only.

EDIT: same goes for `opencv` and `pillow`.

**Comment by dofamin-1** [comment]
@rokm thanks a lot for fast response!
but damn, that hurts.
I've been scratching my head over this for 3 days...
and there is no way we can get around this?
No any further release or something else?

**Comment by bwoodsend** [comment]
You might if you were extremely determined try building NumPy from source using a universal2 build of Python. But if that doesn't work then no. This is a problem with the universal2 approach in general - it's viral - if any of your dependencies aren't universal2 then you're stuffed.

**Comment by bwoodsend** [comment]
I'd stick to just building x86_64 if I were you - the more developers that refuse to or unable to do the cartwheels Apple insist that we currently do, the more likely they are to provide a more practical solution.

**Comment by rokm** [comment]
You need the binaries shipped with those packages to be `universal2`; so unless you can rebuild them all in  `universal2` mode, then no. Well, I suppose you could also manually unpack both single-arch wheels and stitch arch slices of the offending binaries together using `lipo`, but I imagine this won't be a very fun activity...

I suppose you're better off building an `x86_64` and an `arm64` variant of your application in respective single-arch python environments. For complex applications, I see little benefit of doubling your program size to accommodate both architectures... 

Or, a pure `x86_64` build will run both on older hardware and under rosetta on M1.

**Comment by dofamin-1** [comment]
@rokm , @bwoodsend thanks a lot for helping me figure this out! I really appreciate it..
As far as I understood the easiest way for now is to build for `x86_64` and `arm64` separately .
