### ISSUE TITLE
Error when running exe-file with speech_recognition?

### ISSUE THREAD

**Issue by Rapid1898-code** [pyinstaller/pyinstaller#6385]
Try to compile an exe-file including the python-module speech_recognition:
`pyinstaller --onefile checkSpeed.py`

I get this error-information when running the exe-file:
```
C:\Users\Polzi\Documents\DEV\Fiverr\TRY\diego_barny>checkSpeed.exe
Traceback (most recent call last):
  File "checkSpeed.py", line 5, in <module>
    import speech_recognition as sr
ModuleNotFoundError: No module named 'speech_recognition'
[20356] Failed to execute script checkSpeed
```

### Context information (for bug reports)
pyinstaller                4.7
Python 3.9.2
Windows 10

**Comment by rokm** [comment]
If a top-level module/package cannot be found at runtime, this means that the package was not visible to PyInstaller during the freeze process. Which usually means that you have your (virtual) environments mixed up (i.e., the pyinstaller.exe shim belongs to a different python installation or virtual environment than you think you are currently using). Try running pyinstaller from your current python environment via `python -m PyInstaller` instead of using the shim to see if that's the case.

At any rate, I cannot reproduce the problem here - `speech_recognition` is properly collected in my case.

**Comment by Rapid1898-code** [comment]
Thanks for your response - but i am not sure if i understand this right - 

As you expect i am in my virtual environment called "testing".
When i try to run `python -m PyInstaller` i get an error-message:
`C:\Users\Polzi\Documents\DEV\.venv\testing\Scripts\python.exe: No module named pyinstaller`

But i have installed the pyinstaller in the virtual env "testing" - i can see in pip list:
`pyinstaller                4.7`
`SpeechRecognition          3.8.1`

And i try to compile this with
pyinstaller --onefile xyz.py

Still not clear why this is not working,,.,

**Comment by rokm** [comment]
What output do you get if you run the following command: `where pyinstaller`?

EDIT: and `where pip`, `where python` for that matter?

**Comment by Rapid1898-code** [comment]
```
$ where pyinstaller
C:\Users\Polzi\Documents\DEV\.venv\Testing\Scripts\pyinstaller.exe
C:\Users\Polzi\AppData\Local\Programs\Python\Python39\Scripts\pyinstaller.exe
```

**Comment by Rapid1898-code** [comment]
```
$ where python
C:\Users\Polzi\Documents\DEV\.venv\Testing\Scripts\python.exe
C:\Users\Polzi\AppData\Local\Programs\Python\Python39\python.exe
C:\Users\Polzi\AppData\Local\Microsoft\WindowsApps\python.exe

$ where pip
C:\Users\Polzi\Documents\DEV\.venv\Testing\Scripts\pip.exe
C:\Users\Polzi\AppData\Local\Programs\Python\Python39\Scripts\pip.exe
```

**Comment by rokm** [comment]
So you have two versions of pyinstaller installed - one in your venv, one in your base python installation. And you probably end up running the "wrong" pyinstaller.exe.

>  C:\Users\Polzi\Documents\DEV\.venv\testing\Scripts\python.exe: No module named pyinstaller

Try running `python -m PyInstaller`, but be careful about capitalization as python module names are case-sensitive.

**Comment by Rapid1898-code** [comment]
```
$ python -m PyInstaller
The 'enum34' package is an obsolete backport of a standard library package and is incompatible with PyInstaller. Please `pip uninstall enum34` then try again.
(testing) 
```

**Comment by rokm** [comment]
Uninstall the `enum34`, like the error message says.

**Comment by Rapid1898-code** [comment]
With this command
`python -m PyInstaller --onefile xyz.py`
it finally worked

only `pyinstaller --onfile xyz.py` is still not working

Thanks a lot.

But what is the difference between
`pyinstaller --onfile xyz.py`
and
`python -m PyInstaller --onefile xyz.py`

Why is he using obivously another version with the first statement when i am in my activated virtual environment?

**Comment by rokm** [comment]
> But what is the difference between

pyinstaller.exe is just a convenience script generated by setuptools when you install the pyinstaller package. Internally, it invokes the PyInstaller module in the same way as when you do it via `python -m PyInstaller`. The module invocation is longer to write, but less error prone in cases when there are multiple pyinstaller installations present on the system.

> Why is he using obivously another version with the first statement when i am in my activated virtual environment?

No idea; based on the output of `where pyinstaller` I would also expect Windows to pick up the `pyinstaller.exe` from your virtual environment... 

On the other hand, you could uninstall pyinstaller from your base python environment, as it sounds like you don't need it. Then there will be only one `pyinstaller.exe` in `PATH` and you won't have problems with mix-ups...
