### ISSUE TITLE
PyInstaller 2.0 is not embedding manifests into generated EXE files

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#639]
**Original date**: 2012/12/07
**Original reporter**: *CB*

The output folder gains output.exe and output.exe.manifest. Though the manifest has been correctly generated, I would have expected it to be embedded in the created EXE file.

I seem to recall this being done pre-2.0, is there any reason for the change?

**Comment by htgoebel** [comment]
Fixed for onefile-mode, see https://github.com/pyinstaller/pyinstaller/issues/692#issuecomment-68191797 and #149.
