### ISSUE TITLE
Error when opening my exe in bootloader

### ISSUE THREAD

**Issue by EyuphanMandiraci** [pyinstaller/pyinstaller#6392]
My build code is: 
pyinstaller --noconfirm --onefile --console --name "MPDB Beta 5" --log-level "ERROR" --debug "all" --add-data "C:/Users/thekr/Desktop/MPDBBeta5/data.py;." --add-data "C:/Users/thekr/Desktop/MPDBBeta5/forge_download.py;." --add-data "C:/Users/thekr/Desktop/MPDBBeta5/funcs.py;." --add-data "C:/Users/thekr/Desktop/MPDBBeta5/get_ram.py;." --add-data "C:/Users/thekr/Desktop/MPDBBeta5/mail.py;." --add-data "C:/Users/thekr/Desktop/MPDBBeta5/rpc.py;." --add-data "C:/Users/thekr/Desktop/MPDBBeta5/web_request.py;." --add-data "C:/Users/thekr/Desktop/MPDBBeta5/threads;threads/" --add-data "C:/Users/thekr/Desktop/MPDBBeta5/ui;ui/" --hidden-import "discord_rpc" --hidden-import "minecraft_launcher_lib" --hidden-import "psutil" --hidden-import "pypresence" --hidden-import "PyQt5" --hidden-import "requests" --hidden-import "urllib3" --hidden-import "wget"  "C:/Users/thekr/Desktop/MPDBBeta5/mpdb.py"

After this error program closed. (I upload error as txt) (This happens in --onedirectory too)
[error.txt](https://github.com/pyinstaller/pyinstaller/files/7613889/error.txt)

**Comment by bwoodsend** [comment]
PyInstaller and `wget` are not in the same virtual environment. Pick an environment, `python -m pip install` your dependencies plus PyInstaller into it, then invoke PyInstaller via `python -m PyInstaller mpdb.py`.
