### ISSUE TITLE
ModuleNotFoundError: No module named 'pydicom.encoders.gdcm' when pydicom==2.2.2

### ISSUE THREAD

**Issue by AlexHex7** [pyinstaller/pyinstaller#6400]
Hi,  

My os is

    Linux ubuntu 5.4.0-80-generic #90~18.04.1-Ubuntu

My code is **temp.py**

    # temp.py
    import pydicom
    import os

    print('Hello World!!!')

The env is

    pip list | grep pyinstaller
    pyinstaller               4.5.1
    pyinstaller-hooks-contrib 2021.4

    pip list | grep pydicom
    pydicom                   2.2.2

Run command

    pyinstaller -F temp.py 

    5311 WARNING: Hidden import "pkg_resources.py2_warn" not found!
    5311 WARNING: Hidden import "pkg_resources.markers" not found!
    5742 WARNING: Conda distribution 'numpy', dependency of 'numpy', was not found. If you installed this distribution with pip then you may ignore this warning.
    5742 WARNING: Hidden import "six" not found!
    7057 WARNING: Cannot find libgfortran-2e0d59d6.so.5.0.0 (needed by xxxx/python3.8/site-packages/numpy/core/../../numpy.libs/libopenblasp-r0-2d23e62b.3.17.so)
    7074 WARNING: Cannot find libquadmath-2d0c479f.so.0.0.0 (needed by xxxx/python3.8/site-packages/numpy/core/../../numpy.libs/libgfortran-2e0d59d6.so.5.0.0)
    
Run the programm, the error is

    ./dist/temp

    ModuleNotFoundError: No module named 'pydicom.encoders.gdcm'
    [28325] Failed to execute script 'temp' due to unhandled exception!

Fallback **pydicom** version
 
    pip install pydicom==2.0.0

    pip list | grep pydicom
    pydicom                   2.0.0

Re-run command, it works

    rm -r build/ dist/ temp.spec

    pyinstaller -F temp.py 

    5311 WARNING: Hidden import "pkg_resources.py2_warn" not found!
    5311 WARNING: Hidden import "pkg_resources.markers" not found!
    5742 WARNING: Conda distribution 'numpy', dependency of 'numpy', was not found. If you installed this distribution with pip then you may ignore this warning.
    5742 WARNING: Hidden import "six" not found!
    7057 WARNING: Cannot find libgfortran-2e0d59d6.so.5.0.0 (needed by xxxx/python3.8/site-packages/numpy/core/../../numpy.libs/libopenblasp-r0-2d23e62b.3.17.so)
    7074 WARNING: Cannot find libquadmath-2d0c479f.so.0.0.0 (needed by xxxx/python3.8/site-packages/numpy/core/../../numpy.libs/libgfortran-2e0d59d6.so.5.0.0)

    ./dist/temp
    Hello World!!!

**Comment by bwoodsend** [comment]
```
pyinstaller -F --hiddenimport=pydicom.encoders.gdcm temp.py
```

**Comment by AlexHex7** [comment]
> ```
> pyinstaller -F --hiddenimport=pydicom.encoders.gdcm temp.py
> ```

Thanks for your reply.

But another error comes up

    ModuleNotFoundError: No module named 'pydicom.encoders.pylibjpeg'
    [3333] Failed to execute script 'temp' due to unhandled exception!

**Comment by rokm** [comment]
`pyinstaller -F --hiddenimport=pydicom.encoders.gdcm --hiddenimport=pydicom.encoders.pylibjpeg temp.py `?
or
`pyinstaller -F --collect-submodules=pydicom temp.py ` if there are many indirect imports within the `pydicom` package...

**Comment by AlexHex7** [comment]
> 

@bwoodsend @rokm Thanks, it works!

**Comment by cyb666abc** [comment]
管用 @rokm @AlexHex7
