### ISSUE TITLE
Option to not fork the process

### ISSUE THREAD

**Issue by josnyder-rh** [pyinstaller/pyinstaller#6407]
**Is your feature request related to a problem? Please describe.**
I'm running PyInstaller as PID=1 in a container, and there are certain special rules that apply to PID=1 processes in a container. I can't use PyInstaller for my purpose if it is going to fork process and run my actual workload as a child process. 

**Describe the solution you'd like**
I would like PyInstaller to have a mode where it does not `fork()` at all. I believe this is possible by setting environment variables and then calling `exec()` to create a new Python interpreter. I don't think this is easily achievable with the `-F` flag (because something needs to be left over to clean up the unpacked temporary directory), but I believe I have it working with `-D`.

**Describe alternatives you've considered**
Right now I have written a custom bootloader that replaces the PyInstaller bootloader. It sets various environment variables (including `_MEIPASS2`) and then `execve()`'s my PyInstaller binary. It's working great, but I would love to have it upstreamed.

**Comment by bwoodsend** [comment]
I don't see how this is possible. `LD_LIBRARY_PATH` needs to be be configured before startup or none of the .so files will be able to find one another (don't ask me why - it's one of Unix's less intelligent design decisions) which is why we need a parent process to set up the environment for the child process to run.

**Comment by rokm** [comment]
I like this idea. If we can set up the environment (`_MEIPASS` and especially `LD_LIBRARY_PATH`) and then restart/replace the bootloader process with `exec` without a `fork`, then we can make the `onedir` linux builds single-process, same as their Windows and macOS counterparts. Not as an option (I don't like the idea of yet another operation mode), but rather as replacement for the current two-process model (which for `onedir` we have only on linux).
