### ISSUE TITLE
Tuple index out of range when importing matplotlib

### ISSUE THREAD

**Issue by elektrobjorn** [pyinstaller/pyinstaller#6424]
I try to generate a standalone from a Python program that imports matplotlib. This causes about two pages of error messages, ending with "IndexError: tuple index out of range". See errorlog.txt.
The error occurs even with a one line program (see minimal.py.txt):
    import matplotlib.pyplot as plt
The same error occurs when the Python program has some content and actually uses matplotlib (see bugexample.py.txt)

PyInstaller: 5.0.dev0
Python: 3.10.0
Matplotlib 3.5.0
Windows-10-10.0.19043-SP0

[bugexample.py.txt](https://github.com/pyinstaller/pyinstaller/files/7698683/bugexample.py.txt)
[minimal.py.txt](https://github.com/pyinstaller/pyinstaller/files/7698665/minimal.py.txt)
[errorlog.txt](https://github.com/pyinstaller/pyinstaller/files/7698667/errorlog.txt)

**Comment by rokm** [comment]
That's python 3.10.0 bug - see #6301.

Upgrading to 3.10.1 should fix it.
