### ISSUE TITLE
Found some syntax errors when building executable files using psycopg2 while it does not have syntax error at all.

### ISSUE THREAD

**Issue by y-Adrian** [pyinstaller/pyinstaller#6434]
## Description of the issue
It shows syntax errors when building executable files using psycopg2 while it does not have syntax error at all.
### Context information (for bug reports)

* Output of `pyinstaller --version`: `4.7`
* Version of Python: 3.7.9
* Platform: openEuler 20.03 (LTS-SP1)
* How you installed Python: It was there after I installed the system.
* Did you also try this on another platform? Does it work there?
I didn't found this on CentOS7.6, it worked very well on that platform. I installed pyinstaller with pip using the command `pip install pyinstaller` on both platform.
The version of psycopg2 is 2.5.4 and I installed it with the command `pip install --ignore-installed psycopg2==2.5.4`

### A minimal example program which shows the error
```
I found this error after I run the command `pyinstaller patroni.spec`
```
### Stacktrace / full error message

```
Syntax error in /usr/local/lib64/python3.7/site-packages/psycopg2/__init__.py
('invalid syntax',('/usr/local
Syntax error in /usr/local/lib64/python3.7/site-packages/psycopg2/__init__.py', 104, 59, 'connection_factory=None, cursor_factory=None, async=False, **kwargs):\n'))
```

**Comment by rokm** [comment]
Why `psycopg2` 2.5.4? Does that even support python 3.7?

**Comment by y-Adrian** [comment]
> Why `psycopg2` 2.5.4? Does that even support python 3.7?

Er, I don't know it clearly, but it seems working well on CentOS 7.6 with python3. I install psycopg2 with pip, and the pip is the version for python3, would that be a problem?

**Comment by rokm** [comment]
I don't know. But `SyntaxError` is usually thrown directly by python interpreter, so I doubt the problem, whatever it really is, is related to PyInstaller.

**Comment by bwoodsend** [comment]
Can you share the full build log - that can't be all it has to say.

**Comment by HoLo-Debris** [comment]
> Can you share the full build log - that can't be all it has to say.
![Uploading image.png…]()

**Comment by y-Adrian** [comment]
> Can you share the full build log - that can't be all it has to say.

![image](https://user-images.githubusercontent.com/34963138/146314530-3b36dacb-6443-414f-8937-fea931f2f6fc.png)

**Comment by bwoodsend** [comment]
Copy/pase the console output. No screenshots please.

**Comment by rokm** [comment]
Can you also attach (not copy & paste, but attach!) the `/usr/local/lib64/python3.7/site-packages/psycopg2/__init__.py` file here?

**Comment by rokm** [comment]
The error is coming from [here](https://github.com/pyinstaller/pyinstaller/blob/41842f5ad31dd33d7ba4ae03daace2287c80dcb7/PyInstaller/building/utils.py#L605-L608), which is a bit odd - I would expect it to be also raised at an earlier point during the analysis...

**Comment by y-Adrian** [comment]
> Copy/pase the console output. No screenshots please.

I am really sorry but I can't copy it out from my cloud server without permission.

**Comment by y-Adrian** [comment]
> Can you also attach (not copy & paste, but attach!) the `/usr/local/lib64/python3.7/site-packages/psycopg2/__init__.py` file here?

I install psycopg2 with the command `pip install --ignore-installed psycopg2==2.5.4`, and the file doesn't have syntax error at all, it works well on another machine, which using the same code.

**Comment by rokm** [comment]
> I install psycopg2 with the command pip install --ignore-installed psycopg2==2.5.4, and the file doesn't have syntax error at all, it works well on another machine, which using the same code.

Alright, can you compute an md5 or sha256 hash of the file, then? Just so we know we're looking at the same file?

**Comment by rokm** [comment]
> it works well on another machine, which using the same code.

All the more reason to believe that the issue is specific to the environment in question...

**Comment by HoLo-Debris** [comment]
I get this after I run the command `md5sum __init__.py`
6fa06d083d9a8cd685da311561742eea __init__.py

**Comment by y-Adrian** [comment]
> > I install psycopg2 with the command pip install --ignore-installed psycopg2==2.5.4, and the file doesn't have syntax error at all, it works well on another machine, which using the same code.
> 
> Alright, can you compute an md5 or sha256 hash of the file, then? Just so we know we're looking at the same file?

I got this after I run the command `md5sum __init__.py`
6fa06d083d9a8cd685da311561742eea \_\_init\_\_.py

**Comment by rokm** [comment]
What about the machine where it works? What's the `md5sum` there?

For the reference, in unpacked `psycopg2-2.5.4.tar` I get (for corresponding `lib/__init__.py`):
```
50b3292d5cc7cacd867c3e275fa4e29e  lib/__init__.py
```
and same for the git checkout at `2_5_4` tag.

(I cannot install the wheel directly, because my postgresql lib is too recent for that old psycopg2 version).

**Comment by y-Adrian** [comment]
@rokm 
I got the same result as yours when I run the command `md5 __init__.py` on my Mac, but on all of my three linux server I got `6fa06d083d9a8cd685da311561742eea` with the command `md5sum __init__.py`. There must be something wrong with my exvironment.

**Comment by rokm** [comment]
Try copying both versions of the file to the same computer, and run `diff` to see what the difference is.

**Comment by y-Adrian** [comment]
> Try copying both versions of the file to the same computer, and run `diff` to see what the difference is.

They are totally same. If I use `psycopg2-binary` instead I won't get the problem.

**Comment by rokm** [comment]
> They are totally same.

They cannot be totally the same and have different hashes. They could differ in line endings, which would be unnoticeable but may result in a syntax error...

**Comment by y-Adrian** [comment]
> They cannot be totally the same and have different hashes.

I mean the file mentioned in the syntax error issue is totally the same with that in my another server, they has the same hash. But it is different with the hash I got on my Mac.

**Comment by rokm** [comment]
Mystery solved.

The `__init__.py` from .tar.gz has indeed checksum `50b3292d5cc7cacd867c3e275fa4e29e` but once installed via `pip`, it gets `6fa06d083d9a8cd685da311561742eea` due to automatic rewrite of an `kwargs.iteritems()` into `kwargs.items()`. That has nothing to do with the invalid syntax error, though.

The invalid syntax error is raised due to `psycopg2.connect` function having an argument called `async`, which is a reserved keyword in contemporary python. So the error is in fact due to an attempt to use an ancient version of `psycopg2` that does not support python3.7, and has nothing to do with PyInstaller (running `import psycopg2` in python shell will raise the same error).

**Comment by y-Adrian** [comment]
> 

Thank you so much.
