### ISSUE TITLE
web3 + pyinstaller

### ISSUE THREAD

**Issue by MrCanan** [pyinstaller/pyinstaller#6442]
Hi,

```
from web3 import Web3

web3_provider = Web3.HTTPProvider('https://bsc-dataseed.binance.org/')
web3 = Web3(web3_provider)
web3_status = web3.isConnected()

print(web3_status)
```

`pyinstaller --clean --strip --onefile test_web3.py`

Without pyinstaller, web3_status is true every time, so it is normal.
But with pyinstaller, it is ALWAYS false, so there is a problem.

It is for sure a setting of pyinstaller.
Any ideas?

Best regards.

**Comment by rokm** [comment]
It's not like we have the issue template just for the sake of it... What OS, what python version, what pyinstaller version? And, have you tried without `--strip`?

**Comment by MrCanan** [comment]
Hi,

OS: Ubuntu 18.04
Python: 3.6.9
PyInstaller: lastest
Result of your answer: No change without strip parameter

Best regards.

**Comment by rokm** [comment]
Works as expected here, with `web3` and `pyinstaller` installed via `pip install` in a clean `venv` on Ubuntu 18.04 with python 3.6.9

**Comment by MrCanan** [comment]
You say, it works for you? Share me your files (py and compile one) and command line to compile, to let me see.

I am on a fresh VM on VirtualBox, so I have already a clean install.
web3.isConnected() return me true when executing py file, and false after pyinstaller usage.
So I write the problem here to find a solution. ^^

**Comment by rokm** [comment]
[pyi-6442.zip](https://github.com/pyinstaller/pyinstaller/files/7736873/pyi-6442.zip)

**Comment by MrCanan** [comment]
It works with your files, but not mine, even if there seems identical ^^
I close and will try to find the reason why
Thank you for your help and patience =)
