### ISSUE TITLE
Stuck at 547 INFO: Building PKG (CArchive) App.pkg in onefile mode

### ISSUE THREAD

**Issue by Space-Gamer** [pyinstaller/pyinstaller#6455]
## Description of the issue
Taking more than an hour (full tme not known since I had to kill) to compile main file with a couple of data files. Works smoothly in non-onefile mode.
### Context information (for bug reports)
Happens after modifying spec file and running `python -m PyInstaller App.spec`. (Although, same modification of spec file worked for non-onefile mode.)
* Output of 4.7 : ```547 INFO: Building PKG (CArchive) App.pkg
 Compiling D:\App Single File\PC V-2.12\main_kivy.py```
* Version of Python: 3.9.5
* Platform: Windows 10 Pro English United States
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Not Tried

**Comment by Space-Gamer** [comment]
> ## Description of the issue
> Taking more than an hour (full tme not known since I had to kill) to compile main file with a couple of data files. Works smoothly in non-onefile mode.
> 
> ### Context information (for bug reports)
> Happens after modifying spec file and running `python -m PyInstaller App.spec`. (Although, same modification of spec file worked for non-onefile mode.)
> 
> * Output of 4.7 : `547 INFO: Building PKG (CArchive) App.pkg  Compiling D:\App Single File\PC V-2.12\main_kivy.py`
> * Version of Python: 3.9.5
> * Platform: Windows 10 Pro English United States
> * How you installed Python: python.org/downloads
> * Did you also try this on another platform? Does it work there? Not Tried

Hey, I forgot to mention, my app uses latest Kivy for GUI. And my main file is 40kb in size.

**Comment by rokm** [comment]
And how large was the generated dist directory in onedir (non-onefile) mode?

**Comment by Space-Gamer** [comment]
> And how large was the generated dist directory in onedir (non-onefile) mode?
112 MB. Also some other bug or something ig.. I left the packaging at the above mentioned state for 3-4 hours and it filled my disk with the App.pkg file in build folder (took the whole 349GB)!

**Comment by Space-Gamer** [comment]
@bwoodsend Please mention what further info you need. I will do my best to provide them!

**Comment by rokm** [comment]
Can you attach Analysis-00.toc and PKG-00.toc from the `build` directory, then? Or inspect them yourself, and see what is getting pulled into the PKG. Also, what modification did you do on your .spec to trigger this?
