### ISSUE TITLE
Nested bundling causes infinite loop

### ISSUE THREAD

**Issue by henryreed** [pyinstaller/pyinstaller#6462]
## Description of the issue

I am attempting to follow the official guide [here](https://pyinstaller.readthedocs.io/en/stable/usage.html#running-pyinstaller-from-python-code) to bundle a .py file into a .exe, except I wish to do this from an already-bundled executable.

### A minimal example program which shows the error

Given the file `entry.py` in `C:\Users\Admin\Desktop` containing:
```python
import PyInstaller.__main__

print("Hello, world! It is inception time.")

PyInstaller.__main__.run([
    'C:\\Users\\Admin\\Desktop\\helloworld.py',
    '--onefile',
    '--windowed',
    '--distpath',
    'C:\\Users\\Admin\\Desktop'
])
```

And the file `helloworld.py` in `C:\Users\Admin\Desktop` containing:
```python
print("Hello, world!")
```

I bundle `entry.py` with `pyinstaller --onefile .\entry.py`

Executing entry.exe yields an infinite loop, which keeps spawning entry.exe processes, and helloworld.exe is never bundled. I tried using `--hidden-import=PyInstaller` and `--collect-all PyInstaller` when bundling `entry.py` but the result was the same as below.

### Stacktrace / full error message

```
(venv) PS C:\Users\Admin\Desktop> .\dist\entry.exe
Hello, world! It is inception time.
84 INFO: PyInstaller: 5.0.dev0
84 INFO: Python: 3.10.1
84 INFO: Platform: Windows-10-10.0.19043-SP0
84 INFO: wrote C:\Users\Admin\Desktop\helloworld.spec
84 INFO: UPX is not available.
84 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Admin\\Desktop']
Hello, world! It is inception time.
69 INFO: PyInstaller: 5.0.dev0
69 INFO: Python: 3.10.1
84 INFO: Platform: Windows-10-10.0.19043-SP0
84 INFO: wrote C:\Users\Admin\Desktop\helloworld.spec
84 INFO: UPX is not available.
84 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Admin\\Desktop']
Hello, world! It is inception time.
68 INFO: PyInstaller: 5.0.dev0
68 INFO: Python: 3.10.1
84 INFO: Platform: Windows-10-10.0.19043-SP0
84 INFO: wrote C:\Users\Admin\Desktop\helloworld.spec
84 INFO: UPX is not available.
84 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Admin\\Desktop']
Hello, world! It is inception time.
68 INFO: PyInstaller: 5.0.dev0
68 INFO: Python: 3.10.1
68 INFO: Platform: Windows-10-10.0.19043-SP0
68 INFO: wrote C:\Users\Admin\Desktop\helloworld.spec
84 INFO: UPX is not available.
84 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Admin\\Desktop']
Hello, world! It is inception time.
53 INFO: PyInstaller: 5.0.dev0
53 INFO: Python: 3.10.1
68 INFO: Platform: Windows-10-10.0.19043-SP0
68 INFO: wrote C:\Users\Admin\Desktop\helloworld.spec
68 INFO: UPX is not available.
68 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Admin\\Desktop']
```

You can also see multiple processes being spawned as a result of running `entry.exe`:
```
PS C:\Users\Admin> Get-Process entry

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
     60       5     1260       4236       0.81    856   1 entry
    170      15    20868      27620       0.27    940   1 entry
    158      15    21048      27672       0.30   3332   1 entry
     68       4     1240       4228       0.80   4492   1 entry
     80       5     1256       4268       0.92   5576   1 entry
    150      15    20772      27364       0.19   6556   1 entry
    162      15    20920      27520       0.23   7444   1 entry
     76       4     1232       4232       0.98   8276   1 entry
    154      15    20324      27020       0.23   8600   1 entry
     72       4     1260       4256       0.92   8892   1 entry
     64       5     1260       4252       0.83   9076   1 entry
    166      15    20472      27124       0.25  10176   1 entry
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: ```Python 3.10.1```
* Platform: ```Windows en//US```
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? I did not try another platform as the scope of my project is limited to Windows.

**Comment by rokm** [comment]
>  except I wish to do this from an already-bundled executable.

Nope, this won't work.

PyInstaller internally uses a lot of sub-processes where it is assumed that `sys.executable` points to a python interpreter (e.g., [here](https://github.com/pyinstaller/pyinstaller/blob/cab6bda6df73dca0f39be33d97416cd25219f910/PyInstaller/compat.py#L513-L514)); this is not true in a frozen application, where it points to the frozen executable, which ends up in effectively endless recursion.

Even if this was not a problem, the frozen application includes only a subset of python environment, so it cannot be used to freeze an arbitrary script (not to mention the issue of 3rd party packages).

So whatever use case you have for this, it cannot be supported by PyInstaller.

**Comment by henryreed** [comment]
@rokm Understood--thank you for the prompt response and have a great holiday!
