### ISSUE TITLE
Windows 10 version 32 bit on Virtualbox error

### ISSUE THREAD

**Issue by czonta96** [pyinstaller/pyinstaller#6464]
Running under Python 3.7
Error: exception handling in line 49 "No module called ctypes"
But ctypes win32 is instead actually on system, how do you deal with this?

This issue is not happening at all on a 64 bit version of Windows 10 native main system which is running Python 3.9
Is that a problem related to my Python version? I am really confused, help

**Comment by czonta96** [comment]
Can someone fucking help please? It's since yesterday I'm fighting with this and I tried all

**Comment by bwoodsend** [comment]
If you want help then you need provide [the necessary details](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md). All you've essentially told is that you've had a bad day.
