### ISSUE TITLE
Regarding OPCDA Client with OpenOPC ( Executable EXE developed using PyInstaller / py2exe ) is not able to communicate to the server. - opc.read('Tag') function is not called and throwing the below erros

### ISSUE THREAD

**Issue by rajnishnationfirst** [pyinstaller/pyinstaller#6466]
Hi colleagues . 

I need a kind help for the below scenarios . It will be very good of you if you can pls help me for the same

1) I have developed a OPC DA client with all necessary softwares installed on my PC .
2) Below is the code when i run on PYCHARM , its runs successfully as shown below in the below snap with WHITE Editor and EXE OPC DA client in BLACK SCREEN..

4 A) But when develop the same client as an standalone EXE file -build using PyInstaller . the apps gives the below errors as :
Outer Loop Minute Change
Postgre SQL Connection Opened
['Simulation Items', 'Configured Aliases']
**pythoncom error: Failed to setup call into Python gateway

ModuleNotFoundError: No module named 'win32timezone'**

AND  

4 B) But when develop the same client as an standalone EXE file -build using PyInstaller . the apps gives the below errors as :

Outer Loop Minute Chnage
Postgre SQL Connection Opened
Hour Data Exception Error in transction Reverting all other operations of a transction**----  '{F8582D25-88FB-11D0-B850-**00C0F0104305}'
STD CYCLE DATA DONE
ELSE BLOCK SHIFT WISE
Inner Loop Minute Change 20
Postgre SQL Connection Closed
Outer Loop Minute Chnage

Python Code :

        opc = OpenOPC.client()
        ser = opc.servers()
        var = opc.connect('Matrikon.OPC.Simulation.1', 'localhost')
        print(opc.list())
        opc_value_per_tag = opc.read('Random.Int1')[0]
        print(opc_value_per_tag)
Pls suggest and help colleagues as i have bbeen struggling since 10-15 days , but this platform is the last hope where i can get help from you all.

![Pycharm-Snap (1)](https://user-images.githubusercontent.com/64892368/147412446-b27b02d9-4195-4910-880f-a38a55208758.PNG)

Pls note the below details :

I m using pywin32 -  version 303 and also tried with pywin32 228.

I also tried with installing pywin32 executable and also with PIP-pip install pywin32. ,but the issue remains the same.

Python which I m using  is version 3.7.1 - 32Bit .

Tried  building exe using pyinstaller  but failed when running the BUILD EXE CLIENT using PYINSTALLER. 

Plz suggest Jose on how can I rectify this weird problem of OpenOPC and PyInstaller.  

**---pyinstaller  processing -----**

Pls find the commands and details of the pyinstaller i am using for building the EXE.

C:\Users\z003typu\PycharmProjects\OPC_DA_Test>pyinstaller --onefile Test_DA.py
222 INFO: PyInstaller: 4.7
222 INFO: Python: 3.7.1
229 INFO: Platform: Windows-10-10.0.18362-SP0
232 INFO: wrote C:\Users\z003typu\PycharmProjects\OPC_DA_Test\Test_DA.spec
234 INFO: UPX is not available.
241 INFO: Extending PYTHONPATH with paths
['C:\\Users\\z003typu\\PycharmProjects\\OPC_DA_Test']
814 INFO: checking Analysis
872 INFO: checking PYZ
892 INFO: checking PKG
895 INFO: Building because toc changed
895 INFO: Building PKG (CArchive) Test_DA.pkg
4237 INFO: Building PKG (CArchive) Test_DA.pkg completed successfully.
4245 INFO: Bootloader c:\users\z003typu\appdata\local\programs\python\python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
4245 INFO: checking EXE
4277 INFO: Rebuilding EXE-00.toc because Test_DA.exe missing
4277 INFO: Building EXE from EXE-00.toc
4278 INFO: Copying bootloader EXE to C:\Users\z003typu\PycharmProjects\OPC_DA_Test\dist\Test_DA.exe
4311 INFO: Copying icon to EXE
4312 INFO: Copying icons from ['c:\\users\\z003typu\\appdata\\local\\programs\\python\\python37-32\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
4567 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
4577 INFO: Writing RT_ICON 1 resource with 3752 bytes
4579 INFO: Writing RT_ICON 2 resource with 2216 bytes
4581 INFO: Writing RT_ICON 3 resource with 1384 bytes
4582 INFO: Writing RT_ICON 4 resource with 37019 bytes
4583 INFO: Writing RT_ICON 5 resource with 9640 bytes
4584 INFO: Writing RT_ICON 6 resource with 4264 bytes
4585 INFO: Writing RT_ICON 7 resource with 1128 bytes
4591 INFO: Copying 0 resources to EXE
4591 INFO: Emedding manifest in EXE
4595 INFO: Updating manifest in C:\Users\z003typu\PycharmProjects\OPC_DA_Test\dist\Test_DA.exe
4773 INFO: Updating resource type 24 name 1 language 0
4829 INFO: Appending PKG archive to EXE
11103 INFO: Building EXE from EXE-00.toc completed successfully.

C:\Users\z003typu\PycharmProjects\OPC_DA_Test>

**---py2exe processing -----**

Pls find the commands and details of the py2exe i am using for building the EXE.

C:\Users\z003typu\PycharmProjects\OPC_DA_Test>python setup.py py2exe
running py2exe

  20 missing Modules
  ------------------
? SystemHealth                        imported from OpenOPC
? __main__                            imported from bdb, pdb
? _frozen_importlib                   imported from importlib, importlib.abc
? _frozen_importlib_external          imported from importlib, importlib._bootstrap, importlib.abc
? _uuid                               imported from uuid
? _winreg                             imported from platform
? cPickle                             imported from Pyro4.util
? cloudpickle                         imported from Pyro4.util
? collections.Iterator                imported from Pyro4.core
? copy_reg                            imported from Pyro4.util
? dill                                imported from Pyro4.configuration, Pyro4.util
? dummy.Process                       imported from multiprocessing.pool
? exceptions                          imported from Pyro4.util
? java.lang                           imported from platform
? msgpack                             imported from Pyro4.util
? org.python.core                     imported from copy, pickle
? os.path                             imported from ctypes._aix, os, pkgutil, py_compile, tracemalloc, unittest, unittest.util
? readline                            imported from cmd, code, pdb
? selectors2                          imported from Pyro4.socketserver.multiplexserver
? selectors34                         imported from Pyro4.socketserver.multiplexserver
Building 'dist\Test_DA.exe'.
Building shared code archive 'dist\library.zip'.
Copy c:\users\z003typu\appdata\local\programs\python\python37-32\python37.dll to dist
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\select.pyd to dist\select.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\pyexpat.pyd to dist\pyexpat.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\unicodedata.pyd to dist\unicodedata.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_socket.pyd to dist\_socket.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_bz2.pyd to dist\_bz2.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_lzma.pyd to dist\_lzma.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_hashlib.pyd to dist\_hashlib.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_ssl.pyd to dist\_ssl.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_ctypes.pyd to dist\_ctypes.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\psycopg2\_psycopg.cp37-win32.pyd to dist\psycopg2._psycopg.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32\win32wnet.pyd to dist\win32wnet.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_decimal.pyd to dist\_decimal.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_contextvars.pyd to dist\_contextvars.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32\_win32sysloader.pyd to dist\_win32sysloader.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32\win32api.pyd to dist\win32api.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_sqlite3.pyd to dist\_sqlite3.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_multiprocessing.pyd to dist\_multiprocessing.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\_queue.pyd to dist\_queue.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\Pythonwin\win32ui.pyd to dist\win32ui.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32\win32trace.pyd to dist\win32trace.pyd
Copy C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\lib\site-packages\win32\win32event.pyd to dist\win32event.pyd
Copy DLL C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\sqlite3.dll to dist\
Copy DLL C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\libssl-1_1.dll to dist\
Copy DLL C:\Users\z003typu\AppData\Local\Programs\Python\Python37-32\DLLs\libcrypto-1_1.dll to dist\
Copy ExtensionDLL C:\WINDOWS\SYSTEM32\pywintypes37.dll to dist\
Copy ExtensionDLL C:\WINDOWS\SYSTEM32\pythoncom37.dll to dist\

**Comment by rokm** [comment]
Assuming 4A is for PyInstaller, 

```
**pythoncom error: Failed to setup call into Python gateway

ModuleNotFoundError: No module named 'win32timezone'**
```

likely means that you need to add `win32timezone` to PyInstaller's hiddenimports, for example by adding `--hidden-import win32timezone` to your PyInstaller command.

**Comment by bwoodsend** [comment]
And you need to activate your virtual environment before running PyInstaller.
