### ISSUE TITLE
MacOS - Pyinstaller application changes dock icon while running 

### ISSUE THREAD

**Issue by NiTRoeSE** [pyinstaller/pyinstaller#6471]
Hi i wonder about why a app build with pyinstaller changes the icon in dock after running the app to a python icon ?
Maybe its my mistake but i don't find a solution that the app keeps the app icon while running ..

Building with this command:

` python3 -m PyInstaller  -n FritzMonitor --windowed --icon=./img/network.icns --osx-bundle-identifier=com.nitrosoft.fritzmonitor --clean --noconsole myscript.py`

![Bildschirmaufnahme 2021-12-29 um 21 27 19](https://user-images.githubusercontent.com/24574743/147701103-8f25149b-281d-4d4c-b2ec-297ff2dcf2d8.gif)

I hope someone can help or give a hint what's the problem.

MacOS Monterey 12.1
Python 3.9

Thanks in advanced

**Comment by rokm** [comment]
Can you provide a minimal code example that triggers this behavior?

**Comment by NiTRoeSE** [comment]
> Can you provide a minimal code example that triggers this behavior?

Yes for shure,... same happens with following sample code from pysimplegui:

```
import PySimpleGUI as sg

sg.theme('DarkAmber')   # Add a touch of color
# All the stuff inside your window.
layout = [  [sg.Text('Some text on Row 1')],
            [sg.Text('Enter something on Row 2'), sg.InputText()],
            [sg.Button('Ok'), sg.Button('Cancel')] ]

# Create the Window
window = sg.Window('Window Title', layout)
# Event Loop to process "events" and get the "values" of the inputs
while True:
    event, values = window.read()
    if event == sg.WIN_CLOSED or event == 'Cancel': # if user closes window or clicks cancel
        break
    print('You entered ', values[0])

window.close()


```
Build with:

` python3 -m PyInstaller  -n ExampleApp --windowed --icon=./img/network.icns --osx-bundle-identifier=com.example --clean --noconsole example.py`

**Comment by NiTRoeSE** [comment]
I think i found the problem, and it have nothing to do with pyinstaller:

https://github.com/PySimpleGUI/PySimpleGUI/issues/4509

If i give pysimplegui a default icon for all windows encoded in base64 it works.
Sorry, my fault, i thought its related to pyinstaller, but isn't.

kind regards.

/closed

**Comment by rokm** [comment]
Indeed, that python icon is the default PySimpleGUI icon.

**Comment by PySimpleGUI** [comment]
There's a front-end written in PySimpleGUI that has pyinstaller as the backend (the only one at the moment).
https://github.com/PySimpleGUI/psgcompiler

I'll make sure and put in the readme that the application's icon must be set along with the icon used by pyinstaller.  They're different as pointed out here.  I have the same kind of issue with the psgshortcut program that makes windows shortcuts.  The shortcut icon isn't the same as the "runtime icon".  This was explained in the Udemy course I just finished, but I see that I didn't explain it well in the readme.  

Thanks for the help!
