### ISSUE TITLE
Error running exe output

### ISSUE THREAD

**Issue by AbRamazani** [pyinstaller/pyinstaller#6476]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.7```
* Version of Python: 3.9.9
* Platform: Windows10
* How you installed Python: python.org/download

### A minimal example program which shows the error
I used the following command to get the exe output
```shell
pyinstaller --onefile --windowed -i myicon.ico mypythonfile.py
```
This went well until the end but some warnings were shown.
```shell
...
72813 WARNING: Hidden import "pkg_resources.py2_warn" not found!
72814 WARNING: Hidden import "pkg_resources.markers" not found!
...
76663 WARNING: Library wintab32.dll required via ctypes not found
```
Anyway, the output was taken. But when I run it, I encounter this scene:
![Eroor](https://s4.uupload.ir/files/error_al6s.png)
**what's the solution?**

**Comment by rokm** [comment]
Can you provide a minimum example that triggers this issue for you?

**Comment by AbRamazani** [comment]
> Can you provide a minimum example that triggers this issue for you?

I want to get the exe output from the mahab.py file from [this ](https://github.com/AbRamazani/mahab) repository.

**Comment by rokm** [comment]
I can't reproduce the problem here (i.e., the `win32com`/`pywintypes`/`pythoncom` components seem to be collected as expected and the runtime hook `pyi_rth_win32comgenpy` does not crash like that)...

Does running `import pywintypes` from python prompt work for you (using the same environment that you run pyinstaller from)? 

If you create a onedir build instead of onefile one (i.e., without `--onefile`), do you see `pythoncom39.dll` and `pywintypes39.dll` collected in the frozen application directory?

**Comment by AbRamazani** [comment]
> I can't reproduce the problem here (i.e., the `win32com`/`pywintypes`/`pythoncom` components seem to be collected as expected and the runtime hook `pyi_rth_win32comgenpy` does not crash like that)...
> 
> Does running `import pywintypes` from python prompt work for you (using the same environment that you run pyinstaller from)?
> 
> If you create a onedir build instead of onefile one (i.e., without `--onefile`), do you see `pythoncom39.dll` and `pywintypes39.dll` collected in the frozen application directory?

Yes `import pywintypes` works.

I see `pywintypes39.dll` but not `pythoncom39.dll`.

**Comment by rokm** [comment]
> > I can't reproduce the problem here (i.e., the `win32com`/`pywintypes`/`pythoncom` components seem to be collected as expected and the runtime hook `pyi_rth_win32comgenpy` does not crash like that)...
> > Does running `import pywintypes` from python prompt work for you (using the same environment that you run pyinstaller from)?
> > If you create a onedir build instead of onefile one (i.e., without `--onefile`), do you see `pythoncom39.dll` and `pywintypes39.dll` collected in the frozen application directory?
> 
> Yes `import pywintypes` works.
> 
> I see `pywintypes39.dll` but not `pythoncom39.dll`.

How about this snippet?

```python
import pythoncom
print(pythoncom)
```

Does it work in python prompt? What is the output?

**Comment by AbRamazani** [comment]
> > > I can't reproduce the problem here (i.e., the `win32com`/`pywintypes`/`pythoncom` components seem to be collected as expected and the runtime hook `pyi_rth_win32comgenpy` does not crash like that)...
> > > Does running `import pywintypes` from python prompt work for you (using the same environment that you run pyinstaller from)?
> > > If you create a onedir build instead of onefile one (i.e., without `--onefile`), do you see `pythoncom39.dll` and `pywintypes39.dll` collected in the frozen application directory?
> > 
> > 
> > Yes `import pywintypes` works.
> > I see `pywintypes39.dll` but not `pythoncom39.dll`.
> 
> How about this snippet?
> 
> ```python
> import pythoncom
> print(pythoncom)
> ```
> 
> Does it work in python prompt? What is the output?

Yes this snippet works and output is `<module 'pythoncom' (C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pywin32_system32\pythoncom39.dll)>`
But i run it in `virtual environment`.

**Comment by bwoodsend** [comment]
`C:\Users\username\AppData\Roaming\Python\Python39\site-packages\pywin32_system32\pythoncom39.dll` is not a virtual environment path - that's just a regular Python installation.

**Comment by rokm** [comment]
What about

```python
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
print(get_pywin32_module_file_attribute('pythoncom'))
```

If that gives you the same path as you listed above, try rebuilding your application (with added `--clean` option to force full rebuild). In the build messages, look for messages:
```
INFO: Loading module hook 'hook-pywintypes.py' from ...
```
and
```
INFO: Loading module hook 'hook-pythoncom.py' from ...
```
Do you see both? Since `pywintypes39.dll` got collected, you should see the first one. If the second one is missing, try adding `--hiddenimport pythoncom` to your pyinstaller command, and see if that changes anything.

**Comment by AbRamazani** [comment]
> What about
> 
> ```python
> from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
> print(get_pywin32_module_file_attribute('pythoncom'))
> ```
> 
> If that gives you the same path as you listed above, try rebuilding your application (with added `--clean` option to force full rebuild). In the build messages, look for messages:
> 
> ```
> INFO: Loading module hook 'hook-pywintypes.py' from ...
> ```
> 
> and
> 
> ```
> INFO: Loading module hook 'hook-pythoncom.py' from ...
> ```
> 
> Do you see both? Since `pywintypes39.dll` got collected, you should see the first one. If the second one is missing, try adding `--hiddenimport pythoncom` to your pyinstaller command, and see if that changes anything.

This time it was printed in the output of the virtual environment address.(`myprojectpath\venv\lib\site-packages\pywin32_system32\pythoncom39.dll`)

I also added `--clean` but did not see these two lines.I do not see `pythoncom39.dll` this time either.

I also added `----hiddenimport pythoncom` but it did not make a difference.

**Comment by rokm** [comment]
Can you attach the generated `build\Analysis-00.toc` file, then?

**Comment by AbRamazani** [comment]
> Can you attach the generated `build\Analysis-00.toc` file, then?

[Toc file](https://s20.picofile.com/d/8445965018/9919a769-d009-472f-a73d-4e6ae941b939/Analysis_00.toc)

**Comment by rokm** [comment]
Hmm...

So `pywintypes39.dll` is indeed collected from your virtual environment:
```
('pywintypes39.dll',
   'projectpath\\venv\\Lib\\site-packages\\pywin32_system32\\pywintypes39.dll',
   'BINARY'),
```

This is where `pythoncom39.dll` should be collected from as well. And in one of previous steps, you've confirmed that it exists there - I suppose if it did not, the `pythoncom` hook would have raised an exception anyway during the build prcoess.

So the only way I can think of for it not being collected is if the `pythoncom` hook is not run (but it should be, as we can also see that `pythoncom.py` is collected):

```
  ('pythoncom',
   'projectpath\\venv\\lib\\site-packages\\pythoncom.py',
   'PYMODULE'),
```

So, do you see a message 
```
INFO: Loading module hook 'hook-pythoncom.py' from ...
```
during the build process? 

Does the file `projectpath\venv\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pythoncom.py` exist?

---

I guess at this point, I can suggest you to either try collecting that dll file yourself using `"--add-binary projectpath\venv\Lib\site-packages\pywin32_system32\pythoncom39.dll;."`, or set up a new virtual environment from scratch and try again there.

**Comment by AbRamazani** [comment]
> Hmm...
> 
> So `pywintypes39.dll` is indeed collected from your virtual environment:
> 
> ```
> ('pywintypes39.dll',
>    'projectpath\\venv\\Lib\\site-packages\\pywin32_system32\\pywintypes39.dll',
>    'BINARY'),
> ```
> 
> This is where `pythoncom39.dll` should be collected from as well. And in one of previous steps, you've confirmed that it exists there - I suppose if it did not, the `pythoncom` hook would have raised an exception anyway during the build prcoess.
> 
> So the only way I can think of for it not being collected is if the `pythoncom` hook is not run (but it should be, as we can also see that `pythoncom.py` is collected):
> 
> ```
>   ('pythoncom',
>    'projectpath\\venv\\lib\\site-packages\\pythoncom.py',
>    'PYMODULE'),
> ```
> 
> So, do you see a message
> 
> ```
> INFO: Loading module hook 'hook-pythoncom.py' from ...
> ```
> 
> during the build process?
> 
> Does the file `projectpath\venv\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pythoncom.py` exist?
> 
> I guess at this point, I can suggest you to either try collecting that dll file yourself using `"--add-binary projectpath\venv\Lib\site-packages\pywin32_system32\pythoncom39.dll;."`, or set up a new virtual environment from scratch and try again there.

**do you see a message?** : ``No, I don't.``
**Does the file ``projectpath\venv\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pythoncom.py`` exist?** : ``Yes``
**set up a new virtual environment from scratch and try again there.** : ``I have changed the virtual environment several times.
I even tried Python 3.9.4 but it did not change.``

**Comment by rokm** [comment]
One last thing to try, then. 

What if you create a new directory in your current working directory (where you run pyinstaller from), called `extra-hooks`, and copy `projectpath\venv\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pythoncom.py` into it. 

And then run
```
pyinstaller --clean --additional-hooks-dir extra-hooks --hiddenimport pythoncom [the rest of your arguments]
```
Do you see `INFO: Loading module hook 'hook-pythoncom.py' from ...` in build log now, and is the `pythoncom39.dll` file collected?

**Comment by AbRamazani** [comment]
> One last thing to try, then.
> 
> What if you create a new directory in your current working directory (where you run pyinstaller from), called `extra-hooks`, and copy `projectpath\venv\Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-pythoncom.py` into it.
> 
> And then run
> 
> ```
> pyinstaller --clean --additional-hooks-dir extra-hooks --hiddenimport pythoncom [the rest of your arguments]
> ```
> 
> Do you see `INFO: Loading module hook 'hook-pythoncom.py' from ...` in build log now, and is the `pythoncom39.dll` file collected?

Yes, both were seen this time.

**Comment by AbRamazani** [comment]
It was finally fixed.
Thank you so much for your tips!🙏 🙏

**Comment by andrewd18** [comment]
I also ran into a similar issue with python 3.8.6 and pyinstaller 4.8 on 2022-02-03. It was complaining about pywintypes. I resolved it by uninstalling and reinstalling pypiwin32 in my venv.

```
pip uninstall pypiwin32 pywin32
pip install pypiwin32
```
This pulled in `pypiwin32-223-py3-none-any.whl` and `pywin32-303-cp38-cp38-win_amd64.whl` which has fixed the issue.
