### ISSUE TITLE
Which version of pyinstaller supports creating file as Shared Object 

### ISSUE THREAD

**Issue by Soujanya076** [pyinstaller/pyinstaller#6477]
I'm trying to executable file of elf file type 'DYN' using pyinstaller , If I build bootloader manually I'm able to create the file of type DYN
pyinstaller-4.3/bootloader
setenv CC "/usr/bin/clang -pie -fPIE" 
python ./waf distclean all -v
cd ../
python setup.py install 

root@FreeBSD113:~/ESEB_444 # file dist_hello_dyn_43/hello
dist_hello_dyn_43/hello: ELF 64-bit LSB shared object, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.3, FreeBSD-style, stripped
root@FreeBSD113:~/ESEB_444 #

-----------> But If I install pyinstaller via pip install not able to create file as shared object But in linux is different case as mentioned below 

**FreeBSD**
root@FreeBSD113:~/ESEB_444 # pip install pyinstaller==4.3

root@FreeBSD113:~/ESEB_444 # pyinstaller --onefile hello.py
58 INFO: PyInstaller: 4.3
58 INFO: Python: 3.9.5
66 INFO: Platform: FreeBSD-11.3-RELEASE-amd64-64bit-ELF
.....
root@FreeBSD113:~/ESEB_444 # file dist/hello
dist/hello: ELF 64-bit LSB executable, x86-64, version 1 (FreeBSD), dynamically linked, interpreter /libexec/ld-elf.so.1, for FreeBSD 11.3, FreeBSD-style, stripped
root@FreeBSD113:~/ESEB_444 #

**Linux**
root@gssd-ubuntu184:~/ESEB_444# pip install pyinstaller==4.3
root@gssd-ubuntu184:~/ESEB_444# pyinstaller --onefile hello.py
52 INFO: PyInstaller: 4.3
52 INFO: Python: 3.6.9
52 INFO: Platform: Linux-4.15.0-163-generic-x86_64-with-Ubuntu-18.04-bionic
53 INFO: wrote /root/ESEB_444/hello.spec
54 INFO: UPX is not available.
56 INFO: Extending PYTHONPATH with paths
....
root@gssd-ubuntu184:~/ESEB_444# file dist/hello
dist/hello: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=24675b0091f38f45c5c1c5484cf24925b439b164, stripped
root@gssd-ubuntu184:~/ESEB_444# pyinstaller --version
4.3
root@gssd-ubuntu184:~/ESEB_444#

1. **Which version of pyinstaller is supported in FreeBSD to create file as Shared Object without building bootloader manually ??**

**Comment by bwoodsend** [comment]
No version of PyInstaller has supported creating shared object files on any OS. Executables switched to using PIE (position independent executable) mode on Linux which some out of date Linux desktops mistook for shared libraries because shared libraries are generally compiled with `-fPIC` (position independent code) on Linux.

**Comment by Soujanya076** [comment]
Okay..  you mean to say if I want to create executable as elf header type as DYN,  then I need to build bootloader from source code of pyinstaller as I mentioned in the first part of the description.. 
Else if we install pyinstaller via pip .. it always creates executable as EXEC elf header type always.. 
Please confirm ...

**Comment by rokm** [comment]
We don't provide binary wheels for FreeBSD, so the bootloader gets compiled on your machine anyway.

So exporting `CC="clang -pie -fPIE"` before running `pip install pyinstaller` should give you PIE-enabled bootloaders as well. If that's not the case, you might want to clear pip's cache in case it is using locally built wheels from previous runs (where PIE was not enabled).

**Comment by Soujanya076** [comment]
Thankyou for the information
