### ISSUE TITLE
ctypes does not work in --onefile mode

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#648]
**Original date**: 2012/12/17
**Original reporter**: *pyinstaller AND m DOT allo DOT ws*

I am using:
- Windows 7
- PyInstaller2.0
- Python 2.7.3, 32-bit (from Python.org)
- Visual C++ Express 2010

I wrote a library in C and compiled it to a DLL with Visual C++ Express. Then I used ctypes to load the library in Python and call its functions.

When I run PyInstaller in --onedir mode, it copies the DLL into the dist directory and it works fine. When I run PyInstaller in --onefile mode, it does not work, the error is:
```
WindowsError: [Error 126] The specified module could not be found
```
The traceback references the exact line number where I call ctypes.cdll.LoadLibrary("my_lib.dll").

I checked the temp directory created by running the --onefile EXE, and the temp directory does indeed include the DLL. The problem is that Python doesn't look in the temp directory, Python instead looks in whatever directory contains the EXE file.

Where Python should look:
```
C:\Users\zakf\AppData\Local\Temp\_MEI8482\my_lib.dll
```
Where Python ACTUALLY looks:
```
C:\Users\zakf\pyi_builds\my_app\dist\my_app.exe
```
I managed to fix it by following these two steps:

1. Remove this code:
```
my_lib = ctypes.cdll.LoadLibrary("my_lib.dll")
```
And replace with this code:
```
temp_dir = sys._MEIPASS
lib_path = os.path.join(temp_dir, "my_lib.dll")
my_lib = ctypes.cdll.LoadLibrary(lib_path)
```
2. Because of the prior step, PyInstaller can no longer automatically detect the DLL. So you must add this to the .spec file:
```
a.binaries + [('my_lib.dll', 'path/to/dll', 'BINARY')]
```
After these two steps, the --onefile application works properly.

I have not tested it on another Windows machine yet, so I don't know if it really works. I may be missing msvcr100.dll, or who knows what. Wish me luck.

Zak Fallows

**Comment by andrek666** [comment]
In the first first step, from which file do you remove this code?

**Comment by buggywhip** [comment]
I can confirm that this problem also exists under OSX and that the OP's workaround was necessary for me to proceed.

**Comment by matysek** [comment]
This should be fixed with latest dev version. If not everywhere, please report a new issue.
