### ISSUE TITLE
OSError: [WinError 126] Cannot find the specified module. Error loading "****\dist\detectAirplane\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

### ISSUE THREAD

**Issue by wantaoliu** [pyinstaller/pyinstaller#6482]
### Context information (for bug reports)

> PS D:\DetectionFrame\20211224mmdetection\dist\detectAirplane> .\detectAirplane.exe --h
> Traceback (most recent call last):
>   File "detectAirplane.py", line 5, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "mmdet\__init__.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "mmcv\__init__.py", line 4, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "mmcv\fileio\__init__.py", line 2, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "mmcv\fileio\file_client.py", line 15, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "mmcv\utils\__init__.py", line 22, in <module>
>   File "<frozen importlib._bootstrap>", line 983, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 476, in exec_module
>   File "torch\__init__.py", line 135, in <module>
>     raise err
> OSError: [WinError 126] Cannot find the specified module. Error loading "D:\DetectionFrame\20211224mmdetection\dist\detectAirplane\torch\lib\caffe2_detectron_ops_gpu.dll" or one of its dependencies.

# Environment

> Package                   Version
> addict                    2.4.0
> albumentations            1.1.0
> altgraph                  0.17.2
> appdirs                   1.4.4
> asynctest                 0.13.0
> atomicwrites              1.4.0
> attrs                     21.2.0
> certifi                   2021.10.8
> charset-normalizer        2.0.9
> cityscapesScripts         2.2.0
> click                     7.1.2
> codecov                   2.1.12
> colorama                  0.4.4
> coloredlogs               15.0.1
> coverage                  6.2
> cycler                    0.11.0
> Cython                    0.29.25
> flake8                    4.0.1
> fonttools                 4.28.3
> future                    0.18.2
> GDAL                      3.0.2
> humanfriendly             10.0
> idna                      3.3
> imagecorruptions          1.1.2
> imageio                   2.13.2
> importlib-metadata        4.2.0
> importlib-resources       5.4.0
> iniconfig                 1.1.1
> intel-openmp              2022.0.0
> interrogate               1.5.0
> isort                     4.3.21
> jaraco.classes            3.2.1
> jaraco.collections        3.4.0
> jaraco.functools          3.4.0
> jaraco.structures         2.1.0
> jaraco.text               3.6.0
> jaraco.ui                 2.3.0
> jaraco.windows            5.7.0
> joblib                    1.1.0
> kiwisolver                1.3.2
> kwarray                   0.5.21
> macholib                  1.14
> Markdown                  3.3.6
> matplotlib                3.5.0
> mccabe                    0.6.1
> mkl-fft                   1.3.1
> mkl-random                1.2.2
> mkl-service               2.4.0
> mmcv-full                 1.4.0
> mmdet                     2.19.0
> model-index               0.1.11
> more-itertools            8.12.0
> networkx                  2.6.3
> numpy                     1.21.2
> olefile                   0.46
> onnx                      1.7.0
> onnxruntime               1.5.1
> opencv-python             4.5.5.62
> opencv-python-headless    4.5.4.60
> openmim                   0.1.5
> ordered-set               4.0.2
> packaging                 21.3
> pandas                    1.3.4
> panopticapi               0.1
> path                      16.2.0
> pefile                    2021.9.3
> Pillow                    8.4.0
> pip                       21.2.4
> pluggy                    1.0.0
> protobuf                  3.19.1
> py                        1.11.0
> pycocotools-windows       2.0.0.2
> pycodestyle               2.8.0
> pycryptodome              3.10.1
> pyflakes                  2.4.0
> pyinstaller               4.7
> pyinstaller-hooks-contrib 2021.4
> pyparsing                 3.0.6
> pyquaternion              0.9.9
> pyreadline                2.1
> pyshp                     2.1.3
> pytest                    6.2.5
> python-dateutil           2.8.2
> pytz                      2021.3
> PyWavelets                1.2.0
> pywin32                   302
> pywin32-ctypes            0.2.0
> PyYAML                    6.0
> qudida                    0.0.4
> regex                     2021.11.10
> requests                  2.26.0
> scikit-image              0.19.0
> scikit-learn              1.0.1
> scipy                     1.7.3
> setuptools                58.0.4
> setuptools-scm            6.3.2
> six                       1.16.0
> sklearn                   0.0
> tabulate                  0.8.9
> terminaltables            3.1.7
> threadpoolctl             3.0.0
> tifffile                  2021.11.2
> toml                      0.10.2
> tomli                     1.2.2
> torch                     1.10.1
> torchaudio                0.10.1
> torchvision               0.11.2
> tqdm                      4.62.3
> typing-extensions         3.10.0.2
> ubelt                     0.10.1
> urllib3                   1.26.7
> wheel                     0.37.0
> wincertstore              0.2
> xdoctest                  0.15.10
> yapf                      0.31.0
> zipp                      3.6.0

Could you tell me how to solve this problem,Please

**Comment by rokm** [comment]
Is this an anaconda environment and was `torch` installed via conda?

**Comment by yang-0201** [comment]
i meet this problem too,how to solve this

**Comment by bwoodsend** [comment]
By providing [enough information that we can help you](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by rokm** [comment]
If you're using anaconda-installed `torch`, you will probably need to ensure that `uv.dll` from conda environment's DLL directory is collected, because it won't be picked up automatically...
