### ISSUE TITLE
PyQt5 produces binaries without Wayland support [Has Workaround]

### ISSUE THREAD

**Issue by simaoafonso-pwt** [pyinstaller/pyinstaller#6483]
## Description of the issue

When you create a PyQt5 application, the Wayland Qt plugins are not included, so only Xorg is supported. If you do not force wayland to be ignored (unset `WAYLAND_DISPLAY` or set `QT_QPA_PLATFORM=xcb`), you get:

```
qt.qpa.wayland: Failed to load client buffer integration: "wayland-egl"
qt.qpa.wayland: Available client buffer integrations: ()
qt.qpa.wayland: No shell integration named "xdg-shell" found
qt.qpa.wayland: No shell integration named "xdg-shell-v6" found
qt.qpa.wayland: No shell integration named "wl-shell" found
qt.qpa.wayland: No shell integration named "ivi-shell" found
qt.qpa.wayland: Loading shell integration failed.
qt.qpa.wayland: Attempted to load the following shells ("xdg-shell", "xdg-shell-v6", "wl-shell", "ivi-shell")
```

These are the missing binaries, if you install PyQt5 in a venv in `$(VENVDIR)`, include:

```
--add-binary $(VENVDIR)/lib/python3.8/site-packages/PyQt5/Qt/plugins/wayland-shell-integration/*:PyQt5/Qt/plugins/wayland-shell-integration
--add-binary $(VENVDIR)/lib/python3.8/site-packages/PyQt5/Qt/plugins/wayland-graphics-integration-client/*:PyQt5/Qt/plugins/wayland-graphics-integration-client
--add-binary $(VENVDIR)/lib/python3.8/site-packages/PyQt5/Qt/plugins/wayland-decoration-client/*:PyQt5/Qt/plugins/wayland-decoration-client 
```

This adds about 1MB of shared objects, it's worth to include.

I guess this can be fixed by changing the hook code, to include these new plugins. Maybe here:

https://github.com/pyinstaller/pyinstaller/blob/9cca9cb613f3824ac3035ed99a366a66e1dfb633/PyInstaller/utils/hooks/qt.py#L379

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.7```
* Version of Python: `3.8.12`
* Platform: Arch Linux
* How you installed Python: Arch Linux repositories

**Comment by rickykresslein** [comment]
Setting QT_QPA_PLATFORM=xcb also makes the application slightly blurry on KDE/Wayland. I would love to see a fix for this bug so apps run properly on Wayland.

**Comment by simaoafonso-pwt** [comment]
@rokm Thanks for this, I rebuilt the app with the latest `develop` branch without the hacks above and can confirm this is fixed.
