### ISSUE TITLE
Pyinstaller not recognizing external libraries

### ISSUE THREAD

**Issue by smikkel997** [pyinstaller/pyinstaller#6488]
When i turn a python file into an executable with pyinstaller, everything goes smoothly. But when I open the executable, I get this error: ModuleNotFoundError: No module named 'ccxt'. I removed this module temporarily from my script and when i compiled and opened the new executable, it gave the same error but with the next library. This leads me to believe that pyinstaller simply doesn't support Local application/library specific imports. Does anyone have a solution to this problem

**Comment by rokm** [comment]
Where is the `ccxt` module/package installed?

**Comment by rokm** [comment]
And how are you importing it? Directly in your program, i.e., with `import ccxt`?

**Comment by rokm** [comment]
Although on the other hand, if top-level import (i.e., a package) is directly imported in program and not found in the frozen version, and if the same goes for other imports, then you probably have pyinstaller installed in a different python (virtual) environment than the rest of your libraries...

**Comment by smikkel997** [comment]
i fixed it not seeing the ccxt import by locating where the missing modules were installed and adding it to the command with -p. However, now that the executable imports the modules correctly, it won't open my configuration json file. Found [a post](https://stackoverflow.com/questions/9553262/pyinstaller-ioerror-errno-2-no-such-file-or-directory) about this but the executable still doesn't recognize it. I want the file to be outside the bundle but I can't find any solution for this.

**Comment by bwoodsend** [comment]
You're mixing up environments. Test your code actually runs in the terminal:
```
python your-code.py
```
If that works, invoke pyinstaller using:
```
python -m PyInstaller your-code.py
```
If you get a ModuleNotFoundError for PyInstaller then run:
```
python -m pip install pyinstaller
```
Then rerun pyinstaller.
