### ISSUE TITLE
Qt6 missing Multimedia hooks

### ISSUE THREAD

**Issue by Numerlor** [pyinstaller/pyinstaller#6489]
## Description of the issue
Qt reintroduced the Multimedia module in Qt 6.2, pyinstaller is currently missing a hook to support this.
At least for PySide6, including `QtMultimedia` and `QtMultimediaWidgets` as qt6 dependencies in the hook works

**Comment by FHU-yezi** [comment]
Yes, to use pyinstaller, I switched to PyQt5.
