### ISSUE TITLE
Import hook for passlib (password hashing library)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#649]
**Original date**: 2012/12/20
**Original reporter**: *psychosaxophone AND gmail DOT  COOM *

I'm using passlib for password authentication. However, pyinstaller doesn't include passlib when compiling, possibly because of multiple warnings. If, however, I copy the entire passlib directory from C:\python27\Lib\site-packages, the compiled program runs fine.

I know the FAQ says to try solving the warnings, but I really have no idea how to do so. I've included the warn*.txt file generated by pyinstaller.

PyInstaller is not bundling the passlib handlers: `passlib.handlers.*`

**Comment by htgoebel** [comment]
This feature-request if five years old now. Nobody worked on ti, so I'm closing it.

**Comment by liquidaty** [comment]
Just spent 3 hrs trying to get passlib to work with pyinstaller. hidden-imports, adding random import + other statements to script, and many variations thereof. nothing worked. finally, I just manually copied the entire passlib directory to the target build directory
