### ISSUE TITLE
Website temporarily offline

### ISSUE THREAD

**Issue by linuxdan** [pyinstaller/pyinstaller#6490]
Browsers say they cannot find the site
Archive.org has snapshots, but nothing in 2022

**Comment by bwoodsend** [comment]
We're merging https://pyinstaller.org with https://pyinstaller.readthedocs.io so yes, there's a brownout whilst we muck around with DNS and cloudfare.

**Comment by joshsleeper** [comment]
good luck with all that! maybe worth pinning this issue until you get it sorted out?

**Comment by szabgab** [comment]
I just wanted to report that http://www.pyinstaller.org/ is not available, but I see it was already reported a month ago. Should the `README.md` be updated to link to https://pyinstaller.readthedocs.io/  maybe?

**Comment by bwoodsend** [comment]
Yeah, I meant to do that a while ago.

**Comment by Legorooj** [comment]
Should be online in a day or two hopefully. Just sorting out domain ownership quickly.

**Comment by Legorooj** [comment]
That took a little longer than expected but the docs are now down whilst the DNS updates. Everything should be working in a few hours, with https://pyinstaller.org as the main url. The old readthedocs links will redirect there.

**Comment by mmaridev** [comment]
Still not getting any resolution from cloudflare:

```
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 1232
;; QUESTION SECTION:
;pyinstaller.org.		IN	A

;; AUTHORITY SECTION:
pyinstaller.org.	3601	IN	SOA	dns1.registrar-servers.com. hostmaster.registrar-servers.com. 1649687149 43200 3600 604800 3601

;; Query time: 51 msec
;; SERVER: 1.1.1.1#53(1.1.1.1)
;; WHEN: lun apr 11 22:32:39 CEST 2022
;; MSG SIZE  rcvd: 117
```

**Comment by Legorooj** [comment]
@mmaridev as I said, it would be down for a few hours. It's all up and running now 🎉.
