### ISSUE TITLE
Pyinstaller not running main file

### ISSUE THREAD

**Issue by xp4xbox** [pyinstaller/pyinstaller#6497]
## Description of the issue

Pyinstaller won't run the main file of my program. On launch, pyinstaller immediately exits with no error. Here is the log right before cleanup

```
[13652] LOADER: Running client.py
[13652] LOADER: OK.
[13652] LOADER: Manually flushing stdout and stderr
[13652] LOADER: Cleaning up Python interpreter.
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.dev0```
* Version of Python: 3.10
* Platform: Windows
* How you installed Python: python.org/downloads

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.
  
here is the build log:
https://gist.github.com/xp4xbox/d49205458f8f6c7d5ab3f2359dba943c

**Comment by rokm** [comment]
So how do you know that your `client.py` script was not run?

**Comment by xp4xbox** [comment]
I added a print and input above the imports.

**Comment by rokm** [comment]
If you freeze a simple hello-world script with PyInstaller in the same environment, does that work?

**Comment by xp4xbox** [comment]
It does

**Comment by rokm** [comment]
So you'll have to figure out what's different with your actual script. Without an example to reproduce the issue here, you're on your own.

**Comment by xp4xbox** [comment]
You can try it yourself if that would help, I'm pretty lost. 

git clone `https://github.com/xp4xbox/Python-Backdoor/tree/refactor`
python -m pip install -r requirements.txt
python src/setup.py, click build

(windows only)

**Comment by rokm** [comment]
I guess the problem is that you have a package with the same name as your entry-point script - try adding a print to your `src\client\__init__.py` to see if it ends up being executed instead of `src\client.py`.

**Comment by xp4xbox** [comment]
That fixed it thanks.
