### ISSUE TITLE
no codec search functions registered

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#651]
**Original date**: 2013/01/01
**Original reporter**: *blacksheep DOT cx AND gmail DOT  COOM *

Hi,

Hope someone can help me with following issue.

"LookupError: no codec search functions registered: can't find encoding"

LinuxMint Version 13 (maya) (64-Bit)  + Python 2.7.3

Additional infos (Traceback, spec-file, build-log) attached as .txt

thanks
chris

**Comment by karikalansaitechnology** [comment]
LookupError: no codec search functions registered: can't find encoding
 how to resolve this error in ubuntu 14.04
