### ISSUE TITLE
Opportunistically translate icon images to platform format (ico, icns) at build time

### ISSUE THREAD

**Issue by Starbuck5** [pyinstaller/pyinstaller#6510]
**Is your feature request related to a problem? Please describe.**
When packaging applications on different operating systems, the icons need to provided in a different format. I always end up uploading my PNG images to some sketchy "PNG to ICO" and "PNG to ICNS" converter websites.

**Describe the solution you'd like**
I saw the other day that PIL fully supports both of these formats. So it would be relatively simple to make a program that translates images in many formats into the required ICO or ICNS. It would be very convenient if PyInstaller could use PIL to translate icons to the system formats when they're built. I figure PyInstaller wouldn't want to add PIL as a full dependency just for this small optional bit of functionality, so I propose that PyInstaller tries to import PIL and convert to the correct format if incorrect format images are passed to `--icon`. If PIL isn't installed, that's fine, it will just do what it does now.

**Describe alternatives you've considered**
Of course this is very much just a convenience. There are conversion web sites online to handle this, or I could use PIL to do it myself.

**Additional context**
I could work on this.
Maybe maintainers think this is more maintenance hassle than it's worth in convenience. But I thought it was a cool idea to put out there. 😄

**Comment by Legorooj** [comment]
I like this idea. If you could work on it that would be great.

**Comment by bwoodsend** [comment]
Ooh, I hate optional dependencies. It's one extra thing to forget to also install when you install PyInstaller. It creates two code paths to test but no sane way to cover them both in one test suite run. It's one more unknown when someone reports they're having issues. Hard no from me, but I imagine I'm outvoted on that.

**Comment by Starbuck5** [comment]
@bwoodsend Thank you for the feedback.

We could do PIL as a mandatory dependency on Mac and Windows. I figured that there would be more hesitation to do that though, which is why I proposed it optionally. But it would be cool to get this convenience to everyone, if another dependency isn't too big of an ask.

If I did a PR on this, I would make an effort to make the error messages and docs as clear as possible to mitigate any misunderstandings.

**Pass it unsupported format, PIL found:**
Log output “PIL translated icon file {given} to {format}”
**Pass it unsupported format, PIL not found:**
Error "unsupported image format. Use {format} or install PIL to attempt automatic format conversion"
**Pass it supported format:**
Same as now

**Comment by rokm** [comment]
PIL is already an optional dependency anyway, for converting/resizing the splash screen image when necessary (or returning the error if PIL is unavailable). So I see no problem if it is used in the same way for icon conversion.

**Comment by bwoodsend** [comment]
@Starbuck5 Just do it. I'll cover my eyes and swallow my squeamishness.

**Comment by bwoodsend** [comment]
@Starbuck5 Are you still wanting to do this? I've rather changed my mind about not wanting this after remembering what a pain PNG to icon/icns is myself so if you'd rather not do it then I will.

**Comment by Starbuck5** [comment]
@bwoodsend I've been very slow on this, but yes, I'd like to do it.

I lost steam after doing the Windows version and the Documentation.
Remaining to do is the Mac version and the tests.

This is what I've currently got: https://github.com/starbuck5/pyinstaller/tree/icon-translation

**Comment by bwoodsend** [comment]
Cool, no worries. What you've got so far looks good.
