### ISSUE TITLE
--splash splash_png.png doesn't get close even if the GUI is started.

### ISSUE THREAD

**Issue by GauriDhande** [pyinstaller/pyinstaller#6511]
I am trying to package my tkinter python program into exe. I am using --splash flag for spalsh screen. However, even after the exe unpacks and GUI starts running, the splash screen appears on the screen. It doesn't get closed.

The command I am running is:
pyinstaller --noconfirm --onefile --windowed --icon "C:/Users/report/logo.ico" --splash "C:/Users/report/splash_png.png" --no-embed-manifest --add-data "C:/Users/report/img.png;." --hidden-import "tkinter" --hidden-import "PIL" "C:/Users/report/executable_script.py"

Can anybody help me with solving this issue? Thanks in advance.

**Comment by AndCycle** [comment]
you need to close it manually
https://pyinstaller.readthedocs.io/en/stable/usage.html#the-pyi-splash-module

**Comment by GauriDhande** [comment]
In the above link, I can see that pyi_splash Module takes as update text to display on splash screen. I want to have input as a img file as my splash screen. 

https://pyinstaller.readthedocs.io/en/stable/usage.html#cmdoption-splash

Exactly like the above link. But somehow, it doesn't get closed.

**Comment by rokm** [comment]
Read the very last part of that sample from https://pyinstaller.readthedocs.io/en/stable/usage.html#the-pyi-splash-module again...
