### ISSUE TITLE
pkgutil.iter_modules with arbitrary path

### ISSUE THREAD

**Issue by gentlegiantJGC** [pyinstaller/pyinstaller#6528]
## Description of the issue
The iter_modules patch implemented in #5959 has a bug where the path must start with the _MEIPASS or it will throw an assertion error.

The normal iter_modules function can take any valid path. Your code first calls that:
https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py#L37

and later asserts it starts with _MEIPASS
https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py#L59

which means that a path outside of the executable will throw the assertion error.

I think when implementing it was overlooked that this function could be used to look at a path outside the executable path.

### Context information (for bug reports)

* PyInstaller Version 4.8
* All OS and python versions

I will have a look into creating a pull request to fix this issue.
I think the solution is to change the assertion to an if statement to only run the code below that if it starts with _MEIPASS and thus could be bundled in the executable.

**Comment by rokm** [comment]
> I think the solution is to change the assertion to an if statement to only run the code below that if it starts with _MEIPASS and thus could be bundled in the executable.

I agree. Changing the assertion into if-statement that returns immediately if path does not start with _MEIPASS sounds like a proper fix.

**Comment by gentlegiantJGC** [comment]
A few more things I would like to fix with the implementation:
If an empty list is given it will assume the root whereas the vanilla implementation will return an empty list
Was there a reason why only the first path is considered?
