### ISSUE TITLE
Instructions for building the bootloader on Windows don't work

### ISSUE THREAD

**Issue by bmustill-rose** [pyinstaller/pyinstaller#6534]
Hi,

The [instructions for building the bootloader](https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html) no longer seem to work for me under Windows 10 X64 or 7 X64 (no other operating systems tested).

Specifically, the documentation for Windows suggests to install Chocolatey and then run
```
choco install -y python vcbuildtools
```
Unfortunately this no longer seems to work. I've done quite a bit of delving into this and from what I can tell the short version of what's going on is that Microsoft appear to no longer be hosting one of the files that this installer depends on - duplicating the steps in the Chocolatey script manually also fails.
I was able to resolve this by running
```
choco install python visualstudio2017-workload-vctools -y
```
This works in as much as I can build a bootloader that functions but I'm not experienced enough with Pyinstaller to be sure if this is the right way of solving the problem or not. I hope it helps someone never the less.

**Comment by bwoodsend** [comment]
@rokm How do you normally install MSVC into your Windows VMs? Using choco or the more conventional installers? Whichever it is, that approach should probably be the one in our docs - I don't think any of the rest of us perform that kind of setup on more than a single setup and forget basis.

**Comment by rokm** [comment]
I personally use the official MS installers.

But the Vagrant builder (which I used for 4.8 bootloaders) is using choco:
https://github.com/pyinstaller/pyinstaller/blob/d617d54cc86de629fd35a705f26876ebe79b4804/bootloader/Vagrantfile#L414

So we should probably update docs to use:
`choco install -y python3 visualstudio2019-workload-vctools`

**Comment by bwoodsend** [comment]
` choco install -y python3 visualstudio2019-workload-vctools` it is then...

**Comment by bwoodsend** [comment]
Done. Thanks for pointing that out @bmustill-rose.
