### ISSUE TITLE
Executable opens repeatedly on MacOS - Issue Narrowed down to Multiprocessing

### ISSUE THREAD

**Issue by mrhamm** [pyinstaller/pyinstaller#6554]
## Description of the issue
I am creating a tkinter app in the form of an executable from a single python file.  The executable works just fine when using Windows 10 and Ubuntu 20.04  When using the file created on MacOs Big Sur, the executable seems to work, but it opens the app process repeatedly until I force kill all of its processes.  I have tested the python file without compiling with pyinstaller and it works fine.  

I think this is an issue with how pyinstaller is treating the multiprocessing module on MacOS.  This issue prevents me from utilizing multiprocessing, which is crucial to the function of my app.  I have included a minimal reproducible example of the problem as well as the specifications.  

### Context information (for bug reports)

* Output of `pyinstaller --version:   4.8
* Version of Python:  3.9.10
* Platform: MacOS Big Sur
* How you installed Python:  brew
* Did you also try this on another platform? Does it work there?
Works on Windows10 and Ubuntu 20.04

### A minimal example program which shows the error

----App.py----
```python
import tkinter as tk                
import time 
import multiprocessing as mp

#Base class that I use to redirect multiproccessing outputs and print them
#multiprocessing is needed

class ConsoleFrame(tk.Frame):

    def __init__(self, parent,controller):

        tk.Frame.__init__(self, parent)

        #I believe that the mp.Queue() causes the bug
        self.stdout = mp.Queue()
        self.stderr = mp.Queue()

class SampleApp(tk.Tk):

    def __init__(self, *args, **kwargs):

        print('Spawning new app')

        tk.Tk.__init__(self, *args, **kwargs)

        tk.Tk.geometry(self,"600x600") #for visual
        container = tk.Frame(self)   #for visual 
        #gives you some time before the next app starts, trust me you want this
        time.sleep(5) 
        #Starts the console frame
        self.frame = ConsoleFrame(parent=container, controller=self) 
 
 
if __name__ == "__main__":

    app = SampleApp()
    mp.freeze_support()
    app.mainloop()
```
I compiled the file with all of the following, all giving the same result:
pyinstaller -F -w App.py
pyinstaller -F App.py
pyinstaller App.py

The bug seems to be happening due to the mp.Queue() 
I need to use the multiprocessing queue - there is no other simple alternative for my project.  It looks like there is an issue similar to the windows issue that is usually solved with mp.freeze_support() .  You can see I call that here and it doesn't help (of course, there is no reason that it would help anyways, it only affects mp on windows.)

Any help would be greatly appreciated -- I'm sure that this would be a bug worth solving for the MacOS dev community.

**Comment by rokm** [comment]
You need to call `multiprocessing.freeze_support()` *before* you use any of `multiprocessing` functionality.

What happens in the above code is, you instantiate `SampleApp`, which instantiates `ConsoleFrame`, which in turn instantiates `multiprocessing.Queue`, and *then* you call `multiprocessing.freeze_support`. So when `multiprocessing.Queue`s are instantiated, they spawn the multiprocessing's resource tracker, and because frozen support is not properly set up, that leads to recursive program re-spawn.

So fix the order of calls:
```python
if __name__ == "__main__":
    mp.freeze_support()
    app = SampleApp()
    app.mainloop()
``` 
and things should work as expected.

**Comment by mrhamm** [comment]
> 
Thank you so much!!
Can confirm this works.  Though, the windowed option with the "-w" flag still has some issue.  When you click the App, it opens and closes immediately.  Removing that option, the UNIX executable *does* work now.

**Comment by rokm** [comment]
> When you click the App, it opens and closes immediately.

That's `onefile` (`-F`) build? These have two processes, and the parent process is put to background as soon as possible, but this usually manifests itself as app's icon appearing & disappearing (program is started and parent goes to background), and then appearing again (once data is extracted and child is launched). Try using onedir build instead.

If onedir build opens and closes immediately, i.e., the application crashes due to unhandled exception, then implement proper top-level exception handling and logging to see what the problem is.

**Comment by mrhamm** [comment]
> 
The unix executable works just fine for both builds.  
Using "pyinstaller -F -w App.py" to give the "windowless option" (so that the console doesn't open)  gives a bundled "App.app" clickable which closes as soon as it clicks.  It also produces the App UNIX executable, and that one doesn't have any issues.   If you use the App executable in the Contents/MacOS folder of the App.app bundle, that works fine as well

**Comment by rokm** [comment]
What about `pyinstaller -w App.py`?

**Comment by mrhamm** [comment]
> What about `pyinstaller -w App.py`?

Same result.  Clickable App closes immediately but the UNIX executable in the App folder works as expected.

**Comment by rokm** [comment]
Are we still talking about the sample code above, or your actual application? Because the app bundle generated from the sample code seems to work just fine here...

**Comment by mrhamm** [comment]
> Are we still talking about the sample code above, or your actual application? Because the app bundle generated from the sample code seems to work just fine here...

Hmm, yes you are right -- I was bundling the full App -- the sample here is working for me just fine, apologies.  

Any suggestions as to what to look for to debug this?

**Comment by rokm** [comment]
> Any suggestions as to what to look for to debug this?

Your full app is probably doing something that violates the constraints that macOS imposes on app bundles. Including, but not limited to, trying to write to bundle directory, using relative paths that make assumption about current working directory, relying on full shell environment being available (e.g., LANG environment variable).

The easiest way is to implement proper exception handling to catch the exception and display its traceback (either in a UI, or store it in some fixed location that you can write to).

**Comment by mrhamm** [comment]
> > Any suggestions as to what to look for to debug this?
> 
> Your full app is probably doing something that violates the constraints that macOS imposes on app bundles. Including, but not limited to, trying to write to bundle directory, using relative paths that make assumption about current working directory, relying on full shell environment being available (e.g., LANG environment variable).
> 

Thanks so much, appreciate your help resolving the initial issue - yes, I have definitely violated some of those things in the App structure, but now I know where to look  :) .   👍 Cheers
