### ISSUE TITLE
Too much temp folders

### ISSUE THREAD

**Issue by rejjin** [pyinstaller/pyinstaller#6560]
Hi guys!

I have Windows 10 official build and use Python 3.7 x32.

The application built using PyInstaller creates a temporary folder of 15.8mb each time it is launched. 
This is a problem because free space will be used up very quickly.
Can I fix it?

Inside folders:
![](https://i.imgur.com/cNZgwAS.jpg)

**Comment by bwoodsend** [comment]
Each temporary folder should be deleted when your application closes (provided that it exits cleanly. i.e. doesn't crash). Is that not happening?

**Comment by eric15342335** [comment]
Hmm, I built myself a console application . The temporary folder still remains after I " X " the window. The console application is as follows:
```python
while True:
    print(input())
```

**Comment by rokm** [comment]
> after I " X " the window

That's the opposite of application being properly closed/shut down, isn't it?
