### ISSUE TITLE
PyInstaller fails to install on xp

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#6568]
Hi so i want my application which i developed to work on xp and so when i try to install pyinstaller 3.2.1 on windows xp it just fails to install and shows that pip fails to download pywin32 for pyinstaller==3.2.1. Python version = python 3.4.4
Can someone help me in this issue.
Any help will be appreciated

**Comment by rokm** [comment]
That's unsupported version of PyInstaller, python, and OS, so you're pretty much on your own.

That said, PyPI doesn't seem to provide `pywin32` wheels for python 3.4; you should probably look at https://sourceforge.net/projects/pywin32/files/

**Comment by ghost** [comment]
thanks i can make my app supported on xp and vista :)
