### ISSUE TITLE
Unable to make an exe from program using libOsmGpsMap

### ISSUE THREAD

**Issue by programmin1** [pyinstaller/pyinstaller#6575]
## Description of the issue
pyinstaller seems to bundle all of the dependencies and dlls... except for libOSMGPSMAP.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.9```
* Version of Python: 3.9.10
* Platform: Windows 10, English, msys2
* How you installed Python: msys2 and using /mingw64/bin/python
* Did you also try this on another platform? Does it work there? N/A

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
N/A this is open source repo at the "windows" branch, at https://github.com/programmin1/Repeater-START/branches

### Stacktrace / full error message

```
> .\repeaterstart.exe
repeaterstart.py:58: PyGIWarning: OsmGpsMap was imported without specifying a version first. Use gi.require_version('OsmGpsMap', '1.0') before import to ensure that the right version gets loaded.
using library: <gi.repository.OsmGpsMap> (version 1.0)

** (repeaterstart.exe:9304): WARNING **: 01:53:02.120: Failed to load shared library 'libosmgpsmap-1.0-1.dll' referenced by the typelib: 'libosmgpsmap-1.0-1.dll': The specified module could not be found.
gi/types.py:217: Warning: cannot derive '__main__+DummyMapNoGpsPoint' from non-derivable parent type 'void'
Traceback (most recent call last):
  File "repeaterstart.py", line 63, in <module>
  File "gi/types.py", line 226, in __init__
  File "gi/types.py", line 205, in __init__
  File "gi/types.py", line 217, in _type_register
RuntimeError: could not create new GType: __main__+DummyMapNoGpsPoint (subclass of void)
[9304] Failed to execute script 'repeaterstart' due to unhandled exception!
PS C:\msys64\home\Luke\Repeater-START\dist - Copy\repeaterstart> ls ./libosm*
```

Even when I do copy libosmgpsmap-1.0-1.dll to the same running directory.
I don't know much Windows development so apologies if this is a user error.

**Comment by rokm** [comment]
> Even when I do copy libosmgpsmap-1.0-1.dll to the same running directory.

Surely that DLL has other dependencies that would also need to be copied in that case...

----

Either way, if you want this to be handled automatically, you will need to create hooks, similar to the existing ones for the GObjectIntrospection-bound libraries. In this case, you need both a pre-safe-import-module hook ([example](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Clutter.py)) and a standard hook ([example](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/hooks/hook-gi.repository.Clutter.py)).

So, create a new directory, called `extra-hooks` in your current working directory, and create the following two files:

<details><summary>extra-hooks/pre_safe_import_module/hook-gi.repository.OsmGpsMap.py</summary>
<p>

```python
# extra-hooks/pre_safe_import_module/hook-gi.repository.OsmGpsMap.py

def pre_safe_import_module(api):
    # PyGObject modules loaded through the gi repository are marked as MissingModules by modulegraph, so we convert them
    # to RuntimeModules in order for their hooks to be loaded and executed.
    api.add_runtime_module(api.module_name)
```

</details>

<details><summary>extra-hooks/hook-gi.repository.OsmGpsMap.py</summary>
<p>

```python
# extra-hooks/hook-gi.repository.OsmGpsMap.py

from PyInstaller.utils.hooks.gi import get_gi_typelibs
binaries, datas, hiddenimports = get_gi_typelibs('OsmGpsMap', '1.0')
```

</details>

Then add the path to extra hooks via the [--additional-hooks-dir switch](https://pyinstaller.readthedocs.io/en/stable/usage.html#cmdoption-additional-hooks-dir), e.g.,

```
pyinstaller --clean --additional-hooks-dir extra-hooks/ [...]
```

**Comment by programmin1** [comment]
Thank you thank you, this loads, but has an issue with not grabbing any new tiles... Probably a question for libOsmGps team though?

```
(repeaterstart.exe:10496): libsoup-CRITICAL **: 23:25:41.363: soup_session_real_requeue_message: assertion 'item != NULL' failed

(repeaterstart.exe:10496): OsmGpsMap-WARNING **: 23:25:41.363: Error downloading tile: 6 - TLS/SSL support not available; install glib-networking

(repeaterstart.exe:10496): libsoup-CRITICAL **: 23:25:41.378: soup_session_real_requeue_message: assertion 'item != NULL' failed

(repeaterstart.exe:10496): OsmGpsMap-WARNING **: 23:25:41.394: Error downloading tile: 6 - TLS/SSL support not available; install glib-networking

(repeaterstart.exe:10496): libsoup-CRITICAL **: 23:25:41.409: soup_session_real_requeue_message: assertion 'item != NULL' failed

(repeaterstart.exe:10496): OsmGpsMap-WARNING **: 23:25:41.425: Error downloading tile: 6 - TLS/SSL support not available; install glib-networking

(repeaterstart.exe:10496): libsoup-CRITICAL **: 23:25:41.425: soup_session_real_requeue_message: assertion 'item != NULL' failed
```

**Comment by rokm** [comment]
Looks like you need to ensure that `glib-networking` libs are collected as well...

**Comment by programmin1** [comment]
This should be doing so, I  also try it with

```
from gi.repository import Gio
from gi.repository import GLib
```

in script, same result.

The one other issue with a user importing glib-networking shows it is an old issue and doesn't seem to have resolution other than a very old branch - https://github.com/pyinstaller/pyinstaller/issues/1709
also said options like --include-vorbis seem to have been removed too.

**Comment by rokm** [comment]
If `glib-networking` is loaded dynamically, then PyInstaller has no way of discovering the dependency and collecting it automatically... 

Can you provide a minimum working example using libOsmGps?

**Comment by rokm** [comment]
Hmm, this is going to be ugly... Because the only thing `glib-networking` provides are modules for `Gio` that are located in `/msys64/mingw64/lib/gio/modules`. So they are dynamically loaded and have absolutely no ties to python packages or extensions.

I think I managed to get tile downloads working in your program by modifying the spec:
```
block_cipher = None

binaries = [
    ('C:/msys64/mingw64/lib/gio/modules/libgiognomeproxy.dll', 'lib/gio/modules'),
    ('C:/msys64/mingw64/lib/gio/modules/libgiolibproxy.dll', 'lib/gio/modules'),
    ('C:/msys64/mingw64/lib/gio/modules/libgiognutls.dll', 'lib/gio/modules'),
    ('C:/msys64/mingw64/lib/gio/modules/libgioopenssl.dll', 'lib/gio/modules'),
    # These should be picked up by dependency analysis of the above modules, but don't seem to be...
    ('C:/msys64/mingw64/bin/libgnutls-30.dll', '.'),
    ('C:/msys64/mingw64/bin/libintl-8.dll', '.'),
    ('C:/msys64/mingw64/bin/libproxy-1.dll', '.'),
]
hiddenimports = []
datas = [
     ('C:/msys64/mingw64/lib/gio/modules/giomodule.cache', 'lib/gio/modules'),
    # Collect data (for when code is fixed not to assume current working directory)
    ('src/locateme.svg', '.'),
    ('src/mapbox.svg', '.'),
    ('src/signaltower.svg', '.'),
    ('src/signaltowerdown.svg', '.'),
    ('src/SettingsDialog.glade', '.'),
]

a = Analysis(['src/repeaterstart.py'],
             pathex=[],
             binaries=binaries,
             datas=datas,
             hiddenimports=hiddenimports,
             hookspath=['./extra-hooks/'],
[...]
```

and setting the `GIO_EXTRA_MODULES` environment variable at the start of the program:
```
import os
if getattr(sys, 'frozen', False):
    os.environ['GIO_EXTRA_MODULES'] = os.path.join(sys._MEIPASS, 'lib', 'gio', 'modules')
```


----

That said, there's several other issues:

* you do not collect images nor the .glade file, and the code generally seems to make assumptions current working directory is the application's top-level directory (i.e., using relative paths). That's generally untrue in frozen applications.

* the use of `urllib.request.urlretrieve` in `BackgroundDownload` thread is (at least on my system) throwing errors about missing certificate. Fixed by:
```python
if getattr(sys, 'frozen', False):
    import ssl
    if ssl.get_default_verify_paths().cafile is None and 
        os.environ['SSL_CERT_FILE'] = os.path.join(sys._MEIPASS, 'certifi', 'cacert.pem')
```
at the program start. This used to be done by a runtime hook for certifi, but we removed that (https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/332, https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/335) and you need to do it yourself if you want to use certifi's cacert as your default certificate for `ssl`). Seems you already had a similar cacert loading in your unfrozen codepath, though.

* an `import encodings.idna` seems to be required at the program start, otherwise you get missing module errors when trying to use networking functions in a thread

**Comment by programmin1** [comment]
It works well and I finished the build, thank you!
