### ISSUE TITLE
Well AV causing issue in latest build but working fine on v4.8 (with bootload recompiled)

### ISSUE THREAD

**Issue by RaSan147** [pyinstaller/pyinstaller#6578]
yep read it all up. I know i gotta submit it to the AV portals.
but just to tell you, the same hello world code with v4.8 didn't flag as virus but the latest dev version (also 4.9) is causing trouble with AV.

can you guys check if any of your changes are causing this 🤔
close it if you want. thanks for your time.

**Comment by bwoodsend** [comment]
The bootloaders in 4.8 and 4.9 are the same files
