### ISSUE TITLE
macOS bootstraper leaves a zombie process

### ISSUE THREAD

**Issue by vachooho** [pyinstaller/pyinstaller#6582]
> ps -ax | grep Threat
16865 ??         0:01.58 .../ThreatHunting
16874 ??         0:00.00 (ThreatHunting)
16890 ttys001    0:00.00 grep Threat

on version 4.9 
any chance this can be fixed soon?

**Comment by vachooho** [comment]
This is on windowed macOS app but the same issue happens with any build: onedir or onefile

**Comment by rokm** [comment]
>  any chance this can be fixed soon?

Not unless you can provide a reproducer.

**Comment by vachooho** [comment]
from multiprocessing import Pool

-process arguments - throw exception on invalid arguments or quit
pool = Pool()
input("waiting for input:")

- compile with pyinstaller 
- goes into the infinite loop of fork() ing the process
- if you have some code before creating Pool() that throws an exception and quits - then you get a zombie process

for example if arguments are unexpected (launched by multiprocessing with the arguments below) 
-B -S ... ... -c "from multiprocessing.resource_tracker import main;main(8)"

Seeing that there is a code for handling this in pyi_rth_multiprocessing.py I think you might want to know it.

**Comment by rokm** [comment]
You need to call [`multiprocessing.freeze_support`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) before using anything from `multiprocessing`. Otherwise, you'll end up with infinite respawn loop in the frozen application.

**Comment by vachooho** [comment]
thanks!
