### ISSUE TITLE
Let the bootloader send a SIGINT to the python process for cleanup functions etc

### ISSUE THREAD

**Issue by reapercreap** [pyinstaller/pyinstaller#6591]
It would be very nice, if the console will check for the CTRL_CLOSE_EVENT to send a SIGINT to the python process, so you can listen for that in your python code for executing a cleanup function because every time you hit the x button of the console window the MEIxxxx directory remains.

I found these two functions [SetConsoleCtrlHandler](https://docs.microsoft.com/en-us/windows/console/setconsolectrlhandler), [GenerateConsoleCtrlEvent](https://docs.microsoft.com/en-us/windows/console/generateconsolectrlevent) but I don't know in such large projects where I need to add it.

Tell me if it is possible and if not, I would like to learn maybe why it doesn't work.

Thank you and stay healthy.

**Comment by rokm** [comment]
Hmm... it looks like we could indeed install a custom handler in the onefile parent process' codepath via `SetConsoleCtrlHandler` to intercept console close event (or any of other shutdown-related events, really), send a SIGINT signal to the child process, and delay returning from the handler until the cleanup is complete (via a semaphore or similar synchronization primitive between the parent processes' main thread and the handler, which is executed in its own thread).

The problem I see is that the [timeout for `CTRL_CLOSE_EVENT` handler is 5 seconds](https://docs.microsoft.com/en-us/windows/console/handlerroutine#timeouts). So depending on the application size and the filesystem performance, the application may or may not finish cleaning up after itself before it is forcefully terminated. 

Might still be worth a shot, though.

**Comment by reapercreap** [comment]
Hey, cool that you are interested in but where do I have to look for it if it is implemented? I find git very complicated - you are allowed to laught about it :D - so? ^:D

edit: will this feature request get linked to it or whats going on then?

**Comment by rokm** [comment]
> edit: will this feature request get linked to it or whats going on then?

If this gets implemented, this feature request will be referenced by the pull request, and will be closed once the PR is merged.
