### ISSUE TITLE
Options related to spec generation are silently ignored if an existing .spec file is given

### ISSUE THREAD

**Issue by SnoopJ** [pyinstaller/pyinstaller#6600]
## Description of the issue

When invoking PyInstaller, if a `.spec` file is passed, arguments like `--add-binary` are discarded silently, leaving no indication to the user that these arguments **have no effect**. More specifically, `--add-binary` is not consumed by [`building.build_main.main()`](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/building/build_main.py#L802-L827) (invoked [here](https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/__main__.py#L118-L122)).

I discovered this behavior while working on build automation for an application that has some custom logic in the `.spec` file, but which will also want to add somewhat-arbitrary data to the `binaries` for the build. I ended up generating the final `.spec` from a template that fills in the binaries, but I would have been saved a bit of _"what the heck?!"_ time if PyInstaller issued a warning or error for me that what I was trying to do was nonsense.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: 4.9
* Platform: Ubuntu 20.04.3
* How you installed Python: pyenv
* Did you also try this on another platform? Does it work there? Yes. No.

### A minimal example program which shows the error

```
$ echo "print('hello world')" > repro.py
$ touch data1.txt data2.txt
$ python3 -m PyInstaller --add-binary=data1.txt:data repro.py
...
$ tree dist/
dist/                                                                             
└── repro                                                                         
    ├── base_library.zip                                                          
    ├── data                             
    │   └── data1.txt
    ├── libbz2.so.1.0
...
$ # data1 is part of the generated spec file, naively try to add data2
$ python3 -m PyInstaller --add-binary=data2.txt:data repro.spec
... (no warning or error about ignored argument) ...
$ tree dist/                                                                      
dist/                                                                             
└── repro           
    ├── base_library.zip    
    ├── data                             
    │   └── data1.txt
    ├── libbz2.so.1.0
```

**Comment by SnoopJ** [comment]
Here's an example patch that introduces the user-facing warning I found myself wishing I'd seen while debugging my build script. I don't know if this attempted usage actually constitutes an error, and this fault applies to other arguments (e.g. `--add-datas`), but it seems like a simple enough change that could maybe be generalized:

```diff
diff --git a/PyInstaller/__main__.py b/PyInstaller/__main__.py
index 6157308..8422eea 100644
--- a/PyInstaller/__main__.py
+++ b/PyInstaller/__main__.py
@@ -117,6 +117,8 @@ def run(pyi_args=None, pyi_config=None):
 
         # Skip creating .spec when .spec file is supplied.
         if args.filenames[0].endswith('.spec'):
+            if args.binaries:
+                logger.warning("Cannot add binaries to existing .spec (%s)", args.binaries)
             spec_file = args.filenames[0]
         else:
             spec_file = run_makespec(**vars(args))
```

With this diff applied, the output of PyInstaller looks like:

```
$ python3 -m PyInstaller --add-binary=data2.txt:data repro.spec
236 INFO: PyInstaller: 5.0.dev0+g9db19c9.mod
237 INFO: Python: 3.8.10
252 INFO: Platform: Linux-5.4.0-90-generic-x86_64-with-glibc2.29
252 WARNING: Cannot add binaries to existing .spec ([('data2.txt', 'data')])
...
```

**Comment by bwoodsend** [comment]
Yeah it's not great. #6460 would have sorted it but I doubt we'll ever go through with that one. If we are going to start slapping checks in, I'd rather that they were errors - the signal to noise ratio of PyInstaller's warnings is already so low that I'm amazed when people even look at them.

**Comment by SnoopJ** [comment]
In writing #6660 I think maybe I got a little carried away with solving a problem a bit larger than this issue. If need be, I can prune it back to some additional functions/state on the `parser` to satisfy this issue.
