### ISSUE TITLE
win7 run-time error

### ISSUE THREAD

**Issue by MuggleDreamJoinGitHub** [pyinstaller/pyinstaller#6601]
development environment:
win10 x64
pycharm 2020.3.3
python38 x86
pyinstaller 4.9

testing environment:
win7 x64
win7 x86

------------------------------------------------
Code:
------
import time
if __name__ == '__main__':
    print('hello')
    time.sleep(10)

-------------------------------------------------
D:\DevelopCode\Python\test32_01>pyinstaller -F main.py
123 INFO: PyInstaller: 4.9
123 INFO: Python: 3.8.8
124 INFO: Platform: Windows-10-10.0.17763-SP0
124 INFO: wrote D:\DevelopCode\Python\test32_01\main.spec
129 INFO: UPX is not available.
130 INFO: Extending PYTHONPATH with paths
['D:\\DevelopCode\\Python\\test32_01']
345 INFO: checking Analysis
349 INFO: Building because D:\DevelopCode\Python\test32_01\main.py changed
349 INFO: Initializing module dependency graph...
353 INFO: Caching module graph hooks...
367 INFO: Analyzing base_library.zip ...
2569 INFO: Processing pre-find module path hook distutils from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInsta
ller\\hooks\\pre_find_module_path\\hook-distutils.py'.
2570 INFO: distutils: retargeting to non-venv dir 'd:\\developtools\\develop ide\\python\\python38-32\\lib'
5074 INFO: Caching module dependency graph...
5272 INFO: running Analysis Analysis-00.toc
5278 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by d:\developtools\develop ide\python\python38-32\python3-32.exe
5530 INFO: Analyzing D:\DevelopCode\Python\test32_01\main.py
5532 INFO: Processing module hooks...
5533 INFO: Loading module hook 'hook-difflib.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hoo
ks'...
5534 INFO: Loading module hook 'hook-distutils.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\h
ooks'...
5535 INFO: Loading module hook 'hook-distutils.util.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstall
er\\hooks'...
5537 INFO: Loading module hook 'hook-encodings.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\h
ooks'...
5620 INFO: Loading module hook 'hook-heapq.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks
'...
5621 INFO: Loading module hook 'hook-lib2to3.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hoo
ks'...
5671 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyI
nstaller\\hooks'...
5673 INFO: Loading module hook 'hook-pickle.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hook
s'...
5674 INFO: Loading module hook 'hook-sysconfig.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\h
ooks'...
5675 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\P
yInstaller\\hooks'...
5676 INFO: Loading module hook 'hook-xml.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks'.
..
5719 INFO: Loading module hook 'hook-_tkinter.py' from 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\ho
oks'...
5900 INFO: checking Tree
5989 INFO: checking Tree
6085 INFO: checking Tree
6105 INFO: Looking for ctypes DLLs
6120 INFO: Analyzing run-time hooks ...
6122 INFO: Including run-time hook 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rt
h_subprocess.py'
6125 INFO: Including run-time hook 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rt
h_pkgutil.py'
6128 INFO: Including run-time hook 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rt
h_multiprocessing.py'
6132 INFO: Including run-time hook 'd:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rt
h_inspect.py'
6138 INFO: Looking for dynamic libraries
6320 INFO: Looking for eggs
6321 INFO: Using Python library d:\developtools\develop ide\python\python38-32\python38.dll
6321 INFO: Found binding redirects:
[]
6324 INFO: Warnings written to D:\DevelopCode\Python\test32_01\build\main\warn-main.txt
6377 INFO: Graph cross-reference written to D:\DevelopCode\Python\test32_01\build\main\xref-main.html
6389 INFO: checking PYZ
6392 INFO: Building because toc changed
6392 INFO: Building PYZ (ZlibArchive) D:\DevelopCode\Python\test32_01\build\main\PYZ-00.pyz
6928 INFO: Building PYZ (ZlibArchive) D:\DevelopCode\Python\test32_01\build\main\PYZ-00.pyz completed successfully.
6940 INFO: checking PKG
6941 INFO: Building because toc changed
6942 INFO: Building PKG (CArchive) main.pkg
8503 INFO: Building PKG (CArchive) main.pkg completed successfully.
8506 INFO: Bootloader d:\developtools\develop ide\python\python38-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit\run.exe
8506 INFO: checking EXE
8510 INFO: Building because toc changed
8510 INFO: Building EXE from EXE-00.toc
8514 INFO: Copying bootloader EXE to D:\DevelopCode\Python\test32_01\dist\main.exe
8519 INFO: Copying icon to EXE
8519 INFO: Copying icons from ['d:\\developtools\\develop ide\\python\\python38-32\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-c
onsole.ico']
8521 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
8521 INFO: Writing RT_ICON 1 resource with 3752 bytes
8522 INFO: Writing RT_ICON 2 resource with 2216 bytes
8522 INFO: Writing RT_ICON 3 resource with 1384 bytes
8522 INFO: Writing RT_ICON 4 resource with 37019 bytes
8523 INFO: Writing RT_ICON 5 resource with 9640 bytes
8523 INFO: Writing RT_ICON 6 resource with 4264 bytes
8523 INFO: Writing RT_ICON 7 resource with 1128 bytes
8527 INFO: Copying 0 resources to EXE
8527 INFO: Emedding manifest in EXE
8528 INFO: Updating manifest in D:\DevelopCode\Python\test32_01\dist\main.exe
8528 INFO: Updating resource type 24 name 1 language 0
8531 INFO: Appending PKG archive to EXE
10840 INFO: Building EXE from EXE-00.toc completed successfully.

---------------------------------------------------------
Error INFO:
------------
C:\Users\admin\Desktop>main.exe
Traceback (most recent call last):
  File "D:\DevelopTools\Develop IDE\Python\Python38-32\Lib\site-packages\PyInsta
ller\hooks\rthooks\pyi_rth_multiprocessing.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\__init__.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\context.py", line 6, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "multiprocessing\reduction.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "socket.py", line 49, in <module>
ImportError: DLL load failed while importing _socket: parameter error。
[2388] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled excep
tion!

**Comment by bwoodsend** [comment]
Does the Windows 7 machine have the service pack 2 installed? Realistically, if you're going to build for Windows 7 then you should build on Windows 7.
