### ISSUE TITLE
update installation dependency documentation to 'pywin32-ctypes' instead of pypiwin32 and pywin32

### ISSUE THREAD

**Issue by Sorontik** [pyinstaller/pyinstaller#6606]
I just started looking into PyInstaller and immediately stumbled upon some (for me) very confusing things in the documentation, regarding the PyWin32/pypiwin32 package dependency.
This issue is completely based on the Documentations, i did not look into any code.

### The Problem:
- PyInstaller needs either `PyWin32` or `pypiwin32` package and will automatically install `pypiwin32` if none of them is already installed.
However, `pypiwin32` seems outdated and no longer supported. Recent releases seem to only happen at `PyWin32`.
- Also all the links in the Documentation (specifically, the two pages linked in my explanation) regarding the `PyWin32` or `pypiwin32` dependency seem to be outdated and missleading. (And sometimes point to specific versions instead of the generic "most recent" one)

It looks like both PyPi Entries go back to the same sources, only at different points in time.

### Suggested Solution:
- Make pyinstaller prefer `PyWin32` over `pypiwin32` and automatically install `PyWin32` if none of them is already installed.

- Change the Documentation to point users to the [`PyWin32`](https://pypi.org/project/pywin32/) PyPi page and the corresponding [GitHub Repo](https://github.com/mhammond/pywin32).
Additionally mention, that the PyWin32 project intermittently was available via [`pypiwin32`](https://pypi.org/project/pypiwin32/), which seems to be outdated and no longer supported by their developers right now. (Maybe mention it can still be used by pyinstaller, if applicable)
- minor: make sure to not reference specific versions (in links, the documentation or dependencies) unless that is your intention, in which case the documentation should explicitly point out that * this specific version * is required/meant

Since both packages are already supported and seem to originate from the same sources, i don't think there would be any problems/bugs arising from these changes.
(At worst, existing compatibility issues between `pyinstaller` and the latest `PyWin32` version would be revealed and affect a wider audience)

To confirm or deny my conclusions below, you might want to contact [Mark Hammond](https://github.com/mhammond), who is the owner of both the github and sourceforge repo and should be able to explain the true story.

### Explanation/Research:
**What does the pyinstaller documentation say:**
Both documentation pages [Requirements](https://pyinstaller.readthedocs.io/en/stable/requirements.html) and [How to Install PyInstaller](https://pyinstaller.readthedocs.io/en/stable/installation.html)
say, that either the `PyWin32` or the `pypiwin32` package has to be installed and that `pypiwin32` will be automatically installed, if none of them is already installed.
The How-To also calls `pypiwin32` the "more recent" of the two 

**What does the pyinstaller documentation hyperlink to:**
For `PyWin32`, both Documentation pages link to the [PyWin32 sourceforge page](https://sourceforge.net/projects/pywin32/files/) which, in it's Readme, directly states that this is the OLD repo and that all up to date stuff happens on the [github repo](https://github.com/mhammond/pywin32/releases)

For `pypiwin32`, both Documentation pages link to the [pypi page](https://pypi.org/project/pypiwin32/219/) of the version 219, which is from 2014 and heavily outdated. However even the [most recent version](https://pypi.org/project/pypiwin32/) is from 2018 and does not contain any description, links or other information.
The OLD 219 version does have a Homepage link, which points to the same [pywin32 sourceforge repo](https://sourceforge.net/projects/pywin32/) as the documentation mentioned above.

**manually searching for pywin32 on pypi**
Manually searching for "pywin32" on pypi (since i found no link chain going there from the documentation) leads to the [`pywin32` page](https://pypi.org/project/pywin32/) which contains proper descriptions, links to the [github repo](https://github.com/mhammond/pywin32) and the latest pypi version corresponds to the latest github release (at time of writing: Release 303 on 20 Dec 2021)

**My Conclusions**
I'm in no way involved in either of `pywin32` or `pypiwin32` and have no idea of the connections between them, nor do i have any idea of how exactly pyinstaller is dependent on them, but this is how the linked pages look:
The [`PyWin32` pypi package history](https://pypi.org/project/pywin32/#history) lists one release in 2007, one in 2010 and then regular releases since early 2018.
The [`pypiwin32` pypi package history](https://pypi.org/project/pypiwin32/#history) lists only a total of three releases in 2014, 2017 and the last one early in 2018.

The PyWin32 project started on [sourceforge](https://sourceforge.net/projects/pywin32/) and migrated from sourceforge to [github](https://pypi.org/project/pywin32/) early in 2018 (specifically since build 221 as listed in the [changelog on github](https://mhammond.github.io/pywin32/html/CHANGES.txt).
Initially, it was only sporadically released to PyPi, first to `PyWin32` (in 2007 and 2010), then to `pypiwin32` (2014, 2017, 2018) and then back to `PyWin32`, which looks like it has been released to regularly since 2018.

**Comment by bwoodsend** [comment]
`pywin32-ctypes` is the one that actually gets used.

https://github.com/pyinstaller/pyinstaller/blob/93ad16d5c970f70f843a5eda8b177f681743005b/setup.cfg#L62

If there are any references to any other variants in the docs then they need to be deleted.

**Comment by Sorontik** [comment]
well, in that case...
`pywin32-ctypes` seems to be an independent re-implementation of pywin32, written in pure python, according to the github-repo readme

so a complete overhaul of these sections of the documentation might be needed.

**Comment by bwoodsend** [comment]
Turns out I had already addressed this in 0c118e94b4c8e6c5646b946cf600a7148de25014 but just hadn't backported it. I've done it now but it won't land on the stable version of the docs until the next release. [The docs built off the development branch](https://pyinstaller.readthedocs.io/en/latest/requirements.html) have the changes.
