### ISSUE TITLE
Executable not launching

### ISSUE THREAD

**Issue by SalvishGoomanee** [pyinstaller/pyinstaller#6611]
Hello,

I have the same issue at the moment. I of course executed the `.exe` by simply typing in `app.exe` but it is not working at all for me.

Double clicking on the app to open does not show anything.

Are there modifications to the `app.spec` file that needs to be appended?

System: Python = 3.9, PyInstaller = 4.7 

Thanks

**Comment by bwoodsend** [comment]
... and fill out the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md) so that we have at least some idea of what you're doing.
