### ISSUE TITLE
Pydicom

### ISSUE THREAD

**Issue by albamiguel** [pyinstaller/pyinstaller#6614]
Doing a project ,we have seen that with pyinstaller,the library pydicom is not supported, so It generates some difficulties  in medicine projects.
Thanks

**Comment by rokm** [comment]
Any specific problem? That is not addressed by a `--collect-submodules pydicom.encoders --collect-data pydicom` or an equivalent hook?

**Comment by albamiguel** [comment]
The problem is that when we create the .exe, the library of pydicom generates an error, so trying to open  the file which has just been  genetared is impossible

**Comment by rokm** [comment]
Can we see the error message, perhaps?

**Comment by albamiguel** [comment]
It does not show us  like an error message, the problem is that we are not able to open the .exe. However, we have seen that if we eliminated everything related to pydicom  in our notebook, the .exe of our program is generated perfectly, but we need to use pydicom. Because of that we think that the library of pydicom is not supported by pyinstaller.

**Comment by rokm** [comment]
What version of PyInstaller are you using? Are you using `noconsole`/`windowed` mode? And have you tried adding the above options (`--collect-submodules pydicom.encoders --collect-data pydicom`) to your PyInstaller command?

**Comment by albamiguel** [comment]
We are using pyinstaller version 4.8,pydicom versión 2.3.0.
After trying what you have said before, when we run the .exe, it closed instantly

**Comment by rokm** [comment]
How are you running the .exe? By double-clicking on it? If this is a console-enabled build, run it from command prompt (otherwise yes, it will "close instantly" and close the console as well). If it is windowed build, you should get at least an unhandled exception error dialog (unless something else went wrong...) - if not, then switch to console-enabled build, and run from the command prompt, so you can see the error in the console output.

**Comment by albamiguel** [comment]
The exception we got is Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception.

**Comment by bwoodsend** [comment]
We need the full error output. That line just says something went wrong.

**Comment by bwoodsend** [comment]
We need the full error output - not just one line.

**Comment by bwoodsend** [comment]
We need the full error output - not just one line.

**Comment by albamiguel** [comment]
![IMG_20220223_150156](https://user-images.githubusercontent.com/80346538/155414439-0e770a23-cdbf-4697-a694-21b65e6fd295.jpg)
)

**Comment by rokm** [comment]
Hmmm... this looks like a problem with collection of `pywin32` stuff, and is not directly related to  `pydicom`. Can you either try re-installing `pywin32`, or removing it altogether from your environment if you do not need it (as far as I can tell, it is not directly used by `pydicom`, but it ends up optionally imported via `pkg_resources`, which is used by `pydicom`).
