### ISSUE TITLE
Logging module pre-safe-import-module hook failed, needs fixing.

### ISSUE THREAD

**Issue by zbouslikhin** [pyinstaller/pyinstaller#6617]
## Description of the issue
I'm using struclog together with logging and everything works fine in dev.
When trying to bundle using pyinstaller, modue logging.config is not found

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.9```
* Version of Python: 3.9.2
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "C:\Users\b\AppData\Local\pypoetry\Cache\virtualenvs\vizprocessing-DqUd93ZO-py3.9\lib\site-packages\urllib3\__init__.py", line 7, in <module>
    import logging
  File "D:\py\vizprocessing\src\vizprocessing\logging\__init__.py", line 1, in <module>
    from vizprocessing.logging.multilogging import VizLogger
  File "D:\py\vizprocessing\src\vizprocessing\logging\__init__.py", line 1, in <module>
    from vizprocessing.logging.multilogging import VizLogger
  File "D:\py\vizprocessing\src\vizprocessing\logging\multilogging.py", line 3, in <module>
    from logging.config import dictConfig
ModuleNotFoundError: No module named 'logging.config'
pre-safe-import-module hook failed, needs fixing.
```

**Comment by bwoodsend** [comment]
Can you please provide a minimal reproducing example. One stacktrace doesn't tell us much.

**Comment by rokm** [comment]
This looks like your `logging` subpackage somehow ending up shadowing the standard `logging` package.

**Comment by zbouslikhin** [comment]
I figured it out. I had one subpackage that was named "logging" and that was causing conflict with the built-in Python's logging. Renaming the subpackage did the job.
