### ISSUE TITLE
Challenges w.r.t using multiprocessing within .spec

### ISSUE THREAD

**Issue by smasihemami** [pyinstaller/pyinstaller#6631]
Dear PyInstaller team,

I have a large number of .py files which needs to be converted to .pyd as a way of obfuscating the code to be run on windows. I get the list of these .py files from the output of Analysis class (Analysis.pure), and then try to call cythonize on all of them **in parallel**, in order to finish the cythonization faster. For doing this on 10 files, running sequentially takes around 16 seconds while running in parallel takes only 3 seconds (I've got 10 physical cores on my machine). So running in parallel is very much important in my case.

In order to be able to run cythonize in parallel, I had to introduce "if __ name __ =='**__ main __**':" to the beginning of spec file to be able to use multiprocessing pool map. Then I realized that "__ name __" is set to **builtins** on running PyInstaller. Then after changing __ main __  to **builtins** I can still not get multiprocessing to work. There comes failures similar to below:
_pickle.PicklingError: Can't pickle <function {some_function_name} at {some_memory_address}>: attribute lookup {some_function_name} on __ main __ failed

Would appreciate any of your advices on this matter.

**Comment by rokm** [comment]
The .spec file is executed via `exec` with custom namespace ([here](https://github.com/pyinstaller/pyinstaller/blob/d006b364cfabd1ac23f57c28b92d385331987edf/PyInstaller/building/build_main.py#L725)), and I suspect that interferes with `multiprocessing`.

If you create a basic `multiprocessing` example script and try to `exec` it from another script, it ends up with a similar error when the namespace dict is specified (and is similarly reduced/limited).

So what you're trying to do is apparently unsupported. (Or perhaps the namespace is missing something - but as motivation for this non-standard build process is entirely on your side, you'll have to figure it out yourself).

**Comment by rokm** [comment]
What *might* work is defining your processing function (the one called via map) within PyInstaller.building.build_main, and then mapping it into [spec_namespace](https://github.com/pyinstaller/pyinstaller/blob/d006b364cfabd1ac23f57c28b92d385331987edf/PyInstaller/building/build_main.py#L689) with which the spec file is executed...

**Comment by bwoodsend** [comment]
It's a requirement of `multiprocessing` that it can just `import` the script that your functions are defined in. You can see this simply by trying to run a basic `multiprocessing` example purely in the Python REPL. But the `exec()`-ing isn't the problem here because [we provide the spec's file path to `compile()`](https://github.com/pyinstaller/pyinstaller/blob/7933d7266042f9861306defd3335d69db31e66f6/PyInstaller/building/build_main.py#L722) so it's able to find the source code. It can't however `import` it because of the custom namespace normally provided to the spec file - you'd need to add `from PyInstaller.building.api import Analysis, EXE, ...`. Then you'd hit the problem that hidden global settings object `PyInstaller.config.CONF` (which I desperately want to get rid of) isn't configured to a functional default.

All in all though, I doubt it would do you much good even if it did work. Do you really want a setup where you have to watch all 10 of your files recompile whenever you modify one of them?

**Comment by smasihemami** [comment]
Well, I don't have much control over the current setup I have, meaning there are a number of python files that need to be cythonized before being packed by pyinstaller. This happens whenever some of these file change.

Is there a way (or what is the correct way) to tell pyinstaller to use cython instead of normal compilation to python bytecode? Don't know the command for latter, but for former one could just say 'cythonize -i some_file.py'

Right now, I have a spec file which I give to pyinstaller and it makes a distribution, which works fine and all the tests pass with its output, before cythonizing any python code. 

Then, in order to make a distribution from cythonized python codes, I duplicated that spec and removed the call to PYZ, EXE and COLLECT, and pickled the result of Analysis (analysis.pure), followed by subprocess.check_call to a python script which reads from pickled results of analysis.pure and runs cythonize command in parallel on some of the source files found by Analysis, and removes the corresponding .c and .py afterwards (just cythonizing my own code, but not those coming from site packages). At this step, all the test suites in my repo pass, meaning the cythoznied python code (.pyd) still works. Then I use the aforementioned spec again to make a distribution. The main python script in this spec (entry point for pyinstaller executable) is of course not cythonized. After doing so, the output of pyinstaller does not work as expected, and fails with some simple imports.

Would again appreciate any of your advices.

Btw. I went through documentation but could not find some relevant information on how to use cython together with pyinstaller, to make a distribution in which python source code cannot be easily reverse-engineered and understood (in other words, to hide the source code more thoroughly https://pyinstaller.readthedocs.io/en/stable/operating-mode.html?highlight=cython#hiding-the-source-code).

**Comment by rokm** [comment]
PyInstaller by itself has no support for integration with cython in the way that you are trying to achieve here (hence no documentation on how to use cython together with pyinstaller).

I think the only realistic way of using `cython` in your scenario is to pre-process the code you want protected, and then run PyInstaller on that. Which, from what I understand, you are already kind of doing (although I see no reason why you would need to pickle analysis.pure; why not just recursively list all the source files you want to compile?).

But the catch is that PyInstaller cannot analyze imports from the cythonized modules (which is kind of the point of cythonization in your case...), so you end up with missing imports for modules that are imported by those modules (and not imported in the entry-point script). You'll need to manually add those missing modules via `hiddenimports` (or perhaps you could re-use the results of the original Analysis).

**Comment by bwoodsend** [comment]
[pyminifier with --no-latin](http://liftoff.github.io/pyminifier/#special-sauce) would be my recommended way to hide source code (although I've never had to use it).

**Comment by smasihemami** [comment]
I have now at least a working solution with cython as a layer of protection, and pyinstaller can properly package cythonized files, and it works just as before. 
@rokm Thanks for your help, it helped a lot.
@bwoodsend looks great. will look into as an additional code protection layer.
