### ISSUE TITLE
Creating EXE with instapy-module not possible?

### ISSUE THREAD

**Issue by Rapid1898-code** [pyinstaller/pyinstaller#6637]
Hello - i would like to create an executeable for windows using pyinstaller with the instapy-module in it -

This is the code which runs fine in the terminal -

```
import os
from instapy import InstaPy
from importlib import reload
import sys
import xlwings as xw

# sys.getdefaultencoding()
# sys.stdin.reconfigure(encoding='utf-8')
# sys.stdout.reconfigure(encoding='utf-8')

if __name__ == '__main__':
  SAVE_INTERVAL = 5
  WAIT = 3
  FN = "param.xlsx"
  path = os.path.abspath(os.path.dirname(sys.argv[0]))  
  fn = path + "/" + FN
  wb = xw.Book (fn)
  ws = wb.sheets["param"]
  
  INSTA_USER = ws[f"B1"].value
  INSTA_PW = ws[f"B2"].value
  listTags = ws.range("D2:D100").value
  listTags = [x for x in listTags if x != None]
  listNotTags = ws.range("E2:E100").value
  listNotTags = [x for x in listNotTags if x != None]
  listComments = ws.range("F2:F100").value
  listComments = [x for x in listComments if x != None]

  session = InstaPy(username=INSTA_USER, 
                    password=INSTA_PW,
                    headless_browser= True)
  session.login()
  session.like_by_tags(listTags, amount=1)
  session.set_dont_like(listNotTags)
  session.set_do_comment(True, percentage=10)
  session.set_comments(listComments)
  session.end()
```

But when i compile the exe-file with 
`pyinstaller --onefile instaBot.py`
and start the exe-file 

I get this error:
```
Traceback (most recent call last):
  File "instaBot.py", line 2, in <module>
    from instapy import InstaPy
ModuleNotFoundError: No module named 'instapy'
[17704] Failed to execute script instaBot
```

How can i create an exe-file using pyinstaller with the instapy-module in it?

**Comment by rokm** [comment]
Is PyInstaller installed in the same python environment as `instapy` and the rest of the libraries you're using? Do you have multiple python environments and multiple PyInstaller installations, and the one launched when you run `pyinstaller` is not the one you expect it to be?

When a frozen application ends up missing a direct import from its entry-point script, 99% of times it is due to mixed up environments. (Plus, I tried freezing your example myself, and it works here - i.e., reaches the point where it tries to read the param.xlsx).

**Comment by Rapid1898-code** [comment]
Of course you are right of course...
I forgot to install pyinstaller in the virtual environment.
Thanks a lot!

**Comment by Rapid1898-code** [comment]
I seems i was happy to soon.
I installed pyinstaller in the virutal environment - and created the exe-file again in the virtual environment.

But again i get the same error.

Should i run the pyinstaller with the full path?
Or should i check something else?
But what path i have to take in that way - and where is the pyinstaller executeable stored?

**Comment by Rapid1898-code** [comment]
When i am in the activated virtual environment - and in this environment pyinstaller is installed and i run
`pyinstaller --onefile instaBot.py`
why is he not taking the pyinstller from the activated virtual environment?

Or do i have to use some parmater to force this use in any way?

**Comment by bwoodsend** [comment]
Verify your script works with whichever Python environment you have active using `python instaBot.py` then run PyInstaller from that same environment using `python -m PyInstaller --onefile instaBot.py`. That's the most muddle-proof method.

**Comment by Rapid1898-code** [comment]
What is the parameter -m for?

**Comment by bwoodsend** [comment]
It means execute a library. https://docs.python.org/3/using/cmdline.html#cmdoption-m

**Comment by Rapid1898-code** [comment]
Ok - i see.

When running the exe-file i get now rid of the initial error.

But now i get this error instead:

```
InstaPy Version: 0.6.16
 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "C:/Users/Polzi/InstaPy"
Traceback (most recent call last):
  File "instaBot.py", line 29, in <module>
    session = InstaPy(username=INSTA_USER,
  File "instapy\instapy.py", line 330, in __init__
  File "instapy\browser.py", line 131, in set_selenium_local_session
  File "instapy\browser.py", line 50, in create_firefox_extension
  File "zipfile.py", line 1727, in write
  File "zipfile.py", line 501, in from_file
FileNotFoundError: [WinError 3] Das System kann den angegebenen Pfad nicht finden: 'C:\\Users\\Polzi\\AppData\\Local\\Temp\\_MEI154362\\instapy\\firefox_extension\\manifest.json'
[10012] Failed to execute script 'instaBot' due to unhandled exception!
```

(when i run the python-file directly in the command line i didn´t get this error of course)

**Comment by rokm** [comment]
`--collect-data instapy`

**Comment by Rapid1898-code** [comment]
Thanks! I think with this command it finally worked:
`python -m PyInstaller --collect-data instapy --onefile instaBot.py`

What is this 
`--collect-data instapy`
doing?

**Comment by rokm** [comment]
It collects data files from the specified package. PyInstaller's module graph tracks only imported python modules and extensions, so the non-python resources, such as data files, are not collected (unless someone wrote a hook for the package). You might want to look at [this section of the docs](https://pyinstaller.readthedocs.io/en/stable/usage.html#what-to-bundle-where-to-search), as you might need to use options like `--collect-data`, `--collect-submodules`, etc.
