### ISSUE TITLE
idea: reduce bootloader file size

### ISSUE THREAD

**Issue by earonesty** [pyinstaller/pyinstaller#6638]
**Is your feature request related to a problem? Please describe.**
When I distribute 5 executables as a part of a single pyinstaller package, the bootloader exe size is pretty big (11MB on windows) per executable.

**Describe the solution you'd like**
Simple solution is to ship a much smaller EXE file, that simply loads the DLL (or .SO) containing all of the logic for the bootloader.

**Describe alternatives you've considered**
We can package all of our logic as one executable with lots of flags and options, but that starts to get ugly, and there are certain circumstances (such as a bug reporter), where we want the EXE to really be a different entry point.

**Comment by rokm** [comment]
The bootloader executable is 230 KB in size. What's contributing to your final executable size is the embedded PYZ archive that contains byte-compiled .pyc modules. Under the current design, PYZ archive cannot be shared among different executables, but you can disable its use by using `noarchive=True` option in the .spec file (passing it to `Analysis` instance(s)).
