### ISSUE TITLE
Mixed onefile and onedir packaging in Linux

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#664]
**Original date**: 2013/01/26
**Original reporter**: *mmysinger AND seachangepharma DOT  COOM *

We are trying to better comply with the LGPL by moving only those particular shared libraries out of a onefile type installation into the onedir location. However, the LD_LIBRARY_PATH setting in the Linux bootloader only references the tempdir location, so this fails to find the onedir shared libraries (which are located in homedir). Meanwhile, other paths like PYTHONPATH are set to look in both tempdir and homedir, so I think it makes sense that LD_LIBRARY_PATH also look first in tempdir and then in homedir. To change this, I used the attached patch and have also added a mailing list discussion.

**Comment by matysek** [comment]
We are not going to support this mode.
