### ISSUE TITLE
[Missing] Code of Conduct

### ISSUE THREAD

**Issue by FahimFBA** [pyinstaller/pyinstaller#6642]
**Is your feature request related to a problem? Please describe.**
No. It's an addition. The project is currently missing the Code of Conduct which defines standards for how to engage in a community.

**Describe the solution you'd like**
If you are interested in adding one, then I would submit a PR with that.

**Describe alternatives you've considered**
Not applicable for this issue.

**Additional context**
Not applicable for this issue.

**Comment by bwoodsend** [comment]
Hmm, do we need one? People are generally pretty civilised here.

**Comment by rokm** [comment]
> Hmm, do we need one? People are generally pretty civilised here.

I was going to ask the same thing.

**Comment by FahimFBA** [comment]
> Hmm, do we need one? People are generally pretty civilised here.

That's also true. Still, I thought about whether you want this project to have one or not. Please feel free to close the issue if you don't think the necessity of it.

**Comment by rokm** [comment]
Alright, I'm closing this for now, and we will revisit it if/when it becomes necessary.
