### ISSUE TITLE
Can't read exception message on windows console applications

### ISSUE THREAD

**Issue by santagada** [pyinstaller/pyinstaller#6646]
Because pyinstall doesn't do a wait for key press (like using pause in a bat file) windows close the console window before the message can be read. This happens when a console application is opened by double clicking it (so the console lifetime is govern by the process) or when its a uac_admin and its run from a non elevated console (so the same will happen, a new elevated console window opens and the data will be there).

Waiting for input after a traceback crash would fix it, but maybe that should be only done when the process owns the console or on a flag in the spec file for debugging purposes.

**Comment by rokm** [comment]
> Waiting for input after a traceback crash would fix it, but maybe that should be only done when the process owns the console or on a flag in the spec file for debugging purposes.

Not happening on my watch. I mean, if you want to see the exception message of the console application, simply run it from the command prompt instead of double-clicking on it. Or implement proper top-level exception handling in your application code and wait for input on exceptions, if you find this a good idea.

**Comment by santagada** [comment]
Again, on the command prompt it still doesn't work, as windows doesn't allow an elevated process to attach to a non elevated command prompt.

Of course I can implement it myself, but then all pyinstaller apps, need to have a wrapper script like this:

```
try:
  import actual_script
 except:
   print_traceback
   input('an exception has happened')
```

Which is quite inconvenient. If this input was part of the debug flag of the spec it would make development easier.

**Comment by bwoodsend** [comment]
Just run it from an elevated console then.
