### ISSUE TITLE
Pyinstaller leaks key when using with GitHub action secrets 

### ISSUE THREAD

**Issue by illusionyy** [pyinstaller/pyinstaller#6652]
When using with GitHub action secrets, pyinstaller prints the key parameter into the console, a solution to this would be an additional argument to suppress the using key output. In this case the test key is 
```
[=?)K]P=`D!B,T}
```
https://github.com/illusion0001/py-patcher/runs/5439402984?check_suite_focus=true#step:4:19

https://github.com/pyinstaller/pyinstaller/blob/c95dba86673cba819558a0c6218e934095d87ac9/PyInstaller/building/build_main.py#L289

To something like
```py
logger.info('--hide-key is used, key will be hidden.')
```
Perhaps it might be a good idea to not leave string reference to the key, and write just the variable?
https://github.com/pyinstaller/pyinstaller/blob/c95dba86673cba819558a0c6218e934095d87ac9/PyInstaller/building/build_main.py#L294

**Comment by bwoodsend** [comment]
In what scenario are your build logs public but your source code is private?

**Comment by rokm** [comment]
Well, to be fair, there's no real need to print the key in the debug message. (Or the message could be downgraded to debug instead of info, so it is not shown by default).

**Comment by illusionyy** [comment]
> In what scenario are your build logs public but your source code is private?

The source is here, https://github.com/illusion0001/py-patcher. tried testing keys and noticed it was being printed out

**Comment by bwoodsend** [comment]
> Well, to be fair, there's no real need to print the key in the debug message.

Yeah, I agree. I guess that what I really wanted to say is that, since the bytecode encryption feature is mostly smoke and mirrors (the encryption key has to be part of the executable where anyone who knows where to look can find it), if you're seriously concerned about that encryption key getting leaked then the PyInstaller's encryption feature is inadequate for your needs anyway.
