### ISSUE TITLE
pyinstaller *.exe:  the *.exe  is not consistent with the source *.py functionally

### ISSUE THREAD

**Issue by lin-name** [pyinstaller/pyinstaller#6656]
Hello!
Sorry to interrupt you!
but i  faced debug. here is the example.py
![捕获](https://user-images.githubusercontent.com/65641960/156981741-9b3970f1-8527-47e7-b2df-f4d2bbac6321.PNG)

And i can run the example.py well in python environments when i input:
$ python example.py -i c:\11 -t d:\22 -m T
and it get the right outputs.

but after i  get the example.exe via Pyinstaller, and the input is the same as before,

but it get the error:
![捕获2](https://user-images.githubusercontent.com/65641960/157017764-b867ea6e-1022-4639-9fa4-78c83c374144.PNG)
$ example.exe -i c:\11 -t d:\22 -m T
The argument -m T can run in .py, why it is could not recognized in the *.exe?
Why does it happen? and how  can i solve this error?

Looking forward for your reply.

**Comment by rokm** [comment]
The usage message does not match your `p.add_argument` calls (there's a `--feature_num` argument instead of `--scan_mode`). 

Are you using an old exe or freezing a different script? Try removing `build` and `dist` directories, and rebuild your program again.
