### ISSUE TITLE
pyinstaller error with tkinter 

### ISSUE THREAD

**Issue by omtoi101** [pyinstaller/pyinstaller#6658]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.10```
* Version of Python:  3.9.8
* Platform: Windows 
* How you installed Python: python.org/downloads 
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
seems to appear when compiling an exe with pyinstaller within another exe, running the compilation program as a .py produces a functioning exe
but running the compilation program as an exe generates a broken exe that produces the stacktrace bellow
code used to generate exe:
output = subprocess.run(f'cd %temp% && pyinstaller.exe --onefile --windowed --win-private-assemblies --win-no-prefer-redirects --clean -i {icon} --upx-dir="{upx_dir}" "{temp}\\{name}.py" --hidden-import "sqlite3" --hidden-import "json" --hidden-import "win32crypt" --hidden-import "Cryptodome.Cipher.AES" --hidden-import "discord_webhook" --hidden-import "bs4" --key {password}', stdout=subprocess.PIPE,shell=True, stderr=subprocess.PIPE, stdin=subprocess.PIPE)
please note that i disabled upx and enabled debug mode and got the same problem
i have also tried to ignore the package tkinter with --exclude-module "tkinter" but the code needs tkinter unfortunately.
i have also tried including tkinter with --hidden-import "tkinter" but it fails as well

```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 25, in <module>
FileNotFoundError: Tcl data directory "C:\Users\omtoi101\AppData\Local\Temp\_MEI234922\tcl" not found.
```
im not entirely sure what is happening, sorry if i did this submission wrong, any help is appreciated!

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> seems to appear when compiling an exe with pyinstaller within another exe

Does it work if you run pyinstaller manually?

If it does, then the parent exe's environment could be somehow interfering with discovery and collection of the Tcl/Tk stuff... In that case, please provide a minimum example of the parent script that triggers the problem (just invoking PyInstaller from a PyInstaller-compiled script via `subprocess.run()` seems to work here).

**Comment by omtoi101** [comment]
> > seems to appear when compiling an exe with pyinstaller within another exe
> 
> Does it work if you run pyinstaller manually?
> 
> If it does, then the parent exe's environment could be somehow interfering with discovery and collection of the Tcl/Tk stuff... In that case, please provide a minimum example of the parent script that triggers the problem (just invoking PyInstaller from a PyInstaller-compiled script via `subprocess.run()` seems to work here).

It does not appear if I run pyinstaller manually, everything works fine then

**Comment by rokm** [comment]
Then parent exe's environment is probably interfering with the build.

For the child build, can you open `build/<name>/Analysis-00.toc` and check if Tcl/Tk shared libraries are collected from actual python installation (as they are if you run PyInstaller manually) or are they perhaps collected from the parent exe's bundle? Does the parent exe use `tkinter`? Are `tkinter` extension, Tcl/Tk shared libs and the script data directories (`tcl`, `tcl8` and `tk`)  fully collected there?

**Comment by omtoi101** [comment]
[Analysis-00.toc.txt](https://github.com/pyinstaller/pyinstaller/files/8213252/Analysis-00.toc.txt)
this is my .toc file im not entirely sure what you want me to look for but that is for the exe built within the parent exe

**Comment by omtoi101** [comment]
> Then parent exe's environment is probably interfering with the build.
> 
> For the child build, can you open `build/<name>/Analysis-00.toc` and check if Tcl/Tk shared libraries are collected from actual python installation (as they are if you run PyInstaller manually) or are they perhaps collected from the parent exe's bundle? Does the parent exe use `tkinter`? Are `tkinter` extension, Tcl/Tk shared libs and the script data directories (`tcl`, `tcl8` and `tk`) fully collected there?

also the parent exe uses tkinter for fileboxes

**Comment by rokm** [comment]
That toc actually looks alright (the `tcl` and `tk` script directories seem to collected, from what I can tell)...

> also the parent exe uses tkinter for fileboxes

... but if I import `tkinter` in my test "builder" program, the resulting compiled program indeed lacks those directories. 

What happens is that the `pyi_rth__tkinter` runtime hook in the parent program sets `TCL_LIBRARY` and `TK_LIBRARY` environment variables to point to the bundle's collected `tcl` and `tk` directories ([here](https://github.com/pyinstaller/pyinstaller/blob/b52ff39faec1002101ad6d462b26898a6813e78e/PyInstaller/hooks/rthooks/pyi_rth__tkinter.py#L23) and [here](https://github.com/pyinstaller/pyinstaller/blob/b52ff39faec1002101ad6d462b26898a6813e78e/PyInstaller/hooks/rthooks/pyi_rth__tkinter.py#L28)). Then, when PyInstaller is ran in this environment, this causes the _tkinter standard hook to discover that `tcl` directory as the tcl library location, instead of the one from the python installation. Which is not a problem per-se, but the problematic part is that we assume that Tk library location is called `tk8.x` next to the `tcl` library directory ([here](https://github.com/pyinstaller/pyinstaller/blob/b52ff39faec1002101ad6d462b26898a6813e78e/PyInstaller/utils/hooks/tcl_tk.py#L96)), and that is not the case here (because it is collected as just `tk` into the bundle).

And the PyInstaller output should actually contain the following error message about it:
```
10018 INFO: Loading module hook 'hook-_tkinter.py' from [...]\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
10381 ERROR: Tk data directory "[...]\dist\builder\tk8.6" not found.
```
But as that error is not treated as fatal, you end up with defunct build.

So to properly collect those directories from python installation, you should perform your `subprocess.run()` call with a cleaned-up environment, e.g.:

```python
[...]
import os
subproc_env = os.environ.copy()
subproc_env.pop('TCL_LIBRARY', None)
subproc_env.pop('TK_LIBRARY', None)

output = subprocess.run(..., env=subproc_env)

[...]
```

**Comment by rokm** [comment]
I suppose we could also harden the `tk_root` discovery in the _tkinter hook code to consider `tk` as a fallback when `tk8.x` is not found. 

But on the other hand, I'm not particularly fond of accommodating the corner-case scenarios that arise when people try to spawn PyInstaller from frozen executables and similar dubious use cases. (I mean, you already assume that system has fully-functional python and PyInstaller installed, and that PyInstaller's shim exe is in the `PATH`; might as well do away with freezing the parent script).

**Comment by bwoodsend** [comment]
Likewise, if running PyInstaller from within a PyInstaller bundle really is the only way to cause this then I don't think this is worth doing anything about.

**Comment by omtoi101** [comment]
thanks for the help guys!
