### ISSUE TITLE
Remove files not accessed during run

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#6659]
Would it be possible to monitor which files in the bundle are actually accessed during program run, so that they may be excluded from the bundle?

**Comment by rokm** [comment]
If we could, we wouldn't be collecting unused files in the first place...

**Comment by rokm** [comment]
You could use `psutil` to check which shared libraries from the bundle are loaded by the program to remove the others - see https://github.com/pyinstaller/pyinstaller/discussions/6645#discussioncomment-2296509. 

But for data files, you'd probably have to monitor syscalls (e.g., using `strace` on linux).

**Comment by ghost** [comment]
Since there is a feasible method of implementing it, can we please leave the ticket open.

**Comment by ghost** [comment]
btw inotifywatch works better than strace.

**Comment by rokm** [comment]
> Since there is a feasible method of implementing it, can we please leave the ticket open.

How is it feasible on the build side? I.e., any post-build analysis and optimization (such as including `psutil` in your program code to see what shared libraries are used, or tracing the file access via strace/inotifywatch) is well beyond the scope of PyInstaller.

**Comment by ghost** [comment]
Not according to modern build standards. It's not much different in terms of legwork than including Profile Guided Optimization for example. You just run the program, monitor its file system access, and exclude everything that wasn't touched from the payload.

**Comment by rokm** [comment]
> Not according to modern build standards. It's not much different in terms of legwork than including Profile Guided Optimization for example. You just run the program, monitor its file system access, and exclude everything that wasn't touched from the payload.

It's not really the same, is it? If you miss a seldom-used branch in PGO, it just won't be optimized well. If you miss a seldom-used branch in what you're proposing, you end up with missing files and defunct program.

**Comment by ghost** [comment]
that's a good point. speaking of which, developing my installer took 12 hours of repeated guess and check fyi.

**Comment by ghost** [comment]
in theory it could have been automated using exactly the tools I used to fix the problems, locate (+updatedb), pip, conda, etc.

**Comment by rokm** [comment]
Yeah, I agree that automating this (at least to the extent possible) would be very valuable. But I still think this is beyond the scope of PyInstaller itself, and should be implemented as a separate utility, both due to complexity and due to OS-specific nature.

**Comment by bwoodsend** [comment]
You'd need a test suite with 100% coverage ran across every possible permutation of platform/OS/hardware/libraries you support to really do this without just giving yourself builds that pass smoothly through your test system but break as soon as they land in the real world. The psutil method doesn't get you nearly as far as you'd expect.

**Comment by ghost** [comment]
that's extreme

I don't see a way to build a compressed executable that excludes a list of files. Is that not supported? From what I can tell I can delete files in the dist/ directory that are not needed.

**Comment by rokm** [comment]
> I don't see a way to build a compressed executable that excludes a list of files. Is that not supported? From what I can tell I can delete files in the dist/ directory that are not needed.

You can only edit onedir builds as a post-processing step (and even with that, only collectedbinaries and data files, but not collected .pyc modules).

To exclude arbitrary files in both onedir and onefile builds, you'll need to filter `Analysis.pure`, `Analysis.binaries`, `Analysis.datas`, etc. in the spec file before those are passed on to PYZ, EXE, and COLLECT. For example, if you had a tool that generated the list of files to exclude based on runtime analysis, you'd load that list within the spec file, and then perform the filtering.

**Comment by ghost** [comment]
I was able to filter (and delete) all files not actually used during a run with a strace post-processing script. It should work for other projects, and its a one-liner.

Is there a good example of filtering Analysis.* as above?

**Comment by rokm** [comment]
> Is there a good example of filtering Analysis.* as above?

Here is an example for binaries: https://github.com/pyinstaller/pyinstaller/blob/feb6168d991e4acc20895769aa787e9db9af39fe/PyInstaller/building/build_main.py#L662

But since those properties are public, it can be done outside of a method.

**Comment by ghost** [comment]
Here is a prototype.

```bash
PROJ="my_proj_name"

cd dist

PWD="$(pwd)"

strace -fyo strace_${PROJ}.log ${PROJ}/${PROJ}

rm `comm <(cat strace_${PROJ}.log                                 |\
           tr '"<>;?:' '\n'                                       |\
           sed 's/^ *//'                                          |\
           sort -u                                                |\
           tr '\n' '\0'                                           |\
           xargs -0 -n 1 -P 8 realpath -q -e '{}' \; 2>/dev/null  |\
	   sed 's/^ *//'                                          |\
           grep -E '^\/'                                          |\
	   sort -u                                                |\
	   grep -F "${PWD}")                                       \
	 <(find ~+ . -type f                                      |\
	   sed -r "s,^\.\/,${PWD}/,"                              |\
	   sort -u)                                               |\
    cut -f2                                                       |\
    grep -vE 'anything|you|want|to|keep'` 

find . -type d -empty -delete

```
