### ISSUE TITLE
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed:

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#6667]
I am currently disabling SSL to get past this error like so:

```bash
echo 'import ssl;ssl._create_default_https_context = ssl._create_unverified_context' > hook.ssl.py

# pyinstaller ...
#     --runtime-hook=hook.ssl.py

```

I attempted including certifi, but haven't found a way forward that keeps SSL enabled.

**Comment by rokm** [comment]
And we're somehow supposed to divine in what context you are getting the error? The issue template that you chose to ignore explicitly asks for OS, python version, minimal reproducer or at least the full traceback...

**Comment by ghost** [comment]
I think this project is in need of a new maintainer. $.02

**Comment by rokm** [comment]
> I think this project is in need of a new maintainer. $.02

Feel free to apply for the position.

**Comment by ghost** [comment]
The runtime environment could be an issue. I am using Mambaforge on Ubuntu. I can't prevent dependencies from trying to reach the internet.

**Comment by rokm** [comment]
Can we see the full traceback? I.e., what component is trying to perform https access, and fails at doing so?

**Comment by rokm** [comment]
You might want to try setting `SSL_CERT_FILE` to the bundled `certifi`'s `cacert.pem`. We used to have a runtime hook for that, but was removed in pyinstaller/pyinstaller-hooks-contrib#335 for the reasons outlined in pyinstaller/pyinstaller-hooks-contrib#332.

**Comment by bwoodsend** [comment]
> I think this project is in need of a new maintainer. $.02

Only if you define *maintainer* as someone who has to spend most of his time teasing the details out of users who could have but chose not to fill in the issue template the first time. That kind of *maintenance* has you questioning your life choices pretty quickly.

**Comment by ghost** [comment]
I don't see the people involved as relevant. The only thing that matters is whether the information could be useful to the project.

**Comment by ghost** [comment]
I was able to fix it by using the old runtime hook.
