### ISSUE TITLE
Double click to execute pyinstaller onefile application on Linux

### ISSUE THREAD

**Issue by sarperkilic** [pyinstaller/pyinstaller#6670]
Hello,

I am converting my python GUI applicaton to onefile with this command:

`pyinstaller --onefile main.py`

I can run the onefile from terminal ( ./dist/main ), but cannot execute with double click.

How can I solve this problem.

My system is Ubuntu 18.04.

Thanks

**Comment by bwoodsend** [comment]
Can you tell if it's running and crashing immediately or just not running at all? It could be that your desktop still hasn't caught up with Linux's switch to PIE executables or it could be a bug in your code (most likely something that assumes your current working or relies on changes to `$PATH` made by your `.bashrc`).

**Comment by rokm** [comment]
If you want to run your program by double-clicking it from the desktop environment's UI, then create a proper launcher (the .desktop file or whatever your DE uses). 

If you absolutely must run the binary itself via double-click, you'll need to recompile the bootloader without the PIE enabled. See for example #5855.
