### ISSUE TITLE
Program launch time changes depending on how many times I open it

### ISSUE THREAD

**Issue by rowlesmr** [pyinstaller/pyinstaller#6677]
## Description of the issue
Immediately after making the (ondir) executable, I can open my program in ~5-7 s to launch. On each subsequent time, it takes ~2-2.5 minutes

Building with debug==all always gives an opening time of 5-10 s.

In all cases, the pyinstallation process works without errors, and my program actually does run with no errors. It is just the startup time that changes.

I did have to alter the matplotlib hook as per https://stackoverflow.com/a/67922414/36061

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.10```
* Version of Python: 3.9.4
* Platform: Windows 10
* How you installed Python: python.org/downloads
* Did you also try this on another platform? No. Does it work there? I don't know.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Building with 5.0dev failed on an IPython hook? I can't remember the last time I ever looked at IPython.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and
I can't. It doesn't cover erratic startup.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)
Yes. The program runs.

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

`pyinstaller --name "pdCIFplotter" --onedir --noupx ..\src\pdCIFplotter\__main__.py --icon ..\src\pdCIFplotter\icon.ico`

This creates `build` and `dist` folders and a `pdcifplotter.spec` file. At the end of the process, there is a folder `pdcifplotter` in the `dist` folder. I move this folder to another location and rename it `pdcif1`. When I run this, it takes about 2-2.5 min to open.

The `build` and `dist` folders and a `pdcifplotter.spec` file now exist. the `dist` folder is empty. I run the same command:

`pyinstaller --name "pdCIFplotter" --onedir --noupx ..\src\pdCIFplotter\__main__.py --icon ..\src\pdCIFplotter\icon.ico`

At the end of the process, there is a folder `pdcifplotter` in the `dist` folder. I move this folder and rename it `pdcif2`. When I run this, it takes about 5-7 s to open.

If I try to run pdcif1 again, it takes ~2 min. If I try to run pdcif2 again, now it takes ~2 min to open.

In all of my testing, `pyinstaller --name "pdCIFplotter" --onedir --noupx --debug=all ..\src\pdCIFplotter\__main__.py --icon ..\src\pdCIFplotter\icon.ico` produces a program that launches in 5-10 s.

### Stacktrace / full error message
There is none.

This behaviour is weird. What more can I try/information I can gather?

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
1) Is there an anti-virus program running on the system?

2) What if you use `--debug=noarchive` as opposed to `--debug=all`? What is the executable size in the case when no `--debug` flag is passed and when `--debug=all` or `--debug=noarchive` is used?

**Comment by rokm** [comment]
I've tried to make a build of https://github.com/rowlesmr/pdCIFplotter and cannot reproduce the long start time on subsequent runs.

**Comment by rowlesmr** [comment]
1) Just the standard windows security virus and threat protection. I can't turn it off, as it is centrally managed. Watching my task manager, I can see "Antimalware Service Executable" going up to 20% CPU while the program is trying to launch, and than straight back to 0% once it has.

2) Just right now, `--debug=all` took 0:05, `--debug=noarchive` took 0:05, and no debug took 2:04 to launch. Debug-all executable is 364 kB, noarchive is 360 kB, and no debug is 11561 kB.

Looks like I may have to deploy the noarchive version to get a consistent startup.

**Comment by rowlesmr** [comment]
> I've tried to make a build of https://github.com/rowlesmr/pdCIFplotter and cannot reproduce the long start time on subsequent runs.

Thanks for doing that. I don't have access to other computers for that sort of testing. I'm assuming you had no virus scanning running.

**Comment by bwoodsend** [comment]
> Just right now, --debug=all took 0:05, --debug=noarchive took 0:05, and no debug took 2:04 to launch

That is the difference between using the `run.exe` which antivirus's target all the time and `rund.exe` which they tend to ignore. There is [an unofficial copy of PyInstaller built with mingw instead of MSVC](https://github.com/webcomics/pyinstaller-builder) you can try instead.

**Comment by rokm** [comment]
> Looks like I may have to deploy the noarchive version to get a consistent startup.

Looks like it. Either your AV is picking on the executable due to size (so the 0:05 start-up time for `--debug=all` and `--debug=noarchive` is without a scan taking place), or it scans all executables, but it takes considerably longer to scan the exe with embedded PYZ archive due to its size (the difference does seem rather drastic, but I'm not surprised by such things anymore). 

> > I've tried to make a build of https://github.com/rowlesmr/pdCIFplotter and cannot reproduce the long start time on subsequent runs.
> 
> Thanks for doing that. I don't have access to other computers for that sort of testing. I'm assuming you had no virus scanning running.

I think I have Windows security running, but it didn't seem to be interfering with the executable in my case. Could be that the centralized settings that your system is subjected to are different from the defaults that I use in my test VM, though.

**Comment by rowlesmr** [comment]
>  [an unofficial copy of PyInstaller built with mingw instead of MSVC](https://github.com/webcomics/pyinstaller-builder) 

Given that readme, I'll have to follow this one!
