### ISSUE TITLE
SyntaxError: invalid syntax  pre-safe-import-module hook failed, needs fixing

### ISSUE THREAD

**Issue by MOMOANNIE** [pyinstaller/pyinstaller#6678]
When I use pyinstaller to package python projects in the windows environment, the following problems occur：

443 INFO: PyInstaller: 4.10
444 INFO: Python: 3.6.2
444 INFO: Platform: Windows-10-10.0.19041-SP0
446 INFO: wrote E:\Projects\pipeline.spec
453 INFO: UPX is not available.
454 INFO: Extending PYTHONPATH with paths
['E:\\Projects\\master0601']
  File "<string>", line 2
    import
         ^
SyntaxError: invalid syntax
1026 INFO: checking Analysis
1026 INFO: Building Analysis because Analysis-00.toc is non existent
1031 INFO: Initializing module dependency graph...
1042 INFO: Caching module graph hooks...
1061 INFO: Analyzing base_library.zip ...
  File "<string>", line 2
    import
         ^
SyntaxError: invalid syntax
  File "<string>", line 2
    import
         ^
SyntaxError: invalid syntax
4529 INFO: Caching module dependency graph...
4625 INFO: running Analysis Analysis-00.toc
4656 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\ASUS\.virtualenvs\master0601-tYJbxQyD\Scripts\python.exe
4905 INFO: Analyzing E:\Projects\Dinova\master0601\airway_pipeline.py
6397 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\ASUS\\.virtualenvs\\master0601-tYJbxQyD\\lib\\site-packages\\pyinstaller-4.10-py3.6.egg\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
6399 INFO: distutils: retargeting to non-venv dir 'c:\\users\\asus\\appdata\\local\\programs\\python\\python36\\lib'
7509 INFO: Processing pre-find module path hook site from 'C:\\Users\\ASUS\\.virtualenvs\\master0601-tYJbxQyD\\lib\\site-packages\\pyinstaller-4.10-py3.6.egg\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
7511 INFO: site: retargeting to fake-dir 'C:\\Users\\ASUS\\.virtualenvs\\master0601-tYJbxQyD\\lib\\site-packages\\pyinstaller-4.10-py3.6.egg\\PyInstaller\\fake-modules'
17171 INFO: Processing pre-safe import module hook six.moves from 'C:\\Users\\ASUS\\.virtualenvs\\master0601-tYJbxQyD\\lib\\site-packages\\pyinstaller-4.10-py3.6.egg\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
  File "<string>", line 2
    import
         ^
SyntaxError: invalid syntax
pre-safe-import-module hook failed, needs fixing.

I have searched a lot of information and have not found an effective solution. How can I solve this?

**Comment by rokm** [comment]
How did you install PyInstaller?

**Comment by MOMOANNIE** [comment]
> How did you install PyInstaller?

I downloaded the installation package and installed pyinstaller through the official website. I tried to use `pip install pyinstaller`  but all reported errors as follows:
![微信图片_20220316181833](https://user-images.githubusercontent.com/26375536/158568685-cb9223ff-d192-4a47-a1b6-d886a341f295.jpg)

**Comment by rokm** [comment]
What is the output of `pip freeze` in your environment? 

Can you try creating a new virtual environment; activate it; upgrade pip, wheel, and setuptools (`python -m pip install -U pip wheel setuptools`); and then try to install pyinstaller via `pip install pyinstaller`?

**Comment by MOMOANNIE** [comment]
> What is the output of `pip freeze` in your environment?

airway==0.1.1
altgraph==0.17.2
Brotli==1.0.9
cffi==1.15.0
colorama==0.4.4
cssselect2==0.4.1
cycler==0.11.0
decorator==4.4.2
fonttools==4.27.1
future==0.18.2
html5lib==1.1
igraph==0.9.9
imageio==2.15.0
importlib-metadata==4.8.3
importlib-resources==5.4.0
kiwisolver==1.3.1
Markdown==3.3.6
matplotlib==3.3.4
networkx==2.5.1
numpy==1.19.5
pandas==1.1.5
pefile==2021.9.3
Pillow==8.4.0
pycparser==2.21
pydicom==2.2.2
pydyf==0.1.2
pyinstaller==4.10
pyinstaller-hooks-contrib==2022.2
pyparsing==3.0.7
pyphen==0.11.0
python-dateutil==2.8.2
python-igraph==0.9.9
pytz==2021.3
PyWavelets==1.1.1
pywin32==303
pywin32-ctypes==0.2.0
PyYAML==6.0
scikit-image==0.17.2
scipy==1.5.4
six==1.16.0
texttable==1.6.4
tifffile==2020.9.3
tinycss2==1.1.1
tqdm==4.63.0
typing_extensions==4.1.1
weasyprint==54.2
webencodings==0.5.1
zipp==3.6.0
zopfli==0.1.9

 pyinstaller==4.10 is installed by me through the installation package

**Comment by MOMOANNIE** [comment]
> Can you try creating a new virtual environment; activate it; upgrade pip, wheel, and setuptools (`python -m pip install -U pip wheel setuptools`); and then try to install pyinstaller via `pip install pyinstaller`?

I removed the original virtual environment, re-created a virtual environment, and after activating it, I used `python -m pip install -U pip wheel setuptools `to update, and then used `pip install pyinstaller` to install pyinstaller, but the same error still occurs, what's going on? 
![Snipaste_2022-03-16_19-16-51](https://user-images.githubusercontent.com/26375536/158578394-2392e721-de5c-4c31-8230-7727fa367dea.png)

**Comment by rokm** [comment]
Hmm, looks like `pefile` is somehow blocking the installation of recent pyinstaller versions. So pip tries to install an older version, which is not compatible with your python version (e.g., pyinstaller 2.0, which results in SyntaxError seen at the top of your screenshot).

**Comment by MOMOANNIE** [comment]
> Hmm, looks like `pefile` is somehow blocking the installation of recent pyinstaller versions. So pip tries to install an older version, which is not compatible with your python version (e.g., pyinstaller 2.0, which results in SyntaxError seen at the top of your screenshot).

Hmm, Has this happened before? I've looked online for this problem, but it didn't solve it. what should I do?

**Comment by rokm** [comment]
I haven't seen this happen before, so no idea, really.

What happens if you start with clean virtual environment again, upgrade pip/wheel/setuptools, then install pefile (`pip install pefile`), and then try to pin pyinstaller version (`pip install pyinstaller==4.10`)? Do you see any errors reported by pip in previous steps?

**Comment by MOMOANNIE** [comment]
> I haven't seen this happen before, so no idea, really.
> 
> What happens if you start with clean virtual environment again, upgrade pip/wheel/setuptools, then install pefile (`pip install pefile`), and then try to pin pyinstaller version (`pip install pyinstaller==4.10`)? Do you see any errors reported by pip in previous steps?

I cleared the virtual environment, updated pip, etc., and then installed pefile, and it started reporting errors as follows:

![Snipaste_2022-03-16_19-16-51](https://user-images.githubusercontent.com/26375536/158586058-ece69915-05e4-4d85-a3a5-5747b6374da3.png)

**Comment by rokm** [comment]
What are you using to create virtual environment? The `venv` module, or something else?

**Comment by MOMOANNIE** [comment]
> What are you using to create virtual environment? The `venv` module, or something else?

I am using pipenv of windows system

**Comment by rokm** [comment]
Can you try a regular `venv` instead?

**Comment by MOMOANNIE** [comment]
> Can you try a regular `venv` instead?

I tried to use the virtual environment created by conda, but an error was also reported during the packaging process using pyinstaller, and there was no exe file in the generated dist folder

**Comment by rokm** [comment]
Is this a conda python?

**Comment by MOMOANNIE** [comment]
> Is this a conda python?

No, it's not conda python, my first attempt was to use a conda virtual environment and it failed, then I used pipenv to create a virtual environment and I got those errors above

**Comment by rokm** [comment]
What if you try to install the latest version of `pefile` (`pip install pefile==2021.9.3`) - what is the error in that case? Because again, the syntax errors in your screenshot are from old versions that are probably incompatible with your python)...

**Comment by MOMOANNIE** [comment]
> What if you try to install the latest version of `pefile` (`pip install pefile==2021.9.3`) - what is the error in that case? Because again, the syntax errors in your screenshot are from old versions that are probably incompatible with your python)...

When I install the latest version of the prefile, I get the following error:
![Snipaste_2022-03-16_22-48-23](https://user-images.githubusercontent.com/26375536/158617879-0482ef62-eba7-4a36-b260-c4963bf94d05.png)

**Comment by rokm** [comment]
Have you install/upgraded `pip`, `wheel` and `setuptools` in your environment?

**Comment by rokm** [comment]
What is the output of `where pip` and `where python`, and of `pip --version` and `python -c "import setuptools; print(setuptools.__version__)"`?

**Comment by MOMOANNIE** [comment]
> Have you install/upgraded `pip`, `wheel` and `setuptools` in your environment?

Yes，I have，I used `python -m pip install -U pip wheel setuptools` to update

**Comment by MOMOANNIE** [comment]
> What is the output of `where pip` and `where python`, and of `pip --version` and `python -c "import setuptools; print(setuptools.__version__)"`?

The output is as follows：
![Snipaste_2022-03-17_10-01-09](https://user-images.githubusercontent.com/26375536/158721801-f082dbc9-b426-446f-8541-8c7bf42e863f.png)
![1](https://user-images.githubusercontent.com/26375536/158721811-39c72f08-5944-4cf1-b1ae-d6c6d57a5774.png)

**Comment by rokm** [comment]
Hmm, this all looks fine.

What if you download the [pefile-2021.9.3.tar.gz](https://files.pythonhosted.org/packages/ee/e1/a7bd302cf5f74547431b4e9b206dbef782d112df6b531f193bb4a29fb1b9/pefile-2021.9.3.tar.gz) manually, unpack it, move into unpacked directory, and try to either:
- try to install via `pip install .`
- or try to build wheel via `python setup.py bdist_wheel`

Do these two commands work, or do you also get the syntax error?

**Comment by MOMOANNIE** [comment]
> * try to install via `pip install .`

when I try to  use the command, the error is as follows:
![1](https://user-images.githubusercontent.com/26375536/158762237-6c7677e6-8faf-4cf7-b2d9-324486f9aa6c.png)





> * or try to build wheel via `python setup.py bdist_wheel`

when  I  try to use the command, no errors appear


![2](https://user-images.githubusercontent.com/26375536/158762456-eff853ac-8377-48a2-a741-7dcbf886d5c5.png)

**Comment by rokm** [comment]
> > * try to install via `pip install .`
> 
> when I try to use the command, the error is as follows:

Not `pip install setup.py` - use `pip install .`

---

But if the second command succeeded, you should have a .whl file in the dist directory. Try installing it via `pip install dist\pefile-2021.9.3-py3-none-any.whl`.

**Comment by MOMOANNIE** [comment]
> Not `pip install setup.py` - use `pip install .`

I use `pip install .`, I also get the syntax error

![1](https://user-images.githubusercontent.com/26375536/158773251-2b8943d0-cb8a-4b09-950b-fc78c83c2d20.png)



> But if the second command succeeded, you should have a .whl file in the dist directory. Try installing it via `pip install dist\pefile-2021.9.3-py3-none-any.whl`.

I use `pip install dist\pefile-2021.9.3-py3-none-any.whl` ,the error  as follows:
![2](https://user-images.githubusercontent.com/26375536/158773591-b13c4775-640f-4489-8b28-f5865a723ace.png)

**Comment by rokm** [comment]
What if you try to manually download the `future-0.18.2.tar.gz`, unpack it and build the wheel, then try to install the built `future` wheel?

**Comment by MOMOANNIE** [comment]
> What if you try to manually download the `future-0.18.2.tar.gz`, unpack it and build the wheel, then try to install the built `future` wheel?

Yes, I can successfully install future by this method


![3](https://user-images.githubusercontent.com/26375536/158779664-568e946a-a665-4cb1-a0e4-38cc0d23eca9.png)

**Comment by rokm** [comment]
Ok, what about `pefile`? Does it install now that `future` has been installed?

**Comment by MOMOANNIE** [comment]
> Ok, what about `pefile`? Does it install now that `future` has been installed?

Yes, the prefile is already installed, haha

![4](https://user-images.githubusercontent.com/26375536/158791387-fe9bc89c-60a6-4be0-b0ee-9b7d487e2012.png)

**Comment by rokm** [comment]
Does `pip install pyinstaller` work now?

**Comment by MOMOANNIE** [comment]
> Does `pip install pyinstaller` work now?

Yes, It works now, thank you very much
![5](https://user-images.githubusercontent.com/26375536/158803107-a3f619ef-6953-4506-9040-33c34a667ea6.png)

**Comment by MOMOANNIE** [comment]
> Does `pip install pyinstaller` work now?

When I successfully installed pyinstaller and used pyinstaller to package my project, this problem ```
SyntaxError: invalid syntax
pre-safe-import-module hook failed, needs fixing.
```still occurs. What's going on?

![6](https://user-images.githubusercontent.com/26375536/158811891-26539e7a-1860-4ac5-9fd7-bd818ae6de2c.png)

**Comment by rokm** [comment]
This has nothing to do with ` pre-safe-import-module hook failed, needs fixing.`, there's other syntax errors before that, too.

There's something in you environment that triggers that, and I have absolutely no idea what it is. But it's definitely not related to PyInstaller, as the exactly same error was popping up during the above installation attempts for other packages. 

I'm out of ideas - perhaps you should try reinstalling your python, or upgrading pipenv.

**Comment by bwoodsend** [comment]
Those syntax errors are presumably happening inside `exec_statement()` calls. That's the only place I know that executes raw strings without setting the source filename parameter and that would not always abort the build. And I imagine that the cause will by some invalid Python file kicking around in `sys.path` with the same name as some standard library package. Can you run it using:
```
python -vvvv PyInstaller -Dw airway_pipeline.py >logs.txt 2>&1
```
That'll create a file called `logs.txt` - can you upload that here? Those logs contain which files Python is trying to import.

**Comment by bwoodsend** [comment]
Incidentally, PyInstaller 4.10 doesn't support Python 3.6 so this particular setup is doomed anyway.

**Comment by rokm** [comment]
> Incidentally, PyInstaller 4.10 doesn't support Python 3.6 so this particular setup is doomed anyway.

Was #6475 actually backported to `v4`? There still seem to be references to 3.6 support in the code (e.g., [here](https://github.com/pyinstaller/pyinstaller/blob/669313ba4c5c1403ebeb335c35cb68c8c6ba5dd4/bootloader/src/pyi_pythonlib.c#L555-L560) or [here](https://github.com/pyinstaller/pyinstaller/blob/669313ba4c5c1403ebeb335c35cb68c8c6ba5dd4/PyInstaller/archive/writers.py#L370-L373)).

**Comment by bwoodsend** [comment]
Hmm, you're right. [v4 CI has also been running Python 3.6](https://github.com/pyinstaller/pyinstaller/actions/runs/1968112084).

**Comment by MOMOANNIE** [comment]
> python -vvvv PyInstaller -Dw airway_pipeline.py >logs.txt 2>&1

I use this command to generate this log tex，the logs.txt  says `python: can't open file 'PyInstaller': [Errno 2] No such file or directory`, but I have already installed pyinstaller, why can't I find it?
[logs.txt](https://github.com/pyinstaller/pyinstaller/files/8299070/logs.txt)
t

**Comment by MOMOANNIE** [comment]
> python -vvvv PyInstaller -Dw airway_pipeline.py >logs.txt 2>&1

I use this command to generate this log text，the logs.txt  says `python: can't open file 'PyInstaller': [Errno 2] No such file or directory`, but I have already installed pyinstaller, why can't I find it?
[logs.txt](https://github.com/pyinstaller/pyinstaller/files/8299070/logs.txt)

**Comment by rokm** [comment]
That command should have been:

```
python -vvvv -m PyInstaller -Dw airway_pipeline.py >logs.txt 2>&1
```

(the original is missing the `-m` before `PyInstaller`).

**Comment by MOMOANNIE** [comment]
> python -vvvv -m PyInstaller -Dw airway_pipeline.py >logs.txt 2>&1

I try the command, the logs.txt as follows:
[logs.txt](https://github.com/pyinstaller/pyinstaller/files/8302556/logs.txt)

**Comment by bwoodsend** [comment]
What about:

```
python -vvvv C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\PyInstaller\hooks\pre_safe_import_module\hook-six.moves.py >logs.txt 2>&1
```

**Comment by MOMOANNIE** [comment]
> What about:
> 
> ```
> python -vvvv C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\PyInstaller\hooks\pre_safe_import_module\hook-six.moves.py >logs.txt 2>&1
> ```

 I use the command, the logs.txt as follows:
[logs.txt](https://github.com/pyinstaller/pyinstaller/files/8308686/logs.txt)

**Comment by bwoodsend** [comment]
Hmm, that last one does indeed show it going ballistic but for a different reason. It appears to be trying to `import C:\\Users\\ASUS\\`. I dread to think how it got into that mess.
```
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.pyd
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.py
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.pyw
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.pyc
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.py
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.pyw
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.pyc
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.py
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.pyw
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.pyc
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.py
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.pyw
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.pyc
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.pyd
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.py
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.pyw
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.pyc
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.pyd
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.py
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.pyw
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.pyc
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.pyd
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.py
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.pyw
# trying E:\Projects\Dinova\Airway-master0601\C:\Users\ASUS\.pyc
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.py
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.pyw
# trying c:\users\asus\appdata\local\programs\python\python36\DLLs\C:\Users\ASUS\.pyc
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.py
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.pyw
# trying c:\users\asus\appdata\local\programs\python\python36\lib\C:\Users\ASUS\.pyc
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.pyd
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.py
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.pyw
# trying c:\users\asus\appdata\local\programs\python\python36\C:\Users\ASUS\.pyc
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.pyd
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.py
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.pyw
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\C:\Users\ASUS\.pyc
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.cp36-win_amd64.pyd
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.pyd
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.py
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.pyw
# trying C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\lib\site-packages\C:\Users\ASUS\.pyc
C:\Users\ASUS\.virtualenvs\Airway-master0601-tYJbxQyD\Scripts\python.exe: Error while finding module specification for 'C:\\Users\\ASUS\\.virtualenvs\\Airway-master0601-tYJbxQyD\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py' (ModuleNotFoundError: No module named 'C:\\Users\\ASUS\\')
```
I reckon reinstalling Python is the most sensible thing to do after all.

**Comment by MOMOANNIE** [comment]
> I reckon reinstalling Python is the most sensible thing to do after all.

So which version of python do I reinstall?

**Comment by bwoodsend** [comment]
Just the latest will do. Unless you want to support Windows 7, in which case use 3.8.

**Comment by MOMOANNIE** [comment]
> Just the latest will do. Unless you want to support Windows 7, in which case use 3.8.

Ok, then I will try to reinstall python

**Comment by bwoodsend** [comment]
Did you get it working? I'd like to avoid open but stale issue threads.
