### ISSUE TITLE
cx_oracle hook - bundle additional files

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#668]
**Original date**: 2013/02/09
**Original reporter**: *wallenpb AND gmail DOT  COOM *

I am trying to use pyinstaller with a the cx_oracle module.  The program runs fine from the interpreter and the oci.dll, oraociicus10.dll, and tnsnames.ora files in the same folder with the .py program file.  After compiling I get the following error even though I have placed these files in the same folder with output .exe file.  What do I need to do?

cx_Oracle.InterfaceError: Unable to acquire Oracle environment handle

**Comment by htgoebel** [comment]
I'm closing this. It's nearly two years old now and I assume nobody is working on it. If anybody is using Oracle and wants to implement this, go ahead. We'd appreciate a pull-request. (Or you could ask one of the core-developers for paid support.)
