### ISSUE TITLE
missing hooks for Cryptodome and Cryptodomex

### ISSUE THREAD

**Issue by M909M** [pyinstaller/pyinstaller#6680]
Hello,

I discovered an Issue with the PyInstaller4.8 that is not existing in 3.6 : 
When creating an .exe with 3.6 I got a Folder named "Cryptodome" in the compiled result, but not so with 4.8 (it´s completely missing).
When I copy this folder into the 4.8 compiled Folder it´s running again.

I searched through the "hooks" and discovered that in the PyInstaller - Folder for the 4.8 ("\Lib\site-packages\PyInstaller\hooks\" 
the files are missing :

"hook-Crypto.py"
"hook-Cryptodome.py"

unfortunately I don´t have experience how to implement it correctly and I think this would be helpfull for other Users too.... 

best regards
Michael M. 

P.S.: 
figured it out, copied to "\Anaconda_32Bit\Lib\site-packages\PyInstaller\hooks" and it will be implemented again =)

**Comment by rokm** [comment]
These hooks were moved out of `pyinstaller` into `pyinstaller-hooks-contrib` ([here](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-Crypto.py) and [here](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-Cryptodome.py)), which should end up installed as a dependency of recent `pyinstaller` versions. Is it installed in your case?

**Comment by rokm** [comment]
> figured it out, copied to "\Anaconda_32Bit\Lib\site-packages\PyInstaller\hooks" and it will be implemented again =)

Ah, this is anconda-packaged PyInstaller 4.x? Looks like they indeed do not package/install the contrib hooks...

**Comment by rokm** [comment]
> Looks like they indeed do not package/install the contrib hooks...

Or rather, the PyInstaller 4.8 package in the main conda channel does not install contrib hooks, while the PyInstaller 4.10 package from conda-forge does. So use that instead: ` conda install -c conda-forge pyinstaller `

**Comment by M909M** [comment]
Sorry, no improvement, did so : conda install -c conda-forge pyinstaller

but still no "hooks-contrib" :
![image](https://user-images.githubusercontent.com/90220222/158576937-29f9452d-597b-4222-900a-9db4d3c11549.png)

.exe afterwards again not running : 
"OSError: Cannot load native module 'Cryptodome.Cipher._raw_ecb': Trying '_raw_ecb.cp38-win32.pyd':   ...etc"

and same "fix" copying the hooks manually in the "hooks" Folder solves this Issue again....

**Comment by rokm** [comment]
When you installed `pyinstaller` from conda-forge, did it install `pyinstaller-hooks-contrib` package is well or not?

That screenshot proves nothing; the contrib hooks should end up in `Lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks`.

**Comment by M909M** [comment]
When installing from conda-forge the Folder "Lib\site-packages\_pyinstaller_hooks_contrib\" is not existing afterwards, 
just the "PyInstaller" Folder from the screenshot.

**Comment by rokm** [comment]
Did it upgrade PyInstaller to 4.10 at all? Because now that I look at it, it looks like conda-forge doesn't provide 32-bit windows builds...

So I guess at this point, you could try installing `pyinstaller` via `pip` (which should also pull in `pyinstaller-hooks-contrib`), or just install `pyinstaller-hooks-contrib` via `pip`.

**Comment by rokm** [comment]
But in the end, this is a conda packaging issue - they are providing `pyinstaller` 4.x package without contrib hooks in their main channel. Report the issue with them if you want it fixed.

**Comment by M909M** [comment]
> Did it upgrade PyInstaller to 4.10 at all? Because now that I look at it, it looks like conda-forge doesn't provide 32-bit windows builds...
> 
> So I guess at this point, you could try installing `pyinstaller` via `pip` (which should also pull in `pyinstaller-hooks-contrib`), or just install `pyinstaller-hooks-contrib` via `pip`.

-> the latest Version from Anaconda is 4.8. Pip is no solution, because I prefer using the conda package installer, pip will just destroy the whole installation. 

Thx for your efforts, i´ll report it to Anaconda, 
greetings and have a nice day =)
