### ISSUE TITLE
The packaged .exe only works on one machine

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#669]
**Original date**: 2013/02/10
**Original reporter**: *martijnende AND gmail DOT  COOM *

Hi, I'm not sure if this is the right place to report this, but it appears that when I create a single file .exe using PyInstaller, it only works on one computer. My other computer produces a bunch of errors:

```
Cannot build import library: "C:\Users\****\AppData\Local\Temp\_MEI94842\libs\python27.lib" not found
Cannot build import library: "C:\Users\****\AppData\Local\Temp\_MEI94842\libs\python27.lib" not found
Exception in Tkinter callback
[ some bunch of tracebacks ]
CompileError: error: could not create 'c:\users\****\appdata\local\temp\****\python27_intermediate\
compiler_d41d8cd98f00b204e9800998ecf8427e\Release\users\****\****\pyinstaller\gui\dist\gui.exe?175104':
The syntax of the filename, directoryname or volumename is incorrect
```

Imported libraries: Tkinter, tkFileDialog, tkMessageBox, numpy, matplotlib.pyplot, scipy.signal.medfilt, scipy.weave, pywt

There are two pieces of code that utilize weave.inline (C++) which seems somehow related to the problem (it works up to the point of reaching weave code).

**Comment by htgoebel** [comment]
This clound to be related to #362
