### ISSUE TITLE
Python 3.10 error installing

### ISSUE THREAD

**Issue by nielson266** [pyinstaller/pyinstaller#6691]
I tried to install and received the version error,
The current project's Python requirement (>=3.10) is not compatible with some of the required packages
        - pyinstaller requires Python <3.11,>=3.6, so it will not be satisfied for Python >=3.11,
my current version of python is 3.10.3.

**Comment by rokm** [comment]
How are you trying to install PyInstaller? `pip install pyinstaller` or something else?

**Comment by nielson266** [comment]
> How are you trying to install PyInstaller? or something else?`pip install pyinstaller`

poetry add pyinstaller

**Comment by rokm** [comment]
> > How are you trying to install PyInstaller? or something else?`pip install pyinstaller`
> 
> poetry add pyinstaller

That's not our problem, then. Your `pyproject.toml` has a python version range that's wider than what pyinstaller supports, and `poetry` doesn't seem to like that.

**Comment by rokm** [comment]
See this: https://github.com/python-poetry/poetry/issues/1413#issuecomment-974830488
