### ISSUE TITLE
Better 

### ISSUE THREAD

**Issue by Tosh0kan** [pyinstaller/pyinstaller#6695]
**Describe the solution you'd like**
I would PyInstaller to not need me to add a custom function in my script for me to be able to use other files (like JSONs) when I'm using the `--onefile` option

**Describe alternatives you've considered**
Currently, anyone that wants to use the python script in conjunction with any other kind of file (JSONs, images, anything) needs to use a function brilliantly made by a user on StackOverflow, described here (https://stackoverflow.com/a/60953781/10925021).

**Comment by bwoodsend** [comment]
If you're having to do anything differently at runtime in a frozen application to locate resources then you're doing it wrong. [The docs already covers this](https://pyinstaller.readthedocs.io/en/v4.9/runtime-information.html#placing-data-files-at-expected-locations-inside-the-bundle).
