### ISSUE TITLE
Package/module name match -> no error message

### ISSUE THREAD

**Issue by snowdonr** [pyinstaller/pyinstaller#6702]
I've run into the issue described in bug [#2049](https://github.com/pyinstaller/pyinstaller/issues/2049#issue-160286511), i.e. a package and the initial module 'scriptname' have the same name (excepting the .py suffix). If the package __init__.py is empty (or absent) there is no relevant error message when the pyinstaller runs, or when the program runs, it simply does nothing. If there is a print statement in the __init__.py the error message is not helpful:
```
Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding
Python runtime state: core initialized
ModuleNotFoundError: No module named 'encodings'
```
Although the discussion for bug 2049 suggests this situation is 'not permitted' in python, the ambiguity never comes up as the module is the entry point and is never **itself** called.

Found with: pyinstaller 4.10, Windows 10, python 3.7-9

Proposed solutions:
- An error message would save substantial time when someone stumbles across this issue
- In the specific case of the entry point & module matching either name could be automatically renamed

Example to reproduce:
matching_name.py:
```
print("Test point one")
from matching_name import call_module

if __name__ == '__main__':
    call_module.InnerClass()
```

matching_name/call_module.py:
```
class InnerClass(object):
    def __init__(self):
        print("Inner init test point")
```

pyinstaller matching_name.py

**Comment by bwoodsend** [comment]
Hrmm, well I can't even run your code under normal Python...
```python
> python matching_name.py
Test point one
Test point one
Traceback (most recent call last):
  File "/e/notebooks/pyi-issues/6702/matching_name.py", line 2, in <module>
    from matching_name import call_module
  File "/e/notebooks/pyi-issues/6702/matching_name.py", line 2, in <module>
    from matching_name import call_module
ImportError: cannot import name 'call_module' from partially initialized module 'matching_name' (most likely due to a circular import) (/e/notebooks/pyi-issues/6702/matching_name.py)
```
... so I'd be pretty reluctant to try and make PyInstaller magic a functional application out of it. I wouldn't be opposed to some kind of warning if a module name is ambiguous but I don't see how PyInstaller can do any more than that.

Incidentally, I get exactly the same error when ran through PyInstaller.
```python
> ./matching_name 
Test point one
Test point one
Traceback (most recent call last):
  File "matching_name.py", line 2, in <module>
  File "/io/PyInstaller/loader/pyimod03_importers.py", line 495, in exec_module
  File "matching_name.py", line 2, in <module>
ImportError: cannot import name 'call_module' from partially initialized module 'matching_name' (most likely due to a circular import) (/e/notebooks/pyi-issues/6702/dist/matching_name/matching_name.pyc)
[195227] Failed to execute script 'matching_name' due to unhandled exception!
```

Not sure how you got that encodings error - that usually implies you've moved the executable out of a onedir build and ran it without the rest of the bundle.

**Comment by rokm** [comment]
> `ImportError: cannot import name 'call_module' from partially initialized module 'matching_name' (most likely due to a circular import) (/e/notebooks/pyi-issues/6702/matching_name.py)`

This happens if the package is a namespace package. If it has an `__init__.py`, then the sample code does work in python.

**Comment by rokm** [comment]
That said, the situation with entry-point script shadowing the package name (or vice versa, depending on your perspective) is the same as if you tried to run the entry point as `python -m matching_name` instead of `python matching_name.py`. If there was no package named `matching_name`, the script (now treated as module) would run correctly, but if the package shadows the module, you'll get an error.

So I don't think it's unreasonable to consider this corner case as a situation that should be avoided on user's part, instead of trying to accommodate it.

**Comment by snowdonr** [comment]
That's quite reasonable, the primary motivator was that the code ran fine directly in my development but the pyinstaller executable runs and does nothing (e.g. no print test point output). Without some clue as to the source this is quite tricky to debug, so even a message related to the fact that the entry point is empty (as presumably the .exe is pointing at the `__init__.py`) would be helpful.

I agree it is obviously not a common situation however, and perhaps python itself should be explicitly failing or warning when this sort of shadowing happens. Also, this will teach me not to be lazy in naming, even when the entry point is essentially a stub for the module.

**Comment by bwoodsend** [comment]
I suppose the specific case of the provided entry point script being replaced with another module/package of the same name is detectable. We can compare the path of the entry point script to the path of the module that `modulegraph` picks up and raise an error if they don't match. Producing a functional program out of that case still sounds impossible to me.

**Comment by rokm** [comment]
I suppose detecting this situation and raising an error should be enough.
