### ISSUE TITLE
investigate what bootloader code changes cause antivirus alert

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#671]
**Original date**: 2013/02/22

I also have problems with my virus scanner (Sophos for PC), which detects support/loader/Windows-32bit/run.exe as virus/malware. When I install my frozen app on other's computer, I also see various virus warnings. Likewise, simply downloading my app in Google Chrome produces a warning (this may be a dangerous program -- keep it?).

I did some looking at the commit history on github. On my PC, Sophos is happy until rev b793f5b362295fed9b3374aceaaccbb15c8c2229. The previous recompile was at 17d5baa0e6916262623521b835403bf89db60a18, less than 20 commits away; of those, only a few have changes to the bootloader source. If I compiled each of these source changes and tested, would someone be able and willing to try to work around the change that triggers the virus warnings?

**Comment by htgoebel** [comment]
I'm closing this issue. IMHO this is a wast of time because nobody knows what signatures anti-malware programs come up with next.
