### ISSUE TITLE
Acticate splash text directly from the --splash option

### ISSUE THREAD

**Issue by mkhoshbin1** [pyinstaller/pyinstaller#6718]
**Is your feature request related to a problem? Please describe.**
In order to have text on the splash screen, I have to create a spec file and activate the text message by changing the Splash object's from *None* to a tuple.
This means that I have to create a spec file, edit it using Powershell, and then run it.

**Describe the solution you'd like**
I would like the --splash option to have one of the following:
1. position parameter which is added to the spec file.
2. A Boolean value which if set to true, puts the text at a predefined position (such as 5% from the lower left edges which is the norm).

**Comment by bwoodsend** [comment]
We don't like to add everything as command line options because otherwise `pyinstaller --help` ends up a mile long. I already normally have to grep it to find what I'm looking for.

>  This means that I have to create a spec file, edit it using Powershell, and then run it.

This sounds like a pretty minor hardship to me.

**Comment by mkhoshbin1** [comment]
OK. Seems reasonable. I'll close the issue.

**Comment by TheBoojah** [comment]
I have a use case where I call pyinstaller from another python script file like so:
```
import PyInstaller.__main__
import pyinstaller_versionfile

pyinstaller_versionfile.create_versionfile(
# versionfile stuff here
)

PyInstaller.__main__.run([
    'VARIABLESCRIPTFILE',
    '--name=foobar',
    '--onefile',
    '--noconsole',
    '--noconfirm',
    '--splash=splash.png',
    '--version-file=versionfile.txt',
    '--distpath=foopath1',
    '--workpath=foopath2',
    '--specpath=foopath3',
    '--upx-dir=foopath4',
])
```
Using versionfile and variable filenames and locations for my build process.

How could I enable text_pos using this mode of calling pyinstaller?
Editing the .spec file manually is just overvritten.

**Comment by rokm** [comment]
> How could I enable text_pos using this mode of calling pyinstaller?

You cannot. If you want to use splash options, you need to build from the spec file instead of building from .py file (which re-generates .spec file on each run).
