### ISSUE TITLE
ModuleNotFoundError: No module named 'svm'

### ISSUE THREAD

**Issue by sreekar-G** [pyinstaller/pyinstaller#6725]
Hello, 
 
We are using a SVM based detections but when we integrate with Pyinstaller we are getting error like that we don't have module name like svm. 
but when we try running the python3 main.py we are not able to get any import issue. 

We tried using hook files and stuff you guys mentioned in the documentation but we are not able to trace back the issue.

On running the libsvm/python we are facing this issue. please let us know

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

71 INFO: PyInstaller: 4.10
71 INFO: Python: 3.8.10
77 INFO: Platform: Linux-5.13.0-39-generic-x86_64-with-glibc2.29
77 INFO: wrote /home/local/ZOHOCORP/sree-11756/bms/learnopencv/ImageMetrics/Python/libsvm/python/main.spec
78 INFO: UPX is not available.
79 INFO: Extending PYTHONPATH with paths
['/home/local/ZOHOCORP/sree-11756/bms/learnopencv/ImageMetrics/Python']
184 INFO: checking Analysis
184 INFO: Building Analysis because Analysis-00.toc is non existent
184 INFO: Initializing module dependency graph...
185 INFO: Caching module graph hooks...
191 INFO: Analyzing base_library.zip ...
1595 INFO: Processing pre-find module path hook distutils from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
1625 INFO: distutils: retargeting to non-venv dir '/usr/lib/python3.8'
3010 INFO: Caching module dependency graph...
3085 INFO: running Analysis Analysis-00.toc
3110 INFO: Analyzing /home/local/ZOHOCORP/sree-11756/bms/learnopencv/ImageMetrics/Python/libsvm/python/main.py
4106 INFO: Processing pre-find module path hook site from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_find_module_path/hook-site.py'.
4106 INFO: site: retargeting to fake-dir '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/fake-modules'
5755 INFO: Processing module hooks...
5755 INFO: Loading module hook 'hook-cv2.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
5824 INFO: Loading module hook 'hook-_tkinter.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5873 INFO: checking Tree
5873 INFO: Building Tree because Tree-00.toc is non existent
5873 INFO: Building Tree Tree-00.toc
5877 INFO: checking Tree
5877 INFO: Building Tree because Tree-01.toc is non existent
5877 INFO: Building Tree Tree-01.toc
5905 WARNING: Tcl modules directory /usr/share/tcltk/tcl8.6/../tcl8 does not exist.
5907 INFO: Loading module hook 'hook-difflib.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5909 INFO: Loading module hook 'hook-distutils.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5914 INFO: Loading module hook 'hook-distutils.util.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5916 INFO: Loading module hook 'hook-encodings.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5944 INFO: Loading module hook 'hook-heapq.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5947 INFO: Loading module hook 'hook-lib2to3.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5954 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5955 INFO: Loading module hook 'hook-numpy._pytesttester.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5956 INFO: Loading module hook 'hook-numpy.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5963 INFO: Import to be excluded not found: 'f2py'
5981 INFO: Loading module hook 'hook-packaging.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5981 INFO: Loading module hook 'hook-pickle.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
5982 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
6303 INFO: Processing pre-safe import module hook win32com from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
6395 WARNING: Hidden import "pkg_resources.py2_warn" not found!
6395 WARNING: Hidden import "pkg_resources.markers" not found!
6397 INFO: Loading module hook 'hook-scipy.linalg.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
6397 INFO: Loading module hook 'hook-scipy.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
6398 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
6399 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
7074 INFO: Processing pre-safe import module hook gi.repository.GLib from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GLib.py'.
8243 INFO: Processing pre-safe import module hook six.moves from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
13273 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13273 INFO: Loading module hook 'hook-scipy.stats._stats.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13274 INFO: Loading module hook 'hook-setuptools.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13739 INFO: Loading module hook 'hook-sqlite3.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13776 INFO: Loading module hook 'hook-sysconfig.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13776 INFO: Loading module hook 'hook-wcwidth.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13778 INFO: Loading module hook 'hook-xml.dom.domreg.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13779 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13779 INFO: Loading module hook 'hook-xml.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
13780 INFO: Loading module hook 'hook-IPython.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
13981 INFO: Import to be excluded not found: 'PyQt4'
13981 INFO: Import to be excluded not found: 'PySide'
13983 INFO: Import to be excluded not found: 'gtk'
13983 INFO: Loading module hook 'hook-certifi.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
13984 INFO: Loading module hook 'hook-jedi.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
14177 INFO: Loading module hook 'hook-parso.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/stdhooks'...
14181 INFO: Loading module hook 'hook-PIL.Image.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
14391 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
14393 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
14395 INFO: Loading module hook 'hook-PIL.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
14398 INFO: Import to be excluded not found: 'PySide6'
14401 INFO: Import to be excluded not found: 'PyQt6'
14402 INFO: Loading module hook 'hook-PyQt5.QtCore.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.23ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/pkg_resources/__init__.py:123: PkgResourcesDeprecationWarning: 0.1.36ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
14497 INFO: Loading module hook 'hook-PyQt5.QtGui.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
14545 INFO: Loading module hook 'hook-PyQt5.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
14558 WARNING: Hidden import "sip" not found!
14558 INFO: Loading module hook 'hook-gi.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
14565 INFO: Loading module hook 'hook-gi.repository.GLib.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
14751 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
15452 INFO:   Matplotlib backend "GTK3Agg": added
15987 INFO:   Matplotlib backend "GTK3Cairo": added
16476 INFO:   Matplotlib backend "GTK4Agg": added
16967 INFO:   Matplotlib backend "GTK4Cairo": added
17153 INFO:   Matplotlib backend "MacOSX": ignored
    cannot import name '_macosx' from 'matplotlib.backends' (/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/matplotlib/backends/__init__.py)
17478 INFO:   Matplotlib backend "nbAgg": ignored
    No module named 'IPython.kernel'
17780 INFO:   Matplotlib backend "QtAgg": added
18082 INFO:   Matplotlib backend "QtCairo": added
18377 INFO:   Matplotlib backend "Qt5Agg": added
18677 INFO:   Matplotlib backend "Qt5Cairo": added
18870 INFO:   Matplotlib backend "TkAgg": ignored
    cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
19067 INFO:   Matplotlib backend "TkCairo": ignored
    cannot import name 'ImageTk' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
19356 INFO:   Matplotlib backend "WebAgg": added
19861 INFO:   Matplotlib backend "WX": ignored
    No module named 'wx'
20043 INFO:   Matplotlib backend "WXAgg": ignored
    No module named 'wx'
20223 INFO:   Matplotlib backend "WXCairo": ignored
    No module named 'wx'
20478 INFO:   Matplotlib backend "agg": added
20740 INFO:   Matplotlib backend "cairo": added
21264 INFO:   Matplotlib backend "pdf": added
21787 INFO:   Matplotlib backend "pgf": added
22089 INFO:   Matplotlib backend "ps": added
22358 INFO:   Matplotlib backend "svg": added
22846 INFO:   Matplotlib backend "template": added
22885 INFO: Processing pre-safe import module hook gi.repository.Gio from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Gio.py'.
22885 INFO: Processing pre-safe import module hook gi.repository.GObject from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GObject.py'.
22885 INFO: Processing pre-safe import module hook gi.repository.Gtk from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Gtk.py'.
22885 INFO: Processing pre-safe import module hook gi.repository.Gdk from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Gdk.py'.
22901 INFO: Processing pre-safe import module hook gi.repository.GdkPixbuf from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GdkPixbuf.py'.
24363 INFO: Loading module hook 'hook-matplotlib.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
24563 INFO: Loading module hook 'hook-pygments.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
25645 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
25672 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
25678 INFO: Loading module hook 'hook-PyQt5.QtWidgets.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
25761 INFO: Loading module hook 'hook-gi.repository.GObject.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
25850 WARNING: Hidden import "gi._gobject" not found!
25850 INFO: Loading module hook 'hook-gi.repository.Gdk.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
25926 INFO: Processing pre-safe import module hook gi.repository.cairo from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.cairo.py'.
25926 INFO: Processing pre-safe import module hook gi.repository.Pango from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Pango.py'.
25927 INFO: Loading module hook 'hook-gi.repository.GdkPixbuf.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
26061 INFO: Processing pre-safe import module hook gi.repository.GModule from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.GModule.py'.
26061 INFO: Loading module hook 'hook-gi.repository.Gio.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
26186 INFO: Loading module hook 'hook-gi.repository.Gtk.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
26737 INFO: Processing pre-safe import module hook gi.repository.xlib from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.xlib.py'.
26737 INFO: Processing pre-safe import module hook gi.repository.Atk from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/pre_safe_import_module/hook-gi.repository.Atk.py'.
26738 INFO: Loading module hook 'hook-gi.repository.Pango.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
26813 INFO: Loading module hook 'hook-gi.repository.cairo.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
26882 INFO: Loading module hook 'hook-gi.repository.xlib.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
26949 INFO: Loading module hook 'hook-gi.repository.Atk.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
27023 INFO: Loading module hook 'hook-gi.repository.GModule.py' from '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks'...
27191 INFO: Looking for ctypes DLLs
27248 WARNING: Library user32 required via ctypes not found
27284 INFO: Analyzing run-time hooks ...
27298 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_subprocess.py'
27299 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
27300 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
27302 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
27303 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
27305 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_pyqt5.py'
27306 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gdkpixbuf.py'
27306 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gtk.py'
27307 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_glib.py'
27307 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gio.py'
27307 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_gi.py'
27308 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/_pyinstaller_hooks_contrib/hooks/rthooks/pyi_rth_traitlets.py'
27309 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth__tkinter.py'
27309 INFO: Including run-time hook '/home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/hooks/rthooks/pyi_rth_mplconfig.py'
27327 INFO: Looking for dynamic libraries
27507 WARNING: Cannot find libQt5EglFSDeviceIntegration.so.5 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so)
27508 WARNING: Cannot find libQt5EglFsKmsSupport.so.5 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/egldeviceintegrations/libqeglfs-kms-egldevice-integration.so)
27769 WARNING: Cannot find libQt5EglFSDeviceIntegration.so.5 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqeglfs.so)
27836 WARNING: Cannot find libxcb-xinerama.so.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-egl-integration.so)
27836 WARNING: Cannot find libxcb-xinerama.so.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-egl-integration.so)
28073 WARNING: Cannot find libxcb-xinerama.so.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so)
28073 WARNING: Cannot find libxcb-xinerama.so.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platforms/libqxcb.so)
28110 WARNING: Cannot find libQt5EglFSDeviceIntegration.so.5 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/egldeviceintegrations/libqeglfs-emu-integration.so)
28214 WARNING: Cannot find libQt5EglFSDeviceIntegration.so.5 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/egldeviceintegrations/libqeglfs-x11-integration.so)
28502 WARNING: Cannot find libxcb-xinerama.so.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so)
28502 WARNING: Cannot find libxcb-xinerama.so.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/libqxcb-glx-integration.so)
30840 WARNING: Cannot find libicudata.so.56 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platformthemes/../../lib/libicuuc.so.56)
30854 WARNING: Cannot find libicuuc.so.56 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platformthemes/../../lib/libicui18n.so.56)
30854 WARNING: Cannot find libicudata.so.56 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/platformthemes/../../lib/libicui18n.so.56)
31631 WARNING: Cannot find libxcb-xinerama.so.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyQt5/Qt5/plugins/xcbglintegrations/../../lib/libQt5XcbQpa.so.5)
32130 WARNING: Cannot find libgfortran-040039e1.so.5.0.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/scipy/special/../../scipy.libs/libopenblasp-r0-8b9e111f.3.17.so)
32144 WARNING: Cannot find libquadmath-96973f99.so.0.0.0 (needed by /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/scipy/special/../../scipy.libs/libgfortran-040039e1.so.5.0.0)
34917 INFO: Looking for eggs
34917 INFO: Python library not in binary dependencies. Doing additional searching...
34941 INFO: Using Python library /lib/x86_64-linux-gnu/libpython3.8.so.1.0
34963 INFO: Warnings written to /home/local/ZOHOCORP/sree-11756/bms/learnopencv/ImageMetrics/Python/libsvm/python/build/main/warn-main.txt
35043 INFO: Graph cross-reference written to /home/local/ZOHOCORP/sree-11756/bms/learnopencv/ImageMetrics/Python/libsvm/python/build/main/xref-main.html
35403 INFO: checking PYZ
35403 INFO: Building PYZ because PYZ-00.toc is non existent
35403 INFO: Building PYZ (ZlibArchive) /home/local/ZOHOCORP/sree-11756/bms/learnopencv/ImageMetrics/Python/libsvm/python/build/main/PYZ-00.pyz
36649 INFO: Building PYZ (ZlibArchive) /home/local/ZOHOCORP/sree-11756/bms/learnopencv/ImageMetrics/Python/libsvm/python/build/main/PYZ-00.pyz completed successfully.
36696 INFO: checking PKG
36697 INFO: Building PKG because PKG-00.toc is non existent
36697 INFO: Building PKG (CArchive) main.pkg
111420 INFO: Building PKG (CArchive) main.pkg completed successfully.
111762 INFO: Bootloader /home/local/ZOHOCORP/sree-11756/.local/lib/python3.8/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
111762 INFO: checking EXE
111762 INFO: Building EXE because EXE-00.toc is non existent
111762 INFO: Building EXE from EXE-00.toc
111762 INFO: Copying bootloader EXE to /home/local/ZOHOCORP/sree-11756/bms/learnopencv/ImageMetrics/Python/libsvm/python/dist/main
111762 INFO: Appending PKG archive to custom ELF section in EXE
112040 INFO: Building EXE from EXE-00.toc completed successfully.

This is the stracktrace what we are getting while building it to script.

Please use the ImageMetrics of opencv library and try to place it under Python/libsvm/python which reproduces the issue.

Waiting for the reply it helps us a lot.

**Comment by bwoodsend** [comment]
This can either be:

* You need to add `--hidden-import=svm` to your build command
* `svm` isn't installed in the correct (virtual) environment
* This `svm` library is placed somewhere weird (not in `sys.path` where PyInstaller can't see it so it can't collect it) then added to `sys.path` on the fly at runtime.

You haven't actually given us any of the information we ask for so I have no way of knowing which.
