### ISSUE TITLE
Issues with font rendering

### ISSUE THREAD

**Issue by forctis** [pyinstaller/pyinstaller#6729]
Hi there

Been trying to compile a python script with pyinstaller, it works well but fonts are rendered in the tiniest of sizes despite the fact that I specify a size 16 or 18, or even 12. Nothing happens and neither the font face changes (it defaults to what "seems" is Arial or some other sans-serif, but can't for sure say as the size is tiny).

What I'm trying to do is to load the fonts. Unfortunately I'm using tkinter so needed an additional library, tkextrafont. What I do is simply to load them and then define them

_fontpath_1 = os.path.join(script_dir,"assets"),"DejaVuSansMono.ttf")
DejaVu = Font(file=str(fontpath_1),family="DejaVu Sans Mono", size="16")_

using them as needed. It works perfectly when running the script, but in the pyinstaller compiled version it does not. In my spec file I add

_datas = [('c://Vision//VP3//tkextrafont//','tkextrafont'), ('c://Vision//VP3//assets//','assets') ]_

to be sure both the library and the fonts are picked. When looking at the _MEIPASS temp directory the fonts are indeed there, the tkextrafont also, the directory is accessible (exe launches and without any issues) but the fonts are rendered in size 6 or something. There is nothing I have tried that works.

Any ideas?

TIA

**Comment by rokm** [comment]
Can you provide a complete minimal example that exhibits the issue?

The `tkextrafont`'s [own example](https://github.com/TkinterEP/python-tkextrafont/blob/master/example/example.py) seems to work as expected (once the font name is corrected from "Roboto" to "Roboto Medium"; and using `--add-data tkextrafont` to collect the .tcl files and the .dll file from the `tkextrafont` package)...

**Comment by forctis** [comment]
Thanks for the swift reply.

For ease of exposition I worked on tkextrafont example directly.

```python
import tkinter as tk
from tkinter import ttk
from tkextrafont import Font
import sys, os

if hasattr(sys, '_MEIPASS'):
    script_dir = sys._MEIPASS
else:
    script_dir = os.path.dirname(os.path.abspath(__file__))

window = tk.Tk()

font_1 = Font(file="C://Vision//VP3//assets//DejaVuSansMono.ttf")
assert font_1.is_font_available("DejaVu Sans Mono")
assert "DejaVu Sans Mono" in font_1.loaded_fonts()
assert font_1.font_info("DejaVuSansMono.ttf")[0]["copyright"]

font_2 = Font(file="C://Vision//VP3//assets//helvetica.ttf")
assert font_1.is_font_available("Helvetica")
assert "Helvetica" in font_1.loaded_fonts()
assert font_1.font_info("helvetica.ttf")[0]["copyright"]

ttk.Label(window, text="DejaVu Sans Mono 012345", font=("DejaVu Sans Mono", 16)).grid()
ttk.Label(window, text="Helvetica 012345", font=("Helvetica", 11)).grid()
window.mainloop()
```

Now, let me summarize what happened.

1. Program compiled well, using

_python -m PyInstaller --onefile --clean example_script.spec_

2.  Included the path where the fonts were located in the .spec file

```
_a = Analysis(['example.py'],
pathex=[],
binaries=[],
datas = [('c://Vision//tkextrafont//','tkextrafont'),('c://Vision//VP3//assets//','assets')],
hiddenimports=[],
hookspath=[],
hooksconfig={},
runtime_hooks=[],
excludes=[],
win_no_prefer_redirects=False,
win_private_assemblies=False,
cipher=block_cipher,
noarchive=False)_
```

4. Executes but throws an exception error

__tkinter.TclError: error 0 - cannot load font "C:/Vision/dist/DejaVuSansMono.ttf"_

5.  Hence fonts were NOT picked by the EXE until I included them by hand in the DIST folder (?) and then it worked.

Very weird.

**Comment by rokm** [comment]
> ```python
> assert font_1.font_info("DejaVuSansMono.ttf")[0]["copyright"]
> ```

This should be `assert font_1.font_info(font_1_path)[0]["copyright"]`. Otherwise, it's looking for TTF file in the current working directory (and dies with an error in step 3). Same with the other one.

**Comment by forctis** [comment]
Let me try and revert

**Comment by rokm** [comment]
You can also skip the last assert altogether, since what we'll probably be looking at are visual results.

**Comment by forctis** [comment]
I thought about that, but wanted to replicate the example 1:1

**Comment by forctis** [comment]
OK works now, let me try to replicate in my own code not with a Label but an Entry and a Menu.

**Comment by forctis** [comment]
OK, found what happening and it seems the pointer to the temp directory referenced by _MEISPASS is not picked and all drops to the root C:\ directory. Dunno why it's happening.

**Comment by forctis** [comment]
Right, did some tests on the main routine I'm working with.

1. Picks the temp directory as referenced by _MEIPASS correctly and the font files are there.
2. I pass the directory through variable fp_1 (pointing at where the TTF files are) and e.g. call for the DejaVu typeface

DejaVu = Font(file=str(fp_1))
assert DejaVu.is_font_available("DejaVu Sans Mono")
assert "DejaVu Sans Mono" in DejaVu.loaded_fonts()

3. No good.
4. Wonder if there is any other import messing things around, but checked the path it points at and it's correct, everything else as in the above example, and yet it does not pick the font size. OTHERWISE the program runs without a flaw.

Any ideas? Will carry out testing but if you have any suggestions, most welcome.

**Comment by forctis** [comment]
Hi guys

On further testing... looked at all possible combos, still no good.

- The application runs without a glitch with font rendering (using tkextrafonts) from console/IDE interface.
- The _MEIPASS path is correctly picked up and referenced
- The loading procedure as in the example above
- It might be an issue with tk.Canvas (or rather: with a window widget created inside a Canvas).
- Here is how both versions look. 

a) Running the script the usual way
![2022-04-08_16h47_01](https://user-images.githubusercontent.com/36732461/162463361-22ed3578-d756-4377-882e-2858813f70f3.png)

b) Running the compiled EXE
![2022-04-08_16h45_00](https://user-images.githubusercontent.com/36732461/162463880-518862e1-8eae-4d19-ae5d-42cd79defedc.png)

(BTW you see it doesn't even pick the font type)

Any ideas?

**Comment by rokm** [comment]
Do you have a minimal example that reproduces the issue now?

**Comment by forctis** [comment]
Will try to make a cut out example from the big python script.

**Comment by forctis** [comment]
This should give you a flavor of where the fonts are called

from PIL import Image, ImageTk
import tkinter as tk
import tkinter.filedialog
import tkinter.messagebox
from tkinter import StringVar
from tkinter import Label
from tkextrafont import Font
import time, datetime
import cv2
import sys, os, fnmatch, os.path, keyboard, screeninfo
import inspect
import numpy as np
import glob
import re
import pims
import base64
import sys

if hasattr(sys,'_MEIPASS'):
    script_dir = sys._MEIPASS
else:
    script_dir = os.path.dirname(os.path.abspath(__file__))

homeDir  = os.path.expanduser("~")
storeDir = os.path.join(os.path.join(homeDir,".testdir"),"XYZ")

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# Create welcome(splash) screen
# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>

welcomeScreen = tk.Tk()
w = 1280
h = 720

# Grab screen width and height
# ----------------------------
monitor = screeninfo.get_monitors()
ws = monitor[0].width
hs = monitor[0].height

# Calculate x and y coordinates
# for the Tk root window
# -----------------------------
global xP, yP
xP = (ws/2) - (w/2)
yP = (hs/2) - (h/2)

# Set the dimensions of the screen
# and where it is placed
# --------------------------------
welcomeScreen.geometry('%dx%d+%d+%d' % (w, h, int(xP), int(yP)))
welcomeScreen.overrideredirect(True)
welcomeScreen.resizable(False, False)

# Pick image
# ----------
draw = np.random.randint(1,3)
if draw == int(1):
    imagenW = Image.open(os.path.join(script_dir, "app1920_1.png"))
elif draw == int(2):
    imagenW = Image.open(os.path.join(script_dir, "app1920_2.png"))
elif draw == int(3):
    imagenW = Image.open(os.path.join(script_dir, "app1920_3.png"))

imagenParaMostrar = imagenW.resize((w,h), Image.ANTIALIAS)
imagenParaMostrar = ImageTk.PhotoImage(imagenParaMostrar)

# Show on canvas
# --------------
wScreenCanvas = tk.Canvas(welcomeScreen, height=h, width=w, bd=0, highlightthickness=0)
wScreenCanvas.grid(row=0, sticky=tk.W + tk.E + tk.N + tk.S)
wScreenCanvas.pack(fill=tk.BOTH, expand=1)
wScreenCanvas.create_image(0, 0, image=imagenParaMostrar, anchor=tk.NW, tags="VID")

# >>>>>>>>>>>>
# Main program
# >>>>>>>>>>>>

def mainProgram():

    welcomeScreen.destroy()
    root = tk.Tk()

    # Set the dimensions of the screen
    # and where it is placed
    # --------------------------------
    root.geometry('%dx%d+%d+%d' % (w, h, int(xP), int(yP)))
    root.resizable(False, False)
    root.overrideredirect(False)
    root.attributes('-fullscreen',False)
    root.iconbitmap(os.path.join(script_dir,"project1.ico"))
    root.title("Test")

    # Define fonts
    # ------------
    fp_1 = os.path.join(script_dir,"DejaVuSansMono.ttf")
    fp_2 = os.path.join(script_dir,"helvetica.ttf")
    DejaVu = Font(file=str(fp_1))
    assert DejaVu.is_font_available("DejaVu Sans Mono")
    assert "DejaVu Sans Mono" in DejaVu.loaded_fonts()
    Helvetica = Font(file=str(fp_2))
    assert Helvetica.is_font_available("Helvetica")
    assert "Helvetica" in Helvetica.loaded_fonts()

    class VideoPlayer(tk.Frame):
        def __init__(self, master, videoSize=(1280,720)):
            super().__init__(master=master)
            self.columnconfigure(0, weight=1)
            self.rowconfigure(0, weight=1)
            self.cap = None
            self.currentImage = None
            self.videoSize = videoSize
            self.isPlaying = False
            self.isVideo = False
            self.totalFrames = 0
            self.frameCount = 0
            self.fps = 1
            self.frameInterval = 10
            self.rate = 1
            self.numTimes = 1
            self.launch = 0
            self.triggerPlay = True

            self.display = tk.Canvas(self, height=720, width=1280, bd=0, highlightthickness=0)
            self.display.grid(row=0, sticky=tk.W + tk.E + tk.N + tk.S)
            self.pack(fill=tk.BOTH, expand=1)

            # ---------------------------------------------------------------------------------------------

            def boton_disparo_1():
                fileOpen(self)

            def limitEntry(entrada, vS):
                valor_entrada = entrada.get()
                if len(valor_entrada) > vS:
                    entrada.set(valor_entrada[:vS])

            # ------------------------------------------------------- << Start here check NCF file

            # Check if NCF file is there
            # --------------------------
            path_1  = os.path.join(storeDir,'*.ncf')
            NCFfile = glob.glob(path_1, recursive=True)

            if len(NCFfile) == 0:
                self.imagen = Image.open(os.path.join(script_dir,"Validation.png"))
                self.imagenResized = self.imagen.resize(self.videoSize, Image.ANTIALIAS)
                self.imagenResized = ImageTk.PhotoImage(self.imagenResized)
                self.display.delete("VID")
                self.display.create_image(0, 0, image=self.imagenResized, anchor=tk.NW, tags="VID")
                self.focus_force()
                self.lift()
                self.update()
                ee1 = StringVar()
                self.uEntry_1  = tk.Entry(self, font=("DejaVu Sans Mono", 16), width=10, fg="#000000", bg="#fafafa", bd=0, textvariable=ee1)
                ee1.trace("w", lambda name, index, mode, sv=ee1: limitEntry(ee1,10))
                self.display.create_window(95, 460, anchor="nw", window=self.uEntry_1)
                imagenBoton = Image.open(os.path.join(script_dir,"valBoton.png"))
                imagenBoton = imagenBoton.resize((230,67), Image.ANTIALIAS)
                self.imagenBotonVisible = ImageTk.PhotoImage(imagenBoton)
                self.boton = tk.Button(self, image=self.imagenBotonVisible, command = boton_disparo_1)
                self.boton.configure(bg="#fafafa",bd=0)
                self.boton.place(x = self.videoSize[0] - 560, y = self.videoSize[1] - 260)

            # ------------------------------------------------------- << End here check NCF file

            self.bind("<Configure>", self.resize)
            self.frameLoop()
            self.update()

# ---------------------------------------------------------------------------------------------------

        def resize(self, event):
            self.videoSize = (event.width, event.height)
            if not self.isPlaying:
                self.startupResized = self.imagen.resize(self.videoSize, Image.ANTIALIAS)
                self.startupResized = ImageTk.PhotoImage(self.startupResized)
                self.display.delete("VID")
                self.display.create_image(0, 0, image=self.startupResized, anchor=tk.NW, tags="VID")

        # Popup menu
        # ----------
        def popup(self):
            self.display.popMenu = tk.Menu(self, tearoff = 0)
            self.display.popMenu.add_command(label = "Play", font=("Helvetica", 11), command = lambda: self.letsStart())
            self.display.popMenu.add_command(label = "Stop", font=("Helvetica", 11), command = lambda: self.letsStop())
            self.display.bind("<Button-3>",self.do_popup)

        def do_popup(self, event):
            try:
                self.display.popMenu.tk_popup(event.x_root, event.y_root, 0)
            finally:
                self.display.popMenu.grab_release()

        def fileOpen(self):
            root.overrideredirect(False)
            root.attributes('-fullscreen',False)
            self.outerLoop = 0
            path_2 = tk.filedialog.askopenfilename(title="Select a file",filetypes=[("Our files", "*.xxx")])
            if path_2:
                if path_2.split(".")[-1].lower() in "xxx":
                    self.processFile(path_2)
                else:
                    # Fatal error... exiting
                    # ----------------------
                    exit()

        def processFile(self, path: str):
            self.launch = 1
            root.resizable(True, True)
            self.cap = pims.open(path,as_raw=True)
            self.getDetails()
            self.frameCount = 0
            self.isVideo = True
            self.isPlaying = True
            self.popup()
            
        def getDetails(self):
            self.totalFrames = int(len(self.cap))
            self.fps = int(self.cap.frame_rate)
            self.height = self.cap.height
            self.width = self.cap.width
            if self.totalFrames > 1:
                self.numTimes = 10E8
            else:
                self.numTimes = 1

        def frameLoop(self):
            # -----------------------------------
            # Reset frameCount on loop completion
            # self.outerLoop on start
            # -----------------------------------
            if self.frameCount == self.totalFrames:
                if self.totalFrames > 1:
                    self.outerLoop += 1
                self.frameCount = 0
            # ----
            if self.outerLoop == self.numTimes:
                self.isPlaying = False
            # ----
            if self.isPlaying:
                framearray   = np.asarray(self.cap.get_frame(self.frameCount))
                self.currentImage = framearray.reshape(self.height,self.width,3)
                cv2image    = cv2.resize(self.currentImage, (self.videoSize))
                self.imagen = Image.fromarray(cv2.cvtColor(cv2image, cv2.COLOR_BGR2RGBA))
                self.imgtk  = ImageTk.PhotoImage(self.imagen)
                # ----
                self.display.delete("VID")
                self.display.create_image(0, 0, image=self.imgtk, anchor=tk.NW, tags="VID")
                self.frameCount += 1
                # ----
            # ----
            # Show
            # ----
            self.after(self.rate, self.frameLoop)

        def key(self, event):
            # For checks
            # ----------
            print("pressed", event.keycode)

    # >>>>> End of Class

    app = VideoPlayer(root)

# >>>>>>>> End of Main program

welcomeScreen.after(2000, mainProgram)
welcomeScreen.mainloop()

**Comment by rokm** [comment]
How do I reproduce the problem with the above code (assuming I generate random images with required filenames)? There's one text entry field on the left side, but that seems to have the same (normally large) font in unfrozen and frozen variant...

**Comment by forctis** [comment]
Hi there, have been unable to follow this due to a family issue.

Well, TBH I simply don't know what's going on. I have stripped the code to something uber-simple (just to see what font and size were being picked) and it works, but in my application (as I start adding functions) the font typeface is picked but THE SIZE IS NOT (so now what I have managed to make work is that the typeface is rendered correctly, but the size remains tiny as before).

This code works

```python
from PIL import Image, ImageTk
import tkinter as tk
import tkinter.filedialog
import tkinter.messagebox
from tkinter import StringVar
from tkinter import Label
from tkextrafont import Font
import time, datetime
import cv2
import sys, os, fnmatch, os.path, keyboard, screeninfo
import inspect
import numpy as np
import base64
import sys

if hasattr(sys,'_MEIPASS'):
    script_dir = sys._MEIPASS
else:
    script_dir = os.path.dirname(os.path.abspath(__file__))

homeDir  = os.path.expanduser("~")
storeDir = os.path.join(os.path.join(homeDir,".testdir"),"XYZ")

w = 1280
h = 720

monitor = screeninfo.get_monitors()
ws = monitor[0].width
hs = monitor[0].height

global xP, yP
xP = (ws/2) - (w/2)
yP = (hs/2) - (h/2)

def mainProgram():

    splash.destroy()
    root = tk.Tk()
    root.geometry('%dx%d+%d+%d' % (w, h, int(xP), int(yP)))
    root.overrideredirect(False)
    root.resizable(False, False)
    root.attributes('-fullscreen',False)
    root.title("New window")

    class VideoPlayer(tk.Frame):
        def __init__(self, master, videoSize=(1280,720)):
            super().__init__(master=master)
            self.columnconfigure(0, weight=1)
            self.rowconfigure(0, weight=1)

            self.display = tk.Canvas(self, height=720, width=1280, bd=0, highlightthickness=0)
            self.display.grid(row=0, sticky=tk.W + tk.E + tk.N + tk.S)
            self.pack(fill=tk.BOTH, expand=1)

            def limitEntry(entrada, vS):
                valor_entrada = entrada.get()
                if len(valor_entrada) > vS:
                    entrada.set(valor_entrada[:vS])

            ee1 = StringVar()

            self.uEntry_1  = tk.Entry(self, font=("DejaVu Sans Mono", 18), width=10, fg="#000000", bg="#fafafa", bd=0, textvariable=ee1)
            ee1.trace("w", lambda name, index, mode, sv=ee1: limitEntry(ee1,10))
            self.display.create_window(95, 460, anchor="nw", window=self.uEntry_1)

    app = VideoPlayer(root)
    app.mainloop()

# --------------

splash = tk.Tk()
splash.geometry('%dx%d+%d+%d' % (w, h, int(xP), int(yP)))
splash.overrideredirect(True)
splash.resizable(False, False)

imagenW = Image.open(os.path.join(script_dir, "app1920_1.png"))
imagenParaMostrar = imagenW.resize((w,h), Image.ANTIALIAS)
imagenParaMostrar = ImageTk.PhotoImage(imagenParaMostrar)

wScreenCanvas = tk.Canvas(splash, height=h, width=w, bd=0, highlightthickness=0)
wScreenCanvas.grid(row=0, sticky=tk.W + tk.E + tk.N + tk.S)
wScreenCanvas.pack(fill=tk.BOTH, expand=1)
wScreenCanvas.create_image(0, 0, image=imagenParaMostrar, anchor=tk.NW, tags="VID")

# Define fonts
# ------------
fp_1 = os.path.join(script_dir,"DejaVuSansMono.ttf")
fp_2 = os.path.join(script_dir,"helvetica.ttf")
DejaVu = Font(file=str(fp_1))
assert DejaVu.is_font_available("DejaVu Sans Mono")
assert "DejaVu Sans Mono" in DejaVu.loaded_fonts()
Helvetica = Font(file=str(fp_2))
assert Helvetica.is_font_available("Helvetica")
assert "Helvetica" in Helvetica.loaded_fonts()

splash.after(5000, mainProgram)
splash.mainloop()
```

But there is absolutely no major structural difference between this code and the bigger one. Let me reiterate that all works without a glitch when launching via an IDE but not when compiled (the code above, strangely, works on both instances, despite being structurally similar to the one not working). So honesty at odds here.

**Comment by rokm** [comment]
Hmmm... do you get consistent behavior if you use font size in pixels (i.e., giving the [negative value](https://anzeljg.github.io/rin2/book2/2405/docs/tkinter/fonts.html)) instead of points? If that is the case, there might be a subtle difference between native python and pyinstaller-frozen application in terms of DPI handling...

**Comment by rokm** [comment]
To explore the possibility of this being a DPI-related issue a bit more... 

You said it works fine if you launch it via IDE - does it also work fine if you run it without the IDE being involved (e.g., using python.exe from cmd prompt)?

Does adding a code block like [this](https://github.com/python/cpython/blob/dbd9d75fedfebb215fe3e2b60249ac642cc8abf2/Lib/idlelib/pyshell.py#L14-L22) at the top of your program help?

**Comment by forctis** [comment]
> To explore the possibility of this being a DPI-related issue a bit more...
> 
> You said it works fine if you launch it via IDE - does it also work fine if you run it without the IDE being involved (e.g., using python.exe from cmd prompt)?
> 
> Does adding a code block like [this](https://github.com/python/cpython/blob/dbd9d75fedfebb215fe3e2b60249ac642cc8abf2/Lib/idlelib/pyshell.py#L14-L22) at the top of your program help?

Right, THIS (adding the suggested code block as per the link above) **seems to have worked**. Now, the Q here is whether compiling on MacOS would not be the same chore as before (as this is clearly a win-specific hack). But so far, so good. Wonder if this a pyinstaller-related bug (one of those you fish by chance) or something else not related to pyinstaller.

Thanks a lot for the feedback. It now remains to see if compiling on another OS (targets are windows and MacOS) does not become problematic.

**Comment by rokm** [comment]
> Now, the Q here is whether compiling on MacOS would not be the same chore as before (as this is clearly a win-specific hack)

I imagine compiling on macOS will be a chore regardless of this :) (the block is behind platform-specific check, though, so it should not affect the app on macOS. You might get an additional warning about missing ctype library during the build, though).

> Wonder if this a pyinstaller-related bug (one of those you fish by chance) or something else not related to pyinstaller.

What is the behavior if you run you code from the cmd instead from IDE? I don't see python itself setting DPI awareness anywhere on its own - neither programmatically nor via the manifest, so I would expect it to exhibit the same problem as pyinstaller-frozen application (and if not, we should find out where the difference is coming from). But it might be that the IDE sets up the DPI awareness, and this is inherited by spawned child processes, effectively masking the issue when you run your code through IDE...

**Comment by forctis** [comment]
I will look at a non-IDE run shortly ;-) but you're right that an IDE (I'm using Pyzo 4.12.3) might be masking things up.

Yeah, I'm building up strength for the mac build, but needs to be done (or at least attempted).

Back to you shortly.

**Comment by forctis** [comment]
Right... launching the program from the command prompt also works perfectly now, after adding that bit of code you directed me to. So clearly it's not IDE-related.

**Comment by rokm** [comment]
> Right... launching the program from the command prompt also works perfectly now, after adding that bit of code you directed me to. So clearly it's not IDE-related.

Did launching your python code from command prompt work before you added call to `SetProcessDpiAwareness`, though?

**Comment by forctis** [comment]
Nope, fails. But more interestingly (and puzzling) is that although the fonts (typeface/size) work in the compiled EXE when run in my PC (where the EXE was created) when done in someone else's PC they don't (this with SetProcessDpiAwareness as noted above). So: it now works for me, it doesn't for at least someone else (same OS - Windows 10 Pro - but different PC). Views?

**Comment by rokm** [comment]
Does the minimal sample from `tkextrafont` (from the beginning of this conversation) work on that other PC?

EDIT: also, which part is failing there - typeface or only size?

**Comment by forctis** [comment]
I will check (have 5 hour difference between them and me so will know in a few hours).

**Comment by forctis** [comment]
Wonder about this... note the comment on whether SetProcessDpiAwareness(1) works on ALL monitors...

https://bugs.python.org/msg319132

**Comment by forctis** [comment]
Update: the minimal example works (on both computers) and that's about it. Now the amended code works on the production computer but not on the slave. Changed the code snipped suggested above for this

```python
if sys.platform == 'win32':
    import ctypes
    winVer = platform.win32_ver(release='')[0]
    try:
        if int(winVer) >= 10:
            ctypes.windll.shcore.SetProcessDpiAwareness(2)
        elif int(winVer) == 8:
            ctypes.windll.shcore.SetProcessDpiAwareness(1)
        else:
            ctypes.windll.user32.SetProcessDPIAware()
    except (ImportError, AttributeError, OSError):
        pass
```

To no avail (in the sense that it did not change behavior on the slave PC). Wonder what's going on as both PCs run the same OS (Windows 10) and the fonts render now correctly works in one, but not on the other.

**Comment by rokm** [comment]
The "slave" is your build machine? Are both machines equivalent in terms of DPI they use (their monitors' pyhsical size, resolution, and consequently DPI)? Perhaps you can query the DPI used by the system using whatever relevant Windows API (even to just see if it differs between the two machines)?

At any rate, I doubt this has anything to do with pyinstaller...

**Comment by forctis** [comment]
Slave is the secondary machine. I will check on the other PC used as it is 10k KM away ;-) and will try test on a third PC. Doubt the DPI resolution matters and in any case SetProcessDpiAwareness(2) should make it monitor-aware rather than purely system-aware.

**Comment by forctis** [comment]
An update: should have thought about this, but seeing that nothing is happening captured the value thrown by ctypes.windll.shcore.SetProcessDpiAwareness(2) which is -2147024891 or equivalently 0x80070005 = E_ACCESSDENIED meaning DPI awareness has NOT been set (!)

This is quite odd, as the call is at the VERY TOP of the code (meaning another process has captured it, as DPI awareness cannot be set more than once) but may explain what's going on in the slave machine, although does not provide an answer as to why it works in the build PC.

Let me try a new hack.

**Comment by forctis** [comment]
Well...

https://bugs.python.org/msg245058

Which somehow suggests the behavior I'm seeing: OK on console or via IDE (although the IDE sets DPI awareness by itself, hence the E_ACCESSDENIED noted above, but somehow it sorts out) but with issues on the compiled EXE. Or that's my guess.

**Comment by rokm** [comment]
Are you getting the `E_ACCESSDENIED` when trying to set DPI awareness in the compiled exe? If so, you could try hacking our manifest generation to insert those DPI awareness settings into it (similarly to how it is done for long-path opt-in, [here](https://github.com/pyinstaller/pyinstaller/blob/6811c873b8cf8a09a7ad7db1449626a72a64df05/PyInstaller/utils/win32/winmanifest.py#L857-L867)).

**Comment by forctis** [comment]
Before even starting and die trying, presume you have seen this

https://stackoverflow.com/questions/67779317/how-to-avoid-windows-10-autoscaling-with-high-dpi

**Comment by rokm** [comment]
Yes, that's what I had in mind. 

For a quick test, you could also create a onedir build with `--no-embed-manifest` and then edit the generated external manifest - however, you'd need to be careful because Windows seem to cache the manifests, so once the executable is ran, if you make any changes to the manifest, you need to rename both the executable and the manifest for the changes to take effect. That's why editing the manifest generation code might be a safer way (or, you could extract the embedded manifest using `mt.exe`, make the changes, and then embed it again...).

**Comment by forctis** [comment]
Well, made an attempt using this

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly manifestVersion="1.0" xmlns="urn:schemas-microsoft-com:asm.v1" xmlns:asmv3="urn:schemas-microsoft-com:asm.v3">
    <assemblyIdentity type="win32" name="MyApplication" version="1.0.0.0" processorArchitecture="amd64"/>

    <asmv3:application>
        <asmv3:windowsSettings>
            <dpiAware xmlns="http://schemas.microsoft.com/SMI/2005/WindowsSettings">true/pm</dpiAware>
            <dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2,PerMonitor</dpiAwareness>
            <gdiScaling xmlns="http://schemas.microsoft.com/SMI/2017/WindowsSettings">true</gdiScaling>
        </asmv3:windowsSettings>
    </asmv3:application>
</assembly>

and then adding it on compilation, but no good either. Your suggestions seem a bit convoluted for something that should be more straightforward, dunno. But have to admit that whatever is happening is becoming quite annoying.

On that quoted post from SO, I pick on what the OP mentioned in the end... "I wonder if is a Pyinstaller issue..."

**Comment by rokm** [comment]
> On that quoted post from SO, I pick on what the OP mentioned in the end... "I wonder if is a Pyinstaller issue..."

Or maybe the manifest in that SO post is invalid, who knows? It has effectively two `application` and two `windowsSettings` nodes in the XML - does MS spec allow that? 

To reduce amount of guessing, you could check if your changes had any effect at all, by querying the DPI awareness setting within the program via [GetProcessDpiAwareness](https://docs.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-getprocessdpiawareness).

**Comment by rokm** [comment]
And FWIW, editing external manifest generated by `--no-embed-manifest` and adding a `<dpiAwareness xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">PerMonitorV2</dpiAwareness>` node to existing `windowsSettings` node changes the return value of `GetProcessDpiAwareness` from 0 to 2, as expected.

**Comment by forctis** [comment]
Well, added awareness = ctypes.c_int() before and after calling SetProcessDpiAwareness and indeed DPI awareness change from 0 to 2, as expected. This happens in my build machine and in the slave machine we've been using for testing. HOWEVER in the slave machine it does nothing to change the font aspect, whereas it works on the build machine. BOTH operate the same OS/build. This is incredibly weird.

**Comment by forctis** [comment]
Back on this...

Decided to try loading the fonts with pyglet instead of tkextrafont. It works on the development machine, actually. Now, what I have seen is some interesting behavior.

a. Development PC (Win 10, Python 3.7 installed) -> Fonts rendered OK, program works OK
b. Alternative PC #1 (Win 7 Pro, no Python installed) -> Fonts with issues (family picked OK, size 10 pt), program works OK
c. Alternative PC #2 (Win 10, Python 3.9 installed) -> Fonts with issues (as above: family OK, size 10 pt), program FAILS

So besides the font issue (only works correctly in the development machine) the behavior between cases (a) and (c) above are a mystery. Case (b) suggests there are not loose Python dependencies, because there is no Python installed in that PC. OTOH the odd behavior between cases (a) and (c) suggest something is being picked-up in the background where the failure suggests something conflicting between the Python 3.7 and 3.9 versions, but alas, on a clean PC (no Python) all works a treat, save the fonts.

Any ideas?

**Comment by rokm** [comment]
I think this issue report is getting all over the place - what is this "program works OK" vs "program FAILS"? I was under impression that font size was the only issue here...

What is the physical monitor size and screen resolution of a), b) and c)? What are the scaling settings used by Windows?

And first and foremost, what is the behavior of your unfrozen code on a) and on c) (and on b), if you can install python there and test), without PyInstaller involved at all? If you run your code via python.exe from cmd, does the font size work as expected or not? Because if not, there's nothing left to discuss here - PyInstaller's bootloader does not set any DPI awareness flags by itself, and neither does python.exe, so I would expect the behavior between the unfrozen code in python interpreter and the frozen application to be consistent (even if it is not what you are aiming for).

**Comment by forctis** [comment]
OK, let me explain myself:

1. Program works OK means exactly that, no issues of bits of code or any of the embedded algorithms that break down.

2. Program FAILURE means that the executable launches but at some stage in its run it fails to behave as expected (algorithm breaks down).

3. In two of the three instances the scaling settings are 200% (need to check on one of the PCs which is remote, that is, not on my desk) and screen resolution 3000 x 2000 in the two PCs loaded with Win 10 OS (cases a and c), and 125% on a 1366 x 768 display in the Win 7 PC (case b).

4. And here is the important bit: NO ISSUES (fonts or otherwise) with the behavior of the *.py file when run from the command line on PC having Python loaded (but will check again on the one I am not handling directly); I will load Python for testing on the Win 7 PC (where things did work save the fonts when running the EXE, as in the development PC) and report.

For avoidance of doubt: I was NOT EXPECTING this additional behavior to the fonts scaling one.

**Comment by forctis** [comment]
Update: **font issue sorted**. The ONLY way to get this working was to load the fonts in tkinter was AS A RESOURCE using pyglet.

For the benefit of other users, rather than resorting to

pyglet.font.add_file('path to your fonts')
pyglet.font.load(name='font family name', size=desired size)

you need (and this was my last port of call before calling it quits...)

pyglet.resource.path=['path to your fonts']  -> Could be as string or as variable
pyglet.resource.reindex()                               -> Do not forget this
pyglet.resource.add_font('font file name')    -> Here note it is the font file name (fontname.ttf) and not the font family name.

Important also to add: if you are using os (as in os.path.dirname) make absolutely sure you change separators to "/" as otherwise pyglet.resource will not work.

The easiest way is to issue replace -> if **fontspath** is your path, do fontspath.replace("\\","/")

This got it sorted. I have read the resource.reindex() step may be slow on some implementations, not on my case if it's the first call to reindexing. If you run it twice (and you shouldn't unless you're using pyglet to load other resources) then it takes its time.

Tkextrafont just didn't work. Plain and simple. Reason similar to pyglet using the font.add_file route: it seems some font metrics are not fully recognized/picked-up when loading a font this way.

Important #2 (not an issue in my coding, but worth mentioning): always place this code AFTER your root window, e.g. root = tk.TK() call.

Will check other issues with self-executable later.
