### ISSUE TITLE
File closing before the script even runs.

### ISSUE THREAD

**Issue by pandadevv5495** [pyinstaller/pyinstaller#6734]
Im trying to make a simple file. I used `pyinstaller hi.py` I click on the exe but it just closes instantly. It does not do anything at all. When I try windowed it says python39.dll could not be found. I dont know what to do.

**Comment by rokm** [comment]
Sounds like you're trying to run executable in the `build` directory, instead of the one in the `dist` directory (where the complete application bundle is generated).
