### ISSUE TITLE
Problems with PyInstaller 2.0 waf call

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#674]
**Original date**: 2013/02/26
**Original reporter**: *hoel AND gl DASH group DOT  COOM *

After my generated exe failed with

...
  File "./pyinstaller-2.0/PyInstaller/loader/iu.py", line 105, in getmod
    mod = imp.load_module(nm, fp, attempt, (ext, mode, typ))
ImportError: /tmp/_MEIIOFY3W/PyQt4.QtCore.so: undefined symbol: PyUnicodeUCS2_GetDefaultEncoding

under linux 64 I thought I might need a self compiled boot-loaders with
my self compiled python. So I entered "pyinstaller-2.0/source" and
called

>python ./waf configure
Linux-64bit detected 
Building LSB bootloader. 
Checking for program gcc or cc           : /usr/bin/gcc 
Checking for program cpp                 : /usr/bin/cpp 
Checking for program ar                  : /usr/bin/ar 
Checking for program ranlib              : /usr/bin/ranlib 
Checking for gcc                         : ok  
Checking for program python              : /usr/local/gltools/python/Python-2.7/linux_x86_64-UBUNTU12.10/bin/python 
Checking for Python version              : 2.7.2 
Checking for library python2.7           : yes 
Checking for program python2.7-config    : /usr/local/gltools/python/Python-2.7/linux_x86_64-UBUNTU12.10/bin/python2.7-config 
Checking for custom code                 : Could not find the python development headers 
/data/tmp/hoel/GLPy/mkexec/pyinstaller-2.0/source/wscript:116: error: the configuration failed (see '/data/tmp/hoel/GLPy/mkexec/pyinstaller-2.0/source/build/config.log')

I then added -v to the command line and got

...
18:47:51 runner system command -> ['/usr/bin/gcc', 'default/test_1.o', '-o', '/data/tmp/hoel/GLPy/mkexec/pyinstaller-2.0/source/build/.conf_check_0/testbuild/default/testprog', '-L/usr/local/gltools/python/Python-2.7/linux_x86_64-UBUNTU12.10/lib', '-Wl,-Bdynamic', '-lm', '-lpthread', '-ldl', '-lutil', '-lpython2.7']

which leads me to the idea that waf is trying to link the libraries in
the wrong order. If I execute the command at the command line, it
becomes clear, that libpython requires libm. Is there any was to solve
this problem?

Kind regards

Berthold Höllmann

**Comment by htgoebel** [comment]
Outdated.
