### ISSUE TITLE
Execution failes when import mpxj

### ISSUE THREAD

**Issue by Cowboyserg** [pyinstaller/pyinstaller#6740]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(4.10)```
* Version of Python: 3.7
* Platform: Windows 10 (x-64)
* How you installed Python: pip install pyinstaller

### A minimal example program which shows the error

```
import mpxj
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "<read_mpp.py>", line 4, im <module>
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocker
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "mpjx\__init__.py", line 10, in <module>
StopIteration
[20704] Failed to execute script ‘read_mpp’ due to unhandled exception!
```

### `exe` was created with command

```
pyinstaller --noconfirm --onefile --console --clean  "C:/Users/User/PycharmProjects/read_mpp.py"
```

**Comment by bwoodsend** [comment]
Judging by [this line where it's failing](https://github.com/joniles/mpxj/blob/a5d351cabbf616321764bf9bf8f382e4d6661e0c/src.python/mpxj/mpxj/__init__.py#L9-L10), it looks like `mpxj` contains some jar files which need collecting. Adding `--collect-datas=mpxj` to your build command should do the job?

**Comment by Cowboyserg** [comment]
Another problem occurred
when run 
```
pyinstaller --noconfirm --onefile --console --clean --collect-datas=mpxj "C:/Users/User/PycharmProjects/read_mpp.py"
```
read_mpp.py:
```
import jpype
import mpxj
jpype.startJVM()
```


have this
```
Traceback (most recent call last):
  File "<read_mpp.py>", line 3, im <module>
  File "jpype\_core.py", line 227, in startJVM
SystemError: java.lang.ClassNotFoundException: org.jpype.classloader.DynamicClassLoader
[20704] Failed to execute script ‘read_mpp’ due to unhandled exception!
```

**Comment by bwoodsend** [comment]
I see [jpype already has a hook for PyInstaller](https://github.com/jpype-project/jpype/blob/8e90e5aaa4e87faae3bf8b825768986c4b089e41/jpype/_pyinstaller/hook-jpype.py) so it's supposed work out the box. You're probably better raising this with them.

**Comment by rokm** [comment]
This snippet:

```python
# program.py
import jpype
import mpxj
jpype.startJVM()
```

works for me in both onedir and onefile mode:
* `pyinstaller --noconfirm  --console --clean --collect-data mpxj program.py`
* `pyinstaller --noconfirm  --console --clean --collect-data mpxj --onefile  program.py`

Try building in onedir mode (or inspect the embedded archive of your onefile executable) and check if `org.jpype.jar` is collected into application bundle's top directory.

**Comment by Cowboyserg** [comment]
> This snippet:
> 
> ```python
> # program.py
> import jpype
> import mpxj
> jpype.startJVM()
> ```
> 
> works for me in both onedir and onefile mode:
> 
> * `pyinstaller --noconfirm  --console --clean --collect-data mpxj program.py`
> * `pyinstaller --noconfirm  --console --clean --collect-data mpxj --onefile  program.py`
> 
> Try building in onedir mode (or inspect the embedded archive of your onefile executable) and check if `org.jpype.jar` is collected into application bundle's top directory.

Thank you very much @rokm, @bwoodsend . This command helped me
```
pyinstaller --noconfirm --onefile --console --clean --add-data "C:/Users/User/PycharmProjects/org.jpype.jar;." --collect-data "mpxj"  "C:/Users/User/PycharmProjects/read_mpp.py"
```
How did you realise, that I should not write `--collect-data "jpype1"`, but point out exactly `org.jpype.jar` file?

**Comment by rokm** [comment]
It looks like that `org.jpype` is installed directly into `site-packages` instead of a package sub-directory - that's why `--collect-data jpype` does not work here. 

And [jpype's own PyInstaller hook](https://github.com/jpype-project/jpype/blob/8e90e5aaa4e87faae3bf8b825768986c4b089e41/jpype/_pyinstaller/hook-jpype.py) should collect that file for you (unless that hook is not visible to PyInstaller for some reason...)

**Comment by Thrameos** [comment]
The pyinstaller hooks was contributed user code to jpype.   If there is something wrong with the pattern, please consider submitting a patch with improvements.

**Comment by rokm** [comment]
> The pyinstaller hooks was contributed user code to jpype. If there is something wrong with the pattern, please consider submitting a patch with improvements.

I think the hook is fine and it seems to works as expected - at least it did for me. 

No idea why it didn't seem to fire in the case of this issue report, though... (judging by the jar location, it might be PyCharm-related)
