### ISSUE TITLE
Not finding geos_c.dll for shapely windows 

### ISSUE THREAD

**Issue by dmatos2012** [pyinstaller/pyinstaller#6745]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.10```
* Version of Python: ```3.8.2```
* Platform: ```Linux (Ubuntu 20.04)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

### A minimal example program which shows the error
test.py
```python
import shapely # shapely version 1.8.1.post1
```
Run command
```
pyinstaller test.py
```

### Stacktrace / full error message

```
4164 INFO: Loading module hook 'hook-shapely.py' from 'c:\\users\\david\\documents\\venvs\\gui_app\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
Error: geos_c.dll not found, required by hook-shapely.py.
Please check your installation or provide a pull request to PyInstaller to update hook-shapely.py.
```

Somehow, I think shapely changed where everything is installed, if I change the `hook-shapely.py` for the following
```
pkg_base, pkg_dir = get_package_paths('shapely')
standard_path = os.path.join(pkg_dir, 'DLLs') # doesnt find geos_c
```
If I change standard_path in `hooks-shapely.py` to 
```
 standard_path = os.path.join(pkg_base, 'Shapely.libs')  
dll_path = find_library('geos_c-615c861f') # from 'geos_c'
```
Then hook-shapely executes correctly. I could do a PR, but this seems more like a hack, and not a proper way to find the `Shapely.libs` etc. Please let me know if need anything else.

**Comment by rokm** [comment]
> * Platform: ```Linux (Ubuntu 20.04)

does not match

> `4164 INFO: Loading module hook 'hook-shapely.py' from 'c:\\users\\david\\documents\\venvs\\gui_app\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...`

I assume you're on Windows, since you mention the `standard_path = os.path.join(pkg_dir, 'DLLs')` that is part of the Windows codepath.

----

But either way, what version of `pyinstaller-hooks-contrib` are you using? I think the latest version (`v2022.3`), which includes pyinstaller/pyinstaller-hooks-contrib#394, should already fix this.

**Comment by dmatos2012** [comment]
Yeah, lol , sorry that was a mistake, it was clearly on Windows.

Updating the `pyinstaller-hooks-contrib` fixed the issue. Thank you so much for the help @rokm
