### ISSUE TITLE
Domain http://www.pyinstaller.org/ is down .

### ISSUE THREAD

**Issue by aadrian** [pyinstaller/pyinstaller#6750]
The domain http://www.pyinstaller.org/ that is referenced everywhere seems to be down.

**Comment by bwoodsend** [comment]
It's really http://pyinstaller.org/ now. Don't worry, it's being fixed in #6749.

**Comment by Legorooj** [comment]
I'll add a redirect for www.

**Comment by Legorooj** [comment]
Redirect added, it should go live within the next few hours - as soon as DNS updates.

**Comment by aadrian** [comment]
> Redirect added ..

@Legorooj  
This is great, thank you! 

All existing links seem to work now.
