### ISSUE TITLE
Pyinstaller 5.0: No module named 'matplotlib.backends.backend_svg'

### ISSUE THREAD

**Issue by pllim** [pyinstaller/pyinstaller#6760]
Our cron job successfully ran with Pyinstaller 4.10: https://github.com/astropy/astropy/runs/6051473069?check_suite_focus=true

But fails with Pyinstaller 5.0: https://github.com/astropy/astropy/runs/6058169005?check_suite_focus=true

```
>           plt.savefig(buff, format='svg')

astropy_tests/visualization/tests/test_units.py:35: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
matplotlib/pyplot.py:958: in savefig
    ???
matplotlib/figure.py:3019: in savefig
    ???
matplotlib/backend_bases.py:2259: in print_figure
    ???
matplotlib/backend_bases.py:2184: in _get_output_canvas
    ???
matplotlib/backend_bases.py:144: in get_registered_canvas_class
    ???
importlib/__init__.py:127: in import_module
    ???
<frozen importlib._bootstrap>:1014: in _gcd_import
    ???
<frozen importlib._bootstrap>:991: in _find_and_load
    ???
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

name = 'matplotlib.backends.backend_svg'
import_ = <function _gcd_import at 0x7f6c8af6c430>

>   ???
E   ModuleNotFoundError: No module named 'matplotlib.backends.backend_svg'

<frozen importlib._bootstrap>:973: ModuleNotFoundError
```

I have not noticed any code changes on `astropy` side that would have caused this failure between the 2 runs, but Pyinstaller version definitely changed between them. Not sure if the fix is on your end or ours. Any advice is greatly appreciated. Thanks!

**Comment by bwoodsend** [comment]
The matplotlib hook no longer collects every backend it can get its hands on (see the last entry under [v5.0 breaking changes](https://pyinstaller.org/en/v5.0/CHANGES.html#incompatible-changes)). You're now encouraged to [pick your backend(s)](https://pyinstaller.org/en/v5.0/hooks-config.html#matplotlib-hook-options).

**Comment by bwoodsend** [comment]
Just out of curiosity, are you using one of the matplotlib GUI backends too or exclusively offscreen rendering?

**Comment by pllim** [comment]
I think just offscreen but maybe @astrofrog or @Cadair can confirm.

**Comment by pllim** [comment]
Thanks for the quick reply, @bwoodsend . Alas, I am not a pyinstaller user myself, so I am not sure how to translate instructions at https://pyinstaller.org/en/v5.0/hooks-config.html#matplotlib-hook-options to what we have in https://github.com/astropy/astropy/tree/main/.pyinstaller . Any hints? Thanks!

**Comment by bwoodsend** [comment]
It's a spec file only option and what astropy has is determinedly dodging using a spec file. You can cheat and add
```python
import matplotlib
matplotlib.use("svg")
```
somewhere in [run_astropy_tests.py](https://github.com/astropy/astropy/blob/main/.pyinstaller/run_astropy_tests.py) and PyInstaller will spot it and bundle it accordingly. Whether your users would have to do that too rather depends on what exactly matplotlib is being used for.

**Comment by pllim** [comment]
> what astropy has is determinedly dodging using a spec file

😅

Thanks for the tips! I will try `use()`.
