### ISSUE TITLE
pyinstaller 5.0 fails when using --onefile with a .spec file

### ISSUE THREAD

**Issue by LucaPaganin** [pyinstaller/pyinstaller#6762]
## Description of the issue

pyinstaller --onefile fails when using a .spec file

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0```
* Version of Python: 3.10.4
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No I only tried in Windows

### A minimal example program which shows the error
The command giving me the error is simply this one
```
pyinstaller -F main.spec
```
where the content of main.spec file is the following
```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None

options = [('u', None, 'OPTION')]

a = Analysis(['main.py'],
             pathex=['..\\'],
             binaries=[],
             datas=[
                ('..\\..\\.venv\\Lib\\site-packages\\rulexpy', 'rulexpy'),
                ('..\\mqttbroker\\app\\mosquitto', 'mqttbroker\\app\\mosquitto')
                ],
             hiddenimports=[
                'api.app.main',
                'control.app.main',
                'mqttbroker.app.main',
                'resourcemanager.app.main',
                'session.app.main',
                'compute.app.main',
                'notify.app.main',
                'bridge.app.main'
                ],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data, 
          cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          options,
          a.binaries,
          a.zipfiles,
          a.datas,
          [],
          name='main',
          debug=False,
          bootloader_ignore_signals=False,
          strip=False,
          upx=True,
          upx_exclude=[],
          runtime_tmpdir=None,
          console=True )
```

### Stacktrace / full error message

```
67 INFO: PyInstaller: 5.0
67 INFO: Python: 3.10.4
88 INFO: Platform: Windows-10-10.0.19044-SP0
option(s) not allowed:
  --onedir/--onefile
makespec options not valid when a .spec file is given
```

I would like to stress that until pyinstaller version 4.10 it was working fine without this error. Is this error due to a breaking change due to a choice you made in releasing version 5.0?

**Comment by bwoodsend** [comment]
Quoting the [breaking changes release notes for v5](https://pyinstaller.org/en/v5.0/CHANGES.html#incompatible-changes):

> Issue an error report if a .spec file will not be generated, but command-line options specific to that functionality are given.

**Comment by LucaPaganin** [comment]
So if I run simply

```
pyinstaller main.spec
```

it should give me the same result I was obtaining before when I was providing the `--onefile` option?

**Comment by bwoodsend** [comment]
Yep. That `--onefile` never did anything for spec files.

**Comment by LucaPaganin** [comment]
Thanks for the quick response!
