### ISSUE TITLE
Shapely >= v1.8

### ISSUE THREAD

**Issue by sdransfeld** [pyinstaller/pyinstaller#6772]
shapely has moved it's libraries to another folder. site-packages\Shapely.libs on windows, maybe something else on other platforms. Need to change hooks-shapely.py

Something like:
    if is_module_satisfies('shapely >= 1.8'):
        dll_path = os.path.join(pkg_base, 'Shapely.libs')
        binaries += [(dll_path, '.')]

fixed it for me, but maybe a more robust solution can be found.

**Comment by rokm** [comment]
This should be fixed by https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/394, which is available in `pyinstaller-hooks-contrib`>= `v2022.3`.
