### ISSUE TITLE
PyInstaller with SAP PyRFC package

### ISSUE THREAD

**Issue by the-master-student** [pyinstaller/pyinstaller#6773]
## Description of the issue
Hi everyone,
I am currently trying to use PyInstaller to create a bundle on windows. I have successfully achieved bundling the app on linux and it works perfectly fine. However, whenever I try to bundle the app on windows it fails with an "ImportError: DLL load failed while importing pyrfc: The specified module could not be found." As you can see from the error I import the library pyrfc which is based on some other libraries that I included with --add-binary option. This works perfectly fine on Linux. That's why I am very confused why I get this error on windows. I found article that explained that the Windows SDK needs to be installed and all the libraries should be copied when creating the bundle. Did this however nothing changed.  Another thread discussed that Visual Studio Redistributables needs to be installed. Also did this and still the error is shown that the DLL load failed. 

My code imports for example PyQt5 and it works if I do not import the pyrfc package. However, when the pyrfc package is imported it fails. I cannot figure out what could possibly go wrong. I am creating the bundle the same way I did for Linux and Mac which worked perfectly for them both, but not on windows.

Thank you so much in advance :)

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0```
* Version of Python: Python 3.8.3
* Platform:  Windows 10
* How you installed Python:  python.org/downloads

* try the latest development version, using the following command: DONE

* follow *all* the instructions in our "If Things Go Wrong" Guide:
When using the dependency walker interesting errors are displayed such as that DLLs starting with EXT-MS-WIN-xxx.DLL and API-MS-WIN-xxx.DLL cannot be found by the system. What could this possibly mean?

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ x] start with clean installation
  * [ x] use the latest development version
  * [ x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ x] Package your program in **--onedir mode**
  * [ x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

The output of --debug=imports states that the package was not found. This is the part related to this package. It is located under User/AppData as the other packages successfully installed like PyQt5.

import pyrfc # PyInstaller PYZ
import pyrfc._exception # PyInstaller PYZ
import 'pyrfc._exception' # <pyimod03_importers.FrozenImporter object at 0x000002252B2FAF10>
# pyrfc.pyrfc not found in PYZ
Traceback (most recent call last):
  File "extraction_windows.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "pyrfc\__init__.py", line 30, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 556, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1101, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed while importing pyrfc: The specified module could not be found.
[8596] Failed to execute script 'extraction_windows' due to unhandled exception!

**Comment by rokm** [comment]
Well, I get the same error when trying to use pyrfc without having SAP NWRFC SDK. So either `sapnwrfc.dll` is missing from the bundle, or one of its dependencies is missing from the bundle - check what files are missing using dependency walker. The `EXT-MS-WIN-xxx.DLL` and `API-MS-WIN-xxx.DLL` missing is not an issue, because those are usually shims that resolved at runtime.

The docs mention that Visual Studio 2013 redist is required for NWRFC - I imagine all the corresponding DLLs will also need to be collected into the bundle (or the redist will need to be installed on the target machine), and they might run afoul of PyInstaller's [inclusion/exclusion list](https://github.com/pyinstaller/pyinstaller/blob/6811c873b8cf8a09a7ad7db1449626a72a64df05/PyInstaller/depend/dylib.py#L60-L94) (I know we try to handle 2015/2017/2019/2022 DLLs, but the earlier versions are a gray area).

Either way, as SAP NWRFC SDK is proprietary and not publicly available, and we have no means of checking what's going on, you'll need to figure this out yourself.

**Comment by the-master-student** [comment]
The SAP NWRFC SDK library contains 6 .dll files and .lib files. I added all the files via --add-binary when creating the bundle. I also included the Windows SDK DLLs according to your instruction from the documentation. 

Option 3: Install the [Windows Software Development Kit (SDK) for Windows 10](https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk) and expand the .spec-file to include the required DLLs, see “Distributing Software that uses the Universal CRT“ in the above-mentioned link, number 6. Nothing works. 

If I use the second option with Visual Studio 2019 resist how can I copy these libraries when creating the bundle.

I would so much appreciate some help as I additionally lack windows expertise and am bound to master thesis deadline :/
Thank you so much in advance.

**Comment by rokm** [comment]
What is your full PyInstaller command, then?

**Comment by the-master-student** [comment]
pyinstaller --onefile --add-binary="C:\nwrfcsdk\lib\icudt50.dll;." --add-binary="C:\nwrfcsdk\lib\icuin50.dll;." --add-binary="C:\nwrfcsdk\lib\icuuc50.dll;." --add-binary="C:\nwrfcsdk\lib\libicudecnumber.dll;." --add-binary="C:\nwrfcsdk\lib\libsapucum.dll;."  --add-binary="C:\nwrfcsdk\lib\sapnwrfc.dll;."  --add-binary="C:\nwrfcsdk\lib\libsapucum.lib;." --add-binary="C:\nwrfcsdk\lib\sapnwrfc.lib;." --add-binary="C:\nwrfcsdk\lib\sapnwrfc.pdb;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-console-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-console-l1-2-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-datetime-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-debug-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-errorhandling-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-fibers-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-file-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-file-l1-2-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-file-l2-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-handle-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-heap-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-interlocked-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-libraryloader-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-localization-l1-2-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-memory-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-namedpipe-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-processenvironment-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-processthreads-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-processthreads-l1-1-1.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-profile-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-rtlsupport-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-string-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-synch-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-synch-l1-2-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-sysinfo-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-timezone-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-core-util-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-conio-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-convert-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-environment-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-filesystem-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-heap-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-locale-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-math-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-multibyte-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-private-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-process-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-runtime-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-stdio-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-string-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-time-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\api-ms-win-crt-utility-l1-1-0.dll;." --add-binary="C:\Program Files (x86)\Windows Kits\10\Redist\10.0.22000.0\ucrt\DLLs\x64\ucrtbase.dll;." --debug=imports extraction_windows.py

- PyRFC 2.5.0 ist installer at c:\users\<usename>\appdata\roaming\python\python38\site-packages
- the executable runs without any problem on the machine it was created on


The output when executing on a different machine without Python or the packages:

> import pyrfc # PyInstaller PYZ
> import pyrfc._exception # PyInstaller PYZ
> import 'pyrfc._exception' # <pyimod03_importers.FrozenImporter object at 0x000002296E55AF10>
> pyrfc.pyrfc not found in PYZ
> Traceback (most recent call last):
>   File "extraction_windows.py", line 30, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
>   File "pyrfc\__init__.py", line 30, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 657, in _load_unlocked
>   File "<frozen importlib._bootstrap>", line 556, in module_from_spec
>   File "<frozen importlib._bootstrap_external>", line 1101, in create_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
> ImportError: DLL load failed while importing pyrfc: The specified module could not be found.
> [2488] Failed to execute script 'extraction_windows' due to unhandled exception!

Thank you so much in advance.

**Comment by rokm** [comment]
> the executable runs without any problem on the machine it was created on

> The output when executing on a different machine without Python or the packages:

Does the other machine have Visual Studio 2013 redist installed? Because you are collecting the UCRT DLLs (which I think is redundant, unless the other machine is Windows 7, because otherwise Windows uses their own copy), but I don't see any DLL from VC runtime on that list (for example, `msvcp120.dll`). 

Try creating a onedir build instead of onefile one, and inspect the pyrfc extension or NWRFC DLLs in Dependency Walker on the target machine to see what you are missing...

Those files might have been picked up by automatic dependency analysis, but are not included because they are not in [this list](https://github.com/pyinstaller/pyinstaller/blob/6811c873b8cf8a09a7ad7db1449626a72a64df05/PyInstaller/depend/dylib.py#L60-L94) (which has VS2010 entries, and 2015/2017/2019 ones) - so once you know what DLLs from VS2013 redist you are missing, you can try adding them to that list, and they might be collected automatically.

**Comment by the-master-student** [comment]
Thank you so much for the clarification. It worked. I had different VS versions and it was very confusing. 

I appreciate your time and effort so much. Thank you
