### ISSUE TITLE
Issue with wxPython binary on MacOS

### ISSUE THREAD

**Issue by aglavic** [pyinstaller/pyinstaller#6787]
## Description of the issue
Im distributing my program based on python 3.x and wxPython using pyinstaller. On Windows this works well for some time and I'm trying to get a Mac OS executable now.

I have installed all may dependencies in a anaconda environment, this is the package list:
[conda_build.yml](https://github.com/pyinstaller/pyinstaller/files/8592080/conda_build.yml.txt)

While this environment allows me to compile a working minimal example with wxPython and runs my program correctly, I get some wired behavior when I run pyinstaller for my software. After the initialization I get many error messages from wxPython concerning douplicate implementations as it sees wx libraries of twice that are normally sym-linked in the system, but these seem to be just warnings that have no negative effect. When the code gets to a point where the wx.html functionality is used, however, the program crashes with a segmentation fault:
[crash_wxpython.log](https://github.com/pyinstaller/pyinstaller/files/8592056/crash_wxpython.log)

I have tried just copying all libraries from the the conda environment into the .app folder, which had no effect. I also added all wx sub-modules to the hiddenimports, which had no effect either.
Now I'm out of my expertise both what concerns MacOS and pyinstaller. Is ther anything I can do to better debug what is the actual problem?

Here is the pyinstaller spec fiel I've been using;
[genx_mac.spec](https://github.com/pyinstaller/pyinstaller/files/8592126/genx_mac.spec.txt)

### Context information (for bug reports)
* Output of `pyinstaller --version`: ```5.0.1```
* Version of Python: 3.9.12 (anaconda)
* Platform: OS X,
* How you installed Python: pip
* Did you also try this on another platform? No issue on Windows.

### A minimal example program which shows the error
I will try to create one, but maybe someone can already give me a hint of what is going on.

### Stacktrace / full error message
[crash_wxpython.log](https://github.com/pyinstaller/pyinstaller/files/8592056/crash_wxpython.log)

**Comment by bwoodsend** [comment]
> objc[41825]: Class wxNSTabView is implemented in both /Users/genx/genx/genx/dist/genx.app/Contents/MacOS/libwx_osx_cocoau_core-3.1.dylib (0x123d947a0) and /Users/genx/genx/genx/dist/genx.app/Contents/MacOS/libwx_osx_cocoau_core-3.1.5.0.0.dylib (0x1251937a0). One of the two will be used. Which one is undefined.

You seem to have two copies of the same library and loading both is disallowed on macOS. Identifying where they came from is probably your next step. There should be some TOC files in the `build` directory PyInstaller generates which will tell you that.

**Comment by rokm** [comment]
They were probably originally symlinks (even more likely considering this is conda), and ended up hard copies due to our lack of support for symlinks...

This makes it a duplicate of (or at very least closely related to) #5710.

**Comment by aglavic** [comment]
> You seem to have two copies of the same library and loading both is disallowed on macOS. Identifying where they came from is probably your next step. There should be some TOC files in the `build` directory PyInstaller generates which will tell you that.

Yes, I can confirm that the 3.1 library in the original is a symlink to the 3.1.5.0.0 version. I'm not sure this is the source for the crash, as the GUI does not crash without using the html library but shows the same error messages for the libraries.

**Comment by rokm** [comment]
> I'm not sure this is the source for the crash, as the GUI does not crash without using the html library but shows the same error messages for the libraries.

It is - see https://github.com/pyinstaller/pyinstaller/issues/5710.

**Comment by aglavic** [comment]
I think you are right and this is a duplicate of #5710. I can get a working binary with older wxpython and work around with replacing the second library version by a symlink does also work.
