### ISSUE TITLE
PyInstaller 5.0.1 can't find icon

### ISSUE THREAD

**Issue by Numerlor** [pyinstaller/pyinstaller#6788]
## Description of the issue
PyInstaller fails to find an icon specified with a valid path,s eems to be caused by the path being joined with specpath here 
https://github.com/pyinstaller/pyinstaller/blob/1a7d704ffbabb433007e3ba04750c2f13ade48e5/PyInstaller/utils/win32/icon.py#L95-L106

the SystemExit logs `path` which is a valid path (`.\pyinstaller_build\../icon/icons_library.ico` in the linked example), but `self.path` is used for the file which joins specpath with the passed in path again (`.\pyinstaller_build\.\pyinstaller_build\../icon/icons_library.ico`)
### Context information (for bug reports)

* Output of `pyinstaller --version`: `5.0.1`
* Version of Python: 3.10.4
* Platform: Windows
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?

### A minimal example program which shows the error
https://github.com/Numerlor/pyinstaller_icon
set up project (install pyinstaller/poetry install) and run `pyinstaller .\pyinstaller_build\file.spec` from the project root

**Comment by rokm** [comment]
These lines should probably be removed: https://github.com/pyinstaller/pyinstaller/blob/85d04eedbf4cf56006863ea8ad88363f69c89fee/PyInstaller/utils/win32/icon.py#L98-L99
Similarly as to how #6775 removed the other `os.path.isabs()` check in this file.

---

Although the root of the problem is that `CONF['spec']` and `CONF['specpath']` are not resolved to full absolute path, but are rather left in their original relative form. So prepending it to the icon path does not produce an absolute path, hence it ends up being prepended twice in two different places. Similarly, it seems that `CONF['distpath']` and `CONF['workpath']` are also not resolved if relative paths are provided via `--distpath` and `--workpath` CLI switches...

**Comment by The-Compiler** [comment]
FWIW I still do see issues in my project as well, which worked fine with PyInstaller 4.9.

With 5.0.1, I see:

```
41170 INFO: Copying icons from ['misc\\..\\qutebrowser\\icons\\qutebrowser.ico']
Unable to open icon file misc\..\qutebrowser\icons\qutebrowser.ico
```

but it's there:

```
PS C:\Users\florian.bruhin\proj\qutebrowser> ls .\misc\qutebrowser.spec


    Directory: C:\Users\florian.bruhin\proj\qutebrowser\misc


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          5/2/2022   9:35 AM           2503 qutebrowser.spec


PS C:\Users\florian.bruhin\proj\qutebrowser> ls .\misc\..\qutebrowser\icons\qutebrowser.ico


    Directory: C:\Users\florian.bruhin\proj\qutebrowser\qutebrowser\icons


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----          4/5/2022  12:20 PM         115490 qutebrowser.ico
```

**Comment by wanghaisheng** [comment]
```
    a = Analysis(['./main.py'],
hiddenimports=['sqlalchemy.sql.default_comparator'],    
                 pathex=[],
                 binaries=[],
                 datas=datas,
                 
                 hookspath=[],
                 runtime_hooks=[],
                 excludes=[],
                 win_no_prefer_redirects=False,
                 win_private_assemblies=False,
                 cipher=block_cipher,
                 noarchive=True)
    pyz = PYZ(a.pure, a.zipped_data,
              cipher=block_cipher)
    exe = EXE(pyz,
              a.scripts,
              a.binaries,
              a.zipfiles,
              a.datas,
              [],
              name='link-detect',
              debug=True,
              bootloader_ignore_signals=False,
              strip=False,
              upx=False,
              upx_exclude=[],
              runtime_tmpdir=None,
              console=False,
              icon='icon.ico'
              )

```
spec  py ico  all in the same folder

change to ./icon.ico still error
@rokm

**Comment by rokm** [comment]
@wanghaisheng The fix is not part of the release yet...

**Comment by bwoodsend** [comment]
I'll do a release in the next couple of days. Since we managed to not fix it the first time around, could someone check my sanity and test with the head of the development branch for me?
```
pip install https://github.com/pyinstaller/pyinstaller/archive/refs/heads/develop.zip
pyinstaller .\pyinstaller_build\file.spec
```

**Comment by Numerlor** [comment]
> I'll do a release in the next couple of days. Since we managed to not fix it the first time around, could someone check my sanity and test with the head of the development branch for me?
> 
> ```
> pip install https://github.com/pyinstaller/pyinstaller/archive/refs/heads/develop.zip
> pyinstaller .\pyinstaller_build\file.spec
> ```

Seems to be working correctly now
