### ISSUE TITLE
Again: Multiprocessing and --onefile under Windows, now: Pools

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#679]
**Original date**: 2013/03/04
**Original reporter**: _Markus DOT Piotrowski AND ruhr DASH uni DASH bochum DOT de_ @MarkusPiotrowski

I'm trying to pack a program which uses multiprocessing.Pool(). While --onedir is fine, --onefile results in runtime errors (translated from German):

```
WindowsError:[Error 5] Access denied and (sometimes) WindowsError:[Error 6] No such handle 
```

Of course I tried the recipe which works fine for me for multiprocessing.Process but it does not seem to work with pools. Do you have an idea, how I have to change the recipe?

System: Win7, 64 bit (problem also under 32 bit Win7)
Python: 2.7.2
Pyinstaller: recent development branch
Attached file: Pool_Test.py

**Comment by htgoebel** [comment]
@MarkusPiotrowski: Hi, this is an old PyInstaller issue by you. Can you please verify it is still an issue, otherwise close it. Thanks.

If it is still an issue, would you please be so kind and check if #1161 solves it. Thanks

**Comment by htgoebel** [comment]
@MarkusPiotrowsk: #1161 is merged now, so you can test using the current development head.

**Comment by MarkusPiotrowski** [comment]
Pools still seem to be a problem, even with the development branch. Here's my code:

    from multiprocessing import Process, freeze_support, Pool
    import random, time

    def f(number):
        time.sleep(random.randint(0,4))
        print 'Number', number
        return number

    if __name__ == '__main__':
        freeze_support()
        while True:
            print 'Testing Multiprocess...'
            p1 = Process(target=f, args=(1,))
            p2 = Process(target=f, args=(2,))
            p3 = Process(target=f, args=(3,))
            p4 = Process(target=f, args=(4,))
    
            p1.start()
            p2.start()
            p3.start()
            p4.start()

            p1.join()
            p2.join()
            p3.join()
            p4.join()

            print 'Testing Pool...'
            pool = Pool(processes=4)
            result = pool.map(f, (1,2,3,4))
            pool.close()
            pool.join()
        
            stop = raw_input('Please press "return"')

Multiprocess works fine in --onefile, but Pool crashes with errors 5 and 6

    WindowsError:[Error 5] Access denied and (sometimes) WindowsError:[Error 6] No such handle 

Both parts are running fine as 'one directory'

System: Win7, 64 bit
Python: 2.7.5
Pyinstaller: recent development branch

**Comment by Legorooj** [comment]
Can this be closed now?
