### ISSUE TITLE
M1 MacOS 12.3.1+python3.9.10+pyinstaller in Problem

### ISSUE THREAD

**Issue by jiayouzl** [pyinstaller/pyinstaller#6801]
hello everybody

pyinstaller -F ./app.py

and

iterm ./app

It will send a request like an Apple server(api.apple-cloudkit.com), which takes about 10 seconds each time. What's going on? Thank you!

pyinstaller version==5.0.1

my code
```
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

print('0.0.1')
```

**Comment by rokm** [comment]
Onefile (`-F`) build needs to unpack itself before it can run. And then OS probably needs to scan the extracted contents, too. Both happen each time you run your onefile program.

**Comment by jiayouzl** [comment]
> Onefile (`-F`) build needs to unpack itself before it can run. And then OS probably needs to scan the extracted contents, too. Both happen each time you run your onefile program.

First of all, thank you. I know what you said about decompressing with-F, but the problem now is that the program will visit apple's website(api.apple-cloudkit.com), which causes the program to start slowly.

It takes about 10 seconds to use it normally every time.

**Comment by jiayouzl** [comment]
> Onefile (`-F`) build needs to unpack itself before it can run. And then OS probably needs to scan the extracted contents, too. Both happen each time you run your onefile program.

-D It will be the same

**Comment by rokm** [comment]
So it is *your code* that is using the CloudKit?

**Comment by jiayouzl** [comment]
> So it is _your code_ that is using the CloudKit?

no my all code~

```
#!/usr/bin/env python3
# -*- coding: UTF-8 -*-

print('0.0.1')
```

**Comment by jiayouzl** [comment]
![iShot_2022-05-05_00 21 54](https://user-images.githubusercontent.com/7685337/166726713-8c8b1e79-d862-496c-9921-d44df48e32a8.gif)

**Comment by rokm** [comment]
And you're 100% that this isn't macOS checking your executable or its contents?

**Comment by jiayouzl** [comment]
> And you're 100% that this isn't macOS checking your executable or its contents?

I'm not sure, just want to know how to solve this problem.

When the program runs, it will not be accessed to the Apple website.

**Comment by rokm** [comment]
On my test system, I can confirm that onefile builds seem to trigger access to api.apple-cloudkit.com on every run, while onedir build does so on the first run (unless renamed or moved; in which case it triggers it again). So my guess would be that this is OS scanning the unsigned executable (or its components, like shared libraries). 

Perhaps signing the executable (or rather, everything) with valid Apple developer ID will exempt your program from this scan?

**Comment by jiayouzl** [comment]
> On my test system, I can confirm that onefile builds seem to trigger access to api.apple-cloudkit.com on every run, while onedir build does so on the first run (unless renamed or moved; in which case it triggers it again). So my guess would be that this is OS scanning the unsigned executable (or its components, like shared libraries).
> 
> Perhaps signing the executable (or rather, everything) with valid Apple developer ID will exempt your program from this scan?

I know what I should do, thank you very much!
