### ISSUE TITLE
building bootloader fails with `error LNK2005` strnlen already defined in pyi_utils.c.2.o

### ISSUE THREAD

**Issue by ewerybody** [pyinstaller/pyinstaller#6803]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.1```
* Version of Python:  tried with `3.8`, `3.9`, `3.10`
* Platform:  **Windows**
* How you installed Python:  installer from python.org/downloads
* Did you also try this on another platform? Does it work there?
  Not another platform but another machine! It worked there! 👍
  But I still don't know what the issue is on MY machine :/

* try the latest development version, using the following command:
  ... well this IS the version from git already. I guess the rest here does not apply to this kind of "bug", right?

I just updated `chocolatey` to latest and then fetched the suggested in Admin-mode:
```
choco install -y python3 visualstudio2019-workload-vctools
```

Then in `...\pyinstaller\bootloader` i called `c:\..{different versions}\python.exe ./waf all`:

```error
[24/24] Linking build\debug\run_d.exe
libucrt.lib(strnlen.obj) : error LNK2005: strnlen already defined in pyi_utils.c.2.o
...\pyinstaller\bootloader\build\debug\run_d.exe : fatal error LNK1169: one or more multiply defined symbols found

Waf: Leaving directory `...\pyinstaller\bootloader\build\debug'
Build failed
 -> task in 'run_d' failed with exit status 1169 (run with -v to display more information)
```

Here is a complete log of the situation if needed:
[pyinstaller_waf_error_LNK2005.log](https://github.com/pyinstaller/pyinstaller/files/8626610/pyinstaller_waf_error_LNK2005.log)

**Comment by rokm** [comment]
Can you open the `pyinstaller\bootloader\build\config.log`, search for "Checking for function strnlen" (should be at the end), and check why that particular test failed to compile?

**Comment by rokm** [comment]
Does it perhaps help if you move pyinstaller source to a shorter path (i.e., #4824 or this [waf](https://gitlab.com/ita1024/waf/-/issues/2299) issue).

**Comment by ewerybody** [comment]
I'm mindblown! 😧 That worked! I honestly though: "what a ridiculous idea!"

My username is actually 7 characters shorter on the failing machine. That was the only difference in that path which was "only" 50 chars into the `pyinstaller` root dir.

**Comment by ewerybody** [comment]
Darn I was searching for `LNK2005` before posting but didn't see this. :/ I'm sorry that I didn't dig deeper before.
But couldn't there be a better solution? Or some hint somewhere?

I did some testing on the 2 PCs.
The Registry setting `HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem\LongPathsEnabled` is on `1` on both. Turning it to `0` did NOT change a thing.

The path can be **longer** if the path is **less deeply nested** and if the **path to msvc** is **shorter**! specifically:
### pc 1
len to msvc: **110** chars **11** subdirs (installed via chocolatety)
* 0 subdirs 61 ✔ 62 ❌(c:\(super long dir name))  
* 1 subdirs 58 ✔ 59 ❌(c:\subdir\..(super long dir name))
* 2 subdirs 55 ✔ 56 ❌(c:\users\username\...(super long dir name))
* 3 subdirs 52 ✔ 53 ❌ ...
* 4 subdirs 49 ✔ 50 ❌ ...
* 5 subdirs 46 ✔ 47 ❌ ... 
### pc 2
len to msvc: **56** chars **5** subdirs (installed via VS installer)
* 0 subdirs 92 ✔ 93 ❌(c:\(super long dir name))  
* 1 subdirs 89 ✔ 90 ❌(c:\subdir\..(super long dir name))
* 2 subdirs 86 ✔ 87 ❌...
* 3 subdirs 83 ✔ 84 ❌...
* 4 subdirs 80 ✔ 81 ❌...
* 5 subdirs 77 ✔ 78 ❌... 

as in **works ✔ breaks ❌** like path length in characters.

So **per subdir** the path needs to be be **3 characters shorter**!

But there is still a 31 chars diff between the 2 machines 🤔. I dunno how to make sense of that in regards of the msvc directory. There is [this stackoverflow answer](https://stackoverflow.com/a/17809339/469322) about that 260 limit but that doesn't make much more sense since the "solution name" must be the same in all cases.

Some of my number are here:
> [path len test.txt](https://github.com/pyinstaller/pyinstaller/files/8631706/path.len.test.txt)

**Comment by bwoodsend** [comment]
I'd been meaning to check what the actual character limit is then add a check that it's short enough in the build script so that it can produce a useful error message. At least now I know that it's not possible to get a nice clear consistent threshold. It's not the answer I wanted to here but thanks for finding it.

Possibly the compiler is installed somewhere different on your two machines - the one installed in a longer path being PC 1? That's the only possible cause I can come up with for the difference between the two.

The 260 character limit is a red herring. As long as that `LongPathsEnabled` is set to 1, it's disabled so it can't interfere. I think, deep in the bowls of MSCV's internals, there must be a command buffer that's getting truncated somewhere. The issue does not happen if you use gcc no matter how long your paths are so it's not waf's fault AFAICT.

**Comment by rokm** [comment]
From the fix in the [`waf` issue](https://gitlab.com/ita1024/waf/-/issues/2299) (which will be available once waf 2.1 is released and we update our copy to it...), I think the problem is that
a) `waf` generates include paths for MSVC include directories as relative to the build directory, for example (taken from the other issue that the linked waf issue references) `/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2017\\BuildTools\\VC\\Tools\\MSVC\\14.16.27023\\include`. So include directories that are deep in the bowels of MSVC installation path may end up prefixed with many `..\\`, depending on how deep your build directory is.
b) MSVC probably has (an internal) include directory path length limit of an unknown value (possibly unrelated to 260 characters limit, and unrelated to the long path support as well)

**Comment by ewerybody** [comment]
Yeah I also thought there must be some metric to tell `True`/`False` its your path!

I mean in a way there is. Pretty predictable with the number of subdirs if you once get the sweet spot.
I got the idea for looking into that from the verbose `-v` output one gets in the `config.log`:
```
...
Checking for function strnlen
==>

    #include <string.h>

    int main(int argc, char **argv) {
        void (*p)();

        (void)argc; (void)argv;
        p=(void(*)())(strnlen);
        return !p;
    }

<==
[1/2] Compiling [32mbuild\conf_check_8f8ff9991bc6f54827b0bf6b5cc69b16\test.cpp[0m

['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX64\\x64\\CL.exe', '/nologo', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\include', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\shared', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\um', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\winrt', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\cppwinrt', '/DWIN32', '/DNTDDI_VERSION=0x06010000', '/D_WIN32_WINNT=0x0601', '..\\test.cpp', '/FC', '/c', '/FoC:\\Users\\techarteric\\io\\code\\_incoming\\pyinstaller\\bootloader\\build\\conf_check_8f8ff9991bc6f54827b0bf6b5cc69b16\\testbuild\\test.cpp.1.o']
out: test.cpp

C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\ucrt\corecrt_memcpy_s.h(12): fatal error C1083: Cannot open include file: 'vcruntime_string.h': No such file or directory


from C:\Users\techarteric\io\code\_incoming\pyinstaller\bootloader: Test does not build: Traceback (most recent call last):
  File "C:\Users\techarteric\io\code\_incoming\pyinstaller\bootloader\waf3-2.0.20-a3a5949fb45bcd86794262f86d7977a7\waflib\Configure.py", line 335, in run_build
    bld.compile()
  File "C:\Users\techarteric\io\code\_incoming\pyinstaller\bootloader\waf3-2.0.20-a3a5949fb45bcd86794262f86d7977a7\waflib\Tools\errcheck.py", line 140, in check_compile
    ret=self.orig_compile()
  File "C:\Users\techarteric\io\code\_incoming\pyinstaller\bootloader\waf3-2.0.20-a3a5949fb45bcd86794262f86d7977a7\waflib\Build.py", line 176, in compile
    raise Errors.BuildError(self.producer.error)
waflib.Errors.BuildError: Build failed
 -> task in 'testprog' failed with exit status 2: 
	{task 2869873703200: cxx test.cpp -> test.cpp.1.o}
['C:\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\bin\\HostX64\\x64\\CL.exe', '/nologo', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\include', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\NETFXSDK\\4.8\\include\\um', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\ucrt', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\shared', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\um', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\winrt', '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Windows Kits\\10\\include\\10.0.19041.0\\cppwinrt', '/DWIN32', '/DNTDDI_VERSION=0x06010000', '/D_WIN32_WINNT=0x0601', '..\\test.cpp', '/FC', '/c', '/FoC:\\Users\\techarteric\\io\\code\\_incoming\\pyinstaller\\bootloader\\build\\conf_check_8f8ff9991bc6f54827b0bf6b5cc69b16\\testbuild\\test.cpp.1.o']

no
from C:\Users\techarteric\io\code\_incoming\pyinstaller\bootloader: The configuration failed
```

There are quite some of these crazy relative paths in there like:
```
 '/I..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\Program Files (x86)\\Microsoft Visual Studio\\2019\\Community\\VC\\Tools\\MSVC\\14.26.28801\\ATLMFC\\include',
```
where I thought: that doesn't look healthy! These **must** be shorter with an absolute path! But I have no idea where these are constructed.

**Comment by rokm** [comment]
> These **must** be shorter with an absolute path! 

They are, and AFAICT, the waf patch switches to an absolute path in such cases. 

> But I have no idea where these are constructed.

`waf` generates those, so we have no control over them. If we wanted to address this at this point, we'd need to switch our `waf` copy from the stable version to a checkout from 2.1 branch.

**Comment by ewerybody** [comment]
Nice @bwoodsend ! I'll give it a try asap.

**Comment by ewerybody** [comment]
✔ I can **confirm** that it works with the [update-waf](https://github.com/bwoodsend/pyinstaller/tree/update-waf) branch!
