### ISSUE TITLE
Add An Multiple Splash Screen and License Approval

### ISSUE THREAD

**Issue by Rohith-sreedharan** [pyinstaller/pyinstaller#6819]
Like i would suggest That:
        1. Multiple Splash Screen
        2. agree to our License dialog box

More Info: 
         Multiple Splash Screen should loaded random from the list and should be visible at startup.. like different images should be available
        
         License Dialog Box:
                      Dialog Box to accept or reject the dialog box [optional if needed]

I Hope You gonna consider my idea, as i think its worth!!!

**Comment by xo-HADES-xo** [comment]
Agreement to License box does not need to be part of a Splash Screen setup.  Write your own simple startup window (GUI with check box) for user to agree to license, if they do, proceed to call the main program, otherwise, gracefully exit.

**Comment by Rohith-sreedharan** [comment]
OK got it can you send me an referring code for it?

**Comment by Rohith-sreedharan** [comment]
> Agreement to License box does not need to be part of a Splash Screen setup. Write your own simple startup window (GUI with check box) for user to agree to license, if they do, proceed to call the main program, otherwise, gracefully exit.

What about Multiple Splash Screen

**Comment by bwoodsend** [comment]
> What about Multiple Splash Screen

The splash screen can't be controlled by Python code - only tcl script or C - so, short of requiring users to learn and write tcl script, we'd have to hardcode this random selection of splash screens directly into the bootloader in C which is a heck of a lot of work for what's essentially just a flashy gimmick feature.

**Comment by Legorooj** [comment]
License dialogs should not be part of a PyInstaller executable. If you need one, it should be part of the program that _installs_ your PyInstaller executable.

**Comment by Rohith-sreedharan** [comment]
> 

Great then

**Comment by Legorooj** [comment]
I'm not against having multiple images for the splash screen but it's not high on our Todo list. Feel free to submit a PR for it.
