### ISSUE TITLE
--key not allowed as command line argument anymore

### ISSUE THREAD

**Issue by marcelomanzo** [pyinstaller/pyinstaller#6836]
PS C:\Users\marce\PycharmProjects\srsapp> pyinstaller.exe test.spec --noconfirm --key abc2123
82 INFO: PyInstaller: 5.1
82 INFO: Python: 3.10.0
91 INFO: Platform: Windows-10-10.0.22000-SP0
option(s) not allowed:
  --key
makespec options not valid when a .spec file is given
PS C:\Users\marce\PycharmProjects\srsapp>

I understand that the arguments now needs to be in the spec files, but shouldn't the --key come from the command line, as it's a key to encrypt the py files, as security option, it should no be stored in a file.

**Comment by rokm** [comment]
Even before the change, the only way to effectively specify it was via the spec file; when you ran `pyinstaller ... --key mykey program.py`, it was written to the generated `program.spec` file. And if you ran `pyinstaller --key mynewkey program.spec`, the `--key` argument had no effect and the value from the spec file was taken.
