### ISSUE TITLE
LoadLibrary: PyInstaller: FormatMessageW failed

### ISSUE THREAD

**Issue by Avnsx** [pyinstaller/pyinstaller#6837]
## Description of the issue
Executables compiled on windows 10 with pyinstaller are not able to be ran on Windows 7. I think this is a huge issue, because I personally use pyinstaller to fix the need for users to have python installed, when using my open source projects. A still remarkable amount of users are on Windows 7 and this really takes the entire sense behind the story of compiling python code to executables. The only solution that works for me is compiling with python 3.8.10 (which is compatible with both versions of Windows), else I keep running into this error.

### Context information (for bug reports)

* Pyinstaller Version: 5.1
* Version of Python: 3.10.4
* Platform: Windows 10, Windows 7
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Compiled on Windows 10, ran on Windows 7 doesn't work there but works on windows 10.

### A minimal example program which shows the error

You can literally compile any code with pyinstaller on windows 10 with python 3.10.4 and try to run that compiled executable on windows 7; it'll always result in the same exact error.

### Stacktrace / full error message
```
Error loading Python DLL \appdata\local\temp\_mei17882\python310.dll
No error messages generated.
FormatMessageW: The parameter is incorrect.
LoadLibrary: Pyinstaller: FormatMessageW failed.
```

This issue has also been pointed out before in https://github.com/pyinstaller/pyinstaller/issues/3999 but was falsely closed, because the contributor or maintainer at the time thought it would only be related to wine.

**Comment by Legorooj** [comment]
We don't support windows 7. The only versions we support are 8, 10, and 11. 

If you'd like to support windows 7, iirc you'll need to build on windows 7. PyInstaller should still be compatible even if it doesn't officially support win7.

**Comment by bwoodsend** [comment]
And the latest version of Python to support Windows 7 or 8.0 was Python 3.8 so by using Python 3.10 you've already broken it.

**Comment by Avnsx** [comment]
> We don't support windows 7. The only versions we support are 8, 10, and 11.
> 
> If you'd like to support windows 7, iirc you'll need to build on windows 7. PyInstaller should still be compatible even if it doesn't officially support win7.

Well according to https://github.com/pyinstaller/pyinstaller/issues/3999#issuecomment-459788030 this also happens on Windows 10 and windows 8

    ¯\_(ツ)_/¯

**Comment by rokm** [comment]
> Well according to [#3999 (comment)](https://github.com/pyinstaller/pyinstaller/issues/3999#issuecomment-459788030) this also happens on Windows 10 and windows 8

That comment is related to original report on using wine to cross-compile application for Windows, though. And the report was made against python 3.4 that's EOL'd now. And before we started preventing wine DLLs from being collected, which I suspect was the cause of the original issue.

But none of that matters in your case, which is much more straightforward - if you're trying to use python >= 3.9 on Windows 7, it won't work. Python.org [download page](https://www.python.org/downloads/windows/) states as much, for example: ```Note that Python 3.9.13 cannot be used on Windows 7 or earlier.``` And by extension, PyInstaller-frozen application won't work either, because the collected python shared library won't load on Windows 7.

**Comment by bwoodsend** [comment]
But that particular user was using Wine so they'll have been picking up Wine's shim libraries instead of the proper MSVC runtime DLLs. There is someone on that thread who wasn't using Wine but was using Python 3.9 which is incompatible with Windows 7.
