### ISSUE TITLE
Support for one-file setuid binaries

### ISSUE THREAD

**Issue by KnockKnockWho** [pyinstaller/pyinstaller#6842]
I have some questions regarding the documentation at https://readthedocs.org/projects/pyinstaller/downloads/pdf/stable/, which currently states the following:
`
Do not give administrator privileges to a one-file executable (setuid root in Unix/Linux, or the “Run this program
as an administrator” property in Windows 7). There is an unlikely but not impossible way in which a malicious attacker
could corrupt one of the shared libraries in the temp folder while the bootloader is preparing it. Distribute a privileged
program in one-folder mode instead.
`

1. What is the issue with the current extraction process? If the newly created temporary directory is only writeable to the creator (i.e. has permissions 755 or stricter), there should not be any way for an unprivileged user to corrupt the shared libraries that get extracted there.
2. If this currently affects setuid executables, it is likely that this is also an issue when being run as root regularly, e.g. using sudo. The only difference would be that an attacker has to wait for this event. Is that correct?
3. Is there any support for root/administrator-safe one-file binaries planned?

I am asking because I am actually interested in distributing a Python app that is supposed to be run as root.

Thank you.

**Comment by bwoodsend** [comment]
Hmm, I think that line is obsolete. It was introduced [here](https://github.com/pyinstaller/pyinstaller/commit/90c62ebf92fc72df4b974fe15ca5fca66a957ad0/doc/source/Manual.rst#diff-b43e7725672701376318b623c4a82405133588040f3d1565f168eac8db120c33R342) in PyInstaller 2.1 which is long before https://github.com/pyinstaller/pyinstaller/security/advisories/GHSA-7fcj-pq9j-wh2r was raised and addressed for Windows. On Unix, all files are created with `0700` permissions so an attacker shouldn't even be able to `ls` the temporary directory - let alone sabotage its contents.

So I think it's safe to remove that line although I'll wait for @rokm to give a second opinion.

**Comment by rokm** [comment]
The temporary directory on linux is indeed created with `700` permissions, so only the creator (the user running the program) has access to them. On Windows, we similarly use the current user's SID due to [GHSA-7fcj-pq9j-wh2r](https://github.com/pyinstaller/pyinstaller/security/advisories/GHSA-7fcj-pq9j-wh2r) (originally, it was SID `S-1-3-4`, but due to lack of support for that in Wine, it was changed to resolving and using the current user's SID).

That said, that paragraph is still correct if you consider a local, unprivileged user, to be a potential attacker (e.g., seeking privilege escalation). The user could launch the `suid`'d executable, and because contents of temporary directory are writable to them, they might try to edit the contents (e.g., replace a shared library or a data file) to achieve desired execution path with admin privileges.

Whether or not that is a relevant definition of an attack depends on your system and use case - if this is a single-user linux desktop where the user can elevate to admin privileges either via `su` or `sudo`, then this is obviously moot. But in that case, I don't see much point in giving the executable `suid`, either (unless maybe if it is intended to be launched from other user-privileged programs and authentication for purposes of privilege elevation is undesirable).

**Comment by KnockKnockWho** [comment]
Thank you both for your replies.

> That said, that paragraph is still correct if you consider a local, unprivileged user, to be a potential attacker (e.g., seeking privilege escalation). The user could launch the `suid`'d executable, and because contents of temporary directory are writable to them, they might try to edit the contents (e.g., replace a shared library or a data file) to achieve desired execution path with admin privileges.

I would indeed consider a local, unprivileged user to be a potential attacker. If the presence of a setuid binary leads to a privilege escalation, this is a vulnerability. However, I fail to see how a privilege escalation would work in that case. If the executable would have a `setuid` bit set for its owner, let's assume `root` here, the temporary directory would be owned by that user, i.e. `root`, and because the permissions are `700`, nobody else would have access to that directory. Since I don't assume that the bootloader performs setuid manipulations of any kind, I would argue that the paragraph can be removed (for Unix/Linux at least).

**Comment by rokm** [comment]
> However, I fail to see how a privilege escalation would work in that case. If the executable would have a `setuid` bit set for its owner, let's assume `root` here, the temporary directory would be owned by that user, i.e. `root`, and because the permissions are `700`, nobody else would have access to that directory.

Yes, you are correct. I earlier missed the fact that `suid` + executable being owned by root (which is prerequisite for privilege escalation in the first place) also means that the temporary directory ends up being owned by root. 

So yeah, the paragraph should probably be removed.

**Comment by KnockKnockWho** [comment]
Before I submit the removal of this note as a PR, I would like to make sure that running a PyInstaller binary as administrator is safe on Windows as well. Unfortunately, I am not too familiar with Windows. It could be an issue there.

According to https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_win32_utils.c#L443, only the current user has access to the directory. But elevating privileges works differently on Windows. My understanding is that instead of switching the user identity, the whole process runs under the same identity but with elevated privileges. Now assume the application is started with administrator privileges (e.g. through `runas`). Then, PyInstaller would create the temporary directory as specified. However, since this directory is guarded by the user identity only, an unelevated process running under the same identity could still modify the files in the directory, unless access can be somehow restricted to other processes with at least the same level of elevation. Is that correct?

As I said, I am not very familiar with Windows, so I might be off base here. Maybe someone who is more familiar with Windows can chip in?

**Comment by rokm** [comment]
That's correct. On Windows, the temporary directory is still writable by the user, even if the program was ran with elevated privileges (e.g., --uac-admin). 

But I think if the user is capable of elevating to admin privileges via UAC (whether it is just confirmation dialog, or requires actual authorization), they already have admin privileges and can do anything they want anyway. Unless it is possible to lock down UAC elevation so that only the hypothetical PyInstaller-frozen application can be elevated in such way. Then I guess we should still consider it an attack vector.

**Comment by bwoodsend** [comment]
Hmm, I can't see that 42a67148b3bdf9211fda8499fdc5b63acdd7e6cc does anything at all?

**Comment by rokm** [comment]
> Hmm, I can't see that [42a6714](https://github.com/pyinstaller/pyinstaller/commit/42a67148b3bdf9211fda8499fdc5b63acdd7e6cc) does anything at all?

It switches from `_wmkdir` to `CreateDirectoryW`, where we can specify security attributes (i.e., the owner SID).

**Comment by bwoodsend** [comment]
But what difference does that make if it's not disallowing unprivileged write access?

**Comment by rokm** [comment]
It prevents *another* user from editing the contents of the temporary directory. The CVE is about having a onefile program running under privileged user (system service, system administrator account, etc.) and another, unprivileged user, trying to escalate their own privileges by editing the temporary directory that should not be writable by them.

**Comment by KnockKnockWho** [comment]
42a67148b3bdf9211fda8499fdc5b63acdd7e6cc fixes the issue for other user identities. Before this fix, if you were running a PyInstaller program as administrator, another user account that is not allowed to run programs with elevated privileges could modify the libraries to execute code with elevated privileges as the user that is running the PyInstaller program.

But basically the "issue" on Windows that currently exists, if you even want to call it one, is comparable to an attacker already having access to a user with sudo capabilities while not having gained true root access yet. On Linux, at that point, the game is over anyway as there are many methods to elevate to root, e.g. by hijacking the sudo function through `~/.bash_profile`. I guess this is just inherent to distributing programs that are supposed to be run as administrator this way on Windows. At some point, even if it is only a point between downloading and first execution of the app, it can be overwritten to elevate to admin privileges. This would be true for any program that e.g. elevates to admin to start a classic Windows installer as long as it is lying around e.g. in the `Downloads` folder. However, programs using classic installers are usually protected from this kind of attack after installation, as their files are placed in `C:\Program Files\` and are not modifiable without elevating privileges. In contrast, for PyInstaller programs, this attack is possible during unpacking or even all the time if the file permissions allow modification without elevated privileges.

There are two solutions that come to mind:

1. Integrate an optional, classic installer functionality that extracts the files once to e.g. `C:\Program Files\` or a location of the user's choice and make sure that file permissions are set accordingly. Probably the cleanest and best way.
2. Check if the PyInstaller application is running with elevated privileges. If so, modify the file permissions for the temp dir so that one can only modify its files when already running with elevated privileges. This wouldn't fix the issue of modification due to insecure file permissions though.
