### ISSUE TITLE
The ordinal 380 could not be located in the dynamic link library <MY_PROJECT.exe>.

### ISSUE THREAD

**Issue by Dave-J-69420** [pyinstaller/pyinstaller#6845]
### Hey everyone!
So, I just made a game called _"Bonk!"_ (basically _Pong!_ with cheems hitting Picardía) and tried to convert `main.py` (the game's main Python file) to EXE. Then what followed? Boom! [An error](https://user-images.githubusercontent.com/99442121/170114374-0df6e65c-1881-473c-bf30-2cc75fee6e92.png)! I have no idea what is that, but please help me, I want my game to be EXE, because it deserves it! 🥺 🙏

**Comment by rokm** [comment]
What version of PyInstaller are you using? Is this a onefile or onedir build?

`The ordinal 380 could not be located in the dynamic link library` means that windowed variant of bootloader failed to load the correct version of Common Controls library. Usually this happens when there's something wrong with the application's manifest, but we now embed that into the executable in both onefile and onedir build...

**Comment by Dave-J-69420** [comment]
> What version of PyInstaller are you using? Is this a onefile or onedir build?
> 
> `The ordinal 380 could not be located in the dynamic link library` means that windowed variant of bootloader failed to load the correct version of Common Controls library. Usually this happens when there's something wrong with the application's manifest, but we now embed that into the executable in both onefile and onedir build...

I'm using PyInstaller v4.9 and this is a onefile. This question may be dumb, but is the the manifest `<filename>.exe.manifest` file? If yes, then what to do here? Also, sorry for late reply. 😕

**Comment by bwoodsend** [comment]
Yes, it is, but are you definitely running the exe in the `dist` folder instead of the `build` folder? `<filename>.exe.manifest` should only exist in `build` which is just for temporary files.

**Comment by Dave-J-69420** [comment]
> Yes, it is, but are you definitely running the exe in the `dist` folder instead of the `build` folder? `<filename>.exe.manifest` should only exist in `build` which is just for temporary files.

I'm running the EXE file in the `dist` folder, that's right. Yeah, `Bonk!.exe.manifest` IS located in the `build` folder. But I can't see my EXE game in `build`...

**Comment by rokm** [comment]
The manifest is (should be?) embedded into the final executable (in onedir mode, you can get side-by-side manifest instead via `--no-embed-manifest` switch).

Can you attach the `Bonk!.exe.manifest` from the `build` folder here?

**Comment by Dave-J-69420** [comment]
> The manifest is (should be?) embedded into the final executable (in onedir mode, you can get side-by-side manifest instead via `--no-embed-manifest` switch).
> 
> Can you attach the `Bonk!.exe.manifest` from the `build` folder here?

I use `--onefile`, but okay, I will send the `Bonk!.exe.manifest` file here
```xml
<!--Bonk!.exe.manifest-->
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <assemblyIdentity type="win32" name="main" processorArchitecture="amd64" version="1.0.0.0"/>
  <trustInfo xmlns="urn:schemas-microsoft-com:asm.v3">
    <security>
      <requestedPrivileges>
        <requestedExecutionLevel level="asInvoker" uiAccess="false"/>
      </requestedPrivileges>
    </security>
  </trustInfo>
  <dependency>
    <dependentAssembly>
      <assemblyIdentity type="win32" name="Microsoft.Windows.Common-Controls" language="*" processorArchitecture="*" version="6.0.0.0" publicKeyToken="6595b64144ccf1df"/>
    </dependentAssembly>
  </dependency>
  <compatibility xmlns="urn:schemas-microsoft-com:compatibility.v1">
    <application>
      <supportedOS Id="{e2011457-1546-43c5-a5fe-008deee3d3f0}"/>
      <supportedOS Id="{35138b9a-5d96-4fbd-8e2d-a2440225f93a}"/>
      <supportedOS Id="{4a2f28e3-53b9-4441-ba9c-d69d4a4a6e38}"/>
      <supportedOS Id="{1f676c76-80e1-4239-95bb-83d0f6d0da78}"/>
      <supportedOS Id="{8e0f7a12-bfb3-4fe8-b9a5-48fd50a15a9a}"/>
    </application>
  </compatibility>
  <application xmlns="urn:schemas-microsoft-com:asm.v3">
    <windowsSettings>
      <longPathAware xmlns="http://schemas.microsoft.com/SMI/2016/WindowsSettings">true</longPathAware>
    </windowsSettings>
  </application>
</assembly>
```

**Comment by bwoodsend** [comment]
I doubt that it's this but can you try renaming `Bonk!` to `Bonk`? I'm fairly certain that `!` isn't a valid path character on Windows.

**Comment by rokm** [comment]
Hmm, the manifest looks OK to me. I guess next question is, does `boink!.exe` actually have manifest embedded?
If you have Visual Studio installed, you can check using `mt.exe` (from its Developer command prompt):

```shell
mt.exe -inputresource:"c:\path\to\boink!.exe" -out:con
```

If not, you can use the following python snippet (ran from environment where you have PyInstaller installed)

```python
from PyInstaller.utils.win32 import winmanifest
manifest = winmanifest.ManifestFromResFile('path/to/boink!.exe')
print(manifest.toprettyxml())
```

Does this display the embedded manifest, or is there an error/message about manifest/resource not being found?

**Comment by Dave-J-69420** [comment]
> Hmm, the manifest looks OK to me. I guess next question is, does `boink!.exe` actually have manifest embedded? If you have Visual Studio installed, you can check using `mt.exe` (from its Developer command prompt):
> 
> ```shell
> mt.exe -inputresource:"c:\path\to\boink!.exe" -out:con
> ```
> 
> If not, you can use the following python snippet (ran from environment where you have PyInstaller installed)
> 
> ```python
> from PyInstaller.utils.win32 import winmanifest
> manifest = winmanifest.ManifestFromResFile('path/to/boink!.exe')
> print(manifest.toprettyxml())
> ```
> 
> Does this display the embedded manifest, or is there an error/message about manifest/resource not being found?

Well... When I run `mt.exe -inputresource:"c:\path\to\boink!.exe" -out:con`, it says:
```yaml
mt.exe : The term 'mt.exe' is not recognized as the name of a cmdlet, function, script file, or operable program. Check
 the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ mt.exe -inputresource:"D:\Programming\Softwares\Python\Projects\Bonk! ...
+ ~~~~~~
    + CategoryInfo          : ObjectNotFound: (mt.exe:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```
But this is because I don't know where is the `mt.exe` stored... Gonna try the Python one...

**Comment by rokm** [comment]
> But this is because I don't know where is the `mt.exe` stored...

`mt.exe` is likely available only after Visual Studio's `vcvarsall.bat` is ran (e.g., in Developer Command Prompt shortcuts).

**Comment by Dave-J-69420** [comment]
> `mt.exe` is likely available only after Visual Studio's `vcvarsall.bat` is ran (e.g., in Developer Command Prompt shortcuts).

You mean I need to run `vcvarsall.bat` file to use `mt.exe`? And can I run it as a file or only in DCP?

**Comment by bwoodsend** [comment]
Yes. But just use the Python variant if you're not familiar with MSVC.
```python
from PyInstaller.utils.win32 import winmanifest
manifest = winmanifest.ManifestFromResFile('path/to/boink!.exe')
print(manifest.toprettyxml())
```

**Comment by Dave-J-69420** [comment]
> Yes. But just use the Python variant if you're not familiar with MSVC.
> 
> ```python
> from PyInstaller.utils.win32 import winmanifest
> manifest = winmanifest.ManifestFromResFile('path/to/boink!.exe')
> print(manifest.toprettyxml())
> ```

Okay! And the Python variant, where should I paste the code? In the `main.py` of the Bonk!?

**Comment by bwoodsend** [comment]
No, create a new .py file, paste it in there, replace `path/to/boink!.exe` with whatever its real filename is, then run that .py file.

**Comment by Dave-J-69420** [comment]
> No, create a new .py file, paste it in there, replace `path/to/boink!.exe` with whatever its real filename is, then run that .py file.

You mean I have to replace Bonk!.exe with the new `.py` file?

**Comment by bwoodsend** [comment]
No I mean in the new .py file you just wrote, replace the line:
```python
manifest = winmanifest.ManifestFromResFile('path/to/boink!.exe')
```
with
```python
manifest = winmanifest.ManifestFromResFile('D:\Programming\Softwares\Python\Projects\Bonk!\dist\Bonk!.exe')
```

**Comment by bwoodsend** [comment]
Maybe just upload your program somewhere so that we can look at it.

**Comment by Dave-J-69420** [comment]
> Maybe just upload your program somewhere so that we can look at it.

Hmm... I ran it and this happened:
```yaml
File "D:\Programming\Softwares\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programming\Softwares\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "c:\Users\david\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\david\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 444, in main    
    run()
  File "c:\Users\david\.vscode\extensions\ms-python.python-2022.4.1\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 285, in run_file
    runpy.run_path(target_as_str, run_name=compat.force_str("__main__"))
  File "D:\Programming\Softwares\Python\lib\runpy.py", line 269, in run_path
    return _run_module_code(code, init_globals, run_name,
  File "D:\Programming\Softwares\Python\lib\runpy.py", line 96, in _run_module_code
    _run_code(code, mod_globals, init_globals,
  File "D:\Programming\Softwares\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "d:\Programming\Softwares\Python\Projects\Bonk!\manifest-check.py", line 5, in <module>
    manifest = winmanifest.ManifestFromResFile('D:\\Programming\\Softwares\\Python\\Projects\\Bonk!\\dist\\Bonk!.exe')
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 942, in ManifestFromResFile
    raise InvalidManifestError("No matching manifest resource found in '%s'" % filename)
PyInstaller.utils.win32.winmanifest.InvalidManifestError: No matching manifest resource found in 'D:\Programming\Softwares\Python\Projects\Bonk!\dist\Bonk!.exe'
```

**Comment by bwoodsend** [comment]
<s>How did you install Python? It looks like you have two in there and one of them is just a VSCode plugin?</s> Edit: Ignore that. You have a normal installation of Python but you ran it from VSCode so it'll be using a slightly customised `runpy` alternative. That shouldn't be an issue.

Can you upload that EXE then? You'll probably have to hide it in a zip file or GitHub will block it.

**Comment by rokm** [comment]
Looks like the exe doesn't contain the manifest after all. Which explains the ordinal 380 error, but raises a question why manifest is missing. Can you rebuild your program with added `--clean` flag to your pyinstaller command, and attach the resulting build log (the output printed to console during the build) here?

**Comment by Dave-J-69420** [comment]
> Looks like the exe doesn't contain the manifest after all. Which explains the ordinal 380 error, but raises a question why manifest is missing. Can you rebuild your program with added `--clean` flag to your pyinstaller command, and attach the resulting build log (the output printed to console during the build) here?

Ok.
```haskell
--Input
pyinstaller --clean --noconfirm --onefile --windowed --icon "D:/Programming/Softwares/Python/Projects/Bonk!/icon.ico" --add-data "D:/Programming/Softwares/Python/Lib/site-packages/panda3d;panda3d/" --add-data "D:/Programming/Softwares/Python/Lib/site-packages/panda3d-1.10.11.dist-info;panda3d-1.10.11.dist-info/" --add-data "D:/Programming/Softwares/Python/Lib/site-packages/direct;direct/" --add-data "D:/Programming/Softwares/Python/Lib/site-packages/ursina;ursina/" --add-data "D:/Programming/Softwares/Python/Lib/site-packages/ursina-4.1.1.dist-info;ursina-4.1.1.dist-info/" --paths "D:/Programming/Softwares/Python/Lib/site-packages/panda3d"  "D:/Programming/Softwares/Python/Projects/Bonk!/main.py"
```
```yaml
#Output
668 INFO: PyInstaller: 4.9
668 INFO: Python: 3.10.2
688 INFO: Platform: Windows-10-10.0.22000-SP0
689 INFO: wrote C:\Users\david\main.spec
718 INFO: UPX is not available.
719 INFO: Removing temporary files and cleaning cache in C:\Users\david\AppData\Local\pyinstaller
791 INFO: Extending PYTHONPATH with paths
['D:\\Programming\\Softwares\\Python\\Projects\\Bonk!',
 'D:\\Programming\\Softwares\\Python\\Lib\\site-packages\\panda3d']
2789 INFO: checking Analysis
2789 INFO: Building Analysis because Analysis-00.toc is non existent
2789 INFO: Initializing module dependency graph...
2882 INFO: Caching module graph hooks...
2954 INFO: Analyzing base_library.zip ...
13074 INFO: Processing pre-find module path hook distutils from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
13095 INFO: distutils: retargeting to non-venv dir 'D:\\Programming\\Softwares\\Python\\lib'
18441 INFO: Caching module dependency graph...
18799 INFO: running Analysis Analysis-00.toc
18872 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by D:\Programming\Softwares\Python\python.exe
19008 INFO: Analyzing D:\Programming\Softwares\Python\Projects\Bonk!\main.py
21723 INFO: Processing pre-find module path hook site from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-site.py'.
21737 INFO: site: retargeting to fake-dir 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\fake-modules'
28399 INFO: Processing module hooks...
28400 INFO: Loading module hook 'hook-pycparser.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
28418 INFO: Loading module hook 'hook-difflib.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
28428 INFO: Loading module hook 'hook-distutils.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
28429 INFO: Loading module hook 'hook-distutils.util.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
28433 INFO: Loading module hook 'hook-encodings.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
28570 INFO: Loading module hook 'hook-heapq.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
28585 INFO: Loading module hook 'hook-lib2to3.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
28999 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
29004 INFO: Loading module hook 'hook-pickle.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
29008 INFO: Loading module hook 'hook-PIL.Image.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
30160 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
30164 INFO: Loading module hook 'hook-PIL.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
30181 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
30184 INFO: Loading module hook 'hook-pkg_resources.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
31281 INFO: Processing pre-safe import module hook win32com from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
31367 WARNING: Hidden import "pkg_resources.py2_warn" not found!
31367 WARNING: Hidden import "pkg_resources.markers" not found!
31371 INFO: Loading module hook 'hook-setuptools.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
33150 INFO: Loading module hook 'hook-sysconfig.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
33156 INFO: Loading module hook 'hook-win32ctypes.core.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
33562 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
33565 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
33568 INFO: Loading module hook 'hook-xml.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
33569 INFO: Loading module hook 'hook-_tkinter.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
33857 INFO: checking Tree
33857 INFO: Building Tree because Tree-00.toc is non existent
33858 INFO: Building Tree Tree-00.toc
34380 INFO: checking Tree
34382 INFO: Building Tree because Tree-01.toc is non existent
34385 INFO: Building Tree Tree-01.toc
34528 INFO: checking Tree
34528 INFO: Building Tree because Tree-02.toc is non existent
34528 INFO: Building Tree Tree-02.toc
34537 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks'...
34592 INFO: Looking for ctypes DLLs
34717 INFO: Analyzing run-time hooks ...
34726 INFO: Including run-time hook 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
34761 INFO: Including run-time hook 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
34786 INFO: Including run-time hook 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
34801 INFO: Including run-time hook 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
34818 INFO: Including run-time hook 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
34835 INFO: Including run-time hook 'D:\\Programming\\Softwares\\Python\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
34866 INFO: Looking for dynamic libraries
38029 INFO: Looking for eggs
38030 INFO: Using Python library D:\Programming\Softwares\Python\python310.dll
38030 INFO: Found binding redirects:
[]
38041 INFO: Warnings written to C:\Users\david\build\main\warn-main.txt
38179 INFO: Graph cross-reference written to C:\Users\david\build\main\xref-main.html
38245 INFO: Appending 'datas' from .spec
39161 INFO: checking PYZ
39161 INFO: Building PYZ because PYZ-00.toc is non existent
39161 INFO: Building PYZ (ZlibArchive) C:\Users\david\build\main\PYZ-00.pyz
40681 INFO: Building PYZ (ZlibArchive) C:\Users\david\build\main\PYZ-00.pyz completed successfully.
40725 INFO: checking PKG
40726 INFO: Building PKG because PKG-00.toc is non existent
40726 INFO: Building PKG (CArchive) main.pkg
90770 INFO: Building PKG (CArchive) main.pkg completed successfully.
90878 INFO: Bootloader D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\bootloader\Windows-64bit\runw.exe
90879 INFO: checking EXE
90879 INFO: Building EXE because EXE-00.toc is non existent
90880 INFO: Building EXE from EXE-00.toc
90909 INFO: Copying bootloader EXE to C:\Users\david\dist\main.exe
91177 INFO: Copying icon to EXE
91178 INFO: Copying icons from ['D:\\Programming\\Softwares\\Python\\Projects\\Bonk!\\icon.ico']
Traceback (most recent call last):
  File "D:\Programming\Softwares\Python\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Programming\Softwares\Python\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Programming\Softwares\Python\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\building\build_main.py", line 793, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\building\build_main.py", line 725, in build
    exec(code, spec_namespace)
  File "C:\Users\david\main.spec", line 23, in <module>
    exe = EXE(pyz,
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\building\api.py", line 508, in __init__
    self.__postinit__()
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\building\api.py", line 607, in assemble
    icon.CopyIcons(self.name, self.icon)
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\utils\win32\icon.py", line 208, in CopyIcons
    return CopyIcons_FromIco(dstpath, [srcpath])
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\utils\win32\icon.py", line 148, in CopyIcons_FromIco
    for i, f in enumerate(icons):
  File "D:\Programming\Softwares\Python\lib\site-packages\PyInstaller\utils\win32\icon.py", line 115, in __init__
    file.seek(e.dwImageOffset, 0)
OSError: [Errno 22] Invalid argument
```

**Comment by rokm** [comment]
So your build is failing with icon-related error (is `D:/Programming/Softwares/Python/Projects/Bonk!/icon.ico` a valid .ico file?) and the executable you end up with is incomplete - not only it lacks the manifest, it does not contain your python program, either.

**Comment by Dave-J-69420** [comment]
> So your build is failing with icon-related error (is `D:/Programming/Softwares/Python/Projects/Bonk!/icon.ico` a valid .ico file?) and the executable you end up with is incomplete - not only it lacks the manifest, it does not contain your python program, either.

`icon.ico` is valid...

**Comment by rokm** [comment]
> > So your build is failing with icon-related error (is `D:/Programming/Softwares/Python/Projects/Bonk!/icon.ico` a valid .ico file?) and the executable you end up with is incomplete - not only it lacks the manifest, it does not contain your python program, either.
> 
> `icon.ico` is valid...

Can you attach it here, so I can take a look at it and see if I can reproduce the error with it?

**Comment by bwoodsend** [comment]
... and to make sure that it's not just a PNG mislabeled with a .ico suffix.

**Comment by Dave-J-69420** [comment]
> ... and to make sure that it's not just a PNG mislabeled with a .ico suffix.

Oh, so here's the problem. Thank you!

**Comment by Dave-J-69420** [comment]
> > > So your build is failing with icon-related error (is `D:/Programming/Softwares/Python/Projects/Bonk!/icon.ico` a valid .ico file?) and the executable you end up with is incomplete - not only it lacks the manifest, it does not contain your python program, either.
> > 
> > 
> > `icon.ico` is valid...
> 
> Can you attach it here, so I can take a look at it and see if I can reproduce the error with it?

The `main.py`?

**Comment by rokm** [comment]
> > > > So your build is failing with icon-related error (is `D:/Programming/Softwares/Python/Projects/Bonk!/icon.ico` a valid .ico file?) and the executable you end up with is incomplete - not only it lacks the manifest, it does not contain your python program, either.
> > > 
> > > 
> > > `icon.ico` is valid...
> > 
> > 
> > Can you attach it here, so I can take a look at it and see if I can reproduce the error with it?
> 
> The `main.py`?

No, the icon file. But if you already determined that it is actually a PNG with .ico suffix instead of real ICO file, then that's what is causing the error.
