### ISSUE TITLE
pyinstaller 2.0 failed when runing pyinstaller.py with static python 2.7 library

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#685]
**Original date**: 2013/03/18
**Original reporter**: *anonymous*

I have pyinstaller 2.0 installed, when runing pyinstaller MyScript

I got error pyhton library not found.

I found there is a ticket #420 on the patch for supporting static link python library.

but it only support for pyinstaller 1.5.1.  Is there a fix for pyinstaller 2.0?

**Comment by matysek** [comment]
We do not support statically linked python dll.
