### ISSUE TITLE
Windows only permission denied error writing to {appname}.exe.notanexecutable

### ISSUE THREAD

**Issue by bwoodsend** [pyinstaller/pyinstaller#6854]
### Discussed in https://github.com/orgs/pyinstaller/discussions/6848

<div type='discussions-op-text'>

<sup>Originally posted by **namgi-11health** May 25, 2022</sup>
I have an odd situation, so I want to share it 

I run it local I got this error msg.

```
File "c:\users\namgi.yoon\documents\simulator2.5\myenv\lib\site-packages\PyInstaller\building\api.py", line 605, in assemble
    self._copyfile(exe, build_name)
 File "c:\users\namgi.yoon\documents\simulator2.5\myenv\lib\site-packages\PyInstaller\building\api.py", line 789, in _copyfile
    with open(outfile, 'wb') as outfh:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\namgi.yoon\\Documents\\Simulator2.5\\dist\\Simulator2.5.exe.notanexecutable'
```

I felt odd because the script could create files in build/Simulator2.5 and dist folder and .spec but why is giving me permission denied..

```
# Step 1: copy the bootloader file, and perform any operations that need to be done prior to appending the PKG.
logger.info("Copying bootloader EXE to %s", build_name)
self._copyfile(exe, build_name)
os.chmod(build_name, 0o755)
```

It seems copyfile as Writing to a Binary File and then give permission 755 anyway

the issue was the an alternative suffix

```
# On Windows, we must never create a file with a .exe suffix that we then have to (re)write to (see #6467).
# Any intermediate/temporary file must have an alternative suffix.
build_name = self.name + '.notanexecutable' if is_win or is_cygwin else self.name
```
I change the suffix to ‘.namgi' then it’s working. Please get me why wasn't worked with '.notanexecutable' and worked '.namgi'</div>

**Comment by bwoodsend** [comment]
Ughh, this worries me. It seems that the same AV engine that caused #6467 is now targeting our dummy `.notanexectuable` suffix.

> I change the suffix to ‘.namgi' then it’s working. Please get me why wasn't worked with '.notanexecutable' and worked '.namgi'

_Because Windows is a very dumb operating system_ is the short answer...

I'm going to pin this issue to see if other people start having it too. If they do, then I guess that the next least unpractical solution would be to replace `'.notanexecutable'` with something dynamic like `uuid.uuid1().hex`.

**Comment by rokm** [comment]
What if we saved the temporary executable without any suffix?

**Comment by rokm** [comment]
Also, it seems that in onefile builds, we end up with `name.exe.notanexecutable` instead of `name.notanexecutable`...

**Comment by bwoodsend** [comment]
> What if we saved the temporary executable without any suffix?

That's an option too.

**Comment by bwoodsend** [comment]
Judging by the lack of people reporting this, presumably this isn't happening. Close this for now...
