### ISSUE TITLE
OSError: could not get source code

### ISSUE THREAD

**Issue by geoexploring** [pyinstaller/pyinstaller#6865]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ``5.1``
* Version of Python:  ``3.7.6``
* Platform:  ``win10``
* How you installed Python:  ``python.org``
* Did you also try this on another platform? Does it work there? ``Not tested on other platforms``

* try the latest development version, using the following command: ``Still have the same problem``

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

[Paddle](https://github.com/PaddlePaddle/Paddle) is a popular deep learning framework in China, especially for industrial applications, which is friendly, so using Pyinstaller to package Paddle is a common step.

Here is a [demo code](https://www.paddlepaddle.org.cn/documentation/docs/zh/api/paddle/jit/save_cn.html#daimashili) to reproduce Bug (The paddle version is [PaddlePaddle-gpu2.3.0](https://paddle-wheel.bj.bcebos.com/2.3.0/windows/windows-gpu-cuda10.2-cudnn7-mkl-avx/paddlepaddle_gpu-2.3.0-cp37-cp37m-win_amd64.whl), which is the latest edition) :
```python
# example 1: save layer
import numpy as np
import paddle
import paddle.nn as nn
import paddle.optimizer as opt

BATCH_SIZE = 16
BATCH_NUM = 4
EPOCH_NUM = 4

IMAGE_SIZE = 784
CLASS_NUM = 10

# define a random dataset
class RandomDataset(paddle.io.Dataset):
    def __init__(self, num_samples):
        self.num_samples = num_samples

    def __getitem__(self, idx):
        image = np.random.random([IMAGE_SIZE]).astype('float32')
        label = np.random.randint(0, CLASS_NUM - 1, (1, )).astype('int64')
        return image, label

    def __len__(self):
        return self.num_samples

class LinearNet(nn.Layer):
    def __init__(self):
        super(LinearNet, self).__init__()
        self._linear = nn.Linear(IMAGE_SIZE, CLASS_NUM)

    @paddle.jit.to_static
    def forward(self, x):
        return self._linear(x)

def train(layer, loader, loss_fn, opt):
    for epoch_id in range(EPOCH_NUM):
        for batch_id, (image, label) in enumerate(loader()):
            out = layer(image)
            loss = loss_fn(out, label)
            loss.backward()
            opt.step()
            opt.clear_grad()
            print("Epoch {} batch {}: loss = {}".format(
                epoch_id, batch_id, np.mean(loss.numpy())))

# 1. train & save model.

# create network
layer = LinearNet()
loss_fn = nn.CrossEntropyLoss()
adam = opt.Adam(learning_rate=0.001, parameters=layer.parameters())

# create data loader
dataset = RandomDataset(BATCH_NUM * BATCH_SIZE)
loader = paddle.io.DataLoader(dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    drop_last=True,
    num_workers=2)

# train
train(layer, loader, loss_fn, adam)

# save
path = "example_model/linear"
paddle.jit.save(layer, path)

```

Running the above code (`demo.py`) on the VSCode terminal is no problem.
Use `PyInstaller -D demo.py --distpath=./out` to package into `demo.exe`, and then run `demo.exe` in cmd, the following error will be reported:

```
C:\Users\admin\Desktop\Paddle\out\demo>demo.exe
W0602 12:33:46.781188   624 gpu_context.cc:278] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.6, Runtime API Version: 10.2
W0602 12:33:48.869580   624 gpu_context.cc:306] device: 0, cuDNN Version: 7.6.
Traceback (most recent call last):
  File "demo.py", line 72, in <module>
  File "demo.py", line 48, in train
  File "paddle\fluid\dygraph\layers.py", line 930, in __call__
  File "paddle\fluid\dygraph\layers.py", line 915, in _dygraph_call_func
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 384, in __call__
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 360, in __call__
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 436, in get_concrete_program
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 801, in __getitem__
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 790, in _build_once
  File "decorator.py", line 232, in fun
  File "paddle\fluid\wrapped_decorator.py", line 25, in __impl__
  File "paddle\fluid\dygraph\base.py", line 51, in __impl__
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 694, in from_func_spec
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 140, in convert_to_static
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 77, in convert_with_cache
  File "paddle\fluid\dygraph\dygraph_to_static\program_translator.py", line 104, in _convert
  File "paddle\fluid\dygraph\dygraph_to_static\utils.py", line 550, in func_to_source_code
  File "inspect.py", line 955, in getsourcelines
  File "inspect.py", line 786, in findsource
OSError: could not get source code
[8764] Failed to execute script 'demo' due to unhandled exception!
```

A similar problem occurs when packing PyTorch, Specific reference [pytorch # 1899](https://github.com/pytorch/vision/issues/1899) and [pyinstaller # 5673](https://github.com/pyinstaller/pyinstaller/issues/5673).

I think may need to rewrite '[@paddles.jit.to_static](https://github.com/PaddlePaddle/Paddle/blob/40a7e0ad43009976b2a7f79f1f909b659cdf56ef/python/paddle/fluid/dygraph/jit.py#L163)', but I haven't found a suitable solution as [pytorch # 1899](https://github.com/pytorch/vision/issues/1899).

**Comment by rokm** [comment]
In order to use JIT compilation that is used in deep learning frameworks such as `PyTorch` and `paddle`, you need to ensure that .py sources are collected. That's because PyInstaller collects only byte-compiled .pyc modules, which results in "could not get source code" errors when source code is requested.

In this particular case, since `@paddle.jit.to_static` decorator is used in the entry-point script (`demo.py`), you need to ensure that the script itself is also collected in the source form, for example by adding `--add-data demo.py;.` to your pyinstaller command.

This should take care of the source code error, but then you'll probably hit this problem: https://github.com/pyinstaller/pyinstaller/issues/5902#issuecomment-859121376. Brénainn submitted a PR to `paddle` to fix this, but it didn't get merged so if you want to use `paddle` with PyInstaller, you'll need to patch your local `paddle` copy.

**Comment by bwoodsend** [comment]
Consider this an open invitation to anyone who wishes to rebase https://github.com/PaddlePaddle/Paddle/pull/33543 and submit their own pull request. I gave up when it became apparent that the reason that they had such an enormous number of open pull requests is because they don't review them until CI has passed and their CI was broken so that hadn't passed for months. But that was a year ago - they might have fixed it by now 🤨...

#6290 is already open for the JIT detection so I'll close this in favour of that one.
