### ISSUE TITLE
ITK does not work in pyinstaller

### ISSUE THREAD

**Issue by Javi-r** [pyinstaller/pyinstaller#6868]
### Discussed in https://github.com/orgs/pyinstaller/discussions/6867

<div type='discussions-op-text'>

<sup>Originally posted by **Javi-r** June  3, 2022</sup>
This is the error:  AttributeError: module 'itk' has no attribute 'Image'  and  AttributeError: module 'itk' has no attribute 'GDCMSeriesFileNames'

This is my spec file:

from PyInstaller.utils.hooks import collect_submodules

hiddenimports += collect_submodules('vtkmodules')
hiddenimports += collect_submodules('pydicom')
hiddenimports += collect_submodules('itk')

block_cipher = None

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='app',
)</div>

**Comment by rokm** [comment]
Please provide either minimal code example that triggers the issue, or full error traceback. Otherwise, we have no means of discerning where the error was raised and why.

**Comment by rokm** [comment]
Although quickly looking at `itk` code, it seems to perform both lazy loading *and* expects to find the source .py files on the filesystem (and PyInstaller does not collect those...). 

So you can try adding this at the top of your spec:
```
from PyInstaller.utils.hooks import collect_submodules, collect_data_files

hiddenimports = []
datas = []

hiddenimports += collect_submodules('itk')
datas += collect_data_files('itk', include_py_files=True)
```

and then pass both `hiddenimports` and `datas` to `Analysis` via arguments with the same name.

**Comment by Javi-r** [comment]
Thank you very much this has worked for me
