### ISSUE TITLE
TKINTER GUI

### ISSUE THREAD

**Issue by coder606-ctrl** [pyinstaller/pyinstaller#6872]
Hey guys, so for my tkinter gui it is all black therefor i can't see any text!
I am a begginer in python so maybe its really simple but i do not know my code is:
from tkinter import *

root = Tk()

myLabel = Label(root, text="Hello World!")

myLabel.pack()

root.mainloop()

Please help me to fix this.

**Comment by rokm** [comment]
Without information about the OS, python version (and how you installed it - i.e., python.org, anaconda, etc.), and version of PyInstaller, there's no way we can try reproducing the problem...
