### ISSUE TITLE
in pyinstaller-5.1-py3-none-win_amd64.whl runw.exe and runw_d.exe are flagged as malicious by virustotal

### ISSUE THREAD

**Issue by sshilovsky** [pyinstaller/pyinstaller#6877]
https://www.virustotal.com/gui/file/12626a9f10192da9f3d67c3fc77ebb105662fa64063ecf2027cb46f4d139a5e2

https://www.virustotal.com/gui/file/c2397b5461b45b4332e12011d468c57f450f0ca0fb4aaa04d45ca7698ee9967e

This results in generated files being flagged as well.

**Comment by Legorooj** [comment]
Unfortunately, due to the fact that some people use PyInstaller to build malicious programs, our bootloaders get flagged. Signing your program will fix this issue.
