### ISSUE TITLE
Encountering Fatal Python Error when running app; failing to get random numbers to initialize Python

### ISSUE THREAD

**Issue by raymond130** [pyinstaller/pyinstaller#6878]
Hi there, I checked with the mailing group and searched around the internet but was told to post this here. My original question is below:

In this case, my python program is compiling fine and running fine when executed through a command line or batch file or even a test program. However, when trying to integrate it into a larger application it simply won't start. I downloaded DebugView to see what was happening because it was obvious the exe was opening but not running.

What I found was that as the internal python interpreter was unpacked and started, it ran into a fatal Python error: failed to get random numbers to initialize Python.

Has anyone run into this before? I think it is happening because we are running this app through a custom executable framework that changes some of the env variables. Realistically I am wondering if I can write a hook to set this env variable back to what it should be before the python interpreter starts.

---> end original question

It seems like what has to be changed is the SYSTEMROOT environment variable, before the interpreter is started.

I tried to write a hook with the following text: 	os.environ['SYSTEMROOT'] = 'C:\Windows'

However since hooks are run after the python interpreter is initialized, this hasn't worked for me.

I'm not exactly sure what to do - we're trying to get this to run in one file without a little DLLs as are necessary, and since we run it through a larger program I don't think it's possible to start it via batch file.

Thanks for any help!

### Context information (for bug reports)

Here is the compile command I'm running:

pyinstaller --onefile --paths C:\Users\braymond\Anaconda3\DLLs --noconsole --debug=all program.py

I should mention that this program runs through command line and batch file just fine, it also runs alright in our test program which just calls process.start(). The issue seems to be with the specific way this larger program calls the executable. Already tried running without UPX but it didn't make a difference.

* Output of `pyinstaller --version`: ```5.1```
* Version of Python:  3.9.12
* Platform:  Windows (English)
* How you installed Python:  Anaconda Installation
* Did you also try this on another platform? Does it work there?  - No, this program is meant to be windows-only

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
Will do, going to make a simple hello world program
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
[35344] Fatal Python error: 
[35344] failed to get random numbers to initialize Python
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Well, I can confirm that setting `SYSTEMROOT` to something else than `c:\Windows` (e.g., just `c:\`) results in `Fatal Python error: _Py_HashRandomization_Init: failed to get random numbers to initialize Python`.

That said, this obviously has nothing to do with PyInstaller itself, but rather with your framework and it messing up the runtime environment for the spawned subprocess.

Trying to restore the environment within the subprocess itself is a rather moot task, because the lack of proper `SYSTEMROOT` may be subtly influencing other parts of the bootloader code even before python interpreter is launched. So you should sort out the environment variables before you spawn the subprocess; most of process-spawning functions allow you to pass custom environment variables that are applied only to that subprocess...
