### ISSUE TITLE
Specifying Windows Version Resources from within spec files

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#688]
**Original date**: 2013/03/20
**Original reporter**: _bill AND tutts DOT org_

Currently PyInstaller supports file names that ONLY contain VSVersionInfo structures in Python notation.

This makes it more complicated to have the resource information be dependant upon custom logic. (Sort of like the attached versionResource.py file)

I've also attached a patch to also allow supplying the VSVersionInfo instance instead of a file name to the version keyword argument.

Here's how using this might look using the attached versionResource.py file:

```
import versionResource
from PyInstallerHelper import *


a = Analysis(['startCollectionUI.py'],
             pathex=None,
             hiddenimports=HiddenImports(),
             hookspath=None, excludes=excludePure)

a.datas += [('7z.dll', '7z.dll', 'DATA')]
a.datas += [('7z.exe', '7z.exe', 'DATA')]
a.datas += [('collection.xml', 'collection.xml', 'DATA')]
a.datas += [('License.html', 'License.html', 'DATA')]

RemoveUninterestingEncodings(a.pure)

pyz = PYZ(a.pure)

exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name=os.path.join('dist', 'CollectionUI.exe'),
          debug=False,
          strip=None,
          upx=False,
          console=False,
          version=versionResource.UIVersion)

```

**Comment by htgoebel** [comment]
This feature-request if four years old now. Nobody worked on ti, so I'm closing it. If somebody wants to implement this, feel free to provide a pull-request.
