### ISSUE TITLE
Error running onefile executable created by PyInstaller under Portable Python

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#689]
**Original date**: 2013/03/21
**Original reporter**: *maverick*

I have been using PyInstaller for a while and have been very happy with it. However, after I upgraded from Portable Python 2.7.2 to 2.7.3 (I don't think it uses Active Python) all of my newly-created single-file executables would not run, giving instead the error:

"An application has made an attempt to load the C runtime library incorrectly. Please contact the application's support team for more information."

I probed a little deeper and discovered that this was due to the C runtime library not seeing a manifest. Using ArchiveViewer the manifest seems to be correctly contained in the file, but this was not the case using a resource editor. I was able to fix the problem by building the executable using the onedir option instead of onefile, then simply moving just the manifest to the directory containing the single-file executable, which allowed it to work. So it seems to me that this would be an easy fix for you; instead of embedding the manifest in the archive, try embedding it into the exe file itself as a resource (without compression). Based on my testing I think this should work.

Thank you for the good work.

**Comment by matysek** [comment]
PortablePython is not developed anymore and any of the following replacement is recommended (Not sure if PyInstaller works with them or not):
* https://python-xy.github.io/
* https://winpython.github.io/
* https://store.continuum.io/cshop/anaconda/
* https://www.pythonanywhere.com/
