### ISSUE TITLE
Linux executable much larger than Windows and macOS

### ISSUE THREAD

**Issue by Montspy** [pyinstaller/pyinstaller#6893]
I am freezing a GUI app (based on wxPython) for 3 targets: linux, windows and macOS using this command
```
pyinstaller --onefile --windowed main.py
```

I noticed that Linux exectuables are **much** bigger than their windows and macOS equivalents
Linux: ~109MB
Windows: ~27MB
macOS: ~17MB

This is the same observation as issue #4494. That particular issue should have been solved many versions ago. Is it back or is this expected?

Trying to dig down on why, I used `archive_viewer.py` on the Linux and Windows executables (truncated to 10 largest sections):

You can clearly see that the cpython core is taking ~71MB on Linux but less than 3MB on Windows.

### Windows
<html><body>
<google-sheets-html-origin>

pos | length | length (MB) | uncompressed | iscompressed | type | name
-- | -- | -- | -- | -- | -- | --
2301794 | 9155287 | 8.731162071 | 34369888 | 1 | b | libopenblas.WCDJNK7YVMPZQ2ME2ZZHJJRJ3JIKNDB7.gfortran-win_amd64.dll
23794861 | 3666272 | 3.496429443 | 3666272 | 0 | z | PYZ-00.pyz
20117030 | 2969904 | 2.832321167 | 8650752 | 1 | b | wxmsw315u_core_vc140_x64.dll
16491127 | 2223740 | 2.120723724 | 8142848 | 1 | b | wx\_core.cp39-win_amd64.pyd
13634511 | 1966215 | 1.875128746 | 4457488 | 1 | b | python39.dll
987673 | 1295853 | 1.235821724 | 3399200 | 1 | b | libcrypto-1_1.dll
19075752 | 1041278 | 0.9930400848 | 2781184 | 1 | b | wxbase315u_vc140_x64.dll
11760222 | 871374 | 0.8310070038 | 2768896 | 1 | b | numpy\core\_multiarray_umath.cp39-win_amd64.pyd
15666372 | 405761 | 0.3869638443 | 1119760 | 1 | b | unicodedata.pyd
16155042 | 336085 | 0.3205156326 | 1296384 | 1 | b | wx\_adv.cp39-win_amd64.pyd

</body>
</html>

### Linux
<html><body>
<google-sheets-html-origin>

pos | length | length (MB) | uncompressed | iscompressed | type | name
-- | -- | -- | -- | -- | -- | --
32426167 | 74228373 | 70.78969288 | 190105552 | 1 | b | wx/_core.cpython-38-x86_64-linux-gnu.so
24713285 | 7712882 | 7.355577469 | 21339440 | 1 | b | wx/_adv.cpython-38-x86_64-linux-gnu.so
106654540 | 5458869 | 5.205983162 | 14471192 | 1 | b | wx/_html.cpython-38-x86_64-linux-gnu.so
20420166 | 3343876 | 3.188968658 | 10788096 | 1 | b | libwx_gtk3u_core-3.1.so.5
9621671 | 2887043 | 2.753298759 | 8037912 | 1 | b | libgtk-3.so.0
14907396 | 2076228 | 1.980045319 | 5449112 | 1 | b | libpython3.8.so.1.0
112884349 | 1889478 | 1.80194664 | 1889478 | 0 | z | PYZ-00.pyz
4762389 | 1313215 | 1.252379417 | 2954080 | 1 | b | libcrypto.so.1.1
19095351 | 1194314 | 1.138986588 | 3312824 | 1 | b | libwx_baseu-3.1.so.5
2406895 | 756941 | 0.7218751907 | 1293928 | 1 | b | libX11.so.6

</body>
</html>

Thanks

**Comment by rokm** [comment]
> You can clearly see that the cpython core is taking ~71MB on Linux but less than 3MB on Windows.

If `wx` binaries (shared libraries / python extensions) and their dependencies are larger on linux that Windows / macOS, there's nothing we can really do about it. We just collect them as they are.

**Comment by rokm** [comment]
How did you install wxPython on linux? On my Fedora box, the `/usr/lib64/python3.10/site-packages/wx/_core.cpython-310-x86_64-linux-gnu.so` that comes from distribution's RPM is 12 MB in size...

**Comment by rokm** [comment]
But installing `wx` on linux via `pip install wxpython` indeed builds everything from source and presumably with debug symbols enabled, because `_core.cpython-38-x86_64-linux-gnu.so` ends up being 156 MB. 

You can either try stripping (only) debug symbols from those .so files in your `wx` installation (using `strip --strip-debug <filename>`). 

Or, PyInstaller also supports [`--strip`](https://pyinstaller.org/en/stable/usage.html#cmdoption-s) which automatically runs `strip` on collected binaries. But I think its default options are a bit more aggressive, so I'd recommend you to manually use `strip --strip-debug` on the offending `wx` binaries before running PyInstaller.

Either way, that's not really our issue. If anything, `wxpython` should not build itself with debug symbols enabled.
