### ISSUE TITLE
ctypes.cdll.LoadLibrary path string format bug (solved)

### ISSUE THREAD

**Issue by Yeb02** [pyinstaller/pyinstaller#6915]
Hi, 

I encountered a tiny bug when compiling with Python 3.8 on Windows 10, without flags. The two following lines of code are mutually exclusive depending on the use case. The first one works if and only if the script is ran by python in a console, the second only works when compiling with pyinstaller.

```
ic = ctypes.cdll.LoadLibrary("./tisgrabber_x64.dll")   # To use when running with python
ic = ctypes.cdll.LoadLibrary("tisgrabber_x64.dll")     # To use when compiling with pyinstaller
```

This is the pyinstaller error when compiling with python syntax:

**96071 INFO: Looking for ctypes DLLs
96147 WARNING: Ignoring ./tisgrabber_x64.dll imported from C:\PATH\panoramapp.py - only basenames are supported with ctypes imports!**

This is the python error when using pyinstaller syntax:

**FileNotFoundError: Could not find module 'tisgrabber_x64.dll' (or one of its dependencies). Try using the full path with constructor syntax.**

**Comment by bwoodsend** [comment]
That first error is not an error; it's just a useless warning. `ctypes.cdll.LoadLibrary("./tisgrabber_x64.dll")` will fail in Python or PyInstaller if you change your working directory. You should reference it relative to `__file__` (see [docs](https://pyinstaller.org/en/stable/runtime-information.html#using-file)). Then you'll probably need to `--add-data` that file (again see that page) to get PyInstaller to collect it.

**Comment by Yeb02** [comment]
It may be just a warning , but the .exe would not start when using the python-compatible code at compile time. (A prompt appears for a fraction of a second, 2 or 3 lines are written, and then it vanishes)
Since I make extensive use of this dll in my python code, it probably is expected behaviour that  ```WARNING: Ignoring ./tisgrabber_x64.dll``` renders the .exe unusable.
