### ISSUE TITLE
I am getting Permission denied error when using it in python script

### ISSUE THREAD

**Issue by furkanyalcinz** [pyinstaller/pyinstaller#6917]
I am using pyinstaller from code like this:

import os
os.system('cmd /k "pyinstaller --onefile main.py --uac-admin"')

when I run the code I am getting an error like below:

71 INFO: PyInstaller: 4.9
71 INFO: Python: 3.10.5
88 INFO: Platform: Windows-10-10.0.22000-SP0
90 INFO: wrote C:\Users\furka\Desktop\test\main.spec
92 INFO: UPX is not available.
105 INFO: Extending PYTHONPATH with paths
['C:\\Users\\furka\\Desktop\\test']
365 INFO: checking Analysis
365 INFO: Building Analysis because Analysis-00.toc is non existent
365 INFO: Initializing module dependency graph...
377 INFO: Caching module graph hooks...
392 INFO: Analyzing base_library.zip ...
4029 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
4033 INFO: distutils: retargeting to non-venv dir 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib'
5296 INFO: Caching module dependency graph...
5417 INFO: running Analysis Analysis-00.toc
5450 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\furka\AppData\Local\Programs\Python\Python310\python.exe
5629 INFO: Analyzing C:\Users\furka\Desktop\test\main.py
5640 INFO: Processing module hooks...
5641 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5643 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5645 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5647 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5747 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5749 INFO: Loading module hook 'hook-lib2to3.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5780 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5783 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5786 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5787 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5788 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
5898 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks'...
6030 INFO: checking Tree
6030 INFO: Building Tree because Tree-00.toc is non existent
6031 INFO: Building Tree Tree-00.toc
6097 INFO: checking Tree
6097 INFO: Building Tree because Tree-01.toc is non existent
6097 INFO: Building Tree Tree-01.toc
6200 INFO: checking Tree
6201 INFO: Building Tree because Tree-02.toc is non existent
6201 INFO: Building Tree Tree-02.toc
6237 INFO: Looking for ctypes DLLs
6252 INFO: Analyzing run-time hooks ...
6256 INFO: Including run-time hook 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
6260 INFO: Including run-time hook 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
6262 INFO: Including run-time hook 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
6266 INFO: Including run-time hook 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
6274 INFO: Including run-time hook 'C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
6280 INFO: Looking for dynamic libraries
6460 INFO: Looking for eggs
6460 INFO: Using Python library C:\Users\furka\AppData\Local\Programs\Python\Python310\python310.dll
6461 INFO: Found binding redirects:
[]
6465 INFO: Warnings written to C:\Users\furka\Desktop\test\build\main\warn-main.txt
6526 INFO: Graph cross-reference written to C:\Users\furka\Desktop\test\build\main\xref-main.html
6564 INFO: checking PYZ
6564 INFO: Building PYZ because PYZ-00.toc is non existent
6565 INFO: Building PYZ (ZlibArchive) C:\Users\furka\Desktop\test\build\main\PYZ-00.pyz
6948 INFO: Building PYZ (ZlibArchive) C:\Users\furka\Desktop\test\build\main\PYZ-00.pyz completed successfully.
6980 INFO: checking PKG
6981 INFO: Building PKG because PKG-00.toc is non existent
6981 INFO: Building PKG (CArchive) main.pkg
9258 INFO: Building PKG (CArchive) main.pkg completed successfully.
9311 INFO: Bootloader C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
9312 INFO: checking EXE
9312 INFO: Building EXE because EXE-00.toc is non existent
9313 INFO: Building EXE from EXE-00.toc
9313 INFO: Copying bootloader EXE to C:\Users\furka\Desktop\test\dist\main.exe
9389 INFO: Copying icon to EXE
9390 INFO: Copying icons from ['C:\\Users\\furka\\AppData\\Local\\Programs\\Python\\Python310\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
9488 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
9489 INFO: Writing RT_ICON 1 resource with 3752 bytes
9489 INFO: Writing RT_ICON 2 resource with 2216 bytes
9490 INFO: Writing RT_ICON 3 resource with 1384 bytes
9490 INFO: Writing RT_ICON 4 resource with 37019 bytes
9490 INFO: Writing RT_ICON 5 resource with 9640 bytes
9491 INFO: Writing RT_ICON 6 resource with 4264 bytes
9491 INFO: Writing RT_ICON 7 resource with 1128 bytes
9495 INFO: Copying 0 resources to EXE
9496 INFO: Emedding manifest in EXE
9496 INFO: Updating manifest in C:\Users\furka\Desktop\test\dist\main.exe
9595 INFO: Updating resource type 24 name 1 language 0
9606 INFO: Appending PKG archive to EXE
Traceback (most recent call last):
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 124, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\__main__.py", line 58, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 793, in main  
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 725, in build 
    exec(code, spec_namespace)
  File "C:\Users\furka\Desktop\test\main.spec", line 23, in <module>
    exe = EXE(pyz,
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\api.py", line 508, in __init__     
    self.__postinit__()
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 155, in __postinit__
    self.assemble()
  File "C:\Users\furka\AppData\Local\Programs\Python\Python310\lib\site-packages\PyInstaller\building\api.py", line 740, in assemble     
    with open(self.name, 'ab') as outf:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\furka\\Desktop\\test\\dist\\main.exe'

Can you help me?

**Comment by rokm** [comment]
This looks like your anti-virus program interfering with the build (i.e., locking access to the file between PyInstaller's modification steps).

**Comment by furkanyalcinz** [comment]
> 

I am not using any antivirus program except windows defender. Should I close it?

**Comment by rokm** [comment]
Yeah, either try disabling Windows Defender, or try upgrading to PyInstaller 4.10 or 5.1, to see if #6629 makes any difference (based on discussion around #6467).

**Comment by furkanyalcinz** [comment]
> Yeah, either try disabling Windows Defender, or try upgrading to PyInstaller 4.10 or 5.1, to see if #6629 makes any difference (based on discussion around #6467).

Thank you for your help. When I am updating version 5.1 the problem was solved.
