### ISSUE TITLE
DLL packaging problem under Windows 10 PySide6 6.3 (works fine under PySide6 6.2)

### ISSUE THREAD

**Issue by jamesbcd** [pyinstaller/pyinstaller#6924]
## Description of the issue
When building on Windows, using PySide6 6.3 or later, the packaged app fails to run, popping up an "Unhandled exception in script" dialog, with the error:
"ImportError: DLL load failed while importing QtCore: The specified module could not be found."

The error does not occur when packaging with PySide 6.2.4.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.1```
* Version of Python: Python 3.10.5
* Platform: Windows-10-10.0.19044-SP0
* How you installed Python: Windows installer from python.org/downloads
* Did you also try this on another platform? Does it work there?
Yes, the build works fine on macOS 10.14

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

Tried this, but it made no difference.

The pyinstaller output suggests that some Microsoft runtime DLLs from Shiboken are not being packaged:

54847 INFO: Looking for dynamic libraries
1080 WARNING: lib not found: Qt6Pdf.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\imageformats\qpdf.dll
1111 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\tls\qcertonlybackend.dll
1166 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\tls\qopensslbackend.dll1208 WARNING: lib not found: api-ms-win-shcore-scaling-l1-1-1.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\platforms\qwindows.dll
1215 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\platforms\qwindows.dll
1339 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\tls\qschannelbackend.dll
1444 WARNING: lib not found: api-ms-win-shcore-scaling-l1-1-1.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\platforms\qdirect2d.dll
1453 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\platforms\qdirect2d.dll1513 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\plugins\networkinformation\qnetworklistmanager.dll
1706 WARNING: lib not found: MSVCP140_2.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\QtGui.pyd
1736 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\QtGui.pyd
1782 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\QtWidgets.pyd
1820 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\QtCore.pyd
1852 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\QtNetwork.pyd
1976 WARNING: lib not found: MSVCP140_1.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Gui.dll
1988 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Gui.dll
2013 WARNING: lib not found: MSVCP140_2.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Gui.dll
2091 WARNING: lib not found: MSVCP140_1.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Core.dll
2103 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Core.dll
2151 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Network.dll
2219 WARNING: lib not found: MSVCP140_1.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Widgets.dll
2235 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Widgets.dll
2290 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6VirtualKeyboard.dll
2365 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Qml.dll
2472 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\lib\site-packages\PySide6\pyside6.abi3.dll
2581 WARNING: lib not found: MSVCP140_1.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Quick.dll
2594 WARNING: lib not found: MSVCP140.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Quick.dll
2611 WARNING: lib not found: MSVCP140_2.dll dependency of C:\JamesWorkArea\Code\multiscript\venv3.10\Lib\site-packages\PySide6\Qt6Quick.dll

**Comment by rokm** [comment]
Hmm... looks like`PySide6` 6.3.x moved the bundled VC runtime DLLs from `PySide6` directory into `shiboken6` one, and our library search fails to find them there. 

I suppose the most sure-fire way to work around this is to ensure that VC runtime is installed on your build system, so the DLLs end up collected from there. Or manually copying them back from `shiboken6` into `PySide6`.

Long-term, we'll have to check if we can make our library search on Windows a bit smarter, accounting for search paths added via `PATH` and `AddDllDirectory`.

**Comment by rokm** [comment]
FWIW, having VC runtime DLLs in `shiboken6` instead `PySide6` directory also seems to break `PySide6` 6.3.x under python 3.7 on Windows systems without VC runtime installed (i.e., without PyInstaller involved); the `os.add_dll_directory()` is not available in that python version and therefore dynamic DLL search path is not set correctly.

**Comment by jamesbcd** [comment]
Thank-you, that patch works really well! Thanks for the super-fast and effective help!

**Comment by skrynnik** [comment]
Man, you are legend, thank you.
