### ISSUE TITLE
pyinstaller dist .app Unable to run

### ISSUE THREAD

**Issue by 18237634625** [pyinstaller/pyinstaller#6941]
macOS 12.3.1
python2.7.15
pyinstaller3.6

Pyinstaller can package properly。but Test. app in dist cannot run。test  exec file Running normally。

pyinstaller -F -w test.py

The test.py file has only one line print(' Hello word ')

**Comment by rokm** [comment]
App bundles on macOS don't have a console, so a program consisting of `print(' Hello word ')` will just start and quietly exit...

That said, we don't support old versions of PyInstaller nor python2.
