### ISSUE TITLE
Add capability of specifying additional dependency resources to include

### ISSUE THREAD

**Issue by chaslain** [pyinstaller/pyinstaller#6955]
**Is your feature request related to a problem? Please describe.**
I am unable to create an installer for projects that utilize certain google dependencies because these dependencies require json files to be present within the dependency folder.

**Describe the solution you'd like**
An extra command line flag to include all files in the distribution, or files matching a pattern- or provide a file similar to .gitignore that allows you to specify patterns of files to include in addition to the project.

**Describe alternatives you've considered**
Moving the files manually into the finished directory as part of the build process, which doesn't work.

**Additional context**
You can view this project for context on what I am trying to make work with pyinstaller:
https://github.com/AlanHeckinJohnston/bc-tool

**Comment by rokm** [comment]
Sounds like what you're looking for is [`--collect-data <pkg_name>`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-data) command-line switch or using [`collect_data_files()`](https://pyinstaller.org/en/stable/hooks.html#PyInstaller.utils.hooks.collect_data_files) in your .spec file or custom hook. The collection is based on the package name (as opposed to distribution one), though.
