### ISSUE TITLE
GTK3 MSYS2 ImportError: Typelib file for namespace 'freetype2', version '2.0' not found.

### ISSUE THREAD

**Issue by MrPancakes39** [pyinstaller/pyinstaller#6957]
## Description of the issue

Looks like pyinstaller forgets to package freetype2 with the other libraries causing gi to fail importing it.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.2```
* Version of Python: ```Python 3.10.5```
* Platform: Windows 11 English
* Used MSYS2 with "MSYS2 MINGW 64-bit" enviroment
* Used the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
* [X] Started with clean installation
* [X] Used the latest development version

### A minimal example program which shows the error
```
# test.py

import gi

gi.require_version("Gtk", "3.0")
from gi.repository import Gtk

print("Hello I'm a Test")
```

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "gi/importer.py", line 142, in load_module
  File "gi/module.py", line 257, in get_introspection_module
  File "gi/module.py", line 109, in __init__
gi.RepositoryError: Typelib file for namespace 'freetype2', version '2.0' not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 7, in <module>
  File "gi/importer.py", line 144, in load_module
ImportError: Typelib file for namespace 'freetype2', version '2.0' not found
[13600] Failed to execute script 'main' due to unhandled exception!
```

**Comment by rokm** [comment]
This is going to be fixed by #6951, which adds a hook for `gi.repository.freetype2`. Looks like the typelib of the latest version of `HarfBuzz` (which is now also available in msys2/mingw64) depends on `freetype2` typelib.
