### ISSUE TITLE
pip install pyinstaller==3.6 fail

### ISSUE THREAD

**Issue by 18237634625** [pyinstaller/pyinstaller#6961]
python2.7.12
windows10 x64

```

C:\Users\admin>pip install pyinstaller==3.6
Collecting pyinstaller==3.6
  Using cached https://files.pythonhosted.org/packages/3c/c9/c3f9bc64eb11eee6a824686deba6129884c8cbdf70e750661773b9865ee0/PyInstaller-3.6.tar.gz
Requirement already satisfied: setuptools in c:\python27\lib\site-packages (from pyinstaller==3.6)
Collecting altgraph (from pyinstaller==3.6)
  Using cached https://files.pythonhosted.org/packages/84/3f/1a5c9bef54cac9bf41edd6f4aaf61cd52ed578e10ccc607e0278012cb4a5/altgraph-0.17.2-py2.py3-none-any.whl
Collecting dis3 (from pyinstaller==3.6)
  Using cached https://files.pythonhosted.org/packages/9c/5c/4a4a2802f10f558018413990a58fd3dd7ed1eb48e6de7266334c2489bad6/dis3-0.1.3-py2-none-any.whl
Collecting pywin32-ctypes>=0.2.0 (from pyinstaller==3.6)
  Using cached https://files.pythonhosted.org/packages/9e/4b/3ab2720f1fa4b4bc924ef1932b842edf10007e4547ea8157b0b9fc78599a/pywin32_ctypes-0.2.0-py2.py3-none-any.whl
Collecting pefile>=2017.8.1 (from pyinstaller==3.6)
  Using cached https://files.pythonhosted.org/packages/f9/1e/fc4fac0169d16a98577809400bbcfac8ad1900fa792184327b360ea51fc6/pefile-2021.5.13.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admin\appdata\local\temp\pip-build-u4swlf\pefile\setup.py", line 86, in <module>
        long_description = "\n".join(_read_doc().split('\n')),
      File "c:\users\admin\appdata\local\temp\pip-build-u4swlf\pefile\setup.py", line 30, in _read_doc
        tree = ast.parse(f.read())
      File "C:\Python27\lib\ast.py", line 37, in parse
        return compile(source, filename, mode, PyCF_ONLY_AST)
      File "<unknown>", line 3789
        f'Export directory contains more than 10 repeated entries '
                                                                  ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admin\appdata\local\temp\pip-build-u4swlf\pefile\
You are using pip version 9.0.1, however version 22.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

C:\Users\admin>
```

I execute any command related to pip install, and the same error as above will appear

I tried the solutions on the internet but again it didn't work **python -m pip install --upgrade pip**

```



C:\Users\admin>python -m pip install --upgrade pip
Collecting pip
  Using cached https://files.pythonhosted.org/packages/4b/b6/0fa7aa968a9fa4ef63a51b3ff0644e59f49dcd7235b3fd6cceb23f202e08/pip-22.1.2.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\admin\appdata\local\temp\pip-build-hh3h4j\pip\setup.py", line 7
        def read(rel_path: str) -> str:
                         ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in c:\users\admin\appdata\local\temp\pip-build-hh3h4j\pip\
You are using pip version 8.1.1, however version 22.1.2 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.

```
my pip version：

```
C:\Users\admin>pip --version
pip 9.0.1 from c:\python27\lib\site-packages\pip-9.0.1-py2.7.egg (python 2.7)

C:\Users\admin>

```

**Comment by rokm** [comment]
The errors you are getting are not coming from PyInstaller, but rather from `pefile` (where the version you are trying to install is using f-strings that are not available in python 2.7) and from `pip` (where the version you are trying install is using type annotations that are also not available in python 2.7). So if you want to use python 2.7, you will need to find the last version of those packages that still support python 2.7, and install that version.

Either way, we do not provide support for old pyinstaller versions, and we do not support python 2.7, so you are on your own.

**Comment by 18237634625** [comment]
@rokm 
> The errors you are getting are not coming from PyInstaller, but rather from `pefile` (where the version you are trying to install is using f-strings that are not available in python 2.7) and from `pip` (where the version you are trying install is using type annotations that are also not available in python 2.7). So if you want to use python 2.7, you will need to find the last version of those packages that still support python 2.7, and install that version.
> 
> Either way, we do not provide support for old pyinstaller versions, and we do not support python 2.7, so you are on your own.

**So if you want to use python 2.7, you will need to find the last version of those packages that still support python 2.7, and install that version.**

Thanks, what is the version you are talking about that supports python2.7! pyinstaller? I read the version support on the official website, I am using pyinstaller==3.6 which supports python2.7.

Or do you mean let me find the last version of `pefile` and `pip` that supports python2.7?

**Comment by rokm** [comment]
> I am using pyinstaller==3.6 which supports python2.7

Yes, but *we* do not offer support for PyInstaller 3.x (or even 4.x, for that matter) anymore, so there is no point in opening issues against those versions.

> Or do you mean let me find the last version of `pefile` and `pip` that supports python2.7?

Yes - you need to manually install compatible version of `pefile`, then try reinstalling pyinstaller 3.6.

**Comment by 18237634625** [comment]
@rokm 
> Yes, but _we_ do not offer support for PyInstaller 3.x (or even 4.x, for that matter) anymore, so there is no point in opening issues against those versions.
> 
> > Or do you mean let me find the last version of `pefile` and `pip` that supports python2.7?
> 
> Yes - you need to manually install compatible version of `pefile`, then try reinstalling pyinstaller 3.6.


Thanks

It's amazing

Finally I tried`pip install Pyinstaller==3.0` and it worked.

As for the specific reason, I don't know. It can only be attributed to the direct compatibility problem of the version
