### ISSUE TITLE
Failed to get ANSI buffer size(WideCharToMultiByte: 参数错误。 )Failed to convert pyhome to ANSI (invalid multibyte string)

### ISSUE THREAD

**Issue by 18237634625** [pyinstaller/pyinstaller#6968]
Hi handsome

Welcome to the PyInstaller issue tracker! Before creating an issue, please heed the following:

python2.7.12
windows10 x64
pyinstaller3.0

I packaged successfully and generated .exe

Runs on my own computer with no errors

I sent the .exe to the customer for use, and the error was reported when I opened it:

client computer：windows10  x64

```
Failed to get ANSI buffer size(WideCharToMultiByte: 参数错误。
)Failed to convert pyhome to ANSI (invalid multibyte string)

```

**Comment by rokm** [comment]
We do not support pyinstaller 3.x nor python 2.7 anymore.
