### ISSUE TITLE
after build python code exe not working ahk in windows machine

### ISSUE THREAD

**Issue by pamraman** [pyinstaller/pyinstaller#6969]
## Description of the issue
i have made one python code and from that i am finding windows process id usin ahk library and then activating that windows and performing AHK keys operation.
python code is working well without pyinstaller. if i build exe using pyinstaller then ahk is not working.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.2```
* Version of Python: 3.10.1
* Platform: Windows (en)
* How you installed Python: pyenv
* Did you also try this on another platform? Does it work there?  : No. we only need for windows so not tried for other platform

### Stacktrace / full error message
Its not giving any error and also not activating window using AHK.

### Sample code is working fine without pyinstaller but not worked after build this code using pyinstaller

```
from ahk import AHK
from ahk.window import Window

ahk = AHK()
win = ahk.active_window       

#win = list(ahk.windows()) 
win1 = Window(ahk, ahk_id = "0x20043c")
win1.activate()
# print('win id updated')
```

**Comment by rokm** [comment]
Is it listing any windows with `ahk.windows()` at all?

The `ahk` package has data files (ahk templates) that need to be collected. And you also need to ensure that `AutoHotKey.exe` is collected.

So you need to get the path to the `AutoHotKey.exe`, by running `where AutoHotKey.exe`.

Then add the following command-line switches to your PyInstaller command: `--collect-data ahk --add-binary c:\path\to\AutoHotKey.exe;.`.

And, at the start of your program, before you import `ahk`, add the following:
```python
import os
import sys
if getattr(sys, 'frozen', False):
    os.environ['AHK_PATH'] = os.path.join(sys._MEIPASS, 'AutoHotKey.exe')
```
