### ISSUE TITLE
Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception: No module named 'os'

### ISSUE THREAD

**Issue by VERISBABY** [pyinstaller/pyinstaller#6972]
## Description of the issue
I compiled .py files using pyinstaller but when i open my compiled .exe file, it shows a error widget - Unhandled exception in script. I have tried the ways of adding os to '`--hidden import`', moving 'import os' to the first line of .py files, adding `--path` and even copying the os file from the python310 source folder to my directory that need to compile but still not working!

### Context information (for bug reports)
* Output of `pyinstaller --version`: ```5.2```
* Version of Python: <3.10.5>
* Platform: <Windows-10-10.0.19044-SP0>
* How you installed Python: <python.org/downloads-->
* Did you also try this on another platform? Does it work there?
NO
* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
My program uses many libraries like numpy, tensorflow, numba, scipy, cv2,...And have many files. I use os to mkdir folder in my program
```

### Stacktrace / full error message
```
Title: **Unhandled exception in script.**
MESSAGE: _Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception: No module named 'os'_
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
What is the PyInstaller command that you are using to build your program?

**Comment by VERISBABY** [comment]
> What is the PyInstaller command that you are using to build your program?

pyinstaller --noconfirm --onedir --windowed --icon "C:/Users/Administrator/Desktop/admin/logo.ico" --name "house" --upx-dir "C:/Program Files/Python310/Lib/site-packages/upx" --clean --log-level "DEBUG" --debug "all" --add-data "C:/Users/Administrator/Desktop/admin/python310.dll;." --paths "C:/Program Files/Python310" --collect-data "numpy" --exclude-module "soundfile" --hidden-import "_socket" --hidden-import "cv2.cv2" --hidden-import "os" --hidden-import "_asyncio" --paths "C:/Program Files/Python310/Lib/site-packages" --paths "C:/Program Files/Python310/DLLs" --paths "C:/Program Files/Python310/Lib/site-packages/tensorflow" --upx-exclude "python310.dll"  "C:/Users/Administrator/Desktop/admin/house.py"

**Comment by rokm** [comment]
>--add-data "C:/Users/Administrator/Desktop/admin/python310.dll;." 
>--paths "C:/Program Files/Python310" 
>--paths "C:/Program Files/Python310/Lib/site-packages" 
>--paths "C:/Program Files/Python310/DLLs" 
>--paths "C:/Program Files/Python310/Lib/site-packages/tensorflow"

These all look suspicious, and the last one is just plain wrong - you should never point search path *inside* the package, because that makes the package's modules become top-level modules. 

If you need to use `--paths` in that way, that usually means that you have multiple python environments and that pyinstaller is installed in a different one than the one you're using for your code.

**Comment by bwoodsend** [comment]
Either your PyInstaller is not installed in that 3.10.5 environment that you think it is in or your doing something invalid like running the executable in the `build` folder instead of the `dist` folder or distributing just the executable rather than the entire directory. Can we have an actual minimal example please? i.e. Code such as just `import os` and a build command with no usages of `--paths`. And the build log as well so that we can check if PyInstaller is reporting from a Python 3.10.5 environment or not.

**Comment by VERISBABY** [comment]
> Either your PyInstaller is not installed in that 3.10.5 environment that you think it is in or your doing something invalid like running the executable in the `build`  folder instead of the `dist` folder or distributing just the executable rather than the entire directory. Can we have an actual minimal example please? i.e. Code such as just `import os` and a build command with no usages of `--paths`. And the build log as well so that we can check if PyInstaller is reporting from a Python 3.10.5 environment or not.

I checked environment, try to run .exe file in both `build` & `dist` folder and try not to use `--path `but it still has that error. In my files, my main use of os is to create files and directories, those code is inside `root=Tk()`:
```
import os
...
if os.path.exists('folder/') == False:
	os.mkdir('folder/')
```
And pyinstaller cmd has run:
`pyinstaller --noconfirm --onedir --windowed --icon logo.ico --name "home" --clean --log-level "DEBUG" --debug "all" --noupx --bootloader-ignore-signals --hidden-import "cv2.cv2" --hidden-import "os" login.py`

**Comment by rokm** [comment]
What if you try to build this program:
```python
# program.py
import os
print("Press any key to exit")
input()
```
with
```
pyinstaller --clean --noconfirm program.py
```

Does the generated program (dist/program/program.exe) work?

**Comment by VERISBABY** [comment]
> What if you try to build this program:
> 
> ```python
> # program.py
> import os
> print("Press any key to exit")
> input()
> ```
> 
> with
> 
> ```
> pyinstaller --clean --noconfirm program.py
> ```
> 
> Does the generated program (dist/program/program.exe) work?

No. And when I tried running the .exe file on PowerShell 7.2.5 or CMD, it shows an error with this traceback:
```
Traceback (most recent call last):
  File "PyInstaller\loader\pyiboot01_bootstrap.py", line 14, in <module>
ModuleNotFoundError: No module named 'os'
[13272] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```
That is `import os` line.

**Comment by rokm** [comment]
> That is `import os` line.

Yes, but that's `import os` line in PyInstaller's bootstrap scripts, not in the `program.py`...

Can you upload the generated `build` and `dist` directories for this sample program somewhere, so we can download them and see what's going on?

**Comment by VERISBABY** [comment]
> > That is `import os` line.
> 
> Yes, but that's `import os` line in PyInstaller's bootstrap scripts, not in the `program.py`...
> 
> Can you upload the generated `build` and `dist` directories for this sample program somewhere, so we can download them and see what's going on?

this is full file i build: <https://github.com/VERISBABY/programe>

**Comment by rokm** [comment]
Can you also upload the following file: `C:\Program Files\Python310\lib\site-packages\PyInstaller\loader\pyiboot01_bootstrap.py'?`

**Comment by VERISBABY** [comment]
I have fixed the error. I came up with this: try deleting all the source files related to pyinstaller and reinstalling it. But I noticed in the files that `bdist-pyinstaller` is included, it seems that install it will cause an error? Because when reinstalling with just `pip install pyinstaller`, it doesn't give the error anymore.

**Comment by rokm** [comment]
Yeah, it looked like at some point, the local copy of `pyiboot01_bootstrap.py` was modified to import `os` sooner than it should.
