### ISSUE TITLE
[25175] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [pyinstaller/pyinstaller#6979]
I freeze a simple hello world and run on several machines, but failed on one of them.
The script is packed with follow version of tools:

    pyinstaller:5.2
    Python: 3.9.12
    Ubuntu: 18.04

I try to run the packaged file on ubuntu18.04:

[25170] WARNING: file already exists but should not: /tmp/_MEIKTRoO8/torch/_C.cpython-39-x86_64-linux-gnu.so
[25170] WARNING: file already exists but should not: /tmp/_MEIKTRoO8/torch/_dl.cpython-39-x86_64-linux-gnu.so
[25175] Module object for struct is NULL!
ValueError: bad marshal data (unknown type code)
[25175] Module object for pyimod01_os_path is NULL!
ValueError: bad marshal data (unknown type code)
[25175] Module object for pyimod02_archive is NULL!
ValueError: bad marshal data (unknown type code)
[25175] Module object for pyimod03_importers is NULL!
ValueError: bad marshal data (unknown type code)
[25175] Module object for pyimod04_ctypes is NULL!
ValueError: bad marshal data (unknown type code)
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[25175] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception

I don't know how to fix it. Thank you so much if anyone can help!

Is it related to the warning of the packaging process？

(mmdeploy) zhang@zhang-QiTianM540-A739:/media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx$ pyinstaller -F trans_segmask3onnx_exe3.py
162 INFO: PyInstaller: 5.2
162 INFO: Python: 3.9.12 (conda)
164 INFO: Platform: Linux-5.4.0-122-generic-x86_64-with-glibc2.27
165 INFO: wrote /media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx/trans_segmask3onnx_exe3.spec
167 INFO: UPX is not available.
168 INFO: Extending PYTHONPATH with paths
['/media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx']
360 INFO: checking Analysis
360 INFO: Building Analysis because Analysis-00.toc is non existent
360 INFO: Initializing module dependency graph...
361 INFO: Caching module graph hooks...
364 WARNING: Several hooks defined for module 'numpy'. Please take care they do not conflict.
365 INFO: Analyzing base_library.zip ...
2279 INFO: Processing pre-find module path hook distutils from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/pre_find_module_path/hook-distutils.py'.
2303 INFO: distutils: retargeting to non-venv dir '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9'
4097 INFO: Caching module dependency graph...
4190 INFO: running Analysis Analysis-00.toc
4209 INFO: Analyzing /media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx/trans_segmask3onnx_exe3.py
5376 INFO: Processing pre-find module path hook site from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/pre_find_module_path/hook-site.py'.
5376 INFO: site: retargeting to fake-dir '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/fake-modules'
8232 INFO: Processing pre-safe import module hook gi from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/pre_safe_import_module/hook-gi.py'.
10091 INFO: Processing pre-safe import module hook six.moves from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/pre_safe_import_module/hook-six.moves.py'.
12545 INFO: Processing pre-safe import module hook win32com from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller_hooks_contrib-2022.8-py3.9.egg/_pyinstaller_hooks_contrib/hooks/pre_safe_import_module/hook-win32com.py'.
16913 INFO: Processing module hooks...
16913 INFO: Loading module hook 'hook-numpy.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/numpy/_pyinstaller'...
16953 WARNING: Conda distribution 'numpy', dependency of 'numpy', was not found. If you installed this distribution with pip then you may ignore this warning.
16964 INFO: Import to be excluded not found: 'f2py'
16977 INFO: Loading module hook 'hook-certifi.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller_hooks_contrib-2022.8-py3.9.egg/_pyinstaller_hooks_contrib/hooks/stdhooks'...
16979 INFO: Loading module hook 'hook-torch.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller_hooks_contrib-2022.8-py3.9.egg/_pyinstaller_hooks_contrib/hooks/stdhooks'...
17011 INFO: Loading module hook 'hook-torchvision.ops.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller_hooks_contrib-2022.8-py3.9.egg/_pyinstaller_hooks_contrib/hooks/stdhooks'...
17012 INFO: Loading module hook 'hook-cv2.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller_hooks_contrib-2022.8-py3.9.egg/_pyinstaller_hooks_contrib/hooks/stdhooks'...
17013 INFO: Loading module hook 'hook-h5py.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller_hooks_contrib-2022.8-py3.9.egg/_pyinstaller_hooks_contrib/hooks/stdhooks'...
17013 INFO: Loading module hook 'hook-shelve.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
17018 INFO: Loading module hook 'hook-PIL.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
17027 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
17029 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
17029 INFO: Loading module hook 'hook-xml.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
17030 INFO: Loading module hook 'hook-lib2to3.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
17039 INFO: Loading module hook 'hook-sqlite3.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
17378 INFO: Loading module hook 'hook-pkg_resources.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
18261 INFO: Loading module hook 'hook-matplotlib.backends.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
18261 INFO: Matplotlib backend selection method: automatic discovery of used backends
18424 INFO: Trying determine the default backend as first importable candidate from the list: ['Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
19252 INFO: Selected matplotlib backends: ['TkAgg']
19333 INFO: Loading module hook 'hook-setuptools.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
20318 INFO: Loading module hook 'hook-_tkinter.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
20377 INFO: checking Tree
20377 INFO: Building Tree because Tree-00.toc is non existent
20377 INFO: Building Tree Tree-00.toc
20386 INFO: checking Tree
20386 INFO: Building Tree because Tree-01.toc is non existent
20386 INFO: Building Tree Tree-01.toc
20421 INFO: checking Tree
20421 INFO: Building Tree because Tree-02.toc is non existent
20421 INFO: Building Tree Tree-02.toc
20423 INFO: Loading module hook 'hook-matplotlib.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
20581 INFO: Loading module hook 'hook-pickle.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
20586 INFO: Loading module hook 'hook-platform.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
20589 INFO: Loading module hook 'hook-distutils.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
20612 INFO: Loading module hook 'hook-numpy._pytesttester.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
20615 INFO: Loading module hook 'hook-difflib.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
20617 INFO: Loading module hook 'hook-pygments.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
22520 INFO: Loading module hook 'hook-distutils.util.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
22523 INFO: Loading module hook 'hook-encodings.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
22741 INFO: Loading module hook 'hook-packaging.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
22741 INFO: Loading module hook 'hook-heapq.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
22746 INFO: Loading module hook 'hook-sysconfig.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
22749 INFO: Loading module hook 'hook-PIL.Image.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
23138 INFO: Loading module hook 'hook-multiprocessing.util.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
23142 INFO: Loading module hook 'hook-setuptools.msvc.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
23144 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks'...
23192 INFO: checking Tree
23192 INFO: Building Tree because Tree-03.toc is non existent
23192 INFO: Building Tree Tree-03.toc
23200 INFO: checking Tree
23200 INFO: Building Tree because Tree-04.toc is non existent
23200 INFO: Building Tree Tree-04.toc
23203 INFO: Looking for ctypes DLLs
23656 WARNING: Library vcruntime140.dll required via ctypes not found
23686 WARNING: Library vcruntime140_1.dll required via ctypes not found
23716 WARNING: Library msvcp140.dll required via ctypes not found
23757 WARNING: Library user32 required via ctypes not found
23829 INFO: Analyzing run-time hooks ...
23840 INFO: Including run-time hook '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/rthooks/pyi_rth_subprocess.py'
23841 INFO: Including run-time hook '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/rthooks/pyi_rth_pkgutil.py'
23843 INFO: Including run-time hook '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/rthooks/pyi_rth_inspect.py'
23843 INFO: Including run-time hook '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py'
23845 INFO: Including run-time hook '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/rthooks/pyi_rth_pkgres.py'
23847 INFO: Including run-time hook '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/rthooks/pyi_rth__tkinter.py'
23848 INFO: Including run-time hook '/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/hooks/rthooks/pyi_rth_mplconfig.py'
23867 INFO: Looking for dynamic libraries
/home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/building/build_main.py:157: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
30658 INFO: Looking for eggs
30658 INFO: Python library not in binary dependencies. Doing additional searching...
30670 INFO: Using Python library /home/zhang/anaconda3/envs/mmdeploy/lib/libpython3.9.so.1.0
30705 INFO: Warnings written to /media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx/build/trans_segmask3onnx_exe3/warn-trans_segmask3onnx_exe3.txt
30836 INFO: Graph cross-reference written to /media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx/build/trans_segmask3onnx_exe3/xref-trans_segmask3onnx_exe3.html
30956 INFO: checking PYZ
30956 INFO: Building PYZ because PYZ-00.toc is non existent
30956 INFO: Building PYZ (ZlibArchive) /media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx/build/trans_segmask3onnx_exe3/PYZ-00.pyz
32456 INFO: Building PYZ (ZlibArchive) /media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx/build/trans_segmask3onnx_exe3/PYZ-00.pyz completed successfully.
32491 INFO: checking PKG
32491 INFO: Building PKG because PKG-00.toc is non existent
32491 INFO: Building PKG (CArchive) trans_segmask3onnx_exe3.pkg
324475 INFO: Building PKG (CArchive) trans_segmask3onnx_exe3.pkg completed successfully.
324540 INFO: Bootloader /home/zhang/anaconda3/envs/mmdeploy/lib/python3.9/site-packages/pyinstaller-5.2-py3.9.egg/PyInstaller/bootloader/Linux-64bit-intel/run
324540 INFO: checking EXE
324540 INFO: Building EXE because EXE-00.toc is non existent
324540 INFO: Building EXE from EXE-00.toc
324562 INFO: Copying bootloader EXE to /media/zhang/DATA11/work_dir/TensorRT/trans_segmask3onnx/dist/trans_segmask3onnx_exe3
324587 INFO: Appending PKG archive to custom ELF section in EXE
339265 INFO: Building EXE from EXE-00.toc completed successfully.

**Comment by rokm** [comment]
You are very likely installing PyInstaller from `develop` branch, which may at times include changes that require bootloader to be rebuilt (in this case, a97fdfe6f5908874e891b783206f29631849b9cf). 

So if you want to use `develop` branch, be sure to set `PYINSTALLER_COMPILE_BOOTLOADER=1` environment variable before you run `pip install`.

**Comment by Avasam** [comment]
@rokm I'm having the exact same problem that just started happening. Similar stracktrace:
```
[16486] Module object for struct is NULL!
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ModuleNotFoundError: No module named '_struct'
[16486] Module object for pyimod02_archive is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_archive.py", line 27, in <module>
ModuleNotFoundError: No module named 'struct'
[16486] Module object for pyimod03_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod03_importers.py", line 23, in <module>
ModuleNotFoundError: No module named 'pyimod02_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod03_importers'
[16486] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

I don't use PyInstaller from develop, I install from PyPi.
Built executable and logs: https://github.com/Toufool/Auto-Split/actions/runs/2745057729
Pip install step: https://github.com/Toufool/Auto-Split/runs/7535795086?check_suite_focus=true#step:4:469
PyInstaller-5.2
pyinstaller-hooks-contrib-2022.8
Python 3.10
Ubuntu 22.04

**Comment by rokm** [comment]
@Avasam This is not the "exact same problem" at all.

In the OP case, the code objects cannot be even unmarshalled, which is most likely due to the changes made in https://github.com/pyinstaller/pyinstaller/commit/a97fdfe6f5908874e891b783206f29631849b9cf and bootloader not being rebuilt:
```
[25175] Module object for struct is NULL!
ValueError: bad marshal data (unknown type code)
[25175] Module object for pyimod01_os_path is NULL!
ValueError: bad marshal data (unknown type code)
[25175] Module object for pyimod02_archive is NULL!
ValueError: bad marshal data (unknown type code)
[25175] Module object for pyimod03_importers is NULL!
ValueError: bad marshal data (unknown type code)
[25175] Module object for pyimod04_ctypes is NULL!
ValueError: bad marshal data (unknown type code)
Traceback (most recent call last):
File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in
ModuleNotFoundError: No module named 'pyimod03_importers'
[25175] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception
```
---

In your case, the modules umarshal fine, but cannot be loaded due to `_struct` module/extension missing from the build. And as far as I can tell, this is caused by a mix-up between system-installed python and the one installed by `actions/setup-python`. Because if you check the Analysis-00.toc in the build logs you linked, you will see that the python stdlib is collected from system python, e.g.:
```
('struct', '/usr/lib/python3.10/struct.py', 'PYMODULE'),
```
but the python shared lib is collected from the action-installed one:
```
  ('libpython3.10.so.1.0',
   '/opt/hostedtoolcache/Python/3.10.5/x64/lib/libpython3.10.so.1.0',
   'BINARY')],
```
In system-installed python, the `_struct` module is a built-in, so there is nothing to collect, but because you end up with shared lib from action-installed python (where `_struct` is an extension), it ends up missing.

If you check build logs for earlier builds (like [this one](https://github.com/Toufool/Auto-Split/actions/runs/2700907589)], you will see that everything there is collected from action-installed python:
```
...
  ('struct',
   '/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/struct.py',
   'PYMODULE'),
...
  ('lib-dynload/_struct',
   '/opt/hostedtoolcache/Python/3.10.5/x64/lib/python3.10/lib-dynload/_struct.cpython-310-x86_64-linux-gnu.so',
   'EXTENSION'),
...
('libpython3.10.so.1.0',
   '/opt/hostedtoolcache/Python/3.10.5/x64/lib/libpython3.10.so.1.0',
   'BINARY'),
...
```
