### ISSUE TITLE
[Documentation] Splashscreen on linux does not support transparency

### ISSUE THREAD

**Issue by Avasam** [pyinstaller/pyinstaller#6987]
## Description of the issue

On linux, my splashscreen appears as follows, where the transparent parts are gray. They are transparent on Windows.
![image](https://user-images.githubusercontent.com/1350584/181349589-46a035da-e9cf-4825-9ef4-62b839f83f3b.png)

Here's the hard-cut transparency image I am using for reference:
![splash](https://user-images.githubusercontent.com/1350584/181352939-5a2bd7de-ffb3-4471-a299-5a21a3f6c0df.png)

I understand this could be a Linux limitation and/or the nature of the splashscreen being *experimental*. But this limitation is not currently documented: https://pyinstaller.org/en/stable/usage.html#splash-screen-experimental

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.2
* Version of Python: 3.10
* Platform: Ubuntu 22.04
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?
Yes Windows

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

N/A (program can be empty, just needs a spashscreen)

### Stacktrace / full error message

N/A

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
You're right; hard-cut transparency [does not seem to be supported on linux](https://github.com/pyinstaller/pyinstaller/blob/7875d7684c6ddad90e91af9141229083ebb1297f/PyInstaller/building/splash_templates.py#L162-L163). Sounds like a platform-specific limitation of Tcl/Tk.

And yeah, it would be nice if the docs contained a note about that - care to open a PR that adds one?
