### ISSUE TITLE
how to integrate .bmp files and other types of files into the exe

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [pyinstaller/pyinstaller#6988]
When I run the packaged file, the problem occurs, I don't know how to integrate .bmp files and other types of files into the exe, thank you for your answer.
load checkpoint from local path: epoch_36.pth
Traceback (most recent call last):
  File "trans_segmask3onnx_exe3.py", line 179, in <module>
    torch2onnx(
  File "mmdeploy/apis/core/pipeline_manager.py", line 354, in _wrap
  File "mmdeploy/apis/core/pipeline_manager.py", line 324, in call_function
  File "mmdeploy/apis/core/pipeline_manager.py", line 273, in call_function_local
  File "mmdeploy/apis/core/pipeline_manager.py", line 105, in __call__
  File "mmdeploy/apis/pytorch2onnx.py", line 63, in torch2onnx
  File "mmdeploy/codebase/mmdet/deploy/object_detection.py", line 144, in create_input
  File "mmdet/datasets/pipelines/compose.py", line 41, in __call__
  File "mmdet/datasets/pipelines/loading.py", line 67, in __call__
  File "mmcv/fileio/file_client.py", line 992, in get
  File "mmcv/fileio/file_client.py", line 517, in get
FileNotFoundError: [Errno 2] No such file or directory: '1_04300035.bmp'

For example:

        deploy_cfg_path = 'mmdeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py'
        model_cfg_path = 'mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py'
        img = '1_04300035.bmp'
        work_dir = filenname[:-4]

**Comment by rokm** [comment]
1) you need to [collect non-python data yourself](https://pyinstaller.org/en/stable/spec-files.html#adding-files-to-the-bundle). Either use [`--add-data`](https://pyinstaller.org/en/stable/usage.html#cmdoption-add-data) or [`--collect-data`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-data) (if data is  part of a python package), or `datas` argument to `Analysis` in the spec file, as described in the docs.

2) you should always [anchor your paths using modules' `__file__` attribute](https://pyinstaller.org/en/stable/runtime-information.html#using-file), because otherwise relative paths end up being interpreted relative to the current working directory, which may or may not be what you and your code expect.

**Comment by jiaqizhang123-stack** [comment]
Sorry, I don't quite understand, I tried -add-data or --collect-data, but it still gives that the .bmp file does not exist.
In addition, for the .py file embedded in the main function, as shown in the above example, how should it be integrated.

    deploy_cfg_path = 'mmdeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py'
    model_cfg_path = 'mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py'
    img = '1_04300035.bmp'
    work_dir = filenname[:-4]

**Comment by rokm** [comment]
Have you checked if the image is actually collected into frozen application bundle? (If you are using `onefile` build, you might want to switch to `onedir` until you get everything running, as it is easier to inspect).

Those .py files probably need to be collected as data files, e.g., 
`--add-data /full/path/to/location/of/mmdeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py;mmdeploy/configs/mmdet/instance-seg`
`--add-data /full/path/to/localtion/of/mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py;mmdetection/configs/mask_rcnn`

Similarly, you need to collect the image to your application bundle (this will collect it to the top-level directory):
`--add-data /full/path/to/where/images/are/1_04300035.bmp;.`

Then, in the code, you need to anchor those paths to `sys._MEIPASS` (or, if this is entry-point script, you could also use `os.path.dirname(__file__)`):

```python
deploy_cfg_path = 'mmdeploy/configs/mmdet/instance-seg/instance-seg_onnxruntime_dynamic.py'
model_cfg_path = 'mmdetection/configs/mask_rcnn/mask_rcnn_r50_fpn_1x_coco.py'
img = '1_04300035.bmp'
work_dir = filenname[:-4]

if getattr(sys, 'frozen', False):
    deploy_cfg_path = os.path.join(sys._MEIPASS, deploy_cfg_path)
    model_cfg_path = os.path.join(sys._MEIPASS, model_cfg_path)
    img = os.path.join(sys._MEIPASS, img)
```
