### ISSUE TITLE
M1 Monterey Automation permission keeps disappearing

### ISSUE THREAD

**Issue by bilinenkisi** [pyinstaller/pyinstaller#6996]
## Description of the issue
I use osascript in my project to get information from the current app but in the m1 platform, automation permission disappears while executing the script. I tried to freeze my unix executable app without upx but it didn't work. 
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(5.2)```
* Version of Python: 3.9
* Platform: macOS m1 Monterey 
* How you installed Python: pre-installed
* Program works on intel platforms of Apple but on m1 it resets automation permission

  * [x] start with a clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

**Comment by bwoodsend** [comment]
Does [this](https://github.com/pyinstaller/pyinstaller/discussions/6932#discussioncomment-3080040) get you anywhere?

**Comment by bilinenkisi** [comment]
> Does [this](https://github.com/pyinstaller/pyinstaller/discussions/6932#discussioncomment-3080040) get you anywhere?

Unfortunately because of I'm not packaging my program as .app, I can't use info.plist.

**Comment by rokm** [comment]
Is this even possible without an .app bundle and its `Info.plist`? If so, how? 

I think I recall reading somewhere that it linker can embed `Info.plist` into an executable, but that's not an option for PyInstaller in general due to pre-built bootloaders. I suppose you could try rebuilding the bootloader yourself and patch its build script to inject `Info.plist` into it (provided embedded `Info.plist` allows you to opt in for automation permissions).

**Comment by bilinenkisi** [comment]
> Is this even possible without an .app bundle and its `Info.plist`? If so, how?
> 
> I think I recall reading somewhere that it linker can embed `Info.plist` into an executable, but that's not an option for PyInstaller in general due to pre-built bootloaders. I suppose you could try rebuilding the bootloader yourself and patch its build script to inject `Info.plist` into it (provided embedded `Info.plist` allows you to opt in for automation permissions).

hmm, I understand but is re-building bootlader depends on platform or not? For example, can i combine bootloader on intel mac and after use for m1?

**Comment by bilinenkisi** [comment]
According to this [discussion ](https://github.com/pyinstaller/pyinstaller/discussions/5926), i can use directly `--osx-entitlements-file` command to inject Info.plist to executable.

**Comment by rokm** [comment]
> > Is this even possible without an .app bundle and its `Info.plist`? If so, how?
> > I think I recall reading somewhere that it linker can embed `Info.plist` into an executable, but that's not an option for PyInstaller in general due to pre-built bootloaders. I suppose you could try rebuilding the bootloader yourself and patch its build script to inject `Info.plist` into it (provided embedded `Info.plist` allows you to opt in for automation permissions).
> 
> hmm, I understand but is re-building bootlader depends on platform or not? For example, can i combine bootloader on intel mac and after use for m1?

We [try to build `universal2` bootloader](https://github.com/pyinstaller/pyinstaller/blob/ba38ba4ba90ae726129e15240f25c27ddc29bf29/bootloader/wscript#L356-L379)  if the toolchain supports it. Not sure what it takes to get `Info.plist` embedded into each arch slice, though... maybe it's enough to just put the necessary flags into `LINKFLAGS` (search around for `-sectcreate,__TEXT,__info_plist`).

**Comment by rokm** [comment]
> According to this [discussion ](https://github.com/pyinstaller/pyinstaller/discussions/5926), i can use directly `--osx-entitlements-file` command to inject Info.plist to executable.

That's entitlements passed to the `codesign`. I could be wrong, but I don't think it's the same thing. Still, doesn't hurt to try...

**Comment by bilinenkisi** [comment]
> > > Is this even possible without an .app bundle and its `Info.plist`? If so, how?
> > > I think I recall reading somewhere that it linker can embed `Info.plist` into an executable, but that's not an option for PyInstaller in general due to pre-built bootloaders. I suppose you could try rebuilding the bootloader yourself and patch its build script to inject `Info.plist` into it (provided embedded `Info.plist` allows you to opt in for automation permissions).
> > 
> > 
> > hmm, I understand but is re-building bootlader depends on platform or not? For example, can i combine bootloader on intel mac and after use for m1?
> 
> We [try to build `universal2` bootloader](https://github.com/pyinstaller/pyinstaller/blob/ba38ba4ba90ae726129e15240f25c27ddc29bf29/bootloader/wscript#L356-L379) if the toolchain supports it. Not sure what it takes to get `Info.plist` embedded into each arch slice, though... maybe it's enough to just put the necessary flags into `LINKFLAGS` (search around for `-sectcreate,__TEXT,__info_plist`).

Ok thanks, I will search for it. if somehow I can manage to make working it, I will write here.

**Comment by bilinenkisi** [comment]
> > > > Is this even possible without an .app bundle and its `Info.plist`? If so, how?
> > > > I think I recall reading somewhere that it linker can embed `Info.plist` into an executable, but that's not an option for PyInstaller in general due to pre-built bootloaders. I suppose you could try rebuilding the bootloader yourself and patch its build script to inject `Info.plist` into it (provided embedded `Info.plist` allows you to opt in for automation permissions).
> > > 
> > > 
> > > hmm, I understand but is re-building bootlader depends on platform or not? For example, can i combine bootloader on intel mac and after use for m1?
> > 
> > 
> > We [try to build `universal2` bootloader](https://github.com/pyinstaller/pyinstaller/blob/ba38ba4ba90ae726129e15240f25c27ddc29bf29/bootloader/wscript#L356-L379) if the toolchain supports it. Not sure what it takes to get `Info.plist` embedded into each arch slice, though... maybe it's enough to just put the necessary flags into `LINKFLAGS` (search around for `-sectcreate,__TEXT,__info_plist`).
> 
> Ok thanks, I will search for it. if somehow I can manage to make working it, I will write here.

it appears to be fixed itself but I don't know why it was happened or fixed

**Comment by bilinenkisi** [comment]
After some research and testing, I noticed that even if I call an apple script from the terminal via python os.system call, the same thing happens. So I think this is a bug in Monterey m1 which is why this issue can be closed. Thanks for all the help you have done so far
