### ISSUE TITLE
How would I be able to use pyinstaller inside an exe produced by pyinstaller?

### ISSUE THREAD

**Issue by GodFather227** [pyinstaller/pyinstaller#7000]
* Output of `pyinstaller --version`: ```(5.2)```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there? No, No it does not

```
Fatal error in launcher: Unable to create process using '"C:\Users\this1\AppData\Local\Programs\Python\Python310\python.exe"  "C:\Users\this1\AppData\Local\Programs\Python\Python310\Scripts\pyinstaller.exe" --clean --onefile --noconsole -i NONE -n testing testing.py': The system cannot find the file specified.

Traceback (most recent call last):
  File "<dist\obf\builder.py>", line 3, in <module>
  File "<frozen builder>", line 56, in <module>
  File "shutil.py", line 749, in rmtree
  File "shutil.py", line 600, in _rmtree_unsafe
  File "shutil.py", line 597, in _rmtree_unsafe
FileNotFoundError: [WinError 3] The system cannot find the path specified: 'build'
[3908] Failed to execute script 'builder' due to unhandled exception!
```

I just want to be able to use pyinstaller inside of an app

**Comment by rokm** [comment]
> The system cannot find the file specified.

This most likely means that the executable you are trying to spawn for your process (`C:\Users\this1\AppData\Local\Programs\Python\Python310\python.exe`) does not exist. Or perhaps you have an extra set of quotes around it that cause problems. Either way, this looks like a problem with process spawning in your code, and has nothing to do with PyInstaller.

But if you assume that python environment is available and that PyInstaller is installed in it, what is even the point of trying to create a frozen application that calls it? It won't be portable, anyway...
