### ISSUE TITLE
Can't load plugin: sqlalchemy.dialects:clickhouse.native

### ISSUE THREAD

**Issue by wuhuanyan** [pyinstaller/pyinstaller#7007]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.3```
* Version of Python: 3.8.12
* Platform: Windows 10
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
Have not tried

### A minimal example program which shows the error

```python
from sqlalchemy import create_engine
import sqlalchemy
import clickhouse_driver
import clickhouse_sqlalchemy


print('sqlalchemy.__version__', sqlalchemy.__version__)
print('clickhouse_driver.__version__', clickhouse_driver.__version__)
print('clickhouse_sqlalchemy.__version__', clickhouse_sqlalchemy.__version__)


uri = 'clickhouse+native://{}:{}@{}:{}/{}'
uri = uri.format('default', '1', '127.0.0.1', '19000', 'caiwu')
engine = create_engine(uri)
print(engine)
```

run in pycharm
```
sqlalchemy.__version__ 1.3.24
clickhouse_driver.__version__ 0.2.2
clickhouse_sqlalchemy.__version__ 0.1.6
Engine(clickhouse://default:***@127.0.0.1:19000/caiwu)
```

### Stacktrace / full error message

```
sqlalchemy.__version__ 1.3.24
clickhouse_driver.__version__ 0.2.2
clickhouse_sqlalchemy.__version__ 0.1.6
Traceback (most recent call last):
  File "test.py", line 14, in <module>
  File "sqlalchemy\engine\__init__.py", line 525, in create_engine
  File "sqlalchemy\engine\strategies.py", line 61, in create
  File "sqlalchemy\engine\url.py", line 172, in _get_entrypoint
  File "sqlalchemy\util\langhelpers.py", line 277, in load
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:clickhouse.native
[15936] Failed to execute script 'test' due to unhandled exception!
```

no parameters are added here
I just came into contact with pyinstaller, and I'm not very familiar with it, so there may be some pyinstaller parameters that may affect the correct output, but I don't know what to add.

**Comment by rokm** [comment]
Since the plugin discovery is performed via metadata, you need to collect the metadata of the plugin distribution. And since there are indirect imports involved, you also need to explicitly collect python modules. So add the following to your PyInstaller command:

```--copy-metadata clickhouse_sqlalchemy --collect-submodules clickhouse_sqlalchemy```

**Comment by wuhuanyan** [comment]
> Since the plugin discovery is performed via metadata, you need to collect the metadata of the plugin distribution. And since there are indirect imports involved, you also need to explicitly collect python modules. So add the following to your PyInstaller command:
> 
> `--copy-metadata clickhouse_sqlalchemy --collect-submodules clickhouse_sqlalchemy`

How can I analyze the libraries that need to be added?

**Comment by wuhuanyan** [comment]
According to the parameters you provide, I keep packaging and testing, adding one dependency after another. 
It's too troublesome.

@rokm  I directly according to the ***[requirements.txt]***, add the following parameters [hidden import, collect all, recursive copy metadata], and the packaged command is probably

```python

# Space limit. 
# The dependent names are not listed here. 
# The three parameters contain the dependency information of requirements.txt

pyinstaller test. py 
--hidden-import pak
--collect-all pak
--recursive-copy-metadata pak
```

After packaging, the runtime still reports an error. 
I checked the release directory and found that the ***[clickhouse_sqlalchemy]*** folder was missing, 
but there was a ***[clickhouse_sqlalchemy-0.1.6.dist info]*** folder. 
However, there can be ***[clickhouse_driver]*** and ***[clickhouse_driver-0.2.2.dist info]*** folders at the same time.
```python
clickhouse_driver
clickhouse_driver-0.2.2.dist info
# clickhouse_sqlalchemy
clickhouse_sqlalchemy-0.1.6.dist info
```



I don't know why the same command will cause such inconsistent results. 
Finally, I found the ***[clickhouse_sqlalchemy]*** folder from the ***[site packages]*** folder of Python and copied it to the release directory to run normally.
