### ISSUE TITLE
Error with joblib and argparser

### ISSUE THREAD

**Issue by jckkvs** [pyinstaller/pyinstaller#7008]
## Description of the issue
An error occurs when converting a python program using the joblib and argparser libraries to an executable file with pyinstaller.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.3```
* Version of Python: 3.7, 3.10 
* Platform: Windows10 (JP)
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
 No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
tried.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### A minimal example program which shows the error

```
import joblib
import argparse
def test(a):
    return a
parser = argparse.ArgumentParser()
parser.add_argument("testarg")
args = parser.parse_args()
_ = joblib.Parallel(n_jobs=2)(joblib.delayed(test)(i) for i in range(2))
```

### Stacktrace / full error message

```
usage: test.exe [-h] testarg
test.exe: error: the following arguments are required: testarg

(py310) C:\Users\11665307\Desktop\test_exe\src>dist\test\test.exe a
usage: test.exe [-h] testarg
test.exe: error: unrecognized arguments: -B -S -E -s -c
usage: test.exe [-h] testarg
test.exe: error: unrecognized arguments: --multiprocessing-fork
usage: test.exe [-h] testarg
test.exe: error: unrecognized arguments: --multiprocessing-fork
エラー: プロセス "16948" が見つかりませんでした。
エラー: プロセス "16944" が見つかりませんでした。
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    _ = joblib.Parallel(n_jobs=2)(joblib.delayed(test)(i) for i in range(2))
  File "joblib\parallel.py", line 1056, in __call__
  File "joblib\parallel.py", line 935, in retrieve
  File "joblib\_parallel_backends.py", line 542, in wrap_future_result
  File "concurrent\futures\_base.py", line 445, in result
  File "concurrent\futures\_base.py", line 390, in __get_result
joblib.externals.loky.process_executor.TerminatedWorkerError: A worker process managed by the executor was unexpectedly terminated. This could be caused by a segmentation fault while calling the function or by an excessive memory usage causing the Operating System to kill the worker.

[7572] Failed to execute script 'test' due to unhandled exception!
joblib\_memmapping_reducer.py:607: UserWarning: Failed to delete temporary folder: C:\Users\11665307\AppData\Local\Temp\joblib_memmapping_folder_7572_5afe203d17264e99bb486f596bd65315_a4f823b804854d238270e449b2e3ff06
joblib\_memmapping_reducer.py:607: UserWarning: Failed to delete temporary folder: C:\Users\11665307\AppData\Local\Temp\joblib_memmapping_folder_7572_5afe203d17264e99bb486f596bd65315_6402fbffad1a44d4a8dae744772ec5a1```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
This is happening because `loky` (the default backend for `joblib`) is not supported in PyInstaller-frozen application. Therefore, the spawned subprocesses end up running your main code, where argument parser fails to recognize those `loky`-specific arguments, and returns error.

Perhaps you'll have more luck with `multiprocessing`or `threaded` backend, but don't forget to call `multiprocessing.freeze_support` at the top of your entry-point script to divert program flow for subprocesses, otherwise you'll probably end up with a similar error.

**Comment by jckkvs** [comment]
After posting a bug report, I consulted joblib's github and was able to resolve the issue
https://github.com/joblib/joblib/issues/1002#issuecomment-579625775

Replace ```Parallel(n_jobs=self.n_jobs)``` with ```Parallel(n_jobs=self.n_jobs, prefer="threads")```

In my environment, ```freeze_support()``` could not solve the problem.
