### ISSUE TITLE
Kivy is not packaged with all data

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#701]
**Original date**: 2013/04/10
**Original reporter**: *mrkafk AND gmail DOT  COOM *

I package app with following cmd:

```
python pyinstaller.py --hidden-import=win32api --hidden-import=kivy C:\soft\pyinstaller-pyinstaller-6195cc3\teecons\teecons.spec   
```
 
This results in exception:

```

C:\soft\pyinstaller-pyinstaller-6195cc3\teecons2\dist\teecons>teecons.exe
[INFO              ] Kivy v1.6.0
[INFO              ] [Logger      ] Record log in C:\Users\ADMIN\.kivy\logs\kivy_13-04-09_12.txt
[INFO              ] [Factory     ] 137 symbols loaded
[DEBUG             ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
 Traceback (most recent call last):
   File "<string>", line 5, in <module>
   File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\loader\pyi_importers.py", line 270, in load_module
     exec(bytecode, module.__dict__)
   File "C:\soft\pyinstaller-pyinstaller-6195cc3\teecons\build\teecons\teecons\out00-PYZ.pyz\kivy.app", line 219, in <module>
   File "C:\soft\pyinstaller-pyinstaller-6195cc3\PyInstaller\loader\pyi_importers.py", line 270, in load_module
     exec(bytecode, module.__dict__)
   File "C:\soft\pyinstaller-pyinstaller-6195cc3\teecons\build\teecons\teecons\out00-PYZ.pyz\kivy.lang", line 1427, in <module>
   File "C:\soft\pyinstaller-pyinstaller-6195cc3\teecons\build\teecons\teecons\out00-PYZ.pyz\kivy.lang", line 1140, in load_file
 IOError: [Errno 2] No such file or directory: 'C:\\soft\\PYINST~1\\teecons2\\dist\\teecons\\kivy\\data\\style.kv'
```

Manual copying of "kivy" subdir from C:\Python27\Lib\site-packages\kivy to "dist" subdir fixes the problem, but I wonder if helper for dealing with module peculiarities like this are available?

pyinstaller version: https://github.com/pyinstaller/pyinstaller/zipball/develop

os: win 7 x64
python: 2.7 x64

**Comment by rawluk** [comment]
If the Kivy packaging instructions (http://kivy.org/docs/guide/packaging-windows.html) are followed correctly (including custom editing the pyinstaller spec file) this issue is worked around. However, another issue will be encountered that will need to be worked around: https://github.com/kivy/kivy/issues/3272

It's not clear to me if following the kivy packaging instructions is seen as a workaround to this issue or confirmation that this is a kivy issue and not a pyinstaller issue. Regardless, I hope this helps save other people some time.

**Comment by matham** [comment]
It works fine if the kivy instructions (http://kivy.org/docs/guide/packaging-windows.html) are followed. It's just a matter of installing the hooks and making sure you include what is needed so I don't think this is a pyinstaller issue and should probably be closed.

Regarding https://github.com/kivy/kivy/issues/3272, that again is unrelated to pyinstaller and has been fixed. It was just a matter of fixing the kivy hook, and ensuring dlls which are lazily loaded are included (i.e. sdl2 png dll which is not loaded until it's needed).

**Comment by htgoebel** [comment]
The kivy instructions seam to show a clean way for freezing kivy-apps. @rawluk @matham So I'm closing this issue. If someone wants to submit a pull-request for some kivy-hooks, we'd appreciate this as it would make kivy-users live easier.
