### ISSUE TITLE
Generated executable cannot be executed: "Permission denied"

### ISSUE THREAD

**Issue by estella144** [pyinstaller/pyinstaller#7017]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.1```
* Version of Python: 3.10.1
* Platform: macOS 12.2.1 (21D62)
* How you installed Python: from python.org
* Did you also try this on another platform? No Does it work there? N/A

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
pyinstaller --noupx --onedir calc.py
cd dist
./calc
```

### Stacktrace / full error message

```
zsh: permission denied: ./calc
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
If this was a onefile build, then `dist/calc` would be an executable. But as you are generating a onedir build, the `dist/calc` is a directory, and `dist/calc/calc` is the executable you should be running...

**Comment by estella144** [comment]
Oh ok
