### ISSUE TITLE
pyinstaller-5.3-py3-none-win_amd64.whl false positive by windows defender (resolved)

### ISSUE THREAD

**Issue by mheguy** [pyinstaller/pyinstaller#7019]
pyinstaller-5.3-py3-none-win_amd64.whl was detected as having malware by windows defender.
In case you get other reports about this, I just wanted to let you know that I submitted it as a false positive and the latest malware definitions reflect that.

![image](https://user-images.githubusercontent.com/10162554/183415838-821abdeb-d5e3-4a44-939b-1a1bd91aebb4.png)

More than anything I'm using this ticket as an opportunity to say thank you for this project.
I've always been super satisfied with pyinstaller and I appreciate all the work done to maintain and improve it. :)

**Comment by bwoodsend** [comment]
Oh wow! An antivirus vendor that actually listens to false detection feedback...

What was the submission process like? Does it look automate-able? Do you need any corporate credentials like MacAffee does or a paid account like AVG? I think, last time I tried Windows Defender, I needed to demonstrate that I was a genuine Windows user using the latest version of Defender - is that still the case?

**Comment by mheguy** [comment]
I went to the link that was provided in the issue template for Microsoft.
I selected "home customer".
I signed in with my work email (which may have helped bump the review priority a bit).
I completed the form.
Really nothing special.
![image](https://user-images.githubusercontent.com/10162554/184501211-77a77089-a54e-4f43-986a-31d14a1b430e.png)


In terms of automation: it doesn't seem especially easy.
Microsoft doesn't take submissions by email.
They also don't accept anonymous submissions: you have to be logged in.
