### ISSUE TITLE
Probléme pour ajouter un fichier image GIF

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#702]
**Original date**: 2013/04/10
**Original reporter**: *anonymous*

Bonjour,
Je travaille sous windows, j'ai un programme Python en 2.7.
Il comporte une interface graphique avec la librairie TKinter.
J'ai une image en gif qui doit s'afficher sur la fenêtre.
J'utilise PYinstaller2.0 si je désactive l'utilisation de l'image tout est OK, si je remet l'utilisation de l'image et que je re packe le programme, le Main.exe ne veut pas démarrer il dit ne pas trouver l'image.
J'ai essayé de modifier le main.spec pour lui donner le chemin du gif mais ca ne marche pas
Pouvez vous m'aider.

**Comment by matysek** [comment]
The description is not understandable.
