### ISSUE TITLE
Compile two executables in one run

### ISSUE THREAD

**Issue by ZvikaZ** [pyinstaller/pyinstaller#7020]
**Is your feature request related to a problem? Please describe.**
I have experienced the same problem described at https://github.com/pyinstaller/pyinstaller/issues/6244 and https://github.com/pyinstaller/pyinstaller/issues/6036 - namely to support both GUI and CLI apps on Windows. I understand that due to Windows limitation, we must have two executables. Therefore, I do two separate runs of PyInstallers (in default `--onedir` mode), to create two almost identical directories, the only difference between them is the executable itself.

**Describe the solution you'd like**
It'd be nice to have an option to create two executables in the directory with a single PyInstaller run. It can be a general option, if you see that fit, or even something tailored to this problem - it can be even presented to the end user as a third option: 
- `--windowed` : GUI only
- `--console`: CLI only
- `--both` : Support both

In my opinion it might even be a sane default, but maybe that's reaching too far :-)

**Describe alternatives you've considered**
Of course, running PyInstaller twice *works*, but it's suboptimal, and raises concerns as the aforementioned issues. While having the `both` option conveys the message that it's not a bug, but a designed feature.

**Additional context**

**Comment by bwoodsend** [comment]
If you want two executables, you just edit the spec file and add a second `EXE()` block. There's an example [here](https://gitlab.com/ikus-soft/minarca/-/blob/a340e4ef97917d566fe83bf385c1d4170e62c6c5/minarca-client/minarca.spec#L62-100) if you need it.

I really don't see that there's a need for a new feature here - just a lack of awareness of the spec file and the malleability of its individual components. Needs better documentation: probably. New feature: I don't think so.

**Comment by rokm** [comment]
> I really don't see that there's a need for a new feature here - just a lack of awareness of the spec file and the malleability of its individual components. Needs better documentation: probably. New feature: I don't think so.

I agree. Advanced use cases such as this should be handled via .spec files.
