### ISSUE TITLE
Backwards compatible builds for MacOs

### ISSUE THREAD

**Issue by Moosems** [pyinstaller/pyinstaller#7022]
**Is your feature request related to a problem? Please describe.**
I often want to set up automatic builds for MacOs but whenever I run the builds compiled with gh actions the error of backwards compatibility always comes up as I use `10.14.6`. The latest gh actions build will soon be `10.11` and making backwards compatible builds becomes very important on larger projects. 

**Describe the solution you'd like**
After reading through the building code for projects like VS Code it doesn't seem to require using the oldest version possible as they use macos-latest so if we could check for dependencies that require macos version specifics then we can allow it to be backwards compatible to some extent

**Describe alternatives you've considered**
Using other build services

**Additional context**
Nope :)

**Comment by bwoodsend** [comment]
There's nothing PyInstaller can do if libraries in your build aren't compiled with a low enough deployment target. You'll have to figure out which files are incompatible (which I suppose PyInstaller could have a feature for) and re-engineer your gh actions workflow to match. This usually boils down to:
* Use Python from python.org instead of actions/setup-python or brew
* Don't use brew for anything
* Expect to have to build some of your packages from source

There's a nice example of this [here](https://github.com/sabnzbd/sabnzbd/blob/cbeab4dd55a12499ff3cc32d1fca440e0f24cfa7/.github/workflows/build_release.yml#L65) where they're targeting macOS 10.9 and building a universal2 application.

**Comment by Moosems** [comment]
I could use a bit of explaining how to implement what they did in the example. I tried implementing it [here](https://github.com/DIP-Editor/DIP-dev/blob/main/.github/workflows/Macbuild.yml) and got this output when running the file:
```yaml
/Volumes/DIP/DIP.app/Contents/MacOS/DIP ; exit;
Moosems-MacBook-Pro:~ Moosems$ /Volumes/DIP/DIP.app/Contents/MacOS/DIP ; exit;
[2225] Error loading Python lib '/Volumes/DIP/DIP.app/Contents/MacOS/Python': dlopen: dlopen(/Volumes/DIP/DIP.app/Contents/MacOS/Python, 10): Symbol not found: _preadv
  Referenced from: /Volumes/DIP/DIP.app/Contents/MacOS/Python (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in /Volumes/DIP/DIP.app/Contents/MacOS/Python
logout
Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]
```

**Comment by bwoodsend** [comment]
You're link is private so I can't see it.

**Comment by rokm** [comment]
Which python are you using on your CI? This one is explicitly targeting macOS 11.0:
> ```
>   Referenced from: /Volumes/DIP/DIP.app/Contents/MacOS/Python (which was built for Mac OS X 11.0)
> ```

That probably makes it `actions/setup-python` or a homebrew python, neither of which will be backwards compatible. You should explicitly install and use the python.org build, as in example linked in https://github.com/pyinstaller/pyinstaller/issues/7022#issuecomment-1211732628.

**Comment by Moosems** [comment]
I figured it out. I was using the python.org but not the right version. I fixed that and a few other bugs and got it to work in my example repo [here](https://github.com/Moosems/PyInstallerBuild)

**Comment by rokm** [comment]
>       PYTHONVERSION: "3.10.0"

Make that a 3.10.1 or later, otherwise you risk being hit by #6301.

**Comment by Moosems** [comment]
Could `3.10.6` work?

> > ```
> >   PYTHONVERSION: "3.10.0"
> > ```
> 
> Make that a 3.10.1 or later, otherwise you risk being hit by #6301.

**Comment by rokm** [comment]
It should. Anything but 3.10.0, which has the bug from the linked issue.

**Comment by Moosems** [comment]
@rokm For my example repo I simplified the process greatly so it the future you might want to use that as an example when people ask about this ;)
