### ISSUE TITLE
Dll not found warning

### ISSUE THREAD

**Issue by FlorinPT** [pyinstaller/pyinstaller#7024]
345 WARNING: Failed to collect submodules for 'setuptools._vendor.pyparsing.diagram' because importing 'setuptools._vendor.pyparsing.diagram' raised: FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\PC\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\setuptools\\_vendor\\pyparsing\\diagram\\template.jinja2'
C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py:157: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
  warnings.warn('No audio backend is available.')
3588 WARNING: lib not found: torch_cuda_cpp.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchaudio\_torchaudio.pyd
4784 WARNING: lib not found: torch_cuda_cu.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchaudio\_torchaudio.pyd
4784 WARNING: lib not found: c10.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchaudio\_torchaudio.pyd
4785 WARNING: lib not found: torch_cpu.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchaudio\_torchaudio.pyd
4790 WARNING: lib not found: torch_cuda_cpp.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\_C.pyd
4792 WARNING: lib not found: c10_cuda.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\_C.pyd
4794 WARNING: lib not found: c10.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\_C.pyd
4794 WARNING: lib not found: torch_cpu.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchvision\_C.pyd
4797 WARNING: lib not found: torch_python.dll dependency of C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\_C.cp39-win_amd64.pyd
5139 WARNING: lib not found: api-ms-win-security-systemfunctions-l1-1-0.dll dependency of C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\bin\cudart64_110.dll

**Comment by rokm** [comment]
Those are all warnings, not errors...

**Comment by FlorinPT** [comment]
> Those are all warnings, not errors...

error or warning everyone says that this is not the answer because the program is not running because of it

**Comment by rokm** [comment]
> error or warning everyone says that this is not the answer because the program is not running because of it

If the program is not running, we need to see the run-time error, not the build-time warnings.

**Comment by FlorinPT** [comment]
> If the program is not running, we need to see the run-time error, not the build-time warnings.

The program does not give any errors and does not work. I did not understand your purpose. Because of these warnings, the torch requirements are not in the program and the program opens but does not work.

**Comment by rokm** [comment]
> > If the program is not running, we need to see the run-time error, not the build-time warnings.
> 
> The program does not give any errors and does not work. I did not understand your purpose. Because of these warnings, the torch requirements are not in the program and the program opens but does not work.

Those warnings are coming from binary dependency analysis which indeed fails to find those DLLs because of dynamically added search paths (something we will hopefully address with #6925), but our [`torch` hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-torch.py) collects pretty much the whole `site-packages/torch` directory, including `site-packages/torch/lib` where those DLLs (`torch_cuda_cpp.dll`, `torch_cuda_cu.dll`, `c10.dll `, etc.) are located. So if you open you frozen application directory (assuming you are building in `onedir` mode; if you use `onefile`, switch to `onedir` for easier debugging), you can check if they are in `torch/lib` subdirectory.

>  the program opens but does not work

Are you running the program from the console (assuming you are using a console-enabled build; if you use `--noconsole`/`--windowed` parameter then remove for now) or by double clicking on the executable?

**Comment by FlorinPT** [comment]
> > > If the program is not running, we need to see the run-time error, not the build-time warnings.
> > 
> > 
> > The program does not give any errors and does not work. I did not understand your purpose. Because of these warnings, the torch requirements are not in the program and the program opens but does not work.
> 
> Those warnings are coming from binary dependency analysis which indeed fails to find those DLLs because of dynamically added search paths (something we will hopefully address with #6925), but our [`torch` hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-torch.py) collects pretty much the whole `site-packages/torch` directory, including `site-packages/torch/lib` where those DLLs (`torch_cuda_cpp.dll`, `torch_cuda_cu.dll`, `c10.dll `, etc.) are located. So if you open you frozen application directory (assuming you are building in `onedir` mode; if you use `onefile`, switch to `onedir` for easier debugging), you can check if they are in `torch/lib` subdirectory.
> 
> > the program opens but does not work
> 
> Are you running the program from the console (assuming you are using a console-enabled build; if you use `--noconsole`/`--windowed` parameter then remove for now) or by double clicking on the executable?

I solved it when I did those warnings as you said, but these are there.


281 WARNING: Failed to collect submodules for 'pkg_resources._vendor.pyparsing.diagram' because importing 'pkg_resources._vendor.pyparsing.diagram' raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'
372 WARNING: Failed to collect submodules for 'setuptools._vendor.pyparsing.diagram' because importing 'setuptools._vendor.pyparsing.diagram' raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'
C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py:157: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
  warnings.warn('No audio backend is available.')

**Comment by rokm** [comment]
> 281 WARNING: Failed to collect submodules for 'pkg_resources._vendor.pyparsing.diagram' because importing 'pkg_resources._vendor.pyparsing.diagram' raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'
> 372 WARNING: Failed to collect submodules for 'setuptools._vendor.pyparsing.diagram' because importing 'setuptools._vendor.pyparsing.diagram' raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'
> C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py:157: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
> **import**(package)
> C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
> warnings.warn('No audio backend is available.')

These should have no impact on your program. If your program is still not running, the problem is likely elsewhere.

**Comment by FlorinPT** [comment]
> > 281 WARNING: Failed to collect submodules for 'pkg_resources._vendor.pyparsing.diagram' because importing 'pkg_resources._vendor.pyparsing.diagram' raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'
> > 372 WARNING: Failed to collect submodules for 'setuptools._vendor.pyparsing.diagram' because importing 'setuptools._vendor.pyparsing.diagram' raised: AttributeError: module 'railroad' has no attribute 'DiagramItem'
> > C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\PyInstaller\building\build_main.py:157: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
> > **import**(package)
> > C:\Users\PC\AppData\Local\Programs\Python\Python39\lib\site-packages\torchaudio\backend\utils.py:67: UserWarning: No audio backend is available.
> > warnings.warn('No audio backend is available.')
> 
> These should have no impact on your program. If your program is still not running, the problem is likely elsewhere.

My program is still not working. There is no problem when you run it as a normal script.
