### ISSUE TITLE
Add command options for data files (datas) and binaries.

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#703]
**Original date**: 2013/04/10
**Original reporter**: *davecortesi AND gmail DOT  COOM *

After the command options changed and added in 2.0 and 2.1, there remains only one frequent reason for editing the spec file: the need to bundle additional files with the app. A useful enhancement for 2.2 would be to add command-line options for this purpose. For example:

- `--addfile=`*path-to-file* Include a single file in the bundle;  *path-to-file* can be absolute or relative to cwd;  ex. `--addfile=../src/README.txt`  (?does this need to be quoted? Or can it be quoted? `--addfile='My Documents\project\src\README')

- `--addtree=(`*path-to-dir* `,` *runtime-folder-name* `,` *exclude-pattern* `)` Basically the Tree class syntax, the 2nd and 3rd args can be omitted or null strings.

Either option can be given multiple times. They just end up as more input to COLLECT or EXE but now the user doesn't have to tweak the spec file to get them. Even if the user will end up tweaking the spec file for this or other uses, it would be useful to have these as options of `pyi-makespec` to get the spec file off to a good start.

**Comment by shrx** [comment]
Just came to say I'm looking forward to this, IMO it's a really useful addition.

**Comment by RavisMsk** [comment]
That is really useful option, because *.spec* contains absolute path in *pathex*, and this makes usage of pyinstaller with same .spec on different machines kind of difficult.

**Comment by htgoebel** [comment]
@RavisMsk
> because .spec contains absolute path

You can easily adopt this to relative paths or whatever you need. The .spec file ist just a special Python program.
