### ISSUE TITLE
Docstrings of `exec_statement` and `eval_statement` have a note with an incorrect version number

### ISSUE THREAD

**Issue by absassi** [pyinstaller/pyinstaller#7034]
## Description of the issue

This is a documentation issue.

The docstrings of `exec_statement` and `eval_statement` in `PyInstaller.utils.hooks` contains the following note:

    Notes:
        As of v4.6.0, usage of this function is discouraged in favour of the
        new :mod:`PyInstaller.isolated` module.

However, the `PyInstaller.isolated` module does not exist in versions 4.6-4.10. It is only available starting from 5.0.

**Comment by bwoodsend** [comment]
Yeah, that docstring was written before we decided that `PyInstaller.isolated` should wait until the next major release. Thanks for pointing that out.
