### ISSUE TITLE
ModuleNotFoundError: No module named 'torch'

### ISSUE THREAD

**Issue by FlorinPT** [pyinstaller/pyinstaller#7041]
Fatal Python error: init_sys_streams: can't initialize sys standard streams
Python runtime state: core initialized
Traceback (most recent call last):
  File "C:\Users\PC\AppData\Local\Programs\Python\Python39\Lib\site-packages\torchvision\io\__init__.py", line 1, in <module>
ModuleNotFoundError: No module named 'torch'

Added paths: 

C:/Users/PC/AppData/Local/Programs/Python/Python39/Lib/site-packages/torch/lib
C:/Users/PC/AppData/Local/Programs/Python/Python39/Lib/site-packages/torchvision
C:/Users/PC/AppData/Local/Programs/Python/Python39/Lib/site-packages/torchaudio

**Comment by FlorinPT** [comment]
Why did you close? @bwoodsend

**Comment by bwoodsend** [comment]
Because this is an issue tracker where people report bugs, providing the diagnostics information you chose to ignore from the issue template - not a place you can dump half a stacktrace and expect people to waste their time fixing your code for you.

**Comment by FlorinPT** [comment]
Is it my problem? this is the problem of your codes

**Comment by FlorinPT** [comment]
There is a module and it cannot find it. I enter the path of the module, but it still cannot find it.
