### ISSUE TITLE
Outdated links in README

### ISSUE THREAD

**Issue by BLKSerene** [pyinstaller/pyinstaller#7043]
### Context information (for bug reports)

The link in the [support section of README](https://github.com/pyinstaller/pyinstaller#support) is dead, maybe should be updated and linked to [When Things Go Wrong](https://pyinstaller.org/en/stable/when-things-go-wrong.html)?

And the links in the [usage section](https://github.com/pyinstaller/pyinstaller#usage) and [changelog section](https://github.com/pyinstaller/pyinstaller#changes-in-this-release) both direct to v5.0.1 of the doc, should be linked to the latest version of the doc.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

None (Doc-related)

### Stacktrace / full error message

None (Doc-related)

**Comment by bwoodsend** [comment]
For once I find myself saying that you didn't need to fill out the issue template just for this.
