### ISSUE TITLE
Implementing Onelib mode (Exe outside the dir)

### ISSUE THREAD

**Issue by LcyDev** [pyinstaller/pyinstaller#7051]
**Is your feature request related to a problem? Please describe.**
Onefile is slow compared to onelib, because of having to extract all the libraries to a temporary directory.

Onelib instead doesn't have to do any of this but instead you get a folder filled of things that you don't really want to see.

**Describe the solution you'd like**
Most programs deal with this by having the exe topfolder from the libraries.

In pyinstaller this doesn't exist, however there was some workarounds... until they didn't work anymore.

**Describe alternatives you've considered**
I suppose the only alternative would be to make a separate executable which opens the program executable inside the mess (by compiling a main.c or something)

**Info**

Since the last issue (#1048) mentioning this was in 2014, i decided to open a new one.

Mostly because i'm trying to implement this feature by myself and some friends.
It would be nice if someone could provide an updated steps like the provided in original issue to make it easier. (Since that's probably outdated)
I'm currently implementing the argument "--onelib" and then i'll look into making it work.

But, lastly, would this be even worth it?
I don't want to make this if it's going to generate a lot of issues.
In that case i would prefer to make the topfolder EXE in .c and save myself the headache.

**Comment by LcyDev** [comment]
Also, would the path be changed for the script?
Meaning if my code creates files, would them be inside of the lib folder? (not wanted)

**Comment by rokm** [comment]
> But, lastly, would this be even worth it?

That probably depends on whom you ask; there's certainly been several requests for this. But to put it very bluntly, in spite of what #1048 says about "happily accepting this feature", I personally have no interest in maintaining another build mode, with its own set of corner cases and search-path-related semantics.

If you don't want users to look into the frozen application's directory, create an installer that sets up shortcuts to the executable. Or use a launcher .bat script in one directory above. Or a launcher executable, like you suggested.

> Also, would the path be changed for the script?
> Meaning if my code creates files, would them be inside of the lib folder? (not wanted)

That depends on how and where your code creates files. But ideally, the frozen application should be considered immutable and the code should not be writing files into application directory in the first place. Instead, use application-specific directory in user's home directory. That way, your code won't fail if someone puts the application into read-only location, and it will also handle multi-user setups.

**Comment by bwoodsend** [comment]
I a kinda impressed at how little has changed since #1048. That todo list hasn't aged at all although I think that the bit about `DYLD_LIBRARY_PATH` is naive of the Mach-O header rewriting polava PyInstaller still contains.

> But to put it very bluntly, in spite of what https://github.com/pyinstaller/pyinstaller/issues/1048 says about "happily accepting this feature", I personally have no interest in maintaining another build mode, with its own set of corner cases and search-path-related semantics.

I would be keen on having this purely in the hope that it would reduce the number of people using `--onefile` mode and learning the hard way why `--onefile` mode is useless on macOS and near useless on Windows.

The idea of testing this makes me very uncomfortable though. We currently run almost all of our tests twice - once in `--ondir` and once in `--onefile` mode. Despite the fact that this more than doubles the time it takes to run the test suite (currently about 90 minutes per platform/Python version), we've never dared to reduce this to only running a few tests in both modes then picking a single mode for the rest because mode-specific bugs are common and show up in such unexpected places. Adding a third mode, which is in fact a whole family of new modes we if make the lib's location relative to the exe configurable, is going to blow that up completely.

**Comment by LcyDev** [comment]
I see, yeah this would be more of a pain than anything else.
We won't focus too much in this since i have a lot of other stuff pending but i'll try to make it work at least.

I already made the wrapper in C and it works nicely.

**Comment by dunkmann00** [comment]
> I would be keen on having this purely in the hope that it would reduce the number of people using --onefile mode and learning the hard way why --onefile mode is useless on macOS and near useless on Windows.

@bwoodsend Could you elaborate on this? I've used `--onefile` on macOS and Windows for a simple cli project that I've bundled and it seems fine?

**Comment by bwoodsend** [comment]
On Windows, every program ran for the first time gets fed through MS Defender and most likely some even less effective antivirus like MacAffee or AVG. On macOS, every program ran for the first time gets scanned and compared to some hidden Apple database of known malicious software. Both of these can take ages depending on the size of the software.

In onefile mode, which unpacks itself afresh every time it's ran, the unpacked application is _new_ in the eyes of the operating system so it gets scanned every time it runs. So long story short, your startup time can go way up depending on your security setup.

**Comment by dunkmann00** [comment]
I see, thanks for explaining that! I was aware on macOS about Gatekeeper, but didn't realize that there would be any problems after the first time a downloaded binary was run. After reading your reply I looked into it and found [this](https://support.apple.com/guide/security/protecting-against-malware-sec469d47bd8/web) from Apple, and I gather 'XProtect' is what you are referring to (on macOS).

Well, this is definitely good to keep in mind when freezing. Thanks again for responding and all your work on PyInstaller!
