### ISSUE TITLE
Dynamic Extracting with --onefile

### ISSUE THREAD

**Issue by Worldwidebrine** [pyinstaller/pyinstaller#7060]
## Is your feature request related to a problem? Please describe.
When I run my exe created with `--onefile` and `--add-data`, it extracts **all files** into temp dir, including files **not needed** according to user's choice.

## Describe the solution you'd like
Allow us to add data that will be extracted only when requested by the script.

## Describe alternatives you've considered
Append zip to exe, making it extractable.
```
copy /b out.exe+sfx.zip sfx.exe
```
```py
import sys
from zipfile import ZipFile
dynamicdata = ZipFile(sys.executable, "r")
```
I'm not sure if this is a good idea, but it works anyway.

**Comment by rokm** [comment]
I don't see this happening. The `onefile` mode is intended to provide a self-extracting archive for the (whole) application, not a mechanism for providing optional features for your application.

From technical standpoint, the extraction happens in bootloader before your python code is ran, so there's no way for your code (or your user) to influence what gets extracted and what does not. I suppose we could introduce a special type of TOC entry for the archive that is not automatically extracted, but that means we'd need to make the PyInstaller's archive reader code (the python version) available at the runtime.

If you have optional data you don't want/need extracted every time, use custom zip like you suggested. Although embedding it in executable like that will likely work only on Windows (and only for one such archive), so I think using external zip packages in addition to the main executable would be better.

**Comment by bwoodsend** [comment]
I'd also point out that, since the only possible reason I can think of for doing this is reducing startup time, the bottleneck in extraction isn't the extraction itself - rather it's the antivirus scan/codesign verification that's triggered on any extracted `.dll`/`.so`/`.dylib` files. If your data files are just data files then not extracting them isn't going to save you a noticeable amount of time.

**Comment by julienfr112** [comment]
I totally understand the "wontfix" status, as it seems complicated to implement. But I would really happy to have this feature. My use case is to deploy a backend that needs large binaries. The pyinstaller one-file is also the cli for the backend (start, stop ...) and the time it takes to decompress the python code is ok, but it become a problem when the large binaries are decompressed, even if they are not required at all in most commands.
