### ISSUE TITLE
How to prevent my app  from re-extraction which converted to exe by pyinstaller

### ISSUE THREAD

**Issue by meddany** [pyinstaller/pyinstaller#7061]
Hello!

I built a mid-webapp scale. I converted it to EXE onefile. using pyinstaller. and it works fine.
My only concern here.  if i share this app with some people. they  would easly re-extract it and get the source code. Is there anyway ( even if it is weak ) to prevent EXE from re-extracted again ?

**Comment by bwoodsend** [comment]
See #5988
