### ISSUE TITLE
urllib exception if exe path is on remote directory

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#707]
**Original date**: 2013/04/17
**Original reporter**: *atrepaul AND yahoo DOT  COOM *

Hello,

I use PyInstaller v2.0-338-g555e9f7 (the "development code" that I downloaded from your web site on february 22nd 2013).

This is for Windows, with python2.7.3

The generated exe file works perfectly when launched from the local hard disk of any Windows computer.
But it raises an exception in urllib if the path that leads to the exe file is on a remote computer and the path is long (seems to trigger a 8.3 DOS path in PyInstaller) :

```
encoded_params = urllib.urlencode(params)
try:
  f = urllib.urlopen('%s/oneShowSyncCgi.py?%s' % (webServerURL, encoded_params))
except:
  print sys.exc_info()[0]  #  returns this :  <type 'exceptions.IOError'>
  print sys.exc_info()[1]  #  returns this :  [Errno socket error] [Errno 11003] getaddrinfo failed
```

-This exception only happens if the exe file is on a Linux file server (accessed by Windows computers using the samba mount point provided by Linux), and only if the path is long enough to trigger a 8.3 DOS path.
-Same problem if the remote directory is write enable or not.

-Using a drive letter (H:\myPath) or an UNC path doesn't fix the problem.

-I tried to us PyInstaller on Windows XP 32bit (using the standard python.org installation), and also on Windows Seven 64bit (using ActivePython), same problem.

-Then I tried urllib2 instead of urllib, and then I even tried httplib, same problem...

Here is the page that explains this 11003 getaddrinfo error :
http://msdn.microsoft.com/en-us/library/windows/desktop/ms740668%28v=vs.85%29.aspx#WSANO_RECOVERY

I attach the spec file and the output logs.

Any idea ?

Thanks.

**Comment by matysek** [comment]
All errors with unicode paths and 8.3 dos paths should be fixed latest dev version
