### ISSUE TITLE
MacOS/Python3.10: "The document could not be opened" when launching app bundle by drag&drop file or Open With

### ISSUE THREAD

**Issue by luejerry** [pyinstaller/pyinstaller#7071]
## Description of the issue

After building a MacOS windowed app bundle using Python 3.10, launching the app by drag & dropping a registered file type to the app icon or right click file -> "Open With" produces an error "The document {file.ext} could not be opened. {program} cannot open files in the {ext name} format." The app then starts successfully but does not receive the Open Document event.

The app does receive the Open Document event properly without error if the same is done while the app is already running.

Switching my Python version to 3.7.5 to build the app resolved the issue (I did not test other versions).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.3```
* Version of Python: 3.10.6
* Platform: macOS 12.2 (Intel)
* How you installed Python: pyenv
* Did you also try this on another platform? Does it work there?
  * Did not test on other MacOS versions. Works on Python 3.7.5
* try the latest development version
  * Same error is encountered, if using Python 3.10

### A minimal example program which shows the error

This issue is reproducible using the exact example from the official documentation: [Open event handling in a tkinter-based gui application](https://pyinstaller.org/en/stable/feature-notes.html#open-event-handling-in-a-tkinter-based-gui-application).

1. Copy the code and spec file from example
2. Build under Python 3.10
3. Make sure the app is not running and run the example commands. The error is produced when the first `open` command is run.

### Stacktrace / full error message

System dialog with error message: "The document {file.ext} could not be opened. {program} cannot open files in the {ext name} format."

**Comment by rokm** [comment]
What version of Tcl/Tk is your `pyenv`-built Python 3.10.6 using? For example, what is the output if you run the following snippet in your python:
```python
from tkinter import Tcl; print(Tcl().eval("info patchlevel")
```

**Comment by luejerry** [comment]
> What version of Tcl/Tk is your `pyenv`-built Python 3.10.6 using?

8.6.11

**Comment by rokm** [comment]
> > What version of Tcl/Tk is your `pyenv`-built Python 3.10.6 using?
> 
> 8.6.11

Any chance you can try with 8.6.12 instead?

**Comment by luejerry** [comment]
Building with Tk 8.6.12 fixed the problem. Thank you!
