### ISSUE TITLE
exe creation failing after upgrading Python, with a ctypes error

### ISSUE THREAD

**Issue by bwoodsend** [pyinstaller/pyinstaller#7072]
### Discussed in https://github.com/orgs/pyinstaller/discussions/7069

<div type='discussions-op-text'>

<sup>Originally posted by **qazmlpok** September  6, 2022</sup>
I had a working pyinstaller setup for a WxPython project. This weekend I decided to upgrade my local python and packages; now pyinstaller isn't working.

I am able to use it on the WxPython sample projects, so it shouldn't be an issue with WxPython. I have a spec file, but I get the exact same result even if I target the pyw file directly.

The full stack trace is:

```python
Traceback (most recent call last):
  File "C:\Program Files\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Program Files\Python310\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\__main__.py", line 178, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\__main__.py", line 59, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 934, in main
    build(specfile, distpath, workpath, clean_build)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 856, in build
    exec(code, spec_namespace)
  File "E:\temp\temp\quivi-64\quivi.spec", line 7, in <module>
    a = Analysis(
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 381, in __init__
    self.__postinit__()
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 660, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\isolated\_parent.py", line 238, in call
    return isolated.call(function, *args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\isolated\_parent.py", line 176, in call
    raise RuntimeError(f"Child process call to {function.__name__}() failed with:\n" + output)
RuntimeError: Child process call to find_binary_dependencies() failed with:
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\building\build_main.py", line 162, in find_binary_dependencies
    return bindepend.Dependencies(binaries, redirects=binding_redirects, xtrapath=extra_libdirs)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\depend\bindepend.py", line 205, in Dependencies
    for ftocnm, fn in getAssemblyFiles(pth, manifest, redirects):
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\depend\bindepend.py", line 373, in getAssemblyFiles
    for assembly in getAssemblies(pth):
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\depend\bindepend.py", line 327, in getAssemblies
    res = winmanifest.GetManifestResources(pth)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\utils\win32\winmanifest.py", line 979, in GetManifestResources
    return winresource.GetResources(filename, [RT_MANIFEST], names, languages)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 156, in GetResources
    res = _GetResources(hsrc, types, names, languages)
  File "C:\Program Files\Python310\lib\site-packages\PyInstaller\utils\win32\winresource.py", line 125, in _GetResources
    data = win32api.LoadResource(hsrc, type_, name, language)
  File "C:\Program Files\Python310\lib\site-packages\win32ctypes\pywin32\win32api.py", line 166, in LoadResource
    return _common._PyBytes_FromStringAndSize(pointer, size)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_c_ubyte instance instead of c_char_p
```

The final bit is in pywin32, but reverting pywin32 back to 303 (from 304) also changes nothing.

Since it works for the WxPython sample projects, I'm sure the issue has to be with my project somehow, but I don't know where to begin to look. Especially because it used to work before I upgraded everything.</div>

**Comment by bwoodsend** [comment]
@qazmlpok Could you inject a `print(filename)` just before the return statement at `C:\Program Files\Python310\lib\site-packages\PyInstaller\utils\win32\winmanifest.py`, line 979 then rerun so we know which file its failing over?

**Comment by qazmlpok** [comment]
C:\Program Files\Python310\python310.dll.

The other parameters are None

**Comment by rokm** [comment]
The error is coming from `pywin32-ctypes`, not `pywin32` (not that it makes much of a difference, since it has not been updated in a while).

```
  File "C:\Program Files\Python310\lib\site-packages\win32ctypes\pywin32\win32api.py", line 166, in LoadResource
    return _common._PyBytes_FromStringAndSize(pointer, size)
ctypes.ArgumentError: argument 1: <class 'TypeError'>: expected LP_c_ubyte instance instead of c_char_p
``` 
This is rather odd, because if I instrument that file in my local installation, `pointer` is in fact an instance of `ctypes.c_char_p`, and there is no error. And the [function signature](https://github.com/enthought/pywin32-ctypes/blob/5b8c08b9e4580af93de62a2a34a02b37abc7a591/win32ctypes/core/ctypes/_common.py#L32-L35) seems to also expect `c_char_p`.  What version of python (including revision/patch-level) are you using? And just in case, what version of `pywin32-ctypes` do you have installed (presumably 0.2.0)?

(As a side note, this is `ctypes`-based codepath in `pywin32-ctypes`; perhaps installing `cffi` and triggering `cffi` codepath may work-around this problem?).

**Comment by qazmlpok** [comment]
Python 3.10.6
pywin32-ctypes            0.2.0
pyinstaller               5.3

Fresh install of Python, using the Windows installer from the website.

I added some more print statements to the win32api.py file, right before the troublesome line.

```
Backend is ctypes
Right before _common._PyBytes_FromStringAndSize; c_char_p(140729425658016) <class 'ctypes.c_char_p'> 1349 <class 'int'>
```

Then I ran it again on the wx sample project, which still works:

```
PATH: C:\Program Files\Python310\python310.dll
Backend is ctypes
Right before _common._PyBytes_FromStringAndSize; c_char_p(140729434374304) <class 'ctypes.c_char_p'> 1349 <class 'int'>
PATH: C:\Program Files\Python310\VCRUNTIME140.dll
PATH: C:\Program Files\Python310\DLLs\select.pyd
Backend is ctypes
Right before _common._PyBytes_FromStringAndSize; c_char_p(140730699051168) <class 'ctypes.c_char_p'> 1349 <class 'int'>
PATH: C:\Program Files\Python310\DLLs\_decimal.pyd
Backend is ctypes
Right before _common._PyBytes_FromStringAndSize; c_char_p(1442532137120) <class 'ctypes.c_char_p'> 1349 <class 'int'>
PATH: C:\Program Files\Python310\DLLs\_hashlib.pyd
```

And so on. 

I don't know what the str of c_char_p is supposed to represent, but it is using c_char_p in every instance and working in one place and not the other.

**Comment by rokm** [comment]
Hmmm, how is your application's code organized, then? Do you have all code that is not part of the entry-point script in a single package, or are there multiple top-level modules/packages next to the entry-point script?

**Comment by qazmlpok** [comment]
The entry point file imports wx directly. Other dependencies are brought in from other files, only where they're needed.

Is it better to just put all the definite dependencies in the main file? The older version (of python and pyinstaller) was able to pick up all the imports without issue.

**Comment by rokm** [comment]
> The entry point file imports wx directly. Other dependencies are brought in from other files, only where they're needed.
> 
> Is it better to just put all the definite dependencies in the main file? The older version (of python and pyinstaller) was able to pick up all the imports without issue.

No. I'm asking about top-level modules because PyInstaller extends python's search path to include the directory where the entry-point script is located. Which means that any top-level modules next to the entry-point script might end up shadowing their standard lib counterparts, which tends to lead to odd errors involving changed behavior during pyinstaller's build... it seems like a bit of a stretch in this case, but I cannot think of any other reason why the behavior would change like that.

Just to be sure, can you try running the offending function manually from python interpreter? E.g.,  open python interpreter, and run:
```python
from PyInstaller.depend.bindepend import getAssemblyFiles
getAssemblyFiles(r'C:\Program Files\Python310\python310.dll')
```
then exit python, set PYTHONPATH to point to the top-level directory containing your entry-point script (e.g., run `set PYTHONPATH=C:\...` in command prompt before running `python.exe` in it), and then re-run the above snippet again. Do either of runs trigger the issue?

**Comment by rokm** [comment]
Another thing you can try is printing the `argtypes` of `_common._PyBytes_FromStringAndSize` to see what the expected argument types are (should be `ctypes.c_char_p` and `ctypes.c_longlong`). I.e., add a 
```python
print("Function:", _common._PyBytes_FromStringAndSize, _common._PyBytes_FromStringAndSize.argtypes)
``` 
before the problematic line.

**Comment by qazmlpok** [comment]
> Another thing you can try is printing the argtypes of _common._PyBytes_FromStringAndSize to see what the expected argument types are (should be ctypes.c_char_p and ctypes.c_longlong). 

That was the issue. The program interfaces with a dll, and I was modifying _PyBytes_FromStringAndSize. I didn't expect that would have external effects like this. Commenting out the block doing that enables the exe to build.

Thanks for the help, all.

**Comment by bwoodsend** [comment]
That's a relief.
