### ISSUE TITLE
Documentation for pyinstaller not updated following issue #6053

### ISSUE THREAD

**Issue by J-Cheetham** [pyinstaller/pyinstaller#7073]
Follow on from #6053
Following the pyinstaller docs for bundling multiple apps together lead me to the same errors as documented in issue #6053 

There was a follow on issue raised #6094 to improve the docs but it appears this has not be performed. The out of date documentation is still causing issues for pyinstaller users so this is a request to bring it up to date.

**Comment by rokm** [comment]
Please don't open duplicate issues - doing so won't get them solved any faster...
