### ISSUE TITLE
The bug report template redirects to a non-existing support mailing list page

### ISSUE THREAD

**Issue by ericzolf** [pyinstaller/pyinstaller#7077]
The bug template in GitHub states:

> Welcome to the PyInstaller issue tracker! Before creating an issue, please heed the following:
> 
> 1. This tracker should only be used to report bugs and request features / enhancements to PyInstaller
>     - For questions and general support, use the mailing list, see
> 	  <http://www.pyinstaller.org/support.html#mailing-list>

The page doesn't exist and I couldn't find any reference to a mailing list.

**Comment by bwoodsend** [comment]
You're right. It should just point to the mailing list page https://groups.google.com/g/pyinstaller?pli=1

**Comment by ericzolf** [comment]
This said, I then discovered the GitHub discussions at https://github.com/pyinstaller/pyinstaller/discussions - not sure which one is preferred.

**Comment by Legorooj** [comment]
I've updated it to redirect people to the discussions page.
