### ISSUE TITLE
cant include pywin32 lib

### ISSUE THREAD

**Issue by MarvinZhong** [pyinstaller/pyinstaller#7081]
my code using pywin32 lib
when try to compile to exe with pyinstaller
its always fail when detecting "pywintypes310.dll" or "pythoncom310.dll"
tried different version from 5.0 to 5.4.1
when tried version 5.0 to 5.3 its fail with error
```
SystemExit: Unable to find "C:\Users\User\AppData\Local\Programs\Python\Python310\pythoncom310.dll
Could not open file mapping object (2)." when adding binary and data files.
```
when tried version 5.4 or 5.4.1 its fail with error
```
SystemExit: Unable to find "C:\Users\User\AppData\Local\Programs\Python\Python310\pywintypes310.dll
Could not open file mapping object (2)." when adding binary and data files.
```
anyone have the same problems? any help appreciated, Thanks

**Comment by rokm** [comment]
> SystemExit: Unable to find "C:\Users\User\AppData\Local\Programs\Python\Python310\pythoncom310.dll
> Could not open file mapping object (2)." when adding binary and data files.

Hmm, those leading and ending quotes look like there was error in the hook and the error message became part of the filename.

Can you try running this in your python environment:
```python
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
get_pywin32_module_file_attribute('pywintypes')
```
What is the output?

And what is the output if you run:
```python
import pywintypes
pywintypes.__file__
```
or 
```python
import pythoncom
pythoncom.__file__
```

**Comment by MarvinZhong** [comment]
```python
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
get_pywin32_module_file_attribute('pywintypes')
```

##### the output

```
'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\pywintypes310.dll\r\nCould not open file mapping object (2).'
```

<hr>

```python
import pywintypes
pywintypes.__file__
```

##### the output

```
'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\pywintypes310.dll'
```

<hr>

```python
import pythoncom
pythoncom.__file__
```

##### the output

```
'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\pythoncom310.dll'
```

#### the problem probably come from the first function, is there a way to fix it?

**Comment by MarvinZhong** [comment]
### I think I found temp solution thanks to @rokm 

I notice that the return value is a string,

>```
>'C:\\Users\\User\\AppData\\Local\\Programs\\Python\\Python310\\pywintypes310.dll\r\nCould not open file mapping object (2).'
>```
so i just split it and get the first value,
and i did this to both hook-pywintypes.py and hook-pythoncom.py

```python
# As Is
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
dll_filename = get_pywin32_module_file_attribute('pywintypes')
```

```python
# To Be
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
dll_filename = get_pywin32_module_file_attribute('pywintypes').split('\r\n')[0]
```

```python
# As Is
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
dll_filename = get_pywin32_module_file_attribute('pythoncom')
```

```python
# To Be
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
dll_filename = get_pywin32_module_file_attribute('pythoncom').split('\r\n')[0]
```

and i got the idea that just write the path as string could works too

```python
# To Be
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
dll_filename = 'C:\Users\User\AppData\Local\Programs\Python\Python310\pythoncom310.dll'
```

```python
# To Be
from PyInstaller.utils.hooks import get_pywin32_module_file_attribute
dll_filename = 'C:\Users\User\AppData\Local\Programs\Python\Python310\pywintypes310.dll'
```

Still its doesn't solve why its giving output:

> Could not open file mapping object (2)

I mostly ignore it because it doesn't affect the code

**Comment by bwoodsend** [comment]
We ought to get rid of that `exec_statement()` call so I'll leave this one open.

https://github.com/pyinstaller/pyinstaller/blob/6c8a6a53c359622d5e9f22e934eb3ae71fd0efb5/PyInstaller/utils/hooks/win32.py#L41-L47

**Comment by rokm** [comment]
> We ought to get rid of that `exec_statement()` call so I'll leave this one open.

At this point, we should probably get rid of them all...
