### ISSUE TITLE
Protect the python code using a password

### ISSUE THREAD

**Issue by yarona1993** [pyinstaller/pyinstaller#7098]
Ask for a password before decrypting the python bytecode
The password could be supply by environment variable, stdin or a process argument
Then the loader will use the password as the decryption key for the python bytecodes

**Comment by bwoodsend** [comment]
Why not just put your program in an encrypted zip file? Then you don't have to supply the password every time and PyInstaller startup routines don't have to get any more complicated than they already are.

**Comment by amoh-godwin** [comment]
@yarona1993 if you are going to do what @bwoodsend is saying, you should check out [zipimport](https://pymotw.com/3/zipimport/index.html)
