### ISSUE TITLE
No enough documentation covering libraries

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#710]
**Original date**: 2013/04/23
**Original reporter**: *anonymous*

Hello,

My project is set up in Eclipse.  I have a src directory with my own programming.  I have a lib with, among other things, pysnmp and pyans1.  I can get the pyinstaller to finish, but it never shows the pysnmp libraries (that's the first error--so the other libraries are likely not there either).  

However, I cannot seem to find a coherent example.  I'm sure that once I'm more familiar with the product, the documentation will make more sense, but for right now, I'm still struggling with simply adding libraries, eggs, etc.  And frequently when I try to follow a link, I get a 404 error from this site.

Could you please post--prominently--the accepted way to get the libraries in there?

Thank you.

**Comment by htgoebel** [comment]
This is an old issue from anonymous. No chance to get into dialogue.
