### ISSUE TITLE
ModuleNotFoundError: No module named 'requests' in GitHub release zip and tar.gz

### ISSUE THREAD

**Issue by jtravell** [pyinstaller/pyinstaller#7108]
## Description of the issue
  
A `ModuleNotFoundError: No module named 'requests'` error is being thrown every time we try to run an app that was:  
1.) compiled using pyinstaller and 
2.) compressed by a GitHub release into either a zip or a tar.gz archive on a windows-latest GitHub runner.  
  
This problem only occurs with windows releases.  By contrast, a linux-version of this process works perfectly in Ubuntu-latest GitHub runners.  
THE SAME ERROR OCCURS WHETHER THE WINDOWS ZIP OR THE WINDOWS TAR.GZ ARCHIVE IS USED.    
   
**ERROR MESSAGE:**  
  
The error message is:  
  
    Traceback (most recent call last):
      File "myapp.py", line 5, in <module>
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "one_module_in_myapp.py", line 6, in <module>
    About to: run myapp
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "another_module_in_myapp.py", line 7, in <module>
      File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
      File "third_module_in_myapp.py", line 6, in <module>
    ModuleNotFoundError: No module named 'requests'
    [2748] Failed to execute script 'myapp' due to unhandled exception!
    inside one_module_in_myapp.py
    About to dir
    
    Error: Process completed with exit code 1.
  
**RECREATING THE ERROR:**  
    
You can recreate this error in the following two steps:  
  
First, use pyinstaller to compile a version of a python app that requires the `requests` module and push the compiled windows app files in non-compressed form to a branch of a repository called something like windows-release.  We did this with the following GitHub workflow.  
  
    name: compile-app
    on:
      push:
        branches:
          - test
    jobs:
      create-windows-exe-and-push-to-windows-release-branch:
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v3
            with:
              token: ${{ secrets.HUSH }}
          - shell: pwsh
            name: Create exe
            run: |
              python -m pip install --upgrade pip PyYaml
              python -m pip install --upgrade pip pyinstaller
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\myappwinrel\\
              echo "About to start"
              cd app
              del __init__.py
              echo "About to: pyinstaller myapp.py"
              pyinstaller myapp.py
              echo "About to dir"
              dir
              echo "About to dir D:\\a\\RepoName\\RepoName\\app\\dist\\myapp\\"
              cd D:\\a\\RepoName\\RepoName\\app\\dist\\myapp\\
              dir
              Move-Item -Path "D:\\a\\RepoName\\RepoName\\app\\dist\\myapp\\*" -Destination "C:\\Users\\runneradmin\\myappwinrel\\"
              echo "About to dir C:\\Users\\runneradmin\\myappwinrel\\"
              cd C:\\Users\\runneradmin\\myappwinrel\\
              dir
              Get-ChildItem D:\a\RepoName\RepoName -recurse | foreach ($_) {remove-item $_.fullname -recurse}
              echo "About to dir D:\\a\\RepoName\\RepoName\\ "
              cd D:\\a\\RepoName\\RepoName\\
              dir
              Move-Item -Path "C:\\Users\\runneradmin\\myappwinrel\\*" -Destination "D:\\a\\RepoName\\RepoName\\"
          - shell: cmd
            name: Push to release-windows branch
            env:
              GIT_PAT: ${{ secrets.HUSH }}
            run: |
              echo "About to dir C:\\Users\\runneradmin\\myappwinrel\\"
              cd C:\\Users\\runneradmin\\myappwinrel\\
              dir 
              set repoWithToken="https://"$GIT_PAT"@github.com/AccountName/RepoName.git"
              git config --global user.email "username@mydomain.com"
              git config --global user.name "AccountName"
              git init
              git remote add origin %repoWithToken%
              git add --all
              git commit -am "pushed from compile-app"
              git push --force -u origin HEAD:release-windows
    
Second, run the following workflow to create a windows release and then to retrieve the windows release archive, expand the archive, and try to run the app that pyinstaller compiled:  
  
    name: release-manually
    on:
      workflow_dispatch:
        inputs:
          version:
            description: 'Version'
            required: true
            type: string
          description:
            description: 'Description of release'
            required: true
            type: string
    jobs:
      release-a-windows-version:
        runs-on: windows-latest
        steps:
          - shell: pwsh
            name: Release
            env:
              DESCRIPTION: ${{ inputs.description }}
              VERSION: ${{ inputs.version }}
              GH_TOKEN: ${{ secrets.HUSH }}
            run: |
              $vers="windows-"+$env:VERSION
              $nameOfRelease="RepoName-"+$vers
              echo "About to create release"
              gh api --method POST -H "Accept: application/vnd.github+json" /repos/AccountName/RepoName/releases -f tag_name=$vers -f target_commitish='release-windows' -f name=$nameOfRelease -f body="$env:DESCRIPTION" -F draft=false -F prerelease=false -F generate_release_notes=false 
      download-release-and-run-myapp:
        needs: [release-a-windows-version]
        runs-on: windows-latest
        steps:
          - uses: actions/checkout@v3
          - id: ConfigureWindowsAgent 
            uses: ./.github/actions/windows-provisioner
          - shell: pwsh
            name: Download and extract Release
            env:
              DESCRIPTION: ${{ inputs.description }}
              VERSION: ${{ inputs.version }}
              GH_TOKEN: ${{ secrets.HUSH }}
            run: |
              $vers="windows-"+$env:VERSION
              $repoWithToken = '"https://"+$env:GH_TOKEN+"@github.com/AccountName/RepoName"'
              echo "About to download release"
              mkdir staging
              gh release download $vers --archive tar.gz --repo $repoWithToken
              $folderName="RepoName-"+$vers
              $tarName=$folderName+".tar.gz"
              tar -xvf $tarName -C staging
              Get-ChildItem -Path "staging" -Recurse | Copy-Item -Destination "C:\\Users\\runneradmin\\myapphome\\"
              echo "About to dir C:\\Users\\runneradmin\\myapphome\\"
              cd C:\\Users\\runneradmin\\myapphome\\
              dir 
          - name: Run myapp
            run: |
              $env:Path += ";C:\\Users\\runneradmin\\myapphome\\"
              cd C:\\stgng\\
              echo 'About to: run myapp'
              myapp 

The code for `.github/actions/windows-provisioner/action.yml` that is referenced by the above workflow is as follows:  

    name: 'Configure Windows Agent'
    description: 'Prepares Windows-latest agents.'
    runs:
      using: "composite"
      steps:
        - name: Configure agent
          shell: pwsh
          run: |
              New-Item -ItemType Directory -Force -Path C:\\stgng\\
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\myappconfig\\
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\myapp\\
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\myapp\\keys\\
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\myapp\\keys\\adminAccounts\\
              python -m pip install --upgrade pip requests
              python -m pip install --upgrade pip PyYaml
              python -m pip install --upgrade pip IPy
              python -m pip install --upgrade pip pyinstaller
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\keys\\
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\keys\\starter\\
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\myapp\\logs\\
              New-Item -ItemType Directory -Force -Path C:\\Users\\runneradmin\\myapphome\\
              New-Item -ItemType Directory -Force -Path D:\\a\\RepoName\\myappAdmin\\
              New-Item -ItemType Directory -Force -Path D:\\a\\RepoName\\myappAdmin\\binaries\\
              $old = (Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name path).path
              $new  =  "$old;C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64\\Scripts\\"  
              echo "About to set item property"
              Set-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name path -Value $new
              echo "About to show permanent PATH"
              Get-ItemProperty -Path 'Registry::HKEY_LOCAL_MACHINE\System\CurrentControlSet\Control\Session Manager\Environment' -Name path
              echo "About to add to temporary PATH"
              $env:Path += ";C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64\\Scripts\\"
              echo "About to show temporary PATH"
              echo $env:Path
      
The version of pyinstaller is the latest version retrieved by the `python -m pip install --upgrade pip pyinstaller` command.  
  
### Context information (for bug reports)
  
* Output of `pyinstaller --version`: 5.4.1
* Version of Python: 3.9
* Platform: Windows
* How you installed Python: GitHub windows-latest comes with python pre-installed, so we used that.

**Comment by rokm** [comment]
Unless I'm missing something, I don't see you installing `requests` anywhere in your example workflow. Is the same true for your actual workflow?

**Comment by jtravell** [comment]
@rokm Of course we install `requests`.  Have you been able to recreate this **BUG** in your software in the 7 hours since you posted your comment above?  No one can use pyinstaller to release windows versions in GitHub until you resolve this.  

Per your question, requests is installed using `python -m pip install --upgrade pip requests`, not only in the `windows-provisioner` action that is referenced in the code, but also explicitly during repeated variations of the `Download and extract release` step shown above.  We even tried a variation of installing `requests` in the same folder in which Python is installed.  And the compiled code works **BEFORE** it is pushed into the `gh api` create release api call, so the problem seems to occur when the pyinstaller-compiled app is zipped and tarred.  We did not include all the many things we tried because the OP states that this works in `ubuntu-latest` without all the additional redundant additions of `requests` installation attempts.

You need to recreate this **BUG**  in a minimal GitHub repository.  The code we gave should be sufficient for you to recreate this **BUG** quickly.

**Comment by rokm** [comment]
> Per your question, requests is installed using `python -m pip install --upgrade pip requests`, not only in the `windows-provisioner` action that is referenced in the code...

I don't see `windows-provisioner` referenced anywhere in the `compile-app` workflow and its `create-windows-exe-and-push-to-windows-release-branch` job that you posted in your issue report. Nor do I see that workflow installing `requests` via `pip` before PyInstaller is called. 

> ...but also explicitly during repeated variations of the `Download and extract release` step shown above.

Installing `requests` *after* compiling your application with PyInstaller won't magically put the missing `requests` module in the frozen application.

> You need to recreate this BUG in a minimal GitHub repository. The code we gave should be sufficient for you to recreate this BUG quickly.

The code you provided is either incomplete and does not reflect your actual workflow (i.e., does not reflect that `requests` is available at the time when you run pyinstaller, if you keep insisting that you *do* install it) or it is incorrect (does not install the `requests` before running PyInstaller). As such, I see no reason to investigate this any further.

> We did not include all the many things we tried because the OP states that this works in `ubuntu-latest` without all the additional redundant additions of `requests` installation attempts.

I cannot comment on your `ubuntu-latest` workflow without seeing it, either. For all I know, you could be properly installing `requests` in that environment.

**Comment by jtravell** [comment]
@rokm The call to the windows provisioning code has always been in every version of the OP and is:  

        - uses: actions/checkout@v3
        - id: ConfigureWindowsAgent 
          uses: ./.github/actions/windows-provisioner

Since these 3 lines are in the same job and are placed before the step where the crippling **BUG** in your software manifests, it is clear that all of the windows provisioning lines have been run on the same machine where your crippling **BUG** manifests and before your crippling **BUG** manifests.  We assumed that you are familiar with GitHub actions syntax to see this, given that you have a GitHub repository.  

We have also now added the explicit code from `.github/actions/windows-provisioner/action.yml` to the OP above to remove all ambiguity.  

When will you resolve this crippling **BUG** in your software that was reported a day ago?  

@itszero @bwhite @bwhite @edrex  Are you able to help resolve this crippling **BUG** in your software?  We are trying to help you improve your product.

**Comment by bwoodsend** [comment]
You appear to be adding `C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64\\Scripts` to PATH but nowhere to you ensure that `C:\\hostedtoolcache\\windows\\Python\\3.10.7\\x64` appears in PATH so `python` could resolve to anything from Chocolatey's Python to that silly Python auto-install shim from the Windows store. You're also appending rather than prepending meaning that any other Python environments will take precedence over that 3.10.7 environment you're trying to use.

But whatever, @jtravell I'm going to block you since not only are you using this issue tracker as a generic _fix my code for me_ forum, but you can't even do it in a civilised manner.
