### ISSUE TITLE
Splash screen closes and then reopens

### ISSUE THREAD

**Issue by ughstudios** [pyinstaller/pyinstaller#7121]
I am calling `pyi_splash.close()` and it flickers off for a second and then reopens. Is this normal? How can I not have this happen?

**Comment by ughstudios** [comment]
This seems to happen when using the `multiprocessing` module. It reopens the local .exe file, which causes it to trigger the splash to open again. Are there any workarounds?

**Comment by rokm** [comment]
> Are there any workarounds?

Nope. 

We'll have to add an option to disable splash screen via environment variable to the bootloader. And then have the main process set that environment variable so that splash screen disabled in any subsequent executable runs within child processes...

**Comment by rokm** [comment]
@ughstudios Would you be able to provide a minimum example that exhibits this behavior? I tried to reproduce it locally with a simple program that uses `multiprocessing` (`multiprocessing.Process`), but it seems to work as expected without having to be fixed...

**Comment by iamyb** [comment]
if splash is used together with [gooey](https://github.com/chriskiehl/Gooey), then will show again after click the start in gooey GUI. It can be reproduced by a very basic gooey example. @rokm

**Comment by rokm** [comment]
> if splash is used together with [gooey](https://github.com/chriskiehl/Gooey), then will show again after click the start in gooey GUI. It can be reproduced by a very basic gooey example. @rokm

Yes, anything that spawns a sub-process using `sys.executable` without restoring `_MEIPASS2` environment variable prior to doing so will end up showing the splash screen again (and in the case of onefile builds, will also cause the sub-process to run as a new parent process and unpack into separate temporary directory). 

But with `multiprocessing` (that the OP mentioned),this should not be the case, because our run-time hook explicitly [restores `_MEIPASS2`](https://github.com/pyinstaller/pyinstaller/blob/f563dce1e83fd5ec72a20dffd2ac24be3e647150/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L55-L73) (but for that to work properly, `multiprocessing.freeze_support` needs to be called before any `multiprocessing` primitives are used).

I think to properly handle everything else, we should invert the logic that is trying to accommodate one PyInstaller-frozen application trying to run a different PyInstaller-frozen application; instead of clearing `_MEIPASS2` and restoring it before selected few subprocess calls, we should keep it set and instead use a different environment variable to track the current application's archive location. And if that changes, we should reset `_MEIPASS2` in the child application. (And `_MEIPASS2` will likely need to be renamed to something else to avoid issues when child application is made with older PyInstaller version). The plan is to do this eventually - primarily because it would help simplify run-time hook for `multiprocessing`, and potential run-time hooks for other multiprocessing frameworks, but it should also help with the splash screen.

**Comment by rokm** [comment]
> > if splash is used together with [gooey](https://github.com/chriskiehl/Gooey), then will show again after click the start in gooey GUI. It can be reproduced by a very basic gooey example. @rokm
> 
> Yes, anything that spawns a sub-process using `sys.executable` without restoring `_MEIPASS2` environment variable prior to doing so will end up showing the splash screen again (and in the case of onefile builds, will also cause the sub-process to run as a new parent process and unpack into separate temporary directory).
> 
> But with `multiprocessing` (that the OP mentioned),this should not be the case, because our run-time hook explicitly [restores `_MEIPASS2`](https://github.com/pyinstaller/pyinstaller/blob/f563dce1e83fd5ec72a20dffd2ac24be3e647150/PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py#L55-L73) (but for that to work properly, `multiprocessing.freeze_support` needs to be called before any `multiprocessing` primitives are used).
> 
> I think to properly handle everything else, we should invert the logic that is trying to accommodate one PyInstaller-frozen application trying to run a different PyInstaller-frozen application; instead of clearing `_MEIPASS2` and restoring it before selected few subprocess calls, we should keep it set and instead use a different environment variable to track the current application's archive location. And if that changes, we should reset `_MEIPASS2` in the child application. (And `_MEIPASS2` will likely need to be renamed to something else to avoid issues when child application is made with older PyInstaller version). The plan is to do this eventually - primarily because it would help simplify run-time hook for `multiprocessing`, and potential run-time hooks for other multiprocessing frameworks, but it should also help with the splash screen.

On the other hand, even with above changes in place, we will need to ensure that `pyi_splash` module does not show warnings when imported in a sub-process (which ideally should not happen, but might be unavoidable).

I think the straightforward way would be to not delete the `_PYIBoot_SPLASH` environment variable [here](https://github.com/pyinstaller/pyinstaller/blob/f563dce1e83fd5ec72a20dffd2ac24be3e647150/PyInstaller/fake-modules/pyi_splash.py#L97-L112), but instead set it to "handled" or something like that. Then the bootloader could check if `_PYIBoot_SPLASH` is set and skip the splash screen in that case, while `pyi_splash` module would suppress the warnings if `_PYIBoot_SPLASH` is set to "handled". And we can implement this change independently of what I described in the previous post.

This means that if splash-enabled program A runs splash-enabled program B as a helper, the splash of the program B will also end up suppressed, but I think that's an acceptable tradeoff. Once the full program change detection based on changed archive (described in previous post) is in place, we can reset `_PYIBoot_SPLASH` on change, which would enable the splash of the program B in this scenario.

**Comment by dperez-01** [comment]
Is the fix already developed and launched? I am still facing this issue.
```
if __name__ == '__main__':
    from multiprocessing import freeze_support
    freeze_support()

    import ctypes.wintypes
    ctypes.windll.shcore.SetProcessDpiAwareness(True)
    import sys
    if getattr(sys, 'frozen', False):
        import pyi_splash
```

Those are my very first lines, just so you know, as I might be doing something wrong (new to multiprocessing). Also, consider I am using a `pathos.multiprocessing` `ProcessPool` instance. Windows 11, Python 3.11.2, Pyinstaller 6.0.0

**Comment by rokm** [comment]
> Is the fix already developed and launched? I am still facing this issue.
> 
> ```
> if __name__ == '__main__':
>     from multiprocessing import freeze_support
>     freeze_support()
> 
>     import ctypes.wintypes
>     ctypes.windll.shcore.SetProcessDpiAwareness(True)
>     import sys
>     if getattr(sys, 'frozen', False):
>         import pyi_splash
> ```
> 
> Those are my very first lines, just so you know, as I might be doing something wrong (new to multiprocessing). Also, consider I am using a `pathos.multiprocessing` `ProcessPool` instance. Windows 11, Python 3.11.2, Pyinstaller 6.0.0

Nope. 

And `pathos.multiprocessing` is not supported anyway, unless it is using stdlib `multiprocessing` (as opposed to 3rd-party `multiprocess`). But if that's the case, there is no point in using `pathos` over directly using `multiprocessing`.

**Comment by dperez-01** [comment]
>>`pathos.multiprocessing` is not supported anyway, unless it is using stdlib `multiprocessing`

Well considering that, it may actually work, as according to pathos docs:

>>This module contains map and pipe interfaces to python’s multiprocessing module.

Thanks for your fast response

**Comment by paulmueller** [comment]
I was trying to look into this issue, but I am having trouble finding out where `_PYIBoot_SPLASH` is defined in the [bootloader sources](https://github.com/paulmueller/pyinstaller/tree/splash_disable_on_subprocess/bootloader/src). Is there some magic happening that rewrites environment variable names (I am not fluent in C)?

**Comment by rokm** [comment]
> I was trying to look into this issue, but I am having trouble finding out where `_PYIBoot_SPLASH` is defined in the [bootloader sources](https://github.com/paulmueller/pyinstaller/tree/splash_disable_on_subprocess/bootloader/src). Is there some magic happening that rewrites environment variable names (I am not fluent in C)?

The variable is set by the Tcl script that sets up the splash screen, https://github.com/pyinstaller/pyinstaller/blob/070c6ea5634388a5abadc53fa7e064c56b630897/PyInstaller/building/splash_templates.py#L66

If you plan on poking around, a warning - the related parts of the code (and the splash screen behavior) are going to significantly change in the (hopefully near) future: https://github.com/rokm/pyinstaller/tree/subprocess-environment-inheritance

**Comment by paulmueller** [comment]
Thanks for the heads-up. I have managed to modify the bootloader to disable the splash screen when `_PYIBoot_SPLASH="handled"`: https://github.com/paulmueller/pyinstaller/commit/167b43610fa87bca3f78ce2131b291f21532480a

If anyone would like to try this: You can install my changes via
```
pip install https://github.com/paulmueller/pyinstaller/archive/splash_disable_on_subprocess.zip
```
and then set the environment variable `PYINSTALLER_COMPILE_BOOTLOADER=1` before running PyInstaller.

**Comment by paulmueller** [comment]
Thanks for the heads-up. I have managed to modify the bootloader to disable the splash screen when `_PYIBoot_SPLASH="handled"`: https://github.com/pyinstaller/pyinstaller/compare/develop...paulmueller:pyinstaller:splash_disable_on_subprocess

If anyone would like to try this: You can install my changes via
```
pip install https://github.com/paulmueller/pyinstaller/archive/splash_disable_on_subprocess.zip
```
and then set the environment variable `PYINSTALLER_COMPILE_BOOTLOADER=1` before running PyInstaller.

**Comment by dperez-01** [comment]
> Thanks for the heads-up. I have managed to modify the bootloader to disable the splash screen when `_PYIBoot_SPLASH="handled"`: [develop...paulmueller:pyinstaller:splash_disable_on_subprocess](https://github.com/pyinstaller/pyinstaller/compare/develop...paulmueller:pyinstaller:splash_disable_on_subprocess)
> 
> If anyone would like to try this: You can install my changes via
> 
> ```
> pip install https://github.com/paulmueller/pyinstaller/archive/splash_disable_on_subprocess.zip
> ```
> 
> and then set the environment variable `PYINSTALLER_COMPILE_BOOTLOADER=1` before running PyInstaller.

Thank you very much :). I will try it with my app in approximately a week.
