### ISSUE TITLE
[125942] Cannot open PyInstaller archive from executable for aws cli package

### ISSUE THREAD

**Issue by jauyzed** [pyinstaller/pyinstaller#7130]
Hello. I'm running into a issue with pyinstaller for aws cli: 

$ aws 
[125942] Cannot open PyInstaller archive from executable (/usr/local/aws-cli/v2/2.8.0/dist/aws) or external archive (/usr/local/aws-cli/v2/2.8.0/dist/aws.pkg)

$ pip3 list
Package                   Version
------------------------- -------
altgraph                  0.17.3
pip                       20.2.4
pyinstaller               5.4.1
pyinstaller-hooks-contrib 2022.10
setuptools                50.3.2

$ python3 --version
Python 3.9.7

AWS support suggested I report this error in this forum. to get some answers. Thanks

**Comment by bwoodsend** [comment]
I don't understand what you're trying to report. Is this your own PyInstaller-ified build of aws-cli? Is it downloaded from RHEL's package repositories? What does PyInstaller have to do with aws-cli?

**Comment by jauyzed** [comment]
@bwoodsend 
It is just the aws-cli binary that I'm trying to install from AWS: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html

Upon install/upgrade successful: 
$ aws --version
[126449] Cannot open self /usr/local/aws-cli/v2/2.6.4/dist/aws or archive /usr/local/aws-cli/v2/2.6.4/dist/aws.pkg

I tried downgrading the version of aws cli from latest to a previous version of aws-cli 2.6.4 which is also resulting the same error. I did follow the process of uninstall of aws cli with removal of aws directories which is described here: https://docs.aws.amazon.com/cli/latest/userguide/uninstall.html 

I have tried installing latest pyinstaller with pip which didn't resolve this issue. 
`

**Comment by rokm** [comment]
What is the output of `ls -l /usr/local/aws-cli/v2/2.8.0/dist/aws`? (Or whatever version you have installed at the moment)

**Comment by jauyzed** [comment]
It is all set to root. I have changed the ownership to non root which has resolved the issue. Now the non-root user is able to execute the aws commands

I looked into this error message here: https://github.com/pyinstaller/pyinstaller/blob/develop/bootloader/src/pyi_main.c#L159. 
If the error might have said something about permission, it would have been helpful.
