### ISSUE TITLE
`from some_name.app import another_name` get skipped on macOS 

### ISSUE THREAD

**Issue by jourdain** [pyinstaller/pyinstaller#7133]
## Description of the issue

When trying to bundle a simple application I realized that a module was skipped for no reason on macOS probably because it has a path/name similar to a macOS app (something.app). 

### Context information

* Output of `pyinstaller --version`: ```5.4.1```
* Version of Python: 3.9.9
* Platform:  OS X
* How you installed Python: pyenv
* Did you also try this on another platform? Does it work there? 
  * Yes it works on Linux and Windows

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```sh
python3 -m venv .venv
source .venv/bin/activate
pip install -U pip
pip install trame pyinstaller
```

Create a file `simple.py`

```python
from trame.app import get_server
from trame.ui.vuetify import SinglePageLayout
from trame.widgets import vuetify, vtk

server = get_server()

with SinglePageLayout(server) as layout:
    with layout.content:
        with vuetify.VContainer(fluid=True, classes="pa-0 fill-height"):
            with vtk.VtkView():
                with vtk.VtkGeometryRepresentation():
                    vtk.VtkAlgorithm()

if __name__ == "__main__":
    server.start()
```

You can validate that the code works by running `python simple.py` which should open your browser with a 3D cone if your port 8080 is free. If need be you can provide a port by adding a `--port 1234` arg.

Then build an executable directory by running pyinstaller as follow

```sh
pyinstaller \
    --name "cone" \
    --hidden-import pkgutil \
    --collect-data trame \
    --collect-data trame_client \
    --collect-data trame_vuetify \
    --collect-data trame_vtk \
    simple.py
```

Then try to run the generated bundle

```sh
./dist/cone/cone 
Traceback (most recent call last):
  File "simple.py", line 1, in <module>
    from trame.app import get_server
ModuleNotFoundError: No module named 'trame.app'
[60853] Failed to execute script 'simple' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
Hmm, it works for me. I've got it going on Linux and a macOS 12 M1 machine. The .app suffix sounds like a red herring to me. It's more likely to be something in your environment such as a file named `trame.py` floating around in your project somewhere. PyInstaller should have written a file named `build/cone/xref-cone.html` - could you upload that?

**Comment by jourdain** [comment]
Thanks for looking into that. I had to zip it but you can find it below.

[xref-cone.html.zip](https://github.com/pyinstaller/pyinstaller/files/9725215/xref-cone.html.zip)

**Comment by jourdain** [comment]
Searching for all the trame.py within my test bed directory

```sh
find . -name trame.py 
./.venv/lib/python3.9/site-packages/trame/modules/trame.py
./.venv/lib/python3.9/site-packages/trame/widgets/trame.py
./.venv/lib/python3.9/site-packages/trame_client/widgets/trame.py
./.venv/lib/python3.9/site-packages/trame_components/widgets/trame.py
```

**Comment by rokm** [comment]
Looks like all `trame` imports are marked as missing, so they weren't discoverable during the build. 

One way this could happen is if `pyinstaller` command somehow does not resolve to the one in your venv, but to some other installation that happens to be in `PATH` (I haven't seen that happen with a venv, though). What is the output of `which pyinstaller`? Any change if you invoke it as `python -m PyInstaller ...` instead of `pyinstaller ...`?

**Comment by jourdain** [comment]
Wow! That was it, thank you so much! Not sure how I got a global pyinstaller into pyenv...

```sh
type pyinstaller
pyinstaller is /Users/sebastien.jourdain/.pyenv/shims/pyinstaller
```

Running the following worked

```sh
python -m  PyInstaller \
    --name "cone" \
    --hidden-import pkgutil \
    --collect-data trame \
    --collect-data trame_client \
    --collect-data trame_vuetify \
    --collect-data trame_vtk \
    simple.py
```
