### ISSUE TITLE
pyinstaller created image loop many times

### ISSUE THREAD

**Issue by jdai** [pyinstaller/pyinstaller#7136]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
5.4.1 and latest daily version
* Version of Python: 
4.10.4 and 4.10.7
* Platform: 
Win11 and Ubuntu 20.04
* How you installed Python: 
python.org/downloads
* Did you also try this on another platform? Does it work there?
both Ubuntu and Windows, both 5.4.1 or daily zip, results the same. If I run source .py it is ok.

* try the latest development version, using the following command:
tried already
```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ x] start with clean installation
  * [ x] use the latest development version
  * [ x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ NA] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.
not sure how to 

### A minimal example program which shows the error

```
"""
    racon supplement: check/install required packages
    
    jodai@amperecomputing.com
"""


import importlib.util
import subprocess
import sys

# add the required packages here without any version numbers
requirements = ['PySimpleGUI', 'beautifulsoup4', 'logging', 'openpyxl', 'pillow', 'regex']


def is_venv():
    """
        check if running inside virtual environment
    """
    if hasattr(sys, 'real_prefix') or (hasattr(sys, 'base_prefix') and sys.base_prefix != sys.prefix):
        return True
    else:
        return False


def install_missing_pkgs():
    """
        install missing pkgs based on requirements list
    """
    reterr = 0
    missing_pkgs = [pkg for pkg in requirements if importlib.util.find_spec(pkg) is None]
    if missing_pkgs:
        print('required pkgs: ', requirements)
        print('missing pkgs: ', missing_pkgs)
        for pkg in missing_pkgs:
            if is_venv():
                cmd = [sys.executable, "-m", "pip", "install", '--upgrade', pkg]
            else:
                cmd = [sys.executable, "-m", "pip", "install", '--user', '--upgrade', pkg]
            print('running command:', ' '.join(cmd))
            reterr |= subprocess.run(cmd, shell=False).returncode
    return reterr


if __name__ == "__main__":
    install_missing_pkgs()
    
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by jdai** [comment]
after added debug in .spec, how to debug it?

**Comment by bwoodsend** [comment]
A PyInstaller not only doesn't contain pip but it doesn't contain a Python interpreter. `sys.execitable` points to the EXE file you just built. `subprocess.run([sys.exectuable, ...anything])` therefore means restart your application. You certainly can't install packages into a frozen application because it's _frozen_ i.e. immutable.

And FWIW, even outside of PyInstaller, installing packages on the fly like that is a terrible way to handle dependencies.

**Comment by jdai** [comment]
my windows binary works fine. On Ubuntu, the problem is I installed required pkg, and IDE still install them, yet binary cannot found it. The No.1 problem of python is too many versions on too many folders. 
thanks for clarify. I thought pyinstaller could include all referenced pkg. Another thing is I tried to add binary option it doesn't work well.
