### ISSUE TITLE
Empty DEST not allowed when adding binary and data files.

### ISSUE THREAD

**Issue by q1225** [pyinstaller/pyinstaller#7144]
LunarCreek.py

**Comment by q1225** [comment]
Empty DEST not allowed when adding binary and data files. Maybe you want to used '.'.
Caused by 'LunarCreek.py'.
 datas=[('LunarCreek.py',''),('a1.JPG','/lunarcreek/FBG/'),('b1.JPG','/lunarcreek/FBG/'),('b2.JPG','/lunarcreek/FBG/'),('b3.JPG','/lunarek/FBG/'),('b4.JPG','/lunarcreek/FBG/'),('b5.JPG','/lunarcreek/FBG/'),('b6.JPG','/lunarcreek/FBG/'),('b6_1.JPG','/lunarcreek/FBG/'),('b6_2.JPG','/lunarcreek/FBG/'),('b6_3.JPG','/lunarcreek/FBG/'),('b7.JPG','/lunarcreek/FBG/'),('b7_1.JPG','/lunarcreek/FBG/'),('b7_2.JPG','/lunarcreek/FBG/'),('b7_3.JPG','/lunarcreek/FBG/'),('b7_4.JPG','/lunarcreek/FBG/'),('b7_5.JPG','/lunarcreek/FBG/'),('b8.JPG','/lunarcreek/FBG'),('b8_1.JPG','/lunarcreek/FBG/'),('b8_2.JPG','/lunarcreek/FBG/'),('b8_3.JPG','/lunarcreek/FBG/'),('music_1.WAV','/lunarcreek/bm/'),('music_2.WAV','/lunarcreek/bm/'),('music3.WAV','/lunarcreek/bm/'),('349112__scriotxstudios__rusty-valve-turn-close.WAV','/lunarcreek/lunarcreek/SE/'),('618110__nachtmahrtv__banshee-scream-monster.WAV','/lunarcreek/lunarcreek/SE/'),('Door_Knocking_Sound_Effect.WAV','/lunarcreek/SE/'),('Free_Sound_Effect_Seal.WAV','/lunarcreek/SE/'),('Paper_Falling_Sound_Effect_(No_copyright_sound_effects)_Sounds.WAV','/lunarcreek/SE/'),('Running_Sound_Effect.WAV','/lunarcreek/SE/'),('Scary_Footsteps_Sound_Effect.WAV','/lunarcreek/SE/'),('Slap_Sound_Effect_Free.WAV','/lunarcreek/SE/'),('c1_base.PNG','/lunarcreek/C/'),('C1-angry.PNG','/lunarcreek/C/'),('c1-cry.PNG','/lunarcreek/C/'),('c1-happy.PNG','/lunarcreek/C/'),('C1-scared.PNG','/lunarcreek/C/'),('c1-smug.PNG','/lunarcreek/C/'),('c2.PNG','/lunarcreek/C/'),('C2-base.PNG','/lunarcreek/C/'),('C2-Happy.PNG','/lunarcreek/C/'),('C2-shocked.PNG','/lunarcreek/C/'),('C2-smug.PNG','/lunarcreek/C/'),('c3-angry.PNG','/lunarcreek/C/'),('c3-base.PNG','/lunarcreek/C/'),('C3-fusrated.PNG','/lunarcreek/C/'),('c3-happy.PNG','/lunarcreek/C/'),('c3-sorry.PNG','/lunarcreek/C/'),('C3-surprised.PNG','/lunarcreek/C/'),('c4.PNG','/lunarcreek/C/'),('c4_1.PNG','/lunarcreek/C/'),('c5.PNG','/lunarcreek/C/'),('c6.PNG','/lunarcreek/C/'),('c6_1.PNG','/lunarcreek/C/'),('c7.PNG','/lunarcreek/C/'),('c8.PNG','/lunarcreek/C/'),('c8_1.PNG','/lunarcreek/C/'),('c9.PNG','/lunarcreek/C/'),('sp-1.PNG','/lunarcreek/C/'),('sp-2.PNG','/lunarcreek/C/'),('audacity-win-3.2.0-64bit.exec','/lunarcreek/VC/'),('bea_scene_5.WAV','/lunarcreek/VC/'),('Bea_scene_7.WAV','/lunarcreek/VC/'),('bea_scene_8.WAV','/lunarcreek/VC/'),('Boss.WAV','/lunarcreek/VC/'),('Fannie_Scene1.WAV','/lunarcreek/VC/'),('Fannie_Scene2.WAV','/lunarcreek/VC/'),('Fannie_Scene3.WAV','/lunarcreek/VC/'),('Fannie_Scene4.WAV','/lunarcreek/VC/'),('Fannie_Scene5.WAV','/lunarcreek/VC/'),('Fannie_Scene6.WAV','/lunarcreek/VC/'),('Fannie_Scene6_5.WAV','/lunarcreek/VC/'),('Fannie_Scene7.WAV','/lunarcreek/VC/'),('Fannie_Scene8.WAV','/lunarcreek/VC/'),('InkeeperScene1f.WAV','/lunarcreek/VC/'),('InkeeperScene2.WAV','/lunarcreek/VC/'),('Museum_Guide.WAV','/lunarcreek/VC/'),('Person_Inside.WAV','/lunarcreek/VC/'),('Postmaster.WAV','/lunarcreek/VC/'),('robed_people.WAV','/lunarcreek/VC/'),('Cult_of_Seal_VN_lines_Final.docx','/lunarcreek/'),('Credits.docx','/lunarcreek/'),('Stone_Slide_Sound_Effects.WAV','/lunarcreek/SE/'),('Thud_Sound_Effect.WAV','/lunarcreek/SE/'),('Gypsy_Cruse.ttf','/lunarcreek/')]

**Comment by bwoodsend** [comment]
Just use `.` as the dest field.

**Comment by q1225** [comment]
could u give an example

**Comment by q1225** [comment]
cause the program is not following the path

**Comment by q1225** [comment]
"C:\Users\sherry\a1.JPG" when adding binary and data files.

**Comment by bwoodsend** [comment]
> Just use `.` as the dest field.

https://pyinstaller.org/en/stable/runtime-information.html#placing-data-files-at-expected-locations-inside-the-bundle

**Comment by q1225** [comment]
when i follow the doc it give me invaild syntax

**Comment by q1225** [comment]
datas=[('/lunarcreek/FBG/*.jpg','FBG'),('/lunarcreek/bm/*.wav','bm'),('/lunarcreek/SE/*.wav','SE'),('/lunarcreek/C/*.png','C'),('/lunarcreek/VC/*.wav','VC'),('/lunarcreek/*.docx','docs'),(,'/lunarcreek/gui/font/*.ttf','font')],

**Comment by bwoodsend** [comment]
That's because you've got an extra comma before `'/lunarcreek/gui/font/*.ttf'`.

**Comment by q1225** [comment]
it can find them although the path is correct

**Comment by q1225** [comment]
can't

**Comment by bwoodsend** [comment]
Do you really have `lunacreek` installed at the root of your filesystem?

Look, if you're not comfortable dealing with file path syntax then you're not ready to be using PyInstaller.
