### ISSUE TITLE
Pyinstaller fails to compile PyTorch on M1/arm64

### ISSUE THREAD

**Issue by samheather** [pyinstaller/pyinstaller#7151]
## Description of the issue

When freezing an application for M1/arm64 making use of PyTorch, PyInstaller fails due to detecting binaries with incorrect target architectures. These same binaries can be traced through to the venv used to run the application via the Python interpreter successfully.

The same issue has been reported and fixed in Nuitka (similar to PyInstaller) - see [here](https://github.com/Nuitka/Nuitka/issues/1774) and [here](https://bytemeta.vip/repo/pytorch/pytorch/issues/84351).

Seems likely to be an issue with the integration with torch/pytorch? I'm continuing to dig into this and get as simple as an example as possible, but wanted to raise ASAP in-case you had an any immediate indication of what might be going on here and ideas.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.4.1```
* Version of Python: 3.10.7
* Platform: macOS
* How you installed Python: via python.org
* Did you also try this on another platform? Does it work there?: N/A, as other dependencies in this project are arm64-only.

* try the latest development version, using the following command: **yes, done, no change**

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and **yes, done, no change**

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

This is the best example I've got today - it has a few extra components, but none impact the issue described. I'll try to put together another example if required, but it's slightly temperamental.

http://github.com/samheather/pyinstaller-pytorch-hook-issue-demo/

### Stacktrace / full error message

```
38678 DEBUG: Signing file '/Users/samuel/Library/Application Support/pyinstaller/bincache00_py310_64bit/arm64/adhoc/no-entitlements/torch/_C.cpython-310-darwin.so'
Traceback (most recent call last):
  File "/Users/samuel/git/imaginAIry/venv/bin/pyinstaller", line 8, in <module>
    sys.exit(run())
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 179, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 60, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 962, in main
    build(specfile, distpath, workpath, clean_build)
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 884, in build
    exec(code, spec_namespace)
  File "/Users/samuel/git/imaginAIry/demo.spec", line 53, in <module>
    coll = COLLECT(
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/building/api.py", line 876, in __init__
    self.__postinit__()
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/building/api.py", line 908, in assemble
    fnm = checkCache(
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/building/utils.py", line 381, in checkCache
    osxutils.binary_to_target_arch(cachedfile, target_arch, display_name=fnm)
  File "/Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/PyInstaller/utils/osx.py", line 323, in binary_to_target_arch
    raise IncompatibleBinaryArchError(
PyInstaller.utils.osx.IncompatibleBinaryArchError: /Users/samuel/git/imaginAIry/venv/lib/python3.10/site-packages/torch/_dl.cpython-310-darwin.so is incompatible with target arch arm64 (has arch: x86_64)!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
As mentioned in the issues you linked, this is a problem with `torch` `arm64` wheels - they ship `x86_64`  version of the `torch._dl` extension (`torch/_dl.cpython-310-darwin.so`). If `torch` functions on macOS M1 in spite of that, this means that this extension is unused, and can be safely removed from your `torch` installation (which, as far as I can see, is the work-around for the nuitka). 

You could also try to exclude it via `--exclude torch._dl` (which will work as long as the extension is collected due to import analysis). 

Ultimately, we might add conditional exclude to our [`torch` hook](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-torch.py), but we would first need to refactor it up into "proper" hook (instead of brute-force mess that it is at the moment), so that's pretty low-priority...

So I'm pretty much leaning towards `wontfix` on this one; let `torch` people clean up their `arm64` wheels.

**Comment by bwoodsend** [comment]
> So I'm pretty much leaning towards wontfix on this one; let torch people clean up their arm64 wheels.

Likewise. This is torch's packaging bug - not yet another thing for PyInstaller to hop around.

**Comment by samheather** [comment]
Thanks both, appreciate the input. In this specific case is there any way I can tell pyinstaller to ignore wheels and compile torch from source, either at freeze, or at time of set up of the venv (and for pyinstaller to subsequentially use _those_ arm64 compiled binaries)?

**Comment by rokm** [comment]
> Thanks both, appreciate the input. In this specific case is there any way I can tell pyinstaller to ignore wheels and compile torch from source, either at freeze, or at time of set up of the venv (and for pyinstaller to subsequentially use _those_ arm64 compiled binaries)?

PyInstaller only collects files from your build environment. So you have to build `torch` from source yourself, and then install it into your python environment. But you should first try just excluding the problematic extension (`--exclude torch._dl`); a copy will also be collected by the terrible brute-force hook, but that copy doesn't undergo binary analysis nor arch validation because it is marked as a data file. So I think the failure is due to actual EXTENSION entry that is picked up via modulegraph/imports analysis.

**Comment by samheather** [comment]
Thanks @rokm. I'll compile from source. Unfortunately `--exclude torch._dl` (output attached for others future reference, torch won't run without that file, so it looks like that file IS required at runtime when running under the interpreter). Maybe Rosetta is getting involved...

[out.txt](https://github.com/pyinstaller/pyinstaller/files/9748253/out.txt)

**Comment by rokm** [comment]
I presume this is your first time using `torch` , `PyInstaller`, and macOS (M1 or otherwise)? Take a look at #7052, and the link given there.
