### ISSUE TITLE
Missing 'pylibjpeg-libjpeg' plugin in pydicom library if building exe via pyinstaller

### ISSUE THREAD

**Issue by BJladika** [pyinstaller/pyinstaller#7157]
## Description of the issue
Hello, I tried to build app, which uses pydicom library via pyinstaller and it somehow misses some import (like dependency) so, it works uncorrectly if used with a some specific set of datasets (containing jpeg encoding kinda).

I reported to pydicom github, but they said its some issue with pyinstaller. https://github.com/pydicom/pydicom/issues/1712

So I'm reporting here. Maybe I needed to add some additional hidden import and it can be solved easily?

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.5``` (Also tried to build with 5.3 earlier)
* Version of Python: 3.10.6
* Platform: Windows 10 (RU) Home Edition (Superior OS)
* How you installed Python: python.org/downloads
* If I remember correctly, tried on Ubuntu too. Didn't work also.

### A minimal example program which shows the error

```python
from pydicom import dcmread

x = dcmread("test_1.dcm")
y = x.pixel_array
```

### app.spec settings
```
a = Analysis(
    ['xdataset.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=['pydicom.encoders.gdcm', 'pydicom.encoders.pylibjpeg'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='xdataset',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "xdataset.py", line 16, in <module>
  File "pydicom\dataset.py", line 1887, in pixel_array
  File "pydicom\dataset.py", line 1444, in convert_pixel_data
  File "pydicom\dataset.py", line 1556, in _convert_pixel_data_without_handler
  File "pydicom\dataset.py", line 1536, in _convert_pixel_data_without_handler
  File "pydicom\dataset.py", line 1563, in _do_pixel_data_conversion
  File "pydicom\pixel_data_handlers\pylibjpeg_handler.py", line 327, in get_pixeldata
  File "pydicom\pixel_data_handlers\pylibjpeg_handler.py", line 235, in generate_frames
RuntimeError: Unable to convert the Pixel Data as the 'pylibjpeg-libjpeg' plugin is not installed
[2716] Failed to execute script 'xdataset' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
Ughh, damn optional dependencies. Why can't they just pick a JPEG library and make it a dependency...

Because libjpeg is bolted in via an entry point, PyInstaller has no way of knowing that it needs to be collected. That causes [this line](https://github.com/pydicom/pydicom/blob/a8be738418dee0a2b93c241fbd5e0bc82f4b8680/pydicom/pixel_data_handlers/pylibjpeg_handler.py#L117) to silently return an empty dict which means that [_DECODERS](https://github.com/pydicom/pydicom/blob/a8be738418dee0a2b93c241fbd5e0bc82f4b8680/pydicom/pixel_data_handlers/pylibjpeg_handler.py#L117) is empty which means that [this check](https://github.com/pydicom/pydicom/blob/a8be738418dee0a2b93c241fbd5e0bc82f4b8680/pydicom/pixel_data_handlers/pylibjpeg_handler.py#L227-L235) is hit.

This command seems to get it working for me:

```
pyinstaller --hiddenimport=pydicom.encoders.gdcm --hiddenimport=pydicom.encoders.pylibjpeg --hiddenimport=pylibjpeg --copy-metadata=pylibjpeg-libjpeg --copy-metadata=numpy --hiddenimport=libjpeg --noconfirm --clean test.py

**Comment by BJladika** [comment]
Damn these dependencies indeed. 

Very interesting solution. I hope that sometime later there will be some automatical solution with building from one or other library. Cheers for help!
