### ISSUE TITLE
Pyinstaller doesn't see my local module

### ISSUE THREAD

**Issue by Gookuruto** [pyinstaller/pyinstaller#7158]
I trying to make executable file with command:
`pyinstaller -F .\eucentricity_finder\gui.py`

my directories looks like this:

|
->eucentricity_finder
    |
    ->gui.py
|
->workflow
    |
    ->eucentricity_api.py ...

and i got this error:

> 297 INFO: PyInstaller: 5.5
> 297 INFO: Python: 3.8.8
> 298 INFO: Platform: Windows-10-10.0.19041-SP0
> 300 INFO: wrote F:\repo\SEM_Automation\gui.spec
> 302 INFO: UPX is not available.
> 304 INFO: Extending PYTHONPATH with paths
> ['F:\\repo\\SEM_Automation']
> 645 INFO: checking Analysis
> 645 INFO: Building Analysis because Analysis-00.toc is non existent
> 646 INFO: Initializing module dependency graph...
> 648 INFO: Caching module graph hooks...
> 659 INFO: Analyzing base_library.zip ...
> 2129 INFO: Loading module hook 'hook-encodings.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 3517 INFO: Loading module hook 'hook-pickle.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 4030 INFO: Loading module hook 'hook-heapq.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 4503 INFO: Caching module dependency graph...
> 4660 INFO: running Analysis Analysis-00.toc
> 4664 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
>   required by c:\users\mpuchala\appdata\local\programs\python\python38\python.exe
> 4711 INFO: Analyzing F:\repo\SEM_Automation\eucentricity_finder_ui\gui.py
> 5485 INFO: Loading module hook 'hook-platform.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 5762 INFO: Loading module hook 'hook-difflib.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 6065 INFO: Loading module hook 'hook-sysconfig.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 6241 INFO: Loading module hook 'hook-PIL.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 6292 INFO: Loading module hook '[hook-PIL.Image.py](http://hook-pil.image.py/)' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 6847 INFO: Loading module hook 'hook-xml.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 6879 INFO: Loading module hook '[hook-xml.etree.cElementTree.py](http://hook-xml.etree.celementtree.py/)' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 7281 INFO: Loading module hook '[hook-PIL.ImageFilter.py](http://hook-pil.imagefilter.py/)' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\PyInstaller\\hooks'...
> 7355 INFO: Loading module hook 'hook-workflow.py' from 'c:\\users\\mpuchala\\appdata\\local\\programs\\python\\python38\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
> Traceback (most recent call last):
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\runpy.py", line 194, in _run_module_as_main
>     return _run_code(code, main_globals, None,
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\runpy.py", line 87, in _run_code
>     exec(code, run_globals)
>   File "C:\Users\mpuchala\AppData\Local\Programs\Python\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 179, in run
>     run_build(pyi_config, spec_file, **vars(args))
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\__main__.py", line 60, in run_build
>     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 963, in main
>     build(specfile, distpath, workpath, clean_build)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 885, in build
>     exec(code, spec_namespace)
>   File "F:\repo\SEM_Automation\gui.spec", line 7, in <module>
>     a = Analysis(
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 410, in __init__
>     self.__postinit__()
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
>     self.assemble()
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\building\build_main.py", line 573, in assemble
>     priority_scripts.append(self.graph.add_script(script))
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 268, in add_script
>     self._top_script_node = super().add_script(pathname)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1433, in add_script
>     self._process_imports(n)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
>     target_modules = self._safe_import_hook(*import_info, **kwargs)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 381, in _safe_import_hook
>     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
>     target_modules = self.import_hook(
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1518, in import_hook
>     submodule = self._safe_import_module(head, mname, submodule)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 428, in _safe_import_module
>     return super()._safe_import_module(module_basename, module_name, parent_package)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
>     self._process_imports(n)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
>     target_modules = self._safe_import_hook(*import_info, **kwargs)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 381, in _safe_import_hook
>     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2301, in _safe_import_hook
>     target_modules = self.import_hook(
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 1518, in import_hook
>     submodule = self._safe_import_module(head, mname, submodule)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 428, in _safe_import_module
>     return super()._safe_import_module(module_basename, module_name, parent_package)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2062, in _safe_import_module
>     self._process_imports(n)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\lib\modulegraph\modulegraph.py", line 2850, in _process_imports
>     target_modules = self._safe_import_hook(*import_info, **kwargs)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 368, in _safe_import_hook
>     excluded_imports = self._find_all_excluded_imports(source_module.identifier)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\analysis.py", line 356, in _find_all_excluded_imports
>     excluded_imports.update(module_hook.excludedimports)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 320, in __getattr__
>     self._load_hook_module()
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\depend\imphook.py", line 387, in _load_hook_module
>     self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\compat.py", line 609, in importlib_load_source
>     return mod_loader.load_module()
>   File "<frozen importlib._bootstrap_external>", line 462, in _check_name_wrapper
>   File "<frozen importlib._bootstrap_external>", line 962, in load_module
>   File "<frozen importlib._bootstrap_external>", line 787, in load_module
>   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
>   File "<frozen importlib._bootstrap>", line 702, in _load
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 783, in exec_module
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-workflow.py", line 14, in <module>
>     datas = copy_metadata('workflow')
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\PyInstaller\utils\hooks\__init__.py", line 991, in copy_metadata
>     dist = pkg_resources.get_distribution(package_name)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 478, in get_distribution
>     dist = get_provider(dist)
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 354, in get_provider
>     return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 909, in require
>     needed = self.resolve(parse_requirements(requirements))
>   File "c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\pkg_resources\__init__.py", line 795, in resolve
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'workflow' distribution was not found and is required by the application

i tried to create hook like this:
```
 from PyInstaller.utils.hooks import collect_all
 datas, binaries, hiddenimports = collect_all('workflow')
```
but it doesn't help. 

Any idea what can be wrong?

**Comment by rokm** [comment]
The problem is that we have an existing hook for a package called [`workflow`](https://pypi.org/project/workflow/) - it is being triggered by your `workflow` package due to name collision, and it is raising error because it expects the distribution metadata for the (actual) `workflow` package.

You will either have to remove the offending hook file (`c:\users\mpuchala\appdata\local\programs\python\python38\lib\site-packages\_pyinstaller_hooks_contrib\hooks\stdhooks\hook-workflow.py`) or rename your `workflow` to something else. 

Or even better, organize all your top-level modules into a top-level package (e.g., `myproject` or `eucentricity_finder`) with entry-point script being next to it.

**Comment by bwoodsend** [comment]
Perhaps we should start guarding hooks with
```python
try:
    importlib.metadata.distribution("distribution-name")
except importlib.metadata.PackageNotFoundError:
    skip
```
That won't be fun.

**Comment by Gookuruto** [comment]
rokm answer helped thanks alot 

> Perhaps we should start guarding hooks with
> 
> ```python
> try:
>     importlib.metadata.distribution("distribution-name")
> except importlib.metadata.PackageNotFoundError:
>     skip
> ```
> 
> That won't be fun.

this also would be helpful in the future.
