### ISSUE TITLE
i can't download the version regular of pyinstaller that download the version developer

### ISSUE THREAD

**Issue by Azaretdodo** [pyinstaller/pyinstaller#7176]
hello this was the error "enum34 is ever missing" now fornulately this problem is repair i have tried to download pyinstaller but the version developer is downloaded instead the version regular thus and finaly thanks you in advance to help myself download the version regular,

regards.

Azaretdodo.

**Comment by rokm** [comment]
Despite the appearances, this is an issue tracker, not a support forum...
