### ISSUE TITLE
I can't download the version regular unfortunately that download the version developer

### ISSUE THREAD

**Issue by Azaretdodo** [pyinstaller/pyinstaller#7177]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.0.1'''
* Version of Python: . 3.7 
* Platform: Windows (french)
* How you installed Python: python.org/downloads,
* Did you also try this on another platform? Does it work there? Yes on Ubuntu and that work good

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by bwoodsend** [comment]
You have long since demonstrated that you lack the knowledge to use command line tools or manage Python environments - both of which are core prerequisites to using PyInstaller successfully without wasting everyone else's time. No matter how much we baby sit you, you never get anywhere. You have also exhausted both Rok's and my patience.
