### ISSUE TITLE
macOS sign failure in 5.6

### ISSUE THREAD

**Issue by Safihre** [pyinstaller/pyinstaller#7185]
I just updated to 5.6 from 5.5 and now the [signing of the macOS binary fails](https://github.com/sabnzbd/sabnzbd/actions/runs/3319366181/jobs/5484435047#step:11:133).
```
63308 INFO: Signing the BUNDLE...
70586 WARNING: Error while signing the bundle: codesign command (['codesign', '-s', '***', '--force', '--all-architectures', '--timestamp', '--options=runtime', '--entitlements', 'builder/osx/entitlements.plist', '--deep', '/Users/runner/work/sabnzbd/sabnzbd/dist/SABnzbd.app']) failed with error code 1!
output: /Users/runner/work/sabnzbd/sabnzbd/dist/SABnzbd.app: replacing existing signature
/Users/runner/work/sabnzbd/sabnzbd/dist/SABnzbd.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /Users/runner/work/sabnzbd/sabnzbd/dist/SABnzbd.app/Contents/MacOS/jaraco.collections-3.6.0.dist-info
```
Based on the Breaking Changes section I was already fearing this.
 Since you were expecting problems, I was hoping you could tell me what to do now?
This `jaraco.collections` is just one of many dependencies.

EDIT: I just saw #7184 by @lordwelch, maybe that fixes it?

**Comment by rokm** [comment]
> EDIT: I just saw #7184 by @lordwelch, maybe that fixes it?

It should. Due to that typo, the relocation was not happening at all, regardless of whether the file was a .py/.pyc or not.

**Comment by Safihre** [comment]
Yes, it seems to have worked:
https://github.com/sabnzbd/sabnzbd/actions/runs/3319595160/jobs/5484944255

**Comment by bwoodsend** [comment]
v5.6.1 is out with the fix for this.
