### ISSUE TITLE
Docs: add `--log-level` to list of command-line options having an effect when building from a spec file

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#7194]
Docs say:

> Only the following command-line options have an effect when building from a spec file:

> - [--upx-dir](https://pyinstaller.org/en/v5.6.1/usage.html#cmdoption-upx-dir)

> - [--distpath](https://pyinstaller.org/en/v5.6.1/usage.html#cmdoption-distpath)

> - [--workpath](https://pyinstaller.org/en/v5.6.1/usage.html#cmdoption-workpath)

> - [--noconfirm](https://pyinstaller.org/en/v5.6.1/usage.html#cmdoption-y)

> - [--ascii](https://pyinstaller.org/en/v5.6.1/usage.html#cmdoption-a)

> - [--clean](https://pyinstaller.org/en/v5.6.1/usage.html#cmdoption-clean)

https://pyinstaller.org/en/v5.6.1/spec-files.html#using-spec-files

I am not sure this is correct. For me, `pyinstaller project.spec --log-level=WARN` and `pyinstaller project.spec --log-level=INFO` behave differently.

**Comment by rokm** [comment]
You're right, `--log-level` takes effect regardless of whether building from spec or py file. Care to open a PR that adds the command-line option to the list in https://github.com/pyinstaller/pyinstaller/blob/develop/doc/spec-files.rst?

**Comment by bersbersbers** [comment]
@rokm sure, see https://github.com/pyinstaller/pyinstaller/pull/7196
