### ISSUE TITLE
Makespec option is not valid when a .spec file is given

### ISSUE THREAD

**Issue by andefar6063** [pyinstaller/pyinstaller#7203]
Hi!
Im working on making my program and i have some problems when I try to compile it.
I get this error: 

`option(s) not allowed:
  --onedir/--onefile
  --name
  --add-data
  --add-binary
  --hidden-import/--hiddenimport
  --console/--nowindowed/--windowed/--noconsole
  --icon
makespec options not valid when a .spec file is given`
I have tried on multiple devices, but it keeps coming up.
``
so what should I do?
Here is the .bat file I run:

`@echo off

set "{{=setlocal enableDelayedExpansion&for %%a in (" & set "}}="::end::" ) do if "%%~a" neq "::end::" (set command=!command! %%a) else (call !command! & endlocal)"

%{{%
    C:\Users\antcr\AppData\Local\Programs\Python\Python39\Scripts\pyarmor pack
    -x " --advanced 2 --bootstrap 2 --enable-suffix --exclude helheim"
    -e "
        --add-data 'C:/Users/antcr/AppData/Local/Programs/Python/Python39/Lib/site-packages/helheim^;helheim'
        --add-binary 'C:/Users/antcr/AppData/Local/Programs/Python/Python39/Lib/site-packages/helheim/pytransform_vax_000061.pyd^;helheim'
        --add-data 'C:/Users/antcr/AppData/Local/Programs/Python/Python39/Lib/site-packages/cloudscraper^;cloudscraper'
        -c
        --onefile
        --hidden-import dateutil.parser
        --hidden-import helheim
        --hidden-import cloudscraper
        --hidden-import cryptography
        --hidden-import polling2
        --hidden-import PIL
        --hidden-import PIL.Image
    "
    --name SerpentAIO
    main.py
%}}%

**Comment by rokm** [comment]
Since PyInstaller 5.0, we do not allow using options that have no effect on spec files when building from spec file anymore (see #6660).

In  this case, PyArmor is probably generating the .spec file using the argument you gave it, adds its protection part, and then tries to build from spec, again passing one or more of those original arguments. So they need to update their code to prevent passing  those listed arguments to PyInstaller when building from the spec.

**Comment by andefar6063** [comment]
Rokm is there any way I’m able to use pyinstaller version under 5.0?

**Comment by rokm** [comment]
You can always install a specific version rather than the latest. For example, `pip install pyinstaller==4.10`. Keep in mind that we don't really support old series, though, so if you run into issues, you're on your own. Especially if the problem is a bug that has since been fixed in 5.x.

**Comment by rokm** [comment]
On the other hand, you are probably also using an older version of `pyarmor`. With its latest release (7.7.0), I cannot reproduce the problem with those arguments being passed. But with 6.8.1, I can see that error (and you probably needed to install 6.8.1 to use `-x " --advanced 2 --bootstrap 2 --enable-suffix --exclude helheim"`).

**Comment by andefar6063** [comment]
Downloaded 4.10 and everything works now! There is a huge community that
needs this so you just helped a lot. Thanks your awsome!

lør. 29. okt. 2022 kl. 12.15 skrev Rok Mandeljc ***@***.***>:
