### ISSUE TITLE
Regression in PyInstaller 5.6: Cannot import `ctypes`

### ISSUE THREAD

**Issue by mhils** [pyinstaller/pyinstaller#7208]
Starting with PyInstaller 5.6, binaries that import `ctypes` crash on startup if libffi is missing on the host system. Here is a minimal Dockerfile example:

```dockerfile
FROM python:3.10-bullseye as builder

RUN pip install pyinstaller==5.6  # 5.5 works
RUN echo "import ctypes; print('ok')" > /tmp/foo.py
RUN cd /tmp && pyinstaller --onefile foo.py
RUN ls

FROM ubuntu:22.04

COPY --from=builder /tmp /tmp
CMD ["/tmp/dist/foo"]
```

```
docker build -t repro .; docker run --rm -it repro
```

```
Traceback (most recent call last):
  File "foo.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "ctypes/__init__.py", line 8, in <module>
ImportError: libffi.so.7: cannot open shared object file: No such file or directory
[8] Failed to execute script 'foo' due to unhandled exception!
```

We originally discovered this for mitmproxy at https://github.com/mitmproxy/mitmproxy/issues/5699. I dug a bit deeper there and found that the binary contains `libffi.so.7.1.0` , but not `libffi.so.7`.

Nonetheless, thank you folks for the fantastic work you're doing here! 😃

**Comment by bwoodsend** [comment]
Sounds like #7189 again. I see I'm getting what I deserved for being too lazy to do a patch release after that one's fix went in. Hang on whilst I hit the release button...

**Comment by bwoodsend** [comment]
It's away.

**Comment by bwoodsend** [comment]
Really nice little reproducer by the way. Thanks for making the effort.

**Comment by mhils** [comment]
Awesome, thank you so much for the quick fix! 🍰
