### ISSUE TITLE
Error encountered packaging asyncio lib

### ISSUE THREAD

**Issue by syikmis** [pyinstaller/pyinstaller#7210]
## Description of the issue
Hello the problem I have encountered is when packaging the [asyncio lib](https://docs.python.org/3/library/asyncio.html).
I am getting a `OSError: [WinError 10022] An invalid argument was supplied`. The problem is also described [here](https://stackoverflow.com/questions/74265184/winerror-converting-python-script-to-executable-with-asyncio-lib-and-pyinstaller).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.4.1```
* Version of Python: ```3.10.2```
* Platform: Windows 10 OS, Intel 64bit
* How you installed Python: Workspace software installation routine
* Did you also try this on another platform? Does it work there? No, did not try

### A minimal example program which shows the error

```
import asyncio
import os
import time


def main():
    print("Hello World!")
    time.sleep(4)


if __name__ == '__main__':
    os.system('cls')
    main()

```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "asyncio\__init__.py", line 39, in <module>
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "asyncio\windows_events.py", line 8, in <module>
OSError: [WinError 10022] An invalid argument was supplied
```

**Comment by rokm** [comment]
[Line 8 in `asyncio.windows_events` imports `_overlapped` extension](https://github.com/python/cpython/blob/v3.10.2/Lib/asyncio/windows_events.py#L8); usually extensions failing to load means that there is a DLL dependency issue.

Can you first try with the latest PyInstaller release (5.6.2) instead of 5.4.1 (since that one is affected by #7102)? If that does not work, try building without `--onefile` option to to get onedir build, and tell us the contents of the resulting onedir application directory.

**Comment by syikmis** [comment]
Hello,
I have upgraded to Pyinstaller 5.6.2 - it did not help, same error. 
I have run following command: `python -m PyInstaller main.py --name asyc_test  --clean  -w`

The results of the directory are: 
```
asyc_test.exe
base_library.zip
files.txt
libcrypto-1_1.dll
libffi-7.dll
libssl-1_1.dll
pyexpat.pyd
python310.dll
select.pyd
unicodedata.pyd
VCRUNTIME140.dll
_asyncio.pyd
_bz2.pyd
_ctypes.pyd
_decimal.pyd
_hashlib.pyd
_lzma.pyd
_multiprocessing.pyd
_overlapped.pyd
_queue.pyd
_socket.pyd
_ssl.pyd
```

**Comment by rokm** [comment]
Hmm, in that case, can you archive both the `build` and `dist` directory and upload them somewhere, so I can take a look at them?

**Comment by syikmis** [comment]
Thank you for your help!
I uploaded the directories as .zip into a file sharing service - i hope that works
[Link](https://netfiles.de/aded28f76b39dfcb9e6094088ea717e93650c3effb5a5ffed7a71b798ef40743;faHkepZC)

**Comment by rokm** [comment]
That frozen example starts without an error in my test VM, which complicates debugging...

After searching for `WinError 10022`, I suspect it is coming from the `winsock` library (`_overlapped` imports `_socket` module during its [execution during import](https://github.com/python/cpython/blob/a58ebcc701dd6c43630df941481475ff0f615a81/Modules/overlapped.c#L1935-L1973)).

To pin-point the origin, can you try freezing the following test programs:

```python
# test-overlapped.py
import _overlapped
print(_overlapped)
```

```python
# test-socket.py
import _socket
print(_socket)
```

```python
# test-socket2.py
import socket
print(socket)
```

Do they also raise the same error on your system when frozen? Do they run normally if you run them as unfrozen scripts?

**Comment by rokm** [comment]
Is your Q:\\ drive a network share? Does it help if you move the dist directory to C:\\ drive and run from there?

**Comment by syikmis** [comment]
Hello,

output regarding test-overlapped.py (frozen):
```
Traceback (most recent call last):
  File "main.py", line 2, in <module>
OSError: [WinError 10022] An invalid argument was supplied
```
output regarding test-overlapped.py (unfrozen)
`<module '_overlapped' from 'C:\\Program Files\\Python310\\DLLs\\_overlapped.pyd'>`


output regarding test-socket.py:
`runs without problems frozen and unfrozen`

output regarding test-socket2.py:
`runs without problems frozen and unfrozen`

**Comment by syikmis** [comment]
> Is your Q:\ drive a network share? Does it help if you move the dist directory to C:\ drive and run from there?
Yes it is. I get another error referencing another lib - let my try tackling that.

**Comment by rokm** [comment]
Suppose the problem is that at least under some configurations, `socket` functions cannot be used in executable running on (some types of?) network shares. Perhaps a bug on Microsoft's side, perhaps a security feature. Either way, nothing we can do about it.
