### ISSUE TITLE
documentation multipackage is not at current state of the code

### ISSUE THREAD

**Issue by sehHeiden** [pyinstaller/pyinstaller#7215]
[documentation](https://pyinstaller.org/en/stable/spec-files.html#example-merge-spec-file) is not at the current state.

pyi-build does not exist anymore and the tests , that are referenced are also gone. 

still I tried to build two .py files into one package (one file). The size is not reduced. Instead two exe files are build with the full size each.

**Comment by rokm** [comment]
> still I tried to build two .py files into one package (one file). The size is not reduced. Instead two exe files are build with the full size each.

MERGE does indeed seem to be broken in v5.x series (https://github.com/pyinstaller/pyinstaller/pull/7236#issuecomment-1319919586) in addition to outdated documentation.
