### ISSUE TITLE
Problem with pyproj 3.4.0 , package not found 

### ISSUE THREAD

**Issue by aymondebroglie** [pyinstaller/pyinstaller#7227]
## Description of the issue

I try to run pyinstaller on the following  simple `test.py` file 

```python 
import pyproj

print(pyproj.__version__)
```

With  pyproj : `3.3.1`

`pyinstaller test.py; ./dist/test/test` -> `3.3.1`

With pyproj `3.4.0` I get the following error message 

```Traceback (most recent call last):
  File "test.py", line 1, in <module>
    import pyproj
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "pyproj/__init__.py", line 70, in <module>
  File "importlib/metadata.py", line 569, in version
  File "importlib/metadata.py", line 542, in distribution
  File "importlib/metadata.py", line 196, in from_name
importlib.metadata.PackageNotFoundError: pyproj 
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.6.2```
* Version of Python:  3.9.12
* Platform:  **Linux (Ubuntu)** 
* How you installed Python:  **Through conda** 
* Did you also try this on another platform? Does it work there?  **Did not try** 

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
**same error**
* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```python 
import pyproj

print(pyproj.__version__)
```

### Stacktrace / full error message

Running in debug mode, full logs attached 
[bug-pyproj-log.txt](https://github.com/pyinstaller/pyinstaller/files/9953103/bug-pyproj-log.txt)

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
See pyinstaller/pyinstaller-hooks-contrib#505 - looks like we aren't going to be fixing this, but rather wait for next `pyproj` release.

**Comment by rokm** [comment]
As a work-around, you can add `--copy-metadata pyproj` to your PyInstaller command.

**Comment by aymondebroglie** [comment]
Thanks you for the quick answer , the work around seems to be perfect !

**Comment by rokm** [comment]
This should now also work out-of-the-box with latest release of `pyinstaller-hooks-contrib`.
