### ISSUE TITLE
[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate

### ISSUE THREAD

**Issue by sidekick-eimantas** [pyinstaller/pyinstaller#7229]
## Description of the issue
When trying to post to slack using [python slack sdk](https://github.com/slackapi/python-slack-sdk) through a packaged application, I'm hitting `[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate`.

I found another issue here: https://github.com/pyinstaller/pyinstaller/issues/6667 which describes the same problem.
The suggested solution of setting the `SSL_CERT_FILE` environment variable to point to either `/Users/eimantas/.local/homebrew/etc/openssl@1.1/cert.pem` or `/Users/eimantas/.local/bin/skm-cli/skm/certifi/cacert.pem` works.

My understanding then is that `_ssl.c` of my PyInstaller frozen application is unable to discover the system certificates file. 

I can only reproduce this when packaging in GitHub Actions. When I package my application locally, I am not hitting this problem.

I am packaging my application as follows:
```py
def _prepare_package() -> None:
    shutil.rmtree(path=ROOT / "dist", ignore_errors=True)
    subprocess.run(
        [
            utils.which("pyinstaller"),
            "skm_cli/__main__.py",
            "--name",
            "skm",
            "--onedir",
            "--noconfirm",
            "--additional-hooks-dir",
            "pyinstaller-hooks/",
        ],
        cwd=ROOT,
        check=True,
    )
    (ROOT / "dist" / "skm-cli").mkdir(parents=True, exist_ok=True)
    shutil.move(src=ROOT / "dist" / "skm", dst=ROOT / "dist" / "skm-cli" / "skm")
    shutil.copy(src=ROOT / "README.md", dst=ROOT / "dist" / "skm-cli")
```

I've verified that my system certificates are available, using this command:
```py
import ssl

ctx = ssl.SSLContext()
ctx.load_default_certs()
print(ctx.get_ca_certs())
```

This is how we set up the environment:
```py
#!/usr/bin/env bash

set -euo pipefail

brew install "python@3.10"

if [ ! -d ".venv" ]; then
  python3.10 -m venv --copies --clear --upgrade-deps ".venv"
  source ".venv/bin/activate"
  python -m pip install --upgrade pip setuptools wheel
  python -m pip install --editable .[dev]
fi

source ".venv/bin/activate"
```

Any help or pointers would be highly appreciated.
Thank you.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.6.2```
* Version of Python: 3.10.7 (also occurs on 3.10.8)
* Platform: Linux (GitHub Actions ubuntu-22.04 runner, GitHub Actions macos-12 runner)
* How you installed Python: `brew install python@3.10`
* Did you also try this on another platform? Does it work there?: Bug not present when packaging locally on my MacOS M1 with Rosetta, Python x86 install

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
I will try and produce a minimal example if noone has any obvious solutions

### Stacktrace / full error message

```
eimantas@Eimantass-MacBook-Pro built % skm slack post-alert-failing-regression-tests --project my-project --run-url test 
2022-11-09 19:28:16.213374+00:00 [ERROR	] Failed to send a request to Slack API server: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>  filename=base_client.py function_name=_perform_urllib_http_request line_number=448 module_name=base_client module_path=slack_sdk/web/base_client.py process_id=34339 process_name=MainProcess thread_id=8640448000 thread_name=MainThread
2022-11-09 19:28:17.471230+00:00 [ERROR	] Failed to send a request to Slack API server: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>  filename=base_client.py function_name=_perform_urllib_http_request line_number=448 module_name=base_client module_path=slack_sdk/web/base_client.py process_id=34339 process_name=MainProcess thread_id=8640448000 thread_name=MainThread
Traceback (most recent call last):
  File "urllib/request.py", line 1348, in do_open
  File "http/client.py", line 1282, in request
  File "http/client.py", line 1328, in _send_request
  File "http/client.py", line 1277, in endheaders
  File "http/client.py", line 1037, in _send_output
  File "http/client.py", line 975, in send
  File "http/client.py", line 1454, in connect
  File "ssl.py", line 513, in wrap_socket
  File "ssl.py", line 1071, in _create
  File "ssl.py", line 1342, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "skm_cli/__main__.py", line 13, in <module>
  File "skm_cli/__main__.py", line 9, in main
  File "typer/main.py", line 328, in __call__
  File "typer/main.py", line 311, in __call__
  File "click/core.py", line 1130, in __call__
  File "typer/core.py", line 778, in main
  File "typer/core.py", line 216, in _main
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1657, in invoke
  File "click/core.py", line 1404, in invoke
  File "click/core.py", line 760, in invoke
  File "typer/main.py", line 683, in wrapper
  File "skm_cli/_cli/_slack.py", line 185, in post_alert_failing_regression_tests
  File "slack_sdk/web/client.py", line 2072, in chat_postMessage
  File "slack_sdk/web/base_client.py", line 156, in api_call
  File "slack_sdk/web/base_client.py", line 187, in _sync_send
  File "slack_sdk/web/base_client.py", line 294, in _urllib_api_call
  File "slack_sdk/web/base_client.py", line 473, in _perform_urllib_http_request
  File "slack_sdk/web/base_client.py", line 397, in _perform_urllib_http_request
  File "slack_sdk/web/base_client.py", line 504, in _perform_urllib_http_request_internal
  File "urllib/request.py", line 216, in urlopen
  File "urllib/request.py", line 519, in open
  File "urllib/request.py", line 536, in _open
  File "urllib/request.py", line 496, in _call_chain
  File "urllib/request.py", line 1391, in https_open
  File "urllib/request.py", line 1351, in do_open
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:997)>
[34339] Failed to execute script '__main__' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by sidekick-eimantas** [comment]
Trying to narrow the issue down - replacing `libcrypto.1.1.dylib` in the bad install (packaged in github actions) with `libcrypto.1.1.dylib` from the good install (packaged locally) dissapears the problem

**Comment by rokm** [comment]
The `certifi` CA certs are *not* automatically used with the stdlib's `urllib.request`; you need to explicitly provide (now-deprecated) `cafile`/`capath` arguments or `ssl.Context` via `context` argument to `urllib.request.urlopen()`. Not sure if your slack SDK API provides support for passing those, though.

Or alternatively, set `SSL_CERT_FILE` environment variable at the start of your program to point to the path returned by `certifi.where()` (which should give correct location in frozen application as well). This is what the hook that was removed in pyinstaller/pyinstaller-hooks-contrib#332 was doing; but as argued there, the program should opt-in to use `certifi` itself, it should not be forced upon it. (On the other hand, the 3rd party `requests` library, for example, automatically opts-in to use `certifi` CA bundle - as also mentioned in discussion of pyinstaller/pyinstaller-hooks-contrib#332).

Otherwise, the `ssl` module probably tries to use system CA certs; which may or may not be there, and may or may not be up-to-date.

----

If you tracked down the difference to bundled `libcrypto.1.1.dylib`, perhaps different copies have different default location for CA certs (which would make sense if setting `SSL_CERT_FILE` fixes the problem, regardless of which copy you use).

Do you use homebrew `python@3.10` both in your GitHub Actions workflow and when packaging locally?

Can you check the `build/<name>/Analysis-00.toc` and see where the `libcrypto.1.1.dylib` is collected from in each case?

**Comment by sidekick-eimantas** [comment]
> The `certifi` CA certs are _not_ automatically used with the stdlib's `urllib.request`; you need to explicitly provide (now-deprecated) `cafile`/`capath` arguments or `ssl.Context` via `context` argument to `urllib.request.urlopen()`. Not sure if your slack SDK API provides support for passing those, though.
> 
> Or alternatively, set `SSL_CERT_FILE` environment variable at the start of your program to point to the path returned by `certifi.where()` (which should give correct location in frozen application as well). This is what the hook that was removed in [pyinstaller/pyinstaller-hooks-contrib#332](https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/332) was doing; but as argued there, the program should opt-in to use `certifi` itself, it should not be forced upon it. (On the other hand, the 3rd party `requests` library, for example, automatically opts-in to use `certifi` CA bundle - as also mentioned in discussion of [pyinstaller/pyinstaller-hooks-contrib#332](https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/332)).
> 
> Otherwise, the `ssl` module probably tries to use system CA certs; which may or may not be there, and may or may not be up-to-date.
> 
> If you tracked down the difference to bundled `libcrypto.1.1.dylib`, perhaps different copies have different default location for CA certs (which would make sense if setting `SSL_CERT_FILE` fixes the problem, regardless of which copy you use).
> 
> Do you use homebrew `python@3.10` both in your GitHub Actions workflow and when packaging locally?
> 
> Can you check the `build/<name>/Analysis-00.toc` and see where the `libcrypto.1.1.dylib` is collected from in each case?

Hi rokm, thank you for looking into this

Yes, we use `brew install python@3.10` in both GitHub Actions workflow and when packaging locally

libcrypto.1.1.dylib sourcing locations:
- local macos: /Users/eimantas/.local/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib (we install homebrew to `~/.local/homebrew`)
- github actions macos: /opt/homebrew/opt/openssl@1.1/lib/libcrypto.1.1.dylib
- github actions linux: /home/linuxbrew/.linuxbrew/opt/openssl@1.1/lib/libcrypto.so.1.1

The odd thing is, the application packaged in github actions on ubuntu-22.04, will experience this problem when running on the same github actions ubuntu-22.04 image

**Comment by rokm** [comment]
What you can also do is, add a 
```python
import ssl
print(ssl.get_default_verify_paths())
```
to your program (or just try freezing that snippet).

When ran under python.org python (or frozen using this version), the output is:
```
DefaultVerifyPaths(
cafile='/Library/Frameworks/Python.framework/Versions/3.10/etc/openssl/cert.pem', 
capath=None, 
openssl_cafile_env='SSL_CERT_FILE', 
openssl_cafile='/Library/Frameworks/Python.framework/Versions/3.10/etc/openssl/cert.pem', 
openssl_capath_env='SSL_CERT_DIR', 
openssl_capath='/Library/Frameworks/Python.framework/Versions/3.10/etc/openssl/certs'
)
```

When running under homebrew python (or freezing using this version), the output is:
```
DefaultVerifyPaths(
cafile='/usr/local/etc/openssl@1.1/cert.pem', 
capath='/usr/local/etc/openssl@1.1/certs', 
openssl_cafile_env='SSL_CERT_FILE', 
openssl_cafile='/usr/local/etc/openssl@1.1/cert.pem', 
openssl_capath_env='SSL_CERT_DIR', 
openssl_capath='/usr/local/etc/openssl@1.1/certs'
)
```

And swapping the `libcrypto.1.1.dylib` changes the output accordingly. 

So based the locations you have given, I'd say that your GA copy of OpenSSL uses different prefix for default CA path than your local installation, and therefore cannot find the default CA certs. By switching the `libcrypto.1.1.dylib˙, you have probably effectively changed the default location of the CA file to the one that is correct for your system. But it is probably not portable, so if you try to run the program on a system without brew installed, you'll see the same error.

If you want a portable application, you'll need to use the `certifi` CA bundle (using the `SSL_CERT_FILE`).

**Comment by rokm** [comment]
> The odd thing is, the application packaged in github actions on ubuntu-22.04, will experience this problem when running on the same github actions ubuntu-22.04 image

The same ubuntu-22.04 image without homebrew python and OpenSSL installed?

**Comment by sidekick-eimantas** [comment]
> > The odd thing is, the application packaged in github actions on ubuntu-22.04, will experience this problem when running on the same github actions ubuntu-22.04 image
> 
> The same ubuntu-22.04 image without homebrew python and OpenSSL installed?

You're right, we're not installing python or openssl when consuming the app

**Comment by sidekick-eimantas** [comment]
> So based the locations you have given, I'd say that your GA copy of OpenSSL uses different prefix for default CA path than your local installation, and therefore cannot find the default CA certs. By switching the `libcrypto.1.1.dylib˙, you have probably effectively changed the default location of the CA file to the one that is correct for your system. But it is probably not portable, so if you try to run the program on a system without brew installed, you'll see the same error.

That's exactly it, thank you so much !

When packaging in GA ubuntu, then trying to run the application in a different job without setting up homebrew, the application hits the SSL error because since a few months ago homebrew is no longer in the PATH of GA ubuntu images by default.

When packaging in GA macos, then trying to run the application in GA macos, it works (I had not tried this before this discussion)

When packaging in GA macos, then trying to run the application locally, it does not work, because we install homebrew into a different path on our laptops than GA

It's all adding up now

Thank you very much @rokm

I'll proceed with your suggestion
> If you want a portable application, you'll need to use the certifi CA bundle (using the SSL_CERT_FILE).
