### ISSUE TITLE
How to make pyinstaller exe trusted by Avast?

### ISSUE THREAD

**Issue by blakphonix** [pyinstaller/pyinstaller#7239]
Hello,
I created a python program and converted it to an executable with pyinstaller. The program writes excel files in protected folders by AVAST (like desktop). Avast disallows the program from writing and raises a message asking for user permission.
The question is, how can I make my software trusted by avast to avoid this message? Should I publish it in Microsoft Store? 
Note: my software does not silently write in protected folders, it raises a "save as" window around 1min before document writing, and the program keeps updating the file each couple of minutes.

**Comment by bwoodsend** [comment]
Ask AVAST, not us.
