### ISSUE TITLE
"Suspecious file warning" for all pyinstaller executables

### ISSUE THREAD

**Issue by blakphonix** [pyinstaller/pyinstaller#7240]
Hello,
I would like to report that every exe file I generate with pyinstaller would cause AVAST to raise a warning about a "suspecious file" and scans it. The scan results says the file is safe. But the issue happens with all exe generated by pyinstaller. I wonder if there is solution?
Thanks

**Comment by bwoodsend** [comment]
See https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md
