### ISSUE TITLE
Generated EXE does not use GPU when deploying

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [pyinstaller/pyinstaller#7246]
Hello, when I use pyinstaller on my computer to generate an exe from the GPU program of torch, and I test it on the target machine, it does not use GPU. Is it because there is no cuda and other installation packages on the target machine? Thank you for your answer

**Comment by rokm** [comment]
Probably. I think CUDA DLLs are dynamically loaded by `torch` at runtime, so they are not picked up by PyInstaller's dependency analysis, and are therefore not collected automatically. So you'll probably need to install CUDA runtime on the target machine.

Or, you could try to figure out which CUDA DLLs need to be collected, and collect them into your application - see #7175 for similar discussion for `tensorflow`. But unless you have a good reason not to, I suggest you to go with installing CUDA runtime.
