### ISSUE TITLE
Failed to use mega.py library in app

### ISSUE THREAD

**Issue by VERISBABY** [pyinstaller/pyinstaller#7250]
## Description of the issue
I use mega.py library for my application. And when i executed to .exe file, i opened & i got this error:
`Failed to execute script 'main' due to unhandled exception: HTTPSConnectionPool(host='g.api.mega.co.nz, port-443): Max retries exceeded with url: /cs?id=1485743051 (Caused by NewConnectionError(' <urllib3.connection.HTTPSConnection object at 0x0000028EB6B38F10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed'))`
i tried with -F & --onedir.
### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.6.2
* Version of Python: 3.10.8
* Platform: Windows 10.00
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?
No, i tried python 3.11 too.

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ yes] start with clean installation
  * [ yes] use the latest development version
  * [ yes] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [yes ] Package your program in **--onedir mode**
  * [yes ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
```
from mega import Mega

mega = Mega()
m = mega.login('thenhan20.jandi@gmail.com', 'password')
m.download_url('https://mega.nz/file/xxxxxxxxxxxxxxxxxxxxxx')
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Can we see the whole traceback? I.e., does the error occur during the login or during the download?

FWIW, the following example with anonymous login seems to work just fine for me:
```python
from mega import Mega

mega = Mega()
m = mega.login()
m.download_url('https://mega.nz/file/xxx')
```
