### ISSUE TITLE
This application failed to start because it could not find or load the Qt platform plugin "windows".

### ISSUE THREAD

**Issue by lipei-pp** [pyinstaller/pyinstaller#7252]
Environment: win10 Professional Edition

python version: 3.4.4(conda virtual environment)

Pyinstaller: 3.4

PyQt5:5.4.0

This application failed to start because it could not find or load the Qt platform plugin "windows".

Reinstalling the application may fix this problem.

How can I solve it?

**Comment by lipei-pp** [comment]
Third party library :
pip list
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 4
29).
Package                   Version
------------------------- ---------
altgraph                  0.17
future                    0.18.2
importlib-resources       0.4
macholib                  1.14
netaddr                   0.8.0
pefile                    2019.4.18
pip                       19.1.1
PyInstaller               3.4
pyinstaller-hooks-contrib 2022.0
pyqt5-tools               5.5.1.1.2
pywin32-ctypes            0.2.0
redis                     3.3.11
scapy                     2.4.5
setuptools                27.2.0
typing                    3.10.0.0
wheel                     0.33.6

**Comment by rokm** [comment]
We don't really support PyInstaller 4.x series anymore; so 3.4 that was released over four years ago is definitely out of question.

If you want support, use a recent version of python, PyInstaller, and PyQt5.
