### ISSUE TITLE
Adding support for Windows ARM64 native

### ISSUE THREAD

**Issue by bwoodsend** [pyinstaller/pyinstaller#7257]
### Discussed in https://github.com/orgs/pyinstaller/discussions/7188

<div type='discussions-op-text'>

<sup>Originally posted by **infinitepower18** October 25, 2022</sup>
Python 3.11 is the first version to officially support ARM64 Windows. I have tried to build an exe with a simple test program but it crashes when I try to run it. However it works fine if I use the AMD64 Python. So is ARM64 supported by Pyinstaller currently?</div>

To get PyInstaller to build native arm64 applications we need to first figure out how to compile the bootloaders for arm64, preferably in a way that doesn't deviate too far from our current waf based build system.

Seemingly no developers own a Windows arm machine but Windows arm can be virtualised on macOS M1 using [this guide](https://docs.getutm.app/guides/windows/). (Thanks for pointing that out @infinitepower18.)

--- 

FYI: For people wanting to support Windows on ARM now, 32bit intel applications can be ran under emulation on Windows ARM so building using a 32 bit version of Python on a regular intel machine will produce an application which runs, albeit slower, on Windows ARM.

**Comment by bwoodsend** [comment]
waf doesn't seem to be able to detect MSVC's arm SDK. With [a minimal example waf project](https://github.com/pyinstaller/pyinstaller/discussions/5956#discussioncomment-922571), it goes for the `x64` tool chain by default and finds nothing at all if explicitly told to use `--msvc_targets=arm`. I have managed to get something working by circumventing waf and doing my usual ridiculous oneliner from an ARM MSVC developer prompt:
```
cl -DWIN32 -DHAVE_STRNLEN -Izlib src\main.c src\pyi_apple_events.c src\pyi_archive.c src\pyi_exception_dialog.c src\pyi_global.c src\pyi_launch.c src\pyi_main.c src\pyi_path.c src\pyi_python.c src\pyi_pythonlib.c src\pyi_splash.c src\pyi_splashlib.c    src\pyi_utils.c src\pyi_win32_utils.c zlib\adler32.c zlib\crc32.c zlib\inffast.c zlib\inflate.c zlib\inftrees.c zlib\zutil.c /link /OUT:..\PyInstaller\bootloader\Windows-64bit-arm\run.exe user32.lib advapi32.lib
```

**Comment by rokm** [comment]
> waf doesn't seem to be able to detect MSVC's arm SDK. With [a minimal example waf project](https://github.com/pyinstaller/pyinstaller/discussions/5956#discussioncomment-922571), it goes for the `x64` tool chain by default and finds nothing at all if explicitly told to use `--msvc_targets=arm`.

Shouldn't that be `arm64`?

**Comment by bwoodsend** [comment]
`--msvc_targets=arm64` doesn't work either. `python waf --help` suggests `arm` under the help for `--msvc_targets`.

**Comment by bwoodsend** [comment]
gcc doesn't support ARM but LLVM+clang does. Installing [LLVM-15.0.2-woa64.exe](https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.2/LLVM-15.0.2-woa64.exe) gives me an installation of clang which works. waf is able to detect this and build the hello world project. Our bootloader building waf script falls over but this works well:
```
clang -o ../PyInstaller/bootloader/Windows-64bit-arm/run.exe -Izlib/ -DHAVE_STRNLEN src/*.c zlib/*.c -ladvapi32
```

**Comment by bwoodsend** [comment]
I'll see what I can do to get our waf script to work with Windows+clang.

**Comment by bwoodsend** [comment]
It would appear that I'm being blocked by a `.a` vs `.lib` suffix convention mismatch 🙄:
```bash
brenainn@WINDOWS-KNDK3G4  /c/pyinstaller/bootloader (develop)
$ python waf --clang --static-zlib all -v
[22/22] Linking build\debug\run_d.exe
18:14:49 runner ['C:\\Program Files\\LLVM\\bin\\clang.exe', '-Wl,--enable-auto-import', '-m64', '-municode', 'src\\main.c.3.o', 'src\\pyi_apple_events.c.2.o', 'src\\pyi_archive.c.2.o', 'src\\pyi_exception_dialog.c.2.o', 'src\\pyi_global.c.2.o', 'src\\pyi_launch.c.2.o', 'src\\pyi_main.c.2.o', 'src\\pyi_path.c.2.o', 'src\\pyi_python.c.2.o', 'src\\pyi_pythonlib.c.2.o', 'src\\pyi_splash.c.2.o', 'src\\pyi_splashlib.c.2.o', 'src\\pyi_utils.c.2.o', 'src\\pyi_win32_utils.c.2.o', '-oC:\\pyinstaller\\bootloader\\build\\debug\\run_d.exe', '-Wl,-Bstatic', '-L.', '-lstatic_zlib.lib', '-Wl,-Bdynamic', '-luser32', '-lcomctl32', '-lkernel32', '-ladvapi32', '-lgdi32']
lld-link: warning: ignoring unknown argument '--enable-auto-import'
lld-link: warning: ignoring unknown argument '-Bstatic'
lld-link: warning: ignoring unknown argument '-Bdynamic'
lld-link: error: could not open 'static_zlib.lib': no such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `C:\pyinstaller\bootloader\build\debug'
Build failed
 -> task in 'run_d' failed with exit status 1:
        {task 2078845916720: cprogram main.c.3.o,pyi_apple_events.c.2.o,pyi_archive.c.2.o,pyi_exception_dialog.c.2.o,pyi_global.c.2.o,pyi_launch.c.2.o,pyi_main.c.2.o,pyi_path.c.2.o,pyi_python.c.2.o,pyi_pythonlib.c.2.o,pyi_splash.c.2.o,pyi_splashlib.c.2.o,pyi_utils.c.2.o,pyi_win32_utils.c.2.o -> run_d.exe}
['C:\\Program Files\\LLVM\\bin\\clang.exe', '-Wl,--enable-auto-import', '-m64', '-municode', 'src\\main.c.3.o', 'src\\pyi_apple_events.c.2.o', 'src\\pyi_archive.c.2.o', 'src\\pyi_exception_dialog.c.2.o', 'src\\pyi_global.c.2.o', 'src\\pyi_launch.c.2.o', 'src\\pyi_main.c.2.o', 'src\\pyi_path.c.2.o', 'src\\pyi_python.c.2.o', 'src\\pyi_pythonlib.c.2.o', 'src\\pyi_splash.c.2.o', 'src\\pyi_splashlib.c.2.o', 'src\\pyi_utils.c.2.o', 'src\\pyi_win32_utils.c.2.o', '-oC:\\pyinstaller\\bootloader\\build\\debug\\run_d.exe', '-Wl,-Bstatic', '-L.', '-lstatic_zlib.lib', '-Wl,-Bdynamic', '-luser32', '-lcomctl32', '-lkernel32', '-ladvapi32', '-lgdi32']

brenainn@WINDOWS-KNDK3G4  /c/pyinstaller/bootloader (develop)
$ /bin/find | grep static_zlib
./build/debug/libstatic_zlib.lib
```

**Comment by bwoodsend** [comment]
That one was solvable quite easily by telling waf not to build a library archive for zlib - rather just use the object files directly during linking. The next pain in the backside is that there is no arm equivalent to the `-m64`/`-m32` arch flag.

**Comment by bwoodsend** [comment]
This would be so much simpler if that waf script wasn't littered with cross compilation.

**Comment by bwoodsend** [comment]
Turns out that it'll happily swallow the `-m64` flag. I had expected there to be a `-marm64` option which is what I had in my head as gcc and clang having on Linux but I'm not sure where I got that idea because a quick check shows that they don't.

**Comment by bwoodsend** [comment]
Got something working now. Test suite is about 3rd of the way through and looking encouraging.
