### ISSUE TITLE
Fixes for use of pyinstaller with Django 4.x and custom management commands.

### ISSUE THREAD

**Issue by Rumbelows** [pyinstaller/pyinstaller#7258]
PROBLEM:
This feature aims to solve the problem of the custom app level management commands being missed out from hidden imports alongside issues with imports of apps listed within INSTALLED_APPS failing due to erroneous execution of 'eval_script' function. Specifically when the hidden imports of the INSTALLED_APPS are evaluated the logging outputs generated by 'collect_submodules' when called in django_import_finder.py are captured in the STDOUT regardless of the --log-level. Also any additional management commands provided by one of the INSTALLED_APPS are ignored as the 'get_commands' function has a hardcoded referenced to Django 1.8 command set. Django's currently implementation of command collection will not complain of missing commands at runtime thereby rendering the patch of this function that is currently implemented irrelevant.

SOLUTION:
The solution to this issue is to remove several redundant parts of the code alongside adding additional overrides for decluttering STDOUT. 

The following is a list of measures taken to resolve the problem
-  remove the monkey patching of Django's 'get_commands' method in pyi_rth_django.py
- modify the collect static code to have a boolean input parameter 'log' which when the relevant calls to logging within this function are wrapped in a conditional will serve to prevent logs being inappropriately raised.

**Comment by bwoodsend** [comment]
Neither of us have any experience with django, nor do we feel that PyInstaller+django is a particularly wise combination. If you want this to happen, you'll have to do it yourself.
