### ISSUE TITLE
pkg_resources.DistributionNotFound:The 'magic_filter'

### ISSUE THREAD

**Issue by Quv1Li** [pyinstaller/pyinstaller#7261]
I am trying to make an .exe out of my script.When I execute pyinstaller -F main.py it runs fine. But when I try to execute the .exe in a terminal it shows me the error message below.Can someone help me how to fix this

- Output of pyinstaller --version: 5.6.2
- Version of Python: 3.10.0
- Platform: Windows 10 

full error message
![изображение_2022-11-20_170735294](https://user-images.githubusercontent.com/118672242/202906712-ca249b48-0260-4e8a-aaef-a27ec6ed72fa.png)

**Comment by rokm** [comment]
Try adding `--copy-metadata magic_filter` to your PyInstaller command.
