### ISSUE TITLE
TypeError: expected str, bytes or os.PathLike object, not NoneType

### ISSUE THREAD

**Issue by TaeDDin** [pyinstaller/pyinstaller#7282]

**Comment by rokm** [comment]
What paths is your code trying to join in line 46 of `dql.py`?

**Comment by TaeDDin** [comment]
> 의 46번째 줄에서 코드가 어떤 경로를 조인하려고 `dql.py`합니까?

Gets the python path from the window environment variable, site.USER_SITE 
ex) "C:\Users\TaeDin\AppData\Local\Programs\Python\Python310\Lib\site-packages" 
and join it with "streamlink\_version.py"

Because I am not good at English, I can use a translator to speak strange words.

**Comment by bwoodsend** [comment]
`site.USER_SITE` will be None under PyInstaller since 7bc99716a6b8db9c31b3a8e84fe708d29db53444. It'll also be None when ran in normal Python with either `-s` or `-S` set. Whatever you are trying to do is non-portable and a bad idea.

**Comment by TaeDDin** [comment]
> `site.USER_SITE` will be None under PyInstaller since [7bc9971](https://github.com/pyinstaller/pyinstaller/commit/7bc99716a6b8db9c31b3a8e84fe708d29db53444). It'll also be None when ran in normal Python with either `-s` or `-S` set. Whatever you are trying to do is non-portable and a bad idea.

Even so, it would have gotten the python address from the windows environment variable.

And since 7bc9971, I wonder why "site.USER_SITE" outputs none, and if I don't want to go back like before, I wonder if there is a way to get the Python path other than other Windows environment variables.
