### ISSUE TITLE
PyInstaller compile python script and crash without specific error message

### ISSUE THREAD

**Issue by Datajacker** [pyinstaller/pyinstaller#7289]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.6.2```
* Version of Python: `3.9.13 `
* Platform: Windows 10
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Nope

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### Description of error

** The python runs directly without any error in the command line. However, it reports the following errors when compiled into exe file**

### Stacktrace / full error message

```
[7844] Failed to execute script 'generate_report_with_ui' due to unhandled exception!
[7844] LOADER: OK.
[7844] LOADER: Manually flushing stdout and stderr
[7844] LOADER: Cleaning up Python interpreter.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> `[7844] Failed to execute script 'generate_report_with_ui' due to unhandled exception!`

Any messages before this one? Can we see the whole message log?

**Comment by Datajacker** [comment]
Yeah. I can share the full log in the attached file. I use the print statement in the middle to see where the error occurs. I can see that it crushes at some points that user-defined modules can't be accessed. The print output has been removed.
[error_log.txt](https://github.com/pyinstaller/pyinstaller/files/10114461/error_log.txt)

**Comment by rokm** [comment]
What is the output of the program if you build *without* `--debug` option? If you get only `Failed to execute script 'generate_report_with_ui' due to unhandled exception` without any traceback, can you try catching the exception in your python code and print its traceback using the `traceback` module?

**Comment by Datajacker** [comment]
I will try without the `--debug` option. When I directly run the python script, there is no error. I get proper results. I wonder how I can catch the exception with `traceback` if there is no error.

**Comment by rokm** [comment]
If you see `Failed to execute script 'generate_report_with_ui' due to unhandled exception` in your output, this means that this `PyEval_EvalCode` call in bootloader,
https://github.com/pyinstaller/pyinstaller/blob/9b6aeae47184a0d76fa1639bab2435c99f9ee180/bootloader/src/pyi_launch.c#L513-L519
returned NULL, which *usually* means there was an error. I.e., it is not a crash in the sense of segmentation fault where the program would terminate immediately.  I say usually because usually this would also print exception traceback, which seems is not the case here...

Is this a public code you can share, so we can take a look at it and try to figure out what's going on? Otherwise, can you provide a stand-alone example that triggers this problem?

**Comment by Datajacker** [comment]
https://github.com/pyinstaller/pyinstaller/issues/7289#issuecomment-1330857218
I have run this without debug mode. It crushes in the same way.

> What is the output of the program if you build _without_ `--debug` option? If you get only `Failed to execute script 'generate_report_with_ui' due to unhandled exception` without any traceback, can you try catching the exception in your python code and print its traceback using the `traceback` module?

**Comment by rokm** [comment]
If there's no traceback, we cannot really do anything without an example code. If you found out which place it crashes on, perhaps you can turn that into a stand-alone example that triggers the same problem?

**Comment by Datajacker** [comment]
I can't share the details about the user-defined modules. However, I can share the code structure where I think it causes the error. 
```
  ├── ignite                   # the user-defined module
  │   ├── operators         # the user-defined sub-module
  │   │           ├── __init__.py
  │   │           ├── operator.py
  │   │           └── operator_and.py
  │   └── match.py 
```
I can source that the error happens within the operators sub-module. It is a module which conducts string parse with NLP method and user-defined operators. I wonder if it is because the pyinstaller application has isolated the exe file from the sub-module or if it transforms the string into a different format.

**Comment by rokm** [comment]
If those modules are imported using standard "import ..." statements, then PyInstaller should detect them and collect them. If not, you would probably see a `ModuleNotFound` error at runtime, unless you have some special error handling in there. You can always check what modules are collected by opening `build/<name>/Analysis-00.toc` and search for module names in there.

In your earlier log, I remember seeing `transformers`; it could be that some part of that package (metadata, for example) or one of its dependencies is not collected and that is causing the problems. But again, that would usually result in a run-time exception with a traceback that would tell us what is going wrong.

In the absence of the traceback, there's not enough information for us to go on. So the best I can do is suggest you to find exactly where your program terminates (for example, by placing `print()` statements around your code), and once you have the exact location, turn that into a stand-alone example that you can share with us.

**Comment by Datajacker** [comment]
Thank you very much for your suggestions!  I have found that there are missing dependencies which are not compiled by pyinstaller or reported as error messages. After manually adding dependencies into the spec file, it works. 
```
block_cipher = None
add_files = [ ]
a = Analysis(['minimal.py'],
         pathex=['/Developer/PItests/minimal'],
         binaries=None,
         datas=add_files,
         hiddenimports=[],
         hookspath=None,
         runtime_hooks=None,
         excludes=None,
         cipher=block_cipher)
pyz = PYZ(a.pure, a.zipped_data,
         cipher=block_cipher)
exe = EXE(pyz,... )
coll = COLLECT(...)
```
