### ISSUE TITLE
pass manifest to require admin permission not work on windows 7

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#729]
**Original date**: 2013/06/17
**Original reporter**: *markma*

I want to let user run the program as administrator, then I passed a manifest file to pyinstaller with --manifest option.

```
python pyinstaller.py command_proxy.py -w --manifest command_proxy.manifest
```

After generating is done, I logged in as a standard user and open this generated exe file, then I found that it doesn't ask me for admin privilege

**Comment by htgoebel** [comment]
Solved by #149.
