### ISSUE TITLE
Hanging at Extra DLL search directories (PATH)

### ISSUE THREAD

**Issue by LogicEnthusiast** [pyinstaller/pyinstaller#7290]
## Description of the issue

Hanging on `INFO: Extra DLL search directories (PATH)`

Line of code which is hanging: https://github.com/pyinstaller/pyinstaller/blob/develop/PyInstaller/isolated/_parent.py#L233

possible solution

```python
        try:
            self._child.wait(timeout=5)
        except subprocess.TimeoutExpired:
            self._child.kill()
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.6.2```
* Version of Python: 3.10.8
* Platform: Windows 10
* How you installed Python: python.org/downloads
* Did you also try this on another platform? No

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

don't have it yet

### Stacktrace / full error message

No error message generated, hanging at

```
2082 INFO: Extra DLL search directories (PATH):
```

**Comment by rokm** [comment]
Can you consistently reproduce this hang-up? I.e., does it occur every time you try to build your program, or just sometimes? If it is consistent, could you provide a minimal reproducer - I imagine a script that just imports all 3rd party packages that your real program uses should suffice?

**Comment by bwoodsend** [comment]
Duplicate of #7269. But you've managed to pinpoint exactly where in the isolation process it's getting stuck so this one big step further than we ever got on #7269. Even though a brute force `self._child.kill()` would harmless in this case, I'd still like at least try to find out why it's getting stuck before injecting timeouts and kills. If you add `print(function, args, kwargs)` [here](https://github.com/pyinstaller/pyinstaller/blob/40f7eff90af08ef2b0ebb9cdbc69e005114c533b/PyInstaller/isolated/_parent.py#L249), does that give you a reproducer which you can then get to hang jus by running `from PyInstaller import isolated; isolated.call(function, *args, **kwargs)` from a terminal?

**Comment by LogicEnthusiast** [comment]
Issue is consistent.  However it's very hard to find the minimal program as
my program has many modules(100s).  Will take a lot of time to narrow it
down.

Replacing(patching) child.wait() call in _parent.Python class fixes the
issue.  And the resulting binary file works fine.

Subprocess docs have something about .wait() call deadlocks when using
pipes. Probably related to that.

**Comment by rokm** [comment]
> Issue is consistent. However it's very hard to find the minimal program as my program has many modules(100s). Will take a lot of time to narrow it down.

Do you have a `requirements.txt` file for your program, then? Or perhaps you can share you `build/<name>/Analysis-00.toc` file and we can figure out the main imports/packages from that...

> Replacing(patching) child.wait() call in _parent.Python class fixes the issue.  And the resulting binary file works fine.

Yeah, but we'd like to know why the issue occurs in the first place and fix the underlying cause, if possible.

**Comment by LogicEnthusiast** [comment]
Please find attached `requirements.txt` and `Analysis-00.toc` (updated to mask private info).

[files.zip](https://github.com/pyinstaller/pyinstaller/files/10115627/files.zip)

Please note that `Analysis-00.toc` is from the last successful run (patched `Python` class)

One more thing I noticed during testing.

`self._write_handle.write(b"\n")` succeeds sending the new line to the `_child.py`. And `_child.py` actually exits (the code under `if __name__ == '__main__':` finishes its execution - confirmed with bunch of print statements.

So the only possible explanation is some kind of race condition with `child.wait()`

Documentation talks about something related to deadlock:

![image](https://user-images.githubusercontent.com/5157167/204602610-9b4abc56-831f-4332-9507-ac858742f036.png)

Seems like it might be related to the **amount** of data being sent to/from the child process.

**Comment by rokm** [comment]
Thanks for the files! I'll see if I can reproduce this and see what's going on (although the main question, whether the child receives the EOF line and supposedly exists, has already been answered by your analysis).

> Documentation talks about something related to deadlock:

We are not using `stdout=PIPE` nor `stderr=PIPE`, though. Nor should at this point any more data be transferred through *any* of the pipes, really.

**Comment by rokm** [comment]
Hmm, so even if with all packages imported in the test script, I cannot reproduce this...

@qalexma While you're able to consistently reproduce the problem, can you please check two more things?

1) You say that the code in `_child.py` reaches the end - do you also see the actual process exit, for example in Task Manager? (If you instrument `_parent.py` to print the child's Process ID, do you still see that process in Task Manager when the hang-up occurs?)

2) If you add the timeout to `self._child.wait()` as you suggested, but then instead of trying to kill the process, you do a `self._child.poll()` to check its state, does this report that the process is still running (i.e., returns `None`) or does it report to be finished?

**Comment by qalexma** [comment]
Added the following to `_parent.py`

```python
    def __exit__(self, exc_type, exc_val, exc_tb):
        # Send the signal (a blank line) to the child to tell it that it's time to stop.
        print('process exit pid = ' + str(self._child.pid))
        self._write_handle.write(b"\n")
        self._write_handle.flush()
        print('polling the proc = ' + str(self._child.poll()))
        print('waiting for child exit')
        self._child.wait()
```

here is the log:

```
2681 INFO: Extra DLL search directories (PATH): [ ... ]
process exit pid = 32228
polling the proc = None
waiting for child exit
```

On that last line it hangs.

And yes looks like this process pid is still in memory at this point

![image](https://user-images.githubusercontent.com/5157167/204717322-028c719d-1075-4eb8-b6c0-fc883c45556d.png)

**Comment by qalexma** [comment]
so here is couple of interesting facts:

1. Added polling twice with 1 second delay between them. Every other call to `isolate.call` shows the pattern `polling the proc = None` and then `polling the proc = 0`. Meaning the process doesn't exit immediately, but after 1 second it exits.

Once it reaches the `Extra DLL search directories` part, the process shows `polling the proc = None` in both cases - before and after 1 sec wait. Even though the print statements in the child process itself point to the fact that it actually finishes after receiving the new line char (it executes all the way to the last statement in the script, which is my print)

2. The call to `isolated.call`  which is actually hanging is this one

![image](https://user-images.githubusercontent.com/5157167/204722405-80ace1f7-3da7-4d74-b991-49862c033c30.png)


So I put print statements in front of it to see all the arguments passed to it. And then recreated minimal program to make this call in isolation 

![image](https://user-images.githubusercontent.com/5157167/204722802-cba92689-3d5f-4915-b3d6-fdb6afcf37ec.png)

And it is successful, process exits properly

```
process created pid = 6560
c:\Users\....\workspace\.....\tests\pyinstaller\main.py:173: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
2272 INFO: Extra DLL search directories (AddDllDirectory): [ ... ]
2273 INFO: Extra DLL search directories (PATH): [ ... ]
process exit pid = 6560
polling the proc = None
polling the proc after 1 sec = 0
waiting for child exit
child exited!
```

**Comment by qalexma** [comment]
gets more interesting

the `_child.py` that is hanging (in this example pid 8616) has another child process, which is also `_child.py` (pid 20612). Only the pid 20612 started with system-wide python (it is bypassing the venv somehow). The first `_child.py` started with python.exe from venv

![image](https://user-images.githubusercontent.com/5157167/204728322-f3dacc0d-11a5-44fc-9045-aa886080689c.png)

**Comment by qalexma** [comment]
And some more info

**Good scenario**

```
process created pid = 19124
Hello! I'm _child.py.__main__, my os.getpid() = 23332
This is __exit__ method of Python class, self._child.pid = 19124
polling self._child.poll() => None
time to end this child process
waiting 3 sec
this is the last statement executed in _child.py process, os.getpid() = 23332
polling again self._child.poll() => 0
waiting for child exit pid = 19124
child exited!
```

**Bad scenario**

```
process created pid = 4464
Hello! I'm _child.py.__main__, my os.getpid() = 11412
C:\Users\...\workspace\...\venv\lib\site-packages\PyInstaller\building\build_main.py:173: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
1435 INFO: config validation ok = False
2353 INFO: Extra DLL search directories (AddDllDirectory): [ ... ]
2353 INFO: Extra DLL search directories (PATH): [ ... ]
This is __exit__ method of Python class, self._child.pid = 4464
polling self._child.poll() => None
time to end this child process
waiting 3 sec
this is the last statement executed in _child.py process, os.getpid() = 11412
polling again self._child.poll() => None
waiting for child exit pid = 4464
```

So seems like it is always creating 2 pids: 
1. as visible from subprocess creation (4464), 
2. pid 11412 as visible from the `_child.py` itself.

Those are both python processes running `_child.py` (only 11412 is running from under system-wide python.exe)

![image](https://user-images.githubusercontent.com/5157167/204732743-93e2eeff-1898-43e0-801d-e65a117af225.png)

**Comment by qalexma** [comment]
List of files opened by both of those (pid 4464 and pid 11412). Seems like pid 11412 still has a lot of files opened at the time of the hanging

![image](https://user-images.githubusercontent.com/5157167/204734109-0f7abc50-82b0-47f3-9f65-a6f6ebe6da0d.png)

**Comment by LogicEnthusiast** [comment]
So turns out here is what's happening. `isolated.call()` is creating a `_child.py` and passing a function to it. Seems like this function sometimes can be the whole program under analysis. In my case that program was creating threads, and one of them was `daemon = False` which means closing the main program will not stop the thread. So that is what was blocking `_child.py` from exiting. Figured this out by adding 

```python
import threading
for thread in threading.enumerate(): 
    print(thread.name)
```

at the end of the `_child.py`. It became apparent that 2 threads were still running when `_child.py` was supposed to close.

adding `daemon = True` to the thread instantiation (in the program which is being parsed by pyinstaller) fixes the issue. However that's not necessarily what is always the desired option.

I guess the question is how to make `_child.py` more robust for such source code patterns (where threads are created without daemon=True)

**Comment by rokm** [comment]
Nice detective work there!

The child sub-process in question,

https://github.com/pyinstaller/pyinstaller/blob/d46744f487035aee97f27966847f9a88f209b840/PyInstaller/building/build_main.py#L690

runs this `find_binary_dependencies` function:

https://github.com/pyinstaller/pyinstaller/blob/d46744f487035aee97f27966847f9a88f209b840/PyInstaller/building/build_main.py#L127-L192

This function first attempts to import all top-level modules and packages used by your program (in case their initialization adjusts `PATH` or adds extra DLL search directories via `os.add_dll_directory`), and then runs the binary dependency analysis on the collected binaries (i.e., tries to resolve the DLLs that they are linked against).

So to clarify the situation, does some top-level package or module that is part of your program perform automatic thread instantiation during its import phase, as opposed to "on-demand" by explicitly calling a function from your program? That's the only scenario I can imagine where this dependency analysis sub-process will end up running arbitrary user code.

**Comment by LogicEnthusiast** [comment]
Yes exactly this thread instantiation is executed during module imports.
And the way it is instantiated doesn't allow it to stop automatically when
the main program stops (non-daemon thread).

When i adjusted it to be daemon thread (meaning it will be killed when main
program stops), the hanging of the _child.py is not observed.

**Comment by rokm** [comment]
OK, great, this clears up the failure mode and its underlying cause, and also explains why we haven't been able to reproduce the problem on our side.

I'd argue that having modules whose import causes side effects like that is a questionable design choice, and it affects other areas of analysis where module may end up imported (e.g., when analyzing a submodule of a package, importing the package itself is unavoidable). As extreme examples, the module popping up a dialog, or running a system-restart command come to mind...

I can't really think of any sane defense against such arbitrary code execution.

In this particular case, I'm now leaning towards adding the timeout for that final wait in parent, and attempting to kill the subprocess (and then wait again for the sake of formality, possibly with timeout again). As well as displaying a warning (or raising an error if we have strict build mode enabled, to catch potential occurrences of this on our CI).

**Comment by bwoodsend** [comment]
Are we importing the top level script in this analysis? I don't really expect everyone to be disciplined enough to wrap their top level code in `if __name__ == "__main__"` guards.

**Comment by rokm** [comment]
As far as I know, the entry-point script itself is not imported. If it were, UI-based scripts without the `__main__` guard would end up popping their UI during analysis and block it...

**Comment by LogicEnthusiast** [comment]
so what's the next step, do you want me to add the timeout/kill. What is the process exactly

**Comment by bwoodsend** [comment]
I think so. It's not due to some horrible but fixable Windows API/pipe deadlocking like I had previously expected. And it's not going to truncate output and miss data since it's not getting killed until all data is already sent back.

One last option would be to call `os._exit(0)` right at the end of `PyInstaller.isolated._child`. That at least cuts through threads where `sys.exit()` doesn't.

**Comment by rokm** [comment]
Yeah, let's go with timeout + kill, now that we know that we are not trying to mask a pipe deadlock problem. If you feel like putting together a PR, go ahead, otherwise we'll pick this up in the upcoming days.

**Comment by LogicEnthusiast** [comment]
how do I go about creating a PR? Reading the [docs](https://pyinstaller.org/en/stable/development/pull-requests.html) it is saying I will need to create a fork of the whole project first. Is that actually necessary?

Let me know if that doc is the correct one to follow.

**Comment by bwoodsend** [comment]
Yes that's correct. Forking is the easy bit though, just press the Fork button at the top right of https://github.com/pyinstaller/pyinstaller. If you're not familiar with git and GitHub though it's probably easier just to leave it to us.
