### ISSUE TITLE
_decimal.cpython-39-darwin.so is incompatible with target arch x86_64 (has arch: arm64)!

### ISSUE THREAD

**Issue by lewisd1996** [pyinstaller/pyinstaller#7308]
Hi guys, my mac has an M1 chip and when trying to export my python file to an executable file with the target arch of `x86_64`, I get the following error:

```
PyInstaller.utils.osx.IncompatibleBinaryArchError:
/opt/homebrew/Cellar/python@3.9/3.9.14/Frameworks/Python.framework/Versions/3.9/lib/python3.9/lib-dynload/
_decimal.cpython-39-darwin.so is incompatible with target arch x86_64 (has arch: arm64)!
```

I am running the code: 
`pyinstaller --onefile --target-arch x86_64 scraper.py`

Reason for doing this is I have made a small web scraper for someone and their mac is not M1, so they get the following error when trying to open the executable:
`zsh: bad CPU type in executable`

The file itself works fine and omitting the `--target-arch x86_64` works as expected.

**Comment by bwoodsend** [comment]
Homebrew Python is single arch so, since you're running on M1 then you've only got an `arm64` version of Python. To build an x86_64 application you need an x86_64 or universal2 Python environment.
