### ISSUE TITLE
DLL load failed while importing _core, repeated error

### ISSUE THREAD

**Issue by mvolar** [pyinstaller/pyinstaller#7309]
Hello everyone,

similar to closed issue #6229 I try to run pyinstaller on a simple python script using tkVideoPlayer, the script runs excellently when using normal launching command line python launcher, however after using pyinstaller to try and install it produces the error mentioned in the title , as if it failed to find/load the PyAV module  (it finishes the install without throwing any breaking errors, even says success). 

I have checked all of the codecs/.dll extenstion mentioned in #6229 to see if my problem is identical, however all of my codecs get hooked from the main package installation directory `.../site-packages/av.libs` and for the life of me I can't figure out what is the error, or rather why it fails to import the av._core module.

The full output error is:
```
Traceback (most recent call last):
  File "sample_video.py", line 30, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tkVideoPlayer\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "tkVideoPlayer\tkvideoplayer.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "av\__init__.py", line 52, in <module>
ImportError: DLL load failed while importing _core: The specified module could not be found.
```

I have tried:

1. importing av._core from the script
2. pointing pyinstaller with the add-data command to the av.libs package location
3. adding the av folder to the add-data
4. adding entire site packages to the add-data
5. compiling a script which does NOTHING ELSE but importing av and then printing hello world

And all failed giving me the same error code

I have also included the Analysis.toc file below and the entire build directory:

[Analysis-00.txt](https://github.com/pyinstaller/pyinstaller/files/10164379/Analysis-00.txt)
[build.zip](https://github.com/pyinstaller/pyinstaller/files/10164568/build.zip)

Im trying to compile the [sample example](https://github.com/PaulleDemon/tkVideoPlayer/blob/master/examples/sample_player.py) provided in the tkVideoPlayer library. Pyinstaller version is 5.6.2, python version is 3.9.7 and everything is run from the conda prompt (so far I had no issues with compilation of other scripts from the prompt, to programs worked flawlessly).

My full program uses the tkvideoplayer and is a lot more complex,  so I have tried to reduce the problem maximally.

**Comment by rokm** [comment]
Can you also attach the `dist` directory? The result for script that does nothing except imports av and prints hello world should suffice.

**Comment by mvolar** [comment]
Unfortunately the zipped dist directory is over 25mb (just barely over, at 31 mb) so im sending a [mediafire link](https://www.mediafire.com/file/nmmzjmdtzs0jh67/dist.zip/file) with the repository. The example is minimal, just, but still produces the error. In the meantime this has been tested on 2 different PC's from the anaconda prompt, still producing the same error:
```
import av
print("hello world")
```
-------------------------

UPDATE:
Running pyinstaller from system Powershell and a fresh install of python 3.11 (can't find the identical 3.9.7 working distribution since it is in security mode) successfully imports the av library and the tkVideoPlayer, so it seems to be a problem between the anaconda3 and pyinstaller and/or python 3.9 specific it's hard to tell.

**Comment by bwoodsend** [comment]
Anaconda breaks up packages so that the DLLs are stored elsewhere. Reverse engineering this is near impossible so PyInstaller doesn't try to do it generally. The most practical solution is always to just not use PyInstaller with conda.

**Comment by rokm** [comment]
The problem is that anaconda python (versions 3.8 and 3.9) contains a patch that breaks `os.add_dll_directory`, which means that the DLLs in `av.libs` directory cannot be found by the frozen application.

The `av.__init__` therefore contains the following work-around:
```python
# Some Python versions distributed by Conda have a buggy `os.add_dll_directory`
# which prevents binary wheels from finding the FFmpeg DLLs in the `av.libs`
# directory. We work around this by adding `av.libs` to the PATH.
if (
    os.name == "nt"
    and sys.version_info[:2] in ((3, 8), (3, 9))
    and os.path.exists(os.path.join(sys.base_prefix, "conda-meta"))
):
    os.environ["PATH"] = (
        os.path.abspath(os.path.join(os.path.dirname(__file__), os.pardir, "av.libs"))
        + os.pathsep
        + os.environ["PATH"]
    )
```
but this does not kick in in the frozen application, because we do not collect "conda-meta" directory.

Switching to python.org python (or perhaps using Anaconda python 3.10) should therefore fix the problem. 

Adding
```python
import os
import sys
if getattr(sys, 'frozen', False):
    dll_dir = os.path.join(sys._MEIPASS, 'av.libs')
    os.environ['PATH'] = dll_dir + os.pathsep + os.environ['PATH'] 

import av
# ...
``` 
at the top of the script should also work as a work-around.

Now I thin I remember seeing this particular issue before, but cannot find it in our issue tracker...
