### ISSUE TITLE
v5.7.0 -w package flask to run .exe file error

### ISSUE THREAD

**Issue by yangyuexiong** [pyinstaller/pyinstaller#7325]
After upgrading to v5.7.0, -w packaged the flask application, and an error occurred when running .exe. Try to add the following code in the entry file to solve this problem, and it can run successfully. If you don't add this code block, is there any other way to solve it?

<img width="439" alt="image" src="https://user-images.githubusercontent.com/26624465/207484203-52fe6c43-c268-4e78-ad0e-7bf50bbc3014.png">

`
import os
import sys

import PyInstaller

if PyInstaller.__version__ == "5.6.2":
    pass
else:
    sys.stdout = open(os.devnull, "w")
`

**Comment by rokm** [comment]
> If you don't add this code block, is there any other way to solve it?

No. If you use noconsole/windowed mode, you now need to set a fake `sys.stdout` yourself. Same as if you ran your python code in noconsole `pythonw.exe` interpreter. 

If you want this to work without setting fake `sys.stdout` yourself, you should ask either `flask` maintainers to not call `show_server_banner` when `sys.stdout` is unavailable, or ask `click` maintainers to gracefully handle cases when `click.utils.echo` is called with unavailable file handle.

**Comment by rokm** [comment]
Also, you should not be importing `PyInstaller` in your application. You can safely override `sys.stdout` even when using PyInstaller < 5.7.

**Comment by rokm** [comment]
I've opened issue with `click` (https://github.com/pallets/click/issues/2415) - as they are advertising `click.utils.echo` as replacement for `print`, they should be properly handling the case when console is unavailable.
