### ISSUE TITLE
'Gdown' library error when running .exe

### ISSUE THREAD

**Issue by VERISBABY** [pyinstaller/pyinstaller#7334]
## Description of the issue
'Gdown' library error when running .exe after executed. It runs normal when i test on IDLE. i think it's relate to something on pyinstaller.

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.7.0
* Version of Python: 3.10.9
* Platform: Windows (language settings)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.
**YES IN ALL OPTIONS ABOVE**

### A minimal example program which shows the error

```
url='https....'
# THIS IS LINE 60
gdown.download(url, output, quiet=False)
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "myfile.py", line 60, in <module>
  File "gdown\download.py", line 256, in download
  File "tqdm\std.py", line 1109, in __init__
  File "tqdm\std.py", line 1361, in refresh
  File "tqdm\std.py", line 1509, in display
  File "tqdm\std.py", line 350, in print_status
  File "tqdm\std.py", line 343, in fp_write
  File "tqdm\utils.py", line 89, in __getattr__
AttributeError: 'NoneType' object has no attribute 'write'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Are you building in `noconsole` / `windowed` mode? PyInstaller 5.7 does not provide dummy `sys.stdout` / `sys.stderr` and instead keeps them at `None`, same as you would get in `pythonw.exe`: https://pyinstaller.org/en/v5.7.0/CHANGES.html#incompatible-changes

So if you have code that fails to check whether `sys.stdout` or `sys.stderr` are available before trying to use them (in this case, either `gdown`, or underlying `tqdm`), you need to set them to devnull objects yourself at the start of your program. E.g., 
```python
if sys.stdout is None:
    sys.stdout = open(os.devnull, "w")
if sys.stderr is None:
    sys.stderr = open(os.devnull, "w")
``` 
See #7325, #7310.

And if you build with PyInstaller in noconsole/windowed mode, you should try running your code with `pythonw.exe` interpreter instead of `python.exe` to catch the issues related to lack of console.

**Comment by VERISBABY** [comment]
> Are you building in `noconsole` / `windowed` mode? PyInstaller 5.7 does not provide dummy `sys.stdout` / `sys.stderr` and instead keeps them at `None`, same as you would get in `pythonw.exe`: https://pyinstaller.org/en/v5.7.0/CHANGES.html#incompatible-changes
> 
> So if you have code that fails to check whether `sys.stdout` or `sys.stderr` are available before trying to use them (in this case, either `gdown`, or underlying `tqdm`), you need to set them to devnull objects yourself at the start of your program. E.g.,
> 
> ```python
> if sys.stdout is None:
>     sys.stdout = open(os.devnull, "w")
> if sys.stderr is None:
>     sys.stderr = open(os.devnull, "w")
> ```
> 
> See #7325, #7310.
> 
> And if you build with PyInstaller in noconsole/windowed mode, you should try running your code with `pythonw.exe` interpreter instead of `python.exe` to catch the issues related to lack of console.

_**Thanks, I added the code snippet above at the top of my app file and it fixed the error.**_
