### ISSUE TITLE
pyinstaller & shutil

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#734]
**Original date**: 2013/07/02
**Original reporter**: _anonymousqsdqsdqsd_

Pyinstaller & shutil [function copy] probleme !

hi i'm trying to convert a .py code into .exe , all was fine till i used shutil to copy my file 
actually my code is similar to that : 

dr  = os.environ['WINDIR']
current = os.path.abspath(**file**)
shutil.copy(current, dr)

as we can see the code copy the current fine to windows file (this is just an exemple )  ; the code actually works fine but if we compile it into exe and run it we will see  . 

Traceback (most recent call last):
  File "<string>", line 13, in <module>
  File "C:\Documents and Settings\john\Desktop\pyinstaller\pyinstaller-2.0\test
\build\pyi.win32\test\out00-PYZ.pyz\shutil", line 119, in copy
  File "C:\Documents and Settings\john\Desktop\pyinstaller\pyinstaller-2.0\test
\build\pyi.win32\test\out00-PYZ.pyz\shutil", line 82, in copyfile
IOError: [Errno 2] No such file or directory: 'C:\Documents and Settings\john
\Desktop\pyinstaller\pyinstaller-2.0\test\dist\test.py'

the error is from function copy becouse it doesnt find test.py in \test\dist\test.py  . 

 any solutions ?  

i tryed  : 
dr  = os.environ['WINDIR']
current = os.path.abspath(**file**)
newfile = current.replace('py','exe')
shutil.copy(current, dr)

but it stil say 

IOError: [Errno 2] No such file or directory: 'C:\Documents and Settings\john
\Desktop\exeinstaller\exeinstaller-2.0\test\dist\test.exe'

**Comment by aman17ashray** [comment]
The duplicate mentioned above has been closed. How can one get around this error?

**Comment by bwoodsend** [comment]
They were both closed because they don't make sense. The file pointed to by `__file__` doesn't exist. And you shouldn't be copying or modifying it anyway.
