### ISSUE TITLE
Error detected while installing pyinstaller 5.7.0

### ISSUE THREAD

**Issue by PythonExpert-create** [pyinstaller/pyinstaller#7346]
We are working on a project, where we need to install pyinstaller 5.7.0. But while downloading https://files.pythonhosted.org/packages/a6/fc/029b4c0138abc7941ea757044efd5b739de2ef561a87bad624309dafdd89/pyinstaller-5.7.0-py3-none-win_amd64.whl file, we have encounted virus detected error. Is it the error expected?

![error](https://user-images.githubusercontent.com/121290510/209321515-ceef3706-a7a4-48d4-b6f3-c981eb8cf2d1.PNG)

**Comment by bwoodsend** [comment]
See the [antivirus issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md).
