### ISSUE TITLE
Python 3.11.1 can't install Pyinstaller

### ISSUE THREAD

**Issue by Stuntlover-TM** [pyinstaller/pyinstaller#7356]
I recently upgraded to Python 3.11.1, and of course I need to redownload libraries and such, but when running `pip install pyinstaller` I get an error:
```
C:\Users\Stuntlover>pip install pyinstaller
Collecting pyinstaller
  Using cached pyinstaller-5.7.0-py3-none-win_amd64.whl (1.3 MB)
ERROR: Could not install packages due to an OSError: [Errno 22] Invalid argument: 'C:\\Users\\Stuntlover\\AppData\\Local\\Temp\\pip-unpack-ai2ipi_2\\pyinstaller-5.7.0-py3-none-win_amd64.whl'
```

and after that error gets shown, apparently windows defender flagged something? (this happens every time right after it throws that error, it wasn't just a coincidence)
![image](https://user-images.githubusercontent.com/101748104/209812590-dafff958-071c-41f7-a115-c5bbe130ae13.png)

**Comment by GeckoPie007** [comment]
I have the same issue.

**Comment by bwoodsend** [comment]
This is a bug in your antivirus provider. Report the issue to them - not us. We can't do anything about it.

**Comment by Stuntlover-TM** [comment]
oh, you're right, apparently disabling windows defender fixes it, sorry and thank you (enabling it after its done installing wont cause any issues, fyi)
