### ISSUE TITLE
Building pyInstaller fails with strange clang error under macOS 10.15 and Homebrew

### ISSUE THREAD

**Issue by jmmelko** [pyinstaller/pyinstaller#7381]
Hi,

I am having troubles building pyinstaller from Homebrew, since I updated the formula. Among all my other formulas, this is the only one that refuses to build.

I am writing here because it seems to be a pyInstaller issue, not a Homebrew one, and the log says "Do not report this issue to Homebrew/brew or Homebrew/core!"

I think it has to do with the clang C compiler. Maybe a version issue?

I have found a similar error message in issue #1341 [https://github.com/pyinstaller/pyinstaller/issues/1341](1341), but this may be completely unrelated.

The error I get is:

```
[19/20] Linking build/debug/tests/test_launch
Undefined symbols for architecture x86_64:
  "_checkFile", referenced from:
      _test_checkFile in test_launch.c.2.o
  "_splitName", referenced from:
      _test_splitName in test_launch.c.2.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have checked the following:

- [X] Homebrew does download the 5.7.0 version (see next section below)
- [X] Unzipping the .gzip, I find that the functions are indeed defined in the c script, as follows:
```int checkFile(char *buf, const char *fmt, ...);
static void test_checkFile(void **state) {
    char result[PATH_MAX];
```
- [X] The installation command seems OK: "python3.11 ./waf all --no-universal2 STRIP=/usr/bin/strip"
- [X] The virtual environment in which this command is executed is managed by Homebrew: I assume everything is OK as all my other formulas build
- [X] I assume that the clang that is called is the one provided by Apple, because I don't have any HomeBrew formula called  'clang' or 'llvm'  ; in the macOS Terminal, the command`which clang` answers:
 ```
Apple clang version 12.0.0 (clang-1200.0.32.29)
Target: x86_64-apple-darwin19.6.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

### Downloaded files by HomeBrew

```
==> Fetching pyinstaller
==> Downloading https://files.pythonhosted.org/packages/5a/13/a7cfa43856a7b8e4894848ec8f71cd9e1ac461e51802391a3e2101c60ed6/altgraph-0.17.3
Already downloaded: /Users/lagaffe/Library/Caches/Homebrew/downloads/2b32e84161681feb5911d4b89cbecdad53aa6424f06892bfb5cd301a5222cdc5--altgraph-0.17.3.tar.gz
==> Downloading https://files.pythonhosted.org/packages/46/92/bffe4576b383f20995ffb15edccf1c97d2e39f9a8c72136836407f099277/macholib-1.16.2
Already downloaded: /Users/lagaffe/Library/Caches/Homebrew/downloads/107bc2d2781424698f61c7573aea66a182c55487da19f5044fe639987b413989--macholib-1.16.2.tar.gz
==> Downloading https://files.pythonhosted.org/packages/f4/e1/1b4f8394be02574479167b0f09a9fdb3ca4f184b45bd89d5878e44ba72ed/pyinstaller-hoo
Already downloaded: /Users/lagaffe/Library/Caches/Homebrew/downloads/dee33bb1239429c9213ff114d701dcd45fd7037e15a7d2924747f2b3914cb62f--pyinstaller-hooks-contrib-2022.14.tar.gz
==> Downloading https://files.pythonhosted.org/packages/13/2e/bc4c0026659cea46aca867f4d71e8bab5a6430b4c005c51e174da5e6e4a2/pyinstaller-5.7
Already downloaded: /Users/lagaffe/Library/Caches/Homebrew/downloads/77f59edde69eb5fa1a828902612bf1ac26ac41143931cb0097d1d39196f3f625--pyinstaller-5.7.0.tar.gz
```

### Note on my environment

I have to emphasize that I am running MacOS Catalina 10.15.7, so all my formulas have to be built locally instead of using binaries. I have noticed in the logs that pyinstaller assumes that I am running 10.13, but I have managed to force it to use 10.15 by setting MACOSX_DEPLOYMENT_TARGET="10.15" (by modifying the ruby script of the Homebrew formula), and this changes nothing.

(yes, I know that it is no longer supported by Homebrew. Even thoug, could you please not despise me like the Homebrew developers in their disclaimer statement).

### Other log files

The "config.log" and "01.python3.11" log files are available on request.

The most interesting part is the beginning of "01.python3.11":

```
2023-01-18 05:53:25 +0000

python3.11
./waf
all
--no-universal2
STRIP=/usr/bin/strip

'all' finished successfully (0.001s)
'distclean' finished successfully (0.000s)
Setting top to                           : /private/tmp/pyinstaller-20230118-94300-15loc3/pyinstaller-5.7.0/bootloader 
Setting out to                           : /private/tmp/pyinstaller-20230118-94300-15loc3/pyinstaller-5.7.0/bootloader/build 
Python Version                           : 3.11.1 (main, Jan 15 2023, 20:19:46) [Clang 12.0.0 (clang-1200.0.32.29)] 
Checking for 'clang' (C compiler)        : clang 
MacOS deployment target                  : Setting to 10.13 
Checking size of pointer                 : 8 
Platform                                 : Darwin-64bit detected based on compiler 
Checking for library m                   : yes 
Checking for library z                   : yes 
Checking for library cmocka              : yes 
Checking for function unsetenv           : yes 
Checking for function mkdtemp            : no 
Checking for function dirname            : yes 
Checking for function basename           : yes 
Checking for function strndup            : yes 
Checking for function strnlen            : yes 
Checking for program 'strip'             : /usr/bin/strip 
Checking for program 'strip'             : /usr/bin/strip 
'configure' finished successfully (2.357s)
'make_all' finished successfully (0.004s)
Waf: Entering directory `/private/tmp/pyinstaller-20230118-94300-15loc3/pyinstaller-5.7.0/bootloader/build/debug'
[ 1/20] Compiling src/pyi_path.c
[ 2/20] Compiling src/pyi_exception_dialog.c
[ 3/20] Compiling src/pyi_apple_events.c
[ 4/20] Compiling src/pyi_win32_utils.c
[ 5/20] Compiling src/pyi_main.c
[ 6/20] Compiling src/pyi_utils.c
[ 7/20] Compiling src/pyi_launch.c
[ 8/20] Compiling src/pyi_python.c
[ 9/20] Compiling src/pyi_global.c
[10/20] Compiling src/pyi_splashlib.c
[11/20] Compiling src/pyi_archive.c
[12/20] Compiling src/pyi_pythonlib.c
[13/20] Compiling src/pyi_splash.c
[14/20] Compiling src/main.c
[15/20] Compiling tests/test_path.c
[16/20] Compiling tests/test_launch.c
[17/20] Linking build/debug/run_d
[18/20] Linking build/debug/tests/test_path
[19/20] Linking build/debug/tests/test_launch
ld: warning: dylib (/usr/local/lib/libcmocka.dylib) was built for newer macOS version (10.15) than being linked (10.13)

ld: warning: dylib (/usr/local/lib/libcmocka.dylib) was built for newer macOS version (10.15) than being linked (10.13)
Undefined symbols for architecture x86_64:
  "_checkFile", referenced from:
      _test_checkFile in test_launch.c.2.o
  "_splitName", referenced from:
      _test_splitName in test_launch.c.2.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Waf: Leaving directory `/private/tmp/pyinstaller-20230118-94300-15loc3/pyinstaller-5.7.0/bootloader/build/debug'
Build failed
 -> task in 'test_launch' failed with exit status 1 (run with -v to display more information)
```

Thank you

**Comment by rokm** [comment]
Ah yes, someone renamed those functions and forgot to adjust the code in tests, which are not compiled on the CI, so the issue went unnoticed...

**Comment by bwoodsend** [comment]
Do we use those tests at all? I hadn't noticed that they existed until now.

**Comment by rokm** [comment]
We don't have `cmocka` installed on the CI, so we don't use them. And we only notice that they exist (and are broken) when someone is unfortunate enough to try to build bootloader on a system that has `cmocka` available.

I have a branch that fixes the tests on all three main OSes (https://github.com/rokm/pyinstaller/tree/fix-bootloader-tests) and adds a `--no-tests` option to bootloader's waf script. The idea was also to install `libcmocka-dev` on ubuntu runner to have at least one pipeline try to build the tests.

But for what is worth, we can probably just remove them and save ourselves some future trouble. (For example, building the tests precludes building of universal2 bootloader on macOS, because brew-installed cmocka library is single-arch...)

**Comment by bwoodsend** [comment]
Maybe make the tests opt in rather than opt out then? And install `libcmocka-dev` on CI like you say so that the tests aren't just left to rot.

**Comment by jmmelko** [comment]
As a quick and dirty fix, renaming the libcmocka libraries to prevent the install script from finding them did the trick. So thank you for reading me.

FYI, cmocka is used by ffmpeg, and since ffmpeg is a very popular program, maybe it's worth correcting this bug!

(Other Homebrew formulas using cmocka are: ffmpeg                    librist                   ocrmypdf                  unpaper)
