### ISSUE TITLE
gi: run glib-compile-schemas after schema xml files have been copied

### ISSUE THREAD

**Issue by amolenaar** [pyinstaller/pyinstaller#7394]
**Is your feature request related to a problem? Please describe.**

When building a `gi` based projects (everything GTK), GSchema files are copied to `share/glib-2.0/schemas`. Schema files can be copied from different locations. e.g. `/usr/`, and `/usr/local`.

Each schema directory contains a file `gschemas.compiled`. This is the file that is actually used to read schemas in your application.

By just copying the files, the `gschemas.compiled` file of the last directory that has been copied will be the actual schema used.

This means that your application can error on missing schemas, although the xml files are present in the schema directory.
This is a tricky issue, since you expect the schema files to be found and the `gschemas.compiled` file can easily be overlooked.

**Describe the solution you'd like**

PyInstaller should run `glib-compile-schemas` after all schema files have been copied to `share/glib-2.0/schemas`.

**Describe alternatives you've considered**

`glib-compile-schemas` can be run separately after the  package has been built.

**Additional context**

https://github.com/gaphor/gaphor/issues/2015

**Comment by rokm** [comment]
Hmm, this means that at the end of `Analysis`, we'd need to copy all schemas files (= the .gschema.xml files that are going 
to be collected to `share/glib-2.0/schemas`) to a temporary working directory, run `glib-compile-schemas`, and replace the `gschemas.compiled` in the TOC (which came from one of original schemas directories) with the one from the temporary working directory. (So we don't have to explicitly deal with COLLECT, BUNDLE, and PKG in onefile mode, which probably isn't solvable without temporary directory anyway).

This raises another question, though - after we compile the schemas, do we need to include the source .gschema.xml files, or can we drop them from the TOC and instead collect only the resulting `gschemas.compiled` file?

**Comment by amolenaar** [comment]
> This raises another question, though - after we compile the schemas, do we need to include the source .gschema.xml files, or can we drop them from the TOC and instead collect only the resulting `gschemas.compiled` file?

I did some tests on my side. It works with only `gschemas.compiled`. I also checked with the GTK folks and we can leave out the xml files.

**Comment by rokm** [comment]
> > This raises another question, though - after we compile the schemas, do we need to include the source .gschema.xml files, or can we drop them from the TOC and instead collect only the resulting `gschemas.compiled` file?
> 
> I did some tests on my side. It works with only `gschemas.compiled`. I also checked with the GTK folks and we can leave out the xml files.

Great, thanks for looking into this!
