### ISSUE TITLE
QtDeclarative support for QtQuick

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#740]
**Original date**: 2013/07/22
**Original reporter**: *nicholastanjerome AND gmail DOT  COOM *

Hi,

I wanted to ask here, whether this will be supported or is it already implemented?

http://stackoverflow.com/questions/12516448/pyinstaller-how-to-include-qml-file-for-a-simple-pyside-qml-application

**Comment by htgoebel** [comment]
@cbenhagen I assume this old ticket can be closed due to your work on the Qt hooks?

**Comment by cbenhagen** [comment]
The fixed hooks plus this answer (https://stackoverflow.com/a/19172295/3695912) should be enough to close this ticket yes.
