### ISSUE TITLE
exit without sys is not working.

### ISSUE THREAD

**Issue by alexd555** [pyinstaller/pyinstaller#7403]
Hi,

If I use "exit" function without import sys or from sys import exit then the function is not recognized.

Should it be fixed ?

Thanks,
Alex

**Comment by bwoodsend** [comment]
`exit()` is not part of the Python language. See [this note](https://docs.python.org/3/library/constants.html?highlight=exit#constants-added-by-the-site-module).

>  They are useful for the interactive interpreter shell and should not be used in programs.

**Comment by alexd555** [comment]
Mabye it's not port of Python but it works without import in all OS.
How do you understand that it's not part of the python ? it's  imported automatically during startup the script.
@bwoodsend

**Comment by rokm** [comment]
>Mabye it's not port of Python but it works without import in all OS.

If you run python with `site` disabled (`python -S`), `exit` is not available, either. 

And PyInstaller-frozen applications also run with `site` disabled.
