### ISSUE TITLE
exe file made python script which should not share with clients

### ISSUE THREAD

**Issue by Pandurangbhor** [pyinstaller/pyinstaller#7426]
There is error, when you use option "--onefile" and made our application in exe.after that we open that exe it will made a copy of our python script in temp folder name like "MEI2525266" .It is dangerous, means we share original python code to client.kindly solve this bug for --one file format.  I hope this issue will solve.

[Kindly go through this ](https://pyinstaller.org/en/stable/advanced-topics.html#the-bootstrap-process-in-detail) 

First process: bootloader starts.

If one-file mode, extract bundled files to temppath/_MEIxxxxxx.

Modify various environment variables:

GNU/Linux: If set, save the original value of LD_LIBRARY_PATH into LD_LIBRARY_PATH_ORIG. Prepend our path to LD_LIBRARY_PATH.

AIX: same thing, but using LIBPATH and LIBPATH_ORIG.

OSX: unset DYLD_LIBRARY_PATH.

Set up to handle signals for both processes.

Run the child process.

Wait for the child process to finish.

If one-file mode, delete temppath/_MEIxxxxxx.

**Comment by bwoodsend** [comment]
No it doesn't. If raw `.py` files are appearing in MEIPASS then you must be doing something silly like `--add-data=your-script.py:.`. PyInstaller bytecompiles Python code then puts then directly into the .exe file.
