### ISSUE TITLE
Failed to execute script 'GUI' due to unhandled exception: couldn't recognize data in image file

### ISSUE THREAD

**Issue by Danny875** [pyinstaller/pyinstaller#7427]
I'm having an error related to some images that are placed in a specific folder, whenever I start the executable GUI application, and I'm thinking that the path to it might not be in the right format accepted by the PyInstaller. 

The errors look like this:

_tkinter.TclError: couldn't recognize data in image file "/Test1/Numpad/number-1.png"
[62807] Failed to execute script 'GUI' due to unhandled exception: couldn't recognize data in image file "/Users/danydragoi/Test1/Numpad/number-1.png"
[62807] Traceback:
Traceback (most recent call last):
  File "GUI.py", line 94, in <module>
  File "tkinter/__init__.py", line 4064, in __init__
  File "tkinter/__init__.py", line 4009, in __init__
_tkinter.TclError: couldn't recognize data in image file "/Test1/Numpad/number-1.png"

Thank you in advance!

I am looking forward to hearing from you!

**Comment by bwoodsend** [comment]
>  _tkinter.TclError: couldn't recognize data in image file "/Test1/Numpad/number-1.png"

I seriously doubt you have a directory called `Test1` at the root of your filesystem. [Read the docs](https://pyinstaller.org/en/stable/runtime-information.html#using-file) for how to properly locate application resources.
