### ISSUE TITLE
No module named 'gssapi.raw.cython_converters'

### ISSUE THREAD

**Issue by muebel** [pyinstaller/pyinstaller#7428]
Hi
I would like to report the following issue.
When I execute an app bundled with pyinstaller, I get the error

ModuleNotFoundError: No module named 'gssapi.raw.cython_converters'

The module cython_converters.cpython-37m-x86_64-linux-gnu.so exists (it was installed by pip):
~/Envs$ ls krb5_client/lib/python3.7/site-packages/gssapi/raw/
chan_bindings.cpython-37m-x86_64-linux-gnu.so      ext_rfc5588.cpython-37m-x86_64-linux-gnu.so
chan_bindings.pyi                                  ext_rfc5588.pyi
creds.cpython-37m-x86_64-linux-gnu.so              ext_rfc5801.cpython-37m-x86_64-linux-gnu.so
creds.pyi                                          ext_rfc5801.pyi
cython_converters.cpython-37m-x86_64-linux-gnu.so  ext_rfc6680_comp_oid.cpython-37m-x86_64-linux-gnu.so
_enum_extensions                                   ext_rfc6680_comp_oid.pyi
exceptions.cpython-37m-x86_64-linux-gnu.so         ext_rfc6680.cpython-37m-x86_64-linux-gnu.so
exceptions.pyi                                     ext_rfc6680.pyi
...

Running Pyinstaller it copies all modules except cython_converters.cpython-37m-x86_64-linux-gnu.so from
~/Envs/krb5_client/lib/python3.7/site-packages/gssapi/raw/
to
~/Envs/dist/krb5_client/gssapi/raw/

~/Envs$ ls dist/krb5_client/gssapi/raw/
chan_bindings.cpython-37m-x86_64-linux-gnu.so     ext_rfc5588.cpython-37m-x86_64-linux-gnu.so
creds.cpython-37m-x86_64-linux-gnu.so             ext_rfc5801.cpython-37m-x86_64-linux-gnu.so
exceptions.cpython-37m-x86_64-linux-gnu.so        ext_rfc6680_comp_oid.cpython-37m-x86_64-linux-gnu.so
...

Investigating the issue I found that cython_converters module is the only module under ~/Envs/krb5_client/lib/python3.7/site-packages/gssapi/raw/ which does not have a corresponding .pyi file. This may be related to the issue.

python 3.7.3
virtualenv 20.17.1
gssapi 1.8.2
pyinstaller 5.7.0

I used the following command to bundle the app:
(krb5_client) ~/Envs$ pyinstaller --windowed krb5_client/krb5_client/krb5_client.py

When I execute the app there appears the error:
(krb5_client) ~/Envs$ dist/krb5_client/krb5_client
Traceback (most recent call last):
  File "krb5_client/krb5_client.py", line 12, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "krb5_client/sso_net.py", line 4, in <module>
    import gssapi
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gssapi/__init__.py", line 31, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 499, in exec_module
  File "gssapi/raw/__init__.py", line 50, in <module>
  File "gssapi/raw/creds.pyx", line 1, in init gssapi.raw.creds
  File "gssapi/raw/names.pyx", line 6, in init gssapi.raw.names
  File "gssapi/raw/misc.pyx", line 1, in init gssapi.raw.misc
ModuleNotFoundError: No module named 'gssapi.raw.cython_converters'
[10055] Failed to execute script 'krb5_client' due to unhandled exception!

I already asked this question in pyinstaller@googlegroups.com but this forum seems to me more active.

Thanks a lot

**Comment by bwoodsend** [comment]
`--hiddenimport=gssapi.raw.cython_converters'`

> I already asked this question in [pyinstaller@googlegroups.com](mailto:pyinstaller@googlegroups.com) but this forum seems to me more active.

Except that this is not a forum - it's a bug tracker.

**Comment by muebel** [comment]
OK, but I think this is a bug.
Where can I report it?

**Comment by muebel** [comment]
Thank you very much. That resolves this issue.
