### ISSUE TITLE
_tkinter.TclError: couldn't open "/Users/username/Numpad/number-1.png": no such file or directory (MacOS)

### ISSUE THREAD

**Issue by Danny875** [pyinstaller/pyinstaller#7433]
Hi,

I'm getting the following errors after successfully converting my files to an executable, on MacOS:

Traceback (most recent call last):
  File "GUI.py", line 108, in <module>
  File "tkinter/__init__.py", line 4064, in __init__
  File "tkinter/__init__.py", line 4009, in __init__
_tkinter.TclError: couldn't open "/Users/username/Numpad/number-1.png": no such file or directory
[91624] Failed to execute script 'GUI' due to unhandled exception!
logout

Saving session...
...copying shared history...
...saving history...truncating history files...
...completed.

[Process completed]

What I notice is that the path shown above is not the correct one, even though in the "Spec" file, I have indicated the correct path, as presented below:

a = Analysis(
    ['/Users/username/Test1/GUI.py'],
    pathex=[],
    binaries=[],
    datas=[('/Users/username/Test1/Numpad', 'Numpad'), ('/Users/username/Test1/myfile.txt', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

As it can be seen, there is a folder called "Test1", where all the packages needed are installed, together with all the files needed for this specific application. 

I would definitely appreciate if you could provide me with some advice regarding this issue, which seems to be a bug.

Thank you in advance!

**Comment by rokm** [comment]
The path `/Users/username/Numpad/number-1.png` is coming from your code (line 108 in GUI.py). So it looks like you are not setting it correctly - perhaps you are using relative path, whereas you should be anchoring it to the `__file__`, as described in [the docs](https://pyinstaller.org/en/stable/runtime-information.html#using-file).
