### ISSUE TITLE
when run  pyinstaller -D  -w  *.py， A transformer and diffusion log error occurs when packing the exe， what should  i do 

### ISSUE THREAD

**Issue by zhanghongyong123456** [pyinstaller/pyinstaller#7446]
![image](https://user-images.githubusercontent.com/48466610/219852195-eb77bec3-4c0d-430e-8d61-2c35db14bb80.png)

**Comment by rokm** [comment]
You need to override `sys.stderr` (and `sys.stdout`, just in case) with a dummy handle at the start of your program if you want this to work in `windowed`/`noconsole` mode:

```python
import sys
import os
if sys.stdout is None:
    sys.stdout = open(os.devnull, "w")
if sys.stderr is None:
    sys.stderr = open(os.devnull, "w")

# the rest of your program
# ...
``` 

But you should also open a bug with `diffusers` to fix their broken logging code.
