### ISSUE TITLE
Scipy>=1.9.2 Fails to import e.g. scipy.sparse on Windows

### ISSUE THREAD

**Issue by jdegenstein** [pyinstaller/pyinstaller#7453]
## Description of the issue

I had scipy unpinned in `setup.py` for our project and recently noticed that it was not producing a fully working installation of scipy. This was with  `scipy==1.10.1`. I tried to pin `scipy<=1.9.1` and it fixed the issue. I understand there were some changes to scipy 1.9.2 to change to delvewheel on Windows, and that resulted in some changes to pyinstaller's scipy hooks. I am using the latest version of the hooks (`pyinstaller-hooks-contrib==2023.0`).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```pyinstaller==4.10 and pyinstaller-hooks-contrib==2023.0```
* Version of Python: python=3.9.16
* Platform: Windows
* How you installed Python: Conda (python 3.9.16  h4de0772_0_cpython)
* Did you also try this on another platform? Does it work there? Yes it works on Linux

### Stacktrace / full error message

Our application has an ipython console built-in, and when I run the following in that console (in the scipy==1.10.1 build) I get this error:
```
In [1]: import scipy

In [2]: import scipy.sparse
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Input In [2], in <cell line: 1>()
----> 1 import scipy.sparse
File PyInstaller\loader\pyimod03_importers.py:495, in exec_module(self, module)
File scipy\sparse\__init__.py:283, in <module>
File PyInstaller\loader\pyimod03_importers.py:495, in exec_module(self, module)
File scipy\sparse\csgraph\__init__.py:185, in <module>
File PyInstaller\loader\pyimod03_importers.py:495, in exec_module(self, module)
File scipy\sparse\csgraph\_laplacian.py:7, in <module>
File PyInstaller\loader\pyimod03_importers.py:495, in exec_module(self, module)
File scipy\sparse\linalg\__init__.py:120, in <module>
File PyInstaller\loader\pyimod03_importers.py:495, in exec_module(self, module)
File scipy\sparse\linalg\_isolve\__init__.py:4, in <module>
File PyInstaller\loader\pyimod03_importers.py:495, in exec_module(self, module)
File scipy\sparse\linalg\_isolve\iterative.py:9, in <module>
ImportError: DLL load failed while importing _iterative: The specified module could not be found.
```
In the logs of this same scipy==1.10.1 build I am getting several error messages like this:
```
2023-02-20T15:32:11.4874062Z 123221 WARNING: lib not found: libopenblas-802f9ed1179cb9c9b03d67ff79f48187.dll dependency of C:\Users\runneradmin\micromamba-root\envs\test\lib\site-packages\scipy\linalg\_fblas.cp39-win_amd64.pyd
```
The scipy==1.9.1 build includes an additional libopenblas DLL (not present in scipy==1.10.1 build):
```
2023-02-21T03:41:32.7592786Z dist/CQ-editor/libopenblas.PZA5WNOTOH6FZLB2KBVKAURAKVTFSNNU.gfortran-win_amd64.dll
2023-02-21T03:41:32.8082033Z dist/CQ-editor/libopenblas64__v0.3.21-gcc_10_3_0.dll
```
I can supply the full logs, but they are quite lengthy as our application is complex.

**Comment by rokm** [comment]
> `pyinstaller==4.10`

This was fixed by #7170 (PyInstaller 5.6).
