### ISSUE TITLE
entitlements file not being used?

### ISSUE THREAD

**Issue by msj121** [pyinstaller/pyinstaller#7455]
I'm confused as using:
MacOs 12.2.1
Python 3.10.8
PyInstaller 5.8.0

Somehow I still get the standard info.plist and NOT the entitlements file that I am trying to use. Is there a way to change the info.plist? Can I manually edit it after creation or will that change the app size and cause an issue?

Spec file:
```
block_cipher = None
a = Analysis(
    ['pc.py'],
    pathex=[],
    binaries=[],
    datas=[('./lm/', 'lm'), ('./we/', 'we')],
    hiddenimports=['tensorflow'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='pc',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity='A0....',
    entitlements_file='/Users/me/Documents/Code/pc/Info.plist',
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='pc',
)
app = BUNDLE(
    coll,
    name='pc.app',
    icon=None,
    bundle_identifier='com.me.pc',
)
```

**Comment by rokm** [comment]
Entitlements file is not the same as `Info.plist`. The former is passed to the `codesign` utility when signing collected binaries and the bundle.

If you want to add custom entries to generated `Info.plist`, you need to pass a dictionary via `info_plist` argument to `BUNDLE`, as documented [here](https://pyinstaller.org/en/stable/spec-files.html#spec-file-options-for-a-macos-bundle). See also [here](https://pyinstaller.org/en/stable/feature-notes.html#registering-supported-file-types-and-custom-url-schemas) for an example. If you have an existing `Info.plist` that you want to use, you'll need to convert it to such  dictionary. 

You could also replace/edit the file itself after .app bundle is generated, but that will invalidate the (ad-hoc) signature, so you will probably need to resign the bundle yourself (either ad-hoc, or with real certificate, if you have one).
