### ISSUE TITLE
Altered `sys.path` is not respected in `collect_data_files` call to `isolated.call`

### ISSUE THREAD

**Issue by ikelos** [pyinstaller/pyinstaller#7456]
## Description of the issue

In our old spec files we used to locally add the current directory to `sys.path`, in order to make sure that the development (not installed) version of the python code could be packaged.  This used to work fine probably version with 4.8.

We added the spec file with a very early line of:
```
sys.path.append(os.path.dirname(os.path.abspath(SPEC)))
```
and later called an `Analysis` containing `data = collect_data_files('package.thing')` where under the current directory `package.thing` existed and was a valid package.

```
140 WARNING: collect_data_files - skipping data collection for module 'package.thing' as it is not a package.
338 INFO: Extending PYTHONPATH with paths
['/path/to/project', '/path/to/project', '/value/in/pathex']
```

Upon debugging it appears that the calls to `isolated.call` ignore the earlier call to `sys.path.append`, reverting to the initial pyinstaller's `sys.path` value.  The calls to "Extending PYTHONPATH" appear to occur after the data collection has occurred and it's not clear whether they would be taken into account or not.

A work around is to call `PYTHONPATH=/path/to/project pyinstaller file.spec`, which does then find package.thing and all other relevant files.

Please let me know if you need further information.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.8.0```
* Version of Python: 3.10
* Platform: Gentoo Linux
* How you installed Python: Gentoo package
* Did you also try this on another platform:  Also tested on Windows, also does not work
* Try the latest development version: Same issue

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode** 
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import os
import sys

from PyInstaller.building.api import PYZ, EXE
from PyInstaller.building.build_main import Analysis
from PyInstaller.utils.hooks import collect_submodules, collect_data_files, collect_dynamic_libs

sys.path.append(os.path.dirname(os.path.abspath(SPEC)))

analysis = Analysis(['scipt.py'],
                        pathex = [os.path.dirname(os.path.abspath(SPEC)), '/value/in/pathex'],
                        datas = collect_data_files('package.thing'))

pyz = PYZ(analysis.pure, analysis.zipped_data)
exe = EXE(pyz,
              analysis.scripts,
              analysis.binaries,
              analysis.zipfiles,
              analysis.datas,
              [('u', None, 'OPTION')],
              name = 'thing',
              debug = False,
              bootloader_ignore_signals = False,
              strip = False,
              upx = False,
              runtime_tmpdir = None,
              console = True)
```

### Stacktrace / full error message

```
140 WARNING: collect_data_files - skipping data collection for module 'package.thing' as it is not a package.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Is `package.thing` a package? I.e., is `thing` a subpackage of `package`, or is it actually a submodule?

**Comment by ikelos** [comment]
It passes the [`is_package` check](https://github.com/pyinstaller/pyinstaller/blob/c2011f1fee56fab611070e365fb26edd4a2c2fff/PyInstaller/utils/hooks/__init__.py#L457) as indicated when PYTHONPATH is appropriately set.  It's just that when it's set dynamically within the python spec itself, it vanishes in the isolated container.

**Comment by ikelos** [comment]
#6294 may be related.

**Comment by rokm** [comment]
Hmm, `sys.path` indeed does not seem to be propagated from parent process to the child. Marking this as a bug for now, because perhaps it should be.



> #6294 may be related.

No, that was the old behavior as well. If you want(ed) to use `collect_*` in spec for packages in non-default paths, you always had to either set `PYTHONPATH` accordingly or modify `sys.path` (which does not work anymore, as you noted). That's because additional paths passed via `--paths ` are applied when `Analysis` is instantiated, which is *after* `collect_*` functions in the spec file are called.

**Comment by bwoodsend** [comment]
I guess a `python_path += sys.path` somewhere in [here](https://github.com/pyinstaller/pyinstaller/blob/55eb4764f6c09894cd29180d5128476b8212fd21/PyInstaller/isolated/_parent.py#L171-L172) would do. My head hurts trying to figure out the order in the items should go in though.

**Comment by bwoodsend** [comment]
I suppose the parent's `PYTHONPATH` will already be in `sys.path` so it should be the `pathex` entries first, then `sys.path` then ignore `PYTHONPATH`.

**Comment by rokm** [comment]
What if we serialized parent's `sys.path` as part of args passed to the child, and overwrote it at the start of child process?

**Comment by bwoodsend** [comment]
That sounds like a better idea. Although make it *serialize parent's `pathex + sys.path`*.

**Comment by rokm** [comment]
Wouldn't `pathex` already be in `sys.path` once we pass [this point](https://github.com/pyinstaller/pyinstaller/blob/55eb4764f6c09894cd29180d5128476b8212fd21/PyInstaller/building/build_main.py#L349-L355), i.e., after `Analysis` is instantiated? 

Prior to that, `pathex` paths (as well as entry-point script's parent directory) have no effect on main process - and I don't see a straightforward way of dealing with that (which is what #6294 is about).

**Comment by bwoodsend** [comment]
Huh, why on earth do we go to all the trouble of keeping track of a separate `self.pathex` variable if we then go ahead and merge it with `sys.path` anyway...

**Comment by rokm** [comment]
> Huh, why on earth do we go to all the trouble of keeping track of a separate `self.pathex` variable if we then go ahead and merge it with `sys.path` anyway...

One use is [the guts check](https://github.com/pyinstaller/pyinstaller/blob/55eb4764f6c09894cd29180d5128476b8212fd21/PyInstaller/building/build_main.py#L427) to trigger re-analysis on change. Although now that I see it, I think it should be using full `sys.path` instead, because external changes induced via `PYTHONPATH` environment variable should probably also trigger re-analysis.
