### ISSUE TITLE
tcl encodings not bundled with Tkinter

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#746]
**Original date**: 2013/07/25
**Original reporter**: _anonymous_

Text input unable in Tkinter entry field due bad encoding on Windows with non-ascii locale (cp1251 in my case) after building application by Pyinstaller-2.0 and Python-2.7
The reason - no encoding directory in _MEI\tcl of builded application.
Workaround - manual copy directory tcl\tcl8.5\encoding from Python's install to _MEI\tcl\encoding of builded distrib.
Maybe this behavior should respect --ascii option of pyinstaller.py

**Comment by htgoebel** [comment]
This issue is 5 years old now, nobody worked on it and demand seems to be rare. So I'm closing this now.
