### ISSUE TITLE
pyinstaller 5.8.0 fails with blosc2 > 2.0.0

### ISSUE THREAD

**Issue by EricBLivingston** [pyinstaller/pyinstaller#7470]
## Description of the issue
Simply importing blos2 2.1.0 or 2.1.1 (the latest as of this report) will cause a series of recursive generation of console screens popping up and disappearing. In a multiprocessing environment they will be never-ending until they are all killed or the machine crashes. This occurs on both Windows and MacOs in my testing.

### Context information (for bug reports)

* Output of `pyinstaller --version`:  5.8.0
* Version of Python: 3.10
* Platform: Windows & OS X
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
This breakage occurs on Windows and OS X

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

import blosc2
if __name__ == "__main__":
    print("Hello World")

### Stacktrace / full error message

No error is printed: instead, multiple console windows pop up in rapid succession. If Multitasking is used, this continues forever until all related tasks are stopped or the machine crashes.

**Comment by rokm** [comment]
`blosc2` indirectly uses `multiprocessing`, so `multiprocessing.freeze_support` needs to be called at the start of the frozen application. 

Looks like some `multiprocessing` primitives are used when `blosc2` is imported (probably via `cpuinfo` package), so you need to ensure it is called before importing `blosc2`:

```python
# Must be done before importing blosc2
import multiprocessing
if __name__ == "__main__":
    multiprocessing.freeze_support()

import blosc2
if __name__ == "__main__":
    print("Hello World")
```

**Comment by EricBLivingston** [comment]
Hmm - do you mean just import multiprocessing prior, or also specifically call freeze_support() before importing blosc2?

**Comment by rokm** [comment]
> Hmm - do you mean just import multiprocessing prior, or also specifically call freeze_support() before importing blosc2?

You need to call `multiprocessing.freeze_support` before anything from `multiprocessing` is used (so in this case, before `blosc2` is imported).

**Comment by EricBLivingston** [comment]
This half-solves my problem. I implemented code like yours above, where the very first lines were your import and use of freeze_support prior to anything else.

This allows the frozen program to run... however it still quickly throws up two console windows which disappear too quickly to see what they are doing. This doesn't occur in an unfrozen run, so something's still going on with the frozen version that's causing something to happen in those console windows

I double-checked and blosc2 v2.0.0 does not generate those pop-up consoles. The problem starts with blosc2 v2.1.0

**Comment by rokm** [comment]
Are you using `noconsole`/`windowed` mode?

**Comment by rokm** [comment]
Also, looks like `blosc2` v2.1.0 added use of `cpuinfo`, so the changed behavior is likely coming from that: https://github.com/Blosc/python-blosc2/commit/c8adcf4d1c588cfe8a725ab515a91807ea4fdd22

**Comment by rokm** [comment]
If you are using `noconsole` / `windowed` mode, then the following two subprocesses in `cpuinfo` that try to run `wmi` on Windows will end up forcing their own console open: [first](https://github.com/workhorsy/py-cpuinfo/blob/f3f0fec58335b9699b9b294267c15f516045b1fe/cpuinfo/cpuinfo.py#L220-L222) and [second](https://github.com/workhorsy/py-cpuinfo/blob/f3f0fec58335b9699b9b294267c15f516045b1fe/cpuinfo/cpuinfo.py#L273-L274).

To prevent that, their `_run_and_get_stdout` implementation should be patched to pass [`creationflags = subprocess.CREATE_NO_WINDOW`](https://docs.python.org/3/library/subprocess.html#subprocess.CREATE_NO_WINDOW) argument to [this `Popen` call](https://github.com/workhorsy/py-cpuinfo/blob/f3f0fec58335b9699b9b294267c15f516045b1fe/cpuinfo/cpuinfo.py#L323) (only on Windows).

**Comment by EricBLivingston** [comment]
Aha - yes, when the windows flash up I can see for a moment that wmi is part of the window title.

I am using noconsole, so it's as you describe. Why would that not be happening when I run normally (unfrozen?) I suppose because I'm launching in a console within my IDE? (PyCharm)

Is there a workaround or are we just stuck? Or, can I monkey-patch cpuinfo myself to add in the edit you describe?

I guess I could change that line in my copy to read:
p1 = Popen(command, stdout=PIPE, stderr=PIPE, stdin=PIPE, creationflags=subprocess.CREATE_NO_WINDOW)

**Comment by rokm** [comment]
> I am using noconsole, so it's as you describe. Why would that not be happening when I run normally (unfrozen?) I suppose because I'm launching in a console within my IDE? (PyCharm)

Yes; if there is a console available, the spawned sub-processes do not open a new one. Conversely, if there is no console available, they open a new console themselves (unless they are also windowed/noconsole programs).

> Is there a workaround or are we just stuck? Or, can I monkey-patch cpuinfo myself to add in the edit you describe?
> 
> I guess I could change that line in my copy to read: p1 = Popen(command, stdout=PIPE, stderr=PIPE, stdin=PIPE, creationflags=subprocess.CREATE_NO_WINDOW)

I think modifying your copy of `cpuinfo` is the only work-around for this. If it works, you could perhaps let the `cpuinfo` folks know, so they upstream the change.

**Comment by bwoodsend** [comment]
You'd be amazed at how many popular packages are naive to the idea that Python can be run in windowed mode.
