### ISSUE TITLE
crashpad warnings or errors

### ISSUE THREAD

**Issue by Akash88py** [pyinstaller/pyinstaller#7479]
When ever use GUI like PyQt5 or tkinter in my python code and convert into .exe file. I get the below error
Can not init crashpad with status: CRASHPAD_DB_INIT_ERROR[5352:NonCelloThread] registry_win.h:55:GetProtoFromRegistryValue Opening registry key Software\Google\DriveFS\Share failed with 0x2
[5340:NonCelloThread] registry_win.h:55:GetProtoFromRegistryValue Opening registry key Software\Google\DriveFS\Share failed with 0x2

Is there there any way I can make this error not come?

**Comment by Akash88py** [comment]
Here is code I am using.

from PyQt5 import QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow, QPushButton, QFileDialog
from PyQt5 import QtCore
import sys
 
 
def dialog():
    file , check = QFileDialog.getOpenFileName(None, "QFileDialog.getOpenFileName()",
                                               "", "All Files (*);;Python Files (*.py);;Text Files (*.txt)")
    if check:
        print(file)
 
app = QApplication(sys.argv)
win = QMainWindow()
win.setGeometry(400,400,300,300)
win.setWindowTitle("CodersLegacy")
  
button = QPushButton(win)
button.setText("Press")
button.clicked.connect(dialog)
button.move(50,50)
 
win.show()
sys.exit(app.exec_())

**Comment by rokm** [comment]
This looks like something that's caused by Google Drive FS, and has nothing to do with us (i.e., cannot be reproduced in an environment without Google Drive FS installed).
