### ISSUE TITLE
pytorch project on mac can not work

### ISSUE THREAD

**Issue by ILG2021** [pyinstaller/pyinstaller#7485]
Hello, I have developed a yolo server based on pytorch and I use pyinstaller to package it. It works well on windows, but when I packages it on Mac, the execute app will stuck, even no error is print to terminal.
Anyone have packaged pytorch project on mac successfully. 
This is the yolo project:
https://github.com/ILG2021/yolo-server

The command i use to package:
pyinstaller --noconfirm --onefile --console --icon "./yolo.png" --add-data "./venv/Lib/site-packages/yolov7;yolov7/"  "./yolo.py"

**Comment by rokm** [comment]
If you get an error about `'@loader_path/../../functorch/.dylibs/libiomp5.dylib'` not being found (which in turn prevents `libtorch_global_deps.dylib` from being loaded), you need to add `--collect-binaries functorch` to your PyInstaller command.

However, to get `torch`-based frozen applications work on macOS, you will also need work-around from https://github.com/pyinstaller/pyinstaller-hooks-contrib/issues/375#issuecomment-1025913127.
