### ISSUE TITLE
matplotlib tmp folders

### ISSUE THREAD

**Issue by Akascape** [pyinstaller/pyinstaller#7487]
I have noticed that if my executable imports **matplotlib or imageio** package, then it creates a random empty **tmp folder** inside the OS temp directory (`C:\Users\User\AppData\Local\Temp`).
Note that I am **not** discussing about the `MEIxxxxxx` folder which is generated with one-file mode. It is a different tmp folder (maybe generated using the tempfile method with prefix-tmp).
Though this folder gets deleted when we exit the program, but I don't know why this is happening with some library imports only. This is not happening if I run the normal python file.

I am using pyinstaller 5.8.0, python 3.9, windows 11.

**Comment by bwoodsend** [comment]
Our [runtime hook for matplotlib](https://github.com/pyinstaller/pyinstaller/blob/df992f17040a76fac5ac21d1edbfd72bb751c217/PyInstaller/hooks/rthooks/pyi_rth_mplconfig.py) creates a new temporary directory to redirect matplotlib's config directory into. I imagine that importing `imageio` makes PyInstaller include `matplotlib` due to the matplotlib imports in `imageio/plugins/_tifffile.py` so again, that leads to the runtime hook being included.

I have been meaning to scrap that hook for years but there's been some disagreement over whether it should stay or not.

**Comment by Akascape** [comment]
@bwoodsend Now it makes sense. I have also used the matplotlib font function in one of my app, so it will be necessary in that case.

But there should be an option to change that tmp folder spawn location in one-file mode, like maybe merging it with `runtime-tmpdir` is a good idea.

I generally don't like to use the default os temp directory because of crash/permission issues, so I use runtime-tmpdir.

**Moreover, this tmp folder is also generated with the one-directory executable. Ig that hook is unnecessary for one-dir mode.**

**Comment by bwoodsend** [comment]
The runtime hook serves the same purpose in either onefile or onedir mode. Without the runtime hook, matplotlib generates a cache of all available fonts and stores it somewhere in your home directory so that the next time matplotlib is started, it doesn't have to regenerate that cache. The runtime hook tells matplotlib to store its cache in a temporary directory which PyInstaller then deletes so that the next time the application launches, it has to regenerate the fonts list from scratch.

**Comment by Akascape** [comment]
@bwoodsend I understand, I just want to know if it will be possible to change that tmp folder location from OS temp directory to a different location? Like the MEIxxxxxx folder location which can be changed using `runtime-tmpdir`.

**Comment by Akascape** [comment]
@bwoodsend This tmp folder should not be created in the os temp directory.
Ig the problem can be fixed by just changing [this line](https://github.com/pyinstaller/pyinstaller/blob/df992f17040a76fac5ac21d1edbfd72bb751c217/PyInstaller/hooks/rthooks/pyi_rth_mplconfig.py#L31) in the hook:
```python
configdir = tempfile.mkdtemp(dir=sys._MEIPASS, prefix="matplotlib_cache_")
```
Or maybe create the file in matplotlib's main folder and **remove the atexit method** from the hook. This will also prevent the one-dir from making the tmp again.
```python
configdir = os.path.join(sys._MEIPASS, "matplotlib", "cache")
```
Will there be any issue?

**Comment by rokm** [comment]
> @bwoodsend This tmp folder should not be created in the os temp directory.

Why not? That's what the OS temp directory is generally used for...

So if you want this matplotlib cache relocated for your application, you can modify the hook yourself.

Or as a more general approach, create a custom runtime hook that overrides `os.environ['TMP']` (or `TEMP`, or whichever the corresponding environment variable is for the OS) with your custom location (e.g., based on `sys._MEIPASS`). Then add this runtime hook to your frozen program via [`--runtime-hook`](https://pyinstaller.org/en/stable/usage.html#cmdoption-runtime-hook) command-line argument (or equivalent spec file options, if you're building from the spec). I think these custom runtime hooks are always ran first, so it should change the temporary directory location before the matplotlib runtime hook is ran.

> Will there be any issue?

In general, possibly yes.

There's no guarantee that sys._MEIPASS is actually writable (e.g., if onedir bundle is installed in read-only location, or if macOS app bundle translocation has kicked in, and so on). Therefore, the frozen application should ideally be considered immutable (regardless of onedir or onefile mode).

**Comment by Akascape** [comment]
@rokm  Ok I get it,
> There's no guarantee that sys._MEIPASS is actually writable (e.g., if onedir bundle is installed in read-only location, or if macOS app bundle translocation has kicked in, and so on). Therefore, the frozen application should ideally be considered immutable (regardless of onedir or onefile mode).

Just want to ask another question, if we use `-runtime tmpdir` with onefile mode and suppose the exe file is in a read-only location, will the MEIxxxxxx folder be created in that case?

**Comment by rokm** [comment]
> Just want to ask another question, if we use `-runtime tmpdir` with onefile mode and suppose the exe file is in a read-only location, will the MEIxxxxxx folder be created in that case?

If the tmpdir ends up in read-only location (e.g., next to executable), the exe will fail to extract and run.

**Comment by Akascape** [comment]
@rokm but the hook should be more specific, because the matplotlib font cache only forms if we use something like `matplotlib.font_manager.findSystemFonts()`,
otherwise the tmp folder stays empty.

Just importing matplotlib is also creating that unnecessary temp folder.

**Comment by rokm** [comment]
> @rokm but the hook should be more specific, because the matplotlib font cache only forms if we use something like `matplotlib.font_manager.findSystemFonts()`, otherwise the tmp folder stays empty.
> 
> Just importing matplotlib is also creating that unnecessary temp folder.

Yeah, as far as font cache goes, that's a good point. It seems that `matplotlib.get_cachedir` is used within `matplotlib.font_manager` and `matplotlib.texmanager`.

But on the other hand, I think overriding `MPLCONFIGDIR` dir (and consequently creating a valid temporary directory for it) also ensures that the frozen application is isolated from any `matplotlib` configuration found in user's home directory, which might be applicable to their python+matplotlib installation, but not to the frozen application. For example, if they had `$MPLCONFIGDIR/matplotlibrc` that forces particular backend that is not available in the (3rd party) frozen application that they also try to run on their system (without knowing it is based on python+matplotlib). `MPLCONFIGDIR` is queried during import of `matplotlib`, and the existence of the directory (and ability to write to it) is also checked.

So I'm not convinced that the current behavior needs to be changed. If you are really bothered by creation of that temporary directory, then modify your local copy of the hook.
