### ISSUE TITLE
Add Option to don't write spec

### ISSUE THREAD

**Issue by JakobDev** [pyinstaller/pyinstaller#7492]
**Is your feature request related to a problem? Please describe.**
Currently PyInstaller always writes a.spec file, but there are cases in which this is not needed e.g. when using a custom build script which calls PyInstaller directly with the correct arguments.

**Describe the solution you'd like**
Adding a new `--no-spec` Option, to make PyInstaller not write a .spec file.

**Describe alternatives you've considered**
Deleting the File from the script, but it would be better, if it would not be created at all.

**Additional context**
None

**Comment by bwoodsend** [comment]
The spec file is used by PyInstaller - even if you don't touch it. Preventing its writing to disk would require PyInstaller to generate the spec file in memory then execute it from there. It wouldn't be impossible but I don't see the point in all that effort/abstraction.

**Comment by JakobDev** [comment]
Then this Option could apply, that the spec is written in a temporary directory and deleted after being used.

**Comment by rokm** [comment]
I fail to see the benefit of adding yet another option for something that can be easily achieved by the caller. Doubly so when `PyInstaller` is called programmatically from custom build script.

**Comment by bwoodsend** [comment]
Why are you so opposed to there being a spec file? If you add it to your `.gitignore` it should be no more intrusive that `__pycache__` or pytest's cache or any other generated file.

**Comment by JakobDev** [comment]
I just don't like it, when working files are placed

**Comment by bwoodsend** [comment]
That really doesn't sell if for me.
