### ISSUE TITLE
Looking to install pyinstaller on a ARM64 Windows device

### ISSUE THREAD

**Issue by 200502002** [pyinstaller/pyinstaller#7499]
**Is your feature request related to a problem? Please describe.**
In a way. I am looking to build an executable to used on windows on arm test devices.

**Describe the solution you'd like**
Got the latest pyinstaller from Github. The bootloader folder doesn't have ARM64.

**Describe alternatives you've considered**
I need to write my executable in C or C++ which I'm trying to desperately avoid. I'd benefit a lot if I could use python and build an executable because python has some inbuilt libraries that I can readily use.

**Additional context**
Will be using numpy etc to include in this executable.

**Comment by bwoodsend** [comment]
There's arm64 Windows wheels on PyPI. Conventional `pip install pyinstaller` on an arm64 machine with arm64 Python should work.

**Comment by bwoodsend** [comment]
Looks like NumPy don't support Windows+arm64 yet though so probably still a dead end.

**Comment by 200502002** [comment]
I'll try to work around NumPy if I can get this working. I need numpy to
compute the RMS value and THD+N of a recorded signal. Do you have any
recommendations on Python and Pyinstaller versions? These are the ones I've
at this time.
Python: 3.11.2.
PyInstaller: 5.9.0


Best regards,
Anupama.

**Comment by bwoodsend** [comment]
They should be fine since they both support arm64.

**Comment by 200502002** [comment]
Thanks, I have this limitation at the moment where the network adapter is
not working. Is there a way I can install this offline? or may be copy the
setup files to the device from elsewhere?

**Comment by bwoodsend** [comment]
Not really. `pip wheel pyinstaller` will download the wheels you need which you can copy onto the machine without  network but that requires another machine that has pip and network access.
