### ISSUE TITLE
shell completion

### ISSUE THREAD

**Issue by Freed-Wu** [pyinstaller/pyinstaller#7500]
Can pyinstaller provide completions for common shells?

**Describe the solution you'd like**
<https://docs.iterative.ai/shtab/>

Like:

- <https://github.com/google/vimdoc/blob/823e3bbc1944d0377408b602ec10ba0c39a8bf8e/setup.py#L36>
- <https://github.com/andreafrancia/trash-cli/blob/b913bf30b277cecc04f27858d275802684ecac13/setup.cfg#L31-L33>
- <https://github.com/inducer/pudb/blob/1dea19a3a14ba2398e5b7909eb86cad0c0152b3d/setup.py#L24>
- <https://github.com/piccolomo/plotext/blob/f760510cc6957de82c57502c07e4d0c0e4762302/setup.py#L25>
- <https://github.com/wookayin/gpustat/blob/56a9dcf3c99f29065f1215afcff372d01da9f256/setup.py#L116>

**Describe alternatives you've considered**
<https://docs.iterative.ai/shtab/#alternatives>

**Comment by bwoodsend** [comment]
I'm game for giving shtab a shot. I did actually try integrating argcomplete once but it was so slow and worked so badly that I gave up on it. At a glance, it looks like shtab actually does it properly - installing completion files once rather than on the fly ever time you press tab.

**Comment by bwoodsend** [comment]
Closed by #8008. We ended up going for argcomplete after all.
