### ISSUE TITLE
Recursion detected at runtime when using pyinstaller

### ISSUE THREAD

**Issue by DaveCodeP** [pyinstaller/pyinstaller#7502]
I'm using pyinstaller to create a windows exe that controls a Sentech USB Camera. The Python code works fine running under Python but fails when running as an exe. The exception message that I get at runtime is "ERROR: recursion is detected during loading of "stapipy" binary extensions". The code that generates the error message is below. It appears that when run as a python script the line **native_module = importlib.import_module('stapipy')** imports the correct module from the file "stapipy.cp38-win_amd64.pyd" but when run as an exe causes the bootloader function (below) to be called recursively resulting in the error message.

	# '__init__.py' file for the stapipy module (which includes the line that raises the above exception) is below:

    import os
    import sys
    import importlib
    
    __all__ = []
    
    def bootstrap():
        import copy
        save_sys_path = copy.copy(sys.path)
        
        if hasattr(sys, 'STAPI_LOADER'):
            print(sys.path)
            raise ImportError('ERROR: recursion is detected during loading of "stapipy" binary extensions.')
        sys.STAPI_LOADER = True
    
        DEBUG = False
        if hasattr(sys, 'STAPI_LOADER_DEBUG'):
            DEBUG = True
    
        import platform
        if DEBUG: print('stapipy loader: os.name="{}" platform.system()="{}"'.format(os.name, str(platform.system())))
    
        LOADER_DIR = os.path.dirname(os.path.abspath(os.path.realpath(__file__)))
    
        PYTHON_EXTENSIONS_PATHS = [LOADER_DIR]
    
        g_vars = globals()
        l_vars = locals()
    
        if DEBUG: print(f"stapipy loader: PYTHON_EXTENSIONS_PATHS = {l_vars['PYTHON_EXTENSIONS_PATHS']}")
    
        applySysPathWorkaround = False
        if hasattr(sys, 'STAPI_REPLACE_SYS_PATH_0'):
            applySysPathWorkaround = True
        else:
            try:
                BASE_DIR = os.path.dirname(LOADER_DIR)
                if sys.path[0] == BASE_DIR or os.path.realpath(sys.path[0]) == BASE_DIR:
                    applySysPathWorkaround = True
            except:
                if DEBUG: print("stapipy loader: exception during checking workaround for sys.path[0]")
                pass  # applySysPathWorkaround is False
            
        for p in l_vars['PYTHON_EXTENSIONS_PATHS']:
            sys.path.insert(1 if not applySysPathWorkaround else 0, p)
        
        env_str = ""
        import re
        ptn = re.compile('STAPI_BIN_PATH_V1_2')
        for env in os.environ:
            result = ptn.fullmatch(env)
            if result:
                env_str = result.group()
                break
        if DEBUG: print(f"stapipy loader: env_str = {env_str}")
    
        if env_str and sys.version_info >= (3, 8):
            for item in os.getenv(env_str).split(';'):
                os.add_dll_directory(item)
                if DEBUG: print(f"stapipy loader: add_dll_directory({item})")
        
        if DEBUG: print("Relink everything from native stapipy module to stapipy package")
    
        py_module = sys.modules.pop('stapipy')
    
        native_module = importlib.import_module('stapipy')
    
        sys.modules['stapipy'] = py_module
        setattr(py_module, 'stapipy', native_module)
    
        for item_name, item in filter(lambda kv: kv[0] not in ('__file__', '__loader__', '__spec__',
                                                               '__name__', '__package__'),
                                      native_module.__dict__.items()):
            if item_name not in g_vars:
                g_vars[item_name] = item
        
        sys.path = save_sys_path  # multiprocessing should start from bootstrap code
    
        try:
            del sys.STAPI_LOADER
        except Exception as e:
            if DEBUG:
                print("Exception during delete STAPI_LOADER:", e)
        
        if DEBUG: print("stapipy loader: DONE")
    
    bootstrap()

The output from pyinstaller is below:

    G:\My Drive\Python\PDR\AssistAlign>pyinstaller --clean --onefile --add-binary "*.png;." --add-binary "*.gif;." --name "PDRCAM" assistalign.py
    3057 INFO: PyInstaller: 5.9.0
    3057 INFO: Python: 3.8.6
    3058 INFO: Platform: Windows-10-10.0.19041-SP0
    3126 INFO: wrote G:\My Drive\Python\PDR\AssistAlign\PDRCAM.spec
    3185 INFO: UPX is not available.
    3185 INFO: Removing temporary files and cleaning cache in C:\Users\Dave\AppData\Local\pyinstaller
    26530 INFO: Extending PYTHONPATH with paths
    ['G:\\My Drive\\Python\\PDR\\AssistAlign']
    28704 INFO: checking Analysis
    28705 INFO: Building Analysis because Analysis-00.toc is non existent
    28706 INFO: Initializing module dependency graph...
    28714 INFO: Caching module graph hooks...
    29155 INFO: Analyzing base_library.zip ...
    32895 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    33669 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    37240 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    41131 INFO: Caching module dependency graph...
    41905 INFO: running Analysis Analysis-00.toc
    42092 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
      required by C:\Users\Dave\AppData\Local\Programs\Python\Python38\python.exe
    43803 INFO: Analyzing G:\My Drive\Python\PDR\AssistAlign\assistalign.py
    44235 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    44372 INFO: Loading module hook 'hook-cv2.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
    44644 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    47722 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
    47869 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    48054 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    48647 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    49427 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    52235 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    56362 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    60835 INFO: Processing module hooks...
    61264 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks'...
    61299 INFO: checking Tree
    61301 INFO: Building Tree because Tree-00.toc is non existent
    61301 INFO: Building Tree Tree-00.toc
    64141 INFO: checking Tree
    64143 INFO: Building Tree because Tree-01.toc is non existent
    64143 INFO: Building Tree Tree-01.toc
    64206 INFO: checking Tree
    64209 INFO: Building Tree because Tree-02.toc is non existent
    64209 INFO: Building Tree Tree-02.toc
    64380 INFO: Looking for ctypes DLLs
    64400 INFO: Analyzing run-time hooks ...
    64412 INFO: Including run-time hook 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
    64423 INFO: Including run-time hook 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
    64438 INFO: Including run-time hook 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
    64448 INFO: Including run-time hook 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
    64521 INFO: Looking for dynamic libraries
    C:\Users\Dave\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\building\build_main.py:177: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
      __import__(package)
    8411 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\numpy\\.libs', 'C:\\Program Files (x86)\\Common Files\\OMRON_SENTECH\\GenICam\\v3_4\\Win32\\bin\\', 'C:\\Program Files (x86)\\Common Files\\OMRON_SENTECH\\StApi\\v1_2\\Win32\\bin\\', 'C:\\Program Files\\Common Files\\OMRON_SENTECH\\GenICam\\v3_4\\x64\\bin\\', 'C:\\Program Files\\Common Files\\OMRON_SENTECH\\StApi\\v1_2\\x64\\bin\\']
    8412 INFO: Extra DLL search directories (PATH): ['C:\\Program Files (x86)\\Common Files\\MVS\\Runtime\\Win32_i86', 'C:\\Program Files (x86)\\Common Files\\MVS\\Runtime\\Win64_x64', 'C:\\Program Files (x86)\\Common Files\\MvCodeCameraSDK\\Runtime\\Win64_x64', 'C:\\Program Files (x86)\\Common Files\\MvCodeCameraSDK\\Runtime\\Win32_i86', 'C:\\Program Files\\General MVTech\\MV Viewer\\Runtime\\x64\\', 'C:\\Program Files\\General MVTech\\MV Viewer\\Runtime\\Win32\\', 'C:\\WINDOWS\\System32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\PROGRA~1\\DISKEE~1\\DISKEE~1', 'C:\\WINDOWS\\system32', 'C:\\WINDOWS', 'C:\\WINDOWS\\System32\\Wbem', 'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\WINDOWS\\System32\\OpenSSH\\', 'C:\\PROGRA~1\\CONDUS~1\\DISKEE~1\\', 'C:\\Users\\Dave\\AppData\\Local\\Packages\\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\\LocalCache\\local-packages\\Python38\\Scripts', 'C:\\Program Files\\Common Files\\OMRON_SENTECH\\GenICam\\v3_2\\bin\\', 'C:\\Program Files\\Common Files\\OMRON_SENTECH\\StApi\\v1_1\\', 'C:\\Program Files (x86)\\Common Files\\OMRON_SENTECH\\GenICam\\v3_2\\bin\\', 'C:\\Program Files (x86)\\Common Files\\OMRON_SENTECH\\StApi\\v1_1\\', 'C:\\Program Files (x86)\\Common Files\\OMRON_SENTECH\\GenICam\\v3_4\\Win32\\bin\\', 'C:\\Program Files (x86)\\Common Files\\OMRON_SENTECH\\StApi\\v1_2\\Win32\\bin\\', 'C:\\Program Files\\Common Files\\OMRON_SENTECH\\GenICam\\v3_4\\x64\\bin\\', 'C:\\Program Files\\Common Files\\OMRON_SENTECH\\StApi\\v1_2\\x64\\bin\\', 'C:\\Program Files\\Git\\cmd', 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\Scripts\\', 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\', 'C:\\Users\\Dave\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\Dave\\AppData\\Local\\Programs\\Microsoft VS Code\\bin']
    78195 INFO: Looking for eggs
    78197 INFO: Using Python library C:\Users\Dave\AppData\Local\Programs\Python\Python38\python38.dll
    78198 INFO: Found binding redirects:
    []
    78323 INFO: Warnings written to G:\My Drive\Python\PDR\AssistAlign\build\PDRCAM\warn-PDRCAM.txt
    78685 INFO: Graph cross-reference written to G:\My Drive\Python\PDR\AssistAlign\build\PDRCAM\xref-PDRCAM.html
    78866 INFO: Appending 'binaries' from .spec
    80617 INFO: checking PYZ
    80627 INFO: Building PYZ because PYZ-00.toc is non existent
    80628 INFO: Building PYZ (ZlibArchive) G:\My Drive\Python\PDR\AssistAlign\build\PDRCAM\PYZ-00.pyz
    82474 INFO: Building PYZ (ZlibArchive) G:\My Drive\Python\PDR\AssistAlign\build\PDRCAM\PYZ-00.pyz completed successfully.
    82627 INFO: checking PKG
    82629 INFO: Building PKG because PKG-00.toc is non existent
    82630 INFO: Building PKG (CArchive) PDRCAM.pkg
    158602 INFO: Building PKG (CArchive) PDRCAM.pkg completed successfully.
    159202 INFO: Bootloader C:\Users\Dave\AppData\Local\Programs\Python\Python38\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\run.exe
    159202 INFO: checking EXE
    159218 INFO: Building EXE because EXE-00.toc is non existent
    159218 INFO: Building EXE from EXE-00.toc
    161018 INFO: Copying bootloader EXE to G:\My Drive\Python\PDR\AssistAlign\dist\PDRCAM.exe.notanexecutable
    163167 INFO: Copying icon to EXE
    163196 INFO: Copying icons from ['C:\\Users\\Dave\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages\\PyInstaller\\bootloader\\images\\icon-console.ico']
    163202 INFO: Writing RT_GROUP_ICON 0 resource with 104 bytes
    163203 INFO: Writing RT_ICON 1 resource with 3752 bytes
    163204 INFO: Writing RT_ICON 2 resource with 2216 bytes
    163204 INFO: Writing RT_ICON 3 resource with 1384 bytes
    163205 INFO: Writing RT_ICON 4 resource with 37019 bytes
    163206 INFO: Writing RT_ICON 5 resource with 9640 bytes
    163221 INFO: Writing RT_ICON 6 resource with 4264 bytes
    163223 INFO: Writing RT_ICON 7 resource with 1128 bytes
    163428 INFO: Copying 0 resources to EXE
    163429 INFO: Embedding manifest in EXE
    163433 INFO: Updating manifest in G:\My Drive\Python\PDR\AssistAlign\dist\PDRCAM.exe.notanexecutable
    163443 INFO: Updating resource type 24 name 1 language 0
    163625 INFO: Appending PKG archive to EXE
    164830 INFO: Fixing EXE headers
    171130 INFO: Building EXE from EXE-00.toc completed successfully.

Any help much appreciated

**Comment by rokm** [comment]
PyInstaller's `FrozenImporter` does not support attempts at package substituting itself with a submodule via `sys.path` manipulation, hence the recursion error. 

So the only solution here is to force collection in source mode to prevent any modules from being collected into PyInstaller's PYZ archive (thus bypassing the `FrozenImporter`), similarly to [what we have to do for OpenCV (which has the same problem)](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/d2c02afc587775b0e36b6279a9e1e04d2df13645/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-cv2.py#L139-L148).

I.e., you'll need to create a custom hook (`hook-stapipy.py`) that sets `module_collection_mode` [global hook variable](https://pyinstaller.org/en/stable/hooks.html#hook-global-variables) to `'py'`, and then pass the directory that contains the extra hook via [`--additional-hooks-dir`](https://pyinstaller.org/en/stable/usage.html#cmdoption-additional-hooks-dir) argument to your PyInstaller command.

**Comment by DaveCodeP** [comment]
Thanks for your help. I'll try and work through that now.
