### ISSUE TITLE
Simple PyQt5 script packaged on Ubuntu 16.04 fails to run on Ubuntu 22.04

### ISSUE THREAD

**Issue by BLKSerene** [pyinstaller/pyinstaller#7506]
Sorry for this issue. I've searched around and tried many solutions. Although I somewhat find a workaround now, I'm wondering whether there is a simpler and better solution.

When a simple PyQt5 script is packaged on Ubuntu 16.04, it runs without any problem on Ubuntu 16.04, but fails to run on Ubuntu 22.04.

The simple PyQt5 script:
```
import sys

from PyQt5.QtWidgets import QApplication, QMainWindow

class Test(QMainWindow):
    pass

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.processEvents()

    test = Test()
    test.showMaximized()

    sys.exit(app.exec_())
```
When run on Ubuntu 22.04, it shows the following error:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_log_structured_standard
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(1:9079): GLib-GIO-ERROR **: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
```
Setting QT_QPA_PLATFORM=wayland did not solve the problem, and the error now is:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
/usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so: undefined symbol: g_log_structured_standard
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libdconfsettings.so
GLib-GIO-Message: Using the 'memory' GSettings backend.  Your settings will not be saved or shared with other applications.

(1:9083): GLib-GIO-ERROR **: Settings schema 'org.gnome.settings-daemon.plugins.xsettings' does not contain a key named 'antialiasing'
Trace/breakpoint trap (core dumped)
```

Sudo executing the program solve the problem, but it shows a lot of warning:
```
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
/usr/lib/x86_64-linux-gnu/gvfs/libgvfscommon.so: undefined symbol: g_task_set_name
Failed to load module: /usr/lib/x86_64-linux-gnu/gio/modules/libgvfsdbus.so

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:18:21: '-gtk-outline-radius' is not a valid property name

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:19:28: '-gtk-secondary-caret-color' is not a valid property name

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:31:20: '-gtk-icon-shadow' is not a valid property name

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:39:2: Missing name of pseudo-class

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:51:21: Missing name of pseudo-class

...here skips a lot of Gtk-WARNING here...

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:6466:12: 'min-height' is not a valid property name

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:6558:12: 'min-height' is not a valid property name

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:6568:22: Not a valid image

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:6575:13: 'min-width' is not a valid property name

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:6576:14: 'min-height' is not a valid property name

(1:9142): Gtk-WARNING **: Theme parsing error: gtk.css:6580:20: '-gtk-icon-shadow' is not a valid property name
libGL error: MESA-LOADER: failed to open vmwgfx: /usr/lib/dri/vmwgfx_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: vmwgfx
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```

And I have no idea why sudo solves the problem. Logging out and switching to Xorg also solves the problem, but showing the same errors above (except the first line). So I guess it is related to Ubuntu switching to wayland starting from 21.04? Manually switching to Xorg or requiring sudo every time to startup the packaged program is awkward for my users. So, are there anything I'm missing here?

Python: 3.9.16 (compiled from source)
OS: Ubuntu 16.04/22.04
PyInstaller: 5.9.0
PyQt5: 5.15.9

**Comment by bwoodsend** [comment]
Did you install PyQt5 using apt or pip? The PyQt5 wheels on PyPI contain libraries to support both X and wayland and PyInstaller makes a point of collecting both so this *should* work with pip's variant.

**Comment by BLKSerene** [comment]
> Did you install PyQt5 using apt or pip? The PyQt5 wheels on PyPI contain libraries to support both X and wayland and PyInstaller makes a point of collecting both so this _should_ work with pip's variant.

PyQt5 is installed via pip.

**Comment by rokm** [comment]
Looks like incompatibility of the mix of libraries that were collected from the build system and the ones that are available on the host system. Which is not really surprising, considering the amount of changes in the ABI between Ubuntu 16.04 and 22.04.

If PyQt5 is installed via pip, and if this is a onedir build, you could try manually removing some of the collected shared libraries (starting with `libstdc++`, if collected; then anything related to Gtk, GLib/Gio, and X) and see if you can get it to work.

But in general, binary distribution of software on linux is complicated (especially if using UI frameworks) and full of pitfalls, and there are no guarantees for compatibility across different distributions or across different versions of the same distribution.

**Comment by BLKSerene** [comment]
> Looks like incompatibility of the mix of libraries that were collected from the build system and the ones that are available on the host system. Which is not really surprising, considering the amount of changes in the ABI between Ubuntu 16.04 and 22.04.
> 
> If PyQt5 is installed via pip, and if this is a onedir build, you could try manually removing some of the collected shared libraries (starting with `libstdc++`, if collected; then anything related to Gtk, GLib/Gio, and X) and see if you can get it to work.
> 
> But in general, binary distribution of software on linux is complicated (especially if using UI frameworks) and full of pitfalls, and there are no guarantees for compatibility across different distributions or across different versions of the same distribution.

Thanks for the suggestions. Since I do not work with Ubuntu very often (only for distributing Linux version of my app), is there any API from PyInstaller that I could use to get a list of all related DLLs (as there are so many under the dist folder)?

**Comment by rokm** [comment]
> > Looks like incompatibility of the mix of libraries that were collected from the build system and the ones that are available on the host system. Which is not really surprising, considering the amount of changes in the ABI between Ubuntu 16.04 and 22.04.
> > If PyQt5 is installed via pip, and if this is a onedir build, you could try manually removing some of the collected shared libraries (starting with `libstdc++`, if collected; then anything related to Gtk, GLib/Gio, and X) and see if you can get it to work.
> > But in general, binary distribution of software on linux is complicated (especially if using UI frameworks) and full of pitfalls, and there are no guarantees for compatibility across different distributions or across different versions of the same distribution.
> 
> Thanks for the suggestions. Since I do not work with Ubuntu very often (only for distributing Linux version of my app), is there any API from PyInstaller that I could use to get a list of all related DLLs (as there are so many under the dist folder)?

Unfortunately there is not. The shared libs that we do collect are determined by recursive dependency analysis (e.g., running `ldd` on a binary python extension, and then running it again on all its dependencies, and then again on each of those, and so on). 

And to make matters worse, when trying to debug the problems with mixing collected and system libraries, there is usually no general rule as what to do (i.e., what libraries to remove from the frozen application or what libraries to add). So you need to find the working combination (if it even exists) through experimentation (and aided by prior experience/knowledge).

If your application is not proprietary, it is better to use distribution's standard packaging mechanisms (e.g., provide PPA with deb packages for Ubuntu), or have users set up virtual environments instead of using PyInstaller and try creating a "universal" Linux binary (there is no such thing, especially when you use libraries with complex dependency trees).

**Comment by BLKSerene** [comment]
@rokm Ah, lucky that I only tried deleting two files... I confirmed that removing `libgtk-3.so.0` (this single file) fixes most warnings. No need to sudo anymore, and no Gtk-WARNING (styles for the open file dialog of Qt also become normal).

Now only 3 warnings remain. Then, removing `libstdc++.so.6` fixes 2 of them:
```
libGL error: MESA-LOADER: failed to open vmwgfx: /usr/lib/dri/vmwgfx_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: vmwgfx
libGL error: MESA-LOADER: failed to open swrast: /usr/lib/dri/swrast_dri.so: cannot open shared object file: No such file or directory (search paths /usr/lib/x86_64-linux-gnu/dri:\$${ORIGIN}/dri:/usr/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
```
I'm not sure how to fixes the last 1 warning:
`Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`
But it seems that most functions are back to normal now, I'm OK with it. Thanks anyway!

**Comment by rokm** [comment]
> I'm not sure how to fixes the last 1 warning:
> `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`
> But it seems that most functions are back to normal now, I'm OK with it. Thanks anyway!

I suppose a quick work-around might be to check if `XDG_SESSION_TYPE` environment variable contains `wayland`, and then set `QT_QPA_PLATFORM=wayland ` instead (at the very start of your program).

**Comment by BLKSerene** [comment]
> > I'm not sure how to fixes the last 1 warning:
> > `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`
> > But it seems that most functions are back to normal now, I'm OK with it. Thanks anyway!
> 
> I suppose a quick work-around might be to check if `XDG_SESSION_TYPE` environment variable contains `wayland`, and then set `QT_QPA_PLATFORM=wayland ` instead (at the very start of your program).

I tried `export QT_QPA_PLATFORM=wayland` and then execute the program (still in terminal), now it cannot run and shows 2 more warnings (the Gnome warning still there):
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
libpng warning: iCCP: known incorrect sRGB profile
./Wordless: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags
```

**Comment by rokm** [comment]
> > > I'm not sure how to fixes the last 1 warning:
> > > `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.`
> > > But it seems that most functions are back to normal now, I'm OK with it. Thanks anyway!
> > 
> > 
> > I suppose a quick work-around might be to check if `XDG_SESSION_TYPE` environment variable contains `wayland`, and then set `QT_QPA_PLATFORM=wayland ` instead (at the very start of your program).
> 
> I tried `export QT_QPA_PLATFORM=wayland` and then execute the program (still in terminal), now it cannot run and shows 2 more warnings (the Gnome warning still there):
> 
> ```
> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> QSocketNotifier: Can only be used with threads started with QThread
> libpng warning: iCCP: known incorrect sRGB profile
> ./Wordless: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_proxy_marshal_flags
> ```

Are wayland shared libraries collected into the frozen application (e.g., `libwayland-client.so.0`)? If they are, the collected version might be too old and lack the `wl_proxy_marshal_flags` symbol. Try removing it (or maybe all `libwayland-*.so` shared libraries).

**Comment by rokm** [comment]
Although for what is worth, I seem to be getting `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.` when running unfrozen PyQt5 script in Wayland session in a Fedora 36 VM, so this one is likely not specific to PyInstaller and the woes of collected shared libraries.

**Comment by rokm** [comment]
> Although for what is worth, I seem to be getting `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.` when running unfrozen PyQt5 script in Wayland session in a Fedora 36 VM, so this one is likely not specific to PyInstaller and the woes of collected shared libraries.

So by default, the application runs under XWayland, unless you specifically try to force it to run under Wayland with `QT_QPA_PLATFORM`, but then you'll probably need to sort out the bundled wayland shared libraries.

EDIT: and when forcing Wayland mode, even unfrozen script will generate a `QSocketNotifier: Can only be used with threads started with QThread` warning.

**Comment by BLKSerene** [comment]
> > Although for what is worth, I seem to be getting `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.` when running unfrozen PyQt5 script in Wayland session in a Fedora 36 VM, so this one is likely not specific to PyInstaller and the woes of collected shared libraries.
> 
> So by default, the application runs under XWayland, unless you specifically try to force it to run under Wayland with `QT_QPA_PLATFORM`, but then you'll probably need to sort out the bundled wayland shared libraries.
> 
> EDIT: and when forcing Wayland mode, even unfrozen script will generate a `QSocketNotifier: Can only be used with threads started with QThread` warning.

The app could run after removing `libwayland-client.so.0`, but some warning/errors change:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
QSocketNotifier: Can only be used with threads started with QThread
This plugin does not support setting window opacity
This plugin does not support setting window opacity
This plugin does not support setting window opacity
This plugin does not support setting window opacity
This plugin does not support setting window opacity
...The above line repeated many times...
```
Now when a new dialog is opened, the main window/background does not fade out (I mean, blurred?).
Try removing all other `libwayland-*.so` files: `libwayland-cursor.so.0`, `libwayland-egl.so.1`, `libwayland-server.so.0`, the same.

**Comment by rokm** [comment]
That looks like limitation of Qt+Wayland to me. 

Modifying your original example:
```python
import sys

from PyQt5.QtWidgets import QApplication, QMainWindow

class Test(QMainWindow):
    pass

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.processEvents()

    test = Test()
    test.showMaximized()
    test.setWindowOpacity(0.75)  # generates "This plugins does not support setting window opacity" under Wayland

    sys.exit(app.exec_())
```

and running it unfrozen generates the same "This plugin does not support setting window opacity" warning when Wayland is forced via `QT_QPA_PLATFORM`, and the window remains fully opaque. In contrast, transparency is set when XWayland is used.

Perhaps this is a limitation of Wayland compositor under GNOME, which is why Qt disables it by default (and hence the original `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.` message).

**Comment by BLKSerene** [comment]
> Perhaps this is a limitation of Wayland compositor under GNOME, which is why Qt disables it by default (and hence the original `Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.` message).

Thanks for the analysis, really helps a lot!
