### ISSUE TITLE
web3 + pyinstaller

### ISSUE THREAD

**Issue by marktohark** [pyinstaller/pyinstaller#7507]
#6442

I have the same issue.
but my os is windows.
app execute well in my computer.
but app execute in another computer, this issue happen.

python = 3.9 
pyinstaller = 5.8.0
web3.py = 6.0
OS: windows 10

have anyone solve it!?

**Comment by bwoodsend** [comment]
[Sigh]. Minimal reproducer example? Runtime error message? Without both of these, I can only assume that your code does something nonportable and this has nothing to do with PyInstaller.

**Comment by marktohark** [comment]
```python
import web3
from web3 import Web3
try:
    w3 = Web3(web3.HTTPProvider("https://cloudflare-eth.com"))
    if not w3.is_connected():
        print("connect failed")
        return

except Exception as e:
    logging.error("connect eth node failed: {}".format(e))
    print("connect eth node failed: {}".format(e))
```

i don't catch any exception.
it only print "connect failed".
it's weird.
if i don't package by pyinstaller, it will work well.
but it package it, it always show "connect failed".
also packaged app running on my computer is normal, but it running on another computer(A computer) will get "connect failed".
both computer is win10.
if i install python on A computer, and code example, it work well.
i am very confused.
i had watch this issue↓
https://github.com/ethereum/web3.py/issues/2268

**Comment by marktohark** [comment]
I solve it on windows.
it is about windows proxy setting.
