### ISSUE TITLE
hookspath in spec file not used by pyinstaller 5.9.0

### ISSUE THREAD

**Issue by HROMANO** [pyinstaller/pyinstaller#7513]
Platform : windows 10

Python 3.10.10 from:
- MSYS2 UCRT64.
- Official python.org windows installer.

PyInstaller 5.9.0 in a clean venv and using a SPEC file (`application.spec`).

Analysis object of `application.spec` includes a `"hooks"` directory in the `hookspath`list (nothing special in the other parts, apart from a `data_files` list): 

```
a = Analysis(
    ["application.py"],
    pathex=[],
    binaries=[],
    datas=data_files,
    hiddenimports=[],
    hookspath=["hooks"],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
```

`"hook"` directory includes hooks for `picos` (`hook-picos.py`) and `pyparsing` (`hook-pyparsing.py`) that don't exist elsewhere in pyinstaller directories.

`pyinstaller --clean application.spec` does not use these hooks from the directory pointed by `hookspath`.

The same SPEC file works if I downgrade pyinstaller to 5.8.0 in both MSYS2 or official python venv.

Could be related to 556cd59e66a8b034d8061267ef9b5dea05526821 as it works again when I comment line 112 of [PyInstaller/building/build_main.py](https://github.com/pyinstaller/pyinstaller/commit/556cd59e66a8b034d8061267ef9b5dea05526821#diff-c3791a9ec34b415496a4346760cc90d720f388c9cfb09d4c566395aaf19deac5)

```
entry_points = sorted(entry_points, key=lambda x: x.module_name == "_pyinstaller_hooks_contrib.hooks")
```

**Comment by rokm** [comment]
https://github.com/pyinstaller/pyinstaller/commit/556cd59e66a8b034d8061267ef9b5dea05526821 changes the order of entry-point-discovered hook directories, but the `hookspath` argument to `Analysis` should be prepended to those:
https://github.com/pyinstaller/pyinstaller/blob/7230e8bbda4a35f8afee41ac77dae6ed2f1e1348/PyInstaller/building/build_main.py#L374-L381

Can you add a `print(self.hookspath)` after this block in both 5.8 and 5.9 to see if the output is different?

That said, I cannot seem to reproduce this (python.org python 3.10.8).

**Comment by bwoodsend** [comment]
> pyinstaller --clean application.spec does not use these hooks from the directory pointed by hookspath.

Just to confirm, PyInstaller finds no hooks for picos and pyparsing? Not PyInstaller finds some hooks for them from somewhere else?

**Comment by HROMANO** [comment]
Today I can't reproduce the problem that was 100% reproducible yesterday, grrr. Maybe a reboot inbetween?

I close the issue, thank you for your help and sorry for the noise.
