### ISSUE TITLE
Can support for conda environments be added?

### ISSUE THREAD

**Issue by z4668640** [pyinstaller/pyinstaller#7514]
As we all know, pyinstaller can quickly package python programs into exe-like executable files. However, in different environments, the size of the same code package is inconsistent. I wrote a simple program that only uses the read_csv function of the pandas package and PySide6. The file size of the program packaged in the conda virtual environment is 278m, and the file packaged in pipenv will be smaller. When I use VMware Workstation to create After installing a brand new windows 11 environment and then packaging, the packaged file size is only 40m.
    I searched the Internet and found that this is a problem that has existed for a long time. Everyone’s program will encounter this situation when packaging: pyinstaller can easily package all the packages in the entire environment when packaging conda. This is very inconvenient work for our users, so could you please improve the work in this area? Many thanks.

**Comment by rokm** [comment]
Given the amount of resources and man-power we have, we do not plan to go out of our way to support conda.

**Comment by bwoodsend** [comment]
Ask yourself why a virtual conda environment containing only pandas and PySide6 contains more than 278MB of stuff for PyInstaller to collect. There's no way PyInstaller could magically undo the mess of debug files that conda ships and the dependence on MKL that conda adds to numpy.

**Comment by z4668640** [comment]
> Ask yourself why a virtual conda environment containing only pandas and PySide6 contains more than 278MB of stuff for PyInstaller to collect. There's no way PyInstaller could magically undo the mess of debug files that conda ships and the dependence on MKL that conda adds to numpy.

Thanks, this is very helpful. I will try more. Generally, what method do you use to obtain a clean environment to package the program?

**Comment by bwoodsend** [comment]
Old-school venv is my favorite. Other people will most likely steer you towards virtualenv or pip-env which have *more features* but no extra features that I've ever felt I needed before.

```bash
python -m venv .env
.\env\Scripts\activate.bat
pip install pyinstaller pandas PySide6
pyinstaller your-code.py
```
