### ISSUE TITLE
Adding package paths

### ISSUE THREAD

**Issue by dibrinsofor** [pyinstaller/pyinstaller#7527]
## Description of the issue
I am able to successfully freeze the app but one of the packages I use seems to be using a sys call. I have tried to include the path  from my virtual environment but the issue persists. How can I handle this case?

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.9.0```
* Version of Python: 3.9.4
* Platform: Windows (language settings)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? Yes. It works without pyinstaller

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [x] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
from tld import get_fld

url = "www.google.com/dibrineedshelp"
fld = get_fld(url, fix_protocol=True)
print(fld)

```

### Stacktrace / full error message

```
127.0.0.1 - - [28/Mar/2023 16:56:47] "POST /?pin=788-436-924&btn=Confirm+Pin HTTP/1.1" 500 -
Traceback (most recent call last):
  File "tld\utils.py", line 206, in get_tld_names
  File "codecs.py", line 905, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dibri Nsofor\\Desktop\\projs\\emailTracker\\dist\\app\\tld\\res\\effective_tld_names.dat.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "tld\base.py", line 101, in update_tld_names
  File "codecs.py", line 905, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Dibri Nsofor\\Desktop\\projs\\emailTracker\\dist\\app\\tld\\res\\effective_tld_names.dat.txt'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "flask\app.py", line 2548, in __call__
  File "flask\app.py", line 2528, in wsgi_app
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "app.py", line 46, in index
  File "imapencoding.py", line 214, in get_mail
  File "imapencoding.py", line 328, in process_mail
  File "tld\utils.py", line 438, in get_fld
  File "tld\utils.py", line 304, in process_url
  File "tld\utils.py", line 162, in get_tld_names
  File "tld\utils.py", line 234, in get_tld_names
  File "tld\base.py", line 116, in update_tld_names
tld.exceptions.TldIOError: [Errno 2] No such file or directory: 'C:\\Users\\Dibri Nsofor\\Desktop\\projs\\emailTracker\\dist\\app\\tld\\res\\effective_tld_names.dat.txt'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by dibrinsofor** [comment]
is there a discord channel or slack I can check-in with?

**Comment by rokm** [comment]
Looks like the `tld` package has a data file, which you need to collect by adding `--collect-data tld` to your PyInstaller command.

**Comment by dibrinsofor** [comment]
can we include an example of this in the [When things go wrong](https://pyinstaller.org/en/v4.2/when-things-go-wrong.html) section of the docs?

**Comment by bwoodsend** [comment]
It'll go in in #5117 eventually...

**Comment by dibrinsofor** [comment]
can I place an empty directory in the build folder? or how can I specify no source with  the `--add-data  "source;dest"` flag.

**Comment by rokm** [comment]
> can I place an empty directory in the build folder? or how can I specify no source with the `--add-data "source;dest"` flag.

You cannot add empty directories to the frozen application.
