### ISSUE TITLE
.exe build doesn't import pyodbc library

### ISSUE THREAD

**Issue by hoangde2811** [pyinstaller/pyinstaller#7528]
Dear developer!!
I use pyinstaller to build my project to .EXE to run on windows operating system but it gives me an error that cannot import the pyodbc library but I have already installed that library, I have attached the image below. Please help me to get the project to work. 
Sincerely thank you.
![image](https://user-images.githubusercontent.com/87251371/228997356-442f9363-fe3d-4213-a36c-7569a7da2b20.png)
![image](https://user-images.githubusercontent.com/87251371/228997872-90f17e15-5f9f-4021-b5d0-fc5e00f21a1b.png)

**Comment by rokm** [comment]
PyInstaller has no way of knowing that your `create_engine()` call implies that `pyodbc` needs to be collected - the import analysis works only on direct module imports. So you need to ensure it is collected by adding it to hidden imports. 

Use either [`--hidden-import pyodbc`](https://pyinstaller.org/en/stable/usage.html#cmdoption-hidden-import) or even [`--collect-submodules pyodbc`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-submodules) to do so.
