### ISSUE TITLE
Clearer documentation on plashscreen text color

### ISSUE THREAD

**Issue by nup002** [pyinstaller/pyinstaller#7529]
**Is your feature request related to a problem? Please describe.**
I cannot figure out how to set a custom RGB color for splashcreen color. Only the name-based colors like "white", "black", etc. works. Trying to set the color as an RGB tuple causes the splashscreen to fail to load. 

**Describe the solution you'd like**
I would like an example on how to set a custom RGB splashscreen color in the documentation: https://pyinstaller.org/en/stable/spec-files.html#PyInstaller.building.splash.Splash.__init__

**Comment by rokm** [comment]
Are html color codes (e.g., `#16a085`) not working?

**Comment by nup002** [comment]
Yes, that does seem to work. I could have sworn I tried that already with no luck. Can we still make the documentation clearer on this point? Took me some time to understand what "RGB HTML notation" meant.

**Comment by rokm** [comment]
Yeah, fair point. If nothing else, html codes should be used instead of `rgb()` tuples in the text when talking about magenta on Windows to reduce amount of confusion.

**Comment by rokm** [comment]
@nup002 do you think changes in #7530 are sufficient? You can see the pre-rendered manual here: https://pyinstaller--7530.org.readthedocs.build/en/7530/spec-files.html

**Comment by nup002** [comment]
I suggest putting text such as `#40e0d0` and `turquoise` in quotes to avoid confusion for beginners in Python who might put ``text_color: turquoise`` instead of the correct ``text_color: "turquoise"`` in the spec-file.
