### ISSUE TITLE
Python37 error loading dll file

### ISSUE THREAD

**Issue by RJSOG** [pyinstaller/pyinstaller#7534]
## Description of the issue

After building a python script using pyinstaller, i tried to run it on a Windows Server 2012 R2 which gave me the following error:
 **_Error loading Python DLL `C:\Users\test\AppData\Local\Temp\_MEI4545\python37.dll` LoadLibrary: Specified module can't be found_** 

### Context information (for bug reports)
* Output of `pyinstaller --version`: ```5.9.0```
* Version of Python: ```3.7 32bits```
* Build Platform: ```Windows 10```
* Run Platform: ```Windows 2012 R2```
* How you installed Python: Python Executable 3.7
* Build Command: ```pyinstaller.exe --uac-admin --add-data *conf* --add-data *icon* --add-data *png* --add-binary *exe32* --add-binary *exe64* --paths *pythonDir* --noconsole --icon *ocd.ico* --onefile *script*```
* No error when running the build command.
* The binairie is working fine on Windows 10.

**Comment by rokm** [comment]
Does the built executable work on other Windows versions, e.g., on Windows 10?

**Comment by bwoodsend** [comment]
Running on platform that's older than the one you built on is asking for trouble.

**Comment by RJSOG** [comment]
> Does the built executable work on other Windows versions, e.g., on Windows 10?

Yes as i said, it's working fine on Windows 10 but not on old platform...

**Comment by RJSOG** [comment]
> Running on platform that's older than the one you built on is asking for trouble.

So if i try to build it on a old platform, you think that's will fix the issue ?

**Comment by rokm** [comment]
> > Does the built executable work on other Windows versions, e.g., on Windows 10?
> 
> Yes as i said, it's working fine on Windows 10 but not on old platform...

Yeah, sorry, I missed that part in your original report.

> So if i try to build it on a old platform, you think that's will fix the issue ?

Building on the older platform should ensure that all DLLs that are collected from the system are in fact compatible with that platform. 

In the case of `python37.dll`, the only problematic dependency that I can think of might be `vcruntime140.dll`. After you build your program, can you check the `build/<name>` directory, and open a file `Analysis-00.toc` with text editor. Then find the entry for `vcruntime140.dll` and see where it was collected from - was it from the python's installation (the same directory as `python37.dll`) or from somewhere else?

**Comment by RJSOG** [comment]
> 
The file `Analysis-00.toc` give me the following result for `vcruntime140.dll` :
`VCRUNTIME140.dll',
   'c:\\users\\my_user\\appdata\\local\\programs\\python\\python37-32\\VCRUNTIME140.dll',
   'BINARY')`
 which is my current python installation folder.

**Comment by rokm** [comment]
> The file `Analysis-00.toc` give me the following result for `vcruntime140.dll` : `VCRUNTIME140.dll', 'c:\\users\\my_user\\appdata\\local\\programs\\python\\python37-32\\VCRUNTIME140.dll', 'BINARY')` which is my current python installation folder.

That's not the problem, then...

Can you create a onedir build instead of onefile one, and try running that on the target system?

**Comment by RJSOG** [comment]
I tried with the `onedir` build on a Windows 2008 R2 machine, the dll still can't be loaded...

**Comment by rokm** [comment]
> I tried with the `onedir` build on a Windows 2008 R2 machine, the dll still can't be loaded...

And if you check the onedir build (after copying to the target machine), do you see `python37.dll` and `vcruntime140.dll` in there? If you open `python37.dll` with Dependency Walker (on the target machine), does it resolve all dependencies or not?

**Comment by RJSOG** [comment]
`python37.dll` and `vcruntime140.dll` are present in the onedir build.
When loading the `python37.dll` on Dependency Walker, those issues appears :
![image](https://user-images.githubusercontent.com/44468960/230109380-45234675-9429-4edc-9d7b-360a967b85bb.png)

**Comment by rokm** [comment]
Those `api-ms-win-*` DLLs are usually resolved at runtime, and should not be problem (at least on recent Windows versions; but if executable works on 2008 R2 where you built it, it shouldn't be a problem on 2012, I think).

Can you take a screenshot that shows both top level entry (`python37.dll`), and `vcruntime140.dll` under it?

**Comment by rokm** [comment]
If you go to python.org download page and download the *embeddable zip file* of same python 3.7.x 32-bit that you had installed on your built system, and unpack and try to run it on your 2012 system, does the embeddable/portable python run or not?

If it runs, what happens if you take `vcruntime140.dll` and `python37.dll` from embeddable python and put them in your onedir application - does it start working?

**Comment by RJSOG** [comment]
> 

The executable is not working on **Windows 2008 R2** as well, and i am building the package on **Windows 10**.

For `python37.dll`:

![2023-04-05_17h33_47](https://user-images.githubusercontent.com/44468960/230130959-5b7d9a3f-4f5f-4910-a020-09b445b4798f.png)

For `vcruntime140.dll`:

![2023-04-05_17h34_08](https://user-images.githubusercontent.com/44468960/230131062-19e85b30-b32b-4d14-9093-a9d160213507.png)

**Comment by RJSOG** [comment]
> If you go to python.org download page and download the _embeddable zip file_ of same python 3.7.x 32-bit that you had installed on your built system, and unpack and try to run it on your 2012 system, does the embeddable/portable python run or not?
> 
> If it runs, what happens if you take `vcruntime140.dll` and `python37.dll` from embeddable python and put them in your onedir application - does it start working?

When trying to run embed python on the `Windows 2012 R2`:

![image](https://user-images.githubusercontent.com/44468960/230133887-2553bbf1-b8aa-436a-8a7a-8d67e299074a.png)

**Comment by rokm** [comment]
So I guess the last thing to test is if you use python 3.7 installer on Windows 2012 R2 - does the python run or not? Because if it does not, there's no reason to expect that a PyInstaller-frozen application built with that python version will run, either - whatever the cause for incompatibility is.

**Comment by RJSOG** [comment]
Using the Python executable installer works perfectly fine...
So what could be the issue ? 
![image](https://user-images.githubusercontent.com/44468960/230413655-bf549bae-0d03-4195-8ce3-bd8db73221f9.png)

**Comment by rokm** [comment]
> Using the Python executable installer works perfectly fine... So what could be the issue ? ![image](https://user-images.githubusercontent.com/44468960/230413655-bf549bae-0d03-4195-8ce3-bd8db73221f9.png)

That's 64-bit python, though, is it not?

**Comment by RJSOG** [comment]
Yes it is i will try with a 32-bit version

**Comment by RJSOG** [comment]
Python 3.7 32bit is working as well.
![image](https://user-images.githubusercontent.com/44468960/230607295-7fadec0b-f0c8-465b-80a5-af8bc4ac1a00.png)

**Comment by rokm** [comment]
Hmm... and if you copy `python37.dll` and `vcruntime140.dll` from this installation to the onedir application?

**Comment by RJSOG** [comment]
If i manually copy the `python37.dll` and `vcruntime140.dll` to the onedir application it's working.
But i can't work with a onedir application for production purpose..

**Comment by rokm** [comment]
In that case, if you compare the `python37.dll` and `vcruntime140.dll` on your original build system (assuming it's also using python 3.7.0), in the original onedir application, and on your target system (or in working onedir application) - are they the same (e.g., if you compute their hashes)?

On a related note, are you maybe using upx for your build and that causes difference in DLLs?

**Comment by RJSOG** [comment]
The hash for both `python37.dll` and `vcruntime140.dll` are exactly the same on the onedir application and my target system.

I am not using upx for building the script.

**Comment by RJSOG** [comment]
I tried to rebuild using the onefile command still got the same issues...

![image](https://user-images.githubusercontent.com/44468960/230620959-7ed49ae3-086a-4922-85b1-5ae88faa72ea.png)

**Comment by rokm** [comment]
> The hash for both `python37.dll` and `vcruntime140.dll` are exactly the same on the onedir application and my target system.

You mean there is no difference in hashes between the original non-working onedir application and the working onedir application (where you copied the DLLs)? I find that hard to believe - if that were the case, copying the DLLs would not have done anything...

**Comment by rokm** [comment]
The second error window implies that this is a problem with missing CRT DLLs (and AFAIK, these are usually sorted out by Windows updates). But that would make sense only if your build system is using some version of python 3.7, higher than 3.7.0 that you demonstrated to work.

That's why I'm trying to focus on onedir case first, to figure out what the difference between DLLs is and what is causing it...

**Comment by RJSOG** [comment]
> > The hash for both `python37.dll` and `vcruntime140.dll` are exactly the same on the onedir application and my target system.
> 
> You mean there is no difference in hashes between the original non-working onedir application and the working onedir application (where you copied the DLLs)? I find that hard to believe - if that were the case, copying the DLLs would not have done anything...

I don't know why but it was working when i was replacing the dll manually, it's not the case anymore.

**Comment by rokm** [comment]
I'm out of ideas, then. Perhaps try to build your application with python that you installed on the old Windows system now, and see if that works.
