### ISSUE TITLE
Recursion loading hook-pkg_resources.py - Pytorch 2.0.0 & Torchvision 0.15.1

### ISSUE THREAD

**Issue by RC300** [pyinstaller/pyinstaller#7537]
Run pip3 install pyinstaller==5.9.0 numpy==1.24.2 opencv-python==4.7.0.72 pillow==9.5.0 torch==2.0.0 torchvision==0.15.1
Collecting pyinstaller==5.9.0
  Downloading pyinstaller-5.9.0-py3-none-win_amd64.whl (1.3 MB)
     ---------------------------------------- 1.3/1.3 MB 19.9 MB/s eta 0:00:00
Collecting numpy==1.24.2
  Downloading numpy-1.24.2-cp311-cp311-win_amd64.whl (14.8 MB)
     --------------------------------------- 14.8/14.8 MB 54.7 MB/s eta 0:00:00
Collecting opencv-python==4.7.0.72
  Downloading opencv_python-4.7.0.72-cp37-abi3-win_amd64.whl (38.2 MB)
     --------------------------------------- 38.2/38.2 MB 24.2 MB/s eta 0:00:00
Collecting pillow==9.5.0
  Downloading Pillow-9.5.0-cp311-cp311-win_amd64.whl (2.5 MB)
     ---------------------------------------- 2.5/2.5 MB 32.1 MB/s eta 0:00:00
Collecting torch==2.0.0
  Downloading torch-2.0.0-cp311-cp311-win_amd64.whl (172.3 MB)
     -------------------------------------- 172.3/172.3 MB 5.0 MB/s eta 0:00:00
Collecting torchvision==0.15.1
  Downloading torchvision-0.15.1-cp311-cp311-win_amd64.whl (1.2 MB)
     ---------------------------------------- 1.2/1.2 MB 37.0 MB/s eta 0:00:00
Requirement already satisfied: setuptools>=42.0.0 in c:\hostedtoolcache\windows\python\3.11.2\x64\lib\site-packages (from pyinstaller==5.9.0) (65.5.0)
Collecting altgraph
  Downloading altgraph-0.17.3-py2.py3-none-any.whl (21 kB)
Collecting pyinstaller-hooks-contrib>=2021.4
  Downloading pyinstaller_hooks_contrib-2023.1-py2.py3-none-any.whl (256 kB)
     ------------------------------------- 256.8/256.8 kB 16.4 MB/s eta 0:00:00
Collecting pefile>=20[22](https://github.com/RC300/B/actions/runs/4608171850/jobs/8143592934#step:4:23).5.30
  Downloading pefile-20[23](https://github.com/RC300/B/actions/runs/4608171850/jobs/8143592934#step:4:24).2.7-py3-none-any.whl (71 kB)
     ---------------------------------------- 71.8/71.8 kB 3.8 MB/s eta 0:00:00
Collecting pywin32-ctypes>=0.2.0
  Downloading pywin32_ctypes-0.2.0-py2.py3-none-any.whl (28 kB)
Collecting filelock
  Downloading filelock-3.10.7-py3-none-any.whl (10 kB)
Collecting typing-extensions
  Downloading typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting sympy
  Downloading sympy-1.11.1-py3-none-any.whl (6.5 MB)
     ---------------------------------------- 6.5/6.5 MB 59.3 MB/s eta 0:00:00
Collecting networkx
  Downloading networkx-3.0-py3-none-any.whl (2.0 MB)
     ---------------------------------------- 2.0/2.0 MB 32.3 MB/s eta 0:00:00
Collecting jinja2
  Downloading Jinja2-3.1.2-py3-none-any.whl (133 kB)
     -------------------------------------- 133.1/133.1 kB 7.7 MB/s eta 0:00:00
Collecting requests
  Downloading requests-2.28.2-py3-none-any.whl (62 kB)
     ---------------------------------------- 62.8/62.8 kB 1.1 MB/s eta 0:00:00
Collecting MarkupSafe>=2.0
  Downloading MarkupSafe-2.1.2-cp311-cp311-win_amd64.whl (16 kB)
Collecting charset-normalizer<4,>=2
  Downloading charset_normalizer-3.1.0-cp311-cp311-win_amd64.whl (96 kB)
     ---------------------------------------- 96.7/96.7 kB 5.4 MB/s eta 0:00:00
Collecting idna<4,>=2.5
  Downloading idna-3.4-py3-none-any.whl (61 kB)
     ---------------------------------------- 61.5/61.5 kB 3.4 MB/s eta 0:00:00
Collecting urllib3<1.27,>=1.21.1
  Downloading urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
     -------------------------------------- 140.9/140.9 kB 8.7 MB/s eta 0:00:00
Collecting certifi>=2017.4.17
  Downloading certifi-2022.12.7-py3-none-any.whl (155 kB)
     -------------------------------------- 155.3/155.3 kB 9.1 MB/s eta 0:00:00
Collecting mpmath>=0.19
  Downloading mpmath-1.3.0-py3-none-any.whl (536 kB)
     ------------------------------------- 536.2/536.2 kB 17.0 MB/s eta 0:00:00
Installing collected packages: pywin32-ctypes, mpmath, altgraph, urllib3, typing-extensions, sympy, pyinstaller-hooks-contrib, pillow, pefile, numpy, networkx, MarkupSafe, idna, filelock, charset-normalizer, certifi, requests, pyinstaller, opencv-python, jinja2, torch, torchvision
Successfully installed MarkupSafe-2.1.2 altgraph-0.17.3 certifi-2022.12.7 charset-normalizer-3.1.0 filelock-3.10.7 idna-3.4 jinja2-3.1.2 mpmath-1.3.0 networkx-3.0 numpy-1.[24](https://github.com/RC300/B/actions/runs/4608171850/jobs/8143592934#step:4:25).2 opencv-python-4.7.0.72 pefile-2023.2.7 pillow-9.5.0 pyinstaller-5.9.0 pyinstaller-hooks-contrib-2023.1 pywin32-ctypes-0.2.0 requests-2.28.2 sympy-1.11.1 torch-2.0.0 torchvision-0.15.1 typing-extensions-4.5.0 urllib3-1.26.15
4381 INFO: PyInstaller: 5.9.0
4381 INFO: Python: 3.11.2
4397 INFO: Platform: Windows-10-10.0.20348-SP0
4397 INFO: wrote D:\a\B\B\A.spec
4397 INFO: UPX is not available.
4397 INFO: Extending PYTHONPATH with paths
['D:\\a\\B\\B']
4867 INFO: checking Analysis
4867 INFO: Building Analysis because Analysis-00.toc is non existent
4867 INFO: Initializing module dependency graph...
4867 INFO: Caching module graph hooks...
4882 INFO: Analyzing base_library.zip ...
7008 INFO: Loading module hook 'hook-encodings.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...
8119 INFO: Loading module hook 'hook-heapq.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...
11308 INFO: Loading module hook 'hook-pickle.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...
15624 INFO: Caching module dependency graph...
15780 INFO: running Analysis Analysis-00.toc
15796 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\hostedtoolcache\windows\Python\3.11.2\x64\python.exe
17726 INFO: Analyzing D:\a\B\B\A.py
17757 INFO: Loading module hook 'hook-cv2.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
17788 INFO: Loading module hook 'hook-numpy.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\numpy\\_pyinstaller'...
18733 INFO: Loading module hook 'hook-difflib.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...
19202 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...
19436 INFO: Loading module hook 'hook-xml.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...
20906 INFO: Loading module hook 'hook-platform.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...
21453 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...
231[25](https://github.com/RC300/B/actions/runs/4608171850/jobs/8143592934#step:4:26) INFO: Loading module hook 'hook-torch.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
2[38](https://github.com/RC300/B/actions/runs/4608171850/jobs/8143592934#step:4:39)13 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\hostedtoolcache\\windows\\Python\\3.11.2\\x64\\Lib\\site-packages\\PyInstaller\\hooks'...

=============================================================
A RecursionError (maximum recursion depth exceeded) occurred.
For working around please follow these instructions
=============================================================

1. In your program's .spec file add this line near the top::

     import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)

2. Build your program by running PyInstaller with the .spec file as
   argument::

     pyinstaller myprog.spec

3. If this fails, you most probably hit an endless recursion in
   PyInstaller. Please try to track this down has far as possible,
   create a minimal example so we can reproduce and open an issue at
   https://github.com/pyinstaller/pyinstaller/issues following the
   instructions in the issue template. Many thanks.

Explanation: Python's stack-limit is a safety-belt against endless recursion,
eating up memory. PyInstaller imports modules recursively. If the structure
how modules are imported within your program is awkward, this leads to the
nesting being too deep and hitting Python's stack-limit.

With the default recursion limit (1000), the recursion error occurs at about
115 nested imported, with limit 2000 at about 2[40](https://github.com/RC300/B/actions/runs/4608171850/jobs/8143592934#step:4:41), with limit [50](https://github.com/RC300/B/actions/runs/4608171850/jobs/8143592934#step:4:51)00 at about
6[60](https://github.com/RC300/B/actions/runs/4608171850/jobs/8143592934#step:4:61).

Error: Process completed with exit code 1.

**Comment by rokm** [comment]
Have you tried to increase the recursion limit as suggested in the error message?

If you did and it did not help, then we'll need a minimum example that triggers the error (e.g., a simple script with same imports as in your program).

**Comment by RC300** [comment]
It is pyinstaller's error when installing Pytorch 2.0.0 and Torchvision 0.15.1 specifically. Please check the compatibility with newest versions of Pytorch and fix it in the next update.
