### ISSUE TITLE
subdirectory modules are not being frozen

### ISSUE THREAD

**Issue by sharon92** [pyinstaller/pyinstaller#7539]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.9.0```
* Version of Python: 3.11.2
* Platform: Windows 10
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
The Program has the following structure:
(all init.py are with leading and trailing "__")
build\
dist\
src\
------functions\
---------- __init__.py (not empty)
---------- functions.py
------tasks\
---------- __init__.py (not empty)
----------Extractor.py
----------FloodPlainAnalysis.py
----------FloodPlainCorrection.py
----------FloodPlainCreator.py
----------FloodPlainDelineation.py
----------GridHecRas.py
----------KonsistenzPruefung.py
------__init__.py (empty)
------main.py 
FloodPlainCreator.spec

Freezing this package and running it results in Import Error (it runs normally in console if not frozen):

```
Traceback (most recent call last):
  File "C:\Users\S.Shaji\OneDrive - BKW\Entwicklung\FP-Creator\src\main.py", line 60, in <module>
    from tasks import (
ModuleNotFoundError: No module named 'tasks'
[10708] Failed to execute script 'main' due to unhandled exception!
```

Line 60 of main looks like this:

```
#import task functions
from tasks import (
    FloodPlainCreator,
    FloodPlainDelineation,
    FloodPlainAnalysis,
    FloodPlainCorrection,
    GridHecRas,
    Extractor,
    GangExtractor,
    hwgk,
    operateRaster)

#import functions
from functions import printdeltatime

```

Tasks--> __init__.py looks like this:
```
#Import all the Task modules here
from .FloodPlainCreator import FloodPlainCreator
from .FloodPlainDelineation import FloodPlainDelineation
from .FloodPlainAnalysis import FloodPlainAnalysis
from .FloodPlainCorrection import FloodPlainCorrection
from .GridHecRas import GridHecRas
from .Extractor import Extractor, GangExtractor
from .KonsistenzPruefung import hwgk, operateRaster
```

FloodPlainCreator.spec looks like this

```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None

import os,glob, sys
sys.modules['FixTk'] = None
cwd = os.getcwd()
#rootd = r"c:\Users\S.Shaji\OneDrive - BKW\Entwicklung\FP-Creator\env11"
rootd = r"c:\Entwicklung\FP-Creator\env311"
rasterio_imports_paths = glob.glob(os.path.join(rootd,r'Lib\site-packages\rasterio\*.py'))
rasterio_imports = []
for item in rasterio_imports_paths:
    current_module_filename = os.path.split(item)[-1]
    current_module_filename = 'rasterio.'+current_module_filename.replace('.py', '')
    rasterio_imports.append(current_module_filename)

bins = []
fiona_libs = os.path.join(rootd,r"Lib\site-packages\Fiona.libs")
for dll in os.listdir(fiona_libs):
    bins +=[(os.path.join(fiona_libs,dll),"Fiona.libs")]
	
a = Analysis(
    [r'src\main.py'],
    pathex=[],
    binaries=[
    (os.path.join(rootd,r"Lib\site-packages\MeshParser\mesh.dll"),'MeshParser'),
    (os.path.join(rootd,r"Lib\site-packages\osgeo\gdal304.dll"),'osgeo'),
    (os.path.join(rootd,r"Lib\site-packages\osgeo\geos_c.dll"),'osgeo'),
    (os.path.join(rootd,r"Lib\site-packages\osgeo\gdal_contour.exe"),'osgeo'),
    (os.path.join(rootd,r"Lib\site-packages\osgeo\gdal_rasterize.exe"),'osgeo'),
    (os.path.join(rootd,r"Lib\site-packages\osgeo\gdal_translate.exe"),'osgeo'),
    *bins
    ],
    datas=[],
    hiddenimports=[
    'pyarrow.vendored.version',
    'pyogrio._geometry','pyogrio._err',
    'fiona','fiona.schema','shapely','pyproj._datadir','pyproj._compat',
    *rasterio_imports
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[
	'IPython'
	],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='FloodPlainCreator',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='FloodPlainCreator',
)

**Comment by rokm** [comment]
If the directory containing your entry-point script (`main.py`) also contains an `__init__.py`, it is assumed to be a package, and *its parent directory* is added to the search path instead of the directory itself. So in your case, search path is extended with `top_level` instead of `top_level/src`.

Remove the `__init__.py` from `src`, since that's clearly not intended to be a package.

**Comment by sharon92** [comment]
> Remove the `__init__.py` from `src`, since that's clearly not intended to be a package.

removing ` __init__.py` breaks the build:
```
Traceback (most recent call last):
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\isolated\_parent.py", line 372, in call
    return isolated.call(function, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\isolated\_parent.py", line 293, in call
    ok, output = loads(b64decode(self._read_handle.readline()))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
EOFError: EOF read where object expected

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "c:\Entwicklung\FP-Creator\env311\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\__main__.py", line 194, in _console_script_run
    run()
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\building\build_main.py", line 981, in main
    build(specfile, distpath, workpath, clean_build)
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\building\build_main.py", line 903, in build
    exec(code, spec_namespace)
  File "FloodPlainCreator.spec", line 23, in <module>
    a = Analysis(
        ^^^^^^^^^
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\building\build_main.py", line 415, in __init__
    self.__postinit__()
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\building\datastruct.py", line 173, in __postinit__
    self.assemble()
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\building\build_main.py", line 699, in assemble
    isolated.call(find_binary_dependencies, list(self.binaries), self.binding_redirects, collected_packages)
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\isolated\_parent.py", line 371, in call
    with Python() as isolated:
  File "c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\isolated\_parent.py", line 247, in __exit__
    self._write_handle.flush()
OSError: [Errno 22] Invalid argument
```

**Comment by rokm** [comment]
> removing ` __init__.py` breaks the build:

That's a different problem, then, but at least it shows that your submodules are being processed now...

The binary scanning sub-process seems to crash while its importing modules; can you modify your PyInstaller copy (`c:\Entwicklung\FP-Creator\env311\Lib\site-packages\PyInstaller\building\build_main.py`) and add a `print(package)` before this line:
https://github.com/pyinstaller/pyinstaller/blob/fe73e51cebeb595b7923b3eda3da8ec14c08e7c3/PyInstaller/building/build_main.py#L177

This way, you will get the list of imported packages/modules leading to the subprocess crash. Please paste the whole list here (could be a module on its own that's problematic, or a sequence of module imports).

**Comment by sharon92** [comment]
Thank you! Yeah I already tried this before. But failed to notice that I didnt add `osgeo` to hidden imports. This time I noticed it because printing the package name stopped at osgeo.

Now it freezes and runs correctly!

Should I close the issue or delete it?

**Comment by rokm** [comment]
> Should I close the issue or delete it?

We prefer issues to be closed, in case someone else stumbles across a similar problem.
