### ISSUE TITLE
Django root directory discovery in PyInstaller 2.1

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#754]
**Original date**: 2013/08/25
**Original reporter**: *squishyent AND gmail DOT  COOM *

There is a bug in PyInstaller.hooks.hookutils.django_find_root_dir(), on line 273 of hookutils.py, which prevents PyInstaller from discovering the Django root directory.  The problem is the line:

if os.isdir(f):

which should be:

if os.isdir(os.path.join(manage_dir, f)):

This prevents the script from examining the folder which contains settings.py and urls.py.  I was getting the following warning:

WARNING: No django root directory could be found!

With the suggested update, the script correctly packages my program.

Thanks!

**Comment by matysek** [comment]
This bug report is too old.
