### ISSUE TITLE
about windows service program using pyinstaller

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#755]
**Original date**: 2013/08/25
**Original reporter**: *Jerry*

Hi:
platform: windows xp sp3
pyinstaller version: 2.0

command:pyinstaller.py -F mytestservice.py(python code for windows service), generate mytestservice.exe successfully, and installed as a windows service successfully also, but when try to start the windows service, error[1053] occurs.

I have no idea about this situation, is there something special to generate a windows service exe file, confused a lot.

Thanks a lot in advance, any suggestion?

**Comment by ypfboy** [comment]
Is it solved? I reported the same mistake
