### ISSUE TITLE
ffmpeg missing in Pydub-based exe for Windows

### ISSUE THREAD

**Issue by autopodfm** [pyinstaller/pyinstaller#7561]
So I'm using Pyinstaller to create an executable for a Pydub script.  It's part of a plug-in for Adobe.  It works perfectly on Mac for all my users.  However, for certain users on Windows, but not all, they get the following error:

``
Pydub\utils.py 170: Runtime Warning: Couldn't find ffmpeg or..
``

I think maybe it's for people who don't already have ffmpeg on their machine?  Is there a way to make sure it bundles correctly?

**Comment by bwoodsend** [comment]
Ugh, this isn't a support service...

PyInstaller isn't going to magically collect ffmpeg unless you tell it to. You'll need the [--add-binary](https://pyinstaller.org/en/stable/usage.html#cmdoption-add-binary) option.

**Comment by autopodfm** [comment]
I did use --add-binary and it didn't work still.

**Comment by rokm** [comment]
> I did use --add-binary and it didn't work still.

Then if you're 100% sure that you used `--add-binary` correctly and you have ffmpeg executable collected, you should check how `pydub` discovers it ([here](https://github.com/jiaaro/pydub/blob/master/pydub/utils.py#L148-L175)) and take steps to ensure it is discoverable within the frozen application's environment.
