### ISSUE TITLE
Another person's MacOS application won't open

### ISSUE THREAD

**Issue by kanewi11** [pyinstaller/pyinstaller#7573]
pyinstaller: 5.10.1
Python: 3.10.5

After I made `pyinstaller -F main.py`, my program works fine and opens. But after I upload the application to a file-sharing site and download it, it stops opening. And if I run it `Contents/MacOS/main` it will open.

I can attach all the files, the program is not a big 

Do you know what could be the problem?

**Comment by kanewi11** [comment]
I figured out what the problem is, when I download a file, the path to the base directory changes to `/private/var/folders/9n/...` I tried all variants of absolute paths, but nothing works (


HELP 😄

**Comment by rokm** [comment]
macOS translocates untrusted (unsigned) .app bundles to read-only directory in random path before running it.

So if this is a onefile .app bundle and you are trying to access a file that is in the .app bundle but not collected into executable's archive (and thus not unpacked to temporary directory indicated by `sys._MEIPASS`), you'll probably need to anchor your path to `sys.executable`.

**Comment by kanewi11** [comment]
> macOS translocates untrusted (unsigned) .app bundles to read-only directory in random path before running it.
> 
> So if this is a onefile .app bundle and you are trying to access a file that is in the .app bundle but not collected into executable's archive (and thus not unpacked to temporary directory indicated by `sys._MEIPASS`), you'll probably need to anchor your path to `sys.executable`.

I understood that the application is in the sandbox, roughly speaking. But I've tried every way.

- `sys._MEIPASS`
- `sys.executable`
- `sys.argv[0]`
- and others, none gave the right result. 

The only way is to work with the package content files (

**Comment by rokm** [comment]
What is it you are trying to do, though? Read a file?

**Comment by kanewi11** [comment]
> What is it you are trying to do, though? Read a file?

Yes I need to read the configuration file and from this configuration file see the name of the photo and output it in pqt6

**Comment by rokm** [comment]
Can you create a test pyqt6 application that displays `sys._MEIPASS`, `sys.executable` and `sys.argv[0]` and post the values here? 

I still think `sys.executable` should work as an anchor path for files that are part of .app bundle but are not part of onefile frozen application (and in onedir build, both `sys._MEIPASS` and parent of `sys.executable` should point to the same directory. Regardless of whether translocation kicks in or not.

**Comment by kanewi11** [comment]
`sys.executable` - /private/var/folders/.../d/PicOnScreen.app/Contents/MacOS/PicOnScreen

`sys._MEIPASS` - /var/folders/.../T/_MEIwu6I49

`sys.argv[0]` - /private/var/folders/.../d/PicOnScreen.app/Contents/MacOS/PicOnScreen

> Can you create a test pyqt6 application that displays `sys._MEIPASS`, `sys.executable` and `sys.argv[0]` and post the values here?
> 
> I still think `sys.executable` should work as an anchor path for files that are part of .app bundle but are not part of onefile frozen application (and in onedir build, both `sys._MEIPASS` and parent of `sys.executable` should point to the same directory. Regardless of whether translocation kicks in or not.

**Comment by kanewi11** [comment]
Is there any way around translocation? And there are cases when **`You have no rights to open the program`**.

**Comment by rokm** [comment]
These paths look as expected - the .app bundle is translocated to ` /private/var/folders/.../d`, so `sys.executable` and `sys.argv` point there. And since this is onefile build, it unpacks itself to the temporary directory pointed to by `sys._MEIPASS`.

So if your config file and image file are part of frozen application, they should be inside `sys._MEIPASS` (assuming you collected them into top-level directory), and you need to anchor your paths to `sys._MEIPASS`.

If they are not part of the frozen application but you added them to .app bundle yourself, then they should be translocated together with the .app bundle, so you can anchor to parent path of `sys.executable`.

**Comment by kanewi11** [comment]
> These paths look as expected - the .app bundle is translocated to ` /private/var/folders/.../d`, so `sys.executable` and `sys.argv` point there. And since this is onefile build, it unpacks itself to the temporary directory pointed to by `sys._MEIPASS`.
> 
> So if your config file and image file are part of frozen application, they should be inside `sys._MEIPASS` (assuming you collected them into top-level directory), and you need to anchor your paths to `sys._MEIPASS`.
> 
> If they are not part of the frozen application but you added them to .app bundle yourself, then they should be translocated together with the .app bundle, so you can anchor to parent path of `sys.executable`.

Well I +- did so, thank you!

**Comment by rokm** [comment]
> Is there any way around translocation? And there are cases when **`You have no rights to open the program`**.

It's an OS feature, so unless you (or your end-user) disable Gatekeeper on the target machine, or you sign your .app bundle with valid Apple developer certificate, then no. 

Not sure what `You have no rights to open the program` is about, but it could be about `com.apple.quarantine` attribute being set to the file downloaded from internet (which you can remove using `xattr -r -d com.apple.quarantine path/to/program.app`).

**Comment by kanewi11** [comment]
> > Is there any way around translocation? And there are cases when **`You have no rights to open the program`**.
> 
> It's an OS feature, so unless you (or your end-user) disable Gatekeeper on the target machine, or you sign your .app bundle with valid Apple developer certificate, then no.
> 
> Not sure what `You have no rights to open the program` is about, but it could be about `com.apple.quarantine` attribute being set to the file downloaded from internet (which you can remove using `xattr -r -d com.apple.quarantine path/to/program.app`).

You are the best 👍
