### ISSUE TITLE
multiprocessing shared_memory creating infinite process

### ISSUE THREAD

**Issue by dumoulina** [pyinstaller/pyinstaller#7580]
## Description of the issue
Looks like #4865 & #2322
The program keep launching processes wheras I only use multiprocessing.shared_memory.SharedMemory( ) command

### Context information (for bug reports)

* Output of `pyinstaller --version`: 5.10.1
* Version of Python: 3.10.6
* Platform: Ubuntu 22.04.2
* How you installed Python: default ubuntu
* Did you also try this on another platform? Does it work there?
no issue on windows with python 3.11 (didn't test with 3.10 but seems to be a non windows OS issue)

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file. (yes but can't read anything as too many process)

### A minimal example program which shows the error

```python
from multiprocessing import shared_memory

# the shm is in my situation is already created but for testing purpose I create one there
try:
    shm = shared_memory.SharedMemory("emg_input_game", create=True, size=4) # float size
except: # already exists
    shm = shared_memory.SharedMemory("emg_input_game", create=False)
```

### Stacktrace / full error message

```
Program -B -S -E -s -c fromp multiprocessing.ressource_tracker import main;main(12)
Program -B -S -E -s -c fromp multiprocessing.ressource_tracker import main;main(11)
Program -B -S -E -s -c fromp multiprocessing.ressource_tracker import main;main(12)
Program -B -S -E -s -c fromp multiprocessing.ressource_tracker import main;main(11)
...
```
`killall` command achieve sometimes to kill them all

**Comment by rokm** [comment]
If you want to use `multiprocessing` in PyInstaller-frozen application, you need to call `multiprocessing.freeze_support()` before using any `multiprocessing` functionality.

**Comment by dumoulina** [comment]
> If you want to use `multiprocessing` in PyInstaller-frozen application, you need to call `multiprocessing.freeze_support()` before using any `multiprocessing` functionality.

ok thanks, it should be added in the "When Things Go Wrong"
