### ISSUE TITLE
Pyinstaller doesn't work with latest Anaconda-Navigator

### ISSUE THREAD

**Issue by Clavicle773** [pyinstaller/pyinstaller#7583]
## Pyinstaller doesn't work with latest Anaconda-Navigator

I tried to develop an executable python script when I got the message in the "*Output..." section. The specific file that is recommended to be removed is part of the Anaconda Navigator and Conda, with both being up-to-date. 

If a user follows the recommendation to "conda remove pathlib" it will break Anaconda Navigator. The conda package plan if Pathlib is attempted to be uninstalled is shown below 

Please update Pyinstaller to work with Anaconda Navigator

### Context information (for bug reports)

* Output of `pyinstaller --version: The 'pathlib' package is an obsolete backport of a standard library package and is incompatible with PyInstaller. Please remove this package (located in C:\Users\gbeck\AppData\Local\anaconda3\lib\site-packages) using conda remove
then try again.
* Version of Python: Python 3.10.10 | packaged by Anaconda, Inc. | (main, Mar 21 2023, 18:39:17) [MSC v.1916 64 bit (AMD64)] on win32
* Platform:  Windows 10 Pro for Workstations Version 21H2
* How you installed Python:  conda
* Did you also try this on another platform? Does it work there?
No. 

* try the latest development version, using the following command:
```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Done: 
Output here: pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
Collecting https://github.com/pyinstaller/pyinstaller/archive/develop.zip
  Downloading https://github.com/pyinstaller/pyinstaller/archive/develop.zip
     / 4.6 MB 3.7 MB/s 0:00:01
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: pefile>=2022.5.30 in c:\users\gbeck\appdata\local\anaconda3\lib\site-packages (from pyinstaller==5.10.1) (2023.2.7)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in c:\users\gbeck\appdata\local\anaconda3\lib\site-packages (from pyinstaller==5.10.1) (2023.2)
Requirement already satisfied: pywin32-ctypes>=0.2.0 in c:\users\gbeck\appdata\local\anaconda3\lib\site-packages (from pyinstaller==5.10.1) (0.2.0)
Requirement already satisfied: setuptools>=42.0.0 in c:\users\gbeck\appdata\local\anaconda3\lib\site-packages (from pyinstaller==5.10.1) (65.6.3)
Requirement already satisfied: altgraph in c:\users\gbeck\appdata\local\anaconda3\lib\site-packages (from pyinstaller==5.10.1) (0.17.3)

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

## Package Plan ##

  environment location: C:\Users\gbeck\AppData\Local\anaconda3

  removed specs:
    - pathlib
 The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    python-lsp-server-1.7.2    |  py310haa95532_0         125 KB
    ------------------------------------------------------------
                                           Total:         125 KB
The following packages will be REMOVED:
**anaconda-navigator-2.4.0-py310haa95532_0** Anaconda Navigator
conda-repo-cli-1.0.41-py310haa95532_0
freetype-2.12.1-ha860e81_0
navigator-updater-0.3.0-py310haa95532_0
**pathlib-1.0.1-pyhd3eb1b0_1** Needed to run Anaconda Navigator
pillow-9.4.0-py310hd77b12b_0
pyjwt-2.4.0-py310haa95532_0
The following packages will be UPDATED:
python-lsp-server  1.7.1-py310haa95532_0 --> 1.7.2-py310haa95532_0

### Stacktrace / full error message
N/A

**Comment by rokm** [comment]
`pathlib` has been part of python stdlib since python 3.4, so there is no reason for Anaconda Navigator to depend on external (obsolete and unmaintained) [pathlib package](https://pypi.org/project/pathlib/). Open a bug with them.

The presence of the obsolete `pathlib` package may cause errors during PyInstaller analysis (#7406), and since the package is unnecessary, we black list it (along with some other now-obsolete backports of stdlib packages) here:
https://github.com/pyinstaller/pyinstaller/blob/b4d87c24f2447f1aa6b8a44f7fd01f197e81b331/PyInstaller/compat.py#L754-L764

Nothing prevents you from disabling that check in your copy of PyInstaller, if you absolutely need to have both anaconda navigator and pyinstaller installed in the same virtual environment.

**Comment by Clavicle773** [comment]
I created a fork with this commented out as a mitigation until the interoperability issues can be resolved [pyinstaller-Nissha](https://github.com/Dragon052000/pyinstaller-Nissha.git)

**Comment by bwoodsend** [comment]
Use a virtual environment. You should never install packages into Conda's main environment.
