### ISSUE TITLE
Error in executable of python program using ocrmypdf

### ISSUE THREAD

**Issue by koolkunz** [pyinstaller/pyinstaller#7585]
## Description of the issue
I am trying to create a pyinstaller exe of a python program using ocrmypdf but the resulting exe does not run properly and gives the error mentioned below.

pyinstaller commands I have tried:
`pyinstaller --clean sourcecode/sample.py --hidden-import ocrmypdf --hidden-import pikepdf --hidden-import importlib-resources --hidden-import pluggy --collect-all ocrmypdf --collect-all pikepdf --collect-all importlib-resources --collect-all pluggy --recursive-copy-metadata ocrmypdf --recursive-copy-metadata pikepdf --recursive-copy-metadata importlib-resources --recursive-copy-metadata pluggy`

`pyinstaller --clean sourcecode/sample.py --hidden-import ocrmypdf --hidden-import pikepdf --collect-all ocrmypdf --collect-all pikepdf`

* Output of `pyinstaller --version`: 5.10.1
* Version of Python: Python 3.8.15 - 64bit
* Platform: Windows
* How you installed Python: python.org/downloads

### A minimal example program which shows the error

```
import ocrmypdf

ocrmypdf.ocr('input.pdf', 'output.pdf', deskew=True)
```
NOTE: To run this program you need to have Ghostscript and Tesseract-OCR installed in the system with appropriate environment variables set (refer: https://ocrmypdf.readthedocs.io/en/latest/installation.html#installing-on-windows)

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "sample.py", line 3, in <module>
  File "ocrmypdf\api.py", line 338, in ocr
    plugin_manager = get_plugin_manager(plugins)
  File "ocrmypdf\_plugin_manager.py", line 104, in get_plugin_manager
    return OcrmypdfPluginManager(
  File "ocrmypdf\_plugin_manager.py", line 45, in __init__
    self.setup_plugins()
  File "ocrmypdf\_plugin_manager.py", line 69, in setup_plugins
    for module in sorted(
TypeError: '<' not supported between instances of 'FrozenImporter' and 'FileFinder'
[8900] Failed to execute script 'sample' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
```
pyinstaller --copy-metadata pikepdf --copy-metadata ocrmypdf --collect-submodules ocrmypdf sample.py
```
works for me.

**Comment by koolkunz** [comment]
> ```
> pyinstaller --copy-metadata pikepdf --copy-metadata ocrmypdf --collect-submodules ocrmypdf sample.py
> ```
> 
> works for me.

Is the produced exe running properly without any errors?

**Comment by bwoodsend** [comment]
Actually, on trying with a different PDF I see I also need `--collect-datas ocrmypdf.data`. But yes. It's working.
```bash
~ # ./dist/sample/sample 
Scanning contents: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 603.41page/s]
OCR:   0%|                                                                                                                                                                                                        | 0.0/1.0 [00:00<?, ?page/s][tesseract] lots of diacritics - possibly poor OCR
OCR: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.0/1.0 [00:05<00:00,  5.41s/page]
PDF/A conversion: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 16.74page/s]
Recompressing JPEGs: 0image [00:00, ?image/s]
Deflating JPEGs: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00, 80.59image/s]
JBIG2: 0item [00:00, ?item/s]
```

I doubt that this will ever be portable though. Unless you want to tell your users to install ghostscript separately, you'll have a hard time bundling it.

**Comment by koolkunz** [comment]
Do you mind sharing the .spec file generated for your build, i must be doing something wrong

And Regarding ghostscript and tesseract, I have found/built portable exe for it and I'll copy that folder over in the pyinstaller directory, and then add it to path using os.environ.

**Comment by bwoodsend** [comment]
```python
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import collect_submodules
from PyInstaller.utils.hooks import copy_metadata

datas = []
hiddenimports = []
datas += collect_data_files('ocrmypdf.data')
datas += copy_metadata('pikepdf')
datas += copy_metadata('ocrmypdf')
hiddenimports += collect_submodules('ocrmypdf')


block_cipher = None


a = Analysis(
    ['sample.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='sample',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='sample',
)
```

**Comment by koolkunz** [comment]
Also what version of python and pyinstaller are you using?

**Comment by bwoodsend** [comment]
Python 3.10.11.. PyInstaller 5.10.1.

**Comment by bwoodsend** [comment]
> TypeError: '<' not supported between instances of 'FrozenImporter' and 'FileFinder'

This is a naive bug in ocrmypdf trying to sort `MetaPathFinder()` subclasses instead of sorting by module name. I'd have though that you'd need to be collecting source code to encounter it though. Do you have .py files in your application?

**Comment by rokm** [comment]
> Do you have .py files in your application?

Considering all `--collect-all` options in the original PyInstaller command, I would imagine this is the case.

**Comment by koolkunz** [comment]
> > TypeError: '<' not supported between instances of 'FrozenImporter' and 'FileFinder'
> 
> This is a naive bug in ocrmypdf trying to sort `MetaPathFinder()` subclasses instead of sorting by module name. I'd have though that you'd need to be collecting source code to encounter it though. Do you have .py files in your application?

Yes, there are a lot of .py files in the various imported packages folders like ocrmypdf and pikepdf etc.

**Comment by rokm** [comment]
As Brénainn said, this is a bug in `ocrmypdf` - they [try to directly sort the list of `ModuleInfo` entries obtained by `pkgutil.iter_modules`](https://github.com/ocrmypdf/OCRmyPDF/blob/cb251a8d03c2f8329e773af87988164d700b48ce/src/ocrmypdf/_plugin_manager.py#L69-L71). This works as long as there's only one module with a given name available, but breaks if there are more, because then comparison between module finders is attempted.

In unfrozen version, there is only one module with a given name - the .py file (discovered by `FileFinder`).

In frozen application, there would normally also be only one module with a given name - the .pyc collected in PYZ archive and handled by our `FrozenImporter`.

However, because you used all those `--collect-all` options, the source .py files were also collected, so now each module is available twice - once from PYZ archive (`FrozenImporter`) and once from source .py file (discovered by `FileImporter`).

So you should remove the `--collect-all`  options; if you need to collect modules that are lazily imported (and thus missed by PyInstaller analysis), use `--collect-submodules`.

**Comment by koolkunz** [comment]
`pyinstaller --copy-metadata pikepdf --copy-metadata ocrmypdf --collect-submodules ocrmypdf --collect-datas ocrmypdf.data sample.py`

I used this and it is working fine, --collect-all was the culprit as you guys mentioned.
Thanks for your help!
