### ISSUE TITLE
PyInstaller fails on Windows and Linux with opentelemetry

### ISSUE THREAD

**Issue by EdLeafe** [pyinstaller/pyinstaller#7586]
## Description of the issue

We recently added the `opentelemetry` libraries to our application, which we then build with PyInstaller. While it's working on Mac, it's failing on Windows and Linux. I saw similar issues  (such as https://github.com/open-telemetry/opentelemetry-python/issues/2514) and added the `collect_submodules()` and `copy_metadata()` calls to the .spec file, but they didn't fix the problem nor change the output.

Trying to run the executable I see the error in the stacktrace section below.

Any idea how to get this to work?

### Context information (for bug reports)

* Output of `pyinstaller --version`: 
 
`5.10.1`

* Version of Python: 

`3.9.16`

* Platform: 

`Windows 10 Enterprise`

* How you installed Python: 

python.org download

* Did you also try this on another platform? Does it work there?

It works on MacOS, but also fails on Linux. 

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

No change

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

I created a minimal program that imports the opentelemetry modules as in our actual program:
```
from opentelemetery import propagate, trace

def main():
    print("testing")

if __name__ == "__main__":
    main()
```

I then built an .exe using our .spec file, changing the name to point to the test file:

```
# -*- mode: python -*-
block_cipher = None
import os
import sys

import grpc
from PyInstaller.utils.hooks import collect_submodules, copy_metadata

# work-around for https://github.com/pyinstaller/pyinstaller/issues/4064
# check distutils_path exists before changing the value
import distutils
distutils_path = getattr(distutils, 'distutils_path', None)
if distutils_path != None and distutils_path.endswith('__init__.py'):
    distutils.distutils_path = os.path.dirname(distutils_path)

sys.modules['FixTk'] = None
file_name = "main.dll" if os.name == "nt" else "main.so"

datas=[]
datas += copy_metadata("opentelemetry_api", recursive=True)
datas += copy_metadata("opentelemetry_sdk", recursive=True)
datas += copy_metadata("opentelemetry_exporter_otlp_proto_grpc", recursive=True)
hiddenimports = ['pkg_resources', 'opentelemetry_sdk']
hiddenimports.extend(collect_submodules("opentelemetry_sdk"))

a = Analysis(['main.py'],
             pathex=[os.path.abspath(SPECPATH), os.path.abspath(os.path.join(SPECPATH, '..'))],
             binaries=[],
             datas=datas,
             hiddenimports=hiddenimports,
             hookspath=[],
             hooksconfig={},
             runtime_hooks=[],
             excludes=['FixTk', 'tcl', 'tk', '_tkinter', 'tkinter', 'Tkinter'],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data,
             cipher=block_cipher)
exe = EXE(pyz,
          a.scripts,
          [],
          exclude_binaries=True,
          name='test',
          debug=True,
          bootloader_ignore_signals=False,
          strip=False,
          upx=False,
          console=True,
          disable_windowed_traceback=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas, 
               strip=False,
               upx=False,
               upx_exclude=[],
               name='test')
```

It build successfully, and I tried running it with: 

`./dist/test.exe`

and got the exact same error.

### Stacktrace / full error message

```
$ ./dist/ngc/ngc.exe registry chart list '*ed_test*'
Failed to load configured propagator: tracecontext
Traceback (most recent call last):
  File "opentelemetry\propagate\__init__.py", line 138, in <module>
  File "importlib_metadata\__init__.py", line 208, in load
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'opentelemetry.trace.propagation.tracecontext'
Traceback (most recent call last):
  File "ngc.py", line 12, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "ngccli\ngc.py", line 16, in <module>
    from ngccli import clicommand, environ
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "ngccli\clicommand.py", line 13, in <module>
    from ngccli.api.configuration import Configuration
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "ngccli\api\configuration.py", line 18, in <module>
    from ngccli.api.authentication import Authentication
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "ngccli\api\authentication.py", line 37, in <module>
    from ngccli.tracing import traced_request
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "ngccli\tracing.py", line 14, in <module>
    from opentelemetry import propagate, trace
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "opentelemetry\propagate\__init__.py", line 138, in <module>
  File "importlib_metadata\__init__.py", line 208, in load
  File "importlib\__init__.py", line 127, in import_module
ModuleNotFoundError: No module named 'opentelemetry.trace.propagation.tracecontext'
[23256] Failed to execute script 'ngc' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> ```
> hiddenimports = ['pkg_resources', 'opentelemetry_sdk']
> hiddenimports.extend(collect_submodules("opentelemetry_sdk"))
> ```

> ``` 
> ModuleNotFoundError: No module named 'opentelemetry.trace.propagation.tracecontext'
> ``` 

The package you should be collecting submodules from is called `opentelemetry`, not `opentelemetry_sdk`.

EDIT: wheras for `copy_metadata`, the dist names should be used - which you already do (i.e., `opentelemetry_api`, `opentelemetry_sdk`, `opentelemetry_exporter_otlp_proto_grpc`).

**Comment by EdLeafe** [comment]
Thanks - that fixed it, although I never would have guessed that, since there is no `opentelemetry` library.
