### ISSUE TITLE
Build the .pkg file without Xcode and verify it with the Transporter app. I find the "Resources folder" at "my.app/Contents/Resources/lib/PyQt5/Qt5/lib/QtBluetooth.framework"

### ISSUE THREAD

**Issue by bensonwang186** [pyinstaller/pyinstaller#7609]
Python：3.10.7
PyQt5：5.15.9
cx_Freeze：6.13.1

I write this macOS app with Python PyQt and build a “.pkg” file, without using Xcode, and use Transporter app to verify. I successfully build the “.pkg” file which can pass Transporter app’s verification. 

When I do the code signing with my.app, I get the error message
```
my.app: replacing existing signature
my.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: my.app/Contents/MacOS/lib/PyQt5/Qt5/qml/QtQml/Models.2
```
so I find the answer 
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-OSX-Code-Signing-Qt to solve this problem. 

Below is my command:

```
python Installer/mac/fix_app_qt_folder_names_for_codesign.py Installer/my.app

pkgbuild --install-location /Applications --component my.app my.pkg

productbuild --distribution dist.xml --package-path ./my.pkg ./my_final.pkg

productsign --sign "xxx" my.pkg my_signed.pkg
```

**my.app directory tree**

    my.app
    ├───Contents
        ├───_CodeSignature
        ├───embedded.provisionprofile
        ├───Frameworks
        ├───Info.plist
        ├───MacOS
        └───Resources
            ├───icon.icns
            └───lib
                └───PyQt5
                    └───Qt5
                        ├───qml
                        └───lib
                            ├───QtBluetooth.framework
                                   ├───Resources
                                   └───Versions
                            ├───QtCore.framework
                                   ├───Resources
                                   └───Versions
                             .....
                             .....

However, an error message appears when the “.pkg” file verified by Transporter App:

Error Message：ITMS-90260: Bad Bundle Executable - You must include a valid CFBundleExecutable key in the nested bundle [my.pkg/Payload/my.app/Contents/Resources/lib/PyQt5/Qt5/lib/QtBluetooth.framework] property list file. property list file.

I have some question:
1. how to solve this Error Message：ITMS-90260: Bad Bundle Executable?
2. I had build other project(python：3.6/pyqt：5.9.2), I don't have "Resources folder" at "my.app/Contents/Resources/lib/PyQt5/Qt5/lib/QtBluetooth.framework" and I can verified by Transporter App.
When I build this project(python：3.10.7/pyqt：5.15.9), I find the "Resources folder" at "my.app/Contents/Resources/lib/PyQt5/Qt5/lib/QtBluetooth.framework", Is it because of the "Resources folder" that there is a "Bad Bundle Executable" problem? How can I solve this problem?

**Comment by bwoodsend** [comment]
>  cx_Freeze：6.13.1

This is PyInstaller's issue tracker - not cx_freeze's.
