### ISSUE TITLE
Mac os x Icon not bouncing in dock when loading.

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#761]
**Original date**: 2013/09/05
**Original reporter**: *peder DOT jorgensen AND gmail DOT  COOM *

On mac osx, when a user clicks on a dock icon to launch an app the app icon starts bouncing to illustrate that it's loading, and it keeps on bouncing till it launches. 
This is not happening on an application frozen with the --onefile option.

**Comment by htgoebel** [comment]
This feature-request if five years old now. Nobody worked on is and nobody commented on this issue, so I'm closing it.
