### ISSUE TITLE
wx.Image().ConvertToBitmap() and Error Message

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#762]
**Original date**: 2013/09/06
**Original reporter**: *anonymous*

wx.Image()**.ConvertToBitmap()** dosen't work.

But the bigger issue is that the error message which are raised by the .exe close immediately after the error occures.
It makes it impossible to read the error message.

After several trys to add hooks and hidden-imports according to the error messages from the warn.txt, i gave it up and tried it with py2exe, which shows me the error message and i could solve the issue.

System: Windows 7 Ultimate 32-Bit
Pyinstaller 2.0

If i can't read the error message i can't solve the problem.
Please fix this as soon as possible :)

**Comment by matysek** [comment]
If this is still an issue please reopen it.
