### ISSUE TITLE
Error Pyinstaller PyQt5

### ISSUE THREAD

**Issue by Mikiqueen0** [pyinstaller/pyinstaller#7640]
When I try to run pyinstaller It print error message : 
** main.py line 7 is `from PyQt5.QtWidgets import QApplication, QMainWindow, QHeaderView, QTableWidgetItem`
macOS ventura, PyQt 5.15.9, Python 3.11.3

File "main.py", line 7, in <module>
ImportError: dlopen(/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/PyQt5/QtWidgets.abi3.so, 0x0002): Symbol not found: __ZN10QArrayData11shared_nullE
  Referenced from: <A3E44BCF-5998-3ACB-B03F-F4CD4AB90D3F> /private/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/PyQt5/QtWidgets.abi3.so
  Expected in:     <18FC602C-E5BB-356F-AAE0-51813731737C> /private/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/QtCore
[28646] Failed to execute script 'main' due to unhandled exception: dlopen(/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/PyQt5/QtWidgets.abi3.so, 0x0002): Symbol not found: __ZN10QArrayData11shared_nullE
  Referenced from: <A3E44BCF-5998-3ACB-B03F-F4CD4AB90D3F> /private/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/PyQt5/QtWidgets.abi3.so
  Expected in:     <18FC602C-E5BB-356F-AAE0-51813731737C> /private/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/QtCore
[28646] Traceback:
Traceback (most recent call last):
  File "main.py", line 7, in <module>
ImportError: dlopen(/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/PyQt5/QtWidgets.abi3.so, 0x0002): Symbol not found: __ZN10QArrayData11shared_nullE
  Referenced from: <A3E44BCF-5998-3ACB-B03F-F4CD4AB90D3F> /private/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/PyQt5/QtWidgets.abi3.so
  Expected in:     <18FC602C-E5BB-356F-AAE0-51813731737C> /private/var/folders/gn/lkyfx4p15pzcfnk4bdg5dft40000gn/T/_MEInOK6Ir/QtCore

**Comment by bwoodsend** [comment]
Uhm, operating system? Python version? PyQt5 version?

**Comment by rokm** [comment]
Is there another PySide/PyQt installed in that environment? Usually missing symbols stem from incompatible libraries being collected from different PyQt/PySide packages.
