### ISSUE TITLE
Problem exporting gpytorch (jit)

### ISSUE THREAD

**Issue by PMoldtmann** [pyinstaller/pyinstaller#7647]
## Description of the issue

I want to package a tkinter/customtkinter application that uses gpytorch for Bayesian Optimization but I get the error message below. After 2 days of looking online and trying different things myself, I still cannot get it to work.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.6.2```
* Version of Python: ```3.8.16```
* Platform: Windows 11 Home 64bit
* How you installed Python: conda
* Did you also try this on another platform? Does it work there? I did not but I tried multiple conda envs

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
I did but no joy.

  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import customtkinter as ctk
import gpytorch
import torch

class GUI(ctk.CTk):
    def __init__(self):
        super().__init__()
GUI()
```

Compiled with 
```
python -m PyInstaller -w --add-binary "icon.ico;." main.py --collect-all customtkinter --hidden-import PIL 
```
I tried adding 
```
--collect-all gpytorch --collect-all torch --hidden-import gpytorch
```
but no joy.

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "torch\_sources.py", line 21, in get_source_lines_and_file
    sourcelines, file_lineno = inspect.getsourcelines(obj)
  File "inspect.py", line 979, in getsourcelines
  File "inspect.py", line 798, in findsource
OSError: could not get source code

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "gpytorch\__init__.py", line 5, in <module>
    import linear_operator
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "linear_operator\__init__.py", line 2, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "linear_operator\operators\__init__.py", line 3, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "linear_operator\operators\_linear_operator.py", line 18, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "linear_operator\utils\__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "linear_operator\utils\contour_integral_quad.py", line 7, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "linear_operator\utils\linear_cg.py", line 17, in <module>
  File "torch\jit\_script.py", line 1340, in script
    ast = get_jit_def(obj, obj.__name__)
  File "torch\jit\frontend.py", line 234, in get_jit_def
    parsed_def = parse_def(fn)
  File "torch\_sources.py", line 96, in parse_def
    sourcelines, file_lineno, filename = get_source_lines_and_file(fn, ErrorReport.call_stack())
  File "torch\_sources.py", line 28, in get_source_lines_and_file
    raise OSError(msg) from e
OSError: Can't get source for <function _jit_linear_cg_updates at 0x00000196FF083430>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

```

I added to main.spec:
```
import gpytorch
import inspect

def collect_source_files(modules):
    datas = []
    for module in modules:
        source = inspect.getsourcefile(module)
        dest = f"src.{module.__name__}"  # use "src." prefix
        datas.append((source, dest))
    return datas

source_files = collect_source_files([gpytorch])  # return same structure as `collect_data_files()`
source_files_toc = TOC((name, path, 'DATA') for path, name in source_files)
```

and changed "get_source" in "pyimod2_importers.py" to:
```
def get_source(self, fullname):
        """
        Method should return the source code for the module as a string.
        But frozen modules does not contain source code.

        Return None.
        """
        if fullname in self.toc:
            sourcename = f"src.{fullname}"
            if sourcename in self.toc:
                return self._pyz_archive.extract(sourcename)[1].decode("utf-8")
            return None
        else:
            # ImportError should be raised if module not found.
            raise ImportError('No module named ' + fullname)
```
As suggested in https://github.com/pyinstaller/pyinstaller/issues/4764#issuecomment-726668800

but still the same error.

It is complaining about 'linear_operator'
Trying to add
```
from PyInstaller.utils.hooks import collect_data_files

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=binaries,
    datas=[datas,*collect_data_files("linear_operator",include_py_files=True)],
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
```
raises the warnings below before crashing when trying to compile by

python -m PyInstaller main.spec

```
25408 WARNING: Unable to find package for requirement scikit-learn from package gpytorch.
25408 INFO: Packages required by gpytorch:
['linear_operator']
2661 WARNING: Failed to collect submodules for 'torch.utils.tensorboard' because importing 'torch.utils.sensorboard' raised: ModuleNotFoundError: No module named 'tensorboard'
```

Adding
```
import os
os.environ["PYTORCH_JIT"] = "0"
```
to my main.py also didn't do anything

Compilation log is:
```
C:\Users\pHiLi\OneDrive\Dokumente\HSU\Masterarbeit\EvaluationMA\App>cd C:\Users\pHiLi\OneDrive\Dokumente\HSU\Masterarbeit\EvaluationMA\App

C:\Users\pHiLi\OneDrive\Dokumente\HSU\Masterarbeit\EvaluationMA\App>call activate ThreeEightTorch

(ThreeEightTorch) C:\Users\pHiLi\OneDrive\Dokumente\HSU\Masterarbeit\EvaluationMA\App>python -m PyInstaller -w --add-binary "icon.ico;." main.py --collect-all customtkinter --hidden-import PIL --collect-all gpytorch --collect-all torch
1692 INFO: PyInstaller: 5.11.0
1692 INFO: Python: 3.8.16 (conda)
1703 INFO: Platform: Windows-10-10.0.22621-SP0
1704 INFO: wrote C:\Users\pHiLi\OneDrive\Dokumente\HSU\Masterarbeit\EvaluationMA\App\main.spec
1706 INFO: UPX is not available.
3802 INFO: Determining a mapping of distributions to packages...
26182 INFO: Packages required by customtkinter:
['darkdetect']
30081 WARNING: Unable to find package for requirement scikit-learn from package gpytorch.
30081 INFO: Packages required by gpytorch:
['linear_operator']
3131 WARNING: Failed to collect submodules for 'torch.testing._internal.distributed._shard.sharded_tensor' because importing 'torch.testing._internal.distributed._shard.sharded_tensor' raised: ModuleNotFoundError: No module named 'expecttest'
4127 WARNING: NOTE: Redirects are currently not supported in Windows or MacOs.
39734 WARNING: Unable to find package for requirement typing-extensions from package torch.
39735 INFO: Packages required by torch:
[]
39735 INFO: Extending PYTHONPATH with paths
['C:\\Users\\pHiLi\\OneDrive\\Dokumente\\HSU\\Masterarbeit\\EvaluationMA\\App']
40805 INFO: Appending 'binaries' from .spec
40807 INFO: Appending 'datas' from .spec
42502 INFO: checking Analysis
43562 INFO: checking PYZ
43799 INFO: checking PKG
43800 INFO: Bootloader C:\Users\pHiLi\anaconda3\envs\ThreeEightTorch\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
43801 INFO: checking EXE
44064 INFO: checking COLLECT
WARNING: The output directory "C:\Users\pHiLi\OneDrive\Dokumente\HSU\Masterarbeit\EvaluationMA\App\dist\main" and ALL ITS CONTENTS will be REMOVED! Continue? (y/N)y
On your own risk, you can use the option `--noconfirm` to get rid of this question.
69278 INFO: Removing dir C:\Users\pHiLi\OneDrive\Dokumente\HSU\Masterarbeit\EvaluationMA\App\dist\main
72372 INFO: Building COLLECT COLLECT-00.toc
101576 INFO: Building COLLECT COLLECT-00.toc completed successfully.

(ThreeEightTorch) C:\Users\pHiLi\OneDrive\Dokumente\HSU\Masterarbeit\EvaluationMA\App>pause
Press any key to continue . . .
```

I also tried a further linear_operator install 
```
conda install linear_operator -c gpytorch
```

now, according to Anaconda3, I have "linear-operator" and "linear_operator" installed, still no joy.

**Comment by rokm** [comment]
https://github.com/pyinstaller/pyinstaller/issues/4764#issuecomment-726668800 is outdated, and if you replaced  `get_source` in `pyimod2_importers.py`, you basically removed the implementation that is able to read to read files from filesystem (if they are collected).

First re-install PyInstaller to reset your changes, then ensure that sources for `linear_operator` are collected. I think the `--collect-all` you are using might do the trick, but it's usually cleaner to add

```
datas = collect_data_files('linear_operator', include_py_files=True, includes=['**/*.py'])
``` 

to your spec, and pass the `datas` to `Analysis`.

Or even better, create a custom hook, `extra-hooks\hook-linear_operator.py` with:
```python
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = collect_submodules('linear_operator')
# Collect as both byte-compiled modules and source files
module_collection_mode = 'pyz+py'
```

and then add `--additional-hooks-dir=extra-hooks` to your PyInstaller command.

**Comment by PMoldtmann** [comment]
**I'll be logging my progress as I go, hopefully getting it to work soon**

- So I set up a clean Python Enviroment Version 3.8.16 as Gpytorch demands Python 3.8

- I activate the conda environment
- I install customtkinter for the interface via ```pip install customtkinter```
- I install gpytorch via ```pip install gpytorch```
```Installing collected packages: mpmath, typing-extensions, threadpoolctl, sympy, numpy, networkx, MarkupSafe, joblib, filelock, scipy, jinja2, torch, scikit-learn, linear-operator, gpytorch```
- I install pyinstaller via ```conda install -c conda-forge pyinstaller```
- I install torch via ```pip install torch```
- I compile with ```python -m PyInstaller -w -F --add-binary "icon.ico;." main.py --collect-all customtkinter --hidden-import PIL --collect-all linear_operator```

**It works**, although I get a ```WARNING: file already exists but should not: C:\Users\name\AppData\Local\Temp\_MEI212442\torch\_C.cp38-win_amd64.pys``` and ```WARNING: file already exists but should not: C:\Users\name\AppData\Local\Temp\_MEI212442\torch\_C_flatbuffer.cp38-win_amd64.pys```. Anyway now back to my original project(installing dependencies beyond my minimal example).

- I install pandas via ```conda install -c anaconda pandas```
- I install pillow via ```conda install -c anaconda pillow```
- I install xlsxwriter via  ```conda install -c conda-forge xlsxwriter```
- I install openpyxl via ```conda install -c anaconda openpyxl```
- I install botorch via ```conda install -c pytorch -c gpytorch botorch```
Under straight up execution, so not even using pyinstaller I get the error: 
```
Traceback (most recent call last):
 [...]
ImportError: cannot import name '_mul_broadcast_shape' from 'gpytorch.utils.broadcasting' (C:\Users\name\anaconda3\envs\ThreeEightTorch\lib\site-packages\gpytorch\utils\broadcasting.py)
```
So back to the beginning:
**2nd attempt**
- Create a new env in python 3.8.16
- ```pip install customtkinter```
- ```conda install -c pytorch -c gpytorch botorch```
- ```conda install -c anaconda openpyxl```
- ```conda install -c conda-forge xlsxwriter```
- ```conda install -c anaconda pillow```
- ```conda install -c anaconda pandas```
- gpytorch already satisfied
- torch already satisfied
again: ```ImportError: cannot import name '_mul_broadcast_shape' from 'gpytorch.utils.broadcasting' (C:\Users\name\anaconda3\envs\BO\lib\site-packages\gpytorch\utils\broadcasting.py)```
Added ```from botorch.models import SingleTaskGP``` to prior minimal example and it immediately triggered the error so ```conda remove botorch```

**3rd attempt**
- ```conda install botorch -c pytorch -c gpytorch -c conda-forge```
**it works, without errors**
- ```conda install -c conda-forge pyinstaller```
- compiled with ```python -m PyInstaller -w --add-binary "icon.ico;." main.py --collect-all customtkinter --hidden-import PIL --collect-all linear_operator``` but got a "module not found" for openpyxl
- adding ```--hidden-import openpyxl.cell._writer``` got rid of that but then I got:
```Traceback (most recent call last):
  File "main.py", line 17, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
  File "torch\__init__.py", line 140, in <module>
    raise err
OSError: [WinError 126] The specified module could not be found. Error loading "C:\Users\name\[...Project_Folder...]\dist\main\torch\lib\caffe2_nvrtc.dll" or one of its dependencies.
```
- adding ```--collect-all torch``` didn't do the trick, neither did ```--hidden-imports torch```
- adding ```-F``` option to compile gives the same error, so I guess it's because of some dependency
- adding ```--collect-all gpytorch --collect-all scipy``` doesn't do it
- is the "\t" in "[...\]\torch\[...]" being interpreted as a tab character?
- [here ](https://stackoverflow.com/questions/62138516/pyinstaller-torch-exception-most-probably-this-dynlib-dll-was-not-found-when) someone mentioned that caffe2_nvrtc.dll depends on ```nvcuda.dll``` 
- 
adding ```from pathlib import Path``` and
```
MISSING_LIBS = (
Path(r'C:\Windows\System32\nvcuda.dll'),
)

a.binaries += TOC([(lib.name, str(lib.resolve()),'BINARY') for lib in MISSING_LIBS])
``` 
to the .spec as suggested there doesn't help, neither does ```--hidden-import cudatoolkit``` or ```--include-all cudatoolkit``` as ```nvcuda.dll``` is part of this package as [see here](https://answers.microsoft.com/en-us/windows/forum/all/nvcudadll/b475ea5d-4ad8-4bae-9d39-367f6d7f8058)
- [here](https://discuss.pytorch.org/t/cannot-import-torch-error-loading-caffe2-nvrtc-dll/166808) someone mentioned they solved another issue with torch by installing torchvision, so installed it via ```conda install -c pytorch torchvision``` and added ```--collect-all torchvision``` to the compile command, didn't work, neither did ```--hidden-import torchvision```

***WAY TO SOLUTION***
- uninstall pathlib ```conda remove pathlib``` or don't install it to begin with
- install latest dev build 
```
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
- compiled with 
```
python -m PyInstaller -w --add-binary "icon.ico;." main.py --collect-all customtkinter --hidden-import PIL --collect-all linear_operator --hidden-import openpyxl.cell._writer --hidden-import cudatoolkit --hidden-import torchvision --collect-all torch
```
- it now runs but doesn't display images as it does why running the script directly
- adding ```--collect-all tkinter``` to the compile command fixed that, I think everything is working as expected now
**so in total:**
```
python -m PyInstaller -w --add-binary "icon.ico;." main.py --collect-all customtkinter --hidden-import PIL --collect-all linear_operator --hidden-import openpyxl.cell._writer --hidden-import cudatoolkit --hidden-import torchvision --collect-all torch --collect-all tkinter
```
- I wanted to export it as a compressed exe but ```-F``` returns ```Failed to extract cublas64_11.dll: decompression resulted in return code -1!```
