### ISSUE TITLE
MacOS App: codesign checks out on local machine, Apple notarizes just fine, but won't run on other machine.

### ISSUE THREAD

**Issue by Ruben-Kruepper** [pyinstaller/pyinstaller#7658]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.11```
* Version of Python: 3.9 and 3.10 tested
* Platform: OSX
* How you installed Python: both brew and pkg from python.org tested
* Did you also try this on another platform? Does it work there? No

### A minimal example program which shows the error

```
if __name__ == '__main__':
    print('hello world')
```

### Stacktrace / full error message

When run by my collegue in a console, he gets

```

/Applications/Parsonos\ Service.app/Contents/MacOS/Parsonos\ Service ; exit;
USERNAME ~ % /Applications/Parsonos\ Service.app/Contents/MacOS/Parsonos\ Service ; exit;
[17381] Error loading Python lib '/Applications/Parsonos Service.app/Contents/MacOS/Python': dlopen: dlopen(/Applications/Parsonos Service.app/Contents/MacOS/Python, 0x000A): tried: '/Applications/Parsonos Service.app/Contents/MacOS/Python' (code signature invalid in <7397B7D9-A63D-3CEA-AF3D-C47E9EBDE96F> '/Applications/Parsonos Service.app/Contents/MacOS/Python' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00353A70, codeBlobSize=0x0000B560), '/System/Volumes/Preboot/Cryptexes/OS/Applications/Parsonos Service.app/Contents/MacOS/Python' (no such file), '/Applications/Parsonos Service.app/Contents/MacOS/Python' (code signature invalid in <7397B7D9-A63D-3CEA-AF3D-C47E9EBDE96F> '/Applications/Parsonos Service.app/Contents/MacOS/Python' (errno=1) sliceOffset=0x00000000, codeBlobOffset=0x00353A70, codeBlobSize=0x0000B560)

```

I have no clue what's going on here. `codesign`is happy with all signatures (of the `.app`as well as the `Python` binary) on my machine. I have checked and it is indeed signed by my developer id, not ad-hoc. Apple's notarization service is also happy with the App.

**Comment by Ruben-Kruepper** [comment]
This seems like it may be related to [Issue #5062](https://github.com/pyinstaller/pyinstaller/issues/5062).

**Comment by rokm** [comment]
What if you check the signatures on the .app bundle (and the `Python` shared lib) on your colleague's computer? How did you transfer the .app bundle to your colleague's computer?

**Comment by Ruben-Kruepper** [comment]
> What if you check the signatures on the .app bundle (and the `Python` shared lib) on your colleague's computer? How did you transfer the .app bundle to your colleague's computer?

1. will ask him to do that asap
2. I followed what appears to be pretty standard procedure: zip, notarize the zip, unzip and staple the notarization, then zip again and share

I'm no mac expert, do you think going via `dmg`or `pkg`would make a difference?

**Comment by rokm** [comment]
In that case, if you take your shared zip and unpack it on your machine, does it run?

**Comment by Ruben-Kruepper** [comment]
Yes, it does. I even created another user on my machine, downloaded it and it ran fine as that user as well. So it seems to be a device-level issue.

**Comment by rokm** [comment]
Hmm, then check the signatures on the colleagues machine. Both on the .app bundle and on the `Python` shared lib. 

And maybe also compute a checksum (e.g., `sha256`) of `Python` both on your machine and your colleague's to check the file integrity (separate from code-signature verification).
