### ISSUE TITLE
PyInstaller error with function toRaw in utils\versioninfo.py

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#767]
**Original date**: 2013/09/11
**Original reporter**: *aditya DOT kichu AND gmail DOT  COOM *

I am trying to use PyInstaller to build a windows client for the GRR project. I seem to get an Unbound Local error about a local variable 'raw_val' referred before assignment. This variable occurs in the file Pyinstaller\utils\versioninfo.py line 442. I have attached an error log with this to provide more information.

Python version 2.7.4.
Windows 7 64 bit machine.
Pyinstaller version: v 2.0 - 597

**Comment by matysek** [comment]
Closing. Please try the latest dev. If it still persists report a new issue.
