### ISSUE TITLE
ImportError: DLL load failed while importing _env

### ISSUE THREAD

**Issue by Dumbliidore** [pyinstaller/pyinstaller#7673]
## Description of the issue
There is a error when I use fiona on my code.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```4.5.1```
* Version of Python: 3.8.5
* Platform: Windows11
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there?
 I didn't.

### A minimal example program which shows the error

```python
import fiona

path = r"xxx.gdb"       # The path to a gdb file.
layers = fiona.listlayers(path)

print(layers)
```

### Stacktrace / full error message

```cmd
Traceback (most recent call last):
  File "test.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 546, in exec_module
  File "fiona\__init__.py", line 116, in <module>
ImportError: DLL load failed while importing _env: 找不到指定的模块。
[22544] Failed to execute script 'test' due to unhandled exception!
```

**Comment by rokm** [comment]
> * Output of pyinstaller --version: 4.5.1

That's an old and unsupported version of PyInstaller.

**Comment by Dumbliidore** [comment]
> 

You're right, I've solved it, thanks.
