### ISSUE TITLE
Setup the package using a wizard 

### ISSUE THREAD

**Issue by eyalk11** [pyinstaller/pyinstaller#7675]
My suggestion is to provide an option to generate a setup wizard for the app.
Doing setup that simply copies the files to "program files/my app" would ultimately allow for preferable run time compared to one-file option currently.   And using compressed files is not the most convenient way for users , generally.

While it is a bit out of scope,  doing it isn't hard as it seems if we use inno setup. It could just generate suitable iss file, that contains the  instructions about building the installer. Possibly also call the compiler for it. 

An example for such file: 
```
#define MyAppName "Compare My Stocks"
#define MyAppVersion "1.0.0"
#define MyAppPublisher "eyalk11"
#define MyAppURL "https://github.com/eyalk11/compare-my-stocks"
#define MyAppExeName "compare-my-stocks.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{0F67A6FE-C5A8-403D-80A0-DFE5E626232F}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\compare-my-stocks
DisableProgramGroupPage=yes
LicenseFile=C:\Users\ekarni\compare-my-stocks\LICENSE
ArchitecturesInstallIn64BitMode=x64
ArchitecturesAllowed=x64
; Uncomment the following line to run in non-administrative install mode (install for the current user only.)
;PrivilegesRequired=lowest
PrivilegesRequiredOverridesAllowed=dialog
Compression=lzma2/fast
SolidCompression=yes
WizardStyle=modern

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[Files]
Source: "dist\compare-my-stocks\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent


```

**Comment by bwoodsend** [comment]
I think that the name and possibly the version and maybe the icons are the only parts of that `.iss` that PyInstaller could produce using only the information it already has. Everything else would have to be exposed as parameters to PyInstaller (without a nice dedicated inisetup IDE to help you chose them). That sounds to me much worse than writing your own iss from scratch.

**Comment by rokm** [comment]
I'd say generating installers for your frozen application is out of scope of PyInstaller. It creates a stand-alone application from your python code, and how you distribute (and update) it is up to you. I see no technical reason why this would need to be integrated into PyInstaller itself, as you can always automate it in a build script (or a higher-level build tool) that calls PyInstaller and then creates the installer from the result. So that's a no from me.

But I do agree that onedir build + installer is the way to go for distributing the application, as opposed to the onefile build...

**Comment by josmithua** [comment]
> But I do agree that onedir build + installer is the way to go for distributing the application, as opposed to the onefile build...

[Sorry this is off topic] Curious, is this because of performance reasons? Or other reasons?

**Comment by bwoodsend** [comment]
Yeah, these days there's the overhead of *first-time-run* antivirus scans (which contrary to their name will run every time because the unpacked application is rewritten every time) on top of the usual overhead of unpacking everything and starting a second process.
