### ISSUE TITLE
Error OpenCV

### ISSUE THREAD

**Issue by lsc58461** [pyinstaller/pyinstaller#7678]
Error:
OpenCV(4.7.0) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\templmatch.cpp:588: error: (-215:Assertion failed) corr.rows <= img.rows + templ.rows - 1 && corr.cols <= img.cols + templ.cols - 1 in function 'cv::crossCorr'

When I compile with PyInstaller and run the compiled file from a location other than the dist folder, the aforementioned error occurs.

**Comment by lsc58461** [comment]
Partial code used:
        login_form_img = cv2.imread(f'{current_dir}\\NIX\\Data\\Login\\login_page.png', 0)

        # Capture the current screen screenshot
        screenshot = pyautogui.screenshot()
        screenshot = cv2.cvtColor(np.array(screenshot), cv2.COLOR_RGB2GRAY)

        # Image matching
        result = cv2.matchTemplate(screenshot, login_form_img, cv2.TM_CCOEFF_NORMED)

        # Find the highest value in the matching results and set the threshold
        min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(result)
        threshold = 0.8

**Comment by rokm** [comment]
> When I compile with PyInstaller and run the compiled file from a location other than the dist folder, the aforementioned error occurs.

If I had to guess, I'd say you are either loading your image or your template using a relative path, implicitly assuming that they are located in your current working directory (= the dist folder). When that assumption is broken, you fail to load the image (or the template) and trigger the above assert.

**Comment by rokm** [comment]
>  login_form_img = cv2.imread(f'{current_dir}\NIX\Data\Login\login_page.png', 0)

How is `current_dir` computed?

**Comment by lsc58461** [comment]
current_dir = get_current_directory()

def get_current_directory():
    if getattr(sys, 'frozen', False):
        current_dir = os.path.dirname(sys.executable)
    else:
        current_dir = os.path.dirname(os.path.abspath(__file__))
    return current_dir

**Comment by rokm** [comment]
Are you using `onedir` or `onefile` build?

**Comment by lsc58461** [comment]
'--onefile' option was used.

**Comment by rokm** [comment]
If you are collecting that `NIX\Data\Login\login_page.png` into frozen application bundle, then anchoring the path to `sys.executable` is not correct - you should be using `os.dirname(__file__)` (in entry-point script) or `sys._MEIPASS` - both of which will point to the temporary directory into which the application's data is available. (Whereas for `onedir`, `os.path.dirname(sys.executable)` should match `os.dirname(__file__)` (in entry-point script) and `sys._MEIPASS`, so it wouldn't matter).

But if that's a onefile build, then the only way the program actually works is if you manually placed the `NIX\Data\Login\login_page.png` next to the executable... Can you show us the whole PyInstaller command?

**Comment by lsc58461** [comment]
PyInstaller command:
pyinstaller -w --onefile --icon=.\NIX.ico --add-data "Initial Setting.exe;." --add-data "update.exe;." --add-data "login_page.png;." --add-data "login_result.png;." --add-data "play_button.png;."--name=Auto_Login main.py

Partial initial code used:
        current_dir = get_current_directory()
        
        def copy_file(source_path, destination_path):
            try:
                shutil.copy(source_path, destination_path)
                logging.info(f"파일이 {source_path} 에서 {destination_path} 로 복사 되었습니다.")
            except Exception as e:
                logging.warning(f"파일 복사 에러 발생: {str(e)}")
        
        def get_file_path(filename):
            if hasattr(sys, '_MEIPASS'):
                # 실행 파일 내부에서 실행 중인 경우
                logging.info(f'get_file_path : {os.path.join(sys._MEIPASS, filename)}')
                logging.info('실행 파일 내부')
                return os.path.join(sys._MEIPASS, filename)
            else:
                # 일반적인 파이썬 스크립트로 실행 중인 경우
                logging.info(f'get_file_path : {os.path.dirname(os.path.abspath(__file__))}\\{filename}')
                return os.path.dirname(os.path.abspath(__file__)) + "\\" + filename
        # login_page.png
        login_page_png_path = get_file_path('login_page.png')
        
        copy_file(login_page_png_path, f'{current_dir}\\NIX\\Data\\Login\\login_page.png')

        # login_result.png
        login_result_png_path = get_file_path('login_result.png')
        
        copy_file(login_result_png_path, f'{current_dir}\\NIX\\Data\\Login\\login_result.png')

        # play_button.png
        play_button_png_path = get_file_path('play_button.png')
        
        copy_file(play_button_png_path, f'{current_dir}\\NIX\\Data\\Login\\play_button.png')

**Comment by rokm** [comment]
Hmm, okay. So at build time, you actually collect the image `login_page.png` into the frozen application bundle, and then at run-time, you copy it from application's temporary directory to `NIX\Data\Login\login_page.png` next to the executable?

In that case, does the copying actually succeed? Does `shutil.copy` actually create the target directory structure if it does not exist yet? Or does this block,
```
    def copy_file(source_path, destination_path):
        try:
            shutil.copy(source_path, destination_path)
            logging.info(f"파일이 {source_path} 에서 {destination_path} 로 복사 되었습니다.")
        except Exception as e:
            logging.warning(f"파일 복사 에러 발생: {str(e)}")
```
silently fail because you swallow the exception, but you use `-w` (windowed/noconsole) so you cannot see the warning?

Try building without `-w` so you get console and see what's going on...

And while you're at it, try printing the dimensions of both images right before the `cv2.matchTemplate` call - one of the images is likely to be 0 x 0 because it failed to load...

**Comment by lsc58461** [comment]
I appreciate your gratitude for the answers provided.

The issue occurs because the screenshot is a 2-dimensional grayscale image, while the img is a 3-dimensional color image. The mismatch in dimensions between the two images causes an error in the cv2.matchTemplate function.

Another issue with the code is that it encounters problems when trying to load paths that include Korean characters.
