### ISSUE TITLE
How to update exe without repackaging other third-party libraries?

### ISSUE THREAD

**Issue by KingerFzb** [pyinstaller/pyinstaller#7680]
```
import package1
import package2

def func():
    package1.func()
    package2.func()

func()
print('Hello World')
```
I wrote the above code and packaged it with pyinstaller, now I changed the code without introduce other libraries.
```
import package1
import package2

def func():
    package1.func()
    package2.func()

func()
print('Hello World')
print('add something new')
```
Then I packed the code again, and pyinstaller still packages all the files, even though they already exist.
I tried to get exe from the second package and put it into the first package. It still works well.
Is there a way to just update exe? You know, if too many libraries are introduced, repackaging will take a long time.

**Comment by rokm** [comment]
> Is there a way to just update exe?

There is not.
