### ISSUE TITLE
Building with Python 3.11.4 fails

### ISSUE THREAD

**Issue by jay0lee** [pyinstaller/pyinstaller#7692]
# Steps to repro
1. Upgrade to Python 3.11.4
2. Compile a sample app with PyInstaller 5.11.0

```
import urllib.parse
print('hello world')
```

# Expected result
Compiled app works

# Actual result
Script compiles but dies at runtime with:

```
./test 
[20089] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
  File "pathlib.py", line 14, in <module>
  File "urllib/parse.py", line 40, in <module>
ModuleNotFoundError: No module named 'ipaddress'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[20089] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

# Other details
Python 3.11.4 has a patch which imports ipaddress from urllib.parse:

https://github.com/python/cpython/commit/b2171a2fd41416cf68afd67460578631d755a550

**Comment by jay0lee** [comment]
I did some more testing and this fails in the same fashion when I import `ipaddress` directly also:

```
import ipaddress
print('hello world')
```

**Comment by bwoodsend** [comment]
The same thing happened to Python 3.12. Looks like we'll need a change a bit like https://github.com/pyinstaller/pyinstaller/pull/7670/commits/ce6b0db739184ba544208ea7b7aaa8e3dbb4f731. I wonder if CPython will keep barkporting the offending change to 3.10, 3.9 and 3.8...

If you need a dirty fix now, find the `_PY3_BASE_MODULES` set in `lib/python3.11/site-packages/PyInstaller/compat.py` and add `"ipaddress"` there.

**Comment by bwoodsend** [comment]
Actually it shouldn't. Python 3.10 and below are all in security fixes only mode.

**Comment by bwoodsend** [comment]
> I did some more testing and this fails in the same fashion when I import `ipaddress` directly also:
> 
> ```
> import ipaddress
> print('hello world')
> ```

Just the print statement or an empty script is enough. `pathlib` (which imports `urllib.parse` which now imports `ipaddress`) is a so called *base module* which means that it's needed by the code that handles all the other imports.

**Comment by bwoodsend** [comment]
Fixed in v5.12.
```bash
pip install "pyinstaller>=5.12"
```

**Comment by jay0lee** [comment]
Huge thanks for the quick fix and release!

**Comment by haohetao** [comment]
I have a same problem.
