### ISSUE TITLE
FileNotFoundError when compiling a script

### ISSUE THREAD

**Issue by SimoLRepo** [pyinstaller/pyinstaller#7710]
Hi, i downloaded "Python Windows embeddable package (64-bit)" [v3.11.4] and ubsequently then downloaded pyinstaller [v5.12.0] via pip and carefully followed the instructions taken from multiple sources to understand its use. Unfortunately, the following error keeps occurring inexplicably:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\Python_amd64\\python311.zip\\struct.pyc'

I checked the zipper file and the "struct.pyc" file is present

**Comment by bwoodsend** [comment]
See #4989.
