### ISSUE TITLE
Fatal error in launcher: Unable to create process using 

### ISSUE THREAD

**Issue by funmolde** [pyinstaller/pyinstaller#7717]
Hello -_-
I have this error when I launch my .exe file created with pyinstaller on another other PC where python is not installed.

Fatal error in launcher: Unable to create process using "C:\Users\Max\AppData\Local\Programs\Python\Python39\python.exe"

I tried to add the python.exe file but the same error.
I would like to be able to launch my .exe program without having to install python on another other PC .

pyinstaller version: 5.12.0
Python on my pc: 3.9.8
Windows 11 64 bits

Thank you

**Comment by rokm** [comment]
Your code or the 3rd party code you are using is trying to launch that python process - there's nothing we can do about that.
