### ISSUE TITLE
can't install pyinstaller

### ISSUE THREAD

**Issue by rodneybear** [pyinstaller/pyinstaller#7718]
I am new to using pyinstaller. When running pip install -U pyinstaller i keep getting same error.
ERROR: Could not find a version that satisfies the requirement pyinstaller (from versions: none)
ERROR: No matching distribution found for pyinstaller

**Comment by bwoodsend** [comment]
What's the output of `pip -VV`?

**Comment by nithinmahendran** [comment]
Can you try installing via pip3? Can you please confirm if you are using your development machine where you are have access to the internet? Or are you using your organizations machine?
