### ISSUE TITLE
Failed to execute script due to unhandled exception: No Module named 'wx'

### ISSUE THREAD

**Issue by ahmed-gamal10** [pyinstaller/pyinstaller#7719]
Unhandled exception in script: 
Failed to execute script 'app' due to unhandled exception: No module named 'wx' 
Traceback (most recent call last): 
File "app.py", line 7, in <module> 
File "Pylnstaller\loader\pyimod02_importers.py", line 352, in excel 
File "app_tray.py", line 3, in <module> ModuleNotFoundError: No module named 'wx'
![image](https://github.com/pyinstaller/pyinstaller/assets/16737528/d4566004-467a-424e-b76e-6d20d9dca362)

I am facing this error while running my application after converting it using pyinstaller using the below link
pyinstaller --paths bg_services;WSserver;utils;ws_handlers;models;ui --windowed --name CaptureHub --icon=scanning.ico --clean app.py
 however, the application run normally in Python environment.

the below file is the warn file that was generated in the build folder

[warn-CaptureHub.txt](https://github.com/pyinstaller/pyinstaller/files/11782434/warn-CaptureHub.txt)

**Comment by rokm** [comment]
If that `wx` is a direct import in the entry-point script (and the attached warn file suggests it is), then it was not accessible during the build. Most common reason for that is mixed up python environments (`pyinstaller` script pointing to installation in python environment that is different from the one in which you run your script).

If you run `where pyinstaller` in the command prompt (`cmd`), what is the output? 

Is there any difference if you run `python -m PyInstaller ...` instead of `pyinstaller ...`?

**Comment by ahmed-gamal10** [comment]
@rokm I tried your solution, but it does not change anything I got the same error and same results. 
can you help me to find a solution for this case?

**Comment by bwoodsend** [comment]
> If you run where pyinstaller in the command prompt (cmd), what is the output?

**Comment by ahmed-gamal10** [comment]
@bwoodsend  this is the cmd log

---------------------------------------------------------------------------------------------------------------------------------------
C:\Git Projectss\Capture-Hub 3.7>pyinstaller --paths bg_services;WSserver;utils;ws_handlers;models;ui --windowed --name CaptureHub --icon=scanning.ico --clean app.py
2643 INFO: PyInstaller: 5.10.1
2643 INFO: Python: 3.7.0
2643 INFO: Platform: Windows-10-10.0.19041-SP0
2645 INFO: wrote C:\Git Projectss\Capture-Hub 3.7\CaptureHub.spec
2658 INFO: UPX is not available.
2659 INFO: Removing temporary files and cleaning cache in C:\Users\ahmed.gamal\AppData\Local\pyinstaller
2709 INFO: Extending PYTHONPATH with paths
['C:\\Git Projectss\\Capture-Hub 3.7',
 'C:\\Git Projectss\\Capture-Hub 3.7\\bg_services',
 'C:\\Git Projectss\\Capture-Hub 3.7\\WSserver',
 'C:\\Git Projectss\\Capture-Hub 3.7\\utils',
 'C:\\Git Projectss\\Capture-Hub 3.7\\ws_handlers',
 'C:\\Git Projectss\\Capture-Hub 3.7\\models',
 'C:\\Git Projectss\\Capture-Hub 3.7\\ui']
3618 INFO: checking Analysis
3619 INFO: Building Analysis because Analysis-00.toc is non existent
3619 INFO: Initializing module dependency graph...
3624 INFO: Caching module graph hooks...
3847 INFO: Analyzing base_library.zip ...
6683 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
8142 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
8511 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
10880 INFO: Caching module dependency graph...
11277 INFO: running Analysis Analysis-00.toc
11306 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\ahmed.gamal\AppData\Local\Programs\Python\Python37-32\python.exe
11506 INFO: Analyzing C:\Git Projectss\Capture-Hub 3.7\app.py
11592 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
12136 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
12204 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
12254 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
12909 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
14506 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
17158 INFO: Loading module hook 'hook-charset_normalizer.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
17439 INFO: Loading module hook 'hook-cryptography.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
21194 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
23110 INFO: Processing module hooks...
23126 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks'...
23138 INFO: checking Tree
23139 INFO: Building Tree because Tree-00.toc is non existent
23139 INFO: Building Tree Tree-00.toc
26075 INFO: checking Tree
26075 INFO: Building Tree because Tree-01.toc is non existent
26075 INFO: Building Tree Tree-01.toc
26409 INFO: checking Tree
26410 INFO: Building Tree because Tree-02.toc is non existent
26411 INFO: Building Tree Tree-02.toc
26524 INFO: Looking for ctypes DLLs
26544 INFO: Analyzing run-time hooks ...
26552 INFO: Including run-time hook 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
26560 INFO: Including run-time hook 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
26570 INFO: Including run-time hook 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
26580 INFO: Including run-time hook 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
26648 INFO: Looking for dynamic libraries
1389 INFO: Extra DLL search directories (PATH): ['C:\\ProgramData\\Oracle\\Java\\javapath', 'C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.5.8-hotspot\\bin', 'C:\\Program Files\\Eclipse Adoptium\\jdk-8.0.352.8-hotspot\\bin', 'C:\\Program Files\\Common Files\\Oracle\\Java\\javapath', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\Program Files\\Java\\jdk1.8.0_152\\bin', 'D:\\Maven\\apache-maven-3.8.6\\bin', 'C:\\ProgramData\\chocolatey\\bin', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files\\TortoiseGit\\bin', 'C:\\Program Files\\PowerShell\\7\\', 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\Scripts\\', 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Python\\Python37-32\\', 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2023.1.2\\bin', 'C:\\Users\\ahmed.gamal\\AppData\\Local\\Programs\\Microsoft VS Code\\bin']
29879 INFO: Looking for eggs
29879 INFO: Using Python library C:\Users\ahmed.gamal\AppData\Local\Programs\Python\Python37-32\python37.dll
29881 INFO: Found binding redirects:
[]
29892 INFO: Warnings written to C:\Git Projectss\Capture-Hub 3.7\build\CaptureHub\warn-CaptureHub.txt
30047 INFO: Graph cross-reference written to C:\Git Projectss\Capture-Hub 3.7\build\CaptureHub\xref-CaptureHub.html
30207 INFO: checking PYZ
30208 INFO: Building PYZ because PYZ-00.toc is non existent
30210 INFO: Building PYZ (ZlibArchive) C:\Git Projectss\Capture-Hub 3.7\build\CaptureHub\PYZ-00.pyz
32403 INFO: Building PYZ (ZlibArchive) C:\Git Projectss\Capture-Hub 3.7\build\CaptureHub\PYZ-00.pyz completed successfully.
32438 INFO: checking PKG
32440 INFO: Building PKG because PKG-00.toc is non existent
32442 INFO: Building PKG (CArchive) CaptureHub.pkg
32534 INFO: Building PKG (CArchive) CaptureHub.pkg completed successfully.
32539 INFO: Bootloader C:\Users\ahmed.gamal\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PyInstaller\bootloader\Windows-32bit-intel\runw.exe
32540 INFO: checking EXE
32541 INFO: Building EXE because EXE-00.toc is non existent
32541 INFO: Building EXE from EXE-00.toc
32543 INFO: Copying bootloader EXE to C:\Git Projectss\Capture-Hub 3.7\build\CaptureHub\CaptureHub.exe.notanexecutable
32573 INFO: Copying icon to EXE
32583 INFO: Copying icons from ['C:\\Git Projectss\\Capture-Hub 3.7\\scanning.ico']
32584 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
32584 INFO: Writing RT_ICON 1 resource with 16936 bytes
32589 INFO: Copying 0 resources to EXE
32589 INFO: Embedding manifest in EXE
32591 INFO: Updating manifest in C:\Git Projectss\Capture-Hub 3.7\build\CaptureHub\CaptureHub.exe.notanexecutable
32592 INFO: Updating resource type 24 name 1 language 0
32596 INFO: Appending PKG archive to EXE
32632 INFO: Fixing EXE headers
32709 INFO: Building EXE from EXE-00.toc completed successfully.
32717 INFO: checking COLLECT
32717 INFO: Building COLLECT because COLLECT-00.toc is non existent
32718 INFO: Building COLLECT COLLECT-00.toc
45056 INFO: Building COLLECT COLLECT-00.toc completed successfully.
C:\Git Projectss\Capture-Hub 3.7>


and this is the warn text file
[warn-CaptureHub.txt](https://github.com/pyinstaller/pyinstaller/files/12027063/warn-CaptureHub.txt)

------------------------------------------------------------------------------------------------------------------------------------------

And the outbut in dist folder is the following files and folders:
base_library.zip
CaptureHub.exe
certifi
charset_normalizer
cryptography
cryptography-35.0.0.dist-info
ETDA-invoice.xml
icons
libcrypto-1_1.dll
libssl-1_1.dll
PdfAConverter-jar-with-dependencies.jar
psutil
pyexpat.pyd
python3.dll
python37.dll
select.pyd
sRGBColorSpaceProfile.icm
tcl
tcl8
tcl86t.dll
tk
tk86t.dll
tornado
twain.cp37-win32.pyd
unicodedata.pyd
VCRUNTIME140.dll
views
xmpTemplate.xml
_asyncio.pyd
_bz2.pyd
_cffi_backend.cp37-win32.pyd
_contextvars.pyd
_ctypes.pyd
_decimal.pyd
_elementtree.pyd
_hashlib.pyd
_lzma.pyd
_multiprocessing.pyd
_overlapped.pyd
_queue.pyd
_socket.pyd
_ssl.pyd
_tkinter.pyd

![image](https://github.com/pyinstaller/pyinstaller/assets/16737528/4de5f734-c696-42fd-8f20-a6e7ebd07c2e)


I had a backup of the dist folder that work successfully and it has more files that this output
altgraph-0.17.2.dist-info
base_library.zip
CaptureHub.exe
certifi
cryptography
cryptography-2.2.2.dist-info
ETDA-invoice.xml
icons
IPython
jedi
libcrypto-1_1.dll
libopenblas.VTYUM5MXKVFE4PZZER3L7PNO6YB4XFF3.gfortran-win32.dll
libsodium-1a96dce1.dll
libssl-1_1.dll
libzmq-v141-mt-4_3_4-809e0775.dll
mfc140u.dll
msvcp140.dll
numpy
parso
PdfAConverter-jar-with-dependencies.jar
PIL
private.key
psutil
pyexpat.pyd
pyinstaller-4.6.dist-info
python37.dll
pythoncom37.dll
pywintypes37.dll
pyzmq.libs
select.pyd
selfsigned.crt
setuptools-39.0.1.dist-info
sqlite3.dll
sRGBColorSpaceProfile.icm
tcl
tcl8
tcl86t.dll
tk
tk86t.dll
twain.cp37-win32.pyd
unicodedata.pyd
VCRUNTIME140.dll
views
wcwidth
win32api.pyd
win32clipboard.pyd
win32com
win32evtlog.pyd
win32pdh.pyd
win32security.pyd
win32trace.pyd
win32ui.pyd
win32wnet.pyd
wx
wxbase30u_net_vc140.dll
wxbase30u_vc140.dll
wxmsw30u_adv_vc140.dll
wxmsw30u_core_vc140.dll
xmpTemplate.xml
zmq
_asyncio.pyd
_bz2.pyd
_cffi_backend.cp37-win32.pyd
_contextvars.pyd
_ctypes.pyd
_decimal.pyd
_distutils_findvs.pyd
_elementtree.pyd
_hashlib.pyd
_lzma.pyd
_multiprocessing.pyd
_overlapped.pyd
_queue.pyd
_socket.pyd
_sqlite3.pyd
_ssl.pyd
_tkinter.pyd
_win32sysloader.pyd

![image](https://github.com/pyinstaller/pyinstaller/assets/16737528/53e678a0-0ad3-4743-a62b-ee6d6c35659a)

and this is the backup warn text file 

[warn-CaptureHub.txt](https://github.com/pyinstaller/pyinstaller/files/12027054/warn-CaptureHub.txt)

**Comment by bwoodsend** [comment]
So PyInstaller is installed in a Python 3.7 environment at `C:\Users\ahmed.gamal\AppData\Local\Programs\Python\Python37-32` without using a virtual environment. Presumably `wx` is installed in a different (possibly virtual) environment. You either need to install `wx` into the `C:\Users\ahmed.gamal\AppData\Local\Programs\Python\Python37-32` environment or to install PyInstaller into whichever environment `wx` is in.
