### ISSUE TITLE
Pyinstaller-created program not opening on fresh Windows install

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#772]
**Original date**: 2013/09/15
**Original reporter**: *sajattack AND gmail DOT  COOM *

I recently broke a solid state drive so I had to reinstall windows etc. After a fresh install, a program I created with pyinstaller wouldn't open or give me an error message. Now that I have installed Visual Studio 2012, it works fine. I'm assuming VS comes with a bunch of redistributables, one or more of which is required for pyinstaller. Does anyone know what it is so I can inform my users?

**Comment by codewarrior0** [comment]
This is essentially fixed. PyInstaller now bundles the required redistributables with the built app.
