### ISSUE TITLE
OSError: [WinError 1920] 系统无法访问此文件。: "C:\\Users\\xieLabypya'ba'ba'ba'\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\python.exe"

### ISSUE THREAD

**Issue by friendmaking** [pyinstaller/pyinstaller#7720]
OSError: [WinError 1920] 系统无法访问此文件。: "C:\\Users\\xieLabypya'ba'ba'ba'\\AppData\\Local\\Microsoft\\WindowsApps\\PythonSoftwareFoundation.Python.3.7_qbz5n2kfra8p0\\python.exe"
When using pyinstall to package the pyside2 program, an error occurred that the Python interpreter cannot access. May I ask how to solve it

**Comment by bwoodsend** [comment]
Can you try with a Python environment from https://python.org/downloads? The Windows store Python has a history of poorly thought out permissions locking which leads to errors like this.

**Comment by bwoodsend** [comment]
And can we have the full error message so we have some idea of what it was trying to do when it failed.

**Comment by rokm** [comment]
What version of PyInstaller is that? I thought we fixed this sort of issue...

**Comment by friendmaking** [comment]
> What version of PyInstaller is that? I thought we fixed this sort of issue...

It's version 5.12.0.
Thank you for your help. The problem has been resolved: I changed the path and created a new virtual environment, and the bug disappeared

**Comment by friendmaking** [comment]
> Thank you for your help. The problem has been resolved: I changed the path and created a new virtual environment, and the bug disappeared

Thank you for answering my question. The problem has been resolved: I changed the path and created a new virtual environment, and the bug disappeared
