### ISSUE TITLE
Plain import of `glfw` hangs execution

### ISSUE THREAD

**Issue by BenBE** [pyinstaller/pyinstaller#7723]
## Description of the issue

When a program compiled with PyInstaller tries to import `glfw`, the execution hangs and loads of subprocesses start to be spawned.

Tested with both `glfw` versions 2.5.5 (first noticed), still exists with 2.5.9:

```
$ pip3 show glfw
Name: glfw
Version: 2.5.9
Summary: A ctypes-based wrapper for GLFW3.
Home-page: https://github.com/FlorianRhiem/pyGLFW
Author: Florian Rhiem
Author-email: florian.rhiem@gmail.com
License: MIT
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.12.0```
* Version of Python: Python 3.10.6
* Platform: Ubuntu 22.04 LTS (amd64)
* How you installed Python: distribution package
* Did you also try this on another platform? Does it work there?

The script, that this issue was first noticed with, works fine on Windows.
The small reproducer posted below was not tested on Windows though, just with Linux (multiple computers).

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

No change in behavior.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

Done. See below.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
print("1")
import glfw
print("2")
```

### Stacktrace / full error message

Just prints `1` and hangs while spawning loads of subprocesses.
Running the same script with python directly prints both "1" and "2" nearly instantly and then exits.

The [following trace](https://github.com/pyinstaller/pyinstaller/files/11817729/test.trace.log) shows the debug output. The program has been interrupted using <kbd>Ctrl</kbd>+<kbd>c</kbd> once it entered the infinite subprocess loop.

Binary built using the following command line:
```
LC_ALL=C.UTF-8 pyinstaller -n test --noconfirm --noupx --onedir --collect-binaries glfw -d all --clean test.py 
```

**Comment by bwoodsend** [comment]
That's because [glfw does a version check in a subprocess](https://github.com/FlorianRhiem/pyGLFW/blob/0679b96a0fd1c5f3f2fc568630fa72d73338f850/glfw/library.py#L69-L120). In a PyInstaller application, `sys.executable` is the application rather than a Python interpreter so every subprocess spawns a new subprocess recursively until the whole thing crashes. There's nothing PyInstaller can do about this. `glfw` need to remove that subprocess (which wouldn't be necessary if it didn't try to iterate across `glfw3` libraries).

**Comment by BenBE** [comment]
FYI: Resolved [upstream](https://github.com/FlorianRhiem/pyGLFW/issues/71#issuecomment-1604623323) in release [2.6.0](https://github.com/FlorianRhiem/pyGLFW/releases/tag/v2.6.0) (or later).
