### ISSUE TITLE
Can we minimise the console window to taskbar?

### ISSUE THREAD

**Issue by Akascape** [pyinstaller/pyinstaller#7729]
I want the console window running in the background, but it stays behind after opening the main window of my app.
I want that console window to be **minimized in the taskbar** after opening the main app. Is it possible?
Or is there any other method to get the access to that console window?

**Comment by bwoodsend** [comment]
I don't know the gory details of Windows's APIs but I very much doubt that this is possible. Whatever it is that you want to see in that console, I suggest you redirect it somewhere else such as a log file or a hidden diagnostics window.

**Comment by rokm** [comment]
You can programmatically minimize the console in your code. Example:

```python
import sys
import signal
import ctypes

from PySide2 import QtCore, QtWidgets

if sys.platform == 'win32':
    import ctypes
    import ctypes.wintypes
    
    # Get console window
    console_window = ctypes.windll.kernel32.GetConsoleWindow()
    if console_window:
        # Check if console is owned by this process...
        process_id = ctypes.windll.kernel32.GetCurrentProcessId()
        console_process_id = ctypes.wintypes.DWORD()
        ctypes.windll.user32.GetWindowThreadProcessId(console_window, ctypes.byref(console_process_id))
        console_process_id = console_process_id.value
        if process_id == console_process_id:
            # ... and if it is, minimize it
            ctypes.windll.user32.ShowWindow(console_window, 2)  # SW_SHOWMINIMIZED

# The example GUI application
app = QtWidgets.QApplication(sys.argv)
signal.signal(signal.SIGINT, signal.SIG_DFL)

window = QtWidgets.QWidget()
window.setWindowTitle("Hello world!")
window.show()

app.exec_()
```

The above example explicitly verifies that the process owns console (i.e., was not launched from already-opened console, in which case you might not want to minimize it). The downside is that it works only for `onedir` builds; in `onefile` build, the console would be owned by the parent process, and so the check would have to be done differently.

Another thing to note is that the console will be minimized only after the program reaches your code (so it won't *start* minimized). If you wanted to further reduce the amount of time the console is open, you would have to perform minimization in the bootloader, probably at the very beginning of its execution. But even with that, it would not be instantaneous.

**Comment by Akascape** [comment]
@rokm 

> The downside is that it works only for onedir builds; in onefile build, the console would be owned by the parent process, and so the check would have to be done differently.

Unfortunately, I am making an one-file executable. How can I do the check there?

> Another thing to note is that the console will be minimized only after the program reaches your code (so it won't start minimized). 

Yes, that is the what I exactly need. Just like other programs, eg: blender.

**Comment by Akascape** [comment]
@rokm btw can this feature be added to pyinstaller?
It would be great if we have option like `minimise_console`.

**Comment by rokm** [comment]
> @rokm btw can this feature be added to pyinstaller? It would be great if we have option like `minimise_console`.

I suppose we could try adding a bootloader flag that would, depending on the value, call `ShowWindow` with either SW_SHOWMINIMIZED or SW_HIDE as soon as we can read options from the PKG. This would allow console to be hidden/minimized when console is owned by either onedir or onefile program.

I'll try to come up with a prototype and see how it behaves.

**Comment by rokm** [comment]
> > @rokm btw can this feature be added to pyinstaller? It would be great if we have option like `minimise_console`.
> 
> I suppose we could try adding a bootloader flag that would, depending on the value, call `ShowWindow` with either SW_SHOWMINIMIZED or SW_HIDE as soon as we can read options from the PKG. This would allow console to be hidden/minimized when console is owned by either onedir or onefile program.
> 
> I'll try to come up with a prototype and see how it behaves.

Although if you want to minimize console when your UI comes up, you should be doing this in your code; as minimizing in bootloader will happen before any python code is ran...

**Comment by Akascape** [comment]
@rokm 
>  The downside is that it works only for onedir builds; in onefile build, the console would be owned by the parent process, and so the check would have to be done differently.

That method is not working with onefile build. What will be the approach for it?

**Comment by rokm** [comment]
> @rokm
> 
> > The downside is that it works only for onedir builds; in onefile build, the console would be owned by the parent process, and so the check would have to be done differently.
> 
> That method is not working with onefile build. What will be the approach for it?

I told you as much, didn't I? If you want it to work with onefile, you'll either have to remove the console ownership check, or revise it to account for console being owned by the parent process.

Or, you can try using #7735, but you will have to recompile the bootloader yourself, otherwise it won't work.
