### ISSUE TITLE
Can I use PyInstaller to package transformers only in windowed mode?

### ISSUE THREAD

**Issue by 17Reset** [pyinstaller/pyinstaller#7731]
I see from other branches that when transformers need to print progress bars in the console using tqdm, package this project and only choose --console mode?

**Comment by rokm** [comment]
You can set up dummy `sys.stdout` and `sys.stderr` if your code (or the 3rd party code you are using) cannot deal with them being `None` in the windowed mode. See https://github.com/pyinstaller/pyinstaller/issues/7334#issuecomment-1357447176.

**Comment by 17Reset** [comment]
> You can set up dummy and if your code (or the 3rd party code you are using) cannot deal with them being in the windowed mode. See [#7334 (comment)](https://github.com/pyinstaller/pyinstaller/issues/7334#issuecomment-1357447176).`sys.stdout``sys.stderr``None`

It's transformers that will print the progress bar using the console by default, how can this be handled, please?
  File "transformers\utils\logging.py", line 88, in _configure_library_root_logger
    _default_handler.flush = sys.stderr.flush
                             ^^^^^^^^^^^^^^^^
'NoneType' object has no attribute 'flush'

**Comment by rokm** [comment]
> how can this be handled, please?

Again, see https://github.com/pyinstaller/pyinstaller/issues/7334#issuecomment-1357447176.

**Comment by 17Reset** [comment]
> > how can this be handled, please?
> 
> Again, see [#7334 (comment)](https://github.com/pyinstaller/pyinstaller/issues/7334#issuecomment-1357447176).

Thank you very much, it worked.
