### ISSUE TITLE
No module a

### ISSUE THREAD

**Issue by JMoreno97** [pyinstaller/pyinstaller#7742]
I have this proyect structure in PyCharm
![image](https://github.com/pyinstaller/pyinstaller/assets/18291802/b4fe1b8f-ab40-45d3-8971-ccac6879bcf7)

I had no problems to run my app running main.py which in src/main.py

But when I create the .exe using this command:
`pyinstaller --onefile --clean --debug=imports --name Configurador src/main.py      `

I get this error and I cant run my app:

```
ModuleNotFoundError: No module named 'src'
[15292] Failed to execute script 'main' due to unhandled exception!
```

**Comment by bwoodsend** [comment]
Does `python src/main.py` work? PyCharm wrongly adds the root of your project to `sys.path` so under PyCharm, you'd be able to run `import src` but in normal Python, this won't work.

However, this is a very wrong way to layout your package. You're `Classes` and `Schemas` directories and contents of the `src` directory should be moved into a directory named to whatever your project is called. `main.py` should be renamed to `__main__.py`. Then you should write a `pyproject.toml` (see [tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/)), install your package with pip in editable mode and then you can come back to PyInstaller.
