### ISSUE TITLE
Relax the Python version upper bound

### ISSUE THREAD

**Issue by laclouis5** [pyinstaller/pyinstaller#7748]
**Is your feature request related to a problem? Please describe.**
PyInstaller currently requires [Python >= 3.8 and < 3.13](https://github.com/pyinstaller/pyinstaller/blob/c342dacc7cd7330b1e974fb5cbd81d08b196023e/setup.cfg#L60C3-L60C3).

This breaks many projects that do not specify an upper bound to the Python version. For instance in one of my project using Poetry to manage dependencies, I use the constrain `python = "^3.8"` and I'm not able to add PyInstaller as a dependency. 
I need to specify the same upper bound as PyInstaller: `python = "^3.8 <3.13"` for this to work, but this limit is rather arbitrary IMO.

What is the purpose of this limit and would it be possible to relax it?

**Describe the solution you'd like**
Relax the Python constrain, e.g. using Python >= 3.8.

**Describe alternatives you've considered**
Specifying the same upper bound for the Python constrain as PyInstaller.

**Comment by bwoodsend** [comment]
See #7605. Tl;dr is no, it's a very deliberate constraint.

**Comment by bwoodsend** [comment]
As long as I know, PyInstaller has never supported a new minor version of Python out the box.

**Comment by laclouis5** [comment]
Thanks for the answer, makes sense.
