### ISSUE TITLE
Added binaries do not see other added binaries on the list.

### ISSUE THREAD

**Issue by duhoang** [pyinstaller/pyinstaller#7750]
I have two missing DLLs when building my EXE with Pyinstaller. When I add them via add binaries in the spec file, and the first missing DLL is dependent on the second missing DLL, but it won't recognize the second missing DLL if they are both on the add binaries list.

Example:
`9830 WARNING: lib not found: avformat-58.dll dependency of C:\Users\PC\Desktop\stablenetfusion\stablenetfusion-app\venv\Lib\site-packages\torchaudio\lib\_torchaudio_ffmpeg.pyd
9832 WARNING: lib not found: avutil-56.dll dependency of C:\Users\PC\Desktop\stablenetfusion\stablenetfusion-app\venv\Lib\site-packages\torchaudio\lib\_torchaudio_ffmpeg.pyd`

Notice how `avutil-56.dll` and `avformat-58.dll` are missing for `_torchaudio_ffmpeg.pyd`

Nothing unusually here, according to the docs I can simply add those binaries using the spec file like so:

`a = Analysis(['main.py'],
             pathex=['.\\py_src\\'],
             binaries=[
                ('.\\binary-dependencies\\avutil-56.dll', '.'),
                ('.\\binary-dependencies\\avformat-58.dll', '.'),
                ],`

But now while `avutil-56.dll` is found for `_torchaudio_ffmpeg.pyd`, it is missing for  `avformat-58.dll` even though it was added to binaries list.

`9125 WARNING: lib not found: avutil-56.dll dependency of C:\Users\PC\Desktop\stablenetfusion\stablenetfusion-app\py_src\binary-dependencies\avformat-58.dll
9153 WARNING: lib not found: avcodec-58.dll dependency of C:\Users\PC\Desktop\stablenetfusion\stablenetfusion-app\py_src\binary-dependencies\avformat-58.dll
11387 WARNING: lib not found: avdevice-58.dll dependency of C:\Users\PC\Desktop\stablenetfusion\stablenetfusion-app\venv\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd
11389 WARNING: lib not found: avfilter-7.dll dependency of C:\Users\PC\Desktop\stablenetfusion\stablenetfusion-app\venv\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd
11391 WARNING: lib not found: avcodec-58.dll dependency of C:\Users\PC\Desktop\stablenetfusion\stablenetfusion-app\venv\Lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd`

* Output of `pyinstaller --version`: 5.13.0
* Version of Python: 3.11.3
* Platform: Windows-10-10.0.22621-SP0
* How you installed Python: python.org/downloads

**Comment by rokm** [comment]
Those warnings are originating from the binary dependency analysis, which is not aware that you added missing DLLs to the application yourself. (But when you manually add a DLL, it undergoes the binary dependency analysis as well, which might result in additional warnings for its dependencies).

If you are manually adding DLLs from external location like that, you will likely need to add whole dependency tree (all DLLs from that directory). This will not make the warnings go away, but should ensure that the DLLs are collected nevertheless.

Alternatively, you could try adding the location (the `binary-dependencies` directory) to the `PATH` environment variable before running PyInstaller (or modify `os.environ['PATH']` at the top of your spec file) - that should allow the binary dependency analysis to find those DLLs and fix the warnings as well.

**Comment by duhoang** [comment]
> Alternatively, you could try adding the location (the `binary-dependencies` directory) to the `PATH` environment variable before running PyInstaller (or modify `os.environ['PATH']` at the top of your spec file) - that should allow the binary dependency analysis to find those DLLs and fix the warnings as well.

Having done what you suggested, the DLLs found in the PATH will warn of missing dependent DLLs also contained in that PATH. So it doesn't fix the warns in my original post.

Because of this, it's hard to understand what DLLs are truly missing to fix it.

**Comment by rokm** [comment]
Well, it works for me. With latest version of `torchaudio`, I get the following missing lib warnings during binary analysis:

```
8562 WARNING: lib not found: avformat-58.dll dependency of [...]\venv\lib\site-packages\torchaudio\lib\_torchaudio_ffmpeg.pyd
8562 WARNING: lib not found: avutil-56.dll dependency of [...]\venv\lib\site-packages\torchaudio\lib\_torchaudio_ffmpeg.pyd
9334 WARNING: lib not found: avfilter-7.dll dependency of [...]\venv\lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd
9349 WARNING: lib not found: avformat-58.dll dependency of [...]\venv\lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd
9364 WARNING: lib not found: avutil-56.dll dependency of [...]\venv\lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd
9370 WARNING: lib not found: avdevice-58.dll dependency of [...]\venv\lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd
9370 WARNING: lib not found: avcodec-58.dll dependency of [...]\venv\lib\site-packages\torchaudio\lib\libtorchaudio_ffmpeg.pyd
```

but if I download ffmpeg DLLs from https://github.com/BtbN/FFmpeg-Builds (e.g., `ffmpeg-n4.4.3-3-gb48951bd29-win64-gpl-4.4.zip`) and add `[...]\ffmpeg-n4.4.3-3-gb48951bd29-win64-gpl-shared-4.4\bin` to `PATH` before calling PyInstaller, the DLLs end up collected without warnings.

**Comment by rokm** [comment]
But as `torchaudio` wheel does not provide the ffmpeg libraries by itself, do you really need them for your program to function in the first place?

**Comment by duhoang** [comment]
> But as `torchaudio` wheel does not provide the ffmpeg libraries by itself, do you really need them for your program to function in the first place?

That's a good question. The EXE doesn't launch the Python process as expected, and those are the only Warns I get in the build process, no other errors. They might be red herrings.

Not sure how to debug the EXE otherwise.

**Comment by rokm** [comment]
> They might be red herrings. 

They very likely are.

>  The EXE doesn't launch the Python process as expected
> Not sure how to debug the EXE otherwise.

Make sure to build in onedir mode, and with console enabled. Then, if you run the exe from console (instead of double-clicking on it), it should display some run-time error message if something goes wrong.

Or are you actually trying to run python subprocesses from your EXE? That will probably not work in the PyInstaller-frozen application...

**Comment by duhoang** [comment]
> Make sure to build in onedir mode, and with console enabled. Then, if you run the exe from console (instead of double-clicking on it), it should display some run-time error message if something goes wrong

That's a good idea, let me try this.

The project is here btw if you are curious: https://github.com/duhoang/sample-sd-python-app/blob/main/py_src/main.spec
