### ISSUE TITLE
requires PIL library but it was not found in your environment.

### ISSUE THREAD

**Issue by duhoang** [pyinstaller/pyinstaller#7752]
I'm getting this error debugging an EXE:
`  File "transformers\utils\import_utils.py", line 1014, in requires_backends
    raise ImportError("".join(failed))
ImportError:
CLIPImageProcessor requires the PIL library but it was not found in your environment. You can install it with pip:
`pip install pillow`. Please note that you may need to restart your runtime after installation.`

It said that PIL was not found, but I've also added to the hidden-imports in the spec file like so:
`hiddenimports += collect_submodules('PIL')`

I can also see the PIL dir in my dist folder.

Note: the error originated from `transformers`, for some reason I had to collect data for transformers for it to be included in the dist.

`datas += collect_data_files('transformers', include_py_files=True, includes=['**/*.py'])`

* Output of `pyinstaller --version`: 5.13.0
* Version of Python: 3.10.11
* Platform:Windows-10-10.0.22621-SP0
* How you installed Python:  python.org/downloads

**Comment by rokm** [comment]
> It said that PIL was not found, but I've also added to the hidden-imports in the spec file like so: `hiddenimports += collect_submodules('PIL')`
> 
> I can also see the PIL dir in my dist folder.

Yeah, but if you look at the source of `transformers/utils/import_utils.py`, you will see that it also tries to query the package's metadata to determine whether package is available or not.

So you need `datas += copy_metadata('pillow')`.

And if you're dealing with `transformers`, you probably already had to collect metadata for other packages...

> Note: the error originated from transformers, for some reason I had to collect data for transformers for it to be included in the dist.
> `datas += collect_data_files('transformers', include_py_files=True, includes=['**/*.py'])`

Deep learning frameworks like `torch` and `tensorflow` usually require the source .py files to be available.
