### ISSUE TITLE
error: unrecognized arguments: -m torch.distributed.run -

### ISSUE THREAD

**Issue by minwim** [pyinstaller/pyinstaller#7756]
pyinstaller version: 5.13.0

YOLOV8: https://github.com/ultralytics/ultralytics.git

conda create -n v8 python=3.8

on conda environment:

I write:
_**_from ultralytics import YOLO
import argparse

def parse_argsv():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", help='YOLO mode, i.e. train, val, predict, export, track, benchmark', type=str, default='train')
    parser.add_argument("--model", help='model pre-trainned, i.e. yolov8s-seg.pt, my-seg.pt', type=str, default='/home/ultralytics/workspace/runs/segment/train5/weights/best.pt')
    parser.add_argument("--data", help='# path to data file, i.e. coco128.yaml', type=str, default='/home/data/ultralytics/workspace/yaml/infects-0529-sxyw.yaml')
    parser.add_argument("--epochs", help='number of epochs to train for ', type=int, default=2)
    parser.add_argument("--batch", help='number of images per batch (-1 for AutoBatch)', type=int, default=4)
    parser.add_argument("--imgsz", help='size of input images as integer or w,h', type=int, default=1240)
    parser.add_argument("--device", help='device to run on, i.e. cuda device=0 or device=0,1,2,3',   nargs="*", type=int, default=[0,1,2,3])
    parser.add_argument("--workers", help='number of worker threads for data loading (per RANK if DDP)', type=int, default=4)
    parser.add_argument("--patience", help='epochs to wait for no observable improvement for early stopping of training', type=int, default=150)
    arg = parser.parse_args()
    return arg

def model_train(args):
    model = YOLO(args.model)  # load a pretrained model (recommended for training)
    model.train(
                data = args.data, 
                epochs = args.epochs, 
                imgsz = args.imgsz, 
                batch = args.batch,
                device = args.device,
                workers = args.workers,
                patience = args.patience
                # resume = True
                )

if __name__ == '__main__':
    # freeze_support()
    args = parse_argsv()
    # print(vars(args))
    if args.mode == 'train':
       model_train(args)_**_

when i run **python yolov8.py --device 0 1** it can be run, multi-gpu, 
from ultralytics import YOLO
from multiprocessing import freeze_support
import argparse
import os

def parse_argsv():
    parser = argparse.ArgumentParser()
    parser.add_argument("--mode", help='YOLO mode, i.e. train, val, predict, export, track, benchmark', type=str, default='train')
    parser.add_argument("--model", help='model pre-trainned, i.e. yolov8s-seg.pt, my-seg.pt', type=str, default='/home/govion/data/wlm/ultralytics/workspace/runs/segment/train5/weights/best.pt')
    parser.add_argument("--data", help='# path to data file, i.e. coco128.yaml', type=str, default='/home/govion/data/wlm/ultralytics/workspace/yaml/infects-0529-sxyw.yaml')
    parser.add_argument("--epochs", help='number of epochs to train for ', type=int, default=2)
    parser.add_argument("--batch", help='number of images per batch (-1 for AutoBatch)', type=int, default=4)
    parser.add_argument("--imgsz", help='size of input images as integer or w,h', type=int, default=1240)
    parser.add_argument("--device", help='device to run on, i.e. cuda device=0 or device=0,1,2,3',   nargs="*", type=int, default=[0,1,2,3])
    parser.add_argument("--workers", help='number of worker threads for data loading (per RANK if DDP)', type=int, default=4)
    parser.add_argument("--patience", help='epochs to wait for no observable improvement for early stopping of training', type=int, default=150)
    arg = parser.parse_args()
    return arg

def model_train(args):
    model = YOLO(args.model)  # load a pretrained model (recommended for training)
    model.train(
                data = args.data, 
                epochs = args.epochs, 
                imgsz = args.imgsz, 
                batch = args.batch,
                device = args.device,
                workers = args.workers,
                patience = args.patience
                # resume = True
                )

if __name__ == '__main__':
    # freeze_support()
    args = parse_argsv()
    # print(vars(args))
    if args.mode == 'train':
       model_train(args)

-------------------------
when i run **python yolov8.py --device 0** or ** python yolov8.py --device 0 1" all can be run correctly

when I use **pyinstaller -D yolov8.py"
on the folder path/dist/yolov8
when I run  **./yolov8 --device 0** it can be run 
but run ** yolov8 --device 0 1** it failed

------------------------------------
erros log:
_yolov8: error: unrecognized arguments: -m torch.distributed.run --nproc_per_node 4 --master_port 47007 /home/govion/.config/Ultralytics/DDP/_temp_qn27l1xi139979813887568.py
Traceback (most recent call last):
  File "yolov8.py", line 40, in <module>
  File "yolov8.py", line 24, in model_train
  File "ultralytics/yolo/engine/model.py", line 373, in train
    self.trainer.train()
  File "ultralytics/yolo/engine/trainer.py", line 188, in train
    raise e
  File "ultralytics/yolo/engine/trainer.py", line 186, in train
    subprocess.run(cmd, check=True)
  File "subprocess.py", line 516, in run
subprocess.CalledProcessError: Command '['/home/data/ultralytics/workspace/dist/yolov8/yolov8', '-m', 'torch.distributed.run', '--nproc_per_node', '4', '--master_port', '47007', '/home/.config/Ultralytics/DDP/_temp_qn27l1xi139979813887568.py']' returned non-zero exit status 2._

**Comment by bwoodsend** [comment]
Is yolo not able to use `multiprocessing` for its multiprocessing? PyInstaller does not provide the `python` executable so DIY subprocessing like this isn't going to work otherwise.

**Comment by bwoodsend** [comment]
You might be able to spoof your way through by handling the subprocess path yourself – detecting those command line arguments and calling [torch.distributed.run.main()](https://github.com/pytorch/pytorch/blob/6bfd507c15f2d26212d3e2b9e581d9525bfd37d1/torch/distributed/run.py#L795).

```python
# Put at the top of your main script
if sys.argv[1:3] == ["-m", "torch.distributed.run"]:
    from torch.distributed.run import main
    main(sys.argv[3:])
    sys.exit(0)
```

**Comment by minwim** [comment]
thanks@bwoodsend
