### ISSUE TITLE
--debug should be honored with spec file

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#776]
**Original date**: 2013/09/19
**Original reporter**: *davecortesi AND gmail DOT  COOM *

It appears that the --debug command line option is ignored when the input is a .spec file. If I call pyinstaller --debug myscript.py, the generated spec file has DEBUG=True and whenever that spec file is used, the loader is in debug mode.

However if the input is myscript.spec containing DEBUG=False, then the --debug command line option is ignored.

The command line option should override the spec file contents so that one can build a debug module using an existing, tested spec file. The present alternative is to have two spec files, or to edit the spec file twice, once to set DEBUG=True and once to put it back to the normal False.

**Comment by htgoebel** [comment]
As of PyInstaller 3.0, if you run PyInstaller on the main script, it generates a new .spec-file with the correct `debug` value. If you are running PyInstaller on the .spec-file, the .spec-file of course is untouched.
