### ISSUE TITLE
No such file or directory: '5'

### ISSUE THREAD

**Issue by Zibri** [pyinstaller/pyinstaller#7768]
$ pyinstaller --onefile ./stat.py
305 INFO: PyInstaller: 5.12.0
306 INFO: Python: 3.8.10
326 INFO: Platform: Linux-4.4.0-19041-Microsoft-x86_64-with-glibc2.29
6117 INFO: wrote /mnt/g/pyusbtap/stat.spec
6127 INFO: UPX is available.
6131 INFO: Extending PYTHONPATH with paths
['/mnt/g/pyusbtap']
Fatal Python error: init_import_size: Failed to import the site module
Python runtime state: initialized
Traceback (most recent call last):
  File "/usr/lib/python3.8/site.py", line 79, in <module>
    import os
  File "/usr/lib/python3.8/os.py", line 27, in <module>
    import stat as st
  File "/mnt/g/pyusbtap/stat.py", line 21, in <module>
    f = open(fname, "rb")
FileNotFoundError: [Errno 2] No such file or directory: '5'
T

**Comment by rokm** [comment]
> $ pyinstaller --onefile ./stat.py

> ```
> File "/usr/lib/python3.8/site.py", line 79, in
> import os
> File "/usr/lib/python3.8/os.py", line 27, in
> import stat as st
> ```

Your entry-point script (`stat.py`) is shadowing the python's `stat` module, so it is being imported during the analysis. Rename it to something else.

**Comment by Zibri** [comment]
ohhh I see... nice catch...  perhaps this should be addressed in the program if possible.
