### ISSUE TITLE
pyinstaller try to copy linux library on windows platform

### ISSUE THREAD

**Issue by ChangmingTian** [pyinstaller/pyinstaller#7775]
```python
 if platform.system().lower() == "windows":
            if struct.calcsize("P") * 8 == 32:
                self.jlink = CDLL("JLinkARM.dll", winmode=0)
            else:
                self.jlink = CDLL("JLink_x64.dll", winmode=0)
        elif platform.system().lower() == "linux":
            if struct.calcsize("P") * 8 == 32:
                self.jlink = CDLL("libjlinkarm_x86.so")
            else:
                self.jlink = CDLL("libjlinkarm.so")
```
When I run pyinstaller on windows platform,Got error:
cp: cannot create symbolic link 'libjlinkarm_x86.so': No such file or directory
I do not need pyinstaller copy linux library to package on windows platform.
How to make pyinstaller distinguish between linux and windows???

**Comment by bwoodsend** [comment]
What's the full error message? Is it an error or just a warning?

PyInstaller automatically detects use of `ctypes` but can't evaluate all the `if platform.system() ...` conditionals statically so what should happen is that PyInstaller tries to collect all those libraries, is only able to collect one because only the native platform one exists, then issue warnings for the rest which you can safely ignore.

**Comment by ChangmingTian** [comment]
> is only able to collect one because only the native platform one exists, then issue warnings for the rest which you can safely ignore.

```
cp: cannot create symbolic link './libjlinkarm.so': No such file or directory
cp: cannot create symbolic link './libjlinkarm.so.7': No such file or directory
cp: cannot create symbolic link './libjlinkarm_x86.so': No such file or directory
make: *** [Makefile:87: dist/a.exe] Error 1
```
libjlinkarm.so is a linux soft link file,that's why the cp cmd failed on windows platform.
I have to keep some private libraries(linux and windows version) with my python projec.
It seems python not support statically condition as C/C++ #ifdef __win32__.
Is there a way to set PyInstaller ignore linux libraries on windows platform?

**Comment by bwoodsend** [comment]
I fail to see why a broken Makefile has anything to do with PyInstaller.
