### ISSUE TITLE
Exclude Gstreamer from the search of binaries

### ISSUE THREAD

**Issue by Raizencorp** [pyinstaller/pyinstaller#7781]
Hi,

So i'm developping a app that need a specific version of some binaries, that i get from GTK3. But gstreamer also has them and it seem that they are always collected from both because GTK3 get the prefix "lib" and not gstreamer.

I already uninstalle Gstreamer and it work just fine. But the point is to be able to have Gstreamer installed on the same PC

And as a matter of fact, the others packages tries to open the binaries without the "lib" prefix first.

So i would like to block the access og my gstream but it seems the excludes = ['gstreamer'] (or directly the path)
doesn't have any effect.

I even used the upx_exclude the but with "gstreamer\*" and the path. But it keep retrieving it.

**Comment by bwoodsend** [comment]
Which binaries specifically? Which OS (presumably Linux)? Is gstreamer from a system package or one of the gstreamer wrappers on PyPI or compiled from source? I'd expect it to be a system package but then it and GTK should be dynamically linked and you should therefore only have one copy of whatever these binaries are.

We're not likely to create a feature specifically for gstreamer but you should be able to achieve this by filtering/modifying `a.binaries` in the spec file before it's passed to `COLLECT()`.

**Comment by bwoodsend** [comment]
If you run `tree` in the root of you build and then post that annotating which libraries you want replaced/removed, that would make this a lot clearer.

**Comment by Raizencorp** [comment]
Oh my bad, here is everything:
-Windows 10 64bit
- pangotf2-1.0-0 and pango-1.0-0(but it's best to get rid of every binaries so there is no other conflict in the future)

as i said, the problem with gstreamer and GTK3 is the nomenclature of the files. GTK3 name every binaries with the prefix 'lib' so i get libpango-1.0-0 from GTK3 and pango-1.0-0 from gstreamer. And it's the one without 'lib' that is prioritize by the other packages.

Sure thing, i wasn't asking something specific for gstreamer. I'm pretty sure this is a one case in all due to the compatibility of everything. But maybe have a exclude that would exclude from the COLLECT() as you mention.

But isn't a.binaries only use to get ? Can it also exclude ? 
and what about the hooks specified for gstreamer ? i tried to remove them from the rthooks.dat but nothing really changed

**Comment by rokm** [comment]
> libpango-1.0-0 from GTK3 and pango-1.0-0 from gstreamer

If that is the case, aren't your gtk3 libs referencing `libpango-1.0-0` and your gstreamer libs referencing `pango-1.0-0`? If these are link-time dependencies, they are not interchangeable due to different names and their references, and binary dependency analysis is correct to pick both of them up. It is up to you to ensure you are using compatible gtk3 and gstreamer builds (i.e., using same naming scheme).

But if you want to try to work-around this at PyInstaller level, the only way to filter out binaries is to filter `Analysis.binaries` in the .spec file, before they are passed on to EXE and COLLECT.
