### ISSUE TITLE
sys.stderr is NoneType using --windowed option on Windows

### ISSUE THREAD

**Issue by T-Born** [pyinstaller/pyinstaller#7782]
freezing my app using --windowed mode used to work fine. Now running the build app crashes because sys.stderr is None.

minimal example migth be (main.py): 
```
import sys

if __name__ == '__main__':
    sys.stderr.write("test")
```

build command: `pyinstaller --name test --onedir --windowed main.py`

running built leads to: 
```
Traceback (most recent call last):
  File "main.py", line 4, in <module>
AttributeError: 'NoneType' object has no attribute 'write'
```

* Output of `pyinstaller --version`: 5.13.0
* Version of Python: 3.10.11
* Platform: Windows 10
* How you installed Python: Windows store
* Did you also try this on another platform? no

**Comment by rokm** [comment]
`sys.stdout` and `sys.stderr` are `None` in windowed/noconsole mode, same as if you ran your code in windowed python interpreter (`pythonw.exe`). See [the note in python docs](https://docs.python.org/3/library/sys.html#sys.__stderr__).

**Comment by rokm** [comment]
This behavior changed in [PyInstaller 5.7](https://pyinstaller.org/en/v5.7.0/CHANGES.html#incompatible-changes) - it is now up to users to deal with naive code that expects the streams to be always available. For an example, see https://github.com/pyinstaller/pyinstaller/issues/7334#issuecomment-1357447176.

**Comment by T-Born** [comment]
Thanks @rokm.
