### ISSUE TITLE
Possible regression for Bottle clients on Windows with pyinstaller >= 3.7

### ISSUE THREAD

**Issue by NathanRichard** [pyinstaller/pyinstaller#7786]
## Description of the issue

When an application importing the bottle package is built using pyinstaller 5.7.0 under windows with console=False, it fails at startup with:

`
File "bottle.py", line 73, in <module>
AttributeError: 'NoneType' object has no attribute 'write'
`

According to [this source code,](https://github.com/bottlepy/bottle/blob/40aec5d4cca6ff4fbd73f4080554580fe4f5c212/bottle.py#L73)  bottle expects both sys.stdout and sys.stderr to have a ".write" attribute.

I suspect it is related to ([#3503](https://github.com/pyinstaller/pyinstaller/issues/3503)).

Note : for years we have been building our application with (console=False, windowed=True) under windows. It includes a webserver (bottle) and can be invoked both using cli and gui. Historically we used console=False because console=True conflicted with our gui framework under windows 7.

In case this new behavior is expected, can you comment on the potential impact of using (console=True, windowed=True) for a windows application ? [According to the documentation,](https://pyinstaller.org/en/stable/usage.html#windows-and-mac-os-x-specific-options) they seem to be exclusive (ie windowed implies noconsole).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.7.0``` (the issue is also at least in 5.8 and 5.13)
* Version of Python: 3.8
* Platform: Windows 7 and Windows 10 (Fr)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? No issue on Linux and MacOS.

### A minimal example program which shows the error

Client application:
```python
import bottle

print("Hello world")
```
Spec file (default generated, except for (console=False, windowed=True)
```python
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['bottle_client.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='bottle_client',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    console=False,
    windowed=True,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='bottle_client',
)

```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "bottle_client.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 499, in exec_module
  File "bottle.py", line 73, in <module>
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by rokm** [comment]
> According to [this source code,](https://github.com/bottlepy/bottle/blob/40aec5d4cca6ff4fbd73f4080554580fe4f5c212/bottle.py#L73) bottle expects both sys.stdout and sys.stderr to have a ".write" attribute.

Then this is a bug in `bottle`. `sys.stdout` and `sys.stderr` may be `None` if console is not available, as per [python docs](https://docs.python.org/3/library/sys.html#sys.__stderr__).

PyInstaller used to provide dummy writer objects for `sys.stdout` and `sys.stderr` in windowed mode, but we [removed that in 5.7](https://pyinstaller.org/en/stable/CHANGES.html#id25) in order to match the behavior of windowed python interpreter (`pythonw.exe`).

So if you have code that naively assumes that streams are always available, you should deal with it yourself. Either by fixing it, or by providing your own dummy streams - for an example, see https://github.com/pyinstaller/pyinstaller/issues/7334#issuecomment-1357447176.

**Comment by NathanRichard** [comment]
Hello rokm,

Thank you for your quick reply.

Indeed bottle expects the process to be connected to a console. As I am not a bottle maintainer myself I cannot tell if it is a bug or an undisclosed requirement.

However, I understand that pyinstaller cannot be fine tuned for each python package ; in some case it is even impossible because the package in questions have conflicting requirements (`bottle` and `click` in this example).

I will keep in mind the fix of providing my own dummy streams : but what about applications that require _both_ a console and gui output ? Shouldn't pyinstaller provide native support for that use case ? Then could we consider using `console=True, windowed=True` ?

**Comment by rokm** [comment]
> I will keep in mind the fix of providing my own dummy streams : but what about applications that require _both_ a console and gui output ? Shouldn't pyinstaller provide native support for that use case ? Then could we consider using `console=True, windowed=True` ?

There are two types of win32 executables; those that are compiled with [`CONSOLE` subsystem](https://learn.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170) ("console" applications) and those that are compiled with [`WINDOWS` subsystem](https://learn.microsoft.com/en-us/cpp/build/reference/subsystem-specify-subsystem?view=msvc-170), without console attached ("windowed" or "noconsole" applications). Both types of application can display GUI.

There is no `windowed=True` argument anywhere in PyInstaller. `--noconsole` and `--windowed` command-line switches set `console=False` (= application has no console attached) - which causes PyInstaller to use bootloader executable that was compiled with WINDOWS subsystem. `--console` and `--nowindowed` command-line switches set `console=True` - which causes PyInstaller to use bootloader that was compiled with CONSOLE subsystem.

**Comment by NathanRichard** [comment]
Ok, I was mislead by the fact that it is possible to set `console=True, windowed=True` in a .spec file.
Thank you for your reply.
Best regards
