### ISSUE TITLE
Problem using tabula

### ISSUE THREAD

**Issue by EmeleanM** [pyinstaller/pyinstaller#7791]
I currently have a program that uses Tabula-py as a library, where I import tabula and use the read_pdf function. The pyinstaller manages to compile the program but when executed it generates a specific error, I would like to know the list of libraries currently compatible with the pyinstaller.

Traceback (most recent call last):
  File "FrankWinstoncrum_original-Copy1.py", line 60, in <module>
  File "tabula\io.py", line 425, in read_pdf
  File "tabula\io.py", line 88, in _run
  File "subprocess.py", line 526, in run
subprocess.CalledProcessError: Command '['java', '-Dfile.encoding=UTF8', '-jar', 'C:\\Users\\56959\\AppData\\Local\\Temp\\_MEI137962\\tabula\\tabula-1.0.5-jar-with-dependencies.jar', '--pages', 'all', '--guess', 'C:/Users/56959/Downloads\\METROP1260_Metropolitan_Insurance_LLC_23_07_18 17_37_13_37.pdf']' returned non-zero exit status 1.

**Comment by bwoodsend** [comment]
`--collect-data=tabula`

**Comment by EmeleanM** [comment]
Thanks, it work!
