### ISSUE TITLE
[Windows] Setting PYINSTALLER_COMPILE_BOOTLOADER didn't recompile bootloader.

### ISSUE THREAD

**Issue by Blank-c** [pyinstaller/pyinstaller#7792]
I have gcc (added to PATH) and visual c/c++ installed.
I set the environment variable to value `1`, but pyinstaller didn't reompile the bootloader when installing from pip (`pip install pyinstaller`).
Am I doing something wrong?

**Comment by rokm** [comment]
You'll probably need to add `--no-binary pyinstaller` to your `pip` command to force installation from sdist.

**Comment by Blank-c** [comment]
Tried `pip install pyinstaller --no-binary all`, didn't work.

**Comment by Blank-c** [comment]
Nope, it just built the wheel but not the bootloader.

**Comment by rokm** [comment]
Can we see the complete command that you are using, then?

**Comment by Blank-c** [comment]
```powershell
(env) C:\Users\sauha\Desktop\Test\env\Scripts>pip install pyinstaller --no-binary pyinstaller
Collecting pyinstaller
  Using cached pyinstaller-5.13.0-py3-none-any.whl
Requirement already satisfied: setuptools>=42.0.0 in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (65.5.0)
Requirement already satisfied: altgraph in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (0.17.3)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (2023.6)
Requirement already satisfied: pefile>=2022.5.30 in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (2023.2.7)
Requirement already satisfied: pywin32-ctypes>=0.2.1 in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (0.2.2)
Installing collected packages: pyinstaller
Successfully installed pyinstaller-5.13.0

[notice] A new release of pip is available: 23.1.2 -> 23.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

(env) C:\Users\sauha\Desktop\Test\env\Scripts>where gcc
C:\MinGW\bin\gcc.exe

```

**Comment by rokm** [comment]
>   Using cached pyinstaller-5.13.0-py3-none-any.whl

You also need to disable cache... `--no-cache-dir`.

**Comment by Blank-c** [comment]
didn't work
```powershell
Collecting pyinstaller
  Downloading pyinstaller-5.13.0.tar.gz (4.1 MB)
     ---------------------------------------- 4.1/4.1 MB 1.8 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: setuptools>=42.0.0 in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (65.5.0)
Requirement already satisfied: altgraph in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (0.17.3)
Requirement already satisfied: pyinstaller-hooks-contrib>=2021.4 in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (2023.6)
Requirement already satisfied: pefile>=2022.5.30 in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (2023.2.7)
Requirement already satisfied: pywin32-ctypes>=0.2.1 in c:\users\sauha\desktop\test\env\lib\site-packages (from pyinstaller) (0.2.2)
Building wheels for collected packages: pyinstaller
  Building wheel for pyinstaller (pyproject.toml) ... done
  Created wheel for pyinstaller: filename=pyinstaller-5.13.0-py3-none-any.whl size=2042511 sha256=0cf98de1230feaffa7bf6e91045e3935a657fdd665a8c70ef28169163ee609bc
  Stored in directory: C:\Users\sauha\AppData\Local\Temp\pip-ephem-wheel-cache-2twslqzq\wheels\eb\af\65\6d12858f2f2516d557429539329ae3ae4b5bff1e9f7c337f0b
Successfully built pyinstaller
Installing collected packages: pyinstaller
Successfully installed pyinstaller-5.13.0
```

**Comment by rokm** [comment]
And if you add `--verbose` to your `pip` command?

**Comment by Blank-c** [comment]
Oh wait it did compile. How can I force gcc?

**Comment by rokm** [comment]
> Oh wait it did compile. How can I force gcc?

I don't think you can with direct `pip` install. 

You'll need to download the sdist archive yourself, and unpack it (let's say the top-level unpacked directory is called `pyinstaller-5.13.0`). Then `cd pyinstaller-5.13.0/bootloader` and run `python waf all --gcc`. And then install using `pip install ..` (if ran from `bootloader` directory) or `pip install .` (if ran from top-level directory).

**Comment by Blank-c** [comment]
Oh I understand. Thank you for helping. Have a nice day.

**Comment by Blank-c** [comment]
Also, one last question. Does running waf auto replaces the bootloader binaries or do we have to copy each one?
I mean if I clone the repo and run waf, and then after that I do `pip install -e .`, will the new bootloader be used?

**Comment by rokm** [comment]
> Also, one last question. Does running waf auto replaces the bootloader binaries or do we have to copy each one? I mean if I clone the repo and run waf, and then after that I do `pip install -e .`, will the new bootloader be used?

If you install in editable mode, then new bootloaders are automatically available when you rebuild them (`waf` copies them into `PyInstaller/bootloader/...`).

**Comment by bwoodsend** [comment]
> Oh wait it did compile. How can I force gcc?

Running `set CC=gcc` before the pip install should do it?

**Comment by rokm** [comment]
> > Oh wait it did compile. How can I force gcc?
> 
> Running `set CC=gcc` before the pip install should do it?

Not if MSVC can be found in the environment.
