### ISSUE TITLE
Pyinstaller not working with Vosk

### ISSUE THREAD

**Issue by arvindmn01** [pyinstaller/pyinstaller#7795]
I have created exe file using Pyinstaller. i am using vosk in the backend but when i open the exe file it gives me this error.
![Screenshot 2023-07-28 145322](https://github.com/pyinstaller/pyinstaller/assets/100796728/324fb357-f96e-4739-bfeb-30f273f71324)

**Comment by rokm** [comment]
Please do not open duplicate issues/discussions.
