### ISSUE TITLE
Compiling bootloader for M1 on Intel Mac

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#7810]
I am on an Intel mac with MacOS 13. I tried compiling boot-loader for M1, but it does not seem to work. 

I did:
```
CC='clang -arch=arm64' python waf --no-universal2 all
```

I get:
```
clang: warning: argument unused during compilation: '-arch=arm64' [-Wunused-command-line-argument]
```

clang version: 
```
Apple clang version 14.0.3 (clang-1403.0.22.14.1)
```

can someone pls tell me how to build it? 
i eventually want to build a binary from my x86 host, and run that binary on M1

**Comment by rokm** [comment]
You cannot use PyInstaller to build an `arm64` application on Intel Mac, because that requires an active `arm64` python environment. So there's little point in trying to compile a pure `arm64` bootloader.

**Comment by rokm** [comment]
But to answer your question, the `clang` argument should be `-arch arm64`, not `-arch=arm64`.

**Comment by ghost** [comment]
@rokm , on the official site it says `-arch=arm64` 
https://pyinstaller.org/en/stable/bootloader-building.html

I thought it said we can also build universal2 bootloader and binaries from pyinstaller. How does that work?

**Comment by rokm** [comment]
> @rokm , on the official site it says `-arch=arm64` https://pyinstaller.org/en/stable/bootloader-building.html

Tthat needs to be corrected, then...

> I thought it said we can also build universal2 bootloader and binaries from pyinstaller. How does that work?

The `universal2` bootloader is built by default. And the pre-compiled bootloader is also `universal2`, so you don't need to build it yourself (unless you have a good reason to do so).

As for `universal2` applications - that's possible only if your python is `universal2` and if all non-pure-python packages you are using are also `universal2`. If that is not the case, you can build only for the architecture that matches the python environment in which you are running PyInstaller. See [the docs](https://pyinstaller.org/en/stable/feature-notes.html#macos-multi-arch-support).

**Comment by ghost** [comment]
Thanks a lot, I am trying to setup a CI/CD automated builds. Most of the CI/CD tools dont support M1 hardware, so it would be good to have some way build M1 apps on Intel hardware.

**Comment by bwoodsend** [comment]
cirrus-ci supports M1: https://cirrus-ci.org/guide/macOS/

**Comment by ghost** [comment]
@rokm I have the exact list of all the python packages i need, and i have all those packages with me. I also have the bootloader built for m1 ready with me. 
Now is there any way i can build the my app, without acutally executing the py script?

**Comment by rokm** [comment]
> @rokm I have the exact list of all the python packages i need, and i have all those packages with me. I also have the bootloader built for m1 ready with me. Now is there any way i can build the my app, without acutally executing the py script?

Not with PyInstaller; since PyInstaller collects files from the python environment in which it is running.
