### ISSUE TITLE
My .exe closes automatically after opening it and there is no error in my code

### ISSUE THREAD

**Issue by Tzubay** [pyinstaller/pyinstaller#7819]
Until a few weeks ago I made my code in python and used pyinstaller to create an .exe of my code and it always worked perfectly, until today when I tried it again and even if I create the .exe it closes right after being opened.

My code, even if it is a simple print("Hello world"), when converted to an .exe with pyinstaller, the window closes without even showing anything on the screen, this had never happened before.

* Output of `pyinstaller --version`: ```(5.13.0)```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there? I tried on another pc, another version of python, and the error persists

I hope you know a solution to this problem, thank you very much

**Comment by rokm** [comment]
> the window closes without even showing anything on the screen

What window - the console one? Are you running the .exe by double-clicking on it? If that is the case, what if you open a command prompt (cmd.exe) and run your .exe from there?

**Comment by Tzubay** [comment]
yes, the console closes
(to create the .exe I use pyinstaller --onefile "Name_of_my_code")

From the CMD the .exe executes correctly (to test I am using only a print with the message "hello world") and executing it from cmd the message appears correctly, it only fails opening the .exe with double click, the console window almost closes Instantly.

**Comment by rokm** [comment]
> From the CMD the .exe executes correctly (to test I am using only a print with the message "hello world") and executing it from cmd the message appears correctly, it only fails opening the .exe with double click, the console window almost closes Instantly.

What else do you expect for a `print('Hello world')` application to do if you double click on it? It opens console, prints its message, and closes the console as it exits...

**Comment by Tzubay** [comment]
It's an example, it's not supposed to close automatically, the same thing happens if I do anything else, for example a data entry, it doesn't leave time to enter any data, it just closes, it doesn't do anything else

**Comment by rokm** [comment]
> It's an example, it's not supposed to close automatically,

A hello-world example *is* supposed to close automatically when it exits (which is almost immediately). 

But the same will happen if your program is interrupted due to unhandled exception. So running the .exe by double-clicking on it is not going to help you in debugging the problem.

**Comment by Tzubay** [comment]
ohh, I understand, thanks
Is there a way to prevent the console window from closing automatically when the program "terminates"?

**Comment by rokm** [comment]
>  Is there a way to prevent the console window from closing automatically when the program "terminates"?

There is not. If the program owns the console window (is not launched from an existing console), the window is closed when the program terminates.

**Comment by Tzubay** [comment]
you helped me a lot, thank you very much, you are great ;)
