### ISSUE TITLE
Importing scipy.signal with onefile option produces WARNING..... pyconfig.h already exists

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#782]
**Original date**: 2013/09/25
**Original reporter**: *jonnojohnson AND gmail DOT  COOM *

If I create a script with only the line:

```
import scipy.signal
```

and build with the -F option I get the following warning when launching the exe:

```
WARNING: file already exists but should not: C:\Users\...\Include\pyconfig.h
```

I've seen this in other versions but definitely in: 2.1dev-e958e02

**Comment by JohnyMoSwag** [comment]
I'm seeing the same on 2.1 & development branch

**Comment by smartswdeveloper** [comment]
Problem solved with :
    Go to C:\Python27\Lib\site-packages\PyInstaller\build.py
    Find the def append(self, tpl): function.
    Change if tpl[2] == "BINARY": to if tpl[2] in ["BINARY", "DATA"]:
Source http://stackoverflow.com/questions/19055089/pyinstaller-onefile-warning-pyconfig-h-when-importing-scipy-or-scipy-signal
