### ISSUE TITLE
Problem with greenlet, again

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#784]
**Original date**: 2013/09/30
**Original reporter**: *q AND imap DOT ch*

I'm trying to create a package for a project that uses `greenlet`, but pyinstaller won't include it in the package whatsoever. I found a similar ticket #242 where the case could apparently be resolved by importing the `greenlet` module somewhere else in the code. I tried that but with no success. I can plaster my code all over with import statements, pyinstaller won't include the egg in the package. If I copy it manually, either the whole egg or just the .pyd in it, it works. I also used `--hidden-import=greenlet` and pyinstaller somewhere states that

```
  7847 INFO: Hidden import 'greenlet' has been found otherwise"
```

In contrast to #242, I use `eventlet`. I also used `--hidden-import=eventlet` and `--hidden-import=eventlet.support` (the module that really imports `greenlet`). I also wrote a hook that did a import of `eventlet`, `eventlet.support` and `greenlet`. The .toc files all mention `greenlet`, however it's still missing in the `eggs` directory.

I guess that fact that I can't find eventlet (a .egg directory) is due to `eventlet` being included in the pyz archive.

I have attached the whole `build` as a `.tar.gz` directory where I also have put the `.BAT` file with the pyinstaller commands, the hook module and the generated `.spec` file.

**Comment by matysek** [comment]
If this problem still persists, report a new issue.
