### ISSUE TITLE
locale not identified within macOS .app bundle

### ISSUE THREAD

**Issue by gernophil** [pyinstaller/pyinstaller#7841]
Hey,
I've ported an app based on Python from Windows to macOS. I can run the app from command line and I was also able to make an `.app` file and start it on my mac using `PyInstaller`. One thing that does not work in the `.app` bundle somehow is to get the locale via `locale.getdefaultlocale()[0][0:2]`. If I build the app and start it via command line from the app folder (not the `.app` file), everything works and the app starts in the language of my macOS. However, if I start the `.app` bundle via double click, the app is always in English. Any ideas, how I can read the locale within an `.app` bundle?
Thanks for you help :)

**Comment by rokm** [comment]
That's because when you launch .app bundle from Finder via double-click, you get limited environment in which `LANG` is not set, and hence default locale cannot be determined. If you want to get user's locale on macOS, you will likely need to use its own API for that.

**Comment by gernophil** [comment]
Thanks for you reply. I know that's none of `PyInstaller`'s business, but could you give me an hint on how to do that?

**Comment by rokm** [comment]
Maybe https://github.com/orgs/pyinstaller/discussions/6378#discussioncomment-1672768?

**Comment by gernophil** [comment]
Perfect, that was the solution:
```
import Foundation  # pyobjc
sud = Foundation.NSUserDefaults.standardUserDefaults()
locale = sud.stringForKey_('AppleLocale')
```
Thanks a lot :).
