### ISSUE TITLE
MacOS application opening, closing, and then opening again

### ISSUE THREAD

**Issue by jcovin293** [pyinstaller/pyinstaller#7845]
I have built my application for MacOS using PyInstaller. When I open my application, it seems to be loading in the application bar and then closes. It will then open again and successfully open. This is confusing and makes it seems that this application is crashing on load.

**Comment by rokm** [comment]
Is this a onefile or onedir build?

**Comment by jcovin293** [comment]
This has occurred on a onefile build.

**Comment by rokm** [comment]
Then that's the expected behavior.
