### ISSUE TITLE
OS error: could not get source code

### ISSUE THREAD

**Issue by Karthik-2002-git** [pyinstaller/pyinstaller#7851]
![dsshow issue](https://github.com/pyinstaller/pyinstaller/assets/85507271/a9d02ab7-b0b2-495e-a8a3-e8bce6e402c4)

## Description of the issue
I have converted my pyqt5 project into exe using pyinstaller. The project has alot of library imports and one among that is the 'dshow' function of the 'datashader.mpl_ext' library (used for data visualization). Whenver the converted exe app invokes the dsshow function, it gets crashed. I also tried adding 'datashader.mpl_ext' and 'datashader' in hidden imports, but still the app crashes while calling the dsshow  function. Is this a bug and how do I resolve this?
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.13.0```
* Version of Python: 3.9.13
* Platform: Windows
* How you installed Python: PyCharm
* Did you also try this on another platform? Does it work there?No

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
If the error you are getting is `OS error: could not get source code`, then you need to ensure that the source .py files are collected for whatever package requires them. PyInstaller does not collect source files by default; only byte-compiled .pyc modules...

**Comment by Karthik-2002-git** [comment]
I have installed matplotlib, sklearn, pandas, numpy, etc via pip. They all workfine. But the dsshow function of the datashader library causes the exe to crash. The app works fine when run in PyCharm.

**Comment by Karthik-2002-git** [comment]
****

> If the error you are getting is `OS error: could not get source code`, then you need to ensure that the source .py files are collected for whatever package requires them. PyInstaller does not collect source files by default; only byte-compiled .pyc modules...

How do i get the source.py of datashader and ensure it gets collected?

**Comment by rokm** [comment]
> > If the error you are getting is `OS error: could not get source code`, then you need to ensure that the source .py files are collected for whatever package requires them. PyInstaller does not collect source files by default; only byte-compiled .pyc modules...
> 
> How do i get the source.py of datashader and ensure it gets collected?

Using [`module_collection_mode`](https://pyinstaller.org/en/stable/hooks.html#hook-global-variables), either in a custom hook, or as a dictionary in .spec file that you pass to the `Analysis` instance.

For example, edit your .spec file and add `module_collection_mode` as the last keyword argument to the `Analysis`:
```
a = Analysis(
    ...
    module_collection_mode={
        'datashader': 'pyz+py',
    },
)
```

Then rebuild your program using the .spec file instead of the original .py file (as to not overwrite the edited .spec).
