### ISSUE TITLE
Data that is added via --add-data is not getting signed (correctly)

### ISSUE THREAD

**Issue by gernophil** [pyinstaller/pyinstaller#7852]
Hey,

it's me again. Hopefully, this time it's a real bug and not just me nit searching deep enough. However, I did not find any information regarding this. I have this small macOS app (https://github.com/gernophil/noScribe) from that I built an `.app` using `PyInstaller`. The good thing is I was able to sign and notarize it completely, but only with some manual steps after `PyInstaller`. After the first failed notarization try the log showed around 50 files with invalid or missing codesign in the notarization log file. All these files belong to modules that I manually added using `--add-data`. After PyInstaller is finished I need to remove all the `xattr` using `xattr -cr macOSapp.app` (this step seems to be optional, though), resign these 50 manually and then sign the whole `.app` bundle again. After this I can notarize my app. It seems like data added with --add-data is not properly signed.

**Comment by rokm** [comment]
Files added via `--add-data` are treated as data files, and placed into `Contents/Resources` in macOS .app bundles. Therefore, they do not get signed automatically (neither during PyInstaller's processing of collected binaries, nor when final .app bundle gets deep-signed). 

At least in the current PyInstaller releases; in upcoming v6, we will try to automatically reclassify files in case someone is mistakenly adding binaries via `--add-data`...
