### ISSUE TITLE
How to manually build using pyinstaller?

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#7861]
Say i have already have all the .pyc files and all native .so/.dylib files of all the modules with me. 
How to manually compile to an executable, if i already have the bootloader. 

I am trying to build for m1 on an intel machine. 
Thats why i do not want to execute the script for analysis. 
Basically i realized that the .pyc or .pyz files are same for both intel and M1, only native .so/.dylib are different. so i just want to manually bundle the .pyc files and native modules with the m1 bootloader. 

If i have an existing executable built with pyinstaller, is there any way i can patch / add more .pyc files in it?

**Comment by rokm** [comment]
I suppose you would have to write a different tool that performs same executable construction steps that PyInstaller does; possibly re-using the PyInstaller code.

Since that is out of scope of PyInstaller itself, don't expect any support from us in that endeavor, though.

**Comment by bwoodsend** [comment]
Hand stitching things together isn't going to make cross compiling any more feasible.
