### ISSUE TITLE
After double-clicking on Mac M1, the icon appears briefly and then disappears

### ISSUE THREAD

**Issue by cikichen** [pyinstaller/pyinstaller#7862]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.13.0```
* Version of Python: 3.11.3
* Platform: OS X（Mac M1）
* How you installed Python: pyenv
* Did you also try this on another platform? Does it work there?
101 INFO: PyInstaller: 5.13.0
101 INFO: Python: 3.11.3
107 INFO: Platform: macOS-13.4.1-arm64-arm-64bit

pyinstaller main.spec --noconfirm
```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files

datas = [('files', 'files'), ('languages.json', '.'), ('app', 'app')]
datas += collect_data_files('sv_ttk')
#hiddenimports = ['flask']
hiddenimports = ['requests']
block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='my',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    version='file_version_info.txt',
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch='arm64',
    codesign_identity=None,
    entitlements_file=None,
    uac_admin=True,
    icon=['icon/icon.ico'],
)
app = BUNDLE(
    exe,
    name='my.app',
    icon='icon/icon.icns',
    bundle_identifier=None,
)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
If the icon appears and disappears (without re-appearing again), the program terminated due to unhandled exception.
What if you run the bundle's executable from terminal (`./my.app/Contents/MacOS/my`)  - does that show any errors?

Also note that there is no point in building `onefile` macOS .app bundles; you should use `onedir` mode instead (especially if you plan to codesign/notarize it).

**Comment by cikichen** [comment]
> If the icon appears and disappears (without re-appearing again), the program terminated due to unhandled exception. What if you run the bundle's executable from terminal (`./my.app/Contents/MacOS/my`) - does that show any errors?
> 
> Also note that there is no point in building `onefile` macOS .app bundles; you should use `onedir` mode instead (especially if you plan to codesign/notarize it).
@rokm 
```
cd my.app/Contents/MacOS/my
./my
```
work fine! but double-clicking icon not work.

**Comment by rokm** [comment]
> > If the icon appears and disappears (without re-appearing again), the program terminated due to unhandled exception. What if you run the bundle's executable from terminal (`./my.app/Contents/MacOS/my`) - does that show any errors?
> > Also note that there is no point in building `onefile` macOS .app bundles; you should use `onedir` mode instead (especially if you plan to codesign/notarize it).
> 
> ```
> cd my.app/Contents/MacOS/my
> ./my
> ```
> 
> work fine!

What if you do not cd into the .app bundle's directory (or any of its sub-directories)?

**Comment by cikichen** [comment]
Double-click the .app file, the icon appears on the dock for a few seconds, then disappears, the UI won't show up. @rokm

**Comment by cikichen** [comment]
By the way, the compiled .exe works fine on Windows.

**Comment by rokm** [comment]
> Double-click the .app file, the icon appears on the dock for a few seconds, then disappears, the UI won't show up. @rokm

Like I said, it probably terminates due to unhandled exception - the icon appears when the bootloader starts, and when it reaches your program code, it terminates.

Does your program include any files that you are trying to load, and you are using relative path to reference them? (That's why I am asking what happens if you do not cd into directory next to executable).

But you could also try wrapping your whole program into global `try/except` block, and write the exception information to a file.

**Comment by rokm** [comment]
Alternatively, if it works when you run it from the terminal (regardless of whether you cd into the directory next to executable or not) but not when you double click on it in Finder, you might be using some functions that have unexpected return values when ran in limited shell environment (for example `locale.getlocale()`).

But without seeing the code, I cannot really help you. It's probably best if you try to add a global `try/except` block to your program, and log the exception to a file.

**Comment by cikichen** [comment]
```
import base64
import json
import locale
import logging
import os
import platform
import re
import subprocess
import sys
import threading
import time
import tkinter
import webbrowser
from http.server import HTTPServer, SimpleHTTPRequestHandler
from sys import platform
from tkinter import messagebox, ttk
import requests

import sv_ttk

if sys.platform == 'win32':
    from setuptools.msvc import winreg

from icons import images
from version import current_version, update_url
from multiprocessing import freeze_support

freeze_support()
locale.setlocale(locale.LC_ALL, '')

PORT = 8602
HOST = "localhost"
logging.basicConfig(level=logging.DEBUG, format='%(asctime)s %(levelname)s:%(message)s')
# BUILD_DIR = os.path.join(os.getcwd(), "files")

if hasattr(sys, '_MEIPASS'):
    # Running as PyInstaller bundle
    lang_data_file = os.path.join(sys._MEIPASS, "languages.json")
else:
    # Running as Python script
    lang_data_file = "languages.json"
# Load the language file
with open(lang_data_file, "r", encoding="utf-8") as f:
    lang_data = json.load(f)

# Set language preference based on system locale
system_locale = locale.getdefaultlocale()[0]
if system_locale.startswith("zh"):
    lang = "zh"  # Chinese
else:
    lang = "en"  # English


def resource_path(relative_path):
    if hasattr(sys, '_MEIPASS'):
        return os.path.join(sys._MEIPASS, relative_path)
    return os.path.join(os.path.abspath("."), relative_path)


BUILD_DIR = resource_path('files')

if __name__ == "__main__":
    root = tkinter.Tk()
    app = App(root)
    root.mainloop()
```

app file: https://drive.google.com/file/d/1pkd3QEalI6iiQfrTgLMg04jFw834rKi8/view?usp=sharing
@rokm

**Comment by rokm** [comment]
> system_locale = locale.getdefaultlocale()[0]
> if system_locale.startswith("zh"):

`locale.getdefaultlocale()` might return `(None, None)`, as per [python docs](https://docs.python.org/3.11/library/locale.html#locale.getdefaultlocale). 

In that case, `system_locale.startswith(..)` will raise `AttributeError: 'NoneType' object has no attribute 'startswith'`.

If you need to determine locale on macOS, you should use Apple API for that. See #7841.

**Comment by cikichen** [comment]
> > system_locale = locale.getdefaultlocale()[0]
> > if system_locale.startswith("zh"):
> 
> `locale.getdefaultlocale()` might return `(None, None)`, as per [python docs](https://docs.python.org/3.11/library/locale.html#locale.getdefaultlocale).
> 
> In that case, `system_locale.startswith(..)` will raise `AttributeError: 'NoneType' object has no attribute 'startswith'`.
> 
> If you need to determine locale on macOS, you should use Apple API for that. See #7841.

```
# Set language preference based on system locale
# system_locale = locale.getdefaultlocale()[0]
# if system_locale.startswith("zh"):
#     lang = "zh"  # Chinese
# else:
#     lang = "en"  # English
lang = "en"
```
The solution doesn't work, the issue persists.

**Comment by rokm** [comment]
> The solution doesn't work, the issue persists.

Are we talking about your actual application now, or the minimized example you provided? 

Because if I create a onefile macOS .app bundle from your minimized example (with commented `locale.getdefaultlocale` part; and commented out the `app = App(root)` part), it shows the Tk window if I run it from terminal or if I run it from Finder (on x86_64, though).

**Comment by cikichen** [comment]
Is it only on the M1 that these issues occur? @rokm

**Comment by rokm** [comment]
> Is it only on the M1 that these issues occur? @rokm

`locale.getdefaultlocale()` may return `(None, None)` on macOS regardless of whether the system is x86_64 or arm64 (M1/M2). So I doubt your problem is specific to M1 (unless you also tested on x86_64 and it works there).
