### ISSUE TITLE
How to patch a .pyc file in a pyinstaller build

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#7865]
I apologize for creating another issue. 

I wanted to see if i can update a .pyc file in a build. It looks like I have to go through the TOC and then find the PYZ-00.pyz . Then extract PYZ-00.pyz, and recompress it. 
Will that violate any checksums or anything? 
Assuming the new .pyz will have a different size? what other values do i have to patch in the binary?

**Comment by rokm** [comment]
Why wouldn't you just rebuild your application?

To patch a single .pyc file, you would have to extract the PYZ from executable (actually, from executable's PKG), then unpack the PYZ, swap the .pyc in question, re-create the PYZ, re-create the PKG, and embed the PKG in a new bootloader executable (or find a way to cleanly remove the old PKG from the existing executable). And then, depending on your OS, modify the executable to make it look like the PKG is part of the executable (and if this is about macOS, you're in for a lot of pain). So you would have to closely mimic the PyInstaller's executable construction pipeline, probably re-using code from there.

And again, we do not support this sort of endeavor, so do not expect us to walk you through it.
