### ISSUE TITLE
PySide2 app is openable by open 'name'.app but not using double click on MacOS

### ISSUE THREAD

**Issue by GregorBecker** [pyinstaller/pyinstaller#7875]
## Description of the issue
After using the way described in issue #7859, our application works when calling Contents/MacOS/'name' and by calling the app via open 'name'.app in the terminal but not by opening it via double click. We (@jtock and I) are using PySide2 within our application. Is this a known issue on MacOS and is there a known workaround?

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```develop https://github.com/pyinstaller/pyinstaller/commit/6447a7f8a8c828514e59ce3e81d1c3235b2dcbb4```
* Version of Python: 3.9.13
* Platform: MacOS
* How you installed Python: globally
* Did you also try this on another platform? Does it work there?

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

**Comment by rokm** [comment]
If it runs from the terminal but not from the Finder, then you are likely a victim of reduced shell environment in the latter case...

Are you trying to use `locale.getdefaultlocale` or some other function from `locale` module?

**Comment by bwoodsend** [comment]
Could you wrap your code in a *try/except log error to file* block so that we've got some diagnostics to work with?
```python
import traceback

try:
    your code here
except:
    open("/Users/Shared/error.log", "w").write(traceback.format_exc())
```

**Comment by GregorBecker** [comment]
Thank you for the fast responds. The error.log now shows that within the following call in our initial Pythonscript ```p = sp.Popen([python, -m, streamlit, run,  program_files\\GUI_st\\1_Main_Application.py, --server.headless=True, --global.developmentMode=False, --server.enableXsrfProtection=false], stdout=sp.DEVNULL)``` Python is not detectable. Are we doing something wrong here? 

error.log

Traceback (most recent call last):
  File "program_files/start_script.py", line 59, in <module>
    p = sp.Popen(cmd.split(), stdout=sp.DEVNULL)
  File "subprocess.py", line 951, in __init__
  File "subprocess.py", line 1821, in _execute_child
OSError: [Errno 2] No such file or directory: 'python'

We also tried python3.9, python3, streamlit as well as ./Python non of them worked.

**Comment by rokm** [comment]
> Python is not detectable. Are we doing something wrong here?

Why are you trying to run the python interpreter from the frozen application? That defeats the point of freezing your application using PyInstaller in the first place, since you now have to ensure that there is python (with streamlit installed) available on your target machine...

And it doesn't work when you run the application from Finder because applications that are started that way have a limited shell environment set up (see #6378); this includes `PATH` environment variable, which in this case does not contain the path to python interpreter.

> We also tried python3.9, python3, streamlit as well as ./Python non of them worked.

The `Python` in the frozen application bundle is a shared library, not executable.
