### ISSUE TITLE
Unable to serve external files with DEBUG = True

### ISSUE THREAD

**Issue by mpelzsherman** [pyinstaller/pyinstaller#7883]
When we build our installer with DEBUG = True, it works fine.

We can load images, .js, .css etc. just fine.

When we build without DEBUG = True, however, the server refuses to load any external file.

For example, our main .js file yields the following error:

```
Refused to execute script from 'http://localhost:8000/static/static/js/main.5b32b158.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

The content-type response header is always "text/html".

Manually adding "type" declarations to the `<script>` tags does not resolve the issue.

We have the following:

ALLOWED_HOSTS = ['localhost', '127.0.0.1']

Is there some setting we need to enable serving of external files?

Many thanks in advance!

**Comment by bwoodsend** [comment]
Uhmm, how are we supposed to know what might compel your web server to use the wrong mime types? We'd need to see code - you haven't even given us a hint as to what framework it uses!

At a wild guess, it's possible that `main.5b32b158.js` isn't packaged or is being looked for in the wrong place and your server is sending back an HTML 404 page. That `static/static` path in your URL looks somewhat unlikely to be correct.

I don't even know what this `DEBUG = True` option is so I can't guess why it would make or break a server.

**Comment by mpelzsherman** [comment]
Hi @bwoodsend. Thanks very much for your response. I realize I didn’t give you much to go on there. I am new to pyInstaller and I inherited the project I’m working on. I incorrectly assumed that the DEBUG setting was an undocumented feature of pyinstaller. I know the file paths look funny, but they are in fact, correct. Just making this one change causes the issue. 

Since the problem appears to be on our end, I’ll go ahead and close the issue. Thanks for your help.

**Comment by mpelzsherman** [comment]
For reference, here is the DEBUG setting I was referring to:

https://github.com/pyinstaller/pyinstaller/blob/develop/tests/functional/data/django/django_site/settings.py#L25

I looked through the pyinstaller docs and found this:

https://docs.djangoproject.com/en/4.1/ref/settings/#debug

... but itdoesn't explain the change in behavior regarding the content types.
