### ISSUE TITLE
PyInstaller isn't executing next line of code

### ISSUE THREAD

**Issue by itsOdell** [pyinstaller/pyinstaller#7886]
## Description of the issue
Pyinstaller is not executing next line of code while python interpreter is.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.13.0```
* Version of Python: 3.11
* Platform: Windows 11
* How you installed Python: Original source python.org
* Did you also try this on another platform? Does it work there? Don;;t
Don't have any other platforms

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

The image provided below is from the normal python interpreter, notice the <user_agent object> being printed?
![Screenshot 2023-08-25 112721](https://github.com/pyinstaller/pyinstaller/assets/75822755/87dc7533-a9bd-4117-acfa-29f3d1ceb13b)

the image provided below is the pyinstaller compiled output, see how the <user_agent object> isnt being printeed here? the code isnt executing the line provided below
![Screenshot 2023-08-25 112852](https://github.com/pyinstaller/pyinstaller/assets/75822755/4200abd3-d75e-40f3-b966-cd05583e1098)

### A minimal example program which shows the error

There is no error messages, its just not executing correctly

**Comment by rokm** [comment]
Sure, we have nothing better to do on a Friday night than reconstructing what package and functions from it you are trying to use...

But FWIW, you are probably not collecting data from `random_user_agent` package, and are swallowing the resulting
```
  File "random_user_agent/user_agent.py", line 23, in __init__
  File "random_user_agent/user_agent.py", line 51, in load_user_agents
  File "zipfile.py", line 1284, in __init__
FileNotFoundError: [Errno 2] No such file or directory: '[...]/random_user_agent/data/user_agents.zip'
```
exception.

Try adding `--collect-data random_user_agent` to your PyInstaller command to collect the package's data.

**Comment by itsOdell** [comment]
Is there any we can get to a conclusion privately? I dont want to leak my codebase so I was forced to provide minimal info

**Comment by rokm** [comment]
> Is there any we can get to a conclusion privately? I dont want to leak my codebase so I was forced to provide minimal info

Nope, we don't run a private consultancy here.

And it shouldn't be that hard to provide a minimal example of your use of `random_user_agent` that demonstrates the issue completely independently from your codebase.

**Comment by itsOdell** [comment]
this is my main.py:
```
from utils import get_random_user_agent from utils #utils is a local file which i created
def main():
    random_ua = get_random_user_agent()
    print("You have gotten a random user agent")
```

and now this is my utils.py:
```
from random_user_agent.user_agent import UserAgent
from random_user_agent.params import SoftwareName, OperatingSystem

def get_random_user_agent():
    software_names = [SoftwareName.CHROME.value, SoftwareName.SAFARI.value,SoftwareName.FIREFOX.value, SoftwareName.EDGE.value]

    operating_systems = [OperatingSystem.WINDOWS.value, OperatingSystem.LINUX.value, OperatingSystem.MACOS.value, OperatingSystem.MAC_OS_X.value]


    user_agent_rotator = UserAgent(software_names=software_names, operating_systems=operating_systems)
    #^ the above line is where the code doesnt execute past further. So in the main function in main.py, the print() never gets executed
    
    return user_agent_rotator.get_random_user_agent()
    
    you can search up random_user_agent on pypi

**Comment by rokm** [comment]
Are you collecting the data from `random_user_agent`?

**Comment by itsOdell** [comment]
no, this is the current command im using: ```PyInstaller --noconfirm --onefile --console --add-binary ".\chromedriver.exe;." .\main.py```

**Comment by rokm** [comment]
Try adding `--collect-data random_user_agent` to your PyInstaller command.

**Comment by itsOdell** [comment]
Thanks. But the way quick question, should I also add my local files (such as utils.py) to —collect-data and how do I know which packages to add? There wasn’t enough info pertaining in the docs
