### ISSUE TITLE
OSError: exception: access violation reading 0x00000010

### ISSUE THREAD

**Issue by GDHang** [pyinstaller/pyinstaller#7893]
python32 3.10，my project import xlwings，execute pyinstaller successfully，but start exe failed

pyinstaller -version：5.13.1
xlwings -version：0.30.11

Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 46, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 31, in _pyi_rthook
  File "PyInstaller\fake-modules\_pyi_rth_utils\__init__.py", line 43, in secure_mkdtemp
  File "PyInstaller\fake-modules\_pyi_rth_utils\_win32.py", line 234, in secure_mkdir
OSError: exception: access violation reading 0x00000010
[15328] Failed to execute script 'pyi_rth_win32comgenpy' due to unhandled exception!

**Comment by rokm** [comment]
Ah, yes, I forgot to add `argtypes` for `CreateDirectoryW` in `pyi_rth_utils\_win32.py` (and for some other functions used in error handling codepaths).

**Comment by GDHang** [comment]
> Ah, yes, I forgot to add `argtypes` for `CreateDirectoryW` in `pyi_rth_utils\_win32.py` (and for some other functions used in error handling codepaths).

Thanks for answering my problem!

**Comment by ils94** [comment]
> Ah, yes, I forgot to add `argtypes` for `CreateDirectoryW` in `pyi_rth_utils\_win32.py` (and for some other functions used in error handling codepaths).

I'm having the same problem, but I don't know how to apply the fixes you apparently did.

**Comment by ewcr** [comment]
Please help, how can I resolve the problem in _win32.py file?

**Comment by ils94** [comment]
> > Ah, yes, I forgot to add `argtypes` for `CreateDirectoryW` in `pyi_rth_utils\_win32.py` (and for some other functions used in error handling codepaths).
> 
> I'm having the same problem, but I don't know how to apply the fixes you apparently did.

I fixed it by installing pyinstaller 5.6.2 lol

All modules, even the ones I was certain to build .exe without issue was giving out this error, so I had to downgrade.

**Comment by ewcr** [comment]
It's a pity, no way, there's nothing else to do but downgrade
thanks.

**Comment by bwoodsend** [comment]
PyInstaller `v5.13.2` should be out in an hour or so.

**Comment by bwoodsend** [comment]
There we go. That should be normality restored.
