### ISSUE TITLE
Update from 5.13.0 to 5.13.1 results in crash of Python 3.8 32bit build

### ISSUE THREAD

**Issue by Safihre** [pyinstaller/pyinstaller#7897]
We build SABnzbd with nice recent 64bit Python 3.11.5, but also with Python 3.8 32bit so we can release a "legacy" version that still runs on Windows 7 and on the few 32 bit systems out there. We've been doing this for quite a while and all is well.

However, [Renovate triggered an update](https://github.com/sabnzbd/sabnzbd/pull/2666) of PyInstaller to 5.13.1 from 5.13.0 and now suddenly the Python 3.8 32 bit build fails because it runs beyond the build limit of 30 minutes. Normally the build of both releases combined completes within 5-10 minutes.

1. [5.13.1 build](https://github.com/sabnzbd/sabnzbd/actions/runs/5994335258/job/16284054145)
2. [5.13.0 build](https://github.com/sabnzbd/sabnzbd/actions/runs/5993065481/job/16284099196) that I re-triggered just to confirm it's not some GitHub Actions issue.

I'm not sure if it's Python 3.8 or 32bit that is causing the issue.

**Comment by rokm** [comment]
Considering the last output from PyInstaller is `41354 INFO: Building COLLECT COLLECT-01.toc completed successfully.` (which is the same as in "good" 5.13.0 build) and you are using a custom build script, can you add a debug message to your build script after the PyInstaller process is ran? I.e., so we can see if the build script is stuck in PyInstaller process for whatever reason, or if the PyInstaller process has finished and the build script is stuck somewhere else?

**Comment by rokm** [comment]
Since this is 32-bit python on Windows, perhaps #7893 is manifesting in some way? Are you trying to run the generated executable somewhere during the build process?

**Comment by bwoodsend** [comment]
It does test it. https://github.com/sabnzbd/sabnzbd/blob/77518cf1f5eb1162ed0634c6f1f16d4d70df6822/builder/package.py#L266

Presumably, that's crashing and creating a blocking error dialog.

**Comment by Safihre** [comment]
> Since this is 32-bit python on Windows, perhaps #7893 is manifesting in some way? Are you trying to run the generated executable somewhere during the build process?

Seems you are right.
I disabled the release-check to get [a successful build](https://github.com/sabnzbd/sabnzbd/actions/runs/6016857238) and it fails to run:
```
Traceback (most recent call last):
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 46, in <module>
  File "Lib\site-packages\PyInstaller\hooks\rthooks\pyi_rth_win32comgenpy.py", line 31, in _pyi_rthook
  File "PyInstaller\fake-modules\_pyi_rth_utils\__init__.py", line 43, in secure_mkdtemp
  File "PyInstaller\fake-modules\_pyi_rth_utils\_win32.py", line 234, in secure_mkdir
OSError: exception: access violation reading 0x00000010
```
So, wait for 5.13.2 it seems?

**Comment by Safihre** [comment]
Guess we can close as duplicate of #7893!
