### ISSUE TITLE
Pillow does not find TgaImagePlugin when frozen

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#790]
**Original date**: 2013/10/08
**Original reporter**: *atrepaul AND yahoo DOT  COOM *

Hello,

I have a python script that loads a tga picture using Pillow (the fork of PIL).
I use this method to import Pillow :
from PIL import Image

It works all right like this : python myScript.py
But after I freeze it with PyInstaller, it can't load the tga picture and displays this :

File "/Volumes/Data/xxxxxx/build/generique/out00-PYZ.pyz/PIL.Image", line 2006, in open
IOError: cannot identify image file

It's very similar to what happened in a previous version of PyInstaller with PIL :
#454 

I have tried freezing this Pillow script with the latest available version of PyInstaller (2.1), same problem.

Here is how Pillow loads the ImagePlugins :

In its __init__.py file :
```
_plugins = ['ArgImagePlugin',
            'BmpImagePlugin',
......
            'TgaImagePlugin',
            'TiffImagePlugin',
......
            'XpmImagePlugin',
            'XVThumbImagePlugin']
```

In its Image.py file :
```
from PIL import VERSION, PILLOW_VERSION, _plugins
......
    for plugin in _plugins:
        try:
            if DEBUG:
                print ("Importing %s"%plugin)
            __import__("PIL.%s"%plugin, globals(), locals(), [])
        except ImportError:
            if DEBUG:
                print("Image: failed to import", end=' ')
                print(plugin, ":", sys.exc_info()[1])
```

I activated the DEBUG mode, and saw that the frozen app can't find the TgaImagePlugin :

Image: failed to import TgaImagePlugin : No module named TgaImagePlugin (and also lots of other ImagePlugins)

Then I copied TgaImagePlugin.py and TgaImagePlugin.pyc to the same place where the frozen app is, it still bugs.

Do you know how I could workaround that problem ?

This is on Mac OS X 10.8.5, Mac Ports, python2.7.5, Pillow2.2.1.

Thanks.

**Comment by htgoebel** [comment]
This is solved since 3.0 at least, see https://github.com/pyinstaller/pyinstaller/blob/3.0/PyInstaller/hooks/hook-PIL.Image.py
