### ISSUE TITLE
Python core libraries being frozen import

### ISSUE THREAD

**Issue by itsOdell** [pyinstaller/pyinstaller#7900]
## Description of the issue
Pyinstaller cant find the code library (concurrent.futures) in PYZ
### Context information (for bug reports)
So im importing a class named "Future" from the core library called concurrent. But pyinstaller is saying 
```
# concurrent.futures.thread not found in PYZ
# bytecode is stale for 'concurrent.futures.thread'
# code object from C:\Users\abdul\AppData\Local\Temp\_MEI227202\concurrent\futures\thread.py
import 'concurrent.futures.thread' # <_frozen_importlib_external.SourceFileLoader object at 0x0000023873172150>
```

* Output of `pyinstaller --version`: ```5.13.0```
* Version of Python: 3.11
* Platform: Windows 11/English
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there?
Nope, doesn't work on other platforms

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import concurrent.futures

thread_amount = input("how many workers/thread do you want")



def cleanup():
   global STOP_THREADS
   STOP_THREADS = True
    sys.exit(0)


def main():
    if STOP_THREADS == True:
         return;

with concurrent.futures.ThreadPoolExecutor(max_workers=thread_amount) as executor:
    try:
        while not STOP_THREADS:
            executor.submit(main)
            sleep(uniform(thread_delay_min, thread_delay_max))
    except KeyboardInterrupt:
        cleanup()
```

### Stacktrace / full error message

```
# concurrent.futures.thread not found in PYZ
# bytecode is stale for 'concurrent.futures.thread'
# code object from C:\Users\abdul\AppData\Local\Temp\_MEI227202\concurrent\futures\thread.py
import 'concurrent.futures.thread' # <_frozen_importlib_external.SourceFileLoader object at 0x0000023873172150>
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by itsOdell** [comment]
What this code does is it takes a pool of threads and each thread executes a function. Whenever one thread dies/stops/exits, `import concurrent.futures.ThreadPoolExecutor` automatically creates a new thread henceforth resulting in an infinite thread pool execution

**Comment by rokm** [comment]
Are you running PyInstaller with `--debug all` (or `--debug noarchive`)? In that case, modules will not be in PYZ.

Although considering you seem to have `concurrent\futures\thread.py` in your frozen application directory, you are likely using some additional PyInstaller options that you forgot to tell us about. So, what is the PyInstaller command that you are using (or what does your .spec file look like, if you are building from .spec instead of .py)?

**Comment by itsOdell** [comment]
Im running `--debug all`. The listed below are all the modules I have imported :

local file: `main.py`
- selenium
- seleniumwire
- time
- colorama
- os
- random
- prettytable
- threading
- signal
- concurrent.futures
- local file: proxy.py
- local file: auth.py
- local file: utils.py

local file: `proxy.py` (gets a random proxy from proxies.txt)
- random
- colorama
- os
- re

local file: `auth.py' (asks user for license key and validates it)
- requests
- datetime

local file: 'utils.py'
- random_user_agent
- os
- sys
- re


As for the creation im using auto-py-to-exe, and this is my config.json which i have exported:
```{
 "version": "auto-py-to-exe-configuration_v1",
 "pyinstallerOptions": [
  {
   "optionDest": "noconfirm",
   "value": true
  },
  {
   "optionDest": "filenames",
   "value": "C:/Users/abdul/Programming/python/project/main.py"
  },
  {
   "optionDest": "onefile",
   "value": true
  },
  {
   "optionDest": "console",
   "value": true
  },
  {
   "optionDest": "icon_file",
   "value": "C:/Users/abdul/Programming/python/project/Default_A_cosmic_scene_of_a_majestic_solar_eclipse_with_the_mo_2_a30cdd98-47a8-4f07-90a1-4acb973fded.ico"
  },
  {
   "optionDest": "name",
   "value": "Horizons Edge"
  },
  {
   "optionDest": "upx_dir",
   "value": "C:/Users/abdul/Programming/python/project"
  },
  {
   "optionDest": "ascii",
   "value": false
  },
  {
   "optionDest": "clean_build",
   "value": false
  },
  {
   "optionDest": "debug",
   "value": "all"
  },
  {
   "optionDest": "strip",
   "value": false
  },
  {
   "optionDest": "noupx",
   "value": false
  },
  {
   "optionDest": "disable_windowed_traceback",
   "value": false
  },
  {
   "optionDest": "embed_manifest",
   "value": true
  },
  {
   "optionDest": "uac_admin",
   "value": false
  },
  {
   "optionDest": "uac_uiaccess",
   "value": false
  },
  {
   "optionDest": "win_private_assemblies",
   "value": false
  },
  {
   "optionDest": "win_no_prefer_redirects",
   "value": false
  },
  {
   "optionDest": "bootloader_ignore_signals",
   "value": false
  },
  {
   "optionDest": "argv_emulation",
   "value": false
  },
  {
   "optionDest": "datas",
   "value": "C:/Users/abdul/Programming/python/project/ca.crt;."
  },
  {
   "optionDest": "datas",
   "value": "C:/Users/abdul/Programming/python/project/Default_A_cosmic_scene_of_a_majestic_solar_eclipse_with_the_mo_2_a30cdd98-47a8-4f07-90a1-4acb973fded.ico;."
  },
  {
   "optionDest": "binaries",
   "value": "C:/Users/abdul/Programming/python/project/chromedriver.exe;."
  },
  {
   "optionDest": "collect_all",
   "value": "selenium"
  },
  {
   "optionDest": "collect_all",
   "value": "colorama"
  },
  {
   "optionDest": "collect_all",
   "value": "prettytable"
  },
  {
   "optionDest": "collect_all",
   "value": "seleniumwire"
  },
  {
   "optionDest": "collect_all",
   "value": "random_user_agent"
  },
  {
   "optionDest": "collect_all",
   "value": "requests"
  },
  {
   "optionDest": "hiddenimports",
   "value": "selenium"
  },
  {
   "optionDest": "hiddenimports",
   "value": "colorama"
  },
  {
   "optionDest": "hiddenimports",
   "value": "prettytable"
  },
  {
   "optionDest": "hiddenimports",
   "value": "seleniumwire"
  },
  {
   "optionDest": "hiddenimports",
   "value": "random_user_agent"
  },
  {
   "optionDest": "hiddenimports",
   "value": "requests"
  },
  {
   "optionDest": "collect_all",
   "value": "selenium-wire"
  },
  {
   "optionDest": "hiddenimports",
   "value": "selenium-wire"
  }
 ],
 "nonPyinstallerOptions": {
  "increaseRecursionLimit": true,
  "manualArguments": ""
 }
}```

**Comment by itsOdell** [comment]
one more additional info: the executable ouput runs perfectly fine ONLY if the host machine has the source code. If the device doesnt have the source code and only has the executable, it wont run as intended

**Comment by rokm** [comment]
> Im running `--debug all`.

Then, like I said, it is to be expected that module is not found in PYZ, because `--debug all` implies `--debug noarch`, which causes .pyc modules to be collected as individual files instead of collecting them into PYZ archive.

> one more additional info: the executable ouput runs perfectly fine ONLY if the host machine has the source code. If the device doesnt have the source code and only has the executable, it wont run as intended

What source code? Your local .py files, python stdlib, or 3rd party packages?

If source code is not available, do you get an error message? "It won't run as intended" means absolutely nothing to people who cannot see your code - considering the package list in you auto-py-to-exe config file, the initial minimal example may not be representative of the issue at all.
