### ISSUE TITLE
Feature to compile .pyc files

### ISSUE THREAD

**Issue by khanxbahria** [pyinstaller/pyinstaller#7901]
**Is your feature request related to a problem? Please describe.**
Currently, PyInstaller can only pack given that the .py files are present (which are perhaps necessary to resolve imports and other stuff).

**Describe the solution you'd like**
However it would be great if one could directly pack .pyc files, where the imports and other custom details could be manually specified in .spec file or similar.

**Describe alternatives you've considered**
There is no current solution that I'm aware of.

**Additional context**

**Comment by rokm** [comment]
You can already use sourceless modules (.pyc files without the .py file) with PyInstaller, provided they are discoverable in the build environment. For example, whole stdlib is sourceless when building with "portable" windows python.

Anything else sounds like beyond the scope of PyInstaller.
