### ISSUE TITLE
Using Pyinstaller with kivyMD application is missing several kivyMD core files

### ISSUE THREAD

**Issue by weaved459** [pyinstaller/pyinstaller#7902]
Python 3.10, kivy 2.2.1, kivymd 1.1.1 on ubuntu 22.04, application runs successfully from command line.  It's utilizing a .kv file separately, TopAppBar, ScrollView and a MDGridLayout with a 3 custom widgets (combining button behaviour with a MDLabel) and a regular MDIconButton as the last column.

No error is reported by Pyinstaller it builds successfully but when you attempt to run the executable from the command line many errors occur for missing modules / files.  Not sure if kivyMD being a newer component to kivy has more to do with this than anything else but I thought I'd report it.

So far modules and scripts I had to manually copy over before the application would work ...

in kivymd under the dist directory:

factory_registers.py   (missing MDTopAppBar, newer change in kivyMD)
icon_definitions.py

in kivymd/uix under the dist directory:

behaviors dir
controllers dir
files added in toolbar dir _init_py, toolbar.py (missing MDTopAppBar, newer change in kivyMD)
files added to list dir _pycache_, _init_.py, list.py

**Comment by rokm** [comment]
PyInstaller can only analyze (direct) module imports made in python code. So if you use a .kv file (or inline strings with kivy language), there is no way for PyInstaller to determine what modules should be collected. It is up to you to add the missing modules to [hidden imports](https://pyinstaller.org/en/stable/when-things-go-wrong.html#listing-hidden-imports).
