### ISSUE TITLE
Failed to execute script due to unhandled exception. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

### ISSUE THREAD

**Issue by Shahab-Ahmed** [pyinstaller/pyinstaller#7906]
I am attempting to create an executable for the iColorIt model. The script is running fine in the command prompt however, when I run pyinstaller icolorit_ui.py --onefile --windowed, move the file to my base directory with all of the files I get the following error: 

> Traceback (most recent call last):
>   File "torch\_sources.py", line 23, in get_source_lines_and_file
>   File "inspect.py", line 979, in getsourcelines
>   File "inspect.py", line 798, in findsource
> OSError: could not get source code
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "icolorit_ui.py", line 8, in <module>
>     from timm.models import create_model
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\__init__.py", line 2, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\__init__.py", line 1, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\byoanet.py", line 16, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\byobnet.py", line 36, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\helpers.py", line 18, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\layers\__init__.py", line 10, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\layers\conv_bn_act.py", line 8, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\layers\create_norm_act.py", line 16, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\layers\norm_act.py", line 7, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\layers\create_act.py", line 7, in <module>
>   File "<frozen importlib._bootstrap>", line 991, in _find_and_load
>   File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
>   File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
>   File "PyInstaller\loader\pyimod02_importers.py", line 377, in exec_module
>   File "timm\models\layers\activations_jit.py", line 19, in <module>
>   File "torch\jit\_script.py", line 1338, in script
>   File "torch\jit\frontend.py", line 262, in get_jit_def
>   File "torch\_sources.py", line 120, in parse_def
>   File "torch\_sources.py", line 32, in get_source_lines_and_file
> OSError: Can't get source for <function swish_jit at 0x0000021B69C3CCA0>. TorchScript requires source access in order to carry out compilation, make sure original .py files are available.

I am aware that other issues like this have been raised but I am new to this library and following them has been difficult. Any help will be appreciated.

**Comment by bwoodsend** [comment]
See https://github.com/pyinstaller/pyinstaller/issues/7126

**Comment by rokm** [comment]
You need to ensure that source files for `timm` package is collected.
