### ISSUE TITLE
Keep extracted _MEI folder between application starts

### ISSUE THREAD

**Issue by moritz89** [pyinstaller/pyinstaller#7909]
**Is your feature request related to a problem? Please describe.**
When packaging PyInstaller binaries with Inno Setup, it is not required to unpack all files on each start. They can be kept after the app ends and reused on the next start.

**Describe the solution you'd like**
An option that works in tandem with the `--runtime-tmpdir ` option to extract files in the installed *Program Files* folder

**Describe alternatives you've considered**
Just run the app as usual (only a startup optimization)

**Additional context**
- The extracted files should be deleted by Inno Setup upon uninstalling the app
- The PyInstaller bundled exe is also placed in the *Program Files* folder

**Comment by rokm** [comment]
When packaging PyInstaller binaries with Inno Setup, you would likely want to use the `onedir` mode instead of `onefile` one, wouldn't you? Then there is no extraction, and the files are managed by the Inno Setup installer.

**Comment by moritz89** [comment]
Thanks, I had overlooked that option
