### ISSUE TITLE
Manually specifying architecture matching system fails to detect compiler when building bootloader

### ISSUE THREAD

**Issue by oddbookworm** [pyinstaller/pyinstaller#7914]
## Description of the issue
When building the bootloader manually, if you specify the architecture that matches your system, it can throw an error
On a 64-bit system
```
(venv) PS C:\Users\andre\Projects\pyinstaller\bootloader> python.exe ./waf all --target-arch=64bit
'all' finished successfully (0.000s)
'distclean' finished successfully (0.013s)
Setting top to                           : C:\Users\andre\Projects\pyinstaller\bootloader
Setting out to                           : C:\Users\andre\Projects\pyinstaller\bootloader\build
Python Version                           : 3.11.5 (tags/v3.11.5:cce6ba9, Aug 24 2023, 14:38:34) [MSC v.1936 64 bit (AMD64)]
Checking for 'msvc' (C compiler)         : not found 
Checking for 'gcc' (C compiler)          : not found
Checking for 'clang' (C compiler)        : not found
could not configure a C compiler!
(complete log in C:\Users\andre\Projects\pyinstaller\bootloader\build\config.log)
```
Removing the `--target-arch=64bit` argument works perfectly (and specifying 32 bit works too)

### Context information (for bug reports)

* Output of `pyinstaller --version`: N/A (building bootloader from source)
* Version of Python: 3.11
* Platform: Windows 11
* How you installed Python: python.org download
* Did you also try this on another platform? Does it work there? No

### A minimal example program which shows the error
N/A (building bootloader from source)

### Stacktrace / full error message
Edit: uploading `config.log`
[config.log](https://github.com/pyinstaller/pyinstaller/files/12509000/config.log)

**Comment by rokm** [comment]
Indeed. Looks like the `{host}_{target}` strings returned by [`_msvc_target`](https://github.com/pyinstaller/pyinstaller/blob/096c4b1656833446736a36f6b6b2141aa8c19072/bootloader/wscript#L380-L393) are not valid in case when native target is specified via `--target-arch`. In such cases, they should be a single-arch string (and 64-bit Intel/AMD should actually be remapped to `x64`).

**Comment by rokm** [comment]
https://github.com/pyinstaller/pyinstaller/pull/7915 should fix the problem - can you check and confirm?

**Comment by oddbookworm** [comment]
> #7915 should fix the problem - can you check and confirm?

Yep, seems to have fixed it
