### ISSUE TITLE
Questions about hiding the source code

### ISSUE THREAD

**Issue by khwongbz** [pyinstaller/pyinstaller#7916]
May i know is the source code being hided and can not be accessed during the runtime of the executable? if not, where is the source code after compilation? I compiled my project into one-folder mode. I have read the documentation and i am not very sure about that. Big thx for the help!

**Comment by bwoodsend** [comment]
Ughh, I've answered this question so many times. If you want the illusion of protected source code, use [pyarmor](https://github.com/dashingsoft/pyarmor). If you want it genuinely protected then forget it -- it's impossible.
