### ISSUE TITLE
Update JavaScript node.js version in pyinstaller

### ISSUE THREAD

**Issue by TockiG** [pyinstaller/pyinstaller#7917]
### Context information

* Output of `pyinstaller --version`: ```5.13.0``` at commit 122a996
* Version of Python: 3.9.13
* Platform: macOS-10.16-x86_64-i386-64bit
* How you installed Python: global
* Same issue on Linux and Windows

### Issue

We are building a pyside2 application which is running a streamlit GUI. In streamlit we are using an element (st.plotly_chart) which is using some JavaScript code itself. 
There is a missing function l.replaceAll. It is provided by node.js at version > 15. We assume that there is a node.js version which is provided by pyinstaller and has lower version. Is node.js provided by the pyinstaller and is there a way to update the version / set the version?

### Stacktrace / full error message

```
TypeError: l.replaceAll is not a function
at http://localhost:8501/static/js/1168.39ebb497.chunk.js:1:352
at u (http://localhost:8501/static/js/1168.39ebb497.chunk.js:1:715)
at http://localhost:8501/static/js/1168.39ebb497.chunk.js:1:5230
at h (http://localhost:8501/static/js/1168.39ebb497.chunk.js:1:5901)
at aa (http://localhost:8501/static/js/main.dccfd6b5.js:2:2442236)
at Gu (http://localhost:8501/static/js/main.dccfd6b5.js:2:2494580)
at ks (http://localhost:8501/static/js/main.dccfd6b5.js:2:2481826)
at qs (http://localhost:8501/static/js/main.dccfd6b5.js:2:2481754)
at _s (http://localhost:8501/static/js/main.dccfd6b5.js:2:2481617)
at gs (http://localhost:8501/static/js/main.dccfd6b5.js:2:2478583)
```

Greetings 
@gregorbecker and Jan

**Comment by bwoodsend** [comment]
> We assume that there is a node.js version which is provided by pyinstaller and has lower version.

No. PyInstaller has no awareness of node.js and will not package any version of it unless told to either via add `--add-data/--collect-data/--collect-all` command line option or a hook. If you're sure that it's not the former then look inside the various `build/*/*.toc` files to see which package PyInstaller is pulling it from.

Beyond that, I can't help you without a minimal example and the corresponding command line options.

**Comment by TockiG** [comment]
Thank you for your reply! Based on your hint we did some more research and figured out that there is a. incompatibility between pyside2 and streamlit.plotly_charts / node.js. Updating to pyside6 solved our issue.
Thank you, @gregorbecker and Jan
