### ISSUE TITLE
Executable created on Linux 18 getting ModuleNotFound when run on Linux 20

### ISSUE THREAD

**Issue by dzairgus** [pyinstaller/pyinstaller#7919]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.13```
* Version of Python: 3.11.4
* Platform: Executable created on Ubuntu 18.04.6 LTS and is run/error comes on Linux 20.04
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
Also tried on Ubuntu 22.04.2 LTS and got the same error

### A minimal example program which shows the error

```
 - Created executable using pyinstaller 5.13 on Ubuntu 18.04.6 LTS and runs without issues
 - When that same executable is distributed to another Linux version (20.04 or 22.04) it yields the error below
```

### Stacktrace / full error message

```
>>>./run_executable
[2238] Module object for struct is NULL!
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ModuleNotFoundError: No module named '_struct'
[2238] Module object for pyimod01_archive is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod01_archive.py", line 19, in <module>
ModuleNotFoundError: No module named 'struct'
[2238] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 28, in <module>
ModuleNotFoundError: No module named 'pyimod01_archive'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[2238] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!

```

**Comment by bwoodsend** [comment]
Works fine for me. I built `print("hello")` on a ubuntu 18.04 Docker container with Conda Python+PyInstaller and it works fine running in a Ubuntu 22.04 container.

Does hello world work for you? What's your build command? Is `run_executable` the application or some wrapper script?

Can you also search inside the various `build/*/*.toc` files for `libpython3.11.so` and make sure that it is coming from your Conda environment rather than some other Python environment?

**Comment by dzairgus** [comment]
@bwoodsend Thanks for your help! We are looking into your other suggestions, but in the meantime the command we used is the following if it sheds any light:

`executable.py --hidden-import=brotli --name=sources_dler --distpath=build_sources_dler --workpath=dist_sources_dler --clean -w --exclude-module lib2to3 --exclude-module scipy --exclude-module numpy --exclude-module pil --exclude-module sphinx --exclude-module matplotlib --exclude-module ipdb --exclude-module IPython --hidden-import=sys --hidden-import=datetime   --hidden-import=re --hidden-import=json --hidden-import=socket --hidden-import=importlib --hidden-import=uuid --hidden-import=time  --hidden-import=zipfile  --hidden-import=glob --hidden-import=traceback --hidden-import=os   --hidden-import=requests  --hidden-import=urllib3 --hidden-import=Crypto.Hash --hidden-import=base64 --hidden-import=io --hidden-import=Crypto.Cipher --hidden-import=multiprocessing --hidden-import=abc --hidden-import=Crypto.Util.Padding --hidden-import=threading --hidden-import=copy --hidden-import=signal --hidden-import=Crypto --hidden-import=Crypto.Cipher --hidden-import=Crypto.Cipher.AES --hidden-import=Crypto.Random --hidden-import=Crypto.Cipher.PKCS1_v1_5 --hidden-import=Crypto.PublicKey.RSA --hidden-import=_sitebuiltins --noupx --hidden-import=PIL._tkinter_finder --hidden-import=ipaddress`

**Comment by bwoodsend** [comment]
Hmm, no. All that tells me is that you've been adding `--hidden-import` flags at random. `os` is a builtin module – you can't not include it!

**Comment by bwoodsend** [comment]
Just to confirm, you have actually checked that the executable does run on Ubuntu 16? This isn't some crazy setup where the only way to access the build machine is through CI/CD and it runs no tests?

**Comment by bwoodsend** [comment]
Closing for now. Comment below if you get the reproducer down to something small enough to be shareable and I'll repoen.
