### ISSUE TITLE
Multiprocessing freeze support error on Linux

### ISSUE THREAD

**Issue by a-wang24** [pyinstaller/pyinstaller#7920]
## Description of the issue
This is a follow up to #7410 which was fixed in #7411. I am still encountering the same or similar issue with Pyinstaller on versions after #7411 went in. The failure message is: `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEItsfTua/base_library.zip`

I am using the `--onefile` packaging method with a `.spec` file and calling `freeze_support()` at the top of my main block. I am using a subclass of `multiprocessing.SpawnProcess`.

Since this is only happening on Linux and the multiprocessing Python docs claim that `freeze_support` should have no effect on non-Windows machines, I've tried to wrap it in a conditional checking the platform is windows. That led to a different error on Linux: `multiprocessing/resource_tracker.py:96: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.`

### Context information (for bug reports)

* Output of `pyinstaller --version`: `5.13.2`
* Version of Python: `3.9.10`
* Platform: CentOS7 arm64 within docker container
* How you installed Python: `RUN curl -o Python-3.9.10.tar.xz https://www.python.org/ftp/python/3.9.10/Python-3.9.10.tar.xz` 
* Did you also try this on another platform? Does it work there?

- Amazon Linux 2 - Bug is present
- Ubuntu 18 - Bug is present
- MacOS 13.5.1 - Bug is not present

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode** (Bug does not manifest)
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
```
from multiprocessing import context, freeze_support, SimpleQueue

def main():
    in_queue = SimpleQueue()
    out_queue = SimpleQueue()

    pool = []
    for _ in range(4):
        w = Worker(in_queue, out_queue)
        w.start()
        pool.append(w)

    for p in pool:
        p.terminate()
        p.join()

class Worker(context.SpawnProcess):
    def __init__(self, inqueue: SimpleQueue, outqueue: SimpleQueue) -> None:
        super().__init__()
        self._inqueue = inqueue
        self._outqueue = outqueue
        self.daemon = True

    def run(self) -> None:
        put = self._outqueue.put
        get = self._inqueue.get

        while True:
            task = get()
            if task is None:
                break

            i, value = task
            put((i, value + 1))

if __name__ == "__main__":
    freeze_support()
    main()
```
Spec file
```
block_cipher = None
a = Analysis(
    ["../../reproduce_pyinstaller_bug.py"],
    pathex=["."],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=["bundling/hooks"],
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name="mp_test",
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
)
```
running `pyinstaller file.spec --distpath=build/final`

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1388, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1369, in _legacy_get_spec
  File "<frozen importlib._bootstrap>", line 423, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 716, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 536, in _get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEItsfTua/base_library.zip'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Side note 1: there is no multi-threading involved in this example, so this is *not* a thread-safety issue in any way.

Side note 2:

> Since this is only happening on Linux and the multiprocessing Python docs claim that `freeze_support` should have no effect on non-Windows machines, I've tried to wrap it in a conditional checking the platform is windows.

Python docs are talking about Python's implementation, which I think was made for `py2exe`. PyInstaller's run-time hook for `multiprocessing` overrides that implementation so that `multiprocessing` works in onedir and onefile mode, regardless of the OS. So in the case of PyInstaller, `multiprocessing.freeze_support` has effect on all OSes, and omitting its call tends to result in endless process spawn loop (although that depends on the default start method for the platform, unless explicitly overridden).

----

The error is caused because the program's main process exits while the resource tracker's process is being started, and thus the temporary directory is removed before the resource tracker's process can access the `base_library.zip`. Adding a delay before worker termination loop in `main` would work around this issue.

However, I think the real cause of this behavior is that this example is incorrect - the workers are subclassed from `context.SpawnProcess`, but the `multiprocessing` start method is left at the default. On linux, the default method is `fork`, while on macOS, it is `spawn` (from python 3.8 on). Therefore, on linux, you have a mismatch between the start method (which I suspect influences creation of resources, such as queues) and the process start method, which results in the resource tracker process being incorrectly spawned (this does not affect unfrozen script, and probably not onedir frozen applications either, but is a problem for onefile due to deletion of temporary directory).

If I modify the example:

```python
from multiprocessing import context, freeze_support, SimpleQueue
from multiprocessing import get_start_method, set_start_method
import sys

def main():
    in_queue = SimpleQueue()
    out_queue = SimpleQueue()

    pool = []
    for _ in range(4):
        w = Worker(in_queue, out_queue)
        w.start()
        pool.append(w)

    for p in pool:
        p.terminate()
        p.join()

class Worker(context.SpawnProcess):
    def __init__(self, inqueue: SimpleQueue, outqueue: SimpleQueue) -> None:
        super().__init__()
        self._inqueue = inqueue
        self._outqueue = outqueue
        self.daemon = True

    def run(self) -> None:
        put = self._outqueue.put
        get = self._inqueue.get

        while True:
            task = get()
            if task is None:
                break

            i, value = task
            put((i, value + 1))

if __name__ == "__main__":
    freeze_support()
    if len(sys.argv) > 1:
        set_start_method(sys.argv[1])
    print(f"using start method: {get_start_method()}")
    main()
``` 

and freeze it in onedir mode, running it with `spawn` argument on linux works as expected. Similarly, freezing and running it with `fork` argument on macOS results in the same issue with missing `base_library.zip`.

**Comment by a-wang24** [comment]
First, thank you for the extremely quickly reply

Apologies about thread safety in the title - I too hastily copied from the other issue referenced. I have updated it to avoid potential confusion by other readers. Also noted about the `freeze_support` being required for pyinstaller.

_____________

That makes sense regarding adding a delay and setting the start method properly. I've updated the example to include your changes, and added a `time.sleep(10)` between worker start and termination in the main loop. I'm still getting a similar error when running in onefile mode via a spec file. This seems unrelated to multiprocessing now?
Traceback:
```
[2284] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "pathlib.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "fnmatch.py", line 14, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
  File "<frozen zipimport>", line 259, in load_module
  File "re.py", line 125, in <module>
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 982, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 925, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1414, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1388, in _get_spec
[2282] LOADER: Freeing archive status for /app/bundling/deid_link/dist/mp_test
  File "<frozen importlib._bootstrap_external>", line 1369, in _legacy_get_spec
[root@c188e885b27f deid_link]#   File "<frozen importlib._bootstrap>", line 423, in spec_from_loader
  File "<frozen importlib._bootstrap_external>", line 716, in spec_from_file_location
  File "<frozen zipimport>", line 191, in get_filename
  File "<frozen zipimport>", line 709, in _get_module_code
  File "<frozen zipimport>", line 536, in _get_data
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/_MEIC4BQI5/base_library.zip'
[2284] LOADER: extracted pyimod03_ctypes
[2284] LOADER: running unmarshalled code object for pyimod03_ctypes...
[2284] LOADER: Installing PYZ archive with Python modules.
[2284] LOADER: PYZ archive: PYZ-00.pyz
[2284] LOADER: Running pyiboot01_bootstrap.py
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[2284] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

I found https://github.com/pyinstaller/pyinstaller/issues/7692 which seems to be a similar issue. However, I've inspected `Pyinstaller/compat.py` and found the listed modules (`pathlib`, `fnmatch`, `re`) in the `PY3_BASE_MODULES` block. Any ideas what I might be doing wrong here?

**Comment by rokm** [comment]
Can you paste the modified code, so I can try running it locally and see what is happening?

This still looks like the issue with temporary directory being deleted while a process is being started; and the delay between the worker start and termination loop is likely not a proper fix - the proper fix should be getting the start method in order.

**Comment by a-wang24** [comment]
Yes np - I think I have both added a delay and got the start method in order.

Modified code:
```
from multiprocessing import context, freeze_support, SimpleQueue
from multiprocessing import get_start_method, set_start_method
import sys
import time

def main():
    in_queue = SimpleQueue()
    out_queue = SimpleQueue()

    pool = []
    for _ in range(4):
        w = Worker(in_queue, out_queue)
        w.start()
        pool.append(w)

    time.sleep(10)

    for p in pool:
        p.terminate()
        p.join()

class Worker(context.SpawnProcess):
    def __init__(self, inqueue: SimpleQueue, outqueue: SimpleQueue) -> None:
        super().__init__()
        self._inqueue = inqueue
        self._outqueue = outqueue
        self.daemon = True

    def run(self) -> None:
        put = self._outqueue.put
        get = self._inqueue.get

        while True:
            task = get()
            if task is None:
                break

            i, value = task
            put((i, value + 1))

if __name__ == "__main__":
    freeze_support()
    if len(sys.argv) > 1:
        set_start_method(sys.argv[1])
    print(f"using start method: {get_start_method()}")
    main()
```

I am executing the built file with `./file spawn`

**Comment by rokm** [comment]
Hmmm, this seems to work as expected (Fedora 38, with system-packaged python 3.9.18) across multiple runs; whereas without delay and spawn argument, I could reproduce the problem immediately.

**Comment by a-wang24** [comment]
Could this be an issue specifically with Python 3.9.10? It is challenging for me to upgrade my python version to 3.9.18, but it is something I can look into if that will resolve the issue for me.

This is the OS I am on within a docker container:
```
[root@c188e885b27f >]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (AltArch)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (AltArch)"
```

**Comment by rokm** [comment]
> Could this be an issue specifically with Python 3.9.10? It is challenging for me to upgrade my python version to 3.9.18, but it is something I can look into if that will resolve the issue for me.

I don't think so. I've just tried building 3.9.10 in CentOS 7 container, and it seems to work as well. 

Is there any change if you inherit from `multiprocessing.Process` instead of `context.SpawnProcess`?

**Comment by rokm** [comment]
> VERSION="7 (AltArch)"

Are you running under x86_64 or some other architecture?

**Comment by a-wang24** [comment]
> Is there any change if you inherit from multiprocessing.Process instead of context.SpawnProcess?

no change here

> Are you running under x86_64 or some other architecture?


I am running on Arm64. We build a file using pyinstaller that needs to support arm64 and x86_64. I will try on x86_64

**Comment by a-wang24** [comment]
Wow - I'm sorry for wasting your time, Rok.

I was improperly mounting the sample code into my docker container, so while I updated the example, I was still creating the onefile from the old, broken version.

I have tried the updated example on both x86_64 and arm64 and it works with no issues. Thank you so much for your prompt responses and help!

**Comment by a-wang24** [comment]
I'm going to try this solution with our actual codebase. I will circle back if anything comes up but closing this issue.

Thanks again for the quick resolution
