### ISSUE TITLE
Hidden imports not found

### ISSUE THREAD

**Issue by Alcher5** [pyinstaller/pyinstaller#7924]
324 INFO: checking Analysis
324 INFO: Building Analysis because Analysis-00.toc is non existent
324 INFO: Initializing module dependency graph...
325 INFO: Caching module graph hooks...
333 INFO: Analyzing base_library.zip ...
1075 INFO: Loading module hook 'hook-encodings.py' from '/usr/local/lib/python3.7/dist-packages/PyInstaller/hooks'...
1569 INFO: Loading module hook 'hook-pickle.py' from '/usr/local/lib/python3.7/dist-packages/PyInstaller/hooks'...
1744 INFO: Loading module hook 'hook-heapq.py' from '/usr/local/lib/python3.7/dist-packages/PyInstaller/hooks'...
2756 INFO: Caching module dependency graph...
2892 INFO: running Analysis Analysis-00.toc
**2919 INFO: Analyzing hidden import 'modes_.init'**
**2919 ERROR: Hidden import 'modes_.init' not found**
2919 INFO: Processing module hooks...
2929 INFO: Looking for ctypes DLLs
2929 INFO: Analyzing run-time hooks ...
2933 INFO: Looking for dynamic libraries
3307 INFO: Looking for eggs
3308 INFO: Python library not among binary dependencies. Performing additional search...
3379 INFO: Using Python library /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
3406 INFO: checking PYZ
3406 INFO: Building PYZ because PYZ-00.toc is non existent
...
5651 INFO: Appending PKG archive to custom ELF section in EXE
5668 INFO: Building EXE from EXE-00.toc completed successfully

The hidden imports I provide in CMD are not found. I'm trying to create one executable (--onefile) using --hidden-import .

If I run the script in the usual way, the dynamic module is imported and loaded..

**Comment by bwoodsend** [comment]
At least provide us a stacktrace if you expect us to be able to do anything at all.

**Comment by Alcher5** [comment]
The module is in a subdirectory
├── main.py
├── modes_
│      └── init.py

main.py:
...
import importlib
from importlib import import_module
...
module = importlib.import_module(f'modes_.init')


Writed in CMD:
pyinstaller --clean --paths modes_ --hidden-import=modes_.init --onefile main.py

**Comment by Alcher5** [comment]
@bwoodsend how to provide stack trace?

**Comment by bwoodsend** [comment]
That example works fine. Whatever you think the issue is, it's something else.

> @bwoodsend how to provide stack trace?

When you run the application from a terminal, it's the error message it produces (and I mean all of it -- not just the last line).

**Comment by Alcher5** [comment]
@bwoodsend 

Output when running a binary file:

user@vm:~/sap/dist$ sudo ./main init 
['/tmp/_MEIDwM7C7/base_library.zip', '/tmp/_MEIDwM7C7/lib-dynload', '/tmp/_MEIDwM7C7', '/home/user/sap/modes\_']
Traceback (most recent call last):
  File "sap/main.py", line 62, in \<module\>
  File "importlib/\_\_init\_\_.py", line 127, in import_module
  File "\<frozen importlib._bootstrap\>", line 1006, in _gcd_import
  File "\<frozen importlib._bootstrap\>", line 983, in _find_and_load
  File "\<frozen importlib._bootstrap\>", line 953, in _find_and_load_unlocked
  File "\<frozen importlib._bootstrap\>", line 219, in _call_with_frames_removed
  File "\<frozen importlib._bootstrap\>", line 1006, in _gcd_import
  File "\<frozen importlib._bootstrap\>", line 983, in _find_and_load
  File "\<frozen importlib._bootstrap\>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'modes\_'
[26972] Failed to execute script 'main' due to unhandled exception

**Comment by Alcher5** [comment]
@bwoodsend 

user@vm:~/sap$ pyinstaller **main.spec**
120 INFO: PyInstaller: 5.13.2
120 INFO: Python: 3.7.3
121 INFO: Platform: Linux-5.15.0-70-generic-x86_64
123 INFO: Extending PYTHONPATH with paths
['/home/user', '/home/user/sap']
302 INFO: checking Analysis
303 INFO: Building Analysis because Analysis-00.toc is non existent
303 INFO: Initializing module dependency graph...
304 INFO: Caching module graph hooks...
311 INFO: Analyzing base_library.zip ...
1082 INFO: Loading module hook 'hook-encodings.py' from '/home/user/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
1514 INFO: Loading module hook 'hook-pickle.py' from '/home/user/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
1585 INFO: Loading module hook 'hook-heapq.py' from '/home/user/.local/lib/python3.7/site-packages/PyInstaller/hooks'...
2547 INFO: Caching module dependency graph...
2660 INFO: running Analysis Analysis-00.toc
2682 INFO: Analyzing /home/user/sap/main.py
**2685 INFO: Analyzing hidden import '/home/user/sap/modes_/init.py'**
**2685 ERROR: Hidden import '/home/user/sap/modes_/init.py' not found**
2685 INFO: Processing module hooks...
2695 INFO: Looking for ctypes DLLs
2695 INFO: Analyzing run-time hooks ...
2699 INFO: Looking for dynamic libraries
3040 INFO: Looking for eggs
3040 INFO: Python library not among binary dependencies. Performing additional search...
3103 INFO: Using Python library /lib/x86_64-linux-gnu/libpython3.7m.so.1.0
3105 INFO: Warnings written to /home/user/sap/build/main/warn-main.txt
3117 INFO: Graph cross-reference written to /home/user/sap/build/main/xref-main.html
3135 INFO: checking PYZ
3135 INFO: Building PYZ because PYZ-00.toc is non existent
3135 INFO: Building PYZ (ZlibArchive) /home/user/sap/build/main/PYZ-00.pyz
3301 INFO: Building PYZ (ZlibArchive) /home/user/sap/build/main/PYZ-00.pyz completed successfully.
3303 INFO: checking PKG
3303 INFO: Building PKG because PKG-00.toc is non existent
3303 INFO: Building PKG (CArchive) main.pkg
5270 INFO: Building PKG (CArchive) main.pkg completed successfully.
5271 INFO: Bootloader /home/user/.local/lib/python3.7/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
5271 INFO: checking EXE
5271 INFO: Building EXE because EXE-00.toc is non existent
5271 INFO: Building EXE from EXE-00.toc
5273 INFO: Copying bootloader EXE to /home/user/sap/dist/main
5273 INFO: Appending PKG archive to custom ELF section in EXE
5285 INFO: Building EXE from EXE-00.toc completed successfully.

---------------------------
2685 ERROR:  Hidden import ... not found
Why was the file not found? The file is there, the user has rights.

**Comment by bwoodsend** [comment]
>  2685 INFO: Analyzing hidden import '/home/user/sap/modes_/init.py'

Sounds like you're passing the filename rather than the module name to `hiddenimports`.

**Comment by Alcher5** [comment]
@bwoodsend thank u for help!

used the command:
user@vm:~/sap$ sudo pyinstaller --clean --paths=modes_ --hidden-import=init -F main.py
It's worked!

But now I'm faced with a new error:
In my script, module 1 (init)  is loaded from the main.py, and module 2 (init_checker_os) is loaded from module 1 (init). 

In the line for pyinstaller I entered:
user@vm:~/sap$ sudo pyinstaller --clean --paths=modes_ --paths=modules --hidden-import=init --hidden-import=init_checker_os -F main.py

The modules is in a subdirectories:
├── main.py
├── modes_
│ └── init.py
├── modules
│ └── init_checker_os.py

And it didn't work...  

How to tell pyinstaller that there is a second module, which is specified in the second file?
main.py   <--   init.py  <--  init_checker_os.py
