### ISSUE TITLE
Missing hook-Crypto.py

### ISSUE THREAD

**Issue by LGunter** [pyinstaller/pyinstaller#7931]
This issue was sent before but closed due to lack of details o I'm requesting an answer since I'm having the same issue.

I have PyCryptodome installed on my computer and it loads perfectly when I run pyinstaller without any parameters.  But when I try to run it inside of a virtual environment and specify the site-packages there, the hook-Crypto.py never gets called.  I have checked both folders where the site-packages are located and they identical.

**Comment by bwoodsend** [comment]
What do you mean by *specify the site-packages there*? If you're hacking it into `sys.path` via the `--paths` flag or `PYTHONPATH` then it's no wonder it doesn't work. If PyCryptodome is in a virtual environment then PyInstaller must also be in that environment.

In any case, freezing a [random PyCryptodome example](https://www.pycryptodome.org/src/examples#generate-an-rsa-key) inside a venv environment worked fine for me.

```fish
> python -m venv env
> source ./env/bin/activate.fish
(env) > python -m pip install -Uq pip wheel
(env) > pip install pycryptodome pyinstaller
...
Successfully installed altgraph-0.17.3 pycryptodome-3.18.0 pyinstaller-5.13.2 pyinstaller-hooks-contrib-2023.8
(env) > pyinstaller test.py 
183 INFO: PyInstaller: 5.13.2
183 INFO: Python: 3.10.9
184 INFO: Platform: Linux-6.5.0-1-MANJARO-x86_64-with-glibc2.38
...
(env) > ./dist/test/test
b'-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAtJsmoqiMvcTTucrpOqJl\n5qPAwbGH+lnmQlgxTaCG/5bDqiDwRXndRZ+5Z3YixaAFt4BoKlEp/ND6jEQiISEx\nxHCKlzfDndicab/fTnBhuhH6g6nzYLfFqQLgJtOJxFA2Ae0KZE8pqlnFyniwvzZN\n32+mWkiJpvpUPQIPLylaT1X/FhJRAUGLSomDOE8BgWb/vhCMlfYyXZP36Cjjfyz7\nQUivH06918nPVevNy+1hJJ8PCyEPHUcFoNoDV7XM9vqoY5funGdGoTPJc+IchbDM\npXLAlaqA30ZbvYrFAUHoyab4HYshQ4/pVJ5MBdUVtfMUARDvkdBqJDokVAm79S+h\nhQIDAQAB\n-----END PUBLIC KEY-----
```

**Comment by LGunter** [comment]
Yes both PyCryptodome and Pyinstaller are in the virtual environment.  And I used the --paths parameter to use the site-packages in the virtual environment but the hook-Crypto wasn't called by Pyinstaller but it pulls all the other modules from the virtual.

**Comment by bwoodsend** [comment]
Well then this isn't enough information to go on either. I need the full steps to reproduce (source code, build environment, steps used to set up the venv, command used to build) and the build logs and runtime stacktrace (like it said in the [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/bug_report.md)). Anything less than that and this issue is no more actionable than the last one that got closed.

**Comment by LGunter** [comment]
[requirements.txt](https://github.com/pyinstaller/pyinstaller/files/12595417/requirements.txt)
[main.txt](https://github.com/pyinstaller/pyinstaller/files/12595432/main.txt)
[mainspec.txt](https://github.com/pyinstaller/pyinstaller/files/12595443/mainspec.txt)
files attached for the build.  source code only has the imports for the entire project.  
[Virtual for Pyinstalller & Playwright.txt](https://github.com/pyinstaller/pyinstaller/files/12595459/Virtual.for.Pyinstalller.Playwright.txt)

**Comment by rokm** [comment]
> from crypto.Cipher import AES
> from crypto.Random import get_random_bytes

Does it help if you capitalize "crypto"?
```python
from Crypto.Cipher import AES
from Crypto.Random import get_random_bytes
```
