### ISSUE TITLE
PyInstaller doesn't package libpython

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#794]
**Original date**: 2013/10/10
**Original reporter**: _ajford_

Perhaps I am doing something wrong, but I cannot seem to build a single executable file.

I have simplified the script down to a single line, "print 'Hello World'", and still I cannot get a working single file executable.

When attempting to run the executable, I get the following error:

```
Error loading Python lib '/home/foo/hello/build/hello/libpython2.6.so.1.0': /home/foo/hello/build/hello/libpython2.6.so.1.0: cannot open shared object file: No such file or directory
```

I've attached a simple bash script that demonstrates exactly how I'm attempting to build this simple script.

Also note, I've tried this with the manual install of pyinstaller (via setup.py), as well as when installed via PIP. I have tried this on a debian box running python 2.7.5 as well as a CentOS 6.3 box running python 2.6.6

**Comment by beastsenior** [comment]
use
./configure --enable-shared --prefix=/usr/local LDFLAGS="-Wl,--rpath=/usr/local/lib"
when you compile Python from source

**Comment by htgoebel** [comment]
@beastsenior  How should your comment be related to this issue?

**Comment by jesusjda** [comment]
Same issue with python 3.5

`pyinstaller 3.5.dev0+0ffa574bf`

copying the file `libpython3.5m.so.1.0` to `libpython3.5m.so` works (as I see in another site)

to get the error I execute: `pyinstaller myscript.py` and several --hidden-import

thankyou so much for your work ;)
