### ISSUE TITLE
Issue With My Recipe Finding App Only When It's Compiled With Pyinstaller

### ISSUE THREAD

**Issue by tbrsvn** [pyinstaller/pyinstaller#7940]
## Description of the issue

When I print all the matching recipes, it doesn't finish printing all of them before prompting you with the selection tkinter window. For instance:

pyinstaller compiled only prints up to 959 recipes before the tkinter window comes up with the indredients: "beef,tomato", whereas in python it prints 1218 and the scoring system. It finishes printing after the tkinter prompt with pyinstaller.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.13.2```
* Version of Python: 3.11.5
* Windows 11
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?: I tried it on linux, and it still doesn't work

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
from nltk.tokenize import RegexpTokenizer
import tkinter as tk
from tkinter import simpledialog, messagebox
from gooey import Gooey, GooeyParser
import win32process, win32gui, win32con
import ujson as json
import os
import pkg_resources
import sys
from autocorrect import Speller
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.lib import colors
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, ListFlowable, ListItem
from reportlab.lib.styles import getSampleStyleSheet

spell = Speller()
tokenizer = RegexpTokenizer(r"\w+")

if len(sys.argv) >= 2:
    if not "--ignore-gooey" in sys.argv:
        sys.argv.append("--ignore-gooey")

if not "--ignore-gooey" in sys.argv and getattr(sys, "frozen", False):

    pid = os.getpid()  # get PID of this script, use os.getppid() if standalone .exe

    # get window for chosen PID
    def get_hwnds_for_pid(pid):
        def callback(hwnd, hwnds):
            if win32gui.IsWindowVisible(hwnd) and win32gui.IsWindowEnabled(hwnd):
                _, found_pid = win32process.GetWindowThreadProcessId(hwnd)
                if found_pid == pid:
                    hwnds.append(hwnd)
            return True

        hwnds = []
        win32gui.EnumWindows(callback, hwnds)
        return hwnds

    open_windows_with_corresponding_pid = get_hwnds_for_pid(pid)
    for hwnd in open_windows_with_corresponding_pid:
        try:
            win32gui.ShowWindow(hwnd, win32con.SW_HIDE)
        except Exception:
            pass

def load_recipe_data():
    try:
        with pkg_resources.resource_stream(__name__, 'recipes.json') as file:
            return json.load(file)
    except Exception as e:
        print(f"Error loading recipe data: {e}")
        return {}

def find_matching_recipes(recipe_data, available_ingredients):
    matching_recipes = []

    for recipe_key, recipe_info in recipe_data.items():
        recipe = recipe_info
        recipe_ingredients = tokenizer.tokenize(" ".join(recipe.get("ingredients", [])))
        recipe_ingredients = [ingredient.lower() for ingredient in recipe_ingredients]

        additional_ingredients = [ingredient for ingredient in recipe_ingredients if ingredient not in available_ingredients]
        score = len(additional_ingredients)

        if all(keyword in recipe_ingredients for keyword in available_ingredients):
            matching_recipes.append({"recipe": recipe, "score": score})

    matching_recipes.sort(key=lambda x: x["score"])
    return matching_recipes

@Gooey(program_name="Recipe Finder", default_size=(800, 600))
def main():
    parser = GooeyParser(description="Find recipes based on your available ingredients!")

    parser.add_argument("Available_Ingredients", type=str, help="Comma-separated list of available ingredients")

    args = parser.parse_args()

    input_ingredients = args.Available_Ingredients.split(",")
    corrected_ingredients = [spell(ingredient.strip().lower()) for ingredient in input_ingredients]

    print("\nInputted Ingredients:")
    for original, corrected in zip(input_ingredients, corrected_ingredients):
        print(f"{original} (Auto-corrected to: {corrected})")

    recipe_data = load_recipe_data()

    if not recipe_data:
        return

    matching_recipes = find_matching_recipes(recipe_data, corrected_ingredients)

    if not matching_recipes:
        print("No matching recipes found.")
        return

    print("\nMatching recipes:")
    for index, recipe in enumerate(matching_recipes, start=1):
        print(f"{index}. {recipe['recipe'].get('title', 'Title not available')} (Score: {recipe['score']})")

    print("\nScoring System:")
    print("The score is based on the number of additional ingredients required for each recipe.")
    print("Lower score indicates a better match with your available ingredients.")

    root = tk.Tk()
    root.withdraw()
    recipe_number = simpledialog.askinteger("Recipe Selection", "Enter the number of the recipe you want to view:")
    
    if recipe_number is not None and 0 <= recipe_number - 1 < len(matching_recipes):
        selected_recipe = matching_recipes[recipe_number - 1]["recipe"]
        print(f"\nRecipe: {selected_recipe.get('title', 'Title not available')}\n")
        print("Ingredients:")
        for ingredient in selected_recipe.get("ingredients", []):
            print(f"- {ingredient}")
        print("\nDirections:")
        for step, direction in enumerate(selected_recipe.get("directions", []), start=1):
            print(f"{step}. {direction}")

        create_pdf = messagebox.askyesno("Create PDF", "Do you want to create a PDF of this recipe so you can print it?")
        if create_pdf:
            create_recipe_pdf(selected_recipe)

    elif recipe_number is not None:
        print("\nInvalid recipe number.")

def create_recipe_pdf(recipe):
    try:
        pdf_file = f"{recipe.get('title', 'Recipe')}.pdf"

        if os.path.exists(pdf_file):
            confirm_override = messagebox.askyesno("File Exists", f"'{pdf_file}' already exists. Do you want to override it?")
            if not confirm_override:
                return

        doc = SimpleDocTemplate(pdf_file, pagesize=letter)
        styles = getSampleStyleSheet()
        story = []

        title = recipe.get('title', 'Title not available')
        title_text = Paragraph(f"<b>Recipe: {title}</b>", styles['Title'])
        story.append(title_text)

        story.append(Spacer(1, 12))

        ingredients_text = "<b>Ingredients:</b><br/>" + "<br/>".join(recipe.get("ingredients", []))
        ingredients = Paragraph(ingredients_text, styles['Normal'])
        story.append(ingredients)

        story.append(Spacer(1, 12))

        directions_label = Paragraph("<b>Directions:</b>", styles['Normal'])
        story.append(directions_label)

        directions = recipe.get("directions", [])
        for i, line in enumerate(directions, start=1):
            direction_text = f"{i}. {line}"
            direction = Paragraph(direction_text, styles['Normal'])
            story.append(direction)

        doc.build(story)
        messagebox.showinfo("PDF Created", f"Recipe PDF '{pdf_file}' created successfully.")
    except Exception as e:
        print(f"Error creating PDF: {e}")
        messagebox.showerror("PDF Error", "An error occurred while creating the PDF.")

if __name__ == "__main__":
    main()
```

### Stacktrace / full error message

```
No error message, just acts weird
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> When I print all the matching recipes, it doesn't finish printing all of them before prompting you with the selection tkinter window. For instance:
>
> pyinstaller compiled only prints up to 959 recipes before the tkinter window comes up with the indredients: "beef,tomato", whereas in python it prints 1218 and the scoring system. It finishes printing after the tkinter prompt with pyinstaller.


Which means you get an exception during execution, but because you are hiding the console, you don't get to see it:

```
Exception in thread Thread-1 (_forward_stdout):
Traceback (most recent call last):
  File "threading.py", line 1038, in _bootstrap_inner
  File "threading.py", line 975, in run
  File "gooey\gui\processor.py", line 70, in _forward_stdout
  File "gooey\gui\processor.py", line 84, in _extract_progress
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xae in position 13: invalid start byte
```

In my case, it stopped at
```
157. Mexican Stuffed Shells with Ground Beef (Score: 40)
```
and in original script the next line (which failed to be processed in frozen application) is:
```
158. NO YOLKS® Beef Noodle Casserole (Score: 40)
```

So that `®` is triggering an error.

Why? Because there is an encoding mismatch between the main process and the subprocess that `gooey` spawns.

They are trying to force the UTF8 encoding for the sub-process [by setting PYTHONIOENCODING](https://github.com/chriskiehl/Gooey/blob/be4b11b8f27f500e7326711641755ad44576d408/gooey/gui/processor.py#L91). However, PyInstaller-frozen applications are supposed to be isolated from the environment, so that environment variable is ignored, and the spawned subprocess ends up using local encoding (in my case `cp1252`).

I think a possible work-around is to set `PYTHONUTF8` at the beginning of your program, which will eventually force the sub-process into UTF8 mode (this works because that environment variable is one of the few that is honored by PyInstaller v5. In v6, it will also be ignored, but there you will be able to enable the UTF-8 mode via `-X utf8=1` run-time option):

```python
import os
os.environ['PYTHONUTF8'] = 1

from nltk.tokenize import RegexpTokenizer
...
```

But I suspect the problem could be avoided altogether if `gooey` used `universal_newlines`/`text` flag with their `subprocess.Popen` calls and stopped trying to manually decode the received `stdout`... (since it seems the issue is not limited to PyInstaller - chriskiehl/Gooey#852).

**Comment by tbrsvn** [comment]
It didn't work! Maybe it has to be encoded in something else.

**Comment by Norok-The-Diablo** [comment]
I'm going to keep trying things, I didn't have time this morning to test it in Linux. Maybe my JSON file isn't encoded in UTF-8

**Comment by tbrsvn** [comment]
I'm going to keep trying things, I didn't have time this morning to test it in Linux. Maybe my JSON file isn't encoded in UTF-8.

**Comment by rokm** [comment]
> I'm going to keep trying things, I didn't have time this morning to test it in Linux. Maybe my JSON file isn't encoded in UTF-8.

Nah, it's encoding mismatch between processes. You can reproduce it with:

```python
from gooey import Gooey, GooeyParser


@Gooey(program_name="Problem example", default_size=(800, 600))
def main():
    parser = GooeyParser(description="Reproduce the problem")
    args = parser.parse_args()
    print('®')
    

if __name__ == "__main__":
    main()
```

works unfrozen, raises `UnicodeDecodeError` when frozen.

**Comment by tbrsvn** [comment]
So how would I fix this? Do I have to go through the JSON file and remove special characters? I can probably make a program to do that.

**Comment by rokm** [comment]
> So how would I fix this? Do I have to go through the JSON file and remove special characters? I can probably make a program to do that.

This particular issue with `®` on Windows should be fixed by setting `PYTHONUTF8` at the start of your program. Your program works for me afterwards (or if I fix `gooey` to use `universal_newlines`/`text`). You mentioned linux - so are we still talking about Windows, or is this a linux issue now?

**Comment by tbrsvn** [comment]
I'm on windows, I was just offering to try it on Linux. I added that line and I still have the same issue. I do have a different JSON file then the download script that I'm using. Should I try the one the gets produced by my download script?

**Comment by rokm** [comment]
I've tested with the one produced by the download script. If you can upload the other JSON somewhere, I can take a look at it.

**Comment by tbrsvn** [comment]
Ahh ok, I'll link it when I get home

**Comment by rokm** [comment]
Although one thing I did notice now is that the dialog for entering the recipe number is shown too soon, and in the frozen application, it seems to block the processing until dismissed. EDIT: perhaps not processing per-se, but rather retrieval of the printed lines into the GUI...

**Comment by rokm** [comment]
And that might be fixed by doing a `sys.stdout.flush()` before you display the dialog.

**Comment by tbrsvn** [comment]
Where would I put the flush, sorry I'm asking so many elementary questions, but I'm pretty new to Python.

**Comment by rokm** [comment]
Before you display the dialog ([here](https://github.com/Norok-The-Diablo/recipefinder/blob/a552e7bd36fc24c095c702e85ef92a1172714526/RecipeFinder.py#L79)), since that will block the execution until the dialog is dismissed, and at that point, you want the whole stdout to be really printed out (so the GUI can pick it up and display it).

You might also do a pre-emptive flush after printing each recipe line ([here](https://github.com/Norok-The-Diablo/recipefinder/blob/a552e7bd36fc24c095c702e85ef92a1172714526/RecipeFinder.py#L73)).

**Comment by tbrsvn** [comment]
Thank you so much for the help, I'll test all of this when I get home at 5, and I'll send the link for my JSON.

**Comment by tbrsvn** [comment]
https://drive.google.com/file/d/1tlbqEQMQ_rkq2-bRXOxP9c_tXYay030t/view?usp=sharing, thats my json file. I have no clue what the difference is.

**Comment by rokm** [comment]
That file seems to work for me, once the program sets `PYTHONUTF8=1` and once stdout is flushed. 

Since you show several dialogs (recipe selection, PDF output), you should probably flush stdout before showing each of them, otherwise the output displayed in the `gooey` GUI might appear out of sync. Instead of explicitly calling `sys.stdout.flush()` you could also modify all your `print` statements into `print(..., flush=True)` to flush immediately after you write something to stdout.

**Comment by tbrsvn** [comment]
Strange, it doesn't work for me! Should I try a different version of python? What are you on?

**Comment by tbrsvn** [comment]
I did all the updates to the GitHub, maybe I missed something.

**Comment by rokm** [comment]
You forgot to add `import sys` at the top of your program. That doesn't influence the frozen program, though, because the bootstrap script imports it as well. But it won't work in unfrozen script.

> Strange, it doesn't work for me! Should I try a different version of python? What are you on?

I've tested with python 3.11.5 and PyInstaller 5.13.2 on Windows 10.

When you say it doesn't work, what exactly happens?

**Comment by tbrsvn** [comment]
I just re-compiled it but turned off my A.V. Turns out it was blocking a tmp file that pyinstaller uses. The program works perfectly now. Thank you so much for helping me! You are clearly an expert and this saved so much headache.
