### ISSUE TITLE
The PyInstaller library will package all the libraries I have installed during packaging

### ISSUE THREAD

**Issue by 1764364648** [pyinstaller/pyinstaller#7945]
The PyInstaller library will pack all the libraries I have installed when packing. Can you solve this problem in the next version and not pack all the libraries I have installed?

**Comment by 1764364648** [comment]
If all the installed libraries are packed, it will cause the application performance to decline and make the application larger.

**Comment by bwoodsend** [comment]
We can not. There are packages with *optional dependencies* where PyInstaller has no way of knowing which you do need and which you don't. To give you the common example, Pandas *optionally* depends on a range of database readers/writers, various visualisation libraries (matplotlib, seaborn) which can again utilise a range of GUI backends (all the Qts, wx, tkinter) or web based frameworks (including the entirety of Jupyter notebooks).

If you look inside the `build/*/xref-*.html` file, you can see the full chain of module imports that lead PyInstaller into thinking a given package was needed.

When you give it a package like that, PyInstaller's dependency scanner is useless without help. You can either `--exclude=unwantedpackage` the unwanted packages or build in a minimal virtual environment with only the packages you know you need installed.
