### ISSUE TITLE
PermissionError: Two .exe on Windows. An .exe runs the second one using Popen to remove the first one

### ISSUE THREAD

**Issue by AlberLC** [pyinstaller/pyinstaller#7965]
## Description of the issue

When I create two programs in Windows that execute each other, strange things happen.

I have a `program_1` that runs the exe from `program_2`. `program_2` attempts to delete the directory where `program_1` is located, it successfully deletes all content except the root directory which raises a `PermissionError` because the directory is in use (only this root directory remains, the rest is deleted).

Possibly it is the expected operation and it is not a bug but very strange things happen. For example, the working directory and MEIPASS point to different directories and it would not make sense for said directory to remain marked in use when the first program finished and all the program files could be deleted except for the root directory.

If this works well, could someone tell me a way to make two applications call each other so I can get one application to update the other (delete and paste the new files)?

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.0.0```
* Version of Python: `3.10.11`
* Platform: Windows 11 (spanish - Spain)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?
I didn't try.

* try the latest development version, using the following command:
`pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip`
Still the same.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

#### Dist directory structure:

**Before** run `program_1.exe`:
```
dist/
├─ program_1/
│  ├─ _internal/
│  │  └─ ...
│  └─ program_1.exe
└─ program_2/
   ├─ _internal/
   │  └─ ...
   └─ program_2.exe
```

**After** run `program_1.exe`:
```
dist/
├─ program_1/
│  └─ log.txt
└─ program_2/
   ├─ _internal/
   │  └─ ...
   └─ program_2.exe
```

`program_1` source:
```python
import subprocess

subprocess.Popen('../program_2/program_2.exe')
```

`program_2` source:
```python
import pathlib
import shutil
import sys
import traceback

try:
    shutil.rmtree('../program_1')
except PermissionError:
    pathlib.Path('log.txt').write_text(
        f'{traceback.format_exc()}\n'
        f'\n'
        f"{'working directory:':<20}{pathlib.Path.cwd()}\n"
        f"{'MEIPASS:':<20}{sys._MEIPASS}\n",
        encoding='utf-8'
    )
```

I expected `log.txt` to appear in the `program_2` directory, but it appeared in the `program_1` directory.

`dist/program_1/log.txt`:
```
Traceback (most recent call last):
  File "main_2.py", line 7, in <module>
  File "shutil.py", line 750, in rmtree
  File "shutil.py", line 624, in _rmtree_unsafe
  File "shutil.py", line 622, in _rmtree_unsafe
PermissionError: [WinError 32] El proceso no tiene acceso al archivo porque está siendo utilizado por otro proceso: '../program_1'


working directory:  <path to app>\dist\program_1
MEIPASS:            <path to app>\dist\program_2\_internal
```

`main.spec`:
```
# -*- mode: python ; coding: utf-8 -*-


# ---------------------------------------------------
# -------------------- program_1 --------------------
# ---------------------------------------------------
a_1 = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False
)
pyz_1 = PYZ(a_1.pure)

exe_1 = EXE(
    pyz_1,
    a_1.scripts,
    [],
    exclude_binaries=True,
    name='program_1',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None
)
coll_1 = COLLECT(
    exe_1,
    a_1.binaries,
    a_1.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='program_1'
)

# ---------------------------------------------------
# -------------------- program_2 --------------------
# ---------------------------------------------------
a_2 = Analysis(
    ['main_2.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False
)
pyz_2 = PYZ(a_2.pure)

exe_2 = EXE(
    pyz_2,
    a_2.scripts,
    [],
    exclude_binaries=True,
    name='program_2',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=False,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None
)
coll_2 = COLLECT(
    exe_2,
    a_2.binaries,
    a_2.datas,
    strip=False,
    upx=False,
    upx_exclude=[],
    name='program_2'
)
```

**Comment by rokm** [comment]
That's how current working directory works - it is inherited by the child process.

If you run `program1.exe` by double clicking on the executable, the current working directory is the executable's parent directory (`<path to app>\dist\program_1`). And if that executable spawns `program2.exe`, *its* current working directory remains the same. So if that second executable creates a file with a relative path, that path will be relative to `<path to app>\dist\program_1`. This also likely means that your second executable is also blocking the removal of the directory in question.

If you want the log file to appear next to the second executable, you would have to use something like `(pathlib.Path(sys.executable) / 'log.txt').write_text()`.

And you should not be using relative paths for the executables either, because that will fall apart if your current working directory is not the `<path to app>\dist\program_1`. For example if you open command prompt, and run the executable this way:
```
cd <path to app>
dist\program_1\program_1.exe
```

**Comment by AlberLC** [comment]
Okay, I got it. It's just that I've been tearing my hair out for 5 days to be able to self-update an app distributed with pyinstaller. 

The furthest I went was to create two apps so that one would overwrite the other but I have run into many problems and in the end with this one that I cannot solve.

Is there any way to achieve my goal?

**Comment by rokm** [comment]
If the problem is that the `program_1` directory is locked due to being current working directory for both programs, wouldn't it help if `program_1.exe` changed its current working directory (for example, to the parent `dist` directory) before running `program_2.exe`?

**Comment by AlberLC** [comment]
oh my!! thank you. Now that the problem has been reduced to that and you have given me the idea, I have been able to solve it.

I have used `os.chdir` from within `program_1` to change the working directory to the parent. Is it the correct way or is there another way?

**Comment by bwoodsend** [comment]
> I have used os.chdir from within program_1 to change the working directory to the parent. Is it the correct way or is there another way?

It'll work but it's not the correct way. The correct way is to anchor your paths like Rok suggested (although his example is supposed to say `(pathlib.Path(sys.executable).parent / 'log.txt').write_text()`
