### ISSUE TITLE
Unnecessarily large file size increase? (6mb -> 40mb)

### ISSUE THREAD

**Issue by ddinan** [pyinstaller/pyinstaller#7974]
I recently recompiled my script into a .exe but the file size was abnormally larger than its original counterpart. The original version was only 6mb (and was a standalone .exe, without any other files), but the new version is over 40mb. I want to make it as lightweight as possible and only want the single .exe file without the additional dependencies.

Command: `pyinstaller --icon=app.ico run.py -F`

Compiling without the -F parameter does work and the file size matches the original, but for some reason, when the .exe is moved to somewhere else, it closes immediately.

I'm not using any heavy packages, so I'm just not sure what could be causing the file size to be so large.

Packages used:

```python
from threading import Thread
from queue import Queue
from string import digits, ascii_uppercase
from itertools import product
import time
import requests
from os import path
from tqdm import tqdm
```

Is there another command I should be using to achieve the desired effect?

**Comment by rokm** [comment]
Does this also happen if you reduce the test program to just the imports you specified?

Because if I try to freeze such program in a minimal virtual environment (where I install `requests` and `tqdm`), the resulting `onefile` build is 6.8 MB.

**Comment by bwoodsend** [comment]
Only you are in a position to figure out what's changed. Use `pyi-archiveviewer` to see what's in the executable, look at the `build/*/*.toc` files to see the files PyInstaller collected, look at the `build/*/xref-*.html` file to see what modules were included.

**Comment by ddinan** [comment]
> Does this also happen if you reduce the test program to just the imports you specified?
> 
> Because if I try to freeze such program in a minimal virtual environment (where I install `requests` and `tqdm`), the resulting `onefile` build is 6.8 MB.

I've just tested with this code:

```python
from threading import Thread
from queue import Queue
from string import digits, ascii_uppercase
from itertools import product
import time
import requests
from os import path
from tqdm import tqdm

print("Hello!")
```

I have used the following command: `pyinstaller --onefile run.py` and the product is still a 40.8mb .exe file.

**Comment by ddinan** [comment]
> Only you are in a position to figure out what's changed. Use `pyi-archiveviewer` to see what's in the executable, look at the `build/*/*.toc` files to see the files PyInstaller collected, look at the `build/*/xref-*.html` file to see what modules were included.

I'm not entirely sure what I should be looking for here, the modules appear to be correct.

**Comment by rokm** [comment]
Either use `pyi-archive_viewer` utility to inspect the contents of the generated `onefile` build, or create a `onedir` build instead of `onefile` one, which you can then inspect using file browser. The idea is to determine what files were collected into the frozen application.

**Comment by CarlGao4** [comment]
I discovered that pyinstaller usually pack some unused modules into the package, since then I would always create a new virtual environment and uninstall all unused modules then use pyinstaller

**Comment by yixinBC** [comment]
I use pyinstxtractor-ng to unpack a exe and just found pyinstaller sometimes packed all the .pyd file inside the site-packages folder,which made that exe finally have up to 81.4MB.
You can find that exe on:https://github.com/Dr34nn/CRC_Cracker/releases/tag/v1.1.0
That exe also uses the `tqdm` module.
