### ISSUE TITLE
Windows defender detects virus when using --noconsole on pyinstaller 6.0.0 works fine on earlier versions

### ISSUE THREAD

**Issue by Saarlooswolf** [pyinstaller/pyinstaller#7976]
## Description of the issue
I am using windows 10 22h2 and when I use --noconsole or -w Windows defender stops pyinstaller from compiling into an exe because it detects a trojan. This only happens on pyinstaller 6 it works just fine on pyinstaller 5. I'm using python 3.11 and this happened on all of my apps with this version.
### Context information (for bug reports)

* Output of pyinstaller --version: 6.0.0
* Version of Python: 3.11
* Platform: Windows 10
* How you installed Python: microsoft store
* Did you also try this on another platform? Does it work there? No I only have windows 10

**Comment by bwoodsend** [comment]
Then it's Microsoft's bug -- not ours.

**Comment by nai-kon** [comment]
Same happened to me after 6.0.0
I'm using --noconsole --onedir

**Comment by bwoodsend** [comment]
Report it to Microsoft then. We have no control over their software.
