### ISSUE TITLE
Request: do not close application if owning console is closed

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#7986]
**Is your feature request related to a problem? Please describe.**
I tried `--hide-console hide-early` recently, and it's a great mix of being able to launch an app without a console (by double-clicking app.exe, or by running `start app.exe` from a terminal) and of being able to see console output (by launching `app.exe` from a terminal).

However, when I use the latter approach, closing the terminal seems to close the app.

**Describe the solution you'd like**
Optionally, closing the terminal should not close the app.

**Comment by rokm** [comment]
> However, when I use the latter approach, closing the terminal seems to close the app.

That's the OS-defined behavior, and we have no control over it.
