### ISSUE TITLE
Regression in 6.0.0 when bundling CuPy

### ISSUE THREAD

**Issue by pwuertz** [pyinstaller/pyinstaller#7988]
## Description of the issue

Bundled applications with `cupy` worked with PyInstaller 5.13.2 (+ custom hooks), but now fail when switching to PyInstaller 6.0.0.

The relevant error message at runtime is:
`ModuleNotFoundError: No module named 'cupy._core._carray'`

PyInstaller 5.13.2 correctly bundled this file:
`<application>\cupy\_core\_carray.cp311-win_amd64.pyd`

PyInstaller 6.0.0 does in fact bundle some of the `cupy\_core` files, such as
`<application>\_internal\cupy\_core\_dtype.cp311-win_amd64.pyd`,
but indeed misses `_carray.cp311-win_amd64.pyd`.

PyInstaller requries a custom hook for bundling `cupy`, this one worked with PyInstaller < 6 so far:

```python
# hook-cupy.py
from PyInstaller.utils.hooks import collect_all
datas, binaries, hiddenimports = collect_all("cupy")
hiddenimports += ["cupy_backends", "fastrlock", "fastrlock.rlock"]
```

The `collect_all` behavior in `6.0.0` seems to be the issue here. With `5.13.2`, the `datas` list from `collect_all("cupy")` contains all the `.pyd` files, but in `6.0.0` the `datas` list contains no `.pyd` files at all (`binaries` is empty in both cases).

### Context information (for bug reports)

* Output of `pyinstaller --version`: `6.0.0`
* Version of Python: 3.11
* Platform: Windows
* How you installed Python: python.org

### A minimal example program which shows the error

```python
import cupy
```

**Comment by rokm** [comment]
The .pyd files should not be in `datas`, as they are extensions/modules and not "data files" as PyInstaller defines them. So strictly speaking, the behavior change is intentional and not a regression. 

But `collect_all('cupy')` (and `collect_submodules('cupy')` that it calls should return `cupy._core._carray` among `hiddenimports` (and in v5, this was masked by .pyd files being among data files). I'll check why that is not happening.

**Comment by rokm** [comment]
If you run
```python
import pprint
from PyInstaller.utils.hooks import collect_submodules
pprint.pprint(collect_submodules('cupy'))
```
in your python environment, what is the output?

**Comment by pwuertz** [comment]
Oh, so if the `.pyd` files should have been in `hiddenimports`, not in `datas`, I probably just got lucky with v5. Does the `collect_submodules -> hiddenimports` process by any chance **require** the module to be importable at build time?

If so, my build environment in question wasn't able to `import cupy` since I didn't install all the 3rd-party libraries like CUDA-toolkit, assuming that pyinstaller would search `site-packages/cupy` and successfully pick up the `.pyd` files (which v5 did as `datas`).

With `CUDA_PATH` being set to a matching CUDA toolkit, pyinstaller 6 `collect_all` indeed now populates `hiddenimports` with all extension modules.

This is the intended behavior?

Specifically, `collect_submodules` requires modules to be importable at build time in order to find extensions? There is no option to do this statically?

**Comment by rokm** [comment]
> This is the intended behavior?

> Specifically, collect_submodules requires modules to be importable at build time in order to find extensions? There is no option to do this statically?

Yeah, that is indeed the case - PyInstaller is intended to be ran in the working environment, where modules are importable (i.e., so you can run your unfrozen code in that environment). So your use case with missing CUDA was not really supported in the first place, but the issue got masked by `collect_all` (which is part of why we'd like to discourage the use of it).

`collect_all` calls `collect_data_files` with `include_py_files=True`, which collects .py files and used to also collect .pyd files; so any modules missing from analysis - be it pure-python modules or extension modules, would still end up in the application bundle. The difference is that pure-python modules that were collected as part of "proper" analysis were collected as byte-compiled modules in executable-embedded PYZ archive, while the "missed" modules were collected just as source .py files (= "data files").

**Comment by rokm** [comment]
I *think* you can also collect un-importable modules (at least in some cases) by directly listing them in `hiddenimports`, but `collect_submodules` requires the packages (and sub-packages) to be importable, so it can walk over their modules.

---

But if you require the sort of static analysis that the old implementation of `collect_all` gave you, you could still programmatically list all .pyd files from package's directory, and add them to `binaries` (or `datas`, now that we have automatic binary-vs-data reclassification in place).

**Comment by pwuertz** [comment]
Thanks for the in-depth explanations!

So I should prefer using `collect_data_files/collect_dynamic_libs/collect_submodules` over `collect_all` in order to avoid bundling `.py` files as `datas` (if possible).

In situations where `import x` isn't desired (or just not possible) within a build environment, I should collect `hiddenimports` and/or `binaries` by walking the file tree (sort of a `collect_submodules_static` helper function), instead of using `collect_submodules`.

**Comment by pwuertz** [comment]
For reference, this seems to do the job for "friendly" packages:
```python
def collect_submodules_static(package: str) -> list[str]:
    """List all submodules of a given package without importing them."""
    import pkgutil
    import importlib
    from pathlib import Path

    # Find base folder for `package`-submodules
    package_spec = importlib.util.find_spec(package)
    assert len(package_spec.submodule_search_locations) == 1, "Expected single search location"
    package_folder = Path(package_spec.submodule_search_locations[0])
    assert package_folder.is_dir(), "Expected existing folder for search location"

    # List submodules recursively
    def iter_submodules(prefix: str, folder: Path):
        for submodule in pkgutil.iter_modules(path=[str(folder)]):
            name = f"{prefix}.{submodule.name}"
            yield name
            if submodule.ispkg:
                yield from iter_submodules(name, folder / submodule.name)

    return [package, *iter_submodules(package, package_folder)]
```

So my new `hook-cupy.py` with no-import-support is now:
```python
# hook-cupy.py
...
datas = collect_data_files("cupy")
binaries = collect_dynamic_libs("cupy")
hiddenimports = collect_submodules_static("cupy")
hiddenimports += ["cupy_backends", "fastrlock", "fastrlock.rlock"]
```

(verified with PyInstaller 6.0.0, CuPy 12.2.0, Python 3.11, Win & Linux)

**Comment by rokm** [comment]
Hmm, I suppose we are importing packages in our `collect_submodules` implementation because that is the only way to handle packages that modify their `__path__` during initialization. 

But we could think about falling back to the `importlib.util.find_spec()` and at least nominal package paths when a package cannot be imported.
