### ISSUE TITLE
How to propagate LD_LIBRARY_PATH (LDLP) in Pyinstaller 2.1

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#799]
**Original date**: 2013/10/15
**Original reporter**: *previn DOT lin AND gmail DOT  COOM *

I see solution for pyinstaller2.0 to propagate LD_LIBRARY_PATH (LDLP) in ticket #625 as below.

But seems this don't work for pyinstaller 2.1, any workround or suggestion if I want propagate LD_LIBRARY_PATH (LDLP) using pyinstalller 2.1? Thanks in advance!

**Comment by htgoebel** [comment]
Duplicate, #625 is still open and to be implemented.
