### ISSUE TITLE
Every call to joblib Parallel creates a new tkinter window on Linux

### ISSUE THREAD

**Issue by jesieleo** [pyinstaller/pyinstaller#7996]
## Description of the issue

This is a bug related to two libraries: `tkinter` and `joblib`.
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.0.0```
* Version of Python: ```3.11.5```
* Platform: ```GNU/Linux ubuntu```
* How you installed Python: ```anaconda```
* Did you also try this on another platform? Does it work there?
```No, not yet.```

### A minimal example program which shows the error

```
import multiprocessing
multiprocessing.freeze_support()

from joblib import Parallel, delayed
import tkinter as tk


def f():
    print('func called')


if __name__ == '__main__':
    root = tk.Tk()

    button = tk.Button(root,
                       command=lambda: Parallel(n_jobs=-1, backend='multiprocessing')(delayed(f)() for _ in range(1)),
                       text='func')
    button.pack()

    root.mainloop()
```
#6852

**Comment by jesieleo** [comment]
##   a workable solution
Useing multiprocessing instead of joblib 

```
import multiprocessing
multiprocessing.freeze_support()

#from joblib import Parallel, delayed
import tkinter as tk

def f(number):
    print('func called')

def call_f():
    with multiprocessing.Pool(multiprocessing.cpu_count()) as pool:
        pool.map(f,range(1))

if __name__ == '__main__':
    root = tk.Tk()

    button = tk.Button(root, command=call_f,text='func')
    button.pack()

    root.mainloop()
```

**Comment by rokm** [comment]
`multiprocessing` is the only multiprocessing framework that is supported by PyInstaller, and `joblib` by default uses `loky`, which is not supported.
