### ISSUE TITLE
Looking for help with troubleshooting the issue: The 'PyYAML>=3.01' distribution was not found and is required by the application

### ISSUE THREAD

**Issue by stanislaw** [pyinstaller/pyinstaller#8003]
## Description of the issue

Hello, thank you for creating this tool!

I had been using pyinstaller quite successfully until I encountered this issue, and I currently don't have a good idea on how to debug it. I didn't change anything with respect to the pyinstaller setup in the past several months. The [last successful CI job](https://github.com/strictdoc-project/strictdoc/pull/1309) was in September 22th. After that date, my pyinstaller jobs have been failing.

The manifestation in my tool StrictDoc is like this:

```
DistributionNotFound: The 'PyYAML>=3.01' distribution was not found and is required by the application
error: Parallelizer: One of the child processes has exited prematurely.
```

Before these lines, the PyInstaller's log shows only these lines relevant to PyYAML:

```
17221 WARNING: collect_data_files - skipping data collection for module 'PyYAML' as it is not a package.
17221 WARNING: collect_dynamic_libs - skipping library collection for module 'PyYAML' as it is not a package.
```

A bit of background: The PyYAML is imported indirectly by `pybtex` which is using a system of plugins, loading PyYAML dynamically at run time. I guess that this runtime magic can be the main contributor to the problem. I had previously configured PyYAML via a pyinstaller hook and it worked until this issue popped up: https://github.com/strictdoc-project/strictdoc/blob/4bafc582c615e8031c8226a25462dbb5af53f48a/developer/pyinstaller_hooks/hook-yaml.py

```
  File "strictdoc/backend/sdoc/models/type_system.py", line 104, in __init__
  File "pybtex/database/__init__.py", line 531, in from_string
  File "pybtex/database/__init__.py", line 321, in from_string
  File "pybtex/database/__init__.py", line 941, in parse_string
  File "pybtex/plugin/__init__.py", line 106, in find_plugin
  File "pybtex/plugin/__init__.py", line 80, in _load_entry_point
  File "pkg_resources/__init__.py", line 2517, in load
  File "pkg_resources/__init__.py", line 2540, in require
  File "pkg_resources/__init__.py", line 829, in resolve
  File "pkg_resources/__init__.py", line 870, in _resolve_dist
pkg_resources.DistributionNotFound: The 'PyYAML>=3.01' distribution was not found and is required by the application
```

**The important fact**: if I change the version of Python that runs the failing CI job from 3.10 or 3.11 to 3.7, the issue goes away, so it makes me think that there was a relatively recent regression in either pybtex or pyinstaller itself.

This is the command that I have been using for quite a while and it has always worked until September 22th+:

```
        pyinstaller
            --clean
            --name strictdoc
            --noconfirm
            --additional-hooks-dir developer/pyinstaller_hooks
            --distpath {path_to_pyi_dist}
            --hidden-import strictdoc.server.app
            --add-data strictdoc/export/html/templates:templates/html
            --add-data strictdoc/export/rst/templates:templates/rst
            --add-data strictdoc/export/dot/templates:templates/dot
            --add-data strictdoc/export/html/_static:_static
            --add-data strictdoc/export/html/_static_extra:_static_extra
            strictdoc/cli/main.py
```

The full log of the failing CI job can be found here:
https://github.com/strictdoc-project/strictdoc/actions/runs/6499710810/job/17653602959?pr=1325

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.0.0```

* Version of Python: 3.10 and 3.11 on GitHub Actions machines. At the same time, building with Python 3.7 works on GitHub Actions.
* Platform:  GitHub Actions CI machines: Ubuntu 22.04.3 and macOS 12.7 21G816
* How you installed Python: `Run actions/setup-python@v2 Successfully setup CPython (3.11.5)`
* Did you also try this on another platform? Does it work there?

I cannot reproduce this issue locally with Python 3.7.15 installed with pyenv and macOS 12.6.3. 

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

I have tried it and the result is still the same, here is the [failing job build log](https://github.com/strictdoc-project/strictdoc/actions/runs/6499933549/job/17654284006?pr=1325).

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

I am afraid I don't have sufficient time to understand the internals of pybtex and create an example that correctly isolates the issues. I hope that there could be quicker insights from the pyinstaller developers before I go harder on this issue.

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

I already showed the stacktrace above as I believe was logical within my description.

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by stanislaw** [comment]
cc @RobertoBagnara

**Comment by rokm** [comment]
`PyInstaller.utils.hooks.collect_all` expects importable (package) name (`yaml`), not dist name (`PyYAML`), so that hook you wrote for `yaml` is bogus. 

But, in PyInstaller 5.13.2 and earlier (which you get on python 3.7, since v6 dropped compatibility with 3.7), `collect_all` directly passed the package name to `copy_metadata`. The latter expects dist name - so this caused warnings when package name did not match dist name. So in 6.0.0, we now attempt to map passed package name to a dist name.

As a side effect, this breaks your hook. In your case, the `collect_submodules`/`collect_dynamic_libs`/`collect_data_files` part of `collect_all` never really worked (because `PyYAML` is not an importable package name), but `copy_metadata` did. Now, it doesn't work at all, because importable package name is strictly required for all parts.

Since your hook was effectively only ever using `copy_metadata` part of `collect_all`, you should switch that `collect_all` call with `datas = copy_metadata('PyYAML')`.

**Comment by stanislaw** [comment]
This is the razor-sharp answer I was hoping for! I have changed to `copy_metadata('PyYAML')` and it is working again now! Thank you very much for a very quick answer!
