### ISSUE TITLE
PyInstaller versions > 5.13.0 result in significantly slow startup times when packaging Django programs.

### ISSUE THREAD

**Issue by ghost** [pyinstaller/pyinstaller#8024]
When using PyInstaller version > 5.13.0 to package a Django program, the startup time takes more than 60 seconds+, while with PyInstaller version = 5.13.0, it only takes 5 seconds。

**Comment by bwoodsend** [comment]
Is this on Windows? It's most likely just an antivirus thing if it is.

**Comment by bwoodsend** [comment]
If not, I'll need an example django project which shows the problem.

**Comment by ghost** [comment]
Thank you, but this is the company's code and cannot be sent. We'll have to respect the company's decision.
