### ISSUE TITLE
App crashing after encountering cv2.VideoCapture(0)

### ISSUE THREAD

**Issue by saran-invitrace** [pyinstaller/pyinstaller#8026]
Before Introducing the problem, I worked on Mac OS Ventura 13.0, and Here’s tree of my workspace folder
```
├── app.py
├── opencv_cam.spec
└── ui
│    └── opencv_window.py
└── log
    └── error.log
```

My goal is to build a live webcam application using PySide6 framework and bundled by Pyinstaller
Here are the code of each file

```Python
# ui/opencv_window.py
from PySide6.QtCore import *
from PySide6.QtGui import *
from PySide6.QtWidgets import *
import cv2
import sys

# Utility function for logging into error.log
def log_at(x,log_file="/logs/error.log"):
    with open(log_file,"w") as f:
        f.write(str(x))

# My main widget
class MainWidget(QWidget):

    def __init__(self,app):
        QWidget.__init__(self)
        self.video_size = QSize(320, 240)
        self.setup_ui()
        self.setup_camera()

    def setup_ui(self):
        """Initialize widgets.
        """
        self.image_label = QLabel()
        self.image_label.setFixedSize(self.video_size)

        self.quit_button = QPushButton("Quit")
        self.quit_button.clicked.connect(self.close)

        self.main_layout = QVBoxLayout()
        self.main_layout.addWidget(self.image_label)
        self.main_layout.addWidget(self.quit_button)

        self.setLayout(self.main_layout)

    def setup_camera(self):
        """Initialize camera.
        """
			
        log_at("before VideoCapture")
        self.capture = cv2.VideoCapture(0)
        log_at("after VideoCapture")
        self.capture.set(cv2.CAP_PROP_FRAME_WIDTH, self.video_size.width())
        self.capture.set(cv2.CAP_PROP_FRAME_HEIGHT, self.video_size.height())

        self.timer = QTimer()
        self.timer.timeout.connect(self.display_video_stream)
        self.timer.start(30)

    def display_video_stream(self):
        """Read frame from camera and repaint QLabel widget.
        """
        
        _, frame = self.capture.read()
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame = cv2.flip(frame, 1)
        image = QImage(frame, frame.shape[1], frame.shape[0], 
                       frame.strides[0], QImage.Format_RGB888)
        self.image_label.setPixmap(QPixmap.fromImage(image))

if __name__ == "__main__":
    app = QApplication(sys.argv)
    win = MainWidget(app)
    win.show()
    sys.exit(app.exec_())
```

Here's my `app.py`

```Python
# app.py
import sys
import os

from PySide6.QtWidgets import *
from PySide6.QtGui import *
from ui.opencv_window import MainWidget
import os

def main():
    app = QApplication(sys.argv)
    win = MainWidget(app)
    win.show()
    sys.exit(app.exec_())

if __name__ == "__main__":
    # Use the same directory path as the python file
    os.chdir(os.path.dirname(__file__))
	
    try:
        main()

    # For debug log
    except Exception as e:
        import traceback
        with open('/logs/error.log', 'w') as f:
            traceback.print_exc(file=f)  # This will write the full traceback to the log file
```

Here’s the result when execute `python app.py
`![](https://file.notion.so/f/f/4bb0e75a-0f10-4313-9117-af22298079f2/a67b0912-f072-41ad-baf2-b880eca1975c/Untitled_design_(1).gif?id=76b35454-5648-44a3-a82c-1fd24caf32d1&table=block&spaceId=4bb0e75a-0f10-4313-9117-af22298079f2&expirationTimestamp=1697896800000&signature=RJtxibvwq-It2vIY21MrelTnO-Dg4QODxgrUCEYGzVo)

Everything is worked as expected, however, when I bundled this into `.app` file using the following spec files.

```Python
# pyinstaller opencv-cam.spec --noconfirm
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None
datas = []

a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='opencv-cam',
    debug=True,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='opencv-cam',
)
app = BUNDLE(
    coll,
    name='opencv-cam.app',
    icon=None,
    bundle_identifier=None,
)
```

Once run pyinstaller opencv-cam.spec, There is new folders; `build` and `dist`

```
├── app.py
├── opencv_cam.spec
└── ui
│    └── opencv_window.py
└── log
│   └── error.log
│    
└── build
│ 	└── ...
└── dist
		└── opencv-cam
		│ 	└── ...
	  └── opencv-cam.app
```

When I open [opencv-cam.app](http://opencv-cam.app/), The app is crashing. I wonder why it is crashing, so i take a look at  `log/error.log`

```
before VideoCapture
```

Instead of `after VideoCapture`, This mean the app is crashing before `after VideoCapture`, and after `before VideoCapture`, which is this line

```python
# ui/opencv_window.py
    def setup_camera(self):
        """Initialize camera.
        """			
        log_at("before VideoCapture")
        self.capture = cv2.VideoCapture(0)
        log_at("after VideoCapture")
```

This lead me to question, it does not even raise an exception, but it is crashing for unknown reason when it run until this line. My question is how to debug the problem, I want to know why it is crashing, is there anything i missing. 

Note : **pyinstaller** was in the same conda environment as opencv-python, Hence when Pyinstaller build a bundled app, it will download all packages and dependencies in that environment

## My Assumption : 
Assumption : Maybe it does not download all dependencies which support the process of opencv-python, for example, ffmpeg.dll.

**Comment by rokm** [comment]
So this is macOS with Anaconda python? Are packages (PySide6 and opencv) installed via conda or via pip?

**Comment by saran-invitrace** [comment]
Yes it Is macOS with Anaconda python 

I initialized a conda environment and install them via `pip`, hence, that those packages PySide6 and opencv are located at 
`/Users/saraninvitrace/miniconda3/envs/my-env/lib/python3.9/site-packages`

**Comment by rokm** [comment]
Hmmm... 

1) Any difference if you use `opencv-python-headless` instead of `opencv-python`? At least on linux, the GUI-enabled variant uses Qt5, so it might not play nicely with PySide6 in the frozen application (not sure about macOS - but you don't seem to be using OpenCV-provided UI anyway).

2) Any difference if you try open a video file instead of a camera?

**Comment by saran-invitrace** [comment]
1. Actually, I try all of opencv-python variants, and None of them is working 
- opencv-python-headless
- opencv-contrib-python-headless
- opencv-contrib-python

2.  It works! The app is not crashing when changing from
`self.capture = cv2.VideoCapture(0)`
to
`self.capture = cv2.VideoCapture("./resource/images/vid_sample.mp4")`

**Comment by rokm** [comment]
If video file works, then perhaps you need extra permissions for .app bundle to access camera?

https://developer.apple.com/documentation/avfoundation/capture_setup/requesting_authorization_to_capture_and_save_media

**Comment by rokm** [comment]
Maybe as a quick sanity check, does opening a camera work if you run the regular POSIX build (`dist/opencv-cam/opencv-cam`) instead of the .app bundle?

**Comment by saran-invitrace** [comment]
> Maybe as a quick sanity check, does opening a camera work if you run the regular POSIX build (`dist/opencv-cam/opencv-cam`) instead of the .app bundle?

Yes, this works !! I wonder why ?

**Comment by rokm** [comment]
Because POSIX programs have fewer restrictions than .app bundles.

As per docs I linked earlier, you'll need to ensure that your .app bundle's Info.plist contains a [NSCameraUsageDescription](https://developer.apple.com/documentation/bundleresources/information_property_list/nscamerausagedescription), so the OS asks the user to allow access (instead of just terminating your program).

Modify the .spec and add the following to the BUNDLE:

```python
app = BUNDLE(
    ...
    info_plist={
        'NSCameraUsageDescription': 'Camera access is required because...',
    },
)
```

Then rebuild using the modified .spec.

**Comment by saran-invitrace** [comment]
> 
> Modify the .spec and add the following to the BUNDLE:
> 
> ```python
> app = BUNDLE(
>     ...
>     info_plist={
>         'NSCameraUsageDescription': 'Camera access is required because...',
>     },
> )
> ```
> 
> Then rebuild using the modified .spec.


Thank you ! The app is no longer terminating!

The problem now is that the video is not rendered 
![](https://i.ibb.co/QMtTr5k/Screenshot-2566-10-21-at-11-12-07.png)



> Maybe as a quick sanity check, does opening a camera work if you run the regular POSIX build (`dist/opencv-cam/opencv-cam`) instead of the .app bundle?

Ps. This still works with video rendering

**Comment by saran-invitrace** [comment]
I also debug more on the value of ret and frame, and found out that the camera is not opened, although the camera is authorized

```Python
def display_video_stream(self):
        """Read frame from camera and repaint QLabel widget.
        """
        
        ret, frame = self.capture.read()
        log_at(f"{frame = }")
        log_at(f"{ret = }")

```

and in `error.log`

```
before VideoCapture
after VideoCapture
frame = None
ret = False
frame = None
ret = False
.
```

I'm not sure if it is because missing some dependencies ffmpeg or ..., but  it might not be the case since this application is able to read video file and the camera is opened in regular POSIX build

**Comment by rokm** [comment]
> but it might not be the case since this application is able to read video file and the camera is opened in regular POSIX build

Yeah, since it works in POSIX build, it is more likely to be an issue specific to .app bundles and their restrictions.

What if you run the .app bundle's executable from terminal, i.e., `./dist/opencv-cam.app/Contents/MacOS/opencv-cam`? Does that print any error messages to terminal?

**Comment by bwoodsend** [comment]
Did you get the permission prompt pop up?

<img width="372" alt="image" src="https://github.com/pyinstaller/pyinstaller/assets/30940778/a8d65975-748b-44de-8928-2b4ad1ae769d">

Once I'd accepted that and restarted the application, it started working.

**Comment by saran-invitrace** [comment]
> The problem now is that the video is not rendered ![](https://camo.githubusercontent.com/b9e562d716daae55a57f2566a3c13d1023fe8a44cb7b52774d8dd489b5c4c36e/68747470733a2f2f692e6962622e636f2f514d745472356b2f53637265656e73686f742d323536362d31302d32312d61742d31312d31322d30372e706e67)


^It's quite strange. The first time I tried, my camera didn't open. 
However, Now, when I attempted it again hours later, the camera finally started working!

**Comment by rokm** [comment]
Looks like you need to restart the application once you grant the access (or maybe reopening the capture would do the trick as well). But that's a problem in OpenCV.
