### ISSUE TITLE
Pyinstaller exe of wxPython app doesn't run on other computers

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#803]
**Original date**: 2013/10/17
**Original reporter**: *big12rich*

I have 64 bit windows 7 running 32 bit python 2.7 with pyinstaller 2.0 and 2.1.  I am trying to package a wxPython app I created and it doesn't want to function on computers that do not have a python version installed. Neither 2.0 or 2.1 can package an exe that works on a 32 bit computer.  On a virtual server it will flash the process briefly in the task manager.  Otherwise on a 32 bit windows XP machine it says the W2_32.dll is not a valid windows image.  That is the closest I became to having it functioning.  I originally built the app in 64 bit platform of python version 2.7 but then changed to 32 bit so it could be compatible across platforms.  I have Pywin32 installed and UPX and can successfully point to the directory for the app to be packaged with this tool.  The single file exe doesn't work as well.

**Comment by matysek** [comment]
Not enough info for debugging.
