### ISSUE TITLE
Update hook module loading to PEP-451

### ISSUE THREAD

**Issue by tjoloi** [pyinstaller/pyinstaller#8031]
Currently, the way hooks are loaded is through `importlib_load_source(self.hook_module_name, self.hook_filename)` found in `compat.py` which ends up using `importlib.Loader.load_module`. Unfortunately this way of loading modules is deprecated since 3.4 and, according to the warning and the documentation, is set to be removed in python 3.12.

The new way of loading modules from source is to use `importlib.abc.Loader.exec_module`, which requires a base ModuleType created using `types.ModuleType(loader.name)`. The function `importlib.abc.Loader.create_module` also exists to create a base ModuleType from a spec but this function returns `None` when "default module creation semantics should take place" which is the case for `SourceFileLoader` and, as far as I can tell, means using `types.ModuleType`.

I am not able to make the change and test it to open a pull request but the changes _should_ look a bit like this in `compat.py`:

Current
```
def importlib_load_source(name: str, pathname: str):
    # Import module from a file.
    mod_loader = importlib.machinery.SourceFileLoader(name, pathname)
    return mod_loader.load_module()
```

New
```
def importlib_load_source(name: str, pathname: str):
    # Import module from a file.
    mod_loader = importlib.machinery.SourceFileLoader(name, pathname)
    base_mod_type =  types.ModuleType(loader.name)
    return mod_loader.exec_module(base_mod_type)
```

This was causing an issue to me since the `load_module` function was throwing a silent warning which ended up as an error due to me using `warnings.simplefilter('error')` somewhere in my code. I do believe this is a _me_ issue, but also I believe that this is relevant to the project since it looks like the function is scheduled to be removed at one point in python 3.12

**Comment by bwoodsend** [comment]
Thanks for digging through to find the non deprecated version. Given that the 3.12 release has come and gone, we're presumably safe for another 10 months or so but there's no harm in getting it out the way.
