### ISSUE TITLE
Model loading fails in Pyinstaller-deployed app

### ISSUE THREAD

**Issue by schosdas** [pyinstaller/pyinstaller#8032]
I am trying to use a model.pt deployed through yolov5 and pytorch in opencv.
It works fine when running in Python, but there is a problem when deploying it as an exe and running it.

Here is my code:

```
    import cv2
    import torch
    from PIL import Image
    import sys
    # Load YOLOv5 model
    model = torch.hub.load('ultralytics/yolov5', 'custom', path='model.pt')   
    print("test")
    # opencv code.....
```

And my project structure is as follows:

```
    - build/
    - dist/
    - yolov5/
    - main.py
    - main.spec
    - model.pt
```

There is a problem in the part of my code where I load the model.
The following code is the code I originally tried to load the model. When I run it after deployment, I get an error that I can't find the ultralytics module.

`    model = torch.hub.load('ultralytics/yolov5', 'custom', path='model.pt')
`
To fix this, I added the corresponding module to the `hiddenimports` in main.spec and tried running it again, but the problem continued, such as not being able to find a file called ultralytics/default.yaml.

My main.spec code is as follows:

```
    a = Analysis(
        ['main.py'],
        pathex=[],
        binaries=[],
        datas=[('model.pt', '.')],
        hiddenimports=['ultralytics'],
        hookspath=[],
        hooksconfig={},
        runtime_hooks=[],
        excludes=[],
        noarchive=False,
    )
```

After deploying with pyinstaller main.spec and trying to run it in the terminal, I get the following error:

`    FileNotFoundError: [Errno 2] No such file or directory: \dist\main\_internal\ultralytics\cfg\default.yaml'
`
Upon checking the directory of the deployed app, I found that the ultralytics folder does not exist.

Can anyone tell me about this problem? 
Thank you.

**Comment by rokm** [comment]
You need to collect data files from the `ultralytics` package as well. For example, add `from PyInstaller.utils.hooks import collect_data_files` at the top of the specs, then modify `datas` argument to `Analysis` to `datas=[('model.pt', '.')] + collect_data_files('ultralytics')`.

Also,

>     model = torch.hub.load('ultralytics/yolov5', 'custom', path='model.pt')   

That path to model should very likely be anchored to avoid assumptions about current working directory; `path=os.path.join(os.path.dirname(__file__), 'model-pt')`.
