### ISSUE TITLE
PyInstaller 5.13.2 not published to conda-forge

### ISSUE THREAD

**Issue by ejwcobra** [pyinstaller/pyinstaller#8034]
I have a small program I maintain that uses PyInstaller, and I manage my Python compile environment with Conda.  I’m trying to upgrade to PyInstaller 5.13.2, but that version doesn’t exist in conda-forge.  However, I do see 5.13.0, as well as nearly every other PyInstaller version.  Could PyInstaller 5.13.2 be published to conda-forge?
https://anaconda.org/conda-forge/pyinstaller/files

**Comment by rokm** [comment]
This is wrong place to ask for Anaconda packages and updates, as we have nothing to do with those.

**Comment by bwoodsend** [comment]
Try https://github.com/conda-forge/pyinstaller-feedstock/ instead. That said, please do not use PyInstaller on Anaconda. On a good day, the applications it builds are 2-10x larger and obviously broken. On other days, it's 2-10x larger and subtly broken.
