### ISSUE TITLE
update manual with python 3 details

### ISSUE THREAD

**Issue by matysek** [pyinstaller/pyinstaller#804]
**Original date**: 2013/10/21

We should update manual with Python 3 instructions when Python3 support is added.
 - Python 3.3 has built-in support for virtualenvironments. Command *pyvenv* or *pyvenv-3.3*

**Comment by matysek** [comment]
@tallforasmurf assigning this to you since you are working on manual.

**Comment by tallforasmurf** [comment]
I added one sentence to the paragraph where we recommend virtualenv. I don't want to take virtualenv out entirely because we still support 2.7 and probably will forever. Anyway if someone was porting from 2.7 with VENV, would they change to pyvenv? Prbly not.
