### ISSUE TITLE
Command not regonized

### ISSUE THREAD

**Issue by GevaX** [pyinstaller/pyinstaller#8044]
I have installed pyinstaller using pip install pyinstaller
but when i do the command it shows:
PS E:\Documents\Robotics\Masterpiece\Codes\Testing> pyinstaller rps.py  
pyinstaller : The term 'pyinstaller' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path is 
correct and try again.
At line:1 char:1
+ pyinstaller rps.py
+ ~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (pyinstaller:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by rokm** [comment]
You need to add your python environment's `Scripts` directory to `PATH`. `pip install pyinstaller` very likely warned you about this. If you don't know how to do that, run `PyInstaller` as a module instead - i.e., `python -m PyInstaller ...`.

**Comment by GevaX** [comment]
Thanks that worked using the python -m PyInstaller
