### ISSUE TITLE
No module names 'skimage.data._fetchers'

### ISSUE THREAD

**Issue by pythonPleiades** [pyinstaller/pyinstaller#8051]
Program works well under PyCharm and converted to an executable file using auto-py-to-exe without error. The only issue during the conversion is 431318 WARNING: Hidden import "sip" not found! The executable file start without issue but an error occur while registering images using the module Astroalign. Here the traceback:

File "main.py", line 20, in <module>
File "PyInstaller\loader\pyimod02_importers.py", line 352, in exec_module
File "skimage\__init__.py", line 141, in <module>
File "lazy loader\__init__.py, line 76, in __getarr__
File "importlib\__init__.py, line 126, in import_module
ModuleNotFoundError: No module named 'skimage.data._fetchers'
[6968] Failed to execute script 'main' due to unhandled exception!

From other posts, I tried pip install -U setuptools but didn't rectify the issue
I re-install scikit_image but didn't rectify the issue.

any suggestions? I'm new at python.

**Comment by rokm** [comment]
What versions of `scikit-image`, `PyInstaller`, and `pyinstaller-hooks-contrib` are you using?

**Comment by pythonPleiades** [comment]
scikit_image: 0.20.0
PyInstaller: 5.9.0
PyInstaller-hooks-contrib: 2023.1

Thanks for the reply.

**Comment by rokm** [comment]
`scikit-image` 0.20.0 requires `pyInstaller-hooks-contrib` >= 2023.2. (and 0.22.0 requires >= 2023.10).

**Comment by pythonPleiades** [comment]
I upgrade the packages and now working perfectly. Thanks for your help.
