### ISSUE TITLE
Does the latest  pyinstaller 6.1 not support the latest pyarmor 8.4.2? 

### ISSUE THREAD

**Issue by 17Reset** [pyinstaller/pyinstaller#8056]
I'm using pyarmor on Python 312 to protect my project and then using pyinstaller to package it, but the packaged project runs with an error and doesn't report any errors, so I'm guessing if it's an incompatibility between the two?

**Comment by rokm** [comment]
We don't support `pyarmor` (or any other 3rd party tool) per-se, so if there is an incompatibility, you should report it to them.

**Comment by 17Reset** [comment]
Okay. Thank you very much.
