### ISSUE TITLE
MacOS: Wrong path when seaching for Python

### ISSUE THREAD

**Issue by SpecialCharacter** [pyinstaller/pyinstaller#8059]
MacOS: Catalina 10.15.7 (too old for brew)
Python: 3.12.0, installed via python.org/downloads
Pyinstaller: 6.1.0

Pyinstaller searches for Python in `~*build*/<program>/_internal/Python,` but `_internal` is under `~*dist*/<program>/_internal/Python`.

Yesterday I was able to get my program running by copying `_internal` from `*dist*` to `*build*`, but today it won't run.

**Comment by rokm** [comment]
You should be running `dist/<program>/<program>`, not `build/<program>/<program>`. The `dist` directory contains your final frozen application, while `build` directory contains intermediate build results.
