### ISSUE TITLE
Pyinstaller crashing with "trace trap"

### ISSUE THREAD

**Issue by DH-Engineering** [pyinstaller/pyinstaller#8065]
I'm using MacOS Ventura
Kyvi 2.2.x
Python 3.9.2
PyInstaller: 6.1.0

My python applications using a Kyvi UI and working well without bundling. 
I'm bundling my app using a spec file. This has worked in the past. But lately the binary is crashing on the console with:
[1]    38625 trace trap 

The MacOS package is not starting either. 
The internet says a trace trap issue is caused by a debugger. But im not using any debugger mode with that app.

I set some print() at the main loop of the program. As it is not printing on the console I assume the app crashes already without running into the code. 

Can you please let me know how to debug this further or what could be wrong with configuration

Thank you

**Comment by rokm** [comment]
Can we see the spec file?

**Comment by DH-Engineering** [comment]
``` 
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['filedialog.py'],
    pathex=[],
    binaries=[],
    datas=[('logs/testSuite.log', '.'), ('example.csv', '.'), ('file.conf', '.'), ('*.icns', '.'), ('*.kv', '.')],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
 
)


pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='Kwarterli',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file='entitlements.plist',
    icon='icon.icns',
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    a.excludes,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='Kwarterli2d'
)

app = BUNDLE(
    exe,
    name='xxx.app',
    icon='icon.icns',
    bundle_identifier='xxxxx',
    info_plist={
        'NSPrincipalClass': 'NSApplication',
        'NSAppleScriptEnabled': False,
        'LSBackgroundOnly': False,
        'NSRequiresAquaSystemAppearance': 'No',
        'CFBundlePackageType': 'APPL',
        'CFBundleSupportedPlatforms': ['MacOSX'],
        'CFBundleIdentifier': 'xxxxx',
        'CFBundleVersion': '1.0.7',
        'LSMinimumSystemVersion': '12.00',
        'LSApplicationCategoryType': 'public.app-category.utilities',
        'ITSAppUsesNonExemptEncryption': False,
    }
)
```

**Comment by rokm** [comment]
This looks like you manually stitched together a `onefile` and a `onedir` template. If your end-goal is an .app bundle, you should start from a clean `onedir` template  (`pyinstaller --onedir --windowed filedialog.py` or `pyi-makespec --onedir --windowed filedialog.py`), and then add in relevant fields, without modifying how members of `Analysis` (`a.binaries`, `a.datafiles`, etc.) are passed around.

**Comment by rokm** [comment]
Also, are you code-signing your .app bundle and enabling hardened run-time? The executable created by that spec file has `onefile` semantics, so hardened run-time will terminate it as it tries to unpack itself.

**Comment by DH-Engineering** [comment]
No I did not code sign this .app. 
This are my entitlements:

	<key>com.apple.security.cs.allow-jit</key>
	<true/>
	<key>com.apple.security.cs.allow-unsigned-executable-memory</key>
	<true/>
    <key>com.apple.security.cs.disable-library-validation</key>
    <true/>
    <key>com.apple.security.app-sandbox</key>
    <true/>

Would codesigning be required?

**Comment by rokm** [comment]
> No I did not code sign this .app. This are my entitlements:
> 
> ```
> <key>com.apple.security.cs.allow-jit</key>
> <true/>
> <key>com.apple.security.cs.allow-unsigned-executable-memory</key>
> <true/>
> <key>com.apple.security.cs.disable-library-validation</key>
> <true/>
> <key>com.apple.security.app-sandbox</key>
> <true/>
> ```
> 
> Would codesigning be required?

No, it shouldn't. But if it were enabled, it would explain why you are getting the crash.

So the next candidate is this:

> ```
>     console=True,
> ```

which should be `False` for .app bundles, which require a special variant of the bootloader (we've seen this before - https://github.com/pyinstaller/pyinstaller/issues/7123#issuecomment-1267549677). Does changing it help? (FWIW, you should still start with a clean `--onedir --windowed` template...)

**Comment by DH-Engineering** [comment]
Thanks for the help so far. It was hinting me in the right directions. The spec file I posted above is working if I set entitlements_file=None. But I want to submit in the Apple Appstore. So this entitlements needs to be set. 
Any idea? BTW I need an onfile app

**Comment by rokm** [comment]
> The spec file I posted above is working if I set entitlements_file=None

Ah, so perhaps it is not hardened run-time, but sandbox (`com.apple.security.app-sandbox`) that prevents unpacking behavior.

> But I want to submit in the Apple Appstore.

Then you will need code-signing and notarization, and that requires hardened run-time. So onefile builds (intentional or unintentional) are out of question.

**Comment by DH-Engineering** [comment]
So hardened runtime would only work with ondir and onfile apps? What Is the limitation? 
Onefile is half the size, starts faster and codes is hidden.

**Comment by rokm** [comment]
> So hardened runtime would only work with ondir and onfile apps? What Is the limitation?

I think sandboxing (or could be a hardened runtime) prevents the application from unpacking itself. Which makes sense, as a security measure - otherwise application could smuggle additional unchecked binaries. Also, in onefile, binaries are in the embedded archive, so you cannot post-hoc codesign them; I also imagine this is a problem for notarization process (otherwise, there would be little point to it in the first place).

> Onefile is half the size

That very much depends on your perspective; during application run-time, it is the size of onefile executable, plus the size of unpacked archive (which would be the size of onedir app). And for distribution, the onedir .app bundle would likely be placed inside a .dmg, so compression there would take care of size at distribution time. 

> starts faster

It does not - it needs to be extracted on each run, and the OS typically scans the contents on each run as well (since from its perspective, it is always "new").

>  codes is hidden

One can always check and extract the contents of executable-embedded archive. Either using PyInstaller's own `pyi-archive_viewer`, or using 3rd party tools.
