### ISSUE TITLE
Unable to see .exe file in file explorer, but it exists in terminal. 

### ISSUE THREAD

**Issue by Corey4005** [pyinstaller/pyinstaller#8072]
## Description of the issue
I can see the .exe file in my terminal, but I am unable to view it in my file explorer. 
### Context information (for bug reports)
Here is an image of the terminal showing the exe file:
![image](https://github.com/pyinstaller/pyinstaller/assets/74572313/4aebdd30-3423-422b-b29e-40575b3b5e1f)

Here is an image showing that the file explorer is "empty":
![image](https://github.com/pyinstaller/pyinstaller/assets/74572313/0dfa1b4d-c2de-4035-bdf8-04ed620c20c2)

* Output of `pyinstaller --version`: ```(6.1.0)```
* Version of Python: Python 3.12
* Platform: Windows 10 (English)
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
No I have not tried it on another platform. 

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
You're not comparing the same location, though, are you?

In the terminal, the location is 
```
c:\Users\Corey4005\Desktop\repos\aquatron\virt\dist
```

and in Explorer, the location seems to be

```
c:\Users\Corey4005\Desktop\repos\aquatron-repo\aquatron\virt\dist
```

instead.

**Comment by bwoodsend** [comment]
You can open the terminal's current directory in explorer by typing `start .` or open expoler's directory in terminal by type `cmd` into the address bar.

**Comment by Corey4005** [comment]
> You're not comparing the same location, though, are you?
> 
> In the terminal, the location is
> 
> ```
> c:\Users\Corey4005\Desktop\repos\aquatron\virt\dist
> ```
> 
> and in Explorer, the location seems to be
> 
> ```
> c:\Users\Corey4005\Desktop\repos\aquatron-repo\aquatron\virt\dist
> ```
> 
> instead.

I am so sorry. LOL. I was in the wrong spot. I had copied some directories over to another file because I was rebuilding the environment and 100% forgot to delete the old dir. I found the exe lol.

**Comment by Corey4005** [comment]
> You can open the terminal's current directory in explorer by typing `start .` or open expoler's directory in terminal by type `cmd` into the address bar.

Thanks for closing and for the advice. I found it. I accidentally was looking in a similar but wrong directory.
