### ISSUE TITLE
Regression: `datas` moved to `_internal` in pyinstaller 6.1.0. pyinstaller 5.13.1 puts `datas` in correct directory

### ISSUE THREAD

**Issue by djsamseng** [pyinstaller/pyinstaller#8075]
## Description of the issue
In version 6.1.0 `datas` are bundled into the `_internal` folder. Per the [spec file documentation](https://pyinstaller.org/en/stable/spec-files.html#adding-data-files) this should go to the folder specified. In version 5.13.1 `datas` are bundled correctly into the destination folder.

Narrowing the scope: 5.13.2 works correctly but 6.0.0 does not

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.1.0```
* Version of Python: 3.8
* Platform: Linux (Ubuntu)
* How you installed Python: Default python installation
* Did you also try this on another platform? Does it work there? `No`

### A minimal example program which shows the error

```bash
pip3 install pyinstaller==5.13.1
pyinstaller EOD-Robot.spec
ls ./dist/EOD-Robot/assets
# Exists and all contents present
ls ./dist/EOD-Robot/config.ini
# File exists

pip3 install pyinstaller==6.1.0
pyinstaller EOD-Robot.spec
ls ./dist/EOD-Robot/assets
ls: cannot access './dist/EOD-Robot/assets': No such file or directory
ls ./dist/EOD-Robot/config.ini
ls: cannot access './dist/EOD-Robot/config.ini': No such file or directory
ls ./dist/EOD-Robot/_internal/assets
# Exists and all contents present
ls ./dist/EOD-Robot/_internal/config.ini
# File exists
```

Spec file
```
# -*- mode: python ; coding: utf-8 -*-


block_cipher = None


a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ("assets/*.png", "assets"),
        ("assets/*.ico", "assets"),
        ("assets/__init__.py", "assets"),
        ("config.ini", ".")
    ],
    hiddenimports=['PIL._tkinter_finder'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='EOD-Robot',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['assets/App_no_bg.ico'],
)

coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='EOD-Robot',
)
```

**Comment by rokm** [comment]
This is [a documented incompatible change for v6.0](https://pyinstaller.org/en/stable/CHANGES.html#incompatible-changes) (see #7713).

> In version 6.1.0 `datas` are bundled into the `_internal` folder. Per the [spec file documentation](https://pyinstaller.org/en/stable/spec-files.html#adding-data-files) this should go to the folder specified. In version 5.13.1 `datas` are bundled correctly into the destination folder.

They should go to the specified folder under *top-level application directory*. Which for onedir builds used to be the same directory as the executable, but from v6.0 on, it is the `_internal` subdirectory (so everything but executable is collected in there). If you want the old v5.x layout for whatever reason, you can add `contents_directory='.'` argument to `EXE` (requires v6.1; see #7968).
