### ISSUE TITLE
Multiprocessing hook on MacOS will raise an error

### ISSUE THREAD

**Issue by mkb79** [pyinstaller/pyinstaller#8080]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.1.0```
* Version of Python: 3.10, 3.11 and 3.12 tested
* Platform: MacOS
* How you installed Python: brew
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

See [this](https://github.com/mkb79/audible-cli/issues/78#issuecomment-1795516280) comment.

### Stacktrace / full error message

See [this](https://github.com/mkb79/audible-cli/issues/78#issuecomment-1795516280) comment.

When using `pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py` with my package the error above occurs on MacOS when executing the binary. Debian 11/12 is running fine. Windows is untested yet. 

The created binary will be executed. But when the command is finished, the command `audible -B -S -E -s -c from multiprocessing.resource_tracker import main;main(15)` is executed by the shell.

It seems that the `pyi_rth_multiprocessing` hook will cause the issue. When using `pyinstaller --clean -F --hidden-import audible_cli -n audible -c pyi_entrypoint.py --exclude-module multiprocessing` all is running fine.

**Comment by rokm** [comment]
You've got it backwards, actually. 

The `pyi_rth_multiprocessing` run-time is there to catch and divert the program flow of `multiprocessing` child processes (either worker processes or the helper processes, such as the resource tracker). But in order for it to work correctly (or rather, at all), you need to call [`multiprocessing.freeze_support`](https://docs.python.org/3/library/multiprocessing.html#multiprocessing.freeze_support) before using any `multiprocessing` functionality (so it is best to call it at the very start of your program). 

(Note that python docs say it is required only on Windows, but that is for their original implementation, which probably caters to `py2exe`. In PyInstaller's case, you need to call this function whenever `spawn` start method is used; currently this is the default on macOS and Windows, but python also plans to change it on linux from `fork` to `spawn`).

**Comment by mkb79** [comment]
@rokm 
Thank you for your quick reply. I've tried it with `multiprocessing.freeze_support` already. But this will result in a „frozen“ shell after command execution. I'll had to press CTRL+C to abort. 

But why `audible -B -S -E -s -c from multiprocessing.resource_tracker import main;main(15)` is executed by the MacOS shell? Is it perhaps because I use Click with subcommands?

I'm think the following lines in the multiprocessing hook will cause the error:

```python
    if (
            len(sys.argv) >= 2 and sys.argv[-2] == '-c' and sys.argv[-1].startswith(
                ('from multiprocessing.resource_tracker import main', 'from multiprocessing.forkserver import main')
            ) and set(sys.argv[1:-2]) == set(_args_from_interpreter_flags())
        ):
            exec(sys.argv[-1])
            sys.exit()
```

The command args will not be processed correctly?

**Comment by rokm** [comment]
> But why `audible -B -S -E -s -c from multiprocessing.resource_tracker import main;main(15)` is executed by the MacOS shell? 

What do you mean, by "executed by MacOS shell"? The subprocess is spawned by your main process. And contrary to unfrozen python script where it would be spawned as `python -B -S -E -s -c from multiprocessing.resource_tracker import main;main(15)`, in the frozen application, the executable is called.

So if you use `click`, you will probably need to call `freeze_support` before setting up `click` and its CLI parsing.

**Comment by mkb79** [comment]
@rokm 
In my case `audible -B -S -E -s -c from multiprocessing.resource_tracker import main;main(15)` and not `python -B -S -E -s -c from multiprocessing.resource_tracker import main;main(15)` is executed by the shell. So here must something going wrong. Because my command does not have a `-B` flag the error occurs.

**Comment by rokm** [comment]
So what happens if you change your `pyi_entrypoint.py` into:

```python
import multiprocessing
multiprocessing.freeze_support()

from audible_cli import cli
cli.main()
```

**Comment by mkb79** [comment]
I'll rewrote my `pyi_entrypoint.py` this way yesterday. As I wrote above, this will result in a hanging shell after the command is running successfully. The command have to be aborted with CTRL+C.

**Comment by rokm** [comment]
Is there a way for me to test this without Audible account?

**Comment by mkb79** [comment]
You can run the command without an Audible account. In that case `error: Config file […] does not exists` appears. But I does not know if the same errors as described in my issue appears. I don’t have tested this. 

I'll using this entrypoint script to show the output:

```python
import sys


print(sys.argv)

from audible_cli import cli
cli.main()
```

This will print me out two commands. The origin command which I entered in my shell and `audible -B -S -E -s -c from multiprocessing.resource_tracker import main;main(15)`.

**Comment by mkb79** [comment]
So the entrypoint script must be executed twice.

**Comment by rokm** [comment]
> So the entrypoint script must be executed twice.

Entry-point script should be executed for each spawned subprocess; in the frozen application, there's no other way. But the resource tracker one should be trapped by `freeze_support`.

**Comment by rokm** [comment]
Which you can verify with:

```python
import sys
import multiprocessing

print("A:", sys.argv)
multiprocessing.freeze_support()
print("B:", sys.argv)

from audible_cli import cli
cli.main()
```

So I guess if this is freezing your shell after completion, that's the part you should be looking into, instead of omitting `freeze_support`.

**Comment by mkb79** [comment]
I'll try it later, as I don't have a Mac available right now.

My package don’t use the `multiprocessing` module. I'll have to find out if my dependencies use this. If not, and I don’t find another solution for the hanging shell, I'll exclude multiprocessing when using pyinstaller.

**Comment by rokm** [comment]
> My package don’t use the multiprocessing module. 

It makes no difference if you use it directly or one of the dependencies does.

> I'll have to find out if my dependencies use this.

You can check the `build/{name}/xref-{name}.html` file to see what packages are importing `multiprocessing` (`rsa.parallel` and `tqdm.std` come up in my local build). Something is using some part of `multiprocessing` at runtime, otherwise the resource tracker would not have been spawned. Could be that the codepath in question is optional though, since you seem to get away with excluding `multiprocessing`.

**Comment by mkb79** [comment]
Thank you for your explanation and time. I'll try it out to fix the hanging shell issue. This is the best way to prevent other drawbacks.
