### ISSUE TITLE
At "Loading module hook" it's taking too much time, hope this can be speeded up

### ISSUE THREAD

**Issue by roydad** [pyinstaller/pyinstaller#8091]
**Is your feature request related to a problem? Please describe.**
windows version
At "Loading module hook" it's taking too much time, hope this can be speeded up

**Describe the solution you'd like**
 A hook cache can be created on first packaging,
When packaging for the second time, If the code has not changed, the hook caching can be called to save time

**Comment by rokm** [comment]
The analysis and intermediate build targets are already cached in your local `build` directory, so running the build process against unchanged code already skips analysis and re-uses the cached results (unless you use `--clean` option that forces a clean rebuild). 

There is no plan to introduce any global caching for analysis/hooks (across different builds), though, if that is what you are asking for.
