### ISSUE TITLE
eggs folder not handled properly (MEIPASS not found, etc.)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#810]
**Original date**: 2013/10/30
**Original reporter**: *mcfly_6464 AND yahoo DOT  COOM *

I am creating a single file executable with PyInstaller 2.1.  I employ the resource_path below to grab my data files when needed.  The exe builds fine but I get an error when trying to run the exe that says it cant find the temp folder.  

```

def resource_path(relative_path):

    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except Exception:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)
```

When I run the py file (within IDLE), my app runs perfectly and loads all of the data files. However, when I bundle it with PyInstaller 2.1 (one file method) I get the following error after the exe builds:

```
Traceback (most recent call last):
File "<string>", line 37, in <module>
WindowsError: [Error 3] The system cannot find the path   
specified: 'C:\\Users\\Me\\AppData\\Local\\Temp\\_MEI188722\\eggs/*.*'
```

**Comment by htgoebel** [comment]
This is an old issue, we never managed to reproduce, and my request for restarting the search is 10 month old without answer. So I'm closing this as invalid.
