### ISSUE TITLE
Closing EXE does not exit cleanly

### ISSUE THREAD

**Issue by tester0077** [pyinstaller/pyinstaller#8100]
After creating an exe from a python project, running the project file works OK ,but on exit it leaves a remnant in memeory, which needs to be killed with task manager

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.1.0```
* Version of Python: Python 3.9.0
* Platform: Win 11 64-bit
* How you installed Python:  python.org/downloads
* Did you also try this on another platform? No Does it work there?????

* try the latest development version, using the following command:
 fails with:
```
      error: could not open 'PyInstaller\bootloader\Windows-32bit-intel\run.exe': Invalid argument
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pyinstaller
Failed to build pyinstaller
ERROR: Could not build wheels for pyinstaller, which is required to install pyproject.toml-based projects
WARNING: There was an error checking the latest version of pip.
PS D:\pkg\python\wpBG>
```
Note, if you ask to install software, please also include instructions on how to reverse this installation
```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
With develop version??
running exe from DOS box leaves something behind which a background process named wpBG.exe which prevents the app from starting properly. While this background process is on the task manager list, the app will load but without any tool bar icons and is thus pretty useless.

If started from the PS prompt, it will start with the icons visible, but on exit it too will leave a (/another) copy of wpBG.exe on the task list.
In either case, the prompt will not appear again until the 'left-over' task is killed.

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and
Without instructions on how to clean up, that will be needed in any case.
### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

FWIW, --noupx made no difference
Simply opening & closing the app, without executing it intended function give the same behavior
After startup, the app shows up as one of the tasks, when it it closed down, either from the menu or Alt-F4, it moves to background tasks.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Can you provide a minimal code example that reproduces this issue? Otherwise this is pretty much inactionable on our part, since we have no idea what your code actually does, what packages/frameworks it is using, and so on.

**Comment by tester0077** [comment]
Being very new to Python, wxPython & PyInstaller I was unsure of how to go about creating a minimum example, but after a bit of experimenting, I think I have narrowed down the issue to a single statement
```
#!/usr/bin/python3
"""
    My test project
"""
import wx               # pip install wxPython
#import the wxFB created GUI file 
import wpBgBase  
[wpBGtest.zip](https://github.com/pyinstaller/pyinstaller/files/13339638/wpBGtest.zip)

#=====================================================
class MyFrameAui(wpBgBase.MyFrameAui):
    def __init__(self,parent):
        #super().__init__(None)    <<<<<<<<<<<<<<<< including this line causes the issue
        wpBgBase.MyFrameAui.__init__(self,parent) 
# ===================================================        
app = wx.App(False) 
frame = MyFrameAui(None) 
frame.Show(True) 
#start the applications 
app.MainLoop() 
# ------------------------------- eof ------------------------------
```
I have attached a zip file with the 2 py files as well as the graphics used.

**Comment by bwoodsend** [comment]
That zip attachment hasn't actually attached.

**Comment by rokm** [comment]
> That zip attachment hasn't actually attached.

It has (can be downloaded via the URL), but the markup is probably mangled due to being inside the code block.

---

> ```
> #super().__init__(None)    <<<<<<<<<<<<<<<< including this line causes the issue
> ```

@tester0077 : to clarify, including the line *instead* of the second one, like this:
```python
def __init__(self,parent):
        super().__init__(None)
```

or including it *together* with the second one, line this:

```python
def __init__(self,parent):
        super().__init__(None)
        wpBgBase.MyFrameAui.__init__(self,parent) 
```

**Comment by tester0077** [comment]
Just commenting the super line fixes the issue, if all I do is invoke the app & exit
The second line stays in either case.
I had included the super() trying to fix an issue with some functions set in the base code not being called. Partly as a workaround for the super() call not being part of the base class.
For all of that, I am very much a newb and have no idea whether that call is needed or even useful :-(

If I actually run a backup, I may still have the issue - still investigating that part

**Comment by rokm** [comment]
> Just commenting the super line fixes the issue, if all I do is invoke the app & exit The second line stays in either case. I had included the super() trying to fix an issue with some functions set in the base code not being called. Partly as a workaround for the super() call not being part of the base class. For all of that, I am very much a newb and have no idea whether that call is needed or even useful :-(
> 
> If I actually run a backup, I may still have the issue - still investigating that part

If you do 
```python
def __init__(self,parent):
        super().__init__(None)
        wpBgBase.MyFrameAui.__init__(self,parent) 
```
then you are calling parent constructor *twice*, and that leads to problems.

If you run your code via `python wpBG.py` from command prompt (`cmd`), you will see that if you close your application's window, the python process will not exit either, and there will be a dangling python.exe listed among processes in Task manager.

So the issue you are describing here is stemming from incorrect use of wxPython API, and has nothing to do with PyInstaller (except that you get danging wpBG.exe instead of dangling python.exe).

---

So that constructor should in fact be:
```python
def __init__(self, parent):
        super().__init__(parent) # This is equivalent to:  wpBgBase.MyFrameAui.__init__(self,parent) 
```

**Comment by tester0077** [comment]
Using your code did clean up the issue for me, even if I actually execute the app's code and do a backup
Thank you very much

**Comment by tester0077** [comment]
Only one remaining issue:
What to I need to do to be able to make a desktop icon which runs the app and can find the icons used for the tool bar?
As it is, I can run the app from inside the PS shell, after creating the dist exe and it displays the tool bar graphics, but, if I 'send that exe to the desktop under Win 11, it executes, but is not able to find the icons, which makes the app more or less unusable.

**Comment by bwoodsend** [comment]
It's not clear to me what you're asking but if you're wondering why the icons in your `rc/` directory don't show up then it's because you're referencing their locations with relative paths which is also invalid Python. See [docs](https://pyinstaller.org/en/stable/runtime-information.html?highlight=__file__#using-file).

**Comment by tester0077** [comment]
Thank you. Fortunately, my GUI builder makes it very easy to use absolute paths and the EXE now shows the appropriate graphics.
I was not aware that using relative paths was invalid Python, because using them has worked for me  all along. Possibly this issue is hidden or overcome by wxPython.
I had read the PyInstaller docs about this but they did not seem to help me decipher this issue :-(

**Comment by rokm** [comment]
>  I was not aware that using relative paths was invalid Python, because using them has worked for me all along. Possibly this issue is hidden or overcome by wxPython.

It works only as long as your current working directory contains those files (i.e., if you run your code from directory that contains it). If you move to another directory and run your code from there, those relative paths won't work, either.

**Comment by tester0077** [comment]
Typically, my projects by default & intentionally include all of those files, which may well be why I have not run into any issues.
But it is good to be aware of this. Thank you.

**Comment by tester0077** [comment]
OK, I now have tried to move the exe created with absolute paths, to a different machine and I get the same issue with missing or icons not found.
Since this bundling of the project was the main idea behind building an OS agnostic python based utility, I find myself very disappointed.
Searching the 'net for ways to get what I wanted & would still need, seems to imply that it is possible, but not very straight forward

**Comment by rokm** [comment]
If you are collecting those icons into frozen application bundle and are referencing them via absolute paths anchored to `__file__` as described in docs that Brénainn linked earlier, it should work. 

We, however, have no way of guessing what exactly you are doing and what not. So what does your modified code look like, and what does your PyInstaller command (or .spec file) look like?

**Comment by tester0077** [comment]
Obviously my basic assumptions need adjusting.
I had thought that I would be able to use as project 'as is' and then convert it to a PyInstaller exe for Windows and another executable for Linux. With a definite intention for sharing these apps.
By now I realize (I think) that my projects will/would need to be build from the ground up with the necessary 'plumbing' to  eventually be usable for the base for bundling with PyInstaller (& likely any other equivalent approach).
My original motivation was to be able to move (gradually) away from Windows & C++ to Linux.
By now I have come to understand that learning enough about all of the 'gotchas' related and implicit in this process (from Python and ... differences in "Linux' OSes) exceeds, by a good margin, the effort I would have to expend to use a hybrid approach. I expect that I will shelve and mothball the 'OS agnostic' approach for now and worry about getting my own jobs done.
Thank you all for your help in getting me this far.
There is a chance I might come back to something along these lines, but for now, I need to get on with things, right now, right here.
