### ISSUE TITLE
[Feature Request] Allow Users to Choose Location for Python Runtime Files: End of File (EOF) or Resources

### ISSUE THREAD

**Issue by Blank-c** [pyinstaller/pyinstaller#8101]
[For Windows]

At present, PyInstaller appends Python Runtime Files to the end of the generated executable when using the onefile option. I suggest introducing the ability for users to choose the placement of these runtime files, giving the option to either position them at the end of the file (EOF) or within the Resources, which can later be retrieved by the bootloader by utilising Windows API functions like `FindResource` and `LoadResource` for obtaining the runtime files as needed.

**Comment by rokm** [comment]
What would be the benefit of having PKG embedded in resources instead of appended at the end of executable?

**Comment by Blank-c** [comment]
1) It's not easy to accidentally remove the PKG with the strip tool.
2) The packed executable stays fine because packers won't mess it up without adding the PKG overlay.
3) You can get into the archive using simple WinAPI functions instead of needing PyInstaller's Archive Reader.

**Comment by rokm** [comment]
> 3. You can get into the archive using simple WinAPI functions instead of needing PyInstaller's Archive Reader.

Wait, are you asking for the whole PKG archive to be embedded as a single resource (instead of being appended to the executable), or not having PKG at all and instead putting its contents into separate resource entries?

Also, do you know if win32 resources API impose any limits on the size?

**Comment by Blank-c** [comment]
> Wait, are you asking for the whole PKG archive to be embedded as a single resource (instead of being appended to the executable), or not having PKG at all and instead putting its contents into separate resource entries?

Yes, I meant to put the whole PKG file as an embedded resource.

> Also, do you know if win32 resources API impose any limits on the size?

[[Source](https://stackoverflow.com/questions/67407062/visual-studio-embed-large-resource-file-almost-4gb/67409823#67409823)] It looks like the resource size doesn't matter as long as the final size of the executable is under 4GB.

**Comment by rokm** [comment]
Hmm, the source you provided also seems to suggest that the limit would be 2GB due to constraints on image size (and due to image being memory-mapped at run-time).

**Comment by rokm** [comment]
> Yes, I meant to put the whole PKG file as an embedded resource.

Then PyInstaller's Archive Reader is in no way redundant, as you still need to handle archive structure (you wouldn't need to scan for the MAGIC pattern, though). And we need it on other OSes anyway, so even if we got rid of it on Windows, it wouldn't really benefit us in any way in the grand scheme of things.

**Comment by Blank-c** [comment]
It could be 2GB (someone said in comment) or 4GB (someone else said in the answer).

**Comment by Blank-c** [comment]
> Then PyInstaller's Archive Reader is in no way redundant, as you still need to handle archive structure (you wouldn't need to scan for the MAGIC pattern, though). And we need it on other OSes anyway, so even if we got rid of it on Windows, it wouldn't really benefit us in any way in the grand scheme of things.

I didn't say that it should be removed. I think its  a good idea to allow the user to place the PKG in the resources instead of EOF.

**Comment by rokm** [comment]
> > Then PyInstaller's Archive Reader is in no way redundant, as you still need to handle archive structure (you wouldn't need to scan for the MAGIC pattern, though). And we need it on other OSes anyway, so even if we got rid of it on Windows, it wouldn't really benefit us in any way in the grand scheme of things.
> 
> I didn't say that it should be removed. I think its a good idea to allow the user to place the PKG in the resources instead of EOF.

On the other hand, I'm vehemently opposed to having *another* option, with different codepath and potentially different behavior and bugs. 

If we were to go the resources way, it would have to replace the EOF approach completely. 

And even that would mean that we will have different embedded resource extraction codepath for Windows vs other OSes, due to EOF codepath being based on file access (seeking to offset indicated by the TOC) while the resource-based one would presumably have to be based on in-memory access.

**Comment by bwoodsend** [comment]
You seem to be missing the fact that the embedded PKG is a custom format so, even if you could extract the PKG from the EXE using a more standard Windows tool, you'd still need PyInstaller's Archive Reader to do anything with the archive. If needing PyInstaller's Archive Reader is inevitable, what's the point in this change?

**Comment by Blank-c** [comment]
You have a point.
