### ISSUE TITLE
Error on Linux Chrome OS Flex

### ISSUE THREAD

**Issue by paulocoutinhox** [pyinstaller/pyinstaller#8107]
Hi,

When i try to use Linux release package on Linux Chrome OS Flex i get this error:

``` 
[357] Error loading Python lib '/home/paulo/dist/My App/_internal/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /home/paulo/dist/My App/_internal/libpython3.9.so.1.0)
``` 

The build process is here:
https://github.com/paulocoutinhox/pyside6-demo/blob/main/.github/workflows/linux.yml

And the spec is here:
https://github.com/paulocoutinhox/pyside6-demo/blob/main/My%20App.spec

Can anyone help me?

Ref: https://github.com/paulocoutinhox/pyside6-demo/issues/1

**Comment by bwoodsend** [comment]
Presumably Linux Chrome OS has an older version of glibc than the latest Ubuntu. You need to build on something older than your intended runtime environment – either by changing `ubuntu-latest` to an older version or by sticking the whole build process in an old Debian/CentOS Docker container.
