### ISSUE TITLE
import of qtcore and python-usb not working in 2.1 (Ubuntu)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#811]
**Original date**: 2013/10/30
**Original reporter**: *geenzo AND gmail DOT  COOM *

Up to version 1.5.1 everything was working just fine.
In the new 2.1 the output binary (created with -F option) alway returns errors when launched:
Traceback (most recent call last):
  File "<string>", line 19, in <module>
ImportError: No module named backend.libusb1
(the same happens with importing qtcore)

On the very same system, using pyinstaller 1.5.1 it works perfectly.

**Comment by matysek** [comment]
Does not contain much information for reproducing this issue and also  there are other reports related to pysub that are being worked on.
