### ISSUE TITLE
AttributeError: module 'PyInstaller.depend.bindepend' has no attribute 'selectImports'

### ISSUE THREAD

**Issue by Frany-oss** [pyinstaller/pyinstaller#8110]
I'm trying to create an executable for a Python (3.10) application that uses Kivy and yoloV7. The command im using to create the executable is: `pyinstaller --onefile --noconsole start.py`, I also tried with `pyinstaller --onefile --noconsole --hidden-import selectImports start.py`. The logs i get are:

> ⟩ pyinstaller --onefile --noconsole --hidden-import selectImports start.py
> 
> 143 INFO: PyInstaller: 6.2.0
> 143 INFO: Python: 3.10.12
> 145 INFO: Platform: Linux-5.15.0-83-generic-x86_64-with-glibc2.35
> 146 INFO: wrote /home/frany/Documents/TP/autoposture/Autoposture/start.spec
> 148 INFO: Extending PYTHONPATH with paths
> 2926 WARNING: stderr: Traceback (most recent call last):
>  Traceback (most recent call last):
> 2926 WARNING: stderr:   File "/home/frany/.local/bin/pyinstaller", line 8, in <module>
>    File "/home/frany/.local/bin/pyinstaller", line 8, in <module>
> 2926 WARNING: stderr:     sys.exit(_console_script_run())
>      sys.exit(_console_script_run())
> 2926 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 214, in _console_script_run
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 214, in _console_script_run
> 2927 WARNING: stderr:     run()
>      run()
> 2927 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 198, in run
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 198, in run
> 2927 WARNING: stderr:     run_build(pyi_config, spec_file, **vars(args))
>      run_build(pyi_config, spec_file, **vars(args))
> 2927 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 69, in run_build
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/__main__.py", line 69, in run_build
> 2927 WARNING: stderr:     PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
>      PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
> 2927 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1069, in main
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1069, in main
> 2928 WARNING: stderr:     build(specfile, distpath, workpath, clean_build)
>      build(specfile, distpath, workpath, clean_build)
> 2928 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1009, in build
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1009, in build
> 2928 WARNING: stderr:     exec(code, spec_namespace)
>      exec(code, spec_namespace)
> 2929 WARNING: stderr:   File "/home/frany/Documents/TP/autoposture/Autoposture/start.spec", line 4, in <module>
>    File "/home/frany/Documents/TP/autoposture/Autoposture/start.spec", line 4, in <module>
> 2929 WARNING: stderr:     a = Analysis(
>      a = Analysis(
> 2929 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 470, in __init__
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 470, in __init__
> 2929 WARNING: stderr:     self.__postinit__()
>      self.__postinit__()
> 2929 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
> 2930 WARNING: stderr:     self.assemble()
>      self.assemble()
> 2930 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 608, in assemble
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 608, in assemble
> 2930 WARNING: stderr:     priority_scripts.append(self.graph.add_script(script))
>      priority_scripts.append(self.graph.add_script(script))
> 2930 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 268, in add_script
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 268, in add_script
> 2930 WARNING: stderr:     self._top_script_node = super().add_script(pathname)
>      self._top_script_node = super().add_script(pathname)
> 2931 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1260, in add_script
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1260, in add_script
> 2931 WARNING: stderr:     self._process_imports(n)
>      self._process_imports(n)
> 2931 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2703, in _process_imports
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2703, in _process_imports
> 2932 WARNING: stderr:     target_modules = self._safe_import_hook(*import_info, **kwargs)
>      target_modules = self._safe_import_hook(*import_info, **kwargs)
> 2932 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 437, in _safe_import_hook
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 437, in _safe_import_hook
> 2932 WARNING: stderr:     return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
>      return super()._safe_import_hook(target_module_partname, source_module, target_attr_names, level, edge_attr)
> 2932 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2160, in _safe_import_hook
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2160, in _safe_import_hook
> 2933 WARNING: stderr:     target_modules = self.import_hook(
>      target_modules = self.import_hook(
> 2933 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1332, in import_hook
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1332, in import_hook
> 2933 WARNING: stderr:     target_package, target_module_partname = self._find_head_package(
>      target_package, target_module_partname = self._find_head_package(
> 2934 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1511, in _find_head_package
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1511, in _find_head_package
> 2934 WARNING: stderr:     target_package = self._safe_import_module(
>      target_package = self._safe_import_module(
> 2934 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 484, in _safe_import_module
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 484, in _safe_import_module
> 2934 WARNING: stderr:     return super()._safe_import_module(module_basename, module_name, parent_package)
>      return super()._safe_import_module(module_basename, module_name, parent_package)
> 2935 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1892, in _safe_import_module
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 1892, in _safe_import_module
> 2935 WARNING: stderr:     self._process_imports(n)
>      self._process_imports(n)
> 2935 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2703, in _process_imports
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/lib/modulegraph/modulegraph.py", line 2703, in _process_imports
> 2936 WARNING: stderr:     target_modules = self._safe_import_hook(*import_info, **kwargs)
>      target_modules = self._safe_import_hook(*import_info, **kwargs)
> 2936 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 368, in _safe_import_hook
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 368, in _safe_import_hook
> 2936 WARNING: stderr:     excluded_imports = self._find_all_excluded_imports(source_module.identifier)
>      excluded_imports = self._find_all_excluded_imports(source_module.identifier)
> 2936 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 356, in _find_all_excluded_imports
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/analysis.py", line 356, in _find_all_excluded_imports
> 2936 WARNING: stderr:     excluded_imports.update(module_hook.excludedimports)
>      excluded_imports.update(module_hook.excludedimports)
> 2936 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 316, in __getattr__
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 316, in __getattr__
> 2936 WARNING: stderr:     self._load_hook_module()
>      self._load_hook_module()
> 2937 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 383, in _load_hook_module
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/depend/imphook.py", line 383, in _load_hook_module
> 2937 WARNING: stderr:     self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
>      self._hook_module = importlib_load_source(self.hook_module_name, self.hook_filename)
> 2937 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/compat.py", line 629, in importlib_load_source
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/compat.py", line 629, in importlib_load_source
> 2937 WARNING: stderr:     mod_loader.exec_module(mod)
>      mod_loader.exec_module(mod)
> 2937 WARNING: stderr:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
>    File "<frozen importlib._bootstrap_external>", line 883, in exec_module
> 2937 WARNING: stderr:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
>    File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
> 2938 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/hooks/hook-kivy.py", line 21, in <module>
>    File "/home/frany/.local/lib/python3.10/site-packages/PyInstaller/hooks/hook-kivy.py", line 21, in <module>
> 2938 WARNING: stderr:     hiddenimports = get_deps_all()['hiddenimports']
>      hiddenimports = get_deps_all()['hiddenimports']
> 2938 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 272, in get_deps_all
>    File "/home/frany/.local/lib/python3.10/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 272, in get_deps_all
> 2938 WARNING: stderr:     'binaries': _find_gst_binaries(),
>      'binaries': _find_gst_binaries(),
> 2938 WARNING: stderr:   File "/home/frany/.local/lib/python3.10/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 370, in _find_gst_binaries
>    File "/home/frany/.local/lib/python3.10/site-packages/kivy/tools/packaging/pyinstaller_hooks/__init__.py", line 370, in _find_gst_binaries
> 2938 WARNING: stderr:     plugin_deps = bindepend.selectImports(plugin_filepath)
>      plugin_deps = bindepend.selectImports(plugin_filepath)
> 2938 WARNING: stderr: AttributeError: module 'PyInstaller.depend.bindepend' has no attribute 'selectImports'
>  AttributeError: module 'PyInstaller.depend.bindepend' has no attribute 'selectImports'

I dont even have a selectImports in my code or anything like that

I can't find the answer anywhare. Here is the github: [https://github.com/Cesarmosqueira/Autoposture](https://github.com/Cesarmosqueira/Autoposture).

Please feel free to ask any questions. Thanks

**Comment by bwoodsend** [comment]
See https://github.com/orgs/pyinstaller/discussions/8057

**Comment by rokm** [comment]
Open bug report with `kivy`; they are providing the failing hook, which is using an internal PyInstaller function that is gone in PyInstaller v6.
