### ISSUE TITLE
When running PyInstaller from Python code, buildpath and distpath options are ignored

### ISSUE THREAD

**Issue by dariopnc** [pyinstaller/pyinstaller#8114]
## When running PyInstaller from Python code, buildpath and distpath options are ignored
In the doc it says, literally:

> If you want to run PyInstaller from Python code, you can use the run function defined in PyInstaller.__main__. For instance, the following code:
>```python
>import PyInstaller.__main__
>
>PyInstaller.__main__.run([
>    'my_script.py',
>    '--onefile',
>    '--windowed'
>])
>```
>Is equivalent to:
>
>`pyinstaller my_script.py --onefile --windowed`

It does not mention any exclusion and it hints at the fact that any option can be used, especially the most used ones like `--distpath` and `--workpath`.

When you run the following example, the second and third arguments are ignored, in favor of `DEFAULT_WORKPATH` and `DEFAULT_DISTPATH` respectively.

```python
PyInstaller.__main__.run([
   'my_script.py',
   '--workpath "%s"' % workpath,
   '--distpath "%s"' % distpath
])
```

I guess the issue lies in `PyInstaller.building.build_main.main` and the fact that the default values for attributes `distpath` and `workpath` are not updated, parsing the `**kw` attribute contents

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.1.0```
* Version of Python: 3.11.6
* Platform: Windows 10 22H2 (build SO 19045.3570) (language it_IT)
* How you installed Python: venv
* Did you also try this on another platform? Does it work there? No, haven't tried

### A minimal example program which shows the error

1. Create file `helloworld.py` with:
   ```python
   print("Hello World!")
   ```
2. Run `pyinstaller helloworld.py` to generate file `helloworld.spec` (this step is necessary to avoid falling in another issue)
3. Verify that `build` and `dist` subdirectories were created with the usual contents
4. Delete them
5. Run `pyinstaller helloworld.spec --buildpath alt_build --distpath alt_dist`
6. Verify that `alt_build` and `alt_dist` subdirectories were created with the usual contents, instead of the previous two
7. Delete them
8. Create file `pyinstaller_code.py` with:
   ```python
   import PyInstaller.__main__
   
   PyInstaller.__main__.run([
       'helloworld.spec',
       '--workpath "alt_build"',
       '--distpath "alt_dist"'
   ])
   ```
9. Run it with `python pyinstaller_code.py`
10. Expected result would be a situation similar to `6.`, obtained a situation similar to `3.`
11. Delete `build` and `dist` subdirectories, `helloworld.py`, `helloworld.spec` and `pyinstaller_code.py` files

### Stacktrace / full error message
No error message, the build is fine, only in the wrong path

**Comment by rokm** [comment]
When you pass a command-line option like `--buildpath alt_build` on the CLI, this results in `sys.argv` having `['--buildpath', 'alt_build']`, and not `['--buildpath alt_build']`.

So your example should be:

```python
import PyInstaller.__main__

PyInstaller.__main__.run([
    'helloworld.spec',
    '--workpath', 'alt_build',
    '--distpath', 'alt_dist'
])
```
