### ISSUE TITLE
Code signing on macOS fails on PyQt6 with "bundle format unrecognized" after upgrade from v5.13 to v6.2

### ISSUE THREAD

**Issue by ErikBjare** [pyinstaller/pyinstaller#8120]
## Description of the issue

Build fails while signing, ending with:

```
104417 INFO: Signing the BUNDLE...
115485 WARNING: Error while signing the bundle: codesign command (['codesign', '-s', '***', '--force', '--all-architectures', '--timestamp', '--options=runtime', '--entitlements', PosixPath('scripts/package/entitlements.plist'), '--deep', '/Users/runner/work/activitywatch/activitywatch/dist/ActivityWatch.app']) failed with error code 1!
output: /Users/runner/work/activitywatch/activitywatch/dist/ActivityWatch.app: replacing existing signature
/Users/runner/work/activitywatch/activitywatch/dist/ActivityWatch.app: bundle format unrecognized, invalid, or unsuitable
In subcomponent: /Users/runner/work/activitywatch/activitywatch/dist/ActivityWatch.app/Contents/Frameworks/PyQt6/Qt6/lib/QtPdf.framework

115486 WARNING: You will need to sign the bundle manually!
```

After upgrading PyInstaller from v5.13 to v6.2.

Perhaps the hooks need to be updated? Not sure why it suddenly has an issue with that file in `v6.2.0`.

 - PR: https://github.com/ActivityWatch/activitywatch/pull/976
 - CI run: https://github.com/ActivityWatch/activitywatch/actions/runs/6959043476/job/18935405327?pr=976

### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.2.0
* Version of Python: 3.9
* Platform: macOS

I have skipped the extra steps in the issue template, which I found to not be relevant to this issue since the error clearly points out PyQt6 as the culprit, and I have a small PR with failing CI run that previously worked in v5.13.

I will not provide a minimal example program, due to a lack of time (and questionable value of the exercise in this case).

**Comment by rokm** [comment]
Starting with 6.x, we are trying to preserve the Qt .framework bundles structure, and somewhat in your build setup seems to be running afoul of that.

FWIW, trying to freeze a simple `import PyQt6.QtPdf` program seems to correctly collect `example.app/Contents/Frameworks/PyQt6/Qt6/lib/QtPdf.framework`, so I don't think this is a problem with PyQt6 per-se.

Can you try removing `MERGE` from the .spec file? You are generating onedir builds on all OSes, so `MERGE` makes no sense in that context - if you wanted a package with multiple executables and shared binaries/datas, you should create a single COLLECT with all EXEs, and all `datas` and `binaries` from all `Analysis` objects. 

But the way you are passing all the COLLECTs to BUNDLE, their TOCs should be merged and de-duplicated before collection without any explicit merging.

Also, could you enable `--log-level DEBUG` on the CI, so we can see detailed build log?

I'll try to recreate your build process locally/off-line and see if I can find something useful...

**Comment by rokm** [comment]
Also, can you try ensuring that PyQt6 and PyQt6-Qt6 are in sync? From [the build log](https://github.com/ActivityWatch/activitywatch/actions/runs/6959043476/job/18935405327?pr=976#step:13:1218):

> ```
> PyQt6==6.3.1
> PyQt6-Qt6==6.5.3
> PyQt6-sip==13.6.0
> PyQt6-stubs @ git+https://github.com/TilmanK/PyQt6-stubs@86d119ed202c1f9f86923563c2754cf93c1ec303
> ```

**Comment by ErikBjare** [comment]
>Can you try removing MERGE from the .spec file? You are generating onedir builds on all OSes, so MERGE makes no sense in that context - if you wanted a package with multiple executables and shared binaries/datas, you should create a single COLLECT with all EXEs, and all datas and binaries from all Analysis objects.

We are using this particular `aw.spec` only for macOS. 

We build differently for Windows/Linux, with one `.spec` file per module ([example](https://github.com/ActivityWatch/aw-qt/blob/master/aw-qt.spec)), the result of which we then structure as `activitywatch/<module>/` in our final build ([like this](https://github.com/ActivityWatch/activitywatch/blob/2a94a5707cc39c4ddfa31ab5a4d501266b860378/Makefile#L160-L182)).

I've commented out the MERGE in a new commit, as you suggested.

>But the way you are passing all the COLLECTs to BUNDLE, their TOCs should be merged and de-duplicated before collection without any explicit merging.

Not sure what the implication is here.

>could you enable --log-level DEBUG on the CI

Done!

>can you try ensuring that PyQt6 and PyQt6-Qt6 are in sync?

Done! Good catch.

**Comment by rokm** [comment]
Taking out the `MERGE` should fix the issue, I think - with v5, your use of `MERGE` was essentially a no-op, but due to a bug in symlinks bookkeeping during `MERGE`, it now removes the symlinks from the collected Qt .framework bundles (hence invalid bundle structure). I'll fix that part, even though it should not be applicable to you anymore.

---

One more thing, though. With v6, we now use symlinks within the frozen application bundle, and I see that you are generating .zip files from POSIX builds (macOS and/or Linux). You should add `--symlinks` to your `zip` call [here](https://github.com/ActivityWatch/activitywatch/blob/2a94a5707cc39c4ddfa31ab5a4d501266b860378/scripts/package/package-all.sh#L55). Otherwise, your build will end up with several duplicates of the files, which will baloon the size and might also cause issues at run-time.

**Comment by rokm** [comment]
> One more thing, though. With v6, we now use symlinks within the frozen application bundle, and I see that you are generating .zip files from POSIX builds (macOS and/or Linux). You should add `--symlinks` to your `zip` call [here](https://github.com/ActivityWatch/activitywatch/blob/2a94a5707cc39c4ddfa31ab5a4d501266b860378/scripts/package/package-all.sh#L55). Otherwise, your build will end up with several duplicates of the files, which will baloon the size and might also cause issues at run-time.

Hmm, actually, it looks like you also need to use `cp -R` instead of `cp -r` on macOS for symlinks to be preserved during the copying that you do [here](https://github.com/ActivityWatch/activitywatch/blob/2a94a5707cc39c4ddfa31ab5a4d501266b860378/Makefile#L165).

**Comment by ErikBjare** [comment]
Thank you so much for the help @rokm! 👑 

And thanks for the heads-up about symlinks.
