### ISSUE TITLE
[25112] Failed to execute script 'my program' due to unhandled exception!

### ISSUE THREAD

**Issue by DohyeonKn** [pyinstaller/pyinstaller#8131]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.2.0```
* Version of Python: 3.10.9
* Platform:  Windows 
* How you installed Python: conda,jupyter
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
import pandas as pd

from glob import glob

import os

lines2skip=0
def header_info(fname): #파일 컬럼 가져오기
    skiprows=0
    cols=[]
    for line in open(fname,encoding='latin-1'):
        skiprows+=1

        if '# name' in line:
            col=line.split(' = ')[1]

            col=col.strip()
            cols.append(col)
        if '*END*' in line:
            lines2skip=skiprows
    return cols, lines2skip
def t_df(fname): #파일 열어 데이터프레임화
    cols,lines2skip = header_info(fname)

    df=pd.read_csv(fname,delimiter='\s+',names=cols,encoding='cp1252',skiprows=lines2skip)



    return df

desktop_path = os.path.join(os.path.expanduser('~'), 'Desktop')
desktop_path = os.path.abspath(desktop_path)

folder_name = 'CTDdata'


folder_path = os.path.join(desktop_path, folder_name)

print(f'{folder_path}')

if not os.path.exists(folder_path):
    os.mkdir(folder_path)
    
input('생성된 바탕화면의 CTDdata폴더에 파일을 넣어주세요 \n 이후 아무 키나 입력해주세요')
fns=glob(f'{folder_path}\\*.cnv')
for fn in fns:
    df=t_df(fn)
    fname=fn.split('.')[0]
    df.to_excel(f'{fname}.xlsx',index=False)
input('끝났습니다')
print('Done')

It was verified that the script file runs well on Jupiter, and later.I converted the py file into an exe file using pyinstaller, but the following code appears when I run it, and it cannot be executed

[25112] Failed to execute script 'my program' due to unhandled exception!

converted py to exe code ,pyinstaller --onefile ctdtrans.py
and also try to pyinstaller --hidden-import=openpyxl --onefile ctdtrans.py  

please helpme
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> It was verified that the script file runs well on Jupiter, and later.I converted the py file into an exe file using pyinstaller, but the following code appears when I run it, and it cannot be executed

Does it work with the python interpreter in the python environment in which you have PyInstaller installed, though?

> [25112] Failed to execute script 'my program' due to unhandled exception!

What is the actual error traceback that precedes this message?

---

I've tried to freeze and run your script with a test file, and it seems to work fine. So you probably have PyInstaller installed in a different python environment than `pandas` and `openpyxl`.
