### ISSUE TITLE
A RecursionError while importing Tensorflow

### ISSUE THREAD

**Issue by TimofeiKargin** [pyinstaller/pyinstaller#8133]
My versions:
```
OS: Ubuntu 22.04 jammy
Kernel: x86_64 Linux 6.2.0-37-generic
Python: 3.10.12
tensorflow: 2.15.0
pyinstaller: 6.2.0
pyinstaller-hooks-contrib: 2023.10
```

Here is my **main.py**:
```
import tensorflow as tf
import sys
sys.setrecursionlimit(sys.getrecursionlimit() * 5)
```
How I try to create .exe file to by runned on Windows:
`pyinstaller --clean --onefile --windowed main.py`

What I get:
```
=============================================================
A RecursionError (maximum recursion depth exceeded) occurred.
For working around please follow these instructions
=============================================================

1. In your program's .spec file add this line near the top::

     import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)

2. Build your program by running PyInstaller with the .spec file as
   argument::

     pyinstaller myprog.spec

3. If this fails, you most probably hit an endless recursion in
   PyInstaller. Please try to track this down has far as possible,
   create a minimal example so we can reproduce and open an issue at
   https://github.com/pyinstaller/pyinstaller/issues following the
   instructions in the issue template. Many thanks.

Explanation: Python's stack-limit is a safety-belt against endless recursion,
eating up memory. PyInstaller imports modules recursively. If the structure
how modules are imported within your program is awkward, this leads to the
nesting being too deep and hitting Python's stack-limit.

With the default recursion limit (1000), the recursion error occurs at about
115 nested imported, with limit 2000 at about 240, with limit 5000 at about
660.
```
I suppose, there is a possible working workaround using Pyinstaller's settings, but reading the documentation wasn't successful.
Does anyone has any ideas to check?

**Comment by rokm** [comment]
> ```sys.setrecursionlimit(sys.getrecursionlimit() * 5)```

You're supposed to put that at the start of your spec file (so it affects the process in which PyInstaller's analysis is running), not in your `main.py`. And then build using the .spec file (`pyinstaller --clean main.spec`).

FWIW, I cannot trigger the recursion error in jammy container, with system-provided python 3.10.12 and clean virtual environment with tensorflow 2.15.0 installed. Are you using a virtual environment, or base python environment (with all the system-provided packages installed as well)? Try with a clean virtual environment and install just tensorflow and PyInstaller in it, to see if it makes any difference.

> How I try to create .exe file to by runned on Windows:

If you build on Linux, you will get a Linux binary, not a Windows .exe...

**Comment by TimofeiKargin** [comment]
> Are you using a virtual environment, or base python environment (with all the system-provided packages installed as well)?

I use base. Yeah, now it all makes sense.
Anyway, now I will create Windows virtual machine and build on windows to get windows .exe.
Thanks!
