### ISSUE TITLE
PyInstaller --strip error at mac os

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#814]
**Original date**: 2013/11/04
**Original reporter**: *ainiyishen7590 AND 163 DOT  COOM *

Hi，
 I  Found a bug when I use --strip option
When I use ‘sudo python PyInstaller a.py' there is no problem but the app is kind of fat
When I use 'sudo python PyInstaller --strip a.py' the PyInstaller Error，It's
```
8023 INFO: building EXE from out00-EXE.toc
8079 INFO:Executing - strip -S /Users/myname/Library/Application Support/pyinstaller/bincache10_py27/run
Execution failed: [Errno 2] No such file or directory
```
OS Version:OS X 10.8.5
Python Version:2.7.5
PYInstaller Version:2.1

**Comment by htgoebel** [comment]
This feature-request if four years old now. Nobody worked on is and nobody commented on this issue, so I'm closing it.
