### ISSUE TITLE
COM object loader is out of order

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#815]
**Original date**: 2013/11/04
**Original reporter**: *hlcd DOT hlcd AND gmail DOT  COOM *

Python 2.7.2 32-bits Pyinstaller 2.1 Windows 7-64 MSVC++ Express 2008

Experiments:
---
Attempt to recompile bootloaders (..\windows\dllmain.c) and make it work. Fails.

Problems encountered:
---

DllCanUnloadNow?, DllGetClassObject?, DllRegisterServer?, DllUnregisterServer? are not exported in bootloader, because dllmain.def is not explicitely tied to the project during the link process (which is required with MSVC).

After modifying C:\Program Files\Microsoft SDKs\Windows\v6.0A\Include\ObjBase?.h and C:\Program Files\Microsoft SDKs\Windows\v6.0A\Include\OleCtl?.h, and dllmain.c,to be able to export the relevant symbols

-> symbols are now included.

But startUp function was buggy. I modified it (see attached files) to avoid regsvr32 crash.

After that, registration can start but fails. In my case, the output was (parts of the paths are hidden on purpose)

STARTGot PathsLOADER: archivename is F:\..\driveobject_com.dll Opened ArchiveLOADER: Python library: F:\..\python27.d ll LOADER: Manipulating evironment LOADER: PYTHONPATH=F:\..\pyinstaller\dist\..\ LOADER: PYTHONHOME=F:\..\ LOADER: Manipulating Python's sys.path

File "<string>", line 1

sys.path.append(r"F:\l.._com\")

SyntaxError?: EOL while scanning string literal Started new Pythonset sys.frozenLOADER: importing modules from CArchive LOADER: extracted struct LOADER: extracted pyi_os_path LOADER: extracted pyi_archive LOADER: extracted pyi_importers Imported ModulesLOADER: Installing import hooks LOADER: out00-PYZ.pyz Installed ZlibsLOADER: Running scripts Traceback (most recent call last):

File "<string>", line 15, in <module>

AttributeError?: 'module' object has no attribute '_MEIPASS' LOADER: RC: -1 from pyi_rth_Tkinter Loading PythoncomPythoncom? failed to load

Hope it will help you to fix COM server functionnality of pyinstaller.

Thanks in advance.

**Comment by matysek** [comment]
Closing as 'won't fix' since I haven't seen user demand to still support MakeComServer. This feature haven't been touched for several years and I don't have the necessary knowledge.
