### ISSUE TITLE
AIX - Error during execution on some systems

### ISSUE THREAD

**Issue by cdb9201** [pyinstaller/pyinstaller#8150]
Built a program on AIX and execution on same os version systems, some work, some fail.  Not able to determine where the problem is.  

Built on:
-pyinstaller -v
5.13.2
-oslevel -s
7300-01-02-2320
-pip3 list
Package                   Version
altgraph                  0.17.3
build                     1.0.3
certifi                   2023.7.22
charset-normalizer        2.1.1
click                     8.1.7
distro                    1.8.0
gpg                       1.13.1
idna                      3.4
importlib-metadata        5.0.0
numpy                     1.21.6
packaging                 23.2
pip                       23.3.1
pip-tools                 6.14.0
pycryptodomex             3.17
pyinstaller               5.13.2
pyinstaller-hooks-contrib 2023.8
pyproject_hooks           1.0.0
requests                  2.31.0
setuptools                47.1.0
tomli                     2.0.1
typing_extensions         4.4.0
urllib3                   2.0.4
wheel                     0.41.2
zipp                      3.15.0

Runtime error:
oslevel -s
7300-01-02-2320

[9372048] Error loading Python lib '/tmp/_MEILMBMea/libpython3.7m.so': dlopen: rtld: 0712-001 Symbol _GLOBAL__AIXI_libintl_so/tmp/_MEILMBMea/libpython3.7m.so was referenced
      from module /tmp/_MEILMBMea/libpython3.7m.so(), but a runtime definition
      of the symbol was not found.
rtld: 0712-001 Symbol _GLOBAL__AIXD_libintl_so/tmp/_MEILMBMea/libpython3.7m.so was referenced
      from module /tmp/_MEILMBMea/libpython3.7m.so(), but a runtime definition
      of the symbol was not found.

**Comment by rokm** [comment]
Sounds like the same problem as https://github.com/orgs/pyinstaller/discussions/7933. That said, AIX is a contributed platform to which we do not have access, so you're pretty much on your own.

**Comment by cdb9201** [comment]
Well thanks that helped point me in the right direction, found that the version of the libintl.a library was the culprit.  Once I installed dnf and got all its conflicts worked out my program runs with out error...  seems the libraries the dnf uses my program also uses.
