### ISSUE TITLE
After packaging with pyinstaller: pytorch '2.1.1+cu121' calls the wrong libcublasLt version (libcublasLt.so.11 instead of libcublasLt.so.12)

### ISSUE THREAD

**Issue by youssefoum** [pyinstaller/pyinstaller#8154]
## Description of the issue
I packaged (--onedir mode) a simple example of a pytorch '2.1.1+cu121' code. After running the executable I get this error:
```
Could not load library libcublasLt.so.11. Error: libcublasLt.so.11: cannot open shared object file: No such file or directory
```
If I create a symbolic link with the command `ln -s libcublasLt.so.12 libcublasLt.so.11` in the `_internal` folder the code works fine.
But, why would `libcublasLt.so.11` be called instead of `libcublasLt.so.12` ?
Same goes for `libcublas.so.11`.

### Context information (for bug reports)
* Output of `pyinstaller --version`: ```6.2.0```
* Version of Python: 3.10.13
* Platform:  Linux-5.4.0-150-generic-x86_64-with-glibc2.27
* How you installed Python: conda
* GPU: Quadro P6000
* Nvidia Driver Version: 530.30.02
* CUDA Version: 12.1

## A minimal example program which shows the error
```
import torch
import torch.nn as nn

m = nn.Conv2d(16, 33, 3, stride=2).cuda()
x = torch.rand(20, 16, 50, 100).cuda()
m(x)
```

**Comment by rokm** [comment]
I cannot reproduce this - if I set up clean conda environment with python 3.10.13, install torch 2.1.1+cu121 as per official instructions (`conda install pytorch torchvision torchaudio pytorch-cuda=12.1 -c pytorch -c nvidia`), and freeze your example, it works with collected `libcublas.so.12` and `libcublasLt.so.12` as expected.

Can you check the whole error message to determine what part was trying to load `libcublasLt.so.11` (e.g., was it linked from another shared library, or was it loaded from python code)? 

Does your conda environment's lib directory also contain both `libcublasLt.so.11` and `libcublasLt.so.12`?

**Comment by youssefoum** [comment]
You are right, after setting up a clean conda environment, there seems to be no problem. My conda environment has no libcublasLt.so.11 tho, only libcublasLt.so.12 exists.
