### ISSUE TITLE
The URL of "the v6.3.0 section of the changelog" is broken

### ISSUE THREAD

**Issue by keelung-yang** [pyinstaller/pyinstaller#8159]
Hi,
In release page, https://github.com/pyinstaller/pyinstaller/releases

the [v6.3.0 section of the changelog](https://pyinstaller.org/en/v6.3.0/CHANGES.html#id1) is broken.

![image](https://github.com/pyinstaller/pyinstaller/assets/20385450/8d26868d-b50d-4332-a6ee-48bc498d3324)

**Comment by bwoodsend** [comment]
Hmm, that's weird. readthedocs didn't trigger a build when the v6.3.0 tag was created...

**Comment by bwoodsend** [comment]
There we go, back to normal. Looks like the web hook token for GitHub notifying readthedocs of changes needed refreshing. Thanks for letting us know.
