### ISSUE TITLE
crash on macos seems can not find the python execute path

### ISSUE THREAD

**Issue by ILG2021** [pyinstaller/pyinstaller#8160]
After launching the app packaged by pyinsteller on a test machine (not the develop machine), it crashed and report “Python.framework” is damaged and can’t be opened. You should move it to the Trash. I don't know why.

**Comment by bwoodsend** [comment]
Most likely, you're not copying it in a way that preserves its symlinks.

**Comment by ILG2021** [comment]
I don't think so. It is a console and one dir app. I zip it and upload to dropbox. When i test it on another mac, it crashed, and I download it on the host mac, it can run regularly. The symlinks works ok. The console gives some errors like block by system policy.

**Comment by rokm** [comment]
> The console gives some errors like block by system policy.

There's your answer, then.

**Comment by rokm** [comment]
If you are 100% that symlinks are not the problem (you created your zip with `--symlinks` option), then either the other Mac is configured to not run untrusted (= unsigned) code, or perhaps the OS marked the files with `com.apple.quarantine` (which you can remove with `xattr -d com.apple.quarantine <filename>` ).

**Comment by ILG2021** [comment]
`[3307] Error loading Python lib '/Users/mac/Downloads/my-app/_internal/Python': dlopen: dlopen(/Users/mac/Downloads/my-app/_internal/Python, 0x000A): tried: '/Users/mac/Downloads/my-app/_internal/Python' (code signature in <0135FF15-F94D-3BAB-8237-0DC61059F33E> '/Users/mac/Downloads/my-app/_internal/Python.framework/Versions/3.11/Python' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/mac/Downloads/my-app/_internal/Python' (no such file), '/Users/mac/Downloads/my-app/_internal/Python' (code signature in <0135FF15-F94D-3BAB-8237-0DC61059F33E> '/Users/mac/Downloads/my-app/_internal/Python.framework/Versions/3.11/Python' not valid for use in process: library load disallowed by system policy), '/Users/mac/Downloads/my-app/_internal/Python.framework/Versions/3.11/Python' (code signature in <0135FF15-F94D-3BAB-8237-0DC61059F33E> '/Users/mac/Downloads/my-app/_internal/Python.framework/Versions/3.11/Python' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/mac/Downloads/my-app/_internal/Python.framework/Versions/3.11/Python' (no such file), '/Users/mac/Downloads/my-app/_internal/Python.framework/Versions/3.11/Python' (code signature in <0135FF15-F94D-3BAB-8237-0DC61059F33E> '/Users/mac/Downloads/my-app/_internal/Python.framework/Versions/3.11/Python' not valid for use in process: library load disallowed by system policy), '/Library/Frameworks/Python.framework/Versions/3.11/Python' (no such file), '/System/Library/Frameworks/Python.framework/Versions/3.11/Python' (no such file, not in dyld cache)`

This is the errors. Can you give any suggestion?

**Comment by rokm** [comment]
What is the output of `ls -l /Users/mac/Downloads/my-app/_internal`?

And the output of `xattr -l /Users/mac/Downloads/my-app/_internal/Python`?

**Comment by rokm** [comment]
As well as: `codesign -vv /Users/mac/Downloads/my-app/_internal/Python`?

**Comment by ILG2021** [comment]
> As well as: `codesign -vv /Users/mac/Downloads/my-app/_internal/Python`?

Thanks for your help, after replace every symlink by the real file, the Python.framework crash has been fixed. I think it is a bug of pyinstaller. And then the system begin to block every so file in lib-dynload. And I solve it by:

sudo spctl –master-disable
./my-app/my-app
sudo spctl –master-enable

This problem cost me a few days. Thank God, it is fixed.

**Comment by rokm** [comment]
Does it work if instead of replacing the symlinks, you manually ad-hoc sign the `Python.framework` bundle? I.e., run `codesign -s - --deep --force /Users/mac/Downloads/my-app/_internal/Python.framework`?

**Comment by ILG2021** [comment]
> Does it work if instead of replacing the symlinks, you manually ad-hoc sign the `Python.framework` bundle? I.e., run `codesign -s - --deep --force /Users/mac/Downloads/my-app/_internal/Python.framework`?

I will try later, thank you very much.

**Comment by rokm** [comment]
I'm reopening this, as it is likely a regression from PyInstaller 5.x series.

In v6, we preserve .framework bundle layouts (to address several other issues), but during the build, we sign only the collected binaries instead of the whole .framework bundles (i.e., together with the bundle's resources). When we are generating .app bundles, this is masked by the fact that we recursively sign the whole .app bundle at the end, so those .framework bundles are (re)signed as well. But in regular POSIX builds, the collected/reconstructed .framework bundles in fact do not have proper signature. This affects both onedir and onefile builds (although in the former case, the user could fix this by manually re-signing all the .framework bundles), but the actual effect likely depends on the security policy on the target Mac.

We need to rework the bincache system with special handling for collected .framework bundles (and top-level embedded .app bundles as well - see https://github.com/pyinstaller/pyinstaller/issues/7969): all contents of the .framework to be collected needs to be copied to the cache, signed as a single entity, and collected from bincache (along with the `_CodeSignature/CodeResources` that is generated during the signing).

**Comment by ILG2021** [comment]
> I'm reopening this, as it is likely a regression from PyInstaller 5.x series.
> 
> In v6, we preserve .framework bundle layouts (to address several other issues), but during the build, we sign only the collected binaries instead of the whole .framework bundles (i.e., together with the bundle's resources). When we are generating .app bundles, this is masked by the fact that we recursively sign the whole .app bundle at the end, so those .framework bundles are (re)signed as well. But in regular POSIX builds, the collected/reconstructed .framework bundles in fact do not have proper signature. This affects both onedir and onefile builds (although in the former case, the user could fix this by manually re-signing all the .framework bundles), but the actual effect likely depends on the security policy on the target Mac.
> 
> We need to rework the bincache system with special handling for collected .framework bundles (and top-level embedded .app bundles as well - see #7969): all contents of the .framework to be collected needs to be copied to the cache, signed as a single entity, and collected from bincache (along with the `_CodeSignature/CodeResources` that is generated during the signing).

Very nice. So how about another problem, the system continue requesting permission for loading the dynamic libs in the lib-dynload. And I find that even execute sudo spctl –master-disable, m1 computer still need permission. It is very frustrating.

**Comment by rokm** [comment]
> > I'm reopening this, as it is likely a regression from PyInstaller 5.x series.
> > In v6, we preserve .framework bundle layouts (to address several other issues), but during the build, we sign only the collected binaries instead of the whole .framework bundles (i.e., together with the bundle's resources). When we are generating .app bundles, this is masked by the fact that we recursively sign the whole .app bundle at the end, so those .framework bundles are (re)signed as well. But in regular POSIX builds, the collected/reconstructed .framework bundles in fact do not have proper signature. This affects both onedir and onefile builds (although in the former case, the user could fix this by manually re-signing all the .framework bundles), but the actual effect likely depends on the security policy on the target Mac.
> > We need to rework the bincache system with special handling for collected .framework bundles (and top-level embedded .app bundles as well - see #7969): all contents of the .framework to be collected needs to be copied to the cache, signed as a single entity, and collected from bincache (along with the `_CodeSignature/CodeResources` that is generated during the signing).
> 
> Very nice. So how about another problem, the system continue requesting permission for loading the dynamic libs in the lib-dynload. And I find that even execute sudo spctl –master-disable, m1 computer still need permission. It is very frustrating.

The files in lib-dynload should be signed (with ad-hoc identity by default, same as the main executable) regardless of the problem with .framework bundles. You can verify with `codesign -vv` again.

**Comment by ILG2021** [comment]
By the way, the error seems like:

```
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ImportError: dlopen(/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so, 0x0002): tried: '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (code signature in <20041707-32F0-365A-BC46-16F16463EDFC> '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (no such file), '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (code signature in <20041707-32F0-365A-BC46-16F16463EDFC> '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' not valid for use in process: library load disallowed by system policy)
```
_struct.cpython-311-darwin.so is the one of the dynamic libs block by the system.

**Comment by rokm** [comment]
> By the way, the error seems like:
> 
> ```
> Traceback (most recent call last):
>   File "struct.py", line 13, in <module>
> ImportError: dlopen(/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so, 0x0002): tried: '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (code signature in <20041707-32F0-365A-BC46-16F16463EDFC> '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (no such file), '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (code signature in <20041707-32F0-365A-BC46-16F16463EDFC> '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' not valid for use in process: library load disallowed by system policy)
> ```
> 
> _struct.cpython-311-darwin.so is the one of the dynamic libs block by the system.

Does it work if you build with PyInstaller 5.13.2 instead of 6.x?

**Comment by ILG2021** [comment]
> > By the way, the error seems like:
> > ```
> > Traceback (most recent call last):
> >   File "struct.py", line 13, in <module>
> > ImportError: dlopen(/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so, 0x0002): tried: '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (code signature in <20041707-32F0-365A-BC46-16F16463EDFC> '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' not valid for use in process: library load disallowed by system policy), '/System/Volumes/Preboot/Cryptexes/OS/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (no such file), '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' (code signature in <20041707-32F0-365A-BC46-16F16463EDFC> '/Users/mac/Downloads/my-app/_internal/lib-dynload/_struct.cpython-311-darwin.so' not valid for use in process: library load disallowed by system policy)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > _struct.cpython-311-darwin.so is the one of the dynamic libs block by the system.
> 
> Does it work if you build with PyInstaller 5.13.2 instead of 6.x?

still has the problem. the system will block Python and so libs. says that it is malicious. I am testing on os 14

the error is like:
`“_ctypes.cpython-311-darwin.so” can’t be opened because Apple cannot check it for malicious software.`  use codesign is no use.

**Comment by ILG2021** [comment]
pyinstaller 5.13.2 don't has the python.framework problem. but system still keeping block the so libs. Only type sudo spctl --global-disable can pass it. I am testing on mac os 14.2, maybe the new feature of the os.

**Comment by rokm** [comment]
> pyinstaller 5.13.2 don't has the python.framework problem. 

Yeah, that's expected, since `Python.framework` is preserved only in v6.

> but system still keeping block the so libs. Only type sudo spctl --global-disable can pass it. I am testing on mac os 14.2, maybe the new feature of the os.

I'm building on x86_64 Monterey (12.x), and testing on an M3 Mac that was just upgraded to 14.2, and I cannot reproduce this.

FWIW, I cannot reproduce the block due to unsigned `Python.framework` either, so I think for both parts of this problem, the security policy on your target Mac is also in play here. How do you run the program - from `Terminal` app? Do you have "Allow the applications below to run software locally that does not meet the system's security policy" enabled for `Terminal`?

**Comment by ILG2021** [comment]
> > pyinstaller 5.13.2 don't has the python.framework problem.
> 
> Yeah, that's expected, since `Python.framework` is preserved only in v6.
> 
> > but system still keeping block the so libs. Only type sudo spctl --global-disable can pass it. I am testing on mac os 14.2, maybe the new feature of the os.
> 
> I'm building on x86_64 Monterey (12.x), and testing on an M3 Mac that was just upgraded to 14.2, and I cannot reproduce this.
> 
> FWIW, I cannot reproduce the block due to unsigned `Python.framework` either, so I think for both parts of this problem, the security policy on your target Mac is also in play here. How do you run the program - from `Terminal` app? Do you have "Allow the applications below to run software locally that does not meet the system's security policy" enabled for `Terminal`?

I build on a mac os 13 and python 3.11. I double click the execute file.

**Comment by rokm** [comment]
Is it an x86_64 build, arm64 one, or universal2?

**Comment by ILG2021** [comment]
> Is it an x86_64 build, arm64 one, or universal2?

x86_64 build

**Comment by rokm** [comment]
What is the output of `xattr -lr /Users/mac/Downloads/my-app`? Is it empty?

**Comment by ILG2021** [comment]
> xattr -lr /Users/mac/Downloads/my-app

./my-app: com.apple.lastuseddate#PS: ???e
./my-app: com.apple.quarantine: 00c1;65828e49;QuarantineService;

**Comment by rokm** [comment]
Is the quarantine flag also set on the contents? Because that is the only scenario where I can reproduce the extensions in `lib-dynload` not being able to load with `... not valid for use in process: library load disallowed by system policy` error.

**Comment by rokm** [comment]
I.e., does recursively removing the quarantine flag (`xattr -dr com.apple.quarantine /Users/mac/Downloads/my-app`) fix the problem?

**Comment by vgvishesh** [comment]
> I.e., does recursively removing the quarantine flag (`xattr -dr com.apple.quarantine /Users/mac/Downloads/my-app`) fix the problem?

Running this command on the extracted app directory worked well.

**Comment by xyc** [comment]
I have this issue as well with MAS (Mac App Store) build containing a pyinstaller binary built with `--onefile`. If it's built into a directory it works fine.

**Comment by brusand** [comment]
is it the same issue as mine ?
816] Error loading Python lib '/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib': dlopen: dlopen(/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib, 10): no suitable image found.  Did find:
	/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib: cannot load 'libpython3.8.dylib' (load command 0x80000034 is unknown)
	/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib: cannot load 'libpython3.8.dylib' (load command 0x80000034 is unknown)

**Comment by rokm** [comment]
> is it the same issue as mine ? 816] Error loading Python lib '/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib': dlopen: dlopen(/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib, 10): no suitable image found. Did find: /Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib: cannot load 'libpython3.8.dylib' (load command 0x80000034 is unknown) /Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib: cannot load 'libpython3.8.dylib' (load command 0x80000034 is unknown)

What version of macOS did you build your program on, and what version of macOS are you trying to run it on? 

This seems to be the case of an older version of macOS not recognizing the `LC_BUILD_VERSION` load command (0x80000034) that is used by python shared library, which must have been built for a recent version of macOS (the old load command was `LC_VERSION_MIN_MACOSX`).

**Comment by ILG2021** [comment]
I think the problem is when i distribute the package i use zip, and it remove system link.
