### ISSUE TITLE
Pyinstaller build .exe step fails when buildspec console=False, works when console=True, Python 3.12.1 Win10 Pro 64bit VSCode Virtual Environment

### ISSUE THREAD

**Issue by RobertFishcake** [pyinstaller/pyinstaller#8162]
Pyinstaller build .exe step fails when buildspec console=False, but works when console=True.  Tried multiple times back to back with the flag swapped between True / False - same result.  I recently upgraded from Python 3.10.10 (everything else the same) and did not have this issue under that version of Python. I have cleanly installed Python 3.12.1 and have checked all paths etc - all is ok.

Python 3.12.1, Win10 Pro 64bit VSCode Virtual Environment

run1(fails):
pyinstaller --clean PyInstallerBuildSpec.spec
last few output messages: with console=False (the only difference):

48872 INFO: checking EXE
48872 INFO: Building EXE because EXE-00.toc is non existent
48872 INFO: Building EXE from EXE-00.toc
Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>

run2 (works):
pyinstaller --clean PyInstallerBuildSpec.spec
last few output messages: with console=True (the only difference):

49389 INFO: checking EXE
49389 INFO: Building EXE because EXE-00.toc is non existent
49390 INFO: Building EXE from EXE-00.toc
49390 INFO: Copying bootloader EXE to C:\Users\Private\Documents\...
49412 INFO: Copying icon to EXE
49422 INFO: Copying 0 resources to EXE
49422 INFO: Embedding manifest in EXE
49425 INFO: Appending PKG archive to EXE
49464 INFO: Fixing EXE headers
50581 INFO: Building EXE from EXE-00.toc completed successfully.
(venvTBRRS) PS C:\Users\Private\Documents\...

 PyInstallerBuildSpec.spec
# -*- mode: python ; coding: utf-8 -*-
block_cipher = None

a = Analysis(
    ['MyPythonProgram.py'],
    pathex=['..\\CommonModules'],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='PyInstallerBuildSpec',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['myIcon.ico'],
)

**Comment by rokm** [comment]
Did your anti-virus program removed the windowed bootloader executable? Try disabling the AV and reinstalling PyInstaller...

**Comment by RobertFishcake** [comment]
Yes it was my AV program... Avast!
It was silently blockly several steps through the creation of the .exe (but strangely only when console=False)
It seems to be moaning about [L] Win64:Evo-gen [Trj] (0)
Once I added all the Exceptions it works fine.
Many thanks!
