### ISSUE TITLE
Using PyInstaller version above  v5.13.2 results in numerous false-positives in VirusTotal

### ISSUE THREAD

**Issue by headshote** [pyinstaller/pyinstaller#8164]
This is the issue I discovered by recently updating to the latest (v6.3.0) version, and backtesting with 6.1 and 6.0. Somewhere between 15-18 AV vendors (mostly low-tier, but also including McAfee and Bitdefender, sometimes Google) flag my executable as malware, namely Gen:Variant.Cerbu.

Downgrading to v5.13.2 simply resolved the issue. 

The reason why I am adding this issue (do with it what you will) is that versions 6+ exploded in false-positives. I've been using PyInstaller since 2019 and this phenomenon is from these last releases.

**Comment by loekx4** [comment]
In Microsoft Defender as well

**Comment by rokm** [comment]
Take it up with your AV vendor. Or download PyInstaller source, compile the bootloader yourself, and install from source with your own build of bootloader. 

The only thing we can do here is to stop shipping pre-built bootloaders altogether - but then there will be complaints from people who don't know how to set up a C compiler; and on the other hand, nobody is forcing *you* to use the pre-build bootloaders. Convenience comes at a cost.

**Comment by headshote** [comment]
Absolutely don't care to take anything to vendors, just let you know, that 6+ causes this, no issues with older versions.

**Comment by bwoodsend** [comment]
Having known good and bad versions doesn't actually help us though. You might think we can look at what changed between them, find whatever's upsetting the antiviruses and magically fix it but in reality it just means that some antivirus somewhere saw a piece of malware built with PyInstaller 6.x (or mistook a PyInstaller application for malware), used it's dumb, but highly impressive sounding and marketable AI to memorise the wrong part of the file then, without any kind of validation, that classification gets uploaded to the *global threat intelligence database* (another naive but highly marketable concept) where the other stupid antiviruses see them and blindly copy them, causing this large wave of unanimous, but completely wrong, classifications across the different antiviruses.

We're completely powerless in this situation. All I can do is explain to people how the their antivirus actually works and hope that they'll bear that in mind when they choose whether or not to buy into them.

**Comment by headshote** [comment]
Ok, fair enough, it just might be that this "Cerbu" malware was packaged with v 6 and above of PyInstaller, discovered by antivirus(es) and now any PyInstaller-based app will suffer when using these versions (unless using custom build like suggested by you). This is a scenario I was fearing. Thanks for responding

**Comment by loekx4** [comment]
Thanks for your explanation, just wanted to let you know that this "happens". I understand we can't expect a dedicated solution for this issue from the pyinstaller side, but surely hope you can proceed with your excellent work and product. Thanks again!

**Comment by Lesserkuma** [comment]
Building your own bootloader no longer seems to work. Keep getting false-positives.

**Comment by Purfview** [comment]
v6.3.0 did some magic, a report is clean as a newborn:

![alt text](https://i.imgur.com/zCwRNOH.png)

[The report link]( https://www.virustotal.com/gui/file/b758831bc1cfed31e0b6a4dc636926f28f85c0c46f603e604277aa0ffbdd2bae).

I'm afraid to press "Reanalyze" now. 😆

**Comment by bwoodsend** [comment]
Pfff, don't celebrate too soon. The antivirses will adjust...

**Comment by ILG2021** [comment]
to reduce user's anxiety, i back to 5.13.2
