### ISSUE TITLE
Splash Image Persists After Application Launch

### ISSUE THREAD

**Issue by haqueshenas** [pyinstaller/pyinstaller#8165]
I used auto-py-to-exe to convert my Python code into an .exe file and configured the splash image in the Advanced section. However, when running the converted .exe file, I noticed that the image persists on the screen until the application is closed. I'm seeking guidance on resolving this issue. Thank you!

**Comment by rokm** [comment]
You need to close the splash screen in your application code. See the documentation: https://pyinstaller.org/en/stable/usage.html#splash-screen-experimental
