### ISSUE TITLE
failed to open archive file

### ISSUE THREAD

**Issue by gpangb** [pyinstaller/pyinstaller#8171]
We use PyInstaller to package our python scripts to an EXE file with the -F option. Most of the time the executables run without problem. But sometimes, we got the problem says "`Cannot open archive file`". We encountered this problem not only on one executables.

We tried to use the latest version of PyInstaller (6.1.0) to repackage one script and test, but we still get the similar error message "`Failed to extract pyi_rth_pkgres: failed to open archive file!`" occationally.

We tried to figure out the root cause and find the solution by searching the Internet, but we still cannot find any clue after weeks.

Does anyone know about this? What causes the problem and how to solve it?

**Comment by rokm** [comment]
If you encounter `Failed to extract pyi_rth_pkgres: failed to open archive file!`, then it means that we failed to open the executable for reading [here](https://github.com/pyinstaller/pyinstaller/blob/34a9fbecce956c1ffe16bf811ce2887300512a97/bootloader/src/pyi_archive.c#L221-L225). To get to this point, we had to be able to open it for reading at least once before (where the archive is initially parsed), so this suggests that on the problematic system, there is intermittent issues with access to the file. Either because of anti-virus program, network drive, some other OS issue, and so on.

**Comment by gpangb** [comment]
Thank rokm for the quick reply.

I had checked the PyInstaller source files before, we found there are two places that will print such messages, one is the place you mentioned, the other is [here](https://github.com/pyinstaller/pyinstaller/blob/34a9fbecce956c1ffe16bf811ce2887300512a97/bootloader/src/pyi_archive.c#L323-L329). According to the [comments of the function](https://github.com/pyinstaller/pyinstaller/blob/34a9fbecce956c1ffe16bf811ce2887300512a97/bootloader/src/pyi_archive.c#L289-L293), I thought the problem was at the later one. Then is it also possible to fail there?

There do is an anti-virus software running in these environments. But before attributing to the anti-virus, I want to exclude all other possible causes first, since it's hard to get the evidence of the anti-virus software.

Causing by network drives can be excluded, because the executables reside in hard disks, e. g. drive C or drive D.

At first, we thought it's related to the concurrent running of the executable. In these environments, the same executable may be launched by many different processes simultaneously. But I checked the source code, the temporary folder name consists of PID, and even if the name conflicts, the process will exits without such message. It seems the concurrent running doesn't matter.

**Comment by rokm** [comment]
> Thank rokm for the quick reply.
> 
> I had checked the PyInstaller source files before, we found there are two places that will print such messages, one is the place you mentioned, the other is [here](https://github.com/pyinstaller/pyinstaller/blob/34a9fbecce956c1ffe16bf811ce2887300512a97/bootloader/src/pyi_archive.c#L323-L329). According to the [comments of the function](https://github.com/pyinstaller/pyinstaller/blob/34a9fbecce956c1ffe16bf811ce2887300512a97/bootloader/src/pyi_archive.c#L289-L293), I thought the problem was at the later one. Then is it also possible to fail there?

It is also possible to fail here, yes (for the same reasons). But `pyi_rth_pkgres` is extracted into memory, not on the filesystem, so that particular error message was encountered in the codepath that I linked. But if the error is sporadic, you can probably see it for both cases.

> There do is an anti-virus software running in these environments. But before attributing to the anti-virus, I want to exclude all other possible causes first, since it's hard to get the evidence of the anti-virus software.
> 
> Causing by network drives can be excluded, because the executables reside in hard disks, e. g. drive C or drive D.
> 
> At first, we thought it's related to the concurrent running of the executable. In these environments, the same executable may be launched by many different processes simultaneously. But I checked the source code, the temporary folder name consists of PID, and even if the name conflicts, the process will exits without such message. It seems the concurrent running doesn't matter.

This is about opening executable file for reading, so concurrent access from multiple processes should not matter (unless CRT has some limitation on that which I am not aware of). I would find it more likely that the hypothetical anti-virus program is trying to gate access, and causes issues when there are multiple simultaneous requests.

**Comment by rokm** [comment]
> > Thank rokm for the quick reply.
> > I had checked the PyInstaller source files before, we found there are two places that will print such messages, one is the place you mentioned, the other is [here](https://github.com/pyinstaller/pyinstaller/blob/34a9fbecce956c1ffe16bf811ce2887300512a97/bootloader/src/pyi_archive.c#L323-L329). According to the [comments of the function](https://github.com/pyinstaller/pyinstaller/blob/34a9fbecce956c1ffe16bf811ce2887300512a97/bootloader/src/pyi_archive.c#L289-L293), I thought the problem was at the later one. Then is it also possible to fail there?
> 
> It is also possible to fail here, yes (for the same reasons). But `pyi_rth_pkgres` is extracted into memory, not on the filesystem, so that particular error message was encountered in the codepath that I linked. But if the error is sporadic, you can probably see it for both cases.

It might also be worth noting that run-time hook (such as `pyi_rth_pkgres`) and entry-point script extraction happens *after* data and binaries are extracted to the temporary directory (so in this particular cases, the open attempts in the code path that you linked must have all suceeded). It also happens in the child process (the one that runs python interpreter and those scripts), as opposed to the parent process (which does the data and binaries extraction).

**Comment by gpangb** [comment]
Thanks rokm, I will try to configure the anti-virus program to exclude the folder where the executable locates and observe whether the problem happen again.

Is excluding this folder enough, do I need to exclude other folders, for example the folder where the temporary folder locates? The temporary folder is created in the Windows temp folder, exclude the Windows temp folder is not safe.

**Comment by rokm** [comment]
I think excluding the executable (or its location) should do the trick, if this is what is causing the problem. 

I don't think there is any need to exclude the temporary directory, though - unless you receive an error message that indicates that we failed to open the target file in the temporary directory (as opposed to failing to (re)open the executable file and its embedded archive).
