### ISSUE TITLE
Pyinstaller not bundling txt files when installing scikit-image

### ISSUE THREAD

**Issue by severecoder** [pyinstaller/pyinstaller#8176]
I have tried various versions of pyinstaller to install scikit-image and while the installation is successful, the txt files under skimage.filters are not bundled.

The orb_descriptor_positions.py looks for orb_descriptor_positions.txt in the same location as the python file  "skimage.filters " but the location only contains .so files now. 

At this point, I am forcing pyinstaller to add the file using the following command.

add_data_template.format("data/orb_descriptor_positions.txt", "debian/usr/share/applications/skimage/feature")

**Comment by rokm** [comment]
> Pyinstaller not bundling txt files...

PyInstaller by default does not collect non-python data files unless you tell it to. Or unless an existing hook for a package tells it to collect the data files from that package.

That being said, I'll update [the hook for `skimage.feature`](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/src/_pyinstaller_hooks_contrib/hooks/stdhooks/hook-skimage.feature.py) to collect that `orb_descriptor_positions.txt`.

**Comment by severecoder** [comment]
Thank you so much for the quick response. This is interesting because on our older builds, I have the txt file packaged into the path but it just suddenly stopped working for me.

**Comment by rokm** [comment]
What version of `scikit-image` were you using in the old builds, and what version are you using now? The `orb_descriptor_positions.txt` seems to have moved from `skimage/data` to `skimage/feature` in v0.17.0, but I don't think we had a hook that was collecting it from `skimage/data`, either.
