### ISSUE TITLE
A hybrid freez as onefile/onedir

### ISSUE THREAD

**Issue by Purfview** [pyinstaller/pyinstaller#8178]
Is there a way to do it?

If no then would it be hard to implement such feature to keep some libs/files as onedir when the rest packed as onefile?

**Comment by rokm** [comment]
> Is there a way to do it?

Nope.

> If no then would it be hard to implement such feature to keep some libs/files as onedir when the rest packed as onefile?

Yes. And that's not even considering my aversion to having to implement and/or maintain such a "feature".

**Comment by bwoodsend** [comment]
What on earth would be the point? It's not a self contained single file nor does it avoid all the issues that accompany exectuables unpacking their guts on the fly. It's a worst of both worlds!

**Comment by Purfview** [comment]
> What on earth would be the point? It's not a self contained single file nor does it avoid all the issues that accompany exectuables unpacking their guts on the fly. It's a worst of both worlds!

Point would be a close look to "single file" when keeping few gigabytes sized libs outside.

**Comment by bwoodsend** [comment]
I hoped that banishing all the non executable files into that `_internal` directory would remove the incentive to have *less files*.

**Comment by Purfview** [comment]
> I hoped that banishing all the non executable files into that `_internal` directory would remove the incentive to have _less files_.

Thanks for the hint, I didn't knew that such feature was recently implemented. Now onedir looks like usable option.

Btw, default `_internal` name can be changed with `--contents-directory`.
