### ISSUE TITLE
ModuleNofFoundError: google.generativeai trouble

### ISSUE THREAD

**Issue by NumerusXXL** [pyinstaller/pyinstaller#8179]
## Description of the issue
I am building a simple app. When I try to make the .py to exe using no matter which tool Pyinstaller ,py2exe. Nothing works. It makes an exe for me, but it always says module google not found. I also tried it with VERY simple code, using only the google library, but same issue

I use the pyinstaller --onefile main.py
I installed the library and it successfully works in pycharm as a .py

### Context information (for bug reports)

* Output of `pyinstaller --version`: (6.3.0)
* Version of Python: 3.11.2 final.0
* Platform: Windows 10 Pro 19045 (English) 
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there?: I tried it on a Win11 23H2 VM. No it also doesnt work

### A minimal example program which shows the error

main.py:

import google.generativeai as genai
genai.configure(api_key="///")
gemini_model = genai.GenerativeModel('gemini-pro')
prompt = input()
completion = gemini_model.generate_content(
prompt,
generation_config=genai.types.GenerationConfig(

        temperature=0.3)
)

response = completion.text
print(response)

### Stacktrace / full error message

Traceback (most recent call last):
File "main.py", line 10 in <module>
ModuleNotFoundError: No module named 'google'
[3380] Failed to execute script 'main' due to unhandled exception

**Comment by bwoodsend** [comment]
>  I installed the library and it successfully works in pycharm as a .py

Have you tried running it outside of PyCharm? PyCharm likes to set up virtual environments for you so that you don't realise that your dependencies are installed in the wrong Python environment.

**Comment by NumerusXXL** [comment]
Yes, I get the same error:

C:\Users\Misha\PycharmProjects\geminiTest>python main.py
Traceback (most recent call last):
  File "C:\Users\Misha\PycharmProjects\geminiTest\main.py", line 3, in <module>
    import google.generativeai as genai
ModuleNotFoundError: No module named 'google'

**Comment by NumerusXXL** [comment]
But I also allready created different projects, different venv (using PyCharm). Also the path to the venv seems to be correct. It also works with every other library. Just not with the one from google.

Here is the .venv in pycharm terminal : (.venv) PS C:\Users\Misha\PycharmProjects\geminiTest> 

Everything seems to be correct

**Comment by rokm** [comment]
Your example works for me, so this is a problem with your environment; most likely, you are running `pyinstaller` that is installed in a different environment than `google-generativeai` and your other project dependencies.

What is the output of `where pyinstaller`?

**Comment by NumerusXXL** [comment]
C:\Users\Misha\PycharmProjects\gemini-translator-queen-parts MT>where pyinstaller
C:\Users\Misha\AppData\Local\Programs\Python\Python311\Scripts\pyinstaller.exe

**Comment by NumerusXXL** [comment]
Seems to be so. Could you help me out by saying how to fix this? I am just starting with Python, so I dont realise many things.
