### ISSUE TITLE
Pyinstaller having problems with relative paths 

### ISSUE THREAD

**Issue by Scorptech** [pyinstaller/pyinstaller#8181]
Hi, 

I've started to use Pyinstaller to compile my Python programs, but I came across a major issue a lot of people seem to be having problems with. 

I have checked out the Pyinstaller website for information along with a number of web searches, but no seems to have solved the program. The issue is with relative paths using ico files and standard png files. 

The only work around I can do is to use an absolute path, which is obviously not ideal. 

Do you have any links or solutions to this problem. I'll be happy to make a Youtube video showing a solution if there is one. 

I have tried a number of the recommended solutions but none of them have worked. 

Regards 

Alan

**Comment by bwoodsend** [comment]
https://pyinstaller.org/en/stable/runtime-information.html?highlight=__file__#using-file
