### ISSUE TITLE
PyInstaller-Converted .exe File Not Saving Output Images as Expected

### ISSUE THREAD

**Issue by Akashmsagar0707** [pyinstaller/pyinstaller#8182]
I am stuck with an unusual problem. I have a GUI code written in Python PyQt5. It has images, put inside an image folder and many python files. This GUI is working fine in Pycharm. I am able to generate a standalone executable file for this project using Pyinstaller. When i run the exe , no images are visible in GUI . i have really tried hard and searched a lot of internet for the same , but still i am not getting this concept of getting the images . please help me for this .

**Comment by bwoodsend** [comment]
Most likely your code is not relocatable (uses relative paths instead of paths anchored to [`__file__`](https://pyinstaller.org/en/stable/runtime-information.html?highlight=__file__#using-file) and/or you're not collecting those images into your application (e.g. via `--add-data`).
