### ISSUE TITLE
duplicated logs when upgrading from v5 to v6

### ISSUE THREAD

**Issue by ehdez** [pyinstaller/pyinstaller#8185]
When running a web app through pyinstaller, the logging messages are duplicated several times, like so:

![cap1](https://github.com/pyinstaller/pyinstaller/assets/25016247/5392efc6-9487-4c3b-840a-a0f4d2cb9cfa)
![cap2](https://github.com/pyinstaller/pyinstaller/assets/25016247/34332de1-bb23-4984-ab47-63ced0b359c1)
![cap3](https://github.com/pyinstaller/pyinstaller/assets/25016247/81953790-3507-471c-ba90-8ee92c584595)

This was not the case before upgrading to v6... could this be a bug?

**Comment by rokm** [comment]
What do you mean by duplicated? These appear to be coming from three different processes - if this happens within the single run of your web app, it means that it is spawning sub-processes using `sys.executable`, and hence you get run log for each such sub-process.
