### ISSUE TITLE
pyinstaller 打包整个项目时spec配置中的console=False问题

### ISSUE THREAD

**Issue by Adreaming5101** [pyinstaller/pyinstaller#8187]
我生成了spec文件，将spec文件里的console设置成Teue，并且打包成exe后，前端后端能正常交互；但是当我将console设置成False后，前端后端无法正常交互，前端界面出现网络错误，无法登录，前端报错信息为“POST http://127.0.0.1:17777/ net::ERR_EMPTY_RESPONSE”，请问有什么思路能帮忙解决吗？

**Comment by bwoodsend** [comment]
Not based on a description as inadequate as that.
