### ISSUE TITLE
Pygame program fails to run after building with pyinstaller 2.1

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#819]
**Original date**: 2013/11/09
**Original reporter**: *fox_rtkbur AND TrashMail DOT net*

Using Pyinstaller 2.1, running the resulting binary gives this output:
Traceback (most recent call last):
  File "<string>", line 18, in <module>
  File "/home/s/.pyinstaller-2.1/PyInstaller/loader/pyi_importers.py", line 270, in load_module
    exec(bytecode, module.__dict__)
  File "/usr/lib/python2.7/dist-packages/pygame/__init__.py", line 99, in <module>
    from pygame.base import *
ImportError: No module named base

However, this works without problems using Pyinstaller 1.5.1.

**Comment by matysek** [comment]
Closing. Not enough information to reproduce and no code example for testing.

**Comment by WreXplorer** [comment]
Any chance this could be reopened? I am experiencing the same issue. It takes place while simply importing pygame in any *.py. Software runs normally then when attempting to run the exported executable in a 64-bit ubuntu os, the output lists exactly as shown above. No idea what is causing this and I am running out of thoughts.

**Comment by htgoebel** [comment]
Of course we can reopen this, if one is willing to submit a minimal example on how to reproduce this error. See https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs
