### ISSUE TITLE
Pyinstaller having small django APP with image upload and file upload

### ISSUE THREAD

**Issue by eshopblr** [pyinstaller/pyinstaller#8201]
I'm using a Django app which uploads images and files and generated a exe.
when the exe is ran the MEDIA file which stores the images are stored in the TEMP directory while exe is running and are accessible by the APP.
Once I stop the exe the TEMP directory getting deleted and also the images that are uploaded lost. IS there a way how to address this and store on the known path instead of TEMP directory.  I'm looking for a standard way and portable across platforms?

**Comment by bwoodsend** [comment]
Well put them somewhere else then. [`appdirs.user_data_dir()`](https://pypi.org/project/appdirs/) is probably what you're looking for.
