### ISSUE TITLE
The Pyinstaller build product does not meet the security compilation options

### ISSUE THREAD

**Issue by Galun-yase** [pyinstaller/pyinstaller#8203]
On the Linux platform, scan BIND_NOW, NX, PIC, PIE, FS, and Strip using tools
There are situations where the security compilation options are not met;

On the Windows platform, when scanning security compilation options such as GSCheck, NXCheck, DBCheck, and SafeSEHCheck using tools, there are situations where they are not met.

**Comment by rokm** [comment]
>  There are situations where the security compilation options are not met;

Care to divulge some details on those situations? Which options are missing, and from what files the executable itself or a binary collected from the build environment?
