### ISSUE TITLE
"No module named pyinstaller": support `python -m pyinstaller`

### ISSUE THREAD

**Issue by bersbersbers** [pyinstaller/pyinstaller#8215]
**Is your feature request related to a problem? Please describe.**
Many tools recommend running `python -m modulename` to make sure the correct python version/venv is used instead of relying on shims or otherwise configured entry points. However, `python -m pyinstaller` errors with
> No module named pyinstaller

**Describe the solution you'd like**
`python -m pyinstaller` should behave the same way as `pyinstaller(.exe)` does.

**Comment by bwoodsend** [comment]
The module name is case sensitive `PyInstaller` so it's `python -m PyInstaller`.

I would have preferred that the module name uses the same lower case as the project and repo and PyPI distribution names do but I think we're 15 years too late to fix that.

**Comment by bersbersbers** [comment]
Oh, thank you!
