### ISSUE TITLE
Architecture detection on Windows ARM64 emulating AMD64 is broken

### ISSUE THREAD

**Issue by robertobrien130** [pyinstaller/pyinstaller#8219]
Hello,

I have the same problem as https://github.com/pyinstaller/pyinstaller/issues/8183 but apparently with a different root cause.

I'm using Python 3.12.1 and Windows 11, pyinstaller version 6.3.0

When trying to compile from my spec file, I get the following error:

X:\Desktop\SportsGuru>pyinstaller SportsGuruGUI.spec
296 INFO: PyInstaller: 6.3.0
296 INFO: Python: 3.12.1
312 INFO: Platform: Windows-11-10.0.22631-SP0
327 INFO: Extending PYTHONPATH with paths
['X:\\Desktop\\SportsGuru']
644 INFO: Appending 'binaries' from .spec
644 INFO: checking Analysis
785 INFO: checking PYZ
848 INFO: checking PKG
896 INFO: Bootloader C:\Users\robertobrien\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-arm\runw.exe
896 INFO: checking EXE
896 INFO: Building EXE because EXE-00.toc is non existent
896 INFO: Building EXE from EXE-00.toc
Fatal error: PyInstaller does not include a pre-compiled bootloader for your
platform. For more details and instructions how to build the bootloader see
<https://pyinstaller.readthedocs.io/en/stable/bootloader-building.html>

I followed the tips in the above linked issue, but all of the 4 files are in my Python\Lib\site-packages\PyInstaller\bootloader folder.

What am I missing?

**Comment by bwoodsend** [comment]
To double check, if you type
```
stat C:\Users\robertobrien\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-arm\runw.exe
```
into a terminal/command prompt, you don't get some kind of file not found error?

**Comment by bwoodsend** [comment]
Also could you check the output of `python -m platform` does say `ARM64`?

**Comment by robertobrien130** [comment]
I do get a "Windows cannot find the file specified" error.

For your other question:

C:\Users\robertobrien>python -m platform
Windows-11-10.0.22631-SP0

C:\Users\robertobrien>

**Comment by robertobrien130** [comment]
runw.exe is here: "C:\Users\robertobrien\AppData\Local\Programs\Python\Python312\Lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe"

**Comment by rokm** [comment]
Are you running ARM64 python on ARM64 Windows machine?

What is the output of
```
import platform
print(platform.machine())
```

The error message suggests that you are running on ARM64, but have a PyInstaller installation with x64 bootloaders (i.e., you have an AMD64 PyPI wheel installed instead of ARM64 one, for some reason).

**Comment by robertobrien130** [comment]
I'm running windows 11 in Parallels on a Mac

when I run the above Python code, it outputs `ARM64`

**Comment by rokm** [comment]
Then you probably ended up with x64 PyPI wheel (which has x64 bootloaders in `Windows-64bit-intel`) instead ARM64 wheel (which has ARM64 bootloaders in `Windows-64bit-arm`, where PyInstaller expects to find them on ARM64 system).

If you install PyInstaller in a clean virtual environment, e.g.,
```
C:\Users\robertobrien\AppData\Local\Programs\Python\Python312\python.exe -m venv venv
venv\Scripts\activate.bat
python -m pip install -U pip wheel setuptools
python -m pip install --no-cache-dir PyInstaller
```

do you see it download and install `pyinstaller-6.3.0-py3-none-win_arm64.whl ` or `pyinstaller-6.3.0-py3-none-win_amd64.whl`?

If you keep ending up with x64/amd64 variant instead of arm64, the fastest way to work around the issue will probably be to manually download the arm64 wheel from https://pypi.org/project/pyinstaller/#files and install the downloaded wheel, `pip install <filename>`.

**Comment by robertobrien130** [comment]
It does download the AMD version in the venv:

```Downloading pyinstaller-6.3.0-py3-none-win_amd64.whl.metadata (8.3 kB)
Requirement already satisfied: setuptools>=42.0.0 in c:\users\robertobrien\venv\lib\site-packages (from PyInstaller) (69.0.3)
```

I downloaded the ARM wheel directly from the above link, and when I went to install it via pip, I'm now getting this error:

```C:\Users\robertobrien>pip install pyinstaller-6.3.0-py3-none-win_arm64.whl
ERROR: pyinstaller-6.3.0-py3-none-win_arm64.whl is not a supported wheel on this platform.
```

**Comment by bwoodsend** [comment]
Where did you install Python from?

**Comment by robertobrien130** [comment]
Ah you may be on to something there. I installed it from the python website, but it looks like the file I downloaded is `python-3.12.1-amd-64`

**Comment by bwoodsend** [comment]
That would certainly explain it (although I'm surprised that `platform.machine()` doesn't return `AMD64` in that case).

**Comment by bwoodsend** [comment]
If you still have that amd64 Python installed, could you check what this returns?
```python
import sysconfig
print(sysconfig.get_platform())
```

**Comment by rokm** [comment]
As well as:
```python
import os
print(os.environ.get('PROCESSOR_ARCHITEW6432'))
print(os.environ.get('PROCESSOR_ARCHITECTURE'))
print(os.environ.get('PROCESSOR_IDENTIFIER'))
```

these are used behind the scenes in `platform.machine`, although python 3.12 added a WMI-based check that takes precedence over those...

**Comment by bwoodsend** [comment]
Answering our own questions:
```python
>>> import platform
>>> platform.machine()
'ARM64'

>>> platform.architecture()
('64bit', 'WindowsPE')

>>> import sysconfig
>>> print(sysconfig.get_platform())
win-amd64

>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
None
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
AMD64
>>> print(os.environ.get('PROCESSOR_IDENTIFIER'))
ARMv8 (64-bit) Family 8 Model 0 Revision   0, QEMU
```
I guess that if we detected a Windows+ARM64 environment based on either `sysconfig.get_platform()` or `os.environ.get('PROCESSOR_ARCHITECTURE')` then we'd have dodged this?

**Comment by bwoodsend** [comment]
And for reference, this is what it looks like with the 32 bit installer on ARM64.
```python
>>> import platform
>>> platform.machine()
'ARM64'

>>> import sysconfig
>>> print(sysconfig.get_platform())
win32

>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
ARM64
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
x86
>>> print(os.environ.get('PROCESSOR_IDENTIFIER'))
ARMv8 (64-bit) Family 8 Model 0 Revision   0, QEMU
```

**Comment by rokm** [comment]
Is this with python 3.12? Could you also check an earlier version (e.g., 3.11) - to see if the addition of WMI-based query changed the behavior of `platform.machine()`?

**Comment by rokm** [comment]
Although I suppose
```
>>> import platform
>>> platform.machine()
'ARM64'
```

and 

```
>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
None
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
AMD64
```

should be a proof enough that the WMI query that takes precedence over `PROCESSOR_` environment variables in 3.12 is what makes `platform.machine()` return `ARM64`...

**Comment by bwoodsend** [comment]
Those outputs on Python 3.11 are identical to the ones from Python 3.12.

**Comment by rokm** [comment]
> Those outputs on Python 3.11 are identical to the ones from Python 3.12.

Hmm, that's odd - what about `platform._get_machine_win32()`?

**Comment by robertobrien130** [comment]
For what it's worth, I tried installing the ARM Python version, but it doesn't support so many of the wheels that I needed for my app that I ended up just spinning up a virtual desktop and was able to successfully run everything there.

**Comment by rokm** [comment]
> For what it's worth, I tried installing the ARM Python version, but it doesn't support so many of the wheels that I needed for my app

Yeah, the lack of arm64 Windows wheels means that at least for now, it might make more sense to run x64 python using emulation on arm64. Which is why we need to improve our detection of x86 or x64 python running on arm64.

**Comment by rokm** [comment]
So we have:

<details><summary>x64 on x64 (native) - mingw64</summary><p>

```
>>> import platform
>>> platform.machine()
'AMD64'

>>> platform.architecture()
('64bit', 'WindowsPE')

>>> import sysconfig
>>> print(sysconfig.get_platform())
mingw_x86_64

>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
None
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
AMD64
```

</p></details>


<details><summary>x64 on x64 (native) - python.org</summary><p>

```
>>> import platform
>>> platform.machine()
'AMD64'

>>> platform.architecture()
('64bit', 'WindowsPE')

>>> import sysconfig
>>> print(sysconfig.get_platform())
win-amd64

>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
None
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
AMD64
```


</p></details>

<details><summary>x86 on x64 - mingw32</summary><p>

```
>>> import platform
>>> platform.machine()
'AMD64'

>>> platform.architecture()
('32bit', 'WindowsPE')

>>> import sysconfig
>>> print(sysconfig.get_platform())
mingw_i686

>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
AMD64
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
x86
```

</p></details>



<details><summary>x86 on x64 - python.org</summary><p>

```
>>> import platform
>>> platform.machine()
'AMD64'

>>> platform.architecture()
('32bit', 'WindowsPE')

>>> import sysconfig
>>> print(sysconfig.get_platform())
win32

>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
AMD64
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
x86
```

</p></details>


<details><summary>x64 on arm64</summary><p>

``` 
>>> import platform
>>> platform.machine()
'ARM64'

>>> platform.architecture()
('64bit', 'WindowsPE')

>>> import sysconfig
>>> print(sysconfig.get_platform())
win-amd64

>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
None
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
AMD64
```

A minor inconsistency is that `PROCESSOR_ARCHITEW6432` is not set (I read somewhere that x64 emulation on arm64 does not use WOW), but luckily, we are not interested in the *host* architecture, but in the target/emulated one.

</p></details>

<details><summary>x86 on arm64</summary><p>


``` 
>>> import platform
>>> platform.machine()
'ARM64'

>>> import sysconfig
>>> print(sysconfig.get_platform())
win32

>>> import os
>>> print(os.environ.get('PROCESSOR_ARCHITEW6432'))
ARM64
>>> print(os.environ.get('PROCESSOR_ARCHITECTURE'))
x86
``` 

</p></details>


We can probably use `PROCESSOR_ARCHITECTURE` environment variable, and within the context of bootloader path, we only need to determine if the lowercase string starts with `arm` or not (for `arm` vs `intel` suffix).

**Comment by bwoodsend** [comment]
It looks like pip (via packaging) [is using sysconfig](https://github.com/pypa/packaging/blob/57a6a7ff661930a8b0dde55663947b80cf3c196a/src/packaging/tags.py#L508-L521C16). It would probably make sense to match method, although it probably doesn't matter either way.

**Comment by rokm** [comment]
> It looks like pip (via packaging) [is using sysconfig](https://github.com/pypa/packaging/blob/57a6a7ff661930a8b0dde55663947b80cf3c196a/src/packaging/tags.py#L508-L521C16). It would probably make sense to match method, although it probably doesn't matter either way.

Does `sysconfig.get_platform()` under arm64 python return `win-arm64`? I'm not particularly happy with its return values differing between mingw and python.org python, but if all we are after is `if 'arm' in sysconfig.get_platform().lower()`, then it should be OK as well.

**Comment by bwoodsend** [comment]
> Does sysconfig.get_platform() under arm64 python return win-arm64?

Yes. And `PROCESSOR_ARCHITECTURE` is set to `ARM64`.

**Comment by bwoodsend** [comment]
I suppose that `PROCESSOR_ARCHITECTURE` does give us exactly what we're looking for without any normalisation. In which case, I guess I'll vote we use `PROCESSOR_ARCHITECTURE`.

**Comment by rokm** [comment]
Considering [what `sysconfig.get_platform` seems to be doing](https://github.com/python/cpython/blob/77b45fa6d0b8c0c14657b5117b21a3f3f2ce97d8/Lib/sysconfig/__init__.py#L553-L581), `PROCESSOR_ARCHITECTURE` gets my vote as well.

**Comment by bwoodsend** [comment]
Ughh why would it do that? I thought that the whole point of the sysconfig module was to expose compile time options, in this case the target platform...

**Comment by bwoodsend** [comment]
How do you expect `non-native-python waf all` to work? Half the time, `wscript` sets its target platform based on what `waf` can infer from the compiler and the other half it defaults to building a native binary.

In the case of x86/AMD64 Python running on ARM64, I'd personally expect `python waf all` to build for the same architecture as Python but currently, the compiler target platform detection unconditionally picks arm.

**Comment by rokm** [comment]
Hmm, I think I would expect it to build the bootloader for the (emulated) python's architecture, because that is going to be used when user tries to run PyInstaller in that environment.
