### ISSUE TITLE
Start another python interpreter and script from single file exe

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#822]
**Original date**: 2013/11/11
**Original reporter**: *anonymous*

It would be very nice to be able to start a Python program using another instance of the Python interpreter/library from a onefile package.

The reason for this request is to circumvent packages like multiprocessing and to be able to start sub processes independent of the current running Python interpreter instance. Note that multiprocessing is not a option on all platforms. Of course the new instanciated/started Python interpreter and the module it loads should be in the working dir of the package or the onefile packaged exe.

For instance:
When a Python module ProgramA packaged into a single file exe wants to start Python ProgramB from it, I would code from ProgramA.py:

   os.system("ProgramB.py")

I cannot find a way to do this (and it might be even more complex when ProgramB.py contains PyQt4 calls).

**Comment by htgoebel** [comment]
This would basically mean we should include the complete Python interpreter into PyInstaller. I don't think, this is a good idea.
Either you ensure, Python is installed on the target system *or* you freeze your other program with PyInstaller, too.

Closing as wn't fix.
