### ISSUE TITLE
Error loading Python lib '/tmp/_MEIxDVGoc/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIxDVGoc/libpython3.9.so.1.0)

### ISSUE THREAD

**Issue by junjielyu13** [pyinstaller/pyinstaller#8222]
I get the following isseu:

**Error loading Python lib '/tmp/_MEIxDVGoc/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /tmp/_MEIxDVGoc/libpython3.9.so.1.0)**

This problem occurred when I packaged the program on a computer and sent it to my server

How can I solve this problem through packaging? Instead of modifying the server environment

**Comment by rokm** [comment]
> How can I solve this problem through packaging? Instead of modifying the server environment

By packaging on a system that has glibc as old (or older) than your server. See [the docs](https://pyinstaller.org/en/stable/usage.html#making-gnu-linux-apps-forward-compatible).

**Comment by junjielyu13** [comment]
How do I use an older version of glibc for packaging? Download an older version to my computer? Is there any other way

**Comment by rokm** [comment]
Set up a build system (a VM or a Docker container) with distribution that has old enough glibc (or that matches your server).

**Comment by junjielyu13** [comment]
can I use this repo **https://github.com/ripiuk/pyinstaller-many-linux** to packing my python file?

**Comment by rokm** [comment]
> can I use this repo **https://github.com/ripiuk/pyinstaller-many-linux** to packing my python file?

Considering that it was last updated 5 years ago, I don't think that's a good idea... It's a free world, though (at least for the time being).

FWIW, if your application is simple enough and since you seem to be using `onefile` mode, you could also try using `staticx` to work-around the glibc: https://pypi.org/project/staticx

**Comment by bwoodsend** [comment]
It's pretty easy just to an old generic base image:
```console
$ docker run -v "$PWD:/io" -it ubuntu:focal
# cd /io
# apt-get update && apt-get install -y python3-pip
# pip3 install pyinstaller -r your-requirements.txt
# pyinstaller your-code.py

**Comment by junjielyu13** [comment]
> It's pretty easy just to an old generic base image:
> 
> ```
> $ docker run -v "$PWD:/io" -it ubuntu:focal
> # cd /io
> # apt-get update && apt-get install -y python3-pip
> # pip3 install pyinstaller -r your-requirements.txt
> # pyinstaller your-code.py
> ```

It's seems work to me,  thanks! ! I use the ubuntu:18.04 image to package, which uses gblic2.27, and should be able to be run on my server. (I crashed the server yesterday :sweat_smile:, I will test it after when I fix server. Thank you all.)
