### ISSUE TITLE
ModuleNotFoundError: No module named 'gcsfs'

### ISSUE THREAD

**Issue by rupurt** [pyinstaller/pyinstaller#8228]
Howdy :wave: 

I'm having trouble getting `fsspec` and `gcsfs` to work with `pyinstaller`. `fsspec` is using `importlib` to [dynamically import](https://github.com/fsspec/filesystem_spec/blob/2e3f0221a5b9d2d3489c85058d388387a1235de3/fsspec/registry.py#L254) the `gcsfs.GCSFileSystem` module and class into the registry.

I've created the following custom hook

```python
from PyInstaller.utils.hooks import collect_data_files

module_collection_mode = "py+pyz"
hiddenimports = [
    "gcsfs",
]
datas = collect_data_files("gcsfs")
```

But I still get the following error

```shell
ModuleNotFoundError: No module named 'gcsfs'

The above exception was the direct cause of the following exception:

╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ in download:95                                                                                   │
│                                                                                                  │
│ in _filesystem:128                                                                               │
│                                                                                                  │
│ in filesystem:290                                                                                │
│                                                                                                  │
│ in get_filesystem_class:238                                                                      │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
ImportError: Please install gcsfs to access Google Storage
[735368] Failed to execute script 'main' due to unhandled exception!

```

**Comment by rokm** [comment]
What if you add `--hidden-import gcsfs` or even `--collect-submodules gcsfs` to your PyInstaller command instead (assuming you building directly from your .py file, not from the .spec file)?

**Comment by rupurt** [comment]
That works @rokm! Cheers.

Silly me for not trying that first... I've recently cleanup up our `Makefile` to move those flags into hooks. Any idea why that wouldn't work in a hook?

**Comment by bwoodsend** [comment]
Possibly you forgot to `--additional-hooks-dir` the hook's parent directory into PyInstaller's hook search path? Also PyInstaller's caching doesn't notice hook changes so a `--clean` could have been the answer too. PyInstaller logs the hooks it loads so I'd check there to see if it's actually being loaded.

**Comment by rokm** [comment]
> That works @rokm! Cheers.
> 
> Silly me for not trying that first... I've recently cleanup up our `Makefile` to move those flags into hooks. Any idea why that wouldn't work in a hook?

You didn't mention which module you were trying to hook with that hook - `fsspec` or `gcsfs`? (i.e., what was the hook's filename?)

**Comment by rupurt** [comment]
`gcsfs`. It's in the hidden imports of the hook file

**Comment by rokm** [comment]
> `gcsfs`. It's in the hidden imports of the hook file

But is the hook called `hook-fsspec.py` or `hook-gcsfs.py`? I.e., which module is supposed to trigger the hook?

**Comment by rupurt** [comment]
Ah gotcha. It's called `hook-gcsfs.py`

**Comment by rokm** [comment]
> Ah gotcha. It's called `hook-gcsfs.py`

Then that's why it doesn't work. It should have been called `hook-fsspec.py`, and it should contain only the 
```
hiddenimports = [
    "gcsfs",
]
```
statement.

So that when PyInstaller's analysis encounters `fsspec`, it runs the hook, which tells it that `fsspec` has a hidden (indirect) import of `gcsfs`. 

A `hook-gcsfs.py` specifying `gcsfs` as a hidden import is pointless, because if a hidden import is required (all imports of that module are indirect), analysis will never see `gcsfs`, and will thus also never run the hook.

**Comment by rupurt** [comment]
Ah ok, that makes a lot of sense. Thank you for the pointer! It worked :smile: :tada:
