### ISSUE TITLE
symbol not found in flat namespace '__ZN9tesseract11TessBaseAPID1Ev'.  /. Segmentation fault: 11

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#8229]
File "poker/main.py", line 14, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "poker/restapi_local.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "poker/tools/screen_operations.py", line 11, in <module>
ImportError: dlopen(/Users/dickr/dev/Poker/poker/dist/main/_internal/tesserocr.cpython-311-darwin.so, 0x0002): symbol not found in flat namespace '__ZN9tesseract11TessBaseAPID1Ev'

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.3.0```
* Version of Python: 3.11
* Platform: MacOs
* How you installed Python: Conda
* Did you also try this on another platform? Yes, it works fine with windows. I also tied with pure python, then I get a different error:
* (.venv) (base) NICOLASs-MacBook-Pro:main dickr$ ./main
Segmentation fault: 11

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

I'm trying to package www.github.com/dickreuter/Poker

**Comment by rokm** [comment]
1. How did you install `tesserocr` in the `conda` case - via `conda` or via `pip`? Is this a pure conda environment (everything installed via conda), or are there pip-installed dependencies in it as well? Do you also happen to have a Homebrew installed on the build system?

2. If you open `build/main/Analysis-00.toc` and search for tesseract shared libraries (`libtesseract`, `libleptonica`), were they collected? If so, where were they collected from?

3. Can you reproduce the problem with just the following program:
```python
from tesserocr import PyTessBaseAPI, PSM, OEM  # line 11 from poker/tools/screen_operations.py
print("hello")
``` 

If so, can you archive the resulting `build` and `dist` directory and upload it somewhere so I can take a look at it? (note: if you are going to create a zip, make sure to use `-y` / `--symlinks` option to preserve symlinks).

**Comment by bwoodsend** [comment]
> I also tied with pure python, then I get a different error:

What was that error? We don't support conda so I'm not really interested in the conda case. DLL load errors are a common, self inflicted theme of using conda.

**Comment by rokm** [comment]
> > I also tied with pure python, then I get a different error:
> 
> What was that error? We don't support conda so I'm not really interested in the conda case. DLL load errors are a common, self inflicted theme of using conda.

> ```
> (.venv) (base) NICOLASs-MacBook-Pro:main dickr$ ./main
> Segmentation fault: 11
> ```

Although that looks to me as if both venv and conda base environment were active, which could be a problem in itself...

**Comment by dickreuter** [comment]
Seems to be an issue with tesserocr. Will try to resolve that and close this issue for now.
