### ISSUE TITLE
Usage of multiprocessing.ThreadPool occurs endless loop of restarts on macOS

### ISSUE THREAD

**Issue by MarshalX** [pyinstaller/pyinstaller#8233]
## Description of the issue

The packaged script that uses `ThreadPool` from `multiprocessing` returns unexpected results. Moreover, it could stuck in the endless loop that restarts the app over and over again on macOS. I prepared a test stand using GitHub Actions with a time limit to demonstrate this issue: _del_

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.3.0```
* Version of Python: 3.8-3.12
* Platform: macOS Intel, macOS Apple Silicon
* How you installed Python: pyenv
* Looks like it works fine on Ubuntu and Windows
* I tried the dev build of pyinstaller. Same 

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Code of `main.py`:

```python
from multiprocessing.pool import ThreadPool


def main():
    with ThreadPool(processes=1) as pool:
        for x in pool.imap(lambda v: v, [1, 2, 3]):
            print(x, end='')


if __name__ == '__main__':
    main()

```

Command to package:

```shell
pyinstaller --onedir --debug all --noupx main.py
```

Command to run:

```shell
./dist/main/main
```

### Stacktrace / full error message

I created a repository that verifies this issue on many platforms, Python versions, and pyinstaller versions using GHA. To see the full debug logs use this workflow: _del_

### Notes

- Works fine on macOS with Python 3.7 and stable pyinstaller (5.x)
- Works fine on Windows and Linux
- Same issue in onefile mode

**Comment by rokm** [comment]
To use `multiprocessing` in frozen application, you need to call `multiprocessing.freeze_support` before using any `multiprocessing` functionality.

See https://pyinstaller.org/en/latest/common-issues-and-pitfalls.html#multi-processing

**Comment by MarshalX** [comment]
@rokm lmao thank you xd idk how it worked in Python 3.7 and broken in 3.12. i thought some kind of hook calls it for me

**Comment by rokm** [comment]
> @rokm lmao thank you xd idk how it worked in Python 3.7 and broken in 3.12. i thought some kind of hook calls it for me

That's because the default start method on macOS changed from `fork` to `spawn` in python 3.8, as per https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods

**Comment by MarshalX** [comment]
@rokm don't you know btw why this can occur in onedir mode? 

> Generate report multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.

and it also calls main.py a few times with strange args. like `-B`

**Comment by rokm** [comment]
> @rokm don't you know btw why this can occur in onedir mode?
> 
> > Generate report multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
> 
> and it also calls main.py a few times with strange args. like `-B`

Read the docs that I linked earlier - they explain the strange args. You should probably try moving the `freeze_support` call to the very top of your entry-point script.

**Comment by MarshalX** [comment]
@rokm you are awesome! yeah, moving helped
