### ISSUE TITLE
Different handling of directory structure in pytinstaller 6.3?

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#8235]
The below used to work well in pyinstaller 5.11 but now it's no longer working with pyinstaller 6.3.

```
a = Analysis(['main.py'],
             pathex=['poker'],
             datas=[ ( 'gui/ui/*.ui', '.' ),( 'gui/ui/*.ui', 'gui/ui' ),( 'decisionmaker/*.json', 'decisionmaker' )],
```

I get this error in pyinstaller 6.3
`file: [Errno 2] No such file or directory: 'gui/ui/main_form.ui'`

Where can I find more information on how this has changed? It doesn't seem to be in the changelog. many thanks

**Comment by rokm** [comment]
Look under `Incompatible changes` for `6.0.0`: "All of onedir build’s contents except for the executable are now moved into a sub-directory ...".

Long story short, you should not be accessing resources using relative paths - anchor the to `__file__` instead: https://pyinstaller.org/en/stable/runtime-information.html#using-file (note that this applies to older PyInstaller versions as well, but there it would have caused issues only in certain build types).

**Comment by rokm** [comment]
And if you want the old onedir layout, you should set `contents_directory` to `'.'`: https://pyinstaller.org/en/stable/CHANGES.html#id5
