### ISSUE TITLE
 DLL load failed while importing QtCore

### ISSUE THREAD

**Issue by dickreuter** [pyinstaller/pyinstaller#8237]
File "poker\main.py", line 12, in <module>
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
[18196] Failed to execute script 'main' due to unhandled exception!

pyinstaller==6.3
PyQt6==6.5.2

The issue also occurs when I use PyQT 6.4.2.

**Comment by rokm** [comment]
Can we see the `Analysis-00.toc` from the `build` directory?

**Comment by dickreuter** [comment]
Uploaded it here:
https://www.deepermind-pokerbot.com/analysis.toc

**Comment by dickreuter** [comment]
Added it here:
http://www.deepermind-pokerbot.com/analysis.toc

**Comment by rokm** [comment]
Hmmm, for starters, this build seems to have collected both `PyQt5` and `PyQt6` - it might not be the cause of the problem (it would be on Linux or macOS, but not necessarily on Windows), but it is unnecessarily bloating up your build. I noticed you had both in your `requirements_win.txt` yesterday, but they are gone now. If you have both installed, and are also using `qtpy`, then you should explicitly exclude the unwanted one (because `qtpy`'s conditional imports will pull in all installed Qt bindings).

---

On the other hand, is this build from your CI pipeline? I see [a similar error in the build log](https://github.com/dickreuter/Poker/actions/runs/7533127220/job/20505066214#step:6:63), which probably prevents us from properly processing `PyQt6` dependencies:

```
 32658 WARNING: QtLibraryInfo(PyQt6): failed to obtain Qt library info: Child process call to _read_qt_library_info() failed with:
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\PyInstaller\isolated\_child.py", line 63, in run_next_command
    output = function(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\site-packages\PyInstaller\utils\hooks\qt\__init__.py", line 196, in _read_qt_library_info
    QtCore = importlib.import_module('.QtCore', package)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\hostedtoolcache\windows\Python\3.11.7\x64\Lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 676, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 573, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1233, in create_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
ImportError: DLL load failed while importing QtCore: The specified procedure could not be found.
```

My first guess would be that this is caused by pinning of `PyQt6`, while `PyQt6-Qt6` is unpinned (and thus you get incompatible Qt libs from  `PyQt6-Qt6` 6.6.1).

**Comment by rokm** [comment]
> My first guess would be that this is caused by pinning of `PyQt6`, while `PyQt6-Qt6` is unpinned (and thus you get incompatible Qt libs from `PyQt6-Qt6` 6.6.1).

https://github.com/dickreuter/Poker/actions/runs/7533127220/job/20505066214#step:5:161

**Comment by dickreuter** [comment]
Thanks for all the help. I've added a pin to PyQt6-Qt6, also removed PyQt5. Now the error is gone, but the application just ends without any error:

Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
d-----         1/16/2024  12:04 PM                gui
d-----         1/16/2024  12:04 PM                _internal
-a----         1/16/2024  12:03 PM       40206668 main.exe


PS C:\Users\dickr\OneDrive\dev\PythonProjects\Poker\poker\dist\main> main
PS C:\Users\dickr\OneDrive\dev\PythonProjects\Poker\poker\dist\main> ./main
PS C:\Users\dickr\OneDrive\dev\PythonProjects\Poker\poker\dist\main>

**Comment by rokm** [comment]
If you add print statements, can you pinpoint where it crashes (for example, on what import)?

**Comment by dickreuter** [comment]
The culprit is:
```
api = PyTessBaseAPI(path=tesserpath,
                    psm=PSM.SINGLE_LINE,
                    oem=OEM.LSTM_ONLY)
```
I verified that the path is correct and that the data is present.

it worked well with pyinstaller 5 but seems to have trouble with pyinstaller 6. I do understand that the application path has now moved to ..._internal, but I did accommodate for that change.

**Comment by rokm** [comment]
Can you reproduce it with a minimal example that performs just that call?
