### ISSUE TITLE
Unable to build executable file

### ISSUE THREAD

**Issue by nightzjp** [pyinstaller/pyinstaller#8241]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import numpy
import torch
# import clip
# git+https://github.com/xinyu1205/recognize-anything.git
from ram.models import ram
from ram import inference_ram as inference
from ram import get_transform


def main():
    print(numpy.random.random)
    print(torch.cuda.is_available())
    print(ram)
    print(inference)
    print(get_transform)
    print("main.function")


if __name__ == '__main__':
    print("main.start")
    main()
```

### Stacktrace / full error message

```
![image](https://github.com/pyinstaller/pyinstaller/assets/73635091/6985777f-d8ab-4f32-8ae4-d1f885a25102)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
You need to ensure that source .py files for `fairscale` (possibly also for `ram`) are collected - PyInstaller does not collect those by default.

Either edit the generated .spec file and add the following to the Analysis:
```
a = Analysis(
    ...
    module_collection_mode={
        'fairscale': 'pyz+py',
    }
)
```
and then rebuild using the .spec file (instead of .py file).

Or, create a custom hook for `fairscale` that sets `module_collection_mode` to `'pyz+py'`, as described [in documentation](https://pyinstaller.org/en/stable/hooks.html#hook-global-variables).
