### ISSUE TITLE
build django project fail,raise a Collecting Django migration scripts error

### ISSUE THREAD

**Issue by 496482665** [pyinstaller/pyinstaller#8244]
### i have a Directory Structure like this:
“”“
├── application
│   ├── __init__.py
│   ├── __pycache__
│   │   ├── __init__.cpython-39.pyc
│   │   ├── asgi.cpython-39.pyc
│   │   ├── dispatch.cpython-39.pyc
│   │   ├── routing.cpython-39.pyc
│   │   ├── settings.cpython-39.pyc
│   │   ├── urls.cpython-39.pyc
│   │   └── websocketConfig.cpython-39.pyc
│   ├── asgi.py
│   ├── celery.py
│   ├── dispatch.py
│   ├── routing.py
│   ├── settings.py
│   ├── urls.py
│   ├── websocketConfig.py
│   └── wsgi.py
├── dvadmin
│   ├── system
│   │   ├── __init__.py
│   │   ├── __pycache__
│   │   ├── admin.py
│   │   ├── apps.py
│   │   ├── fixtures
│   │   ├── management
│   │   ├── migrations
│   │   ├── models.py
│   │   ├── signals.py
│   │   ├── tests.py
│   │   ├── urls.py
│   │   ├── util
│   │   └── views
├── manage.py
├── requirements.txt
”“”

### and this is my installed_app:
INSTALLED_APPS = [
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django_comment_migrate",
    "rest_framework",
    "django_filters",
    'rest_framework_simplejwt.token_blacklist',
    "dvadmin.system",
]

when i run pyinstall -F,i have a error about :Collecting Django migration scripts,like this:
<img width="1160" alt="image" src="https://github.com/pyinstaller/pyinstaller/assets/41267824/c5ad58bb-1d16-4e9a-917a-74caf3957291">

<img width="698" alt="image" src="https://github.com/pyinstaller/pyinstaller/assets/41267824/df7b6d35-ee94-4b19-8787-35de13b4e954">
it seems like the django-hook can not solve the dvadmin.system module,how can i fix this problem?

**Comment by rokm** [comment]
As a quick work-around, you can try putting an empty `__init__.py` file into `dvadmin` directory. That should take care of that particular error.

**Comment by 496482665** [comment]
> As a quick work-around, you can try putting an empty `__init__.py` file into `dvadmin` directory. That should take care of that particular error.

thanks a lot!it works
