### ISSUE TITLE
Flask File Uploading and app enviroment

### ISSUE THREAD

**Issue by aadejare** [pyinstaller/pyinstaller#8248]
Creating a flask application, I have specific folders that the files should upload to. While running the application, it will upload the files, but once the application closes, the files go missing. This mechanism happens when running a Windows program. I looked into the [platformdirs](https://github.com/platformdirs/platformdirs) and other areas, but they do not address my question.

What method can I use to upload a file into a designated directory in the application and assure that it renders the specific way?

[Please see this link to see how Flask uploads files](https://flask.palletsprojects.com/en/2.3.x/patterns/fileuploads/)
I also leverage [FlaskWebGui](https://github.com/ClimenteA/flaskwebgui) to run the Flask program and then Pyinstaller via auto py to exe to create the program.

**Comment by rokm** [comment]
> but once the application closes, the files go missing.

Are you using `onefile` mode? Because in that case, the application's directory is temporary, and you should not be storing files into it if you want to make them persistent across the runs.
