### ISSUE TITLE
pyinstaller install failed

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#825]
**Original date**: 2013/11/15

I installed pyinstaller from archive as per instructions in documentation. I got the following error during verification of install.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

C:\Users\Raymond>pyinstaller --version
Traceback (most recent call last):
  File "C:\Python27-32\Scripts\pyinstaller-script.py", line 5, in <module>
    from pkg_resources import load_entry_point
  File "build\bdist.win32\egg\pkg_resources.py", line 2793, in <module>
  File "build\bdist.win32\egg\pkg_resources.py", line 673, in require
  File "build\bdist.win32\egg\pkg_resources.py", line 576, in resolve
pkg_resources.DistributionNotFound: distribute

C:\Users\Raymond>
```

I searched the website but didn't find any guidance. 

Note: I got an error when I first ran setup.py when it failed to import from setuptools. I installed setuptools and then ran setup.py again. Could this sequence of events have caused the failure? Is there  another package I have to install? Perhaps package dependencies should be added to the documentation.

**Comment by localperf** [comment]
Installing functools32 seemed to solve my problem (after also installing distribute and setuptools).
