### ISSUE TITLE
No mechanism of applying -O or -OO, disabling assert, and removing doc strings

### ISSUE THREAD

**Issue by ElliotGarbus** [pyinstaller/pyinstaller#8252]
## Description of the issue
There is no way to specify the python command line options -O or -OO that disables asserts and removes the doc strings.

### Context information (for bug reports)
In Pyinstaller version 6.3.0, There is no way to specify the python command line option.
The use of the PYTHONOPTIMIZE env variable has no effect.

The documentation:  https://pyinstaller.org/en/stable/spec-files.html#specifying-python-interpreter-options
Includes the statement: "'O' or 'optimize': increment the value of sys.flags.optimize. Equivalent to Python’s -O command-line option." 

Unfortunately, this is not equivalent the -O option, as asserts are not disabled. 

Pyinstaller Version: 6.3.0
Python Version: 3.12.1
OS: WIndows 11

**Comment by rokm** [comment]
https://pyinstaller.org/en/stable/spec-files.html#specifying-python-interpreter-options

**Comment by rokm** [comment]
Ah, sorry, missed the part about asserts. If you want to disable those, you need to byte-compile with optimization level 2 (i.e., optimization must be set during the build).

E.g., `PYTHONOPTIMIZE=2 pyinstaller  --clean --noconfirm program.py` or `python -OO -m PyInstaller ...`.

**Comment by ElliotGarbus** [comment]
@rokm 
Unfortunately, this is not equivalent the -O option, as asserts are not disabled.
```
exe = EXE(
    pyz,
    a.scripts,
    [('O', None, 'OPTION'), ('O', None, 'OPTION')],
   ...
```
Using the code above will not disable asserts or remove doc strings.

**Comment by ElliotGarbus** [comment]
@rokm Are you sure that will work?  I manually deleted the build and dist directories and could not get the desired behavior.

**Comment by ElliotGarbus** [comment]
On the users group I was told: "You used to be able to use python -OO -m PyInstaller your-code.py but pycparser (one of PyInstaller’s indirect Windows-only dependencies) doesn’t allow it now."

**Comment by rokm** [comment]
> On the users group I was told: "You used to be able to use python -OO -m PyInstaller your-code.py but pycparser (one of PyInstaller’s indirect Windows-only dependencies) doesn’t allow it now."

That's also true, but you did not specify the OS here...

**Comment by ElliotGarbus** [comment]
Good catch!  Added.  Given it is Windows 11, is there a solution?

**Comment by rokm** [comment]
Hmmm, actually, I don't think `pycparser` is our indirect dependency. So if you don't have code that depends on it, you might get away with just `python -OO -m PyInstaller ...`  - can you try? (And conversely, if you have code that depends on `pycparser`, then you probably can't use `-OO` with unfrozen code, either)

**Comment by ElliotGarbus** [comment]
I'm not using pycparser.  I'll try from the command line.

**Comment by ElliotGarbus** [comment]
```
python -m pyinstaller...
```
Result: No module named pyinstaller

**Comment by rokm** [comment]
Ah, it is of course a bit more complicated than that - the thing is, if you have `cffi` installed, that pulls in `pycparser`, and then `win32-ctypes` (which we use) uses that, and results in the error. If you don't have `cffi` installed, you can get away with `-OO`.

**Comment by rokm** [comment]
> ```
> python -m pyinstaller...
> ```
> 
> Result: No module named pyinstaller

Python module names are case-sensitive.

**Comment by ElliotGarbus** [comment]
Many thanks!  That worked!!! Yeah!  
It does suggest a gap in the docs.

**Comment by ElliotGarbus** [comment]
Problem solved!

```
python -OO  -m PyInstaller --clean -y  .\my-specfile.spec
```
Works!  Thanks again.

**Comment by rokm** [comment]
> Many thanks! That worked!!! Yeah! It does suggest a gap in the docs.

Yeah, that's the thing with the docs, they are always out-of-date...

But if we want to document `-OO` for assertion removal, we need to figure out if we can force `pywin32-ctypes` into `ctypes`-only mode...

**Comment by ElliotGarbus** [comment]
Thanks again.  I'll close this issue.

**Comment by bwoodsend** [comment]
Possibly a `sys.modules["cffi"] = None; import win32ctypes` would force the mode but I dread to think what else it would do.

**Comment by rokm** [comment]
> Possibly a `sys.modules["cffi"] = None; import win32ctypes` would force the mode but I dread to think what else it would do.

I would expect it to lead to failure to collect `cffi` with applications that actually use it. But perhaps if we removed the `sys.modules` entry after we import `win32ctypes` in our `compat` module? Or maybe we could ask pywin32-ctypes folks to add a switch (for example, an environment variable) that allows it to ignore `cffi`?

**Comment by rokm** [comment]
The alternative would be to force optimization in `compile()` calls in `get_code_object` and `compile_pymodule` in `PyInstaller.building.utils`, but that would also require bypass of code cache (otherwise you might end up with non-optimized code-object from the cache that modulegraph constructed), and would be very messy in general.

**Comment by ElliotGarbus** [comment]
DId I just get lucky?
Here is my pip list:
```
Package                   Version
------------------------- ----------
altgraph                  0.17.4
certifi                   2023.11.17
charset-normalizer        3.3.2
Cython                    3.0.7
distlib                   0.3.8
docutils                  0.20.1
filelock                  3.13.1
idna                      3.6
Kivy                      2.3.0
kivy-deps.angle           0.4.0
kivy-deps.glew            0.3.1
kivy-deps.gstreamer       0.3.3
kivy-deps.sdl2            0.7.0
Kivy-Garden               0.1.5
packaging                 23.2
pefile                    2023.2.7
pillow                    10.2.0
pip                       23.3.2
platformdirs              4.1.0
Pygments                  2.17.2
pyinstaller               6.3.0
pyinstaller-hooks-contrib 2023.12
pypiwin32                 223
pywin32                   306
pywin32-ctypes            0.2.2
requests                  2.31.0
setuptools                69.0.3
urllib3                   2.1.0
virtualenv                20.25.0

```

**Comment by rokm** [comment]
> DId I just get lucky?

Yes. If you do a `pip install cffi` (or install something that depends on `cffi`), it will stop working.

**Comment by ElliotGarbus** [comment]
Noted!  Thanks again!

**Comment by bwoodsend** [comment]
> I would expect it to lead to failure to collect cffi with applications that actually use it. But perhaps if we removed the sys.modules entry after we import win32ctypes in our compat module? Or maybe we could ask pywin32-ctypes folks to add a switch (for example, an environment variable) that allows it to ignore cffi?

Or possibly we could banish its usage into a `PyInstaller.isolated` subprocess. We don't use `win32api` that much (although probably still more than I'd want in subprocesses).

The environment variable switch sounds most appealing to me. I've interacted with the `win32-ctypes` author before and he was pretty accommodating back then so he might humour us. I'd expect it to make his testing easier too.

**Comment by Xoriun** [comment]
Would be possible to clarify up the documentation at [https://pyinstaller.org/en/stable/spec-files.html#specifying-python-interpreter-options](url) because there I can't find any hints as to that you need to run ```python -O -m PyInstaller ...``` instead of just ```pyinstaller ...```.

**Comment by rokm** [comment]
> Would be possible to clarify up the documentation at [https://pyinstaller.org/en/stable/spec-files.html#specifying-python-interpreter-options](url) because there I can't find any hints as to that you need to run `python -O -m PyInstaller ...` instead of just `pyinstaller ...`.

Yeah, we should probably add a note there. 

Maybe also raise an error (or at least display a warning) if we detect mismatch between optimization flag passed to PyInstaller and the actual `sys.flags.optimization` within the build process. 

(Ideally, we would translate the passed optimization flag and byte-compile everything with corresponding optimization level; which in turn would require us to ignore modulegraph's code cache, and always byte-compile all modules in local build directory).
