### ISSUE TITLE
The program packaged with pyinstaller cannot run, when encountering “subprocess.run(cmd, check=True)”.

### ISSUE THREAD

**Issue by jiaqizhang123-stack** [pyinstaller/pyinstaller#8254]
Hello, the code for reporting errors is 
def generate_ddp_file(trainer):
    """Generates a DDP file and returns its file name."""
    module, name = f'{trainer.__class__.__module__}.{trainer.__class__.__name__}'.rsplit('.', 1)

    content = f"""
# Ultralytics Multi-GPU training temp file (should be automatically deleted after use)
overrides = {vars(trainer.args)}
if __name__ == "__main__":
    from {module} import {name}
    from ultralytics.utils import DEFAULT_CFG_DICT

    cfg = DEFAULT_CFG_DICT.copy()
    cfg.update(save_dir='')   # handle the extra key 'save_dir'
    trainer = {name}(cfg=cfg, overrides=overrides)
    results = trainer.train()
"""
    (USER_CONFIG_DIR / 'DDP').mkdir(exist_ok=True)
    with tempfile.NamedTemporaryFile(prefix='_temp_',
                                     suffix=f'{id(trainer)}.py',
                                     mode='w+',
                                     encoding='utf-8',
                                     dir=USER_CONFIG_DIR / 'DDP',
                                     delete=False) as file:
        file.write(content)
    return file.name
def generate_ddp_command(world_size, trainer):
    """Generates and returns command for distributed training."""
    import __main__  # noqa local import to avoid https://github.com/Lightning-AI/lightning/issues/15218
    if not trainer.resume:
        shutil.rmtree(trainer.save_dir)  # remove the save_dir
    file = generate_ddp_file(trainer)
    dist_cmd = 'torch.distributed.run' if TORCH_1_9 else 'torch.distributed.launch'
    port = find_free_network_port()
    cmd = [sys.executable, '-m', dist_cmd, '--nproc_per_node', f'{world_size}', '--master_port', f'{port}', file]
    return cmd, file

cmd, file = generate_ddp_command(world_size, self)
subprocess.run(cmd, check=True)

When running packaged exe, the program will keep repeating itself. I know it's mainly caused by sys.executable. How can I solve this problem? Thank you for your help

**Comment by bwoodsend** [comment]
There is no Python interpreter in a frozen application so any package which invokes Python subprocesses via `sys.executable` is inherently unfreezable. If you're lucky, you can redirect the subprocess manually. e.g. At the top of your main script:
```python
import sys
if sys.argv[1:3] == ["-m", "torch.distributed.run"]:
    from torch.distributed.run import main
    sys.argv[1:] = sys.argv[3:]
    main()
    sys.exit()
```
If that doesn't work though then there's basically sod all PyInstaller can do about it. Torch is not designed for freezing (or even distributing, given its size and CUDA dependency).
