### ISSUE TITLE
no suitable image found libpython3.8.dylib

### ISSUE THREAD

**Issue by brusand** [pyinstaller/pyinstaller#8257]
## Description of the issue
build on monterey and when install on mavericks,i have this error at launch:
no suitable image found libpython3.8.dylib

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(paste here)```
* latest
* Version of Python: 
* 3.8.13
* Platform: 
* OS X
* How you installed Python: 
* pyenv and python-dev with brew
* Did you also try this on another platform? Does it work there?
no

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> build on monterey and when install on mavericks,i have this error at launch:
> no suitable image found libpython3.8.dylib

> pyenv and python-dev with brew

Homebrew environment is not backwards compatible - and so libraries collected from homebrew environment as part of PyInstaller build are not backwards compatible, either.
