### ISSUE TITLE
Ultralytics OpenVINO Model Is Not Working When EXE Is Made

### ISSUE THREAD

**Issue by osvpl** [pyinstaller/pyinstaller#8260]
I have made an EXE of my object detection program.
I am using Ultralytics YOLOv8 with OpenVINO model.
Everything is working fine when I am running the .py file.

But when I am making an EXE using pyinstaller, it shows that OpenVINO is not installed.

**Loading best_openvino_model for OpenVINO inference ...
requirements: Ultralytics requirement ['openvino>=2023.0'] not found, attempting AutoUpdate ...
'pip' is not recognized as an internal or external command,
operable program or batch file.
requirements: X Command 'pip install -- no-cache "openvino>=2023.0" ' returned non-zero exit status 1.**

Here's the screenshot of error
![image](https://github.com/pyinstaller/pyinstaller/assets/156005125/3329ce69-101f-4e70-be9b-e52a39b24f21)

I have tried all possible commands like below

pyinstaller --collect-data=ultralytics --collect-data=openvino --collect-submodules openvino --collect-binaries openvino --hidden-import openvino --hidden-import openvino-dev --hidden-import openvino-telemetry VPS.py

pyinstaller --collect-data=ultralytics --collect-data=openvino VPS.py

pyinstaller --collect-data=ultralytics --collect-data=openvino --collect-submodules openvino --collect-binaries openvino VPS.py

Please help

**Comment by rokm** [comment]
The presence/absence of the `openvino` is probably determined by querying its metadata, so you should ensure that it is collected - i.e., try adding [`--copy-metadata openvino`](https://pyinstaller.org/en/stable/usage.html#cmdoption-copy-metadata) to your PyInstaller command (in addition to `--collect-submodules openvino`).

**Comment by osvpl** [comment]
Thanks buddy

That worked.

But how do we determine that which arguments we should use?

Is there any way to find that?

**Comment by rokm** [comment]
> Thanks buddy
> 
> That worked.
> 
> But how do we determine that which arguments we should use?
> 
> Is there any way to find that?

As with any complex tool, it helps if you understand how the tool (= PyInstaller) works and what its limitations are. Then, you can investigate the line of code that raised an error, and see what needs to be done about it.
