### ISSUE TITLE
Adding Files To Root Directory Goes To _internal Directory

### ISSUE THREAD

**Issue by osvpl** [pyinstaller/pyinstaller#8261]
When I am trying to add any file in the root folder with **--add-data "config.ini;."** in one directory mode, the file goes inside the **_internal** directory.

How to keep it in the root folder, the folder where .exe is?

**Comment by bwoodsend** [comment]
You just copy it in there. That said, you should assume that users are going to install your application into a read only directory so putting a config file inside your application is a bad idea. Somewhere in the home directory is where it should go.
