### ISSUE TITLE
Calling some other Function other than main of my python script

### ISSUE THREAD

**Issue by jaideep746** [pyinstaller/pyinstaller#8263]
I have created a windows application exe of my python script using pyinstaller.The exe is working fine but its only executing statements or functions defined after if __name__ == "__main__" . But I do want to all other functions directly which are defined in the same script. As windows Exe supports getting the proc address of the function with the help of dll export , is there a way to get the proc address of a function from the windows exe which is converted using pyinstaller.

**Comment by rokm** [comment]
No; PyInstaller bootloader exe starts embedded python executable, and runs your byte-compiled script in it. So it is not turning your python code into a shared library (DLL), and therefore you cannot get a proc address of a python function from it.
