### ISSUE TITLE
ImportError: DLL load failed while importing pywintypes: The parameter is incorrect.

### ISSUE THREAD

**Issue by wasawatpeng** [pyinstaller/pyinstaller#8264]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```(6.3.0)```
* Version of Python: 3.12
* Platform: Windows 10 (English)
* How you installed Python: python.org/download

The exe file works well on my PC and others (already tested on PC without python installed).
But on some PC (Windows 10), The error occurs for no reason.

### Error message

```
C:\Work\MyProgram\>myprogram.exe
Traceback (most recent call last):
    File "PyInstaller\hooks\rthooks pyi_rth_win32comgenpy.py", line 46, in <module> 
    File "PyInstaller\hooks\rthooks¥pyi_rth_win32comgenpy.py", line 25, in _pyi_rthook 
    File "PyInstaller\loader\pyimod02_importers.py", line 385, in exec_module
    File "win32com_init_py", line 8, in <module>
    File "PyInstaller\loader¥pyimod02_importers.py", line 385, in exec_module 
    File "pythoncom.py", line 2, in <module>
    File "PyInstaller\loader¥pyimod02_importers.py", line 385, in exec_module
    File "pywintypes.py", line 126, in <module>
    File "pywintypes.py", line 116, in __import_pywin32_system_module__
ImportError: DLL load failed while importing pywintypes: The parameter is incorrect.
[15668] Failed to execute script "pyi_rth_win32comgenpy" due to unhandled exception!
```

I found some relate issue such as 
* [#6685](https://github.com/pyinstaller/pyinstaller/issues/6685)
* [pyinstaller ImportError: DLL load failed - only on some PC's](https://stackoverflow.com/questions/62433855/pyinstaller-importerror-dll-load-failed-only-on-some-pcs) (stackoverflow)

They said that install/reinstall MSVC will fix it.
So that, I tried to simulate the error on my PC by uninstall MSVC 2015-2019. But it still works properly.

**Comment by rokm** [comment]
What is the minimal example that triggers this error - can you reproduce it with a simple
```python
import win32com
print("Hello!")
```
program?

What version of Windows 10 is running on the problematic machine?

**Comment by wasawatpeng** [comment]
I will confirm you later about the minimal example to trigger error.
 
Then, The Windows 10 version of PC that error occurs is Windows 10 build 19044.3930.
That's not the same as my PC and others that is Windows 10 build 19045.3930 (The exe works fine).

**Comment by rokm** [comment]
Do you perhaps have another 19044 machine to test with? I have a VM with an ancient Win 10 1507 (build 10240); and if I build that `import win32com` example (with pywin32 306) on Win 10 22H2 (build 19045.3996), the program runs both on the build and test machine.

Also: I'm assuming that the OS is 64-bit, but are you building a 32-bit or 64-bit program?

**Comment by wasawatpeng** [comment]
Sorry for late reply, I do not know that the customer has another 19044 machine or not. Still in the process to contact with customer.

For the question of 32-bit or 64-bit. I have already checked and ensured that is 64-bit program.
