### ISSUE TITLE
App gets quarantined upon download / marked as damaged on macOS

### ISSUE THREAD

**Issue by Cliffback** [pyinstaller/pyinstaller#8268]
## Description of the issue

I'm trying to create a portable native macOS application for a python program, and it works fine locally for me, but after uploading it to releases in my repo and downloading again, the app will be flagged as damaged, and has to be moved to the bin. I know this is because it gets quarantined, and can be fixed with `xattr -d com.apple.quarantine /path/to/appname.app` but I'd rather avoid users having to do this.

I am used to apps only being flagged as from an unkown author, and can be opened the first time by right clicking and hitting open.

I understand that this probably is due to the contents of the app not following the official "guidelines" for how to structure a mac app, but I'm not sure. 

Is my only solution to sign the application as an Apple Developer, or is it a problem with how pyinstaller structures the app, and can be fixed? If so, how to fix.

My spec-file looks like this:

`# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['run.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='FlashGBX',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=False,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
    icon=['FlashGBX/res/icon.ico'],
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='FlashGBX',
)
info_plist = {
    'CFBundleName': 'FlashGBX',
    'CFBundleDisplayName': 'FlashGBX',
    'CFBundleGetInfoString': 'Reads and writes Game Boy and Game Boy Advance cartridge data.',
    'CFBundleShortVersionString': '3.36',
    'CFBundleIdentifier': 'com.lesserkuma.FlashGBX',
}
app = BUNDLE(
    coll,
    name='FlashGBX.app',
    icon='FlashGBX/res/icon.ico',
    bundle_identifier='com.lesserkuma.FlashGBX',
    info_plist=info_plist,
)`

My repo: (https://github.com/Cliffback/FlashGBX-macOS)
The compiled app can be downloaded from the Releases page.
The repo is just to create a native mac app from this repo: (https://github.com/lesserkuma/FlashGBX/)

Anyone has a clue to how to resolve this?

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.3.0```
* Version of Python: 3.11.7
* Platform:  macOS Sonoma 14.3
* How you installed Python: homebrew

**Comment by bwoodsend** [comment]
How are you archiving the application? It sounds like you're [not preserving symlinks](https://pyinstaller.org/en/latest/common-issues-and-pitfalls.html#requirements-imposed-by-symbolic-links-in-frozen-application).

**Comment by rokm** [comment]
The quarantine part is your problem to solve, and has nothing to do with PyInstaller. (I.e., the OS puts that quarantine attribute on app that has been downloaded, and is not signed).

**Comment by rokm** [comment]
> I understand that this probably is due to the contents of the app not following the official "guidelines" for how to structure a mac app, but I'm not sure.

FWIW, we are now structuring the .app bundles to conform to the recommended layout (well, unless you manage to clobber symlinks in the generated .app bundle with your distribution method).

**Comment by Cliffback** [comment]
> How are you archiving the application? It sounds like you're [not preserving symlinks](https://pyinstaller.org/en/latest/common-issues-and-pitfalls.html#requirements-imposed-by-symbolic-links-in-frozen-application).

I tried compressing with symlinks preserved just now, and upon uploading and downloading, the message at least changed from being "damaged" to not "apple not being able to check it for malware", so that is at least something, thank you. Still can't be opened without running xattr.

**Comment by Cliffback** [comment]
> > I understand that this probably is due to the contents of the app not following the official "guidelines" for how to structure a mac app, but I'm not sure.
> 
> FWIW, we are now structuring the .app bundles to conform to the recommended layout (well, unless you manage to clobber symlinks in the generated .app bundle with your distribution method).

Thanks for the clarification, that is really good to know. So as long as the packaging preserves symlinks, the message should theoretically go away when signed as a offical dev account.

**Comment by rokm** [comment]
I think quarantine issue comes specifically from downloading a zip archive and unpacking it. You might be able to avoid it with a DMG file as a distribution method (perhaps even without signing with official dev account).

**Comment by Cliffback** [comment]
> I think quarantine issue comes specifically from downloading a zip archive and unpacking it. You might be able to avoid it with a DMG file as a distribution method (perhaps even without signing with official dev account).

That was it! Using create-dmg did the job without signing it, thanks for the suggestion
