### ISSUE TITLE
Searching for wrong version of VC90.CRT assembly

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#827]
**Original date**: 2013/11/20
**Original reporter**: *tfcRobert AND gmail DOT  COOM *

My build of a PyQt app on my Win7 fails missing:

amd64_Microsoft.VC90.CRT_1fc8b3b9a1e18e3b_9.0.21022.8_none

The same app builds fine on my Vista machine with the most simple command line...
"pyinstaller myapp"

I can't seem to locate the version it's looking for online. Is there a way to point to the *9.0.30729 version that's in my winsxs folder?

There were other tickets on this site with similar problems but I couldn't see the solution.

Love the product..
Robert

**Comment by cxfksword** [comment]
I found the correct version Microsoft Visual C++ 2008 Redistributable Package, not with sp1.

http://www.microsoft.com/en-us/download/details.aspx?id=29
http://www.microsoft.com/en-us/download/details.aspx?id=15336

**Comment by codewarrior0** [comment]
> Is there a way to point to the *9.0.30729 version that's in my winsxs folder?

Yes, normally when you install the newer version, it also installs a "policy file" into the winsxs folder that will redirect requests for the older version to the newer one.

I'm can't tell from the description whether this is a build-time issue or a run-time one, but my guess is that it's build time. I think PyInstaller's assembly finding doesn't honor the policy file, and tries to find the older version of the CRT assembly when it gives this error.

I'll have to revisit the assembly and manifest handling code at some point.

**Comment by codewarrior0** [comment]
> The same app builds fine on my Vista machine

Windows 7 and later have the newer versions of the CRT and the policy file pre-installed.

**Comment by matysek** [comment]
Do we care much about xp/vista?

**Comment by codewarrior0** [comment]
Maybe. Different sources put the market share of XP just above or below that of all versions of OS X. One source (Kaspersky Labs) says XP is still widely used in East Asia, which is understandable as those areas have lots of netcafes who wouldn't be in any hurry to upgrade.

**Comment by codewarrior0** [comment]
I think the core issue (ignoring policy files) is something we need to address anyway, to be compatible with all assemblies.

**Comment by htgoebel** [comment]
I'm in favour of *not* supporting XP, as even the vendor stopped support. Security patches are not available any more. So we would encourage using a insecurity operation system.

**Comment by codewarrior0** [comment]
I don't think we do anything to *explicitly support* XP, and I haven't come across a need to do anything that would make it stop working on XP. 

Handling assemblies in the general case is something we should do anyway. It's the same thing as how we bundle Frameworks on OS X and edit the linkage info to reflect that the Framework is inside the app bundle instead of installed in the system.

**Comment by codewarrior0** [comment]
This is fixed. PyInstaller now follows policy redirects while searching for assemblies: If an executable requires version 21022 of the CRT90, but only version 30729 is installed, then version 30729 will be bundled with the executable (and all bundled manifests are updated to that version).
