### ISSUE TITLE
"Can't find a usable init.tcl in the following directories" error on Spyder mac Sonoma

### ISSUE THREAD

**Issue by mgad02** [pyinstaller/pyinstaller#8275]
Hi. I've used the standalone spyder app before and never had this issue. Not sure what changed besides updating my mac software. Worth noting is that when opening spyder using anaconda navigator, this doesn't seem to be an issue. I just needed to run the standalone spyder but am not sure what the problem is. I have tried uninstalling and reinstalling spyder with no luck.

**General info:**
Mac chip: Apple M2 Pro chip
Software: Sonoma 14.0
Spyder version: 5.5.0
Python version: 3.9.14
IPython version: 8.17.2

**Minimal code run that gives the error message:**
`import tkinter as tk
from tkinter import filedialog

root = tk.Tk()
root.withdraw()

files_path_list = filedialog.askopenfilenames()`

**Error message:**
`Traceback (most recent call last):

  File /Applications/Spyder.app/Contents/Resources/lib/python3.9/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Library/Mobile Documents/com~apple~CloudDocs/
    root = tk.Tk()

  File tkinter/__init__.pyc:2270 in __init__

TclError: Can't find a usable init.tcl in the following directories: 
    /usr/local/Cellar/tcl-tk/8.6.13_5/lib/tcl8.6 /Applications/Spyder.app/Contents/lib/tcl8.6 /Applications/Spyder.app/lib/tcl8.6 /Applications/Spyder.app/Contents/library /Applications/Spyder.app/library /Applications/Spyder.app/tcl8.6.13/library /Applications/tcl8.6.13/library

This probably means that Tcl wasn't installed properly.`

I tried googling the issue and know others have had this problem too but I'm not super savvy with coding and this kind of things so haven't been able to solve it yet so I would appreciate any help. Thanks.

**Comment by bwoodsend** [comment]
This has nothing to do with PyInstaller?

**Comment by mgad02** [comment]
Oh I'm sorry. I've barely used GitHub so accidentally posted the issue here. Thanks for pointing that out.
