### ISSUE TITLE
Pytest-xdist cannot run after being packaged with pyinstaller

### ISSUE THREAD

**Issue by fashionprivate** [pyinstaller/pyinstaller#8283]
## Pytest-xdist cannot run after being packaged with pyinstaller
This Python script can be run locally, but after being packaged with pyinstaller, it has been stuck in an endless loop. Is there a problem with packaging?

### Context information
* Python 3.11.6
* pyinstaller==6.3.0
* pytest==8.0.0
* pytest-xdist==3.5.0

My code:

test_case.py

```
import pytest
 
def test_example1():
    assert 1==1

def test_example2():
    assert 1 + 1 == 2

if __name__ == "__main__":
    pytest.main(["-n", "1"])
```

It was always running before.

I have tried using different versions of packages, but none of them worked.

**Comment by rokm** [comment]
Anything that spawns subprocesses using `sys.executable` will end up with endless spawn loop once frozen by PyInstaller, unless you explicitly identify the subprocess in your entry-point script (by matching `sys.argv`), and redirect the program flow into whatever module/function it is supposed to call.

The one exception is `multiprocessing` framework, for which we have run-time hook that does this program flow diversion, but even that requires you to call `multiprocessing.freeze_support` (see https://pyinstaller.org/en/latest/common-issues-and-pitfalls.html#multi-processing for details).

For anything else, you are on your own. See https://github.com/pyinstaller/pyinstaller/issues/8254#issuecomment-1905666853 for a similar question and example.

**Comment by rokm** [comment]
For the sake of completeness:
```python
import sys
import pytest

def test_example1():
    assert 1==1

def test_example2():
    assert 1 + 1 == 2

if __name__ == "__main__":
    # Redirect program flow in pytest-xdist worker process(es)
    if sys.argv[1:] == ["-u", "-c", "import sys;exec(eval(sys.stdin.readline()))"]:
        exec(eval(sys.stdin.readline()))
        sys.exit(0)

    # Main program flow
    pytest.main(["-n", "1"])
```

And the (onedir) spec file; in order for xdist to be discovered, its metadata needs to be collected (1). And due to indirect imports, submodules from `xdist` need to be collected as well (2). In addition, the source of `xdist.remote` is also required (3).

```python
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_submodules
from PyInstaller.utils.hooks import copy_metadata

datas = []
hiddenimports = []
datas += copy_metadata('pytest-xdist')  # (1) --copy-metadata pytest-xdist
hiddenimports += collect_submodules('xdist')  # (2) --collect-submodules xdist


a = Analysis(
    ['test_case.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    module_collection_mode={
        'xdist.remote': 'pyz+py',  # (3) ensure source is available for xdist.remote
    }
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='test_case',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='test_case',
)
```

**Comment by fashionprivate** [comment]
Ok, thanks. And where I should save the spec file above?

**Comment by rokm** [comment]
> Ok, thanks. And where I should save the spec file above?

You should edit (or completely replace) the .spec file that PyInstaller generated for you when you ran `pyinstaller ... test_case.py`; and then you should build using spec file instead of .py file: `pyinstaller --clean test_case.spec`.

**Comment by fashionprivate** [comment]
Thanks, it works
