### ISSUE TITLE
App icon not showing on frozen exe while using pyside

### ISSUE THREAD

**Issue by tmblog** [pyinstaller/pyinstaller#8293]
Hi I have a flask app which uses the pyside's QWebEngineView when I run it from my IDE the app icon works because I have I have set it like:

```
   main_window = QMainWindow()
   main_window.setWindowTitle("App Name")
    try:
        main_window.setWindowIcon(QIcon("icon.ico"))
    except Exception as e:
        print(f"Error setting icon: {e}")
```
But when I create the standalone the default python app is showing, here's what I use to create the app.

```
pyinstaller --add-data "templates;templates" --add-data "static;static" 
--add-data "data.db;." --add-data "settings.json;." --add-data "printed_ids.json;." 
--icon icon.ico --name App_Name app.py helpers.py
```
Am I missing something?

**Comment by rokm** [comment]
> ```
>         main_window.setWindowIcon(QIcon("icon.ico"))
> ```

> Am I missing something?

You are using relative path to load that icon, which assumes that the icon is in your current working directory. And with frozen applications, that's not the case. You should anchor the path to `__file__`, like described [in the docs](https://pyinstaller.org/en/stable/runtime-information.html#using-file).

**Comment by rokm** [comment]
And you also need to collect the icon in your frozen application with `--add-data "icon.ico;."` (the `--icon` argument only sets the executable-embedded icon, but you are trying to load `QIcon` from file).

**Comment by rokm** [comment]
> app.py helpers.py

And you probably have only one entry point script - `app.py`.

**Comment by tmblog** [comment]
Thank you for the prompt response, am I right in thinking that I only need the --icon icon.ico in the pyinstaller should be ok? I can safely remove the pyside's `setWindowIcon`

**Comment by tmblog** [comment]
> > app.py helpers.py
> 
> And you probably have only one entry point script - `app.py`.

Entry point is only one yes you're right, I olny put helpers.py so that pyinstaller can scan it for dependancies, do I not need that?

**Comment by bwoodsend** [comment]
No

**Comment by rokm** [comment]
> Thank you for the prompt response, am I right in thinking that I only need the --icon icon.ico in the pyinstaller should be ok?

If you want to load `QIcon()` from file, then you also need to collect the icon file as data file (--add-data "icon.ico;."), and load it using path that is anchored to `__file__`. `--icon icon.ico` embeds the icon in the executable itself (i.e., to show the icon when you view the .exe file in file browser); I'm not sure what Qt policy is for window title icon (it might take the executable's icon if you do not explicitly call `setWindowIcon`).

**Comment by rokm** [comment]
> > > app.py helpers.py
> > 
> > 
> > And you probably have only one entry point script - `app.py`.
> 
> Entry point is only one yes you're right, I olny put helpers.py so that pyinstaller can scan it for dependancies, do I not need that?

If you give PyInstaller two .py files like that, they are treated as two entry-point scripts, and are called one after the other. Which is probably not what you need nor want (although if `helpers.py` does nothing during its initialization, you will probably not even notice it).
