### ISSUE TITLE
Frozen PIL packaged by PyInstaller supports only a limited amount of save keys,.

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#830]
**Original date**: 2013/11/22
**Original reporter**: *LaurensBER*

The output of "print Image.SAVE.keys()" on my local Python installation is:

['XBM', 'PCX', 'SPIDER', 'HDF5', 'TIFF', 'WEBP', 'BUFR', 'EPS', 'PPM', 'MSP',
RIB', 'GIF', 'BMP', 'TGA', 'IM', 'JPEG', 'PDF', 'FITS', 'PALM', 'WMF', 'PNG']

When I package it as a single exe (--onefile) with PyInstaller I get the following output:

['TIFF', 'PPM', ''GIF', 'BMP', 'JPEG', 'PNG']

You can test this by building the following python program with PyInstaller:

from PIL import Image, ImageTk, ImageDraw, ImageFont
Image.init()
print Image.SAVE.keys()

I'm building from a .spec file and I include the following line to be sure that the PDF plugin is imported:

'hiddenimports=['PdfImagePlugin?'],"

I found the following (old) ticket that might or might not be related: 
http://www.pyinstaller.org/ticket/454
http://www.mail-archive.com/pyinstaller@googlegroups.com/msg01167.html

**Comment by matysek** [comment]
The PIL hooks were broken in develop branch so I fixed them.
