### ISSUE TITLE
Error loading Python DLL when running onedir binary via a windows symlink

### ISSUE THREAD

**Issue by neilcampbell** [pyinstaller/pyinstaller#8300]
## Description of the issue

Binary built in `onedir` mode cannot load the bundled Python interpreter dll, when run via a symlink on Windows.
This appears to be a similar issue to https://github.com/pyinstaller/pyinstaller/issues/4674, however effects Windows.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.4.0```
* Version of Python: `3.11`
* Platform: `Windows 11`
* How you installed Python: `python.org/downloads`
* Did you also try this on another platform? Does it work there? `Yes, It works on macOS`

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
See https://gist.github.com/neilcampbell/baf4da15be2cda0694e95eb2cda6265b for the repro steps

### Stacktrace / full error message
```
[10996] PyInstaller Bootloader 6.x
[10996] LOADER: executable is C:\src\c\os\pyinstaller-bug\test.exe
[10996] LOADER: _MEIPASS2 is not set
[10996] LOADER: archivename is C:\src\c\os\pyinstaller-bug\test.exe
[10996] LOADER: Cookie found at offset 0x5607E
[10996] LOADER: No need to extract files to run; setting extractionpath to homepath
[10996] LOADER: SetDllDirectory(C:\src\c\os\pyinstaller-bug\_internal)
[10996] LOADER: Already in the child - running user's code.
[10996] LOADER: Python library: C:\src\c\os\pyinstaller-bug\_internal\python311.dll
Error loading Python DLL 'C:\src\c\os\pyinstaller-bug\_internal\python311.dll'.
LoadLibrary: The specified module could not be found.
```

**Comment by rokm** [comment]
Yeah, symlinked executable is definitely not resolved to its original path on Windows at the moment, so that failure is not unexpected.

**Comment by aorumbayev** [comment]
Hey @rokm any recommended options to work around this problem? 

For extra context we are distributing this binary (using `onedir` mode) via winget to windows users and winget creates a symlinked executable by default. There are no options for pre/post install hooks in winget to work around this by adding an extra symlink to the dependencies folder. This is a non issue for us if we are to use onefile mode but we explicitly wanted to stick to onedir given that its significantly faster to boot and its a metric we don't want to compromise on given that we provide a cli tool in that binary.

**Comment by rokm** [comment]
> Hey @rokm any recommended options to work around this problem?

Unfortunately not. The Windows codepath in bootloader was not written with symlinks in mind.

**Comment by bwoodsend** [comment]
> winget creates a symlinked executable by default

That is pretty mean of them. Windows+symlinks have never been a good pair so a shim executable like what chocolately uses would be far more sensible.

**Comment by neilcampbell** [comment]
> winget creates a symlinked executable by default

That's how it works when using a [portable install type](https://github.com/microsoft/winget-cli/blob/master/doc/specs/%23182%20-%20Support%20for%20installation%20of%20portable%20standalone%20apps.md#install).

You can also install via msi and msix, which gives you more control, so that's what we might need to use here.
