### ISSUE TITLE
Including sqlite databases with absolute path from blueprint

### ISSUE THREAD

**Issue by tmblog** [pyinstaller/pyinstaller#8301]
Hi firstly, apologies if this has been answered somewhere but I couldn't find it.
I am having issues including a databasea in the build.
My folder structure is 
app.py
bp/database.py
pdb.db

inside bp/database.py
I have referenced the pdb.db like:
```
current_dir = os.path.dirname(os.path.abspath(__file__))
pdb_db_path = os.path.join(current_dir, '../pdb.db')
conn = sqlite3.connect(pdb_db_path)
```

then in pyinstaller command:
`pyinstaller --add-data "templates;templates" --add-data "static;static" --add-data "bp;bp" --add-data "data.db;." --add-data "pdb.db;." --clean --console app.py`

It probably includes it but my abslute path is probably wrong?

**Comment by rokm** [comment]
> It probably includes it

Surely you can verify that yourself by checking the contents of the frozen application? Is the `pdb.db` where you expect it to be, in the application's top-level directory (i.e., directly under the `_internal` directory)?

> but my abslute path is probably wrong?

And you can verify that by yourself by adding a
```python
print(pdb_db_path, os.path.isfile(pdb_db_path))
``` 
before that `sqlite3.connect` call.

PyInstaller by default does not create the `bp` directory if it contains only .py files; and then trying to access file via parent of a non-existing directory will not work on some OSes - you might need to do `pdb_db_path = os.path.normpath(os.path.join(current_dir, '../pdb.db'))` instead.  But I don't think that's a problem on Windows, and besides, you are explicitly collecting `bp`, so this should not be an issue.

**Comment by tmblog** [comment]
> Surely you can verify that yourself by checking the contents of the frozen application? Is the `pdb.db` where you expect it to be, in

Sorry for the noob question how do I do this?

**Comment by rokm** [comment]
> > Surely you can verify that yourself by checking the contents of the frozen application? Is the `pdb.db` where you expect it to be, in
> 
> Sorry for the noob question how do I do this?

The PyInstaller command you posted implies that you're using `onedir` builds - so you can open the application's directory (`dist/<name>/_internal`) in file browser, and see the contents.

**Comment by tmblog** [comment]
Great thank you! I can see it there. So must be the way I am referencing it.

**Comment by rokm** [comment]
> Great thank you! I can see it there. So must be the way I am referencing it.

Then try adding that print statement before `sqlite3.connect` to see what happens at run-time.

**Comment by tmblog** [comment]
> > Great thank you! I can see it there. So must be the way I am referencing it.
> 
> Then try adding that print statement before `sqlite3.connect` to see what happens at run-time.

```
        current_dir = os.path.dirname(os.path.abspath(__file__))
        pdb_db_path = os.path.join(current_dir, '../pdb.db')
        print(pdb_db_path, os.path.isfile(pdb_db_path))
```
gives me:

```
c:\Users\userx\Documents\dev\python\app-folder\bp\../p_db.db True
```
cheers

**Comment by rokm** [comment]
That's for unfrozen version, or frozen?

**Comment by tmblog** [comment]
It doesn't print anything from the frozen version.

**Comment by rokm** [comment]
> It doesn't print anything from the frozen version.

Does it terminate due to unhandled exception before that, then? Do you get any output to console at all (assuming you are running from command prompt instead of double-clicking on the executable)?

**Comment by tmblog** [comment]
No it doesn't crash. it says table not found in my logs. That's because it can't find the db file. Definitely to do with my referencing. Cos I include another db file that works but it's called from root. This db file is called from a blueprint directory.

**Comment by rokm** [comment]
Hmm, then there's not enough information for us to help you, unless you can provide a minimum example that reproduces the issue (so we can see what's actually going on).
