### ISSUE TITLE
Could not find QtWebEngineProcess

### ISSUE THREAD

**Issue by letkan** [pyinstaller/pyinstaller#8307]
So, I'm on Arch Linux, latest python, PyQt5 5.15.5, pyinstaller-git. I have this script which is a wrapper for a minimal web browser that I used to test pyinstaller; when launching the binary I get this error 'Could not find 'QtWebEngineProcess'. I've noticed that I'm not the only one having this problem, that this issue has been around for some time without a clear solution. Someone suggested putting QtWebEngineProcess at the root level and that indeed worked for me too but it's more of a cheat. Somehow the build process is not informing the binary of the correct path to QtWebEngineProcess.
Thanks for looking into it

**Comment by rokm** [comment]
Is that PyQt5 from Arch repository (i.e., system-installed) or from PyPI wheel? Our hooks are tailored to the latter, so you will likely have more luck if you set up a minimal virtual environment and install PyQt5 via `pip install` (FWIW, it should also be more portable in general, as it needs to cater to wider range of distributions).

**Comment by bwoodsend** [comment]
This one I'm guessing?
```console
> pacman -Fx '.*QtWebEngineProcess'
extra/qt5-webengine 5.15.15-2 (qt5)
    usr/lib/qt/libexec/QtWebEngineProcess
```
So not even installed inside the Python environment...

**Comment by rokm** [comment]
Yeah, collecting Qt stuff from distribution packages is a mess. I know for sure that it doesn't work on Fedora, either. It's a very low-priority thing as far as I'm concerned, because distribution packages tend to be of limited portability anyway (glibc version, custom path patches, etc.).

**Comment by rokm** [comment]
Hmm, but perhaps just forcing the target path for `QtWebEngineProcess` might do the trick.

On Fedora PyQt6, it is under `/lib64/qt6/libexec`, so it ends up collected under `_internal/PyQt6/Qt6/lib64/qt6/libexec` (whereas under PyPI-compatible layout, it should be under `_internal/PyQt6/Qt6/libexec`). It's likely the same with Arch PyQt5 variant, judging by the path.

**Comment by letkan** [comment]
> Is that PyQt5 from Arch repository (i.e., system-installed) or from PyPI wheel? Our hooks are tailored to the latter, so you will likely have more luck if you set up a minimal virtual environment and install PyQt5 via `pip install` (FWIW, it should also be more portable in general, as it needs to cater to wider range of distributions).

From repository. The fact that pyinstaller does find it and bundles it within the dist means that it's only a misconfiguration of the path; somehow the app looks for QtWebEngineProcess in ./ since that's how it eventually works.

**Comment by rokm** [comment]
> > Is that PyQt5 from Arch repository (i.e., system-installed) or from PyPI wheel? Our hooks are tailored to the latter, so you will likely have more luck if you set up a minimal virtual environment and install PyQt5 via `pip install` (FWIW, it should also be more portable in general, as it needs to cater to wider range of distributions).
> 
> From repository. The fact that pyinstaller does find it and bundles it within the dist means that it's only a misconfiguration of the path; somehow the app looks for QtWebEngineProcess in ./ since that's how it eventually works

Yeah, that's because we try to compute destination path as relative to Qt `PrefixPath` and that doesn't work out so well for distributions that place Qt's libexec directory under `/lib{64}`.

I'll see about fixing that part to force collection into the expected location. Since we try to enforce PyPI target layout anyway, that's probably the sane thing to do.

**Comment by letkan** [comment]
> Yeah, that's because we try to compute destination path as relative to Qt `PrefixPath` and that doesn't work out so well for distributions that place Qt's libexec directory under `/lib{64}`.
> 
> I'll see about fixing that part to force collection into the expected location. Since we try to enforce PyPI target layout anyway, that's probably the sane thing to do.

I agree that a fixed path would most likely do the trick. Thanks for considering this.

**Comment by bwoodsend** [comment]
FWIW, building on an up to date rolling distribution like Arch is generally a bad idea since all Arch packages will be built to expect very recent versions of glibc so if you give your application to someone using Ubuntu (which due to its long term support model is always at least 1 to 3 years out of date) you'll almost certainly get glibc symbol errors.

**Comment by letkan** [comment]
Luckily I only build stuff for myself to make my life easier :)

**Comment by rokm** [comment]
@letkan Can you check if https://github.com/rokm/pyinstaller/tree/linux-distro-qtwebengine fixes the problem on Arch? (It seems to do the trick on my Fedora system with Fedora-packaged Qt6 and PyQt6).

**Comment by letkan** [comment]
> @letkan Can you check if https://github.com/rokm/pyinstaller/tree/linux-distro-qtwebengine fixes the problem on Arch? (It seems to do the trick on my Fedora system with Fedora-packaged Qt6 and PyQt6).

Unfortunately it didn't work, same problem, now that I know where too look, I will experiment. Thanks

**Comment by rokm** [comment]
> > @letkan Can you check if https://github.com/rokm/pyinstaller/tree/linux-distro-qtwebengine fixes the problem on Arch? (It seems to do the trick on my Fedora system with Fedora-packaged Qt6 and PyQt6).
> 
> Unfortunately it didn't work, same problem, now that I know where too look, I will experiment. Thanks

Where does the `QtWebEngineProcess` end up being collected, then?

**Comment by letkan** [comment]
> Where does the `QtWebEngineProcess` end up being collected, then?

In /_internal/PyQt5/Qt5/lib/qt/libexec/QtWebEngineProcess as before

**Comment by rokm** [comment]
> > Where does the `QtWebEngineProcess` end up being collected, then?
> 
> In /_internal/PyQt5/Qt5/lib/qt/libexec/QtWebEngineProcess as before

Even if you do
```
pip uninstall pyinstaller
pip install https://github.com/rokm/pyinstaller/archive/refs/heads/linux-distro-qtwebengine.zip
```
?

**Comment by letkan** [comment]
I just noticed my mistake, wrong branch, sorry. Will get back :)

**Comment by letkan** [comment]
> pip install https://github.com/rokm/pyinstaller/archive/refs/heads/linux-distro-qtwebengine.zip

Splendid! It now works as expected, thanks for the fix and patience.
