### ISSUE TITLE
[Bug Report] Regarding the Specification of Icons

### ISSUE THREAD

**Issue by 1m188** [pyinstaller/pyinstaller#8312]
[Bug Report] Regarding the Specification of Icons

I am using pyinstaller 6.4, and when there is an underscore "_" in the generated name specified using the --name parameter, the designated icon does not work as expected. What I mean is that when the generated name does not contain an underscore, the specified icon appears normally in the file browser. However, when there is an underscore, the icon of the generated file appears as the default icon of pyinstaller.

pyinstaller 6.4
python 3.8 (installed by conda, so as pyinstaller, which from conda-forge channel)
Windows 11  23H2
I do not try this on another platform

**Comment by rokm** [comment]
Hmm, I can't seem to reproduce this. Can you provide a full example that triggers this issue (the icon, the PyInstaller command, the .spec file, etc.) so I can reproduce it?
