### ISSUE TITLE
win32ctypes.pywin32.pywintypes.error: (225, 'BeginUpdateResourceW', 'Operation did not complete successfully because the file contains a virus or potentially unwanted software')

### ISSUE THREAD

**Issue by LucasSom** [pyinstaller/pyinstaller#8320]
Hello!

I'm trying to create an .exe from a simple app but when I run `pyinstaller -w myApp.py` the operation is aborted with the error code `win32ctypes.pywin32.pywintypes.error: (225, 'BeginUpdateResourceW', 'Operation did not complete successfully because the file contains a virus or potentially unwanted software')`. I've tried it on Windows 10 and Windows 11 and with a simple "Hello world" program it still appears.

But without the `-w` flag (that is, only running `pyinstaller myApp.py`) the error does not occur, so, there is possibly an issue with the `-w` flag.

**Comment by bwoodsend** [comment]
No, it's just that most people who write malware using PyInstaller use `-w` mode so the dumb heuristics based antiviruses are more prone to misclassifying a windowed application as malware. Report the false positive to the antivirus. Talking to us about it is a waste of time.
