### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by aleonccc** [pyinstaller/pyinstaller#8321]
### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.4.0
* Version of Python: 
* Platform: Windows (es/ES)
* How you installed Python: python.org/downloads
* Did you also try this on another platform? No Does it work there?

* try the latest development version, using the following command:
```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
Inside the insert_update_matricula_classlife_util.py:
from util_interface import get_new_fields, copy_to_clipboard, from_items_to_fields

Inside the util_interface.py:
import json
import pyperclip

“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "Utils\insert_update_matricula_classlife_util.py", line 1, in <module>
ModuleNotFoundError: No module named 'pyperclip'
[6972] Failed to execute script 'insert_update_matricula_classlife_util' due to unhandled exception!

```
ModuleNotFoundError: No module named 'pyperclip'
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Usually when a direct import like that ends up missing, it means that it was not available in the python environment in which PyInstaller is installed. Do you happen to have multiple python environments with PyInstaller installed? If that's the case try running it as `python -m PyInstaller ...` instead of `pyinstaller ...` to avoid mix-ups.

**Comment by aleonccc** [comment]
Hi there,
Thanks, unfortunately it doesn't work.

[image: image.png]
[image: image.png]

Best regards.

**Comment by rokm** [comment]
In that case, if you try to build and run the following test program in your environment:
```python
# test_program.py
import pyperclip
print(pyperclip)
```
Does it work?

**Comment by aleonccc** [comment]
Hi, Rok!



Thanks for your support.

 

At the end, I reinstalled the Python ecosystem (interpreter and packages) and it works fine!

Best regards.

 

De: Rok Mandeljc ***@***.***> 
Enviado el: viernes, 23 de febrero de 2024 11:59
Para: pyinstaller/pyinstaller ***@***.***>
CC: aleonccc ***@***.***>; Author ***@***.***>
Asunto: Re: [pyinstaller/pyinstaller] ModuleNotFoundError (Issue #8321)

 

In that case, if you try to build and run the following test program in your environment:

# test_program.py
import pyperclip
print(pyperclip)

Does it work?
