### ISSUE TITLE
Certum.pl Nightmare - Remove Link

### ISSUE THREAD

**Issue by x011** [pyinstaller/pyinstaller#8324]
I urge you to remove the link promoting certum.pl for their affordable open source certificates. Engaging with them has been an incredibly frustrating experience. Despite having paid and submitted my documents over a month ago, their support has been utterly ineffective, failing to provide any coherent assistance. I discovered them through a link on [https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md), a decision I deeply regret. I am now compelled to involve the police and file a formal scam report to initiate a chargeback through my bank. It has been an absolute ordeal and a colossal waste of time. I strongly advise keeping a distance from this disreputable company.

here's the link snipped:

```
open source projects can get them [a fair bit cheaper](https://shop.certum.eu/open-source-code-signing-on-simplysign.html)
```

**Comment by bwoodsend** [comment]
Fair enough. There's a few things in there I've been meaning to edit anyway. I guess this is as good an excuse as any to get round to doing them...

**Comment by x011** [comment]
> Fair enough. There's a few things in there I've been meaning to edit anyway. I guess this is as good an excuse as any to get round to doing them...

Thank you so much, you're doing a favor to the opensource community.
