### ISSUE TITLE
tkinter menubar not calculated properly with none of the .geometry() methods when bundled into pyinstaller 

### ISSUE THREAD

**Issue by jessielw** [pyinstaller/pyinstaller#8326]
## Description of the issue
**I originally posted this over at cython github they told me to also post the issue here.** 
https://github.com/python/cpython/issues/115569

Issue:
tkinter menubar not calculated properly with none of the .geometry() methods when bundled into pyinstaller 

### Bug description:
Utilizing tkinter I save the geometry of the windows for users, so they can re-open them at the same size/position as they closed them. This works great besides windows with a menu bar. The menu bar isn't calculated properly when calling the `root.geometry()` method (or any other variant). So the window shrinks in height each time it's closed, which is undesired. 

I can only reproduce this if I compile my program into a binary with pyinstaller (onefile and onedir mode). 

As a work around I am now doing this, but this does seem like a bug to me. 
```python
    def save_config_information_root():
        # root exit parser
        root_exit_parser = ConfigParser()
        root_exit_parser.read(config_file)

        # save main gui window position/geometry
        if root.wm_state() == "normal":
            root.config(menu="")
            root.update_idletasks()
            if (
                root_exit_parser["save_window_locations"]["windowx"]
                != root.geometry()
            ):
                root_exit_parser.set(
                    "save_window_locations", "windowx", root.geometry()
                )
                with open(config_file, "w") as root_exit_config_file:
                    root_exit_parser.write(root_exit_config_file)
```
Simply setting `menu=""` removes the menu and there for doesn't take it's size into consideration. 

Hopefully I posted this in the right place. I know that it's only reproducible when compiled with pyinstaller, but since pyinstaller only bundles the code, I am wondering if it's a deeper issue here. 

Thanks!

### CPython versions tested on:

3.11.5

### Operating systems tested on:

Windows

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.3.0```
* Version of Python: 3.11.5
* Platform: Windows
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there?

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Can you provide a full minimal example that triggers the bug, not just your work around for it?

**Comment by jessielw** [comment]
Updating both of these issues as the same. The issue is because I used something like so. 

```python
root = Tk()

def another_window():
     root.update_idletasks() # issue is here <-
     another_window = Window(root) # this is a top level, in this other window we calculate size based on root's geometry, this window also gets withdrawn immediately as we want it hidden unless we need it
     
# a lot of other main window code
if bundled:
     another_window()
# do a bunch of stuff on main window

root.mainloop()
```
The issue was `root.update_idletasks()`. Removing this allows the geometry to be properly calculated bundled/not bundled. I will close this. 

Note for those that are interested instead of relying on `update_idletasks()` to get the proper geometry I just wrote a class that can handle it without causing the bug.

```python
class ErrorWindowLauncher:
    def __init__(self):
        self.root_geometry_check = collections.deque(maxlen=3)
        self._ensure_stable_geometry()

    def _ensure_stable_geometry(self):
        geometry_width = root.winfo_width()
        self.root_geometry_check.append(geometry_width)

        if len(self.root_geometry_check) == 3 and all(
            width == self.root_geometry_check[0] for width in self.root_geometry_check
        ):
            # If the width has stabilized and remains the same for the last 3 observations
            if geometry_width > 100:
                self._launch_hidden_error_window()
        else:
            root.after(50, self._ensure_stable_geometry)

    @staticmethod
    def _launch_hidden_error_window():
        error_window = ErrorWindow(root)
        sys.stderr = StderrRedirector(error_window)
```
