### ISSUE TITLE
OSX - hooks for pyobjc

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#833]
**Original date**: 2013/12/09
**Original reporter**: _romixlev AND web DOT de_

[pyobjc](https://pypi.python.org/pypi/pyobjc/) provides a possibility to write Cocoa GUI applications on Mac OS X in pure Python. So, it is very convenient to use pyobjc in many cases as it saves a lot of time.

But the problem is that pyinstaller cannot properly package applications using pyobjc. It produces an executable, but when you start it, it immediately crashes with the following exception:

```
NotImplementedError: Can't perform this operation for unregistered loader type
```

An example application on Mac OS X that demonstrates a problem can be as simple as this:

```
from AppKit import *
print NSPasteboard.generalPasteboard().types()
```

It is interesting to note that py2app has now problems with pyobjc.

Is there any hope that pyobjc would be supported by pyinstaller?

**Comment by matysek** [comment]
> Is there any hope that pyobjc would be supported by pyinstaller?

It's more open for user contribution.

**Comment by JokerQyou** [comment]
Interesting to know that this was an issue with v2.1, because back to early 2015 I did not have this problem with PyInstaller 2.1, everything was working perfectly with OS X 10.9 and 10.10. After a system upgrade (OS X 10.11), however, thing started to fall apart: pyobjc and Foundation lib are broken in my virtualenv; after I've managed to fix it, this problem suddenly jump out from nowhere. And FYI, OS X 10.11.1 with Python 2.7.10 in virtualenv and PyInstaller 3.1.

**Comment by JokerQyou** [comment]
Inspired by [this answer](http://stackoverflow.com/a/27053668), I eliminated the use of `Foundation` library, and used `pyobjc` instead: `SomeNSClass = objc. lookUpClass('SomeNSClass')` and it works well, this issue does not happen now.

**Comment by htgoebel** [comment]
If somebody wants to implement this, feel free to provide a pull-request

**Comment by BoboTiG** [comment]
FTR, I am using `pyobjc` with PyInstaller 3.3.1 and it worked so far. I just try with the `develop` branch and all is working fine.

As example, the code given in the description returns:
```python
(
    "public.html",
    "Apple HTML pasteboard type",
    "public.utf8-plain-text",
    NSStringPboardType
)
```

Also, I am using Foundation and other frameworks provided by `pyobjc` without any error.
I think you can close this issue
