### ISSUE TITLE
Minimal runtive pack

### ISSUE THREAD

**Issue by Yrij-Zhavoronkov** [pyinstaller/pyinstaller#8354]
Add the option "do not compile to exe", to only compile to *.pyc and prepare a minimal environment. 
The exe assembly in dir mode is not needed for further assembly of bamboo, but spoils the assembly with errors 
`OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software.`

**Comment by bwoodsend** [comment]
PyInstaller is not a way to create minimal environments. If this is what you want then you've got completely the wrong tool.

**Comment by Yrij-Zhavoronkov** [comment]
Nevertheless, pyinstaller collects the files needed for the utility very well, which gives a small volume of the distribution. It would be a good utility if it were possible not to generate.exe at the end, and assemble a folder ready to run from it, for example: 
`py main.pyc`
