### ISSUE TITLE
pyinstaller pack cudatoolkit cudnn

### ISSUE THREAD

**Issue by KnSun99** [pyinstaller/pyinstaller#8355]
Hi,
Use the pyinstaller tool to package.exe
Can cudatoolkit and cudnn in anaconda environment be packaged into the installation package?

![image](https://github.com/pyinstaller/pyinstaller/assets/123467428/d61857cc-d0ed-4c3f-a6c9-e6c7153f041d)

**Comment by rokm** [comment]
It likely won't be automatically packed, because most of CUDA DLLs are loaded dynamically, so they slip past PyInstaller's binary dependency analysis.

So you'll likely have to use `PyInstaller.utils.hooks.conda.collect_dynamic_libs` in .spec file.

**Comment by KnSun99** [comment]
Thanks for your reply!
I'll try.
