### ISSUE TITLE
optimize option in .spec file doesn't work

### ISSUE THREAD

**Issue by Xoriun** [pyinstaller/pyinstaller#8357]
I want the python interpreter in my exported .exe file to be called with the ```-O``` option.
MWE for testing:
```
if __debug__:
    print('debug')
else:
    print('no debug')
```
When just running with python, this works as intended (normal execution print ```debug```, with the ```-O``` flag it prints ```no debug```).

So I created a ```.spec``` file with ```pyi-makespec --console --onefile p2e.py``` and then added ```('O', None, 'OPTION')``` in the empty list in the EXE call in the ```.spec``` file:
```
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['p2e.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [('O', None, 'OPTION')],
    name='p2e',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

```
Then I ran ```pyinstaller --noconfirm --clean p2e.spec```. Neither command threw an error and the resulting executable runs as well.

However, no matter what I change in the ```.spec``` file, it always prints ```debug```.
For the options, I tried ```[('O', None, 'OPTION'), ('O', None, 'OPTION')]```, ```[('O', None, 'OPTION')]```, ```[('optimize', None, 'OPTION'), ('optimize', None, 'OPTION')]``` and ```[('optimize', None, 'OPTION')]```, all with the same result.

I also know that these changes get recognized, since when I drop the ```-clean``` option, each time I change the ```.spec``` file, pyinstaller says that something changed.

I also did a new install through pip with ```pip uninstall pyinstaller``` and ```pip install pyinstaller``` (now on newest versions 6.5.0).
I'm on python 3.11.6 and Windows 10 and don't have other platforms available for testing.

Is there something I am missing or I overlooked?

**Comment by bwoodsend** [comment]
Yeah, that's expected. `-O` is a compile time option to the Python interpreter but your PyInstaller application is not compiling anything at runtime. See #8252.

**Comment by Xoriun** [comment]
thx, that solved it for me
