### ISSUE TITLE
probleme  pyinstaller NSAppleScript

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#836]
**Original date**: 2013/12/17
**Original reporter**: *amar DOT oussalah AND me DOT  COOM *

my_ script:
    from applescript import *
    AppleScript('say "Time out Time out Time out"').run()

And 
pyinstaller -F -w my_script.py
......
in execution i have:
Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "build/bdist.macosx-10.9-x86_64/egg/applescript/__init__.py", line 5, in <module>
ImportError: cannot import name NSAppleScript
logout

**Comment by matysek** [comment]
applescript is outdated and fails with some other errors so it is hard to reproduce this error.
