### ISSUE TITLE
Using pyinstaller to package the flaskockeio project, the module failed to receive instructions

### ISSUE THREAD

**Issue by YL193** [pyinstaller/pyinstaller#8365]
I created a module and introduced socketio from the main program. It runs normally in the development environment, but after packaging, the module cannot respond to requests

```python
from app import socketio
import math

@socketio.on('MExe')
def gcmexe(data):
   print(data)
``` 

.spec file
``` 
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['app.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
      'engineio.async_drivers.threading',
      'model.model1'
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='app',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

**Comment by rokm** [comment]
Do you see any error messages in the console?

Shouldn't you be collecting the resources for you app (e.g., the `templates` directory)?

FWIW, I can freeze the official Flask-SocketIO example/test (https://github.com/miguelgrinberg/Flask-SocketIO/tree/main/example), and it works as expected (after collecting submodules from `engineio` and resources from `templates` directory).

**Comment by YL193** [comment]
Thank you. I have updated my program based on this template and the issue has been resolved
