### ISSUE TITLE
Data persistence between relaunches

### ISSUE THREAD

**Issue by tmblog** [pyinstaller/pyinstaller#8369]
Hi I am having a peculiar issue where the data doesn't persist between app relaunches, e.g. when I load the exe it all loads as expected. I have data saved on sqlite databases and some json files.

While the app is running if I save data it persists, but when I close the app and relaunch it, it reverts back to the original state e.g. as it was when compiled.

I am using this to build it:

```
pyinstaller -F --add-data "templates;templates" --add-data "print-files;print-files" 
--add-data "p-print-files;p-print-files" --add-data "static;static" --add-data "data.db;." 
--add-data "p_database.db;." --add-data "printer_settings.json;." --add-data "printed_order_ids.json;." 
--add-data "pose;pose" --icon icon.ico --clean --console --name Alps app.py
```

I have checked the file permissions for all of the files and dbs in question and they are readable and writable.

The files are indeed referenced with absolute paths like:

`json_file_path = path.abspath(path.join(path.dirname(__file__), 'printed_order_ids.json'))`

i am stuck for what it could be any pointers and help highly appreciated.

**Comment by rokm** [comment]
You are using onefile mode, and are storing your files into application's directory. Which, in onefile mode, is ephemeral (i.e., created on each run and cleaned up after application exits). So clearly there cannot be any persistence, by design.

If you need persistent storage, use a location outside of the application directory; for example, using something like [`appdirs`](https://pypi.org/project/appdirs/).

**Comment by tmblog** [comment]
Thank you for the response, so I can just use it like:
```
data_dir = user_data_dir("AppName", "Author")
settings_path = os.path.join(data_dir, 'printer_settings.json')
```
Is this right?
Thank you

**Comment by rokm** [comment]
> Thank you for the response, so I can just use it like:
> 
> ```
> data_dir = user_data_dir("AppName", "Author")
> settings_path = os.path.join(data_dir, 'printer_settings.json')
> ```
> 
> Is this right? Thank you

That looks about right, yes.
