### ISSUE TITLE
-p not work for --collect-submodules

### ISSUE THREAD

**Issue by pkuwwt** [pyinstaller/pyinstaller#8374]
## Description of the issue

the search path specified `-p`  is used by `--hidden-import` but not `--collect-submodules`

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.5.0```
* Version of Python:3.10.13
* Platform: OS X
* How you installed Python: macport

### A minimal example program which shows the error

`main.py`
```python
import importlib
test = importlib.import_module('test_module.test')
test.hello()
```

`test_module/test.py`
```python
def hello():
    print('hello')
```

`test_module/__init__.py`
```python
```

```bash
# test_module is not found
pyinstaller --log-level TRACE -y  -p `pwd` --collect-submodules test_module main.py 2>&1 | grep 'not a package'
```
The result is
```
307 DEBUG: collect_submodules - test_module is not a package
```

```bash
# test_module is found
PYTHONPATH=`pwd` pyinstaller --log-level TRACE -y  -p `pwd` --collect-submodules test_module main.py 2>&1 | grep 'not a package'
```

**Comment by bwoodsend** [comment]
Yeah, we know. See #6294.
