### ISSUE TITLE
pycountry returns None on Windows in 6.5.0

### ISSUE THREAD

**Issue by davesc63** [pyinstaller/pyinstaller#8390]
## Description of the issue
Pyinstaller does not return any values on Windows.
Same as this issue: https://github.com/pyinstaller/pyinstaller/pull/8306

Python flask app
Uses pycountry to determine the user locale.
Works when frozen on MacOS
Does not work on Windows

Have built a clean venv to try again - no luck
Used a GitHub running - same result
Built new windows locally - same result

### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.5.0
* Version of Python: 3.11
* Platform: Windows
* How you installed Python: setup-python@v5 github action
* Did you also try this on another platform? Does it work there? Works on MacOS

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

Tried this as well - No luck

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
# Get the user's preferred locale
        user_locale, _ = locale.getlocale()
        # Extract the country code from the locale
        country_code = user_locale.split('_')[-1]
        # Use pycountry to get the country name
        country = pycountry.countries.get(alpha_2=country_code)
        country_name = country.name if country else None
        country_flag = country.flag if country else None
        logger.info(f"Country: {country_name} {country_flag}")
```

### Stacktrace / full error message

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
Does that code work on your Windows system when you run it unfrozen? What does `locale.getlocale()` return (both in unfrozen and in frozen case)?

Because on my system, `locale.getlocale()` returns `('English_Slovenia', '1252')`, and since the first part is not a two-letter language code, the `pycountry` lookup via `alpha_2` fails. The same happens both in unfrozen python script and frozen python application. See https://github.com/python/cpython/issues/82986 for more examples of `locale.getlocale()` not returning RFC-1766 language tags.

**Comment by davesc63** [comment]
You are right, it is locale that has changed!
