### ISSUE TITLE
PyInstaller with cfgrib

### ISSUE THREAD

**Issue by happymvd** [pyinstaller/pyinstaller#8393]
* Platform: 
* How you installed Python: < python.org/downloads>
* Did you also try this on another platform? Does it work there?
No I only have access to a Windows computer

### A minimal example program which shows the error

```
import xarray as xr
import cfgrib
import datetime as dt
import os
import sys
print('this is working')
```

When I try and run the exe I get the following error message
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Dell\AppData\Local\Temp\_MEI32242\gribapi\grib_api.h'
[1692] Failed to execute script 'Testing' due to unhandled exception!

```

**Comment by rokm** [comment]
>  FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\Dell\AppData\Local\Temp_MEI32242\gribapi\grib_api.h'

If you need non-python files collected from a package, use [`--collect-data`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-data). In this case, add `--collect-data gribapi` to your PyInstaller command.

**Comment by happymvd** [comment]
Thank you that worked well
