### ISSUE TITLE
Some pyd files in the root directory of the packaged program deleting without affect running

### ISSUE THREAD

**Issue by znsoooo** [pyinstaller/pyinstaller#8412]
**Is your feature request related to a problem? Please describe.**

There are several pyd files in the root directory of the program packaged by pyinstaller, and deleting them will not affect the normal operation, why is this?

I found that after the pyinstaller `--onedir` mode packaging, the deletion of these files did not affect the program running:

```
_bz2.pyd
_hashlib.pyd
_lzma.pyd
_socket.pyd
_ssl.pyd
pyexpat.pyd
select.pyd
unicodedata.pyd
```

I've searched for what these files do, and I'm wondering why they're still being packed with pyinstaller since they're not being used in the program.

Or it is actually used, but the branch I'm running doesn't use this part of the functionality?

In addition to these files, are all OTHER files necessary? Because if I use 64-bit, or other versions of Python, and packaged by pyinstaller, the file structure will be different, and delete some files will not affect the running too.

In addition, pyinstaller's `--onefile` packaging mode is actually a compressed package, and this part of the file will also be added. So this problem still existing, and causes the file size increasing.

**Describe the solution you'd like**

Don't include unnecessary pyd/dll files in packaged folder.

**Describe alternatives you've considered**

An optional parameter for minimal packaging.

In particular, I can delete the files directly in the ONEDIR mode, which there is not a similar remedy in ONEFILE mode. So it is important.

**Additional context**

![image](https://github.com/pyinstaller/pyinstaller/assets/34830785/8d1f8d49-91ff-43e2-9e03-de8bdd7f7000)

**Comment by bwoodsend** [comment]
You're using a long unsupported Python+PyInstaller version and some of those libraries have already been cleared out.

If you look inside `build/*/xref-*.html`, that'll tell you which modules imports those modules (possibly inside a conditional or function if they're not being loaded on startup). You can then `--exclude-module` them once you're convinced that the code that uses them isn't needed.

**Comment by znsoooo** [comment]
@bwoodsend Thank you for your reply.

I tested on the latest Python-3.12-amd64+PyInstaller-6.6.0, and the problem still exist.

Test code:

```python
# test.py

import os
import sys

print('\nEXE:\n  ' + sys.executable)
print('\nWORK:\n  ' + os.getcwd())
print('\nPATH:\n  ' + '\n  '.join(sys.path))
print('\nFILE:\n  ' + __file__)
print('\nARGS:\n  ' + '\n  '.join(sys.argv))

input('\npause: ')
```

Packaging command:

```bash
py -3.12 -m PyInstaller -y --noupx test.py
```

Running result, the problem still exist (ssl and pyexpat are removed, and decimal is added):

![image](https://github.com/pyinstaller/pyinstaller/assets/34830785/738e7bb4-c5d4-4e70-8000-6918efdc47cc)

By the way, the `--exclude-module` parameter you mentioned is available.

But what I am wondering is why the DEFALUT dependency analysis will including these unused modules? Can this be improved?

**Comment by rokm** [comment]
> But what I am wondering is why the DEFALUT dependency analysis will including these unused modules? Can this be improved?

Because they are (conditionally) imported by other parts of standard library, and since we cannot know if they will be required at run-time or not, we need to collect them. 

For example, `_bz2.pyd` extension is imported by `bz2` module (which you don't see because it is .py module and collected in PYZ archive), which in turn is imported from `encodings.bz2_codec`, `shutil`, `tarfile`, and `zipfile`. So if nothing else, this gets pulled in by `encodings.bz2_codec`, which is imported by `encodings` (which in turn is needed to initialize the interpreter). Which, as Brénainn told you, you can see for yourself in the `build/<name>/xref-<name>.html` file.

Many of those imports are conditional, but only *you* can know whether you can remove (or exclude) them or not *for your specific application*.

**Comment by znsoooo** [comment]
@rokm Thanks, I understand.

**Comment by znsoooo** [comment]
@rokm I have another question.

When I use Python>=3.7 and 64-bits, I find that the packager will include these DLLs, but removing them will not affect program running:

![image](https://github.com/pyinstaller/pyinstaller/assets/34830785/84cae8eb-a71e-45a5-b612-d7ab7f4d6074)


The "libcrypto-1_1.dll" file seems to be used for SSL, so I didn't use it actually.

But I didn't found them in "xref-\<name\>.html" report, and can't exclude them by "--exclude-module" parameter.

Do you have any suggestions?

**Comment by rokm** [comment]
If you want to exclude data files and shared libraries (i.e., files that are not python extensions), you will need to filter `Analysis.datas` and `Analysis.binaries` lists in the spec file, after `Analysis` is instantiated and before those lists are passed to `EXE`, `COLLECT`, etc. This means that you will need to build using .spec file (i.e., run PyInstaller against modified .spec file instead of .py file).

**Comment by znsoooo** [comment]
@rokm Do you mean like this...?

```python
# test.spec

...

a = Analysis(
    ['test.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=['unicodedata'],
    noarchive=False,
    optimize=0,
)

# User defined filter begin ->

for bin in a.binaries.copy():
    if bin[0].startswith('api-ms-') or bin[0] == 'libcrypto-1_1.dll':
        a.binaries.remove(bin)

# <- User defined filter end

pyz = PYZ(a.pure)

...
```

By the way, did these DLLs' dependency analysis are not visible in "xref.html" file (or some where else)? Did I understanding right?

**Comment by bwoodsend** [comment]
Yes, although you're risking throwing away portability by removing those files. It may be that your application doesn't use them but it's more likely that you have other copies of those DLLs installed that came with other programs (including your original Python environment).

> By the way, did these DLLs' dependency analysis are not visible in "xref.html" file (or some where else)? Did I understanding right?

That file is for modules – not DLLs.

**Comment by znsoooo** [comment]
@bwoodsend Thanks reminder, I'll do the test carefully.

**Comment by znsoooo** [comment]
@bwoodsend Thanks reminder, I'll do the test carefully.
