### ISSUE TITLE
mac [816] Error loading Python lib 

### ISSUE THREAD

**Issue by brusand** [pyinstaller/pyinstaller#8416]
## Description of the issue
when i install the dmg on an other mac, i have this issue
[816] Error loading Python lib '/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib': dlopen: dlopen(/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib, 10): no suitable image found.  Did find:
	/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib: cannot load 'libpython3.8.dylib' (load command 0x80000034 is unknown)
	/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib: cannot load 'libpython3.8.dylib' (load command 0x80000034 is unknown)
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.3.0```
* Version of Python:  3.8.13
* Platform:  OS X
* How you installed Python:  pyenv
* Did you also try this on another platform? Does it work there?

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
(paste text here)
“Minimal“ means: remove everything from your code which is not relevant for this bug,
esp. don't use external programs, remote requests, etc.
A very good example is https://gist.github.com/ronen/024cdae9ff2d50488438. This one helped
us reproducing and fixing a quite complex problem within approx 1 hour.
```

### Stacktrace / full error message
[816] Error loading Python lib '/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib': dlopen: dlopen(/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib, 10): no suitable image found.  Did find:
	/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib: cannot load 'libpython3.8.dylib' (load command 0x80000034 is unknown)
	/Applications/gyp6band.app/Contents/Frameworks/libpython3.8.dylib: cannot load 'libpython3.8.dylib' (load command 0x80000034 is unknown)

```
(paste text here)
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
> when i install the dmg on an other mac, i have this issue

The version of macOS that you have on your older Mac does not recognize the `LC_BUILD_VERSION` load command (0x80000034) that is used by python shared library, which must have been built for a recent version of macOS (the old load command was `LC_VERSION_MIN_MACOSX`).

If you want the program to run on older Macs, you will need to ensure that you are using binaries that were compiled for older versions of macOS. The easiest way is to build on an older Mac.

That said, `LC_BUILD_VERSION` seems to have become the default in 2018 with macOS 10.14, and as per README, we do not officially support anything older than 10.15, mostly due to `codesign` bugs on old macOS versions.
