### ISSUE TITLE
When I try to freeze a Python script with the 'tables'/'PyTables' library, the resulted program will not work

### ISSUE THREAD

**Issue by qoolcezar** [pyinstaller/pyinstaller#8419]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.6.0```
* Version of Python: ```3.11.8```
* Platform: Windows-10-10.0.19045-SP0 x64
* How you installed Python: during conda environment creation with ```conda create --name test_env python=3.11```
* Did you also try this on another platform? Does it work there? Yes, I tried on another Windows 10 x64 platform, same behavior.
* Pandas version: ```2.2.2```
* PyTables version: ```3.9.2```
* conda version: ```24.3.0```

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
Tried, same behavior. 

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

Done!

### A minimal example program which shows the error

Note: initial steps assuming conda is installed on the machine:
1) ```conda create --name test_env python=3.11``` and ```conda activate test_env```
2) ```pip install pyinstaller```
3) ```pip install pandas```
4) ```pip install tables```

```
import pandas as pd
print("Pandas is installed at:", pd.__file__)
print("Pandas version:", pd.__version__)

import tables
print("PyTables version:", tables.__version__)
print("PyTables is installed at:", tables.__file__)


df = pd.DataFrame({'A': range(3)})
df.to_hdf('test.h5', key='data')
```
My final objective is to save multiple pandas dataframes with the to_hdf method.

### Frozen program error

```
Traceback (most recent call last):
  File "test_script.py", line 6, in <module>
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "tables\__init__.py", line 55, in <module>
TypeError: sequence item 2: expected str instance, NoneType found
[13384] Failed to execute script 'test_script' due to unhandled exception
```

### Frozen program debug trace
[exe_run_debug.txt](https://github.com/pyinstaller/pyinstaller/files/15038451/exe_run_debug.txt)

### Pyinstaller debug trace
[out.txt](https://github.com/pyinstaller/pyinstaller/files/15038452/out.txt)

### Other information:
I also create the hook-tables.py but the issue still happens.
```
from PyInstaller.utils.hooks import collect_submodules
# tables keeps Python extensions loaded with dynamic imports here.
hiddenimports = collect_submodules('tables')
```
I tried several versions of pandas, tables and pyinstaller and I pinpointed (hopefully well) the issue to the way pyinstaller handles the tables module. I use conda as a virtual environment management solution, the issue I tested on a clean environments with minimal installed packages.
All the packages I installed with pip. (with conda the resulted program has around 250 MB and still not working).
When freezing I used the --noupx, --onedir, --hidden-import=tables and --debug=all flags but I also tried different combinations.

**Comment by rokm** [comment]
Hmm, I cannot reproduce this with `conda`-installed `pytables`, but I can with PyPI `tables` wheel. 

With the latter, `libblosc2.dll` is bundled in the `tables` package (in addition to a copy being placed in `tables.libs` directory...), and the error is triggered because this bundled copy is not collected.

So adding [`--collect-binaries tables`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-binaries) to your PyInstaller command should do the trick.

---

Do note, however, than `tables` upon import uses `cpuinfo` ([here](https://github.com/PyTables/PyTables/blob/ae689fd5b05d73cd9558fbf9a865d13a4082dc2d/tables/leaf.py#L7-L11)). `cpuinfo` in turn uses `multiprocessing` - and for that to work with PyInstaller, you need to ensure that `multiprocessing.freeze_support` is called before any `multiprocessing` primitive is used (i.e., before you import `tables`).

See https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#multi-processing

So effectively, you need to import `tables` like this:

```python
import multiprocessing
multiprocessing.freeze_support()
import tables
...
```

**Comment by qoolcezar** [comment]
Confirmed fix!
Thank you @rokm !
