### ISSUE TITLE
Modify bootloader strings to help prevent false positives

### ISSUE THREAD

**Issue by danyeaw** [pyinstaller/pyinstaller#8425]
One of the things I noticed now that we are uploading our bootloaders to VirusTotal is that some of them are detected by [YARA](https://yara.readthedocs.io/en/stable/index.html) rules like: https://github.com/bartblaze/Yara-rules

I went around to different Yara rule repositories and opened Pull Requests to try to remove PyInstaller rules. Some of them have been merged already, many are still open though.

Even if the Yara rules are marked informational, the bootloader files where the rule finds PyInstaller have much higher false positive rates.

The rules are also pretty simple and many were written based on this article from https://isc.sans.edu/diary/21057 8 years ago. For example, they are opening the bootloader and looking for resources with certain strings, for instance with one of:

- pyi-windows-manifest-filename
- pyi-runtime-tmpdir
- PyInstaller
- _PYI_ONEDIR_MODE
- pyi-bootloader-ignore-signals
- Cannot open PyInstaller

Since there seems to be quite a few of these Yara rules copied from this article, what if we modify some of these common strings being searched for so that they are no longer present? This of course could cause people to update their rules, but I don't get the feeling that anyone is out there really trying to stay ahead of PyInstaller since we aren't malicious software.

**Comment by rokm** [comment]
Let's not. 

Like you said, nothing prevents the rules from being updated for the changed names; and then updated yet again when we change them again, and again, and again. So I think if scanners want to identify PyInstaller-built executables (even if just for informative purposes), they will always have enough information for that - if nothing else, they could home in on the magic pattern at the beginning of PKG archive.

For example, that `_PYI_ONEDIR_MODE` is a relatively new addition to PyInstaller: https://github.com/pyinstaller/pyinstaller/commit/9cb94974429e4558bca84a8352de51f238b62a78 I have a branch with refactoring of bootloader where this will end up renamed to `_PYI_POSIX_ONEDIR_MODE`, though, and used only in POSIX codepaths.

`pyi-windows-manifest-filename` was removed in 4.6.

`pyi-runtime-tmpdir` and `pyi-bootloader-ignore-signals` are run-time options; and while we could rename them internally, I would prefer not to.

`PyInstaller` and `Cannot open PyInstaller` -> I suppose this means we would need to remove all mentions of PyInstaller from all erorr messages (and other strings).

**Comment by bwoodsend** [comment]
> Even if the Yara rules are marked informational, the bootloader files where the rule finds PyInstaller have much higher false positive rates.

Do we have any reason to believe this is a real cause and effect and not just a correlation caused by both the YARA rules and the antiviruses looking for the same thing i.e. stuff that looks like PyInstaller's bootloaders?

**Comment by danyeaw** [comment]
I thought when I went through the detections earlier, some of them were flagged by Yara rules, and some were not. Today they were all detected by this rule: https://github.com/bartblaze/Yara-rules/blob/master/rules/generic/PyInstaller.yar.

Here are the false positives, most out of 71 virus tools, some out of 68.

| compiler | run.exe | run_d.exe  | runw.exe | runw_d.exe |
|------------- | ------------- | ------------- | -------------- | ---------------- |
| gcc x64 | 5 | 1 | 2 | 1 |
| msvc x64   | 4 | 4 |  4 | 2 |
| clang x64  | 3 | 2 | 2 | 2 |
| msvc 32-bit  | 4 | 2 | 6 | 3 |

I guess to prove that it improves it, I would need to create some PyInstaller bootloaders that aren't detected by that Yara rule.

**Comment by bwoodsend** [comment]
I think there's a delay in the YARA rule flagging. I looked for the YARA flags yesterday and couldn't find them then refreshed the virus total page a bit later and the all appeared.

> I guess to prove that it improves it, I would need to create some PyInstaller bootloaders that aren't detected by that Yara rule.

Which would inevitably be different enough that the vendors that memorise files instead of analysing them stop thinking of them as malicious.

Perhaps we could do the opposite. i.e. Create some new bootloaders that are sufficiently shuffled around to defeat the memorisation based vendors but still match the YARA rules? If we can make the detection rate drop significantly that way then we know that those vendors aren't paying much/any heed to the YARA rules.

**Comment by rokm** [comment]
If you want to test with reshuffled bootloader, you could try https://github.com/rokm/pyinstaller/tree/bootloader-refactor

**Comment by danyeaw** [comment]
The reshuffled bootloader is performing much better for false positives:

| compiler | run.exe | run_d.exe  | runw.exe | runw_d.exe |
|------------- | ------------- | ------------- | -------------- | ---------------- |
| gcc x64 | 0 | 0 | 1 | 1 |
| msvc x64   | 1 | 1 |  2 | 2 |
| msvc 32-bit  | 2 | 2 | 5 | 4 |

I haven't figured out how to run clang locally, I'm getting a linker flags missing error.

While they aren't zero, they are definitely better. The Yara rules are still being detected.

**Comment by danyeaw** [comment]
I think this is probably not a good option, I'll keep thinking about what else we can do to reduce false positives. The reshuffled bootloader looks like it will help for sure.

**Comment by rokm** [comment]
> The reshuffled bootloader looks like it will help for sure.

Only until after first release, though...
