### ISSUE TITLE
Packaged binaries do not respect PYTHONUNBUFFERED and parent process never gets stdout / stderr

### ISSUE THREAD

**Issue by Prinzhorn** [pyinstaller/pyinstaller#8426]
## Description of the issue

Originally via mitmproxy (https://github.com/mitmproxy/mitmproxy/issues/6757), took a while to track this down to a minimal PyInstaller binary. When spawning a PyInstaller binary from a parent process (not a pty) the parent does not get the stdout. If I instead spawn a `python` process with the identical (unpackaged) script it works. The script also respects `PYTHONUNBUFFERED`, the PyInstaller binary does not. It does not matter what the parent process is (we tried spawning from Python and Node.js).

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.6.0```
* Version of Python: 3.12.3
* Platform: Docker `python:3.12.3-bookworm` (so Debian I guess)
* How you installed Python: Used the `python:3.12.3-bookworm` docker for the repro
* Did you also try this on another platform? Does it work there? N/A

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode** (N/A it's a single file, I'm using `--onefile` already)
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

hello.py

```py
import time


def main():
    while True:
        print("Hello, world! Press Ctrl+C to exit.")
        time.sleep(1)


if __name__ == "__main__":
    main()
```

parent.py

```py
import subprocess


def run_command(command):
    try:
        process = subprocess.Popen(
            command,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            shell=True,
            env=dict(PYTHONUNBUFFERED="1"),
        )

        while True:
            stdout_line = process.stdout.readline().decode().strip()

            if stdout_line:
                print("stdout:", stdout_line)

            # Check if both pipes are closed and process has terminated
            if not stdout_line and process.poll() is not None:
                break

    except Exception as e:
        print("Error:", e)

# Using the binary created from hello.py does not work (no stdout).
command = "/dist/hello"

# This works, we get the stdout (only when setting `PYTHONUNBUFFERED`).
# command = "python hello.py"

run_command(command)
```

I used Docker to reproduce this:

1. `docker run --rm -it python:3.12.3-bookworm /bin/bash`
2. From a second terminal: `docker cp hello.py [ID]:/` (replace [ID] with the id of the docker container, e.g. via `docker ps`)
3. From a second terminal: `docker cp parent.py [ID]:/` (replace [ID] with the id of the docker container, e.g. via `docker ps`)
4. Now we're in the docker container and have both `hello.py` and `parent.py` available.
5. `pip install pyinstaller`
6. `pyinstaller --onefile hello.py`
7. `chmod +x dist/hello`
8. Now we have both the hello.py and a `/dist/hello` binary created from it.
9. `python parent.py`
10. We got no output
11. Edit `parent.py` to run `command = "python hello.py"` instead of `command = "/dist/hello"`
12. `python parent.py`
13. We see the output of hello.py
14. Edit `PYTHONUNBUFFERED="0"`
15. We don't see the output of hello.py
16. So launching `python hello.py` gets us stdout if we set `PYTHONUNBUFFERED`. The binary created by PyInstaller does not respect it and does not give us stdout.

So I wonder if this is expected and wanted behavior? Do we really need to manually flush every time? Or should the behavior of `hello.py` be identical to the packaged version?

**Comment by bwoodsend** [comment]
I'd argue that that's expected. I don't think we've explicitly considered this one but we do actively avoid letting variables like `PYTHONDEVMODE` or the various site-packages or encoding affecting ones from affecting the runtime of an executable that wasn't built to expect it. If we were going to support it, it would be a build time option and go [in here](https://pyinstaller.org/en/stable/spec-files.html#specifying-python-interpreter-options).

Personally I've always considered unbuffered mode to be a honey pot. Using flush whenever you're finished sending something sounds far more reasonable to me than mucking around with global interpreter settings.

**Comment by rokm** [comment]
If you want unbuffered I/O, read https://pyinstaller.org/en/stable/spec-files.html#specifying-python-interpreter-options

**Comment by Prinzhorn** [comment]
Thanks a lot :+1:
