### ISSUE TITLE
Pyinstaller failed: PyInstaller.isolated._parent.SubprocessDiedError: Child process died calling _is_package() with args=('skimage.io._plugins',) and kwargs={}.

### ISSUE THREAD

**Issue by hoangthethief** [pyinstaller/pyinstaller#8430]
Description of the issue
I use pyinstaller to create executable file. But it failed multiple times.

Context information (for bug reports)
File "C:\ProgramData\Anaconda\Lib\site-packages\PyInstaller\isolated\_parent.py", line 307, in call
    raise SubprocessDiedError(
PyInstaller.isolated._parent.SubprocessDiedError: Child process died calling _is_package() with args=('skimage.io._plugins',) and kwargs={}.

Output of pyinstaller --version: 6.6.0
Version of Python: 3.11.7
Platform: Windows 11

Please help me fix this bug.
Thank you!

**Comment by rokm** [comment]
What happens if you open python interpreter and run `import skimage.io._plugins`?
