### ISSUE TITLE
Module not found at runtime

### ISSUE THREAD

**Issue by rafael-wampfler** [pyinstaller/pyinstaller#8435]
Hello

I'm using v6.6.0 and Python 3.11 to compile my Python Flask server into a standalone. For this I'm using the following server.spec file:

```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import copy_metadata
from PyInstaller.utils.hooks import collect_submodules  # Added
import sys ; sys.setrecursionlimit(sys.getrecursionlimit() * 5)
from PyInstaller.utils.hooks import collect_dynamic_libs

datas = []
datas += collect_data_files('torch')
datas += copy_metadata('torch')
datas += copy_metadata('tqdm')
datas += copy_metadata('regex')
datas += copy_metadata('requests')
datas += copy_metadata('packaging')
datas += copy_metadata('filelock')
datas += copy_metadata('numpy')
datas += copy_metadata('tokenizers')
datas += copy_metadata('transformers')
datas += collect_data_files('transformers')

# Added
hiddenimports = []
hiddenimports = collect_submodules('transformers')

block_cipher = None


a = Analysis(
    ['server_midj.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports, 
    hookspath=['pyinstaller-hooks'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
    # Added
    module_collection_mode={
        "transformers": "pyz+py",
    },
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='server_midj',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

I have in `chatbot/image_generation/pyinstaller-hooks/hook-server.py`:

```
from PyInstaller.utils.hooks import collect_data_files
datas = collect_data_files('image_generation')
```

At runtime I'm now getting the following error:

```
  File "image_generation/server_midj.py", line 10, in <module>
ModuleNotFoundError: No module named 'helper_functions_midj'
[2165581] Failed to execute script 'server_midj' due to unhandled exception!
```

`helper_functions_midj.py` is located at `chatbot/image_generation`, so at the same folder as `server_midj.py` which is the starting point of my app.

I'm completely confused why this file is not found.

**Comment by bwoodsend** [comment]
Have you tried adding `helper_functions_midj` to `hiddenimports`?

**Comment by rafael-wampfler** [comment]
I have tried it with `hiddenimports.append('helper_functions_midj')` and `hiddenimports = collect_submodules('transformers') + collect_submodules('helper_functions_midj')` but none of the two worked.

**Comment by rokm** [comment]
Does `image_generation` also contain an `__init__.py` file?

If that is the case, then PyInstaller will not add `image_generation` to its search path, but rather its parent directory (which you should see if you look for `INFO: Extending PYTHONPATH with paths` debug message and the line that follows it).

So you will need to add the path to `image_generation` directory to either `PYTHONPATH` environment variable before running PyInstaller, or adding it to the `pathex` list in the spec file.

**Comment by rokm** [comment]
Since it seems that the .spec file is also located in the `image_generation` directory (next to the entry-point script), you can use `SPECPATH` variable, which stores the path to directory that contains the .spec file:
```
a = Analysis(
   ['server_midj.py'],
   pathex=[SPECPATH]`,
   ...
)
```

**Comment by rafael-wampfler** [comment]
Adding `SPECPATH ` worked. Thank you very much for the help.
