### ISSUE TITLE
Built executables connect to unknown IPs

### ISSUE THREAD

**Issue by RobertAzovski** [pyinstaller/pyinstaller#8436]
Hello. I have noticed that any executables make connections to different unknown ips even if it is oneliner scripts, even hello world scripts.
https://www.virustotal.com/gui/file/74f7f4e33d0ecac814afcba85f917eda89d30a61b9707d0c825b18b9391edc6a/behavior
`NetRange:       131.253.21.0 - 131.253.47.255
CIDR:           131.253.21.0/24, 131.253.22.0/23, 131.253.32.0/20, 131.253.24.0/21
NetName:        MICROSOFT
NetHandle:      NET-131-253-21-0-1
Parent:         NET131 (NET-131-0-0-0-0)
NetType:        Direct Allocation
OriginAS:
Organization:   Microsoft Corp (MSFT-Z)`

I found out that this is a Microsoft IPs. This categorically does not suit me, that my program goes somewhere without my knowledge and without my permission, even if it is Microsoft itself.

I tried reinstalling the bootloader for mingv64, as described in the official documentation, but it did not help. Connections are still happening.

At the same time, I know you can say that this is specific to VirusTotal, but I checked on older exe files and there are no connections there.

I'm not worried about false positives, I want to get rid of extraneous connections. I will be glad if you help me solve this problem.

**Comment by bwoodsend** [comment]
See #8323.
