### ISSUE TITLE
SystemError: Negative size passed to Pyunicode_ New

### ISSUE THREAD

**Issue by lqyp0420** [pyinstaller/pyinstaller#8438]
when i frozen my code in win11 and used open .exe in win7.  an error happend and how can i do it?

frozen in win11 23H2 python: 3.10.9    i test pyinstaller 6.3.0 and 6.6.0 

During handling of the above exception,another exception occurred 
Traceback (most recent call last) :
File "frozen zipimporty.line93.in __init__
KeyError:"D:\tyabas-post\internal\hase_library.zip"
During handlingof the aboue exception, another exception occurred 
Traceback (most recent call last:
File frozen importlih.bootstrap>",line1027.in _find_and_load 
File frozen importlib.hootstrap> line 1002 in _find_and_load unlocke 
File frozen importlib.bootstrap line945 in _find_spec 
File frozen importlib.hootstrap_external>".line1439.in find_spec 
File frozen importlib.hootstrap_external>".line1408.in _get_spec 
File frozen importlih.bootstrap_external>".line 1374.in _path_inporter cache 
File frozen inportlib.bootstrap_external>".line 1350.in _path _hooks 
File"frozen zipimport.line95.in __init__
File frozen zipimport.line 513.in _read_directory 
File"frozen importlib.bootstrap external>",line 104.in _path_join
SystemError:Negatiuesize passed to PyUnicodeNew

**Comment by rokm** [comment]
What python version and what PyInstaller version are you using?

**Comment by lqyp0420** [comment]
> What python version and what PyInstaller version are you using?
frozen in win11 23H2   python: 3.10.9    i test pyinstaller 6.3.0 and 6.6.0

**Comment by rokm** [comment]
python >= 3.9 is not supported on Windows 7 and earlier. 

See the notes on https://www.python.org/downloads/windows/
