### ISSUE TITLE
Fatal Error 126 after compiling exe on Win 7 - Matplotlib

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#844]
**Original date**: 2014/01/07
**Original reporter**: _allankey_

I created an exe file on Win 7 and pyinstaller seems to have compiled it ok. The program opens and runs fine up until I try to plot a graph using matplotlib, at which point the program crashes and I get the console error message: 

MKL FATAL ERROR: cannot load neither mk2_avx.dll nor mk2_def.dll

Any ideas on why this is happening and what can be done to solve it? I am not sure if it's an issue with matplotlib or something else. 

Thanks in advance for any help.

**Comment by panofish** [comment]
Same problem for me.  My simple matplotlib program (see below) runs fine until I create a onefile OR onedir exe.  Then the exe fails immediately at start before executing anything.  Clearly, something is missing, either a dll or a hiddenimport, but I need help finding what is missing.

I am running Windows 7 64bit.
Python 2.7.9
pyinstaller 2.1 (installed using "pip install) 
matplotlib 1.4.3 (installed using pip install)

---------------------------------------

    from pylab import *

    figure(1, figsize=(6,6))
    ax = axes([0.1, 0.1, 0.8, 0.8])

    labels = 'Frogs', 'Hogs', 'Dogs', 'Logs'
    fracs = [15, 30, 45, 10]
    explode=(0, 0.05, 0, 0)

    pie(fracs, explode=explode, labels=labels,
                    autopct='%1.1f%%', startangle=90)

    title('Pie Chart Example', bbox={'facecolor':'0.8', 'pad':5})

    show()

**Comment by htgoebel** [comment]
@panofish Have you tried following the instructions at https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong. Please make sure you are using the lates development version, too. And esp. we need to know *what* dll exactly is missing.

**Comment by panofish** [comment]
Thanks for your help htgoebel, but I was able to solve which modules were missing by redirecting the stderr and stdout for my pyinstaller exe to a file like this:

myprogram.exe 1> errors.txt 2>&1 

Before redirecting, there was no visible output.  Inside the errors.txt file I saw 2 errors about missing modules Tkinter and FileDialog.  After adding their import statements to my python program, my pyinstaller exe now works fine!

**Comment by htgoebel** [comment]
@panofish Please post the exact error messages here, so we have a change to implement a hooks for this so other will not run into this trouble. Thanks.

**Comment by panofish** [comment]
ImportError: No module named Tkinter
ImportError: No module named FileDialog

**Comment by htgoebel** [comment]
Thanks. Is there no stack-trace around?

**Comment by panofish** [comment]
stack-trace?

**Comment by htgoebel** [comment]
https://en.wikipedia.org/wiki/Stack_trace
You are a Python developer, aren't you?

**Comment by eque** [comment]
Hi, not sure if this will help, but I ran into the same problem using enthought and running my tk script from the editor.  When I ran my script using the Powershell it was fine, so I figured the problem might have something to do with enthought.  Changing the PyLab back-end seems to help (Edit-->Preferences-->Python)

**Comment by NGJROMO** [comment]
I have a very similar problem. After I try to plot a graph using Matplotlib inside one of my Pyinstaller builds I get:
MKL FATAL ERROR: cannot load neither mkl_avx2.dll nor mkl_def.dll

After copying those dlls to the dist folder manually I get
MKL FATAL ERROR: cannot load neither mkl_vml_def.dll nor mkl_vml_avx2.dll

And after copying those dll files as well, the program runs fine.
Any help on that perhaps? I'm fairly new to pyinstaller.

**Comment by NGJROMO** [comment]
Hey guys.

Fixed my problem by adding

# Override dll search path.
ctypes.windll.kernel32.SetDllDirectoryW('C:/Users/ngj/AppData/Local/Continuum/Anaconda3/Library/bin/')
# Init code to load external dll
ctypes.CDLL('mkl_avx2.dll')
ctypes.CDLL('mkl_def.dll')
ctypes.CDLL('mkl_vml_avx2.dll')
ctypes.CDLL('mkl_vml_def.dll')

# Restore dll search path.
ctypes.windll.kernel32.SetDllDirectoryW(sys._MEIPASS)

to my code.

Kind regards,

Nick

**Comment by mrxiaohe** [comment]
@NGJROMO : 
Where exactly did you add the code? I am also encountering the same problem. Thanks!

**Comment by panofish** [comment]
I was able to solve which modules were missing by redirecting the stderr and stdout for my pyinstaller exe to a file like this:

myprogram.exe 1> errors.txt 2>&1

Before redirecting, there was no visible output. Inside the errors.txt file I saw 2 errors about missing modules Tkinter and FileDialog. After adding their import statements to my python program, my pyinstaller exe now works fine!

**Comment by NGJROMO** [comment]
@mrxiaohe:

Added the code in the preamble of the .py code that I am converting.

You're basically loading the missing DLL files manually: Here's a somewhat better explanation:
https://github.com/pyinstaller/pyinstaller/wiki/Recipe-Win-Load-External-DLL

**Comment by NGJROMO** [comment]
FYI,

After I installed countless python, pandas, matplotlib and pyinstaller (dev version) updates, I found out that the lines that I recommended on Feb 26 now make the executable crash with an 'entry point error' on some (but not all) windows 10 and 7 machines.

Commenting out those lines did the trick.
