### ISSUE TITLE
Unable to generate EXE from versions >6.2

### ISSUE THREAD

**Issue by xo-HADES-xo** [pyinstaller/pyinstaller#8440]
From Pyinstaller versions >6.2 I startarted having an issue with Pyinstaller not completing with a message: 

`
Traceback (most recent call last):
  File "C:\Python311\Lib\site-packages\win32ctypes\pywin32\pywintypes.py", line 33, in pywin32error
    yield

  File "C:\Python311\Lib\site-packages\win32ctypes\pywin32\win32api.py", line 209, in BeginUpdateResource
    return _resource._BeginUpdateResource(filename, delete)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Python311\Lib\site-packages\win32ctypes\core\ctypes\_util.py", line 39, in check_null
    raise make_error(function, function_name)

me)
OSError: [WinError 225] Operation did not complete successfully because the file contains a virus or potentially unwanted software.
`

- At first install of any version of >6.2, EXE is generated with no issue
- shut down PC and restart, I start getting error message above.
- Downgrade to Pyinstaller=6.2 and then I can generate EXE with no issues. 
- Restart PC and try again, and Pyinstaller=6.2 generates EXE with no issues. 

To replicate: 

1. create simple Hello.py file to print something
2. use: pyinstaller.exe -w Hello.pyw

I know it says virus issues, so could be false positive.  But don't see why Pyinstaller=6.2 and not any new versions.  Something changed in newer versions to make this.

**Comment by rokm** [comment]
The [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md) said pretty much everything we have to say on this matter.
