### ISSUE TITLE
Ursina Font Bug

### ISSUE THREAD

**Issue by Leonmmcoset** [pyinstaller/pyinstaller#8442]
Hello,I am made game with Ursina,but if I build with Pyinstaller,then it's always : Could not load font file: OpenSans-Regular.ttf
Even I change the font in the code:
``` python
import ursina
Text.default_font = '_internal/font/gamefont.ttf'
from ursina.prefabs.first_person_controller import FirstPersonController
app = Ursina()
```
but it is always have errors if I build by PyInstaller!

**Comment by rokm** [comment]
Hmm, to get the basic `ursina` example running frozen on Linux, I need `--collect-submodules panda3d --collect-binaries panda3d --collect-data panda3d --collect-data ursina`. The `panda3d` stuff seems to be required for pipeline, while data from `ursina` package itself includes the fonts and fixes `OSError: Could not load font file: OpenSans-Regular.ttf`.

For anything more, you'll have to provide your minimal example and what OS you are trying to run on.

**Comment by Leonmmcoset** [comment]
I use windows

**Comment by rokm** [comment]
And what PyInstaller command are you using? Any `--collect-data`, `--collect-binaries`, `--collect-submodules`?

**Comment by rokm** [comment]
FWIW, `--collect-submodules panda3d --collect-binaries panda3d --collect-data panda3d --collect-data ursina` seems to do the trick on Windows with basic `ursina` example as well.

**Comment by Leonmmcoset** [comment]
``` python
import os
os.system(f'pyinstaller --add-data "venv/bin/_internal/image/:image/"\
          --add-data "C:\\Users\\leonm\PycharmProjects\leonsystem\\venv\Lib\site-packages\\ursina:usina/"\
          --add-data "C:\\Users\\leonm\PycharmProjects\leonsystem\\venv\Lib\site-packages\\ursina-7.0.0.dist-info:ursina-7.0.0.dist-info"\
          --add-data "C:\\Users\leonm\PycharmProjects\leonsystem\\venv\Lib\site-packages\panda3d:panda3d"\
          --add-data "C:\\Users\\leonm\PycharmProjects\\leonsystem\\venv\Lib\site-packages\panda3d-1.10.14.dist-info:panda3d-1.10.14.dist-info"\
          --add-data "C:\\Users\leonm\PycharmProjects\leonsystem\\venv\Lib\site-packages\panda3d_tools:panda3d_tools"\
          --add-data "C:\\Users\leonm\PycharmProjects\leonsystem\\venv\Lib\site-packages\direct:direct"\
          --add-data "venv/bin/_internal/font/:font/"\
          --add-data "C:\\Users\leonm\PycharmProjects\leonsystem\\venv\Lib\site-packages\pipeline:pipeline"\
          --add-data "C:\\Users\leonm\PycharmProjects\leonsystem\\venv\Lib\site-packages\pipeline-0.1.0.dist-info:pipeline-0.1.0.dist-info"\
          --path "C:\\Users\leonm\PycharmProjects\leonsystem\\venv\Lib\site-packages\panda3d"\
          --collect-submodules panda3d --collect-binaries panda3d --collect-data panda3d --collect-data ursina\
          -i="C:\\Users\\leonm\\PycharmProjects\\leonsystem\\icon.ico" \
          -D -y \
          C:\\Users\leonm\PycharmProjects\leonsystem\\venv\\bin\cmd.py')
```

**Comment by rokm** [comment]
And you're getting `Could not load font file: OpenSans-Regular.ttf` with that? Can you check the contents of the program directory, then? Does `dist/<name>/_internal/ursina/fonts` exist, and does it contain `OpenSans-Regular.ttf`?

I think most of the options you are using should be unnecessary (at least for the basic example); unless you failing to activate your virtual environment or are using `pyinstaller` shim from another virtual environment. But in that case you should sort out your virtual environments instead, because otherwise you'll run into lots of subtle issues with import analysis.

**Comment by Leonmmcoset** [comment]
IT WORKS!!! THANKS!!!
