### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by joako233** [pyinstaller/pyinstaller#8443]
Hello everyone,

I've encountered a recursion error while working on my project, and I'm seeking some guidance on how to resolve it. The error message indicates a 'recursion limit exceeded' issue, and I've tried adjusting the recursion limit without success. Could anyone here provide some insights or suggestions on how to troubleshoot and fix this error?

Error message: 
=============================================================
A RecursionError (maximum recursion depth exceeded) occurred.
For working around please follow these instructions
=============================================================
My code:

`from seleniumbase import Driver
from seleniumbase import undetected
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
import time
import sys
import pandas as pd

sys.setrecursionlimit(1500)

url = 'https://www.pagespro.com/recherche/auto/Evry%20%2891000%29/toiture'

nombres_comerciales = []
telefonos = []
correos = []
sitios_web = []
direcciones = []
fiscales = []

contador = 0
driver = Driver(undetectable=True,headless=True)
driver.maximize_window()

driver.get(url)
time.sleep(1.3)
aceptar_cookies = EC.presence_of_element_located((By.XPATH,'//button[contains(text(),"COMPRIS")]'))
aceptar_cookies = WebDriverWait(driver,10).until(aceptar_cookies)
aceptar_cookies.click()

while True:
    
    click_titulos = EC.presence_of_all_elements_located((By.XPATH,"//h2[@class='h4']/.."))
    click_titulos = WebDriverWait(driver,10).until(click_titulos)

    for titulo in click_titulos:
        time.sleep(2)
        try:
            texto_titulo = titulo.text
        except:
            texto_titulo = titulo.text

        if texto_titulo not in nombres_comerciales:
            nombres_comerciales.append(texto_titulo)
            titulo.click()
            print("(+) Extracting business data...")
        else:
            continue
        
        
        telefono = EC.presence_of_element_located((By.XPATH,"//span[@id='tel_1']"))
        telefono = WebDriverWait(driver,10).until(telefono)
        telefono.click()
        time.sleep(1.2)

        texto_telefono = EC.presence_of_element_located((By.XPATH,"//span[@id='tel_1']/a"))
        texto_telefono = WebDriverWait(driver,10).until(texto_telefono)
        texto_telefono = texto_telefono.text
        texto_telefono = texto_telefono.split("\n")
        texto_telefono = texto_telefono[1]
        telefonos.append(texto_telefono)

        email = EC.presence_of_element_located((By.XPATH,"//span[@id='email_1']"))
        email = WebDriverWait(driver,10).until(email)
        email.click()
        time.sleep(1.2)

        texto_email = EC.presence_of_element_located((By.XPATH,"//span[@id='email_1']/a"))
        texto_email = WebDriverWait(driver,10).until(texto_email)
        texto_email = texto_email.text
        texto_email = texto_email.split("\n")
        texto_email = texto_email[1]
        correos.append(texto_email)

        try:    
            sitio_web = EC.presence_of_element_located((By.XPATH,"//ul[@class='list-contact']//span[@class='website_label']"))
            sitio_web = WebDriverWait(driver,6).until(sitio_web)
            sitio_web = sitio_web.text

            if "." in sitio_web and "linkedin" not in sitio_web and "facebook" not in sitio_web:
                sitios_web.append(sitio_web)
            else:
                raise ValueError("El sitio web es igual a 'Facebook'")
        except:
            try:
                click_sitio = EC.presence_of_element_located((By.XPATH,"//ul[@class='list-contact']//i[@class='adp-icon adp-icon--chevron-bas']"))
                click_sitio = WebDriverWait(driver,5).until(click_sitio)
                click_sitio.click()
                time.sleep(1.3)
                sitio_web = EC.presence_of_element_located((By.XPATH,"//ul[@class='list-contact']//li[2]//span[@class='website_label']"))
                sitio_web = WebDriverWait(driver,5).until(sitio_web)
                sitio_web = sitio_web.text
                if "Facebook" not in sitio_web:
                    sitios_web.append(sitio_web)
                else:
                    raise ValueError("El sitio web es igual a 'Facebook'")
            except:
                sitio_web = 'IT DOES NOT HAVE A WEBSITE'
                sitios_web.append(sitio_web)
        
        direccion = EC.presence_of_element_located((By.XPATH,"//span[@class='adress_label']"))
        direccion = WebDriverWait(driver,10).until(direccion)
        texto_direccion = direccion.text
        direcciones.append(texto_direccion)
        try:
            diret = EC.presence_of_element_located((By.XPATH,"//section[@id='finance_juridique']//dT[contains(text(),'SIRET')]/../dd"))
            diret = WebDriverWait(driver,10).until(diret)
            diret = diret.text
            fiscales.append(diret)
        except:
            diret = 'NO SIRET FOUND'
            fiscales.append(diret)
        
            
        time.sleep(1.3)
        driver.back()
        time.sleep(1.7)
        driver.execute_script("window.scrollTo(0, arguments[0]);", 270)
    time.sleep(2)
    print()
    print(nombres_comerciales)
   
    try:
        flecha = EC.presence_of_element_located((By.XPATH,"//button[@class='len1 adpJam']/span[@class='adp-icon adp-icon--chevron-droit']"))
        flecha = WebDriverWait(driver,10).until(flecha)
        time.sleep(2)
        flecha.click()
        contador = contador +1
        time.sleep(2)
        if contador ==1:
            print("(+) All businesses were successfully analyzed.")
            print()
            print("Exiting...")
            break
    except:
        pass
  
    time.sleep(3)

driver.close()

diccionario = {"Business name": nombres_comerciales,
               "Phone number": telefonos,
               "Adress": direcciones,
               "Email": correos,
               "Siret": fiscales,
               "Website": sitios_web}

df = pd.DataFrame(diccionario)
df.to_excel("Data.xlsx",index=False)
quit()
`

**Comment by bwoodsend** [comment]
Like the instructions say, the `sys.setrecursionlimit(1500)` goes in your spec file then you rebuild with `pyinstaller your-project.spec`.

Or better yet, build from a minimal virtual environment with only pyinstaller and the packages you need in it. You might also want to consider replacing pandas with xlsxwriter since you're not using pandas for anything pandas-related and it's a horrible dependency with a huge file size, tonnes of optional dependencies (which stresses the recursion limit) and terrible startup time.
