### ISSUE TITLE
One python script has change to exe file, but the exe call a bat file to start other python script failed, the error is no module name site

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#845]
**Original date**: 2014/01/08
**Original reporter**: *shitian DOT ma AND mediatek DOT  COOM *

pyinstaller version : pyinstaller 2.0
python version: python 2.7.1

This error involved three files:

file(named: Updater.py) will to change to exe file content:  
   import os
   if __name__ == '__main__':
       os.system("start.bat")

bat file content:
    python start.py

another python file content:
    if __name__ == '__main__':
       print("start.py")

Spec file to change to exe file:
  # -*- mode: python -*-
a = Analysis(['D:\\develop\\code\\workspace\\TestUX\\Updater.py'],
             pathex=['D:\\Software\\pyinstaller-2.0','C:\\Python27\\Lib\\site-packages','C:\\Python27\\Lib','C:\\Python27\\libs'],
             hiddenimports=[],
             hookspath=None)
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          a.binaries,
          a.zipfiles,
          a.datas,
          name=os.path.join('E:\\InstallTest\\TestNATA', 'Updater.exe'),
          debug=False,
          strip=None,
          upx=True,
          console=True , icon='D:\\NATAInstall\\Installpackages\\SHQA\\10.ico')

Run Result:
   console display: no module named site

**Comment by matysek** [comment]
@JMSwag is this issue still relevant or could it be closed?

**Comment by JMSwag** [comment]
@matysek this can be closed.
