### ISSUE TITLE
Pyinstaller  does not add CFBundleVersion on macOS

### ISSUE THREAD

**Issue by arun-gautham** [pyinstaller/pyinstaller#8452]
{
    NSLocalizedDescription = "The Info.plist in the package must contain the CFBundleVersion key.";
    NSLocalizedFailureReason = "Unable to validate your application.";
}

The when u build my pkg with Pyinstaller the pkg is created and works well , but when I validate_app 

xcrun altool --validate-app -t osx -f xxxxxxx.pkg -u arunrajarao@gmail.com -p xxxxxxxxx --verbose

I get the above error, this is not blocking as I can update the info.plist and continue
how ever it would be nice to have PyInstaller already do it .

**Comment by rokm** [comment]
If you are building from the .spec file, you can add entries for `Info.plist` there:
https://pyinstaller.org/en/stable/spec-files.html#spec-file-options-for-a-macos-bundle

(either directly to `info_plist` dictionary, or to `version` key).

**Comment by rokm** [comment]
> (either directly to `info_plist` dictionary, or to `version` key).

Actually, `version` seems to be translated into `CFBundleShortVersionString`, so if you need `CFBundleVersion` to pass validation, you will need to add it to `info_plist` dictionary.

**Comment by arun-gautham** [comment]
Thanks working

**Comment by rokm** [comment]
For the reference, what value are you passing to `CFBundleVersion`, and what to `CFBundleShortVersionString`. Would it help if PyInstaller translated the `version` (which is "0.0.0" by default) to both of those instead of just `CFBundleShortVersionString`?
