### ISSUE TITLE
Python3 is added with with bundle identifier 'com.apple.python3'.

### ISSUE THREAD

**Issue by arun-gautham** [pyinstaller/pyinstaller#8453]
when o build on MACOS I see that Python3 is added with with bundle identifier 'com.apple.python3'.

{
    NSLocalizedDescription = "Asset validation failed";
    NSLocalizedFailureReason = "Invalid Bundle. The application bundle may not contain tools or frameworks provided by Apple, or using bundle identifiers in the 'com.apple.' namespace. Invalid bundle: Python [com.ngintec.OffCloud.Host.pkg/Payload/OffCloud.app/Contents/Frameworks/Python3.framework], with bundle identifier 'com.apple.python3'. (ID: 77d87677-2b06-47b5-ae28-6c87df8164cb)";
    NSUnderlyingError = "Error Domain=IrisAPI Code=-19241 \"Asset validation failed\" UserInfo={status=409, detail=Invalid Bundle. The application bundle may not contain tools or frameworks provided by Apple, or using bundle identifiers in the 'com.apple.' namespace. Invalid bundle: Python [com.ngintec.OffCloud.Host.pkg/Payload/OffCloud.app/Contents/Frameworks/Python3.framework], with bundle identifier 'com.apple.python3'., id=77d87677-2b06-47b5-ae28-6c87df8164cb, code=STATE_ERROR.VALIDATION_ERROR.90278, title=Asset validation failed, NSLocalizedFailureReason=Invalid Bundle. The application bundle may not contain tools or frameworks provided by Apple, or using bundle identifiers in the 'com.apple.' namespace. Invalid bundle: Python [com.ngintec.OffCloud.Host.pkg/Payload/OffCloud.app/Contents/Frameworks/Python3.framework], with bundle identifier 'com.apple.python3'., NSLocalizedDescription=Asset validation failed}";
    "iris-code" = "STATE_ERROR.VALIDATION_ERROR.90278";

is there config to change this behaviour

**Comment by rokm** [comment]
We don't modify the `Info.plist`s from collected frameworks. 

So the way to avoid this would be to not use the Apple's python3 interpreter for your build environment, but instead use python.org python build.

**Comment by Arvin-xc** [comment]
Same problem :(

**Comment by Arvin-xc** [comment]
I fixed this by changing `com.apple.python3` to `org.python.python` in
`xxx/Python3.framework/Versions/3.9/Resources/Info.plist`

**Comment by bwoodsend** [comment]
Given that the builtin Python environment is deprecated and there's really no reason to use it, I don't see much value in trying to add a workaround for this.
