### ISSUE TITLE
ProductVersion in windows version info doesn't show in some cases

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#846]
**Original date**: 2014/01/09
**Original reporter**: _anonymous_

PrdouctVersion in windows version info doesn't show when the ProductVersion string length doesn't divide by 4 (length % 4 == 0)

**Comment by htgoebel** [comment]
[Assume](https://github.com/pyinstaller/pyinstaller/pull/2599#issuecomment-317804407) this is solved.
