### ISSUE TITLE
spybot/avast reports runw.exe / created .exe as infected - antivirus false positive

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#847]
It was recently reported that the python3 branch causes false positives for created .exe files. Noticeably Avast and Spybot.

It was also reported that version of python3 from 6/23/2014 works without any false positives.

Possible solution:
* examine python3 branch history what is different
* avoid stripping of run*.exe files?
* maybe the exec can be marked post build: http://stackoverflow.com/questions/350977/how-to-make-my-program-dep-compatible
* try to make windows bootloader DEP compatible (Data Execution Prevention)
     * https://www.veil-framework.com/dep-pyinstaller/
     * http://www.verisgroup.com/2014/05/07/pwnstaller-and-the-veil-framework/

**Comment by hellais** [comment]
Is this still an issue? Are there any suggestions on which branch/git tag/HEAD to use to avoid triggering antiviruses?

This is a blocker on having important software such as [Tor](https://torproject.org) from using pyinstaller.

**Comment by htgoebel** [comment]
@hellais One can never know what antivirus detects. This can change from one day to another.

**Comment by matysek** [comment]
@hellais Recently this has been reported only for the python3 branch. The 'develop' branch should be fine.

There is probably no other way than report it to antivirus companies as False Positives. For one project (that uses python3 branch) helped to report it as false positives. It helped to improve the situation.

But as @htgoebel pointed out. One can never know what antivirus detects.
