### ISSUE TITLE
Import error with mpl_toolkits.mplot3d

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#848]
**Original date**: 2014/01/14
**Original reporter**: *clmabile AND numericable DOT fr*

High

I am trying to build an exe where mplot3d is used to create a 3D drawing. The line in my python code is as follows:
```
from mpl_toolkits.mplot3d import Axes3D
```
When I run my exe file created with pyinstaller I get the following message
```
Import error: no module named mpl_toolkits.mplot3d
```
in the warning file generated by pyinstaller I find this message:
```
W: no module named mpl_toolkits (delayed import by matplotlib.mlab)
```
can you help me

Claude

**Comment by flalix** [comment]
try
import importlib
importlib.import_module('mpl_toolkits.mplot3d').__path__

**Comment by grofte** [comment]
This happens to me too but only on Windows. Mac and Linux are fine. 
```python
import importlib
importlib.import_module('mpl_toolkits.mplot3d').Axes3D
```
did not work but I'm not sure if that's what you meant by path.

**Comment by htgoebel** [comment]
Please follow the instructions in https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong

**Comment by matysek** [comment]
This is probably related to #727

**Comment by daikaixian** [comment]
`pip install matplotlib  `

@pyinstaller-tickets-migration 
it works for me.

**Comment by Jacoobr** [comment]
@pyinstaller-tickets-migration 
I use the command as follows:
`pip install matplotlib` 
then I compile my code  ,it worked! The error is gone.

**Comment by yoyojacky** [comment]
sudo pip install -U  matplotlib  
it worked! the error is fixed.
