### ISSUE TITLE
main script should be byte-compiled

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#850]
**Original date**: 2014/01/20
**Original reporter**: *anonymous*

command line:

pyinstaller --runtime-hook rthook_pyqt4.py --onefile test.py
pyinstaller test.spec

using archive viewer, i can extract the test.py file, the other files from the project are in the correct pyc format inside the archive.

**Comment by htgoebel** [comment]
This is now handled in #1847. I assume we'd not implement this for another few years, if the bug in #1847 wouldn't have shown up.
