### ISSUE TITLE
No Module Name listenerimpl

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#854]
**Original date**: 2014/04/16

i was following ticket no #312:
i have changed my hook files,hook-wx.lib.pubsub.setuparg1.py and hook-wx.lib.pubsub.core.py, and  also added all  modules of my asset into .spec file which  were causing error that module not found.
in my .spec file i also have added wx.lib.pubsub.core.arg1.listenerimpl along with other nodules in hiddenimports list.   my exe is getting created but still it is  not working, throwing the error in log file "no module named listenerimpl". i am using python2.7,wx2.8,pyInstaller2.0
Please guide..

**Comment by htgoebel** [comment]
The test-cases `test_wx_pubsub_arg1` and `test_wx_pubsub_kwargs` show this problem, if the hook mechanism fails (as it does as of today and f0d24ba65c1). So I'm closing this issue, esp. since the original poster did never answer.
