### ISSUE TITLE
 Could not find the Qt platform plugin "xcb"

### ISSUE THREAD

**Issue by pysoft13** [pyinstaller/pyinstaller#8541]
## Description of the issue
python application run fines when running the python script but doesn't launch one 'compiled' with pyinstaller with one_file option.
same app works great with pyinstaller on red hat 7, i'm not able to run the pyinstaller executable on red hat 8

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.6.0```
* Version of Python: 
* Platform: 
* How you installed Python: 
* Did you also try this on another platform? Does it work there?
works on red hat 7, not on red hat 8

NO Errors on pyinstaller log, executable is well generated but crashes with the xcb error.

**Comment by rokm** [comment]
Either you are missing a low-level dependency of the `xcb` platform plugin on the target system, or there is a conflict between shared libraries collected from the build RHEL7 system and the run-time RHEL8 system. 

In general, there are no guarantees about cross-distribution compatibility (or across different versions of the same distribution), especially with complex GUI frameworks.

I suppose you could try debugging this by creating a onedir build, and then try running `ldd` against the `xcb` plugin shared lib (with `LD_LIBRARY_PATH` set to the frozen application's `_internal` directory) on the target system. That would tell you if there is a missing library.

**Comment by bwoodsend** [comment]
Can you clarify what the build and runtime environments are in the failing case? Are you building on RHEL7 then running on 8 or building and running on 8? And which Qt variant is this? And are you installing it from PyPI or RedHat repositories?

**Comment by toledo-labs** [comment]
I'm having the same problem on Ubuntu 22.04 my app runs in terminal but cannot run with a pyinstaller binary

**Comment by rokm** [comment]
> I'm having the same problem on Ubuntu 22.04 my app runs in terminal but cannot run with a pyinstaller binary

What Qt bindings are you using, and how did you install them (pip, apt, ...)?

**Comment by toledo-labs** [comment]
I'm building in a virtual env setup by qtcreator. The Qt and app dependencies were install via pip. 
![Screenshot from 2024-05-25 05-34-38](https://github.com/pyinstaller/pyinstaller/assets/142635636/0243ee1f-795d-486e-9e4a-720f608ab213)


However the qtcreator IDE in order to startup is binded to a Qt library from by home directory. The library was built from source. Thanks for replying

**Comment by rokm** [comment]
> I'm building in a virtual env setup by qtcreator. The Qt and app dependencies were install via pip. ![Screenshot from 2024-05-25 05-34-38](https://private-user-images.githubusercontent.com/142635636/333800268-0243ee1f-795d-486e-9e4a-720f608ab213.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDQ4NzEsIm5iZiI6MTcxNjY0NDU3MSwicGF0aCI6Ii8xNDI2MzU2MzYvMzMzODAwMjY4LTAyNDNlZTFmLTc5NWQtNDg2ZS05ZTRhLTcyMGY2MDhhYjIxMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNVQxMzQyNTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MDAzODE0NjM1YmFiYTFmODgwNjljYzIyNjIzZmQzMTVjZmQyOThlN2QxODA5ZGEwN2E2Y2U2MzUxOTM1MjkyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.P2MofyaxtFbLwyx6h_8aEbnsE8_VA2y1Siu6jvEXtyE)
> 
> However the qtcreator IDE in order to startup is binded to a Qt library from by home directory. The library was built from source. Thanks for replying

You need to install PyInstaller in that virtual environment, and ensure that you are running PyInstaller that is installed in that virtual environment (and not some other instance that you may happen to have in `PATH`).

**Comment by toledo-labs** [comment]
Ok, pyinstaller was installed in the virtual env but I still had one more thing to do. I had to remove the Qt library in my home directory that qtcreator uses to start up. The virtual env still uses the OS 
 env variables: LD_LIBRARY_PATH="$LD_LIBRARY_PATH:/home/toledo/Qt/lib/". Once I removed this library or its path it worked. Thank you sir.
