### ISSUE TITLE
Some change broke PyArmor Behavior

### ISSUE THREAD

**Issue by LuisHenri** [pyinstaller/pyinstaller#8562]
## Description of the issue

I was using PyInstaller v4.* until the problem with the [new SetupTools v70 release problem](https://github.com/pyinstaller/pyinstaller/issues/8554), when I switched to v6.*.

I use PyArmor to obfuscate my application and PyInstaller to generate the executable.
With PyArmor, I also have some [plugins](https://pyarmor.readthedocs.io/en/v7.7.4/how-to-do.html#how-to-deal-with-plugins) defined throughout my code.

The problem is that after the PyInstaller update, some of the Plugins stopped working. More specifically, when I use these plugins from inner packages inside my Application (using the plugins withing my main.py works as expected).
After some investigation, I noticed that the problem started on [PyInstaller v5.11.0](https://github.com/pyinstaller/pyinstaller/compare/v5.10.1...v5.11.0). It works just fine on v5.10.1. I haven't had time to check what exactly was changed though.

So, I assume that it has been like that ever since.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.11.0 and above```
* PyArmor version: ```7.7.4```
* Version of Python: 3.8.10
* Platform: Windows 11
* How you installed Python: python.org/downloads and venv
* Did you also try this on another platform? No

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [X] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

See https://gist.github.com/LuisHenri/4e488c87648f10b518606d24da4a2447

**Comment by bwoodsend** [comment]
> The problem is that after the PyInstaller update, some of the Plugins stopped working

What does that actually mean? Bear in mind that we don't use or support pyarmor.

**Comment by bwoodsend** [comment]
Ahh, nevermind. Now I see you're expecting it to run this plugin script but instead it's jumping straight into your main code.

**Comment by LuisHenri** [comment]
Sorry, @bwoodsend. I added a link to PyArmor's Plugins page, but I'll try to briefly explain it.

These "Plugins" are comments in the code that are used to inject some functions or other behaviors for when the Code is obfuscated by PyArmor.
I.e., During the simple execution of my sample scripts above (`python main.py`) it will print "Hello World!", while running it obfuscated and packed should print "Entered PyArmor Plugin".

I'll update my gist because I think I've found a clearer way of showing it is on PyInstaller side. Give me some minutes, please

**Comment by rokm** [comment]
Looking at the PyArmor-patched spec,

```
# Patched by PyArmor
_src = 'C:\\Users\\Rok\\Development\\pyi-pyarmor\\code'
_obf = 0
for i in range(len(a.scripts)):
    if a.scripts[i][1].startswith(_src):
        x = a.scripts[i][1].replace(_src, r'C:\Users\Rok\Development\pyi-pyarmor\code\dist\obf')
        if os.path.exists(x):
            a.scripts[i] = a.scripts[i][0], x, a.scripts[i][2]
            _obf += 1
if _obf == 0:
    raise RuntimeError('No obfuscated script found')
for i in range(len(a.pure)):
    if a.pure[i][1].startswith(_src):
        x = a.pure[i][1].replace(_src, r'C:\Users\Rok\Development\pyi-pyarmor\code\dist\obf')
        if os.path.exists(x):
            if hasattr(a.pure, '_code_cache'):
                with open(x) as f:
                    a.pure._code_cache[a.pure[i][0]] = compile(f.read(), a.pure[i][1], 'exec')
            a.pure[i] = a.pure[i][0], x, a.pure[i][2]
# Patch end.
```

This will fail to update the code cache in PyInstaller >= 5.11.0 because the TOC list is now just list, and so `a.pure` does not have a `_code_cache` attribute attached to it anymore. See #7615 and https://github.com/pyinstaller/pyinstaller/commit/a9619ea4e17e8c9f315d107bdabfc0b7374f0bbe specifically.

**Comment by rokm** [comment]
While this probably has quite problematic implications, it is not really our problem, and is something that PyArmor should deal with on their side.

**Comment by LuisHenri** [comment]
For anyone in the future, while PyArmor doesn't fix this issue, the solution will be to fixate PyInstaller version to 5.10.*
