### ISSUE TITLE
In-memory solution and zero-copy as alternative to _MEI_ unpacking

### ISSUE THREAD

**Issue by ManPython** [pyinstaller/pyinstaller#8572]
**Is your feature request related to a problem? Please describe.**
In-memory solution and zero-copy as alternative to _MEI_ can be this what users/coders expecting as code in RAM not TEMP dirs
https://github.com/pyinstaller/pyinstaller/issues/3717
 https://github.com/pyinstaller/pyinstaller/issues/8571

**Describe alternatives you've considered**
Pyoxidizer.. Nuitka, etc.

**Additional context**
just simple command we need 
`pyinstaller --in-memory --console script_python.py`

**Comment by bwoodsend** [comment]
Shared libraries can't be ran from RAM on any platform. This request is impossible.

**Comment by rokm** [comment]
Ain't happening. If you require this sort of functionality, go with the alternatives you listed. Or create a RAM-disk and point your `TMP` / `TEMP` at it. Or don't use the `onefile` mode.

**Comment by ManPython** [comment]
@bwoodsend 
There is many tricks where this can be done.. in case I not clarified vison
1. VM type solutions, eg. many obusfactors doing this, but also c# is effective with this but is simple way due nature of language
2. Attach lib as binary
https://giodicanio.com/2024/03/25/embedding-and-extracting-binary-files-like-dlls-into-an-exe-as-resources/
https://github.com/GiovanniDicanio/CppWinDllResourceExtractor
3. Use python parts as static part or source code that preparing eg. python311.dll then as in 2 point attach other related .dll as without source but as required for specified OS (eg. vcruntime140.dll msvcp140.dll etc), also .pyc files as compiled have sources and can be compiled in other way 

I was more focused on this feature by point 3

**Comment by ManPython** [comment]
Open thread! ; )
https://github.com/fancycode/MemoryModule
https://web.archive.org/web/20240226050917/https://www.andreafortuna.org/2017/12/08/what-is-reflective-dll-injection-and-how-can-be-detected/
https://www.defcon.org/images/defcon-20/dc-20-presentations/King/DEFCON-20-King-Reflective-Injection-Detection.pdf
https://www.youtube.com/results?search_query=Detecting+Reflective+Injection

**Comment by ManPython** [comment]
Or maybe tool can be added as standard?
https://vishalgrade.com/2021/01/14/how-to-do-ilmerge-in-dynamics-ce-cds-data-verse-plugin-to-merge-multiple-assemblies-into-one/

https://github.com/ytk2128/dll-merger
https://github.com/dotnet/ILMerge

**Comment by bwoodsend** [comment]
> Shared libraries can't be ran from RAM on any platform. This request is impossible.

To be clear, this is just the tip of the iceberg. Just being able to load a simple DLL into memory doesn't make every package in the world automatically zip-safe.

And FWIW, Nuitka's onefile mode works exactly the same way as PyInstaller's.
