### ISSUE TITLE
 dynlib/dll was not found when the application was frozen

### ISSUE THREAD

**Issue by trittsv** [pyinstaller/pyinstaller#8575]
Hello i have the error message when i want to execute the `.exe` generated with pyinstaller.
`ddsc.dll dynlib/dll was not found when the application was frozen`

Its about the package cyclonedds from the repo cyclonedds-python which has a `ddsc.dll` dependency.

PyInstaller correctly copys the dll into the `_internal` folder and i can execute it on the pc where it was build.

But when i copy and execute it on a other windows machine the error above shows up.

Can you recommend me any way how to debug this further?

**Comment by rokm** [comment]
Can we see the full error traceback? What version of python (and is it anaconda python?), cyclonedds-python, and PyInstaller are you using?

If you load the collected `ddsc.dll` on the other Windows machine with for example Dependency Walker, do you see any missing dependencies?

**Comment by trittsv** [comment]
When I open it with dependencies then it’s marks three files as not found on the machine where it does not work:
- ucrtbased.dll
- VCRUNTIME140d.dll
- libssl-1_1-x64.dll
- Libcrypto-1_1-x64.dll

but I installed the windows redistributables.
On the pc where it works they are marked as found with dependencies

**Comment by rokm** [comment]
Can you provide the rest of the info (versions)? Also, is this pip-installed cyclonedds-python? 

PyPI windows wheels of the latest version seem to have ddsc.dll, ucrtbased.dll, and vcruntime140d.dll in `cyclonedds.libs`, and on my test machine, PyInstaller seems to collect all three of those (into the `cyclonedds.libs`, not directly into `_internal`).

**Comment by trittsv** [comment]
Thank you very much for your help, with your help you got me on the right place to look.
it works now when i added all sub depends of `ddsc.dll` manually in binaries=[ ... ] in the spec file.
I dont use the cyclonedds package from PyPi, i use a local build of cyclonedds and cyclonedds-python.
python 3.11

**Comment by rokm** [comment]
Did you have to collect `vcruntime140d.dll` and `ucrtbased.dll` from `c:\windows\system32`? Because that would explain why they were not collected automatically - files from that directory are not collected unless they are [in this list](https://github.com/pyinstaller/pyinstaller/blob/16d3f973a0b3d44cf58d34085ccfae5427ccfc51/PyInstaller/depend/dylib.py#L58-L176).

But I suppose a better question is, why is `ddsc.dll` linked against debug runtime instead of release one? (I see the same is true for Window PyPI wheel...)

**Comment by trittsv** [comment]
Yes I had to collect them from c:\windows\system32 😬

maybe it’s liked with debug runtime because the default build type is „RelWithDebInfo“?

**Comment by trittsv** [comment]
@rokm  i know now why the PyPi package of cyclonedds links with debug `vcruntime140d.dll`. 

Because in the PyPi build `cmake --build . --target install` is used,
A `--config RelWithDebInfo` is missing - windows then just builds `Debug`.

So it should be `cmake --build . --config RelWithDebInfo --target install`

I will prepare a PR in the cyclonedds-python repo.

**Comment by rokm** [comment]
Yeah, in my experience, cmake + MSVC ignores the `CMAKE_BUILD_TYPE=RelWithDebInfo` flag during configuration, and you need to explicitly specify `--config Release` at build time (`cmake --build`) to build in release mode (I think the accepted values are only `Debug` and `Release`, though, which correspond to MSVC build types; whereas `RelWithDebInfo` is CMake's internal build type).

**Comment by trittsv** [comment]
It's fixed now in the latest cyclonedds-python release
