### ISSUE TITLE
Opening console in FullScreen

### ISSUE THREAD

**Issue by AlexiJemano** [pyinstaller/pyinstaller#8580]
I have a more console based interactive app i found out that the program looks cooler when its maximized so the question is how do i tell pyinstaller to make the screen fullscreen or is there a separate module for that?

**Comment by bwoodsend** [comment]
If you copy the code inside the `if sys.platform == "win32":` block from https://github.com/pyinstaller/pyinstaller/issues/7729#issuecomment-1605503018 but replace the 2 with a 3 to `ShowWindow()`, that'll do it.

**Comment by bwoodsend** [comment]
Closing since this isn't really specific to PyInstaller. You can do apply this to a normal `.py` file launched from file explorer.
