### ISSUE TITLE
grab_version fails on pythonw.exe

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#859]
**Original date**: 2014/02/04
**Original reporter**: *michael AND redmule DOT  COOM *

running this:

```
pyi-grab_version c:\Python27\pythonw.exe
```

Yields an exception:

```
Traceback (most recent call last):
  File "c:\dev\virtenvs\reports2\Scripts\pyi-grab_version-script.py", line 9, in <module>
    load_entry_point('PyInstaller==2.1', 'console_scripts', 'pyi-grab_version')()
  File "c:\dev\virtenvs\reports2\lib\site-packages\PyInstaller\cliutils\grab_version.py", line 41, in run
    vs = PyInstaller.utils.versioninfo.decode(sys.argv[1])
  File "c:\dev\virtenvs\reports2\lib\site-packages\PyInstaller\utils\versioninfo.py", line 109, in decode
    nm = win32api.EnumResourceNames(h, RESOURCE_TYPE['RT_VERSION'])[0]
IndexError: list index out of range
```

That executable (pythonw.exe) is the 2.7.6 x32 from python.org.

**Comment by pjrobertson** [comment]
I can confirm that I get this error when running grab_version.py on a newly created .exe file (created with PyInstaller).

If I run it on an existing app (e.g. firefox.exe) then it works fine.

**Comment by cztomczak** [comment]
Looks like the reason it fails is because these executables do not have the `VersionInfo` resource embedded. It could display a friendly message though.

It fails on a newly created exe file created with PyInstaller, because by default PyInstaller doesn't embed `VersionInfo` resource.

**Comment by htgoebel** [comment]
Thanks for finding the reason. Would you mind providing a pull-request for the friendly message?

**Comment by cztomczak** [comment]
Sure, I can try. This or next weekend.

**Comment by htgoebel** [comment]
Great :-)

**Comment by cztomczak** [comment]
Created PR: https://github.com/pyinstaller/pyinstaller/pull/2792
