### ISSUE TITLE
`collect_submodules()` fails on hyphenated submodule in 6.8.0

### ISSUE THREAD

**Issue by SnoopJ** [pyinstaller/pyinstaller#8591]
## Description of the issue

I have a build that includes the [`onnx`](https://pypi.org/project/onnx/) library (specifically `onnx==1.11.0`) that succeeds on PyInstaller 6.7 and fails under PyInstaller 6.8.0, specifically due to the inability to import a submodule with a hyphen in its name:

```
Error: Invalid hiddenimport 'onnx.backend.test.case.model.single-relu'. Hidden imports should be importable module names – not file paths. i.e. use --hiddenimport=foo.bar instead of --hiddenimport=.../site-packages/foo/bar.py
```

I took a quick peek at the log between 6.7.0 and 6.8.0 and these commits look like the best culprits (based only on inspection of the commit messages!). Don't have time to run a bisect now, but I might do that later if one of the maintainers doesn't beat me to it:

```
8b5d76d2 Deprecate mixing Python environments using --paths=.../site-packages
a34370fb Make --hiddenimport=.../site-packages/foo/bar.py a build error
1d29b15e Block running PyInstaller from inside C:\Windows
94037335 Dispel the myth that PyInstaller should be ran as an admin
c46cd1e1 archive: update C struct definitions and types of fields
dddf2344 building: on Windows, add parent directory of python.exe to DLL search path
4d6ee33d hookutils: qt: suppress warnings for unavailable Qt bindings packages
fe858d76 building: ensure symbolic links on Windows use backslash separators
042de70c rthook: inspect: normalize path component separator
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.8.0```
* Version of Python: 3.9.14
* Platform: Ubuntu 22.04
* How you installed Python: `pyenv`
* Did you also try this on another platform? Does it work there?:  I haven't tried this on Windows yet, but I suspect it is probably also affected.

### A minimal example program which shows the error

```
$ ~/.pyenv/versions/3.9.14/bin/python3 -m venv venv
$ ./venv/bin/python3 -m pip install "PyInstaller==6.8.0" "onnx==1.11.0"
$ cat scratch.py 
import onnx

print("hello world")
$ # NOTE: the protocol buffers variable below is an ONNX detail that makes this reproducer more portable (no dependency on protoc)
$ PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python ./venv/bin/python3 -m PyInstaller --collect-all=onnx scratch.py
```

### Stacktrace / full error message

```
$ PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python ./venv/bin/python3 -m PyInstaller --collect-all=onnx scratch.py 
127 INFO: PyInstaller: 6.8.0, contrib hooks: 2024.7
127 INFO: Python: 3.9.14
131 INFO: Platform: Linux-6.5.0-26-generic-x86_64-with-glibc2.35
131 INFO: Python environment: /tmp/pyinstaller-repro/venv
131 INFO: wrote /tmp/pyinstaller-repro/scratch.spec
227 WARNING: Failed to collect submodules for 'onnx.backend.test.report' because importing 'onnx.backend.test.report' raised: ModuleNotFoundError: No module named 'pytest'
2258 INFO: Module search paths (PYTHONPATH):
['/tmp/pyinstaller-repro',
 '/opt/pleora/ebus_sdk/Ubuntu-22.04-x86_64/lib',
 '/tmp/pyinstaller-repro',
 '/home/jgerity/.pyenv/versions/3.9.14/lib/python39.zip',
 '/home/jgerity/.pyenv/versions/3.9.14/lib/python3.9',
 '/home/jgerity/.pyenv/versions/3.9.14/lib/python3.9/lib-dynload',
 '/tmp/pyinstaller-repro/venv/lib/python3.9/site-packages',
 '/tmp/pyinstaller-repro']
Error: Invalid hiddenimport 'onnx.backend.test.case.model.single-relu'. Hidden imports should be importable module names – not file paths. i.e. use --hiddenimport=foo.bar instead of --hiddenimport=.../site-packages/foo/bar.py
```

Note that the `pytest` warning is unrelated to the problem, installing the missing modules for `onnx.backend.test` (also includes `tabulate`) resolves the warnings but does not affect the error this report is concerned with.

**Comment by bwoodsend** [comment]
Yeah, that'll be a34370fb. I guess we could relax [the offending regex](https://github.com/pyinstaller/pyinstaller/blob/df1507f9c423eaf6794eee6723d6d09b86da1f3e/PyInstaller/building/build_main.py#L492) to just slashes?

**Comment by SnoopJ** [comment]
Ah, nice. Thanks for the quick response.

Perhaps it makes sense to run the module name through [`packaging.utils.canonicalize_name(name, validate=True)`](https://packaging.pypa.io/en/stable/utils.html#packaging.utils.canonicalize_name) for this purpose?

Edit: probably not, that's for _distributions_ rather than module names. I misremembered the purpose of that mechanism. I was thinking of [name normalization](https://packaging.python.org/en/latest/specifications/name-normalization/) which does the _opposite_ of what I remembered (i.e. it normalizes to `hyphenated-form` rather than `snake_form`)
