### ISSUE TITLE
OSError: Could not find compatible tinycudann extension for compute capability 75.

### ISSUE THREAD

**Issue by ashutoshmishra1014** [pyinstaller/pyinstaller#8592]
I have been following the instructions for packing with pyinstaller as mentioned here:
https://pyarmor.readthedocs.io/en/latest/topic/repack.html

### Description of the issue
Dependent library not bundled properly

### Context information (for bug reports)
Output of pyinstaller --version: 6.7.0
Version of Python: 3.8.16
Output of pyarmor --version: 8.5.7
Platform: Ubuntu 22.04
How you installed Python: conda
Did you also try this on another platform? Does it work there?: I haven't tried this on Windows yet, but I suspect it is probably also affected.

### A minimal example program which shows the error
My application is based on the below project:
https://github.com/nerfstudio-project/nerfstudio

which has as one of the dependencies on the the below package:
https://github.com/NVlabs/tiny-cuda-nn
It is a library with python bindings for cuda kernels for efficient MLPs

```
pyarmor gen -O dist2 -r nerfstudio/train.py nerfstudio/
python dist2/train.py
pyi-makespec --onefile nerfstudio/train.py
pyinstaller train.spec
dist/train
```

My spec file looks like this:
```
# -*- mode: python ; coding: utf-8 -*-
from PyInstaller.utils.hooks import collect_data_files, collect_submodules, copy_metadata
hiddenimports = []
datas = []
datas += copy_metadata('tqdm')
# some other copy_metadata
datas += collect_data_files('wandb', include_py_files=True, includes=['**/vendor/**/*.py'])

# These are imports from vendored stuff in wandb
hiddenimports += collect_submodules('pathtools')
hiddenimports += collect_submodules('tinycudann')


a = Analysis(
    ['nerfstudio/train.py'],
    pathex=[],
    binaries=[],
    datas=datas,
    hiddenimports=hiddenimports,
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)
....
```

### Stacktrace / full error message
I have already added the tinycudann submodule in my spec file but yet when running `dist/train`, I get the below error:
```
    import tinycudann
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "tinycudann/__init__.py", line 9, in <module>
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "tinycudann/modules.py", line 58, in <module>
OSError: Could not find compatible tinycudann extension for compute capability 75.
[1099070] Failed to execute script 'train' due to unhandled exception!
```

**Comment by rokm** [comment]
Judging by [this](https://github.com/NVlabs/tiny-cuda-nn/blob/4892659e015b12bd2fce446b8a8e33e646b21746/bindings/torch/tinycudann/modules.py#L54-L63), you should add `tinycudann_bindings._75_C` to hidden imports as well. 

Maybe try doing `hiddenimports += collect_submodules('tinycudann_bindings')` in the spec to ensure the extensions for all compute capabilities are collected.

**Comment by ashutoshmishra1014** [comment]
Thanks, it worked.

**Comment by ashutoshmishra1014** [comment]
Thanks, it worked.
