### ISSUE TITLE
错误模块名称: ucrtbase.dll，版本: 10.0.18362.387，时间戳: 0x4361b720

### ISSUE THREAD

**Issue by zhengquantao** [pyinstaller/pyinstaller#8603]
I use `pyinstaller -F -w mini-tool.py` can running exe normally on windows10 system， but I use `pyinstaller -F  mini-tool.py` running some time, then exe auto closed。you can help me?   
system event message
```
错误应用程序名称: mini-tool.exe，版本: 0.0.0.0，时间戳: 0x666d4b91
错误模块名称: ucrtbase.dll，版本: 10.0.18362.387，时间戳: 0x4361b720
异常代码: 0xc0000409
错误偏移量: 0x000000000006c4c8
错误进程 ID: 0x3178
错误应用程序启动时间: 0x01dabefb140b23aa
错误应用程序路径: D:\PythonProject\mini_tool_v2\dist\mini-tool.exe
错误模块路径: C:\Windows\System32\ucrtbase.dll
报告 ID: e4c9ce1e-a7d3-4cea-b7cf-7fae51973256
错误程序包全名: 
错误程序包相对应用程序 ID: 
```

**Comment by rokm** [comment]
> you can help me?

Not without knowing what your application is actually doing. If you can provide an example that triggers this error so that we can reproduce it locally, then we can look into it. Otherwise, you're on your own.

**Comment by zhengquantao** [comment]
thanks， i remove scipy.optimize.minimize options params，exe can running normally。maybe options displaying execution details trigger sys.stdout、sys.stderr。 


before
```
optim_result = scipy.optimize.minimize(fun=obj_fun, x0=par_init, method=opt_method, jac=obj_grad, options={'gtol': 1e-6, 'disp': True})
```

after
```
optim_result = scipy.optimize.minimize(fun=obj_fun, x0=par_init, method=opt_method, jac=obj_grad)
```
