### ISSUE TITLE
SyntaxError: invalid or missing encoding declaration when running pyinstaller

### ISSUE THREAD

**Issue by JulienChampagnol** [pyinstaller/pyinstaller#8607]
## Description of the issue
I can't bundle my app on windows environment.
My app is a python package with a script
(see https://github.com/Geode-solutions/GeodeApp-Back/blob/83710d6fccdf493fc695daf9e4d5b872677d4c58/pyproject.toml#L27)
The script is working fine when called by itself, but the pyinstaller command if failing

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.8.0```
* Version of Python: 3.10
* Platform: Windows, french
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? The script works fine on Ubuntu 22.04, with python 3.10 also
I have the same bug in a github action environment with windows
(see https://github.com/Geode-solutions/GeodeApp/actions/runs/9581436803/job/26418238765#step:5:619)

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```
=> Same result

### A minimal example program which shows the error

```
https://github.com/JulienChampagnol/ReproducePyInstallerError/tree/main
```

### Stacktrace / full error message
```
Syntax error in C:\Users\XXX\Desktop\Code\GeodeApp\electron-server\venv_back\Scripts\geodeapp_back.exe
    encoding = find_cookie(first)
   File "C:\Users\XXX\AppData\Local\Programs\Python\Python310\lib\tokenize.py", line 337, in find_cookie
     raise SyntaxError(msg)
 SyntaxError: invalid or missing encoding declaration
```

**Comment by rokm** [comment]
From https://github.com/JulienChampagnol/ReproducePyInstallerError/blob/c2b570ddbe795dbb7a68ec371584a4a6bcf209ed/install.ps1#L13C1-L13C88:
>```
>pyinstaller --onefile --collect-data opengeodeweb_back ./venv/Scripts/geodeapp_back.exe
>``` 


You are trying to run PyInstaller against setuptools-created .exe shim, instead of an actual python script.
