### ISSUE TITLE
Start app on macos with sudo

### ISSUE THREAD

**Issue by Vasa211** [pyinstaller/pyinstaller#8621]
How make .app start with sudo
Now i create all without —windowed and just start in terminal sh:
```
#!/bin/bash
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
RESOURCE_FILE_PATH="$SCRIPT_DIR/main"
sudo "$RESOURCE_FILE_PATH"
```

Its work for me, but i really want make normal .app 😅

I try creating with Platypus but its not working for me too

**Comment by bwoodsend** [comment]
That's never going to happen. For starters, how on earth is sudo supposed to read the password without a TTY to read from?

It makes much more sense for you application to run in regular mode then spawn subprocesses as root -- either using sudo or `osascript -e 'do shell script "your command here" with administrator privileges'`
