### ISSUE TITLE
Scipy generates an ImportError due to circular import

### ISSUE THREAD

**Issue by AlexEdenbach** [pyinstaller/pyinstaller#8631]
Hi all, 
the scipy package seem to generate an ImportError, c.f. the following minimal example using the modules kivy, numpy, and scipy in a virtual environment:

  ```
from kivy.app import App
  from kivy.uix.label import Label
  import numpy as np
  from scipy import linalg
  
  class MainApp(App):
  
      def build(self):
          self.title = 'QUINTO APP'
          a = np.array([[1., 2.], [3., 4.]])
          b =linalg.inv(a)
          return Label(text=f' hello world! \n this is a: {a} \n this is b:{b}')
  
  if __name__ == "__main__":
      MainApp().run()

```
- If I exclude scipy: pyinstaller main.py generates an executable, which works fine
- If I add scipy: pyinstaller main.py generates the following error: **ImportError: cannot import name 'f2py2e' from partially initialized module 'numpy.f2py' (most likely due to a circular import)** 

Well, true- scipy imports numpy as well (e.g. venv/lib/python3.11/site-packages/scipy/_lib/array_api_compat/numpy). How can I solve  this problem?

**Comment by rokm** [comment]
Don't use `numpy` 2.0.0 (and don't use `scipy` 1.14.0) until next PyInstaller release, which will include #8622. See also #8613.

**Comment by AlexEdenbach** [comment]
Hi all, 
I found the solution:
1. add **collect-subnodule** to pyinstaller:
`pyinstaller --collect-submodule=numpy.f2py main.py`

2. Add the following lines to the hook file **hook-scipy.py**  for scipy in .../venv_q/lib/python3.11/site-packages/PyInstaller/hooks:
```
from PyInstaller.utils.hooks import collect_data_files
from PyInstaller.utils.hooks import collect_submodules
hiddenimports = ['scipy._lib.%s' % m for m in ['messagestream', "_ccallback_c", "_fpumode"]]
hiddenimports = collect_submodules('scipy')
datas = collect_data_files('scipy')
```

**Comment by rokm** [comment]
>  I found the solution:

As the song goes: `All his solutions, it seemed, were only problems in disguise...`

If you are going to modify `hook-scipy.py`, you might as well apply the changes from #8622, which avoid brute-force collecting stuff that shouldn't be collected (like `numpy.f2py.tests`)...
