### ISSUE TITLE
ImportError: No module named QtCore

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#864]
**Original date**: 2014/03/07
**Original reporter**: *j DOT kossick AND gmail DOT  COOM *

Hi, I have this small PyQt4 example script:

```
import sys 
from PyQt4 import QtCore, QtGui 

app =QtGui.QApplication(sys.argv) 
window =QtGui.QMainWindow() 
window.setCentralWidget(QtGui.QLabel("Hello")) 
window.show() 
sys.exit(app.exec_()) 
```

When I try to freeze it everything seems to be fine but when I start the frozen application I get following error:

```
Traceback (most recent call last):
  File "<string>", line 36, in <module>
ImportError: No module named QtCore

```

I already tried the --onedir option and added 'PyQt4' to the hiddenimports. Still no success..

**Comment by fth86** [comment]
I am having the same issue, but I am already using the development version of pyinstaller (2.1.1dev-). Is there a newer version - I couldn't find one- or has this issue become unfixed somehow?

**Comment by matysek** [comment]
* Could you try the 'python3' branch?
* And if it does not work then report issue for that branch?

**Comment by fth86** [comment]
Oh, I didn't see that the python 3 branch is supposed to work with python 2.7 as well. It worked. Thank you!

**Comment by matysek** [comment]
> I didn't see that the python 3 branch is supposed to work with python 2.7 as well.

It did not until this week :)

**Comment by Kyson** [comment]
Hi, i have a script :
```
import sys

from PySide.QtGui import QApplication
from PySide.QtGui import QLabel
from PySide.QtGui import QPushButton
from PySide.QtGui import QVBoxLayout
from PySide.QtGui import QWidget


class RmCmdWidget(QWidget):
    def __init__(self):
        QWidget.__init__(self)
        self.status_bar = QLabel()
        self.start_btn = QPushButton("start")
        self.stop_btn = QPushButton("stop")
        self.container = QVBoxLayout()

    def setup(self):
        self.setWindowTitle("Rmcmd")
        self.setMinimumWidth(200)
        self.setMinimumHeight(140)
        self.setMaximumWidth(200)
        self.setMaximumHeight(140)

        self.container = QVBoxLayout()
        self.start_btn.setFixedHeight(40)
        self.stop_btn.setFixedHeight(40)
        self.status_bar.setFixedHeight(20)
        self.container.addWidget(self.start_btn)
        self.container.addWidget(self.stop_btn)
        self.container.addWidget(self.status_bar)
        self.setLayout(self.container)


if __name__ == "__main__":
    print "wtf!!!!!!!!!!!!!!!!!"
    app = QApplication(sys.argv)
    widget = RmCmdWidget()
    widget.setup()
    widget.show()
    app.exec_()
    sys.exit()

```
every run well when debug and package(`pyinstaller test.py`).

but when i run the 'exe' packaged , i got an import error:no module named pyside.*

how can i fix it ? thx :)
