### ISSUE TITLE
An error occurred: ImportError: DLL load failed while importing _ssl

### ISSUE THREAD

**Issue by zqq-nuli** [pyinstaller/pyinstaller#8654]
Thanks for wanting to report an issue you've found in redis-py. Please delete this text and fill in the template below.  
It is of course not always possible to reduce your code to a small test case, but it's highly appreciated to have as much data as possible. Thank you!

**Version**: What redis-py and what redis version is the issue happening on?
(5, 0, 5)
**Platform**: What platform / version? (For example Python 3.5.1 on Windows 7 / Ubuntu 15.10 / Azure)
Python 3.12.2
**Description**: Description of your issue, stack traces from errors and code that reproduces the issue
When running on a device that has not installed openssl, an error will occur

I created a virtual environment with the following command, but I get the same result when I try to package it through a non-virtual environment, I even tried to fall back to version 6.8 and I get the same result

```sh
python -m venv .
```

```sh
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\templates\init.py", line 9, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\templates\xxxxxx.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\model\xxxxxxx.py", line 11, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "src\model\myredis.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "redis\__init__.py", line 3, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "redis\asyncio\__init__.py", line 1, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "redis\asyncio\client.py", line 5, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
  File "ssl.py", line 100, in <module>
ImportError: DLL load failed while importing _ssl: 找不到指定的模块。
```

pyinstaller --version == 6.9.0

I can't pinpoint what the problem is, he's really weird, when I packaged it three days ago, using the same version of pyinstaller, he was working fine, but today I've been trying for three hours, and I've looked at all the relevant issues I can retrieve so far, and none of them have been resolved.

When you use the command line to execute the source code, he is perfectly fine, but once I packaged it to an .exe program, he gets this error, here is the code that minimally reproduces the error.

I can't even catch the error! Be sure to run it on a Windows device that doesn't have openssl installed!

```python

try:
    r = redis.Redis(host="localhost", port=6379, db=0, ssl=False)
    print("Connected to Redis.")
except Exception as e:
    with open("./error.txt", "w", encoding="utf-8") as file:
        file.write(f"Error: {e}")

input("Press Enter to continue...")
```

```sh
pyinstaller .\test.py --onefile
```

**Comment by rokm** [comment]
Are you using anaconda python or python.org python?

See https://github.com/pyinstaller/pyinstaller/issues/7510#issuecomment-1478248109. 

If you can reproduce the problem with simple 

```
import ssl
print(ssl)
```

then upload the build of that test program somewhere so we can take a look at it. (If you cannot, then provide a build of a minimal reproducer, so we can take a look at that instead).

You can also check yourself if `_ssl` extensions and all its dependencies are collected in the frozen application (as well as where they are collected from).

**Comment by zqq-nuli** [comment]
I solved the problem this way, but I still don't know the reason for the problem, so I hope someone will help me out if they can, thank you very much!

[url](https://stackoverflow.com/questions/42563757/conda-update-condahttperror-http-none/60342954#60342954)


```
if running under a virtual env (i.e. your have issued the command: conda activate <env_name>)

The files (libcrypto-1_1-x64.dll and libssl-1_1-x64.dll) to copy are found under: C:\USER<username>.conda\envs<env_name>\Library\bin

They have to be copied into: C:\USER<username>.conda\envs<env_name>\DLLs

```



Because I packaged it a few days ago and still had no problems, but then today this problem suddenly appeared, I don't seem to have touched any of the environment variables, I just installed an extra openssl on my windows

**Comment by zqq-nuli** [comment]
> Are you using anaconda python or python.org python?
> 
> See [#7510 (comment)](https://github.com/pyinstaller/pyinstaller/issues/7510#issuecomment-1478248109).
> 
> If you can reproduce the problem with simple
> 
> ```
> import ssl
> print(ssl)
> ```
> 
> then upload the build of that test program somewhere so we can take a look at it. (If you cannot, then provide a build of a minimal reproducer, so we can take a look at that instead).
> 
> You can also check yourself if `_ssl` extensions and all its dependencies are collected in the frozen application (as well as where they are collected from).


Thank you very much for your help, I think I'm using python.org because I downloaded python 3.12 from python.org, but the way I've solved it above, it looks like I should be using anaconda because I used to run the local big model download of anaconda and maybe that's why I'm confusing the issue!

**Comment by zqq-nuli** [comment]
> Are you using anaconda python or python.org python?
> 
> See [#7510 (comment)](https://github.com/pyinstaller/pyinstaller/issues/7510#issuecomment-1478248109).
> 
> If you can reproduce the problem with simple
> 
> ```
> import ssl
> print(ssl)
> ```
> 
> then upload the build of that test program somewhere so we can take a look at it. (If you cannot, then provide a build of a minimal reproducer, so we can take a look at that instead).
> 
> You can also check yourself if `_ssl` extensions and all its dependencies are collected in the frozen application (as well as where they are collected from).

I can't fix this by just adding _ssl along with ssl, since that's what I did initially

**Comment by rokm** [comment]
We have no way of knowing what python environment(s) you have, and if they are used properly or mixed up, so we cannot really help you.

Can you rebuild with added `--clean` option (to force full rebuild), and paste the full build log here? After that, go to `build\<name>` directory and look for `Analysis-00.toc` file and attach it here as well (or paste its contents). This way, we can perhaps see what is being collected, and from where.
