### ISSUE TITLE
Packaging Error on Macos: Unknown Mach-O header: /opt/homebrew/bin/Accelerate

### ISSUE THREAD

**Issue by kaka1909** [pyinstaller/pyinstaller#8657]
## Description of the issue
When I run `pyinstaller myapp.spec` and I met the error message like:

`ValueError: Unknown Mach-O header: 0x23212f6f in <_io.BufferedReader name='/opt/homebrew/bin/Accelerate'>`

So I am unable to complete my packaging. I logged some and found the binary dependency is collected by libtorch_cpu.dylib when executing the code

```python
logger.debug("Analyzing binary %r", src_name)
        # Analyze imports (linked dependencies)
        for dep_name, dep_src_path in get_imports(src_name, search_paths):
            logger.debug("Processing dependency, name: %r, resolved path: %r", dep_name, dep_src_path)

```
in pyinstaller/depend/bindepend.py  (line # 148 -- # 151)

The full error message shows:

```
37604 DEBUG: Analyzing binary '/opt/homebrew/bin/Accelerate'
Traceback (most recent call last):
  File "~/myapp/.venv/bin/pyinstaller", line 8, in <module>
    sys.exit(_console_script_run())
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 228, in _console_script_run
    run()
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 212, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 69, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1186, in main
    build(specfile, distpath, workpath, clean_build)
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 1126, in build
    exec(code, spec_namespace)
  File "dakar.spec", line 4, in <module>
    a = Analysis(
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 527, in __init__
    self.__postinit__()
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 184, in __postinit__
    self.assemble()
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 894, in assemble
    self.binaries.extend(find_binary_dependencies(self.binaries, collected_packages))
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 282, in find_binary_dependencies
    return bindepend.binary_dependency_analysis(binaries, search_paths=extra_libdirs)
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/depend/bindepend.py", line 150, in binary_dependency_analysis
    for dep_name, dep_src_path in get_imports(src_name, search_paths):
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/depend/bindepend.py", line 242, in get_imports
    return _get_imports_macholib(filename, search_paths)
  File "~/myapp/.venv/lib/python3.10/site-packages/PyInstaller/depend/bindepend.py", line 439, in _get_imports_macholib
    m = MachO(filename)
  File "~/myapp/.venv/lib/python3.10/site-packages/macholib/MachO.py", line 121, in __init__
    self.load(fp)
  File "~/myapp/.venv/lib/python3.10/site-packages/macholib/MachO.py", line 136, in load
    self.load_header(fh, 0, size)
  File "~/myapp/.venv/lib/python3.10/site-packages/macholib/MachO.py", line 170, in load_header
    raise ValueError("Unknown Mach-O header: 0x%08x in %r" % (header, fh))
ValueError: Unknown Mach-O header: 0x23212f6f in <_io.BufferedReader name='/opt/homebrew/bin/Accelerate'>
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.6.0```
* Version of Python: 
* Platform: <! OSX macos 14.5 (23F79) -->
* How you installed Python: <!- homebrew + virtualenv -->
* Did you also try this on another platform? Does it work there? Nope
* My main dependencies:
```
PySide6  -- 6.6.2
torch -- 2.1.0
scipy -- 1.11.3
numpy -- 1.26.4
macholib -- 1.16.3
opencv-python -- 4.10.0.84
ffmpeg-python -- 0.2.0
facenet-pytorch -- 2.5.3
```

Thank you in advance to help me. It really bothers me which I can't proceed my work. T_T

**Comment by rokm** [comment]
Is this on arm64 Mac or x86_64 one?

What kind of file is `/opt/homebrew/bin/Accelerate`? Is it a wrapper shell script? What package did install it, and how come is it being collected in the first place? 

You seem to imply that is is a linked dependency of `libtorch_cpu.dylib` - but that should be linked against `/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate`, not `/opt/homebrew/bin/Accelerate`... 

Can you paste (or attach) the whole build log with `--log-level DEBUG`?

**Comment by kaka1909** [comment]
> Is this on arm64 Mac or x86_64 one?
> 
> What kind of file is `/opt/homebrew/bin/Accelerate`? Is it a wrapper shell script? What package did install it, and how come is it being collected in the first place?
> 
> You seem to imply that is is a linked dependency of `libtorch_cpu.dylib` - but that should be linked against `/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate`, not `/opt/homebrew/bin/Accelerate`...
> 
> Can you paste (or attach) the whole build log with `--log-level DEBUG`?

1. It is Mac ARM64 with M1 chip.
2. /opt/homebrew/bin/Accelerate should be a framework provided by Apple which provide mathematical computations and image calculations, and is optimized for high performance and low energy consumption. This is their doc : https://developer.apple.com/documentation/accelerate.  I do not remember how it is installed before, maybe some dependency requirement... And I found in log:
```
Processing dependency, name: '/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate', resolved path: '/opt/homebrew/bin/Accelerate'
``` 
which leads to the homebrew location

4. OK, I will attach the [wholelog.txt](https://github.com/user-attachments/files/16259078/wholelog.txt).

**Comment by kaka1909** [comment]
here is the log

**Comment by rokm** [comment]
> /opt/homebrew/bin/Accelerate should be a framework provided by Apple which provide mathematical computations and image calculations, and is optimized for high performance and low energy consumption. 

Nope, that's `/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate`.

`/opt/homebrew/bin/Accelerate` is probably called `/opt/homebrew/bin/accelerate`, and is in all likelihood an entry-point script installed by [`accelerate` *python package*](https://pypi.org/project/accelerate/). This is further supported by the error itself: 

> `ValueError: Unknown Mach-O header: 0x23212f6f in <_io.BufferedReader name='/opt/homebrew/bin/Accelerate'>`

because `0x23212f6f` = `#!/o`

You can also open `/opt/homebrew/bin/Accelerate` in text editor, and see what its contents are.

---

> And I found in log:
> `Processing dependency, name: '/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate', resolved path: '/opt/homebrew/bin/Accelerate'`

Yeah, this is what I was after - it looks like there's a bug in our dependency scanner where for some reason we resolve `/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate` into `/opt/homebrew/bin/Accelerate`, which should not happen.

As a work around, you can temporarily rename `/opt/homebrew/bin/Accelerate` to for example `/opt/homebrew/bin/Accelerate-`, and then the build should work.

But I cannot reproduce this switch on my test Mac... So to debug this, can you also try the following:

* run `otool -L /Users/itsme_1/foobar/myproj/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib` and paste the output here
* run `pyi-bindepend /Users/itsme_1/foobar/myproj/.venv/lib/python3.10/site-packages/torch/lib/libtorch_cpu.dylib` and paste the output here
* using the python environment that you use for building, try running the following python snippet:
```python
from macholib.dyld import dyld_find
print(dyld_find('/System/Library/Frameworks/Accelerate.framework/Versions/A/Accelerate'))
```

**Comment by rokm** [comment]
Did you perhaps add `/opt/homebrew/bin` to library search path (for example, by adding it to `DYLD_LIBRARY_PATH` environment variable)? That is one scenario where I can get `dyld_find` to prefer executable/script in bin directory over the original framework name...

What is the output of the `printenv` shell command?

**Comment by kaka1909** [comment]
> Did you perhaps add `/opt/homebrew/bin` to library search path (for example, by adding it to `DYLD_LIBRARY_PATH` environment variable)? That is one scenario where I can get `dyld_find` to prefer executable/script in bin directory over the original framework name...
> 
> What is the output of the `printenv` shell command?

Yes, you give the clue, I modified my DYLD_LIBRARY_PATH, and everything works fine. Thanks a lot!!!
