### ISSUE TITLE
Could not import `pywintypes` or `win32api` from `win32ctypes.pywin32`

### ISSUE THREAD

**Issue by 1234shemingjun** [pyinstaller/pyinstaller#8660]
my interpreter is PyPy3【3.13】 and i use it in Pycharm
so, i installed pyinstaller【6.9.0】 in Pycharm
I try to build my scripts as single package，but this happens：

> Could not import `pywintypes` or `win32api` from `win32ctypes.pywin32`.
> Please make sure that `pywin32-ctypes` is installed and importable, for example:
> 
> pip install pywin32-ctypes

it's strange，beacuse i installed pywin32-ctypes

**Comment by rokm** [comment]
What happens if you run

```
from win32ctypes.pywin32 import pywintypes
from win32ctypes.pywin32 import win32api
```

in your python environment?

> my interpreter is PyPy3【3.13】 and i use it in Pycharm

But either way, we do not support PyPy interpreter, so it is unlikely you will get PyInstaller to work.

**Comment by 1234shemingjun** [comment]
pyinstaller not support PyPy interpreter？
so，which one can support PyPy interpreter？

**Comment by rokm** [comment]
> pyinstaller not support PyPy interpreter？ 

Nope, we support only the original/reference CPython interpreter (www.python.org).

>so，which one can support PyPy interpreter？

No idea, you'll have to look around at alternatives yourself.
