### ISSUE TITLE
    with _open(write_to_parent, "wb") as write_fh:  OSError: [Errno 22] Invalid argument  When using pycharm to wrap my programm

### ISSUE THREAD

**Issue by Chimaco37** [pyinstaller/pyinstaller#8666]
I encountered the below error when i using pyinstaller to wrap my python programme, please take a look, thanks a lot!

(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> pyinstaller --version
6.9.0

(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> python
Python 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.

Platform:
Windows, pycharm

How you installed Python:
pycharm download

(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> pyinstaller Leaf_Phenotyping.py -F                                           
293 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
293 INFO: Python: 3.11.9
296 INFO: Platform: Windows-10-10.0.22631-SP0
296 INFO: Python environment: C:\Users\WANG LAB\Desktop\nuitka\.venv
300 INFO: wrote C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping\Leaf_Phenotyping.spec
300 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Scripts\\pyinstaller.exe',
 'C:\\Users\\WANG '
 'LAB\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\Lib',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\leaf_phenotyping']
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> Traceback (most recent call last):
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 96, in <module>
    while run_next_command(read_fh, write_fh):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 82, in run_next_command
    write_fh.flush()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 92, in <module>
    with _open(write_to_parent, "wb") as write_fh:
OSError: [Errno 22] Invalid argument

**Comment by rokm** [comment]
This looks like the main PyInstaller process died while running some operation using isolated subprocess - since you seem to be getting PS prompt *before* the error traceback from the child process, and there is no traceback for the parent process.

Presumably this happens [here](https://github.com/pyinstaller/pyinstaller/blob/4f15892b9b20a73c2f7c170f61a7db2f07f0b5b8/PyInstaller/building/build_main.py#L507), i.e., the first use of isolated subprocess after [module search paths are printed](https://github.com/pyinstaller/pyinstaller/blob/4f15892b9b20a73c2f7c170f61a7db2f07f0b5b8/PyInstaller/building/build_main.py#L484).

Can you add one `logger.info("something")` call before [L507](https://github.com/pyinstaller/pyinstaller/blob/4f15892b9b20a73c2f7c170f61a7db2f07f0b5b8/PyInstaller/building/build_main.py#L507) in your local copy of PyInstaller and one `logger.info("something")` call after L507 to confirm that this is the case?

Also, can you verify that `PyInstaller.isolated` works if you use it in stand-alone script? I.e., create `test_script.py` with the following contents

```python
# test_script.py
import os
from PyInstaller import isolated

@isolated.decorate
def test_function():
    import os
    print(f"Hello from {os.getpid()}")
    return 12

if __name__ == '__main__':
    print(f"Main process: {os.getpid()}")
    ret = test_function()
    print("Returned value:", ret)
```

and try to run it in your python environment: `python test_script.py`. Does it run successfully or does it raise a similar error?

**Comment by Chimaco37** [comment]
> This looks like the main PyInstaller process died while running some operation using isolated subprocess - since you seem to be getting PS prompt _before_ the error traceback from the child process, and there is no traceback for the parent process.
> 
> Presumably this happens [here](https://github.com/pyinstaller/pyinstaller/blob/4f15892b9b20a73c2f7c170f61a7db2f07f0b5b8/PyInstaller/building/build_main.py#L507), i.e., the first use of isolated subprocess after [module search paths are printed](https://github.com/pyinstaller/pyinstaller/blob/4f15892b9b20a73c2f7c170f61a7db2f07f0b5b8/PyInstaller/building/build_main.py#L484).
> 
> Can you add one `logger.info("something")` call before [L507](https://github.com/pyinstaller/pyinstaller/blob/4f15892b9b20a73c2f7c170f61a7db2f07f0b5b8/PyInstaller/building/build_main.py#L507) in your local copy of PyInstaller and one `logger.info("something")` call after L507 to confirm that this is the case?
> 
> Also, can you verify that `PyInstaller.isolated` works if you use it in stand-alone script? I.e., create `test_script.py` with the following contents
> 
> ```python
> # test_script.py
> import os
> from PyInstaller import isolated
> 
> @isolated.decorate
> def test_function():
>     import os
>     print(f"Hello from {os.getpid()}")
>     return 12
> 
> if __name__ == '__main__':
>     print(f"Main process: {os.getpid()}")
>     ret = test_function()
>     print("Returned value:", ret)
> ```
> 
> and try to run it in your python environment: `python test_script.py`. Does it run successfully or does it raise a similar error?

Hi, based on your advice, i changed my local pyinstaller build_main.py, and try to wrap my programm again, here is the output:
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> pyinstaller Leaf_Phenotyping.py -F                                                                                                                               
172 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
172 INFO: Python: 3.11.9
172 INFO: Platform: Windows-10-10.0.22631-SP0
172 INFO: Python environment: C:\Users\WANG LAB\Desktop\nuitka\.venv
172 INFO: wrote C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping\Leaf_Phenotyping.spec
188 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Scripts\\pyinstaller.exe',
 'C:\\Users\\WANG '
 'LAB\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\Lib',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages',
 'C:\\Users\\WANG '
 'LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\nuitka-2.4rc11-py3.11.egg',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\leaf_phenotyping']
188 INFO: something
345 INFO: something
345 INFO: checking Analysis
345 INFO: Building Analysis because Analysis-00.toc is non existent
345 INFO: Running Analysis Analysis-00.toc
345 INFO: Target bytecode optimization level: 0
345 INFO: Initializing module dependency graph...
345 INFO: Caching module graph hooks...
361 INFO: Analyzing base_library.zip ...
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> Traceback (most recent call last):
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 96, in <module>
    while run_next_command(read_fh, write_fh):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 82, in run_next_command
    write_fh.flush()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 92, in <module>
    with _open(write_to_parent, "wb") as write_fh:
OSError: [Errno 22] Invalid argument


Then i ran the test_script.py as followed:
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> python .\test_script.py
Main process: 13480
Hello from 12092
Returned value: 12

take a look pls, thanks🌹

**Comment by rokm** [comment]
So if you run the build multiple times, it crashes at different points?

**Comment by Chimaco37** [comment]
> So if you run the build multiple times, it crashes at different points?

What the heck.... yes you are right...
I am currently using nuitka to wrap my programme as well, maybe this has some impact on it?
I run the programme multiple times in a row, this is what it output:
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> pyinstaller Leaf_Phenotyping.py -F                                                                                                                               
172 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
172 INFO: Python: 3.11.9
172 INFO: Platform: Windows-10-10.0.22631-SP0
172 INFO: Python environment: C:\Users\WANG LAB\Desktop\nuitka\.venv
172 INFO: wrote C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping\Leaf_Phenotyping.spec
188 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Scripts\\pyinstaller.exe',
 'C:\\Users\\WANG '
 'LAB\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\Lib',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages',
 'C:\\Users\\WANG '
 'LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\nuitka-2.4rc11-py3.11.egg',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\leaf_phenotyping']
188 INFO: something
345 INFO: something
345 INFO: checking Analysis
345 INFO: Building Analysis because Analysis-00.toc is non existent
345 INFO: Running Analysis Analysis-00.toc
345 INFO: Target bytecode optimization level: 0
345 INFO: Initializing module dependency graph...
345 INFO: Caching module graph hooks...
361 INFO: Analyzing base_library.zip ...
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> Traceback (most recent call last):
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 96, in <module>
    while run_next_command(read_fh, write_fh):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 82, in run_next_command
    write_fh.flush()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 92, in <module>
    with _open(write_to_parent, "wb") as write_fh:
OSError: [Errno 22] Invalid argument

(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping>
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> pyinstaller Leaf_Phenotyping.py -F 
567 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
567 INFO: Python: 3.11.9
582 INFO: Platform: Windows-10-10.0.22631-SP0
582 INFO: Python environment: C:\Users\WANG LAB\Desktop\nuitka\.venv
582 INFO: wrote C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping\Leaf_Phenotyping.spec
598 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Scripts\\pyinstaller.exe',
 'C:\\Users\\WANG '
 'LAB\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\Lib',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages',
 'C:\\Users\\WANG '
 'LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\nuitka-2.4rc11-py3.11.egg',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\leaf_phenotyping']
598 INFO: something
1145 INFO: something
1145 INFO: checking Analysis
1145 INFO: Building Analysis because Analysis-00.toc is non existent
1145 INFO: Running Analysis Analysis-00.toc
1145 INFO: Target bytecode optimization level: 0
1145 INFO: Initializing module dependency graph...
1145 INFO: Caching module graph hooks...
1177 INFO: Analyzing base_library.zip ...
3307 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
3448 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> Traceback (most recent call last):
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 96, in <module>
    while run_next_command(read_fh, write_fh):
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 82, in run_next_command
    write_fh.flush()
OSError: [Errno 22] Invalid argument

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\WANG LAB\Desktop\nuitka\.venv\Lib\site-packages\PyInstaller\isolated\_child.py", line 92, in <module>
    with _open(write_to_parent, "wb") as write_fh:
OSError: [Errno 22] Invalid argument

(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> pyinstaller Leaf_Phenotyping.py -F 
541 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
541 INFO: Python: 3.11.9
556 INFO: Platform: Windows-10-10.0.22631-SP0
556 INFO: Python environment: C:\Users\WANG LAB\Desktop\nuitka\.venv
556 INFO: wrote C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping\Leaf_Phenotyping.spec
572 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Scripts\\pyinstaller.exe',
 'C:\\Users\\WANG '
 'LAB\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\Lib',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages',
 'C:\\Users\\WANG '
 'LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\nuitka-2.4rc11-py3.11.egg',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\leaf_phenotyping']
572 INFO: something
1166 INFO: something
1166 INFO: checking Analysis
1166 INFO: Building Analysis because Analysis-00.toc is non existent
1166 INFO: Running Analysis Analysis-00.toc
1166 INFO: Target bytecode optimization level: 0
1166 INFO: Initializing module dependency graph...
1182 INFO: Caching module graph hooks...
1198 INFO: Analyzing base_library.zip ...
(.venv) PS C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping> pyinstaller Leaf_Phenotyping.py -F 
563 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7
563 INFO: Python: 3.11.9
563 INFO: Platform: Windows-10-10.0.22631-SP0
579 INFO: Python environment: C:\Users\WANG LAB\Desktop\nuitka\.venv
579 INFO: wrote C:\Users\WANG LAB\Desktop\nuitka\leaf_phenotyping\Leaf_Phenotyping.spec
579 INFO: Module search paths (PYTHONPATH):
['C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Scripts\\pyinstaller.exe',
 'C:\\Users\\WANG '
 'LAB\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311\\Lib',
 'C:\\Users\\WANG LAB\\AppData\\Local\\Programs\\Python\\Python311',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages',
 'C:\\Users\\WANG '
 'LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\nuitka-2.4rc11-py3.11.egg',
 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\leaf_phenotyping']
579 INFO: something
1158 INFO: something
1158 INFO: checking Analysis
1158 INFO: Building Analysis because Analysis-00.toc is non existent
1158 INFO: Running Analysis Analysis-00.toc
1158 INFO: Target bytecode optimization level: 0
1158 INFO: Initializing module dependency graph...
1158 INFO: Caching module graph hooks...
1173 INFO: Analyzing base_library.zip ...
3051 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...
4303 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\WANG LAB\\Desktop\\nuitka\\.venv\\Lib\\site-packages\\PyInstaller\\hooks'...

I'll try again when nuitka programme ended, but I was wondering why is this happening?

**Comment by rokm** [comment]
> I'll try again when nuitka programme ended, but I was wondering why is this happening?

No idea, sorry. Like I said, best I can guess from these logs is that the parent (main) PyInstaller process dies for some reason.

If you are running a nuitka build in parallel, are you maybe running low on system resources (RAM or disk)?

Maybe try with a minimal python environment, where you install just PyInstaller, and freeze a simple `print("hello world")` program,  to see if that works...

**Comment by Chimaco37** [comment]
> > I'll try again when nuitka programme ended, but I was wondering why is this happening?
> 
> No idea, sorry. Like I said, best I can guess from these logs is that the parent (main) PyInstaller process dies for some reason.
> 
> If you are running a nuitka build in parallel, are you maybe running low on system resources (RAM or disk)?
> 
> Maybe try with a minimal python environment, where you install just PyInstaller, and freeze a simple `print("hello world")` program, to see if that works...

Indeed, it should be only low RAM left this time, I'll try your advice later, if anything useful, i'll update.

**Comment by Chimaco37** [comment]
> > I'll try again when nuitka programme ended, but I was wondering why is this happening?
> 
> No idea, sorry. Like I said, best I can guess from these logs is that the parent (main) PyInstaller process dies for some reason.
> 
> If you are running a nuitka build in parallel, are you maybe running low on system resources (RAM or disk)?
> 
> Maybe try with a minimal python environment, where you install just PyInstaller, and freeze a simple `print("hello world")` program, to see if that works...

I think i know what's going on, i created a minimal python environment and do what you advised, and it output the same thing, even i run some pip install pyinstaller it will end and output nothing, then i closed a protection software running on my PC, when i close it everything's fine. Thanks a lot bro ❀
