### ISSUE TITLE
Better porting

### ISSUE THREAD

**Issue by hackpro4005** [pyinstaller/pyinstaller#8675]
I think that it should be possible with an option to make a linux binary on windows or the other way around

**Comment by rokm** [comment]
PyInstaller is collecting binaries (the python shared library, binary python extensions, and their dependencies) from the python environment it is running in. So it is impossible to create linux binary using Windows python environment and vice versa, as environment contains only binaries for its OS.

If you want to build for a different platform, you need to run its native python environment in some way (e.g., Windows python environment under wine on linux, linux python environment under WSL or in docker containers on Windows).
