### ISSUE TITLE
pyinstaller bundles apps with gdal

### ISSUE THREAD

**Issue by obladlee** [pyinstaller/pyinstaller#8684]
l make an app with pyside6 and gdal，which to read geospatial data like shapefile or filegeodatabase.
My environment：
- python=3.10.13
- pyside6.7
- gdal3.9.1
- pyinstaller6.9

It works well on vscode before bundling.
l success to bundle  my app. When executing app, the gdal failed to read some files, but some success. No error outputs although l use the try execpt to catch error.
l wonder is pyinstaller supported gdal? 
Below is my build log:

1006 INFO: PyInstaller: 6.9.0, contrib hooks: 2024.7                                                        
1007 INFO: Python: 3.10.13 (conda)
1020 INFO: Platform: Windows-10-10.0.19045-SP0
1020 INFO: Python environment: E:\ProgramData\anaconda3\envs\datasearch310
1021 INFO: wrote E:\vs_code\Arcpy\arcpy\datasearch\GeoSpatialMeatadata.spec
2188 INFO: Module search paths (PYTHONPATH):
['E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Scripts',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\python310.zip',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\DLLs',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\win32',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\win32\\lib',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\Pythonwin',
 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\setuptools\\_vendor',
 'E:\\vs_code\\Arcpy\\arcpy\\datasearch',
 'E:\\vs_code\\Arcpy\\arcpy\\datasearch']
2535 INFO: Appending 'datas' from .spec
2543 INFO: checking Analysis
2573 INFO: Building because E:\vs_code\Arcpy\arcpy\datasearch\gdalreader.py changed
2573 INFO: Running Analysis Analysis-00.toc
2573 INFO: Target bytecode optimization level: 0
2574 INFO: Initializing module dependency graph...
2575 INFO: Caching module graph hooks...
2602 INFO: Analyzing base_library.zip ...
4947 INFO: Loading module hook 'hook-heapq.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
5072 INFO: Loading module hook 'hook-encodings.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
7779 INFO: Loading module hook 'hook-pickle.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
9605 INFO: Caching module dependency graph...
9863 INFO: Looking for Python shared library...
9876 INFO: Using Python shared library: E:\ProgramData\anaconda3\envs\datasearch310\python310.dll
9877 INFO: Analyzing E:\vs_code\Arcpy\arcpy\datasearch\main.py
9891 INFO: Loading module hook 'hook-PySide6.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
10129 INFO: Loading module hook 'hook-shiboken6.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
10161 INFO: Loading module hook 'hook-PySide6.QtNetwork.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
10728 INFO: Loading module hook 'hook-PySide6.QtWidgets.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
11000 INFO: Loading module hook 'hook-PySide6.QtCore.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
11301 INFO: Loading module hook 'hook-PySide6.QtGui.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
11991 INFO: Loading module hook 'hook-osgeo.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
12639 INFO: Loading module hook 'hook-platform.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
12670 INFO: Loading module hook 'hook-numpy.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Lib\\site-packages\\numpy\\_pyinstaller'...
13359 INFO: Loading module hook 'hook-sysconfig.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
14829 INFO: Loading module hook 'hook-difflib.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
15137 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
15249 INFO: Loading module hook 'hook-xml.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
17196 INFO: Loading module hook 'hook-jinja2.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
17914 INFO: Analyzing hidden import 'osgeo.gdalnumeric'
17916 INFO: Processing module hooks...
18002 INFO: Performing binary vs. data reclassification (375 entries)
18240 INFO: Looking for ctypes DLLs
18242 WARNING: Ignoring ./Everything64.dll imported from E:\vs_code\Arcpy\arcpy\datasearch\search.py - only basenames are supported with ctypes imports!
18254 INFO: Analyzing run-time hooks ...
18260 INFO: Including run-time hook 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
18263 INFO: Including run-time hook 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
18268 INFO: Processing pre-find module path hook _pyi_rth_utils from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-_pyi_rth_utils.py'.
18271 INFO: Loading module hook 'hook-_pyi_rth_utils.py' from 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks'...
18272 INFO: Including run-time hook 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'     
18277 INFO: Including run-time hook 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\rthooks\\pyi_rth_osgeo.py'18280 INFO: Including run-time hook 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pyside6.py'
18321 INFO: Looking for dynamic libraries
19024 INFO: Extra DLL search directories (AddDllDirectory): ['E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Lib\\site-packages\\shiboken6', 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin']
19025 INFO: Extra DLL search directories (PATH): ['E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Lib\\site-packages\\PySide6']
24742 WARNING: Library not found: could not resolve 'pgc.dll', dependency of 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin\\mkl_pgi_thread.2.dll'.
24743 WARNING: Library not found: could not resolve 'pgf90.dll', dependency of 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin\\mkl_pgi_thread.2.dll'.
24744 WARNING: Library not found: could not resolve 'pgmath.dll', dependency of 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin\\mkl_pgi_thread.2.dll'. 
24744 WARNING: Library not found: could not resolve 'ur_loader.dll', dependency of 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin\\omptarget.rtl.unified_runtime.dll'.
24745 WARNING: Library not found: could not resolve 'msmpi.dll', dependency of 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin\\mkl_blacs_msmpi_lp64.2.dll'.
24746 WARNING: Library not found: could not resolve 'impi.dll', dependency of 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin\\mkl_blacs_intelmpi_ilp64.2.dll'.
24747 WARNING: Library not found: could not resolve 'impi.dll', dependency of 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin\\mkl_blacs_intelmpi_lp64.2.dll'.
24747 WARNING: Library not found: could not resolve 'msmpi.dll', dependency of 'E:\\ProgramData\\anaconda3\\envs\\datasearch310\\Library\\bin\\mkl_blacs_msmpi_ilp64.2.dll'.
24825 INFO: Warnings written to E:\vs_code\Arcpy\arcpy\datasearch\build\GeoSpatialMeatadata\warn-GeoSpatialMeatadata.txt
24996 INFO: checking PYZ
25005 INFO: Building because E:\vs_code\Arcpy\arcpy\datasearch\gdalreader.py changed
25006 INFO: Building PYZ (ZlibArchive) E:\vs_code\Arcpy\arcpy\datasearch\build\GeoSpatialMeatadata\PYZ-00.pyz
26536 INFO: Building PYZ (ZlibArchive) E:\vs_code\Arcpy\arcpy\datasearch\build\GeoSpatialMeatadata\PYZ-00.pyz completed successfully.
26591 INFO: checking PKG
26599 INFO: Building because toc changed
26600 INFO: Building PKG (CArchive) GeoSpatialMeatadata.pkg
157606 INFO: Building PKG (CArchive) GeoSpatialMeatadata.pkg completed successfully.
157633 INFO: Bootloader E:\ProgramData\anaconda3\envs\datasearch310\lib\site-packages\PyInstaller\bootloader\Windows-64bit-intel\runw.exe
157634 INFO: checking EXE
157646 INFO: Building because toc changed
157646 INFO: Building EXE from EXE-00.toc
157678 INFO: Copying bootloader EXE to E:\vs_code\Arcpy\arcpy\datasearch\dist\GeoSpatialMeatadata.exe
157683 INFO: Copying icon to EXE
157688 INFO: Copying 0 resources to EXE
157688 INFO: Embedding manifest in EXE
157692 INFO: Appending PKG archive to EXE
157928 INFO: Fixing EXE headers
159318 INFO: Building EXE from EXE-00.toc completed successfully.

**Comment by rokm** [comment]
>  No error outputs although l use the try execpt to catch error.

What do you do with those caught errors?

**Comment by obladlee** [comment]
> > No error outputs although l use the try execpt to catch error.
> 
> What do you do with those caught errors?

output log file using logging.
here is code snippet to read file with gdal
`def read_metadata(self):

        """
        Reads metadata from the file.
        Yields:
            dict: A dictionary containing metadata information.
        """
        try:
             if self.datasource is None: ...
             metadata = {...}
             for layer_index in range(self.datasource.GetLayerCount()): ....
             ......
        except Exception as e:
            logging.error(f" error reading file: {self.file_path}")
            logging.error(e)`

**Comment by rokm** [comment]
Does the log file get created at all? Does it contain anything?

Try making a console-enabled build (remove `--windowed` / `--noconsole` flags from your PyInstaller command), and try running the program from command prompt. So you can see if it dumps any additional clues into stderr/stdout.

**Comment by obladlee** [comment]
> Does the log file get created at all? Does it contain anything?
> 
> Try making a console-enabled build (remove `--windowed` / `--noconsole` flags from your PyInstaller command), and try running the program from command prompt. So you can see if it dumps any additional clues into stderr/stdout.

log file created. It prints "error reading file: filepath", but exception is null, which made me clueless.
l would try your way.Thank you！

**Comment by rokm** [comment]
Try replacing

```
        logging.error(f" error reading file: {self.file_path}")
        logging.error(e)
```

with 

```
        logging.error(f" error reading file: {self.file_path}", exc_info=True)
```

That should print the full exception info, instead of just its message.

**Comment by rokm** [comment]
But if you are having trouble reading a file, two common causes of errors are:
- file not being collected into frozen application (if it is supposed to be bundled with the application, you need to ensure that it is collected; this does not happen automatically)
- trying to load the file via relative path instead of [absolute one anchored to `__file__` attribute](https://pyinstaller.org/en/stable/runtime-information.html#using-file)

**Comment by obladlee** [comment]
> But if you are having trouble reading a file, two common causes of errors are:
> 
> * file not being collected into frozen application (if it is supposed to be bundled with the application, you need to ensure that it is collected; this does not happen automatically)
> * trying to load the file via relative path instead of [absolute one anchored to `__file__` attribute](https://pyinstaller.org/en/stable/runtime-information.html#using-file)
Thanks for your advice.
l catched the error,
 it is "File "osgeo\ogr.py", line 2149, in GetSpatialRef   return _ogr.Layer_GetSpatialRef(self, *args)  RuntimeError".
lt is about gdal , not fault of pyinstaller.
l find solution in this issue https://github.com/OSGeo/gdal/issues/990
l defined the USE_OSR_FIND_MATCHES=NO environment variable with gdal. lt works!

**Comment by obladlee** [comment]
Thanks for your advice.
l catched the error,
it is "File "osgeo\ogr.py", line 2149, in GetSpatialRef return _ogr.Layer_GetSpatialRef(self, *args) RuntimeError".
lt is about gdal , not fault of pyinstaller.
l find solution in this issue https://github.com/OSGeo/gdal/issues/990
l defined the USE_OSR_FIND_MATCHES=NO environment variable with gdal. lt works!
