### ISSUE TITLE
PyZMQ error when bundling multipackage in one-file mode

### ISSUE THREAD

**Issue by MattTheCuber** [pyinstaller/pyinstaller#8687]
## Description of the issue

I created an application then when packaging multiple executables importing PyZMQ in one-file throws the error `Dependency pyzmq.libs\msvcp140-587ef1e98d22156d27ef55ba57e44cb3.dll not found in the referenced dependency archive.`

I followed the guide almost exactly from here: https://pyinstaller.org/en/latest/spec-files.html#example-merge-spec-file. The only change I made was adding `--onefile` to the `pyi-makespec` commands, and putting `import zmq` in each Python script. See the minimal example below.

Similar issue: https://github.com/pyinstaller/pyinstaller/issues/5510

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.9.0```
* Version of Python: 3.11.9
* Platform: Windows 10
* How you installed Python: Windows store
* Did you also try this on another platform? Does it work there? I did not.

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

#### Commands
1. `pyinstaller foobar.spec` - no errors.
2. `.\dist\foo.exe` - no errors
3. `.\dist\bar.exe` - throws `Dependency pyzmq.libs\msvcp140-587ef1e98d22156d27ef55ba57e44cb3.dll not found in the referenced dependency archive.` error

#### foo.py
```python
import zmq

print("foo")
```

#### bar.py
```python
import zmq

print("bar")
```

#### foobar.spec
```python
# -*- mode: python ; coding: utf-8 -*-

foo_a = Analysis(["foo.py"])

bar_a = Analysis(["bar.py"])

MERGE((foo_a, "foo", "foo"), (bar_a, "bar", "bar"))

foo_pyz = PYZ(foo_a.pure)
foo_exe = EXE(
    foo_pyz,
    foo_a.dependencies,
    foo_a.scripts,
    foo_a.binaries,
    foo_a.datas,
    [],
    name="foo",
    debug=False,
    upx=True,
)

bar_pyz = PYZ(bar_a.pure)
bar_exe = EXE(
    bar_pyz,
    bar_a.dependencies,
    bar_a.scripts,
    bar_a.binaries,
    bar_a.datas,
    [],
    name="bar",
    debug=False,
    upx=True,
)
```

### Stacktrace / full error message

```
[26672] Dependency pyzmq.libs\msvcp140-587ef1e98d22156d27ef55ba57e44cb3.dll not found in the referenced dependency archive.
[26672] Failed to extract entry: foo:pyzmq.libs\msvcp140-587ef1e98d22156d27ef55ba57e44cb3.dll.
```

**Comment by rokm** [comment]
Hmm, looks like that `msvcp140-587ef1e98d22156d27ef55ba57e44cb3.dll` is collected twice; once in `pyzmq.libs\msvcp140-587ef1e98d22156d27ef55ba57e44cb3.dll` (the correct location) and once in top-level directory, which is an issue in itself (probably because the hook was written when PyInstaller was always collecting shared libs into top-level directory). Looks like this duplication is tripping up MERGE as well.

I'll have to take a closer look at the MERGE itself, but you can eliminate the underlying issue by finding your local copy of `hook-zqm` (should be in `site-packages/_pyinstaller-hooks-contrib/hooks/stdhooks` and change [the last line](https://github.com/pyinstaller/pyinstaller-hooks-contrib/blob/master/_pyinstaller_hooks_contrib/stdhooks/hook-zmq.py#L63) from

```python
    binaries += [(dll_file, '.') for dll_file in dll_files]
```

to

```python
    binaries += [(dll_file, 'pyzmq.libs') for dll_file in dll_files]
```

**Comment by MattTheCuber** [comment]
That temporary workaround fixed my problem. Thanks!
