### ISSUE TITLE
All background processes have name MainProcess

### ISSUE THREAD

**Issue by nup002** [pyinstaller/pyinstaller#8689]
## Description of the issue
All background processes launched with multiprocessing.Pool have the name 'MainProcess', despite using `multiprocessing.freeze()`.

Repro steps with `main.py` minimal example program below:
```
conda create --name myenv python=3.11
conda activate myenv
conda install pyinstaller
pyinstaller main.py
dist\main\main.exe
```

Expected output:
```
main.py:4: UserWarning: Process name: MainProcess
main.py:4: UserWarning: Process name: SpawnPoolWorker-1
```

Actual output:
```
main.py:4: UserWarning: Process name: MainProcess
main.py:4: UserWarning: Process name: MainProcess
```

## Why is this a problem?
I use the process name to decide whether to display the Splashscreen, as follows:
```
if getattr(sys, 'frozen', False) and current_process().name == 'MainProcess':
    try:
        import pyi_splash
    except Exception as error:
        pass
```
When all background processes are named `MainProcess`, the splashscreen is displayed every time a background process launches.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.9.0``` (also tested on 6.8.0 and 6.0.0)
* Version of Python: Tested on 3.11 and 3.10
* Platform: Windows (English)
* How you installed Python: Conda
* Only tested on Windows

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error
`main.py`
```
from time import time
from warnings import warn
from multiprocessing import freeze_support, Pool, current_process
warn(f"Process name: {current_process().name}")


def main():
    with Pool(1) as pool:   # Create pool
        tick = time()
        while time() - tick < 1:  # Keep pool alive for 1 second 
            pass


if __name__ == "__main__":
    freeze_support()
    main()
```

**Comment by rokm** [comment]
> I use the process name to decide whether to display the Splashscreen, as follows:

While the process name is an issue we should look into, you are operating under misconception that you(r code) get(s) to decide whether to show splash screen or not. The decision is made by the bootloader, regardless of whether you import `pyi_splash` in your code or not. And there's been a longstanding issue with splash screen being shown by spawned subprocesses that (re)use `sys.executable` (spawned via `multiprocessing` or manually via `subprocess`), e.g., #7121. This is hopefully addressed by #8634.

**Comment by nup002** [comment]
Thank you for the rapid reply. I look forward to #8634 making it into a release. Until then, is there a current hack/workaround to the issue of splashcreens being shown by spawned subprocesses?

**Comment by rokm** [comment]
> Until then, is there a current hack/workaround to the issue of splashcreens being shown by spawned subprocesses?

Unfortunately, there is none that I can think of.

**Comment by rokm** [comment]
The process name is actually not an issue, either: at the point where it is queried in the original example, we are still in the "common" part of the entry point. Only when `freeze_support` is called and the program flow in the worker process gets diverted into `multiprocessing` code, it gets renamed (by the said `multiprocessing` code).

Consider the following example:

```python
import os
import sys
from multiprocessing import freeze_support, Pool, current_process

print(f"pid-{os.getpid()}: args: {sys.argv}")
print(f"pid-{os.getpid()}: process name: {current_process().name}")


def f(x):
    print(f"pid-{os.getpid()}: process name inside worker: {current_process().name}")
    return x * x


def main():
    with Pool(1) as pool:   # Create pool
        pool.map(f, [1])


if __name__ == "__main__":
    freeze_support()
    main()
```
and its output when run frozen:

```
pid-2276: args: ['dist\\program\\program.exe']
pid-2276: process name: MainProcess
pid-9512: args: ['C:\\Users\\Rok\\Development\\pyi-multiprocess\\dist\\program\\program.exe', '--multiprocessing-fork', 'parent_pid=2276', 'pipe_handle=564']
pid-9512: process name: MainProcess
pid-9512: process name inside worker: SpawnPoolWorker-1
```

In the worker process (9512), the process name is "MainProcess" before the program flow is diverted by `freeze_support`, and afterwards, it is correctly named `SpawnPoolWorker-1`. That's why [our docs](https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#when-to-call-multiprocessing-freeze-support) suggest that you might want to call `freeze_support` as soon as possible - because they should not be executing any more code of your entry-point than necessary. Although that is unrelated to the issue with splash screen and subprocesses.
