### ISSUE TITLE
WARNING:failed to remove temporary directory: C:\users\x\AppData\Local\Temp\_MEI396362

### ISSUE THREAD

**Issue by zouzhe1** [pyinstaller/pyinstaller#8701]
# 1，problem

WARNING:failed to remove temporary directory: C:\users\x\AppData\Local\Temp\_MEI396362

![image](https://github.com/user-attachments/assets/09e7ef6c-e368-4606-a85d-75b6bffc8e45)

## note：
When I use Splash, closing the exe program results in this error popping up.

If I do not use Splash, then this issue does not occur.

# 2，code
## spec
```
splash = Splash('image.png',
                binaries=a.binaries,
                datas=a.datas,
                text_pos=(10, 50),
                text_size=12,
                text_color='black')
exe = EXE(pyz,
          a.scripts,
          splash,                   # <-- both, splash target
          splash.binaries,          # <-- and splash binaries
          ...)
```
## python
main.py
```
import pyi_splash
pyi_splash.close()
```

---
# 3，environment
win10  
python3.8.13
pyinstaller-6.9.0
pyinstaller_hooks_contrib-2024.7.dist-info

**Comment by rokm** [comment]
This sounds like the same issue as in follow-up to #7106 (from https://github.com/pyinstaller/pyinstaller/issues/7106#issuecomment-2219639908 on). If your anti-virus program injects other DLLs into the process that depend on `VCRUNTIME140.dll`, then we fail to unload the bundled copy of the DLL and consequently fail to remove it from the temporary directory (and the temporary directory itself). 

I've added a work around for that (https://github.com/pyinstaller/pyinstaller/pull/8650), which should be part of the next release.

Can you check what files are left in the temporary directory after we fail to remove it?

**Comment by zouzhe1** [comment]
@rokm   thank for your reply. My file only have a VCRUNTIME140.dll,no other file.

**Comment by yk616** [comment]
I also met this problem. My environment is python-3.9.0 with pyinstaller-6.10.0. Here is my code `test.py:`
```
import os
import sys
import tkinter as tk

if hasattr(sys, "_MEIPASS"):
    import pyi_splash
    pyi_splash.close()


def restart():
    os.execl(sys.executable, sys.executable, *sys.argv)
    exit()


root = tk.Tk()

button = tk.Button(root, text="restart", command=restart)
button.pack()

root.mainloop()
```
command: `pyinstaller test.py -Fw --splash test.png`
When I restart my program, this issue will occur.

**Comment by rokm** [comment]
>  When I restart my program, this issue will occur.

Yeah, that's expected with v6.10.

See 
https://pyinstaller.org/en/v6.10.0/CHANGES.html#incompatible-changes
and
https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#using-sys-executable-to-spawn-subprocesses-that-outlive-the-application-process-implementing-application-restart

**Comment by yk616** [comment]
I modified my code:
```
def restart():
    os.environ["PYINSTALLER_RESET_ENVIRONMENT"] = "1"
    os.execl(sys.executable, sys.executable, *sys.argv)
    exit()
```
However, this problem still exists.

**Comment by rokm** [comment]
> However, this problem still exists.

Hmm, indeed. And again, only with splash screen enabled.

I suspect this is side effect of https://github.com/pyinstaller/pyinstaller/pull/8650 - the (re)spawned process tries to preload system copy of VCRUNTIME140.dll, but because the original/parent process called `SetDllDirectory()` on its _MEIPASS directory (and this is inherited by children), we end up loading the DLL from original _MEIPASS and block its deletion.

Let's see if calling `SetDllDirectory(NULL)` when we reset environment helps...

**Comment by rokm** [comment]
@yk616 If you know how to rebuild the bootloader, you can try adding
```c
SetDllDirectoryW(NULL);
```
*before* this line
https://github.com/pyinstaller/pyinstaller/blob/88e0cb5697bde00a3c358df1f5353659a8d23354/bootloader/src/pyi_main.c#L398. 
It should fix the problem.

**Comment by yk616** [comment]
> It should fix the problem.

Thank you for your reply. I don't know how to rebuild bootloader, so I'll wait for the next update.
