### ISSUE TITLE
Compile for main.pyd

### ISSUE THREAD

**Issue by joseph16388** [pyinstaller/pyinstaller#8704]
Hello！
       I used easycython to compile main.py to main.pyd and then wrote a py script and use（from main import XXX） to run the program successfully. But Pyinstaller does not compile for this change. So How can I tell the Pyinstaller program that main.pyd exists?
thanks！

**Comment by rokm** [comment]
The entry point script must be a .py script - it cannot be a binary extension. As a work-around, you can create a .py file that loads and runs the main() function from the .pyd. EDIT: I missed the part where you said you already did that. What exactly does not work?

**Comment by rokm** [comment]
But then you will probably need to add all imports made by `main.pyd` are added to hidden imports, because PyInstaller cannot analyze imports made from binary extensions.

**Comment by joseph16388** [comment]
> The entry point script must be a .py script - it cannot be a binary extension. As a work-around, you can create a .py file that loads and runs the main() function from the .pyd. EDIT: I missed the part where you said you already did that. What exactly does not work?

yes, i created a .py file that loads and runs the main() function from the .pyd,thanks

**Comment by rokm** [comment]
> > The entry point script must be a .py script - it cannot be a binary extension. As a work-around, you can create a .py file that loads and runs the main() function from the .pyd. EDIT: I missed the part where you said you already did that. What exactly does not work?
> 
> yes, i created a .py file that loads and runs the main() function from the .pyd,thanks

So what exactly does "But Pyinstaller does not compile for this change."  mean, then? Is your `main.py` file collected into PYZ because it shadows `main.pyd` in the same directory?

**Comment by joseph16388** [comment]
> > > The entry point script must be a .py script - it cannot be a binary extension. As a work-around, you can create a .py file that loads and runs the main() function from the .pyd. EDIT: I missed the part where you said you already did that. What exactly does not work?
> > 
> > 
> > yes, i created a .py file that loads and runs the main() function from the .pyd,thanks
> 
> So what exactly does "But Pyinstaller does not compile for this change." mean, then? Is your `main.py` file collected into PYZ because it shadows `main.pyd` in the same directory?

this change means that main.py be compiled to main.pyd.Anyway, now that I've added hidden-import, I can compile it，thanks
