### ISSUE TITLE
Pyinstaller created exe doesn't work with urllib3 and requests

### ISSUE THREAD

**Issue by baseplate-admin** [pyinstaller/pyinstaller#8706]
## Description of the issue

When i open an  exe created by pyinstaller, it raises this error.
```python
Can't connect to HTTPS URL because the SSL module is not available.
```

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.9.0```
* Version of Python: 3.12.4
* Platform: Windows/11
* How you installed Python: python.org
* Did you also try this on another platform? Does it work there? : No, didn't test on anything except windows

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
# t.py
import requests

requests.get('https://google.com')
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "t.py", line 4, in <module>
  File "requests\api.py", line 73, in get
  File "requests\api.py", line 59, in request
  File "requests\sessions.py", line 589, in request
  File "requests\sessions.py", line 703, in send
  File "requests\adapters.py", line 667, in send
  File "urllib3\connectionpool.py", line 768, in urlopen
  File "urllib3\connectionpool.py", line 294, in _get_conn
  File "urllib3\connectionpool.py", line 1059, in _new_conn
ImportError: Can't connect to HTTPS URL because the SSL module is not available.
[32248] Failed to execute script 't' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by rokm** [comment]
It works as expected for me. Can you try with clean virtual environment with only `requests` installed and `PyInstaller` installed? (And build with added `--clean` option to eliminate any caching issues). If it raises the same error, please copy and paste the full build log.

**Comment by baseplate-admin** [comment]
i have found the issue.

```python 
# -*- mode: python ; coding: utf-8 -*-


a = Analysis(
    ['src\\shiinobi\\cli.py'],
    pathex=['src\\shiinobi'],
    binaries=[],
    datas=[],
    hiddenimports=['selectolax'],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='__main__',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False, ############ <----------------- Setting strip=True causes issue
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
```

So Setting strip=True caused this issue

**Comment by rokm** [comment]
> So Setting strip=True causes this issue

Yeah, wouldn't be surprised. What `strip` utility do you have in your `PATH` on Windows, anyway? The one from mingw/msys?

**Comment by baseplate-admin** [comment]
> The one from mingw/msys?

Very likely yes.

**Comment by baseplate-admin** [comment]
Sorry for the noise, i didn't realize it was my fault. 

Should i close this issue?
