### ISSUE TITLE
Unable to disable frozen modules

### ISSUE THREAD

**Issue by mpelzsherman** [pyinstaller/pyinstaller#8710]
I am getting errors like the following in my project:

```
    mod_dir = os.path.dirname(hooks.get_module_file_attribute(mod_name))
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen ntpath>", line 277, in dirname
  File "<frozen ntpath>", line 241, in split
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

These errors only occur on Windows, and my research indicates they might be due to the use of python's "frozen modules".

I am trying to disable frozen modules by passing the `-X frozen_modules=off` flag to the Python interpreter.
But so far I haven't found a way to do this.

Does anyone know:
1. Is my theory correct that disabling frozen modules likely to fix this problem?, and
2. How can I do it?

Many thanks for your help!

**Comment by rokm** [comment]
Is this raised by `Django` hook? In that case, it is unlikely that frozen modules are a problem, and more likely that `mod_name` refers to a namespace package instead of module or "classic" package.

**Comment by rokm** [comment]
Try adding a `print(mod_name)` in before the line that raises the error in your local copy of the hook, to see what package is causing the problem. If it is one from your own codebase, then as a work-around, you can add an empty `__init__.py` file into it, and it should work.
