### ISSUE TITLE
Cannot open PyInstaller archive from executable (C:\Users\wwy\TestPlugin.exe) or external archive (C:\Users\wwy\TestPlugin.pkg)

### ISSUE THREAD

**Issue by wwy19841007** [pyinstaller/pyinstaller#8729]
I've been running pyinstaller to build my python scripts on a windows. So far it has doing a great job. Until recently pyinstaller just don't work. Every .exe file it build performs ok on my windows, but report '**Cannot open PyInstaller archive from executable (C:\Users\wwy\TestPlugin.exe) or external archive (C:\Users\wwy\TestPlugin.pkg)**'.

Then I tried building an empty application like below using command 'pyinstaller -F TestPlugin.py'. But it still reported the same error.

# -*- coding: utf-8 -*-
def main():
    print("app start")

if __name__ == '__main__':
    main()

I'm using version 6.3.0. And I have tried 5.13.2, 6.5.0, 6.9.0. Non of them works.
My python version is 3.10.11.

Please help me fix this problem.

**Comment by rokm** [comment]
> Every .exe file it build performs ok on my windows, but report 'Cannot open PyInstaller archive from executable (C:\Users\wwy\TestPlugin.exe) or external archive (C:\Users\wwy\TestPlugin.pkg)'.

To clarify, is the error reported on your machine as well, or on another machine?

Either way, this usually means that either you somehow corrupted your .exe file (e.g., while transferring it), or the anti-virus program is blocking access to the .exe.

**Comment by wwy19841007** [comment]
> > Every .exe file it build performs ok on my windows, but report 'Cannot open PyInstaller archive from executable (C:\Users\wwy\TestPlugin.exe) or external archive (C:\Users\wwy\TestPlugin.pkg)'.
> 
> To clarify, is the error reported on your machine as well, or on another machine?
> 
> Either way, this usually means that either you somehow corrupted your .exe file (e.g., while transferring it), or the anti-virus program is blocking access to the .exe.

It works on the building machine, which is mine. But reported this error on all other two machines.

**Comment by wwy19841007** [comment]
> > Every .exe file it build performs ok on my windows, but report 'Cannot open PyInstaller archive from executable (C:\Users\wwy\TestPlugin.exe) or external archive (C:\Users\wwy\TestPlugin.pkg)'.
> 
> To clarify, is the error reported on your machine as well, or on another machine?
> 
> Either way, this usually means that either you somehow corrupted your .exe file (e.g., while transferring it), or the anti-virus program is blocking access to the .exe.

Thanks for your reply. Problem solved. It the anti-virus program's fault.

**Comment by wwy19841007** [comment]
Issue Closed.
