### ISSUE TITLE
Failed to execute script when `jaraco\\text\\Lorem ipsum.txt` is removed??!?

### ISSUE THREAD

**Issue by ewerybody** [pyinstaller/pyinstaller#8731]
```
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\{projectpath}\\_internal\\jaraco\\text\\Lorem ipsum.txt'
[4968] Failed to execute script 'pyi_rth_pkgres' due to unhandled exception!
```

Well, I hacked the spec file to get rid of unwanted resources in my package. That usually works like a charm. But I just updated to latest PyInstaller 72 and saw this `jaraco` resource collected with just a text file in it during analysis. When I remove it it complains?
Why would I want this resource in my package? What is this? 🙂

### Context information

* Output of `pyinstaller --version`: ```72.1.0```
* Version of Python: `3.11`
* Platform: Windows 10 English US
* How you installed Python: python.org/downloads installer
* Did you also try this on another platform? Does it work there? No, I'm on windows for this only

**Comment by rokm** [comment]
Go complain to `setuptools`, which are now vendoring full copy of `jaraco.text`, which in turn bundles (and requires!) that file. 

Although if it ended up collected in `_internal\jaraco\text`, then either you are using PyInstaller < 6.10.0, or you have a stand-alone copy of `jaraco.text` (which has a similar requirement) in addition to one bundled with setuptools 72.1.0.

**Comment by ewerybody** [comment]
Ahhhh OK! :D Well, these hooks were collected through Analysis: 
```
pyi_rth_pkgres
pyi_rth_pkgutil
pyi_rth_setuptools
```
I thought I need these! Now I just excluded them and Voilà: It works. THANK YOU! 🙇‍♀️
