### ISSUE TITLE
Endless Recursion in PyInstaller

### ISSUE THREAD

**Issue by susanna-ng3** [pyinstaller/pyinstaller#8732]
### Context information (for bug reports)
Python's stack-limit is a safety-belt against endless recursion,
eating up memory. PyInstaller imports modules recursively. If the structure
how modules are imported within your program is awkward, this leads to the
nesting being too deep and hitting Python's stack-limit.

With the default recursion limit (1000), the recursion error occurs at about
115 nested imported, with limit 2000 at about 240, with limit 5000 at about
660.

* Output of `pyinstaller --version`: ```(paste here)```
* Version of Python: <3.12>
* Platform: <Windows, scripting on PyCharm>
* How you installed Python: <python.org/downloads, conda>
* Did you also try this on another platform? Does it work there? no 

###Current Imports
import PySimpleGUI as sg
import pdal
import json
import numpy as np
import os
import csv
from datetime import datetime
import pyproj
import time
import sys
sys.setrecursionlimit(sys.getrecursionlimit() * 5)

### GUI layout (partial)
# GUI Layout
layout = [
    [sg.Text('Input LAS/LAZ File:'), sg.Input(), sg.FileBrowse(file_types=(("LAS/LAZ Files", "*.las;*.laz"),))],
    [sg.Text('Source CRS:'), sg.Input(key='source_crs')],
    [sg.Text('Target CRS:'), sg.Input(key='target_crs')],
    [sg.Checkbox('Use EPSG Codes', default=True, key='use_epsg')],
    [sg.Text('Output Precision:'), sg.Input('6', key='precision')],
    [sg.Button('Calculate RMS'), sg.Button('Exit')],
    [sg.Output(size=(80, 15))]
]

# Create the window
window = sg.Window('Enhanced RMS Calculator', layout)

**Comment by rokm** [comment]
> ###Current Imports
> ...
>  sys.setrecursionlimit(sys.getrecursionlimit() * 5)

You need to increase recursion limit at the top of your .spec file, not in your python program. And then rebuild using the modified spec file.

**Comment by susanna-ng3** [comment]
thank you. fixed it
