### ISSUE TITLE
Building Kivy Python executable with pyinstaller is failing

### ISSUE THREAD

**Issue by weaved459** [pyinstaller/pyinstaller#8735]
Env(virtual environment):

OS Ubuntu 22.04.4
Python 3.12.4
Kivy 2.3.0
pyinstaller 6.10.0

pyinstaller main.py results in multiple warnings with a last failure message stating....
AttributeError: module 'PyInstaller.depend.bindepend' has no attribute 'selectImports'

**Comment by bwoodsend** [comment]
That's kivy's bug if their writing their own hooks which [use private APIs](https://github.com/kivy/kivy/blob/9ef218027178115a66b417ae34b21f488bdd3617/kivy/tools/packaging/pyinstaller_hooks/__init__.py#L370).

**Comment by rokm** [comment]
See https://github.com/kivy/kivy/issues/8653 and https://github.com/kivy/kivy/issues/8773.
