### ISSUE TITLE
pyinstaller onefile file size increases in latest version 6.10

### ISSUE THREAD

**Issue by petef19** [pyinstaller/pyinstaller#8736]
While testing which `numpy` package has the smallest footprint when added to our app, discovered these inconsistencies in the file size of the `onefile` compiled output of two different `pyinstaller` versions.
Our single script app is very small, in both cases below the **exact same** `app.py` was used.

Can anybody explain these discrepancies?

```
pyinstaller 4.9, (old)
pyinstaller-hooks-contrib 2022.2 (old)
numpy 2.0.1: does not work
numpy 1.26.4: does not work
numpy 1.25.2: adds 12.4 MB
numpy 1.24.4: adds 11.8 MB
numpy 1.23.5: adds 11.7 MB
numpy 1.22.4: adds 12.1 MB	
numpy 1.21.4: adds 11.5 MB     <--- smallest

pyinstaller 6.10 (latest)
pyinstaller-hooks-contrib 2024.8 (latest)	
numpy 2.0.1 : adds 13.1 MB
numpy 1.26.4: adds 12.3 MB
numpy 1.25.2: adds 21.8 MB (!)    <---- larger
numpy 1.24.4: adds 20.6 MB (!)    <---- larger
numpy 1.23.5: adds 20.4 MB (!)    <---- larger
numpy 1.22.4: adds 21.0 MB (!)    <---- larger
numpy 1.21.4: adds 20.1 MB (!)    <---- larger
```
Considering that the same `app.py` was used, zero changes in cfg, I would have  assumed that the newer `pyinstaller` version either matches the file size of the much older version or reduces it due to improvements.... (?)

Win 10 x64
Python 3.10.2

**Comment by bwoodsend** [comment]
If you build in onedir mode then diff the file tree:
```
> du -h dist/
3.0M	dist/new/_internal/numpy/core
176K	dist/new/_internal/numpy/linalg
2.1M	dist/new/_internal/numpy/random
112K	dist/new/_internal/numpy/fft
33M	dist/new/_internal/numpy/.libs
39M	dist/new/_internal/numpy
83M	dist/new/_internal
86M	dist/new
3.0M	dist/old/numpy/core
176K	dist/old/numpy/linalg
2.1M	dist/old/numpy/random
112K	dist/old/numpy/fft
5.3M	dist/old/numpy
52K	dist/old/setuptools-58.1.0.dist-info
53M	dist/old
```
The difference is that old PyInstaller is forgetting to package `numpy/.libs`.

**Comment by bwoodsend** [comment]
Hmm, actually that's nonsense. The new PyInstaller is collecting `libopenblas` twice.
```
> du -ah -t1m dist/
2.9M	dist/new/new.exe
4.3M	dist/new/_internal/python310.dll
33M	dist/new/_internal/libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
1.1M	dist/new/_internal/unicodedata.pyd
2.9M	dist/new/_internal/numpy/core/_multiarray_umath.cp310-win_amd64.pyd
3.0M	dist/new/_internal/numpy/core
2.1M	dist/new/_internal/numpy/random
33M	dist/new/_internal/numpy/.libs/libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
33M	dist/new/_internal/numpy/.libs
39M	dist/new/_internal/numpy
3.3M	dist/new/_internal/libcrypto-1_1.dll
83M	dist/new/_internal
86M	dist/new
2.9M	dist/old/old.exe
4.3M	dist/old/python310.dll
33M	dist/old/libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
1.1M	dist/old/unicodedata.pyd
2.9M	dist/old/numpy/core/_multiarray_umath.cp310-win_amd64.pyd
3.0M	dist/old/numpy/core
2.1M	dist/old/numpy/random
5.3M	dist/old/numpy
3.3M	dist/old/libcrypto-1_1.dll
53M	dist/old
139M	dist/
```

**Comment by rokm** [comment]
That's because `numpy` hook explicitly collects dynamic libs from the package into top-level application directory: [upstream](https://github.com/numpy/numpy/blob/282c79ebc9b61ebc5f0755736ec953b8d954922c/numpy/_pyinstaller/hook-numpy.py#L13) and [our (original) copy](https://github.com/pyinstaller/pyinstaller/blob/ca8a976a4d28118d91d728362bfd43c48e21666d/PyInstaller/hooks/hook-numpy.py#L28).

With 1.26.x and 2.x series, that's not a problem because the libs have been moved outside of the package.

I suppose for versions of numpy that do not have bundled hook and use our copy (< 1.23), we can fix that on our side. The in-between versions are probably unfixable.

**Comment by bwoodsend** [comment]
Given that NumPy <=1.23 is [officially](https://scientific-python.org/specs/spec-0000/#support-window) dead, I'd say no to trying to do anything about it.

This is another case though where giving numpy the numpy hook is doing more harm than good. Might be worth undoing that.

**Comment by rokm** [comment]
> This is another case though where giving numpy the numpy hook is doing more harm than good. Might be worth undoing that.

Yeah, I second that. 

I think in general, it has turned out that we are in much better position to maintain hooks than the upstream projects, because 

a) we have deeper understanding of PyInstaller and its intricacies 

b) we nowadays have much faster release cycles, so we can respond to these sort of issues at faster pace (goes both for PyInstaller and pyinstaller-hooks-contrib).

**Comment by petef19** [comment]
so are you guys saying that the `numpy 2.0.1` import in `pyinstaller 6.10` is correct and the file size is not bloated?

**Comment by bwoodsend** [comment]
It's not bloated through any fault of PyInstaller's at least. It is bigger although that's because numpy is bigger. Unfortunately, that's just the trend in the scientific community.

**Comment by petef19** [comment]
@bwoodsend 
fully understand that package size may increase w/ updated releases
my OP points out how some `pyinstaller` + `numpy` combinations were incorrectly bloated (for whatever reason), this can be easily identified by comparing both `1.21.4` installs
Can you confirm that `numpy 2.0.1` on latest `pyinstaller` is NOT bloated?
Thanks.

**Comment by rokm** [comment]
>  Can you confirm that numpy 2.0.1 on latest pyinstaller is NOT bloated?

That should be the case, since the duplication issue is limited to < 1.26. Do you have any further evidence to the contrary?

**Comment by rokm** [comment]
And if you're interested in further "non-bloated" comparisons, you can manually fix the `hook-numpy.py` file your local numpy and PyInstaller 6.x installation; change the `binaries = collect_dynamic_libs("numpy", ".")` line into `binaries = collect_dynamic_libs("numpy")`. (Keep in mind that this latter variant is needed to prevent duplication with PyInstaller >= 6.0, while the former variant is needed to prevent duplication with PyInstaller < 6.0).

**Comment by petef19** [comment]
@rokm: copy that, thank you, I'll try that - hopefully it wlll reduce size of `numpy` import b/c even the non-bloated imports are way too large if you just use one or two functions
