### ISSUE TITLE
Inspect.stack()'s code_context is None when freezed.

### ISSUE THREAD

**Issue by mhertz** [pyinstaller/pyinstaller#8738]
As title, freezed apps return None as code_context from inspect.stack(). I see already an inspect rthook in your project, but little different issue seemingly

Hope i'm not completely misunderstanding something fundamental here.

Thanks in advance!
```
C:\deluge2\python>type test.py
import inspect

print(inspect.stack()[0][4])

C:\deluge2\python>python.exe test.py
['print(inspect.stack()[0][4])\n']

C:\deluge2\python>dist\test\test.exe
None

C:\deluge2\python>Scripts\pyinstaller.exe -v
6.10.0

C:\deluge2\python>python.exe -V
Python 3.12.5
```

**Comment by rokm** [comment]
> Hope i'm not completely misunderstanding something fundamental here.

You are; PyInstaller does not collect source code for your entry-point script, so there is no code context available. (And while we are at it, it does not collect source code for modules either, unless there is a hook that instructs it to do so).

If you absolutely require this information, you will need to collect your entry-point script as a data file as well, e.g., `pyinstaller --clean --noconfirm test.py --add-data test.py:.`

**Comment by mhertz** [comment]
Thanks alot for your gracefully clarification of this, much appreciated and I apologize jumping the gun before understanding the issue better. Thanks!
