### ISSUE TITLE
Still flashes after launching

### ISSUE THREAD

**Issue by yumianhuli1** [pyinstaller/pyinstaller#8748]
The package command contains --windowed --noconsole, but a black box still flashes after launching？But the launch is successful，Just affect the visual experience, how to solve? thanks！

**Comment by rokm** [comment]
That usually happens when your code (or the 3rd party code you are using) spawns a subprocess using a program or utility that is built with console enabled.

**Comment by yumianhuli1** [comment]
> That usually happens when your code (or the 3rd party code you are using) spawns a subprocess using a program or utility that is built with console enabled.
thanks！
Are you referring to the use of subprocess of python?

**Comment by rokm** [comment]
>  Are you referring to the use of subprocess of python?

Yes.

**Comment by yumianhuli1** [comment]
> > Are you referring to the use of subprocess of python?
> 
> Yes.

You mean that if I don't want to see a black box, I must not use subprocess, then replace the subprocess part with another method，right?

**Comment by rokm** [comment]
> > > Are you referring to the use of subprocess of python?
> > 
> > 
> > Yes.
> 
> You mean that if I don't want to see a black box, I must not use subprocess, then replace the subprocess part with another method，right?

You should find the part of code where problematic subprocess is spawned. If it is spawned via `subprocess` module, you can try passing [subprocess.CREATE_NO_WINDOW](https://docs.python.org/3/library/subprocess.html#subprocess.CREATE_NO_WINDOW) to its `creationflags` argument. In case of 3rd party code, you should check if you can avoid entering that particular codepath.

**Comment by yumianhuli1** [comment]
> > > > Are you referring to the use of subprocess of python?
> > > 
> > > 
> > > Yes.
> > 
> > 
> > You mean that if I don't want to see a black box, I must not use subprocess, then replace the subprocess part with another method，right?
> 
> You should find the part of code where problematic subprocess is spawned. If it is spawned via `subprocess` module, you can try passing [subprocess.CREATE_NO_WINDOW](https://docs.python.org/3/library/subprocess.html#subprocess.CREATE_NO_WINDOW) to its `creationflags` argument. In case of 3rd party code, you should check if you can avoid entering that particular codepath.

Thanks for your kind reply!
I added creationflags=subprocess.CREATE_NO_WINDOW to the input to all subprocess-related functions
Now it doesn't pop up after booting, but there is still a popup during booting. Do you know what else causes this?

**Comment by rokm** [comment]
> Do you know what else causes this?

My first guess would be that some module that your are importing is spawning a subprocess during its initialization. But it's hard to say without knowing what exactly your code does. Can you provide a minimal example that triggers this issue during its startup?

**Comment by yumianhuli1** [comment]
> > Do you know what else causes this?
> 
> My first guess would be that some module that your are importing is spawning a subprocess during its initialization. But it's hard to say without knowing what exactly your code does. Can you provide a minimal example that triggers this issue during its startup?

I found that when I import a dependency from this library（https://github.com/Breakthrough/PySceneDetect）, cmd window pops up.
Dependency:
from scenedetect import open_video, SceneManager
from scenedetect.detectors import ContentDetector

**Comment by rokm** [comment]
That sounds like something that would also be spawning subprocesses (e.g., to check for presence of `ffmpeg` executable). Either directly in the `scenedetect` code (see `scenedetect.platform` for example) or from its backends (for example, if you are using `moviepy` backend).

**Comment by yumianhuli1** [comment]
> That sounds like something that would also be spawning subprocesses (e.g., to check for presence of `ffmpeg` executable). Either directly in the `scenedetect` code (see `scenedetect.platform` for example) or from its backends (for example, if you are using `moviepy` backend).

Yes, I have solved it.Thanks a lot!
