### ISSUE TITLE
New option/tag for increase performance for create a one-file bundled executable

### ISSUE THREAD

**Issue by rpascoal** [pyinstaller/pyinstaller#8766]
I would like to suggest adding an additional option when generating the executable through the **--onfile** tag that can improve performance in its second execution by partially resolving the processing delay.

How does PyInstaller generate a temporary folder for the project's dependent files and it does this every time it is run, and this takes 3 to 4 seconds and the idea would be to pass a parameter/tag that informs whether or not you want the folder to be temporary be created at all times.

Example on Windows:

```
pyinstaller --onefile --rewrite-temp-dir=no .\Demo.py

pyinstaller --onefile --runtime-tmp .\myDemoDir --rewrite-temp-dir=no .\Demo.py

```
If there is already a way to do this, please let me know!

Regards
Ricardo Pascoal

**Comment by bwoodsend** [comment]
See #7907
