### ISSUE TITLE
PyInstaller: Generated EXE Files Flagged as Virus in Latest Version (Detected by Quick Heal)

### ISSUE THREAD

**Issue by K-Gopal126** [pyinstaller/pyinstaller#8776]
I have encountered an issue with the latest version of PyInstaller, where the generated EXE files are being flagged as a virus by multiple antivirus programs, including Quick Heal. This problem did not occur in previous versions and seems to have started after updating to the most recent release.

**Steps to Reproduce:**

1. Create a simple Python script.
2. Use PyInstaller to compile the script into an EXE file.
3. Run the EXE file and notice that it is flagged as a virus or malware by Quick Heal and potentially other antivirus software.

**Expected Behavior:**

The EXE file generated by PyInstaller should not be flagged as a virus by any reputable antivirus software, including Quick Heal.

**Environment:**

- **PyInstaller version:** 6.10.0
- **Python version:** 3.12.5
- **Operating System:** Windows 11

**Comment by rokm** [comment]
The [issue template](https://github.com/pyinstaller/pyinstaller/blob/develop/.github/ISSUE_TEMPLATE/antivirus.md) says all we have to say on this matter. Take it up with your anti-virus program vendor.

**Comment by Robinsane** [comment]
I also recently encountered this I believe; my program automatically disappeared multiple times from a network folder.

Pyinstaller 6.1.0 was fine for me, this happened on 6.10.0

@K-Gopal126 What was your problem-free pyinstaller version before 6.10.0?
