### ISSUE TITLE
PyTables 3.9.2 endless loop

### ISSUE THREAD

**Issue by martinowitsch** [pyinstaller/pyinstaller#8783]
There is an issue with pyTables 3.9.2. PyInstaller is looping and not starting the .exe file. I dont see any major strange things during compilation or in the warn-test_pyTables.txt file.

PyInstaller: 6.10.0
tables: 3.9.2

my MWE:
```
import tables 
print('Hi')
```

The first loop gives a strange error at the end:
**[PYI-3376:DEBUG] LOADER: trying t[PoY Il-149o68ad :DEeBxUGe]cut aLOAbDER: lhided-eembend dweidnd oaw rccrheivatede!.
-[P1Y4I9-6383:7D6E:BUDG] ELBOUADEGR: ] eLntOerAiDnERg the w:a iattitnegmp tloop.i.n.g
 to open archive C:\dist\test.exe**

See the full output for the first loop:
```
[PYI-14968:DEBUG] PyInstaller Bootloader 6.x
[PYI-14968:DEBUG] LOADER: executable file: C:\dist\test.exe
[PYI-14968:DEBUG] LOADER: trying to load executable-embedded archive...
[PYI-14968:DEBUG] LOADER: attempting to open archive C:\dist\test.exe
[PYI-14968:DEBUG] LOADER: cookie found at offset 0x572A11F
[PYI-14968:DEBUG] LOADER: archive file: C:\dist\test.exe
[PYI-14968:DEBUG] LOADER: application has onefile semantics...
[PYI-14968:DEBUG] LOADER: _PYI_ARCHIVE_FILE not defined...
[PYI-14968:DEBUG] LOADER: process level = 0
[PYI-14968:DEBUG] LOADER: this is parent process of onefile application.
[PYI-14968:DEBUG] LOADER: initializing security descriptor for temporary directory...
[PYI-14968:DEBUG] LOADER: initializing security descriptor from string: D:(A;;FA;;;S-1-5-21-223686960-1572950274-59529505-14183)
[PYI-14968:DEBUG] LOADER: creating temporary directory (runtime_tmpdir=(null))...
[PYI-14968:DEBUG] LOADER: attempting to create temporary application directory under ...
[PYI-14968:DEBUG] LOADER: created temporary directory: ...
[PYI-14968:DEBUG] LOADER: application's top-level directory: ...
[PYI-14968:DEBUG] LOADER: calling SetDllDirectory: ...
[PYI-14968:DEBUG] LOADER: splash screen is unavailable.
[PYI-14968:DEBUG] LOADER: extracting files to temporary directory...
[PYI-14968:DEBUG] LOADER: setting _PYI_APPLICATION_HOME_DIR to ...
[PYI-14968:DEBUG] LOADER: starting the child process...
[PYI-14968:DEBUG] LOADER: setting up child process...
[PYI-14968:DEBUG] LOADER: child process started!
[PYI-14968:DEBUG] LOADER: creating hidden window to capture system shutdown events...
[PYI-3376:DEBUG] PyInstaller Bootloader 6.x
[PYI-3376:DEBUG] LOADER: executable file: C:\dist\test.exe
[PYI-3376:DEBUG] LOADER: trying t[PoY Il-149o68ad :DEeBxUGe]cut aLOAbDER: lhided-eembend dweidnd oaw rccrheivatede!.
-[P1Y4I9-6383:7D6E:BUDG] ELBOUADEGR: ] eLntOerAiDnERg the w:a iattitnegmp tloop.i.n.g
 to open archive C:\dist\test.exe
```

nothings happens after this and the loader keeps on looping (see the time stamp):
```
[PYI-3376:DEBUG] PyInstaller Bootloader 6.x
...
[PYI-3376:DEBUG] LOADER: running test_pyTables.py
[PYI-9952:DEBUG] PyInstaller Bootloader 6.x
...
[PYI-9952:DEBUG] LOADER: running test_pyTables.py
[PYI-4672:DEBUG] PyInstaller Bootloader 6.x
...
[PYI-4672:DEBUG] LOADER: running test_pyTables.py
[PYI-16128:DEBUG] PyInstaller Bootloader 6.x
...
[PYI-16128:DEBUG] LOADER: running test_pyTables.py
[PYI-3748:DEBUG] PyInstaller Bootloader 6.x
...
```

If I switch to tables 3.8.0 the issue does not occur.

Can some one reproduce this error?

**Comment by rokm** [comment]
> The first loop gives a strange error at the end:
> ```
> -[P1Y4I9-6383:7D6E:BUDG] ELBOUADEGR: ] eLntOerAiDnERg the w:a iattitnegmp tloop.i.n.g
> to open archive C:\dist\test.exe
> ```

That's just two processes trying to write to console at the same time, and their output ending up interleaved...

---

Usually, if you get endless spawn loop like that, `multiprocessing` is involved, and you need to call `multiprocessing.freeze_support` before any primitive from `multiprocessing` is used, as per docs: https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#multi-processing

You can confirm this if you print `sys.argv` at the start of your program:

```python
import sys
print(f"Args: {sys.argv}")

import tables 
print('Hi')
``` 

Then you get (for onedir build, instead of onefile that you are using):
```
>dist\program\program.exe
Args: ['dist\\program\\program.exe']
Args: ['...\\dist\\program\\program.exe', '--multiprocessing-fork', 'parent_pid=5896', 'pipe_handle=336']
Args: ['...\\dist\\program\\program.exe', '--multiprocessing-fork', 'parent_pid=6684', 'pipe_handle=656']
Args: ['...\\dist\\program\\program.exe', '--multiprocessing-fork', 'parent_pid=3560', 'pipe_handle=508']
...
```

which indicates that multiprocessing worker process is being spawned, unsucessfuly, and thus repeatedly.

So in this case, importing `tables` triggers use of `multiprocessing` somewhere, so `multiprocessing.freeze_support` needs to be called before importing `tables`:

```python
import sys
print(f"Args: {sys.argv}")

import multiprocessing
multiprocessing.freeze_support()

import tables 
print('Hi')
```

```
>dist\program\program.exe
Args: ['dist\\program\\program.exe']
Args: ['...\\dist\\program\\program.exe', '--multiprocessing-fork', 'parent_pid=7656', 'pipe_handle=248']
Hi
```

**Comment by rokm** [comment]
And the use of `multiprocessing` happens in `cpuinfo.get_cpu_info`, which is called from [here](https://github.com/PyTables/PyTables/blob/v3.9.2/tables/leaf.py#L7-L11) during `tables.leaf` initialization. 

This call (as opposed to just the import of `cpuinfo`) was added in v3.9.0 by https://github.com/PyTables/PyTables/commit/a2bdcdec3885e20c99098dcb633a48c72e1871fe. But it was removed later somewhere during v3.10.0 development cycle, so with v3.10.0 and later, you should be also able to get away without calling `freeze_support`. EDIT: well, at least in the basic `import tables` example - with real use, you might still hit the codepath that calls `cpuinfo.get_cpu_info()`, and you need to ensure that  `freeze_support` is called before that.
