### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '\pydicom\\data\\urls.json'

### ISSUE THREAD

**Issue by Devanshu-Augusty** [pyinstaller/pyinstaller#8790]
## Description of the issue
I am using PyInstaller to convert my main.py script into an executable. The script runs perfectly when executed as a Python file. However, when running the compiled .exe, I encounter the following error:

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\augus\\AppData\\Local\\Temp\\_MEI80482\\pydicom\\data\\urls.json'
[PYI-20064:ERROR] Failed to execute script 'main' due to unhandled exception!

### Context information (for bug reports)
-> It appears that the generated executable is attempting to locate the urls.json file within a temporary directory (C:\\Users\\augus\\AppData\\Local\\Temp\\_MEI80482\\pydicom\\data\\), but the file is not found.

-> Since I am using a virtual environment, I am unsure why the executable is trying to access this path in my local directory.

* Output of `pyinstaller --version`: ```6.10.0```
* Version of Python: 3.11.2
* Platform:  Windows 11
* How you installed Python: python.org/downloads
* I also tried it on a Virtual machine, with python version 3.12.6 (with virtual environment) , same issue there also

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

main.py
```
import pydicom
print("pydicon test")
```
pyinstaller command:
```
pyinstaller --name main --onefile  main.py
```
main.spec file:
```
# -*- mode: python ; coding: utf-8 -*-

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[],
    hiddenimports=[
        'pydicom.encoders.gdcm',
        'pydicom.encoders.pylibjpeg',
        'pydicom.pixels.decoders.gdcm',
        'pydicom.pixels.decoders.pylibjpeg',  # add pylibjpeg decoder
        'pylibjpeg',                          # include pylibjpeg module
        'pylibjpeg.plugins',                  # include plugins
        'pylibjpeg.pydicom',
        'pylibjpeg_openjpeg',                 # include openjpeg plugin if needed
        'pydicom.pixels.decoders.pillow',
        'pydicom.pixels.decoders.pyjpegls',
        'pydicom.pixels.decoders.rle',
        'pydicom.pixels.encoders.gdcm',
        'pydicom.pixels.encoders.native',
        'pydicom.pixels.encoders.pyjpegls',
        'pydicom.pixels.encoders.pylibjpeg',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
    optimize=0,
)
pyz = PYZ(a.pure)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.datas,
    [],
    name='main',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)

```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "pydicom\__init__.py", line 33, in <module>
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "pydicom\examples\__init__.py", line 11, in <module>
  File "pydicom\data\data_manager.py", line 337, in get_testdata_file
  File "pydicom\data\data_manager.py", line 369, in _get_testdata_file
  File "pydicom\data\download.py", line 138, in get_url_map
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\augus\\AppData\\Local\\Temp\\_MEI80482\\pydicom\\data\\urls.json'
[PYI-20064:ERROR] Failed to execute script 'main' due to unhandled exception!
```

### Expected Behavior:
*The .exe file should include all necessary files, including urls.json, to run independently without needing to access local directories.

### Question:
*Why is the executable trying to locate this file in the local directory? How can I ensure that all necessary files are bundled within the executable during the build process with PyInstaller?

**Comment by rokm** [comment]
See https://github.com/pyinstaller/pyinstaller-hooks-contrib/pull/796
