### ISSUE TITLE
Issue with latest setuptools==75.0.0

### ISSUE THREAD

**Issue by arossert** [pyinstaller/pyinstaller#8793]
A new version was released yesterday that caused the build to fail
```
13:34:09  Traceback (most recent call last):
13:34:09    File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
13:34:09      return _run_code(code, main_globals, None,
13:34:09    File "C:\Python38\lib\runpy.py", line 87, in _run_code
13:34:09      exec(code, run_globals)
13:34:09    File "C:\Python38\Scripts\pyinstaller.exe\__main__.py", line 7, in <module>
13:34:09    File "C:\Python38\lib\site-packages\PyInstaller\__main__.py", line 228, in _console_script_run
13:34:09      run()
13:34:09    File "C:\Python38\lib\site-packages\PyInstaller\__main__.py", line 212, in run
13:34:09      run_build(pyi_config, spec_file, **vars(args))
13:34:09    File "C:\Python38\lib\site-packages\PyInstaller\__main__.py", line 69, in run_build
13:34:09      PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
13:34:09    File "C:\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 1189, in main
13:34:09      build(specfile, distpath, workpath, clean_build)
13:34:09    File "C:\Python38\lib\site-packages\PyInstaller\building\build_main.py", line 1129, in build
13:34:09      exec(code, spec_namespace)
13:34:09    File "cicd/simulation/simulation.spec", line 161, in <module>
13:34:09      copy_tree(os.path.join(DISTPATH, 'sbpostaction'), os.path.join(DISTPATH, 'sbsimulation'))
13:34:09    File "C:\Python38\lib\site-packages\setuptools\_distutils\dir_util.py", line 155, in copy_tree
13:34:09      return list(itertools.chain.from_iterable(map(copy_one, names)))
13:34:09    File "C:\Python38\lib\site-packages\setuptools\_distutils\dir_util.py", line 186, in _copy_one
13:34:09      yield from copy_tree(
13:34:09    File "C:\Python38\lib\site-packages\setuptools\_distutils\dir_util.py", line 155, in copy_tree
13:34:09      return list(itertools.chain.from_iterable(map(copy_one, names)))
13:34:09    File "C:\Python38\lib\site-packages\setuptools\_distutils\dir_util.py", line 197, in _copy_one
13:34:09      file_util.copy_file(
13:34:09    File "C:\Python38\lib\site-packages\setuptools\_distutils\file_util.py", line 104, in copy_file
13:34:09      from distutils._modified import newer
13:34:09  ModuleNotFoundError: No module named 'distutils._modified'
```

### Context information (for bug reports)

* PyInstaller 6.10.0
* Version of Python: 3.8
* Platform: All

**Comment by rokm** [comment]
Are you sure this is PyInstaller issue?

```
13:34:09    File "cicd/simulation/simulation.spec", line 161, in <module>
13:34:09      copy_tree(os.path.join(DISTPATH, 'sbpostaction'), os.path.join(DISTPATH, 'sbsimulation'))
```

this implies that you are using `distutils.dir_util.copy_tree` in your spec file, and this ends up raising error, for whatever reason. It could still be issue with PyInstaller + setuptools/distutils, but can you reproduce the problem by just calling `copy_tree` outside of the PyInstaller?

**Comment by arossert** [comment]
@rokm Sure, I will give it a try, Tx

**Comment by arossert** [comment]
@rokm Seems like `copy_tree` is working when running in IPython

**Comment by rokm** [comment]
Hmm, can you provide a minimal reproducer that triggers the error locally (not your on CI)? 

Because if I try to mimic your `copy_tree` in a spec file on my Windows VM, it seems to work as expected. 

And that `distutils._modified` seems to have been present in previous versions of `setuptools`-vendored `distutils` as well. So the only scenario I can imagine right now that would result in `distutils._modified` missing is if analysis somehow changed the search paths and now `distutils` resolves to the stdlib version instead of setuptools one...

But there are many factors - are you setting `SETUPTOOLS_USE_DISTUTILS` in your environment? If you modify your spec to copy (and arbitrary file/directory) *before* running the analysis, does it work? Does it fail if you move the copy attempt after the analysis? So having a reproducer would help narrowing these down...

**Comment by arossert** [comment]
@rokm I'm trying to reproduce it in a small example but it seems to be working 😥 
We are not using the `SETUPTOOLS_USE_DISTUTILS` env var and also noticed that setuptools has released new version (75.1.0) but I still have the same issue, will update once I will have more information

**Comment by rokm** [comment]
I suppose you could consider switching from `distutils.dir_util.copy_tree` to `shutil.copytree`. Or perhaps even do that copy outside of the spec file using OS commands on the CI (assuming it is performed at the end of the spec file).

**Comment by arossert** [comment]
@rokm I discovered some weird things in here, I have other projects that use the same flow and they do not have this issue, but they use the latest PyInstaller version 6.10.0 and this one is using 6.7.0 (since I have another issue upgrading).

Also it only happens when running from the CI flow (Junkins), when running manually it does not happen, I checked the env vars and I don't see anything that can effect this 😥 

Since this only happens on older version of PyInstaller I will switch to `shutil` and will close this issue, Tnaks,
