### ISSUE TITLE
PyInstaller `onefile` and `onedir` builds break when using Rye to install Python on Linux

### ISSUE THREAD

**Issue by alexdelorenzo** [pyinstaller/pyinstaller#8802]
## Description of the issue
When using [Rye](https://rye.astral.sh/) to install Python on Linux, PyInstaller `onefile` and `onedir` builds break with errors.

Rye uses the portable Python builds from here: https://github.com/indygreg/python-build-standalone

Examples with errors are posted below.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.10.0```
* Version of Python: 3.12.5
* Platform: Linux (tried Arch and Ubuntu)
* How you installed Python: Rye
* Did you also try this on another platform? Does it work there?: **Yes, PyInstaller works fine on macOS and Windows using Rye to install portable Python. It's only on Linux that it doesn't work.**

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Install Python like so:
```bash
$ rye toolchain fetch cpython@3.12.5
$ rye init
$ rye pin cpython@3.12.5
```

#### Example scripts to run PyInstaller on

```python
# main.py
print("hello world")
```

And:

```python3
# example.py
import multiprocessing
print("hello world")
```

### Stacktrace / full error message
```bash
$ dist/main
[1475051] Module object for struct is NULL!
Traceback (most recent call last):
  File "struct.py", line 13, in <module>
ModuleNotFoundError: No module named '_struct'
```
And:

```bash
$ dist/example
Traceback (most recent call last):
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 107, in <module>
  File "PyInstaller/hooks/rthooks/pyi_rth_multiprocessing.py", line 95, in _pyi_rthook
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/popen_forkserver.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/forkserver.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 419, in exec_module
  File "multiprocessing/connection.py", line 22, in <module>
ModuleNotFoundError: No module named '_multiprocessing'
[13284] Failed to execute script 'pyi_rth_multiprocessing' due to unhandled exception!
```

## See also
 - https://github.com/indygreg/python-build-standalone/issues/276

**Comment by bwoodsend** [comment]
We'll have a look but disclaimer: we're not really interested in supporting every esoteric build of Python. Debian's Python environment with its hybrid use of `--enable-shared` is bad enough. Covering all possible combinations of statically versus dynamically linked versus vendored versus missing dependencies multiplied by all the ways to (mis)use `@RPATH` is not particularly rewarding.

**Comment by rokm** [comment]
I suspect the underlying issue is that we fail to resolve `rye` python's shared library, and end up collecting the one from base system's installation - can you verify that by opening `build/<name>/Analysis-00.toc` and finding the entry for `libpython3.12.so`?

With `rye` python build, `_struct` is a built-in, but with system python, it is extension module. So when we use system python's libpython at run-time, we end up missing `_struct` because it was a built-in in the original build environment... (on the other hand, if the base system also happens to have libpython where `_struct` is a built-in, as seems to be the case on my test Ubuntu system, then the problem does not manifest).

The output of `ldd` is 
```
$ ldd .rye/py/cpython@3.12.5/bin/python3
	linux-vdso.so.1 (0x00007ffef41a0000)
	/home/rok/.rye/py/cpython@3.12.5/bin/../lib/libpython3.12.so.1.0 (0x00007e8eb6c00000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007e8eb85b5000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007e8eb85b0000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007e8eb85ab000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007e8eb84c2000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007e8eb84bb000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007e8eb6800000)
	/lib64/ld-linux-x86-64.so.2 (0x00007e8eb85ce000)
```

which does not match our `libname => fullpath (address)` regex pattern.

And the underlying reference looks like this:
```
$ readelf -d .rye/py/cpython@3.12.5/bin/python3.12 | grep libpython
 0x0000000000000001 (NEEDED)             Shared library: [$ORIGIN/../lib/libpython3.12.so.1.0]
```

**Comment by alexdelorenzo** [comment]
@bwoodsend I can imagine it's unrewarding, so thanks for taking a look. Both Rye and `uv` use these builds, and I believe PyOxidizer does, as well. Might be less esoteric over time. 

> I suspect the underlying issue is that we fail to resolve `rye` python's shared library, and end up collecting the one from base system's installation - can you verify that by opening `build/<name>/Analysis-00.toc` and finding the entry for `libpython3.12.so`?

@rokm sure:

```
 [('libpython3.12.so', '/lib/x86_64-linux-gnu/libpython3.12.so', 'BINARY'),
```

Looks like you're right.
