### ISSUE TITLE
My program can run when not packaged, packaged after running error, win32 dependency can not be found

### ISSUE THREAD

**Issue by miaopass-future** [pyinstaller/pyinstaller#8806]
python 3.10.1
pyinstaller==6.10.0
windows 10
![image](https://github.com/user-attachments/assets/150e70ec-ab9e-4bae-9925-45ae9774b068)

My program can run when not packaged, packaged after running error, win32 dependency can not be found

**Comment by rokm** [comment]
Can we see the full error traceback?

**Comment by miaopass-future** [comment]
I operate the way there is a problem, should not be pyinstaller's problem, sorry
