### ISSUE TITLE
VM initialization error appears when executing the executable program generated by PyInstaller

### ISSUE THREAD

**Issue by Aloha0424** [pyinstaller/pyinstaller#8807]
I am using PyLucene (which depends on JDK) in Python, and it works correctly in the VSCode IDE and when executed locally. However, when I package it with PyInstaller and run it, I keep getting the error: 'Error occurred during initialization of VM: Failed setting boot class path.'

When I remove the PyLucene-related code from the test code in main.py, it runs normally. Therefore, I suspect that the code packaged by PyInstaller cannot start the JVM. I have already checked the JDK configuration repeatedly.

I added the JRE path in the spec file and configured the environment variables in the runtime-hooks.
`datas=[
        ("/Library/Java/JavaVirtualMachines/temurin-21.jre/Contents/Home", "jre"),]`

```python
import os
os.environ['JAVA_HOME'] = os.path.join(os.path.dirname(__file__), 'jre')
os.environ['PATH'] = os.path.join(os.environ['JAVA_HOME'], 'bin')  + os.pathsep + os.environ['PATH']
if not os.environ.get('CLASSPATH'):
    os.environ['CLASSPATH'] = ''
os.environ['CLASSPATH'] = os.path.join(os.environ['JAVA_HOME'], 'lib', '*') + os.pathsep + os.environ['CLASSPATH']

print('JAVA_HOME=', os.environ['JAVA_HOME'])
print('PATH=', os.environ['PATH'])
print('CLASSPATH=', os.environ['CLASSPATH'])
```

enrionment and versions:

- os: macos 14.4 (23E214)
- python: 3.11
- pyinstaller: 6.10.0
- pylucene: 9.10.0
- jdk: 
```
java -version
openjdk version "21.0.4" 2024-07-16 LTS
OpenJDK Runtime Environment Temurin-21.0.4+7 (build 21.0.4+7-LTS)
OpenJDK 64-Bit Server VM Temurin-21.0.4+7 (build 21.0.4+7-LTS, mixed mode)```

**Comment by rokm** [comment]
Are you building .app bundle or POSIX executable?

Does it work if instead to collected copy of jre you point it to the system one?

Does it work if instead of collecting `jre` via PyInstaller's `datas`, you manually copy the `jre` directory into frozen application after it is built (i.e., so that PyInstaller's binary processing is completely bypassed)?

**Comment by Aloha0424** [comment]
1. For "Are you building .app bundle or POSIX executable?", I am building POSIX executable.
2. For "Does it work if instead to collected copy of jre you point it to the system one?", No, it's still not work. Here is some log
```
JAVA_HOME= /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home
PATH= /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/yuenwill/miniconda3/envs/everdent-remio/bin:/Users/yuenwill/miniconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/yuenwill/bin:/opt/homebrew/bin/:
CLASSPATH= /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home/lib/*:
Error occurred during initialization of VM
Failed setting boot class path.
```
3. For "Does it work if instead of collecting jre via PyInstaller's datas, you manually copy the jre directory into frozen application after it is built (i.e., so that PyInstaller's binary processing is completely bypassed)?", No, it's still not work. Here is some log
```
(everdent-remio) yuenwill@192 release % cp -r /Library/Java/JavaVirtualMachines/temurin-21.jdk/Contents/Home/ dist/test/_internal/jdk 
(everdent-remio) yuenwill@192 release % ls dist/test/_internal/jdk 
NOTICE	bin	conf	include	jmods	legal	lib	man	release
(everdent-remio) yuenwill@192 release % ./dist/test/test 
JAVA_HOME= /Users/yuenwill/work/remio/release/dist/test/_internal/jdk
PATH= /Users/yuenwill/work/remio/release/dist/test/_internal/jdk/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/yuenwill/miniconda3/envs/everdent-remio/bin:/Users/yuenwill/miniconda3/condabin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/Library/Apple/usr/bin:/Users/yuenwill/bin:/opt/homebrew/bin/:
CLASSPATH= /Users/yuenwill/work/remio/release/dist/test/_internal/jdk/lib/*:
Error occurred during initialization of VM
Failed setting boot class path.
```

Any other tips?

**Comment by Aloha0424** [comment]
Here is my demo code.
[lucene_demo.zip](https://github.com/user-attachments/files/17179203/lucene_demo.zip)

**Comment by rokm** [comment]
Hmm, I think the problem here is that we collect a copy of `libjvm.dylib`  into top-level application directory (as a result of binary dependency analysis), and this then messes up the Java classes seaerch paths.

Can you try removing `_internal/libjvm.dylib` and replace it with symlink that points to `jre/lib/server/libjvm.dylib`? You might need to also replace `_internal/libjava.dylib` with symlink to `jre/lib/libjava.dylib`.

The example then starts for me without runtime hook.

(But I did also have to copy `JCC-3.14-py3.11-macosx-10.9-universal2.egg` because there is a hardcoded path to the .egg somewhere, and the lack of it was causing a segfault on both linux and macOS; and I build `lucene` in "modern" variant, so it was not an .egg - although I doubt this has any impact on this issue)

**Comment by Aloha0424** [comment]
> replace _internal/libjvm.dylib with symlink to jre/lib/server/libjvm.dylib
> replace _internal/libjava.dylib with symlink to jre/lib/libjava.dylib


This works! Thank you very much! This problem has been troubling me for at least three days.
