### ISSUE TITLE
Package dynamic library excluded by global exclusion rules (numpy.libs, pandas.libs, etc.)

### ISSUE THREAD

**Issue by eickr** [pyinstaller/pyinstaller#8810]
## Description of the issue

Dynamic libraries for packages such as numpy will not be collected if the virtual environment exists under certain paths.
For Windows platforms, this includes situations where your virtual environment is underneath the Windows directory for any reason.

This issue affects various versions of third party packages that generate dynamic libraries when they are installed, such as numpy, pandas, etc.. For reproduction of the error I recommend numpy v1.26.4.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.10.0```
* Version of Python: `3.11.9`
* Platform: `Windows Server 2019 Datacenter`
* How you installed Python: `python.org/downloads executable installer`
* Did you also try this on another platform? Does it work there? `Issue is specific to Windows OS, but theoretically could occur on other platforms`.
* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import numpy

if __name__ == "__main__":
    pass
```

### Stacktrace / full error message

```
Traceback (most recent call last):
  File "numpy\core\__init__.py", line 24, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "numpy\core\multiarray.py", line 10, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "numpy\core\overrides.py", line 8, in <module>
ImportError: DLL load failed while importing _multiarray_umath: The specified module could not be found.
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "numpy\__init__.py", line 144, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "numpy\__config__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "numpy\core\__init__.py", line 50, in <module>
ImportError: 
IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Importing the numpy C-extensions failed. This error can happen for
many reasons, often due to issues with your setup or how NumPy was
installed.
We have compiled some common reasons and troubleshooting tips at:
    https://numpy.org/devdocs/user/troubleshooting-importerror.html
Please note and check the following:
  * The Python version is: Python3.11 from "C:\GitLab-Runner\builds\REDACTED\simpletest\dist\simpletest\simpletest.exe"
  * The NumPy version is: "1.26.4"
and make sure that they are the versions you expect.
Please carefully study the documentation linked above for further help.
Original error was: DLL load failed while importing _multiarray_umath: The specified module could not be found.
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "cli.py", line 2, in <module>
    import numpy
  File "PyInstaller\loader\pyimod02_importers.py", line 378, in exec_module
  File "numpy\__init__.py", line 149, in <module>
ImportError: Error importing numpy: you should not try to import numpy from
        its source directory; please exit the numpy source tree, and relaunch
        your python interpreter from there.
[PYI-26728:ERROR] Failed to execute script 'cli' due to unhandled exception!
```

### PyInstaller Build Debug Log Snippet

```
608 INFO: PyInstaller: 6.10.0, contrib hooks: 2024.8
608 INFO: Python: 3.11.9
880 INFO: Platform: Windows-10-10.0.17763-SP0
880 INFO: Python environment: C:\Windows\System32\config\systemprofile\AppData\Local\pypoetry\Cache\virtualenvs\simpletest-2HIaBwPf-py3.11
...removed for brevity...
891 INFO: Module search paths (PYTHONPATH):
['C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Scripts\\pyinstaller.exe',
 'C:\\Python311\\python311.zip',
 'C:\\Python311\\DLLs',
 'C:\\Python311\\Lib',
 'C:\\Python311',
 'C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11',
 'C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages',
 'C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages\\setuptools\\_vendor',
 'C:\\GitLab-Runner\\builds\\REDACTED\\simpletest']
468 DEBUG: discover_hook_directories: Hook directories: ['C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages\\numpy\\_pyinstaller', 'C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages\\_pyinstaller_hooks_contrib\\stdhooks', 'C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages\\_pyinstaller_hooks_contrib']
2511 INFO: checking Analysis
...removed for brevity...
20369 INFO: Looking for dynamic libraries
C:\Windows\System32\config\systemprofile\AppData\Local\pypoetry\Cache\virtualenvs\simpletest-2HIaBwPf-py3.11\Lib\site-packages\PyInstaller\building\build_main.py:207: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
21740 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages\\numpy.libs']
21741 INFO: Extra DLL search directories (PATH): []
...removed for brevity...
24093 DEBUG: Analyzing binary 'C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages\\numpy\\core\\_multiarray_umath.cp311-win_amd64.pyd'
...removed for brevity...
24373 DEBUG: Processing dependency, name: 'libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll', resolved path: 'C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages\\numpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll'
24373 DEBUG: Skipping dependency 'C:\\Windows\\System32\\config\\systemprofile\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\simpletest-2HIaBwPf-py3.11\\Lib\\site-packages\\numpy.libs\\libopenblas64__v0.3.23-293-gc2f4bdbb-gcc_10_3_0-2bde3a66a51006b2b53eb373ff767a3f.dll' due to global exclusion rules.
```

### Workarounds

You can explicitly tell pyinstaller to include the libs directory with the `--add-data` argument. This works, but is undesirable as a general solution because you first have to realize the libs are being excluded on a case by case basis.

You can put your virtual environment somewhere else so that it isn't running afoul of the global exclusion rules. If you can do it, this works. But sometimes things are out of your control.

### Thoughts on fixing the issue in PyInstaller

The offending part of the source code is pyinstaller/PyInstaller/depend/dylib.py's `WinExcludeList` class, which excludes everything under the Windows directory. However, theoretically this issue could occur with other blanket directory exclusions.

I'm not sure if there's an effective and performant way to except dynamic libraries from these blanket exclusions. But given the virtual environment is known to the analysis, perhaps these blanket exclusions can merely except it?

**Comment by rokm** [comment]
I suppose anything in `C:\WINDOWS\system32\config\systemprofile` (which should be returned by `pathlib.Path.home()`) is fair game in this scenario...

So `WinExcludeList` constructor could check if `pathlib.Path.home()` is sub-directory of `winutils.get_windows_dir()`, and do an extra check to overturn exclusion if necessary.
