### ISSUE TITLE
exec_module try to load json as json.py

### ISSUE THREAD

**Issue by chengchu88** [pyinstaller/pyinstaller#8811]
Hello sir,
I got an error as below when running the .exe, and has been trying with all sort of .spec file trick, but still the pyinstaller want to 'import json' as json.py, while the json is simply a built-in package of the python. The error message is as below:

and i have added the following to the .spec file:

datas += collect_data_files('json')
and 
    hiddenimports=['json'],

but still not working. I'd appreciate it if you could give me some directions how to solve this issue.

thank  you!

**Comment by rokm** [comment]
The error message is missing...

**Comment by chengchu88** [comment]
sorry, I thought I pasted it.
here it is:

Traceback (most recent call last):
  File "_pyinstaller_hooks_contrib\rthooks\pyi_rth_nltk.py", line 14, in
<module>
  File "PyInstaller\loader\pyimod02_importers.py", line 379, in exec_module
  File "nltk\__init__.py", line 138, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 379, in exec_module
  File "nltk\text.py", line 30, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 379, in exec_module
  File "nltk\tokenize\__init__.py", line 89, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 379, in exec_module
  File "nltk\tokenize\stanford_segmenter.py", line 15, in <module>
  File "PyInstaller\loader\pyimod02_importers.py", line 379, in exec_module
  File "json.py", line 15, in <module>
ImportError: attempted relative import with no known parent package
[PYI-2552:ERROR] Failed to execute script 'pyi_rth_nltk' due to unhandled
exception!

**Comment by rokm** [comment]
Try opening `build/<name>/Analysis-00.toc` and find the entry for `json.py` to see where it was collected from (it is likely some other module than stdlib's json).

What is your project's directory structure? Do you have a `json.py` file located next to your entry-point script?

**Comment by chengchu88** [comment]
Hello Rok,
Indeed, here is the 'json' line:
('json',

 'C:\\Users\\5158\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pydantic\\deprecated\\json.py',
   'PYMODULE'),

How can I mitigate this issue?

thanks,

**Comment by rokm** [comment]
I think the only way for that module to become treated as top-level `json` module is if `C:\\Users\\5158\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pydantic\\deprecated` is added to python search path; either via `PYTHONPATH` environment variable, or via pyinstaller's `--path` option (or its `pathex` .spec file equivalent). Is that the case - are you modifying search paths?

**Comment by chengchu88** [comment]
Hello Rok,
Thank you for the reply. I think instead of using the
 ('json',

 'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\pydantic\\deprecated\\json.py',)
as the python module, I need the 'import json' to use the python built-in
json module, so it should look like this:
('json',

 'C:\\Users\\xxxx\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\json\\__init__.py',
   'PYMODULE'),

(note: i got the pyinstaller to produce the correct json result in the .toc
file by messing up the pydantic\\deprecated\\json.py, however this will
result in other error.)

Is there a way to force pyinstaller to use
Python\\Python311\\Lib\\json\\__init__.py' as the json module?

Thanks!

**Comment by rokm** [comment]
Can you rebuild with added `--clean` option and paste the build log here so we can see what is going on during the build? If you are building using a spec file, please paste that as well.
