### ISSUE TITLE
cygwin build failed for pyinstaller 6.10

### ISSUE THREAD

**Issue by timofey-retailnext** [pyinstaller/pyinstaller#8814]
applicable to 6.8-6.10 and develop branch:

      [19/21] Compiling src/main.c
      ../../src/pyi_main.c: In function ‘pyi_main’:
      ../../src/pyi_main.c:410:9: error: ‘ret’ undeclared (first use in this function)
        410 |         ret = cygwin_conv_path(CCP_POSIX_TO_WIN_W | CCP_RELATIVE, pyi_ctx->application_home_dir, dllpath_w, PYI_PATH_MAX);
            |         ^~~
      ../../src/pyi_main.c:410:9: note: each undeclared identifier is reported only once for each function it appears in

      Waf: Leaving directory `/tmp/pip-install-fjdd4f0p/pyinstaller_280306b2082a4db59eb280efd05c2f18/bootloader/build/debug'
      Build failed
       -> task in 'OBJECTS' failed with exit status 1 (run with -v to display more information)

syntax error: need to declare "int ret" before usage in the function

**Comment by rokm** [comment]
Thanks for the report! Should be fixed by #8815.

If you run into additional issues with Cygwin, let us know - it is one of the (nominally supported) platforms that are relatively poorly tested...
