### ISSUE TITLE
Compile error installing on AIX 7.2

### ISSUE THREAD

**Issue by pcudmore** [pyinstaller/pyinstaller#8819]
Trying to install Pyinstaller on AIX 7.2. When I run python3 -m pip install Pyinstaller it gives the following error when it tries to compile the bootloader:

>   [14/21] Compiling src/pyi_path.c
  ../../src/pyi_pythonlib.c: In function 'pyi_pylib_load':
  ../../src/pyi_pythonlib.c:71:13: error: 'dllname' undeclared (first use in this function); did you mean 'dll_name'?
     71 |             dllname,
        |             ^~~~~~~
        |             dll_name
  ../../src/pyi_pythonlib.c:71:13: note: each undeclared identifier is reported only once for each function it appears in
  ../../src/pyi_pythonlib.c:72:13: error: 'DLLNAME_LEN' undeclared (first use in this function); did you mean 'MAX_DLL_NAME_LEN'?
     72 |             DLLNAME_LEN,
        |             ^~~~~~~~~~~
        |             MAX_DLL_NAME_LEN
  

If I make the changes suggested by the compiler and manually compile it then the errors go away. I don't know if this is the correct solution.

**Comment by rokm** [comment]
Thanks for the report!

> I don't know if this is the correct solution.

It is. The names of those variables changed during refactor in v6.8, but I missed couple of them inside that `#ifdef AIX` block.
