### ISSUE TITLE
Anuga and mpi4py problem

### ISSUE THREAD

**Issue by mikilterribile** [pyinstaller/pyinstaller#8825]
Hi everyone,

I'm trying to freeze my environment and scripts into an application using PyInstaller. I have several packages and a very long script, but I've isolated the problem down to a minimal example.

I'm attempting to freeze Anuga, which has mpi4py as a dependency. I really need mpi4py (I cannot exclude it) to perform parallel computations with Anuga, but PyInstaller is giving me the following error:

```
...
128923 INFO: Including run-time hook 'pyi_rth_pywintypes.py' from 'C:\\Users\\miche\\anaconda3\\envs\\ambiente_switch2\\lib\\site-packages\\_pyinstaller_hooks_contrib\\rthooks'    
128925 INFO: Including run-time hook 'pyi_rth_pythoncom.py' from 'C:\\Users\\miche\\anaconda3\\envs\\ambiente_switch2\\lib\\site-packages\\_pyinstaller_hooks_contrib\\rthooks'     
128926 INFO: Including run-time hook 'pyi_rth_cryptography_openssl.py' from 'C:\\Users\\miche\\anaconda3\\envs\\ambiente_switch2\\lib\\site-packages\\_pyinstaller_hooks_contrib\\rthooks'
128929 INFO: Including run-time hook 'pyi_rth_osgeo.py' from 'C:\\Users\\miche\\anaconda3\\envs\\ambiente_switch2\\lib\\site-packages\\_pyinstaller_hooks_contrib\\rthooks'
129344 INFO: Looking for dynamic libraries
C:\Users\miche\anaconda3\envs\ambiente_switch2\lib\site-packages\PyInstaller\building\build_main.py:207: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
Abort(1090447) on node 0 (rank 0 in comm 0): Fatal error in PMPI_Init_thread: Unknown error class, error stack:
MPIR_Init_thread(192)........:
MPID_Init(1645)..............:
MPIDI_OFI_mpi_init_hook(1574):
(unknown)(): Unknown error class
[unset]: write_line error; fd=-1 buf=:cmd=abort exitcode=1090447
...
```

In the past, I faced a similar issue, and the PyInstaller community suggested dynamically importing the libfabric.dll library with the following code (as a .py file in the extra-hooks folder), which resolved the problem at that time.

```python
# extra-hooks/hook-mpi4py.py
from PyInstaller.utils.hooks import get_installer, logger

binaries = []

if get_installer('mpi4py') == 'conda':
    from PyInstaller.utils.hooks import conda
    
    # conda-forge builds of `mpi4py` depend on `impi_rt`, from which we need to collect dynamically-loaded
    # `Library/bin/libfabric/libfabric.dll`. The main conda channel builds depend on `msmpi`, which does not seem to
    # require any extra collection steps.
    try:
        impi_rt_files = conda.files('impi_rt')
    except ImportError:
        pass
    
    for impi_rt_file in impi_rt_files:
        if impi_rt_file.name != 'libfabric.dll':
            continue
        impi_rt_file = impi_rt_file.locate()
        logger.info("hook-mpi4py: collecting %r", str(impi_rt_file))
        binaries += [(str(impi_rt_file), '.')]
```

However, with the updated versions of my packages, this solution no longer seems to work, and I still get the same error as reported above. These are the versions of my Python and packages:

Python: 3.10.14
Anuga: 3.1.9
mpi4py: 3.1.6

Here is the minimal example I'm trying to freeze:

```python
# minimal_example.py
import anuga

print("This is a minimal example")
```

I would greatly appreciate any help or suggestions to resolve this issue.

Thank you in advance for your assistance.

Best regards,
Michele Zucchelli

**Comment by rokm** [comment]
In contrast to #8447, which was a run-time error, this one seems to be a build-time. Specifically, it seems to happen during package imports prior to binary dependency analysis, so one of the packages seems to be trying to perform MPI initialization during its import. 

Does it help if you add `anuga` and/or `mpi4py` to `suppressed_imports` list here? https://github.com/pyinstaller/pyinstaller/blob/2ebca31568e4d84371845a9358245aa4b2de0337/PyInstaller/building/build_main.py#L272-L280

**Comment by rokm** [comment]
You could also try to add a `print(package)` before this call

https://github.com/pyinstaller/pyinstaller/blob/2ebca31568e4d84371845a9358245aa4b2de0337/PyInstaller/building/build_main.py#L286

to see which package is causing MPI initialization.

But actually, does this error abort the build or not?

**Comment by mikilterribile** [comment]
Yes, sorry for the delay. Your first suggestion fixed the problem. Adding
suppressed_imports += ["anuga", "mpi4py"] to build_main.py worked perfectly.
Many thanks for your kindness.
Best regards,
Michele Zucchelli
