### ISSUE TITLE
Speed up pyinstaller build / bundle time

### ISSUE THREAD

**Issue by lorinczszabolcs** [pyinstaller/pyinstaller#8832]
**Is your feature request related to a problem? Please describe.**
Performing binary vs. data reclassification takes ~20-30 minutes out of the total ~45-50 minutes.

**Describe the solution you'd like**
I've seen in #7659 , that it might be possible to parallelize binary dependency scanning, but as I'm unfamiliar with the topic, I'm not sure if that's the same part as the one described above. If it is, it might still be useful considering parallelizing it.

**Comment by rokm** [comment]
Assuming you are talking about Windows, have you tried dowgrading `pefile` as per #8762?

**Comment by lorinczszabolcs** [comment]
That was it ⚡️ Thank you!
