### ISSUE TITLE
Set EXE version in Spec file

### ISSUE THREAD

**Issue by nickanthony-dgl** [pyinstaller/pyinstaller#8833]
I would like to have Pyinstaller generate an .EXE that has its version metadata populated. I can see that there is the [`--version-file`](https://pyinstaller.org/en/stable/usage.html#cmdoption-version-file) commandline option, however I can't use this with a spec file because I get an error: "makespec options not valid when a .spec file is given".

Is there some way that I can provide a version file from within my Spec file?

**Comment by rokm** [comment]
You can add `version='filename'` argument to the `EXE` in the spec file.

**Comment by nickanthony-dgl** [comment]
Thanks. Do you know if there is any documentation for `EXE` that covers this?

**Comment by rokm** [comment]
Hmm, doesn't look like it. The section on [Windows version data](https://pyinstaller.org/en/stable/usage.html#capturing-windows-version-data) is also somewhat out-of-date.

In general, if you want to find out how command-line options map into generated spec file, it is usually best to just generate a new spec with added command line options and see what has changed.

**Comment by nickanthony-dgl** [comment]
Ok, thanks.
