### ISSUE TITLE
Pyinstaller: An unexpected error occurred: [WinError 2] The system cannot find the file specified when running the exe file

### ISSUE THREAD

**Issue by mattchai** [pyinstaller/pyinstaller#8847]
An unexpected error occurred: [WinError 2] The system cannot find the file specified

1. create a project with a virtual environment on pycharm.
2. pip install openvino
3. pip install pyinstaller

There is no any error when run below commands, but get error "An unexpected error occurred: [WinError 2] The system cannot find the file specified" when running the exe file.

pyinstall -D --collect-submodules openvino --collect-binaries openvino --collect-data openvino xxx.py
or 
pyinstaller --onefile --add-data="./model/:model" --collect-submodules openvino --collect-binaries openvino --collect-data openvino xxx.py

here is my py file:
```python
import subprocess
import os
from datetime import datetime
from get_current_dir import get_current_dir


def npu_latency():
    # Path to the ONNX model
    # model_path = "resnet50_fp32.onnx"
    model_path = get_current_dir("model", "resnet50_fp32_qdq.onnx")

    # 获取当前时间并格式化为字符串
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")

    # Construct the command as a list of arguments
    command = [
        "benchmark_app",
        "-m", model_path,
        "-d", "NPU",
        "-hint", "latency"
    ]

    try:
        # Run the command
        result = subprocess.run(command, capture_output=True, text=True)

        # Print the output to the console
        print("STDOUT:")
        print(result.stdout)
        print("STDERR:")
        print(result.stderr)

        # Write the stdout to a text file
        output_file_path = "benchmark_output_npu_throughput.txt"
        # 获取文件名和扩展名
        filename_without_ext, file_extension = os.path.splitext(output_file_path)

        # 生成带有时间戳的新文件名
        new_filename = filename_without_ext + "_" + timestamp + file_extension


        with open(new_filename, "w") as file:
            file.write(result.stdout)

        print(f"Output has been written to {output_file_path}")

    except subprocess.CalledProcessError as e:
        print(f"Error running benchmark_app: {e}")
        print("STDOUT:")
        print(e.stdout)
        print("STDERR:")
        print(e.stderr)

    except Exception as e:
        print(f"An unexpected error occurred: {e}")

if __name__ == "__main__":
    npu_latency()
    user_input = input("请输入内容 (输入 Q 退出): ")
```

here is project structure in pycharm:
![image](https://github.com/user-attachments/assets/719e6626-3323-431b-8bfe-97c6a22c4d28)

**Comment by rokm** [comment]
That ` [WinError 2] The system cannot find the file specified"` is very likely raised by `subprocess.run()` because the program/script you are trying to run (`benchmark_app`) cannot be found.

Seeing how `benchmark_app` is an entry-point script of `openvino`, you will not be able to collect it as-is, either (because its executable is only a shim that fully depends on the actual python environment it was installed in).
