### ISSUE TITLE
using pyinstaller and splash screen problem with uv

### ISSUE THREAD

**Issue by emcek** [pyinstaller/pyinstaller#8849]
## Description of the issue
When my app using splashscreen:
```python
try:
    import pyi_splash
    pyi_splash.close()
except ImportError:
    pass
```
and part of `spec` file:
```spec
...
splash = Splash(
    'src/dcspy/img/splash.png',
    binaries=a.binaries,
    datas=a.datas,
    text_pos=None,
    text_size=12,
    minify_script=True,
    always_on_top=True,
)
...
```

I got error after `pyinstaller dcspy_cli.spec`:
```console
...
37107 INFO: TclTkInfo: initializing cached Tcl/Tk info...
Your platform does not support the splash screen feature, since tkinter is not installed. Please install tkinter and try again.
...
```
This is problem with `uv` detecting `tk/tkinker`: astral-sh/uv#7036, there is workaround:

```python
import sys
import os
os.environ["TCL_LIBRARY"] = os.path.join(sys.base_prefix, "tcl", "tcl8.6")
os.environ["TK_LIBRARY"] = os.path.join(sys.base_prefix, "tcl", "tk8.6")
```

When I put change `.venv/Lib/site-packages/PyInstaller/utils/hooks/tcl_tk.py`:
```diff
@isolated.decorate
def _get_tcl_tk_info():
    """
    Isolated-subprocess helper to retrieve the basic Tcl/Tk information:
     - tkinter_extension_file = the value of __file__ attribute of the _tkinter binary extension (path to file).
     - tcl_data_dir = path to the Tcl library/data directory.
     - tcl_version = Tcl version
     - tk_version = Tk version
     - tcl_theaded = boolean indicating whether Tcl/Tk is built with multi-threading support.
    """
+    import sys
+    import os
+    os.environ["TCL_LIBRARY"] = os.path.join(sys.base_prefix, "tcl", "tcl8.6")
+    os.environ["TK_LIBRARY"] = os.path.join(sys.base_prefix, "tcl", "tk8.6")
    try:
        import tkinter
        import _tkinter
    except ImportError:
        # tkinter unavailable
        return None
```
it worked:
```console
...
37848 INFO: Collect Tcl/Tk data files for the splash screen
37900 INFO: checking Splash
37900 INFO: Building Splash because Splash-00.toc is non existent
37900 INFO: Building Splash D:\Projects\dcspy_dev\build\dcspy_cli\Splash-00.res
...
```
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11```
* Version of Python: 3.13
* Platform: Windows (language en)
* How you installed Python: uv
* Did you also try this on another platform? Does it work there? this is problem with `uv`

### Notes
Of course this not PyInstaller issue, but `uv` get huge momentum, so maybe there is small chance to make some workaround (more fancy and platform agnostic) in PyInstaller.

**Comment by rokm** [comment]
> Of course this not PyInstaller issue, but uv get huge momentum, so maybe there is small chance to make some workaround (more fancy and platform agnostic) in PyInstaller.

Nope, I see no reason why we would be working around this in PyInstaller. 

If you need to set `TCL_LIBRARY` and `TK_LBIRARY` environment variables to have usable `tkinter` in your environment, then it is up to you to ensure those are set before you run PyInstaller.
