### ISSUE TITLE
Default icons are no longer packaged with macOS wheel

### ISSUE THREAD

**Issue by MatteoH2O1999** [pyinstaller/pyinstaller#8855]
When trying to build a `--windowed` application with Pyinstaller 6.11.0 i noticed that it could not find the default icon anymore (see Github Actions [build logs](https://github.com/MatteoH2O1999/medium_scale_combat_5e/actions/runs/11452878983/job/32250922139)).
I then checked the downloaded wheel for both 6.11.0 and 6.10.0 with an archive viewer and noticed that the icons are no longer being packaged (see [wheels](https://github.com/user-attachments/files/17564344/wheels.zip) in folder `PyInstaller/bootloader` the 6.10.0 one has `Darwin-64bit` and `images` folders, while the 6.11.0 only has the `Darwin-64bit` folder).

**Comment by bwoodsend** [comment]
Thanks. Guess it was too much to hope for that #8805 would make it without breaking something. I was amazed it's survived this lightly.

**Comment by bwoodsend** [comment]
Slightly underwhelming cause.
https://github.com/pyinstaller/pyinstaller/blob/0779daae400daa4066f91dd634cc731608b901ed/setup.py#L104-L105
I spelt `icns` wrong.
