### ISSUE TITLE
_tcl_data not found

### ISSUE THREAD

**Issue by Zebulee** [pyinstaller/pyinstaller#8856]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11.0```
* Contrib hooks: 2024.9
* Version of Python: 3.13.0
* Platform: Windows-11-10.0.22631-SP0
* How you installed Python: python.org/downloads
* Did you also try this on another platform? Does it work there? did not test on other platform

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [X] start with clean installation
  * [X] use the latest development version
  * [X] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [X] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [X] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
from tkinter import Tk, filedialog

root = Tk()
root.withdraw()
filename = filedialog.asksaveasfilename(defaultextension=".csv", filetypes=[("CSV files", "*.csv")])
if filename:
    with open(filename, mode='w', newline='') as file:
        writer = csv.writer(file)
        writer.writerow(['Barcode', 'Time'])  # Header
        for barcode, time in list_barcodes:
            writer.writerow([barcode, time])          
root.destroy()
```

### Stacktrace / full error message

```
[PYI-3896:DEBUG] LOADER: running pyi_rth__tkinter.py
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 36, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 28, in _pyi_rthook
FileNotFoundError: Tcl data directory "C:\Program Files (x86)\CC\CodeChrono\_internal\_tcl_data" not found.
[PYI-3896:ERROR] Failed to execute script 'pyi_rth__tkinter' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by Zebulee** [comment]
Full Debug of the frozen program:
[PYI-3896:DEBUG] PyInstaller Bootloader 6.x
[PYI-3896:DEBUG] LOADER: executable file: C:\Program Files (x86)\CC\CodeChrono\CodeChrono.exe
[PYI-3896:DEBUG] LOADER: trying to load executable-embedded archive...
[PYI-3896:DEBUG] LOADER: attempting to open archive C:\Program Files (x86)\CC\CodeChrono\CodeChrono.exe
[PYI-3896:DEBUG] LOADER: cookie found at offset 0x286673
[PYI-3896:DEBUG] LOADER: archive file: C:\Program Files (x86)\CC\CodeChrono\CodeChrono.exe
[PYI-3896:DEBUG] LOADER: application has onedir semantics...
[PYI-3896:DEBUG] LOADER: _PYI_ARCHIVE_FILE not defined...
[PYI-3896:DEBUG] LOADER: process level = 1
[PYI-3896:DEBUG] LOADER: application's top-level directory: C:\Program Files (x86)\CC\CodeChrono\_internal
[PYI-3896:DEBUG] LOADER: calling SetDllDirectory: C:\Program Files (x86)\CC\CodeChrono\_internal
[PYI-3896:DEBUG] LOADER: splash screen is unavailable.
[PYI-3896:DEBUG] LOADER: loading Python shared library: C:\Program Files (x86)\CC\CodeChrono\_internal\python313.dll
[PYI-3896:DEBUG] LOADER: loaded functions from Python shared library.
[PYI-3896:DEBUG] LOADER: pre-initializing embedded python interpreter...
[PYI-3896:DEBUG] LOADER: creating PyConfig structure...
[PYI-3896:DEBUG] LOADER: initializing interpreter configuration...
[PYI-3896:DEBUG] LOADER: setting program name...
[PYI-3896:DEBUG] LOADER: setting python home path...
[PYI-3896:DEBUG] LOADER: setting module search paths...
[PYI-3896:DEBUG] LOADER: setting sys.argv...
[PYI-3896:DEBUG] LOADER: applying run-time options...
[PYI-3896:DEBUG] LOADER: starting embedded python interpreter...
[PYI-3896:DEBUG] LOADER: setting sys._MEIPASS
[PYI-3896:DEBUG] LOADER: importing modules from PKG/CArchive
[PYI-3896:DEBUG] LOADER: extracted struct
[PYI-3896:DEBUG] LOADER: running unmarshalled code object for module struct...
[PYI-3896:DEBUG] LOADER: extracted pyimod01_archive
[PYI-3896:DEBUG] LOADER: running unmarshalled code object for module pyimod01_archive...
[PYI-3896:DEBUG] LOADER: extracted pyimod02_importers
[PYI-3896:DEBUG] LOADER: running unmarshalled code object for module pyimod02_importers...
[PYI-3896:DEBUG] LOADER: extracted pyimod03_ctypes
[PYI-3896:DEBUG] LOADER: running unmarshalled code object for module pyimod03_ctypes...
[PYI-3896:DEBUG] LOADER: extracted pyimod04_pywin32
[PYI-3896:DEBUG] LOADER: running unmarshalled code object for module pyimod04_pywin32...
[PYI-3896:DEBUG] LOADER: looking for PYZ archive TOC entry...
[PYI-3896:DEBUG] LOADER: path to PYZ archive stored into sys._pyinstaller_pyz...
[PYI-3896:DEBUG] LOADER: running pyiboot01_bootstrap.py
[PYI-3896:DEBUG] LOADER: running pyi_rth_usb.py
[PYI-3896:DEBUG] LOADER: running pyi_rth_inspect.py
[PYI-3896:DEBUG] LOADER: running pyi_rth__tkinter.py
Traceback (most recent call last):
  File "PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 36, in <module>
  File "PyInstaller\hooks\rthooks\pyi_rth__tkinter.py", line 28, in _pyi_rthook
FileNotFoundError: Tcl data directory "C:\Program Files (x86)\CC\CodeChrono\_internal\_tcl_data" not found.
[PYI-3896:ERROR] Failed to execute script 'pyi_rth__tkinter' due to unhandled exception!
[PYI-3896:DEBUG] LOADER: ERROR.
[PYI-3896:DEBUG] LOADER: manually flushing stdout and stderr...
[PYI-3896:DEBUG] LOADER: cleaning up Python interpreter...
[PYI-3896:DEBUG] LOADER: unloading Python shared library...
[PYI-3896:DEBUG] LOADER: end of process reached!

**Comment by rokm** [comment]
Are you building using a virtual environment with python 3.13.0? If that's the case, you might be running into #8820.

**Comment by Zebulee** [comment]
Yes, I am building from a virtual env. Thank you for the link.

Should I try building it in global instead of venv ? or change the version of python?

**Comment by rokm** [comment]
> Yes, I am building from a virtual env. Thank you for the link.
> 
> Should I try building it in global instead of venv ?

Yeah, as per links in #8820, tkinter is broken in general with Windows + python 3.13.0 + venv. Other python versions should work.

If you want to use 3.13.0, you will need to manually set `TCL_LIBRARY` and `TK_LIBRARY` environment before running PyInstaller.  (assuming you are running under `cmd` and not powershell):

```
set TCL_LIBRARY=[...]\Python313\tcl\tcl8.6
set TK_LIBRARY=[...]\Python313\tcl\tk8.6

pyinstaller ...
```
