### ISSUE TITLE
Qt OpenSSL DLLs are not loaded from the app directory if `pywin32` is also used

### ISSUE THREAD

**Issue by jonathanperret** [pyinstaller/pyinstaller#8857]
## Description of the issue

When packaging an app that uses some variant of PyQt/PySide (I encountered this using PySide6 6.6.2) for Windows, the OpenSSL DLLs that QtNetwork depends on (`libssl-3-x64.dll` and `libcrypto-3-x64.dll`) are [collected and copied](https://github.com/pyinstaller/pyinstaller/blob/0779daae400daa4066f91dd634cc731608b901ed/PyInstaller/utils/hooks/qt/__init__.py#L652) into the `_internal` (aka `sys._MEIPASS`) folder. And for Qt (specifically `qopensslbackend.dll`) to find them, a runtime hook prepends `_internal` to the `PATH`: https://github.com/pyinstaller/pyinstaller/blob/0779daae400daa4066f91dd634cc731608b901ed/PyInstaller/hooks/rthooks/pyi_rth_pyside6.py#L50-L53

This works fine in the simple case of an app that uses PySide and nothing else. However, in some cases the DLLs are not loaded from `_internal`, and worse, they can be loaded from any directory on the `PATH` that contains DLLs named identically. In our case we saw Qt load `libssl-3-x64.dll` from `C:\Program Files\HP\HP One Agent`, ending the program with an access violation because the DLLs were incompatible.

I tracked the issue down to the `PATH` not being correctly modified if a part of the path being prepended was already present in the current `PATH`. `prepend_path_to_environment_variable` does a simple `in` check on strings for the path to be added: https://github.com/pyinstaller/pyinstaller/blob/0779daae400daa4066f91dd634cc731608b901ed/PyInstaller/fake-modules/_pyi_rth_utils/__init__.py#L25-L29

So if a previous hook has added `C:\Program Files\my-app\_internal\foo` to the `PATH`, then `C:\Program Files\my-app\_internal` will never be added, preventing Qt from locating the appropriate DLLs.

And it turns out the runtime hook for `pywin32` does exactly that (not using `prepend_path_to_environment_variable `by the way): https://github.com/pyinstaller/pyinstaller/blob/0779daae400daa4066f91dd634cc731608b901ed/PyInstaller/loader/pyimod04_pywin32.py#L49-L56

Here's a bare-bones app that reproduces the issue in case it helps: https://github.com/jonathanperret/pyinstaller-path-issue

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.6.1```
* Version of Python: 3.11.9
* Platform: Windows 11
* How you installed Python: `python.org/downloads`
* Did you also try this on another platform? Does it work there?
  Other platforms are not affected, this is a Windows-specific issue

**Comment by rokm** [comment]
Thanks for initial analysis! Looks like `prepend_path_to_environment_variable` should split the string obtained from PATH, and then perform the "in" check on the list of substrings. This would ensure that only exact full path is matched, instead of potential prefix matches.

**Comment by jonathanperret** [comment]
> Thanks for initial analysis! Looks like `prepend_path_to_environment_variable` should split the string obtained from PATH, and then perform the "in" check on the list of substrings. This would ensure that only exact full path is matched, instead of potential prefix matches.

Yes, that’s how I would do it as well. Technically, prepending is only idempotent if the path you’re trying to prepend appears as the first in the existing list, but I suppose that’s enough of an edge case to let it slide.

Are you interested in a PR?

**Comment by jonathanperret** [comment]
> Are you interested in a PR?

Sorry, I did not see you already had one going.

**Comment by jonathanperret** [comment]
Note that for the affected project, I opted to entirely remove the OpenSSL QtNetwork backend: https://github.com/AllYarnsAreBeautiful/ayab-desktop/pull/723

In addition to avoiding the `PATH` issue documented here, this saves packaging a second copy (the first comes from Python itself under the names `libssl-3.dll` and `libcrypto-3.dll`) of the OpenSSL DLLs, which were of doubtful provenance anyway in my case (on a GitHub Actions runner, they were being picked up from `C:\Program Files\MySQL\MySQL Server 8.0\bin`!).

I've achieved this by deleting `qopensslbackend.dll` before running PyInstaller, but I wonder if there was an option I could have used to block that plugin from being collected.

Also, do you think it would be useful to have an easy way to prevent PyInstaller from packaging this plugin and the accompanying OpenSSL libraries? The native (`schannel`) Windows backend is probably sufficient for 99% of applications.

**Comment by rokm** [comment]
> I've achieved this by deleting `qopensslbackend.dll` before running PyInstaller, but I wonder if there was an option I could have used to block that plugin from being collected.

Right now, removing the plugin file from the build environment is in fact the only (or at least the most surefire) way.

I am/was planning to add options to include/exclude specific Qt plugins via the hooks configuration mechanism, but haven't gotten around to it yet...

While you could exclude the `qopensslbackend.dll` file by filtering `a.binaries` in the spec file after `Analysis` is instantiated and before its members are passed on to `EXE` and `COLLECT`, you would also need to filter out the corresponding SSL libs.

> (on a GitHub Actions runner, they were being picked up from `C:\Program Files\MySQL\MySQL Server 8.0\bin`!).

That's because we mimic the discovery mechanism used by `qopensslbackend.dll` - if you have those libs in `PATH`, we can only assume that you want them collected (because they would also be used by original python script running in that environment). But on the other hand, if you sanitized the `PATH` before the build and thus ended up not collecting OpenSSL libs, you would end up with `qopensslbackend.dll` that would attempt to load them from `PATH` at run-time (leading to issues like the one you originally described).

**Comment by jonathanperret** [comment]
Thanks for the reply, this makes sense. The `PATH` situation on Windows is really fraught. In a sense, it's lucky that the runners have the requested libs on the `PATH`, so that (with this issue fixed) at least a predictable library is loaded. But this does not solve the problem when a builder does not have these libraries around, you end up with a "time-bomb" package that will break on random machines.

Anyway, I just wanted to suggest that defaulting to excluding `qopensslbackend.dll` might do more good than harm. But I understand that this is not a decision you can take lightly.
