### ISSUE TITLE
"Tuple Index Out of Range" Error with PyInstaller and Pandas

### ISSUE THREAD

**Issue by linxiaoxiaobai** [pyinstaller/pyinstaller#8872]
I am experiencing a "tuple index out of range" error while attempting to package a Python script using PyInstaller. The script involves reading an Excel file using Pandas. The standalone script runs without issues directly in Python, but encounters this error once packaged.

Here are some details about the issue:

Environment:

Python version: Python 3.10.0
Pandas version: pandas version 2.2.3
PyInstaller version:PyInstaller version6.11.1
Operating System:win11
Steps to Reproduce:

Use the following script to read an Excel file named example.xlsx with a sheet named Sheet1.
Ensure example.xlsx contains data. In my case, it has several rows and columns filled with sample data.
Code Snippet:

python
import logging
import pandas as pd

def test_read_excel(file_path, sheet_name):
    logging.basicConfig(level=logging.DEBUG)
    try:
        df = pd.read_excel(file_path, sheet_name=sheet_name, header=None)
        logging.info(f"Excel file '{file_path}' read successfully.")
        logging.debug(f"DataFrame preview:\n{df.head()}")
        logging.debug(f"DataFrame shape: {df.shape}")
    except Exception as e:
        logging.error(f"Error reading Excel file: {e}")

test_read_excel('example.xlsx', 'Sheet1')
Problem Encountered:

When running the script directly using Python, it executes as expected, successfully logging the DataFrame preview and its shape.
After packaging with PyInstaller, the executable throws a "tuple index out of range" error.
Error Log:

Unfortunately, the error message does not provide additional details that could pinpoint the exact location or cause.
Additional Information:

I have ensured that the Excel file exists and the sheet name is correctly specified.
The DataFrame operations themselves do not seem to be the issue when run in a regular Python environment.
I would appreciate any insights or suggestions on what might be causing this issue when using PyInstaller. Could there be a missing dependency or configuration in my PyInstaller setup? Any help would be greatly appreciated. Thank you!

**Comment by bwoodsend** [comment]
See #6301. tl;dr It's a CPython bug. Use something other than 3.10.0.
