### ISSUE TITLE
OSError When Loading Fonts in PyInstaller Executable

### ISSUE THREAD

**Issue by NexTechQuantum** [pyinstaller/pyinstaller#8873]
When running my Python script directly, it functions as expected and loads fonts without any issues. However, when I package the script using PyInstaller and run the generated executable, I encounter an OSError: cannot open resource when attempting to load a .ttf font.

**Context information (for bug reports)**

- Output of pyinstaller --version: 6.11.0
- Version of Python: 3.13.0
- Platform: Microsoft Windows 11 Pro (Build 10.0.22631)
- Did you also try this on another platform? Does it work there?: Not tested on other platforms.

**Steps taken to troubleshoot**

- Used --add-data option to include the font file:
`pyinstaller --onefile --windowed --add-data "C:/Windows/Fonts/aldhabi.ttf;." ui.py`

- Applied a resource_path function for handling file paths in packaged executables:
```
def resource_path(relative_path):
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

font_path = resource_path("C:/Windows/Fonts/aldhabi.ttf")
```

- Moved the font file to the project directory and used:
`pyinstaller --onefile --windowed --add-data "aldhabi.ttf;." ui.py`

### example program which shows the error

```
import subprocess
import barcode
from barcode.writer import ImageWriter
from PIL import ImageFont
import sys
import os
import glob

def resource_path(relative_path):
    base_path = getattr(sys, '_MEIPASS', os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)

font_path = resource_path("arial.ttf") 
font = ImageFont.truetype(font_path, 15)


def get_system_uuid():
    result = subprocess.run(["powershell", "-Command", "Get-WmiObject Win32_ComputerSystemProduct | Select-Object -ExpandProperty UUID"], capture_output=True, text=True)
    return result.stdout.strip()

def find_available_font():
    # Check common font directories, including packaged directory
    font_dirs = [
        resource_path("Fonts"),  # Directory where fonts are included in the executable
        "C:/Windows/Fonts",  # Default Windows fonts directory
        os.path.dirname(sys.executable)  # Directory of the executable
    ]

    for font_dir in font_dirs:
        if os.path.exists(font_dir):
            for font_path in glob.glob(os.path.join(font_dir, "*.ttf")):
                try:
                    print(f"Trying to load font: {font_path}")
                    return ImageFont.truetype(font_path, 15)
                except Exception as e:
                    print(f"Failed to load font {font_path}: {e}")

    return None

def create_barcode(uuid):
    barcode_class = barcode.get_barcode_class('code128')
    writer = ImageWriter()

    # Attempt to find an available font
    font = find_available_font()
    if font:
        writer.font = font
        print("Font successfully loaded.")
    else:
        # Fallback to default font
        writer.font = ImageFont.load_default()
        print("Using default font.")

    barcode_obj = barcode_class(uuid, writer=writer)
    barcode_file = resource_path('barcode')
    barcode_obj.save(barcode_file)
    return f"{barcode_file}.png"

if __name__ == "__main__":
    uuid = get_system_uuid()
    if uuid:
        output_path = create_barcode(uuid)
        print(f"Barcode created for UUID: {uuid}")
        print(f"Barcode saved as: {output_path}")
    else:
        print("Failed to retrieve UUID.")

```

**Stacktrace / full error message**

```
Traceback (most recent call last):
  File "ui.py", line 379, in <module>
  File "barcode_generator.py", line 57, in create_barcode
  File "PIL\ImageFont.py", line 879, in truetype
  File "PIL\ImageFont.py", line 876, in freetype
  File "PIL\ImageFont.py", line 284, in __init__
OSError: cannot open resource

```
**Additional details**

![Screenshot 2024-11-11 111516](https://github.com/user-attachments/assets/88cb62fe-65d0-4209-9fcd-bd74b82b87b0)

**Comment by rokm** [comment]
The font resource that is missing is likely `DejaVuSansMono.ttf` from `barcode\fonts`. Try adding `--collect-data barcode` to your PyInstaller command.

**Comment by rokm** [comment]
And default/bundled font from `barcode\fonts` is used becase `barcode.writer.ImageWriter` does not have a `font` attribute (albeit there is a `font_path` attribute in contemporary versions of `python-barcode`)...

**Comment by NexTechQuantum** [comment]
> The font resource that is missing is likely `DejaVuSansMono.ttf` from `barcode\fonts`. Try adding `--collect-data barcode` to your PyInstaller command.

Thank you so much, @rokm! Your advice worked perfectly, and the issue is resolved now. Adding the font resource as you suggested did the trick. Really appreciate your help and the detailed explanation!
