### ISSUE TITLE
Add-data not solving the problems with distributed and dask

### ISSUE THREAD

**Issue by uriii3** [pyinstaller/pyinstaller#8874]
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11.1```
* Version of Python: ```Python 3.12.0```
* Platform: `OS X`
* How you installed Python: `conda env create` command
* Did you also try this on another platform? Does it work there? Nope, not yet (I will after reporting it here if it can be helpful)

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [x] use the latest development version
  * [x] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [x] Package your program in **--onedir mode**
  * [x] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
from dask.delayed import Delayed
import xarray

dataset = xarray.open_zarr("./dataset.zarr")

Delayed.compute(dataset)
```

(I have created a file `.zarr`, definitely can send it if it I needed but I don't think it is important)
I'm creating the binary with the following command:
`python -m PyInstaller error_report.py --onefile --copy-metadata xarray --copy-metadata zarr --add-data "PATH.../site-packages/dask/dask.yaml:./dask" --add-data "PATH.../site-packages/distributed/distributed.yaml:./distributed"`

### Stacktrace / full error message

```
Traceback (most recent call last):                                                                                                               
  File "error_report.py", line 6, in <module>
  File "dask/base.py", line 372, in compute
  File "dask/base.py", line 647, in compute
  File "dask/base.py", line 1140, in get_scheduler
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "distributed/__init__.py", line 4, in <module>
  File "<frozen importlib._bootstrap>", line 1354, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1325, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 929, in _load_unlocked
  File "PyInstaller/loader/pyimod02_importers.py", line 378, in exec_module
  File "distributed/config.py", line 20, in <module>
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIJovOWE/distributed/distributed.yaml'
[PYI-24373:ERROR] Failed to execute script 'error_report' due to unhandled exception!
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by uriii3** [comment]
I've also tried with numpy >2.0 and numpy <2.0, both of them seemed to get the same error.

Also, my command used to work, I don't think we haven't changed any dependency on our side, so I'm not sure what can be causing the problem.

**Comment by rokm** [comment]
When collecting files from packages, you can use [`--collect-data <packagename>`](https://pyinstaller.org/en/stable/usage.html#cmdoption-collect-data) instead of `--add-data`. So in this case `--collect-data dask --collect-data distributed` - does this make any difference?

**Comment by uriii3** [comment]
Mmh seems to end up doing the same with this change. It is weird because I retried it and then the second time it threw a different error, I'll try to explore a bit the dependencies it has troubles with now and get back.

**Comment by rokm** [comment]
Based on the traceback, this should be reproducible with just

```python
import distributed
```

Can you confirm?

The above reduced sample seems to work with `--collect-data distributed` for me. Can you try forcing a clean build (`--clean`) to ensure you are not using an old executable? 

If all that fails, try using `pyi-archive_viewer <executable>` to dump the contents of embedded archive and see if that `distributed/distributed.yaml` is collected.

**Comment by uriii3** [comment]
Yesss, definitely seems to work. Is it different, then, to do `--add-data` than `--collect-data`?

Thank you for everything and sorry to bother! 🙌

**Comment by rokm** [comment]
> Yesss, definitely seems to work. Is it different, then, to do `--add-data` than `--collect-data`?

It shouldn't be, provided you set the destination path correctly with `--add-data` (which you seem to have...).

You can try with `--add-data` again, and inspect the embedded archive with `pyi-archive_viewer <executable>` to see if `distributed/distributed.yaml` is where it should be.

**Comment by uriii3** [comment]
Mmh okay... thanks a lot for the quick response and the help!

And thanks also for the tip with `psi-archive_viewer <executable>` tip to be able to pinpoint the problem. Thank you very much!

**Comment by uriii3** [comment]
Would there be any case in which `pyi-archive_viewer <executable>` this would get me dask, and I made sure to add `--collect-data dask` in the command, and yet the error in the terminal is still something like:

```
FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIBnD6sO/dask/dask.yaml'
```

I am feeling a bit hopeless right now 🫠

**Comment by rokm** [comment]
> Would there be any case in which `pyi-archive_viewer <executable>` this would get me dask, and I made sure to add `--collect-data dask` in the command, and yet the error in the terminal is still something like:
> 
> ```
> FileNotFoundError: [Errno 2] No such file or directory: '/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIBnD6sO/dask/dask.yaml'
> ```
> 
> I am feeling a bit hopeless right now 🫠

Hmm, if you see it with `pyi-archive_viewer` then it should be there when program unpacks itself. 

For debugging these sort of things, it is usually best to switch to onedir mode, which makes it easier to debug missing-file issues. And once you have everything ready, go for onefile (and hope it still works; but if it doesn't at least you know it is specific to onefile in some way).

Alternatively, you could print the value of `sys._MEIPASS` at the very start of your onefile program, then stall the execution (e.g., using `input()`), and go investigate the temporary directory to see if files are actually there.

**Comment by rokm** [comment]
I've generated a test zarr dataset to go with your example. I think the problem is that dask/distributed is using `multiprocessing`, which means you should add `multiprocessing.freeze_support()` call at the very start of your program, as per https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#multi-processing

Otherwise, you'll end up with endless spawn loop. This will have extra "feature" in onefile mode: once the original/true application process exits, the parent will clean up the temporary directory, and all recursively spawned worker processes (whose program flow should be diverted using `freeze_support` to avoid running your main program code) will start getting missing-file errors.

**Comment by uriii3** [comment]
Mmmh huh okay, nice! 

I was trying this and it seems to work, but then it jumps to something like it is trying to wait for a response, with an infinite loop, throwing `Error: No such option: -B` continuously.

I'll try to pin point the problem with a shorter example file (but will most definitely help me understand what I'm doing wrongly).

**Comment by uriii3** [comment]
OMG! You are so right! I'll try it right away, thank you soooo much!!!!

**Comment by uriii3** [comment]
Okay, with `onedir` adding `freeze_support()` it definitely works, with `onefile` not yet. I'll check tomorrow how about the linux and windows machines, let's see how they go (if not, I'll create a onedir for the macOS and the rest will be in one file and that will be it).

Thank you so much for everything, I really appreciate your help 🙌

**Comment by rokm** [comment]
> Okay, with `onedir` adding `freeze_support()` it definitely works, with `onefile` not yet.

Are you talking about the minimum example, or your actual application?

**Comment by uriii3** [comment]
My actual application, sorry.

I'll try to make sure that everything is solved with a onedir option for my application and I'll try again to approach the issue, trying to narrow down the different problems so that the reporting can be more easy.

Thank you very much for everything!

**Comment by uriii3** [comment]
How should I proceed to try to pin point the minimal example? I tried it with my little example and it seems to work, and I'm not sure what part of the whole package will be the problem (the error is still that there are some 'missing dependencies') but the problem seems not to be that... (if i rerun it several times, the output is different, and it works correctly before throwing the error... so seem quite sure a thing about the multiprocessing).

**Comment by rokm** [comment]
What is the error message (or what are the error messages, if they are different across runs)? The traceback should point out where the error is coming from, and that might also help with isolating the code for minimal example.

**Comment by uriii3** [comment]
The main error is this one:
`ModuleNotFoundError: No module named 'mmap' `, but the module varies within mmap or cmath, and also dask. Which makes me think that it is still related with the multiprocessing.freeze_support().

**Comment by rokm** [comment]
What is the full error traceback?

**Comment by uriii3** [comment]
```
Traceback (most recent call last):
  File "copernicusmarine/command_line_interface/copernicus_marine.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "copernicusmarine/__init__.py", line 4, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "copernicusmarine/catalogue_parser/models.py", line 11, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "copernicusmarine/core_functions/utils.py", line 19, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "xarray/__init__.py", line 3, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "xarray/groupers.py", line 15, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/__init__.py", line 49, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/core/api.py", line 47, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/core/groupby/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/core/groupby/generic.py", line 68, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/core/frame.py", line 149, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/core/generic.py", line 184, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/core/methods/describe.py", line 41, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/io/formats/format.py", line 82, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "pandas/io/common.py", line 26, in <module>
ModuleNotFoundError: No module named 'mmap'
[PYI-40090:ERROR] Failed to execute script 'copernicus_marine' due to unhandled exception!
multiprocessing/resource_tracker.py:104: UserWarning: resource_tracker: process died unexpectedly, relaunching.  Some resources might leak.
[PYI-40091:ERROR] Failed to load Python shared library '/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIDtftwN/libpython3.12.dylib': dlopen: dlopen(/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIDtftwN/libpython3.12.dylib, 0x000A): tried: '/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIDtftwN/libpython3.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIDtftwN/libpython3.12.dylib' (no such file), '/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIDtftwN/libpython3.12.dylib' (no such file), '/private/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIDtftwN/libpython3.12.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIDtftwN/libpython3.12.dylib' (no such file), '/private/var/folders/np/b0vs84gj635cbf56__s7bg500000gn/T/_MEIDtftwN/libpython3.12.dylib' (no such file) 
```

**Comment by rokm** [comment]
Hmmm, this still looks like some process is being spawned after the main application process exits (or dies) and the onefile parent cleans up temporary directory. `mmap` and `cmath` are stdlib extension modules.

Where in `copernicus_marine.py` did you put the `multiprocessing.freeze_support`?

**Comment by uriii3** [comment]
Direclty before running it!
`if __name__ == "__main__":
    freeze_support()
    command_line_interface() `

This is the pr: https://github.com/mercator-ocean/copernicus-marine-toolbox/pull/207/files

**Comment by rokm** [comment]
I think with all the magic that `click` does, it should go at the very top of the file:

```python
import multiprocessing
multiprocessing.freeze_support()

import click

from copernicusmarine.command_line_interface.group_describe import (
    cli_group_describe,
)
from copernicusmarine.command_line_interface.group_get import cli_group_get
from copernicusmarine.command_line_interface.group_login import cli_group_login
from copernicusmarine.command_line_interface.group_subset import (
    cli_group_subset,
)


@click.command(
    cls=click.CommandCollection,
    sources=[
        cli_group_describe,
        cli_group_login,
        cli_group_subset,
        cli_group_get,
    ],
    context_settings=dict(help_option_names=["-h", "--help"]),
)
@click.version_option(None, "-V", "--version", package_name="copernicusmarine")
def base_command_line_interface():
    pass


def command_line_interface():
    base_command_line_interface(windows_expand_args=False)


if __name__ == "__main__":
    command_line_interface()
```

**Comment by uriii3** [comment]
Uuh, okay i'll try!!

**Comment by uriii3** [comment]
It wasn't solved by this, although I'm not sure what else to try now ahahah. I'll keep digging a bit! (I even tried to put more than one multiprocessing.freeze_support() but it doesn't work).

Is there anything I can locate with the `onedir` that will help me debug this?

**Comment by uriii3** [comment]
With 3 freeze_support seems to work 🫠 . Now it is missing other stuff but that problem is solved hahaha. I'll continue to check, but thank you so much for all the help!!

**Comment by uriii3** [comment]
Okay, looks like after that there was some missing dependencies on `zarr` but it looks fine. I'll investigate in a future moment which of the `freeze_support()` is the one that works or if indeed I need the 3 of them.

Anyway, thank you so much, I'm so grateful to you. Thanks for all the help but moreover thanks for the library that you are maintaining, it is very useful.

Kind regards! 🤗

**Comment by rokm** [comment]
>  I'll investigate in a future moment which of the freeze_support() is the one that works or if indeed I need the 3 of them.

Unlikely - after the first one is called, the rest should be no-op (because program flows with matching arguments should not make it past the first one). Unless you have different codepaths that somehow manage to bypass the call that is supposed to be at the very top of your entry-point script.
