### ISSUE TITLE
program(ond-dir) build by pyintaller , run in docker(ubuntu20.04), can not found libQt6Core.so.6 when host machine is ubuntu16.04 but ok when host is ubuntu20.04

### ISSUE THREAD

**Issue by motocoder-cn** [pyinstaller/pyinstaller#8876]
## Description of the issue
is use pyinstaller in docker env,host system is  ubuntu16.04, docker image: ubuntu20.04

then use same image(ubunt20.04) run in other machine

when:
*  `host: ubuntu16.04`: program can not found libQt6Core.so.6  (but in _internal libQt6Core.so.6 is exist)
*  `host: ubuntu20.04`: work ok

### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.11.1
* Version of Python:  3.9
* Platform: GNU/Linux (distribution)
* How you installed Python: apt
* Did you also try this on another platform? Does it work there?

### A minimal example program which shows the error

Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "qt_core.py", line 1, in <module>
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory

### Stacktrace / full error message
[PYI-173:DEBUG] PyInstaller Bootloader 6.x
[PYI-173:DEBUG] LOADER: executable file: /opt/MLGoAnno/mlgoanno
[PYI-173:DEBUG] LOADER: trying to load executable-embedded archive...
[PYI-173:DEBUG] LOADER: attempting to open archive /opt/MLGoAnno/mlgoanno
[PYI-173:DEBUG] LOADER: cookie found at offset 0x8614E7
[PYI-173:DEBUG] LOADER: archive file: /opt/MLGoAnno/mlgoanno
[PYI-173:DEBUG] LOADER: application has onedir semantics...
[PYI-173:DEBUG] LOADER: _PYI_ARCHIVE_FILE not defined...
[PYI-173:DEBUG] LOADER: process level = 0
[PYI-173:DEBUG] LOADER: POSIX onedir process needs to set library search path and restart itself.
[PYI-173:DEBUG] LOADER: setting LD_LIBRARY_PATH=/opt/MLGoAnno/_internal
[PYI-173:DEBUG] LOADER: restarting process via execvp
[PYI-173:DEBUG] PyInstaller Bootloader 6.x
[PYI-173:DEBUG] LOADER: executable file: /opt/MLGoAnno/mlgoanno
[PYI-173:DEBUG] LOADER: trying to load executable-embedded archive...
[PYI-173:DEBUG] LOADER: attempting to open archive /opt/MLGoAnno/mlgoanno
[PYI-173:DEBUG] LOADER: cookie found at offset 0x8614E7
[PYI-173:DEBUG] LOADER: archive file: /opt/MLGoAnno/mlgoanno
[PYI-173:DEBUG] LOADER: application has onedir semantics...
[PYI-173:DEBUG] LOADER: _PYI_ARCHIVE_FILE already defined: /opt/MLGoAnno/mlgoanno
[PYI-173:DEBUG] LOADER: using same archive file as parent environment!
[PYI-173:DEBUG] LOADER: process level = 1
[PYI-173:DEBUG] LOADER: POSIX onedir process has already restarted itself (level = 1).
[PYI-173:DEBUG] LOADER: application's top-level directory: /opt/test/_internal
[PYI-173:DEBUG] LOADER: splash screen is unavailable.
[PYI-173:DEBUG] LOADER: loading Python shared library: /opt/MLGoAnno/_internal/libpython3.9.so.1.0
[PYI-173:DEBUG] LOADER: loaded functions from Python shared library.
[PYI-173:DEBUG] LOADER: pre-initializing embedded python interpreter...
[PYI-173:DEBUG] LOADER: creating PyConfig structure...
[PYI-173:DEBUG] LOADER: initializing interpreter configuration...
[PYI-173:DEBUG] LOADER: setting program name...
[PYI-173:DEBUG] LOADER: setting python home path...
[PYI-173:DEBUG] LOADER: setting module search paths...
[PYI-173:DEBUG] LOADER: setting sys.argv...
[PYI-173:DEBUG] LOADER: applying run-time options...
[PYI-173:DEBUG] LOADER: starting embedded python interpreter...
[PYI-173:DEBUG] LOADER: setting sys._MEIPASS
[PYI-173:DEBUG] LOADER: importing modules from PKG/CArchive
[PYI-173:DEBUG] LOADER: extracted struct
[PYI-173:DEBUG] LOADER: running unmarshalled code object for module struct...
[PYI-173:DEBUG] LOADER: extracted pyimod01_archive
[PYI-173:DEBUG] LOADER: running unmarshalled code object for module pyimod01_archive...
[PYI-173:DEBUG] LOADER: extracted pyimod02_importers
[PYI-173:DEBUG] LOADER: running unmarshalled code object for module pyimod02_importers...
[PYI-173:DEBUG] LOADER: extracted pyimod03_ctypes
[PYI-173:DEBUG] LOADER: running unmarshalled code object for module pyimod03_ctypes...
[PYI-173:DEBUG] LOADER: looking for PYZ archive TOC entry...
[PYI-173:DEBUG] LOADER: path to PYZ archive stored into sys._pyinstaller_pyz...
[PYI-173:DEBUG] LOADER: running pyiboot01_bootstrap.py
[PYI-173:DEBUG] LOADER: running pyi_rth_inspect.py
[PYI-173:DEBUG] LOADER: running pyi_rth_pkgutil.py
[PYI-173:DEBUG] LOADER: running pyi_rth_multiprocessing.py
[PYI-173:DEBUG] LOADER: running pyi_rth_pkgres.py
[PYI-173:DEBUG] LOADER: running pyi_rth_setuptools.py
[PYI-173:DEBUG] LOADER: running pyi_rth_pyside6.py
[PYI-173:DEBUG] LOADER: running pyi_rth_mplconfig.py
[PYI-173:DEBUG] LOADER: running main.py
Traceback (most recent call last):
  File "main.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "qt_core.py", line 1, in <module>
ImportError: libQt6Core.so.6: cannot open shared object file: No such file or directory
[PYI-173:ERROR] Failed to execute script 'main' due to unhandled exception!
[PYI-173:DEBUG] LOADER: ERROR.
[PYI-173:DEBUG] LOADER: manually flushing stdout and stderr...
[PYI-173:DEBUG] LOADER: cleaning up Python interpreter...
[PYI-173:DEBUG] LOADER: unloading Python shared library...
[PYI-173:DEBUG] LOADER: end of process reached!

**Comment by bwoodsend** [comment]
Which environment are you building in and which are you running in? If you're building in 20.04 then running in 16.04 then of course that's not going to work because everything in your application is linked against whatever glibc version 20.04 carries.

**Comment by motocoder-cn** [comment]
> Which environment are you building in and which are you running in? If you're building in 20.04 then running in 16.04 then of course that's not going to work because everything in your application is linked against whatever glibc version 20.04 carries.

i build in in docker(ubuntu20.04) , run in another machine also docker(ubuntu20.04)

finally if found, two machine has different kerna version, libQt6Core have to match kernal version @bwoodsend
