### ISSUE TITLE
ModuleNotFoundError: No module named 'unicodedata'

### ISSUE THREAD

**Issue by alidurraniwanclouds** [pyinstaller/pyinstaller#8880]
Hi, I've been using Pyinstaller for linux in order to make binary with python3.10 version installed on machine.
but unfortunately I'm facing issues regarding imports frequently regarding python module I've been utilising in my code named
`apscheduler` I removed this import and handled the part of code utilising this module manually but after that it started giving me modulenotfound error for requests module as well, I've tried couple of ways like using `--hidden-import` `--collect-all` but still facing the same issue as given below.
 ```
Traceback (most recent call last):
  File "main.py", line 126, in <module>
  File "main.py", line 31, in linux_daemonize
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "agent/run.py", line 9, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "agent/tasks/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "agent/tasks/registration_tasks/__init__.py", line 1, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "agent/tasks/registration_tasks/agent_registration_tasks.py", line 5, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "requests/__init__.py", line 119, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "requests/packages.py", line 7, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "idna/__init__.py", line 2, in <module>
  File "PyInstaller/loader/pyimod02_importers.py", line 384, in exec_module
  File "idna/core.py", line 3, in <module>
ModuleNotFoundError: No module named 'unicodedata'
[PYI-73754:ERROR] Failed to execute script 'main' due to unhandled exception!
```
` File "agent/tasks/registration_tasks/agent_registration_tasks.py", line 5, in <module> this line includes only
   import requests`
### I did try adding `unicodedata` `unicodedata2` `requests` in hidden imports and collect all option

**Comment by rokm** [comment]
What version of pyinstaller are you using?

What kind of python are you building with? Is it system-provided python, or some other version that you installed in addition to system-provided python (e.g., `rye`, `uv`)? If you are not using system-provided python, does the system also provide a python 3.10?

**Comment by alidurraniwanclouds** [comment]
I'm using pyinstaller version 6.11.1
and also using system-provided python. and sorry the version was python 3.9.20.

**Comment by rokm** [comment]
Can you rebuild with added `--clean` option and paste the build log, then?

**Comment by alidurraniwanclouds** [comment]
```
96 INFO: PyInstaller: 6.11.1, contrib hooks: 2024.10
96 INFO: Python: 3.9.20
99 INFO: Platform: Linux-5.14.0-474.el9.x86_64-x86_64-with-glibc2.34
99 INFO: Python environment: /usr
102 INFO: Removing temporary files and cleaning cache in /root/.cache/pyinstaller
106 INFO: Module search paths (PYTHONPATH):
['/usr/lib64/python39.zip',
 '/usr/lib64/python3.9',
 '/usr/lib64/python3.9/lib-dynload',
 '/usr/local/lib64/python3.9/site-packages',
 '/usr/local/lib/python3.9/site-packages',
 '/usr/lib64/python3.9/site-packages',
 '/usr/lib/python3.9/site-packages',
 '/usr/lib/python3.9/site-packages/bcc-0.31.0+629a5b4f-py3.9.egg',
 '/root/auth-agent-python']
288 INFO: checking Analysis
288 INFO: Building Analysis because Analysis-00.toc is non existent
288 INFO: Running Analysis Analysis-00.toc
289 INFO: Target bytecode optimization level: 0
289 INFO: Initializing module dependency graph...
290 INFO: Initializing module graph hook caches...
299 INFO: Analyzing base_library.zip ...
809 INFO: Processing standard module hook 'hook-encodings.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
1704 INFO: Processing standard module hook 'hook-pickle.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
2339 INFO: Processing standard module hook 'hook-heapq.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
2476 INFO: Caching module dependency graph...
2564 INFO: Looking for Python shared library...
2574 INFO: Using Python shared library: /lib64/libpython3.9.so.1.0
2574 INFO: Analyzing /root/auth-agent-python/main.py
2596 INFO: Processing standard module hook 'hook-platform.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
2944 INFO: Processing standard module hook 'hook-multiprocessing.util.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
2997 INFO: Processing standard module hook 'hook-xml.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
3349 INFO: Processing pre-safe-import-module hook 'hook-urllib3.packages.six.moves.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module'
3725 INFO: Processing standard module hook 'hook-charset_normalizer.py' from '/usr/local/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/stdhooks'
3788 INFO: Processing pre-safe-import-module hook 'hook-typing_extensions.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks/pre_safe_import_module'
3789 INFO: SetuptoolsInfo: initializing cached setuptools info...
4436 INFO: Processing standard module hook 'hook-certifi.py' from '/usr/local/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/stdhooks'
4973 INFO: Processing standard module hook 'hook-difflib.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
6362 INFO: Processing standard module hook 'hook-scapy.layers.all.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
6692 INFO: Processing standard module hook 'hook-psutil.py' from '/usr/local/lib/python3.9/site-packages/_pyinstaller_hooks_contrib/stdhooks'
7012 INFO: Processing standard module hook 'hook-sqlite3.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
8298 INFO: Processing standard module hook 'hook-sysconfig.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks'
8361 INFO: Processing module hooks (post-graph stage)...
9593 INFO: Performing binary vs. data reclassification (4 entries)
9604 INFO: Looking for ctypes DLLs
9896 INFO: Analyzing run-time hooks ...
9903 INFO: Including run-time hook 'pyi_rth_multiprocessing.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks/rthooks'
9905 INFO: Including run-time hook 'pyi_rth_pkgutil.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks/rthooks'
9906 INFO: Including run-time hook 'pyi_rth_inspect.py' from '/usr/local/lib/python3.9/site-packages/PyInstaller/hooks/rthooks'
9920 INFO: Looking for dynamic libraries
10529 INFO: Warnings written to /root/auth-agent-python/build/main/warn-main.txt
10574 INFO: Graph cross-reference written to /root/auth-agent-python/build/main/xref-main.html
10595 INFO: checking PYZ
10595 INFO: Building PYZ because PYZ-00.toc is non existent
10595 INFO: Building PYZ (ZlibArchive) /root/auth-agent-python/build/main/PYZ-00.pyz
11464 INFO: Building PYZ (ZlibArchive) /root/auth-agent-python/build/main/PYZ-00.pyz completed successfully.
11485 INFO: checking PKG
11485 INFO: Building PKG because PKG-00.toc is non existent
11485 INFO: Building PKG (CArchive) main.pkg
14872 INFO: Building PKG (CArchive) main.pkg completed successfully.
14874 INFO: Bootloader /usr/local/lib/python3.9/site-packages/PyInstaller/bootloader/Linux-64bit-intel/run
14874 INFO: checking EXE
14874 INFO: Building EXE because EXE-00.toc is non existent
14874 INFO: Building EXE from EXE-00.toc
14875 INFO: Copying bootloader EXE to /root/auth-agent-python/dist/main
14876 INFO: Appending PKG archive to custom ELF section in EXE
14932 INFO: Building EXE from EXE-00.toc completed successfully.

```

**Comment by rokm** [comment]
Hmm, that looks alright. 

Can you open `/root/auth-agent-python/build/main/Analysis-00.toc` and search for `unicodedata` in there? Is there an entry for it? (Similarly, is there one in `/root/auth-agent-python/build/main/PKG-00.toc`?)

**Comment by alidurraniwanclouds** [comment]
yes, I believe I do have entries in both files 
`/root/auth-agent-python/build/main/Analysis-00.toc`
['unicodedata']
`/root/auth-agent-python/build/main/PKG-00.toc`
('lib-dynload/unicodedata.cpython-39-x86_64-linux-gnu.so',
   '/usr/lib64/python3.9/lib-dynload/unicodedata.cpython-39-x86_64-linux-gnu.so',
   'EXTENSION'),

**Comment by rokm** [comment]
Since you seem to be using onefile mode, I guess you are getting this error in a sub-process that outlives the main application process. Once the main application process exits, its parent cleans up the temporary directory, and the spawned sub-process ends up with missing file(s).

Are you using `multiprocessing` without calling ˙multiprocessing.freeze_support`? 

Or are you manually spawning a process using `sys.executable` and then exiting the application process?

Can you provide a minimal example that triggers the error?

**Comment by alidurraniwanclouds** [comment]
`from multiprocessing import freeze_support
    freeze_support()`
    
    after that I deamonize the process and call a specific function which makes GET, POST, etc calls 
    the function uses threading in order to make call every 5 seconds.

**Comment by alidurraniwanclouds** [comment]
```
def linux_daemonize():
    if os.fork() > 0:
        sys.exit(0)
    os.setsid()  # Detach session
    # Second fork
    if os.fork() > 0:
        sys.exit(0)
    sys.stdout.flush()
    sys.stderr.flush()
    # Try minimal redirection for debugging
    with open('/tmp/daemon_output.log', 'w') as log_file:
        os.dup2(log_file.fileno(), sys.stdout.fileno())
        os.dup2(log_file.fileno(), sys.stderr.fileno())
    # Inline import for RunAgent
    from agent.run import RunAgent
    runner = RunAgent()
    agent_runner_thread = threading.Thread(target=runner.start_scheduler)
    agent_runner_thread.start()

if __name__ == '__main__':
    from multiprocessing import freeze_support
    freeze_support()

    if os_name.lower() == 'linux':
        import contextvars, _contextvars
        install_prerequisites = LinuxPrerequisites()
        is_prerequisites_install = install_prerequisites.install_packages()
        if not is_prerequisites_install:
            raise Exception(f"Prerequisite installation failed {os_name.capitalize()}")
        linux_daemonize()

```

This is basic code of what I'm doing I'm encountering import issue under start_scheduler function..

**Comment by rokm** [comment]
You seem to be exiting the main (original) application process after first `os.fork`. You can't do that with onefile application, because it will cause the parent process of the onefile application enter the cleanup mode and exit. And so your forked sub-processes end up with missing files.

If you want a separate and independent instance of a onefile application that is supposed to outlive the current application process, you will need to spawn it (instead of just forking) and also set `PYINSTALLER_RESET_ENVIRONMENT` environment variable, as described [here](https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#using-sys-executable-to-spawn-subprocesses-that-outlive-the-application-process-implementing-application-restart).

**Comment by alidurraniwanclouds** [comment]
I want the binary itself to handle the daemonization and keep the processes running in background, under the scheduler function that I've shared above I'm using multiprocessing and threading.

**Comment by rokm** [comment]
Well, that approach violates the assumption of onefile application mode - namely that once the (original) application process exits, the temporary directory should be cleaned up. 

As far as I see, your options are as follows:
- don't use onefile mode
- have your original application process spawn a full independent instance of the application using `subprocess.Popen()` and `sys.executable` (and set the afore-mentioned environment variable), so that the instance in the background has its own temporary directory
- go and modify PyInstaller's bootloader code to accommodate your case, if possible (I'm not sure how you would have the onefile parent process track the subprocesses spawned from the original application child process, though)

**Comment by hutianlei0805** [comment]
I found the problem, it's with the pyinstaller version. I also reported an error using 6.11.1, but when I switched to 6.9.0, it ran normally.

**Comment by rokm** [comment]
> I found the problem, it's with the pyinstaller version. I also reported an error using 6.11.1, but when I switched to 6.9.0, it ran normally.

That's because the behavior was changed in v6.10.0, as described in [the changelog](https://pyinstaller.org/en/stable/CHANGES.html#incompatible-changes).
