### ISSUE TITLE
Do not share the _MEIxxxx tmp folder

### ISSUE THREAD

**Issue by rqx110** [pyinstaller/pyinstaller#8884]
I have a onefile application which is pacakged by Pyinstaller 6.x. In this application I have an AutoUpdate feature, it download a new version, and then copy the new file to execute directory, finally it will close self and restart(using a bat file to restart on Windows).
It works well before Pyinstaller 6.x(like 5.13.2), but it can't work for greater than pyinstaller 6.x.

I have debug this for a while, found that in Pyinstaller 6.x, when restart as I mentioned it is not create a new _MEIxxxx folder, instead it shared using the old ones, this can be problem if we close the old one and the new one(by restart) can't wokr because the _MEIxxxx folder is deleted.

For a simple, I create a minimal sample to reproduce this problem:
```py
# main.py
import os
import subprocess

import win32con
import win32event
import win32process
from win32comext.shell import shellcon
from win32comext.shell.shell import ShellExecuteEx


def run_win(cmd_line=None, wait=True, show_window=True):
    cmd = cmd_line[0]
    params = subprocess.list2cmdline(cmd_line[1:])

    proc = ShellExecuteEx(
        nShow=win32con.SW_SHOWNORMAL if show_window else win32con.SW_HIDE,
        fMask=shellcon.SEE_MASK_NOCLOSEPROCESS,
        lpVerb='runas',  # causes UAC elevation prompt.
        lpFile=cmd,
        lpParameters=params)

    if wait:
        proc_handle = proc['hProcess']
        _ = win32event.WaitForSingleObject(proc_handle, win32event.INFINITE)
        rc = win32process.GetExitCodeProcess(proc_handle)
    else:
        rc = None

    return rc
    
command = input('enter "p" to restart:')

if command == 'p':   
    run_win(cmd_line=["cmd.exe", "/c", 'restart.bat'], wait=False)
    input('look at the temp folder, there is only one _MEIxxxx folder if packaged by pyinstaller 6.x.\nAnd two _MEIxxxx folders if packaged by pyinstaller 5.13.2!\n press enter key to close')
    #os._exit(0)  # in real application I need call this to close current and using new one created in previous step
```

here is the `restart.bat`
```bat
@echo off
ping 127.0.0.1 -n 5 -w 1000 > NUL
echo restarting...
start "" "main.exe"
```

here is all things, it contains two dist folder which create by pyinstaller 6.11.1 and pyinstaller 5.13.2, you can run the `main.exe` in the dist folder, then you will see different behaviors
[pyinstaller-issue.zip](https://github.com/user-attachments/files/17810675/pyinstaller-issue.zip)

**Comment by bwoodsend** [comment]
Have you tried [this](https://pyinstaller.org/en/v6.11.1/common-issues-and-pitfalls.html#independent-subprocess)?

**Comment by bwoodsend** [comment]
That said, I'd really discourage DIY auto update mechanisms. Anything you attempt is almost certainly oozing with privilege escalation vulnerabilities.

**Comment by rqx110** [comment]
> Have you tried [this](https://pyinstaller.org/en/v6.11.1/common-issues-and-pitfalls.html#independent-subprocess)?

Nice! after set the `PYINSTALLER_RESET_ENVIRONMENT` environment  variable, it works now!
