### ISSUE TITLE
PyInstaller treats first argument as program name on Win32, even when it's not

### ISSUE THREAD

**Issue by alexchandel** [pyinstaller/pyinstaller#8895]
### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.11.1
* Version of Python: 3.13
* Platform: Windows 11
* How you installed Python: CPython 3.13
* Did you also try this on another platform? Does it work there? N/A

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [x] start with clean installation
  * [ ] use the latest development version
  * [N/A] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [N/A] Package your program in **--onedir mode**
  * [N/A] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [x] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

Starting a process on Windows is a litte different than unix (see [CreateProcess](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessa)).  Arguments are passed in one single string, `lpCommandLine`, rather than a list of strings.  The "image path" (the executable to be run) can be passed as a separate argument `lpApplicationName`, or it can be passed as the first argument in `lpCommandLine`.

Traditionally, programs that create a process by passing `lpApplicationName` also put the path as the first argument to `lpCommandLine`, *but this is not required*.  However, it appears PyInstaller's frozen programs look for the first argument for their name, regardless of whether this is a valid image path vs. whether the image path was simply not provided as the first argument.  This then causes problems when the arguments are parsed, as the first one is missing (having been taken as the image name):

```py
# partial contents of frozen exe
import argparse
parser = argparse.ArgumentParser()
parser.add_argument('--foo', help='an argument', default='')
args = parser.parse_args()  # complains that `bar` is not a valid argument, claims our exe is called `--foo`
```

You can simulate this spawning method from an example

```py
import subprocess
from pathlib import Path
full_path_to_exe = Path(...)
subprocess.Popen(
    args='--foo bar',
    executable=full_path_to_exe,
    cwd=full_path_to_exe.parent,
    shell=False,
)
```

This works around the issue when you have control of the calling process (which you do not always have), and illustrates the issue:

```py
import subprocess
from pathlib import Path
full_path_to_exe = Path(...)
subprocess.Popen(
    args=f'"{full_path_to_exe.name}" --foo bar',
    executable=full_path_to_exe,
    cwd=full_path_to_exe.parent,
    shell=False,
)
```

Again, the Win32 environment does NOT guarantee that the first argument of your "command line string" (which is parsed by the MS C runtime using some fairly complicated rules into your argv list of strings).

### Stacktrace / full error message

N/A

**Comment by bwoodsend** [comment]
Just to simplify the OP a bit:

Given a test program which uses command line arguments in some way such as:
```python
# test.py
import sys
print(sys.argv)
```
If you freeze that then invoke it as a subprocess using `Popen()`'s `executable` option then `sys.argv[0]` disappears:
```python
>>> _ = subprocess.run(["dist/test/test.exe", "--foo", "bar"])
['dist/test/test.exe', '--foo', 'bar']
>>> _ = subprocess.run(args=["--foo", "bar"], executable="dist/test/test.exe")
['--foo', 'bar']
```
---
This is doesn't work for normal Python either though so I'm not sold that this is incorrect behaviour.
```python
>>> _ = subprocess.run([sys.executable, "test.py", "--foo", "bar"])
['test.py', '--foo', 'bar']
>>> _ = subprocess.run(args=["test.py", "--foo", "bar"], executable=sys.executable)
unknown option --foo
usage: test.py [option] ... [-c cmd | -m mod | file | -] [arg] ...
```

**Comment by rokm** [comment]
I'm also not sold on the conclusion that this is a PyInstaller problem - if program name/path is not passed as the first argument, then `argv[0]` will not be program name, and this will mess up various command-line parser implementations that expect that to be the case (inlcuding `argparse`, as demonstrated by OP).

Consider the following C program:
```c
// commandline.c
#include <stdio.h>
#include <windows.h>

int wmain(int argc, const wchar_t **argv)
{
    printf("argc=%d:\n", argc);
    for (int i = 0; i < argc; i++) {
        printf("argv[%i]: %S\n", i, argv[i]);
    }
        
    printf("GetCommandLine: %S\n",  GetCommandLineW());
    
    printf("__argc=%d:\n", __argc);
    for (int i = 0; i < __argc; i++) {
        printf("__wargv[%i]: %S\n", i, __wargv[i]);
    }

    return 0;
}
```

Compiling it with MSVC and running it via 

```python
subprocess.run(args=["--foo", "bar"], executable="commandline.exe")
```

gives us:

```
argc=2:
argv[0]: --foo
argv[1]: bar
GetCommandLine: --foo bar
__argc=2:
__wargv[0]: --foo
__wargv[1]: bar
```

Which is in line with what happens with PyInstaller-frozen executables and python.exe (as shown by Brénainn in the comment above).

**Comment by bwoodsend** [comment]
Turns out that this isn't Windows specific either.
