### ISSUE TITLE
Files added with -add-data get deleted after a short period of time and break the program

### ISSUE THREAD

**Issue by skeddles** [pyinstaller/pyinstaller#8896]
## Description of the issue

The program works find at first, but after a certain number of hours it seems the temp directory you extracted the files to gets deleted, and then the program no longer works. This program is supposed to run indefinitely, so this is not okay.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11.0```
* Version of Python: ```3.10.6```
* Platform: windows
* How you installed Python: no idea
* Did you also try this on another platform? Does it work there? no

* try the latest development version, using the following command:

```shell
pip install https://github.com/pyinstaller/pyinstaller/archive/develop.zip
```

* follow *all* the instructions in our "If Things Go Wrong" Guide
  (https://github.com/pyinstaller/pyinstaller/wiki/If-Things-Go-Wrong) and

### Make sure [everything is packaged correctly](https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs#make-sure-everything-is-packaged-correctly)

  * [ ] start with clean installation
  * [ ] use the latest development version
  * [ ] Run your frozen program **from a command window (shell)** — instead of double-clicking on it
  * [ ] Package your program in **--onedir mode**
  * [ ] Package **without UPX**, say: use the option `--noupx` or set `upx=False` in your .spec-file
  * [ ] Repackage you application in **verbose/debug mode**. For this, pass the option `--debug` to `pyi-makespec` or `pyinstaller` or use `EXE(..., debug=1, ...)` in your .spec file.

### A minimal example program which shows the error

```
import os
import sys
import time
from playsound import playsound 

# Determine the base path for the executable
if getattr(sys, 'frozen', False):  # If the script is running as an executable
    base_path = sys._MEIPASS  # PyInstaller sets this to a temporary folder
else:
    base_path = os.path.abspath(".")  # Otherwise, use the current working directory

# Path to the audio file, now at the root level of the bundled files
sound_file = os.path.join(base_path, "bitty.mp3")
chime_interval_minutes = 30  # Set your chime interval here

def chime():
    print(f"Chime program started. Will chime every {chime_interval_minutes} minutes starting from the next hour.")
    playsound(sound_file)

    # Wait until the top of the next hour
    current_time = time.localtime()
    seconds_until_next_hour = (60 - current_time.tm_min) * 60 - current_time.tm_sec
    time.sleep(seconds_until_next_hour)

    # Start the regular chime intervals
    while True:
        # Play the chime sound
        playsound(sound_file)

        # Sleep for the interval specified
        time.sleep(chime_interval_minutes * 60)

if __name__ == "__main__":
    chime()
```

### Stacktrace / full error message

```
Cannot find the specified file. Make sure the path and filename are correct.
```

Please also see <https://github.com/pyinstaller/pyinstaller/wiki/How-to-Report-Bugs>
for more about what would use to solve the issue.

**Comment by skeddles** [comment]
you're gonna tell me to use --runtime-tempdir, but then i have to put in a relative / absolute location. i still want to use the temp folder so it doesn't get placed anywhere important / noticeable, but i dont want it to get deleted.

**Comment by rokm** [comment]
> i still want to use the temp folder so it doesn't get placed anywhere important / noticeable, but i dont want it to get deleted.

Then tell your OS not to periodically clean your temporary directory?
