### ISSUE TITLE
Packaging of multithreaded software on MacOS

### ISSUE THREAD

**Issue by DynamicBiosystems** [pyinstaller/pyinstaller#8904]
The software is developed using PySide6, and employs PySide6.QtCore.QThread to facilitate multithreaded operation. On the macOS system, directly running the .py script works normally. However, after packaging with pyinstaller and double-clicking the app, the software launches multiple times, initiating several processes in the background until the computer crashes.
The run command is: pyinstaller -w -D gui.py --add-data "./data:data" -i logo.ico

**Comment by rokm** [comment]
Can you provide sample code that reproduces the error?
