### ISSUE TITLE
Unable to create binary using pyinstaller - Getting error related to fastai library

### ISSUE THREAD

**Issue by sgssgjrss** [pyinstaller/pyinstaller#8906]
Error details attached.
[PyInstallerProblemNov2024.odt](https://github.com/user-attachments/files/17993482/PyInstallerProblemNov2024.odt)
[fastAIError.odt](https://github.com/user-attachments/files/17993483/fastAIError.odt)

**Comment by bwoodsend** [comment]
Please don't post duplicates of the mailing list.
