### ISSUE TITLE
Regarding the issue of packaging with pyinstaller on macOS systems.

### ISSUE THREAD

**Issue by yangmengace** [pyinstaller/pyinstaller#8907]
The software is developed using PySide6, and employs PySide6.QtCore.QThread to facilitate multithreaded operation. On the macOS system, directly running the .py script works normally. However, after packaging with pyinstaller and double-clicking the app, the software launches multiple times, initiating several processes in the background until the computer crashes.
The run command is: pyinstaller -w -D gui.py --add-data "./data:data" -i logo.ico
The following is part of the code：

```python
import logging
import os
import pathlib
import socket
import sys
import time
import urllib.parse
import urllib.request
from PySide6 import QtGui
from PySide6.QtCore import (
    Qt,
    QThread,
    QTimer,
    QUrl,
    Signal,
    QEvent
)
from PySide6.QtGui import (
    QAction,
    QDesktopServices,
)
from PySide6.QtWebEngineWidgets import QWebEngineView
from PySide6.QtWidgets import (
    QApplication,
    QFileDialog,
    QMainWindow,
    QMessageBox,
    QSplashScreen,
    QStyle,
)
from werkzeug.serving import make_server
class WorkerThread(QThread):
    result_signal = Signal()
    def __init__(self, data, s, port) -> None:
        super().__init__()
        self.data = data
        self.s = s
        self.port = port
    def run(self):
        self.app = create_app()
        logging.debug("WorkerThread: Flask App Created")
        configure_app(self.app, self.data, self.s, None)
        self.result_signal.emit()
        self.server = make_server(URL, self.port, self.app)
        self.server.serve_forever()
class MainWindow(QMainWindow):
    def __init__(self):
        super().__init__()
        self.port = get_port()
        self.worker_thread = None
        self.bar = self.menuBar()
        self.showMaximized()      
        self.setCentralWidget(self.browser)
        self.browser.setVisible(False)       
        file = self.bar.addMenu("File")
        # Open #########################
        _open = QAction(
            self.style().standardIcon(QStyle.StandardPixmap.SP_DialogOpenButton),
            "Open",
            self,
        )
        _open.setShortcut("Ctrl+O")
        file.addAction(_open)
        def trigger():
            options = QFileDialog.Options()
            data, _ = QFileDialog.getOpenFileName(self, "Open File", "", "Files (*.h5ad)", options = options)
            if data:
                spatial = os.path.dirname(data) + '/spatial'
                if self.worker_thread:
                    self.worker_thread.server.shutdown()
                    self.worker_thread.terminate()
                    self.worker_thread.wait()
                    self.browser.setVisible(False)
                    self.port = get_port()
                self.worker_thread = WorkerThread([data], [spatial], self.port)
                self.worker_thread.result_signal.connect(self.on_result)
                self.worker_thread.start()
                self.worker_thread.setPriority(QThread.Priority.LowestPriority)    
        _open.triggered.connect(trigger)
        file.addSeparator()
    def closeEvent(self, event: QEvent) -> None:
        if self.worker_thread:
            self.worker_thread.terminate()
        event.accept()
def is_port_in_use(port):
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as s: 
        return s.connect_ex(("localhost", port)) == 0 
def get_port():
    port = 5001
    while is_port_in_use(port):
        port += 1
        if port == 6000:
            exit(0)
    logging.info("Port: " + str(port))
    return port
def main():
    qt_app = QApplication([])
    QThread.currentThread().setPriority(QThread.Priority.HighestPriority)
    ui = MainWindow()
    ui.show()
    qt_app.exec()
if __name__ == "__main__":
    main()
```

**Comment by rokm** [comment]
> the software launches multiple times, initiating several processes in the background until the computer crashes.

Sounds like your application triggers the use of `multiprocessing` (or some other multi-processing framework) at some point, and you end up with endless spawn loop. Read https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#multi-processing and see if adding `multiprocessing.freeze_support()` solves the problem (you should probably add the call at the very top of your entry-point script, to avoid unnecessary Qt imports in the worker process).

I don't see any part that would directly use `multiprocessing`, but then again, you did not provide the code for `create_app`. So my guess would be it happens somewhere in there.

**Comment by yangmengace** [comment]
Hello, I have tried the method of multiprocessing.free_support() on the MacOS system. Although only one software window is opened, multiple processes will pop up in the background to occupy memory space. So this method does not solve the problem.
The following is the code of the create_app section:

def create_app():
    from flask import Flask, send_from_directory
    from flask_compress import Compress 

    app = Flask(__name__, static_folder=os.path.join(cirrocumulus.__path__[0], "client"), static_url_path="")

    app.config["SEND_FILE_MAX_AGE_DEFAULT"] = 0 

    @app.route("/")
    def root():
        '''返回客户端目录下的 index.html 文件'''
        return send_from_directory(
            os.path.abspath(os.path.join(app.root_path, "client")), "index.html"
            # "client", "index.html"
        )

    if bool(os.environ.get(CIRRO_COMPRESS, "true")):
        Compress(app)
    return app

**Comment by rokm** [comment]
> multiple processes will pop up in the background to occupy memory space.

How many processes are we talking here? Are they still crashing the computer, like the initial problem?

And what are the arguments that are passed to the executable in these background processes?

If `multiprocessing` is used, then there are bound to be worker subprocesses...
