### ISSUE TITLE
Building with Python 3.10.16 fails

### ISSUE THREAD

**Issue by thanhdxuan** [pyinstaller/pyinstaller#8912]
## Description of the issue
It's duplicated with #7692, happen with `3.10.16` again.
### Context information (for bug reports)

* Output of `pyinstaller --version`: ```5.13.2```
* Version of Python: 3.10.16 
* Platform: Linux 
* How you installed Python: use python docker image 
* Did you also try this on another platform? Does it work there?
**It's works on Windows x64**

### Stacktrace / full error message

```
[227] Module object for pyimod02_importers is NULL!
Traceback (most recent call last):
  File "PyInstaller/loader/pyimod02_importers.py", line 22, in <module>
  File "pathlib.py", line 14, in <module>
  File "urllib/parse.py", line 39, in <module>
ModuleNotFoundError: No module named 'ipaddress'
Traceback (most recent call last):
  File "PyInstaller/loader/pyiboot01_bootstrap.py", line 17, in <module>
ModuleNotFoundError: No module named 'pyimod02_importers'
[227] Failed to execute script 'pyiboot01_bootstrap' due to unhandled exception!
```

**Comment by rokm** [comment]
> Output of `pyinstaller --version`: `5.13.2`

PyInstaller 5.x is not supported anymore, so if you want to continue using it, either use it with python <= 3.10.15, or patch it yourself (i.e., extend [this part](https://github.com/pyinstaller/pyinstaller/blob/d1b6b520a017578a19e1cb9514752a4517755ee0/PyInstaller/compat.py#L661-L663) to python 3.10.16, or just include `ipaddress` regardless of python version).

**Comment by Diogo-Rossi** [comment]
Hello @rokm 

Just to be clear: is it sufficient to add this snippet to my code?

```python
from PyInstaller.compat import PY3_BASE_MODULES
PY3_BASE_MODULES.add('ipaddress')
```
