### ISSUE TITLE
Python 3.10.16 and python3.9.21 are broken, due to ipaddress import

### ISSUE THREAD

**Issue by jmrgibson** [pyinstaller/pyinstaller#8919]
The same issue as reported in https://github.com/pyinstaller/pyinstaller/issues/7692 is now present in 3.10.16 and 3.9.21. This is because python backported the change from 3.11 older branches

diffs for python3 versions
- https://github.com/python/cpython/compare/v3.10.15...v3.10.16
- https://github.com/python/cpython/compare/v3.9.20...v3.9.21

Specifically, would it be possible to get this fix ported to the 5.x branch?

The patch to fix this is below

```
diff --git a/PyInstaller/compat.py b/PyInstaller/compat.py
index 6bd3e4b0..d9ad1c1c 100644
--- a/PyInstaller/compat.py
+++ b/PyInstaller/compat.py
@@ -658,7 +658,7 @@ def importlib_load_source(name: str, pathname: str):
 if not is_py310:
     PY3_BASE_MODULES.add('_bootlocale')

-if sys.version_info >= (3, 11, 4):
+if sys.version_info >= (3, 11, 4) or sys.version_info >= (3, 10, 16) or sys.version_info >= (3, 9, 20):
     # required by loader/pymod02_importers.py -> pathlib -> urllib
     PY3_BASE_MODULES.add('ipaddress')
```

3.8 does not seem to have this issue.

**Comment by bwoodsend** [comment]
This doesn't affect anything after 9bc447f29bbcd164a64f2d5dd3d38ecbcabf9ea2. I really don't think it's fair for you to expect me to maintain two branches just so that you can defer keeping your dependencies up to date.

**Comment by jmrgibson** [comment]
> This doesn't affect anything after [9bc447f](https://github.com/pyinstaller/pyinstaller/commit/9bc447f29bbcd164a64f2d5dd3d38ecbcabf9ea2). I really don't think it's fair for you to expect me to maintain two branches just so that you can defer keeping your dependencies up to date.

Fair enough. Apologies if my report came across as demanding, it was a long day of debugging to find the eventual root cause.
