### ISSUE TITLE
Compiled executables behaving strangely

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#892]
**Original date**: 2014/04/23
**Original reporter**: *anonymous*

I'm encountering an extremely weird situation that I can't get my head around.

I have a small app that pings a website to check a version number, and downloads a file if the version doesn't match. The code imports python-requests (2.2.1) and wxPython (3.0.0.0), and I'm compiling using PyInstaller 2.1

If I name the file rlc-upd.py (compiled to rlc-upd.exe) everything works as expected.

If I name the file rlc-updater.py (compiled to rlc-updater.exe) the app asks for administrator permission.

Build system is Windows 7 64 bit, Python 2.7.6 32 bit.

I can work with the former name, but I'm curious to see if there's an explanation for this other than the name (which sounds like a conspiracy theory).

I've attached a slightly modified version of the code - I've scrubbed references to the website and program.

**Comment by htgoebel** [comment]
I'm closing this issue, because it was reported by anonymous and the attached code is gone with the old trac instance.
