### ISSUE TITLE
Unable to import '_imaging' from 'PIL'

### ISSUE THREAD

**Issue by LatosProject** [pyinstaller/pyinstaller#8926]
### Context information (for bug reports)

* Output of `pyinstaller --version`: 6.11.1
* Version of Python: 3.12.8
* Platform: Windows 11
* How you installed Python: python.org/downloads

**Steps to reproduce:**
* pyinstaller --noconfirm --noconsole --onefile --icon="C:\Windows\System32\cmd.exe" --name=main main.py

* Create a script "a"
  
      ...
      def replace_and_restart():
          current_user = os.getenv("USERNAME")
          bat_script = f"""
          @echo off
          timeout /t 3 >nul
          taskkill /f /im main.exe >nul 2>&1
          move /y "{TEMP_EXE_PATH}" "{EXE_PATH}" >nul
          start "" "{EXE_PATH}"
          del "%~f0"
          """
          try:
              bat_path = os.path.join(os.path.dirname(EXE_PATH), f"update_{int(time.time())}.bat")
              with open(bat_path, "w") as bat_file:
                  bat_file.write(bat_script)
              subprocess.Popen([bat_path], shell=True)
              sys.exit(0)
          except Exception:
              return None
      ...
  
* Create a script "b"
  
      from PIL import ImageGrab
      ...
      def upload_screenshot():
          try:
              screenshot = ImageGrab.grab()
              image_stream = BytesIO()
              screenshot.save(image_stream, format="PNG")
              image_stream.seek(0)
      ...
      def replace_and_restart():
          current_user = os.getenv("USERNAME")
          bat_script = f"""
          @echo off
          timeout /t 3 >nul
          taskkill /f /im main.exe >nul 2>&1
          move /y "{TEMP_EXE_PATH}" "{EXE_PATH}" >nul
          start "" "{EXE_PATH}"
          del "%~f0"
          """
          try:
              bat_path = os.path.join(os.path.dirname(EXE_PATH), f"update_{int(time.time())}.bat")
              with open(bat_path, "w") as bat_file:
                  bat_file.write(bat_script)
              subprocess.Popen([bat_path], shell=True)
              sys.exit(0)
          except Exception:
              return None
      ...
  
* There exist two programs, assuming program a (which has not imported PIL) and program b. When I update itself with the built-in function of program a, the program reports an error and crashes.
  
* The pyinstaller creates a file prefixed with _MEI in appdata/temp at startup. Then I imported the library PIL in the new version of the program, which was not available in the old version of the program. After the program is replaced, start launches the new version of the program with the expectation that it should create a temporary _MEI folder containing the PIL library. But the problem is that the new program started still uses the _MEI folder of the old version of the program which does not contain PIL. This problem does not occur if the new version of the program is started directly by double-clicking or cmd.
  

### Stacktrace / full error message

    Traceback (most recent call last):
      File "killerqueen\main.py", line 1, in <module>
      File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
      File "killerqueen\WebSocketClient.py", line 11, in <module>
      File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
      File "killerqueen\utils.py", line 23, in <module>
      File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
      File "PIL\ImageGrab.py", line 26, in <module>
      File "PyInstaller\loader\pyimod02_importers.py", line 384, in exec_module
      File "PIL\Image.py", line 97, in <module>
    ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\admin\AppData\Local\Temp\_MEI43482\PIL\__init__.pyc)

**Comment by rokm** [comment]
Sounds like you might want to read 

https://pyinstaller.org/en/stable/common-issues-and-pitfalls.html#using-sys-executable-to-spawn-subprocesses-that-outlive-the-application-process-implementing-application-restart

and try setting the `PYINSTALLER_RESET_ENVIRONMENT` environment variable as described there.
