### ISSUE TITLE
ImportError: DLL load failed while importing _gi in PyGObject on Windows with MSYS2

### ISSUE THREAD

**Issue by JunHeng234** [pyinstaller/pyinstaller#8931]
PS D:\VSS Programming> & C:/Users/User/AppData/Local/Programs/Python/Python313/python.exe "d:/VSS Programming/t.py"
Traceback (most recent call last):
  File "d:\VSS Programming\t.py", line 1, in <module>
    import gi
  File "C:\Users\User\AppData\Local\Programs\Python\Python313\Lib\site-packages\gi\__init__.py", line 40, in <module>
    from . import _gi
ImportError: DLL load failed while importing _gi: The specified module could not be found._

I am currently encountering an issue when trying to use PyGObject in my Python project. After installing PyGObject and its dependencies, I receive the following error when attempting to run my script: "ImportError: DLL load failed while importing _gi: The specified module could not be found." My environment details are as follows: I am using Python version 3.13, PyGObject version 3.50.0, and the GTK libraries installed via MSYS2 on Windows 10. I have taken several steps to resolve this issue, including installing MSYS2 and updating the package database, as well as installing the necessary GTK and GLib packages using pacman. I have verified that the correct DLL files exist in the MSYS2 directories and checked that my system PATH variable includes the directories where the GTK and GLib DLLs are located. However, I still face the import error when attempting to run my script, both in the command prompt and the MSYS2 terminal. Here’s a snippet of the code that causes the error:

import gi
from gi.repository import GLib

print("GLib version:", GLib.VERSION_STRING)

I am seeking assistance on whether there are specific DLLs that must be present in the PATH for PyGObject to function correctly, and what additional troubleshooting steps I can take to resolve this DLL load error. Any help or guidance on this issue would be greatly appreciated. Thank you!

**Comment by bwoodsend** [comment]
What does this have to do with PyInstaller?

**Comment by rokm** [comment]
You'll likely have more luck with msys2 python combined with msys2 pygobject and gtk, or with non-msys2 python (you seem to be using python.org) combined with non-msys2 gtk/pygobject (e.g., [gvsbuild](https://github.com/wingtk/gvsbuild)).

Either way, this has nothing to do with PyInstaller, and is thus off-topic here.
