### ISSUE TITLE
Missing resource handling docs

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#895]
**Original date**: 2014/04/29
**Original reporter**: *matej*

There are recommended ways of how to use resources in packages.
The cleanest seem to be the pkgutils or pkg_resources ways.

The [pyinstaller documentation mentions](http://www.pyinstaller.org/export/develop/project/doc/Manual.html?format=raw#adapting-to-being-frozen) the way of using the "frozen" attribute together with "__file__".
However, a closed issue indicates that the pkgutils way might already be supported. However, it is not documented.

I think that there are two major points the documentation lacks:

1. How to include files in the distribution? [I guess](http://pythonhosted.org/PyInstaller/#adding-files-to-the-bundle) that I should use the Tree in my spec file. However, how to do it in the proper way? What should be the prefix?

2. How to make the files visible by the [pkgutil](https://docs.python.org/2.7/library/pkgutil.html#pkgutil.get_data) module functions? I had no luck, so I have reverted to the freeze stuff, which works.

**Comment by tallforasmurf** [comment]
I will return to this after I check in the updated manual with "hooks" chapter this week.

**Comment by tallforasmurf** [comment]
Regarding use of pkgutil.get_data(), are we discussing compile-time use, for example as a way to construct the datas argument to Analysis in the spec file or perhaps the datas list in a hook? Or are we talking about run-time?

I am dubious about how this could work at run-time -- the python doc says it is like,

    d = os.path.dirname(sys.modules[package].__file__)
    data = open(os.path.join(d, resource), 'rb').read()

But does `sys.modules[package].__file__` have a useful value for a frozen module?

**Comment by tallforasmurf** [comment]
The updated doc has a more detailed section on "Adding Files to the Bundle" (http://pythonhosted.org/PyInstaller/#adding-files-to-the-bundle) and it links to the TOC/Tree discussion. So everything about how to add files to the bundle via the spec file is pretty well covered.

The OP seems to be concerned with locating files at run-time. The current doc says nothing about pkgutil (because I didn't know about it). I am going to do some simple testing to see if pkgutil.get_data() has any use in a bundled app. (Hypothesis: no.)

**Comment by htgoebel** [comment]
You may want to check out the test-case in `old-suite`. There should be examples.

**Comment by tallforasmurf** [comment]
Thank you, there were useful examples. Most usefully, they show that pkgutil is expected to work.

**Comment by tallforasmurf** [comment]
Commit #8a1ef63
