### ISSUE TITLE
Can you provide a fallback solution like packaging the entire virtual environment? The size doesn't matter as much as getting it to run!

### ISSUE THREAD

**Issue by caoyc** [pyinstaller/pyinstaller#8954]
使用pyinstaller打包程序已经占用到了整个项目用时的80%，结果依然没有任何异常提示的直接闪退，现在崩溃的不仅是程序还有我，只想要一个能跑的起来的程序，可不可以提供个类似直接将整个虚拟环境打包的兜底方案，相比于大小，能跑起来更重要！

Using PyInstaller to package the program takes up 80% of the total project time, yet there are no error messages and it crashes directly without any indication. Now, not only is the program crashing, but so am I. I just want an executable (.exe) that runs. Can you provide a fallback solution like packaging the entire virtual environment? The size doesn't matter as much as getting it to run!

**Comment by rokm** [comment]
>  Can you provide a fallback solution like packaging the entire virtual environment?

No.
