### ISSUE TITLE
--add-data not working

### ISSUE THREAD

**Issue by techvd** [pyinstaller/pyinstaller#8958]
## Description of the issue
The --add-data option doesn't seem to be working. I'm running pyinstaller using:

pyinstaller --add-data "resources:resources" main.py

The resources folder has some files, as well as subfolders such as images. These files are not being copied to the final dist location.

### Context information (for bug reports)

* Output of `pyinstaller --version`: ```6.11.1```
* Version of Python: 3.11.9
* Platform: Windows 11
* How you installed Python: conda
* Did you also try this on another platform? Does it work there?
Yes. Same problem on Ubuntu 22.04

### A minimal example program which shows the error

```
with open("resources/notes.txt", "r", encoding="utf-8") as f:
    lines = f.readlines()
    print(lines)
```

(with a small text files named notes.txt under resources folder)

### Stacktrace / full error message
```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
FileNotFoundError: [Errno 2] No such file or directory: 'resources/notes.txt'
[PYI-12520:ERROR] Failed to execute script 'main' due to unhandled exception!
```
### Additional Notes
When I run main.py in the directory directly, it works fine. I also tried pyinstaller with debug but don't see any information relevant to the resources being copied. But it does add this line to the spec file:
datas=[('resources', 'resources')],

I'm also not 100% if the files are literally expected to be copied to the dist folder or if they would be embedded into the exe. If it is the former, there is definitely no resources folder created in the destination folder.

**Comment by rokm** [comment]
> I'm also not 100% if the files are literally expected to be copied to the dist folder or if they would be embedded into the exe. If it is the former, there is definitely no resources folder created in the destination folder.

They should be copied into `dist/<name>/_internal/resources`.

And you should be referring to the resources using the absolute path, as described in [documentation](https://pyinstaller.org/en/stable/runtime-information.html#using-file):

```python
import os
with open(os.path.join(os.path.dirname(__file__), "resources/notes.txt"), "r", encoding="utf-8") as f:
    lines = f.readlines()
    print(lines)
```

**Comment by techvd** [comment]
thank you. my bad for missing that. I thought the code generally works without any changes but using __fie__ works. If the data is copied to the exe direction directly, that might be even better.

**Comment by rokm** [comment]
Actually, your code only works if you run it from the directory where the `main.py` is. If you move to any other directory and try to run it from there, it will fail with the same error. By using relative path, you are making unwarranted assumptions about current working directory.
