### ISSUE TITLE
Multipackages - make them clear

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#896]
**Original date**: 2014/04/29
**Original reporter**: *matej*

Let's consider a situation where you have as situation when there is a Python package that has two scripts.

By browsing the documentation and the source, I came to conclusion that I want multipackages.
There are several issues with them though:

- Contents of the spec file (ie MERGE, ANALYZE, ...) is not documented (at least in the latest 2.1 documentation).
- The spec file I have found in [1.6 docs](http://www.pyinstaller.org/export/develop/project/doc/Manual.html?format=raw#merge) is quite complicated. Eg why the dummy package at the beginning?
- The examples in the source don't make sense to me concept-wise: How can multipackages make sense if two of the packages are one-file only? The idea, as I understand, is that common dependencies end up in the same directory and the script executables end up there, too. Tests seem to concern [more cases](https://github.com/pyinstaller/pyinstaller/blob/develop/tests/multipackage/test_multipackage1.spec), which make me think that maybe I understand multipackages wrong.

**Comment by tallforasmurf** [comment]
I will return to this after I check in the updated manual with hooks chapter this week.

**Comment by tallforasmurf** [comment]
I believe the current doc addresses this properly, see http://pythonhosted.org/PyInstaller/#multipackage-bundles. Yes it would work for two, --one-file, scripts  (if it worked at all which waits on #1527). The OP is incorrect in saying "common dependencies end up in the same directory and the script executables end up there, too". The shared dependencies end up bundled in the first app. Other bundled apps have the abs. pathname of that app and open it as a file and use items from it. Correct?
