### ISSUE TITLE
Packaging libwayland* can break if user uses newer libraries

### ISSUE THREAD

**Issue by C0rn3j** [pyinstaller/pyinstaller#8963]
pyinstaller seems to collect libwayland*.so on Linux.

Which can cause issues like this one:

```
./Tauon Music Box: symbol lookup error: /lib/x86_64-linux-gnu/libEGL_mesa.so.0: undefined symbol: wl_display_create_queue_with_name
```  
*this is from a user running a pyinstaller image built on Ubuntu 24.04, on Ubuntu 24.10 - works for me on Arch Linux, I presume HW matters as I run Nvidia, so presumably no mesa involvement*

This was previously briefly talked about here - https://github.com/pyinstaller/pyinstaller/issues/7506

On Arch Linux, all those files are owned by the `wayland` library.

```
% pacman -Qo /usr/lib/libwayland-client.so /usr/lib/libwayland-cursor.so /usr/lib/libwayland-egl.so /usr/lib/libwayland-server.so
/usr/lib/libwayland-client.so is owned by wayland 1.23.1-1
/usr/lib/libwayland-cursor.so is owned by wayland 1.23.1-1
/usr/lib/libwayland-egl.so is owned by wayland 1.23.1-1
/usr/lib/libwayland-server.so is owned by wayland 1.23.1-1
```

Is there even a case where a user would be running a Wayland compositor without having these Wayland client libraries available on the host?

It seems to me that these should not be packaged by default, but maybe I am overlooking something.

**Comment by rokm** [comment]
> this is from a user running a pyinstaller image built on Ubuntu 24.04, on Ubuntu 24.10 - works for me on Arch Linux, I presume HW matters

HW and specific versions of components packaged by distributions.

> Is there even a case where a user would be running a Wayland compositor without having these Wayland client libraries available on the host?
> 
> It seems to me that these should not be packaged by default, but maybe I am overlooking something.

Feel free to open a PR that adds those libraries (perhaps a `libwayland-*.so` pattern) to [the exclusion list](https://github.com/pyinstaller/pyinstaller/blob/96314c327436bcaae922b568439ed95d57432a07/PyInstaller/depend/dylib.py#L182-L222).
