### ISSUE TITLE
Ampersand in folder name

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#899]
**Original date**: 2014/05/06
**Original reporter**: *anonymous*

I've reated a subfolder in my source dir.
So I've to use the %CD% variable to go in the subfolder and find my script.py file.

pyinstaller "%CD%\..\main.py"

It fails if my source dir contains a "&" in the name (ex.: "C:\my projects\AAA & BBB") and I call pyinstaller from a subfolder.
It works if I remove the ampersand ("C:\my projects\AAA BBB").

Error:
```
[...]
  File "c:\Python27\lib\site-packages\pyinstaller-2.1-py2.7.egg\PyInstaller\build.py", line 1873, in build
    execfile(spec)
  File "D:\Programming\Python\Projects\GPX & KML\PyInstaller\GPX .spec", line 6, in <module>
    runtime_hooks=None)
  File "c:\Python27\lib\site-packages\pyinstaller-2.1-py2.7.egg\PyInstaller\build.py", line 409, in __init__
    raise ValueError("script '%s' not found" % script)
ValueError: script 'D:\Programming\Python\Projects\GPX ' not found
```
It fails to create .spec file. It truncate the path on the "&" character and add .spec, in my case it has created a "GPX .spec" instead of "main.spec", Note the space after "GPX".

Thanks,
Alessandro

**Comment by htgoebel** [comment]
I strongly assume, this is problem is related to the shell. `&` is a typical shell meta-character and the effect would fit.
