### ISSUE TITLE
script frozen by pyinstaller cant run in paths containing characters in some other encodings

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#901]
**Original date**: 2014/05/08
**Original reporter**: *ikadog*

there is already a post here 'http://www.pyinstaller.org/ticket/824'
but for the version of 2.1, the solution 
## is available now
,by modifing the stb_to_utf8 and stb_from_utf8 to MultiByteToWideChar and WideCharToMultiByte in stb.h in the bootloader,and it works fine.
and here is it 'https://github.com/dkw72n/pyinstaller/tree/develop'
(thanks to http://hi.baidu.com/domhow/item/341817d1afd5a558ddf9bee9)
would you make the changes to the official version?

**Comment by htgoebel** [comment]
@codewarrior0 Is this your topic, too? Then please assign this issue to you. Thanks.

**Comment by codewarrior0** [comment]
Sure. I know what this is about, too. Sometimes, Windows filenames are stored in ARCHIVE_STATUS as utf-8 and sometimes as mbcs. I'm cleaning it up so it will only be utf-8 internally, and mbcs is only used when talking to Python.

**Comment by codewarrior0** [comment]
Fixed with ab5ab6fdcf160e0c5ecb341d33c9730faed67a37
