### ISSUE TITLE
_MEIXXXXX folder is not cleaned when the application is killed by the close button.

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#902]
**Original date**: 2014/05/08
**Original reporter**: _rocky9_

I made a console application for windows with pyinstaller and know a onefile application creates a temporary folder _MEIXXXXX which is removed when the application is correctly terminated.
If I terminate my application by Ctrl+C, the _MEI folder is cleaned.
But terminating the application by pushing the close button, the _MEI folder is not cleaned.
How can I fix this?

**Comment by JulioV** [comment]
I've found the same problem. I have a falcon web app and this is my main python script which boots up the server

```python
import threading
import webbrowser
import time
import sys
from marking_server import app
import waitress


def launch_browser():
    """Launches the app"""
    time.sleep(3)
    webbrowser.open("http://localhost:8000/static/index.html", new=0, autoraise=True)


if __name__ == "__main__":
    launch_thread = threading.Thread(target=launch_browser)
    launch_thread.start()
    PORT = sys.argv[1] if len(sys.argv) > 1 else 8000
    waitress.serve(app, port=PORT)
    launch_thread.join()
```

How should I handle the close action when the user uses the Close button on the CMD window? I'm using Windows 10
