### ISSUE TITLE
"import pydoc" in "fake-site.py" significantly increases the size of generated executables

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#907]
**Original date**: 2014/05/22
**Original reporter**: *bakery2k*

"import pydoc" was added to "fake-site.py" in [this commit](https://github.com/pyinstaller/pyinstaller/commit/67da6fb1b258cce7d30e852bdd46f23cd7ed76ee), to fix a low priority issue which seems only to affect embedded IPython. Unfortunately it significantly increases the size of all generated executables - sometimes by as as much as 50%.

For example, a simple "Hello World" script on my system (Windows, 32-bit Python, with UPX). Commenting out "import pydoc" reduces file sizes as follows:

Python 2.4: 1,686KB => 1,224KB
Python 2.5: 2,035KB => 1,303KB
Python 2.6: 2,707KB => 2,078KB
Python 2.7: 3,013KB => 2,328KB

Would it be possible to make "import pydoc" conditional in some way, so that it (and the associated size increase) is only included when necessary?

**Comment by htgoebel** [comment]
@matysek Can we close this iusse? For python 3 support the fake-site module will be dropped.
