### ISSUE TITLE
Crash after 5-10 seconds with ctypes

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#915]
**Original date**: 2014/06/16
**Original reporter**: *funkzy*

Hi,

I'm using PyInstaller 2.1 on OS X 10.9.3, using MacPorts installed python 2.7.

I am experiencing a crash with the below test, only on the packaged application - running this under the Python interpreter runs forever as expected.

Repro code:

```
import ctypes
import time

# No crash if commented:
libSystem = ctypes.CDLL('libSystem.dylib', use_errno=True)

try:
    while True:
        time.sleep(20)
except (KeyboardInterrupt, SystemExit):
    print 'exiting'
    sys.exit(0)
```

I am running this via terminal. Result:
$ time ./crash_test

real	0m9.934s
user	0m0.034s
sys	0m0.020s

It typically takes 5-10 seconds to crash.

If I comment out the line that calls CDLL, there is no crash with the compiled application.

My spec file is as such:

```
# -*- mode: python -*-
a = Analysis(['crash_test.py'],
             pathex=['/Users/jeff/python_projects/soundsync'],
             hiddenimports=[],
             hookspath=None,
             runtime_hooks=None)
pyz = PYZ(a.pure)
exe = EXE(pyz,
          a.scripts,
          exclude_binaries=True,
          name='crash_test',
          debug=False,
          strip=None,
          upx=True,
          console=False )
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=None,
               upx=True,
               name='crash_test')
app = BUNDLE(coll,
             name='crash_test.app',
             icon=None)
```

Any help would be appreciated - thanks!

**Comment by matysek** [comment]
I just tested the code example and it  works for me with latest dev version. Closing.
