### ISSUE TITLE
Hook for collecting files for PyEnchant (OS X)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#967]
**Original date**: 2007/04/28
**Original reporter**: *anonymous*

> I've added PyEnchant-1.3.0 to my program and cannot get PyInstaller
> 1.3 to package it.  PyEnchant stores its dictionaries in C:
> \Python24\Lib\site-packages\enchant\share\enchant\myspell\.  The files
> in here are plain text files: en_US.dic, en_US.aff, etc. ...

I finally found what I need to do.  For the record, from
http://sourceforge.net/mailarchive/forum.php?thread_name=45346C4B.507...
"You need to copy both the "share" and "lib" dirs from the enchant
site-packages directory nto the dir of the exe. "share" contains the
dictionaries themselves, while "lib" contains the enchant myspell
plugin."

And Giovanni Bajo wrote:

OK. That can be taken care of using a setup program like InnoSetup.

Anyway, I would like this to be fixed automatically by PyInstaller.
There is much infrastructure in place to pack trees of data files into
the executable, unpack automatically them at startup, and let the
package find them. This is the way the Tkinter support works, for instance.

Alas, that support is currently hardcoded for Tkinter. It would have to
be generalized, so that one can write something like an extended import
hook to handle that. It's not that hard to do, but I don't have time
right now to do it.

But I would appreciate if you could open a ticket on the website
reporting the exact problem and the findings you reported on the mailing
list. This will make sure I won't forget about this, and I'll eventually
have this fixed.

**Comment by htgoebel** [comment]
Post-boning features to milestone 3.1

**Comment by matysek** [comment]
This is actually implemented I just wanted to add small improvements.

**Comment by matysek** [comment]
I did a redesign of the hook and simplified it.
