### ISSUE TITLE
PyInstaller can't freeze scripts importing the "kiwi" library

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#970]
**Original date**: 2007/07/21
**Original reporter**: _anonymous_

The line "import kiwi" in a script makes PyInstaller generate a unusable executable.

For every detail (including PyInstaller warnings), and for suggestions about fixing the problem, see the thread "PyInstaller e Kiwi" on it.comp.lang.python.

Regards.

**Comment by htgoebel** [comment]
New news in this for nearly three year. closing. If you feel this is still an issue with the current release, please open a brand new issue.
