### ISSUE TITLE
running pyinstaller from a  python script is unecessarily hard!

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#972]
**Original date**: 2007/09/07
**Original reporter**: _anonymous_

I have a build script which is written in python. I want to run Pyinstaller from there. This should be easy as PyInstaller is a python program. However, I'm finding that it is much harder than I thought it would be, mainly because of the reliance on globals and the assumption that the code will be run from a command line and have the working directory be where Build.py/Makespec.py is (it uses this to locate the dat files).

I realise I can workaround this by running the command directly, but it would be _very_ nice to just call the build and Makespec functions directly from my python script (maybe just telling it where to find the dat files). 

This is an enhancement request; otherwise I am VERY happy with the code!! :)
P.S. It would be excellent if you could get this integrated into the Python Standard Library..

Best Regards, Tushar.

**Comment by alphaCTzo7G** [comment]
There doesnt seem to be a `./pyinstaller.py` file in the top directory. 

At this point, is it possible to import `pyinstaller` and create the `.exe` file without resorting to `os.system` etc?

**Comment by htgoebel** [comment]
The script ./pyinstaller.py is gone indeed. Please use `PyInstaller.__main__.run()`.

**Comment by bittner** [comment]
This doesn't seem to be mentioned in the documentation anywhere. Is this correct?

I believe it should be mentioned in or at the end of the [Usage chapter](https://pyinstaller.readthedocs.io/en/stable/usage.html).
