### ISSUE TITLE
CrossCompiling (Win Exes from Linux)

### ISSUE THREAD

**Issue by pyinstaller-tickets-migration** [pyinstaller/pyinstaller#984]
**Original date**: 2008/06/08
**Original reporter**: _anonymous_

This is probably one of the **most wanted** features.[[br]]
It would be surely a great idea to creates exes from Linux (and maybe other *nix).
#### How?

Something like the thing I' talking about is already possible, it has been implemented in IronPython ([English how-to](http://66.102.9.104/translate_c?hl=it&sl=it&tl=en&u=http://www.python-it.org/node/150), [Italian how-to](http://www.python-it.org/node/150)).
[[br]]
It is also possible to crosscompile files using Wine ([english how-to](http://66.102.9.104/translate_c?hl=it&sl=it&tl=en&u=http://www.python-it.org/node/167),[italian how-to](http://www.python-it.org/node/167)) and this one can be the right solution, using a method like the one used to ship [Ies4Linux](http://www.tatanka.com.br/ies4linux/page/How_does_IEs_4_Linux_work).

**Comment by ericoporto** [comment]
Why is this closed?

**Comment by htgoebel** [comment]
Because we will not implement it, see the [FAQ](https://github.com/pyinstaller/pyinstaller/wiki/FAQ).
